### ISSUE TITLE
Specify grid dimensions with an enum

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1000]
If we don't support more than two dimensions, then it should take an enum.

**Comment by bryevdv** [comment]
I think we are agreed that an enum would be a nice improvement. We nee do make it happen in a way that provide a deprecation path. Changing this to a feature issue.

**Comment by mattpap** [comment]
I started working on this thinking it should be quick and easy, but a lot of code depend on `dimension` being an integer, so there will be actually a lot of changes. Postponing after 0.8.

**Comment by bryevdv** [comment]
@mattpap I would be in favor of marking this `wontfix` and closing at this point. This needs to happen in this release cycle (for a deprecation cycle before 1.0) and it just does not seem like a high enough priority to bother.
