### ISSUE TITLE
New way to export_png in bokeh 2.0 creates issues in Ubuntu WSL

### ISSUE THREAD

**Issue by michael-imbeault** [bokeh/bokeh#10014]
So apparently there was a switch from PhantomJS to using Firefox + geckodriver / Chromium + chromedriver for the export_png functionality in versions following 1.4.

All good in theory, but it doesn't work in Ubuntu 20.04 when installed through WSL (Windows Subsystem for Linux - Windows 10).

Even basic plotting examples (such as https://docs.bokeh.org/en/latest/docs/gallery/ridgeplot.html) crash at the save stage (using export_png(p, filename="test.png")), outputting:

"Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'."

Now both Firefox and geckodriver are installed and in PATH (tested calling them from home dir).

However, Firefox when launched directly crashes, a known issue in WSL1 (https://bugzilla.mozilla.org/show_bug.cgi?id=1611787). Probably why Bokeh 'cant find it'. Same with Chromium-browser, not compatible with WSL1 for other reasons.

As of now, I downgraded back to Bokeh 1.4.0 / PhantomJS and everything is working again.

Can you confirm that there is no way to save PNGs in Bokeh 2.0+ using WSL? A lot of developers have similar setups, its not a common one but definitively not an edge case.

**Comment by mattpap** [comment]
It still may be possible to export images with phantomjs (though I didn't test this), by using:
```py
from selenium import webdriver                                                                                                       
from bokeh.io.export import get_screenshot_as_png
from bokeh.resources import INLINE_LEGACY
driver = webdriver.PhantomJS(executable_path="phantomjs")
get_screenshot_as_png(plot, driver=driver, resources=INLINE_LEGACY)
```
phantomjs can be installed with `npm install -g phantomjs-prebuilt`. Note that selenium's support for phantomjs is deprecated, and I wouldn't run any untrusted JavaScript there (treat it as if there was no sandbox, which may fine in a container).

**Comment by bryevdv** [comment]
@michael-imbeault And just to echo what @mattpap with more detail, the Selenium project has already removed all support for phantomjs in 4.0 alpha releases:

https://github.com/SeleniumHQ/selenium/blob/b5dbffc7d27b915204691def5c1f29141fb9a0a5/rb/CHANGES#L70-L71

There's definitely nothing we can do about that. So slightly longer term, everyone will have to find ways to move on from phantomjs, regardless.

**Comment by michael-imbeault** [comment]
Great, thanks for the tip. WSL2 is just around the corner (a few weeks for general availability) and should allow for more compatibility, so probably a short term problem.
