### ISSUE TITLE
What happened to mpl.to_bokeh ? [FEATURE]

### ISSUE THREAD

**Issue by cuspime** [bokeh/bokeh#10019]
In previous versions there was a package to deal with other libraries like matplot and seaborn ([see here](http://docs.bokeh.org/en/0.11.1/docs/user_guide/compat.html))

What happened with it and how can I embed a Seaborn plot in a bokeh layout??

**Comment by bryevdv** [comment]
@cuspime `mpl.to_bokeh` was deprecated more than three years (two major releases) ago, and subsequently removed. We made several public announcements along the way, and also added explicit deprecation warnings for some time. The initial implementation of MPL emulation relied on a third-party library `mplexporter` that itself was eventually abandoned, and which also relied heavily on private MPL libraries. It was also hugely incomplete, and as a result `mpl.to_bokeh` only barely worked for a fraction of MPL (and when it did at all, the results were often bad). It was unsupportable and unmaintainable as it was, and unfortunately not something we had resources to take ownership of.

**Comment by bryevdv** [comment]
I should add, there was briefly hope that [MEP 25](https://github.com/matplotlib/matplotlib/wiki/MEP25) would provide a way for other libraries to integrate with MPL in a defined, maintained way. But as you can see no work has been done on that in more than six years. The abandonment of MEP 25 was the final nail in the coffin for Bokeh's MPL support.

**Comment by bryevdv** [comment]
Lastly will just mention that if you want assistance using native Bokeh APIs, the Project Discourse is a great place to ask for help: https://discourse.bokeh.org/

**Comment by jbednar** [comment]
BTW, there are a couple of currently supported alternatives:

- The [Panel](https://panel.holoviz.org) library (built on Bokeh) can return a Bokeh model from a Seaborn or other Matplotlib plot, which you can then embed in a  Bokeh layout.  It works differently from the old APIs that translate into Bokeh primitives; instead it's just a way of displaying an actual Seaborn plot in a Bokeh Server app or with Bokeh plots and widgets in a notebook.
- The [hvPlot](https://hvplot.holoviz.org) and the [HoloViews](https://holoviews.org) library on which it was built duplicate most of what Seaborn does (and a lot that it does not), returning native Bokeh models and layouts that provide full interactivity.
