### ISSUE TITLE
[BUG] Dropdown widget evet rests the Y-axis on the second plot.

### ISSUE THREAD

**Issue by mbilyanov** [bokeh/bokeh#10013]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh version: BokehJS 1.3.4
Python version 3.7
OS version: Linux Ubuntu 18.00
Chrome version: Version 81.0.4044.138 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior

The expected behaviour is the Y-scale to remain unchanged after the update is triggered.

The observed behavior is that the Y-scale for the second (bottom) plot is reset. Where there is not reset for the Y-scale of the top plot.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

# My update setup:
mavg = Select(title='Moving Average', value=SMA, options=[SMA, EMA])
mavg.on_change('value', lambda attr, old, new: update(task='mavg'))

# The callbacks that handle the Y-scale fitting as we drag through a zoomed region:

callback_top = CustomJS(args={'y_range': p1.y_range, 'source': source}, code='''
    clearTimeout(window._autoscale_timeout_top_plot);

    var Index = source.data.time,
        Low = source.data.candle_bound_min,
        High = source.data.candle_bound_max,
        start = cb_obj.start,
        end = cb_obj.end,
        min = Infinity,
        max = -Infinity;

    for (var i=0; i < Index.length; ++i) {
        if (start <= Index[i] && Index[i] <= end) {
            max = Math.max(High[i], max);
            min = Math.min(Low[i], min);
        }
    }

    console.log(`[top_plot] min: ${min}, max: ${max}`);
    //console.log(`index: ${Index}`);
    console.log(`[top_plot] start: ${start}, end: ${end}`);

    var pad = (max - min) * .05;

    window._autoscale_timeout_top_plot = setTimeout(function() {
        y_range.start = min - pad;
        y_range.end = max + pad;
    });
''')

callback_bottom = CustomJS(args={'y_range': p2.y_range, 'source': source}, code='''
    clearTimeout(window._autoscale_timeout_bottom_plot);

    var Index = source.data.time,
        Low = source.data.macd_bound_min,
        High = source.data.macd_bound_max,
        start = cb_obj.start,
        end = cb_obj.end,
        min = Infinity,
        max = -Infinity;

    for (var i=0; i < Index.length; ++i) {
        if (start <= Index[i] && Index[i] <= end) {
            max = Math.max(High[i], max);
            min = Math.min(Low[i], min);
        }
    }

    console.log(`[bottom_plot] min: ${min}, max: ${max}`);
    //console.log(`index: ${Index}`);
    console.log(`[bottom_plot] start: ${start}, end: ${end}`);

    var pad = (max - min) * .05;

    window._autoscale_timeout_bottom_plot = setTimeout(function() {
        y_range.start = min - pad;
        y_range.end = max + pad;
    });
''')

```

#### Stack traceback and/or browser JavaScript console output

These are my own debugging console logs:

[top_plot] min: 7839.6, max: 8521.3
[top_plot] start: 1589191881288.17, end: 1589217792945.353
[bottom_plot] min: -31.745717504226867, max: 107.5251719439384
[bottom_plot] start: 1589191881288.17, end: 1589217792945.353

#### Screenshots or screencasts of the bug in action

![candlesticks3](https://user-images.githubusercontent.com/48017279/81698765-5a3ceb80-945e-11ea-86e4-90042ac741c3.gif)

**Comment by bryevdv** [comment]
I notice you have also logged a support question on the Discourse. I am going to go ahead and close this issue until it is determined whether there is a bug or whether it is a usage issue.

**Comment by mbilyanov** [comment]
Sure. Thank you.
