### ISSUE TITLE
[FEATURE] More default theme for Bokeh

### ISSUE THREAD

**Issue by Cheukting** [bokeh/bokeh#10028]
During the PyCon Hatchery Mentories sprint, it has been mentioned that currently There's only 3 default theme and it would be great to have more.

**Comment by bryevdv** [comment]
Some additional built in themes would be fantastic to have! Some off-the-cuff ideas:

* approximations of other common/popular tool styles (e.g "ggplot")
* the "minimal" themes are not actually so minimal to my eye, maybe some versions even more reduced axes, grids, ticks, etc (not sure what to call)

**Comment by bryevdv** [comment]
Re-opening to leave this as an evergreen call for possible new themes.

**Comment by ashwani-rathee** [comment]
![](https://i.imgur.com/W9a5VGc.png)
![](https://i.imgur.com/8yAb6au.png)
These two themes or something similar to these would be a good idea to create a PR,is it??

**Comment by bryevdv** [comment]
I'm going to go ahead and close this. We are generally always happy to consider new themes form users, on a case-by-case basis, so I am not sure what purpose this issue serves at this point.
