### ISSUE TITLE
[BUG] DatePicker.disabled doesn't always work

### ISSUE THREAD

**Issue by zeknafar** [bokeh/bokeh#10022]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.0.2
python 3.7.4 (Anaconda)
Windows 10
Reproduced with FireFox 76.0.1 and Microsoft Edge 81.0.416.72

#### Description of expected behavior and the observed behavior
From the provided code, I would expect that clicking the button and setting dp.disabled to True or False would change the disabled state of the DatePicker widget in the webui. The observed behavior is clicking the button does not change the disabled state of the DatePicker widget in the webui.

#### Complete, minimal, self-contained example code that reproduces the issue
The following example creates a DatePicker widget and button. The button is supposed to toggle the disabled state of the DatePicker:
```
from bokeh.plotting import curdoc
from bokeh.models import DatePicker, Button
from bokeh.layouts import column
dp = DatePicker(title='Date')
dp.disabled = True
b = Button(label='press')
def callback():
    dp.disabled = not dp.disabled
    print(dp.disabled)
b.on_click(callback)
curdoc().add_root(column(dp,b))
```

#### Stack traceback and/or browser JavaScript console output
I don't see any errors in the FireFox web console.

**Comment by bryevdv** [comment]
@zeknafar I can't reproduce any problem at all on OSX with Safari, Chrome, or FF. 

Just o be clear, you are runnign this as a bokeh server app, i.e. 
```
bokeh serve --show app.py
```
correct? And not trying to run it as a simple python script?

**Comment by bryevdv** [comment]
Well, I can repro an issue on a windows VM (@mattpap can you check on linux?)

**Comment by zeknafar** [comment]
I used the bokeh serve command with the sample code for testing. 

Tonight I also tested using chrome 81.0.4044.138 and the DatePicker.disabled property in the callback function doesn't work. Let me know if there are any other windows browsers that would be useful for me to test with. I currently don't have access to a linux machine for testing.
