### ISSUE TITLE
[FEATURE] Allow named columns to be used in EditTools

### ISSUE THREAD

**Issue by scaine1** [bokeh/bokeh#10040]
In the examples below I will be using the LineEditTool developed in feature branch #9968 

However I  believe that the issue/feature I will describe applies generally to all the EditTools and could potentially be implemented on the abstract base class.

My problem is that there appears to be only two methods of successfully getting an edit tool to work. 

**1)  passing in data directly to the p.line method as arguments as shown in the example below**

```
from datetime import datetime, timedelta
from bokeh.models import ColumnDataSource, LineEditTool, Circle
from bokeh.plotting import figure
from bokeh.io import curdoc, show


p = figure(
    y_range=(0, 10),
    x_axis_type="datetime",
    width=400,
    height=400,
    title="TimeSeries Edit Tool",
)

dates = [datetime(2020, 5, 1) + timedelta(days=x) for x in [1, 2, 3, 4, 5, 6, 7, 8, 9]]
l1 = p.line(
    dates,
    [1, 2, 3, 4, 5, 4, 3, 2, 1],
    color="green",
    alpha=1.0,
    line_width=5,
)

c1 = p.circle([], [], size=10, color="red")
ledit_tool = LineEditTool(renderers=[l1], intersection_renderer=c1, dimensions="height")
p.add_tools(ledit_tool)

curdoc().add_root(p)
show(p)
```

**2) creating CDS where the columns MUST be named x and y or else the edit tool does not function.**

```
from datetime import datetime, timedelta
from bokeh.models import ColumnDataSource, LineEditTool, Circle
from bokeh.plotting import figure
from bokeh.io import curdoc, show


p = figure(
    y_range=(0, 10),
    x_axis_type="datetime",
    width=400,
    height=400,
    title="TimeSeries Edit Tool",
)

dates = [datetime(2020, 5, 1) + timedelta(days=x) for x in [1, 2, 3, 4, 5, 6, 7, 8, 9]]
cds = ColumnDataSource({"x": dates, "y":[1, 2, 3, 4, 5, 4, 3, 2, 1]})
l1 = p.line(
    x="x",
    y="y",
    source=cds,
    color="green",
    alpha=1.0,
    line_width=5,
)

c1 = p.circle([], [], size=10, color="red")
ledit_tool = LineEditTool(renderers=[l1], intersection_renderer=c1, dimensions="height")
p.add_tools(ledit_tool)

curdoc().add_root(p)
show(p)
```

Looking at the doc strings for the edit tools it seems like the necessity of using **x** and **y** is known.
```
The tool will modify the columns on the data source corresponding to the 
``x`` and ``y`` values of the glyph. Any additional columns in the data
source will be padded with the declared``empty_value``, when adding a new
point.
```

I would think that generally when people are making complex interactive dashboards they will be using the CDS option and it is highly likely they are going to want to be using their own names for the columns rather than forced to use x and y so that the edit tools work.

This is certainly true in my case. While I have gotten my code to work using the **x** and **y** restriction, it did force changes that made the code less readable and generally worse off.

**3) Proposed 3rd option where CDS with custom named columns can be used** 

I think a 3rd option would be useful where the CDS can be used and the edit tool takes additional keyword arguments allow the names of the columns to be passed.

If this can be implemented on the EditTool base class it may not be a large change but could end up having quite a large effect.

Below is the code below that I would like to see working but currently does not.

```
from datetime import datetime, timedelta
from bokeh.models import ColumnDataSource, LineEditTool, Circle
from bokeh.plotting import figure
from bokeh.io import curdoc, show


p = figure(
    y_range=(0, 10),
    x_axis_type="datetime",
    width=400,
    height=400,
    title="TimeSeries Edit Tool",
)

dates = [datetime(2020, 5, 1) + timedelta(days=x) for x in [1, 2, 3, 4, 5, 6, 7, 8, 9]]
cds = ColumnDataSource({"datetime": dates, "prediction":[1, 2, 3, 4, 5, 4, 3, 2, 1]})
l1 = p.line(
    x="datetime",
    y="prediction",
    source=cds,
    color="green",
    alpha=1.0,
    line_width=5,
)

c1 = p.circle([], [], size=10, color="red")
ledit_tool = LineEditTool(x="datetime", y="prediction", renderers=[l1],
        intersection_renderer=c1, dimensions="height")
p.add_tools(ledit_tool)

curdoc().add_root(p)
show(p)
```

**Comment by bryevdv** [comment]
The existing tools always use whatever field is configured on the glyph that they control, which is the simplest and most correct thing to do, and also places the least burden on users. You can see that in action e.g. in the point draw tool here:

https://github.com/bokeh/bokeh/blob/81998986b6850b0c8c6610e7d7f27bab4ea08ae7/bokehjs/src/lib/models/tools/edit/point_draw_tool.ts#L23-L30

All the existing tools correctly use this kind of indirection to obtain the CDS column name from the glyph. But at a glance, the new line edit tool seems to get in to trouble here:

https://github.com/bokeh/bokeh/blob/81998986b6850b0c8c6610e7d7f27bab4ea08ae7/bokehjs/src/lib/models/tools/edit/line_edit_tool.ts#L50-L53

And possibly other places, I stopped scanning when I saw that. In any case the new tool should be updated to follow the pattern of the previous tool. @scaine1 if you are able to, a PR would certainly be appreciated.

**Comment by scaine1** [comment]
Ahhh! that's what that part of the code was for :)
Not surprising the issue was caused by code I wrote and my lack of bokeh knowledge.

Yep I will fix and make a PR.

**Comment by scaine1** [comment]
I have made the changes that fix the issue.

However before I make the PR I thought I would check one part of the code that I am unsure of. 

In the else section of the code I have written the way I would naively code it.

However, I have included as a comment al alternative method that I saw the the PolyEditTool.

Is there any difference between these two approaches? is one better than the other?




```
    const [xkey, ykey] = [glyph.x.field, glyph.y.field]

    let x: number[]
    let y: number[]

    if (xkey) {
      x = cds.get_array(xkey)
    }
    else {
      x = Array.from(cds.data.x)
      // I could do the line below
      // x = glyph.x.value
    }
    if (ykey) {
      y = cds.get_array(ykey)
    }
    else {
      y = Array.from(cds.data.y)
      // I could do the line below
      //y = glyph.y.value
    }
```

**Comment by scaine1** [comment]
This might be a related issue.

When the LineEditTool is used to modify a datetime axis the return type is different.

Initially I created a ColumnDataSource with the x-axis being a series of datetime objects.

When the LineEditTool is used to modify the y-values the x-axis values are converted from datetime objects to string representations of the date in milliseconds since epoch.

I assume this is a consequence of the serialisation between the JavaScript side and the python side.
 
However, is this result expected or should the values be converted back in to a datetime object on the python side. 


initially the cds values are
```
{'datetime': [datetime.datetime(2020, 5, 2, 0, 0), datetime.datetime(2020, 5, 3, 0, 0), datetime.datetime(2020, 5, 4, 0, 0), datetime.datetime(2020, 5, 5, 0, 0), datetime.datetime(2020, 5, 6, 0, 0), datetime.datetime(2020, 5, 7, 0, 0), datetime.datetime(2020, 5, 8, 0, 0), datetime.datetime(2020, 5, 9, 0, 0), datetime.datetime(2020, 5, 10, 0, 0)], 'prediction': [2, 2, 2, 2, 2, 2, 2, 2, 2]}
```
after the use of the LineEditTool the values are
```
{'datetime': [1588377600000, 1588464000000, 1588550400000, 1588636800000, 1588723200000, 1588809600000, 1588896000000, 1588982400000, 1589068800000], 'prediction': [2, 2, 2, 2, 2, 4.097701149425287, 2, 2, 2], 'prediction1': [2, 2, 2, 2, 2, 4.097701149425287, 2, 2, 2]}
```

<details>
<summary> The code here highlights the issue. </summary>

```
from datetime import datetime, timedelta
from bokeh.models import ColumnDataSource, DataTable, DateFormatter, LineEditTool, NumberFormatter, Row, TableColumn, Circle
from bokeh.plotting import figure, output_file, show
from bokeh.io import curdoc, show


p = figure(
    y_range=(0, 10),
    x_axis_type="datetime",
    width=400,
    height=400,
    title="Linked with table"
)

dates = [datetime(2020, 5, 1) + timedelta(days=x) for x in [1, 2, 3, 4, 5, 6, 7, 8, 9]]

cds = ColumnDataSource({
    "datetime": dates,
    "prediction": [2, 2, 2, 2, 2, 2, 2, 2, 2],
    })


# line part
l1 = p.line(
    "datetime",
    "prediction",
    source=cds,
    color="black",
    alpha=1.0,
    line_width=5,
)

cds_c1 = ColumnDataSource({"datetime":[], "prediction1":[]})
c1 = Circle(x="datetime", y="prediction1", size=10, fill_color="red")
c1_rend = p.add_glyph(cds_c1, c1)
ledit_tool = LineEditTool(renderers=[l1], intersection_renderer=c1_rend, dimensions="height")
p.add_tools(ledit_tool)

# table part below

date_col = TableColumn(field="datetime", title="Datetime", formatter=DateFormatter())
pred_col = TableColumn(field="prediction", title="Prediction", formatter=NumberFormatter(format="0.0"))

def handler(attr, old, new):
    print(cds.data)

tbl = DataTable(
    source=cds,
    columns=[date_col, pred_col],
    width=400,
    height=400,
    editable=True
    )

print(cds.data)

cds.on_change('data', handler)
curdoc().add_root(Row(p, tbl))
show(p)
```
</details>

**Comment by bryevdv** [comment]
@scaine1 re: datetimes, the actual underlying type for datetimes is "milliseconds-since-epoch" and that is what everything is going to eventually end up as. For standalone content it's not really a concern, but in the server case where things can "come back" it can definitely be surprising. I am not sure we can do much about it though, in the "plain Python list" case. (I think numpy datetime arrays would function better)

re: `Array.from` I am fairly sure that is to accommodate cases when the CDS column is a typed array and not a simple `Array` since `let x: number[]` is going to only expect a simple `Array`, not a typed Array. Maybe it would be possible to do without this copy (e.g. with a different type declaration) but I am not sure offhand. cc @mattpap @philippjfr   For now I would say jsut submit a PR that emulates the existing tools.

**Comment by scaine1** [comment]
I made my PR but I suspect I may have done something wrong. I see there are merge conflicts. 

I thought I got everything up to date by doing a **git fetch upstream** then rebasing from master.. but I must have missed something

**Comment by scaine1** [comment]
Sorry I was quite confused.  I wasn't quite aware that the changes were already in the master branch. 
For some reason I thought they were still kept on a seperate branch  as part of the bokeh repository.

I pulled down the latest master and added just my bug fix. 

Thanks for your patience and guidance.
