### ISSUE TITLE
Javascript Error: property Grid.axis wasn't declared

### ISSUE THREAD

**Issue by sbonaretti** [bokeh/bokeh#10046]
Hi, 

I have just installed bokeh 2.0.2 with `pip install bokeh`. 

When I run: 
```
from bokeh.io import output_notebook
output_notebook()
```
either it takes a long time (message: `Loading BokehJS`), or I get `BokehJS 1.2.0 successfully loaded.`, but from my understanding it should load a more recent version

If I run a simple visualization taken from an example, I get: 
`Javascript Error: property Grid.axis wasn't declared`

Any suggestions on how I can get started with bokeh?
Thanks!!!

**Comment by bryevdv** [comment]
Hi @sbonaretti This is going to be some local configuration issue. Happy to discuss, but the appropriate venue is the Project Discourse, not the issue tracker. Can you open a topic there, and also please include the output of `import bokeh; bokeh.__version__` in the notebook. 

https://discourse.bokeh.org/

**Comment by sbonaretti** [comment]
Done! Thanks!

**Comment by dynexcel-ddc1** [comment]
@sbonaretti How did you solve the issue? I am facing same problem..Can you discuss the solution please.

**Comment by yaseenjamii814** [comment]
@sbonaretti How did you solve the issue? I am facing same problem..Can you discuss the solution please.

**Comment by JonathanAldridge** [comment]
For anyone else who runs across this.  When I got this, it was due to a mismatch in the Bokeh PYTHON version and the Bokeh Javascript library version.  (I was running a new version of Python/Bokeh, but was still embedding the graph into an old page that was loading an old Bokeh Javascript library.)
