### ISSUE TITLE
Specify custom tile providers when working with maps

### ISSUE THREAD

**Issue by harabat** [bokeh/bokeh#10057]
**Is your feature request related to a problem? Please describe.**
Currently, Bokeh only contains a selection of 10 tile providers to work with when making maps. Many free tile providers exist: being able to generate maps from custom tilesets would be welcome. 

**Describe the solution you'd like**
Enable `get_providers()` in `tile_providers.py` to accept custom tilesets. 

**Describe alternatives you've considered**
No alternative solutions exist within Bokeh, so someone with the issue above would have to take to libraries like folium, Plotly, etc, but it is stated in the documentation that Bokeh aims to add more support for working with maps. 

**Additional context**
Free providers are listed [here](http://leaflet-extras.github.io/leaflet-providers/preview/). I have a PR ready that implements my solution, but I had to do a thing in a hacky way, not an issue, works but could be more elegant. 

An illustration:
```
tile_provider = get_provider(
    provider='https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.{ext}',
    attr='Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
)

p = figure(x_range=(-2000000, 6000000), y_range=(-1000000, 7000000),
           x_axis_type="mercator", y_axis_type="mercator", width=500, height=500)
p.add_tile(tile_provider)

show(p)
```
![Stament Watercolor][0]

[0]: https://i.stack.imgur.com/R2Bti.png

**Comment by philippjfr** [comment]
You can already define custom tiles:

```python
from bokeh.models import MercatorTileSource, TileSource
MercatorTileSource(
    url='http://tile.stamen.com/watercolor/{Z}/{X}/{Y}.jpg',
    attribution='Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
)
```

**Comment by bryevdv** [comment]
@harabat You absolutely can do this right now by configuring your own `WMTSTileSource` directly, and passing that to `add_tile`. If you have more questions about how to do that, the appropriate venue for support/help desk question is the Project Discourse:

https://discourse.bokeh.org/

**Comment by harabat** [comment]
Didn't know that, cheers. Maybe it would make sense to add this information to the [docs](https://docs.bokeh.org/en/latest/docs/user_guide/geo.html) and to `add_tile()`'s docstring.

**Comment by harabat** [comment]
> Didn't know that, cheers. Maybe it would make sense to add this information to the [docs](https://docs.bokeh.org/en/latest/docs/user_guide/geo.html) and to `add_tile()`'s docstring.

@bryevdv @philippjfr (don't know if you'll see my comment in a closed issue if I don't mention you)

**Comment by harabat** [comment]
**Context**
Hey, I opened an issue [here](https://github.com/bokeh/bokeh/issues/10057) after mistakenly re-implementing a feature allowing custom tileset providers to be specified in `get_providers()`. The issue was closed, as it's already possible with `add_tile(WMTSTileSource())`. I might be mistaken, but this information was sufficiently difficult to find for me to re-implement this myself, as I didn't find any mention of this in the docs, in the docstrings, or on SO. Could the issue be reopened, so I can make a PR for the `add_tiles()` docstring and someone in the team can change the [docs](https://docs.bokeh.org/en/latest/docs/user_guide/geo.html)? Asking here because people aren't notified of new comments in closed issues, but I'll remove this when the issue is re-opened. 

**Description of problem**
I think there's scope for discussion about the current way custom tilesets are specified: most urls are of the type `https://tiles.yourtileprovider.come/{z}/{x}/{y}.png`, but many are like `https://{s}.yourtileprovider.come/{z}/{x}/{y}.png` or `https://{s}.yourtileprovider.come/{z}/{x}/{y}.{ext}` (where {s} is the subdomain and {ext} is the format), which breaks `add_tiles()`. The way I reimplemented the feature, I went with a hacky workaround where:
- I replace {s} by 'a', not sure how hacky it is though, as folium's code seems to be doing the same thing by default, even though subdomains can be specified (the relevant code is in `class TileLayer` in raster_layers.py in folium, if you're interested)
- I replace {ext} by png (I noticed that both jpg and png work). Folium itself is broken by leaving the {ext} though (I'll raise an issue there)

**Possible solutions**
Specifying a url with {s} and {exp} should work straight away. Maybe `add_tiles()` could try to replace {s} and {ext} with default values ('a' and 'png') and the docstring could mention something along the lines of `If you specify a url for a custom tileset, it needs to be of the type https://tiles.yourtileprovider.come/{z}/{x}/{y}.png`, so that at least people will know where to look for the problem if their url doesn't work. 

**Alternatives considered**
People could try and find clean urls, but this is not straightforward, as most resources, like [OpenStreetMap's list of tile servers](https://wiki.openstreetmap.org/wiki/Tile_servers) and [this list of free tile providers](https://leaflet-extras.github.io/leaflet-providers/preview/), don't consider {s} to be a problem. 

**Additional context**
The description of the subdomain issue on OSM's tile servers page:

> In the URLS to Carto.com and some others there is also a {s} which should be replaced by the subdomain[1]. Subdomains are used to help with browser parallel requests per domain limitation. These subdomains are typically single letters 'a', 'b' and 'c'. Refer to the provider documentation for details of available subdomains.

**Comment by bryevdv** [comment]
@harabat would suggest opening new issue for any follow-on ideas to keep discussions focused

**Comment by harabat** [comment]
Cheers

**Comment by harabat** [comment]
I posted about this on discourse a few minutes ago, thought you weren't notified of comments on closed issues. I deleted the post on discourse.
