### ISSUE TITLE
[FEATURE] Proper error on Labels when dtype object kdims

### ISSUE THREAD

**Issue by arkanoid87** [bokeh/bokeh#10079]
When using x/yoffset options in Labels, you get empty output and a cryptic javascript console error if x and y kdims are of dtype "object"

I ended up in this situation by building a test input dataframe by list of rows with mixed int and string columns, so the pandas infer engine decided to make all my columns of dtype object.

Pandas was not wrong and I made a silly move,  but I think it would be nice to have a meaningful error when this happens. It would save time.

```
hv.extension('bokeh')
df = pd.DataFrame(np.array([[1,2,'foo'],[2,1,'bar']]), columns=['a','b','c'])
hv.Labels(df, ['a','b'], 'c').opts(xoffset=0.1)
```

just remove the .opts(xoffset=0.1) and you get a valid output

**Comment by philippjfr** [comment]
Thanks for the issue and particularly the minimal example, however could you reopen this issue on to the HoloViews repo?

**Comment by bryevdv** [comment]
For ref: http://github.com/pyviz/holoviews
