### ISSUE TITLE
[BUG] LabelSet offset parameters not applied

### ISSUE THREAD

**Issue by LaurensvanG** [bokeh/bokeh#10078]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 2.0.2
python: 3.7.4
ipython: 7.13.0
Chrome: 84.0.4147.21

#### Description of expected behavior and the observed behavior
The `x_offset` property on the `LabelSet` glyph should offset the label text but the offset is not applied.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure
from bokeh.models import LabelSet, ColumnDataSource
from bokeh.io import output_notebook, show
output_notebook()

# Dummy data
data=ColumnDataSource(dict(x=[0, 1, 2, 3], y=[1, 2, 1, 3], labels=["a", "b", "c", "d"]))

# Create figure
p = figure()
r1 = p.circle(x="x", y="y", source=data)
r2 = LabelSet(x="x", y="y", x_offset=.5, y_offset=-.5, text="labels", source=data)
p.add_layout(r2)

show(p)
```

#### Stack traceback and/or browser JavaScript console output
n/a

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/57599515/83012393-9efa8200-a01b-11ea-9cdc-ebd0ea7e59fe.png)

**Comment by mattpap** [comment]
> `x_offset=.5, y_offset=-.5`

`{x,y}_offset` allows values only in screen space (pixels), so a value of 0.5 will be treated as 1 pixel offset. If you want an offset in data space, then there are currently two options, either include it in the data, or apply a transform to `x` and `y` fields. If you think it would be useful to support data space offsets, then I suggest discussing this on https://discourse.bokeh.org/.
