### ISSUE TITLE
Documenting the documentation process and guidelines

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1007]
I think it would be extremely helpful and would make it easier for other people to help out with documentation to have/improve the documentation on how to document in Bokeh and some guidelines to have a common style. e.g #961.

e.g. some things that are not clear for me right now is which folder hosts the files, difference between folder sphinx/source/tutorial and sphinx/tutorial_source; docs sections organization: what to include in User Guide, Developer Guide, vs Reference Guide.

Some other suggestions for the documentation process: 
- Keep track of "undocumented or not documented well enough" features and a TODO list for documentation.
- PR's adding new features should include docs and be reviewed taking the docs also into account. Ideally, in my opinion, only should get merged to master when they contain proper docs. Rushing to get features in a release, but failing to provide enough information on how to use them, can have a negative effect on users expectations.

**Comment by bryevdv** [comment]
I do want to make a pass over the dev guide docs in general and also the docs docs in particular soon. Moving to `0.12.7` to keep track of.
