### ISSUE TITLE
[BUG]Not able to embed bokeh Panel layout column in flask

### ISSUE THREAD

**Issue by sameerCoder** [bokeh/bokeh#10071]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by sameerCoder** [comment]
My Bokeh plot is working fine, so i thought of putting this dynamic plot on cloud / live so that others can also use & see this Web Application. I am getting below Error after running few lines of python code.:
```
'Input must be a Model, a Document, a Sequence of Models and Document, or a dictionary from string to Model and Document'
ValueError: Input must be a Model, a Document, a Sequence of Models and Document, or a dictionary from string to Model and Document
127.0.0.1 - - [23/May/2020 17:38:05] "GET /plot/ HTTP/1.1" 500*
```
**when i am checking my finalplot data type - it is showing <class 'panel.layout.Column'>**
My code which i am trialing is below.
```

from flask import Flask, render_template
from werkzeug.wrappers import Request,Response

app=Flask(_name_)

@app.route('/plot/')
def plot():
    from shapely.geometry import Point,Polygon
    import pandas as pd
.......
.......
......
......
......
    dd=df_div.opts(width=70, height=70)
    dd1=df_div1.opts(width=600, height=90)



    finalplot=pn.Column(pn.Row(dd, dd1), tiles*rasterize(hmap1).options(**opts)*hmap2*logo1.opts(hooks=[absolute_position], apply_ranges=False)).servable()
    #print("--- %s seconds ---" % (time.time() - strtt))
    #finalplot



    script1, div1 = components(finalplot)
    cdn_js=CDN.js_files[0]
    #cdn_css=CDN.css_files[0]
    return render_template("plot.html",
    script1=script1,
    div1=div1,
    #cdn_css=cdn_css,
    cdn_js=cdn_js )
```

So i want to know why my error of input is coming , is through component is the best way to embed ?
Even i tried to embed by from_html , there also Error came. 
Kindly let me know how to solve this Error so that i can embed my bokeh plot into flask app.
Thank you .
I will really appreciate if some one help me with this.

**Comment by philippjfr** [comment]
@sameerCoder This isn't really a bokeh issue so I'll close. That said the problem here is simple, a Panel object is not a Bokeh object it simply renders as a Bokeh model eventually. So all you need to change is this:

```python
    script1, div1 = components(finalplot.get_root())
```

The `.get_root` method gets the bokeh root model which can then be used just like any other Bokeh component.

**Comment by bryevdv** [comment]
I really don't like the `invalid` tag, perhaps we could/should change it to `downstream` or `third-party` since things that would be marked invalid are almost always issues in something else.
