### ISSUE TITLE
Examples tests report BokehJS version mismatch

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10087]
```
tests/test_examples.py::test_file_examples[/home/runner/work/bokeh/bokeh/examples/models/file/daylight.py-example11-config11] 
[INFO] Example run in 0.966s
[INFO] Example rendered in 0.873s
[JS] {log} file:///usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/bokeh/server/static/js/bokeh.js:7248:21 [bokeh] setting log level to: 'info'
[JS] {warning} file:///usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/bokeh/server/static/js/bokeh.js:1104:34 [bokeh] JS/Python version mismatch
[JS] {warning} file:///usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/bokeh/server/static/js/bokeh.js:1105:34 [bokeh] Library versions: JS (2.0.2) / Python (40f33cf)
[JS] {info} file:///usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/bokeh/server/static/js/bokeh.js:661:34 [bokeh] document idle at 38 ms
PASSED
```
Seems to be using CDN resources, not local ones, which could eventually result in an un-fixable build.

Noting that this was happening before #10058 

cc @mattpap

**Comment by mattpap** [comment]
It clearly uses non-CDN resources as visible in the log:
```
file:///usr/share/miniconda3/envs/bk-test/lib/python3.6/site-packages/bokeh/server/static/js/bokeh.js:1105:34
```
I think the problem is that bokeh started reporting version information differently/incorrectly, but I need to debug this.

**Comment by bryevdv** [comment]
Yes, that seems like it might be possible. Checked the logs again and definitely the local package is what is installed in to the test env:
```
Run bash ci/install_bokeh_package.sh
  bash ci/install_bokeh_package.sh
  shell: /bin/bash -l {0}
  env:
    CONDA: /usr/share/miniconda3
    CONDA_PKGS_DIR: /home/runner/conda_pkgs_dir
+ conda install --yes --quiet --offline /tmp/conda-bld/noarch/bokeh-b99489e-py_0.tar.bz2
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```

Tangentially, do you have any issue raising 
```
[bokeh] setting log level to: 'info'
``` 
to debug level? It does not seem important to report this in common usage.

**Comment by mattpap** [comment]
> (...) to debug level? It does not seem important to report this in common usage.

I would remove this message altogether. We don't have any other APIs that inform the user about a value being set. However, I would display some more debug information if bokehjs is run in `dev` mode (`Bokeh.settings.dev = true`) (ref issue #10110).

**Comment by mattpap** [comment]
I think this was covered by PR #13741.
