### ISSUE TITLE
[BUG]The vbar for categorical data do not function normally when the number of categories are large

### ISSUE THREAD

**Issue by ruochiz** [bokeh/bokeh#10082]
I'm using the 2.02 verion of Bokeh, and I noticed this bug. When I try to update the data and x_range of a categorical vbar, it's not functioning normally if there are too many categories.

This is the minimal code to reproduce the problems:

```

import warnings
warnings.filterwarnings("ignore")




from bokeh.layouts import row, column
from bokeh.plotting import curdoc, figure, ColumnDataSource
from bokeh.models.widgets import Slider, Select, Button, Div, PreText, Toggle


def update_bar(button):
	print ("I'm here")
	categorical_h_all.data_source.data["x"] = ['a','b','c','d']
	categorical_h_all.data_source.data["top"]= [2,3,4,5]
	categorical_info.x_range.factors = ['a','b','c','d']
	return

bar_info = ['a','b','c','d','e','f','g','h','i','j']
count = [1,1,1,1,1,1,1,1,1,1]

categorical_info = figure(toolbar_location=None,x_range=bar_info)
categorical_h_all = categorical_info.vbar(x=bar_info, top=count, width=0.5)

button1 = Button(label="test1", button_type="danger", width=150)
button1.on_click(update_bar)
curdoc().add_root(row(categorical_info, button1))
```
I use bokeh serve to use it
When I click the button, there will not be any change, and there is a "bokeh.min.js?v=57d29d5936e494351385d736f792154c:256 Uncaught TypeError: Cannot read property 'length' of undefined" error in the chrome browser.

But, if you change the original ```bar_info``` to a shorted version of itself, let's say ['a', 'b', 'c', 'd', 'e', 'f'], and shorten the original count to the same length. 
```bar_info, count = bar_info[:6],count[:6]```
The update from the click event can be made, and there is no error messages.

Could you help to see if there's a bug, or I used the package in a wrong way? Thanks

**Comment by ruochiz** [comment]
Oh, I think I find a work-around, or the solution of it.

If I update the data source with ```categorical_h_all.data_source.data = dict(x=...,top=...)```, then it works.

Is it preferred to update the data all at once, instead of column by column?

**Comment by bryevdv** [comment]
> Is it preferred to update the data all at once, instead of column by column?

This is almost always preferred, but in cases where the column lengths change, it is *required*. There is an assumption that all CDS columns always all have exactly the same length at all time. Breaking the assumption results in undefined behavior.
