### ISSUE TITLE
No image_rgba downsampling utility

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#1008]
Currently only `image` and `line` glyphs have downsampling facilities on the server; a similar capability should be added for `image_rgba` glyphs.

**Comment by birdsarah** [comment]
@bryevdv - are we moving AR out of bokeh-core - if so, should we close this?

**Comment by bryevdv** [comment]
This wasn't even AR I think this was some other stab at downsampling. This can definitely be closed.
