### ISSUE TITLE
Deprecate ragged array case in ImageBase.image

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10090]
ref https://github.com/bokeh/bokeh/pull/10069#discussion_r432221545

**Comment by sirspoon** [comment]
Bryan suggested to link to this comment here for reference..
https://discourse.bokeh.org/t/share-an-image-within-a-cds/7289/4
thanks

**Comment by bryevdv** [comment]
I'm actually not sure how we can meaningully deprecate this. I think at this point I would simply propose removing the codepath outright in BokehJS at 3.0, and trying to improve types on the Python at the same (e.g. maybe an `Array2dSpec` that has a validation to check the column is list of 2d arrays. 

I'm going to go ahead and switch the milestone now. cc @bokeh/dev comment if there are any concerns.
