### ISSUE TITLE
[BUG] Using anchors in the API Reference hides the anchored element under the header

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10103]
For example, try opening https://docs.bokeh.org/en/latest/docs/reference/models/callbacks.html#bokeh.models.callbacks.OpenURL

Expected behavior: the page is opened with `OpenURL` visible at the very top.
Actual behavior: the page is opened with `OpenURL` obscured by the header.

Related, although for regular headers and not for code: #9915

**Comment by bryevdv** [comment]
Now that we have transitioned to the official Pydata Sphinx theme instead of our old vendored version, this problem has come back. Unfortunately the solution that worked before does not seem to work anymore with the updated theme.

**Comment by p-himik** [comment]
Has this transition been published? Because the URL in the OP still works just fine for me in Google Chrome.

**Comment by bryevdv** [comment]
Only on test: http://docs.bokeh.org/en/test/docs/user_guide/categorical.html#filling

**Comment by p-himik** [comment]
Works for me just fine as well!

**Comment by bryevdv** [comment]
That page has lots of plots which maybe confuses the matter. Also, interesting, but apparently the issue (maybe) is only when *clicking the actual anchor*. On safari, clicking the anchor on this entry:

http://docs.bokeh.org/en/test/docs/reference/models/formatters.html#bokeh.models.formatters.BasicTickFormatter.layout

Shifts the page up to hide the anchor I just clicked:

<img width="1105" alt="Screen Shot 2021-04-06 at 10 05 13 AM" src="https://user-images.githubusercontent.com/1078448/113750542-cef4c600-96bf-11eb-924f-dda3e56e9acf.png">

**Comment by p-himik** [comment]
Yeah, I tried both loading with the anchor and clicking on an anchor when all the plots are already there. Both work in the latest Google Chrome just fine. But if I remove the initial markup that made it work at the URL in the OP, it stops working. Not sure what the difference is.

**Comment by bryevdv** [comment]
Just to be clear don't think thing the published test version has this fix? So far I only tried putting the fix back locally after I noticed the issue loally, and where it did not seem to work (at least for actual anchor clicking). But I will double check.

**Comment by jorisvandenbossche** [comment]
It's working correctly for me as well. But you are using Safari? That's unfortunately a know issue ... -> https://github.com/pydata/pydata-sphinx-theme/issues/325 (with a possible workaround with caveats)

**Comment by bryevdv** [comment]
This seems to be resolved in the latest deployed dev docs. Clicking the anchor scrolls up, but not underneath the menu.
