### ISSUE TITLE
[FEATURE] Addition of a Measuring Tool

### ISSUE THREAD

**Issue by ayushiitr2901** [bokeh/bokeh#10100]
It would be great if we have a measuring tool that reports the distance between the previous and current position of the mouse. This shall simplify the task of people looking to measure the change in coordinate values between different points on the plot.

**Solution:**
Adding a new tool that activates on a tap of the mouse, setting up an initial anchor, and then displays the distance between the current position of the pointer and the initial anchor ( delta_x, delta_y) as the user pans around anywhere on the canvas. The details shall be displayed and continuously updated in a tooltip that follows the pointer.

**Alternative Approach:**
Rather than the pan, the tool can also be made to work with two taps defining an initial and final anchor and then displaying the distance coordinates.

I think the first approach might be more helpful for mobile or touch users. But it would be great if we have multiple opinions.

**Comment by bernardosulzbach** [comment]
This would be very useful to me. I think that (optionally) snapping to plotted points would be amazing, so that the user could measure the variation in the actual data, not just between two points on the screen.

**Comment by mattpap** [comment]
This is a duplicate of issue #182.
