### ISSUE TITLE
webdriver failing to find installed firefox/geckodriver

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10108]
Can't get export examples running on binder even though everything is installed and on the path:

<img width="1130" alt="Screen Shot 2020-06-02 at 8 23 16 PM" src="https://user-images.githubusercontent.com/1078448/83592297-e9459c80-a50e-11ea-90d1-7189fcc93af0.png">

**Comment by bryevdv** [comment]
Noting the failure is in `webdriver.Firefox` with:
```
SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by bryevdv** [comment]
Users reporting a similar problem on Collab

**Comment by vivek1383** [comment]
Hello! 
Reporting the same issue in my case as well. 
The export png method fails in colab setup. I have installed selenium/chromedriver etc. But the export method fails every time with this error. 

`

> Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.

`

I am simply using this command
`x = export_png(plt, filename=Path + '/Print my Plot.png')`

**Comment by bryevdv** [comment]
@vivek1383 can you poke around and try to locate where the web driver and browser actually get installed on collab? It's not something we have control over (and not something I have any immediate offhand knowledge of).

**Comment by vivek1383** [comment]
Sure let me try. I did try to look for it in /content/node_modules/ But I couldnt. Let me poke around more.

**Comment by vivek1383** [comment]
Okay followed this post https://stackoverflow.com/questions/60686871/colab-cant-find-chromedriver-path and now I find the chrome driver here. "/usr/bin/chromedriver". firefox bin is also in the same directory.

**Comment by vivek1383** [comment]
Hello team, 
Any help will be appreciated here. I think if I can get any pointers to what the system path variable is, I may be able to proceed. 

Thanks in advance.

**Comment by bryevdv** [comment]
@vivek1383 It's `PATH` on all platforms, AFAIK

**Comment by vivek1383** [comment]
ok, thanks. Let me try that.

**Comment by mattpap** [comment]
The problem is that `bin/firefox` is a script (in conda's case trivial `bin/FirefoxApp/firefox "@"`), and webdriver expects an executable binary file. I'm not sure why it's failing now. Perhaps the script is a new addition or geckodriver is stricter now. In any case, the solution is to provide a path to the real binary to geckodriver, which will be fun to maintain across platforms, etc.

**Comment by mattpap** [comment]
If the problem persists after PR #10360 in certain environments, please reopen with information what `which firefox` is, and if it's a script, where the actual binary is located.

**Comment by vivek1383** [comment]
@mattpap I am not sure what you mean by the above. I am not very well versed with the python environment. So some of it may need to be elaborated than usual. 
I tried setting the path as suggested to visible binaries. That doesnt seem to work. I installed the package like this -->

```
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium
```

I have set the path here and tried couple of different versions: 

```
! echo $PATH

import os
os.environ['PATH'] += ":/usr/bin/chromedriver"

! echo $PATH
```
Let me know if I am missing anything.

**Comment by bryevdv** [comment]
@vivek1383 #10360  is not part of any release yet, you would need to build from source or install a pre-release dev build to test things out. Otherwise the next release should happen next week.

**Comment by vivek1383** [comment]
Ah, okay. I think the problem with that is that I am not sure when Google colab will upgrade Bokeh to the latest version. It took them almost over 2 months to upgrade to the latest. 
Meanwhile, is there any workaround?

**Comment by mattpap** [comment]
> Meanwhile, is there any workaround?

One can always create a web driver on his own and use that driver instead of the default one, e.g.:
```py
export_png(my_plot, webdriver=my_driver)
```
To create a driver, one can copy code from `bokeh.io.webdriver` and fill in the paths manually, instead of relying on auto-detection.

**Comment by vivek1383** [comment]
Got it! Thanks for the pointers. Let me try that and see what happens.

**Comment by mcrot** [comment]
I also experience this problem in my Django project. In my working copy the geckodriver is found, but not in my Docker container,
although it is built with `RUN conda install -c conda-forge firefox geckodriver` in the Dockerfile and I can see that the binaries have been installed and are accessible through `$PATH`. I'll try to locate the binaries and to create the drivers manually, thanks for the hint.

**Comment by vivek1383** [comment]
Forgot to post it here. @mattpap 's trick has worked. I created my own webdriver and pointed it to the binaries. It works fine for now.

**Comment by mcrot** [comment]
Thanks @vivek1383 . I'm not sure which part of the `bokeh.io.webdriver` to use, as @mattpap mentioned.
I've tried the following: 
```python
from selenium import webdriver
driver = webdriver.Firefox(firefox_binary='/opt/conda/bin/FirefoxApp/firefox',
                                         executable_path='/opt/conda/bin/geckodriver')
image = get_screenshot_as_png(plot, driver=driver)
```
The paths I've found by using `which` on my Docker container, for firefox it was a script (as expected) and I used the binary
file where it points to.

The driver is found, but I get an exception:
```
 File "/app/topobank/manager/models.py", line 684, in renew_thumbnail
    executable_path='/opt/conda/bin/geckodriver')
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```
I don't understand which process as already existed and why.

Could you post the code you've finally used in to instantiate the driver, @vivek1383?

**Comment by mcrot** [comment]
I've done a little more research and because of [the answer to this SO question](https://stackoverflow.com//questions/52534658/webdriverexception-message-invalid-argument-cant-kill-an-exited-process-with) I've tried to find out whether the firefox and geckodriver versions match.

Although I've used `RUN conda install -c conda-forge firefox geckodriver` in the Dockerfile,
the firefox binary in my docker container (here docker-compose service "django") is missing dependencies:
```
$ docker-compose -f local.yml run --rm django /opt/conda/bin/FirefoxApp/firefox --version
[...]
XPCOMGlueLoad error for file /opt/conda/bin/FirefoxApp/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
``` 
I've added `RUN apt-get install --yes libgtk-3-0` to my Dockerfile, because this package contains the missing library. 
Now the next library is missing:
```
$ docker-compose -f local.yml run --rm django /opt/conda/bin/FirefoxApp/firefox --version
[...]
XPCOMGlueLoad error for file /opt/conda/bin/FirefoxApp/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
Somehow the dependencies of the firefox conda package seem to be broken? Probably I should take another path to install firefox + geckodriver in my Docker container.

**Comment by mcrot** [comment]
Now it works - somehow, but the memory is not freed. My summary so far:

1. In order to get the binary running, I've got to install packages on system level in my docker container:
```
RUN apt-get install --yes libgtk-3-0 libdbus-glib-1-2
```
Then I could execute `firefox --version`.

2. In order to cope with the error message `selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process`, I started the driver headless:
```python
        from selenium import webdriver
        from selenium.webdriver.firefox.options import Options        
        options = Options()
        options.headless = True
        driver = webdriver.Firefox(options=options,
                                   firefox_binary='/opt/conda/bin/FirefoxApp/firefox',
                                   executable_path='/opt/conda/bin/geckodriver')
        image = get_screenshot_as_png(plot, driver=driver)
```
Then the image creation worked, but in a loop after a few images, suddenly I've got this
```python
  File "/opt/conda/lib/python3.7/site-packages/bokeh/io/export.py", line 226, in get_screenshot_as_png
    [width, height, dpr] = _maximize_viewport(web_driver)
  File "/opt/conda/lib/python3.7/site-packages/bokeh/io/export.py", line 397, in _maximize_viewport
    web_driver.set_window_size(width + eps, height + eps)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1090, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1182, in set_window_rect
    "height": height})['value']
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette
```
3. This seems to be related to [too low memory settings for the container](https://stackoverflow.com/a/55206440/10608001).
Then I've added `shm_size: '2gb'` to my docker-compose service.

Now I can create thumbnails for my plots, but the memory goes up and up and is unfortunetely not freed. 
Is this different in your solution @vivek1383 ?

**Comment by Prashavu** [comment]
> Now it works - somehow, but the memory is not freed. My summary so far:
> 
> 1. In order to get the binary running, I've got to install packages on system level in my docker container:
> 
> ```
> RUN apt-get install --yes libgtk-3-0 libdbus-glib-1-2
> ```
> 
> Then I could execute `firefox --version`.
> 
> 1. In order to cope with the error message `selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process`, I started the driver headless:
> 
> ```python
>         from selenium import webdriver
>         from selenium.webdriver.firefox.options import Options        
>         options = Options()
>         options.headless = True
>         driver = webdriver.Firefox(options=options,
>                                    firefox_binary='/opt/conda/bin/FirefoxApp/firefox',
>                                    executable_path='/opt/conda/bin/geckodriver')
>         image = get_screenshot_as_png(plot, driver=driver)
> ```
> 
> Then the image creation worked, but in a loop after a few images, suddenly I've got this
> 
> ```python
>   File "/opt/conda/lib/python3.7/site-packages/bokeh/io/export.py", line 226, in get_screenshot_as_png
>     [width, height, dpr] = _maximize_viewport(web_driver)
>   File "/opt/conda/lib/python3.7/site-packages/bokeh/io/export.py", line 397, in _maximize_viewport
>     web_driver.set_window_size(width + eps, height + eps)
>   File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1090, in set_window_size
>     self.set_window_rect(width=int(width), height=int(height))
>   File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 1182, in set_window_rect
>     "height": height})['value']
>   File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/opt/conda/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette
> ```
> 
> 1. This seems to be related to [too low memory settings for the container](https://stackoverflow.com/a/55206440/10608001).
>    Then I've added `shm_size: '2gb'` to my docker-compose service.
> 
> Now I can create thumbnails for my plots, but the memory goes up and up and is unfortunetely not freed.
> Is this different in your solution @vivek1383 ?

Hi I'm facing the exact same issue all of a sudden from day before . Till then it was working perfectly fine , it says can't find the oath and I checked that ithe .exe s available in my packages ( geckodriver.exe) , I installed by the conda forge a few months ago, now I tried to update it and also pip install it , but nothing works ,I don't have firefox at work and we have onky chrome and internet explorers. Until 3 days ago it used to open in the I.E . What do I do ,as I can't create a firefox driver too u like you as we don't have firefox .

**Comment by mcrot** [comment]
@Prashavu , I think the firefox/geckodriver feedstock on conda-forge has some problem, maybe [this issue](https://github.com/conda-forge/firefox-feedstock/issues/25) is related. After installing the extra packages `libgtk-3-0`and `libdbus-glib-1-2` and specifying my executables explicitly, I could use firefox+geckodriver. If you don't have firefox but chrome, it is maybe possible to instantiate a webdriver for chrome+chromedriver in a similar way as described above for firefox+geckodriver. Take a look at this comment, that may work for you: https://github.com/bokeh/bokeh/issues/6594#issuecomment-346178496

**Comment by mcrot** [comment]
Concerning my memory problem: It is solved by calling
```
driver.close()
```
I wonder, whether using the chromedriver is faster, but this is another topic.
after creating my image.

**Comment by mcrot** [comment]
@Prashavu , also [this article](https://medium.com/@tehniyat122/export-image-as-png-file-using-bokeh-plot-2faa2822b7ef) may help you.

**Comment by Prashavu** [comment]
> @Prashavu , also [this article](https://medium.com/@tehniyat122/export-image-as-png-file-using-bokeh-plot-2faa2822b7ef) may help you.

Thanks for your pointers ! Actually I have bit of an issue with using Chrome as we are not allowed to upgrade or download an gecxkodriver.exe directly from the web t to match versions ,I'm left only with Internet explorer, which was working until couple of days ago, I'm not using any cloud platform (AWS/Collab)  to run my code ,just Spyder on anaconda, given this how can I Install  the additional dependencies  u mentioned using pip on the anaconda terminal?

**Comment by mcrot** [comment]
@Prashavu , I've no experience with IE and use Linux, so I cannot help you with that one. But I want to mention, that for Chrome, you need a `chromedriver` executable (not `geckodriver`, that is for firefox). Maybe you have already one installed, otherwise there are pypi packages which install a chromedriver in the background: https://pypi.org/search/?q=chromedriver
Currently I'm trying to figure out how to do this in a Docker container. However, probably this topic should no longer be discussed here, because it starts getting off-topic I think, because the original issue is about firefox+geckodriver.

**Comment by Sieboldianus** [comment]
It's obvisoully quite difficult to get the png/svg stuff working in various setups. The key seems to be that there are various ways to install browsers, and it is not easy for bokeh to automatically get paths.

I am running in the follow setup (and got svg/png output working, see instructions below):

* Debian Docker Image
* Holoviews/Geoviews with Bokeh plotting backend
* specific conda environment (`worker_env`)
* strict conda channel settings (`conda config --set channel_priority strict`)
* channel: `conda-forge`

First, I installed firefox as a standalone packages (not from conda-forge, because this seem to lack behind the release schedule):

```bash
wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz \
 && sh -c 'tar -x geckodriver -zf geckodriver-v0.27.0-linux64.tar.gz -O > /usr/bin/geckodriver' \
 && chmod +x /usr/bin/geckodriver \
 && rm geckodriver-v0.27.0-linux64.tar.gz \
 && apt-get install firefox-esr --yes
```

As you can see, I also installed geckodriver, but I was unable to use it in python. Therefore, I makde an alternative install of geckodriver in python:
```bash
conda env create --file environment_default.yml --name worker_env --quiet
```
This is my environment_default.yml:
```yml
name: worker_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - holoviews
  - selenium
  - geckodriver
```

Now, in jupyter, to export a holoviews plot (e.g.) as png:

```python
import sys
from pathlib import Path
from bokeh.io import export_png
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

hv_layers = (gf.ocean.opts(alpha=0.1, fill_color="blue") * \
                 gf.coastline.opts(line_color="black") * \
                 gf.borders.opts(line_color="darkgrey")
            ).opts(
        bgcolor="white",
        responsive=True,
        data_aspect=1)
p =  hv.render(hv_layers, backend='bokeh')
        options = Options()
        options.headless = True
        web_driver = Firefox(
            options=options,
            firefox_binary=str(Path('/usr/bin/firefox')),
            executable_path=str(Path("/opt/conda/envs/worker_env/bin/geckodriver")))
        export_png(p, filename= 'hv_plot.png', webdriver=web_driver)
```

This has worked for me with the following versions:
- bokeh 2.2.3
- holoviews 1.13.5

**Comment by obust** [comment]
I have the same issue with installing firefox in a docker image from firefox-feedstock.
I tried both 83.0 and 79.0 and they give the same error

```
$ firefox --version
XPCOMGlueLoad error for file /opt/conda/bin/FirefoxApp/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

I'd like to avoid installing system dependencies (libgtk, libdbus) and instead move more dependencies to conda.

I tried to install gtk3 from conda but it is also having some [dependency issues](https://www.gitmemory.com/issue/conda-forge/gtk3-feedstock/16/667236511)...

**Comment by zbarry** [comment]
For people who are having trouble getting this to work in Jupyter notebooks with conda envs, I realized that if you have this sort of setup:

1. You run `jupyter lab` out of conda environment 1
2. You run your notebook using a Jupyter kernel from conda env 2 that was installed via `ipykernel`

the `conda/envs/environment2/bin/` folder for env 2 will not be on your `PATH`: https://github.com/jupyter/notebook/issues/4527

One solution to this is to make sure your conda environment you run Jupyter Lab/Notebook out of has `firefox` and `geckodriver` installed.

**Comment by dycw** [comment]
I'm running into this again and again. Any ideas on how to fix?

```
  File "/home/wande/work/utilities-2633/src/tests/test_holoviews.py", line 37, in test_saving_png
    save_plot(Curve(range(3)), tmp_path.joinpath("plot.png"))
  File "<@beartype(utilities.holoviews.save_plot) at 0x7fa78bb87f70>", line 29, in save_plot
  File "/home/wande/work/utilities-2633/src/utilities/holoviews.py", line 140, in save_plot
    save(plot, tmp)
  File "/home/wande/work/utilities-2633/.venv/lib/python3.9/site-packages/holoviews/util/__init__.py", line 788, in save
    return renderer_obj.save(obj, filename, fmt=fmt, resources=resources,
  File "/home/wande/work/utilities-2633/.venv/lib/python3.9/site-packages/holoviews/plotting/renderer.py", line 595, in save
    rendered = self_or_cls(plot, fmt)
  File "/home/wande/work/utilities-2633/.venv/lib/python3.9/site-packages/holoviews/plotting/renderer.py", line 199, in __call__
    data = self._figure_data(plot, fmt, **kwargs)
  File "/home/wande/work/utilities-2633/.venv/lib/python3.9/site-packages/holoviews/plotting/bokeh/renderer.py", line 127, in _figure_data
    img = get_screenshot_as_png(plot.state, driver=state.webdriver)
  File "/home/wande/work/utilities-2633/.venv/lib/python3.9/site-packages/bokeh/io/export.py", line 236, in get_screenshot_as_png
    web_driver = driver if driver is not None else webdriver_control.get()
  File "/home/wande/work/utilities-2633/.venv/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 153, in get
    self.current = self.create()
  File "/home/wande/work/utilities-2633/.venv/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 157, in create
    driver = self._create(kind)
  File "/home/wande/work/utilities-2633/.venv/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 175, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the form
er with 'conda install -c conda-forge firefox geckodriver'.
```

Didn't really see this some 1-2 months ago, using mostly latest `bokeh` (2.4.3) via `holoviews` (1.15.2); on RedHat 7.9 and Python 3.9.

Everyone's been using the same `geckodriver` for almost 1/2 year now:

``` 
total 8108
drwxr-x---.  2 stat-arb stat-arb-common    4096 Jun 29 08:02 .
drwxr-xr-x. 15 stat-arb stat-arb-common    4096 Nov  4 16:39 ..
-rwxr-x---.  1 stat-arb stat-arb-common 8293024 Jun 29 08:01 geckodriver
```

but tests recently started flagging this.

More bizarrely, it's my tests which fail -- but I can still make these images via CLI & libraries.

**Comment by anitagraser** [comment]
I'm also running into this issue: https://github.com/anitagraser/cml-example-base/actions/runs/5563625371/jobs/10162695536?pr=2

Any pointers would be more than welcome.
