### ISSUE TITLE
[BUG] Resource warning unclosed file... _sri.json possible Resource Leak

### ISSUE THREAD

**Issue by mikeafaltys** [bokeh/bokeh#10128]
bokeh==2.0.2, 
Windows 10 Home Version10.0.18363 Build 18363 
PyCharm 2020.1.2 (Community Edition), Build #PC-201.7846.77, built on May 31, 2020, Runtime version: 11.0.7+10-b765.53 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o., Windows 10 10.0, GC: ParNew, ConcurrentMarkSweep, Memory: 1979M, Cores: 12
Non-Bundled Plugins: org.exbin.deltahex.intellij, ru.meanmail.plugin.requirements

#### Description of expected behavior and the observed behavior
Expected html plot but addition got warning:
\venv\lib\site-packages\bokeh\resources.py:107: ResourceWarning: unclosed file <_io.TextIOWrapper name=‘C:\…\venv\lib\site-packages\bokeh\_sri.json’ mode=‘r’ encoding=‘cp1252’> _SRI_HASHES = json.load(open(join(ROOT_DIR, “_sri.json”)))

#### Complete, minimal, self-contained example code that reproduces the issue

```
df is a pandas dataframe 40,000 rows and 7 columns, float

    output_file(f'{data_path()}{plot_title}.html')
    if df.shape[1] > 2:
        colors = Category20[df.shape[1]]  # limited to 20 colors
    else:
        colors = ['#1f77b4', '#aec7e8']  # why do palettes have a min of 3?
    p = figure(title=plot_title, x_axis_label='Time(s)', y_axis_label=left_axis_label,
               x_range=(df.Time[0], df.Time.iloc[-1] * 1.3))
    for i, col in enumerate(df.columns):
        if col != 'Time': 
            p.line(x='Time', y=col, source=df, legend_label=col, color=colors[i])
    p.legend.click_policy = "hide"
    show(p)

```

#### Stack traceback and/or browser JavaScript console output

C:\Users\.....\GitHub\MultimodeEPGTest\venv\lib\site-packages\bokeh\resources.py:107:

**Comment by bryevdv** [comment]
Fixing this in the 2.2 release ready PR
