### ISSUE TITLE
BokehDeprecationWarnings with Bokeh v 2.02

### ISSUE THREAD

**Issue by unique379r** [bokeh/bokeh#10121]
Hi 
I am using nanoQC ( https://github.com/wdecoster/nanoQC) which uses Bokeh to plot the analysis of long read reads but while using I am getting errors **"BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead".** 
Any possible solution or update on it?
Someone from the previous version has reported  (https://github.com/PatrikHlobil/Pandas-Bokeh/issues/51) and it seems you have fixed it but this is actually not the case of latest release.

Please have a look.
Thanks

**Comment by bryevdv** [comment]
@unique379r It's up to whoever maintains nanoQC to update their usage of Bokeh to use the newer syntax. We have nothing to do with nanaQC (I've never heard of it before now) and certainly no influence over its development.
