### ISSUE TITLE
[BUG] `TileRenderer` ignores the `visible` property

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10147]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.1.0rc1

#### Description of expected behavior and the observed behavior
`TileRenderer` should take into account the `visible` property. Both if passed to its constructor and if changed in runtime if using Bokeh server.

#### Complete, minimal, self-contained example code that reproduces the issue
```python
from bokeh.io import show
from bokeh.plotting import figure
from bokeh.tile_providers import CARTODBPOSITRON, get_provider

p = figure(x_range=(-2000000, 6000000), y_range=(-1000000, 7000000),
           x_axis_type="mercator", y_axis_type="mercator")

p.add_tile(get_provider(CARTODBPOSITRON), visible=False)

show(p)
```
The root cause is that `TileRenderer` just doesn't check `visible` at all. It seems like every renderer checks this property. Maybe it should be checked at a higher level?

**Comment by mattpap** [comment]
> Maybe it should be checked at a higher level?

It should, however due to having renderers that either paint to canvas, or render to DOM or both, this gets a bit more complicated.
