### ISSUE TITLE
Replacing Iris data with penguin data

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#10157]
So given recent events there has been a lot of discussion about the Iris data, which is a standard for demonstrating classification and other statistical techniques. The problem with it is that was first published by Ronald Fisher (a Eugenicist) in the Annals of Eugenics and I don't think I need to point out why that history is extremely problematic for a dataset that has been used for classification problems. It's also incredibly overused and many people will roll their eyes just seeing it.

Thankfully there is a new dataset a lot of people seem to be coalescing around, specifically this open source dataset about penguins: https://github.com/allisonhorst/palmerpenguins, which has several advantages:

* It wasn't popularized by a eugenicist
* It has more interesting dimensions to explore
* It's about penguins 🐧 🐧 🐧 

I therefore propose we replace the Iris data in sampledata and all the associated examples with equivalent examples using the penguin data. Libraries like seaborn have already taken this step and I think we should too.

**Comment by bryevdv** [comment]
+1 for sure (was not aware of the history)

**Comment by jbednar** [comment]
I was just wondering about this myself; I think we share the same twitter feeds. :-/

**Comment by ashwani-rathee** [comment]
I also think it should be done ,but does replacing would mean completely removing the iris data?

**Comment by philippjfr** [comment]
I'd say we should keep it around for a little while but add a deprecation warning on import. Does that seem reasonable?

**Comment by ashwani-rathee** [comment]
Yeah,That seems reasonable with deprecation warning.I would like to help on this.:)

**Comment by bryevdv** [comment]
This is nearly done, these appear to be the only remaining examples that make use of `iris`. Presumably they all can/should use `penguins` instead:
```
base ❯ grip iris
models/widgets.py
6:    :sampledata: autompg2, iris
23:from bokeh.sampledata.iris import flowers

plotting/iris.py
3:between petal width and length for three different iris species.
10:    :sampledata: iris
16:.. _alternatives to Iris: https://www.meganstodel.com/posts/no-to-iris/
20:from bokeh.sampledata.iris import flowers

output/apis/json_item_themed.py
9:from bokeh.sampledata.iris import flowers

output/apis/autoload_static.py
8:from bokeh.sampledata.iris import flowers

output/apis/json_item.py
9:from bokeh.sampledata.iris import flowers

output/apis/components_themed.py
6:from bokeh.sampledata.iris import flowers

basic/layouts/words_and_plots.py
5:from bokeh.sampledata.iris import flowers
```
