### ISSUE TITLE
[BUG] Using CDS field as color for nonselection_fill_color gets the wrong colors when using a view

### ISSUE THREAD

**Issue by MichaelMonn** [bokeh/bokeh#10156]
Python 3.6.0, Bokeh 2.0.2, Pandas 0.25.3

#### Issue:
when setting the nonselection_fill_color of a bokeh glyph to be the name of a field in a CDS, the color is improperly represented if the glyph is given a CDSview

#### Example:
```
from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers
from bokeh.models import ColumnDataSource, CDSView, IndexFilter
from bokeh.palettes import OrRd9
import pandas as pd

COLORS = OrRd9[::-1]
N_COLORS = len(COLORS)
def get_colors(var):
        c_data = data.data[var]
        if len(c_data) > N_COLORS:
            groups = pd.qcut(c_data, N_COLORS)
        else:
            groups = pd.Categorical(c_data)
        data.data['color'] = [COLORS[xx] for xx in list(groups.codes)]

data = ColumnDataSource(data=flowers)
view = CDSView(source=data, filters=[IndexFilter(list(range(50,100)))])
get_colors('petal_length')

p = figure(title = "Iris Morphology", tools=["tap", "save"])
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'

p1 = p.circle(x="petal_length", y="petal_width",
         color="color", size=10,
         nonselection_alpha=1, nonselection_fill_color="color",
         selection_fill_color='blue',
         source=data, view=view)

output_file("iris.html", title="iris.py example")
show(p)
```

#### Screenshots or screencasts of the bug in action

colors showing up in order (low to high from left to right) as expected:
![bokeh_plot (4)](https://user-images.githubusercontent.com/49727347/84436430-6ce34580-ac01-11ea-9c39-290c167cabb8.png)

color order changes when selected (the issue):
![bokeh_plot (3)](https://user-images.githubusercontent.com/49727347/84436424-69e85500-ac01-11ea-9539-e656db5c0d59.png)

If we turn off the view, the order is preserved:
![bokeh_plot (2)](https://user-images.githubusercontent.com/49727347/84436391-5e952980-ac01-11ea-8443-11eb9cfb9653.png)

**Comment by mattpap** [comment]
This seems to be a duplicate of a recently fixed issue (I can't find it right now). @MichaelMonn, if you could verify this by installing and testing with bokeh 2.1-rc2 (`conda install -c bokeh/label/dev bokeh=2.1.0rc2`)?

**Comment by MichaelMonn** [comment]
@mattpap, I tried it with version 2.1.0rc2 and it appears to be resolved 👍 

Thanks so much for pointing this out!
