### ISSUE TITLE
[BUG] Typed Arrays returned as dicts

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10153]
Run `examples/howto/events_app.py`. For a lasso selection the `"x"` and `"y"` arrays are returned as dicts:

```
selectiongeometry(geometry={
    "type":"poly",
    "sx":[544,533,531,527,526,526,531,534,545,555,564,570,570],
    "sy":[135,142,145,152,160,165,184,191,201,205,208,210,210],
    "x":{"0":99.67,"1":97.43,"2":97.02,"3":96.21,"4":96,"5":96,"6":97.02,"7":97.63,"8":99.88,"9":101.92,"10":103.75,"11":104.98,"12":104.98},
    "y":{"0":79.95,"1":78.6,"2":78.02,"3":76.68,"4":75.14,"5":74.17,"6":70.51,"7":69.16,"8":67.24,"9":66.47,"10":65.89,"11":65.5,"12":65.5}
}, final=false)
```

Have seen Typed Arrays get represented in this format it other contexts. I would not be surprised to learn that this is a general issue in other places as well. It would be nice to return as "ndarray" types but would also settle for plain lists. 

cc @mattpap

**Comment by bryevdv** [comment]
@mattpap it's more that that, the values come back to python callbacks in the `event` as dicts

**Comment by philippjfr** [comment]
Right, I've seen that in a few places in fact. Should have filed an issue earlier but I've actually added a utility to handle this case [in Panel](https://github.com/holoviz/panel/blob/master/panel/io/model.py#L81) and an conditional branch [in HoloViews](https://github.com/holoviz/holoviews/blob/master/holoviews/plotting/bokeh/callbacks.py#L1128).
