### ISSUE TITLE
[BUG] Spectrogram app fails to run: : Property 'layer' does not exist on type 'WaterfallRendererView'.

### ISSUE THREAD

**Issue by luciotorre** [bokeh/bokeh#10167]
#### Description of expected behavior and the observed behavior
Spectrogram app fails to run.

#### Complete, minimal, self-contained example code that reproduces the issue

```
~/tmp/bokeh/examples/app$ bokeh serve --show spectrogram

 *** Pyaudio package not installed, using synthesized audio data ***

2020-06-14 17:53:15,004 Starting Bokeh server version 2.0.2 (running on Tornado 6.0.4)
2020-06-14 17:53:15,005 User authentication hooks NOT provided (default user enabled)
2020-06-14 17:53:15,007 Bokeh app running at: http://localhost:5006/spectrogram
2020-06-14 17:53:15,007 Starting Bokeh server with process id: 56306
Compilation failed:

spectrogram/waterfall.ts:52:22 - error TS2339: Property 'layer' does not exist on type 'WaterfallRendererView'.

52     const ctx = this.layer.ctx
                        ~~~~~
```

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Ubuntu 20.04
```
~/tmp/bokeh/examples/app$ python --version
Python 3.8.2
```

```
~/tmp/bokeh/examples/app$ head ../../CHANGELOG 
2020-04-21    2.0.2:
--------------------
```

```$ pip freeze
appdirs==1.4.3
bokeh==2.0.2
CacheControl==0.12.6
certifi==2019.11.28
chardet==3.0.4
colorama==0.4.3
contextlib2==0.6.0
distlib==0.3.0
distro==1.4.0
html5lib==1.0.1
idna==2.8
ipaddr==2.2.0
Jinja2==2.11.2
lockfile==0.12.2
MarkupSafe==1.1.1
msgpack==0.6.2
numpy==1.18.5
packaging==20.3
pep517==0.8.2
Pillow==7.1.2
progress==1.5
pyparsing==2.4.6
python-dateutil==2.8.1
pytoml==0.1.21
PyYAML==5.3.1
requests==2.22.0
retrying==1.3.3
scipy==1.4.1
six==1.14.0
tornado==6.0.4
typing-extensions==3.7.4.2
urllib3==1.25.8
webencodings==0.5.1
```

**Comment by bryevdv** [comment]
@luciotorre as it happens I just ran this example on both 2.0.2 and current 2.1 release candidate last night, both working as expected. My speculation is that that is a usage or configuration issue on your end that is causing custom extension compilation failure. In particular this error could be caused by (inadvertent) version mismatches between BokehJS runtime compiled agains. 

As such we should move this discussion to the Project Discourse for now:

https://discourse.bokeh.org/

If we can determine there is actually some reproducible issue, the we can alwasy re-open here.

**Comment by paulrleary** [comment]
Was this actually created as a new topic on Project Discourse?  

I am having the same issue.  In PyCharm, it is apparent that the import statements are failing in the TypeScript file waterfall.ts, as the modules are not recognized.  The TypeScript error terminal has the following output. If this is better suited for Project Discourse, we can revisit there.

Error:(1, 38) TS2307: Cannot find module 'models/renderers/renderer'.
Error:(2, 33) TS2307: Cannot find module 'models/mappers/linear_color_mapper'.
Error:(3, 21) TS2307: Cannot find module 'models/scales/scale'.
Error:(4, 21) TS2307: Cannot find module 'core/types'.
Error:(5, 22) TS2307: Cannot find module 'core/dom'.
Error:(6, 20) TS2307: Cannot find module 'core/properties'.
Error:(24, 36) TS2339: Property 'num_grams' does not exist on type 'WaterfallRenderer'.
Error:(24, 57) TS2339: Property 'tile_width' does not exist on type 'WaterfallRenderer'.
Error:(25, 32) TS2339: Property 'tile_width' does not exist on type 'WaterfallRenderer'.
Error:(25, 55) TS2339: Property 'gram_length' does not exist on type 'WaterfallRenderer'.
Error:(36, 31) TS2339: Property 'num_grams' does not exist on type 'WaterfallRenderer'.
Error:(36, 54) TS2339: Property 'tile_width' does not exist on type 'WaterfallRenderer'.
Error:(40, 60) TS2339: Property 'palette' does not exist on type 'WaterfallRenderer'.
Error:(41, 24) TS2339: Property 'plot_view' does not exist on type 'WaterfallRendererView'.
Error:(42, 24) TS2339: Property 'plot_view' does not exist on type 'WaterfallRendererView'.
Error:(43, 26) TS2339: Property 'plot_view' does not exist on type 'WaterfallRendererView'.
Error:(48, 10) TS2339: Property 'connect' does not exist on type 'WaterfallRendererView'.
Error:(48, 29) TS2339: Property 'change' does not exist on type 'WaterfallRenderer'.
Error:(48, 42) TS2339: Property 'request_render' does not exist on type 'WaterfallRendererView'.
Error:(52, 22) TS2339: Property 'layer' does not exist on type 'WaterfallRendererView'.
Error:(62, 57) TS2339: Property 'tile_width' does not exist on type 'WaterfallRenderer'.
Error:(90, 29) TS2339: Property 'tile_width' does not exist on type 'WaterfallRenderer'.
Error:(94, 39) TS2339: Property 'tile_width' does not exist on type 'WaterfallRenderer'.
Error:(98, 78) TS2339: Property 'latest' does not exist on type 'WaterfallRenderer'.
Error:(99, 36) TS2339: Property 'gram_length' does not exist on type 'WaterfallRenderer'.
Error:(100, 42) TS2339: Property 'tile_width' does not exist on type 'WaterfallRenderer'.
Error:(104, 54) TS2339: Property 'tile_width' does not exist on type 'WaterfallRenderer'.
Error:(104, 77) TS2339: Property 'gram_length' does not exist on type 'WaterfallRenderer'.
Error:(133, 20) TS2339: Property 'default_view' does not exist on type 'WaterfallRenderer'.
Error:(135, 10) TS2339: Property 'define' does not exist on type 'typeof WaterfallRenderer'.
Error:(143, 10) TS2339: Property 'override' does not exist on type 'typeof WaterfallRenderer'.
Information:Cannot find parent 'tsconfig.json'

**Comment by bryevdv** [comment]
@paulrleary not AFAIK. I'll note that the app continues to function correctly and run without issue with latest version 2.1.1 so this really seems like more of a PyCharm configuration issue than a Bokeh issue. So Discourse is definitely the more appropriate venue.

**Comment by paulrleary** [comment]
@bryevdv, thank you. I was able to get it working later yesterday, by reinstalling bokeh.  I believe it had something to do with a conflict between multiple installs of nodejs.
