### ISSUE TITLE
custom latex examples do not run

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10164]
Cannot get either example under `custom` to function with 2.1.0rc3 with a simple python call to the script. Both seem to compile things fine, but then report 
> Unhandled Promise Rejection: Error: Model 'latex_label.LatexLabel' does not exist. This could be due to a widget or a custom model not being registered before first usage.

in the browser.  Using this node on OSX:
```
nodejs                    14.4.0               h2c41780_0    conda-forge
```

If there is something beyond a simple `python foo.py` that is necessary to run these, then this issue should be re-tasked to add a README to each. Otherwise it can be changed to `bug`. If there is some unsupported range of build tools we need to find a way to warn better. 

To note: the `examples/models/file/latex_extension.py` example **does*** work.

cc @mattpap

**Comment by bryevdv** [comment]
@mattpap tangential to this if you could do a cross section of manual testing on linux in the next 24hrs it would appreciated.

**Comment by mattpap** [comment]
I already did a fair amount of testing. I may be able to do some more tomorrow.

**Comment by bryevdv** [comment]
> I already did a fair amount of testing. I may be able to do some more tomorrow.

If you have already done enough to your satisfaction just reporting a 👍 is fine then
