### ISSUE TITLE
[BUG] Incorrect type of `Select.options`

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10174]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.1.0

#### Description of expected behavior and the observed behavior
`Select.options` says that it accepts 
```python
Either(List(Either(String, Tuple(Either(Int, String), String))),
       Dict(String, List(Either(String, Tuple(Either(Int, String), String))))
```

In reality, it doesn't accept `Int`s there as
1. `Select.value` can only be a string
2. `Select` in BokehJS doesn't use integers at all

An easy solution is to just drop `Int` from that field descriptor.
A (maybe) better solution is to allow integers in `Select.value` and `Select` in BokehJS. But it would require remembering the right type and converting the currently selected value in HTML to it so the correct type is stored in the model and used in every callback.

**Comment by bryevdv** [comment]
My vote is just to remove it and simplify the type
