### ISSUE TITLE
[FEATURE] Allow any number in spinner using step=None

### ISSUE THREAD

**Issue by xavArtley** [bokeh/bokeh#10179]
In input type number specification an `any` step can be set allowing any number 

> A string value of any means that no stepping is implied, and any value is allowed (barring other constraints, such as min and max).

The actual behavior of Bokeh `Spinner`, throw a javascript error if `step` is set to `None`
Moreover the smallest `step` allowed is 1e-16 so a value of 1.532512855486e-16 will be rounded to 2e-16 at best

It could be intersting if the `step` is set to `None`, to allow the user to enter any number with any precision

**Comment by philippjfr** [comment]
Thanks for taking this on @xavArtley!

**Comment by mattpap** [comment]
If we are going to support this, then it would make sense to rename `Spinner` to `NumberInput`, or perhaps split off `Spinner` as a subclass of `NumberInput`.

**Comment by bryevdv** [comment]
This issue is closed by #10190 AFAIK but please re-open if I am mistaken.
