### ISSUE TITLE
Improve 3d extension example with echarts

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10171]
This project was recently brought to my attention:

https://echarts.apache.org/examples/en/index.html#chart-type-globe

We could possibly make a better 3d extension example (or even a few different ones) with that that, since vis.js is extremely limited.

cc @philippjfr perhaps it might even make sense to make some built-in/supported extensions at the HV level to connect Bokeh data source to these kinds of things (much more investigation/consideration needed first)

**Comment by philippjfr** [comment]
@MarcSkovMadsen has been playing around with this and even submitted an example for the Panel gallery here: https://github.com/holoviz/panel/pull/1286 So I suspect he'll have some thoughts.

**Comment by MarcSkovMadsen** [comment]
My first impression is that all Python plotting libraries including Bokeh and Plotly will have a hard time competing against ECharts on simple, aggregated datasets. It’s much more modern.

- super fast
- awesome looks
- transitions
- lots and lots of impressive examples.

How well it works for data exploration, reuse and combination of plots, interactivity including linked brushing etc. I don’t know.

It was pretty simple to support displaying ECharts json and PyeCharts via the Panel WebComponent. Would be super simple to convert to Bokeh model.

Adding interactivity on top I would not know. 

A lot of the advanced ECharts examples on the docs requires js in addition to json configuration. Don’t know if they can be developed in Python via PyeCharts.

If ECharts would be possible to support as an additional backend for HoloViews I would not know.

But support for ECharts/ PyeCharts would be a Killer Feature anywhere.

**Comment by bryevdv** [comment]
Seemed like a nice idea at the time, but without an involved champion to take the lead I am skeptical that this will move forward.
