### ISSUE TITLE
Widget selection + change x - Categorical axis possible?

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1017]
I was working on an app this weekend for a Hackathon called SkillCluster, that scraped job postings and computed how many times technical skill 'foo' also required technical skill 'bar' and wanted to visualize a dataset that consisted in a table with this structure:

| primary_term        | secondary_term          | frequency  |
| ------------- |:-------------:| -----:|
| python     | R | 60 |
| python     | java      |   10 |
| java | maven      |   70 |

So, I wanted a Select widget for the primary term and display a bar chart of the secondary terms associated to that primary term and their frequency. e.g.

![screen shot 2014-08-17 at 9 00 46 pm](https://cloud.githubusercontent.com/assets/4940549/3946800/72771b22-267c-11e4-9dd0-b908edb4011a.png)

So, the categories in the x axis should change every time a select a different term in the Selection widget.

I wasn't able to make that work, so, I wanted to ask if that was actually supported, since I don't seem to find an example that does that. My question is: Is it possible to have a Selection widget that modifies the `x`Categorical axis?

If the answer is `yes`, then I can share my code to find out what I was doing wrong.

**Comment by birdsarah** [comment]
@chdoig - this is do-able - I made some examples here: http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/tests/1017_select_widget_categorical_axis.ipynb

In particular with the new callbacks, we can use the following in our js:
```javascript
x_range.set('factors', factors[val]);
```

can we close?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by shubham0420** [comment]
@birdsarah your link is not working. Did any one find solution?

**Comment by shubham0420** [comment]
Hi got the answer to this.
plot.x_range.factors = ['a','b','c','d'] 
and your axis will change.
