### ISSUE TITLE
[BUG] `GeoJSONDataSource` incorrectly processes `MultiPolygon` geometry type

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10193]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.1.0

#### Complete, minimal, self-contained example code that reproduces the issue
```python
from bokeh.io import show
from bokeh.models import GeoJSONDataSource, GMapOptions
from bokeh.plotting import gmap

data = """{
  "type": "FeatureCollection",
  "features": [
    {
      "id": "0",
      "type": "Feature",
      "properties": {"plotted_data": 98.7805281},
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [-98.11372330298127, 30.48557591185999],
              [-98.11336081363682, 30.48592948588511],
              [-98.11319281272974, 30.486219485691766]
            ]
          ],
          [
            [
              [-98.10916428343725, 30.492520477204575],
              [-98.10904979183817, 30.49274448101661],
              [-98.10904600029392, 30.492747999424935]
            ]
          ]
        ]
      }
    }
  ]
}
"""
data_source = GeoJSONDataSource(geojson=data)

map_options = GMapOptions(lat=30.2861, lng=-97.7394, map_type="roadmap", zoom=11)

plot = gmap(%YOUR_API_KEY%, map_options)

plot.patches('xs', 'ys', source=data_source,
             line_color='black', line_width=0.25, fill_alpha=1)

show(plot)
```

`GeoJSONDataSource._add_geometry` has this function:
```typescript
    function flatten(acc: Position[], item: Position[]) {
      return acc.concat([[NaN, NaN, NaN]]).concat(item)
    }
```
And it's incompatible with this code in `proj4/lib/checkSanity.js`:
```javascript
        if (typeof Number.isFinite === 'function') {
            if (Number.isFinite(num)) {
                return;
            }
            throw new TypeError('coordinates must be finite numbers');
        }
```

Given that the same `flatten` function is used for the `MultiLineString` geometry type, it might also be broken.

#### Stack traceback and/or browser JavaScript console output
```
Uncaught (in promise) TypeError: coordinates must be finite numbers
    at checkCoord (checkSanity.js:13)
    at Object.default_1 [as default] (checkSanity.js:4)
    at Object.transform [as default] (transform.js:18)
    at transformer (core.js:10)
    at Object.forward (core.js:81)
    at project_xy (projections.js:32)
    at Object.project_xsys (projections.js:44)
    at PatchesView.set_data (glyph.js:187)
    at GlyphRendererView.set_data (glyph_renderer.js:123)
    at GlyphRendererView.lazy_initialize (glyph_renderer.js:68)
```

**Comment by bryevdv** [comment]
Was this working before 2.1?

**Comment by p-himik** [comment]
It was working in 1.4 and stopped in 2.0.
The culprit is 83301c115cf9154abac2d48c8995f90927804e52 that has updated the `proj4` dependency. In `<2.4`, it wasn't doing any checks, but it introduced them in 2.4.5-alpha in https://github.com/proj4js/proj4js/commit/42fae04d1257b9689fa372ea674a3a749636d468

**Comment by p-himik** [comment]
An easy fix would to not call `wgs84_mercator.forward` if both of the coords are `NaN`. But I'm not sure what to do when just one of them is `NaN`. But crashing the whole page is probably not the way to go. Report it via `console.error` - sure. But the end user will never see this error because there's nothing in the UI that says that something's wrong.

**Comment by mattpap** [comment]
@p-himik, do you think that PR #10198 is sufficient to fix this issue, or does `GeoJSONDataSource` need a better parser?

**Comment by p-himik** [comment]
@mattpap LGTM :+1:
