### ISSUE TITLE
[FEATURE] line_dash vectorizable where appropriate

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10203]
For "multi" glyphs and some annotation, it is currently only possible to specify a single line dash style. It could be possible to make this property "vectorized" so that e.g. different individual lines in a `multi_line` can have different dash styles. 

The slight trickiness here will be that dash styles are expressed as lists of numbers, so vectorizing dash styles means accepting "lists of lists" which is not the case for any other property AFAIK. Additionally there are some string aliases for some of the common simple patterns, so those will also have to be handled.

**Comment by mytan310** [comment]
Hello, is this a possible feature to work on? I'd like make an attempt to work on it and finish by the month (:

**Comment by bryevdv** [comment]
@mytan310 is it not necessary to leave these messages on multiple issues all over the tracker. If an issue is opened, and no-one is assigned or has indicated in the comments that they intend to work on it then please feel free to submit a PR without asking.

**Comment by mytan310** [comment]
@bryevdv Sorry about that, I thought I should let you know before starting working on the task. Thank you for letting me know, I will keep that in mind in the future for other tasks to just submit a pull request (:

**Comment by bryevdv** [comment]
No worries @mytan310 , look forward to your contributions!

**Comment by bryevdv** [comment]
@mattpap I know there was some work recently on scalar/vectorized properties. Should this issue still be open? If so, should it be `GFI`?

**Comment by mattpap** [comment]
This will done as a side effect of my current work. For simplicity, I unified visual properties in each "class", so that e.g. `LineVector` has only vectorized properties.
