### ISSUE TITLE
Naming for new coordinate systems

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10209]
Follow on work from #10202 to finalize naming before releasing.

**Comment by mattpap** [comment]
ref https://github.com/bokeh/bokeh/pull/10202#issuecomment-646948920

**Comment by bryevdv** [comment]
Looking again more closely at the changes in #10202 I can more succinctly delineate the important facts:

* A `Frame` collects all x-scales and y-scales on one place (what all renderers may use) 
* A `CoordinateTransform` narrows things down to one particular x-scale and y-scale (what a specific render actually uses)

With a time machine, I'd say that what is currently called `Frame` might be `FrameSet` or `FrameCollection` and the single coordinate transform be on `Frame`. But, the current `CoordinateTransform` is perfectly descriptive and fine, so I don't think that needs any change. 

However, I have *never* encountered "scope" in any context remotely similar to this. So I do think that should `.scope` should change to something else. Some ideas:

* `renderer.local_frame` (a specific narrowing of the frame)
* `renderer.pane` (a thing "inside" a a frame)

or even just "coordinates" might make sense given how it is used:

* `renderer.coordinates.map_to_screen` 

seems very readable.
