### ISSUE TITLE
BEP 7: Decision making

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10214]
ref: https://github.com/bokeh/bokeh/wiki/BEP-7:-Decision-Making

In order to apply for organizational GH sponsor status, I had to provide a model for group decision making. I would like to codify that model that I sent them (modulo refinements resulting from this discussion) publicly in BEP 7.

#### Rationale

This proposal aims to make the high level decision making of the Bokeh core team and NumFOCUS committee more transparent and accountable.

#### What is the process

The model I described was more or less this:

> Official decision making follows a model of unanimous consent. Technical or financial proposals are put before the relevant team. Proposals may be put forth as Issues, PRs, topics on the Project Discourse, or as an email to all team members, as appropriate.  If there is no comment or objection within first timebox, then the proposal is deemed to pass. If there is comment or objection, then discussion may proceed for the duration of a second timebox. If any objections are resolved n that time, the proposal is deemed to pass. Otherwise, I vote will be taken among all the team members.
>
> The timebox durations may be stipulated by the proposer, however may not be shorter than three days. 

#### When will this process apply

* any expenditure of funds always be a recorded decision
* "big" technical proposals  (specifically: if any team member asks for a recorded decision)

This process is not meant to impede day-to-day development. Standard work for bugfixes and small features will not normally come under this process, and only require an approval before merge. It is expected most recorded decisions will be financial matters. 

#### Where are decisions recorded

I propose that a read-only public Google sheet be created to record official decisions. The sheet should have a row for each proposal gives:

* date
* brief proposal desription
* any relevant links or references
* resolution (agreed by consent, agreed by vote, denied by vote)

The spreadsheet should be linked in the BEP document. 

cc @bokeh/core

**Comment by birdsarah** [comment]
+1 from me.

**Comment by bryevdv** [comment]
@bokeh/dev I have made a first draft of the actual BEP page here:

https://github.com/bokeh/bokeh/wiki/BEP-7:-Decision-Making

Please leave and comments, suggestions for improvements, or questions here.

**Comment by bryevdv** [comment]
In the spirit of the process outlined there I will plan to mark the proposal as "Implemented" on July 10, if there is no comment or disagreement.

**Comment by birdsarah** [comment]
Read it. LGTM.

**Comment by mattpap** [comment]
> In the spirit of the process outlined there I will plan to mark the proposal as "Implemented" on July 10, if there is no comment or disagreement.

I propose extending this time to the 15th (Wednesday), as I would like to have some more time to address my concerns regarding this proposal.

**Comment by mattpap** [comment]
> Team members may express votes immediately. If enough +1 votes are expressed before the timebox is expired, then the proposal passes.

Even if there's an overwhelming vote for or against a matter, I think that the official acceptance or decline of a proposal should happen at the the end of the established timebox, otherwise there's a risk that unpopular opinion, which could potentially make others reconsider their position, may not be voiced or seen at all. This is especially given the short default (3 day) time frame.

**Comment by bryevdv** [comment]
> Even if there's an overwhelming vote for or against a matter, I think that the official acceptance or decline of a proposal should happen at the the end of the established timebox, otherwise there's a risk that unpopular opinion, which could potentially make others reconsider their position, may not be voiced or seen at all. This is especially given the short default (3 day) time frame.

This is in fact my natural inclination, but let me explain why I changed it to that add that "short-circuit clause". Recently after a very-useful and productive (free) video call with a grant writing expert, some of us wanted to engage a few hours of (paid) services to help with the next CZI proposal in depth. They wanted some assurances of a contract from NF by end of week since the submission deadline itself is not that far off. Putting in three days, plus potential delay on the NF side could have pushed things well past that. TLDR; occasionally there are actual time sensitive decisions that need to be made quickly (if they can be). So what is the right compromise here? Perhaps this short-circuit clause could apply only to the NF committee decisions?

@birdsarah 👍 done

**Comment by bryevdv** [comment]
I have added a note regarding short-circuit vote permitted for expedient financial decisions, and marked the BEP as implemented.
