### ISSUE TITLE
[BUG] Periodic callback don't stop in Django

### ISSUE THREAD

**Issue by Hoxbro** [bokeh/bokeh#10218]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
  - bokeh=2.1.0
  - panel=0.9.6
  - django=3.0.7
  - django-channels=2.4.0

#### Description of expected behavior and the observed behavior
As first reported in holoviz/panel#1125 I have a Django site which have a widget with a periodic callback, so a plot is updated every 10 seconds. But I have noticed that when I leave the site without stopping the periodic callback it keeps running forever in Django, where Panel is running for ~30 seconds.

It was [mentioned](https://github.com/holoviz/panel/issues/1125#issuecomment-645404719) by @philippjfr that it could be related to server cleanup handlers which aren't correctly triggered when running via Django.

#### Complete, minimal, self-contained example code that reproduces the issue
See [periodic_example.zip](https://github.com/bokeh/bokeh/files/4813615/periodic_example.zip). The example is using Panel right now, I hope this is okay but if it is needed I can try to remove the Panel part from the code. 

To run the example with Django use the command `python manage.py runserver` and to run it with Panel use the command `panel serve panel_example.py` 

#### Screenshots or screencasts of the bug in action
**Panel**
![panel](https://user-images.githubusercontent.com/19758978/84885303-24110e00-b093-11ea-9f65-825569f78474.gif)

**Django**
![django](https://user-images.githubusercontent.com/19758978/84885377-41de7300-b093-11ea-992f-e386624bd830.gif)

**Comment by philippjfr** [comment]
Thanks @Hoxbro. I've started looking at this already and the basic problem is that the Django server does not register a periodic callback which checks for closed sessions and then cleans up after them. I've not yet found a good way to fix that but will keep looking.
