### ISSUE TITLE
[BUG] Misplaced Rects when using incomplete categorical ranges

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10219]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.1.0

#### Description of expected behavior and the observed behavior
If you plot rects and provide factor ranges to the figure that don't include some of the data points, the rects will be misplaced.
In the example below, notice how the circles are positioned properly.

#### Complete, minimal, self-contained example code that reproduces the issue
```python
from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

ds = ColumnDataSource(dict(x=list('AAABBBCCC'), y=list('ABCABCABC')))

p = figure(x_range=list('BC'), y_range=list('CB'))
p.rect(x='x', y='y', width=0.9, height=0.9, source=ds)
p.circle(x='x', y='y', radius=0.2, color='red', source=ds)

show(p)
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/4410314/85312454-85841300-b4bf-11ea-8c25-2568fad9d61a.png)

**Comment by bryevdv** [comment]
Does this affect vbar too or just texts? (I guess is be surprised it was not noticed sooner if it does affect vbar)

**Comment by p-himik** [comment]
Doesn't seem to affect vbars.
