### ISSUE TITLE
Rename main branch

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10224]
In light of current events, many organizations are making positive moves toward more inclusion and the removal of terminology with contentious historical baggage. [Github is changing the default branch name to `main`](https://www.bbc.com/news/technology-53050955), with Microsoft following more widely. The Rapids project will also be making such a change, and others as well. 

I propose that we rename `master` to `main` across all of the repositories in the Bokeh organization that are not forks. I propose we start with smaller/lesser used repositories to gain experience and practice, and and with this one. 

This is especially timely as we are planning to change our branching/milestone process to move dev off of the main branch anyhow.  A walkthrough of the steps required to do this can be found here:

https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

cc @bokeh/core 

- [x] [bokeh/blog.bokeh.org](https://github.com/bokeh/blog.bokeh.org)
- [x] [bokeh/bokeh](https://github.com/bokeh/bokeh)
- [x] [bokeh/bokehjs-examples](https://github.com/bokeh/bokehjs-examples)
- [x] [bokeh/bokeh.org](https://github.com/bokeh/bokeh.org)
- [x] [bokeh/bokeh-notebooks](https://github.com/bokeh/bokeh-notebooks)
- [x] [bokeh/demo.bokeh.org](https://github.com/bokeh/demo.bokeh.org)
- [x] [bokeh/FDV-notebooks](https://github.com/bokeh/FDV-Notebooks)
- [x] [bokeh/ipywidgets_bokeh](https://github.com/bokeh/ipywidgets_bokeh)
- [x] [bokeh/jupyter_bokeh](https://github.com/bokeh/jupyter_bokeh)
- [x] [bokeh/pm](https://github.com/bokeh/pm)
- [x] [bokeh/rbokeh](https://github.com/bokeh/rbokeh)
- [x] [bokeh/bokeh-scala](https://github.com/bokeh/bokeh-scala)
- [x] [bokeh/bokeh-scala-sample](https://github.com/bokeh/bokeh-scala-sample)
- [x] [bokeh/slack-invite.bokeh.org](https://github.com/bokeh/slack-invite.bokeh.org)

Remaining repos are archived or forks that we should probably leave intact.

**Comment by birdsarah** [comment]
100% yes. Mozilla also doing the same: https://bugzilla.mozilla.org/show_bug.cgi?id=1643142

**Comment by bryevdv** [comment]
@bokeh/dev I've started doing the simple ones, it has been pretty painless. The only one I slightly worry about is `bokeh-notebooks` since there are external refs to master in nbviewer and mybinder, etc. but apparently GH has started forwarding things to the default branch now, so things should be OK. Still I will wait a bit to work on that one. 

@mattpap FYI I will plan to update the scala, R, and jupyter extension repos tomorrow. Here is the instructions I have been following

**Comment by bryevdv** [comment]
@bokeh/dev OK I think all the  most trivial ones are changed. That leaves 

* rbokeh -- will update after hearing back from @hafen about the two open PRs there
* bokeh-notebooks -- will do this sometime in the next week
* bokeh -- this will require some planning, we will need to clear most/all open PRs first

**Comment by mattpap** [comment]
>  this will require some planning, we will need to clear most/all open PRs first

Is this really necessary? Most PRs are targeting `branch-2.*` anyway. Only one target `master`, which simply should be re-based.

**Comment by bryevdv** [comment]
> Is this really necessary?

Nope, just still shaking off eight years of habits. I will try to have all the remaining ones done by next week's meeting.

**Comment by bryevdv** [comment]
OK, this has been done for `bokeh/bokeh`

**Comment by bryevdv** [comment]
OK I have set the default branch to `main` on all Bokeh repos, an d I have also deleted the `master` branch on all Bokeh repos except `bokeh-notebooks`. Unfortunately, if GH is automatically redirecting deleted branches to the default, it is still not enough to make the MyBinder tutorials be able to launch correctly. I have pushed a snapshot of `main` back to `master`. I'll ping the binder folks so see if they have any good/quick fixes on their end. Otherwise we may have to wait an see if GH offers any features to help better support moves like this in the near futures. Worst case we have to update old docs and that would be a pain.

**Comment by mattpap** [comment]
> OK I have set the default branch to main (...)

Well, except `bokeh` repo. This will force all contributors to set the base of their PRs to the active `branch-*`, which will cause them and us a lot of headache.

**Comment by bryevdv** [comment]
@mattpap yes except this one which remains `branch-2.3` per our new developing branch policy.

**Comment by bryevdv** [comment]
ref: https://github.com/jupyterhub/binderhub/issues/1145#issuecomment-682561508 MyBinder consider short-term workaround on their end
