### ISSUE TITLE
[BUG] events_app.py is broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10221]
With 2.1.1 release, this line fails:
```
        const {to_string} = Bokeh.require("core/util/pretty")
```
wiht the error:
```
Error: Cannot find module 'core/util/pretty'
```
cc @mattpap is this some old, bad usage, that should have already previously been udpated in the example? Or was is this a regression that should work and was broken #10188 ?  

My guess is the former, and that this should be using `import` but I wanted to check for sure before labeling.

Edit: perhaps not, since the code in a `CustomJS` is not a module, import does not seem to work.

**Comment by mattpap** [comment]
I'm pretty sure there's a mismatch between the version of events_app example you are running and bokehjs' version. `core/util/pretty` is available on `master` and the example was updated accordingly. In release-2.1 branch there should be no such module and the example should use `JSON.stringify()`.

**Comment by mattpap** [comment]
`import ` can only be used at the top-level of modules, so unfortunately we can't use it in `CustomJS`. However, one can use dynamic imports, i.e. `await import()`,

**Comment by bryevdv** [comment]
You're right, I was looking at master. New habits take time
