### ISSUE TITLE
Bokeh 2.0.1 editable table source does't update

### ISSUE THREAD

**Issue by danwang123** [bokeh/bokeh#10223]
I am using bokeh 2.0.1, after I edit my datatable, the source.data keep the original data source. Could you help to check

**Comment by bryevdv** [comment]
@danwang123 as stated in the issue template, please use the public Discourse for asking support / help-desk style questions:

https://discourse.bokeh.org/

However, please note: I ti will not be possible for any to assist you without *must more information*. Specifically, you will need to provide *actual code*. It is not possible to speculate about anything in response to a question as vague as the one above.
