### ISSUE TITLE
[BUG] bokeh js v2.x legacy libraries

### ISSUE THREAD

**Issue by asirjoosingh** [bokeh/bokeh#10233]
Hello,

I posted a [more detailed version of this question](https://discourse.bokeh.org/t/bokeh-2-x-legacy-js/5862) on the Bokeh Discourse and it was suggested that I open an issue here.

*Main Issue*
Using Bokeh version 2.02 or version 2.1.1 I am unable to load the Bokeh legacy libraries. I tried
`>bokeh.resources.Resources(mode="cdn",legacy=True).render()`
which gives a list of libraries including links of the form
https://cdn.bokeh.org/bokeh/release/bokeh-2.1.1.legacy.min.js
These links do not appear to be valid (getting 403 error on access) for these two versions but they are accessible for v2.0.0.

*Additional Question*
I also asked an additional question about where to find documentation on the differences between the main versions of a Bokeh JS library and its corresponding legacy version (e.g. between `bokeh-2.1.1.legacy.min.js` and `bokeh-2.1.1.min.js`). How can one determine what functionality is lost using the legacy versions? Any help would be greatly appreciated.

Thanks very much: I really appreciate the continued support for the legacy versions - we have an audience that is restricted to IE11 and it's great to still have an option.

Andrew

**Comment by bryevdv** [comment]
@mattpap can you comment on the additional question? I will work on publishing the missing legacy bundles tomorrow.

**Comment by bryevdv** [comment]
@asirjoosingh Legacy resources for all the missing versions should be available now please report back if there are any issues. 

I will leave this open as `discussion` for now so @mattpap can chime in though AFAIK there are no features lost using the legacy bundles (they are simply larger and possibly slightly less efficient in some places)

**Comment by asirjoosingh** [comment]
Great, thank you. Links all seem to be working now - much appreciated!

**Comment by asirjoosingh** [comment]
@bryevdv I'm having some issues with the legacy versions that I tried to distill down to a minimal example. Python is version 3.7.7 for all tests, and I tested using legacy libraries for Bokeh versions 2.0.0, 2.0.2 and 2.1.1.

The minimal example attempts to use `bokeh.embed.components` to template in a basic Bokeh figure in a basic HTML template. I'm testing on Chrome and IE11 on Windows 7. The plot shows up for versions 2.0.0 and 2.0.2 but not for 2.1.1, but I get console errors for all cases which have been hanging me up when I'm trying to debug my actual application (using widgets). (Note this minimal example works with the "modern" libraries in Chrome and on both Chrome and IE with v 1.4.0.)

**template.html**
```
<!doctype html>
<html lang="en">

  <head>
    <title>Test</title>

  {{ bokeh_resources | safe }}

  <script type="text/javascript">
      Bokeh.set_log_level("debug");
  </script>
  {{ bokeh_script | safe }}
  </head>

  <body>
  <h3>before plot</h3>
  {{ bokeh_div["figure"] | safe }}
  <h3>after plot</h3>
  </body>
</html>
```

**testlegacy.py**
```
import numpy as np
from jinja2 import Template
from bokeh.embed import components
from bokeh.models import ColumnDataSource
from bokeh.resources import Resources
from bokeh.plotting import figure

x=np.linspace(0,4*np.pi,100)
y=np.sin(x)
source=ColumnDataSource(dict(x=x,y=y))
fig=figure(width=320,height=180)
line=fig.line(x="x",y="y",source=source)

resources=Resources(mode="cdn",legacy=True).render()
script,div=components({"figure":fig})

with open("template.html","r") as f:
    template=Template(f.read())

with open("test.html","w") as f:
    f.write(template.render(bokeh_resources=resources,bokeh_script=script,bokeh_div=div))
```

The console output is identical for 2.0.0 and 2.0.2 so I include one screenshot for both of those, then a separate screenshot for 2.1.1 in Chrome and IE. Note IE is quiet about 2.0.0 and 2.0.2 (and the plot shows up) but when I try to introduce widgets I get the same errors that it complains about in 2.1.1. Screenshots are below.

Any help or guidance would be greatly appreciated. Thanks for the help thus far!
Andrew

_v 2.0.0 output_
![output200](https://user-images.githubusercontent.com/2474739/86199211-82280180-bb27-11ea-8a53-5c5200b0b0b6.jpg)

_v 2.1.1 output_
![output211](https://user-images.githubusercontent.com/2474739/86199263-9bc94900-bb27-11ea-804b-d332a7d002a2.jpg)

_v 2.1.1 output (IE)_
![output211-ie](https://user-images.githubusercontent.com/2474739/86199269-9f5cd000-bb27-11ea-9fae-edd6d2bd8357.jpg)

**Comment by bryevdv** [comment]
cc @mattpap 

Not sure these will make a difference, but some things to try in order to probe the issue:

* try a simpler example with `show` instead of embedding with `components` 
* try `mode="inline"` instead of `"cdn"

**Comment by mattpap** [comment]
Legacy bundles are currently completely broken, including on modern browsers, and non-trivially broken on proper legacy browsers. This will get fixed, as legacy support is required for my client work. However, in the long term the current approach to legacy support is unsustainable and either needs to be dropped or rethought from the ground up.

**Comment by asirjoosingh** [comment]
Thanks for the information @mattpap - looking forward to tracking the issue in future releases.

Just FYI in case it's useful @bryevdv I tried your suggestions and observe exactly the same results using CDN for v 2.0.0 2.0.2 and 2.1.1 using `show`. I did notice that `Resources(mode="inline",legacy=True)` and `Resources(mode="inline",legacy=False)` give exactly the same output (the modern libraries) for all three versions.

Thanks again for the efforts and the responses. I wish I could help but I don't have much JS experience but if you need me to do any testing please let me know.

**Comment by mattpap** [comment]
TODO:

- [ ] fix transpilation of ND arrays to ES5 (https://github.com/bokeh/bokeh/pull/10350#issuecomment-665916248)
