### ISSUE TITLE
Improve responsiveness when hovering over many points

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#10234]
#### My Pain

I would like to use Bokeh plots in my applications but sometimes they feel slow and sluggish.

An example of this is plots with many points. The many points by them selves is not the main problem. The main problem is hovering.

If the users hovers over the Bokeh plot it becomes unresponsive and my fan turns on. 

I suspect its due to collecting and showing tool tips for many points

My fear is that my users turn away from my apps because they appear slow or dead.

#### Example

https://ferret.pmel.noaa.gov/osmc/dashboard

I hover and the drag the plot. The first time its OK responsive. The second time it takes 10 secs before the plot moves.

![bokeh-slow](https://user-images.githubusercontent.com/42288570/85915787-ce82f100-b84a-11ea-893f-cbb81a084f73.gif)

#### Another Example

Its the same problem at awesome-panel.org in the Kickstarter Dashboard. If I want to select some points to filter on the hovering often steps in first and I have to wait 5-10 secs for the plot to respond.

![image](https://user-images.githubusercontent.com/42288570/85915794-f1ada080-b84a-11ea-996a-5de131f1b3c9.png)

#### Solution

Fix this :-) For example by 

- fixing the cause if there is a cause or
- setting a max on the number of points to show hover information for.

FYI @philippjfr

**Comment by mattpap** [comment]
> https://ferret.pmel.noaa.gov/osmc/dashboard

For me it hangs as soons I attempt to use the hover tool. Hover tool/Tooltips are currently extremely inefficient, primarily due to inefficient manipulation of DOM nodes. When that's solved, we will be able to look into further optimizations, e.g. doing computations off main thread.

> setting a max on the number of points to show hover information for.

Various policies, like limiting the number of entries showed, were supposed to be implemented for awhile now.
