### ISSUE TITLE
Add support for rendering in environments lacking DOM

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10248]
In particular support:

1. WebWorkers
2. Node with a canvas polyfill

**Comment by bryevdv** [comment]
@mattpap do you still intend to pursue this? I have not perceived any demand to do e.g. rendering in nodejs apps lately

**Comment by mattpap** [comment]
With recent shift towards tighter integration with DOM/CSS (e.g. PR #13828) and upcoming accessibility (CZI) and theming (holoviz and CZI) work, it won't be possible to achieve (2) anymore. This is fine and such ideas only held us back on the browser front. (1) is still very desirable (aka. multi-threading support in bokehjs), but that needs its own discussion and actionable issues.
