### ISSUE TITLE
Deprecate Oval?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10252]
We currently have both `Oval` and `Ellipse`, which are nearly identical. There have been approximately ~zero support questions or issues about either of these (that I have observed) in the last 8 years, so my opinion is that there is little reason to maintain both. 

I would propose to deprecate `Oval` (which has the more complicated implementation) now, and remove it in Bokeh 3.0. 

Thoughts @bokeh/dev?

**Comment by mattpap** [comment]
Lack of support questions is not a good indicator in my opinion. Maybe ellipse-like glyphs are just flawless? However, `Oval` definitively has to go, given that it doesn't provide any functionality over `Ellipse`, except for being 25% shrunk for some reason.

**Comment by bryevdv** [comment]
@mattpap Right I don't think is a perfect indicator, but absent actual telemetry, it's just one of the few we have at all. 

Let's see if anyone has strong opinions otherwise but it seems like we are on the same page.
