### ISSUE TITLE
Passing DataFrame.to_dict() type to ColumnSourceData.stream Doesn't Cause Graph to Refresh

### ISSUE THREAD

**Issue by bjwong** [bokeh/bokeh#10258]
I have a pandas.DataFrame that I converted to a dictionary using pandas.DataFrame.to_dict(). The resultant dictionary is something that while Bokeh's ColumnSourceData.stream() will accept, it does not cause the graph to dynamically refresh as stream() is called.

I had to break out the data in the DataFrame into a list, transpose it, then use a for...loop to generate a new dictionary with variable-based key names in order get it to work with the stream() function. The reason is to_dict() creates a dictionary like so:

myDict = { 'x': 1}

But Bokeh's stream function expects the format of the dictionary to be the following:

myDict = {'x': [1]}   #Note that "figures one" is enclosed in square brackets.

I don't know if this is a Bokeh limitation or a limitation of pandas. Needless to say, this took me over 48 hours to figure out.

Thanks.

**Comment by bryevdv** [comment]
@bjwong the values in the stream update have to be lists or arrays. I think this is fairly well laid out in the docs:

https://docs.bokeh.org/en/latest/docs/reference/models/sources.html?highlight=stream#bokeh.models.sources.ColumnDataSource.stream

Where the given example explicitly shows lists in use, and where the new data is described as:
> a mapping of column names to ***sequences of new data*** to append to each column.
All columns of the data source must be present in new_data, with ***identical-length*** append data.

In the future, if you have questions, the Bokeh project Discourse is a good place to obtain community support:

https://discourse.bokeh.org/

Also FWIW I think it's possible to convert the starting data to the required format more simply than you describe, e.g.
```
In [1]: new_data = dict(x=1, y=2)

In [2]: new_data
Out[2]: {'x': 1, 'y': 2}

In [3]: new_data = { key: [val] for key, val in new_data.items() }

In [4]: new_data
Out[4]: {'x': [1], 'y': [2]}
```

**Comment by bjwong** [comment]
May I make a suggestion? Maybe provide a note that pandas.DataFrame.to_dict() doesn't create quite the data type that stream() expects? I didn't know this and just assumed that because pandas seems so oft-referenced in the example codes that this was not an issue.

I like the In[3] suggestion. We have keys in our data log files that could change without warning, so I'm trying to keep everything as variable-based as possible to reduce headaches in the future. This enables me to keep doing so.
