### ISSUE TITLE
[FEATURE] Add a DocumentReady event

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#10265]
In many cases you want your application to display something as quickly as possible. In the current design of bokeh server everything has to be initialized in the initial request. One solution to alleviate this issue would be to defer any expensive computation on initialization until after we have actually rendered something to screen. However currently there is no way to tell when the frontend is done initializing the rendered Document. 

Therefore I propose adding a BokehEvent which signals when the Document is ready (or in BokehJS terminology, when it is idle).

**Comment by bryevdv** [comment]
Noting that the work in #10266 was only for a Python/Bokeh server event, not yet for `js_on_event`

**Comment by philippjfr** [comment]
Right, should have checked this but a Document does not yet have the ability to register js callbacks on it.

**Comment by bryevdv** [comment]
@philippjfr this issue got closed is there a (new?) issue for a JS init event? (I actually thought there was a different older issue about this than this one but I can't find it if so)

**Comment by kszlim** [comment]
@philippjfr I was wondering the same thing, I was trying to register a JS callback on this event, but didn't find any documentation that implied it didn't work until I came across this issue.
