### ISSUE TITLE
[BUG] compiler.json is half of the shipped release artifact's weight

### ISSUE THREAD

**Issue by lmeyerov** [bokeh/bokeh#10267]
We realized ~half of the bokeh conda distro (50MB) is a seemingly unnecessary  file `compiler.json`: https://discourse.bokeh.org/t/the-purpose-of-compiler-json/4721 . Additional files may also be unnecessary according to https://jcristharif.com/conda-docker-tips.html , but afaict, compiler.json is a lot of bang for very little buck. This is becoming a performance tax on the pydata ecosystem, such as install speed, docker builds, CI, etc.

Thread: https://twitter.com/xhochy/status/1280488453780770816

Real-world docker repro: 

* before: https://hub.docker.com/layers/graphistry/graphistry-forge-base/v2.30.22/images/sha256-d7cb047757e6c4cc38687a2263adbe49b49a502a13347d1f249ad96afdcde729?context=repo

* after: https://hub.docker.com/layers/graphistry/graphistry-forge-base/v2.30.23/images/sha256-a03c4ab2836a9da1629bbcb9571166566ae9c4015d24f1a7419c0658febcf308?context=repo

* note this line for current work around in `after` in the big layer: 
``` 
find /conda -follow -type f -name '*.js.map' -delete   \
  && ( find /conda/envs/rapids/lib/python3.7/site-packages/bokeh -follow -type f -name '*.js' ! -name '*.min.js' -delete || echo "rm bokeh fail 1" )    \
 && ( find /conda/envs/rapids/lib/python3.7/site-packages/bokeh -follow -type f -name 'compiler.json' ! -name '*.min.js' -delete || echo "rm bokeh fail 2" )

```

I'm not familiar enough with the project nor compiler.json on the appropriate fix, but thought the heads up would help.

**Comment by bryevdv** [comment]
@lmeyerov I think you are simply using old package versions? The latest conda package (and for several releases before) are nowhere near 50mb:
```
-rw-r--r-- 1 bryan staff 5.4M Jun 28 11:51 bokeh-2.1.1-py38_0.conda
-rw-r--r-- 1 bryan staff 6.7M Jun 22 14:56 bokeh-2.1.1-py_0.tar.bz2
```
and there is no compiler.json anywhere inside them, either:
```
~/anaconda/pkgs master*
(dev) ❯ cd bokeh-2.1.1-py38_0

~/anaconda/pkgs/bokeh-2.1.1-py38_0 master*
(dev) ❯ find . -name compiler.json

~/anaconda/pkgs/bokeh-2.1.1-py38_0 master*
(dev) ❯ cd ../bokeh-2.1.1-py_0

~/anaconda/pkgs/bokeh-2.1.1-py_0 master*
(dev) ❯ find . -name compiler.json

~/anaconda/pkgs/bokeh-2.1.1-py_0 master*
```
You can also see that .json files are now excluded in the manifest:

https://github.com/bokeh/bokeh/blob/54b710bc253a092ad04f4c628f9fc0ad07d8081b/MANIFEST.in#L29


I am going to go ahead and close this on the assumption that that is the case, based on the information I gave above. If you can demonstrate otherwise (with details), we are happy to re-open.

**Comment by lmeyerov** [comment]
This is in Nvidia RAPIDS pydata standard distro from 1mo. Will dig.

**Comment by bryevdv** [comment]
@lmeyerov Bokeh was updated to 2.1.1 in RAPIDS just last week. Before that it was using a some 1.x version.

**Comment by lmeyerov** [comment]
Yep looking at it now: https://github.com/rapidsai/cuxfilter/commit/28592f2c3da52fb4b22fc574f21b75b92e8eab44

**Comment by bryevdv** [comment]
Would love to hear back any actual differential comparison between previous and current state, though FWIW I think we re just about at the limit of what we can trim. The large majority of users who use Bokeh are not optimizing for Docker image size, so there is only so much we can do to prioritize for that before it starts to impact the common user in bad ways.

**Comment by lmeyerov** [comment]
100MB => 13MB sounds good! RAPIDS users (even if not using bokeh, which is the typical case) are looking at ~1.5GB, so this drops from ~6% => 0.8%, and thus no longer an outlier :)

**Comment by bryevdv** [comment]
Feel free to reach out on the GOIA slack (I work for nvidia)

**Comment by xhochy** [comment]
Small followup: Now `compiler.js` is the biggest artefact in the bundle. It seems like this is neither minified and at the same time an aggregation that contains `compiler/` which is also included in the package. 

- Should `compiler.js` be minified just as other Javascript files?
- Should the `compiler` directory in that folder be excluded from the relase sdist/conda package?

**Comment by bryevdv** [comment]
cc @mattpap for thoughts

**Comment by mattpap** [comment]
> Should compiler.js be minified just as other Javascript files?

If there exists a minifier that can handle this and do it in reasonable time, sure. Just removing leading whitespace shaves off 5 MB from the bundle.

> Should the compiler directory in that folder be excluded from the relase sdist/conda package?

I would consider packaging extensions' related stuff separately, but that's a maintenance burden, so someone would have take the lead and doit.

**Comment by bryevdv** [comment]
> If there exists a minifier that can handle this and do it in reasonable time, sure. J

Could this be minified just at release time? That would make the time less important from the POV or dev cycle iteration.
