### ISSUE TITLE
[BUG] export_svgs() function creats two files (one is empty)

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#10273]
#### software version info (bokeh, python)
Python: 3.6.10
Bokeh: 2.1.1

#### Description of expected behavior and the observed behavior
While generating a svg export in bokeh 2.1.1 an unnecessary empty file is created, too. The second file gets the same name as the first one with a suffix "_1" right before the file extension.
It was expected that only on file is created.

#### Minimal example
```
import numpy as np
import bokeh.plotting as bk_plt
import bokeh.io as bk_io

bk_plt.output_notebook()

N = 500
x = np.linspace(0, 10, N)
y = np.linspace(0, 10, N)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx)*np.cos(yy)

p2 = bk_plt.figure(x_range=(0, 10), y_range=(0, 10))
p2.image(image=[d], x=0, y=0, dw=10, dh=10, palette="Spectral11", alpha = 0.5)
p2.output_backend = 'svg'
bk_io.export_svgs(p2, filename = 'asdf.svg')
```

#### Screenshots
![code_svg_exports](https://user-images.githubusercontent.com/68053396/87018192-346b6300-c1d1-11ea-97bd-2b22786b7fd3.png)
![svg_exports](https://user-images.githubusercontent.com/68053396/87017021-bfe3f480-c1cf-11ea-9f6e-e6ee4fd746f5.png)

**Comment by mattpap** [comment]
Broken in PR #9948. Since we have a canvas per layer, then multiple SVG files are produced, because of this code:

https://github.com/bokeh/bokeh/blob/253bc4e012b3959c5ab3b5d694f3437f340d6e8e/bokeh/io/export.py#L350

Technically a regression, but even adding a SVG icon would break this.

**Comment by mattpap** [comment]
Together with PR #9964, we will be able to generate a single SVG in most cases.
