### ISSUE TITLE
Update blog links on all websites to point to Medium

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh#10282]
Should point to https://medium.com/bokeh 

Starting with:
* [x] https://bokeh.org
* [x] https://demo.bokeh.org
* [x] dash.png image in bokeh-notebooks
* [ ] `sphinx/source/docs/releases/1.3.0.rst`
* [ ] `bokeh/server/views/app_index.html`

**Comment by bryevdv** [comment]
I've updated the main page and the demo site (latter won't show until it is re-deployed, but I will wait until the net release to do that)
