### ISSUE TITLE
Housekeeping: Update python idioms

### ISSUE THREAD

**Issue by Anthchirp** [bokeh/bokeh#10289]
I had a look through some of the source code and noticed (perfectly working) code that is using a bit out of date coding styles that are likely remnants from Python 2.6 and 2.7.

For example things like
* `IOError`/`EnvironmentError` (has been merged into `OSError` in Python 3.3+)
* `class ClassName(object):` style declarations (`object` is redundant since Python 3)
* `io.open` (once used for 2.7/3+ cross-compatibility, now redundant)
* `x = set([... for ... in ...])` which can be shortened to a set comprehension `{... for ... in ...}` (supported since Python 2.7)
* some places that are particularly amenable to f-strings (Python 3.6+)
* `super(ClassName, self).(...)` can be shortened to `super().(...)` with Python 3+

Happy to prepare a PR for this, but would like to check first if there is any interest in doing this.

**Comment by mattpap** [comment]
> `super(ClassName, self).(...)` can be shortened to `super().(...)`

If I recall correctly, there are a few cases, which actually require the more verbose syntax.

**Comment by bryevdv** [comment]
> If I recall correctly, there are a few cases, which actually require the more verbose syntax.

There should not be, I fixed them a few months ago.

**Comment by bryevdv** [comment]
I'm 👍 for this @Anthchirp but suggest it would be good to make separate individual commits in the PR for each of the different updates to make reviewing easier.
