### ISSUE TITLE
Contributing guide needs updating wrt. BEP 6

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10283]
All references to `master` branch should be replaced with `branch-2.2`, or just call it the "default" branch (?).

**Comment by mattpap** [comment]
ref https://github.com/bokeh/bokeh/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request-pr

**Comment by bryevdv** [comment]
I suggest "default base branch" (branch-x.y is a base branch for releases, one one is the current default)
