### ISSUE TITLE
[BUG]Path for Bokeh server application does not exist

### ISSUE THREAD

**Issue by iDataist** [bokeh/bokeh#10294]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

OS: Windows 10

Browser: Chrome

bokeh: 2.1.1       
             
notebook: 6.0.3                    

#### Description of expected behavior and the observed behavior

Expected behavior: `servable` function serves or initializes the dashboard. There are two ways to use the servable function, either in a Jupyter notebook file where the dashboard is displayed within the notebook file itself, or using the terminal command `panel serve --show notebook_name.ipynb` which creates a web application of the dashboard via the default localhost port 5006. 

Observed behavior: The dashboard was rendered in the Jupyter notebook. However, the web application of the dashboard failed to render. 

#### Complete, minimal, self-contained example code that reproduces the issue
Code in Jupyter notebook
```
# Create rows
price_chart_row = pn.Row(price_chart)
portfolio_evaluation_row = pn.Row(portfolio_evaluation_table)
trade_evaluation_row = pn.Row(trade_evaluation_table)

# Create columns
portfolio_column = pn.Column(
    '# Portfolio Evaluation Metrics', 
    price_chart_row, 
    portfolio_evaluation_row)
trade_column = pn.Column('# Trade Evaluation Metrics', 
                         trade_evaluation_row)

# Create tabs
trading_dashboard = pn.Tabs(
    ("Portfolio Metrics", portfolio_column),
    ("Trade Metrics", trade_column)
)
trading_dashboard.servable()
```
Code in Terminal
```
panel serve --show trading_dashboard.ipynb
```

#### Stack traceback and/or browser JavaScript console output
```
ERROR: Path for Bokeh server application does not exist: C:\Users\hwdgr\Dropbox\FinTech\15-Algorithmic-Trading\1\Activities
\trading_dashboard.ipynb

```
#### Screenshots or screencasts of the bug in action
Screenshot of Jupyter notebook
![image](https://user-images.githubusercontent.com/46846986/87234316-4f86d000-c395-11ea-8728-928269764fdd.png)

Screenshot of terminal
![image](https://user-images.githubusercontent.com/46846986/87234301-33832e80-c395-11ea-9c20-93a6e04bda23.png)

**Comment by bryevdv** [comment]
@iDataist `servable` is not part of the Bokeh API. This is some issue with Panel, you will need to submit an issue on their tracker:

https://github.com/holoviz/panel/issues
