### ISSUE TITLE
[BUG] Slider values increment by 2x steps

### ISSUE THREAD

**Issue by ac-ML** [bokeh/bokeh#10302]
The Slider values appear to increment by a factor of 2. I tested the rendering with Bokeh 2.1.1. on Chrome and Firefox.  Here's a sample:

```python
from bokeh.models import Slider
from bokeh import io
slider = Slider(start=0, end=9, value=0, step=1, title="foo")
io.show(slider)
```

Moving the slider will display 2x increments of 'step'. The example in https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#slider appears to show the same issue.

**Comment by bryevdv** [comment]
Noting: moving the slider *with the keyboard*

**Comment by bryevdv** [comment]
@ac-ML to clarify, you mean: moving the slider with the keyboard arrows? I cannot reproduce any issue with mouse movements.

**Comment by ac-ML** [comment]
@bryevdv Yes. The 2x increment happens when using the keyboard arrows.
