### ISSUE TITLE
[FEATURE] Trigger DoubleTap event when a glyph is hit

### ISSUE THREAD

**Issue by sayantan11995** [bokeh/bokeh#10309]
In my scenario I have a network plot with nodes and edges. I want to trigger the `DoubleTap`  event only after double-tapping on any node(a glyph).
By using `js_on_event` callback I am able create a `DoubleTap` event in my network plot. It seems like  the `DoubleTap` event currently provide the location of the event, but does not do any hit testing on glyphs like `TapTool`.

It would be really helpful if this support gets added.

**Comment by bryevdv** [comment]
I don't think it would be advised to add hit-testing to the bare `DoubleTap` event, but what I was proposing was to make the current tap tool be more configurable (e.g. to do its normal hit-testing on a double tap instead of the currently hard-coded single tap only)

**Comment by mattpap** [comment]
This was proposed in issue #7845 and there was a failed PR #7846 attempting to implement it. I will resurrect that PR and see if this is more feasible to achieve now.

**Comment by bryevdv** [comment]
I missed the old issue, I will go ahead and close this as a dupe then and milestone the old one.
