### ISSUE TITLE
[BUG] Cannot deselect with TapTool

### ISSUE THREAD

**Issue by 23pointsNorth** [bokeh/bokeh#10317]
When using the TapTool as shown here: https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#taptool, one can click on a point to select, shift+click to add extra, but clicking again on an already selected point doesn't deselect the point.

**Comment by bryevdv** [comment]
cc @mattpap I recall you added the context menu for box selection compositing. Do you have any thoughts about this? Currently `shift-tap` appends to the current selection but it would be simple enough to make it also see if the new point(s) are already selected, and in that case, unselect them. Perhaps this should be configurable. I'm not sure if a context menu on the toolbar is merited just for this. 

Additionally, it would be nice to offer an unselect mechanism that works on mobile, but I am not sure what the best option there is. Perhaps tap to initial select and press corresponds to shift-top above?

**Comment by mattpap** [comment]
Tap tool works pretty much the same as other selection tools, so one can deselect in subtract mode (ctr+shift+click) or clear the selection completely by using clear selection option from tap tool's context menu (press on tap tool's button and choose the last option (`x`)). The later works on mobile devices (for that reason it's a press to show gesture instead of hover).

**Comment by bryevdv** [comment]
@mattpap It's good that is that way for consistency with other tools, but it's also pretty clunky be the only UX for this case. Being able tap something to select then it tap again to unselect is a very common UX interaction, and I think we should offer that in order to be familiar with common expectations.

**Comment by 23pointsNorth** [comment]
@mattpap I wasn't aware of 
> subtract mode (ctr+shift+click)`. 

Even googling it doesn't show up relevant docs (and definitely not the key combination). 
I would prefer @bryevdv suggestion, as the behaviour is fairly expected. And as a minimum can make a PR to add a description to the (example) documentation.

**Comment by mattpap** [comment]
> > subtract mode (ctr+shift+click)`.

> Even googling it doesn't show up relevant docs (and definitely not the key combination).

This is a recent addition, so documentation is lagging behind.

**Comment by mattpap** [comment]
> Being able tap something to select then it tap again to unselect is a very common UX interaction (...)

It depends. Some systems do this, some use double click and some deselect by not hitting anything (we do this btw.). My point is that whatever we do, we have to consider all relevant tools (in this case all selection tools) and their behavior on specific platforms (mobile vs. desktop). Discoverability is an orthogonal concept, that's at least partially covered by issue #8512.

**Comment by stevendbrown** [comment]
On Windows, deselecting with Crtl-Shift-Click works as expected but on macOS it seems to be caught and handled without passing the modified event to the browser. Does the end-user browser have to be differently configured on macOS to allow this functionality? I can certainly work around by press-and-hold on the tool itself to switch to subtract mode (which is just excellent, thanks for that @mattpap).

**Comment by mattpap** [comment]
> (...) but on macOS it seems to be caught and handled without passing the modified event to the browser.

It may be command key (or something like that) on mac os instead of ctrl. Otherwise, which browser you are speaking about?

**Comment by stevendbrown** [comment]
> > (...) but on macOS it seems to be caught and handled without passing the modified event to the browser.
> 
> It may be command key (or something like that) on mac os instead of ctrl. Otherwise, which browser you are speaking about?

I've tested Chrome 84.0.4147.105 and Safari 13.1.2 on macOS 10.15.6. Neither of either of the other modifier keys seem to elicit the desired behaviour (option or command).

**Comment by ofir-frd** [comment]
Hey @bryevdv , @mattpap ,

I was wondering if there have been any updates on this issue. I've been following along and finding a solution would be helpful for me as well.

Thanks
