### ISSUE TITLE
Improving examples usefulness with indexing and comments

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1032]
We have a lot of great examples, but sometimes it's hard to know what each of them is trying to exemplify, show or demonstrate, just by the folder directory they're in. I think it would be easier to search for a similar example if we had a comment at the beginning of each one, saying what is the purpose of its existence, references to concrete examples in the documentation and/or an example index in the  documentation-gallery.

I find the gallery section in matplotlib, http://matplotlib.org/gallery.html, and how they group them into categories, very useful when I'm running into problems and I want to find a similar working example.

Getting this done, might decrease the amount of user questions with answer: see example `foo.py`, help people in the team answer more efficiently these simple questions when they do occur and help us keep track of what examples we do have, avoid duplicates and spot not exemplified features.

**Comment by mattpap** [comment]
There's a related issue #1350.

**Comment by bryevdv** [comment]
with just-merged #5407 ReST in docstrings for examples will now be rendered above the plot on the dedicated page for the plot. So commentary and indexing directives can be added to any example easily.

**Comment by bryevdv** [comment]
This issue is old and somewhat underspecified, I am going to make more detailed tasks for current docs tasks in new issues.
