### ISSUE TITLE
Change NumberArray to Float32Array?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10329]
AFAICT WebGL does not support Float64 buffers. E.g. they are explicitly caught and excepted in three.js, trying to use them with ReGL generates bogus output (seems like the raw data is just being interpreted as Float32). And in Bokeh, the existing code definitely copies everything into `Float32Array` before  sending to buffers:
```
  74 :        this.vbo_s.set_data(0, new Float32Array(map(this.glyph.sradius, (s) => s*2)))
  172 :       this.vbo_x.set_data(0, new Float32Array(xx))
  173 :       this.vbo_y.set_data(0, new Float32Array(yy))
  176 :       this.vbo_a.set_data(0, new Float32Array(this.glyph._angle))
  181 :       this.vbo_s.set_data(0, new Float32Array(map(this.glyph.sradius, (s) => s*2)))
  183 :       this.vbo_s.set_data(0, new Float32Array(this.glyph._size))
```

Which I assume happens for a reason. All this copying seems pretty wasteful, but mostly has me wondering why we are using `Float64Array` as a default everywhere to begin with. It's been that way forever but I don't have any recollection of an actual discussion or decision. 

Would it make sense to change `NumberArray` to be `Float32Array` (and also to update a few explicit `Float64Array` instances left in the code base to be `NumberArray`)? It seems this would allow less copying in the webgl support eventually, but also reduce Bokeh's memory footprint in general. 

Alternatively, are there any *specific* situtations where 16 vs 7 sig digits is required? If so can we isolate those and change to `Float32Array` everywhere else?

Thoughts @philippjfr @mattpap @bokeh/dev ?

**Comment by mattpap** [comment]
This has been my goal when introducing `NumberArray` type. However, currently some code paths (e.g. `_radius` -> `sradius` in `Circle` glyph when radius units are `screen), so there will be changes necessary to achieve this.
