### ISSUE TITLE
[FEATURE] cmap for VArea glyph

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#10328]
**Idea**
I was looking for a function to draw a virtual area with a color map, like the one show in the figure below.
![goal](https://user-images.githubusercontent.com/68053396/88184257-c42dfa00-cc32-11ea-8d7a-1352c78c4bca.PNG)

This is the code how I created the figure.
```
import numpy as np
from bokeh.io import  show, output_notebook
from bokeh.plotting import figure
from bokeh.palettes import brewer

output_notebook()

N = 500
x = np.linspace(-2, 3, N)
y = np.linspace(0, 10, N)

y1 = np.zeros(N)
y2 = 10-x**2

d = np.zeros([N, N])
for j, _y in enumerate(y):
    for i, _x in enumerate(x):
        d[j][i] = _y if _y < 10 - _x**2 else -1
        
plot = figure(title=None,
              plot_width=300, 
              plot_height=300,
              min_border=0,
              toolbar_location=None
             )

palette = brewer["OrRd"][9]+('#ffffff',)

plot.image(image=[d], x=-2, y=0, dw=5, dh=10, palette=palette[::-1], level="image")
plot.line(x, y2)

show(plot)
```
**Wanted solution**
I was somehow hoping to get the same result while using the VArea glyph like the example in the example gallery, because my solution is ugly for a small number of ```N```. Furthermore it is not as smoth as the VArea if I zoom into the picture.
![latest](https://user-images.githubusercontent.com/68053396/88185841-b4afb080-cc34-11ea-8ff9-c3e53542dd91.PNG)
```
import numpy as np

from bokeh.io import show
from bokeh.models import VArea, ColumnDataSource

N = 500
x = np.linspace(-2, 3, N)
y = np.linspace(0, 10, N)

y1 = np.zeros(N)
y2 = 10-x**2

source = ColumnDataSource(dict(x=x, y1=y1, y2=y2))

plot = figure(title=None,
              plot_width=300, 
              plot_height=300,
              min_border=0, 
              toolbar_location=None
             )

glyph = VArea(x="x", y1="y1", y2="y2", hatch_color="#f46d43", fill_alpha=0.2)
plot.add_glyph(source, glyph)
plot.line(x, y2)

show(plot)
```

**Additional comment**
This is not an urgent topic to me. I am just interested if this could be possible in the future and if someone else is interested in this functionality, too.

**Comment by bryevdv** [comment]
I think this is probably possible now, by constructing the areas you want to colormap and then either drawing them with `varea_stack` or `patches`. There's just not a single function for it, and speaking plainly, I doubt we would consider adding one for something so specific, so I will close this. Happy to discuss possible ways to implement using current APIs on the Discourse support forum:

https://discourse.bokeh.org/

**Comment by mosc9575** [comment]
Thank you for your hint. Somehow I missd the ```varea_stack()``` function. Using this, my example looks much better. Now it looks like I wanted it to.

![solution](https://user-images.githubusercontent.com/68053396/88276700-cac67b00-ccdf-11ea-9b7a-bb9be74689ac.PNG)

May this is useful: My minimal example:
```
import numpy as np
from bokeh.io import show, output_notebook
from bokeh.palettes import brewer
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

output_notebook()

# data
N = 500
x = np.linspace(-2, 3, N)
y = np.linspace(0, 10, N)

y1 = np.zeros(N)
y2 = 10-x**2

# colors
palette = brewer["OrRd"][9]+('#ffffff',)
palette = palette[::-1]

# sort data into one range
l = len(palette)
mat = np.zeros([N, l])
ranges = np.linspace(0, np.ceil(y2.max()), l)

for i, _y in enumerate(y2):
    for j, _range in enumerate(ranges):
        if _range <= _y:
            diff =  _y - _range 
            if diff < ranges[1]:
                mat[i][j] = diff
            else:
                mat[i][j] = ranges[1]
        else:
            mat[i][j] = 0
mat = mat.T#.clip(min=0)

# create dictionary
stack = []
d = {'x': x, 'y0':y1}
for i in range(l):
    item = str(i)
    stack.append(item)
    d.update({item: mat[i][:]})
    
source = ColumnDataSource(d)

plot = figure(title=None,
              plot_width=300, 
              plot_height=300,
              min_border=0, 
              toolbar_location=None
             )

plot.varea_stack(stack, x='x', color=palette, source=source)
plot.line(x, y2)

show(plot)
```
