### ISSUE TITLE
bokeh build includes copyright statement from Anaconda in my bokeh extension

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#10333]
Bokeh: 2.1.1

I'm developing the `awesome-panel-extensions` package which is also a Bokeh Extension. A step in the build process is to run `bokeh build`.

I can see that the files generated in the `dist` folder contains the below copyright notice. I think this is a bug. I would expect no copyright notice to be inserted (except if I configured it to) or a custom one relevant for my extension.

```bash
*!
 * Copyright (c) 2012 - 2020, Anaconda, Inc., and Bokeh Contributors
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * 
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 * 
 * Neither the name of Anaconda nor the names of any contributors
 * may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
*/
```

**Comment by mattpap** [comment]
Extension bundles contain parts of bokehjs' code base (prelude, etc.) and those are a subject to (very liberal per BSD-3) licensing requirements. For that matter, bokehjs' bundles themselves contain quite a few third-party licenses. However, having bokeh's license as the most prominent part of an extension bundle is definitively misleading. Thus it should be possible to provide an author's license as the first statement of a bundle. This can be derived from a well defined `package.json`, as licensing information is a requirement for publishing.

**Comment by MarcSkovMadsen** [comment]
Hi @mattpap 

Thanks.

Is the message that i can configure it In package.json? Or is something that should be changed by Bokeh?

**Comment by mattpap** [comment]
Both, assuming you didn't configure `package.json` fully at your end (at least `license` field). In `bokeh build` we will have expose relevant fields and/or give an option for including a license file (via a `bokeh.ext.json` config, which finally would be useful for something).
