### ISSUE TITLE
[FEATURE] Consistent use of underscores

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#10332]
Haven't been plotting in a while, and coming back to bokeh after a break I wrote the following

```
    p.x_range.end = 1
    p.y_range.end = 20
    p.yaxis.axis_label = 'density'
    p.xaxis.axis_label = 'Proportion of visits that the same script loads.'
```

One of the things I've always like about bokeh is that it's pretty easy to guess what to put in, or the fuzzy property matching gives the answer.

The inconsistency between `x_range` and `xaxis` is bothering me. 

I don't think it's worth making a breaking api change over, but can we add aliases in one direction so that, for example, I could use `x_axis` and `x_range`.

If people think this is a good idea we could inventory if it happens elsewhere.

**Comment by mattpap** [comment]
> The inconsistency between `x_range` and `xaxis` is bothering me.

Yeah, it should be `x_axis`. I'm guessing `xaxis` is a side effect  Matlab/pylab-like naming conventions.

**Comment by bryevdv** [comment]
I would advocate for `noaction` on this (or `wontfix`).  Quoting my response on the PR:

> Given all the code completion and intellisense tools available I would actually not doing anything at all. If this deprecation were ever actually carried out, it would break a enormous amount of code, pointlessly. We did a good job for awhile but are already starting to catch flak about breaking changes again. There is no upside to ever actually removing either xaxis or x_range. Given that, all this does is add a confusing semi-permanent alias that will cause problems when advice on support forums starts to diverge. .

**Comment by mattpap** [comment]
> We did a good job for awhile but are already starting to catch flak about breaking changes again.

Any data to support this claim (the same goes with other statements)? I'm genuinely interested in how much flak we actually get as a percentage of all bokeh's usage. This may be tricky to analyze due to inherent bias of commenters, because, in my opinion, an upset user is more likely to comment than a just inconvenienced one (in this case by having an inconsistent API). If Python's intellisense is so good and prevalent (I think neither is true), then upgrading to new APIs should be as simple as using one's favourite refactoring tool (perhaps shipped with one's favourite editor/IDE).

**Comment by birdsarah** [comment]
I was going to leave this alone as I've learned in the past that I'm not good at convincing @bryevdv and it is definitely a small thing.

But, I was just making a log plot, and couldn't figure it out and had to look up the API to write:

```
p = figure(x_axis_type='log')
p.xaxis.axis_label = 'a log scale'
```

(Random aside, the fuzzy matching property suggestion never suggests `x_axis_type`.)

I don't disagree that there's some maintenance burden here. Any code is a maintenance burden. But looking at @mattpap's PR. It is only x/ygrid and x/yaxis that are subject to this inconsistency. Because we didn't catch it till now, doesn't mean it isn't an inconsistency that's worth fixing.

**Comment by birdsarah** [comment]
> Given all the code completion and intellisense tools available I would actually not doing anything at all.

On this point specifically. I do all my plotting in notebooks. I think that's a very common usage mode. Code completion e.g. `p.x` + tab will give you the options. 

![Screenshot from 2020-07-31 22-58-13](https://user-images.githubusercontent.com/1796208/89093573-59db2f00-d381-11ea-83b8-18827f69f196.png)

Before you mentioned this I hadn't been trying to code complete my plotting code in the notebook. I'm not sure why. It's not a habit I have. I'm happy to be debated on what's normal here.

Again, now I've seen it, I'm not sure it's intuitive / easy / convenient to have `axis` and `grid` alphabetically out of order.
