### ISSUE TITLE
examples' tests fail because headless browser doesn't start in time

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10339]
See e.g. https://github.com/bokeh/bokeh/pull/10337#issuecomment-663926513, but that's a common recurrence. This issue was solved in bokehjs' visual tests, so the solution can be simply copied to examples' tests.

**Comment by tcmetzger** [comment]
I just had a similar, possibly related (?) error in pull request #10349. All tests ran fine, except for [one webdriver test (windows-latest, 3.6)](https://github.com/bokeh/bokeh/runs/920076202?check_suite_focus=true), raising `selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages`.

**Comment by mattpap** [comment]
This is a different issue. Selenium/webdrivers are inherently unreliable, resulting in a variety of failures. examples' tests don't use selenium, but interact with chromium over chrome devtools protocol (CDP).
