### ISSUE TITLE
Documentation and examples updates for 2.2 release

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10344]
- [x] `DocumentReady` event (PR #10266) needs documentation and examples
- [x] Dev guide updates to describe new requirements in https://github.com/bokeh/bokeh/pull/10338
- [x] Better documentation for `Dropdown`
- [x] user guide webgl example needs to use circle, not scatter
- [x] release notes

**Comment by bryevdv** [comment]
I added the bare documentation for `DocumentReady` we will need to add a cleaned up example later (cc @philippjfr) I would propose under `examples/howto/doc_ready.py`
