### ISSUE TITLE
Examples/Compat missing

### ISSUE THREAD

**Issue by lpilz** [bokeh/bokeh#10356]
I can't seem to find the code example for seaborn compatibility as hinted at in: https://docs.bokeh.org/en/0.10.0/docs/user_guide/compat.html

The whole examples/compat directory seems to be missing...

**Comment by bryevdv** [comment]
The docs you link are to version 0.10, which is from half a decade ago. All MPL compatible support was deprecated in version 0.12.5 (nearly four years ago) and then later removed:


https://docs.bokeh.org/en/latest/docs/releases.html#release-0-12-5

The current version is 2.1.1 and the you can always find the current latest docs at `/en/latest`:


https://docs.bokeh.org/en/latest/
