### ISSUE TITLE
[BUG] slickgrid import has syntax error

### ISSUE THREAD

**Issue by ColCh** [bokeh/bokeh#10358]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### Complete, minimal, self-contained example code that reproduces the issue

```
no code :)
```

#### Stack traceback and/or browser JavaScript console output

```
SyntaxError: /foo/node_modules/@bokeh/bokehjs/node_modules/@bokeh/slickgrid/slick.core.js: Unexpected token, expected "," (661:6)

  659 |       UP: 38,
  660 |       A: 65
> 661 |       C: 67,
      |       ^
  662 |       V: 86
  663 |     },
  664 |     "preClickClassName" : "slick-edit-preclick",
```

#### Screenshots or screencasts of the bug in action

my resolved slickgrid version is `2.4.27`

and here comes file for it: https://unpkg.com/browse/@bokeh/slickgrid@2.4.27/slick.core.js

![image](https://user-images.githubusercontent.com/599439/89072863-0cab8d00-d382-11ea-9cb4-06ff7e10ea04.png)

In next version, https://unpkg.com/browse/@bokeh/slickgrid@2.4.27-1/slick.core.js - it got fixed

BUT! It can't be resolved to that package.

![image](https://user-images.githubusercontent.com/599439/89073047-64e28f00-d382-11ea-8cb7-4030be15c1e4.png)

https://semver.npmjs.com/

Pls fix. Just publish it `2.4.27-1` as `2.4.28` or something

**Comment by mattpap** [comment]
> Just publish it 2.4.27-1 as 2.4.28 or something

2.4.28 is not an option, because the version should consist of slick grid's version and build number. Apparently the correct syntax is to use `+` (build number) instead of `-` (pre-release) (ref https://semver.org/).

**Comment by mattpap** [comment]
Unfortunately npm doesn't support `+` syntax, treating `2.4.27+1` and `2.4.27` as the same version number.

**Comment by ColCh** [comment]
> > Just publish it 2.4.27-1 as 2.4.28 or something
> 
> 2.4.28 is not an option, because the version should consist of slick grid's version and build number. Apparently the correct syntax is to use `+` (build number) instead of `-` (pre-release) (ref [semver.org](https://semver.org/)).

this is strange to me :) you are using fork, and forks may follow other versioning, which differs from upstream

But, may be, I'm just not in context. Thank you for reviewing this issue 👍

**Comment by bryevdv** [comment]
@mattpap what about `2.4.27.1` ?

**Comment by mattpap** [comment]
> couldn't we publish 2.4.27+1

I was wrong about `+` syntax in semver. It should be ignored and npm follows this, thus 2.4.27 and 2.4.27+1 are the same version.

> unpublish 2.4.27

If anything, we can only deprecate. Can't unpublish any version of a package that something depends on.

**Comment by mattpap** [comment]
I guess we will have to abandon matching version number with slickgrid and proceed with 2.4.28.

**Comment by mattpap** [comment]
One more option is to use `major.minor.{patch}{build|2}` scheme (build is 2 decimal digits), e.g. the current version would be `2.4.2701`. This checks all the boxes, because it preserves the order, keeps complete and intact slickgrid's version and allows incremental build updates.
