### ISSUE TITLE
[BUG] Jupyterlab won't generate plots

### ISSUE THREAD

**Issue by GiovanniGatti** [bokeh/bokeh#10386]
I've been using Bokeh for awhile in a distant server. I am trying to get it installed in my local machine.

I've just followed the installation steps from [quickstart](https://docs.bokeh.org/en/latest/docs/user_guide/quickstart.html#installation) and then [Using with Jupyter](https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html#jupyterlab), but plotting generation is not working.

In practice, I'm not able to plot even simplest charts charts like
![image](https://user-images.githubusercontent.com/1745450/89866966-ba077780-dbb0-11ea-87d9-7c375ca758a4.png)

Downloading them gives weird images:
![image](https://user-images.githubusercontent.com/1745450/89867062-defbea80-dbb0-11ea-80e1-1f655c5ce503.png)

## Technical details

**OS version**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Browser**: Google Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**Virtualenv**
```
$ pip freeze
```
[requirements.txt](https://github.com/bokeh/bokeh/files/5055266/requirements.txt)

**Browser's JavaScript console output**

```
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
VM139:200 Bokeh: BokehJS not loaded, scheduling load and callback at Tue Aug 11 2020 09:02:37 GMT+0200 (Central European Summer Time)
VM139:240 Bokeh: injecting script tag for BokehJS library:  https://cdn.bokeh.org/bokeh/release/bokeh-2.1.1.min.js
VM139:240 Bokeh: injecting script tag for BokehJS library:  https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.1.1.min.js
VM139:240 Bokeh: injecting script tag for BokehJS library:  https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.1.1.min.js
VM139:240 Bokeh: injecting script tag for BokehJS library:  https://cdn.bokeh.org/bokeh/release/bokeh-gl-2.1.1.min.js
VM51 bokeh-2.1.1.min.js:162 [bokeh] document idle at 40 ms
VM139:206 Bokeh: all BokehJS libraries/stylesheets loaded
VM139:292 Bokeh: BokehJS plotting callback run at Tue Aug 11 2020 09:02:38 GMT+0200 (Central European Summer Time)
VM51 bokeh-2.1.1.min.js:240 [bokeh] setting log level to: 'info'
VM139:184 Bokeh: all callbacks have finished
VM51 bokeh-2.1.1.min.js:421 [Violation] 'setInterval' handler took 207ms
[Violation] Forced reflow while executing JavaScript took 207ms
```

I don't see any obvious error and everything went fine during the installation process. I'm a little bit out of ideas on what to investigate since no error comes up.

Curiously, in the Browser's console I see 'BokehJS not loaded' while in the Jupyterlab interface I have 'BokehJS 2.1.1 successfully loaded'.

**Comment by GiovanniGatti** [comment]
I got it to work after disabling '3D Acceleration' in VirtualBox.

![image](https://user-images.githubusercontent.com/1745450/89870049-93980b00-dbb5-11ea-8c75-8c3172a66796.png)

It seems then a lower level issue.

**Comment by mattpap** [comment]
3d acceleration should have no bearing on bokehjs' behavior when using the default (`canvas`) backend. Can you try the same example with and without 3d acceleration using `webgl` backend:
```py
figure(output_backend="webgl")
```
I'm curious how I will behave. Did you observe any issues with other JS libraries utilizing HTML5 canvas?

**Comment by bryevdv** [comment]
Chrome and possibly other browsers have options to enable/disable "hardware acceleration" for 2d HTML canvas, which probably uses APIs that are included under the name "3d acceleration". So another option is to check browser settings
