### ISSUE TITLE
Test legacy bundles before release

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10391]
We will be able to test only in chromium headless, but that will cover quite a few bases. We will have to test manually in IE.

**Comment by bryevdv** [comment]
@mattpap since 2.4 will be the last release level to support legacy bundles I don't think investing in CI is worthwhile. Just leaving this as a reminder to manually test for 2.4, up to all the release candidates.

**Comment by tcmetzger** [comment]
@mattpap @bryevdv 
I tried to test things on Internet Explorer (21H1) on my win10 machine (caveat: I never use IE, so it is possible that some configuration is broken on my local system). 

I installed Bokeh into a brand new conda environment with `pip install --pre bokeh==2.4.0dev7`. I then ran some examples with `BOKEH_LEGACY=true`. They worked fine on Firefox (91.0.2), Chrome (92.0.4515.159) and Edge (93.0.961.38) - but not on Internet Explorer! Looking at the source code, the HTML files correctly point to the legacy version of BokehJS on the CDN (`src="https://cdn.bokeh.org/bokeh/dev/bokeh-2.4.0dev7.legacy.min.js"`), but the IE window just stays empty where the plots should be.

For example, this is what anscombe.py looks like (the div widgets get rendered, but not the grid layout):
![image](https://user-images.githubusercontent.com/39711796/132289003-9b723751-80a6-45c5-82cf-1fed6d25e6da.png)

This is the console output: 
![image](https://user-images.githubusercontent.com/39711796/132289019-e5afc948-02ca-4c28-b7ac-e9141a7c9033.png)

As a more simple example, I tried https://github.com/bokeh/bokeh/blob/branch-2.4/sphinx/source/docs/user_guide/examples/plotting_scatter_circle.py. Again, this works on all browsers except for IE. The correct BokehJS is in the source code (src="https://cdn.bokeh.org/bokeh/dev/bokeh-2.4.0dev7.legacy.min.js"), but the IE window stays completely white. 
BokehJS gets loaded from the CDN:
![image](https://user-images.githubusercontent.com/39711796/132289188-cf4f35b9-e83f-41e0-86cd-5036c36c8be9.png)
But this time, there are not even any errors in the Console:
![image](https://user-images.githubusercontent.com/39711796/132289059-dba5bd8d-d6bc-4f54-9e32-7ec2c98f03aa.png)
Even setting `$Env:BOKEH_LOG_LEVEL ="debug"` doesn't really provide any helpful info:
![image](https://user-images.githubusercontent.com/39711796/132289476-0ac48793-44db-4cee-b730-75f53a101ce4.png)

**Comment by tcmetzger** [comment]
Unfortunately, I experienced the same behavior again with 2.4.0rc1 (`BOKEH_LEGACY` set to `True`).  Everything works as expected in Firefox, etc, but in Internet Explorer (21H1), I only see a white, empty screen. I can see in the source code that https://cdn.bokeh.org/bokeh/dev/bokeh-2.4.0rc1.legacy.min.js is used as BokehJS. There are no errors in the IE console. This is the code I used:
```
from bokeh.plotting import figure, show
p = figure()
p.line([1, 2, 3], [6, 7, 2])
show(p)
```
CC @mattpap @bryevdv

**Comment by bryevdv** [comment]
FWIW at least some places estimate IE browser share at < 1% 

https://gs.statcounter.com/browser-market-share

If it's too much effort, just my $0.2 but I am not personally opposed to just dropping support in this release.

**Comment by mattpap** [comment]
That's just a regex issue, can be fixed in no time.

**Comment by bryevdv** [comment]
I'll cut an rc2 as soon as there is a PR for this merged then, I don't think any other issues are remaining / have been found

**Comment by bryevdv** [comment]
I will go ahead and cut rc2 so the doc site can get a thorough review.
