### ISSUE TITLE
Color site for OpenURL no longer exists

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10397]
ref: https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html#openurl

The `http://www.colors.commutercreative.com` site used for the `OpenURL` callback in the example above seems to no longer exist. 

Could probably use e.g. `http://www.html-color-names.com/firebrick.php` instead.

**Comment by morrme** [comment]
Indeed it doesn't look like the currently referenced page exists at all on the original site anymore. 

May I help with this change?

**Comment by bryevdv** [comment]
@morrme certainly, a PR to update would be very welcome
