### ISSUE TITLE
Bokeh server can display an empty document without any visible errors

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#1039]
While trying to debug https://github.com/ContinuumIO/bokeh/issues/1017, I keep running into a state where there is no JS error in the console or any warning or error from the script or bokeh-server. This is on 0.5.2.

Test script in [this gist](https://gist.github.com/kdodia/ffb89e1492a7a06fc894).

![bokeh_plot_server_](https://cloud.githubusercontent.com/assets/4944634/4001006/75df913c-295f-11e4-9d44-497eb2aaf2c0.png)

Suggestions welcome.

**Comment by birdsarah** [comment]
As of 0.9.1 if you try to plot something that won't render you should get a validation warning like: 

````python
E-1004 (REQUIRED_RANGE): A required Range objects missing: x_range, y_range [Plot, ViewModel:Plot, ref _id: d979d8b4-94de-4af9-a546-1c8b2b40ed8d]
````

Can we close?

**Comment by bryevdv** [comment]
I suppose. I'm not certain there aren't other error conditions that might result in empty pages that we haven't added validations for, but we could address those as they come up in other issues.
