### ISSUE TITLE
marker_compare.py does not exercise webgl

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10413]
In its current form it uses `scatter` which does not (cannot) use webgl (since webgl is about repeating a single type of thing many times, and scatter can be parameterized by marker type). 

It should be updated to use actual glyph methods.

**Comment by mattpap** [comment]
`scatter()` could use glyph methods on its own as an optimization if `marker_type` is a constant.

**Comment by mattpap** [comment]
Based on my prior experience with testing webgl backend, I'm also considering to add an option or "forced" backend type enums, so that if webgl can't be used for whatever reason, bokehjs would fail hard immediately, making sure that we show or test what we expect to.
