### ISSUE TITLE
[FEATURE] Document Python exceptions handling

### ISSUE THREAD

**Issue by vinokurov** [bokeh/bokeh#10418]
When an exception happens during a python callback execution, the callback is terminated and no changes are applied to the model. The user who doesn't have access to the stdout cannot see the exception and may get confused whether the response is slow or something went wrong.
It would be great if it was possible to handle exceptions that are happening on a document level, e.g. to display a popup message to the user.

I am suggesting to introduce a Document exception_callback. Something like this:
```python
document = curdoc()

error_div = Div(text="", visible=False)
document.add_root(error_div)

def exception_handler(error, traceback):
    error_div.text = str(error)
    error_div.visible = True

document.on_exception(exception_handler)
```

In my project (using Bokeh v.2.1.1) I have achieved this by monkey patching `@_needs_document_lock` decorator. I have added an `except` section in the `try` block:
```python
                try:
                    result = func(self, *args, **kwargs)
                    if inspect.isawaitable(result):
                        # Note that this must not be outside of the critical section.
                        # Otherwise, the async callback will be ran without document locking.
                        result = await result

                # THIS EXCEPT SECTION IS ADDED
                # IT ALLOWS TO HANDLE EXCEPTIONS BY CALLING A PRE_REGISTERED document.exception_callback()
                except Exception:
                    if hasattr(self._document, "exception_callback"):
                        self._document.add_next_tick_callback(exception_callback)
                    raise

                finally:
                    ...
```

**Comment by vinokurov** [comment]
opened 2 issues by mistake

**Comment by bryevdv** [comment]
dupe of #10419

**Comment by sandeep59** [comment]
Hi 
I have recently started using Bokeh, Is this issue resolved? Can we do error handling in Bokeh server app?
Please post an example how can we do it on call backs and show the error in layout.
