### ISSUE TITLE
INLINE_LEGACY does not work (CDN.legacy = True does work)

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10426]
cc @mattpap Just noting that in my testing on Win10 I was unable to get anything to work in IE with INLINE_LEGACY. I *was* able to see things work [1] by using CDN and explicitly setting `CDN.legacy = True`.

I don't intend to hold up the 2.2 release over this since the usage with CDN functions. 

[1] Vertical sliders are evidently broken in IE

**Comment by mattpap** [comment]
> Vertical sliders are evidently broken in IE

It looks like they are completely broken (#10444).
