### ISSUE TITLE
[BUG] Toggle on_click is fired when "active" is changed from Python side

### ISSUE THREAD

**Issue by quentinmit** [bokeh/bokeh#10424]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.1.1

#### Description of expected behavior and the observed behavior
`on_click` should, as its name implies, only fire when the user actually clicks on the `Toggle`. Instead, because it's actually implemented as `on_change('active', …)`, it also fires when the 'active' value is changed programmatically. This means that it's not possible to keep a `Toggle` synchronized with external Python state (when you click, it toggles the external state, but meanwhile the external state resets the toggle which causes it to toggle the external state again).

Ideally, it would be possible to attach a `click` event handler that truly just fires on click, and doesn't even change `active` at all.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.models import Toggle
from bokeh.io import curdoc

doc = curdoc()

value = False

t = Toggle()
def on_click(new):
    print("on_click(%s)" % new)
    def set():
        global value
        value = new
    doc.add_timeout_callback(set, 500)
t.on_click(on_click)
doc.add_root(t)

async def worker():
    t.active = value
doc.add_periodic_callback(worker, 100)
```

#### Stack traceback and/or browser JavaScript console output

The log will show:
```
on_click(True)
on_click(False)
on_click(True)
on_click(False)
...
```

The expected behavior from this code would be to see the toggle flip 500ms after the click (or, flash briefly, then flip for good after 500ms, if on_click still has the side effect of toggling active directly).

**Comment by quentinmit** [comment]
FWIW in the meantime I just used a custom model that subclasses Button (so inherits Button's `on_click`) and has an `active` property so the callback can toggle its status.

**Comment by xaptronic** [comment]
@quentinmit did your solution to this include any custom JS? I ran into the same problem and resolved it by creating a new python model with what is basically a copy of the Toggle javascript, but including triggering a ButtonClick event
