### ISSUE TITLE
Activate wheel zoom by default with BokehJS

### ISSUE THREAD

**Issue by PBrockmann** [bokeh/bokeh#10439]
With BokehJS, I would like to have the wheel zoom for scrolling activated by default.
It is not the case by default. 

An option like: 
`active_scroll = "wheel_zoom" `
is not implemented.

But changing the line 30073 of bokeh.js file from
`return et == 'tap' || et == 'pan';`
to
`return et == 'tap' || et == 'pan' || et == 'scroll';`
activates the wheel zoom.

Am I breaking something doing this ? if not could it be added in next release.

Simple code to test this is availaible from https://jsfiddle.net/PBrockmann/ct6okdya/

**Comment by bryevdv** [comment]
cc @mattpap IIRC there are several places where "plumbing" is not fully hooked up in the BokehJS API
