### ISSUE TITLE
[BUG] pull_session not working in Win10 without this import statement: 'from bokeh.server.server import Server'

### ISSUE THREAD

**Issue by gopimandala** [bokeh/bokeh#10431]
OS Windows10
Bokeh server version 2.1.1 (running on Tornado 6.0.4)
Flask version 1.1.2
Python version 3.8.3

The bokeh plots run fine on their own (i.e. via bokeh serve myapp.py command without pull session), however, when combined with Flask (and with pull session), the pull_session fails with below error msg.
`OSError: Cannot pull session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)
`
Here is my flask code:
```
from flask import Flask, render_template
from bokeh.embed import server_document,server_session
from bokeh.server.server import Server  # If i comment this, I  get above 'Cannot pull session document...' error. 
from bokeh.client import pull_session

app = Flask(__name__)

#create index page function
@app.route("/")

def index():
    myurl = "http://localhost:5006/mybokeh"
    session = pull_session(url=myurl)
    bokeh_script = server_session(None, url=myurl, session_id=session.id)
    return render_template("index.html",bokeh_script=bokeh_script)

#run the app
if __name__ == "__main__":
    app.run(debug=True)
```
If i comment below line I get the above pull session error and I if uncomment it, it works absolutely fine.
`from bokeh.server.server import Server`

Link to discussion in [discourse](https://discourse.bokeh.org/t/pull-session-doesnt-work-if-i-dont-include-from-bokeh-server-server-import-server-statement-which-i-am-not-using-anywhere/6195)

**Comment by bryevdv** [comment]
This is almost certainly that this fix:
```
# See https://github.com/bokeh/bokeh/issues/9507
if sys.platform == 'win32' and sys.version_info[:3] >= (3, 8, 0):
    import asyncio
    if type(asyncio.get_event_loop_policy()) is asyncio.WindowsProactorEventLoopPolicy:
        # WindowsProactorEventLoopPolicy is not compatible with tornado 6
        # fallback to the pre-3.8 default of WindowsSelectorEventLoopPolicy
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
is only done on `bokeh.server` imports and is not on the `bokeh.client` codepath

**Comment by bryevdv** [comment]
@gopimandala We are going to have a 2.2.1 quick fixes release very soon. I would like to include but, but need a verification that this is actually the correct diagnosis. Can you confirm whether adding these lines to your script also fixes things (i.e. if you remove the extra server import)


```
import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by gopimandala** [comment]
Hi Bryan, as mentioned in the discourse portal, these 2 lines fix the issue and it works even i remove the extra server import statement.
