### ISSUE TITLE
[BUG] Regression causing multiple js_on_event subscribers to be ignored

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#10435]
In Bokeh 2.2 there has been a major regression causing multiple events subscribed with js_on_event to be ignored, i.e. only the last subscribed event is processed. In the example below you will notice that when performing a box_select it will print both 'foo' and 'bar' to the console on selection when using bokeh 2.1.1 but only prints 'bar' in 2.2.

```python
from bokeh.events import SelectionGeometry
from bokeh.models import ColumnDataSource, CustomJS, Rect
from bokeh.plotting import figure, output_file, show

output_file('js_on_event_regression.html')

source = ColumnDataSource(data=dict(x=[], y=[], width=[], height=[]))

cb1 = CustomJS(code="""console.log("foo")""")
cb2 = CustomJS(code="""console.log("bar")""")

p = figure(plot_width=400, plot_height=400, tools="box_select",
           title="Select Below", x_range=(0, 1), y_range=(0, 1))

rect = Rect(x='x', y='y', width='width', height='height',
            fill_alpha=0.3, fill_color='#009933')

p.add_glyph(source, rect, selection_glyph=rect, nonselection_glyph=rect)

p.js_on_event(SelectionGeometry, cb1)
p.js_on_event(SelectionGeometry, cb2)

show(p)
```

**Comment by mattpap** [comment]
https://github.com/bokeh/bokeh/blob/5045aca77623712b52918f6a636ce55d231445e9/bokeh/model.py#L371

**Comment by mattpap** [comment]
Although even with this fixed, it doesn't work. There must be a secondary issue.

**Comment by philippjfr** [comment]
Between this and #10434 can we accelerate the timeline for a 2.2.1 release? These are both pretty major regressions.

**Comment by bryevdv** [comment]
Sure, once both are fixed with tests (and we can back port legacy inline
fix too)
