### ISSUE TITLE
Figure toolbar is fixed on screen when scrolling down on app hosted by bokeh server

### ISSUE THREAD

**Issue by laurafeuerhake** [bokeh/bokeh#10430]
The figure toolbar is fixed at a specific screen position and does not stay next to the figure when scrolling down on the page.
When loading the page, everything seems to be fine:
![image](https://user-images.githubusercontent.com/33908698/91280957-cdf1d280-e787-11ea-801b-b510445850b1.png)
When scrolling down on the page:
![image](https://user-images.githubusercontent.com/33908698/91281056-ed88fb00-e787-11ea-9a6e-8a9b24b23f42.png)

**Comment by mattpap** [comment]
This shouldn't happen. We will need more information about the browser, platform, do you use any custom templates, etc. Preferably a reproducible test case should be provided.

**Comment by laurafeuerhake** [comment]
Hi Matt, Thanks for the fast answer, it was actually caused by some custom css template.
