### ISSUE TITLE
[BUG] incorrect Plot._check_bad_extra_range_name

### ISSUE THREAD

**Issue by poldavezac** [bokeh/bokeh#10443]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.2.0

#### Description of expected behavior and the observed behavior
the extra_rnage_name check fails incorrectly when  a callback is used  which has a renderer from a secondary plot with extra ranges.

#### Complete, minimal, self-contained example code that reproduces the issue
add the following patch to "tests/unit/bokeh/models/test_plots.py"
```
@@ -192,6 +193,7 @@ class TestPlotValidation:
         p, dep = figure(), figure()
         dep.extra_x_ranges['foo'] = Range1d()
         dep.grid.x_range_name="foo"
+        p.grid[0].js_on_change("dimension", CustomJS(code = "", args = {"toto": dep.grid[0]}))
         with mock.patch('bokeh.core.validation.check.log') as mock_logger:
             check_integrity([p])
         assert mock_logger.error.call_count == 0
```
This can be corrected by discarding Callback objects from collected models in Plot._check_bad_extra_range_name

I've created a branch with those changes, 3 lines in all. I'm happy to create a PR if that is the correct procedure.

**Comment by bryevdv** [comment]
@poldavezac I'd say go ahead and submit the PR, it will be easier to evaluate a PR (and iterate if necesssary)

I think this is also a somewhat more general problem with complicated object graphs and `CustomJS` args, @mattpap do you recall? But if there is a simple sensible fix for this specifically, we can put it in.

**Comment by mattpap** [comment]
> I think this is also a somewhat more general problem with complicated object graphs and CustomJS args, (...)

That's a different issue with cyclic graphs. Nevertheless, this issue is interesting on its own. I think that this validator is too broad. It should only look at `Plot`'s properties that contain "own" renderers (so `renderers` and `left`, `right`, `above`, `below` and `center` panels).

**Comment by bryevdv** [comment]
I think that this validator is too broad. It should only look at Plot's properties that contain "own" renderers (so renderers and left, right, above, below and center panels).

Looking at the actual check method now, I agree. I think it might predate those

**Comment by poldavezac** [comment]
I've updated my PR accordingly: checks performed on the plot's layouts and renderers
