### ISSUE TITLE
[BUG] MultiChoice disabled attribute is not working

### ISSUE THREAD

**Issue by maeglin89273** [bokeh/bokeh#10452]
#### Version
Bokeh 2.2.1
Python 3.8

#### Description
While I set disabled of MultiChoice widget to true in a button click callback, the widget is not disabled as expected.
However, it can be disabled at the initialization or immediately disabled after the initialization.
Errors are logged in the browser console.

#### Example code:
```
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import MultiChoice, Button

options = [str(i) for i in range(1, 10)]
multi_choice = MultiChoice(options=options)


disable_choices_button = Button(label='Disable')
def disable_choices():
    multi_choice.disabled = True
disable_choices_button.on_click(disable_choices)


widgets = column([multi_choice,
                  disable_choices_button])
curdoc().add_root(widgets)
```

#### Stack traceback and/or browser JavaScript console output

![multichoice_bug](https://user-images.githubusercontent.com/5237288/91927738-db213b00-ed0c-11ea-8deb-2504e83cf3a2.png)

**Comment by bryevdv** [comment]
Here is a debug version of the log:

<img width="489" alt="Screen Shot 2020-09-02 at 8 56 05 AM" src="https://user-images.githubusercontent.com/1078448/92006962-31d14980-ecfa-11ea-8860-00432c0d675a.png">

<img width="650" alt="Screen Shot 2020-09-02 at 8 57 27 AM" src="https://user-images.githubusercontent.com/1078448/92007081-588f8000-ecfa-11ea-9316-8c69a6254d71.png">
