### ISSUE TITLE
LabelSet does not display with categorical coordinates

### ISSUE THREAD

**Issue by kiramt** [bokeh/bokeh#10454]
### Version info

Python version      :  3.7.4 (default, Sep 28 2019, 16:39:19)
IPython version     :  (not installed)
Tornado version     :  6.0.4
Bokeh version       :  2.2.1 or 2.2.0
node.js version     :  (not installed)
npm version         :  (not installed)

### Description
I have a heatmap coded in Bokeh which has one row set up to display text via a LabelSet rather than rects. It works fine in Bokeh 2.1.1 but in 2.2.0 and 2.2.1 the text does not display. There are no error messages. The behaviour is the same in Chrome (84.0.4147.135) and Safari (13.1.1).

Here is how it looks in 2.1.1:

![Screen Shot 2020-09-02 at 15 06 38](https://user-images.githubusercontent.com/18192472/91993968-ec2e7400-ed2d-11ea-9c38-5ae9bbaa96ce.png)

and in 2.2.0 / 2.2.1:

![Screen Shot 2020-09-02 at 15 07 18](https://user-images.githubusercontent.com/18192472/91994022-01a39e00-ed2e-11ea-8160-94e4ca3ae310.png)

### Example code
```
from bokeh.models import ColumnDataSource, LinearColorMapper, LabelSet
from bokeh.plotting import figure, output_file, show
from bokeh.palettes import RdBu11
from bokeh.transform import transform

output_file("label.html", title="label.py example")
mapper = LinearColorMapper(palette=RdBu11, low=0, high=1)

source = ColumnDataSource(data=dict(ys=["A", "B", "A", "B", "A", "B"],
                                    xs=["1", "1", "2", "2", "3", "3"],
                                    scores=[0, 0.4, 0.2, 0.1, 0.5, 0.8]))

textsource = ColumnDataSource(data=dict(ys=["Original", "Original", "Original"],
                                    xs=["1", "2", "3"],
                                    text=['A', 'B', 'B']))

p = figure(x_range=["1", "2", "3"], y_range=["Original", "A", "B"])
p.rect(x='xs', y='ys', width=1, height=1, source=source, line_color=None,
       fill_color=transform('scores', mapper), name="scores")

labels = LabelSet(x='xs', y='ys', text='text', level='annotation',
              x_offset=-5, y_offset=-5, source=textsource, render_mode='canvas')

p.rect(x='xs', y='ys', width=1, height=1, source=textsource,
               fill_color="white")

p.add_layout(labels)

show(p)
```

**Comment by bryevdv** [comment]
@kiramt This does not have anything to do with `rect `glyphs, the text does not display even if the rects are removed. 

@mattpap the rendered label examples in the docs work:

https://docs.bokeh.org/en/latest/docs/user_guide/annotations.html?x=labelset#labels

My best quick guess is that it's the combination labels and *categorigal coordinates* that have regressed.

**Comment by mattpap** [comment]
`LabelSet.{x,y}` have `NumberSpec` type instead of `Coordinate{X,Y}`, which results in storing categorical labels in typed arrays (results in arrays of `NaN`s).

**Comment by bryevdv** [comment]
I'll try to push a fix today or tomorrow

**Comment by mattpap** [comment]
I already prepared a PR fixing this and other annotations.

**Comment by kiramt** [comment]
Awesome, thank you!

**Comment by gambitvk** [comment]
HI Guys,

I am using version 2.3.0.dev3. and trying to get labels happening  with the below code.  contents of A and B are strings ... and content of C is float. 

Everything works including the hover tool ... but i can't seems to get the labelset to output value of C inside each box of the heatmap. This feels similar to the bug that this was mean to fix?

any ideas? cheers 

`
 self.source = ColumnDataSource({'A': [], 'B': [], 'C': []})

        hover = HoverTool(tooltips=[('A', '@A')])

        p = figure(plot_width=PLOT_WIDTH, plot_height=PLOT_HEIGHT, title=f'some name',
                   x_range=[], y_range=[], toolbar_location=None, tools=[hover], x_axis_location='above',
                   x_axis_label='Expiry', y_axis_label='Trading_day')

        p.rect(x='A', y='B', width=1, height=1, source=self.source,
               line_color=None, fill_color=transform('volume', self.mapper))

        color_bar = ColorBar(color_mapper=self.mapper, location=(0, 0),
                             ticker=BasicTicker(desired_num_ticks=len(self.colors)),
                             formatter=PrintfTickFormatter(format='   %d'))

        labels = LabelSet(x='A', y='B', text='C', level='glyph',
                          text_align='center', source=self.source, render_mode='canvas')

        p.add_layout(labels)
        p.add_layout(color_bar, 'right')
        p.axis.axis_line_color = None
        p.axis.major_tick_line_color = None
        p.axis.major_label_text_font_size = '12px'
        p.axis.major_label_standoff = 0
        p.xaxis.major_label_orientation = 1.0

        return p
`

**Comment by bryevdv** [comment]
@gambitvk this is unrelated to the issue. `LabelSet` only displays string columns (this is expected). You will need to convert the value in the "C" column to be strings.

**Comment by gambitvk** [comment]
@bryevdv thanks for picking that out !!
