### ISSUE TITLE
[BUG] `DateSlider` and `DateRangeSlider` ignore `format` set to an instance of `TickFormatter`

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10468]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.2

#### Description of expected behavior and the observed behavior
The type of the `format` property is `Either(String, Instance(TickFormatter))`. However, if you pass an instance of `TickFormatter`, the formatter is completely ignored.

#### Complete, minimal, self-contained example code that reproduces the issue
```python
from datetime import date

from bokeh.io import show
from bokeh.models import DateSlider
from bokeh.models.formatters import DatetimeTickFormatter

slider = DateSlider(start=date(2020, 1, 1),
                    end=date(2020, 8, 1),
                    value=date(2020, 1, 1),
                    format=DatetimeTickFormatter())

show(slider)
```

The root cause is that both `DateSlider` and `DateRangeSlider` just assume that `format` is a string and use it as such.

**Comment by mattpap** [comment]
Easy to fix, but we need to investigate why the type system didn't raise an issue with the existing code.

**Comment by mattpap** [comment]
Well, it's this way by design. Maybe an eslint-typescript rule exists that would help with this.
