### ISSUE TITLE
[TASK?] docs/{release,installation}.rst have empty toctrees, which can be removed

### ISSUE THREAD

**Issue by pradyunsg** [bokeh/bokeh#10465]
The empty toctree directive in docs/release.rst results in adding an empty `<ul>` element to it, which is a no-op under the current Sphinx theme. Thus this directive is a no-op and can be removed to simplify the file.

**Comment by gaurlakshya** [comment]
Hey @pavithraes 
I want to work on this issue. Will you please tell me that how can i start
and what is the exact file location in which i have to make changes.
