### ISSUE TITLE
Add link to community page on all websites

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh#10473]
A link to https://bokeh.org/community/ needs to be added to the footers:
- [ ] https://docs.bokeh.org/en/latest/
- [ ] https://demo.bokeh.org/

**Comment by AdityaJ7** [comment]
Can I work on this issue?

**Comment by pavithraes** [comment]
@AdityaJ7 Sure! The link needs to be added as 'Support' under 'Hands On' in the footers. It's already been added to https://bokeh.org/, you can see that for reference. :)

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Sure! The link needs to be added as 'Support' under 'Hands On' in the footers. It's already been added to https://bokeh.org/, you can see that for reference. :)

Hey, thanks for the guidance I have a small question. I just have to update this file right: https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/bokeh/footer.html

**Comment by pavithraes** [comment]
@AdityaJ7 Yes, that is correct

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Yes, that is correct.

I have made the PR, thanks for helping me out, you can check if it is correct

**Comment by bryevdv** [comment]
@pavithraes maybe a separate issue on the demo site repo for that change?
