### ISSUE TITLE
Update documentation section of the developer docs

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh#10482]
Documentation section of developer docs: https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html

* Rearrange [build the documentation section](https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html#build-the-documentation) -- Move information about environment variables before docs build command.
While following the steps top-down, setting GOOGLE_API_KEY step can be missed. It looks like a common issue while building the docs, reordering might help to some extent.
* Add Windows-specific build steps:
  * Setting environment variables in Windows command prompt and powershell
  * Use of `make.bat` in windows instead of `make`

**Comment by varianceslayer** [comment]
@pavithraes I am working on this. Any lead on the windows part would be helpful. Thanks

**Comment by pavithraes** [comment]
@varianceslayer I believe #10500 already covers this issue among other things. Would you be interested in working on a different issue? I'd prefer avoiding duplication of effort. :)

**Comment by varianceslayer** [comment]
Yeah sure. Would be happy to contribute to something. Let me know if you have any suggestions. Thanks a lot!

**Comment by pavithraes** [comment]
@varianceslayer You can take a look at the other issues marked as [good-first-issues](https://github.com/bokeh/bokeh/labels/good%20first%20issue). If you'd like to work on a similar documentation quick fix, you may consider: #10467
