### ISSUE TITLE
Add button_type with no border

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#10505]
One of my first pains when starting to use Panel/ Bokeh was that there is no `button_type` without a border.

This is a pain if you would like to create an icon button like

![image](https://user-images.githubusercontent.com/42288570/93562430-50844100-f986-11ea-9765-8c71d875955f.png)

or if you would like to create buttons that look like links

![image](https://user-images.githubusercontent.com/42288570/93562557-8aedde00-f986-11ea-96b0-9a494082e1f0.png)

You can off course solve this by a little bit of css.

```html
<style>
.bk-root .bk-btn-default {
    border-width: 0px;
}
</style>
```

But one of the promises of Bokeh/ Panel as I see it is that this is a high level framework where you can do most common things quickly and from Python.

I believe buttons without borders are a very common use case.

## Solution

Add a `button_type` similar to `default` but with `border-width: 0px;`.

I don't know what is should be called but here are some suggestions `flat`, `neutral`, `no_border`,  `link` or `stealth`.

## Additional Context

Let me know if you would accept a PR for this.

In fast.design a button without borders is called `stealth`

![image](https://user-images.githubusercontent.com/42288570/93565727-1f0e7400-f98c-11ea-8c65-6062e320da9c.png)

The Material Design buttons have no border by default

![image](https://user-images.githubusercontent.com/42288570/93565800-3cdbd900-f98c-11ea-86fc-572f88c7af06.png)

FYI. @philippjfr

**Comment by mvashishth** [comment]
Can I work on this?

**Comment by mattpap** [comment]
> Can I work on this?

See "linked pull requests".

**Comment by mvashishth** [comment]
Apologies, didn't see that. I'll look for some other issue to work on.

**Comment by MarcSkovMadsen** [comment]
@mvashishth . Feel free to give the linked pull request an iteration. I am not aware of anything missing. But it’s not been accepted yet. So maybe there is something missing.

**Comment by mvashishth** [comment]
@MarcSkovMadsen Can you please tell me where exactly this feature is required and how does it work?
