### ISSUE TITLE
Render method of AbstractButton does not support Icon that replaces element

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#10501]
#### Summary

I am trying to implement an `SVGIcon` widget for Panel. A part of this is a `SVGIcon` bokeh model. I can see that the `render` part of https://github.com/bokeh/bokeh/blob/branch-2.3/bokehjs/src/lib/models/widgets/abstract_button.ts should be changed as shown below.

![image](https://user-images.githubusercontent.com/42288570/93428826-6d564100-f8c0-11ea-971d-1581823d5192.png)

to support replacing the`icon_view.el` element instead of modifying it in the `icon_view.render` method.

Alternative: Please tell me I should never replace `icon_view.el` but only modify it including adding children. And why :-)

#### Details

The `render` part of the `SVGIconView` replaces `this.el` instead of updating it.

```typescript
render(): void {
    super.render()

    if (this.model.svg!=null && this.model.svg!=""){
        const el = htmlToElement(this.model.svg)
        if (el!==null){
          this.el=el
        } else {
          this.el = document.createElement("svg")
        }
    }
    this.el.style.display = "inline"
    this.el.style.verticalAlign = "middle"
    this.el.style.fontSize = `${this.model.size}em`
    this.el.style.fill = this.model.fill_color
    if (this.model.spin_duration>0){

    }

    this.el.classList.add("icon")
    this.el.classList.add(`icon-${this.model.name}`)
  }
```

This is different than the fontawesome custom example in the Bokeh github repo. And it also reveals that the render method of the AbstractButton should be modified as shown below.

https://github.com/bokeh/bokeh/blob/branch-2.3/bokehjs/src/lib/models/widgets/abstract_button.ts

#### Additional Context

Let me know if you would like a PR. Thanks.

For now I will just modify `el` instead of replacing it. I'm replacing it to keep things as small and efficient as possible. But maybe I should not do that?

**Comment by MarcSkovMadsen** [comment]
Just as inspiration I have the Bokeh and Panel code working.

![svg_icon](https://user-images.githubusercontent.com/42288570/93433772-8d3d3300-f8c7-11ea-97fb-1a5d41ebace8.gif)

**Comment by mattpap** [comment]
> The render part of the SVGIconView replaces `this.el` instead of updating it.

That's against the design. `this.el` is readonly. Your options are either to set `tagName` to `svg` or to add `<svg>` child to the existing `this.el`.

**Comment by MarcSkovMadsen** [comment]
Ok. Thats fine. Just think I've seen some code I've not written that replaces `this.el`.
