### ISSUE TITLE
Documentation: Wrong date in footer

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#10529]
The docs still display last year's date in the footer: 

![grafik](https://user-images.githubusercontent.com/39711796/94303061-18e73d00-ff22-11ea-8475-6cd10f4b10fb.png)

**Comment by pavithraes** [comment]
@tcmetzger Nice catch! Thanks! I see this needs to be updated in the [demo site](https://demo.bokeh.org/) too, shall correct it there. :)
