### ISSUE TITLE
[BUG] Updating color in CDS does not rerender

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#10527]
Coloring does not seem to update when you trigger a change in the CDS until the glyph is repainted, e.g. by panning/zooming it out of frame. This occurs for explicit colors but also colormapped values. In the example below I reverse the colors on a custom tool event but it doesn't update until I zoom in and out:

```python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, CustomJS, CustomAction

p = figure()

cds = ColumnDataSource(data={'x': [0, 1], 'y': [0, 1], 'color': ['red', 'green']})

p.scatter(source=cds, x='x', y='y', color='color', size=20)

cb = CustomJS(args={'cds': cds}, code="""
cds.data['color'] = cds.get_column('color').reverse()
""")

tool = CustomAction(callback=cb)

p.tools.append(tool)

show(p)
```

![color_issue](https://user-images.githubusercontent.com/1550771/94173716-9e241080-fe94-11ea-9e6e-795e8bc5656c.gif)

This happens with Bokeh 2.2.1, I haven't yet gone back and see when this regressed.

**Comment by bryevdv** [comment]
@philippjfr This is expected? It's AFAIK always been the case that you have to replace `source.data` *entirely* (else, explicitly call `source.change.emit` manually)

**Comment by philippjfr** [comment]
Oh right sorry. Even with the emit this happens.

**Comment by bryevdv** [comment]
This code works as expected for me with 2.2.1
```
cb = CustomJS(args={'cds': cds}, code="""
  cds.data['color'] = cds.get_column('color').reverse()
  cds.change.emit()
""")
```
Can you update the OP with your version?

**Comment by philippjfr** [comment]
I think I only tried `cds.properties.data.change.emit()` but I guess I keep getting confused when to use that and when to use `cds.change.emit()`. Closing since it's not really a bug.
