### ISSUE TITLE
[Feature] Support full text search for MultiChoice and  auto complete input 

### ISSUE THREAD

**Issue by mukeshkdangi** [bokeh/bokeh#10525]
Bokeh 2.1.1, Python 3, Windows 10, Chrome 

#### Description of expected behavior and the observed behavior

**1. Bokeh  Multichoice search is not working as expected. When type a string suggestion list in dropdown is not showing correct results** 
For example Dropdown list has around 7 elements containing 'ca' as a substring but when i type 'ca' only 4 elements shows up in the drop down instead of 7. 
![Bokeh_drop_down_search_error_1](https://user-images.githubusercontent.com/4831230/94123714-ff060700-fe08-11ea-929b-c5923fc2a636.png)
![Bokeh_drop_down_search_error_2](https://user-images.githubusercontent.com/4831230/94123725-0200f780-fe09-11ea-82d7-c9f626cb1409.png)

**2. Bokeh auto complete is not showing results for sub string. It only shows when we type string from start. I tried using modified version of bokeh-widget-2.2.1.js but for some reason bokeh is still able acess bokeh-widget.min.js** 

_2.1. Sub String search is not working which very essential thing when we talk about search. 
2,2 I added bokeh-widgets-2.1.1.js JS file in my code as :_ 
```
 <script src="/bokeh_app/static/js/jquery.min.js"></script>
    **<script src="/bokeh_app/static/js/bokeh-widgets-2.1.1.js"></script>**
    <script src="/bokeh_app/static/js/jquery-ui.min.js"></script>
<script src="/bokeh_app/static/js/bokeh-2.1.1.js"></script>
<script src="/bokeh_app/static/js/bokeh-api.min.js"></script>
<script src="/bokeh_app/static/js/bokeh-gl.min.js"></script>
<script src="/bokeh_app/static/js/bokeh-tables.min.js"></script>

```

H**owever Bokeh is accessing **bokeh-widgets.min.js**  instead of modified ``` **<script src="/bokeh_app/static/js/bokeh-widgets-2.1.1.js"></script>**``` which is not there in my project structure at all.**  
![Bokeh_minJS_error](https://user-images.githubusercontent.com/4831230/94124590-0b3e9400-fe0a-11ea-85e5-d4426e2a2aab.png)

Any help regarding these two issues is very critical and appreciated

**Comment by bryevdv** [comment]
The MulitChoice is a wrapper around choices.js

https://github.com/jshjohnson/Choices

Whether or not we can support full-test support is entirely dependent on what choices.js can support. (Some investigation will  be needed, or if you know already please respond with details).

For the questions about developing BokehJS/building a custom BokehJS that is outside the scope of the issue tracker. The Dev Guide is here:

https://docs.bokeh.org/en/latest/docs/dev_guide.html

and the community support Discourse is here:

https://discourse.bokeh.org

**Comment by mukeshkdangi** [comment]
thanks for the update. 
can we do something in bokeh-widget.js for full text search.  The auto complete class has a function which has 'search_string.startswith(sub_string).' can we just try replacing that with 'includes()' API of JS. i was trying to do same but bokeh is by default using bokeh-widget.min.js instead of user included js.  
```
for (const text of this.model.completions) {
                        if (acnorm(text).includes(acnorm(value))) {
                            completions.push(text);
                        }
                    }
```

also i believe this Multichoice search is bug instead of a new feature. 

Thanks

**Comment by bryevdv** [comment]
> also i believe this Multichoice search is bug instead of a new feature.

Noted, but disagree.

> can we do something in bokeh-widget.js for full text search.

As I mentioned, the place to ask "how do I" support questions is the Discourse, not the issue tracker.

**Comment by mukeshkdangi** [comment]
adding 'includes' worked for in case if AutoCompleteInout so it's better to add ` if (acnorm(text).includes(acnorm(value))) ` this line of code instead of `startsWith()` . I can not contribute because JS file is not available for contribution. 

Regarding ChoicesJS, wouldn't it be a simple HTML5 dropdown thing instead of relying on someone else's library which has issues.

**Comment by bryevdv** [comment]
> wouldn't it be a simple HTML5 dropdown thing instead of relying on someone else's library which has issues.

@mukeshkdangi The `MultiChoice` widget was added specifically because users loudly asked for a "modern" choice widget. If you don;t like it, nothing is forcing you to use it.  If you want a simple basic HTML dropdown, that is what the `Select`

https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#select

but note that it also only currently has "startswith" search capability.

> I can not contribute because JS file is not available for contribution.

I don't know what this means. If there is a change in BokehJS you think would improve things then you can fork this repository and submit the change as a pull request.

**Comment by rsdenijs** [comment]
I think the issue 1. that is listed in here is simply that choices.js only shows 4 results by default, it is listed in their readme ( searchResultLimit: 4,).  This is an option MultiChoice does not expose atm.

**Comment by philippjfr** [comment]
It would be quite straightforward to expose the `searchResultLimit` option on the MultiChoice widget (with a better name).
