### ISSUE TITLE
[FEATURE] Please add necessary testing files to pypi releases

### ISSUE THREAD

**Issue by epsilon-0** [bokeh/bokeh#10526]
Currently the pypi releases don't have everything needed to do the tests making it hard to validate if the install has succeeded on a system wide level when installing via the systems package manager.

Having tests along with the package makes it easy to verify the installation.

Thanks.

**Comment by epsilon-0** [comment]
Only needed file that is currently missing is the `conftest.py` file.

**Comment by bryevdv** [comment]
> Only needed file that is currently missing is the conftest.py file.

Unfortunately this is very far from the actual truth :) Bokeh spans both Python and Javascript (and in fact much of the actual work is in the JS component that ships with the library) and running all the tests, which include:

* Python Unit Tests
* JavaScript unit tests
* Image diff tests
* Integration tests
* Examples tests

requires the installation of many non-python components:

* NodeJS/NPM
* Typescript compiler
* Firefox, Chrome and Chrome Dev tools
* Other non-python dependencies

It not a trivial matter to run all the tests, and running them all in series would take well over an hour.  

Presumably you are referring to just the small subset of Python unit tests. I think the Python unit tests by themselves are of limited utility for package verification, so this is just not a high priority in my mind. That said if just including `conftest.py` is something that would be helpful, we would certainly accept a PR for that small single change (offhand probably just a change to the manifest file, and possibly a small change to config in setup.py as well)

**Comment by epsilon-0** [comment]
Indeed, so far we have only been running python unittests to do minimal verification, which also required npm for some tests, which I assume to mean that it also runs javascript unittests.

Running integration tests along with more complex tests is not something that we are aiming to do on our side, but even just the unittests do give a much better confidence for packaging :smile_cat: 

I am unsure how the pypi release is packaged so am at a loss about what to do in the PR.

**Comment by bryevdv** [comment]
> which also required npm for some tests, which I assume to mean that it also runs javascript unittests.

No the NPM in the Python unit tests is only for the Python-side `CustomJS` compilation capability. It does not run any of the actual BokehJS unit tests, which are under the `bokehjs` directory. 

> I am unsure how the pypi release is packaged so am at a loss about what to do in the PR.

If  you are familiar with PyPI packaging in general, it should be similar to including extra files in any Python package, i.e. adding to the manifest:

https://github.com/bokeh/bokeh/blob/branch-2.3/MANIFEST.in#L14

and then running `setup.py sdist` to check that it is included.

**Comment by amoh-godwin** [comment]
@epsilon-0 I strongly agree test are important for a project as big as bokeh. Currently, everything is breaking on my machine.
Do a:
`from bokeh.io import output_file`
and it tells you no name 'io' in module 'bokeh',  'bokeh' is not a package

But are you suggesting the tests be done on the user end or on the bokeh developer end? I am a bit confused. Forgive me

**Comment by bryevdv** [comment]
@amoh-godwin We have many thousands of tests, they run on every single commit in CI. We also do smoke tests with the final release packages before publishing. Whatever issue you are seeing, it is almost certainly something to do with your local system configuration, and not a problem with the released conda or pip package. So, the appropriate place to seek support for that is the project discourse: https://discourse.bokeh.org/

This issue is only about whether any how much to bundle the test files with the release packages, which after some thought I can simply state we will not do, for all the reasons listed above. Accordingly I close this as `coaction`

**Comment by amoh-godwin** [comment]
@bryevdv the issue I was seeing was due to an internal system problem of my making. It has been fixed. Sorry.
