### ISSUE TITLE
[BUG] scale_both sizing mode doesn't work when aspect ratio < 1

### ISSUE THREAD

**Issue by TeriForey** [bokeh/bokeh#10538]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 2.2.1
Python 3.8.2
Notebook 6.0.3
Mac OS Catalina 10.15.6
Chrome Version 85.0.4183.121

#### Description of expected behavior and the observed behavior

Setting the sizing mode to 'scale_both' should make the plots responsive irrespective of the aspect ratio. Instead, it only works on plots with a greater width than height. Plots with an aspect ratio less than 1, or with a greater 'plot_height' than 'plot_width' are not responsive.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import output_file, show
from bokeh.plotting import figure
from bokeh.layouts import row

x = list(range(11))
y0 = x

p = figure(aspect_ratio=1.59, sizing_mode='scale_both')
p.circle(x, y0, size=12, alpha=0.8, color="#53777a")

p2 = figure(aspect_ratio=0.59, sizing_mode='scale_both')
p2.circle(x, y0, size=12, alpha=0.8, color="#53777a")

output_file('plot.html')

show(row(p, p2))

```

#### Stack traceback and/or browser JavaScript console output

No warnings or errors reported in the console.

#### Screenshots or screencasts of the bug in action

Image shows a plot in real life going beyond the card boundary.

<img width="692" alt="Screenshot 2020-09-30 at 08 16 16" src="https://user-images.githubusercontent.com/8916421/94654638-4141b380-02f5-11eb-932c-d815169e0d30.png">

**Comment by bryevdv** [comment]
@TeriForey 

You need also to set the sizing mode on the `row`

```
show(row(p, p2, sizing_mode="scale_both"))
```
