### ISSUE TITLE
Help requested: Apply writing style guidelines to docs

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#10539]
Starting with the 2.3 branch, Bokeh will have style guidelines for writing documentation. Detailed information and instructions are available as [PDF (with links)](https://github.com/bokeh/bokeh/files/5307588/Bokeh-doc-guidelines.pdf) and as [RestructuredText file in the Bokeh repository](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/dev_guide/documentation.rst). 

The goal is to apply these new style guidlines to the existing documentation, as much as possible. Any help in updating the current docs is appreciated! 

Bokeh's new style guidelines for documentation writing are based on the [Google developer documentation style guide](https://developers.google.com/style). The most important things to keep in mind:

* Be aware of **sentence length**. Try to avoid sentences that require more than two commas. Consider breaking up longer sentences. You could also use bulleted or numbered lists instead.
* Use **sentence case for headlines** (capitalize words like in a regular sentence, but do not use any punctuation at the end).
* Avoid jargon or uncommon words and phrases. Keep in mind that many users of Bokeh don't use English as their primary language.
* Use **active voice** instead of passive voice whenever possible.
* Address the reader in the **second person ('you')**. Avoid using the first person ('we') or the third person ('the user').
* Use **American English** spelling and grammar (refer to Merriam-Webster for consistent spelling).
* Use **serial commas**, also known as Oxford Commas.
* Write in a way that is [inclusive ](https://developers.google.com/style/inclusive-documentation) and [accessible](https://developers.google.com/style/accessibility).
* Activate the **spell checker** in your development environment.
 
Feel free to ask any questions or add comments to this thread. Like all of Bokeh, the style guidelines are being adapted and improved all the time.

To avoid two people working on the same doc, please add a comment here or open a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) before you begin. Please link any pull requests regarding writing style updates to this issue. 

Thank you for your help!

**Comment by tcmetzger** [comment]
I'm currently working on those two files:
* https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/installation.rst
* https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/quickstart.rst

**Comment by varianceslayer** [comment]
@tcmetzger I wanted to contribute to this issue, quite confused which file to start with. Please suggest something. Thanks a ton!

**Comment by tcmetzger** [comment]
@varianceslayer Thank you for helping! Sorry about the confusion - I'd suggest picking a document in the User Guide to start with. All .rst files for the user guide are in the [/sphinx/source/docs/user_guide](https://github.com/bokeh/bokeh/tree/branch-2.3/sphinx/source/docs/user_guide) folder in the repo. You can work on any file you like (except for quickstart.rst and installation.rst, which I am currently working on). Maybe there is a topic that you are particularly interested in? For example, the [layouts section](https://docs.bokeh.org/en/latest/docs/user_guide/layout.html) is rather short and looks like a good place to start. The PDF file linked in my initial comment contains information and links about working with the .rst files and setting up a docs development environment.

I'd also suggest taking a look at the [Google developer documentation style guide](https://developers.google.com/style). An easy way to get started with Google's style guide are their free [technical writing courses](https://developers.google.com/tech-writing).

I hope this helps!

**Comment by bryevdv** [comment]
I was not aware of those courses, maybe those could also be linked in the dev guide docs chapter ? (if they are not already, and I just missed it)

**Comment by tcmetzger** [comment]
@bryevdv The courses are already in there, in the [Documentation style guidelines](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/dev_guide/documentation.rst#documentation-style-guidelines) section. 😃

**Comment by varianceslayer** [comment]
I am picking this file to work on
- https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/annotations.rst

**Comment by Konntroll** [comment]
Hi! Is it be okay if I take the chapter on Jupyter for editing?

- https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/jupyter.rst

**Comment by bryevdv** [comment]
@Konntroll Certainly, we'd love to have your contribution

**Comment by tcmetzger** [comment]
@Konntroll Absolutely, thanks a lot!

In addition to the User guide, we also always appreciate contributions to the [Developers Guide](https://docs.bokeh.org/en/latest/docs/dev_guide.html), available at https://github.com/bokeh/bokeh/tree/branch-2.3/sphinx/source/docs/dev_guide

**Comment by Konntroll** [comment]
#10556 
Finished with the edit and made a draft pull request for now as I expect some feedback so I can make adjustments. Looking forward to hearing what you guys think.

@tcmetzger, thanks for the suggestion. I think I'll start with the User guide docs and we'll see how it goes :-)

**Comment by tcmetzger** [comment]
In addition to [installation.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/installation.rst) and [quickstart.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/quickstart.rst), I'm also currently working on data.rst in the user guide (https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/data.rst).

**Comment by Konntroll** [comment]
I'll take over layout.rst here https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/layout.rst.

**Comment by Konntroll** [comment]
I'll also take on bokeh.js here https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/bokehjs.rst.

**Comment by Konntroll** [comment]
Taking over [export.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/export.rst).

**Comment by Konntroll** [comment]
Will also take over [graph.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/graph.rst).

Unrelated to the above but relevant to some other docs:
We have sub-sections in some of the docs that start with 'Note' or 'Warning' on a separate line preceding a paragraph containing the note or warning. Would it not be better to give these words some emphasis and merge them with the paragraph they introduce like so?

**Note:** Google has its own Terms of Service for ...

or

**Warning:** Behind the scenes, Bokeh converts the GeoJSON coordinates ...

**Comment by mattpap** [comment]
Status of `sphinx/source/docs/user_guide`:
- [ ] ├── annotations.rst
- [ ] ├── bokehjs.rst
- [ ] ├── categorical.rst
- [ ] ├── cli.rst
- [ ] ├── compat.rst
- [ ] ├── concepts.rst
- [ ] ├── data.rst
- [ ] ├── embed.rst
- [ ] ├── export.rst
- [ ] ├── extensions_gallery
- [ ] │   ├── latex.rst
- [ ] │   ├── ticking.rst
- [ ] │   ├── tool.rst
- [ ] │   ├── widget.rst
- [ ] │   └── wrapping.rst
- [ ] ├── extensions.rst
- [ ] ├── geo.rst
- [ ] ├── graph.rst
- [ ] ├── interaction
- [ ] │   ├── callbacks.rst
- [ ] │   ├── legends.rst
- [ ] │   ├── linking.rst
- [ ] │   └── widgets.rst
- [ ] ├── interaction.rst
- [ ] ├── jupyter.rst
- [ ] ├── layout.rst
- [ ] ├── notebook.rst
- [ ] ├── plotting.rst
- [ ] ├── quickstart.rst
- [ ] ├── server.rst
- [ ] ├── styling.rst
- [ ] ├── tools.rst
- [ ] └── webgl.rst

(tick means claimed)

**Comment by tcmetzger** [comment]
@Konntroll I believe what you are seeing are Sphinx directives (["paragraph level markup"](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#paragraph-level-markup)). Sphinx renders any indented text following a directive like `.. warning::` or `.. tip::` as a colored box for emphasis. So, the structure of these directives should be left intact (but you can change the text, or even create new boxes or move existing ones).
![grafik](https://user-images.githubusercontent.com/39711796/95767137-24986a80-0c69-11eb-8dec-ae3203ebecf8.png)

**Comment by Konntroll** [comment]
@tcmetzger, you are right. That's what I get for jumping between different editors. Thanks for pointing that out :-)

**Comment by Konntroll** [comment]
Taking over [categorical.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/categorical.rst).

**Comment by Konntroll** [comment]
Taking over compat.rst.

Btw, any reason this issue is now closed? Should I be doing anything differently now that it is?

**Comment by mattpap** [comment]
See https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords, though your PRs don't seem to adhere to this, so I don't know. I will keep reopening this issue. My (at least) pattern is to use `addresses #NNNN` when I don't want to close an issue.

**Comment by pillemer** [comment]
Hey, would love to help! Can I take over geo.rst?
I have read the contributing guidelines but this is my first time contributing to an open source project so any advice, comments or directions would be great.

**Comment by Konntroll** [comment]
Taking over [cli.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/cli.rst) and [concepts.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/concepts.rst). Seeing as cli.rst is only a paragraph long, I'll roll these two into one pull request.

**Comment by crricks** [comment]
Mind if I take of https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/tools.rst? 

Thanks!

**Comment by pavithraes** [comment]
@crricks Sure! We'd love to have your contribution :)

**Comment by samwill** [comment]
I can take [WebGL](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/webgl.rst)

**Comment by Konntroll** [comment]
I'll take [embed.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/embed.rst) now.

**Comment by Konntroll** [comment]
Taking on [extensions.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/extensions.rst) now.

**Comment by Konntroll** [comment]
Will take [plotting.rst](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/plotting.rst) now.

**Comment by Konntroll** [comment]
Will take server.rst now.

Should hopefully have more time to work on these in about a week. For now end-of-the-year surge at work is eating up lots of time and energy.

**Comment by tcmetzger** [comment]
I'm working on styling.rst!

**Comment by Konntroll** [comment]
If you don't mind, I'll take [Interactions](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/interaction.rst) with all the underlying sections:

- Linking behavior
- Interactive legends
- Adding widgets
- JavaScript callbacks

**Comment by tcmetzger** [comment]
With #10900, all files of the user guide have been updated. I'll close this issue (and potentially open a new one for updates to the dev guide). Thanks everyone for your help!!
