### ISSUE TITLE
[FEATURE] Add x-box-select & y-box-select specific icons.

### ISSUE THREAD

**Issue by erezinman** [bokeh/bokeh#10533]
Please add these tool-specific icons. I created a possible x-box-select icons that you can use (I assume no rights for them, if that's a problem). The y-select tool is just a rotation of the x-select-tool's icon by 90-degrees.

![XBoxSelect](https://user-images.githubusercontent.com/4324329/94421590-7384d100-018e-11eb-8f24-49f0a4709f82.png)
![XBoxSelect_2](https://user-images.githubusercontent.com/4324329/94422104-3836d200-018f-11eb-9287-59abc5899b5d.png)

**Comment by tcmetzger** [comment]
Hi @erezinman, thank you for your suggestion and the icons, and sorry it took us so long to reply! In order for us to review your idea, we'd need more information. Please follow the instructions on https://github.com/bokeh/bokeh/blob/branch-2.4/.github/ISSUE_TEMPLATE/feature_request.md. Thank you!
