### ISSUE TITLE
[BUG] Bokeh 2.3.0.dev1 version (the latest on pypl) doesn't display with Holoviews in Jupyter Notebook

### ISSUE THREAD

**Issue by erezinman** [bokeh/bokeh#10535]
Inside a Jupyter notebook, using Bokeh 2.3.0.dev1, the following code displays nothing:

```python
import holoviews as hv
hv.extension('bokeh')

hv.Curve([1,2])
```

I'm using the latest Holoviews version (1.13.4). When reverting to v2.2.1, the code runs well.

**Comment by philippjfr** [comment]
Thanks, I'll take a look at this tomorrow. Suspect it's some incompatibility with Panel.

**Comment by mattpap** [comment]
> `Error: Plot(1005).align given invalid value: null`

`LayoutDOM.align` doesn't allow `null`. It was a fluke that it worked before.

**Comment by erezinman** [comment]
So the problem is with HV?

**Comment by philippjfr** [comment]
Looks like it, I'll release 1.13.5 before 2.3 is officially released.

**Comment by philippjfr** [comment]
Closing as the fix is now in HoloViews.

**Comment by erezinman** [comment]
Thank you @philippjfr
