### ISSUE TITLE
Bad `super` call in "contexts.py"

### ISSUE THREAD

**Issue by erezinman** [bokeh/bokeh#10536]
I get the error 

>   File "/usr/local/lib/python3.6/dist-packages/bokeh/server/contexts.py", line 343, in __getattr__
>     return super.__getattr__(name)
> AttributeError: type object 'super' has no attribute '__getattr__'

when calling `print(doc.session_context.request.aruments)` inside the callback passed to `bokeh.server.server.Server` (terrible name-spacing, BTW).  As far as I understand, the call should be to `super().` rather than `super.`. 

Thanks

**Comment by mattpap** [comment]
@erezinman it would be great if you could submit a PR fixing this.

**Comment by nils-werner** [comment]
I think this issue arises because of a typo: `request.arguments` is defined and should run fine, only if you mistype it `request.aruments`, that's when `__getattr__()` gets called.
