### ISSUE TITLE
[BUG] Division element id of components can be invalid for CSS

### ISSUE THREAD

**Issue by annahadji** [bokeh/bokeh#10547]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

python: 3.7.7
bokeh: 2.2.1
jupyter_core: 4.5.0
jupyter_client: 5.3.3
Chrome 85
macOS Catalina 10.15.7

#### Description of expected behavior and the observed behavior

In CSS, identifiers cannot start with a digit, two hyphens, or a hyphen followed by a digit (see [reference](https://www.w3.org/TR/CSS21/syndata.html#characters)). 

In `make_globally_unique_id()`, `uid.uuid4()` in [L270 of serialization](https://github.com/bokeh/bokeh/blob/b56543346bad8cdabe99960e63133619feaafbb7/bokeh/util/serialization.py#L270) does not guarantee to return an id that starts with a-z or A-Z.

Fixing this would enable users to use css styling on a HTML element selected using the `id` attribute, which takes precedence over `class` selectors.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure
from bokeh.embed import components

p = figure(title="simple line plot")
p.line([1, 2, 3], [6, 7, 2], line_width=2)

plot_script, plot_div = components(p, wrap_plot_info=False)
print(plot_div.elementid)  # id will sometimes start with digit (e.g. 2ce2f0ca-3528-49a0-8b29-6384ac382220)
# ...
```

#### Screenshots or screencasts of the bug in action

Here is a codepen example of CSS requiring identifiers starting with [a-z, A-Z], where the ids have been generated from components. Note that JS doesn't have this requirement. https://codepen.io/annahadji/pen/KKMPpWb

#### Suggested fix(es)

* ~~Prepend a random character [a-z, A-Z] or `bk-` (to be consistent with bokeh css class names) to the generated id from `uid.uuid4()`. (Would it matter if the length of the id increased by a few characters?)~~
* ~~Or call `uid.uuid4()` in `make_globally_unique_id()` until a valid id is returned.~~

EDIT:
*  Most recent proposal from @mattpap and @bryevdv is to have a clean function that generates plain numeric IDs to use as Bokeh Model ids and a separate function that generates prefixed css-appropriate DOM ids in cases where the DOM is involved.

**Comment by mattpap** [comment]
Adding a prefix should be sufficient.

**Comment by mvashishth** [comment]
Hi. Is anyone working on this?

**Comment by bryevdv** [comment]
given the further thought in https://github.com/bokeh/bokeh/pull/10548#issuecomment-706548360 I am removing GFI for this
