### ISSUE TITLE
[BUG]Slope annotation is not drawn with gradient of 0

### ISSUE THREAD

**Issue by CRiddler** [bokeh/bokeh#10541]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
python: 3.8.5
bokeh: 2.2.1
jupyter_core: 4.6.3
jupyter_client: 6.1.6 
windows 10 Home

#### Description of expected behavior and the observed behavior
Slope does not draw any line when `gradient == 0`. I would expect it to draw a horizontal line. Seem funky to have to check if my gradient is near 0 and have an if statement to draw a horizontal Span instead of being able to specify `Slope(gradient=0, y_intercept=...)`

#### Complete, minimal, self-contained example code that reproduces the issue
```
# code goes here between backticks
from bokeh.plotting import figure
from bokeh.models import Slope
from bokeh.io import show

p = figure(width=200, height=200, x_range=(-1, 1), y_range=(-1, 1))

for gradient in [1, -1, 0]:
    s = Slope(gradient=gradient, y_intercept=0)
    p.add_layout(s)

show(p)
```

#### Stack traceback and/or browser JavaScript console output
No errors or warnings are raised

#### Screenshots or screencasts of the bug in action
Actual output:
![image](https://user-images.githubusercontent.com/31414128/94855370-42510e80-03e3-11eb-97ea-9ccd028b6e47.png)

Expected output:
![image](https://user-images.githubusercontent.com/31414128/94855575-952ac600-03e3-11eb-883c-556cfd776ade.png)

**Comment by bryevdv** [comment]
Marking as GFI. For anyone interested to tackle this, this relevant function in the BokehJS source code is here:

https://github.com/bokeh/bokeh/blob/0846e8598cf06a17265203bd2471902dac11d3d5/bokehjs/src/lib/models/annotations/slope.ts#L20

**Comment by chillytaka** [comment]
Hi, I'd like to work on this, is there something that I need to watch out for before I started ?
