### ISSUE TITLE
[FEATURE] DataSource with directly provided and derived series

### ISSUE THREAD

**Issue by cirnod** [bokeh/bokeh#10557]
**Problem Description**
I would like to plot a time series and provide in the hover tooltip the absolute and relative time. The absolute time (and the data values) are provided as a ColumnDataSource to the plot. It would be nice if I could add the relative time as a "special" series derived from the absolute time (e.g. relTime = absTime - fixedOffset). [CustomJSTransform](https://docs.bokeh.org/en/latest/docs/user_guide/data.html#customjstransform) provides something similar. However, as far as I can see, it is not possible to combine directly supplied series with a derived series in a single data source such that both series (directly supplied and derived) can be used in a hover tooltip. 

**Proposed Solution**
It would be nice if the ColumnDataSource source would support to add derived sources (e.g. via the `transform()` command) or if there would be a new type of [source](https://docs.bokeh.org/en/latest/docs/reference/models/sources.html#bokeh.models.sources.DataSource) which allows to combine directly supplied series with derived series. 

**Alternatives Considered**
It would be possible to simply generate an additional series with the values of the derived series (relative time) and add this series to the ColumnDataSource. However, in my opinion this is inefficient since it represents an unnecessary data duplication. Therefore, the suggested feature could help in reducing the HTML file size or the amount of streamed data since the derived series would be generated by JavaScript in the client (browser).

**Comment by bryevdv** [comment]
@cirnod If I understand your stated need then this could be accomplished already with a [`CustomJSHover`](https://docs.bokeh.org/en/latest/docs/reference/models/tools.html?highlight=customjshover#bokeh.models.tools.CustomJSHover) that combines existing columns with either other or outside data. 

If you agree this serves your use case then I think my personal position would be to close this to avoid adding complexity that is not demonstrably necessary.

**Comment by cirnod** [comment]
Thank you for the hint with CustomJSHover. I tested it with bokeh 2.2.2 and  2.3.0.dev1. Unfortunately, it seems that CustomJSHover does not completely satisfy my use case. As far as I see, it allows to format a given series only with one formatter (simple numeric or custom). In my use case I would need to add the same series twice, once with a simple numeric formatter and a second time with a custom formatter. When I try to add two tooltips with the same series but different formatters both tooltips show the value provided by CustomJSHover. 

I understand that the proposed way of enabling the use case with adding derived series to ColumnDataSource is probably not the best possible. After learning about the CustomJSHover approach, I think extending HoverTool/CustomJSHover such that it supports multiple different formatters for the same series might be a better approach.

**Comment by bryevdv** [comment]
@cirnod I think you have some misconceptions about `CustomJSHover` however I would consider resolving this to be a support question, so I would ask that you make a new topic on the community discourse and that we continue there:

https://discourse.bokeh.org/

Please provide a minimal complete example as a basis for the question, as discussions without real code can become unfocused.
