### ISSUE TITLE
BEP 9: Minimum downstream versions

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10558]
Following on from #9295 I'd like to codify our policy for tracking Python versions. I'd to propose that we reduce the burden on ourselves by adopting a policy that is either very simple, reactive to existing precedent, or both, e.g.:

* We will guarantee to support the three latest minor versions of Python, measured from 6 months after the latest minor release (to allow the later release some time for adoption), or
* We will follow NEP 29

Thoughs @bokeh/dev

**Comment by mattpap** [comment]
Given the new annual release cycle for Python, both almost equivalent (starting with 3.9). Though I would proceed with the first one, as it gives immediate indication how many versions are supported.

**Comment by bryevdv** [comment]
FYI NEP 29 suggests this for projects:

> We suggest that all projects adopt the following language into their development guidelines:
> 
> This project supports:
>
> * All minor versions of Python released 42 months prior to the project, and at minimum the two latest minor versions.
> * All minor versions of numpy released in the 24 months prior to the project, and at minimum the last three minor versions.

However, since NEP 29 was adopted, Python has moved from an 18 month cadence to a 12 month cadence, so adopting NEP as-is is more like 4 Python versions. So I agree that "number of versions" is simpler and clearer, and propose:

> Bokeh commits to supporting *at least* the three latest minor versions of Python. 
>
> To allow time for the most recent Python version to gain adoption, the clock starts three months after a new Python minor version is release.
> 
> **Example**:  Suppose Bokeh currently supports Python versions 3.9.x, 3.10.x, and 3.11.x. Python releases 3.12.0. Bokeh support for 3.9.x may not be dropped immediately, but only after three months have passed since 3.12.0 was released. 

Do we want also to make statements about Numpy? Two observations:

* We have this far been *extremely* conservative in supporting previous Numpy versions. Much more than NEP 29 suggests. 

* We don't actually currently test with the min numpy version in CI (but we probably should)

**Comment by bryevdv** [comment]
I've gone ahead and started the draft here:

https://github.com/bokeh/bokeh/wiki/BEP-9:-Downstream-Version-Support

**Comment by bryevdv** [comment]
cc @bokeh/core I have fleshed out the draft of the BEP a the link above. I think it is ready for review/adoption. Please take a look and register any comments, or 👍 / 👎  here in a comment

👍 from me

**Comment by ianthomas23** [comment]
@bryevdv My apologies, that was only a half-considered comment before I moved on to a meeting. I've actually read and understand it all now!

No, don't modify the historic information in the table, and numpy 1.18 seems a sensible choice for bokeh 3.0. So :+1: from me.

**Comment by bryevdv** [comment]
OK I think we already have enough agreement, but I will leave this open for another day in case anyone else wants to chime in. Otherwise I will plan to mark accepted and update the wiki tomorrow

**Comment by bryevdv** [comment]
<img width="348" alt="Screen Shot 2021-12-02 at 09 53 37" src="https://user-images.githubusercontent.com/1078448/144476683-3172a27b-5663-4ef8-8232-7bc8af6a9275.png">


and also from @ianthomas23 above. 

I will mark as accepted now.
