### ISSUE TITLE
[BUG] sizing_mode responsiveness issue when rendering two grapghs in a single row

### ISSUE THREAD

**Issue by tarun1992** [bokeh/bokeh#10584]
We are rendering the graph from python to Angular using bokeh js embed.

When rendering two graphs in a row and if use sizing_mode = "scale_both". Our goal is to make the graphs responsive to the front-end UI. 

Expected behavior: The embedded graphs should appear responsive.
Current behavior: The graphs expand the available width and two graphs are very big on the UI.

In the below screenshot, the graphs do not fit on the screen and expand the available width. 

![image](https://user-images.githubusercontent.com/4682201/96254641-411f0480-0fd3-11eb-8d83-d423caa8c507.png)
Backend - 
`   p2 = figure(x_range= month_year, plot_height=400, plot_width = 490  , sizing_mode="scale_both",  title=" Sample title",
            toolbar_location=None)`

Frontend - 
` Bokeh.embed.embed_item(divId);`
Bokeh JS - 2.2.2
Python - 3.7
Angular - 10

Any help would be appreciated.

**Comment by bryevdv** [comment]
@tarun1992 please provide a complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that can actually be run and investigated.

**Comment by mattpap** [comment]
Based on the given information, this may be a bug or a feature. We will need to know who exactly you embed those plots, i.e. is there a bokeh layout, or else what kind of CSS layout is being used, is there a custom template, etc. `scale_both` sizing mode means that plots (or layouts in general) will expand into available space in both directions (if used, aspect matching may distort things). If you want to fit into a certain space, it's up to you do design a CSS layout that will prevent bokeh layout to extend too far. This may require using `max-width` property, or otherwise properly constraining a flexbox or grid CSS layouts.

**Comment by tarun1992** [comment]
Thank you for your response. Basically, we have a requirement in which we have to show two graphs in a row, and to achieve this we are sending a response from python to angular via restful API. 
Frontend code - 
HTML -
`<div style="display: flex;">
<div [id]="id0"></div>
<div [id]="id0"></div>
</div>`

Typescript - 
`fetch(url)
.subscribe(()=>{
Bokeh.embed.embed_item(id0);
Bokeh.embed.embed_item(id1);
})`

Python - 
`p1 = figure(x_range= month_year, plot_height=400, plot_width = 490 , sizing_mode="scale_both", title=" Sample title", toolbar_location=None)
p2 = figure(x_range= month_year, plot_height=400, plot_width = 490 , sizing_mode="scale_both", title=" Sample title", toolbar_location=None)`

I have already used `max-width` on the frontend, it does not remain responsive and the graphs get cut and do not shrink as per the available width. Please let me know if I can use any other property available at the backend/frontend to achieve responsive behaviour without affecting the graphs remain cut.

I will try to create a sample example to replicate the behavior. 

Thank you for your help.

**Comment by bryevdv** [comment]
@tarun1992 will you be able to provide a minimal reproducing example? If not this will be closed soon as `norepro`

**Comment by bryevdv** [comment]
closed for lack of response
