### ISSUE TITLE
The empty_value property of EditTools needs generalizing

### ISSUE THREAD

**Issue by jlstevens** [bokeh/bokeh#10583]
The `EditTool` models have an [empty_value property](https://github.com/bokeh/bokeh/blob/branch-2.3/bokeh/models/tools.py#L1222) that inserts a given value into a CDS when a new glyph is inserted.

This works fine when you only need a new value for a single column (in the property docstring example this single column is 'color') but these tools should allow the insertion of new values for multiple columns. 

The API I would expect to support this would probably be a dictionary where the keys are the column names and the values can be `Bool`, `Int`, `Float`, `Date`, `Datetime`, `Color` or `String`.

**Comment by mattpap** [comment]
I suppose we could go a step further and ask what should be the default values for a data set's columns. Then `empty_value` would become an override to adjust the settings for the particular tool.

**Comment by bryevdv** [comment]
This seems nice to have, but I am moving it out of 2.3
