### ISSUE TITLE
2.2.3 Release 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10585]
@mattpap and I have both agreed that a 2.2.3 is warranted to get https://github.com/bokeh/bokeh/pull/10513 pushed out. I can make the release this weekend but need to know what else should go in this milestone. @mattpap can you create the milestone and add what you think should go in?

cc @bokeh/core comment below to propose any issues/PRs you think need to go in 2.2.3

**Comment by mattpap** [comment]
> can you create the milestone and add what you think should go in?

Sure. I will go ahead and backport the offending PR as well.

**Comment by bryevdv** [comment]
> add what you think should go in?

Habits die hard. I just realize this is exactly what we proposed *not* to do. So rather: Put in anything you backport yourself, and propose thigns to backport here in the issue (milestone should be updated *after* backports)

**Comment by bryevdv** [comment]
Marking this as `discussion` fow so that it does not end up in changelog. In the future I'd be fine with discussion+backports tag, or adjusting the changelog script to no include these somehow.
