### ISSUE TITLE
[BUG] Outdated example for CustomJSHover

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10581]
https://docs.bokeh.org/en/latest/docs/reference/models/tools.html?highlight=customjshover#bokeh.models.tools.CustomJSHover

It says to use `formatters=dict(y=lat_custom)`. But it should be `formatters={'@y': lat_custom}`, according to https://docs.bokeh.org/en/latest/docs/releases.html#hovertool-formatters-specification

**Comment by mvashishth** [comment]
Hi. I can take up the issue if that is fine.

**Comment by p-himik** [comment]
Of course!

**Comment by mvashishth** [comment]
Can you please point me to the repo that has the docs website?

**Comment by p-himik** [comment]
Most of the documentation is done via docstrings.
The particular line in question is here: https://github.com/bokeh/bokeh/blob/branch-2.3/bokeh/models/tools.py#L900

**Comment by mvashishth** [comment]
Are there any standards for making a pull request?
