### ISSUE TITLE
[BUG] Whiskers `base` have reduced precision

### ISSUE THREAD

**Issue by golmschenk** [bokeh/bokeh#10594]
# Software versions
bokeh==2.2.3
Python==3.8.5
macOS==10.15.7

# Description of expected behavior and the observed behavior
Whiskers with a `base` requiring high precision seem not to be correctly placed. Plotting both a scatter plot and whiskers with the same `x`/`base` results in the scatter points being positioned differently than the whiskers when high precision is required. The precision of the `base` seems to be reduced. 

# Minimal example
```
import pandas as pd
from bokeh.io import show
from bokeh.models import ColumnDataSource, Whisker
from bokeh.plotting import Figure

data_frame = pd.DataFrame({'x': [1, 1.0000001, 1.0000002, 1.0000003], 'y': [1, 2, 3, 4]})
data_frame['y_plus_error'] = data_frame['y'] + 1
data_frame['y_minus_error'] = data_frame['y'] - 1

source = ColumnDataSource(data_frame)
figure = Figure()
figure.scatter(source=source, x='x', y='y')
figure.add_layout(Whisker(source=source, base='x', upper='y_plus_error', lower='y_minus_error'))

show(figure)
```
The result appears as:
<img width="615" alt="Screen Shot 2020-10-22 at 9 11 44 PM" src="https://user-images.githubusercontent.com/1691031/96945367-92376880-14ab-11eb-9406-22eeef93b796.png">

A similar problem occurs for `'x': [1000000, 1000000.1, 1000000.2, 1000000.3]`, but it does not appear for `'x': [1, 1.1, 1.2, 1.3]`, suggesting it is due to lost precision.

**Comment by bryevdv** [comment]
Thanks for the complete issue @golmschenk  

@mattpap Seems we have another internal precision loss during internal conversions. This one is not related to a missing int64 type like #10513 though, since the df columns here are properly float64 (which should start out as float64 typed arrays)

**Comment by mattpap** [comment]
This works on `branch-2.3` with both variants of `x`. However, typing of "resolved" arrays is completely wrong, which may also indicated that there are still wrong code paths.

**Comment by bryevdv** [comment]
Well, I guess we could close this with a test-only PR then

**Comment by bryevdv** [comment]
discovered that `multi_line` is broken from precision on current `branch-2.3` @mattpap do you know if there is an issue?

**Comment by bryevdv** [comment]
Have gone ahead and made separate https://github.com/bokeh/bokeh/issues/10738 with MRE for multi line

**Comment by bryevdv** [comment]
This was fixed by https://github.com/bokeh/bokeh/issues/10738
