### ISSUE TITLE
[BUG] BokehJS minimal example is not working

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10599]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh v2.2.3

#### Description of expected behavior and the observed behavior
The example at https://docs.bokeh.org/en/2.2.3/docs/user_guide/bokehjs.html?highlight=javascript%20development#minimal-example should work as is, without any modifications.
Instead, it shows a blank page.

It fails because `plotting.ts/show` uses `document.body` but if a script is executed from within `<head>`, `document.body` is `null`.
The example can be fixed by just moving the last `<script>` inside the `<body>`, but I'm not sure if that's the correct fix.

The only other relevant issue that I've found is #7330 but it seems that that issue is completely outdated.

#### Stack traceback and/or browser JavaScript console output
```
Uncaught (in promise) TypeError: Cannot read property 'classList' of null
    at r (bokeh-2.2.3.min.js:572)
    at Object.t.add_document_standalone (bokeh-2.2.3.min.js:572)
    at Object.r.show (bokeh-api-2.2.3.min.js:51)
    at test.html:36
```

**Comment by mattpap** [comment]
In general it's up to the user to make sure that any scripts that touch DOM (especially under `<body>`) wait for DOM content loaded event before proceeding. Thus we typically include "user" scripts after DOM elements they intent to use. So, this example is wrong, but we can make it work without changes, by making `show()` wait for content loaded (it's already a very high-level, async function, so such change won't hurt it).
