### ISSUE TITLE
quote (') from networkx index node are translated to (&#x27;)

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#10604]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
last version Bokeh 2.2.2 
python 3.8
networkx 2.5
holoview 1.13.3
OS 10.13.6
safari firefox

old version:
previous version Bokeh 2.0(?)  January 2020 example displayed
networkx 2.4
python 3.5

#### Description of expected behavior and the observed behavior
All quote(') are now translated as (&#x27;) in the node index. This did not happen in any other mix of older versions. I am not manipulating the index. I will make a minimum code later when possible.
#### Complete, minimal, self-contained example code that reproduces the issue

```
node_hover_tool = HoverTool(tooltips=[("Node", "@index")])
plot.add_tools(node_hover_tool)

```
#### Screenshots or screencasts of the bug in action
![Screen Shot 2020-10-26 at 11 32 58 AM](https://user-images.githubusercontent.com/23002446/97213990-a2876600-177f-11eb-9480-0ce2c5ac8b3b.png)
![Screen Shot 2020-10-26 at 11 33 14 AM](https://user-images.githubusercontent.com/23002446/97213999-a5825680-177f-11eb-9a9e-8ff95aca637a.png)

**Comment by bryevdv** [comment]
> I will make a minimum code later when possible

Please do add one as soon as you can. I would like to do a bisection on this but will definitely need a complete, minimal example to work from. Also anything you can do to narrow down the "latest working version" will help narrow the search.

**Comment by mattpap** [comment]
This fails because first `replace_placeholders()` escapes `@text`'s value, which is passed to `textContent`, which interprets encoded HTML entities as literal character sequences. `replace_placeholders()` should not encode strings in raw string mode. It's `textContent`'s job to make sure XSS in not allowed. In other uses of this function, currently only `OpenURL`, a more appropriate encoding should be used, as `escape()` is not URL-safe.

**Comment by Pierretherenard** [comment]
Here is the code and a simple json file:
`
@staticmethod
    def minimal_network():
        import networkx as nx

        from bokeh.models import ColumnDataSource, HoverTool, Label
        from bokeh.plotting import figure, output_file, show, from_networkx
        from bokeh.models import Circle, MultiLine
        from bokeh.models.sources import CDSView

        the_path = FileStuff('your path to json file')

        G = FileStuff.read_json_file(the_path)

        edge_dict = dict()
        edge_dict['start'] = [x[0] for x in G.edges(data=True)]
        edge_dict['end'] = [x[1] for x in G.edges(data=True)]

        edge_attr_keys = [attr_key for edge in list(G.edges(data=True)) for attr_key in edge[2].keys()]
        edge_attr_keys = list(set(edge_attr_keys))

        for attr_key in edge_attr_keys:
            edge_dict[attr_key] = [edge_attr[attr_key] if attr_key in edge_attr.keys() else None
                                   for _, _, edge_attr in list(G.edges(data=True))]

        edg_col = list(edge_dict['value'])
        edge_color = []
        for i_col in range(len(edg_col)):
            edge_color.append('white')

        edge_source = ColumnDataSource(edge_dict)

        f_title = f"Network component with {G.number_of_nodes()} nodes and {G.number_of_edges()} edge. "

        big_width = 800
        plot = figure(title=f_title, plot_width=big_width, plot_height=400, x_range=(-1, 1), y_range=(-1, 1),
                      tools="pan,wheel_zoom,reset", active_scroll="wheel_zoom", toolbar_location="left"
                      , x_axis_type=None, y_axis_type=None)

        node_hover_tool = HoverTool(tooltips=[("Node", "@index")])
        plot.add_tools(node_hover_tool)

        graph_renderer = from_networkx(G, nx.spring_layout, scale=1, center=(0, 0))

        # Set edge attribute to Bokeh DataSource
        graph_renderer.edge_renderer.data_source = edge_source
        graph_renderer.edge_renderer.data_source.add(edge_color, 'edge_color')
        graph_renderer.edge_renderer.view = CDSView(source=edge_source)

        graph_renderer.node_renderer.glyph = Circle(size=10, fill_color="red",
                                                    line_color="white", line_width=1)
        graph_renderer.edge_renderer.glyph = MultiLine(line_color='edge_color', line_alpha=0.3, line_width=1)
        plot.renderers.append(graph_renderer)

        plot.xgrid.grid_line_color = None
        plot.ygrid.grid_line_color = None
        plot.background_fill_color = "#9e5e05"

        output_file("graph_test.html")
        show(plot)
`
no support of json so here are the lines:
`
{
"nodes":[
{"id": "No quote.", "group": 1 },
{"id": "One ' quote", "group": 1 }
],
"links":[
{"source": "No quote.", "target": "One ' quote", "value": 1}
]
}
`

**Comment by Pierretherenard** [comment]
oops forgot the class:
`
class FileStuff:

    def __init__(self, file_name):
        self.file_name = str(file_name)

    def read_json_file(self):
        import json
        from networkx.readwrite import json_graph

        with open(str(self.file_name)) as f:
            js_graph = json.load(f)
        return json_graph.node_link_graph(js_graph)
`

**Comment by bryevdv** [comment]
FYI @Pierretherenard code-blocks require *triple*-backticks (```) I have edited your posts
