### ISSUE TITLE
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.

### ISSUE THREAD

**Issue by Prashavu** [bokeh/bokeh#10601]
Trying to export image from bokeh/holoviews  and I get this error from **past 4 days**. Before that was working perfectly fine and used to open images on the IE. 
I had  installed geckodriver via `conda install -c conda-forge firefox geckodriver`.
Browser : IE 11.1518
Im not able to find out the root cause, because the geckodriver.exe is there in site-packages, I have also pasted a copy of the .exe  in the folder where python.exe is.Also tried to upgrade geckodriver,holoviews and bokeh nothing fixed the issue.
Python : 3.8
Browser : IE 11.1518

**Comment by bryevdv** [comment]
@Prashavu this is some usage or system configuration issue, not a burg report or feature request, so it should be directed to the community Discourse: https://discourse.bokeh.org
