### ISSUE TITLE
Add TOC to reference doc

### ISSUE THREAD

**Issue by mrx23dot** [bokeh/bokeh#10613]
Please add right hand side table of content to the docs for easier navigation
http://docs.bokeh.org/en/latest/docs/reference/plotting.html

like it's on this side 

https://docs.bokeh.org/en/latest/docs/user_guide/styling.html

Follow up from 
https://discourse.bokeh.org/t/documentation-fails-on-opera-browser/6611/3

**Comment by bryevdv** [comment]
I doubt we can add a right hand TOC simply because the Spinx theme we use simply does not work that way. It build TOCs from section/subsection structure and we will not be able to add that for methods in a class. But all the methods listed at the top used to be (should be) links, so we can make sure that those become links again to function as a TOC (just not floating on the right)

**Comment by mrx23dot** [comment]
Could be on any side.
As long as a new user can find .line( ) without searching with CTRL+F and finding 1000s of results.

Eg. left TOC could be replaced, or we could add a subsection which contains primitives.

**Comment by bryevdv** [comment]
@mrx23dot sorry I was not clear. The them we have presents technical limitations that prevent it from being on either side. We can make the be list at the top be a big list *of links* which is an effective TOC (but it won't be floating). That is the best we can do without creating our own custom Sphinx theme (an enormous effort)

**Comment by mrx23dot** [comment]
Whichever is the simplest. I would simply replace the left side navigation items with primitives.
And put the original items into drop down button, or onto an index page. 
Up to you guys, cheers!

**Comment by bryevdv** [comment]
Noting that the links at the top work on the 2.1.0 deployed docs, but do not work on the 2.2.0 deployed docs. So it could be some config change made between those two releases, or maybe a sphinx or other dependency change.
