### ISSUE TITLE
Storing static PNG for OpenGraph

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#10614]
I'm working on adding OpenGraph compatible meta tags to the docs. As discussed with @bryevdv, @pavithraes and @hyles-lineata, we need a place to store a publicly accessible, static PNG file that can be displayed as the default image whenever sharing a link on an opengraph-enabled website. 
This is the image that I would like to use for now ([download url](https://tcmetzger.de/STATIC/bokeh.png)): 
![bokeh](https://user-images.githubusercontent.com/39711796/97473956-cc1fc900-1908-11eb-927a-45eafe517374.png)
This image can be easily improved and replaced anytime by updating the static PNG file.

**Comment by bryevdv** [comment]
OK we just need to decide on a path. For reference, an existing URL on the static site is

https://static.bokeh.org/logos/logo.png

For something like this I think the path/filename should be somewhat specific or descriptive, in case we need to accommodate different or new versions in the future.

**Comment by tcmetzger** [comment]
How about `https://static.bokeh.org/opengraph/bokeh-logo.png`?

**Comment by bryevdv** [comment]
`bokeh-logo` is a bit to generic to me (and this is not, properly, the actual logo—I think we should use "logo" in a narrow sense) What does OG call these images, cards?

**Comment by tcmetzger** [comment]
As far as I know, the terminology is different for different implementations of the OpenGraph protocol. In the [official docs](https://ogp.me/#metadata) they say "og:image - An image URL which should represent your object within the graph." - so, how about:
`https://static.bokeh.org/opengraph/bokeh-og-image.png`

**Comment by bryevdv** [comment]
is it possible we might want to use different images in different contexts? I guess I was thinking more description e.g. `/opengraph/logotype-on-hex.png`

**Comment by tcmetzger** [comment]
Ah, I see - let's go with that!

**Comment by bryevdv** [comment]
For a little brevity in the URL that will be everywhere I also went with "og" for dirname:

http://static.bokeh.org/og/logotype-on-hex.png

**Comment by bryevdv** [comment]
@tcmetzger I guess last thing I'd double check: this image seems a bit on the large side? Is it typical for open graph images to be this large (size and/or dimensions) 

At some point probably ought to verify all the caching policy headers for our static content, there's no reason these can't be cached ~forever (both on cloud front and in users browsers locally)

**Comment by tcmetzger** [comment]
I'll probably optimize the file a bit, I currently need this mostly for testing.

**Comment by bryevdv** [comment]
OK just let me know, we will have to issue a cloudfront invalidation to update the file

**Comment by tcmetzger** [comment]
Will do!
