### ISSUE TITLE
Hovertool does not work for dynamically added glyphs

### ISSUE THREAD

**Issue by Neithiri** [bokeh/bokeh#10612]
#### Context : First I added a blue scatter plot to a figure and an hover tool. Then, I dynamically added an other scatter plot (a red one) thanks to a callback attached to a Button widget. I'm running the script on Bokeh server.
Expected behavior : The hover tool works for both scatter plots.
Observed behavior : The hover tool only works for the first scatter plot. (the blue one)
This issue does not appear when I directly add an other scatter plot without using a callback.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models import Button
from bokeh.io import curdoc, show
from bokeh.layouts import row
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.io import show

def update_button(click):
    source2 = ColumnDataSource({'x': [1, 2, 3], 'y': [3, 1, 2]})
    plot.circle(x='x', y='y', source=source2, line_color='red', fill_color='red', size=5)

TOOLTIPS = [('Ordinate ', '@y'),
            ('Abscissa ', '@x')]

plot = figure(tools = [], tooltips = TOOLTIPS)

source1 = ColumnDataSource({'x': [1, 2, 3], 'y': [1, 2, 3]})

plot.circle(x='x', y='y', source=source1, line_color='blue', fill_color='blue', size=5)

button = Button(label="Add scatter plot", button_type="default")

button.on_click(update_button)

curdoc().add_root(row(button, plot))

```
#### Screenshots or screencasts of the bug in action
![Enregistrement-_2](https://user-images.githubusercontent.com/73587866/97438880-b66ccc80-1925-11eb-99aa-6395c7ed3bea.gif)

**Comment by bryevdv** [comment]
@Neithiri Hover tool adds all available glyphs *at the time the tool is created in the browser*. Unfortunately there is no good way to for us to be able to automagically add glyphs after the fact. So it will always be the case that if you need that to happen, it would be by appending to the `renderers` list on the tool manually and explicitly.

However, it seems even manually managing the renderers to update is not currently supported. 

cc @mattpap as an aside this was one reason having "empty list" mean the same as "auto" was good: if you start with "auto" now, you can't do `p.hover[0].renderers.append(new_renderer)` even if appending worked currently. If you want to manually manage later, you have to manually manage from the start.

**Comment by bryevdv** [comment]
I'm triaging this as `feature` since it's not something we have ever promised.

**Comment by Neithiri** [comment]
> 
> 
> @Neithiri Hover tool adds all available glyphs _at the time the tool is created in the browser_. Unfortunately there is no good way to for us to be able to automagically add glyphs after the fact. So it will always be the case that if you need that to happen, it would be by appending to the `renderers` list on the tool manually and explicitly.
> 
> However, it seems even manually managing the renderers to update is not currently supported. That is something we can improve.
> 
> cc @mattpap as an aside this was one reason having "empty list" mean the same as "auto" was good: if you start with "auto" now, you can't do `p.hover[0].renderers.append(new_renderer)` even if appending worked currently. If you want to manually manage later, you have to manually manage from the start.

@bryevdv thanks for your quick answer. I confirm that manually managing the renderers does not work, I have already tried this.
I hope some day it will be improved.

**Comment by bryevdv** [comment]
@Neithiri in the mean time you can add all the glyph renderers up front and use the callback to toggle their `visible` property instead. In fact, this is what I would always recommend, even assuming this issue gets worked on some day. It is always advised to try to create the full "object graph" up front and then make updates by changing *data* and *properties* rather than by adding/deleting objects.

**Comment by Neithiri** [comment]
> 
> 
> @Neithiri in the mean time you can add all the glyph renderers up front and use the callback to toggle their `visible` property instead. In fact, this is what I would always recommend, even assuming this issue gets worked on some day. It is always advised to try to create the full "object graph" up front and then make updates by changing _data_ and _properties_ rather than by adding/deleting objects.

@bryevdv Thanks for your suggestion. I thought I could do that too. Unfortunately, I'm working with large data sets on a project, so adding all the glyph renderers up front is not conceivable.
Nevertheless, I managed to remove the hover tool before adding the second scatter plot and creating a new, it currently works.
Here is the full code :
```
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure
from bokeh.models import Button
from bokeh.layouts import row
from bokeh.io import curdoc

def update_button(click):
    plot.tools.pop()
    source2 = ColumnDataSource({'x': [1, 2, 3], 'y': [3, 1, 2]})
    plot.circle(x='x', y='y', source=source2, line_color='red', fill_color='red', size=5)
    hover = HoverTool(tooltips = TOOLTIPS)
    plot.add_tools(hover)

TOOLTIPS = [('Ordinate ', '@y'),
            ('Abscissa ', '@x')]

plot = figure(tools = [], tooltips = TOOLTIPS)

source1 = ColumnDataSource({'x': [1, 2, 3], 'y': [1, 2, 3]})

plot.circle(x='x', y='y', source=source1, line_color='blue', fill_color='blue', size=5)

button = Button(label="Add scatter plot", button_type="default")

button.on_click(update_button)

curdoc().add_root(row(button, plot))
```

**Comment by bryevdv** [comment]
>  Unfortunately, I'm working with large data sets on a project, so adding all the glyph renderers up front is not conceivable.

@Neithiri FY you can add the glyphs with empty data sources to start and update just the data at a later time.

**Comment by Neithiri** [comment]
> 
> 
> > Unfortunately, I'm working with large data sets on a project, so adding all the glyph renderers up front is not conceivable.
> 
> @Neithiri FY you can add the glyphs with empty data sources to start and update just the data at a later time.

This is a good idea ! Thanks for the suggestion @bryevdv.
