### ISSUE TITLE
[BUG] JS/Python version mismatch in 2.3.0dev3

### ISSUE THREAD

**Issue by rstrutt** [bokeh/bokeh#10620]
Looks like a typo somewhere - just spinning-up any simple example in 2.3.0dev3 you see this in the console (one with a hyphen, one without);

![image](https://user-images.githubusercontent.com/7271339/97623795-8fcd9500-19fc-11eb-88e6-d2e96e1fea62.png)

**Comment by bryevdv** [comment]
This was already fixed in main
