### ISSUE TITLE
[BUG]  Missing cursor snap for crosshair and points

### ISSUE THREAD

**Issue by mrx23dot** [bokeh/bokeh#10636]
## ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python 3.6.7
Win7 x64
bokeh==2.2.3

#### Description of expected behavior and the observed behavior
 When I move my cursor over a point, the hover appears with the value, but the value changes as I move my mouse slightly over the point.

 It should snap to the point and display it's exact value (from the given input array).

 There isn't any other way to precisely read out the underlying value. (don't want to zoom in infinitely)

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.plotting import figure
from bokeh.embed import components

fig = figure(plot_width=800, plot_height=200, title= titleIn+" [%d]" % scale, tools="pan,wheel_zoom,save,hover,crosshair,reset")
fig.line(x=[1,2], y=[1,2], line_width=2)
fig.circle(x=[1,2], y=[1,2], line_color='red', size=8)
script_ocf_insert, div_ocf_insert = components(fig)
#display in html

```
#### Screenshots or screencasts of the bug in action
![no_snap](https://user-images.githubusercontent.com/4163396/98172911-19440200-1eea-11eb-9d5b-ff1ccfc80fda.png)

**Comment by bryevdv** [comment]
@mrx23dot the default tooltips specify the special fields `$x` and `$y` which configure display of data-space *coordinates*, i.e. the position under the mouse. If you want to show the coordinates of the glyph, that is described in detail in the docs:

https://docs.bokeh.org/en/dev/docs/user_guide/tools.html#hovertool

For any further usage/support questions please use the community discourse, not the issue tracker: https://discourse.bokeh.org

**Comment by mrx23dot** [comment]
I figured it out
@x instead of &x
