### ISSUE TITLE
[BUG] 2.3.0dev5 - Using a widget as a parameter in its own js callback throws 'Maximum call stack size exceeded' on JS side

### ISSUE THREAD

**Issue by rstrutt** [bokeh/bokeh#10643]
#### ALL software version info 
Bokeh 2.3.0dev5
Chrome Version 79.0.3945.79 (Official Build) (64-bit)
Windows 7 Pro SP1

#### Description of expected behavior and the observed behavior
If you add a widget as a parameter in its own JavaScript callback, the page will not render and a 'Maximum call stack size exceeded' error is thrown on the JavaScript side.

Expected behavior is that that the page should render as there is nothing special about giving the JavaScript side a reference to the bk widget itself.

The test case below works OK in 2.3.0dev3 but fails in 2.3.0dev5.

#### Complete, minimal, self-contained example code that reproduces the issue

```
doc = curdoc()

# A Select with a js callback.  Note that the parameter to the callback is the widget itself.
select = Select(title='Select', options=['A', 'B', 'C'])
js_callback = CustomJS(args=dict(param=select), code="console.log('select callback: '+param)")
select.js_on_change('value', js_callback)

# ...in a column
doc_root = column(children=[select])

# Add our column as the doc root, and return
doc.add_root(doc_root)
```

#### Stack traceback and/or browser JavaScript console output

![image](https://user-images.githubusercontent.com/7271339/98406331-c5493280-203b-11eb-9762-a8732d9801e6.png)

**Comment by bryevdv** [comment]
Thanks for the complete MRE @rstrutt

**Comment by rstrutt** [comment]
No problem - glad to help!

**Comment by rstrutt** [comment]
Awesome turnaround, chaps. Thanks.
