### ISSUE TITLE
support selection/hover highlighting for annotations

### ISSUE THREAD

**Issue by 23pointsNorth** [bokeh/bokeh#10644]
The Whisker annotation module does not support any selection option. 
This results in non-standard views when data points, containing whiskers, are selected. See image below. 
Expected behaviour: being bale to specify nonselection_alpha/line_alpha, nonselection_color similar to cirlces, lines. 

bokeh: 2.2.3
python 3.7
ubuntu, docker

Image -- observe selected points bottom right, selected cluster of 3 points.:
![wh](https://user-images.githubusercontent.com/3803951/98408707-892cc680-2069-11eb-9867-ad94ead31938.png)

**Comment by mattpap** [comment]
We will need to implement composite glyphs and turn `Whisker` annotation into such glyph, to support all the features.

**Comment by bryevdv** [comment]
This will definitely require some planning. I would prefer if we can keep it so that annotations themselves don't directly participate in hit-testing, but rather afford some way to delegate highlighting status to some some other actual Glyph.

**Comment by bryevdv** [comment]
Some further questions to answer:

* How do we want to express linking of annotations to glyphs at the model level? e.g. 
  * Is it just a look connection by both renderers being configured on the same `LegendItem`?
  * Or do we want to actually have glyphs be able to specify "linked" annotations directly (and then legends delegate) to glyphs for any linked annotations to change?
* What does the convenience / user API look like for linking glyphs and annotations?
  * additional params to glyph methods?
  * free functions for setting up linkages?
* Annotations do not currently have a muted state
  * adding muted props to annotations seems like it might be alot of work
  * could just completely turn off annotations (set `.visible = False`) for both muted and hidden glyph states

**Comment by mattpap** [comment]
Closing in favour of discussion https://github.com/bokeh/bokeh/discussions/12487.
