### ISSUE TITLE
[BUG] PNG Export on macOS High density display crops image

### ISSUE THREAD

**Issue by cjw85** [bokeh/bokeh#10652]
I'm seeing the recurrence of an issue that was apparently fixed in #9639

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.11
Python 3.6
Jupyterlab 2.2.8
macOS 10.15.7
Chrome 86.0.4240.183

#### Description of expected behavior and the observed behavior
When pressing the floppy-disk icon in the bokeh toolbox of a plot, the exported image is cropped and does not display the whole plot.

#### Complete, minimal, self-contained example code that reproduces the issue
Taking some code from bokeh help pages, the details of the plot are not relevant.

```
import bokeh
print(bokeh.__version__)
from bokeh.plotting import output_notebook
output_notebook()

from bokeh.plotting import figure, show
from bokeh.sampledata.iris import flowers

colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'

p.circle(flowers["petal_length"], flowers["petal_width"],
         color=colors, fill_alpha=0.2, size=10)

show(p)
```

#### Screenshots or screencasts of the bug in action
Browser screenshot:
![Browser screenshot](https://user-images.githubusercontent.com/3592009/98555301-b069da80-2299-11eb-9d13-753e3aaa3ff7.png)

Exported image:
![bokeh_plot](https://user-images.githubusercontent.com/3592009/98555456-de4f1f00-2299-11eb-9e69-1d961ca124bc.png)

**Comment by mattpap** [comment]
This was fixed in bokeh 2.2 (issue #10249).
