### ISSUE TITLE
Surface Repo Examples in Docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10663]
Over the years it has often been the case that the answer to many user support questions is 

> Here is an example in the repo that show how to do that...

However,  the repo examples have no visibility in the main docs site, and many users simply do not know to look in GitHub for example code to reference, so we continually have to provide this answer. 

I propose to create a sphinx extension that can generate an index for examples inside the main documentation. This would help make the examples more discoverable, and in case we still have to provide this answer in support forums, it would allow us to link to somewhere in the docs, rather than in the repo.  (Linking in to the docs is better because docs can automatically maintain versioned links to the appropriate tags in the repo, whereas a bare repo link in a forum answer is forever stuck at one version forever)

I think this can proceed in steps:

* Start with a simple list of filenames that link to the repo (versioned to the correct repo tag)
* Add support for parsing a short decscription out a docstring or initial comment in an example to include in the index
* Add support for automatically cross referencing examples in the reference guide (could be based on explicit keyword or by introspecting the APIs used in an example)

### Gallery

I don't personally think this can/should replace the gallery. We have vastly more examples than there are things in the gallery, and I expect this will always be the case. There are technical reasons some examples don't play well with our gallery extension, and being in the gallery means someone has to manually create a useful thumbnail, i.e. the gallery needs to be curated. I would like the example index to be a complete automated reference. 

---

So the first question is where should this live inside the current docs structure?

cc @hyles-lineata @pavithraes @tcmetzger

**Comment by tcmetzger** [comment]
Another gallery-related idea: How about we create a new page called "Examples" that is displayed in the docs menu where "Gallery" currently is. This new examples-page would be a mini-landingpage and contain two subpages: One is the Gallery page as it is, the second sub page is an overview over the examples in the repo. This way the gallery stays and is still called gallery, while the examples are going to be very easy to find.

**Comment by bryevdv** [comment]
This we started / mostly done with the user guide, examples, and gallery refactor for 3.0
