### ISSUE TITLE
[BUG] Warnings about integrity checks when using CDN resources with extension

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#10668]
It seems like this bit of the js_resources template code https://github.com/bokeh/bokeh/blob/b56543346bad8cdabe99960e63133619feaafbb7/bokeh/core/_templates/js_resources.html#L17

assumes that both bokeh.js and all extensions (which are also provided as `js_files`) will have existing hashes. This is not (necessarily) the case so users end up seeing these warnings when using CDN resources: 

>Error parsing 'integrity' attribute ('sha384-'). The digest must be a valid, base64-encoded value.

It's only a warning so not critical but still would be nice to fix. The simplest fixes are:

- Make the template check more strict
- segregate BokehJS js files from external / extension js files in rendering

I think improving the templating code is probably the easiest fix. In the long term we could consider publishing hashes for extensions.

**Comment by bryevdv** [comment]
@philippjfr Did you want to submit a fix for 2.3?

**Comment by philippjfr** [comment]
Will do.
