### ISSUE TITLE
[BUG] Webgl perf regressions in branch-2.3

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10666]
See https://github.com/bokeh/bokeh/pull/10655 for details

**Comment by bryevdv** [comment]
@mattpap just double checking, did we agree to move this to `next` at the last meeting? I would say current performance is better than the linked comment but still noticeably worse than 2.2.3

**Comment by mattpap** [comment]
It was accidentally moved. I already have a fix, so a PR will follow later today or tomorrow.
