### ISSUE TITLE
[FEATURE]Allow naming (title) of Tools

### ISSUE THREAD

**Issue by fearcon-eap** [bokeh/bokeh#10662]
I'm sorry if this already possible, I could not find a way to achieve the presented behaviour.

**Is your feature request related to a problem? Please describe.**
When adding multiple tools of the same type (e.g. multiple Hovertools) it is impossible for the user to distinguish which of the hover tools he is (de-)activating in the toolbar as the tools get a generic name describing the type of the tool.
![image](https://user-images.githubusercontent.com/57448034/98838082-12664380-2444-11eb-9cf6-c25e432ec81d.png)

**Describe the solution you'd like**
I would like to be able to name the tool when creating it. Something in the style of
```
HoverTool(
        tooltips=[],
        formatters={},
        title = 'Hover Average'
)
```
In addition to having access to this during creation it would be good to be able to edit it after creation,
```
ht = HoverTool(...)
ht.title = "Hover Average"
```

![image](https://user-images.githubusercontent.com/57448034/98838517-acc68700-2444-11eb-97c7-33b601ba0eb8.png)

**Comment by bryevdv** [comment]
@mattpap this seems fairly straightforward and useful, and it also seems compatible with any future work that might consolidate hover tools into a single collapsible menu. So I am tentatively marking as `feature` (and GFI) but please comment or re-triage if you disagree. 

I am not sure `title` is the best property name here, maybe `description` might be better. We could also consider using existing `name` if it is provided (but then it's not possible to provide a name without also changing the display, so maybe not)

**Comment by mytan310** [comment]
Hi, is anyone working on it? If not, I am interested and can complete it by the end of this month!

**Comment by bryevdv** [comment]
@mytan310 Please feel free to submit a PR to get things started
