### ISSUE TITLE
[BUG] MouseWheel events not suppressed when WheelZoomTool active

### ISSUE THREAD

**Issue by nitrocalcite** [bokeh/bokeh#10669]
This could be a documentation error.  The documentation on [MouseWheel](https://docs.bokeh.org/en/latest/docs/reference/events.html) events says:

> By default, Bokeh plots do not prevent default scroll events unless a WheelZoomTool or WheelPanTool is active. This may change in future releases.

This would seem to imply that if the WheelZoomTool is active, the MouseWheel event callbacks would be disabled.  However, when I have the WheelZoomTool active and I use the scroll wheel, the callback is still triggered.  Additionally, it's not clear to me how to change this "default" behavior.

Here's a MRE:

```
from bokeh.plotting import figure
from bokeh.events import MouseWheel
import panel as pn

f = figure()
f.line([0, 1], [0, 1])
f.on_event(MouseWheel, lambda evt: print(evt.x, evt.y, evt.delta, evt))
pn.pane.Bokeh(f).show()
```
I'm getting the event information printed in the console when I use the scroll wheel whether or not I activate the WheelZoomTool.

This is on:
`bokeh 2.2.3`
`panel 0.9.7`
Windows 10
Chrome & Firefox

Can someone point me to the documentation on how to change this "default" behavior?  Alternatively, is there a way to tell whether a given tool is active Python-side so I can suppress these events myself?  Though I'm new to Bokeh, I wasn't able to find this in the docs.

Thanks in advance!

**Comment by IuryPiva** [comment]
Hey @nitrocalcite, sorry for the late reply. I think this is just a documentation issue. And to check the events currently subscribed you can look at [subscribed_events](https://docs.bokeh.org/en/latest/docs/reference/model.html?highlight=subscribed_events#bokeh.model.Model.subscribed_events)

**Comment by mattpap** [comment]
>> By default, Bokeh plots do not prevent default scroll events unless a WheelZoomTool or WheelPanTool is active. This may change in future releases.

> This would seem to imply that if the WheelZoomTool is active, the MouseWheel event callbacks would be disabled. 
> `f.on_event(MouseWheel, lambda evt: print(evt.x, evt.y, evt.delta, evt))`

The documentation talks about the native DOM (mouse) `wheel` event, which has its default [behavior](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#preventing_default_behavior), which is scrolling of the viewport or the containing block, suppressed when respective tools are active. `MouseWheel` refers to bokeh's UI event. By design, bokeh's UI events are not suppressed when tools using the same gestures are active.
