### ISSUE TITLE
Unintended (?) changes to package(-lock).json

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10673]
This https://github.com/bokeh/bokeh/commit/e2ec89cc37dac0ea29ed3cd34be0a97deab7e834 commit rewrote `package.json` and upgraded `package-lock.json` to version 2, which requires `npm@7`. For every user that uses `npm<7`, npm will revert it to version 1, causing confusion. `npm@7` comes by default only with nodejs 15 and updating npm doesn't automatically update to higher major version (one has to use `npm install -g npm@7`). I'm guessing this is the result of conda-forge having most recent versions of nodejs available.

The version of nodejs/npm for building bokehjs needs to be more strictly controlled, especially non-LTS versions should not be used. We can upgrade to `npm@7` and the new `package-lock.json` format, but this needs to be done across the board. In particular the minimum supported version needs to be changed.

**Comment by bryevdv** [comment]
Agree all the env files in the `ci` dir as well as the top level env file should be put in sync or node version
