### ISSUE TITLE
examples/webgl/marker_compare doesn't actually use webgl

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10676]
It uses `p.scatter(marker=marker)` which doesn't support webgl. Trivial solution is to replace it with `gettattr(p, marker)`. However, it would be better if scatter and individual marker glyph functions used the same rendering code paths.

**Comment by bryevdv** [comment]
dupe of #10413?

**Comment by mattpap** [comment]
Duplicate indeed.
