### ISSUE TITLE
[BUG] ScientificFormatter shows 0 as 0.000e+00

### ISSUE THREAD

**Issue by comatrion** [bokeh/bokeh#10675]
#### Software version info
bokeh 2.1.1
python 3.7
chrome  78.0.3904.97 (Official Build) (64-bit)
macOS 10.14.6 Mojave

#### Description of expected behavior and the observed behavior
Context: 
A table with a column of floats including 0, formatted with ScientificFormatter, precision set to 3, other parameters defaulted.

Expect: 
That 0 would be rendered as 0.

Observed:
Rendered as 0.000e+00 per configured precision (default precision gives 0.0000000000e+00).

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.models.widgets import DataTable, ScientificFormatter, TableColumn
from bokeh.models import ColumnDataSource
from bokeh.plotting import show

table = DataTable(
    source=ColumnDataSource(dict(x=[1e-8, 1e-4, 1e-2, 1, 100, 10000, 1000000, 0])),
    columns=[
        TableColumn(
            field='x',
            title='X',
            formatter=ScientificFormatter(precision=3),
        ),
    ],
    editable=True,
)

show(table)
```

#### Screenshots

<img width="619" alt="Screenshot 2020-11-13 at 14 07 25" src="https://user-images.githubusercontent.com/31922007/99081251-6dba4200-25ba-11eb-8dc7-01a3d6de81c4.png">

**Comment by mattpap** [comment]
Looking at the implementation, there needs to be a special case for 0.
