### ISSUE TITLE
Move Bokeh docs to the latest version of pydata-sphinx-theme

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh#10685]
[pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html) recently added the feature to show multiple toc levels (https://github.com/pandas-dev/pydata-sphinx-theme/pull/256), which can be helpful for Bokeh docs.

**Comment by tcmetzger** [comment]
This would be a great feature to have, in my opinion!
