### ISSUE TITLE
[BUG] column and row destroy datatable column width property in 2.2.3

### ISSUE THREAD

**Issue by EdTheEagle** [bokeh/bokeh#10689]
Running on WIN10, python 3.6.2, bokeh 2.2.3, Chrome, Jupyter notebook

Currently moving from 1.3.4 to 2.2.3. Encountered this bug, where the column width settings are lost when the datatable is instered in a row or column layout. To illustrate the behavior:

```
from bokeh.io import show, output_notebook
from bokeh.layouts import column, row
from bokeh.models import ColumnDataSource, TableColumn, DataTable
import pandas as pd
output_notebook()
cWidths = [200,20,20,20,400]
columns = [TableColumn(field=i,width=cWidths[j], title=i ) for j,i in enumerate(['strategy','pos','order','data','status'])]  #if i != 'colors' else HTMLTemplateFormatter(template=colorCol))
status_src = ColumnDataSource(pd.DataFrame(columns=['strategy','pos','order','data','status']))

statusTable = DataTable(source=status_src, columns=columns, width=720, editable=False,index_position=None)

show(statusTable) # column widths are as expected
show(column(statusTable)) # column widths are lost
show(row(statusTable)) # column widths are lost

```

**Comment by bryevdv** [comment]
@EdTheEagle can you please make the code snipped above *complete* so that is may be easily copy and pasted for testing?

@mattpap thoughts here? the `width` docs state:

> The width ***or maximum width (depending on data table’s configuration)*** in pixels of this column.

So can can believe that current practice might require a more explicit `width_policy` or `sizing_mode` somewhere (in which case this can be closed) but let me know what you think.

**Comment by EdTheEagle** [comment]
I've added the imports in the code above. Played around with width_policy and sizing_mode, but no success unfortunately

**Comment by bryevdv** [comment]
Based on local testing, this was resolved at some point (all three cases in the code above display identically for me)
