### ISSUE TITLE
[BUG] bokeh app does not show in jupyter notebook

### ISSUE THREAD

**Issue by EdTheEagle** [bokeh/bokeh#10691]
Bokeh 2.2.3, WIN10, python 3.6.2. Chrome, jupyter-notebook

For bokeh app development, I used to show an interactive bokeh app with (Bokeh version 1.3.4):

`show(Application(FunctionHandler(bkApp)))`

And it would pop up and all the interactions would work. This does not work in the new version, no errors, just nothing.

**Comment by bryevdv** [comment]
@EdTheEagle I am unable to reproduce any any problem with Bokeh 2.2.3 and Python 3.6.2 on Win 10 / Crome with the notebook server embed example in the repo:

<img width="791" alt="Screen Shot 2020-11-16 at 10 10 37 AM" src="https://user-images.githubusercontent.com/1078448/99291074-1a333880-27f4-11eb-83cb-7cbc9ab56577.png">


I except there is some local issue with your system but I would ask to continue the discussion for now on the project discourse until we can determine for certain that there is anything on this end that can or should be done:

https://discourse.bokeh.org/

As always, it is strongly advised to bring a complete reproducing example of your own to provide for testing.
