### ISSUE TITLE
[FEATURE] Allow widget updates during callback function execution like before wihtout add_next_tick_callback function.

### ISSUE THREAD

**Issue by EdTheEagle** [bokeh/bokeh#10690]
In  v1.3.4, it was possible to change the appearance of the bokeh app during the execution of a callback, even before the callback returned. This made coding really easy, especially when dealing with button interactions which execute lengthy calculations.

My usual code format would be like below, where the button label was changed while the callback was still running:

```
def buttonAction():
    if Button_B.label == 'someState':
        Button_B.label = 'processing'
        Button_B.button_type = 'warning'
   
        # some code that takes time to process

        Button_B.label = 'done'
        Button_B.button_type = 'primary'    
    else:
        Button_B.label = 'someState'
        Button_B.button_type = 'success'
```

This worked like a charm and the widget updates I could do was not restricted to button appearances, but I could also update ColumnDataSources for example.

I am aware of the add_next_tick_callback function, but that will lead to a much larger codebase in more complex interactions.

The odd thing is that with a clean install of  1.3.4, the above does not work and only updates the widgets after the callback returns.

**Comment by bryevdv** [comment]
This was changed a long time ago and is not something we can go back to, sending updates on every property change is both inefficient and makes system state hard to reason about. Now that Bokeh server users native co-routines it might be possible to afford explicit synchronization points via an `await` statement, but there is already an issue for that https://github.com/bokeh/bokeh/issues/9669 so I will close this one.
