### ISSUE TITLE
[BUG] TextAreaInput value_input no change event detected

### ISSUE THREAD

**Issue by comatrion** [bokeh/bokeh#10702]
#### Software version info
bokeh 2.1.1
python 3.7
chrome  78.0.3904.97 (Official Build) (64-bit)
macOS 10.14.6 Mojave

#### Description of expected behavior and the observed behavior
Context: 
A `TextAreaInput` widget and a `Div` which is updated for changes on both `value_input` and `value`.

Expect: 
1. That the `Div` text is updated on each keystroke, as described here https://docs.bokeh.org/en/latest/docs/reference/models/widgets.inputs.html?highlight=textareainput#bokeh.models.widgets.inputs.TextAreaInput.value_input
2. That the `Div` text is updated when you enter text and the click outside the area.

Observed:
1. No change on each keystroke.
2. OK

#### Complete, minimal, self-contained example code that reproduces the issue

File `main.py`
```
from bokeh.models.widgets import TextAreaInput, Div
from bokeh.layouts import column
from bokeh.io import curdoc

doc = curdoc()

tai = TextAreaInput(rows=5, value="", placeholder="Enter text")
div = Div(text="Nothing received here")

def callback(attr, old, new):
    div.text = f"Callback {attr}, {old}, {new}"
    
tai.on_change("value_input", callback)
tai.on_change("value", callback)

doc.add_root(column([tai, div]))
```
then from within directory containing `main.py`
```
bokeh serve . --show
```

#### Screenshots

<img width="349" alt="Screenshot 2020-11-18 at 12 59 17" src="https://user-images.githubusercontent.com/31922007/99533647-1d6a2800-299e-11eb-853e-0630e6c838a1.png">

**Comment by bryevdv** [comment]
Confirmed in 2.2.3 and current `branch-2.3` Not sure if this is a regression or perhaps it has never worked properly
