### ISSUE TITLE
[BUG] ModuleNotFound error for every sub-module I try to import

### ISSUE THREAD

**Issue by amoh-godwin** [bokeh/bokeh#10717]
I seem to be getting a module not found error for everything that I import in bokeh.
So I decided to do the quickstart example located here: https://docs.bokeh.org/en/latest/docs/user_guide/quickstart.html#userguide-quickstart

```
from bokeh.plotting import figure, output_file, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend_label="Temp.", line_width=2)

# show the results
show(p)
```

I actually copied and pasted the code.

My specs:
python: 3.7.6 (Anaconda)
bokeh: both 2.2.3, and 2.3.0.dev5
OS: Windows 10

**I am not running it in a notebook but rather in CMD.exe.**

**_Traceback (most recent call last):
  File "bokeh.py", line 1, in <module>
    from bokeh.plotting import figure, output_file, show
  File "H:\CS\studies\python\scipy\bokeh.py", line 1, in <module>
    from bokeh.plotting import figure, output_file, show
ModuleNotFoundError: No module named 'bokeh.plotting'; 'bokeh' is not a package_**

I have checked the bokeh package folder myself, everything is there.

![bokeh_error](https://user-images.githubusercontent.com/18188576/99910578-b8d50300-2ce6-11eb-8402-9809e3a56c19.jpg)

Let me repeat. This error is shown for anything that I try to import
> `from bokeh.io import output_file`
> `from bokeh.sampledata.stocks import AAPL`

error everywhere.

**Comment by xavArtley** [comment]
Try to name your file differently than bokeh.py ?

**Comment by amoh-godwin** [comment]
@xavArtley Thank you very, very much. Works brilliantly, like magic.

**Comment by bryevdv** [comment]
@amoh-godwin it is not magic -- Python has a defined search path order for importing modules and by naming your module `bokeh.py` you shadowed the installed bokeh package. That's just how Python works. 

In the future, if you are not sure something is a bug, please post first on the community discourse for support: https://discourse.bokeh.org/

**Comment by amoh-godwin** [comment]
@bryevdv Actually I immediately remembered the search path thing when he told me the solution. I was just trying to be funny.
