### ISSUE TITLE
[FEATURE] Add continuous_update to sliders

### ISSUE THREAD

**Issue by Hoxbro** [bokeh/bokeh#10715]
**Is your feature request related to a problem? Please describe.**
I usually have my sliders connected to long running functions, which for example needs to open files, do some data analysis and then plot the data. The real-time feedback therefore becomes more of a burden than being helpful.

Right now I need to use the `value_throttled` instead of `value` for every callback. My suggestion would be that a `continuous_update` option is when creating the slider like

``` python
Slider(start=0.1, end=10, value=1, step=.1, title="Amplitude", continuous_update=False)
```
With this options I only have to choose once on how the sliders should react for the rest of the code. At the same time it would also be easier to change the slider between updating continues or not. [Ipywidgets](https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html#continuous_update) is using this method, which will also make it easier for people coming from ipywidgets.

**Describe the solution you'd like**
Add `continuous_update` option when creating the slider.

**Additional context**
I have trying to implement the feature in my [own fork](https://github.com/Hoxbro/bokeh/pull/1/files), but as I have literately no experience in JavaScript or TypeScript, I don't know if it is the right way to implement it.  At the same time I did not want to fill your PR with this feature if it was doomed from the start.

**Comment by bryevdv** [comment]
@Hoxbro I very much doubt we can do this, for a couple of reasons:

* It's duplicative of existing features, which is never good from a maintenance and documentation perspective. 

* The mechanism with explicit separate properties fits much better with Bokeh's event system for technical reasons.

* In ~8 years of supporting Bokeh no one has ever asked about switching between throttled and continuous updates dynamically, the effort to support that is simply not justified by (lack of) the demand. 

For that matter, we used to do things this way with a `callback_policy` and it did not work very well which prompted  the switch to the current way. I.e. this approach has already been tried and explicitly discarded. Given that, I am going to close with `noaction`.
