### ISSUE TITLE
[FEATURE] Autoformatting

### ISSUE THREAD

**Issue by kir0ul** [bokeh/bokeh#10712]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to spend time on formatting issues in a review. I think these kind of issues add no real value to the project but are still time consuming.

**Describe the solution you'd like**
I think enforcing some autoformatting tool(s) in CI would avoid these kind of issues in the future.
Ideally it would also be nice to have a [pre-commit](https://pre-commit.com/) hook.

Possible solutions:
* Python:
  * [Black](https://black.readthedocs.io/)
  * [autopep8](https://github.com/hhatto/autopep8)
  * [YAPF](https://github.com/google/yapf)
* TypeScript:
  * [Prettier](https://prettier.io/)
  * [ts-standard](https://github.com/standard/ts-standard)
  * [eslint-config-standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript)

Curious to hear what you think! :slightly_smiling_face:

**Comment by bryevdv** [comment]
I am a strong advocate of applying Black formatting throughout the Python codebase. But there has been some disagreement among the core team regarding it. However, recently we ratified a formal decision making process so we will to simply put the matter to a vote to resolve it. 

I would also very much be in favor of auto-formatting the JS side, but have no particular opinion on what tools, and would be happy to conform to any choice made there. 

What I may actually put up for formal decision is simply to designate (for the first time) official maintainer roles that would be responsible for these kinds of decisions in their respective areas, and I would propose:

* Python maintainer: Myself
* JS maintainer: @mattpap 

cc @bokeh/core

**Comment by kir0ul** [comment]
I'm also a huge fan of Black, which I apply everywhere :grin: 

Not sure which option would be best on the JS side, [popularity would suggest Prettier](https://npmcharts.com/compare/standard,prettier,ts-standard,eslint-config-standard-with-typescript?log=true), but apart from that I wouldn't know.

Also for reference in case you'd prefer to apply the autoformatting in a more incremental way, here are a few options:
* [Darker](https://github.com/akaihola/darker)
* [lint-staged](https://github.com/okonet/lint-staged)

Happy to help on this issue where possible!

**Comment by bryevdv** [comment]
Since there were no comments re: "maintainer roles" I've opened a narrower decision for just Black formatting the Python code base here: https://github.com/bokeh/bokeh/issues/9636#issuecomment-735295845

Will leave this issue open to discuss any auto-formatting for BokehJS outside that decision.

**Comment by mattpap** [comment]
> (...) what I may actually put up for formal decision is simply to designate (for the first time) official maintainer roles that would be responsible for these kinds of decisions in their respective areas, (...)

I think this is a good idea and I'm happy to proceed with this in near future.

**Comment by bryevdv** [comment]
> I think this is a good idea and I'm happy to proceed with this in near future.

👍 OK we should probably propose a new section for the "Roles" BEP in a new issue that describes what exactly the responsibilities are

**Comment by bryevdv** [comment]
I'm going to go ahead and close this discussion now that #9636 is resolved

**Comment by kir0ul** [comment]
For the record now there's also [Rome](https://rome.tools/) that is able to lint & autoformat JS/TS code.
