### ISSUE TITLE
[BUG] 404 trying to find autoload.js when running Jupyter notebook

### ISSUE THREAD

**Issue by ohmeow** [bokeh/bokeh#10723]
Running the example here: https://github.com/bokeh/bokeh/blob/2.2.3/examples/howto/server_embed/notebook_embed.ipynb returns the following Javascript error after the call to `show(...)`:

```
GET https://localhost:41731/autoload.js?bokeh-autoload-element=1002&bokeh-absolute-url=https://localhost:41731&resources=none net::ERR_CONNECTION_REFUSED
```

I am ssh'ng and into a remote machine and port forwarding from local port 9999 to 8889, so that my Jupyter notebook is accessible on my dev machine from `https://localhost:8889`.  I tried setting `notebook_url="http://localhost:8889"` but I get the same error.

OS: Ubuntu Linux 18.04
Python: 3.7

**Comment by bryevdv** [comment]
If this is a remote machine then some additional configuration will be needed. But support questions should be posed on the community Discourse, not the issue tracker

https://discourse.bokeh.org/
