### ISSUE TITLE
BOKEH_STRICT does not raise validation errors

### ISSUE THREAD

**Issue by pablo-esteban** [bokeh/bokeh#10733]
Hello,

I am plotting a rectangular grid where the axis labels are factors. If there are duplicated factors along any axis, as expected, an error should be raised. When I run my code I see:

```
ERROR:bokeh.core.validation.check:E-1019 (DUPLICATE_FACTORS): FactorRange must specify a unique list of categorical factors for an axis: duplicate factors found: 'a'
```
If I set `BOKEH_STRICT=1` I don't see any difference. I was expecting an exception being raised.

In the validation section of the documentation I found the `check_integrity` function which I hoped would raise the `DUPLICATE_FACTORS` error, but it does not. Is this a bug or expected behaviour? 

How can I detect this issue before rendering to html? How can I catch the `DUPLICATE_FACTORS` validation error?

I've tested this on Bokeh 2.2.3 and 2.1.1

Below is my code:

```python
import pandas as pd
import numpy as np

from bokeh.plotting import Figure
import bokeh.palettes as palettes
from bokeh.models import LinearColorMapper
from bokeh.transform import transform
from bokeh.resources import CDN
from bokeh.embed import file_html


index = ["a", "a"]
columns = ["b"]
N = len(index)
M = len(columns)
data = pd.DataFrame(np.random.rand(N * M).reshape(N, M), index=index, columns=columns)

ii, jj = np.meshgrid(data.columns, data.index, indexing="ij")
ii = ii.flatten()
jj = jj.flatten()
cc = [data.loc[j, i] for i, j in zip(ii, jj)]
plot_data = dict(x=ii, y=jj, colors=cc)

fig = Figure(
    x_axis_location="above",
    x_range=list(map(str, data.columns)),
    y_range=list(map(str, reversed(data.index))),
)
fig.rect(
    "x",
    "y",
    1,
    1,
    source=plot_data,
    color=transform("colors", LinearColorMapper(palette=palettes.magma(7))),
    line_color=None,
)

file_html(fig, CDN, "boom")
```

**Comment by mattpap** [comment]
Here's the offending code (since 2015):
https://github.com/bokeh/bokeh/blob/9dcbafe7a6b72d8e740ba85a1a1e0804080f6d9b/bokeh/core/validation/check.py#L128-L130

**Comment by bryevdv** [comment]
Yah we just never turned it on. I'm still not sure I want to have validation errors always unconditionally raise executions, though, so this would require a little more th

**Comment by pablo-esteban** [comment]
At least, can the `check_integrity()` return an error list or something?

**Comment by bryevdv** [comment]
Well we can't have  `check_integrity` return the error list and also potentially be the place that would raise exceptions on errors (some day), since that combination would be very muddled API. However if we want to have `check_integrity` return errors *only*, and punt the potential exception raising downstream to where `check_integrity` is called:

https://github.com/bokeh/bokeh/blob/f7538e1da3848a226edeb7f9ecf83b98e70a76df/bokeh/document/document.py#L932-L941

Then that would be reasonable. The commented code in `check_integrity` should be moved/updated to that `validate` method above, and some new tests should be added for the new `check_validate` return value as well. (I think actually all the current mocked tests for `check_validate` could be simplified to just check return values, which would also be nice to do at the same time) @pablo-esteban do you want to submit a PR for this? Speaking plainly, its not likely to be high on my priority list any time soon.

**Comment by bryevdv** [comment]
Regarding the env var, if anyone want to tackle that at the same time, I think I would recommend getting rid of `BOKEH_STRICT` and replacing with `BOKEH_VALIDATION_EXCEPTIONS` with values

* `"none"` logs errors and warnings, no exceptions (default)
* `"errors"` logs warnings, exceptions on errors
* `"full"` exceptions on errors or warnings

**Comment by pablo-esteban** [comment]
I'll do it. I just need to setup the dev environment...

**Comment by bryevdv** [comment]
@pablo-esteban awesome let us know if we can help with questions. FYI this is all pure python-side you you could probably skip all the BokehJS building parts if you really want to.

**Comment by mytan310** [comment]
@pablo-esteban Are you still planning on working on this? I can work on it if you are okay with it!

**Comment by pablo-esteban** [comment]
> @pablo-esteban Are you still planning on working on this? I can work on it if you are okay with it!

Yes, i still plan to do it.

**Comment by pablo-esteban** [comment]
> > @pablo-esteban Are you still planning on working on this? I can work on it if you are okay with it!
> 
> Yes, i still plan to do it.

I'm sorry, I won't be able to work on this.

**Comment by bryevdv** [comment]
Thank for the update, I have closed the PR

**Comment by RandyRcw** [comment]
@danie1zhang and I can work on this. We're beginners in contributing to open source repositories and this seems like a great place to start.

**Comment by bryevdv** [comment]
@RandyRcw that's great, let me know if there is anything I can do to help you get started, or questions I can answer
