### ISSUE TITLE
Creating a Bokeh plot using a numpy array of dtype('S13') returns blank canvas

### ISSUE THREAD

**Issue by gallamine** [bokeh/bokeh#1073]
I have a numpy array of dtype 'S13'. When I try and create a bokeh plot (in an IPython notebook) the plot is returned as a blank canvas. Calling the same plot with matplotlib returns the correct plot. This is very confusing. I finally had to do this to get it to plot:

```
bokeh.figure()
bokeh.scatter(data[:,1].astype(float),data[:,0].astype(float), size=4)
bokeh.show()
```

It was not at all apparent why Numpy chose D13, but it took a good deal of thought to finally diagnose the problem. I don't know if it's an actual bug, but I figure it will cause confusion for others working with Bokeh.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
