### ISSUE TITLE
[BUG] WebGL output backend not working on some Apple mobile devices

### ISSUE THREAD

**Issue by bahrikutlu** [bokeh/bokeh#10747]
https://docs.bokeh.org/en/latest/docs/user_guide/webgl.html

I am able to use this feature successfully on a PC, Iphone 11 and Iphone XR. However, the charts are not rendering on Apple Ipad devices. Specifically, I tried it on an iPad 5th gen and couple more ipads on Browserstack (ipad 6th, 7th and 8th gen). The test on 5th gen was on a real device in my hands but the other three were on Browserstack. I came across this problem on my website but was able to reproduce it on the official Bokeh page. On my personal project, all my problems went away after removing the Webgl backend setting.
Thank you.

UPDATE : This problem went away sometime between December 2020 and June 2021 with an update to Safari on IOS. Current up to date IOS version is 14.6 and the WebGL backend works properly on the official page.

**Comment by bryevdv** [comment]
I can repro this on my ipad. I doubt there is anything we can do in the immediate/short term. The longer term plan is to re-found webgl on top of ReGL which itself is more extensively platform tested than we will have the resources to achieve. If you expect your primary audience to be on mobile safari then I would say it is advised to avoid webgl at present.

**Comment by mattpap** [comment]
@bahrikutlu, can you provide basic information (per issue template) which would allow us to assess this bug (e.g. are there any console messages?).

**Comment by bahrikutlu** [comment]
@mattpap I wasn't able to get any console message since I don't have a setup to have access to console on IOS devices. As I have mentioned the bug can be reproduced on official Bokeh page that I have provided in my first message.

**Comment by ianthomas23** [comment]
To keep all interested parties informed, I have started working on a webgl rewrite and should have something to demonstrate in a few weeks time, although Christmas may interfere with this.

**Comment by bryevdv** [comment]
@ianthomas23 is there any open issue or PR we can reference this to (and ideally close this in favor of)?

**Comment by bahrikutlu** [comment]
UPDATE : This problem went away sometime between December 2020 and June 2021 with an update to Safari on IOS. Current up to date IOS version is 14.6 and the WebGL backend works properly on the official page.

**Comment by ianthomas23** [comment]
@bahrikutlu Thanks for the update, I'm glad there is no longer a problem.  I'll close this issue.
