### ISSUE TITLE
[BUG] Stamen Images Broken in Documentation in Chrome

### ISSUE THREAD

**Issue by tmorrell** [bokeh/bokeh#10744]
In https://docs.bokeh.org/en/latest/docs/reference/tile_providers.html#bokeh-tile-providers with Chrome 87.0.4280.67  the Stamen examples are broken because they use http links. This was fixed in the tile provider https://github.com/bokeh/bokeh/commit/c42199633e2a1a6a515afb1dfeaa1e2ccb0d7c34, but not in the docstring.
![Screen Shot 2020-11-30 at 4 46 20 PM](https://user-images.githubusercontent.com/10798874/100682922-0fb48b00-332c-11eb-8895-68bbc8f52aad.png)

**Comment by bryevdv** [comment]
Thanks @tmorrell would you like to submit a PR to update the URLs?
