### ISSUE TITLE
[BUG] DataTable documentation suggestions

### ISSUE THREAD

**Issue by chrisjdixon** [bokeh/bokeh#10748]
[I was confused by DataTables and their documentation](https://discourse.bokeh.org/t/printing-df-as-datatable-why-arent-columns-adjusting-in-width/6824) and couldn't work out which setting made columns automatically adjust their width. The ever helpful @hyles-lineata kindly pointed me to [autosize_mode](https://docs.bokeh.org/en/latest/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.DataTable.autosize_mode).

@hyles-lineata has asked for my suggestions on documentation before so hopefully I can help explain how documentation might've been a little clearer for a layman like me. Here are the settings that I thought might've affected column widths, how I interpreted them, and my tentative suggestions:

- [fit_columns](https://docs.bokeh.org/en/latest/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.DataTable.fit_columns): I still don't understand what this does. It seems to only make column widths consistent. If it's doing something could the explanation be made clearer?
- [sizing_mode](https://docs.bokeh.org/en/latest/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.DataTable.sizing_mode): would've been nice if this stated 'How the component **(DataTable)** should size itself' or similar, purely to avoid confusion with settings for other things
- under [TableColumn: width](https://docs.bokeh.org/en/latest/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.TableColumn.width): column widths don't seem to respond to this at all, at least with the below code. Is this an obsolete setting that can be dropped or have I misunderstood something?

```
import pandas as pd, numpy as np, random, string
from bokeh.models import ColumnDataSource, DataTable, TableColumn
from bokeh.plotting import show

df = pd.DataFrame(np.random.randint(0,100,size=(100, 12)), columns=[(random.randint(1,30) * random.choice(string.ascii_uppercase)) for col in range(12)])

def bokehprint(x):
    show(DataTable(columns= [TableColumn(field=c, title=c, width=len(c)) for c in x.columns], fit_columns = True, sizing_mode = 'stretch_both', source=ColumnDataSource(x)))

bokehprint(df)
```

I've probably misunderstood a few things here, so please feel free to disregard any / all of this. Thanks again for all your help

**Comment by hyles-lineata** [comment]
PR is in to make the `fit_columns` docstring a little clearer. 

Re the other two points:
- `sizing_mode` is actually a param for a LayoutDOM object. DataTable is just inheriting it, and our auto-generated docs includes it in the DataTable reference. This is why the phrasing is so generic: the docstring is written at the parent class level, and applies to other component types also.  Unfortunately, no quick fix here.
- TableColumn widths can be overriden by DataTable width settings (as reflected in the newer `autosize` param docstrings). I believe what's happening in your example is that you're setting TableColumn widths, but then overriding them with `fit_columns=True`.  I did some testing with this one, and found that TableColumn widths worked as expected; if you have a counterexample that doesn't use DataTable column-width-fitting settings, though, of course let us know on the Discourse.

Thanks for great docs feedback, @chrisjdixon !
