### ISSUE TITLE
[BUG] Plaintext copy-pasted from DataTable has a different order

### ISSUE THREAD

**Issue by lyijin** [bokeh/bokeh#10749]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.2.3
Python 3.9.1rc
Debian sid
Vivaldi/Chrome, same behaviour on both browsers

#### Description of expected behavior and the observed behavior
I have an app that generates a DataTable based on lasso-ed points on the main plot. I've always felt that selecting text from DataTable was a bit cumbersome, as it was hard to select-all, but to my absolute surprise, I found that there was a checkbox method to select rows, i.e.

``DataTable(..., selectable='checkbox')``

This solved my need for a quick way to select-all (by clicking the checkbox on the header row), but selecting the rows + CTRL--C + CTRL-V elsewhere produces text that is ordered in an unexpected fashion. I hope these pictures suffice to illustrate the expected/observed behaviour:

![image](https://user-images.githubusercontent.com/9586164/100841311-3a891580-34cb-11eb-86c4-caac8c686fcb.png)
Instead of being sorted numerically, the row indexes are sorted character... ally?

![image](https://user-images.githubusercontent.com/9586164/100841489-7d4aed80-34cb-11eb-9c59-cd5ddee91f69.png)
This is harder to explain. I sorted the same table by "Selected peptide", so it's now ordered alphabetically by peptide sequence instead of numerically by index number. Copy-pasting it out shows an order that, I think, suffers from the same problem as the previous one. The third row (with index 16) is located at line 13 of the pasted text output, which is the same as the previous table. Previously, the third row (index 2), is also located at line 13 of the output.

#### Complete, minimal, self-contained example code that reproduces the issue
Uh, it's a bit of a spaghetti... if you cannot reproduce the same behaviour on a typical DataTable, let me know and I'll try to condense my code into something minimal/shareable.

Thanks!

**Comment by bryevdv** [comment]
@lyijin we do really need a minimal reproducer to be able to run and investigate.

**Comment by lyijin** [comment]
Sure thing, sorry for being lazy initially.

I plagiarised the example code provided by Bokeh for DataTables, and modified the "Downloads" column to a modulus to make it sortable in a predictable manner.
https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html

```
from datetime import date

from bokeh.io import save
from bokeh.models import ColumnDataSource, DataTable, DateFormatter, TableColumn

data = dict(
        dates=[date(2014, 3, i+1) for i in range(22)],
        downloads=[i % 10 for i in range(22)],
    )
source = ColumnDataSource(data)

columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, selectable='checkbox', width=400, height=600)

save(data_table, filename='datatable.html')
```

This screenie shows copy-pasting from the default order. Again, the indices aren't sorted by numeric order.
![image](https://user-images.githubusercontent.com/9586164/101228021-02155180-36ee-11eb-9408-2bf36c058a8e.png)

This screenie shows copy-pasting when sorted by "Downloads". Same logic as what I mentioned previously, the third row in the original table (index 20, 2014-3-21, 0) is again at row 20.
![image](https://user-images.githubusercontent.com/9586164/101228031-10636d80-36ee-11eb-9385-d89292c4f0a1.png)

Sidenote: My initial table had no date data in it but the Bokeh one did. Erm, I think the DateFormatter() might be faulty as well, it shows zero epoch instead of the 2014 dates... but copy-pasting the date contents worked. Maybe the JS library for the table is at fault here?

This can also be seen on the bokeh widgets website too!
![image](https://user-images.githubusercontent.com/9586164/101228325-4ce39900-36ef-11eb-88c1-dbcf647b373a.png)

**Comment by bryevdv** [comment]
cc @mattpap ^^^ possibly another datetime precision loss codepath?

**Comment by bryevdv** [comment]
In any case I can repro the copy-paste issue with the longer example table sorted by downloads. We do actually have CI tests to check copy-past order for data table but evidently they don't capture whatever is going on here.
