### ISSUE TITLE
[BUG] Hover indices broken 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10754]
ref: https://docs.bokeh.org/en/dev/docs/user_guide/interaction/callbacks.html#customjs-for-specialized-events

`cb_data.index.indices` is now undefined, I would regard this is a showstopper (I discovered this because I have current support questions about using this callback on hover feature)

We should not break this without a deprecation since it is clear that users do rely on it.

**Comment by mattpap** [comment]
Thanks to documentation jumping around I discovered a regression in https://docs.bokeh.org/en/dev/docs/user_guide/interaction/callbacks.html#customjs-for-ranges.

**Comment by mattpap** [comment]
I guess I will fix both at the same time.
