### ISSUE TITLE
[FEATURE] Add format options like pre- and poststing to NumeralTickFormatter

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#10763]
**software version info (bokeh, python)**

Python: 3.6.10
Bokeh: 2.2.3

**Idea and solution**
I lately tried to call the NumeralTickFormatter on an axis and then I wanted to add a postfix to the generated string. I was not able to do it but in the documentation it is mentioned that bokeh uses http://numbrojs.com which already has this options.

I thought it would be cool and helpful to extend the current NumeralTickFormatter to take more optional keyword arguments and then pass them to the ```numbro.format()``` function.

**Comment by bryevdv** [comment]
@mosc9575 you can already add whatever you want after a formatted field in the string , e.g. 
```
"@{foo}-some-postfix"
```
This is simpler and more general (works with any formatter) There is no need to make the formatter syntax (which is already substantially complicated) even more complicated.
