### ISSUE TITLE
[FEATURE] Inverse legend selection (Hide/Show)

### ISSUE THREAD

**Issue by Vel-San** [bokeh/bokeh#10771]
There is currently a hide/show legends drawn on graphs, but i am not really sure if there is 'Inverted' selection. Once we select 1 legend, ALL other legends are hidden automatically, instead of hiding the selected one.

Same goes for selecting 2 legends, 3 etc.. 

**Describe alternatives you've considered**
To be fair, there is no alterantive for me. I had to work with the current funtionality 😄 

**Additional context**
I know currently 'Legends' aren't given priority (Been tracking several issues related to legends) but this would be a nice feature (if it isn't added yet, i looked the docs and couldn't find it)

**Comment by bryevdv** [comment]
I didn't realize there is already an issue for this: https://github.com/bokeh/bokeh/issues/8841 so accordingly I will close this as a dupe. 

@Vel-San please feel free to chime in on the other issue. What it comes does to is that once you actually start getting in the weeds there are actually some hard to resolve (or at least as-yet-unresolved) questions about discoverable UX, what to do with multiple selections, etc.
