### ISSUE TITLE
Svg element not showing when saving plot

### ISSUE THREAD

**Issue by znstrider** [bokeh/bokeh#10773]
I am trying to save a plot that includes svg elements.

When I specify the relative svg path, the svg element will show on the plot, but not in the png that I save.
When I specify the absolute svg path, the svg element will not show on the plot, but do so in the png when I save it.

The minimal example would be:

```
from bokeh.plotting import figure
from bokeh.io.export import get_screenshot_as_png
from bokeh.io import show

image_url = …

p = figure(x_range=(0,1), y_range=(0,1))
p.image_url([img_url], x=0.5, y=0.5, w=1, h=1, anchor=‘center’)
show( p )

img = get_screenshot_as_png(p)
img.save(‘img.png’)

#same with export_png(p, png.png)”""
```

This is happening both when working in a notebook or using a server app and with bokeh versions 2.0.0 and 2.2.3.

Is there any way to have the svg shown both when viewing the app and when saving the plot as an image?
Does this work for pngs?

**Comment by bryevdv** [comment]
There are two main obstacles to having VG output work `image_url`:

* Unlike every other glyph (except map tiles), `image_url` has to asynchronously load remote resources over the network. the standard render path takes care to make sure to re-render after the load finishes, but I am not offhand sure that the SVG render path does that at all (i.e. it might be converting to SVG before the image request even finishes)

* `image_url` also does not use the basic HTML canvas APIs that we ported from `canvas2svg` I believe here are ways to embed bitmapped raster images like PNGs inside SVG content, but we'd have to special-case that and AFAIK it's never been done. 

cc @mattpap for thoughts as well.

**Comment by mattpap** [comment]
`ImageURL` glyph works with SVGs, as demonstrated in:
https://github.com/bokeh/bokeh/blob/2af103f86050fff34a5ba562803c24821b510d15/bokehjs/test/integration/regressions.ts#L75-L101
Though this uses in-line images. I will need at least JS console output and preferably a complete example to resolve this.

**Comment by znstrider** [comment]
As I hopefully worded more clearly now, the svg specified for the image_url _**does**_ show on the plot when provided the relative path, ie "project_name/static/image.svg" but it disappears when the image is saved.

But strangely it does show in the saved png when provided "/Users/user_name/project_name/static/image.svg" but not on the plot output.

Is this the JS console output you are asking for? (I have no clue about that)

> NOT SHOWING IN BROWSER:
> 
> Freezing file:///private/var/folders/jt/m9f0ht492399/T/tmpsrx.html DocumentFreezer.js:81:15
> sendSyncMessage suspend #0/1 SyncMessage.js:226:19
> Unfreezing file:///private/var/folders/jt/m9f0ht492399/T/tmpsrx.htmlDocumentFreezer.js:97:15
> sendSyncMessage finalizing SyncMessage.js:244:19
> sendSyncMessage resume #0/0 - 18ms SyncMessage.js:235:19
> sendSyncMessage finalizing SyncMessage.js:244:19
> [bokeh] setting log level to: 'info' bokeh-2.2.3.min.js:188:1389
> [bokeh] document idle at 51 ms bokeh-2.2.3.min.js:166:1258
> [bokeh] unable to load /Chess/lichess_pieces/cburnett/bB.svg image after 1 attempts bokeh-2.2.3.min.js:428:365
> [bokeh] attempting to load /Chess/lichess_pieces/cburnett/bB.svg without a cross origin policy bokeh-2.2.3.min.js:428:452
> [bokeh] unable to load /Chess/lichess_pieces/cburnett/bB.svg image after 1 attempts bokeh-2.2.3.min.js:428:365
> 
> 
> SHOWING IN BROWSER:
> 
> same without last line
> ...
> [bokeh] unable to load /Users/user_name/project_name/static/lichess_pieces/cburnett/bB.svg image after 1 attemptsbokeh-2.2.3.min.js:428:365
> [bokeh] attempting to load /Users/user_name/project_name/static/lichess_pieces/cburnett/bB.svg without a cross origin policy bokeh-2.2.3.min.js:428:452


```
# 1
from bokeh.plotting import figure
from bokeh.io.export import get_screenshot_as_png
from bokeh.io import show, export_png

img_url1 = "project_name/static/image.svg"

p = figure(x_range=(0,1), y_range=(0,1))
p.image_url([img_url1], x=0.5, y=0.5, w=1, h=1, anchor=‘center’)
show( p )

export_png(p, png1.png)


# 2
from bokeh.plotting import figure
from bokeh.io.export import get_screenshot_as_png
from bokeh.io import show, export_png

img_url2 =  "/Users/user_name/project_name/static/image.svg"

p = figure(x_range=(0,1), y_range=(0,1))
p.image_url([img_url2], x=0.5, y=0.5, w=1, h=1, anchor=‘center’)
show( p )

export_png(p, png2.png)
```

**Comment by bryevdv** [comment]
@znstrider do things work when you use images from proper URL locations, e.g `https://some.place/foo.svg` browsers have various restrictions about when and how they will loa local files and I can imagine that might be the problem here (if so, nothing we can do about it)

**Comment by bryevdv** [comment]
closing as stale 

Given the passing visual test with a remote SVG referenced above, it's possible this is related to locally loaded files and browser security rules. TO consider re-opening this we would need:

* OS/browser info (including versions)
* Bokeh version
* complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) (including any SVG files to run)
