### ISSUE TITLE
[FEATURE] Differential re-rendering of updated plots

### ISSUE THREAD

**Issue by ShashShukla** [bokeh/bokeh#10784]
I created an animation in Bokeh 1.4 using CustomJS callbacks that consists of a set of static line plots in the background (low opacity), one static highlighted plot (high opacity), and a dot that moves along this static highlighted plot as time progresses. I find that if I render only the highlighted plot and moving dot, the animation is very snappy. But when I include the other line plots as well, the animation is about 10 times slower, despite the fact that these other plots are static. My guess is thus that while only the position of the single dot is changing over time, Bokeh seems to re-rendering the static plots as well, leading to a huge slowdown in animation speed. 

It would thus be great if there were a way to more efficiently re-render the plot, with Bokeh only re-rendering parts of the plot that have actually changed.

My code for when all the line plots are included:
```py
import numpy as np
import time
from bokeh.models import ColumnDataSource, CustomJS, Slider, Toggle
from bokeh.io import output_notebook
from bokeh.layouts import grid
from bokeh.plotting import figure, show
from bokeh.palettes import viridis as colormap
output_notebook() # render animation inline

dt = 5e-4
ds = 100 # downsampling factor
N = 20 # number of signals
x = np.arange(0,2*np.pi,dt)
f = np.arange(1,N+1)
y = np.sin(np.outer(f,x))

xi = 0 # initial index for time slider
fs = 0 # index of selected signal

x_t = [x[xi]]
y_t = [y[fs][xi]]

# load data in Bokeh
graphs = ColumnDataSource(dict(x=x,y=y[0]))
nodes = ColumnDataSource(dict(x_t=x_t,y_t=y_t))
index_t = ColumnDataSource(dict(index=x))

# construct bokeh plots
TOOLS = "pan, box_zoom, wheel_zoom, box_select, reset"
colors = colormap(N)

plot = figure(tools=TOOLS, plot_width=200, plot_height=30, title="Signal vs Time")
plot.title.align='center'
plot.line(x='x', y='y', source=graphs, color='black')
plot.circle(x='x_t', y='y_t', source=nodes, size=15, color='grey')
for n in range(N):
    plot.line(x=x, y=y[n], color=colors[n], alpha=0.1)

# time slider
Timecallback = CustomJS(args=dict(graphs=graphs, nodes=nodes, dt=dt*ds),
                    code="""
    const arrayPos = (array) => Math.abs(array - cb_obj.value) < 0.1*dt;
    const new_value = graphs.data['x'].findIndex(arrayPos);
    
    nodes.data['x_t']  = [graphs.data['x'][new_value]];
    nodes.data['y_t']  = [graphs.data['y'][new_value]];
    nodes.change.emit();
""")

t_slider = Slider(start=x[0], end=x[-1], value=x[xi], step=dt*ds, title="Time")
t_slider.js_on_change('value', Timecallback)

# play/pause
toggle_js = CustomJS(args=dict(slider=t_slider,indexCDS=index_t, dt=dt*ds),code="""
    var check_and_iterate = function(index){
        var slider_val = slider.value;
        var toggle_val = cb_obj.active;
        if(toggle_val == false) {
            cb_obj.label = '► Play';
            clearInterval(looop);
            }
        else if(slider_val >= index[index.length - 1]) {
            cb_obj.label = '► Play';
            slider.value = index[0];
            cb_obj.active = false;
            clearInterval(looop);
            }
        else if(slider_val !== index[index.length - 1]){
            slider.value = slider.value + dt;
            }
        else {
        clearInterval(looop);
            }
    }
    if(cb_obj.active == false){
        cb_obj.label = '► Play';
        clearInterval(looop);
    }
    else {
        cb_obj.label = '❚❚ Pause';
        var looop = setInterval(check_and_iterate, 10, indexCDS.data['index']);
    };
""")

toggle = Toggle(label='► Play',active=False)
toggle.js_on_change('active',toggle_js)

# render interactive plot
layout = grid([[plot], [toggle,t_slider]], sizing_mode = 'scale_width')
show(layout)
```

To see the difference in animation speed, simply comment out the code corresponding to the static line plots in the background:
```
for n in range(N):
    plot.line(x=x, y=y[n], color=colors[n], alpha=0.1)
```

**Comment by mattpap** [comment]
Having a generic partial renderer would be great, but that's far in the future. For now there is (well, should be) a simple workaround, which works by layering your visualization, where each layer can be updated and repainted independently. Currently we use this approach for rendering selection overlays, etc. In your case this change should work:
```py
plot.circle(x='x_t', y='y_t', source=nodes, size=15, color='grey', level="overlay")
```
Unfortunately, due internal faulty logic, this still triggers full repaint when glyphs are changed.

**Comment by bryevdv** [comment]
Can we clarify terminology? Even with separately rendered and stored layers, there will always (to my definition) be a "full repaint" at the end when all the layer canvases are blitted to the final canvas? I think you mean that some of the expensive `render` calls can be avoided, if there are layers with no changes they can just be re-painted as-is.

**Comment by ShashShukla** [comment]
@mattpap Thank you for the suggestion. I specified the level for the circle plot as you suggested, but there is no discernible difference in animation time. I also tried relegating the static plots to the 'image' or 'underlay' level, but again saw no change in runtime. This may indicate that the bottleneck is the final blitting that @bryevdv alluded to.

**Comment by mattpap** [comment]
> I specified the level for the circle plot as you suggested, but there is no discernible difference in animation time. 

You need PR #10785 for this.
