### ISSUE TITLE
Typo in prelude.ts

### ISSUE THREAD

**Issue by dvbuntu** [bokeh/bokeh#10782]
There is a typo in prelude.ts which becomes part of `bokeh-[VERSION].min.js`. "lenght" should be replace with "length"

https://github.com/bokeh/bokeh/blob/90e83b256dafa1371cc90d4e03ffcdc006b8e172/bokehjs/src/compiler/prelude.ts#L65

**Comment by bryevdv** [comment]
@dvbuntu how did you run in to this? Is there a specific set up or usage that uncovers this directly?

cc @mattpap

**Comment by dvbuntu** [comment]
I was trying to diagnose an unrelated problem and opened up https://cdn.bokeh.org/bokeh/release/bokeh-2.2.3.min.js directly.  The typo happens near the top, so I just happened to see it.  Then I searched for the typo in the repository itself to find what file creates that portion.  As a 2nd condition of an AND statement, I suspect this only triggers rarely.

**Comment by mattpap** [comment]
I need to verify this, but this part of the normalization function may not be needed anymore.

**Comment by mattpap** [comment]
This was fixed in PR #13713.
