### ISSUE TITLE
Dialog not in sync with TextInput's "on_change" callback in taylor_server.py

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [bokeh/bokeh#1078]
I am using [`taylor_serverl.py`](https://github.com/ContinuumIO/bokeh/blob/master/examples/glyphs/taylor_server.py) as a model for several apps that I am hoping to build, but I am running into a strange problem. If you run the original example  [`taylor_serverl.py`](https://github.com/ContinuumIO/bokeh/blob/master/examples/glyphs/taylor_server.py) from `master` using the latest dev build (`20140822`) you will notice the following behavior:

1. Enter a bad expression in the field **Expression**, e.g. `exp(-x)*sin(x)foo` (noticed that I appended `foo` at the end of the default expression), and press `RET` (enter)
3. You will get a dialog saying that `Sympify of expression 'could not parse u'exp(-x)*sin(x)foo'' failed ... `. So far so good, this is to be expected.
4. Close the dialog and **fix the expression**, e.g. enter the original default expression `exp(-x)*sin(x)`, and press `RET` (enter)
5. You will get **again** a dialog saying that the expression is wrong. If you close the dialog and just press `RET` again, it will work fine (the dialog won't pop up)

The above happens every time I update the expression. Why is this? Is it a bug in the example or a bug the widget `Dialog`?  I am still not familiar with the internals of Bokeh (e.g. what `sesion.store_document` does), so I can't tell.

**Comment by birdsarah** [comment]
This seems to be fixed in Bokeh 0.9.1. Please re-open is you see the issue again.
