### ISSUE TITLE
[FEATURE] boxplot.py example: improve performance for larger datasets

### ISSUE THREAD

**Issue by Saravji** [bokeh/bokeh#10783]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**
I used the boxplot.py example to implement a very similar functionality in my project. The issue comes with the volume of the data: My dataset is several million rows.
Actually processing the data and getting a plot takes an extremely long time.

**Describe the solution you'd like**
I did some performance analysis and found that lines 30 to 35 are responsible for 95% of time spend:
```
if not out.empty:
    outx = []
    outy = []
    for keys in out.index:
        outx.append(keys[0])
        outy.append(out.loc[keys[0]].loc[keys[1]])
```

**Describe alternatives you've considered**
Suggesting to replace lines 30 to 35 with:
```
if not out.empty:
    outx = list(out.index.get_level_values(0)
    outy = list(out.values)
```

**Additional context**
analysis on my test dataset (15000 rows) did reduce this part alone from 6.66s to 4.14ms
running the code on my full dataset (35,278,061 rows) delivers a result in 3.46 seconds while I aborted the current code without result after 6 hours.

Happy to contribute.

**Comment by bryevdv** [comment]
> Happy to contribute.

@Saravji A PR to update the example would be great, thank you!
