### ISSUE TITLE
Add default browser env var to docs

### ISSUE THREAD

**Issue by hyles-lineata** [bokeh/bokeh#10796]
MarcSkovMadsen has [posted on the Discourse](https://discourse.bokeh.org/t/setting-the-default-browser-for-show-on-windows/6946) about setting an env var to point to the default browser for `--show`.

Having run into this need myself, I think it would be a good idea to add this to the documentation updates coming out with 2.3, and I am assigning myself to execute.

**Comment by bryevdv** [comment]
FYI env vars are currently documented in the `bokeh.settings` reference:

https://docs.bokeh.org/en/latest/docs/reference/settings.html#bokeh-settings

(and also referenced briefly in the [dev guide](https://docs.bokeh.org/en/latest/docs/dev_guide/env_vars.html))

Perhaps there is some way to surface them better tho

**Comment by hyles-lineata** [comment]
Ah! That's great, then. I had looked through the User Guide and hadn't seen them. Any objection to adding them there too (or maybe just links, rather than repeating the information)?

**Comment by bryevdv** [comment]
I think links to `bokeh.settings` and maybe also more explicitly highlighting the connection that every setting has an associated env var would be good. I don't have strong  feelings about where to link, there doesn't seem to be an entirely relevant place except maybe a new subsection in *Defining Key Concepts*?

**Comment by bryevdv** [comment]
@tcmetzger any thoughts on where this might best fit?

**Comment by tcmetzger** [comment]
Yes, _Defining Key Concepts_ sounds like a good place, I'd say after _Output methods_. I'll draft something up the next few days and start a PR. What would be the most important ones to explicitly mention there? `BOKEH_BROWSER `and `BOKEH_RESOURCES`, I think? For the rest I'd link to the reference guide.
