### ISSUE TITLE
[FEATURE] Page Visibility API

### ISSUE THREAD

**Issue by zybex86** [bokeh/bokeh#10794]
Problem:
[I wanted to utilize the Page Visibility API to stop/start an AJAX callback in a plot](https://discourse.bokeh.org/t/utilizing-page-visibility-api/6914).

There was a problem with accessing the variables for the source and other tools that were available on the page. In the end, I could access the variables in JS by naming the variables in Python and referencing them using `window.Bokeh.documents[0].get_model_by_name("foo")`

There could be an easier way to access those elements. Maybe let the `args` in `CustomJS` be available in JS in some way? Not a JS expert here so I do not know how to do it :(

**Comment by zybex86** [comment]
@bryevdv suggested that @hyles-lineata should get to know the issue

**Comment by bryevdv** [comment]
@mattpap is the document index now exposed in the `context` parameter to `CustomJS`?

**Comment by mattpap** [comment]
Yes. Here's a usage example:

https://github.com/bokeh/bokeh/blob/000d49f9bfed412be978d995ecdb88cf9d412ecf/examples/interaction/js_callbacks/reset_plot.py#L18-L22

**Comment by bryevdv** [comment]
I think this issue could be closed then, or re-purposed just for docs updates? 

That said, I am going to make an issue about factoring out common "CustomJS" implementation logic, and that would also be a good time to document common behavior and expectations for all "CustomJS" models, in which case we could close this issue in favor of the new one.

**Comment by bryevdv** [comment]
I"m going to close this in favor of #13994
