### ISSUE TITLE
[FEATURE] Support Tornado WebSocket compression on server

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#10798]
Tornado has supported enabling of WebSocket compression [since v4.1](https://www.tornadoweb.org/en/stable/websocket.html#tornado.websocket.WebSocketHandler.get_compression_options). When working locally this makes little sense but when serving a Bokeh application on a server it can be useful to enable compression and reduce the bandwidth but increasing CPU and memory cost.

**Comment by bryevdv** [comment]
@philippjfr AFAIK the current test failures are all fairly trivial but we should also at least add a mock test that verifies that when the setting is set that the tornado side is passed the expected config value as well.
