### ISSUE TITLE
export_svg function in branch-2.3

### ISSUE THREAD

**Issue by dbogatov** [bokeh/bokeh#10792]
I was following discussions here https://github.com/bokeh/bokeh/pull/10402 and here https://github.com/bokeh/bokeh/issues/9169 .
I got the impression that `export_svg` is fixed in https://github.com/bokeh/bokeh/pull/10713 .

So I followed the dvelopement instructions to install the very latest version of the package, and yet it says that it cannot import `export_svg` from `bokeh.io`.
Is it supposed to work in the latest patch?

**Comment by bryevdv** [comment]
> that it cannot import export_svg from bokeh.io

That function is very recent. Almost certainly you are picking up an old version install, instead of the development install. You can inspect `bokeh.__version__` to confirm. Check your system paths, conda or virtual envs, etc.

**Comment by bryevdv** [comment]
If you have further usage/support questions then https://discourse.bokeh.org is a good resource.
