### ISSUE TITLE
[BUG] precision loss in patch update when using timeseries data with multi_line glyph (introduced in v2.2.0)

### ISSUE THREAD

**Issue by jundl77** [bokeh/bokeh#10801]
The patch update functionality became very slow (possibly also incorrect) when working with a `datetime` X axis (i.e. timeseries data) and a `multi_line` glyph starting at version 2.2.0. I am not sure about other glyphs, as I have not tested them.

#### Software version details
**Bokeh:** Bug appeared going from 2.1.1 -> 2.2.0 (I am currently using 2.2.3)
**Python:** 3.8
**OS:** Mac OSX 10.15.7
**Browser:** Chrome 87.0.4280.88

#### Description of expected behavior and the observed behavior
Starting at version 2.2.0 of bokeh, the [patch](https://github.com/bokeh/bokeh/blob/branch-2.3/bokeh/models/sources.py#L530) update method became very slow when working with the `multi_line` glyph. I have created a minimal example based on the [patch_app.py](https://github.com/bokeh/bokeh/blob/main/examples/howto/patch_app.py) that demonstrates this behavior.

In the example, you will see two graphs, each randomly updating via patch. One graph has an integer X-axis, and one has a DateTime X-axis. If you run the code once with bokeh version 2.1.1, you will see that both graphs update at the same rate, but starting on bokeh version 2.2.0, the graph with the integer X-axis will update at the same rate as before, but the graph with the DateTime X-axis will update significantly slower, and also at seemingly random intervals, to a point where it is not very usable.

You will also notice that no random points are updated in the datetime X-axis graph. Instead, the updated points "snap" to other points, almost as if they were grouped-by clusters. This is also something that I have noticed in my real-world application, where the intended points are no longer updated correctly. Below, you will find the example code, as well as some pictures showing the results.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
# This is a Bokeh server app. To function, it must be run using the
# Bokeh server ath the command line:
#
#     bokeh serve --show patch_app.py
#
# Running "python patch_app.py" will NOT work.
import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import gridplot
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from datetime import datetime, timedelta


def gen_timeseries(size):
    ui_refresh_rate_ms = timedelta(milliseconds=2000)

    start_timestamp = datetime.now()

    timestamp_counter = start_timestamp + ui_refresh_rate_ms
    datetime_axis = list()
    for i in range(size):
        datetime_axis.append(timestamp_counter)
        timestamp_counter += ui_refresh_rate_ms

    return datetime_axis

# CDS with 1d array elements and a numerical X axis
x = np.linspace(0, 10, 200)
y0 = np.sin(x)
y1 = np.cos(x)
source_numerical = ColumnDataSource(data=dict(xs=[x, x], ys=[y0, y1], color=["olive", "navy"]))

p1 = figure(plot_width=400, plot_height=400)
p1.multi_line('xs', 'ys', alpha=0.6, line_width=4, color="color", source=source_numerical)

# CDS with 1d array elements and a datetime X axis
x = gen_timeseries(200)
x_random = np.random.uniform(10, size=200)
y0 = np.sin(x_random)
y1 = np.cos(x_random)
source_datetime = ColumnDataSource(data=dict(xs=[x, x], ys=[y0, y1], color=["red", "green"]))

p2 = figure(plot_width=400, plot_height=400)
p2.multi_line('xs', 'ys', alpha=0.6, line_width=4, color="color", source=source_datetime)


def update():
    # update a single point of the numerical X-axis data
    i = np.random.randint(200)
    new_y_a = 100 * np.random.random()
    new_y_b = 100 * np.random.random()
    source_numerical.patch({'ys': [([0, i], [new_y_a]), ([1, i], [new_y_b])]})

    # update a single point of the datetime X-axis data
    i = np.random.randint(200)
    new_y_a = 100 * np.random.random()
    new_y_b = 100 * np.random.random()
    source_datetime.patch({'ys': [([0, i], [new_y_a]), ([1, i], [new_y_b])]})


curdoc().add_periodic_callback(update, 50)

curdoc().add_root(gridplot([[p1, p2]]))
```

#### Example Screenshots

**bokeh-2.1.1 after 10sec**:
![image](https://user-images.githubusercontent.com/3936594/103232984-31f5f480-493c-11eb-8b1f-b7058a4e6454.png)

**bokeh-2.2.3 after 10sec**:
![image](https://user-images.githubusercontent.com/3936594/103232932-11c63580-493c-11eb-9cd9-bd71fbf98279.png)

You can see how the identical code results in two very different update patterns for the datetime X-axis graph (right graph) in the two bokeh versions.

I have looked a little bit at the bokeh code to see what the issue could be, but I could not really find anything.

**Comment by mattpap** [comment]
Possibly duplicate or another variant of #10738. I will keep this open for now, at least until I verify this in PR #10788.

**Comment by bryevdv** [comment]
The visual discrepancy is certainly the same as #10738 and I wonder if the "slowness" is simply that visual updates are happening "on top of" one another (so ~N updates happen before any visual differences appear)

**Comment by jundl77** [comment]
So you think it's mostly due to precision loss? I can run the same sample code again, with say a 2hour ticks in the x-axis instead of a 2sec ticks, I assume that should then eliminate the effect, right?

**Comment by jundl77** [comment]
That certainly seems to be the case, here is what it looks like with a 2hour intervals on the x-axis instead of 2sec:

![image](https://user-images.githubusercontent.com/3936594/103308959-09412e00-4a14-11eb-9e1d-5db05e3b0f83.png)

**Comment by bryevdv** [comment]
Thanks for the updated results @jundl77 ! @mattpap do you still want to keep this open?

**Comment by jundl77** [comment]
Yeah, no problem. Do you have any ETA on when this will be fixed? I'm asking, because if it will take longer, then we might just use bokeh 2.1.1 for now.

**Comment by mattpap** [comment]
> Do you have any ETA on when this will be fixed?

ASAP, but then we need to make the release, which it looks will happen between 11-15 of January.

**Comment by jundl77** [comment]
Ah, that's great news!
