### ISSUE TITLE
Local Docs builds not working

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10808]
cc @mattpap @tcmetzger 

Are either of you able to build and view docs locally on `branch-2.3`? I have tried the following steps:

* `git clean -fdx .`
* `rm -rf bokehjs/node_modules`
* `python setup.py --build-js`
* `BOKEH_DOCS_CDN=local GOOGLE_API_KEY="junk" make clean html serve`

Then when viewing the docs in the browser there are no plots, and console errors:

<img width="1227" alt="Screen Shot 2020-12-31 at 12 10 03 PM" src="https://user-images.githubusercontent.com/1078448/103424449-34856380-4b61-11eb-99b7-822ae7b645e9.png">

I'm willing to believe there is an issue somehow just on my local end but I'd like confirmation that things work for others.

**Comment by mattpap** [comment]
I'm guessing `rm -rf bokehjs/build` should help. If that's the case, then we may want to use `node make build --rebuild` under `--build-js` to disable caching.

**Comment by bryevdv** [comment]
It did, but wonder why `git clean -fdx .` at the top level did not remove. I will leave this open for now to consider changes to `--build-js`
