### ISSUE TITLE
`conda` warnings from bokeh-ci workflow

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10803]
There multiple warnings like this in every CI run:
```
Warning: 'defaults' already in 'channels' list, moving to the top
```
Perhaps benign, but maybe affects resolution order. In any case, it would be good to clear this up. /cc @bryevdv

**Comment by bryevdv** [comment]
Weird, I will take a look soon.

**Comment by bryevdv** [comment]
@mattpap I think this is actually coming from `conda-incubator/setup-miniconda` and maybe the solution is just to remove `defaults` from the env files e.g. here:

https://github.com/bokeh/bokeh/blob/branch-2.3/ci/environment-test-3.9.yml#L26

But we *do* want defaults first AFAIK and the warning mentions that its presence results in "moving to the top" so we might just have to live with it unless there is some other way to guarantee defaults is always first.
