### ISSUE TITLE
Enable custom tick formatter labels

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#1080]
(previous conversation in https://github.com/ContinuumIO/bokeh/issues/106)

Would be nice for users to specify a custom tick formatting instead of relying on BokehJS defaults.

Not considered a high priority at the moment.

**Comment by kdodia** [comment]
Closing in favor of #1668

**Comment by bryevdv** [comment]
Sorry I searched for "ticks" and missed a few existing issues it seems.
