### ISSUE TITLE
Upgrade bokeh.server.django to django 3.x

### ISSUE THREAD

**Issue by grant-m-s** [bokeh/bokeh#10800]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Ubuntu 20.04
python 3.8.5
bokeh-2.2.3, Django-3.1.4, channels-3.0.3, panel-0.10.2
Firefox 84.0
Chrome 87.0.4280.66

#### Description of expected behavior and the observed behavior

Trying to run your bokeh django howto code located [here](https://github.com/bokeh/bokeh/tree/branch-2.3/examples/howto/server_embed/django_embed).

When I run `python3 manage.py runserver 0.0.0.0:8000` the server starts without any issues.

When I then go to any of the app links:
[http://127.0.0.1:8000/shape_viewer](http://127.0.0.1:8000/shape_viewer), [http://127.0.0.1:8000/sea_surface](http://127.0.0.1:8000/sea_surface), or [http://127.0.0.1:8000/sea_surface_with_template](http://127.0.0.1:8000/sea_surface_with_template)
The tab says: '500 Internal Server Error Exception inside application. Daphne'

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

python3 manage.py runserver 0.0.0.0:8000

```

#### Stack traceback and/or browser JavaScript console output
```Traceback (most recent call last):
  File "Directory/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "Directory/lib/python3.8/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "Directory/lib/python3.8/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "Directory/lib/python3.8/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "Directory/lib/python3.8/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "Directory/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "Directory/lib/python3.8/site-packages/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
  File "Directory/lib/python3.8/site-packages/bokeh/server/django/consumers.py", line 103, in __init__
    kwargs = self.scope["url_route"]["kwargs"]
AttributeError: 'DocConsumer' object has no attribute 'scope'
HTTP GET /shape_viewer 500 [0.90, 127.0.0.1:56486]
```

**Comment by mattpap** [comment]
> Django-3.1.4

Django support in bokeh was designed for and tested with django 2.x. We would like to upgrade to 3.x, but we don't have resources for this currently.

**Comment by yvechang** [comment]
> > Django-3.1.4
> 
> Django support in bokeh was designed for and tested with django 2.x. We would like to upgrade to 3.x, but we don't have resources for this currently.

My django version is (2, 2, 19, 'final', 0). However, I have the same problem as [grant-m-s posted](https://github.com/bokeh/bokeh/issues/10800#issue-775444914).
"AttributeError: 'DocConsumer' object has no attribute 'scope'"

Does I miss something?

**Comment by bryevdv** [comment]
functionality moving to separate project
