### ISSUE TITLE
[BUG] Example in LabelSet documentation doesn't seem to be correct

### ISSUE THREAD

**Issue by blutack** [bokeh/bokeh#10819]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh v2.2.3, Python 3.9

#### Description of expected behavior and the observed behavior

I created a LabelSet by pasting the only example from the current user guide (https://docs.bokeh.org/en/latest/docs/user_guide/annotations.html#labels).

```
LabelSet(x='x', y='y', text='names', level='glyph',
         x_offset=5, y_offset=5, source=source)
```

However, no labels were visible.

I then found this stackoverflow question (https://stackoverflow.com/questions/57084145/bokeh-doesnt-show-labels) in which the suggested answer was to remove the `level='glyph'` argument.

I removed the level argument and my LabelSet then worked correctly.

In the stackoverflow question, user 'bigreddot' said the following, implying they are a bokeh developer:

> I can guarantee we've never tested LabelSet with level='glyph'. It's definitely not anything we would have imagined or intended. The default level annotation was chosen specifically to make sure that the labels rendered on top of everything else. I would generally consider level to be an implementation detail accidentally and unfortunately leaked in to the public API and would advise against tinkering with it in any case. – bigreddot Jul 18 '19 at 6:44

If this is correct, could someone please accept a pull request or directly amend the example in the documentation and remove the level argument?

Many thanks!

**Comment by bryevdv** [comment]
@blutack if you are offering to make the PR, we would accept it.

**Comment by blutack** [comment]
Thanks, I've opened a PR
