### ISSUE TITLE
LabelSet not shown when x axis is text, not a number

### ISSUE THREAD

**Issue by hansqiao** [bokeh/bokeh#10818]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**
There is a problem to show labels in vbar, when x axis is not a number. Label shows correctly when x axis is in numbers.

**Describe the solution you'd like**
Will like label (LabelSet) to show no matter if x axis is number or not.

**Describe alternatives you've considered**
Currently using BokehJS 2.2.3. Heard 2.3 resolved the issue. Please maintain it in new versions.

**Additional context**

**Comment by hansqiao** [comment]
Here is one not showing label:

from bokeh.palettes import PuBu
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource, ranges, LabelSet
from bokeh.plotting import figure
output_notebook()

source = ColumnDataSource(dict(x=['Áætlaðir','Unnir'],y=[576,608]))

x_label = ""
y_label = "Tímar (klst)"
title = "Tímar; núllti til þriðji sprettur."
plot = figure(plot_width=600, plot_height=300, tools="save",
        x_axis_label = x_label,
        y_axis_label = y_label,
        title=title,
        x_minor_ticks=2,
        x_range = source.data["x"],
        y_range= ranges.Range1d(start=0,end=700))


labels = LabelSet(x='x', y='y', text='y', level='glyph',
        x_offset=-13.5, y_offset=10, source=source, render_mode='canvas')

plot.vbar(source=source,x='x',top='y',bottom=0,width=0.3)

plot.add_layout(labels)
show(plot)

**Comment by hansqiao** [comment]
But change x to number, then label shows:

from bokeh.palettes import PuBu
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource, ranges, LabelSet
from bokeh.plotting import figure
output_notebook()

source = ColumnDataSource(dict(x=[2,3],y=[576,608]))

x_label = ""
y_label = "Tímar (klst)"
title = "Tímar; núllti til þriðji sprettur."
plot = figure(plot_width=600, plot_height=300, tools="save",
        x_axis_label = x_label,
        y_axis_label = y_label,
        title=title,
        x_minor_ticks=2,
        x_range = (1,5),
        y_range= ranges.Range1d(start=0,end=700))


labels = LabelSet(x='x', y='y', text='y', level='glyph',
        x_offset=-13.5, y_offset=10, source=source, render_mode='canvas')

plot.vbar(source=source,x='x',top='y',bottom=0,width=0.3)

plot.add_layout(labels)
show(plot)

**Comment by bryevdv** [comment]
> Heard 2.3 resolved the issue.

@hansqiao if you heard that it was fixed in 2.3 then please search for an existing issue (or ask about it on Slack or Discourse) before making a new issues. This was resolved in https://github.com/bokeh/bokeh/issues/10454 (not yet released)
