### ISSUE TITLE
[BUG]: links lead to a 404 error

### ISSUE THREAD

**Issue by cyborg1995** [bokeh/bokeh#10813]
Hello, the links given in [README.md](https://github.com/bokeh/bokeh/blob/branch-2.3/README.md) lead to a webpage showing a 404 error.

1. 'installation documentation' link under Installation
2. 'first steps guides' link under Resources

Thanks!

**Comment by bryevdv** [comment]
Thanks for the issue @cyborg1995 however this is just a timing issue. The README links were updated in anticipation of new docs locations that will go live when the next release is published (it's just taking longer than we expected)
