### ISSUE TITLE
Add Hatch Patterns for Glyphs

### ISSUE THREAD

**Issue by dbeezt** [bokeh/bokeh#10824]
I was surprised to see that hatch patterns can't be applied to Glyphs, at least not to those of class 'Circle'. There's render-able space so it seems fitting to allow a pattern to occupy it just as a colour would.

Example code:

    g = nx.erdos_renyi_graph(n = 20, p = 0.5)  
    graph_renderer = from_networkx(g, nx.spring_layout, scale=1, center=(0, 0))
    graph_renderer.node_renderer.glyph = Circle(size='5', fill_color='green', hatch_pattern='static')
    show(plot)

Results in `AttributeError: unexpected attribute 'hatch_pattern' to Circle, possible attributes are angle, angle_units, fill_alpha, fill_color, js_event_callbacks, js_property_callbacks, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, radius, radius_dimension, radius_units, size, subscribed_events, tags, x or y`.

**Comment by mattpap** [comment]
It makes sense to have hatch patterns supported for all glyphs that already support fill visuals. PR #10825 implements this.

**Comment by dbeezt** [comment]
Talk about a fast turnaround! That's awesome, thanks for engaging.
