### ISSUE TITLE
[BUG] Patches drawn as a single shape if used with CDSView

### ISSUE THREAD

**Issue by hal8174** [bokeh/bokeh#10831]
#### ALL software version info
bokeh: 2.2.3
python: 3.9.1
browser: firefox and chrome

#### Description of expected behavior and the observed behavior

If patches are drawn with a CDSView, the shapes are drawn as one shape instead of multiple.

This bug only appears, if a subset of the data is drawn with patches.

#### Code Example

```python
from bokeh.plotting import curdoc, figure
from bokeh.models import ColumnDataSource, CDSView, Div
from bokeh.models.filters import BooleanFilter
from bokeh.layouts import column, row


data1 = ColumnDataSource({'xs': [[1, 1, 0, 0], [4, 4, 3, 3], [2, 2, 1, 1]],
                          'ys': [[1, 0, 0, 1], [4, 3, 3, 4], [2, 1, 1, 2]]})

p1 = figure()

p1.patches(
    source=data1,
    view=CDSView(source=data1, filters=[BooleanFilter([False, True, True])])
)

data2 = ColumnDataSource({'xs': [[4, 4, 3, 3], [2, 2, 1, 1]],
                          'ys': [[4, 3, 3, 4], [2, 1, 1, 2]]})

p2 = figure()

p2.patches(
    source=data2
)

curdoc().add_root(row(column(Div(text='<h2>Bug:</h2>'),
                             p1), column(Div(text='<h2>Expected:</h2>'), p2)))
```

#### Bug in action

![image](https://user-images.githubusercontent.com/65651213/104125903-f60a5880-5359-11eb-8dff-1be2ef64625a.png)

**Comment by mattpap** [comment]
This is fixed in 2.3-dev. Likely candidate for a duplicate is issue #10589.
