### ISSUE TITLE
[BUG] Layout regressions

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10851]
cc @mattpap 

`branch-2.3` has some serious layout regressions, verified on OSX with Chrome and Safari. These shots were generated with `2.3.0dev10-6-g3b668d6c` (not fixed by uniforms PR)

Some examples:

<img width="1718" alt="Screen Shot 2021-01-18 at 1 28 24 PM" src="https://user-images.githubusercontent.com/1078448/104964966-718b8b80-5992-11eb-8db6-a82a50b7defe.png">

<img width="1045" alt="Screen Shot 2021-01-18 at 1 31 03 PM" src="https://user-images.githubusercontent.com/1078448/104964972-74867c00-5992-11eb-8cd2-8ef73210a420.png">

<img width="1535" alt="Screen Shot 2021-01-18 at 1 38 42 PM" src="https://user-images.githubusercontent.com/1078448/104964983-7f411100-5992-11eb-944f-e4e751783d4e.png">

**Comment by mattpap** [comment]
I will investigate this tomorrow.
