### ISSUE TITLE
Orientation on titles

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1085]
We currently support orientarion (rotation) of tick labels, but not "title" labels.

**Comment by birdsarah** [comment]
ping @bryevdv @pzwang - re our discussion on title rotation - this has been a feature request for a while (here's the mailing list discussion - https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/1085/bokeh/MqJW3qWifYg/ZTUZ_Trw84gJ)

**Comment by birdsarah** [comment]
This is now completed as part of #4392.

You can add a title to any side of a plot and it auto-rotates (similar to Axis). You can also manually add a Label and rotate it yourself to any degree you want and place it wherever you want.
