### ISSUE TITLE
[FEATURE]would you like upgrade bokeh-scala to support jdk8 and scala-2.12 or scala-2.13

### ISSUE THREAD

**Issue by mullerhai** [bokeh/bokeh#10859]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bryevdv** [comment]
@mullerhai the title is confusing — are you offering to do this work yourself? bokeh-scala is not currently actively maintained and has not been updated in several years. (also this issue should be moved to the bokeh-scala repository)

**Comment by mattpap** [comment]
At this point bokeh-scala needs to be rewritten from scratch to make it usable with modern bokehjs (the last released version supports bokehjs ~0.12). If there is interest in that, let's continue discussion in bokeh-scala's repository or in [Discussions](https://github.com/bokeh/bokeh/discussions).

**Comment by mullerhai** [comment]
> At this point bokeh-scala needs to be rewritten from scratch to make it usable with modern bokehjs (the last released version supports bokehjs ~0.12). If there is interest in that, let's continue discussion in bokeh-scala's repository or in [Discussions](https://github.com/bokeh/bokeh/discussions).

Thanks ，I also can use  bokeh in python
