### ISSUE TITLE
[BUG] Ajax and Server sent examples broken  

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10853]
cc @mattpap 

Browser display is completely blank and JS console reports

> Unhandled Promise Rejection: Error: Size mismatch

for both `ajax_source.py` and `server_sent_events_source.py`

Present on `2.3.0dev10-7-g6fbe3be6b` (not fixed by uniforms PR)

**Comment by mattpap** [comment]
It's a corner case in data initialization related to empty data sources. I will get that fixed tomorrow.
