### ISSUE TITLE
Widgets + Plotting.py integration interface discussion

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1086]
I'd like to get the discussion going on the widgets + plotting.py integration and get everyone's ideas on how they'd like the interface to look like.

I'd like for us to wrap as much as possible the widget, so the user doesn't have to write all those functions that we are currently writing in our examples in the low interface; even if that means restricting a little bit what you can do with them (if they need something more particular they can always go to the lower interface).

I think it should be something as minimalistic as:

```python
line(x="foo", y="bar", source=data_source....)
select_widget(selectable_column="baz", source=data_source)
```

*Note: For me source here is not the current ColumnDataSource, but your entire data_source (maybe something similar to what @MattR proposed as a BlazeDataSource), something that you pass that contains everything that you'll ever want to plot within that plot using those widgets.

Of course, we'll have to analyze what would the common use case of each widget be, take into account the coming stateless plotting interface, @mattpap's python->JS  and how to manage that connection to this "BlazeDataSource" or whatever alternative we can think of.

cc: @bryevdv, @damianavila, @kdodia

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
