### ISSUE TITLE
[BUG] bokeh.client max nessage size not configurable

### ISSUE THREAD

**Issue by jeffreymonaco** [bokeh/bokeh#10863]
ISSUE Bokeh server application with moderate size column data source (10000 samples of 100 variables) works when accessed directly via standalone server but fails when embedded in a Flask application using pull_session()/server_session() mechanism.

It can be shown by example that the problem manifests based on the size of the data source used in a plot even in cases where only two of the columns are used in the rendering.

ENVIRONMENT Mac OSX Big Sur with Anaconda Python. Python 3.8.5, Bokeh 2.2.3, Flask 1.1.2.
Client browser Google Chrome Version 87.0.4280.141 (Official Build) (x86_64)

A minimal reproducible example and addition information is available via Bokeh Discourse Topic 7092.

https://discourse.bokeh.org/t/bokeh-embedded-session-limitations-race-condition-or-bug/7092

**Comment by bryevdv** [comment]
Determined that Tornado has a separate (and smaller) max websocket size for `websocket_connect` that `bokeh.client` uses. We will need to expose this as a configurable option.
