### ISSUE TITLE
New stateless plotting.py interface discussion

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1087]
From FD:

>I think we should basically make plotting.py completely unstateful which s a big change but it would solve all the weird order issues that can happen in notebooks and other things as well.

Let's keep the discussion in an issue so we can all contribute on the new plotting.py interface.

cc: @bryevdv, @damianavila, @kdodia

**Comment by bryevdv** [comment]
There is still more that could possibly be done to remove even more state from `plotting.py` but I think this particular issue has served its purpose.
