### ISSUE TITLE
[BUG] Link to export_svg() in export.rst is broken

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#10879]
In the [current dev-version user guide](https://docs.bokeh.org/en/dev/docs/user_guide/export.html#exporting-svg-images), the link in export.rst to  `export_svg()` is broken, while the link to `export_svgs()` seems to work fine:

![grafik](https://user-images.githubusercontent.com/39711796/106349455-c9739d80-6282-11eb-92e2-84bfcd412c20.png)

The reason for this is that the link in the rst-code should link to [bokeh.io.export.export_svg](https://docs.bokeh.org/en/dev/docs/reference/io.html#bokeh.io.export.export_svg) (instead of to bokeh.io.export_svg).

While this is easily fixed, I noticed something odd when digging around:

- The docstrings for both `export_png()` and `export_svgs()` seem to exist twice in [io.html](https://docs.bokeh.org/en/dev/docs/reference/io.html): For `export_png()`, both [bokeh.io.export_png](https://docs.bokeh.org/en/dev/docs/reference/io.html#bokeh.io.export_png) and [bokeh.io.export.export_png](https://docs.bokeh.org/en/dev/docs/reference/io.html#bokeh.io.export.export_png) are valid paths. Similarly for `export_svgs()`, both [bokeh.io.export_svgs](https://docs.bokeh.org/en/dev/docs/reference/io.html#bokeh.io.export_svgs) and [bokeh.io.export.export_svgs](https://docs.bokeh.org/en/dev/docs/reference/io.html#bokeh.io.export.export_svgs) are valid paths.

- The situation for `export_svg()` is different: This function's docstring only exists once, at [bokeh.io.export.export_svg](https://docs.bokeh.org/en/dev/docs/reference/io.html#bokeh.io.export.export_svg).

This inconsistency explains how the wrong path got included in #10565. This also means that the import statement for `export_svg()` should be `from bokeh.io.export import export_svg` (instead of `from bokeh.io import export_svg`).

Going forward I was wondering if it would make sense to make  `export_svg()`, `export_svgs()`, and  `export_png()` consistently use the same path: In export.rst, I would like to change the path of all three functions to `bokeh.io.export.export_xxx`, and correspondingly be consistent and change the import statements in all three examples to `from bokeh.io.export import export_xxx`.

However, if the difference between `export_svg()` on the one hand and `export_svgs()` and `export_png()` on the other hand is intentional, we might consider explaining the reasoning in export.rst.

**Comment by bryevdv** [comment]
> I would like to change the path of all three functions to bokeh.io.export.export_xxx, and correspondingly be consistent and change the import statements in all three examples to from bokeh.io.export import export_xxx.
 
I am 👎 on this. The intention is that `bokeh.io` is where the general public API lives. The submodules exist purely for ease of maintenance and users should not know about them at all, unless they need to use something advanced from the "dev" API.

**Comment by bryevdv** [comment]
@tcmetzger I will make a quick PR to add `export_png` to `bokeh.io` that will fix the broken link and bring to API structure in line with intention. I do think that we don't do a good job of splitting off the  docs for the "general public API" in `bokeh.io` from the complete reference for all the individual submodules (which do contain some advanced functions that some users will want to use). This is why the docs show up twice: once for `bokeh.io` and once for `bokeh.io.export`. 

This situation is not unique to `bokeh.io`. Most of the top level modules that are structured as a `dir/__init__.py` with submodules probably has a similar story. I think it would be good to open a follow-up issue to do discuss:

* what do we *want* to happen in terms of UX for "general" vs "dev" API docs
* how can we implement this

In the past we had considered a complicated system of decorators to both mark functions as general/dev and also record the function signature to try and maintain no API changes under test. That was way to unwieldy and was abandoned. But perhaps a scaled back system that just marks "dev API" functions could help with automating better docs. Can you make the follow up issue?

**Comment by tcmetzger** [comment]
@bryevdv Thanks for the explanation, that makes a lot of sense. I'd say the most important thing is for `export_svg()`, `export_svgs()`, and `export_png()` to be consistent!
I'll get the follow up issue started.
