### ISSUE TITLE
[BUG] Error with Hover callback

### ISSUE THREAD

**Issue by jordaniac89** [bokeh/bokeh#10870]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh==2.2.3
python==3.6
networkx==2.5

#### Description of expected behavior and the observed behavior
When trying to use a CustomJS callback with a networkx-generated graph, the browser gives me the following error on every mouse movement:

![Screen Shot 2021-01-26 at 2 38 43 PM](https://user-images.githubusercontent.com/8006059/105896034-50571a80-5fe4-11eb-8234-51da1c87e271.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```
G.add_edges_from(edges)

graph_renderer = from_networkx(G, nx.spring_layout, scale=1, center=(0, 0))
graph_renderer.node_renderer.glyph = Circle(size=15, fill_color='fill_color')
graph_renderer.edge_renderer.glyph = MultiLine(line_alpha=0.8, line_width=1)

plot = Plot(plot_width=400, plot_height=400,
            x_range=Range1d(-1.1, 1.1), y_range=Range1d(-1.1, 1.1))

bands_ds = ColumnDataSource(bands_df)
band_members_ds = ColumnDataSource(band_members_df)

hover_callback = CustomJS(
    args={'bands': bands_ds, 'band_members': band_members_ds},
    code='''
        console.log('here')
    ''')
node_hover_tool = HoverTool(
    callback=hover_callback,
    renderers=[graph_renderer.node_renderer, graph_renderer.edge_renderer]
    )

plot.add_tools(node_hover_tool, BoxZoomTool(), ResetTool())
plot.renderers.append(graph_renderer)
show(plot)


```

**Comment by bryevdv** [comment]
@jordaniac89 we require a *complete* minimal example, i.e. that can be pasted as-is in to an editor and immediately run, in order to investigate directly (and any necessary data to run as well).

**Comment by bryevdv** [comment]
@jordaniac89 just noting that without more information to be able to reproduce, this issue will close in three days.
