### ISSUE TITLE
Remove SRI integrity checks from js_resources.html template

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#10877]
So I'm still seeing the issue mentioned in https://github.com/bokeh/bokeh/issues/9773 appear randomly on some server deployments. Usually this is when a user has been developing an application locally and then switches to loading the deployed application, presumably for the same reason as mentioned in #9773, which is that it was loaded without the SRI hashes and then breaks when the SRI hashes are enabled.

My vote is to disable checking of SRI hashes since it causes silent errors which many users won't catch or know how to fix. I'd also prefer if this went into Bokeh 2.3.

Cc @bryevdv, @mattpap

**Comment by bryevdv** [comment]
I agree, but also think we should continue to compute and publish the hashes, and leave all the verify APIs, etc in place. Anyone that wants to use them in their own script tags can still do so, we just won't insert the hashes into any script loads we generate.

cc @jakirkham just to give you a heads up as I recall you spearheaded the initial issue to add these. Unfortunately we are at a point of throwing in the towel.

**Comment by bryevdv** [comment]
@philippjfr I do think trying to put this in right before a release is highly risky, I would prefer to push to 2.4 and make sure the next release cycle is not nearly as long.

**Comment by philippjfr** [comment]
>I do think trying to put this in right before a release is highly risky, I would prefer to push to 2.4 and make sure the next release cycle is not nearly as long.

Fair enough, I'm okay with pushing it.

**Comment by jakirkham** [comment]
cc @martey (for awareness)
