### ISSUE TITLE
[BUG] 'dashed' line style not working properly when using webgl

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#10876]
Bokeh 2.2.3
Python 3.8.5
Ubuntu 18.04
Notebook or Bokeh server
Latest Firefox or Chromium

I've tried webgl rendering to speed up my scatter plots, with great success. However I use a `line` in these plots and noticed that all possible values for the `line_dash` keyword argument work except `'dashed'`, although the legend item seems to adapt just fine.

This is a rather minor issue but I figured it should be noted somewhere.

Minimal code:

```py
from bokeh.plotting import figure
from bokeh.io import curdoc
from bokeh.layouts import gridplot

p1 = figure(title='No webgl')
p1.line([0, 1, 2, 3], [2, 5, 1, 6], line_dash='dashed', line_width=3, legend_label='Line1')

p2 = figure(title='webgl', output_backend='webgl')
p2.line([0, 1, 2, 3], [2, 5, 1, 6], line_dash='dashed', line_width=3, legend_label='Line1')

curdoc().add_root(gridplot([p1, p2], ncols=2, merge_tools=True))
```
![dashed_line](https://user-images.githubusercontent.com/49269671/106299749-d8902680-6255-11eb-866f-28cc3ee8172b.png)

**Comment by bryevdv** [comment]
> although the legend item seems to adapt just fine.

IIRC legends are not rendered using webgl regardless of the main plot.
