### ISSUE TITLE
Docs: remove reference of outdated 'nbserverproxy' 

### ISSUE THREAD

**Issue by marckassay** [bokeh/bokeh#10897]
Preamble to this issue: 
I created a PR that I have now abandon since it merged off of an outdated branch. But more importantly I wasn't, and still haven't, been able to verify my proposed change (see [diff](https://github.com/marckassay/bokeh/commit/84ca7351c405ea77c2e27534818ebe72e5a673ab#diff-8c45079081b85c480519fdc2262a3d9b136b234bfe2dd80f8e2c4aa7d82e0340)). All text below is from my original PR.

Reason for propose change:

> Note: This project used to be called nbserverproxy. As nbserverproxy is an older version of jupyter-server-proxy, uninstall nbserverproxy before installing jupyter-server-proxy to avoid conflicts. - [ref](https://github.com/jupyterhub/jupyter-server-proxy#jupyter-server-proxy)

I haven't verified that this works, since I'm in the midst of developing a solution to a larger issue where this was a subset of it.

Additional doc:
[jupyter-server-proxy - installation](https://github.com/jupyterhub/jupyter-server-proxy/blob/master/docs/install.rst)

**Comment by bryevdv** [comment]
Marking as `discussion` until someone can confirm.

**Comment by bryevdv** [comment]
Someone one the discourse confirmed this worked, and also said they might be able to submit at PR for it. 

https://discourse.bokeh.org/t/cannot-embed-bokeh-server-in-notebook-through-jupyterhub/7178/5
