### ISSUE TITLE
[FEATURE] Add custom_tooltip and custom_icon to all tools (not implemented in SelectTools)

### ISSUE THREAD

**Issue by aerow610** [bokeh/bokeh#10914]
Currently, tools such as the `CrosshairTool` and `BoxSelectTool` do not have the ability to set a custom tooltip or custom icon. I have really enjoyed having these features in the PointDrawTool and think that it would be nice to have them across all of the different tools. See the discussion about the issue from Discourse below:
[Issue from Discourse - 7222](https://discourse.bokeh.org/t/custom-tooltip-icon-not-implemented-in-selecttools/7222)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the ability for SelectTools (and all other tools as well) to be able to set a `custom_tooltip` and `custom_icon`

**Describe alternatives you've considered**
Subclassing the tools that don't have this ability and hard coding in the location for each icon

**Additional context**
n/a

**Comment by bryevdv** [comment]
@mattpap AFAIK there are no obvious blockers to this, but let me know if there are considerations I am not aware of.

**Comment by bryevdv** [comment]
Need to check current status (possibly done?)

**Comment by mattpap** [comment]
Currently there's `Tool.description` (instead of `custom_tooltip`), but customizing icons needs to be implemented.
