### ISSUE TITLE
[BUG] Deprecate broken HSL objects 

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#10919]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh: 2.3.0dev13
Python: 3.8.6
Win 10

#### Description of expected behavior and the observed behavior
Expected: I can use a (correctly defined) HSL object and an RGB object interchangably
Observed: I have to convert HSL to RGB to render a glyph

This is connected to my work in #10899.

#### Complete, minimal, self-contained example code that reproduces the issue

A working example with an RGB object:
```
from bokeh.plotting import figure, show
from bokeh.colors import RGB
col = RGB(255,0,0,0.5)
p = figure(title = "RGB")
p.circle(2, 5, size=100, color=col)
show(p)
```

An example with HSL that I would expect to work, but which gives me a ValueError:
```
from bokeh.plotting import figure, show
from bokeh.colors import HSL
col = HSL(260, 1, 0.7, 0.5)
p = figure(title = "HSL - ValueError")
p.circle(2, 5, size=100, color=col)
show(p)
```

Workaround: if I use the `to_rgb()` method, everything works:
```
from bokeh.plotting import figure, show
from bokeh.colors import HSL
col = HSL(260, 1, 0.7, 0.5).to_rgb()
p = figure(title = "HSL - workaround")
p.circle(2, 5, size=100, color=col)
show(p)
```

If this behavior is intentional, we might consider adding an explanation somewhere in the docs.

**Comment by bryevdv** [comment]
I think this largely indicates that no one has ever used this in nearly ten years, so maybe it should just be deprecated abd removed at 3.0

**Comment by tcmetzger** [comment]
Also: The method `to_hsl()` in rgb.py returns a HSL object - however, the docstring erroneously says it returns an RGB object

**Comment by tcmetzger** [comment]
@bryevdv Very good point, that makes a lot of sense. How about:

- I don't mention RGB and HSL objects in #10899 (I was initially planning to include those in the list of options for defining colors in https://docs.bokeh.org/en/latest/docs/user_guide/styling.html#specifying-colors)
- I use #10899 to quickly fix the docstring for to_hsl() in rgb.py

What do you think?

**Comment by bryevdv** [comment]
@tcmetzger That sounds fine, as long as we are touching these things I'd really like to deprecate HSL at this time as well. cc @bokeh/dev

**Comment by BenjaminPelletier** [comment]
There is a comment in here about no one using HSL for 10 years, so I just wanted to add my 2 cents.  I am new to Bokeh and am using HSL and am sad about the spewing of deprecated messages and that it will be removed in a future version.  Even if the class will be removed, at least leave some way/function to compute an RGB color knowing HSL values.

**Comment by jbednar** [comment]
The [HoloViews HSV component](https://holoviews.org/reference/elements/bokeh/HSV.html) may be useful...

**Comment by KEClaytor** [comment]
@BenjaminPelletier same, I'm currently using HSL because I want to programmatically value lightness, I'm using the standard library [`colorsys`](https://docs.python.org/3/library/colorsys.html) to do the conversion; `c = bokeh.colors.RGB(*colorsys.hls_to_rgb(hue, 0, 1))` but then the call to `c.lighten(value)` converts it to `bokeh.colors.HSL` internally and throws the stream of errors anyway! I imagine once it's fully depreciated those errors will go away.
