### ISSUE TITLE
[BUG] 'freehand_draw' is not in name space for tools

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#10912]
#### software version
bokeh v.2.2.3

#### Description
I tried the `"FreehandDrawTool"` which is working fine if it is imported as a model. But right now it is not possible to activate the tool by the name "freehand_draw" because the name is not in the name space for tools. The two lines below raise a ValueError saying `unexpected tool name 'freehand_draw'`.
```
from bokeh.plotting import figure
p = figure(tools="freehand_draw")
```

**Comment by bryevdv** [comment]
Thanks for the catch @mosc9575 would you like to submit the PR to update this? The relevant code sections are here on the python side:

https://github.com/bokeh/bokeh/blob/b85c299ceb7ae4f51eff19cbbc43bcd89805b2de/bokeh/models/tools.py#L1625

Then also adding a line like this:
``` 
this.register_alias("freehand_draw", () => new FreehandDrawTool())
```
in [`freehand_draw_tool.ts`](https://github.com/bokeh/bokeh/blob/branch-2.3/bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts) (You can see an example for comparison in another tool [here](https://github.com/bokeh/bokeh/blob/9dcbafe7a6b72d8e740ba85a1a1e0804080f6d9b/bokehjs/src/lib/models/tools/gestures/box_select_tool.ts#L115))

**Comment by BLuchterhand** [comment]
Hi! I'm looking to get a bit of experience with Git contributions, and this looks like a fairly straight-forward issue to get some introduction to Bokeh. How can I work on this?

**Comment by mattpap** [comment]
There's already PR #10917 open fixing this issue.

**Comment by bryevdv** [comment]
@BLuchterhand look for other `good First issue` issues and we are happy to help walk through things.

**Comment by bryevdv** [comment]
@mosc9575 did you intend to complete this PR? The alias also needs to be added on the python side as described here https://github.com/bokeh/bokeh/issues/10912#issuecomment-780754592
