### ISSUE TITLE
bokeh_releases needs to process files more carefully

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10934]
If there is ignored junk in `source/docs/releases` (e.g. an errant `.vscode` directory) then the extension will blow up. It should take care to only process `*.rst` files and ignore others. 

https://github.com/bokeh/bokeh/blob/b8b9ccbc3e4d2869b2c2a50f7a46b3824565f15c/bokeh/sphinxext/bokeh_releases.py#L102-L103

**Comment by enkeyz** [comment]
Would like to work on this one.

**Comment by bryevdv** [comment]
@enkeyz that would be fantastic, the main thing is to get set up to build the docs. Once you can build the docs locally, you can make and test the changes described above. The dev docs have information about getting set up:

https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html

https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html#building-bokeh-s-documentation

I would say start going through that and let us know and places you might get stuck along the way and we will help out!

**Comment by enkeyz** [comment]
I mean, it's an easy fix: `versions = [x.rstrip(".rst") for x in listdir(join(app.srcdir, "docs", "releases")) if x.endsWith(".rst")] `

Will make a PR tomorrow.

**Comment by enkeyz** [comment]
Btw, how one can run all tests? Didn't find info about it in the docs.
