### ISSUE TITLE
Bring up branch-2.4

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10932]
This is just a reminder that `branch-2.4` will need to be rebased, or late 2.3 commits be merged into it. Last round we neglected to bring the 2.2 CHANGELOG entries into the branch (I just happened to notice the other day, so things are now up to date). 

I might make some new labels to support this. I'd like to make sure there is some minimal process in place to ensure that branch hygiene is maintained, but I don't think issues like these need to get dumped into the automated CHANGELOG, since they are of zero interest to users. (Alternatively: we could stop putting `task` in the CHANGELOG and reserve that label for repo/project related things that don't get added there... cc @tcmetzger for thoughts)

**Comment by bryevdv** [comment]
`sphinx/versions.json` was also out  of date and updated. We do need to figure out more process around branch hygiene and movement.

**Comment by bryevdv** [comment]
FYI I have updated the default branch to `branch-2.4`

**Comment by bryevdv** [comment]
Hrm, this does not seem to be done, `branch-2.4` is missing the lastest 2.3 tags:
```
68dd7d8a1 (HEAD -> branch-2.4, origin/branch-2.4) Replace JS var with let/const across the codebase (#10930)
379e446ed Bring 2.4 branch up to date (#10944)
a4a807585 Update user guide (annotations.rst and others)
18f3e470c add missing 2.2.x changelog entries
6f3f7dc96 Merge deployment staging branch staging-2.3.0rc2
8886baa66 (tag: 2.3.0rc2) Deployment updates for release 2.3.0rc2
```

In general I would *not* expect a newer branch to to have all the o

**Comment by mattpap** [comment]
I suggested in the PR to use "rebase and merge" which (I guess; I never actually used it) would have resolved the issue. Anyway, I think it is early enough that we can and should update the branch, with:
```
git rebase --onto origin/branch-2.3 379e446ed3c225f3ebc5daea39c1aa5126d12531
```

**Comment by bryevdv** [comment]
OK, we will have to temporarily un-protect the branch. I will do this this morning.

**Comment by bryevdv** [comment]
This id done.
