### ISSUE TITLE
RadioGroup checkboxes stay the same size when zooming in firefox

### ISSUE THREAD

**Issue by pat-schmitt** [bokeh/bokeh#10937]
#### ALL software version info
bokeh 2.2.3
firefox 85.0.1
chrome 88.0.4324.182

#### Description of expected behavior and the observed behavior

When you zoom in/out into a bokeh app using the keys 'Ctrl' and '+/-' the checkboxes stay the same size when using firefox. This leads to a misalignment of the text and the checkboxes. When using for example chrome the checkboxes change their size with no misalignment with the text. This can also be observed for a CheckboxGroup (not shown here).

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import show
from bokeh.models import CustomJS, RadioGroup

LABELS = ["Option 1", "Option 2", "Option 3"]

radio_group = RadioGroup(labels=LABELS, active=0)
radio_group.js_on_click(CustomJS(code="""
    console.log('radio_group: active=' + this.active, this.toString())
"""))

show(radio_group)

```

#### Screenshots or screencasts of the bug in action
 Firefox:
![zooming_firefox](https://user-images.githubusercontent.com/50843444/108816586-b53b6b80-75b6-11eb-9b5e-7286a03be6cc.gif)

Chrome:

![zooming_chrome](https://user-images.githubusercontent.com/50843444/108815961-a1433a00-75b5-11eb-9040-007994ed28d6.gif)

**Comment by bryevdv** [comment]
This seems like a FF issue, to be honest. @pat-schmitt do you have any examples of FF behaving the way Chrome does outside of Bokeh?

**Comment by pat-schmitt** [comment]
No sorry, I have no other examples by the hand

**Comment by pat-schmitt** [comment]
With Firefox version 89.0 this is fixed
