### ISSUE TITLE
Changelog process / policies

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10949]
cc @tcmetzger @bokeh/dev 

I'd like to discuss how best to keep up the CHANGELOG.  My current somewhat unformed observations:

* I think we put too much in the CHANGELOG. There are always tasks that really only have to do with repo or infra maintenance, or build changes, etc. I just don't think these are of any interest at all to users. I think we could either:
  - make a new label to explicitly exclude something from the automated CHANGELOG
  - re-purpose `task` to mean "things that aren't for the CHANGELOG
  or other ideas?

* The CHANGELOG on `branch-2.3` was missing all the later `branch-2.2` changes. We need to figure out some procedures to help ensure branch hygiene is maintained. I think trying to automate this is probably more trouble than it is worth, but e could probably add some *validation* that at least warns us when things are missing when they shouldn't be.

**Comment by jbednar** [comment]
I agree with keeping a CHANGELOG user focused and omitting maintainer tasks.

**Comment by tcmetzger** [comment]
I don't know much about what automation is currently happening, but I agree that the CHANGELOG should be user focused. Maybe we could end up having two labels - something like `task-maintenance` (makes it possible to find all related changes) and something `task-changelog` (additional tag that means this object gets included in the changelog and the repsective automations)?

**Comment by p-himik** [comment]
A very common and IMO the best approach is to force each PR to also add a line to the CHANGELOG under the section `Unreleased`. Unless, perhaps, it has a specific label to denote that it's something internal and should not have a record in the changelog.

Later, during the release phase, that `Unreleased` is replaced with the actual version number and a new and empty `Unreleased` section is added.

I haven't been happy with the Bokeh changelog at all. In fact, I think that putting commit messages there should be avoided at all costs. This automation just shifts the onus on the users.
Commits are for the development log, for developers.
Records in CHANGELOG are for the user-facing changers, for users.
These two can have zero lines in common, and that is fine.

**Comment by p-himik** [comment]
Ah, here's a relevant section in the document that I was trying to find: https://keepachangelog.com/en/1.0.0/#effort
In fact, the whole document is worth reading.

**Comment by bryevdv** [comment]
Hi @p-himik 👋  I am familiar with that document, and I agree that a project needs all the things listed there. And in fact my response is that we have all of those things, we just don't happen to call it "changelog". Our release notes page:

https://docs.bokeh.org/en/latest/docs/releases.html

is:

* reverse chronological listing of all releases
* with ISO dates
* curated to highlight important user-focused information
* contains information about deprecations and migrations

We use that page because we want to be able to link into docs, have syntax-highlighted code snippets, collapsible tables for SRI hashes, etc. 

I'm -1 on changing the current CHANGELOG text file to be more like the curated release notes:

* would make the doc itself internally inconsistent,  with the first 10 years of content being wildly different from new content
* would make more work (the opposite of what I want) for curation, with results that are almost duplicative (but *not quite*, even wose)

So now thinking about it in this contexts, I think my new proposal would be this then:

* derive the CHANGELOG by a simple concatenation of all release notes `.rst` files at every release

This would be a simple procedure and we could simplify the curent `milestones.py` script to just do issue/pr validation and jettison all the code for changelog generation. 

What we might want to do is 

To keep the trickle of funds coming in from Tidelift, we do need to keep a CHANGELOG file (or do work to use their API or manual upload, neither of which I want to do) but they have "limited support" for ReST format so I think this would be the simplest option. GitHub will also render .rst files, you can see what one looks like here:

https://github.com/bokeh/bokeh/blob/branch-2.4/sphinx/source/docs/releases/2.3.0.rst

What we might want to do is lightly edit the existing .rst to be more consistent in their structure, remove any cruft, and make any adjustments/compromises that improve the "plain text" version in the CHANGELOG file. (We *might* have to change teh name to `CHANGELOG.rst` too)

Thoughts?

**Comment by bryevdv** [comment]
As for unreleased changes, we could add an `unreleased.rst` to the `source/docs/releases` folder. This would actually solve the issue we have now where someone has to manually create a new `x.y.z.rst` as a *first* step to recording any information. We coudl even automate the process of copying the content of `unreleased.rst` (and clearing it out) to the a new `x.y.z.rst` as part of the release. But that woudl also be simple to do.

**Comment by p-himik** [comment]
Oh, I completely forgot about the Releases web page, right! Deriving the changelog from cleaned up and structured release description files sounds like a good idea to me. As well as having `unreleased.rst`.
There will probably have to be a test or two to make sure that the rst files' structure is exactly as expected.

**Comment by bryevdv** [comment]
I'll make a separate new issue linking to the discussion.
