### ISSUE TITLE
Automate python min-version and requirements in docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10946]
I'd like to make small sphinx extensions (or whatever works simplest) to automate scraping the python min version and hard requirements from `setup.py` so that the manual updates like in #10945 are not necessary

cc @tcmetzger

**Comment by bryevdv** [comment]
As an aside it might make the most sense to start using `poetry` with a `pyproject.toml` so that the information above is available in a declarative configuration instead of an executable `setup.py`

@shughes-uk might have some advice on switching

**Comment by tcmetzger** [comment]
Absolutely, having this information maintained automatically would be great!
