### ISSUE TITLE
Bookmarked Views

### ISSUE THREAD

**Issue by helloAliens** [bokeh/bokeh#1094]
When viewing saved plots in the bokeh-server, I often find myself wanting to save the current view (current pan, zoom, etc) so that I could show that exact view to another person at a later time. It would be nice if one could save/bookmark the current view and label it. Allowing more than one bookmarked view would be nice too. Providing direct links to each view via HTML link anchors would help users direct attention to particular views.

**Comment by bryevdv** [comment]
I'm going to close this. It references the old (gone) `bokeh-server` and the current bokeh server can accept generic HTTP request arguments, which could be used to implement a bookmarking scheme that is specific to a given bokeh app. Bokeh apps are too general to implement a bookmarking "generic" bookmarking scheme that would apply or be appropriate in all cases.
