### ISSUE TITLE
Minor cleanup after PR #10939

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10941]
There were some minor comments left on https://github.com/bokeh/bokeh/pull/10939

**Comment by bryevdv** [comment]
Not sure why GH is lately no longer closing issues automatically anymore

**Comment by mattpap** [comment]
I'm not sure. I works on and off again. I checked all recent PRs, and they have correct `fixes #nnnnn`, but no linked issues, which is the requirement for closing (even if it says it will close when hovering over `fixes`). Linking should happen automatically when `fixes` is added.

**Comment by bryevdv** [comment]
OK, will just assume it's a sporadic problem that fix itself, and check accordingly for now. If we are still seeing it in a few weeks I'll email gh support
