### ISSUE TITLE
Update versioneer version?

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#10957]
We currently use version 0.18 of [Versioneer](https://github.com/python-versioneer/python-versioneer). According to the docstring in versioneer.py (in the root of the Bokeh repo), versioneer officially only supports Python up to version 3.6. With support for Python 3.6 to be dropped in Bokeh 2.4, we might consider updating versioneer to the most recent version 0.19.

This is certainly low priority as things are still working as they should, and most likely will continue to work.

See https://github.com/bokeh/bokeh/pull/10945#issuecomment-786081165, cc @bryevdv

**Comment by bryevdv** [comment]
Let's plan to have it done by 2.4 There's nothing that could break in a way that would effect released packages, but it could break in a "stressful unplanned fire drill" kind of way.

**Comment by bryevdv** [comment]
not sure why GH Is not auto-closing issues tonight
