### ISSUE TITLE
[FEATURE] Live server

### ISSUE THREAD

**Issue by tom-programming** [bokeh/bokeh#10977]
Having to reload a server every time a file is updated is cumbersome

It would be wonderful to have something akin to NodeJS' live-server. The program watches for filesystem changes and reloads the server when the python files are changed. This can enable a higher level of continuous development.

Certainly there are ways to do it outside of Bokeh, but having this feature in the Bokeh server would probably be helpful.

**Comment by mattpap** [comment]
Run bokeh server with `--dev`. See issue #4236.

**Comment by axil** [comment]
For me,

```
bokeh.exe serve --dev myapp.py
```
results in

```
ERROR: list index out of range
```

which bails out immediately with no further details or any clues of how to debug it

and 

```
bokeh.exe serve --dev --show myapp.py
```
(despite being discouraged [here](https://discourse.bokeh.org/t/prevent-hot-reload-with-dev-to-open-a-new-browser-tab-at-every-save/10681)) manages to start the app but then after the file is modified it breaks with equally useless

```
Error while finding module specification for '__main__' (ValueError: __main__.__spec__ is None)
```

I'm using myapp from the `bokeh serve` [tutorial](https://docs.bokeh.org/en/latest/docs/user_guide/server/app.html)

Running against the `bokeh==3.2.2` on Windows 10.

**Comment by bryevdv** [comment]
`--dev --show` works as expected for me on OSX but apparently there is some regression in the other case. @axil Please open a new bug report with full details. This two year old issue is (was) about something else entirely.

**Comment by axil** [comment]
Done https://github.com/bokeh/bokeh/issues/13371
