### ISSUE TITLE
[BUG] `plot_width` no longer a `Figure` property in bokeh 2.3.0

### ISSUE THREAD

**Issue by jrbourbeau** [bokeh/bokeh#10978]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

- bokeh 2.3.0
- Python 3.8.8
- Mac OSX

#### Description of expected behavior and the observed behavior

Previously, for example with bokeh 2.2.3, `plot_width` was a property of `Figure`. However, this is no longer the case in bokeh 2.3.0.

For context, Dask uses `figure().properties()` for keyword argument validation in some of it's plotting utilities. There may be a workaround we can implement on the Dask side, but I still wanted to surface this change regardless. 

#### Complete, minimal, self-contained example code that reproduces the issue

With bokeh 2.2.3:

```python
In [1]: import bokeh

In [2]: bokeh.__version__
Out[2]: '2.2.3'

In [3]: from bokeh.plotting import figure

In [4]: "plot_width" in figure().properties()
Out[4]: True
``` 

With bokeh 2.3.0:

```python
In [1]: import bokeh

In [2]: bokeh.__version__
Out[2]: '2.3.0'

In [3]: from bokeh.plotting import figure

In [4]: "plot_width" in figure().properties()
Out[4]: False
```

#### Stack traceback and/or browser JavaScript console output

N/A

#### Screenshots or screencasts of the bug in action

N/A

**Comment by bryevdv** [comment]
@jrbourbeau The change was to resolve on `width` and `height` instead, to make plots consistent with every other layout-able, but leave `plot_width` and `plot_height` as (plain-Python) property aliases for compatibility, but evidently that was not sufficient.

**Comment by bryevdv** [comment]
@mattpap do the new actual (Bokeh) property aliases show up in `properties`? If not, could they? That doesn't seem unreasonable as a policy, and we could put that change in a 2.3.1

**Comment by bryevdv** [comment]
It looks like we could potentially just add `__property_aliases__` to the results by default (maybe an `exclude_aliases` option to omit them). But I don't know offhand if doing that would break anything elsewhere. 

We would also have to apply this change to `branch-2.3` and and a slightly different change to `branch-2.4` since the "simplify properties" PR has already landed.

**Comment by bryevdv** [comment]
@jrbourbeau Do you think that a change to use `width` and `height` on the Dask side is sufficient, then? If so I will close this with `noaction`. (Of course if you need time to decide that we can leave it open in the mean time)

**Comment by mattpap** [comment]
> do the new actual (Bokeh) property aliases show up in properties? If not, could they? That doesn't seem unreasonable as a policy, and we could put that change in a 2.3.1

They do in bokehjs (mapping to actual properties). However, bokehjs works exclusively with property descriptors, so there is no room for e.g. accidentally serializing both. I suppose bokeh should work the same, but it may be easier said than done.

**Comment by jrbourbeau** [comment]
> Do you think that a change to use width and height on the Dask side is sufficient, then?

I think it should be, but is it okay if we keep this issue open until https://github.com/dask/dask/pull/7297 is merged?

**Comment by bryevdv** [comment]
OK I will go ahead and close this now, thanks @jrbourbeau
