### ISSUE TITLE
Hover Tool displaying only up to millisecond level granularity

### ISSUE THREAD

**Issue by sapnads** [bokeh/bokeh#10981]
Hi, I am using HoverTool to get the y-axis values as well as the time stamp in x-axis displayed. I tried %6N in the datetime formatting for hover, however it pads 0's in the end in place of microseconds. I am working on a project that needs the time displayed up to the microsecond level granularity. Is there a solution or workaround to get this working with Hover in Bokeh?

Thanks!

**Comment by bryevdv** [comment]
@sapnads  please add all the information asked for (versions, etc) as well as a complete, minimal reproducer to investigate.

**Comment by sapnads** [comment]
Sure sorry about that. Bokeh version used was 2.1.1

The following code didn't work and even though the timestamp itself had all 6 values of decimal upto microseconds it displayed the time with 0's after the first 3 decimal places. 

HoverTool(tooltips=[('timestamp', '@timestamp{%Y-%m-%d:%H:%M:%S.%6N}'), ('{}'.format(y_label), '@{}'.format(y_label))], formatters={'@timestamp': 'datetime'}, mode='mouse')

**Comment by bryevdv** [comment]
@sapnads first off you should try using the latest version 2.3 since the any issue might be fixed there. 

Second, we need a [Minimal Reproducing Example](https://stackoverflow.com/help/minimal-reproducible-example) i.e. a ***complete*** script, including any synthetic or sample data necessary to run it. With hundreds of thousands of users and only a handful of maintainers, it is absolutely imperative that reports include all the information necessary to investigate without *speculation, guessing, or "filling in the gaps"*.

**Comment by hegde-anish** [comment]
Hi,

I have the same issue as @sapnads. 

I'm using the following versions.  
       * bokeh --> 2.3.0
       * holoviews --> 1.14.2
       * pandas --> 1.1.4
       * jupyterlab --> 3.0.9
       
This is the minimal reproducing script.

`import pandas as pd
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource, DatetimeTickFormatter
from bokeh.models.tools import HoverTool
from bokeh.resources import INLINE
import bokeh.io
from bokeh import *
bokeh.io.output_notebook(INLINE)


df = pd.DataFrame()

# Timestamp is initially in epochs
df['timestamp'] = [1608686202075379, 1608686202182350, 1608686202225138, 1608686202465283, 1608686202875081]
df['variable'] = [2.4, 7.2, 9.6, 1.7, 5.8]

# Converted to datetime 
df['timestamp'] = pd.to_datetime(df.timestamp, unit='us')


source = ColumnDataSource(df)
p = figure()

p.circle(x='timestamp', y='variable', source=source, size=10, color='green')
p.xaxis.formatter=DatetimeTickFormatter()

hover = HoverTool(tooltips=[('timestamp', '@timestamp{%Y-%m-%d:%H:%M:%S.%6N}'), ('variable', '@variable{0.3f}')], formatters={'@timestamp': 'datetime'}, mode='mouse')

p.add_tools(hover)

print(df)
show(p)`

As you can see from the output below, `timestamp` column in `df` has data of type datetime and has precision up to microseconds. However the hovertool truncates this to milliseconds and appends 0s at the end. 

![image](https://user-images.githubusercontent.com/20843188/109864193-637a8d00-7c17-11eb-914f-4ea0c60cbd7f.png)

**Comment by bryevdv** [comment]
@hegde-anish @sapnads Is there some documentation somewhere that states that this is expected to work in Bokeh? If so, can you point us at it? 

For hover tools, `"datetime"` formatting is handled by the [`timezone`](http://bigeasy.github.io/timezone/) library, and I am not sure it supports anything beyond ms, in which case neither can we. But that should be made clear in the documentation. I would say that using `CustomJSHover` is probably the best option to format values that require more precision.

**Comment by sapnads** [comment]
Do you have a sample on how to use CustomJSHover for this specifc use case?

**Comment by bryevdv** [comment]
Nothing specific to that. `CustomJSHover` is a generic feature that allows you implement arebitrary formatting using snippets of JavaScript code. Happy to talk about it more but the appropriate place for usage/help discussion is the [project Discourse](https://discourse.bokeh.org/)

**Comment by bryevdv** [comment]
I do note that the User Guide here:

https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields

states

> "datetime" Provides formats for date and time values. The full set of formats is listed in the DatetimeTickFormatter reference documentation.

And the ref docs for `DatetimeTickFormatter` state:

> Nanosecond as a decimal number, zero-padded on the left (range 000000000-999999999). Supports a padding width specifier, i.e. %3N displays 3 leftmost digits. ***However, this is only accurate to the millisecond level of precision due to limitations of timezone.***

@tcmetzger do you think there are any ways/places we can make this more clear? If not I think this can be closed with no action.

**Comment by tcmetzger** [comment]
In my oppinion, the [paragraph about %N in the reference guide](https://docs.bokeh.org/en/latest/docs/reference/models/formatters.html#bokeh.models.formatters.DatetimeTickFormatter) is still the best place to have this information. In the[ "Formatting tooltip fields" section of the User Guide](https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields), there is also a link to the `CustomJSHover` model.

So, I'd be OK with leaving the docs as they are.

**Comment by azjps** [comment]
While not ideal, I'll mention that a simple workaround is to have a separate `"microseconds"` or `"nanoseconds"` column in your `ColumnDataSource` , e.g. via 
```python
df['timestamp'] = pd.to_datetime(df.timestamp, unit='us')
df["microseconds"] = df["timestamp"].dt.microsecond
```
and then reference it in your tooltip via something like `@timestamp{%Y-%m-%d:%H:%M:%S}.@microseconds{%06d}` and `formatters={"@timestamp": "datetime", "@microseconds": "printf"}`.

When plotting a lot of time series its a bit annoying to have to add all these additional redundant `microseconds` columns, but fortunately it doesn't require much effort to write.

There's a somewhat related discussion in https://github.com/bokeh/bokeh/issues/1135.
