### ISSUE TITLE
Replace plot_width and plot_height with width and height

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10980]
There are still many examples and areas of the docs that use the original `plot_width` and `plot_height` properties. We should update all of these to use `width` and `height` instead. 

cc @tcmetzger

**Comment by tcmetzger** [comment]
This could be a good first issue - I'll also keep it on my to do list!

**Comment by bryevdv** [comment]
I waffled about adding `good first issue`. It definitely would be a good first issue, but I do think it should land for 2.4 and usually we reserve GFI for things that don't have a deadline. But we could add GFI, and if no-one's picked it up as 2.4 nears we just do it ourselves.

**Comment by satishjasthi** [comment]
Hi  bryevdv

Can I take up this issue

**Comment by tcmetzger** [comment]
@satishjasthi Absolutely, we'd appreciate a PR from you! 
You can find more information on contributing to the docs here: https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html Let me know if you have any questions getting set up!

**Comment by bryevdv** [comment]
@tcmetzger there is already #10989 (which needs some work still) I did not realize it was not already linked

**Comment by mattpap** [comment]
How is this `completed` if there is 125 instances of `plot_width` in `examples/` alone?
```
$ git grep plot_width examples | wc -l
125
```

**Comment by tcmetzger** [comment]
@mattpap You are right - my commit in the other PR is only a partial fix, since I only focussed on `figure()` (excluding Jupyter notebooks and tests). I did not want to do all the updates in that one PR, so I'll do some follow-up PRs. I also found that `plotgrid()` still seems to expect `plot_width` and `plot_height` - that might warrant its own issue.
![grafik](https://user-images.githubusercontent.com/39711796/114312776-b104d800-9aa8-11eb-9907-8124bff04f09.png)

**Comment by bryevdv** [comment]
I was in a hurry and closed it in error, but I think @tcmetzger has a handle on taking care of things in another PR or two

**Comment by mattpap** [comment]
> I also found that `gridplot()` still seems to expect plot_width and plot_height - that might warrant its own issue.

At least `width` and `height` should be added to `gridplot()` and perhaps `plot_*` deprecated, but let's start a new issue to discuss that.
