### ISSUE TITLE
[BUG] can't update image with ColumnDataSource in 2.3.0

### ISSUE THREAD

**Issue by bjarthur** [bokeh/bokeh#10993]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.3.0, python 3.7.1, mac OS 10.15.7, chrome 88.0.4324.192

#### Description of expected behavior and the observed behavior
an example straight from the docs gives this image, but when i modify it to use a ColumnDataSource, i get an entirely blank page
<img width="604" alt="Screen Shot 2021-03-03 at 3 23 06 PM" src="https://user-images.githubusercontent.com/1538268/109867367-659f1480-7c34-11eb-9da6-bbada77a7824.png">

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np

from bokeh.plotting import figure, output_file, show

output_file("image.html", title="image.py example")

x = np.linspace(0, 10, 250)
y = np.linspace(0, 10, 250)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx)*np.cos(yy)

### straight from the docs, and works
p = figure()

p.image(image=[d], x=0, y=0, dw=10, dh=10, level="image")
p.grid.grid_line_width = 0.5

show(p)

### modified to use a ColumnDataSource, and does not work on 2.3.0
### this, or sth very similar, used to work in 2.2
p2 = figure()

source = ColumnDataSource(data=dict(image=[]))
glyph = p2.image('image', source=source, level="image")

source.data.update(image=d)
glyph.glyph.x=0
glyph.glyph.y=0
glyph.glyph.dw=10
glyph.glyph.dh=10

show(p2)
```

possibly related to  https://github.com/bokeh/bokeh/issues/10942 ?

**Comment by bryevdv** [comment]
@bjarthur this usage is not correct. The values of a CDS are all columns, and that includes for images, which should be a list or sequence of images. You need
```
source.data.update(image=[d])
```
This is consistent for every situation in Bokeh, with no exceptions. CDS values are always lists/sequences of other values (even if those other values are themselves 2d image arrays).

In the future, please refer usage-related questions to the project [Discourse site](https://discourse.bokeh.org) first. If it is determined there is a bug we will refer you to the tracker.
