### ISSUE TITLE
[FEATURE] Add a min_exponent to only show axis labels as exponents for number higher than this exponent

### ISSUE THREAD

**Issue by ethankruse** [bokeh/bokeh#11007]
I was going to add this to #11006, but this feels more like a feature request than a specific bug with the log axis numbering.

Is it possible to add an equivalent to [matplotlib's](https://matplotlib.org/stable/tutorials/introductory/customizing.html) `min_exponent`, which allows you to set an exponent value such that log values are only displayed as exponents if the value is above this parameter.

For example, simple code in matplotlib:

```
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

mpl.rcParams['axes.formatter.min_exponent'] = 3

plt.close('all')

plt.figure()

xx = 10.**np.arange(-6,6,0.1)
yy = np.random.randn(xx.size)

plt.scatter(xx, yy)

plt.xscale('log')
```

allows x-axis values between (10^-3, 10^3) to be regular decimal numbers.

<img width="532" alt="Screen Shot 2021-03-05 at 3 10 20 PM" src="https://user-images.githubusercontent.com/6944089/110168253-e856d980-7dc4-11eb-9d79-13194983c440.png">

Currently (both in 2.3.0 and 2.2.X), I've been using a custom script that sets the min and max exponents. Taking the [doc example](https://docs.bokeh.org/en/latest/docs/user_guide/plotting.html#log-scale-axes) and adding my script:

```
def log_axis_labels(min_tick=-2.001, max_tick=3.):
    """
    Bokeh can't do subscript or superscript text, which includes scientific
    notation in axis labels. This is a hack script that uses unicode
    superscript values and manually creates pseudo-scientific notation axis
    labels. Any values within log10(min_tick) and log10(max_tick) will be
    displayed as normal, while outside those bounds in either direction will
    be converted to scientific notation.

    Parameters
    ----------
    min_tick : float, optional
        Maximum small log(10) value that will display in scientific notation
        instead of the full decimal representation. The default is -2.001,
        meaning axis labels will go from 9x10^-3 to 0.01.
    max_tick : float, optional
        Minimum large log(10) value that will display in scientific notation
        instead of the full decimal representation. The default is 3, meaning
        axis labels will go from 999 to 10^3.

    Returns
    -------
    str:
        JavaScript code function that generates the appropriate tick labels.

    """
    return f"""
var logtick = Math.log10(tick);
if ((logtick > {min_tick}) && (logtick < {max_tick})){{
    return tick.toLocaleString();
}} else {{
    var power = Math.floor(logtick);
    var retval = 10 + (power.toString()
             .split('')
             .map(function (d) {{ return d === '-' ? '⁻' : '⁰¹²³⁴⁵⁶⁷⁸⁹'[+d]; }})
             .join(''));
    var front = (tick/Math.pow(10, power)).toPrecision(2).toString().slice(0,3);
    
    if (front == '1.0'){{
        return retval
    }}
    else if (front.slice(1,3) == '.0'){{
        return front[0] + 'x' + retval
    }}
    
    return front + 'x' + retval
}}
    """


from bokeh.plotting import figure, output_file, show
from bokeh.models import FuncTickFormatter

x = [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
y = [10**xx for xx in x]

output_file("log.html")

# create a new plot with a log axis type
p = figure(plot_width=400, plot_height=400, y_axis_type="log")

p.line(x, y, line_width=2)
p.circle(x, y, fill_color="white", size=8)

p.axis.major_label_text_font_size = "20px"

p.yaxis.formatter = FuncTickFormatter(code=log_axis_labels(max_tick=2.99))
```

you get the expected output where values below 10^3 are displayed in regular decimal format. However, it's hacky, and it relies on weird unicode digits that for some reason render 1-3 at different sizes/boldness than 4-9, so it looks weird as evidenced by the output:

<img width="404" alt="Screen Shot 2021-03-05 at 3 19 28 PM" src="https://user-images.githubusercontent.com/6944089/110169103-2ef90380-7dc6-11eb-946c-31070eaa51df.png">

It'd be nice if this functionality could just be folded into the new log axis exponent labels. Perhaps even doing better than matplotlib and allowing a single number `min_exponent=3` that would set the limits to (10^-3, 10^3) or also a tuple `min_exponent=(-2,4)`  that would set the limits to (10^-2, 10^4).

**Comment by bryevdv** [comment]
Seems self-contained, which is my primary criteria for `good first issue`

**Comment by inwaves** [comment]
@bryevdv I can take a look.

**Comment by mattpap** [comment]
You are modifying a legacy plain-text code path. You need to change this and `format_graphics()` (above).

**Comment by mosc9575** [comment]
@mattpap Thanks for the fast reply. I will check this out.

**Comment by mosc9575** [comment]
Well, I also changed

https://github.com/bokeh/bokeh/blob/187803263a34c9f2d351578b548e99178cd8f591/bokehjs/src/lib/models/formatters/log_tick_formatter.ts#L49-L53

to this:
```
return expos.map((expo) => {
  if (abs(expo)<2){
      const b = new TextBox({text: unicode_replace(`${base**expo}`)})
      const e = new TextBox({text: ''})
      return new BaseExpo(b, e)
  }else{
      const b = new TextBox({text: unicode_replace(`${base}`)})
      const e = new TextBox({text: unicode_replace(`${expo}`)})
      return new BaseExpo(b, e)
  }
})
```

I hope this is correct. But I somehow still see no changes in the generated figure.

**Comment by bryevdv** [comment]
@mosc9575 are you certain you are using the locally built BokehJS? e.g. by setting the `BOKEH_RESOURCES=inline` environment variable?

**Comment by mosc9575** [comment]
@bryevdv Thank you, your hint was perfect. Now I finally see the changes in the figure and some logs in the console.

For the fixed value of 2 for the min_exponent this is how the figure looks like.

![fixed min_exponent=2](https://user-images.githubusercontent.com/68053396/115346503-86a1d180-a1b0-11eb-9c2d-cd31c5cb2268.png)

I will try to pass the value from Python to BokehJS and if this is working I will create a PR.

**Comment by mosc9575** [comment]
With the changes above the code below 

```
x = [-4.0, -3.5, -3.0, -2.5, -2.0, -1.5, -1.0, -0.5, 0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
y = [10**xx for xx in x]

# create a new plot with a log axis type
p = figure(plot_width=300, plot_height=300, y_axis_type="log")

p.line(x, y, line_width=2)
p.circle(x, y, fill_color="white", size=8)
p.left[0].formatter.min_exponent=3

show(p)
```
results in

![bokeh_plot (1)](https://user-images.githubusercontent.com/68053396/115615933-d804aa80-a2ef-11eb-8276-ec6a779afc65.png)
