### ISSUE TITLE
Discussion: Gallery reorganization

### ISSUE THREAD

**Issue by ghost** [bokeh/bokeh#11008]
GOAL:  Decide upon a new organization method for Bokeh gallery examples at docs.bokeh.org.

BACKGROUND: The gallery needs new examples to explain and highlight some of the features that have been added to Bokeh over the last couple of years.  As the gallery grows, the size and choice will hamper ability to visually scan the examples and pick out relevant examples for a user's purpose.  A new organization structure will allow examples to be arranged in useful subcategories.

PROPOSAL:  My initial proposal is to leave Server App and Notebook examples unchanged, and use Standalone Examples as the area we can subdivide into chart types. Something like:
- scatter
- linear/timeseries
- bar/histogram
- heatmap/hexbin
- geodata
- network graph
- other

This proposal is just meant as a starting point for discussion, so please respond with any additions, objections, edge cases and considerations. Thanks!
cc @tcmetzger

**Comment by mattpap** [comment]
Maybe #2724 could be incorporated into this?

**Comment by bryevdv** [comment]
For sure, the main reason that was never done is because I was not sure what thumbnails should look like for "large" examples, e.g. a big grid. It doesn't really make sense to crush all of a big example down into a tiny thumbnail IMO. This issue should also consider several things holistically, like:

* Dow we should approach thumbnails (and if there is anything we can do to automate or simplify keeping them up to date) 
* Defining a docstring or top-comment format so that examples can display informational test instead of only a bare plot and code
* keywords or cross-indexing to have plots show up in multiple sections when appropriate

**Comment by tcmetzger** [comment]
That sounds great! It definitely makes sense to categorize things a bit. We could proabably also use the colored boxes from [Sphinx panels](https://sphinx-panels.readthedocs.io/en/latest/), like we did on the [docs landing page](https://docs.bokeh.org/en/latest/index.html).

**Comment by bryevdv** [comment]
We can try out the panels and see, but I will admit to being skeptical. The primary benefit of the gallery is to be a very information dense index that is also manages quickly scannable. It seems like putting every thumbnail inside a panel, with an inside border and title area, will take up a *lot* of space.

**Comment by tcmetzger** [comment]
Absolutely +1 on the alt text - for accessibility and SEO reasons! 
I was thinking the panels more to visually group categories on the gallery landing page (with different colors, like the yellow, green and blue on the docs landing page). That's undoubtedly going to take some experimenting!

**Comment by pavithraes** [comment]
Just for quick reference, here are the galleries from some other viz projects:
- [Matplotlib](https://matplotlib.org/stable/gallery/index.html)
- [Plotly](https://plotly.com/python/)
- [D3](https://observablehq.com/@d3/gallery)
- [Altair](https://altair-viz.github.io/gallery/index.html)

I like the idea of using sphinx panels. The MLP gallery seems to have boundaries for each gallery item, I think this looks nice. :)

**Comment by tcmetzger** [comment]
Because I just happened to learn this: matplotlib uses a sphinx extension, [sphinx-gallery (https://github.com/sphinx-gallery/sphinx-gallery)](https://github.com/sphinx-gallery/sphinx-gallery), to automate some of their galleries. That might be an option for us as well!

**Comment by bryevdv** [comment]
@tcmetzger AFAIK that tools is very heavily tied to both MPL and static images, so it's probably not going to be useful, at least not directly.

**Comment by bryevdv** [comment]
The gallery was re-organized to go along with the new user's guide information architecture last year.
