### ISSUE TITLE
[BUG] Log axis exponents react differently when font size is defined in anything but px (e.g. pt)

### ISSUE THREAD

**Issue by ethankruse** [bokeh/bokeh#11006]
Hi,

I was excited to see 2.3.0 starts to include exponents for large numbers. However, it seems a bit buggy, in that it works if you define your font size in "px" but not in "pt" or any other units so far as I can tell.

Taking the [doc's log axis example](https://docs.bokeh.org/en/latest/docs/user_guide/plotting.html#log-scale-axes), I just add a single line setting a custom font size.

```
from bokeh.plotting import figure, output_file, show

x = [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
y = [10**xx for xx in x]

output_file("log.html")

# create a new plot with a log axis type
p = figure(plot_width=400, plot_height=400, y_axis_type="log")

p.line(x, y, line_width=2)
p.circle(x, y, fill_color="white", size=8)

p.axis.major_label_text_font_size = "20px"

show(p)
```

Using `"20px"` works as expected:

<img width="413" alt="Screen Shot 2021-03-05 at 2 35 30 PM" src="https://user-images.githubusercontent.com/6944089/110164902-0b32bf00-7dc0-11eb-8815-5f9cd6af969c.png">

Using a font size of `"20pt"` instead causes the exponents to have the same font size as the base numbers, which looks wrong and takes up way more space.

<img width="395" alt="Screen Shot 2021-03-05 at 2 36 05 PM" src="https://user-images.githubusercontent.com/6944089/110164958-1f76bc00-7dc0-11eb-83d0-4e9b95ae65ad.png">

Digging into the code, it seems like you theoretically accept font sizes in [these units](https://docs.bokeh.org/en/latest/_modules/bokeh/core/property/visual.html#FontSize):
```
em|ex|ch|ic|rem|vw|vh|vi|vb|vmin|vmax|cm|mm|q|in|pc|pt|px
```

and using any other of those units aside from `px` causes the same problem.

**Comment by mattpap** [comment]
> `em|ex|ch|ic|rem|vw|vh|vi|vb|vmin|vmax|cm|mm|q|in|pc|pt|px`

Theoretically, but only absolute units will work reliably (at some point we may get back to PR #10259 that adds support for relative units). So, `pt` should work, but the new implementation of log axis labels works only with `px`. It assumes that normalization to `px` units happens before this, but that doesn't actually happen.
