### ISSUE TITLE
[FEATURE] Make PolyAnnotation arrays CDS driven

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11012]
Currently, when defining vertices for a PolyAnnotation, the `xs` and `ys` properties only accept arrays of floats. In order to use data units to position a vertex on a datetime axis, all datetime information needs to be converted to a float (`datetime.timestamp() * 1000` or `time.mktime(datetime.timetuple())*1000`, for example).

It would be very convenient (and more consistent) if it was possible to use an array of datetime objects directly. My understanding is that PolyAnnotation is not using a CDS - and that coordinates thus are not DataSpecs (which would be able to handle datetime data). See https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/user_guide/examples/plotting_polygon_annotation.py for an example. 

cc @bryevdv

**Comment by mattpap** [comment]
Closing in favour of discussion https://github.com/bokeh/bokeh/discussions/12487.
