### ISSUE TITLE
[FEATURE] BokehJS usage : documentation updates

### ISSUE THREAD

**Issue by oviquezr** [bokeh/bokeh#11013]
This issue is a follow-up to discussion from discourse: [Differences in BokehJS vs Python : expected usage](https://discourse.bokeh.org/t/differences-in-bokehjs-vs-python-expected-usage/7313). It is intended to match with the PR proposed in the above discussion, with respect to usage notes for BokehJS. 

The documentation changes reflect the usage differences between Python and JS on version 2.3; solutions or workarounds are noted where possible.

**Comment by bryevdv** [comment]
cc @mattpap @tcmetzger

**Comment by tcmetzger** [comment]
This is an excellent list, thank you @oviquezr! 

Even though the release notes seem to be the best place for this sort of information, I'd still consider adding a link to this list as a `.. note::` in https://docs.bokeh.org/en/latest/docs/user_guide/bokehjs.html - at least until the inconsistencies mentioned here have been fixed.

**Comment by tcmetzger** [comment]
I just saw @bryevdv's [comment on the PR](https://github.com/bokeh/bokeh/pull/11014#issuecomment-791771469) - that makes a lot of sense, let's talk about where to put the information (and links to it) in the PR instead of here!

**Comment by bryevdv** [comment]
> at least until the inconsistencies mentioned here have been fixed.

I should clarify one thing though, which is that there is not an exception of exact 1-1 parity between BokehJS API and Python Bokeh API. In particular BokehJS has as minimal high-level "charts" API that is entirely absent from Python . I think it's fair to say we want the "plotting" APIs to be similar to each other, but being idiomatic in the language should always take precedence (and then we can just note any differences resulting from that priority)

**Comment by mattpap** [comment]
Still there is plenty of bugs and fixable inconsistencies on that list.

**Comment by bryevdv** [comment]
Summarizing my POV:

* release notes just gets BokehJS-only changes from 2.2.3 to 2.3
* `bokehjs.rst` gets a "Comparison to Python" section
* new issues made as appropriate for actual bugs to fix

Does that sound good? 

@oviquezr we'd be happy to have help with any/all of those please just let us know what you are available to work on.

**Comment by oviquezr** [comment]
@bryevdv sounds like a plan! I'll put together a fresh PR with this in mind. 
Would it be fair to add a "current usage" section to `bokehjs.rst` in order to address the workarounds available for the entries in my list that may warrant an issue, such as the palette selection?

**Comment by bryevdv** [comment]
Sure that seems fine, maybe make a note in any issues to fix things to update any relevant section with the fix :)

**Comment by oviquezr** [comment]
I've updated the original PR with the doc changes; let me know if you rather I scrap that PR and make a clean one with those changes! 
I'll start filing the bug reports with the relevant docs update notes as well, and will start getting myself comfortable with updating the source code, see if I can lend a hand with that as well.

**Comment by tcmetzger** [comment]
Thank you for your work on this - let us know if you need help getting set up with working on the code. The docs have some helpful information in the [Developers Guide](https://docs.bokeh.org/en/latest/docs/dev_guide.html), including some [specifics about BokehJS](https://docs.bokeh.org/en/latest/docs/dev_guide/bokehjs.html). 

BTW: I'm planning on revising and improving the developer docs sometime in the next few months, so I'd also appreciate some feedback and ideas on how to improve the docs!
