### ISSUE TITLE
[BUG] Serialization of MessageSent document event includes all model references

### ISSUE THREAD

**Issue by matbryan52** [bokeh/bokeh#11026]
Observed a drop in performance while upgrading from release 2.2.3 to 2.3.0, on a page using ```MouseMove``` events to update a line plot. Fast mouse movement causes events to 'queue' and complete after mouse has stopped.

Issue discussed on Discourse at [https://discourse.bokeh.org/t/mousemove-events-queuing-up-after-2-3-0-update/7361](https://discourse.bokeh.org/t/mousemove-events-queuing-up-after-2-3-0-update/7361).

From @mateusz on Discourse:

> Currently serialization of MessageSent document event includes all model references this event’s model field refers to, whereas it should include only previously unknown models. This is a regression since PR [https://github.com/bokeh/bokeh/pull/10602](https://github.com/bokeh/bokeh/pull/10602).

An MWE is available on the Discourse thread.

Versions:
Bokeh 2.3.0 (upgrading from 2.2.3)
Python 3.9.2 on Ubuntu 20.04 / Firefox 86.0

Video of behaviour:

https://user-images.githubusercontent.com/78845903/110388722-cb8c0180-8063-11eb-9ca3-323139880ff2.mp4

**Comment by bryevdv** [comment]
@mattpap we should make sure this can go in a 2.3.1 release next week. Pretty sure this is also affecting cuxfilter cc @ajaythorve

**Comment by mattpap** [comment]
> `bokeh.core.property.bases.DeserializationError: Float expected Real, got None of type NoneType`

This is most likely unrelated and a side effect of making properties non-nullable by default in 2.3. I need to add model/attr information to those deserialization errors, because currently I don't know whether you're setting a bokeh's property with incorrect type of value, or you need to update your properties to make them nullable where needed. We already did that for validation errors.

**Comment by philippjfr** [comment]
Probably not related but it seems data models are also sent and/or registered on each render:

<img width="297" alt="Screen Shot 2021-03-09 at 7 51 32 PM" src="https://user-images.githubusercontent.com/1550771/110522219-f6805f00-8110-11eb-9f8f-f139e64cdb14.png">

Do you want an issue for that?

**Comment by bjarthur** [comment]
here is another MWE.  vastly slower in 2.3 vs 2.2.  great to hear this might be fixed in 2.3.1.  thanks!

```
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, curdoc
from bokeh.events import PanStart, Pan

p = figure()
p.toolbar.active_drag = None
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
quad = ColumnDataSource(data=dict(left=[], right=[], bottom=[], top=[]))
p.quad(left='left', right='right', top='top', bottom='bottom', source=quad, fill_color="black")

def cb_panstart(evt):
    quad.data.update(left=[evt.x], right=[evt.x], bottom=[evt.y], top=[evt.y])

def cb_pan(evt):
    quad.data.update(right=[evt.x], top=[evt.y])

p.on_event(PanStart, cb_panstart)
p.on_event(Pan, cb_pan)

doc = curdoc()
doc.add_root(p)
```

**Comment by bryevdv** [comment]
@bjarthur @matbryan52 if you have the ability to build and test from the latest `branch-2.3` that would be helpful, otherwise I will try to make a dev build for testing in the next day or two (very slammed with work-work this week)

**Comment by bjarthur** [comment]
i've never built bokeh before, but would gladly test a dev build.  thanks!

**Comment by bryevdv** [comment]
FYI for some reason the AWS upload in our automation is failing in CI (works fine locally with the same credentials) so a dev build may be a few days off until I can sort out what's changed.

**Comment by bryevdv** [comment]
@bjarthur `2.3.1dev1` is now availble, `conda install -c bokeh/c/dev bokeh` or pip install with `--pre` Note that dev build CDN resources are NOT guaranteed to remain published, do not use dev builds for anything permanent or "prod"

**Comment by bjarthur** [comment]
super zippy for me!  thanks so much!!
