### ISSUE TITLE
[BUG] Palettes not accessible by name for `ColorMapper` objects in BokehJS

### ISSUE THREAD

**Issue by oviquezr** [bokeh/bokeh#11034]
Version: 2.2.3 and 2.3
Browsers: Chrome, Brave, Safari

When creating an `image()`, for example, the color map can be defined with a `Bokeh.LinearColorMapper()`. However, the palette collection is not available by name (string) to the color mapper instance. Instead, the palette argument must be provided as a color string array in order to render correctly.

- In 2.2.3, setting the palette to a string value will render the image as an all-black region
- In 2.3.0, setting the palette to a string value will trigger an `Uncaught Error`

Key source code (key lines)

```
var cmap = new Bokeh.LinearColorMapper({palette:'Viridis256',low:0,high:1,nan_color:'white'});
```

The above code will produce output like the following (v2.3.0):

```
Uncaught Error: LinearColorMapper(9CC3FD23D2D844B697284A876ACD009C).palette given invalid value: "Viridis256"
```

A complete, minimal example is given via CodePen at [bokehjs_palette](https://codepen.io/oviquezr/pen/bGBRxmx), and shows the following:
- default palette (grayscale)
- original bug\*
- a workaround

\* The example will load with v2.3.0 by default, and will show only the default palette (grayscale) and the workaround, since the error will stop the plot from rendering entirely. The workaround consists of passing the palette as a color string array; this array is extracted from the original Palette source code.

- To trigger the error in v2.3.0, uncomment JS:line 26
- To switch to v2.2.3 and see the monochromatic render, uncomment JS:lines 26-36, HTML:lines 6-9, and comment out HTML:lines 1-4

Issue is related to discourse topic: [Differences in BokehJS vs Python : expected usage](https://discourse.bokeh.org/t/differences-in-bokehjs-vs-python-expected-usage/7313)

**Comment by oviquezr** [comment]
To Do:
- [ ] update palette argument handler in color mapper objects
- [ ] update `sphinx/source/docs/user_guide/bokehjs.rst` at tag `.. _userguide_bokehjs_differences_palette:`

**Comment by bryevdv** [comment]
@oviquezr I don't think you need to define `myViridis` all the palettes are available as named constants in `palettes.ts` which is part of the `bokeh-api` bundle:

https://github.com/bokeh/bokeh/blob/branch-2.4/bokehjs/src/lib/api/palettes.ts

**Comment by oviquezr** [comment]
> @oviquezr I don't think you need to define `myViridis` all the palettes are available as named constants in `palettes.ts` which is part of the `bokeh-api` bundle:
> 
> https://github.com/bokeh/bokeh/blob/branch-2.4/bokehjs/src/lib/api/palettes.ts

The issue I ran into  there was that the palettes, as defined in the `bokeh-api` bundle, do not seem to be exposed to the user. I defined `myViridis` from those arrays to convey a working solution; in my own active project, I actually used `bokehjs/src/lib/api/palettes.ts` to create a `Palettes` object for my own convenience, until the palette becomes accessible to color mapper objects, or until the palette itself becomes readily accessible to the user (perhaps `Bokeh.Palettes`?)

**Comment by mattpap** [comment]
Named palettes are not supported, because palettes are located in a separate bundle, to make the main bundle smaller, which makes it tricky to support from models. It's solvable, but needs some thought. For now, one has to do manually in bokehjs, what bokeh does automatically. Also, palettes need to be updated to match bokeh.

**Comment by bryevdv** [comment]
@oviquezr if you want to submit the small PR to expose `Bokeh.Palettes` that would be quick to accept
