### ISSUE TITLE
Two examples tests failing 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11031]
All PR runs since ~yesteday
```
tests/test_examples.py::test_file_examples[/home/runner/work/bokeh/bokeh/examples/models/file/buttons.py-example2-config2] 
[INFO] Example run in 0.588s
[INFO] Example rendered in 0.789s
[JS] Failed to load resource: net::ERR_FILE_NOT_FOUND
[JS] Failed to load resource: net::ERR_FILE_NOT_FOUND
[JS] ReferenceError: Bokeh is not defined
[JS]     at file:///home/runner/work/bokeh/bokeh/examples/models/file/buttons.html:22:13
[JS] ReferenceError: Bokeh is not defined
[JS]     at HTMLDocument.fn (file:///home/runner/work/bokeh/bokeh/examples/models/file/buttons.html:50:15)
[JS] Uncaught
FAILED
```

cc @mattpap I have not had a chance to look into this at all.

**Comment by mattpap** [comment]
I'm working on it in PR #11024.

**Comment by bryevdv** [comment]
OK but we need that isolated fix on `branch-2.3` unless you want to back port all of #11024 ?

**Comment by mattpap** [comment]
It is not fixed yet. I had to disable examples with pre-built extensions to make it work.

**Comment by bryevdv** [comment]
@mattpap this is fixed now? I don't see this example exclude in `examples.yaml`

**Comment by mattpap** [comment]
Whatever was the problem was fixed at some point. I use this example for experimenting with widgets.
