### ISSUE TITLE
[BUG] Calling `figure({title:"some title"})` replaces Title object with string, prevents subsequent updates to title text

### ISSUE THREAD

**Issue by oviquezr** [bokeh/bokeh#11038]
Version: 2.2.3 and 2.3
Browsers: Chrome, Brave, Safari

When creating a figure with `var plot = new Bokeh.Plotting.figure()`, the property `plot.title` will instantiate from `Bokeh.Title()`. However, when calling `var plot = new Bokeh.Plotting.figure({title:"some title"})`, BokehJS replaces `plot.title` with the provided string. This makes it so that the title text cannot be dynamically updated later. In Python, the
equivalent approach casts the string in the argument to the underlying Title() object.

To preserve the ability to update a figure title later, the following sequence works as expected:

```
var plot = new Bokeh.Plotting.figure()
plot.title.text = "some title"
```

A complete, minimal example is given via CodePen at [bokehjs_titles](https://codepen.io/oviquezr/pen/LYbLBJK). The example shows two figures, each using one of the methods described above. The example also provides a button to trigger an update to both figure titles; however, only one of the titles can be updated as needed. JS lines 44-51 show the update function:

```
function addTitle() {
  var new_val = Math.floor(Math.random()*10)
  // plot1 title is string
  plot1.title = 'New Title '+new_val
  
  //plot2 title is Title object
  plot2.title.text = 'New Title '+new_val+' #2'
}
```

Note that `plot1.title` in this example is of type string, as set by JS lines:7-12 so it does **not** contain a `.text` value, while `plot2.title` is an instance of `Bokeh.Title` and thus provides the property `plot2.title.text`.

Issue is related to discourse topic: [Differences in BokehJS vs Python : expected usage](https://discourse.bokeh.org/t/differences-in-bokehjs-vs-python-expected-usage/7313)

**Comment by bryevdv** [comment]
cc @mattpap I am not sure what your WIP PR covers, but please review these new split out issues to make sure any that should be associated are associated.
