### ISSUE TITLE
[BUG] `Bokeh.Widgets` objects missing `tools`, required by `Bokeh.Plotting.gridplot()` 

### ISSUE THREAD

**Issue by oviquezr** [bokeh/bokeh#11035]
Version: 2.2.3 and 2.3
Browsers: Chrome, Brave, Safari

A `Div()` instance created by calling `var mydiv = new Bokeh.Widgets.Div()` does not include `mydiv.toolbar.tools` to facilitate using in a custom `Bokeh.Plotting.gridplot()`; or `gridplot()` fails to check whether the property exists before accessing. This throws:

```
Uncaught TypeError: Cannot read property 'tools' of undefined
```

To use a `Div()` inside a `gridplot()`, my current workaround is to first set the div's toolbar property, as follows:

```
mydiv.toolbar = {tools:[]}
```

A complete, minimal example is given via CodePen at [bokehjs_div_tools](https://codepen.io/oviquezr/pen/gOLzbvZ), where JS:line 17 contains the workaround noted above. Comment this line out to trigger the failure.

Issue is related to discourse topic: [Differences in BokehJS vs Python : expected usage](https://discourse.bokeh.org/t/differences-in-bokehjs-vs-python-expected-usage/7313)

**Comment by oviquezr** [comment]
Renamed to reflect that this occurs with `Bokeh.Widgets.Slider` as well, and might apply to other `Widgets` not yet tested

**Comment by mattpap** [comment]
It applies to everything that's not a `Plot`.
