### ISSUE TITLE
BokehJS loading is too chatty 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11047]
None of this is really of interest to users: 

<img width="716" alt="Screen Shot 2021-03-12 at 10 21 54 AM" src="https://user-images.githubusercontent.com/1078448/110982091-f18ffb00-831c-11eb-9f87-48323605a7b9.png">

I think this should be pared down to something more like:
``` 
[bokeh] Loading BokehJS bundles
[bokeh] BokehJS 2.3.1 loaded (bokeh, bokeh-widgets)
```

All the rest of the details coudl remain with `console.debug`

**Comment by mattpap** [comment]
For the most part it's autoload that's so chatty. Otherwise bokehjs prints only this:
```
[bokeh] setting log level to: 'debug'
[bokeh] document idle at 217 ms
```
(from `plotting/file/color_scatter.py`).

**Comment by bryevdv** [comment]
Sure, I meant for this issue to cover all the various ways bokeh can be loaded.

**Comment by bryevdv** [comment]
Well, they are already set to `console.debug` not `console.log` and the default levels seem to browser dependent. (E.g. loads are chatty on safari but are *not* chatty on chrome) I don't want to remove these entirely and AFAIK there is no simple way to hide them by default on all browsers , so I will just close this with `noaction`.
