### ISSUE TITLE
bokeh works inline but output_notebook() failed to load

### ISSUE THREAD

**Issue by MeliBall** [bokeh/bokeh#11048]
![Capture](https://user-images.githubusercontent.com/63462653/111002218-c5e43380-8363-11eb-9537-dd9eab1780cf.PNG)

Hi guys
can somebody help to handle this error?

**Comment by bryevdv** [comment]
@MeliBall All of the errors in your screen shot are from Panel, not from Bokeh. The notebook screenshot you have looks to be the standard tuturial, which does not use Panel at all. So, you need to provide more information (basically, all of the information in the issue template that was asked for in the first place):

* system/platform info
* browser info
* all relevant environment package versions

and most especially, the exact notebook that is causing a problem.

**Comment by bryevdv** [comment]
FWIW I am not able to repro any issue woith the standard tutorial:

<img width="894" alt="Screen Shot 2021-03-12 at 1 57 46 PM" src="https://user-images.githubusercontent.com/1078448/111003008-2f038100-833b-11eb-8ccf-4433d3984eaf.png">

**Comment by MeliBall** [comment]
Sorry, i am just starting with bokeh tutorials
I did the same example that you plotted above and it worked. But when i try the command output_notebook() it just keep loading without retrieving any result. I though it could be a network issue and I disconnected from my VNP, the the problem persists

**Comment by MeliBall** [comment]
I am using windows7, google chrome, and here the package info:
IPython - 7.21.0
Pandas - 1.2.2
Bokeh - 2.3.0

**Comment by bryevdv** [comment]
@MeliBall I am not sure why the output would not update, however, if the plot renders, then `output_notebook` must have actually been successful

**Comment by philippjfr** [comment]
That's pretty weird, this could happen if Panel is imported in a startup script though.

**Comment by MeliBall** [comment]
![Capture](https://user-images.githubusercontent.com/63462653/111004520-f7f79480-8367-11eb-9802-71e61dc7ee10.PNG)


I am mainly interested to deploy my maps with bokeh... but it just keep loading and nothing is retrieved

**Comment by bryevdv** [comment]
@MeliBall You need to provide us a complete notebook to run and investigate including any and all data that might be necessary to run it. It's not possible to speculate about anything with out actually running real code.

**Comment by MeliBall** [comment]
Hi guys

I am working in this environment:

# Name                    Version                   Build  Channel
access                    1.1.3              pyhd8ed1ab_0    conda-forge
affine                    2.3.0                      py_0    conda-forge
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.3.0            py38haa244fe_0    conda-forge
boost-cpp                 1.74.0               h54f0996_2    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bs4                       4.9.3                         0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cairo                     1.16.0            hba8bd2f_1007    conda-forge
cartopy                   0.18.0          py38h7c06ecb_12    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.5           py38hd8c33c5_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
cftime                    1.4.1            py38h347fdf6_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorcet                  2.0.6              pyhd8ed1ab_0    conda-forge
contextily                1.1.0              pyhd8ed1ab_0    conda-forge
coverage                  5.5              py38h294d835_0    conda-forge
cryptography              3.4.4            py38hb7941b4_0    conda-forge
curl                      7.71.1               h4b64cdc_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h294d835_3    conda-forge
dask                      2021.2.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.2.0           pyhd8ed1ab_0    conda-forge
datashader                0.12.0             pyhd3deb0d_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
distributed               2021.2.0         py38haa244fe_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
esda                      2.3.6              pyhd8ed1ab_0    conda-forge
et-xmlfile                1.0.1                    pypi_0    pypi
expat                     2.2.10               h39d44d4_0    conda-forge
fiona                     1.8.18           py38h60f4e94_0    conda-forge
fontconfig                2.13.1            h1989441_1004    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
fsspec                    0.8.7              pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38haa244fe_3    conda-forge
gdal                      3.1.4            py38h7b01a69_8    conda-forge
geocoder                  1.38.1                     py_1    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_0    conda-forge
geoplot                   0.4.1                      py_0    conda-forge
geopy                     2.1.0              pyhd3deb0d_0    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                hee96dd5_4    conda-forge
geoviews                  1.8.2                      py_0    conda-forge
geoviews-core             1.8.2                      py_0    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
giddy                     2.3.3                      py_0    conda-forge
hdf4                      4.2.13            h0e5069d_1004    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.14.2             pyhd8ed1ab_0    conda-forge
hvplot                    0.7.0              pyhd3deb0d_0    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.7.0            py38haa244fe_0    conda-forge
importlib_metadata        3.7.0                hd8ed1ab_0    conda-forge
inequality                1.0.0                      py_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
ipykernel                 5.5.0            py38hc5df569_1    conda-forge
ipython                   7.21.0           py38hc5df569_0    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jdcal                     1.4.1                    pypi_0    pypi
jedi                      0.18.0           py38haa244fe_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                    pypi_0    pypi
jupyter-console           6.2.0                    pypi_0    pypi
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
kealib                    1.4.14               h0883a5c_1    conda-forge
kiwisolver                1.3.1            py38hbd9d945_1    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.1.4                hca2c63a_8    conda-forge
libglib                   2.66.7               h1e62bf3_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h02ac0ef_1012    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.1                 h4f54205_1    conda-forge
libpysal                  4.4.0              pyhd8ed1ab_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_3    conda-forge
libspatialite             5.0.1                h987baeb_3    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
libwebp-base              1.2.0                h8ffe710_0    conda-forge
libxml2                   2.9.10               hf5bbc77_3    conda-forge
llvmlite                  0.35.0           py38h57a6900_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.2              pyhd8ed1ab_0    conda-forge
markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
markupsafe                1.1.1            py38h294d835_3    conda-forge
matplotlib-base           3.3.4            py38h34ddff4_0    conda-forge
mercantile                1.1.6              pyh9f0ad1d_0    conda-forge
mgwr                      2.1.2                      py_0    conda-forge
mistune                   0.8.4           py38h294d835_1003    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mock                      4.0.3            py38haa244fe_1    conda-forge
more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.2            py38hbd9d945_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38haa244fe_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nest-asyncio              1.5.1                    pypi_0    pypi
netcdf4                   1.5.6           nompi_py38h5338a22_100    conda-forge
networkx                  2.5                        py_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.2.0            py38haa244fe_0    conda-forge
numba                     0.52.0           py38h4c96930_0    conda-forge
numexpr                   2.7.2            py38h4c96930_0    conda-forge
numpy                     1.20.1           py38h0cc643e_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h48faf41_0    conda-forge
openpyxl                  3.0.6                    pypi_0    pypi
openssl                   1.1.1j               h8ffe710_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.2            py38h4c96930_0    conda-forge
pandoc                    2.11.4               h8ffe710_0    conda-forge
pandocfilters             1.4.3                    pypi_0    pypi
panel                     0.10.3             pyhd8ed1ab_0    conda-forge
param                     1.10.1             pyhd3deb0d_0    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py38h9273828_2    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pluggy                    0.13.1           py38haa244fe_4    conda-forge
pointpats                 2.2.0                      py_0    conda-forge
poppler                   0.89.0               h3772339_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.1                 h0f1a9bc_1    conda-forge
proj                      7.2.0                h1cfcee9_2    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h294d835_1    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pygments                  2.8.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.0.0.post1      py38h0ae89ba_0    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pysal                     2.3.0                      py_0  
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
pytables                  3.6.1            py38h153c448_3    conda-forge
pytest                    6.2.2            py38haa244fe_0    conda-forge
pytest-cov                2.11.1             pyh44b312d_0    conda-forge
python                    3.8.8           h7840368_0_cpython    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyviz_comms               2.0.1              pyhd3deb0d_0    conda-forge
pywin32                   300                      pypi_0    pypi
pywinpty                  0.5.7            py38h32f6830_1    conda-forge
pyyaml                    5.4.1            py38h294d835_0    conda-forge
pyzmq                     22.0.3           py38h09162b1_1    conda-forge
qtconsole                 5.0.2                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
quantecon                 0.4.8                    py38_0  
rasterio                  1.2.0            py38h5653988_0    conda-forge
rasterstats               0.14.0                     py_0    conda-forge
ratelim                   0.1.6                      py_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rtree                     0.9.7            py38h8b54edf_1    conda-forge
scikit-learn              0.24.1           py38ha09990b_0    conda-forge
scipy                     1.6.0            py38h5f893b4_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
segregation               1.5.0              pyhd8ed1ab_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
shapely                   1.7.1            py38h2426642_4    conda-forge
simplejson                3.17.2           py38h294d835_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
spaghetti                 1.5.6              pyhd8ed1ab_0    conda-forge
spglm                     1.0.8                      py_0    conda-forge
spint                     1.0.7              pyhd8ed1ab_0    conda-forge
splot                     1.1.3              pyhd8ed1ab_1    conda-forge
spreg                     1.2.2              pyhd8ed1ab_0    conda-forge
spvcm                     0.3.0                      py_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
statsmodels               0.12.2           py38h347fdf6_0    conda-forge
sympy                     1.7.1            py38haa244fe_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.2            py38haa244fe_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    2.2.4                hddc2a84_1    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
tobler                    0.5.4              pyhd3eb1b0_0  
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.58.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.24.3                     py_1    conda-forge
vc                        14.2                 hb210afc_3    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_3    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py38haa244fe_4    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
xarray                    0.17.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.8                h4e2f164_1    conda-forge


The code I am running is below:

from bokeh.plotting import figure, output_notebook, show
from bokeh.tile_providers import STAMEN_TERRAIN
output_notebook()

minx, miny, maxx, maxy = xys_wb.total_bounds
y_range = miny, maxy
x_range = minx, maxx

def base_plot(tools='pan,wheel_zoom,reset',plot_width=600, plot_height=400, **plot_args):
    p = figure(tools=tools, plot_width=plot_width, plot_height=plot_height,
        x_range=x_range, y_range=y_range, outline_line_color=None,
        min_border=0, min_border_left=0, min_border_right=0,
        min_border_top=0, min_border_bottom=0, **plot_args)

    p.axis.visible = False
    p.xgrid.grid_line_color = None
    p.ygrid.grid_line_color = None
    return p

options = dict(line_color=None, fill_color='#800080', size=4)

**Comment by MeliBall** [comment]
Error in the google console:

**Bokeh: BokehJS not loaded**

  console.debug("Bokeh: BokehJS not loaded, scheduling load and callback at", now());
    root._bokeh_is_loading = css_urls.length + js_urls.length;

    function on_load() {
      root._bokeh_is_loading--;
      if (root._bokeh_is_loading === 0) {
        console.debug("Bokeh: all BokehJS libraries/stylesheets loaded");
        run_callbacks()
      }
    }

    function on_error(url) {
      console.error("failed to load " + url);
    }

    for (let i = 0; i < css_urls.length; i++) {
      const url = css_urls[i];
      const element = document.createElement("link");
      element.onload = on_load;
      element.onerror = on_error.bind(null, url);
      element.rel = "stylesheet";
      element.type = "text/css";
      element.href = url;
      console.debug("Bokeh: injecting link tag for BokehJS stylesheet: ", url);
      document.body.appendChild(element);
    }

    const hashes = {"https://cdn.bokeh.org/bokeh/release/bokeh-2.3.0.min.js": "HjagQp6T0/7bxYTAXbLotF1MLAGWmhkY5siA1Gc/pcEgvgRPtMsRn0gQtMwGKiw1", "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.3.0.min.js": "ZEPPTjL+mdyqgIq+/pl9KTwzji8Kow2NnI3zWY8+sFinWP/SYJ80BnfeJsa45iYj", "https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.3.0.min.js": "exLqv2ACDRIaV7ZK1iL8aGzGYQvKVuT3U2CT7FsQREBxRah6JrkVCoFy0koY1YqV"};

    for (let i = 0; i < js_urls.length; i++) {
      const url = js_urls[i];
      const element = document.createElement('script');
      element.onload = on_load;
      element.onerror = on_error.bind(null, url);
      element.async = false;
      element.src = url;
      if (url in hashes) {
        element.crossOrigin = "anonymous";
        element.integrity = "sha384-" + hashes[url];
      }
      console.debug("Bokeh: injecting script tag for BokehJS library: ", url);
      document.head.appendChild(element);
    }
  };

  function inject_raw_css(css) {
    const element = document.createElement("style");
    element.appendChild(document.createTextNode(css));
    document.body.appendChild(element);
  }

  
  var js_urls = ["https://cdn.bokeh.org/bokeh/release/bokeh-2.3.0.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.3.0.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.3.0.min.js", "https://unpkg.com/@holoviz/panel@^0.10.3/dist/panel.min.js"];
  var css_urls = ["http://localhost:5006/static/extensions/panel/css/alerts.css", "http://localhost:5006/static/extensions/panel/css/card.css", "http://localhost:5006/static/extensions/panel/css/dataframe.css", "http://localhost:5006/static/extensions/panel/css/json.css", "http://localhost:5006/static/extensions/panel/css/markdown.css", "http://localhost:5006/static/extensions/panel/css/widgets.css"];
  

  var inline_js = [
    function(Bokeh) {
      Bokeh.set_log_level("info");
    },
    function(Bokeh) {
    
    
    }
  ];

  function run_inline_js() {
    
    if (root.Bokeh !== undefined || force === true) {
      
    for (var i = 0; i < inline_js.length; i++) {
      inline_js[i].call(root, root.Bokeh);
    }
    if (force === true) {
        display_loaded();
      }} else if (Date.now() < root._bokeh_timeout) {
      setTimeout(run_inline_js, 100);
    } else if (!root._bokeh_failed_load) {
      console.log("Bokeh: BokehJS failed to load within specified timeout.");
      root._bokeh_failed_load = true;
    } else if (force !== true) {
      var cell = $(document.getElementById("1884")).parents('.cell').data().cell;
      cell.output_area.append_execute_result(NB_LOAD_WARNING)
    }

  }

  if (root._bokeh_is_loading === 0) {
    console.debug("Bokeh: BokehJS loaded, going straight to plotting");
    run_inline_js();
  } else {
    load_libs(css_urls, js_urls, function() {
      console.debug("Bokeh: BokehJS plotting callback run at", now());
      run_inline_js();
    });
  }
}(window));

**Comment by MeliBall** [comment]
!bokeh info

Python version      :  3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.21.0
Tornado version     :  6.1
Bokeh version       :  2.3.0
BokehJS static path :  C:\Users\U0115872\Anaconda3\envs\geo2\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)

**Comment by philippjfr** [comment]
One thing you can do is upgrade Panel to 0.11.0, but your code still gives no indication why Panel would be imported.

**Comment by MeliBall** [comment]
HI guys

I tried with another provider in your notebooks, CARTODBPOSITRON, and it worked. It seems the problem was caused by using STAMER_TERRAIN
thanks a lot for your help

**Comment by bryevdv** [comment]
So, I am not convinced this is not a usage or package version issue. I think for now the best place to continue this discussion is on the support forum, not the issue tracker:

https://discourse.bokeh.org

So, I am going to go ahead and close this here. If we an determine that there is actually some reproducible issue, we can certainly re-open. 

@MeliBall some suggestions to help you improve your issues:

* please utilize the GitHub `<details>` markup when posting very long lists (like the package list) so that they are hidden behind an collapsible div by default
*  use gist to share notebooks or other files: https://gist.github.com
* please check code-formatting and quotind and preview your comments and edit if needed (some of the ones above have formatting that is completely off)
