### ISSUE TITLE
Separate javascript bundle for WebGL

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#11053]
As discussed in PR #10861.  I have found previous references to this before, e.g. issue #4321.

I am not self-assigning this as it is a bundling issue rather than WebGL, and I don't know anything about bokeh bundling yet.

**Comment by mattpap** [comment]
Restoring the webgl bundle is trivial, so we will do it just before 2.4 release, if a better option doesn't emerge by then.
