### ISSUE TITLE
[BUG] Invalid BBox of BoxSelection

### ISSUE THREAD

**Issue by xavArtley** [bokeh/bokeh#11054]
I encouter a javascript error when I begin a box selection from outside the plot (starting from vertical position of the title)

The following gif should better describe the bug:
![SelectionBoxError](https://user-images.githubusercontent.com/18531147/111043223-b509ef80-8441-11eb-8a4f-f4a97e64ccd2.gif)

the MRE:
```python
import numpy as np

from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from bokeh.io import output_file, show


output_file("test.html", mode="inline")


TOOLS="box_select"
p = figure(title = "My chart", tools=TOOLS)

source = ColumnDataSource(
    data=dict(
        x=np.arange(10),
        y=np.random.rand(10),
    )
)
p.scatter("x", "y",source=source)


show(p)
```

Bokeh
Version: 2.3.0

**Comment by mattpap** [comment]
This only happens when selection is started outside of the frame.
