### ISSUE TITLE
[BUG] Sizing mode example layout broken in docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11057]
ref: https://docs.bokeh.org/en/latest/docs/user_guide/layout.html#sizing-modes

Starting in 2.3 the layout of the examples above is broken:

---

<img width="975" alt="Screen Shot 2021-03-13 at 8 57 52 PM" src="https://user-images.githubusercontent.com/1078448/111057770-cd2c3f80-843e-11eb-9d22-643e2404245d.png">

cc @mattpap

**Comment by philippjfr** [comment]
Saw a similar case yesterday, with a number of plots overlapping. Definitely something off about stretch_height/stretch_both.

**Comment by philippjfr** [comment]
@mattpap You sure this issue is limited to the docs? I think this is another layout regression. Will try to come up with a standalone example tomorrow.

**Comment by mattpap** [comment]
@philippjfr, it is a layout regression, that's why I removed `docs` label. I'm working on fix.

**Comment by philippjfr** [comment]
Oh I'm blind, "removed". Sorry for the noise.
