### ISSUE TITLE
[BUG] Tilerenderer snap_back path issue with setv

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11061]
Zooming out too far on a tile source encounters this codepath:

https://github.com/bokeh/bokeh/blob/79d8b9d691f0558f29a1efa46527c4e6cb847618/bokehjs/src/lib/models/tiles/tile_renderer.ts#L320-L322

Then in `setv` this happens:
```
for (const [attr, value] of changes) {
  const prop = this.properties[attr];
  changed.set(prop, value);
  previous.set(prop, prop.get_value());
}
```
The value of `this` is the `Range1d` and the value of `attr` is `"x_range"` so `prop` ends up undefined. 

Not sure if `setv` has a bug or this one codepath is calling `setv` incorrectly (maybe more likely) but one of them needs to be fixed. 

Edit: looking again it seems this code block calls `setv` differently (inconsistently) for `y_range` so it definitely seems that the problem is in the tile renderer.

ref: https://discourse.bokeh.org/t/tilesource-with-local-tile-file/7389/4

cc @mattpap  @brendancol

**Comment by philippjfr** [comment]
Not sure if this is related but the tile renderer has been incredibly unstable for me in 2.3. I've been seeing a ton of errors like this:

> Uncaught (in promise) Error: invalid bbox {left: 1196, top: NaN, right: 1238.9869384765625, bottom: NaN}

with the axes doing weird things and the map disappearing.

**Comment by philippjfr** [comment]
Ignore me, that was actually related to a colorbar (next to a plot with a tile renderer). Will still try to figure out a reproducer.

**Comment by mattpap** [comment]
It's an obvious bug, primarily because `setv()` is dynamically typed. I actually fixed this when working on synchronization a few months back, but that work stalled, so the bugfix never surfaced.

**Comment by bryevdv** [comment]
I made a PR for the trivial immediate fix. It seems like the `values` parameter of `setv` ought to be type-able at this point, but I don't have time to dig in to it at the moment.
