### ISSUE TITLE
Get the value of the select widget on notebook

### ISSUE THREAD

**Issue by RemilYoucef** [bokeh/bokeh#11064]
Hello, I'm using jupyter notebook, I want to get the current value of the **SELECT widget** , I tried IPython.notebook.kernel.execute but it doesn't work : here is my code where I have two controlers of type select (instance & declination) and i want to get the value of the declination controls when updating it. 

callback = CustomJS(args=dict(source=s1, controls=controls), code="""
    if (!window.full_data_save) {
        window.full_data_save = JSON.parse(JSON.stringify(source.data));
    }
    var full_data = window.full_data_save;
    var full_data_length = full_data.x.length;
    var new_data = { x: [], y: [], instance: [], declination : []}
    for (var i = 0; i < full_data_length; i++) {
        if (full_data.declination[i] === null)
            continue;
        if (
            (controls.declination.value === 'All' || full_data.declination[i] === controls.declination.value) && 
            (controls.instance.value === 'All' || full_data.instance[i] === controls.instance.value)
        ) {
            Object.keys(new_data).forEach(key => new_data[key].push(full_data[key][i]));
        }
    }
    source.data = new_data;
    source.change.emit();
    var kernel = IPython.notebook.kernel;
    IPython.notebook.kernel.execute("value =" + cb_obj.value);

**Comment by bryevdv** [comment]
The GitHub issue tracker is reserved for bug reports and feature requests only. It is not the appropriate place to seek general support or help with usage questions. For that, please considere [Discourse site](https://discourse.bokeh.org).
