### ISSUE TITLE
[BUG] Use of np.int is deprecated in numpy 1.20

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#11071]
If you run `examples/webgl/clustering.py` with recent numpy (1.20+) you see the following warning:
```
clustering.py:47: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_pred = algorithm.labels_.astype(np.int)
```
The warning conveniently states the fix.

It will be sensible to check that there are no other examples or tests that use the same deprecation.

**Comment by bryevdv** [comment]
(Sorry we were editing labels at just the same time it seems!)

**Comment by inwaves** [comment]
Hey @ianthomas23 / @bryevdv, anyone doing work on this? If not, I can pick it up.

**Comment by bryevdv** [comment]
@inwaves please go ahead!

**Comment by inwaves** [comment]
@bryevdv Awesome.

Based on the [changelog](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) for 1.20, I'm thinking that any mention of the `np.int` type aliases that contains precision can stay, as in `np.int32` is ok to continue using as-is, but `np.int` can be simplified to the `int` builtin. All `np.float` instances can be replaced with `float`. Thoughts on this?
