### ISSUE TITLE
Running a embed bokeh in flask using server document.

### ISSUE THREAD

**Issue by say2sankalp** [bokeh/bokeh#11080]
Previously, bokeh dashboard was being powered on terminal by following command 
`bokeh server bokeh_app.py --port=5090 --alow-websocket-origin=10.0.0.0:5000 `

But now i want to power it on through server document which is embed feature, can someone suggest me some analogous method through server_documnet api as this api is currently being used for embed bokeh.

**Comment by bryevdv** [comment]
The GitHub issue tracker is reserved for bug reports and feature requests only. It is not the appropriate place to seek general support or help with usage questions. For that, please consider the [Discourse site](https://discourse.bokeh.org). To increase the chance that someone will decide to volunteer their time to help, always include as much information and detail as possible.

**Comment by say2sankalp** [comment]
@bryevdv , Thankyou ! will forward this query to discourse
