### ISSUE TITLE
[FEATURE] Wordcloud plot as in wordcloud package

### ISSUE THREAD

**Issue by narek-davtyan** [bokeh/bokeh#11084]
**Describe the solution you'd like**
I would like to have a wordcloud (tag cloud) plot  with functionality at least as in wordcloud python package (available with pip). The built-in solution would be much faster than the current alternative (read below).

**Describe alternatives you've considered**
Currently I use that wordcloud package, but it is slow to update! I use bokeh image method to load the processed array from wordcloud library. The contents should be dynamically updated all the time in my project, but it slow.

**Comment by bryevdv** [comment]
Offhand I think this might be too high-level / schematic for Bokeh. At this point Bokeh is good for general purpose plotting, but is also intentionally at a middle-level that is appropriate for other tools to build upon. That is, we've avoided adding API for specific schematized plots like "Histogram" or "Parallel Coords" at the Bokeh level.  It might be more reasonable e.g. to add a `wordcloud` to a higher level tool [`Holoviews`](http://holoviews.org) or [Pandas-Bokeh](https://github.com/PatrikHlobil/Pandas-Bokeh). Which might also necessitate feature work at the Bokeh level to support that better or more easily. 

cc @philippjfr for thoughts

**Comment by bryevdv** [comment]
cc @bokeh/dev as well. I'll state up front that I am inclined to close this with no action. There are probably existing JS libraries for word clouds that could be wrapped as examples, or as I suggested, this could go in a higher level too.

**Comment by bryevdv** [comment]
Closing as out of scope for Bokeh proper
