### ISSUE TITLE
Line color won't change when I use line_color for patches in theme.yml

### ISSUE THREAD

**Issue by sinazadeh** [bokeh/bokeh#11109]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
pandas: 1.2.3
python: 3.9
browser: Google Chrome: 89.0.4389.90 
OS: Windows 10
#### Description of expected behavior and the observed behavior
Line color won't change when I use line_color for patches in theme.yml
for example:
```
plot.patches('xs','ys', source = geosource, fill_color = {'field' :'data_column', 'transform' : color_mapper}, line_color = 'black')
```
works perfectly but adding this line on theme.yml won't work.

#### Complete, minimal, self-contained example code that reproduces the issue
(ne_110m_admin_0_countries.shp file is accessible by searching on google / df is a dataframe with two columns. One is the country_code and the other is some data with name data_column)
main.py:
```
gdf = gpd.read_file(ne_110m_admin_0_countries.shp)[['ADMIN', 'ADM0_A3', 'geometry']]
gdf.columns = ['country', 'country_code', 'geometry']
merged = gdf.merge(df, left_on = 'country_code', right_on = 'country_code', how = 'left')
merged_json = json.loads(merged.to_json())
json_data = json.dumps(merged_json)
geosource = GeoJSONDataSource(geojson = json_data)
plot = figure()
palette = brewer['Spectral'][10][::-1]
color_mapper = LinearColorMapper(palette = palette)
plot.patches('xs','ys', source = geosource, fill_color = {'field' :'data_column', 'transform' : color_mapper})
curdoc().theme = Theme(filename="theme.yml")
layout = column(plot)
curdoc().add_root(layout)
```
theme.yml
```
attrs:
       Patches: 
                     line_width : 0.25
                     fill_alpha : 1
                     line_color : '#000000'
```
line_width and fill_alpha works but line_color is not working in yml file.

**Comment by bryevdv** [comment]
@sinazadeh we need a complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) in order to investigate, i.e. code that we can actually run. Please add any missing imports or other code to the snippet above and either provide the data file, or change the code to use synthetic data.

**Comment by bryevdv** [comment]
close as stale / lack of MRE
