### ISSUE TITLE
[BUG] Bokeh not rendering in Jupyter Lab

### ISSUE THREAD

**Issue by Sidney-Bishop** [bokeh/bokeh#11111]
Hi 

similar to this issue: https://github.com/bokeh/bokeh/issues/10002 ( thanks to all for detailed info )

I've encountered a similar problem on MAC OS Big Sur 11.2 ( see screen grab below )

**However**, I don't have any markdown code mentioning Bokeh

Python version      :  3.8.5 (default, Sep  4 2020, 02:22:02)
IPython version     :  7.19.0
Tornado version     :  6.0.4
Bokeh version       :  2.2.3

I get the same error in Jupyter Lab.

Any suggestions would be appreciated.

<img width="1401" alt="Screenshot 2021-03-29 at 19 19 17" src="https://user-images.githubusercontent.com/7266636/112885166-52af2100-90c8-11eb-8b5e-99bc59ae678a.png">

Best Jason

**Comment by bryevdv** [comment]
What version of Jupyter-lab? what version of the (required) `jupyter_bokeh` extension?

**Comment by philippjfr** [comment]
Try upgrading to latest HoloViews and Bokeh first. `jupyter_bokeh` is not required.

**Comment by Sidney-Bishop** [comment]
> What version of Jupyter-lab? what version of the (required) `jupyter_bokeh` extension?

jupyter lab 2.2.6
jupyter_bokeh-2.0.4

**Comment by Sidney-Bishop** [comment]
> Try upgrading to latest HoloViews and Bokeh first. `jupyter_bokeh` is not required.

Theses are my version, I think they are the latest but I'll check:
Holoviews: 1.14.2
Bokeh: 2.2.3

**Comment by philippjfr** [comment]
In any case, this should go on the HoloViews issue tracker. You should upgrade to Bokeh 2.3 before doing anything else though.

**Comment by Sidney-Bishop** [comment]
> In any case, this should go on the HoloViews issue tracker. You should upgrade to Bokeh 2.3 before doing anything else though.

Thanks all for your help and apologies for miss-placed issue, I'll post it on HoloViews issue tracker if it persists after upgrade.
