### ISSUE TITLE
[BUG]  ColorBars do not update when their properties are updated

### ISSUE THREAD

**Issue by finnoshea** [bokeh/bokeh#11116]
Bokeh 2.3.0
Python 3.6.9
Tornado 6.1
Ubuntu Ubuntu 18.04.3 LTS running under Windows Subsystem for Linux
Google Chrome

When updating a property of a ColorBar, the displayed ColorBar is not modified.  I expect it to be modified.

Example of the problem:
```
from bokeh.plotting import figure, curdoc
from bokeh.colors import HSL
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, LinearColorMapper, ColorBar, Select
import numpy as np

def colorize(data,reverse=False):
    if reverse:
        return [HSL(h-180,1.0,0.5).to_rgb() for h in data]
    else:
        return [HSL(h,1.0,0.5).to_rgb() for h in data]

def update(attr,old,new):
    if menu.value == 'reverse':
        y = 360-1 * x
        c = colorize(x,reverse=True)
    else:
        y = 1 * x
        c = colorize(x)
    source.data = {'x':x,'y':y,'c':c}
    #updateColorBar(p.right[0])
    updateColorBar(p._property_values['right'][0])

def updateColorBar(cb):
    if menu.value == 'reverse':
        cb.title = 'reverse'
        u = colorize(np.linspace(0,360,101,endpoint=True),
                reverse=True)
    else:
        cb.title = 'normal'
        u = colorize(np.linspace(0,360,101,endpoint=True))
    newcm = LinearColorMapper(palette=u,low=0.0,high=2*np.pi)
    cb.color_mapper.palette = newcm.palette
    cb.color_mapper.low = newcm.low
    cb.color_mapper.high = newcm.high

# prepare some data
x = np.linspace(0,360,361,endpoint=True)
y = x
c = colorize(x)

source = ColumnDataSource({'x':x,'y':y,'c':c})

# create a new plot with a title and axis labels
p = figure(title="Simple scatter example", x_axis_label="x",
                y_axis_label="y",toolbar_location="above")

# create a plot to show the colors
p.scatter('x', 'y',size=2,color='c',source=source)

u = colorize(np.linspace(0,360,101,endpoint=True))
color_mapper = LinearColorMapper(palette=u,low=0.0,high=2*np.pi)
color_bar = ColorBar(color_mapper=color_mapper,
                     label_standoff=12,
                     title='normal')

p.add_layout(color_bar, 'right')

menu = Select(title='Order',value='normal',
                options=['normal','reverse'])
menu.on_change('value',update)

t = column(children=[menu,p])

# show the results
curdoc().add_root(t)
```

Images before and after using the Select object to try to change the point coloring (works) and the ColorBar (does not work).
![colorbar_normal](https://user-images.githubusercontent.com/26681383/113170778-b9812700-91fb-11eb-8882-a5e5e15d3cf7.jpg)
![colorbar_not_reverse](https://user-images.githubusercontent.com/26681383/113170783-bab25400-91fb-11eb-919d-eacbf51bc915.jpg)

For more testing, see the SO: https://stackoverflow.com/questions/66876346/updating-a-colorbar-in-bokeh

**Comment by finnoshea** [comment]
If I try to replace the ColorBar entirely, it disappears. Modify the update function and add a new one to create a ColorBar:

```
def update(attr,old,new):
    if new == 'reverse':
        y = 360 - 1 * x
        c = colorize(x,reverse=True)
    else:
        y = 1 * x
        c = colorize(x)
    source.data = {'x':x,'y':y,'c':c}
    cbar = p.right[0]
    #updateColorBar(cbar,new)
    p.right[0] = makeColorBar()
    print(p.right[0].visible)

def makeColorBar():
    if menu.value == 'reverse':
        title = 'reverse'
        u = colorize(np.linspace(0,360,101,endpoint=True),True)
    else:
        title = 'normal'
        u = colorize(np.linspace(0,360,101,endpoint=True))
    cm = LinearColorMapper(palette=u,low=0.0,high=2*np.pi)
    return ColorBar(color_mapper=cm,label_standoff=12,
                          title=title)
```

When I run this a different way, using ```python3 -i file_name.py``` and ask for the identity of ```p.right[0]`` I get ```ColorBar(id='1042', ...)```. If I then manually change ```menu.value = 'reverse'``` (True is printed to screen) and look at the identity of the ColorBar I get ```ColorBar(id='1057', ...)```. It appears that the new color bar isn't being pushed to the display, while the old one is being removed.

**Comment by bryevdv** [comment]
tentatively marking for `2.3.2`

**Comment by finnoshea** [comment]
> Just FYI this is probably not useful/informative, there is no connection to any Bokeh server when run this way

For sure, but I wanted to see if the ColorBar itself was changing.

For posterity, I opened this issue after coming across what I think is a similar issue in #5068.

**Comment by bryevdv** [comment]
For sure, but I wanted to see if the ColorBar itself was changing.

@finnoshea For sure but Bokeh has two mirror halves, in Python and JavaScript. What matters is that the change in python is propagated to the JS side, and then subsequently that the change on the JS side triggers something to happen (e.g. a repaint). This seems to be failing the last bit in ways specific to `ColorBar` (i.e. I don't think there is any relation to #5068)

**Comment by profxj** [comment]
FWIW, I report that I am successfully able to dynamically change `low` and `high` 
of the `color_mapper` of my `ColorBar`.  Have not tried other attributes.

v2.3.2

**Comment by Davide-sd** [comment]
With version v2.3.2 I have mixed results. Sometimes I'm able to update it, sometimes I'm not.

**Comment by Siyh** [comment]
Hi-I'm trying to figure out if I need to try and find a workaround for this bug (maybe completely clear the plot and remake it), what is the current best estimate for when a fix might be released (i.e. is it likely to make it into 2.4, when is 2.4 likely to be released etc.)? Thanks

**Comment by agharbi6** [comment]
> Hi-I'm trying to figure out if I need to try and find a workaround for this bug (maybe completely clear the plot and remake it), what is the current best estimate for when a fix might be released (i.e. is it likely to make it into 2.4, when is 2.4 likely to be released etc.)? Thanks

Not sure about the release date but I have also successfully dynamically changed the colorbar using low and high of color_mapper as well

**Comment by bryevdv** [comment]
> what is the current best estimate for when a fix might be released (i.e. is it likely to make it into 2.4, when is 2.4 likely to be released etc.)

I can't offer anything like that. We plan to release 2.4 in the next month, if this issue is something that can be fit in alongside other priorities in that time, then it will be in 2.4. If not, it won't. Bokeh is a mostly volunteer open-source project, work gets done when the people who have decided to be involved can make time. 

If you need an immediate WAR then I would suggest creating two separate colorbars, one with each different mapper, and toggling their visibility. That is frankly what I would suggest as the best approach in any case, regardless of this issue.

**Comment by Siyh** [comment]
> > what is the current best estimate for when a fix might be released (i.e. is it likely to make it into 2.4, when is 2.4 likely to be released etc.)
> 
> I can't offer anything like that. We plan to release 2.4 in the next month, if this issue is something that can be fit in alongside other priorities in that time, then it will be in 2.4. If not, it won't. Bokeh is a mostly volunteer open-source project, work gets done when the people who have decided to be involved can make time.
> 
> If you need an immediate WAR then I would suggest creating two separate colorbars, one with each different mapper, and toggling their visibility. That is frankly what I would suggest as the best approach in any case, regardless of this issue.

I was able to implement your suggested workaround, thanks for the suggestion.
