### ISSUE TITLE
[BUG] Bad formatting in tooltips with HoverTool

### ISSUE THREAD

**Issue by Mark531** [bokeh/bokeh#11127]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.3.0
python 3.7.7
Windows 10 64-bit
Edge
#### Description of expected behavior and the observed behavior
The example given in the bokeh documentation about tooltip formatting doesn't work as expected: it seems the formats are not recognized.
#### Complete, minimal, self-contained example code that reproduces the issue
The code is taken from the bokeh documentation (haven't been able to find the latest example):
http://docs.bokeh.org/en/1.0.2/docs/user_guide/examples/tools_hover_tooltip_formatting.html
```
import numpy as np

from bokeh.io import output_file, show
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure
from bokeh.sampledata.stocks import AAPL

output_file("tools_hover_tooltip_formatting.html")

def datetime(x):
    return np.array(x, dtype=np.datetime64)

source = ColumnDataSource(data={
    'date'      : datetime(AAPL['date'][::10]),
    'adj close' : AAPL['adj_close'][::10],
    'volume'    : AAPL['volume'][::10],
})

p = figure(plot_height=250, x_axis_type="datetime", tools="", toolbar_location=None,
           title="Hover Tooltip Formatting", sizing_mode="scale_width")
p.background_fill_color="#f5f5f5"
p.grid.grid_line_color="white"
p.xaxis.axis_label = 'Date'
p.yaxis.axis_label = 'Price'
p.axis.axis_line_color = None

p.line(x='date', y='adj close', line_width=2, color='#ebbd5b', source=source)

p.add_tools(HoverTool(
    tooltips=[
        ( 'date',   '@date{%F}'            ),
        ( 'close',  '$@{adj close}{%0.2f}' ), # use @{ } for field names with spaces
        ( 'volume', '@volume{0.00 a}'      ),
    ],

    formatters={
        'date'      : 'datetime', # use 'datetime' formatter for 'date' field
        'adj close' : 'printf',   # use 'printf' formatter for 'adj close' field
                                  # use default 'numeral' formatter for other fields
    },

    # display a tooltip whenever the cursor is vertically in line with a glyph
    mode='vline'
))

show(p)
```

#### Stack traceback and/or browser JavaScript console output
The code runs without error.
#### Screenshots or screencasts of the bug in action
![bokeh](https://user-images.githubusercontent.com/17707763/113512568-81644600-9565-11eb-969f-931fdf4ed68c.jpg)

**Comment by bryevdv** [comment]
Hover tool formatters dict format changed at version 2.0 ([migration notes here](https://docs.bokeh.org/en/latest/docs/releases.html#hovertool-formatters-specification)) The same full example example is in the docs is here:

https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields
