### ISSUE TITLE
line tutorial Range ValueError

### ISSUE THREAD

**Issue by msarahan** [bokeh/bokeh#1112]
I just worked through the lines tutorial (I like it - thanks), but encountered problems with the very end exercise of setting x_range and y_range parameters.  I first tried passing a list [-10,10](which is what is done in the solutions).  I got a ValueError:

ValueError: expected an instance of type Range, got [-10, 10] of type list

OK, so perhaps I'm stubborn, so I tried a tuple, wondering if better conversion existed for it:

ValueError: expected an instance of type Range, got (-10, 10) of type tuple

However, it looks like I really should be using bokeh.objects.Range1D objects, as pointed out in the next (scatter.py) example.

I've read in other issues (searching for duplicate issues) that this tutorial will be replaced soon.  Is this a general issue (bug) that lists and tuples _should_ work for this argument - or should the tutorial rework include a step to create Range1D objects?

This was done with Bokeh 0.5.2 - please disregard if the master branch fixes this behavior.

**Comment by bryevdv** [comment]
This is now trivial with `.accepts` PR incoming.

**Comment by bryevdv** [comment]
After discussion it would be preferable to have existing ranges be updated in place when feasible, but this will require some enhancements to `.accepts`

**Comment by bryevdv** [comment]
Going to close this after all, it has not seemed to be a big impediment for folks to set start/end individually.
