### ISSUE TITLE
CI is currently broken (networkx / decorator)

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11126]
ref: https://github.com/networkx/networkx/issues/4718
ref: https://github.com/networkx/networkx/issues/4722

I guess we may need a fix on our end regardless, since who knows when a new `networkx` package that  pins to `decorator < 5` might land in conda defaults. I think will need to either:

* pip install networkx, or
* lower bound to 2.5.1 to pick it up from conda-forge (much sooner than defaults, I assume)

cc @mattpap @philippjfr @bokeh/dev

**Comment by dschult** [comment]
Decorator 5.0.5 fixed this issue. So it is only a problem with decorator 5.0.0-5.0.4.

**Comment by bryevdv** [comment]
🤞 I just kicked off a merge so we can see if this can be closed https://github.com/bokeh/bokeh/actions/runs/717270418

**Comment by bryevdv** [comment]
Builds now passing, thanks for the follow up @dschult !
