### ISSUE TITLE
[BUG] Time for updating one column in a CDS depends on the total number of columns

### ISSUE THREAD

**Issue by JulianHirsch** [bokeh/bokeh#11138]
### ALL software version info:
bokeh==2.3.0
pandas==1.1.4
Microsoft Edge==89.0.774.68

### Description of expected behavior and the observed behavior
The time it takes to update a subset (one column) of a ColumnDataSource seems to increase linearely with the number of total columns in that CDS. 
I would expect to see this behaviour only for an increased number of rows to update, but not for an increased number of total columns.  
The example below measures the time it takes to update one column for different numbers of total columns with a fixed number of rows. The time plot output can be seen below.

### Complete, minimal, self-contained example code that reproduces the issue:
```py
#Using Bokeh==2.3.0 as server app
import pandas as pd
from bokeh.plotting import figure, curdoc, show
from bokeh.models import ColumnDataSource
from bokeh.layouts import layout
import random
import time
import numpy as np

N_test = 3

times_list_cols = []

def update_data(n_cols, n_rows):
    # Prepare a CDS with some random value:
    df = pd.DataFrame({"Value1": [int(random.random()*10) for i in range(n_rows)]})

    # Add n_cols additional columns with random values 
    for i in range(n_cols):
        df[f"col_{i}"] = df[f"Value1"]/i

    # Create actual CDS
    source = ColumnDataSource(df)
    
    # Update one column and make N_test time measurements
    new_column = source.data["Value1"]+1
    time_needed=[]
    for test_n in range(N_test):
        t0=time.time()
        source.data['Value1'] = new_column
        time_needed.append(time.time() - t0)
    
    return np.mean(time_needed)

# Check impact of columns and show results
times=[]
N_rows=5000
for n_cols in range(0,200):
    time_needed = update_data(n_cols=n_cols, n_rows=N_rows)
    times.append(time_needed)
    print(f"Time needed for {n_cols} cols and {N_rows} rows: {time_needed}")

plot_rows = figure(plot_width=800, plot_height=250)
plot_rows.line(x=np.arange(0,200), y=times)
plot_rows.yaxis.axis_label = 'Time in s'
plot_rows.xaxis.axis_label = 'Number of Columns in CDS'
plot_rows.title.text = "Increasing the number of COLUMNS in a CDS"

# Check impact of rows and show results
times=[]
N_cols=100
for n_rows in range(0,20000,100):
    time_needed = update_data(n_cols=N_cols, n_rows=n_rows)
    times.append(time_needed)
    print(f"Time needed for {N_cols} cols and {n_rows} rows : {time_needed}")

plot_cols = figure(plot_width=800, plot_height=250)
plot_cols.line(x=np.arange(0,20000,100), y=times)
plot_cols.yaxis.axis_label = 'Time in s'
plot_cols.xaxis.axis_label = 'Number of Rows in CDS'
plot_cols.title.text = "Increasing the number of ROWS in a CDS"

show(layout([[plot_rows],[plot_cols]]))

```

### Screenshots:
![image](https://user-images.githubusercontent.com/60778354/113834438-1f852580-978b-11eb-8f07-68b52112e380.png)

**Comment by mattpap** [comment]
This is currently by design, i.e. updating one column requires re-evaluation of the entire `dict` (under `source.data`). I think this could be optimized and aligned with patching behavior, especially given that we already wrap built-in `dict` to detect in-place updates.

**Comment by JulianHirsch** [comment]
@mattpap Does this mean, that changing only one column with `source.patch` should be independent of the total number of columns, regarding the consumed time? 

Changing the obove function `update_data()` to use `source.patch` as shown in the following, I get the same behavior with linear increasing time consumption based on the total number of columns:

`
def update_data(n_cols, n_rows):
    # Prepare a CDS with some random value:
    df = pd.DataFrame({"Value1": [int(random.random()*10) for i in range(n_rows)]})

    # Add n_cols additional columns with random values 
    for i in range(n_cols):
        df[f"col_{i}"] = df[f"Value1"]/i

    # Create actual CDS
    source = ColumnDataSource(df)
    
    # Update one column and make N_test time measurements
    new_column = source.data["Value1"]+1
    patches = {'Value1': [(slice(len(new_column)), [v for v in new_column])]}

    time_needed=[]
    for test_n in range(N_test):
        t0=time.time()
        source.patch(patches)
        time_needed.append(time.time() - t0)
    
    return np.mean(time_needed)
`

**Comment by bryevdv** [comment]
@mattpap  it is not by design. There is existing special case code in the column data descriptor that tries to detect only the columns that changed—it's just not working anymore

**Comment by bryevdv** [comment]
Looking into this, it comes down to this call:
```
        # re-validate because the contents of 'old' have changed,
        # in some cases this could give us a new object for the value
        value = self.property.prepare_value(obj, self.name, value
```
which triggers a revalidation of the entire value in `-notify_mutated` even when there is an update hint. 

Secondarily, at least at a quick glance, `PropertyValueColumnData.update` is being called at least two more times than I would expect for a single column update.

**Comment by bryevdv** [comment]
Here is quick diff that just skips re-validation if there is a diff, that immediately makes the time to set a column become constant, independent of the number of columns

<details>

```diff
diff --git a/bokeh/core/property/bases.py b/bokeh/core/property/bases.py
index a8d4fc989..0fd6e04c3 100644
--- a/bokeh/core/property/bases.py
+++ b/bokeh/core/property/bases.py
@@ -60,6 +60,7 @@ from .singletons import (
 )

 if TYPE_CHECKING:
+    from ...document.events import DocumentPatchedEvent
     from ..types import ID

 #-----------------------------------------------------------------------------
@@ -334,7 +335,7 @@ class Property(PropertyDescriptorFactory[T]):
         """
         return value

-    def prepare_value(self, owner: HasProps | Type[HasProps], name: str, value: Any) -> T:
+    def prepare_value(self, owner: HasProps | Type[HasProps], name: str, value: Any, hint: DocumentPatchedEvent | None = None) -> T:
         if value is Intrinsic:
             value = self._raw_default()
         if value is Undefined:
diff --git a/bokeh/core/property/container.py b/bokeh/core/property/container.py
index 04f9b6cff..044d390d8 100644
--- a/bokeh/core/property/container.py
+++ b/bokeh/core/property/container.py
@@ -251,6 +251,11 @@ class ColumnData(Dict):
                 new_data[key] = self.values_type.from_json(value, models=models)
         return new_data

+    def prepare_value(self, owner: HasProps | Type[HasProps], name: str, value: Any, hint: DocumentPatchedEvent | None = None):
+        if hint is None:
+            return super().prepare_value(owner, name, value, hint)
+        return value
+
     def serialize_value(self, value):
         return transform_column_source_data(value)

diff --git a/bokeh/core/property/descriptors.py b/bokeh/core/property/descriptors.py
index 47d2ea723..ce4500f8f 100644
--- a/bokeh/core/property/descriptors.py
+++ b/bokeh/core/property/descriptors.py
@@ -591,7 +591,7 @@ class PropertyDescriptor(Generic[T]):

         # re-validate because the contents of 'old' have changed,
         # in some cases this could give us a new object for the value
-        value = self.property.prepare_value(obj, self.name, value)
+        value = self.property.prepare_value(obj, self.name, value, hint)

         self._set(obj, old, value, hint=hint)
```
</details>

This works by overriding `prepare_value` on `ColumnData` and skipping the work if the `hint` is not None.  It's maybe possible this is just a reasonable thing to do as-is. It will take a little more considetation. It's possible we can/should still call `prepare_value` but only on subset of data covered by the hint. 

In any case we might also want to issue a warning if the base class `prepare_value` ever gets passed a `hint`, since that should not happen.

**Comment by bryevdv** [comment]
There is also another option, maybe better. It is specifically the validation inside `prepare_value` that is expensive:
```
            if validation_on():
                self.validate(value)
``` 
Se we could keep the one single `prepare_value` on the base, and plumb the hint through to the `validate` method, though if we do that we would probably want to do that for `transform` as well. 

As an aside @JulianHirsch for now, you could disable validation:

https://docs.bokeh.org/en/latest/docs/reference/core/properties.html?highlight=validation#validation-control
