### ISSUE TITLE
[BUG] Inconsistent hatch rotation

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#11149]
When rotating glyphs with a hatch pattern, the hatch rotates for markers but does not rotate for non-markers.
```python
from bokeh.layouts import row
from bokeh.plotting import figure, curdoc

backend = 'canvas'
fig = figure(width=300, height=300, output_backend=backend,
             title=backend)

x = [0, 1, 2]
angle = [0, 0.3, 0.6]
c = 'orange'
fig.rect(x=x, y=3, angle=angle, hatch_pattern='|', fill_color=c, width=0.7, height=0.7)
fig.square(x=x, y=2, angle=angle, hatch_pattern='|', fill_color=c, size=50)
fig.ellipse(x=x, y=1, angle=angle, hatch_pattern='|', fill_color=c, width=0.8, height=0.5)
fig.hex(x=x, y=0, angle=angle, hatch_pattern='|', fill_color=c, size=50)

curdoc().add_root(fig)
```
![Screenshot_2021-04-08 Bokeh Application](https://user-images.githubusercontent.com/580326/113989219-21f98500-9848-11eb-8d2b-dfee510aea7c.png)

This might be on purpose but probably consistent behaviour is preferred.

(bokeh 2.3.0, python 3.9 via anaconda on Ubuntu 20.10).

**Comment by mattpap** [comment]
Hatch patterns should not rotate with glyph rotation. Any rotatiotion of a pattern should be a part of a pattern definition. I think reason for this behavior, is that some glyphs paint during path construction (when glyph rotation is still applied) (markers in particular) and some after.

**Comment by ianthomas23** [comment]
Yes, here's the marker code with rendering occurring within the rotation
https://github.com/bokeh/bokeh/blob/ed54705d627ae500509e57fe071fc7a60fc8a951/bokehjs/src/lib/models/glyphs/marker.ts#L45-L51
and a typical marker rendering function
https://github.com/bokeh/bokeh/blob/ed54705d627ae500509e57fe071fc7a60fc8a951/bokehjs/src/lib/models/glyphs/defs.ts#L238-L246
