### ISSUE TITLE
[BUG] CDSView is inactive for varea

### ISSUE THREAD

**Issue by Mark531** [bokeh/bokeh#11144]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.3.0
python 3.7.7
Windows 10 64-bit

#### Description of expected behavior and the observed behavior
Calling varea in conjunction with a CDSView should only fill the filtered parts of the graph. But all the graph is filled.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import pandas as pd
from bokeh.models import ColumnDataSource, CDSView, BooleanFilter
from bokeh.plotting import figure, show

df = pd.DataFrame({"x":[1,2,3,4,5], "y1":[10,20,15,30,25], "y2":[14,22,11,32,20]})

source = ColumnDataSource(df)
p = figure(plot_width=400, plot_height=300)
view = CDSView(source=source, filters=[BooleanFilter(df.y1 < df.y2)])
p.varea(x="x", y1="y1", y2="y2", color="green", source=source, view=view)
show(p)
```

#### Stack traceback and/or browser JavaScript console output
No error

#### Screenshots or screencasts of the bug in action
![screenshot](https://user-images.githubusercontent.com/17707763/113937648-c6a0a600-97f9-11eb-8332-6122702727b2.jpg)

**Comment by bryevdv** [comment]
@Mark531 This is working as intended. `varea` is only ever going to draw one single connected area. If you add a view/filter to one, it will just throw those points out and connect whatever is left. I am afraid if you want disjoint regions (which is what I am inferring that you want), then you will need to use one of the glyphs that is specifically intended for that, e.g `patches` or `multi_polygons`.

One reason this is so it that is extremely easy to get into cases that don't actually make sense, which is in fact the case above. What would supposed to happenfor the lone isolated points at x=4? That is not enough points to define an area.

**Comment by bryevdv** [comment]
cc @bokeh/dev there is not currently any clean way to restrict things in the type system, but I would be 👍 to explore ways to restrict views to only scatter and line glyphs. I think their application to area-like glyphs is dubious at best.

**Comment by Mark531** [comment]
@bryevdv Hello, for me an area can be perfectly defined for 2 isolated points: it would be the line connecting them. My intent was just to generate several unconnected areas. But ok, I will check patches or multi_polygons.

**Comment by bryevdv** [comment]
> Hello, for me an area can be perfectly defined for 2 isolated points:

This is problematic for a number of reasons:
* they are not the same to the low level browser canvas API and have to be handled differently
* same for hit-testing, they cannot be handled with the same codepaths
* What if you otherwise want the line color of the area to be None?

As well as others. Tying to support this in `varea` would *drastically complicate `varea`, and the effort/reward is simply not justifiable given that it does not at all seem to be a common need, and given that there are alternatives elsewhere (patches, etc)

**Comment by bryevdv** [comment]
@Mark531 let's move support / usage questions to the discourse:

https://discourse.bokeh.org

**Comment by Mark531** [comment]
Ok, I created this topic:
https://discourse.bokeh.org/t/how-to-fill-disconnected-areas/7590
