### ISSUE TITLE
embedding content with session_id returns blank page

### ISSUE THREAD

**Issue by drdelayismysenpai** [bokeh/bokeh#11151]
When trying to lock content and serve with flask and server_document with the following code an empty page is returned.
`bokeh serve app.py --session-ids external-signed`

and the following code
```
from bokeh.embed import server_document
from bokeh.util import token
from bokeh.util import token
from flask import Flask, render_template, render_template_string, request, url_for, redirect, session

app = Flask(__name__)

app_html = """
<!DOCTYPE html>
<html>
<body>
<h2>JavaScript in Body</h2>
<p id="demo"></p>
{{ bokeh_script | safe }}
</body>
</html> 
"""
@app.route('/vis')
def visualization():
    s_id = token.generate_session_id(sec_id,True)
    url = str("http://host:port/bokeh_server?bokeh-session-id={}&".format(s_id))
    bokeh_script = server_document(url=url)
    return render_template_string(app.html, bokeh_script=bokeh_script)
```

Every of the following url options has problems:

`url = str("http://roscontainer:5007/bokeh_server")` cant use session_id, brings up plot in the right way
`url = str("http://host:port/bokeh_server?bokeh-session-id={}".format(s_id))`  brings up session id error due to missing ampersand at the end -> not in docs  
`url = str("http://host:port/bokeh_server?bokeh-session-id={}&".format(s_id))` displays empty block where bokeh should be. 

The problem can only be within the formatting of the url. The session id of the last url is correct, but it returns no plot. As far as I can see, this is a bug.
spent way too much time on this.

**Comment by bryevdv** [comment]
@drdelayismysenpai `server_document` is not intended fo embedding sessions, full stop. For that, there is `server_session`, documented here:

https://docs.bokeh.org/en/latest/docs/user_guide/embed.html#app-sessions

>  spent way too much time on this.

The project discourse is a great resource for getting help with usage questions:

https://discourse.bokeh.org/
