### ISSUE TITLE
[BUG] Non-selected hatching not grayed out

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#11154]
Another hatch rendering bug.  Non-selected glyphs that include a hatch pattern have their line and fill visuals grayed out, but not their hatching.
```python
from bokeh.plotting import figure, curdoc

fig = figure(width=250, height=200, output_backend='canvas', tools=['box_select'])
fig.rect(x=[0, 1, 2], y=3, width=0.7, height=0.7, angle=[0, 0.3, 0.6],
         hatch_pattern='x', fill_color='orange', )

curdoc().add_root(fig)
```
Serve this script, then use the Box Select tool to select the central rect to give:
![Screenshot_2021-04-09 Bokeh Application](https://user-images.githubusercontent.com/580326/114147187-5afd2c80-9910-11eb-903b-1fcc768ef6c4.png)
I'd expect the unselected hatching to have a lower alpha.

(Bokeh 2.3.0, python 3.9, ubuntu 20.10).

**Comment by mattpap** [comment]
This is a plotting API issue. The default alpha for non-selection glyph is not applied to hatch visuals (`pop_visuals()` in `bokeh.plotting._renderer`). A fix needs to be applied to bokehjs' plotting API as well.
