### ISSUE TITLE
[BUG] DataTable stuttering/unperformant scrolling

### ISSUE THREAD

**Issue by rynkk** [bokeh/bokeh#11167]
Bokeh 2.3.1, Google Chrome Version 89.0.4389.128, Win 10 Version 10.0.19041 Build 19041

Bokehs `DataTable`s seem to have performance issues when scrolling quickly.

The underlying js-library `slickgrid` feels very fluid in comparison.

example_code:
```
from bokeh.io import show
from bokeh.models import TableColumn, DataTable, ColumnDataSource

headers = [str(i) for i in range(25)]
DATA_POINT_COUNT = 5000

columns = [TableColumn(field=h) for h in headers]
data = {c.field: [i for i in range(DATA_POINT_COUNT)] for c in columns}
d = DataTable(columns=columns, source=ColumnDataSource(data=data), width=800, height=800)

show(d)
```

performance_tab: [gyazo](https://gyazo.com/e034592c34936160a1444b71b9bbeb88) 3.5s blocking time out of 7s recording
(Note: In 2.2.0 scripting took more time than rendering)
example_video: [gyazo](https://gyazo.com/64c821a8d53ef642c0a53ace0abcbf1c)

what it should feel like: [github.io](http://mleibman.github.io/SlickGrid/examples/example4-model.html)

**Comment by bryevdv** [comment]
FWIW on OSX w/ safari and Chrome I can't actually tell any subjective difference between the Bokeh version and the linked "bare" slickgrid version. Both blank (briefly) during scrolling. Will have to boot into windows and see if any difference is evident there specifically.

**Comment by jeffreymonaco** [comment]
My tests match Bryan's reported experience. Also on OSX (Big Sur) with latest Chrome Version 89.0.4389.114 (Official Build) (x86_64).

**Comment by bryevdv** [comment]
It's actually weird. Both examples have a call stack that repeatedly gets down to `handleScroll`. The bare example basically stops there, but the Bokeh example clearly descends much further into all sorts renders, redraws, row cleanups. These all appear to be slickgrid functions, but I am not sure what would cause them to trigger in the bokeh case but not the bare case. I suppose some options:

* different versions of slickgrid
* using slickgrid in some sub-optimal way
* unavoidable bokeh-related overhead

All that said, the overall time for `handleScroll` is roughly the same ~40ms in *both* cases, presumably why it does not really appear to behave any differently for me.

**Comment by rynkk** [comment]
Upon further investigation and creating a ~1:1 replication with slickgrid.js I realized that this is simply a limitation of slickgrid/jquery's rendering bloat.
Reducing the tables total size can cut this down by a lot.

<details>
  <summary>HTML-Equivalent</summary>
  
  
  ```javascript
  <!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico" />
  <title>SlickGrid example 1: Basic grid</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/6pac-slickgrid/2.4.34/slick.grid.min.css" integrity="sha512-Kl/knC6ZpWLDZdJnsvPuGO+v7l0FAUHWkIpMZ72lnClWexK5pO+m7+9RYjKXbMe5hZmu7YecXMFfr8/Q2M18Fw==" crossorigin="anonymous" />
</head>
<body>
<style>
html, body {
    height: 100%;
}
#myGrid {
    min-height: 100%;
    height: auto !important;
    height: 100%;
    margin: 0 auto -20px;
}

</style>

<div id="myGrid"></div>

<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/6pac-slickgrid/2.4.34/lib/jquery.event.drag-2.3.0.min.js" integrity="sha512-KDxEu6O4w1m+7VXY3Nu3PuE9aix43Tj4GsNcr/NWZIYCOx7UTeemZ1kyqpzMhm7TEuSD3bn6pu3d7v6nskjo+A==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/6pac-slickgrid/2.4.34/slick.core.min.js" integrity="sha512-JsOv/yrX9sZxiOqthtYzjzf5FvA8Dr2EqZxslf1q//mmfy4EvAvNUm425OT4UrOTHOqpZCqKVWjbgRPa9TCllg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/6pac-slickgrid/2.4.34/slick.grid.min.js" integrity="sha512-Ha8HG7pDpsiZrH5ni3ryUMm5kn8CC3DtTipCzHgPiWHN8sxGcJG5iA4f1B5KNLTvnSkPVHFUyxtesz3yT64Ysg==" crossorigin="anonymous"></script>

<script>

  var AMOUNT_COLS = 25
  var AMOUNT_ROWS = 2500

  var grid;
  var columns = [
  ];

  var data = [];
  for (var i=0; i<AMOUNT_ROWS; i++) {
    data[i] = {}
    for (var j=0; j<AMOUNT_COLS; j++){
      str = "abc"+j
      data[i][str]=i+"longdatalonglongdata"
    }
  };

  for (var i=0; i<AMOUNT_COLS; i++){
    columns.push({id: "abc"+i, name: "Abc"+i, field: "abc"+i})
  }
  console.log(data)
  console.log(columns)

  var options = {
    enableCellNavigation: true,
    enableColumnReorder: false
  };

  $(function () {
    grid = new Slick.Grid("#myGrid", data, columns, options);
  })
</script>
</body>
</html>
  ```
  
</details>

**Comment by bryevdv** [comment]
FWIW We are hoping to move to a more modern and maintained table widget on the future.
