### ISSUE TITLE
[BUG] Do not make room for invisible tick labels

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11162]
```py
from bokeh.plotting import figure, show
from bokeh.models import LinearAxis

p = figure()
p.add_layout(LinearAxis(major_label_text_color=None), "right")
p.add_layout(LinearAxis(major_label_text_color=None), "above")

p.axis.major_tick_in = 10
p.axis.major_tick_out = 0
p.axis.minor_tick_in = 5
p.axis.minor_tick_out = 0

p.line([-10,10], [-10,10])
show(p)
```

produces:

<img width="614" alt="Screen Shot 2021-04-12 at 4 19 36 PM" src="https://user-images.githubusercontent.com/1078448/114474352-e4c82680-9baa-11eb-9346-3b6831982276.png">

Since there are no tick labels (or axis label) on the RHS side, the toolbar should not be set so far off.

**Comment by bryevdv** [comment]
As an aside @mattpap why is this line a `sum` and not `max`?

https://github.com/bokeh/bokeh/blob/97ded7d2fdb04cad3183181bf88833f8b857b153/bokehjs/src/lib/models/axes/axis.ts#L343

**Comment by mattpap** [comment]
> (...) why is this line a sum and not max?

Because it sums labels extents in multi-line (categorical axes) setup. For non-categorical axes it's just one value.
