### ISSUE TITLE
[BUG] Layout regression in panel introduced by PR #11123

### ISSUE THREAD

**Issue by xavArtley** [bokeh/bokeh#11188]
On @mattpap  recommandation, I re-post here the issue opened on panel https://github.com/holoviz/panel/issues/2228

**Comment by mattpap** [comment]
Looking at this and issue #11161, it seems that they are related. In both cases suggested width/height is not respected, resulting in tool small layouts.

**Comment by MarcSkovMadsen** [comment]
I see many and more Panel users affected by this.
