### ISSUE TITLE
[BUG] Legend item is not rendered when there's no data

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#11193]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
```
Python version      :  3.7.2 (default, Dec 29 2018, 06:19:36) 
Tornado version     :  6.1b2
Bokeh version       :  2.3.1-2-ge93044b43
node.js version     :  v15.14.0
npm version         :  7.7.6
```
#### Description of expected behavior and the observed behavior
The code below should show a proper legend with one item rendered according the first line definition.
Instead, only the legend item label is rendered - not the line itself.
Initially brought to attention in [this SO comment](https://stackoverflow.com/questions/60829090/how-to-add-span-to-figure-legend-in-bokeh/60829528?noredirect=1#comment118825847_60829528).

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource

p = figure()

p.line([], [], legend_label='span',
       line_dash='dotdash', line_color="black", line_alpha=0.7)

ds = ColumnDataSource(dict(x=[0, 1], y=[0, 1]))
p.circle('x', 'y', source=ds)

show(p)
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/4410314/115865709-60df2b80-a441-11eb-8adf-89e1a3ea7b13.png)

**Comment by mattpap** [comment]
This is currently intentional:
https://github.com/bokeh/bokeh/blob/9e5a17bff08b547ac5f718f807f55624f6fdbe6e/bokehjs/src/lib/models/renderers/glyph_renderer.ts#L351-L352
but it works without this check, so I presume we can remove this code. We just need to validate that this works for all glyphs.

**Comment by bryevdv** [comment]
What is supposed to happen if the glyph specifies any visual property at all a CDS column field? I don't think this kind of legend can ever be made to work properly in all circumstances. Rather than have a half-broken feature I would rather solve this by offering https://github.com/bokeh/bokeh/issues/10776

**Comment by p-himik** [comment]
#10776 handles only lines and rects, and doesn't solve the more general problem of wanting to have a stable legend with a predefined set of items that doesn't depend on the actual data.

Perhaps a better way to handle it, which should also handle #10776, is to allow adding any glyph at all to the legend explicitly.

**Comment by bryevdv** [comment]
@p-himik Can you write up your ideas in a little more detail in  #10776 and then we can close this issue in favor of that one.
