### ISSUE TITLE
[BUG] Cannot clear active of RadiGroup

### ISSUE THREAD

**Issue by maeglin89273** [bokeh/bokeh#11203]
## Bug Description
Bokeh version 2.3.1
In the documentation, RadioGroup's active state is nullable. However, if I set active to None, the error occurs in the browser and the state remains. This still works in version 2.2.1.

## Example Code
```
# test_radio_group.py
from bokeh.io import curdoc
from bokeh.models import Button, RadioGroup

clear_btn = Button(label='clear')
def clear_active():
    radio_btn_group.active = None

clear_btn.on_click(clear_active)
radio_btn_group = RadioGroup(labels=['a', 'b', 'c'], active=1)
curdoc().add_root(radio_btn_group)
curdoc().add_root(clear_btn)
```
run:
bokeh serve test_radio_group.py

### Documentation
![Screenshot from 2021-04-26 12-02-55](https://user-images.githubusercontent.com/5237288/116027431-734aa680-a687-11eb-9c70-e2fa7e1e2544.png)

### Browser Console Error
![Screenshot from 2021-04-26 11-48-04](https://user-images.githubusercontent.com/5237288/116027085-89a43280-a686-11eb-85a9-c2d21f1abef3.png)

**Comment by bryevdv** [comment]
@maeglin89273 please add the missing portions of the example code so that it is a *complete*  [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by maeglin89273** [comment]
@bryevdv Import statements added. Thanks!

**Comment by mattpap** [comment]
In bokeh `RadioGroup.active` can be nullable, but bokehjs doesn't allow this, both on API and implementation level. I have mixed feelings about allowing this.

**Comment by mattpap** [comment]
Actually given that `RadioButtonGroup` already supports this, then this should be considered as a bug.
