### ISSUE TITLE
[BUG] Conflicting test dependencies in downstream CI build

### ISSUE THREAD

**Issue by jrbourbeau** [bokeh/bokeh#11211]
In https://github.com/bokeh/bokeh/pull/11207 we observed that `bokeh`s own test dependencies can sometimes conflict with test dependencies of other downstream projects. For example, `flaky` (used by `bokeh`) and `pytest-rerunfailures`  (used by `dask` / `distributed`) both register their own `flaky` `pytest` marker which can lead to errors when trying to run tests.

As a temporary workaround, we're attempting to uninstall `flaky` in the downstream CI build over in https://github.com/bokeh/bokeh/pull/11207. However, it would be good to revisit this in the future with a more long-term fix.

**Comment by bryevdv** [comment]
Probably the best solution is a much more minimal conda env file just for downstream tests.

**Comment by bryevdv** [comment]
@mattpap  suggests changing directory to avoid top-level conftest may help
