### ISSUE TITLE
[BUG] Links to Line Properties gives 404 in user guide

### ISSUE THREAD

**Issue by EricThomson** [bokeh/bokeh#11215]
The link to `Line Properties` in the following sections of the User Guide yield a 404:
- https://docs.bokeh.org/en/latest/docs/user_guide/styling.html#lines
- https://docs.bokeh.org/en/latest/docs/user_guide/styling.html#minor-lines

The link in both cases directs to:
https://docs.bokeh.org/en/latest/docs/user_guide/Lineproperties

I think they should direct to:
https://docs.bokeh.org/en/latest/docs/user_guide/styling.html#line-properties

Sorry I don't have time to to a PR right now.

**Comment by bryevdv** [comment]
cc @tcmetzger

**Comment by tcmetzger** [comment]
Indeed, some of the internal links in styling.rst were broken after hanging headlines from titles to sentence case. PR #11223 fixes those links (based on the 2.3 branch). For 2.4, I would like to use `rst_epilog` (#11187) to fix this - that would be more consistent than forward porting my fix from the 2.3 branch.

**Comment by bryevdv** [comment]
@tcmetzger you will have to update and rebase the current PR to get the CI fixes on `branch-2.4` FWIW I am also OK with just landing this on `branch-2.4` and not working about 2.3

**Comment by tcmetzger** [comment]
@bryevdv  PR #11187 (rst_epilog) already includes a fix for this issue - so if we are OK to not have a fix in 2.3, we could just close #11223.
