### ISSUE TITLE
Time period x_axis_type

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1121]
In plotting timeseries, sometimes the x_axis_type might be a period range rather than a datetime. For example you want to plot an aggregation by week, month, year...

Pandas handles that with a period_range and a periodindex:
http://pandas.pydata.org/pandas-docs/stable/timeseries.html#periodindex-and-period-range

In Bokeh right now, you have to give it a date. For example, in the previous existing downloads app, you'd have to generate an artificial date to assign that aggregation (e.g. first day of the month, first day of the year), but it get's more complicated if you have to do first day of a week.

```
       daily   = lambda x: datetime.date(x.year, x.month, x.day),
       monthly = lambda x: datetime.date(x.year, x.month, 1),
       yearly  = lambda x: datetime.date(x.year, 1, 1),
```

Could we have a time period x_axis_type? Otherwise, what alternative would you recommend for plotting weekly aggregation functions?

cc: @bryevdv

As an alternative, I've tried to set a week string by doing: 

``` python
df['week']=df['date'].map(lambda x: str(x.year)+'/'+ str(x.isocalendar()[1]))
```

But I have too many weeks and the result is:
![screen shot 2014-09-02 at 5 07 12 pm](https://cloud.githubusercontent.com/assets/4940549/4126562/8e26c840-32ed-11e4-90e4-54189679841c.png)

**Comment by bryevdv** [comment]
There are now fixed interval tickers as well as possibilities for custom extension tickers to accomplish any desired behavior. I think those can suffice
