### ISSUE TITLE
[BUG] After upgrade to Bokeh 2.3.1 multiple plot stopped to work

### ISSUE THREAD

**Issue by georgesimeo** [bokeh/bokeh#11222]
Multiple plot WORKS fine with: 

OS: Ubuntu 20.04.2 LTS
Python version      :  3.7.7 (default, Mar 26 2020, 15:48:22) 
IPython version     :  7.13.0
Tornado version     :  6.0.4
Bokeh version       :  2.0.1

conda version : 4.8.3
conda-build version : 3.18.11
python version : 3.7.7.final.0
virtual packages : __glibc=2.31

I've got blank page, after upgrade Bokeh plot stopped to work for the following configuration:

OS: Ubuntu 20.04.2 LTS
Python version      :  3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
IPython version     :  7.22.0
Tornado version     :  6.1
Bokeh version       :  2.3.1

conda version : 4.10.1
conda-build version : 3.21.4
python version : 3.8.8.final.0
virtual packages :  __glibc=2.31=0

Here is the code for plotting several curves within one  tab.
The last curve has different length from other two.

```
fig.line(LDates, 0.7 * N * np.ones(len(LDates)), legend_label="70% of the population", line_color="red", line_width=2, line_dash="4 4")
fig.line(LDates, R, legend_label="Removed cases", line_width=1, line_color="darkmagenta")    
fig.line(VDates, cumVAC, legend_label="Vaccinated persons", line_width=1, line_color="blue")
```
Console output 

01:35:26.516 [bokeh] data source has columns of inconsistent lengths 2 bokeh-2.3.1.min.js:222:1079
01:35:26.592 Uncaught (in promise) Error: Size mismatch
t https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:176
    assert https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:176
    select https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:190
    set_data https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:263
    set_data https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:226
    lazy_initialize https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:226
    c https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:287
    build_views https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:287
    build_renderer_views https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:520
    lazy_initialize https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:520
    c https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:287
    build_views https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:287
    build_child_views https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:506
    lazy_initialize https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:506
    c https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:287
    build_views https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:287
    build_child_views https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:506
    lazy_initialize https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:506
    c https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:287
    build_views https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:287
    build_child_views https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:506
    rebuild https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:506
    connect_signals https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:505
    s https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:207
    emit https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:180
    emit https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:180
    _setv https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:179
    setv https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:179
    apply_json_patch https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:165
    _handle_patch https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:588
    handle https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:588
    _steady_state_handler https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:585
    _current_handler https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:585
    _on_message https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:585
    onmessage https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:585
    connect https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:585
    connect https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:585
    pull_session https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:585
    d https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:584
    add_document_from_session https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:584
    w https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:163
    embed_items https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:163
    embed_document blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:114
    fn blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:118
    fn blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:134
    safely https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:593
    fn blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:108
    inline_js blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:137
    inline_js blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:139
    run_inline_js blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:150
    <anonymous> blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:161
    run_callbacks blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:27
    run_callbacks blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:25
    load_libs blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:45
    <anonymous> blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:159
    <anonymous> blob:http://localhost:8888/614df897-5050-493d-a1cd-2f2e6d887e65:164

 I tried to use figure multi_line and got more issues
 the auto scale is wrong and also can't add different labels as a list for each separate plot.

**Comment by bryevdv** [comment]
> data source has columns of inconsistent lengths

@georgesimeo This is telling you have a usage error. This has *always* been a usage error, but it used to be undefined behavior in the past, possibly "working" or more likely failing silently in some way. Now it raises an error. However, it is (and has always been) a bedrock assumption that all columns in a Bokeh ColumnDataSource all must have the same length at all times. 

If you'd like to discuss how to fix up your your code, the discourse is the appropriate place for support questions: https://discourse.bokeh.org/
