### ISSUE TITLE
Simplify instructions for GOOGLE_API_KEY

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11242]
In the Documentation section of the Dev Docs, we have detailed instructions on how to set `GOOGLE_API_KEY=some_value`. When creating the [current version of this page](http://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html#preparing-your-environment), I pretty much just copied and edited that section from an older version of the docs. 

Having set up a docs dev environment for myself and others a few times now, I notice that I always use `conda env config vars set GOOGLE_API_KEY=some_value` across any kind of platform. This way, this variable becomes part of the conda environment and is loaded automatically each time I `conda activate bkdev`. Is there any reason not to change the "[Preparing your environment](http://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html#preparing-your-environment)" section to use  `conda` instead of whatever mechanism each OS offers?

**Comment by bryevdv** [comment]
I was not aware conda env could do this. Seems like a reasonable/useful thing to me

**Comment by tcmetzger** [comment]
Yes, that's a neat feature: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables

We could also think about setting `GOOGLE_API_KEY` somewhere in our `environment.yml`, that should also be possible, I believe.

**Comment by bryevdv** [comment]
I feel like an explicit step is better than the env file. Putting in the env files means they would affect CI, but CI needs to use real credentials. Putting in the env file risks accidentally leaking a real credential, and might trip up GitGuardian checks even if it is a fake credential.
