### ISSUE TITLE
[BUG] Name and id attributes are not propagated for buttons, paragraph and other widgets by Bokeh.embed.embed_item

### ISSUE THREAD

**Issue by gh4ag** [bokeh/bokeh#11263]
I am refering to this Bokeh discussion:
https://discourse.bokeh.org/t/button-attribute-name-not-shown-in-browser-inspect-elements/3377

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

- bokeh: 2.3.1
- python: Python 3.9.4
- OS: OSX 10.15.7
- browser: Chrome, Firefox
- usage: with fastApi, Bokeh content is provided to my javascript as a json string through a GET request. Then it is included on the page using Bokeh.embed.embed_item(json_reponse)

#### Description of expected behavior and the observed behavior

The attributes `name`and `id` present in the json object passed to `Bokeh.embed.embed_item` is not alway propagated in the html output.

For instance, it works for `MultiSelect` or `Input` widgets but not for `Button` widgets.

It would be nice to have them in order to catch events from my own javascript code.

#### Complete, minimal, self-contained example code that reproduces the issue

Project structure:

|-main.py
|-index.html

**index.html**

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <!-- Bokeh CDN -->
  {{ bokeh_resources |safe }}
  <!-- END Bokeh CDN -->
  <script >
  //Wait for the DOM tree to be loaded
    (function () {
      console.log("Fetching bokeh content.")
      fetch('http://127.0.0.1:8000/init')
        .then(function (response) {
          response.json()
            .then(function (item) {
              console.log("Bokeh json item:", item);
              Bokeh.embed.embed_item(JSON.parse(item), "bokeh_block")
            });
        })
    })();
  </script>
  <title>Dashboard</title>
</head>

<body>
  <div id="bokeh_block"></div>
</body>
</html>
```

**main.py**

```python
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
import json
from bokeh.resources import CDN # to put Bokeh's JS and CSS CDN in the <head> from 
from bokeh.embed import json_item # convert python to json for loading from JS
from bokeh.layouts import column
from bokeh.models import Button, Paragraph, MultiSelect, Dropdown

# lunch the API server
app = FastAPI()
# tell where to find templates
templates = Jinja2Templates(directory="./")

# used index.html as root file
@app.get("/", response_class=HTMLResponse)
async def main(request: Request):
	global templates, frames_id
	bokeh_resources =  CDN.render() # add bokeh script and link imports 
	return templates.TemplateResponse("index.html", context={"request": request, "bokeh_resources":bokeh_resources})

@app.get("/init")
def read_root():
	button = Button(label="MyButton", name="button1")
	paragraph = Paragraph(text="My paragraph", name="paragraph1")
	multi = MultiSelect(options=["1", "2"], name="multi1")
	dropdown = Dropdown(menu=["A", "B"], name="dropdown2")
	col = column(button, paragraph, multi,dropdown )
	return json.dumps(json_item(col))
```

Code to run the fastAPI server:

```zsh
uvicorn main:app --reload
```

#### Stack traceback and/or browser JavaScript console output

Console output:
```text
Bokeh json item: 
{"target_id": null,
 "root_id": "1005",
 "doc": {"defs": [], "roots": {"references": [{"attributes": {"icon": null, "label": "MyButton", "name": "button1"}, "id": "1001", "type": "Button"}, {"attributes": {"name": "multi1", "options": ["1", "2"]}, "id": "1003", "type": "MultiSelect"}, {"attributes": {"children": [{"id": "1001"}, {"id": "1002"}, {"id": "1003"}, {"id": "1004"}]}, "id": "1005", "type": "Column"}, {"attributes": {"name": "paragraph1", "text": "My paragraph"}, "id": "1002", "type": "Paragraph"}, {"attributes": {"icon": null, "menu": ["A", "B"], "name": "dropdown2"}, "id": "1004", "type": "Dropdown"}], "root_ids": ["1005"]}, "title": "", "version": "2.3.1"}}
```

#### Screenshots or screencasts of the bug in action

<img width="329" alt="Capture d’écran 2021-05-12 à 16 46 54" src="https://user-images.githubusercontent.com/9591954/117995578-ba9c8c80-b341-11eb-9641-5e8d434fe5e7.png">

HTML output for the button widget:
```html 
<div class="bk" style="position: relative; display: block; left: 0px; top: 0px; width: 300px; height: 32px; margin: 5px;">
    <div class="bk bk-btn-group">
        <button class="bk bk-btn bk-btn-default" type="button">MyButton</button>
    </div>
</div>
```

*The id and name tags are missing*

HTML output for the multiselect widget:

```html
<select class="bk bk-input" multiple="true" name="multi1" size="4">
    <option class="bk" value="1">1</option>
    <option class="bk" value="2">2</option>
</select>
```
*The name tag is present but the id tag is missing*

**Comment by bryevdv** [comment]
@gh4ag You have made assumptions about what these properties are for that are not the case. `name` is an arbitrary name you can provide to a Bokeh object for the purpose of identifying it in the object graph:

https://docs.bokeh.org/en/latest/docs/reference/model.html?highlight=name#bokeh.model.Model.name

There is no expectation that it will be relayed to the DOM.

Similarly, the `id` is the id of the Bokeh object in the object graph. It is also not related at all to DOM ids, and in fact should never be set ny users at all. Object IDs are completely managed by Bokeh.

**Comment by gh4ag** [comment]
Thank you for your reply, I have learnt something!

I didn't have any expectation about any relay to DOM. However, I was looking for a way to add listener to widget events and I observed that for some widgets, the `name` tag was relayed, for some other it was not. This is still for me unclear why ? If it is not a bug, it is still a very mysterious inconsistent behaviour.
