### ISSUE TITLE
[BUG] FileInput filename not returning the filenames after upgrading to v2.3.2

### ISSUE THREAD

**Issue by Suicoleiro** [bokeh/bokeh#11276]
The FileInput widget doesn't return the filename anymore after upgrading from v2.2.3 to v2.3.2

Minimal example code:
```
from bokeh.models import FileInput, CustomJS
from bokeh.io import show

myFileInput = FileInput(accept='.pdf',multiple=True)

myFileInput.js_on_change("value", CustomJS(code="""
    console.log(this)
    console.log(this.filename)
    console.log(this.value)
    console.log(this.accept)
"""))

show(myFileInput)
```

<b>Expected behavior:</b>
When selecting 6 pdf files, "this.filename" should return an array of 6 filenames in the console.

<b>Observed behavior:</b>

<b>v2.2.3</b>
Correctly returns an array of 6 filenames
![FileInput_v2-2-3](https://user-images.githubusercontent.com/56967998/118355670-7f80a000-b571-11eb-8d59-fbbf30f7128c.JPG)

<b>v2.3.2</b>
Incorrectly returns an empty field
![FileInput_v2-3-2](https://user-images.githubusercontent.com/56967998/118355675-87404480-b571-11eb-9ca1-25515523ad08.JPG)

**Comment by mattpap** [comment]
This is the culprit:
https://github.com/bokeh/bokeh/blob/404648077ba71339598936978db72b545d6f39fa/bokehjs/src/lib/models/widgets/file_input.ts#L51-L58

Those assignments need to be done simultaneously, otherwise callbacks will be called as soon as the first property is updated. This code was the same in 2.2, so it must have been a fluke it worked.

**Comment by Suicoleiro** [comment]
Thanks for the response @mattpap 
For now, it works with v2.3.2 if I change ```myFileInput.js_on_change("value",``` to ```myFileInput.js_on_change("filename",```

**Comment by Suicoleiro** [comment]
> 
> 
> This is the culprit:
> 
> https://github.com/bokeh/bokeh/blob/404648077ba71339598936978db72b545d6f39fa/bokehjs/src/lib/models/widgets/file_input.ts#L51-L58
> 
> Those assignments need to be done simultaneously, otherwise callbacks will be called as soon as the first property is updated. This code was the same in 2.2, so it must have been a fluke it worked.

@mattpap Not sure if I'm reading your response correctly nor am I experienced at all. Are you proposing something like below or is this leading to the same issue?

```js
if (this.model.multiple) {
Object.assign(this.model, {value: values, filename: filenames, mime_type: mime_types})
} else {
Object.assign(this.model, {value: values[0], filename: filenames[0], mime_type: mime_types[0]})
}
```

**Comment by mattpap** [comment]
No, the above would still trigger independent assignments. This is what I meant:
```ts
if (this.model.multiple)
  this.model.setv({value: values, filename: filenames, mime_type: mime_types})
else
  this.model.setv({value: values[0], filename: filenames[0], mime_type: mime_types[0]})
```
However, I was also investigating a new approach to simultaneous assignments, that would leave the code almost unchanged, but that work still requires some thought though.

**Comment by bryevdv** [comment]
@Suicoleiro Would you be interested to submit a PR the immediate fix above?

**Comment by Suicoleiro** [comment]
@bryevdv apologies for the late answer. Yes, this would be perfect to get familar with the process and will help me for future contributions. Still have to go through all bokeh developers documentation but if a few days are not critical, I'm very happy to give it a stab.

**Comment by Suicoleiro** [comment]
@bryevdv performed following steps but need some help for the next steps:
- Set up Bokeh as described in the Developers section forking 2.4 branch
- Adapted the forked bokeh/bokehjs/src/lib/models/widgets/file_input.ts as suggest by @mattpap 
- Built/Installed using python setup.py develop --build-js
- Tested before and after built using a minimal script as follows:
```python
from bokeh.models import FileInput, CustomJS, TextInput
from bokeh.io import curdoc
from bokeh.layouts import column

myFileNames = TextInput(value="", title="Number of file names:")
myFileValues = TextInput(value="", title="Number of file values:")

myFileInput = FileInput(accept='.pdf',multiple=True)

myFileInput.js_on_change("value", CustomJS(args=dict(myFileNames=myFileNames, myFileValues=myFileValues), code="""
    // get number of file names
    myFileNames.value = this.filename.length.toString();
    // get number of file values
    myFileValues.value = this.value.length.toString();
"""))

curdoc().add_root(column(myFileInput, myFileNames, myFileValues))
```

Before (v2.3.3):
![FileInput_result_v2 3 3](https://user-images.githubusercontent.com/56967998/129633278-e3cb60d0-a8a6-490c-bb13-22e37cdbbbc9.JPG)

After (v2.4dev):
![FileInput_result_v2 4dev](https://user-images.githubusercontent.com/56967998/129633325-cb09f5c9-ff69-4405-8ebd-77773d3b7e1d.JPG)

Questions:
- Are there additional tests required (didn't manage to create an automated test using pytest)
- Can you advise on the next steps?

Thanks!

**Comment by bryevdv** [comment]
@Suicoleiro it seems like you have a working changeset with manual testing, which is great!

> didn't manage to create an automated test using pytest

For this kind of change, any real tests will have to be JavaScript tests, since the actual implementation is all in BokehJS. The existing JS unit tests for `FileInput` are here:

https://github.com/bokeh/bokeh/blob/branch-2.4/bokehjs/test/unit/models/widgets/file_input.ts

At a quick glance, it seems like it should not be too bad to copy one of those tests and update it to cover the "multiple" case. I would suggest opening a PR at this point, and then we can iterate on some unit tests in the PR. Thanks!

**Comment by bryevdv** [comment]
also cc @tcmetzger who is in the middle of updating and improving our dev docs, and may want to ask you about your experience going through them for the first time

**Comment by Suicoleiro** [comment]
@bryevdv Thanks, will see if I can add two test cases in the respective bokehjs folder for accepting multiple files. The existing tests will help getting familiar.

@tcmetzger In terms of creating a successful PR, do you happen do have any material that you plan to implement? This would be very helpful.
![grafik](https://user-images.githubusercontent.com/56967998/129791728-7c53a319-a733-4fa5-b436-8c4447557cca.png)

Until this point the documentation has been very nice and I was able to follow even as a newbie. Please let me know if you would like to talk about more detailed feedback and in which form you would want me to comment?

Thanks!

**Comment by tcmetzger** [comment]
@Suicoleiro Thank you for your work on this pull request! And thanks for your feedback on the docs. I'm collecting feedback and ideas for the developer docs update in this issue: https://github.com/bokeh/bokeh/issues/11354 - feel free to add any observations you made while working on this PR! The current updates are in this Pull Request: https://github.com/bokeh/bokeh/pull/11513
