### ISSUE TITLE
[BUG] hover tooltip is cut off when the tooltip is tall and hover near the top of the plot

### ISSUE THREAD

**Issue by orionlee** [bokeh/bokeh#11273]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 2.3.2 (also tested on 2.2.3)
python: 3.7
notebook: 6.3.0
browser: Chrome 90

#### Description of expected behavior and the observed behavior
For hover tooltip, when the tooltip is tall and user hovers around a glyph near the top of the plot, 
- observed behavior: the tooltip is cutoff. (See screenshot below).
- expected behavior: the tooltip should adjust its position so that it stays within visible area.

The issue happens both in jupyter (`output_notebook`) and in standalone file (`output_file`) output.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# based on https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields
    
from bokeh.plotting import ColumnDataSource, figure, reset_output, output_file, output_notebook, show

reset_output()
# output_file("toolbar.html")
output_notebook()

source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=['A', None, 'c', 'd', 'E'],
))

# make the tooltip tall enough to expose the issue
TOOLTIPS = [  
    ("index", "$index"),
    ("(x,y)", "($x, $y)"),
    ("desc", "@desc"),
    ("desc2", "@desc"),
    ("desc3", "@desc"),
    ("desc4", "@desc"),
    ("desc5", "@desc"),
    ("desc6", "@desc"),
]

p = figure(plot_width=400, plot_height=400, tooltips=TOOLTIPS,
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)
```

#### Screenshots or screencasts of the bug in action

---
Normal tooltip:

![image](https://user-images.githubusercontent.com/250644/118202961-e25a2600-b40f-11eb-86c7-3c3a40f0e5ad.png)

---
When hovers near the top of the plot (the first line of the tooltip, index, is cut off completely):

![image](https://user-images.githubusercontent.com/250644/118203018-01f14e80-b410-11eb-95c4-2acba9689010.png)

**Comment by tcmetzger** [comment]
@orionlee Sorry for the late reply! The default basic tooltip is nothing but a very basic default. For anything else, custom HTML tooltips offer some more options: https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#custom-tooltip
However, I don't know of a way to dynamically change the positioning of a tooltip as you describe it. 

@mattpap is this something that could be included in the CSS layout improvements you mention here: https://github.com/bokeh/bokeh/issues/11455#issuecomment-889353050?

**Comment by bryevdv** [comment]
Another idea would be to let the anchor point float on the side is attached on, e.g. in the above case the anchor could be near the top of the tooltip (still attached on the left side) with the tooltip dangling downward, and for one of the bottom points, the opposed (still attached on the left side but near the bottom and dangling upward). The position of the attachment could vary smoothly depending on the mouse position relative to the top or bottom of the frame.

**Comment by orionlee** [comment]
I think the default tooltip should be able to handle cases such as this in general.

The existing tooltip already handles something similar in horizontal direction. E.g., in the above example, when one does a mouseover of a point near the right edge of the plot, the anchor point is put to the left of the point.

![image](https://user-images.githubusercontent.com/250644/128399165-5a8a4cbc-f8de-41d9-b3b2-3e171375178b.png)

Similar logic can be employed to handle cases where the tooltip is near the top of the plot.

**Comment by bryevdv** [comment]
@orionlee just to be clear, the existing tooltip already does exactly what you describe above, for the vertical direction, *if you set the attachment to the top or bottom*.  The question is what to do about vertical positioning when the attachment is on the left or right, and I outlined a proposal for that above.
