### ISSUE TITLE
Document conda init in Getting Set Up

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11282]
May be necessary before `conda activate`

**Comment by afzal442** [comment]
Interested. Could you help me through this?

**Comment by bryevdv** [comment]
The file to edit is here:

https://github.com/bokeh/bokeh/blob/branch-2.4/sphinx/source/docs/dev_guide/setup.rst

The relevant section is the "Conda" section, I think we just need to inform users that the first time they install Anaconda, they may need to run the `conda init` command line program once.

**Comment by cjw296** [comment]
@bryevdv - what does `conda init` do here?

**Comment by bryevdv** [comment]
@cjw296 `conda init` makes sure that `conda` and its subcommands are present on the system PATH for easy use, regardless of OS/shell. This might have happened during Anaconda install, but might not, so we should advise everyone to just run it (once).

**Comment by cjw296** [comment]
Ah, of course, I'm sure U have run that at some point :-)
