### ISSUE TITLE
Cannot bokeh build when using custom tag

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#11292]
I am starting a new bokeh extension [panel-chemistry](https://github.com/MarcSkovMadsen/panel-chemistry).

One of the co-contributors is interested in learning how to build Panel/ Bokeh extensions. For that reason I have tagged my repository `v0.0.1-before-pre-built-bokeh-extensions`.

Now when I run `panel build panel_chemistry` I get the error `ValueError: invalid literal for int() with base 10: 'before'`.

I have tracked down the issue and can see that the `version.py::_update_from_vcs` function does not expect tags like that.

![image](https://user-images.githubusercontent.com/42288570/119213178-910bff80-babd-11eb-8140-f850b91bce8d.png)

I don't know what the solution is. Maybe a regex that tests that the `output` is on the expected form. And if not raises and exception with a better error description including help on what to do.

**Comment by bryevdv** [comment]
`version.py` is actually a vendored component from [versioneer](https://github.com/python-versioneer/python-versioneer) (vendoring this file is intended, and how versioneer functions). We do occasionally update versioneer itself, which means any modifications to `versions.py` would have to be manually ported forward (if that is even possible, if anyone happens to remember to) anytime versioneer is updated. I am *strongly* disinclined to make any changes to `version.py`, and suggest that the best appropriate solution is to use actual [PEP-440](https://www.python.org/dev/peps/pep-0440/) compliant.

cc @bokeh/dev

**Comment by MarcSkovMadsen** [comment]
Thanks @bryevdv . Sorry I have never heard about these things before. I will have to learn and adapt.

**Comment by bryevdv** [comment]
@MarcSkovMadsen actually I guess I spoke too soon, the file you are referencing above is not our vendored versioneer file, which is actually `_version.py`. The error you show is from the `version.py` file in the Param project. Bokeh does not use param  at all. It is a Holoviews/Panel component. It's possible the Holoviz folks could make a change that would enable your use case, but you should open the issue on their tracker: 

https://github.com/holoviz/param
