### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jt4186** [bokeh/bokeh#11296]
Expected behavior: Plots displayed after sample code runs.
Observed behavior: Plots not displayed, no errors.  Browser console shows attempts to reach out to the internet.

Inline mode still seems to reach out to the internet for these files:

https://unpkg.com/tabulator-tables@4.9.3/dist/css/tabulator_simple.min.css
https://unpkg.com/moment@2.27.0/moment.js
https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.js

Server OS: Ubuntu 18.04
bokeh: 2.3.2
python: 3.7.3
ipython: 7.19.0
tornado: 6.1

browsers that have the problem: Chrome, Firefox

```
import holoviews as hv
import numpy as np
hv.extension('bokeh')
from holoviews.plotting.links import RangeToolLink

# Genrate Random Data
def randomDataGenerator(noOfSampleDataSets):
    for i in range(noOfSampleDataSets):
        res = np.random.randn(1000).cumsum()
        yield res



#generate all curves
def getCurves(n):
    for data in randomDataGenerator(n):
        curve = hv.Curve(data)
        yield curve

!bokeh info

source_curves, target_curves  = [], []
for curve in getCurves(10):
    # Without relabel, the curve somehow shares the ranging properties. opts with clone=True doesn't help either.
    src = curve.relabel('').opts(width=800, height=200, yaxis=None, default_tools=[]) 
    tgt = curve.opts(width=800, labelled=['y'], toolbar='disable')
    source_curves.append(src)
    target_curves.append(tgt)     

# link RangeTool for the first curves in the list.
x =RangeToolLink(source_curves[0],target_curves[0])

#Overlay the source and target curves
overlaid_plot_src = hv.Overlay(source_curves).relabel('Source')    
overlaid_plot_tgt = hv.Overlay(target_curves).relabel('Target').opts(height=600)

# layout the plot and render
layout = (overlaid_plot_tgt + overlaid_plot_src).cols(1)
layout.opts(merge_tools=False,shared_axes=False)

```

**Comment by bryevdv** [comment]
@jt4186 holoviews is a separate project, not part of Bokeh, that was created and is maintained by a different group of people. You should file any issues involving holoviews on the  holoviews tracker: https://github.com/holoviz/holoviews/issues

**Comment by bryevdv** [comment]
Also:

> Inline mode still seems to reach out to the internet for these files:

Bokehb does not use or load these files at all. (Again, possibly/probably an HV concern)
