### ISSUE TITLE
axis_ticker in plotting.py interface

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1130]
I want to be able to set the x_axis_ticker in an x_axis_type='datetime' to `yearly`, `montly`, `weekly`, `daily`... in the plotting.py interface.

e.g:
![screen shot 2014-09-03 at 1 25 12 pm](https://cloud.githubusercontent.com/assets/4940549/4140340/f441b61a-33a3-11e4-88d2-0eca2275b4b0.png)

Proposing something like x_axis_ticker = "monthly".

Some FD comments:
>then the problem becomes enumerating and documenting a gazillion named configurations

> probably better to just let people pass in the ticker they want :)

>I can appreciate that at the object level, we want people to pass in objects, but at a higher level there is a lot of value in being able to specify common ticker intervals

cc: @bryevdv, @pzwang

**Comment by birdsarah** [comment]
@chdoig I'm pretty sure the DatetimeTickFormatter didn't exist when you opened this issue. Does it meet your needs?

**Comment by chdoig** [comment]
Yes, but I got many complaints in the scipy tutorial that it's not clear in the docs and we don't have a good example. I'd suggest extending the docs and adding an example before closing the issue, or opening a new one.

**Comment by bryevdv** [comment]
Well there's a good place to put additional examples now, do you happen to have any useful ones handy?

**Comment by bryevdv** [comment]
I think this is done now, with configurable ticker being the solution. There are several examples now as well as user-guide sections. I will close as complete but please re-open if there are still other considerations.

**Comment by bryevdv** [comment]
Actually marking as dupe since I think it was covered by other work (and reporting it as completed work for 0.12 would be misleading)
