### ISSUE TITLE
conda is regularly failing in CI

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#11300]
It fails regularly in different jobs, e.g. with:
```
ConnectionResetError: [Errno 104] Connection reset by peer
```
from https://github.com/bokeh/bokeh/pull/11286/checks?check_run_id=2659598526.

Perhaps we could make it more robust, e.g. by retrying commands that failed due to networking errors.

**Comment by mattpap** [comment]
Another recent one https://github.com/bokeh/bokeh/pull/11297/checks?check_run_id=2659707329.

**Comment by bryevdv** [comment]
Conda install is handled by ``conda-incubator/setup-miniconda@v2`](https://github.com/conda-incubator/setup-miniconda) so the place to make that suggestion is upstream (or there may even already be an option to configure re-tries, that we are just not using)
