### ISSUE TITLE
`test_version` fails if git repository status changes during tests

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#11318]
For example if I `git add` during tests, I get this:
```py
tests/unit/bokeh/util/test_version.py F.........                                                                                      [100%]

================================================================= FAILURES ==================================================================
________________________________________________________ Test___version__.test_basic ________________________________________________________

self = <test_version.Test___version__ object at 0x7f00a3b4d370>

    def test_basic(self) -> None:
        assert isinstance(buv.__version__, str)
>       assert buv.__version__ == get_versions()['version']
E       AssertionError: assert '2.3.0-141-geaf5907d4' == '2.3.0-141-geaf5907d4-dirty'
E         - 2.3.0-141-geaf5907d4-dirty
E         ?                     ------
E         + 2.3.0-141-geaf5907d4

tests/unit/bokeh/util/test_version.py:45: AssertionError
```
This may seem like a minor thing, but it's annoying to have tests technically fail all the time, for such a irrelevant reason. Do we have to test the git-dependent part of version string in `test_version:test_basic()`?

**Comment by bryevdv** [comment]
> Do we have to test the git-dependent part of version string in test_version:test_basic()?

I'm fine if you want to remove it, but a `startswith` check seems like a reasonable alternative change that would maintain that local/git versioning has not been unintentionally changed.

**Comment by mattpap** [comment]
Well, this is not just about `-dirty` suffic. For example, doing `git commit --amend` during testing results in this:
```py
self = <test_version.Test___version__ object at 0x7f5493f38fa0>

    def test_basic(self) -> None:
        assert isinstance(buv.__version__, str)
>       assert buv.__version__ == get_versions()['version']
E       AssertionError: assert '2.3.0-145-g3c8177cca' == '2.3.0-145-ge141ac9ba'
E         - 2.3.0-145-ge141ac9ba
E         + 2.3.0-145-g3c8177cca
```
Perhaps it would be sufficient to run this test as the first one, before there is any chance for making modifications to the repository. Currently it runs last.

**Comment by bryevdv** [comment]
I actually think the existing "quick" fix is sufficient (there are not going to be `git commit --amend` happening while running tests). It's possible some new `.gitignore` would resolve the issue by preventing the repo status becoming dirty for whatever file crumbs are getting dropped during tests in CI, but just ignoring `-dirty` is reasonable defensive programming.
