### ISSUE TITLE
[FEATURE] Directed graphs

### ISSUE THREAD

**Issue by dr3y** [bokeh/bokeh#11311]
I have been working on making directed graphs in bokeh. Using `networkx` it is easy to create a `DiGraph` object and have directions in my arrows. But using `from_networkx()` there is no way to automatically draw arrows at the end of the graph edges.

My current work-around is to edit the path of `graph.edges` to make it look like an arrow. This has the bad consequence that arrows do not stay arrow-shaped if you resize the graph or zoom in.

![arrow example](https://i.imgur.com/J8doQsj.png)

Proposed solution:
have `from_networkx()` understand about `DiGraph` objects and allow different glyphs to appear at the ends of lines (maybe you want flat head arrows or something instead of normal arrows)

**Comment by IuryPiva** [comment]
Hey @dr3y thanks for submitting this feature request, sorry this took so long to get a response.

Have you looked at our [ArrowHead](https://docs.bokeh.org/en/latest/docs/reference/models/arrow_heads.html?highlight=arrowhead#bokeh.models.arrow_heads.ArrowHead) model? how would your proposal differ from it?
