### ISSUE TITLE
[FEATURE] Ability to control spacing between legend labels

### ISSUE THREAD

**Issue by tom-andersson** [bokeh/bokeh#11326]
My issue is that I'm plotting many time series in one plot using [hvPlot](https://github.com/holoviz/hvplot) (which uses bokeh), and there are many legend labels (49, to be exact). It seems that multi-column legends are yet to be implemented in bokeh (see #3880 and holoviz/holoviews#4529). So a bokeh legend can only be a single column (or row, which I'm not interested in). Attached image below shows how this means the legend extends outside of the figure, cutting off many elements.

Currently, my only option to show all legend elements is to make the plot super long (i.e. a large `height` input to `opts`) or to reduce the fontsize of the legend and make it more compact. The fontsize of legend labels can be controlled using `plot_obj.opts(fontsize={'legend': 5})`, but this doesn't change the actual spacing between legend labels (i.e., the legend height stays the same).

Given the inability to have multi-column legends for plots with many elements, could we make bokeh legend label spacing scale with the fontsize, or a similar solution to that?

![eg](https://user-images.githubusercontent.com/26459412/121331791-1e997d00-c90f-11eb-8df4-0edc88806cef.png)

**Comment by bryevdv** [comment]
Isn't this [`Legend.label_height`](http://docs.bokeh.org/en/latest/docs/reference/models/annotations.html?highlight=legend#bokeh.models.annotations.Legend.label_height) ?

**Comment by mattpap** [comment]
It's `Legend.spacing` (default 3px).

**Comment by bryevdv** [comment]
Probably both, `label_height` to let the label box shrink in case you have configured a small font size, and `spacing` to also reduce the space between label boxes. 

@tom-andersson I am not sure if these options are exposed via `hvplot` or not. They could be, but regardless you an configure them yourself directly on  the Bokeh objects that `hvplot` generates. 

I am inclined to close this with `noaction` unless there are further comments or concerns? (i.e. a complete, pure-Bokeh [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that showed these options failing to function as expected would make this a bug, but AFAIK they do function as expected).

**Comment by philippjfr** [comment]
Yeah let's close this and reopen an issue on hvPlot. There's a proposal to expose all Bokeh options via a fairly consistent API that will solve this.

**Comment by jbednar** [comment]
There isn't an option to have the spacing scale with the fontsize, though, right?  That's why I'm thinking of this as a Bokeh rather than hvPlot request.

**Comment by mattpap** [comment]
> There isn't an option to have the spacing scale with the fontsize, though, right?

No, usually features like this one are in absolute units (pixels). There's a PR open (https://github.com/bokeh/bokeh/pull/10259) adding support for scalable text, which then could be extended to support this (assuming we want to have consistent behavior across bokeh, instead of an one-off).

**Comment by jbednar** [comment]
Ok, then I'd agree to close this issue, deal with it for HoloViews/hvPlot using the existing options for now, and await having a nice scalable text/baseline solution!

**Comment by bryevdv** [comment]
Also just to mention another option: There's nothing to stop adding two separate `Legend` objects to one plot. That's especially something a higher level tool could do and make simpler from a higher level.

**Comment by tom-andersson** [comment]
Thanks very much everyone. I've managed to get the spacing down with the following:

```
    b = hv.render(plot)  # My amazing interactive hvPlot figure

    b.legend.label_text_font_size = '5pt'
    b.legend.label_height = 5
    b.legend.glyph_height = 5
    b.legend.spacing = 5
    
    from bokeh.plotting import figure, output_file, save
    output_file('figures/antarctic_station_temp_data_yearly_bokeh.html', mode='inline')
    save(b)
```

These values haven't been tuned at all, and I haven't checked that each attribute update is necessary, but it produced the results I wanted, allowing a greater density of legend elements:

![eg](https://user-images.githubusercontent.com/26459412/121516480-28da7a80-c9e6-11eb-9e22-86bccbfac099.png)

I'm guessing there's a way to do this while staying within the HoloViews API by using [HoloViews plot hooks](http://holoviews.org/user_guide/Customizing_Plots.html#Plot-hooks). Haven't looked into that yet though.

**Comment by tom-andersson** [comment]
@bryevdv Thanks for the tip about adding multiple `Legend` objects to obtain a multi-column legend. [I've found this SO post](https://stackoverflow.com/questions/41573881/create-a-two-line-legend-in-a-bokeh-plot) which does what I need, but in my case all the lines are already plotted on the figure using `hvPlot`. Is there a `bokeh` `Figure` attribute that returns a list of lines and their handles, so that I can manually loop through them to create multiple legends from the existing lines?

Now this may be pushing my luck on off-topic-ness (feel free to ignore or redirect me), but I'd like to also have _all lines automatically hidden_ (not muted), and click on them to reveal them. The reason is that I now have even more time-series (~250), each with potentially 10,000s of points. It would be convenient to have a single plot for all of them, but have them all hidden by default to reduce memory demand. I could then use my nice (manual) multi-column legend to choose which ones to inspect. @jbednar, I know of the `hvplot` `legend_muted` option, but what about `legend_hidden`, or similar? Or is there a `bokeh` way to do this, @bryevdv? 

I'm loving being able to email interactive HTML plots to my colleagues, by the way. Thanks again for the `bokeh` -> `hvplot` ecosystem.

**Comment by bryevdv** [comment]
>  Is there a bokeh Figure attribute that returns a list of lines and their handles, so that I can manually loop through them to create multiple legends from the existing lines?

There are various ways do this, but these questions are veering into support question territory to I'll ask that these questions move to the Discourse: https://discourse.bokeh.org

> I'm loving being able to email interactive HTML plots to my colleagues, by the way. Thanks again for the bokeh -> hvplot ecosystem.

Thanks for the kinds words

**Comment by tom-andersson** [comment]
Thank you for pointing me to the Discourse page @bryevdv, I've created threads on these two questions [here](https://discourse.bokeh.org/t/manual-multi-column-legends/7952) and [here](https://discourse.bokeh.org/t/auto-hide-all-legend-entries/7953).
