### ISSUE TITLE
[BUG] Incorrect legend entries and colors when dynamically updating groupby key

### ISSUE THREAD

**Issue by tomas16** [bokeh/bokeh#11331]
I've created a small example to illustrate the issue, see below for the code. The data used here is:
```
   x    y ab cd  num
0  0  1.0  a  c    0
1  1  1.0  a  d    1
2  2  1.0  a  c    2
3  3  1.0  a  d    3
4  4  1.0  a  c    4
5  5  1.0  b  d    0
6  6  1.0  b  c    1
7  7  1.0  b  d    2
8  8  1.0  b  c    3
9  9  1.0  b  d    4
```

See below video for an illustration of the 2 issues.
1. When switching the groupby key from `num` to `ab`, the fill colors for the legend entries should be blue and red (same as the first 2 colors when the key is `num`).
2. When switching back from `ab` to `num`, the legend contains entries from 2 different columns of the underlying dataframe.

https://user-images.githubusercontent.com/8531909/121441412-992dc100-c93e-11eb-961c-433ad75b406c.mov

If we set the default groupby key to `ab`, we get similar behavior. Note that now some of the legend entries have the same color after switching to `num`. When we switch back to `ab`, the legend entries are still the values from the `num` column.

https://user-images.githubusercontent.com/8531909/121441182-2886a480-c93e-11eb-9e1d-b944494b191c.mov

When we switch between groupby keys with the same number of unique values, we again get the issue with the colors, and when switching back the legend entries stay stuck at `c` and `d`.

https://user-images.githubusercontent.com/8531909/121442191-fb3af600-c93f-11eb-9bf8-3983f33f972e.mov

**Summary:** it appears that when we change the groupby column the second time, it leaves the values in place, and if the new groupby column has more unique values it appends them to the legend.

The code for this example:

```python
import numpy as np
import pandas as pd
import panel as pn
import param as pm
import holoviews as hv
import time
hv.extension('bokeh')


class Example(pm.Parameterized):
    groupby = pm.Selector(label="Group by", objects=['ab', 'cd', 'num'])#, default='num')
    integer_param = pm.Integer()

    def __init__(self):
        super().__init__()
        self.k2 = 5
        x = np.arange(self.k2 * 2)
        y = np.ones(self.k2 * 2)
        ab = np.array(['a'] * self.k2 + ['b'] * self.k2)
        cd = np.array(['c', 'd'] * self.k2)
        num = np.array(list(range(self.k2)) * 2)
        self.data = pd.DataFrame(dict(x=x, y=y, ab=ab, cd=cd, num=num))

    @pm.depends("groupby", "integer_param")
    def points(self):
        self.data['y'] = np.ones(self.k2 * 2) * self.integer_param
        pts = hv.Points(self.data, kdims=['x', 'y'], vdims=['ab', 'cd', 'num'])
        pts_grouped = pts.groupby(self.groupby)
        pts_overlayed = pts_grouped.overlay()
        m = hv.render(pts_overlayed)
        print(f"""points() - time = {time.time()}
    m = {m}
    m.legend = {m.legend}""")
        for idx in range(len(m.legend.items)):
            print(
f"""    m.legend.items[{idx}]: {m.legend.items[idx]}
        m.legend.items[{idx}].index = {m.legend.items[idx].index}
        m.legend.items[{idx}].label = {m.legend.items[idx].label}
        m.legend.items[{idx}].renderers = {m.legend.items[idx].renderers}
        m.legend.items[{idx}].renderers[0].data_source.data = {m.legend.items[idx].renderers[0].data_source.data}
        m.legend.items[{idx}].renderers[0].glyph = {m.legend.items[idx].renderers[0].glyph}
                fill_color = {m.legend.items[idx].renderers[0].glyph.fill_color}""")
        print()
        return pts_overlayed

    def viewable(self, **kwargs):
        return hv.DynamicMap(self.points)


if __name__ == '__main__':
    example = Example()

    print(example.data)

    panel = pn.Row(example.param, example.viewable())
    panel.show(title="example", port=8890)
```

As you can see, this example is created using holoviews with bokeh as rendering backend instead of using the bokeh API directly. I initially developed my application using bokeh, but as it grew and I discovered holoviews, I decided to switch. The reasons I believe the issue is with bokeh and not with holoviews are:
1. I encountered the same issue when I was using bokeh directly. Unfortunately I don't have the code for that anymore. I came up with a workaround in which I manually create the legend, see below code. The only limitation was that it's not possible to mute individual legend entries.
2. In above example, the update is printing out a lot of information about the underlying bokeh models. What's printed out is actually what I expect and doesn't match what's displayed in the browser.

I've used the javascript console in Safari to check what data is being received by the browser and it matches what gets displayed, so I can rule out issues in BokehJS and narrow the problem down to bokeh's python code.

Workaround for original bokeh-only version:

```python
    def _update_groupby(self, fig_scatter, groupby_col):
        factors = list(sorted(set(self._source.data[groupby_col])))
        colormap = factor_cmap(field_name=groupby_col, palette=cc.palette.glasbey_hv,
                               factors=factors)
        renderer = fig_scatter.renderers[0]
        renderer.glyph.fill_color = colormap
        renderer.glyph.line_color = colormap
        renderer.selection_glyph = renderer.glyph
        renderer.nonselection_glyph.fill_color = colormap
        renderer.nonselection_glyph.line_color = colormap

        # There are 3 ways to create this legend:
        # 1. Use legend_group (python side) or legend_field (javascript side) in the original
        #    call to circle(). However, these fields aren't attributes of the created objects,
        #    so we'd still need a separate mechanism to update the legend. It turns out that the
        #    legend that gets created this way is exactly what we do manually below.
        # 2. Add a single LegendItem with label=field(groupby_col). We can update the groupby_col
        #    whenever the legend needs to get updated. The drawback with this method is that we
        #    don't have control over the ordering of the items in the legend.
        # 3. Below mechanism, when used without index, creates a legend wherein all items have
        #    the same color. The trick is adding the index. We have full control over ordering
        #    this way.
        fig_scatter.legend.items = [
            LegendItem(label=factor,
                       renderers=[renderer],
                       index=find_first(self._source.data[groupby_col], factor))
            for factor in factors]
```

Using
* python 3.7
* bokeh 2.3.2
* on macOS 11.3.1

Output of `conda list` attached.
[conda_list.txt](https://github.com/bokeh/bokeh/files/6627482/conda_list.txt)

**Comment by bryevdv** [comment]
@tomas16 we absolutely will need a complete *pure-Bokeh* [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) in order to investigate anything here.

I will reiterate what is in the docs and what you seem have indicated above: `legend_group` is not dynamic. It only computes legend items once, up front. There is no expectation that it would re-compute. The primary alternatives are to use `legend_field` or to mange the legend items manually. Additionally, you replace the existing plot with an entirely new plot that specifies a different `legend_group`. 

As it is, I'm not sure if this issue should be:

* a support question
* a feature request
* a bug report
* closed `working as intended`
* bounced back upstream

We really must have a pure-Bokeh test script to be able to properly evaluate 

* your expectations, vs
* what the code actual does, comparing to
* what is officially supported

cc @philippjfr @jbednar

**Comment by tomas16** [comment]
@bryevdv thanks for the feedback.

I took another stab at a pure bokeh example, but considering I solved the issue when I was using bokeh without holoviews, I can't figure out what I was doing when I saw the same behavior (I've only started using bokeh a couple of weeks ago, so beginner's mistakes...). For completeness sake, I added a full working example below, in which I manually create legend items. I'm not sure how to support muting individual items, any suggestions are welcome.

Is my understanding correct that both `legend_group` and `legend_field` don't allow to change the groupby column, but are only useful for initial legend creation?

> Additionally, you replace the existing plot with an entirely new plot that specifies a different legend_group.

Do you mean this is what holoviews is doing in the background (and perhaps shouldn't?), or do you mean this is what you'd recommend for this case?

Would you agree this is possibly a bug in holoviews, perhaps in the way they (re)create the legend? The reason I thought the issue was with bokeh is that the bokeh models returned by `hv.render` are in fact correct and as expected. For instance, when selecting `num` I see 5 legend items, each with a different `fill_color`. However the javascript console in Safari shows different colors in the json, with some entries having the same color, as shown in the screen captures I posted. Basically the bokeh models returned by `hv.render` look fine, and the json in the javascript console matches what's getting displayed in the browser, but the two don't match.

```python
import numpy as np
import pandas as pd
from bokeh.models import ColumnDataSource, Legend, LegendItem, Select
from bokeh.transform import factor_cmap
from bokeh.palettes import RdBu5
from bokeh.plotting import figure
from bokeh.layouts import row
from bokeh.server.server import Server


def create_sample_data():
    k2 = 5
    x = np.arange(k2 * 2)
    y = np.ones(k2 * 2)
    ab = np.array(['a'] * k2 + ['b'] * k2)
    cd = np.array(['c', 'd'] * k2)
    num = np.array(list(range(k2)) * 2)
    return pd.DataFrame(dict(x=x, y=y, ab=ab, cd=cd, num=num))


def find_first(array, query_value):
    """Find the index of the first occurrence of a value in a numpy array"""
    try:
        return next((idx for idx, val in np.ndenumerate(array) if val == query_value))[0]
    except StopIteration:
        raise ValueError("Value not found.")


class Example:
    def __init__(self, data):
        self.groupby_cols = [c for c in data.columns if c not in {'x', 'y'}]
        self.source = ColumnDataSource(data)
        # Factors must be str
        for col in self.groupby_cols:
            self.source.data[col] = self.source.data[col].astype(str)
        self.layout = self.create_layout()

    def _update_groupby(self, fig_scatter, groupby_col):
        factors = list(sorted(set(self.source.data[groupby_col])))
        colormap = factor_cmap(field_name=groupby_col, factors=factors, palette=RdBu5)
        renderer = fig_scatter.renderers[0]
        renderer.glyph.fill_color = colormap
        renderer.glyph.line_color = colormap
        renderer.selection_glyph = renderer.glyph
        renderer.nonselection_glyph.fill_color = colormap
        renderer.nonselection_glyph.line_color = colormap

        # There are 3 ways to create this legend:
        # 1. Use legend_group (python side) or legend_field (javascript side) in the original
        #    call to circle(). However, these fields aren't attributes of the created objects,
        #    so we'd still need a separate mechanism to update the legend. It turns out that the
        #    legend that gets created this way is exactly what we do manually below.
        # 2. Add a single LegendItem with label=field(groupby_col). We can update the groupby_col
        #    whenever the legend needs to get updated. The drawback with this method is that we
        #    don't have control over the ordering of the items in the legend.
        # 3. Below mechanism, when used without index, creates a legend wherein all items have
        #    the same color. The trick is adding the index. We have full control over ordering
        #    this way.
        fig_scatter.legend.items = [
            LegendItem(label=factor,
                       renderers=[renderer],
                       index=find_first(self.source.data[groupby_col], factor))
            for factor in factors]

    def _create_groupby_select(self, fig):
        select = Select(title="Group by", options=self.groupby_cols)
        select.on_change("value", lambda attr, old, new: self._update_groupby(fig, new))
        return select

    def _create_scatterplot(self):
        fig = figure(height=600)
        fig.circle(x='x', y='y', source=self.source, size=6)
        fig.add_layout(Legend(), 'right')
        return fig

    def create_layout(self):
        fig = self._create_scatterplot()
        sel = self._create_groupby_select(fig)
        self._update_groupby(fig, self.groupby_cols[0])
        return row([sel, fig])

    def bkapp(self, doc):
        doc.add_root(self.create_layout())


if __name__ == "__main__":
    data = create_sample_data()
    app = Example(data)
    server = Server({'/': app.bkapp}, num_procs=1)
    server.start()
    print('Opening Bokeh application on http://localhost:5006/')
    server.io_loop.add_callback(server.show, "/")
    server.io_loop.start()
```

**Comment by tomas16** [comment]
I tried using the [hook mechanism](https://holoviews.org/user_guide/Plots_and_Renderers.html#saving-and-rendering) in holoviews and the bokeh figure there is wrong and matches what gets displayed in the browser. This confirms the issue is with holoviews and we can close the issue here.

I'm trying to figure out how I can use the hook to override the bokeh figure. Since the `hv.render()` call in my `points()` method returns a correct bokeh figure, I'm trying to save it and use it to replace what I get in the hook. Will probably take some more trial and error to get right.
