### ISSUE TITLE
Add rounded corners for rect/quad glyphs

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#11348]
It would be nice to have a glyph that was like rect/quad, but that supported rounded corners.  This would make using Bokeh for diagramatic workflows slightly smoother/slicker.

**Comment by mattpap** [comment]
I've been wanting to implement this for a long time, so tentatively adding to 2.4.

**Comment by mrocklin** [comment]
I'm happy to provide an excuse :)

**Comment by Pierretherenard** [comment]
Does that mean 'legend' and 'label' will be able to have round corner as well?
