### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jjvrmorales367** [bokeh/bokeh#11346]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

#### Screenshots or screencasts of the bug in action

*Note: Everyone interacting in the Bokeh project's codebases, issue trackers, and discussion forums is expected to follow the [Code of Conduct](https://github.com/bokeh/bokeh/blob/master/CODE_OF_CONDUCT.md).*

**Comment by bryevdv** [comment]
@jjvrmorales367 There is no information above. Was this issue creation a mistake or accident?
