### ISSUE TITLE
[BUG] TypeError: t.select is not a function, when using RangeSlider

### ISSUE THREAD

**Issue by Knaifhogg** [bokeh/bokeh#11345]
## Versions:
Bokeh 2.3.2
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)] on win32
Mozilla Firefox 89.0 (64-bit)
Microsoft Edge Version 88.0.705.68 (Official build) (64-bit)

## Expected behaviour:
Code taken from https://stackoverflow.com/a/58812296
Range slider affects filter of source for plot. You can select how much to filter using the range slider.

## Observed behaviour:
HTML file created and opened. Range slider does not affect plot. Errors in browser console. Does not occur at all ranges.

## Code:
```
from bokeh.layouts import column
from bokeh.plotting import figure, show
from bokeh.models import CustomJS, ColumnDataSource, RangeSlider, CDSView, IndexFilter

source = ColumnDataSource(data=dict(
    x=[1,2,3,4],
    y=[1,1,1,1],
    t0=[1,1,0,0],
    t1=[0,1,0,0],
    t2=[0,1,1,0],
    t3=[0,0,1,1],
    t4=[0,0,0,1],
    t5=[0,0,0,0],
))

p = figure(plot_height=500, x_range=(0,5), y_range=(0,2))

view = CDSView(source=source, filters=[IndexFilter([0, 1])])
p.circle('x', 'y', size=10, color="navy", alpha=0.8,
         source=source, view=view)

callback = CustomJS(args=dict(source=source, view=view), code="""
    const start = cb_obj.value[0]
    const end = cb_obj.value[1]
    const indices = []
    for (var i=0; i < source.get_length(); i++) {
        for (var j=start; j<=end; j++) {
            if (source.data["t" + j][i]==1) {
                indices.push(i)
                break
            }
        }
    }
    view.indices = indices
""")

ti_slider = RangeSlider(start=0, end=5, value=(0,1), step=1, title="Time Period")
ti_slider.js_on_change('value', callback)

show(column(ti_slider, p))
```

## Error output:
![image](https://user-images.githubusercontent.com/68106656/122066602-2d8e9c80-cdf3-11eb-80e6-601122e7e031.png)
![image](https://user-images.githubusercontent.com/68106656/122067110-96761480-cdf3-11eb-92aa-10200456c723.png)

**Comment by mattpap** [comment]
> `view.indices = indices`

`CDSView.indices` of type `BitSet`, not an array, so you would have to import it and then use `BitSet.from_indices(indices)`. However, this property is internal to `CDSView`. Most likey, you have set selection or inspection indices on a data source, which will then update `CDSView.indices` accordingly, applying filters, etc.

**Comment by bryevdv** [comment]
Is this a support discussion to move to Discourse? What is needed still to resolve on the tracker?

**Comment by bryevdv** [comment]
@Knaifhogg please open a support topic on https://discourse.bokeh.org

**Comment by Knaifhogg** [comment]
Thank you for the nudge, it helped me in finding a solution. Posting it here for others.

Created filter variable:
`ifilter = IndexFilter(indices=[])`
`view = CDSView(source=source, filters=[ifilter])`

Passed it to callback:
`callback = CustomJS(args=dict(source=source, ifilter=ifilter)`

Update filter indices instead, and emit changes:
`ifilter.indices = indices`
`source.change.emit()`
