### ISSUE TITLE
Simplify DatatimeTickFormatter format properties

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11347]
Currently `DateTimetickFormatter` accepts a *list* of formats for each time scale. This is mostly just taken from the Chaco implentation that was used as a reference in very early days. But it's unclear what causes a given format to be chosen out of that list. The docs state "By default, only the first format string passed for each time scale will be used". Looking at the code, it seem like the formatter might try to sort the formats based on their length when applied to "now", and use the first of *that* list. Either way it is complicated and seems unnecessary and useless as is. 

I propose for  3.0 to change the property types to be single `String` instead of `List(String)`, but add an `accepts` to keep existing code that sets lists of 1-length strings working (with a warning).  This would still be breaking if anyone is doing e.g. `formatter.minsec[0]` but  I suspect that is very uncommon at best. 

cc @bokeh/dev

**Comment by jbednar** [comment]
Sounds like it needs better docs, but choosing the shortest representation does seem like a good heuristic, to me, if you aren't going to support some other choosing mechanism. One way or another any fixed format for datetimes is not going to be useful across very different timescales, which arise naturally due to zooming in and out.

**Comment by bryevdv** [comment]
@jbednar I want to make sure you are understanding: there will still be a different format *per-scale*. BUt there will not be a *list of formats* per scale. 

Right now we have these defaults:
```
microseconds = ['%fus']
milliseconds = ['%3Nms', '%S.%3Ns']
seconds = ['%Ss']
minsec = [':%M:%S']
minutes = [':%M', '%Mm']
hourmin = ['%H:%M']
hours = ['%Hh', '%H:%M']
days = ['%m/%d', '%a%d']
months = ['%m/%Y', '%b %Y']
years = ['%Y']
```

AFAICT the second formats there are either unused or are literally unpredictably, capriciously sorted according to the time of day the plot is *viewed* (terrible, if so).

I am proposing this instead, a single format *per-scale*:
```
microseconds = '%fus'
milliseconds = '%3Nms'
seconds = '%Ss'
minsec = ':%M:%S'
minutes = ':%M'
hourmin = '%H:%M'
hours = '%Hh'
days = '%m/%d'
months = '%m/%Y'
years = '%Y'
```

Does this change your understanding or comment?

**Comment by jbednar** [comment]
Ok, sounds good. "For each time scale" in your original comment then is not talking about "for each time axis" (one format per axis), but for each separate time duration range that might apply to that axis (many possible formats per axis). Carry on, then! :-)

**Comment by bryevdv** [comment]
Disambiguating terminology would probably help here too. The properties like `minsec` etc. are probably more properly called something like "time scale interval"
