### ISSUE TITLE
PNG export for LaTeX

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11359]
After adding LaTeX capabilities to Bokeh, we need to make sure that LaTeX elements export correctly to PNG. This is part of the LaTeX work for the CZI R3 grant (#11191).

**Comment by mattpap** [comment]
Is there actually anything to do here? Tex math content in PR #11128 is rendered to canvas, so it will be part both of output from PNG/SVG export and save tool.

**Comment by bryevdv** [comment]
Given that math text rendering requires loading external resources, I can at least imagine race conditions with export being plausible. This issue can serve as a reminder to check and test that specifically, and it is also useful to have as an issue that aligns with the proposal goals for reporting purposes.
