### ISSUE TITLE
Docker container for dev environment

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11352]
Setting up and maintaining a local development environment can be time-consuming, especially for new contributors. To make it easier for new contributors to work on Bokeh, we would like to create a pre-configured Docker container with all the necessary packages, environment variables, and configuration. This is part of the maintenance and sustainability work for the CZI R3 grant (#11351).

**Comment by bryevdv** [comment]
I have come around on this. I use docker container exclusively for dev on node-rapids now. Admittedly, the setup requirements are even more onerous there than here, but at this point, we should leverage the pervasiveness of docker to streamline our default dev setup even more (we will always want "bare install" instructions somewhere but a docker workflow that works on all platforms with essentially just a `docker pull` and `docker run` should become thew new default)
