### ISSUE TITLE
Improve good first issue (GFI) experience

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11353]
We already have a good selection of issues labeled Good First Issue (GFI) for potential new contributors. However, it would make it easier to get started with Bokeh if we had some information and links to resources that we could add to most or all GFIs. As discussed with @bryevdv, we will put together these resources and add them to GFI discussions where appropriate. This is part of the maintenance and sustainability work for the CZI R3 grant (#11351).

**Comment by bryevdv** [comment]
We should also work to refine the definition of GFI. In the past my primary criteria was that something be more or less self-contained, not that it be trivial or small necessarily. But I think we should move to making "trivia or small" be a primary consideration as well. Those kinds if issues are critical for any sort of success at sprints (especially online ones).

**Comment by hyles-lineata** [comment]
What do y'all think about adding a page to the Developers section to walk through the basic branching, committing, etc process on GH? Developers who might not work full-time in software could find the procedures obscure or confusing, and even those of us who do work in software but use other version management platforms (BitBucket, GitLab, etc-- this is me!) can get frustrated with new terminology and layouts, and the inconvenience is a deterrent. 

And developers for whom this is old hat can just skip over that section. :)

**Comment by bryevdv** [comment]
I've thought about this in the past, I do wonder if there are existing resources we can link to or crib from to avoid having to create this content ourselves from scratch. Tho I am sure there would be tangible benefits e.g. to screenshots that directly reference our repos, so maybe it is worth it.

**Comment by tcmetzger** [comment]
I have opened a separate issue for the developer docs update: https://github.com/bokeh/bokeh/issues/11354 This includes two (more or less) new sections, "Creating issues" and "Creating a successful Pull Request". I'd say we should include some basic information about our processes and procedures there and then link to some more in-depth resources (both BEPs and other resources on github.com or elsewhere) to keep the maintenance of these sections manageable.

**Comment by tcmetzger** [comment]
Closing this with https://github.com/bokeh/bokeh/pull/11513. There is now also a new GFI template in the wiki to help in this regard: https://github.com/bokeh/bokeh/wiki/Good-first-issue-template
