### ISSUE TITLE
Update developer docs

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11354]
The developer docs have grown organically with Bokeh over many years. Some parts of them are incomplete or now outdated. To make the developer tools a more useful resource for existing and new contributors, we will update, edit, and restructure the existing information. This is part of the maintenance and sustainability work for the CZI R3 grant (#11351).

**Comment by tcmetzger** [comment]
This is the structure I'd like to propose for the updated developer docs section (all titles are just working titles at this point):

- **Devguide landing page**: Based on `dev_guide.rst`. Lists all relevant resources for contributors (Developer docs, Slack, Discourse, roadmap, Github wiki/BEPs, CONTRIBUTING.md, CODE_OF_CONDUCT.md, etc.). Provides a quick “where to start” orientation guide. Offers different entry points for different audiences, grouped by different areas of contributions, such as  "Docs/Examples", "Python", "BokehJS", and "Server" (similar to the boxes on the [general documentation landing page](https://docs.bokeh.org)).
- **Setting up a development environment**: Combines information from `env_vars.rst` and `setup.rst`.
- **Running local tests**: Based on information from `testing.rst`, but focused on running tests. Creating/updating tests will have separate chapters for Python and TS, respectively.
- **Creating issues**: Combines information from Github/Wiki/Issue templates, information about issue management and labels.
- **Creating a successful Pull Request**: Combines information from Github/Wiki/PR templates, walks through an example PR.
- **Contributing to the docs**: Based on `documentation.rst`.
- **Working with Bokeh models**: Based on `models.rst`.
- **Understanding Bokeh server**: Based on `server.rst`.
- **Testing Python code**: Based on `testing.rst` with a focus on adding/updating Python-based tests.
- **Contributing to BokehJS**: based on `bokehjs.rst` with a focus on adding and updating TS code.
- **Testing TS code**: Based on `testing.rst` and `bokehjs.rst` with a focus on adding/updating TS-based tests.
- **Contributing to language bindings**: Based on `bindings.rst`.

**Comment by tcmetzger** [comment]
Another thought: I'd like to change the dev guide's headline from "Developers" to "Contribute", i.e. in the menu on docs.bokeh.org, the link to the dev guide would be "Contribute". 
![image](https://user-images.githubusercontent.com/39711796/125493202-ab740e9e-d384-44df-b2c2-6d1ce04d6ed4.png)

This is why I think we should do that:

- First of all, the dev guide contains information for people who want to contribute to Bokeh. Because our main goal for this document is to make it easier for people to find the information they need to contribute to Bokeh, I think we should make that the focus of the headline.
- Second: "Developers" is slightly misleading, in that Bokeh itself is mostly used by developers to build user-facing applications. So the target audience of the User Guide and Reference Guide are also developers, in a sense. What sets the dev guide apart from the other parts of the docs is that it contains information specifically for people who want to contribute.
- Third: the dev guide does not only contain information for software developers who want to contribute to Bokeh - but it also contains information for people like technical writers who want to contribute to the docs, for example.

**Comment by bryevdv** [comment]
FWIW I think "Developer's Guide" is pretty universally understood in OSS to be "people developing on the project itself" (as opposed to users) and I also think folks working on docs are included in that. But my main concern with "Contribute" is that some people may see is and assume it only refers to "financially contribute". But I'm ok to change it especially if we do expand sections in include other kinds of non-docs, non-code contributions. (And maybe there is an even better word/phrase for the menu, I haven't thought about it)

**Comment by tcmetzger** [comment]
This is definitely all still a work in progress, so we can always update the title or go back to Developer's Guide. I'll open a WIP PR soon, so we can look at things in context!
