### ISSUE TITLE
Add LaTeX rendering to elements

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11355]
To make Bokeh more useful in academic and research-related contexts, we need to add capabilities to use mathematical notation (LaTeX) in several Bokeh elements. The goal is to have LaTeX rendering capabilities for titles, axis labels, tick labels, labels, and div widgets. This is part of the LaTeX work for the CZI R3 grant (#11191).

ToDos:

- [x] Titles #11708 
- [x] axis labels #11128 
- [x] tick labels #11420 
- [x] Labels #11708 
- [x] Div widgets #11585 
- [x] Paragraph widgets #11585 
- [x] RangeSlider and Slider widgets #11815

**Comment by tcmetzger** [comment]
Related PRs are #11067 (extension example) and #11128 (LaTeX on axis labels).

**Comment by philippjfr** [comment]
Can I add an item to the list here? Specifically widget labels would be very handy. We've had a request for this for a very long time: https://github.com/holoviz/panel/issues/1324

**Comment by mattpap** [comment]
> Specifically widget labels would be very handy.

It's not on the list, but we discussed this a while back, so this will be added, hopefully next week or so.
