### ISSUE TITLE
Improve tests for SVG backend

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11362]
To ensure sustainable development of Bokeh's SVG exporting features, we need to expand and improve tests of the related code.  This is part of the exports improvements work for the CZI R3 grant (#11361).

**Comment by mattpap** [comment]
This should be not just about export, but testing the SVG backend in general. This way export will be covered implicitly, but tests will be close to the actual logic, and would also cover saving as well (save tool).

**Comment by tcmetzger** [comment]
As discussed, this is how we would like to divide the work into individual pull requests: 

### 1. Unit tests for the engine itself (exposed API)
This refers to unit tests for the SVG backend methods in svg.ts. The tests will be implemented with 6 roughly equally complex PRs.

1. PR on basic paint methods of API: `fillText`, `strokeText`, `arc`, `rect`, `stroke`, `fill`
2. PR on transformation-related methods: `scale`, `rotate`, `translate`, `transform`, `moveTo`
3. PR on state management-related methods: `save`, `restore`, `clip`, `getTransform`, `setTransform`, `resetTransform`
4. PR on path-related methods: `closePath`, `beginPath`, `bezierCurveTo`, `quadraticCurveTo`, `arcTo`, `lineTo `(and thus implicitly `rect`, `fillRect`, `strokeRect`)
5. PR on style-related methods: `createLinearGradient`, `createRadialGradient`, `createPattern`, `addLineDash`
6. PR for drawImage: `drawImage`

A test for a method is completed when it covers every exposed parameter and every if-branch in a method.

### 2. Integration tests 
This refers to integration tests for the SVG-export function of BokehJS. Because this is based on the code tested by the above unit tests, we do not need to have integration tests for each possible method but instead focus on making sure that the export function as a whole is working properly.

Integration tests will be based on 5 existing examples from the `bokeh/examples/` folder. They will first be exported to SVG. Then the exported file will be converted to PNG and compared to a baseline file.

**Comment by tcmetzger** [comment]
@IuryPiva Did I understand correctly that it would be better to put `closePath` and `beginPath` into their own PR, maybe as a seventh PR?

**Comment by IuryPiva** [comment]
> @IuryPiva Did I understand correctly that it would be better to put `closePath` and `beginPath` into their own PR, maybe as a seventh PR?

Sorry for the late response. After looking at the code of both I think the best idea is to have them as their own PR, yes.
