### ISSUE TITLE
[BUG] RadioButtonGroup orientation doesn't have expected effect

### ISSUE THREAD

**Issue by sdc50** [bokeh/bokeh#11374]
versions:

python: 3.9.5
jupyterlab: 3.0.16
bokeh: 2.3.2

When setting the RadioButtonGroup `orientation` attribute to `'vertical'` I would expect the buttons to be stacked on top of each other vertically (something like rotating the horizontal version 90 degrees):

![image](https://user-images.githubusercontent.com/6454472/123116936-f168c680-d406-11eb-97e3-205a56d76640.png)

(but with the text oriented horizontally)

However, it seems that they are just stretched in the vertical direction:

![image](https://user-images.githubusercontent.com/6454472/123116264-5cfe6400-d406-11eb-86ce-113fa6f0ab0c.png)

I'm can't see how this would be useful, so I'm assuming this is a bug. It would be great if `orientation='vertical'` would stack the buttons on top of each other vertically.

**Comment by sdc50** [comment]
![image](https://user-images.githubusercontent.com/6454472/123118584-61c41780-d408-11eb-8e72-54562e0fd36b.png)

I think either (or both!) of these options would be suitable for an `orientation='vertical'` configuration.

**Comment by mattpap** [comment]
Orientation is not implemented on button groups at all, it's just bad design decisions that lead to it inheriting `orientation` property from `Widget` model. Though it shouldn't be too hard to make it work.

**Comment by bryevdv** [comment]
>  inheriting orientation property from Widget model

When did `orientation` get added to `Widget` ??

**Comment by mattpap** [comment]
Awhile back. It's a side effect of JS/TS not having decent support for mixing code in.
