### ISSUE TITLE
[BUG] multi_line with logScale

### ISSUE THREAD

**Issue by captKuk** [bokeh/bokeh#11378]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python 3.7.10 and Python 3.8.5 (miniconda installations)
bokeh 2.3.2
(Both in a bokeh serve environment as well as on a jupyter-environment on Firefox)
OS: OpenSuse 15.2 

#### Description of expected behavior and the observed behavior

I’m trying to plot data with a multi_line glyph and with the vertical axis being logarithmic.

The displayed plot is is autoscaled only on a small window of the available data. One can zoom out manually and see everything, but the default view eclipses some data. When using repeated calls for generating line glyphs, the vertical axis scales as expected. (To see that behaviour set the variable use_multiline to False) Also, when only one line is provided to the multi_line (reduce xs and ys to one element each), the range is selected correctly.

#### Complete, minimal, self-contained example code that reproduces the issue
```py
from bokeh.plotting import figure
from bokeh.io import show
from bokeh.models import ColumnDataSource

fig = figure(y_axis_type="log")
xs = [[0,1],[0,1],[0,1]]
ys = [[2,1],[100,200],[10,20]]

data = dict(xs= xs,
           ys= ys)

data_source = ColumnDataSource(data)

# Change this...
# ************************
use_multiline = True
# ************************
#

if use_multiline:
    fig.multi_line(xs="xs", ys="ys", source=data_source)
else:
    for x, y in zip(xs,ys):
        fig.line(x=x, y=y)

show(fig)
```

#### Screenshots or screencasts of the bug in action
With Multi_line:
![grafik](https://user-images.githubusercontent.com/62313973/123180300-04a48200-d459-11eb-9e9e-a7080d3a20fe.png)
With simple lines:
![grafik](https://user-images.githubusercontent.com/62313973/123180427-3e758880-d459-11eb-8454-ee6a71e91d1b.png)

**Comment by mattpap** [comment]
@captKuk, please include imports in code when submitting bug reports (so that code can be copied and run).

**Comment by captKuk** [comment]
@mattpap, excuse me, I thought I had edited the imports in, but apparently I didn't. Thank you for taking care of that.
