### ISSUE TITLE
[FEATURE] bokeh-plot should parse ReST docstrings in example

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11381]
The code block here:

https://github.com/bokeh/bokeh/blob/a6cf8293dc7b4bdee68f3378173f48431b9cb103/bokeh/sphinxext/bokeh_plot.py#L146-L158

should extract the doctring from the source, (for file source, let's stipulate that "inline" content is assumed not to have a docstring). 

Then, towards the bottom where docutils nodes are constructed, use `self._parse(doctoring, "<bokeh-content>")` to generate a node to add right after the target id node. It would be good to add another directive option flag, e.g. `process-docstring` that defaults to off (to keep compatibility) and that is enabled explicitly in the gallery detail template. I suppose to keep complete compatibility, if this flag is False, we should leave the docstring in the source so that it displays as-is in the code block. 

There may also be some other minor refactoring cleanup that can happen:

* I think the source and js items returned and stored by `_process_script` are no longer necessary to return and keep. 
* The bare tuples could become dataclasses for improved typing

**Comment by hyles-lineata** [comment]
To confirm, the desired end result here is that docstrings appear on each gallery example's page (e.g. iris.html), and not [at this stage] in the full listing on gallery.html? Or both?

**Comment by bryevdv** [comment]
Yes for now let's just concentrate on the gallery detail pages (i.e. the individual page for each gallery item) We can consider something like extracting a title or some other feature from the ReST docstring to use as a summary on the main gallery front page later.
