### ISSUE TITLE
[FEATURE] Enable tornado websocket compression via bokeh serve

### ISSUE THREAD

**Issue by horosin** [bokeh/bokeh#11386]
Issue #10798 implementation allowed enabling websocket compression in BokehTornado class. Could it be surfaced in bokeh serve command?

https://github.com/bokeh/bokeh/issues/10798

**Comment by horosin** [comment]
This was done but is undocumented

https://github.com/bokeh/bokeh/blob/a6cf8293dc7b4bdee68f3378173f48431b9cb103/bokeh/command/subcommands/serve.py#L723

**Comment by bryevdv** [comment]
It is documented in `--help` output as well all the reference guide: 

https://docs.bokeh.org/en/latest/docs/reference/server/tornado.html
