### ISSUE TITLE
Hover tool swaps sides at an off-center position

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#1139]
Easier to show:

![fullscreen_9_4_14__4_29_pm](https://cloud.githubusercontent.com/assets/4944634/4157101/9332de6c-347a-11e4-9269-a0b6bfea81f1.png)

*(the hover tooltip should be displaying on the right side of the cursor at that point)*

**Comment by birdsarah** [comment]
this appears to now be fixed - not sure when it happened. (tested on bokeh 0.9.1)

![image](https://cloud.githubusercontent.com/assets/1796208/8626237/f0a2e616-2743-11e5-9a50-eb40073316bb.png)
