### ISSUE TITLE
address code issues flagged by lgtm

### ISSUE THREAD

**Issue by hyles-lineata** [bokeh/bokeh#11392]
[LGTM lists four code issues,](https://lgtm.com/projects/g/bokeh/bokeh/alerts/?mode=list) all python; one is that flask is being run in debug mode, and the other three are paths that depend upon a user-supplied value.

**Comment by hyles-lineata** [comment]
Notes from review:
- the [flask_server.py](https://lgtm.com/projects/g/bokeh/bokeh/snapshot/3bd1d19b81c05db3b837495dd98982447b785948/files/examples/embed/arguments/flask_server.py?sort=name&dir=ASC&mode=heatmap#x592eb5113a7053ce:1) issue, where the app is run in debug mode, I actually think this is preferable for an _example case_. I propose leaving this one as-is and setting to ignore in LGTM.
- Re ln 64 in [file_server.py](https://lgtm.com/projects/g/bokeh/bokeh/snapshot/3bd1d19b81c05db3b837495dd98982447b785948/files/bokeh/_testing/plugins/file_server.py?sort=name&dir=ASC&mode=heatmap), I'm inclined to ignore this one also, but if I'm honest it's because I don't 100% understand the problem. @bryevdv any objection to ignoring this one? 
- In the [auth.py](https://lgtm.com/projects/g/bokeh/bokeh/snapshot/3bd1d19b81c05db3b837495dd98982447b785948/files/examples/howto/server_auth/auth.py?sort=name&dir=ASC&mode=heatmap#xde8484d295622cd:1) issues, testing shows I can change the tornado RequestHandler's redirect to go to the base uri without affecting behavior, so I've made this change in my branch.

**Comment by bryevdv** [comment]
`file_server.py` is purely testing code, that can definitely be ignored. All the others sound good too.

**Comment by mattpap** [comment]
On a side note, why do we read files with `latin-1` encoding (first on the list)?
```py
with open(os.path.join(HTML_ROOT, path), encoding="latin-1") as f:
```
If anything, this should read them in binary mode.

**Comment by bryevdv** [comment]
> On a side note, why do we read files with latin-1 encoding (first on the list)?

probably cruft left over from py2 days (code was introduced with the encoding from the start, 6 years ago)
