### ISSUE TITLE
Add `ellipse()` method to `SVGRenderingContext2D`

### ISSUE THREAD

**Issue by IuryPiva** [bokeh/bokeh#11404]
Relates to #11337 

In order to make Bokeh's SVG backend up to [HTML Standard](https://html.spec.whatwg.org/#dom-context-2d-ellipse) the arc function should use the ellipse implementation which is currently not defined.

**Comment by IuryPiva** [comment]
Ellipses on SVG and CanvasContext differs too much and have some clear limitations:
 - SVG ellipse element is made of 4 different elliptical arcs https://www.w3.org/TR/SVG/shapes.html#EllipseElement each covering a quarter of the ellipse which can't be given start and end angles like CanvasContext' ellipse https://html.spec.whatwg.org/#dom-context-2d-ellipse
 - Rotation happens in the origin for CanvasContext and on calculated center for SVG
 
 Canvas left SVG Right
<img width="633" alt="image" src="https://user-images.githubusercontent.com/26139868/124540897-b4350900-ddf6-11eb-82de-fa971373a8dd.png">

**Comment by mattpap** [comment]
Resolved in PR #11337.
