### ISSUE TITLE
[BUG] `SVGRenderingContext2D.arc()` differs from Canvas specification, it breaks if used without calling `beginPath()` beforehand

### ISSUE THREAD

**Issue by IuryPiva** [bokeh/bokeh#11402]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python version      :  3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09) 
IPython version     :  7.24.1
Tornado version     :  6.1
Bokeh version       :  2.4.0dev1-34-gc9750ac3a
BokehJS static path :  /Users/iury/git-repos/bokeh/bokeh/bokeh/server/static
node.js version     :  v15.14.0
npm version          :  7.16.0
OS.                        : macOS Big Sur 11.5 Beta

#### Description of expected behavior and the observed behavior
When using `CanvasRenderingContext2D.arc()` it can be called without calling `CanvasRenderingContext2D.beginPath()`, if you try to do the same with `SVGRenderingContext2D.arc` it will show an error.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import {SVGRenderingContext2D} from "@bokehjs/core/util/svg"

const ctx = new SVGRenderingContext2D(size)
ctx.arc(0, 0, 5, 0, 2 * Math.PI);
ctx.fill();

```

#### Stack traceback and/or browser JavaScript console output

framework.js:89 TypeError: Cannot read property 'nodeName' of undefined
    at SVGRenderingContext2D.moveTo (svg.js:498)
    at SVGRenderingContext2D.lineTo (svg.js:520)
    at SVGRenderingContext2D.arc (svg.js:880)
    at test (svg.js:126)
    at svg.js:141
    at _run_test (framework.js:181)
    at yield_all (framework.js:111)
    at yield_all.next (<anonymous>)
    at Object.run_all (framework.js:87)
    at run?k=SVGRenderingContext2d:80
run_all	@	framework.js:89
async function (async)		
run_all	@	framework.js:87
(anonymous)	@	run?k=SVGRenderingContext2d:80
async function (async)		
(anonymous)	@	run?k=SVGRenderingContext2d:78
(anonymous)	@	run?k=SVGRenderingContext2d:81

**Comment by mattpap** [comment]
Resolved in PR #11407.
