### ISSUE TITLE
pandas future warning for commits.py

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11415]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh: current branch-2.4
Python: 3.8.8 (win10), 3.8.10 (ubuntu)
pandas: 1.3.0 (conda-forge)

#### Description of expected behavior and the observed behavior
Running `commits.py` (e.g. when building the docs) creates the following warning for line 61:

```
FutureWarning: Using .astype to convert from timezone-aware dtype to timezone-naive dtype is deprecated and will raise in a future version.  Use obj.tz_localize(None) or obj.tz_convert('UTC').tz_localize(None) instead
  data.index = pd.to_datetime(data.index, utc=True,).astype('datetime64[ns]').tz_localize('utc').tz_convert('US/Central')  # 15:11:58
```

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.sampledata import commits
```

**Comment by tcmetzger** [comment]
Changing line 61 in commits.py to

`data.index = pd.to_datetime(data.index, utc=True,).tz_convert('US/Central')`

removes the warning. The dtype of the resulting dataframe's index is still `datetime64[ns, US/Central]`.

**Comment by unnumsykar** [comment]
Hi , 
I am new to open source, can I try to fix this issue!

**Comment by bryevdv** [comment]
@unnumsykar That would be great, please let us know if we can help with any questions

**Comment by unnumsykar** [comment]
So how can I begin with this bug ??

**Comment by unnumsykar** [comment]
> Changing line 61 in commits.py to
> 
> `data.index = pd.to_datetime(data.index, utc=True,).tz_convert('US/Central')`
> 
> removes the warning. The dtype of the resulting dataframe's index is still `datetime64[None]`.

**Comment by unnumsykar** [comment]
from the above comments 

 I think by passing ```None``` will remove the time zone information preserving local time.
i.e   ```data.index = pd.to_datetime(data.index, utc=True,).tz_convert('None')```

Is is it correct or what else do i need to know ?

**Comment by bryevdv** [comment]
@unnumsykar I think you should edit the line as described by @tcmetzger  in https://github.com/bokeh/bokeh/issues/11415#issuecomment-876765407 which does not remove the timezone
