### ISSUE TITLE
On installation (v2.3.3): ModuleNotFoundError: No module named '_setup_support'

### ISSUE THREAD

**Issue by AndreasMartin72** [bokeh/bokeh#11414]
Getting this error using:
pip 21.1.3
python 3.7.9
Windows 10 (64bit)

**Comment by bryevdv** [comment]
@AndreasMartin72 I can't reproduce any issue on OSX:
<details>
```
piptest ❯ pip install bokeh
Collecting bokeh
  Downloading bokeh-2.3.3.tar.gz (10.7 MB)
     |████████████████████████████████| 10.7 MB 10.8 MB/s
Collecting PyYAML>=3.10
  Using cached PyYAML-5.4.1-cp39-cp39-macosx_10_9_x86_64.whl (259 kB)
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 30.6 MB/s
Collecting Jinja2>=2.9
  Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 25.8 MB/s
Collecting numpy>=1.11.3
  Downloading numpy-1.21.0-cp39-cp39-macosx_10_9_x86_64.whl (16.9 MB)
     |████████████████████████████████| 16.9 MB 17.2 MB/s
Collecting pillow>=7.1.0
  Downloading Pillow-8.3.1-cp39-cp39-macosx_10_10_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 20.9 MB/s
Collecting packaging>=16.8
  Downloading packaging-21.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 15.8 MB/s
Collecting tornado>=5.1
  Downloading tornado-6.1-cp39-cp39-macosx_10_9_x86_64.whl (416 kB)
     |████████████████████████████████| 416 kB 13.6 MB/s
Collecting typing_extensions>=3.7.4
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.0.1-cp39-cp39-macosx_10_9_x86_64.whl (13 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 7.2 MB/s
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: bokeh
  Building wheel for bokeh (setup.py) ... done
  Created wheel for bokeh: filename=bokeh-2.3.3-py3-none-any.whl size=11342778 sha256=c42243794c917cb1df437fff4244f0b187a78f04b5e91afdb5b738dd074ce779
  Stored in directory: /Users/bryan/Library/Caches/pip/wheels/b5/c4/82/45a0af76d9cf21105cace3ca73378a7799601153a02b0f58ae
Successfully built bokeh
Installing collected packages: six, pyparsing, MarkupSafe, typing-extensions, tornado, PyYAML, python-dateutil, pillow, packaging, numpy, Jinja2, bokeh
Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 PyYAML-5.4.1 bokeh-2.3.3 numpy-1.21.0 packaging-21.0 pillow-8.3.1 pyparsing-2.4.7 python-dateutil-2.8.1 six-1.16.0 tornado-6.1 typing-extensions-3.10.0.0

~ 16s
piptest ❯ python
Python 3.9.5 (default, May 18 2021, 12:31:01)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> bokeh
<module 'bokeh' from '/Users/bryan/anaconda/envs/piptest/lib/python3.9/site-packages/bokeh/__init__.py'>
>>>
```
</details>

Can you provide an actual screenshot or screen capture video of your install process?

**Comment by bryevdv** [comment]
Also to note this file has been part of our build for almost 5 years, it's not new. It's also correctly (still) included in the manifest: https://github.com/bokeh/bokeh/blob/branch-2.3/MANIFEST.in#L21

**Comment by bryevdv** [comment]
I was also able to successfully install by running `python setup.py install` directly from the sdist. @AndreasMartin72 I have to presume for now that this is some isolated issue with your setup. We will definitely need much more information to be able to investigate.

**Comment by bryevdv** [comment]
Also now can't repro any issue pip installing into a fresh Anaconda Python on a fresh Win10 VM:

<img width="1125" alt="Screen Shot 2021-07-08 at 00 45 18" src="https://user-images.githubusercontent.com/1078448/124883139-e163f180-df85-11eb-9c2d-f5737f0b6577.png">

cc @bokeh/dev if anyone has easy access to windows and wants to try, please do. I am inclined to close with `norepro` tomorrow unless someone can demonstrate in detail how to reproduce a problem

**Comment by xavArtley** [comment]
@bryevdv I installed bokeh==2.3.3 using pip without any problem
![image](https://user-images.githubusercontent.com/18531147/124891463-4dbc1080-dfd9-11eb-9c4f-5aabb3cc8282.png)

**Comment by AndreasMartin72** [comment]
Thank you for supporting!

Here some more detailed information:
```
c:\Py37\Scripts>pip install --proxy=http://XXXXXXXXXXXXX:8080 bokeh
Collecting bokeh
  Downloading bokeh-2.3.3.tar.gz (10.7 MB)
     |████████████████████████████████| 10.7 MB 6.8 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\py37\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\X\\AppData\\Local\\Temp\\pip-install-lcl24ug6\\bokeh_0219a4718151425f82abe066b50a551d\\setup.py'"'"'; __file__='"'"'C:\\Users\\X\\AppData\\Local\\Temp\\pip-install-lcl24ug6\\bokeh_0219a4718151425f82abe066b50a551d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\X\AppData\Local\Temp\pip-pip-egg-info-ozgnykd3'
         cwd: C:\Users\X\AppData\Local\Temp\pip-install-lcl24ug6\bokeh_0219a4718151425f82abe066b50a551d\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\X\AppData\Local\Temp\pip-install-lcl24ug6\bokeh_0219a4718151425f82abe066b50a551d\setup.py", line 68, in <module>
        from _setup_support import ( # isort:skip
    ModuleNotFoundError: No module named '_setup_support'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/85/9c8c47dc99671590e21d0cecf5cf1208db0ddb525093b2fecdbb233e3645/bokeh-2.3.3.tar.gz#sha256=a5fdcc181835561447fcc5a371300973fce4114692d5853addec284d1cdeb677 (from https://pypi.org/simple/bokeh/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading bokeh-2.3.2.tar.gz (10.7 MB)
     |█████████████▌                  | 4.5 MB 6.4 MB/s eta 0:00:01
ERROR: Operation cancelled by user
```

Trying to install manually:
```
c:\x\bokeh-2.3.3>dir .

 Verzeichnis von c:\x\bokeh-2.3.3

07.07.2021  19:54    <DIR>          .
07.07.2021  19:54    <DIR>          ..
07.07.2021  19:54    <DIR>          bokeh
07.07.2021  19:54    <DIR>          bokeh.egg-info
07.07.2021  19:49           337.317 CHANGELOG
07.07.2021  19:46               851 classifiers.txt
07.07.2021  19:46             1.494 LICENSE.txt
07.07.2021  19:46               769 MANIFEST.in
07.07.2021  19:54            16.642 PKG-INFO
07.07.2021  19:46            12.261 README.md
07.07.2021  19:54             2.708 setup.cfg
07.07.2021  19:46             4.913 setup.py
07.07.2021  19:54    <DIR>          tests
07.07.2021  19:46            70.143 versioneer.py
07.07.2021  19:46            12.761 _setup_support.py
              10 Datei(en),        459.859 Bytes
               5 Verzeichnis(se), 207.650.742.272 Bytes frei

c:\x\bokeh-2.3.3>python --version
Python 3.7.9

c:\x\bokeh-2.3.3>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    from _setup_support import ( # isort:skip
ModuleNotFoundError: No module named '_setup_support'
```

**Comment by bryevdv** [comment]
If you manually untarm the sdist is the file there?

**Comment by bryevdv** [comment]
The file is clearly there. Is your Python customized in any way at all? Custom PYTHONPATH, anything?

**Comment by bryevdv** [comment]
@AndreasMartin72 I have built a wheel manually, that will be (temporarily) availalble at https://files.bokeh.org/bokeh-2.3.3-py3-none-any.whl. Does that wheel install for you? My best guess is that your python installation or configuration is somehow non-standard. Starting with version 2.4 wheels will be published to PyPI.

**Comment by bryevdv** [comment]
Just noting for reference that the `_setup_support.py` module (and imports from it in `setup.py`) were added in PR https://github.com/bokeh/bokeh/pull/5760 which puts things at since *0.12.5* almost half a decade ago. With tens of millions of successful installs since then, I am confident that this is not any kind of generalized problem, and that whatever is going on is localized/specific to the one system. @AndreasMartin72 please also try installing on other systems to confirm.

**Comment by AjayThorve** [comment]
Can confirm the install works fine on my windows 10 64bit machine,  pip 21.1.3

![image](https://user-images.githubusercontent.com/20476096/124966455-33cdfe00-dfd8-11eb-8071-2db3357c6c3c.png)

**Comment by bryevdv** [comment]
For good measure I have also made checked with Python 3.7.9 specifically, just to rule out something to do with Python version, and again cannot reproduce any issue

<img width="879" alt="Screen Shot 2021-07-08 at 11 58 50" src="https://user-images.githubusercontent.com/1078448/124976336-f7a09a80-dfe3-11eb-8679-836dcd7c958e.png">

**Comment by AndreasMartin72** [comment]
> The file is clearly there in the directory listing you provided. Is your Python customized in any way at all? Custom PYTHONPATH, anything? Where/how is your Python installed from?

Since I have no admin privileges on the target machine, I installed Python by extracting the "Windows embeddable package (64-bit)" from https://www.python.org/downloads/windows in Folder C:\Py37
Then I installed pip: `python get-pip.py --proxy="http://[user:passwd@]proxy.server:port"`
For this issue I have my PATH variable set to: `set PATH=C:\Py37;C:\Py37\Scripts` nothing else.
I installed many other packages (numpy, matplotlib, seaborn, scikit-learn, ...), so I'm confused, why this fails...

**Comment by AndreasMartin72** [comment]
It seems to be due to the embedded version of Python. I'm now able to use the Python installer, when deselecting the option "for all useres", no admin privileges are neccessary. Now all works fine for me.
Thanks for your support!!
