### ISSUE TITLE
[FEATURE] Avoid using numpy.append when streaming numpy data

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#11424]
I'm profiling the Dask dashboard and finding that we're spending a decent amount of time here

https://github.com/bokeh/bokeh/blob/391c8e5c66a87a801257b3d0f8931fb1ed035947/bokeh/core/property/wrappers.py#L434-L436

I wonder if there is a way to avoid appending numpy arrays together.  This triggers a full copy of both.

**Comment by bryevdv** [comment]
@mrocklin do you have any specific ideas? I am not personally aware of what else could be done with *numpy* but perhaps I am just unaware. Otherwise maybe we could allow new array types to be used as columns, and utilize any extra features those might have e.g. for reserving capacity and avoiding copies on append.

**Comment by mrocklin** [comment]
I don't know the details of bokeh at this part particularly well, so it's hard to say.  

In other systems that I've dealt with that deal with streaming numpy-like data around we tend not to keep a single large numpy array, but instead a deque of smaller numpy arrays.  This is also, I think, how bytearray works (roughly).  Semantically you have one large array-like thing.  You can extend it easily and let data fall off of it easily and stream through it easily.  It's slightly harder to do random access but ok.

**Comment by mrocklin** [comment]
I have no idea if this is right for Bokeh though.

**Comment by bryevdv** [comment]
I'd love to have a chunked array option for CDS columns, I'd just like to think we wouldn't / shouldn't have to reinvent all of that wheel from scratchm(and maintain it). Will have to do some research and see if there are existing tools or NumPy wrappers would could use out of the box.

**Comment by mrocklin** [comment]
If you can provide the necessary API that Bokeh needs I'm happy to pass this around to people who may know.  If it's simple enough I may also be able to get someone to build something.

**Comment by bryevdv** [comment]
Well, for a start here is the `transform_array` function that currently handles NumPy arrays (and ultimate Pandas Series) as well 

https://github.com/bokeh/bokeh/blob/391c8e5c66a87a801257b3d0f8931fb1ed035947/bokeh/util/serialization.py#L429-L464

More or less it needs to handle two cases:

* if ` buffers` is None then this is standalone (HTML) case and we need to convert to a single base64-encoded array to include in the static output
* Otherwise, we are sending  data over the wire protocol and need to generate a buffer to send over the Websocket, this is currently more or less:
    ```
        buffer_id = make_id()
        buf = (dict(id=buffer_id), array.tobytes())
        buffers.append(buf)

        return BufferJson(
            __buffer__  = buffer_id,
            shape       = array.shape,
           dtype       = str(array.dtype.name),
            order       = cast(ByteOrder, sys.byteorder),
        )
    ```

Of course, for streaming we don't actually need to do all this serialization, we just need to be a able to do the no-copy append to the column, and send the steam event with the marginal new data. But whatever is used as a  column needs to support the above for the *non-streaming* cases.

**Comment by mrocklin** [comment]
I see two options:

1.  Ideally the protocol would be fine with us sending a sequence of buffers and it would fill up a large buffer on the other side (although I suspect that this is a larger change)
2. We could use a `bytearray`, although this might just be delaying the problem, depending on how the code that sends these buffers works

**Comment by bryevdv** [comment]
@mrocklin just to reiterate, if you are streaming then the only data that is sent is the small new streamed data, not the entire buffer (or buffers). All you need is to precent the copy in the Python process, when streaming, correct? Then the comments above are specifically relevant to your case, but merely pointing out that whatever is added, also would need to work when *not streaming* also (in *that* case when the full data is sent).

**Comment by mrocklin** [comment]
> if you are streaming then the only data that is sent is the small new streamed data, not the entire buffer (or buffers)

OK, let me go back to my original example and get the full call stack.  Something may be amiss on my end.

**Comment by mrocklin** [comment]
Looking back on your recent conversation I'm not sure I fully understood.  At first I interpretted this as "if all you're doing is streaming then you shouldn't hit the `np.append` call.  I collected this stack to show otherwise.

distributed/dashboard/components/scheduler.py:1520

    self.source.stream(rectangles, self.n_rectangles)

bokeh/models/sources.py:419

    self._stream(new_data, rollover)

bokeh/models/sources.py:531

    self.data._stream(self.document, self, new_data, rollover, setter)

bokeh/core/property/wrappers.py:416

    data = np.append(self[k], new_data[k])

...


However, now I think that you may be saying something different .  I'm not sure though.

**Comment by mrocklin** [comment]
OK, I had an automated process that was polling the dashboard every second, causing a new page to be rendered, causing the bulk update.  This was an issue on my end.  Thank you for engaging here on a weekend and I apologize for the disruption.

**Comment by mrocklin** [comment]
(I linked to the issue above if you want to take a look at what was happening)

**Comment by bryevdv** [comment]
> At first I interpretted this as "if all you're doing is streaming then you shouldn't hit the np.append call. 

No, the opposite:

* The append *only* happens during streaming
* The fill buffer(s) serialization only append during non-stream
* Any new "chunked array" column type needs to work for both of the above

Does that clarify?

**Comment by bryevdv** [comment]
@mrocklin another idea occurred to me. The only reason the `append` is even necessary at all is to keep the `data` completely in sync between Python and JS. But if you only need to stream *to* the client, then perhaps a simpler option would be a  new *streaming only* data source that does not keep any data at all on the Python side, it just sends it to  BokehJS and forgets about it. Thoughts?

**Comment by mrocklin** [comment]
I can imagine use cases for that.  I think that that would cover most of
our cases going forward.  However this stopped being a pain point though,
and my guess is that you have other things to do.  If I have a limited
supply of Bokeh karma then I would choose not to burn it on this one :)
