### ISSUE TITLE
Widget docs, examples and deprecation status

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#1143]
List of current available widgets:

* ~~DataSlider~~
* DataTable
* ~~HandsonTable~~
* TableColumn
* ~~PivotTable~~
* ~~ObjectExplorer~~
* ~~IPythonRemoteData~~
* ~~PandasPivotTable~~
* ~~PandasPlotSource~~
* Paragraph
* HBox
* VBox
* ~~VBoxModelForm~~
* VBoxForm
* TextInput
* PreText
* Select
* Slider
* MultiSelect
* DateRangeSlider
* DatePicker
* Panel
* Tabs
* Dialog

@everyone who has information on whether these widgets should be removed or not and/or information on what they do, please edit or comment. We should, ideally also provide an example for each of them. I think an example is probably more effective to understanding what it does than reading about it.

**Comment by bryevdv** [comment]
All of the widgets are all now documented in the user guide, with an inline rendered code example generated by `bokeh-plot` sphinx directive. There are also numerous examples of using widgets with both customJS and python callbacks.
