### ISSUE TITLE
Selenium unit tests fail on Ubuntu locally

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11449]
While working on updating the dev docs sections on writing and running tests, I could not figure out how to run all unit tests on Ubuntu 20.4 locally (specifically the Selenium-related export tests).

This is what I did:

- [Download Ubuntu 20.4](https://ubuntu.com/download/desktop/thank-you?version=20.04.2.0&architecture=amd64) and install in a new 64-bit Linux VM in Oracle Virtual Box (Version 6.1.18 r142142 from virtualbox.org on Win10). Install VirtualBox Guest Additions, git, and miniconda.
- Set up dev environment: 
    - `git clone https://github.com/bokeh/bokeh.git`
    - `conda env create environment.yml`
    - `npm install -g npm@7`, `npm ci`
    - `python setup.py develop --build-js`
    - `bokeh sampledata`
- without installing any extra packages, the conda env now includes selenium 3.141.0, geckodriver 0.29.0, firefox 90.0 (no chromedriver or chrome). Running my own little export test works flawlessly:
    ````
    from bokeh.io import export_png, export_svg
    from bokeh.plotting import figure
    p = figure()
    line = p.line([1,2], [3,4])
    export_png(p, filename="plot.png")
    export_svg(p, filename="plot.svg")
    ````
- However, running `pytest tests/unit/` results in: 3 failed, 8185 passed, 9 skipped, 74 warnings, 19 errors. The error message is "Message: 'chromedriver' executable needs to be in PATH." - so it seems like tests require chromedriver and will not work with geckodriver.
- Therefore, install chromedriver with conda: `conda install -c conda-forge python-chromedriver-binary` (following https://docs.bokeh.org/en/latest/docs/user_guide/export.html#additional-dependencies)
- with python-chromedriver-binary 92.0.4515.43.0 installed, `pytest tests/unit/` still produces the same errors as before - because for some reason, conda install only puts chromedriver into `~/miniconda3/envs/bkdev/lib/python3.9/site-packages/chromedriver_binary` but not into PATH. 
- After `sudo cp ~/miniconda3/envs/bkdev/lib/python3.9/site-packages/chromedriver_binary/chromedriver /usr/bin/` (and also `sudo apt-get install chromium-browser` for chromium 92.0.4515.107), `pytest tests/unit/bokeh/io/test_export.py` still errors. Error message: `<class 'selenium.common.exceptions.WebDriverException'>Message: unknown error: DevToolsActivePort file doesn't exist`

This is where I'm stuck now.

First of all, if unit tests do in fact require chromedriver (and, other than the export_ functions in bokeh.io, do not work with geckodriver), we should update the dev docs accordingly. 

We should also consider providing better instructions on how to install and configure selenium with chromedriver if chromedriver is the only option to run unit tests with. Or is there a way to include chromedriver in environment.yml like we do with geckodriver?

I would also consider making `pytest -m "not selenium" tests/unit` the recommended way to run unit tests locally to lower the bar for new contributors.

My issue with using conda to install chromedriver requiring an extra step might also be a problem with miniconda - nevertheless, we might also have to document this because we generally recommend using Anaconda or miniconda.

**Comment by tcmetzger** [comment]
I also tried a similar thing in my native win10 environment. Here, `conda env create environment.yml` also only installed geckodriver/firefox with selenium, not chromedriver. I also got the same error messages indicating that chromedriver is required for the unit tests. And also here, after running `conda install -c conda-forge python-chromedriver-binary`, I still had to manually add `chromedriver.exe` to my PATH. 
However, when running `pytest.exe .\tests\unit\bokeh\io\test_export.py` in Anaconda Powershell, there are no errors anymore, just test_get_svg_no_svg_present failed, with `<class 'AssertionError'> assert ['<svg versio...g=="/></svg>'] == ['<svg versio...mCC"/></svg>']`

So, it seems like at least on Ubuntu and Windows, a user has to manually install the chromedriver package from conda-forge and then add the executable to PATH before running the tests.

Running `chromium --headless` on my Ubuntu VM gives me the following output:
````
[0727/093827.278832:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for swiftshader
[0727/093827.296931:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
````
So it is possible that my problem with `DevToolsActivePort file doesn't exist` mentioned above is related to some VirtualBox-specific graphics driver issues.

**Comment by tcmetzger** [comment]
Running `conda install -c conda-forge python-chromedriver-binary` downloads this package: https://github.com/danielkaiser/python-chromedriver-binary (also works with `pip install chromedriver-binary`). According to the docs in this repo, there are indeed manual steps required to get `chromedriver` to run. The package comes with a little script, `chromedriver-path`, to add chromedriver to PATH: 
````
export PATH=$PATH:`chromedriver-path`
`````
Another way to use this package is using a different/additional import like in this example: 

````
from selenium import webdriver
import chromedriver_binary  # Adds chromedriver binary to path

driver = webdriver.Chrome()
driver.get("http://www.python.org")
assert "Python" in driver.title
`````

So, I guess we have two options:
* update our docs to include information on how to install chromedriver after installing  python-chromedriver-binary
* modify our handling of the webdriver to import chromedriver_binary  

@bryevdv / @mattpap do you have a preference here?

**Comment by IuryPiva** [comment]
The same happened with me on MacOS. The tests would fail unless I manually install chromedriver and add to path

**Comment by tcmetzger** [comment]
@bryevdv on a system with a functioning geckodriver and no chromedriver available, I tried `pytest --driver="firefox" tests/unit/bokeh/io/test_export.py` but still got the error message "'chromedriver' executable needs to be in PATH."

The `--driver` setting generally seems to be available according to `conftest.py`:
https://github.com/bokeh/bokeh/blob/e7c5155403747275a39d73a11171d7b6edecb748/conftest.py#L34

But I could not make it take effect on the unit tests.

However, when I manually changed
https://github.com/bokeh/bokeh/blob/e7c5155403747275a39d73a11171d7b6edecb748/tests/unit/bokeh/io/test_export.py#L49

to `@pytest.fixture(scope="module", params=["firefox"])`, the test ran with Firefox and passed!

**Comment by bryevdv** [comment]
@tcmetzger Evidently that option is specific to the tests in `tests/intgration`:
```
dev-3.9 ❯ pytest tests/integration/models/test_datarange1d.py  --driver="firefox"
=============================================================== test session starts ================================================================
platform darwin -- Python 3.9.4, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/bryan/work/bokeh, configfile: setup.cfg
plugins: cov-2.12.1, asyncio-0.15.1, flaky-3.7.0, html-3.1.1, xdist-2.2.1, metadata-1.11.0, forked-1.3.0
collected 4 items

Bokeh selenium tests using 'firefox' driver (no-console-error assertions: OFF)
```

And if I actually look in `test_export.py` I see that there is actually a different local pytest ficxture that makes the test always run for *both* drivers:
```
@pytest.fixture(scope="module", params=["chromium", "firefox"])
def webdriver(request: pytest.FixtureRequest):
    driver = webdriver_control.create(request.param)
    try:
        yield driver
    finally:
        webdriver_control.terminate(driver)
```
which can actually be seen in the verbose test output:
```
tests/unit/bokeh/io/test_export.py::test_get_screenshot_as_png[chromium-dimensions0] PASSED                                                            [  3%]
tests/unit/bokeh/io/test_export.py::test_get_screenshot_as_png[chromium-dimensions1] PASSED                                                            [  6%]
tests/unit/bokeh/io/test_export.py::test_get_screenshot_as_png[chromium-dimensions2] PASSED                                                            [  9%]

.....
                                                            [ 42%]
tests/unit/bokeh/io/test_export.py::test_get_screenshot_as_png[firefox-dimensions0] PASSED                                                             [ 45%]
tests/unit/bokeh/io/test_export.py::test_get_screenshot_as_png[firefox-dimensions1] PASSED                                                             [ 48%]
tests/unit/bokeh/io/test_export.py::test_get_screenshot_as_png[firefox-dimensions2] PASSED                                                             [ 51%]
```

Presumably this is so that we can ensure that export is working on both browsers. That's definitely the best thing to do from a "project reliability" POV but at the same time it's also definitely a higher burden on new contributors trying to run these tests locally. 

I am maybe just inclined to tell users to run with `-m "not selenium"` as a first / default step, at least for now.

**Comment by bryevdv** [comment]
As an aside, I recall now I had wanted to confine `--driver` to only the integration tests, instead of being a top-level option that every test suite would accept, even if it did not apply. But that is not supported by pytest:

https://stackoverflow.com/questions/51311988/way-to-add-pytest-options-outside-top-level-conftest

**Comment by tcmetzger** [comment]
@bryevdv thanks for your explanation, that makes a lot of sense!

> I am maybe just inclined to tell users to run unit tests with -m "not selenium" as a first / default step, at least for now.
I'm +1 on that!

**Comment by mattpap** [comment]
What's the resolution of this issue?

**Comment by tcmetzger** [comment]
@mattpap  As @bryevdv suggested, we now generally recommend people run tests locally with `-m "not selenium"` (while of course still explaining all the prerequisites to also run selenium tests locally).
