### ISSUE TITLE
[BUG] license-related codebase tests on Win10 fail

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11444]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Win10 
Bokeh version: current branch-2.4
Python version 3.8.8

#### Description of expected behavior and the observed behavior
Running ` pytest tests/codebase` on a clean and freshly reset `branch-2.4` branch should not fail. However, both `test_js_license_set.py` and `test_license.py` fail with ` FileNotFoundError: [WinError 2] The system cannot find the file specified`. 

Running the same tests on the exact same branch on Ubuntu  20.04 returns no errors (so maybe this is related to case-sensitivity being handled differently in Win and Linux?).

#### Complete, minimal, self-contained example code that reproduces the issue

```
pytest tests/codebase
```

#### Stack traceback and/or browser JavaScript console output
````
========================================================== short test summary info ==========================================================
FAILED tests/codebase/test_js_license_set.py::test_js_license_set - FileNotFoundError: [WinError 2] The system cannot find the file specified
FAILED tests/codebase/test_license.py::test_license_set - FileNotFoundError: [WinError 2] The system cannot find the file specified
================================================= 2 failed, 23 passed, 1 warning in 58.86s ==================================================
````

**Comment by tcmetzger** [comment]
I remember @Ariel-Yeung mentioning the same issue with Windows a few days ago. It would be great to hear from other Windows users to confirm this as something that needs looking into.

**Comment by bryevdv** [comment]
We could just skip these on windows, that would be fine with me. The main thing is that they run in CI. If there's an easy/quick fix that's fine too though. However,

> Running pytest tests/codebase on a clean and freshly reset main 

Generally speaking people should only be working on `branch-x.y` branches, and not main.

**Comment by tcmetzger** [comment]
@bryevdv I meant branch-2.4, of course - that is also what I ran my tests on. I'll edit my original post.

I'm also fine with skipping those tests on Windows, if that's the easiest fix.
