### ISSUE TITLE
[BUG] Hover glyphs permanently rendered with vline/hline mode in 2.4.0dev

### ISSUE THREAD

**Issue by g-parki** [bokeh/bokeh#11446]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
OS   :  macOS Big Sur 11.4
Browser    :   Safari 14.1.1 
Python version      :  3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15) 
IPython version     :  7.25.0
Tornado version     :  6.1
Bokeh version       :  2.4.0dev1-48-g9538fd6ff
node.js version     :  v16.4.1
npm version         :  7.20.0

#### Description of expected behavior and the observed behavior
Expected: Hover glyphs to individually render according to hline/vline cursor hit testing.
Observed: Hover glyphs immediately, permanently rendered when cursor is over plot area.

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.models import HoverTool
from bokeh.plotting import figure, show

p = figure()
cr = p.circle(x = [1,2,3,4], y = [1,2,3,4], size=20,
              fill_color="steelblue",
              hover_fill_color="red", hover_alpha=0.1)
p.add_tools(HoverTool(tooltips=None, renderers=[cr], mode='vline'))
show(p)
```

#### Stack traceback and/or browser JavaScript console output
_[Log] [bokeh] setting log level to: 'info' (bokeh-2.4.0dev1.min.js, line 184)
[Info] [bokeh] – "document idle at 40 ms" (bokeh-2.4.0dev1.min.js, line 165)_

#### Screenshots or screencasts of the bug in action
<img width="624" alt="image" src="https://user-images.githubusercontent.com/61096711/127077052-982d9436-fe27-47d1-b5dd-94f664011503.png">

*Note: Everyone interacting in the Bokeh project's codebases, issue trackers, and discussion forums is expected to follow the [Code of Conduct](https://github.com/bokeh/bokeh/blob/master/CODE_OF_CONDUCT.md).*

**Comment by bryevdv** [comment]
Can confirm it's only with vline/hline (which is definitely odd).

**Comment by bryevdv** [comment]
See also this example in the current dev docs https://docs.bokeh.org/en/dev-2.4/docs/user_guide/styling.html#hover-inspections

**Comment by bryevdv** [comment]
Ah the other salient observation: a vline hit should only inspect one of the scatter circles above, but it triggers for all of them. Speculating the is a bad change in the selection/hit-test restult

**Comment by g-parki** [comment]
> a vline hit should only inspect one of the scatter circles above, but it triggers for all of them.

Correct, and it’s also permanent. When the cursor is moved off the plot, all the points are still rendered as if they’re hovered
