### ISSUE TITLE
Bokeh-CI unit export tests failing 

### ISSUE THREAD

**Issue by g-parki** [bokeh/bokeh#11460]
Relates to most recent tests on:

- #11441
- #11458
- #11456
- #11459

We're getting a common error in `test_get_svg_no_svg_present()`
#### Stack traceback and/or browser JavaScript console output
```
	[<TracebackEntry D:\a\bokeh\bokeh\tests\unit\bokeh\io\test_export.py:152>]
test_get_svg_no_svg_present failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	assert ['<svg versio...g=="/></svg>'] == ['<svg versio...mCC"/></svg>']
  At index 0 diff: '
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
width="20" height="20"><defs/><image width="20" height="20" preserveAspectRatio="none"
xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAGxJR
EFUOE9j/P//vwMDAwMIUwUw/v//v4GBgaGeKqYxMDCMGggJyTdv3jD8+vWLYLCysbExiIiIoKjDGobPnj1jkJKSImggNnWjBkKCbTQM
cSafgUs2xOYUZmbmC+Li4gbIXhgtbQiWBwQVAAAO4ZJGgX8M6QAAAABJRU5ErkJggg=="/></svg>' !=
'<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
width="20" height="20"><defs/><image width="20" height="20" preserveAspectRatio="none"
xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAbElEQVQ4T2P8//+/AwMD
AwhTBTD+//+/gYGBoZ4qpjEwMIwaCAnJN2/eMPz69YtgsLKxsTGIiIigqMMahs+ePWOQkpIiaCA2daMGQoJtNAxxJp+BSzbE5hRmZ
uYL4uLiBsheGC1tCJYHBBUAAA7hkkaBfwzpAAAAAElFTkSuQmCC"/></svg>'
```

*Note: Everyone interacting in the Bokeh project's codebases, issue trackers, and discussion forums is expected to follow the [Code of Conduct](https://github.com/bokeh/bokeh/blob/master/CODE_OF_CONDUCT.md).*

**Comment by bryevdv** [comment]
What's changed? #11450 and #11453 from the last day or two had successful runs.

**Comment by g-parki** [comment]
Brainstorming... does the test environment depend on any of the docker stuff removed in #11454?

**Comment by bryevdv** [comment]
No nothing should depend on that, and also everything in there was hopelessly broken and out of date. I would be floored if that was related in any way.

**Comment by mattpap** [comment]
> What's changed? #11450 and #11453 from the last day or two had successful runs.

At least PR #11453 I already restarted a few times. Those are undeterministic failures. I don't have an explanation yet, but fortunately they fail on all platforms (originally mostly on macos).

**Comment by bryevdv** [comment]
For now can we add `@flaky` or `@skip` to minimize impact on other PRs?

**Comment by g-parki** [comment]
> For now can we add `@flaky` or `@skip` to minimize impact on other PRs?

ok, on it
