### ISSUE TITLE
dev build sdists do no carry correct version info

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1148]
Normally `versioneer.py` replaces `bokeh/_version.py` with hardcoded version information. I think this is the problem:
```
if 'BOKEH_DEV_VERSION' in os.environ:
    _version = os.environ['BOKEH_DEV_VERSION']
    _cmdclass = {'build_py': build_py}
else:
    _version = versioneer.get_version()
    _cmdclass = versioneer.get_cmdclass()
```
We need to write our own `_version.py` for dev builds, or extend it or versioneer to accommodate our dev build process.

**Comment by bryevdv** [comment]
@damianavila is this part of any of your current WIP?

**Comment by damianavila** [comment]
Nop, but we can integrate it... assigning to myself
