### ISSUE TITLE
[FEATURE] Enhanced docstrings for gallery entries

### ISSUE THREAD

**Issue by hyles-lineata** [bokeh/bokeh#11489]
Now that we have a new section to present ReST docstrings for gallery examples, update the existing gallery examples with docstrings including (where applicable):
- a brief description of the plot and data source
- link to sampledata
- link to APIs used in example
- link to relevant User Guide section

**Comment by bryevdv** [comment]
re-opening to cover updating examples to now use the new directive from #11490
