### ISSUE TITLE
build_and_upload.sh needs improvements

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1149]
Several improvements:
* [ ] detailed build output goes to log files
* [ ] high-level operation steps to stdout
* [ ] summary success/failure for every upload inane place at completion
* [x] move to `scripts` dir
* [x] remove generated `__conda_version__.py` files at the end

**Comment by damianavila** [comment]
Since now the script run on the cloud, a lot of these improvements have less importance (probably some of them can be dismissed). In any case, there is still some of them which are needed. I will work on them after 0.8 release.

**Comment by bryevdv** [comment]
@damianavila is this issue still needed to be open?

**Comment by damianavila** [comment]
I think the script is pretty stable and, soon, we need to evaluate the migration to the anaconda build system... so, any further developments should be done in that work, I think. Let's close this one for now.
