### ISSUE TITLE
[BUG] The update() method is not equivalent to changing widget properties directly

### ISSUE THREAD

**Issue by EfremBraun** [bokeh/bokeh#11520]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.3.3
Python 3.8.5
MacOs Catalina 10.15.7
Google Chrome 92.0.4515.131

#### Description of expected behavior and the observed behavior
Per the docs:

> The following are equivalent:

```
from bokeh.models import Range1d

r = Range1d

# set properties individually:
r.start = 10
r.end = 20

# update properties together:
r.update(start=10, end=20)
```

However, this is not true. The `update` method pushes the changes to the browser, whereas changing properties directly does not. See below.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import Select, Button

# Set up widgets
select = Select(options=['1', '2'])
button1 = Button(label='Change select options directly')
button2 = Button(label='Change select options via update')

# Set up callbacks
def update_select_direct(attrname):
    select.options += ['3']

def update_select_update(attrname):
    select.update(options = select.options + ['3'])

button1.on_click(update_select_direct)
button2.on_click(update_select_update)


# Set up layouts and add to document
curdoc().add_root(column(select, button1, button2))

```

#### Stack traceback and/or browser JavaScript console output
Clicking the 'Change select options directly' button does not push the change made to the browser. The change does get made, but the user won't know until the other button is pressed.
Clicking the 'Change select options via update' button pushes the change made to the browser.

**Comment by bryevdv** [comment]
@EfremBraun The code in your second case is `+=`  `iadd` and not and `=` assignment, as per the docs, and I expect that is the difference. Will have to see if this can be supported or whether docs clarification is needed.

**Comment by EfremBraun** [comment]
You're right. Very strange. Changing the line from `select.options += ['3']` to `select.options = select.options + ['3']` fixes the issue. I thought the former was just a Python shortcut for the latter. I'm shocked to see that it's not...

**Comment by EfremBraun** [comment]
Didn't know about `iadd` before. Anyway, I'll leave this up here since, as you mentioned, it'd be nice to support this feature (or to amend the docs to clarify that it's not allowed).

**Comment by bryevdv** [comment]
> I thought the former was just a Python shortcut for the latter. 

Well, yes and no. Technically they are implemented by different special methods. But for standard Python types they are implemented to behave ust as you describe, i.e. with `a += b` as more or less a shortcut for `a = a + b`.

Bokeh properties are not simple Python types. They are heavily instrumented in order that "simple" operations like `slider.options = new_options` actually cause lots of thing to automagically happen:

* type validation
* triggering events
* serializing and sending to a separate browser process

Offhand, I would expect this to work, as our property list wrappers do in fact implement custom `iadd` methods:

https://github.com/bokeh/bokeh/blob/75a904132c77cf11e9d7f9ef2bc363cccfa4cada/bokeh/core/property/wrappers.py#L227-L230

However, that may only currently work right for Bokeh properties that are basic `List`, whereas the `options` property is actually a fairly complicated union type of several properties. It's possible the automatic container wrapping that happens for lists does not work for union types. More investigation will be needed.

**Comment by bryevdv** [comment]
JUst an update that I am almost certain the speculation above is correct. Comparing the actual type for the values of a `Select.options` vs ` MultiSelect.value` it's evident that the former is just a plain Python list (which is why calling `+=` on it does nothing special) but that that former is a Bokeh property list wrapper (that would intercept a call to `+=` to trigger change events);
```python
In [16]: s = Select()

In [17]: ms = MultiSelect()

In [18]: type(s.options)
Out[18]: list

In [19]: type(ms.value)
Out[19]: bokeh.core.property.wrappers.PropertyValueList
```

**Comment by bryevdv** [comment]
Here is a tiny diff that does fix the immediate problem:
```diff
diff --git a/bokeh/core/property/either.py b/bokeh/core/property/either.py
index 352c73c42..aa1b21b34 100644
--- a/bokeh/core/property/either.py
+++ b/bokeh/core/property/either.py
@@ -109,6 +109,11 @@ class Either(ParameterizedProperty):
         msg = "" if not detail else f"expected an element of either {nice_join(self.type_params)}, got {value!r}"
         raise ValueError(msg)

+    def wrap(self, value):
+        for tp in self.type_params:
+            value = tp.wrap(value)
+        return value
+
     # TODO (bev) implement this
     # def _may_have_unstable_default(self):
     #     return any(tp._may_have_unstable_default() for tp in self.type_params)
```
This seems like a very blunt way to attack the problem, that relies on `wrap` methods for distinct type params playing well together in a way that I don't think we have ever tried to guarantee. But AFAIK we don't keep track of which type param  is "engaged" so I am not sure we could do better.

**Comment by EfremBraun** [comment]
@bryevdv I pulled in #11521 and tested it on the example I gave in the first post, but I don't see anything different...
