### ISSUE TITLE
[FEATURE] Make `global_alpha` of `ImageRGBA` an `AlphaSpec`

### ISSUE THREAD

**Issue by bminixhofer** [bokeh/bokeh#11548]
**Is your feature request related to a problem? Please describe.**
I'm trying to highlight an `ImageRGBA` glyph on hover (i.e. globally increase the alpha on hover). I have it working by overwriting the image data with a new alpha on hover in a `CustomJS` callback looking roughly like this:

```javascript
// `highlight` is defined above, based on the `cb_data.index.image_indices`

source.data.image.forEach((image, i) => {
    if (source.data.highlighted[i] != highlight) {
        let color = highlight ? 200 : 100;

        for (let i = 0; i < image.length; i++) {
            if (image[i] > 0) {
                image[i] = image[i] & (255 | (255 << 8) | (255 << 16));
                image[i] = image[i] | (color << 24);
            }
        }

        source.data.highlighted[i] = highlight;
        source.change.emit();
    }
});
```

**Describe the solution you'd like**
The `ImageRGBA` glyph already has a `global_alpha` attribute but it is a `Float`. Making it an `AlphaSpec` would solve my issue, since then I could change it from Javascript like this:

```javascript
source.data.image.forEach((image, i) => {
    if (source.data.highlighted[i] != highlight) {
        let alpha = highlight ? 0.8 : 0.3;

        source.data.global_alpha[i] = alpha;
        source.data.highlighted[i] = highlight;
        source.change.emit();
    }
});
```

**Describe alternatives you've considered**
Currently, as an alternative it would be possible to pass the alpha values of each pixel as extra information to the `CustomJS` callback and use them to compute the alpha, but that's tedious.

**Comment by mattpap** [comment]
Also looks like SVG backend doesn't support global alpha properly.
