### ISSUE TITLE
URL printed in server startup log always assumes http protocol

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#11565]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
All software configurations when using a bokeh server are affected.

#### Description of expected behavior and the observed behavior
When the `bokeh serve` command is supplied with the ssl-related arguments allowing to serve https sessions, the resulting log should reflect that in the URL displayed in the output on startup. This is a bit of a detail obviously, but it would be better to have the right URL printed if possible.

Here is the code in [bokeh/serve.py](https://github.com/bokeh/bokeh/blob/branch-2.4/bokeh/command/subcommands/serve.py):

```python
for route in sorted(applications.keys()):
    url = "http://%s:%d%s%s" % (address_string, server.port, server.prefix, route)
    log.info("Bokeh app running at: %s" % url)
```

One can imagine that the protocol could be inferred from the provided arguments so that the `url` variable can be adapted accordingly. For instance when you're not behind a reverse proxy checking the existence of a certfile argument with .pem extension or the existence of both a .crt certfile and a keyfile argument might do the job.

**Comment by bryevdv** [comment]
@TheoMathurin Conditioning the reported protocol on the presence or absence of SSL config seems reasonable to me. Are you interested in submitting a PR for this?  If not, I will leave this unmilestoned and triaged as a `good first issue` for someone in the future.

**Comment by TheoMathurin** [comment]
@bryevdv Sure, I'll submit a first proposition in the coming days.
