### ISSUE TITLE
[FEATURE] Make AutocompleteInput more usable by providing an option to match any part of the input items

### ISSUE THREAD

**Issue by dev1010101** [bokeh/bokeh#11571]
**Problem:**
AutocompleteInput only matches start of the items, this severely limits the usability in some use cases.
e.g. when list is  ['Biology', 'Chemistry', 'Physics']
Typing "mis" should match Chemistry
Now it only matches when typing "Che"

**Solution:**
Provide a new option to enable matching any part of the string not just the beginning. \
The Javascript changes are trivial (it now uses string function StartsWith)

**Comment by tcmetzger** [comment]
@dev1010101 Thanks for the idea, that does sound pretty straightforward indeed. When implementing this change, it should be configurable, i.e. add a parameter to the object where a user can define if StartsWith or Includes is applied. This would mean updates to both the Python and JavaScript model.

Would you be interested in opening a PR on this? @IuryPiva can help you get started, if you'd like!

**Comment by pietrea2** [comment]
Hello! I'm interested in working on this change.
How can I get started?

**Comment by bryevdv** [comment]
@pietrea2 The dev setup guide is here:

https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html

The relevant line in the current implementation is here:

https://github.com/bokeh/bokeh/blob/69c578373d8d7a0aced34c2493ae4b3a7f072959/bokehjs/src/lib/models/widgets/autocomplete_input.ts#L149

The task will be to add a new property to `AutoComplete` (Python and BokehJS sides) and then change the code above to switch on the new property. By default it should perform the same old `startsWith` check, but for the other branch it will need to do the "includes" check.

**Comment by jennazch** [comment]
Hi! First time contributor here, I was wondering where this feature is in the application? As in, where can we see this feature in the UI when we build and run it?

**Comment by bryevdv** [comment]
HI @jennazch Just for some preliminary context, Bokeh has a server component that can be run, but more than anything, Bokeh is a library, which means Bokeh is something other people use as part of *their* applications. We do often have example scripts or demos in the docs that show example usage of the library features. 

However. the `Autocomplete` widget is maybe not one of the most commonly used widgets, and is a big lightly documented. As far as I know, the only example that shows it off is this one: 

https://github.com/bokeh/bokeh/blob/branch-3.0/examples/models/file/widgets.py

There probably also ought to be at least a minimal example on this page: 

https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html

But it seems to be missing. It would be convenient if whoever makes a PR for this issue could add a tiny example there in the same work.

**Comment by bryevdv** [comment]
@mattpap should this be closed?

**Comment by dev1010101** [comment]
Yes
