### ISSUE TITLE
Allow data models to inherit from non data models

### ISSUE THREAD

**Issue by marcuskd** [bokeh/bokeh#11596]
Hi,

I get an error if a ColumnDataSource is defined in a base class derived from a Bokeh class, whereas if the CDS is defined in a sub class of that base class then the error does not occur. Minimal example code...

```
from bokeh.core.properties import Instance
from bokeh.models.sources import ColumnDataSource
from bokeh.layouts import Row
from bokeh.plotting import Figure, show


class Base(Row):

    __view_model__ = 'Row'
    __subtype__ = 'Base'

    __view_module__ = 'bokeh'

    cds = Instance(ColumnDataSource)

    def __init__(self):
        super().__init__()
        self.cds = ColumnDataSource(data={'x': [0, 1], 'y': [2, 3]})


class Sub(Base):

    __view_model__ = Base.__view_model__
    __subtype__ = 'Sub'

    def __init__(self):

        super().__init__()
        fig = Figure()
        fig.line(self.cds.data['x'], self.cds.data['y'])
        self.children.append(fig)


if __name__ == '__main__':
    show(Sub())
```

The above code fails with the browser error:
**Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'set_value')
    at l.setv (bokeh-2.3.3.min.js:179)
    at Function._initialize_references_json (bokeh-2.3.3.min.js:165)
    at Function.from_json (bokeh-2.3.3.min.js:165)
    at w (bokeh-2.3.3.min.js:163)
    at Object.t.embed_items (bokeh-2.3.3.min.js:163)**
 
The following code works - all that has changed is moving the CDS from the base to sub class...

```
from bokeh.core.properties import Instance
from bokeh.models.sources import ColumnDataSource
from bokeh.layouts import Row
from bokeh.plotting import Figure, show


class Base(Row):

    __view_model__ = 'Row'
    __subtype__ = 'Base'

    __view_module__ = 'bokeh'

    def __init__(self):
        super().__init__()


class Sub(Base):

    __view_model__ = Base.__view_model__
    __subtype__ = 'Sub'

    cds = Instance(ColumnDataSource)

    def __init__(self):

        super().__init__()
        self.cds = ColumnDataSource(data={'x': [0, 1], 'y': [2, 3]})
        fig = Figure()
        fig.line(self.cds.data['x'], self.cds.data['y'])
        self.children.append(fig)


if __name__ == '__main__':
    show(Sub())
```

Is this a bug or am I doing something wrong?

Environment...
Windows 10
Chrome 93.0.4577.63 (Official Build) (64-bit)
Bokeh 2.3.3
Python 3.7.6

Thanks.

**Comment by mattpap** [comment]
I strongly doubt this mechanism (i.e. `__subtype__`) was ever tested with anything more complex than a single level of inheritance, so this not working may not be unexpected. This mechanism in really cumbersome and will be removed in bokeh 3.0, and replaced with data model (though those don't support this use case yet). Ultimately something like this should work in future versions of bokeh:
```py
from bokeh.core.properties import Instance
from bokeh.models.sources import ColumnDataSource
from bokeh.layouts import Row
from bokeh.plotting import Figure, show
from bokeh.model import DataModel

class Base(Row, DataModel):

    cds = Instance(ColumnDataSource)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.cds = ColumnDataSource(data={'x': [0, 1], 'y': [2, 3]})

class Sub(Base):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        fig = Figure()
        fig.line(self.cds.data['x'], self.cds.data['y'])
        self.children.append(fig)

show(Sub()
```

**Comment by marcuskd** [comment]
Thanks @mattpap for the quick response. I'll avoid this use case for now but will definitely revisit in 3.0 onwards, would be useful to be able to do this.
