### ISSUE TITLE
[BUG] Line segments vanishing with WebGL enabled

### ISSUE THREAD

**Issue by LordKobra** [bokeh/bokeh#11606]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh: 2.3.3
Python: 3.9.6
OS: Windows 10 / Manjaro Linux
Browser: Mozilla Firefox

#### Description of expected behavior and the observed behavior

Hello, Bokeh is a great library to plot and interactively analyze spatial data! Recently i discovered my trajectories/lines had missing segments. After a few experiments, I've come to conclusion it happens when WebGL is enabled and two consecutive points have the same coordinates.

In the example below, point 3 and 4 have the same coordinates. With WebGL enabled, the line segment P2-P3 and P4-P5 vanish and maybe even the zero-length segment P3-P4.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.plotting import figure, show
p = figure(plot_width=400, plot_height=400, output_backend="webgl")
p.line(x=[1,2,3,3,4,5], y=[0,0,1,1,6,10])
show(p)
```

#### Screenshots or screencasts of the bug in action
Expected Result without WebGL:
![expected_plot](https://user-images.githubusercontent.com/39347022/133293698-85edc132-3dee-4613-83e1-6611dfab83e9.png)
WebGL Result:
![error_plot](https://user-images.githubusercontent.com/39347022/133295313-e0dfe6f7-ae45-4e19-953d-0847d67f0b7f.png)

**Comment by bryevdv** [comment]
cc @ianthomas23 

@LordKobra please check again with 2.4.0rc1 available later today via `pip install --pre` This issue may already by fixed.

**Comment by LordKobra** [comment]
Thanks for the quick reply! I will try out later.

**Comment by bryevdv** [comment]
Actually I needed to create a 2.4.0rc env for testing anyway, this appears to be fixed in 2.4 already:

<img width="1068" alt="Screen Shot 2021-09-14 at 09 34 30" src="https://user-images.githubusercontent.com/1078448/133297924-2d0996bd-ddde-4f03-a102-946425a81092.png">

**Comment by mattpap** [comment]
Works fine in 2.4:
![image](https://user-images.githubusercontent.com/27475/133298316-814fa84b-7e01-4a7f-86aa-35d40b0afb3a.png)

**Comment by LordKobra** [comment]
That's great to see! I've also tested it on 2.4 and it's working.

Thanks a lot!
