### ISSUE TITLE
[BUG] Server embed notebook issue

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11610]
cc @mattpap 

2.4.0rc1 with classic notebook and jupyter lab:

<img width="903" alt="Screen Shot 2021-09-14 at 10 35 12" src="https://user-images.githubusercontent.com/1078448/133306406-070a6acb-04e2-4ec0-84e0-c90d4e52f51c.png">

**Comment by tcmetzger** [comment]
I saw what seems to be the same thing on win 10 (running `examples\howto\server_embed\notebook_embed.ipynb` in Jupyter Notebook 6.4.3 with Python 3.9.6 and Firefox 92.0):
![image](https://user-images.githubusercontent.com/39711796/133311893-cbc096d5-78fe-4b3e-bbf6-068f7701e0d0.png)

**Comment by mattpap** [comment]
This got broken when `var` was replaced with `const`/`let`.
