### ISSUE TITLE
[BUG] Hover tool takes long time to render

### ISSUE THREAD

**Issue by sistemicorp** [bokeh/bokeh#11629]
Possible regression from bokeh ver 2.3.0 to 2.4.0.  
Python 3.8. Chrome Version 93.0.4577.82 (Official Build) (64-bit). Ubuntu 20.

The hover tool is lightening fast to render in v2.3.0, but is very slow in 2.4.0 for the same minimal example.
```
from bokeh.layouts import layout
from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, Range1d, LinearScale, LinearAxis, HoverTool

NUM_DATA_POINTS = 48000

source = ColumnDataSource(data={
    "t": [i for i in range(1, NUM_DATA_POINTS)],
    "i": [i for i in range(1, NUM_DATA_POINTS)],
    "y": [i * 2 for i in range(1, NUM_DATA_POINTS)],
})

plot = figure(toolbar_location="above",
              y_range=(0.1, NUM_DATA_POINTS*4),
              x_range=(0, NUM_DATA_POINTS),
              y_axis_type="linear")

line = plot.line(x="t", y="i", line_width=2, source=source, color="green", legend_label="i")
plot.line(x="t", y="y", line_width=4, alpha=0.4, source=source, color="red", legend_label="y")

ht = HoverTool(
    tooltips=[("i", "@i{0.00}"), ("y", "@y{0}"), ("t", "@t{0.000} ms")],
    # >>> Uncomment to make hover tool really slow
    #mode='vline',
    #show_arrow=True,
    #renderers=[line],
)
plot.tools = [ht]
doc_layout = layout()
doc_layout.children.append(plot)
show(doc_layout)
```

Chrome Inspect console:
```
bokeh-2.4.0.min.js:520 [Violation] 'requestAnimationFrame' handler took 6005ms
bokeh-2.4.0.min.js:520 [Violation] 'requestAnimationFrame' handler took 5998ms
bokeh-2.4.0.min.js:520 [Violation] 'requestAnimationFrame' handler took 6091ms
```

**Comment by antoniomolram** [comment]
Hi, 

I still can see the performance issue. I was using 2.4.0 and now I just updated to 2.4.2. Still the performance is still poor. Is working but with a big amount of data the delay is really insane. @sistemicorp describe it quite well. I would like to let it open this issue until this performance issue is clarify

**Comment by bryevdv** [comment]
@antoniomolram I can't reproduce any issue with the original MRE in the OP, nor can I reproduce any issue with the 2300x130 heatmap MRE, which is why this issue was closed. If you are seeing an issue with some other usage pattern, please open a new issue referring to this one. But note it is absolutely necessary that you provide a complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) so that we have something concrete to investigate.

**Comment by bryevdv** [comment]
For reference here is Bokeh 2.4.2 and the 300k point heatmap (OSX/Safari)


![ScreenFlow](https://user-images.githubusercontent.com/1078448/144099988-6f04279d-7432-4f23-93e8-be562a41b4bc.gif)

**Comment by antoniomolram** [comment]
hi, yes, is more an 4M points. But for me the interesting part is if a disable the hover is fine, I can zoom the data and is working fine. What maybe can be useful is an option to click the data and see the hover information instead of showing the data just moving the mouse around.

**Comment by bryevdv** [comment]
>  What maybe can be useful is an option to click the data and see the hover information instead of showing the data just moving the mouse around. 

You could implement a `CustomJS` selection callback to update a div or text/labels on the plot. I will state categorically that 4M points is out of scope for normal Bokeh usage and reiterate that Holoviews+Datashader is really probably a much better avenue at that scale.

**Comment by stas-sl** [comment]
https://user-images.githubusercontent.com/4602302/151663233-3d63a011-f5c8-4dcd-8524-f05acc59ed32.mp4

I believe this is a HoloViews issue, that's why I created it there (https://github.com/holoviz/holoviews/issues/5198), though it might be related somehow
