### ISSUE TITLE
[BUG] mypy tests fail in Windows

### ISSUE THREAD

**Issue by g-parki** [bokeh/bokeh#11627]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
`branch-3.0` on Windows 10

#### Issue:
`mypy tests` fails in `tests\test_examples.py` because `signal.alarm()` doesn't exist on Windows. This is preventing us from using Windows for the CI codebase checks, suggested in #11625 

#### Ideas...
- Remove `tests.test_examples` from `pyproject.toml` so it just gets skipped
- Refactor the `signal` stuff to separate file which isn't included in `pyproject.toml`
- Do away with `signal.alarm()`

Here's the console error output:
```
tests\test_examples.py: note: In function "_run_example":
tests\test_examples.py:287:23: error: Module has no attribute "SIGALRM"  [attr-defined]
            signal.signal(signal.SIGALRM, alarm_handler)
                          ^
tests\test_examples.py:288:9: error: Module has no attribute "alarm"  [attr-defined]
            signal.alarm(20 if not example.is_slow else 60)
            ^
tests\test_examples.py:301:13: error: Module has no attribute "alarm"  [attr-defined]
                signal.alarm(0)
                ^
Found 3 errors in 1 file (checked 295 source files)
```

**Comment by mattpap** [comment]
Platform specific code has to be wrapped with:
```py

if sys.platform == 'win32':
    # Windows specific definitions
    ...
else:
    # Posix specific definitions
    ...
```
for mypy to understand.

**Comment by g-parki** [comment]
Thanks @mattpap
