### ISSUE TITLE
[FEATURE]  MultiChoice widget sorts options by default

### ISSUE THREAD

**Issue by PinkusFloyd** [bokeh/bokeh#11638]
**Is your feature request related to a problem? Please describe.**
I use the MultiChoice widget to display a list of options that are grouped in specific ways. By default, MultiChoice sorts these options and this can't be changed. This makes it difficult for me to find similar items in the dropdown. 

**Describe the solution you'd like**
Either: set sort to false by default and users can choose whether they want to pass in a sorted list, or pass through the option to set sorted. I think the first option is best, and this is consistent with similar widgets like Dropdown (and is a one liner code change). 

**Describe alternatives you've considered**
The only real alternative is using a different style of widget, eg. a MultiSelect

**Additional context**
The example on the widgets page in the documentation shows this happening: https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#multichoice

**Comment by bryevdv** [comment]
Bokeh uses [`choices.js`](https://github.com/Choices-js/Choices) for the underlying implementation so it really comes down to what is supported by that library. It looks likes there is a [`shouldSort`](https://github.com/Choices-js/Choices#shouldsort) option that defaults to true. I would not be opposed to changing this default and leaving the ordering up to users as suggests (avoiding any new code complexity on our end)

**Comment by PinkusFloyd** [comment]
Awesome, sounds good, thanks!

Just fyi, I set `shouldSort: false` in `multichoice.ts` in my dev env and it seemed to solve the problem as expected.

**Comment by bryevdv** [comment]
@PinkusFloyd would you like to submit a PR for this? A small update to the [integration test](https://github.com/bokeh/bokeh/blob/branch-3.0/tests/integration/widgets/test_multi_choice.py#L86) would be needed but we can help walk through that.

**Comment by PinkusFloyd** [comment]
Sure, I can make a PR in the next day or two. 

I can give the integration test a shot but I'm unfamiliar with it. How do you suggest I approach it?

**Comment by bryevdv** [comment]
@PinkusFloyd in the test I linked above, the passed-in options are pre-sorted. I think at a minimum it would suffice to deliberately un-sort those options, and then update the checks below that reference the first item in the options, accrodingly.

**Comment by bryevdv** [comment]
FYI There is info about running these Python integration tests locally in this section:

https://docs.bokeh.org/en/latest/docs/dev_guide/testing.html#run-python-tests

But you can also just make a first attempt at a PR and see how CI runs go.
