### ISSUE TITLE
[BUG] export_png() fails

### ISSUE THREAD

**Issue by EfremBraun** [bokeh/bokeh#11632]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.4.0
Python 3.9.7
MacOs Catalina 10.15.7
Google Chrome  93.0.4577.82
Selenium 3.141.0
geckodriver 0.29.1 
python-chromedriver-binary 93.0.4577.15.0

#### Description of expected behavior and the observed behavior
Since upgrading to the official 2.4.0 release, exporting plots from code has started throwing me an error. I have Selium, geckodriver, and python-chromedriver-binary installed, so I don't know what else to do.

NB that when I was using Bokeh version '2.4.0dev4+11.g03cc08c31', I wasn't getting this error.

#### Complete, minimal, self-contained example code that reproduces the issue
Copied from https://docs.bokeh.org/en/latest/docs/gallery/slider.html, and then added export_png()
```
import numpy as np

from bokeh.layouts import column, row
from bokeh.models import CustomJS, Slider
from bokeh.plotting import ColumnDataSource, figure, show
from bokeh.io import export_png

x = np.linspace(0, 10, 500)
y = np.sin(x)

source = ColumnDataSource(data=dict(x=x, y=y))

plot = figure(y_range=(-10, 10), width=400, height=400)

plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)

amp_slider = Slider(start=0.1, end=10, value=1, step=.1, title="Amplitude")
freq_slider = Slider(start=0.1, end=10, value=1, step=.1, title="Frequency")
phase_slider = Slider(start=0, end=6.4, value=0, step=.1, title="Phase")
offset_slider = Slider(start=-5, end=5, value=0, step=.1, title="Offset")

callback = CustomJS(args=dict(source=source, amp=amp_slider, freq=freq_slider, phase=phase_slider, offset=offset_slider),
                    code="""
    const data = source.data;
    const A = amp.value;
    const k = freq.value;
    const phi = phase.value;
    const B = offset.value;
    const x = data['x']
    const y = data['y']
    for (let i = 0; i < x.length; i++) {
        y[i] = B + A*Math.sin(k*x[i]+phi);
    }
    source.change.emit();
""")

amp_slider.js_on_change('value', callback)
freq_slider.js_on_change('value', callback)
phase_slider.js_on_change('value', callback)
offset_slider.js_on_change('value', callback)

layout = row(
    plot,
    column(amp_slider, freq_slider, phase_slider, offset_slider),
)

show(layout)

export_png(plot, filename="plot.png")
```

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "/Users/edbraun/test/test.py", line 49, in <module>
    export_png(plot, filename="plot.png")
  File "/Users/edbraun/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/bokeh/io/export.py", line 111, in export_png
    image = get_screenshot_as_png(obj, width=width, height=height, driver=webdriver, timeout=timeout)
  File "/Users/edbraun/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/bokeh/io/export.py", line 236, in get_screenshot_as_png
    web_driver = driver if driver is not None else webdriver_control.get()
  File "/Users/edbraun/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 153, in get
    self.current = self.create()
  File "/Users/edbraun/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 157, in create
    driver = self._create(kind)
  File "/Users/edbraun/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 175, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.
```

**Comment by mattpap** [comment]
Just to note, there not changes to `bokeh.io.{export,webdriver}` since 2.4.0dev4.

**Comment by EfremBraun** [comment]
Nonetheless, I can confirm that the above code works with the following environment:

Bokeh 2.4.0dev4+11.g03cc08c31
Python 3.9.6
MacOs Catalina 10.15.7
Google Chrome 93.0.4577.82
Selenium 3.141.0
geckodriver 0.29.1
(No chromedriver installed)

**Comment by bryevdv** [comment]
@EfremBraun your script works for me with 2.4, the export unit tests succeed on `branch-3.0`, on OSX. Also the export unit tests are passing on all platforms on CI. Besides what @mattpap has noted, I have to believe this comes down to a (different) difference between your two envs.

**Comment by EfremBraun** [comment]
Ach. Okay that's good to know. I'll debug and report any findings back here.

**Comment by EfremBraun** [comment]
Yes you're correct. I took the original environment that used Bokeh version '2.4.0dev4+11.g03cc08c31', upgraded to 2.4.0, and everything still works. I'll keep debugging to find the actual issue.

**Comment by EfremBraun** [comment]
Problem solved. Firefox was not installed via conda. `conda install firefox -c conda-forge` fixed this.

I'll close the issue.
