### ISSUE TITLE
[BUG] RangesUpdate not emitted when using xwheel_pan

### ISSUE THREAD

**Issue by alexbjorling** [bokeh/bokeh#11633]
The following code triggers the `RangesUpdate` event when using all the pan/zoom/reset tools, except for the `xwheel_pan` and `ywheel_pan` ones. I suspect this is not the intended behavior.

```
from bokeh.plotting import figure, curdoc
from bokeh.events import RangesUpdate

p = figure(tools=('xwheel_zoom', 'ywheel_zoom', 'xwheel_pan', 'ywheel_pan',
                  'box_zoom', 'pan', 'reset'))
p.line([1,2], [4,3])
p.on_event(RangesUpdate, lambda evt: print(evt))
curdoc().add_root(p)
```

This is bokeh 2.4.0, Python 3.9.7, Ubuntu 21.04.

**Comment by bryevdv** [comment]
I'm sure it needs a call to 
```
this.plot_view.trigger_ranges_update_event()
```
added. Quite honestly forget these tools exist, I still don't quite understand the point of a wheel pan. Triaging to land on `branch-3.0` since there's already several backports to 2.4.1 this can just be included in one batch.

**Comment by bryevdv** [comment]
@alexbjorling if you are interested to make a stab at a PR, you can see how other tools trigger the update:

https://github.com/bokeh/bokeh/search?q=trigger_ranges_update_event

Things should be very similar inside https://github.com/bokeh/bokeh/blob/branch-3.0/bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts

**Comment by alexbjorling** [comment]
Oh, for what I'm writing now the wheel pan is perfect. I have a waterfall 2d plot showing vibrational spectra over time. You pan the time axis, and this event causes data from the new time range to be read from the database and shown.

Put in PR #11634, hope it's OK!
