### ISSUE TITLE
Document Tool.icon in user guide

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11640]
Following  #11538, we should add information about the option to define a custom icon for tools to the user guide (in "Configuring plot tools", file `tools.rst`). A new section could be added between "Specifying tools" and "Setting the active tools". This new section could also be a good place to mention the `description` property.

**Comment by ABODFTW** [comment]
I will work on this, please let me know if there are any additional details, will send PR as soon as I get it done.

**Comment by tcmetzger** [comment]
@ABODFTW Thank you, looking forward to your PR! The relevant information should be in my description here in the issue, as well as in PR https://github.com/bokeh/bokeh/pull/11538 and the related issue https://github.com/bokeh/bokeh/issues/10914.

For general information on how to set up your system and update the docs, please see:

- https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html
- https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html
- https://docs.bokeh.org/en/latest/docs/dev_guide/pull_requests.html

Let me know if you have any questions!

**Comment by ABODFTW** [comment]
Did create a PR, but couldn't customize icons using an image URL, or a PIL object, not sure if this expected behavior, or I couldn't get it to work, there are more details in the PR, looking forward to your feedback.
