### ISSUE TITLE
Rename FuncTickFormatter

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11642]
Every other model in Bokeh that can process JS is a "CustomJS"-something. I'd like to propose renaming `FuncTickFormatter` (which is an awful name, my fault) to `CustomJSTickFormatter` for 3.0. which will bring its naming in line with everything else. 

cc @bokeh/dev

**Comment by mattpap** [comment]
I would also drop `Custom` as it seems redundant to me, but I suppose it would be too much trouble than it's worth at this point.

**Comment by bryevdv** [comment]
> I would also drop Custom as it seems redundant to me, but I suppose it would be too much trouble than it's worth at this point.

I think it is a little clunky but the  main reason not to change it is that `CustomJS` is unique and effectively searchable online while `JS` would definitely not be.
