### ISSUE TITLE
Test for `MultiChoice` widget

### ISSUE THREAD

**Issue by ingebert** [bokeh/bokeh#11653]
Related to #11605:
At the moment there is no proper test to make sure that new options added to `MultiChoice` widget are implemented consistently on both sides, Python and JS.

**Comment by tcmetzger** [comment]
This issue is a request to write tests. In addition to the discussion for #11605, helpful information to get started can be found in https://docs.bokeh.org/en/latest/docs/dev_guide/testing.html and https://docs.bokeh.org/en/latest/docs/dev_guide/writing_tests.html.
