### ISSUE TITLE
[BUG] Issue with line rendering when selecting indices

### ISSUE THREAD

**Issue by Lukas-Trisauskas** [bokeh/bokeh#11661]
#### Description of expected behavior and the observed behavior
This is my first time raising an issue on a public repo. So, if I make any mistakes, I apologise in advance. 

The selected area in the plot gets disconnected from the entire plot line, the start of unselected line and end of unselected line joins together.

> This happens, only when circle glyphs are added to the plot

**Before**
![before](https://user-images.githubusercontent.com/76224796/134269638-98a2fe02-d969-4637-a3af-128664e7096e.png)
**After**
![after](https://user-images.githubusercontent.com/76224796/134269633-9b263a04-9fd0-44a2-a0fa-a3aec460a244.jpg)

```
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource, BoxSelectTool, ResetTool
import numpy as np

output_file("example.html")

sample_data = np.random.rand(20)

source = ColumnDataSource(
    data=dict(x=np.arange(0, len(sample_data)), y=sample_data)
)
color_brewer = ["#31a354", "#addd8e"]

p = figure(width=1000, height=400, tools="box_select, reset", active_drag="box_select")
p.line(x='x', y='y', source=source, line_width=7, line_color=color_brewer[1])
p.circle(x='x', y='y', source=source, size=7, line_color=color_brewer[0], color=color_brewer[0])

show(p)
```
#### Screenshots or screencasts of the bug in action
![Animation5](https://user-images.githubusercontent.com/76224796/134268185-426cde6c-af92-43a8-837f-1c9f69ec6ab6.gif)
![example](https://user-images.githubusercontent.com/76224796/134268218-1d84b040-042a-4f4a-ad8e-afeba48c3aa2.jpg)

**Comment by bryevdv** [comment]
@Lukas-Trisauskas thank you or the very detailed bug report

cc @bokeh/dev This seems to be a slight regression, given the screen capture animations in previous PR https://github.com/bokeh/bokeh/pull/6491 which show the "unselected" line being broken up and not "crossing" the selected points.

**Comment by Lukas-Trisauskas** [comment]
@mattpap Thank you! Is the fix now included in the final package. I already upgraded bokeh to `2.4.0` and the problem still persists.

**Comment by mattpap** [comment]
You will have to wait for bokeh 2.4.1, which, I think, we will schedule soon.

**Comment by Lukas-Trisauskas** [comment]
> You will have to wait for bokeh 2.4.1, which, I think, we will schedule soon.

@mattpap That's great. Thank you!!
