### ISSUE TITLE
url prefix broken with non-bokeh prefixed urls

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#1166]
currently we try to auto-detect server url prefix in bokehjs by parsing the url, and looking for the string /bokeh/.  This is a bad idea, we should send this down to the client from the server

**Comment by bryevdv** [comment]
@hhuuggoo is this still the case?

**Comment by birdsarah** [comment]
@havocp i'm guessing this has gone away?

**Comment by havocp** [comment]
The auto-guessing I think is gone, but it might be worth a double check. However we do need to add back a command line option and/or setting for the prefix.

**Comment by bryevdv** [comment]
no longer relevant
