### ISSUE TITLE
[BUG] JavaScript error when setting LabelSet text to None

### ISSUE THREAD

**Issue by EfremBraun** [bokeh/bokeh#11673]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.4.0
Python 3.8.5
MacOs Catalina 10.15.7
Google Chrome 93.0.4577.82

#### Description of expected behavior and the observed behavior
This is essentially the same issue as was raised at https://github.com/plotly/dash/issues/671 (that post was what helped me debug this issue). When a None value is set as a `LabelSet`'s text, a JavaScript error is thrown that was tricky to troubleshoot. I think it might be good to throw an error for this on the Python side so users can know that this isn't allowed.

#### Complete, minimal, self-contained example code that reproduces the issue
Mainly copied from the example given in https://docs.bokeh.org/en/latest/docs/user_guide/annotations.html#labels, adding a button that changes the ColumnDataSource to include a None value:
```
from bokeh.models import ColumnDataSource, Label, LabelSet, Range1d, Button
from bokeh.plotting import figure, output_file, show
from bokeh.io import curdoc
from bokeh.layouts import column

output_file("label.html", title="label.py example")

source = ColumnDataSource(data=dict(height=[66, 71, 72, 68, 58, 62],
                                    weight=[165, 189, 220, 141, 260, 174],
                                    names=['Mark', 'Amir', 'Matt', 'Greg',
                                           'Owen', 'Juan']))

p = figure(title='Dist. of 10th Grade Students at Lee High',
           x_range=Range1d(140, 275))
p.scatter(x='weight', y='height', size=8, source=source)
p.xaxis[0].axis_label = 'Weight (lbs)'
p.yaxis[0].axis_label = 'Height (in)'

labels = LabelSet(x='weight', y='height', text='names',
              x_offset=5, y_offset=5, source=source, render_mode='canvas')

citation = Label(x=70, y=70, x_units='screen', y_units='screen',
                 text='Collected by Luke C. 2016-04-01', render_mode='css',
                 border_line_color='black', border_line_alpha=1.0,
                 background_fill_color='white', background_fill_alpha=1.0)

p.add_layout(labels)
p.add_layout(citation)

b = Button(label='Click Me')

def change_labels():
    source.data = dict(height=[66, 71, 72, 68, 58, 62],
                       weight=[165, 189, 220, 141, 260, 174],
                       names=['Mark', 'Amir', 'Matt', 'Greg',
                              'Owen', None])

b.on_click(change_labels)

curdoc().add_root(column([p, b]))
```

#### Stack traceback and/or browser JavaScript console output
```
[bokeh] setting log level to: 'debug'
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:163 [bokeh] embed: computed ws url: ws://localhost:5006/hi/ws
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:587 [bokeh] Creating websocket 0 to 'ws://localhost:5006/hi/ws' session 'TtLU4O6b9g7rkOxFqDvSDo2KSyrOwqu8J23VppdQI8aT'
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:587 [bokeh] Websocket connection 0 is now open
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:587 [bokeh] Pulling session for first time
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:165 [bokeh] Creating Document from JSON
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:165 [bokeh] Library versions: JS (2.4.0) / Python (2.4.0)
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:412 [bokeh] Toolbar: activating tool: PanTool(1022) for event type 'pan'
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:165 [bokeh] Adding root: Column(1046)
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:587 [bokeh] Created a new session from new pulled doc
15[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:519 [bokeh] PlotView initialized
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:496 [bokeh] layout computed in 21 ms
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:165 [bokeh] document idle at 52 ms
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:163 Bokeh items were rendered successfully
bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:285 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'split')
    at x.paint (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:285)
    at v._v_canvas_text (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:386)
    at v.paint (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:386)
    at v._render (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:234)
    at v.render (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:206)
    at O._paint_levels (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:519)
    at O._actual_paint (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:519)
    at O.paint (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:519)
    at O.repaint (bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:519)
    at bokeh.min.js?v=5759548377bd02b340ddead21a94c5d1:519
```

**Comment by bryevdv** [comment]
@EfremBraun I don't see where you've set `LabelSet.text` to None, above? I see you have set a new value for `source.data` that omits the `names` column that drives the `LabelSet`, but this is not really something we would be able to warn about, since there is a level of indirection between the data and the thing that uses the data.

**Comment by bryevdv** [comment]
cc @mattpap 

I am not sure how we could warn about this, CDS columns with list values are not validated by type, since they could be used to drive lots of different things.

**Comment by bryevdv** [comment]
The alternative in this specific case is simply to allow `LabelSet` to understand and handle None values (e.g. by skipping that entry in the column) but if we decide to do that this should be a changed to feature request.

**Comment by EfremBraun** [comment]
I'm not necessarily requesting the feature. Once I figured out what the problem was, I was able to take care of it for my own application simply. But it was tricky for me to figure out the cause, so I figured other users might be running into the issue as well.

**Comment by mattpap** [comment]
`null` is already handled by the data processing part of bokehjs, it's just painting that doesn't recognize this (as well as `NaN` for that matter in other properties. If it wasn't for `screen` units, I would recommend to just use `Text` glyph.

**Comment by bryevdv** [comment]
@EfremBraun I suggested adding the feature because I think that is something that could actually be done. The alternative is to close this with `noaction` because there is not really any way for us to do anything else on the Python side, because there is not a good way to surface the error condition a that level. At best, we could try to make a better error message in the JS console where the error is actually evident.

**Comment by EfremBraun** [comment]
I can confirm that #11674 fixed this issue.
