### ISSUE TITLE
[BUG] Parallel Plot example with output_backend="webgl" not working

### ISSUE THREAD

**Issue by xavArtley** [bokeh/bokeh#11679]
From bokeh 2.4.0 if output_backend="webgl" is set on figure options (https://github.com/bokeh/bokeh/blob/664fc492b8a7ac5839424b04f63a351c06f38187/examples/custom/parallel_plot/parallel_plot.py#L34), the selection glyphs does not render correctly cf image below:
![bug_webgl_backend](https://user-images.githubusercontent.com/18531147/134693512-81f592b0-3827-4484-8450-60f81ec9ca94.gif)

**Comment by bryevdv** [comment]
@xavArtley i just want to make sure I understand. The only thing that isn't working is that the rectangles for showing the selection regions are not displaying, is that correct?

**Comment by xavArtley** [comment]
Exactly

**Comment by bryevdv** [comment]
cc @ianthomas23

**Comment by ianthomas23** [comment]
I've confirmed this is a WebGL bug and I intend to supply a fix on Monday.
