### ISSUE TITLE
[DOCS] Guidance for downstream packagers

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11701]
Recent work made `pip install .` work from sdists, but also from bare source checkouts (`python setup.py`now automatically tries to build BokehJS by default if nodejs is installed). I think it is important to discourage downstream packagers from building their own BokehJS in the packages they release, and instead only use the published sdist as a basis for their packages (since it has a BokehJS included that is guaranteed to be identical to CDN)

cc @tcmetzger

**Comment by bryevdv** [comment]
@tcmetzger any thoughts on where to put this?

**Comment by tcmetzger** [comment]
I could see a warning somewhere in https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#build-and-install-locally. 

Would it also make sense to output a warning to the console whenever `setup.py` is run? Something like "Caution: the BokehJS built by this process is only for local development purposes. If you plan to release Bokeh as part of your own package, make sure to use the published sdist" etc.

**Comment by bryevdv** [comment]
Actually, this probably addresses like 3 or 4 people in the world. Going to close with `noaction` for now.
