### ISSUE TITLE
[BUG] Docs still mention @gen.coroutine

### ISSUE THREAD

**Issue by raflas** [bokeh/bokeh#11716]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.4, python 3.7.6, OS Big Sur 11.5, Chrome

#### Description of expected behavior and the observed behavior
Unlocked callbacks work with Bokeh 1.4.0 any version above the callbacks just execute after the "locking code" has finished.  The issue was replicated using the attached code from Bokeh 2.4.0 online manual, it work with Bokeh 1.4.0, I have not been able to make it work with any version above that.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

from functools import partial
import time

from concurrent.futures import ThreadPoolExecutor
from tornado import gen

from bokeh.document import without_document_lock
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure

source = ColumnDataSource(data=dict(x=[0], y=[0], color=["blue"]))

i = 0

doc = curdoc()

executor = ThreadPoolExecutor(max_workers=2)

def blocking_task(i):
    time.sleep(1)
    return i

# the unlocked callback uses this locked callback to safely update
@gen.coroutine
def locked_update(i):
    source.stream(dict(x=[source.data['x'][-1]+1], y=[i], color=["blue"]))

# this unlocked callback will not prevent other session callbacks from
# executing while it is running
@gen.coroutine
@without_document_lock
def unlocked_task():
    global i
    i += 1
    res = yield executor.submit(blocking_task, i)
    doc.add_next_tick_callback(partial(locked_update, i=res))

@gen.coroutine
def update():
    source.stream(dict(x=[source.data['x'][-1]+1], y=[i], color=["red"]))

p = figure(x_range=[0, 100], y_range=[0,20])
l = p.circle(x='x', y='y', color='color', source=source)

doc.add_periodic_callback(unlocked_task, 1000)
doc.add_periodic_callback(update, 200)
doc.add_root(p)

```

#### Screenshots or screencasts of the bug in action

*Note: Everyone interacting in the Bokeh project's codebases, issue trackers, and discussion forums is expected to follow the [Code of Conduct](https://github.com/bokeh/bokeh/blob/master/CODE_OF_CONDUCT.md).*

**Comment by bryevdv** [comment]
BTW generally speaking `@gen.coroutine` should not be needed or used anywhere. It was a mistake that that example in the docs was left with those in. Properly the example should be 
```
@without_document_lock
async def unlocked_task():
    import asyncio
    global i
    i += 1
    res = await asyncio.wrap_future(executor.submit(blocking_task, i), loop=None)
    doc.add_next_tick_callback(partial(locked_update, i=res))
```

Except `without_document_lock` is not smart enough to handle native coroutines apparently. This works though
```
async def unlocked_task():
    import asyncio
    global i
    i += 1
    res = await asyncio.wrap_future(executor.submit(blocking_task, i), loop=None)
    doc.add_next_tick_callback(partial(locked_update, i=res))
unlocked_task.nolock = True
```
