### ISSUE TITLE
Docs still reference FuncTickFormatter

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11723]
PR #11696 changes the name of `FuncTickFormatter` to `CustomJSTickFormatter`. However, `styling.rst` in the user guide still uses the old name `FuncTickFormatter` (currently on line 770, 773, and 1207). This should be changed accordingly. The corresponding example `styling_func_tick_formatter.py` has to be renamed as well (to `styling_custom_js_tick_formatter.py`)

**Comment by TheLaw1337** [comment]
#11725 please review
