### ISSUE TITLE
BokehJS example in docs is broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11744]
ref: https://docs.bokeh.org/en/latest/docs/user_guide/bokehjs.html#bokeh-plotting

Colors do not render:
<img width="645" alt="Screen Shot 2021-10-15 at 11 06 32" src="https://user-images.githubusercontent.com/1078448/137532898-606c81b0-64e1-40ce-8729-ac9b5b7b1992.png">

Seems like data is passed directly to `circle` but also put inside a CDS, probably should be using CDS for everything?

**Comment by g-parki** [comment]
Can't submit a PR at the moment. Here's what I found though...

https://github.com/bokeh/bokeh/blame/branch-3.0/sphinx/source/docs/user_guide/bokehjs.rst#L115

This line is expecting one `color` argument (in a variety of formats) and an optional `alpha` argument. Quick fix is wrapping the color args in an array:
```colors.push(plt.color([50+2*x, 30+2*y, 150]));```

> passed directly to circle but also put inside a CDS, probably should be using CDS for everything?

Agreed, and this is a good opportunity to demonstrate passing CDS fields to the glyph options. This works:
```
const circles = p.circle({ field: "x" }, { field: "y" }, {
    source: source,
    radius: radii,
    fill_color: { field: "colors" },
    fill_alpha: 0.6,
    line_color: null
});
```
[CodePen here](https://codepen.io/gparki/pen/mdMPQva)
