### ISSUE TITLE
Need examples of callbacks with BokehJS

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11745]
ref: https://discourse.bokeh.org/t/bokehjs-callback-on-select-get-start-and-end/8514

There is almost no information I am aware of (examples, docs) demonstrating how BokehJS users might set up callbacks on ranges, selections, etc as there is for Python. The Discourse question above is a prototypical example ask "update a div from a range event"

There should be examples under `bokehjs/examples` and also documentation support in the users guide: https://docs.bokeh.org/en/latest/docs/user_guide/bokehjs.html#

**Comment by jleppert** [comment]
+1 all the examples and references online are for python, this doesn't help those of us that just want to use pure bokehjs

**Comment by stas-sl** [comment]
Just faced the same issue. After a few hours of digging into the source code, I managed to kinda solve it, but it looks quite hacky. Would be nice if there existed a better way similar to python, but I didn't find it.

https://observablehq.com/d/ffddeccfd2462f80

```javascript
const { CustomJS } = Bokeh;
const { Button, Div, Slider } = Bokeh.Widgets;

const divWidget = new Div();
const btnWidget = new Button({ button_type: "success", 
                               js_event_callbacks: {'button_click': [
                                 new CustomJS({args: {divWidget: divWidget}, 
                                                code: "divWidget.text = `click: ${new Date()}`"})]}});
const sliderWidget = new Slider({ start: 0, end: 10, step:1, value: 0, 
                                    js_property_callbacks: {'change:value': [
                                    new CustomJS({args: {divWidget: divWidget},
                                                    code: "divWidget.text = `${this.value}`"})]}})
```
