### ISSUE TITLE
[FEATURE] Github merge instructions in docs

### ISSUE THREAD

**Issue by g-parki** [bokeh/bokeh#11754]
The first merge option is "Create a merge commit," which yields ugly results when the new folks (i.e. me) do their first merge. I now know we "squash and merge" most of the time. Maybe add some dev documentation about how this is managed?
cc @tcmetzger

![image](https://user-images.githubusercontent.com/61096711/137991646-e0031e59-7acc-4cbb-b7f7-b20d6aff9547.png)
![image](https://user-images.githubusercontent.com/61096711/137991684-abf2c468-e77d-47f8-97e2-b5dba68fac8d.png)

**Comment by bryevdv** [comment]
FYI the other option is just to turn off the other options:

<img width="591" alt="Screen Shot 2021-10-19 at 14 16 57" src="https://user-images.githubusercontent.com/1078448/137991865-4dccd76e-aa03-4315-8292-7086f6fea32d.png">

We have tried to rebase back/forward ports, but:

* there's not mechanism to prevent normal squash instead, and I have done at least twice, and
* GH UI annoyingly "remembers" which means the next normal PR might get accidentally rebased

So, maybe we should just only allow squash merges for everything.

**Comment by bryevdv** [comment]
@bokeh/dev any objections to just disabling merge and rebase commits? Presumably if we really need to do either we can just temporarily change the setting.

**Comment by p-himik** [comment]
@bryevdv What are the problems with using rebase for everything?

**Comment by bryevdv** [comment]
Bokeh is big with a complicated build and our individual commits are not hygenic enough to be bisectable when the need arises.

**Comment by jbednar** [comment]
Right. Rebase is rarely desirable, unless a developer already squashed their commits into a few meaningful chunks within the PR branch. That's rare; usually just the PR is the meaningful unit.

**Comment by bryevdv** [comment]
I've made the change, so I don't think any docs updates are needed at this point.

**Comment by p-himik** [comment]
Ah, GitHub doesn't have an option to squash and rebase, got it. GitLab does have it, so I was a bit confused.

**Comment by bryevdv** [comment]
Ah, squash and rebase would be nice for sure, not sure why it's not an option
