### ISSUE TITLE
[FEATURE] Show scale in map

### ISSUE THREAD

**Issue by sebhan2** [bokeh/bokeh#11755]
I am using the OSM tile provider in bokeh to plot a basemap. I think it would be great to have a way to show the scale of the map in meters or kilometers depending on the zoom level.

Just to clarify, the axis labels can remain in WGS84-pseudo-mercator but I want to have a scale or some sort of ruler to give a better sense of the distances in the plot.

Here is an example image from the OSM website where I have marked the scale in the bottom left corner.

![ebe74fa72f7f3145bdfcbb1a5a1caeb426a2b245](https://user-images.githubusercontent.com/26087071/138156148-4bcf2189-0506-44ef-8f2f-c18cdb0e0239.jpeg)

**Comment by gmerritt123** [comment]
I'd like to help with this and I think I have the required logic/bokeh coding skills to do it (see https://discourse.bokeh.org/t/is-it-possible-to-show-the-scale-in-an-osm-tile-plot-using-bokeh/8535/5?u=gmerritt123 ), but am far from a "real" developer (I have never contributed to a legit open source project before and my git skills/understanding are very lacking). Frankly I am really intimidated by the whole process of making pull requests and merging them etc. I am very willing to learn though, so if someone's willing to hold my hand through it I'd be happy to take this on.

**Comment by gmerritt123** [comment]
Alright I made it somewhere around these steps here:

![image](https://user-images.githubusercontent.com/58000181/138375760-45198907-3845-4540-a0be-1f9c6c5f271e.png)

I *think* I created a branch and pushed it to my fork:

![image](https://user-images.githubusercontent.com/58000181/138376083-e6105a01-f15b-41fc-a72b-ed87497bbe00.png)

and...

![image](https://user-images.githubusercontent.com/58000181/138376180-5d72997b-c648-4754-ac36-c9b86c156dd7.png)

So... if I did that correctly, how do I make the initial commit as suggested?

... I tried some things...

![image](https://user-images.githubusercontent.com/58000181/138376351-d3d150b3-49c2-48da-95eb-7a268639e180.png)

These two steps are very fuzzy/ill defined to me... please advise.... thank you...

**Comment by carve11** [comment]
@gmerritt123 have you made any progress on this?

**Comment by gmerritt123** [comment]
No I have not. 

One additional hurdle that will matter big time for map scales at least is the nature of the web mercator projection --> it is only consistent "1 unit = 1 meter" directly at the equator and gets distorted as one moves north/south. My solution to this was to determine an appropriate local coordinate projection/grid (e.g. NAD 83 utm zone 17N for my neck of the woods), and to use [Proj4JS](https://github.com/proj4js/proj4js) to reproject the web mercator projccted points to their respective local coordinate system prior to calculating any distances.

So if you do implement some python-side workaround setup a la my sketch-out here --> https://github.com/bokeh/bokeh/issues/11755#issuecomment-949591507 please keep the above issue in mind: it was a serious late project crisis when I realized it was an issue and I don't wish that stress on anyone else :-D

**Comment by carve11** [comment]
@gmerritt123 Thanks for the comment. I have tried to make a custom extension and tried to take into account the projection. However, I did make the scale a bit more universal and not only one for maps. You can have a look at https://github.com/carve11/bokeh/tree/main/scalebar - my first attempt at TypeScript so the code it probably pretty ugly  - and I have no experience coding extensions.
