### ISSUE TITLE
session.store_document() fails in table_server example

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1176]
Currently this works:
```
def select_columns(obj, attr, old, fields):
    table.columns = [ column for column in columns if column.field in fields ]
    session.store_objects(table)
```
If you replace `store_objects(table)` with `store_document(document)` it fails with:
```
2014-09-09 17:46:18,600:ERROR:root:model not found for {u'type': u'TableColumn', u'id': u'3d836afe-4445-4fac-81c1-973634f86139'}
```
on the server-side and `table.columns` contains `null` values on the JS-side.

**Comment by birdsarah** [comment]
I believe this is now fixed. data_tables_server.py example now uses self.session.store_document successfully.

https://github.com/bokeh/bokeh/blob/master/examples/glyphs/data_tables_server.py#L136
