### ISSUE TITLE
[FEATURE] Resolution scaling

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [bokeh/bokeh#11769]
**Is your feature request related to a problem? Please describe.**
I have a plot where I've tuned the sizes of various fonts and glyphs to my liking. Then, my colleague asks for a higher resolution image. Because everything in Bokeh is handled in pixels, I have to delve into Bokeh's API, find everything that's measured in pixels, and manually scale each one of them. I can't just simply ask for a larger figure.

Also already requested [here](https://github.com/bokeh/bokeh/issues/8807)

**Describe the solution you'd like**
Be able to ask for a larger figure. A nice solution would be able to measure everything in bokeh in relative units, and then specify the scale at the end. But I doubt you're interested in that refactoring? It seems like too much of an API change.

The solution I wrote for myself is below, the main entrypoint being `resize(figure, ratio_to_enlarge_or_shrink)`:

```
def resize_font(obj, fontattr, ratio):
    font = obj.__getattribute__(fontattr)
    font_size, font_unit = font[:-2], font[-2:]
    obj.__setattr__(fontattr, str(math.floor(int(font_size)*ratio)) + font_unit)

def resize_int(obj, intattr, ratio):
    val = obj.__getattribute__(intattr)
    _BetterCDF(data, ax, data_len=data_len, reverse=reverse)
    obj.__setattr__(intattr, math.floor(val*ratio))

def resize(fig, ratio, legend=True):
    resize_int(fig, 'width', ratio)
    resize_int(fig, 'height', ratio)
    resize_font(fig.title, 'text_font_size', ratio)
    for axis in fig.xaxis, fig.yaxis:
        resize_font(axis, 'axis_label_text_font_size', ratio)
        resize_font(axis, 'major_label_text_font_size', ratio)
        resize_int(axis, 'axis_label_standoff', ratio)
        resize_int(axis, 'axis_line_width', ratio)
        resize_int(axis, 'major_tick_line_width', ratio)
        resize_int(axis, 'major_tick_in', ratio)
        resize_int(axis, 'major_tick_out', ratio)
        resize_int(axis, 'major_label_standoff', ratio)
        resize_int(axis, 'minor_tick_line_width', ratio)
        resize_int(axis, 'minor_tick_in', ratio)
        resize_int(axis, 'minor_tick_out', ratio)
    if legend:
        resize_font(fig.legend, 'label_text_font_size', ratio)
        resize_int(fig.legend, 'title_standoff', ratio)
        resize_int(fig.legend, 'border_line_width', ratio)
        resize_int(fig.legend, 'label_standoff', ratio)
        resize_int(fig.legend, 'label_width', ratio)
        resize_int(fig.legend, 'label_height', ratio)
        resize_int(fig.legend, 'glyph_width', ratio)
        resize_int(fig.legend, 'glyph_height', ratio)
        resize_int(fig.legend, 'padding', ratio)
        resize_int(fig.legend, 'spacing', ratio)
        resize_int(fig.legend, 'margin', ratio)
```
(the calls to `__getattribute__` and `__setattr__` can be replaced with explicit `obj.<attr>`, they were just to save me typing)

I'm happy to contribute something like this if it's wanted. I don't know how to test it - I can check that every item I thought of has been modified, which is a very basic test, but I don't know how to test that the image before and after resizing are identical, except for the scale and small rounding differences. This list of properties would also need to be exhaustive, so future developers would need to commit to adding to this list as plot elements measured in fixed width units (e.g. pixels) are added.

**Comment by bryevdv** [comment]
I've re-opened #8807 which has (hopefully) a simpler approach involving providing a single scale factor to the webdriver. I'll close this for now as a duplicate (since there is more discussion in the other issue).
