### ISSUE TITLE
[FEATURE] Propagate Name attribute to js for all Models

### ISSUE THREAD

**Issue by hyamanieu** [bokeh/bokeh#11782]
**Problem statement**
`document.getElementsByName` is a fairly powerful and simple way to access bokehjs models on client side in a customjs callback. However it is propagated only for a few widgets (`TextInput`) and it's lacking for many other ones (all buttons, checkboxes, etc.).

**Ideal solution**
Propagate the Name attribute to the bokehjs models of all models.

**Comment by bryevdv** [comment]
@hyamanieu You will need to explain in more detail. The `document.getElementsByName` returns DOM elements, but the `name` property is a property of Bokeh models, which are JavaScript objects and not DOM elements (they have have one or multiple DOM elements associated with a view of the model, but do not have to, in general). Please share a *complete script* that demonstrates what you are talking about with `TextInput`

**Comment by bryevdv** [comment]
Well, I guess you are talking about this

https://github.com/bokeh/bokeh/blob/805e2f7673e8ba40c884e9993481108fa76c02ae/bokehjs/src/lib/models/widgets/text_like_input.ts#L33

@mattpap any idea when/why this went in? It appears to be from pre-Typescript days, that's as far back as I tried to dig. Not really sure how much I like this, or at least associating with the generic `name` property, which does not have this association anywhere else. I might be convinced a dedicated `dom_name` , that only exists on widgets where it makes sense to, could be OK.

**Comment by hyamanieu** [comment]
@bryevdv  thanks for your explanation, and here below an example.

In a notebook:
```python
#[1]
import bokeh as bk
from bokeh.plotting import show
from bokeh.io import output_notebook
output_notebook()
#[2]
callback = bk.models.callbacks.CustomJS(code="console.log(document.getElementsByName(cb_obj.name))")

txt_input = bk.models.widgets.TextInput(name='foo',value='here')
btn = bk.models.widgets.Button(name='bar',label='mybutton')

txt_input.js_on_change('value', callback)
btn.js_on_click(callback)

layout = bk.layouts.Column(txt_input,btn)
#[3]
show(layout)
```

changing the value of the text input will return you a list with one element: the textinput. Clicking the button returns you an empty list.

A typical situation I require these elements is to use the `.focus()` method. It doesn't work directly on the bokeh model (`cb_obj`) itself.
As I said, it's not only about buttons: anything that can be focussed would be nice, and I think of all widgets (checkboxes, dropdown, etc.). So far only Text input and similar ones work.

The various javascript concepts are still fuzzy to me (which is why I use Bokeh ;) ), please be patient if I am a bit off with my descriptions :) .

**Comment by mattpap** [comment]
> any idea when/why this went in?

No idea. It only applies to `TextInput` and `TextareaInput`, so I'm guessing it was a local idea that fortunately wasn't spread elsewhere. I would remove this.

**Comment by mattpap** [comment]
If one wants to get an element associated with a model's view, then there are APIs for this, e.g.:
```ts
// Let's assume we are in JS console
const [view] = Object.values(Bokeh.index)     // and there's only a single root
const model = view.model.select_one("foo")    // and we are searching for "foo" named model
view.owner.get_one(model).el
```
