### ISSUE TITLE
Update issue template to use new GH forms

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11791]
GitHub has rolled out a new form of issue form/template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

We would like to use this new feature to update our current templates for bug reports and feature requests (located in `.github/ISSUE_TEMPLATE/`). The forms should ask for the same information that we are currently asking for in our existing templates. More information on that is available in https://docs.bokeh.org/en/latest/docs/dev_guide/pull_requests.html and https://docs.bokeh.org/en/latest/docs/dev_guide/creating_issues.html - both of those documentation pages also need to be updated once we use the new issue form feature.

A good example of the new form in action is the bug report form in the Sphinx repo: https://github.com/sphinx-doc/sphinx/issues/new?assignees=&labels=bug&template=bug-report.yml

cc @bryevdv

**Comment by bryevdv** [comment]
FWIW I'm not sure this is a `good first issue` — it's important enough (to me at least, I have been waiting for this for ~10 years) that I don't think we should put off implementing it in case someone randomly decides to work on it.
