### ISSUE TITLE
`BOKEH_DEV=true` assumes file resources when using the server

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11794]
Running:
```
BOKEH_DEV=true bokeh serve sliders.py
```
results in resource request like

> http://localhost:5006/Users/bryan/work/bokeh/bokehjs/build/js/bokeh.js

which naturally fail 404. This happens with 2.4 and 3.0

cc @mattpap

**Comment by mattpap** [comment]
It's broken, though I'm not sure if it ever worked. I always specify the type of resources explicitly for the given job, so my command line always looks like this:
```
BOKEH_DEV=true BOKEH_RESOURCES=server ...
```

**Comment by bryevdv** [comment]
In fact this is already documented:

https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html?highlight=bokeh_dev#bokeh-dev

I have a vague recollection that there is some reason this can't be improved. I'd be fine closing, given the documentation.

**Comment by mattpap** [comment]
Let's keep it for now, as I would actually clean up and simplify the dev setup.
