### ISSUE TITLE
[BUG] HoverTool with mode=vline can make glyphs disappear

### ISSUE THREAD

**Issue by ian-r-rose** [bokeh/bokeh#11804]
Using a HoverTool with `mode="vline"` can cause some unrelated glyphs to disappear from the chart.

As far as I can tell, this is a regression that was introduced in 2.4.0 (everything works fine in 2.3.3).

The following creates a line *and* a varea with a hover tool for the line:
```python
import numpy as np

from bokeh.io import show
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure

x = np.linspace(0, 4. *np.pi, 100)
y = np.sin(x) + 2

source = ColumnDataSource({"x": x, "y": y})

p = figure(tools="")
p.line(x='x', y='y', source=source)
p.varea(x='x', y1=0, alpha=0.5, y2='y', source=source)

p.add_tools(HoverTool(mode="vline")) # mode="mouse" succeeds

show(p)
```
When I hover over the chart, the *varea* glyph disappears. The line and hover seem to behave normally.

#### Stack traceback and/or browser JavaScript console output
I didn't see any useful tracebacks or JS console output

#### Screenshots or screencasts of the bug in actio
![bokehbug](https://user-images.githubusercontent.com/5728311/141869609-a5bc479c-b608-4fd4-b0a5-4fb9ba0fa9d7.gif)

**Comment by bryevdv** [comment]
This is working on both `branch-3.0` and `branch-2.4` so it was evidently accidentally fixed and also already backported, so I will go ahead and close this. A new 2.4.2 release will be out within the next week.

**Comment by bryevdv** [comment]
@ian-r-rose if you need an immediate WAR then the solution would be to explicitly set `renderers` for the hover tool and exclude the varea glyph

**Comment by ian-r-rose** [comment]
Thanks for the quick response @bryevdv .

> This is working on both `branch-3.0` and `branch-2.4` so it was evidently accidentally fixed and also already backported, so I will go ahead and close this. A new 2.4.2 release will be out within the next week.

That's great to hear, thanks.

> @ian-r-rose if you need an immediate WAR then the solution would be to explicitly set `renderers` for the hover tool and exclude the varea glyph

Unfortunately, updating the above to exclude the varea still shows the same problem (unless I've made a mistake):

```python
import numpy as np

from bokeh.io import show
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure

x = np.linspace(0, 4. *np.pi, 100)
y = np.sin(x) + 2

source = ColumnDataSource({"x": x, "y": y})

p = figure(tools="")
line = p.line(x='x', y='y', source=source)
p.varea(x='x', y1=0, alpha=0.5, y2='y', source=source)

p.add_tools(HoverTool(mode="vline", renderers=[line]))

show(p)
```

**Comment by ian-r-rose** [comment]
I can confirm that I no longer see the issue in the 3.0.0.dev1 release published to PyPI.

I suppose timing-wise https://github.com/bokeh/bokeh/pull/11764 seems like a good candidate for the accidental fix?
