### ISSUE TITLE
Remove unnecessary whitespace from rendered templates

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#11811]
Currently it both looks unprofessionally and is tedious to work with, e.g. for `color_scatter.py` I get:
![image](https://user-images.githubusercontent.com/27475/142170642-3e395a80-f0fa-42dc-b4d4-c53c4e235b51.png)
At minimum all gaps need to be removed. Additionally indentation should be consistent. This can be partially achieved by enabling automatic whitespace control in jinja and removing manual from our templates. However, that doesn't fully resolve the problem. On the other hand we may need to actually use manual control, but use it consistently and rigorously everywhere. I'm not sure which is better, as I had some, but not full, success with both.

**Comment by bryevdv** [comment]
I do think think is a case where the simplest solution that goes the farthest with the least effort is the best. If Jinja automation can make a 90% improvement, i.e. especially removing the large vertical gaps, that should be settled for. It is absolutely not worth putting in tons of effort (or worse, burdening an entire time with perpetual manual effort) to chase perfection here.

**Comment by g-parki** [comment]
Jinja has a fairly standard operation for trimming around blocks, which can be enabled by adding `trim_blocks=True, lstrip_blocks=True` to `Environment()` here:
https://github.com/bokeh/bokeh/blob/7b85b044c78b6772242e5fcae6224409d1b3b523/bokeh/core/templates.py#L81

As already noted, this doesn't fix the hard-coded indentation and line breaks, of which there's a lot (a key source being comments on the top of the files, which can be fixed on an individual basis). I'll play around with this some more.
![image](https://user-images.githubusercontent.com/61096711/142559725-84b20dc7-0397-4b45-9fcd-37e17687ecb3.png)
