### ISSUE TITLE
[FEATURE] Add a way to switch off `output_notebook` and `output_file`

### ISSUE THREAD

**Issue by hamogu** [bokeh/bokeh#11827]
### Problem description

After setting `output_notebook` or `output_file` there seems to be no way to unset them again. I may run a notebook and want to show the top dozen plots in the notebook, but then save the later ones only into a file. There seems to be no documented way of doing that.

### Feature description

I suggest to allow `output_file(None)` to switch off file output and `output_notebook(False)` and/or `output_notebook(None)` (I like "False", but one could argue that "None" is good to have consistency with what I suggested for `output_file`) to switch off the notebook output.

### Potential alternatives

After looking through the code, I found that 
```
from bokeh.io import state
state.curstate()._file = None
```
works, but that requires (a) reading the code and (b) accessing obscure internal objects.

**Comment by mattpap** [comment]
There is `curstate().reset()` that cleans up all state. However, it seems to me that all those modes should be mutually exclusive, so if `output_file()` was called after `output_notebook()`, it should reset notebook state.

**Comment by hamogu** [comment]
`reset_output` is documented very close to the location that I looked at: https://docs.bokeh.org/en/latest/docs/reference/io.html#bokeh-io-output
I must have just missed it; now that I know how it's called and where I should have looked, I think what you have in the docs right now is good enough. If I just can't read, it's my own fault, so I'm closing this. If other people run into the same thing again, we can always come back and see if it needs a more prominent explanation (e.g. in https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html) but as long as I'm the only one, it's probably safe to assume that this is a lesser needed feature and having it in the API docs should be sufficient.
