### ISSUE TITLE
[BUG] PanTool can't be deactivated in grid plot

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#11839]
### Software versions

Python version      :  3.9.7 | packaged by conda-forge | (default, Sep 23 2021, 07:28:37) 
IPython version     :  7.28.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /opt/conda/envs/development/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v15.14.0
npm version         :  7.7.6
Operating system    :  Linux-5.10.0-8-amd64-x86_64-with-glibc2.31

### Browser name and version

Chrome, Version 96.0.4664.45

### Expected behavior

I expect to disable tools like the PanTool for grids in a similar way like for single figures [official documentation](https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#setting-the-active-tools).

### Observed behavior

It is not possuble to deactivate a tool in a grid plot. The toolbar of the grid plot is of type `ProxyToolbar` with two toolbars of type `Toolbar`.

There is a question on [StackOverflow](https://stackoverflow.com/questions/70097251/deactivate-specific-hover-tool-in-bokeh-html-figures) about this behavior.

### Example code

```Python
from bokeh.plotting import ColumnDataSource, figure, show, output_notebook
from bokeh.layouts import gridplot

source = ColumnDataSource(data=dict(x=[1, 2, 3],y=[2, 5, 3],))                         

def get_figure():
    p = figure(width=400, height=200,tools='pan')
    p.circle('x', 'y', size=20, source=source)
    p.toolbar.active_drag = None
    return p


grid = gridplot([get_figure() for i in range(2)], ncols=1)
grid.children[0].toolbar.toolbars[0].active_drag = None
show(grid)


show(get_figure())
```

### Screenshots

This is the output of an single figure, working like explained in the documentation. The tool is deactivated, like expected.
![Singel](https://user-images.githubusercontent.com/68053396/143571883-e26acc5f-9806-48d4-b6cb-17b0be14b69e.PNG)

This is the output for a grid. The tool is not deactivated.
![Grid](https://user-images.githubusercontent.com/68053396/143571875-835fce89-1719-4528-a23c-e9bc9a82423f.PNG)

**Comment by mosc9575** [comment]
Looks like this was a topic before in [#10107](https://github.com/bokeh/bokeh/issues/10107) with a following PR [#10095](https://github.com/bokeh/bokeh/pull/10095).

Therefor this might be a duplicate.

**Comment by tcmetzger** [comment]
I was able to reproduce this with branch-3.0 (Ubuntu 20.04. Firefox and Chrome). 

I only had to adjust the example slightly to avoid the error message from https://github.com/bokeh/bokeh/pull/11482:

```
from bokeh.plotting import ColumnDataSource, figure, show
from bokeh.layouts import gridplot

source = ColumnDataSource(data=dict(x=[1, 2, 3],y=[2, 5, 3],))

p1 = figure(width=400, height=200,tools='pan')
p1.circle('x', 'y', size=20, source=source)
p1.toolbar.active_drag = None

p2 = figure(width=400, height=200,tools='pan')
p2.circle('x', 'y', size=10, source=source)
p2.toolbar.active_drag = None

grid = gridplot([p1, p2], ncols=1)
grid.children[0].toolbar.toolbars[0].active_drag = None
show(grid)
```
