### ISSUE TITLE
[BUG] Zoom-in failing with the `xzoom_in` tool

### ISSUE THREAD

**Issue by florentbr** [bokeh/bokeh#11832]
### Software versions

Python version      :  3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
IPython version     :  7.28.0
Tornado version     :  6.1
Bokeh version       :  2.4.0
BokehJS static path :  C:\Users\florent\AppData\Local\Programs\Python\Python39\lib\site-packages\bokeh\server\static
node.js version     :  v14.2.0
npm version         :  6.14.4

### Browser name and version

Firefox 93

### Expected behavior

With the `xzoom_in` tool, the plot is expected to zoom in when the "Zoom in (x-axis)" button is clicked.

### Observed behavior

Pressing the "Zoom in (x-axis)" button has no effect whith the `xzoom_in` option. It works as expected with the `zoom_in` tool.

### Example code

```Python
from bokeh.plotting import figure
from bokeh.models import LinearAxis, Range1d

s1 = figure(width=600, height=300, tools='xzoom_in,zoom_out,box_zoom,reset')

s1.y_range.start, s1.y_range.end = s1.y_range.bounds = (0, 20)

s1.line([0, 50, 100], [13, 12, 11])

show(s1)
```

**Comment by bryevdv** [comment]
This has to do with the interaction with the bounds. Here is a simpler MRE:
```python
from bokeh.plotting import figure, show

s1 = figure(width=600, height=300, tools='xzoom_in,zoom_out,box_zoom,reset')
s1.y_range.start, s1.y_range.end = (0, 20)
s1.line([0, 50, 100], [13, 12, 11])

s1.y_range.bounds = (1, 21)   # WORKS

# s1.y_range.bounds = (0, 20) # DOES NOT WORK

show(s1)
```

I expect this may be a floating point precision issue, e.g. when the y-bounds are exactly tight to the starting range, the x-zoom does something that violates the bounds constraint. 

@florentbr for now your WAR is to slightly enlarge the bounds (or remove bounds entirely)

**Comment by florentbr** [comment]
@bryevdv,  thanks for the workaround.
There's probably more than a floating point since the bounds should only apply to the Zoom-out an not the Zoom-in.
I also noticed that the Zoom-out never zoom back to the full view.
Do you know where the code related to this feature is located ?

**Comment by bryevdv** [comment]
>  bounds should only apply to the Zoom-out an not the Zoom-in.

The thing about floating point precision errors is they often turn up where you would not expect them. Range management is some of the most complex, complicated, messy code in all of Bokeh. Ranges updates always have to consider both ranges together, to support features like data following, auto-ranging, and aspect ratio fixing. Any floating point calculation anywhere along the way that results in a computed `y.end ~= 20.000......0001` will cancel the operation when bounds are set. 

> Do you know where the code related to this feature is located ?

https://github.com/bokeh/bokeh/blob/branch-3.0/bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
https://github.com/bokeh/bokeh/blob/branch-3.0/bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts

**Comment by florentbr** [comment]
I tracked down the issue thanks to your information.

It cancels the zoom-in if the current range x or y is superior or equal to the bounds (min, max) :

https://github.com/bokeh/bokeh/blob/288de1348ffedabdf050e3254c500b886f08db41/bokehjs/src/lib/models/plots/range_manager.ts#L246-L247

Well, this means that it will never resize the x axis if the y axis is equal to the bound.

To fix it, I replaced `>=` by `>` to test if the range is off bound:
https://github.com/florentbr/bokeh/commit/5433193a2431b8a048e14232084f903ac993a8c0
