### ISSUE TITLE
[BUG] If CSV contains "--", any data is not plotted

### ISSUE THREAD

**Issue by yuji38kwmt** [bokeh/bokeh#11855]
### Software versions

Python version      :  3.9.7 (default, Oct  8 2021, 12:01:40) 
IPython version     :  7.28.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /home/vagrant/.pyenv/versions/3.9.7/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v16.13.0
npm version         :  8.1.0
Operating system    :  Linux-4.18.0-16-generic-x86_64-with-glibc2.27

### Browser name and version

Firefox 94.0(64-bit)

### Expected behavior

I expect that "Alice" and "Chris" are plotted.

### Observed behavior

"Alice" and "Chris" are not plotted.

### Example code

```Python
import pandas
from bokeh.plotting import ColumnDataSource, figure
import numpy
import bokeh


input_csv = "input.csv"
output_html = "output.html"

x_column = "x"
y_column = "y"

df = pandas.read_csv(input_csv)

fig = figure(
    x_axis_label=x_column,
    y_axis_label=y_column,
)

source = ColumnDataSource(data=df)

fig.circle(x=x_column, y=y_column, source=source)
fig.text(
    x=x_column,
    y=y_column,
    source=source,
    text="name",
)

bokeh.plotting.reset_output()
bokeh.plotting.output_file(output_html, title=output_html)
bokeh.plotting.save(bokeh.layouts.column([fig]))
```

input.csv

```
name,x,y
Alice,120.1,1.1
Bob,130.1,--
Chris,140.1,3.3
```

### Stack traceback or browser console output

Browser Console Output

```
[bokeh] setting log level to: 'info' bokeh-2.4.2.min.js:184:1360
[bokeh] could not set initial ranges 3 bokeh-2.4.2.min.js:521:2168
[bokeh] document idle at 60 ms bokeh-2.4.2.min.js:165:1339
```

### Screenshots

![image](https://user-images.githubusercontent.com/6350027/144529063-8d470251-d6fd-4806-b4eb-89f111feeb86.png)

# Custom Information

"Alice" and "Bob" are plotted in the following cases.

### (A) y colum type is int 

input.csv
```
name,x,y
Alice,120.1,1
Bob,130.1,--
Chris,140.1,3
```

### (B) Convert y column type to float64

```
df = pandas.read_csv(input_csv)
df.replace({"--": numpy.nan}, inplace=True)
df[y_column] = df[y_column].astype("float64")
```

### (C) Create dataframe from dict

```
df = pandas.DataFrame({"name": ["Alice", "Bob", "Chris"], "x": [120.1, 130.1, 140.1], "y": [1.1, "--", 3.3]})
```

**Comment by bryevdv** [comment]
@yuji38kwmt The content in the file causes Pandas to read in the `y` column as a string series:
```
In [2]: df
Out[2]:
    name      x    y
0  Alice  120.1  1.1
1    Bob  130.1   --
2  Chris  140.1  3.3

In [3]: df.y
Out[3]:
0    1.1
1     --
2    3.3
Name: y, dtype: object
```

That is a problem for you to handle with whatever data cleaning or sanitization is appropriate for your use case.

**Comment by yuji38kwmt** [comment]
Thanks

**Comment by philippjfr** [comment]
@yuji38kwmt The issue tracker is for issues with the bokeh library. That said, if I load:

```
name,x,y
Alice,120.1,1.1
Bob,130.1,--
Chris,140.1,3.3
```

from CSV I get the exact same result as in your last screenshot. It's only this that does not work for me:

```
name,x,y
Alice,120.1
Bob,130.1,--
Chris,140.1
```

because it is missing the y values. Note I would recommend loading your csv with `pandas.read_csv(input_csv, na_values='--')`.

**Comment by bryevdv** [comment]
> Why does bokeh behave this way.

When you initialize from the dict, it is pandas that is behaving differently, not bokeh. You can answer these questions by actually examining the data frame and column types. Bokeh just plots the data it is given, in all cases. 

Please take further usage questions to support forums, e.g the community discourse instance.
