### ISSUE TITLE
Examples README.md files needs checking and updating

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#11868]
Some of the `README.md` files in the `examples` directory and its subdirectories are out of date, so need checking and updating.

As an example, `plotting/README.md` contains
```
There are three subdirectories:

* `file` examples that output to static HTML files

* `notebook` examples that display inline in [Jupyter](http://jupyter.org) notebooks

* `server` examples that send output to a Bokeh server, using the python client library for the server
```
but there are no `notebook` and `server` directories.

**Comment by girolamodaschio** [comment]
Good morning :)

Since I'm exploring Bokeh as a tool, I'm passionate about what are you doing here and generally, I'm in love with open source projects,

I'd like to contribute to the resolution of this issue in my spare time!

**Comment by girolamodaschio** [comment]
I'm in the hope that the commits are found useful,
Happy to receive feedback and edit what I've done.
Ciao!
