### ISSUE TITLE
Ability to share BoxZoom between charts with GridPlot

### ISSUE THREAD

**Issue by ItamarShDev** [bokeh/bokeh#11862]
### Problem description

when creating charts with same x_range and columndatasource, shared BoxZoom wont work on all charts

### Feature description

Ability to share BoxZoom between charts with GridPlot

### Potential alternatives

using specific box zoom on each chart with shared range

**Comment by bryevdv** [comment]
> shared BoxZoom wont work on all charts

What dots this mean? What duff you try that didn't work the way you expected? Provide complete code?

**Comment by bryevdv** [comment]
I'm going to go ahead and close this. @ItamarShDev we can consider re-opening if you can provide a much more detailed description of what you want to propose.

**Comment by ItamarShDev** [comment]
Let's say i take the code example from [Linking docs](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/linking.html#linked-panning):
```python
from bokeh.io import output_file, show
from bokeh.layouts import gridplot
from bokeh.plotting import figure

x = list(range(11))
y0 = x
y1 = [10-xx for xx in x]
y2 = [abs(xx-5) for xx in x]

# create a new plot
s1 = figure(width=250, height=250, title=None)
s1.circle(x, y0, size=10, color="navy", alpha=0.5)

# create a new plot and share both ranges
s2 = figure(width=250, height=250, x_range=s1.x_range, y_range=s1.y_range, title=None)
s2.triangle(x, y1, size=10, color="firebrick", alpha=0.5)

# create a new plot and share only one range
s3 = figure(width=250, height=250, x_range=s1.x_range, title=None)
s3.square(x, y2, size=10, color="olive", alpha=0.5)

p = gridplot([[s1, s2, s3]])
# show the results
show(p)
```


Now i want to add X axis BoxZoomTool.

If i try: 

```python
from bokeh.io import output_file, show
from bokeh.layouts import gridplot
from bokeh.plotting import figure
from bokeh.models import BoxZoomTool

xbox_zoom = BoxZoomTool(dimensions='width') # < ---- INIT Tool
x = list(range(11))
y0 = x
y1 = [10-xx for xx in x]
y2 = [abs(xx-5) for xx in x]

# create a new plot
s1 = figure(width=250, height=250, title=None)
s1.add_tools(xbox_zoom) # < ---- ADD Tool to chart
s1.circle(x, y0, size=10, color="navy", alpha=0.5)

# create a new plot and share both ranges
s2 = figure(width=250, height=250, x_range=s1.x_range, y_range=s1.y_range, title=None)
s2.add_tools(xbox_zoom) # < ---- ADD Tool to chart

s2.triangle(x, y1, size=10, color="firebrick", alpha=0.5)

# create a new plot and share only one range
s3 = figure(width=250, height=250, x_range=s1.x_range, title=None)
s3.add_tools(xbox_zoom) # < ---- ADD Tool to chart
s3.square(x, y2, size=10, color="olive", alpha=0.5)

p = gridplot([[s1, s2, s3]])
# show the results
show(p)
```
I will get the following behavior, where the box zoom only works on the first chart:
[video of the behavior](https://user-images.githubusercontent.com/953371/146668405-2b3ca4fe-d92d-49a3-8946-eeb5780e83e7.mp4)




What can i do to make gridplot use BoxZoom on a single axis correctly?

**Comment by mattpap** [comment]
The default `BoxZoomTool` interferes with the new one when used in a grid (proxy) toolbar. Remove the default tool and the new one will work as expected. Proxy toolbar is a very naive and fragile piece of bokehjs, and will be redesigned for 3.0.
