### ISSUE TITLE
Remove katex example, test and docs

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#11870]
Now that we have LaTeX labels, etc, working, we no longer need to demonstrate the use of katex. There is an example, a test and some mentions in the docs about it.

I tried to remove it as part of PR #11869 when I converted the katex Bessel function example, but I ended up with a number of sphinx errors that I didn't understand so I am hoping that @tcmetzger might want to deal with this.

**Comment by tcmetzger** [comment]
I have started #11879 to address this. Demonstrating how to build extension examples per se might still be useful, just like testing this functionality as part of the examples tests. Therefore, I would not remove these examples but instead add a note to the respective Readme files and docstrings, linking to the math text section in the user guide.
However, if we decide that we can safely remove the two examples, I'll be happy to make a new PR to delete them!
cc @bryevdv @mattpap
