### ISSUE TITLE
ImageURL blinks when the datasource updated

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#11877]
### Software versions

Python version      :  3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.29.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  c:\mambaforge\lib\site-packages\bokeh\server\static
node.js version     :  v16.12.0
npm version         :  8.1.0
Operating system    :  Windows-10-10.0.19041-SP0

### Browser name and version

Chrome, Version 96.0.4664.93 (Official Build) (64-bit)

### Expected behavior

I use ImageURL to display animation by updating the datasource. I worked well with version 2.0.1, but after update the version to 2.4.2, the image blinks.

I checked every versions, and found that version 2.2.2 is ok, but version 2.3.0 blinks.

version 2.0.1

![bokeh_ok](https://user-images.githubusercontent.com/826871/145354772-afbe6c60-636e-406e-b4b6-cee520627816.gif)

### Observed behavior

version 2.4.2

![bokeh_ng](https://user-images.githubusercontent.com/826871/145355175-10027276-2882-4d83-b6b9-4b5e9fb161e3.gif)

### Example code

```Python
from bokeh.plotting import figure, curdoc
from bokeh.models import ColumnDataSource
from matplotlib import cm
import numpy as np
import base64
import cv2

def image_to_url(image):
    _, imgdata = cv2.imencode(".jpg", image, (cv2.IMWRITE_JPEG_QUALITY, 90))
    imgdata = imgdata.ravel()
    url = "data:image/jpeg;base64," + base64.encodebytes(imgdata).decode()
    return url   

def get_image(k):
    Y, X = np.mgrid[-1:1:500j, -1:1:500j]
    Z = np.sin(k * np.sqrt(X**2 + Y**2))
    img = cm.viridis(Z, bytes=True)[:, :, 2::-1]
    return img

k = 1.0

def set_image(image):
    data = {"image":[image_to_url(image)], "width":[image.shape[1]], "height":[image.shape[0]], "x":[0], "y":[0]}
    source_image.data = data

figure_ = figure(toolbar_location=None, plot_width=250, plot_height=250)
figure_.xaxis.visible = False
figure_.yaxis.visible = False
figure_.xgrid.visible = False
figure_.ygrid.visible = False
figure_.outline_line_color = "#cccccc"
source_image = ColumnDataSource(data={})
image = get_image(k)
set_image(image)
image_model = figure_.image_url("image", source=source_image, 
                                               x="x", y="y", w="width", h="height", anchor="bottom_left")
def update_image():
    global k
    set_image(get_image(k))
    k += 0.1
    
doc = curdoc()
doc.add_periodic_callback(update_image, 100)
doc.add_root(figure_)
```

**Comment by mattpap** [comment]
Flickering like this is not unexpected with `ImageURL` glyph, as image loading from an URL is an asynchronous process, and bokehjs attempts to render partial results and images are fetched. This results in two render iterations in this case, one which clears the canvas and the other that renders the image. This could potentially be optimized, as we're dealing with data URL images with no external references (SVG with linked images would be a counter example).

However, for usage like this a much better choice would be to use `ImageRGBA` glyph, which not only would prevent any flickering, but also is much more efficient both performance and memory-wise (allows direct rendering of ndarrays).

**Comment by ruoyu0088** [comment]
The problem can be fixed by modify the for-loop in `_set_data()`:

https://github.com/bokeh/bokeh/blob/a72dc7687509eb98edd8be706c441d946bb9331c/bokehjs/src/lib/models/glyphs/image_url.ts#L54

```typescript
for (let i = 0; i < n_urls; i++) {
    const url = this.url.get(i)
    if (!url)
      continue

    if(url.startsWith('data:image')){
        this.image[i] = new Image()
        this.image[i].src = url
        continue;
    }

    new ImageLoader(url, {
      loaded: (image) => {
        if (this._set_data_iteration == _set_data_iteration) {
          this.image[i] = image
          this.renderer.request_render()
        }
      },
      attempts: retry_attempts + 1,
      timeout: retry_timeout,
    })
  }

```

**Comment by TheoMathurin** [comment]
Unfortunately as of 3.1.1, there is still blinking when updating the image.

Minimal example:

```python
from bokeh.plotting import figure, curdoc
from bokeh.models import ColumnDataSource, Button
from bokeh.layouts import column


def update_image(event):
    global k
    k += 1
    data = {"image": [urls[k % 2]], "width": [300], "height": [300], "x": [0], "y": [0]}
    source_image.data = data


k = 0
urls = ['https://docs.bokeh.org/en/latest/_images/examples/basic/areas/stacked_area.png',
        'https://docs.bokeh.org/en/latest/_images/examples/basic/annotations/colorbar_log.png']

fig = figure(frame_width=300, frame_height=300)
fig.xgrid.visible = False
fig.ygrid.visible = False
source_image = ColumnDataSource(data={"image": [urls[0]], "width": [300], "height": [300], "x": [0], "y": [0]})
image_model = fig.image_url("image", source=source_image,
                            x="x", y="y", w="width", h="height", anchor="bottom_left")

button = Button()
button.on_click(update_image)

doc = curdoc()
doc.add_root(column(fig, button))
```

Also tested on 3.0.3.

**Comment by mattpap** [comment]
It blinks because bokehjs doesn't cache images, so when you update the data, for the sake of consistency, bokehjs renders once to remove old data, awaits for images to load, and then re-renders. See also the TODO in `ImageURLView._set_data()`. Please start a new feature request issue for this.

**Comment by TheoMathurin** [comment]
Thanks @mattpap.

My understanding was that closing this issue through #11888 meant the blink was suppressed. But I will open a new issue, because the current behavior is prohibitive if you want to have animations.
