### ISSUE TITLE
Rename server.start to server.install

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#11882]
ref: https://stackoverflow.com/questions/68969251/bokeh-server-start-not-showing-anything/68975581#68975581

One example of confusion linked above. The `Server.start` method merely installs Bokeh callbacks on an event loop, it does not start anything.  Propose to rename `start` to `install` to more accurately reflect what the method does, and add back a deprecated `start` method that delegates to `install`.

**Comment by NaincyKumariKnoldus** [comment]
Hey @bryevdv Can I do this please?

**Comment by bryevdv** [comment]
@NaincyKumariKnoldus Sorry I missed your question, as far as I know, no one else is working on this so please feel free to submit a PR.

**Comment by NaincyKumariKnoldus** [comment]
Hey @bryevdv I have raised my PR. Review that.

**Comment by NaincyKumariKnoldus** [comment]
Hey @bryevdv I have made the requested changes.

**Comment by bryevdv** [comment]
@NaincyKumariKnoldus There is no need to keep pinging me. You may also need to adjust your expectations about time-frames for PR reviews. Bokeh is a volunteer project with members in all different time zones (It is rather late at night where I am.) PR review turnaround may take days or even longer.

**Comment by bryevdv** [comment]
I've actually changed position on the value of this. It's a little confusing but a breaking change would also be so.
