### ISSUE TITLE
[FEATURE] Expose a file name parameter in SaveTool

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#11881]
### Problem description

Hi,

As everyone knows currently the file name of plots saved with `SaveTool` is 'bokeh_plot.png'. 

I've had use cases where this annoyed users, for instance when they save many plots for later use and want to know what variables or which parameters were used for a given plot. There are also several places [on](https://github.com/bokeh/bokeh/issues/6798) [the](https://stackoverflow.com/questions/43358427/bokeh-custom-save-tool) [web](https://discourse.bokeh.org/t/specifying-name-of-saved-plot-image-file/3058/6) where people mention this need.

Of course it is possible to create a dedicated download button triggering the save programmatically but it's more code, it takes space in the layout and it can be confusing to users.

### Feature description

There's [a discussion](https://stackoverflow.com/questions/43358427/bokeh-custom-save-tool) on SO to which I have contributed last July, providing a working `CustomSaveTool` model. I started with the standard `SaveTool` and added a savename parameter that can be changed from python.

As mentioned by @bryevdv in the various discussions about this, the issue with such a feature is that it may not work in all situations.

However over the course of the last few months I've used my `CustomSaveTool` in a publicly available app. It has been tested on Linux (Ubuntu, CentOS), Windows 10 and macOS with Firefox, Chrome/Chromium, Safari and Edge (but to my knowledge not with IE or Opera). All combinations seemed to work properly. Most notably I did not encounter an example where the browser opened a new tab. There was either a dialog opened or the file was directly downloaded.

If this is a requirement for a PR to be accepted, I can continue and check if it works on other OS/browser configurations, but I would need a detailed list.

### Potential alternatives

If the modification of the standard `SaveTool` is not an option, maybe a separate tool could be created.

### Additional information

NB: I would build an extension for my own use but unfortunately I have not been able to do so as [the docs](https://docs.bokeh.org/en/latest/docs/user_guide/extensions.html#pre-built-extensions) is a bit thin on the subject. And as [this link](https://awesome-panel.readthedocs.io/en/latest/guides/awesome-panel-extensions-guide/bokeh-extensions.html#prebuilt-bokeh-extensions) shows, it can be a bit tricky.

**Comment by bryevdv** [comment]
@TheoMathurin We can definitely consider a PR, but since there is some question, the more documented behavior we can have on different platforms, the better. 

Also, to be honest, a file name property seems like a marginal improvement that won't help much for standalone (non-server) cases, since it would only be possible to update the name from JavaScript, after initial configuration. I think the ideal here would be a tool that pops up a small text input to ask for a name.

**Comment by TheoMathurin** [comment]
Alright I can make sure the tool behaves as intended on IE and Chromium-based browsers such as Opera or Brave.

As for the non-server mode—for instance in a notebook—currently the tool as an inline extension works the same as in server mode. In either case if you modify the save_name attribute from python after a plot is created, it will not be taken into account, but it will in plots created afterwards. I think this behavior is quite reasonable, if it persists once the extension is built like other tools.

Opening an input that prompts the user for a file name would be interesting but not as the default when using the standard save tool I guess. Maybe you mean creating a separate model then.

**Comment by bryevdv** [comment]
> Opening an input that prompts the user for a file name would be interesting but not as the default when using the standard save tool I guess. Maybe you mean creating a separate model then.

No, I was proposing improving the existing tool directly. Being able to to specify the name at save time has definitely been asked before, and at least IMO, is what would make the tool truly useful.
