### ISSUE TITLE
Hover tool improvements

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1189]
- [ ] background color for div configurable
- [x] preserve `OrderedDict` field order on BokehJS side
- [x] configurable with .eco template for more flexible presentation
- [ ] target user-supplied div id instead of  creating tooltip
- [ ] fixed `x`, `y` position, or locations like "upper left"
- [ ] per-glyph customization
- [ ] docs/examples configuring for individual glyphs

**Comment by birdsarah** [comment]
@bryevdv  - things have moved along, is this still an up-to-date to-do list?

**Comment by bryevdv** [comment]
It still seems pretty reasonable. I would like to try and integrate my "fancy bubbles" code for tooltips at some point still, though.

**Comment by joelostblom** [comment]
A high level syntax for fixed tooltip positions would be great! Is there currently a low-level way of of doing this? I would like the tooltip to always show up below the plot. I am trying to modify the [custom tooltip example in the docs](http://bokeh.pydata.org/en/0.11.1/docs/user_guide/tools.html#custom-tooltip), but to no avail so far.

```html
hover = HoverTool(
        tooltips="""
        <div>
            <div>
                <img
                    src="@imgs" height="42" alt="@imgs" width="42"
                    style="float: left; margin: 0px 15px 15px 0px;"
                    border="2"
                ></img>
            </div>
            <div>
                <span style="font-size: 17px; font-weight: bold;">@desc</span>
                <span style="font-size: 15px; color: #966;">[$index]</span>
            </div>
            <div>
                <span style="font-size: 15px;">Location</span>
                <span style="font-size: 10px; color: #696;">($x, $y)</span>
            </div>
        </div>
        """
    )
```

**Comment by bryevdv** [comment]
@joelostblom It would not be much code to write a custom user extension to do this. I am going to be working on more JS api and extension docs this week leading up to the release that will hopefully help people write extensions more easily (so that you don't have to wait on us!)

**Comment by joelostblom** [comment]
Thanks! Although I have not tried out JS before, I look forward to giving it a go when the updated docs and API are out.

And thanks to [info from the Bokeh google group](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/WzTT9wCWXMk), I have managed to get the hover popup to be at a fixed position on the page, but not fixed relatively to the bokeh figure. I can't figure out how to get the figure's position on the page and use that to position the hover tooltip. I am posting my code for the hover tooltip in case you immediately see something that might point me in the right direction.

```html
hover2 = HoverTool(tooltips="""
    <div style="font-family: Ubuntu;
                width : 200px;
                position: fixed;
                left: 85px;
                top: 370px;
              //  border: 2px solid black;
              //  background: #f5f5f5;
                padding: 10px">

    <span style="font-size: 16px;">@Shrt_Desc</span>
    <span style="font-size: 14px;"><br>@RDI{1.1} %RDI</span>
    <span style="font-size: 14px;"><br>@Grams{1.1} @Unit</span>
    </div>
        """
    )
```

Good luck with the release!

**Comment by brycepg** [comment]
@joelostblom 

1. Add an identifier to your tooltip div
2. Use a callback in your hovertool to a javascript snippit
3. Have the callback manipulate the dom

Make sure you remove position:fixed and top/bottom from your style
```python
from bokeh.models import CustomJS

callback = CustomJS(code="""
// You may want to make this future-proof by making a function that finds parent elements by the class 'bk-tooltip'
var tooltip = document.getElementById("static-tooltip").parentElement.parentElement.parentElement;
tooltip.style.top = ""; // unset what bokeh.js sets
tooltip.style.left = "";
tooltip.style.bottom = "0px";
tooltip.style.left = "0px";

""")
hover2 = HoverTool(tooltips="""
    <div id="static-tooltip">
    <span style="font-size: 16px;">@Shrt_Desc</span>
    <span style="font-size: 14px;"><br>@RDI{1.1} %RDI</span>
    <span style="font-size: 14px;"><br>@Grams{1.1} @Unit</span>
    </div>
""", callback=callback)
```

**Comment by bryevdv** [comment]
Several of these are completed, some are obsolete, and some are covered by other issues. I am going to close this issue in favor of individual issues for any remaining tasks.
