### ISSUE TITLE
TimeSeries chart too restrictive on required DataFrame structure?

### ISSUE THREAD

**Issue by michaelaye** [bokeh/bokeh#1190]
The new `TimeSeries` chart in 0.6.0 requires a multi-level index in the columns of the `pd.DataFrame`.
I believe most users would have the time axis data only once in the main index of the `pd.DataFrame`, e.g. when analyzing a bunch of measurements that were taken with several sensors, but at the same time. It feels like you guys implemented the more advanced version of supporting several different time data axes first without implementing the simple case of having just one time column? Or am I missing something?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
