### ISSUE TITLE
[FEATURE] remove_tools() function for plots

### ISSUE THREAD

**Issue by EfremBraun** [bokeh/bokeh#11908]
### Problem description

I would like to interactively add and remove tools from my plot depending on the user selection (my specific case is that at a specific step in the program, I want the user to be able to use the PointDrawTool to add/remove/move points from the graph; other than at that step, I don't want the user to be able to do this).

I can use the `add_tools()` to add tools interactively, but there is not a simple way to remove tools interactively.

### Feature description

Create a `remove_tools()` method for the `Plot` class which accepts a list of tools and removes them from the plot.

### Potential alternatives

 Currently, I'm removing tools myself "under the hood" via `plot.toolbar.tools.remove(toolA)`, where I had earlier defined `toolA=PointDrawTool()` and then added it via `plot.add_tools(toolA)`. It feels a little silly to me to have an `add_tools()` method without a `remove_tools()` method though.

### Additional information

Low priority since there's an existing workaround.

**Comment by g-parki** [comment]
> silly to me to have an `add_tools()` method without a `remove_tools()`

I agree with you on that. Low priority, but I'll go ahead and work on it. I see tests are missing for `add_tools()` as well, so this is a good time to add them.

**Comment by mattpap** [comment]
`Plot.add_tools()` is historical artifact and a side effect of tools requiring a back reference to a plot, and not having collection wrappers. Both issue were addressed, so currently one may as well use `plot.toolbar.tools.append()`. This will be even simpler when issue #3819 is resolved (then it will be `plot.tools.append()`). Sill, as long as we keep `add_tools()`, we may add `remove_tools()` for symmetry.

**Comment by EfremBraun** [comment]
Thanks!
