### ISSUE TITLE
[FEATURE] Be able to set active tool by passing the string name of the tool

### ISSUE THREAD

**Issue by EfremBraun** [bokeh/bokeh#11917]
### Problem description

When I want to programmatically set an active tool, per https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#setting-the-active-tools, I need to give a `Tool` instance. However, since tools are mainly specified via something like `plot = figure(tools="pan,wheel_zoom,box_zoom,reset")` (per https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#specifying-tools), the `Tool` instances are not accessible to the user.

### Feature description

It would be nice to be able to set the active tool by passing the string name of the tool. For instance, `plot.toolbar.active_drag = 'pan'`

### Potential alternatives

One can access the `Tool` instances from the current `Toolbar`, but they don't have names associated with them, so one has to know which index they are in the `tools` list. e.g., one can do `plot.toolbar.active_drag = plot.toolbar.tools[2]` if it is known that the second item in the `tools` list is the pan tool. But this doesn't look so good...if the developer later re-orders the tools, this will become messed up.

Alternatively, perhaps implement some kind of `get_tool_instance()` function, where the user can call `plot.toolbar.get_tool_instance('pan')` to get the `Tool` instance of the pan tool. Then the user can set the active tool by calling `plot.toolbar.active_drag = plot.toolbar.get_tool_instance('pan')`.

**Comment by mattpap** [comment]
So, saying `plot.toolbar.active_drag = 'pan'` would mean to activate by tool type rather than name, because we could have e.g. `PanTool(name="this_specific_pan_tool")` and then say `plot.toolbar.active_drag = 'this_specific_pan_tool'`. I suppose both could be implemented one way or the other, though the later can be already achieved with lengthy `plot.toolbar.active_drag = curdoc().select_one(dict(name="this_specific_pan_tool"))`.

**Comment by EfremBraun** [comment]
The issue with `plot.toolbar.active_drag = curdoc().select_one(dict(name="this_specific_pan_tool"))` is that it can't be done if the tool was initialized via `plot = figure(tools="pan,wheel_zoom,box_zoom,reset")`, since then the tool wouldn't be able to be given a name. So I think the former way of doing it would be preferable.

The only counter-argument I can think of would be if there would be a way for multiple `pan` tools to be present, since in that case `plot.toolbar.active_drag = 'pan'` wouldn't be sufficient to get the particular tool. However, since I don't think that is the case, I don't think this is an issue.

**Comment by bryevdv** [comment]
@mattpap I definitely interpret the OP usage of "name" to mean "type name", e.g. tool aliases like "pan", which I think @EfremBraun has now also clarified. 

I don't love this, for a few small reasons, but would not reject it outright. The main awkwardness IMO revolves around tool aliases like "xpan" which represent a PanTool but with a specific configuration. There aren't any great options AFAICT

* interpret all "*pan" as just "pan" and apply to any currently configured PanTool
* only accept a subset of aliases, i.e. "pan" and "wheel_zoom", but reject the ones like "xpan" and "ywheel_zoom" 
* actually check for a real "xpan" configured as "xpan"

The last seems too fiddly, the first too result in muddy docs that have "This means this, *except in this other case*..." which is always generally a bad sign.

I guess as a compromise I would propose using the actual types:

```
plot.toolbar.active_drag = PanTool
```

which cost an import but is much cleaner in my opinion. It does not require muddying or special casing already existing definitions, and uses existing objects (types) with that already have the necessary meaning.

**Comment by EfremBraun** [comment]
IMHO, since the third option is what's also done when a figure's tools are specified in the `figure(tools=...)` call, it would work in this case as well. However, the last idea mentioned sounds fine to me as well.

**Comment by bryevdv** [comment]
> IMHO, since the third option is what's also done when a figure's tools are specified in the figure(tools=...) call, it would work in this case as well. However, the last idea mentioned sounds fine to me as well.

Actually this reminds me that you can in principle add e.g. xpan and ypan (and even a plain pan, I think) all together. So in the extreme case, using the type is not sufficient to pick which to activate. However, in the common case, not being able to just say "pan" when there is actually only a single "xpan" would be fragile and frustrating. I have to say the more I think about it the more I am 👎 on this idea, unfortunately.

**Comment by bryevdv** [comment]
FYI currently this should be possible:
```
plot.toolbar.active_drag = plot.select_one(PanTool)
```
I am inclined to just leave things at that, in order that the `select_one` is an explicit choice. In case there are multiple pan tools, I would not want to hide/be responsible for that choice.

**Comment by EfremBraun** [comment]
Ah, that works very well. Much better alternative to `plot.toolbar.active_drag = plot.toolbar.tools[2]`. I see no reason to change things either with that being possible, so I'll go ahead and close this.
