### ISSUE TITLE
Request: offer `notebook=True` for all plots

### ISSUE THREAD

**Issue by michaelaye** [bokeh/bokeh#1191]
the TimeSeries chart has a `notebook=True` option that apparently saves the user from calling `output_notebook` first. Is it possible to have this for all plots like `line`, `scatter`, etc.?

**Comment by birdsarah** [comment]
I believe this is fixed. I think the request was for it to be on all charts - and it now is https://github.com/bokeh/bokeh/blob/master/bokeh/charts/_chart_options.py#L79

**Comment by damianavila** [comment]
No, the idea it to having it for the other API, in particular the plotting one...

**Comment by birdsarah** [comment]
My bad - thanks @damianavila

**Comment by bryevdv** [comment]
I'm -1 on this. Having multiple ways of doing things is a real documentation and example headache. I'd like there to be one clear, simple way of doing things.

**Comment by michaelaye** [comment]
For consistency it should be removed then from the TimeSeries, otherwise it's a confusing inconsistent API, offer something here, not there.

**Comment by bryevdv** [comment]
I would like to being the process of deprecating and removing some of the current charts kwargs.

**Comment by bryevdv** [comment]
This was deprecated in `0.11`, closing.

**Comment by bryevdv** [comment]
And to add: I imagine all current deprecations will be removed at `1.0` later this year.
