### ISSUE TITLE
[BUG] LabelSet labels do not show up for bar chart

### ISSUE THREAD

**Issue by appletonbrian** [bokeh/bokeh#11910]
### Software versions

Python version      :  3.8.11 (default, Aug  3 2021, 15:09:35) 
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /home/brian/.conda/envs/myenv/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-4.15.0-162-generic-x86_64-with-glibc2.17

### Browser name and version

Firefox 95.0.1 (64-bit) and Chrome 86.0.4240.111 (64-bit)

### Expected behavior

I am trying to reproduce the results shown in [this StackOverflow answer for how to add data labels to dodge(grouped) bar plots](https://stackoverflow.com/a/56016987/7081944). Three different LabelSets are created, each producing an integer data label over a set of bars in the bar plot.

<img src="https://i.stack.imgur.com/vudVd.png">

### Observed behavior

I ran this code verbatim. The resulting plot has no data labels, and the plot title has been erased.

<img src="https://i.imgur.com/Xb3oC6y.png">

### Example code

```Python
from bokeh.core.properties import value
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, LabelSet
from bokeh.plotting import figure
from bokeh.transform import dodge

output_file("dodged_bars.html")

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ['2015', '2016', '2017']
data = {'fruits' : fruits,
        '2015'   : [2, 1, 4, 3, 2, 4],
        '2016'   : [5, 3, 3, 2, 4, 6],
        '2017'   : [3, 2, 4, 4, 5, 3]}

source = ColumnDataSource(data=data)

p = figure(x_range=fruits, y_range=(0, 10), plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

labels15=LabelSet(x=dodge('fruits', -0.25, range=p.x_range),y='2015',text='2015',source=source,text_align='center')
labels16=LabelSet(x=dodge('fruits', 0.0, range=p.x_range),y='2016',text='2016',source=source,text_align='center')
labels17=LabelSet(x=dodge('fruits', 0.25, range=p.x_range),y='2017',text='2017',source=source,text_align='center')

vbar1 = p.vbar(x=dodge('fruits', -0.25, range=p.x_range), top='2015', width=0.2, source=source,
       color="#c9d9d3", legend=value("2015"))

p.vbar(x=dodge('fruits',  0.0,  range=p.x_range), top='2016', width=0.2, source=source,
       color="#718dbf", legend=value("2016"))

p.vbar(x=dodge('fruits',  0.25, range=p.x_range), top='2017', width=0.2, source=source,
       color="#e84d60", legend=value("2017"))

p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"

p.add_layout(labels15)
p.add_layout(labels16)
p.add_layout(labels17)

show(p)
```

**Comment by mattpap** [comment]
Use:
```py
labels15=LabelSet(..., text=value('2015'), ...)
```
Otherwise, `"2015"` is interpreted as a column in the data source. Though there should be a warning that the column is missing, to give you at least some feedback.

**Comment by appletonbrian** [comment]
> Use:
> 
> ```python
> labels15=LabelSet(..., text=value('2015'), ...)
> ```
> 
> Otherwise, `"2015"` is interpreted as a column in the data source. Though there should be a warning that the column is missing, to give you at least some feedback.

Making that change produces:

<img src="https://i.imgur.com/8Yncy5o.png">

Which is not the desired behavior; see "Expected Behavior" above. I believe `'2015'`, `'2016'`, and `'2017'` are indeed supposed to be interpreted as columns in the data source, because the intent is for each column to be labeled with its y-value.

**Comment by appletonbrian** [comment]
The problem seems to be a string conversion issue. `data['2015']` is a list of integers, whereas I suppose the `LabelSet` argument `text` is looking for a string or list of strings. To work around this, I added another key in the `data` dictionary `'2015_labels'` containing strings and used `labels15=LabelSet(..., text='2015_labels', ...)`. Results below.

It would be helpful if my initial incorrect usage produced some sort of warning or error message, instead of just failing to work.

**Modified code:**

```
from bokeh.core.properties import value
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, LabelSet
from bokeh.plotting import figure
from bokeh.transform import dodge

output_file("dodged_bars.html")

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ['2015', '2016', '2017']
data = {'fruits': fruits,
        '2015': [2, 1, 4, 3, 2, 4],
        '2015_labels': [str(i) for i in [2, 1, 4, 3, 2, 4]],
        '2016': [5, 3, 3, 2, 4, 6],
        '2017': [3, 2, 4, 4, 5, 3]}

source = ColumnDataSource(data=data)

p = figure(x_range=fruits, y_range=(0, 10), plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

labels15 = LabelSet(x=dodge('fruits', -0.25, range=p.x_range), y='2015', text='2015_labels', source=source,
                    text_align='center', render_mode='canvas')
labels16 = LabelSet(x=dodge('fruits', 0.0, range=p.x_range), y='2016', text='2016', source=source,
                    text_align='center')
labels17 = LabelSet(x=dodge('fruits', 0.25, range=p.x_range), y='2017', text='2017', source=source,
                    text_align='center')

vbar1 = p.vbar(x=dodge('fruits', -0.25, range=p.x_range), top='2015', width=0.2, source=source,
               color="#c9d9d3", legend=value("2015"))

p.vbar(x=dodge('fruits', 0.0, range=p.x_range), top='2016', width=0.2, source=source,
       color="#718dbf", legend=value("2016"))

p.vbar(x=dodge('fruits', 0.25, range=p.x_range), top='2017', width=0.2, source=source,
       color="#e84d60", legend=value("2017"))

p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"

p.add_layout(labels15)
p.add_layout(labels16)
p.add_layout(labels17)

show(p)
```

**Output, showing correct labels for 2015:**
<img src="https://i.imgur.com/eHNpSMb.png">

**Comment by bryevdv** [comment]
I'm not actually sure there anything to do here? `LabelSet` has always expected *string* columns. As for errors, as is usually the case, the actual work is done in JS not in Python. Accordingly, there is an error, in the JS console *in the browser*:

> Unhandled Promise Rejection: TypeError: this.text.split is not a function. (In 'this.text.split("\n")', 'this.text.split' is undefined)

It's true that JS error messages could be more visible, since educating users to look at their browser JS console is a continual challenge. But there is a separate issue regarding surfacing browser errors better, so I am inclined to close this issue with no action.

**Comment by bryevdv** [comment]
As for adding Python-side validation, I am 👎 on that:

* It's at best at half-measure. It it  no way prevents a user from updating bad data directly on the JS side e.g. in a `CustomJS` callback, and such validation would have zero visibility in to that scenario
* Despite only handling a subset of cases, it would impose on-trivial complication and overhead at serialization time. 

This is ultimately a JS-side error condition, so really only a JS-side solution makes sense.

**Comment by bryevdv** [comment]
Absent other comment, closing with `noaction`
