### ISSUE TITLE
bokehjs test connection failure under nodejs 17

### ISSUE THREAD

**Issue by g-parki** [bokeh/bokeh#11911]
I've run into `CRITICAL ERROR: Error: connect ECONNREFUSED ::1:9222` on both my MacOS and Windows 10 machines when I run the bokehjs unit tests. I rebuilt the dev environment, but the issue remains. I'm not sure if this is a "me" thing or not - can a @bokeh/dev attempt to replicate please?
Otherwise, any ideas?

```
cd bokehjs
node make test:unit
```
Output:
```
[11:35:00] Starting 'test:start:headless'...
DevTools listening on ws://127.0.0.1:9222/devtools/browser/912230f1-1235-46e3-9666-7a1679cc0d11
[11:35:00] Finished 'test:start:headless' after 184 ms
[11:35:00] Starting 'test:start:server'...
listening on 127.0.0.1:5777
[11:35:03] Finished 'test:start:server' after 2.69 s
[11:35:03] Starting 'test:start'...
[11:35:03] Finished 'test:start' after 0 ms
[11:35:03] Starting 'test:compile:unit'...
[11:35:09] Finished 'test:compile:unit' after 6.20 s
[11:35:09] Starting 'test:build:unit'...
[11:35:15] Finished 'test:build:unit' after 6.17 s
[11:35:15] Starting 'test:unit'...
CRITICAL ERROR: Error: connect ECONNREFUSED ::1:9222
[11:35:18] Finished 'test:unit' after 2.30 s
[11:35:18] failed: tests failed
[11:35:18] failed: tests failed
[11:35:18] failed: task 'top-level' failed because 'test:unit' failed
[11:35:18] failed: task 'top-level' failed because 'test:unit' failed
```

**Comment by mattpap** [comment]
It looks like there's a mixup between ipv4 and ipv6 addresses. Is this a new issue? Perhaps you've updated chromium recently? Or maybe you have a very new (and possible incompatible) nodejs? Let's start with some version numbers the clear out the obvious sources.

**Comment by g-parki** [comment]
Whoops, meant to paste this in:
```
Python version      :  3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:36:06) [MSC v.1929 64 bit (AMD64)]
IPython version     :  7.19.0
Tornado version     :  6.1
Bokeh version       :  2.4.0+167.g0ef16000d
BokehJS static path :  c:\users\parki\documents\github\bokeh\bokeh\server\static
node.js version     :  v17.1.0
npm version         :  7.24.2
Operating system    :  Windows-10-10.0.19042-SP0
```

**Comment by mattpap** [comment]
Downgrade nodejs to 16 and it should work again.

**Comment by mattpap** [comment]
It looks like starting with nodejs 17, ipv6 is preferred over ipv4. I'm guessing you can try using `NODE_OPTIONS=--dns-result-order=ipv4first` with 17.

**Comment by g-parki** [comment]
> Downgrade nodejs to 16 and it should work again.

Yep, that's it.

https://github.com/bokeh/bokeh/blob/0ef16000dc6b6e0961101c3c191e5690d20e7fb0/environment.yml#L45
What do you think about capping the node version in `bkdev`? `nodejs >=14, <17`

**Comment by mattpap** [comment]
Possibly, at least until a solution is devised. I'm pretty sure preference for ipv6 isn't going away in 18, so we need to figure out how to deal with this properly.

**Comment by treysis** [comment]
Try to always use `localhost` instead of `127.0.0.1` or otherwise the proposal is to use `127.0.0.1` instead of `localhost`.

**Comment by mattpap** [comment]
We use nodejs 18.x in CI since PR #12828 on all platforms, and there has been no such issues anymore. If problems persist in some scenarios, please reopen.
