### ISSUE TITLE
[BUG] Incompatibility with Django 4.0

### ISSUE THREAD

**Issue by PeterW-3E** [bokeh/bokeh#11924]
### Software versions

Python version      :  3.9.2 (default, Feb 28 2021, 17:03:44) 
IPython version     :  7.20.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /usr/local/lib/python3.9/dist-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.10.0-9-amd64-x86_64-with-glibc2.31

### Expected behavior

Compatibility of Bokeh with most recent Django 4.0

### Observed behavior

Using Bokeh 2.4.2 with Django 4.0 leads to the following error message on Django startup: 

...
 File "/usr/local/lib/python3.9/dist-packages/bokeh/server/django/routing.py", line 27, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.9/dist-packages/django/conf/urls/__init__.py)

It seems to be related to https://forum.djangoproject.com/t/django-4-0-url-import-error/11065 - i.e. deprecation of url() function in Django 3.1 and its removal in Django 4.0

### Example code

```Python
The code in routing.py should be changed, i.e. Bokeh file bokeh/server/django/routing.py should be corrected:

line 27:
from django.conf.urls import url
into
from django.urls import re_path

lines 108, 123, 125 and 127:
url(...
into
re_path(...

(no example code is available as this problem is triggered directly by a Bokeh distribution file on Django startup, the above (manual) changes in my local Bokeh installation led to Django startup without the above error message).
```

**Comment by bryevdv** [comment]
@PeterW-3E I have to be up front and say I don't know when or even if Bokeh's Django integration will be re-visited. The best case-scenario for continued support in the future is if someone with Django experience, who uses Django regularly and know what kind of integration would be ergonomic to Django users, decides to become a contributor, and help maintain this corner of Bokeh.

**Comment by philippjfr** [comment]
There's interest from the folks that originally funded the work on the Django support to potentially move the Django server layer into a separate repo and update it to support recent Django versions. I'll try to arrange a meeting with the stakeholders in the next couple of weeks. Ping @sdc50

**Comment by bryevdv** [comment]
Ideally work would proceed along lines that further separates the protocol from the transport, so that using the Bokeh protocol is reasonably simple and similar regardless of whether it is used over a websocket or channels (or even long polling)

**Comment by rdmtinez** [comment]
> There's interest from the folks that originally funded the work on the Django support to potentially move the Django server layer into a separate repo and update it to support recent Django versions. I'll try to arrange a meeting with the stakeholders in the next couple of weeks. Ping @sdc50

Any news regarding this?

**Comment by bryevdv** [comment]
functionality moving to separate project

**Comment by sdc50** [comment]
> functionality moving to separate project

https://github.com/bokeh/bokeh-django

**Comment by kavita-p** [comment]
> > functionality moving to separate project
> 
> https://github.com/bokeh/bokeh-django

May I ask why this project is no longer accessible? I'm trying to get a Django project with some Bokeh integration off the ground and I can't find any information on what's happened in the past 20-odd days that renders it unavailable.

**Comment by bryevdv** [comment]
@kavita-p I assume that the folks who are taking it over don't consider it ready for use or publication yet. cc @philippjfr @sdc50 

As for why it is not available in this repo: it was already broken, doesn't actually fit in the API structure cleanly, and no-one here has the bandwidth to support it.

**Comment by hedonistrh** [comment]
Hey, thanks a lot for great work. 🙏🏼 I was trying to use "tabulator" with "panel" and I am using Django 4. According to [documentation](https://panel.holoviz.org/user_guide/Django.html), I should change `bokeh.server.django` with `bokeh_django` but I am not able to find bokeh_django package. Based on this dicussion, apparently that is removed. Are there any update about that work?
