### ISSUE TITLE
[BUG] major_label_overrides are not applied if the overrides are float but the original labels are int

### ISSUE THREAD

**Issue by arian-f** [bokeh/bokeh#11930]
### Software versions

Python version      :  3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
IPython version     :  7.30.1
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  C:\Users\user\AppData\Roaming\Python\Python39\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19043-SP0

### Expected behavior

consider the MWE below, I'd expect the following (notice 'A' and 'B' labels)

![image](https://user-images.githubusercontent.com/48122976/148360628-27f820ee-f61a-4986-a579-6932656d5ffa.png)

when writing down major_label_overrides this is hard to get wrong accidentaly. However, I generated them, so they had a `float` type instead of an `int`. 

One guess of what happens: the major_label_overrides  are converted to strings and compared as such. Then '1' != '1.0'.

### Observed behavior

the original labels are shown, not the overridden ones:

![image](https://user-images.githubusercontent.com/48122976/148360690-eedc11df-f496-4dd0-ac2f-5193c8152001.png)

I can get the overrides to actually apply if I convert them to `int`s. 
This is not straightforward to figure out.

### Example code

```Python
from bokeh.plotting import figure, show
from bokeh.models import FixedTicker

x = [1, 2, 3]
y = [4, 4.5, 6]

# notice that these label overrides have floats
labels = { 1.0: 'A', 3.0: 'C' }
labels_working = { int(k): v for k, v in labels.items() }

fig_bug = figure()
fig_bug.line(x, y)
fig_bug.xaxis.ticker = FixedTicker(ticks=x)
fig_bug.xaxis.major_label_overrides = labels
show(fig_bug)

fig_works = figure()
fig_works.line(x, y)
fig_works.xaxis.ticker = FixedTicker(ticks=x)
fig_works.xaxis.major_label_overrides = labels_working
show(fig_works)
```

**Comment by mattpap** [comment]
This happens, because `dict` is serialized as JS plain objects, so keys become strings. In upcoming bokeh 3.0 we will fix this by serializing `dict` as JS `Map`.
