### ISSUE TITLE
Re-rendering a layout causes menus to be removed from DOM

### ISSUE THREAD

**Issue by maximlt** [bokeh/bokeh#11946]
### Software versions

Python version      :  3.7.11 (default, Jul 27 2021, 07:03:16) 
IPython version     :  7.27.0
Tornado version     :  6.1
Bokeh version       :  2.4.1
BokehJS static path :  /Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/server/static
node.js version     :  v17.0.1
npm version         :  8.1.0

### Expected behavior

I'd expect changing the `css_classes` attribute of the layout not to break the overflow menu button.

### Observed behavior

Suppose a layout that contains a figure, this figure having a toolbar that includes an overflow menu button (I'm not sure about the correct naming of this button). If the `css_classes` property of the layout is modified after it is displayed, the overflow menu button no longer displays the hidden tools when clicked.

### Example code

1/ Run this snippet with `bokeh serve issue.py --show`, 2) check that the overflow menu button works correctly, 3) click on the top button and 4) clicking on the overflow menu button no longer displays the remaining tools.

```Python
# issue.py
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import Button
from bokeh.plotting import figure

button = Button(label="Click to set .css_classes to the layout")
p = figure(height=150)

l = column(button, p)

def cb(event):
    l.css_classes = ['placeholder']

button.on_click(cb)

curdoc().add_root(l)
```

### Screenshots
![issue_bokeh_dotdotdot](https://user-images.githubusercontent.com/35924738/148899652-a8c6f492-745d-4436-a709-cd75f9d23cdd.gif)

**Comment by maximlt** [comment]
I'd be happy to work on this bug, although I would need some pointers since I couldn't quite figure out what is not working as expected.

**Comment by mattpap** [comment]
I will handle this as a part of the layout work (PR #11915).

**Comment by maximlt** [comment]
Great thanks!

**Comment by bryevdv** [comment]
@maximlt We would love to have your contribution in other areas, however, please feel free to ping or ask about any other issues!
