### ISSUE TITLE
[FEATURE]  DataTable with date: In total the date column has NaN-Nan-Nan instead of a space

### ISSUE THREAD

**Issue by mauropu** [bokeh/bokeh#11940]
### Problem description

When adding a total to a DataTable that contains a column with dates, a NaN-Nan-Nan always appears in the final total

### Feature description

I wish I could indicate a blank as the total of the date column.

### Potential alternatives

.

### Additional information

This is the examples

```py
from datetime import date
from random import randint
import pandas as pd
import numpy as np
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn
from bokeh.io import output_file, show
output_file('data_table.html')

#Define the data
dataFrame = pd.DataFrame({'names':[chr(i+65) for i in range(10)], \
                        'dates': [date(2014, 3, i+1) for i in range(10)], \
                       'downloads':[randint(0, 100) for i in range(10)]})
#Convert the datetime.date to datetime64
dataFrame['dates'] = pd.to_datetime(dataFrame['dates'],errors='coerce')# If ignore, then invalid parsing will return the input
                                        # If coerce, then invalid parsing will be set as NaT
rigaSommaDataFrame=dataFrame.sum(axis=0,numeric_only=True,skipna=True) # axis=0 colonne axis=1 righe 
dataFrame=dataFrame.append(rigaSommaDataFrame,ignore_index=True) # if True, the indexes from the source DataFrame objects are ignored 
numeroRigheDataFrame=len(dataFrame.index)-1 # index sono le righe
dataFrame.iat[numeroRigheDataFrame,0]="Total"
dataFrame.iat[numeroRigheDataFrame,1]=""
print(dataFrame)
source = ColumnDataSource(dataFrame)
#define the columns and the DataTable
columns = [
        TableColumn(field="names", title="Names"),
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=550)

show(data_table)
```

![DataTable](https://user-images.githubusercontent.com/33205885/148647341-9dc079d3-2bb7-4b4c-93ec-59d9dd42fcf6.jpg)

**Comment by Harsh-31** [comment]
Can I solve this issue ? Can you assign me this ?

**Comment by Harsh-31** [comment]
from datetime import date
from random import randint
import pandas as pd
import numpy as np
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn
from bokeh.io import output_file, show
output_file('data_table.html')

#Define the data
dataFrame = pd.DataFrame({'names':[chr(i+65) for i in range(9)],
'dates': [date(2014, 3, i+1) for i in range(9)],
'downloads':[randint(0, 100) for i in range(9)]})

#Convert the datetime.date to datetime64
dataFrame['dates'] = pd.to_datetime(dataFrame['dates'],errors='coerce')# If ignore, then invalid parsing will return the input

# If coerce, then invalid parsing will be set as NaT
rigaSommaDataFrame=dataFrame.sum(axis=0,numeric_only=True,skipna=True) # axis=0 colonne axis=1 righe
dataFrame=dataFrame.append(rigaSommaDataFrame,ignore_index=True) # if True, the indexes from the source DataFrame objects are ignored
numeroRigheDataFrame=len(dataFrame.index)-1 # index sono le righe
dataFrame.iat[numeroRigheDataFrame,0]="Total"
dataFrame.iat[numeroRigheDataFrame,1]= ""
print(dataFrame)
source = ColumnDataSource(dataFrame)

#define the columns and the DataTable
columns = [
TableColumn(field="names", title="Names"),
TableColumn(field="dates", title="Date", formatter=DateFormatter(nan_format="")),
TableColumn(field="downloads", title="Downloads"),
]
data_table = DataTable(source=source, columns=columns, width=400, height=550)

show(data_table)



**Issue Resolved. Now it is not showing NaN-NaN-NaN. I hope it will help you.** 

![Capture](https://user-images.githubusercontent.com/66908988/148827889-502801f4-bcb8-4090-869f-0005cbea9e48.PNG)

**Comment by bryevdv** [comment]
Hi @Harsh-31 that is not a resolution to this issue, your output has dropped the "J" row entirely. That is not the goal, the goal is to still display the row, but do so with better formatting.

Can you confirm that all you did is add `nan_format=""` to the `DateFormatter` ? If so I think there may actually be a bug as well, since I would not expect that to delete the row from the output.

**Comment by mauropu** [comment]
Hi
I have test the solution and add to my code 
DateFormatter(nan_format="")
I think that all work very fine
I see 10 rows
Thanks Thanks Thanks
![Image2](https://user-images.githubusercontent.com/33205885/148836263-cd3c68ab-5e97-4ab7-8dac-6f8d919f353f.jpg)

**Comment by bryevdv** [comment]
Oh it looks like you generated one less row `range(9)` in your original code. 

After having a chance to study the OP more closely, there is not actually any issue or bug at all here. @mauropu summing datetimes is not really a reasonable operation, which is why you re seeing a nan value. However, I think the current default behavior, i.e. displaying nans as nans, is entirely appropriate. It is possible to do something different, e.g. by using `nan_format` as @Harsh-31 suggests or otherwise customizing the formatter, but that is a support question, so it belongs on the Discourse, not the issue tracker:

https://discourse.bokeh.org
