### ISSUE TITLE
[BUG] Replacing filter of CDSView does not trigger update of DataTable

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#11955]
### Software versions

Python version      :  3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.4.2

### Expected behavior

CDSView should react to filter changes for both plots and tables as described here: https://github.com/bokeh/bokeh/discussions/11560#discussioncomment-1281910

### Observed behavior

Only plots are updated, the DataTable won't receive an update unless it is disabled and re-enabled.

### Example code

```Python
import pandas as pd

from bokeh.layouts import row
from bokeh.models import Button, ColumnDataSource, CDSView, DataTable, IndexFilter, TableColumn
from bokeh.plotting import curdoc, figure

col_names = ["col1", "col2", "col3"]
data = [["a", 1, 2], ["b", 3, 4], ["c", 5, 6], ["d", 7, 8]]

df = pd.DataFrame(data)
df.columns = col_names

source = ColumnDataSource(df)
selection = CDSView(source=source, filters=[])

ui_columns = [TableColumn(field=col, title=col) for col in col_names]
table = DataTable(source=source, columns=ui_columns, view=selection)

plot = figure(width=400, height=400)
plot.circle(x="col2", y="col3", source=source, view=selection)

def update_filter():
    selection.filters = [IndexFilter(indices=[1])] # Only updates plot NOT table

    # required to trigger an update of the table (but causes unnecessary rendering)
    #table.disabled=True
    #table.disabled=False

    # Another option to trigger the table update
    #table.visible = False
    #table.visible = True


button = Button(label="Foo", button_type="success")
button.on_click(update_filter)

curdoc().add_root(row(table, plot, button))
```

**Comment by bryevdv** [comment]
Confirmed in `branch-3.0` FYI for future reference @muendlein note that when 3.0 is released `CDSView` will no longer need (or accept) a `source` argument.

**Comment by mattpap** [comment]
Since PR #11239 this is under visual test.
