### ISSUE TITLE
[FEATURE] Bokeh event Hooks

### ISSUE THREAD

**Issue by matteo-morando** [bokeh/bokeh#11950]
### Problem description

Missing event hooks to implement custom loaders

### Feature description

Could be possible to add a custom hook when the Bokeh items were rendered or when Errors occurs (like rendering problems, websocket ecc) practically near many console.log?

The line of reference is the following
https://github.com/bokeh/bokeh/blob/ca239b9a92605710f4ea6681da29696979d98824/bokehjs/src/lib/embed/index.ts#L75

Maybe something like this
`window.top.postMessage('bokeh_loaded','*')`

### Potential alternatives

Unknown

**Comment by bryevdv** [comment]
Sorry this fell through the cracks for triage. @matteo-morando Bokeh 3.1 adds events for `DocumentReady` and for `ConnectionLost` do those satisfy your needs?

**Comment by bryevdv** [comment]
Closing for lack of update. We can consider re-opening if/when additional information is provided.
