### ISSUE TITLE
[BUG] Table formatting causes layout crash/collapse

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#11965]
### Software versions

Python version      :  3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.4.2

### Expected behavior

Layout is rendered correctly with TableColumn formatting (ScientificFormatter)

### Observed behavior

TableColumns with ScientificFormatter cause a complete layout crash: all layout items shift, overlap, etc.

### Example code

```Python
from bokeh.layouts import row
from bokeh.models import Button, ColumnDataSource, CDSView, DataTable, IndexFilter, TableColumn
from bokeh.plotting import curdoc, figure
from bokeh.models import ScientificFormatter

col_names = ["col1","col2","col3","col4"]

source = ColumnDataSource()
ui_columns = [TableColumn(field=col, title=col, formatter=ScientificFormatter(power_limit_low=-3, power_limit_high=5, precision=6)) for col in col_names]
table = DataTable(width=300, max_width=300, columns=ui_columns)
table.source = source
button = Button(label="test")
table2 = DataTable(width=500, max_width=500, source=source, columns=ui_columns)

curdoc().add_root(row(table, button, table2))
```

### Screenshots

![bokeh_layout_normal](https://user-images.githubusercontent.com/71090451/150422901-914ccbe6-f025-43c3-a81d-c4ad24e6d969.PNG)
![bokeh_layout_bug](https://user-images.githubusercontent.com/71090451/150422902-0bdfe944-6114-4cbf-862b-6c33abe1e99c.PNG)

**Comment by bryevdv** [comment]
@muendlein TableColumns refer to columns that are ***presumed to exist*** in a CDS. So at the very least, regardless, you need to make sure the CDS has the expected columns, even if they are empty lists/arrays. 

However, a separate issue is that the cell formatting step is not happy when there is not data (with or without expected empty columns). Confirmed in `branch-3.0` as well
