### ISSUE TITLE
[BUG] Option groups of the Select widget are sorted

### ISSUE THREAD

**Issue by maximlt** [bokeh/bokeh#11963]
### Software versions

Python version      :  3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) 
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.0.2+1062.g6aac056b2.dirty
BokehJS static path :  /home/liquetm/dev/bokeh/bokeh/server/static
node.js version     :  v16.13.0
npm version         :  8.1.0
Operating system    :  Linux-5.4.0-92-generic-x86_64-with-glibc2.10

### Expected behavior

I expect the `Select` widget to display the option groups in the ordered provided in the constructor.

### Observed behavior

The groups are sorted on the client-side (see the screenshot)

I'm not sure but this might happen because the JSON encoder (the `serialize_json` function) sorts the keys by default.

### Example code

```Python
from bokeh.io import show
from bokeh.models import Select

# Note the order of the dictionary keys: C A B
select = Select(title='Opt Group', value='1', options=dict(C=['5', '6'], A=['3', '4'], B=['1', '2']))

show(select)
```

### Screenshots

![image](https://user-images.githubusercontent.com/35924738/150106379-072b9377-9cbf-41d1-a8f8-b1434a36bb93.png)

**Comment by mattpap** [comment]
> I'm not sure but this might happen because the JSON encoder (the serialize_json function) sorts the keys by default.

This this the reason. Given that insertion order is officially preserved since 3.7, I think I will change this in PR #11960, especially given that in that PR, raw `dict` isn't used for structural encoding anymore.

**Comment by maximlt** [comment]
Great! You're on fire @mattpap 🔥
