### ISSUE TITLE
Reset and resize tools do not work with GMapPlot

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1196]
Best option is to make usable in some reasonable way, but at a minimum, disable and warn about disabling.

**Comment by dsoto** [comment]
Similar issue in #2007

**Comment by birdsarah** [comment]
From @Maggie-M  on #2007 

Pressing the Reset button at any time in this example causes the plot to point somewhere in the South Atlantic Ocean.

I've illustrated this with a little Indiana Jones 'travel montage' map to make this issue into an adventure.

![image](https://cloud.githubusercontent.com/assets/1796208/8627938/ed3ef1ee-274e-11e5-9db2-f0fde7a76264.png)

**Comment by bryevdv** [comment]
Am closing this as a dupe. There was another issue about the reset tool that was just fixed and closed, and I am not sure resize is worth fixing or possible to do.
