### ISSUE TITLE
[BUG] DataTable rendering behaves inconsistently for different indices of an IndexFilter

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#11969]
### Software versions

Python version      :  3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.4.2

### Expected behavior

DataTable rendering based on a CDSView with an IndexFilter should be consistent with the corresponding indices.

### Observed behavior

DataTable does not execute an update render for certain combinations of data size and indeces (which is pretty weird).
In my minimal example I have a dataset with 109 rows that is displayed in one table. Another table will show the current selection when a button is clicked. For row indices from 0 to 96 this works as expected, however no table rendering is executed for row indices from **97 to 108**.  Why?
This issue can not be observed for a dataset with 108 rows however other dataset sizes (i.e. 500) show similar issues.
(issue might be similar to #11955)

### Example code

```Python
import pandas as pd
import numpy as np

from bokeh.layouts import row, column
from bokeh.models import Button, ColumnDataSource, CDSView, DataTable, IndexFilter, TableColumn
from bokeh.plotting import curdoc, figure

col_names = ["col1", "col2", "col3", "col4"]
data = np.random.rand(109, 4)
df = pd.DataFrame(data=data, columns=col_names)

ui_columns = [TableColumn(field=col, title=col) for col in col_names]
source = ColumnDataSource(df)
view1 = CDSView(source=source)
view2 = CDSView(source=source, filters=[IndexFilter(indices=[])])

table = DataTable(width=300, max_width=300, source=source, columns=ui_columns, view=view1)
table2 = DataTable(width=500, max_width=500, source=source, columns=ui_columns, view=view2)


def add_selection_to_table():
    selected_indices = source.selected.indices
    table2.view.filters = [IndexFilter(indices=selected_indices)]
    table2.disabled = True
    table2.disabled = False


def clear_selection_from_table():
    table2.view.filters = [IndexFilter(indices=[])]
    table2.disabled = True
    table2.disabled = False


# two basic interactive buttons for data filtering
button = Button(label="select")
button.on_click(add_selection_to_table)

button2 = Button(label="clear selection")
button2.on_click(clear_selection_from_table)

curdoc().add_root(row(table, column(button, button2), table2))
```

**Comment by bryevdv** [comment]
This is pretty bizarre. The description to repro was a little unclear to me: for the benefit of others:

* select a block from table 1 below row 96 -> select button shows selection in table 3 (and clear button clears)
* select a block from table 1 *above* row 96 -> nothing shows up in table 2

New info: 

* select a block *straddling* row 96 -> works 

@mattpap could this be a bug with the bitset implementation? The very specific cutoff at 96 = 64 + 32 is at least initially suggestive to me.

**Comment by bryevdv** [comment]
Also noting this persists on `branch-3.0`

**Comment by muendlein** [comment]
Another example in case that helps: 500 rows with row index 483 as splitting value (above 483 the selection will not show up in table 2).

**Comment by muendlein** [comment]
@bryevdv I did some debugging on this issue however I am currently stuck (mainly due to lacking a proper debug setup for the bokehjs stuff). From my debugging I have noticed that the bitset calculation seems to be working as intended. However assigning the indices to the CDSView model changes will reset the bitset values to 0 (for indices above the 'threshold'). At this stage I am even more confused, do you have any idea how the assignment can have this kind of impact?


compute_indices function of CDSViewView:
```
    ...
    const filtered = this.model.filter.compute_indices(source)
    indices.intersect(filtered)

    console.log(indices) // indices are correct here
    this.model.indices = indices // assignment seems to be the root cause
    console.log(this.model.indices) // indices of the model is not the same as the original indices
    ...
```
