### ISSUE TITLE
[FEATURE] Allow passing things other than models into args argument on CustomJSHover

### ISSUE THREAD

**Issue by gmerritt123** [bokeh/bokeh#11996]
### Problem description

Basic MRE 

```
from bokeh.models import CustomJS, CustomJSHover

cb = CustomJS(args=dict(v='something')) #fine

cbh = CustomJSHover(args=dict(v='something')) #not fine
```

### Feature description

I'd like to align what I can pass as args to CustomJS and what I can pass to CustomJSHover.

### Potential alternatives

N/A

### Additional information

Discussed here: https://discourse.bokeh.org/t/customjs-and-customjshover-args-argument-not-consistent/8876/3

**Comment by bryevdv** [comment]
Just noting we should probably make a property alias for the `args` dict that gets used throughout for consistency. Currently some are `Dict(String, AnyRef)` and others are `Dict(String, Instance(Model))`
