### ISSUE TITLE
[BUG] Allow reset of DatePicker to empty date

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#11994]
### Software versions

Bokeh 2.4.3

### Expected behavior

I would expect to be able to reset the `DatePicker` widget to a null value, i.e. either None or an empty string.

### Observed behavior

Currently both programmatic and UI resets of the value either to `None` or to `''` triggers  an error.

### Example code

This can be reproduced with:

```Python
from bokeh.models import DatePicker

dpicker = DatePicker(value='2011-01-01')

dpicker.value = None
dpicker.value = ''
```

or by deleting the date in the UI.

![dpicker](https://user-images.githubusercontent.com/1550771/153037897-c0496c32-5813-4cbe-a5a6-a485ed060b32.gif)

### Stack traceback or browser console output

```
ValueError: failed to validate DatePicker(id='1019', ...).value: Expected an ISO date string, got ''
```

**Comment by mattpap** [comment]
The error is sound with the current definition of `DatePicker`. We would have to change `DatePicker.value` to `Nullable(Date)` to allow for clearing the date, perhaps with a UI change adding a "clear" button. This would change the behavior of the widget, which makes me thing about adding this as a derived `OptionalDatePicker` (or something like that) widget.

**Comment by philippjfr** [comment]
The UI already allows resetting the value to an empty string (as can sort of be seen in my gif) so I do think this is a bug and should be supported. No strong opinion on supporting null/None.

**Comment by bryevdv** [comment]
Flatpickr supports a `clear` API:

https://flatpickr.js.org/instance-methods-properties-elements/#clear

And can also have a clear button added easily:

https://flatpickr.js.org/examples/#flatpickr--external-elements

But I would also expect to be able to programmatically clear the value in some manner, so I agree this is an omission.
