### ISSUE TITLE
[Docs] his must be replaced by This

### ISSUE THREAD

**Issue by haripriya9647** [bokeh/bokeh#11995]
### Software versions

Python version      :  3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.19.0
Tornado version     :  6.0.4
Bokeh version       :  2.2.3
BokehJS static path :  C:\Users\hari priya\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  v14.17.4
npm version         :  6.14.14

### Expected behavior

While I was going through the examples in Bokeh Gallery I found a minor spelling error on this page - [https://docs.bokeh.org/en/latest/docs/gallery/latex_normal_distribution.html] 
![Screenshot 2022-02-08 235709](https://user-images.githubusercontent.com/66864971/153052171-a8853398-f627-4171-8b8a-a44a8a2afc12.jpg)

 

### Observed behavior

Where the word "his" must be replaced by "This" in the description.

### Example code

```Python
After Change description will look this way - 
A plot of the Normal (Gaussian) distribution. This example demonstrates the use of mathtext on axes and in Div objects.
```

**Comment by bryevdv** [comment]
@haripriya9647 would you like to submit a PR with this change?

**Comment by haripriya9647** [comment]
Yeah I would like to work on this issue

**Comment by bryevdv** [comment]
Great! Let us know if you have any questions about process, etc or if we can help in any way

**Comment by bryevdv** [comment]
@haripriya9647 did you still want to submit a PR? If not one of the core devs will tack this change on to another PR to avoi leaving this issue open.

**Comment by bryevdv** [comment]
fixing in #12036
