### ISSUE TITLE
Investigate Choices.js for Select

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12002]
As long as we are already bringing in `choices.js` as a dependency, I think we could consider switching to using their Single / Multi Select widgets (scroll down the page to see):

https://choices-js.github.io/Choices/

They are definitely more modern/nicer looking, and support asked-for features like better search and remote fetch for options, out of the box. 

cc @bokeh/dev

**Comment by philippjfr** [comment]
I agree, if we're already pulling in the dependency we may as well leverage all the nice features it provides.

**Comment by mattpap** [comment]
I would keep native widgets and move them to a separate bundle.

**Comment by mattpap** [comment]
I will close this given that we will be dropping external widget dependencies in near future (see e.g. PR #13551). I will implement new `Select` widget using generalized `PaletteSelect`'s logic.
