### ISSUE TITLE
Documentation builds fail in CI

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12008]
With error message:
```
The 'black' distribution was not found and is required by the application
```

**Comment by bryevdv** [comment]
Honestly at a loss for this one. It would probably be a good idea to add an explicit `conda list` on all CI job's environments. It's pretty hard to compare versions across different runs from the noisy conda install output.

**Comment by mattpap** [comment]
So apparently this self-resolved today. I'm going to close this issue. Fragility of sphinx and especially lack of useful error explanation is concerning though.
