### ISSUE TITLE
[FEATURE] provide SRI hashes for CSS resources

### ISSUE THREAD

**Issue by rdmtinez** [bokeh/bokeh#12017]
### Problem description

I'm working on a dashboarding project and my manager would like me to provide an integrity hash for all resources. I was able to find the bokeh.resources.get_all_sri_hashes function, but it only lists the hash for the .js files. Any chance css integrity hashes could be provided in the future?

### Feature description

provide SRI hashes for CSS files

### Potential alternatives

Allow https://www.srihash.org/ to generate SRI hashes given css resource link (e.g. "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.2.min.css")

**Comment by mattpap** [comment]
Bokeh doesn't use CSS files anymore (we use "CSS modules" integrated into JS bundles instead), so those hashes aren't needed. We used to publish empty CSS files for a while, for the sake of backwards compatibility, but that's not done anymore.

**Comment by rdmtinez** [comment]
@mattpap Thank you so much for getting back to me! This is good to know :)
