### ISSUE TITLE
Every model and every property should be used in examples

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1201]
We should automatically verify that we have 100% coverage.

**Comment by mattpap** [comment]
Superseded with #1647.

**Comment by mattpap** [comment]
PS. We should have `reso: superseded` for issues?

**Comment by bryevdv** [comment]
In cases like this I just mark it `reso: invalid` with a clear link the other issue.

**Comment by mattpap** [comment]
OK. Done.
