### ISSUE TITLE
[BUG] Bokeh uses different color than specified (hex)

### ISSUE THREAD

**Issue by michalkowalski94** [bokeh/bokeh#12013]
### Software versions

Python version      :  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
IPython version     :  8.0.1
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /opt/miniconda3/envs/primer_env/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.4.0-84-generic-x86_64-with-glibc2.31

### Jupyter notebook / Jupyter Lab version

jupyterlab       : 3.2.8

### Expected behavior

Showing actual color

### Observed behavior

Showing random color

### Example code

```Python
# ##9A0000 is shown as #79588A (there is actually a shitload of those)
```

### Screenshots

![image](https://user-images.githubusercontent.com/40108472/154737592-d205d34e-9784-4a20-b9b5-fe0edb4a3363.png)
![image](https://user-images.githubusercontent.com/40108472/154737654-75bcdd8f-1aad-46fd-8d41-bd5be69eff90.png)

**Comment by bryevdv** [comment]
@michalkowalski94 You need to provide a complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) in order for anything to be investigated. I've never seen anything like you describe, and I've never heard of anyone reporting anything like you describe, so the onus is on you t provide complete code to reproduce what you are seeing.

**Comment by michalkowalski94** [comment]
Hold Your horses wit Your perogative friend. Made two mistakes, one was missclick second one was sorting.
Have a nice day

**Comment by bryevdv** [comment]
@michalkowalski94 Thanks for the feedback, I am glad you have sorted things out. For future FYI the [Discourse site](https://discourse.bokeh.org) is a great (and usually very responsive) place to start for questions that might or might not be issues.

**Comment by michalkowalski94** [comment]
Sorry for trouble!
Cheers!
