### ISSUE TITLE
[BUG] Incorrect handling of step by DateRangeSlider

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12033]
### Software versions

Python version      :  3.10.2 | packaged by conda-forge | (main, Jan 14 2022, 08:02:09) [GCC 9.4.0]
IPython version     :  8.0.0
Tornado version     :  6.1
Bokeh version       :  3.0.0dev5+2.gf990664e5.dirty
BokehJS static path :  /home/iant/github/bokeh/bokeh/server/static
node.js version     :  v16.12.0
npm version         :  8.3.1
Operating system    :  Linux-5.13.0-30-generic-x86_64-with-glibc2.34

### Browser name and version

Same in all browsers

### Expected behavior

In `DateRangeSlider` the `start` and `end` kwargs are dates, and the `step` is an integer. I expect the units of the `step` to be days therefore. However internally in JS the dates, i.e. slider positions, are stored as POSIX time (in milliseconds since 1970 UTC) so a `step` of 1 is interpreted as 1 millisecond rather than 1 day. If one of the sliders is on a particular date and the `step` is the default of 1, I expect when I drag the handle to the right that the next valid position is the next day.

### Observed behavior

There are many more valid slider positions per day than I expect (86400*1000 to be precise).

### Example code

```Python
# Taken from DateRangeSlider example in docs, but only over 5 days.
from datetime import date
from bokeh.io import show
from bokeh.models import CustomJS, DateRangeSlider

date_range_slider = DateRangeSlider(value=(date(2016, 1, 1), date(2016, 1, 5)),
                                    start=date(2016, 1, 1), end=date(2016, 1, 5))
date_range_slider.js_on_change("value", CustomJS(code="""
    console.log('date_range_slider: value=' + this.value, this.toString())
"""))

show(date_range_slider)
```

**Comment by ianthomas23** [comment]
I think the fix is to override `_calc_to` in `DateRangeSliderView` so that
``` javascript
      step: this.model.step,
```
is actually
``` javascript
      step: this.model.step * 86400*1000,
```

Alternatively, the current behaviour could be deemed acceptable and we just need to update the documentation to clarify that the `step` is in units of milliseconds.

**Comment by g-parki** [comment]
My vote would be to update the default `step` to 86,400,000 and clarify in the documentation that the unit is milliseconds. This also maintains consistency with the upcoming `DatetimeRangeSlider`.
Perhaps the same change makes sense for `DateSlider` since it also accepts `date` values and is rendered in the same format `%d %b %Y`

**Comment by bryevdv** [comment]
@g-parki I don't think changing the default is sufficient, since a user would get unexpected behaviour as soon as they set `step = 7` to try and skip weeks. "One day" seems like the minimal reasonable step for *date*-anything. I do think that `DateSlider` should also get the same treatment. Would one of you be able to submit a PR?

**Comment by g-parki** [comment]
> Would one of you be able to submit a PR?

I'd be happy to.

**Comment by ianthomas23** [comment]
@g-parki Are you still intending to submit a PR for this? It would be good to get it into 3.0 which we are hoping to release soon.

**Comment by g-parki** [comment]
Hey @ianthomas23 sorry I've been tied up with other obligations lately. Yes I'd like to take care of this one. Is there an estimate date for 3.0?

**Comment by ianthomas23** [comment]
Not really, we have reached "soon" but we are not committing more than that. A few weeks perhaps?
