### ISSUE TITLE
[BUG] Changing y axis label affects the labels of all extra y ranges.

### ISSUE THREAD

**Issue by PeterPyn** [bokeh/bokeh#12031]
### Software versions

Python version      :  3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.17.0
Tornado version     :  6.0.3
Bokeh version       :  2.4.2
BokehJS static path :  c:\python\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.17134-SP0

### Expected behavior

Change in y axis label only affects main y axis.

### Observed behavior

Change in y axis label affects main y axis and all extra y ranges.

### Example code

```Python
import numpy as np
from bokeh.models import DataRange1d, LinearAxis
from bokeh.layouts import gridplot
from bokeh.plotting import figure, show
from bokeh.sampledata.stocks import AAPL, MSFT


def datetime(x):
    return np.array(x, dtype=np.datetime64)

p1 = figure(x_axis_type="datetime", title="Stock Closing Prices", y_range=DataRange1d())

p1.grid.grid_line_alpha=0.3
p1.xaxis.axis_label = 'Date'

p1.extra_y_ranges.update({'TestAx': DataRange1d()})
la = LinearAxis(y_range_name='TestAx', axis_label='TestAx')
p1.add_layout(la, 'right')

p1.line(datetime(AAPL['date']), AAPL['adj_close'], color='#A6CEE3', legend_label='AAPL')
p1.line(datetime(MSFT['date']), MSFT['adj_close'], color='#FB9A99', legend_label='MSFT', y_range_name='TestAx')

p1.yaxis.axis_label = 'Price'

show(p1)
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/65343887/156554502-2789c5cd-3aae-4865-b484-431582567c32.png)

**Comment by bryevdv** [comment]
@PeterPyn this is the intended behavior. See the documentation:

https://docs.bokeh.org/en/latest/docs/user_guide/styling.html#styling-axes

To address individual axes, use `xaxis[0`, `xaxis[1]`, etc.

**Comment by PeterPyn** [comment]
Thanks Bryan for the quick response, and sorry that I did not see that in the docs. However, I have to say I find it quite confusing that the property xaxis (singular) refers to a list of axes. I guess that's developed over time, and we just have better read the docs.

**Comment by bryevdv** [comment]
> I have to say I find it quite confusing that the property xaxis (singular) refers to a list of axes. 

I don't disagree that it is a little unusual, but as for rationale: it is far more common for users to want to set identical styles (fonts, colors, etc) across all the axes at once, and for that common case, having an easy way to address all the axes at the same time is a valuable convenience.
