### ISSUE TITLE
Typo in ValueError in L170 of serialization.py repo

### ISSUE THREAD

**Issue by vicade-mp** [bokeh/bokeh#12049]
### Software versions

N/A 

### Expected behavior

N/A

### Observed behavior

N/A

### Example code

```Python
N/A
```

### Screenshots

<img width="1440" alt="VE 2" src="https://user-images.githubusercontent.com/67339350/158912233-4c94c622-9ba4-4fd3-8642-555c6fd38957.png">
<img width="1440" alt="VE" src="https://user-images.githubusercontent.com/67339350/158912219-74d9a234-7ed2-4f85-972f-7416f25c8d8c.png">

**Comment by g-parki** [comment]
Typo in this line:
https://github.com/bokeh/bokeh/blob/c2e2b167ec076e01a5188b07b3ffeb14bfa8c395/bokeh/util/serialization.py#L170
