### ISSUE TITLE
[BUG] Jumpy scroll on mobile

### ISSUE THREAD

**Issue by stas-sl** [bokeh/bokeh#12047]
### Software versions

Python version      :  3.9.7 (default, Sep 16 2021, 08:50:36)
IPython version     :  7.31.1
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /Users/stas/.pyenv/versions/anaconda3-2021.11/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v17.4.0
npm version         :  8.3.1
Operating system    :  macOS-10.15.7-x86_64-i386-64bit

### Browser name and version

Mobile Chrome 99.0.4844.59 (Official Build) stable (64-bit), Mobile Safari

### Expected behavior

Scrolling long pages on mobile works smoothly, no content disappears after page reload.

### Observed behavior

When opening a long page with multiple plots on mobile browser and trying to scroll it, it starts to jump. Sometimes it scrolls only by a few pixels, sometimes it scrolls well, but then jumps to the top. Especially if you try to scroll fast. Sometimes after page reload only half of the page is displayed, or not displayed at all, while the scroll bar is visible and you can scroll. I tested it on mobile Chrome and Safari and observed quite similar behavior, while on Desktop it works fine without any errors in console. It is reproduced even without any plots on a page, if I just stack a lot of Divs in a column. You can try it yourself [here](http://r.curious.by/test_bokeh_mobile_scroll.html) (open in mobile browswer)

### Example code

```Python
import numpy as np

from bokeh.io import output_file, show
from bokeh.plotting import figure
from bokeh.layouts import column
from bokeh.palettes import Category10_10

output_file('test_bokeh_mobile_scroll.html')

figures = []

for i in range(10):
    p = figure(tools=[], toolbar_location=None, title=f'figure {i}')
    x = np.r_[0:30:1000j]
    p.line(x, np.sin(x), color=Category10_10[i])
    figures.append(p)

show(column(figures))
```

### Screenshots

https://user-images.githubusercontent.com/4602302/158619545-163c73d6-bf6d-49ea-818b-4f965e9b9eee.mp4

**Comment by stas-sl** [comment]
Thanks for checking it! Interesting... I've just installed Mobile Firefox 98.1 (8367) and reproduced the same issue as well. It occurs more often on the first scroll when you are at the top of a page, also if you scrolled down to the middle and try to scroll up just a little bit, it suddenly jumps right to the top. Also I observe content disappearing after a few page refreshes.
But I'm using iOS device. Maybe it is specific to iOS? Can someone try to reproduce it there? I also double checked other sites just to be sure that it isn't something specific with my device that causes that issue on all sites.

https://user-images.githubusercontent.com/4602302/158640225-6e891029-eb23-426e-93eb-154f16448d70.mp4

**Comment by mattpap** [comment]
Whatever is going on in this issue, it should be fixed by the new layout.
