### ISSUE TITLE
[FEATURE] Support varea with step lines

### ISSUE THREAD

**Issue by dnnr** [bokeh/bokeh#12062]
### Problem description

Currently, there appears to be no way to fill an area (like with VArea) with a step-line boundary.

The only discussion about it that I could find is this: https://discourse.bokeh.org/t/stacked-area-plot-with-step-levels/4679 There it's suggested to try using vbar_stack instead, but this covers only a narrow subset of what could be done with a proper step-wise varea.

If necessary, I can provide a concrete use-case illustrating the need for this, but for now I'm assuming there's no controversy about its value.

### Feature description

I suppose the straight-forward approach would be to extend VArea with an optional `step_mode` parameter of type `Enum(StepMode)`.

### Potential alternatives

Maybe a separate glyph could also be appropriate? Hard for me to judge.

### Additional information

I haven't really contributed to bokeh before, but I'd be willing to give it a try and scratch my own itch here, as long as there are no fundamental objections to the feature itself. That said, I might be biased by my own need for it, so maybe there's a good reason this doesn't exist yet?

**Comment by jbednar** [comment]
Sounds useful, and once implemented we could add datashader support to cover the case in the linked issue.
