### ISSUE TITLE
[FEATURE] Link documented sampledata to standalone example

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#12066]
### Problem description

Right now the [sampledata](https://docs.bokeh.org/en/latest/docs/reference/sampledata.html?highlight=sampledata#module-bokeh.sampledata.airports) on the documentation is listed and some of these datasets are used in exmples (in `examples/plotting/file` and `examples/models/file`. In #11765 the goal is to link the examples with the sampledata, but there is no link in the other direction.

### Feature description

The goal is to create a link for each sampledata dataset to link to a standalone example in the gallary or at least show where the example is stored in this repository. This should be solved with a Sphinx extention.

This task includes the following steps:
* extract the `sampledata` information from the metadata given in the examples
* create a standalone solution for all examples which use dataset from sampledata
* add a link to the gallery  or a path to the example for each sampledata

### Potential alternatives

If the solution above is to complicated, the links can be places as a "dirty" fix by hand.

**Comment by mosc9575** [comment]
FYI: I want to give this problem a try myself.

**Comment by bryevdv** [comment]
The current PR links only to gallery examples but future work could extend things to link to files in the tree and not just sphinx pages.
