### ISSUE TITLE
[BUG] Non-circle hover glyphs permanently rendered with vline/hline mode

### ISSUE THREAD

**Issue by marxide** [bokeh/bokeh#12078]
### Software versions

Python version      :  3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:06:49)
IPython version     :  8.2.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  ~/miniconda3/envs/test/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  macOS-10.16-x86_64-i386-64bit

### Expected behavior

Hover glyphs to individually render according to hline/vline cursor hit testing, and reset when the cursor moves away.

### Observed behavior

Hover glyphs for all glyphs are rendered as soon as the cursor enters the plot and never go away.

### Example code

```Python
from bokeh.models import HoverTool
from bokeh.plotting import figure, show

p = figure()
_ = p.scatter(
    x=range(5),
    y=range(5),
    marker="circle",
    size=20,
    fill_color="steelblue",
    hover_fill_color="red",
    hover_alpha=0.1,
)
p.add_tools(HoverTool(mode='vline'))
show(p)
```

### Screenshots

![image](https://user-images.githubusercontent.com/9478316/161826797-caa2054f-db4a-4190-855e-ec32ec095b88.png)

**Comment by marxide** [comment]
This issue was also reported in #11446. #11453 claims to have fixed this but it only appears fixed for circle glyphs drawn with `Figure.circle`, not any other glyph or with `.scatter` as provided in the example above.

**Comment by mattpap** [comment]
Still an issue on `branch-3.0`.
