### ISSUE TITLE
[FEATURE] Curved Arrow

### ISSUE THREAD

**Issue by DonCammne** [bokeh/bokeh#12072]
### Problem description

I noted that it is possible to create the model of a straight arrow but not a curved one.

### Feature description

I would like to have a model similar to Arrow but called CurvedArrow (for example) that takes in another argument called "radius" that describes the circular path of the arrow. The head of the arrow has the same direction of the end point.

### Potential alternatives

Another more complex solution can take in two arguments like "r_min" and "r_max" for a spiral path. The head of the arrow has the same direction of the end point.

### Additional information

I also posted a question regarding this issue on the Bokeh website: https://discourse.bokeh.org/t/curved-arrows/

**Comment by mattpap** [comment]
As of bokeh 3.0-dev, curved arrows can be achieved using glyph decorations (currently only implemented in arc and segment glyphs). See https://github.com/bokeh/bokeh/blob/branch-3.0/examples/plotting/file/trefoil.py as an example ([preview](https://user-images.githubusercontent.com/27475/113365025-51deef00-9355-11eb-8b62-a40e56e16918.png)).

**Comment by DonCammne** [comment]
Thanks, it's a very useful implementation. Do you have an idea when the 3.0 version will be released (stable and complete)? I'm working on a server not maintained by me, thus I cannot change the version.

**Comment by mattpap** [comment]
I will close this issue in favour of #13216.
