### ISSUE TITLE
[BUG] gap between adjacent patches with bokeh.models.Patches

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#12085]
### Software versions

Python version      :  3.9.12 (main, Apr  5 2022, 06:56:58)
IPython version     :  8.2.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /home/sroche/anaconda3/envs/bokeh-latest/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31

### Expected behavior

Not sure if this qualifies more as a bug, discussion, or feature request

When line_width=0, there should not be a line the background shows through between two adjacent patches

### Observed behavior

When line_width=0, there is a gap between adjacent patches (that share edges)

### Example code

```Python
import numpy as np

from bokeh.models import ColumnDataSource, Patches
from bokeh.plotting import figure
from bokeh.io import show

xpts = np.array([0, 0, 1, 1])
ypts = np.array([0, 1, 1, 0])

source = ColumnDataSource(dict(
        xs=np.array([(xpts+j) for i in range(5) for j in range(5)]),
        ys=np.array([ypts+i for i in range(5) for j in range(5)]),
    )
)

fig = figure(
    title=None, width=300, height=300,
    min_border=0,background_fill_color="red")

glyph = Patches(xs="xs", ys="ys", fill_color="white",line_width=0)
fig.add_glyph(source, glyph)
fig.ygrid.visible = False
fig.xgrid.visible = False
bokeh.io.show(fig)
```

### Screenshots

![image](https://user-images.githubusercontent.com/22297924/162515312-6863d0a8-f87e-4dcd-a256-03f80ba7787f.png)

**Comment by ianthomas23** [comment]
There isn't really anything that we can do about this. HTML canvas, and most other rendering engines, use a form of alpha blending that is really good for dealing with interpolation of images and textures but is less good in situations like this.

The standard workaround is to use a line of the same color as the fill, but this is no good if your alpha is less than 1 as the fill and line are rendered separately so you will end up with white lines around your pink patches.

**Comment by Anton-Le** [comment]
For me this is a major problem, as I have embarked on exploring my simulation datasets interactively, using xarray and holoviews, which for interactivity relies on Bokeh. Gaps between patches result, in my case, not only in a 'milky image', but in some aliasing artefacts.

When using the line of the same colour as the fill, is it possible to befine this for _every_ patch separately?

**Comment by bryevdv** [comment]
Yes, `line_color` is vectorizable for every glyph, including patches.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this with `noaction`

**Comment by tomchor** [comment]
I know this was closed already since at the time the issue wasn't addressable, but I'm wondering if with Bokeh 3.0 (which apparently reworked many things) the situation may have changed.

@bryevdv I was also wondering if you could post a MWE of the workaround you mentioned [here](https://github.com/bokeh/bokeh/issues/12085#issuecomment-1094152959). I'm new to Bokeh and could not figure out how to do that. Just like with @Anton-Le, I wanna use bokeh as I think it's a great tool, but the white lines are a serious limitation for my workflow.

Thanks!

**Comment by bryevdv** [comment]
hi @tomchor the comment means that the `line_color` property can be configured in exactly the same way as x or y coordinates, i.e. as a list or array of color values in a data source. For more discussion, please use our active community discourse for support questions: https://discourse.bokeh.org/
