### ISSUE TITLE
[BUG] notebook_url for running behind JupyterHub with jupyter-server-proxy not working anymore

### ISSUE THREAD

**Issue by tlvu** [bokeh/bokeh#12090]
### Software versions

Python version      :  3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
IPython version     :  8.2.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /opt/conda/envs/birdy/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  v16.13.1
npm version         :  8.1.2
Operating system    :  Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.10

### Expected behavior

Following intructions for Bokeh to work behind JupyterHub with jupyter-server-proxy at https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html#jupyterhub.

Expected displayed URL to be `https://medus.ouranos.ca/jupyter/user/lvu/proxy/5007`, got `http://localhost:5007`.

Seems to be regression from https://github.com/bokeh/bokeh/issues/7685 and https://github.com/bokeh/bokeh/pull/7686.

### Observed behavior

Got `http://localhost:5007`, instead of `https://medus.ouranos.ca/jupyter/user/lvu/proxy/5007`.

### Example code

```Python
! env |grep -e JUPYTERHUB_EXTERNAL_BASE_URL -e JUPYTERHUB_SERVICE_PREFIX

DASK_DISTRIBUTED__DASHBOARD__LINK=https://medus.ouranos.ca{JUPYTERHUB_SERVICE_PREFIX}proxy/{port}/status
JUPYTERHUB_SERVICE_PREFIX=/jupyter/user/lvu/
JUPYTERHUB_EXTERNAL_BASE_URL=https://medus.ouranos.ca

===============================

import panel as pn

def remote_jupyter_proxy_url(port):
    """
    Callable to configure Bokeh's show method when a proxy must be
    configured.

    If port is None we're asking about the URL
    for the origin header.
    """
    base_url = os.environ['JUPYTERHUB_EXTERNAL_BASE_URL']
    host = urllib.parse.urlparse(base_url).netloc

    # If port is None we're asking for the URL origin
    # so return the public hostname.
    if port is None:
        return host

    service_url_path = os.environ['JUPYTERHUB_SERVICE_PREFIX']
    proxy_url_path = 'proxy/%d' % port

    user_url = urllib.parse.urljoin(base_url, service_url_path)
    full_url = urllib.parse.urljoin(user_url, proxy_url_path)
    return full_url

srv = pn.panel(
    pn.widgets.FloatInput(name='an input one')
).show(port=5007, notebook_url=remote_jupyter_proxy_url)


Launching server at http://localhost:5007
```

### Screenshots

![Screenshot from 2022-04-13 22-20-17](https://user-images.githubusercontent.com/11966697/163301199-9d7c08bc-c649-4316-b222-c3a682ae17ed.png)

**Comment by bryevdv** [comment]
@tlvu That message is not coming from Bokeh, it is coming from Panel:

https://github.com/holoviz/panel/blob/30e8beed30f57bafa24ad973a6d94539bffbaf1e/panel/io/server.py#L774

Panel is a separate project with different maintainers. I would suggest you instead open this issue on the Panel repo. Alternatively, if you can provide a pure-Bokeh  [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), that would be something we could investigate. 

All that said, I am not that message, by itself, indicates any problem. That is coming from the server, and from the server's perspective it is running on localhost (behind the proxy). The `notebook_url` callable is to generate the appropriate connection string from the point of view of the client (in front of the proxy). I don't know that I would expect them to match up. 

cc @philippjfr

**Comment by bryevdv** [comment]
I guess I would also note that the very simple code to process callables in this context has not changed in 4 years:

<img width="986" alt="Screen Shot 2022-04-13 at 21 54 12" src="https://user-images.githubusercontent.com/1078448/163316250-fdb493d1-2b96-4fe9-9ba1-7973ca5ba074.png">

**Comment by tlvu** [comment]
@bryevdv 

> @tlvu That message is not coming from Bokeh, it is coming from Panel:
> 
> https://github.com/holoviz/panel/blob/30e8beed30f57bafa24ad973a6d94539bffbaf1e/panel/io/server.py#L774
> 

Oh sorry, I did not realized that.

> Panel is a separate project with different maintainers. I would suggest you instead open this issue on the Panel repo. 

Indeed, will try an issue on Panel side.

> Are you saying there is an actual issue, besides _just_ the message? If so, please describe _that_.

The issue is only with the display of the message.  The functionality works fine.

If I manually alter the URL in my browser to `https://medus.ouranos.ca/jupyter/user/lvu/proxy/5007/`, it works fine.

I basically do not want my users to have to remember to manually alter the display URL they got back from the code they launch.  Much less error-prone and much more user-friendly that way.

Closing this issue, thanks for your quick reply and clarification.

**Comment by tlvu** [comment]
FYI, started a post on Holoviz discourse: https://discourse.holoviz.org/t/how-to-customize-the-display-url-from-panel-serve-for-use-behind-jupyterhub-with-jupyter-server-proxy/3571
