### ISSUE TITLE
[Doc] update docs to reflect current installation behaviour

### ISSUE THREAD

**Issue by harmbuisman** [bokeh/bokeh#12103]
### Problem description

I noticed that when going through [Setting up a development environment — Bokeh 2.4.2 Documentation 1](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html)

When I run
python setup.py develop

It just builds BokehJS rather than give me the choice options. This is contrary to: " With either mode, Bokeh asks you how to install [BokehJS](https://docs.bokeh.org/en/latest/docs/user_guide/concepts.html#term-BokehJS)."  This was recently updated as per: https://discourse.bokeh.org/t/question-about-documentation/9107https://discourse.bokeh.org/t/question-about-documentation/9107

Docs need updating. Perhaps other parts of the section also need adjustment.

### Feature description

See above

### Potential alternatives

See above

**Comment by bryevdv** [comment]
@tcmetzger Do you have an suggested text for this?

**Comment by tcmetzger** [comment]
@bryevdv I believe this is already updated in the 3.0 docs: https://github.com/bokeh/bokeh/blob/branch-3.0/sphinx/source/docs/dev_guide/setup.rst#6-build-and-install-locally - we could backport that section of the docs in case we do another 2.4 release.

**Comment by tcmetzger** [comment]
This is an effect of the dev docs being part of the general docs, i.e. the deployed version of the dev docs (based on the most recent release, 2.4 in this case) is usually a little behind what is actually happening in the dev branch (branch-3.0 in this case).

**Comment by bryevdv** [comment]
@tcmetzger Weird I went to check the deployed `dev-3.0` docs and it seemed not to be updated, which is why I suggested making an issue. But maybe there was a caching issue and I was seeing an old version. I don't think it's worth the effort to backport, so I will close this issue nw.
