### ISSUE TITLE
Use channel instead of explicit version for GMap API?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12112]
Apparently Google has gotten much more aggressive about completely decommissioning "old" API versions (i.e they stop working entirely). Apparently the default version in 2.4.2 is now de-activated:

https://stackoverflow.com/questions/72056488/plot-points-in-google-map-with-python-with-google-api

Meaning that `gmap` now no-longer works at all out of the box in any released version of Bokeh. 

I guess nowadays there are "release channels" that can be asked for instead:

https://developers.google.com/maps/documentation/javascript/versions#quarterly-updates

So we could use `api_version = "quarterly"` as a default, instead of a pinned version. The risk there is that some new update from Google is incompatible with our current internal implementation. I am not sure what the best solution is here. It's pretty aggravating that a company with the vast resources of Google won't support a wide range APIs they release. 

in any event, the current fixed version in `branch-3.0` is already a few versions behind. If we don't switch to channels we should at least update that before release. We need to add documentation support about this aspect as well. cc @tcmetzger

**Comment by mattpap** [comment]
I think we use the most common API, that won't change between major releases. We also use very little of that API. So I'm all for this change, especially that I've been trying to keep the version updated, but given their policies, it's not quite doable.

**Comment by bryevdv** [comment]
There is also this:

> 3.45 After mid-May, this version will be deleted, and can no longer be used. Any attempt to load this version will be ignored, and you will receive your default channel instead.

So I *think* that starting with 3.45 (which is newer than what  Bokeh 2.4.2 specified) that attempts to use a decommissioned version will fall back to a "default" channel (quarterly? it's not clear where "your default channel" is specified). In that case, sticking to a specific version (newer than 3.45) might be OK. But all things considered I think I might still prefer just moving to `"quarterly"` as the default.
