### ISSUE TITLE
[FEATURE] Expose itemSelectText option on the MultiChoice widget

### ISSUE THREAD

**Issue by monadandan** [bokeh/bokeh#12115]
### Problem description

I have the problem where my options are getting split into two lines due to the "Press to select" text. I would like to remove the "Press to select" text so that the option text doesn't get split into two lines.
![problem_multichoice](https://user-images.githubusercontent.com/14826460/166173875-2b1a50f3-a75a-4881-8289-296f420d7eb3.png)
 

### Feature description

I would like to expose the `itemSelectText` option in the MultiChoice widget, which I see is available in [Choices.js](https://github.com/Choices-js/Choices).  This way, I can change the press to select text to an empty string.

### Potential alternatives

I'm not sure if there is another way I could adjust this option without this feature request. Please let me know if there is a workaround!

Another idea is to create some kind of dictionary where these additional, maybe less commonly used features could be given by the user. This would prevent the bokeh devs from having to address new feature requests to add these additional options.

An alternative to this would be to expose all the Choices.js options to the MultiChoice widget to prevent future feature requests, since this request is similar to issue #10525. 

Thank you!

**Comment by monadandan** [comment]
Update, I have found a workaround with CSS.

For context, I am working with bokeh 2.4.2.

With the following directory tree:
```
myapp
   |
   +---__init__.py
   +---main.py
   |---templates
   |    +---index.html
   |    +---styles.css

```

myapp/templates/styles.css

```
.bk-root .choices__list--dropdown .choices__item--selectable {
    padding-right: 0px;
}

.bk-root .choices__list--dropdown .choices__item--dropdown.choices__item {
    position: relative;
    padding: 2px;
    font-size: 12px;
}

.bk-root .choices__list--dropdown .choices__item {
    position: relative;
    padding: 2px;
    font-size: 12px;
}

.bk-root .choices__list--dropdown .choices__item--selectable:after {
    content: attr(data-select-text);
    font-size: 12px;
    opacity: 0;
    position: absolute;
    right: 10px;
    top: 50%;
    transform: translateY(-50%);
    visibility: hidden;
}
```

myapp/templates/index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {{ bokeh_css }}
    {{ bokeh_js }}
    <style>{% include 'styles.css' %}</style>
  </head>
  <body>
  {{ plot_div|indent(8) }}
  {{ plot_script|indent(8) }}
  </body>
</html>
```

last thing to do is add the css_classes to the widget

```
multichoice_y = MultiChoice(options=multi_choice_options, width=200, 
                            search_option_limit=9999, css_classes=['bk-root'])
```

From the terminal:

`bokeh serve --show myapp`

Make sure you are running from the folder that contains the directory myapp. Don't run from the myapp folder.

This is the result:
![multichoice solved](https://user-images.githubusercontent.com/14826460/166208739-c5e93b52-d125-4d16-81bf-30aa613bddde.png)

There is probably a more elegant way to do this, but I hope this helps anyone else that may run across this.

I'm not sure if this workaround should be a reason to not do the feature request though. Thanks--

**Comment by mattpap** [comment]
It's a really bad design on choices.js' side. The correct approach is to move the irrelevant text out of the way. For now we just remove the text altogether, because just exposing the option and setting it to `""` is insufficient to resolve the problem (there's padding that needs to be removed as well and there's not configuration option for that).
