### ISSUE TITLE
[BUG] Allow to extend vertically a TextAreaInput

### ISSUE THREAD

**Issue by maximlt** [bokeh/bokeh#12123]
### Software versions

Python version      :  3.8.12 (default, Oct 12 2021, 06:23:56) 
IPython version     :  7.30.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /Users/mliquet/miniconda3/envs/panel-dev38/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  v17.0.1
npm version         :  8.1.0
Operating system    :  macOS-10.16-x86_64-i386-64bit

### Expected behavior

The `TextAreaInput` doesn't seem to be able to resize vertically by dragging the resize handle. Also note that, since it might be related, the widget doesn't really have a flex-like behavior when the resize handle is moved horizontally. The widget will freely overlap other widgets and extend beyond its layout. See the GIF below.

### Observed behavior

![issue_bokeh_textareainput](https://user-images.githubusercontent.com/35924738/167429753-f62436c1-257f-4175-b609-d38d8d2c9e8f.gif)

### Example code

```Python
from bokeh.io import show
from bokeh.layouts import row
from bokeh.models import TextAreaInput

tai1 = TextAreaInput(rows=6, title="Label1")
tai2 = TextAreaInput(rows=6, title="Label2")

show(row(tai1, tai2, height=500, background='blue'))
```

**Comment by mattpap** [comment]
The existing layout doesn't pay attention to DOM node resize.

**Comment by maximlt** [comment]
Is it something that will be changed part of Bokeh 3.0?

**Comment by mattpap** [comment]
Yes, respecting DOM/CSS, in particular observing DOM node changes, is the main part of the layout redesign.
