### ISSUE TITLE
[BUG] LabelSet doesn't check type for text

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#12127]
### Software versions

Python version      :  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
IPython version     :  8.1.1
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /opt/conda/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v14.8.0
npm version         :  6.14.7
Operating system    :  Linux-5.10.0-8-amd64-x86_64-with-glibc2.31

### Browser name and version

Google Chrome Version 101.0.4951.64 

### Jupyter notebook / Jupyter Lab version

3.3.2

### Expected behavior

When using LabelSet with wrong types `bokeh` creates a broken figure. Expected is that either trys to parse the given values as `str` or throws a user friendly error message.

### Observed behavior

It the labels for a `LabelSet` have the wrong type (for example `int` or `float`) bokeh creates a plot without labels.
If the user interacts with the plot, it breaks apart.

|**created output**|**after interaction**|
|--|--|
|![No Labels](https://user-images.githubusercontent.com/68053396/168148455-67c8fe45-be62-445f-b4d1-f7b765560eae.PNG)|![Borken](https://user-images.githubusercontent.com/68053396/168148622-4debd016-608c-42a1-ad63-888a3f602459.PNG)|

### Example code

```Python
import pandas as pd
from bokeh.models import LabelSet, ColumnDataSource
from bokeh.plotting import figure, show, output_notebook
output_notebook()

df = pd.DataFrame({
    'a':[0,0,1,1],
    'b':[0,1,0,1],
    'c':[6,7,8,9],
    'color':['#777777', '#999999', '#aaaaaa', '#cccccc']
})

source= ColumnDataSource(df)

p = figure(
    x_range=(-0.5,1.5),
    y_range=(-0.5,1.5),
    width=300,
    height=300
)

p.rect(
    x="a",
    y="b",
    fill_color='color',
    line_color=None,
    width=1,
    height=1,
    source=source,
)
labels = LabelSet(
    x='a',
    y='b',
    text='c',
    text_align='center',
    y_offset=-7,
    source=source,
)
p.add_layout(labels)

show(p)
```

### Stack traceback or browser console output

There is no traceback but there are some logs in the browser console.

```
Uncaught (in promise) TypeError: this.text.split is not a function
    at x.paint (VM165 bokeh-2.4.2.min.js:285:4491)
    at v._v_canvas_text (VM165 bokeh-2.4.2.min.js:386:1677)
    at v.paint (VM165 bokeh-2.4.2.min.js:386:1206)
    at v._render (VM165 bokeh-2.4.2.min.js:234:1007)
    at v.render (VM165 bokeh-2.4.2.min.js:206:1562)
    at O._paint_levels (VM165 bokeh-2.4.2.min.js:519:11560)
    at O._actual_paint (VM165 bokeh-2.4.2.min.js:519:11015)
    at O.paint (VM165 bokeh-2.4.2.min.js:519:9879)
    at O.repaint (VM165 bokeh-2.4.2.min.js:519:9775)
    at VM165 bokeh-2.4.2.min.js:519:2616
```

### Screenshots

The wanted output would be this

![LabelSet](https://user-images.githubusercontent.com/68053396/168147331-0bfbe500-c326-4700-831d-97839ead4f9c.png)
 or an error message.

**Comment by bryevdv** [comment]
I am not sure what we can realistically do about this. We already have some folks complaining about existing validation overhead, looking for ways to reduce it, and this would go in the opposite direction. It's possible, in the special case of columns that are numpy arrays, we could perform a very quick check using the `dtype`. But for a plain Python list we would have to check every element of every list at every serialization and I am skeptical that is something we will decide to do. 

cc @bokeh/dev

**Comment by mattpap** [comment]
We do this coercion in `Text` glyph in bokehjs (for better or worse; I'm not a big supporter of doing so, but this was asked for before). @mosc9575, is there any specific reason for using `LabelSet` over `Text` glyph? Given that source driven annotations are a historical artifact, trying to be poor man's glyphs without actually implementing the glyph interface, they need to be deprecated and removed.

**Comment by bryevdv** [comment]
Upon further reflection I think I am OK with just doing a string conversion on numeric values on the BokehJS side.
