### ISSUE TITLE
[BUG] Updating FactorRange seems to "nest" graphs?

### ISSUE THREAD

**Issue by t-vi** [bokeh/bokeh#12139]
### Software versions

Python: 3.9
Bokeh: 2.3.0 and 2.4.3

### Browser name and version

Firefox

### Jupyter notebook / Jupyter Lab version

-

### Expected behavior

Running the code below should update the bar chart to three columns. (It would not update if I didn't set the factors to `[]` first).

### Observed behavior

The actual bar chart becomes smaller and smaller, as ifnesting.

### Example code

```Python
import bokeh
from bokeh.io import curdoc
from bokeh.models.widgets import Tabs
from bokeh.models import ColumnDataSource, OpenURL, TapTool, Panel, Div
from bokeh.plotting import figure, output_file, show, output_notebook
from bokeh.layouts import column
import bokeh.models.widgets
import bokeh.application
import bokeh.application.handlers.function
import bokeh.server.server


def make(doc):
    names = ["a", "b"]
    ds = ColumnDataSource(
        data=dict(names=names, vals=[3, 2])
    )

    fig = figure(
        x_range=names,
        y_range=(0, 5),  # height=350,
        title="foo",
        toolbar_location=None,
        tools="",
    )

    fig.vbar(
        x="names",
        top="vals",
        width=0.9,
        legend_field="names",
        source=ds,
    )

    fig.xgrid.grid_line_color = None
    fig.legend.visible = False

    def update():
        names = ["a", "b", "c"]
        ds.data = dict(names=names, vals=[3, 2, 1])
        fig.x_range.factors = []
        fig.x_range.factors = names

    
    doc.add_periodic_callback(update, 1000)
    doc.add_root(fig)
    

apps = {
    "/": bokeh.application.Application(
        bokeh.application.handlers.function.FunctionHandler(make)
    )
}

server = bokeh.server.server.Server(apps, port=5002)
server.run_until_shutdown()
```

### Screenshots

Here you can see how it looks. The outmost frame indicates the original size.
Then it iteratively gets smaller.

![image](https://user-images.githubusercontent.com/20787943/169711727-df51803a-0f7d-4031-95fd-ececb1cbf7aa.png)

**Comment by bryevdv** [comment]
@t-vi  am unable to reproduce any issue with your code with Bokeh 2.4.2 on OSX/Safari. I also do not have to (and would not advise) setting the factors to `[]` first.  Please double check that you are actually seeing this with version 2.4.3 (e.g. by printing the version in the script)

Addtitionally, as an FYI `server.run_until_shutdown()` is hight

**Comment by bryevdv** [comment]
I can't repro any issue with version 2.3.0 either, with either Safari or Firefox.

**Comment by t-vi** [comment]
Hi Bryan, thank you for the prompt reply. This ist with 2.4.3 indeed.
Given that you cannot reproduct,aybe it os a race condition. I'm seeing this on a relatively slow computer...

Best regards

Thomas

**Comment by bryevdv** [comment]
@t-vi I would expect BokehJS to reach a quiescent state either way, but you could try swapping the order of the data source and range updates. Those are the only two things that could be contention. Please also provide more detailed system/browser/etc version information

**Comment by t-vi** [comment]
It seems the repro is incomplete and there are additional NaN or Inf at work to trigger the issue. Maybe the answer is "don't use NaN then". I'm closing this. If there were interest, I could try to update the repro and reopen.

**Comment by t-vi** [comment]
P.S.: Thank you for your help and my apologies for the noise.
