### ISSUE TITLE
[BUG] CDN links broken for https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-2.0.1.min.js

### ISSUE THREAD

**Issue by mangelozzi** [bokeh/bokeh#12144]
### Software versions

N/A

### Browser name and version

Chrome 102

### Jupyter notebook / Jupyter Lab version

n?a

### Expected behavior

this link does not work:
https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-2.0.1.min.js

The link is reference in: https://docs.bokeh.org/en/latest/docs/first_steps/installation.html (at the bottom of the page)

### Observed behavior

js file not loaded

### Example code

```Python
no code required
```
```


### Stack traceback or browser console output

N/A

### Screenshots

N/A

**Comment by bryevdv** [comment]
There is no mathjax bundle for version 2.0.1 so this is just an issue with the example links. The simplest solution is just to update the versions in the links, e.g. to 2.4.3 cc @tcmetzger

**Comment by tcmetzger** [comment]
I made PR #12146 as suggested by @bryevdv.
@mangelozzi Thanks for bringing this up!
