### ISSUE TITLE
[BUG] Mathjax 3.2.1 breaks Bokeh

### ISSUE THREAD

**Issue by stefanv** [bokeh/bokeh#12142]
### Software versions

Python version      :  3.8.12 (default, Jan 21 2022, 18:31:05) 
IPython version     :  8.0.1
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /home/stefan/envs/skyportal/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  v18.2.0
npm version         :  8.3.2
Operating system    :  Linux-5.15.37-1-lts-x86_64-with-glibc2.2.5

### Expected behavior

I apologize for the extreme vagueness of this report; I don't have minimally reproducible code yet.

We have observed problems running bokeh with Mathjax 3.2.1, just released. We worked around the issue by pinning `mathjax-full` to `3.2.0`.

### Observed behavior

Lots of our tests failed.

### Example code

```Python
None as yet.
```

**Comment by mattpap** [comment]
bokehjs comes with its own bundle of mathjax, which is supposed to be self-contained and isolated from affecting and being affected by the environment. If a copy of mathjax provided by you is somehow being picked up by bokehjs or iterfers with our copy, then perhaps our assumptions regarding bundling of mathjax may be wrong.

**Comment by stefanv** [comment]
For some reason, I can't find the mathjax reference in the bokeh source repo.  But in the built version of bokehjs (which we import via webpack), I can see in `package.json`:

```
    "mathjax-full": "^3.2.0",
```

Mathjax just made a patch release, 3.2.1, that includes a year's worth of changes, and I believe that these are not compatible with bokeh.

**Comment by mattpap** [comment]
> For some reason, I can't find the mathjax reference in the bokeh source repo.

https://github.com/bokeh/bokeh/blob/95b2a74ff463cfabdf9e3390951fa380166e6691/bokehjs/src/lib/package.json#L24

> (...) which we import via webpack (...)

Now I remember that you bundle bokehjs on your own, so this is were a different version of mathjax can slip in. I will upgrade mathjax and see what's up with the recent changes.

**Comment by stefanv** [comment]
Ah, interesting: that file only lives on certain branches, not on main:

https://github.com/bokeh/bokeh/blob/main/bokehjs/src/lib/package.json

So I presume it is added prior to a specific release.

**Comment by mattpap** [comment]
We don't use `main` branch for development, we just sync it with the most recent stable branch if we remember. You need to look into `branch-x.y` branches, specifically `branch-2.4` and `branch-3.0`.

**Comment by mattpap** [comment]
The problem was on the build system level. They made their single codebase work both on node and the web via a customized webpack build (determining the version number of the library). It's seriously unfortunate to have this kind of change incorporated in a patch release. In general I'm not in favour of their approach, as it makes it tedious to do custom bundling of their code. I'm not sure if the fix in PR #12148 will really help your use case @stefanv, as you may need to define `PACKAGE_VERSION` global in your webpack config (see https://github.com/mathjax/MathJax-src/blob/master/ts/components/version.ts#L25). In fact, you can do that in the iterm; no need to wait for a new bokeh release.

**Comment by stefanv** [comment]
Thank you very much for investigating @mattpap!

**Comment by stefanv** [comment]
> It's seriously unfortunate to have this kind of change incorporated in a patch release.

Many raised eyebrows over this one.
