### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by mkoz92** [bokeh/bokeh#12143]
### Problem description

Lack of inverted Triangle pin and inverted triangle dot

### Feature description

Add the possibility to create a marker for inverted triangles with pins and dots. 

### Potential alternatives

None

**Comment by bryevdv** [comment]
@mkoz92 It's not clear that adding `inverted_triangle` was a good decision in the first place. The standard `triangle` glyph accepts an `angle` property, so it can be inverted just by supplying the correct rotation. I think it is unlikely we would consider adding `inverted_triangle_dot` cc @bokeh/dev

**Comment by ianthomas23** [comment]
We definitely should not add new `inverted_*` markers.
