### ISSUE TITLE
[BUG] Examples/Apps/Stocks has broken URL 

### ISSUE THREAD

**Issue by shenzj1994** [bokeh/bokeh#12145]
### Software versions

Python 3.10.4 Bokeh 3.0

### Browser name and version

Safari

### Expected behavior

Stocks sample should download necessary data and run.

### Observed behavior

In 
[bokeh](https://github.com/bokeh/bokeh)/[examples](https://github.com/bokeh/bokeh/tree/branch-3.0/examples)/[app](https://github.com/bokeh/bokeh/tree/branch-3.0/examples/app)/[stocks](https://github.com/bokeh/bokeh/tree/branch-3.0/examples/app/stocks)/download_sample_data.py 

    zip_file = 'http://quantquote.com/files/quantquote_daily_sp500_83986.zip'

This link is broken and stopped the sample from running.

### Example code

```Python
python examples/app/stocks/download_sample_data.py
```

**Comment by bryevdv** [comment]
cc @bokeh/dev we don't have the rights to distribute those files ourselves (that's why there was a separate download script, rather than the data just being in our sampledsta). If we can't find suitable alternative data to use, we will simply have to remove this example.

**Comment by shenzj1994** [comment]
That is a great example so I think it would be a loss if we just remove it. 
Maybe consider adding some mock data instead?

**Comment by bryevdv** [comment]
Synthetic data would also be an acceptable solution, but in that case it might be nicer if the time series can be dynamically generated on demand. @shenzj1994 Would you be interested to create a function to generate synthetic data for this example?

**Comment by shenzj1994** [comment]
Sure. I can try that.

**Comment by shenzj1994** [comment]
Hi @bryevdv, how about making a similar script but download the data from Yahoo Finance instead? Could there be any licensing issue?
I can still making it to generate random synthetic data but I guess the real-world stock data is better.

**Comment by bryevdv** [comment]
@shenzj1994 It's a possibility, but as long as we are working on this at all, I do actually have a preference to get rid of the download script altogether. 

* The example itself could generate data on the fly, no need to interact with the filesystem at all
* A `bokeh.sampledata` module (which is that standard data interface for almost every other example) could generate the data. It could either return new synthetic data every time, or generate one dataset and save it in the same place that all the other sampledata gets saved. 

Also:

> Could there be any licensing issue?

There definitely *could*. I don't know for sure. Someone would have to look at the detailed terms and make a case that we would be under acceptable use terms.

**Comment by shenzj1994** [comment]
@bryevdv Got it. I will try resolve this issue with synthetic data then.

**Comment by alv2017** [comment]
Hi,
I suggest to use **yfinance** package for data extraction, https://github.com/ranaroussi/yfinance.
It will be possible to pull the data interactively from Yahoo, and get the results. 

On top of that it still will be possible to demonstrate how the hook **on_server_loaded** works.
