### ISSUE TITLE
Links for download badges in readme don't go anywhere

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12150]
The two download badges in the README.md link to https://docs.bokeh.org/en/latest/docs/installation.html but there is no such page. These links should be updated to point to a page that exists, presumably something to do with the installation instructions for conda/pip as appropriate.

Should also check all the other badge links are OK.

![link](https://user-images.githubusercontent.com/580326/171351843-a2d7ce26-e3f9-4895-85f9-3c275aae0dc8.png)

**Comment by mattpap** [comment]
https://docs.bokeh.org/en/latest/docs/installation.html intersetingly enough points to an empty page, and there is one for it in docs' source, why? It either should be a 404 as for any other invalid link, or a redirect to the installation guide.
