### ISSUE TITLE
Update docs for new Tooltip functionalities

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#12168]
Based on #12154, we need to update the docs. From a first glance, this should encompass at least some updates to the User Guide (including examples) and probably a stand-alone example as well.

With Tooltips now being a first class model, we could even think about creating a dedicated tooltips sub-chapter under 'Making interactions' (or somewhere else)!

**Comment by bryevdv** [comment]
> we could even think about creating a dedicated tooltips sub-chapter 

👍 I think we should definitely have a dedicated sub-chapter. There are several features that need to be demonstrated or at least explained individually

I would really like to show off the inspector somewhere as well.
