### ISSUE TITLE
irregular heatmaps

### ISSUE THREAD

**Issue by srepmub** [bokeh/bokeh#12165]
### Problem description

I am wondering if it is possible to easily create an 'irregular' heatmap, meaning with an grid with irregular x and y coords/edges.  preferrably also using numpy instead of pandas. for example something like:

![heatmap](https://user-images.githubusercontent.com/1583248/172801309-39e01ef9-bd33-4eb8-a95d-0b0d68d0da49.png)

this is easy to do in plotly (just pass a 2d numpy array and x- and y-coords), and also a very common thing I think.. if it is already easily possible with bokeh, perhaps an extra example/gallery entry would be nice to have? (all I can find is regular grids).

### Feature description

see problem description

### Potential alternatives

see problem description

**Comment by bryevdv** [comment]
cc @ianthomas23 @jbednar since we recently submitted a grant proposal that may touch on this. 

@srepmub It would be helpful if you could add considerably more detail, e.g. actual example code that you would like to be able to write, a real data source to consider for testing and development, etc.

**Comment by philippjfr** [comment]
If this is about actual irregular sampling then the best current approach is simply to draw independent vectorized quads. It's what we use for the [`QuadMesh` element in HoloViews](http://holoviews.org/reference/elements/bokeh/QuadMesh.html)

**Comment by jbednar** [comment]
Right, but in the example image the irregularity is actually only in whether the grid cell is populated or not; agreed that supporting truly irregular grids is also useful in Bokeh (though already available for Bokeh in HoloViews).

**Comment by bryevdv** [comment]
This is why I'm hoping @srepmub as code/data and details. As it is, it's not clear to me which case is being asked about.

**Comment by srepmub** [comment]
thanks for all the comments. it's not about nan values, but about irregular cell sizes (based on 1-dim x and y coords/edges). I will add example plotly. code.

**Comment by bryevdv** [comment]
@srepmub Actually in that case I agree with @philippjfr and this should just be a matter of using vectorized quads (or possibly one of the other "rect"-like glyphs, depending on your data). But helping with that is a support matter, not appropriate for the GitHub tracker. Please open a topic on our [Discourse site](https://discourse.bokeh.org).
