### ISSUE TITLE
swap band axes

### ISSUE THREAD

**Issue by srepmub** [bokeh/bokeh#12166]
### Problem description

for Band I was unable to find out how to make lower/upper work horizontally, like this:

![band](https://user-images.githubusercontent.com/1583248/172802811-ce1f0857-4fef-416c-a088-d471e877c760.png)

pretty sure with plotly you can swap the band 'direction'.

### Feature description

see problem description

### Potential alternatives

see problem description

**Comment by mattpap** [comment]
Set `band.dimension = "width"`. For usage questions, I will refer you to https://discourse.bokeh.org/.
