### ISSUE TITLE
[FEATURE] Batch rendering of many glyphs on the same plot

### ISSUE THREAD

**Issue by Kadek** [bokeh/bokeh#12171]
### Problem description

I am experimenting with the following code. We plot 10 lines with their own datasources on one plot. The streaming happens periodically every second for all lines. Each line has a different amount of points generated within this one second.

```
from bokeh.layouts import column
from bokeh.plotting import figure, curdoc
from bokeh.models import ColumnDataSource, Dropdown

import numpy as np
import time

class Line:
	def __init__(self, doc, plot, waiting_time):
		self._current_x = time.monotonic()
		self._current_y = 0
		self._new_points = dict(x=[], y=[])
		self._source = ColumnDataSource(data=dict(x=[], y=[]))

		plot.line(source=self._source)
		doc.add_periodic_callback(self._generate_point, waiting_time)

	def _generate_point(self):
		self._current_x = time.monotonic()
		self._current_y += np.random.normal()

		self._new_points["x"].append(self._current_x)
		self._new_points["y"].append(self._current_y)

	def stream(self):
		self._source.stream(self._new_points)

		self._new_points["x"].clear()
		self._new_points["y"].clear()

doc = curdoc()

p = figure(width=300, height=300, tools="pan,reset,save", y_axis_location="right")
lines = []
for i in range(1, 11):
	lines.append(Line(doc, p, 100*i))

def stream_point():
	for line in lines:
		line.stream()

menu = [("Item 1", "item_1"), ("Item 2", "item_2"), ("Item 3", "item_3")]
dropdown = Dropdown(label="Dropdown button", menu=menu)

doc.add_periodic_callback(stream_point, 1000)
doc.add_root(column(p, dropdown))
```

The problem here is that after some time the browser spends so much time rendering the plot that the dropdown button becomes unusable.

### Feature description

Taking a look at the profiling tools that Firefox offers I can spot that for every time the plot receives a websocket message it redraws the whole plot. You can see on the picture the black line (websocket message) followed by a brown line (rendering).

![image](https://user-images.githubusercontent.com/2953645/173625774-8d541977-366b-47b1-86f5-ed87189cd532.png)

What would be really great and would solve my problem here is to trigger rendering only after the last websocket message. Since my update loop is self contained I think the simplest solution would be to give me a possibility to trigger the rendering myself.

Like so
```
plot(automatic_redraw=False)

def stream_point():
	for line in lines:
		line.stream()
        plot.redraw()
```
or
```
def stream_point():
        plot.render_on_update =False
	for line in lines:
                if is_last_line():
                        plot.render_on_update =True
		line.stream()
```

### Potential alternatives

Another idea that comes to my mind is to set some kind of timer on the first received stream message and don't trigger rendering. While the timer is running all next updates are processed but also don't trigger rendering. Once the timer goes it rerenders the plot. On the next received stream message we start from the beginning.

### Additional information

I am happy to look into implementing one of those myself since ideally it should be a simple change. Not sure though if those proposals don't break some design principle of bokeh.

**Comment by bryevdv** [comment]
I'll give my own thoughts, but it will be good to get more input from @bokeh/dev 

I'll start by saying I do see the need  for this is some specific use-cases. I do think the changes and scope should be made absolutely as narrowly as possible. Along those lines I would propose:

* Using a new property, e.g `plot.pause_rendering = True`

   Adding a new boolean property is a trivial few lines to accomplish, while intersecting with nothing else. 

* Set up BokehJS internal callbacks to call existing JS `pause` / `unpause` as appropriate:

    https://github.com/bokeh/bokeh/blob/6f1e39a2a852f2b026a43004d93a99b3b73398a9/bokehjs/src/lib/models/plots/plot_canvas.ts#L105-L119

That seems like it will satisfy the need in a handful of lines of code, and most importantly, not add any sort of special casing to normal Bokeh eventing (either protocol eventing, or internal)

**Comment by bryevdv** [comment]
I had suggested trying that, but don't think `hold` will suppress multiple renders in the same plot when multiple CDD are updated.

**Comment by Kadek** [comment]
I had a small bug in the original post and the first line was generating points with 0s interval. I also updated the firefox profile since the issue of staggering renders is more visible in this case.

I did try using the doc.hold in my original project and I could see the same issue.
Interestingly, enough when I try using doc.hold() in this example my plot freezes somewhere in the middle of the first update or before plotting anything and complains that is cannot set initial ranges.

New code
```
from bokeh.layouts import column
from bokeh.plotting import figure, curdoc
from bokeh.models import ColumnDataSource, Dropdown

import numpy as np
import time

class Line:
	def __init__(self, doc, plot, waiting_time):
		self._current_x = time.monotonic()
		self._current_y = 0
		self._new_points = dict(x=[], y=[])
		self._source = ColumnDataSource(data=dict(x=[], y=[]))

		plot.line(source=self._source)
		doc.add_periodic_callback(self._generate_point, waiting_time)

	def _generate_point(self):
		self._current_x = time.monotonic()
		self._current_y += np.random.normal()

		self._new_points["x"].append(self._current_x)
		self._new_points["y"].append(self._current_y)

	def stream(self):
		self._source.stream(self._new_points)

		self._new_points["x"].clear()
		self._new_points["y"].clear()

doc = curdoc()

p = figure(width=300, height=300, tools="pan,reset,save", y_axis_location="right")
lines = []
for i in range(1, 11):
	lines.append(Line(doc, p, 100*i))

def stream_point():
	doc.hold()
	for line in lines:
		line.stream()
	doc.unhold()

menu = [("Item 1", "item_1"), ("Item 2", "item_2"), ("Item 3", "item_3")]
dropdown = Dropdown(label="Dropdown button", menu=menu)

doc.add_periodic_callback(stream_point, 1000)
doc.add_root(column(p, dropdown))
```

![image](https://user-images.githubusercontent.com/2953645/173626575-7349017d-64f8-452c-a91b-bccd47e5006b.png)

**Comment by Kadek** [comment]
I made a proposal for an implementation here https://github.com/bokeh/bokeh/pull/12236

The following code tests the results:
```
from bokeh.layouts import column
from bokeh.plotting import figure, curdoc
from bokeh.models import ColumnDataSource, Dropdown

import numpy as np
import time

class Line:
	def __init__(self, doc, plot, waiting_time):
		self._current_x = time.monotonic()
		self._current_y = 0
		self._new_points = dict(x=[], y=[])
		self._source = ColumnDataSource(data=dict(x=[], y=[]))

		plot.line(source=self._source)
		doc.add_periodic_callback(self._generate_point, waiting_time)

	def _generate_point(self):
		self._current_x = time.monotonic()
		self._current_y += np.random.normal()

		self._new_points["x"].append(self._current_x)
		self._new_points["y"].append(self._current_y)

	def stream(self):
		self._source.stream(self._new_points)

		self._new_points["x"].clear()
		self._new_points["y"].clear()

doc = curdoc()

p = figure(width=300, height=300, tools="pan,reset,save,box_zoom", y_axis_location="right")
lines = []
for i in range(1, 11):
	lines.append(Line(doc, p, 10*i))

def stream_point():
	p.hold_render=True
	for i, line in enumerate(lines):
		if i == len(lines) - 1:
			p.hold_render=False
		line.stream()

menu = [("Item 1", "item_1"), ("Item 2", "item_2"), ("Item 3", "item_3")]
dropdown = Dropdown(label="Dropdown button", menu=menu)

doc.add_periodic_callback(stream_point, 1000)
doc.add_root(column(p, dropdown))
```

We can see in the profiler that rendering is only triggered after the last DOMEvent
![image](https://user-images.githubusercontent.com/2953645/179357108-851eb4c5-50ae-49cd-b949-931746ab8683.png)

If we comment out the lines where we change `hold_render` then the rendering happens all the time
![image](https://user-images.githubusercontent.com/2953645/179357076-b3a5b5a0-c24c-464f-86aa-129b34c315b0.png)
