### ISSUE TITLE
[FEATURE] Add support for text outlines with annotations

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#12179]
### Problem description

Using text annotations on heatmaps is insufficient as text may become unreadable if the text color matches the heatmap color.
This problem is also described here:
https://stackoverflow.com/questions/60870478/best-color-to-annotate-against-viridis

### Feature description

Allow text to have an outline with a different color (i.e. see here https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/strokeText).
The major advantage of stroke text is that it allows text to be readable no matter the background.

### Potential alternatives

Using the existing annotation background option which has the downside that data may become obscured.

**Comment by bryevdv** [comment]
This seems like a reasonable and valuable ask, so I will tentatively triage as `feature`. Ideally we can add properties to the text propoerties mixins in one place:

https://github.com/bokeh/bokeh/blob/df8d2d1e101a663476ef756ed10957ab56b398fc/bokeh/core/property_mixins.py#L318-L356

And then add an optional `strokeText` step everywhere there is also already a `fillText` call.  But there may be subtleties to hash out, so some investigation will be required (e.g. I think currently a null `fillColor` suppresses all text rendering, can we keep that convention?)
