### ISSUE TITLE
make bokeh-server gunicorn friendly

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#1217]
gunicorn is the most likely candidate for production deployments of bokeh server.  We just need to provide a function which returns a wsgi app, which gunicorn can call.

typically this is either done by giving gunicorn a command line argument with a code snippet that constructs the appropriate wsgi app, http://stackoverflow.com/questions/8495367/using-additional-command-line-arguments-with-gunicorn

Or by giving bokeh-server the option to read all of the things we currently specify via cmdline from a config file

**Comment by damianavila** [comment]
I think this was closed by #1777, if I am missing something else, please reopen it...
