### ISSUE TITLE
[BUG] HTML title not updated in jinja template

### ISSUE THREAD

**Issue by mpnunez** [bokeh/bokeh#12182]
### Software versions

Python version      :  3.6.9 (default, Mar 15 2022, 13:55:28) 
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.3.3
BokehJS static path :  /home/marcel/Coding/projects/bokeh_stuff/bokeh-bug/.venv/lib/python3.6/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system: Ubuntu 18.04.6 LTS

### Browser name and version

Google Chrome 102.0.5005.61 (Official Build) (64-bit)

### Expected behavior

I expected the jinja template to substitute my custom string for `title` into the base template and render the HTML page with the custom string as the title in the tab.

The documentation on https://docs.bokeh.org/en/latest/docs/user_guide/embed.html shows this line

```
<title>{% block title %}{{ title | e if title else "Bokeh Plot" }}{% endblock %}</title>
```

So I would expect to be able to set the page title by supplying the `title` variable to the jinja template as

```
curdoc().template_variables.update(title="Custom title")
```

Even when I override the entire "title" jinja block, it still fails to change the page title.

### Observed behavior

Bokeh rendered the content, but the HTML page title remained the default "Bokeh Application".

### Example code

```Python
`main.py` used in bokeh server

from bokeh.plotting import curdoc
from bokeh.models.widgets import Paragraph

paragraph = Paragraph(
    text="Example Bokeh content", width=200, height=100
)

curdoc().add_root(paragraph)
curdoc().template_variables.update(title="Custom title")
```
```


### Stack traceback or browser console output

_No response_

### Screenshots

![bokeh-screenshot](https://user-images.githubusercontent.com/15945650/174686809-243096ae-cb2d-4672-aca8-afd75d1a3c08.png)

**Comment by bryevdv** [comment]
Title is set handled programmatically:
```
curdoc().title = "My Title"
```

**Comment by mpnunez** [comment]
Thank you. I see it here now: https://docs.bokeh.org/en/latest/docs/reference/document.html#bokeh.document.Document
