### ISSUE TITLE
[FEATURE] Allow `embed_item` to optionally take an element instead of an ID

### ISSUE THREAD

**Issue by pngwn** [bokeh/bokeh#12181]
### Problem description

`Bokeh.embed_item(config, id_string)` uses `getElementById` under the hood. This is fragile and failing for me because the element I wish to attach to is inside the Shadow DOM which is not queryable from BokehJS's context. 

### Feature description

`Bokeh.embed_item(config, id_string)` should optionally take either a string `id` or an `element` reference, skipping the `getElementById` call if it is an element reference.

### Potential alternatives

There are a few hacks involving instantiating Bokeh outside of the Shadow DOM and copying across but they are bad. 

I can fork and patch the library but I'd rather not.

### Additional information

I work on https://gradio.app/ and we are trying to make Bokeh work.

Not sure if this is worth a separate issue, but would be good if we didn't need to use the CDN to make use of the Bokeh scripts. I'm not sure if they are published to npm but they should be published or documented if they are already there. Attaching everything to the window is also not ideal.

**Comment by pngwn** [comment]
Happy to make a PR if this is something you are interested in, it would not be a breaking change and would have no impact on existing users.

**Comment by bryevdv** [comment]
@pngwn  see https://www.npmjs.com/package/@bokeh/bokehjs

> Happy to make a PR if this is something you are interested in, it would not be a breaking change and would have no impact on existing users. 

Seems reasonable change, we would be happy to consider a PR.
