### ISSUE TITLE
[BUG] Div with stretch_width doesn't stretch

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#12205]
### Software versions

Python version      :  3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0]
IPython version     :  8.4.0
Tornado version     :  6.1
Bokeh version       :  3.0.0dev8+4.g6eb8cbb95
BokehJS static path :  /home/tcm/github/bokeh/bokeh/server/static
node.js version     :  v16.14.2
npm version         :  8.5.0
Operating system    :  Linux-5.13.0-51-generic-x86_64-with-glibc2.31

### Browser name and version

Chromium Version 103.0.5060.53, Firefox 102.0

### Expected behavior

Creating a Div with `sizing_mode="stretch_width"`, and `style = {"border": "1px solid red"}`, I'd expect so see a box with a red border that spans the available width of the screen (similar to what I see with `figure(sizing_mode="stretch_width")`.

### Observed behavior

The div is only as wide as the text content inside of it, it does not stretch to the full width.

A workaround is to add `"width": "100%" `to the Div's `style` property - this way, the div does stretch as expected!

### Example code

```Python
from bokeh.models import Div, Column
from bokeh.plotting import figure, show

div1 = Div(
    text="Bokeh",
    sizing_mode="stretch_width",
    style = {"border": "1px solid red"},
    )

plot = figure(sizing_mode="stretch_width")
plot.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5])

show(Column(div1, plot, sizing_mode="stretch_width"))
```

### Screenshots

The div with the red border is only as wide as required by the content, while the plot stretches to the available width, as expected.

![image](https://user-images.githubusercontent.com/39711796/176775160-4e90028d-750c-4ca1-b1c0-ebd73514d120.png)

**Comment by bryevdv** [comment]
tentatively moving to 3.0 since it is layout-related
