### ISSUE TITLE
Call to `show()` not displaying figure in IPython notebook

### ISSUE THREAD

**Issue by fonnesbeck** [bokeh/bokeh#1221]
When working through some of the Bokeh examples/tutorials, I frequently run into the issue that the plot does not show up in the IPython notebook after calling `show()`. In each case, I have called `output_notebook()`. Here is a screen shot:

![screenshot](http://d.pr/i/ougB+)

It appears that no output is produced, either in the notebook or elsewhere. Strangely, even restarting the kernel does not fix the problem. Sometimes shutting down the notebook temporarily cures the problem, but not all the time.

I am running Bokeh 0.6 on OS X 10.9.4 and Python 2.7.6.

**Comment by damianavila** [comment]
Since there is no update so far, I will close it, please @fonnesbeck reopen it if you see the behaviour again. Thanks!
