### ISSUE TITLE
[BUG] Legends inactive_fill_alpha not working

### ISSUE THREAD

**Issue by rdmtinez** [bokeh/bokeh#12225]
### Software versions

Python version      :  3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) 
IPython version     :  8.0.1
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  /home/rdmtinez/projects/environments/pdm39/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.3

### Browser name and version

Chrome: Version 103.0.5060.66 (Official Build) (64-bit)

### Expected behavior

Legends inactive_fill_alpha should dim the glyph in the legend to the appropriate value

### Observed behavior

Assigning Legend's inactive_fill_alpha instead voids the default value and sets the the glyph's alpha to 1 (at least visually it does)

### Example code

```Python
import numpy as np

from bokeh.plotting import figure, output_file, show


def make_legend(title, items):
    legend = Legend(
        title=title,
        title_standoff=0,
        items=items,
        click_policy="hide",    # <- click policy 'hide' acts on visible in renderer
        label_text_font_size="8pt",
        spacing=0,
        inactive_fill_alpha=0.05, # <- default is 0.7, but any value here sets alpha as 1 (hide to see defualt)
    )
    
    return legend



x = np.linspace(0, 4*np.pi, 100)
y = np.cos(x)

p = figure(height=300)

# create two renderers with legend labels and designate one visible=False
main = p.circle(x, y, visible=False)
aux = p.line(x, 2*y, line_dash=[10, 20], line_color="orange", line_width=2)

# set legend label visibility for second renderer to False
legend = make_legend("Legend", items=[("Main", [main]), ("Auxillary", [aux])])

p.add_layout(legend)
show(p)
```

### Stack traceback or browser console output

It does not result in an error

### Screenshots

With Legend's inactive_fill_alpha=0.05 and 'main' visible=False
![image](https://user-images.githubusercontent.com/32708833/177951972-4ca7f851-bd17-4a0a-a489-054f600d2683.png)

With Legend's inactive_fill_alpha **not** set and 'main' visible=False
![image](https://user-images.githubusercontent.com/32708833/177952367-c3b08666-4ba0-4480-b95a-7a09619f6271.png)

With Legend's inactive_fill_alpha **not** set and 'main' visible=False, **but** the legend's Main glyph tapped
![image](https://user-images.githubusercontent.com/32708833/177952738-531b583d-c6b4-4ae8-a891-c1c7e28aebad.png)

**Comment by bryevdv** [comment]
@rdmtinez this is working as intended. The important part of the reference docs:

> The fill alpha for the legend item style when inactive. ***These control an overlay on the item that can be used to obscure it when the corresponding glyph is inactive (e.g. by making it semi-transparent).***

SO, if you the legend item to be "more faded out" you should make the overlay alpha *more opaque*, i.e. the opposite of what you have done above.
