### ISSUE TITLE
[BUG] output_file() documentation is not consistent

### ISSUE THREAD

**Issue by axil** [bokeh/bokeh#12237]
### Software versions

Python version      :  3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
IPython version     :  7.30.1
Tornado version     :  6.0.3
Bokeh version       :  2.4.3
BokehJS static path :  c:\utilities\development\python37-64\lib\site-packages\bokeh\server\static
node.js version     :  v16.15.1
npm version         :  8.11.0
Operating system    :  Windows-10-10.0.19041-SP0

### Expected behavior

The page '[First steps 7](https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_7.html)' says:

> filename: the filename for the HTML file. If you don’t supply a file name, Bokeh will use the file name of your python file as a filename for the HTML file it creates.

### Observed behavior

Yet when I run `output_file()` without any arguments it says:

``` python
TypeError: output_file() missing 1 required positional argument: 'filename'
```

### Example code

```Python
from bokeh.io import output_file

output_file()
```

**Comment by bryevdv** [comment]
Well, what the text means is: “if you don’t supply a file name *by not calling output _file at all *” but I guess that could be worded more clearly. cc @tcmetzger

**Comment by axil** [comment]
For me it would make sense to make it nullable. Because otherwise it is possible to switch back to automatic naming of the filename.

**Comment by tcmetzger** [comment]
@axil Thanks for bringing this up - the docs should definitely reflect the behavior of that function, so I made #12241 to fix that.

I'll leave this issue open as a discussion regarding the question if and how we want some kind of functionality to go back to the default file naming after calling `output_filename()`.

**Comment by bryevdv** [comment]
[`reset_output`](https://docs.bokeh.org/en/latest/docs/reference/io.html#bokeh.io.reset_output) is for clearing output modes, and works with all output modes. I'm not sure we need a second way that only works with one mode.

**Comment by axil** [comment]
My use case is like this: I'm writing a bokeh wrapper for jupyter notebook. `output_notebook` is the default mode there (as it would probably be for any other jupyer notebook wrapper). `output_file` switches to output to a file with a specified name. To switch to automatically named file I have to write `reset_output`. To get both outputs, I need `reset_output` followed by `output_notebook` which is somewhat counter intuitive.

**Comment by bryevdv** [comment]
@axil TBH it seems like rather than using `output_file` at all, instead it would be better to simply call `save` whenever you want a file to be saved. It's more explicit, and AFAICT would be the same lines of code (swapping multiple `output_file` calls for the same number of `save` calls).

**Comment by axil** [comment]
The wording of the updated documentation is not complete: https://github.com/bokeh/bokeh/pull/12241#pullrequestreview-1045049182
