### ISSUE TITLE
[BUG] ContourColorBar does not support theme

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12250]
### Software versions

Python version      :  3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
IPython version     :  8.4.0
Tornado version     :  6.2
Bokeh version       :  3.0.0dev10+16.g9e7ea795d
BokehJS static path :  /home/iant/github/bokeh/bokeh/server/static
node.js version     :  v16.14.2
npm version         :  8.5.0
Operating system    :  Linux-5.11.0-37-generic-x86_64-with-glibc2.31

### Browser name and version

Occurs in all browsers

### Expected behavior

Setting of dark theme should be respected by ContourColorBar.

### Observed behavior

ContourColorBar is displayed using default light theme.

### Example code

```Python
from bokeh.palettes import Spectral5
from bokeh.plotting import curdoc, figure, show
import numpy as np

curdoc().theme = 'dark_minimal'

p = figure(width=400, height=200)

x, y = np.meshgrid(np.arange(6), np.arange(6))
z = (x + y) / 2
cr = p.contour(z=z, levels=[0, 1, 2, 3, 4, 5], line_color="grey", fill_color=Spectral5)
p.add_layout(cr.construct_color_bar(), "right")

show(p)
```

### Screenshots

![Screenshot 2022-07-19 at 20-59-40 Bokeh Plot](https://user-images.githubusercontent.com/580326/179838356-bbebb163-f497-43a0-94c4-6674e2b3bc60.png)

**Comment by ianthomas23** [comment]
It works for `ColorBar`, so there is something I should have done for `ContourColorBar` that I haven't.

**Comment by mattpap** [comment]
You need to update the themes:
```
bokeh/themes/_caliber.py:        "ColorBar": {
bokeh/themes/_contrast.py:        "ColorBar": {
bokeh/themes/_dark_minimal.py:        "ColorBar": {
bokeh/themes/_light_minimal.py:        "ColorBar": {
bokeh/themes/_night_sky.py:        "ColorBar": {
```

**Comment by mattpap** [comment]
I think, so far, you've updated only bokehjs' themes, but those and bokeh's are independent things.

**Comment by ianthomas23** [comment]
Ah yes, thanks for that.
