### ISSUE TITLE
Add pandas as hard dependency

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12261]
This was agreed in https://github.com/bokeh/bokeh/pull/12020#discussion_r913256527

Do we want it in the impending 3.0 release or not?

**Comment by mattpap** [comment]
"agreed" is a strong word based on that discussion. Definitely something to consider, if that means removal of all conditional code related to pandas. On the other hand, having pandas optional would be beneficial to keep, when using bokeh in pyiodide based runtimes.

**Comment by bryevdv** [comment]
> having pandas optional would be beneficial to keep, when using bokeh in pyiodide based runtimes.

Why? Pandas is available on pyodide:

https://pyodide.org/en/stable/usage/packages-in-pyodide.html
