### ISSUE TITLE
[FEATURE] Box_Zoom_Tool that allows zooming in only width, height, or both dimensions in one tool

### ISSUE THREAD

**Issue by bevoorrading** [bokeh/bokeh#12273]
### Problem description

If you want to be able use the BoxZoomTool only in one dimension, both want this functionality for both dimensions, and perhaps also a BoxZoomTool for both dimensions simultaneously, you need three separate zoom tools (i.e, `BoxZoomTool(dimensions='width')`, `BoxZoomTool(dimensions='width')`, and `BoxZoomTool(dimensions='both')`).

### Feature description

A box zooming tool that only zooms in the width dimension if you moves the cursor only horizontally, or only in the height dimension if you moves the cursor only vertically, and has the normal `BoxZoomTool(dimensions='both')` effect otherwise, would allow to have all functionality in one tool. 

### Potential alternatives

Adding three separate BoxZoomTools (i.e, `BoxZoomTool(dimensions='width')`, `BoxZoomTool(dimensions='width')`, and `BoxZoomTool(dimensions='both')`). This is not desirable as it are too many tools, certainly if you also want an option for zooming out, which adds additional tools. Having to switch between the tools is also less effective.

Additionally, multiple similar tools get merged and become unusable when using `merge_tools=True` (although this should be fixed in 3.0?).

### Additional information

[This webpage](https://plotly.com/python/time-series/)  illustrates the requested feature in Plotly Dash. (I like the visual style of Bokeh better, though.)

**Comment by mattpap** [comment]
> Additionally, multiple similar tools get merged and become unusable when using merge_tools=True (although this should be fixed in 3.0?).

This is fixed in 3.0-dev.

**Comment by mattpap** [comment]
We already have a mechanism for switching a mode of a tool or configuring a tool, like changing between selection modes (select, append, intersect, subtract) in selection tools. This is done via a context menu on tools that support this. Looks like box zoom tool was overlooked when this was originally implemented.

**Comment by bryevdv** [comment]
@mattpap this ask is about the mouse interaction, i.e. if you drag horizontally without any vertical movement (within some tolerance) then it behaves as a "horizontal". No need to muck with a context menu or have to switch between modes. To do that we would have to add e.g. `dimension="auto"` or similar. It's a good UX and for feature parity I do think we should pursue it.

**Comment by mattpap** [comment]
Adding a menu is cheap, so I will do that anyway. Especially given this may be a more robust option in the end, because whatever the tolerance will be on the desktop, it may not translate well to e.g. mobile.

**Comment by bryevdv** [comment]
I agree that a menu should also be added, sorry if that was not clear. But I do think an "auto" mode would be good to add separately for folks that want to make use of it (not sure I'd make it a default).

**Comment by bevoorrading** [comment]
For the type of application I'm planning, this is a quite important usability feature. With multiple panels with different types of timeseries data which are connected along the x(time)-axis, but not the y-axis, being able to keep the zooming separated over the axis is absolutely necessary, and convenient switching like this (directly from the mouse) is highly desirable. This type of zooming/switching works very well and intuitively on other "platforms" on the desktop, and mobile devices are not the intended use for me.

I am currently still in the phase of exploring which package/platform seems best for what I intend (though I quite like Bokeh), and something like this could be a deciding factor (clearly depends on much more, but all else being roughly equal ...), since interactivity and ease-of-use are one of the main reasons for rebuilding the application.

I'd be happy to help out with some things, although this particular feature seems like something that's more related to the javascript side (which I'm bit less well-versed in — so far hopefully).

**Comment by mattpap** [comment]
@bevoorrading, the requested features have already been implemented in PR #12227, so this will likely be a part of bokeh 3.0.

**Comment by bevoorrading** [comment]
@mattpap Great, thanks!
