### ISSUE TITLE
[FEATURE] Allow AutocompleteInput min_characters=0

### ISSUE THREAD

**Issue by CmpCtrl** [bokeh/bokeh#12272]
### Problem description

I see the following error when trying to pass a `min_characters=0` into an `AutocompleteInput`. 
```
ValueError: failed to validate AutocompleteInput(id='1083', ...).min_characters: expected positive integer, got 0
```

### Feature description

I'd like to see all of the drop down options when the input is selected, instead of only after entering the first `min_characters`.

### Potential alternatives

It seems like it almost works if you edit the `min_characters` param after initializing the widget, tho it doesnt immediately display the options on focusing on the input, only after an entry, like backspacing to 0 characters.

**Comment by mattpap** [comment]
It looks like an unnecessary limitation. See PR #12296. I made it to display the menu on focus for a consistent behavior.
