### ISSUE TITLE
Integrated igraph plotting.

### ISSUE THREAD

**Issue by swayson** [bokeh/bokeh#1229]
It would be very convenient to have a feature in bokeh, to directly plot [igraph networks](http://python-igraph.readthedocs.org/en/latest/tutorial.html#layouts-and-plotting).

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by damianavila** [comment]
The change of labels, I think, are not notified... so no problem...

**Comment by bryevdv** [comment]
Closing for lack of updates/interest after two years. Also, Bokeh's current extensibility makes it possible for other projects to extend Bokeh easily in ways that are specific to them, which is often a much better option than adding yet more to maintain to the core library.
