### ISSUE TITLE
[BUG] ColumnDataSource does not work with NumPy floating-point scalars

### ISSUE THREAD

**Issue by axil** [bokeh/bokeh#12315]
### Software versions

Python version      :  3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
IPython version     :  7.30.1
Tornado version     :  6.0.3
Bokeh version       :  2.4.3
BokehJS static path :  c:\python37-64\lib\site-packages\bokeh\server\static
node.js version     :  v16.16.0
npm version         :  8.11.0
Operating system    :  Windows-10-10.0.19041-SP0

### Browser name and version

Chrome Version 104.0.5112.81 (Official Build) (64-bit)

### Jupyter notebook / Jupyter Lab version

notebook==6.0.1

### Expected behavior

I expect bokeh to plot numpy floating-point scalars (0-dimensional arrays) as if they were ordinary numbers (integer scalars are processed correctly)

### Observed behavior

It does not plot them.

### Example code

```Python
p = bp.figure()
p.circle([1], [np.array(2)])              # works
p.circle([1.3], [np.array(2.4)])          # does not work
bp.show(p)
```

### Screenshots

![image](https://user-images.githubusercontent.com/170910/185675300-523f4b9a-adbd-42ff-8f56-2ccf6450705f.png)

**Comment by mattpap** [comment]
Given that those 0-dimensions arrays are serialized as actual arrays, then the fact that the integer case works at all in bokehjs is a really neat coincidence and relies on this JS weirdness:
```js
> [2]*8
16
```
Note however that:
```js
> [2, 3]*8
NaN
> [2] + 8
'28'
```
The float case hits a different code path, which results in invalid bounds, preventing rendering of the glyph.

Given that JS doesn't support operator overloading, then we can't implement proper arithmetics. We may in future, when we migrate our data processing pipeline to wasm and a more decent programing language for such purpose.

I suppose we could convert 0-dimension arrays to scalars in the pipeline and avoid the whole debacle.

**Comment by bryevdv** [comment]
> I suppose we could convert 0-dimension arrays to scalars in the pipeline and avoid the whole debacle.

I think we would have to, but then I would be concerned about the performance impact of adding full array scans just to detect this one special case.
