### ISSUE TITLE
Proposed changes for envs / scripts

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12332]
Hi @bokeh/core I'd like to get opinions on the following plan:

* delete top-level `environment.yaml`
* combine `meta.yaml` and all `ci/environment*.yaml` files in a `conda` directory
* move all scripts in `ci` to `scripts/ci` (and `scripts/docker` for the `ci/docker` subdir)

This will need some light updating of the dev guide to point users to use one of the versioned conda env files for their conda install.

**Comment by tcmetzger** [comment]
As much as I like the simplicity of just running `conda env update -f environment.yml`, I can see how the proposed changes make maintaining the environments easier. The 3.0 release is the best time to make changes like that, so I'm for it!

**Comment by ianthomas23** [comment]
I am in favour of them all too.
