### ISSUE TITLE
[BUG] webgl breaks shared brushing

### ISSUE THREAD

**Issue by meistermeister** [bokeh/bokeh#12357]
### Software versions

Python version      :  3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.31.1
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  C:\Users\ajhenryson\AppData\Local\Continuum\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19041-SP0

### Expected behavior

A shared columndatasource should have shared brushing for selections. Selecting circle glyphs should change the appearance of lines plotted from the same source.

### Observed behavior

Only the circle glyphs showed selection, not the lines.

### Example code

```Python
from bokeh.io import output_file, show
from bokeh.layouts import gridplot
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

output_file("brushing.html")

x = list(range(-20, 21))
x2 =list(range(-30, 10))
y0 = [abs(xx) for xx in x]
y1 = [xx**2 for xx in x2]

# create a column data source for the plots to share
source = ColumnDataSource(data=dict(x=x, x2=x2, y0=y0, y1=y1))

TOOLS = "box_select,lasso_select,help"

# create a new plot and add a renderer
left = figure(tools=TOOLS, width=300, height=300, title=None,output_backend="webgl" )
left.circle('x', 'y0', size=0, color='red', source=source) #size zero used to illustrate other unexpected behavior of glyphs
left.line('x', 'y0', source=source)


p = gridplot([[left]])

show(p)
```

### Screenshots

![image](https://user-images.githubusercontent.com/6623132/189030374-7c5526ac-eaef-4642-9c83-d5dfefaf6449.png)
circles are affected, but lines are not.
![image](https://user-images.githubusercontent.com/6623132/189030516-6989e21b-dc4c-45ac-8d6a-2a571e13af21.png)
Removing the webgl backend option restores expected function.

It also seems to cause size 0 circles to be shown rather than hidden, but I don't know if that's a separate bug.

**Comment by meistermeister** [comment]
The screenshots use default sized circles for visibility.

**Comment by ianthomas23** [comment]
Thanks for creating the issue @meistermeister.

This is due to a lack of support for selected indices in WebGL lines. It is not strictly speaking a bug as it is a feature that we never included in the original WebGL implementation and the new implementation follows that. But everyone else will call it a bug so I have labelled it as such.

There is a solution that is similar to that implemented for WebGL markers.

**Comment by ianthomas23** [comment]
`circle(..., size=0)` rendering is a separate bug. Probably a divide by zero.
