### ISSUE TITLE
[BUG] Canvas backend doesn't always render marker vector line_width correctly

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12361]
### Software versions

Python version      :  3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
IPython version     :  8.5.0
Tornado version     :  6.2
Bokeh version       :  3.0.0.dev15+5.g5f8abdbe.dirty
BokehJS static path :  /home/iant/github/bokeh/src/bokeh/server/static
node.js version     :  v16.15.0
npm version         :  8.5.5
Operating system    :  Linux-5.11.0-37-generic-x86_64-with-glibc2.31

### Expected behavior

I expect similar visual output to that produced by the WebGL output backend for a marker `line_width` of `[0, 3, 0, 3]`. I think it is the zeroes causing the problem.

### Observed behavior

See screenshot.

### Example code

```Python
from bokeh.plotting import figure, row, show

ps = []
for backend in ["canvas", "webgl"]:
    p = figure(width=150, height=200, title=backend, output_backend=backend)
    p.circle(x=0, y=[0, 1, 2, 3], fill_color="orange", size=12, line_width=[0, 5, 0, 5])
    ps.append(p)

show(row(ps))
```

### Screenshots

![Screenshot 2022-09-08 at 15-57-27 Bokeh Plot](https://user-images.githubusercontent.com/580326/189155853-e068b05d-1285-4a14-a79c-d6ef584e225d.png)

**Comment by ianthomas23** [comment]
In this situation setting the line width occurs at
https://github.com/bokeh/bokeh/blob/dad61556787b80249bf84bd74b465ed63d2cb82e/bokehjs/src/lib/core/visuals/line.ts#L177

According to https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineWidth#value a value of zero is ignored. Hence the first (bottom) circle in the test image uses the default line width of 1, and the 3rd circle uses the line width of the previous circle.

This is all confirmed by checking if the line width should be zero and using a very small positive value instead. Obviously we cannot fix it this way. Probably we need to check if the line width is zero and don't render the line if it is.

**Comment by mattpap** [comment]
We already do check, but in the scalar case. Currently `doit` doesn't have a vectorized variant to dismiss individual indices. I'm working on a fix.
