### ISSUE TITLE
Sixth element of a legend is not displayed ? [BUG] 

### ISSUE THREAD

**Issue by ValerianPiento** [bokeh/bokeh#12374]
### Software versions

Python version      :  3.8.5 (default, Sep  4 2020, 07:30:14) 
IPython version     :  7.19.0
Tornado version     :  6.0.4
Bokeh version       :  2.2.3
BokehJS static path :  /opt/anaconda3-2020.11/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  v14.18.1
npm version         :  7.24.2

### Expected behavior

In the example written below, I have ten points, all with a different color and marker. I display them using the scatter representation. I expect all the points to appear on screen with the color and marker given in the list. 

### Observed behavior

All the points are displayed, except the sixth one. I tried with different colors and marker, but the sixth one is always missing. 
I haven't tried with more recent versions of Bokeh, so I don't know if this behaviour is still present in the latest version of bokeh. 

### Example code

```Python
import numpy as np

from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

# Set up data
N = 10
x = np.linspace(0, 4 * np.pi, N)
y = x
color = ["blue", "green", "red", "orchid", "orange", "turquoise", "seagreen", "dodgerblue", "dimgrey", "chocolate"]
marker = ["circle", "square", "triangle", "diamond", "inverted_triangle", "plus", "hex", "triangle_pin", "square_pin", "asterisk"]
legend = ["blue", "green", "red", "orchid", "orange", "turquoise", "seagreen", "dodgerblue", "dimgrey", "chocolate"]
source = ColumnDataSource(data=dict(x=x, y=y, color=color, marker=marker, cameras=legend))

# Set up plot
plot = figure(height=400, width=800, title="my color test plot",
              tools="crosshair,pan,reset,save,wheel_zoom")
r1 = plot.scatter(
    x="x",
    y="y",
    source=source,
    color="color",
    marker="marker",
    legend_field="legend",
)

# Set up layouts and add to document
curdoc().add_root(plot)
curdoc().title = "Debug color"
```

### Screenshots

![bokeh](https://user-images.githubusercontent.com/113343272/189621519-c9a7b814-32f6-49e3-9189-89a975c3a7ed.png)

**Comment by mattpap** [comment]
> `legend_field="legend",`

I presume this should be `legend_field="cameras"` or the data source should contain `legend=legend` entry.

> Bokeh version : 2.2.3

This is a pretty old version. I tested this on 3.0-dev15 and it works fine. I will assume this was fixed long ago, somewhere in bokeh 2.3 or 2.4.
