### ISSUE TITLE
Figure out why `HexTile` with `pointytop` orientation and `aspect_scale=0.5` fails

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12379]
```diff
✗ HexTile glyph
 └── should support 'pointytop' orientation and aspect_scale=0.5
diff --git a/bokehjs/test/baselines/linux/HexTile_glyph__should_support_'pointytop'_orientation_and_aspect_scale=0.5.blf b/bokehjs/test/baselines/linux/HexTile_glyph__should_support_'pointytop'_orientation_and_aspect_scale=0.5.blf
index e1e7e91..b0ac968 100644
--- a/bokehjs/test/baselines/linux/HexTile_glyph__should_support_'pointytop'_orientation_and_aspect_scale=0.5.blf
+++ b/bokehjs/test/baselines/linux/HexTile_glyph__should_support_'pointytop'_orientation_and_aspect_scale=0.5.blf
@@ -1,4 +1,4 @@
 Plot bbox=[0, 0, 300, 300]
-  LinearAxis bbox=[33, 278, 262, 22]
-  LinearAxis bbox=[0, 27, 33, 251]
-  Title bbox=[33, 0, 262, 27]
+  LinearAxis bbox=[26, 278, 269, 22]
+  LinearAxis bbox=[0, 27, 26, 251]
+  Title bbox=[26, 0, 269, 27]
```

**Comment by bryevdv** [comment]
Thinking about this today, how is it possible that the baseline has changed, but the image has not?

**Comment by mattpap** [comment]
> Thinking about this today, how is it possible that the baseline has changed, but the image has not?

Baselines and images are captured at different times, so there is more time for things to settle between capturing plot's state (the baseline) and its image. I changed that in https://github.com/bokeh/bokeh/pull/12468/commits/10ca016eebaf448761cf85091738e1ec1874e7aa, so now the baseline should be consistent with the image. This still means that things are happening after ready state is reported, so there are more issues to resolve, but that's a general issue and not specific to this test case.

**Comment by mattpap** [comment]
I didn't notice any failures since PR #12468 was merged (where I improved the testing approach and unskipped the test), so I'm going to close this as resolved.
