### ISSUE TITLE
[BUG] Links in "First steps" documentation all broken

### ISSUE THREAD

**Issue by WoLpH** [bokeh/bokeh#12378]
### Software versions

Not relevant to this issue

### Browser name and version

Chrome 104.0.5112.101, Firefox 104.0.2

### Expected behavior

I expected to end up at a documentation page, I got a 404.

### Observed behavior

I get sent to this page, which results in a 404: https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_1

### Example code

1. Go to the "First Steps" section of the docs: https://docs.bokeh.org/en/latest/docs/first_steps.html
2. Click on any of the "Go to section N" links

**Comment by tcmetzger** [comment]
@WoLpH Thanks for putting in this issue!
The broken links are in the cards in https://docs.bokeh.org/en/latest/docs/first_steps.html - the links in the menu work, but we'll need to fix the link URLs in these cards.

@WoLpH would you be interested in making a PR to update the file https://github.com/bokeh/bokeh/blob/branch-3.0/docs/bokeh/source/docs/first_steps.rst? This would just be adding `.html` to the lines with `.. button-link::` (e.g. .. `button-link:: first_steps/first_steps_1` should be `.. button-link:: first_steps/first_steps_1`, I think).
