### ISSUE TITLE
README.md shows Python 3.7 supported and not 3.10

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12398]
![image](https://user-images.githubusercontent.com/27475/190611796-5de54e4e-55d1-4f78-b0c6-f01acf11c9ad.png)

**Comment by bryevdv** [comment]
Correct, this information use for the latest release, 2.4.3, which was published with 3.7 to 3.9 specified:

https://github.com/bokeh/bokeh/blob/branch-2.4/classifiers.txt

**Comment by mattpap** [comment]
Now looking at this, it obviously works as intended. After all, this readme is for the repository, not a particular branch.
