### ISSUE TITLE
[BUG] Domain is not resolved correctly when using BOKEH_RESOURCES=server

### ISSUE THREAD

**Issue by sdc50** [bokeh/bokeh#12400]
### Software versions

# Name                    Version                   Build  Channel
bokeh                     3.0.0.dev16                py_0    bokeh/label/dev

### Expected behavior

When running:

```
 BOKEH_RESOURCES=server bokeh serve sliders.py --port 5007
```

I would expect static resources to be requested at `http://localhost:5007/static/`. 

### Observed behavior

Even though port 5007 is specified resources are still being requested on port 5006.

![image](https://user-images.githubusercontent.com/6454472/190693728-5cb43151-f8b9-4b86-b932-7cf03d8185b3.png)

### Example code

```Python
cd bokeh/examples/app
BOKEH_RESOURCES=server bokeh serve sliders.py --port 5007
```

**Comment by bryevdv** [comment]
Here is the comment that outlines what I think the appropriate solution is

https://github.com/bokeh/bokeh/pull/12401#issuecomment-1363576533

I don't think I will get to this for 3.1 so I am bumping to 3.2 but also self-assigning.
