### ISSUE TITLE
gridplot examples layouts are broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12405]
ref: https://docs.bokeh.org/en/dev-3.0/docs/examples/models/iris_splom.html

<img width="770" alt="Screen Shot 2022-09-16 at 19 03 10" src="https://user-images.githubusercontent.com/1078448/190836238-28480eff-7af1-46bc-8e99-1287020a08dd.png">

**Comment by bryevdv** [comment]
Anscombe is also completely broken:

ref: https://docs.bokeh.org/en/dev-3.0/docs/examples/models/anscombe.html

<img width="637" alt="Screen Shot 2022-09-16 at 19 04 41" src="https://user-images.githubusercontent.com/1078448/190836276-6d521eb1-d6d5-4dd7-b8bb-4d9a20af7f80.png">

**Comment by bryevdv** [comment]
`grid_axis_alignment_nested.py` in the examples report seems to suffer the same issue

**Comment by mattpap** [comment]
> ref: https://docs.bokeh.org/en/dev-3.0/docs/examples/models/iris_splom.html

This is a side effect of `GridBox` using fractional grid cell sizes by default. This can be remedied by setting `grid.cols = "max-content"` and `grid.rows = "max-content"`, to use maximal sizing of grid's children for row/column sizing.
