### ISSUE TITLE
Jitter example is broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12404]
ref: https://docs.bokeh.org/en/dev-3.0/docs/examples/plotting/jitter.html

The "jitter" plot has no jitter applied.

cc @mattpap not sure what is going on, since another jitter example *is* working:

https://docs.bokeh.org/en/dev-3.0/docs/examples/plotting/categorical_scatter_jitter.html

**Comment by bryevdv** [comment]
The offsets are correct, right before the call to `map` that adds them to the original coordinates (which area also correct). I have to conclude there is some issue our `map` function.

**Comment by bryevdv** [comment]
Oh, the problem is that the coordinates are held in an `Int32NDArray` @mattpap What do you want to do about this. I think the Python code in `jitter.py` should reasonably be expected to work as-is. We could tape over the issue with a cast or something in `jitter.ts` but I think the wider issue is that numerical coordinates may reasonably need to be floating point at any time.

**Comment by mattpap** [comment]
This regression is a good sign actually, that bokehjs is getting more respectful of the type of data it has to work with, instead of making assumptions. The result is of course incorrect, but to fix this an explicit coercion mechanism has to be set up, so that `jitter('yr', 0.4)` would know the resulting array type, following numpy's coercion rules

**Comment by mattpap** [comment]
Also one tick is missing:
![image](https://user-images.githubusercontent.com/27475/190870387-14d2e35e-f015-45f7-86b7-55cccde8edcf.png)
I will look into both issues, but first I will set up testing, because this should have been caught much earlier.

**Comment by bryevdv** [comment]
> Also one tick is missing 

I guess there is an order issue with the tick locations using an auto-range of the original data and the ultimate drawing using an  auto-range of the (incorrectly) jittered data. I'm not sure it would be much of an issue in practice if jitter was working correctly, but if there is a clean and simple  fix then 👍

**Comment by mattpap** [comment]
> Also one tick is missing: (...)

This is actually correct behavior given the setup. This example uses a fixed ticker in x-axis, which doesn't include 69. That value results of truncation of jittered values for 70, when storing data in `Int32Array`. Given that auto-ranging is applied, then the plot is displayed in full.
