### ISSUE TITLE
Custom extension examples not rendering

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12416]
cc @mattpap I noticed this in local docs building,  but the issue also appears on the latest published dev docs:

https://docs.bokeh.org/en/dev-3.0/docs/user_guide/extensions_gallery/tool.html

Seems the extension are not being loaded properly anymore, at least in autoload cases:
```
Uncaught (in promise) Error: could not resolve type 'DrawTool', which could be due to a widget or a custom model not being registered before first usage
```

**Comment by bryevdv** [comment]
@mattpap  any thoughts on this one?

**Comment by mattpap** [comment]
It tested this when this issue was submitted and everything works fine as standalone examples. This seems to be documentation specific issue.

**Comment by bryevdv** [comment]
Yes things work locally, the issue is in the docs specifically. The docs just use `autoload_static` is that embed API  broken for extensions?

**Comment by bryevdv** [comment]
@mattpap FYI this is what I was alluding to in the call:

https://github.com/bokeh/bokeh/blob/1a875c97ed2497f3643bf0c1ffdef0a26fb63b29/src/bokeh/sphinxext/bokeh_plot.py#L231-L244

where `clear_extensions` is this

https://github.com/bokeh/bokeh/blob/1a875c97ed2497f3643bf0c1ffdef0a26fb63b29/src/bokeh/model/model.py#L586-L593

Offhand this does not seem like it should pose any problem, since everything necessary to render that `autoload_static` would need should still be happening after that clear. But if anything jumps out or you have any last-minute ideas I would love to hear them.

**Comment by mattpap** [comment]
I'm not sure what's the difference between standalone and docs, but I can see a clear bug in the handling of `model_class_reverse_map` which eventually leads to this issue. I will submit a PR tomorrow.
