### ISSUE TITLE
[BUG] Movies example is broken with the recent reorganization

### ISSUE THREAD

**Issue by dsolson** [bokeh/bokeh#12444]
### Software versions

The usual

### Expected behavior

Movie example works

### Observed behavior

Movie example doesn't work

### Example code

```Python
bokeh server --show main.py
```

**Comment by bryevdv** [comment]
@dsolson directory apps are intended to be run by supplying the directory:
```
bokeh serve  --show movies
```
Can you confirm you started the app by using the directory? Additionally "Movie example doesn't work" is not useful information. Please provide *details*: is there a stack trace? If so, please provide it. If not, describe what actually does happen.

**Comment by bryevdv** [comment]
This should be resolved. @dsolson it would have been immediately obvious what needed fixing if you had included the information that the issue template requested. Please make sure to include complete details in any future issues.
