### ISSUE TITLE
Toolbar interferes with tooltip

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12447]
ref: https://docs.bokeh.org/en/dev-3.0/docs/examples/plotting/elements.html

<img width="246" alt="Screen Shot 2022-10-02 at 00 03 43" src="https://user-images.githubusercontent.com/1078448/193442240-82fd63bb-8dec-4dea-af1c-75344e43e2cd.png">

**Comment by mattpap** [comment]
There's no winning with CSS. Doing the right thing to avoid cursor interference with tooltips results in this. It's easy to revert to the original behavior.

**Comment by mattpap** [comment]
Actually, the correct solution was there, just wasn't applied correctly due to shadow DOM.
