### ISSUE TITLE
Sizing mode example is broken 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12453]
ref: `examples/basic/layouts/sizing_mode.py` 

all "height" and "both" modes seem broken, as well as "inherit" e.g.

<img width="696" alt="Screen Shot 2022-10-02 at 19 06 18" src="https://user-images.githubusercontent.com/1078448/193489299-ec672027-3947-4645-9ab0-69bb3ac9e8c3.png">

**Comment by bryevdv** [comment]
Also evidenced when embedded in docs
<img width="685" alt="Screen Shot 2022-10-02 at 19 08 47" src="https://user-images.githubusercontent.com/1078448/193489511-6c7494c8-7be7-4803-8bf9-38651d8ec106.png">

**Comment by bryevdv** [comment]
Not sure if it is related but notice the example immediately below in the docs is also similarly squished:

<img width="681" alt="Screen Shot 2022-10-02 at 19 09 31" src="https://user-images.githubusercontent.com/1078448/193489549-106c33a1-1f9f-4ae0-a492-887a3fe13299.png">

**Comment by bryevdv** [comment]
Modulo testing in manual notebooks these are the only blockers to an rc1 I am aware of at the moment cc @bokeh/core

**Comment by tcmetzger** [comment]
I can confirm this behavior (Ubuntu/Chromium and Win10/Chrome)

**Comment by mattpap** [comment]
The behavior in height, especially of standalone plots, is understandable and in CSS perfectly valid. There needs to be space to expand into, but that space is only (by default with standard user-agent CSS) available in width. To get the previous behavior, one needs to set up the vertical space manually, e.g. by setting `html, body { height: 100%; }`, or equivalent. For the case of spanning the entire viewport, there will be specialized UI element (`ViewportBox`) (not a layout) added that will set things up properly.

**Comment by bryevdv** [comment]
@mattpap so the the action to take is to remove the example and update the docs? Or put the plot inside a `Column` with fixed height?

And the other observation should get a separate issue, as it is not height related?

**Comment by bryevdv** [comment]
Changing the example to do this yields expected results:
```
layout = column(select, row(plot, height=800, sizing_mode="stretch_width"))
```
@mattpap is there an easy way to put a border around the `row`? Would #12450 cover that?

**Comment by mattpap** [comment]
> is there an easy way to put a border around the row?

```py
obj.styles = dict(border="1px solid black")` 
```
or
```py
from bokeh.models import Styles
obj.styles = Styles(border="1px solid black")
```
or
```py
obj.stylessheets += ":host { border: 1px solid black; }"
```
or
```py
obj.stylesheets += {
    ":host": dict(border="1 px solid black"),
}
```
or
```py
from bokeh.models import Styles
obj.stylesheets += {
    ":host": Styles(border="1 px solid black"),
}
```

**Comment by bryevdv** [comment]
@mattpap are you saying those *will* work once #12450 is in? That's what I understood #12450 was for. If you are saying these should work now, I tried all the following to no effect
```python
container = row(plot, height=800, sizing_mode="stretch_width")
# container.styles = dict(border="1px solid black")
# container.stylesheets += ":host { border: 10px solid black; }"
# from bokeh.models import Styles
# container.styles = Styles(border="1px solid black")
# container.stylesheets += {":host": Styles(border="1 px solid black")}

layout = column(select, container)
layout.sizing_mode = "stretch_both" # set separately to avoid also setting children

show(layout)
```

**Comment by mattpap** [comment]
What I showed here is what works per instance basis. What #12450 asks for is stylesheets per component basis. This is technically already possible with themes (one can set `stylesheets` in a theme), but I consider this more of a creative hack than a solution. It also wouldn't allow for correct order (precedence) of stylesheets, which is another aim of #12450.

**Comment by mattpap** [comment]
It should have been `append()` instead of `+=`. There's a complete example:
```py
from bokeh.layouts import row, column
from bokeh.plotting import figure
from bokeh.models import Select
from bokeh.io import show

plot = figure()
plot.circle([1, 2, 3], [1, 2, 3])

container = row(plot, height=800, sizing_mode="stretch_width")
#container.styles = dict(border="10px solid black")
#container.stylesheets.append(":host { border: 10px solid black; }")
from bokeh.models import Styles
#container.styles = Styles(border="10px solid black")
container.stylesheets.append({":host": Styles(border="10px solid black")})

select = Select(options=["A", "B"])
layout = column(select, container)
layout.sizing_mode = "stretch_both" # set separately to avoid also setting children

show(layout)
```
All combinations work.

**Comment by bryevdv** [comment]
@mattpap The `stylesheets.append` versions work, but should the `container.styles =` versions be expected to work? The y still do not for me.

**Comment by bryevdv** [comment]
Docs updated, will make separate issues about CSS styling docs and usage.
