### ISSUE TITLE
Wheel Zoom not working with chrome

### ISSUE THREAD

**Issue by dhirschfeld** [bokeh/bokeh#1245]
As discussed on the ML
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/oP3i-B4raIo

With chrome chrome "37.0.2062.120 m" the wheel zoom doesn't work.
It does work with FireFox 32.0.2

bokeh 0.6.1.dev.20140923-np19py27_1

``` python
In [4]: print IPython.sys_info()
{'commit_hash': 'a2e1c67',
 'commit_source': 'installation',
 'default_encoding': 'cp850',
 'ipython_path': 'C:\\dev\\bin\\Anaconda\\lib\\site-packages\\IPython',
 'ipython_version': '3.0.0-dev',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\dev\\bin\\Anaconda\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.5 |Anaconda 2.0.0 (64-bit)| (default, Jul  1 2013, 12:37:52) [MSC v.1500 64 bit (AMD64)]'
} 
```

**Comment by forman** [comment]
With 0.12.0, the issue seems back again, at least on Windows 10: wheel zoom works fine for FF and Edge, but not Chrome.

Issue occurs in my own Notebook and also for all the plots in the gallery: http://bokeh.pydata.org/en/latest/docs/gallery.html

**Comment by birdsarah** [comment]
Thanks for the report @forman.

Are you on a laptop with a touch screen?

**Comment by birdsarah** [comment]
@forman - I've opened a new issue #4862 which I believe describes the current problem. Can you confirm this is your situation on that issue.

**Comment by forman** [comment]
Exactly, mine is a Dell XPS with touchscreen. Just tested with Chrome on Windows 10 without touchscreen and everything is fine!
