### ISSUE TITLE
DOM drag/selection issue

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12456]
It is easy to accidentally to drag over various DOM elements, and in many cases this results in an ugly "selection". The screencap below (Chrome) shows this happening when a lasso select veers just over the plot edge into a neighboring plot. 

![ScreenFlow](https://user-images.githubusercontent.com/1078448/193504404-06137fdc-5f62-483a-953a-61c6432a3b16.gif)

I have also seen similar behavior with sliders on Safari, where the label becomes "highlighted" with any use at all (but not Chrome, afaict).

**Comment by mattpap** [comment]
Can't reproduce this on Linux. There is a mechanism in bokehjs to protect against this. Perhaps the issue is platform specific.

**Comment by bryevdv** [comment]
Yes FWIW  have only experienced this on OSX

**Comment by mattpap** [comment]
This may have been fixed as a side effect of PR #12417.

**Comment by ianthomas23** [comment]
I'll take a look and report back.

**Comment by ianthomas23** [comment]
I can reproduce this on an M1 mac using Safari 16.0 (17614.1.25.9.10) but not Chrome 106.0.5249.119. It was fixed by #12451, i.e. the problem is reproducible with commit `b0350e0` but is fixed with `fd5ff1c`.

**Comment by ianthomas23** [comment]
@bryevdv Can you check that commits from `fd5ff1c` onwards fix this for you?

**Comment by ianthomas23** [comment]
https://github.com/bokeh/bokeh/commit/fd5ff1c1b8a34f7fc5023e349b85677a355a5710 is the commit on `branch-3.0` after PR #12451 was merged which fixes the problem for me.

**Comment by bryevdv** [comment]
OK  I just tried with the tip of `branch-3.0` and it seems fixed there. I guess that commit is not in RC4 somehow? I am not able to go digging further just at the moment, but we should check rc5 when it is deployed.

**Comment by mattpap** [comment]
The fix was merged before rc1.
