### ISSUE TITLE
[BUG] Sphinx warnings while building documentation

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh#12462]
While building the docs with `make html`, I see lots of:

```python-traceback
RemovedInSphinx60Warning: The implementation of Documenter.get_object_members() will be removed from Sphinx-6.0.
```

I think it's because of `EnumDocumenter` ([`ModuleLevelDocumenter` inherits from `Documenter`](https://github.com/sphinx-doc/sphinx/blob/3e29abf8de3f6f29aff18859b5eb88c8c79a1cbc/sphinx/ext/autodoc/__init__.py#L1112))?

https://github.com/bokeh/bokeh/blob/aae3034a9df90119c3c8c71ddf7a15e41821a5d0/src/bokeh/sphinxext/bokeh_autodoc.py#L83-L90

Could the fix be to have a `get_object_members` function in `EnumDocumenter`? Like in:

https://github.com/bokeh/bokeh/blob/aae3034a9df90119c3c8c71ddf7a15e41821a5d0/src/bokeh/sphinxext/bokeh_autodoc.py#L66-L80

**Comment by bryevdv** [comment]
I looked into this a little bit, and technically I actually think this is a sphinx faux-pas. AFAICT sphinx is still using the deprecated API internally, which is *fine*. But if you do that, you should take care to silence the deprecation warnings coming from the internal use. (E.g. by adding a new parameter `_internal=False` that you only set to True internally, to quiet the warning). 

That said, I'd love to have a way to shut those warnings up on our end. Does `EnumDocumenter` function properly with that simple "no-op" definition of `get_object_members`? If so I'd say add it with a comment explaining why it is there.

**Comment by bryevdv** [comment]
If not, another option could be providing a `get_object_members` that just calls the super method, but also silences the warning

**Comment by pavithraes** [comment]
> Does EnumDocumenter function properly with that simple "no-op" definition of get_object_members?

@bryevdv Looks like it does!
