### ISSUE TITLE
[BUG] HoverTool/tooltips time formatter issue

### ISSUE THREAD

**Issue by jmranger** [bokeh/bokeh#12481]
### Software versions

Python version      :  3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.0.dev20
BokehJS static path :  C:\ProgramData\Miniconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Firefox 105.0.3

### Expected behavior

On hovering over a point, the tooltip should display two lines, one showing the exact point timestamp.

### Observed behavior

The datetime in the tooltip isn't formatted as requested

### Example code

```Python
import datetime
from bokeh.models import DatetimeTickFormatter, HoverTool
from bokeh.plotting import figure, show
from math import pi
import pandas

xpts = [ datetime.datetime.utcfromtimestamp(1664780000),
         datetime.datetime.utcfromtimestamp(1664790000) ]
ypts = [1,2]
df = pandas.DataFrame(data=ypts,
                      index=xpts,
                      columns=["pts"])

plot = figure()
plot.scatter(df.index, df["pts"])
line = plot.line(df.index, df["pts"])
plot.add_tools(
    HoverTool(
        tooltips = [ ("Date & time", "@x{%Y-%m-%d %H:%M:%S.%3N}"),
                     ("Value", "@y"),
                   ],
        formatters = {
                        'x' : 'datetime',
                     },
        renderers = [
                      line
                    ],
        toggleable=False
    )
)
plot.xaxis.formatter = DatetimeTickFormatter(
    microseconds = '%Y-%m-%d %H:%M:%S.%f',
    milliseconds = '%Y-%m-%d %H:%M:%S.%f',
    seconds      = '%Y-%m-%d %H:%M:%S',
    minsec       = '%Y-%m-%d %H:%M:%S',
    minutes      = '%Y-%m-%d %H:%M:%S',
    hourmin      = '%Y-%m-%d %H:%M:%S',
    hours        = '%Y-%m-%d %H:%M:%S',
    days         = '%Y-%m-%d %H:%M:%S',
    months       = '%Y-%m-%d %H:%M:%S',
    years        = '%Y-%m-%d %H:%M:%S',
)
plot.xaxis.major_label_orientation = pi/8

show(plot)
```

### Stack traceback or browser console output

Found while testing a possible migration of existing Bokeh 0.12.7 code to 3.0.0.
For what it's worth, code works on 0.12.7.

It could very well be something that changed so long ago that the deprecation warning was removed.

Output of bokeh info for 0.12.7:
Python version      :  3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
IPython version     :  (not installed)
Bokeh version       :  0.12.7
BokehJS static path :  C:\Users\JMR\Desktop\Miniconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)

### Screenshots

![0 12 7](https://user-images.githubusercontent.com/12662295/194955382-a9ea8ef8-19d0-45e1-aaa9-892432f1d834.png)
![3 0 0dev20](https://user-images.githubusercontent.com/12662295/194955383-483a647b-018b-464f-bca3-c8e334c7f9c7.png)

**Comment by jmranger** [comment]
Forgot to mention: no JS error in the console.

**Comment by bryevdv** [comment]
@jmranger please see the migration guide for version 2.0

https://docs.bokeh.org/en/2.4.3/docs/releases.html#hovertool-formatters-specification

**Comment by jmranger** [comment]
Ah. My bad. Thanks for the feedback.
