### ISSUE TITLE
[BUG] Sparse DataFrame can't be plotted without transformation to CDS

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#12507]
### Software versions

Python version      :  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
IPython version     :  8.4.0
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v17.4.0
npm version         :  8.3.1
Operating system    :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.31

### Browser name and version

Google Chrom Version 106.0.5249

### Jupyter notebook / Jupyter Lab version

IPython          : 8.4.0 ipykernel        : 6.9.1 ipywidgets       : 7.7.1 jupyter_client   : 7.1.2 jupyter_core     : 4.9.2 jupyter_server   : not installed jupyterlab       : not installed nbclient         : 0.5.12 nbconvert        : 6.4.2 nbformat         : 5.1.3 notebook         : 6.4.8 qtconsole        : not installed traitlets        : 5.1.1

### Expected behavior

I was experimenting with [sparse data from pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html) and expected that I can display a simple line plot passing pandas data direct to `x` and `y`.

### Observed behavior

It is not possible to pass sparse DataFrame to the plot. It has to be transformed to CDS first. There is no hint, how to do better.

### Example code

```Python
import numpy as np
import pandas as pd

from bokeh.plotting import figure, show, output_notebook
from bokeh.models import ColumnDataSource
output_notebook()

arr = np.random.randn(10)
arr[2:-2] = np.nan

# sparse DataFrame
sdf = pd.DataFrame({'sparsedata':pd.arrays.SparseArray(arr)})

# standard DataFrame
df = pd.DataFrame({'data': arr})

# working syntax for standard DataFrame
p = figure(width=300, height=300)
p.line(x='index', y='data', source=df)
show(p)

# working syntax for sparse DataFrame
p = figure(width=300, height=300)
p.line(x='index', y='sparsedata', source=ColumnDataSource(sdf))
show(p)

# error producing syntax for sparse DataFrame
p = figure(width=300, height=300)
p.line(x=sdf.index, y=sdf.sparsedata)
show(p)
```

### Stack traceback or browser console output

<details><summary>Traceback</summary>
 TypeError                                 Traceback (most recent call last)
Input In [9], in <cell line: 3>()
      1 p = figure(width=300, height=300)
      2 p.line(x=sdf.index, y=sdf.sparsedata)
----> 3 show(p)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/io/showing.py:144, in show(obj, browser, new, notebook_handle, notebook_url, **kwargs)
    141 state = curstate()
    143 if isinstance(obj, LayoutDOM):
--> 144     return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
    146 def is_application(obj: Any) -> TypeGuard[Application]:
    147     return getattr(obj, '_is_a_bokeh_application_class', False)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/io/showing.py:191, in _show_with_state(obj, state, browser, new, notebook_handle)
    189 if state.notebook:
    190     assert state.notebook_type is not None
--> 191     comms_handle = run_notebook_hook(state.notebook_type, 'doc', obj, state, notebook_handle)
    192     shown = True
    194 if state.file or not shown:
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/io/notebook.py:357, in run_notebook_hook(notebook_type, action, *args, **kwargs)
    355 if _HOOKS[notebook_type][action] is None:
    356     raise RuntimeError(f"notebook hook for {notebook_type!r} did not install {action!r} action")
--> 357 return _HOOKS[notebook_type][action](*args, **kwargs)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/io/notebook.py:574, in show_doc(obj, state, notebook_handle)
    572 from ..embed.notebook import notebook_content
    573 comms_target = make_id() if notebook_handle else None
--> 574 (script, div, cell_doc) = notebook_content(obj, comms_target)
    576 publish_display_data({HTML_MIME_TYPE: div})
    577 publish_display_data({JS_MIME_TYPE: script, EXEC_MIME_TYPE: ""}, metadata={EXEC_MIME_TYPE: {"id": obj.id}})
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/embed/notebook.py:87, in notebook_content(model, notebook_comms_target, theme)
     84 # Comms handling relies on the fact that the new_doc returned here
     85 # has models with the same IDs as they were started with
     86 with OutputDocumentFor([model], apply_theme=theme, always_new=True) as new_doc:
---> 87     (docs_json, [render_item]) = standalone_docs_json_and_render_items([model])
     89 div = div_for_render_item(render_item)
     91 render_item = render_item.to_json()
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/embed/util.py:337, in standalone_docs_json_and_render_items(models, suppress_callback_warning)
    335 docs_json: Dict[ID, DocJson] = {}
    336 for doc, (docid, _) in docs.items():
--> 337     docs_json[docid] = doc.to_json()
    339 render_items: List[RenderItem] = []
    340 for _, (docid, roots) in docs.items():
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/document/document.py:758, in Document.to_json(self)
    749 ''' Convert this document to a JSON object.
    750 
    751 Return:
    752     JSON-data
    753 
    754 '''
    756 # this is a total hack to go via a string, needed because
    757 # our BokehJSONEncoder goes straight to a string.
--> 758 doc_json = self.to_json_string()
    759 return loads(doc_json)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/document/document.py:785, in Document.to_json_string(self, indent)
    776         model.static_to_serializable(serializer)
    778 root_ids = [ r.id for r in self._roots ]
    780 json = DocJson(
    781     title=self.title,
    782     defs=serializer.definitions,
    783     roots=RootsJson(
    784         root_ids=root_ids,
--> 785         references=references_json(self.models),
    786     ),
    787     version=__version__,
    788 )
    790 return serialize_json(json, indent=indent)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/document/util.py:151, in references_json(references)
    149 for r in references:
    150     struct = r.struct
--> 151     struct['attributes'] = r._to_json_like(include_defaults=False)
    152     references_json.append(struct)
    154 return references_json
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/model/model.py:623, in Model._to_json_like(self, include_defaults)
    605 def _to_json_like(self, include_defaults: bool):
    606     ''' Returns a dictionary of the attributes of this object, in
    607     a layout corresponding to what BokehJS expects at unmarshalling time.
    608 
   (...)
    621 
    622     '''
--> 623     all_attrs = self.properties_with_values(include_defaults=include_defaults)
    625     # If __subtype__ is defined, then this model may introduce properties
    626     # that don't exist on __view_model__ in bokehjs. Don't serialize such
    627     # properties.
    628     subtype = getattr(self.__class__, "__subtype__", None)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/core/has_props.py:555, in HasProps.properties_with_values(self, include_defaults, include_undefined)
    534 def properties_with_values(self, *, include_defaults: bool = True, include_undefined: bool = False) -> Dict[str, Unknown]:
    535     ''' Collect a dict mapping property names to their values.
    536 
    537     This method *always* traverses the class hierarchy and includes
   (...)
    553 
    554     '''
--> 555     return self.query_properties_with_values(lambda prop: prop.serialized,
    556         include_defaults=include_defaults, include_undefined=include_undefined)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/core/has_props.py:611, in HasProps.query_properties_with_values(self, query, include_defaults, include_undefined)
    608     continue
    610 try:
--> 611     value = descriptor.serializable_value(self)
    612 except UnsetValueError:
    613     if include_undefined:
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/core/property/descriptors.py:344, in PropertyDescriptor.serializable_value(self, obj)
    330 """ Produce the value as it should be serialized.
    331 
    332 Sometimes it is desirable for the serialized value to differ from
   (...)
    341 
    342 """
    343 value = self.__get__(obj, obj.__class__)
--> 344 return self.property.serialize_value(value)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/core/property/container.py:267, in ColumnData.serialize_value(self, value)
    266 def serialize_value(self, value):
--> 267     return transform_column_source_data(value
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/util/serialization.py:525, in transform_column_source_data(data, buffers, cols)
    523 for key in to_transform:
    524     if pd and isinstance(data[key], (pd.Series, pd.Index)):
--> 525         data_copy[key] = transform_series(data[key], buffers=buffers)
    526     elif isinstance(data[key], np.ndarray):
    527         data_copy[key] = transform_array(data[key], buffers=buffers)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/util/serialization.py:427, in transform_series(series, force_list, buffers)
    425 else:
    426     vals = series.values
--> 427 return transform_array(vals, force_list=force_list, buffers=buffers)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/util/serialization.py:371, in transform_array(array, force_list, buffers)
    339 ''' Transform a NumPy arrays into serialized format
    340 
    341 Converts un-serializable dtypes and returns JSON serializable
   (...)
    366 
    367 '''
    369 array = convert_datetime_array(array)
--> 371 return serialize_array(array, force_list=force_list, buffers=buffers)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/util/serialization.py:458, in serialize_array(array, force_list, buffers)
    456     array = array.filled(np.nan)  # Set masked values to nan
    457 if (array_encoding_disabled(array) or force_list):
--> 458     return transform_array_to_list(array)
    459 if not array.flags['C_CONTIGUOUS']:
    460     array = np.ascontiguousarray(array)
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/util/serialization.py:385, in transform_array_to_list(array)
    383 if (array.dtype.kind in ('u', 'i', 'f') and (~np.isfinite(array)).any()):
    384     transformed = array.astype('object')
--> 385     transformed[np.isnan(array)] = 'NaN'
    386     transformed[np.isposinf(array)] = 'Infinity'
    387     transformed[np.isneginf(array)] = '-Infinity'
File /opt/conda/envs/aiva-env/lib/python3.9/site-packages/pandas/core/arrays/sparse/array.py:610, in SparseArray.__setitem__(self, key, value)
    605 def __setitem__(self, key, value):
    606     # I suppose we could allow setting of non-fill_value elements.
    607     # TODO(SparseArray.__setitem__): remove special cases in
    608     # ExtensionBlock.where
    609     msg = "SparseArray does not support item assignment via setitem"
--> 610     raise TypeError(msg)
TypeError: SparseArray does not support item assignment via setitem
</details>

**Comment by mosc9575** [comment]
I didn't took to much time to think about, but at the moment I would go for a resonable error warning (option 0).

I checked the size of the CDS from the example above and there is no difference between an original df and a sparse one.

```
import sys
sys.getsizeof(ColumnDataSource(df))
>>> 48
sys.getsizeof(ColumnDataSource(sdf))
>>> 48
```

Since the approach with the CDS is working, I think there is no need to make it unnecessary complicated. The sparse dataframes has some benefit using pandas with data with a large number of NaNs, but this can be solved on the python side.

**Comment by mattpap** [comment]
Note that `sys.getsizeof()` isn't a good data structure size measurement tool, because it doesn't include size of referenced objects, so a list of `n` objects will include the size of the list data structure and (give or take) size of `n` pointers, e.g.:
```py
In [1]: import sys

In [2]: l0 = []

In [3]: l1 = [1, 2, 3]

In [4]: sys.getsizeof(l0)
Out[4]: 56

In [5]: sys.getsizeof(l1)
Out[5]: 88

In [6]: sys.getsizeof([l0])
Out[6]: 64

In [7]: sys.getsizeof([l0, l0])
Out[7]: 72

In [8]: sys.getsizeof([l0, l0, l0])
Out[8]: 80

In [9]: sys.getsizeof([l1, l1, l1])
Out[9]: 80
```
`_8` and `_9` should be clearly different in size.

**Comment by benrussell80** [comment]
> ```python
> sdf = pd.DataFrame({'sparsedata':pd.arrays.SparseArray(arr)})
> ...
> # working syntax for sparse DataFrame
> p = figure(width=300, height=300)
> p.line(x='index', y='sparsedata', source=ColumnDataSource(sdf))
> show(p)
> ```
I am seeing that this snippet raises
`bokeh.core.serialization.SerializationError: can't serialize <class 'pandas.core.arrays.sparse.array.SparseArray'>`
for versions
- python 3.10
- pandas 1.5.3
- numpy 1.24
- bokeh 3.1.0.dev3

Regarding solutions @bryevdv mentioned:
0. Have CDS display error: Something like this probably do the trick
```python
if any(isinstance(ty, pd.core.arrays.sparse.dtype.SparseDtype) for ty in df.dtypes):
    ...
```
1. Have CDS do conversion: pandas series containing SparseArrays have `.sparse.to_dense()` accessor methods. If _all_ of the columns in a DataFrame are SparseArrays then `df.sparse.to_dense()` works. Otherwise, each column would have to be done individually.

**Comment by mattpap** [comment]
Converting to dense representation isn't ideal, but good enough for now. We do this kind of transformations a lot. @benrussell80, if you want, please submit a PR, especially given you already fixed one issue in this area.

**Comment by benrussell80** [comment]
Will do
