### ISSUE TITLE
Dask downstream tests and basic usage failures

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12503]
Trying to actually run a simple example  with RC4 results in the MissingBokeh route handler page:
```
Dask needs bokeh >= 2.1.1 for the dashboard.

Install with conda: conda install bokeh>=1.0

Install with pip: pip install bokeh>=2.1.1
```
But (I think) this happens on any error, so it's unclear what the ultimate error is. cc @pavithraes @jrbourbeau is there a way to get more verbose error information? I am running this in this code in ipython which does not really tell me anything:
```
from dask.distributed import Client, progress
import dask
import dask.dataframe as dd
from sklearn.linear_model import LinearRegression

client = Client(threads_per_worker=4,
                n_workers=2, memory_limit='2GB')

df = dask.datasets.timeseries()

def train(partition):
    est = LinearRegression()
    est.fit(partition[['x']].values, partition.y.values)
    return est

# client.dashboard_link

# df[['x', 'y']].resample('1h').mean().head()
```

**Comment by bryevdv** [comment]
I should also mention that everal downstream tests are failing with import errors, e.g:
```
E   ImportError: cannot import name 'InstanceDefault' from 'bokeh.core.properties' (/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/core/properties.py)
```

ref: https://github.com/bokeh/bokeh/actions/runs/3293338907/jobs/5429833162

However we are not actually testing the correct package. The  downstream package install step causes Bokeh 2.4.3 to be installed.

**Comment by bryevdv** [comment]
@mattpap I think this is the breaking change:
```
E   ImportError: cannot import name 'Panel' from 'bokeh.models' (/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/__init__.py)
```

is this a rename? If so we should add a deprecated compatibility alias for now

**Comment by bryevdv** [comment]
Well, adding an alias will not be sufficient. Doing that, the next problem comes from Dask passing an `id`
```
        self.root = figure(
            title="Bytes stored on cluster",
            tools="",
            id="bk-cluster-memory-plot",
            width=int(width / 2),
            name="cluster_memory",
            min_border_bottom=50,
            **kwargs,
        )
```
then
```
AttributeError: unexpected attribute 'id' to figure, possible attributes are ...
```
which is really unfortunate

**Comment by bryevdv** [comment]
OK things seem to work (modulo my very simple tests) with these changes:

* `Panel = TabPanel` alias
* `kw.pop("id", None)` at the top of `figure.__init__`

@mattpap I'm ok with adding deprecations for both of these. I will submit a PR later today.

**Comment by jrbourbeau** [comment]
Thanks for ping @bryevdv. Looks like I'm a little late to the party. Did you solve the things that needed solving? 

> I will open an issue on dask, they should probably add < 3 for now

An issue would be great 

> But (I think) this happens on any error, so it's unclear what the ultimate error is

Yeah, that appears to be the case. It'd be good to fix that. 


Also, it looks like we're giving conflicting versions in the 

```
Dask needs bokeh >= 2.1.1 for the dashboard.

Install with conda: conda install bokeh>=1.0

Install with pip: pip install bokeh>=2.1.1
```

message that's displayed. I've opened up https://github.com/dask/distributed/pull/7172 to improve the situation.

**Comment by bryevdv** [comment]
@jrbourbeau I think some work is needed on Dask side unfortunately. The "inconsistent lengths" console errors indicate a usage problem that might have been more loosely tolerated in the past.

**Comment by bryevdv** [comment]
@bokeh/core I propose to delay our release one week to allow dask to release a new version with a Bokeh version cap before we release 3.0

**Comment by mattpap** [comment]
> `id="bk-cluster-memory-plot"`

This should use `name` instead, or is there a reason to use `id`?

**Comment by mattpap** [comment]
In submitted PR #12505 to completely disallow mixing `id` with property initializers (as bokehjs already does since serialization/protocol redesign in PR #11960).

**Comment by bryevdv** [comment]
> This should use name instead, or is there a reason to use id?

I'm not sure, I didn't find any reference to the custom id (at least that one) from a quick search of the codbase. I think that setting a custom id used to also set a DOM id? Hopefully it was not being relied on for for that.

**Comment by bryevdv** [comment]
OK I guess I will close this as a `discussion` since we are not going to make any changes on our end. I will try to submit a PR this coming week or two to update Dask to work with both 2.x and 3.x (but I do still thing Dask should implement a version cap for their next release cc @jrbourbeau let me know if there is anything I can help with)

**Comment by jrbourbeau** [comment]
Taking a pass at updating `distributed` to work with `bokeh=3` in https://github.com/dask/distributed/pull/5648. I'm hopefully this will be straightforward-ish. If not then we can definitely add an upper bound for `bokeh`
