### ISSUE TITLE
Add support for Quarto notebooks [FEATURE] 

### ISSUE THREAD

**Issue by katossky** [bokeh/bokeh#12521]
### Problem description

Bokeh does not work with Quarto notebooks, as soon as they intertwine Python and other languages. (Python-only notebooks use Jupyter, and Bokeh then works just fine.)

### Feature description

`output_notebook()` is the function that sets the behaviour in notebooks, and it has been used for Jupyter and Zeppelin notebooks. It may be used for Quarto as well.

### Potential alternatives

The alternative is to not use Bokeh inside Quarto, or use complex workflows where one exports Bokeh plots as images/HTML files, etc. and imports/includes them in notebooks.

### Additional information

An other person asks for the feature here  : https://discourse.bokeh.org/t/bokeh-graphics-embedded-in-quarto-files/9445/5

This started as a conversation on the Quarto side about a bug when using Bokeh : https://github.com/quarto-dev/quarto-cli/issues/3083

**Comment by bryevdv** [comment]
As I stated in the linked issue, I think this is something that will have to be championed by someone on the Quarto side of things. We are happy to provide technical guidance, or open focused issues that precipitate out of that work
