### ISSUE TITLE
No bokeh_django on github or PyPI

### ISSUE THREAD

**Issue by bnavigator** [bokeh/bokeh#12530]
### Software versions

3.0.0

### Expected behavior

A valid link or no mention in https://docs.bokeh.org/en/latest/docs/releases.html

### Observed behavior

https://docs.bokeh.org/en/latest/docs/releases.html

> Django integration was moved to https://github.com/bokeh/bokeh-django

:x:  *HTTP 404*

https://pypi.org/search/?q=bokeh_django

:x: Nothing relevant found

### Example code

```Python
N/A
```

**Comment by bryevdv** [comment]
cc @philippjfr can I at least make the repo public today, or is there something that needs to wait on?

**Comment by bryevdv** [comment]
@bnavigator the repo now has public visibility, please submit further issues/questions specific to bokeh-django there.
