### ISSUE TITLE
Setting small plot_width or plot_height to categorical plot without min_border

### ISSUE THREAD

**Issue by yhey** [bokeh/bokeh#1254]
When setting `plot_width` or `plot_height` without `min_border` in `Plot()`, with either the width or height smaller than 80px, and the corresponding axis is categorical, BokehJS exits with "Error: unsatisfiable constraint" on browser console. For example:

    import numpy as np
    from bokeh.plotting import *
    from bokeh.objects import *
    
    from bokeh.browserlib import view
    from bokeh.document import Document
    from bokeh.embed import file_html
    from bokeh.resources import INLINE
    
    factors = ["a", "b", "c", "d", "e", "f", "g", "h"]
    x0 = [0,0,0,0,0,0,0,0]
    x =  [50, 40, 65, 10, 25, 37, 80, 60]
    
    plot = Plot(
        x_range=Range1d(start=0, end=100), y_range=FactorRange(factors=factors),
        title="", plot_width=80, plot_height=80,
        #min_border=2, border_symmetry=None,
    )
    
    segment(x0, factors, x, factors, plot=plot,
            line_width=2, line_color="green", title="Dot Plot")
    circle(x, factors, size=15, fill_color="orange", line_color="green", line_width=3,
           Name="categorical     example")
    
    doc = Document()
    doc.add(plot)
    
    filename = "test.html"
    with open(filename, "w") as f:
        f.write(file_html(doc, INLINE, "Test"))
    print("Wrote %s" % filename)
    view(filename)

If the x-axis (y-axis) has a label, then the plot height (width) needs to be proportionally larger to avoid the error.

In the case where `min_border` is /not/ set explicitly, it would be more intuitive for BokehJS to use a flexible `min_border` rather than a fixed (40px?) value. Or at least the default min_border should be clearly documented.

**Comment by damianavila** [comment]
We now have border documentation, but we should add the default 40px

http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#border

**Comment by damianavila** [comment]
Will be fixed in #2481
