### ISSUE TITLE
[BUG] AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width

### ISSUE THREAD

**Issue by Abonia1** [bokeh/bokeh#12543]
### Software versions

bokeh version:  3.0.0 
python : 3.9.0

### Jupyter notebook / Jupyter Lab version

VS jupyter notebook

### Expected behavior

It should show the plot

### Observed behavior

Error while excuting the code : 
AttributeError                            Traceback (most recent call last)
Cell In [53], line 1
----> 1 show_coverage_over_time(df_coverage, interval='day')

File ~/opt/anaconda3/envs/waenv/lib/python3.9/site-packages/assistant_improve_toolkit/visualize_func.py:389, in show_coverage_over_time(df_coverage, interval)
    385 coverage_data['Coverage'] = coverage_data['Coverage'].fillna(0)
    387 output_notebook(hide_banner=True)
--> 389 p = figure(plot_width=950, plot_height=350, x_axis_type="datetime",
    390            x_range=(start_datetime, end_datetime),
    391            y_range=(max(np.floor(coverage_data['Coverage'].min()) - 10, 0),
    392                     min(np.floor(coverage_data['Coverage'].max()) + 10, 100)), title='Coverage over time')
    394 p.line(x='response_datetime_interval', y='Coverage', source=coverage_data, line_width=1.5, color='#4fa8f6')
    396 p.xaxis.formatter = DatetimeTickFormatter(
    397     seconds=["%Y-%m-%d %H:%M:%S"],
    398     minsec=["%Y-%m-%d %H:%M:%S"],
   (...)
    404     years=["%Y-%m-%d %H:%M:%S"],
    405 )

File ~/opt/anaconda3/envs/waenv/lib/python3.9/site-packages/bokeh/plotting/_figure.py:184, in figure.__init__(self, *arg, **kw)
    182 for name in kw.keys():
    183     if name not in names:
--> 184         self._raise_attribute_error_with_matches(name, names | opts.properties())
    186 super().__init__(*arg, **kw)
...
    366 if not matches:
    367     matches, text = sorted(properties), "possible"
--> 369 raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")

AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width

### Example code

```Python
p = figure(plot_width=950, plot_height=350, x_axis_type="datetime",
                   x_range=(start_datetime, end_datetime),
                   y_range=(max(np.floor(coverage_data['Coverage'].min()) - 10, 0),
                            min(np.floor(coverage_data['Coverage'].max()) + 10, 100)), title='Coverage over time')
```

**Comment by bryevdv** [comment]
`plot_width` (and `plot_height`) were deprecated some time ago, and were finally removed in version 3.0. You will need to upate your code, please see the migration guide:

https://github.com/bokeh/bokeh/wiki/Migration-Guides#removals-
