### ISSUE TITLE
[FEATURE] Allow Datetime values as valid input in PolyAnnotation

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#12542]
### Problem description

Base on the codeof the `PolyAnnotation` example you can see, that only floats are allowed as input for `xs` and `ys`.

```
from datetime import datetime as dt

import pandas as pd

from bokeh.models import PolyAnnotation
from bokeh.plotting import figure, show
from bokeh.sampledata.stocks import GOOG

p = figure(height=200, x_axis_type="datetime",
           background_fill_color="#efefef", title="Google stock")

df = pd.DataFrame(GOOG)
df["date"] = pd.to_datetime(df["date"])

p.line(df["date"], df["close"], line_width=1.5, color="grey")

start_date = dt(2008, 11, 24)
start_x = start_date.timestamp() * 1000
start_y = df.loc[df["date"] == start_date]["close"].values[0]

end_date = dt(2010, 1, 4)
end_x = end_date.timestamp() * 1000
end_y = df.loc[df["date"] == end_date]["close"].values[0]

polygon = PolyAnnotation(
    fill_color="blue", fill_alpha=0.2,
    xs=[start_x, start_x, end_x, end_x],
    ys=[start_y - 100, start_y + 100, end_y + 100, end_y - 100],
)
p.add_layout(polygon)

show(p)
```

Because the plot has allready the `x_axis_type="datetime"` I think it is valid to assume that datetime values should be valid, too.

### Feature description

Change 

https://github.com/bokeh/bokeh/blob/9f00012c81ac0410562a3aaf5d04ccb92b3e8fc9/src/bokeh/models/annotations/geometry.py#L204

and allow `Datetime` as valid input.

**Comment by mosc9575** [comment]
@bryevdv Sorry to ask for your help, but this PR shouldn't be closed. This is just a proposal and I do not know, if you want to add this to bokeh. Could you please re-open this ticket or leave a comment?

**Comment by bryevdv** [comment]
It's pretty annoying that GH closed the issue here for a PR merged on a fork?

**Comment by mattpap** [comment]
Closing in favour of issue #12540.
