### ISSUE TITLE
VBox doesn't work properly under IE

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1256]
It basically behaves as a `HBox`.

**Comment by damianavila** [comment]
status: low priority

**Comment by bryevdv** [comment]
Need more information and testing to clarify when problem occurs

**Comment by almarklein** [comment]
I looked into this and get this:

- on IE 8 nothing is shown
- on IE 9 a HBox shows as if it were a VBox
- on IE 10 and IE 11 all is fine

How widely used is IE 9? Should we even bother?

**Comment by mattpap** [comment]
Perhaps not, see e.g. http://www.w3counter.com/globalstats.php.

**Comment by almarklein** [comment]
Strange, how come IE 9 is in the list, and not IE 10? But yeah 2.3% (and decreasing) would be an ok argument to not bother IMO. I mean, people who want to show viz in the browser may be expected to have a non-ancient browser.

**Comment by damianavila** [comment]
> I mean, people who want to show viz in the browser may be expected to have a non-ancient browser.

:+1:

**Comment by fpliger** [comment]
> I mean, people who want to show viz in the browser may be expected to have a non-ancient browser.

+1

**Comment by bryevdv** [comment]
I'm comfortable saying we don't support IE9.

**Comment by birdsarah** [comment]
> How widely used is IE 9? Should we even bother?

One comment on this, is that we should perhaps be a little more nuanced than globalstats. My experience is that it really varies by user. In particular, US Government agencies, are often really behind, and projects with them as a stakeholder often need IE8 support.

You may be interested in this fun notebook I made (with bokeh) http://nbviewer.ipython.org/urls/dl.dropbox.com/s/ew5potk31fhujub/IE8%20%26%20IE9%20Share.ipynb?dl=0

which breaks these numbers out by geography.

**Comment by birdsarah** [comment]
in particular showing ie8 & ie9 penetration

**Comment by bryevdv** [comment]
@birdsarah weird I get a 503 viewing that URL

**Comment by birdsarah** [comment]
i was having loads of 503 with nbviewer yesterday....the nb link is: https://dl.dropboxusercontent.com/s/ew5potk31fhujub/IE8%20%26%20IE9%20Share.ipynb?dl=0

i made this in jan 2015, i could update it with newer stats.

**Comment by birdsarah** [comment]
Bokeh doesn't seem to work at all with IE9, so I would suggest this issue is now dead.

**Comment by almarklein** [comment]
I can imagine that we've neglected IE9 over time, thereby making it not work on it. Maybe its worth trying to get core BokehJS work on it again?

**Comment by modqhx** [comment]
I'm having similar issue on chrome:
```
ImportError: cannot import name HBox
```
Bokeh v 0.11.1

**Comment by canavandl** [comment]
Hi @modqhx 

Can you give us a code example or the command you're using to raise that error? In 0.11.1, `HBox` moved from `bokeh.models.widgets` to `bokeh.models.layouts`, but we tried to add a deprecation cycle that'd still work.

**Comment by birdsarah** [comment]
Confirm as part of #4392

**Comment by birdsarah** [comment]
Two new layout tests work on IE10 so am assuming this is solved.
Bokeh doesn't work on IE9 get console error "Float64Array is undefined" - this isn't a layout problem.
So marking this as solved, probably due to #4343.

![ie10screenshot-2](https://cloud.githubusercontent.com/assets/1796208/16078456/f287509e-32b3-11e6-971d-faaed1807d46.png)
![ie10screenshot](https://cloud.githubusercontent.com/assets/1796208/16078457/f2a66e02-32b3-11e6-9832-a5ea18293200.png)

IE9 error screenshot

![ie9 error](https://cloud.githubusercontent.com/assets/1796208/16078465/fcd5af28-32b3-11e6-8674-f3787c83a584.png)
