### ISSUE TITLE
[BUG] `bokeh.core.json_encoder.serialize_json` doesn't work as shown in example

### ISSUE THREAD

**Issue by mcrot** [bokeh/bokeh#12574]
### Software versions

Python version      :  3.8.10 (default, Jun 22 2022, 20:18:18) 
IPython version     :  8.5.0
Tornado version     :  6.2
Bokeh version       :  3.0.1
BokehJS static path :  /home/michael/somelocalpath/venv/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.4.0-131-generic-x86_64-with-glibc2.29

And: Numpy version: 1.23.3

### Expected behavior

The documentation for the module [`bokeh.core_json_encoder`](https://docs.bokeh.org/en/latest/docs/reference/core/json_encoder.html) provides a function `serialize_json`.  I need this function in order to serialize arrays.

The example in the docs is
```python
data = dict(b=np.datetime64('2017-01-01'), a = np.arange(3))

>>>print(serialize_json(data))
{"a":[0,1,2],"b":1483228800000.0}
```
I expect that I get the same output as in this example.

### Observed behavior

I get an exception: 
```python
>>> print(serialize_json(data))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/somelocalpath/venv/lib/python3.8/site-packages/bokeh/core/json_encoder.py", line 150, in serialize_json
    return encoder.encode(content)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/michael/somelocalpath/venv/lib/python3.8/site-packages/bokeh/core/json_encoder.py", line 170, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime64 is not JSON serializable
```

If I try to convert the numpy array only, I get a similar exception
```python
TypeError: Object of type ndarray is not JSON serializable
```
(See also minimal example below)

### Example code

```Python
import numpy as np
from bokeh.core.json_encoder import serialize_json

data = dict(a=np.arange(3))

print(serialize_json(data))
```

### Stack traceback or browser console output

Here the traceback for my minimal example code:

```python
Traceback (most recent call last):
  File "bokeh-problem.py", line 6, in <module>
    print(serialize_json(data))
  File "/home/michael/somelocalpath/venv/lib/python3.8/site-packages/bokeh/core/json_encoder.py", line 150, in serialize_json
    return encoder.encode(content)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/michael/somelocalpath/venv/lib/python3.8/site-packages/bokeh/core/json_encoder.py", line 170, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```

**Comment by mcrot** [comment]
Before, in bokeh 3.0.0.dev4 I've used the class `bokeh.core.BokehJSONEncoder` in my code, which did the job, but this seems to have been removed with the 3.0.1 release.

**Comment by mattpap** [comment]
`serialize_json()`'s semantics changed, but it looks like the docstring wasn't updated. Now serialization is performed by new `Serializer` class and `serialize_json()` is used only generate a JSON string out of an intermediate representation generated by the serializer. Here's the new usage:
```py
In [1]: import numpy as np

In [2]: from bokeh.core.serialization import Serializer

In [3]: from bokeh.core.json_encoder import serialize_json

In [4]: s = Serializer()

In [5]: o = s.encode(np.arange(3))

In [6]: o
Out[6]: 
{'type': 'ndarray',
 'array': {'type': 'bytes',
  'data': Buffer(id='p1000', data=<memory at 0x7fdda72dd840>)},
 'shape': [3],
 'dtype': 'int32',
 'order': 'little'}

In [7]: serialize_json(o)
Out[7]: '{"type":"ndarray","array":{"type":"bytes","data":"AAAAAAEAAAACAAAA"},"shape":[3],"dtype":"int32","order":"little"}'
```
or you can skip `serialize_json()` altogether with:
```py
In [1]: import numpy as np

In [2]: from bokeh.core.serialization import Serializer

In [3]: import json

In [4]: s = Serializer(deferred=False)

In [5]: o = s.encode(np.arange(3))

In [6]: json.dumps(o)
Out[6]: '{"type": "ndarray", "array": {"type": "bytes", "data": "AAAAAAEAAAACAAAA"}, "shape": [3], "dtype": "int32", "order": "little"}'
```

**Comment by bryevdv** [comment]
> Before, in bokeh 3.0.0.dev4...  seems to have been removed with the 3.0.1 release.

Just clarifying the change happened at 3.0.0 (after some earlier dev build but before the actual release), not 3.0.1

**Comment by mcrot** [comment]
Thanks @mattpap and @bryevdv, this makes it clear for me. Now I see there is also a `Deserializer`, which I probably need to do it the other way round:
```python
from bokeh.core.serialization import Deserializer
d = Deserializer()
print(d.decode(json.loads(o))   # with o from mattpap's example code
```
