### ISSUE TITLE
embedding using matplotlib compatibility layer

### ISSUE THREAD

**Issue by M4urice** [bokeh/bokeh#1257]
Is it possible to use the matplotlib/pandas compatibility layer  `bokeh.mpl.to_bokeh` (http://bokeh.pydata.org/docs/reference/compat.html?highlight=matplotlib) to get components as returned by `bokeh.embed.components` (http://bokeh.pydata.org/docs/reference/resources_embedding.html#bokeh.embed.components)?

**The task I try to achieve:** I already have a number of pandas dataframes and want to plot them as part of a webpage (being interactive using bokehjs).

**Comment by damianavila** [comment]
`mpl.to_bokeh` returns a plot since #1634, so now it is possible to embed the plot. This can be closed now.
