### ISSUE TITLE
MPL compat layer: Legend element FancyBboxPatch not impemented

### ISSUE THREAD

**Issue by twiecki** [bokeh/bokeh#1258]
I'm running the most recent bokeh from within IPython NB. Using `mpl.to_bokeh()` even on simple plots raises:
```
/home/wiecki/envs/zipline_p14/lib/python2.7/site-packages/bokeh/mplexporter/exporter.py:173: UserWarning: Legend element FancyBboxPatch(337.069,248;89.375x34.4444) not impemented
  warnings.warn("Legend element %s not impemented" % child)
```
And shows no plot.

**Comment by bryevdv** [comment]
Closing as upstream. The core team is not going to spend anymore effort on MPL compat until (if) MEP 25 is realized.
