### ISSUE TITLE
[BUG] MultiChoice dropdown and autocomplete

### ISSUE THREAD

**Issue by RuWi2210** [bokeh/bokeh#12584]
### Software versions

Python version      :  3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.1
BokehJS static path :  C:\Users\sam\Documents\GitHub\Dashboard\lib\site-packages\bokeh\server\static
node.js version     :  v18.12.1
npm version         :  8.19.2
Operating system    :  Windows-10-10.0.19044-SP0

### Expected behavior

Expected the options to be sorted by default. Also I expect the dropdown to show options matching input text. E.g. When I type "t", the dropdown should show "two", "three" and "ten" in the example below.
The above behaviors were observed in 2.4.3

### Observed behavior

When clicking to reveal the dropdown the options are not sorted.
Whenever I type anything in the box, it shows "No results found" instead of the options matching the input.

### Example code

```Python
from bokeh.models import MultiChoice
from bokeh.io import show

options = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]
multi = MultiChoice(value=[], options=options, width=300)

show(multi)
```

### Screenshots

Example showing that the options are not sorted.
![Capture](https://user-images.githubusercontent.com/112623127/200856932-785c7a90-3bf6-46ba-9265-fa75c3a1d960.PNG)

Example showing that autocomplete of input does not work. The input is "t" and there are several options containing that letter, e.g. "two", "three" and "ten".
![Capture2](https://user-images.githubusercontent.com/112623127/200857125-8b9c97f5-7b45-4d21-aecc-290d2ec774a2.PNG)

**Comment by mattpap** [comment]
> When clicking to reveal the dropdown the options are not sorted.

That was done on purpose in https://github.com/bokeh/bokeh/pull/11663. Providing options via a list indicates an order, so sorting by default is not the right thing to do. However, we can expose a property to allow to configure this behavior.

> Whenever I type anything in the box, it shows "No results found" instead of the options matching the input.

This looks like a regression.
