### ISSUE TITLE
Don't delete importlib.metadata in __init__.py

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12587]
We currently clean up `importlib.metadata` in our top-level module, and this can apparently break it for any subsequent use (e.g. by other packages in a Bokeh server app)

ref: https://discuss.python.org/t/module-importlib-has-no-attribute-metadata/20947/1

@bokeh/core I think for now we can wait for a planned 3.1 or 3.0.2 release right after new years, but if we see an uptick in reports about this I would push a 3.0.2 sooner.

**Comment by bryevdv** [comment]
For completeness here is an MRE and I can confirm that making the change described above fixes:
```
#!/usr/bin/env python

# Minimum Reproducible Example for
# Interactive viewer for mapping collections of dvm-dos-tem input datasets.

import os

from osgeo import gdal
from osgeo import osr

import shapely

import geojson
import json
import glob

import bokeh
from bokeh.io import output_file, show, curdoc, save
from bokeh.models.sources import GeoJSONDataSource
from bokeh.models import HoverTool, TapTool, Patches
from bokeh.models.callbacks import CustomJS
from bokeh.plotting import figure

import pyproj

print(bokeh.__version__)

p = figure()

curdoc().add_root(p)
```

**Comment by dopplershift** [comment]
Well, `del importlib.metadata` isn't even cleaning up your namespace, it's just deleting the `.metadata` attribute (whatever it happens to be) from the `importlib` object (which happens to be a module). The right way to clean up the namespace would be `del importlib`.

**Comment by bryevdv** [comment]
@bokeh/core given there is not actually any WAR I can think of for this, I would propose a 3.0.2 early next week.
