### ISSUE TITLE
[BUG] line_policy='none' for HoverTool does not generate any tooltip in 3.0.1

### ISSUE THREAD

**Issue by AliSamiiXOM** [bokeh/bokeh#12585]
### Software versions

Python version      :  3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]
IPython version     :  8.6.0
Tornado version     :  6.2
Bokeh version       :  3.0.1
BokehJS static path :  /home/alsamii/conda3/envs/ml/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.11.0
npm version         :  8.19.2
Operating system    :  Linux-5.15.0-1022-azure-x86_64-with-glibc2.31

### Browser name and version

Google Chrome Version 107.0.5304.87 (Official Build) (64-bit)

### Jupyter notebook / Jupyter Lab version

3.5.0

### Expected behavior

In version 2.4.3 I was able to use `line_policy='none'` in HoverTool, to get a tooltip that followed the mouse. But after I upgraded to 3.0.1, the following code does not generate any tooltip.

### Observed behavior

By running the example code, the tooltip does not show up in version 3.0.1, but I am able to get the tooltip in v2.4.3.

### Example code

```Python
import bokeh.plotting as bokplt
import bokeh.models as bokm
import bokeh.io as bokio

bokio.reset_output()
bokio.output_notebook()

p = bokplt.figure(width=800, height=200)

coord_hover_line = p.line(x=[0,100], y=[10, 5], alpha=0.0)

p.add_tools(bokm.HoverTool(
    tooltips=[("x ", "$x{0.0}")],
    renderers=[coord_hover_line],
    mode='vline',
    line_policy='none',
))

p.add_tools(bokm.CrosshairTool(dimensions="height", line_alpha=0.2))

bokio.show(p)
```

**Comment by bryevdv** [comment]
@AliSamiiXOM please edit the issue to have a meaningful title.

>  At least, this was what I was getting with version 2.4.3. After upgrading to 3.0.1, the tooltip follows the line. 

Also, you re going to need to provide some screenshots or video. I just tried your code above with 2.4.3 and 3.0.1 and it behaved identically (and as expected) in both cases for me. The tooltip stayed with the line with both (which is the behavior for as long back as I can recall).

**Comment by AliSamiiXOM** [comment]
Here are two screenshots with the example code:

Version 2.4.3:
![image](https://user-images.githubusercontent.com/89590437/200944245-8d67e0f7-9d33-4fe9-9551-e54aa1e026fb.png)

Version 3.0.1:
![image](https://user-images.githubusercontent.com/89590437/200944274-d7a0041a-9d8e-4564-b91b-ace5df985deb.png)

**Comment by bryevdv** [comment]
@AliSamiiXOM It seems your issue is with the crosshair tool and has nothing to do with the hover tool. Please add actual code as text, so that we can copy and paste and actually run to investigate. (In general: please never post *images* of code as they are not accessible).

**Comment by bryevdv** [comment]
@AliSamiiXOM This appears to because of the `line_policy="none"` that you have changed to. I am not actually sure what that would do. This code with "interp" works for as expected for me:
```
import bokeh.plotting as bokplt
import bokeh.models as bokm
import bokeh.io as bokio

p = bokplt.figure(width=800, height=200)

coord_hover_line = p.line(x=[0,100], y=[10, 5], alpha=0.0)

p.add_tools(bokm.HoverTool(
    tooltips=[("x ", "$x{0.0}")],
    renderers=[coord_hover_line],
    mode='vline',
    line_policy='interp',
))

p.add_tools(bokm.CrosshairTool(dimensions="height", line_alpha=0.2))

bokio.show(p)
```

**Comment by AliSamiiXOM** [comment]
From what I see on surface, if I change from `line_policy='none'` to `line_policy='interp'`, I can see `CrosshairTool` working completely fine (with the correct tooltip). So, that is why I reported the issue with HoverTool. Now, this might be an interplay between CrosshairTool and HoverTool, such that `none` option does not produce tooltip, but `interp` does.

**Comment by bryevdv** [comment]
@mattpap what is `"none"` supposed to do?  Currently it explodes in the JS console with "This shouldn't happen" I am not sure that "none" should even be an option.

**Comment by AliSamiiXOM** [comment]
@bryevdv , did you run the code with 2.4.3 as explained in the ticket? It was working fine in that version , and the result was different than `interp`.

**Comment by bryevdv** [comment]
@AliSamiiXOM I did run it. I think what you consider "working"  was actually a bug:

>  If it did that in the past think it was a bug at that time.

There would need to be a separate indepedent property to control the position of the hover tooltip in the transverse direction. One property is not sufficient.

**Comment by AliSamiiXOM** [comment]
@bryevdv , not sure if it was a bug. It was a perfectly fine option, that worked consistently well. Actually the location of the tooltip is under the cursor, and without any specific treatment it should have been placed under the cursor, hence the name `none`. Now, if there is no other property to control the position, why the support for this option was discontinued?

**Comment by bryevdv** [comment]
"none" was never explicitly handled. There was a `default` case in `branch-2.4`

https://github.com/bokeh/bokeh/blob/e8c895f15d2f9ad456e1caf71c16c0f5de8d011b/bokehjs/src/lib/models/tools/inspectors/hover_tool.ts#L292-L324

That is gone in the current branch:

https://github.com/bokeh/bokeh/blob/5204d0ee6d87c66d416a021e0a34389c20dd31b5/bokehjs/src/lib/models/tools/inspectors/hover_tool.ts#L283-L306

**Comment by bryevdv** [comment]
> @bryevdv , not sure if it was a bug. It was a perfectly fine option,

@AliSamiiXOM I am not sure why you are arguing with me over this point. I wrote the tool originally. I am *stating* that it was a bug, because the only thing that `line_policy` was ever intended to cover was the position *along the line*. 

Which is not to say that there should not be some way to accomplish what you want, but it should not be by using `line_policy`.

**Comment by bryevdv** [comment]
@AliSamiiXOM We will have to investigate. We may have to add something new. Or perhaps we will just add back explicit handling of `none`, and leave a more thorough rework of the hover tool for some later time. If I squint hard enough at the current help string for `line_policy` perhaps the previous behavior of `"none"` can be justified (but it would need documentation added). I supposed that would probably be least disruptive to users. If that happens it would be in a 3.0.1 release in ~6-7 weeks.

**Comment by AliSamiiXOM** [comment]
@bryevdv , thank you, for the help.
