### ISSUE TITLE
Styling of multiline mathtext not correct

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12594]
`text_font_style` of multiline mathtext titles is not applied correctly to all lines, as identified in #12572. Here is the example image which is using `p.title.text_font_style = "normal"` but only the first line is rendered normal and the other two as the default title bold.

![err](https://user-images.githubusercontent.com/580326/201428631-3e29061b-ea6e-4682-abd5-f176f77b22a2.png)

**Comment by mattpap** [comment]
Those are actually three awkwardly arranged titles, thus font style is applied only to the first. The bigger problem is lack of any sort of line breaking in MaxJax, which is apparently a know missing feature in v3.

**Comment by mattpap** [comment]
I improved the example in PR #12572.

**Comment by ianthomas23** [comment]
@mattpap Thanks for clarifying the situation and for fixing the example in PR #12572. I jumped to conclusions about the problem without fully checking.

This issue isn't really an issue now, or its an issue about a choice of two different problem, either multiline mathtext labels or compound labels including both normal text and mathtext. I think what I will do is open a new discussion summarising the state of mathtext support in Bokeh and listing what we would like to support/improve in future. I'll keep this issue open until then as a reminder to myself.

**Comment by ianthomas23** [comment]
Closing this as it is now included in the MathText discussion #12632.
