### ISSUE TITLE
More neutral install instructions

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12595]
Our various install instructions have comments like

> The easiest way to install Bokeh is to use conda. Conda is part of the [Anaconda Python Distribution](http://anaconda.com/anaconda), which is designed with scientific and data analysis applications like Bokeh in mind.

and then also position `conda` instructions first. This slightly preferential treatment dates back to very early days when Bokeh was wholly supported by Anaconda (but was also motivated by genuine technical reasons&mdash;wheel packages were not available until recently). However, I think in general at this point our stance should be completely neutral on installs.

But furthermore, I would also suggest positioning the `pip` install instructions first. And the reason is that it can take weeks or more for a new release of Bokeh to show up in Anaconda defaults these days, and I am very tired of having to do the "It's simple! Just `conda install bokeh` oh except right after  a release maybe `conda install -c bokeh bokeh`" dance. 

cc @tcmetzger

**Comment by tcmetzger** [comment]
I agree. This could also reflect the fact that we see just a higher number of installs from pip than from conda!
