### ISSUE TITLE
Grid attribute not taken into account if show() is not called

### ISSUE THREAD

**Issue by humm** [bokeh/bokeh#1259]
The following code displays the grid as grey: 

```python
from bokeh.plotting import *

output_server('bug')
hold()
scatter([0.0], [0.0], x_range=[-1.0, 1.0], y_range=[-1.0, 1.0])
grid().grid_line_color='white'

#show()
```

Uncommenting the `show()` call displays the grid as white. Seems unexpected

On OS X 10.9.5, with Chrome 37.0.2062.122.
```
    Bokeh Server Configuration
    ==========================
    python version : 2.7.6
    bokeh version  : 0.6.0-125-g08a6903-dirty
    listening      : 127.0.0.1:5006
    backend        : shelve
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF
    data-directory : None
```

**Comment by damianavila** [comment]
>but in general it would still be the case that any property changes after a show/push would require another one before the changes show up, and that is perhaps the core of the issue.

and this would not be the expected behaviour? I mean... after changes properties make a show/push to actually see it...

**Comment by humm** [comment]
I actually was not aware that a `push()` function existed in the `bokeh.plotting` interface (it is not documented there, but is in the `bokeh.session` one, as a low-level function). Talking about it as an alternative to `show` in the tutorial and using it in an example would fix that.

Using `push` after setting properties seems entirely ok, rather than triggering a `push` for setting properties, which may result in many `push` calls if many properties are set.
