### ISSUE TITLE
[BUG] sdist install fails with --no-binary

### ISSUE THREAD

**Issue by TimoRoth** [bokeh/bokeh#12601]
### Software versions

All Python versions are similarly affected.
Ones without easily available wheels (for example Pyston) a lot worse though.

### Expected behavior

Installing bokeh without the use of binary wheels should succeed.

### Observed behavior

```
Collecting bokeh
  Downloading bokeh-3.0.1.tar.gz (15.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 65.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
      Collecting setuptools>=64
        Using cached setuptools-65.5.1.tar.gz (2.6 MB)
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools-git-versioning
        Downloading setuptools-git-versioning-1.11.0.tar.gz (10 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [8 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-fm8vdn8q/setuptools-git-versioning_7f0d0be05fad4a0f8518e6263fd1d55e/setup.py", line 3, in <module>
                from setuptools_git_versioning import version_from_git
              File "/tmp/pip-install-fm8vdn8q/setuptools-git-versioning_7f0d0be05fad4a0f8518e6263fd1d55e/setuptools_git_versioning.py", line 18, in <module>
                from deprecated import deprecated
            ModuleNotFoundError: No module named 'deprecated'
            [end of output]
```

This is happening because setuptools-git-versioning at build time depends on https://pypi.org/project/Deprecated/ but seems to make no effort to properly declare this dependency.
An upstream issue has been raised about this already, but doesn't seem fruitful: https://github.com/dolfinus/setuptools-git-versioning/issues/72

### Example code

```Python
`pip install --no-binary :all: bokeh`
```

**Comment by bryevdv** [comment]
@TimoRoth I'm sorry, what actual command are you running? I have installed Bokeh 3.0.1 using `pip` many times at this point. Are you saying you are trying to install the `sdist`? or something else?

**Comment by bryevdv** [comment]
TBH I am not sure what we could do besides wholelsale vendoring of `setuptools-git-versioning` if they do not decide to consider publishing their sdists again. There is absolutely no way I would consider going back to `versioneer`.

**Comment by TimoRoth** [comment]
The simplified command boils down to `pip install --no-binary :all: bokeh`, as per the example above.
In reality this is happening as part of a much more involved build process which builds the entire toolchain from source, and is not even pulling in bokeh directly, but as dependency of a dependency:
https://github.com/OGGM/r2d/actions/runs/3449532207/jobs/5757527685#step:6:1589

**Comment by bryevdv** [comment]
@TimoRoth I do hope we are able to reach some satisfactory conclusion, but I do want to be up-front about expectations.   There is basically zero chance any fix for this will end up in 3.0.2 early next week, and then there probably won't be another release until mid-January, barring some critical blocker that affects all (or at least *most* users). It seems that some WARs were suggested in the linked issue, I do advise that you try to engage those for the immediate term.

**Comment by TimoRoth** [comment]
On 13.11.2022 01:00, Bryan Van de Ven wrote:
> @TimoRoth <https://github.com/TimoRoth> I do hope we are able to reach 
> some satisfactory conclusion, but I do want to be up-front about 
> expectations. There is basically zero chance any fix for this will end 
> up in 3.0.2 early next week, and then there probably won't be another 
> release until mid-January, barring some critical blocker that affects 
> all (or at least /most/ users). It seems that some WARs were suggested 
> in the linked issue, I do advise that you try to engage those for the 
> immediate term.

I've spent literal months getting a working toolchain for all of this 
working.
Unfortunately, just using wheels does not work, since then competing 
wheels bring their own, incompatible, binary dependencies with them, and 
when loading them into the same process at runtime, things go very wrong.

Not using build isolation also does not work, it just causes other 
confusing issues (and inflates the image size).

I'm perfectly fine with pulling a development version until things make 
it into a release.

**Comment by bryevdv** [comment]
> I've spent literal months getting a working toolchain for all of this working. 

I sympathize implicitly, however I would be remiss if I was not completely frank with my thoughts, too. The entire Python packaging community has more or less been working for years to make it so that end-users building from source is not really necessary (if not outright discouraged).  You are definitely swimming against the tide, so to speak, with this approach. 

> I'm perfectly fine with pulling a development version until things make it into a release.

Can you elaborate on the specifics of this statement? I can imagine at least three different meanings to this and not all of them would be workable.

**Comment by TimoRoth** [comment]
> Can you elaborate on the specifics of this statement? I can imagine at 
> least three different meanings to this and not all of them would be 
> workable.

I just don't care if there's a release with a fix or not.
If it's fixed _somewhere_, I can just use that.

Whenever it makes it into a release I can just revert back to normal.
