### ISSUE TITLE
[BUG]  Runtime error of incorrect option name crashes webapp (Angular)

### ISSUE THREAD

**Issue by ddkn** [bokeh/bokeh#12617]
### Software versions

node.js : 14.21.1 (lts/fermium)

### Browser name and version

Firefox 102.4

### Expected behavior

I am building a webapp in Angular 14 using `npx ng serve`, which is normally a typescript project. If I create a figure with an object with an incorrect parameter, *e.g.,* Line, I would expect the compiler to yell about an incorrect option being passed and fail to build, or expect that figure object wouldn't render.

### Observed behavior

The project builds fine, but the webapp renders absolutely nothing. As the console spits out an error on runtime that the argument passed is invalid. See screenshots section shows an example of passing `apple: 3` to a Line object, but this could be easily mistaken by a mistype of an option such as `linewidth` when it should be `line_width`.

### Example code

You can get a system up and going from [here](https://discourse.bokeh.org/t/angular-10-bokeh-bokehjs-not-compiling-or-with-webpack/9469/6) and [here](https://discourse.bokeh.org/t/angular-14-bokeh-bokehjs-3/9742/2)

```Python
/* angular14/bokehdemo/src/app/plot/plot.component.ts */
import { Component, OnInit } from '@angular/core';
import * as Bokeh from '@bokeh/bokehjs/build/js/lib/api';

@Component({
  selector: 'app-plot',
  templateUrl: './plot.component.html',
  styleUrls: ['./plot.component.scss']
})
export class PlotComponent implements OnInit {

  constructor() { 
    const plt = Bokeh.Plotting;
    const la = Bokeh.LinAlg;
    
    let x = la.linspace(0, 10, 20);
    let y = x.map(function(v: number) { return v**2 });

    let source = new Bokeh.ColumnDataSource({
      data: {x: x, y: y}
    });
    
    let tools = "pan,crosshair,wheel_zoom,box_zoom,reset,save";
    let p = plt.figure({title: "Test", tools: tools});
    
    let line = p.line(
      {field: 'x'},
      {field: 'y'},
      {source: source, linewidth: 2}, /*WARN incorrect parameter should be line_width */
    );

    plt.show(p, '#bokeh-chart');
  }

  ngOnInit(): void {
  }

}
```

### Stack traceback or browser console output

See the screenshots, but compilation shows no errors. **Whether or not this is an issue with how the Angular build system works with javascript libraries is to be determined on my end.** However, handling incorrect parameters so that build systems see them would be useful.

This may be something related to creating a angular specific package that uses the typescript of bokehjs. 

### Screenshots

![image](https://user-images.githubusercontent.com/13819239/201991850-30ac3c8f-a1fb-4e68-a8c1-339bded1fbce.png)

**Comment by mattpap** [comment]
> `import * as Bokeh from '@bokeh/bokehjs/build/js/lib/api';`

Does this pull in any type declarations for bokehjs in your setup? If so then `linewidth` or any other kind of misspelling like this should be a type error.

**Comment by mattpap** [comment]
Not that `*.d.ts` files are stored separately from `*.js` file, under `build/js/types`. We provide
```json
"types": "build/js/types/bokeh.d.ts",
```
in `package.json`, so those type declaration should be resolved. That probably doesn't without setting up `paths` in `tsconfig.json` for deep imports. Probably this wasn't the best idea to keep those files separate.

**Comment by bryevdv** [comment]
> Probably this wasn't the best idea to keep those files separate.

Are you saying we can make some change? Statements like this are extremely ambiguous. What are the options for actions we can take to help users better?

**Comment by ddkn** [comment]
@mattpap thanks for getting back, I did have to add a separate file in the angular project directory *<PRJ_ROOT>/src/bokehjs.d.ts*, which has the declaration,

```
/* bokehjs.d.ts */
declare module '@bokeh/bokehjs/build/js/lib/embed';
declare module '@bokeh/bokehjs/build/js/lib/client';
declare module '@bokeh/bokehjs/build/js/lib/document';
declare module '@bokeh/bokehjs/build/js/lib/core';
declare module '@bokeh/bokehjs/build/js/lib/api';
declare module '@bokeh/bokehjs/build/js/lib/protocol';
declare module '@bokeh/bokehjs/build/js/lib/models';
```

in order to even `import * as Bokeh from '@bokeh/bokehjs/build/js/lib/api';`

> Not that *.d.ts files are stored separately from *.js file, under build/js/types.

Hm, I didn't realize this. I can try and import or pass that to tsconfig and see what happens. I think typically people import @types/<package> for this, so being built in may be something to document.

Ideally it would be nice to not have the `build/js/lib` parts of the import from the @bokeh/bokeh package.

> in package.json, so those type declaration should be resolved. That probably doesn't work without setting up paths in tsconfig.json for deep imports. Probably this wasn't the best idea to keep those files separate.

Deep imports? I think the compiler was complaining about this. I will report back later with an error message.

**Comment by ddkn** [comment]
Thanks @mattpap! (Just been busy with grad school and work, will be back on bokeh soon, life got in the way).
