### ISSUE TITLE
light_minimal theme is missing

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12610]
It accidentally duplicates the caliber theme due to a copy-pasta. 

ref: https://github.com/bokeh/bokeh/pull/12605/files#r1020946545

This was noticed in #12605 and is fixed by that PR if it is merged

**Comment by mattpap** [comment]
Is `python` auto-applied by github, like `dependencies`? I don't recall this ever used before.

**Comment by bryevdv** [comment]
No, I'm just trying to start being more thorough about noting what part of the codebase changes are primarily for
