### ISSUE TITLE
[BUG] installing bokehjs from npm doesn't pull in dependencies

### ISSUE THREAD

**Issue by ddkn** [bokeh/bokeh#12616]
### Software versions

node.js : v14.21.1 + v 16.18.1 (lts/fermium, lts/gallium from nvm)
Angular : v14

### Expected behavior

Running an Angular 14 webapp, and found that running `npx npm install @bokeh/bokehjs` to install the package and all corresponding dependencies.

Include the package in the angular code, and run `npx ng serve`.

### Observed behavior

Compiling the webapp showed the error message,

```
./node_modules/@bokeh/bokehjs/build/js/lib/core/ui_events.js:1:0-30 - Error: Module not found: Error: Can't resolve 'hammerjs' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/core'

./node_modules/@bokeh/bokehjs/build/js/lib/core/util/projections.js:1:0-35 - Error: Module not found: Error: Can't resolve 'proj4/lib/core' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/core/util'

./node_modules/@bokeh/bokehjs/build/js/lib/core/util/projections.js:2:0-40 - Error: Module not found: Error: Can't resolve 'proj4/lib/Proj' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/core/util'

./node_modules/@bokeh/bokehjs/build/js/lib/core/util/spatial.js:1:0-32 - Error: Module not found: Error: Can't resolve 'flatbush' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/core/util'

./node_modules/@bokeh/bokehjs/build/js/lib/core/util/templating.js:1:0-40 - Error: Module not found: Error: Can't resolve '@bokeh/numbro' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/core/util'

./node_modules/@bokeh/bokehjs/build/js/lib/core/util/templating.js:2:0-51 - Error: Module not found: Error: Can't resolve 'sprintf-js' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/core/util'

./node_modules/@bokeh/bokehjs/build/js/lib/core/util/templating.js:3:0-26 - Error: Module not found: Error: Can't resolve 'timezone' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/core/util'

./node_modules/@bokeh/bokehjs/build/js/lib/models/formatters/datetime_tick_formatter.js:9:0-26 - Error: Module not found: Error: Can't resolve 'timezone' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/formatters'

./node_modules/@bokeh/bokehjs/build/js/lib/models/formatters/numeral_tick_formatter.js:3:0-40 - Error: Module not found: Error: Can't resolve '@bokeh/numbro' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/formatters'

./node_modules/@bokeh/bokehjs/build/js/lib/models/glyphs/webgl/regl_wrap.js:1:0-30 - Error: Module not found: Error: Can't resolve 'regl' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/glyphs/webgl'

./node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax/index.js:1:0-53 - Error: Module not found: Error: Can't resolve 'mathjax-full/js/mathjax.js' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax'

./node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax/index.js:2:0-51 - Error: Module not found: Error: Can't resolve 'mathjax-full/js/input/tex.js' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax'

./node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax/index.js:3:0-54 - Error: Module not found: Error: Can't resolve 'mathjax-full/js/input/mathml' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax'

./node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax/index.js:5:0-52 - Error: Module not found: Error: Can't resolve 'mathjax-full/js/output/svg.js' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax'

./node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax/index.js:6:0-73 - Error: Module not found: Error: Can't resolve 'mathjax-full/js/adaptors/browserAdaptor' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax'

./node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax/index.js:7:0-71 - Error: Module not found: Error: Can't resolve 'mathjax-full/js/handlers/html.js' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax'

./node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax/index.js:8:0-71 - Error: Module not found: Error: Can't resolve 'mathjax-full/js/input/tex/AllPackages.js' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax'

./node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax/index.js:9:0-63 - Error: Module not found: Error: Can't resolve 'mathjax-full/js/input/tex/FindTeX.js' in '/home/ddkn/prj/f14bk/node_modules/@bokeh/bokehjs/build/js/lib/models/text/mathjax'
```

Running

```
npx npm install flatbush @bokeh/numbro timezone regl mathjax-full hammerjs proj4
```

then re-running `npx ng serve` works. Normally you shouldn't need to be closed and restart `ng serve` as it continually builds when run, and doesn't pick up the newly installed packages.

So node.js/npm are not aware of the runtime dependencies for @bokeh/bokehjs.

### Example

This can be referenced on the discourse instance at bokeh for Angular 14 [here](https://discourse.bokeh.org/t/angular-14-bokeh-bokehjs-3/9742) and [initial setup](https://discourse.bokeh.org/t/angular-10-bokeh-bokehjs-not-compiling-or-with-webpack/9469/6)

**Comment by mattpap** [comment]
Just to note, those are `devDependencies`, but regardless no dependencies of any kind are referenced by `package.json` in the generated package.

**Comment by bryevdv** [comment]
@mattpap what is the solution to the issue? "Compiling an Angular webapp with Bokeh" is a thing that it should be possible for users to do, simply.

**Comment by ddkn** [comment]
> Just to note, those are devDependencies, but regardless no dependencies of any kind are referenced by package.json in the generated package.

While that may be, it seems strange to me that when trying to use the package it wants these modules available this could be angular related. This isn't intuitive to me. For example, in python packages you have a set of runtime dependencies listed for a package when installing something from pypi.

Hm, I seem to be having some issues with importing into `node` as well.

```
$ node
Welcome to Node.js v16.18.1.
Type ".help" for more information.
> import * as bokeh from '@bokeh/bokehjs';
import * as bokeh from '@bokeh/bokehjs';
^^^^^^

Uncaught:
SyntaxError: Cannot use import statement inside the Node.js REPL, alternatively use dynamic import
> 
> 
> let Bokeh = await import('@bokeh/bokehjs');
(node:160767) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/ddkn/prj/novonix-frontend/node_modules/@bokeh/bokehjs/build/js/lib/bokeh.js:1
export * from "./main";
^^^^^^

Uncaught SyntaxError: Unexpected token 'export'
> 
>
> let Bokeh2 = require('@bokeh/bokehjs');
/home/ddkn/prj/novonix-frontend/node_modules/@bokeh/bokehjs/build/js/lib/bokeh.js:1
export * from "./main";
^^^^^^

Uncaught SyntaxError: Unexpected token 'export
```

So it seems strange that I can install from `npm` but not really able to import said package. Also this is the same directory with all the dependencies installed.

I have noticed on the [bokehjs documentation](https://docs.bokeh.org/en/latest/docs/dev_guide/bokehjs.html), that this package may not be setup to be used by others easily without building from scratch in `node`.

I will test this tonight just to see, but as of now the npm package seems to misleading on how it works to me at least. I do not claim to be a node guy (but learning), so I could be doing something quite wrong.

> @mattpap what is the solution to the issue? "Compiling an Angular webapp with Bokeh" is a thing that it should be possible for users to do, simply.

I think possibly making a wrapper for @bokeh/bokehjs may be a solution. I see that highcharts has their own [wrapper](https://www.highcharts.com/blog/tutorials/highcharts-with-angular-v14/) for their JS library. So possibly this is the path that needs to be done, something that handles all the imports correctly as a minimum.

PS. I appreciate you guys taking time to respond to this conversation, as I know this isn't normal for Bokeh development.

**Comment by ddkn** [comment]
> @mattpap what is the solution to the issue? "Compiling an Angular webapp with Bokeh" is a thing that it should be possible for users to do, simply.

Work is starting to comb through plotting libraries and we came across the plotlyjs angular equivalent.

https://www.npmjs.com/package/angular-plotly.js/v/0.1.13

Basically this is more or less what I was hoping to propose with bokehjs. But hopefully something that can be maintained with up to date releases. I am willing to try and help but may need some direction from time to time.

## PS. Dependencies of both angular-plotly.js and plotly.js

You can see that the DevDependencies are part of the packages there.

plotly.js
![image](https://user-images.githubusercontent.com/13819239/202908689-254e28aa-8cc3-4917-9f9c-2454c99cdc93.png)

angular-plotly.js
![image](https://user-images.githubusercontent.com/13819239/202908713-78453346-4040-45f2-a8ea-2f7734206a5d.png)

@bokeh/bokehjs
![image](https://user-images.githubusercontent.com/13819239/202908740-d9b03f6c-e30b-4ed8-9a50-59858e6327a4.png)

**Comment by ddkn** [comment]
Hm, in plotly.js they seem to have descriptions on how to include things into Angular manually. This may be something worth looking into first for bokeh (meaning me, and report back). Reason being for wanting to focus on bokeh is people seem to have better experiences with larger datasets, which can be our case.

https://github.com/plotly/plotly.js/blob/master/BUILDING.md#angular-cli

**Comment by matteosox** [comment]
Re-upping this issue. Installing from npm no longer pulls in the relevant dependencies. From 2.4.3, you can see that the main [package.json](https://github.com/bokeh/bokeh/blob/2.4.3/bokehjs/package.json) has these dependencies, but they're no longer contained in [3.0.3](https://github.com/bokeh/bokeh/blob/3.0.3/bokehjs/package.json). Looks like this is the [culprit commit](https://github.com/bokeh/bokeh/commit/3ea24a34f88e437461c4be302a40a7251c378107).

The result is the following traceback for my NextJS app:
```
error - ./node_modules/@bokeh/bokehjs/build/js/lib/core/ui_events.js:1:0
Module not found: Can't resolve 'hammerjs'

Import trace for requested module:
./node_modules/@bokeh/bokehjs/build/js/lib/models/canvas/canvas.js
./node_modules/@bokeh/bokehjs/build/js/lib/models/canvas/index.js
./node_modules/@bokeh/bokehjs/build/js/lib/models/index.js
./node_modules/@bokeh/bokehjs/build/js/lib/models/main.js
./node_modules/@bokeh/bokehjs/build/js/lib/main.js
./node_modules/@bokeh/bokehjs/build/js/lib/bokeh.js
./components/bokeh.tsx
./pages/[league]/[year].tsx
```

Sure enough, my package-lock.json no longer contains `hammerjs` because that dependency isn't correctly noted by the bokehjs package.

**Comment by matteosox** [comment]
> Hm, in plotly.js they seem to have descriptions on how to include things into Angular manually. This may be something worth looking into first for bokeh (meaning me, and report back). Reason being for wanting to focus on bokeh is people seem to have better experiences with larger datasets, which can be our case.
> 
> https://github.com/plotly/plotly.js/blob/master/BUILDING.md#angular-cli

I don't much about Angular, but you can see how to get this running in React (w/ NextJS) [here](https://github.com/matteosox/nba/blob/main/app/pages/%5Bleague%5D/%5Byear%5D.tsx). Specifically, this is a dynamic import, telling it to run this on the client-side only, since bokehjs needs access to browser-only objects like the window. Bokehjs has never run in Node as far as I know, which makes some sense since it can't be run server-side.

Anyways, I _think_ you'll be able to use bokeh 2.4.3, which has these dependencies correctly setup, which you can see on npm [here](https://www.npmjs.com/package/@bokeh/bokehjs/v/2.4.3?activeTab=dependencies).

**Comment by ddkn** [comment]
@matteosox that would make sense (and thanks for the link!). I was initially running on 2.4.3, and was eager for 3.0.x. I have been away doing lab research, but am back now and hoping to do some work on this over the holidays. I just have a few tasks to sort through at work first, but I think people at work would like to see bokeh be a first class citizen for plotting on our frontend work for data analysis -- the bokeh server impressed them, but that feature isn't ideal for our setup, hence my push to Angular, and ideally get more JS devs involved due to ease of accessibility for them.

However, when I was looking at your code

```
import { embed } from '@bokeh/bokehjs'
```

This could only be done on Angular (sort of), when I declare bokeh as a module, as seen on [my post on discourse](https://discourse.bokeh.org/t/angular-10-bokeh-bokehjs-not-compiling-or-with-webpack/9469/6), but you need to pass the build path as well. I know React is more close to javascript, so maybe that is why it worked easier (or more straight forward when dependencies are included).

**Comment by ddkn** [comment]
As @matteosox mentioned, I realize the devDependencies were moved out, but will they be put back for 3.1? Or should I assume that this will not go in? (Sorry for the delay, I ended up finally catching Covid, and was out for quite a while).

**Comment by amaurylivier** [comment]
I am trying to use bokeh 3.3.0 on a react based application (nextjs).

There is still no DevDependencies on npm.

When i try to manually install those dependencies, Bokeh throws me error.

Will they be put back in near futur?

BokehJS is more and more used in web development. 

Thank you

**Comment by ddkn** [comment]
I have been still watching this btw. I haven't had time to look at this yet as I am finishing up some thesis work. We are also possibly switching frameworks, choice is between Vue, React and Angular at work.

@AmauryVa I think the currenty functioning version of bokeh is 2.4.3 on npm that still has devDependencies, and @matteosox has provided his github project [here](https://github.com/matteosox/nba/blob/main/app/pages/%5Bleague%5D/%5Byear%5D.tsx) that integrates Bokeh with React if you needed something today.

From @matteosox 
> From 2.4.3, you can see that the main [package.json](https://github.com/bokeh/bokeh/blob/2.4.3/bokehjs/package.json) has these dependencies, but they're no longer contained in [3.0.3](https://github.com/bokeh/bokeh/blob/3.0.3/bokehjs/package.json). Looks like this is the [culprit commit](https://github.com/bokeh/bokeh/commit/3ea24a34f88e437461c4be302a40a7251c378107).

I will be able to look at this again once I am finished in the next few weeks;  this means I hopefully will be able to help out with this issue since it isn't a priority for anyone else.

**Comment by ddkn** [comment]
Hey @bryevdv and @mattpap,

So I am finally getting back to updating after a long time. I decided to upgrade to `bokehjs=3.3.2|3.3.3` with the new angular17. Add the `*.d.ts` was nice in that I no longer needed the modules file in my code and could import without any yelling, Angular seems to be pulling in from there. After adding the `bokeh{,-api,-widgets,-tables}.min.js` files to the `angular.json` file like previuosly and including them as `<script src=...></script>` in the `index.html` file. The code *builds* but **does not render** the plot as in my [old](https://discourse.bokeh.org/t/angular-14-bokeh-bokehjs-3/9742) attempt. It seems the <div> is null or empty? Or perhaps angular 17 is blocking some rendering. I am unsure at this time. Any ideas I could try and focus on tracking down?

![image](https://github.com/bokeh/bokeh/assets/13819239/ca4fe9a9-c2d2-4f0d-b9eb-5ec58b8a1df4)
![image](https://github.com/bokeh/bokeh/assets/13819239/002e3730-c375-46cc-ad50-30e9b037bac8)

I still needed to pull in manually as dependencies, as @bokeh/bokehjs does not pull these in.

```
npm install @bokeh/numbro proj4 flatbush mathjax-full hammerjs timezone regl
```

I may try to rebuild this from scratch to be purely compatible with Angular 17, but this code was minimal to begin with.

PS. Also not sure if this is relevant, but Angular 17 now has some reactive tooling also called `signal` so there was some complaining I noticed but may be unrelated? Unless the code imported could be problematic since angular `signal` is in the main namespace. The error was on line 33:

![image](https://github.com/bokeh/bokeh/assets/13819239/848aca5c-cd05-4031-a998-6cbc92b2ffae)

PS Happy New year everyone!

**Comment by grinspins** [comment]
I was also looking into upgrading from V2 to V3 and the lack of dependency declarations stopped me from doing so. Having to manage the dependencies on the application level is a serious stability issue, when requirements may change in any minor bokeh release.
I'm wondering if this is an oversight, or intentional to discourage developers from using the JS API independently of  the Python backend.
