### ISSUE TITLE
[BUG] bokeh v3 ColumnDataSource.selected.indices no longer works with ndarray

### ISSUE THREAD

**Issue by orionlee** [bokeh/bokeh#12624]
### Software versions

Python version      :  3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:18:12) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.6.0
Tornado version     :  6.1
Bokeh version       :  3.0.2
BokehJS static path :  C:\pkg\_winNonPortables\Anaconda3\envs\lkv2_1_dev_alt\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.22621-SP0

### Browser name and version

Chrome v107

### Jupyter notebook / Jupyter Lab version

jupyter notebook 6.4.10

### Expected behavior

In defining selection using `ColumnDataSource.selected.indices`, values of type `ndarray` should work.

### Observed behavior

In defining selection using `ColumnDataSource.selected.indices`, values of type `ndarray` does not work in bokeh v3.0.2. It used to work in bokeh v2.x .

When `selected.indices` is of `ndarray`, 
- no plot is produced, nor is there any Python error.
- there is a javascript error. e.g.

```javascript
Error: Selection(p7815).indices given invalid value: {"0":1,"1":2,"2":3,"dtype":"int32","shape":[3],"dimension":1}
    at q.validate (VM60 bokeh-3.0.2.min.js:182:2127)
    at q._update (VM60 bokeh-3.0.2.min.js:182:1842)
    at q.initialize (VM60 bokeh-3.0.2.min.js:182:1480)
    at _.initialize_props (VM60 bokeh-3.0.2.min.js:179:4432)
    at y._decode_object_ref (VM60 bokeh-3.0.2.min.js:212:4715)
    at y._decode (VM60 bokeh-3.0.2.min.js:212:1709)
    at y._decode_plain_object (VM60 bokeh-3.0.2.min.js:212:2270)
    at y._decode (VM60 bokeh-3.0.2.min.js:212:1035)
    at y._decode_object_ref (VM60 bokeh-3.0.2.min.js:212:4684)
    at y._decode (VM60 bokeh-3.0.2.min.js:212:1709)
```

### Example code

```Python
import bokeh
from bokeh.io import show, output_notebook
from bokeh import plotting as bplt
from bokeh import layouts as blayouts
from bokeh import models as bmodels
from bokeh import io as bio
import numpy as np

def test_tap_select(notebook_url="localhost:8888"):
    def create_interact_ui(doc):
        fig = bplt.figure(width=300, height=300, tools="tap")

        source = bmodels.ColumnDataSource(dict(x=[0, .2, .4, .6, .8, 1], y=[0, .1, .2, .6, .9, 1]))
        source.selected.indices = np.array([1,2,3])  # ndarray does not work with bokeh 3.0.2

        r = fig.circle('x', 'y', source=source, size=10, color='#000000',
                # set visual properties for selected glyphs
                            selection_color="#2bff00",

                            # set visual properties for non-selected glyphs
                            nonselection_fill_alpha=1.0,
                            nonselection_fill_color="#000000")

        def handler(attr, old, new):
            print('attr: {} old: {} new: {}'.format(attr, old, new))

        # r.data_source.on_change('selected', handler)
        r.data_source.selected.on_change('indices', handler)

        doc.add_root(fig)

    output_notebook(verbose=False, hide_banner=True)
    show(create_interact_ui, notebook_url=notebook_url)

print("bokeh ", bokeh.__version__)
test_tap_select(notebook_url="localhost:8888");
```

**Comment by orionlee** [comment]
The javascript error seems to indicate there is some marshalling and/or unmarshalling problems for `ndarray` values.

**Workaround**: convert `ndarray` to plain list, before assigning it to `selected.indices`.

**Comment by mattpap** [comment]
Based on a cursory check, it doesn't seem anything changed on the relevant code paths. bokeh's `indices` has a bit wider sequence type than bokehjs, resulting in this error. It's a bit of a hustle to handle ndarray context like this (we have to make sure the dtype and shape are correct), but it's possible to handle this. Alternatively we could convert the value to a list in bokeh, as we do in other places.

**Comment by mattpap** [comment]
Marking as a bug, because of inconsistent property types.
