### ISSUE TITLE
CategoricalHeatMap palette rounds down

### ISSUE THREAD

**Issue by inodb** [bokeh/bokeh#1262]
Hi,

Thank you very much for the new CategoricalHeatMap widget, it looks awesome! I am trying to use the widget to spot presence or absence of something. A problem I'm having in this case is that values that are close to zero are mapped to the first color in the palette, which is white in my plot, see: http://ino.pm/share/mdopson/cluster_pog.html. It would be nice if the values could be ceiled instead of rounded here:

https://github.com/ContinuumIO/bokeh/blob/acfebdaa2607f42f9d4afb5527e447e43a9ac0d5/bokeh/charts/catheatmap.py#L168

Or maybe it would be better if a color map was used instead http://matplotlib.org/api/cm_api.html.

Cheers,
Ino

**Comment by bryevdv** [comment]
If necessary, this issue can be re-opened in the `bkcharts` repo.
