### ISSUE TITLE
export_png doesn't find chrome webdriver because it was installed as chromedriver-binary 

### ISSUE THREAD

**Issue by jeremy9959** [bokeh/bokeh#12625]
### Software versions

Python version      :  3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]
IPython version     :  8.6.0
Tornado version     :  6.2
Bokeh version       :  3.0.2
BokehJS static path :  /home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v14.15.4
npm version         :  6.14.10
Operating system    :  Linux-5.15.0-52-generic-x86_64-with-glibc2.31

### Browser name and version

Google Chrome 107.0.5304.110

### Expected behavior

```python
import numpy as np
from bokeh.plotting import figure
from bokeh.io import export_png

f=figure()
x=np.linspace(-10,10,100)
y=x**2
f.line(x=x,y=y)
export_png(f,filename='out.png')
```
should generate a file 'out.png'.

### Observed behavior

The program crashed with the RunTime error:

```
Traceback (most recent call last):
  File "/home/jet08013/bokehexport.py", line 11, in <module>
    export_png(f,filename='out.png')
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/export.py", line 116, in export_png
    image = get_screenshot_as_png(obj, width=width, height=height, driver=webdriver, timeout=timeout, state=state)
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/export.py", line 254, in get_screenshot_as_png
    web_driver = driver if driver is not None else webdriver_control.get()
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/webdriver.py", line 135, in get
    self.current = self.create()
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/webdriver.py", line 139, in create
    driver = self._create(kind)
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/webdriver.py", line 157, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.
```

**My own investigations show that chromedriver was installed by conda under the name chromedriver-binary and
adding a symlink in the bin directory from chromedriver-binary to chromedriver fixed the problem.**

### Example code

```Python
import numpy as np
from bokeh.plotting import figure
from bokeh.io import export_png

f=figure()
x=np.linspace(-10,10,100)
y=x**2
f.line(x=x,y=y)
export_png(f,filename='out.png')
```

### Stack traceback or browser console output

Traceback (most recent call last):
  File "/home/jet08013/bokehexport.py", line 11, in <module>
    export_png(f,filename='out.png')
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/export.py", line 116, in export_png
    image = get_screenshot_as_png(obj, width=width, height=height, driver=webdriver, timeout=timeout, state=state)
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/export.py", line 254, in get_screenshot_as_png
    web_driver = driver if driver is not None else webdriver_control.get()
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/webdriver.py", line 135, in get
    self.current = self.create()
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/webdriver.py", line 139, in create
    driver = self._create(kind)
  File "/home/jet08013/anaconda3/envs/python310/lib/python3.10/site-packages/bokeh/io/webdriver.py", line 157, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.

**Comment by ianthomas23** [comment]
I have experienced the same issue in some of the various Docker experiments.

A quick search comes up with https://stackoverflow.com/questions/70563825/what-is-the-difference-in-chromedriver-binary-and-chomedriver-exe-in-selenium-py which indicates that we could support `chromedriver-binary` by wrapping an `import chromedriver_binary` in a `try`-`except` block to appropriately modify the `PATH`.

**Comment by bryevdv** [comment]
An issue with that is that we don't actually import `chromedriver` directly ourselves anywhere. The current code relies on selenium:

https://github.com/bokeh/bokeh/blob/420ae5ab3658d2d2a78acc7537eed418aa237a48/src/bokeh/io/webdriver.py#L76-L91

**Comment by bryevdv** [comment]
I"m marking this as `discussion` because I think something probably can be done, and in that case, should be, but it's not clear just what that action is.

**Comment by mattpap** [comment]
> An issue with that is that we don't actually import chromedriver directly ourselves anywhere. The current code relies on selenium

This was changed in 3.0, specifically so that we don't get into the business of resolving executables. If things, don't work then either selenium (or a related library) or the package (that installed an executable in an unusual location or with unusual name) is at fault.

**Comment by bryevdv** [comment]
> This was changed in 3.0, specifically so that we don't get into the business of resolving executables. If things, don't work then either selenium (or a related library) or the package (that installed an executable in an unusual location or with unusual name) is at fault.

While technically true, users really, truly won't care to split hairs over this when their boss asks why they can't get their work accomplished. They will just say "image export in Bokeh is broken". And they won't be wrong. So while I also appreciate the motivations to simplify and push as much as possible on to the driver, if there are situations that don't work where adding a "manual" fallback could keeps things working, I think we have to consider it.

**Comment by bryevdv** [comment]
We could also take another look at Kaleido: https://github.com/plotly/Kaleido

Edit: well, looking more closely at the tracker, it seems they have quite a number issues as well, and it's not clear what the future support/maintenance story will be now that the original author is no longer involved.

**Comment by bryevdv** [comment]
`selenium.webdriver.chrome.webdriver.WebDriver` accepts an `executable_path`:
```
Init signature:
WebDriver(
    executable_path='chromedriver',
    port=0,
    options: selenium.webdriver.chrome.options.Options = None,
    service_args=None,
    desired_capabilities=None,
    service_log_path=None,
    chrome_options=None,
    service: selenium.webdriver.chrome.service.Service = None,
    keep_alive=None,
)
```
Why don't we simply offer a mechanism to configure this value as final backstop users can turn to if absolutely necessary. We could make it a setting so that env var configuration is possible. @bokeh/dev

**Comment by C4ndleCoder** [comment]
SAme issue, ubuntu 22.04.... Need help

**Comment by jeremy9959** [comment]
See my solution and see if that works for you:
...adding a symlink in the bin directory from chromedriver-binary to chromedriver fixed the problem...

**Comment by C4ndleCoder** [comment]
I did this but it didn't work.

ln -s /root/anaconda3/envs/chatbot/lib/python3.10/site-packages/chromedriver_binary/ /bin/chromedriver

**Comment by jeremy9959** [comment]
I think you might need to tailor this to the way your path is set up; or perhaps your problem is just different.

--
Jeremy Teitelbaum, Ph.D.
Professor of Mathematics
Director, MS in Data Science Program
University of Connecticut
https://jeremy9959.net
https://masters.datascience.uconn.edu/
________________________________

**Comment by ianthomas23** [comment]
> Why don't we simply offer a mechanism to configure this value as final backstop users can turn to if absolutely necessary. We could make it a setting so that env var configuration is possible. @bokeh/dev

I like this idea, there are occasions when this solution would make my life easier.
