### ISSUE TITLE
Make Slider and Image available in BokehJS (JS only)

### ISSUE THREAD

**Issue by josephernest** [bokeh/bokeh#12638]
Hi,
As discussed with Bryan in https://discourse.bokeh.org/t/bokehjs-how-to-create-a-slider/9759/3, it would be interesting to have `Slider` and `Image` available directly in BokehJS.

The documentations states that nearly all Python models are available similarly in JS with `new Bokeh.<model>`. It seems that `new Bokeh.Slider(...)` and `new Bokeh.Image(...)` (I'm looking for [color mapped images](https://docs.bokeh.org/en/latest/docs/user_guide/topics/images.html#color-mapped-images)) are currently not available in JS-only BokehJS.
Do you think it would be straightforward to add it? I can do the beta-testing and reporting.

Thanks

PS: I used this issue template because the other ones were quite complex with many textboxes - this one is more classical.

**Comment by bryevdv** [comment]
> PS: I used this issue template because the other ones were quite complex with many textboxes - this one is more classical.

@josephernest the issue templates exist for a reason, to ensure that we can get all the information we need. Please use only the issue templates in the future.

@mattpap I am sure this is actually already possible one way or another, but there is no documentation or examples anywhere that I could find.

**Comment by josephernest** [comment]
Thanks @bryevdv, I'll do this in the future.

**Comment by mattpap** [comment]
Widgets are available under `Bokeh.Widgets` namespace, e.g.:
```ts
new Bokeh.Widgets.Slider({start: 0, end: 100})
```
If a model is not available via a namespace, then one can use this:
```ts
Bokeh.Models.get("Image")
```
to resolve a model by name. Finally, there is a internal way of resolving any JS module:
```ts
Bokeh.require("models/glyphs/image").Image
```
though I recommend not going that far, because module structure isn't stable.

**Comment by mattpap** [comment]
Glyphs should be available via the `Bokeh` namespace, assuming `bokeh-api` bundle is present, so this looks like a bug.

**Comment by josephernest** [comment]
Thanks @mattpap.
Would you have a minimal example of slider?

I think one line is probably missing to display the slider?

https://jsfiddle.net/2pag8qds/

```
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.1.min.js"></script>
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.4.1.min.js"></script>
<div id="chart1"></div>
<div id="chart2"></div>
<script>
var plt = Bokeh.Plotting, M = 100, xx = [], yy = [], colors = [], radii = [];
for (var y = 0; y <= M; y += 4) {
    for (var x = 0; x <= M; x += 4) {
        xx.push(x);
        yy.push(y);
        colors.push(plt.color(50+2*x, 30+2*y, 150));
        radii.push(Math.random() * 0.4 + 1.7)
    }
}
var source = new Bokeh.ColumnDataSource({data: {x: xx, y: yy, radius: radii, colors: colors}});
var p = plt.figure({title: "Colorful Scatter", tools: "pan,crosshair,wheel_zoom,box_zoom,reset,save"});
var circles = p.circle({ field: "x" }, { field: "y" }, {source: source, radius: radii, fill_color: colors, fill_alpha: 0.6, line_color: null});
plt.show(p, "#chart1");

var s = new Bokeh.Widgets.Slider({start: 0, end: 100});
plt.show(s, "#chart2");
</script>
```

**Comment by mattpap** [comment]
You need to include `bokeh-widgets` bundle to make it work. Currently we don't have bokehjs examples showing widgets.

**Comment by bryevdv** [comment]
> You need to include bokeh-widgets bundle to make it work. 

@josephernest in concrete terms this means:
```
<script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.1.min.js"></script>

```
