### ISSUE TITLE
[BUG] Styles are not applied to model in Firefox

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#12633]
### Software versions

Python version      :  3.9.14 | packaged by conda-forge | (main, Nov 21 2022, 13:18:18) 
IPython version     :  8.6.0
Tornado version     :  6.2
Bokeh version       :  3.0.2
BokehJS static path :  /home/shh/miniconda3/envs/bokeh_clean/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-6.0.6-76060006-generic-x86_64-with-glibc2.35

### Expected behavior

I would expect the styles are applied to the model, e.g., in the example below the background should have been changed to red. 

The only way I can get it to work is by using `stylesheets`

### Observed behavior

Nothing happens with the background. 

### Example code

```Python
from bokeh.io import output_notebook, show
from bokeh.models import Div, Styles, Row

output_notebook()

d1 = Div(text="red", width=200, height=100, background="red") 
d2 = Div(text="red", width=200, height=100, styles=Styles(background="red"))  # No changes if using background_color="red".
d3 = Div(text="red", width=200, height=100, stylesheets=[":host { background: red; }"])
show(Row(d1, d2, d3))
```

### Bokeh 3.0.2
![image](https://user-images.githubusercontent.com/19758978/203074713-067cea6a-2e51-4483-b61e-b53f63c24182.png)

### Bokeh 2.4.3
![image](https://user-images.githubusercontent.com/19758978/203074999-202eec88-15b4-46db-90f7-9b710a156f5a.png)

**Comment by mattpap** [comment]
This is specific to firefox.
