### ISSUE TITLE
[FEATURE]  Add a find_stack_level to deprecation.py

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#12646]
### Problem description

The stacklevel of the warn in bokeh/util/deprecation.py is set to 2, making it hard to find the actual place when running the panel test suite. e.g.

``` python
../bokeh/src/bokeh/util/deprecation.py:78
  BokehDeprecationWarning: Positive was deprecated in Bokeh 3.0.0 and will be removed, use Positive(Int) instead.
```

### Feature description

My suggestion will be to copy `pandas.util._exceptions.find_stack_level`; which will give the following output.

``` python
panel/models/vtk.py:28
  BokehDeprecationWarning: Positive was deprecated in Bokeh 3.0.0 and will be removed, use Positive(Int) instead.
```

The function `find_stack_level` I suggest will look something like this:
``` python
def find_stack_level() -> int:
    """
    Find the first place in the stack that is not inside Bokeh.

    Inspired by: pandas.util._exceptions.find_stack_level
    """

    import bokeh

    pkg_dir = os.path.dirname(bokeh.__file__)

    # https://stackoverflow.com/questions/17407119/python-inspect-stack-is-slow
    frame = inspect.currentframe()
    n = 0
    while frame:
        fname = inspect.getfile(frame)
        if fname.startswith(pkg_dir):
            frame = frame.f_back
            n += 1
        else:
            break
    return n
``` 

### Potential alternatives

Leave it as it is.

**Comment by bryevdv** [comment]
@Hoxbro this seems reasonable, can you submit a PR? Ideally there is a minimal test, though this seems like one of those things that may be a bit tricky to cover effectively. Perhaps there are tests in pandas that can be emulated.
