### ISSUE TITLE
[BUG] First steps 2 doc figures have low contrast

### ISSUE THREAD

**Issue by dstansby** [bokeh/bokeh#12647]
### Software versions

n/a

### Expected behavior

The figure at https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_2.html#rendering-circles to have high contrast between the figure background and markers.

### Observed behavior

Instead the yellow markers on white background are very low contrast and hard to see:
<img width="626" alt="Screenshot 2022-11-23 at 20 18 39" src="https://user-images.githubusercontent.com/6197628/203638901-3b150c03-46c3-4129-8f43-ef7c3cb67fca.png">

### Example code

```Python
n/a
```

**Comment by bryevdv** [comment]
Hi @dstansby Thank you for this issue, I agree the colors are not very friendly. I had noticed this also in the past, but then forgot to follow up with an issue about it. Would you be interested to submit a PR to improve the color scheme in this example? (Or ideally, any of the first steps examples that need improvement, if you have the interest/bandwidth). The first steps examples are here:

https://github.com/bokeh/bokeh/tree/branch-3.1/docs/bokeh/source/docs/first_steps/examples

A number of new accessible palettes from Paul Tol were added for Bokeh 3.0:

https://docs.bokeh.org/en/latest/docs/reference/palettes.html#accessible-palettes 

So colors from those could potentially be used. I have also been preferring `background_fill_color="#efefef"` lately, but maybe that would confuse/complicate a first steps example. cc @tcmetzger
