### ISSUE TITLE
[BUG] bokeh.plotting.graph.from_networkx fails on graphs having nodes with string index values

### ISSUE THREAD

**Issue by erivlis** [bokeh/bokeh#12651]
### Software versions

Python version      :  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.2
BokehJS static path :  c:\dev\bokeh_test\venv\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.22621-SP0

### Expected behavior

generate a graph_renderer without crashing :-)

### Observed behavior

The error comes from `StaticLayoutProvider` (in `bokeh\models\graph.py`)

Comparing the 2.4.3 to the 3.0.2 implementations (see below), one can clearly see that the support of string valued indexes has been removed. Is this change intentional or is it a regression the code base?

BTW Monkey patching this by creating a version that replaces ` graph_layout = Dict(Int, Seq(Any)...` with ` graph_layout = Dict(Either(String, Int), Seq(Any)` makes the `from_networkx` function work.  I have not used it in any other context other then investigating this issue so there may be undesired effects of this change.

2.4.3:
```
class StaticLayoutProvider(LayoutProvider):
    '''
    '''

    graph_layout = Dict(Either(String, Int), Seq(Any), default={}, help="""
    The coordinates of the graph nodes in cartesian space. The dictionary
    keys correspond to a node index and the values are a two element sequence
    containing the x and y coordinates of the node.
    .. code-block:: python
        {
            0 : [0.5, 0.5],
            1 : [1.0, 0.86],
            2 : [0.86, 1],
        }
    """)
```

3.0.2:
```
class StaticLayoutProvider(LayoutProvider):
    '''

    '''

    # explicit __init__ to support Init signatures
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

    # TODO: Seq(Any).length == 2
    graph_layout = Dict(Int, Seq(Any), default={}, help="""
    The coordinates of the graph nodes in cartesian space. The dictionary
    keys correspond to a node index and the values are a two element sequence
    containing the x and y coordinates of the node.

    .. code-block:: python

        {
            0 : [0.5, 0.5],
            1 : [1.0, 0.86],
            2 : [0.86, 1],
        }
    """)
```

### Example code

```Python
# pip install bokeh==3.0.2
# pip install networkx==2.8.8

import networkx as nx
from bokeh.plotting import from_networkx

graph = nx.Graph()

graph.add_edge("a", "b")

layout_function = nx.spring_layout

graph_renderer = from_networkx(graph, layout_function, center=(0,0), scale=1)
```

### Stack traceback or browser console output

```python
Traceback (most recent call last):
  File "C:\dev\bokeh_test\bokeh_test.py", line 13, in <module>
    graph_renderer = from_networkx(graph, layout_function, center=(0,0), scale=1)
  File "C:\dev\bokeh_test\venv\lib\site-packages\bokeh\plotting\graph.py", line 125, in from_networkx
    graph_renderer.layout_provider = StaticLayoutProvider(graph_layout=graph_layout)
  File "C:\dev\bokeh_test\venv\lib\site-packages\bokeh\models\graphs.py", line 83, in __init__
    super().__init__(*args, **kwargs)
  File "C:\dev\bokeh_test\venv\lib\site-packages\bokeh\models\graphs.py", line 66, in __init__
    super().__init__(*args, **kwargs)
  File "C:\dev\bokeh_test\venv\lib\site-packages\bokeh\model\model.py", line 115, in __init__
    super().__init__(**kwargs)
  File "C:\dev\bokeh_test\venv\lib\site-packages\bokeh\core\has_props.py", line 298, in __init__
    setattr(self, name, value)
  File "C:\dev\bokeh_test\venv\lib\site-packages\bokeh\core\has_props.py", line 327, in __setattr__
    return super().__setattr__(name, value)
  File "C:\dev\bokeh_test\venv\lib\site-packages\bokeh\core\property\descriptors.py", line 289, in __set__
    value = self.property.prepare_value(obj, self.name, value)
  File "C:\dev\bokeh_test\venv\lib\site-packages\bokeh\core\property\bases.py", line 365, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate StaticLayoutProvider(id='p1032', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {'a': array([-1.        ,  0.48174052]), 'b': array([ 1.        , -0.48174052])}
```

**Comment by bryevdv** [comment]
@mattpap you changed this in https://github.com/bokeh/bokeh/pull/11960 can you comment?

**Comment by mattpap** [comment]
The docstring for `graph_layout` says "The dictionary keys correspond to a node index (...)", so I'm assuming numerical index. Previously the type was `Either(Int, String)`, because bokehjs used plain objects where there is no distinction between numerical and string indices. This seems to me like an coincidental feature, due to us exposing an implementation detail in the API. Given `Graph.add_edge()`'s arguments can be of any (hashable) type, then either the type should be `Any` and the underlying logic probably updated, or there should be a mapping kept between node indices and their labels. Given that the serializer now can handle dictionaries with any keys and bokehjs using JS `Map` internally, the former option is now possible.

**Comment by erivlis** [comment]
@bryevdv @mattpap 

From [https://networkx.org/documentation/stable/_modules/networkx/classes/graph.html#Graph](url):
> Nodes can be arbitrary (hashable) Python objects with optional
> key/value attributes, except that `None` is not allowed as a node.

It seems to me that a two step solution can be made:

1. Step 1: Add the support for `str` index value. This will enable support for all types in several ways:
    1. If the node's index is a `int` - this efficient type will be carried on
    2. If it's an `str` - it's passed on without lose of data or misrepresentation.
    3. Other `hashable` types - left for the developer to "translate" to either an int or a string. having a `str` as a supported option enables to generate a unique, human understandable index value without lose of information. We leave it up to the developer to choose. As a user of the library I for one think it's a good enough compromise.
 2. Step 2: add support for any `hashable` object with some default implementation (which requires better understanding of all considerations related to the bokeh framework). If and when it's implemented it will support backward compatibility existing code.

Of course if step two is easy then there's no need for step one.

Disclaimer - I'm not at all familiar with all the considerations related to the JS side of bokeh.

**Comment by bryevdv** [comment]
Well, we more or less already manufacture the integer index already:

https://github.com/bokeh/bokeh/blob/829a9d09c327164153a24e17c3d5a1d56c26f755/src/bokeh/plotting/graph.py#L86

so the quick and dumb idea might be to just use the hash of the node everywhere (in the spot above, and before passing to the layout provider) instead, to get everything at once. 

I'd say that would worth a quick investigation. 

The potential edge case that comes to mind is that technically speaking, in some cases hashes that are based on object addresses may not be stable due to address randomization (see [this long thread](https://discuss.python.org/t/hash-none-mk-2/21465/7) on DPO). But I am not sure how much of an issue that would be in actual practive (and we can simply document the need to provide a custom `__hash__` if it does come up)

**Comment by bryevdv** [comment]
@erivlis Can you please proved a complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) / test case(s) for generic hashable that doesn't function currently, but that is desired to?

**Comment by erivlis** [comment]
@bryevdv I would say mainly tuples and or dataclasses. But perhaps also other builtins such as datetime etc.

Would this example help?
```python
# pip install bokeh==3.0.2
# pip install networkx==2.8.8
from collections import namedtuple
from dataclasses import dataclass
from datetime import datetime

import networkx as nx
from bokeh.plotting import from_networkx

STAGE = "\N{Black Right-Pointing Triangle}"
SUCCESS = "\N{party popper}"
FAIL = "\N{beetle}"


def create_spring_layout_bokeh_renderer(graph: nx.Graph):
    layout_function = nx.spring_layout
    return from_networkx(graph, layout_function, center=(0, 0), scale=1)


def test_graph(node1, node2):
    try:
        nodes = {'node1': node1, 'node2': node2}
        print(f"{STAGE} Testing {nodes}:")

        print(f"  {STAGE} Creating Networkx Graph:")
        graph = nx.Graph()
        graph.add_edge(node1, node2)
        print((f"    {SUCCESS} Graph created successfully - {graph}:\n"
               f"         Nodes: `{graph.nodes}`\n"
               f"         Edges: `{graph.edges}`"))

        print(f"  {STAGE} Creating Bokeh GraphRenderer:")
        graph_renderer = create_spring_layout_bokeh_renderer(graph)
        print(f"    {SUCCESS} Bokeh Graph Renderer created successfully: {graph_renderer}")
    except (ValueError, TypeError) as e:
        print(f"    {FAIL} Exception Occurred: {e}")


@dataclass(unsafe_hash=True, eq=True)
class HashableNode:
    a: str
    b: int
    c: bool


User = namedtuple("User", ["firstname", "lastname"])

node_examples = [
    (1, 2),
    (True, False),
    (True, True),
    ("a", "b"),
    (("a",), ("b",)),
    (User(firstname="Alice", lastname="Smith"), User(firstname="Bob", lastname="Jones")),
    (datetime(2022, 1, 1), datetime(2023, 1, 1)),
    (User(firstname="Alice", lastname="Smith"), datetime(2022, 1, 1)),
    (HashableNode('a', 1, True), HashableNode('b', 2, False)),
    (HashableNode('a', 1, True), HashableNode('a', 1, True)),
    ([1, 2], [3, 4]),
    ({1, 2}, {3, 4}),
    ({"a": 1, "b": 2}, {"a": 3, "b": 4})
]

for nodes in node_examples:
    test_graph(*nodes)
    print("")
```

output:
```
▶ Testing {'node1': 1, 'node2': 2}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 2 nodes and 1 edges:
         Nodes: `[1, 2]`
         Edges: `[(1, 2)]`
  ▶ Creating Bokeh GraphRenderer:
    🎉 Bokeh Graph Renderer created successfully: GraphRenderer(id='p1001', ...)

▶ Testing {'node1': True, 'node2': False}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 2 nodes and 1 edges:
         Nodes: `[True, False]`
         Edges: `[(True, False)]`
  ▶ Creating Bokeh GraphRenderer:
    🎉 Bokeh Graph Renderer created successfully: GraphRenderer(id='p1033', ...)

▶ Testing {'node1': True, 'node2': True}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 1 nodes and 1 edges:
         Nodes: `[True]`
         Edges: `[(True, True)]`
  ▶ Creating Bokeh GraphRenderer:
    🎉 Bokeh Graph Renderer created successfully: GraphRenderer(id='p1065', ...)

▶ Testing {'node1': 'a', 'node2': 'b'}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 2 nodes and 1 edges:
         Nodes: `['a', 'b']`
         Edges: `[('a', 'b')]`
  ▶ Creating Bokeh GraphRenderer:
    🪲 Exception Occurred: failed to validate StaticLayoutProvider(id='p1128', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {'a': array([ 1.        , -0.61833485]), 'b': array([-1.        ,  0.61833485])}

▶ Testing {'node1': ('a',), 'node2': ('b',)}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 2 nodes and 1 edges:
         Nodes: `[('a',), ('b',)]`
         Edges: `[(('a',), ('b',))]`
  ▶ Creating Bokeh GraphRenderer:
    🪲 Exception Occurred: failed to validate StaticLayoutProvider(id='p1160', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {('a',): array([-1.        , -0.41092479]), ('b',): array([1.        , 0.41092479])}

▶ Testing {'node1': User(firstname='Alice', lastname='Smith'), 'node2': User(firstname='Bob', lastname='Jones')}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 2 nodes and 1 edges:
         Nodes: `[User(firstname='Alice', lastname='Smith'), User(firstname='Bob', lastname='Jones')]`
         Edges: `[(User(firstname='Alice', lastname='Smith'), User(firstname='Bob', lastname='Jones'))]`
  ▶ Creating Bokeh GraphRenderer:
    🪲 Exception Occurred: failed to validate StaticLayoutProvider(id='p1192', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {User(firstname='Alice', lastname='Smith'): array([-0.10485821, -1.        ]), User(firstname='Bob', lastname='Jones'): array([0.10485821, 1.        ])}

▶ Testing {'node1': datetime.datetime(2022, 1, 1, 0, 0), 'node2': datetime.datetime(2023, 1, 1, 0, 0)}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 2 nodes and 1 edges:
         Nodes: `[datetime.datetime(2022, 1, 1, 0, 0), datetime.datetime(2023, 1, 1, 0, 0)]`
         Edges: `[(datetime.datetime(2022, 1, 1, 0, 0), datetime.datetime(2023, 1, 1, 0, 0))]`
  ▶ Creating Bokeh GraphRenderer:
    🪲 Exception Occurred: failed to validate StaticLayoutProvider(id='p1224', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {datetime.datetime(2022, 1, 1, 0, 0): array([-0.18702782, -1.        ]), datetime.datetime(2023, 1, 1, 0, 0): array([0.18702782, 1.        ])}

▶ Testing {'node1': User(firstname='Alice', lastname='Smith'), 'node2': datetime.datetime(2022, 1, 1, 0, 0)}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 2 nodes and 1 edges:
         Nodes: `[User(firstname='Alice', lastname='Smith'), datetime.datetime(2022, 1, 1, 0, 0)]`
         Edges: `[(User(firstname='Alice', lastname='Smith'), datetime.datetime(2022, 1, 1, 0, 0))]`
  ▶ Creating Bokeh GraphRenderer:
    🪲 Exception Occurred: failed to validate StaticLayoutProvider(id='p1256', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {User(firstname='Alice', lastname='Smith'): array([-0.22341821, -1.        ]), datetime.datetime(2022, 1, 1, 0, 0): array([0.22341821, 1.        ])}

▶ Testing {'node1': HashableNode(a='a', b=1, c=True), 'node2': HashableNode(a='b', b=2, c=False)}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 2 nodes and 1 edges:
         Nodes: `[HashableNode(a='a', b=1, c=True), HashableNode(a='b', b=2, c=False)]`
         Edges: `[(HashableNode(a='a', b=1, c=True), HashableNode(a='b', b=2, c=False))]`
  ▶ Creating Bokeh GraphRenderer:
    🪲 Exception Occurred: failed to validate StaticLayoutProvider(id='p1288', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {HashableNode(a='a', b=1, c=True): array([-1.        ,  0.82513471]), HashableNode(a='b', b=2, c=False): array([ 1.        , -0.82513471])}

▶ Testing {'node1': HashableNode(a='a', b=1, c=True), 'node2': HashableNode(a='a', b=1, c=True)}:
  ▶ Creating Networkx Graph:
    🎉 Graph created successfully - Graph with 1 nodes and 1 edges:
         Nodes: `[HashableNode(a='a', b=1, c=True)]`
         Edges: `[(HashableNode(a='a', b=1, c=True), HashableNode(a='a', b=1, c=True))]`
  ▶ Creating Bokeh GraphRenderer:
    🪲 Exception Occurred: failed to validate StaticLayoutProvider(id='p1320', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {HashableNode(a='a', b=1, c=True): array([0, 0])}

▶ Testing {'node1': [1, 2], 'node2': [3, 4]}:
  ▶ Creating Networkx Graph:
    🪲 Exception Occurred: unhashable type: 'list'

▶ Testing {'node1': {1, 2}, 'node2': {3, 4}}:
  ▶ Creating Networkx Graph:
    🪲 Exception Occurred: unhashable type: 'set'

▶ Testing {'node1': {'a': 1, 'b': 2}, 'node2': {'a': 3, 'b': 4}}:
  ▶ Creating Networkx Graph:
    🪲 Exception Occurred: unhashable type: 'dict'
```

> Notice the interesting cases where the node1 and node2 are the same an thus a graph with a single node and an edge from that node to itself is created.

**Comment by erivlis** [comment]
@bryevdv as to your suggestion to use hashes as index values. I guess it can be used like that.
Two things come to mind:
1) The hashes are "unsafe" (as you mentioned)
2) In the resulting bokeh representation of the graph, one loses the original "meaning" or "value" of the node.

I would say the first issue is an edge case that can be avoided if it's documented clearly.
IMHO the 2nd issue is more important as it will cause a "lossy" transform of the original graph. If there's a way to retain the original index values or using a transform which is not "lossy", I think it's preferable.

**Comment by bryevdv** [comment]
> In the resulting bokeh representation of the graph, one loses the original "meaning" or "value" of the node.

I don't see how so? The hash indexes would be an internal representation of the graph, so that BokehJS knows what to draw where. Integer, string, etc node and edge attributes would be preserved. But to be clear, there will always be some limitations based on what can be serialized across the Python<-->JS boundary. If the graph uses arbitrary hashable objects for nodes, that's just never going to be fully faithfully reproducible on the JS side (but it could at least be *drawable*).

**Comment by erivlis** [comment]
So, the way _Networkx_ represents a graph is of "Nodes" which can be any Hashable python object. One can additionally attach to each node "attributes" which essentially are a dict data structure. In that sense the nodes "id" **is** the python object. So all in all a node is comprised from data can "sit" in two places: the node object which serves as ID also and this optional supplemental attributes dict.

Most of the time people we'll use simple objects (e.g. _int_, _str_, etc.) .
But one can use (as demonstrated in the test code above) _tuple_, _dataclass_ and any hashable object. Even complete _Networkx_ Graph objects (as they are hashble objects too :-)) - which gives the ability to create graphs of graphs.

Of course if the aim is to mainly/only "draw" then yes a new "index" by hashing the original node value will suffice. But if the user would think/expect that the _Bokeh_ node IDs are are equivalent to _Networkx_ IDs, as he wants to use them somehow, then he will have a nasty surprise. Hash functions by definition obfuscate and are one way, one can't go back to the original meaning.

Perhaps a solution will be to use a default hash function (which should be fast and simple), and give the user the ability to override it by supplying he's own "hash" function that can supply either an _int_ or _str_ (_str_ for the case the user wants something more human readable) . Of course if this new function has collisions then it's on him (though even that can be warned during processing).
