### ISSUE TITLE
User guide section for CSS stying

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12675]
As far as I know there is not any actual User Guide documentation regarding `styles`, `stylesheets`, etc. There is currently a *Styling plot elements*  section in the *Appearance* chapter that covers using Bokeh properties for plot things. I think I would suggest a  corresponding *Styling DOM elements* section that covers applying CSS styles, using `css_classes`, etc. 

cc @tcmetzger for thoughts

**Comment by tcmetzger** [comment]
Yes, I agree that this should have it's own section under Appearance, like @bryevdv suggests. Is the API for this in its final state so that we can start drafting a first iteration of this section?
