### ISSUE TITLE
[BUG] tooltips disappear when range of image is reversed

### ISSUE THREAD

**Issue by ghost** [bokeh/bokeh#12678]
### Software versions

Python version      :  3.8.13 (default, Nov  8 2022, 17:15:13) 
IPython version     :  8.7.0
Tornado version     :  6.2
Bokeh version       :  3.0.3
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.2.5

### Browser name and version

Firefox 102.5.0esr

### Jupyter notebook / Jupyter Lab version

jupyter-notebook 6.5.2

### Expected behavior

Show the tooltips of an image with range.
![Screenshot from 2022-12-14 10-22-59](https://user-images.githubusercontent.com/85873801/207557210-47991bc5-2a2d-47dd-9df1-0d411c097002.png)

### Observed behavior

Tooltips are not displayed when range is reversed.

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, show

x = np.linspace(0, 10, 300)
y = np.linspace(0, 10, 300)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx) * np.cos(yy)

range_x = bokeh.models.Range1d(start=0, end=10)
#range_y = bokeh.models.Range1d(start=0, end=10)
range_y = bokeh.models.Range1d(start=10, end=0)
p = figure(
    width=400, height=400, 
    x_range=range_x, y_range=range_y
)

p_image = p.image(image=[d], x=0, y=0, dw=10, dh=10, palette="Sunset11")
p.grid.grid_line_width = 0.5
p.add_tools(bokeh.models.tools.HoverTool(renderers=[p_image],
                              tooltips=[("x [fpx]", '$x'), 
                                        ("y [fpx]", '$y'),
                                        ("val", "@image")]
                             ))

show(p)
```

**Comment by mattpap** [comment]
It actually shows up, but in a wrong area:
![Screenshot 2022-12-14 10:52:40](https://user-images.githubusercontent.com/27475/207563594-16c21025-2fef-465f-a3bd-4bd8d8dd1023.png)
