### ISSUE TITLE
Docs on load balancing with Apache can be improved

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#12684]
### Problem description

The load balancing strategy for Apache specified [in the docs](https://docs.bokeh.org/en/latest/docs/user_guide/server/deploy.html#id2) (`byrequests`) does not ensure an optimal distribution of clients across server instances because it is based on the total number of requests served by each worker (see [Apache docs](https://httpd.apache.org/docs/current/en/mod/mod_lbmethod_byrequests.html)). This is not the right metric in the case of Bokeh servers.

### Feature description

Changing the policy to `bybusyness` would be better. It looks at the number of requests currently assigned to each worker (see [Apache docs](https://httpd.apache.org/docs/current/en/mod/mod_lbmethod_bybusyness.html)). I tested this setting and it yields better results.

### Potential alternatives

NA

**Comment by bryevdv** [comment]
@TheoMathurin As you are close to the use case and already have experience with the details of the proposed change, can you submit a PR to update them? The relevant file is here:

https://github.com/bokeh/bokeh/blob/branch-3.1/docs/bokeh/source/docs/user_guide/server/deploy.rst

**Comment by TheoMathurin** [comment]
Sure, this was my intention!
