### ISSUE TITLE
bokeh.plotting.image_url glyph is missing width and height parameters in the documentation

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#1268]
Current display:

![bokeh_plotting_interface_ _bokeh_0_6_1_documentation](https://cloud.githubusercontent.com/assets/4944634/4450012/2d17f65c-4821-11e4-8484-a4257f96455b.png)

**Comment by bryevdv** [comment]
This is now fully documented, automatically:

http://bokeh.pydata.org/en/latest/docs/reference/plotting.html#bokeh.plotting.figure.Figure.image_url
