### ISSUE TITLE
`ctx.arcTo()` is broken in SVG backend

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12699]
From PR #12655:
![image](https://user-images.githubusercontent.com/27475/209788050-a59c3c46-ac37-4d68-9063-6a43156587e6.png)

**Comment by mattpap** [comment]
Also ellipses are broken due to this (and essentially anything that depends on `arcTo()`):
![image](https://user-images.githubusercontent.com/27475/210136421-c4e8db01-c871-4c9a-b395-b1b9102dc08e.png)

**Comment by ianthomas23** [comment]
I'll deal with this, I suspect it is one of my previous "fixes" that has caused the problem.

**Comment by mattpap** [comment]
This is also broken with no rotation:
![image](https://github.com/bokeh/bokeh/assets/27475/745601c2-5187-4351-a8d1-122a879c6533)

**Comment by ianthomas23** [comment]
Upon investigation, this is broken for any SVG `arcTo` that is transformed, whether a rotation or translation or other. I understand the cause and will submit a PR to fix it shortly.
