### ISSUE TITLE
[BUG] DatePicker kills layout

### ISSUE THREAD

**Issue by PeterPyn** [bokeh/bokeh#12709]
### Software versions

Python version      :  3.8.12 (default, Jan 10 2022, 15:40:15) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  3.0.3
BokehJS static path :  C:\ProgramData\Anaconda3\envs\Py3.8\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

### Expected behavior

DatePicker showing up correctly.

### Observed behavior

Whenever I use DatePicker in Bokeh 3, the entire layout of my dashboard seems to be broken (all widgets in a column with 100% width). Was OK in 2.x

### Example code

```Python
import bokeh.plotting as bk
from bokeh.models.widgets import DatePicker, Select
from bokeh.layouts import row, column

p = bk.figure(width=600,
              height=600,
              title="Hello World!")
xs = [0,1,2,3,4,5]
ys = [x**2 for x in xs]

p.line(xs, ys, line_width=2)
s = Select(width=200)
dp = DatePicker(width=200)
b = column(s, dp, p)
#b = column(s, p)
bk.show (b)
```

**Comment by mattpap** [comment]
This seems to work now. Needs a regression test.
