### ISSUE TITLE
[BUG] Changing view's filter with group based legend causes redraw in canvas to be shifted

### ISSUE THREAD

**Issue by Northo** [bokeh/bokeh#12718]
### Software versions

Python version      :  3.10.0 (default, Sep  2 2022, 13:28:41) [Clang 13.1.6 (clang-1316.0.21.2.5)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.3
BokehJS static path : <redacted>/virtualenvs/minimal-example-demo-4tME3q5t-py3.10/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v19.1.0
npm version         :  8.19.3
Operating system    :  macOS-13.0-arm64-arm-64bit

### Browser name and version

Firefox 108.0.1 

### Expected behavior

We have three data points, each with a different color. We set the `legend_group` to be the data points' color.
![image](https://user-images.githubusercontent.com/7114880/210971762-d4f83eec-1bed-41b6-8799-7d4d3f22c85a.png)

We cahnge the view's filter to hide two of the data points and then change the filter back to show all points.

The plot should be drawn correctly on the canvas.

### Observed behavior

**Basic description**
When changing the view's filter
to hide two of the points and then removing the filter again, the canvas appears to
'shift and scale'. This only happens when the legend is activated (i.e. supplying a `legend_group`).
![image](https://user-images.githubusercontent.com/7114880/210971972-104b51bb-11f1-4011-a729-ed53f80117ef.png)

Repeating the process of turning the filter on and off makes the canvas shift and scale more.
![image](https://user-images.githubusercontent.com/7114880/210972146-0efe6da0-04e1-4063-b052-e72eabc08cc0.png)

We suspect this may be related to https://github.com/bokeh/bokeh/issues/8010.

---

**Other observations**

**Panning in filtered state**
When the app is in the state where only one point is shown (the filter is active), panning also causes multiple 'shift and scales to happen'. (In the below screenshot, we put the app in the filtered state, and then made one pan motion, resulting in many shfits).

![image](https://user-images.githubusercontent.com/7114880/210972671-107a8145-ec1a-4199-8f83-382384d4fa2b.png)

**Difference between browsers**
Below we use
- Firefox 108.0.1 
- Chrome 108.0.5359.124 (Official Build) (arm64)
- Safari 16.1 (18614.2.9.1.12)

The bug appears different in different browsers, but is present in all of them.
In Firefox the canvas seems to be redrawn smaller and to the top left corner, with large shifts. 
In chrome and safari, the canvas seem to shift toward the bottom right corner, and the shifts are much smaller and appear to 'zoom in' as opposed to Firefox.

In the three examples below, we set the app in the filtered state, and then panned up and down in a 'wavy' manner.

- Firefox 
  ![image](https://user-images.githubusercontent.com/7114880/210973318-76276748-ff82-4e2d-99da-9dbd507532d0.png)
- Chrome
  ![localhost_5006_demo](https://user-images.githubusercontent.com/7114880/210973374-6ef34124-2693-41bf-873d-994a28ab069c.png)
- Safari
![Screenshot 2023-01-06 at 10 37 01](https://user-images.githubusercontent.com/7114880/210973691-36493009-fee8-4c6b-89e9-a8b5d4089b6f.png)

_See note in **server vs static document for more details**_

**Server vs. static document**
We tried both serving the application using the bokeh server and exporting an html, which resulted in different behaviour. This is probably just an implementation thing in our test case, but worth noting. 
For the server, the plot and toggle button were attached as
```python
curdoc().add_root(plot)
curdoc().add_root(toggle_button)
```
while for the static html we did
```python
show(column(plot, toggle_button))
```

What was discussed in general above was using the Bokeh server approach. When using the static html (see [gist](https://gist.github.com/Northo/2f0934e2f628a3d60449d365ece6f710)), the behaviour in Firefox resembeled that of Chrome and Safari.
![image](https://user-images.githubusercontent.com/7114880/210977257-40800ee4-c548-469a-aa0d-e8c52cca0c16.png)

**Ony affects draw**
When selecting points, clicks and selection areas work on their "correct" position, not the new "shifted" position. I.e. the events from interacting with the plot map to the supposed position on the canvas, not the new shifted position.

### Example code

```Python
"""
Minimal example of 'canvas shift bug'.

We have three data points, each with a different color. When changing the view's filter
to hide two of the points and then removing the filter again, the canvas appears to
'shift'.

Probably related to https://github.com/bokeh/bokeh/issues/8010.

Jan. 6th 2023.
"""
from bokeh.layouts import column
from bokeh.models import (AllIndices, CDSView, ColumnDataSource, CustomJS,
                          IndexFilter, IntersectionFilter, Toggle)
from bokeh.plotting import curdoc, figure, show
from bokeh.transform import linear_cmap

data = {
    "values": [0, 1, 2],
    "type": [0, 1, 2],
    "constant": [1] * 3,
}

set1 = IndexFilter([1, 2])

combined_filter = IntersectionFilter(operands=[AllIndices()])

source = ColumnDataSource(data)
view = CDSView(filter=combined_filter)

fig = figure(tools=["pan", "box_select", "wheel_zoom", "reset", "examine"])
fig.circle(
    "values",
    "constant",
    source=source,
    view=view,
    legend_group="type",
    color=linear_cmap("type", "Viridis256", low=0, high=3),
)

all_indices = (
    AllIndices()
)  # Would be better to simply do this in the JS, but don't know how
set_combined_filter_cb_js = CustomJS(
    args=dict(set1=set1, view=view, all_filter=all_indices),
    code="""
view.filter = cb_obj.active ? set1 : all_filter;
""",
)

filter_form = Toggle()
filter_form.js_on_change("active", set_combined_filter_cb_js)

# show(column(fig, filter_form))
curdoc().add_root(fig)
curdoc().add_root(filter_form)
```

### Stack traceback or browser console output

Below is the stacktrace from turning the filter on and off, resulting in one 'shift' (in Firefox).
```
Uncaught (in promise) RangeError: offset is outside the bounds of the DataView
    get http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:202
    v_doit http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:244
    apply http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:244
    _render http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:503
    draw_legend_for_index http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:503
bokeh.min.js:202:981
Uncaught (in promise) RangeError: offset is outside the bounds of the DataView
    get http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:202
    v_doit http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:244
    apply http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:244
    _render http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:503
    draw_legend_for_index http://localhost:5006/static/js/bokeh.min.js?v=c0fd6d0714f0711512ead292f44613d47677ce99ea34eb56cd0971a46aea61b018dd3aa660b29ee0dae7c21113201e4a9243e21bf8be2644efc00f9d1fa272e1:503
bokeh.min.js:202:981

```

**Comment by Northo** [comment]
I suppose this has to do with the `LegendItem.index` pointing to som index that does not exist, and thus we get the ouside of bounds error, however, I don't know enough about Bokeh's internals to do more than speculating.

**Comment by mattpap** [comment]
We have to consider `CDSView`'s state when rendering a legend, to avoid touching filtered out indices, and map indices computed in bokeh (quite a bit of legend handling logic is in Python) to actual indices after filtering in bokehjs.

**Comment by mattpap** [comment]
> Would be better to simply do this in the JS, but don't know how

This is indeed how we would write it:
```py
all_indices =  AllIndices()
set_combined_filter_cb_js = CustomJS(args=dict(set1=set1, view=view, all_filter=all_indices), code="""
    view.filter = cb_obj.active ? set1 : all_filter;
""")
```
However, you can push more towards JS side with this:
```py
set_combined_filter_cb_js = CustomJS(args=dict(set1=set1, view=view), code="""
    const AllIndices = Bokeh.Models.get("AllIndices")
    view.filter = cb_obj.active ? set1 : new AllIndices()
""")
```
Otherwise, let us know you would expect here in terms of the API or ergonomics. There is relevant discussion going on in https://github.com/bokeh/bokeh/discussions/12668.

**Comment by Northo** [comment]
Thanks for the swift reply. Will try to follow #12668 and comment if I feel I have anything to contribute
