### ISSUE TITLE
[BUG] Updating DatePicker css_classes from callbacks not working

### ISSUE THREAD

**Issue by monadandan** [bokeh/bokeh#12714]
### Software versions

Python version      :  3.7.4 (default, Aug 13 2019, 15:17:50) 
IPython version     :  7.31.1
Tornado version     :  5.1.1
Bokeh version       :  2.4.2
BokehJS static path :  /Users/212613244/miniconda3/envs/acp_base2/lib/python3.7/site-packages/bokeh/server/static
node.js version     :  v16.6.1
npm version         :  7.20.3
Operating system    :  Darwin-19.6.0-x86_64-i386-64bit

### Browser name and version

Chrome Version 108.0.5359.124 (Official Build) (x86_64)

### Expected behavior

If I update the css_classes property of a datepicker from a callback, I would expect to see the class updated in the element in the page. In my example, I change a button css_class and see the behavior happen.

### Observed behavior

It did not update like the button does.

### Example code

```Python
from bokeh.layouts import column
from bokeh.models import DatePicker, Button
from bokeh.io import curdoc

d = DatePicker(css_classes=['test1'])
b = Button(css_classes=['test1'])


def change_css_class(_, __, ___):
    d.css_classes = ['test2']
    b.css_classes = ['test2']


def change_css_class_on_click():
    d.css_classes = ['test2']
    b.css_classes = ['test2']


d.on_change('value', change_css_class)
b.on_click(change_css_class_on_click)
curdoc().add_root(column(d, b))
```

### Screenshots

![image](https://user-images.githubusercontent.com/14826460/210855638-c49931d3-4051-437d-a588-34d5a924590b.png)
![image](https://user-images.githubusercontent.com/14826460/210855690-13daec53-d737-4dcb-9174-71218e7d4c87.png)
![image](https://user-images.githubusercontent.com/14826460/210855714-a96dd90e-959f-4a09-bcaa-56f9e73c8d0e.png)

**Comment by mattpap** [comment]
This happens because `DatePicker` has a custom rendering implementation that effectively prohibits updating its DOM.

**Comment by monadandan** [comment]
In case anyone else runs into this in the meantime, an easy work around is to add the css class to a layout containing the datepicker.
