### ISSUE TITLE
Type check errors due to updated `pandas-stubs`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12719]
```py
mypy 0.991 (compiled: yes)
src/bokeh/sampledata/us_marriages_divorces.py: note: In function "_read_data":
src/bokeh/sampledata/us_marriages_divorces.py:69:[12](https://github.com/bokeh/bokeh/actions/runs/3851947244/jobs/6563734189#step:6:13): error: Item "None" of
"Optional[DataFrame]" has no attribute "ffill"  [union-attr]
        return data.interpolate(method='linear', axis=0).ffill().bfill()
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 726 source files)
```

This seems to be a regression of types in `pandas-stubs`, because instead of having overrides for cases:
* `interpolate(..., inplace: Literal[True]) -> None`
* `interpolate(..., inplace: Literal[False]) -> DataFrame`
now there is one case:
* `interpolate(..., inplace: bool) -> DataFrame | None`
which results in the above error. Sadly mypy doesn't provide `!` operator like TypeScript, so this code has to be rewritten into two lines with an `assert` statement, to rule out `None`.

**Comment by bryevdv** [comment]
Is there an upstream issue anywhere for this?

**Comment by bryevdv** [comment]
@mattpap where are you seeing only one case? I still see overloads e.g. here

https://github.com/pandas-dev/pandas-stubs/blob/main/pandas-stubs/core/frame.pyi
https://github.com/pandas-dev/pandas-stubs/blob/v1.5.2.230105/pandas-stubs/core/frame.pyi

**Comment by mattpap** [comment]
I'm not sure exactly what's happening, but for me it resolves directly to pandas' source code:
```py
    @deprecate_nonkeyword_arguments(version=None, allowed_args=["self", "method"])
    def interpolate(
        self: DataFrame,
        method: str = "linear",
        axis: Axis = 0,
        limit: int | None = None,
        inplace: bool = False,
        limit_direction: str | None = None,
        limit_area: str | None = None,
        downcast: str | None = None,
        **kwargs,
    ) -> DataFrame | None:
        return super().interpolate(
            method,
            axis,
            limit,
            inplace,
            limit_direction,
            limit_area,
            downcast,
            **kwargs,
        )
```
which has type annotations, but in the less useful form.
