### ISSUE TITLE
Can client request that bokeh-server reload data from file?

### ISSUE THREAD

**Issue by nerduno** [bokeh/bokeh#1272]
In order to use bokeh's line-downsampling locally within an ipython notebook, my notebook cell writes the data I'd like to plot to an hdf5 file in the remotedata directory, and then plots the remote data source.  Ideally, the cell could be run multiple times using the same filename, but because the bokeh-server caches the data in memory, overwriting the hdf5 is ineffective.  Is there a mechanism by which I can tell the bokeh-server to reload a data source and/or clear its cache?

Thanks again for the great package.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
