### ISSUE TITLE
Docker builds are failing with `XML_CATALOG_FILES: unbound variable`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12733]
Precisely with:
```
/home/docker/conda_bokeh/envs/bkdev/etc/conda/activate.d/libxml2_activate.sh: line 3: XML_CATALOG_FILES: unbound variable
```
in e.g. https://github.com/bokeh/bokeh/actions/runs/3897352221/jobs/6655087977, but I've been seeing this in multiple PRs since at least Tuesday.

**Comment by niklaskeil** [comment]
Hi there! I had the same issue and disabling the unset variable checking (i.e. `set +u`) solved it temporarily for me, see here for the root of the issue: https://github.com/conda-forge/libxml2-feedstock/pull/82

**Comment by mattpap** [comment]
Relevant packages were fixed upstream. Docker builds are now passing again.
