### ISSUE TITLE
[BUG] hatching scales differently on different displays

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12735]
### Software versions

Python version      :  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
IPython version     :  8.7.0
Tornado version     :  6.2
Bokeh version       :  3.1.0.dev1+19.g0e72ad3c
BokehJS static path :  /Users/iant/github/bokeh/src/bokeh/server/static
node.js version     :  v18.11.0
npm version         :  8.19.2
Operating system    :  macOS-12.6.2-arm64-arm-64bit

### Browser name and version

Doesn't seem to be browser-specific

### Expected behavior

Hatching is drawn with a different scale to other plot features on different displays. In my two examples both svg and webgl backends look OK but canvas varies.

### Observed behavior

Should have same scale (with respect to other plot features) on all displays.

### Example code

```Python
from bokeh.layouts import row
from bokeh.plotting import figure, show

ps = []
for backend in ('canvas', 'svg', 'webgl'):
    p = figure(width=200, height=200, output_backend=backend, title=backend)
    ps.append(p)

    p.quad(left=0, right=1, top=1, bottom=0, fill_color="orange",
           line_color="blue", alpha=0.5, hatch_pattern='x')

show(row(ps))
```

### Screenshots

Screenshot from linux laptop, pixel ratio of about 1.06:
![hatch_linux](https://user-images.githubusercontent.com/580326/212064832-65a7a26b-8618-438a-afef-a3f49e39342e.png)

Screenshot from external monitor attached to M1 mac, pixel ratio of 2:
<img width="603" alt="hatch_mac" src="https://user-images.githubusercontent.com/580326/212064851-72238fda-2615-40c1-9f47-db1749bc614f.png">

**Comment by ianthomas23** [comment]
It would be good if someone else with a retina display could try this out to see if it actually a problem or something dodgy in my dual-screen setup.

**Comment by mattpap** [comment]
@ianthomas23, you don't need a high DPI physical display to verify such issues. This can be done in devtools' emulation mode, like here (on a normal DPI display):

![image](https://user-images.githubusercontent.com/27475/212473460-63b5fe93-5aac-4964-a9cb-4a140f47ba20.png)

You can enable it here:

![image](https://user-images.githubusercontent.com/27475/212473696-05abe8ab-30c4-4ad0-b666-4d3521dec1e4.png)

**Comment by ianthomas23** [comment]
@mattpap Thanks for that.
