### ISSUE TITLE
[BUG] No such file: examples/plotting/marker_map.py

### ISSUE THREAD

**Issue by ninousf** [bokeh/bokeh#12730]
### Software versions

Python version      :  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]
IPython version     :  8.8.0
Tornado version     :  6.2
Bokeh version       :  3.1.0.dev1+19.g0e72ad3c
node.js version     :  v16.17.1
npm version         :  8.19.3
Operating system    :  Linux-5.14.0-1055-oem-x86_64-with-glibc2.31

### Expected behavior

following the dev. guide, in the setup.html page, the example:
`BOKEH_RESOURCES=inline python examples/plotting/marker_map.py`

### Observed behavior

python: can't open file '.../git/bokeh/examples/plotting/marker_map.py': [Errno 2] No such file or directory

### Example code

```Python
`BOKEH_RESOURCES=inline python examples/plotting/marker_map.py`
```

**Comment by mattpap** [comment]
The example was moved and renamed to `examples/basic/data/transform_markers.py`, but the documentation was not updated.

**Comment by mattpap** [comment]
```
$ git grep marker_map docs/
docs/bokeh/source/docs/dev_guide/setup.rst:            BOKEH_RESOURCES=inline python examples/plotting/marker_map.py
docs/bokeh/source/docs/dev_guide/setup.rst:            python.exe .\examples\plotting\file\marker_map.py
docs/bokeh/source/docs/dev_guide/setup.rst:            python examples\plotting\file\marker_map.py
docs/bokeh/source/docs/dev_guide/setup.rst:This creates a file ``marker_map.html`` locally. When you open this file in a web
docs/bokeh/source/docs/dev_guide/setup.rst:.. image:: /_images/bokeh_marker_map_html.png
```
