### ISSUE TITLE
[DOCS] rect glyph shouldn't be used on log axes

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12734]
### Software versions

Python version      :  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
IPython version     :  8.7.0
Tornado version     :  6.2
Bokeh version       :  3.0.0+53.g17cc3af6.dirty
BokehJS static path :  /Users/iant/github/bokeh/src/bokeh/server/static
node.js version     :  v18.11.0
npm version         :  8.19.2
Operating system    :  macOS-12.6.2-arm64-arm-64bit

### Expected behavior

See code and screenshot below. Each plot has a `quad` glyph on the left and a `rect` glyph on the right, both are supposed to be displayed at the same y-position. It is correct for canvas backend but not for WebGL.

### Observed behavior

See screenshot below.

### Example code

```Python
from bokeh.layouts import row
from bokeh.plotting import figure, show

left = 0
right = 10
top = 1e3
bottom = 1e-7

xmid = 0.5*(left + right)
ymid = 0.5*(top + bottom)
width = right - left
height = top - bottom

kwargs = dict(fill_color="orange", line_color="blue", alpha=0.5)

ps = []
for backend in ('canvas', 'webgl'):
    p = figure(width=300, height=300, output_backend=backend, title=backend, y_axis_type='log')
    ps.append(p)

    p.quad(left=left, right=right, top=top, bottom=bottom, **kwargs)
    p.rect(x=xmid + 10, y=ymid, width=width, height=height, **kwargs)

show(row(ps))
```

### Screenshots

<img width="591" alt="Screenshot 2023-01-12 at 11 53 28" src="https://user-images.githubusercontent.com/580326/212061324-74475938-f453-4e04-af82-962acfbfc7b5.png">

**Comment by mattpap** [comment]
Given that webgl backend works in screen space, then type of axis shouldn't matter?

**Comment by ianthomas23** [comment]
It shouldn't matter, but evidently it does!

I suspect what is happening is that we have two sets of transformed coordinates for `rect`, a left/right/top/bottom and a center/width/height, and webgl is can take either for linear axis but for log axis they give different results, depending on whether the log transform is applied before or after the transform from center/width/height to left/right/top/bottom.

**Comment by ianthomas23** [comment]
I've started to look at this with the idea of making the webgl output the same as canvas, assuming that the canvas solution is correct. And that "fix" isn't difficult. But the more I think about it the less happy I am with either output.

Take a look at this, which uses the same code as above except it includes a `block` glyph on the left then the `quad` glyph and finally the `rect` glyph on the right has a rotation of 0.1 radians. This is using latest `branch-3.1`.

<img width="594" alt="Screenshot 2023-01-27 at 13 40 22" src="https://user-images.githubusercontent.com/580326/215100599-933623cd-033e-4241-9240-a1b1f170f777.png">

Canvas and webgl output are the same. I've added a blue circle where the centre of the rotated `rect` glyph is. The canvas rendering of `rect` has a different code path for `alpha = 0` than for `alpha != 0`, and here it looks like both canvas and webgl are correct. Or maybe both incorrect?

Now I am struggling to predict what should displayed for a `rect` glyph characterised by width, height and rotation when it is on logarithmic axes. The width and height presumably refer to the glyph size in its rotated frame of reference, and for `alpha != 0` each of the width and height projects partially onto both x and y axes, so here partially onto one linear and one logarithmic axis. I don't think any of this is well defined, in fact I suspect that in principle any rotatable glyph with a size specified in data units cannot be rendered on log axes.

**Comment by bryevdv** [comment]
> I don't think any of this is well defined, in fact I suspect that in principle any rotatable glyph with a size specified in data units cannot be rendered on log axes.

I agree with this 100% and I would suggest explicitly documenting these cases as undefined behavior and not spend any effort beyond that.

**Comment by ianthomas23** [comment]
OK, I am changing the title and labels of this issue to indicate that it is a docs issue not a bug. I'll submit a PR shortly.
