### ISSUE TITLE
[FEATURE] Add transform.eqhist_cmap

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12752]
### Problem description

We have in `bokeh.transform` both `linear_cmap` and `log_cmap` as handy one-liners to create and use `LinearColorMapper` and `LogColorMapper` objects on a single field. There is no corresponding `eqhist_cmap` for `EqHistColorMapper` and the should be for completeness.

### Feature description

New Python function `eqhist_cmap` and corresponding Python unit tests. It should be relatively easy to follow the approach of `log_cmap`.

### Potential alternatives

Do nothing.

**Comment by ianthomas23** [comment]
I am labelling this as a good first issue as it is Python-only and the solution will be very similar to `log_cmap` and `linear_cmap`.

**Comment by bryevdv** [comment]
cc @tcmetzger @pavithraes can we apply the "good first issue" template to this issue (and clear out all other comments)?

**Comment by DerTimonius** [comment]
Hi @ianthomas23 I'm interested in contributing to this issue. First time for me with this repo 👍

**Comment by ianthomas23** [comment]
> Hi @ianthomas23 I'm interested in contributing to this issue. First time for me with this repo 👍

Hi @DerTimonius, we are pleased to hear that! Let us know if you need any guidance at any stage.

**Comment by bryevdv** [comment]
@DerTimonius for reference the module to add the new function to is here:

https://github.com/bokeh/bokeh/blob/branch-3.1/src/bokeh/transform.py

and the corresponding module for unit tests is here:

https://github.com/bokeh/bokeh/blob/branch-3.1/tests/unit/bokeh/test_transform.py

**Comment by DerTimonius** [comment]
@bryevdv thank you, I looked at the code yesterday and will tackle it later today!

**Comment by DerTimonius** [comment]
First of all thank you for the great guide for setting up a dev environment (and all other guides for contributing, they are awesome)👍 
Ran into issues at some point (after building `bokeh` locally): when running the `bokeh sampledata` command I'm getting a *KeyError: "0.0.1"* . I tried resetting everything as described at the `troubleshooting` section but to no avail.

I still implemented the code that I think is the correct answer (locally so far) and since I'm not able to test it yet I was wondering if I should just let the tests on the Github Actions take care of that?

**Comment by ianthomas23** [comment]
> Ran into issues at some point (after building `bokeh` locally): when running the `bokeh sampledata` command I'm getting a _KeyError: "0.0.1"_ . I tried resetting everything as described at the `troubleshooting` section but to no avail.

This shouldn't happen! It sounds like a problem determining the version of Bokeh installed. There was an issue about this on discourse recently, although I am not sure it will be of much help: https://discourse.bokeh.org/t/editable-installation-keyerror/9898

> I still implemented the code that I think is the correct answer (locally so far) and since I'm not able to test it yet I was wondering if I should just let the tests on the Github Actions take care of that?

Yes, it is fine to use Github Actions for this. Ideally we would identify and fix the `KeyError`, but you may as well make some progress with the PR in the meantime.

**Comment by bryevdv** [comment]
The 0.0.1 version issue has been seen intermittently, but as yet no core devs have been able to reproduce it. Can you open a [GitHub discussion] with more details (exact install steps, platform, etc) we can hopefully try to finally get to the bottom of this issue.

**Comment by DerTimonius** [comment]
@bryevdv I opened a new discussion [here](https://github.com/bokeh/bokeh/discussions/12763) 👍
