### ISSUE TITLE
Line-downsampling request buffering 

### ISSUE THREAD

**Issue by nerduno** [bokeh/bokeh#1275]
I've been testing your line-downsampling code and I've noticed performance issues using wheel-zoom with time-series containing more than 200,000 points (though this will likely be system dependant).  

The issue seems to be that the wheel-zoom generates a series of intermediate downsampled data requests which the server cannot keep up with in real-time.  Rather than jump to processing the most recent request, the server appears to process all the requests in order causing the display to lag badly and display strange data.

Then on occasion something fails and the downsampling stops updating altogether.

I'm using Chrome on MacOSX Mavericks.  Here is a ipython notebook code snippet:

```Python
import bokeh.plotting as bplot

#create server dataset
import numpy as np
import pandas as pd 
from bokeh.transforms import line_downsample
time = np.arange(500000)
value = np.random.randn(500000)
df = pd.DataFrame({'time':time, 'value':value})
df.to_hdf('/Users/andalman/.bokeh/remotedata/defaultuser/test.hdf5','__data__',mode='w',format='table',data_columns=True)

#start server
%cd '/Users/andalman/.bokeh/'
bokeh_server_process = subprocess.Popen(['bokeh-server','-D','remotedata'])
time.sleep(3)

#set output
bplot.output_notebook(docname="test-downsample",url="http://127.0.0.1:5006/")

  
#generate auto-downsampling time_series plot
source = line_downsample.source(data_url="/defaultuser/test.hdf5", 
                                                        owner_username="defaultuser",
                                                        domain='x',
                                                        )
 f = bplot.figure(tools="pan,wheel_zoom,box_zoom,reset,previewsave", plot_width=300, plot_height=300)
 bplot.hold()
 bplot.line('time', 'value',
             color='#A6CEE3', tools="pan,wheel_zoom,box_zoom,reset,previewsave",
             source=source,
             )
bplot.show(f)
```

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
