### ISSUE TITLE
Dev setup docs needs to ensure repo tags

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12768]
The source of the `version == '0.0.1'` has been analyzed and discovered to be a result of a local repo checkout not having any of the release tags present. @ianthomas23 noted in https://github.com/bokeh/bokeh/discussions/12763

> If you fork the bokeh repo via the github UI the default behaviour is to "Copy the branch-3.1 branch only". Evidently this doesn't include the tags. 

So we could include screenshots/instructions to uncheck that GUI setting, however if there is an explicit command-line invocation that will do the right thing, regardless of that setting, I think that would be simpler and preferable. 

cc @tcmetzger

**Comment by DerTimonius** [comment]
Since I had this issue myself, I could update the docs if you'd like 🙂

**Comment by tcmetzger** [comment]
@DerTimonius That would be great, thank you! Please let me know if you have any questions!

**Comment by DerTimonius** [comment]
@tcmetzger I did not include a screenshot, but concice instructions. I hope that's okay.
