### ISSUE TITLE
[BUG] Can not change icon of a tools

### ISSUE THREAD

**Issue by orena1** [bokeh/bokeh#12774]
### Software versions

Python version      :  3.9.13 (main, Aug 25 2022, 18:29:29)
IPython version     :  7.31.1
Tornado version     :  6.1
Bokeh version       :  3.0.3
BokehJS static path :  /Users/orenamsalem/opt/anaconda3/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  macOS-10.16-x86_64-i386-64bit

### Browser name and version

chrome 

### Jupyter notebook / Jupyter Lab version

Jupyter Lab - Version 3.4.4

### Expected behavior

It seems that all options for setting custom icon do not work. 
This simple code preset the problem:
```python
from PIL import Image
from pathlib import Path
import numpy as np 
from bokeh.models import PolyDrawTool
from bokeh.plotting import figure, output_notebook, show
output_notebook()

im_icon = Image.open('B_icon.png')
im_icon = im_icon.convert("RGBA")
imarray_icon  = np.array(im_icon)


# all those do not work
p = figure(title="Simple line example", x_axis_label='x', y_axis_label='y')
# add a line renderer with legend and line thickness to the plot
p.line([1,2], [2,3], legend_label="Temp.", line_width=2)
renderer_in = p.multi_line([], [], line_width=5, alpha=0.4, color='red')


#draw_tool_in = PolyDrawTool(renderers=[renderer_in], num_objects=50,icon='CC.svg')
#draw_tool_in = PolyDrawTool(renderers=[renderer_in], num_objects=50,icon='B_icon.png')
#draw_tool_in = PolyDrawTool(renderers=[renderer_in], num_objects=50,icon='A_icon.icon')
#draw_tool_in = PolyDrawTool(renderers=[renderer_in], num_objects=50,icon=Path('B_icon.png'))
draw_tool_in = PolyDrawTool(renderers=[renderer_in], num_objects=50,icon=imarray_icon)


p.add_tools(draw_tool_in)
show(p)

```
[Here are the files used in this exmaple](https://github.com/bokeh/bokeh/files/10564075/example_icons.zip)

I get the following errors, depending on the attempt:
For rgba numpy array: `Javascript Error: PolyDrawTool(p3720).icon given invalid value: {"0":0,"1":0,"2":0,"3`
For Path('B_icon.png'): `SerializationError: can't serialize <class 'pathlib.PosixPath'>`  (releated #11830 ?)
For all the rest I get:  `Javascript Error: PolyDrawTool(p4389).icon given invalid value: "B_icon.png"`

### Observed behavior

Icon should have change, it did work with with bokeh 2.3 using:
`draw_tool_in.custom_icon = Path('A_icon.png')`

**Comment by orena1** [comment]
The problem is that [Image](https://github.com/bokeh/bokeh/blob/b9e458cfef6e3d86f79c53b507f08b220bf487ae/src/bokeh/core/property/visual.py#L140)  function [transform](https://github.com/bokeh/bokeh/blob/b9e458cfef6e3d86f79c53b507f08b220bf487ae/src/bokeh/core/property/visual.py#L168) is not executing, this is because in this line
https://github.com/bokeh/bokeh/blob/b9e458cfef6e3d86f79c53b507f08b220bf487ae/src/bokeh/models/tools.py#L173

Image is the last in the list, and therefore when transform of the Either is executed: https://github.com/bokeh/bokeh/blob/b9e458cfef6e3d86f79c53b507f08b220bf487ae/src/bokeh/core/property/either.py#L86
Enum(ToolIcon)  transform is the first in the list and it is the one that is executed. 

So there is a bit of a problem with [Either](https://github.com/bokeh/bokeh/blob/b9e458cfef6e3d86f79c53b507f08b220bf487ae/src/bokeh/core/property/either.py#L54) and it is more of a conceptual problem, what the first transform in the list is the one that should be executed.

Anyway, one solution which is in the pull request is to put Image first in the list, it works... But I don't know the consequences as it is the first day that I look at the code. 

Another option is in validate:
https://github.com/bokeh/bokeh/blob/b9e458cfef6e3d86f79c53b507f08b220bf487ae/src/bokeh/core/property/either.py#L97
To remove all the objected that did not pass validation, and keeping only those that pass, hopefully it will be only one.


Happy to hear what ppl think.
Thanks

**Comment by bryevdv** [comment]
I feel like a more general solution here might be to add a `transform` method to `Enum` that raises a `ValueError` for values that are not valid. cc @bokeh/core

**Comment by mattpap** [comment]
I will close this one in favour of the original bug report in #11830.

**Comment by orena1** [comment]
Sure, although #11830 only mention supplied PIL, the problem is that non of the options work, not only PIL, thanks

**Comment by orena1** [comment]
BTW, to whoever see that, the only workaround that I found  (that does not change the code) is this:
```python
def load_icon(path):
    with open(path, "rb") as image_file:
        data = base64.b64encode(image_file.read()).decode('utf-8')
    return f'data:image/png;base64,{data}'
draw_tool1 = PolyDrawTool(renderers=[p1], vertex_renderer=c1,icon=load_icon('B_icon.png'), description='Inside')
```
