### ISSUE TITLE
Syncing two input widgets without infinite callback loop

### ISSUE THREAD

**Issue by samzhang111** [bokeh/bokeh#1277]
I tried to attach a slider and a text field to the same plot, and have slider and text field sync up. However, they triggered each other's callbacks, leading to various boomerang/infinite loops.

    ......
        text = bkw.TextInput(
                value=str(default_val), 
                title='Population Beta:')
        text.on_change('value', self.on_text_change)
        
        slider = bkw.Slider(
                start=-self.maxval, 
                end=self.maxval, 
                value=default_val, 
                step=1, 
                title='Population Beta')
        slider.on_change('value', self.on_slider_change)

    .........

    def on_slider_change(self, obj, attr, old, new):
        self.update_data(new)
    
    def on_text_change(self, obj, attr, old, new):
        try:
            n = int(new)
            n = max(n, -self.maxval)
            n = min(n, self.maxval)

            self.update_data(n)
        except ValueError:
            return

I tried to control for this with my own locks, but it becomes hairy and probably something that should be more atomic.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by samzhang111** [comment]
FYI, I asked a few related but not identical questions on StackOverflow and it looks like quite a few other people are also curious: http://stackoverflow.com/questions/26176074/multiple-questions-with-object-oriented-bokeh

**Comment by birdsarah** [comment]
Thanks @samzhang111 - re-opening and adding tracker status - maybe someone will have an answer.

**Comment by bryevdv** [comment]
The following code works correctly with the new server in `0.12`, closing:
```
from bokeh.models import TextInput, Slider
from bokeh.layouts import widgetbox
from bokeh.io import curdoc

def on_slider_change(attr, old, new):
    text.value = str(new)

def on_text_change(attr, old, new):
    try:
        n = int(new)
        n = max(n, -10)
        n = min(n, 10)

        slider.value = n
    except ValueError:
        return

text = TextInput(
        value=str(2),
        title='Population Beta:')
text.on_change('value', on_text_change)

slider = Slider(
        start=-10,
        end=10,
        value=2,
        step=1,
        title='Population Beta')
slider.on_change('value', on_slider_change)

curdoc().add_root(widgetbox(text, slider))
```

**Comment by zoohair** [comment]
I tried this with a range slider and update the range attribute does not update the widget. 

Any chance to have that fixed or is there a workaround?

```
from bokeh.models import TextInput, RangeSlider
from bokeh.layouts import widgetbox
from bokeh.io import curdoc
from bokeh.client import push_session

def on_slider_change(attr, old, new):
    text.value = str(new[1])

def on_text_change(attr, old, new):
    try:
        n = int(new)
        n = max(n, -10)
        n = min(n, 10)

        slider.range = (0, n)

    except ValueError:
        return

text = TextInput(
        value=str(2),
        title='Population Beta:')
text.on_change('value', on_text_change)

slider = RangeSlider(
        start=0,
        end=10,
        range=(0, 2),
        step=1,
        title='Population Beta')

slider.on_change('range', on_slider_change)

curdoc().add_root(widgetbox(text, slider))

#session = push_session(curdoc())
#session.show(widgetbox(text, slider)) # open the document in a browser
#session.loop_until_closed() # run forever
```
