### ISSUE TITLE
Add configurable option for invoking callback when pressing enter for TextInput 

### ISSUE THREAD

**Issue by sandhujasmine** [bokeh/bokeh#12772]
### Problem description

I have a UI around stable diffusion that invokes a callback to generate an image for a given text input. 
Pressing enter on the TextInput widget is a clean interface; however, by default the callback is only invoked if the value in the TextInput changes. In this case, the random seed is changing by default so there is a use case for generating a diversity of images for the same text input. It would be useful if you could configure the behavior of the TextInput to invoke the callback or trigger an event even if the value of the widget has not changed.

### Feature description

A configurable option for the TextInput widget, which if enabled invokes the callback every time enter is pressed.

### Potential alternatives

Currently I also have a button which needs to be used to invoke the callback if the text doesn't change

**Comment by jbednar** [comment]
It's possible to work around this, but I think it's very reasonable to assume that some authors will want events only when the text changes, and others will always want an event, so having an option seems appropriate to me.
