### ISSUE TITLE
Log messages point to jsnlog.min.js:9 instead of their sources

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1278]
With this in mind, simple `console.log()` is much better, because you see file name and line number where an event occurred and you can even click on the message to get to the location. Now all messages point to `jsnlog.min.js:9`. @bryevdv, I suppose that as long as we use a logging framework, there is no luck in getting the original behavior back, this issue is a `wontfix`? After all, JavaScript doesn't support macros.

**Comment by damianavila** [comment]
>revert to console.log entirely

Involution...

>use console.log just in places where we really, really want line numbers

mmm... not enough consistency

>create per-module loggers to at least provide some better info in the output

maybe, but probably not adding too much...

>live with what we have
>I personally think that the ability to have different log levels switched on an off is more valuable than the line numbers, so I'm inclined to say we should just go with "live with it"

Probably "live with it" until find something better... or some hack to provide the requested info... I pointed a link above that could help... or I am missing something and it will not work at all?

**Comment by bryevdv** [comment]
The link above only pertains to logging caught exceptions, not just any arbitrary log statement. It seems we are agreed to live with, so closing. Feel free to re-open if there is something relevant to add.

**Comment by mattpap** [comment]
Yeah, we have to leave with this, at least for now. This might be revisited when we switch from CoffeeScript to a language that supports macros.
