### ISSUE TITLE
[BUG] Streaming broken when switching from Array to TypedArray

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#12788]
### Software versions

Bokeh: 3.1.0dev1

### Expected behavior

When streaming data to a `ColumnDataSource` it could be coming from multiple different sources or be initially supplied as a list and subsequently be provided as an array (or vice versa). On the client side this should all behave the same and it should appropriately combine regular and typed arrays.

### Observed behavior

What we observe when streaming arrays to a ColumnDataSource that was initialized as lists is that it does not merge the to correctly and you end up with a typed array inside the regular array:

<img width="339" alt="Screen Shot 2023-02-07 at 18 10 36" src="https://user-images.githubusercontent.com/1550771/217315132-2d5cf149-dee2-4c4e-9607-31ceceaa5665.png">

This will confuse any model that tries to consume that data and you can end up with this:

<img width="921" alt="Screen Shot 2023-02-07 at 18 11 25" src="https://user-images.githubusercontent.com/1550771/217315341-caafaed2-5c6e-4784-b4da-0bf3d360a70c.png">

### Example code

```Python
import numpy as np

from bokeh.io import curdoc
from bokeh.models import Button, Column, ColumnDataSource, DataTable, TableColumn

data = dict(A=list(np.random.rand(3)), B=list(np.random.rand(3)))
source = ColumnDataSource(data)
columns = [TableColumn(field=c, title=c) for c in data]
data_table = DataTable(source=source, columns=columns)

b = Button(label='Click')

def add(event):
    source.stream({'A': np.random.rand(10), 'B': np.random.rand(10)})
    
b.on_click(add)

column = Column(children=[b, data_table])

curdoc().add_root(column)
```

**Comment by hoxbro** [comment]
A related thing is if the data source is numpy arrays with type object. The table will disappear. 

``` python
import numpy as np

from bokeh.io import curdoc
from bokeh.models import Button, Column, ColumnDataSource, DataTable, TableColumn

data = dict(A=np.array(list("ABCD")), B=np.array(list("ABCD")))  # Does not work
# data = dict(A=list("ABCD"), B=list("ABCD"))  # Does work
source = ColumnDataSource(data)
columns = [TableColumn(field=c, title=c) for c in data]
data_table = DataTable(source=source, columns=columns)

b = Button(label="Click")


def add(event):
    source.stream({"A": list("EDF"), "B": list("EDF")})


b.on_click(add)

column = Column(children=[b, data_table])

curdoc().add_root(column)
```

https://user-images.githubusercontent.com/19758978/217323727-0d462dc4-6833-418c-bbdf-5b28d8de0566.mp4
