### ISSUE TITLE
Support a hive plot chart type

### ISSUE THREAD

**Issue by alexbw** [bokeh/bokeh#1279]
Posting an issue at the behest of @bryevdv on the mailing list.

I've been using hive plots to display network data with a lot more success than force-directed layouts. I was wondering if there is any functionality for building them in Bokeh?
For an example, see: http://www.hiveplot.net/.

To be clear, I plan on taking a crack at this in the near future, and it seems like this is very low priority for the Bokeh team, so I hope to submit a PR at some point. No guarantees, as usual.

**Comment by bryevdv** [comment]
Requests for new high level charts should now be opened in https://github.com/bokeh/bkcharts
