### ISSUE TITLE
Docker image improvements

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#12803]
We'll need to update the docker dev image after release of 3.1. At the same time it would be good to add:

- Tag the image by the version of chrome it uses.
- Setup `pre-commit` in the conda environment.
- Install `make` so the image can be used to build the docs.

**Comment by mattpap** [comment]
I would expand this list with:

* disable progress for `conda env create` and sample data download
* make sure all scripts use `set -x`, so that we know what commands are executed
* `npm install --location=global npm@8` can be removed as long as most recent LTS of node.js is used

**Comment by ianthomas23** [comment]
Also

- Export docs server port 5009

**Comment by bryevdv** [comment]
@ianthomas23 do you want to close this altogether or move to 3.x?

**Comment by ianthomas23** [comment]
I am inclined to close it as I don't use the docker image in my dev workflow any more.

I would happily *help* someone else if they wanted to drive this forward, but I don't want to drive it myself.

**Comment by bryevdv** [comment]
I'm going to go ahead and close, someone can re-open, or open a new issue if they are interested in working on this. Realistically I think we might just consider dropping docker-related CI entirely in the near future. There is really a need for a dedicated docker champion (someone who uses/likes docker) and we just don't have such a person at present.
