### ISSUE TITLE
[FEATURE] Independent extra ranges in a single figure

### ISSUE THREAD

**Issue by jlstevens** [bokeh/bokeh#12829]
### Problem description

The request here is to have extra axes (e.g. twin axes) where each axis can be independently zoomed (e.g. when hovering over that specific axis with the wheel zoom tool). For instance, currently, if you have twin-y axes, both axes zoom together no matter where you hover when wheel zooming.

### Feature description

This feature request that has been mentioned in the past on [discourse](https://discourse.bokeh.org/t/independent-extra-ranges-in-one-figure/9658).

I would consider this a significant limitation when thinking about multiple axes: the current support is great if you have two different *scales* on the same dimension/axis (e.g. left side shows the temperature in Celsius, the right side shows Fahrenheit - both are temperature) but is far less useful when the quantities/units are different. 

For instance, if you have temperature and precipitation time series data over the same time period, zooming in/out of the temperature data should have no bearing on the display of the precipitation data as those are two different types of quantity.

What I imagine would work in a backwards compatible way is a mechanism to link/unlink the axes. By default the axes could be declared as linked, preserving the current default behavior.

### Potential alternatives

I do not know of any alternatives and would love if someone could suggest a workaround here!

Maybe it is possible to directly overlay two bokeh plots at the DOM (or some other, more appropriate) level?

### Additional information

@bryevdv Suggests that he thought that there is an open issue about this already on the [discourse thread]( https://discourse.bokeh.org/t/independent-extra-ranges-in-one-figure/9658) but I could not find it either after looking. Happy to see this issue closed as a duplicate if we do find the original. Meanwhile, this issue will at least make sure the request is recorded somewhere.

**Comment by mattpap** [comment]
I see two features here:
1. Allow to configure zoom tools with renderers, allowing multiple zoom tools per plot working with different renderers, affecting different sets of ranges. This would work similarly to how select tools work in this regard.
2. Make wheel zoom tool affect only a specific range when used over an associated axis.

Tentatively scheduling for 3.2.

**Comment by jlstevens** [comment]
I agree with the separation you suggest. 

Would the second sub-feature (having the zoom tool affect only the associated axis) mean imply that a more general decoupling between the axes? 

For instance, would this also allow you to update the ranges from JS independently for the two axes? Here I am thinking of the new `autorange='y'` parameter in HoloViews which uses `CustomJS` to automatically update the ranges to the viewable data. 

I would assume so: whatever way the zoom tool interacts with each axis individually should be possible from other JS code, just checking!

**Comment by jbednar** [comment]
Note that even "unlinked" axes should still both zoom together when using box or wheel zoom on the figure viewport; the only way they would zoom differently in the UI would be when zooming on one or the other axes themselves (outside the viewport).
