### ISSUE TITLE
Dynamically update contour plots using data_source

### ISSUE THREAD

**Issue by psmaragdis** [bokeh/bokeh#12842]
### Problem description

With most other types of plots I can do something like (e.g. in the case of image plots in a Jupyter notebook):
```
plot_handle.data_source.data = {'image': [new_data_matrix]}
push_notebook()
```
and dynamically (and efficiently) update a plot.  This is very useful for interactive plotting.

It looks like contour doesn't have a `data_source` field.  Instead there is a list of data_sources describing all the contour lines instead.  However, updating the contour plot that way is cumbersome.

### Feature description

 It would be handy to have the option to just provide a new contour matrix and have the plot update the same way as other plots do.  E.g. something like:
```
plot_handle.data_source.data = {'z': new_data_matrix}
push_notebook()
```

### Potential alternatives

Given the structure of the other types of plots, I think this is the only reasonable approach since it would be using an already existing programming model.

It would be nice to also allow the update of the other parameters that way (x, y, levels).

**Comment by ianthomas23** [comment]
Contour plots do not work like this.

A Bokeh `GlyphRenderer` has a `Glyph` (e.g. `Rect`) and a `data_source` that is a `ColumnDataSource` (CDS). You can update the CDS in Python and it is automatically synchronised with BokehJS and used directly for rendering. 

Contouring occurs via a `ContourRenderer` (derived from `DataRenderer` not `GlyphRenderer`) and is a collection of glyphs, each with its own CDS. The contents of those glyph CDSs are calculated on the Python side from the `x`, `y`, `z`, etc arrays. There is no overall CDS to update here, and you don't want there to be as it would automatically serialize the `x`, `y`, `z` gridded data across to BokehJS wasting a load of time and resources as it is not used directly there.

So the approach you have for a `GlyphRenderer` is not appropriate or relevant for a `DataRenderer`.

It is easy to do what you want though, via:

```python
contour_renderer = fig.contour(x, y, z, ...)

# Update later on
new_contour_data = contour_data(x, y, z, levels)
contour_renderer.set_data(new_contour_data)
```
 this calculates the new sets of filled and line contours from the new `x`, `y`, `z` data and updates the derived glyphs automagically. This is documented in the Contour Plot section of the User Guide: https://docs.bokeh.org/en/latest/docs/user_guide/topics/contour.html
