### ISSUE TITLE
Update Docs for GlyphRenderer

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#12846]
In the Docs there are some gaps in the section for the GlyphRenderer for `selection_glyph`, `nonselection_glyph` and `muted_glyph`. This makes it difficult to understand all the opportunities offerd by bokeh.

This is related to #12845.

![grafik](https://user-images.githubusercontent.com/68053396/221150743-04655f1a-6c09-4aa7-910b-cc4480faee50.png)

**Comment by mattpap** [comment]
It's an extra `"` in:
```py
selection_glyph = Nullable(Either(Auto, Instance(Glyph)), default="auto", help=""""
```
that causes this.
