### ISSUE TITLE
[FEATURE] custom numerical tick format

### ISSUE THREAD

**Issue by yinyea** [bokeh/bokeh#12862]
### Problem description

I checked NumeralTickFormatter it seems there is not much choice to work with number bps  ( 1bps = 0.01%)  / pips  (1pips = 0.0001). Apparently the alternative way is to either change the data set directly or use "dodge" to adjust the data when plotting but these method are not quite intuitive.

### Feature description

add format in NumeralTickFormatter

Number | Format | String
0.004 | "%%bps" | 40bps
0.0001 | "%%pips" | 1pips

### Potential alternatives

a more dynamic numerical format
for example
Number | Format | String
0.004 | "*.**0 bps" | 40 bps
0.00001 | "*.***0 abc" | 0.1 abc

**Comment by bryevdv** [comment]
Hi @yinyea [`CustomJSTickFormatter`](https://docs.bokeh.org/en/latest/docs/user_guide/styling/plots.html#customjstickformatter) exists for creating custom formats. It provides the ability to create entirely arbitrary tick formats, according to any requirements you have.
