### ISSUE TITLE
[BUG] ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by 2-5** [bokeh/bokeh#12872]
### Software versions

Python version      :  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
IPython version     :  8.10.0
Tornado version     :  6.2
Bokeh version       :  3.0.3
BokehJS static path :  .venv\lib\site-packages\bokeh\server\static
node.js version     :  v18.14.1
npm version         :  9.3.1
Operating system    :  Windows-10-10.0.19045-SP0

### Expected behavior

No warning

### Observed behavior

A `ResourceWarning` is reported by `bokeh serve` due to an `open` call outside a `with` context:

```python
bokeh\application\handlers\directory.py:126: ResourceWarning: unclosed file
<_io.TextIOWrapper name='__init__.py' mode='r' encoding='cp1252'>
```

### Example code

The location of the `ResourceWarning` is https://github.com/bokeh/bokeh/blob/main/src/bokeh/application/handlers/directory.py#L126:

```python
self._package_runner = CodeRunner(open(init_py).read(), init_py, argv)
```

**Comment by bryevdv** [comment]
This is already addressed in WIP PR 

* https://github.com/bokeh/bokeh/pull/12779
