### ISSUE TITLE
[BUG] DatetimeTickFormatter strips leading 0 in "%H" format, works in " %H"

### ISSUE THREAD

**Issue by 2-5** [bokeh/bokeh#12870]
### Software versions

Python version      :  3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
IPython version     :  8.10.0
Tornado version     :  6.2
Bokeh version       :  3.0.3
BokehJS static path :  .venv\lib\site-packages\bokeh\server\static
node.js version     :  v18.14.1
npm version         :  9.3.1
Operating system    :  Windows-10-10.0.19045-SP0

### Expected behavior

"%H" always has 2 digits

### Observed behavior

"%H" doesn't always have 2 digits

### Example code

```Python
from datetime import datetime, timedelta

from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models.formatters import DatetimeTickFormatter

x = [datetime(2023, 1, 1) + timedelta(hours=h) for h in range(25)]
y = list(range(len(x)))

p = figure(x_axis_type="datetime")
p.line(x, y)
p.xaxis.formatter = DatetimeTickFormatter(hours="%H")  # " %H" works
show(p)
```

### Screenshots

`DatetimeTickFormatter(hours="%H")`

![2023-02-28_161327](https://user-images.githubusercontent.com/3753822/221879738-79932cdc-82d8-4549-92c7-db431e233e57.png)

`DatetimeTickFormatter(hours=" %H")` (notice leading space in format string)

![2023-02-28_161338](https://user-images.githubusercontent.com/3753822/221879754-a52fe9ba-6791-4193-9b2e-2e9039657cf6.png)

**Comment by mattpap** [comment]
This is apparently a feature. This works without extra spaces:
```py
p.xaxis.formatter = DatetimeTickFormatter(hours="%H", strip_leading_zeros=False)
```

**Comment by 2-5** [comment]
Thanks. `strip_leading_zeros=True` is a weird default for `DatetimeTickFormatter`, giving that `%H` is specifically documented to use 2 digits and there is `%k` for when you don't want leading zeroes.

**Comment by mattpap** [comment]
This indeed looks like a bug to me, i.e. formatters like `%H` should be respected, as we respect it everywhere else (e.g. in `TimePicker` and `DatetimePicker`).

**Comment by bryevdv** [comment]
Well, `strip_leading_zeros` was not even configurable at all until https://github.com/bokeh/bokeh/pull/12170 when this TODO block was finally done:
```
      // TODO: should expose this in api. %H, %d, etc use leading zeros and
      // users might prefer to see them lined up correctly.
      if (this.strip_leading_zeros) {
```
previously `strip_leading_zeros` was a private attr set to true on views and could not be set by  users at all.

I vaguely recall there was a specific broken case the prompted adding `strip_leading_zeros` codepaths in the first place, but it was something like ten years ago, and I don't remember the details. I agree `%H` should do what it advertises by default.

**Comment by bryevdv** [comment]
Probable cause / possible solution in https://github.com/bokeh/bokeh/issues/13183

**Comment by muendlein** [comment]
@bryevdv I am currently working on a PR for this topic. However I am not entirely sure what the intented behaviour of zero stripping should be. In fact the discussion above shows some rather contradicting statements.

 ```
     // TODO: should expose this in api. %H, %d, etc use leading zeros and
      // users might prefer to see them lined up correctly.
```

> I agree %H should do what it advertises by default.

If formatters should be respected at all times the question is if zero stripping is still necessary (you mentioned a broken case long time ago). On the other hand stripping leading zeros (and with that not obeying to the format) becomes useful in particular for seconds/milliseconds/microseconds formats as something like `000500us` or `002ms` may not look good enough compared with `500us` or `2ms`. 
Moving forward I see the best option in replacing the current general `strip_leading_zeros` property with a resolution dependent stripping of leading zeros (via dict/array property). Please let me know what you think about this idea.
