### ISSUE TITLE
[BUG] Wheel zoom with bounds gets stuck on zoom-out 

### ISSUE THREAD

**Issue by albe-jj** [bokeh/bokeh#12897]
### Software versions

Bokeh version 3.0.3

### Expected behavior

with example below, if I wheel zoom in the bottom right corner and then I wheel zoom out on the center of the plot the zooming out gets stuck. 

### Observed behavior

I guess this is because the wheel zoom tool is zooming equally in all directions but it gets stuck when is limited by the bounds if your plot is not centered at the center of your bounds. However for the user would be nice to be able to zoom out completely with the wheel all the way to the bounds. In that case the zooming out action would also imply a panning to the center of the plot when a bound is hit.

### Example code

```Python
import numpy as np

from bokeh.plotting import figure, show
from bokeh.models import MathML, Range1d, DataRange1d


N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = np.array([ [r, g, 150] for r, g in zip(50 + 2*x, 30 + 2*y) ], dtype="uint8")

TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,examine,help"

p = figure(tools=TOOLS)

p.scatter(x, y, radius=radii,
          fill_color=colors, fill_alpha=0.6,
          line_color=None)

p.x_range.bounds = 'auto'
p.y_range.bounds = 'auto'
# p.y_range = DataRange1d(only_visible=True)

show(p)
```

**Comment by bryevdv** [comment]
This is already possible, but requires a configuration (it is not the default)

https://docs.bokeh.org/en/latest/docs/reference/models/tools.html#bokeh.models.WheelZoomTool.maintain_focus
