### ISSUE TITLE
Remove GeoJSPlot

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1289]
More precisely:
```
ReferenceError: Can't find variable: vec3
    http://opengeoscience.github.io/geojs/lib/geo.js?_=1412857616442: 324
```
Do we really depend on an unspecified version of `geo.js`?

**Comment by bryevdv** [comment]
@pzwang following up on recent OOB discussion, I would actually like to remove `GeoJSPlot`.

**Comment by pzwang** [comment]
OK, can we stick it in an attic or somewhere so we don't completely lose it?

**Comment by bryevdv** [comment]
I've never understood "attics" isn't that what revision history is for?

**Comment by birdsarah** [comment]
@mattpap - glyphs/map.py is now working - but I don't think we're pinned to a specific version of `geo.js` yet. want to close?

**Comment by bryevdv** [comment]
`glyphs/map.py` uses `GMapPlot`
