### ISSUE TITLE
Gallery thumbnails for image examples need updating

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12918]
Examples were streamlined and no longer have a hover tool. 

Currently:

<img width="568" alt="Screenshot 2023-03-07 at 20 02 22" src="https://user-images.githubusercontent.com/1078448/223616653-9961cce3-7461-4ebe-be5b-894ebd6bbda0.png">

**Comment by AnishereMariam** [comment]
Hi @bryevdv, I want to contribute to this issue, and I would love to know that I can ask you for support when I need further help.

**Comment by bryevdv** [comment]
Hi @anisheremariam thank you, however I already opened #12921 to fix this last night, in order to make it in the imminent release.

**Comment by bryevdv** [comment]
As an alternative, most of the new date picker widgets do not have gallery entries yet. I'll open an issue with details later today.

**Comment by AnishereMariam** [comment]
@bryevdv, that's wonderful. I will be on the lookout while I contribute to other issues.
