### ISSUE TITLE
Date picker gallery thumbnail broken 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12919]
@mattpap your date picker PR broke this when you renamed the example file without renaming the associated gallery thumbnails for it. 

<img width="545" alt="Screenshot 2023-03-07 at 20 06 52" src="https://user-images.githubusercontent.com/1078448/223617164-90a8f149-6c54-4d64-9b2e-12c016f8815e.png">

**Comment by mattpap** [comment]
I would expect a build error. Just grepping for `datepicker` is not enough to make a rename.

**Comment by bryevdv** [comment]
not sure why issues are not auto-closing the last few days

@mattpap not possible in full generality, image links can be external so the only place they are ultimately known to be broken *for certain* is when a 404 comes up a browser.
