### ISSUE TITLE
[BUG] Artifacts on the signal when using WebGL to plot

### ISSUE THREAD

**Issue by mloureiro-ilof** [bokeh/bokeh#12913]
### Software versions

Python version      :  3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.31.1
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  C:\Users\iLoF_Admin\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.22621-SP0

### Expected behavior

I am currently plotting several series on a bokeh app and when activating webGL I was expecting that the interactions would be smoother and the loading process quicker.

### Observed behavior

However, when activating this option on the line graph, I get several artifacts that I wasn't expecting. When I zoom in they sometimes disappear but since I am developing a visualization app it's important to ensure accurate plots at all times.
I've tested the same script using two different computers with distinct GPUs:
- NVIDIA GeFroce RTX 4070 Ti where all the prints are from and which seems too suffer the most with the bug
- NVIDIA GeFroce RTX 3050 Laptop GPU where there are less occurrences.

### Example code

```Python
from bokeh.plotting import figure
from bokeh.models import (
LinearColorMapper,
PrintfTickFormatter,
NumeralTickFormatter,
Range1d,
)
from bokeh.plotting import ColumnDataSource, show
import numpy as np
import pickle
import pandas as pd

TOOLS = "hover,save,pan,box_zoom,reset,wheel_zoom"
fig = figure(
    tools=TOOLS,
    title='Example Plot',
    output_backend="webgl"
    )

with open('data_20230307_141532.pkl', 'rb') as file:
    # Call load method to deserialze
    mock_data = pickle.load(file)

source = ColumnDataSource(data=mock_data)
                                
fig.line(
        x='freq',
        y='time',
        source=source,
        line_width=2,
)
fig.yaxis.formatter = PrintfTickFormatter(format="%.2e")
show(fig)
```

### Screenshots

![example](https://user-images.githubusercontent.com/87646763/223417612-5aa72797-b977-4505-b919-261c84f92dc0.png)
![when mouse if over a signal](https://user-images.githubusercontent.com/87646763/223417711-0628ebb3-5fe2-4e88-be14-0c596649b1d6.png)
![when mouser is on artifacts (no signal)](https://user-images.githubusercontent.com/87646763/223417780-8a27cc51-9d94-4101-a861-169e30f6a93a.png)

![example1 on code given](https://user-images.githubusercontent.com/87646763/223451014-6fbd8fb7-f73f-4b22-b1d2-8c76ec1ad238.png)
![example2 on code given](https://user-images.githubusercontent.com/87646763/223451054-5ada1883-ced6-4bb9-88ba-45f9789bb8ba.png)

**Comment by bryevdv** [comment]
Hi @mloureiro-ilof thanks for the issue. Please try with latest version 3.0.3 or version 3.1 (hopefully available tomorrow) and report back. There has been much work on webgl since 2.4.3 so any issue may already be fixed. cc @ianthomas23

**Comment by mloureiro-ilof** [comment]
Yes, sorry you are right. However, the problem still remains with the most updated version
![bokeh_plot](https://user-images.githubusercontent.com/87646763/223507604-916ba8ae-682a-47f3-9b87-12b7cf15af03.png)

**Comment by ianthomas23** [comment]
@mloureiro-ilof Can you upload your data somewhere so that we can access it and reproduce the problem?

**Comment by mloureiro-ilof** [comment]
[data_20230307_141532.zip](https://github.com/bokeh/bokeh/files/10919549/data_20230307_141532.zip)
there you go!

**Comment by ianthomas23** [comment]
Thanks!

I can reproduce the problem, it is definitely a bug.

**Comment by ianthomas23** [comment]
Thanks for reporting this @mloureiro-ilof, I should have a fix for it soon.

**Comment by mloureiro-ilof** [comment]
awesome, thanks! will be waiting for news

**Comment by ianthomas23** [comment]
Here is a simpler reproducer:
```python
from bokeh.plotting import figure, row, show
import numpy as np

x = np.linspace(89.1, 89.4, 5)
y = [-127.79500669, -124.78311195, -128.10880922, -127.0787, -180]

ps = []
for backend in ['canvas', 'webgl']:
    p = figure(width=600, height=600, output_backend=backend, title=backend,
               x_range = (-15000, 15000), y_range = (-200, -80))
    p.line(x=x, y=y, line_width=50, line_join="round")
    ps.append(p)

show(row(ps))
```
![webgl](https://user-images.githubusercontent.com/580326/228346118-2ba71cf8-fca2-49f1-b8e8-bef4d54d459f.png)

Spot the difference :astonished:

Because this is related to floating-point precision it is quite difficult to reproduce. Slight differences in coordinates, canvas size, ranges, etc cause the problem to disappear. But this code is a reliable reproducer on my Linux dev system (Quadro T1000) on chromium 111.0.5563.110 but not firefox.
