### ISSUE TITLE
Thumbnails not being rendered in docs gallery

### ISSUE THREAD

**Issue by chinmaychahar** [bokeh/bokeh#12924]
### Software versions

Python version      :  3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.31.1
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  C:\Users\Chinmay\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  v16.17.0
npm version         :  8.19.2
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Brave Version 1.48.171

### Expected behavior

Normally rendered thumbnails for all live demos under 'Bokeh Server' at https://docs.bokeh.org/en/latest/docs/gallery.html

### Observed behavior

The thumbnails in this section link for live demos of 'movies' & 'gapminder' are not being rendered and alt text is being displayed

### Example code

```Python
NA
```

### Screenshots

![Capture](https://user-images.githubusercontent.com/56752925/223645472-66305c0f-d7fc-48f5-ae4e-42a08246906f.PNG)
![Capture -2](https://user-images.githubusercontent.com/56752925/223645513-3b94abf1-f733-4a60-8656-490676bbdfdc.PNG)

**Comment by bryevdv** [comment]
Hi @chinmaychahar they are all rendering for me: 

<img width="1497" alt="Screenshot 2023-03-08 at 07 48 08" src="https://user-images.githubusercontent.com/1078448/223761040-694efd98-dde8-4922-956e-ec988eec32d6.png">

Can you check with other browsers, etc or try a page force reload?

**Comment by chinmaychahar** [comment]
@bryevdv tried on Chrome as well and did force reload too. Can it be a cache issue?
![Capture](https://user-images.githubusercontent.com/56752925/223763950-dd57ef61-453a-482e-9af0-d6085b3a1cae.PNG)

**Comment by bryevdv** [comment]
@chinmaychahar I am afraid I am not really sure, is there a network loading tab you can look at or post that shows the actual URLs that are failing to load? (Edit: and what the error is.... I would assume 404s but good to verify)

**Comment by mattpap** [comment]
I can see this as well for `movies` and `gapminder` both in 3.0 and 3.1-dev docs. There are errors in JS console:
![image](https://user-images.githubusercontent.com/27475/223784526-a1db6c63-74de-4e95-ba17-e52dd03a17c3.png)

**Comment by mattpap** [comment]
Perhaps those `... 2.png` files are the reason:
```sh
$ git ls-files | grep -P '(movies|gapminder).*\.png'
docs/bokeh/source/_images/examples/server/app/gapminder@2x 2.png
docs/bokeh/source/_images/examples/server/app/gapminder@2x.png
docs/bokeh/source/_images/examples/server/app/movies@2x 2.png
docs/bokeh/source/_images/examples/server/app/movies@2x.png
```

**Comment by bryevdv** [comment]
Yes that's almost certainly it. I am not sure why it's working for me

**Comment by chinmaychahar** [comment]
It works for me as well if I open the doc on my mobile but doesn't work on the browser. Not sure why

**Comment by mattpap** [comment]
> I am not sure why it's working for me.

This is because you're using a macbook with a retina display (as far I can tell), so you're getting 2x image variants. It works for me as well on my devices with high density displays.

**Comment by bryevdv** [comment]
Thanks for the catch @chinmaychahar
