### ISSUE TITLE
Verify SRI hashes failing on release build

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12934]
Fails with: 
>     SRI hashes for BokehJS files could not be verified: There are 'bokeh*.js' files missing in the package
which means that there are more hashes recorded in `_sri.json` than there are `bokeh*.js` files in the package. 

This is what appears to be what is *in the package*:
```
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-api.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-api.min.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-gl.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-gl.min.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-mathjax.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-mathjax.min.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-tables.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-tables.min.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-widgets.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh-widgets.min.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh.js
    bokeh-3.1.0/src/bokeh/server/static/js/bokeh.min.js
```
But an `ls` of a local dev dir shows more:
```
❯ ls src/bokeh/server/static/js/bokeh*.js
src/bokeh/server/static/js/bokeh-api.esm.js      src/bokeh/server/static/js/bokeh-mathjax.esm.js      src/bokeh/server/static/js/bokeh-widgets.esm.js
src/bokeh/server/static/js/bokeh-api.esm.min.js  src/bokeh/server/static/js/bokeh-mathjax.esm.min.js  src/bokeh/server/static/js/bokeh-widgets.esm.min.js
src/bokeh/server/static/js/bokeh-api.js          src/bokeh/server/static/js/bokeh-mathjax.js          src/bokeh/server/static/js/bokeh-widgets.js
src/bokeh/server/static/js/bokeh-api.min.js      src/bokeh/server/static/js/bokeh-mathjax.min.js      src/bokeh/server/static/js/bokeh-widgets.min.js
src/bokeh/server/static/js/bokeh-gl.esm.js       src/bokeh/server/static/js/bokeh-tables.esm.js       src/bokeh/server/static/js/bokeh.esm.js
src/bokeh/server/static/js/bokeh-gl.esm.min.js   src/bokeh/server/static/js/bokeh-tables.esm.min.js   src/bokeh/server/static/js/bokeh.esm.min.js
src/bokeh/server/static/js/bokeh-gl.js           src/bokeh/server/static/js/bokeh-tables.js           src/bokeh/server/static/js/bokeh.js
src/bokeh/server/static/js/bokeh-gl.min.js       src/bokeh/server/static/js/bokeh-tables.min.js       src/bokeh/server/static/js/bokeh.min.js
```

I'm not 100% sure yet, but I suspect that hashes were recorded for from the build dir [1], and so that included hashes for the `*.esm.*` files too. If so there are two options, depending on the answer to the question:

* should the `*esm*` files be included in the the package, or not? 

If so, we probably need to adjust the manifest. If not, we need to adjust `sri.py` to exclude esm files. 

cc @mattpap 

[1] in order to include the hashes *in the package*, they necessarily must be computed before the package is built.

**Comment by mattpap** [comment]
> should the *esm* files be included in the the package, or not?

No. They generated by bokehjs' build, but only for internal development and testing. They are not accessible by resources and they should have never been part of bokeh package. I removed them from the package in PR #12635.

**Comment by mattpap** [comment]
Probably `setup.py` needs to be updated to be more selective at copying files (copy exactly what the manifest expects).

**Comment by bryevdv** [comment]
@mattpap AFAICT the esm files are (correctly) not inside the built package. The issues is that the SRI hashes are generated off the built source tree and use a glob that not selective enough. Hashes for the ESM files get added to `_sri.json` and then later when the built package runs `verify_hashes` it complains that there are more hashes than are expected. (I am 99% sure this is what is happening). So the `scripts/sri.py` probably just needs to be updated to be more selective. I will have to look at that tonight when I have time, unless someone else wants to make a stab sooner.

**Comment by bryevdv** [comment]
I pushed https://github.com/bokeh/bokeh/commit/c402468fc51f04d30da242275156978fe54ad90f directly to `branch-3.1` if the release build succeeds, it will need to be cherry picked to `branch-3.2`

**Comment by bryevdv** [comment]
That was the issue, release build for 3.1 did succeed. 

@mattpap tangential question: the ESM files are also being uploaded to CDN:
```
:uploading to CDN: bokeh/release/bokeh-mathjax-3.1.0.esm.min.js
:uploading to CDN: bokeh/release/bokeh-mathjax-3.1.0.esm.min.js
```
is that also unnecessary?

**Comment by mattpap** [comment]
It's unnecessary, because they are not accessible through resources. One would have to add them manually to a template, and for that one can use unpkg or jsdelivr CDNs.

**Comment by bryevdv** [comment]
OK I will remove them manually at some point and make an issue to update the automation for the next release.
