### ISSUE TITLE
[FEATURE] Update ruff to include W291 (trailing whitespace)

### ISSUE THREAD

**Issue by benrussell80** [bokeh/bokeh#12936]
### Problem description

The check for trailing whitespace is currently "home-grown" (https://github.com/bokeh/bokeh/blob/branch-3.2/tests/codebase/test_code_quality.py#L103).

This check is a pet peeve of mine when contributing because I can never tell that there is trailing whitespace until I go to push and I get stopped by the hooks. I would have to run a rather verbose pytest command to catch myself. However, I am much happier running `ruff .` more frequently because it is terse and fast.

### Feature description

Ruff supports rule W291 from flake8 (https://beta.ruff.rs/docs/rules/#warning-w). This is not supported in the current dependent version (0.0.252) but is supported in 0.0.254.

Updating ruff version and removing this check as long as W291 accounts for the same things that the test does.

There are also other types of checks in W* that are similar to the homegrown codebase checks.

### Potential alternatives

I don't see a problem updating ruff version but the existing check may account for cases that the W checks don't.

**Comment by bryevdv** [comment]
I think adding the ruff rule for quick feedback on commit is fine, but we would still need to keep the home-grown check at the same time. At least, I assume the ruff check only applies to python files, whereas the home-grown check applies to every file type in the repo. 

> stopped by the hooks.

The hooks are definitely optional. I find them valuable for dev, but they can be locally reconfigured or omitted entirely as desired

**Comment by benrussell80** [comment]
Got it, I didn't know that those checked non-python files as well. I haven't done much contributing to non-python files so I didn't realize that.

Just adding that I think the hooks are great; they keep me from pushing code that is just going to fail in CI.

**Comment by mattpap** [comment]
bokehjs already has training whitespace and other stylistic rules enabled in its linter, so doing the same in ruff seems quite natural to me. If you want those issues to be pointed out in your IDE, then this is the way to do it. We can leave the custom style check for files that can't be managed by linters.

**Comment by mattpap** [comment]
This now works:
```diff
$ git diff
diff --git a/src/bokeh/__init__.py b/src/bokeh/__init__.py
index c229f6d4c7..535fa295f4 100644
--- a/src/bokeh/__init__.py
+++ b/src/bokeh/__init__.py
@@ -31,7 +31,7 @@ attributes:
 #-----------------------------------------------------------------------------
 # Boilerplate
 #-----------------------------------------------------------------------------
-from __future__ import annotations
+from __future__ import annotations                    
 
 import logging # isort:skip
 log = logging.getLogger(__name__)
```
Running tests:
```
$ pytest tests/codebase/test_ruff.py
```
gives:
```
    def test_ruff() -> None:
        chdir(TOP_PATH)
        proc = run(["ruff", "."], capture_output=True)
>       assert proc.returncode == 0, f"ruff issues:\n{proc.stdout.decode('utf-8')}"
E       AssertionError: ruff issues:
E         src/bokeh/__init__.py:34:35: W291 [*] Trailing whitespace
E         Found 1 error.
E         [*] 1 potentially fixable with the --fix option.
E         
E       assert 1 == 0
E        +  where 1 = CompletedProcess(args=['ruff', '.'], returncode=1, stdout=b'src/bokeh/__init__.py:34:35: W291 [*] Trailing whitespace\nFound 1 error.\n[*] 1 potentially fixable with the --fix option.\n', stderr=b'').returncode

tests/codebase/test_ruff.py:34: AssertionError
```
