### ISSUE TITLE
Don't upload ESM files to CDN

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12941]
Current release automation is overzealous and uploads ESM files, but this is not necessary. ESM uploads from previous releases could be manually deleted from CDN.

**Comment by bryevdv** [comment]
@mattpap you explicitly added code to make it so that ESM bundles are uploaded to CDN in this PR:

* https://github.com/bokeh/bokeh/pull/10730

Specifically [here](https://github.com/bokeh/bokeh/pull/10730/files#diff-9b99dd68c841d09e2dd782c022cef39fd4a46cc0856b6ff761783e680fb047ecR62). I just want to double-check that you want that particular change reverted?

**Comment by mattpap** [comment]
I think was too eager with that change, but let me think about this, before we put any work into removing them and making other changes.

**Comment by bryevdv** [comment]
@mattpap This can be closed correct? based on https://github.com/bokeh/bokeh/pull/13488#issuecomment-1781346228 and work in that PR
