### ISSUE TITLE
[BUG] DataTable and autosize_mode="fit_columns" sometimes table do not render (row is not defined)

### ISSUE THREAD

**Issue by Shadoward** [bokeh/bokeh#12948]
### Software versions

Python version      :  3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  .\lib\site-packages\bokeh\server\static
node.js version     :  v18.12.1
npm version         :  8.19.2
Operating system    :  Windows-10-10.0.19045-SP0

Pandas version      :  1.5.3
Tables version      :  3.8.0

### Expected behavior

The DataTable should render regardless of the autosize_mode option, displaying all the data in the table.

### Observed behavior

When using the autosize_mode="fit_columns" option in the Bokeh DataTable, the table does not render in some cases. This behavior seems to be inconsistent and depends on the content of the table. No pattern has been identified that consistently reproduces the issue.

### Example code

```Python
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn
import pandas as pd
from bokeh.layouts import layout
from bokeh.io import output_file, show

##### This does not work #####
output_file("table.html")
data = dict(
        a=[1, 3],
        b=[134, 134],
        c=['fs', 'f'],
        d=['sd', 'f'],
    )
df = pd.DataFrame(data)
columns = [
            TableColumn(field=Ci, title=Ci, width=1) for Ci in df.columns
        ]

table = DataTable(
    columns=columns,
    source=ColumnDataSource(df),
    index_position=None,
    autosize_mode="fit_columns",
)

layout_table = layout(table, sizing_mode="stretch_width")
show(layout_table)


#### This work #####
output_file("table2.html")
data2 = dict(
        a=[1, 2, 3, 4, 5, 7, 78, 4],
        b=[6, 7, 8, 9, 10, 4, 78, 4],
        c=[6, 7, 8, 9, 10, "hgj", "hgj", "hgjghj"],
        d=[6, 7, 8, 9, 10, "hgj", "hgj", "hgjghj"],
    )
df2 = pd.DataFrame(data2)
columns2 = [
            TableColumn(field=Ci2, title=Ci2, width=1) for Ci2 in df2.columns
        ]
table2 = DataTable(
    columns=columns2,
    source=ColumnDataSource(df2),
    index_position=None,
    autosize_mode="fit_columns",
)

layout_table2 = layout(table2, sizing_mode="stretch_width")
show(layout_table2)
```

### Screenshots

![image](https://user-images.githubusercontent.com/15196061/224525398-dbfe4178-11e6-4cfa-9e2e-9f72a7b50b1e.png)

**Comment by Shadoward** [comment]
When the table row contains only strings and the option "fit_viewport" or "fit_columns" the table doesn't render. 
However, if the row includes a combination of letters and numbers, the issue doesn't occur.

**Comment by mosc9575** [comment]
I close this as duplicate. The later incoming issue #13460 addresses the same problem but has already a milestone.
