### ISSUE TITLE
[BUG] mypy / static typing error on bokeh.models imports

### ISSUE THREAD

**Issue by andyschuster** [bokeh/bokeh#12960]
### Software versions

Python version      :  3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.11.0
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  venv\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.22621-SP0

### Expected behavior

mypy should not produce an error with simple bokeh.models imports like the following code:
`from bokeh.models import BoxAnnotation`

### Observed behavior

However starting in bokeh version 3.0 (also tested in 3.1.0) mypy will report:
`Module "bokeh.models" has no attribute "BoxAnnotation"  [attr-defined]`

This was not the casse with prior 2.x versions including the last Bokeh 2.4.3.

### Example code

```Python
from bokeh.models import BoxAnnotation

# also occurs with other bokeh.models imports:
from bokeh.models import Label
from bokeh.models import LabelSet
# etc...
```

### Stack traceback or browser console output

mypy version: 1.1.1 (latest)

**Comment by bryevdv** [comment]
@andyschuster there is nothing magical going on, all Bokeh models are transitively imported into top-level `bokeh.models` in a standard way, and you can just import the module and look in it yourself to confirm. We also run mypy on every push to GitGub and many people also have it run as a pre-commit hook, without issue. Can you investigate if there is possibly some configuration on your end that is causing problems?  

Edit: or mypy version variation is also worth checking.

**Comment by bryevdv** [comment]
The only other thing that comes to mind is that top-level `__all__` is computed, by concatenating the submodule `__all__` values. Listing things manually is fragile and error-prone so we would not want to change that.

**Comment by mattpap** [comment]
Having a file like this:
```py
from bokeh.models import BoxAnnotation
from bokeh.io import show
box = BoxAnnotation()
show(box)
```
will produce:
```
foo.py:1: error: Module "bokeh.models" has no attribute "BoxAnnotation"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```
This is because mypy doesn't understand `__all__`. There are multiple issues open for that in mypy's issue tracker. My only suggestion for now, is to use full imports if you want to get static typing with bokeh's models. However, bokeh model's constructors and properties aren't statically typed at this point, because it's not possible without creating an extension or writing type declarations manually, so your overall experience will be lackluster.

**Comment by bryevdv** [comment]
Right for good measure here is most relevant ref:

* https://github.com/python/mypy/issues/12582

I would support closing this as `upstream`

**Comment by bryevdv** [comment]
Actually it looks as tho *some* `__all__` expressions may be statically usable, e.g with `+=` so perhaps we can try arranging our computation differently in case that would help.

**Comment by bryevdv** [comment]
Unfortunately changing to use `__all__ += ` did not help. Apparently `pyright` supports this, but handling expressions involving `submodule.__all__` is still an open issue for `mypy`. So I'm back to proposing closing this as `upstream`.

**Comment by bryevdv** [comment]
@andyschuster sorry there is not a better immediate solution for you, hopefully `mypy` will implement the proposed solution for better static "const" value  evaluation some day.

**Comment by andyschuster** [comment]
Thanks for investigating. Is the way `__all__` gets manipulated something that changed since mypy worked fine with the 2.x version of bokeh?

**Comment by bryevdv** [comment]
@andyschuster Yes, the list used to be constructed manually, and was frequently wrong / incomplete as a result.

**Comment by andyschuster** [comment]
Got it. I guess it is time for `# type: ignore` then until either mypy or bokeh change.
