### ISSUE TITLE
[BUG] Update color_scatter.py #12966

### ISSUE THREAD

**Issue by Isaakkamau** [bokeh/bokeh#12965]
### Software versions

Python version      :  3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.1.1
Tornado version     :  6.1
Bokeh version       :  3.0.3
BokehJS static path :  C:\Users\Isaac\AppData\Local\Programs\Python\Python310\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19045-SP0

### Browser name and version

Chrome

### Jupyter notebook / Jupyter Lab version

Jupyter notebook

### Expected behavior

I expected to have a scatter plot by running this code https://docs.bokeh.org/en/latest/docs/examples/basic/scatters/color_scatter.html

### Observed behavior

The code is raising a Value  Error:
 ```ValueError: unexpected tool name 'examine', possible tools are pan, xpan, ypan, xwheel_pan, ywheel_pan, wheel_zoom, xwheel_zoom, ywheel_zoom, zoom_in, xzoom_in, yzoom_in, zoom_out, xzoom_out, yzoom_out, click, tap, doubletap, crosshair, box_select, xbox_select, ybox_select, poly_select, lasso_select, box_zoom, xbox_zoom, ybox_zoom, save, undo, redo, reset, help, box_edit, line_edit, point_draw, poly_draw, poly_edit, freehand_draw or hover```

### Example code

```Python
import numpy as np

from bokeh.plotting import figure, show

N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = np.array([(r, g, 150) for r, g in zip(50+2*x, 30+2*y)], dtype="uint8")

TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,examine,help"

p = figure(tools=TOOLS)

p.scatter(x, y, radius=radii,
          fill_color=colors, fill_alpha=0.6,
          line_color=None)
```

**Comment by mattpap** [comment]
> Bokeh version : 3.0.3

Are you sure this is the version of bokeh that this code is run with? Examine tool was added in Bokeh 3.0, so this code should work just fine. If unsure, add this `import bokeh; print(bokeh.__version__)` to the example and re-run. It's a fairly common issue when using multiple virtual environments.

**Comment by Isaakkamau** [comment]
Hello, @mattpap sorry for that, My bokeh version is `2.4.3` I think that was the reason. Thank you!
