### ISSUE TITLE
Broken link on Bokeh PyPI page 

### ISSUE THREAD

**Issue by chinmaychahar** [bokeh/bokeh#12972]
### Software versions

Python version      :  3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.31.1
Tornado version     :  6.1
Bokeh version       :  3.1.0
BokehJS static path :  C:\Users\Chinmay\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  v16.17.0
npm version         :  8.19.2
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Brave Version 1.48.171

### Expected behavior

The PyPI project description should render the GitHub README normally. [link](https://pypi.org/project/bokeh/)

### Observed behavior

I think using `  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/bokeh/pm/main/assets/logos/SVG/bokeh-logo-white-text-no-padding.svg">
`  for rendering the correct logo according to the theme works on GitHub but the same causes rendering issues on the PyPI page. There should ideally be some work around

### Example code

```Python
N/A
```

### Screenshots

Concerned bug - 
![pypi_bokeh](https://user-images.githubusercontent.com/56752925/225562036-e64d455d-c4b8-429b-8fec-8630facdbe03.PNG)

**Comment by chinmaychahar** [comment]
cc @bryevdv @pavithraes

**Comment by ianthomas23** [comment]
This is a known limitation of PyPI, it does not understand the `<picture>` tag that is used to support both dark and light mode on the same page.

**Comment by bryevdv** [comment]
All things being equal, I would prioritize having it look good on GitHub, and hopefully PyPI will catch up someday.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this `noaction` if there is some way discovered that will allow a for better presentation on PyPI while still affording light/dark mode support on GH, please feel free to re-open.
