### ISSUE TITLE
[BUG] LINK NOT ACCESIBLE

### ISSUE THREAD

**Issue by Ajoke23** [bokeh/bokeh#12985]
@bryevdv @pavithraes 
### Software versions

Python version      :  3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.5.0
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  C:\Users\user\AppData\Roaming\Python\Python310\site-packages\bokeh\server\static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Browser Name: Microsoft Edge, Version: Version 110.0.1587.50 (Official build) (64-bit)

### Expected behavior

I expected the link that will take me to an accessible page

### Observed behavior

![marker map](https://user-images.githubusercontent.com/71567200/226118919-9a938431-b6da-4905-b79a-92018383a8a1.PNG)

I got "This Page does not Exist". It seems the link got broken

### Example code

```Python
https://docs.bokeh.org/en/latest/docs/gallery/marker_map.html
```

**Comment by Soot3** [comment]
the marker_map example got renamed or switched so it should be this instead in the latest docs.

https://docs.bokeh.org/en/latest/docs/examples/basic/data/transform_markers.html

**Comment by bryevdv** [comment]
Hi @Ajoke23 where did you come across the link? As @Soot3 mentions, the location of the link changed recently when the docs were restructured.

**Comment by bryevdv** [comment]
I am going to go ahead and close this. I don't believe the latest docs *themselves* link to this anywhere, I expect it is on old link to "latest" that somewhere else that is now out of date after the move, but there is nothing we can do about that. I f this is mistaken and current latest docs have this internally somewhere, we can re-open.
