### ISSUE TITLE
[FEATURE] Graph update during running callback function

### ISSUE THREAD

**Issue by yinyea** [bokeh/bokeh#13004]
### Problem description

i have a callback function which will run around 10-20seconds+ (FYI it s a machine learning to it runs around 10k times to optimize the figure)
currently when we run bokeh server the graph will only be updated after the callback function finished

### Feature description

a function that can release or force the graph to update during the callback function such as "callback.flush()"

### Potential alternatives

another type of "add_periodic_callback" that wont stop the bokeh server updating graph

**Comment by bryevdv** [comment]
@yinyea you need to elaborate on what you are asking for. It's not clear to me what you expect to happen during the 10-20 seconds that the function runs. Are you saying you have access to some intermediate results, and want to update the plot along the way? Or something else? It's always good to propose even some rough psuedo-code to outline what you are aksing for, and to focus the discussion. 

Lastly, can you confirm that you have tried to apply the techniques described here:

https://docs.bokeh.org/en/latest/docs/user_guide/server/app.html#updating-from-threads

And if so, please be specific about how they did not meet needs.

**Comment by bryevdv** [comment]
Closing for lack of response. We can consider re-opening if/when additional information is provided.
