### ISSUE TITLE
Code Error in the First Steps guide [BUG] 

### ISSUE THREAD

**Issue by Azaya89** [bokeh/bokeh#13011]
### Software versions

Python version      :  3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.11.0
Tornado version     :  6.2
Bokeh version       :  3.1.0rc1+33.g3ace356b
BokehJS static path :  C:\Users\SimpcyClassy\Desktop\Outreachy_Bokeh_Project\bokeh\src\bokeh\server\static
node.js version     :  v18.15.0
npm version         :  8.19.4
Operating system    :  Windows-10-10.0.22621-SP0

### Expected behavior

I expect the code at docs/first_steps/examples/first_steps_8_filter.py to run successfully. This is the code reproduced [here](https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_8.html)

### Observed behavior

When I run the code, it shows a traceback error: 
"AttributeError: unexpected attribute 'filter' to CDSView, similar attributes are filters" 
referencing line 9 of the code. 

When I change the attribute to `filters`, it still shows another traceback error: 
"ValueError: failed to validate CDSView(id='2808', ...).filters: expected an element of List(Instance(Filter)), got IndexFilter(id='2807', ...)"

### Example code

```Python
from bokeh.layouts import gridplot
from bokeh.models import CDSView, ColumnDataSource, IndexFilter
from bokeh.plotting import figure, show

# create ColumnDataSource from a dict
source = ColumnDataSource(data=dict(x=[1, 2, 3, 4, 5], y=[1, 2, 3, 4, 5]))

# create a view using an IndexFilter with the index positions [0, 2, 4]
view = CDSView(filter=IndexFilter([0, 2, 4]))

# setup tools
tools = ["box_select", "hover", "reset"]

# create a first plot with all data in the ColumnDataSource
p = figure(height=300, width=300, tools=tools)
p.circle(x="x", y="y", size=10, hover_color="red", source=source)

# create a second plot with a subset of ColumnDataSource, based on view
p_filtered = figure(height=300, width=300, tools=tools)
p_filtered.circle(x="x", y="y", size=10, hover_color="red", source=source, view=view)

# show both plots next to each other in a gridplot layout
show(gridplot([[p, p_filtered]]))
```

### Stack traceback or browser console output

AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10460\1683818812.py in <module>
      7 
      8 # create a view using an IndexFilter with the index positions [0, 2, 4]
----> 9 view = CDSView(filter=IndexFilter([0, 2, 4]))
     10 
     11 # setup tools

~\anaconda3\lib\site-packages\bokeh\model\model.py in __init__(self, **kwargs)
    126         kwargs.pop("id", None)
    127 
--> 128         super().__init__(**kwargs)
    129         default_theme.apply_to_model(self)
    130 

~\anaconda3\lib\site-packages\bokeh\core\has_props.py in __init__(self, **properties)
    204 
    205         for name, value in properties.items():
--> 206             setattr(self, name, value)
    207 
    208         self._initialized = True

~\anaconda3\lib\site-packages\bokeh\core\has_props.py in __setattr__(self, name, value)
    234             return super().__setattr__(name, value)
    235 
--> 236         self._raise_attribute_error_with_matches(name, properties)
    237 
    238     def __getattr__(self, name: str) -> Unknown:

~\anaconda3\lib\site-packages\bokeh\core\has_props.py in _raise_attribute_error_with_matches(self, name, properties)
    270             matches, text = sorted(properties), "possible"
    271 
--> 272         raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
    273 
    274     def __str__(self) -> str:

AttributeError: unexpected attribute 'filter' to CDSView, similar attributes are filters

**Comment by bryevdv** [comment]
@Azaya89 can you print the version inside from inside the script? I think you must be running the script with an older version of Bokeh. There was a change at Bokeh 3.0 that renamed the property to `filter` (it was `filters` previously in earlier versions). But also, in the docs, all the plots are actually generated using the same code, so if the code was broken, the plot in the docs would also have to be broken (but it is working at that link)

**Comment by Azaya89** [comment]
@bryevdv OK, so I normally run all the codes on my Jupyter notebook but like you suggested, I opened it via my dev environment on conda (where the Bokeh version is 3.1) and it ran successfully. That said, it appears the bokeh I access on my Jupyter notebook is an older version then. How do I upgrade it to the latest version?

**Comment by bryevdv** [comment]
@Azaya89 The best solution is probably the converse: install the notebook in the dev environment. I'd probably just run `pip install  notebook` (or `pip install jupyterlab`) if you are using that. Then when you run the notebook, it will be from the same dev env.

I will go ahead and close this issue (ping me on slack with any update / install issues)
