### ISSUE TITLE
Setup instructions contain a formatting error[BUG] 

### ISSUE THREAD

**Issue by Azaya89** [bokeh/bokeh#13033]
### Software versions

Python version      :  3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
IPython version     :  8.11.0
Tornado version     :  6.2
Bokeh version       :  3.1.0rc1+45.g46449c08
BokehJS static path :  C:\Users\SimpcyClassy\Desktop\Outreachy_Bokeh_Project\bokeh\src\bokeh\server\static
node.js version     :  v18.15.0

### Expected behavior

The Instructions on the setup page [here](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html), specifically **2. FORK AND CLONE THE REPOSITORY**  is supposed to show the correct formatting in the HTTPS side.

### Observed behavior

It doesn't show the correct formatting. The SSH tab shows the easily copied formatting but the HTTPS side does not. It can make it easy to confuse someone who is reading it for the first time.

### Example code

```Python
This is a documentation issue.
```

### Screenshots

SSH side:

![image](https://user-images.githubusercontent.com/99359668/227772001-b9d5636d-84d1-4585-8795-cd731fadbaab.png)

HTTPS side:

![image](https://user-images.githubusercontent.com/99359668/227772019-c2a91e05-3aca-4ea9-b991-a3ed30b10b36.png)

**Comment by ianthomas23** [comment]
This has already been fixed by #12973.
