### ISSUE TITLE
Split Bokeh object up into separate namespaces. 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1304]
The `Bokeh` object in BokehJS has grown very large. It should be partitioned into relevant groups, e.g,:

* `Bokeh.core`
* `Bokeh.renderer`
* `Bokeh.tool`
* `Bokeh.widget`
* `Bokeh.transform`

This split should apply to `Collections` as well. I think this is probably a necessary first step before contemplating splitting BokehJS up into separate modules.

**Comment by mistakevin** [comment]
@mattpap How is this going? Is there any work you want me to prototype or investigate?

**Comment by bryevdv** [comment]
ping @mattpap current TS API work makes this irrelevant?

**Comment by bryevdv** [comment]
Actually, I will state that I think it does, and close (please re-open if there is a different understanding)
