### ISSUE TITLE
Tick lines are not visible using `dark_minimal`, `night_sky` or `contrast` theme

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13048]
### Expected behavior

I expected that major and minor tick lines are always visible by default.

### Observed behavior

I have observed that the major and minor tick lines are not visible if some [themes](https://docs.bokeh.org/en/latest/docs/user_guide/styling/themes.html) are applied.

See
* [`dark_minimal`](https://docs.bokeh.org/en/latest/docs/examples/styling/themes/dark_minimal.html)
* [`night_sky`](https://docs.bokeh.org/en/latest/docs/examples/styling/themes/night_sky.html)
* [`contrast`](https://docs.bokeh.org/en/latest/docs/examples/styling/themes/contrast.html)

In the themes these colors are set properly, but for some reason they are not visiable in the created figure.

### Example code

```Python
from bokeh.plotting import curdoc, figure, show

x = [1, 2, 3, 4, 5]
y = [6, 7, 6, 4, 5]

curdoc().theme = 'contrast'

p = figure(title='contrast', width=300, height=300)
p.line(x, y)

show(p)
```

### Screenshots

![Contrast](https://user-images.githubusercontent.com/68053396/229453930-6744355a-2e6e-43ce-99c6-5b8f30dbddf5.PNG)

<details>
  <summary>technical details</summary>

   ### Software versions
    Python version      :  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
    IPython version     :  8.4.0
    Tornado version     :  6.1
    Bokeh version       :  2.4.3
    BokehJS static path :  /opt/conda/envs/aiva-env/lib/python3.9/site-packages/bokeh/server/static
    node.js version     :  v17.4.0
    npm version         :  8.3.1
    Operating system    :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.31
    
   ### Browser name and version
    Chrome 111.0.5563.147 (Offizieller Build) (64-Bit)

</details>

**Comment by bryevdv** [comment]
@mosc9575 All of those themes explicitly set 
```
            "major_tick_line_alpha": 0,
            "minor_tick_line_alpha": 0,
```
so as far as I know this is the intended and desired visual effect (some people consider them "clutter")

**Comment by mosc9575** [comment]
Sorry I overread the alpha value. I am not sure if this is the best default value but I don't want to discuss it any further because I thought there is a bug in the first place. The alpha value can be easily changed by user. Thanks @bryevdv you your feedback.
