### ISSUE TITLE
[FEATURE] Set `Cross-Origin-Resource-Policy: cross-origin`

### ISSUE THREAD

**Issue by hoodmane** [bokeh/bokeh#13053]
### Problem description

We're working on PyScript in a worker. Currently we're using the SharedArrayBuffer + Atomics approach which requires us to set `Cross-Origin-Embedder-Policy: require-corp`. This makes it so we can only make cross origin requests if they set  `Cross-Origin-Resource-Policy: cross-origin`.

Could you set  `Cross-Origin-Resource-Policy: cross-origin` on all responses from `cdn.bokeh.org`?

**Comment by hoodmane** [comment]
Note that jsdelivr sets this header on their responses:

<details>
<summary>jsdelivr response screenshot</summary>


![Screenshot from 2023-04-04 11-09-13](https://user-images.githubusercontent.com/8739626/229880558-b723299f-1f23-4924-a818-0f70c38fe551.png)



</details>

**Comment by mattpap** [comment]
Given we serve only static resources from the CDN, this should be safe to do. I run into a similar issue before, when working on bokehjs, and it was much easier to redirect requests to jsdelivr (or similar), than using our CDN.

**Comment by bryevdv** [comment]
I'll try to take a look at the AWS configuration tonight.

**Comment by bryevdv** [comment]
I believe this is done, please confirm 
```
dev-311 ❯ curl -H "origin: example.com" -s -I -X GET  https://cdn.bokeh.org/bokeh/release/bokeh-3.1.0.min.js
HTTP/2 200
content-type: application/javascript
content-length: 942224
date: Tue, 04 Apr 2023 23:07:50 GMT
last-modified: Thu, 09 Mar 2023 23:51:35 GMT
etag: "4c85194184648620b8604a2f02c15b3d"
x-amz-server-side-encryption: AES256
cache-control: max-age=31536000
x-amz-version-id: lsfP_7OOzOgXAMN_NKOfIdG.sFekXaNE
accept-ranges: bytes
server: AmazonS3
vary: Accept-Encoding
x-cache: Hit from cloudfront
via: 1.1 174acb08636ac7d9e9a778bbf1bcbc52.cloudfront.net (CloudFront)
x-amz-cf-pop: SEA19-C1
x-amz-cf-id: I9xl86aaalooSqDjN5CRuY3CHjvQtVVzAGQaRY2SZTsFfprN1xGzew==
age: 86884
cross-origin-resource-policy: cross-origin
access-control-allow-origin: *
access-control-expose-headers: *
```

**Comment by hoodmane** [comment]
Working for me. Thanks!

**Comment by bryevdv** [comment]
@hoodmane BTW, my research did  turn up [this document](https://docs.google.com/document/d/1zDlfvfTJ_9e8Jdc8ehuV4zMEu9ySMCiTGMS9y0GU92k/edit) authored by some WhatWG regulars, which said:
> When a document sets this header [COEP], every cross-origin subresource it loads must permit itself to be loaded by setting an appropriate Cross-Origin-Resource-Policy header **or** pass the [CORS check](https://fetch.spec.whatwg.org/#concept-cors-check) by including an Access-Control-Allow-Origin header.

For my own information, was that somehow not the case here? Our CDN sets `access-control-allow-origin: *` after all. (Browser being too strict or that document is out of date?)

**Comment by hoodmane** [comment]
The document you linked says:

> Cross-origin resources can opt in via CORP (with a Cross-Origin-Resource-Policy header with a value which includes the requester, e.g., same-site, or cross-origin for public resources) or with CORS, by responding with appropriate Access-Control-Allow-* headers for requests in CORS mode.

Which is perfectly clear. But it is misleading: at most one of the checks needs to pass, but **which** check is required depends on the request. So if you don't enable both then some requests will not work. 

The [CORS check](https://fetch.spec.whatwg.org/#cors-check) happens when: 
1. the response comes from the network not from a service worker and
2. the "mode" of the request is "cors"

The  [CORP check](https://fetch.spec.whatwg.org/#cross-origin-resource-policy-check) happens when:
1. the response comes from either the network or from a service worker (this is always true) and
2. the "mode" of the request is "no-cors"

Different sources of scripts have different modes:
1. classic `<script>` tags are ordinarily no cors but if the `crossorigin` attribute is specified they are cors (same with `<img>`, `<audio>` and `<video>`).
2. `<script type="module">` tags are always cors
3. `<link>` tags are always cors
4. worker urls are same-origin
5. `importScripts` in a worker is always "no-cors" 

And with `fetch` and `XMLHttpRequest` of course you can choose. I'm not sure about what happens with dynamic or static `import` (the spec for that is in tc39 instead of whatwg and I'm having trouble figuring out what the cors implications of the tc39 spec are...

In our particular example, we are making the requests to the Bokeh cdn via `<script>` tags, so the moral of the story is if we modified the script tags to be `<script crossorigin="anonymous">` then it would work even if `bokeh.cdn.org` doesn't set `cross-origin-resource-policy` as long as it sets `access-control-allow-origin`.

**Comment by bryevdv** [comment]
Thanks for the detailed explanation @hoodmane
