### ISSUE TITLE
[BUG] DataTable`autosize_mode='fit_viewport'` and `autosize_mode='fit_columns` failing in 3.1.0 when data contains strings

### ISSUE THREAD

**Issue by doug-wispr** [bokeh/bokeh#13072]
### Software versions

Python version      :  3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ]
IPython version     :  8.12.0
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  .../venv/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  macOS-13.1-arm64-arm-64bit

### Browser name and version

NA

### Jupyter notebook / Jupyter Lab version

IPython          : 8.12.0 ipykernel        : 6.22.0 ipywidgets       : 8.0.6 jupyter_client   : 8.1.0 jupyter_core     : 5.3.0 jupyter_server   : 2.5.0 jupyterlab       : 3.6.3 nbclient         : 0.6.8 nbconvert        : 6.5.4 nbformat         : 5.7.0 notebook         : 6.5.3 qtconsole        : 5.4.2 traitlets        : 5.9.0

### Expected behavior

When I generate a `DataTable` that has all numeric data and I set `autosize_mode` to either "fit_viewport" or "fit_columns", everything is fine. But if my table has any string data, nothing is rendered.

### Observed behavior

When string data is included, nothing is rendered.

### Example code

This code works as expected:
```Python
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource, TableColumn
from bokeh.models.widgets import DataTable

output_notebook()

def make_table():
    data = {
        "column_1": [1, 2, 3],
        "column_2": [4, 5, 6],
        "column_3": [7, 8, 9],
    }

    data_table = DataTable(
        source=ColumnDataSource(data), 
        columns=[TableColumn(field=col, title=col) for col in data.keys()], 
        width=400, 
        height=280, 
        autosize_mode="fit_viewport",
    )
    return data_table

data_table = make_table()
show(data_table)
```

But this code results in no table being rendered:
```python
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource, TableColumn
from bokeh.models.widgets import DataTable

output_notebook()

def make_table():
    data = {
        "column_1": ['a', 'b', 'c'],
        "column_2": [4, 5, 6],
        "column_3": [7, 8, 9],
    }

    data_table = DataTable(
        source=ColumnDataSource(data), 
        columns=[TableColumn(field=col, title=col) for col in data.keys()], 
        width=400, 
        height=280, 
        autosize_mode="fit_viewport",
    )
    return data_table

data_table = make_table()
show(data_table)
```

Note that if I replace "fit_viewport" with "fit columns", the same behavior occurs. But if I replace "fit_viewport" with "force_fit" (or remove the argument completely), the table renders.

### Stack traceback or browser console output

This behavior is new in Bokeh 3.1.0. I was previously using Bokeh 3.0.1 without trouble. However, even after creating a fresh conda environment and running `pip install bokeh==3.0.01` I cannot return to the old behavior. In that new environment, when I run:
```python
import bokeh
bokeh.__version__
```
I see `'3.0.1'`. 
But when I call `output_notebook()`, I see `BokehJS 3.1.0 successfully loaded.`.

### Screenshots

Here is a working code screenshot (from Jupyter) using `autosize_mode="force_fit"`
![image](https://user-images.githubusercontent.com/119897815/230656689-a192512e-575b-421e-b435-6ed5c70c5b4c.png)

And here is what I see when I use `autosize_mode="fit_viewport"`:
![image](https://user-images.githubusercontent.com/119897815/230656647-bda57e80-6500-40d1-a35b-c1fea792766c.png)

But if all data is numeric, I can generate a table with `autosize_mode="fit_viewport"`:
![image](https://user-images.githubusercontent.com/119897815/230656786-231ea66e-5709-4245-82e1-fe0ab9a726a3.png)

**Comment by Shadoward** [comment]
It seems like this issue is similar to the one discussed [here](https://github.com/bokeh/bokeh/issues/12948). 
When the table row contains only strings and the option "fit_viewport" or "fit_columns" the table doesn't render. However, if the row includes a combination of letters and numbers, the issue doesn't occur.

**Comment by doug-wispr** [comment]
> It seems like this issue is similar to the one discussed https://github.com/bokeh/bokeh/issues/12948.
> When the table row contains only strings and the option "fit_viewport" or "fit_columns" the table doesn't render. However, if the row includes a combination of letters and numbers, the issue doesn't occur.

Yeah, that looks like the same issue.

**Comment by user529481** [comment]
Any ETA on when this might be fixed? This is somewhat of an important feature, I can downgrade but would rather not risk breaking components.

**Comment by mosc9575** [comment]
I have found a workaround for this issue. It makes a difference if the `ColumnDataSource` takes a `dict` as input or a pandas DataFrame.

The source from the DataFrame is working correctly (in the lastest version 3.3.0)

Here is the adapted example from above and the output.
```python
import pandas as pd # added

from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource, TableColumn
from bokeh.models.widgets import DataTable

output_notebook()

def make_table():
    data = {
        "column_1": [1, 2, 3],
        "column_2": [4, 5, 6],
        "column_3": [7, 8, 9],
    }

    data_table = DataTable(
        source=ColumnDataSource(pd.DataFrame(data)), # adapted
        columns=[TableColumn(field=col, title=col) for col in data.keys()], 
        width=400, 
        height=280, 
        autosize_mode="fit_viewport",
    )
    return data_table

data_table = make_table()
show(data_table)
```

![grafik](https://github.com/bokeh/bokeh/assets/68053396/9fbb1bf1-d9a9-43c0-bc1c-3e1bade62705)

**Comment by mosc9575** [comment]
I close this as duplicate. The later incoming issue #13460 addresses the same problem but has already a milestone.
