### ISSUE TITLE
[BUG] Pinching zoom-in on touch devices

### ISSUE THREAD

**Issue by albe-jj** [bokeh/bokeh#13071]
### Software versions

Python version      :  3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.34.0
Tornado version     :  6.1
Bokeh version       :  3.1.0
BokehJS static path :  ...\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Windows-10-10.0.19041-SP0

### Browser name and version

Google chrome for android: version 111.0.5563.116

### Expected behavior

Pinch zoom in and out in android device (google chrome browser).

### Observed behavior

When zoom scroll is activated, pinching to zoom in a 2D plot on touch android browser result in zooming in of the browser viewport instead of the plot. 

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, show
from bokeh.plotting import figure, output_file, save

a = np.array([[1,2], [3, 4]])
p = figure(x_range=(0, 2), y_range=(0, 2))

p.image(image=[a], x=0, y=0, dw=2, dh=2, palette="Spectral11")

output_file("test_pinch_screen.html", mode="inline")
save(p)
```
```


### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

**Comment by bryevdv** [comment]
I seem to recall this working at some point, and the docs and code both seem to reflect that it should work, but I can confirm the same issue on iOS. cc @mattpap for any thoughts about changes to the eventing system

**Comment by mattpap** [comment]
Touch support is generally broken again, e.g. pan tool under certain conditions gives:
![image](https://github.com/bokeh/bokeh/assets/27475/c86e6ae7-2d11-4980-925d-f5baf475cce1)
in JS console.
