### ISSUE TITLE
[BUG] memory leak on hv.extension('bokeh')

### ISSUE THREAD

**Issue by majidaldo** [bokeh/bokeh#13088]
### Software versions

Python version      :  3.11.2 | packaged by conda-forge | (main, Mar 31 2023, 17:45:57) [MSC v.1934 64 bit (AMD64)]
IPython version     :  8.12.0
Tornado version     :  6.2
Bokeh version       :  2.4.3
BokehJS static path : ....Lib/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19045-SP0

### Jupyter notebook / Jupyter Lab version

nb 6.5.3, kernel 6.21.3

### Expected behavior

no memory increase

### Observed behavior

i had the following in a cell that i kept executing (in visual studio code).
it just took a few executions for the memory consumption to go into the GBs.
completely reproducible.

### Example code

```Python

import holoviews as hv
hv.extension('bokeh')
```

### Stack traceback or browser console output

OOM error in vs code.

**Comment by bryevdv** [comment]
@majidaldo Holoviews (and their bokeh extension) is not maintained by the Bokeh team. You should start by posting this issue on the holoviews issue tracker:

https://github.com/holoviz/holoviews
