### ISSUE TITLE
[BUG] Incorrect behaviour of Slider control on Safari (macOS)

### ISSUE THREAD

**Issue by yuriymacdev** [bokeh/bokeh#13081]
### Software versions

Python version      :  3.11.2 (main, Mar 24 2023, 00:31:37) [Clang 14.0.0 (clang-1400.0.29.202)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  /Users/y/Playgrounds/bokehtest/venv/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  macOS-13.3.1-x86_64-i386-64bit

### Browser name and version

macOS Safari 16.4

### Expected behavior

Dragged slider should behave like a regular <input type="range"> HTML control, without selection of the text when the knob is being dragged and without blinking of the tooltip that shows the current slider value.

### Observed behavior

When the slider widget's knob is dragged, the text above it gets selected and the hovering tooltip is blinking.

### Example code

```Python
Can be seen at https://docs.bokeh.org/en/latest/docs/examples/interaction/js_callbacks/slider.html
```

### Screenshots

<img width="722" alt="image" src="https://user-images.githubusercontent.com/50522970/231172861-5b7af812-44ff-4203-8581-f0dd83420c39.png">

**Comment by bryevdv** [comment]
AFAIK this issue is limited to Safari (it does not occur for me on Chrome on OSX, e.g.) @yuriymacdev if you have the ability to test more platforms / browsers please do, it would be valuable to have a more complete survey.

**Comment by yuriymacdev** [comment]
> AFAIK this issue is limited to Safari (it does not occur for me on Chrome on OSX, e.g.) @yuriymacdev if you have the ability to test more platforms / browsers please do, it would be valuable to have a more complete survey.

On Mac, all other browsers I've tested (Firefox, Chromium, Opera) handle this correctly.

@mattpap thanks for fixing this so promptly!

If I understand correctly, the problem occurred because instead of 'input type=range' the div's are used to implement slider functionality.
Just as a suggestion for some future refactoring, perhaps it makes sense for sliders to use a native range input (that all browsers handle well out of box)? They also can be decorated with CSS, and can be programmed to have two handles.
