### ISSUE TITLE
[BUG] Fix broken link to tools guide

### ISSUE THREAD

**Issue by carlosgmartin** [bokeh/bokeh#13108]
### Software versions

Python version      :  3.11.3 (main, Apr  7 2023, 19:30:05) [Clang 13.0.0 (clang-1300.0.29.30)]
IPython version     :  (not installed)
Tornado version     :  6.3.1
Bokeh version       :  3.1.0
BokehJS static path :  /usr/local/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  macOS-11.7.6-x86_64-i386-64bit

### Browser name and version

Firefox 112.0.2

### Expected behavior

Clicking the question mark on a toolbar should open the tools guide.

### Observed behavior

Opens a broken link: https://docs.bokeh.org/en/latest/docs/user_guide/tools.html. The correct link is https://docs.bokeh.org/en/latest/docs/reference/models/tools.html.

### Example code

```Python
N/A
```

### Stack traceback or browser console output

Can be fixed by editing the following lines:
https://github.com/search?q=repo%3Abokeh%2Fbokeh%20%22https%3A%2F%2Fdocs.bokeh.org%2Fen%2Flatest%2Fdocs%2Fuser_guide%2Ftools.html%22&type=code

**Comment by pavithraes** [comment]
@carlosgmartin Welcome, thanks for reporting! Would you be interested in submitting a PR for this?

**Comment by sabbirtkdr** [comment]
@pavithraes Hi, if @carlosgmartin isn't available can I work on this issue? It would potentially help me start my journey to opensource contribution.
