### ISSUE TITLE
Replace utcnow and utcfromtimestamp function calls

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#13125]
`datetime.utcnow` and `utcfromtimestamp` will be deprecated in Python 3.12. We use both in our codebase and should replace them, see https://github.com/python/cpython/issues/103857.

**Comment by rielAsh24** [comment]
@ianthomas23 Hi, I'll be looking into this issue

**Comment by rielAsh24** [comment]
@ianthomas23 Hey, I'm facing some difficulty setting-up geckodrivers as stated in the contribution guidelines. pip and conda show the package doesn't exist.

![geckodriver install error](https://github.com/bokeh/bokeh/assets/89381263/d4eedc8e-8e64-4786-9376-41f2548c8921)

Would be glad if guided on the same.

**Comment by ianthomas23** [comment]
@rielAsh24 I am guessing that you are using an ARM64 mac such as an M1? If so just temporarily comment out the `geckodriver` line in your environment yaml file as there is no such package available for ARM64 macOS. That should allow you to continue following the developer installation instructions. You won't be able to run the BokehJS integration tests that generate images, but this is OK as you should not need to modify those.

**Comment by rielAsh24** [comment]
@ianthomas23 Got you, I'll try it right away. Thank you!

**Comment by rielAsh24** [comment]
Hey @ianthomas23, I added the required changes to the files and ran all the tests recommended.
