### ISSUE TITLE
[BUG] The version switcher "https://docs.bokeh.org/switcher.json" file is malformed

### ISSUE THREAD

**Issue by capac** [bokeh/bokeh#13129]
### Software versions

Python version      :  3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:07:22) [Clang 14.0.6 ]
IPython version     :  8.12.0
Tornado version     :  6.3
Bokeh version       :  3.1.1
BokehJS static path :  /usr/local/Caskroom/miniconda/base/envs/docs/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  macOS-11.7.6-x86_64-i386-64bit

### Expected behavior

I'm trying to compile the Bokeh docs. This process creates a directory at `build/html` with the HTML files of the Bokeh documentation. I'm going to use them to create a Dash docset (see https://kapeli.com/docsets).

### Observed behavior

After updating the `conf.py` file in `docs/bokeh/source` to add in the `extensions` list the `sphinx_favicon` extension (after installing the `sphinx-favicon` module with `pip`), I receive the following warning and error:

```
Warning, treated as error:
The version switcher "https://docs.bokeh.org/switcher.json" file is malformed at least one of the items is missing the "url" or "version" key
make: *** [html] Error 2
```

Now to be fair, if you go look at the URL in the error, the first and last entries don't have the `version` key name, but are listed just as `name`:
```
[
  {
    "name": "latest",
    "url": "https://docs.bokeh.org/en/latest/"
  },
  {
    "version": "3.1.1",
    "url": "https://docs.bokeh.org/en/3.1.1/"
  },
  {
    "version": "3.0.3",
    "url": "https://docs.bokeh.org/en/3.0.3/"
  },
  {
    "version": "2.4.3",
    "url": "https://docs.bokeh.org/en/2.4.3/"
  },
  {
    "version": "2.3.3",
    "url": "https://docs.bokeh.org/en/2.3.3/"
  },
  {
    "version": "2.2.3",
    "url": "https://docs.bokeh.org/en/2.2.3/"
  },
  {
    "version": "2.1.1",
    "url": "https://docs.bokeh.org/en/2.1.1/"
  },
  {
    "version": "2.0.2",
    "url": "https://docs.bokeh.org/en/2.0.2/"
  },
  {
    "version": "1.4.0",
    "url": "https://docs.bokeh.org/en/1.4.0/"
  },
  {
    "name": "dev (3.2)",
    "url": "https://docs.bokeh.org/en/dev-3.2/"
  }
]
```
Any help would be appreciated.

### Example code

```Python
I've download the Bokeh 3.1.1 tag. Once it's extracted, do the following:

cd docs/bokeh
make html
```
You may need to install several additional packages, either using conda or pip.
```


### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

**Comment by bryevdv** [comment]
The version of pydata-sphinx-theme you are trying to use is too new. Supported dev configurations, including any  required pinned package versions, are in the conda env files.

**Comment by bryevdv** [comment]
BTW please also be aware that none of the example plots in the docs will work offline, they all load BokehJS from external remote CDN.

**Comment by bryevdv** [comment]
Note that we do verify the docs build in every push to CI, using the the supported environments in specified in the conda envs for the relevant dev branch. Also note that the versions of sphinx and theme, etc that are still pinned for version 3.1.1 are being raised for the next future release. If you want to see the details about that you can refer to the changes and discussion in this PR:

* https://github.com/bokeh/bokeh/pull/13094

But In any case the appropriate venue for usage questions (including dev-related questions like dev setup or building the docs) is the [Discourse site](https://discourse.bokeh.org), so I will close this issue.
