### ISSUE TITLE
[BUG] Mismatch in GroupFilter documentation example between text and code

### ISSUE THREAD

**Issue by jbkalmbach** [bokeh/bokeh#13126]
### Software versions

Python version      :  3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
IPython version     :  8.13.2
Tornado version     :  6.1
Bokeh version       :  3.1.0
BokehJS static path :  /global/common/software/lsst/gitlab/desc-python-prod/84904/py/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.14.21-150400.24.46_12.0.71-cray_shasta_c-x86_64-with-glibc2.31

### Expected behavior

The documentation text and the plot created by the example code say the output of the group filter in the example code should be the `setosa` labelled data.

### Observed behavior

But the example filter selects the `versicolor` labelled data

### Example code

```Python
(From https://github.com/bokeh/bokeh/blob/branch-3.2/examples/basic/data/filter_group.py)

from bokeh.layouts import gridplot
from bokeh.models import CDSView, ColumnDataSource, GroupFilter
from bokeh.plotting import figure, show
from bokeh.sampledata.iris import flowers

source = ColumnDataSource(flowers)
###
### ***Here the filter selects data that doesn't match documentation or plot label below***
###
view = CDSView(filter=GroupFilter(column_name="species", group="versicolor")) 

opts = {"height": 300, "width": 300, "tools": "box_select,reset,help"}

p1 = figure(title="Full data set", **opts)
p1.circle(x="petal_length", y="petal_width", source=source, color="black")

p2 = figure(title="Setosa only", x_range=p1.x_range, y_range=p1.y_range, **opts)
p2.circle(x="petal_length", y="petal_width", source=source, view=view, color="red")

show(gridplot([[p1, p2]]))
```
```


### Stack traceback or browser console output

_No response_

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/4755090/eb36f063-f85b-4864-9a44-2fdf5b256764)

**Comment by jbkalmbach** [comment]
Happy to fix it up real quick myself.

**Comment by bryevdv** [comment]
@jbkalmbach That would be appreciated, thank you!
