### ISSUE TITLE
Error in downstream library when rendering WebGL canvas with width or height of zero

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#13139]
Originally reported in Panel holoviz/panel#4855.

Under certain circumstances it is possible in BokehJS to create a canvas with a `width` and/or `height` of zero. This is not possible from Bokeh on the Python side, but is using BokehJS via Panel/HoloViews. The reported error message in the browser console is
```
Error rendering Bokeh items: DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at g.blit_webgl (http://localhost:5006/static/js/bokeh.min.js? ...
``` 
Tracking this down leads to
https://github.com/bokeh/bokeh/blob/563a487f8155900b170eadc501587c98f154ee15/bokehjs/src/lib/models/canvas/canvas.ts#L217-L226

According to https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage#exceptions it is not valid to call `ctx.drawImage` with an image that has a width or height of zero.

There is a simple fix, the blitting can be aborted early if width or height are zero. I will submit a PR for this shortly.

**Comment by mattpap** [comment]
I investigated the original submission and this is a layout issue, which results in a bad bbox with in turn results in a badly sized canvas.

**Comment by bryevdv** [comment]
> I investigated the original submission and this is a layout issue, which results in a bad bbox with in turn results in a badly sized canvas.

A defensive guard against rendering to zero-sized canvases still seems advised, if nothing else users might try setting this way to hide things.

**Comment by ianthomas23** [comment]
I could reclassify PR #13140 as a workaround for this issue rather than a fix, if the underlying layout issue is going to be fixed.
