### ISSUE TITLE
roots added in a callback are not displayed

### ISSUE THREAD

**Issue by jeanprey** [bokeh/bokeh#13131]
### Software versions

Python version      :  3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)]
IPython version     :  8.13.2
Tornado version     :  6.3.1
Bokeh version       :  3.1.1
BokehJS static path :  /usr/local/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  macOS-12.6.3-x86_64-i386-64bit

### Expected behavior

add_root with bokeh 2 lively updates a document displayed with bokeh serve. bokeh 3 doesn't update it anymore.

### Observed behavior

With bokeh 3, only roots added at the document creation are displayed. roots added in a callback are not displayed. In the following example, "Hello" and the button are displayed but "On" is never displayed when the button is pressed.

### Example code

```Python
import bokeh.models as bm
import bokeh.plotting as bp

# The callback
def toggle() -> None:
    """
    Toggle state
    """
    global state
    if state: bokehDoc.remove_root(msg)
    else: bokehDoc.add_root(msg)
    state = not state


# Build the page
button = bm.Button(label="Toggle state")
button.on_event("button_click", toggle)
state = False
hello = bm.Div(text="Hello")
msg = bm.Div(text="On")
bokehDoc = bp.curdoc()
bokehDoc.add_root(hello)
bokehDoc.add_root(button)
```

**Comment by mattpap** [comment]
This is a big regression, but it looks like it's easy to fix.

**Comment by mcouch-lg** [comment]
Is there any update on this?

**Comment by bryevdv** [comment]
@mcouch-lg there is never any reason to ask this question on an OSS project tracker. If there were any updates, they would be recorded here in the issue.
