### ISSUE TITLE
Tests fail due to `requests` and `urllib3` 2.x incompatibility

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13152]
See https://github.com/psf/requests/issues/6432. The easiest way to work around this will be to pin `urllib3 <2` for the time being.  Note this is a transitive dependency for us.

**Comment by rielAsh24** [comment]
Hey @mattpap! I will be looking into this. Wanted to confirm, the pinning of the libraries is to be done in all the .yml files in the conda folder or just the environment-test-3.*.yml?

**Comment by mattpap** [comment]
@rielAsh24, normally I would give external contributors a chance to fix such issues, but given our CI is broken right right now and we have a dozen or so PRs to review and merge for the upcoming 3.2 release, then there isn't time for this. In any case, thanks for willing to help with this. If you want to contribute regardless, then we have plenty of open issues to choose from, that you may be interested in.

**Comment by rielAsh24** [comment]
> @rielAsh24, normally I would give external contributors a chance to fix such issues, but given our CI is broken right right now and we have a dozen or so PRs to review and merge for the upcoming 3.2 release, then there isn't time for this. In any case, thanks for willing to help with this. If you want to contribute regardless, then we have plenty of open issues to choose from, that you may be interested in.

@mattpap Surely glad to help! . I'll look into other issues contribute 😄
