### ISSUE TITLE
Prevent blink when updating ImageURL source

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#13157]
### Problem description

As described in https://github.com/bokeh/bokeh/issues/11877, a ImageURL glyph blinks when its source is updated. This is annoying especially for animations / when switching between images with only slight changes.

The author of the original issue mentioned that it appeared in Bokeh 2.3.0. There is no such problem with ImageRGBA.

### Feature description

@mattpap stated that caching the images would do the trick, see _TODO_ [here](https://github.com/bokeh/bokeh/blob/6a018066a85825dd912e32becf1d6e13760105ae/bokehjs/src/lib/models/glyphs/image_url.ts#L62).

### Potential alternatives

I could not make a 2.2.3 install work but if indeed there was no blinking in versions prior to 2.3.0, an alternative could be to investigate what caused the regression.

_Edit: I could confirm that the regression occurred between 2.2.3 and 2.3.0_

### Additional information

Minimal code example:

```python
from bokeh.plotting import figure, curdoc
from bokeh.models import ColumnDataSource, Button
from bokeh.layouts import column


def update_image(event):
    global k
    k += 1
    data = {"image": [urls[k % 2]], "width": [300], "height": [300], "x": [0], "y": [0]}
    source_image.data = data


k = 0
urls = ['https://docs.bokeh.org/en/latest/_images/examples/basic/areas/stacked_area.png',
        'https://docs.bokeh.org/en/latest/_images/examples/basic/annotations/colorbar_log.png']

fig = figure(frame_width=300, frame_height=300)
fig.xgrid.visible = False
fig.ygrid.visible = False
source_image = ColumnDataSource(data={"image": [urls[0]], "width": [300], "height": [300], "x": [0], "y": [0]})
image_model = fig.image_url("image", source=source_image,
                            x="x", y="y", w="width", h="height", anchor="bottom_left")

button = Button()
button.on_click(update_image)

doc = curdoc()
doc.add_root(column(fig, button))
```

**Comment by TheoMathurin** [comment]
With the following `_set_data` function, there is no blink. However we don't yet know if the glyph still behaves as expected in all possible circumstances.

Note that this solution does not cache images. Rather, it's mostly based on the last version that worked without blink (2.2.3). In particular, `this.image` is instantiated only once with a new `Array`, and `this.image[i]` is set in the `loaded` function.

```typescript
protected override _set_data(): void {
    this._set_data_iteration++

    const n_urls = this.url.length
    if (this.image == null || this.image.length != n_urls) {
      this.image = new Array(n_urls)
    }
    this.rendered = new Indices(n_urls)

    const {retry_attempts, retry_timeout} = this.model
    const {_set_data_iteration} = this

    for (let i = 0; i < n_urls; i++) {
      const url = this.url.get(i)
      if (url == "")
        continue

      new ImageLoader(url, {
        loaded: (image) => {
          if (this._set_data_iteration == _set_data_iteration) {
            this.image[i] = image
            this.renderer.request_render()
          }
        },
        failed: () => {
          if (this._set_data_iteration == _set_data_iteration) {
            this.image[i] = undefined
          }
        },
        attempts: retry_attempts + 1,
        timeout: retry_timeout,
      })
    }
```

@mattpap what is your view on this?

**Comment by jeanbaptistejoan** [comment]
I'm very interested in this being solved.

In my use case I really need continuity when switching images. Over time I've developed a custom tool for this but it is inconvenient and can be slow.

**Comment by TheoMathurin** [comment]
@mattpap Do you think this is the right approach?

I've been thinking about caching as an alternative. If you cache images after they have been requested once, it will blink each time an image is requested for the first time. You would either need to cache all images upfront (suboptimal), or cache images sitting next to that which is currently displayed so that animations run smoothly (somewhat convoluted).
