### ISSUE TITLE
[BUG] layout sizing_mode examples broken in Bokeh 3

### ISSUE THREAD

**Issue by cdeil** [bokeh/bokeh#13165]
### Browser name and version

Chrome Mac (same on Safari)

### Expected behavior

At https://docs.bokeh.org/en/latest/docs/user_guide/basic/layouts.html#multiple-objects I would expect the example to show a plot.

### Observed behavior

The plot has zero width. This looks like a bug.

### Example code

This is the example from your docs:
https://docs.bokeh.org/en/latest/docs/user_guide/basic/layouts.html#multiple-objects
https://github.com/bokeh/bokeh/blob/branch-3.2/examples/basic/layouts/sizing_mode_multiple.py

### Stack traceback or browser console output

no errors in browser console or when running the example locally

In the single object example the plot does show, but also when making the browser window small I don't think the results are correct, the "size" modes don't behave properly:
https://docs.bokeh.org/en/latest/docs/user_guide/basic/layouts.html#single-object

At https://docs.bokeh.org/en/2.4.3/docs/user_guide/layout.html#multiple-objects the example looks OK. It seems this is a docs example that wasn't updated when Bokeh 3 updates were made? (or it's broken)

### Screenshots

<img width="1412" alt="Screenshot 2023-05-28 at 15 07 22" src="https://github.com/bokeh/bokeh/assets/852409/7f6b29b4-dbd4-45b3-9f44-4f0c521aa391">

**Comment by pavithraes** [comment]
Thanks for reporting and looking into it! I see we already have #13077 to track the described issue, so I'll close this one as a duplicate. :)
