### ISSUE TITLE
[BUG] legend_field labels no longer update with CDS in Bokeh 3

### ISSUE THREAD

**Issue by samueljamesbader** [bokeh/bokeh#13182]
### Software versions

**For 2.4.3 example**

Python version      :  3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  2.4.3
BokehJS static path :  C:\Users\[OMITTED]\bokeh2venv\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

**For 3.1.1 example**

Python version      :  3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.1.1
BokehJS static path :  C:\Users\[OMITTED]\bokeh3venv\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Google Chrome Version 114.0.5735.110 (Official Build) (64-bit)

### Expected behavior

(This bug report is based on [this Discourse exchange](https://discourse.bokeh.org/t/legend-field-labels-no-longer-update-with-cds-in-bokeh-3/10534/1).)

Suppose the user has a plot which depends on a ColumnDataSource and uses the legend_field feature to group legend entries browser-side.  If the data in the CDS is updated such that the column designated by legend_field changes, the legend entries should also change.  The behavior was normal in Bokeh 2.4.3, but seems to be broken in Bokeh 3.1.1.

I’ve copied the [Legend Field tutorial from the Bokeh documentation](https://docs.bokeh.org/en/latest/docs/user_guide/basic/annotations.html#automatic-grouping-browser-side) to make a minimal example.  As you’ll see, I’ve just added a radio group next to the plot which, when clicked, updates the CDS.  I’ve run this code in both a Bokeh 2.4.3 environment and a Bokeh 3.1.1 environment, and it outputs an html file with the dynamic plot. I’ve attached a slide of screenshots showing how, in 2.4.3, the Legend updates when the data changes, but in 3.1.1, you see it does not.

### Observed behavior

In Bokeh 2.4.3, the legend entries update automatically.  In Bokeh 3.1.1, the glyphs in the legend update, but not their labels.  And if the quantity of entries that should appear changes, that does not update either.  So after a data update, the legend may have the wrong number of entries and the entries may be deceptively labelled.  This is clear in the screenshot of the minimal example attached.

### Example code

```Python
import bokeh
import numpy as np
from bokeh.io import show
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.plotting import figure, save
from bokeh.models.widgets import RadioGroup

orange, blue = '#ef8a62', '#67a9cf'

all_data=dict(
    x=[1, 2, 3, 4, 5, 6],
    y=[2, 1, 2, 1, 2, 1],
    color=[orange, blue, orange, blue, orange, blue],
    label=['hi', 'lo', 'hi', 'lo', 'hi', 'lo'],
)

# Make some subsets of this data and collect into a dict
data_hi={k:np.array(v)[np.array(all_data['label'])=='hi'] for k,v in all_data.items()}
data_lo={k:np.array(v)[np.array(all_data['label'])=='lo'] for k,v in all_data.items()}
datas={'all':all_data,'hi':data_hi,'lo':data_lo}

# We'll start with the "hi" subset
source = ColumnDataSource(data_hi)

# Create the plot using the 'label' as the legend_field
p = figure(x_range=(0, 7), y_range=(0, 3), height=300, toolbar_location=None)
p.circle('x', 'y', radius=0.5, color='color',
         legend_field='label', source=source)

# When a radio element is clicked, change source.data to the corresponding entry in datas
# Slight js tweak here between v2.4.3 and v3.1.1 based on how the serialization works I think(?)
rg = RadioGroup(labels=list(datas.keys()),active=1)
rg.js_on_change('active',CustomJS(args=dict(datas=datas,order=dict(enumerate(datas.keys())),source=source),
        code="source.data=datas[order[cb_obj.active]];" if bokeh.__version__.startswith('2') else \
             "source.data=datas[order.get(cb_obj.active)];"))

# Save to file
print("Bokeh Version: ",bokeh.__version__)
save(bokeh.layouts.row([p,rg]),
    title=f'LegendFieldRegression_Bokeh{bokeh.__version__}',
    filename=f'LegendFieldRegression_Bokeh{bokeh.__version__}.html')
```

### Screenshots

I'm showing on the left column what happens in Bokeh 2.4.3, and in the right column what happens in Bokeh 3.1.1.  In both cases, I run the minimal example code and look at the resulting output HTML.  It starts with the "hi" radio-group selected.  Then I click "lo", then I click "all", and screenshot after each action.  On the left side, you see the legend update properly.  On the right side, the legend label does not change nor does it accommodate an additional glyph (though the color changes...).  I've circled in red on the right.

![image](https://github.com/bokeh/bokeh/assets/6495688/b31fdbbd-bd75-4edc-84da-c8598f451888)

**Comment by mattpap** [comment]
This happens due to an unfortunate optimization that was introduced during the recent redesign of `Legend` annotation.
