### ISSUE TITLE
[BUG] Cannot reset enabled_dates in DatePicker

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#13192]
### Software versions

Python version      :  3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
IPython version     :  (not installed)
Tornado version     :  6.3.2
Bokeh version       :  3.1.1
BokehJS static path :  /home/user/miniconda3/envs/myenv/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-6.2.15-300.fc38.x86_64-x86_64-with-glibc2.37

### Expected behavior

In Bokeh 2.4.3 it was possible, albeit a bit counter-intuitive, to reset `enabled_dates` by changing it to an empty list.

### Observed behavior

Now the behavior has changed and doing so makes all dates unavailable. This makes more sense but to my knowledge now there is no way to reset `enabled_dates`.

I've also tried setting `enabled_dates` to `None` (throws an error in the browser) and `disabled_dates` to an empty list.

### Example code

```Python
from bokeh.models import DatePicker, Button
from bokeh.layouts import column
import datetime as dt
from bokeh.io import curdoc


def callback(_):
    picker.disabled_dates = []


button = Button()
button.on_click(callback)
picker = DatePicker(enabled_dates=[dt.date(2023, 6, 8)])
col = column(button, picker)

curdoc().add_root(col)
```

**Comment by mattpap** [comment]
We handle this case, i.e setting `date_picker.enabled_dates = None`, but the underlying library doesn't.

**Comment by TheoMathurin** [comment]
Thanks @mattpap for the quick fix!
