### ISSUE TITLE
[FEATURE] Make BoxEditTool support Quad Model

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13203]
### Problem description

In recent versions of Holoviews, we changed `hv.Rectangle` object to use Bokeh model `Quad` instead of `Rect`, because of the issues described [here](https://github.com/bokeh/bokeh/issues/12734#issuecomment-1406537475).

We previously used `BoxEditTool` in Holoviews, though it does not work with Quad.  

### Feature description

I have played around with this and got an implementation of BoxEditTool, which works for both Rect and Quad. 

The implementation is here https://github.com/bokeh/bokeh/compare/branch-3.2...Hoxbro:bokeh:hoxbro_quad_edit

``` python
from bokeh.plotting import figure
from bokeh.models import BoxEditTool

from bokeh.io import curdoc

p = figure(x_range=(-4, 4), y_range=(-4, 4))
r_rect = p.rect(x=[0], y=[0], width=[1], height=[1])
r_quad = p.quad(left=[0], bottom=[0], top=[1], right=[1], color="#B3DE69")

draw_tool = BoxEditTool(renderers=[r_quad, r_rect])
p.add_tools(draw_tool)
p.toolbar.active_drag = draw_tool

curdoc().add_root(p)
```

https://github.com/bokeh/bokeh/assets/19758978/3612498b-4db3-48d1-90c1-d9333b1901ea

### Potential alternatives

Not support BoxEditTool for Quad :upside_down_face:

**Comment by hoxbro** [comment]
Something I noted during my testing was that TypedArray does not behave well when moved around. 

``` python
import numpy as np
from bokeh.plotting import figure
from bokeh.models import BoxEditTool
from bokeh.io import curdoc

p = figure(x_range=(-4, 4), y_range=(-4, 4))
r_rect = p.rect(x=[0], y=[0], width=[1], height=[1])
r_rect_np = p.rect(x=np.array([2]), y=np.array([2]), width=np.array([3]), height=np.array([3]))

draw_tool = BoxEditTool(renderers=[r_rect])
p.add_tools(draw_tool)
p.toolbar.active_drag = draw_tool

curdoc().add_root(p)
```

**Comment by mattpap** [comment]
Note that your ndarrays are of integer dtype:
```py
In [1]: import numpy as np

In [2]: np.array(2)
Out[2]: array(2)

In [3]: _.dtype
Out[3]: dtype('int64')
```
Thus some weirdness is expected, though it should align the position to the grid.

**Comment by hoxbro** [comment]
Same thing with `r_rect_np = p.rect(x=np.array([2.]), y=np.array([2.]), width=np.array([3.]), height=np.array([3.]))`

**Comment by mattpap** [comment]
> Same thing with `r_rect_np = p.rect(x=np.array([2.]), y=np.array([2.]), width=np.array([3.]), height=np.array([3.]))`

This works fine, at least with PR #13204.
