### ISSUE TITLE
Allow inline LaTeX support

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13211]
The current version of bokeh only supports whole strings not substrings for the translation to LaTeX. This is mentioned [here](https://github.com/holoviz/holoviews/issues/5740).

At the moment a workaround is to add `\text{ ... }` to the string for plain text inside the math text, but this isn't user-friendly.
The goal is that the code below is valid and results in the figure below.

```Python
x = arange(-2*pi, 2*pi, 0.1)
y = sin(x)

p = figure(height=250, title=r"$$\sin(x)$$ for $$x -2\pi$$ and $$2\pi$$")
p.circle(x, y, alpha=0.6, size=7)

label = Label(
    text=r"$$y = \sin(x)$$",
    x=150, y=130,
    x_units="screen", y_units="screen",
)
p.add_layout(label)

p.yaxis.axis_label = r"$$\sin(x)$$"
p.xaxis.axis_label = r"\(x\pi\)"

show(p)
```
![sin](https://github.com/bokeh/bokeh/assets/68053396/e05eff80-8c20-402e-878e-9c97ed623e54)

**Comment by ianthomas23** [comment]
It is recorded as item 4 in discussion https://github.com/bokeh/bokeh/discussions/12632, but there is no specific issue for it yet (until now!)
