### ISSUE TITLE
js_link is broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13217]
@mattpap all the `js_link` examples in the docs e.g. 

* https://docs.bokeh.org/en/dev-3.2/docs/user_guide/interaction/linking.html#linked-properties
* https://docs.bokeh.org/en/dev-3.2/docs/first_steps/first_steps_9.html#adding-widgets
* https://docs.bokeh.org/en/dev-3.2/docs/examples/topics/images/image_origin_anchor.html

Are non-functional, reporting this error in the console:
```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.value')
```

cc @bokeh/core I would suggest wait until this is fixed to release

**Comment by mattpap** [comment]
`this` wasn't binding anymore due to a misunderstanding in how `.bind()` actually works (can't rebind). Now that we support ES modules in `CustomJS` callbacks, going forward we should start using them instead, as they give more explicit and readable setup (no implicit `this` and `cb_` arguments).
