### ISSUE TITLE
Search bar is missing from dev docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13222]
cc @tcmetzger @bokeh/core 
 
ref: https://docs.bokeh.org/en/dev-3.2/docs/user_guide.html

I am not seeing the search bar anywhere, it is usually at the top of the LHS nav menu.

**Comment by ianthomas23** [comment]
We now have the magnifying glass on the top right.

**Comment by bryevdv** [comment]
Is it not possible to have both, I wonder? I think the field at the top of the nav menu is much more obvious.

**Comment by ianthomas23** [comment]
I agree, but I wonder if there some standardisation occurring in pydata sphinx theme.

**Comment by bryevdv** [comment]
Maybe, my own opinion is definitely to take what works from PST but always ultimately do whatever works best for us. That said: I'll try to take a quick look today, but I would not otherwise suggest to hold up the release since you've pointed out that there is still some search available.
