### ISSUE TITLE
[BUG] `PropertyValueColumnData._stream()` doesn't handle the case when `rollover` is `0` 

### ISSUE THREAD

**Issue by xiaoyang-sde** [bokeh/bokeh#13238]
### Software versions

Bokeh version: `branch-3.3`

### Expected behavior

If `rollover` is set to 0, calling the `_stream` method within `PropertyValueColumnData` should remove all rows. This behavior can be used to delete all rows within a `ColumnDataSource`. (The documentation states that assigning an empty `dict` to `ColumnDataSource.data` achieves the same outcome, but our specific use case doesn't allow us to perform this operation.)

```py
# Source: https://github.com/bokeh/bokeh/blob/branch-3.3/src/bokeh/core/property/wrappers.py#L470-L481
for k, v in new_data.items():
            if isinstance(self[k], np.ndarray) or isinstance(new_data[k], np.ndarray):
                data = np.append(self[k], new_data[k])
                if rollover and len(data) > rollover:
                    data = data[-rollover:]
                # call dict.__setitem__ directly, bypass wrapped version on base class
                dict.__setitem__(self, k, data)
            else:
                L = self[k]
                L.extend(new_data[k])
                if rollover is not None:
                    del L[:-rollover]
```

### Observed behavior

If `rollover` is set to `0`, calling the `_stream` method within `PropertyValueColumnData` has no effect.

### Example code

Our use case is related to the Perspective pane in Panel, which uses the `ColumnDataSource` as the data source. `https://panel.holoviz.org/reference/panes/Perspective.html`.
To reproduce this issue, stream some data with `rollover=0` is enough.

**Comment by bryevdv** [comment]
> https://panel.holoviz.org/reference/panes/Perspective.html.

For future reference [Minimal Reproducible Examples](https://stackoverflow.com/help/minimal-reproducible-example) should be *pure Bokeh code*, and not e.g. Panel code. Panel is a different project maintained by different people and introducing Panel adds a lot of unrelated complexity that only makes it more difficult to debug *Bokeh* issues. 

@xiaoyang-sde as you seem to have a handle on the relevant codepaths, would you like to submit a PR to handle the "0" case in a better way?

**Comment by xiaoyang-sde** [comment]
Thanks! I would like to submit a PR.

Apologies for not putting Bokeh code. Since we are working with Panel, it's not convenient to extract pure Bokeh code from the Panel logics. I traced down the call stack to find the root cause, which is described in the issue.
