### ISSUE TITLE
chart stocks_timeseries need to use internal data instead of yahoo finance

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1323]
This is causing some random errors in TravisCI (timeouts). We have others examples using stocks data... let's use them...

**Comment by bryevdv** [comment]
Contrariwise, I think it is important to demonstrate how to integrate with things like Yahoo API, which is going to be a very common sort of thing people will want to do. I do not recall seeing any testing failures over this issue in the last year or more, so I am going to close. Please re-open if you disagree.

**Comment by damianavila** [comment]
That's ok... and I did not see the failure for long time... so, no problem,
