### ISSUE TITLE
[BUG] .circle and .text create strange behaviour

### ISSUE THREAD

**Issue by k1m190r** [bokeh/bokeh#13243]
### Software versions

Python version      :  3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]
IPython version     :  8.12.0
Tornado version     :  6.2
Bokeh version       :  3.1.1
BokehJS static path :  C:\Users\<user.name>\Python\conda_envs\cuda\lib\site-packages\bokeh\server\static
node.js version     :  v18.16.1
npm version         :  9.5.1
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

MS Edge: V115.0.1901.157 (Official build) beta (64-bit) 

### Jupyter notebook / Jupyter Lab version

jupyter_core: 5.3.0, jupyter_client: 8.1.0

### Expected behavior

Expected behavior selections work and plot not move during selection.

### Observed behavior

Plot moves under the mouse during selection.
- This only happens when `.circle` and `.text` are on the same plot.
- Dropping version of bokeh to 3.0.* produces normal expected behavior.

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource

# output_notebook()

# prep X Y Well for display
data = dict(
    text_label=np.random.rand(20),
    x=np.random.rand(20),
    y=np.random.rand(20),
)
source = ColumnDataSource(data)

TOOLS = "tap,box_select,lasso_select,wheel_zoom,reset"
fig_map = figure(tools=TOOLS)

fig_map.circle("x", "y", source=source)
fig_map.text("x", "y", text="text_label", source=source)

show(fig_map)
```

### Stack traceback or browser console output

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at w._render (bokeh-3.1.1.min.js:534:1738)
    at w.render (bokeh-3.1.1.min.js:376:1233)
    at R._render (bokeh-3.1.1.min.js:372:6705)
    at R.render (bokeh-3.1.1.min.js:239:1657)
    at _._paint_levels (bokeh-3.1.1.min.js:582:15820)
    at _._actual_paint (bokeh-3.1.1.min.js:582:15197)
    at _.paint (bokeh-3.1.1.min.js:582:14153)
    at _.repaint (bokeh-3.1.1.min.js:582:14049)
    at bokeh-3.1.1.min.js:582:3370
    at a (bokeh-3.1.1.min.js:583:187)

### Screenshots

The gray area grows as selection is active and mouse is moving.

![image](https://github.com/bokeh/bokeh/assets/148415/6f572290-8dc4-47d8-92c0-4dbbed35da93)

**Comment by bryevdv** [comment]
@k1m190r please first try latest version 3.2 and report results.

**Comment by k1m190r** [comment]
OK 3.2 does not have this problem. My default coda repo only has 3.1 at the moment, but conda-forge has 3.2. So **not** a problem I guess. Will close.

Thank you for your help Bryan.
