### ISSUE TITLE
Complete the consolidation of scatter markers in bokeh.plotting

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13246]
cc @bokeh/dev 

Awhile back we started the process of consolidating and simplifying scatter markers by removing individual models for scatters, e.g. `Square`, `Triangle`, etc. and replacing them with a single `Scatter` glyph parameterized by marker type. IIRC we intended to continue down this path, and encourage the use of `scatter` as the primary API for scatter plots in `bokeh.plotting` as well, but never quite completed that part. 

I'd like to propose doing so now. Specifically I would deprecate all the individual scatter methods, and also finally make clean separation between `Circle` (data-radius only) and `Scatter(marker="circle")` (screen size only). Summarized:

```python
# These all emit a deprecation
p.triangle(...)
p.square(...)
p.hex(...)

# deprecate glyph-circle with a size
p.circle(..., radius=5)   # expected
p.circle(..., size=10)    # returns Scatter(..., marker="circle") and emits deprecation

# deprecate scatter-circle with a radius
p.scatter(..., marker="circle", size=10)    # expected
p.scatter(..., marker="circle", radius=5)   # returns Circle(...) and emits deprecation
```

The one corner case we would lose here is if someone called `circle(size=10)` to start and wanted to change to `circle(radius=5)` later. I'ver never see or heard of anyone wanting this, and am comfortable with this change since there would be workarounds to recommend in case it really did affect anyone. 

Along with this, we would go through all the docs and examples and use `scatter` consistently for all scatter plots with a screen-space size, or `circle` for plots with a data-space radius. 

I think it goes without saying we would not actually remove any of the deprecated methods any time soon. *Maybe* at a future 4.0 release. 

Are there any concerns or objections to my pursuing the changes above for 3.3?

**Comment by ianthomas23** [comment]
No objections from me. I think the docs update is probably more important than the deprecations so that we don't accidentally end up with a release in which the First Steps recommend a deprecated approach.
