### ISSUE TITLE
[BUG]  plots in png generated by SaveTool on gridplot layout overlap

### ISSUE THREAD

**Issue by ryanolf-tb** [bokeh/bokeh#13252]
### Software versions

Python version      :  3.11.1 (main, Jan  6 2023, 16:08:28) [Clang 14.0.0 (clang-1400.0.29.202)]
IPython version     :  8.8.0
Tornado version     :  6.2
Bokeh version       :  3.2.0
BokehJS static path :  /Users/ryanolf/.pyenv/versions/3.11.1/envs/jupyter/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v19.7.0
npm version         :  9.5.0
Operating system    :  macOS-13.4-arm64-arm-64bit

### Browser name and version

Chrome 114.0.5735.198 (but also tested in Firefox)

### Jupyter notebook / Jupyter Lab version

Jupyter notebook 6.5.2

### Expected behavior

I have a layout generated with gridplot that looks like this in a Jupyter notebook:
<img width="563" alt="Screenshot 2023-07-13 at 23 45 32" src="https://github.com/bokeh/bokeh/assets/112618914/595ae40f-41e3-419e-bd00-dd11f9866205">
When I download a png with the SaveTool, I expect it to look similar.

### Observed behavior

Instead, the downloaded image shows the plots overlapping, like so:
![bokeh_plot](https://github.com/bokeh/bokeh/assets/112618914/b2ce82f2-5248-4013-8e31-8f5a03b1447e)

### Example code

I run this in a jupyter notebook cell:
```Python
from bokeh.plotting import figure, show, output_notebook
from bokeh.layouts import gridplot

output_notebook()

plots = []
x = list(range(100))
y = list(range(100))
for (x, y) in [(x,y)]*4:
    p = figure(width=300, height=300, tools="pan,box_zoom,save,reset")
    p.line(x, y)
    plots.append(p)

layout = gridplot(plots, ncols=2)

# Show the plot
handle = show(layout, notebook_handle=True)
```

**Comment by mattpap** [comment]
High DPI support is broken in grid plots.
