### ISSUE TITLE
[BUG] Python Bokeh visualization aspect ratio issue

### ISSUE THREAD

**Issue by aafshinfard** [bokeh/bokeh#13259]
### Software versions

Python version      :  3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59)
IPython version     :  8.5.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.0
BokehJS static path :  /projects/btl/aafshinfard/miniconda3/envs/btl-amir/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-3.10.0-693.5.2.el7.x86_64-x86_64-with-glibc2.17

### Jupyter notebook / Jupyter Lab version

I am using Jupyter notebook on VSCode (Jupyter Notebook Renderers v1.0.17)

### Expected behavior

I expected a circle with radius=1, which should reach y=-/+1 on the y axis.y-axis

### Observed behavior

On the y-axis, it goes to near -/+1 but is more like -/+0.95 (while this is not an issue on the x-axis)

### Example code

```Python
from bokeh.io import output_notebook, output_file, show
from bokeh.models import Circle
from bokeh.plotting import figure

# Create the figure with an aspect ratio of 1
p = figure(width=500, height=500, x_range=(-1.2, 1.2), y_range=(-1.2, 1.2),
           tools='tap', title='Distorted Circle!', aspect_ratio=1, match_aspect=True)

# Plot the circle
circle = Circle(x=0, y=0, radius=1, fill_color='lightblue', line_color='black')
p.add_glyph(circle)

output_notebook()
show(p, match_aspect=True)
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/31241012/591f151c-6d88-48ec-8de0-3f4948a88899)

**Comment by bryevdv** [comment]
@aafshinfard as stated [in the docs](https://docs.bokeh.org/en/latest/docs/reference/plotting/figure.html#bokeh.plotting.figure.match_aspect) the `match_aspect` setting only applies when using auto-ranges:
> This setting only takes effect when there are two dataranges. This setting only sets the initial plot draw and subsequent resets. It is possible for tools (single axis zoom, unconstrained box zoom) to change the aspect ratio.

If you specify manual `x_range` and `y_range` ranges (as you have done above) then Bokeh will not override them, regardless of what that means for the aspect matching. Another way: you have asked for two mutually incompatible things. Which one you get is arbitrary, but you can only get one. Bokeh chooses to honor manual range values over a request to aspect-match.

**Comment by aafshinfard** [comment]
Thanks for the reply and the information.
The issue remains the same if I remove those features. We would still expect to see a perfect circle, but as the screenshot shows, the circle is "distorted". Any clues why that is happening?

**Comment by aafshinfard** [comment]
Thanks for the reply and the information @bryevdv 
The issue remains the same if I remove those features. We would still expect to see a perfect circle, but as the screenshot shows, the circle is "distorted". Any clues why that is happening?

```
p = figure(width=500, height=500, x_range=(-1.2, 1.2), y_range=(-1.2, 1.2),
           tools='tap', title='Distorted Circle!')
```

The issue goes away if I exclude `x_range` and `y_range`, but why is setting the range affecting the circle?

**Comment by bryevdv** [comment]
> The issue goes away if I exclude x_range and y_range, but why is setting the range affecting the circle?

@aafshinfard It's not affecting the circle. That is a ciecle, *in pixels*.  There are about a half dozen issues here that go into all the details, in case you want to search the tracker for "aspect ratio". I am not going to recount them all again here. I'll only slightly elaborate to say: aspect matching *works* by adjusting the range extents to *make* the "data space" and "pixel space"  aspect ratios match. Ergo: if you override with manual data ranges, then aspect matching *cannot work*. 

If you must specify manual ranges, then you should use a polygonal approximation to a circle, or perhaps an ellipse glyph, which will both "squish" when you force data range extents in a way that makes a 1-by-1 square in data space no longer be square in terms of actual pixels.
