### ISSUE TITLE
[BUG] Issue with adding DataTable to a new tab from a callback

### ISSUE THREAD

**Issue by xygyo77** [bokeh/bokeh#13264]
### Software versions

$ bokeh info
Python version      :  3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
IPython version     :  8.7.0
Tornado version     :  6.2
Bokeh version       :  3.2.0 and 3.1.0
BokehJS static path :  /home/akm/.local/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.15.90.1-akm-microsoft-standard-WSL2+-x86_64-with-glibc2.35

### Browser name and version

chrome 114.0.5735.199 (Official Build) (64bit),  edge 114.0.1823.79 (Official Build) (64bit)

### Expected behavior

**Moved here from Discourse (https://discourse.bokeh.org/t/issue-with-adding-datatable-to-a-new-tab-from-a-callback/10656).**

![initial_disp](https://github.com/bokeh/bokeh/assets/6880067/bb0177c2-41b4-492b-9807-93dbe81c4ffb)

I expect that clicking the 'Add Tab' button on the initial display screen will add a new tab containing both the same plots and data tables as the initial tab. I also expect that the display of the data table in the original tab will be retained.

### Observed behavior

![press-add-button](https://github.com/bokeh/bokeh/assets/6880067/244e5f86-21b1-4889-b584-0b919a2dc56e)
![press-new-tab](https://github.com/bokeh/bokeh/assets/6880067/0fe4e1ea-8324-47c5-83f7-8a76ec491738)

### Example code

```Python
from bokeh.plotting import figure, curdoc
from bokeh.layouts import column
from bokeh.models.widgets import DataTable, TableColumn, Button
from bokeh.models import Tabs, TabPanel, ColumnDataSource

def button_callback():
    # make graph and table
    source = ColumnDataSource(data=dict(x=[1, 2, 3], y=[4, 5, 6]))
    plot = figure(width=400, height=300)
    plot.line('x', 'y', source=source)

    columns = [
        TableColumn(field="x", title="X"),
        TableColumn(field="y", title="Y")
    ]
    data_table = DataTable(source=source, columns=columns, editable=True)
    # layout graph and table
    layout = column(plot, data_table)
    # add tab
    tab = TabPanel(child=layout, title="New Tab")
    tabs.tabs.append(tab)

# setup callback
button = Button(label="Add Tab")
button.on_click(button_callback)

# initial tab
source = ColumnDataSource(data=dict(x=[1, 2, 3], y=[4, 5, 6]))
plot = figure(width=400, height=300)
plot.line('x', 'y', source=source)
columns = [
    TableColumn(field="x", title="X"),
    TableColumn(field="y", title="Y")
]
data_table = DataTable(source=source, columns=columns, editable=True)

layout = column(plot, data_table)
initial_tab = TabPanel(child=layout, title="Initial Tab")
# create tab
tabs = Tabs(tabs=[initial_tab])
curdoc().add_root(column(button, tabs))
```

### Stack traceback or browser console output

**The following message is output to the console when the "Add Tab" button is pressed.**

![image](https://github.com/bokeh/bokeh/assets/6880067/1b6b6e5c-13dd-4813-87d2-a61403c0f89f)

**Comment by aaronmlevy** [comment]
This has been a persistent problem for me, too.
