### ISSUE TITLE
Typo in the reference guide [BUG] 

### ISSUE THREAD

**Issue by Azaya89** [bokeh/bokeh#13278]
### Software versions

Python version      :  3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.1+1.g5ad0156d.dirty
BokehJS static path :  /Users/mac/Documents/development/bokeh/src/bokeh/server/static
node.js version     :  v18.16.1
npm version         :  9.8.1
Operating system    :  macOS-13.2.1-arm64-arm-64bit

### Expected behavior

In the reference guide [here](https://docs.bokeh.org/en/latest/docs/reference/plotting/figure.html#bokeh.plotting.figure.scatter), there is a typographical error in the `scatter()` glyph, specifically in the `legend_field` parameter. 

It should say "The value of this parameter is the name of a column in the data source that should be used **for** the grouping.

The grouping is performed in JavaScript, at the **same time** the Bokeh content is rendered in the browser. If the data is subsequently updated, the legend will automatically re-group."

### Observed behavior

It says "The value of this parameter is the name of a column in the data source that should be used **or** the grouping.

The grouping is performed in JavaScript, at the **time time** the Bokeh content is rendered in the browser. If the data is subsequently updated, the legend will automatically re-group."

**Comment by mosc9575** [comment]
Thanks for pointing out the typos. I am working on some improvement in the documentation and will solves this in #13276, too. I closet his issue as a duplicate.
