### ISSUE TITLE
fix layout issues in docs

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13276]
In the docs there are sometime mistakes in the examples and some code blocks are quoted. This issues collects all this minor changes.

An example of not well formated docs can be seen below.

![grafik](https://github.com/bokeh/bokeh/assets/68053396/0365ab3c-fbab-4ce2-8214-120f55f4aa89)

**Comment by mosc9575** [comment]
There are some open issues:

- [x] ~~indented block in the function `fill_alpha` if `AlphaSpec` is inherited, see [property_mixins](https://docs.bokeh.org/en/latest/docs/reference/core/property_mixins.html#bokeh.core.property_mixins.FillProps.fill_alpha)
This could be solved with a `dedent()` call in `src/bokeh/core/property/dataspec.py`~~
- [x] ~~indented block in the function `fill_alpha` if `ColorSpec` is inherited, see [property_mixins](https://docs.bokeh.org/en/latest/docs/reference/core/property_mixins.html#bokeh.core.property_mixins.FillProps.fill_color)
This could be solved with a `dedent()` call in `src/bokeh/core/property/color.py`~~
- [x ] ~~indented blocks in [sphinxext.html](https://docs.bokeh.org/en/latest/docs/reference/sphinxext.html)
there are quite a few, for example [bokeh_color](https://docs.bokeh.org/en/latest/docs/reference/sphinxext.html#module-bokeh.sphinxext.bokeh_color), [bokeh_enmu](https://docs.bokeh.org/en/latest/docs/reference/sphinxext.html#module-bokeh.sphinxext.bokeh_enum), etc.~~
Today I think the cited blocks are quite good for an optical separation and there is nothing to change.
- [x] ~~non bolt example header in [formatters.html](https://docs.bokeh.org/en/latest/docs/reference/models/formatters.html#bokeh.models.CustomJSTickFormatter.code) and [transforms.html](https://docs.bokeh.org/en/latest/docs/reference/models/transforms.html#bokeh.models.CustomJSTransform.func)
I don't know if it matters but the header is slightly different to a normal example header in other docstrings with a thin horizontal gray line below the bolt word "Examples"~~
- [x] ~~wrong indented code block and wrong Keywords in [tile_providers](https://docs.bokeh.org/en/latest/docs/reference/tile_providers.html#module-bokeh.tile_providers)
This could be solved moving some text into the docstring of `get_provider()` and use `.. autofunction:: bokeh.tile_providers.get_provider`.~~

@bryevdv Cloud you please tell me what you think about the next steps? Which of the issues are important enough to be solved next?

**Comment by bryevdv** [comment]
@mosc9575 Those seem reasonable at a glance, it would be easier to evaluate a WIP PR with changes and screenshots though
