### ISSUE TITLE
[BUG] _pending_writes should be non-None when we have a document lock

### ISSUE THREAD

**Issue by mit10000** [bokeh/bokeh#13296]
### Software versions

Python version      :  3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.1.1
BokehJS static path :  /home/usr/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-4.15.0-142-generic-x86_64-with-glibc2.23

### Browser name and version

Firefox 88.0

### Jupyter notebook / Jupyter Lab version

4.4.0

### Expected behavior

can add a line to a plot in Bokeh app

### Observed behavior

error appears when try to add a line to a figure in a Bokeh app, in Jupyter notebook

### Example code

```Python
"""
Very similar to the Bokeh example in
https://github.com/bokeh/bokeh/blob/2.4.2/examples/howto/server_embed/notebook_embed.ipynb
with minor changes:
"""
import yaml

from bokeh.layouts import column
from bokeh.models import ColumnDataSource, Slider
from bokeh.plotting import figure
from bokeh.themes import Theme
from bokeh.io import show, output_notebook

from bokeh.sampledata.sea_surface_temperature import sea_surface_temperature

output_notebook()

df = sea_surface_temperature.copy()
source = ColumnDataSource(data=df)
plot = figure(x_axis_type='datetime', y_range=(0, 25),
                y_axis_label='Temperature (Celsius)',
                title="Sea Surface Temperature at 43.18, -70.43")
plot.line('time', 'temperature', source=source)

slider = Slider(start=0, end=30, value=0, step=1, title="Smoothing by N Days")

def bkapp(doc):
    def callback(attr, old, new):
        if new == 0:
            data = df
        else:
            data = df.rolling('{0}D'.format(new)).mean()
        source.data = ColumnDataSource.from_df(data)

    slider.on_change('value', callback)
    
    doc.add_root(column(slider, plot))

    doc.theme = Theme(json=yaml.load("""
        attrs:
            Figure:
                background_fill_color: "#DDDDDD"
                outline_line_color: white
                toolbar_location: above
                height: 500
                width: 800
            Grid:
                grid_line_dash: [6, 4]
                grid_line_color: white
    """, Loader=yaml.FullLoader))

show(bkapp) # notebook_url="http://localhost:8888" 

plot.line(df.index,[10.0]*19226,line_color='red',line_width=5)
```

### Stack traceback or browser console output

My whole purpose of the last line is to interactively add component to an existing plot in a Bokeh app.

The last line causes error:

BokehDeprecationWarning: "Use of 'Figure' as a key in Theme attributes" was deprecated in Bokeh 3.0.0 and will be removed, use "'figure' (lower-case) as a key" instead.

plot.line(df.index,[10.0]*19226,line_color='red',line_width=5)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[34], line 1
----> 1 plot.line(df.index,[10.0]*19226,line_color='red',line_width=5)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/plotting/_decorators.py:87, in glyph_method.<locals>.decorator.<locals>.wrapped(self, *args, **kwargs)
     85 if self.coordinates is not None:
     86     kwargs.setdefault("coordinates", self.coordinates)
---> 87 return create_renderer(glyphclass, self.plot, **kwargs)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/plotting/_renderer.py:127, in create_renderer(glyphclass, plot, **kwargs)
    117 muted_glyph = make_glyph(glyphclass, kwargs, muted_visuals)
    119 glyph_renderer = GlyphRenderer(
    120     glyph=glyph,
    121     nonselection_glyph=nonselection_glyph or "auto",
   (...)
    124     muted_glyph=muted_glyph or "auto",
    125     **renderer_kws)
--> 127 plot.renderers.append(glyph_renderer)
    129 if legend_kwarg:
    130     # It must be after the renderer is added because
    131     # if it creates a new `LegendItem`, the referenced
    132     # renderer must already be present.
    133     update_legend(plot, legend_kwarg, glyph_renderer)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/core/property/wrappers.py:138, in notify_owner.<locals>.wrapper(self, *args, **kwargs)
    136 old = self._saved_copy()
    137 result = func(self, *args, **kwargs)
--> 138 self._notify_owners(old)
    139 return result

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/core/property/wrappers.py:167, in PropertyValueContainer._notify_owners(self, old, hint)
    165 def _notify_owners(self, old: Any, hint: DocumentPatchedEvent | None = None) -> None:
    166     for (owner, descriptor) in self._owners:
--> 167         descriptor._notify_mutated(owner, old, hint=hint)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/core/property/descriptors.py:656, in PropertyDescriptor._notify_mutated(self, obj, old, hint)
    652 # re-validate because the contents of 'old' have changed,
    653 # in some cases this could give us a new object for the value
    654 value = self.property.prepare_value(obj, self.name, value, hint=hint)
--> 656 self._set(obj, old, value, hint=hint)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/core/property/descriptors.py:619, in PropertyDescriptor._set(self, obj, old, value, hint, setter)
    616     self._set_value(obj, value)
    618 # for notification purposes, "old" should be the logical old
--> 619 self._trigger(obj, old, value, hint=hint, setter=setter)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/core/property/descriptors.py:697, in PropertyDescriptor._trigger(self, obj, old, value, hint, setter)
    660 """ Unconditionally send a change event notification for the property.
    661 
    662 Args:
   (...)
    694 
    695 """
    696 if hasattr(obj, 'trigger'):
--> 697     obj.trigger(self.name, old, value, hint, setter)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/model/model.py:562, in Model.trigger(self, attr, old, new, hint, setter)
    560 # chain up to invoke callbacks
    561 descriptor = self.lookup(attr)
--> 562 super().trigger(descriptor.name, old, new, hint=hint, setter=setter)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/util/callback_manager.py:188, in PropertyCallbackManager.trigger(self, attr, old, new, hint, setter)
    186 if self.document is not None:
    187     from ..model import Model
--> 188     self.document.callbacks.notify_change(cast(Model, self), attr, old, new, hint, setter, invoke)
    189 else:
    190     invoke()

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/document/callbacks.py:249, in DocumentCallbackManager.notify_change(self, model, attr, old, new, hint, setter, callback_invoker)
    245         hint.setter = setter
    247     event = hint
--> 249 self.trigger_on_change(event)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/document/callbacks.py:413, in DocumentCallbackManager.trigger_on_change(self, event)
    411     for cb in self.change_callbacks():
    412         cb(event)
--> 413 invoke_with_curdoc(doc, invoke_callbacks)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/document/callbacks.py:443, in invoke_with_curdoc(doc, f)
    440 curdoc: Document|UnlockedDocumentProxy = UnlockedDocumentProxy(doc) if getattr(f, "nolock", False) else doc
    442 with patch_curdoc(curdoc):
--> 443     return f()

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/document/callbacks.py:412, in DocumentCallbackManager.trigger_on_change.<locals>.invoke_callbacks()
    410 def invoke_callbacks() -> None:
    411     for cb in self.change_callbacks():
--> 412         cb(event)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/document/callbacks.py:276, in DocumentCallbackManager.on_change_dispatch_to.<locals>.<lambda>(event)
    274 def on_change_dispatch_to(self, receiver: Any) -> None:
    275     if receiver not in self._change_callbacks:
--> 276         self._change_callbacks[receiver] = lambda event: event.dispatch(receiver)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/document/events.py:354, in ModelChangedEvent.dispatch(self, receiver)
    348 def dispatch(self, receiver: Any) -> None:
    349     ''' Dispatch handling of this event to a receiver.
    350 
    351     This method will invoke ``receiver._document_model_changed`` if it exists.
    352 
    353     '''
--> 354     super().dispatch(receiver)
    355     if hasattr(receiver, '_document_model_changed'):
    356         cast(DocumentModelChangedMixin, receiver)._document_model_changed(self)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/document/events.py:220, in DocumentPatchedEvent.dispatch(self, receiver)
    218 super().dispatch(receiver)
    219 if hasattr(receiver, '_document_patched'):
--> 220     cast(DocumentPatchedMixin, receiver)._document_patched(self)

File ~/anaconda3/envs/AvlVisual/lib/python3.10/site-packages/bokeh/server/session.py:246, in ServerSession._document_patched(self, event)
    243 may_suppress = event.setter is self
    245 if self._pending_writes is None:
--> 246     raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
    248 # TODO (havocp): our "change sync" protocol is flawed because if both
    249 # sides change the same attribute at the same time, they will each end
    250 # up with the state of the other and their final states will differ.
    251 for connection in self._subscribed_connections:

RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes

**Comment by bryevdv** [comment]
@mit10000 This is a usage issue. In the context of notebooks, *all* app document modifications must originate from within  the app function in one way or another. If you want to call `plot.line` after the app has rendered, that's fine but it has to happen from a call back that you set up from the start inside `bkapp`, e.g. to respond to a button click or any other Bokeh event. It is ***100% not permissible*** to modify the app document directly, from "outside" the app function. The reason for this is that Jupyter's intrinsic possibility of arbitrary, out-of-order cell execution makes it literally impossible to effectively reason about application state in full generality, unless things are encapsulated some way (i.e. inside the app function)

**Comment by bryevdv** [comment]
For completeness, I will mention that if you ***only*** need to "push"  changes to a plot programmatically after showing it, and not need any callbacks or communication from BokehJS back to Python code, then there a much older API called `push_notebook`:

https://github.com/bokeh/bokeh/tree/branch-3.3/examples/output/jupyter/push_notebook

 But `push_notebook` was originally developed on and old version of  classic notebook before jupyterlab was even conceived, nearly 10 years ago.  IMO it could be considered discouraged at this point.
