### ISSUE TITLE
[FEATURE] Inline widgets for data entry

### ISSUE THREAD

**Issue by jlstevens** [bokeh/bokeh#13291]
### Problem description

Bokeh is often used to build data analysis dashboards where extra widgets are added to interact with some model or data. Another common use case is to capture metadata or annotations: in these situations, the user wants to capture information about the data that they are viewing in a bokeh plot. Typical use cases might be to mark an unusual event on a timeseries or to mark a region-of-interest on a raster image.

Simply marking such a region is often not enough as the user needs to also capture what they want to say about the region they have marked. At the simplest level this can be freeform text e.g. 'The temperature really spiked at this time!' or 'Missing data due to an equipment failure' or 'Model output unstable for all input parameters in this region'. 

Right now, this can be achieved by having a separate text input widget in the dashboard (e.g. added using [panel](https://panel.holoviz.org/)) which captures the text input along with some region drawn on the plot. Of course, other types of data (not just freeform text) may need recording (e.g. int/float values, categorical data selected from a dropdown menu and so on). All these widgets need to be added to such an annotator dashboard.

There are a number of downsides to this (non-inline) approach:

1. This forces the user to start building a dashboard around the plot of interest. This may be done with Bokeh but also with other dashboarding tools which need to be learned.
2. As a result, the user will be forced to think about things such as widget layouts and the overall layout of the dashboard.
3. This approach is not compact, especially when there are additional widgets required  that are *not* about annotating the plot, confusing things.
4. This approach is not direct: users want to enter data right at the point of interest that they are looking at, directly on the plot (as opposed to finding the relevant data entry widgets elsewhere)
5. The widgets are either always present even when only viewing the data (visually noisy) or extra difficulties occur if trying to dynamically show and hide the widgets around the plot depending on whether data entry mode is enabled.

The feature request here is for a way to present inline (pop up) widgets on a plot for data entry. 

### Feature description

Here is a quick mockup of the sort of thing I have in mind:

<img width="50%" alt="image" src="https://github.com/bokeh/bokeh/assets/890576/0b739b72-65c5-4cb6-9785-f367678f7563">

While it would be wonderful to have all the sorts of widgets you can see [here](https://panel.holoviz.org/reference/index.html#widgets), I think even a basic set of widgets would be very useful. Here is what I would consider the minimal set, in priority order:

1. Text input widgets (optional extra features could include: autocomplete, rendering the text onto the plot, max text length, scrolling etc.)
2. Sliders for float and integer values
3. Dropdown menus
4. Buttons

In addition to each widget having a label, I think tooltip support is very important for discoverability.

The visibility of these widgets need to be easily toggled allowing easy data entry when required and hidden away otherwise. The entered data is made available server-side either when the widgets are changed by the user (e.g. text entered, a new dropdown option selected etc.) or when a 'Submit' button is pressed. This data needs to include enough context (position in the plot's data space, selected glyph, or whatever else) so that it is clear what the entered data is supposed to refer to.

In order to edit a previous submission, it will need to be possible to repopulate the widget bank with previous values so the user can make adjustments and resubmit the data.

### Potential alternatives

So far this has been solved by placing widgets around the plot in a dashboard as already described in the 'Problem description' section.

### Additional information

I'm leaving lots of technical aspects open for discussion. Here are some questions that come to mind:

1) Perhaps this is a type of layout that can hold any existing widget that simply appears as a popup over a plot?
2) Perhaps this is a type of tool? Maybe this expands out of the toolbar?
3) Or maybe this is a type of context menu? 
4) Is this necessarily tied to glyph selection? (Here I think that this should have that as an option but I also think freeform entry without selecting any glyph should be allowed).
5) Can the visibility of these widgets be controlled from the server-side?

To conclude, I think this would be an exciting and very useful feature and I'm excited to see discussion about it!

**Comment by jbednar** [comment]
Thanks, @jlstevens ! I'd add that our immediate use case is for [holonote](https://github.com/holoviz/holonote), which implements the persistence and display of annotations but currently leaves their input up to the user, who must do work in every individual app or dashboard to add appropriate controls and logic. A goal of this issue is to cover the majority of such use cases with a configurable Bokeh tool (assuming a positive answer to your question 2) that makes applying holonote (or any custom annotation support that someone may design) easy for an existing plot or application.

Personally, I'd swap widgets 2 and 3 in your first list; I think selecting a category ("ERROR", "DROPOUT", "ANOMALY", "MISSINGDATA", etc.) would be more common than having an integer or float value for the annotation, but maybe I'm not imagining the same applications as you are.

For 4, I do think that usually this tool would start with a Bokeh selection of some sort, and would then collect data to associate with that selection. But yes, if invoked without a selection then I guess users would be entering metadata about the overall set of data being displayed, rather than for a particular subset.

**Comment by jlstevens** [comment]
> Personally, I'd swap widgets 2 and 3 in your first list ...

Actually I agree, dropdowns are probably more important than sliders (though I would really hope to have both!)

> But yes, if invoked without a selection then I guess users would be entering metadata about the overall set of data being displayed, rather than for a particular subset.

If the menu has the concept of a position in data space, that would be some additional context e.g. if you know position of the data entry is made at is (x,y) then that itself is enough for making point annotations (e.g. spans or crosshairs). Then you wouldn't need to make the glyph first.

**Comment by jbednar** [comment]
Ah,ok. I guess for a good UI/UX, you could have a single tool that both creates a Tap or RangeSelect event and then immediately annotates it, without a separate selection previously existing. Sounds nice. And then if somehow the tap was outside the plot it could be annotating an axis or the entire dataset?
