### ISSUE TITLE
DateRangeSlider re-sizing

### ISSUE THREAD

**Issue by georgemarrow** [bokeh/bokeh#1329]
DateRangeSlider widget has its container width set to 0px on load, which causes the entire bar to collapse (the arrows if enabled are placed correctly though). Causing a resize/recomputation of the container width by adjusting browser window size does fix the rendering of the widget. 

I was not able to reproduce the issue with the stand-alone same version jQRangeSlider.

**Comment by mosesmc52** [comment]
Hi, 

I'm trying to get the DateRangeSlider to work. It doesn't appear to display.

**Comment by birdsarah** [comment]
@mosesmc52, it is currently broken I'm afraid: https://github.com/bokeh/bokeh/issues/2268

**Comment by ChangezKhan** [comment]
Any update on this, guys?

**Comment by mattpap** [comment]
This shouldn't be an issue since switch to nouislider in PR #6335.
