### ISSUE TITLE
[BUG] Zoom-out does not continue in other directions when hitting a single range bound

### ISSUE THREAD

**Issue by droumis** [bokeh/bokeh#13317]
### Software versions

Python version      :  3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.1
BokehJS static path :  /Users/droumis/opt/miniconda3/envs/neuro-eeg-viewer/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v20.4.0
npm version         :  9.7.2
Operating system    :  macOS-13.4.1-arm64-arm-64bit

### Expected behavior

Continue zooming out in other directions when hitting a single hard bound.

### Observed behavior

When zooming out on a plot that has explicit hard range bounds, the current behavior is that when the zoom window hits just one of the bounds, the zoom-out stops completely even though there is still space left to zoom out in the remaining directions.

### Example code

```Python
import numpy as np

from bokeh.layouts import column
from bokeh.models import ColumnDataSource, RangeTool
from bokeh.plotting import figure, show, output_notebook

output_notebook()

x_values = np.linspace(0, 3000, 3000)
y_values = np.cumsum(np.random.randn(3000)) + 50

source = ColumnDataSource(data=dict(x=x_values, y=y_values))

# Get the bounds for x and y axes
min_x = x_values.min()
max_x = x_values.max()
min_y = y_values.min()
max_y = y_values.max()

p = figure(height=300, width=800,
           x_range=(x_values[0], x_values[1500]),
           y_range=(min_y+30, max_y-30),
           x_axis_label='X',
           y_axis_label='Y')

# Set the bounds for x and y axes so we cannot pan/zoom outside the data limits
p.x_range.bounds = (min_x, max_x)
p.y_range.bounds = (min_y, max_y)

p.line('x', 'y', source=source)

show(p)
```

### Screenshots

It's a bit hard to see, but in this video I am showing how we are at the edge of the left bounded range and cannot pan more to the left. However, there is still space to pan in the other directions. When I start zooming out, I hit the left bound and the zoom does not continue in the other directions.

https://github.com/bokeh/bokeh/assets/6613202/b31ab474-0efb-4945-8945-d27c3ea87dc8

**Comment by bryevdv** [comment]
@droumis this is as intended, but is also configurable:

https://docs.bokeh.org/en/latest/docs/reference/models/tools.html#bokeh.models.WheelZoomTool.maintain_focus

**Comment by jbednar** [comment]
Great to hear that it's configurable! I certainly would not have expected `maintain_focus` to have that effect. Can anyone motivate what `focus` means in this context?  "If False, zooming can continue independently in any dimension that has not yet reached its bounds, even if that causes overall focus or aspect ratio to change." -- how would zooming change focus?

**Comment by bryevdv** [comment]
@jbednar "focus" in this context means the when scroll zooming, the data-space coordinate underneath the mouse will never change, which can happen if the tool is allowed to change the data-space aspect ratio. When this happens, it becomes impossible to "zoom out" on exactly the same point to get to the same place where you started. The motivation for this feature and the current default was multiple user complaints. `maintain_aspect` might have been a better choice but I don't recall anything else specific about the choice of property name at the time.

**Comment by jbednar** [comment]
Ok, thanks. Yes, `maintain_aspect` would have made it more findable by me, but no point in changing now!

**Comment by droumis** [comment]
@bryevdv 

It looks like there might still be a bug with `maintain_focus=False`. In the video below, when the left, top, and bottom bounds are hit, the wheel zoom no longer adjusts the right-ward range. Is this intended? I can open a new issue if it's too messy to re-open this one.

```python
from bokeh.models import Range1d, WheelZoomTool
from bokeh.plotting import figure, show

x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

p = figure(x_range=Range1d(bounds=(1, 5), start=1, end=2),
           y_range=Range1d(bounds=(2, 7), start=4, end=6.5),tools="reset,pan,")
p.line(x, y)
wheel_zoom = WheelZoomTool(maintain_focus=False) 
p.add_tools(wheel_zoom)
p.toolbar.active_scroll = wheel_zoom
show(p)
```

https://github.com/bokeh/bokeh/assets/6613202/83fb0dbd-4eb1-4f41-943b-a394d2eff92e

**Comment by bryevdv** [comment]
>  In the video below, when the left, top, and bottom bounds are hit, the wheel zoom no longer adjusts the right. Is this intended?

@droumis Are you saying that when the left, top, and bottom bounds are hit, and can thus no longer be updated, that the right should still continue to "zoom" somehow? That would by definition require ceasing to maintain focus. Maintaining focus means zooming consistently in all directions at once, so that the point under the cursor can stay the same. Once any bound is hit, continued zooming and maintaining focus become incompatible.

**Comment by droumis** [comment]
> Are you saying that when the left, top, and bottom bounds are hit, and can thus no longer be updated, that the right should still continue to "zoom" somehow?

Yes, exactly. My expectation was that `maintain_focus=False` would allow this behavior

**Comment by bryevdv** [comment]
@droumis apologies, I had the sense of your complaint reversed (usually a bug is "the thing doesn't work when it is *turned on*". Yes please make a new issue referencing maintain_focus in the title
