### ISSUE TITLE
Selenium deprecation warning because of log_path  

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13324]
### Software versions

Python version      :  3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.1
BokehJS static path :  /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v18.16.1
npm version         :  9.5.1
Operating system    :  Linux-6.4.6-76060406-generic-x86_64-with-glibc2.35

### Expected behavior

No warning emitted. 

### Observed behavior

Our CI is starting to emit this warning: 

```
 /usr/share/miniconda3/envs/test-environment/lib/python3.11/site-packages/bokeh/io/webdriver.py:69: DeprecationWarning: log_path has been deprecated, please use log_output
```

https://github.com/bokeh/bokeh/blob/df464aff6334cbf2f11a844768476b3b5e49db9f/src/bokeh/io/webdriver.py#L69

### Example code

```Python
Not needed.
```

**Comment by bryevdv** [comment]
@Hoxbro would you be able to submit a PR to update this?
