### ISSUE TITLE
[FEATURE] Allow zoom tools to scale subplots/subcoordinates

### ISSUE THREAD

**Issue by droumis** [bokeh/bokeh#13339]
### Problem description

The zoom tools operate only on the final target range on plots with subplots.

### Feature description

Allow the zoom tools to scale subcoordinate ranges on plots that contain subplots.

### Potential alternatives

None

### Additional information

<details>
<summary> Code </summary>

```
import numpy as np
from bokeh.plotting import figure
from bokeh.models import HoverTool, DataRange1d, FactorRange, Range1d, ColumnDataSource, WheelZoomTool, ZoomInTool, ZoomOutTool
from bokeh.io import show, output_notebook
from bokeh.core.properties import field
output_notebook()
np.random.seed(0)

n_channels = 10
n_seconds = 15
fs = 512
max_ch_disp = 5  # max channels to initially display
max_t_disp = 3 # max time in seconds to initially display

total_samples = n_seconds * fs
time = np.linspace(0, n_seconds, total_samples)
data = np.random.randn(n_channels, total_samples).cumsum(axis=1)
channels = [f'EEG {i}' for i in range(n_channels)]

hover = HoverTool(tooltips=[
    ("Channel", "$name"),
    ("Time", "$x s"),
    ("Amplitude", "$y µV"),
])

x_range = Range1d(start=time.min(), end=time.max())
#x_range = DataRange1d()
y_range = FactorRange(factors=channels)

p = figure(x_range=x_range, y_range=y_range, active_scroll="wheel_zoom", lod_threshold=None)
p.add_tools(hover)

source = ColumnDataSource(data=dict(time=time))
renderers = []

for i, channel in enumerate(channels):
    xy = p.subplot(
        x_source=p.x_range,
        y_source=Range1d(start=data[i].min(), end=data[i].max()),
        #y_source=DataRange1d(),
        x_target=p.x_range,
        y_target=Range1d(start=i, end=i + 1),
    )

    source.data[channel] = data[i]
    line = xy.line(field("time"), field(channel), color="black", source=source, name=channel)
    renderers.append(line)

p.add_tools(ZoomInTool(renderers=renderers))
p.add_tools(ZoomOutTool(renderers=renderers))

# p.add_tools(WheelZoomTool(renderers=renderers))

show(p)
```
</details>

<details>
<summary> Video of current behavior </summary>

https://github.com/bokeh/bokeh/assets/6613202/44eb977b-6229-4ee1-822c-b2714eec0f5a

</details>

<details>
<summary> Video of desired behavior (using different software) </summary>

https://github.com/bokeh/bokeh/assets/6613202/678f310f-39fb-48e2-956f-f1339f159c6f

</details>

**Comment by bryevdv** [comment]
`ZoomInTool` and `ZoomOutTool` both have a `dimension` property that defaults to both dimensions. How does configuring a single dimension currently interact with sub-plots?

**Comment by mattpap** [comment]
> How does configuring a single dimension currently interact with sub-plots?

Sub-coordinates are completely transparent to any zooming, panning, etc. This changes in PR #13345.
