### ISSUE TITLE
Tooltip for tab panels

### ISSUE THREAD

**Issue by heili77** [bokeh/bokeh#13349]
### Problem description

I want to describe the content of the panel with a tooltip

### Feature description

Add the tooltip feature to the tab panel like it is available for buttons.

### Potential alternatives

According to the discussion there are no workarounds https://discourse.bokeh.org/t/how-to-add-tooltips-to-tabpanels/10783/2

### Additional information

https://discourse.bokeh.org/t/how-to-add-tooltips-to-tabpanels/10783/2

**Comment by n-taylor** [comment]
I'm beginning work on this issue.
