### ISSUE TITLE
[BUG] can not use with macbook m2max

### ISSUE THREAD

**Issue by bkcarlos** [bokeh/bokeh#13358]
### Software versions

Python version      :  3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
IPython version     :  (not installed)
Tornado version     :  6.3.2
Bokeh version       :  3.2.2
BokehJS static path :  /Users/bkcarlos/miniconda3/envs/python_tools/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v16.20.2
npm version         :  8.19.4
Operating system    :  macOS-13.5.1-arm64-arm-64bit

### Browser name and version

Google Chrome 116.0.5845.140（正式版本） (arm64)

### Expected behavior

run and write a html file

### Observed behavior

Traceback (most recent call last):
  File "/Users/bkcarlos/code/aitools/python_tools/bokeh/bokeh.py", line 1, in <module>
    from bokeh.plotting import figure, show
  File "/Users/bkcarlos/code/aitools/python_tools/bokeh/bokeh.py", line 1, in <module>
    from bokeh.plotting import figure, show
ModuleNotFoundError: No module named 'bokeh.plotting'; 'bokeh' is not a package

### Example code

```Python
from bokeh.plotting import figure, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# create a new plot with a title and axis labels
p = figure(title="Simple line example", x_axis_label="x", y_axis_label="y")

# add a line renderer with legend and line thickness
p.line(x, y, legend_label="Temp.", line_width=2)

# show the results
show(p)
```

### Stack traceback or browser console output

```
packages in environment at /Users/bkcarlos/miniconda3/envs/python_tools:
Name                    Version                   Build  Channel
blas                      1.0                    openblas  
bokeh                     3.2.2                      py_0    bokeh
bottleneck                1.3.5           py310h96f19d2_0  
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2023.05.30           hca03da5_0  
contourpy                 1.0.5           py310h525c30c_0  
freetype                  2.12.1               h1192e45_0  
giflib                    5.2.1                h80987f9_3  
jinja2                    3.1.2           py310hca03da5_0  
jpeg                      9e                   h80987f9_1  
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_0  
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libtiff                   4.5.0                h313beb8_2  
libwebp                   1.2.4                ha3663a8_1  
libwebp-base              1.2.4                h80987f9_1  
llvm-openmp               14.0.6               hc6e5704_0  
lz4-c                     1.9.4                h313beb8_0  
markupsafe                2.1.1           py310h1a28f6b_0  
ncurses                   6.4                  h313beb8_0  
numexpr                   2.8.4           py310hecc3335_1  
numpy                     1.25.2          py310h3b2db8e_0  
numpy-base                1.25.2          py310ha9811e2_0  
openssl                   3.0.10               h1a28f6b_2  
packaging                 23.0            py310hca03da5_0  
pandas                    2.0.3           py310h46d7db6_0  
pillow                    9.4.0           py310h313beb8_0  
pip                       23.2.1          py310hca03da5_0  
python                    3.10.12              hb885b13_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
pytz                      2022.7          py310hca03da5_0  
pyyaml                    6.0             py310h80987f9_1  
readline                  8.2                  h1a28f6b_0  
setuptools                68.0.0          py310hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h80987f9_0  
tk                        8.6.12               hb8d0fd4_0  
tornado                   6.3.2           py310h80987f9_0  
tzdata                    2023c                h04d1e81_0  
wheel                     0.38.4          py310hca03da5_0  
xyzservices               2022.9.0        py310hca03da5_1  
xz                        5.4.2                h80987f9_0  
yaml                      0.2.5                h1a28f6b_0  
zlib                      1.2.13               h5a0b063_0  
zstd                      1.5.5                hd90d995_0  
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/12768384/2f0a7cf2-100e-4349-a270-89231cf706e2)

**Comment by bryevdv** [comment]
@bkcarlos lots of folks use Bokeh on MX Macs. Looking at the info above, it shows different conda envs in the traceback than in the package list. I am nearly 100% sure you just have a path/env mixup, which is the most common explanation for an import error on any platform. 

Edit: also two different envs in the image, `python_tools` vs `aitools`. (Aside: please do not post pictures of text, instead just post a copy of the actual text in a code block. Pictures of text are not accessible or copy-pasteable)

**Comment by bryevdv** [comment]
Adding `NEEDS MORE INFO` @bkcarlos please do some investigation on your end to verify whether or not this is a path/env problem, and report back. (Otherwise I will close as un-actionable in one week)

**Comment by bkcarlos** [comment]
> @bkcarlos lots of folks use Bokeh on MX Macs. Looking at the info above, it shows different conda envs in the traceback than in the package list. I am nearly 100% sure you just have a path/env mixup, which is the most common explanation for an import error on any platform.
> 
> Edit: also two different envs in the image, `python_tools` vs `aitools`. (Aside: please do not post pictures of text, instead just post a copy of the actual text in a code block. Pictures of text are not accessible or copy-pasteable)

python_tools is a conda env name,aitools is folder。i know it maybe a path/env problem. remove and rebuild the conda env and problem still exists. copy code in pythen shell it work, but run 'python boken/boken.py' is not work.

more info:
(python_tools) ➜  python_tools git:(fsm_tools) ✗ conda env list
# conda environments:
#
base                     /Users/bkcarlos/miniconda3
chatglm2                 /Users/bkcarlos/miniconda3/envs/chatglm2
llamacpp                 /Users/bkcarlos/miniconda3/envs/llamacpp
python_tools          *  /Users/bkcarlos/miniconda3/envs/python_tools
qwen                     /Users/bkcarlos/miniconda3/envs/qwen

(python_tools) ➜  python_tools git:(fsm_tools) ✗ pwd           
/Users/bkcarlos/code/aitools/python_tools
(python_tools) ➜  python_tools git:(fsm_tools) ✗

**Comment by bkcarlos** [comment]
I see my problem, I shouldn't used bokeh as my filename, thanks!
