### ISSUE TITLE
[BUG] Inconsistent handling of background and border fill alpha

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#13362]
### Software versions

Python version      :  3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.3.0.dev1+43.g310cb2cb
BokehJS static path :  /Users/iant/github/bokeh/src/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  macOS-13.4-arm64-arm-64bit

### Expected behavior

If you use fractional figure `background_fill_alpha` and `border_fill_alpha` I expect both canvas and SVG backends to look similar.

### Observed behavior

Color mixing is different for canvas and SVG backends.

### Example code

```Python
from bokeh.models import GlobalInlineStyleSheet
from bokeh.plotting import figure, row, show

stylesheet = GlobalInlineStyleSheet(css=".bk-Row { background-color: lightgreen; }")

ps = []
for backend in ('canvas', 'svg'):
    p = figure(
        width=250, height=250, title=backend, output_backend=backend,
        stylesheets=[stylesheet]
    )
    p.line(x=[0, 1], y=[0, 1], line_color="black", line_width=8)
    ps.append(p)

    p.background_fill_alpha = 0.25
    p.background_fill_color = "red"
    p.border_fill_alpha = 0.25
    p.border_fill_color = "blue"

show(row(ps))
```

### Screenshots

<img width="497" alt="Screenshot 2023-09-04 at 11 51 46" src="https://github.com/bokeh/bokeh/assets/580326/ccc34434-ede4-4d43-9494-6aa81a7e5afc">

**Comment by mattpap** [comment]
> `stylesheet = GlobalInlineStyleSheet(css=".bk-Row { background-color: lightgreen; }")`

A more appropriate approach for this setup would be this:
```ts
stylesheet = InlineStyleSheet(css=":host { background-color: lightgreen; }")
```
I'm guessing that using a CSS class instead of `:host` pseudo selector resulted in the global stylesheet.
