### ISSUE TITLE
[BUG] Problems running `bokeh serve` in development mode

### ISSUE THREAD

**Issue by axil** [bokeh/bokeh#13371]
### Software versions

Python version      :  3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.15.0
Tornado version     :  6.3.3
Bokeh version       :  3.2.2
BokehJS static path :  C:\Documents\python\visgb\webserver\env\lib\site-packages\bokeh\server\static
node.js version     :  v18.17.1
npm version         :  9.6.7
Operating system    :  Windows-10-10.0.19045-SP0

### Expected behavior

For me,

```
bokeh.exe serve --dev myapp.py
```
results in

```
ERROR: list index out of range
```

which bails out immediately with no further details or any clues of how to debug it

and 

```
bokeh.exe serve --dev --show myapp.py
```
(despite being discouraged [here](https://discourse.bokeh.org/t/prevent-hot-reload-with-dev-to-open-a-new-browser-tab-at-every-save/10681)) manages to start the app but then after the file is modified it breaks with equally useless

```
Error while finding module specification for '__main__' (ValueError: __main__.__spec__ is None)
```

### Observed behavior

Described above.

### Example code

```Python
I'm using myapp from the `bokeh serve` [tutorial](https://docs.bokeh.org/en/latest/docs/user_guide/server/app.html)
```

**Comment by mattpap** [comment]
Seems to be windows specific. For the sake of completeness can you try `python -m bokeh` instead of `bokeh.exe` with the same arguments as before?

**Comment by axil** [comment]
Same story. 
```
C:\Documents\python\visgb\webserver>bokeh serve --dev myapp3.py
ERROR: list index out of range

C:\Documents\python\visgb\webserver>python -mbokeh serve --dev myapp3.py
ERROR: list index out of range
```

Is there any kind of 'verbose=True' flag to help diagnose the problem?

**Comment by mattpap** [comment]
If I located the place where the exception is captured correctly, then yes, try running the command like this `BOKEH_DEV=true python -m bokeh ...`  (or can be `bokeh.exe`) (whatever is the windows equivalent for setting environmental variables). Note the environmental variable `BOKEH_DEV` and command line argument `--dev` do different things.

**Comment by bryevdv** [comment]
@axil will you be able to report results with `BOKEH_DEV=true` set?

**Comment by bryevdv** [comment]
Going to close for now for lack of response. We can re-open if more information is made available
