### ISSUE TITLE
[BUG] The push_notebook function has no effect when running 

### ISSUE THREAD

**Issue by WheatMaThink** [bokeh/bokeh#13373]
### Software versions

Python version      :  3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:23:25) 
IPython version     :  8.15.0
Tornado version     :  6.3.3
Bokeh version       :  3.2.2
BokehJS static path :  /python3.9/site-packages/bokeh/server/static
node.js version     :  v16.17.0
npm version         :  8.19.2
Operating system    :  macOS-10.15.7-x86_64-i386-64bit

### Jupyter notebook / Jupyter Lab version

 python -m jupyter lab --version    4.0.5

### Expected behavior

run examples:

### Observed behavior

The displayed image is unresponsive

![image](https://github.com/bokeh/bokeh/assets/8164911/fa619343-37d5-4419-b48b-3dc641f420b0)

### Example code

```Python
https://github.com/bokeh/bokeh/blob/3.2.2/examples/output/jupyter/push_notebook/Continuous%20Updating.ipynb
```

**Comment by bryevdv** [comment]
@WheatMaThink do you have the `jupyter_bokeh` extension installed? Also are there any errors or warnings in the browser JS console log?

**Comment by WheatMaThink** [comment]
It's my problem. I really need to install pip install jupyter_bokeh
