### ISSUE TITLE
ColumnDataSource.del_rows

### ISSUE THREAD

**Issue by dg-pb** [bokeh/bokeh#13383]
### Problem description

It is an attempt to re-open https://github.com/bokeh/bokeh/issues/7491

```python
cds = ColumnDataSource
```

has convenient methods to make updates efficiently:
```python
cds.patch      # replace selected rows
cds.stream    # append rows
```
what I think is missing is ability to efficiently remove rows

In https://github.com/bokeh/bokeh/issues/7491 it was said that "so removing a row is likely to be somewhat expensive". Is it actually so? Doesn't `cds.stream` recreate arrays, given they are growing larger in size?

### Feature description

```python
cds = ColumnDataSource(data={'x': [[0, 1, 2, 3]]})
cds.del_rows({'x': (0, slice(0, 2))})
print(cds.data['x'])    # [[2, 3]]
```

### Potential alternatives

I have thought about using `patch` to set values to nans, so that they are not plotted and tracking their location, so that when I append data again, I refill those nans first. But this is a very messy solution.

**Comment by philippjfr** [comment]
I'd love to see this as I have multiple use cases for it in Panel, e.g. to remove rows in a table..

>I have thought about using patch to set values to nans, so that they are not plotted and tracking their location, so that when I append data again, I refill those nans first. But this is a very messy solution.

Also, at least in some cases, such as lines, NaNs have special semantics causing it to render separate lines so this isn't an adequate solution.

**Comment by muendlein** [comment]
I am not entirely sure about your use case but are you aware of CDSView as a way to filter the data?
https://docs.bokeh.org/en/latest/docs/user_guide/basic/data.html#filtering-data

**Comment by dg-pb** [comment]
Thank you, was not aware of it.

My use case is as follows. I run procedure, which draws glyphs. I update them in real time. From time to time I need to press "undo" and remove a number of previously drawn glyphs, then continue procedure with different parameters. The data load of imaging is high compared to data generation procedure and redrawing whole data is not an option.

The problem is that memory can be an issue due to data-load, I would much rather be able to remove, rather than filter out. It seems much cleaner from management perspective too.

**Comment by bryevdv** [comment]
At the time of the OP I'm not sure custom protocol events for patch and stream existed. Without a custom event syncing would require sending the entire CDS every time. I'm not opposed if anyone wants to add this API with a new custom protocol event for efficiency.

**Comment by dg-pb** [comment]
It would be great if someone with a better knowledge of the library than me saw worth in doing it. My JavaScript is not that great also. Otherwise, I might come back to this once I am done with my current project.

**Comment by bryevdv** [comment]
I am closing this in favor of 

* https://github.com/bokeh/bokeh/issues/7988

Assuming either get's worked on, it would really only make sense to implement insert and delete at the same time in one PR.
