### ISSUE TITLE
Unable to clone models with readonly properties

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13389]
```py
In [1]: from bokeh.models import *

In [2]: source = ColumnDataSource()

In [3]: source.clone()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 source.clone()

File ~/repo/bokeh/src/bokeh/core/has_props.py:754, in HasProps.clone(self)
    747 ''' Duplicate a HasProps object.
    748 
    749 This creates a shallow clone of the original model, i.e. any
    750 mutable containers or child models will not be duplicated.
    751 
    752 '''
    753 attrs = self.properties_with_values(include_defaults=False, include_undefined=True)
--> 754 return self.__class__(**{key: val for key, val in attrs.items() if val is not Undefined})

File ~/repo/bokeh/src/bokeh/models/sources.py:235, in ColumnDataSource.__init__(self, *args, **kwargs)
    233     else:
    234         raise ValueError(f"expected a dict or pandas.DataFrame, got {raw_data}")
--> 235 super().__init__(**kwargs)
    236 self.data.update(raw_data)

File ~/repo/bokeh/src/bokeh/models/sources.py:118, in ColumnarDataSource.__init__(self, *args, **kwargs)
    117 def __init__(self, *args, **kwargs) -> None:
--> 118     super().__init__(*args, **kwargs)

File ~/repo/bokeh/src/bokeh/models/sources.py:101, in DataSource.__init__(self, *args, **kwargs)
    100 def __init__(self, *args, **kwargs) -> None:
--> 101     super().__init__(*args, **kwargs)

File ~/repo/bokeh/src/bokeh/model/model.py:110, in Model.__init__(self, *args, **kwargs)
    107 if "id" in kwargs:
    108     raise ValueError("initializing 'id' is not allowed")
--> 110 super().__init__(**kwargs)
    111 default_theme.apply_to_model(self)

File ~/repo/bokeh/src/bokeh/core/has_props.py:302, in HasProps.__init__(self, **properties)
    300     if value is Undefined or value is Intrinsic:
    301         continue
--> 302     setattr(self, name, value)
    304 initialized = set(properties.keys())
    305 for name in self.properties(_with_props=True): # avoid set[] for deterministic behavior

File ~/repo/bokeh/src/bokeh/core/has_props.py:334, in HasProps.__setattr__(self, name, value)
    332 properties = self.properties(_with_props=True)
    333 if name in properties:
--> 334     return super().__setattr__(name, value)
    336 descriptor = getattr(self.__class__, name, None)
    337 if isinstance(descriptor, property): # Python property

File ~/repo/bokeh/src/bokeh/core/property/descriptors.py:329, in PropertyDescriptor.__set__(self, obj, value, setter)
    327 if self.property.readonly:
    328     class_name = obj.__class__.__name__
--> 329     raise RuntimeError(f"{class_name}.{self.name} is a readonly property")
    331 value = self.property.prepare_value(obj, self.name, value)
    332 old = self._get(obj)

RuntimeError: ColumnDataSource.selected is a readonly property
```

**Comment by swdmartinez** [comment]
Can I be assigned this problem? I want to try to fix it!

**Comment by ianthomas23** [comment]
@UFCarlosMartinez We don't assign issues to people. If there not an existing PR to fix it then feel free to work on it.

**Comment by daydin** [comment]
~~I think I have a fix for this, but don't seem to have permission to push?~~

yes I need a fork! sorry. I will get on it.

**Comment by bryevdv** [comment]
@daydin only members of @bokeh/core can push directly to this repo. You will need to fork your own copy of the repo and push a branch to your fork, which you can then use to open a Pull Request here for (PRs from forks is standard procedure for most projects IME)

**Comment by daydin** [comment]
https://github.com/bokeh/bokeh/pull/13438

let's see if I broke anything.

**Comment by Allikooo** [comment]
> ```py
> 
> In [1]: from bokeh.models import *
> 
> 
> 
> In [2]: source = ColumnDataSource()
> 
> 
> 
> In [3]: source.clone()
> 
> ---------------------------------------------------------------------------
> 
> RuntimeError                              Traceback (most recent call last)
> 
> Cell In[3], line 1
> 
> ----> 1 source.clone()
> 
> 
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:754, in HasProps.clone(self)
> 
>     747 ''' Duplicate a HasProps object.
> 
>     748 
> 
>     749 This creates a shallow clone of the original model, i.e. any
> 
>     750 mutable containers or child models will not be duplicated.
> 
>     751 
> 
>     752 '''
> 
>     753 attrs = self.properties_with_values(include_defaults=False, include_undefined=True)
> 
> --> 754 return self.__class__(**{key: val for key, val in attrs.items() if val is not Undefined})
> 
> 
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:235, in ColumnDataSource.__init__(self, *args, **kwargs)
> 
>     233     else:
> 
>     234         raise ValueError(f"expected a dict or pandas.DataFrame, got {raw_data}")
> 
> --> 235 super().__init__(**kwargs)
> 
>     236 self.data.update(raw_data)
> 
> 
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:118, in ColumnarDataSource.__init__(self, *args, **kwargs)
> 
>     117 def __init__(self, *args, **kwargs) -> None:
> 
> --> 118     super().__init__(*args, **kwargs)
> 
> 
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:101, in DataSource.__init__(self, *args, **kwargs)
> 
>     100 def __init__(self, *args, **kwargs) -> None:
> 
> --> 101     super().__init__(*args, **kwargs)
> 
> 
> 
> File ~/repo/bokeh/src/bokeh/model/model.py:110, in Model.__init__(self, *args, **kwargs)
> 
>     107 if "id" in kwargs:
> 
>     108     raise ValueError("initializing 'id' is not allowed")
> 
> --> 110 super().__init__(**kwargs)
> 
>     111 default_theme.apply_to_model(self)
> 
> 
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:302, in HasProps.__init__(self, **properties)
> 
>     300     if value is Undefined or value is Intrinsic:
> 
>     301         continue
> 
> --> 302     setattr(self, name, value)
> 
>     304 initialized = set(properties.keys())
> 
>     305 for name in self.properties(_with_props=True): # avoid set[] for deterministic behavior
> 
> 
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:334, in HasProps.__setattr__(self, name, value)
> 
>     332 properties = self.properties(_with_props=True)
> 
>     333 if name in properties:
> 
> --> 334     return super().__setattr__(name, value)
> 
>     336 descriptor = getattr(self.__class__, name, None)
> 
>     337 if isinstance(descriptor, property): # Python property
> 
> 
> 
> File ~/repo/bokeh/src/bokeh/core/property/descriptors.py:329, in PropertyDescriptor.__set__(self, obj, value, setter)
> 
>     327 if self.property.readonly:
> 
>     328     class_name = obj.__class__.__name__
> 
> --> 329     raise RuntimeError(f"{class_name}.{self.name} is a readonly property")
> 
>     331 value = self.property.prepare_value(obj, self.name, value)
> 
>     332 old = self._get(obj)
> 
> 
> 
> RuntimeError: ColumnDataSource.selected is a readonly property
> 
> ```

**Comment by Allikkoo1** [comment]
> ```python
> In [1]: from bokeh.models import *
> 
> In [2]: source = ColumnDataSource()
> 
> In [3]: source.clone()
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Cell In[3], line 1
> ----> 1 source.clone()
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:754, in HasProps.clone(self)
>     747 ''' Duplicate a HasProps object.
>     748 
>     749 This creates a shallow clone of the original model, i.e. any
>     750 mutable containers or child models will not be duplicated.
>     751 
>     752 '''
>     753 attrs = self.properties_with_values(include_defaults=False, include_undefined=True)
> --> 754 return self.__class__(**{key: val for key, val in attrs.items() if val is not Undefined})
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:235, in ColumnDataSource.__init__(self, *args, **kwargs)
>     233     else:
>     234         raise ValueError(f"expected a dict or pandas.DataFrame, got {raw_data}")
> --> 235 super().__init__(**kwargs)
>     236 self.data.update(raw_data)
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:118, in ColumnarDataSource.__init__(self, *args, **kwargs)
>     117 def __init__(self, *args, **kwargs) -> None:
> --> 118     super().__init__(*args, **kwargs)
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:101, in DataSource.__init__(self, *args, **kwargs)
>     100 def __init__(self, *args, **kwargs) -> None:
> --> 101     super().__init__(*args, **kwargs)
> 
> File ~/repo/bokeh/src/bokeh/model/model.py:110, in Model.__init__(self, *args, **kwargs)
>     107 if "id" in kwargs:
>     108     raise ValueError("initializing 'id' is not allowed")
> --> 110 super().__init__(**kwargs)
>     111 default_theme.apply_to_model(self)
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:302, in HasProps.__init__(self, **properties)
>     300     if value is Undefined or value is Intrinsic:
>     301         continue
> --> 302     setattr(self, name, value)
>     304 initialized = set(properties.keys())
>     305 for name in self.properties(_with_props=True): # avoid set[] for deterministic behavior
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:334, in HasProps.__setattr__(self, name, value)
>     332 properties = self.properties(_with_props=True)
>     333 if name in properties:
> --> 334     return super().__setattr__(name, value)
>     336 descriptor = getattr(self.__class__, name, None)
>     337 if isinstance(descriptor, property): # Python property
> 
> File ~/repo/bokeh/src/bokeh/core/property/descriptors.py:329, in PropertyDescriptor.__set__(self, obj, value, setter)
>     327 if self.property.readonly:
>     328     class_name = obj.__class__.__name__
> --> 329     raise RuntimeError(f"{class_name}.{self.name} is a readonly property")
>     331 value = self.property.prepare_value(obj, self.name, value)
>     332 old = self._get(obj)
> 
> RuntimeError: ColumnDataSource.selected is a readonly property
> ```

**Comment by Allikkoo1** [comment]
https://github.com/bokeh/bokeh/issues/13389#issue-1905666013

**Comment by Allikkoo1** [comment]
> ```python
> In [1]: from bokeh.models import *
> 
> In [2]: source = ColumnDataSource()
> 
> In [3]: source.clone()
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Cell In[3], line 1
> ----> 1 source.clone()
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:754, in HasProps.clone(self)
>     747 ''' Duplicate a HasProps object.
>     748 
>     749 This creates a shallow clone of the original model, i.e. any
>     750 mutable containers or child models will not be duplicated.
>     751 
>     752 '''
>     753 attrs = self.properties_with_values(include_defaults=False, include_undefined=True)
> --> 754 return self.__class__(**{key: val for key, val in attrs.items() if val is not Undefined})
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:235, in ColumnDataSource.__init__(self, *args, **kwargs)
>     233     else:
>     234         raise ValueError(f"expected a dict or pandas.DataFrame, got {raw_data}")
> --> 235 super().__init__(**kwargs)
>     236 self.data.update(raw_data)
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:118, in ColumnarDataSource.__init__(self, *args, **kwargs)
>     117 def __init__(self, *args, **kwargs) -> None:
> --> 118     super().__init__(*args, **kwargs)
> 
> File ~/repo/bokeh/src/bokeh/models/sources.py:101, in DataSource.__init__(self, *args, **kwargs)
>     100 def __init__(self, *args, **kwargs) -> None:
> --> 101     super().__init__(*args, **kwargs)
> 
> File ~/repo/bokeh/src/bokeh/model/model.py:110, in Model.__init__(self, *args, **kwargs)
>     107 if "id" in kwargs:
>     108     raise ValueError("initializing 'id' is not allowed")
> --> 110 super().__init__(**kwargs)
>     111 default_theme.apply_to_model(self)
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:302, in HasProps.__init__(self, **properties)
>     300     if value is Undefined or value is Intrinsic:
>     301         continue
> --> 302     setattr(self, name, value)
>     304 initialized = set(properties.keys())
>     305 for name in self.properties(_with_props=True): # avoid set[] for deterministic behavior
> 
> File ~/repo/bokeh/src/bokeh/core/has_props.py:334, in HasProps.__setattr__(self, name, value)
>     332 properties = self.properties(_with_props=True)
>     333 if name in properties:
> --> 334     return super().__setattr__(name, value)
>     336 descriptor = getattr(self.__class__, name, None)
>     337 if isinstance(descriptor, property): # Python property
> 
> File ~/repo/bokeh/src/bokeh/core/property/descriptors.py:329, in PropertyDescriptor.__set__(self, obj, value, setter)
>     327 if self.property.readonly:
>     328     class_name = obj.__class__.__name__
> --> 329     raise RuntimeError(f"{class_name}.{self.name} is a readonly property")
>     331 value = self.property.prepare_value(obj, self.name, value)
>     332 old = self._get(obj)
> 
> RuntimeError: ColumnDataSource.selected is a readonly property
> ```

**Comment by bryevdv** [comment]
I have deleted all the duplicate quote comments with no context whatsoever. @Allikkoo1 if you need to say something please open a coherent new issue with full details.
