### ISSUE TITLE
[FEATURE] Improving the "Deployment scenario" section of the user guide

### ISSUE THREAD

**Issue by wswope-etiometry** [bokeh/bokeh#13387]
### Problem description

This is a tracking and feedback issue for a documentation PR that I'm planning to submit. 

Currently, the "Deployment scenario" section of the user guide does not cover the `server_document` and `server_session` methods used to embed Bokeh server views into other web applications.

Additionally, my naive understanding is that BokehJS currently does not forward Authorization headers when sending the initial HTTP(S) request to set up its websocket connection to Bokeh server. If this is correct, it would be extremely helpful to note that Bokeh server's websocket endpoint must be exempted by auth modules implemented per the "Authentication" section of the "Deployment scenario" page. (I'm not much of a frontend dev and I have limited experience with websockets - apologies if I'm off-base here.)

### Feature description

I have written a documentation subsection covering the two embedding methods mentioned above.

If anyone has bandwidth or past experience to confirm the websocket + auth module issue in the next few days, I will include a few lines regarding that limitation in the PR linked to this issue - otherwise, I'll set it aside for now. The most relevant sections of the Bokeh code are under `bokehjs/src/lib/client`, which appear to call out to this websocket library: https://github.com/websockets/ws/.

### Potential alternatives

n/a

### Additional information

Original discourse thread here: https://discourse.bokeh.org/t/improving-the-bokeh-server-deployment-scenario-section-of-the-user-guide/10852.

**Comment by bryevdv** [comment]
Thanks @wswope-etiometry! Just noting there is some existing docs for `server_document` and `server_session` under the ouptut chapter of the User Guide:

https://docs.bokeh.org/en/latest/docs/user_guide/output/embed.html#bokeh-applications

I think it's fine for there to be reinforcement in multiple places or for different sections to emphasize different points of view, elaborate on different areas, etc. I just wanted to make sure to keep those existing sections in mind and add any appropriate cross links or references that make sense between them.

**Comment by wswope-etiometry** [comment]
Oh wonderful! Can't believe I didn't find that.

I'll be sure to include a cross-link - thank you for the note!
