### ISSUE TITLE
Release build fails with `FileNotFoundError`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13400]
This is a side-effect of PR #13319:
```py
    Traceback (most recent call last):
      File "/usr/share/miniconda3/envs/bk-release-build/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
        exec(self._code, module.__dict__)
      File "/home/runner/work/bokeh/bokeh/examples/basic/annotations/scale_bar_image.py", line 20, in <module>
        with open("assets/pollen.png", "rb") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'assets/pollen.png'
```

**Comment by mattpap** [comment]
I'm not sure what's the difference between building docs in PRs' CI, where it builds fine, and release CI.

**Comment by bryevdv** [comment]
They seen pretty similar:

https://github.com/bokeh/bokeh/blob/96546ee6bfd68f660496924e71fd24e06afa38c4/release/build.py#L69-L76

vs 

https://github.com/bokeh/bokeh/blob/96546ee6bfd68f660496924e71fd24e06afa38c4/scripts/ci/build_docs.sh#L5-L7

I guess the release build does an additional `make clean` but I don't see how that's relevant, since it would not affect the examples dir tree.

**Comment by bryevdv** [comment]
Oh, the `make clean` does
```
rm -rf source/docs/examples/*
```
Is this example under the `docs` tree, not under top-level `examples`?

Edit: I guess not, I am at a loss for now.

**Comment by bryevdv** [comment]
That said, the thing to do in any case is generate a more robust path based off `__file__` or similar, since we can't control where users might actually run from

**Comment by mattpap** [comment]
I should have run this in the first place:
```
$ python examples/basic/annotations/scale_bar_image.py 
Traceback (most recent call last):
  File "/home/anaconda/repo/bokeh/examples/basic/annotations/scale_bar_image.py", line 20, in <module>
    with open("assets/pollen.png", "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'assets/pollen.png'
```
Then it would have been clear it's a missing `__file__` in asset  resolution.
