### ISSUE TITLE
Split up _sri.json

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13430]
The monolithic `_sri.json` file is starting to get a bit large and unwieldy. Additionally the time to load a file with one set of hashes vs all of them is actually starting to diverge:
```python
In [4]: %timeit json.load(open("src/bokeh/_sri.json"))
268 µs ± 2.65 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [5]: %timeit json.load(open("src/bokeh/_sri.json"))  # trimmed to single version
33.5 µs ± 965 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
We currently load the hashes any time CDN urls are requested in a full version, whether the hashes are ever used or not:
```python
    if is_full_release(version): # TODO: TypeGuard?
        assert version is not None
        sri_hashes = get_sri_hashes_for_version(version)
        result.hashes = lambda components, kind: {
            mk_url(component, kind): sri_hashes[mk_filename(component, kind)] for component in components
        }
``` 
we could further defer this load by moving the `json.load` inside a proper function defined there instead of a `lambda`, and I think we should. 

But, I would also like to propose making a `bokeh/_sri` subdirectory and populating it with separate individual `<version>.json` files. Besides offering some speed improvements, this should also simplify the release automation, since we can just save a new file rather than have to update an existing file in a precise way. 

cc @bokeh/core

**Comment by ianthomas23** [comment]
Sounds sensible to me.
