### ISSUE TITLE
[BUG] image_rgba seems rotated to me?  What am I missing?

### ISSUE THREAD

**Issue by lovettchris** [bokeh/bokeh#13463]
### Software versions

Python version      :  3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
IPython version     :  8.16.1
Tornado version     :  6.2
Bokeh version       :  3.3.0
BokehJS static path :  d:\Anaconda3\envs\sr\lib\site-packages\bokeh\server\static
node.js version     :  v18.17.1
npm version         :  9.8.0
Operating system    :  Windows-10-10.0.22621-SP0

### Browser name and version

VS Code

### Jupyter notebook / Jupyter Lab version

Jupyter notebook

### Expected behavior

I expected the following to create a horizontal red gradient from black to red, but instead it renders as a vertical gradient:

```python
WIDTH=600
HEIGHT=360
img = np.empty((WIDTH, HEIGHT), dtype=np.uint32)
view = img.view(dtype=np.uint8).reshape((WIDTH, HEIGHT, 4))
for i in range(WIDTH):
    for j in range(HEIGHT):
        view[i, j, 0] = int(i/WIDTH*255)
        view[i, j, 1] = 0
        view[i, j, 2] = 0
        view[i, j, 3] = 255

p = figure(width=WIDTH, height=HEIGHT)
p.x_range.range_padding = p.y_range.range_padding = 0

# must give a vector of images
p.image_rgba(image=[img], x=0, y=0, dw=WIDTH, dh=HEIGHT)

show(p)
```

### Observed behavior

I see this:

![image](https://github.com/bokeh/bokeh/assets/18707114/f60c6b4e-c98d-4a8b-abec-6df03fa71c1e)

### Example code

```Python
I got this code from https://docs.bokeh.org/en/latest/docs/examples/topics/images/image_rgba.html and modified it to simplify by filling in only one color.

I'd also love to see some sample code showing a more efficient way to do this (or a bokeh API that can do it):


def create_image(a):
    # an image loaded by open cv into a numpy array is organized differently:
    height, width, channels = a.shape
    img = np.empty((width, height), dtype=np.uint32)
    view = img.view(dtype=np.uint8).reshape((width, height, 4))
    for i in range(width):
        for j in range(height):
            view[i, j, 0] = a[j, i, 0]
            view[i, j, 1] = a[j, i, 1]
            view[i, j, 2] = a[j, i, 2]
            view[i, j, 3] = 255
    return img
```

**Comment by bryevdv** [comment]
@lovettchris please refer to https://numpy.org/doc/stable/reference/generated/numpy.empty.html Numpy arrays are row-major by default, not column major. That means the `A[0][...]` is the first row and `A[1][....]` is the second row, etc. 

If you set `WIDTH, HEIGHT = 4, 2` and also set the alpha channel to 0 and then run your loop it's easy to see what is actually happening:
```
In [10]: img
Out[10]:
array([[  0,   0],
       [ 63,  63],
       [127, 127],
       [191, 191]], dtype=uint32)
```

Note that by default Bokeh starts images at the lower left so for "images" it's often desirable/necessary to use a view that inverts the y-direction of the rows (also consistent with your image above with a row of black on the bottom).

Here is an example that shows how to drive an `image_rgba` from OpenCV (and also demonstrates that the image is only flipped in the y-direction, and *not* transposed across dimensions, as expected):

https://github.com/bokeh/bokeh/blob/branch-3.4/examples/server/app/faces/main.py

In the future if you are not sure if something is a bug, or are looking for advice, please start with the community discourse, not the issue tracker. https://discourse.bokeh.org

**Comment by lovettchris** [comment]
Makes sense, thanks for the additional links.
