### ISSUE TITLE
Update contour line calculations to use ContourPy's LineType.ChunkCombinedNan

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#13485]
The upcoming 1.2 release of ContourPy will include a data format for contour lines tailored to Bokeh's use of lines as NaN-separate numpy arrays (contourpy/contourpy#296). When this release is out on PyPI and conda-forge, we need to update our code to use this new `LineType.ChunkCombinedNan` if `contourpy >= 1.2` is installed. This will improve the performance of calculating contour lines (strictly speaking the calculation takes about the same amount of time but the approach avoids allocating new numpy arrays to insert the NaN into).

Code changes required (wrapped in a version check):

- The `line_type` in the `contour_generator` call.
- Contents of `_lines_to_coords` function.

**Comment by bryevdv** [comment]
Can we just require 1.2 as a minimum version and skip any version checks?

**Comment by ianthomas23** [comment]
We can if others are happy with that approach. I was being conservative as although this will work fine with PyPI and conda-forge, we don't have control over conda `default` channel. But the pin will force `default` to update ContourPy too, which is good from my point of view.

**Comment by bryevdv** [comment]
OK, my vote is still +1 for raising the min ver then. Otherwise if not I'd suggest we make an issue to raise and clear out version checks one release later (one release witch checks, only for the purpose of smoothing over `defaults` channel usage)

**Comment by bryevdv** [comment]
actually 3.4 is probably a ways away @philippjfr @jbednar would it be possible to push for the upcoming contourpy to be added to defaults fairly soon (i.e. the next few months)? If it can be added ahead of 3.4 then there would be no problem just raising the min ver.

**Comment by jbednar** [comment]
We should be able to push for contourpy to be on defaults; please just DM me with the specific version needed and the deadline.

**Comment by bryevdv** [comment]
@ianthomas23 can you drop a note here once 1.2 is released? 

👍 @jbednar for something concrete let's say "Before Christmas" (I'm guessing 3.4 won't happen until early next year)

**Comment by ianthomas23** [comment]
ContourPy is already on defaults but it is not updated automatically on a new release unlike conda-forge. When 1.2 is released I will create a PR at https://github.com/AnacondaRecipes/contourpy-feedstock as I am the best person to do that as I understand the change of dependencies, etc. Then it should just need @jbednar and/or @philippjfr to encourage the appropriate team within Anaconda to review and merge the PR, and upload the built packages.

**Comment by ianthomas23** [comment]
PR to update contourpy on defaults channel is here: AnacondaRecipes/contourpy-feedstock#2. It is correct from my point of view but the builds are failing. As I am not able to see the build logs I can do nothing further with it.

**Comment by mattpap** [comment]
Given that `contourpy` is already imported via an "inner" import, could we make it an optional dependency and thus not rely on when defaults channel gets updated?

**Comment by jbednar** [comment]
The Distro team is working on the feedstock, and my guess is that contourpy should be on defaults today.

**Comment by bryevdv** [comment]
> Given that contourpy is already imported via an "inner" import, could we make it an optional dependency and thus not rely on when defaults channel gets updated?

👎 vote from me. For users if things don't work out of the box that just translates to "it doesn't work".
