### ISSUE TITLE
[BUG] RangeTool does not respect target `max_interval`

### ISSUE THREAD

**Issue by droumis** [bokeh/bokeh#13483]
### Software versions

Python version      :  3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
IPython version     :  8.16.1
Tornado version     :  6.3.3
Bokeh version       :  3.3.0
BokehJS static path :  /Users/droumis/opt/miniconda3/envs/bokeh3.3/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v20.4.0
npm version         :  9.7.2
Operating system    :  macOS-13.5.2-arm64-arm-64bit

### Expected behavior

The RangeTool should respect the constraints imposed by the `max_interval` on the target plot and not allow for expanding the range beyond this interval. Depending on the intended behavior, this may be somewhere between a bug and a feature request.

### Observed behavior

The RangeTool ignores the `max_interval` constraint.

### Example code

```Python
import numpy as np
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, RangeTool
from bokeh.plotting import figure, show

n_points = 3000
x_values = np.linspace(0, 100, n_points) 
y_values = np.random.randn(n_points).cumsum()

source = ColumnDataSource(data=dict(x=x_values, y=y_values))

p = figure(height=300, width=800, tools=["xpan", "xzoom_in", "xzoom_out", "reset"],
           background_fill_color="#efefef", x_range=(22, 30))
p.line('x', 'y', source=source)
p.yaxis.axis_label = 'Value'
p.x_range.max_interval = 10  # Set max zoom interval

select = figure(height=130, width=800, y_range=p.y_range,
                tools="", toolbar_location=None, background_fill_color="#efefef")
range_tool = RangeTool(x_range=p.x_range)
range_tool.overlay.fill_color = "navy"
range_tool.overlay.fill_alpha = 0.2
select.line('x', 'y', source=source)
select.ygrid.grid_line_color = None
select.add_tools(range_tool)

show(column(p, select))
```

### Screenshots

https://github.com/bokeh/bokeh/assets/6613202/fd17e84b-4694-4458-9cae-c0e3f756a745

**Comment by droumis** [comment]
Also, the RangeTool ignores `max_interval` set on the source plot (its own), in addition to the target plot.

**Comment by bryevdv** [comment]
> Also, the RangeTool ignores max_interval set on the source plot (its own), in addition to the target plot.

The range configuration of the plot that contains the range tool is not relevant, the range tool should only care about the range that it is configured with.
