### ISSUE TITLE
[BUG] Even callbcak must have signature, example from Bokeh 3.3.0 fails from the start

### ISSUE THREAD

**Issue by lesolorzanov** [bokeh/bokeh#13486]
### Software versions

Python 3.6
tornado: 5.0.2
bokeh 3.0.0

### Expected behavior

I went to https://docs.bokeh.org/en/latest/docs/user_guide/server/app.html and went to the Single module format (arguably the easiest to use)

I run in a remote server the command

bokeh serve myapp.py 

and it replies 

`Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7f98642cceb8>: Event callback must have signature func(event), got func()`

I assume it refers to `button.on_event('button_click', callback)` can you tell me why this happens in your own example? and how to fix it? 

### Observed behavior

`Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7f98642cceb8>: Event callback must have signature func(event), got func()`

### Example code

```Python
This is your code:


# myapp.py

from random import random

from bokeh.layouts import column
from bokeh.models import Button
from bokeh.palettes import RdYlBu3
from bokeh.plotting import figure, curdoc

# create a plot and style its properties
p = figure(x_range=(0, 100), y_range=(0, 100), toolbar_location=None)
p.border_fill_color = 'black'
p.background_fill_color = 'black'
p.outline_line_color = None
p.grid.grid_line_color = None

# add a text renderer to the plot (no data yet)
r = p.text(x=[], y=[], text=[], text_color=[], text_font_size="26px",
           text_baseline="middle", text_align="center")

i = 0

ds = r.data_source

# create a callback that adds a number in a random location
def callback():
    global i

    # BEST PRACTICE --- update .data in one step with a new dict
    new_data = dict()
    new_data['x'] = ds.data['x'] + [random()*70 + 15]
    new_data['y'] = ds.data['y'] + [random()*70 + 15]
    new_data['text_color'] = ds.data['text_color'] + [RdYlBu3[i%3]]
    new_data['text'] = ds.data['text'] + [str(i)]
    ds.data = new_data

    i = i + 1

# add a button widget and configure with the call back
button = Button(label="Press Me")
button.on_event('button_click', callback)

# put the button and plot in a layout and add to the document
curdoc().add_root(column(button, p))
```
```


### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

**Comment by bryevdv** [comment]
The GitHub issue tracker is reserved for bug reports and feature requests only. The exception is indicating a usage error. To seek general support or help with usage questions, consider the [Community Discourse site](https://discourse.bokeh.org).
