### ISSUE TITLE
Image component + circle

### ISSUE THREAD

**Issue by lguibert** [bokeh/bokeh#1349]
Hi everybody.
http://stackoverflow.com/questions/26592834/add-circle-on-bokeh-image-solved

Here you'll be able to find my ex-problem about adding a circle on a component  image. The perfect guy who found the solution asked me to create an issue, so here it is.

My problem was that the circle wan't display on the final image. The problem was the syntax. Even if you have only one value in your settings (x=10, y=24...), you HAVE to put some [ ] arround the value. Easy stuff, but if you don't know it...

Hope it'll help someone !

**Comment by bryevdv** [comment]
This was fixed a long time ago at some point (just checked)
