### ISSUE TITLE
Some gallery references are dead

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13505]
These seem to be reference guide links, and can show up alongside other links that work just fine. A few examples from 3.3.0 docs:

## `Figure.scatter` link broken

<img width="437" alt="Screenshot 2023-11-01 at 22 18 47" src="https://github.com/bokeh/bokeh/assets/1078448/c3467559-068c-4481-aeb6-707bb2207ffd">

## `models.LabelSet` link broken

<img width="436" alt="Screenshot 2023-11-01 at 22 18 55" src="https://github.com/bokeh/bokeh/assets/1078448/0606fa4f-4910-467a-b9b1-cd3c349e7e5c">

**Comment by Azaya89** [comment]
Is there a simple way to find all similar links that are broken and require fixing? Or it's just these two examples? @bryevdv 

Edit: I did this manually and managed to modify 15 files. It seems to be a slow method though...

**Comment by Azaya89** [comment]
Also, all the _(source code)_ links in this section point to branch-3.0 that no longer exists in the repo. I'm thinking of changing them all to point to branch-3.3 or 3.4, but that seems to be a temporary solution. Is there a way to make sure that the `gallery.json` files always update automatically to the latest branch? 
![image](https://github.com/bokeh/bokeh/assets/99359668/d34833dd-3253-4ed5-a267-557d362787e7)

**Comment by tcmetzger** [comment]
> Is there a way to make sure that the `gallery.json` files always update automatically to the latest branch?

That's a very good thought! The best I can think of right now is to make the URLs point to the main branch, like `https://github.com/bokeh/bokeh/blob/main/examples/server/app/sliders.py`. This should basically always work, even if older branches are deleted/archived. However, I believe the folder structure for these files has also changed, so we'd need to manually check and update all (nine?) links here, and we'd need to update them again whenever we change the file structure again, so this isn't an optimal solution yet!

EDIT: I made https://github.com/bokeh/bokeh/pull/13539 to address this
