### ISSUE TITLE
[BUG]  Template does not seem to render correctly in Firefox

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13520]
### Software versions

https://docs.bokeh.org/en/3.3.1/docs/examples/plotting/periodic_shells.html

### Browser name and version

Mozilla Firefox 119.0

### Expected behavior

`Template` to look the same as in Chrome.

### Observed behavior

When seeing `Template` used in [this example](https://docs.bokeh.org/en/3.2.2/docs/examples/plotting/periodic_shells.html) it does not render as expected in Firefox

### Example code

```Python
https://docs.bokeh.org/en/3.3.1/docs/examples/plotting/periodic_shells.html
```

### Screenshots

In Firefox:

![image](https://github.com/bokeh/bokeh/assets/19758978/f6b04655-3d7c-4db3-abc7-9574e1d9c5a2)

In Google Chrome:
![ Screenshot 2023-11-10 11 07 23](https://github.com/bokeh/bokeh/assets/19758978/4636cc74-28d7-4be9-95ea-283ca5eac13d)

**Comment by mattpap** [comment]
Similar issue to what I already fixed in `UIElementView.render()`. I will need to reuse that implementation to make Firefox happy.
