### ISSUE TITLE
[BUG] Return type of the Model.__new__ function is incorrect

### ISSUE THREAD

**Issue by rchiodo** [bokeh/bokeh#13563]
### Software versions

Python version        :  3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:26:13) [MSC v.1935 64 bit (AMD64)]
IPython version       :  8.18.1
Tornado version       :  6.3.3
Bokeh version         :  3.3.1
BokehJS static path   :  C:\Users\rchiodo\AppData\Local\anaconda3\envs\bk-tutorial\Lib\site-packages\bokeh\server\static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-11-10.0.22000-SP0

### Expected behavior

Return type of constructing a figure to be a figure

### Observed behavior

Return type is a Model

### Example code

```Python
from bokeh.plotting import figure, show

d = figure()

reveal_type(d)

```

The type of d is not figure, but rather Model. This is because of the return value of the Model.__new__ function as Eric describes here:
https://github.com/microsoft/pyright/issues/6583

**Comment by bryevdv** [comment]
@mattpap should we change `tag: mypy` to `tag: typing` ? As Eric noted in the `pyright` issue, currently `mypy` ignores `__new__` return which is presumably why we didn't notice it

**Comment by mattpap** [comment]
> should we change `tag: mypy` to `tag: typing`

Seems more fitting, let's do that.
