### ISSUE TITLE
[BUG] Legend outside plot area won’t resize

### ISSUE THREAD

**Issue by Icoti** [bokeh/bokeh#13566]
### Software versions

Python version        :  3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:26:13) [MSC v.1935 64 bit (AMD64)]
IPython version       :  (not installed)
Tornado version       :  6.3.3
Bokeh version         :  3.3.1
BokehJS static path   :  C:\Users\Blaise\miniconda3\envs\testenv312\Lib\site-packages\bokeh\server\static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-10-10.0.19045-SP0

### Browser name and version

Chrome Version 119.0.6045.161 (Offizieller Build) (64-Bit)

### Expected behavior

In a plot with a legend right, outside of the plot area, while changing the text of the legend to a longer text with `p.legend.items[0].label = {'value': "Longer legend"}`, I expect the width of the plot area and of the legend to adapt automatically to fit the width of the figure.

### Observed behavior

After updating the legend to a longer text, the text is updated but the legend overlaps the plot area.

### Example code

```Python
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import Legend, LegendItem, Button
from bokeh.layouts import column

# Prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# Create a new plot
p = figure(x_axis_label="x", y_axis_label="y", toolbar_location="above", height=200)

# Create an empty legend right, outside of the plotting area:
p.add_layout(Legend(items=[]), "right")
p.legend.click_policy="hide" # Clicking on the legend after callback "repairs" the layout.

# Add renderer:
line = p.line(x, y)
p.legend[0].items.append(LegendItem(label="Temp.", renderers=[line]))

# Define callback with triggering button:
button = Button(label="Click")

def callback():
    p.legend.items[0].label = {'value': "Longer legend"}

button.on_click(callback)

# Define layout:
my_layout = column(button, p)

curdoc().add_root(my_layout)
```

### Stack traceback or browser console output

The expected width ratios can be achieved by clicking twice on the legend to hide and show back the curve.
Though, I didn't find a workaround to enforce the expected size programmatically.

### Screenshots

Initial appearance:
![ini](https://github.com/bokeh/bokeh/assets/94801369/cc22fea4-4662-400c-9090-f1e3de46f22c)
Appearance after callback:
![After callback](https://github.com/bokeh/bokeh/assets/94801369/4736ba23-6fa9-4aa0-814d-abd240d52db4)

**Comment by Icoti** [comment]
https://discourse.bokeh.org/t/legend-outside-plot-area-wont-resize/11036

**Comment by mattpap** [comment]
Canvas layout invalidation doesn't work. The layout is updated in a second render cycle (e.g. when panning).
