### ISSUE TITLE
[FEATURE] Support formatters when using Template as HoverTool

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13599]
### Problem description

When using `Template` as a tooltip in a `HoverTool`. I would like it to be possible to also use formatters. 

### Feature description

I want these two HoverTools to provide the same output (except styling):

``` python
import pandas as pd
import numpy as np

from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure, show
from bokeh.models.dom import Div, Styles, Template, ValueRef


source = ColumnDataSource(
    data=dict(x=[0], y=[0], date=np.array([np.datetime64("2020-01-01")]))
)


def template_tooltips():
    style = Styles(
        display="grid",
        grid_template_columns="auto auto",
        column_gap="10px",
    )
    grid = Div(style=style)
    grid.children = [
        "date",
        ValueRef(field="date{%F}"),
    ]
    return Template(children=[grid])


hovertool1 = HoverTool(
    tooltips=[("date", "@date{%F}")],
    formatters={"@date": "datetime"},
)


hovertool2 = HoverTool(
    tooltips=template_tooltips(),
    formatters={"@date": "datetime"},
)

p = figure(width=400, height=400)
p.add_tools(hovertool1)
p.add_tools(hovertool2)
p.circle("x", "y", size=20, source=source)

show(p)
```

Normal hover tool:
![image](https://github.com/bokeh/bokeh/assets/19758978/51cd702e-a0ee-4334-9357-20e4c0128f9a)

Template hover tool
![image](https://github.com/bokeh/bokeh/assets/19758978/b23b13a3-cc6f-4e84-a30e-7a12b73e5070)

Note: Ignore the styling problem this is because I'm using Firefox. See #13520.

### Potential alternatives

As an alternative, I can use custom HTML to get the same effect, but it will quickly be somewhat ugly.  

### Additional information

For my real purpose, I plan to use this for ImageStack. A rough example is given here: https://github.com/holoviz/holoviews/issues/6015#issuecomment-1853731270.

**Comment by mattpap** [comment]
> `ValueRef(field="date{%F}")`

`ValueRef.field` is a field name, so the syntax with formatting would be something along `ValueRef(field="date", format="%F)`.
