### ISSUE TITLE
Use globally unique and CSS safe IDs in `<script type="application/json">`

### ISSUE THREAD

**Issue by kassbohm** [bokeh/bokeh#13629]
### Problem description

Embedding **multiple** Bokeh-html-files with javascript on **one single html-page**, I run into problems.

Reason: Bokeh repeatedly prints this into html-files:

`<script type="application/json" id="p1050"> `

However: I think, it is unnecessary, to have a "short" id in this context...

### Feature description

When producing html-files with javascript: Use a **random** id such as: 

id="p7365985367398" 

instead of 

id="p1050"

### Potential alternatives

At the moment, I modify my htm-files manually to fix the problem, which is not a big deal...

If I could set the id's myself: This would be an alternative solution...

### Additional information

I thought, there might be other users with the same problem.

**Comment by bryevdv** [comment]
@kassbohm you have not stated what the actual problem you are experiencing is. Are random ids just a personal preference of yours? Or are the current id values actually causing some real issue for you somehow?

**Comment by bryevdv** [comment]
@kassbohm please describe how you are attempting to embed multiple plots. If you are doing everything from a single process you should not get duplicate ids. What exact steps are you taking?

**Comment by kassbohm** [comment]
1. I create several plots one by one. Each one with a Python script.
2. I embed a subset of these plots into different html-pages.

**Comment by bryevdv** [comment]
Embed *how*? Are you using bokeh embedding APIs? (Could be an issue) Just concatenating multiple separate complete HTML files? (Not supported usage) ***please provide actual reproducible details***.

Edit: let me just be clear: if we cannot, ourselves, reproduce an actual problem locally, then this issue will be closed. I hope that better conveys how much and what kind of information we need.

**Comment by kassbohm** [comment]
I am (as you say) "just concatenating multiple separate complete HTML files". And this works just fine, if the above mentioned id's are unique.

I did not know, that this method is "not supported" or "not the way it is supposed to be done" - now I know. Also I have seen bokeh.embed now.

I described the problem as good as I could. So that I do not see a reason for being upset.

**Comment by mattpap** [comment]
You can prefix your invocations of bokeh with `BOKEH_SIMPLE_IDS="no"` to remedy this issue. Given that all other elements get globally unique IDs (and CSS safe), at least for consistency sake we should change the behavior JSON scripts.

**Comment by kassbohm** [comment]
@mattpap Thanks!

This is what I was after.

With this setting: Everything works as expected for me. I have just checked this.

**Comment by bryevdv** [comment]
> You can prefix your invocations of bokeh with BOKEH_SIMPLE_IDS="no" to remedy this issue. Given that all other elements get globally unique IDs (and CSS safe), at least for consistency sake we should change the behavior JSON scripts.

@mattpap can you elaborate, I don't really understand what you are proposing. Do you mean getting rid of "simple" ids altogether? Making them not-default? Something else? 

> So that I do not see a reason for being upset.

I'm not upset @kassbohm just trying to be extra clear and completely unambiguous about needs. You've asked for something but with zero actual details about what you are doing and how it takes lots of back and forth to suss out whether the ask is:

* a feature that already exists that you weren't aware of
* a usage problem that can be addressed by other means
* a bug
* an actual reasonable new feature to consider
* something else
* a combination of all of the above

The number one thing users can do to help maintainers help them is to ***give more details***. For bug reports, or feature requests, or help questions. Always include more specifics: code to run, code you'd like to be able to run, exact steps to follow, full text of error messages, package versions...

**Comment by mattpap** [comment]
> can you elaborate, I don't really understand what you are proposing. Do you mean getting rid of "simple" ids altogether? Making them not-default? Something else?

I'm proposing making all generated elements' IDs to be unique and CSS safe. That in particular means any `<script type="application/json">`. As far as I can tell, JSON scripts are the only elements left that use simple IDs.

**Comment by bryevdv** [comment]
@mattpap OK, but just noting that the switch to simple ids by default was originally [in response to performance complaints](https://github.com/bokeh/bokeh/pull/8309#issuecomment-427519035)

> Additionally, in 1.0 Bokeh is switching to "simple ids" by default, i.e. a simple monotonically increasing sequence of integers. This is ~2x improvement in time to generate IDs for models

Is there some way to avoid regressing performance these days? Are we certain we have not already incurred a cost, and if so how large?

**Comment by mattpap** [comment]
We are talking about one `<script type="application/json" id="...">` per HTML file (or very rarely a few), not changing all IDs under such script(s), so there will be no performance regression. My suggestion to set `BOKEH_SIMPLE_IDS="no"` was a temporary workaround.
