### ISSUE TITLE
Remove all GH source tarballs?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1363]
Idea based on the confusion in #1352. I don't see what purpose they serve, if someone truly wants to build from source (including BokehJS) they can and should clone the repo. 

@mattpap @hhuuggoo @damianavila @pzwang thoughts?

**Comment by bryevdv** [comment]
@pzwang @damianavila @mattpap What do you guys think about this? We should either do this (and update the release BEP to include deleting new ones as step) or close this discussion.

**Comment by bryevdv** [comment]
Actually I am not sure this is possible anymore, without also deleting the tag, so the question may be irrelevant now.

**Comment by bryevdv** [comment]
Well, it can be done through the API it looks like, so it could made an automated part of the release:

https://developer.github.com/v3/repos/releases/#delete-a-release-asset

**Comment by damianavila** [comment]
You can delete the releases... 

![2015-01-06-213823_1366x768_scrot](https://cloud.githubusercontent.com/assets/1640669/5638879/69b8c186-95ec-11e4-9a11-ae2a1db63650.png)

but if you delete it, you also delete the tags. So, not having a good solution for this, I guess we have to live with it and close the issue

**Comment by bryevdv** [comment]
Yes on the GH web UI that is true but I think specific assets can be deleted by using the REST API in the link I put above.

**Comment by bryevdv** [comment]
We could also make the release notes point to the main docs release notes too, I think.

**Comment by damianavila** [comment]
>Yes on the GH web UI that is true but I think specific assets can be deleted by using the REST API in the link I put above.

I saw your link just know... but are you really sure that delete them using the API do not remove the tag?
I have to investigate, but because the Github releases are based on tags, I would probably expect that the release removal also delete the tag...

**Comment by bryevdv** [comment]
I don't think it deletes the release just specific release assets. Could try it out on one if the RC releases I don't care if one of those accidentally gets blown away.

**Comment by damianavila** [comment]
> Could try it out on one if the RC releases I don't care if one of those accidentally gets blown away.

yep... that's a good idea...

**Comment by bryevdv** [comment]
@lexicalunit has agreed to look at this

**Comment by pzwang** [comment]
Realized that I haven't weighed in here.  After reading #1352, I concur that we should get rid of the GH-auto-generated tarballs. 

I would add that the docs on Installing from Source should mention downloading the source tarballs from PyPI.  Right now they assume the user wants/should build BokehJS as well.  (See http://bokeh.pydata.org/en/latest/docs/installation.html#installing-from-source)

**Comment by bryevdv** [comment]
Just to spell out what *I believe* is the case: to delete the assets, we have to create true "releases" using the releases API. So I propose:
* create release for all tags
* remove their tarball assets
* also update things like release notes to point at pydata.org
If I am wrong, there may just be no way to remove them but I hope not.

**Comment by damianavila** [comment]
>create release for all tags

This is already done automatically by Github

>remove their tarball assets

OK, and update it with the our ones...

>also update things like release notes to point at pydata.org

Yep... minimal reference and point to the real release notes...

>If I am wrong, there may just be no way to remove them but I hope not.

To remove what? the releases can be removed, and it seems the asset (binaries) can be removed through the API... so I don't know what are you referring to...

**Comment by bryevdv** [comment]
@damianavila I thought so too but evidently not:
```
In [29]: read_url('https://api.github.com/repos/bokeh/bokeh/releases')
Out[29]: []
```
If you look at the releases page closely, all those links there actually go to `tags` API pages when you click one. So, it seems to create a "real" release, you have to explicitly ask for one.

**Comment by damianavila** [comment]
oohh... who in the world designed this thing in this way :angry: 
OK, now understand... thanks for the clarification...

**Comment by bryevdv** [comment]
Yah I agree, it seems ridiculous. A little more info from their docs seems to corroborate:
>Note: This returns a list of releases, which does not include regular Git tags that have not been associated with a release. (To get a list of Git tags, use the Repository Tags API.)

**Comment by bryevdv** [comment]
I think we can close this and continue any discussion in the linked task issue.
