### ISSUE TITLE
[FEATURE] Delay Pillow / PIL import to optimise Bokeh import time

### ISSUE THREAD

**Issue by cdeil** [bokeh/bokeh#13638]
### Problem description

For me Panel and Bokeh import sometimes is slow (x-ref https://github.com/holoviz/panel/issues/6165 and [HERE](https://stackoverflow.com/questions/77769896/profile-why-python-imports-are-slow-on-macos) ).

Using [tuna](https://github.com/nschloe/tuna) and these commands:
```
time PYTHONPROFILEIMPORTTIME=1 python -c 'import bokeh.plotting' 2> bokeh_import.log
tuna bokeh_import.log
```
I see that a few percent of the import time comes from here:
https://github.com/bokeh/bokeh/blob/5854a250835a93868e4a04149bc44864aec8f775/src/bokeh/core/property/visual.py#L33

### Feature description

Is it feasible / advisable to make this a delayed import to optimise import and startup time?
Is PIL someone required for any Bokeh plotting or only used in special cases?

### Potential alternatives

None

### Additional information

<img width="1902" alt="Screenshot 2024-01-06 at 14 57 51" src="https://github.com/bokeh/bokeh/assets/852409/5cf92182-788a-4675-bfa5-3ed96b253d32">

**Comment by bryevdv** [comment]
@mattpap I'll make a PR to handle this and the other "banned imports" using the new `ruff` check tomorrow, it works very nicely
```
    def test_ruff() -> None:
        chdir(TOP_PATH)
        proc = run(["ruff", "."], capture_output=True)
>       assert proc.returncode == 0, f"ruff issues:\n{proc.stdout.decode('utf-8')}"
E       AssertionError: ruff issues:
E         src/bokeh/core/property/visual.py:33:8: TID253 `PIL` is banned at the module level
E         src/bokeh/io/export.py:37:1: TID253 `PIL` is banned at the module level
E         tests/unit/bokeh/core/property/test_visual.py:29:8: TID253 `PIL` is banned at the module level
E         Found 3 errors.
E
E       assert 1 == 0
E        +  where 1 = CompletedProcess(args=['ruff', '.'], returncode=1, stdout=b'src/bokeh/core/property/visual.py:33:8: TID253 `PIL` is ba...it/bokeh/core/property/test_visual.py:29:8: TID253 `PIL` is banned at the module level\nFound 3 errors.\n', stderr=b'').returncode
```

**Comment by bryevdv** [comment]
Thanks @cdeil this will be in the next minor release. 

Edit: or potentially even sooner, @mattpap this would probably backport cleanly to 3.3.3.
