### ISSUE TITLE
[BUG] Regression handling glyph border_radius that is a dict

### ISSUE THREAD

**Issue by ianthomas23** [bokeh/bokeh#13637]
### Software versions

Python version        :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
IPython version       :  8.17.2
Tornado version       :  6.3.3
Bokeh version         :  3.4.0.dev4+15.gf821f2c5
BokehJS static path   :  /home/iant/github/bokeh/src/bokeh/server/static
node.js version       :  v18.13.0
npm version           :  10.2.3
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.5.0-14-generic-x86_64-with-glibc2.38

### Expected behavior

Prior to commit f821f2c549c95 (PR #13618) on `branch-3.4` it is possible to use `p.rect(..., border_radius=dict(top_left=50))` to have just one of the rect corners rounded. But with that commit nothing renders. It was a big PR so is probably an accidental regression (and the functionality is experimental) and evidently we don't have an appropriate python-level test for this situation.

### Observed behavior

Nothing is displayed. In JS console:
```
Uncaught (in promise) Error: Rect(p1036).border_radius given invalid value: {}
    at N.validate (issue_new.html:200:2223)
    at N._update (issue_new.html:200:1963)
    at N.initialize (issue_new.html:200:1283)
    at m.initialize_props (issue_new.html:196:4318)
    at p._decode_object_ref (issue_new.html:229:4678)
    at p._decode (issue_new.html:229:1739)
    at p._decode_plain_object (issue_new.html:229:2300)
    at p._decode (issue_new.html:229:1026)
    at p._decode_object_ref (issue_new.html:229:4654)
    at p._decode (issue_new.html:229:1739)
```

### Example code

```Python
from bokeh.plotting import figure, show

p = figure(width=300, height=300)

#p.rect(x=0, width=2, y=0, height=1, border_radius=50)  # Works
p.rect(x=0, width=2, y=0, height=1, border_radius=dict(top_left=50))  # Fails

show(p)
```

### Stack traceback or browser console output

See above.

**Comment by mattpap** [comment]
This is because `border_radius` is a `Struct`, which uses `dict` in Python and plain object in JS, which is the worst case to handle.
