### ISSUE TITLE
[FEATURE] Support BoxSelectTool-like range-setting for the RangeTool

### ISSUE THREAD

**Issue by droumis** [bokeh/bokeh#13646]
### Problem description

Limiting the setting of the focused range to just pan/drag with a RangeTool adds extra steps/clicks.

### Feature description

Is there any interest in supporting BoxSelectTool-like range-setting interaction for the RangeTool by default? For example, see [plotly range slider](https://plotly.com/python/range-slider/) or the Bokeh app below that uses a custom callback.

### Potential alternatives

None

### Additional information

```python

import numpy as np
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, RangeTool, BoxSelectTool, CustomJS
from bokeh.plotting import figure, show
from bokeh.sampledata.stocks import AAPL
from bokeh.io import output_notebook

output_notebook()

dates = np.array(AAPL['date'], dtype=np.datetime64)
source = ColumnDataSource(data=dict(date=dates, close=AAPL['adj_close']))

# Main
p = figure(height=300, width=800, tools="xpan", toolbar_location=None,
           x_axis_type="datetime", x_axis_location="above",
           background_fill_color="#efefef", x_range=(dates[1500], dates[2500]))
p.line('date', 'close', source=source)
p.yaxis.axis_label = 'Price'

# Minimap
select = figure(title="Drag the middle and edges of the selection box to change the range above",
                height=130, width=800, y_range=p.y_range,
                x_axis_type="datetime", y_axis_type=None,
                tools="", background_fill_color="#efefef")
select.line('date', 'close', source=source)
select.ygrid.grid_line_color = None

range_tool = RangeTool(x_range=p.x_range)
select.add_tools(range_tool)

bselect = BoxSelectTool(dimensions='width')
select.add_tools(bselect)

callback = CustomJS(args=dict(x_range=p.x_range), code="""
        const geometry = cb_obj.geometry;
        x_range.start = geometry.x0;
        x_range.end = geometry.x1;
""")

select.js_on_event('selectiongeometry', callback)

show(column(p, select))

```

https://github.com/bokeh/bokeh/assets/6613202/3174e247-48cc-44e1-9fb6-941d2438458f

**Comment by bryevdv** [comment]
Please confirm this summary understanding:
> Drag events initiated outside the existing range should define a new range to replace the old one (new behavior). Drag events inside the existing range or on its border should adjust the existing range (current behavior).

If so that seems like a reasonable flag to add. I don't have strong feelings about making it a new default cc @bokeh/dev

**Comment by mattpap** [comment]
@droumis, should this be scheduled under CZI?

**Comment by droumis** [comment]
@bryevdv Yes, that's correct. Either as a flag or enabled by default is fine with me.

@mattpap Yes, it fits for CZI so I'll add the label. Given that this is really low priority, I'd like to take a first shot at this myself if that's ok.

**Comment by droumis** [comment]
I'm not going to have time for this task in the foreseeable future, so I'll let @mattpap take this one

**Comment by droumis** [comment]
@philippjfr were discussing some additional features that would be good to include as general improvements to the RangeTool (I can file separate feature requests if preferred).

1.  adding handle glyphs (see image below from [plotly rangeslider](https://plotly.com/python/range-slider/)
![image](https://github.com/bokeh/bokeh/assets/6613202/fdb62ea7-bc67-4793-961f-0ab3b6aeb16f)
2. ability to invert focus mask (e.g. the non-selected region is darker in the image above)
3. expand/contract selected range via scroll zoom when cursor hovers (e.g. see [altair interval selection](https://altair-viz.github.io/gallery/interval_selection.html) below)

https://github.com/bokeh/bokeh/assets/6613202/6a20db32-da57-4832-acb0-44d698401b68

**Comment by mattpap** [comment]
> adding handle glyphs 

PR #13279 lays the foundation for this kind of features.

> ability to invert focus mask

Added support in PR #13810.

> expand/contract selected range via scroll zoom when cursor hovers

PR #13815 lays the foundation for this, but more work will be needed in a follow-up PR.

**Comment by maximlt** [comment]
While creating a feature request in hvPlot to add an API to make it easy to add a range tool, I had a quick look at how other libraries called this feature. Sharing this here as it might help designing the UI/UX in Bokeh:

- HoloViews: [RangeToolLink](https://holoviews.org/gallery/demos/bokeh/timeseries_range_tool.html)
- Bokeh: [Range tool](https://docs.bokeh.org/en/latest/docs/user_guide/topics/timeseries.html#range-tool)
- Pandas-Bokeh: [rangetool](https://github.com/PatrikHlobil/Pandas-Bokeh?tab=readme-ov-file#lineplot-with-rangetool)
- Plotly: [Range slider](https://plotly.com/python/time-series/)
- HighCharts: [Range selector](https://www.highcharts.com/docs/stock/range-selector)
- ECharts: [Data Zoom](https://echarts.apache.org/examples/en/index.html#chart-type-dataZoom)

(I quite liked the ECharts implementation)

<img width="926" alt="image" src="https://github.com/bokeh/bokeh/assets/35924738/f1a0a9e7-75f3-4989-ac57-ae667277481b">
