### ISSUE TITLE
[FEATURE] `HTMLLabel` to support `stylesheets` and `css_classes` 

### ISSUE THREAD

**Issue by carve11** [bokeh/bokeh#13652]
### Problem description

The `HTMLLabel` or `Label` annotations are very useful renderers for text since they accept screen units. One issue for me is the lack of css style options beyond the current text, border and background arguments. I often find that I would like to style something but not able to. Eg it could be padding, use the font-family defined in html body css, font-weight. I have previously asked about this on [discourse](https://discourse.bokeh.org/t/is-it-possible-to-style-a-htmllabel/10044).

Based on the following versions:
Python version        :  3.11.7 (main, Jan  1 2024, 01:39:59) [Clang 14.0.0 (clang-1400.0.29.202)]
IPython version       :  (not installed)
Tornado version       :  6.4
Bokeh version         :  3.3.3

### Feature description

Other widgets support the arguments `css_classes` and `stylesheets` and, if I have understood correctly, `HTMLLabel` is a `div` element. 

### Potential alternatives

Have not considered any alternatives.

**Comment by mattpap** [comment]
`HTMLLabel` was designed to be an HTML equivalent to canvas `Label` annotation, thus it strives to keep the same API, behavior and appearance. In fact, `HTMLLabel` used to be implemented as `Label(render_mode="css")`. However, the utility of `HTMLLabel` defined like this is questionable. We are currently in the process of adding "floating" UI elements to bokeh (PR #13538), so it will be possible to add HTML panels to plots/canvas and any renderers (e.g. attach HTML to a box annotation) in screen, data and symbolic coordinates. These HTML panels support `css_classes`, `stylesheets` and more.

**Comment by carve11** [comment]
@mattpap Cool, thanks for the update. Looking forward to the floating UI elements.

**Comment by mattpap** [comment]
PR #13828 adds support for all styling properties of `UIElement` to all DOM based renderers on the canvas.
