### ISSUE TITLE
[FEATURE] highlight selected item for dropdown widget

### ISSUE THREAD

**Issue by DeeliN221** [bokeh/bokeh#13672]
### Problem description

Click at a dropdown widget, shows the menu, but no hint of what the item has been set. All the items are in the same style. No highlights, no bold, no frame around it.

![image](https://github.com/bokeh/bokeh/assets/102862066/04cda3b0-af7d-4948-ad80-19a1a6f5a940)

### Feature description

Highlight the item, for example:

![image](https://github.com/bokeh/bokeh/assets/102862066/0dcab599-1576-4aa7-9a49-e684d6239c15)

### Potential alternatives

Move the selected item as the first one in menu, or add a frame around the selected item.

![image](https://github.com/bokeh/bokeh/assets/102862066/eff9c582-249b-4f82-bea2-a9a1544111d9)

**Comment by bryevdv** [comment]
A visual indicator seems reasonable. Any thoughts @mattpap ?

**Comment by mattpap** [comment]
`Dropdown` provides access to actions via a menu (or a default action and a set of actions in the split dropdown case), but it doesn't store any state. For a stateful widget there's `Select`. I suppose we could add support for checked items and groups, which I have to do in other contexts anyway.

**Comment by bryevdv** [comment]
I just realized this wasn't about the `Select` widget. @m3lab-zzl I think a `Select` is what you want instead:

https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#select

I agree with @mattpap that dropdowns are stateless button/menu for initiating an immediate action, and note this is consistent with other sources e.g. [bootstrap](https://getbootstrap.com/docs/4.0/components/dropdowns/) or [w3schools](https://www.w3schools.com/css/css_dropdowns.asp)

I think this issue can be closed with `noaction`

**Comment by DeeliN221** [comment]
Many thanks. I did not check all the widgets and did not know there was a Select. Now I will use Select instead.
