### ISSUE TITLE
[BUG] Using tap tool makes image glyph disappear with webgl enabled

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#13678]
### Software versions

Python version        :  3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0]                                                          
IPython version       :  (not installed)                                        
Tornado version       :  6.3.3                                                  
Bokeh version         :  3.3.4                                                  
BokehJS static path   :  /home/user/miniconda3/envs/bokeh/lib/python3.12/site-packages/bokeh/server/static                                                  
node.js version       :  (not installed)                                        
npm version           :  (not installed)                                        
jupyter_bokeh version :  (not installed)                                        
Operating system      :  Linux-5.15.0-92-generic-x86_64-with-glibc2.35

### Expected behavior

Using the tap tool should not affect the visibility of image glyphs.

### Observed behavior

When the tap tool is enabled, clicking on a plot will make images disappear. It does not happen if the tool is disabled or if webgl is disabled.

### Example code

```Python
import numpy as np

from bokeh.plotting import figure
from bokeh.io import output_notebook, show

output_notebook()

x = np.linspace(0, 10, 300)
y = np.linspace(0, 10, 300)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx) * np.cos(yy)

p = figure(width=400, height=400, output_backend="webgl")
p.image(image=[d], x=0, y=0, dw=10, dh=10)
p.add_tools('tap')

show(p)
```

### Stack traceback or browser console output

No error in python or javascript

### Screenshots

![image_tap](https://github.com/bokeh/bokeh/assets/49269671/7728588f-a790-412e-85df-cea989cd88d1)

**Comment by bryevdv** [comment]
@TheoMathurin does this happen outside notebook environments? Is there any relevant output (errors, etc) in the browser's JavaScript console log?

**Comment by TheoMathurin** [comment]
It happens within a server too. There's nothing in the browser's console.

**Comment by ianthomas23** [comment]
@TheoMathurin Thanks for reporting this. It is definitely a bug, and one for me to fix.

**Comment by TheoMathurin** [comment]
Alright, thanks!
