### ISSUE TITLE
Remove year or year range from copyright notices

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13680]
I recently learned that updating copyright years is unnecessary: https://hynek.me/til/copyright-years/ . I've removed the copyright years from a number of my projects. Cheers to fewer chores 🎉

_Originally posted by @sloria in https://github.com/bokeh/bokeh/issues/13630#issuecomment-1922443533_

**Comment by ianthomas23** [comment]
I am very much in favour of this.

**Comment by mattpap** [comment]
Given the support so far, unless there are any objections, I will submit a PR updating copyright notices.
