### ISSUE TITLE
Useless error formatting can be sometimes costly in on_change setup

### ISSUE THREAD

**Issue by Latill** [bokeh/bokeh#13688]
### Software versions

Python version      :  3.9.2 (default, Feb 28 2021, 17:03:44)
IPython version     :  7.20.0
Tornado version     :  6.3.3
Bokeh version       :  3.1.0

### Expected behavior

on_change method should not be slow to intialize no matter the callback

### Observed behavior

on_change calls callback_manager which checks the arguments of the callback. This check prepares the error message even if it's not being used. The error message calls str(signature) which calls str on optional arguments for get the str representation of default values (or of partial-filled arguments which should not be there, but that's a inspect.signature issue) and can be costly for big data structures.

### Example code

```Python
from bokeh.io import curdoc
from bokeh.models import Div
from functools import partial
import time

def callback(attr, old, new, o):
    pass

div = Div(text="test", width=300)
s = time.time()
div.on_change('text', partial(callback, o=list(range(10000000))))
duration = time.time()-s
div.text = f"on_change last {duration}s"

curdoc().add_root(div)


=> "on_change last 0.8707618713378906s"
```

### Stack traceback or browser console output

will do a PR to just put the formating in the argument breach case.

**Comment by Latill** [comment]
Sorry I'm new on github, and after several attempts never managed to get the commit pushed through, even with token , always getting 403 from github... "remote: Permission to bokeh/bokeh.git denied "

patch is pretty small, if anyone can do it .. thanks !



```
--- a/src/bokeh/util/callback_manager.py
+++ b/src/bokeh/util/callback_manager.py
@@ -205,13 +205,12 @@ def _nargs(fn: Callable[..., Any]) -> int:
 def _check_callback(callback: Callable[..., Any], fargs: Sequence[str], what: str ="Callback functions") -> None:
     '''Bokeh-internal function to check callback signature'''
     sig = signature(callback)
-    formatted_args = str(sig)
-    error_msg = what + " must have signature func(%s), got func%s"
-
     all_names, default_values = get_param_info(sig)

     nargs = len(all_names) - len(default_values)
     if nargs != len(fargs):
+        formatted_args = str(sig)
+        error_msg = what + " must have signature func(%s), got func%s"
         raise ValueError(error_msg % (", ".join(fargs), formatted_args))

```

**Comment by mattpap** [comment]
@Latill, you need to "fork" `bokeh/bokeh` repository into your account and then send a PR from your fork (see the [docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)).

**Comment by Latill** [comment]
Thanks ! it works better indeed :)
