### ISSUE TITLE
[BUG] HoverTool can't adress source with `ö`

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13697]
### Expected behavior

I expect that the HoverTool is able to display information from the data of a ColumnDataSource, even if the key has special letters like `ö` in it. 

### Observed behavior

If the key contains a special letter like `ö`, the HoverTool displays `???` and adds the key without the first letter. 

### Example code

```Python
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show, output_notebook
output_notebook()

source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=['A', 'b', 'C', 'd', 'E'],
    wörter=['A', 'b', 'C', 'd', 'E'],
))
TOOLTIPS = [("desc", "@desc"), ("Wörter", "@wörter")]
p = figure(width=400, height=400, tooltips=TOOLTIPS, title="Mouse over the dots")
p.circle('x', 'y', size=20, source=source)
show(p)
```

![BrokenHoverTool](https://github.com/bokeh/bokeh/assets/68053396/91f7b87b-4ab2-4077-8024-65e8e86f5c96)

<details><summary>Technical Information</summary>
### Software versions

Python version      :  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
IPython version     :  8.14.0
Tornado version     :  6.3.3
Bokeh version       :  3.3.4
BokehJS static path :  /opt/conda/envs/aiva-env/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.35

### Browser name and version

Google Chrome Version 121.0.6167.184 (Offizieller Build) (64-Bit)
</details>

**Comment by mattpap** [comment]
This works:
```py
TOOLTIPS = [("desc", "@desc"), ("Wörter", "@{wörter}")]
```
i.e. full reference syntax. The short/simplified syntax only works with names that are simple identifiers. Perhaps we could extend that a little bit, if there's a cheap and reliable way of doing this in JS.
