### ISSUE TITLE
[BUG] Blurry plots with WebGL

### ISSUE THREAD

**Issue by Yura52** [bokeh/bokeh#13692]
### Software versions

```
Python version        :  3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:33:12) [Clang 15.0.7 ]
IPython version       :  8.15.0
Tornado version       :  6.3.3
Bokeh version         :  3.3.4
BokehJS static path   :  <MY CONDA ENV DIR>/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v21.1.0
npm version           :  10.2.0
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-12.5-arm64-arm-64bit
```

### Browser name and version

Firefox 122.0.1

### Jupyter notebook / Jupyter Lab version

JupyterLab 4.1.1

### Expected behavior

The second plot should not be blurry

### Observed behavior

The second plot should is blurry

### Example code

```Python
import bokeh.plotting
import bokeh.palettes
import bokeh.io
import holoviews as hv

bokeh.io.output_notebook()
hv.extension('bokeh')

x = [0, 1, 2, 3]
y = [1, 2, 3, 2]
width = 500
height = 300
color = bokeh.palettes.Set1_3[1]

p1 = bokeh.plotting.figure(width=width, height=height)
p1.line(x, y, width=2, color=color)
bokeh.plotting.show(p1)

p2 = bokeh.plotting.figure(width=width, height=height, output_backend='webgl')
p2.line(x, y, width=2, color=color)
bokeh.plotting.show(p2)
```

### Screenshots

The first plot:

![0](https://github.com/bokeh/bokeh/assets/8861742/a97e9718-dfa7-474b-833d-f1e2331664b8)

The second plot:

![1](https://github.com/bokeh/bokeh/assets/8861742/2a889716-1548-4413-9cdf-4ae4ca3b5d41)

**Comment by ianthomas23** [comment]
Are you using a Retina display here, or maybe a hybrid setup with one Retina display and an external monitor that is not Retina?

We effectively scale the antialiasing distance by the [pixel ratio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) of the screen, which is 2 for a Retina display. So the antialiasing distance on a Retina display is twice as much in physical pixels which means it is correct in CSS pixels (i.e. expected "human eye" pixels). So the antialiasing should be similar for `canvas` and `webgl` backends, which is evidently not the situation here.

From a purely practical point of view I do not currently have access to a Retina display (or any display with a pixel ratio far from 1) so I am not able to check that what we currently do is what I expect us to do.

**Comment by Yura52** [comment]
Yes, this issue is observed of my MacBook Pro: `14.2-inch (diagonal) Liquid Retina XDR display; 3024-by-1964 native resolution at 254 pixels per inch`

**Comment by ianthomas23** [comment]
Thanks. Could you try with a different browser, ideally Chrome, to confirm that it is not a browser-specific problem?

**Comment by Yura52** [comment]
> Thanks. Could you try with a different browser, ideally Chrome, to confirm that it is not a browser-specific problem?

I reproduced the issue in Safari and in one Blink/Chromium-based browser (unfortunately, I cannot install Chrome on my machine).

**Comment by mattpap** [comment]
I don't see any difference between different pixel densities in Chromium's devtools (all my screens are natively 1:1), but I see a clear differences when scaling the viewport (blurring seems to increase with scaling).

At 100% zoom:
![image](https://github.com/bokeh/bokeh/assets/27475/21983790-b476-4a1a-9052-f7d19412a4d8)

At 250% zoom (need to open this image in a new tab to see it in full resolution and see the blurring):
![image](https://github.com/bokeh/bokeh/assets/27475/a3850f8f-3218-4565-b90f-057207f3b79d)

(both use 1:1 DPI). When testing this, note that you have to reload the page for zoom to take effect in bokehjs.

**Comment by Yura52** [comment]
Not sure if this is an additional context for Bokeh developers or a suggestion to check the zoom-related things on my side :) So just in case I did the following:
- I turned off the native system-wide macOS scaling.
- I reset the browser scaling.

And after those changes, the issue is still there.
