### ISSUE TITLE
Explanation is part of the code block in the latex_axis_labels_titles_labels example

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13720]
In the [latex on axis and titles](https://docs.bokeh.org/en/latest/docs/examples/styling/mathtext/latex_axis_labels_titles_labels.html) example the code block is not pure python code.

![grafik](https://github.com/bokeh/bokeh/assets/68053396/76c2d512-8c47-45a8-ac87-354942e105b5)

It also displays the information which should be evaluated by the `bokeh-plot` directive.

**Comment by tomscambler** [comment]
working on this

**Comment by mosc9575** [comment]
@tomscambler Are you still working on this and do you have any ideas or results yet?
