### ISSUE TITLE
Implement `Widget.disabled`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1376]
Currently only buttons implement this property. Note that `Plot` is a `Widget`, so it should allow this too.

**Comment by bill10** [comment]
any progress? or workaround?

**Comment by tobyhodges** [comment]
the `Slider` widget has a `disabled` attribute, which can be set to `True` to disable and grey out the slider. Other widgets also have the attribute, but don't change their behaviour based on its value. This is true for the `TextInput` widget, for example. I haven't tested the others, but I would guess that it works for the `Button` widget. You can see an example of usage in [this script](https://github.com/tobyhodges/timers/blob/master/browsertimer.py) for `bokeh serve` that I wrote recently.

**Comment by bill10** [comment]
@tobyhodges thanks for the comment. I found too that the disabled attribute works for button. However, it doesn't work for TextInput. I want to disable textinput when the app is running.

**Comment by birdsarah** [comment]
This is a fairly easy PR if someone would be willing to work on it. The core team are limited in resources.

**Comment by tobyhodges** [comment]
I've had a quick look, and unfortunately I think it would involve more understanding of BokehJS/JavaScript than I have right now. I will try to find the time to delve in a bit more deeply, though.

**Comment by bryevdv** [comment]
also refer to #4940 regarding making sure callbacks do not fire for disabled widgets

**Comment by mbreuilly** [comment]
Hello, 
I am using bokeh 0.12.6
I am also interested in this disabled property for various widgets (Select, TextInput), and I did not find a workaround for it.
Has this been fixed in a more recent version of Bokeh? or is this still an on-going process?
thank you very much for your help

**Comment by herm** [comment]
I tested most widgets with the current version from git (8055a93d4dceb31b3b6de91b5d6888b3f1c6b371). 
Working: AutocompleteInput, DatePicker, PasswordInput, TextInput, RangeSlider, Slider
Not working: Select, MultiSelect
