### ISSUE TITLE
Remove twitter icon link from docs and other properties

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13772]
Docs still present a twitter icon link, but we do not really engage on twitter any more. I think it can be removed. 

<img width="277" alt="Screenshot 2024-03-19 at 10 58 48" src="https://github.com/bokeh/bokeh/assets/1078448/07f66059-f84c-4f59-b114-5d90a96280c0">

cc @bokeh/dev

**Comment by Azaya89** [comment]
The Bokeh twitter account liked and retweeted some of my NF/SDG tweets.

**Comment by bryevdv** [comment]
RIght there is a minimal level of activity going on, which is fine for anyone that wants to engage there. I don't think we need to shutter the account, but personally I don't feel the need at this point to actively promote it any longer, either. 

Separately, it's probably reasonable to keep periodically evaluating other services for OSS comms interest.
