### ISSUE TITLE
GMap example not showing glyphs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13771]
With 3.4.0 the scatter markers are not appearing on the gmap example:

https://docs.bokeh.org/en/3.4.0/docs/examples/topics/geo/gmap.html

<img width="977" alt="Screenshot 2024-03-19 at 10 57 28" src="https://github.com/bokeh/bokeh/assets/1078448/3d933e75-d3a0-4dd5-804f-2ba05c8d10ab">

**Comment by bryevdv** [comment]
As a (probably) separate aside, GMaps API also warns:
> Google Maps JavaScript API has been loaded directly without loading=async. This can result in suboptimal performance. For best-practice loading patterns please see https://goo.gle/js-api-loading

**Comment by hakan-77** [comment]
@bryevdv I can confirm this is still the case with 3.4.1

**Comment by bryevdv** [comment]
Triaging for 3.5 but this should ideally be backported to 3.4.x

**Comment by mattpap** [comment]
This was broken in PR #13554. Projections are applied in secondary glyphs to the original data, leading to invalid coordinates or even NaNs.

**Comment by bryevdv** [comment]
@mattpap is it not possible to backport this fix? Otherwise all of 3.4.x will be broken

**Comment by mattpap** [comment]
It should be possible. In fact the PR is marked as "needs backport". We just didn't get to releasing 3.4.2. I will do that when 3.5.0rc1 is finalized (waiting for PR #13918 fixing `TapTool.mode` and a few other PRs).
