### ISSUE TITLE
[BUG] 3.4.0: Selection glyph no longer employs selection_glyph properties

### ISSUE THREAD

**Issue by CTPassion** [bokeh/bokeh#13803]
### Software versions

Python version        :  3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
IPython version       :  (not installed)
Tornado version       :  6.4
Bokeh version         :  3.4.0
BokehJS static path   :  D:\COODE\Coode-PI-E2E-Reporting\venv\Lib\site-packages\bokeh\server\static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-10-10.0.22621-SP0

### Expected behavior

Selected glyphs and non selected glyphs adhere to their supplied properties when a selection is made:

e.g. on the webpage example:
[bokeh docs example](https://docs.bokeh.org/en/3.3.0/docs/user_guide/topics/graph.html#interaction-policies)

### Observed behavior

All nodes become clear and the selected node invisible

### Example code

```Python
import networkx as nx

from bokeh.models import (BoxSelectTool, HoverTool, MultiLine,
                          NodesAndLinkedEdges, Plot, Range1d, Scatter, TapTool)
from bokeh.palettes import Spectral4
from bokeh.plotting import from_networkx, show

G = nx.karate_club_graph()

plot = Plot(width=400, height=400,
            x_range=Range1d(-1.1,1.1), y_range=Range1d(-1.1,1.1))
plot.title.text = "Graph Interaction Demonstration"

plot.add_tools(HoverTool(tooltips=None), TapTool(), BoxSelectTool())

graph_renderer = from_networkx(G, nx.circular_layout, scale=1, center=(0,0))

graph_renderer.node_renderer.glyph = Scatter(size=15, fill_color=Spectral4[0])
graph_renderer.node_renderer.selection_glyph = Scatter(size=15, fill_color=Spectral4[2])
graph_renderer.node_renderer.hover_glyph = Scatter(size=15, fill_color=Spectral4[1])

graph_renderer.edge_renderer.glyph = MultiLine(line_color="#CCCCCC", line_alpha=0.8, line_width=5)
graph_renderer.edge_renderer.selection_glyph = MultiLine(line_color=Spectral4[2], line_width=5)
graph_renderer.edge_renderer.hover_glyph = MultiLine(line_color=Spectral4[1], line_width=5)

graph_renderer.selection_policy = NodesAndLinkedEdges()
graph_renderer.inspection_policy = NodesAndLinkedEdges()

plot.renderers.append(graph_renderer)

show(plot)
```

### Stack traceback or browser console output

-

### Screenshots

3.4.0:
![image](https://github.com/bokeh/bokeh/assets/60933427/8080ae04-3810-4069-90d1-086a16c3193b)
3.3.0:
![image](https://github.com/bokeh/bokeh/assets/60933427/f4b87067-672f-403d-92a5-84c933ea632e)

**Comment by CTPassion** [comment]
@mattpap any reason this is a 3.5 milestone? It should be in 3.4.1 as this is a broken change from 3.3 and is a real problem in my application, which now relies on the newest panel 1.4.0 which has bokeh >3.3.0 as a requirement.

**Comment by bryevdv** [comment]
@CTPassion we almost always land on the current default branch and then collect backports for point releases.
