### ISSUE TITLE
[BUG]  Can't set reuse_port in bokeh.server.util  bind_sockets

### ISSUE THREAD

**Issue by emekelburg** [bokeh/bokeh#13812]
### Software versions

bokeh==3.2.2

### Expected behavior

When creating a socket for an embedded bokeh server within a Flask application, it is currently not possible to set the tornado.netutil option reuse_port.  This leads to an issue with subsequent containerization in scenarios where specific ports need to be opened rather than all ports.   Allowing the user to set this option, and providing the argument to tornato.netutil as "netutil.bind_sockets(port=port or 0, address=address, reuse_port = reuse_port)" solves the issue. 

### Observed behavior

See above. 

### Example code

```Python
sockets, port = bind_sockets("localhost", port=9080)  fails in the context of a Flask web-app in an embed scenario.
```

### Stack traceback or browser console output

solution provided in pull request

**Comment by bryevdv** [comment]
As I stated in the PR, I am initially skeptical that this function is something that end-users should be using at all, it's a specialized helper for internal Bokeh server implementation. I think if users need `netutil.bind_sockets` they should just use `netutil.bind_sockets` directly.

**Comment by emekelburg** [comment]
You are making a great point, thanks for sharing your perspective.    I
agree with you, overkill to implement in the bokeh helper function.
