### ISSUE TITLE
Require way to pass SSL options to Bokeh tornado server

### ISSUE THREAD

**Issue by davidljung** [bokeh/bokeh#1383]
Increasingly, many websites and corporate environments are mandating HTTPS only for web services and sites.

The bokeh-server can be started with port 443, but there is no way to pass SSL certificate options.
In bokeh/server/start.py, the Tornado server is started via the following code:

    tornado_app = make_tornado_app(flask_app=app)
    server = HTTPServer(tornado_app)
    server.listen(server_settings.port, server_settings.ip)
    ioloop.IOLoop.instance().start() 

In order to start it using SSL, the ssl_options param need to be passed somehow: something like:

    tornado_app = make_tornado_app(flask_app=app)
    server = HTTPServer(tornado_app,
                        ssl_options={
                             'certfile': server_settings.certfile,
                             'keyfile':  server_settings.keyfile
                        })
    server.listen(server_settings.port, server_settings.ip)
    ioloop.IOLoop.instance().start()

Unsure if there are other places in the code or JS where http:// is explicitly used.

**Comment by bryevdv** [comment]
@davidljung The is still a work in progress, but check out https://github.com/bokeh/bokeh/pull/1777 in case there is anything useful there too you (or if you have helpful information to add!)

**Comment by bryevdv** [comment]
Since we are finally beginning to document deploy options in earnest, I am closing this discussion.
