### ISSUE TITLE
Tap tool default mode should select+unselect, but not append

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13831]
Original ref: https://discourse.bokeh.org/t/taptool-on-a-pie-chart-reopens-all-previous-taps/11448/6

In Bokeh 3.4.x the tap tool seems to be in permanent "append" mode, i.e. it always does what I would only expect to see if `shift` was added to a tap. 

This can be seen in the [`color_scatter` example in in the gallery](https://docs.bokeh.org/en/3.4.1/docs/examples/basic/scatters/color_scatter.html). Here is the result of just randomly clicking many places with no shift or other modifier added:

<img width="674" alt="Screenshot 2024-04-17 at 10 35 46" src="https://github.com/bokeh/bokeh/assets/1078448/1f4286c3-f2fe-4da7-8238-5f59117fc297">

This does not occur with the 3.3.x version of the gallery example -- each new tap replaces the previous selection. 

cc @bokeh/dev I have triaged `discussion` for now but I believe this is a bug/regression (and merits a 3.4.2 release).

**Comment by mattpap** [comment]
Since bokeh 3.4 the default for tap tool is `xor` mode. It may appear to look like the tool is in `append` mode, but in `append` mode the user can only add selected data points, but not remove them, which the main benefit of `xor` mode. We switched to `xor` default, because users wanted to be able to deselect points and especially toggle data points.

The case from discourse the prompted this discussion silently assumes `replace` mode, which now requires explicit specification. The best way, that works with all modes, would be to keep track of selected data points and perform actions only for newly selected data points. Currently there is no built-in functionality for this.

**Comment by bryevdv** [comment]
cc @bokeh/dev I think this change should be re-visited. It certainly makes sense to offer this mode for some niche cases, but I don't think it makes sense as the default (and it clearly defies some user's expectations as well as seen on the discourse). This is especially jarring in plots like pie or bar charts where there are only a handful of elements to select. This also puts one tool on different footing than all other tools which is not good for simple documentation. Many users have used tap selection as part of a larger UI, e.g. to trigger some other drill down or other UI update and this change breaks all of those usages.

**Comment by bryevdv** [comment]
FWIW I would be ok with this default behavior:

* tapping new points replaces the existing selection (previous behavior)
* tapping an already selected point unselects it (new behavior)

i.e. it is very specifically the "additive" nature of this xor-mode, where tapping a new point adds to an existing selection, that is the problem

**Comment by philippjfr** [comment]
I agree with that proposal. Let's allow deselect but not adding by default.

**Comment by mattpap** [comment]
Do we want this behavior to be implemented in place of `replace` mode (just for tap tool) or should I introduce a new mode?

**Comment by bryevdv** [comment]
I actually don't know what all the current modes are to say, where are they enumerated/described?

Well, I guess they are listed [here](https://docs.bokeh.org/en/latest/docs/reference/core/enums.html#bokeh.core.enums.SelectionMode)

> SelectionMode = Enumeration(replace, append, intersect, subtract, xor)

I guess it's a little weird, I don't think one set of selection modes really neatly covers all the tools in the same way. i.e the re-select to un-select that can  make sense for a tap is nearly impossible to imagine being useful on a lasso tool. I think I lean towards: new mode, e.g. `replace-foo` with that being the default for tap. That's in the interest of not having "replace" mean multiple things, but also being able to say "*a* replace mode" is the default for all tools, which is less awkward to explain.  But I am interested in others' thoughts.

**Comment by gmerritt123** [comment]
Going through updating my stuff to 3.4 right now and THANK YOU for documenting this change.
