### ISSUE TITLE
[BUG] <b> and <strong> ignored in tooltips on Firefox

### ISSUE THREAD

**Issue by gdementen** [bokeh/bokeh#13852]
### Software versions

Bokeh JS version: 3.3+ (probably much earlier but I did not test)

### Browser name and version

Firefox 124.0.2

### Expected behavior

Span in tooltip appears bold

### Observed behavior

It appears as normal text (see screenshots of the documentation below). Interestingly, while using `<b>my text</b>` (or `<strong>my text</strong>`) does not work, using `<span style="font-weight: bold;">my text</span>` **does** work.

### Example code

```Python
The documentation itself exhibits this behaviour:
https://docs.bokeh.org/en/latest/docs/user_guide/interaction/tooltips.html#tooltip-contents
https://docs.bokeh.org/en/latest/docs/user_guide/interaction/tools.html#custom-tooltip
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/832092/dcd5b7cb-6b7b-446e-999a-b623cc47e088)
![image](https://github.com/bokeh/bokeh/assets/832092/c775f4f3-f445-4748-ac8a-251b05d42a7a)

**Comment by gdementen** [comment]
In Google Chrome, it seems to work fine.

**Comment by mattpap** [comment]
`Tooltip`'s stylesheet did override `font-weight` for some reason. On top of that Chromium and Firefox disagree on how user agent stylesheets are defined, thus the difference in appearance.

**Comment by gdementen** [comment]
Thanks for the quick reaction !
