### ISSUE TITLE
Move sampledata files to pip/conda installable package

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13856]
Moving the sampledata to an  installable package will afford the following:

* `bokeh_sampledata` can depend on `pandas` potentially allowing the main package to drop `pandas`
* having an installable package may help with `pyodide` usage (however, it will be a large package... likely tens of MB)
* custom S3 download machinery can be removed from the main repo

I think the simplest thing to do will be to keep all the existing `bokeh.sampledata.foo` modules as shims, and the ones that need to can try to access their data from the separate `bokeh_sampledata` module. If `bokeh_sampledata` cannot be imported then an actionable error can be raised. This approach will avoid any changes to examples and docs, which would otherwise be significant if we want to rip `bokeh.sampledata` out of the main package entirely. 

If any of the "small" datasets currently shipped with the package depend on `pandas` they will need to be moved. Or maybe we just move all the actual data, but keep the `bokeh.sampledata` shim module structure intact. 

cc @philippjfr

**Comment by bryevdv** [comment]
I have most of a `bokeh_sampledata` repo set up, I'll push a new repo to GitHub once tests are moved over and package builds are working. 

@bokeh/dev would it be sufficient to just generate a PyPI package for this? Or do we need to also generate a conda package?

**Comment by philippjfr** [comment]
Thanks for pushing forward with this so quickly. I'm currently a little swamped but hope to take a closer look early next week. A conda package would certainly be nice.

**Comment by bryevdv** [comment]
@bokeh/dev the new repository is here https://github.com/bokeh/bokeh_sampledata

Still need to set up CI, etc. If there is any more modern way to streamline package building and publishing I am all ears.

**Comment by bryevdv** [comment]
As for how to integrate this here with a minimal of disruption, I have a vague idea of creating shim files in this repo that use module `__getattr__` and `__dir__` to make everything appear under `bokeh.sampledata` as it does currently. I haven't actually tried to make that work yet, though, especially with docs build. 

I was also considering date-based versioning for the new package as well.

**Comment by hoxbro** [comment]
> I have a vague idea of creating shim files in this repo that use module `__getattr__` and `__dir__` to make everything appear under `bokeh.sampledata` as it does currently.

This should work. Another thing is you will need `if TYPE_CHECKING:` with the actual imports, to make them discoverable with LSPs.

**Comment by bryevdv** [comment]
@Hoxbro I am not sure I follow your comment, please have a look at the actual PR and let me know if there are some specific changes you think are needed.
