### ISSUE TITLE
[BUG] figure.circle produces empty plot when used datetime axis

### ISSUE THREAD

**Issue by user529481** [bokeh/bokeh#13868]
### Software versions

Python version        :  3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
IPython version       :  8.15.0
Tornado version       :  6.3.3
Bokeh version         :  3.4.1
BokehJS static path   :  /opt/homebrew/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v22.0.0
npm version           :  10.5.1
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-14.4.1-arm64-arm-64bit

### Browser name and version

Edge 124.0.2478.51

### Expected behavior

I'm looking to expand the circle on hover and from the documentation, it looks like figure.circle is the only way to do it. I took the example from the documentation and replaced the x-axis with datetime and the plot is empty. This is where the example is lifted from:

https://docs.bokeh.org/en/latest/docs/user_guide/styling/plots.html#overriding-non-visual-properties

As I understand there is currently no way to expand the datapoint on hover in a timeseries graph. Is that correct?

### Observed behavior

Simply replacing the x values to datetime caused the plot to be empty. 

### Example code

```Python
import numpy as np
import pandas as pd
from datetime import datetime
from bokeh.core.properties import field
from bokeh.io import show
from bokeh.models import BoxAnnotation, Indexed, Rect, Tooltip
from bokeh.palettes import Spectral11
from bokeh.plotting import figure

N = 50

# This x works
x = np.random.random(size=N)*100

# This x does not
x = pd.date_range(start=datetime(2024, 1, 1), periods=N)


y = np.random.random(size=N)*100
radii = np.random.uniform(1, 5, size=N)

p = figure(tools=["hover"], x_axis_type='datetime')

radii = np.ones(N) * 1
radii_big = radii*2
cr = p.circle(
    x, y, radius=radii, color='blue',
    hover_fill_alpha=1, # mix `hover_` attributes with manual setup below
)

# there is no `hover_radius` so we have set things manually
cr.data_source.data["radii_big"] = radii_big
cr.hover_glyph.radius = field("radii_big")

show(p)
```

### Screenshots

<img width="650" alt="Capture d’écran 2024-05-05 à 17 16 06" src="https://github.com/bokeh/bokeh/assets/71951740/f452f847-bd81-4843-b973-1d5983de9123">
^ With datetime x

<img width="606" alt="Capture d’écran 2024-05-05 à 17 16 56" src="https://github.com/bokeh/bokeh/assets/71951740/ef6318be-01d4-4b45-9b44-378e66b8d8e9">
^ with non-datetime x

**Comment by bryevdv** [comment]
This capability was added in 3.4 in PR https://github.com/bokeh/bokeh/pull/13554

In fact, your problem is a usage issue. [As stated in the documentation](https://docs.bokeh.org/en/latest/docs/user_guide/topics/timeseries.html#units), the scale of datetime axes is "milliseconds since epoch" In your code you are asking for circles with a 1 millisecond radius on a scale of months. So, entirely predictably, they are "invisible". If you change the radius to be a reasonable number of milliseconds for axis that spans months: 
```
radii = np.ones(N) * 100000000
```
Then the circles show up, and the dilation as well:

<img width="556" alt="Screenshot 2024-05-05 at 19 05 46" src="https://github.com/bokeh/bokeh/assets/1078448/ab07e07b-af2c-48af-a898-a3f4586aec99">

However, I might suggest using `scatter` rather than `circle` which would afford configuring a `size` in pixels, rather that a `radius` in data units.

Lastly: I am trying to be patient since you seem to be both new to Bokeh and having struggles. But given that, I'd ask you to consider that if you are hitting an issue, it is entirely possible that it is a usage issue. The GitHub issue tracker is reserved for bug reports and feature requests only. It is not the appropriate place to seek general support or help with usage questions. For that, use the [Community Discourse site](https://discourse.bokeh.org).

**Comment by user529481** [comment]
Since you closed my discussion point, have you considered that those OSS contributors left because the code base is not friendly to contributors? I spent the better part of the weekend going through the code base and undisciplined is how I would describe certain aspects of the code base, granted it is OSS but still. To be fair I think Bokeh is the best graphing library out there for what it does, and I wouldn't dream of writing anything even close to it on my best days, let alone trying to do it as an open source project. I know it doesn't sound like it because I'm a prick by nature, but I'm actually a huge fan of bokeh and I'm not being sarcastic. 

Alas not that it matters but I don't believe there is any way for scatter to have the on hover effect of scaling size. I spent a couple of hours trying to do this to no avail with the provided API.

Thanks for the link. It makes a lot of sense that radius is measured in milliseconds and I should have made the connection. Usage error, my mistake.

**Comment by bryevdv** [comment]
> Alas not that it matters but I don't believe there is any way for scatter to have the on hover effect of scaling size.

I literally posted a screenshot above demonstrates that it is possible (with 3.4+). Here's another, explicitly with `scatter` and `size`:

<img width="449" alt="Screenshot 2024-05-06 at 13 31 49" src="https://github.com/bokeh/bokeh/assets/1078448/0a6f3f88-0e80-4e69-990e-189ae21d625b">


But if you would like to discuss usage questions, the community discourse is the correct place, not the tracker, as I already stated.

**Comment by bryevdv** [comment]
Also, re:

> have you considered that those OSS contributors left because the code base is not friendly to contributors?

You misunderstand, completely. That statement was about *me*, seriously considering leaving OSS development after nearly 20 years, because I don't want to put up with users who are "pricks by nature" (***your words***) any longer.

**Comment by user529481** [comment]
That is a relevant clarification. I'm not in your shoes and frankly I don't do what you do not only because I can't, but I don't want to for the same reason you're thinking of leaving.  But it's safe to say a lot of people use Bokeh for things which are a net positive in the world, and I'd be doing them a disservice if I didn't ask you to stay your course. 

Not sure you care, but I thought you should know I wasn't just willy nilly trying to piss maintainers off, and I didn't know you wrote Bokeh. My frustration came from spending Friday + the entire weekend adding a border around a plot & trying to get a data point to pop on hover, and I was able to only do one of those things. And I did go through the documentation --  in fact it was the only thing I could do because I couldn't make sense of the code base, and a lot of the CSS related docs did not work for me. 

I apologize.
