### ISSUE TITLE
[BUG] NPM package has types (*.d.ts) in incorrect location

### ISSUE THREAD

**Issue by BobbyL2k** [bokeh/bokeh#13886]
### Software versions

BokehJS version: broken since 3.1.0 to current version 3.4.1

### Browser name and version

-

### Jupyter notebook / Jupyter Lab version

-

### Expected behavior

Import Bokeh in TypeScript should work when installing

`npm install @bokeh/bokehjs`

```typescript
import * as Bokeh from '@bokeh/bokehjs';
```

TypeScript should not complain about type information being missing.

`node_modules/@bokeh/bokehjs/package.json` expect types information under `build/js/types` (see https://github.com/bokeh/bokeh/blob/cf19b57cb2a5a9301bad882b3977fc4371ed44da/bokehjs/package.json#L41)

However the pre-compiled files under build/js do not match this layout.
Types are located under `build/js/lib` instead of `build/js/types`.

This is easily verifiable by going to NPM package registry and see how there is no `types` directory

https://www.npmjs.com/package/@bokeh/bokehjs?activeTab=code

<img width="784" alt="Screenshot 2567-05-08 at 23 31 37" src="https://github.com/bokeh/bokeh/assets/9302384/f6b208dc-653f-4cf9-9cef-e8aea8d9f5f2">

### Observed behavior

````
Could not find a declaration file for module '@bokeh/bokehjs'. '/path/to/project/node_modules/@bokeh/bokehjs/build/js/lib/bokeh.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/bokeh__bokehjs` if it exists or add a new declaration (.d.ts) file containing `declare module '@bokeh/bokehjs';`
```

### Example code

```typescript
import * as Bokeh from '@bokeh/bokehjs';
```


### Stack traceback or browser console output

_No response_

### Screenshots

_No response_

**Comment by bryevdv** [comment]
@mattpap do you have any input on this?
