### ISSUE TITLE
[FEATURE] Custom sorting of columns in a table

### ISSUE THREAD

**Issue by hmijail** [bokeh/bokeh#13893]
### Problem description

A column in a table might contain data that doesn't sort properly as text or as numbers. E.g.:
AB 1
AB 10
AB 2

### Feature description

I could imagine this being implemented either as having a custom JS function to do the sorting, and/or as having a custom JS function to change how values are displayed, independently of the sorting.

### Potential alternatives

I am currently modifying my tables adding a number prefix and/or sorting them beforehand so that they start in an appropriate state. Obviously this doesn't survive past the first table interaction.

**Comment by hmijail** [comment]
A commenter [here](https://discourse.bokeh.org/t/is-it-possible-to-sort-a-datatable-column-using-a-custom-function/7243) asked for a function to sort by e.g. absolute value. I don't think this would be doable if only value representation can be changed.

**Comment by bryevdv** [comment]
related:
*  #11104

Also noting that SlickGrid's sorting docs are here: https://github.com/mleibman/SlickGrid/wiki/DataView#sorting

and an SO outline for custom individual column sorters here: https://stackoverflow.com/questions/22559891/slickgrid-custom-column-sorters

It does seem like we could add a hook here for extending control of sorting, so I will tentatively triage this as `feature`.
