### ISSUE TITLE
`Tooltip` is initially attached to the DOM when it shouldn't be

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13894]
See bottom left corner:

![image](https://github.com/bokeh/bokeh/assets/27475/9215c690-1058-47a0-b81c-bc5790712779)

(from [color_scatter](https://github.com/bokeh/bokeh/blob/branch-3.5/examples/basic/scatters/color_scatter.py) example).

Goes away after the first hover.

**Comment by trev-gulls** [comment]
Can you post the code for the figure shown in the image?
