### ISSUE TITLE
[FEATURE] triangle relative size by data units

### ISSUE THREAD

**Issue by hxse** [bokeh/bokeh#13905]
### Problem description

The size property of the triangle is pixel units, but I want to find a size property by data units, like radius property of circle.

### Feature description

Add data units property for change triangle size.

### Potential alternatives

I don't know what to do.

**Comment by bryevdv** [comment]
I think I am 👎  on this. This use-case can presently be accomplished via `Patches` or `MultiPolygons` and I don't it is common enough to warrant the added complexity of an entire new glyph. I *might* be convinced that adding a generic "n-gon" glyph with a data `radius` is worth it.

**Comment by bryevdv** [comment]
@ianthomas23 how difficult would a generic "n-gon" webgl implementation be?

**Comment by ianthomas23** [comment]
@bryevdv If you are talking regular polygons, so convex, then it is trivial. The WebGL marker code already has triangle, square and hexagon and could easily be generalised.

**Comment by bryevdv** [comment]
Completed, modulo a WebGL implementation I will make a separate issue for.

**Comment by ianthomas23** [comment]
> Completed, modulo a WebGL implementation I will make a separate issue for.

You can assign that to me, I've already started work on it.
