### ISSUE TITLE
[BUG] Figure not displaying in Dash app (sad smiley) when width >= 20000

### ISSUE THREAD

**Issue by Ericbf-10** [bokeh/bokeh#13907]
### Software versions

Python version      :  3.11.6 (main, Dec  4 2023, 09:14:42) [GCC 9.4.0]
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.1.1
BokehJS static path :  /home/env/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v16.20.2
npm version         :  8.19.4
Operating system    :  Linux-5.15.0-91-generic-x86_64-with-glibc2.31

### Browser name and version

Microsoft Edge, Version 125.0.2535.51 (Official build) (64-bit)

### Expected behavior

Correct display of the plot.
![good_bokeh](https://github.com/bokeh/bokeh/assets/101256121/6e66d343-4cf7-4e2c-a091-a203b5a995eb)

### Observed behavior

Sad smiley where the plot should be when width is around or more than 20.000px. I don't understand why the plot won't show even if the same amount of data is being displayed. I am only changing the dimensions of the plot, not the amount of points to be plotted. Is there a way to display very large plots with bokeh?
![bad_bokeh](https://github.com/bokeh/bokeh/assets/101256121/e96f1b98-ab0b-425c-a03e-9c39e65b4e42)

### Example code

```Python
# Import required libraries
import dash
from dash import html
from dash.dependencies import Input, Output
from bokeh.plotting import figure
from bokeh.embed import file_html
from bokeh.resources import CDN
import numpy as np

# Initialize the app
app = dash.Dash(__name__)

# Define the app
app.layout = html.Div([
    html.Button("Generate Plot", id="generate-button"),
    html.Iframe(id="bokeh-container", srcDoc=None, style={"margin-left": "20px", "width": "20000px", "height": "1000px"})
])

# Define callback to update graph
@app.callback(
    Output("bokeh-container", "srcDoc"),
    [Input("generate-button", "n_clicks")]
)
def update_graph(n_clicks):
    if n_clicks is None:
        return dash.no_update
    else:
        # Create a new plot
        p = figure(sizing_mode="scale_width")

        # Create random data
        x = np.random.random(size=2000) * 100
        y = np.random.random(size=2000) * 100

        # Add scatter points
        p.circle(x, y, size=5, color="navy", alpha=0.5)

        # Convert to html
        html_bokeh = file_html(p, CDN)
        
        return html_bokeh

# Run the app
if __name__ == '__main__':
	app.run_server( 
		host = "0.0.0.0",
		port = "12328",           
		debug=False, 
        dev_tools_hot_reload=True
	)
```

**Comment by mattpap** [comment]
This is a browser limitation wrt. the maximum dimensions of HTML5 canvas. See prior discussion in #9115 and related #13645. See also e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#maximum_canvas_size. I can suggest trying another browser to see if it has higher limits or perhaps reducing height and trading it for width, if width limit wasn't reached, but total number of pixels was.
