### ISSUE TITLE
[BUG] Bokeh 3.5 no longer allow custom properties for HTMLAttr

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13919]
### Software versions

```
Python version        :  3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
IPython version       :  8.24.0
Tornado version       :  6.4
Bokeh version         :  3.5.0.dev4
BokehJS static path   :  /home/shh/projects/holoviz/repos/panel/.pixi/envs/test-ui/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  v20.12.2
npm version           :  10.5.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
```

### Expected behavior

- 

### Observed behavior

Trying to update Panel to work with Bokeh 3.5 dev 4, I stumbled upon the following error message:

![image](https://github.com/bokeh/bokeh/assets/19758978/81a3a416-fe2e-498c-8b36-2c523f6a5e28)

For now I have cast to `any`, see the following commit https://github.com/holoviz/panel/pull/6883/commits/07c1d83b3fcda18d0a650c7036a7eb9107d33b13

### Example code

```Python
-
```

**Comment by mattpap** [comment]
This is a side effect of PR #13735. All attributes that `div()` and such allow, need to be added to `core/dom`.
