### ISSUE TITLE
[BUG] When I want to insert a picture into the bokeh icon and save it as an HTML file, I get a white screen when I open it. Why?

### ISSUE THREAD

**Issue by qiuqc1** [bokeh/bokeh#13930]
### Software versions

Python version        :  3.9.19 (main, May  6 2024, 19:43:03) 
IPython version       :  8.18.1
Tornado version       :  6.3.3
Bokeh version         :  3.4.0
BokehJS static path   :  /root/Software/anaconda3/envs/py39bokeh/lib/python3.9/site-packages/bokeh/server/static
node.js version       :  v18.18.2
npm version           :  9.8.1
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-5.4.54-1.0.0.std7c.el7.2.x86_64-x86_64-with-glibc2.31

### Browser name and version

chrome

### Expected behavior

When I want to insert an image into a bokeh icon and save it as an HTML file, I hope to get a bokeh icon containing the image

### Observed behavior

When I use the bokeh interface and want to insert an image into the bokeh icon, the image is imported, the source in the form of ColumnDataSource, source.data also has an array, the figure is created, and the image is put into it, and finally saved as HTML format, but the opened HTML file is blank, there is no bokeh icon, and no image
I exported source.data from pdb and combined it with gpt, but it still couldn't be solved. I think the problem is still in the combination of source and figure. I also tried adding RGBA conversion, but my image is jpg, which didn't help. I wrote it in Python on the server and need to save it as an HTML file and view the effect locally

So how I solved this problem

### Example code

```Python
import os
import cv2
import base64
import io
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
from bokeh.layouts import column, row
from bokeh.embed import file_html
from bokeh.resources import CDN
from bokeh.models import ColumnDataSource, Slider
from bokeh.plotting import curdoc, figure, output_file
from bokeh.io import curdoc, save
from bokeh.models.callbacks import CustomJS
from bokeh.application import Application

image_folder = "/XXX/visualize/20240604/photo3"

output_folder_bokeh = 'XXX/video/bokeh'
output_file_path = os.path.join(output_folder_bokeh, 'oneph4.html') 

compressed_images = []
def generate_html2(output_file_path):
    output_file(output_file_path, title="Bokeh Image Display")
    target_height = 600
    image_path = "/XXX/visualize/gt/front/n015-2018-07-11-11-54-16+0800__CAM_FRONT__1531281440262460.jpg" 

    # compressed_image = compress_image(image_path, target_height)
    compressed_image = Image.open(image_path)

    img_array = np.array(compressed_image) 
    height, width, _ = img_array.shape
    source = ColumnDataSource(data=dict(image=[img_array], x=[0], y=[0], dw=[width], dh=[height]))  
    print("source.data:", source.data)
    p = figure(x_range=(0, width), y_range=(0, height), toolbar_location=None, tools="") 
    p.image(image='image', x='x', y='y', dw='dw', dh='dh', source=source)  
    save(p, filename=output_file_path)
    print(f'{output_file_path} finish')

generate_html2(output_file_path)
```

### Stack traceback or browser console output

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bokeh Image Display</title>
    <style>
      html, body {
        box-sizing: border-box;
        display: flow-root;
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-3.4.0.min.js"></script>
    <script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
  </head>
  <body>
    <div id="de9a45a2-b55b-4435-86c0-60e0b01c076a" data-root-id="p1004" style="display: contents;"></div>
  
    <script type="application/json" id="d9c5b390-f798-4693-ba7f-30335a15fdb3">
      {"14efd88b-75c4-4af1-ac22-22912f7f5b12":{"version":"3.4.0","title":"Bokeh Application","roots":[{"type":"object","name":"Figure","id":"p1004","attributes":{"x_range":{"type":"object","name":"Range1d","id":"p1013","attributes":{"end":1600}},"y_range":{"type":"object","name":"Range1d","id":"p1014","attributes":{"end":900}},"x_scale":{"type":"object","name":"LinearScale","id":"p1015"},"y_scale":{"type":"object","name":"LinearScale","id":"p1016"},"title":{"type":"object","name":"Title","id":"p1011"},"renderers":[{"type":"object","name":"GlyphRenderer","id":"p1039","attributes":{"data_source":{"type":"object","name":"ColumnDataSource","id":"p1001","attributes":{"selected":{"type":"object","name":"Selection","id":"p1002","attributes":{"indices":[],"line_indices":[]}},"selection_policy":{"type":"object","name":"UnionRenderers","id":"p1003"},"data":{"type":"map","entries":[["image",[{"type":"ndarray","array":{"type":"bytes","data":.....
    </script>
    <script type="text/javascript">
      (function() {
        const fn = function() {
          Bokeh.safely(function() {
            (function(root) {
              function embed_document(root) {
              const docs_json = document.getElementById('d9c5b390-f798-4693-ba7f-30335a15fdb3').textContent;
              const render_items = [{"docid":"14efd88b-75c4-4af1-ac22-22912f7f5b12","roots":{"p1004":"de9a45a2-b55b-4435-86c0-60e0b01c076a"},"root_ids":["p1004"]}];
              root.Bokeh.embed.embed_items(docs_json, render_items);
              }
              if (root.Bokeh !== undefined) {
                embed_document(root);
              } else {
                let attempts = 0;
                const timer = setInterval(function(root) {
                  if (root.Bokeh !== undefined) {
                    clearInterval(timer);
                    embed_document(root);
                  } else {
                    attempts++;
                    if (attempts > 100) {
                      clearInterval(timer);
                      console.log("Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing");
                    }
                  }
                }, 10, root)
              }
            })(window);
          });
        };
        if (document.readyState != "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
      })();
    </script>
  </body>
</html>
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/105922275/3316f0c4-77d1-44cc-bd0b-127af6a03d77)

**Comment by mattpap** [comment]
We will need to see output (any errors and/or warnings) from Chrome's DevTools console (Ctrl+Shif+I). At first glance the generated HTML looks fine, but ~~it's also incomplete, so it's hard to say~~ (need to put the code in triple backticks).

**Comment by mosc9575** [comment]
@qiuqc1 When running your example, I can see an error with the message `Uncaught (in promise) Error: expected a 2D array, not 3D`.

I updated the code so it is working on my machine. Please check out, if the code below works for you.

```
image_path = r"your\figure\path" 

# PIL
im = Image.open(image_path)
imarray = np.array(im.transpose(Image.FLIP_TOP_BOTTOM).convert("RGBA"))
imview = imarray.view(np.uint32).reshape(imarray.shape[:2])
height, width, _ = imarray.shape

# bokeh
source = ColumnDataSource(data=dict(image=[imview], x=[0], y=[0], dw=[width], dh=[height]))

p = figure(x_range=(0,imarray.shape[0]), y_range=(0, imarray.shape[1]))
p = figure(x_range=(0, width), y_range=(0, height), toolbar_location=None, tools="") 
p.image_rgba(image='image', x='x', y='y', dw='dw', dh='dh', source=source)  

show(p)
```

**Comment by qiuqc1** [comment]
> @qiuqc1 When running your example, I can see an error with the message `Uncaught (in promise) Error: expected a 2D array, not 3D`.
> 
> I updated the code so it is working on my machine. Please check out, if the code below works for you.
> 
> ```
> image_path = r"your\figure\path" 
> 
> # PIL
> im = Image.open(image_path)
> imarray = np.array(im.transpose(Image.FLIP_TOP_BOTTOM).convert("RGBA"))
> imview = imarray.view(np.uint32).reshape(imarray.shape[:2])
> height, width, _ = imarray.shape
> 
> # bokeh
> source = ColumnDataSource(data=dict(image=[imview], x=[0], y=[0], dw=[width], dh=[height]))
> 
> p = figure(x_range=(0,imarray.shape[0]), y_range=(0, imarray.shape[1]))
> p = figure(x_range=(0, width), y_range=(0, height), toolbar_location=None, tools="") 
> p.image_rgba(image='image', x='x', y='y', dw='dw', dh='dh', source=source)  
> 
> show(p)
> ```

Finally succeeded!!! Thank you so so so so much, I was stuck here for a long time.

**Comment by qiuqc1** [comment]
> We will need to see output (any errors and/or warnings) from Chrome's DevTools console (Ctrl+Shif+I). At first glance the generated HTML looks fine, but ~it's also incomplete, so it's hard to say~ (need to put the code in triple backticks).

In fact, after I executed the code, I did not encounter any warnings or errors. It directly generated an HTML file, and then when I opened the file, a white screen was displayed. But I have solved it now. Thank you very much.

**Comment by bryevdv** [comment]
> In fact, after I executed the code, I did not encounter any warnings or errors.

@qiuqc1 almost all of the actual work of Bokeh is done by BokehJS in the browser. Most errors will require opening the browser's JavaScript console to view (not much we can do about this, that's just the place where JS errors show up)
