### ISSUE TITLE
Search doesn't work on docs.bokeh.org

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13941]
Initially there errors in JS console:
```ts
Uncaught ReferenceError: $ is not defined
    at custom.js?v=22a1fd09:11:1
(anonymous) @ custom.js?v=22a1fd09:11
pydata-sphinx-theme.js:54 [PST]: Changed to light mode using the light theme.
pydata-sphinx-theme.js:570 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at T (pydata-sphinx-theme.js:570:5)
    at r (mixin.js:11:41)
    at pydata-sphinx-theme.js:584:1
T @ pydata-sphinx-theme.js:570
r @ mixin.js:11
(anonymous) @ pydata-sphinx-theme.js:584
await in (anonymous) (async)
c.a @ async module:49
937 @ pydata-sphinx-theme.js?digest=8d27b9dea8ad943066ae:1
c @ pydata-sphinx-theme.js?digest=8d27b9dea8ad943066ae:1
(anonymous) @ startup:4
(anonymous) @ pydata-sphinx-theme.js?digest=8d27b9dea8ad943066ae:1
```
Then clicking on the search field results in:
```ts
pydata-sphinx-theme.js:200 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at c (pydata-sphinx-theme.js:200:17)
    at HTMLButtonElement.i (pydata-sphinx-theme.js:211:15)
c @ pydata-sphinx-theme.js:200
i @ pydata-sphinx-theme.js:211
```
That's in Chromium and fails in an equivalent manner in Firefox.

**Comment by mattpap** [comment]
I'm referring to the top one, because there's another one on the page. Then on the search page there are three of them:
![image](https://github.com/bokeh/bokeh/assets/27475/d95e62a5-504c-489e-81b7-253b68ace0da)

**Comment by mosc9575** [comment]
The first few lines of the js console are related to the broken custom version version banner 

```
Uncaught ReferenceError: $ is not defined
    at custom.js?v=22a1fd09:11:1
(anonymous) @ custom.js?v=22a1fd09:11
pydata-sphinx-theme.js:54 [PST]: Changed to light mode using the light theme.
pydata-sphinx-theme.js:570 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at T (pydata-sphinx-theme.js:570:5)
    at r (mixin.js:11:41)
    at pydata-sphinx-theme.js:584:1
T @ pydata-sphinx-theme.js:570
r @ mixin.js:11
(anonymous) @ pydata-sphinx-theme.js:584
```

and should be solved by the PRs adressing the pydata-sphinx-theme banner.

**Comment by mosc9575** [comment]
@mattpap Runnig a search on the docs after the 3.4.2 release yesterday doesn't cause any error in the js console. Can we close this issue?

In fact there is a problem with search result for examples. Each example listed on https://docs.bokeh.org/en/latest/docs/examples.html will generate 3 links in the search.

* `examples/<name>.html`
* `examples/<name>.html#<name>`
* `examples/<name>.html#index-0`

But I think this is not what you wanted to be fixed.

**Comment by bryevdv** [comment]
Things seems to be working on the 3.5 docs as well with no issues or jquery console errors, so I will close this. @mosc9575 I'd suggest opening a separate issue for the other (thoughI am not sure what can be done)

<img width="1212" alt="Screenshot 2024-07-20 at 21 34 59" src="https://github.com/user-attachments/assets/0355c84d-1109-461b-969c-550664fac793">
<img width="687" alt="Screenshot 2024-07-20 at 21 35 10" src="https://github.com/user-attachments/assets/28aa15b3-8150-4a59-845f-92942f93d58f">
