### ISSUE TITLE
Bokeh documentation is not showing up on Bing and DuckDuckGo

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13943]
### Development Team members only

Currently, when you search for "bokeh documentation" on Bing or DuckDuckGo, no search results for the documentation website (https://docs.bokeh.org/en/latest/) come up. Does not seem to be issue with Holoviz packages.

Maybe this could be caused by http://bokeh.org/robots.txt. 

| Status | Search engine | Screenshot |
| --- | --- | --- |
| :green_circle:  | [Google](https://www.google.com/search?q=bokeh+documentation) | ![image](https://github.com/bokeh/bokeh/assets/19758978/ada6407b-a7a5-4d24-8533-0c096b2f1229) | 
|:red_circle: | [DuckDuckGo](https://duckduckgo.com/?t=h_&q=bokeh+documentation&ia=web) |![image](https://github.com/bokeh/bokeh/assets/19758978/41d94001-794e-4d7d-95b1-077db8b77529) |
| :red_circle: | [Bing](https://www.bing.com/search?q=bokeh+documentation) | ![image](https://github.com/bokeh/bokeh/assets/19758978/2fb068ab-8a7d-4df8-83c3-19df01d513d9)

**Comment by bryevdv** [comment]
> Maybe this could be caused by http://bokeh.org/robots.txt.

This seems unlikely, that's a separate domain. The file on the docs domain https://docs.bokeh.org/robots.txt is empty (panel does not seem to have a `robots.txt` at all) I am not sure what "should" be the case here, happy for any suggestions.

**Comment by bryevdv** [comment]
Seems like others have reported something similar:

* https://www.jessesquires.com/blog/2022/03/25/my-website-disappeared-from-bing-and-duckduckgo/
* https://webmasters.stackexchange.com/questions/142554/bing-and-duckduckgo-have-suddenly-stopped-indexing-my-website


Realistically, I guess someone is going to have to dive into https://www.bing.com/webmasters/help/Webmaster-Guidelines-30fba23a

**Comment by bryevdv** [comment]
BTW it seems like the services made some kind of change a few months ago. We used to get DDG traffic to the docs then it fell off a cliff in april

<img width="1113" alt="Screenshot 2024-06-27 at 09 05 41" src="https://github.com/bokeh/bokeh/assets/1078448/411b0213-4a30-4a6f-8e90-1a9cf08c51ca">

**Comment by hoxbro** [comment]
I emailed Bing earlier this year and got an answer today that they have fixed it. 
![image](https://github.com/user-attachments/assets/5beb9b55-78d0-4fc8-9ca6-3488c4144c2f)

And to confirm it:
![image](https://github.com/user-attachments/assets/b2608c3c-6337-437b-bbce-b4ca60620662)

**Comment by bryevdv** [comment]
Thanks @hoxbro !!

**Comment by bryevdv** [comment]
Just following up that the traffic from Bing is ticking back up in the Plausible metrics

<img width="1048" alt="Screenshot 2024-11-14 at 10 33 13" src="https://github.com/user-attachments/assets/55745845-d69d-4f60-bae2-29a04c212560">
