### ISSUE TITLE
[BUG] Image Glyph causing tons of unnecessary calls to set_data

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#13951]
### Software versions

Bokeh 3.4 - 3.5rc1

### Expected behavior

Bokeh should efficiently render image glyphs and avoid unnecessary re-computation of the data.

### Observed behavior

When plotting an image glyph, particularly with slightly more expensive colormapping operations such as the `EqHistColorMapper` there is a very noticeable slowdown while plotting, e.g. in this flame graph you can see the issue quite clearly:

<img width="557" alt="Screenshot 2024-06-26 at 11 38 47" src="https://github.com/bokeh/bokeh/assets/1550771/5712d117-97ca-4d34-b366-eab406c82b1f">

### Example code

```Python
Even a simple image plotting example demonstrates this quite well:


import numpy as np

from bokeh.plotting import figure, show
from bokeh.models import EqHistColorMapper
from bokeh.palettes import Viridis256 

x = np.linspace(0, 10, 300)
y = np.linspace(0, 10, 300)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx) * np.cos(yy)

p = figure(width=400, height=400)
p.x_range.range_padding = p.y_range.range_padding = 0

# must give a vector of image data for image parameter
cmapper = EqHistColorMapper(palette=Viridis256)
p.image(image=[d], x=0, y=0, dw=10, dh=10, color_mapper=cmapper, level="image")
p.grid.grid_line_width = 0.5

show(p)
```

**Comment by mattpap** [comment]
This is a side effect of PR #13554 and wasn't fixed in any subsequent PRs so far addressing issues that PR introduced.
