### ISSUE TITLE
Explicit selection glyph example broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13957]
ref: https://docs.bokeh.org/en/latest/docs/user_guide/styling/plots.html#selected-and-unselected-glyphs

Code there does this:
```python
plot = figure(width=400, height=400, tools="tap", title="Select a circle")
renderer = plot.scatter([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=50)

selected_scatter = Scatter(fill_alpha=1, fill_color="firebrick", line_color=None)
nonselected_scatter = Scatter(fill_alpha=0.2, fill_color="blue", line_color="firebrick")

renderer.selection_glyph = selected_scatter
renderer.nonselection_glyph = nonselected_scatter
```

Original plot:

<img width="450" alt="Screenshot 2024-07-01 at 09 01 45" src="https://github.com/bokeh/bokeh/assets/1078448/f0ac8bf5-97a8-4c59-8c41-0639315dbbb7">

After tap (size is wrong):

<img width="473" alt="Screenshot 2024-07-01 at 09 01 58" src="https://github.com/bokeh/bokeh/assets/1078448/8a7dcce1-026d-42a9-a988-50d6cea30266">

Previous version result:

<img width="464" alt="Screenshot 2024-07-01 at 09 02 26" src="https://github.com/bokeh/bokeh/assets/1078448/0e245f38-33ae-44f3-aced-c976048fd5a6">

cc @mattpap I expect this is related to glyph inheritance changes?

**Comment by bryevdv** [comment]
This Discourse topic (reported with 3.5.0rc2) may also be related:

https://discourse.bokeh.org/t/issue-with-custom-coordinate-names-and-bokeh-scatter-plot-selections/11640

@mattpap if you think that's a separate issue let me know and I will open another new one.

**Comment by bryevdv** [comment]
Notably, the `selection_line_file` etc parameter versions *do* work as expected.

**Comment by mosc9575** [comment]
I think this is something we missed by the Circle vs Scatter API cleanup, e.g. https://github.com/bokeh/bokeh/pull/13283. I will make a PR.

**Comment by mattpap** [comment]
I believe the aforementioned example does exactly what it advertises. I would not expect `size`'s value to be magically transferred to models that were unknown to `figure.scatter()`. Well, at least without further changes to dataspec API, like adding  `"inherit"` enum, or something like that. If we are looking for a culprit, then it's PR #13554. This example should have been updated in that PR or a follow-up, either to use explicit `size=50`:
```py
from bokeh.models import Scatter
from bokeh.plotting import figure, show

plot = figure(width=400, height=400, tools="tap", title="Select a circle")
renderer = plot.scatter([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=50)

selected_scatter = Scatter(size=50, fill_alpha=1, fill_color="firebrick", line_color=None)
nonselected_scatter = Scatter(size=50, fill_alpha=0.2, fill_color="blue", line_color="firebrick")

renderer.selection_glyph = selected_scatter
renderer.nonselection_glyph = nonselected_scatter

show(plot)
```
![Screenshot from 2024-07-14 01-56-15](https://github.com/user-attachments/assets/96d0ed3f-c605-416f-bedb-f4ee4197d3d3)

or preferrably, from my perspective, to use `renderer.glyph.clone()` with overrides:
```py
from bokeh.models import Scatter
from bokeh.plotting import figure, show

plot = figure(width=400, height=400, tools="tap", title="Select a circle")
renderer = plot.scatter([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=50)

selected_scatter = renderer.glyph.clone(fill_alpha=1, fill_color="firebrick", line_color=None)
nonselected_scatter = renderer.glyph.clone(fill_alpha=0.2, fill_color="blue", line_color="firebrick")

renderer.selection_glyph = selected_scatter
renderer.nonselection_glyph = nonselected_scatter

show(plot)
```
![Screenshot from 2024-07-14 01-56-55](https://github.com/user-attachments/assets/54018436-3250-4db5-ac52-56fe440664f3)

This is an explicit variant of what bokehjs already does in `"auto"` mode. `HasProps.clone(**overrides)` is available since bokeh 3.5 (PR #13808). Perhaps we will need to backport that PR or a part of it to 3.4, because #13554 was merged in bokeh 3.4.

Finally, there are `selection_*` and `nonselection_*` arguments to `figure.scatter()` which provide us with a third variant, assuming we don't want to show the low-level API and/or mixing of high and low level APIs:
```py
from bokeh.plotting import figure, show

plot = figure(width=400, height=400, tools="tap", title="Select a circle")
plot.scatter(
    [1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=50,
    selection_fill_alpha=1, selection_fill_color="firebrick", selection_line_color=None,
    nonselection_fill_alpha=0.2, nonselection_fill_color="blue", nonselection_line_color="firebrick",
)
show(plot)
```
![Screenshot from 2024-07-14 02-06-44](https://github.com/user-attachments/assets/1b24e8c4-41c0-46dd-b899-9175a9fe0a9b)
Though that doesn't seem to work as I would expect (see non-selection line color being different).

**Comment by bryevdv** [comment]
I can definitely understand that point of view, but apart from the fact that that is not how things have behaved for nearly 12 years, my other issue is simply that (IMO) it is *more uncommon by far* to want selection to also resize a glyph. The intent expanding the properties that selection glyphs was to make resizing *possible* but not (again, IMO) the *default*. Otherwise I feel that the current state of affairs makes the most common case harder and more work, which is, generally speaking, the opposite of what we should strive for. 

All that said, things were not, in fact, previously what I would now consider ideal, either. I.e. I think it would be good if
```
selected_scatter = Scatter()
```
meant that the selected glyph just looks exactly like the default glyph. And that to change the appearance, any explicitly provided properties were *overrides* from the default. But that's not actually the case now or previously. Providing a bare `selected_scatter = Scatter()` automagically inserts a default "grey" color somewhere:

<img width="397" alt="Screenshot 2024-07-14 at 13 41 47" src="https://github.com/user-attachments/assets/4c898869-4090-4c3b-a185-378dfd9c6d46"><img width="405" alt="Screenshot 2024-07-14 at 13 49 34" src="https://github.com/user-attachments/assets/d00a1772-a1b6-40fe-8d06-77321e85645e">


 I vaguely recall the motivation for that in 2012 but it's not what I would do today. 

But given that things are not ideal both past and present, I guess the real task is to decide what to do in the future. Mostly I think things should be consistent one way or the other:

* all properties on "sub-glyphs" inherit values from the parent glyph by default, unless explicitly overridden, or
* no properties on "sub-glyphs" deviate from standard usage in any way (i.e. no more "magic" grey colors or alphas applied behind the scenes on the BokehJS side)

Thoughts, @mattpap ?

**Comment by bryevdv** [comment]
@bokeh/dev @mattpap It does not seem likely to me that a technical answer to the question above will be coming before this   new behavior is simple the new norm. In which case reverting things back to the old behavior at that point would just be another breaking change. 

So, I would now propose to update the example, after all, but not by manually specifying the size, since that is an unreasonable burden for users. Instead, I would make use of and promote `clone` for this purpose, since it affords the "inherit everything then override" workflow, which is what I think is actually wanted, using existing methods:

```python
from bokeh.plotting import figure, show

plot = figure(width=400, height=400, tools="tap", title="Select a circle")
r = plot.scatter([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=50)

r.selection_glyph = r.glyph.clone(fill_alpha=1, fill_color="firebrick", line_color=None)
r.nonselection_glyph = r.glyph.clone(fill_alpha=0.2, fill_color="blue", line_color="firebrick")

show(plot)
```
<img width="406" alt="Screenshot 2024-08-24 at 20 09 06" src="https://github.com/user-attachments/assets/72ecd47f-d957-426b-ab7b-044d10ef8898">
