### ISSUE TITLE
[BUG] Bokeh docs (latest) show "unknown version" warning

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#13950]
The Bokeh docs at docs.bokeh.org show a warning:

![image](https://github.com/bokeh/bokeh/assets/39711796/6ac4e071-7520-432f-84da-947999e1ced3)

("This is documentation for an unknown version. | Switch to stable version"

To reproduce:
Go to docs.bokeh.org, to https://docs.bokeh.org/en/latest/index.html, or use the version switcher to switch the docs version to "latest" (tested on various browsers on Win11 an iOS).

**Comment by tcmetzger** [comment]
@bryevdv @mosc9575 I just noticed #13949 which appears to be related - feel free to close this issue as "won't fix" / "duplicate" if this notification is the expected outcome from the discussion in that PR!

**Comment by bryevdv** [comment]
The fi in the PR will only apply to future deployments. Fixing the already-released docs will require a small manual intervention on AWS that has not happened yet
