### ISSUE TITLE
[BUG] page won't render if CustomJS args has a dict with key "constructor"

### ISSUE THREAD

**Issue by solstag** [bokeh/bokeh#13964]
### Software versions

Python version        :  3.10.7 (main, Jan  1 1970, 00:00:01) [GCC 11.3.0]
IPython version       :  8.23.0
Tornado version       :  6.4
Bokeh version         :  3.5.0
BokehJS static path   :  /home/eris/.local/lib/python3.10/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.9.7-x86_64-with-glibc2.35

### Browser name and version

127.0.2 (64-bit)

### Expected behavior

Rendering the page.

### Observed behavior

Nothing gets rendered. Instead, in the example provided we see the following Javascript error:
`Uncaught (in promise) TypeError: right-hand side of 'in' should be an object, got number`

Because at bokeh.js#L3355, corresponding to:
https://github.com/bokeh/bokeh/blob/f6ce2e019bf6906b69c4fb2316a06b5c9c1e3b99/bokehjs/src/lib/core/util/refs.ts#L36
`obj.constructor` is accessed, but the original constructor got masked by the integer value of the key "constructor" from the dictionary passed in Python to `CustomJS(args=…)`.

I don't understand what this code is doing in the bigger picture, but maybe the intention here was to access `obj._proto_.constructor`?

### Example code

```Python
import bokeh.plotting as bkp
import bokeh.models as bkm

search = bkm.AutocompleteInput()
search_cb = bkm.CustomJS(args=dict(test={"constructor": 12}), code="")
search.js_on_change("change:value", search_cb)

bkp.output_file('test.html', mode='inline')
bkp.save(search)
```

**Comment by l-armstrong** [comment]
Is this issue open to being worked on?

**Comment by mattpap** [comment]
> Is this issue open to being worked on?

Yes, though external input is always welcome.
