### ISSUE TITLE
[FEATURE] Add a conda channel for rc releases 

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#13963]
### Problem description

The Holoviz ecosystem tries to test development and release candidate releases for Bokeh. Our CI uses conda packages, which, when solving, use the largest version number in [alphabetic order](https://github.com/conda/conda/issues/12568) and not  [PEP440](https://peps.python.org/pep-0440/), making it so `.dev` releases have higher priority than `rc`. 

Therefore, we hard-pin the version numbers when we are testing the latest Bokeh RC versions: https://github.com/holoviz/panel/blob/70a27c9edd2ead0ffefb3253404eac0c2354705b/pixi.toml#L25, but often we have to relearn this annoying feature of conda. 

We also end up only testing Panel and HoloViews (sometimes) with the dev versions because of the small but not negligible changes needed. 

### Feature description

I don't want to add an extra burden on the Bokeh infrastructure. 

Having a specific Bokeh channel that contains official and RC versions but not the `.dev` versions. This will likely allow us to use this channel all the time for Bokeh without updating our CI files.

### Potential alternatives

We wait until conda supports PEP 440 :upside_down_face: 

### Additional information

I'm out for the next few weeks, so if I don't answer, it is not because I'm not interested in this.

**Comment by bryevdv** [comment]
I will admit to being annoyed at the prospect of having to add more complication to work around this ridiculous conda bug. Can we just move rcs to the main channel, and publish both full releases and rcs there?  (and dev channel only has `.dev`)

**Comment by bryevdv** [comment]
@bokeh/dev @philippjfr @hoxbro thoughts on the above proposal to publish rcs (but not dev builds) to the main channel? Would that satisfy your needs?

**Comment by philippjfr** [comment]
Hmm, the easiest approach **I think** would simply be to introduce one extra label for the existing bokeh channel so we'd have something like `dev`, `main` and `rc`. That could be a one or two line change here:

https://github.com/bokeh/bokeh/blob/42435cdb6616a3f3d4e90e0a900cf7906c9f4570/release/deploy.py#L43

```python
rc_channel = '-l rc' if config.version_type == 'rc' else ''
...
    system.run(f"anaconda -t {token} upload -u bokeh {path} {main_channel} {rc_channel} -l dev --force --no-progress")
```

Agree that this is ridiculous of course.

**Comment by hoxbro** [comment]
I have no strong opinion on uploading RC releases to the main channel or creating a new channel.   I think both will work.

**Comment by bryevdv** [comment]
@hoxbro @philippjfr I am happy to accept any change either of you want to make here. I don't intend to submit any PR myself.
