### ISSUE TITLE
Remove sampledata download in contributing guide

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh#13960]
I think we can remove: [7. Download sample data](https://docs.bokeh.org/en/dev-3.5/docs/dev_guide/setup.html#download-sample-data) from the development environment setup instructions.

Sample data was moved into a different `bokeh_sampledata` package. Since we have it listed as a dependency in all the [`environment-test-*.yml` files](https://github.com/bokeh/bokeh/tree/branch-3.5/conda), it will be installed while creating the [conda development environment](https://docs.bokeh.org/en/dev-3.5/docs/dev_guide/setup.html#create-a-conda-environment) making the above step redundant (and potentially confusing).

At minimum, we can add a note to match expectations. :)

_(Noticed this when @gabalafou and @Chiemezuo were going through the setup workflow)_

**Comment by Chiemezuo** [comment]
I'd like to work on this as I think it's a good first PR. 
Do I have a go-ahead?

**Comment by bryevdv** [comment]
@Chiemezuo By all means, please proceed :)

**Comment by Chiemezuo** [comment]
I'm currently trying to make this fix, and I noticed in the official guide to writing documentation for bokeh, `pip install bokeh_sampledata` is one of the steps in `1. Prepare your environment`
See [docs on preparing environment](https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html#prepare-your-environment)

Is this something to also be looked into?

**Comment by bryevdv** [comment]
@Chiemezuo agreed for devs working on Bokeh, the sampledata install should already be taken care of by the environment file, and so strictly speaking that note there is not necessary. I think the it can be removed as you suggest

That said, I think that the reference guide for `bokeh.sampledata` here: 

https://docs.bokeh.org/en/latest/docs/reference/sampledata.html 

*should* mention how to install the separate module. I think you could add a few sentences of introduction, including demonstrating `pip install bokeh_sampledata`, to the empty docstring in this module:

https://github.com/bokeh/bokeh/blob/branch-3.6/src/bokeh/sampledata/__init__.py

What do you think? If you agree let's combine these changes in your existing PR.

**Comment by Chiemezuo** [comment]
@bryevdv I'm still quite new to this documentation, so I might not know exactly the best way to do it.

I understand the first part (removing it where it's not needed), but could you explain the latter part (modifying the reference docs) to me a little more? I do apologize, but it's a bit confusing to me at the moment.

**Comment by bryevdv** [comment]
@Chiemezuo are you familiar with docstrings in Python? If so, the docstring at the top of this module is currently empty:

https://github.com/bokeh/bokeh/blob/f6ce2e019bf6906b69c4fb2316a06b5c9c1e3b99/src/bokeh/sampledata/__init__.py#L7-L9

Anything you add to that docstring will automatically show up in the reference guide. I was suggesting added a note about `pip install bokeh_sampledata` to that docstring. Something like:

```rst
The ``bokeh.sampledata`` module exposes datasets that are used in examples and
documentation. Some datasets require separate installation. To install those 
using ``pip``, execute the command:

.. code-block:: sh

    pip install bokeh_sampledata

```

The syntax for these docstrings that get parsed by Sphinx is ReStructuted Text (`.rst`) Here is a tutorial about ReST syntax: https://sphinx-tutorial.readthedocs.io/step-1/

cc @tcmetzger for any additional thoughts on what to say in this location.

**Comment by Chiemezuo** [comment]
Thank you for this @bryevdv !!
I'll look into this and give you feedback as soon as I can.

**Comment by Chiemezuo** [comment]
@bryevdv Done! Thank you for the pointer.
