### ISSUE TITLE
[BUG] Plots fail in Firefox 115.12.0esr (64-bit)

### ISSUE THREAD

**Issue by maltevesper** [bokeh/bokeh#13969]
### Software versions

For my local install, not sure what is running at https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_1.html (apart from bokeh 3.5.0)

Python version        :  3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
IPython version       :  (not installed)
Tornado version       :  6.4.1
Bokeh version         :  3.5.0
BokehJS static path   :  C:\Users\Malte.Vesper\OneDrive - windcave.com\Documents\TestAutomate\.venv\Lib\site-packages\bokeh\server\static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-11-10.0.22631-SP0

### Browser name and version

Firefox 115.12.0esr (64-bit)

### Expected behavior

See a plot (see the attached IE screenshot)

### Observed behavior

bbox issue on browser console, no plot is shown (see attached firefox screenshot)

### Example code

```Python
Simply visit
https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_1.html
with Firefox
```

### Stack traceback or browser console output

While there are more warnings in the console when visiting https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_1.html, this seems to be the relevant one:

Uncaught (in promise) Error: invalid bbox {x: 42, y: NaN, width: 6, height: NaN}
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:230
    _rect https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:346
    rect https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:346
    bbox https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:346
    k https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:355
    _draw_oriented_labels https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:355
    _draw_major_labels https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:355
    _paint https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:355
    paint https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:249
    _paint_levels https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:616
    _actual_paint https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:616
    paint https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:616
    _after_layout https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:616
    after_layout https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:581
    compute_layout https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:581
    invalidate_layout https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:581
    _after_render https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:581
    after_render https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:277
    r_after_render https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:223
    build https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:223
    l https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:220
2 bokeh-3.5.0.min.js:230:990

For comparison here is a log when I try to create a single plot locally:

[bokeh 3.5.0] setting log level to: 'info' bokeh-3.5.0.min.js:185:1338
Uncaught (in promise) Error: invalid bbox {x: 39.19396209716797, y: NaN, width: 27, height: NaN}
    _ https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:230
    _rect https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:346
    rect https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:346
    bbox https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:346
    k https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:355
    _draw_oriented_labels https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:355
    _draw_major_labels https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:355
    _paint https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:355
    paint https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:249
    _paint_levels https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:616
    _actual_paint https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:616
    paint https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:616
    _after_layout https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:616
    after_layout https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:581
    compute_layout https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:581
    invalidate_layout https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:581
    _after_render https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:581
    after_render https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:277
    r_after_render https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:223
    build https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:223
    l https://cdn.bokeh.org/bokeh/release/bokeh-3.5.0.min.js:220
bokeh-3.5.0.min.js:230:990
Error in parsing value for ‘grid-template-rows’.  Declaration dropped. COM21_test_2030717.csv.html:3:29
:host selector in ‘:host:empty’ is not featureless and will never match. Maybe you intended to use :host()? COM21_test_2030717.csv.html:12:13
Error in parsing value for ‘grid-template-rows’.  Declaration dropped. COM21_test_2030717.csv.html:8:29

### Screenshots

Firefox:
![image](https://github.com/bokeh/bokeh/assets/10866845/55e707f4-eb28-4376-8e23-427133530822)
IE:
![image](https://github.com/bokeh/bokeh/assets/10866845/7cff070e-00f7-41e7-a816-26f7b46ca58b)

**Comment by maltevesper** [comment]
I am sure it is a regression in Bokeh 3.5.0, downgrading to 3.4.2 fixes the issue for me.
I have not found migration information https://github.com/bokeh/bokeh/wiki/Migration-Guides,
from the changelog the following item jumps out at me:
- #13863 [component: bokehjs] Generalize bbox handling in UI views (DOM and canvas)

**Comment by mattpap** [comment]
I can reproduce this in Firefox 115. This is an older version of firefox (the most recent is 127), but not that old for it not to work.

**Comment by mattpap** [comment]
Or maybe it is that old or just sluggish to implement modern features, because it doesn't support modern text metrics on HTML5 canvas (PR #13770). The earliest version that supports them is 116.

**Comment by bryevdv** [comment]
What's for discussion @mattpap ? I agree with your initial assessment that FF 115 is probably more recent (last year) than we'd want to exclude. If there's a gentler way to degrade that avoids adding back a bunch of fixups, I think that would be worth considering.

**Comment by maltevesper** [comment]
Mhm I send two comments trhough via mail and am surprised that they are not up yet:

The 115 version is an ESR release which is end of life in two months: https://whattrainisitnow.com/calendar/
I would have been happy with a console message or even a viewport message telling me to upgrade firefox/downgrade bokeh, as that would have saved me a lot of time (not being a web developer, it took me a moment to realise that the issue is not with my script per se.
