### ISSUE TITLE
[BUG] export_png cut off with longer graphs

### ISSUE THREAD

**Issue by PlerionPlorion** [bokeh/bokeh#13990]
### Software versions

Python version        :  3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
IPython version       :  (not installed)
Tornado version       :  6.4.1
Bokeh version         :  3.4.2
BokehJS static path   :  C:\Users\Ruhmi\AppData\Local\Programs\Python\Python39\Lib\site-packages\bokeh\server\static
node.js version       :  v20.12.2
npm version           :  10.5.0
jupyter_bokeh version :  (not installed)
Operating system      :  Windows-10-10.0.26252-SP0

### Browser name and version

Chrome 128

### Expected behavior

Full PNG including entire plot.

### Observed behavior

PNG is the correct size however plot is cutoff and the rest is transparent space.

### Example code

```Python
default exportpng with a long bargraph
```

### Screenshots

![plot](https://github.com/user-attachments/assets/b3cf6d52-8108-4eb7-ba50-28592ad1a809)

**Comment by PlerionPlorion** [comment]
For reference a shorter data set:
![plot](https://github.com/user-attachments/assets/0af7e4a2-d747-4039-acb7-80ced142ee80)

**Comment by bryevdv** [comment]
@PlerionPlorion we absolutely need a complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to be able to reproduce this ourselves.

**Comment by PlerionPlorion** [comment]
Do you want me to include a large csv?

**Comment by bryevdv** [comment]
Yes we would need any input CSV (e.g. uploaded to a [GitHub gist](https://gist.github.com)) or for the script to generate synthetic data on its own

**Comment by PlerionPlorion** [comment]
```
from collections import defaultdict

import pandas as pd
from bokeh.io import curdoc, export_png, export_svg
from bokeh.layouts import layout
from bokeh.models import ColumnDataSource, HoverTool, WheelZoomTool
from bokeh.palettes import Spectral6
from bokeh.plotting import figure, output_notebook, show
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument("headless=new")
driver = webdriver.Chrome(options=options)

# Load the data
opposing = pd.read_csv("opposing_teams.csv")
allied = pd.read_csv("allied_teams.csv")

# For allied teams
allied_aggregated = allied.groupby('Team_Key')['Count'].sum().reset_index()
allied_aggregated.rename(columns={'Count': 'Allied_Count'}, inplace=True)

# For opposing teams
opposing_aggregated = opposing.groupby('Team_Key')['Count'].sum().reset_index()
opposing_aggregated.rename(columns={'Count': 'Opposing_Count'}, inplace=True)

# Merge the DataFrames on the 'Team_Key' column
mergedTeams = pd.merge(allied_aggregated, opposing_aggregated, on='Team_Key', how='outer')

# Fill NaN values with 0 for teams that appear in one dataset but not the other
mergedTeams.fillna(0, inplace=True)

# Convert counts to integers to remove decimals
mergedTeams['Allied_Count'] = mergedTeams['Allied_Count'].astype(int)
mergedTeams['Opposing_Count'] = mergedTeams['Opposing_Count'].astype(int)

# Calculate the total count by summing the 'Allied_Count' and 'Opposing_Count' columns
mergedTeams['Count'] = mergedTeams['Allied_Count'] + mergedTeams['Opposing_Count']

mergedTeams.to_csv("combined_counts.csv", index=False)

# Remove the "frc" prefix from the 'Team_Key' column
mergedTeams['Team_Key'] = mergedTeams['Team_Key'].str.replace('frc', '')

# Group by team_key and add the counts
aggregated_data = mergedTeams.groupby('Team_Key').sum().reset_index()

# Sort the data by the number of appearances in descending order
sorted_data = aggregated_data.sort_values(by='Count', ascending=False)

# Convert to ColumnDataSource for Bokeh
source = ColumnDataSource(sorted_data)

# Create a new plot with a title and axis labels
p = figure(title="Matches With and Against for: ",
           x_axis_label='Team_Key',
           y_axis_label='Matches Across ',
           tools="pan,wheel_zoom,box_zoom,reset",
           x_range=(source.data['Team_Key']),
           y_range=(0, max(source.data['Count'])*1.1),
           width=len(source.data['Team_Key'])*15)
p.xaxis.major_label_orientation = "vertical"
p.toolbar.active_scroll = p.select_one(WheelZoomTool)

# Define hover tool
hover = HoverTool(tooltips=[
    ("Team", "@Team_Key"),
    ("Matches Against", "@Opposing_Count"),
    ("Matches With", "@Allied_Count"),
])
p.add_tools(hover)

# Add a renderer with legend and line thickness
p.vbar_stack(['Allied_Count', 'Opposing_Count'], x='Team_Key', width=0.5, color=Spectral6[:2], source=source,
       legend_label=['Matches With', 'Matches Against'], name='stacked')

# Customize the legend
p.legend.location = "top_left"
p.legend.click_policy="hide"  # Allows clicking on legend items to hide the corresponding data

# Show the results
curdoc().theme = 'dark_minimal'
export_png(p, filename="plot.png", webdriver=driver)
# export_svg(p, filename="plot.svg", webdriver=driver, height=max(source.data['Count'])*50)
show(p)
```
As well as the 2 csv's required to reproduce the issue
[opposing_teams.csv](https://github.com/user-attachments/files/16322383/opposing_teams.csv)
[allied_teams.csv](https://github.com/user-attachments/files/16322384/allied_teams.csv)

**Comment by bryevdv** [comment]
Running this code as-is actually generates a safety error from PIL for me
```
PIL.Image.DecompressionBombError: Image size (186316000 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```
After turning off the safety threshold, the export works fine for me on OSX with Bokeh 3.5:

<img width="330" alt="Screenshot 2024-07-20 at 18 18 34" src="https://github.com/user-attachments/assets/44d1b352-a6e5-4cf9-a75f-29411ae68515"> 

First things first @PlerionPlorion you should try this with latest Bokeh 3.5 in case there is some recent issue that was fixed in this release. But assuming that is not the case, then the issue is likely dependent on your system in some way, e.g. OS or browser versions. If there is an upstream issue (e.g. some versions of Chrome impose a canvas size limit) then it is entirely possible that there is nothing we will be able to do. I'd also suggest experimenting with the firefox webdriver to see if that affects anything for you. 

To completely frank: this is not a usual sized image (as evidenced by the PIL `DecompressionBombError`) and it's also not clear how such a large image can be efficacious from a visualization standpoint, either. My actual advice is to look into different ways to visualize this data that don't result in such outsize proportions.

**Comment by PlerionPlorion** [comment]
Interesting, I don't get the same error but thanks for the advice! Ah I see, pip installing bokeh only get's you up to 3.4.2

**Comment by bryevdv** [comment]
> Ah I see, pip installing bokeh only get's you up to 3.4.2

@PlerionPlorion this is [definitely not true](https://pypi.org/project/bokeh/):
```
bk34-py312 ❯ pip install bokeh
Collecting bokeh
  Using cached bokeh-3.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: Jinja2>=2.9 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (3.1.3)
Requirement already satisfied: contourpy>=1.2 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (1.2.0)
Requirement already satisfied: numpy>=1.16 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (1.26.4)
Requirement already satisfied: packaging>=16.8 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (23.1)
Requirement already satisfied: pandas>=1.2 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (2.2.1)
Requirement already satisfied: pillow>=7.1.0 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (10.2.0)
Requirement already satisfied: PyYAML>=3.10 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (6.0.1)
Requirement already satisfied: tornado>=6.2 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (6.3.3)
Requirement already satisfied: xyzservices>=2021.09.1 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from bokeh) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from Jinja2>=2.9->bokeh) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from pandas>=1.2->bokeh) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from pandas>=1.2->bokeh) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from pandas>=1.2->bokeh) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/bryan/anaconda3/envs/bk34-py312/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.2->bokeh) (1.16.0)
Using cached bokeh-3.5.0-py3-none-any.whl (6.8 MB)
Installing collected packages: bokeh
Successfully installed bokeh-3.5.0
```

If you are trying to update an existing env perhaps you need to add `-U` to upgrade. 

>  I don't get the same error but  

Possibly you have an older version of PIL installed as well. PIL version is *another* variable for you to experiment with. Perhaps old versions of PIL truncate silently instead of raising an error. Again nothing we can do on our end, if something like that is the case.

In any event since you have already closed this yourself, I am going to go ahead and mark this `upstream` since my educated guess is that that is in fact probably the actual situation.

**Comment by PlerionPlorion** [comment]
Oh I guess I should've updated: This only happens on windows, it works fine in my kali wsl environment 👍
