### ISSUE TITLE
[BUG] `Numpy.datetime64` does not work when streaming

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#14004]
### Software versions

``` yaml
Python version        :  3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]
IPython version       :  8.26.0
Tornado version       :  6.4.1
Bokeh version         :  3.5.1
BokehJS static path   :  /home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  v22.5.1
npm version           :  10.8.2
jupyter_bokeh version :  4.0.5
Operating system      :  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35

```

### Expected behavior

Streams should work both with `datetime` and `numpy.datetime64`

### Observed behavior

Currently, it does not work. I'm pretty sure it is related to Numpy 2.0.

### Example code

```Python
from datetime import datetime

import numpy as np
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

data_source = ColumnDataSource(data={"Close": [], "DateTime": []})

fig = figure(x_axis_type="datetime", width=900, height=450)
fig.line(x="DateTime", y="Close", line_color="tomato", line_width=3.0, source=data_source)


def update_chart():
    new_row = {
        "Close": np.random.rand(1),
        "DateTime": np.array([np.datetime64("now")]),  # Does not work
        # "DateTime": [datetime.now()],  # Does work
    }
    data_source.stream(new_row)


curdoc().add_periodic_callback(update_chart, 1000)
curdoc().add_root(fig)
```

### Stack traceback or browser console output

``` python-traceback
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/tornado/gen.py", line 529, in callback
    result_list.append(f.result())
                       ^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/server/session.py", line 226, in with_document_locked
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/document/callbacks.py", line 495, in wrapper
    return invoke_with_curdoc(doc, invoke)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/document/callbacks.py", line 453, in invoke_with_curdoc
    return f()
           ^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/document/callbacks.py", line 494, in invoke
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shh/projects/holoviz/example.py", line 20, in update_chart
    data_source.stream(new_row)
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/models/sources.py", line 461, in stream
    self._stream(new_data, rollover)
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/models/sources.py", line 573, in _stream
    self.data._stream(self.document, self, new_data, rollover, setter)
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/bokeh/core/property/wrappers.py", line 472, in _stream
    data = np.append(self[k], new_data[k])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py", line 5821, in append
    return concatenate((arr, values), axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.exceptions.DTypePromotionError: The DType <class 'numpy.dtypes.Float64DType'> could not be promoted by <class 'numpy.dtypes.DateTime64DType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.DateTime64DType'>)
```

**Comment by mattpap** [comment]
This works as well:
```py
data_source = ColumnDataSource(data={"Close": [], "DateTime": np.array([], dtype=np.datetime64)})
```
I would say this is a usage error with NumPy 2.0. I'm not sure if we can do anything about this, because we can't guess how `[]` will be used in the future.

**Comment by mattpap** [comment]
I suppose would could ignore empty arrays to avoid type conversions, especially during the first concatenation.

**Comment by bryevdv** [comment]
@mattpap I think you mean: if the column is an empty list/array/series/whatever, then just replace the column with the first stream value, and don't bother concatenating at all. That seems reasonable, certainly worth a try.

**Comment by hadihassanbaloch** [comment]
@mattpap Hey! I am new to this so first i tried to recreate this issue. but it is working fine for me without any errors. Can you please guide if i am missing something? because this is my first contribution to open source.
Here are the screenshots for both py and ipynb file. Working fine on both,
![Screenshot 2024-08-02 200006](https://github.com/user-attachments/assets/5f1d2375-0a84-4faf-93fb-ef55b03434de)
![Screenshot 2024-08-02 200052](https://github.com/user-attachments/assets/dc8d076c-dcfe-45ad-8b39-eac60000efcb)

**Comment by mattpap** [comment]
@hadihassanbaloch, you need numpy 2.0 or newer for the error to occur.

**Comment by hadihassanbaloch** [comment]
@mattpap I am using numpy==2.0.1 , python== 3.12.4 , ipython== 8.26.0, bokeh==3.5.1

**Comment by hadihassanbaloch** [comment]
@mattpap the only difference is my os i am using windows and this issue was originated on linux.

**Comment by mattpap** [comment]
> the only difference is my os i am using windows and this issue was originated on linux.

That wouldn't be the first time the platform playing a role in appearance of bug. However, I would double check if you are actually running numpy 2.0 in you script (e.g. by adding `print(np.__version__` after `import numpy as np`). It's surprisingly common for a package manager to show one set of packages and a script run with a different set.

**Comment by hadihassanbaloch** [comment]
@mattpap I have checked np version again and it is 2.0.1 so i think the problem is with the OS. 
![Screenshot 2024-08-03 080505](https://github.com/user-attachments/assets/db06763b-42bf-4bfd-8c40-6f7975aef9c7)

**Comment by hadihassanbaloch** [comment]
@mattpap I have also run this with older version of numpy on google colab and it is still working fine for me so i am sure this has something to do with OS.
![Screenshot 2024-08-03 081059](https://github.com/user-attachments/assets/0e8990fd-0b3e-49dc-8502-d7f9431daeb5)

**Comment by bryevdv** [comment]
@hadihassanbaloch you are not actually exercising the code in question by just executing in the notebook. It is code for a Bokeh server application. The callback code only runs when a session is connected. To actually see the effect of the callback code you need to:

* Run the code with `bokeh serve`, then
* Open a browser to the app URL to open a session

See the docs:

https://docs.bokeh.org/en/latest/docs/user_guide/server.html
