### ISSUE TITLE
[BUG] Glyphs should correctly use configured ranges

### ISSUE THREAD

**Issue by croots** [bokeh/bokeh#14013]
### Software versions

Python version        :  3.9.19 (main, May  6 2024, 19:43:03) 
IPython version       :  (not installed)
Tornado version       :  6.4.1
Bokeh version         :  3.4.3
BokehJS static path   :  /home/USER/micromamba/envs/PROJECT/lib/python3.9/site-packages/bokeh/server/static
node.js version       :  v22.5.1
npm version           :  10.8.2
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.9.10-arch1-1-x86_64-with-glibc2.40

### Browser name and version

Firefox 128.0.3

### Expected behavior

When I pan a plot of glyphs, the glyph should remain loaded as long as its coordinates remain on the plot

### Observed behavior

When I pan a plot of glyphs, glyphs on an extra axis vanish when the coordinates of the glyph would cause that glyph to not be shown had that glyph been graphed on the primary plot.

For example, a glyph plotted at (0, -500) on Y axis 2 will not show if the range of Y axis 1 is [500, 1000], even if the range of Y axis 2 is [0, -1000]

### Example code

```Python
from bokeh.plotting import figure, show
from bokeh.models import Range1d


def main():
    # Boilerplate
    fig = figure(
        width=1500,
        height=750,
    )

    fig.lod_threshold = None # Does not affect results

    # Set the Y axis range to something large
    fig.x_range = Range1d(start=0, end=1000)
    fig.y_range = Range1d(start=-1000, end=1000)

    # Set the second Y axis range to be offset from the primary Y axis range
    fig.extra_y_ranges = {
        "y_range2": Range1d(start=250, end=-750),
    }

    # Draw an offending glyph
    disappearing_act = [[100, 0], [900, 0], [900, -500], [100, -500]]
    x = [coords[0] for coords in disappearing_act]
    y = [coords[1] for coords in disappearing_act]

    glyph_dictionary = {
        "x": [x],
        "y": [y]
    }

    fig.patches(
        "x",
        "y",
        source=glyph_dictionary,
        y_range_name="y_range2",
    )

    # Show fig
    show(fig)

    # Panning up (such that the glyph crosses the bottom of the viewing window) will cause the glyph to vanish about midway through once 0 is no longer visible on the primary Y axis


if __name__ == "__main__":
    main()

```

### Screenshots

![Minimal, glyph showing](https://github.com/user-attachments/assets/856d6f97-6d7d-4c71-a259-dbecc63e7d6a)
![Minimal, glyph vanished prematurely](https://github.com/user-attachments/assets/53bb1e33-adbe-421d-8e35-912b2372de45)

![In practice, glyphs showing](https://github.com/user-attachments/assets/7d17e922-feec-4a65-9246-775b2a417920)
![In practice, glyphs vanished prematurely](https://github.com/user-attachments/assets/4181e8b2-4511-4992-af82-9616a8b5fc1f)

**Comment by bryevdv** [comment]
@croots I can't reproduce any issue with latest Bokeh 3.5.1 (the glyph does not disappear at any point during panning all over). Please try out and report back with the latest release. 

Edit: it does disappear, but only when panning it off the bottom

**Comment by croots** [comment]
> it does disappear, but only when panning it off the bottom

That right. In the minimal example, the glyph is plotted below y=0 on the secondary axis. When the plot is panned such that the primary axis no longer shows anything below y=0, the glyph disappears.

**Comment by bryevdv** [comment]
I don't understand what this issue has to do with LOD, the bad behavior happens with or without any LOD configuration. LOD only applies *during* interactive events (e.g. during, in the middle of a pan). The fact that the glyph disappears permanently indicates just a general bug regarding an interaction with additional axes.

**Comment by croots** [comment]
Perhaps I have my terminology wrong in this case. Generally when I think of "LOD" that concept also includes optimizations that stop the rendering of things that shouldn't be seen, but the extent of my knowledge here just comes from casually following video game development

**Comment by bryevdv** [comment]
Here is the problem (edit: almost certainly), the `Patches` glyph unconditionally uses the default ranges for culling off-screen instances:

https://github.com/bokeh/bokeh/blob/3a743681d80de78f8a86f5acd59b0cb80b3af98a/bokehjs/src/lib/models/glyphs/patches.ts#L37-L43

The correct behavior would be to refer to `x_range_name` and `y_range_name` to look up the correct range. 

Not all glyphs do culling at all, so I would expect many glyphs to not exhibit this kind of issue. But a fix PR should do a quick survey of all `_mask_data` implementations.

**Comment by mattpap** [comment]
> The correct behavior would be to refer to x_range_name and y_range_name to look up the correct range.

This is already resolved on `RendererView`, so the correct way of doing this is:
```ts
const {x_source: x_range, y_source: y_range} = this.renderer.coordinates
```
which also considers composite coordinates systems (based on `Renderer.coordinates`).
