### ISSUE TITLE
[BUG] LaTeX interpretation error in title

### ISSUE THREAD

**Issue by budyaya** [bokeh/bokeh#14025]
### Software versions

python '3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]'
bokeh '3.2.1'

### Browser name and version

Chrome

### Jupyter notebook / Jupyter Lab version

Jupyter Lab 3.6.3 and Jupyter notebook 6.5.4

### Expected behavior

![bokeh_plot](https://github.com/user-attachments/assets/0dd82b02-1256-410e-97f7-2989698f2bf0)

### Observed behavior

<img width="731" alt="03E2C75C-621C-4695-9B16-2BD2D5FE768E" src="https://github.com/user-attachments/assets/27525314-4690-43cb-898b-a6de5e22da35">

### Example code

```Python
from numpy import arange, pi, sin

from bokeh.models.annotations.labels import Label
from bokeh.plotting import figure, show

x = arange(-2*pi, 2*pi, 0.1)
y = sin(x)

p = figure(height=250, title=r"$$\sin(x)$$ for \[x\] between \(-2\pi\) and $$2\pi$$")
p.scatter(x, y, alpha=0.6, size=7)

label = Label(
    text=r"$$y = \sin(x)$$",
    x=150, y=130,
    x_units="screen", y_units="screen",
)
p.add_layout(label)

p.yaxis.axis_label = r"\(\sin(x)\)"
p.xaxis.axis_label = r"\[x\pi\]"

show(p)
```

**Comment by budyaya** [comment]
https://github.com/bokeh/bokeh/issues/14015

**Comment by mosc9575** [comment]
Hello @budyaya. This was part of the release `3.3.3` and the changes are made in https://github.com/bokeh/bokeh/pull/13214.

You can update bokeh to the latest version and the example from the docs will work out of the box. If this is not possible, you can make use of `\text{...}` as a workaround.

The title would be `r"$$\sin(x)\text{ for }x\text{ between }-2\pi\text{ and }2\pi$$"`.
