### ISSUE TITLE
[BUG] Unable to change figures displayed by altering children attribute of gridplot (or other layout classes) in JS callback

### ISSUE THREAD

**Issue by matteosox** [bokeh/bokeh#14068]
### Software versions

Python version        :  3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:34:54) [Clang 16.0.6 ]
IPython version       :  8.27.0
Tornado version       :  6.4.1
NumPy version         :  2.1.0
Bokeh version         :  3.5.2
BokehJS static path   :  /Users/mattfay/miniforge3/envs/jupyter/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  4.0.5
Operating system      :  macOS-14.6.1-arm64-arm-64bit

### Browser name and version

Chrome: Version 128.0.6613.138 (Official Build) (arm64)

### Expected behavior

I'd like to use a JS callback to dynamically update what figures are shown in a gridplot, and their order/position.

### Observed behavior

Nothing happens when I update the children attribute of gridplot in a JSCallback. Console logs show it's happening, and that I'm successfully updating the attribute, but no change in what is rendered. No errors in the console log otherwise.

This was already reported here: https://discourse.bokeh.org/t/update-layout-via-customjs-callback/11255

### Example code

```Python
from bokeh.plotting import figure, show
from bokeh.layouts import gridplot, column
from bokeh.models import CustomJS, MultiChoice
from bokeh.io import output_notebook

output_notebook()

fig1 = figure(title="Some plot")
fig1.scatter([1, 2, 3], [4, 5, 6])
fig2 = figure(title="Some other plot")
fig2.scatter([7, 8, 9], [1, 2 ,3])
figs = {fig1.title.text: fig1, fig2.title.text: fig2}
stack = gridplot(list(figs.values()), ncols=1)
callback = CustomJS(args=dict(stack=stack, figs=figs), code="""
const selections = cb_obj.value
stack.children.length = 0
let row = 0
for (const selection of selections) {
  stack.children.push([figs_dict[selection], row++, 0])
}
""")
multi_choice = MultiChoice(value=list(figs.keys()), options=list(figs.keys()))
col = column([multi_choice, stack])
show(col)
```

**Comment by bryevdv** [comment]
@matteosox Your code has several problems:

* Bokeh can only automagically respond to *assignments*, e.g. `stack.children = new_children`. "In place" updates like the ones above are invisible to Bokeh
* It uses an undefined name `figs_dict` presumable intended to be `figs`
* It doesn't actually set up a `.js_on_change`, so the callback will never even be called

Here is a version that could plausibly be expected to function:
```python
from bokeh.plotting import figure, show
from bokeh.layouts import gridplot, column
from bokeh.models import CustomJS, MultiChoice

fig1 = figure(title="Some plot")
fig1.scatter([1, 2, 3], [4, 5, 6])
fig2 = figure(title="Some other plot")
fig2.scatter([7, 8, 9], [1, 2 ,3])
figs = {fig1.title.text: fig1, fig2.title.text: fig2}
stack = gridplot(list(figs.values()), ncols=1)
callback = CustomJS(args=dict(stack=stack, figs=figs), code="""
const selections = cb_obj.value
const children = []
let row = 0
for (const selection of selections) {
    children.push([figs[selection], row++, 0])
}
stack.children = children
""")
multi_choice = MultiChoice(value=list(figs.keys()), options=list(figs.keys()))
multi_choice.js_on_change("value", callback)
col = column([multi_choice, stack])
show(col)
```

However, it does not update. @mattpap is the `[obj, row, column]` format for gridplot expected to be used on the JS side as well?

**Comment by bryevdv** [comment]
@mattpap `GridPlot` does not implement private `_update_children()` is that an issue?

**Comment by matteosox** [comment]
Thanks for cleaning the example up @bryevdv ! And great to learn about the assignments issue. I'm a big fan of Bokeh, but find it very difficult to work with the JS side of things, so if you're looking for contributors to help document that, I'd be happy to contribute.

**Comment by bryevdv** [comment]
Thanks for the kind words @matteosox we are always extremely happy to have help with improving the documentation. I'd suggest opening a [GitHub Discussion](https://github.com/bokeh/bokeh/discussions) to get things started, maybe listing the areas that you think need more content and would like to work on.

**Comment by mattpap** [comment]
This doesn't update, because `GridPlot` delegates management of layoutable children to `GridBox`, but it doesn't update `GridBox` when `GridPlot.children` property changes.
