### ISSUE TITLE
Add metadata to polar_subcoordinates.py, spans_and_strips.py

### ISSUE THREAD

**Issue by gus123671** [bokeh/bokeh#14079]
### Problem description

There is no metadata in polar_subcoordinates.py or spans_and_strips.py located in examples/plotting/. To understand the purpose of these files, a new contributor would have to read through the code and try to understand what bokeh is doing when we could just present them with a detailed and in-depth explanation of the functionality. 

### Feature description

Add metadata to polar_subcoordinates.py and spans_and_strips.py.

### Potential alternatives

No alternatives but to add documentation unless unnecessary.

**Comment by bryevdv** [comment]
I'm not sure we need dedicated issues for every individual file. It's fine for anhone to open a one-off standalone PR to add or improve example metadata at any time.
