### ISSUE TITLE
[BUG] Spinner input not responding to wheel event

### ISSUE THREAD

**Issue by Kramin42** [bokeh/bokeh#14072]
### Software versions

bokeh 3.4.3, issue is with JS and is present on documentation website, as well as anywhere else.

### Browser name and version

Chrome 126.0.6478.126 and Firefox 115.12.0esr

### Jupyter notebook / Jupyter Lab version

N/A

### Expected behavior

Scrolling the mouse wheel inside the Spinner input changes the value, e.g. working in 2.x: https://docs.bokeh.org/en/2.4.3/docs/user_guide/interaction/widgets.html#spinner

### Observed behavior

Page scrolls instead, spinner value is unchanged, in version 3.x: https://docs.bokeh.org/en/3.4.3/docs/user_guide/interaction/widgets.html#spinner

### Example code

```Python
Visit https://docs.bokeh.org/en/3.4.3/docs/user_guide/interaction/widgets.html#spinner and scroll in the Spinner element
```

### Stack traceback or browser console output

Issue is caused in this code:

```
                _input_mouse_wheel(e) {
                    if (document.activeElement === this.input_el) {
                        e.preventDefault();
                        const t = e.deltaY > 0 ? -1 : 1;
                        this.increment(t * this.model.step)
                    }
                }
```

when scrolling, `document.activeElement` is the parent `bk-Row` element, not the Spinner 
 `bk-Input` element, so the `if` statement fails. You can see this by setting a breakpoint on the wheel event.

### Screenshots

![image](https://github.com/user-attachments/assets/21eabf7a-b224-40b1-af61-e40f3a66a733)

**Comment by bryevdv** [comment]
@Kramin42 the version is not N/A since BokehJS and Python versions are locked. There will not be any future 3.4.x releases, so first things first: please confirm whether the issue is present with latest 3.5.x release, and also ideally with 3.6 dev branch.

**Comment by mattpap** [comment]
This is broken, because `document.activeElement` doesn't respect shadow DOM.
