### ISSUE TITLE
[BUG] p.circle(..) can't be added as renderer to PointDrawTool since 3.6

### ISSUE THREAD

**Issue by measty** [bokeh/bokeh#14082]
### Software versions

Python version        :  3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]
IPython version       :  8.14.0
Tornado version       :  6.3.2
NumPy version         :  1.24.4
Bokeh version         :  3.6.0
BokehJS static path   :  C:\Users\meast\anaconda3\envs\tiatoolbox-newest\Lib\site-packages\bokeh\server\static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  3.0.7
Operating system      :  Windows-10-10.0.22631-SP0

### Expected behavior

Creating a circle glyph renderer using:
```
    c = p.circle(
        "x",
        "y",
        source=pt_source,
        color="red",
        radius=3,
        radius_units="screen",
    )
 ```
and passing it to:
`p.add_tools(PointDrawTool(renderers=[c]))`
Was fine in <3.6, I would expect it to still work

### Observed behavior

Now it gives error:
```
ValueError: failed to validate PointDrawTool(id='p1080', ...).renderers: expected an element of 
List(TypeOfAttr(Instance(GlyphRenderer), 'glyph', Either(Instance(XYGlyph)))), got seq with invalid
  items [GlyphRenderer(id='p1076', ...)]
```
Reason seems maybe to be in
https://github.com/bokeh/bokeh/blob/c31db89bf227d88f62b661c6b6df12fbad0942ed/src/bokeh/models/glyphs.py#L454
There is no XYGlyph (compare with rect):
https://github.com/bokeh/bokeh/blob/c31db89bf227d88f62b661c6b6df12fbad0942ed/src/bokeh/models/glyphs.py#L1344
which works fine when passed to pointDrawTool.

### Example code

```Python
from bokeh.models import Circle, ColumnDataSource, PointDrawTool
from bokeh.plotting import figure

p = figure(width=400, height=400)

pt_source = ColumnDataSource({"x": [], "y": []})
c = p.circle("x", "y", source=pt_source)
PointDrawTool(renderers=[c])
```

### Stack traceback or browser console output

ValueError: failed to validate PointDrawTool(id='p1080', ...).renderers: expected an element of List(TypeOfAttr(Instance(GlyphRenderer), 'glyph', Either(Instance(XYGlyph)))), got seq with invalid items [GlyphRenderer(id='p1076', ...)]

**Comment by bryevdv** [comment]
This regression was introduced in https://github.com/bokeh/bokeh/pull/14027 we will have to issue a point release soon to fix.

**Comment by bryevdv** [comment]
Well, I had hoped to fix this and at the same time add support for a `{class}` format substitution in property help strings at the same time, so that inherited properties could provide more specific information on subclasses, but this turns out to be non-trivial at all. [1]

I'll submit a PR later today with the trivial class hierarchy fix by itself. 

[1] TLDR; not all the format information is known at the same time, in the same place. But worse, helpstrings for things like `CustomJS` have  curly braces (e.g. for JS code) in them which confuses Python `str.format` and causes it to blow up.

**Comment by measty** [comment]
Thanks for the quick resolution!
