### ISSUE TITLE
[BUG] Missing radius parameter in code example

### ISSUE THREAD

**Issue by sophist0** [bokeh/bokeh#14088]
### Software versions

Python version        :  3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
IPython version       :  (not installed)
Tornado version       :  6.4.1
NumPy version         :  2.1.1
Bokeh version         :  3.6.0
BokehJS static path   :  /home/USER_PATH/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  v18.19.1
npm version           :  9.2.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.8.0-45-generic-x86_64-with-glibc2.39

### Browser name and version

Google Chrome: Version 127.0.6533.119 (Official Build) (64-bit)

### Expected behavior

In the "Building applications" tutorial https://docs.bokeh.org/en/latest/docs/user_guide/server/app.html there is a code example under the section "Updating from unlocked callbacks". Running this example using "bokeh serve --show APP_NAME" is supposed to create a Bokeh application which plots circles in random locations.

### Observed behavior

The Bokeh application created by running this example using "bokeh serve --show APP_NAME" does not plot any circles and produces the browser console error:  

[bokeh 3.6.0] attempted to retrieve bokeh.min.js?v=de958ab1870cd066dba119c34f40c5e1ca4af9c0d31988f4020e6c49a056838b8968f69e29f359fb6dae256aed026344b1797302c230126c662521f0895deb32:184 property array for nonexistent field 'radius'

### Example code

```Python
import asyncio
import time
from concurrent.futures import ThreadPoolExecutor
from functools import partial

from bokeh.document import without_document_lock
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure

source = ColumnDataSource(data=dict(x=[0], y=[0], color=["blue"]))

i = 0

doc = curdoc()

executor = ThreadPoolExecutor(max_workers=2)

def blocking_task(i):
    time.sleep(1)
    return i

# the unlocked callback uses this locked callback to safely update
async def locked_update(i):
    source.stream(dict(x=[source.data['x'][-1]+1], y=[i], color=["blue"]))

# this unlocked callback will not prevent other session callbacks from
# executing while it is running
@without_document_lock
async def unlocked_task():
    global i
    i += 1
    res = await asyncio.wrap_future(executor.submit(blocking_task, i), loop=None)
    doc.add_next_tick_callback(partial(locked_update, i=res))

async def update():
    source.stream(dict(x=[source.data['x'][-1]+1], y=[i], color=["red"]))

p = figure(x_range=[0, 100], y_range=[0, 20])
l = p.circle(x='x', y='y', color='color', source=source)

doc.add_periodic_callback(unlocked_task, 1000)
doc.add_periodic_callback(update, 200)
doc.add_root(p)
```

**Comment by sophist0** [comment]
I believe this issue is related to bug: https://github.com/bokeh/bokeh/issues/13899

**Comment by bryevdv** [comment]
In this case the proper course of action is simple—the example just needs to be updated to specify a value for `radius`. @sophist0 would you be able to submit a PR?

**Comment by sophist0** [comment]
Yes I can give submitting a PR a shot @bryevdv.
