### ISSUE TITLE
[BUG] Loss of mobile touch scrolling with update to Bokeh 3.6.0

### ISSUE THREAD

**Issue by patrickjwright** [bokeh/bokeh#14107]
### Software versions

Python version        :  3.10.9 (main, Dec 20 2022, 11:37:34) [GCC 9.4.0]
IPython version       :  7.16.1
Tornado version       :  6.2
NumPy version         :  1.23.5
Bokeh version         :  3.6.0
BokehJS static path   :  /home/pwright/.pyenv/versions/3.10.9/envs/st310/lib/python3.10/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.8.0-47-generic-x86_64-with-glibc2.35

### Browser name and version

Chrome Version 129.0.6668.100

### Expected behavior

Mobile touch scrolling should be functional for bokeh applications (within any bokeh figure).

### Observed behavior

Mobile touch scrolling is non-functional after updating from Bokeh 3.0.2 to 3.6.0.

Here is my web application, where touch scrolling is non-functional after updating versions:

https://www.snowpacktracker.com/btac/stormtracker

I assume this could be true for many bokeh applications, when viewed on a mobile device? I am not sure if this is a recently introduced Bokeh bug, or something to do with how I am serving my application. However, my only change was upgrading Bokeh version.

### Example code

I can try to provide a minimal/reproducible example, but it is somewhat complex to completely reproduce my production Flask app. To start, in Bokeh my `figure` instances are all put into a `layout` such as:

```
doc = curdoc()

hor_layout_select = (
        row(
          column(hor_layout_date_slider),
          column(time_select_widget),
          column(zone_select_widget),
          column(help_spacer,help_button)
        )
    )

children = [hor_layout_select]

for f in figs:
    children.append(f)

l = layout(children, sizing_mode='stretch_width')

doc.add_root(l)
```

I am building my app as a Flask application, where I embed a Bokeh server document such as:

`bokeh.embed.server_document(bokeh_url, resources=None)`

I then use Flask's `render_template()` passing the embedded server doc and a `base.html` (which fetches bokeh js, widgets and tables resources via CDN). I am using some minimal custom css to style the container that holds the bokeh application, but I am not enabling any custom scrolling or mobile functionality in any html or css.

**Comment by patrickjwright** [comment]
Apologies for the formatting edits, and for not providing complete minimal/reproducible example at this time.

**Comment by mattpap** [comment]
Indeed, when all tools are disabled, panning over a plot should result in browser's default behavior, but currently nothing happens. Most likely a regression introduced in the recent redesign of bokehjs' UI gesture handling.

**Comment by mattpap** [comment]
We currently set `touch-action: none`, which completely prevents browser from handling touch events. What we need to do, is to manipulate `touch-action` depending on currently active tools and gestures they support. E.g. no active tools should results in `touch-action: auto`. However, there are non-tool entities that support gestures, which complicates this furthermore.

**Comment by patrickjwright** [comment]
I tried adding `touch-action: auto` to my `.container-fluid`  class as a workaround, but not successful.

My previous functionality was to have only the hover tool active by default. On mobile, if you touched inside one of the figures the hover tool would pop up with actual data values. And touch scrolling for the full application would work as well.

Do you have an estimated timeline to get a fix merged into a 3.6.x version (or 3.7)? Although this app is definitely not mobile first, it is used for operational avalanche forecasting (sometimes on mobile), so I might need to downgrade back to a previous Bokeh version by late November / early December. Do you know which specific version between 3.0.2 and 3.6.0 may have introduced this?

Thanks for all the continued effort from Bokeh contributors, it's a great library!

**Comment by bryevdv** [comment]
I'd like to release 3.6.1 this week but of course I cannot guarantee that 100%

**Comment by patrickjwright** [comment]
@bryevdv @mattpap I updated to Bokeh 3.6.1 and re-deployed my app (thank you!). Touch scrolling on mobile now works as expected. However, the `HoverTool` tooltip is not working on mobile. Previously, you could tap on the screen and use the hover tool to get actual data values (while touch scrolling was also functional).

**Comment by mattpap** [comment]
Let's start a new issue for this. For me hover works, but that's on a device with a pen.

**Comment by patrickjwright** [comment]
https://github.com/bokeh/bokeh/issues/14146
