### ISSUE TITLE
Include Bokeh plots on Authorea

### ISSUE THREAD

**Issue by smaret** [bokeh/bokeh#1413]
I would like to include some plots I've created with Bokeh on [Authorea](https://www.authorea.com/). To test this, I have created an [article](http://www.authorea.com/users/9161/articles/9681) containing a figure of the periodic table that I took from Bokeh's example directory.

After some discussion with the Authorea team, I was able to include the HTML file created with Bokeh in the article. However, only a small part of the figure is displayed. How can I scale down the figure so that it fits in the article?

**Comment by bryevdv** [comment]
Closing absent any update. Please re-open to continue the discussion with any new information.

**Comment by smaret** [comment]
Sorry for taking so long to reply. 

Setting `plot_width` and `plot_height` does the trick. I found out that Authorea includes HTML figures within an `<iframe>` with a fixed size of 500 x 500. So for the plot to be properly rendered in Authorea, one need to set the size of the Bokeh plot to these values. 

By the way, is it possible to set the dimension of the Bokeh plot relative that of the `<iframe>`, e.g. `plot_width = "100%"` ?
