### ISSUE TITLE
[BUG] documentation: sometime a wrong lexer is used to highlight code 

### ISSUE THREAD

**Issue by sblondon** [bokeh/bokeh#14137]
### Software versions

The issue is based on branch 3.7.

### Expected behavior

Some highlight is done by `python` lexer and `python-console` lexer would be more appropriate because the code sample is a copy-paste from python interpreter.

### Observed behavior

When changing to `python-console`, the highlighting will be better in such cases.

### Example code

```Python
Every sample codes starting with `>>> ` should be modified.
```

**Comment by mosc9575** [comment]
@sblondon Could you please add images to illustrate the difference of the highlighting using the two different lexers? It would be nice to see a positive effect on the bokeh docs.

I did a very quick test with one of the modified examples in your PR in a default sphinx project. This means I was using pydata-sphinx-theme as a theme with other colors than the bokeh project.

This is the result:

![grafik](https://github.com/user-attachments/assets/dfb77e2d-6930-4736-9d66-1dd1acea7578)

I don't see any improvement in the highlighting, but I want to mention that the `toggle-promt` extension, an extension bokeh doesn't use at the moment, is not working if I use the phrase `python-console`.

**Comment by sblondon** [comment]
These examples show some differences:
PythonConsole:
![python-console-lexer](https://github.com/user-attachments/assets/d2d27f50-13e1-4e1f-a5a1-bd91a6880648)

Python:
![python-lexer](https://github.com/user-attachments/assets/fd445e61-f487-4681-a6c9-de17fc8cbce9)


I've done them with the [demo of pygments website](https://pygments.org/demo/).
To be fair, IMO, the `Python` highlight mode is better on the previous example.

The screenshots you provided shows only source code without output. It could be better to keep `python` lexer and remove `>>> ` and `... ` characters. There are others source code without output (in [auto.py](https://github.com/bokeh/bokeh/blob/branch-3.7/src/bokeh/core/property/auto.py#L50), [color.py](https://github.com/bokeh/bokeh/blob/e0ac1c790f768f460ef1b7ea764d353281035915/src/bokeh/core/property/color.py#L104), [either.py](https://github.com/bokeh/bokeh/blob/e0ac1c790f768f460ef1b7ea764d353281035915/src/bokeh/core/property/either.py#L61), etc.)

Do you talk about [sphinx-toggleprompt](https://pypi.org/project/sphinx-toggleprompt/)? Does bokeh will use it in the future?

FYI, my PR has been motivated by [this issue](https://pygments.org/demo/) on pygments.

**Comment by mosc9575** [comment]
@sblondon You have linked the demo twice.

I took some time to check some more of the edited examples in the PR and I didn't find a single one where the highlighting would change. And as @sblondon showed in his example sometimes the highlighting is not improved.

This is why I would **vote to close** this issue without action.

I mentioned earlier using `python-console` could have some unwanted side effects, if bokeh decides to use the [`sphinx-toggleprompt`](https://pypi.org/project/sphinx-toggleprompt/). At the moment there is no discussion about using this extension.

The changes would look like below:

![sphinx-toggleprompt](https://github.com/user-attachments/assets/5808f9c7-42f9-484e-8bdc-a9915c9a7f4c)

This could be another issue.

**Comment by bryevdv** [comment]
I agree to close this with `noaction`. Apart from keeping the possibility of integrating the toggleprompt extension, looking at the examples above, I actually just think the standard `python` lexer just looks better in any case,.

**Comment by sblondon** [comment]
Even if I've created the issue and the PR, I agree with you two. I will try to understand why it's better with the wrong lexer. There is room for improvement on the `pygments` side.

Sorry for the noise.

**Comment by bryevdv** [comment]
No need to apologize @sblondon and we'd love to have more future contributions!
