### ISSUE TITLE
[FEATURE] Unclear docs on "first_steps_2.rst"

### ISSUE THREAD

**Issue by BenDavisson** [bokeh/bokeh#14144]
### Problem description

I was running through the docs and became confused on [this stage](https://github.com/bokeh/bokeh/blob/branch-3.7/docs/bokeh/source/docs/first_steps/first_steps_2.rst#rendering-circles).

You tell us to "switch a line() to a circle()"... however, the code shows no mention of the `circle()` being used.  Instead, you use `scatter()`.  

### Feature description

Clean up this area so it makes a bit more sense.  Either show us how to use `circle()` or show us how to use `scatter()`.

### Potential alternatives

Leave it as is.  Maybe it doesn't need to be changed?

### Additional information

Thanks!

**Comment by BenDavisson** [comment]
Noticed the same thing happens further in the doc at this step for [Defining properties of new glyph's](https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_2.html#defining-properties-of-new-glyphs).  You explain to use `circle()` and instead use `scatter()`.

**Comment by bryevdv** [comment]
@BenDavisson the old individual scatter markers like `circle` were deprecated some time ago, replaced with the single generic `scatter` option. There were a lot of places in docs and examples that had to be updated, and evidently a few got overlooked. Would you like to submit a PR to update these?
