### ISSUE TITLE
[BUG] User guide: Multiple objects layout is broken

### ISSUE THREAD

**Issue by henricryden** [bokeh/bokeh#14175]
### Software versions

N/A

### Expected behavior

The [user guide for grids and layouts](https://docs.bokeh.org/en/latest/docs/user_guide/basic/layouts.html#multiple-objects) has a final example of multiple objects, which is broken:

![Image](https://github.com/user-attachments/assets/48c64478-1f67-4b72-990e-1183c6f2f196)

Tested both Firefox and Chromium

### Observed behavior

The plot should render

### Example code

```Python
N/A
```

**Comment by mosc9575** [comment]
@henricryden Thanks for reporting this issues. This is already known and addressed in [#13077](https://github.com/bokeh/bokeh/issues/13077) and [#13784](https://github.com/bokeh/bokeh/issues/13784). I close this issue as duplicate.
