### ISSUE TITLE
[Bubble map with Pie chart at each well location on a map]

### ISSUE THREAD

**Issue by Philliec459** [bokeh/bokeh#14171]
### Problem description

I want to plot bubble maps with pie charts as the face of each bubble. 

### Feature description

Hello, I use Bokeh and Pane for all of my interactive python. I would like to make a bubble map for each well in an oil field where the size of the bubble relates to total oil production and bubble is actually a pie chart showing total oil and water production at each well. 

### Potential alternatives

I really do not have an alternative because what I am proposing is the norm in my industry. 

### Additional information

In the example below the red piece of the pie chart is oil production and the blue piece is water production. 

![Image](https://github.com/user-attachments/assets/79f281c3-65b3-4df6-af16-4ea9b3ce8c36)

**Comment by cvaske** [comment]
This type of plot is also used in the molecular biology world for spatial transcriptomics, usually with the name [scatterpie after the corresponding R library](https://cran.r-project.org/web/packages/scatterpie/index.html). See, for example:

![](https://stlearn.readthedocs.io/en/latest/_images/tutorials_ST_deconvolution_visualization_22_0.png)

https://stlearn.readthedocs.io/en/latest/tutorials/ST_deconvolution_visualization.html

Or [Figure 5I here](https://www.nature.com/articles/s42003-024-07001-y), which would benefit greatly from Bokeh's interactive features. 

The [scatterbar](https://www.biorxiv.org/content/10.1101/2024.08.14.606810v1.full) variant might be something to keep in mind as well:

![Image](https://github.com/user-attachments/assets/9d426de0-1787-4f7e-b18c-58f9e1bd4bf0)

**Comment by bryevdv** [comment]
@Philliec459  @cvaske This type of chart is already possible using existing Bokeh APIs. All of Bokeh's glyphs, including `wedge` are implicitly "scatter" glyphs. So, you can scatter wedges of all different sizes on a plot to build up a chart exactly like the one you show. (In fact, there was an ancient example of *exactly* this type of chart in the repo more than ten years ago that was removed at some point, but I haven't been able to dig it up yet.) 

If you are asking for a dedicated API call just to make this kind of chart, I would say that is unlikely. Bokeh is a more foundational tool for general plotting and generally does not provide schematized charting APIs (that is left to higher level tools built on Bokeh). 

In any case if you have questions about how to create this chart using Bokeh APIs or want to discuss specifics of those details, that's a support discussion so it should move to the  [Discourse site](https://discourse.bokeh.org)

**Comment by jbednar** [comment]
Feel free to open this as a request at the [HoloViews repo](https://github.com/holoviz/holoviews), as HoloViews is a higher level charting library built on Bokeh and the request would be in scope there.

**Comment by bryevdv** [comment]
Just to provide a concrete motivation for discussion on Discourse, here is a two minute example. This is definitely a toy example. There's lots of ways to improve this using a single `wedge` call, using cumulative sum transforms to automatically compute the wedge angle offsets, using color mappers to color wedges dynamically based on other data, etc. Any of that can be discussed on Discourse. 
```
from bokeh.plotting import figure, show
import numpy as np

N = 5
PI2 = 2 * np.pi

red = np.random.random(N)
green = np.ones(N) - red
radius = (np.random.random(N) + 0.1) * 0.2

x = np.arange(N)
y = np.arange(N)

p = figure()
p.wedge(x=x, y=y, color="red", radius=radius, start_angle=0, end_angle=PI2*red)
p.wedge(x=x, y=y, color="green", radius=radius, start_angle=-PI2*green, end_angle=0)

show(p)
```
![Image](https://github.com/user-attachments/assets/22107430-713d-4c31-8262-6e072d96debe)

**Comment by Philliec459** [comment]
This is all excellent. Let me try this on one of my oil fields for a real life example. Thank you all very much and thanks for the examples to work from.

**Comment by Philliec459** [comment]
Thank you for your suggestions. This is plotting just as I want:


![Image](https://github.com/user-attachments/assets/ace6283e-0040-4397-a10b-e703771efe35)

and this is my code:

```python
from bokeh.plotting import figure, show, output_notebook
from bokeh.models import ColumnDataSource
import numpy as np

# Enable Bokeh output in the notebook
output_notebook()

# Extract relevant columns and group by well, summing the production
grouped_data = (
    df[['Well', 'BOPM', 'BWPM', 'X_location', 'Y_location']]
    .dropna()
    .groupby(['Well', 'X_location', 'Y_location'], as_index=False)
    .sum()
)

# Calculate total production and proportions
grouped_data['Total'] = grouped_data['BOPM'] + grouped_data['BWPM']
grouped_data['BOPM_Fraction'] = grouped_data['BOPM'] / grouped_data['Total']
grouped_data['BWPM_Fraction'] = grouped_data['BWPM'] / grouped_data['Total']

# Precompute angles for the wedges
grouped_data['start_angle_oil'] = 0
grouped_data['end_angle_oil'] = grouped_data['BOPM_Fraction'] * 2 * np.pi
grouped_data['start_angle_water'] = grouped_data['end_angle_oil']
grouped_data['end_angle_water'] = 2 * np.pi

# Scale the radius based on BOPM
max_radius = 0.03  # Maximum radius for the largest pie
grouped_data['radius'] = grouped_data['BOPM'] / grouped_data['BOPM'].max() * max_radius

# Convert to a ColumnDataSource
source = ColumnDataSource(grouped_data)

# Create the figure
p = figure(title="Sized Well Production with Pie Charts", width=800, height=600, x_range=(0, 1), y_range=(0, 1))

# Add oil wedges
p.wedge(
    x='X_location',
    y='Y_location',
    radius='radius',
    start_angle='start_angle_oil',
    end_angle='end_angle_oil',
    color="red",
    legend_label="Oil",
    source=source
)

# Add water wedges
p.wedge(
    x='X_location',
    y='Y_location',
    radius='radius',
    start_angle='start_angle_water',
    end_angle='end_angle_water',
    color="blue",
    legend_label="Water",
    source=source
)

# Display the chart
show(p)
```

**Comment by Philliec459** [comment]
Is there any way to do this in Altair?

**Comment by bryevdv** [comment]
@Philliec459 That's a good question for Altair support channels.
