### ISSUE TITLE
[BUG] Dialog widget multiple show/hide broken

### ISSUE THREAD

**Issue by aprsa** [bokeh/bokeh#14183]
### Software versions

Python version        :  3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
IPython version       :  8.29.0
Tornado version       :  6.4.2
NumPy version         :  2.1.3
Bokeh version         :  3.6.2
BokehJS static path   :  /home/andrej/.venvs/tessEBs/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  v18.19.1
npm version           :  9.2.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.8.0-49-generic-x86_64-with-glibc2.39

### Browser name and version

chrome, brave, firefox

### Expected behavior

* create a dialog, set visible=False
* display a dialog via callback that sets visible=True
* hide a dialog via callback that sets visible=False
* display a dialog again via callback that sets visible=True

Dialog should be displayed.

### Observed behavior

Dialog is not displayed the second time around.

### Example code

```Python
from bokeh.models import Button, Dialog, CustomJS
from bokeh.plotting import show
from bokeh.layouts import row

open_button = Button(label="Open Dialog", width=200)

close_button = Button(label="Close", width=100)

dialog = Dialog(
    title="Example Dialog",
    content=close_button,
    visible=False
)

open_button.js_on_click(CustomJS(
    args=dict(dialog=dialog),
    code="""
    console.log('open button clicked');
    dialog.visible = true;
    """
))

close_button.js_on_click(CustomJS(
    args=dict(dialog=dialog),
    code="""
    console.log('close button clicked');
    dialog.visible = false;
    """
))

layout = row(open_button, dialog)
show(layout)
```

### Stack traceback or browser console output

Console log shows that callbacks are propagated correctly.

### Screenshots

![Image](https://github.com/user-attachments/assets/6804910d-510d-48c8-b093-4ed248087d63)

**Comment by mattpap** [comment]
This is coincidentally fixed in PR #14143.

**Comment by aprsa** [comment]
I just fetched your PR (bokeh info shows version 3.7.0.dev4+22.g27efd53b) and tried running the above code on it, but I observe the same behavior, both when using the server and when using components. Is there anything else I should have done?

**Comment by bryevdv** [comment]
You need to have:

* built BokehJS locally
* set `BOKEH_RESOURCES` appropriately to use the local build. 

See the Developer's guide for more details. 

If you look at your browser network tab and see loads from `cdn.bokeh.org` then you are only using whatever the latest published dev build happened to be a few weeks ago.

**Comment by aprsa** [comment]
Thank you @bryevdv and @mattpap!

After exporting BOKEH_RESOURSES=absolute-dev, I can confirm that the dialog reappears for the example above.
