### ISSUE TITLE
installing git version using pip fails because of BokehJs build

### ISSUE THREAD

**Issue by hnykda** [bokeh/bokeh#1419]
Hello,

I wanted to download Bokeh from git repository using pip:

```
pip install git+https://github.com/bokeh/bokeh.git
```

or after cloning the repo

```
pip install -e bokeh
```

but I get following errors. Nor choice 1 nor 2 works. Would be possible to make it work, or it's so unusual that nobody will care? I don't have idea how to do it.

```
 $ pip install git+https://github.com/bokeh/bokeh.git
Downloading/unpacking git+https://github.com/bokeh/bokeh.git
  Cloning https://github.com/bokeh/bokeh.git to /tmp/pip-whq2xiex-build
  Running setup.py (path:/tmp/pip-whq2xiex-build/setup.py) egg_info for package from git+https://github.com/bokeh/bokeh.git
    /tmp/pip-whq2xiex-build/bokehjs

    Bokeh includes a JavaScript library (BokehJS) that has its own
    build process. How would you like to handle BokehJS:

    1) build and install fresh BokehJS
    2) install last built BokehJS from bokeh/bokehjs/build

2
    Choice?
    ERROR: Cannot install BokehJS: files missing in `./bokehjs/build`.


    Please build BokehJS by running setup.py with the `--build_js` option.
      Dev Guide: http://bokeh.pydata.org/docs/dev_guide.html#bokehjs.

    Complete output from command python setup.py egg_info:
    /tmp/pip-whq2xiex-build/bokehjs



Bokeh includes a JavaScript library (BokehJS) that has its own

build process. How would you like to handle BokehJS:



1) build and install fresh BokehJS

2) install last built BokehJS from bokeh/bokehjs/build



Choice?

ERROR: Cannot install BokehJS: files missing in `./bokehjs/build`.





Please build BokehJS by running setup.py with the `--build_js` option.

  Dev Guide: http://bokeh.pydata.org/docs/dev_guide.html#bokehjs.



```

**Comment by dennisobrien** [comment]
It would be great to be able to build from a github repo.  The main use case is when you fix a bug in the source and can't afford to wait for the fix to be officially released.  I'm considering using Bokeh for a project where we use pip's requirements.txt to specify dependencies for other developers and for deployed web servers.  Being able to install from a git repo with our fixes is a lot more attractive than waiting for the next release cycle.

I tried passing the `--build_js` as an argument to pip, but that doesn't work.
```
pip install --verbose --upgrade --global-option="--build_js" git+https://github.com/bokeh/bokeh.git#egg=bokeh
```
This ends up calling `python setup.py egg_info` without passing the arguments along.  I don't know if it is a pip bug or not, but it is documented.
https://pip.pypa.io/en/latest/reference/pip_install/#build-system-interface

The workaround would be to add `--build_js` to `sys.argv` when the argument is "egg_info".  This is already done when the build argument is "sdist".

But that would still leave us with the problem of getting the gulp toolchain to work in the context of a clean git cloned repo.  I haven't gotten this far so I don't know how much of a problem it would be.

**Comment by anujnimkar** [comment]
@hnykda , were you able to resolve this eventually? I am facing the same issues that you faced while cloning the bokeh github repo (https://github.com/bokeh/bokeh).

Thanks!

**Comment by hnykda** [comment]
Almost 4 years later :smiley: ? This reminds me of how old I am getting. Have no idea, sorry.

**Comment by bryevdv** [comment]
This will never happen. Building BokehJS is a complicated process that requires lots of additional tools (Node, typescript compilers, lots of JS dependences installed). There is no way to make all that happen with a "pip GitHub install" and even it there were, it's not a priority at all. We provide easily installable "dev builds" precisely for this reason.
