### ISSUE TITLE
[BUG] DataTable example not rendering with autosize_mode="fit_viewport" or autosize_mode="fit_columns"

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#14204]
### Software versions

Python version : 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
IPython version : 8.12.0
Tornado version : 6.2
NumPy version : 1.24.2
Bokeh version : 3.6.2
node.js version : (not installed)
npm version : (not installed)
jupyter_bokeh version : (not installed)
Operating system : Windows-10-10.0.19045-SP0

### Browser name and version

Firefox

### Expected behavior

DataTable should render when using `autosize_mode="fit_viewport"` or `autosize_mode="fit_columns"`.

### Observed behavior

When setting `autosize_mode="fit_viewport"` or `autosize_mode="fit_columns"` in the example (https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#datatable) the table won't render due to a JS error:
**`Error rendering Bokeh items: ReferenceError: row is not defined`**

### Example code

```Python
from datetime import date
from random import randint

from bokeh.io import show, curdoc
from bokeh.models import ColumnDataSource, DataTable, DateFormatter, TableColumn

data = dict(
        dates=[date(2014, 3, i+1) for i in range(10)],
        downloads=[randint(0, 100) for i in range(10)],
    )
source = ColumnDataSource(data)

columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280, autosize_mode="fit_viewport")

doc = curdoc()
doc.add_root(data_table)
```

**Comment by mattpap** [comment]
Full traceback:
```
Uncaught ReferenceError: row is not defined
    getColContentSize slick.grid.js:2237
    getColAutosizeWidth slick.grid.js:2147
    autosizeColumns slick.grid.js:1997
    _render_table data_table.js:324
    _after_render data_table.js:379
    after_render ui_element.js:143
    r_after_render dom_view.js:56
    _after_resize layout_dom.js:34
    _after_resize data_table.js:163
    after_resize ui_element.js:129
    _resize_observer ui_element.js:88
```

**Comment by muendlein** [comment]
@mattpap Seems to be a dup of [#13460](https://github.com/bokeh/bokeh/issues/13460)
