### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TinkerIt789** [bokeh/bokeh#14208]
### Software versions

Python version        :  3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
IPython version       :  (not installed)
Tornado version       :  6.4.1
NumPy version         :  1.24.2
Bokeh version         :  3.6.2
BokehJS static path   :  /home/my_name/pwrctl/venv/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.6.51+rpt-rpi-v8-aarch64-with-glibc2.36

### Browser name and version

Chromium. Version 129.0.6668.89 (Official Build) built on Debian GNU/Linux 12 (bookworm) (64-bit)

### Jupyter notebook / Jupyter Lab version

No

### Expected behavior

I have a plot with datetime x-axis used for displaying monthly data (VBar).
I want to use MonthsTicker to only have ticks and matching labels (short month name and year) on months.

### Observed behavior

I get no ticks nor labels at all,

### Example code

```Python
from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, DatetimeTickFormatter, MonthsTicker
from datetime import datetime

# Sample data for 6 months
dates = [
    datetime(2024, 1, 1), datetime(2024, 2, 1), datetime(2024, 3, 1),
    datetime(2024, 4, 1), datetime(2024, 5, 1), datetime(2024, 6, 1)
]
values = [10, 20, 15, 25, 18, 22]

# Create a ColumnDataSource
source = ColumnDataSource(data=dict(dates=dates, values=values))

# Create a figure with a datetime x-axis
p = figure(x_axis_type="datetime", title="Monthly Data", toolbar_location="right", tools="pan,wheel_zoom,box_zoom,reset")

# Add VBars
p.vbar(x='dates', top='values', width=20*24*60*60*1000, source=source, legend_label="Values", color="blue")

# Customize the x-axis with MonthsTicker
p.xaxis.ticker = MonthsTicker()
p.xaxis.formatter = DatetimeTickFormatter(months="%b %Y")

p.xaxis.axis_label = "Month"
p.xaxis.major_label_orientation = 1.0  # Rotate labels for better readability

p.yaxis.axis_label = "Value"

# Show the plot
show(p)
```

### Stack traceback or browser console output

Using the following code does produce tick labels however it can also show ticks between months.
p.xaxis.ticker = DatetimeTicker(desired_num_ticks=6)
p.xaxis.formatter = DatetimeTickFormatter(months="%b %Y")

### Screenshots

![Image](https://github.com/user-attachments/assets/3f53b576-5607-4a4f-a70f-58c5da6399d3)

**Comment by bryevdv** [comment]
@TinkerIt789 you need to actually configure the months ticker to specify which months to use, e.g. to generate a tick for every month:
```python
p.xaxis.ticker = MonthsTicker(months=list(range(12)))
```
or to generate every other month:
```python
p.xaxis.ticker = MonthsTicker(months=list(range(0, 12, 2)))
```
This is documented in the reference guide (along with the default empty-list value):

https://docs.bokeh.org/en/latest/docs/reference/models/tickers.html#bokeh.models.MonthsTicker.months

**Comment by TinkerIt789** [comment]
Thx, that works as expected.
