### ISSUE TITLE
Colorbar Axis

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1441]

**Comment by damianavila** [comment]
Estimate: 1 day

**Comment by bryevdv** [comment]
OK, giving up the pretense. #1 priority after 0.8...

**Comment by timburgess** [comment]
It would be good to get an idea of the structure that you have in mind. Judging by the title, the implementation will be a subclass of Axis in <code>bokeh/models/axes.py</code>?

For reference, matplotlib makes it pretty simple to add a colorbar - but invariably there are specific parms to pass to get exactly what you want.
<pre>
# matplotlib example
plt.streamplot(X, Y, U, V, color=U, linewidth=2, cmap=plt.cm.autumn)
plt.colorbar()

# bokeh?
plotting.output_file("image.html", title='bokeh colorbar example')
plot = plotting.figure(plot_height=600, plot_width=1200, x_range=[0,10], y_range=[0,10])
plot.image(image=[data], x=[0], y=[0], dw=[10], dh=[10], palette='Spectral11')
plot.colorbar()
plotting.save(obj=plot)
</pre>

**Comment by bryevdv** [comment]
We use a constraint solver (kiwi.js) to handle the layout of things on the canvas. The issue is not s much the python spelling, or even the actual drawing of a colorbar. I don't expect any of that would take more than a few hours. The issue is that some fairly low level parts of BokehJS dealing with setting up and maintaining layout constraints will need to be extended and pushed beyond where they have been utilized up to this point. Realistically a few new abstractions need to need to be added to keep the complexity and repeated code from spiraling out of hand, and that may take a few days (I'm estimating for me, it would probably be longer for anyone else). If you are potentially interested in working on this, I would be happy to write up an outline of work tasks in more detail.

**Comment by timburgess** [comment]
An outline of steps/tasks would be very useful to me and hopefully also help you clarify what you have in mind. I have some time I can dedicate towards this but there is clearly a lot of effort required to get to a solid understanding of the python code and even more so the BokehJS part.

**Comment by SimonBiggs** [comment]
I made an interactive on selection colour bar in combination with a colour wash. It's a bit of a work around, but it doesn't use any callbacks:
http://simonbiggs.github.io/electronfactors

It would be great if something like this functionality was packaged in.

**Comment by vivekiitkgp** [comment]
@bryevdv Any updates on this?

**Comment by bryevdv** [comment]
This will not be in `0.11` proper, but `0.11` has a new mechanism for extending Bokeh with User Defined Models, so I very much hope to be able to create a custom Colorbar axis model that people can easily use until one gets added to Bokeh core library. To support this feature fully really depends on some refactoring of our canvas layout, which I hope to turn to in the next few weeks. We are prioritizing the best we can with the resources we have.
