### ISSUE TITLE
Changing title on sliders example disables crosshair tool

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1445]
To reproduce:

* start `examples/app/sliders` demo
* observer crosshair working
* change title in text box, press enter to update plot
* observe crosshair no longer working

**Comment by daliagachc** [comment]
any improvement on this issue?

**Comment by bryevdv** [comment]
We are completely re-writing a new tornado/websocket-based server in an open PR. It's possible this in in itself will resolve the issue. But in any case, if not, any work will have to wait for and be based on the completion of the new server in the `0.11` release.

**Comment by daliagachc** [comment]
Ok, i'll wait for the next release to test it, thanks for the quick answer. Just to expand on the issue, I've noticed that also the select tool stops drawing the square selection even though it still selects glyph under the selected area. 

and thanks for the bokeh project... it is great!

**Comment by bryevdv** [comment]
I can no longer reproduce this, not sure when it was fixed, but marking completed and closing.
