### ISSUE TITLE
GridPlot could allow 1d child sequence together with (n, m) tuple

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1448]
Currently `children` property must be a 2d list, but if you have a sequence of `n` plot and you would like to arrange them in a grid, then it would be easier to have: `GridPlot(children=..., layout=(5, 4))` (i.e. 5 items per row, 4 rows). One think I'm not sure about is how to implement this, because:
```
class GridPlot(PlotObject):
    children = Either(List(Instance(Plot)), List(List(Instance(Plot))))
    layout = Tuple(Int, Int)
```
would require cross-property validation (specifying `layout` doesn't make sense for 2d list). Alternatively, first argument to `Either()` could be a 3-tuple or there could be a new model for this case (`FlatGridPlot`?).

**Comment by birdsarah** [comment]
This wasn't done as part of #4392. But there are a number of improvements I'd like to make to the new `layout` function (https://github.com/bokeh/bokeh/blob/master/bokeh/layouts.py#L16), this seems like a great one

**Comment by birdsarah** [comment]
@mattpap did you implement this? I missed the details on the GridSpec PR.

**Comment by mattpap** [comment]
`GridSpec` is even better than what was proposed in this issue, giving much more flexibility the user (e.g. handling empty spaces).

**Comment by mattpap** [comment]
I'm considering this being done as part of PR #4245.
