### ISSUE TITLE
Move all base64 encoded images to *.less files

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1455]
i.e. don't pollute templates and javascript with irrelevant stuff and allow for easy overriding, etc. on CSS level.

**Comment by bryevdv** [comment]
ping @mattpap this was done?

**Comment by bryevdv** [comment]
This appears to have been done:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/less/icons.less

If I am mistaken, please re-open.
