### ISSUE TITLE
HoverTool sometimes causes "Cannot read property 'indexOf' of undefined"

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1456]
See PR #1451 as an example. Move cursor over the plot for some time. It doesn't happen constantly, just from time to time in some isolated spots. You should get this:

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined (categorical_mapper.js:29)
```

in JS console.

**Comment by mattpap** [comment]
This issue is so old and this code was changed so many times since, I doubt this is still reproducible. Note that just grepping for `indexOf` in `*.coffee` files may not be sufficient, because `in` operator generates `indexOf` as well. Perhaps looking at `*.js` generated sources should be conclusive.

**Comment by mattpap** [comment]
OK, so this may still happen, because `CategoricalMapper.{v_}map_to_target()` doesn't work well with `null`, which, I presume, is a valid value in categorical setup.

**Comment by bryevdv** [comment]
I'm not sure that's true, or intended to be true. I had not imagined a null category.

**Comment by bryevdv** [comment]
I would not actually consider `null` a valid categorical value. Given that categoricals are about to be overhauled, and this can't be reproduced, I'm closing
