### ISSUE TITLE
Charts should implement context managers protocol

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1460]
Chart classes should be able to be used like:

```
with Bar(medals, countries) as bar:
    bar.stacked().legend(True)
    bar.title("stacked, dict_input")
    bar.xlabel("countries").ylabel("medals")
    bar.width(600).height(400)
    bar.notebook().show()
```

Context managers could be used to auto-show, auto-save, etc. (especially in the notebook).

**Comment by bryevdv** [comment]
I am closing this for now, we can always revisit later at some point, but I think I have been convinced there there is no meaningful gain for either us or users here.
