### ISSUE TITLE
GlyphRenderer should have hover_glyph property

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1476]

**Comment by bryevdv** [comment]
I do think this would be a good place to use proper delegation, but I am going to move forward and implement this in a straightforward way that just checks for it and uses it when appropriate.

**Comment by bryevdv** [comment]
However, we should solve the problem of duplication of data for selection glyphs before duplicating yet again for hover glyphs. Moving out of 0.8 to `short-term`
