### ISSUE TITLE
Allow plot titles to be located on any edge of the plot (not just the top)

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#149]

**Comment by birdsarah** [comment]
@bryevdv - do you have a S/M/L estimate on this? - currently title placement is horrid.

**Comment by bryevdv** [comment]
small to medium

**Comment by mattpap** [comment]
Shouldn't we get layout working for entire plots, so that issue is trivially fixed?

**Comment by bryevdv** [comment]
This use-case will help get layout working.

**Comment by bryevdv** [comment]
Edit: to elaborate a bit more: Layout *is* working. It is just not applied in as many places as it could be (For instance, to position title labels)

**Comment by birdsarah** [comment]
Done with #4392.
