### ISSUE TITLE
Utility function to check state of numpy and pandas installation

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#1491]
As noted in @fpliger's Charts PR, it might be worthwhile to create a utility function to declare the installation status of numpy and pandas. Something like [this pattern](https://github.com/bokeh/bokeh/pull/1387/files#diff-34aedf0711a1f483d7e7662ba1774fe1R26):

```
try:
    import pandas as pd
except ImportError:
    pd = None
try:
    import numpy as np
except ImportError:
    np = None
```

This is also tied to another issue: ["Hard dependency on numpy"](https://github.com/bokeh/bokeh/issues/1280)

**Comment by bryevdv** [comment]
This was done.
