### ISSUE TITLE
categorical ranges x_range

### ISSUE THREAD

**Issue by Lijantropique** [bokeh/bokeh#1492]
When creating bar charts for two categorical values (side by side), there are some issues with the x_range of the plot: 1. if the x values (centers of rectangles representing each category) are augmented (in order to create more space between two different categories) the right part of the plot is missing. 2. if the bars are getting wider the right part of the plot is missing and normally one category dissapear.

Please see attached image.

![barcharts](https://cloud.githubusercontent.com/assets/5657134/5267190/3d76a5a6-7a1d-11e4-9f2f-7c9f91f110b5.png)

Best regards

**Comment by Lijantropique** [comment]
Sorry for the late reply. With the new update of Bokeh there is no issue with categorical bar graphs.
Regards,
Lij.

**Comment by bryevdv** [comment]
Thanks for the update @Lijantropique !
