### ISSUE TITLE
Make new hover tool which is a "loupe" or magnifying glass

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#1493]
**Transient mode**
When the user clicks on the plot, a transient box is drawn over the plot at the position of the cursor, which shows a zoomed-in view of the data.
![image](https://cloud.githubusercontent.com/assets/543576/5267769/4e49dc9e-7a19-11e4-9c00-843ccf95480b.png)

**Persistent mode**
The user clicks on a plot to create a zoombox, and when the zoombox tool is active, each zoombox has a small Close, Resize, and Move scrubber in its border.  (Perhaps the user can wheelzoom over a zoombox to set its zoom level, or maybe there is just a set of :mag: icons.)  When the zoombox tool is deactivated, the zoomboxes stay around (but with more minimal frame elements).  When the user pans the plot view region, the zoomboxes move along with it.  When the user zoom in, the zoomboxes may disappear or be clipped out of the view region.  When the user zooms out, the zoomboxes may need to be dodged or just overlap.  (Here's a nice use of those annotation callout arrows, @bryevdv!)

**Note for touch interfaces**
For touch, we need to make sure that both modes of creating zoomboxes render them at some offset and not right under the finger, even though the point of interest which they zoom on should be the point under the finger.

**Other configurable aspects**
- size of zoom box: fixed in screen space units or data space units
- option to add hover information about the point or region under the cursor, and have it displayed underneath/above/besides the zoom box. Use same formatting options as current hover tool template.
- x-ray mode for when inspecting AR or naively downsampled data: show all the points etc. (This might be network intensive?)

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by niloxx** [comment]
Hey, I am interested on this too, is there any update? Thanks

**Comment by bryevdv** [comment]
No, but at this point such a tool could be added as a custom extension:

http://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html

And that might be the best place for it to start, honestly

**Comment by bryevdv** [comment]
I'm going to link this to #182 and let it be considered part of that that disucssion.

**Comment by jbschiratti** [comment]
I'm also interested in such a feature. Given that this is an old issue, has such a feature been implemented? I could not find it.
