### ISSUE TITLE
Remove unused DataFactorRange

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#1503]
The model is implemented in BokehJS ([`DataFactorRange`](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/range/data_factor_range.coffee)) but not exposed in Python.

**Comment by bryevdv** [comment]
This would be nice for categorical ranges... It would be trivial to expose, but it's not used anywhere and I am not even sure it works, so it needs a little inspection and investigation first.

**Comment by bryevdv** [comment]
Actually, just going to go the opposite direction, and remove it until (if) it ever ever proves to be needed.
