### ISSUE TITLE
Suggestion to support asyncio in 0.7.x

### ISSUE THREAD

**Issue by rjpereira** [bokeh/bokeh#1508]
It would be very nice if we could embed bokeh-server on our own applications rather than require it to be launched separately. I belive there may be already ways to run it in separate process or thread, but my tests tell me that it would be very simple to add asyncio support in 0.70 tornado's version.
What I did:
on server/start.py:
Added `from tornado.platform.asyncio import AsyncIOMainLoop`
Replaced lines:

    server.listen(server_settings.port, server_settings.ip)
    ioloop.IOLoop.instance().start()

with

    AsyncIOMainLoop().install()
    server.listen(server_settings.port, server_settings.ip)

To test simply started it with

    import asyncio
    import bokeh.server.start
    bokeh.server.start.start_simple_server()
    loop = asyncio.get_event_loop()
    print("Sleeping now...")
    loop.run_forever()

I'm not sure exactly what would be the best way to make it an option rather than direct replacement, but hopefully such a small change can make into a next version to make it asyncio friendly...

**Comment by bryevdv** [comment]
@hhuuggoo right sorry I got that from other discussion, I was more wondering what the deployment example in this case might look like.

**Comment by shongololo** [comment]
+1 for ensuring general patterns easy to employ from asyncio compatible frameworks, e.g. aiohttp

**Comment by bryevdv** [comment]
Not really relevant given new server direction, closing.
