### ISSUE TITLE
Restore BokehJS interface

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1515]
`Bokeh.plotting` is currently badly broken in 0.7. Propose to remove current interface completely, and replace with a new better interface that is built into a separate module `bokeh-api.js`

Note: going through and closing basically all old BokehJS issues. Rationale is to collect references to them here, so that the new JS interface can incorporate all of them (or what makes sense) in a holistic rather than piecemeal fashion.

**Comment by alexbw** [comment]
Might I suggest taking inspiration from the plotly.js inferface? https://plot.ly/javascript-graphing-library/

**Comment by bryevdv** [comment]
HI @alexbw Thanks, a quick glance seems to indicate that this interface is not un-similar to the early prototype `Bokeh.plotting` interface that we had before. I actually expect the new BokehJS interface to be fairly similar to the old BokehJS just with more convenience and capability exposed. The main problem with the old interface was really one of implementation, not necessarily the API itself. It was hastily thrown together as a basic engineering tool and was not flexible or adaptable. 

As we start to work on this issue (in earnest in a couple of weeks, I expect) would you be available to test/try out things and provide feedback?

**Comment by alexbw** [comment]
I would love to.

**Comment by bryevdv** [comment]
Great, I look forward to your input!

**Comment by damianavila** [comment]
status: some work in the next days (1 - 2) and ping the mailing list

**Comment by alexbw** [comment]
Great to hear this is alive!

**Comment by bryevdv** [comment]
@alexbw Only now able to get started, you can follow the WIP PR above to add comments. I may be able to have something *very* simple for the 0.8 release this week, with improvements to follow on. Feedback very welcome.
