### ISSUE TITLE
Charts should implement top level reader functions

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1521]
Charts should implemented top level reader functions just like those exposed by Pandas (http://pandas.pydata.org/pandas-docs/stable/io.html) or even a just simpler wrapper functions like read_file, read_msg, read_clipboard, ....

CLI would also benefit from this.

**Comment by bryevdv** [comment]
`bokeh.charts` just depends on Pandas now, there's no reason to re-create the functionality in pandas.
