### ISSUE TITLE
Scatter plot awfully slow (does not plot "150 000" points)

### ISSUE THREAD

**Issue by lebigot** [bokeh/bokeh#1536]
When I plot through `bokeh-server` a simple line of 150 000 points (with coordinates `numpy.arange(150000)` in both x and y) with `bokeh.plotting.scatter()`, Chrome displays it in maybe 15 seconds on my machine.

(**PS**: see below one of my posts for a very simple way of reproducing the problem.)

Now, the problem is that if I replace these points with a (slice of a) NumPy (record) array of about the same size but with the following values and counts:

- For x: `Counter({2.3047667919672676: 173179, 2.304502478800714: 28, 2.3046346353839908: 20, 2.3046786875784164: 3})`
- For y: `Counter({48.871065381777882: 173179, 48.870455568697587: 28, 48.870760475237738: 20, 48.870862110751112: 3})`

then **the graph takes forever to be rendered** by the browser (I had to close the window after many minutes). I observe the same thing with Safari (each time, the *browser* takes forever).

The problem is the same when I go through an HTML file instead.

The values in the two coordinates are paired in the same order as above, meaning that the resulting scatter plot has exactly *4* points: this is the main difference between the scatter plot that goes reasonably fast and the problematic one.

I tried with a single point repeated 150 000 times (`scatter(numpy.full(150000, 1.23), numpy.full(150000, 1.23))`) and this is awfully slow too: the browser takes forever. The problem thus seems to lie with the special case of repeated points in the same location.

**Comment by damianavila** [comment]
> For reference #902 I wonder if this issue was related.

@bryevdv, I tested the examples with the new plotting API and with this branch and the problem reference in #902 persist...

**Comment by lebigot** [comment]
I tried again, this time with Bokeh 0.8:
```
p = figure()
coords = numpy.full(150000, 1.23)
p.scatter(coords, coords)
```
With the latest Chrome of OS X (40.0.2214.111 64 bits), I had to stop my MacBook Air after **5 minutes** without rendering anything.

**Comment by damianavila** [comment]
Trying this code i get this:

```javascript
Javascript error adding output!
RangeError: Maximum call stack size exceeded
See your browser Javascript console for more details.
```

@lebigot, do you see the same...

**Comment by bryevdv** [comment]
I'm not sure what we can do about that we have no control over browser stack size limits.

**Comment by denfromufa** [comment]
I got the same in `Maximum call stack size exceeded` with latest bokeh release using ipython notebook as the output.
Is there any workaround without filtering out datapoints?
I can generate similar, but static plots with matplotlib.

**Comment by bryevdv** [comment]
Closing this discussion. Initial WebGL support is landing in `0.10` additionally the new server is being designed with binary transfer of data arrays into JS typed arrays as a feature. (That's probably `0.11`) I don't think there is anything further we could possibly do, if people still run into problems its time to turn to downsampling/datashading.
