### ISSUE TITLE
Grey9 very light with 0.7.0

### ISSUE THREAD

**Issue by lguibert** [bokeh/bokeh#1545]
I just updated my bokeh to the 0.7.0 version. Amazing stuff everywhere ! But, one bad point I saw is that the Grey9 palette is very light wheras the Grey9 was really strong in the 0.6.1. 

I guess everybody will see the difference... 

Greys9 with 0.6.1 :
![](https://lh3.googleusercontent.com/-fpnQ6YT-kB4/VIoh-4qZ2mI/AAAAAAAAEic/gjU6P9_vdyQ/s1600/Capture%2Bd%27%C3%A9cran%2Bde%2B2014-10-30%2B12%3A07%3A04.png)

Greys9 with 0.7.0 :
![](https://lh6.googleusercontent.com/-aBdhvP_Vyw4/VIohf_dAxxI/AAAAAAAAEiU/6IcFkxwDXlQ/s1600/Capture%2Bd%27%C3%A9cran%2Bde%2B2014-12-11%2B14%3A56%3A44.png)

Thanks for your incredible work !

**Comment by bryevdv** [comment]
@lguibert FYI I believe this is fixed and the PR will be in 0.7.1 However if you can confirm that it works with this PR that would be immensely useful information.

**Comment by damianavila** [comment]
@lguibert we have merge the fix, please reopen the issue if the fix does not work for you. Cheers.
