### ISSUE TITLE
High Level Charts Disable Scientific

### ISSUE THREAD

**Issue by Rockyyost** [bokeh/bokeh#1549]
Can we disable scientific notation for high level charts? Is it possible to use engineering notation instead? For example, get 3M instead of 3,000,000?

Thanks!

**Comment by gvdeynde** [comment]
I just noticed that the LogTickFormatter doesn't have the option 'use_scientific'. Is this wanted behaviour? I now have a loglogplot with '10^-1' etc as labels. I would like to see this as $10^{-1}$ or $1e-1$.

**Comment by damianavila** [comment]
Please reopen if there is interest.

**Comment by josherick** [comment]
As @damianavila suggested, I tried

    from bokeh.models import Axis
    bar = Bar(data, ...)
    yaxis = bar.chart.plot.select(dict(type=Axis, layout="left"))[0]
    yaxis.formatter.use_scientific = False
    bar.chart.show()

But I get an error that 'bar' has no attribute 'chart' or 'plot' for that matter. Has the interface for `Chart` changed since this was suggested? Is there a different way to do this now?

**Comment by damianavila** [comment]
@josherick yes, the charts interface change a lot since that time... this should work:

```python
from bokeh.embed import components
from bokeh.models import Axis
from bokeh.charts import Bar
data = {"y": [6, 7, 2, 4, 5], "z": [1, 5, 12, 4, 2]}
bar = Bar(data)
yaxis = bar.select(dict(type=Axis, layout="left"))[0]
yaxis.formatter.use_scientific = False
script, div = components(bar)
print(script)
print(div)
```

**Comment by josherick** [comment]
Perfect! Thanks for responding so quickly.

**Comment by nscozzaro** [comment]
I'm really confused... how does your code access the "BasicTickFormatter" class? Is "formatter" short for BasicTickFormatter?
```
yaxis = bar.select(dict(type=Axis, layout="left"))[0]
yaxis.formatter.use_scientific = False
```
I can't figure out how to access the NumeralTickFormatter class. Please let me know how one uses this, thank you!

**Comment by nscozzaro** [comment]
Nevermind, I just found a post on StackOverflow explaining:
`
from bokeh.models import NumeralTickFormatter
p.yaxis.formatter=NumeralTickFormatter(format="00")

`
