### ISSUE TITLE
Allow to render paths longer than 32k points

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1555]
This is browser dependent (reproduced under Chrome 34).

**Comment by damianavila** [comment]
status: require some investigation

**Comment by bryevdv** [comment]
There have been no updates or reports on this in over two years. I am going to close this as stale. There is also now the option of using datashader for larger data sets which did not exist before.

**Comment by jason-s** [comment]
sorry, I no longer use bokeh + don't have time anymore to investigate.
