### ISSUE TITLE
Build a demo box

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1559]
We need to provide a demo box with the latest release for demoing purposes. It has to include at least:

* *all* the notebooks
* *all* the demos
* the ocean, population, taxi demos
* linked datatable
* numba slider,
* etc

pinging @pzwang to let us know what else he wants/need...

**Comment by bryevdv** [comment]
These are all pretty simple to run now. I think the original motivation has diminished enough to close.
