### ISSUE TITLE
Expose a way to configure plot/document URL on the server

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1560]
From recent questions on m.l. it would be nice to *easily* let users set the URL of a plot on the server. Right now its URL is generated by session using document and plot ids (docid, _id) [and apparently is not easily hackable].

Something like having a "url" argument on `session.store_document`?

**Comment by bryevdv** [comment]
This refers to the old `bokeh-server`, closing. URL is now configurable by choosing the app file name/directory name as desired, or by running behind a proxy for real deployments.
