### ISSUE TITLE
More DataTable improvements

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1563]
- [ ] add support for external editors (not directly embedded in cell's HTML)
- [ ] finish remaining cell editors (text, time, date, etc.) (PR #1653)
- [ ] add more cell formatters (time, date, etc.)  (PR #1653)
- [ ] figure out why `select` ignores `keydown` event (prevents editor from using arrows)
- [ ] fix table width in Firefox
- [ ] auto-construct `TableColumn`s from `DataFrame`/`DataSource`

**Comment by bryevdv** [comment]
status: low priority, possibly move off to 0.8.1

**Comment by datnamer** [comment]
some good ideas here: http://renkun.me/formattable/

**Comment by bryevdv** [comment]
@mattpap what of this remains?

**Comment by mattpap** [comment]
Pretty much everything, though I doubt any of this is going to get done.

**Comment by bryevdv** [comment]
OK I am going to close this then, and if there is interest/demand then individual issues can be opened later.
