### ISSUE TITLE
Donut charts example not drawing annular lines

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1578]
On the donut example first category values are not showing the white lines to separate values. See attached image.

![charts_donut](https://cloud.githubusercontent.com/assets/1084690/5538038/5fd24750-8aac-11e4-8e99-bfa9525d9cfa.png)

**Comment by damianavila** [comment]
Hey @fpliger,

This is working for me from master...

![2015-01-08-165905_1366x768_scrot](https://cloud.githubusercontent.com/assets/1640669/5669619/c1149632-9757-11e4-9345-112ad2bbc419.png)

**Comment by fpliger** [comment]
Argh... was so happy when a I say it was fixed! :smile: 

Do you remember which branch? It may be useful..

**Comment by damianavila** [comment]
Not only remember... I can reproduce it... je je

The branch where it is working is `feature/1636_grid_none` which is actually merged here: https://github.com/bokeh/bokeh/pull/1640

**Comment by damianavila** [comment]
And to are more... in current master it is working in python 3, but not in python2... maybe that help you a little bit :wink:

**Comment by fpliger** [comment]
Ah! I think I have a guess now :+1:

**Comment by fpliger** [comment]
Just to share the pleasure of this issue... it randomly fails on python 3 too. Usually when it happens it works again if I deactivate and reactivate my env. Quite frustrating.. :-/
