### ISSUE TITLE
Use new layout system to create vertically oriented GeoPhysics plots

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1586]

**Comment by birdsarah** [comment]
@bryevdv - can we close this. It sounds awesome but is a little thin on the details :D :D

**Comment by bryevdv** [comment]
@pzwang and I have the details in our heads. :) Basically there are plots called well-logs that are fairly common, and it would be useful to demonstrate that Bokeh can accommodate them. You can see some examples here: http://www.geoloil.com/logLAS.php

**Comment by birdsarah** [comment]
I love what they've done with the styling :D

**Comment by VelizarVESSELINOV** [comment]
@bryevdv let me know if you have progressed with this one sounds interesting

**Comment by bryevdv** [comment]
Well nothing ever happened with this. I am sure Bokeh could be used to create those kind of plots, but at least anymore, I don't think we need to go out of our way to be the ones to demonstrate it.
