### ISSUE TITLE
BokehJS unrecoverable errors in notebook 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1592]
It seems easy to get the notebook into an unrecoverable state when using `push_notebook` and IPython interactors. Must close the session entirely and start again to regain plots. Executing all the cells in the notebook stored in this gist:

https://gist.github.com/bryevdv/b4e9eb68a6234a67a570

should reproduce the problem.

To be specific, by "unrecoverable" I mean that clearing all cells and restarting the kernel from the menu does not fix the problem. It is still impossible to generate plots. I have had to close the tab and shutdown from the IPython home notebook list, then re-open a new tab to be able to plot again. 

@damianavila this is a pretty serious bug. We should try to fix it for 0.7.1 for sure. I will take a look and add any findings but I may need your input/assistance.

**Comment by damianavila** [comment]
Nice you have found the issue...
