### ISSUE TITLE
Twitter scrapping map demo using CLI tool 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1598]
References: #1585 

Description from @pzwang : "twitter-scraping tool that plops geotagged tweets matching some hashtags as scatter points on a map plot"

The main task for this would be figuring out how to allow users to spell (on the command line) a mapping from the data returned from some REST endpoint, to what gets shoved into a Bokeh `ColumnDataSource`. @pzwang your input on what you'd like to be able to write at the command prompt to make this happen would help drive this.

**Comment by pzwang** [comment]
You're absolutely right - the data download portion of that demo will be significant to do "for real", and introduce a lot of code and complexity that is unrelated to the purpose of demonstrating bokeh's features.  It would be sufficient and simpler to have an example gzipp-ed file of JSON tweets (maybe even downloaded from Twitter or some other source), and a Python one-liner to read out a tweet every second.

    python -c 'import gzip,time,sys; for line in gzip.open("sampletweets.gz"): (sys.stdout.write(line),time.sleep(1))'

**Comment by fpliger** [comment]
Opinions about how users could specify that they want a GMapPlot? First thing I can think of is a new CLI option:  `--gmap`  that accepts "lat,lon,zoom,map_type" and tells how to build the GMap. Show usage would be:

```Bash
bokeh --gmap "97.3,36.2,10,hybrid"
```

**Comment by mattpap** [comment]
I'm not sure if I would prefer to have this fully expanded or something like this:
```
$ bokeh --gmap=97.3:36.2 --zoom=10 --map=hybrid"
```

**Comment by bryevdv** [comment]
+1 on that suggestion

**Comment by fpliger** [comment]
I like it more too. But what about `map_zoom`? `zoom` could be exchanged with the zoom tools..

**Comment by bryevdv** [comment]
```
$ bokeh --map=97.3:36.2 --map_zoom=10 --map_layer=hybrid"
```
later possibility of `--map_type=geojs`, e.g.

**Comment by fpliger** [comment]
+1 (using `map_layer` here overlaps with `GMapOptions` attr `map_type` but I think it's the best option and is an implementation details not know to most of users)
