### ISSUE TITLE
Remove 0xA0 characters (and encode source files properly)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1605]
Reference: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/RlnJgX6KfsU

**Comment by mattpap** [comment]
I can confirm that the default for plotting API is non-minified resources. @bryevdv, https://github.com/bokeh/bokeh/blob/master/bokeh/plotting.py#L477 explicitly issues `minified=False`.
This was added e3fa6b4c7638042974ed72311c617834a377fb50. Perhaphs left-over debugging aid?

**Comment by bryevdv** [comment]
Yes, probably. Let's change it and add a test for it.
