### ISSUE TITLE
$ can get overridden in the Notebook 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1606]
It is (evidently) possible for other libraries to override `$`, and then our use of `$(function() ...)` as `js_wrapper` here:

https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L248

is fragile, and can cause problems, specifically plots not reloading. This was reported here:

https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/7CJxL7cKxXs

@mattpap just changing to `Bokeh.$` seems to work fine. Do you have any other input?

**Comment by bryevdv** [comment]
@mattpap I am going to make a PR that just makes the `$` -> `Bokeh.$` sub, if there is more or different actions to take please add your thoughts.

**Comment by mattpap** [comment]
That should be sufficient. As I said in yesterday's meeting, the only global variable that bokeh touches is `Bokeh`.
