### ISSUE TITLE
typo in ChartObject error message when filename argument is missing

### ISSUE THREAD

**Issue by jxstanford** [bokeh/bokeh#1612]
If the filename is left off a ChartObject, the following message is generated:

    You have a provide a filename (filename='foo.html' or .filename('foo.html')) to save your plot.

The message should be:

    You have to provide a filename (filename='foo.html' or .filename('foo.html')) to save your plot.

Code to recreate the issue:

```
from bokeh.sampledata.iris import flowers
from bokeh.charts import Scatter

df = flowers[["petal_length", "petal_width", "species"]]
g = df.groupby("species")

scatter = Scatter(g)
scatter.title("iris dataset").legend("top_left")
scatter.width(600).height(400).show()
```

**Comment by bryevdv** [comment]
@jxstanford it looks like you have fixed it in your fork, do you plan on submitting a Pull Request?

**Comment by jxstanford** [comment]
I think it’s been merged:  https://github.com/bokeh/bokeh/pull/1613 <https://github.com/bokeh/bokeh/pull/1613>

John

jxstanford@gmail.com
@jxstanford

**Comment by bryevdv** [comment]
Hah! so it has. Thanks :)
