### ISSUE TITLE
toolbar buttons do not work on updating server plots

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1618]
Run `examples/plotting/notebook/animated.ipynb`, it is not possible to activate any toolbar buttons while the plot is updating.

**Comment by bryevdv** [comment]
@bokeh/dev any ideas on this one? Do we need to resort to web workers or something to service the web socket updates from the server?

**Comment by Maggie-M** [comment]
I have reproduced this behavior with one exception:

Running *Python 3* on *OSX* and using *Chrome* as the default browser, I was able to wheel zoom and pan.  When I **resized the plot**, however, all of the widget's hover text names began blinking and I was unable to use any of them anymore.

**Comment by bryevdv** [comment]
This was fixed at some point, works perfectly with e.g. `app/fourier_animated`
