### ISSUE TITLE
Charts behaviour when notebook=True and server arguments are specified

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1621]
Right now this makes the browser one a new tab pointing to the bokeh-server url that is hosting the plot and creates a new iPyNB cell output. IMO it makes sense to just generate the output cell..

**Comment by fpliger** [comment]
Will be closing this one later today. If any @bokeh/dev have different opinions about this please let me know.

**Comment by damianavila** [comment]
I agree with your opinion...
