### ISSUE TITLE
Charts.GMap class

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1629]
GMap class would be a great addition to charts interface (not to mention that it's a mandatory missing piece for #1598) . 

It's a very different type of chart comparing to the charts we already have in place. In details it needs the GMapOptions arguments to help building the map (lat, lng, zoom and map_type). With that in mind I can think of 2 implementations:

* one that takes all GMapOptions as a `dict` or as `models.GMapOptions` object, like:

```Python
from charts import GMap
options = dict(lat=30.2861, lng=-97.7394, zoom=15, map_type="hybrid")
map = GMap(options, title="GMap Demo")

# or 
options = GMapOptions(lat=30.2861, lng=-97.7394, zoom=15, map_type="hybrid")
map = GMap(options, title="GMap Demo")
```

* one that takes all GMapOptions arguments as a separated `charts.GMap` arguments, like:

```Python
from charts import GMap
options = GMap(lat=30.2861, lng=-97.7394, zoom=15, map_type="hybrid", title="GMap Demo")
```

I think I prefer the later but don't have strong opinions about it..

**Comment by damianavila** [comment]
I think I would go with the last one too...
