### ISSUE TITLE
change colors in bokeh.charts plots?

### ISSUE THREAD

**Issue by bryanbriney** [bokeh/bokeh#1645]
Is there a way to change the color palette for high-level charts (Step, Scatter, etc)?  The default palette is nice, but the first two colors are red and green, which is not optimal for a colorblind audience.  Looks like current palette is just a list of of hexs, so being able to pass an alternate (plot.colors()?) would be nice.

**Comment by fpliger** [comment]
We do have an open issue for that #1464.
 
This should hit master really soon and is planned to be shipped with version 0.8.

If you really need it now (or want to experiment) you can force a palette by patching the chart. Like the following:

```Python
from collections import OrderedDict

import numpy as np

from bokeh.charts import Bar
from bokeh.sampledata.olympics2014 import data as original_data

data = {d['abbr']: d['medals'] for d in original_data['data'] if d['medals']['total'] > 0}

countries = sorted(data.keys(), key=lambda x: data[x]['total'], reverse=True)

gold = np.array([data[abbr]['gold'] for abbr in countries], dtype=np.float)
silver = np.array([data[abbr]['silver'] for abbr in countries], dtype=np.float)
bronze = np.array([data[abbr]['bronze'] for abbr in countries], dtype=np.float)

medals = OrderedDict(bronze=bronze, silver=silver, gold=gold)

bar = Bar(medals, countries, title="grouped, dict_input", xlabel="countries", ylabel="medals", 
          legend=True, width=800, height=600, notebook=True)
bar._set_colors = lambda *args: ["#df5320", "#00ad9c", "#c33ff3"]
bar.show()
```

This is an ugly patch but works.

**Comment by pofican** [comment]
I am facing a similar issue with Dot Charts and tried your solution still no luck cause there is no _set_colors attribute for a Dot Chart object:
AttributeError: 'Chart' object has no attribute '_set_colors'
Any ideas?

**Comment by birdsarah** [comment]
Good news - it's super easy now.

````python
from bokeh.palettes import brewer
palette = brewer["Blues"][3]
````
pass palette into chart call e.g. 
````
bar = Bar(medals, countries, title="grouped, dict_input", xlabel="countries", ylabel="medals", 
          legend=True, width=800, height=600, notebook=True, palette=palette)
````

Palette can actually be a list of any values you want, but there's built in ones shown here: http://bokeh.pydata.org/en/latest/docs/reference/palettes.html

It's very briefly documented here: http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#generic-arguments

**Comment by birdsarah** [comment]
I opened an issue to improve the documentation: #1873

**Comment by pofican** [comment]
Thank you, the documentation is not very detailed and seems like it is out of date.

**Comment by bryevdv** [comment]
@pofican The charts interface is the newest interface to be added to Bokeh, and has undergone a period of rapid iteration and experimentation. Recently we have settled on a happy design architecture that should remain stable, so we can (and intend to) begin proper documentation.

**Comment by jpiabrantes** [comment]
Is there a quick way to change the alpha of the lines? something like: `TimeSeries(df,y='y',alpha=0.1)`
