### ISSUE TITLE
Issue Validation error when plots are duplicated in one document

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1650]
Code to reproduce, top four plots do not render glyphs (tools work and versions below respond accordingly)

```
import numpy as np

from bokeh.plotting import figure, output_file, show
from bokeh.layouts import column, gridplot

N = 50

x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)

output_file("grid.html", title="grid.py example")

TOOLS = "pan,wheel_zoom,box_zoom,reset,save,crosshair"

l = figure(title="line", tools=TOOLS, plot_width=300, plot_height=300)
l.line(x,y, line_width=3, color="gold")

aw = figure(title="annular wedge", tools=TOOLS, plot_width=300, plot_height=300)
aw.annular_wedge(x, y, 10, 20, 0.6, 4.1, color="navy", alpha=0.5,
    inner_radius_units="screen", outer_radius_units="screen")

bez = figure(title="bezier", tools=TOOLS, plot_width=300, plot_height=300)
bez.bezier(x, y, x+0.4, y, x+0.1, y+0.2, x-0.1, y-0.2,
    line_width=2, color="olive")

q = figure(title="quad", tools=TOOLS, plot_width=300, plot_height=300)
q.quad(x, x-0.2, y, y-0.2, color="tomato", alpha=0.4)


p1 = gridplot([[l,aw],[bez,q]])

# specify "empty" grid cells with None
p2 = gridplot([[l,None,aw],[bez,q,None]])

show(column(p1, p2))
```

**Comment by bryevdv** [comment]
Nevermind, problem was because `q` was re-used...

**Comment by bryevdv** [comment]
This is still a problem in `0.12` due to "duplicate edit variables"

**Comment by birdsarah** [comment]
Just to clarify: what is expected to happen in this use case. Are the two plot objects the same i.e. if you pan/select/.... one the other one shows the same?

**Comment by bryevdv** [comment]
I still can't think of any real reasonable use-case for duplicating plots (or more generally, any "layoutable") in a document. I think "solving" this would be a waste of effort to fix a non-problem, so instead I propose to add a validation check for situations like this, which should be simple to check.

**Comment by bryevdv** [comment]
unfortunately `Model.references` returns a set. Which means we could potentially detect this when the duplicate added to a *different* root. But I don't see any good way to determine it in the case above, where the duplicate is buried twice in the *same* root. I don't think it is common in the first place, but in the event it does happen I think that second case is more common, so I don't think it's worth adding complexity on the python side to detect across roots. 

Instead, I will add a note to the JS error message saying it "may indicate the same plot has been added twice"

**Comment by bryevdv** [comment]
well, actually that error is coming from inside kiwi. I have not seen this come up much or at all lately,  so I think we just live with this and point occasional support reports and requests to this issue.

**Comment by mattpap** [comment]
"duplicate edit variables" error will still happen anytime one uses the same layoutable model in a layout (per solver). One option is to ban such usage, or alternatively we could detach layout state from models and move it to views. I'm slowly working my way to achieve the later.

**Comment by bryevdv** [comment]
> One option is to ban such usage

That was my initial plan, see above for why it is not straightforward to do.
