### ISSUE TITLE
[documentation] on embedding

### ISSUE THREAD

**Issue by cloudformdesign** [bokeh/bokeh#1663]
I found it difficult to learn how to embed. The embedding example was helpful, but overly complicated. I wrote this much simpler code that I think will be helpful for new users:

https://gist.github.com/cloudformdesign/0cff67b169b49cc8ae39

If you have any suggestions feel free to give them so that both I and others can learn. Thanks!

**Comment by bryevdv** [comment]
Garrett, 

This is really great! Would you be interested in contributing a Pull Request with this example? You could just add the files and a README to the examples dir, or if you like, add a small section to the Sphinx docs that walk through this minimal example there. Let us know if you are interested, if there is anything we can do to help!

Bryan

**Comment by bryevdv** [comment]
I should mention though, that you are using deprecated code that will be removed in 0.8. Now all the glyph functions are methods on a figure object.  It's more explicit, and better and quite simple to change to:

    p = figure(...)
    p.line(...)

Bryan

**Comment by cloudformdesign** [comment]
Gotcha,  I will make the changes and make the pull request :)

- sent from my Android

**Comment by cloudformdesign** [comment]
Also,  can you give me a pointer on the idea behind RESOURCES.render

I don't know much about html or Java script,  so I don't see what it does
in the template other than it is necessary

- sent from my Android

**Comment by cloudformdesign** [comment]
PR: https://github.com/bokeh/bokeh/pull/1665

**Comment by bryevdv** [comment]
@cloudformdesign `RESOURCES` is a Jinja2 template, and the `render` method is just the standard method that Jinja2 exposes. It takes a dictionary of names and values and substitutes the values into the template, wherever the name appears (basically). The specific purpose of `RESOURCES` is to provide a single template that can handle all the possible combinations of loading BokehJS (e.g., putting it in line, loading from CDN, or from your own server) This is quite low level I would not actually expect users to need to interact with any of the templates directly (they are really implementation details used the functions in `bokeh.embed`, which are what users should be using)
