### ISSUE TITLE
CLI copy selection feature

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1667]
Following discussions on #1657. Should the CLI implement copy to clipboard or pass through stdout so it could be piped to another process? Or both?

**Comment by mattpap** [comment]
It's sufficient to implement pipes, because then you can use `xsel` or `xclip` to get data into clipboard (at least on Linux).

**Comment by bryevdv** [comment]
I concur pipe to `stdout` is sufficient.
