### ISSUE TITLE
mechanism for semantic (re-)labeling of numeric tick values

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1672]

**Comment by mjmare** [comment]
Would this enable me to assign a set of labels at specfic position on the axis?

**Comment by bryevdv** [comment]
Well, the use case I had in mind was to be able to have more meaningful tick labels. This might be what you have in mind too. A specific example I can think of is sometimes a plot is useful to label on a scale proportional to some physical constant. So it might be nice to have ticks at *\alpha*, *2\alpha*, *3\alpha*, etc.

**Comment by wiemerc** [comment]
I think another good example is grades expressed as numbers (because you want to plot average grades for example), but you want to label the axis with the corresponding letters (A = 1, B = 2...).

**Comment by bryevdv** [comment]
I think this is a dupe of #1671 

In the case you want to completely override the formatting of a label, #1671 covers that. In case you just want to add some additional dressing around a tick value (e.g., `6 things`) That is covered by `PrintfTickFormatter`
