### ISSUE TITLE
Ajax/JSON data source

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1682]
Expose a data source that can be configured with  a URL to a REST endpoint along with a mapping or metadata for populating data columns, that can be used to pull data directly to the client. 

Requirements:
* must integrate with blaze server endpoints #1635
* must be usable to simplify spectrogram example further

**Comment by bryevdv** [comment]
@hhuuggoo cab you update or point to another issue with status?

**Comment by hhuuggoo** [comment]
current status is in #1635

**Comment by matdrapeau** [comment]
Is this feature only specific to the blaze server?

What about any kind of generic endpoint using different types of transport (websocket, SSE, long-poll) for data sources?

**Comment by hhuuggoo** [comment]
no it's not - the general ajax data source will support non-blaze things, we will just subclass it for the blaze stuff

**Comment by matdrapeau** [comment]
@hhuuggoo is it possible to have an example on how it should work?

Also, would it work with websockets?

thanks

**Comment by bryevdv** [comment]
@matdrapeau in very rough terms, I'd imagine something like:
```
source = JSONDataSource("http://foo.bar.com/some/rest/api", mapping = [TBD])
```
open question as to how to specify simple mappings between JSON and columns in a column data source. 

web sockets seems feasible but someone who knows more about it than me will probably have to look into that. :)

**Comment by matdrapeau** [comment]
@bryevdv Is this on python side or js side? Cause I would had thought that we could pull/push values directly on client's browsers ?

**Comment by bryevdv** [comment]
This is how you would easily spell it on the Python side. But it would only be the corresponding JS so de object that pulls data on the client.

**Comment by hhuuggoo** [comment]
Well, I think we can also have a WebsocketDataSource - either way, you control the server where the data is served, if you want to update the ajax one, we could give it a polling interval.  Or you could use the websocket one.

**Comment by matdrapeau** [comment]
@hhuuggoo wondering if I can sneak in and maybe help you there? Do you have a PR somewhere I can take a look? I'm looking into a way to update data in realtime using websockets.

Thanks
