### ISSUE TITLE
Reset orignal plot's size

### ISSUE THREAD

**Issue by imaluengo** [bokeh/bokeh#1683]
Currently the `reset` tool of the plots only resets the point of view and the zoom of the data. But, if you resize the plot the only way of recovering its original size is by refreshing the web (in standard web deployment) or by replotting (in ipython notebook).

Is not really a problem, but it would be nice to be able to resize the plot with the `reset` or other tool.

**Comment by bryevdv** [comment]
This will be done in #3254
