### ISSUE TITLE
examples/plotting/file/image.py not working on IE

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1684]
Example works on chrome and firefox but fails on IE with the attached error message.

![bokeh_image_issue_071](https://cloud.githubusercontent.com/assets/1084690/5705706/a76c261a-9a7b-11e4-912c-6b5136b46bb4.PNG)

**Comment by bryevdv** [comment]
There is nothing to do about this. Browser stack limits are beyond our control. I've updated the example not to be 1000x1000, and that was sufficient to get it working on new enough Windows browsers.
