### ISSUE TITLE
examples/glyphs/widgets_server.py not working on 0.7.1 dev build

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1686]
Getting the following issue:

![bokeh_glyphs_widgets_issue_071](https://cloud.githubusercontent.com/assets/1084690/5705937/34e96984-9a7d-11e4-9619-c554cc304853.PNG)

**Comment by damianavila** [comment]
I can not reproduce it... it is working in linux chromium/firefox in py2 and py3

**Comment by damianavila** [comment]
maybe a win specific issue? it would be weird with that failure...

**Comment by mattpap** [comment]
@fpliger, did you rebuild `bokeh.js` from scratch? The error you see can only happen when `common/base` can't resolve a model.

**Comment by fpliger** [comment]
No...

**Comment by mattpap** [comment]
I tested this on Windows under IE and Chrome and can't reproduce.

**Comment by fpliger** [comment]
Great. This should be related to my local environment... I think we can close this as invalid.
