### ISSUE TITLE
Better reported version for deployed dev docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1692]
Right now it uses whatever the last checked in release version is. At a minimum, set to "dev"

**Comment by bryevdv** [comment]
@damianavila is this part of your current build work?

**Comment by damianavila** [comment]
Nop... I am thinking about this... I would't like to use the python script to change it, it has to be a better way... let's use this issue to think about it...

**Comment by damianavila** [comment]
Closed by #1800
