### ISSUE TITLE
Use GH releases API to create real customized releases 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1693]
Write a script that can be used during the release process (eventually included in automated release process)

Reference: https://developer.github.com/v3/repos/releases/

Goals:
* **don't** have GH auto-generated source tarball assets
* **do** have sdist tarballs
* make release description (`body`) mirror the spinx doc release notes 

ping @lexicalunit

**Comment by damianavila** [comment]
For reference, this is deeply related with #1363

**Comment by bryevdv** [comment]
No one has ever asked about this or even tried to use GH releases so there is no point in spending effort on it.
