### ISSUE TITLE
load_notebook doesn't work with IPython master

### ISSUE THREAD

**Issue by jasongrout** [bokeh/bokeh#1697]
I get `<IPython.config.loader.LazyConfigValue at 0x7fa155bbcc50>` for `get_ipython().config.IPKernelApp.parent_appname` on IPython notebook current master.  This doesn't have the string 'notebook' in it, so the load_notebook test fails, and I have to use `force=True`.

**Comment by damianavila** [comment]
Hello @jasongrout, there is an already opened issue about this: #867.
I will fix this soon, before the Jupyter 3.0 release... thanks for the report!

**Comment by damianavila** [comment]
Let's this be open (not a dupe) because the other issue was a discussion in a more general content... and this is dealing with a specific problem inside that discussion.

**Comment by damianavila** [comment]
This was solved indirectly by 1742, BokehJS is load at __init__, so no need to use load_notebook(force=True) anymore with Jupyter/IPython master...
