### ISSUE TITLE
Displaying RGBA images from (N, M, 3-4) arrays

### ISSUE THREAD

**Issue by imaluengo** [bokeh/bokeh#1699]
This is a suggestion. Currently the API of  `image_rgba` states:

> **bokeh.plotting.image_rgba(*args, ***kwargs)**
> The image_rgba glyph takes each image as a two-dimensional array of RGBA values (encoded as 32-bit integers).
> **Parameters:**
> ...
> **image** (str or 2D array_like of uint32) – value or field names of RGBA image data

This is fine for mathematical plotting, where as the gallery examples show you can create a uint32 2D `(N, M)` array and `view` it as a `(N, M, 4)` uint8 array to assign values easily. However, if used for image processing or to show real images, they usually come in the form of `(N, M, 3-4)` arrays (whenever the alpha channel is included or not depends on the library used to load the image). 

The workaround for plotting the images is really simple, and it would allow `(N, M)` uint32 or `(N, M, 3-4)` uint8 images to be passed as an argument:

```python
if img.ndim > 2: # could also be img.dtype == np.uint8
    if img.shape[2] == 3: # alpha channel not included
        img = np.dstack([img, np.ones(img.shape[:2], np.uint8) * 255])
    img = np.squeeze(img.view(np.uint32))
```

Do you think it might be useful to have the workaround inside the plotting function to allow faster plotting w/o needed to convert the image to uint32 everytime?

Additionally, it could be added support for other data type arrays (like `[0., 1.]` RGB float images).

**Comment by canavandl** [comment]
I agree with @imaluengo. Per matplotlib's docs (http://matplotlib.org/api/image_api.html), "For grayscale images, the return array is MxN. For RGB images, the return value is MxNx3. For RGBA images the return value is MxNx4"... using the image.imread method. It makes sense (to me) for bokeh.plotting.figure.image_rgba to accept those three data structures. I did:

img = matplotlib.image.imread('CIE_1931_Chromaticity_Diagram.png') #returns NxMx4 dtype=float32
img = (img*255).astype(np.uint8)
N, M, _ = img.shape
img = img.view(dtype=np.uint32).reshape((N, M)) #convert image NxM dtype=uint32

Then I could load "img" using bokeh.plotting.figure.image_rgba

**Comment by bryevdv** [comment]
This could make sense in a high level chart possibly, but it is too late to change the lower level APIs.

**Comment by shaperilio** [comment]
I realize this is very old, but I landed here doing bit gymnastics trying to display a color image.

It doesn't seem like things have changed. To display a PyTorch tensor of a color image (in float, 0-1 range) with Bokeh I had to do:

```python
# `im` is a `torch.Tensor` with shape (1, n_channels=3, height, width)

# Create alpha channel of all 1's
alpha = torch.ones_like(im[:, 0:1, :, :])

 # Tack alpha channel on
im = torch.cat([im, alpha], dim=1)

 # Rearrange dims and make into an `ndarray`. Shape is now (height, width, 4)
nd = numpy.array(im.squeeze(dim=0).permute(1, 2, 0).cpu().numpy())
h, w, _ = nd.shape

# Rescale to 0-255
nd = (nd * 255).astype(numpy.uint8) 

# Rearrange data in memory; required because we tacked on `alpha`. Cannot make a uint32 view otherwise.
nd = numpy.ascontiguousarray(nd)

# Reinterpret data for Bokeh's sake.
nd = nd.view(dtype=numpy.uint32).reshape((h, w))
```

(That all thanks to @canavandl's code [above](https://github.com/bokeh/bokeh/issues/1699#issuecomment-88312102).)

I can then display the image just fine with `image_rgba`. But if I want a tooltip to show RGB values, it seems I have no choice but to create auxiliary arrays with the original data: a tooltip of `'@image'` of course just gives me the 32-bit number, and `$color[hex, swatch]:image` gives me `null`.

Am I missing something?

**Comment by bryevdv** [comment]
Can you back out what you want in the hover from the dense RGBA array? Then maybe these days a `CustomJSHover` could be useful. Given a small, self-contained MRE I might be able to experiment, but this discussion should move to the community support  [Discourse site](https://discourse.bokeh.org).

Otherwise, the underlying browser APIs needs dense RGBA arrays, so more or less Bokeh will always need them too. Maybe there would be utility in adding some helper functions around doing up-front (i.e. on the Python side, not the JS side) conversion to dense RGBA arrays. If you have specific ideas, please open a new GitHub discussion.

**Comment by shaperilio** [comment]
> Can you back out what you want in the hover from the dense RGBA array? Then maybe these days a `CustomJSHover` could be useful. Given a small, self-contained MRE I might be able to experiment, but this discussion should move to the community support [Discourse site](https://discourse.bokeh.org).

Thanks for the tip. Yes, I could extract the values from the 32-bit number, but I was hoping I could somehow do some math in the `tooltips` specification. I'll move on to the discussion site; currently experimenting with `image_stack` instead.

**Comment by bryevdv** [comment]
> but I was hoping I could somehow do some math in the tooltips specification. 

Specifying that code is what the `CustomJSHover` is for.
