### ISSUE TITLE
Running bokeh-server in development environment under Windows

### ISSUE THREAD

**Issue by rothnic** [bokeh/bokeh#1702]
See [this](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/gjeJ809iH4E) google groups thread.

Due to the .exe file not existing until the conda package is built, running "bokeh-server" doesn't work if you are working in a conda environment. Instead it finds the bokeh-server.exe in the base Anaconda install.

However, running "python bokeh-server" does work. So, should either add the command to the docs, or somehow have access to the .exe file from the development environment.

**Comment by damianavila** [comment]
I guess the best thing to do now is just document this thing... soon we are going to migrate from the conda convert to use a no-arch architecture and binstar, so I don't not if it makes sense to expend time in something that will change soon... and adding `python` before `bokeh-server` is not a big deal from the user/devel perspective, I think... and finally who develops in win??? (just a joke :stuck_out_tongue_winking_eye:, thanks @rothnic to raise this issue). 
Thoughts?

**Comment by bryevdv** [comment]
This seems like a packaging problem. @ilanschnell do you have any thoughts on this, is there something else we need to be doing to get the Windows conda packages created with the `.exe`?

**Comment by rothnic** [comment]
@damianavila yeah, I know. I have mac personal laptop, but a windows one for work. Then linux/mac/windows at home, so it seems that i never can get consolidated on one. I've tried vagrant, but it has its own cross platform issues. Oh well.

I am about to provide some other fixes for the documentation to support building on windows and some other additions. I can add the note in there while I'm at it.

**Comment by rothnic** [comment]
I was going to merge in the referenced changes on master and test on windows. @damianavila or @bryevdv , do you prefer a merge or rebase for fix/feature branches?

**Comment by damianavila** [comment]
always merge.... only rebased in not public branches :wink:
