### ISSUE TITLE
Extending/Fixing Crossfilter

### ISSUE THREAD

**Issue by rothnic** [bokeh/bokeh#1703]
I was looking at extending the crossfilter functionality, since I've previously built something similar in Matlab.

When working on the current master branch, I noticed that not everything is working how it should. First I started walking through some of the functions under models and added documentation as I understood more about what they were doing. Then, I started fixing some issues that appear to exist due to some change in the interface for the main bokeh functionality.

I wanted to go ahead and reference [this commit](https://github.com/rothnic/bokeh/commit/e338c26adf9b9456f8cd68c43cd66208881c7464) to see if there is someone already working in this area, and see if extending it would be of interest.

### Use Cases
I think there are two major use cases that might be different apps, but overlap somewhat:
* Tableau-like Dashboard creation (create a plot, create another, piece them together with controls)
* Exploratory tool that provides faceting (seems somewhat incompatible with the first use case)

### Features
* More plot types
* More aesthetics to map columns into (color, size, shape, etc)
* "Saving" plots to use in a larger dashboard
* Gracefully handle more columns (big list to scroll through, maybe collapse summary by default)
* Handling multiple data sets (configured to different plots on a dashboard, or combining through simple joins of some kind)

**Comment by damianavila** [comment]
It is nice to see you are working in fixes and documentation of this example... I encourage you to keep going on this one and submit PRs against master as soon as you think you have something consistent to be reviewed... so far, the things I have seen in your branch are really helpful, so...

>  see if extending it would be of interest

For sure...

**Comment by fpliger** [comment]
Yeah, agree with @damianavila thoughts.

@rothnic  On [the linked commit](https://github.com/rothnic/bokeh/commit/e401932ea09e9130461bc5a3097cd4a3c2fbd51e) I see you are using `charts.Scatter`. Have you got something working already? The reason I'm asking is that `charts` implements a very different api from plotting and we have open discussions on how to make it evolve and integrate better with other `bokeh` parts.

**Comment by rothnic** [comment]
When I opened this up in Pycharm I immediately saw some things that were missing. The scatter plot being one of them. I think I looked around and saw some of the refactoring that had occurred.

The crossfilter app appeared to be directly creating a figure, then using a scatter method. Line was the same. Most of the stuff I have fixed already was with the bar charts. There were some things that were just not working due to changes in other bokeh components or pandas.

The place that I ended up stopping was when I found an issue with how scatter was being used. You will see the issue I'm running into in the last image in [this album](http://imgur.com/a/yvmsG). Also included in this album are just some other images of the state of it as is. 

The last image shows that when the x axis is discrete/categorical the scatter plot isn't showing up. I'd expect to see the scatter plot handle plotting the scatter points aligned on the x axis to discrete values, then the y axis would just be the y values. You'd likely want to use a different kind of plot in the case, but it should work.

**Comment by rothnic** [comment]
@fpliger to answer your question, if I remember correctly that isn't being used. I saw the missing reference to the lowercase "scatter", so naively replaced it with charts.Scatter. I'll look more into the newer charts components.

**Comment by bryevdv** [comment]
*Any* help extending and improving the crossfilter would be extremely appreciated. It is an important priority, but there are currently still lots of important priorities. :) Especially though, if you have experience using and designing these kinds of tools, that would be incredibly valuable!

**Comment by fpliger** [comment]
For what concerns including any `chart` IMHO it'd be better to wait for #1574 because those would just behave like plots and should *just work*. Right know it'd require some machinery to make them work...

**Comment by rothnic** [comment]
The way the tool worked that I mentioned I had worked on, was by abstracting the plot from the interface. If you think of something like ggplot, they have a consistent interface to the user, so a gui wrapper around it would be easy to construct. 

I was taking a similar concept and had what I called views as a subclass of a parent data view. Each view must expose its requirements (aes) to the interface, where, each requirement would map to a column. I mocked the core of this up one day and the rest of the work has been on a closed network, so I still need to update this code, but here is a [histogram example wrapping a legacy function](https://github.com/rothnic/mAware/blob/master/plugins/%40histogram/histogram.m) and [a simple scatter example](https://github.com/rothnic/mAware/blob/master/aware/data_views/%40scatter_view/scatter_view.m). 

The constants were there so the interface could know these things about the class before instantiating one, which makes the interface mostly independent of the plots. Each plot would have some aesthetics that would be mapped to columns, then it may have toggle-able, and/or drop down options (not in example code). By exposing this common information, the tool could provide the UI utilities without having to write any code. In the Matlab world, people tend to not think about the user experience, so you have many legacy tools that all require some special manipulation of the data. I was using the views as a wrapper, to adapt between the two paradigms.

I am interested in these higher level chart types, since my intent is to have an easy to use gui for exploring tabular datasets. To start, I plan on fixing it in its current form to learn more about how it is implemented, then am going to look into extending it afterwards.

**Comment by bryevdv** [comment]
@rothnic that sounds like a great plan, let  us know any questions of help we can provide. 

@fpliger I don't agree that the `charts` interface is appropriate for the implementation of the cross filter. `charts` is simplified and schematized with the intent of being very simple and easy for a certain class of users to get the 95% use cases with next to no code. But for a developer, this kind of simplicity is not really the most important thing, and when implementing a complex tool, I think it often makes more sense to use a lower level interface that provides finer control.

**Comment by rothnic** [comment]
My initial look into the charts interface versus the lower level interface is that there appears to be some differences in heritage that would make it difficult to work in the charts with the app, as is. I would prefer to have the plot type abstracted away somewhat from the interface, whether that is via the charts, or some other mechanism.

Here is a quick view of what I was looking at. Since crossfilter's parent class is PlotObject, you get HasProps with it. Since Charts doesn't implement this, crossfilter would have to move away from PlotObject, unless there is a way to embed a ChartObject inside of a PlotObject.

Is there an intent to stick with HasProps for PlotObject, and if so, why does ChartObject branch off before?

![crossfilter](https://cloud.githubusercontent.com/assets/452052/5772345/bc0324fa-9d16-11e4-8e07-d37849654af0.png)

**Comment by mattpap** [comment]
> Is there an intent to stick with HasProps for PlotObject, and if so, why does ChartObject branch off before?

There was an experiment with a different style of APIs in `charts` module. However, this will be changed in future and `charts` will use the properties subsystem (`HasProps`). @fpliger may tell you more about this.

**Comment by rothnic** [comment]
I did a little [sketching of a more comprehensive dashboard framework](https://drive.draw.io/?#G0BwotitHXXmF5alhTNWt4ZjEzSDQ). I did this pretty generically, but do understand there is some of this in bokeh currently. If anyone is interested in brainstorming on it, let me know and I can add you to the edit permissions. Crossfilter is the most like what I had in mind, but it'll probably lead towards nominating some additional widgets.

Some other relevant references:
Recently, I did prototype a kind of dashboard using reactjs and react-grid-layout, containing some simple d3js charts. I recommend [playing around with react-grid-layout's demo](https://strml.github.io/react-grid-layout/examples/0-showcase.html), since it is pretty slick. Their flux architecture also makes a lot of sense from the perspective of rendering the charts on the frontend.

NYC (i think) pydata had a talk on a package that does something similar: [spyre](https://github.com/adamhajari/spyre).

**Comment by damianavila** [comment]
>I did a little sketching of a more comprehensive dashboard framework.

For some reason, I can not access the resource... I get a timeout...

>I recommend playing around with react-grid-layout's demo, since it is pretty slick.

mmm... the is very interesting... I heard things about react, but I did not know about this layout capabilities.

**Comment by fpliger** [comment]
> @fpliger I don't agree that the charts interface is appropriate for the implementation of the cross filter. charts is simplified and schematized with the intent of being very simple and easy for a certain class of users to get the 95% use cases with next to no code. But for a developer, this kind of simplicity is not really the most important thing, and when implementing a complex tool, I think it often makes more sense to use a lower level interface that provides finer control.

I wasn't explicitly proposing `charts` for the implementation of cross filter [or at least this was not my intention]. :wink:   My comment about `charts.Scatter` was mostly derived because I've notice it being used in the commit linked here.

In general I'm not sure if makes sense or not (didn't stop enough to think about it).. probably it will when the first *real* use case arise.. :-)

> Is there an intent to stick with HasProps for PlotObject, and if so, why does ChartObject branch off before?

As @mattpap said and I mentioned briefly before, `charts` interface is going to change [probably] in the next release (see #1574). The main idea is that a `Chart` object will inherit from `Plot` and will use the properties subsystem (`HasProps`). I'm currently working on this and I hope this will somehow land in a brach this week.

**Comment by bryevdv** [comment]
@rothnic I also can't access the `draw.io` document. Can you attach a static image to the ticket? Also ping @pzwang who may have thoughts. Thanks so much (again) for your input and work on this.

**Comment by rothnic** [comment]
I think a lot of what I sketched up is addressed through Widgets (layout and controls) and/or some of the discussion in [BEP3](https://github.com/bokeh/bokeh/issues/1373), after reading all the comments. The thing that I struggled with previously is how to support having a plot, but also turning that potentially into multiple plots through subplotting/faceting. Some of the discussion seems to be on that topic in BEP3 near the bottom. The challenge in matlab is that I gave the charts full reign of an axis, which worked well, but you cannot create a subplot within an axis. So if a chart really is a group of 3 subplots, they need to be operating more at a figure level. I couldn't support that in my app because in Matlab an application is really just a figure. You can't have nested figures.

I think the thing that I settled on for the tool I worked on in the past was that you likely want to be able to create the chart via a regular api. So, if I use some interactive tool to create a chart, then decide I want to automate producing it, you don't want to have to manually write it again. That's why I ended up trying to "wrap" existing plots, or write a plot that could be directly used, then wrap it.

So, I'd lean more towards defining some layer between the interface and the plotting, meaning that I wouldn't choose to use high level or a low level approach. I'd leave that up to whoever writes the wrapper (I call this PlotWidget in the diagram). I think this would make it very easy to adapt a Chart into the interface, but still provide the flexibility to write something custom if desired. The wrapper would handle passing options, column selections, etc through down to a regular plotting function, returning some common plot type.

[Here](http://i.imgur.com/8vf4U4b.png) is an image of the draw.io file.

**Comment by rothnic** [comment]
Two additional notes:
[Here is an album](http://imgur.com/a/DOjfw) of the initial version of the tool I built in Matlab, for some context.

For crossfilter, I've found that after fixing most of it, I still have an issue where the x axis has categorical data, and the y axis is continuous. I traced this through the python code and couldn't see anything obvious, but did find a generic error on the javascript side: 

`Bokeh: could not set initial ranges bokeh.js:16697`

Going to PlotView.prototype.set_initial_range, I see that it performs some checks on xrs. It looks at the DataRange1d and finds that both the start and end are NaN, so it sets good_vals to false. The result is a blank plot.

**Comment by rothnic** [comment]
I'm trying to finish up the documentation on crossfilter and had an issue understanding the following snippet:

```
    @classmethod
    def create(cls, **kwargs):
        obj = cls(**kwargs)
        obj.set_metadata()
        choices = obj.make_plot_choices()
        obj.update_plot_choices(choices)
        obj.set_plot()
        obj.set_input_selector()
        return obj
```
At first glance I wondered why you couldn't perform obj.<whatever> within __init__, since the cls is initialized with kwargs. But doing so, I see that the __init__ is being called multiple times on a page load and create is called once. The second call of init occurs via PlotObject's load_json. It appears to be related to the model-view relationship, and dealing with the python and dom representation. 

So create seems to handle the one time initialization of the props, then init will return an existing instance if available?

**Comment by hhuuggoo** [comment]
yes that's right - the server instantiates an instance of the object in order to trigger all the server side events, so we have to distinguish between one time initialization and regular object creation
