### ISSUE TITLE
reset doesn't reset box select

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#1705]
If I've done a box select and want to "un-select" it seems like "reset/reload" button would be the way to do this, but it doesn't.

**Comment by damianavila** [comment]
Did you tried with ESC? btw, I have to say that I don't remember if we document this somewhere...

**Comment by bryevdv** [comment]
The little "question mark" help button text is out of date. But yes, `<ESC>` should reset the selection.

**Comment by damianavila** [comment]
We need to documenting in the site too... labelling as a doc bug...
