### ISSUE TITLE
"apps" aren't browsable from bokeh server pages

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#1706]
If I've started bokeh-server with an "app" then it would be nice if it were browsable somehow from the server web page.  Instead, I need to know/remember exactly the URL path to the app.

This makes it awkward to explore and demo.

**Comment by damianavila** [comment]
Something like `http://localhost:5006/bokeh/app_name` does not look difficult to remember to me, but I agree that if you have multiple apps and you want to show them at the same time, some kind of *dashboard*, in this case the main server page, could be useful...
@hhuuggoo thoughts?
