### ISSUE TITLE
Can't see any way to compose multiple independent apps into a single bokeh-server instance

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#1707]
This doesn't work:

```bash
bokeh-server --script crossfilter/crossfilter_app.py \
                      --script sliders_applet/sliders_app.py \
                      --script stock_applet/stock_app.py
```

And I don't see how to achieve that end without doing something like `cat`ing those files together and running them as a single script.

This seems like a reasonable sort of thing to do, and would certainly be helpful for bokeh demos.

**Comment by damianavila** [comment]
This comes from @bryevdv, from and old email and it will give you insight about how to run several apps...

```
For now the best way I know to run these is to run separate Bokeh servers. To run these, cd to the example directory listed, run the bokeh-server command, and navigate to the given URL.

* examples/app/crossfilter (localhost:5010/bokeh/crossfilter/)

        bokeh-server --port=5010 --ws-port=5011  --zmqaddr="tcp://127.0.0.1:5610" --backend=memory --script=crossfilter_app.py

* examples/app/sliders_applet (localhost:5020/bokeh/sliders/)

        bokeh-server --port=5020 --ws-port=5021 --backend=memory --zmqaddr="tcp://127.0.0.1:5620" --script=sliders_app.py

* examples/app/stock_applet (localhost:5030/bokeh/stocks/)

        bokeh-server --port=5030 --ws-port=5031 --backend=memory --zmqaddr="tcp://127.0.0.1:5630" --script=stock_app.py

Plan for the future is to be able to start up new applets in an already running server so that running multiple servers on different ports is not necessary.
```

Summary, there is plans to make it work with a running server, but not there yet...

**Comment by bryevdv** [comment]
This is a current problem, for sure.

**Comment by ijstokes** [comment]
Yes, that is exactly what I ended up doing: starting up separate bokeh-server instances in each app directory running on different ports.

**Comment by bryevdv** [comment]
@ijstokes do you have thoughts on how adding multiple scripts might best be spelled? What about adding a new script to a running server?

**Comment by hhuuggoo** [comment]
currently the way to do this is to put all apps in one script - not all the code needs to be there, that one script just needs to import everything else

**Comment by bryevdv** [comment]
I think that's a reasonable start. I can just imagine having completely unrelated apps from different people, and having to make some script to include them seems like artifice. A config file to list apps to run, plus some kind of HUP capability to re-read it seems desirable (and standard practice for servers) too.

**Comment by damianavila** [comment]
@birdsarah can you post here you workaround to do this? Thanks!

**Comment by birdsarah** [comment]
Hi all, I've worked around this in the past by using a config file, but I had to roll my own pieces.

You can see the full implementation here: https://github.com/birdsarah/bokeh-server-heroku/

Here's the gist of it:

config.py
````python
#..... other bits as needed
scripts = [
    'blueprints/sliders_app_hbox.py',
    'blueprints/washmap_app.py',
]
````

Procfile (this was running on heroku)
````
web: gunicorn app:tornado_app -k tornado --log-level=DEBUG --log-file - -b 0.0.0.0:$PORT
````

app.py
````python
from bokeh.server.start import make_tornado

tornado_app = make_tornado(config_file='config.py')
tornado_app.start_threads()
````

(I haven't tested the above, if you look at my `app.py` you'll see it's more complicated as I needed to customize more pieces - like having password protected redis and having bokeh server ping out every ~60s)

hope this helps.
