### ISSUE TITLE
smart axis labels given tick spacing

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#1708]
tick labels are too close (see picture below) so they overlap:

![screenshot 2015-01-15 06 54 10](https://cloud.githubusercontent.com/assets/293525/5756947/8ea9ab98-9c83-11e4-97cf-f07f790558f3.png)

This is part of the `examples/server/selection_update.py` example's side histograms.

**Comment by bryevdv** [comment]
See https://github.com/bokeh/bokeh/issues/1669

**Comment by mattpap** [comment]
Currently poor-man's solution is to use `major_label_orientation`.

**Comment by bryevdv** [comment]
Yes, that is a good workaround for now, thanks for suggesting it @mattpap
