### ISSUE TITLE
Resize tool causes confusion: needs help text

### ISSUE THREAD

**Issue by bkreider** [bokeh/bokeh#1715]
Add help text to the resize tool. 

I just watched Ian give a presentation and search for the corner of the plot to grab to resize.  It's not obvious (except in retrospect) that you can click anywhere to resize.  We've been programmed by thousands of UI windows that resize only happens at the edges.  Maybe a cursor change after clicking the resize tool?

**Comment by bryevdv** [comment]
99% resize tool is going away, it's not really compatible with the other layout work
