### ISSUE TITLE
Help tool: hard/impossible to click "learn more" link

### ISSUE THREAD

**Issue by bkreider** [bokeh/bokeh#1716]
On OSX firefox, it is impossible to click the "Learn More" link.  The help bubble vanishes before my cursor can move over it.  On Chrome I was able to do it about 50% of the time by moving the cursor really fast.  

![screen shot 2015-01-15 at 8 02 55 pm](https://cloud.githubusercontent.com/assets/1699478/5770000/9f3c6aa4-9cf1-11e4-9332-7baa6e8a16d1.png)

**Comment by bryevdv** [comment]
ping @LilaHickey

**Comment by bryevdv** [comment]
fixed at some point:
<img width="411" alt="screen shot 2016-06-27 at 11 09 19 pm" src="https://cloud.githubusercontent.com/assets/1078448/16403570/43eac300-3cbc-11e6-970f-a848c7633d26.png">
