### ISSUE TITLE
documentation: wrong title font property name in user guide

### ISSUE THREAD

**Issue by twoscomplement** [bokeh/bokeh#1717]
The following text can be found at http://bokeh.pydata.org/en/latest/docs/user_guide/objects.html#id3 :

* title — a title to display above the plot. - “title” is also the prefix for a set of Text Properties, so you can set the font for the title with the parameter `text_font`.

That `text_font` should be `title_text_font`

**Comment by bryevdv** [comment]
Thanks for the catch @twoscomplement, would you be interested submitting the PR that fixes this?

**Comment by twoscomplement** [comment]
Sure, I should be able to do that.

**Comment by twoscomplement** [comment]
https://github.com/bokeh/bokeh/pull/1722
