### ISSUE TITLE
Demo idea: 2D FFT toy

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#1719]
Another idea for a cool interactive Numba-based demo:

Use bokeh+numba to allow a user to draw dots (of various shapes/sizes) in 2D Fourier space, and then synthesize the image, like how the following web page shows:

http://qsimaging.com/ccd_noise_interpret_ffts.html

Can also support the upload of any image (file, URL), whose normalized grayscale version is used as the starting point of the FFT, and the user can draw over it or erase parts of it, etc.

**Comment by bryevdv** [comment]
This is a neat idea but we should find some place other than the tracker to collect demo ideas, maybe a wiki page.
