### ISSUE TITLE
documentation: user guide describes unsupported axis locations

### ISSUE THREAD

**Issue by twoscomplement** [bokeh/bokeh#1721]
http://bokeh.pydata.org/en/latest/docs/user_guide/objects.html#axes

> location: where along the cross-dimension to locate this axis: "min", "max", "left", "right", "top", "bottom" or a floating point value

I am unable to set an axis location that is not one of the four values from the Location enum - anything else (including 'min', 'max', or floating point values) yields:

> ValueError: expected an element of either Auto or Enum('above', 'below', 'left', 'right')

Is the documentation wrong? If not, how would one go about offsetting an axis?

**Comment by damianavila** [comment]
>Is the documentation wrong? 

Yes, documentation has to be updated.

>If not, how would one go about offsetting an axis?

It is not implemented yet... It was implementation in a previous version but with the new layout system, this is not the case.

**Comment by damianavila** [comment]
Btw, would you like to submit a PR to fix the doc? :wink:

**Comment by mattpap** [comment]
@damianavila, it's good to check if bokehjs doesn't implement those. If so, it would be better to expose those the API fully to bokeh.

**Comment by bryevdv** [comment]
There is none atm.

**Comment by damianavila** [comment]
>@damianavila, it's good to check if bokehjs doesn't implement those. If so, it would be better to expose those the API fully to bokeh.

I check the bokehjs source code and I did not find any implementation, to be sure I also confirm this with @bryevdv...

**Comment by bryevdv** [comment]
estimate: 1hr
