### ISSUE TITLE
Setting plot_{width,height} doesn't work

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1723]
It looks like bokehjs doesn't listen on change event of those properties, but even enabling listening explicitly doesn't help and `set("plot_width", 1000)` doesn't do anything.

**Comment by mattpap** [comment]
This should be investigated for other properties as well, because "on change" events don't often work.

**Comment by bryevdv** [comment]
Did you forward the event to canvas the canvas? That's actually what has to be updated:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/tool/gestures/resize_tool.coffee#L41

**Comment by hhuuggoo** [comment]
bokehjs should (and probably doesn't) update the canvas when plot_height and width are updated

**Comment by mattpap** [comment]
I was using `Bokeh.Collections('Plot').at(0).set("plot_width", 1000)`.

**Comment by bryevdv** [comment]
There's two issues:
* there needs to be events triggered when `plot_width` and `plot_height` are updated
* those even handlers need to update the Canvas, because that's actually what matters

**Comment by mattpap** [comment]
> bokehjs should (and probably doesn't) update the canvas when plot_height and width are updated

It doesn't listen to change appropriate change evens and doesn't update canvas anyway. I will provide a fix reusing code from `resize_tool`.

**Comment by bryevdv** [comment]
It would be nice (maybe later) to provide a way to either i) update both at once, or Ii) batch events so that it doesn't try to redraw twice

**Comment by bryevdv** [comment]
status: quick investigate, possibly push to 0.9 (for 0.8 at most forward the few properties events)

**Comment by birdsarah** [comment]
Hi @mattpap, I think this is where you wanted me to post about a remaining issue with this.

Using `Bokeh.Collections("Plot").at(3).set("plot_width", 106)`

The issue as I'm currently seeing it. On FF and Chrome. You can resize the image down to:
![wont go smaller](https://cloud.githubusercontent.com/assets/1796208/6184819/7290203c-b31b-11e4-9bc0-c0b9045aabcc.png)

But an attempt to go one point smaller in either width or height will give `Uncaught Error: unsatisfiable constraint`. And, perhaps more annoyingly, will render that plot non responsive to further commands.

The same error occurs with:
* negative number
* decimal number

Perhaps obviously, they do leave the object with the value set so `Bokeh.Collections("Plot").at(3).get("plot_width")` will return 100.22 if you just tried to do that.

On the large side I'm experiencing no issues. They can go as large as they want.

**Comment by bryevdv** [comment]
So, BokehJS uses the Kiwi constraint solver to lay out positions for things on the HTML canvas. What this is saying is that making it smaller would violate some hard constraint. Probably related to `min_border` if I had to guess. As an experiment, you can reduce `min_border` and see if it lets you size even smaller. I'm not sure the constraint should be loosened, however. It is intended to be the **min* border size, and it would not be very useful in that capacity if it can just get ignored. But, we could and should probably handle exceptions from the constraint solver more gracefully than an uncaught exception.

**Comment by birdsarah** [comment]
Agreed, I think this is only about handling the exception gracefully. Same with handling the decimal and negative numbers - which you could easily get if you were mis-calculating a value to resize to.

**Comment by jzybert** [comment]
Was the original issue for this fixed? If so, perhaps I'm having a different yet related issue. I have a Bokeh plot embedded in a Flask Application. On the client side, I have a button that will hide one of my two plots. When clicked, I'd like the still visible plot to increase in size to fill the remaining room (and also shrink when the button is pressed again). When I try editing the style property of the canvas, `document.getElementsByTagName("canvas")[0].style.height = "800px"`, the plot increases in height properly. However, when I begin streaming data into the plot or even just resize my browser, the canvas reverts back to its original size. Is editing the `height` property the correct way to do this or is there some other variable that I need to edit for the canvas to retain its new height? I tried doing a CustomJS callback to edit `plot_height` but those changes don't get reflected in the embedded plots.
