### ISSUE TITLE
Add categorical y axis

### ISSUE THREAD

**Issue by matdrapeau** [bokeh/bokeh#1727]
There is no way to add strings into an additional y axis like this:
```plot.extra_y_ranges = {"tags": FactorRange(factors=['tag1', 'tag2'])}```

This give the error:
```expected an element of Dict(String, Instance(Range1d)), got {'tags': <bokeh.models.ranges.FactorRange object at 0x109e12c90>}```

**Comment by damianavila** [comment]
Fixed in #1733
