### ISSUE TITLE
Add a section about bokeh-scala/bokeh.jl/... to main documentation

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1731]
Currently it's hardly visible that there is ongoing effort making bokeh available to other programming environments than JS/Python.

**Comment by bryevdv** [comment]
estimate: 2hr

task: find a good location

**Comment by bryevdv** [comment]
@mattpap I am going to be working in the docs alot this week, I will take care of this.

**Comment by mattpap** [comment]
OK, I didn't do any work in this issue.

**Comment by bryevdv** [comment]
OK, section added to dev guide. More updates later, closing this one.
