### ISSUE TITLE
push_notebook memory leaks

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1732]
reference: http://stackoverflow.com/questions/28051780/memory-overflows-when-streaming-data-using-bokeh-push-notebook

**Comment by damianavila** [comment]
I have already request info about version in the ref...

**Comment by davidbrochart** [comment]
Python 3.4.2 |Anaconda 2.1.0 (64-bit)| (default, Oct 21 2014, 17:16:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> bokeh.__version__ 
'0.6.2.dev.20141204'

Although "conda install bokeh" gives:
bokeh                     0.7.1                np19py34_0

~$ ipython --version
2.3.1

I tried with Chromium and Firefox and have the same behavior: first the browser's memory footprint increases, and then after a minute it's IPython's turn.

**Comment by damianavila** [comment]
Can you please update bokeh to the latest release and check if still see the failure? Just do `conda update bokeh`...

BTW, for the kernel version, you need to do something like: 
```python
import IPython
print(IPython.sys_info())
```
It could be different from the notebook server version if you are doing some weird stuff in the notebook... I would be probably 2.3.1 too, but please check this out too...

**Comment by davidbrochart** [comment]
Well that's what I was mentioning, it's kind of weird that the Bokeh versions don't match:
```
david@david-OptiPlex-745:~$ conda update bokeh
Fetching package metadata: ..
# All requested packages already installed.
# packages in environment at /home/david/anaconda3:
#
bokeh                     0.7.1                np19py34_0  
david@david-OptiPlex-745:~$ python
Python 3.4.2 |Anaconda 2.1.0 (64-bit)| (default, Oct 21 2014, 17:16:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> bokeh.__version__ 
'0.6.2.dev.20141204'
>>> import IPython
>>> print(IPython.sys_info())
{'commit_hash': '1c0eb68',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/david/anaconda3/lib/python3.4/site-packages/IPython',
 'ipython_version': '2.3.1',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-44-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/home/david/anaconda3/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.4.2 |Anaconda 2.1.0 (64-bit)| (default, Oct 21 2014, '
                '17:16:37) \n'
                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}
```

**Comment by damianavila** [comment]
>Well that's what I was mentioning, it's kind of weird that the Bokeh versions don't match

Yes, that's weird... can you `conda remove` the bokeh package... and try installing again? You can also try to install the latest version in a new conda env and check the issue there... let me know how it goes...

**Comment by mattpap** [comment]
@davidbrochart, can you run `import bokeh; bokeh`? This will tells us where exactly is the dev version of bokeh located.

**Comment by davidbrochart** [comment]
```
david@david-OptiPlex-745:~$ python
Python 3.4.2 |Anaconda 2.1.0 (64-bit)| (default, Oct 21 2014, 17:16:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> bokeh
<module 'bokeh' from '/home/david/anaconda3/lib/python3.4/site-packages/bokeh/__init__.py'>
```

**Comment by mattpap** [comment]
I'm not sure what exactly `conda remove` does, but maybe it gets confused if a package was installed by other means to the same location. I had seen similar issue before in my setup.

I would do `conda remove bokeh` and `rm -rf /home/david/anaconda3/lib/python3.4/site-packages/bokeh`. Then `python -c 'import bokeh'` to test if it doesn't import. If it does, then you can `find` or `slocate` other installations of bokeh. Otherwise `conda install bokeh` and you should have a working installation.

**Comment by davidbrochart** [comment]
No luck removing/reinstalling Bokeh:
```
david@david-OptiPlex-745:~$ conda remove bokeh
Fetching package metadata: ..

Package plan for package removal in environment /home/david/anaconda3:

The following packages will be REMOVED:

    bokeh: 0.7.1-np19py34_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ] |#####################################################################################################################| 100%
david@david-OptiPlex-745:~$ conda install bokeh
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /home/david/anaconda3:

The following NEW packages will be INSTALLED:

    bokeh: 0.7.1-np19py34_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ] |#####################################################################################################################| 100%
david@david-OptiPlex-745:~$ python
Python 3.4.2 |Anaconda 2.1.0 (64-bit)| (default, Oct 21 2014, 17:16:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> bokeh.__version__ 
'0.6.2.dev.20141204'
```

With a fresh Anaconda installation and a ```conda update bokeh```:
```
david@david-OptiPlex-745:~$ /home/david/anaconda3_new/bin/python
Python 3.4.2 |Anaconda 2.1.0 (64-bit)| (default, Oct 21 2014, 17:16:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> bokeh.__version__ 
'0.7.1'
>>> bokeh
<module 'bokeh' from '/home/david/anaconda3_new/lib/python3.4/site-packages/bokeh/__init__.py'>
```
But the memory issue remains.

**Comment by bryevdv** [comment]
OK that is really bizarre, I just tried a fresh install in a py3 env to make sure there was not some obvious packaging hiccup, but it seems to work as expected. Does this problem persist in a new fresh env? (e.g., `conda create -n test bokeh=0.7.1`)  @asmeurer do you have any ideas?

**Comment by bryevdv** [comment]
BTW I would not expect this to be fixed by rev'ing Bokeh versions, the `push_notebook` code has not changed since it was introduced. It's possible, though maybe unlikely, that a newer IPython version would fix things. I think this is a problem on our end, though.

**Comment by davidbrochart** [comment]
But I'm surprised you guys cannot reproduce the problem, I have it on two machines.

**Comment by bryevdv** [comment]
I have not had a chance to try yet. I can believe there could be a problem, the possibility has already been raised that the injected scripts would not get cleaned up.

**Comment by asmeurer** [comment]
Oh wut? Can you add me to the bokeh repo so I can route these emails to my @continuum.io address?

**Comment by damianavila** [comment]
> I have not had a chance to try yet. I can believe there could be a problem, the possibility has already been raised that the injected scripts would not get cleaned up.

Yes, I am not saying there is not a problem... I see a lot of memory taken but never enough to make IPython die... Just asking about the versions to check try to reproduce the exact behaviour...

**Comment by asmeurer** [comment]
Also, I'm not entirely clear what is going on here, but check `conda info -a` for anything that would screw up Python's import path.

**Comment by damianavila** [comment]
>Oh wut? Can you add me to the bokeh repo so I can route these emails to my @continuum.io address?

I have invited you...

**Comment by asmeurer** [comment]
Thank you kindly

**Comment by davidbrochart** [comment]
Now I remember having installed Bokeh with ```pip install bokeh``` when I was looking for the latest release. I thought conda could handle pip as well. Anyways, the problem persists with a fresh Anaconda install...

**Comment by damianavila** [comment]
ok... the memory leak is probably cause because the notebook insert a `<div class="output_area"><div class="prompt"></div><div class="output_subarea output_javascript"></div></div>` elements every time it try to display_javascript. There is not an easy way to fix this... you could use `display.clear_output` to eliminate this output but also eliminate the plot...
We are using the display machinery to update the js and the price to pay here for the easy hack is all these new html elements eating your memory and making your ipynb bigger and bigger. I guess we are achieving a limit on the IPython display machinery... and probably to support a lot of updates, we need to switch to others things, for instance, the bokeh-server.

**Comment by davidbrochart** [comment]
Thanks Damian. I was thinking about using the bokeh-server but couldn't find any code example. Is there any tutorial/documentation about it?

**Comment by damianavila** [comment]
You have some examples about animation with the server here: https://github.com/bokeh/bokeh/blob/master/examples/plotting/notebook/animated.ipynb

Btw... I will keep investigating this issue to see if there is something else we can do...

**Comment by bryevdv** [comment]
@damianavila can we tag the divs with IDs and delete old ones from the DOM (by hand, ourselves) before injecting new ones? This use case (notebook without server) is an important one , and should be made to work one way or another. Alternatively, what about a plugin?

**Comment by damianavila** [comment]
>@damianavila can we tag the divs with IDs and delete old ones from the DOM (by hand, ourselves) before injecting new ones? 

We could eliminate on the flight... but the divs get also stored in the ipynb file... so, at notebook loading, you will have a very poor experience...

>This use case (notebook without server) is an important one , and should be made to work one way or another. 

I agree... but it is also true that is only affecting the performance with a **LOT** of updates...

>Alternatively, what about a plugin?

What do you exactly thinking about with a plugin? You mean a custom Bokeh widget?

**Comment by bryevdv** [comment]
I have no idea. :) I just thought a plugin might offer additional control that couldn't be gotten otherwise, and that that might be useful. For instance, a way to execute JS code or inject scripts that don't get saved in `.ipynb` files.  Perhaps the notebook could use a notion of "transient" published objects, that only exist in running note books?

**Comment by davidbrochart** [comment]
@damianavila That's what I meant when I said that I didn't know if it was supposed to be used that way, basically I am trying to do streaming data visualization without a server, which might not be the right way. On the other hand, even if we don't do a lot of updates, it is kind of dirty under the hood, so maybe it is worth cleaning it...

**Comment by bryevdv** [comment]
Another option is to make starting a server together/with the notebook a transparent action so that users don't have to worry with it. But I really would like to make this technique solid, if it is at all possible to do so.

**Comment by damianavila** [comment]
>I just thought a plugin might offer additional control that couldn't be gotten otherwise, and that that might be useful. For instance, a way to execute JS code or inject scripts that don't get saved in .ipynb files. Perhaps the notebook could use a notion of "transient" published objects, that only exist in running note books?

Widgets could be an option...

>Another option is to make starting a server together/with the notebook a transparent action so that users don't have to worry with it. But I really would like to make this technique solid, if it is at all possible to do so.

That's interesting too... let me think a little bit about this...

**Comment by damianavila** [comment]
>@damianavila That's what I meant when I said that I didn't know if it was supposed to be used that way, basically I am trying to do streaming data visualization without a server, which might not be the right way.

You are using the notebook kernel as a server... probably to do streaming it is better to fall-back in a real server like the bokeh one...

>On the other hand, even if we don't do a lot of updates, it is kind of dirty under the hood, so maybe it is worth cleaning it...

Yes... I agree... the thing is that we are using something which was not developed to be used in that way we used and there is where the problems comes. In any case, we need to find a better solution, I agree...

**Comment by bryevdv** [comment]
I do agree that the best use of `push_notebook` is probably for `interact` style things, not streaming. We should add a `..note::` or `.. warning::` about this to the docs for now.

**Comment by damianavila** [comment]
> I do agree that the best use of push_notebook is probably for interact style things, not streaming. We should add a ..note:: or .. warning:: about this to the docs for now.

I agree... I have opened an issue to do it...

**Comment by ivmi** [comment]
As a temporary solution, you can call `display.clear_output` before calling `push_notebook`.The code for updating data should be in a separate cell, to prevent deleting the actual plot.
```
from IPython.core import display
def update():  
    # update data here
    # ...
    display.clear_output()
    source.push_notebook()
```

**Comment by mrocklin** [comment]
I would like to stream data to a bokeh plot in the notebook.  Is `push_notebook` still the right approach?  Is the `display.clear_output()` solution above a sufficient one?

**Comment by bryevdv** [comment]
It is, but the work in #3207 allows more things to be updated (not just data sources) and also fixes the memory leak. It's not quite done yet, but it should be in `0.11`.
