### ISSUE TITLE
Reference Guide formatting issues

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#1738]
On many Reference Guide pages*, the < ul class="simple" > on these pages overlaps the "fork me on github" banner.

![screen shot 2015-01-21 at 11 40 38 am](https://cloud.githubusercontent.com/assets/1417520/5841426/771d1742-a162-11e4-9471-f36481bcdaa3.png)

This is because there is no < h1 > tag above the < ul > to offset it, the way there is on most other pages.

![screen shot 2015-01-21 at 11 44 01 am](https://cloud.githubusercontent.com/assets/1417520/5841533/35ddd61c-a163-11e4-95dd-5eaa4efa6969.png)

*http://bokeh.pydata.org/en/dev/docs/reference/properties.html
http://bokeh.pydata.org/en/dev/docs/reference/plot_objects.html
http://bokeh.pydata.org/en/dev/docs/reference/models.html
http://bokeh.pydata.org/en/dev/docs/reference/compat.html
http://bokeh.pydata.org/en/dev/docs/reference/rest_api.html

**Comment by bryevdv** [comment]
I would ideally like to solve this by removing the "Fork me on Github" banner form all pages except the top level `index.html`

**Comment by damianavila** [comment]
>I would ideally like to solve this by removing the "Fork me on Github" banner form all pages except the top level index.html

I agree...

**Comment by bryevdv** [comment]
fixed in accidental push to master

**Comment by damianavila** [comment]
So, let's close it... and :beers: for everyone :stuck_out_tongue_winking_eye:
