### ISSUE TITLE
Selecting rows on DataTable doesn't trigger `selected` callback on the data source

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1748]

**Comment by bryevdv** [comment]
status for 0.8: investigate, possibly push off

**Comment by bryevdv** [comment]
Possibly fixed, needs testing.

**Comment by bryevdv** [comment]
@mattpap can you provide more context or a way to test?

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mattpap** [comment]
The initial problem here (and in many other places) is that we use `model.set(...)` instead of `model.save()`. However, changing this makes bokeh go into in an infinite loop.

**Comment by mattpap** [comment]
This needs more investigation, moving to long-term.

**Comment by bryevdv** [comment]
This seems to have been fixed at some point: 
<img width="486" alt="screen shot 2016-12-15 at 8 06 14 pm" src="https://cloud.githubusercontent.com/assets/1078448/21249198/fca0ac68-c301-11e6-8a3e-1b5b2b41f853.png">

clicking the row selected accordingly. 

Please re-open if I am somehow mistaken.
