### ISSUE TITLE
`to_bokeh` ignores alpha

### ISSUE THREAD

**Issue by sotte** [bokeh/bokeh#1754]
Hey,

I'm using seaborn's `tsplot` a lot but sadly the `alpha` values are being ignored when converting with `to_bokeh`. See the example:

![bokeh_problem_seaborn_orig](https://cloud.githubusercontent.com/assets/79138/5878556/15e07f92-a328-11e4-857e-142c089c5fb8.png)
![bokeh_problem_seaborn_to_bokeh](https://cloud.githubusercontent.com/assets/79138/5878557/15e082bc-a328-11e4-8b3a-8285f09ffc6c.png)

I'm using bokeh 0.7.1.

**Comment by damianavila** [comment]
I will explore the issue, maybe it is something we need to expose in out BokehRenderer implementation... thanks for the report.

**Comment by sotte** [comment]
Thanks for the quick response. Here is a minimal example.

```python
import seaborn as sns
import bokeh.plotting as bk
from bokeh.mpl import to_bokeh
gammas = sns.load_dataset("gammas")
fig, ax = plt.subplots()
sns.tsplot(gammas, "timepoint", "subject", "ROI", "BOLD signal", ax=ax)
bk.show(to_bokeh(fig))
```

**Comment by sotte** [comment]
Any updates on this?

**Comment by damianavila** [comment]
not yet, but I changed the milestone to 0.8.2 to tackle on this soon...
