### ISSUE TITLE
importing bokeh breaks standard python if ipython also installed

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1761]
[reported by @shughes-uk ] Recent ipython `load_notebook` PR does unexpected things in the standard interpreter if ipython happens to be installed

    bryan@laptop  ~/work/bokeh/bokehjs/src/coffee/renderer/guide $ python
    Python 3.4.2 |Anaconda 2.1.0 (x86_64)| (default, Oct 21 2014, 17:42:20) 
    [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import bokeh
    In :

**Comment by bryevdv** [comment]
Given that there is "no way to determine if you are in the notebook" there can't be any way to determine you are *not* in a notebook. Not sure if there is any solution but to revert.

**Comment by shughes-uk** [comment]
Also breaks the tests if you run them with the standard interpreter, most of them simply don't run so 'pass', which is probably why this wasn't immediately picked up by the unittests.

**Comment by damianavila** [comment]
I think the problem is not if we are (or not) inside a notebook, the problem is detecting if we are (or not) inside IPython... and that's easy to check, see #176 and let me know if that PR fix the issue...
