### ISSUE TITLE
Move/rename examples.html

### ISSUE THREAD

**Issue by Jawabiscuit** [bokeh/bokeh#1766]
In a newly forked repo, examples.html displays errors in Chrome Version 41.0.2272.16 beta-m (64-bit).

system os info:

Name: Microsoft Windows 7 Extreme Edition R1 - x64 (Service Pack 1)
Version: 6.1.7601
ServicePackMajorVersion: 1
ServicePackMinorVersion: 0
Manufacturer: Microsoft Corporation
BuildType: Multiprocessor Free
CodeSet: 1252
CountryCode: 1
Organization:
RegisteredUser: Jonas
NumberOfUsers: 3
MaxNumberOfProcesses: -1
MaxProcessMemorySize: 8TB
VisibleMemorySize: 7.98GB (Remaining 1.68GB)
VirtualMemorySize: 15.95GB (Remaining 8.11GB)
FreeSpaceInPagingFiles: 7.54GB
SystemDrive: C:
WindowsDirectory: C:\Windows
SystemDirectory: C:\Windows\system32
Registry CurrentSize/MaximumSize: 308MB/2GB

**Comment by bryevdv** [comment]
Hi @Jawabiscuit, sorry for the confusion. That file is actually part of our continuous integration testing setup, and not meant for users to run. It should probably be moved/renamed. I'm going to update the title to reflect that and mark it as a task. All of the scripts in the subdirectories under `examples` either auto-open a browser, print connection information when run, or (a few) have a README if the usage is more involved.

**Comment by bryevdv** [comment]
Users very reasonably assume it is a useful file for them to look at, and not a little piece of our CI plumbing.

**Comment by bryevdv** [comment]
@Jawabiscuit also, thanks for pointing this out!

**Comment by Jawabiscuit** [comment]
Ok! Sounds good :+1:

**Comment by bryevdv** [comment]
Came up again with another person just today. Really, all of the files at the top level of `examples` are part of our testing infrastructure and should be moved,

**Comment by damianavila** [comment]
I agree...

**Comment by damianavila** [comment]
Taking an stab on it now at #1778...
