### ISSUE TITLE
Enable tabbed faceting on Crossfilter

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1768]
Implement tabbed faceting option for cross filter.

**Comment by bryevdv** [comment]
@rothnic is this something you would be interested in helping with?

**Comment by rothnic** [comment]
Sure, I could take a look at it, though I'd need a pointer into the
direction of the intended feature. I'm familiar with grammar of graphics
and ggplot, but not sure what exactly that is referring to.

On Tue, Jan 27, 2015 at 12:28 PM, Bryan Van de Ven <notifications@github.com

**Comment by hhuuggoo** [comment]
in the crossfilter, youcan facet on 2 fields, in which case you get a grid of plots

if we facet on 3, then we can have N tabs of scatter plot grids, where each tab is facetting on that 3rd dimension

**Comment by bryevdv** [comment]
@hhuuggoo just beat me to it. :) I will only just point you at this example:

https://github.com/bokeh/bokeh/blob/master/examples/glyphs/glyphs.py#L74

You can run it to see the tabbed panel in action, and the particular line I linked has the `Tab` creation below.

**Comment by rothnic** [comment]
Ah, yeah wasn't sure if tab was related to literal UI elements or some
other concept. I can take a look at it.

**Comment by bryevdv** [comment]
BTW I would think ideally we could have any combination of `facet_x`, `facet_y` and `facet_tab` but if it's easier to start out only allowing tab facets as a third dimension, that is fine too. Thanks again @rothnic! 

BTW we are going to get some help from a designer to sharpen up the visual appearance of the cross filter in the next few weeks as well. If you have any ideas or input please let me know.

**Comment by bryevdv** [comment]
Thanks @rothnic !
