### ISSUE TITLE
Sphinx extension error

### ISSUE THREAD

**Issue by Jawabiscuit** [bokeh/bokeh#1769]
Again, this is a newly forked repo. This error comes up when trying to run `make all`. Thanks!

Python 2.7.5
docutils (0.12)
Sphinx (1.2.3)
sphinx-bootstrap-theme (0.4.5)
sphinxcontrib-httpdomain (1.3.0)
sphinxcontrib-napoleon (0.2.9)
seaborn (0.5.1)

L:\dev\bokeh\sphinx>make all
Making output directory...
Running Sphinx v1.2.3

Extension error:
Could not import extension bokeh.sphinxext.bokeh_autodoc (exception: No module n
amed sphinxext.bokeh_autodoc)

**Comment by bryevdv** [comment]
That was just merged a few hours ago. I thought perhaps the package got left out of `setup.py` but it appears to be correct:

https://github.com/bokeh/bokeh/blob/master/setup.py#L453

Also the module in question is in the right place:

https://github.com/bokeh/bokeh/tree/master/bokeh/sphinxext

Can you do a few things:
* report `bokeh.__version__` 
* let us know how you installed, before trying to build the docs
* compare your local checkout to the links on master above

**Comment by bryevdv** [comment]
@Jawabiscuit did you have any chance to check the things mentioned above?

**Comment by bryevdv** [comment]
Have not been able to reproduce. I think this was an transient problem and I suspect a new clone or git pull would have everything resolved. It he issue persists, please re-open with the above requested info.
