### ISSUE TITLE
compound glyphs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#177]
Seems like this would be useful for making combining lines and arrowhead simpler. Also for line plots that also have markers, if the legend asks a compound glyph (for the lines and markers together) to render, then it will correctly get both the line and the marker in the legend.

**Comment by birdsarah** [comment]
Just had another desire for a compound glyph after thinking about #3206.

I want to make a box with some text (for example) and then when I hover/select the box, then the styling for all the things is updated so they're acting as one with respect to hit testing.

**Comment by bryevdv** [comment]
Yes I have also been thinking about this wrt annotations. I want to do some preliminary work to line up the JS and python project structures before embarking on some things, but reference-able "anchor points" for glyphs would be useful in many areas.

**Comment by bryevdv** [comment]
Arrows/error bars are implemented, there's not really enough left here to be actionable.

**Comment by jasonsross** [comment]
could someone point me to where arrows have been implemented? I see arrow annotations, but those don't seem like robust plotting tools as opposed just putting an arrowhead line_cap on segments allowing quiver plots. Right now you have what you call a quiver plot, but how is it quiver if they are not arrows?

**Comment by bryevdv** [comment]
Only arrow annotations have been implemented. As I said the original issue was never detailed or specific enough to implement anything general. It's something we could consider if someone is interested enough to develop a fully fleshed out proposal.

**Comment by bryevdv** [comment]
>  Do you just mean you want a clear explanation of the request or a fully fleshed out implementation?

Not implementation, but things like:

* clear and specific requirements and goals (definition of "success")
* brief discussion about possible implementation approaches or any pitfalls
* concrete API suggestions 
* complete examples of usage that would be expected to work when the feature is done
