### ISSUE TITLE
[Feature Request] Selectively show glyphs depending on zoom level

### ISSUE THREAD

**Issue by andrewguy** [bokeh/bokeh#1772]
It would be useful to have the ability to selectively render/show glyphs depending on the zoom level.

As an example, when plotting data relating to a biological sequence (DNA, RNA or protein), it is useful to be able to inspect the underlying sequence.  The position in the sequence is usually plotted on the x-axis, and the corresponding sequence (ie. ...ATTAGTAA...) would then be shown just above the x-axis. This can be implemented using text glyphs.  However, when zoomed out, this text blurs together and becomes unreadable.  Rendering the text glyphs only when the user reaches a certain level of zoom would be a lot nicer aesthetically (and probably more responsive).

I imagine there would be other uses for this feature as well.

**Comment by bryevdv** [comment]
@andrewguy Thanks for adding this feature request. Do you have any thoughts on how you might like to be able to spell this? (Or how similar functionality is spelled in other systems?)

**Comment by andrewguy** [comment]
I imagine you would probably add this as a property of any glyph.

You might spell this as:

    p.text(text="A", x=0, y=0, show_with_xzoom=[lower_bound,upper_bound])
where lower_bound and upper_bound define the zoom levels between which to show your glyph.  Defaults would be `[0,inf]` I imagine.

Also, for the sake of aesthetics, maybe an option to fade in - so varying alpha over a small range?  Not essential.  I imagine this might look like:

    p.text(text="A", x=0, y=0, show_with_xzoom=[fade_in,lower_bound,upper_bound, fade_out])

You would also have a similar property called `show_with_yzoom` if you are interested in zoom along the y-axis.

There may be a better (more consistent) way of dealing with this though.  Not sure how the zoom works below the covers - these are just my thoughts from a user perspective.

Many thanks!

**Comment by bryevdv** [comment]
This kind of thing can now be done in a variety of ways:

* with CustomJS range callbacks
* with Bokeh server app callbacks
* with DataShader

I'm going to close this as I don't think adding more interface would add anything, and I also think it would be less flexible than any of the programmatic approaches as well.
