### ISSUE TITLE
Using bokeh keyword in host url affect Config.prefix value

### ISSUE THREAD

**Issue by alishir** [bokeh/bokeh#1775]
If bokeh-server host name contains `bokeh` keyword, value of `Config.prefix` variable in `bokeh.js` is not the expected prefix.
For example if bokeh-server host name is `http://bokeh-testserver.com`, the value of `Config.prefix` will be `http://` instead of `http://bokeh-testserver.com`.

**Comment by damianavila** [comment]
Probably this autoclose when you merge the proposed fix in your fork... am I right?

**Comment by alishir** [comment]
I'm not sure, I removed texts that trigger autocolose procedure from comment message.

**Comment by hhuuggoo** [comment]
Is this necessary?  bokehjs should only need the proper prefix, as the host url should match whatever is serving the page.  currently Config.prefix should pull values from url_prefix setting

**Comment by alishir** [comment]
Today I hosted bokeh server on openshift and my application name was
"bokeh", so the url of application address seems like "
bokeh-username.rhcloud.com".

The bokeh hosted successfully but when I want to view plots, I got an error
in javascript console.
The error was about problem in retrieving `http://bokeh/wsurl`, I found the
cause of the problem is `Config.prefix` value.
By setting this value manually all things work fine. After that I dig
deeper and found that when `bokeh.js` try to find `prefix` it looking for
`/bokeh` substring in url and the bokeh hosted at `
http://bokeh-username.rhcloud.com` and it set prefix to `http://` instead
of `http://bokeh-username.rhcloud.com/`.

**Comment by hhuuggoo** [comment]
Ah!  sorry - I think what i described maybe is not implemented yet. Anyways, my comment is then that we should not pull the prefix from host url, but instead pass the prefix from url_prefix.  In your case, url_prefix is empty, and Config.prefix will then just be "/" which means it should work.  So that is the change I would make.  Does that make sense?

**Comment by alishir** [comment]
In the following code block, `Config.prefix` set based on index of `/bokeh` string in `url`, and I think it is independent of `url_prefix`, am I right?

```javascript
    if (url.indexOf('/bokeh') > 0) {
      Config.prefix = url.slice(0, url.indexOf('/bokeh')) + "/";
    } else {
      Config.prefix = '/';
    }
```

Also I should mention that today is the second day that I heard `bokeh` name and it is my first experience with `bokeh`.
Also I tested the bokeh-server on openshift with setting `--url-prefix` but it doesn't work.

**Comment by bryevdv** [comment]
@alishir @hhuuggoo thanks for having this discussion and sorting this out

**Comment by alishir** [comment]
@bryevdv I hope this little improvement helps the bokeh ;)

**Comment by alishir** [comment]
Hi,

I&#39;d like to include you in my network to share updates and stay in touch.

- Ali

Confirm that you know Ali: https://www.linkedin.com/e/v2?e=-sx7w1p-i8yq8l1n-5a&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=QK50KmJn&amp;invitationID=5998144665826664448


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-sx7w1p-i8yq8l1n-5a&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQGulollGtjFlQAAAUz2w2vSvDXkiNjGbRGeoVjbsmWexbXm8Uv50VVf_C9OnKVf9_Zv5ZwVe2sTt2xSIzfrDon5DRrxL_Tf1rB0HBXKGm5hxUzODi-Mu8S-g63CayWvCzky-blKl2YdAMWvwjrySFpPKyMusfBvPvCCAdAGR0hBrJ8ocbrYPK_gyhPu_2tkzlai&amp;eid=-sx7w1p-i8yq8l1n-5a Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-sx7w1p-i8yq8l1n-5a&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by damianavila** [comment]
@alishir, I think you were spammed and now this last message is being pasted in multiple issues.

**Comment by alishir** [comment]
Ali Shirvani would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Ud3gQdzoSczwRdzoQd34UejARfkh9rCZFt65QqnpKqipKiCRbc3lbkjRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4CsPgJqjxVtD8PemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683744718849_500&markAsRead=

View Ali Shirvani&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3sQd38TdPgNcjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCtD1KfngCsPgJqjxVtD8PemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683744718849_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mkNdS4OdjcMpmcVdz5xczASp69xc6kMcj4Mc30Mc30MpCcOemgSdCoTpm8Ud65BozcMcz0McP4Op38RpC4VdzATczgVpjpAdCpydjsOe6hBpj0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zwQd3gSdzoOe3kSdzgQcjwVejkZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCsPgJqjxVtD8PemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683744718849_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1Pd2RFe7BSszcVqiRMcnsTu7cJfmhFpip4pQZLtBpLolkSpmlai7tDcP9Es4RQp3t3ukgJtT9Jkz4Vr6tbbnFoq6sUbj1oj4Bhd5xzk4NVqlsNrTx4oA58pPBHok8UtQN5tQdFs7FaoChCjT99pDhfd6ZihTxduCRJtRZic58Orj5Wu5hVhj5QelFLgBFFc6wSmBhIpRkQqP52smVar64SsnpxikZKhCFTsyRDbnhLkRl5gBFDmAR4mlpMrQ5hk79HlC9BuDEPlAEMlk51gmtIunthilsOgktghB51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCsPgJqjxVtD8PemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5998144683744718849_500&amp;markAsRead=This email was intended for bokeh/bokeh. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CsPgJqjxVtD8PemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683744718849_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by alishir** [comment]
Ali Shirvani would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Ud3gQdzoSczwRdzoQd34UejARfkh9rCZFt65QqnpKqipKiCRbc3lbkjRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9zoJumBPtD9AemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683744718849_500&markAsRead=

View Ali Shirvani&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3sQd38TdPgNcjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DpMrzRQ9zoJumBPtD9AemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683744718849_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBpj4Toj8RcP1BoPAScm4OejpAoC4Mpj0Ncj0Mc30Mc31CoP8Vp3oSpztBozwQomlycP0Oc30Pcj9AczlCojASejsOd3BBdCgSpC8RdP8Up6lBc30Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACe3gQd3oSdz8UdjoSd3gNe3AVdjRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9zoJumBPtD9AemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683744718849_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=dyRVqndSsCgVqiRMcnsTu7cJfmhFpiphrD1IoTcOtQFgilx8k6tfjjkRiB1RkSlNcCRlimt9jQhRgmdKozlxhSkJklhflRhLsSdLsz9hk5cSlngUoRBodnoNr5lzhPxdu5tQpTlvi5Fgt5Zgr495jn9Vckt4ckJyrlxOrStxdlhgs5hCpD9zunFLe4tUgTtVjRdSrmkQmjwPt6tIuBhqgmROqnFRej5zd6wVgjhGgSwPdkBNhTlysiQOdnoPmBp1j6t5ijtygTkMlk51gl5Dljp6gl1MiQBDhR51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9zoJumBPtD9AemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5998144683744718849_500&amp;markAsRead=This email was intended for bokeh/bokeh. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9zoJumBPtD9AemAJs35TdTxPbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683744718849_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by damianavila** [comment]
spam deleted again... if this keep happening I will lock the thread
