### ISSUE TITLE
[task] Update ipython notebooks

### ISSUE THREAD

**Issue by cloudformdesign** [bokeh/bokeh#1782]
I am starting the process of updating all the ipython notebooks in the examples folder to fit with the new syntax (using figures rather than line, scatter, etc).

I just wanted to create this issue to let you know, I will put my pull request link here and let you know when I am done.

Update: most of these examples do not work out of the box with bokeh 7.1. Kind of bad examples, don-cha-think! :P  Some of them must have even used an older version of pandas, because the csv was loading all-kinda-weird.

**Comment by cloudformdesign** [comment]
I'm trying to get the boxplot to work, and it isn't working at all. I finally did the following:
```
cats = list(range(6))  # this is what I added
f.segment(cats, upper.score, cats, q3.score, x_range=cats, 
        line_width=2, line_color="black")
f.segment(cats, lower.score, cats, q1.score, x_range=cats,
        line_width=2, line_color="black")
```

And now everything works, although without labels. How do I do this with labels?

**Comment by cloudformdesign** [comment]
Ok, here is the first set of changes:
https://github.com/bokeh/bokeh/pull/1783

I am having a lot of problems with the `animated` example in particular. I take it that glyphs can be found in `bokeh.models.glyphs.Glyph` -- but I'm not sure where you get the rest of the machinery to deal with this. I would also be interested in having the actual ipython graph show the animation -- is this possible? Please let me know!

**Comment by cloudformdesign** [comment]
also, I have been removing the `hold()` function from everything... what the heck did/does that do?

**Comment by damianavila** [comment]
Sorry... but in master the examples are updated... did you pull master before going into the notebook???

**Comment by bryevdv** [comment]
Hi @cloudformdesign There was a round of deprecations and some old functions were finally just removed. As @damianavila mentioned, the examples in master should be updated to match the new API. Are you running the examples from a GH checkout or from the ones that were shipped with the package? Perhaps there was a packaging glitch.

**Comment by bryevdv** [comment]
Also to answer your question, `hold()` was part of the old Matlab style stateful api. Basically to add multiple renderers on a plot you would call `hold()` and that would cause any new renderers to be added to the current plot.

**Comment by bryevdv** [comment]
@cloudformdesign I am not sure I understand the question about labeling. You can create categorical ranges, where the axis is comprised of named categories (or factors, in other terminology). In the boxplot example, for simplicity, the categories names are just single letters. You can see the plot here:

http://bokeh.pydata.org/en/latest/docs/gallery/boxplot.html

Legends are annotations that label individual glyphs, so if you for instance you had three lines, you could have a legend that labels each line. I had not thought about a legend on a box plot. Typically you see the categories labeled on the axis (as seen in the example). Can you sketch out what you would want to see in a legend for a boxplot?

**Comment by cloudformdesign** [comment]
you are totally right. I could have sworn I pulled first, but it looks like everything is up to date. Silly me...

Thanks for the clarifications! Those are helpful.

**Comment by bryevdv** [comment]
@cloudformdesign np! :) and thanks for opening a PR, we would love to have more (for example, docs, fixes or anything else!)
