### ISSUE TITLE
automatically fill masked arrays when encoding

### ISSUE THREAD

**Issue by PBrockmann** [bokeh/bokeh#1784]
Could not resist to try cartographic mapping with bokeh...

I have tried to plot a spatial map (lon,lat) with use of plt.image and plt.line to plot continent borders.
Despite 2 problems, it is really promissing and having all this interactivity from the plot itself makes me really enthousiastic.

Attached 2 problems related to this early try:
1) plt.line does not handled missing points 
2) plt.image does not have a modulo feature (I put another issue on that point).

![map_bokeh](https://cloud.githubusercontent.com/assets/5402758/5961731/fe131d64-a7de-11e4-8076-2b69b022517b.png)

**Comment by bryevdv** [comment]
Hi @PBrockmann thanks for the report! During serialization, bokeh encodes missing data as `NaN` values. I can't say I am thrilled about that but I am also not sure what an alternative would be. So, it's probably possible to make the Bokeh JSON encoder smart enough to do this automatically when there are NumPy masked arrays. In the mean time, you could try converting to a regular array with `NaN`s for missing data, and missing points should be handled correctly (but let us know if there is any problem).

I'm not exactly sure what the "modulo feature" is so I will wait for the other issue to comment.

**Comment by PBrockmann** [comment]
Indeed, I can handle this with 2 lines of numpy
```
np.ma.set_fill_value(myVar, np.nan)    # Change fill_value to Nan
myVar = myVar.filled()      # Masked values filled
```
![bokeh_map](https://cloud.githubusercontent.com/assets/5402758/5967523/20489e20-a80e-11e4-8dfe-e298bae4aedc.png)

And finally it looks nice. This try can be tested from
http://nbviewer.ipython.org/gist/PBrockmann/a6302573276ddd49a4c3

**Comment by bryevdv** [comment]
I'm glad that works! I am going to re-open this as the issue to add that automatically in our encode.

**Comment by almarklein** [comment]
Related: the current behavior in the presence of inf and -inf values is to ignore these, but other than with nans, there is no gap. Is this intentional?

![index](https://cloud.githubusercontent.com/assets/3015475/6288061/ae84414e-b916-11e4-8e6f-5a3b081a069d.png)

**Comment by bryevdv** [comment]
Not intentional. What do other systems do with inf

**Comment by almarklein** [comment]
In visvis we decided to handle inf and nan equally. I will do some research ...

**Comment by almarklein** [comment]
Matplotlib also ignored inf (like nan). From what I can find, so does Matlab. 

Do you want me to make Bokeh behave the same? If so, I see two options: 1) in the encoder we translate inf/-inf to nan; 2) in bokehjs the inf values must be handled correctly. I think the latter makes more sense.

**Comment by bryevdv** [comment]
I also prefer the latter. The question is how to encode it. JSON has no "inf" unless I am mistaken.

**Comment by almarklein** [comment]
Neither is nan :)  but apparently they're commonly accepted: http://stackoverflow.com/a/6602204/2271927

Also, we already send `Infinity` and `-Infinity` in the encoder:
https://github.com/bokeh/bokeh/blob/master/bokeh/protocol.py#L62

**Comment by damianavila** [comment]
>JSON has no "inf" unless I am mistaken.

You are right, it is not in the specification...

**Comment by damianavila** [comment]
here they are two ways to deal with this:

http://stackoverflow.com/a/13582033/2785603

**Comment by almarklein** [comment]
My point is that it seems we already send both `NaN` and `Infinity` over JSON.

**Comment by damianavila** [comment]
>My point is that it seems we already send both NaN and Infinity over JSON.

Then I guess we need to handle them correctly on the JS side...

**Comment by almarklein** [comment]
Done. Apparently, the Infinity values were just passed to `ctx.lineTo()` which dealt with it (at least on FF) by linear interpolation.
