### ISSUE TITLE
Support periodic/wrapped ranges

### ISSUE THREAD

**Issue by PBrockmann** [bokeh/bokeh#1785]
Does it make sens to implement a modulo feature to handle topological wrapping along an axis ?
In another words, I would like to pan over the image but when some axis limit is reached get the start of the image.
It is usually called modulo axis or wrapping.

Attached a mapping try with use of  plt.image and plt.line to represent a spatial map (simple cartesian map).
![map_bokeh](https://cloud.githubusercontent.com/assets/5402758/5961908/1ad10bae-a7e0-11e4-8b94-372ebbbf4de1.png)

**Comment by bryevdv** [comment]
Ah, yes it absolutely makes sense. What is needed is a new mapper type (or an extension to the current linear mapper) to handle this use-case.

**Comment by PBrockmann** [comment]
This try can be tested from
http://nbviewer.ipython.org/gist/PBrockmann/a6302573276ddd49a4c3

**Comment by PBrockmann** [comment]
Any news about this wrapping feature ?
By the way, the GeoViews project (http://geo.holoviews.org/Working_with_Bokeh.html) could also benefit from it.

**Comment by bryevdv** [comment]
@PBrockmann Sorry, no there is not. There are unfortunately way more tasks than people to work on them, currently.

**Comment by bryevdv** [comment]
Given that there has not been any other interest expressed in this in nearly five years, I am going to close. If someone (e.g. @philippjfr or @jlstevens from GeoViews) wants to commit to working on this and thinks it would be valuable downstream, we can certainly re-open.

**Comment by philippjfr** [comment]
Would be a nice feature to have, but I can indeed reopen if I ever get around to it.

**Comment by bryevdv** [comment]
This came up on they discourse: https://discourse.bokeh.org/t/how-to-wrap-glyphs-in-a-tile-map-centred-on-asia/7787

@brendancol @tcmetzger is this part of the R4 proposal BTW?
