### ISSUE TITLE
Build on Travis ideas

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1788]
We have mainly two possibilities:

* Add the build job to the current run:
  * PRO: easy and quick
  * CONS: every run in too much long make it impracticable

* Separate TravisCI job:
  * PRO: it does not interfere with the test job, I will set up only to build on master merged (not PRs or branches)
  * CONS: we need to sync the main repo and the "build" one. We can push to both simultaneously, but I can not ask to remember to do that by hand... so we can setup a gitconfig file (to push to both remotes) and ask people (us, but eventually everyone who want to contribute) to install it...

Maybe we have another possibility and I am not seeing it... thoughts?

@mattpap @bryevdv

**Comment by damianavila** [comment]
I have another idea... because certainly I am not sure if building in each commit is necessary, mainly because we are not exposing all these packages to the public... and because it takes a lot of time to do it... I don't think to build en each merge is reasonable... so what if:

I set up a Separate TravisCI job but is the same way describe above but without any gitconfig... so now we decide when to build the package just pushing to the mirror repo... Then all the build process is automated but we have a narrow control of which thing we build to make available to our user. When we decide something is nice to build and spread we just do `git push build master`, where build is the remote "mirror" repo with all the build process automated :wink:. How does it sound?

**Comment by bryevdv** [comment]
+10

**Comment by bryevdv** [comment]
BTW does this mean if we tag dev build with reasonable versions for the tag, that the builds would just get that as the version automatically?

**Comment by bryevdv** [comment]
If that's true, then +100

**Comment by damianavila** [comment]
>BTW does this mean if we tag dev build with reasonable versions for the tag

define reasonable...

>that the builds would just get that as the version automatically?

if we tag, the build has to get the tag as the version, the same way we do in the real release process, it probably needs some little change to support "dev" in the tag (right now we support "rc" in the `get_bump_version.py` script.") 

>That is, would it always be that case that tag == version with no extra work, processing or fudging?

1) `git checkout -b dev_br`
2) `python version_update.py 0.7.2-dev.xxx`
3) `git add .`
4) `git commit -m "New devel build xxx."
5) `git tag -a 0.7.2-dev.xxx`.
6) `git push build --tags`
7) `git push build dev_br:master`

I have to check all these steps but in this case (I am guessing it is in this way) we would never pollute the main repo, just pushing the tags to the "build" remote, and getting the builds with the proper version: in this case 0.7.2-dev.xxx

**Comment by bryevdv** [comment]
That would be brilliant

**Comment by damianavila** [comment]
>That would be brilliant.

OK, I will follow that path...

>Edit: by reasonable versions I mean properly ordered, that a later dev build is always "newer" than an earlier one.

OK, probably using a TRAVIS counter as your proposed before in some other discussion

>BTW conda does not allow dashes in version afaik.

I will keep that in mind...

**Comment by bryevdv** [comment]
Another option is to have a "counter" file in the build repo. It's clunky and I wouldn't want to gunk up the main repo with it, but it's probably acceptable in this separate build repo. 

BTW @ilanschnell is working on conda no-arch pkgs. I think even after they are ready and we can build on binstar, this separate build repo is a good way to continue since it offers more control over when "release" builds get made.

**Comment by damianavila** [comment]
>Another option is to have a "counter" file in the build repo. It's clunky and I wouldn't want to gunk up the main repo with it, but it's probably acceptable in this separate build repo.

Yep, that's true...

>BTW @ilanschnell is working on conda no-arch pkgs. I think even after they are ready and we can build on binstar, this separate build repo is a good way to continue since it offers more control over when "release" builds get made.

Yep... that's the idea...

**Comment by damianavila** [comment]
Copied from FD for permanent reference:

I have the build on TravisCI working :wink:
It is surprising that:
* I build and upload all the packages to binstar in less than 10 min (I skipped the nosetest), it was too quick, probably because of the detailed in the next point,
* I build packages of around 3 mb: it seems that the cleaning of the bokehJS source from the packages (some of my last PRs) but also the starting from a fresh repo (with vendor smaller than before, thx to an old Mateusz PR) give us packages 1/10 of the last devel build size...
* still, I have to figured out the docs deploy (through encrypted SSH key) and finally make a simple script to automate the git steps from the main repo...
Finally some links: 
* complete log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/48977237/log.txt
* the travis.yml file responsible of the build: https://gist.github.com/damianavila/65376d54fe6444cafc22
* devel builds at binstar: https://binstar.org/bokeh/bokeh/files?version=0.7.2.dev.395187

And the CDN available too... all with the same build script running on TravisCI, jeje:
* http://cdn.pydata.org/bokeh/dev/bokeh-0.7.2.dev.395187.min.js
* http://cdn.pydata.org/bokeh/dev/bokeh-0.7.2.dev.395187.min.css
I forgot to mention it before :wink: Jan 31, 2015 2:29

**Comment by damianavila** [comment]
I have a new idea taking in consideration the things learnt from the previous experience... here we go:

* We use the main Bokeh repo to build. We know now that it takes 10 additional minutes, so it makes sense only building in predetermined points (devel builds, rc and releases). That's a reasonable trade-off, between time and complexity of the machinery. 
* We "signal" any of the builds tagging the repo (this is actually doable using TRAVISCI envs variables) and just that... nothing else to do... the script detect the tag and if it is exist, it trigger the build, if not... it is just a normal TravisCI run.

This save us to use a mirror repo, a complex list of git command (or a new script to replace them), hacky download of a travis.yml file with the proper config, etc... In summary, it is a cleaner model, you want a devel build or a rc candidate or release, tag it properly and and push it and the build will be done:

`git tag -a 0.7.2-dev`
`git push origin 0.7.2-dev`

just that two lines...

**Comment by bryevdv** [comment]
why not push a unique tag (with a commit hash, say)? Travis can still detect and add a sequence number, but we don't have to do any of the tag delete weirdness. Just to be clear, tagged builds are build only, no tests?

**Comment by damianavila** [comment]
> why not push a unique tag (with a commit hash, say)? Travis can still detect and add a sequence number, but we don't have to do any of the tag delete weirdness.

Yes, that's another way to solve it...

> Just to be clear, tagged builds are build only, no tests?

Tagged builds can be only build, but I would recommend test + build. I will use `after_success` TravisCI command and put the build after that, so we ensure that the build run if and only if the test passed. The build case would be just an especial case of a normal build... the idea is to use the current run and leverage over it just building if the tag is present and the test run successfully.

**Comment by bryevdv** [comment]
If there is time to do both, certainly we should do both.  I thought perhaps here was a time limit problem. Regarding the tagging I would very much like to avoid having to delete tags.

**Comment by damianavila** [comment]
>If there is time to do both, certainly we should do both. I thought perhaps here was a time limit problem. 

10 more min from time to time does not seems to me to much problem

>Regarding the tagging I would very much like to avoid having to delete tags.

OK, the I will write a tiny script `deploy.sh` where automatically takes the git hash, make the tag and push it :wink:
