### ISSUE TITLE
tap+open URL

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#1795]
A common requested feature is for a simple way to specify a URL to be opened on tap.  While I understand a future goal is to support JS callbacks more generally, I think this is a common enough use case that it would be nice to add a canned policy to just expose this behavior.

I'm not sure what the best approach would be - have the tap tool open the URL if such a field is specified for the point being clicked?

**Comment by bryevdv** [comment]
> I'm not sure what the best approach would be - have the tap tool open the URL if such a field is specified for the point being clicked?

Yes I think this is fine a "canned" special case behavior to add to tap tool for now.

**Comment by bryevdv** [comment]
@hafen FYI this is in a PR that will be merged later today

**Comment by hafen** [comment]
Thanks!  I'm looking here: http://bokeh.pydata.org/en/dev/docs/reference/models.html#bokeh-models-tools and I see there is an "action" property for TapTool, but I can't find a reference on how to use it.  Is there an example somewhere?

**Comment by bryevdv** [comment]
The only canned action yet  is the one that opens URLs. Here is an example in python:

https://github.com/bokeh/bokeh/blob/master/examples/glyphs/colors.py#L178
