### ISSUE TITLE
"dummy" data for custom legend entry shows up on plot

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#1796]
I've been working on an R interface to Bokeh.  For automatic creation of legends I often want complete control over how the glyph looks in the legend, rather than pointing to the GlyphRenderer for the actual glyph in the figure.  The most common case for this need is when there is a glyph with some aesthetic attribute varying for each point, and where there is not necessarily a particular point being rendered that is representative so as to be used as the reference point for the legend.

So to handle this, I make “dummy” glyphs solely for the purpose of the legend, with the right attributes set just the way I want them to look in the legend.  To get the glyph to show in the legend, I have to make it point to a ColumnDataSource with data in it.  If there is not any data, the glyph doesn’t show in the legend.  If there is data, the glyph shows in the legend, but it also shows up on the plot.  If I set x and y to be null, a point still shows up at (0,0).  I suppose I could get around this by setting the x/y location of the glyph to be outrageously large and make sure they aren't used in any range calculations, but there is probably a more elegant way to handle this.  Any experience or suggestions with this would be great.

**Comment by bryevdv** [comment]
@fpliger @damianavila I feel like I saw something similar in the `bokeh.charts` interface at least at some point. Can either (or both) of you comment with your thoughts?

**Comment by damianavila** [comment]
I made something similiar in charts and still lives there after @fpliger refactoring: https://github.com/bokeh/bokeh/blob/master/bokeh/charts/boxplot.py#L311-L322

Essentially we use "invisible" rects (in this case rects, but it is the same for any glyph)... this rects are bind to a datasource and then we pass `None` for `y`, `height` and `width` values, which make it invisible in the chart but useful as legends...

This is in the same direction as @hafen's ideas, and I agree that this is something not elegant... I am not sure about the best solution to this problem, maybe we have to revisit how the legend is generated and make it less automatic or more configurable?

**Comment by pzwang** [comment]
@damianavila That's definitely a bit of a hack.  I think it's fine to create a parameter for glyphs which defines how they appear in legends.  This is a well-defined, common use case.  That way you don't have to create dummy glyphs.

**Comment by hafen** [comment]
Oh I see - the part I was missing was setting size, radius, etc. to null as well.  That does the trick.  It's not elegant but it works, and this is probably something that only effects people building the language bindings, so I don't know how high priority a more elegant fix would be.

**Comment by bryevdv** [comment]
We should make an issue for future improvements, that enumerates the ideas for making it better.
