### ISSUE TITLE
use_prefix for Include not functioning completely correctly 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1798]
Ref: https://github.com/bokeh/bokeh/pull/1774#issuecomment-72505809

ping @mattpap

**Comment by bryevdv** [comment]
Guessing this is part of the problem:
```
In [11]: from bokeh.models import *

In [12]: Rect.__properties__
Out[12]: {'angle', 'dilate', 'height', 'width', 'x', 'y'}

In [13]: Grid.__properties__
Out[13]: 
{'bounds',
 'dimension',
 'grid_line_alpha',
 'grid_line_cap',
 'grid_line_color',
 'grid_line_dash',
 'grid_line_dash_offset',
 'grid_line_join',
 'grid_line_width',
 'ticker',
 'x_range_name',
 'y_range_name'}
```

**Comment by bryevdv** [comment]
This is another symptom:
```
In [3]: from bokeh.models.markers import Square

In [4]: Square.__properties__
Out[4]: {'angle'}

```

**Comment by bryevdv** [comment]
more details:
```
"nonselection_glyph": {"id": "58b9cbd3-0c5e-45cb-a817-b0961a384d0a", "type": "Circle"}```
```
But the alpha values are not getting set in the serialized versions:
```
{"id": "58b9cbd3-0c5e-45cb-a817-b0961a384d0a", "attributes": {"y": {"field": "y1", "units": "data"}, "x": {"field": "x", "units": "data"}, "id": "58b9cbd3-0c5e-45cb-a817-b0961a384d0a", "line_color": {"value": "#1f77b4"}, "fill_alpha": {"value": 1.0, "units": "data"}, "fill_color": {"value": "#1f77b4"}, "doc": "8bb4fe60-8c36-4d74-b35f-f443254e647e", "line_alpha": {"value": 1.0, "units": "data"}, "tags": []}, "type": "Circle"}
```

**Comment by hhuuggoo** [comment]
wait sorry - is the title of this PR supposed to be use_prefix?

**Comment by bryevdv** [comment]
Yes

**Comment by bryevdv** [comment]
This is undoubtedly the problem:

https://github.com/bokeh/bokeh/blob/master/bokeh/_glyph_functions.py#L68

I will fix it in the morning.

**Comment by mattpap** [comment]
> https://github.com/bokeh/bokeh/blob/master/bokeh/_glyph_functions.py#L68

You can always use `hasattr()` (not that I encourage that).

**Comment by bryevdv** [comment]
I would prefer to go back to inheritance, and use something like this:
```
class Foo(Property, FillProps):
    _fill_doc_template = "foo bar %s baz"

```
but I am not sure offhand how to make that work cleanly.

**Comment by bryevdv** [comment]
Could make that work by importing mixins into properties and polluting `MetaHasProps` in ugly ways. I'll just make the `hasattr` fix for now with a note to improve.

**Comment by bryevdv** [comment]
I actually now occurs to me that the code in `_glyph_functions` was already broken for any non-marker class, as-is.
