### ISSUE TITLE
copy on write

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#1799]
implemented COW for bokeh server

This is implemented off of #1713 because we're leveraging some of the testing facilities developed in that branch.  

Embed links, and bokeh pages will have an optional public flag that mean that we want to view a document in copy on write mode.

Immediate Scope:
- The javascript client library will keep track of the docid to temporarydocid mapping, so that multiple
embedded plots on the same page will have the same temporary id
- In copy on write mode - all URLs will have the docid replaced by `docid-temporarydocid`.  
- The server will store any changes in COW mode into the temporary docid (which might not be a full fledged document)
-  websocket clients in COW mode will end up subscribing to 2 topics, the original docid and the temporary one
-  In COW mode, all documents and objects will still retain the original docid, The document will retain an additional parameter about the temporary docid, and it will be the sessions responsibility to ensure that the server does the right thing

Longer Term Scope:
- handle expiration of COW temporary docs
- separate selections from data source so that this mechanism can be used to update plots
- add access controls around bokeh server documents so you can publish to groups rather than just everybody

## work
- [x] add published flag for bokeh server documents 
- [x] modify bokeh server authentication routines to understand COW
  - allow everyone to read from a COW document
  - guarantee we only write to the temporary docid
- [x] modify bokehjs client library to generate temporary docids and subscribe to appropriate channels
- [x] bokeh server should allow anonymous users to view public documents
- [x] add endpoint for turning on publishing for a document, and session functions for hitting this
- [ ] modify embed snippet to use public documents
- [ ] modify object page/app object decorators to use public documents

**Comment by damianavila** [comment]
Since #1855 was merged, I will close this one, but @hhuuggoo if you feel there is still need to be open.
