### ISSUE TITLE
bokeh server crashing when reloading flask app

### ISSUE THREAD

**Issue by mftt** [bokeh/bokeh#1801]
When I run the "stock_applet" example as described in its README.md, i.e.,

    $ bokeh-server --script stock_app.py
    $ python flask_server.py

Everything works fine. However, if I reload the webpage in my browser, the bokeh-server crashes with the following exception

>DeserializationError: Instance(PlotObject) failed to deserilize reference to {u'subtype': u'Figure', u'type': u'Plot', u'id': u'f3fb4a5b-082f-44e0-853a-9452cd1d2559'}
2015-02-03 11:23:44,142:ERROR:tornado.access:500 POST /bokeh/bb/e2b3ec75-eb27-40e3-ac3e-5afc2fcb1b49/bulkupsert (127.0.0.1) 73.41ms

System information:
>Bokeh version: 0.7.1
>Python version: 2.7.9-CPython
>Platform: Darwin-13.4.0-x86_64-i386-64bit

**Comment by mariusei** [comment]
I was able to reproduce the error when reloading, giving the output below. 

However, initially, the Flask server wouldn't output an error as templates/stock.html was missing.

> DeserializationError: Instance(PlotObject) failed to deserilize reference to {u'type': u'StockApp', u'id': u'5c1b8a39-f22b-4757-92d8-3b93866e1843'}
2015-02-10 14:41:56,352:ERROR:tornado.access:500 POST /bokeh/bb/6239603f-ee54-4dc1-bfbd-2f5546b03f92/bulkupsert (127.0.0.1) 143.11ms

**Comment by mftt** [comment]
Seems to be fixed with 0.8 (& dependencies update).

**Comment by istib** [comment]
Which dependencies need updating?

I am still seeing this issue (with 0.8.2 & 0.9)

**Comment by mftt** [comment]
A new version of werkzeug seems to fix it. See http://stackoverflow.com/questions/28241579/error-when-trying-to-run-bokeh-server/28283031#28283031

**Comment by istib** [comment]
Hi @mftt , thanks for the tip. Afraid this fix is already in, though:
https://github.com/bokeh/bokeh/blob/master/bokeh/server/utils/reload.py#L9-L13
