### ISSUE TITLE
TapTool doesn't allow to select exactly one renderer (overlapping renderers)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1803]
I think this should be configurable: either select the top-most or all overlapping renderers (the later is what currently happens). On the other hand, how to select a renderer that's covered completely by another one?

**Comment by bryevdv** [comment]
There's lots of possibilities
* only return the closest
* only return the closest that is also "on top"
* return everything 
* return N closest

etc. 

They are not hard to implement, we just need to expose a way to choose the policy that is not too cumbersome.

**Comment by bryevdv** [comment]
This is a dupe of #2328, continuing discussion there
