### ISSUE TITLE
Seems to be some curplot leftover in the codebase

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1809]
See linked_brusing notebook...

```python
p = gridplot([[s1,s2]])
show()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-9-ca160c5fe7d3> in <module>()
      1 p = gridplot([[s1,s2]])
----> 2 show()

/media/datos/Desarrollos/bokeh/bokeh/plotting.py in show(obj, browser, new, url)
    440     if obj is None:
    441         if notebook:
--> 442             plot = curplot()
    443         else:
    444             plot = curdoc()

NameError: name 'curplot' is not defined
```

I also found another one in the app_reveal...

**Comment by damianavila** [comment]
Checking the code... do we want to keep the ability to show the `curdoc`, I mean using show without passing an object?

```python
def show(obj=None, browser=None, new="tab", url=None):
...
    if obj is None:
        if notebook:
            plot = curplot()
        else:
            plot = curdoc()
    else:
        plot = obj
```

I think that maybe it would be appropriate to just ask the user to actually pass an object (we are showing that in our examples):

```python
def show(obj, browser=None, new="tab", url=None):
...
        plot = obj
```

or just...

```python
def show(plot, browser=None, new="tab", url=None):
...
```

Although `obj` is a better name, maybe it worth to change the `plot` occurrence by `obj`...

**Comment by bryevdv** [comment]
Agree `obj` is better and yes also no need to support `show()` at all anymore.

**Comment by damianavila** [comment]
ok, I will submit a PR fixing it... thanks for the feedback!

**Comment by jewfro-cuban** [comment]
Found another curplot() call in the save() method:

```
    515     if not title:
    516         warnings.warn("save() called but no title was supplied and output_file(...) was never called, using default title 'Bokeh Plot'")
    517         title = "Bokeh Plot"
    518
    519     if obj is None:
--> 520         if not curplot():
    521             warnings.warn("No current plot to save. Use renderer functions (circle, rect, etc.) to create a current plot (see http://bokeh.pydata.org/index.html)")
    522             return
    523         doc = curdoc()
    524     elif isinstance(obj, Widget):
    525         doc = Document()
```

**Comment by bryevdv** [comment]
Sure enough. I will remove that today, but note that the workaround is to not call `save()` with no arguments. This is actually what was intended, anyway, Thanks

**Comment by mlkb** [comment]
hello, 
i keep having this error with curplot()

> module 'bokeh.plotting' has no attribute 'curplot'
I cant find anything about curplot()
any help? thank you

**Comment by bryevdv** [comment]
@mlkb `curplot` was removed over three years ago. Are you actually using an ancient version of Bokeh? If so, your only best bet is to check out a GH tag corresponding to your version and peruse the examples / docs source files. We do not have the human resources to support versions that old. 

However, I would actually suggest that you update to current versions of Bokeh, which are vastly improved, and vastly better documented: http://bokeh.pydata.org/en/latest/
