### ISSUE TITLE
Document new Charts design

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1813]
New design is a big improvements and potentially a magnet for users contribution IF well documented enough so users know how the pattern works and how to create new charts.

**Comment by bryevdv** [comment]
@fpliger I am going to make a quick stab at #1817 right after the current big charts PR is merged so that that organization can be reflected in the docs.

**Comment by fpliger** [comment]
Brilliant! Thank you!

**Comment by bryevdv** [comment]
For this issue, for 0.8 release, will suffice to have reference docs. Additional improvements in follow-on issues.
