### ISSUE TITLE
Better variable names throughout Bokeh.charts

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1814]
ref: #1773 

Remove all `duplet`, `quartet`, `sextet`, `nonet`, etc in favor of readable `namedtuple`s

**Comment by damianavila** [comment]
oh... my lovely `*plet`, I will miss them :stuck_out_tongue_winking_eye:  (sorry, I could not avoid the comment, je je)

**Comment by fpliger** [comment]
ejej This is a sad Issue for @damianavila 

@bryevdv FYI I've corrected the reference, I think you meant #1773 and not #1173 .

**Comment by bryevdv** [comment]
This was done at some point.
