### ISSUE TITLE
Binstar package building and noarch

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1827]
This issue is to collect ideas regarding the build of packages and testing on Binstar:

* [x] look for noarch on TravisCI instead of conda convert
* [ ] look for noarch on Binstar
* [ ] build dev release on Binstar
* [ ] build full release on Binstar
* [ ] test examples on binstar

If you have more things, please add them to the list.

**Comment by bryevdv** [comment]
@almarklein @damianavila can this be closed?

**Comment by almarklein** [comment]
Well, we are not doing any building on binstar/anaconda.org yet. Not sure if this is something we still want to do?

**Comment by damianavila** [comment]
This is something I wanted to do, but still the Anaconda Build system does not have all the things we need... but they are working on that... so I would leave this opened.

**Comment by bryevdv** [comment]
No longer happening, closing.
