### ISSUE TITLE
smooth connected paths

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#183]
Right now you can specify vectors of linear, quadratic, or bezier curves independently.

It would be good to be able to render single paths that have all those components together in one path.

**Comment by bryevdv** [comment]
Hrm, this resolution is invalid, #268 refers to something else. Re-opening.

**Comment by bryevdv** [comment]
There's been evidently zero interest in this in 3 years, closing

**Comment by mmcguffi** [comment]
I think this may be what Im looking for, in #9688
