### ISSUE TITLE
HoverTool doesn't wrap text correctly for tips on the right side of a plot.

### ISSUE THREAD

**Issue by chrislindnercivitas** [bokeh/bokeh#1842]
If there is a lot of text in a hovertool box, it will correctly wrap the text.  However, this only seems to work when the text is on the left side of the plot.  When it draws the tip from the right side, no wrapping occurs, and the text can go off of the screen.

![image](https://cloud.githubusercontent.com/assets/9452037/6111575/7ad72ee4-b04f-11e4-8178-a7d218a5b0ab.png)

**Comment by dbdean** [comment]
This is the same bug as #8052, which is a duplicate of #7991.
