### ISSUE TITLE
tools not working on Gallery - Windows 7 + Chrome 40.0.2214.111 m

### ISSUE THREAD

**Issue by timelyportfolio** [bokeh/bokeh#1848]
On my Windows 7 machine with Chrome 40.0.2214.111 m, the tools are not working.  They work fine on Firefox and even IE. 

![bokeh_tools](https://cloud.githubusercontent.com/assets/837910/6113085/3bece40c-b05a-11e4-902b-d2d7454aaa8b.gif)

Unfortunately, no errors in the console either.

**Comment by bryevdv** [comment]
Just the resize and wheel zoom tool, or others as well?

**Comment by timelyportfolio** [comment]
All tools except for pan/zoom do not work.  They did at some point in the past.  I discovered when I was testing the rbokeh implementation.  Tools do not work there in the RStudio Viewer (webkit based) either, but I considered this an edge case.

**Comment by timelyportfolio** [comment]
Just wanted to update.  I went back to commit 34f85b32ca03c4b02a4b7385c32065e1b1173b51 and still have the issue.

**Comment by bryevdv** [comment]
FYI @pzwang reported problems on OS X with version 40. However everything is working for me with Version 42.0.2298.0 dev (64-bit) (on OS X). Would it be possible to see if the problem persists with a newer Chrome?

**Comment by timelyportfolio** [comment]
does not work (same issue) with Version 41.0.2272.43 beta-m (64-bit) and Bokeh 0.7.1

Since no console error, I can't determine what is happening.  Buttons seem to accept click but behavior is not changed.  Stays on pan.

Shift+scroll does not work either.

**Comment by bryevdv** [comment]
@timelyportfolio right, no more need for `shift+scroll` the wheel zoom and pan can coexist and be active together now without interference. I'll have to fire up a VM to look at this, will probably be this afternoon sometime.

**Comment by scizmeli** [comment]
Hello, any advances on this bug?

**Comment by mridsole** [comment]
Also getting this problem with Chrome 44.0.2403.130 m

**Comment by bryevdv** [comment]
Question we should have asked earlier: are those experiencing this issue using touchscreen enabled laptops that can have both mouse and touch events?

**Comment by bryevdv** [comment]
ref: #3905

**Comment by dhirschfeld** [comment]
I can confirm that [disabling touch](http://bokeh.pydata.org/en/0.10.0/docs/faq.html#are-the-tools-not-working-in-chrome-cromium) makes the tools work.
![image](https://cloud.githubusercontent.com/assets/881019/13206252/eee92998-d945-11e5-8b24-ac91a4175262.png)

Note: I'm on a desktop PC *without* touchscreen monitors.

**Comment by bryevdv** [comment]
OK, I mentioned in the other issue, there is a newer version of the JS lib (hammer.js) that we use to handle UI events. Looking at this http://hammerjs.github.io there is also a new, tiny separate "Hammer-time" component that implements `touch-action` we may want that as well. 

Let me see about a branch / PR to build with the new versions and we can see if that helps anything.

**Comment by nishant031** [comment]
I have got the same issue when using QWebView in QT which enables us to load HTML pages.
I have to figure out and try to detect there and see if disabling touch event works fine or not.

**Comment by bryevdv** [comment]
To be completely frank, I'd very much like to fix this, but I don't really have any idea how. Updating Hammer.js did not seem to have any effect. If anyone here has any suggestions, please chime in.

**Comment by nishant031** [comment]
I actually tried this just now in my QT application by disabling touch (as mentioned in http://stackoverflow.com/questions/27550040/qt-disable-touch-screen-detection)
It still did not work.
I find this Bokeh to be so awesome.... 

Is there a way we can get rid of these buttons from the button bar ? 
I don't want to do this since these provide good functionality of pan, zoom, resize,save etc...

If we still feel that we need to go ahead with Bokeh, I will probably want to remove those buttons...
Is there a way ?  Even the buton on extreme left which opens the bokeh.org ..

**Comment by bryevdv** [comment]
you can remove the entire toolbar by setting `plot.toolbar_location = None`

**Comment by nishant031** [comment]
Thanks..
But, in the example : http://bokeh.pydata.org/en/0.10.0/docs/gallery/legend.html
If I put toolbar_location = none in the line:
p1 = figure(title="Legend Example", tools=TOOLS)

Then it gives error that supported values are right,left,above,below..

Even the documentation on page below says nothing about None : 
http://bokeh.pydata.org/en/0.10.0/docs/user_guide/tools.html

**Comment by bryevdv** [comment]
> Even the documentation on page below says nothing about None : 

Yes, it does :)

> If you would like to hide the toolbar entirely, pass None.

(near the bottom of the section) You can also see an example here:

http://bokeh.pydata.org/en/latest/docs/gallery/scatter.html

BTW your link is to an old version of the docs, you should probably always go to "bokeh.pydata.org/en/***latest***" unless you are specifically looking for older docs.
