### ISSUE TITLE
remove gaps on left and right sides of horizon chart

### ISSUE THREAD

**Issue by matdrapeau** [bokeh/bokeh#1850]
There is some gap on each sides of the plot that should be filled

**Comment by matdrapeau** [comment]
```
    chart.h_symmetry = False
    chart.min_border = 0
    chart.min_border_right = 0
    chart.min_border_left = 0
```
Doesn't do much in horizon_builder.py, the gaps are still there on both sides of the plot

**Comment by matdrapeau** [comment]
Well, this has nothing to do about border sizes. This seems to be about the x axis range which is larger than the actual data range leaving a space on both sides. Since I see the same behavior in the timeseries graph.

@bryevdv how can I fix the x-axis to be as large as the dataset and not larger?

**Comment by matdrapeau** [comment]
It seems the way to handle this is to set the axis bounds to start and end values.

Doing something like:
```
chart.below[0].bounds = (min(values[index]), max(values[index]))
```
Is generating this error:
```
ValueError: expected an element of either Auto or Tuple(Float, Float), got (Timestamp('2000-01-03 00:00:00'), Timestamp('2009-12-31 00:00:00'))
```

Maybe this is another new issue since we should be able to provide timestamp when working with DateTimeAxis

**Comment by damianavila** [comment]
@matdrapeau you probably hit this one: #1734

**Comment by matdrapeau** [comment]
@damianavila just tried by updating the ```bounds``` property without success. The gap is still there

**Comment by matdrapeau** [comment]
I've found it.... ```DataRange1d.rangepadding = 0```

**Comment by bryevdv** [comment]
OH, *that* space/padding... sorry so much going on I misinterpreted what you were after.

**Comment by damianavila** [comment]
>OH, that space/padding... sorry so much going on I misinterpreted what you were after.

yep, I misinterpreted you too... great you have find it...
