### ISSUE TITLE
Pyramid / back-to-back / symmetrical charts 

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#1852]
As mentioned in #1836, I'd love to see a flag on Bar to switch the vertical axis to be the categorical axis so we can make charts like

![20151101_inc011](https://cloud.githubusercontent.com/assets/1796208/6111189/e1a06a00-b03b-11e4-977a-bc8762883e7b.png)
(source: [http://www.economist.com/news/21631911-end-population-pyramid-world-reshaped](http://www.economist.com/news/21631911-end-population-pyramid-world-reshaped))

Am thinking it's fairly easy code, but the interface could get confusing - at the moment my best suggestion would be `vertical_cat` (optional Bool that defaults to false). The reason this is weird is that then you can set a custom y_range, but it would actually be a custom x_range......suggestions welcome.

In implementing this would it be ok to add it as an example in the examples folder, or are there processes for adding new examples?

**Comment by birdsarah** [comment]
So, I've caused some confusion :s 

@bryevdv and @pzwang wrote some comments on #1851 about how to do a range (split / two-way / symmetric ) that would facilitate a pyramid plot.

It's interesting, because I wasn't imagining doing pyramid plots like that. To my mind, a pyramid plot is two bar charts back-to-back. And so I was just imagining using two seperate plots (which could happily share a y_axis because bokeh is awesome) to make a pyramid plot.

In my ipython notebook (http://nbviewer.ipython.org/github/birdsarah/bokeh/blob/pyramid_plot/examples/plotting/notebook/pyramid_plot.ipynb):
* I'm pretty happy with the results using the low-level interface, I'm not sure why I'd want to implement a new range type.
* When I try to use the Bar charting interface, I'm almost there, but there are a couple of additional interfaces I need
** ability to switch the categorical / linear axis - the original intention of this issue
** now i've tried it I see I also need an interface to not add a categorical axis on one of the plots.

Maybe there are some different things bubbling here:
* Bar
* VerticalBar (where the vertical axis is categorical, and the horizontal linear)
* BackToBack (a generic interface to stick together two charts in mirror-image format)

**Comment by birdsarah** [comment]
I've updated the issue title to try and make this a little clearer.

**Comment by bryevdv** [comment]
@birdsarah two back to back charts is absolutely another reasonable approach to this kind of chart. In fact it's one I had previously had in mind, but the suggestion of a split range also seemed useful, so I wanted to get my thoughts about it out while I had them. :) That said, I would wait just a little while for the back to back, in the near future we will have to ability to lay out multiple plots on one canvas, and that would be a much better foundation to build this approach on, I think. 

Alternatively, if anyone wants to dig into the BokehJS code and add a "grid layout" to the existing "simple plot layout" I would be happy to help discuss/plan it. Otherwise I would look for that around the 0.8.1 timeframe.

**Comment by birdsarah** [comment]
@bryevdv, thoughts are always great - I have a lot to learn. 

Holding off on the BackToBack sounds good.

I've opened a new discussion about HorizontalBar charts (#1856), as I think it's easy and something I'd like to see. 

(I hope I'm not causing you issue spam, just trying to keep conversations small, as my brain works better that way)

**Comment by birdsarah** [comment]
From @bryevdv 

> Here is how I would handle this. Plots can accept additional named ranges. So, I would handle this by having a SplitRange (or something) that coordinates two additional Range1d objects. Then individual glyphs can be configured to use either the "left" or "right" half of the SplitRange, which really just means being configured with the appropriate additional named range. Then, we need an axis object that can deal with SplitRange (by for instance, not stroking label for the the shared point twice). I think we can handle tools by letting SplitRange expose a synthetic [start, end] range (similar to categorical ranges). Tools fiddle with this synthetic range, which the SplitRange then uses to update its children ranges (because it knows what the original bounds of the children ranges were, it can scale appropriately). 

> A general description of the SplitRange is just the ability to have twin axes that don't stack on top, but instead render side by side. 

From @pzwang 
> Yep. And this is a common enough pattern that we should specialize for the two-axis use case...

**Comment by birdsarah** [comment]
@pzwang - do you think these layout suggestions, including holding off while the new layout stuff comes through, will meet your needs or are you still interested in a specialized axis / range.

**Comment by damianavila** [comment]
>(I hope I'm not causing you issue spam, just trying to keep conversations small, as my brain works better that way)

We :heart:  this sort of issues spam :wink: Thanks for letting know your though and don't hesitate to open issues for discussions (if there some overlapping, eventually we can develop the discussion in one and close the others if it is really needed, but focused discussion it specific points is a good pattern :wink:).

**Comment by bcipolli** [comment]
May I ask, what's the status of this type of plot in bokeh? I would like to create such a visualization, and wondering if I can do so in Bokeh.

**Comment by bryevdv** [comment]
There's not a canned high level chart type for it, but you can certainly draw this type of chart, as demonstrated above. Now with `hbar` it should be even easier.
