### ISSUE TITLE
HorizontalBar

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#1856]
Following on from #1780, #1836, #1851, #1852

How do people feel about a HorizontalBar variation of Bar, where the categorical axis runs on the y (and the bars run Horizontally)? 

One small naming concern is a potential confusion between: 
- Bar Graph aka Horizontal Bar Graph (we currently don't have a chart for)
- Column Graph aka Vertical Bar Graph (currently `Bar`)

I'm not sure what people use for references on this stuff, I have a few books lying around, but have only picked stuff up informally, so I have no idea what "correct" is or should be. 

But it seems that maybe being explicit and just having HorizontalBar and VerticalBar (which would imply a name change for Bar) might be useful.

**Comment by bryevdv** [comment]
@birdsarah First, thank you very much for starting all these vigorous discussions!

Personally, my own preference would be for `Bar(orientation="horizontal")` and `Bar(orientation="vertical")`, with `HBar` and `VBar` functions that are shortcuts for these.

**Comment by birdsarah** [comment]
I like that.

PR #1836 adds the parameter y_range, where a user can specify a custom `y_range`. That makes the interface:

    Bar(values, cat=['A', 'B'], stacked=False, y_range=Range1d())

With `horizontal` & `vertical` in play, it seems that it would be more appropriate to use `linear_range`, so interface be:

    Bar(value, cat=['A', 'B'], stacked=False, orientation="vertical", linear_range=Range1d())

Building on this, it would seem logical to build on `cat`, and offer a `cat_range` parameter, where users can specify their own categorical_range, and `cat` is a shortcut onto FactorRange(factors=cat).

**Comment by bryevdv** [comment]
agree a non-dimension specific name is advised given these ideas. Perhaps `continuous_range`?

**Comment by birdsarah** [comment]
I have a background question before I go ahead with this one.

When looking at https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder/bar_builder.py#L38
```` python
def Bar(values, cat=None, stacked=False, xscale="categorical", yscale="linear",
        xgrid=False, ygrid=True, **kw):

    return create_and_build(
        BarBuilder, values, cat=cat, stacked=stacked,
        xscale=xscale, yscale=yscale,
        xgrid=xgrid, ygrid=ygrid, **kw
    )
````

I'm confused by the xscale and yscale being in the method signature for Bar, as if a user tries to override them the chart won't render (because they need an appropriate range to match). (At least that's my understanding).

My initial thought would be something like:

```` python
def Bar(values, cat=None, stacked=False, orientation="vertical",
        xgrid=False, ygrid=True, **kw):
   
   if  orientation=="vertical":
        xscale = "categorical"
        yscale = "linear"
        # also set the ranges approprirately

   if  orientation=="horizontal":
        xscale = "linear"
        yscale = "categorical"
        # also set the ranges approprirately

    return create_and_build(
        BarBuilder, values, cat=cat, stacked=stacked,
        xscale=xscale, yscale=yscale,
        xgrid=xgrid, ygrid=ygrid, **kw
    )
````

Wisdom gratefully received.

**Comment by damianavila** [comment]
Adding @fpliger to the discussion who will be interested too...

**Comment by fpliger** [comment]
Ah, apparently I didn't hit "comment" before... here's my reply. :-)

@birdsarah there is certainly an issue with that. It's there mainly because of historical reason. Now that you made me think about it we could have removed those arguments for charts that only support very specific scales when implementing the builders design. I'd be inclined to remove those for 0.8.1 @damianavila @bryevdv what do you think?

**Comment by damianavila** [comment]
:+1: for removal for 0.8.1, as you said they are mainly for historical reasons :raised_hand: and can be removed now, I think...

**Comment by dbendet** [comment]
Hey, just wondering if the the horizontal bar feature has been built.  I've been searching for it in the docs and can't seem to find an example of this.  Is it possible to make horizontal bar charts in Bokeh, or flip the X & Y axes?  Thanks!

**Comment by birdsarah** [comment]
Hi @dbendet - there are a number of variations on bar charts that I'd like to build. However, the charts interface is undergoing a major overhaul at the moment, so I haven't started them yet.

You could certainly make one yourself, it would just require a little more work. I would start by looking at the code that builds the normal bar chart - which is here: https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder/bar_builder.py#L195

Building custom bar charts tripped me up when I was getting started with Bokeh. On a categorical axis you need to format your data in a certain way to set the width of the bars. Check out : https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder/bar_builder.py#L131

**Comment by dbendet** [comment]
@birdsarah thanks for the quick response, I'm looking forward to new features!

**Comment by silviaegt** [comment]
@dbendet would you mind showing me how you coded your graph in order to make it horizontal? Or does anyone have tried it already and have an example of how to do this? I am a newbie :s

**Comment by birdsarah** [comment]
@silviaegt - maybe this will help: http://nbviewer.ipython.org/github/birdsarah/europython-2015-bokeh/blob/gh-pages/notebooks/Plotting.ipynb

**Comment by birdsarah** [comment]
.

**Comment by su79eu7k** [comment]
Google search term "bokeh horizontal bar plot" took me here. After review this thread, I tried workaround by using `.quad()` to mimic stacked horizontal bar chart. If some of you urgently need the chart like me before `HBar()`, `VBar()` implemented, please refer to my [example](https://github.com/su79eu7k/bokeh_examples). @dbendet @silviaegt 

<img src="http://i.imgur.com/uAL9NsM.png", width="200", height="200"><img src="http://i.imgur.com/hewQX7C.png, width="200", height="200">

**Comment by edoardovivo** [comment]
Any news on this?

**Comment by bryevdv** [comment]
The `HBar` glyph (and correspondin `hbar` glyph method on figure) has existed for some time now. There's not currently a maintainer for `bokeh.charts` so I would not expect anything added there anytime soon unless someone new steps in.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/37)
