### ISSUE TITLE
Map projections

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#186]
Should add various map projections. The projections should be specified per-glyph I think, or perhaps plot objects can take a default that could be overridden by glyphs.

**Comment by davidgardenier** [comment]
Astronomer here! I was curious if there's any current work being done on map projections in bokeh? :) For sky maps, we often need to use projections such as a [Mollweide projection](https://en.wikipedia.org/wiki/Mollweide_projection) which would be a great functionality to see in bokeh, as we are currently forced to use tools such as matplotlib.

**Comment by andreas-h** [comment]
@bryevdv Any news on the issue of map projections?

**Comment by bryevdv** [comment]
Closing this, Bokeh is currently being pared down to an essential stable core, so that other tools can build on top of it reliably. The appropriate place for more sophisticated GIS work is GeoViews and other projects on top of a stable Bokeh core. 

cc @jbednar @philippjfr @jlstevens

**Comment by jbednar** [comment]
That said, GeoViews already supports projections, including Mollweide:

[![image](https://user-images.githubusercontent.com/1695496/31565494-9cdf9e74-b02c-11e7-8f11-84cd3c969b4b.png)](http://geoviews.org/Projections.html)

but it only supports them for Matplotlib, via Cartopy, and thus any such projection can't be interactive the way GeoViews is when used with Bokeh.  For Bokeh, GeoViews can accept data in any projection, but it can't support any output projections without having support in Bokeh itself.  @philippjfr could chime in to suggest precisely what minimal support would be needed from Bokeh for us to support output projections for Bokeh plots, but I do think it's changes within Bokeh, not in GeoViews.

**Comment by bryevdv** [comment]
> Bokeh plots, but I do think it's changes within Bokeh, not in GeoViews.

Yes quite possibly but I want narrow constrained features driven by upstream requirements. (This issue is too broad/vague to be useful)
