### ISSUE TITLE
Docs - images overlapping at certain viewports

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#1863]
http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html

![bokeh-docs-chart-responsive](https://cloud.githubusercontent.com/assets/1796208/6142352/a91d0f4c-b169-11e4-9451-9999f026bec5.png)

Happens to me between ~ 1000-1200px & ~600-845px wide 
(Firefox on Ubuntu.)

(I'm pretty sure a clearfix on .section would sort most of the problem)

**Comment by bryevdv** [comment]
LOL (thanks @birdsarah)

**Comment by bryevdv** [comment]
FYI that entire section is about to be re-written and all those images will be live plots with code. Might still need the CSS fix, though.

**Comment by fpliger** [comment]
OMG, this is terrible :-/

**Comment by birdsarah** [comment]
This is fixed now. Not sure when it happened.
