### ISSUE TITLE
Improve numeral.js (scientific notation, time, etc.)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1879]
- [ ] rewrite numeral in coffeescript (turn into a bokehjs module)
- [ ] cleanup the implementation (currently `0.0+` is a positive number)
- [ ] add support for scientific notation (`0.0E+000`, unicode superscript, etc.)
- [ ] better time formatting (e.g. no seconds, with milliseconds)
- [ ] date formatting
- [x] ~~~Excel compatibility~~~ (?)

**Comment by bryevdv** [comment]
@mattpap has any part of this fallen out of some of the recent `numbro` work?

**Comment by mattpap** [comment]
No, I don't think so.

**Comment by bryevdv** [comment]
Now that datetime and CustomJSFormatter exists, I am inclined to let those be the answer for any specialized needs, rather than us taking ownership of more code.
