### ISSUE TITLE
Rendering issue in chrome

### ISSUE THREAD

**Issue by jfmackay** [bokeh/bokeh#1882]
Seems to be a layout problem in chrome + iPython. I draw a simple line chart with Bokeh but it seems to float over the rest of the iPython notebook. This does not occur in Safari. Bokeh 0.7.1, iPython 2.4.1, Chrome 40.0.2214.111.

![screen shot 2015-02-12 at 4 17 08 pm](https://cloud.githubusercontent.com/assets/5185958/6179908/e4c5894c-b2d2-11e4-958e-128fbcd03068.png)

**Comment by bryevdv** [comment]
Need to see if it can reproduced, close if not.

**Comment by bryevdv** [comment]
@jfmackay do you have any minimal code example to reproduce this problem?

**Comment by jfmackay** [comment]
This appears to no longer report on latest Bokeh/Chrome

**Comment by bryevdv** [comment]
OK great, please re-open if the problem shows up again.
