### ISSUE TITLE
Axis.hide should have been called Axis.visible

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1885]
Obviously with reversed logic as well. Reasons: we already have `Glyph.visible` (no need to invent new names) and our properties are nouns or adjectives (at minimum, this property should have been called `hidden`). This should be resolved for 0.8 (it's a new property).

**Comment by bryevdv** [comment]
@mattpap sure that seems reasonable, can you knock this out right quick?

**Comment by mattpap** [comment]
Sure.
