### ISSUE TITLE
Running stream_sys_stats_to_file.sh is failing with a charts attribute error

### ISSUE THREAD

**Issue by kaluza** [bokeh/bokeh#1891]
== Remote URL: origin	https://github.com/ContinuumIO/bokeh (fetch)
origin	https://github.com/ContinuumIO/bokeh (push)
== Most Recent Commit
commit 12973024ce3adf742b3470001f834393e2ec2b69
Merge: 81147f9 898437f
Author: Damián Avila <damianavila82@yahoo.com.ar>
Date:   Sat Feb 14 08:42:49 2015 -0300

Attempting to run sh stream_sys_stats_to_file.sh is failing with an attribute error caused by attempting to access an attribute that has removed removed from the charts library.

The error can be reproduced by running the CLI command within the shell script:
    kaluza|~/engr/devel/graphing/bokeh/examples/cli$ python ../../bokeh-cli --title "CPU STATS" --series "CPU_1,CPU_3" --chart_type "line" --input "sample_data/sys_stats.csv" --output server://clisysdemo --sync_with_source t
    Traceback (most recent call last):
      File "../../bokeh-cli", line 5, in <module>
        cli()
      File "/Users/kaluza/anaconda/lib/python2.7/site-packages/click/core.py", line 610, in __call__
        return self.main(*args, **kwargs)
      File "/Users/kaluza/anaconda/lib/python2.7/site-packages/click/core.py", line 590, in main
        rv = self.invoke(ctx)
      File "/Users/kaluza/anaconda/lib/python2.7/site-packages/click/core.py", line 782, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Users/kaluza/anaconda/lib/python2.7/site-packages/click/core.py", line 416, in invoke
        return callback(*args, **kwargs)
      File "/Users/kaluza/engr/devel/graphing/bokeh/bokeh/cli/core.py", line 66, in cli
        cli.run()
      File "/Users/kaluza/engr/devel/graphing/bokeh/bokeh/cli/core.py", line 197, in run
        self.map_options, children=children, **self.chart_args
      File "/Users/kaluza/engr/devel/graphing/bokeh/bokeh/cli/core.py", line 344, in create_chart
        if chart_type == bc.GMap:
    AttributeError: 'module' object has no attribute 'GMap'

I verified that the stream_sys_stats_to_file.sh worked with the last commit revision '144d07a720ba6d4b5bb32589aa359e73de8f8766': 
kaluza|~/engr/devel/graphing/bokeh/examples/cli$ sh stream_sys_stats_to_file.sh

    Bokeh Server Configuration
    ==========================
    python version : 2.7.9
    bokeh version  : 0.7.0-315-g144d07a
    listening      : 127.0.0.1:5006
    backend        : memory
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF
    data-directory : None

Using saved session configuration for http://localhost:5006/
To override, pass 'load_from_config=False' to Session
2015-02-15 12:22:10,873:INFO:tornado.access:200 GET /bokeh/userinfo/ (127.0.0.1) 1.32ms
2015-02-15 12:22:10,876:INFO:bokeh.server.models.docs:num models: 1

**Comment by bryevdv** [comment]
Hi Brian,

We have not actually announced the Bokeh CLI tool. What CLI code that is in the repository currently should be considered pre-alpha at best right now. We are planning on announcing the CLI tool officially when it is ready for general use. We have also unfortunately had to remove GMap from bokeh.charts temporarily. I expect it will be restored for Bokeh 0.8.1. However, the reason for this was to adopt a vastly better, more extensible and documentable design, so we should be able to progress rapidly on both new bokeh.charts as well as the CLI tool after the upcoming 0.8 release. Unfortunately the current GMap implementation is incompatible, and we simply did not have the man or woman power to get it back into shape in time for 0.8. (Our release dates are not normally driven by external factors, but this one in particular was.)

Thanks,

Bryan

**Comment by bryevdv** [comment]
`GMapPlot` has since been restored. CLI tool is separate issue. Closing as `invalid`
