### ISSUE TITLE
Support __array__ and __list__ protocols

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#1894]
Inputs to bokeh graphing functions seem to be able to take one of the following forms

```
DataFrame, dict, OrderedDict, list, tuple, ndarray
```

I wonder if we could extend this to include anything that supports the `__array__` or `__iter__` protocols.   In my own experiments I wrote this function

``` Python
def normalize_data(data):
    """ Normalize input data to supported types """
    if isinstance(data, (np.ndarray, pd.DataFrame, list, tuple, dict,
        OrderedDict)):
        return data
    if np and hasattr(data, '__array__'):
        result = np.array(data)
        # TODO: Other parts of Bokeh should support numpy record dtypes
        #       convert to DataFrame for now
        if isinstance(result.dtype.descr, list):  # record dtype
            return pd.DataFrame(result)
        else:
            return result
    if isinstance(data, Iterable):
        return list(data)

    raise TypeError("Input type %s not supported" % type(data).__name__)
```

and inserted it into `bokeh/charts/_builder.py:_adapt_values`.  This allowed me to use Blaze expressions directly in Bokeh plots which felt pretty cool.

More generally would it make sense to normalize inputs even further, perhaps using only a single data type within Bokeh, presumably either a `DataFrame` or `OrderedDict`.  I notice that some functions seem to branch on the type of `_values`.

**Comment by bryevdv** [comment]
That is really cool! we should enable this right after 0.8 release I think. Regarding a single type, we are doing out best not to have a hard dependency on Pandas, but also not to require unnecessary copying. Our `DataAdapter` class is a (not complete) stab at a very thin wrapper that presents a "pandas-like" interface, regardless of that the actual data is.

**Comment by damianavila** [comment]
:+1:

**Comment by bryevdv** [comment]
@mrocklin what are examples of libraries/objects that support `__array__` that this could be tested with if it were added?

**Comment by mrocklin** [comment]
At the time of writing this I was probably pretty interested in Blaze.  Nowadays I would recommend dask.array

```python
import dask.array as da
x = da.arange(10, chunks=(5,))
```

**Comment by bryevdv** [comment]
closing, `bokeh.charts` is gone. Possibly makes sense to suggest to HV
