### ISSUE TITLE
Charts xlabel and yabel defaults

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1901]
With introduction of ChartOptions xlabel and ylabel now defaults to 'x_label' and 'y_label'. Thus users need to explicitly pass xlabel='' or ylabel='' for not show anything. IIRC blank was the default in previous versions and I think it makes sense...

**Comment by bryevdv** [comment]
@Maggie-M is about to push a PR to fix this.

**Comment by fpliger** [comment]
Great! 

> changing to xlabel though I think

You mean changing to 'xlabel' as default?

**Comment by fpliger** [comment]
ping @bryevdv @Maggie-M . default values now are 'x-axis' and 'y-axis'. Should we go ahead and use "" as default? Otherwise we should close this issue...

**Comment by bryevdv** [comment]
I am +1 on having the empty string as the default.
