### ISSUE TITLE
ZMQError: Connection refused on starting the server

### ISSUE THREAD

**Issue by Qwlouse** [bokeh/bokeh#1911]
When starting the bokeh-server I get the following stacktrace

```
$ bokeh-server --backend=memory

    Bokeh Server Configuration
    ==========================
    python version : 2.7.6
    bokeh version  : 0.7.1
    listening      : 127.0.0.1:5006
    backend        : memory
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF
    data-directory : None
    
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/greff/venv/py2/local/lib/python2.7/site-packages/bokeh/server/zmqpub.py", line 24, in run
    socket.connect(self.zmqaddr)
  File "zmq/backend/cython/socket.pyx", line 471, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4295)
ZMQError: Connection refused

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/greff/venv/py2/local/lib/python2.7/site-packages/bokeh/server/zmqsub.py", line 24, in run
    socket.connect(addr)
  File "zmq/backend/cython/socket.pyx", line 471, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4295)
ZMQError: Connection refused

```
I run Bokeh 0.7.1 on python 2.7.6:

```
$ python -c "import bokeh; print(bokeh.print_versions())"

  Bokeh version: 0.7.1
  Python version: 2.7.6-CPython
        Platform: Linux-3.13.0-45-generic-x86_64-with-Ubuntu-14.04-trusty
```
The server still starts and shows my plots, but it does not seem to update animated plots. 
Any ideas on how to fix that?

**Comment by bryevdv** [comment]
Well, we are releasing Bokeh 0.8 later today, my first suggestion is to re-try using that, and if there are still problems we can proceed from there.

**Comment by mattpap** [comment]
> The server still starts and shows my plots, but it does not seem to update animated plots. 

If ZMQ doesn't start properly then there will be no websocket support in `bokeh.server` and thus no updates, no animation, etc.

The traceback you show is unexpected, because we use `inproc` protocol and this shouldn't happen (especially that you use a standard linux distribution). What version of zeromq/pyzmq do you have installed on your system?

**Comment by Qwlouse** [comment]
```
$ python -c "import zmq; print(zmq.pyzmq_version())"
14.5.0
```
and 
```
python -c "import zmq; print(zmq.zmq_version())"
2.2.0
```
Im running it from a virtualenv, but that should not matter I guess.

**Comment by Qwlouse** [comment]
Updating to version 0.8.0 did not change the problem:
```
$ bokeh-server --backend=memory

    Bokeh Server Configuration
    ==========================
    python version : 2.7.6
    bokeh version  : 0.8.0
    listening      : 127.0.0.1:5006
    backend        : memory
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF
    
/home/greff/venv/py2/local/lib/python2.7/site-packages/bokeh/server/blaze/__init__.py:19: UserWarning: could not import multiuser blaze server No module named blaze.  This is fine if you do not intend to use blaze capabilities in the bokeh server
  warnings.warn(msg)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/greff/venv/py2/local/lib/python2.7/site-packages/bokeh/server/zmqsub.py", line 24, in run
    socket.connect(addr)
  File "zmq/backend/cython/socket.pyx", line 471, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4295)
ZMQError: Connection refused

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/greff/venv/py2/local/lib/python2.7/site-packages/bokeh/server/zmqpub.py", line 24, in run
    socket.connect(self.zmqaddr)
  File "zmq/backend/cython/socket.pyx", line 471, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4295)
ZMQError: Connection refused

```

**Comment by mattpap** [comment]
On my system:
```
In [1]: import zmq

In [2]: zmq.pyzmq_version()
Out[2]: '14.5.0'

In [3]: zmq.zmq_version()
Out[3]: '4.0.4'
```
Although we don't specify this explicitly in our build, I think you have to have at least zmq 3.x installed on your system.

**Comment by Qwlouse** [comment]
Confirmed. I just updated to `zmq 4.0.5` and it works. Thanks.

It is a bit annoying that `libzmq-dev` shipped with ubuntu is still `2.2.0`.

**Comment by mattpap** [comment]
@Qwlouse, I'm glad it works now. btw. You could try out conda (http://conda.pydata.org), which is our python/native package manager, to improve the situation with ubuntu.

@bryevdv, I think we should somehow follow up on this issue and make sure that the right version of zmq is installed, so that users don't get confusing error messages.

**Comment by damianavila** [comment]
>@bryevdv, I think we should somehow follow up on this issue and make sure that the right version of zmq is installed, so that users don't get confusing error messages.

I agree, just checking the version an warn the user would be enough, I think...

**Comment by bryevdv** [comment]
Yah we should make it a hard dependency version of the server when the server splits to its own package (if it is not already) but we should also do a version check for this and several other dependencies in order to give better message to users.

**Comment by jakeret** [comment]
Quick follow up on this. I'm running on OSX and I was getting the same `ZMQError`. 
I got the `zmq` package from Mac ports and was running on the following version:
```
$ port installed zmq
The following ports are currently installed:
  zmq @3.2.4_0
  zmq @3.2.5_0 (active)
```
```
In [1]: import zmq

In [2]: zmq.zmq_version()
Out[2]: '3.2.5'
```

I had to deactivate this version and install the zmq-devel package (`port install zmq-devel`). Now, I'm on '4.1.2' and is seems that the server is running.

**Comment by npyoung** [comment]
I'm seeing this same problem with pyzmq version 14.7.0 and zmq version 3.2.4 on ubuntu 14.04.

**Comment by bryevdv** [comment]
There is a new server in development (see WIP PR in flight) that does not use ZMQ, so this is not an issue we can devote resources to.
