### ISSUE TITLE
Collect implicit interfaces into a single module

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1916]
Propose to move all "stateful" functions (and the "global" variables they use) into a new module `bokeh.state`:
```
curdoc
cursession
output_file
output_notebook
output_server
push
_push_or_save
reset_output
save
show
```
This should allow any of the different APIs to make use of these facilities for saving, showing, etc. 

To start, `bokeh,plotting` would import all of these into itself, and they would remain available as they are by "transitive importing". However, could wrap these versions in deprecations, with intent that in the future, users import directly from `bokeh.state`. 

This would certainly make these facilities easier to document and maintain and test. 

One question if we do eventually want to remove the transitive imports: what to do about `figure()` which is the one function that needs to stay in `bokeh.plotting` but also uses these:
```
def figure(**kwargs):

    # .....

    fig = Figure(**kwargs)
    curdoc()._current_plot = fig
    if curdoc().autoadd:
        curdoc().add(fig)
    return fig
```
Options: require a `Document` or `state` module to be passed in. Continue to function as-is but import these functions inside `figure`. Thoughts?

**Comment by bryevdv** [comment]
@bokeh/core please comment

**Comment by damianavila** [comment]
Not sure about `state` as the name, but I don't have any better from the top of my head...

>To start, bokeh,plotting would import all of these into itself, and they would remain available as they are by "transitive importing". However, could wrap these versions in deprecations, with intent that in the future, users import directly from bokeh.state.

I agree.

>Options: require a Document or state module to be passed in. Continue to function as-is but import these functions inside figure

Not sure, I would probably go with the second one... I am not against imports in functions when there is a valid cause (and this seems a valid one).
