### ISSUE TITLE
remove _glyphfunctions 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1917]
With the old implicit glyph functions gone, the reason for this complicated machinery is gone too. These should be made simple, normal methods on `plotting.Figure`.

**Comment by fpliger** [comment]
shouldn't we deprecate them for the next release end remove them in the other following release?

**Comment by bryevdv** [comment]
The module itself is purely an implementation detail. Absolutely no one should be doing `import bokeh._glyphfunctions` for any reason  (thats what the leading underscore indicates). Not proposing removing the functions, per se, just the overly complicated way in which they are defined (which is no longer necessary to be so complicated)

**Comment by pzwang** [comment]
Agreed, the _glyphfunctions module should be removable without any deprecation warning.
