### ISSUE TITLE
examples/plotting/file/hover.py broken after 0.8 release

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1920]
All other examples with hover seem to be working. 
There are 2 different issues with the mentioned example:

```
("foo", "@foo"),
("bar", "@bar"),
``` 
lines are raising the following exception on JS side:

```Uncaught [sprintf] expecting number but found array```

and

```("(x,y)", "($x, $y)"),```

is raising:

```Uncaught ReferenceError: x is not defined```

**Comment by damianavila** [comment]
@mattpap can you take a view on this... we pretend to make a point release very soon after this is fixed...

**Comment by mattpap** [comment]
A quick fix is to use `@$index` (etc.) instead of `$index`. Currently both are allowed, but last minute change to function that replaces those placehoders made the later cause errors.
