### ISSUE TITLE
bokeh-notebooks needs update to use the new plotting API

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1927]

**Comment by bryevdv** [comment]
This has become a demonstrated problem for some users, will address today.

**Comment by bryevdv** [comment]
I have removed the tutorial section of now. The solution cell show/hide functionality no longer works in new notebooks. Also the tutorial needs to be updated rev'ed and this should be fixed as part of that work. All other notebooks have been updated to use newest APIs and have been re-executed with a current BokehJS.

**Comment by bryevdv** [comment]
@damianavila is there a way to automate execution of these notebooks as part of official releases?

**Comment by damianavila** [comment]
@damianavila is there a way to automate execution of these notebooks as part of official releases?

What is your idea? BTW, there is a new execute preprocessor in IPython, so we could execute them programmatically if this is your idea...
