### ISSUE TITLE
image glyph method should have a default palette

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1929]
ref: https://twitter.com/michaelaye/status/568154107699048451

**Comment by mattpap** [comment]
Trivial fix, but what should be the default?

**Comment by bryevdv** [comment]
grayscale, probably

**Comment by michaelaye** [comment]
I think for image of non-RGBA content grayscale is a fine choice.

**Comment by almarklein** [comment]
Do we even support RGB or RGBA images? If I modify a simple example to use an NxNx3 image I get nothing.

**Comment by bryevdv** [comment]
ImageRGBA or Figure.image_rgba

**Comment by almarklein** [comment]
Doh, its right below the class that I edited. I suppose I expected a single class for this.

**Comment by bryevdv** [comment]
I'd keep the models distinct but it might make sense to merge them in higher level APIs
