### ISSUE TITLE
Bokeh Glyph Quick Reference 404 (Docs)

### ISSUE THREAD

**Issue by alanhdu** [bokeh/bokeh#1933]
At http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#composition, the link for the [Bokeh Glyph Quick Reference](http://bokeh.pydata.org/en/latest/docs/glyphs_ref.html) is broken.

**Comment by bryevdv** [comment]
Apologies, here is the correct link: 

http://bokeh.pydata.org/en/latest/docs/reference/glyphs.html
