### ISSUE TITLE
Charts and datetime indexes

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1935]
Following up from a post on m.l.. IMO the following should work:

```Python
import datetime
from collections import OrderedDict
from bokeh.charts import Line, Step, TimeSeries
from bokeh.plotting import show
now = datetime.datetime.now()
dt = [now+datetime.timedelta(seconds=i) for i in range(10)]
xyvalues = OrderedDict({'date': dt})
xyvalues['data'] = [2, 3, 7, 5, 26, 27, 27, 28, 26, 20]
xyvalues['moredata'] = [12, 33, 47, 15, 126, 122, 95, 90, 110, 112]
#ln = Line(xyvalues, index='date', xscale='datetime')
st = Step(xyvalues, index='date', xscale='datetime')
ts = TimeSeries(xyvalues, index='date')
show(st)
```

Specifically, charts should have better support for indexes/ranges with datetime values (or even categories). I'm adding this as a bug but open for discussions...

**Comment by fpliger** [comment]
This can be fixed but changing https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder/line_builder.py#L110-L110
to 
```values = self._values[col]```

for line_builder. Also for step_builder is a quick fix.. and I wonder why we were using the nested list comprehension.. @damianavila do you recall? I really don't :-/

**Comment by damianavila** [comment]
Certainly, I don't remember...  maybe related processed one specific type of input?

**Comment by fpliger** [comment]
Yes.. I think so. Tests are passing if I change for line and step so I'd be tempted to remove this logic.

**Comment by damianavila** [comment]
yep, probably... are you intended to get this fix included in 0.8.1?

**Comment by fpliger** [comment]
With the 0.8.1 coming "too" soon for this I've changed it to 0.8.2

**Comment by bryevdv** [comment]
Most work should already be done in current "x, y names" PR

**Comment by fpliger** [comment]
this is now supported with the new charts..
