### ISSUE TITLE
Shiny bindings for rbokeh

### ISSUE THREAD

**Issue by markriseley** [bokeh/bokeh#1937]
Now that you've ported bokeh to R (thanks, the built in interactive controls are great!), would it be possible to add Shiny bindings to enable interactive dashboards eg like this:

http://shiny.rstudio.com/gallery/movie-explorer.html

This page might be what you need to get you started, I'm not an expert in this stuff though:
http://rpackages.ianhowson.com/cran/htmlwidgets/man/htmlwidgets-shiny.html

**Comment by timelyportfolio** [comment]
Yes we plan to fully integrate with Shiny.  See issue https://github.com/bokeh/rbokeh/issues/25.  Please file issues for rBokeh there.  Thanks.

**Comment by markriseley** [comment]
Great news, thanks.

**Comment by bryevdv** [comment]
This should go on the rbokeh issue tracker (and is) :) Closing.

**Comment by timelyportfolio** [comment]
@markriseley basic shiny support should now be added.  Let us know how it works.

**Comment by markriseley** [comment]
Thanks, I'll give it a try.

**Comment by markriseley** [comment]
I installed it just now, and tried Joe's minimal app <#
https://github.com/bokeh/rbokeh/blob/17a62226f931e1d3f6e6a7605ee1b08dcae61f1c/man-roxygen/ex-shiny.R>
with the following error:

Listening on http://127.0.0.1:5279
Error in normalizePath(path.expand(path), winslash, mustWork) :

path[1]="C:\Users\MARKRI~1\AppData\Local\Temp\RtmpMRBGKT\widgetbinding19c6f0e4579":
The system cannot find the path specified

Here is session info (win 8.1 machine)

> devtools::session_info()
Session info
--------------------------------------------------------------------------
 setting  value
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32
 ui       RStudio (0.99.283)
 language (EN)
 collate  English_United Kingdom.1252
 tz       Europe/London

Packages
------------------------------------------------------------------------------
 package     * version     date       source
 bitops      * 1.0-6       2013-08-17 CRAN (R 3.1.2)
 devtools    * 1.7.0       2015-01-17 CRAN (R 3.1.2)
 digest      * 0.6.8       2014-12-31 CRAN (R 3.1.2)
 evaluate    * 0.5.5       2014-04-29 CRAN (R 3.1.2)
 formatR     * 1.0         2014-08-25 CRAN (R 3.1.2)
 hexbin      * 1.27.0      2014-08-09 CRAN (R 3.1.2)
 htmltools   * 0.2.6       2014-09-08 CRAN (R 3.1.2)
 htmlwidgets   0.3.2       2014-12-09 CRAN (R 3.1.2)
 httpuv      * 1.3.2       2014-10-23 CRAN (R 3.1.2)
 httr        * 0.6.1       2015-01-01 CRAN (R 3.1.2)
 knitr       * 1.9         2015-01-20 CRAN (R 3.1.2)
 lattice     * 0.20-29     2014-04-04 CRAN (R 3.1.2)
 magrittr    * 1.5         2014-11-22 CRAN (R 3.1.2)
 maps        * 2.3-9       2014-09-22 CRAN (R 3.1.2)
 mime        * 0.2         2014-09-26 CRAN (R 3.1.2)
 R6          * 2.0.1       2014-10-29 CRAN (R 3.1.2)
 rbokeh        0.2         2015-03-07 Github (bokeh/rbokeh@17a6222)
 Rcpp        * 0.11.4      2015-01-24 CRAN (R 3.1.2)
 RCurl       * 1.95-4.5    2014-12-06 CRAN (R 3.1.2)
 RJSONIO     * 1.3-0       2014-07-28 CRAN (R 3.1.2)
 rstudioapi  * 0.2         2014-12-31 CRAN (R 3.1.2)
 shiny         0.11.1.9000 2015-02-18 Github (rstudio/shiny@fd39075)
 stringr     * 0.6.2       2012-12-06 CRAN (R 3.1.2)
 xtable      * 1.7-4       2014-09-12 CRAN (R 3.1.2)

**Comment by markriseley** [comment]
And when I source the file instead of running I get this:

Error in tag("div", list(...)) : could not find function "rbokehOutput"

The shiny binding functions aren't appearing in the package or the manual
pages of what I just installed.

**Comment by bryevdv** [comment]
@markriseley as previously mentioned, this should go on the rbokeh issue tracker:

https://github.com/bokeh/rBokeh/issues

**Comment by markriseley** [comment]
Ok will add it there.

**Comment by bryevdv** [comment]
Thanks!
