### ISSUE TITLE
Issues with GMapPlot and circle glyphs combination

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1938]
As reported on [m.l.](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/bokeh/nZOdpPZ640Y/IIUgeWwExcYJ) mapping a large number (300,000 circles) on GMapPlot presents a few issues (able to reproduce locally):
1. Reset tool: currently this resets the lon/lat (x,y) values to 0.0, and 0.0, at original zoom level: would be good to over-ride these values to the originally specified lat. lon. set in GMapOptions.
2. Box Zoom Tool: this appears to just centre the plot over the centre point of the box zoom, without changing the zoom level of the map.
3. Pan bug? When I pan, the glyphs (in my case circles), can become dissociated from their correct map location.
4. Color scale: Is it possible to add a colour scale legend relating to the colours assigned to my circle glyphs?
5. Resize: dissociate circles from their original location.

Link to [notebook](http://nbviewer.ipython.org/github/benlaken/ECCO/blob/master/iPlots_xyGMap.ipynb)

link to original [code](https://github.com/benlaken/ECCO)

**Comment by sidpat** [comment]
Facing same issue. Any update on this?

**Comment by bryevdv** [comment]
I believe the recent GMap work will have resolved these issues (however for 300k points, probably better to use Datashader now that it is an option) Please re-open with test code if there are reproducible issues
