### ISSUE TITLE
widget/controls integration

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#194]
It would nice to link fields to controls so that when possible updates can happen on the js side. Simple things like colormap choosing using dropdown, that can happen entirely on the browser side.

**Comment by datnamer** [comment]
+1

**Comment by birdsarah** [comment]
@brevdv - is this done with callbacks?

**Comment by bryevdv** [comment]
I think so, enough to close this anyway,

**Comment by bryevdv** [comment]
(I had originally in mind something a little different but I'm not sure it's worth pursuing now)
