### ISSUE TITLE
Changing line_color interactively

### ISSUE THREAD

**Issue by theonlykk** [bokeh/bokeh#1942]
The examples show that one can change the data on a plot using the text box entry or a drop down menu.  Is it possible to change the line_color on a chart in the same manner?

**Comment by bryevdv** [comment]
You are using a plot on the `bokeh-server`? You can change the attribute on the plot object then `push` the object back to the server, just like in the examples that update data. Let me know if you can't get that working (I am at a conference today or I'd try to provide more)

**Comment by theonlykk** [comment]
Hi Bryan

Many thanks for the quick response!

Can I show you my attempt at the code so far?

I also tried changing plot.outline_line_color but with no luck.

I noticed that if I printed the initial line_color value, {u'value':
u'indigo'} was returned, so I tried passing a dict as the colour as well.

I am able to update the title, so the input value is being read, i just
cant seem to make that change extend to the line_color.

I have basically hacked away at the slider_app code and run the script
using bokeh-server --script foo.py

Again, many thanks for helping with this!

Kind regards

Khalid




On Thu, Feb 19, 2015 at 11:25 AM, Bryan Van de Ven <notifications@github.com
> wrote:

> You are using a plot on the bokeh-server? You can change the attribute on
> the plot object then push the object back to the server, just like in the
> examples that update data. Let me know if you can't get that working (I am
> at a conference today or I'd try to provide more)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bokeh/bokeh/issues/1942#issuecomment-75082823>.
>

import logging
logging.basicConfig(level=logging.DEBUG)

import numpy as np
from bokeh.plotting import *
#from bokeh.plotting import line,figure,multi_line
from bokeh.models import Plot, ColumnDataSource, Range1d
from bokeh.properties import Instance
from bokeh.server.app import bokeh_app
from bokeh.server.utils.plugins import object_page
from bokeh.models.widgets import HBox, Slider, TextInput, VBoxForm
from bokeh.models.glyphs import Circle, Text,Line,Segment,Rect
from collections import OrderedDict

import pandas as pd
from bokeh.charts import TimeSeries

class SlidersApp(HBox):
    extra_generated_classes = [["SlidersApp", "SlidersApp", "HBox"]]

    inputs = Instance(VBoxForm)

    text = Instance(TextInput)
    main_colour_text = Instance(TextInput)
	
    source = Instance(ColumnDataSource)

    plot = Instance(Plot)

    @classmethod
	
    def create(cls):
        """
        This function is called once, and is responsible for
        creating all objects (plots, datasources, etc)
        """
        obj = cls()

        obj.source = ColumnDataSource(data=dict(x=[], y=[]))


        obj.text = TextInput(
            title="title", name='title', value='MSFT'
        )

        obj.main_colour_text = TextInput(
            title="colour", name='colour', value='indigo'
        )
        toolset = "crosshair,pan,reset,resize,save,wheel_zoom"
		
        x = [0, 1, 2, 3, 4, 5,  6,  7, 8,   9, 10]
        y = [0, 8, 2, 4, 6, 9, 15, 18, 19, 25, 28]
        source = ColumnDataSource(data=dict(x=x, y=y))
        x_min = 0
        x_max = 10
        y_min = 0
        y_max = 30

        plot = figure(x_range=[x_min, x_max],y_range=[y_min, y_max],outline_line_color=obj.main_colour_text.value,y_axis_label = obj.main_colour_text.value,title=obj.text.value)

        plot.line("x", "y", source=source,line_color=obj.main_colour_text.value)
		
        obj.plot=plot
		
        obj.update_data()
        
        obj.inputs = VBoxForm(
            children=[
      
                obj.text,obj.main_colour_text
            ]
        )

        obj.children.append(obj.inputs)
        obj.children.append(obj.plot)


        return obj
		
    def setup_events(self):
        super(SlidersApp, self).setup_events()
        if not self.main_colour_text:
            return
        self.main_colour_text.on_change('value', self, 'input_change')

        if not self.text:
            return
        self.text.on_change('value', self, 'input_change')


	
    def input_change(self, obj, attrname, old, new):

        self.update_data()
        self.plot.title = self.text.value
     
        cc = {u'value': u'indigo'}
        cc[u'value']=self.main_colour_text.value
       
        self.plot.outline_line_color=cc
      #  self.plot.outline_line_color=str(self.main_colour_text.value)
        self.plot.title=str(self.main_colour_text.value)
       

    def update_data(self):
     

        main_colour=str(self.main_colour_text.value)
       
        self.plot.outline_line_color=self.main_colour_text.value
       
        cc = {u'value': u'indigo'}
        cc[u'value']=self.main_colour_text.value

        self.plot.outline_line_color=cc
     

  

# The following code adds a "/bokeh/sliders/" url to the bokeh-server. This
# URL will render this StockApp. If you don't want to serve this applet from
# a Bokeh server (for instance if you are embedding in a separate Flask
# application), then just remove this block of code.
@bokeh_app.route("/bokeh/sliders/")
@object_page("sin")
def make_object():
    app = SlidersApp.create()
    return app

**Comment by bryevdv** [comment]
reposting with formatting:
```
python
import logging
logging.basicConfig(level=logging.DEBUG)

import numpy as np
from bokeh.plotting import *
#from bokeh.plotting import line,figure,multi_line
from bokeh.models import Plot, ColumnDataSource, Range1d
from bokeh.properties import Instance
from bokeh.server.app import bokeh_app
from bokeh.server.utils.plugins import object_page
from bokeh.models.widgets import HBox, Slider, TextInput, VBoxForm
from bokeh.models.glyphs import Circle, Text,Line,Segment,Rect
from collections import OrderedDict

import pandas as pd
from bokeh.charts import TimeSeries

class SlidersApp(HBox):
    extra_generated_classes = [["SlidersApp", "SlidersApp", "HBox"]]

    inputs = Instance(VBoxForm)

    text = Instance(TextInput)
    main_colour_text = Instance(TextInput)
	
    source = Instance(ColumnDataSource)

    plot = Instance(Plot)

    @classmethod
	
    def create(cls):
        """
        This function is called once, and is responsible for
        creating all objects (plots, datasources, etc)
        """
        obj = cls()

        obj.source = ColumnDataSource(data=dict(x=[], y=[]))


        obj.text = TextInput(
            title="title", name='title', value='MSFT'
        )

        obj.main_colour_text = TextInput(
            title="colour", name='colour', value='indigo'
        )
        toolset = "crosshair,pan,reset,resize,save,wheel_zoom"
		
        x = [0, 1, 2, 3, 4, 5,  6,  7, 8,   9, 10]
        y = [0, 8, 2, 4, 6, 9, 15, 18, 19, 25, 28]
        source = ColumnDataSource(data=dict(x=x, y=y))
        x_min = 0
        x_max = 10
        y_min = 0
        y_max = 30

        plot = figure(x_range=[x_min, x_max],y_range=[y_min, y_max],outline_line_color=obj.main_colour_text.value,y_axis_label = obj.main_colour_text.value,title=obj.text.value)

        plot.line("x", "y", source=source,line_color=obj.main_colour_text.value)
		
        obj.plot=plot
		
        obj.update_data()
        
        obj.inputs = VBoxForm(
            children=[
      
                obj.text,obj.main_colour_text
            ]
        )

        obj.children.append(obj.inputs)
        obj.children.append(obj.plot)


        return obj
		
    def setup_events(self):
        super(SlidersApp, self).setup_events()
        if not self.main_colour_text:
            return
        self.main_colour_text.on_change('value', self, 'input_change')

        if not self.text:
            return
        self.text.on_change('value', self, 'input_change')


	
    def input_change(self, obj, attrname, old, new):

        self.update_data()
        self.plot.title = self.text.value
     
        cc = {u'value': u'indigo'}
        cc[u'value']=self.main_colour_text.value
       
        self.plot.outline_line_color=cc
      #  self.plot.outline_line_color=str(self.main_colour_text.value)
        self.plot.title=str(self.main_colour_text.value)
       

    def update_data(self):
     

        main_colour=str(self.main_colour_text.value)
       
        self.plot.outline_line_color=self.main_colour_text.value
       
        cc = {u'value': u'indigo'}
        cc[u'value']=self.main_colour_text.value

        self.plot.outline_line_color=cc
     

  

# The following code adds a "/bokeh/sliders/" url to the bokeh-server. This
# URL will render this StockApp. If you don't want to serve this applet from
# a Bokeh server (for instance if you are embedding in a separate Flask
# application), then just remove this block of code.
@bokeh_app.route("/bokeh/sliders/")
@object_page("sin")
def make_object():
    app = SlidersApp.create()
    return app
```

**Comment by bryevdv** [comment]
@hhuuggoo can you comment? It appears updates to the data source triggers the plot to update but not other attributes. Is there a way to force an update?

**Comment by hhuuggoo** [comment]
Does update_data get called?  Or is the plot just not responding to the attribute change.  Usually this is because we forgot to bind events properly on the JavaScript side

**Comment by theonlykk** [comment]
I think the new colour value does get called as I use it to populate the title. 
Sent from my BlackBerry device on the Rogers Wireless Network

-----Original Message-----
