### ISSUE TITLE
More Broken Doc Links

### ISSUE THREAD

**Issue by alanhdu** [bokeh/bokeh#1945]
On http://bokeh.pydata.org/en/latest/docs/dev_guide/process.html, both BEP links are broken.

**Comment by almarklein** [comment]
In the doc sources they links are correct. Do we need to trigger a doc build?

**Comment by almarklein** [comment]
https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/dev_guide/process.rst

No wait. This is weird:
* The link in the rst file: `https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management`
* When I copy the link when rendered as html: `https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/dev_guide/BEP1`

I get the latter even when viewing the rst file as rendered by github.

**Comment by almarklein** [comment]
Ah, the link is malformatted. It is sort of formatted as an inline link, except that the address is defined below. http://sphinx-doc.org/rest.html#hyperlinks
