### ISSUE TITLE
tests scripts enhancements.

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1949]
* [ ] the test-matrix script needs to support dev build from the bokeh Binstar channel
* [ ] the interactive-tester script needs to accept an specific location for examples (use-case, a conda env containing a dev build which is shipped with the Examples folder, so I want to pass this path: `/media/datos/miniconda3/envs/test34/Examples/bokeh`)

ping @Maggie-M

**Comment by fpliger** [comment]
@Maggie-M I've opened the PR with the improvements I've mentioned yesterday. I'm assigning this issue to me as I plan to add the support for specific location for examples on that PR later today..
