### ISSUE TITLE
Develop installation fails: No such file or directory: '/usr/lib/python3.4/site-packages/bokeh.pth'

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#1953]
I am on Ubuntu Linux 14.04. setup.py has a function `getsitepackages()` to get the location of the site-packages. It produces `/usr/lib/python3.4/site-packages` on my machine, which should have been `/usr/local/lib/python3.4/dist-packages`.

AFAIK: there's two ways to get the site-packages dir:
* `sysconfig.get_path('purelib')`
* `site.getsitepackages()[0]`

Can't we just use one of these?

**Comment by almarklein** [comment]
Correction: `sysconfig.get_path()` does not work on pypy. and in Jython there is no `site.getsitepackages()`.

**Comment by damianavila** [comment]
[damian@damian-S400CA][Desarrollos]$ /usr/bin/python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import testi
>>> testi.getsitepackages()
['/usr/lib/python3.4/site-packages', '/usr/lib/site-python', '/usr/python3.4/lib-dynload', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.4/dist-packages', '/usr/lib/dist-python']
>>> 

Is there :wink:, I would suggest try to recover it from the list...
But, you just submitted something... so I will take a look at your PR :stuck_out_tongue_winking_eye:
