### ISSUE TITLE
cannot plot bar plot from pandas

### ISSUE THREAD

**Issue by chanansh** [bokeh/bokeh#1955]
I am trying to export a simple bar plot from pandas to bokeh but it seems this wasn't implemented yet.
Is there a work around?
```
import numpy as np
import pandas as pd
from bokeh import mpl
from bokeh.plotting import show


df = pd.DataFrame({'a': [1,2], 'b': [3,4]}, index = ['one','two'])
#df.plot() - works
df.plot(kind='bar') # -   bokeh\mplexporter\renderers\base.py", line 363, in draw_path  raise NotImplementedError()
show(mpl.to_bokeh(name="dataframe"))
```

**Comment by birdsarah** [comment]
Hi,

I'm afraid I'm not familiar with the matplotlib interface.

However, a simple example of creating a Bar chart with a dataframe is
available here:
https://github.com/bokeh/bokeh/blob/master/examples/charts/bar.py#L35


In it's very simplest form you can do:

    import pandas as pd
    from bokeh.charts import Bar

    df = pd.DataFrame({'a': [1,2], 'b': [3,4]}, index = ['one','two'])
    Bar(df, filename='test.html').show()

Hope this helps, I'm sure someone else will be able to chip in on mpl.

Sincerely,

Sarah Bird

**Comment by bryevdv** [comment]
Hi Chanash,

As Sarah notes, the easiest thing is to just use the Bokeh charts interface, where it is a one-liner. Our MPL support comes from a third party lib, mplexporter, which is not fully complete. Any bug requests though, should go on its GH tracker:

    https://github.com/mpld3/mplexporter

Thanks,

Bryan

**Comment by bs1234** [comment]
Is there currently a simple way to plot a bokeh Bar chart from a pandas dataframe (where the index in the dateframe is timestamps?)

thanks

**Comment by rothnic** [comment]
@bs1234, right now you'd just need to convert the timestamp to the string representation you'd want to see in the chart. Probably should provide some special handling of timestamps to avoid issues.

**Comment by bs1234** [comment]
Many thanks. obvious in hindsight but was banging my head against a brick wall for a while.

I'd love to see the x values for Bar use pandas dataframe index by default, if a dataframe is passed in (with corresponding handling of date format if needed)

I seem to get hung up time and again regarding the correct format of input data for bokeh...
