### ISSUE TITLE
Two instances of autoload_server??

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#1956]
Hi, is it intentional to have two versions of autoload_server in embed.py? If so, they need different names, as the second one is currently overwriting the first:

https://github.com/bokeh/bokeh/blob/master/bokeh/embed.py#L176
````python
def autoload_server(plot_object, session):
    ''' Return a script tag that can be used to embed Bokeh Plots from
        a Bokeh Server....'''
````
https://github.com/bokeh/bokeh/blob/master/bokeh/embed.py#L206
````python
def autoload_server(plot_object, session, public=False):
    ''' Return a script tag that can be used to embed Bokeh Plots from a Bokeh Server.
        The data for the plot is stored on the Bokeh Server. ....'''
````

**Comment by bryevdv** [comment]
Looks like a merge conflict error.

**Comment by bryevdv** [comment]
The second one (with the `public` arg) is the correct one, although it needs its docstring improved.

**Comment by bryevdv** [comment]
Thanks for spotting this, @birdsarah
