### ISSUE TITLE
Throw exception if nonexistent keyword arguments are given

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#1960]
There was a typo in the line `glyphs/line.py` example where it said `line_with` instead of `line_width`. Not a big deal in this case, but can lead to problems that are hard to debug. My feeling is that we should raise an error, or at least show a warning when an invalid keyword argument is given.

**Comment by fpliger** [comment]
here is the file

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/line.py

**Comment by almarklein** [comment]
I fixed the typo in #1951 BTW.

**Comment by almarklein** [comment]
Continuing discussion from #1972 ...

### Summary

Keyword arguments provided by the user that are not properties are silently ignored. I tried to fix that in #1972, but there are places in the code, where we just collect a bunch of key-value pairs and throw that the `plot.glyph_x()` function, because *some* of these functions may accept it. (e.g. here https://github.com/bokeh/bokeh/blob/master/bokeh/transforms/ar_downsample.py#L452)

### Possible solutions

I think there's two directions to go: 

* A: the code making the function call should only pass keywords that it knows are valid.
* B: we allow passing keyword arguments that *can* safely be silently ignored (essentially delaying the checking of validity to a part of the code that is more aware of what kwargs are valid). 

About *how* to fix this ...

* A can probably be implemented by making each function specify what kwargs it accepts, as propsed by @bryevdv using a decorator, and the calling code can inspect that and filter arguments by it.
* We can get B by adding a keyword argument (e.g. `potential_kwags`) that is a dict with kwargs that can be applied if valid, and ignored otherwise

A seems more generic but more work (and needs more thought on the details). B will probably get the job done on the short term (I can probably do this in #1972).

Thoughts?

**Comment by almarklein** [comment]
@bryevdv your thoughs? If I continue on #1972, I'd better do it sooner than later (or it'll drift away from master).

**Comment by bryevdv** [comment]
@almarklein I don't like adding a named arg because it muddies the interface and is a weird thing we have to explain. Here is my proposal:
```
def kw_cull(*kw_names):
    def decorator(func):
        def wrapper(*args, **kw):
            kw["_culled"] = { name : kw.pop(name) for name in kw_names }
            return func(*args, **kw)
        return wrapper
    return decorator

@kw_cull("foo", "bar")
def func(**kw):
    print("kw", kw)
```
Then:
```
In [19]: func(foo=10, bar=20, baz=30)
kw {'_culled': {'bar': 20, 'foo': 10}, 'baz': 30}
```
Or something very like it. (e.g., maybe `kw_names` should really be a dict with default values, needs error checking, etc) Key observations:
* functions like the ones we are trying to "fix" are responsible for `pop` the culled kwargs off. This is a pattern we can document.
* the decorator can annotate the wrapped function later and this can be used to generate better fun signatures in the docs
* we punt on the rare cases where a function has to initialize to `HasProps` --- it is up to the function to split up `kwargs` appropriately.

**Comment by almarklein** [comment]
Isn't that about the same as:

    def func(foo=10, bar=20, **kwargs):
        print(foo, bar, kwargs)

Looking at this again. We have something like this:
        
    def _glyph_function(glyphclass, dsnames, argnames, docstring, xfields=["x"], yfields=["y"]):
    
        def func(plot, *args, **kwargs):
            
            # We pop some kwargs that we need
            source = kwargs.pop('source', None)
            legend_name = kwargs.pop("legend", None)
            
            # We set some kwargs (line_color, fill_color, etc.)
            kwargs.update(_materialize_colors_and_alpha(glyphclass, kwargs))
            
            # Extract kwargs for renderer
            renderer_kwargs = pop_items(kwargs, 'x_range_name', 'y_range_name', name=None)
            
            # We pass all the rest to the Glyph class, but we cannot simply expose that as a decorator
            glyph = glyphclass(**kwargs)
            
            # Create renderer with the extracted kwargs
            glyph_renderer = GlyphRenderer(..., **renderer_kwargs)
    
    
    # In ar_downsample.py
    def replot(plot, ..., plot_opts=None, **kwargs):
        
        # Constuct figure options by popping a few known names
        fig_opts = {}
        fig_opts['plot_width'] = kwargs.pop('plot_width', plot.plot_width)
        # ...
        
        # Construct plot options. We don't know what gets in there
        plot_opts = plot_opts or {}
        plot_opts.update(mapping(src))
        
        # Create plot, pass fig_opts as kwargs to the glyph function
        new_plot = figure(**fig_opts)
        if shader.out == "image":
            new_plot.image(source=src, **plot_opts)  # <===
        elif shader.out == "image_rgb":
            new_plot.image_rgba(source=src, **plot_opts)  # <===
        ...

In `replot()` we do not know what kwargs are in `plot_opts`, they are just passed to `func()`. But  `func()` does not know (at "compile time") what the glyph func can accept. I looked into decorating it to allow this, but it would need to collect the names from what it uses itself, its `glyphclass`,              'color', 'line_color', 'text_color', 'alpha', 'fill_alpha', 'line_alpha', 'text_alpha', then the same list for the `nonselection_x`, and then everything that can end in `_unit`. I have a feeling this quickly becomes complex (can we even collect all names that can have a pairing `x_unit`?).

Since this seems to be an isolated case, my proposal is thus to pass the `plot_opts` using a special argument of which only valid values are used, and others discarded.

**Comment by bryevdv** [comment]
I think you have the sense of my suggestion reversed. I am not talking about using a decorator to pop of the tens of glyph parameters, I was suggesting popping of the three or four that *aren't*.  FWIW we should not do anything based on making any AR code better or different, we are very likely going to move AR out of bokeh and into its own project so it can progress more independently. As for just adding named kwarg parameters to the `func` inside `_glyph_function` if that can be made to work and that solves the issue in all non-AR cases then sure let's just do that.

**Comment by almarklein** [comment]
The idea is to somehow expose information on what kwargs are valid, so that calling code (like AR) can filter its properties, right? So one way or another, all these "pseudo props" need to be taken into account.

>  As for just adding named kwarg parameters to the func inside _glyph_function if that can be made to work and that solves the issue in all non-AR cases then sure let's just do that. 

No it won't. Because of what I said above.

**Comment by bryevdv** [comment]
Why not? Just add `source`, `legend`, `x_range_name`, `y_range_name` and `name` as args with default values to `func`? 
```
def _glyph_function(glyphclass, dsnames, argnames, docstring, xfields=["x"], yfields=["y"]):

    def func(plot, *args, source=None, legend=None, 
             x_range_name="default", y_range_name="default", 
             name=None, **kwargs):

        # We set some kwargs (line_color, fill_color, etc.)
        kwargs.update(_materialize_colors_and_alpha(glyphclass, kwargs))

        # Extract kwargs for renderer
        renderer_kwargs = dict(
            x_range_name=x_range_name, 
            y_range_name=y_range_name, 
            name=name
        )

        # We pass all the rest to the Glyph class, but we cannot simply expose that as a decorator
        glyph = glyphclass(**kwargs)

        # Create renderer with the extracted kwargs
        glyph_renderer = GlyphRenderer(..., **renderer_kwargs)
```
What am I missing? Like I said, remove any AR code form this consideration.

**Comment by bryevdv** [comment]
I don't see the issue as one of advertising anything to outside callers, BTW. I see it as a specification issue of for the function under question. How do we specify the inputs to the function so it can leverage the properties system to the best ability. FWIW I do think this is important to fix up but if we are not achieving consensus then we should probably table this before it devolves into bike shedding, and come back to it from a more requirements oriented starting point later.

**Comment by almarklein** [comment]
Hehe, I am eager to fix this in whatever way you think seems fit. I think we're simply not fully understanding each-other, in part because this problem is rather complex :)

I think the code has already improved, and specifying `source`, `legend` et. al. as args with default values will further improve the specification. But there will still be errors in the tests, because the AR code passes kwargs that are not valid. How can we deal with that?

**Comment by bryevdv** [comment]
OK, thanks for jogging my memory I had actually forgotten that part of the problem. Since we are in agreement that that version of `func` is an improved for bokeh in general, I guess this statement is true: I don't really care what happens to `replot` to make it work with the new version, especially if that is the only problem area. Can you elaborate on your `plot_opts` idea a little more?

**Comment by almarklein** [comment]
The idea would be for `func` to have a `potential_props` arg, which would have to be a dict. The `func()` would filter out the arguments that are valid properties and pass them to the `glyphclass`. It would be a sort of kwargs-that-are-not-checked, which other code (e.g. AR) can use to send automatically collected kwargs.

**Comment by bryevdv** [comment]
I apologize, I am still missing something. I think I'll need to see some actual code to think about it more clearly.

**Comment by almarklein** [comment]
Something like this:

    func(..., potential_props):

        ...
        real_props = [(name, potential_prop[name]) for name in potential_props if name in valid_glyph_props]
      kwargs.update(real_props)

And the code in AR would simply pas `plot_props` as potential_props.

**Comment by bryevdv** [comment]
OK where does `valid_glyph_props` come from? 
```
In [3]: Circle.properties()
Out[3]: 
{'fill_alpha',
 'fill_color',
 'line_alpha',
 'line_cap',
 'line_color',
 'line_dash',
 'line_dash_offset',
 'line_join',
 'line_width',
 'name',
 'radius',
 'radius_dimension',
 'session',
 'size',
 'tags',
 'visible',
 'x',
 'y'}
```
Note that the `_units` ones don't show up there, unfortunately. I think we are stuck with the fact that `replot` needs to be made to not pass junk, especially if it is the only offending culprit in this way.

**Comment by almarklein** [comment]
We could actually use `_materialize_colors_and_alpha` and `_match_data_params` to convert the peudo-properties to real properties, although this complicates things; should we use the line_color from kwargs or from potential_props?

Maybe we should ask: what is the precise purpose of `plot_opts` in the AR code? *should* they overwrite units, colors, etc? I don't really see what `plot_opts.update(mapping(src))` is supposed to do.

**Comment by bryevdv** [comment]
I am pretty wholly unfamiliar with the AR codebase. @JosephCottam can you make a few comments?

**Comment by almarklein** [comment]
@JosephCottam Let me give you a summary. We're trying to change the code such that invalid property names for glyphs result in an error. One problem we run into, is that the AR code passes a dict with options to the glyph function, which contains props that are not valid. It's about the `plot_opts` here: https://github.com/bokeh/bokeh/blob/master/bokeh/transforms/ar_downsample.py#L454 This dict is passed to the glyph function a few lines below.

The main questions are what the purpose is, and what properties this is intended to overwrite.

**Comment by bryevdv** [comment]
FYI changes I'd like to make in #2449 seem to solve this problem. I am seeing the AR test failures tho. Given that we don't really have @JosephCottam 's time to maintain the current AR work in Bokeh, and we had talked about moving AR outside of Bokeh proper, I think we need to make a decision. #2449 fixes a problem that has to be resolved for rbokeh to adopt the new JS version, makes the morass of plotting helper functions much better and improves error reporting.  We could just disable the AR tests and/or remove AR functionality at this point. Or we could try to fix up the AR code enough to pass the tests and work with these changes. I am not sure what would be involved tho. @bokeh/dev

**Comment by birdsarah** [comment]
My opinion would be to move it out. There are talks around that aren't that old that highlight the AR and I know I was excited about it then got into the code and realized it wasn't quite there yet. I think having it continue at its own pace in a separate repo sends a useful message.

**Comment by damianavila** [comment]
I agree with @birdsarah comment here... if it is too much work before the release, we can just disable the tests (or remove it) and let the split for later... but eventually, the split should happen...
