### ISSUE TITLE
Problems when sizing a plot too small

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#1965]
If you select resize on a plot and then drag your mouse to the left as far as you can, it becomes impossible to expand or resize the plot any further.

![screen shot 2015-02-23 at 1 51 39 pm](https://cloud.githubusercontent.com/assets/1417520/6335778/83f7c74e-bb63-11e4-8aff-8923539b54ac.png)

**EDIT** This behavior is also reproducible if you drag your mouse pointer outside of the page while resizing.

![screen shot 2015-02-23 at 2 06 36 pm](https://cloud.githubusercontent.com/assets/1417520/6336107/eced8052-bb65-11e4-8dc4-8da88f07e539.png)

In some instances, this will cause the plots to disappear entirely.

**Comment by mattpap** [comment]
@Maggie-M, please report JS console errors next time, those pretty important to understand what's going on here.

**Comment by mattpap** [comment]
This issue is related to #1723 and perhaps other. JS console shows "unknown constraint" or "unsatisfiable constraint" errors from kiwi.js.

**Comment by Maggie-M** [comment]
Thanks, I will be sure to include the console errors next time!

**Comment by bryevdv** [comment]
There is some odd behaviour now with the plot vertical dimension snapping smaller as the width gets very small, but the situation is no longer un-recoverable like it was previously, the plot can still be resized again.

**Comment by bryevdv** [comment]
closing, resize tool is gone
