### ISSUE TITLE
GlyphRenderer missing in bokeh.objects

### ISSUE THREAD

**Issue by ThomasLecocq** [bokeh/bokeh#197]
There seems to be a missing Renderer in the objects:

``` python
from bokeh.objects import GlyphRenderer
ImportError: cannot import name GlyphRenderer
```

which is used in glyph_data_embed.

**Comment by akashbing** [comment]
i am using 0.12 version of bokeh 
now why this error is coming have you guys change the name ??
tell me alternative 
from bokeh.objects import *
ImportError: No module named objects

**Comment by bryevdv** [comment]
@akashbing `bokeh.objects` was removed *years ago*. In any case the tracker is reserved for bug reports and feature discussions. For support questions (such as yours) please go to the public mailing list https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
