### ISSUE TITLE
Tools passed to Histogram do not show in iPython notebook

### ISSUE THREAD

**Issue by borguz** [bokeh/bokeh#1976]
Here is sample code:
```python
import numpy as np
from bokeh.plotting import output_notebook
from bokeh.charts import Histogram
from bokeh.plotting import show

output_notebook()

data={'values':list(np.random.normal(0, 1, 1000))}
hist=Histogram(data, bins=30,tools="pan,wheel_zoom,box_zoom,select",notebook=True)
hist.show()
```
Box_zoom tool will not show in the resulting embedded plot in iPython notebook.

**Comment by damianavila** [comment]
You are probably using an old version of Bokeh, please install the latest one (0.8.1) and this piece of code should work:

```python
import numpy as np
from bokeh.plotting import output_notebook
from bokeh.charts import Histogram
from bokeh.plotting import show

output_notebook()

data={'values':list(np.random.normal(0, 1, 1000))}
hist=Histogram(data, bins=30,tools="pan,wheel_zoom,box_zoom,box_select",notebook=True)
show(hist)
```

Cheers.

**Comment by borguz** [comment]
That's an improvement, but this is what I see now (Bokeh 0.8.1, ie11):
![bokeh](https://cloud.githubusercontent.com/assets/11183544/6398629/bc62a05a-bda1-11e4-82cb-afe51bb49a38.jpg)

**Comment by damianavila** [comment]
Can you clean you browser cache, restart the notebook kernel and reloading the notebook and check if you get the same? I guess there is some cached js somewhere....

**Comment by borguz** [comment]
That worked, thank you.
