### ISSUE TITLE
Restore glyph/trail.py (and fix the hover not working)

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#1978]
In the map, the hover tool does not seem to work... 
I don't see errors in the js console, just a warn (with logging info) about `Bokeh: 'point' selection not available on Line renderer`...

**Comment by mattpap** [comment]
I'm pretty sure that it never worked and waited for implementing hit testing on lines.

**Comment by damianavila** [comment]
Let's remove the hover then and restore it, I will make the change...
