### ISSUE TITLE
HoverTool issues (0.8.1) 

### ISSUE THREAD

**Issue by km12321** [bokeh/bokeh#1981]
Congrats on releasing version 0.8.1 yesterday, exciting stuff!

I am noticing an issue with HoverTool on our end– any attributes referenced with '$' or '@' show up as '???' in the tooltip. This occurs across all examples, both static HTML pages and server ones. I am using FF v 31.3.0 on CentOS - Looks like analytics.js is the culprit here as I am seeing this error in the browser console any time I hover over a point in this example (http://bokeh.pydata.org/en/latest/tutorial/solutions/gallery/hover.html) : Bokeh: 'point' selection not available on Text renderer.

Also, would it be possible for you to create a HoverTool feature which hovers over a line plot as you drag your mouse along the plot and displays a tooltip with values related to the particular point that is in line with the mouse? This feature would be neat to use alongside the Crosshair tool. 

Thanks for your help!

**Comment by bryevdv** [comment]
@km12321 The message about `Text` renderers can be safely ignored. Just to be clear, do you see the problem if you navigate to that actual link above? Does it fail with any other browsers? That link works for me on every browser I have tried. 

ping @mattpap

**Comment by km12321** [comment]
Yeah, the problem appears in both IE and FF when going to that link. I will try from OS X in a couple hours and get back to you.

Could this somehow be related to an internal firewall setting that is messing up JS bindings to column data source? Other things like tap tool work great for me, just for some reason HoverTool is not cooperating

Thanks

**Comment by bryevdv** [comment]
@km12321 I wouldn't think so, the data in this case is embedded directly in the document. It would be very useful to find some place this *does* work for you, so we can try to make a comparison. I am otherwise at a loss as to what is going on in your particular situation.

**Comment by mattpap** [comment]
@km12321, can you clear you browsers' caches and retry?

**Comment by km12321** [comment]
Tried clearing cache and still showing up as question marks - interestingly the fill color part has always worked, but the other fields do not

**Comment by mattpap** [comment]
Fill color uses different code path than the rest of `$` or `@` placeholders.

**Comment by km12321** [comment]
I have confirmed that this works on OS X on Safari, Chrome and FF, so it must be some sort of internal isssue on our end, or some sort of missing library/dependency

**Comment by bryevdv** [comment]
Hmm maybe a conflict of some sort? Bokeh should be shipping with all of tis required dependencies included but there may be some spillover. In fact, it may be related to this issue I am currently working on: https://github.com/bokeh/bokeh/pull/1991 BokehJS is (unintentionally) using a global jq in places, perhaps your environment is providing a conflicting one. We can certainly put out a dev build as soon as this PR is ready. In the mean time, if you know how to open the browser dev console, you could load the plot and report back the value of `window.$.fn.jquery`

**Comment by km12321** [comment]
Ah that is probably the culprit here - I am getting "1.8.3", and looks like you guys are using 2.x right?

**Comment by bryevdv** [comment]
actually I think we are using 1.11 but that still might be the issue. Let me try to finish up the PR I linked and get you a dev build to try out (it might be Monday, tracking down all our accidental global uses of `$` is going to be a pain)

**Comment by km12321** [comment]
Sounds good, thanks for all the help - maybe some involved sed command can do the trick here :)

**Comment by bryevdv** [comment]
I just merged the PR, a dev build should be available later tonight.

**Comment by damianavila** [comment]
The devel build is available on Binstar: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/Ymw4cMYeDCg

**Comment by km12321** [comment]
What is the right way to install this devel build?
I tried :
conda install -c https://conda.binstar.org/bokeh/channel/dev bokeh-0.8.2dev.52491359
conda install -c https://conda.binstar.org/bokeh/channel/dev bokeh0.8.2dev.52491359
and:
conda install -c https://conda.binstar.org/bokeh/channel/dev bokeh

With the former 2 I get an error saying that no such package exists and with the latter it installs 0.8.1-np19py27_0

Thanks

**Comment by bryevdv** [comment]
```
bryan@laptop (git:master) ~/work/bokeh/examples/plotting/file $ conda install -c bokeh bokeh
Fetching package metadata: ................
Solving package specifications: .
Package plan for installation in environment /Users/bryan/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.9.1                |           py34_0         167 KB
    bokeh-0.8.2dev.52491359    |       np19py34_1        13.7 MB
    ------------------------------------------------------------
                                           Total:        13.8 MB

The following NEW packages will be INSTALLED:

    bokeh:    0.8.2dev.52491359-np19py34_1

The following packages will be UPDATED:

    conda:    3.9.0-py34_0 --> 3.9.1-py34_0                
    greenlet: 0.4.4-py34_0 --> 0.4.5-py34_0                
    requests: 2.5.1-py34_0 --> 2.5.3-py34_0                

Proceed ([y]/n)? 
```

**Comment by bryevdv** [comment]
It's just the `conda` channel now, not `conda/channel/dev` apparently. I will make a quick PR to update those instructions. @damianavila we should probably just include the basic pip/conda commands to install right in the email.

**Comment by bryevdv** [comment]
Wait... actually the original instructions seem to work fine:
```
bryan@laptop (git:master) ~/work/bokeh/examples/plotting/file $ conda install -c bokeh/channel/dev bokeh
Fetching package metadata: ................
Solving package specifications: .
Package plan for installation in environment /Users/bryan/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.9.1                |           py34_0         167 KB
    bokeh-0.8.2dev.52491359    |       np19py34_1        13.7 MB
    ------------------------------------------------------------
                                           Total:        13.8 MB

The following NEW packages will be INSTALLED:

    bokeh:    0.8.2dev.52491359-np19py34_1

The following packages will be UPDATED:

    conda:    3.9.0-py34_0 --> 3.9.1-py34_0                
    greenlet: 0.4.4-py34_0 --> 0.4.5-py34_0                
    requests: 2.5.1-py34_0 --> 2.5.3-py34_0                

Proceed ([y]/n)? 
```

**Comment by bryevdv** [comment]
`conda install -c https://conda.binstar.org/bokeh/channel/dev bokeh` also works for me.

**Comment by bryevdv** [comment]
@km12321 not sure what is going on for you can you report your version of conda?

**Comment by km12321** [comment]
I am getting the following:

$ conda install -c https://conda.binstar.org/bokeh/channel/dev bokeh=0.8.2dev.52491359 
Fetching package metadata: Could not connect to http://repo.continuum.io/pkgs/pro/noarch/
Could not connect to http://repo.continuum.io/pkgs/pro/linux-64/
Could not connect to https://conda.binstar.org/bokeh/channel/dev/noarch/
Could not connect to http://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://conda.binstar.org/bokeh/channel/dev/linux-64/
Could not connect to http://repo.continuum.io/pkgs/free/linux-64/
......
Error: No packages found in current linux-64 channels matching: bokeh 0.8.2dev.52491359*

You can search for this package on Binstar with

    binstar search -t conda bokeh 0.8.2dev.52491359*


And when I do not specify version, it just reverts to 0.8.1:

$ conda install -c bokeh/channel/dev bokehFetching package metadata: Could not connect to http://repo.continuum.io/pkgs/pro/noarch/
Could not connect to http://repo.continuum.io/pkgs/pro/linux-64/
Could not connect to https://conda.binstar.org/bokeh/channel/dev/noarch/
Could not connect to https://conda.binstar.org/bokeh/channel/dev/linux-64/
Could not connect to http://repo.continuum.io/pkgs/free/noarch/
Could not connect to http://repo.continuum.io/pkgs/free/linux-64/
......
Solving package specifications: .
Package plan for installation in environment /home/mkogan/anac_install:

The following NEW packages will be INSTALLED:

    bokeh: 0.8.1-np19py27_0


Do these "Could not connect" issues have something to do with this possibly?

Thanks

**Comment by bryevdv** [comment]
@asmeurer @ilanschnell do you guys have any idea what is going on here? This seems like some conda version or configuration issue.

**Comment by bryevdv** [comment]
To be clear, the same command works fine for me:
```
bryan@laptop (git:master) ~/work/bokeh/sphinx $ conda install -c https://conda.binstar.org/bokeh/channel/dev bokeh=0.8.2dev.52491359
Fetching package metadata: ................
Solving package specifications: .
Package plan for installation in environment /Users/bryan/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.9.2                |           py34_0         2.6 MB
    bokeh-0.8.2dev.52491359    |       np19py34_1        13.7 MB
    ------------------------------------------------------------
                                           Total:        16.2 MB

The following NEW packages will be INSTALLED:

    bokeh:    0.8.2dev.52491359-np19py34_1

The following packages will be UPDATED:

    greenlet: 0.4.4-py34_0 --> 0.4.5-py34_0                
    numpy:    1.9.1-py34_0 --> 1.9.2-py34_0                

Proceed ([y]/n)? n

bryan@laptop (git:master) ~/work/bokeh/sphinx $ conda info
Current conda install:

             platform : osx-64
        conda version : 3.9.1
  conda-build version : not installed
       python version : 3.4.2.final.0
     requests version : 2.5.3
     root environment : /Users/bryan/anaconda  (writable)
  default environment : /Users/bryan/anaconda
     envs directories : /Users/bryan/anaconda/envs
        package cache : /Users/bryan/anaconda/pkgs
         channel URLs : http://conda.alpha.binstar.org/t/<TOKEN>/mutirri/channel/selenium/osx-64/
                        http://conda.alpha.binstar.org/t/<TOKEN>/mutirri/channel/selenium/noarch/
                        http://conda.alpha.binstar.org/t/<TOKEN>/mutirri/osx-64/
                        http://conda.alpha.binstar.org/t/<TOKEN>/mutirri/noarch/
                        http://conda.alpha.binstar.org/t/<TOKEN>/bokeh/channel/dev/osx-64/
                        http://conda.alpha.binstar.org/t/<TOKEN>/bokeh/channel/dev/noarch/
                        http://conda.alpha.binstar.org/t/<TOKEN>/bokeh/osx-64/
                        http://conda.alpha.binstar.org/t/<TOKEN>/bokeh/noarch/
                        http://conda.alpha.binstar.org/t/<TOKEN>/binstar/osx-64/
                        http://conda.alpha.binstar.org/t/<TOKEN>/binstar/noarch/
                        http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/osx-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/bryan/.condarc
    is foreign system : False
```

**Comment by km12321** [comment]
Here is some of my conda info dump:

platform : linux-64
conda version : 3.9.0
conda-build version : 1.8.2
python version : 2.7.9.final.0
requests version : 2.5.3

channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
config file : None
is foreign system : False


Maybe I should try to uninstall and reinstall conda?

**Comment by damianavila** [comment]
Maybe some proxy issue?? pinging @asmeurer @ilanschnell again :wink:

**Comment by ilanschnell** [comment]
Maybe an issue with switching over to https?

**Comment by bryevdv** [comment]
@km12321 were you ever able to test with the devbuild?

**Comment by migdard** [comment]
I have the same issue with 0.8.1. The (more or less) same code works fine with 0.6.1 but shows interrogation marks with this version. The example on the web also is broken for me with FF.

**Comment by bryevdv** [comment]
I believe this is the exact same problem: #2122 For everyone in that issue, upgrading to a more recent version of Firefox solved the problem. If upgrading Firefox does *not* solve the issue for you, please let us know. Unfortunately, we do not have the resources available to run this down any further.

**Comment by migdard** [comment]
I confirm that upgrading from FF 29.0.1 to 37.0.2 fixed it.
Thanks !
