### ISSUE TITLE
Normal RangeSlider needed.

### ISSUE THREAD

**Issue by likit** [bokeh/bokeh#1982]
I found DateRangeSlider widget but I cannot seem to find a RangeSlider for numbers. If it doesn't exist, is it straightforward to adapt the Python code for DateRangeSlider for RangeSlider?

**Comment by bryevdv** [comment]
It's just called `Slider`, see, e.g.:

https://github.com/bokeh/bokeh/blob/master/examples/embed/spectrogram/spectrogram.py#L123

**Comment by likit** [comment]
Hi, thanks for replying. I already checked the example you pointed me to but it was not what I asked for. It's just a slider not a range slider. Here is an example of the range slider from jquery. https://jqueryui.com/resources/demos/slider/range.html. Thanks.
