### ISSUE TITLE
Never use empty dict/list as default argument

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#1983]
While working on #1972, I came across this pattern: `def foo(x={})`, and it appears to happen in several places. This is really dangerous, since if that function is called multiple times with `x` not specified, the same dictionary instance is used. Now if that dictionary was populated during the first call, the items are still in there during the second call...

In relation to #1980, I wonder if pyflakes warns about these things.

**Comment by almarklein** [comment]
The exact rule of thumb is: never use a mutable object as the default value for a function argument.

**Comment by fpliger** [comment]
yeap, definitely something to avoid... unless it's used "deliberately", but in that case it's preferable to be explicit.

IIRC pyflakes (and friends) do warn about this

**Comment by bryevdv** [comment]
There is the occasional use for it, if you want something akin to a C "static" variable. But where are the several places? I believe you, I just don't remember seeing that anywhere offhand, and it would have definitely jumped out at me if I had seen it.

**Comment by almarklein** [comment]
Search for `={}` and you should get a few hits. One place where it definitely leads to problems is here: https://github.com/bokeh/bokeh/blob/master/bokeh/transforms/ar_downsample.py#L404

**Comment by bryevdv** [comment]
Ah, in the AR code. That was written mostly by one person, fairly new to python. I would be surprised to see occurrences outside the AR related modules.

**Comment by almarklein** [comment]
I just checked, and to my surprise both pyflakes and flake8 (with style checking) do *not* warn for this.

**Comment by almarklein** [comment]
https://twitter.com/raymondh/status/576047090905677824

**Comment by pzwang** [comment]
I don't think there is any argument that this should almost never be done, and if it does have to be done, there should be a big fat comment indicating *why*. :)
