### ISSUE TITLE
Investigate the use pytest instead of nose

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#1984]
Pytest differs from nose in that you can just `assert` anything, and when something fails, pytest will apply some voodoo to come up with an error message that makes sense (e.g. show diff of lists if you assert that two lists are equal). This makes writing tests much easier, because you don't need all the `assert_x` functions.

For asserting exceptions, there is a `raises()` function, that can also be used as a context manager. And that's in most cases the only function you ever need in a test.

Some examples:

    assert some_number == 3
    assert some_list == [2, 3, 4]
    raises(ValueError, foo, 3, 4, bar=8)
    with raises(ValueError):
        foo(3, 4, bar)

We can set this up for Travis in a PR and see how we like it. pytest is compatible with unittest and nose, so transition can be smooth. No need to rewrite our existing tests.

**Comment by fpliger** [comment]
not only... niceties like `monkeypatch`, `tmp_dir` and other built-in (but not only) fixtures. Plugins and hooks model. Great integration with pdb for debugging purposes, etc..  (the list could go.. IIRC you could even test javascript with it :-) ) makes pytest my favorite test framework so far :-)

As I commented on another issues earlier the most of the work I'd expect is on the automation machinery of tests (but I don't have enough background on the whole tests implementation/automation to ensure it).

**Comment by almarklein** [comment]
I've set pytest up with Travis before, so I can give it a go.

**Comment by damianavila** [comment]
Sound nice... let's see how the experiment goes...

**Comment by bryevdv** [comment]
> No need to rewrite our existing tests.

Not now, but slowly over time. If we are going to transition to all new tests being `pytest` then eventually all tests should be `pytest`. Question I meant to ask at the presentation I saw but did not have a chance to: How does `pytest` handle floating point almost-equal assertions?

**Comment by fpliger** [comment]
afaik it doesn't. You need to be explicit on your test (or use external methods that do that). That said, it can ingest `unittest` tests (so all `unittest.TestCase` and friends) and you should be able to use those.

**Comment by almarklein** [comment]
In `numpy.testing` there is 'assert_almost_equal` and `assert_allclose`.
Or you can do `assert abs(x-y) < 0.0001`.

**Comment by fpliger** [comment]
Yeap.. we already use some of those used on `bokeh.charts` tests

**Comment by fpliger** [comment]
worth mentioning that if I run:

```Bash
conda install -n pybk27 pytest
py.test -v -s
```

I get the same output from running our current tests... :tada:
