### ISSUE TITLE
Issues with curdoc() on a slow redis connection ??

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#1992]
Hi, 

I haven't had a lot of time to investigate this (and I'm afraid I don't have more in the very near term) but I wanted to share my experiences and see if this made sense / is bonkers / something in between?!

I was doing some very modest testing of my bokeh-server config locally, whilst connected to a remote redis database, to look at the effect of a db latency.  

In my client app I was using a very slightly tweaked version of `app_document` (https://github.com/bokeh/bokeh/blob/master/bokeh/pluginutils.py#L9) (the tweak was *not* calling autload_server to get the _tag so I don't believe it was impacting my tests). 

With simultaneous connections, I started to get the following errors:
````bash
16:56:39 web.1  |   File "/opt/miniconda/envs/server-py2/lib/python2.7/site-packages/bokeh/server/serverbb.py", line 90, in get_document
16:56:39 web.1  |     doc = Document(json_objs)
16:56:39 web.1  |   File "/opt/miniconda/envs/server-py2/lib/python2.7/site-packages/bokeh/document.py", line 45, in __init__
16:56:39 web.1  |     self._init_context()
16:56:39 web.1  |   File "/opt/miniconda/envs/server-py2/lib/python2.7/site-packages/bokeh/document.py", line 337, in _init_context
16:56:39 web.1  |     raise DataIntegrityException("too many plot contexts found")
16:56:39 web.1  | DataIntegrityException: too many plot contexts found
````

As a result I tried altering `app_document` to not use `curdoc()` but to create a new `Document` manually. So my code now looks like this:
````python
def app_document_new_doc(prefix, url="default"):
    def decorator(func):
        def wrapper(*args, **kwargs):
            document = Document()
            session = Session(name=url, root_url=url)
            session.use_doc(document.docid)
            session.load_document(document)
            session.publish()
            document.autoadd = False
            document.autostore = False

            obj = func(*args, **kwargs)
            obj._docid = session.docid
            obj._root_url = session.root_url

            document.add(obj)
            session.store_document(document)
            return obj
        wrapper.__name__ = func.__name__
        return wrapper
    return decorator
````
This seemed to resolve the `DataIntegrityException`.

I'm wondering if you guys have any feedback about this. 

Am I missing something obvious.

I'm wondering if anyone's up for explaining to me the uses for curdoc() when to use it and not to use it.

**Comment by birdsarah** [comment]
@fpliger - given that you so kindly offered. Do you have any opinions on the above? :s

**Comment by fpliger** [comment]
@birdsarah you caught me on a corner that I'm not very used to... :-)

That said, from what I see, my 2 cents here is that _init_context does not handle concurrency (so context creation and re-use) as it should. So if more then on context is being created simultaneously and it fails in the next call. A quick hack to check that you can try is to change line:

https://github.com/bokeh/bokeh/blob/master/bokeh/document.py#L333

to 

```
elif len(pcs) >= 1:
```

. I'd need to have a better look at the code and the context to provide a better (or even correct) solution.

**Comment by hhuuggoo** [comment]
Do you have threads anywhere?

**Comment by birdsarah** [comment]
Thanks @hhuuggoo @fpliger. I was looking at this again the other day on a different box, which I then trashed. Having tried to rebuild it today to look into these issues I cannot seem to duplicate the issue. I'm going to try it again later on the same network connection as before. But for now I'm closing this. I'll be on the lookout for these points if it raises its head again. Thanks again. Bird
