### ISSUE TITLE
Executing js code on "on_change" for Select widget

### ISSUE THREAD

**Issue by GildedHonour** [bokeh/bokeh#1995]
When I create a select widget:

    def my_init(self):
        my_select = Select(title="Title123:", value="All", options=some_opts, id='my_id')
        my_select.on_change('value', self.on_change_123)
   
    def on_change_123(self):
       # doing something
       # can I send a javascript code from here to be executed on the client?
    
And when it's changed (another item is selected), is there any way to call a javascript when it happens? I can, of course, find the select via jquery on the client, subscribe to its "changed" event and then call js on the client, but I wonder, is there a more standard, bokeh way to accomplish that?

**Comment by bryevdv** [comment]
@GildedHonour we are currently working on adding "JS actions". It should be in one of the next few releases.

**Comment by GildedHonour** [comment]
@bryevdv, thanks, so is the only way to do it by adding a javascript handler on the client?

**Comment by damianavila** [comment]
@GildedHonour, you closed the issue, did you find answer to your questions? Thanks.

**Comment by GildedHonour** [comment]
@damianavila , no.

**Comment by bryevdv** [comment]
@damianavila @GildedHonour I think this was covered in the recent `Callback` PR? See, e.g.

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/slider.py

That is a slider example, but you can add a callback to select widgets now too.

**Comment by damianavila** [comment]
I agree, we should close this one, I think...
