### ISSUE TITLE
RangeSlider needed (again).

### ISSUE THREAD

**Issue by likit** [bokeh/bokeh#1996]
Sorry for creating another issue for a range slider. I was asking if it was possible to add a range slider for numbers in my previous issue but I was pointed to a normal slider instead. The range slider I was asking for look like this http://jqueryui.com/slider/#range. Is it possible to add a range slider like the one in the example to bokeh widgets?

**Comment by bryevdv** [comment]
This is not implemented yet.

**Comment by bryevdv** [comment]
@damianavila FYI this is probably ~20 lines of code to add to the existing range slider, we can probably get to it sooner.

**Comment by likit** [comment]
@damianavila @bryevdv Thanks so much.

**Comment by lawremi** [comment]
Ideally it would be based on a `Range1d` model, which one could, for example, specify as the `x_range` on a plot to get automatic synchronization.

**Comment by crashMOGWAI** [comment]
upvote on range slider widget!

**Comment by crashMOGWAI** [comment]
If no one is working, I may try and poke at this.. no promises, my JS is poor. Shouldn't be too difficult since range is in the API (http://api.jqueryui.com/slider/)

**Comment by bryevdv** [comment]
#5258 has an example of a double ended ion range slider that will be in `0.12.3`. #5309 will add a built in double range slider for `0.12.4`
