### ISSUE TITLE
Visual hierarchy on autogenerated docs could be clearer.

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#1998]
Hi, I was trying to share some docs today and realized that I was really struggling with the visual hierarch on the autogenerated docs. I had a quick mess around and came up with the below, with just a few tweaks. I don't have lots of time at the moment, but am happy to do something quick, or to put proper effort into it at a later date.

Let me know.

![side-by-side](https://cloud.githubusercontent.com/assets/1796208/6416974/1cd1df92-be5f-11e4-9b8f-7f387b949920.png)

* [current](https://cloud.githubusercontent.com/assets/1796208/6416907/9a992c2e-be5e-11e4-8c74-0f11b54d0deb.png)
* [after tweaks](https://cloud.githubusercontent.com/assets/1796208/6416911/9f5e0f68-be5e-11e4-89ff-667704ef00b1.png)

**Comment by bryevdv** [comment]
I think this is promising. I like the different "bullet types" for functions/methods vs attrs/propertied. How about keeping some kind of "all the way across" highlighting for selected anchors? just changing the "bullet" color seems a little to subtle to me

**Comment by birdsarah** [comment]
I personally find all the colors distracting (I still find the blue and yellow boxes are distracting). There's no inherent meaning in them. 

I agree the bullet colors are subtle (not good for accessibility at all). For extra clarity, I would prefer if they were all prefixed with a descriptor e.g. method, classmethod, property, attribute.

**Comment by bryevdv** [comment]
@birdsarah it's interesting I added the colored lines because without anything like that everything bleeds together into one jumbled mess, I really need something to visually break up things into chunks, more than just the bold because bold is used in various places. I think adding those descriptors would be great,  just not sure how to make it happen in sphinx offhand.

**Comment by birdsarah** [comment]
Well we could do it with css in the short-term :D - I will have a quick play with some additional color.

**Comment by pzwang** [comment]
I agree that all the boxes and whatnot are visually distracting and don't help my mental model of the structure of the document.  Or maybe my main issue is with the big colored boxes for Warnings and Notes - could those just be outline boxes without filled color?

**Comment by bryevdv** [comment]
Those could be toned down for sure, too.

**Comment by damianavila** [comment]
I like the @birdsarah version... I agree it looks promising...

>Those could be toned down for sure, too.

Yes, that would help

**Comment by birdsarah** [comment]
![screenshot from 2015-02-27 12 19 43](https://cloud.githubusercontent.com/assets/1796208/6420467/1f391c66-be7b-11e4-9bff-1616e6522bd0.png)

**Comment by bryevdv** [comment]
this is brilliant

**Comment by damianavila** [comment]
wow... nice...

**Comment by birdsarah** [comment]
(if you couldn't tell, I picked the colors from the bokeh logo)

**Comment by bryevdv** [comment]
perfect, details are important :)
