### ISSUE TITLE
Support password protected redis

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2000]
Hi all,

I've tweaked the configure method so I could run bokeh-server on heroku with their redis cloud server. 

I enabled use of a password and didn't hard code the db id. You can see the whole thing [here](https://github.com/birdsarah/bokeh-server-heroku/blob/master/configure.py#L23). The relevant bit is:

````python
if backend['type'] == 'redis':
import redis
	rhost = backend.get('redis_host', '127.0.0.1')
	rport = backend.get('redis_port', 6379)
	rpass = backend.get('redis_password')
	bbdb = backend.get('backbone_storage_db_id')
	smdb = backend.get('servermodel_storage_db_id')
	bbstorage = RedisBackboneStorage(
		redis.Redis(host=rhost, port=rport, password=rpass, db=bbdb)
	)
	servermodel_storage = RedisServerModelStorage(
		redis.Redis(host=rhost, port=rport, password=rpass, db=smdb)
	)
````

Would you be interested in a PR version of this? FWIW I haven't tested this on a non-password protected redis instance to confirm it works with that too.

**Comment by bryevdv** [comment]
So, I think so. :) There are two things I am interested in in general for the server: 1) better examples/instructions on how to make production deployments and 2) make the configuration of the server adhere to "12 factor app" style. This does some of both of those things. If you made a new PR that also had some instructions for deploying on Heroku in a README that would be amazing.

**Comment by damianavila** [comment]
>If you made a new PR that also had some instructions for deploying on Heroku in a README that would be amazing.

I agree...

**Comment by birdsarah** [comment]
Sounds good. I have a couple of outstanding issues with it, that maybe you all will have some ideas on.

1) In https://github.com/bokeh/bokeh/blob/master/examples/deploy/README.md it was suggested to run python forwarder.py alongside the tornado process. I could *not* get that working, and I tried fairly hard, although I'm not a heroku wizz. In the end, in my config file I set `forwarder=True` and that works great. If that's not suitable for production for a reason I haven't figured out yet, then that's a stumbling block.

2) On heroku, they shutdown your connection every 55s, so you need to send a ping one way or another to keep the websocket alive. https://devcenter.heroku.com/articles/websockets#timeouts. I haven't implemented that yet as it's not high on my todo list. If anyone has a quick recipe that would speed things along.

So, if (1) is not a problem and (2) can wait. Then should be good to go.

**Comment by bryevdv** [comment]
redis is no longer a dependency of the server, closing.
