### ISSUE TITLE
Is it possible to use the plotting interface in combination with some `Select` widget

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#2003]
All the examples i've seen using Select widget to dynamically update data are using the models interface.

I'm thinking of the population pyramid (in Examples/embed/slideshow), or the automobile linked list (in Examples/glyphs/data_tables_server)

Is it possible to use those widget while still creating the charts with the plotting interface ? If not, might it happen in the future ?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
