### ISSUE TITLE
Inverted Y-axis when using source

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#2004]
I'm trying to get a line plot working with an inverted y-axis (it's a time serie of rankings)

I can get an inverted Y-axis  like this : `Range1d(start=11, end=0)`, but it breaks my tooltips (i guess because everything else is plotted using a *ColumnDataSource*, so they can't find the Y-axis position and don't show)

When i use `DataRange1d(sources=[self.source.columns("y-Axis")])`, i get a standard y-axis, and my tooltips work.

I've tried `DataRange1d(sources=[self.source.columns("y-Axis")], start=11, end=0)`, but it doesn't really do anything different : on creation it's like ` `DataRange1d(sources=[self.source.columns("y-Axis")])``, if i update the data source it's equivalent to  `Range1d(start=11, end=0)`.

Am I missing something, or is there a workaround to be able to get both an inverted axis, and use a *source* ?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
