### ISSUE TITLE
how can you do fill_between like figures in bokeh (line with error as shade)?

### ISSUE THREAD

**Issue by chanansh** [bokeh/bokeh#2008]
how can you do fill_between like figures in bokeh (line with error as shade)?
see http://tonysyu.github.io/plotting-error-bars.html#.VPSp3vmUe9k for an example

**Comment by bryevdv** [comment]
Right now there is no direct high level analog to `fill_between` but you can achieve the same visuals with the `patch` and `patches` glyphs. Here is one example:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/bollinger.py

**Comment by hover2pi** [comment]
Your link is dead!

**Comment by bryevdv** [comment]
That example was recently deleted. Here is another:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/stacked_area.py

**Comment by tommycarstensen** [comment]
@chanansh I think this might also be helpful for you:
https://bokeh.pydata.org/en/latest/docs/reference/models/glyphs/patch.html

I'm looking myself for a way to color between Bezier curves, so I can make a figure like this one:
https://camo.githubusercontent.com/16128d0371a197faa1fa59e259d38dca5c383136/68747470733a2f2f616c69636961726d617274696e646f74636f6d2e66696c65732e776f726470726573732e636f6d2f323031322f30322f686730323438312e706e673f773d383030

I'm not quite sure how to accomplish the rounded curves with Bokeh other than using circles.

![karyogram](https://camo.githubusercontent.com/16128d0371a197faa1fa59e259d38dca5c383136/68747470733a2f2f616c69636961726d617274696e646f74636f6d2e66696c65732e776f726470726573732e636f6d2f323031322f30322f686730323438312e706e673f773d383030)

**Comment by sg-s** [comment]
@bryevdv the example you linked doesn't work

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/stacked_area.py

says it's missing the tol palette

**Comment by bryevdv** [comment]
@sg-s Tol palettes are not in a release yet, they will be in Bokeh 3.0 You can just use a different palette.
