### ISSUE TITLE
FAQ section 

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2014]
With the increasing interest and number of questions we could probably make our users life easier (and save a lot of time) by keeping the docs FAQ section updated with the most recent and relevant questions that pop up on m.l., SO, GH, etc..  This is also easier to change questions later and change answers later as things get fixed in future versions.

There's the risk that some of the questions are duplications of what [we think] is already *well covered* in the docs but my personal opinion is that sometime people prefer FAQs structure and in this case I see no big harm.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
