### ISSUE TITLE
x_range = 'auto' with BokehJS

### ISSUE THREAD

**Issue by PBrockmann** [bokeh/bokeh#2016]
Succeed to update a simple BokehJS with an ajax NCSS request.
Play with http://jsfiddle.net/PBrockmann/mc73mfne
that uses last 0.8.1. Great !!

About the option x_range and y_range set to
x_range: [31536000000, 4102444800000],
y_range: [-2, 3]
it seems that they need to be specified.

I would like to let them set automatically. Is it on purpose ?

Note also
type: "Datetime"
an not "datetime" as before (0.6.0)

**Comment by bryevdv** [comment]
@PBrockmann the old JS interface was broken and removed (around 0.7?) We are in the process of creating a new JS interface, starting with a simple function based interface, with things like React integrations planned later. It is still a WIP.  have added it to the short term milestone, but certainly if you are motivated to contribute a PR for this feature it would be most welcome!

**Comment by PBrockmann** [comment]
Yes, yes, Brian, I have understood the message... ;-)
I am more scoped on finding, promoting and supporting interesting softwares for my community on Climate and Environment Sciences than deeply develop interfaces on a very living library that is developped so actively. I have tried modestly to give feedbacks on some real cases I have in mind. 
So I am afraid not be able to follow the development rocket but I will give a try.

**Comment by bryevdv** [comment]
Not everyone has the time or background to make active contributions, and that is fine and understandable. I just try to remind the offer so as not to accidentally miss any cases where people might. :)

**Comment by bryevdv** [comment]
The new TypeScript/JS interface is much better now, `bokeh.models` and `bokeh.plotting` both have essentially 1-1 ports to JS

http://bokeh.pydata.org/en/latest/docs/user_guide/bokehjs.html
