### ISSUE TITLE
Regular Button vs. Toggle Button Behavior

### ISSUE THREAD

**Issue by km12321** [bokeh/bokeh#2018]
When I use a Button widget and  it gets clicked, the entire app page gets reloaded instead of an ajax call getting fired (the latter being my desired behavior in this case). I tried to work around this behavior by creating my own AbstractButton subclass which overrode the on_click function so that I could bind the button's attribute change to on_change, but this did not help.

I shifted over to a toggle button, which did not reload the page but has to be clicked twice to fire the submit callback I have bound to it. For now I am using a Select widget to run filter updates for my chart. Any suggestions/workarounds?

Thanks

**Comment by cnolanAU** [comment]
I'm also seeing this twice-click problem with the Toggle button. The first event is missed, but the button appears to be depressed. The events from this point become out-of-sync with the visible button state; the 'active' state in the on_click handler for the first registered event comes through as 'True' as the button goes into its original (inactive) state.

**Comment by schaunwheeler** [comment]
I reported this same behavior (for both the Button and the Toggle widgets) recently on the mailing list: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/WDhI435ZzAQ. I would likewise appreciate any suggestions or workarounds.

**Comment by bryevdv** [comment]
Hey guys, that sure sounds like a bug. I am not sure offhand tho, looking at the `change_input` for both the button and toggle, and they are basically identical:

Button: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/widget/button.coffee#L37

Toggle: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/widget/toggle.coffee#L39

The toggle "twice click" is definitely a bug I have noticed recently. It did not do that in the past, but I am not sure what might have change except for possibly a version of some dependency. These will definitely require a bit of deeper investigation.

**Comment by vlall** [comment]
Anyone find a workaround? Maybe a quick hack to the 'active' state of the button might solve the Toggle issue.

**Comment by elz4** [comment]
Still no workaround? Especially for the Button widget reload?

**Comment by bryevdv** [comment]
This discussion refers to the old `bokeh-server` which has been completely removed. The new `bokeh serve` functionality has been much improved, and I do not believe has anything resembling this issue (several hosted, deployed examples are continuously available at demo.bokehplots.com unlike the old server). Please re-open a bug issue if anything similar is found with the new server, however.
