### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by queise** [bokeh/bokeh#2021]
It would be really nice to have the option for a transparent background (and border area) in the plots. Something like a background_alpha attribute for figure().

I'm sorry I cannot contribute to fix that :(

Thank you and congratulations for this excellent library!

**Comment by bryevdv** [comment]
Propose changing removing `border_fill` and `background_fill` here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/plots.py#L290-L296

replacing them with `border` and `background` attributes that are `FillProps`, and making the necessary changes on the BokehJS side. 

Accept `border_fill` and `background_fill` as initializer args and issue deprecation warning.
