### ISSUE TITLE
Allow bokeh server scripts to take command-line arguments

### ISSUE THREAD

**Issue by hsharrison** [bokeh/bokeh#2026]
I'm writing a script that I'd like to take a command-line argument. I can't figure out a way to do that without resorting to terrible hacks (which I'm not entirely sure would work anyway). Has this come up before? Any suggestions for workarounds in the meantime?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by hsharrison** [comment]
I'm still interested. At least it would save me the trouble of having a wrapper script that writes to a temporary file.

**Comment by bryevdv** [comment]
Command line arguments can now be passed, e.g.:
```
bokeh serve --show foo.py --args bar --baz 10
```

**Comment by ryanjdillon** [comment]
Is this in the documentation somewhere? If not, could you further explain how the passed args may be used within the script? Thanks!

**Comment by bryevdv** [comment]
There is a section here: 

http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html#module-bokeh.command.subcommands.serve

Also the PR is linked above, where all the files change (e.g. including docs) can be viewed.

**Comment by ryanjdillon** [comment]
Excellent. Managed to miss that. Thank you Bryan!

**Comment by ShuaiW** [comment]
Maybe I got it wrong but the following code snippet doesn't work (bokeh v.0.12.3)

test.py

```python
import sys

if __name__ == '__main__':
  a = sys.argv[1]
  print a
```

in cli, I typed

`bokeh serve test.py --args 1`

No output in cli (should get 1)

**Comment by bryevdv** [comment]
@ShuaiW the bokeh server loads and executes the code itself, so it's not the same as `python  test.py`, in particular, the module is not a "main" module. Remove the main check and it will work.

**Comment by ShuaiW** [comment]
@bryevdv 

so I already tried this by changing `test.py` to 

```python
import sys
a = sys.argv[1]
print a
```

and cli run 

`bokeh serve test.py --args 1`

still no output

**Comment by bryevdv** [comment]
@ShuaiW You need to also open a session on the server (i.e. navigate a browser to the URL to view the page). The app code is what creates everything needed for new sessions, and it is only run to create new sessions when they occur.

**Comment by ShuaiW** [comment]
@bryevdv is it possible that you provide an minimal working example to illustrate your point? appreciate it

**Comment by bryevdv** [comment]
@ShuaiW certainly but this is not the place for it. General support questions should go on the public user's mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

As this is a usage/support question, I am happy to continue the discussion there.

**Comment by ShuaiW** [comment]
@bryevdv thank you! I posted there
