### ISSUE TITLE
How to add data labels to bokeh plots?

### ISSUE THREAD

**Issue by pofican** [bokeh/bokeh#2028]
I would lik eto add data labels to my plots, I think the "text" and "Hover" widgets combined is what I am looking for but I coudn't find how to use these properly. My code is below and I would like to see the values for each data point is plotted above each circle indicating the exact value of the circle. Are these the right widgets to use for this purpose? I would appreciate some guidelines on how to use these widgets, documentation is not very clear...

```python

from bokeh.plotting import *
factors = ["a", "b", "c"]
x0 = [0, 0, 0]
x =  [50, 40, 65]

output_file("categorical.html", title="categorical.py example")

p1 = figure(title="Dot Plot", tools="resize,save", y_range=[0,100], x_range=factors)

p1.segment(factors, x0, factors, x, line_width=2, line_color=["orange","green","red"])
p1.circle(factors,x, size=15, fill_color=["orange","green","red"], line_color=["orange","green","red"], line_width=3, )
p1.text([65,65,65],[65,65,65], text=[ str(i) for i in x], alpha=0.5, text_font_size="5pt", text_baseline="middle", text_align="center")
hover = p1.select(dict(type=HoverTool))
hover.tooltips = [
    # add to this
    ("(x,y)", "($x, $y)"),
]
show(p1)

**Comment by pzwang** [comment]
This is indeed the right way to do this.  You can look at e.g. https://github.com/bokeh/bokeh/blob/master/examples/glyphs/colors.py or http://bokeh.pydata.org/en/latest/docs/gallery/elements.html for examples of this.

Are there specific aspects of these renderers you would like more clarity on?

**Comment by pofican** [comment]
Awesome! Thank you for sharing these useful examples with me. I am closing the discussion here now.
