### ISSUE TITLE
Hover tool currently does not work with line glyphs

### ISSUE THREAD

**Issue by gregerhardt** [bokeh/bokeh#2031]
As noted in the documentation: 

Point hit testing is not currently available on all glyphs. Hover tool currently does not work with line or image type glyphs.

I am creating this as an issue to show that there is interest in the user community for hover tool capabilities on line glyphs as a highly desirable feature.

**Comment by knightofni** [comment]
As a workaround, you can use an invisible Quad glyph, sharing the same data source than your line plot. Works very nicely.

But having hover tools work directly with lines would be nice.

**Comment by gregerhardt** [comment]
Thanks.  A quad glyph is a good idea.  I'm currently using a circle glyph at the line midpoint, but that is clunky because you have to have good aim.

**Comment by bryevdv** [comment]
dupe of #1486
