### ISSUE TITLE
Is there any reason why p.select() shouldn't take **kwargs?

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#2033]
Looking at https://github.com/bokeh/bokeh/blob/master/bokeh/models/plots.py#L58, it should be a fairly clean change to convert **kwargs into JSON before passing it into the `find()` call...  This would really make the interface a lot cleaner.

The only downside I can see is that in the future, the `.select()` method could not safely grow any actual keyword arguments, lest they conflict with attribute names which are being searched for...

**Comment by pzwang** [comment]
Actually, while we're at it...

Why not change it to also accept positional arguments, i.e. if a string is passed in, it's assumed to be "name=", if a Python `type` is passed in and it's a subclass of PlotObject or HasProps or something, then it's assumed to be a query of the form "type=".  This leads to a must more natural usage, like:

    p.select(TapTool)

and 

    p.select("outliers")  # for a scatter renderer named "outliers"

Thoughts?

**Comment by fpliger** [comment]
I like the idea of positional arguments, specially regarding the named renderers.. OTOH as someone new to the codebase and concepts I think that positional arguments that change "meaning" depending on their type can easily be very confusing.

Honestly I already find `.select` a bit confusing as we should better document what keys and values `selector` can specify ( right now we only have:  `selector (JSON-like) :`). If we do add this bit of info to the docs I'd be +10 for the ** magic. I find it more elegant and does not force the user to pass everything into a dict..

For that reason I think my preference would go for just the **kwargs

**Comment by bryevdv** [comment]
Love this.

**Comment by bryevdv** [comment]
Propose:
```
    # enforce len(kwargs) = 0
    p.select("a string")                    # p.select({"name:" "a string"})
    p.select(PropsType)                     # p.select({"type": PropsType})
    p.select({"foo": "bar", "baz": "quux"}) # p.select({"foo": "bar", "baz": "quux"})

    # enforce len(args) = 0
    p.select(foo="bar", baz="quux")         # p.select({"foo": "bar", "baz": "quux"})
```
@Maggie-M I'd like you to look at this.

**Comment by pzwang** [comment]
Bryan, surely your third line was meant to read:

    p.select(foo="bar", baz="quuz")

?

**Comment by bryevdv** [comment]
No? The third line is the current behaviour (pass in a single selector dict as the arg) and I was just being explicit that we should also keep that. Unless I am missing something?

**Comment by pzwang** [comment]
@fpliger You're right, we need to document the types that can be searched for and provide a bunch of examples of common things.

I ran into this issue while writing the examples last night in response to the mailing list question, and realized that `select()` was the recommended way to get the renderer after using `p.glyphfunc(...)` to create circles and lines.

**Comment by pzwang** [comment]
Ah OK.  Yes, in the case of an actual dict, it needs to pass through.  I see now - I was misunderstanding the comments somehow.

**Comment by bryevdv** [comment]
Yes, sorry the comments are the "translations" into the equivalent code with the current interface

**Comment by bryevdv** [comment]
So the easiest thing is probably to rename `Plot.select` to `Plot._select` and then make a new `Plot.select ` that just does all the argument handling/checking and calls the original.

**Comment by pzwang** [comment]
Yep, great way to do it.
