### ISSUE TITLE
Is there currently a way to make HoverTool "sticky", i.e. remain visible on the last hit point?

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#2035]
Right now the hover bubbles disappear when the mouse cursor leaves the point/glyph.  But in some cases it might be nice for it to only disappear when the mouse cursor enters a new point, or when the tool is turned off altogether, or when the cursor leaves the plot area.

Maybe there is already a different way to achieve this that I'm not aware of...

**Comment by bryevdv** [comment]
There's no "leading edge trigger" currently, I suppose it might be a useful feature tho I am not quite able to imagine a concrete scenario. Can you describe a use-case more specifically? This would probably not be incredibly hard but it would add some complexity to the entire selection architecture I think.

**Comment by pzwang** [comment]
Well, with the hovertool + taptool example I put together, I realized that it was helpful to have the tooltip remain visible as I panned the plot, etc.

Maybe this is another example where the HoverSelect tool would be useful, and maybe this functionality falls entirely under that tool.

**Comment by fpliger** [comment]
That's a good discussion actually. Yesterday I was trying the idea of the "_hit_span" (formerly referred as "_hit_line") on circle glyphs was thinking about the best way to do it. One way is doing like now that tooltip disappear when leaving the glyph, another way would be to always show a tooltip taking the closest glyph from the mouse position (this for point and span geometries). This is actually how I started the implementation of the _hit_span on the line glyph.

IMO the hover+tap tools would be a great addition as it's a good way to "freeze" the tooltips in case the user wants to export/print the plot showing the values tooltip.

**Comment by pzwang** [comment]
Right, the "freeze" tooltip for export is another use case that this stickiness would be useful.  I think taking the "closest glyph to the mouse position" does not actually solve this problem.

The _hit_span thing is useful, but again I think it's for a somewhat different class of problems...

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
