### ISSUE TITLE
Implementation of renderers in WebGL 

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#2036]
Although Bokeh is pretty fast, it does not yet scale well for > 100K data points. Using WebGL is the obvious solution to fix this. This should help e.g. #1536.

## Approach

The 2D context is currently used in the following files:
  * coffee/renderers/*.coffee - the renders themselves
  * coffee/common/plot.coffee - renders the title and calls `render` on all renders
  * coffee/common/canvas.coffee - creates the canvas and configures it

The code will have to be modified to allow using a webgl context instead.

The idea is to allow content to be drawn either in a 2d or gl canvas and squash the results together in a visible canvas (the rest are not visible). I'm now doing benchmarks to decide whether to squash into a 2d or gl canvas. Also need to take layering into account.

Since we are doing 2D rendering for the moment, and have very specific content (glyphs, mostly) to be drawn, I prefer to keep close to the metal. Pure webgl is a little verbose though. Now using vispy.js.

## Some results

* We can render the result of a 2D canvas into a WebGL canvas.
* We can also render the result of a WebGL canvas into a 2D canvas.
* Timing (on my machine): 5 ms to upload a canvas2d into a webgl texture. 1.5 ms to draw an invisible webgl canvas into a 2d canvas. Drawing a 2D canvas into another 2D canvas seems to be nearly instantaneous (0.02 ms) is that even possible? I was quite surprised by these results. These were measured in FF. Measurements in IE and Chrome show the same trend.
* For the above, it seems that there is no significant performance difference between `texImage2D` and `texSubImage2D`, which I found surprising too.
* Vispy.js can be integrated in Bokeh, but needs newer versions of jQuery and jQuery-ui.

## Current status

Implemented that everything is drawn to a 2d canvas, except that it's not visible, and it gets "copied" to a visible gl canvas.

**Comment by almarklein** [comment]
My plan towards this is as follows. Feel free to comment (cc @bryevdv):

* In the `CanvasView` we do a check to see if WebGL support should be enabled. It should be available in the browser, and we probably want a flag to be able to disable it explicitly.
* The `CanvasView` gets a `@canvas2d` and `@canvas3d` attribute. In non-gl mode, `canvas3d` is null, and `canvas2d` is the visible canvas, and everything works as it currently does. In gl-mode, `canvas3d` is the visible webgl canvas, and `canvas2d` is an invisible 2d canvas.
* During rendering each object renders to either of these canvases. Glyphs that can do so should render via webgl if the `canvas3d` is not null.
* The `PlotView` controls the rendering and does so one level at a time. When using gl-mode, the `canvas2d` is cleared at the beginning of processing a level, and at the end of the level it is rendered into the `canvas3d`, thereby blending it with whatever content was rendered in there already. 

This approach allows us to add gl support one glyph at a time. Also it may not make sense for all glyphs to have gl support. With the per-level blending the end-result should match the non-gl-mode, regardless of where glyphs render to.

Since some levels will probably always just render to the `canvas2d` we can probably make some optimizations to reduce the number of times the `canvas2d` is rendered into the `canvas3d`.

We probably also want to combine the drawing of multiple glyphs of the same type. We'll have to see whether the `PlotView` is responsible for this grouping, or if handle this in another way. I think we can address this once the basics are in place, and when we have one or two glyph working.

**Comment by almarklein** [comment]
The plan is to start with just a few simple glyphs (e.g. line, circle), because these are probably to be most common in situations where lots of data is drawn (you are not going to use fancy marker shapes if you draw 1M points). Then extend from there.

**Comment by damianavila** [comment]
@almarklein do you want to keep this open, or do you think we can close this one (because #2569) and open other issues for future improvements?

**Comment by almarklein** [comment]
Let's close this. I'll open up a new meta-issue to list further tasks related to webgl soon.
