### ISSUE TITLE
JavaScript error with Toggle button

### ISSUE THREAD

**Issue by hsharrison** [bokeh/bokeh#2037]
I'm getting the following in the Chrome developer console when I try to use Toggle:

````
Uncaught ReferenceError: build_views is not defined      toggle.js:37
````

It could easily be that I'm doing something wrong. [Here](https://bitbucket.org/hharrison/data-player/src/c4adff303be74946f037cef1900b2f4434aac15b/src/dataplayer/dataplayer_app.py?at=default)'s my code. Apologies for not coming up with a minimal example, I'm a bit strapped for time. I'm also not well-versed on the JavaScript side so I have not investigated further. Other than the fact that removing the toggle and all references to it works fine.

**Comment by bryevdv** [comment]
Thanks for the report! Looks like a "missing import" here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/widget/toggle.coffee#L7

Should be an easy fix.

**Comment by bryevdv** [comment]
Ping @mattpap did you happen to see/fix this in your recent work on making `icon` work?

**Comment by bryevdv** [comment]
This was resolved ages ago:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/toggle.coffee#L4

Additionally just confirmed running `button_server.py` with new (`0.11`+) Bokeh server functions as expected.
