### ISSUE TITLE
What is the best way to develop bokehjs with incremental rebuilds?

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#2038]
Continuuing from an email discussion, posting here because I don't have @mattpap 's email address yet, but also because I think we should either make this easier, and/or update the developer docs.

> > Almar: I'd like to have a quick development cycle, because compiling whole bokehjs takes too long. So I have BOKEH_RESOURCES set to 'relative-dev', and run ``grunt watch`` in bokehjs to update js as soon as I modify a coffee file. However, this does not work, since the generated HTML loads its JS from bokeh/server/static/js. I managed to make it work by changing one line in resources.py. Am I doing something wrong? If not, is it an idea to define a way to make the HTML load from bokhejs/build/js instead?

> Brian: I am cursed with a fast enough laptop and rare enough rebuilds that I usually just put up with the build time. Mateusz always uses incremental build, though, so he is the best person to ask if there are problems or issues. What you described sounds correct to my memory, but may be that the dev docs need to be updated in some way.

**Comment by hhuuggoo** [comment]
with the server it is easy

`$ ./bokeh-server -djs`
`$ grunt watch`

I don't believe there is a good way for file based examples where we embed all of bokeh.js into the file

**Comment by almarklein** [comment]
It *could* be easy though, since bokeh packs the JS into the html each time. The only problem is that it takes the JS from `bokeh/server/static/js`, while grunt outputs to `bokhejs/build/js`.

**Comment by bryevdv** [comment]
I know it has worked for me in the past. FWIW here are the old instructions I got once:

1) static HTML

	BOKEH_RESOURCES=relative-dev python example.py

2) server

	./bokeh-server --dev
	python example-server.py

These are after "grunt watch" is run in another terminal.

Bryan

**Comment by almarklein** [comment]
yeah, that's also what it says in dev docs,  but (1) does not work anymore.

**Comment by bryevdv** [comment]
@mattpap please chime in

**Comment by mattpap** [comment]
@almarklein, there are two options:

1) static: `BOKEH_DEV=true python something.py`
2) dynamic: `./bokeh-server --dev` and then `python something_server.py`

The best way to get static files in place is to:
```
cd boke/server/static
ln -s ../../../bokehjs/build/{js,css}
```
Not doing the above, but also **not** using `setup.py`, should work as well, but perhaps this works only for server. For me using `ln` and staying far away from `setup.py` works the best. I have my own build system as well, but that's just to get unified work environment for bokeh and bokeh-scala (otherwise `grunt` works reasonably well).

**Comment by almarklein** [comment]
Ok, the link thing should work. Is this something we should put in the dev-docs?

**Comment by bryevdv** [comment]
@almarklein we should probably actually develop some minimal tool support. Think the best thing might be a little script that creates the link then runs `grunt watch` then deletes the link on exit.

**Comment by almarklein** [comment]
@bryevdv that makes sense.

Out of curiosity, what is the difference between the code in `bokehjs/build` and `bokeh/server/static`? Why does bokeh not simply use the code from the first directory?

**Comment by bryevdv** [comment]
`bokehjs/build` does not exist in installed packages.

**Comment by almarklein** [comment]
> bokehjs/build does not exist in installed packages. 

Right, of course :) 

Looking into this, I'm less sure whether using a link is a good idea. E.g. I have used setup.py at some point, which means the `server/static/js` dir exists and is locked because it was created with sudo. Nothing that can't be fixed, but all this becomes complicated to explain. More importantly, on Windows you cannot assume that you can create symlinks: https://docs.python.org/3.4/library/os.html#os.symlink

Idea: If `BOKEH_DEV=true` use `bokehjs/dist` if it exists and use `server/static` otherwise. Then simply use grunt watch. WDYT?

**Comment by bryevdv** [comment]
Yes, that seems better. Also changing to `task`

**Comment by almarklein** [comment]
I think this can be closed.
