### ISSUE TITLE
rect hoverplot problem

### ISSUE THREAD

**Issue by nevermindewe** [bokeh/bokeh#2046]
adding hoverplot with multiple rects does not give the expected results.
Attached are two screencaps showing the expected plot (good_plot.png) which was made without the hovertool and the obtained plot (bad_plot.png) that was obtained when "source=ColumnDataSource(...)" was passed to the figure.rect() function.

![bad_plot](https://cloud.githubusercontent.com/assets/5727768/6538264/ecaa1a6c-c42d-11e4-80ca-8a28cfbe8aa9.png)
![good_plot](https://cloud.githubusercontent.com/assets/5727768/6538265/ecaa414a-c42d-11e4-9234-f86cd622d652.png)

The code that reproduces this behavior is below.
The two "f.rect" calls that are commented out were used to generate good_plot.png

```
from pandas import DataFrame

def candlestick():
    try:
        import bokeh
        from bokeh.plotting import (figure, output_notebook, output_file, show,
                                    save, ColumnDataSource)
        from bokeh.models import HoverTool, Range1d
        from math import pi, ceil
        import numpy as np
    except ImportError:
        print "Could not import libraries necessary for candlestick plotting"
        print "Please ensure that Bokeh (bokeh.pydata.org) is installed"
        print "'conda install bokeh' should work if Continuum Anaconda is installed"

    output_file("/tmp/hovertest.html")

    bars=DataFrame({"open":np.arange(50,100),
                    "close":np.arange(100,150),
                    "low":np.arange(50),
                    "high":np.arange(150,200),
                    "volume":np.ones(50)})

    mids = (bars.open + bars.close)/2.0
    spans = abs(bars.open-bars.close)

    blue_bars=(bars.index.values % 2)==1
    red_bars=(bars.index.values % 2)==0

    tools="pan,wheel_zoom,box_zoom,reset,save,hover"
    f=figure(y_range=Range1d(start=0,end=220), plot_width=1000, plot_height=400, tools=tools)

    source=ColumnDataSource(data=dict(open=bars.open, close=bars.close, high=bars.high, low=bars.low, volume=bars.volume))
    f.rect(bars.index[blue_bars], mids[blue_bars], 10, spans[blue_bars], fill_color="#87CEFA", line_color="#87CEFA", width_units="screen", source=\
source)                                                                                                                                             
    f.rect(bars.index[red_bars], mids[red_bars], 5, spans[red_bars], fill_color="red", line_color="red", width_units="screen", source=source)      

    #f.rect(bars.index[blue_bars], mids[blue_bars], 10, spans[blue_bars], fill_color="#87CEFA", line_color="#87CEFA", width_units="screen")
    #f.rect(bars.index[red_bars], mids[red_bars], 5, spans[red_bars], fill_color="red", line_color="red", width_units="screen")

    hovertool = f.select(dict(type=HoverTool))
    hovertool.tooltips=[("open","@open"),
                        ("close","@close"),
                        ("low","@low"),
                        ("high","@high"),
                        ("volume","@volume")]

    show(f)

if __name__ == "__main__":
    candlestick()
```

**Comment by nevermindewe** [comment]
Sorry about the bad code pasting. I haven't pasted code into an issue before.
Also, here is the version info

In [3]: bokeh.print_versions()

   Bokeh version: 0.8.1
  Python version: 2.7.9-CPython
        Platform: Linux-3.13.0-45-generic-x86_64-with-debian-jessie-sid

**Comment by nevermindewe** [comment]
The expected plot is in the second figure that has the blue and red bars not overlapping.
The bad plot is the first figure that has the blue and red bars overlapping.

**Comment by nevermindewe** [comment]
The code below is better but still incorrect.
With this example, the hovertool shows up on the red bars but not the blue bars.

from pandas import DataFrame

def candlestick():
    try:
        import bokeh
        from bokeh.plotting import (figure, output_notebook, output_file, show,
                                    save, ColumnDataSource)
        from bokeh.models import HoverTool, Range1d
        from math import pi, ceil
        import numpy as np
    except ImportError:
        print "Could not import libraries necessary for candlestick plotting"
        print "Please ensure that Bokeh (bokeh.pydata.org) is installed"
        print "'conda install bokeh' should work if Continuum Anaconda is installed"

    output_file("/tmp/hovertest.html")

    bars=DataFrame({"open":np.arange(50,100), "close":np.arange(100,150), "low":np.arange(50),
                    "high":np.arange(150,200), "volume":np.ones(50)})

    mids = (bars.open + bars.close)/2.0
    spans = abs(bars.open-bars.close)

    blue_bars=(bars.index.values % 2)==1
    red_bars=(bars.index.values % 2)==0

    tools="pan,wheel_zoom,box_zoom,reset,save,hover"
    f=figure(y_range=Range1d(start=0,end=220), plot_width=1000, plot_height=400, tools=tools)

    source=ColumnDataSource(data=dict(blue_index=bars.index[blue_bars], blue_open=bars.open[blue_bars], blue_close=bars.close[blue_bars],
                                      blue_high=bars.high[blue_bars], blue_low=bars.low[blue_bars], blue_volume=bars.volume[blue_bars],
                                      blue_mids=mids[blue_bars], blue_spans=spans[blue_bars],
                                      red_index=bars.index[red_bars], red_open=bars.open[red_bars], red_close=bars.close[red_bars],
                                      red_high=bars.high[red_bars], red_low=bars.low[red_bars], red_volume=bars.volume[red_bars],
                                      red_mids=mids[red_bars], red_spans=spans[red_bars]))
    f.rect('blue_index', 'blue_mids', 10, 'blue_spans', fill_color="#87CEFA", line_color="#87CEFA", width_units="screen", source=source)
    f.rect('red_index', 'red_mids', 10, 'red_spans', fill_color="red", line_color="red", width_units="screen", source=source)
    #f.rect(bars.index[blue_bars], mids[blue_bars], 10, spans[blue_bars], fill_color="#87CEFA", line_color="#87CEFA", width_units="screen")         
    #f.rect(bars.index[red_bars], mids[red_bars], 5, spans[red_bars], fill_color="red", line_color="red", width_units="screen")                     

    hovertool = f.select(dict(type=HoverTool))
    hovertool.tooltips=[("blue_open","@blue_open"), ("blue_close","@blue_close"), ("blue_low","@blue_low"),
                        ("blue_high","@blue_high"), ("blue_volume","@blue_volume"),
                        ("red_open","@red_open"), ("red_close","@red_close"), ("red_low","@red_low"),
                        ("red_high","@red_high"), ("red_volume","@red_volume")]
    show(f)

if __name__ == "__main__":
    candlestick()

**Comment by bryevdv** [comment]
(FYI you can use trip backticks on lines before and after code to format as code)

**Comment by bryevdv** [comment]
@nevermindewe OK that might be a bug with hover tool then, I will try to take a quick look today. Here is the "failsafe" option though, just in case you want to try: instead of two rect renderers with a different fill color, only have one rect renderer, and specify the fill color as a column in the data source.

**Comment by nevermindewe** [comment]
More strangeness for you.
The code below doesn't show any hoverplots when the x_axis_type is "datetime".
When the line "bars.index=date_range("2015-01-02 09:30:00", periods=50, freq="5min")" is commented out, the hovertools show up exactly as expected.

```
from pandas import DataFrame, date_range, DatetimeIndex

def candlestick():
    try:
        import bokeh
        from bokeh.plotting import (figure, output_notebook, output_file, show,
                                    save, ColumnDataSource)
        from bokeh.models import HoverTool, Range1d
        from math import pi, ceil
        import numpy as np
    except ImportError:
        print "Could not import libraries necessary for candlestick plotting"
        print "Please ensure that Bokeh (bokeh.pydata.org) is installed"
        print "'conda install bokeh' should work if Continuum Anaconda is installed"

    output_file("/tmp/hovertest.html")

    bars=DataFrame({"open":np.arange(50,100), "close":np.arange(100,150), "low":np.arange(50),
                    "high":np.arange(150,200), "volume":np.ones(50)})
    bars.index=date_range("2015-01-02 09:30:00", periods=50, freq="5min")

    mids = (bars.open + bars.close)/2.0
    spans = abs(bars.open-bars.close)

    blue_bars=np.where(np.arange(50) % 2, True, False)
    red_bars=np.where(np.arange(50) % 2, False, True)

    tools="pan,wheel_zoom,box_zoom,reset,save,hover"
    if isinstance(bars.index, DatetimeIndex):
        f=figure(x_axis_type="datetime", y_range=Range1d(start=0,end=220), plot_width=1000, plot_height=400, tools=tools)
    else:
        f=figure(y_range=Range1d(start=0,end=220), plot_width=1000, plot_height=400, tools=tools)

    source=ColumnDataSource(data=dict(x=bars.index, open=bars.open, close=bars.close,
                                      high=bars.high, low=bars.low, volume=bars.volume,
                                      y=mids, spans=spans,
                                      fill_color = np.where(blue_bars, "#87CEFA", 'red'),
                                      line_color = np.where(blue_bars, "#87CEFA", 'red')))

    f.rect('x', 'y', 10, 'spans', fill_color="fill_color", line_color="line_color", width_units="screen", source=source)

    hovertool = f.select(dict(type=HoverTool))
    hovertool.tooltips=[("open","@open"), ("close","@close"), ("low","@low"),
                        ("high","@high"), ("volume","@volume")]

    show(f)

if __name__ == "__main__":
    candlestick()
```

**Comment by bryevdv** [comment]
There is a bug with hit testing and screen units. Using a data-space width is a workaround (this works):
```
   w = ((bars.index[1] - bars.index[0])/3).total_seconds() * 1000

    f.rect('x', 'y', w, 'spans', fill_color="fill_color", line_color="line_color", source=source)
```

**Comment by bryevdv** [comment]
OK there are now separate issues for the problems encountered here. Marking this as a discussion and closing.
