### ISSUE TITLE
Memory problem with python clients to bokeh serve

### ISSUE THREAD

**Issue by woutergins** [bokeh/bokeh#2050]
I posted this issue on both stackoverflow (http://stackoverflow.com/questions/28939097/embedding-bokeh-plot-in-html-eats-memory) and the Google discussiongroup https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/It7ZSx37Esk), and was advised to post this here, since this sounds like a genuine issue.

The summary is that the "animated" embed example forces the browser to use more and more memory. Bryan Van de ven suggests that this might be a cleanup of the data that is not being handled correctly in the backbone. In both the stackoverflow and discussion group post, I have included a link to a MWE.

**Comment by bryevdv** [comment]
Thanks @woutergins we will take a look at this one very soon.

**Comment by bryevdv** [comment]
@hhuuggoo any offhand thoughts?

**Comment by aganders3** [comment]
I'm running into similar problems with a streaming plot I've created. Here is a gist of my code with the hardware interfacing stubbed out (replaced with a random data): https://gist.github.com/aganders3/3afce94003f184ba1dda

I have tried this with similar results (runaway memory usage) in both Safari and Chrome. I am running `bokeh-server` and my logging script on the same machine (a Mac Mini running OS X 10.8), which is not used for anything else at this time. A difference from the bug as reported is that I am not embedding the plot, but rather viewing the document directly through the bokeh-server interface.

Thanks for all your work on this library, and your recognition of this issue!

**Comment by aganders3** [comment]
I don't really know JS or how to debug it, but I did some investigating with the dev tools in Chrome and I *think* this may have something to do with the plot tools. I recorded the heap allocations with different settings for the `tools` string when constructing my figure, which is updated (using `bk.push()`) every second.

With the plot tools on, I construct the figure like so, and it has the following heap allocation trace:

    tools = 'pan,xwheel_zoom,ywheel_zoom,box_zoom,save,reset'
    self.plot = bk.figure(title="Gradient Temperature Readings",
                          x_axis_label="Time [minutes]",
                          x_axis_type='datetime',
                          y_axis_label="Temperature [degrees C]",
                          h_symmetry=True,
                          height=500,
                          width=1100,
                          logo='grey',
                          tools=tools) 

![screenshot 2015-05-08 10 15 53](https://cloud.githubusercontent.com/assets/1231828/7541693/0e51d488-f56c-11e4-8cc4-ed0f873efdd6.png)

In contrast, turning the tools off:

    tools = ''
![screenshot 2015-05-08 10 17 28](https://cloud.githubusercontent.com/assets/1231828/7541710/2116d618-f56c-11e4-8299-ba7b43db15a3.png)

I was led to the `tools` by comparing two heap snapshots, where I noticed a large size delta in the `(array)` category, which was mostly composed of `(object properties)[]` constructors, each of which referenced either `GestureToolButtonView` or `ActionToolButtonView`.

![screenshot 2015-05-08 10 32 10](https://cloud.githubusercontent.com/assets/1231828/7541928/d00dcd6a-f56d-11e4-82a3-c312355fa4e4.png)

I ran my script overnight with the tools off to test this theory. Usually it chews up all available memory on my machine by morning, but today all was chugging along nicely when I got into the office. Hopefully this is helpful in some way and I'm not just way off the mark.

**Comment by pzwang** [comment]
Thanks for the detailed debug information!

**Comment by bryevdv** [comment]
Just by way of an update, one of the things we want to do as part of the ongoing server work is to make the actual data store in the client "separate" from the rest of the (very lightweight) bokeh document object graph. So, this issue has not been forgotten but it needs to be addressed in this larger context.

**Comment by bryevdv** [comment]
An update, in light of the new server. When running `animated.py` with the `bokeh serve`, the server process itself does not show any memory growth. But the python process that runs `animated.py` *does* seem to show unbounded growth, so this is still an issue.

**Comment by Artimi** [comment]
I know that `embed/animated.py`  should not be used anymore according to https://github.com/bokeh/bokeh/issues/6887 . But I can add some knowledge about this. If I install [objgraph](https://mg.pov.lt/objgraph/) and add use modified version of `update`:
```
def update():
    peak_stats = objgraph.typestats()
    rmin = roll(ds.data["inner_radius"], 1)
    rmax = roll(ds.data["outer_radius"], -1)
    ds.data.update(inner_radius=rmin, outer_radius=rmax)
    objgraph.show_growth(peak_stats = peak_stats)
```
I can see that count o objects `frame` is getting higher every update:
```
frame       19        +1
frame       19        +1
frame       19        +1
frame       22        +1
frame       22        +1
```
And when I get all frames I can see that there is increasing number of frames from `bokeh/client/_connection.py`:|
```
inspect.getframeinfo(c_frames[10])
Traceback(filename='/home/sebekpet/.virtualenvs/bokeh/lib/python3.5/site-packages/bokeh/client/_connection.py', lineno=302, function='_next', code_context=['            yield self._state.run(self)\n'], index=0
```
We can see from this backref that this frame belongs to Runner object of tornado (don't mind the right side of image). 

![frame_backref](https://user-images.githubusercontent.com/1468560/30325348-b372d550-97c4-11e7-874e-d7ffd6de3722.png)

I'm not quite sure how this can happen but it seems that the generator on `ClientConnection._next` is not trully read and therefore some runner/frame is leaking. This might be because of recursing nature of `ClientConnection._next` but that is just a guess. I don't know if this will help you if you want to abandon usage of `session.loop_until_closed()` but maybe it can be helpful on some other place.

**Comment by Artimi** [comment]
My guess was correct. When I run the code with changed method `_handle_messages`:
```python
@gen.coroutine
def _handle_messages(self):
	while True:
		message = yield self._pop_message()
		if message is None:
			yield self._transition_to_disconnected()
		else:
			if message.msgtype == 'PATCH-DOC':
				self._session._handle_patch(message)
			else:
				# we don't know about whatever message we got, ignore it.
				pass
```
It does not leak in state `CONNECTED_AFTER_ACK`. To get rid of this completely the logic in `ClientConnection` should be rewritten so that it calls next in loop and not recursively.

**Comment by bryevdv** [comment]
@Artimi Thanks for the detailed analysis! I definitely want t discourage using `session.loop_until_closed` but I don't want to leave any bugs either. Would you be interested in working up a PR for this fix?

**Comment by Artimi** [comment]
@bryevdv Sure I will try to come up with something.

**Comment by bryevdv** [comment]
@Artimi Brilliant, it is very appreciated!

**Comment by bryevdv** [comment]
@Artimi Are you still interested in contributing this PR?

**Comment by Artimi** [comment]
@bryevdv Hi I've tried it shortly after but the interface changed quite often then. Now I don't see that I will have time for this in near future. Sorry

**Comment by bryevdv** [comment]
`session.loop_until_closed` is being removed as public API in Bokeh 2.0, so I am just gong to close this.
