### ISSUE TITLE
buttons_server.py example : dropdown & split not fully functionnal

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#2053]
When running the buttons_server example (Examples/glyphs) : 

Actions from all buttons produce output in the terminal, except for the dropdown & the split.

If split is clicked once, the action will be registered (`split_handler: baz`)

But just selecting an item from the dropdown / split will not register anything.

Are they missing some `on_change` methods ?

**Comment by bryevdv** [comment]
Can you provide a Minimum Runnable Example to help us diagnose this?

**Comment by knightofni** [comment]
I think the easiest minimum runnable example would be to run example/glyphs/buttons_server.py

If you click on any widget : the action appears in the terminal. 

However, if you select an item from the dropdown / split : the action is not displayed in the terminal.

Let me know if its still unclear.

**Comment by knightofni** [comment]
### Exacts steps to reproduce missing functionality

1. run bokeh-server
2. cd to `bokeh/Examples/bokeh/glyphs`
3. python buttons_server.py
4. Using any widget will produce output in the console except when :
- selecting from dropdown 
- selection from the split (clicking works)

![screen shot 2015-03-17 at 7 59 51 pm](https://cloud.githubusercontent.com/assets/3415960/6686867/56bdf49a-cce0-11e4-9cf5-c981f4eec4c6.png)

Output :

![screen shot 2015-03-17 at 8 00 03 pm](https://cloud.githubusercontent.com/assets/3415960/6686860/4866de66-cce0-11e4-8aba-3682c17b6b9e.png)

If we check in the source code, it seems that the writer of this example had thought that selecting from the dropdown should print an output :

```
def dropdown_handler(action):
    print("dropdown_handler: %s" % action)
    session.store_document(document)

def split_handler(action):
    print("split_handler: %s" % action)
    session.store_document(document)
```

However, the dropdown & the split only have 'on_click' methods, so nothing happens in case of selection :

```
menu = [("Item 1", "item_1"), ("Item 2", "item_2"), None, ("Item 3", "item_3")]
dropdown = Dropdown(label="Dropdown button", type="warning", menu=menu)
dropdown.on_click(dropdown_handler)

menu = [("Item 1", "foo"), ("Item 2", "bar"), None, ("Item 3", "baz")]
split = Dropdown(label="Split button", type="danger", menu=menu, default_action="baz")
split.on_click(split_handler)
```

**Comment by bryevdv** [comment]
Ping @mattpap

**Comment by bryevdv** [comment]
This example works as expected with the new `bokeh serve` Bokeh server.
