### ISSUE TITLE
server/utils/plugins.py not passing in title attribute

### ISSUE THREAD

**Issue by km12321** [bokeh/bokeh#2054]
This file does not specify title attribute for render_template function. I added: 
```
    if hasattr(obj, 'title'):
        title = obj.title
    else:
        title = ""
```
and passed in the title attribute aftewards. This should be a quick fix

**Comment by bryevdv** [comment]
@km12321 would you be interested in contributing a Pull Request for this?

**Comment by km12321** [comment]
Am not an active Git user so it may be easier for someone on your end to do this :)

**Comment by bryevdv** [comment]
This issue refers to the old `bokeh-server` which has been completely removed. I am closing this issue to clear up our tracker. The new `bokeh serve` is much more robust, easy to use, tested, and documented, and supports setting titles.
