### ISSUE TITLE
running server example twice duplicates layout

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2059]
reference: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/pc8XceLuaas

Running the code in the referenced post twice results in two copies of the layout being displayed. Checked also with `examples/glyphs/population_server.py` and confirmed it is happening with that as well. Appears to be a regression. @hhuuggoo @mattpap thoughts very welcome.

**Comment by bryevdv** [comment]
Screenshot attached:
![screen shot 2015-03-11 at 9 58 27 am](https://cloud.githubusercontent.com/assets/1078448/6599005/34facaf0-c7d5-11e4-8db9-9b5bb332157f.png)

**Comment by bryevdv** [comment]
@Maggie-M can you see if this happens with recent released versions? `0.8.1` or `0.8` For each install the test procedure is:
* run `bokeh-server --dev`
* run `examples/glyphs/population_server.py`
* stop it, run it again
* see if layout is duplicated as above
* stop `bokeh-server`

**Comment by fpliger** [comment]
I always though that it should behave in the oposite way.. So reset by default and hold on request.

**Comment by bryevdv** [comment]
That was basically the old behavior. `reset_output` was never needed, the document was always cleared.

**Comment by hhuuggoo** [comment]
I recall that we made the default result of output_server to clear the doc, unless you pass a certain kwarg.  If this isn't happening anymore, it's a regression problem - should be easy to track down though - output_server should wipe out the doc - if not, that's where it broke =)

**Comment by fpliger** [comment]
`output_server` is not taking part in this case as we are talking about `glyph` interface.

I can confirm that it's still happening on master. Of course if you explicitly call `document.clear()` on `population_server.py` example it works expected.

**Comment by bryevdv** [comment]
ping @fpliger

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by damianavila** [comment]
Previous milestone: 0.9.1

**Comment by bryevdv** [comment]
This is not an issue with the new server (verified) Every tab gets its own session.
