### ISSUE TITLE
Y-Axis Alignment in Vertical GridPlot

### ISSUE THREAD

**Issue by bkief** [bokeh/bokeh#2061]
The y-axes of two vertically arranged gridplot figures become misaligned when one of the y-axis tick labels require more space than the other figure. 
 
![image](https://cloud.githubusercontent.com/assets/3420363/6610301/ba29639a-c833-11e4-9ef2-a93667db628e.png)

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by racheladdison** [comment]
I am running into this problem a lot when trying to use VBox. I don't know how many other people could use this fix, but I certainly could.

**Comment by bryevdv** [comment]
This alignment is automatic in Bokeh `0.12`, what version are you using @racheladdison ?

**Comment by racheladdison** [comment]
Awesome! I'm in 0.11.1, so I'll go ahead and get 0.12. Thank you!
