### ISSUE TITLE
Tooltip not working when inverting an axis by passing a `y_range` argument to the figure

### ISSUE THREAD

**Issue by niparis** [bokeh/bokeh#2064]
Note : port from [this](http://stackoverflow.com/questions/29003489/getting-a-tooltip-to-work-with-an-inverted-axis) SO question

It is not possible to have a tooltip while changing the axis by passing the  `y_range` argument to the `figure` object.

Examples with code :
### Normal axis, tooltip working

```
p = bk.figure(title='Non-Inverted Axis, Hover tool-tip', tools=TOOLS,
 plot_width=600, plot_height=300)
p.circle(y='x', x='y', source=source)
hover = p.select(dict(type=HoverTool))
hover.tooltips = [
    ("x", "@x"),
    ("y", "@y"),
]

bk.show(p)
```

![enter image description here](http://i.stack.imgur.com/Z55ZI.png)
### Inverted Axis, no tooltips

```
p = bk.figure(title='Inverted Axis, no tool-tip', tools=TOOLS,
 plot_width=600, plot_height=300, y_range=(10,0))
p.circle(y='x', x='y', source=source)
hover = p.select(dict(type=HoverTool))
hover.tooltips = [
    ("x", "@x"),
    ("y", "@y"),
]

bk.show(p)
```

![enter image description here](http://i.stack.imgur.com/HFRAF.png)

[Here's a notebook](http://nbviewer.ipython.org/gist/knightofni/f6a6538935094a4371ae) with the full code used to generate the plots.

**Comment by knightofni** [comment]
Updated title & text of question

**Comment by bryevdv** [comment]
Quite possibly a bug in the hit-testing logic. I will tentatively mark this as a `bug`, but it will require some further investigation.

**Comment by clairetang6** [comment]
This is no longer a problem (currently 0.12.3). It was almost certainly fixed through [PR 4108](https://github.com/bokeh/bokeh/pull/4108), which fixed hit-testing for reversed ranges that was causing [box select to not work](https://github.com/bokeh/bokeh/issues/3996).
