### ISSUE TITLE
Remove plot instance from GuideRenderer?

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2069]
I don't often add grids to a plot, so doing so the first time this morning.

The `Grid` has a property `plot`, which then sets the Grid renderer in the plot.renderers

With all other components I'm used to manually a plot.renderers.extend or plot.add_layout:
* plot.renderers.extend([GlyphRenderers])
* plot.tools.extend([Tools])
* plot.add_layout(Axis)

So this felt like a bit of a departure from the norm. 

It's somewhat cumbersome, but very explicit, and makes it easy to turn things on and off which I like.

Is there a reason for plot being set on instantiation of Grid? Would it be useful to have the interface be the same as for other Renderers?

----
##### Related Aside

The following code does not work, although it seems like it should.
````python
xaxis = LinearAxis(ticker=SingleIntervalTicker(interval=5), **axis_formats)
yaxis = LinearAxis(ticker=SingleIntervalTicker(interval=5), **axis_formats)

xgrid = Grid(
    plot=None, 
    dimension=0, ticker=xaxis.ticker, 
    grid_line_dash="dashed", grid_line_color="gray"
)                                                                       
ygrid = Grid(
    plot=None, 
    dimension=1, ticker=yaxis.ticker, 
    grid_line_dash="dashed", grid_line_color="gray"
)               
                                                                      
plot.renderers.extend([xgrid, ygrid])   
````
I get the console error:
````javascript
Uncaught TypeError: Cannot read property 'get' of null
````

**Comment by bryevdv** [comment]
Fairly certain the `plot=None` is the problem. You either need to set to it to `plot` by hand, let `add_layout` handle those details.

**Comment by birdsarah** [comment]
Thanks, as always, for the quick response. 

I have been going from the examples and somewhere along the way picked up the plot.renderers.extend habit. Good to know about `add_tools` and `add_glyph` 

The following, which I'm guessing is preferred way, works great, thanks.:
````python
tap = TapTool(renderers=[my_renderer])                                 
plot.add_tools(tap) 
````
Now I'm grepping around I'm seeing loads of examples of add_layout with Grid and add_tools. I cannot explain why my go to examples were ones with non-standard implementations in:

----

Examples that have caused me to err.
examples/glyphs/colors.py
````python
tap = TapTool(plot=plot, renderers=[rect_renderer], action=OpenURL(url=url))
hover = HoverTool(plot=plot, renderers=[rect_renderer], tooltips=tooltips) 
plot.tools.extend([tap, hover])
````
examples/glyphs/trail.py
````python
xgrid = Grid(plot=plot, dimension=0, ticker=xaxis.ticker, grid_line_dash="dashed", grid_line_color="gray")
ygrid = Grid(plot=plot, dimension=1, ticker=yaxis.ticker, grid_line_dash="dashed", grid_line_color="gray")
plot.renderers.extend([xgrid, ygrid])  
````
Other things to clean-up or add a note to:
Grepping for plot.renderers: 
````bash
./glyphs/data_tables.py:plot.renderers.extend([cty, hwy, ygrid])
./glyphs/data_tables_server.py:        plot.renderers.extend([cty, hwy, ygrid])
./glyphs/trail.py:    plot.renderers.extend([xgrid, ygrid])
./glyphs/trail.py:    plot.renderers.extend([xgrid, ygrid])
./plotting/file/data_tables.py:plot.renderers.extend([cty, hwy, ygrid])
````
Grepping for plot.tools:
````
./glyphs/colors.py:plot.tools.extend([tap, hover])
./glyphs/data_tables.py:plot.tools.extend([cty_hover_tool, hwy_hover_tool, select_tool])
./glyphs/data_tables_server.py:        plot.tools.extend([cty_hover_tool, hwy_hover_tool, select_tool])
./glyphs/calendars.py:    plot.tools.append(hover_tool)
./plotting/file/data_tables.py:plot.tools.extend([cty_hover_tool, hwy_hover_tool, select_tool])
 ````

**Comment by birdsarah** [comment]
(btw totally understand your point about needs to be plot=plot AND plot.renderers.extend or use add_tools)

**Comment by bryevdv** [comment]
@mattpap do you have any objections to re-working these to use `add_tools` etc? I think that would be clearer to present one canonical way of doing things.

**Comment by birdsarah** [comment]
Even when we need to have the renderer to attach it to a specific tool (e.g. glyphs/data_tables.py) add_glyph returns the renderer, so we could use add_glyph and use that to build the specific Tool as needed.

**Comment by mattpap** [comment]
Actually, yes. If you want to do anything fancy with the low-level API, you have to have to this knowledge anyway. What should really happen is validation. In this case you shouldn't be able to use/serialize an object if `plot` attribute is `None`.

**Comment by bryevdv** [comment]
I certainly agree that validation here would be good.

**Comment by birdsarah** [comment]
@mattpap, sorry I'm being slow. can you clarify a little. are you saying you prefer 

````python
xgrid = Grid(plot=plot, dimension=0, ticker=LinearAxis().ticker) 
plot.renderers.extend([xgrid])
````
over 
````python
xgrid = Grid(dimension=0, ticker=LinearAxis().ticker) 
plot.add_layout(xgrid)
````

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
