### ISSUE TITLE
publication of weekly meeting minutes

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2071]
ping @pzwang @bokeh/core 

We should probably start putting these some place, we just need to make sure no non-public content is mingled. Where should they live? I am inclined to just throw them all on a single Wiki page for now, but other ideas would be welcomed.

**Comment by birdsarah** [comment]
excited about this. i think wiki page is a great start. i think posting them to the mailing list would be equally valid. meeting minutes tend to get less topical with age, so mailing list seems appropriate to me too.

**Comment by damianavila** [comment]
:+1:

**Comment by bryevdv** [comment]
We will publish minutes starting with tomorrow's meeting. Please be advised our minutes are usually somewhat rough.

**Comment by fpliger** [comment]
:+1:
