### ISSUE TITLE
Docs - getting the generated charts to appear?

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2077]
Hi all,

I'm building the docs locally, and have just noticed that on my local copy of http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#area the area, bar, donut etc. charts are not appearing.

I was getting the error message:
`WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting                                                             
` 

but then install graphviz locally (apt-get install graphviz) and it has gone away, but still no charts appearing. Any thoughts?

**Comment by bryevdv** [comment]
Just checking, did you do a `make clean` after installing graphviz?

**Comment by birdsarah** [comment]
Yep :s Is there a sphinx plugin as well?

**Comment by bryevdv** [comment]
yes but it is loaded in the `conf.py`

**Comment by birdsarah** [comment]
hmmmm... this isn't a priority, so i'm going to can this for now.
