### ISSUE TITLE
Is tools.names.append meant to work?

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2079]
Looking here: https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/tap.py#L46
````python
# in the broswer console, you will see messages when circles are clicked
tool = p.select(dict(type=TapTool))[0]
tool.names.append("mystuff")
````
The select works, but I don't see messages in the console. Am I missing something? (In the server example, I do see the PATCH-PUT as expected, but no "mystuff" message either.)

**Comment by bryevdv** [comment]
Do you have a renderer that you set `name="mystuff"` on? That is the intended use-scenario but it might be broken. If so we will probably just remove it since it somewhat duplicates the `renderers` field on the tool.

**Comment by bryevdv** [comment]
OH, you are talking about an actual example. I think that comment it out of date, I believe the default `console.log` was removed. You can see that it is working, though: if you click on one circle, it gets selected/highlighted.

**Comment by bryevdv** [comment]
![screen shot 2015-03-17 at 9 45 35 pm](https://cloud.githubusercontent.com/assets/1078448/6701745/f65583de-ccee-11e4-95ae-896efb837332.png)

**Comment by birdsarah** [comment]
Yep. As I said: "The select works, but I don't see messages in the console."

Was just checking in on whether there was a feature I should know about or just some out-dated code.

Hope all of this poking around isn't coming across as nit-picking, I'm just trying to get my ducks in a row.

Happy to do a PR to clean this up when I come up for air.

**Comment by bryevdv** [comment]
Nit-picking is good and welcomed, it's what separates exceptional things from merely good ones. We are not there yet but hopefully feedback like this will help get us there. Please don't stop. :)

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
