### ISSUE TITLE
HoverTool panel for annular wedge displays at center coordinates, not over wedge.

### ISSUE THREAD

**Issue by cyrusmaher** [bokeh/bokeh#2080]
There may also be an issue with the hit detection. I end up with the annotation for all wedges being displayed in the center of the concentric wedges.

**Comment by fpliger** [comment]
hi @cyrusmaher , could you paste an example code here so we can easily reproduce the issue (or maybe a screenshot or both :-) )? Thanks

**Comment by bryevdv** [comment]
There is a parameter to snap to the glyph center that defaults to true. I'm in my phone or I'd look it up but it's in the reference guide. 

Bryan

**Comment by cyrusmaher** [comment]
Thanks Bryan!! That's just what I needed. In future versions, Would it be possible (pretty please) to make the snap_to_data default coordinates the middle of the annular wedge patch? 

Also, in the process of putting together the example code below, I encountered a perhaps mildly interesting bug. For the `annular_wedge` call, if you swap "starts" and "stops" and switch the direction to "clock" instead of "anticlock", it seems to raise an issue with the hit detection even though what's displayed looks identical. Am missing something there or is that actually weird?

```python
import bokeh.plotting as bk
import pandas as pd
import math
from bokeh.models import HoverTool, ColumnDataSource

rad2deg = (180 / math.pi)
deg2rad = 1 / rad2deg
        
y_mins = [1] * 3
y_maxes = [2] * 3
start_angles = pd.Series([30, 45, 90])
stop_angles = pd.Series([40, 80, 120])

start_angles_2 = start_angles + 180
stop_angles_2 = stop_angles + 180

df = pd.DataFrame(
                    {
                        'x': 0,
                        'y': 0,
                        'ymin': y_mins, 
                        'ymax': y_maxes,
                        'starts': start_angles * deg2rad,
                        'stops': stop_angles * deg2rad
                    }
                )

df_s = ColumnDataSource(df)
TOOLS = "pan,wheel_zoom,box_zoom,reset,hover"
bk.output_file("test.html")
plot = bk.figure(width=1000, height=1000, tools=TOOLS)


plot.annular_wedge(x='x', y='y', 
                    inner_radius='ymin',
                    outer_radius='ymax',
                    start_angle='stops', # change to "starts"
                    end_angle='starts', # change to "stops"
                    direction="clock", # change to "anticlock"...now it works
                    source=df_s
                    )


hover = plot.select(dict(type=HoverTool))
hover.tooltips = [
    # add to this
    ("index", "$index"),
]
hover.snap_to_data = False
bk.show(plot)
```

**Comment by cyrusmaher** [comment]
Here's a screenshot of the behavior described above. The indices for all wedges show up even when not hovered over any of the glyphs.
https://www.dropbox.com/s/ys057gvadxc5m1n/Screenshot%202015-03-17%2015.44.20.png?dl=0

**Comment by bryevdv** [comment]
@cyrusmaher Looks like a bit of weirdness. I can imagine that using a different `direction` might not have been a well-tested configuration. I will mark this as a `bug` for that reason but I can't speculate on when this will be gotten to. In the mean time I recommend configuring your data to work with `antilock` (which works, if I am not mistaken?)

**Comment by cyrusmaher** [comment]
Yup, that works! Thanks for taking a look!!

**Comment by bryevdv** [comment]
confirmed here is still a hit-testing issue with `direction="clock"` in `0.12dev`
