### ISSUE TITLE
Simplifying glyph units

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2087]
I am working on #2086 at the moment, and a few thoughts about how we handle units have floated through my head. I'd like to get some feedback on some ideas and perhaps the start of a proposal too.

In theory, all of our glyphs can accept either data or screen space coordinates for basically any coordinate or distance. I say "in theory" because this capability has not been thoroughly tested, and I can imagine it has numerous bugs. In fact I am quite certain alot of the hit-testing machinery will fall over with screen units in some places. Here is the thought that occurred to me:

> "screen space" coordinates are (should be) only for annotations 

Is that right? I am trying to think of use cases for screen space coordinates for *data*, and can't. Screen space *distances* (like marker size), sure. But not really for positions. We have never used them that way, I don't think we have ever had  a single example that does this, or gotten a question about it. Anything I can think of that you would want to absolutely position is really some kind of annotation. So here is my proposal:

* Split `DataSpec` into:
 - `Coordinate` (which is always assumed to be data space values)
 - `Distance` (has a corresponding *visible attribute* for `_units`, can be either screen or data space)
 - `ScreenDistance` used for marker size, e.g. (no corresponding `_units`)
 - `DataDistance` used for circle radius, e.g. (no corresponding `_units`)
 - `Position` this is the same as `Distance`, to allow data/screen coords *just for annotations*

So then markers, for instance, would look like this:
```
class Marker:
    x = Coordinate
    y = Coordinate
    size = ScreenDistance
```

Adding these assumption and narrowing these properties would afford a huge simplification all over the BokehJS renderer logic and also lend several things to better testing because the branching is not so completely insane.

What about when you do want to put a `Rect` at some specified screen spot? I propose making new annotation types that can display glyphs at either data locations or screen locations (by accepting `Position`). That's fine and simple, because the annotation can convert the screen positions to data space at render time. I also think we can get by with just supporting a few glyphs for annotations. Of note: annotations would not participate in auto-ranging computations, and hit-testing (if it is needed) can just be done brute-force by the annotation. 

The main point of this is: ***it keeps screen space inputs completely out of normal rendering, hit-testing, and auto-ranging code paths*** and this would be a *huge, truly incredible* simplification. It would also add conceptual clarity in some places where specifications are muddy or overly general. 

Thoughts? I think this can be a significant improvement to the stability, reliability, consistency, and maintainability of the BokehJS codebase. I actually think this is one of the most important things we can do to improve the BokehJS codebase. 

ping @bokeh/core, @pzwang  and @mattpap especially

**Comment by aterrel** [comment]
+100

Even trying to explain to a user the difference between data space and screen space is a challenge.

**Comment by bryevdv** [comment]
I have thought of one tangential use case: pixel offsets for when you want to label markers with text offset at a constant distance. I am confident this can still be made to work in a more streamlined fashion, or perhaps is is also handled as an annotation somehow.

**Comment by bryevdv** [comment]
Upon further thought, things like that should absolutely be a "labels" annotation of some sort and not a data glyph, in my opinion.

**Comment by pzwang** [comment]
Yep, +1 on this

**Comment by bryevdv** [comment]
OK, I will start a PR based of the auto-ranging one, and we can target both for 0.9

**Comment by bryevdv** [comment]
FWIW there are still several features to add to BokehJS (some of them pretty big, too), but this may be the last non-trivial "change" or "fixup" I can really think of.
