### ISSUE TITLE
CheckboxEditor and BooleanFormatter bugs

### ISSUE THREAD

**Issue by rhjmoore** [bokeh/bokeh#2089]
I have some code that shows a DataTable, and one of the fields is meant to be an editable checkbox. The code below should work; unfortunately it only shows a blank cell and no editing is possible. Looking at the HTML produced, the div itself is empty when not selected, and filled with a zero height input checkbox when selected.

Am I doing something wrong or is this a bug?
```
source_control = <a pandas DataFrame; field "Length" is a Boolean dtype>

columns_controls=[
    TableColumn(field='Test ID', title='Test ID',width=60),
    TableColumn(field='Field', title='Field',editor=StringEditor()),
    TableColumn(field='Length', title='Length',editor=CheckboxEditor(),
        formatter=BooleanFormatter(icon='check')),
]
tab_controls=DataTable(height="auto", source=source_controls,
    columns=columns_controls,fit_columns=True,editable=True)
```

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by mattpap** [comment]
> Discussion is now more than 3 months old. Can re-open if renewed interest.

@birdsarah, on what basis you are closing issues like this? Also, you're misusing `wontfix` label. By setting `wontfix` you say that we decided that this doesn't fix into bokeh, for some reason that should be expressed in the issue.

**Comment by bryevdv** [comment]
The basis is that there was a discussion and decision in FD to close `type:discussion` issues that have seen no conversation in more than three months. The `reso:wontfix` is a temporary label until a new one is added per BEP-2.  A discussion should (fairly quickly) result in a new specific feature, task, or bug issue, an answer to a question. There is no point in keeping discussion issues open with zero activity indefinitely.

**Comment by bryevdv** [comment]
@mattpap In this specific case, it's possible that it should be switched to `bug` (or result in a new `bug` issue). You are welcome to do either of those if that is appropriate.

**Comment by dennisobrien** [comment]
I'm also trying to use CheckboxEditor in a DataTable widget without any success.  I see example code using IntEditor, StringEditor, and others, but nothing using CheckboxEditor.

* Display a DataTable that uses CheckboxEditor.
* No checkbox is visible in the column, even for True values.
* Double click one of the cells to make the checkbox appear.
    * Chrome: the checkbox appears off center and is not toggleable.
    * Firefox: the checkbox appears centered and is toggleable.
* Click on another cell to try to remove focus, but nothing happens.  Errors in the JS console:
    * Firefox: "TypeError: this.data[e] is undefined"
    * Chrome: "Uncaught TypeError:  Cannot set property '0' of undefined"

The stack trace looks like this:
* a.190.t._setField
* a.190.t.setField
* a.182.e.applyValue
* a.236.n.execute
* commitCurrentEdit
* a.235.n.commitCurrentEdit
* handleClick
* a.18.Q.event.dispatch
* a.229.r.dispatch
* a.18.Q.event.add.m.handle

I don't know enough about SlickGrid and CoffeeScript to follow this much further, but here's the `applyValue
```
applyValue: (item, state) ->
    # XXX: In perfect world this would be `item[@args.column.field] = state`.
    @args.grid.getData().setField(item.index, @args.column.field, state)
```

**Comment by bryevdv** [comment]
@dennisobrien Yes if that's OK, a new `bug` issue would be a cleaner path. Thanks!

**Comment by dennisobrien** [comment]
Will do.

Most of the weirdness I was seeing was due to me failing to add the column used for the checkbox to the ColumnDataSource.  There are still issues, but not as bad as my previous comment suggested.

**Comment by chrstof** [comment]
I still see this issue using bokeh 12.4 except that Chrome does not show any checkbox, whether I click the field or not.

Is there any work planed to fix that issue?

Thanks!

**Comment by jbrockmendel** [comment]
FWIW, on 0.12.4 I have a case where double-clicking leads to a offset checkbox
![checkboxscreenshot](https://cloud.githubusercontent.com/assets/8078968/25552705/6fec5d4a-2c55-11e7-97b1-887f96a1e73f.png) which cannot be checked.

It belongs in a separate issue, but for now: DateEditor is functional but formatting poorly.
![dateeditorscreenshot](https://cloud.githubusercontent.com/assets/8078968/25552714/a8e56e16-2c55-11e7-8873-e5415e66f5ba.png)

Screenshots are both from Chrome, on OSX.

**Comment by nthomsencph** [comment]
Experiencing this exact bug for BooleanFormatter. Chrome states that `Bokeh items were rendered successfully` but nothing shows up in column. Any plans for this?

**Comment by bryevdv** [comment]
@nthomsencph this issue is 8 years old. There is almost none of the same code left, in fact BokehJS was entirely rewritten in another language in the mean time. Please open a new issue with the Bug Report template and include all the required information.
