### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by bkreider** [bokeh/bokeh#2090]
It would be nice to have a glossary of terms.  I've intuitively grasped linked-brushing, but I realized I have never seen an actual definition of linked or brushing.  Bryan pointed me to the WP article here: http://en.wikipedia.org/wiki/Brushing_and_linking.

**Comment by bryevdv** [comment]
I'm going to close this for lack of activity. I don't myself know what all would be put in such a glossary and there has been no input elaborating.
