### ISSUE TITLE
Visual Improvement for examples/glyphs/taylor_server.py

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2096]
**Order** slider box overlaps **Expression** box if moved all the way to the right.

![screen shot 2015-03-23 at 12 10 12 pm](https://cloud.githubusercontent.com/assets/1417520/6785785/d4d1aa4c-d155-11e4-8af2-a5dc2414322c.png)

**Comment by bryevdv** [comment]
Really involves exposing more layout options to `vbox`, `hbox`, etc.

**Comment by almarklein** [comment]
I did some experiments with different approaches for box layouts: http://www.almarklein.org/html_boxlayout.html which might be useful. I think Bokeh uses `display: box`?

**Comment by bryevdv** [comment]
This is covered by the general layout work that is underway, I am closing this as a dupe.
