### ISSUE TITLE
decimal.Decimal cannot be sent across session

### ISSUE THREAD

**Issue by lukebarnard1** [bokeh/bokeh#2098]
When trying to give data of type decimal.Decimal as data sources to plots, the BokehJSONEncoder does tries to serialise the Decimal object with the standard built-in JSON encoder. This causes an exception "Decimal('...') not JSON serializable". The solution is to edit BokehJSONEncoder.trasnform_python_types to account for this possibility. I have tested the solution and it works.

**Comment by bryevdv** [comment]
If you could submit a PR with your updated code that would be very appreciated.

**Comment by lukebarnard1** [comment]
I've done a pull request, it's number #2099

**Comment by bryevdv** [comment]
Awesome, thanks!
