### ISSUE TITLE
`TypeError 'u' is null` when plotting

### ISSUE THREAD

**Issue by brianbreitsch** [bokeh/bokeh#2102]
I import Bokeh like this:

    from bokeh.plotting import figure, output_file, output_notebook, show
    from bokeh.plotting import Plot, GridPlot
    from bokeh.models import ColumnDataSource
    from bokeh.models.glyphs import Line
    ...

Then plot like so:

    output_notebook()
    time = np.arange(20)
    y = np.random.rand(len(time))
    data = ColumnDataSource(data={'time': time, 'y': y})
    plot = Plot(title='data', plot_width=250, plot_height=250)
    plot.add_glyph(data, Line(x='time', y='y'))
    show(plot)

Ultimately, I get the following error (see line 7):

    "Bokeh: setting prefix to" "/" jquery.min.js:322:15795
    "Bokeh: setting log level to: 'info'" jquery.min.js:301:1950
    "Bokeh: Realizing plot:" jquery.min.js:300:31469
    "Bokeh:  - modeltype: GridPlot" jquery.min.js:300:31469
    "Bokeh:  - modelid: e6b3d2e6-3d61-4e20-ada1-eac5c5aee3d3" jquery.min.js:300:31469
    "Bokeh:  - elementid: 9627e5e3-bde4-4637-a874-130a77a37ea9" jquery.min.js:300:31469
    TypeError: u is null
    Stack trace:
    u</i.prototype._get_mappers@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:301:28723
    u</i.prototype.initialize/<@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:301:27147
    l</s.prototype._get_prop@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:301:6641
    l</s.prototype.get@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:301:6425
    M</r.prototype.initialize@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:303:27549
    e.View@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:299:29835
    r@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:300:26259
    r@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:303:26810
    e@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:301:29812
    h</i.prototype.build_children@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:304:18669
    h</i.prototype.initialize@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:304:17886
    e.View@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:299:29835
    r@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:300:26259
    i@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:304:17651
    @https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:12:24
     re.Callbacks/c@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:297:23656
    re.Callbacks/p.add@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:297:23972
    re.fn.ready@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:297:26077
    re.fn.init@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:297:21182
    re@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:296:29376
    @https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040 line 4 > eval:1:1
    .globalEval@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040:4:4231
    .domManip@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040:5:21389
    .append@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040:5:18980
    OutputArea.prototype._safe_append@https://192.168.3.137:8888/static/notebook/js/outputarea.js?v=20150325213040:414:13
    OutputArea.prototype.append_display_data@https://192.168.3.137:8888/static/notebook/js/outputarea.js?v=20150325213040:534:13
    OutputArea.prototype.append_output@https://192.168.3.137:8888/static/notebook/js/outputarea.js?v=20150325213040:320:13
    OutputArea.prototype.handle_output@https://192.168.3.137:8888/static/notebook/js/outputarea.js?v=20150325213040:234:9
    CodeCell.prototype.get_callbacks/<.iopub.output@https://192.168.3.137:8888/static/notebook/js/codecell.js?v=20150325213040:456:21
    Kernel.prototype._handle_output_message@https://192.168.3.137:8888/static/services/kernels/kernel.js?v=20150325213040:997:13
    .proxy/i@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040:4:5486
    Kernel.prototype._handle_iopub_message@https://192.168.3.137:8888/static/services/kernels/kernel.js?v=20150325213040:1024:13
    Kernel.prototype._finish_ws_message@https://192.168.3.137:8888/static/services/kernels/kernel.js?v=20150325213040:866:17
    .proxy/i@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040:4:5486
    deserialize@https://192.168.3.137:8888/static/services/kernels/serialize.js?v=20150325213040:60:13
    Kernel.prototype._handle_ws_message@https://192.168.3.137:8888/static/services/kernels/kernel.js?v=20150325213040:857:9
    .proxy/i@https://192.168.3.137:8888/static/components/jquery/jquery.min.js?v=20150325213040:4:5486

**Comment by brianbreitsch** [comment]
Also just updated packages (I'm using Anaconda 3 distribution); no longer requires `force=True` but still getting `u is null` error.

**Comment by brianbreitsch** [comment]
Looks like I might have jumped the gun on submitting this issue...
Turns out normal/simple/high-level plotting works, so I guess it has something to do with my actual lower-level plotting code (essentially the following):

    def plot(self, fig):
            plots = []
            data = ColumnDataSource(data=self.buffers)
            for key in self.outputs.keys():
                plot = Plot(background_fill="#efe8e2", border_fill='white', 
                                        title=key, plot_width=250, plot_height=250)
                plot.add_glyph(data, Line(x='time', y=key, line_color='black', line_width=2))
                plots.append(plot)
            grid = GridPlot(children=[plots], title="tracking outputs")
            return grid

I checked and nothing's out of sorts with `self.keys()` or `key`.

**Comment by brianbreitsch** [comment]
SOLVED?

It turns out that `Plot` requires the `x_range` and `y_range` parameters.
I don't know if this is by design, and I don't see it in documentation. Perhaps we can make a more informative warning than `'u' is null`?

Tomorrow I will look into the code to try to find out exactly why...

**Comment by bryevdv** [comment]
There is a new introduction to the User's Guide that explains the different levels of interfaces in Bokeh in greater detail than has been available before:

http://bokeh.pydata.org/en/latest/docs/user_guide/intro.html

In particular, the low level interface is really just a serialization layer, it does not provide any bells or whistles or much help at all assembling plots. There is an open issue regarding adding higher level integrity validation:

https://github.com/bokeh/bokeh/issues/602

But I can't speculate as to when then might be done.
