### ISSUE TITLE
Setting up the css style of tooltip (HoverTool)?

### ISSUE THREAD

**Issue by GildedHonour** [bokeh/bokeh#2103]
How can I setup the css styles of this kind of a toolpit:

![screen shot 2015-03-26 at 14 41 49](https://cloud.githubusercontent.com/assets/2032888/6842102/7c37026a-d3c6-11e4-867e-faf509b2fd74.png)

In particular, the color of the text and width of the border inside it, these look yellow in my example. I found out that it had to with `.bk-tooltip` class but whatever I tried it didn't pan out. Your suggestions?

**Comment by GildedHonour** [comment]
Nobody knows?

**Comment by fpliger** [comment]
@GildedHonour at the moment you can't "easily" customize the tooltips style. We recently added a way to inject some customization directly passing strings to the hover tool to customize it. See https://github.com/bokeh/bokeh/blob/master/examples/glyphs/colors.py. Maybe @mattpap have some other tricks or suggestions in mind.

We have some ideas to add stronger customization patterns and this is definitely something we want to improve in the next releases.

**Comment by bryevdv** [comment]
Actually tooltip can be passed custom html now. See examples/glyphs/sprint.py (or similar, on my phone can't check easily)

**Comment by birdsarah** [comment]
@GildedHonour did you get it working?

**Comment by bryevdv** [comment]
No updates, closing.

**Comment by bcipolli** [comment]
I'm looking to restyle hover tools. Links above no longer work, and discussion in the Google Group didn't seem to lead anywhere.

What's the best way to do this in `0.12.1`?

**Comment by bryevdv** [comment]
Custom tooltips:

http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#custom-tooltip
