### ISSUE TITLE
conda packages needs to use versioneer to create the _version.py file

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#2104]
Right now, there is an asymmetry between our conda packages and the `setup.py sdist` generated version. The second one use versioneer to generate a `_version.py` file containing the tag and full hash in a `get_versions` function. This does not happen when we create the conda package, so it is missing this function... 
NOTE: the conda packages generated by Ilan have this function available because he built the conda packages directly from the pypi package, the last 0.8.2 release on binstar and any of our devel builds have this asymmetry.
We should find a way to make versionner to generated the file when we conda build the package, or provide our own `_version.py` when we conda build...

**Comment by bryevdv** [comment]
If conda build has the right hooks I'd say lets just replace _version.py the way versioneer does when you use sdist.

**Comment by bryevdv** [comment]
@damianavila is this still outstanding / relevant?

**Comment by damianavila** [comment]
We currently provide the packages to be upload to repo.cio... so I think the asymmetry is no longer present/relevant. Let's close this one (I will reopen it if it it is needed).
