### ISSUE TITLE
ServerDataSource auto_bounds should be set to False as default

### ISSUE THREAD

**Issue by babboste** [bokeh/bokeh#2110]
ServerDataSource.transform['auto_bounds'] property is set to True by default.
This causes the fact that even if x_range and y_range are set to some interval, they are not taken into account and all the data_source range is plotted.
This seems to be in contrast with the standard usage of server side resampling and sub-ranging. In case a huge dataset is to be "explored", it should be very usefull to start by default with some small ranges, and one expects that setting x_range and y_range should be enough.

Or may be it would be nice to have this behaviour described in the ServerDataSource documentation, with some hint to set auto_bounds to False in order to make ranges work as expected.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
