### ISSUE TITLE
Hover tool tips not showing data in Firefox

### ISSUE THREAD

**Issue by machiela** [bokeh/bokeh#2122]
It appears there is an issue with propagating the hover tool tips with data when using Firefox browser. My plots with hover tool tips display fine in IE and Chrome, but not Firefox. Also, the example periodic table (http://bokeh.pydata.org/en/latest/docs/gallery/periodic.html) behaves similarly where only question marks (???) appear in the hover tool box.

**Comment by bryevdv** [comment]
I have not personally encountered this problem on FF on OSX. Can you provide more specific information about versions? (Bokeh, OS, browser, etc.)

**Comment by machiela** [comment]
The periodic table on this page (
http://bokeh.pydata.org/en/latest/docs/gallery/periodic.html) is a good
example. From the header, it looks like Bokeh 0.8.2. I am having issues
with displaying tooltips on Firefox 31.4.0 on a Windows 7 Pro as well as
Firefox 31.4.0 on Mac OS X Yosemite. Attached is an example of what I am
seeing.

**Comment by bryevdv** [comment]
The attachment did not make it to GH. Here is a screenshot of FF 36.0 on OSX:

![screen shot 2015-03-31 at 2 49 25 pm](https://cloud.githubusercontent.com/assets/1078448/6927784/48def1dc-d7b5-11e4-81eb-ebc6c3bced3e.png)

Can you try testing on a newer version of FF?

**Comment by machiela** [comment]
Here is a screenshot with Firefox 31.6.0 on Windows 7. The version info says Firefox is up to date.

![hover_tooltip](https://cloud.githubusercontent.com/assets/6854002/6928200/89928fd0-d7c0-11e4-82e3-02e536f74e71.png)

**Comment by machiela** [comment]
Looked into standard Firefox (non ESR), and it seems to be working now on v32. Is there a recommended version of Firefox for displaying Bokeh 0.8+ plots?

![hover_tooltip](https://cloud.githubusercontent.com/assets/6854002/6928379/9df52e0a-d7c1-11e4-96bb-8b4d315b1692.png)

**Comment by bryevdv** [comment]
You can try newer versions here: https://www.mozilla.org/en-US/firefox/channel/

**Comment by bryevdv** [comment]
It looks like there is now. :) I wish we had the resources/bandwidth to look into this problem but realistically it is not going to be a high priority if a newer browser version works.

**Comment by machiela** [comment]
No worries. Looks like the ESR version of Firefox will be updated and compatible later this summer, so just a few months of potential incompatibility. Keep up the spectacular work!
