### ISSUE TITLE
bokeh.models.glyphs.ImageURL scaling rounding error

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2127]
I am trying to import and scale an image (992px x 1024px) using models.glyphs.ImageURL and set the h and w kwargs to one (scale the image to an aspect ratio of 1). The scaled image is always a pixel or two greater in height, leading the image to overhang the x-axis. This is true whether or not the dilate kwarg is set to True or False.

``` python
from bokeh.models import Plot, Range1d, LinearAxis
from bokeh.models.glyphs import ImageURL
from bokeh.plotting import output_notebook, show
output_notebook()

url = 'CIE_1931_Chromaticity_Diagram_CIE_1931_2_Degree_Standard_Observer_Large.png'  #RGBA png 992px x 1024px 

plot = Plot(title='CIE 1931 Chromaticity Diagram',
            x_range=Range1d(start=0, end=1),
            y_range=Range1d(start=0, end=1),
            plot_width=500,
            plot_height=500)

image = ImageURL(url=[url], x=[0.0], y=[1.0], w=[1.0], h=[1.0], dilate=True)

plot.add_glyph(image)

x_axis = LinearAxis(axis_label="x")
y_axis = LinearAxis(axis_label="y")
plot.add_layout(x_axis, 'below')
plot.add_layout(y_axis, 'left')

show(plot)
```

![screenshot 2015-03-31 at 8 11 09 pm](https://cloud.githubusercontent.com/assets/2198981/6933952/2899f840-d7e2-11e4-9412-ac4128d0d54f.png)

Using Bokeh version 0.8.2
type:bug

**Comment by bryevdv** [comment]
Went to evaluate this but it's no longer runnable as-is and once that is resolved the image to display is not available. Closing as `norepro` for now
