### ISSUE TITLE
Selections not working with nominal/categorical axis

### ISSUE THREAD

**Issue by bald** [bokeh/bokeh#2134]
Selections (such as `box_select` or `tap`) are not working correctly when a nominal/categorical axis is used. The *alpha* of unselected data points is **not** changed.

Here are short examples:

### nominal/categorical axis - selection not working

    import bokeh.plotting as bk
    bk.output_file("example.html",)
    x = ["a", "b", "c"]
    y = [0.5, 10.0, 5.0]
    p = bk.figure(title = "nominal/categorical axis", x_range = x, tools = ["box_select"])
    p.circle(x = x, y = y)
    bk.show(p)

### numerical axis - selection working

    import bokeh.plotting as bk
    bk.output_file("example.html",)
    x = [0.5, 10.0, 5.0]
    y = [0.5, 10.0, 5.0]
    p = bk.figure(title = "numerical axis", tools = ["box_select"])
    p.circle(x = x, y = y)
    bk.show(p)

This issue might be related to #2131 and #2064.

**Comment by bryevdv** [comment]
What Bokeh version?

**Comment by bald** [comment]
Bokeh 0.8.2
Python 3.4.3

**Comment by bryevdv** [comment]
This may be fixed in master, please try out the dev build that will be released Friday.

**Comment by bryevdv** [comment]
PR submitted, fix may be in Friday dev build after all.

**Comment by bald** [comment]
Thanks! It's working (0.9 dev)
