### ISSUE TITLE
enlarged tool icons after reload

### ISSUE THREAD

**Issue by brianbreitsch** [bokeh/bokeh#2147]
Hello!
I'm using Firefox 36.0.4.
The first time I make plots with Bokeh, everything works great.

I import:

    from bokeh.plotting import output_notebook, show, figure
    from bokeh.models import Range1d
    from bokeh.charts import Histogram

Then make this plot (sorry it's so large):

![screen shot 2015-04-04 at 5 33 43 pm](https://cloud.githubusercontent.com/assets/4730272/6995113/1f527d36-daf1-11e4-8808-8f40d1ee5943.png)

As soon as I re-execute my import cell, the tool icons become enlarged like so:

![screen shot 2015-04-04 at 5 37 45 pm](https://cloud.githubusercontent.com/assets/4730272/6995123/59f53898-daf1-11e4-8811-60d173ff9282.png)

If I refresh the page, I get:

![screen shot 2015-04-04 at 5 40 55 pm](https://cloud.githubusercontent.com/assets/4730272/6995137/d10ca39e-daf1-11e4-9bfd-f5a42cdc840a.png)

And the console output:

![screen shot 2015-04-04 at 5 39 59 pm](https://cloud.githubusercontent.com/assets/4730272/6995135/b8d0d692-daf1-11e4-9f0b-23b906e7624a.png)

Not a major problem--I just need to avoid executing the import cell more than once. Otherwise, I can restart the kernel and reload the page to get normal-looking tool icons again. Hopefully this information will be of use in continued development (I apologize if this has already been dealt with elsewhere, but I couldn't find it in Issues or on Google or SO).

(P.S. Love the library you guys--I'm excited to see what's to come!)

**Comment by damianavila** [comment]
Can you tell us which version of Bokeh are you using? AFAIK, this was fixed some time ago...

Thanks!

**Comment by brianbreitsch** [comment]
Ah, yes of course, the version I had at the time of post was:
`bokeh 0.8.2 np19py33_0`

I see now there is a version `bokeh 0.8.2 np19py34_0`, I'll see if that helps.

**Comment by brianbreitsch** [comment]
You're right--that update fixed it! Well, at least now it's documented. Thanks!
