### ISSUE TITLE
Add an option to remove the `help` button of the bokeh toolbar

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#2156]
It's currently possible to set on or off any component of the bokeh toolbar, except the `help` button.

The only way to remove it is to completely disable the toolbar.

From [this](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/RftDek1c70s) google groups question.

**Comment by gene-telligent** [comment]
Made a fix for it in #2165 -- now you should be able to include the Help icon (with a custom tooltip and link) at your discretion. It's still on by default but can be easily turned off.

**Comment by ijmiller2** [comment]
What's the proper syntax for this option then? Not seeing (but could be missing) it in the docs.

**Comment by ijmiller2** [comment]
Never mind, I figured it out. Works if you just include an explicit list for the tools parameter within the initialization of the figure object, such as in the [ImageHover example](https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#image-hover): 

```python
plot = figure(plot_width=width, plot_height=height,
     tooltips=TOOLTIPS, tools="pan,wheel_zoom,box_zoom,reset")
```
