### ISSUE TITLE
Color tuples not supported 

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2161]
As reported in this [m.l. discussion](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!topic/bokeh/AoGxLNfa0uU), colors specified as rgb tuples are not working. Neither a 3-tuple of integers (r,g,b) between 0 and 255 or a 4-tuple of (r,g,b,a) where r,g,b are integers between 0..255 and a is between 0..1.

Here's the reported code not working (modified to pass tuple of integer from 0 to 255):

```Python
import matplotlib.pyplot as plt
import numpy as np

# Import bokeh
import bokeh
import bokeh.plotting
from bokeh.colors import RGB

NUM_COLORS = 20

cm = plt.get_cmap('gist_rainbow')

# Define the output file
bokeh.plotting.output_file(filename='quantities.html')

# Define the figure
figure = bokeh.plotting.figure(plot_width=1000, plot_height=600)

# Go through the number of colors
for ix in range(NUM_COLORS):

    # color will now be an RGBA tuple
    # was color = cm(1.*ix/NUM_COLORS)
    color = np.asarray(cm(1.*ix/NUM_COLORS)) * 255
    # IT WORKS WITH:
    # color = RGB(*color).to_hex()

    # Define generic data
    x = np.arange(0, 10)
    y = np.arange(0, 10) + ix

    # Plot the data bokeh style
    figure.line(x, y, line_color=color, line_width=2, legend=str(ix))
    figure.scatter(x, y, color=color)

    # Plot the data mpl style
    #plt.plot(x, y, color=color)

# Show the bokeh plot
bokeh.plotting.show(figure)

# Show the matplotlib plot
#plt.show()
```

If the colors is explicitly converted to hex (like in the commented lines of the above example) it does work

**Comment by rothnic** [comment]
Independently ran into this issue. The tuple is not correctly identified in [_match_data_params](https://github.com/bokeh/bokeh/blob/master/bokeh/plotting_helpers.py#L96), then ends up falling through and being identified as a datasource [later on](https://github.com/bokeh/bokeh/blob/master/bokeh/plotting_helpers.py#L113).

Would it make sense to perform the transformation here in place? If I let the tuple pass into the statement at Line 96, and allow it to be directly assigned, the result is this error: `expected an element of either String, Dict(String, Either(String, Color)) or Color, got (50.1, 100.1, 50.1)`. I can create a Color there, but wasn't sure if there is a preferred location.

One additional thing I noticed is that a Color is defined as one of these types:

```
        types = (Enum(enums.NamedColor),
                 Regex("^#[0-9a-fA-F]{6}$"),
                 Tuple(Byte, Byte, Byte),
                 Tuple(Byte, Byte, Byte, Percent))
```
Where a Byte is an integer type. It is possible people will input floats, as I was doing in the example, so we likely want to handle that case.
