### ISSUE TITLE
Plotting None/nan values fails with log scale axis

### ISSUE THREAD

**Issue by bald** [bokeh/bokeh#2162]
A list containing `None` values is not correctly plotted, if 
- more than one `None` value is in the list, and
- a log scale is used

Something like `[7.1, None, 7.0, 7.5, None, 9.5, 3.0]` is not plotted correctly, while with `[1.1, None, 2, 3.5, 4, 5.5, 6.0]` everything is fine. Interestingly, both lists are plotted fine, if no log scale is used.

Here is an example plot:
![image](https://cloud.githubusercontent.com/assets/574252/7071209/2d61c674-dee4-11e4-85e6-090b939e92d8.png)
This was generated with the following code:

```
from bokeh.plotting import figure, output_file, show, ColumnDataSource

# prepare some data
x = ["a", "b", "c", "d", "e","f", "g"]
y0 = [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
y1 = [1.1, None, 2, 3.5, 4, 5.5, 6.0]
y2 = [7.1, None, 7.0, 7.5, None, 9.5, 3.0]
chartData = {"x": x, "y0": y0, "y1": y1, "y2": y2}

# output to static HTML file
output_file("log_bug.html")

# create a new plot
p = figure(
y_axis_type="log",
y_range=[0.001, 10**2],
x_range = x
)
df = ColumnDataSource(chartData)

p.circle(x = "x", y = "y0", legend="no 'None', everything is fine", size=8, source = df)
p.circle(x = "x", y = "y1", legend="1x 'None', everything is fine", size=8, color = "green", source = df)
p.circle(x = "x", y = "y2", legend="2x 'None', bug", size=8, color = "red", source = df)

# show the results
show(p) 
```

[Bokeh 0.9 dev, Python 3.4]

**Comment by bryevdv** [comment]
Hi @bald I am not actually sure that it "working" with `None` was a conscious design choice, although I can see the utility in it for aligned series where some series have missing data. As a workaround, can you replace the `None` with `nan` values and see if that works for now?

**Comment by bald** [comment]
As far as I remember, my first try was with ´nan´. That didn't work either.
[Can't test this right now, will do it tomorrow]

**Comment by bald** [comment]
Another interesting observation on that topic:

As a workaround, I tried to replace `None` with really low values like `10**-10`. Same behaviour as before.

However, if I change the values to `10**-5`, everything works as expected. To make sure, that these values are never displayed, I disabled the `wheel_zoom` tool.

**Comment by epfahl** [comment]
Any updates on this?  This is going to be a common problem when concatenating dataframes in preparation for brush linking.

**Comment by bryevdv** [comment]
@epfahl It still seems to be an issue in master and 0.9.1 I've added it to a new 0.9.2 milestone. (We are also still working on implementing better project management, as the team and effort has grown.)

**Comment by epfahl** [comment]
@bryevdv  Excellent.  Thanks for the response.

**Comment by delicious-cake** [comment]
still an issue in 0.12.1

**Comment by bryevdv** [comment]
@birdsarah you were looking at log mappers and `NaNs`? or was that just color mappers

@delicious-cake with 700 open issues and only a handful of continually active contributors, it's an unfortunate reality that many issues will take a long time to even get looked at.

**Comment by birdsarah** [comment]
Only ColorMappers

**Comment by bryevdv** [comment]
This got fixed at some point (perhaps @clairetang6 recent work). New output with `0.12.4` pre build off master:

<img width="649" alt="screen shot 2016-12-15 at 8 27 56 pm" src="https://cloud.githubusercontent.com/assets/1078448/21249637/15a58dfc-c305-11e6-8ced-dfec553d53b1.png">

**Comment by clairetang6** [comment]
@bryevdv I think this was fixed before my PR [5477](https://github.com/bokeh/bokeh/pull/5477). And actually PR 5477 breaks this if you take away the user set y range bounds `y_range=[0.001, 10**2]`. 

![image](https://cloud.githubusercontent.com/assets/4241244/21251832/19fd2490-c306-11e6-9eca-6a50a2459d1e.png)

I think it's probably ok to leave this issue closed. The bug is caused by the same problem as for issue [5549](https://github.com/bokeh/bokeh/issues/5549).

**Comment by clairetang6** [comment]
Taking away the user set y range bounds, and changing the last glyphrenderer from a circle to a line to better see what's going on with the None values, 

before PR [5477](https://github.com/bokeh/bokeh/pull/5477):
![image](https://cloud.githubusercontent.com/assets/4241244/21252278/73ff82f4-c30a-11e6-9b55-2422cf53f377.png)

after PR  [5477](https://github.com/bokeh/bokeh/pull/5477):
empty plot like above comment. 

after hotfix in first commit of PR [5561](https://github.com/bokeh/bokeh/pull/5561):
![image](https://cloud.githubusercontent.com/assets/4241244/21252407/53b42350-c30b-11e6-89f9-9712b90b0eb1.png)
