### ISSUE TITLE
Add root_dir for absolute mode Resource 

### ISSUE THREAD

**Issue by bkief** [bokeh/bokeh#2166]
We find it useful to host the bokehjs resource on a shared network location. This allows for lightweight HTML plots to use a predefined and static network location for the JS payload.

**Comment by bkief** [comment]
Still working on updating tests... I should get to it in a couple of days

**Comment by bryevdv** [comment]
@mattpap @damianavila, @bkief expanded on this use-case here: https://github.com/bokeh/bokeh/pull/2167#issuecomment-93885213 Can you guys chime in with thoughts.

**Comment by bryevdv** [comment]
Closing, as there was never any follow up response.
