### ISSUE TITLE
display offsets for text and other glyphs

### ISSUE THREAD

**Issue by rhr** [bokeh/bokeh#2169]
A very useful feature of matplotlib is the ability to specify data-independent display offsets for things like text annotations of points - it would be great to have this in bokeh as well!

**Comment by bryevdv** [comment]
Hi @rhr this is actually something we have just recently been laying some groundwork for doing properly. We used to try and have they glyphs themselves handle both "data space" and "screen space" coordinates, but this was already enormously complicating the standard render/selection/index code path. Adding offsets would make it unmanageable. So, we pulled the screen space capability out in #2109 with the intention that anything specified in screen units (either position or offsets) really counts as an annotation. So we will be adding back labels as annotations (with their own simpified code path that does not participate in selection, etc.) in the very near future.

**Comment by bryevdv** [comment]
This is already possible for `Text` and is also possible in the new `Label` annotation type.
