### ISSUE TITLE
  Graph example code in User Guide is wrong. Show,output_file is not in Bokeh.charts

### ISSUE THREAD

**Issue by chrisfs** [bokeh/bokeh#2170]
If you try to run the example code for high level line graphs, you will get an error. 
In http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#line
the code line is:  from bokeh.charts import Line, show, output_file
this will give you:
ImportError                               Traceback (most recent call last)
<ipython-input-1-7a03361137ee> in <module>()
----> 1 from bokeh.charts import Line, show, output_file

ImportError: cannot import name show

The correct code would be
from bokeh.charts import Line
from bokeh.plotting import output_file,show

Same error appears in all the sample graph codes (Area,Bar,Boxplot,Dot, etc)

**Comment by bryevdv** [comment]
You are looking at the docs for the latest release, but you have an older version installed. You can see that version 0.8.2, which is what the `latest` docs link points to, does now have those functions  available:

https://github.com/bokeh/bokeh/blob/0.8.2/bokeh/charts/__init__.py#L21-L23

If you need to access older versions of the docs, you can do so by replacing "latest" with the version number of interest, for example:

http://bokeh.pydata.org/en/0.7.1/

Note that old versions of the docs are only available back to version 0.7.0 on pydata.org.

**Comment by birdsarah** [comment]
@chrisfs - my bad :s - sorry I didn't realize the history here. In case you were wondering, `bokeh.charts` and `bokeh.plotting` both work and they both import from `bokeh.io` 

@bryevdv - I used `bokeh.plotting` in my talk and may have caused some confusion. Moving forward what should I use as the standard way to import output_notebook, show etc. I'm assuming that it's `from bokeh.io` and that the other ones lurking around are for backwards compatibility.

**Comment by fpliger** [comment]
Worth mentioning that while `bokeh.plotting` is very stable right now the same does not apply to `bokeh.charts`, which have been recently added and have been changing very fast towards a mature interface that we hope will be much more stable (in the sense of fixed API) with the next (0.9) release.
