### ISSUE TITLE
Incorrect image sizes in Bokeh documentation

### ISSUE THREAD

**Issue by xnx** [bokeh/bokeh#2172]
At least on my browser (Firefox 37.0.1) some of the images in the docs are enormous and obscure the other content (such as menus) on the page. e.g. http://bokeh.pydata.org/en/latest/docs/user_guide/examples.html#applets

![screen shot 2015-04-14 at 11 44 11](https://cloud.githubusercontent.com/assets/371774/7140829/9c6edb82-e29b-11e4-9189-41ebf72997e3.png)

**Comment by bryevdv** [comment]
Problem was introduced here:

https://github.com/bokeh/bokeh/commit/2b572de6a7ea05ef72205d431f8d5b60eab0b53f#commitcomment-10833178

Will revert this change in a  PR I am working on for new tutorial.

**Comment by bryevdv** [comment]
Long since fixed, tho @birdsarah feel free to add anything if it is relevant.
