### ISSUE TITLE
Lasso selection in selection_histogram.py is slow

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#2173]
Unlike the box select tool, I think the lasso tool is round-tripping to the server, so it's incredibly unresponsive.  Not sure if this is a simple fix.

**Comment by bryevdv** [comment]
Did you try setting `select_every_mousemove` to `False`?

https://github.com/bokeh/bokeh/blob/master/bokeh/models/tools.py#L294

**Comment by bryevdv** [comment]
This is not the case with the new server, even when selecting every mousemove.
