### ISSUE TITLE
Can't view plots in IE

### ISSUE THREAD

**Issue by StefanRoss** [bokeh/bokeh#2179]
I've been making plots in Bokeh, they work fine in Chrome, but I just get blank pages in IE. I thought this was because my company uses IE8 by default, but we've now been upgraded to IE11 and I see the same problem.

The IE debug console reports that the page targets document mode 7, so it may be an issue with the metadata in the page header.

Is there a way to make Bokeh output plots with the correct metadata for IE?

Also, bigreddot mentioned that you already test with IE, so I'm wondering if this is some compatibility setting which has been set by corporate IT causing this problem?

**Comment by bryevdv** [comment]
@StefanRoss this is an old issue, did you ever reach any resolution? I'm guessing your last supposition may be correct, in which case there is not much we can do. Did you ever try on IE outside your corporate network, for instance?

**Comment by StefanRoss** [comment]
Thanks for following up. No, I never reached a conclusion...that project
finished and it was acceptable to use Firefox only.

I've since moved on to other things so I don't have access to that
environment or the code.

Thanks

Stefan

**Comment by bryevdv** [comment]
OK, sorry it took so long, please feel free to re-open if you encounter the problem again.
