### ISSUE TITLE
Only send modelspec that changed on modelpush

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2181]
Here's the scenario:

* I have 4 data sources on my ServerApp
* The first 2 (A & B) of them are connected to renderers (the second 2 (C & D) just hold a large set of data from which to populate A & B)

When I initiate a data change on the server, A & B get updated via a modelpush. Firstly, very delighted that C & D do not come down the pipe unecessarily, I'm guessing that's because they're not attached to a renderer.

However, A & B are updated independently. That is the action that changes A, does not affect B and vica versa.

Currently when I change A, both A & B come down the websocket. It would be much more efficient to just send A.

This is different from only wanting to update one specific column of a particular DataSource, which would be awesome, but I understand why it's hard. 

Is there any reason why we can't do this?

OR have I messed something up and the above behavior already exists and I've configured something wrong.

Thanks,

Bird

**Comment by hhuuggoo** [comment]
the server should only send the things that have changed - if not then something is broken

https://github.com/bokeh/bokeh/blob/master/bokeh/server/serverbb.py#L389

this *should* default to dirty_only = True

you could set a breakpoint here in the server to examine and verify that the models are indeed dirty - if they are marked dirty when they shouldn't be, then we would have to figure out why

**Comment by birdsarah** [comment]
Thanks @hhuuggoo. Will investigate.

**Comment by birdsarah** [comment]
(am going to check whether this is still an issue)

**Comment by birdsarah** [comment]
closing this as the server has completely changed now.
