### ISSUE TITLE
tooltip templating with variable-length ColumnDataSource fields

### ISSUE THREAD

**Issue by schaunwheeler** [bokeh/bokeh#2184]
(Following the recommendation I received after posting this to the mailing list, I'm moving this here as a feature request).

It would be useful for tooltips to support jinja2-style templating. For example, if I had a data source that looked like this: 

|  |   student_id  |                         history |  xvals | yvals
|---|---|---|---|---|
| 0   |       2217  |  [(2012-2013, 3), (2013-2014, 3)]   |     0   |     0 |
| 1      |    2243   |                 [(2013-2014, 3)]    |    1      |  1 |
| 2       |   2250  |  [(2012-2013, 3), (2013-2014, 3)]   |     2   |     2 |
| 3      |    2340   | [(2012-2013, 2), (2013-2014, 2)]    |    3     |   3 |
| 4      |    2351  |  [(2012-2013, 3), (2013-2014, 2)]     |   4   |     4 |
| 5      |    2372  |  [(2012-2013, 2), (2013-2014, 2)]   |     5     |   5 |
| 6      |    2381   | [(2012-2013, 3), (2013-2014, 4)]    |    6    |    6 |
| 7      |    2398  |  [(2011-2012, 2), (2012-2013, 2)]     |   7     |   7 |
| 8     |     2418    |                [(2013-2014, 2)]    |    8    |    8 |
| 9  |        2423  |  [(2012-2013, 4), (2013-2014, 4)]   |     9   |     9 |

I'd like create a scatterplot using xvals and yvals, with tooltips displaying student_id and history (each student's state test score history), so and individual point’s tooltip would look something like this: 

Student ID: 2250
* 2012-2013: 3
* 2013-2014: 3

If I were doing this in a jinja2 template, but using Bokeh’s tagging conventions for tooltips, I would do something like this:

```
tooltips = """
    <div>Student ID: @student_id</div>
    <div>
	<ul>
            {% for year, score in @history %}
            <li>{{year}}: {{score}}</li>                    
            {% endfor %}
        </ul>
    </div>
    """
```

**Comment by bryevdv** [comment]
Hover tooltips have been configurable for quite a long time: http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#custom-tooltip

**Comment by rconnol** [comment]
I have a text datatype as a field in a dataframe.  The text is split into \n for each list item.

"365 EVERYDAY VALUE - Cookies\nOakland Coffee C..."
I am trying to render a variable length for my tooltip with Jinja2, but no matter how I slice it, it always gets spit out on the same line.

any advice?

source = ColumnDataSource(data=coord)

template = Template("""
        <div>
            <div>
                <span style="font-size: 17px; font-weight: bold;">Location : {{ place }} </span>
            </div>
            <div>
                <span style="font-size: 17px;">Items : </span>
                <ul>
                {% for x in description.split('\n') %}
                    <li style="font-size: 17px;">{{ x }}</li>
                {% endfor %}
                </ul>
            </div>
        </div>
        """)


hover = HoverTool(
    tooltips = 

        template.render(place = "@Location", description = "@Descriptions")
        
    )
![sameline](https://cloud.githubusercontent.com/assets/12263637/18612764/4bcfb542-7d28-11e6-880f-30e9910e0a37.PNG)
