### ISSUE TITLE
Unable to open plot in new tab from main page

### ISSUE THREAD

**Issue by mutirri** [bokeh/bokeh#2187]
According to @bryevdv suggestion I'm submitting this bug.
Steps:

- upload example to already running bokeh server in dev mode:
```
(devbokeh)[irritum@localhost bokeh]$ python examples/plotting/server/line.py
```
This opens a new tab in my already running web browser and shows the plot - that's ok.
However when I:
- open another new tab and navigate to `http://localhost:5006/` site
- I can see the document on the list
**but** when I click on this document - nothing happens.

This action should also open new tab with plot.

**Comment by bryevdv** [comment]
This refers to the old (and completely removed) `bokeh-server`. Please open a new issue for any problems with the new `bokeh serve`
