### ISSUE TITLE
preview save tool should auto download-prompt

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#219]
since apparently this is possible, and then just rename the tool to "save"

**Comment by bryevdv** [comment]
This seems like it might be the only potentially non-terrible way in the future, but it is not supported everywhere yet: http://caniuse.com/#feat=download  I"m tempted to close this as `wontfix`

**Comment by damianavila** [comment]
Yes, I explored this possibility before the release, but the lack of full support of `download` in all the browser seems to problem... so, I would close as `wontfix` for now and when the support for `download` arrives for Safari and IE, we can reopen this one...

**Comment by birdsarah** [comment]
closing as per your suggestions above and graph doesn't seem to be moving on `download` feature

**Comment by mattpap** [comment]
New progress on this issue in PR #4228.
