### ISSUE TITLE
BokehJS install failing because dependencies source doesn't exist

### ISSUE THREAD

**Issue by katmeg** [bokeh/bokeh#2196]
Hi there, 
I installed Bokeh on one machine a couple weeks ago and it went smoothly, but now that I am trying to install it on another, I'm encountering the issue described below.

`npm install` in bokehjs fails because every dependency in `npm-shrinkwrap.json` that is retrieved from http://107.170.72.221:8080 throws the following error:

    npm ERR! fetch failed http://107.170.72.221:8080/xtend/-/xtend-4.0.0.tgz
    npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503

Navigating to http://107.170.72.221:8080 in the browser or via `links` indicates the connection is refused because the webpage cannot be found. 

Might the address currently be offline or am I doing something wrong this time around?

**Note:** Using Node v0.12.2 and npm v2.8.3.

**Comment by bryevdv** [comment]
ping @tswicegood

**Comment by tswicegood** [comment]
Hmm -- I just loaded it.  I've noticed some major downtown across the internet in the last 30 minutes (GitHub, binstar, travis-ci).  Can you try again?

**Comment by tswicegood** [comment]
For completeness @bryevdv that IP address is a DigitalOcean box I've setup with [this Docker image][1] on it to cache npm packages that we use internally at Continuum.  Forgot I had it configured on my box when I ran shrinkwrap, but it should be a little more reliable than npmjs.

[1]: https://github.com/tswicegood/docker-npm-cache

**Comment by katmeg** [comment]
@tswicegood I just tried again and the connection was still refused from my computer. However, accessing the page from my phone works...
Will look into this with IT as it seems the issue is on my end.

**Comment by bryevdv** [comment]
@tswicegood I am not sure I am comfortable with that for an OSS project. Any number of things might cause that box to go or be taken down, on purpose or accidentally. At least when npmjs has a problem, everyone has the problem. This will end up being a weird thing that not enough people know about, know how to diagnose, or have access to fix. Basically: I don't want it to be our responsibility.

**Comment by tswicegood** [comment]
@bryevdv easy enough to change.  I'd forgotten that I even had npm configured to run through that.  I'll open up a PR with the changes.
