### ISSUE TITLE
Bokeh keep open a new tab

### ISSUE THREAD

**Issue by jonhari** [bokeh/bokeh#2198]
Hi guys, when I'm using a simple pandas plotting with bokeh, it keeps opening a new tab as I run the plot.  When I combined with the slider interact ipython html widgets, as I do sliding, the bokeh will keep open a new tab. I'm using ipython notebook, chrome browser, and OSX Yosemite 10.10.2. I can reproduce this issue using different computer.

Library used:

* Bokeh : 0.8.2
* Pandas : 0.16.0
* Numpy :  1.9.2
* IPython 3.1.0
* Python 2.7.9

```Python
from bokeh import mpl
import bokeh.plotting as bk
import pandas as pd
import numpy as np
from IPython.html.widgets import interact
bk.output_notebook()

def update(n=5):
    pd.Series(np.arange(n)).plot()
    bk.show(mpl.to_bokeh(notebook=True))

interact(update,n=(3,10))
```

**Comment by bryevdv** [comment]
@jonhari As a small experiment, can you see if the problem can be replicated with a simple pure-Bokeh plot (i.e., not using Pandas `.plot` and `mpl.to_bokeh`). I suspect the problem is in our `mpl` compat layer somewhere and this information would go a long way to confirming that.

**Comment by jonhari** [comment]
you're right. Using bokeh charts  timeseries, for my goal, Bokeh doesn't open a new tab. Well, I guess it's time to dive into Bokeh then. thanks Bryan

**Comment by bryevdv** [comment]
@jonhari OK that's really good to know, that probably limits the issue down to one of these two files:

https://github.com/bokeh/bokeh/blob/master/bokeh/mpl.py
https://github.com/bokeh/bokeh/blob/master/bokeh/mpl_helpers.py

If you happen to find a solution before we get to it, any info (or even a PR!) is very welcome, thanks.

**Comment by jonhari** [comment]
I think the problem is somewhere in the bokeh.io output_notebook/show/state.But I could be wrong. I tried to reproduce the problem once again.  First I don't specify notebook=True, it surely open 'unnamed.html'. Since then, even if you set it to true, Bokeh will still open new tab

**Comment by krissboy** [comment]
Still having the problem with the first example from http://bokeh.pydata.org/en/latest/docs/quickstart.html

**Comment by bryevdv** [comment]
@krissboy did you mean to comment on another issue? That example does not use either mpl compat, or widgets. I don't see how it is related.

**Comment by krissboy** [comment]
Yes but i get the output in a new tab instead of inline. I am on the latest build of python and ipython.

**Comment by bryevdv** [comment]
Are you changing the quickstart example to use `output_notebook` before running it? As it is it uses `outpout_file` which will open a new tab (as expected).

**Comment by bryevdv** [comment]
@damianavila  Working as expected for me on master. 

<img width="945" alt="screen shot 2015-09-09 at 2 52 43 pm" src="https://cloud.githubusercontent.com/assets/1078448/9772556/915c8b00-5702-11e5-9414-aa74a65d85ac.png">

**Comment by damianavila** [comment]
>@damianavila Working as expected for me on master.

OK, thanks!!

**Comment by veltzerdoron** [comment]
This same example 
`from bokeh import mpl
import bokeh.plotting as bk
import pandas as pd
import numpy as np
from IPython.html.widgets import interact

bk.output_notebook()

def update(n=5):
    pd.Series(np.arange(n)).plot()
    bk.show(mpl.to_bokeh())

interact(update,n=(3,10))`

both shows the plot on my notebook and opens a new tab and I can't get the tab to stop opening (I saw somewhere mentioned sending a notebook=True parameter to the to_bokeh method, but that just isn't recognized by the method)

**Comment by bryevdv** [comment]
@veltzerdoron the GH issue tracker is not the appropriate place for general support or usage questions, please go to the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by veltzerdoron** [comment]
#This resets the output to notebook in case you set it to a file before otherwise both are opened

from bokeh.plotting import figure, show, output_notebook, reset_output

reset_output()
output_notebook()
