### ISSUE TITLE
OpenURL on single line/patch glyphs

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2200]
Users probably only want to open up a single URL if the patch is hit at all. But this does not quite fit with how URLs are referenced/looked up in the other cases. 

For reference:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/callbacks/open_url.coffee#L15-L16

**Comment by bryevdv** [comment]
I'm not sure how this could fit in with the current scheme, but also if this is really needed, either users could use patches instead, or now create a custom tool that accomplished it
