### ISSUE TITLE
sidebartoc displaying strangely when text is minimized

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2206]
In **Safari**, on any page of the docs that requires scrolling down, the sidebartoc will overlap text (and sit behind images and code boxes) if you decrease the font size at all.

![sidebartoc](https://cloud.githubusercontent.com/assets/1417520/7279903/dc37be6a-e8e4-11e4-94d5-fa3414d902f4.png)

This happens even when you maximize the browser window.

**Comment by Maggie-M** [comment]
I've found a similar issue with docs pages (also on Safari) where a horizontal scrollbar is present: if you scroll away from the sidebartoc, a portion of its background color will overlap the text.

![horizontal_scroll](https://cloud.githubusercontent.com/assets/1417520/7282995/199433d8-e8f9-11e4-8cbf-2a3e20eca908.png)

**Comment by bryevdv** [comment]
Can no longer reproduce on latest docs. Re-open if it can be reproduced
