### ISSUE TITLE
Implementation of basic numpy/pandas functionality in JS

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#2209]
There is a similar interest within the Vispy project. It seems no-one is working on this yet though:
* https://github.com/vispy/numpy.js
* https://github.com/vispy/vispy/issues/514

Can someone define what we'd need from Bokeh's point of view?

**Comment by pzwang** [comment]
I think the core "numpy"-like needs are pretty simple:

* Slicing and fancy indexing
* Masking with boolean arrays
* Broadcasted ufuncs for basic math
* No need to support crazy Nd-array stuff; mostly tabular filtering would be sufficient

Creation of views would also be awesome, but not a requirement.

Pandas-like features are actually where we'd get most of the user-visible win:

* Tabular selection, column append, row append
* Datetime indexing and math
* Group-by would be great but does not need to be super sophisticated to start with

**Comment by jakirkham** [comment]
I don't know what you guys have already done on this, but I saw a project that you might be interested in ( https://github.com/hpcgarage/furious.js ). Their byline describes it as a "scientific computing package for JavaScript - inspired by NumPy".

**Comment by jakirkham** [comment]
Also, there is the ndarray package (with extensions). Here is an overview of what is out there ( https://github.com/mikolalysenko/ndarray-tutorial/blob/master/README.md ). Again if you have already seen this, sorry for pointing out the obvious.

**Comment by jakirkham** [comment]
I think I forgot to mention this earlier, but this project is really impressive ( https://github.com/scijs ). They have really made a lot of progress at adding a wide array of NumPy like features to javascript. Their documentation could use some work.

**Comment by mattpap** [comment]
This issue doesn't seem to be anything that should be implemented directly in bokehjs, but should be an independent JS library. I'm inclined to close this issue as `wontfix`, because I doubt we have resources to do this on our own, or as `referred` if we decide to create a new repository move this discussion there.

**Comment by bigreddot** [comment]
Agreed.

**Comment by bryevdv** [comment]
Agreed.
