### ISSUE TITLE
Feature: LinkFormatter

### ISSUE THREAD

**Issue by lukebarnard1** [bokeh/bokeh#2212]
It would be incredibly useful (at least for our purposes) to have a link on each row of a data table that links to another part of the bokeh-server or another website for that matter.

There is already a StringFormatter class that formats data into a string. It takes one value and puts the text into a <span> tag. The LinkFormatter would have to take two values - one for the text and one for the link so I'm not sure if this is the best use of the CellFormatter class.

Alternatively, it would be nice to have Actions available on Tables through TableTools or something like that. PlotObjects already have this as you can add TapTool(action=OpenURL(...)).

**Comment by bryevdv** [comment]
This could be accomplished now with a custom user extension that subclasses `CellFormatter`, without requiring building or adding to the core library (although a useful demonstration might be a pre-cursor for inclusion in the core library)
