### ISSUE TITLE
Charts (Bar) is broken with DataFrames from GroupBy

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2216]
As reported in [m.l.](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/bokeh/AslswU4uPkA/upJxMNz4p-EJ) Bar is broken when receiving a DataFrame created from a GroupBy object. 

When CountBy is saved to csv and then read it back, Bokeh makes a bar chart just fine.

**Comment by chrisfs** [comment]
Hi, 
I am the original poster on Google groups. Let me know if you need any more info.

**Comment by canavandl** [comment]
Hi Chris -

I think the problem may be related to some weirdness about encoding int64 values into JSON (for plotting) on some Windows machines (ref issue #573). I'm guessing the saving to and reading from csv is changing the dataframe dtype and fixing the problem.

Can you try changing the dataframe dtype to int32 like below and then calling the Bar function?

```python
...
import numpy as np

df = df.astype(np.int32)
p = Bar(df)
show(p)
```

**Comment by chrisfs** [comment]
If I did it right, it's still a problem. Here is the example notebook that I added your changes to. It still gives an error 'cannot concatenate 'str' and 'numpy.int64' objects' even though the columns are now int32 dtypes. I have attached the edited Notebook to the Google Groups post, since I can't seem to attache it here

**Comment by bryevdv** [comment]
@chrisfs Can you comment on whether this is still an issue? `bokeh.charts` is the newest API and was quite young at the time. It has changed somewhat in the last 9 months, but is also settling down and becoming more stable.

**Comment by chrisfs** [comment]
Hi,

I will look at this, this week.


Chris S


________________________________

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/57)
