### ISSUE TITLE
Logarithmic axes for charts

### ISSUE THREAD

**Issue by alesarrett** [bokeh/bokeh#2221]
As per plots [(issue #703)](https://github.com/bokeh/bokeh/issues/703), it would be great to have logarithmic axes support also for charts.

**Comment by pzwang** [comment]
For the value axis, log axis support is pretty straightforward, but it
would be nice to also add that a binned categorical logarithmic axis. (We
would need to provide the user a bunch of configuration options, like the
base, the mantissa offset for the bins, etc.)

**Comment by ahothan** [comment]
I would also very much like to see that feature in...
For now I have to use the glyphs interface to pretty much redo what Scatter does ;-(

**Comment by bryevdv** [comment]
`bokeh.charts` has moved to https://github.com/bokeh/bkcharts please re-open there if appropriate

**Comment by BEFH** [comment]
Bokeh.charts no longer exists. Can this be reopened?

**Comment by bryevdv** [comment]
@BEFH not sure what you are asking. This is was close *because* `bokeh.charts` no longer exists. Log axes have long been possible with `bokeh.plotting`, and if you want a higher level API on top of Bokeh you should look to Holoviews

**Comment by BEFH** [comment]
It doesn't seem to work. When I include "x_axis_type="log" in the arguments
to figure, the plot doesn't render correctly (nothing plotted at all).
