### ISSUE TITLE
Broken reset tool after use of resize tool

### ISSUE THREAD

**Issue by mutirri** [bokeh/bokeh#2229]
On `master` branch (b56402b7b89cdf0e7395e94b668477d91a31d3e7):

Try
* load plot from file to `bokeh-server`,
* use `box zoom` on the plot - works just fine,
* use `reset` tool - works just fine.

However:
* use `resize` tool on the plot - works just fine,
* try to use `reset` tool after above action - nothing happens.

**Comment by bryevdv** [comment]
Just checked with `sliders.py` app and new server, this has been resolved at some point. Additionally, reset tool now also resets plot size (this was requested)
