### ISSUE TITLE
expose tap and hover tool hit radius

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2230]
reference: http://stackoverflow.com/questions/29923118/how-to-increase-click-radius-in-bokeh

**Comment by bryevdv** [comment]
Executing this proposal will involve:

* adding a `hit_radius = Float(....)` property to the relevant model classes on "Python side"
* adding the same property to the corresponding BokehJS classes and having the hit test take that value into account instead of using a hard-coded radius

No new files or classes will need to be created.

**Comment by Ravi-R-Singh** [comment]
Hi,

I've been reading up on the project and contributions, and I'd like to take on this task!

**Comment by bryevdv** [comment]
@Ravi-R-Singh We would love to have your contribution. New contributors arrive with a wide variety of experience we can't predict, so please let us know where we can help provide guidance once you start to take a look.
