### ISSUE TITLE
Tick format language

### ISSUE THREAD

**Issue by Jdash99** [bokeh/bokeh#2240]
Charts does not show up when changing the tick format language to other than english ("en").

For example, inside ipython-notebook:

``` python
    import numpy as np
    import pandas as pd
    from bokeh.models import NumeralTickFormatter
    from bokeh.plotting import figure, show

    bokeh.plotting.output_notebook()

    df = pd.DataFrame(np.random.randint(0, 900000000, (10,1)), columns=['my_int'])
    p = figure(plot_width=700, plot_height=280, y_range=[0,1000000000])

    for index, record in df.iterrows():
    p.rect([index], [record['my_int']/2], 0.8, [record['my_int']], 
               fill_color="red", line_color="black")

    p.yaxis.formatter=NumeralTickFormatter(language="es")
    #p.yaxis.formatter=NumeralTickFormatter(language="en") -->Works fine
    show(p)
```

Kernel info:

``` python
    Python 3.4.3 |Anaconda 2.2.0 (32-bit)| (default, Mar  6 2015, 12:08:17) [MSC v.1600 32 bit (Intel)]
    Type "copyright", "credits" or "license" for more information.

    IPython 3.0.0 -- An enhanced Interactive Python
```

**Comment by bryevdv** [comment]
@mattpap do you have any quick comments on this, do you remember if there were any issues already known?

**Comment by colinfang** [comment]
`language='en-gb'` doesn't work either.

Btw, I think it is better if we add a sentence saying the format follows `numeral.js` and place a link to http://numeraljs.com/ in the [reference guide]( http://bokeh.pydata.org/en/latest/docs/reference/models.html#bokeh.models.formatters.NumeralTickFormatter)

**Comment by bryevdv** [comment]
FWIW with `0.12.6` this code:
```
import numpy as np
import pandas as pd
from bokeh.models import NumeralTickFormatter
from bokeh.plotting import figure
from bokeh.io import output_file, show


df = pd.DataFrame(np.random.randint(0, 900000000, (10,1)), columns=['my_int'])
p = figure(plot_width=700, plot_height=280, y_range=[0,1000000000])

for index, record in df.iterrows():
    p.rect([index], [record['my_int']/2], 0.8, [record['my_int']],
           fill_color="red", line_color="black")

p.yaxis.formatter=NumeralTickFormatter(language="es")

output_file("foo.html")
show(p)
```
does produce what appears to be a correct plot. Tho I don't know if there should be any changes to the ticks (they look the same to me). 

@mattpap can this be closed?

**Comment by bryevdv** [comment]
Well, given that the original complaint "chart does not show up" no longer seems to he happening, I am going to close this. Please re-open if a problem can still be reproduced somehow.
