### ISSUE TITLE
Obsolete protocole sslv3

### ISSUE THREAD

**Issue by guillaumeinnov24** [bokeh/bokeh#2241]
[Obsolete protocole sslv3 has been removed in debian 8](https://www.debian.org/releases/jessie/armhf/release-notes/ch-whats-new.en.html)
To install module Bokeh on python 2.7 on Debian 8 I had to edit : 

`/usr/local/lib/python2.7/dist-packages/gevent/ssl.py`

this way : 

**(line 386)**
`#def get_server_certificate(addr,ssl_version=PROTOCOL_SSLv3,ca_certs=None):`
`def get_server_certificate(addr,ssl_version='',ca_certs=None):`

otherwise, you got below error during compil : 

`NameError : name 'PROTOCL_SSLv3' is not defined`

**Comment by bryevdv** [comment]
@guillaumeinnov24 what version?

@bokeh/dev why and where is gevent still listed as a dependency?

**Comment by bryevdv** [comment]
Here: https://github.com/bokeh/bokeh/blob/master/setup.py#L511

I think this should have been removed a long time ago?

**Comment by damianavila** [comment]
When `tornado` was introduced, `gevent` was left optional... but I guess when `gevent` was finally removed, we completely forgot about this references. All the other `gevent` ocurrences: https://github.com/bokeh/bokeh/search?utf8=%E2%9C%93&q=gevent

**Comment by bryevdv** [comment]
@guillaumeinnov24 thanks for the report, `gevent` will not be a dependency for future versions of Bokeh.
