### ISSUE TITLE
Button events seem to reload server app

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2244]
From [m.l. discussion](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/bokeh/WDhI435ZzAQ/zTSkavPNhiIJ):

User implemented a toy example based on stock_app.py:

https://gist.github.com/schaunwheeler/ac1162db95d13a0a5070

What is supposed to happen:
1. Click the "Select plot criteria" button to reveal a "Submit" button and a Select widget.
2. Select a number from the Select widget..
3. Click the "Submit" button to show the selected number in a Paragraph widget.
4. (Optional) Click the "Cancel" button (which is just the re-labelled "Select plot criteria" button) to hide the "Submit" button and Select widget.

What actually happens:
1. Click the "Select plot criteria" and nothing happens.
2. Click the "Select plot criteria" a to reveal a "Submit" button and a Select widget.
3. Select a number from the Select widget.
4. Click the "Submit" button, at which point the entire app seems to reboot to its original state.
5. (Optional) Click the "Cancel" button  to hide the "Submit" button and Select widget but nothing happens.
6. (Optional) Click the "Cancel" button again to actually hide the "Submit" button and Select widget.

Questions:
1. Why do I have to click my buttons twice in order to get them to work?
2. Why does the `submit_menu` callback on my "Submit" button, which just sets the Paragraph text and toggles the menu, restart the entire app?

**Comment by BenjaminRueth** [comment]
Wrote an easier example with the same bug. Maybe that's helpful:
```
from bokeh.models.widgets import HBox, Button, VBoxForm
from bokeh.properties import Instance
from bokeh.server.app import bokeh_app
from bokeh.server.utils.plugins import object_page

class ButtonApp(HBox):  
    extra_generated_classes = [["ButtonApp", "ButtonApp", "HBox"]];    
    button = Instance(Button);
    controls = Instance(VBoxForm);
    
    @classmethod
    def create(cls):
        print "creating app..."        
        obj = cls();
        obj.button = Button(label="Foo", type="success");
        obj.button.label = "Bar";
        obj.controls = VBoxForm(
            children=[
                obj.button
            ]
        )                
        obj.children.append(obj.controls);          
        print "created app!"
        return obj;

    def setup_events(self):
        # recursively searches the right level?
        if not self.button:
            return
        self.button.on_click(self.changeLabel);        
        
    def changeLabel(self):
        print "changing label..."
        self.button.label="BarBar";	
        print "changed label!"
        
@bokeh_app.route("/bokeh/simpleButton/")
@object_page("simpleButton")
def make_ode():
    app = ButtonApp.create()     
    return app         
```
If there's any bad bokeh coding style, I always appreciate corrections!

**Comment by bryevdv** [comment]
The new tornado server sends model patch updates and does not suffer this issue.
