### ISSUE TITLE
Editing source data with DataTable widget

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2248]
DataTable widget lets user edit source content and it's also reflected on the plots using that source on the client side. It doesn't sync with the server though. This creates an inconsistent status. 

If we say that users can change the data using that widget it should reflect the change everywhere. The question here is: do we want this? What is the desired behaviour of the DataTable widget?

**Comment by warren-oneill** [comment]
Hi Fabio, we are running into similar problems. I wrote it as an issue here: #2252

**Comment by warren-oneill** [comment]
Ok I decided to close it to keep the discussion in one place. Is this a possible solution? http://bokeh.pydata.org/en/test/docs/user_guide/interaction.html#callbacks-for-widgets

**Comment by bryevdv** [comment]
Yes quite possibly that callback class or one very much like it could be used to trigger code execution in static documents, when the table changes.

**Comment by fpliger** [comment]
For reference, this older issue #1748 should be related...

**Comment by warren-oneill** [comment]
Do you guys think this issue will be resolved internally or do I need to try and make my own solution? Also, if you plan on doing an intern solution how long will it take? This functionality is pretty fundamental to our project and its pretty difficult for us to move forward without it.

**Comment by pzwang** [comment]
@warren-oneill if selection is the main thing you're interested in, then let's bump the priority on testing #1748 and see if that's sufficient.  If not, then please outline the specific things/features you need in the table editing?  Thanks!

**Comment by warren-oneill** [comment]
hi @pzwang, what we need is to be able to access the values that are entered manually in the DataTable and then make a calculation with the edited values and then enter this calculated value in a row in the table. So basically every time a value is edited it would recalculated this row. 
I wrote some details in #2252 but decided to close it to keep the discussion here.

**Comment by warren-oneill** [comment]
@fpliger @pzwang @bryevdv What the status of this? Is it solved? We are in the process of deciding on which library to use for our company and this is the only issue holding us back from using bokeh.

**Comment by datnamer** [comment]
+1 to this

**Comment by bmweiner** [comment]
+1

**Comment by PythaGorilla** [comment]
+2 to this again

**Comment by pzwang** [comment]
The short answer is that the existing DataTable is fine for display, but it's a stop-gap until we get a better full-fledged table integrated.  The good news is that there are multiple efforts underway on that front.

@almarklein @dwillmer @mattpap Any comments on the latest work w.r.t. Phosphor integration?

**Comment by georgedimitriadis** [comment]
+1 to this also

**Comment by alberthidalgo** [comment]
+1

**Comment by bryevdv** [comment]
This is a dupe of #4616 which has an open PR that will be in `0.12.3`

**Comment by gbakalian** [comment]
Would have been great if editable was an array of Boolean, so we could precise which column we want to be editable. 
(let's say I have a simple timeserie, first column date, second one value, and I do not want the user to be able to change the dates, but only the values) 

Perhaps it would be more pertinent to have then the editable argument in TableColumn ?

**Comment by bryevdv** [comment]
@gbakalian that might be a reasonable feature. Please open a new, separate feature request.
