### ISSUE TITLE
Problem in "Standalone HTML" example

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#2255]
When using `bokeh` version 0.8.2 via `conda`, I tried plotting this example from here ( http://bokeh.pydata.org/en/latest/docs/user_guide/embedding.html?highlight=ipython ).

    from bokeh.plotting import circle
    from bokeh.resources import CDN
    from bokeh.embed import file_html

    plot = circle([1,2], [3,4])

    html = file_html(plot, CDN, "my plot")

However, I got the following error.

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-2-365e7b681bb2> in <module>()
    ----> 1 from bokeh.plotting import Circle
          2 from bokeh.resources import CDN
          3 from bokeh.embed import file_html
          4 
          5 plot = circle([1,2], [3,4])
    
    ImportError: cannot import name Circle

**Comment by jakirkham** [comment]
I think the example should have been like this, which appears to work.

    from bokeh.resources import CDN
    from bokeh.embed import file_html
    
    plot = figure()
    plot.circle([1,2], [3,4])
    
    html = file_html(plot, CDN, "my plot")

**Comment by jakirkham** [comment]
On a separate note, the first time I render the HTML (using `%%html` in iPython 3.1.0). It sometimes complains that javascript was unable to load `Bokeh`, but a quick rerun resolves this issue.

**Comment by bryevdv** [comment]
@jakirkham Thanks for pointing that out. There have been some API changes a while back and a few places probably missed being updated. I am currently working on a completely new user's guide I will make sure to update this example.

**Comment by jakirkham** [comment]
Cool, I will leave it to you then. Thanks. :)

**Comment by bryevdv** [comment]
I don't know about the `%%html` thing, though, @damianavila any ideas?

**Comment by jakirkham** [comment]
Actually, much simpler example using this `display(HTML(html))`. Here is the file if you are curious ( https://github.com/jakirkham/bokeh_examples/blob/master/Bokeh_Example_1.ipynb ). Sometimes when I render this I see that same error, but it will go away after a rerun.

Does it have to do with lingering references to the previous objects? I would ideally like to keep the HTML in there so others can see the example.

**Comment by jakirkham** [comment]
Here is the exact text of the error if that helps.

    Javascript error adding output!
    ReferenceError: Bokeh is not defined
    See your browser Javascript console for more details.

**Comment by jakirkham** [comment]
It's just weird as using `nbviewer` won't produce this error ( http://nbviewer.ipython.org/github/jakirkham/bokeh_examples/blob/master/Bokeh_Example_1.ipynb ). However, it will appear when opening the notebook.

**Comment by bryevdv** [comment]
Re: example, see https://github.com/bokeh/bokeh/commit/8de52a022ae383cfe8e5be93939a2ebf73b8d625

**Comment by jakirkham** [comment]
Looks good to me. I'm going to go ahead and close this then.
