### ISSUE TITLE
tool sometimes switches to pan with no notification for the user

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#226]
When selecting the active tool will frequently change to the pan tool with no user notfication.  This is quite confusing.  My guess is that its keyboard related.

**Comment by bt-** [comment]
Is there a way to enable pan on shift as an option?  I'd like to be able to setup a time series plot with box zoom as default, always on, and pan on shift functionality.  Essentially, a similar interaction as a [dygraph] (http://www.dygraphs.com).
