### ISSUE TITLE
bokeh_magic not working

### ISSUE THREAD

**Issue by blmarket** [bokeh/bokeh#2264]
environment : python 3.4.3, ipython 3.1.0, bokeh 0.8.2

reproducible command : `ipython -c "import bokeh.bokeh_magic"`

which ends up with 404 not found error.

**Comment by blmarket** [comment]
Please label this as bug.

**Comment by bryevdv** [comment]
`bokeh_magic` was created to help deal with problems that the original implicit, stateful interface had in the notebook. After the 0.7 switch to an explicit plotting interface, `bokeh_magic` is no longer necessary. It has probably been broken for some time, and was never publicized to any degree. It was removed from `master` a few days ago, to reduce the maintenance burden, and will not be a part of future releases.

**Comment by blmarket** [comment]
Thanks for explanation. I think code should...

1. Be removed
2. Or raise proper deprecation warning(use create_notebook etc)

Current 404 error seems not meaningful imo.
