### ISSUE TITLE
DateRangeSlider not rendering

### ISSUE THREAD

**Issue by mvaz** [bokeh/bokeh#2268]
Hi all,

I'm trying to add a DateRangeSlider to a bokeh application.

``` Python
import logging
logging.basicConfig(level=logging.DEBUG)

from bokeh.properties import Instance
from bokeh.models import HBox, VBoxForm, Slider, DateRangeSlider
from bokeh.server.app import bokeh_app
from bokeh.server.utils.plugins import object_page

class SlidersApp(HBox):
    extra_generated_classes = [["SlidersApp", "SlidersApp", "HBox"]]

    inputs = Instance(VBoxForm)

    slider = Instance(Slider)
    dateRange = Instance(DateRangeSlider)

    @classmethod
    def create(cls):
        obj = cls(width=500)

        obj.slider = Slider(title="amplitude", name='slider', value=1.0, start=-5.0, end=5.0)

        start = '2010-01-01'
        end = '2015-01-01'
        obj.dateRange = DateRangeSlider(title="Period:", name="period", value=(start,end), bounds=(start,end), range=(dict(days=1), None))

        obj.inputs = VBoxForm(children=[obj.slider, obj.dateRange])

        obj.children.append(obj.inputs)

        return obj

@bokeh_app.route("/bokeh/sliders/")
@object_page("sliders")
def make_object():
    app = SlidersApp.create()
    return app
```

However, when rendering the obj above none of the components appear on the browser (Chrome v42, Safari v8.06, Firefox v34). In the error console, Safari complains of the following:

```
[Log] Bokeh: setting prefix to http://127.0.0.1:5007/ (bokeh.js, line 61288)
[Log] Bokeh: setting log level to: 'info' (bokeh.js, line 15080)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (util.js.map, line 0)
```

If it is not in the  obj.dateRange is added to the children, then the other slider draws as expected.

Any help appreciated.
Cheers, Miguel

**Comment by bryevdv** [comment]
Hi @mvaz those errors are harmless and expected, the `.map` files are only used for development purposes. We have not found a way to silence those lines yet, though. what version of Bokeh are you using?

**Comment by mvaz** [comment]
Hi @bryevdv, I'm currently using 0.8.2. Should I try with the devel branch?
Thought the info would be helpful... I don't see any other error messages anywhere.

**Comment by lukebarnard1** [comment]
I'm getting pretty identical behavior in 0.8.1. The JS console reads:

```
Uncaught TypeError: $(...)[this._handleType(...)] is not a function
```
It refers to an error on bokeh.js, line 55459.

**Comment by fpliger** [comment]
Yeap, this is happening in on master branch as well.

**Comment by Omenien** [comment]
Was this ever resolved?

**Comment by bryevdv** [comment]
Not yet, we are in the middle of some very heavy lifting around the (new) bokeh server, GIS features, static image output, and also splitting up BokehJS and making the model system extensible. These tasks are occupying the entire team at the moment. When the next release lands it will be possible for anyone to add and use their own custom models to Bokeh. That will provide a much simpler and easier way for contributors to make small, targeted contributions without having to wait on us (because we are fairly swamped)

**Comment by pjbutcher** [comment]
It looks like this is still an outstanding issue? I'm using version 0.11.0 and still have the problem described above. This would be a very nice widget to have working :)

**Comment by bryevdv** [comment]
It is, I am afraid everyone is fairly well underwater with other tasks right now. It would definitely be possible to wrap a different/better JS slider library and expose it as a custom Bokeh extension. There was a recent closed PR looking at adding `ionRangeslider` directly to Bokeh, but it was just some experimentation. In case this is something you might be interested in looking at, the old PR could be used as a reference and is here: https://github.com/bokeh/bokeh/pull/3916

And some examples of making a custom model is here: https://github.com/bokeh/bokeh/blob/master/examples/models/custom.py

**Comment by bryevdv** [comment]
OK I figured out the problem, it is described in the PR #4491 but we need to find a better solution I expect.

**Comment by mullenkamp** [comment]
Hello,
I was wondering if there are any updates about this? I just discovered Bokeh and am quite interested in utilizing it to combine spatial data with time series to cycle through dates in spatial data. 
Thanks!

**Comment by mattpap** [comment]
@mullenkamp, sliders were reimplemented from scratch in 0.12.7-dev, so this may not be an issue anymore in upcoming release. We need to verify this though.

**Comment by hsparra** [comment]
DateRangeSlider is appearing for me in bokeh 0.12.7.

**Comment by bryevdv** [comment]
Thanks @HuntJSparra
