### ISSUE TITLE
HBox/hplot broken

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2269]
HBox and hplot are broken after last big JS refactoring (after `0.8.2` release), as can be seen on [dev docs](http://bokeh.pydata.org/en/test/docs/user_guide/layout.html#horizontal-layout)  or on the following attachment..
![hplot_example](https://cloud.githubusercontent.com/assets/1084690/7562277/83cfe5c4-f7d3-11e4-85d4-3b3f30766361.png)

**Comment by bryevdv** [comment]
So the major problem is that it's not *always* broken. Already one attempted fix for this has been reverted, because it fixed this case, but broke others. I am not sure what a good solution or plan forward is. ping @LilaHickey @mattpap @bokeh/core
