### ISSUE TITLE
Hide/show image layers

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#2270]
Regularly, I find myself needing to make multiple image layers in the same graph and find it helpful if I can hide/show different layer combinations easily (ideally through varying alpha). I think this should be doable in `bokeh` and am just trying to figure out how to do it. There seems to be an `image_rgba` layer, which could help with this (though getting this to with `image` would be great too). I see that slider bars and such are possible, but am missing some details here. Mainly, I remain confused on how event notification works and updating existing layers? Some pointers here would be very helpful.

**Comment by tobyhodges** [comment]
I wrote a toy script for varying RGB levels in a color block, which you can view in full here: https://github.com/tobyhodges/colorPicking

I expect that what you want to achieve would be very similar, but with the alpha controlled by a slider, rather than the RGB levels. I think that the following code is the bit that you would find helpful, for more context, check the link above. Version 0.8.2 lacks the Callback functionality required, so you need to clone the latest version of the code from the bokeh GitHub, I think.

`from bokeh import plotting as bkplt
source = bkplt.ColumnDataSource(data=dict(x = x, y = y, color = [hex_color], text_color = [text_color]))

# create plot, as a rect() glyph and centered text label, with fill and text color taken from source
p1 = bkplt.figure(x_range=(-8, 8), y_range=(-4, 4), plot_width=600, plot_height=300, title=None, tools=tools1)
color_block = p1.rect(x='x', y='y', width=18, height=10, fill_color='color', line_color = 'black', source=source)
hex_code_text = p1.text('x', 'y', text='color', text_color='text_color', alpha=0.6667, text_font_size='36pt', text_baseline='middle', text_align='center', source=source)

# the callback function to update the color of the block and associated label text
callback = Callback(args=dict(source=source), code="""
	function componentToHex(c) {
		var hex = c.toString(16);
		return hex.length == 1 ? "0" + hex : hex;
	}
	function rgbToHex(r, g, b) {
		return "#" + componentToHex(r) + componentToHex(g) + componentToHex(b);
	}
	var data = source.get('data');
	var RS = red_slider;
	var GS = green_slider;
	var BS = blue_slider;
	color = data['color'];
	var red_from_slider = RS.get('value');
	var green_from_slider = GS.get('value');
	var blue_from_slider = BS.get('value');
	text_color = data['text_color'];
	color[0] = rgbToHex(red_from_slider, green_from_slider, blue_from_slider);
	if ((red_from_slider > 127) || (green_from_slider > 127) || (blue_from_slider > 127)) {
		text_color[0] = '#000000';
	}
	else {
		text_color[0] = '#ffffff';
	}
	source.trigger('change');
""")

# create slider tool objects to control the RGB levels for first plot. Set callback function to allow refresh
red_slider = Slider(start=0, end=255, value=255, step=1, title="R", callback=callback)
green_slider = Slider(start=0, end=255, value=255, step=1, title="G", callback=callback)
blue_slider = Slider(start=0, end=255, value=255, step=1, title="B", callback=callback)
callback.args['red_slider'] = red_slider
callback.args['green_slider'] = green_slider
callback.args['blue_slider'] = blue_slider`

**Comment by jakirkham** [comment]
This is wonderful. Thanks @tobyhodges. I will take a closer look at this.

**Comment by tobyhodges** [comment]
Glad I could help!

**Comment by pzwang** [comment]
Thanks @tobyhodges!

**Comment by bryevdv** [comment]
@tobyhodges if you would l like to work up a PR with this demonstration, we would love to include in our examples!

**Comment by jakirkham** [comment]
Small clarification, as far as where the widgets can be used, is this a strictly server feature or can (or will) this be possible in iPython?

**Comment by pzwang** [comment]
The example from @tobyhodges works in-browser without a server, by using the `bokeh.models.actions.Callback` mechanism.

**Comment by jakirkham** [comment]
I see. So, I played around with an example @bryevdv came up with and was able to create this iPython notebook. The notebook can be seen here and can even be interacted with ( http://nbviewer.ipython.org/github/jakirkham/bokeh_examples/blob/master/Bokeh_Example_5.ipynb ). The original example is here ( https://github.com/bokeh/bokeh/blob/7e4484b5ae1836337a5d22f2b2d0ce7c3a37f175/examples/plotting/file/slider.py ).

**Comment by bryevdv** [comment]
Yup, the whole idea behind callbacks/actions is to enable a richer class of interactions without needing to resort to the server (the server is great, but still the more that can be done in static documents, the better)

**Comment by tobyhodges** [comment]
I’d love to help out by including this in the examples. Must warn you that I’m fairly new to bokeh, PRs, GitHub etc. so you might have to bear with me a little bit!

> On 11 May 2015, at 21:27, Bryan Van de Ven <notifications@github.com> wrote:
> 
> Yup, the whole idea behind callbacks/actions is to enable a richer class of interactions without needing to resort to the server (the server is great, but still the more that can be done in static documents, the better)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/bokeh/bokeh/issues/2270#issuecomment-101024733>.
> 


--

Dr Toby Hodges

email: tbyhdgs@gmail.com
twitter: @tbyhdgs
github: github.com/tobyhodges

**Comment by damianavila** [comment]
We always have time for a new contributor :wink: 
@tobyhodges, just let us know if you need some help.

**Comment by jakirkham** [comment]
So, I tried to do something like @tobyhodges example with an image and ran into a snafu. Here is what the example looks like ( http://nbviewer.ipython.org/github/jakirkham/bokeh_examples/blob/image_test/Bokeh_Example_9.ipynb ). This is just a variant on this example again like @tobyhodges, but with only an alpha channel and a rectangle ( https://github.com/jakirkham/bokeh_examples/blob/master/Bokeh_Example_8.ipynb ).

**Comment by bryevdv** [comment]
@jakirkham you need to pass a "vector" ov images, try `[img]`.

**Comment by jakirkham** [comment]
Ah, sorry. Thanks @bryevdv.

**Comment by bryevdv** [comment]
No need to apologize :) It's probably an interface we should improve.

**Comment by jakirkham** [comment]
Well, I'm still learning.

**Comment by jakirkham** [comment]
So, that gets me an image. However, I'm the alpha channel doesn't seem to have an effect on it. Admittedly, the `image` method doesn't state it will take `alpha`, but I was hopeful that maybe there are some arguments that all plotted objects take. Is there another way to accomplish this?

**Comment by bryevdv** [comment]
@jakirkham where does it say that? That is a documentation error. `image` takes 2d arrays of scalar data and colormaps them (on the client) using a colormap. Any alpha has to be part of the colormap itself. I think it's not unreasonable to expose a global "image alpha" tunable property, but there is not one at the moment, that would be a feature to add.

**Comment by jakirkham** [comment]
Oh, it doesn't. Sorry wasn't trying to say that it did.

**Comment by jakirkham** [comment]
Can one construct their own colormap and access it from the JS side? If so, this may expose a path for adding this feature in a very rough way.

**Comment by bryevdv** [comment]
Yes, check out:

http://bokeh.pydata.org/en/latest/docs/reference/models.html#bokeh.models.mappers.LinearColorMapper

basically you give it a list of colors and a high/low range to map between.

**Comment by jakirkham** [comment]
Right, I was just looking at this. If it is a string representing a standard palette, can one retrieve the underlying colors or does it converted to them somehow?

**Comment by jakirkham** [comment]
So, I seem to still be missing something. How am I supposed to edit the `palette`? Does its argument need to be a string (that doesn't seem to be allowed)?

I tried a few different strategies. One is shown in the updated notebook. Also, I tried using an RGBA image and changed A as needed, but had no luck. Any thoughts would be appreciated?

**Comment by jakirkham** [comment]
After my exploration of different workarounds, I am thinking that the best strategy is expose the global image alpha property that you have mentioned @bryevdv. Unfortunately, I don't know the best way to go about this. Maybe if you could give me some pointers as to where to look, I could try to come up with something.

**Comment by bryevdv** [comment]
@jakirkham, a palette is just a sequence of colors, e.g. `['#ff0000ff", "#ff00ff00", ...]` etc. 

We could also consider exposing a global alpha property for image glyphs. The first step is figuring out how it should be "spelled" in python.

**Comment by jakirkham** [comment]
Sorry, that question was a bit unclear. Let me try to rephrase it. Taking `p1` to be a figure instance. In the command below we quote the values of `x` and `y`. I am not sure if I understand that so please correct me if I am mistaken. Is this required to access them from JavaScript? If this is true, does this require the argument to `palette` also to be quoted to access it from JavaScript. If I have misunderstood this quoting behavior, please help me understand what its purpose is.

    p1.image(image=image, x='x', y='y', dw=image[0].shape[0], dh=image[0].shape[1], palette=pcm, source=source)

**Comment by jakirkham** [comment]
> We could also consider exposing a global alpha property for image glyphs.

That sounds interesting.

> The first step is figuring out how it should be "spelled" in python.

Alright, well, maybe I should step back until you have had some time to determine the right course. Though I am still interested in the outcome of that discussion.

**Comment by bryevdv** [comment]
Well, I was actually trying to solicit your thoughts on way to spell this feature. If you wanted to add a global alpha to apply to images, how would you like to be able to express it in python?

When you pass string values (instead of list of data) that is in indication to take the values from the corresponding named column in the column data source. In this case, you pass "x" and "y" so it looks int he column data source for columns named "x" and "y"

**Comment by jakirkham** [comment]
> Well, I was actually trying to solicit your thoughts on way to spell this feature. If you wanted to add a global alpha to apply to images, how would you like to be able to express it in python?

In that case, I think having a property on the image glyph would be fine. It could just be a float from 0 to 1 like other alpha values used in Bokeh. Ideally, it could be fed in the constructor or retrieved from the column source. IMHO the global alpha shouldn't mess with actual RGB colors, but only act on the alpha channel of any colors encountered. Sorry if I went too far into the weeds. Does this sound reasonable or do you have some other thoughts?

**Comment by jakirkham** [comment]
> When you pass string values (instead of list of data) that is in indication to take the values from the corresponding named column in the column data source. In this case, you pass "x" and "y" so it looks int he column data source for columns named "x" and "y"

Ok, that makes sense. So, what I am still a little unclear about is what is happening when we provide this to `Callback`? Is this copying this over as JSON then? What happens to this `source` object in JavaScript? Particularly, I am trying to understand what is happening when `source.trigger` is called.

    callback = Callback(args=dict(source=source), code="""
        ...

        source.trigger('change');
    """)

**Comment by bryevdv** [comment]
The point of passing things to `Callback` is just a convenience. You could root around int he JS objects in the fallback to get ahold of the data source, but we added the `args` parameter so you can more easily supply objects to be available from the python side. `source.trigger` triggers a backbone event, which happens to have effect of causing a redraw request.

**Comment by birdsarah** [comment]
@jakirkham - does the PR #4868 make this possible for you - I think it should but I don't have sample code to try it out with image.

**Comment by jakirkham** [comment]
That looks promising, @birdsarah. Thanks for putting that together. Let me give it a try and get back to you.

**Comment by bryevdv** [comment]
@jakirkham any update? I would expect `visible` to work just fine with image glyphs now.

**Comment by birdsarah** [comment]
Yes, I feel very confident. I'm going to close this as fixed by #4868.
