### ISSUE TITLE
Interactive Legends

### ISSUE THREAD

**Issue by bkief** [bokeh/bokeh#2274]
Placeholder for tracking, discussion, and eventual roamap inclusion regarding interactive legends.

Three wishlist items for legends that are common in other JS plotting libraries:
1) Legends off the plot area
2) Hover over legend item and respective glyphs highlight in plot
3) Click of legend item hides/shows the respective glyphs

Use cases include data identification for those with color blindness

Original discussion: https://groups.google.com/a/continuum.io/d/msg/bokeh/TymlMcwsZH0/Fs9Wpxle8SwJ

**Comment by bryevdv** [comment]
This would be a fantastic feature! My only comment is that 1) is independent of the others, and should probably be tackled separately. We are engaging with the author of the `kiwi.js` constraint solver that we currently use for canvas layout. He is also the author of PhosphorJS, and there is the possibility that this library could used to handle all Bokeh app layout, both on and off the canvas, which would be a great win. So, expanding and improving layout is still an ongoing discussion. However, 2) and 3) can be implemented immediately and independently of better layout.

**Comment by birdsarah** [comment]
Indeed. A +1 for me on "2) Hover over legend item and respective glyphs highlight in plot" - it was the first thing someone coming from C3js asked me for recently (http://c3js.org/samples/simple_multiple.html).

**Comment by xmnfw** [comment]
Interactive Legends will be great, for a specific app I need this feature and when it's done I can migrate it from highcharts :), maybe I can help to test.

**Comment by bkief** [comment]
@bryevdv @damianavila  It seems like suggestions 2 & 3 for interactive legends have some enthusiasm behind them. I personally really do like the C3JS implementation Sarah mentioned. Would it be possible to add this feature request as a milestone?

**Comment by damianavila** [comment]
Changed to feature request and adding long-term milestone (we can change that later if we pursue a short-term implementation...

**Comment by bkief** [comment]
@bryevdv I have two thoughts regarding off plot legends. Would it be possible to pad the side of the plot with the legend and have the legend placement ignore the padding, resulting in the legend being placed on top of the padding whitespace? It would effectively be off the plot but on the same html canvas. If not... the toolbar is its own element nestled into the plot table. Why not do the same with the legend? At the moment, the legend is static anyways so it could even be PNG in its own table cell. Just thinking out loud and I thought I would pass along.

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by birdsarah** [comment]
Related request: #3715

**Comment by mattpap** [comment]
I started working on this as a side-effect of work on inspection/selection management (the connection may not be immediate).

**Comment by aiguofer** [comment]
Big +1 for this!

I'm a big fan of how Plotly handles legends, [here's a link](https://plot.ly/python/legend/) to some of their examples for some inspiration.
