### ISSUE TITLE
Matplotlib to bokeh conversion discards category labels

### ISSUE THREAD

**Issue by CatherineH** [bokeh/bokeh#2277]
I'm trying to get seaborn violin plots working in bokeh. I'm following [this example](http://bokeh.pydata.org/en/latest/docs/gallery/violin.html?highlight=violin) . My category labels seem to get discarded on conversion to bokeh. Here's some minimal code:
```python
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from bokeh import mpl
from bokeh.plotting import show

# generate some random data
data = 1 + np.random.randn(20, 6)
my_names = ["kirk","spock","bones","scotty","uhura","sulu"]

# Use Seaborn and Matplotlib normally
my_mpl = plt.figure()
#when seabord is called directly, names works for assigning categories
sns.violinplot(data, color="Set3", names=my_names)
my_mpl.savefig("mpl_test.png")
my_bokeh = mpl.to_bokeh(my_mpl)
print type(my_bokeh)
# Convert to interactive Bokeh plot with one command
show(my_bokeh)
```

This is the image that matplotlib produced:
![mpl_test](https://cloud.githubusercontent.com/assets/1953328/7593659/c7295b08-f8a9-11e4-9779-c760c5b833e7.png)
and the image after converting to bokeh:
![mpl_test2](https://cloud.githubusercontent.com/assets/1953328/7593675/dbfdae12-f8a9-11e4-9c8c-212deb3c537e.png)

**Comment by philippjfr** [comment]
Just as a quick update to this issue. It seems to get the categorical axis labels now but they are drawn in the wrong place. Here's a quick example:

```python
import seaborn as sns
from bokeh import mpl
from bokeh.io import output_notebook, show

output_notebook()
iris = sns.load_dataset("iris")
sns.violinplot(iris.sepal_length, iris.species)
show(mpl.to_bokeh())
```

![image](https://cloud.githubusercontent.com/assets/1550771/9976360/b3da1452-5ed9-11e5-839d-fd1bb8b590e3.png)

**Comment by chbrandt** [comment]
@philippjfr As of versions bokeh-0.11.0 and seaborn-0.7.0 the plot works fine.
