### ISSUE TITLE
TestMatrix script not in sync with BEP 2

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2282]
The issue is that we should use it to test against the RC which is installable/testable following #1107 (basically dev channel) but the script cmds do not specify the right channel for conda or pip. The result is that the script ends up always installing the previous version and doesn't correctly pick up the newest RC build.

Should be enough to change [envs](https://github.com/bokeh/bokeh/blob/master/scripts/test_matrix.py#L168) dict to add the right channel to the cmds being executed.

**Comment by Maggie-M** [comment]
Thanks, Fabio!  

I'm going to get started on a PR either tomorrow or next week to make this change and streamline the overall script, as well.

**Comment by fpliger** [comment]
@Maggie-M I already started working on this on a local branch. Should push tomorrow. I'd be awesome if you can check it out :-)

**Comment by Maggie-M** [comment]
I'll be sure to check it out!  Thanks a bunch!

**Comment by bryevdv** [comment]
I ws suggesting to @Maggie-M that maybe it would be good to pare the existing script down to just create the set of testing env? That by itself is super useful. Then any automated or semi-automated testing helpers could go in other scripts. Thoughts?

**Comment by fpliger** [comment]
That's basically the change I've done... that breaks down in:

- create the envs with the right channels
- install the right dependencies for the tests (now I'm doing if for OS X only but it'd be good to break for Win and Unix)

If you pass the `--keep` parameter it'll basically keep the envs after running the tests. @bryevdv was that what you were suggesting?

**Comment by bryevdv** [comment]
I'm suggesting not having the tests at a all, or having the tests run from a different script, and just having a simple script does nothing except set up all the desired get envs.

**Comment by fpliger** [comment]
:+1:  that's easy with a few tweaks
