### ISSUE TITLE
When 'poly select' tool is clicked, should pan be disabled?

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2287]
Would it be a good idea to turn off panning as soon as someone clicks the poly select tool?  It requires the user to click on various areas of the plot, but if they accidentally drag, the plot will move underneath them and take the selection with it.  

I would imagine this would end up being frustrating.

Edit: Here are some screenshots to show what I mean

Here is the initial selection

![screen shot 2015-05-13 at 1 42 07 pm](https://cloud.githubusercontent.com/assets/1417520/7618186/06ed5646-f976-11e4-87b4-94a942d38529.png)

And here's what happens if you drag the plot

![screen shot 2015-05-13 at 1 42 30 pm](https://cloud.githubusercontent.com/assets/1417520/7618195/11926352-f976-11e4-9070-4c9ab3265952.png)

**Comment by Maggie-M** [comment]
Also, if you resize, the selection stays the same.

**Comment by bryevdv** [comment]
I don't think the poly tool gets much use at all. We can re-visit this in the future if there is interest expressed.
