### ISSUE TITLE
glyph/buttons_server.py dropdown red button looking bad (cut) in Chrome

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2289]
glyph/buttons_server.py have dropdow red button looking bad (cut) in Chrome.
Js console:

```
bokeh: setting prefix to /
bokeh.js:43725 Bokeh: setting log level to: 'info'
bokeh.js:27938 Uncaught Error: cannot call methods on button prior to initialization; attempted to call method 'toggle'
jsnlog.js.map:1 GET http://localhost:5006/bokehjs/static/js/jsnlog.js.map 404 (NOT FOUND)
```

**Comment by bryevdv** [comment]
Looking fine now:

<img width="386" alt="screen shot 2016-07-02 at 11 00 18 pm" src="https://cloud.githubusercontent.com/assets/1078448/16543705/cc75e584-40a8-11e6-879b-69bc3d521e66.png">
