### ISSUE TITLE
Update BEP2 install instructions

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2293]
#1107 installation and instructions work ok on unix and not windows or mac. Should be reviewed and updated

**Comment by jakirkham** [comment]
> #1107 installation and instructions work ok on unix and not windows or mac....

Figure this should go here as opposed to another issue. From the bokeh git repo, running `conda build conda.recipe` won't work on Mac or Windows as there is no build of `pdiff`. I started working on changes to the existing recipe to build FreeImage (required by `pdiff`), but they have stalled at present.

**Comment by damianavila** [comment]
This is probably not the correct issue... can you open a new one describing the same? Thanks!

**Comment by bryevdv** [comment]
pdiff should absolutely not be a required dep to build packages. It is a dev dep and even then really only for CI.

**Comment by damianavila** [comment]
This is done by now...
