### ISSUE TITLE
Crossfilter filter broken on IE

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2295]
crossfilter filtering by continuous field on IE raises the following error when range is selected: SCRIPT7002: XMLHttpRequest: Network Error 0x2efe, Could not complete the operation due to error 00002efe.

**Comment by brendancol** [comment]
this crossfilter example has been replaced...closing old ticket.

**Comment by damianavila** [comment]
@brendancol can you link the PR where it was replaced... just for reference.
