### ISSUE TITLE
It's possible to extend the lasso tool outside the bounds of a plot

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2297]
For reference, this is version '**0.9.0rc-8f3c806-18-g08c81cb**'

![untitled](https://cloud.githubusercontent.com/assets/1417520/7637447/96059696-fa33-11e4-90ee-84f46c760595.png)

**Comment by bryevdv** [comment]
one solution is just to cancel/reset current tool when mouse exits inner area, but another would make the tool boundary "hug" the inner frame
