### ISSUE TITLE
Suggestion for improvement to a specific portion of Bokeh documentation

### ISSUE THREAD

**Issue by kohaugustine** [bokeh/bokeh#2304]
Dear All,

Following a thread I had on the Bokeh Google group with @fpliger , I am creating this issue and would like to contribute that which I have mentioned on the thread to the Bokeh documentation. This is the post:  https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/taptool/bokeh/Lo51k7dU0TQ/ZWTGwSt6xgMJ 

So from what I understand, the next thing I need to do is a Pull request right? But I don't quite understand how that is supposed to work. I am familiar with Git and in my developer team I work collaboratively with Git and a shared repo on Bitbucket, but all this stuff with Pull requests are new to me. At least I believe the first thing I need to do is to clone the whole Bokeh repo right? But after that, which branch should I choose to initiate this pull request and change thingy?

Thank you.

Best,
Augustine

**Comment by birdsarah** [comment]
Hi Augustine. I know how confusing this can be the first few times. Don't hesitate to ask questions.

This https://guides.github.com/introduction/flow/index.html might be useful.

If you can do the following:
* fork the bokeh repo (https://github.com/bokeh/bokeh#fork-destination-box)
* pull it down to your local environment (git clone git@github.com:kohaugustine/bokeh.git)
* make a branch (git checkout -b my_new_branch)
* make your changes 
* push this branch back up (git push --set-upstream origin my_new_branch)

then github should give you a nice PR button.

Good luck!

**Comment by birdsarah** [comment]
This might help: https://github.com/asmeurer/git-workflow

**Comment by bryevdv** [comment]
In any case the question seems to be answered, so closing
