### ISSUE TITLE
Broken link to help pages from Bokeh plots

### ISSUE THREAD

**Issue by cdeil** [bokeh/bokeh#2311]
At http://bokeh.pydata.org/en/latest/docs/quickstart.html#getting-started and every other Bokeh plot there's the question mark to get help:
![screen shot 2015-05-18 at 20 22 55](https://cloud.githubusercontent.com/assets/852409/7687204/c20f2f2a-fd9b-11e4-97e0-0adbeb653507.png)

At the moment this points to http://bokeh.pydata.org/en/latest/docs/user_guide/objects.html#tools which is a broken link, i.e. gives a 404.

**Comment by bryevdv** [comment]
Ah, there was a complete re-write of the user's guide, must have missed updating this detail. I've added a 301 redirect that should get folks to the right place for now. @Maggie-M will update the URL in the tool to be correct in future releases.
