### ISSUE TITLE
sampledata.download() defaults to home directory

### ISSUE THREAD

**Issue by g24swint** [bokeh/bokeh#2313]
We have tight quotas on our home directory to make sure that we keep regulated data in regulated partitions. Therefore, sampledata downloading to a hidden directory off of a home directory is sneaky and hard to troubleshoot when the data downloads fail. Perhaps installing data to a location relative to the conda environment or virtualenv would solve the problem

**Comment by bryevdv** [comment]
@g24swint The should be configurable:

https://github.com/bokeh/bokeh/blob/master/bokeh/sampledata/__init__.py#L30

i.e., a YAML file `~/.bokeh/config` with a `sampledata_dir` key that points to a different location. This obviously never got documented properly, so I am marking this issue as a docs task to add the needed docstring.
