### ISSUE TITLE
Apply LOD to slider widget

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2315]
Hi, 

Am loving the work done in PR #2148 (Client side LOD downsampling for interactive tools)

Was thinking it would be really good to have this on the slider with call back. Slider, like pan, is one of those things with a high temptation factor for creating lots of events quickly.

Thoughts?

**Comment by bryevdv** [comment]
My only observation is that the tunable parameter values that work pretty well for pan/zoom etc. may not be the same values that work well for a slider. In which case we might have to consider moving those parameters to the tools, and communicating them to the plot as needed. Hopefully the defaults are or can be made to work reasonably in all cases, though.

**Comment by bryevdv** [comment]
The other thing to consider is that widgets like sliders can communicate with the server. We would have to figure out what interaction model makes sense for both together.

**Comment by birdsarah** [comment]
"In which case we might have to consider moving those parameters to the tools, and communicating them to the plot as needed." That sounds right to me - having them on the plot is convenient, but having them on the tool seems more expected.

"The other thing to consider is that widgets like sliders can communicate with the server. We would have to figure out what interaction model makes sense for both together." Indeed - I think this might be even more importan. Generating a whole string of network requests because you want to slide the slider around is one of the big downfalls of my africa map server visualization.

**Comment by bryevdv** [comment]
`callback_throttle` and `callback_policy` were added to afford users options for limiting the number of updates.
