### ISSUE TITLE
Text glyph font size from ColumnDataSource field not working in 0.9

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#2316]
In 0.9, I can't link the value of the text size of a text glyph to a field in a ColumnDataSource.  This worked in 0.8.1.

Example using 0.8.1: http://jsfiddle.net/e26k8m1c/
Same example using 0.9.0: http://jsfiddle.net/eLsvnd1g/

**Comment by bryevdv** [comment]
Gah, this is an ugly little bug. Text glyphs and string properties have always been slightly problematic in that strings are used as both literal data values, and as column names. We did a huge cleanup of the internal code that handles properties in BokehJS, and I added tests for all the individual properties (which was a great improvement), but it looks like I forgot to add tests for the property collections (line, fill, text) and that's where the problem becomes evident. I think we will have to put out a 0.9.1 bug fix release fairly soon, perhaps next week. @bokeh/core

**Comment by hafen** [comment]
Cool.  I'm happy to test it out.

**Comment by damianavila** [comment]
I guess, we can have a point release by the end of the next week... or very early the subsequent week (25-26 May). I would like to see 0.9.0 on stage a little bit more to collect more bugs but if this is issue really pressing enough, we can make the point release early next week....

**Comment by hafen** [comment]
Whatever makes sense for you guys is good for me.

**Comment by hafen** [comment]
I just tested the 0.9.1 dev release and it appears this hasn't been addressed.  Is it planned to part of 0.9.1?  This is holding back the update to 0.9 for rbokeh because we have examples that rely on this.  Thanks!

**Comment by bryevdv** [comment]
I'm out traveling, I will try to get to it next week, I definitely intend for it to be fixed for 0.9.1

**Comment by jcrist** [comment]
This just bit me today. Anything I could do to expedite this?

**Comment by bryevdv** [comment]
I am going to try and look at this tomorrow on the way back the U.S.
