### ISSUE TITLE
Some glyphs disappear on zoom / pan in 0.9.0

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#2318]
A few of my test plots have glyphs that disappear when I pan or zoom in 0.9.0.  Here is an example:

0.8.2: http://jsfiddle.net/5emysrbu/
0.9.0: http://jsfiddle.net/vb0y7mq0/

In 0.8.2, zoom / pan is smooth with no missing glyphs.  In 0.9.0, on zoom / pan, several of the points / lines disappear and the appearance of the points is changed.

I've played around with some more simple examples to see if I could pinpoint what the problem is but I haven't been able to figure it out.  I thought it might have something to do with datetime axis, but I have another (more complex) example with numeric axes and patches where most of the patches disappear on pan / zoom.  I wish I could point to something specific as the cause, but maybe it will be obvious to the developers.

**Comment by bryevdv** [comment]
This is a feature:

http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#controlling-level-of-detail

Basically, the level of detail can be reduced during interactive events, to preserve a higher level of interactivity. If you don't want it, you can turn it off (set `lod_threshold` to `None`)

**Comment by hafen** [comment]
Ok - thanks.  That's nice.  I missed that in the update announcement.
