### ISSUE TITLE
ImageURL not extending as expected (until after zoom / pan)

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#2319]
When placing an image using ImageURL and specifying height and width, initially the image does not extend to the full height until after a zoom / pan operation.  An example here that has height and width = 10:

http://jsfiddle.net/nfng1yka/

The image height is 9 until I zoom or pan and then it goes to 10 as expected.

Note that this was an issue pre 0.9.

**Comment by canavandl** [comment]
Related to #2127

**Comment by canavandl** [comment]
Closed with #2786
