### ISSUE TITLE
Using hover (with a JS callback)

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#2324]
I am trying to understand something. Is it possible to trigger a JavaScript callback via a hover event? For example, I have the following notebook ( http://nbviewer.ipython.org/github/jakirkham/bokeh_examples/blob/master/Bokeh_Example_10.ipynb ). Currently, I can click on a point in the first graph and this will show a trace for that point in the bottom window (multiple selection is not implemented). I am curious if the same effect could be accomplished using hovering instead of click selection.

**Comment by birdsarah** [comment]
I'm afraid this is not possible at the moment @jakirkham.

**Comment by jakirkham** [comment]
Thanks for clarifying @birdsarah. Just so I understand, what would be required to get this to work.

**Comment by birdsarah** [comment]
@bryevdv is probably best placed to answer that.

**Comment by bryevdv** [comment]
Adding a JS callback to the hover tool would be pretty trivial, it just needs someone to actually work on it. Here is an issue that covers the features:

https://github.com/bokeh/bokeh/issues/2346

**Comment by jakirkham** [comment]
Oh, sorry, the second part was addressed to anyone. Thanks for the answer @bryevdv.

**Comment by bryevdv** [comment]
I've added this to #2346, so marking this as a dupe (can continue discussion on other issue)
