### ISSUE TITLE
Implement "CARP" authentication component as per tswicegood's recommendation

### ISSUE THREAD

**Issue by mcdonc** [bokeh/bokeh#2327]
Travis suggested that we implement proxy authentication by placing a component in front of Bokeh server that is capable of authenticating incoming requests.  The document he created explaining this is at https://gist.github.com/tswicegood/cbefc28d1672f4edd8e0

My suggestion here is to make use of existing components.  [repoze.who](https://repozewho.readthedocs.org/en/latest/) is a pluggable authentication layer for WSGI applications.  This system is the system currently used by TurboGears for its authentication component, and has been under development for several years.  It has a pluggable architecture, so custom authentication layers can be written as necessary for each client deployment.

Concerns are:

- Websockets.  I believe it will only be possible to authenticate the upgrade request
  for a websocket connection, and no further authentication will be able to get done,
  because websocket communication does not take place over WSGI.  I think this
  is probably acceptable.

- Documentation.  ``repoze.who`` is fairly complex, and although it has its own set
  of integration documentation, suggesting it to external people will require a more
  focused set of Bokeh-specific documentation.

**Comment by bryevdv** [comment]
ping @tswicegood @bkreider

**Comment by bryevdv** [comment]
This work is being done elsewhere by other people. Bokeh will integrate with it but the new server does not have specific a built in notion of auth
