### ISSUE TITLE
bokeh-server internal blaze.server magic

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2330]
``bokeh-server`` internal blaze.server seems to be doing something "more" so that the same data served within ``bokeh-server`` to a ``BlazeDataSource`` works while the same data served with 

```python
server = blaze.Server({'dat': gauss})
server.run(host="127.0.0.1", port=9000)
```

fails (because it serves a different json output).

More in details. ``bokeh-server`` blaze server returns:

```
{"data": [[1, 10], [2, 9], [3, 8], [4, 7]], "names": ["oneA", "oneB"], "datashape": "4 * {oneA: int64, oneB: int64}"}
```
while blaze.server returns:

```
{"data": [[1, 10], [2, 9], [3, 8], [4, 7]], "datashape": "4 * {oneA: int64, oneB: int64}"}
```

**Comment by bryevdv** [comment]
ping @fpliger is this a docs issue or are there changes to propose?

**Comment by fpliger** [comment]
@bryevdv the proposed change here is to either change a few bits to support `blaze.server` (which is different from the multiuser blaze server that we rely on) or ask the blaze team to add what we need to `blaze.server` to make it work. From what I've seen the second choice would be easier... but we can discuss that.

**Comment by cpcloud** [comment]
it'd be pretty easy to add the column names as output when we can. should i make an issue?

**Comment by fpliger** [comment]
@cpcloud  :+1: that'd be awesome if you could! Hopefully this should be enough to close this issue...

**Comment by cpcloud** [comment]
@bryevdv @fpliger i've added the `'names'` to the blaze server response blob. can you guys give a quick review to confirm that this does what you want? thanks!

**Comment by fpliger** [comment]
@cpcloud it's perfect thanks! I'll wait for https://github.com/ContinuumIO/blaze/issues/1131 and then close this issue! :+1:

**Comment by damianavila** [comment]
@fpliger I guess this one can be closed, am I right? I also guess this has to be documented, since you were using this (I suppose), can you take an stab on it? Just a few lines is enough... thanks!

**Comment by damianavila** [comment]
Previous milestone: 0.9.1

**Comment by fpliger** [comment]
@bokeh/core I'd like to close this issue (since many things changed on bokeh and blaze and BlazeDataSource is broken at the moment AFAIK) and open a specific issue for a broader discussion with the both teams. Any objections?

**Comment by bryevdv** [comment]
+1

**Comment by damianavila** [comment]
@fpliger can you cross reference thee issue when you open it? Thanks!
