### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by alexandrul** [bokeh/bokeh#2338]
Environment:
* Python 3.4.3 64 bit
* IPython 3.1.0 
* Bokeh 0.9.0

IPython notebook content:
```python
# In[ ]:
from pandas import Series, DataFrame, Panel, read_excel, concat, merge
import bokeh.plotting as bp
import bokeh.charts as bc

# In[ ]:
bp.output_notebook()

# In[ ]:
df = DataFrame.from_csv('d:\\test.csv')

# In[ ]:
p = bc.BoxPlot(df, title='title', xlabel='x', ylabel='y', width=300, height=400, marker="circle", outliers=True)
bp.show(p)
```

Input data:
```
,A,B
0,620,600
1,623,610
2,597,594
3,610,621
4,610,630
```
Error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-5bcd433f5ba9> in <module>()
----> 1 p = bc.BoxPlot(df, title='title', xlabel='x', ylabel='y', width=300, height=400, marker="circle", outliers=True)
      2 bp.show(p)

# ...Python\lib\site-packages\bokeh\charts\builder\boxplot_builder.py in BoxPlot(values, marker, outliers, xscale, yscale, xgrid, ygrid, **kw)
     82     return create_and_build(
     83         BoxPlotBuilder, values, marker=marker, outliers=outliers,
---> 84         xscale=xscale, yscale=yscale, xgrid=xgrid, ygrid=ygrid, **kw
     85     )
     86

# ...Python\lib\site-packages\bokeh\charts\_builder.py in create_and_build(builder_class, values, **kws)
     40     chart_kws = { k:v for k,v in kws.items() if k not in builder_props}
     41     chart = Chart(**chart_kws)
---> 42     chart.add_builder(builder)
     43
     44     return chart

# ...Python\lib\site-packages\bokeh\charts\_chart.py in add_builder(self, builder)
    116     def add_builder(self, builder):
    117         self._builders.append(builder)
--> 118         builder.create(self)
    119
    120         # Add tools if supposed to

# ...Python\lib\site-packages\bokeh\charts\_builder.py in create(self, chart)
    164         self._adapt_values()
    165         self._process_data()
--> 166         self._set_sources()
    167         renderers = self._yield_renderers()
    168

# ...Python\lib\site-packages\bokeh\charts\builder\boxplot_builder.py in _set_sources(self)
    222         ## Expand min/max to encompass outliers
    223         if self.outliers:
--> 224             start_out_y = min(self._data_scatter[self._attr_scatter[1]])
    225             end_out_y = max(self._data_scatter[self._attr_scatter[1]])
    226             # it could be no outliers in some sides...

ValueError: min() arg is an empty sequence
```

**Comment by canavandl** [comment]
BoxPlot has an "outlier" attribute that will add outlier data points (as scatters) to the boxplot figure. When the the attribute is set to True (default=True), the code boxplot_builder.py code doesn't check that any outlier datapoints actually exist in self._data_scatter['out_y'], so a ValueError exception on applying min.

**Comment by hazemsamoaa** [comment]
I apply your advice by setting outliers=False, but nothing changed, I'm still getting the same error @damianavila @canavandl

**Comment by bryevdv** [comment]
@hazemsamoaa The `bokeh.charts` API including the `BoxPlot` function in the original issue was deprecated and subsequently removed form Bokeh serveral years ago now. It is no longer supported in any way. For higher level APIs on top of Bokeh please look to other projects:

* Holoviews
* Pandas-Bokeh
* Chartify

**Comment by marcox23** [comment]
I had the same problem, changing outliers doesn't work either, reviewing I noticed that the problem of min() arg is an empty sequence, implies that an empty list is being sent to minimize, in my case I was sending data type "str " and data of type "float64", which is not supported for plot since it only supports one or the other, this is why I transformed all the data in the column with astype()

df[column]=df[column].astype(float)

this may be because where you extracted the information from it was found with semicolons, or it was simply created as "str".

you can check the type of the column variables with type()

@alexandrul

**Comment by alexandrul** [comment]
@marcox23 thank you for the possible explanation.
In my case the CSV format was consistent, but I don't have the original file anymore (and, in the meantime, bokeh has deprecated boxplot).

**Comment by bryevdv** [comment]
`bokeh.charts` was entirely removed more than half a decade ago, there is no value to discussing it in this tracker.
