### ISSUE TITLE
heatmap.ipynb in /../Examples/bokeh/charts/notebook/ won't load

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2340]
The heatmap.ipynb example in /../Examples/bokeh/charts/notebook/ won't load. Trying to open it from the ipython notebook tree page just gives an "Error loading notebook" window. I would guess that there is an error in the JSON structure (i.e. a missing bracket).

Bokeh 0.9.0
Python 3.4.3
ipython-notebook 3.1.0

**Comment by canavandl** [comment]
If anybody else can reproduce the error, I will read through the .ipynb file to try and find the problems. Otherwise, i can pull out the cell contents and make a new notebook.

**Comment by damianavila** [comment]
I can load it successfully locally and it is rendered ok with github and nbviewer. Maybe your copy is corrupted?

**Comment by canavandl** [comment]
Neither my development build (.../bokeh/examples/charts/notebook from cloning the bokeh repository) nor my conda install (~/anaconda/envs/bokeh-prod/Examples/bokeh/charts/notebook) work. All of the others are fine for me though.

You have any advice for debugging? I just get the "Error loading window" message and the ipython notebook server doesn't log anything on the failure.

**Comment by damianavila** [comment]
Can you post the file somewhere else (maybe a gist) so I can try to reproduce the error?

**Comment by canavandl** [comment]
https://gist.github.com/canavandl/13259d94d58786dd5aa8

You're right - it seems to load normally on nbviewer. Idk what my problem is...

**Comment by damianavila** [comment]
I can not reproduce your probably with this file neither... not sure what else to suggest...
In any case, I will close this one, we can reopen it if someone else can reproduce it...

Just a last thought... can you try removing the checkpointed ipynb (normally hidden in a `.checkpoint` folder in the same path where this notebook lives) and reload it again?
