### ISSUE TITLE
bokeh version not updated on syncing old fork to bokeh master

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2341]
I forked the bokeh repository when it was at 0.8.2 and today I cloned my fork, added the bokeh repo as an upstream remote and pulled the upstream master onto my master in order to be current with the 0.9.0 version.

I built BokehJS and ran the python setup.py and it all works normally, except that when I check the version of my 0.9.0dev build, it thinks prints 0.8.2dev

```bash
$ python -c "import bokeh; print(bokeh.__version__)"
0.8.2dev-ec4e00a-691-g5411f7b-dirty
```

If I clone the bokeh repo directly and build BokehJS/run setup.py, I get the correct bokeh version.

I don't know if this is worth figuring out/fixing, but I saw there was some weird versioning behaviour elsewhere (i.e. Issue #2284) that may be related. 

Ubuntu 14.04

**Comment by damianavila** [comment]
Can you give me the output of `git tag -l`? I am suspecting you are not getting all the tags for some reason...

**Comment by canavandl** [comment]
...
0.8.0
0.8.0-rc-1297302
0.8.0-rc-4cb754e
0.8.0-rc-81147f9
0.8.1
0.8.1-rc-59eabd0
0.8.2dev-7e5b7b1
0.8.2dev-ec4e00a
xdata-0.1rc

**Comment by damianavila** [comment]
OK, the latest tags are not there, as I suspected... can you try:

 `git pull upstream_name_for_boke_repo --tags`

and check if you have the latest ones?

**Comment by canavandl** [comment]
yup - that did it.
