### ISSUE TITLE
Better blaze.server/bokeh integration

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2345]
At the moment `bokeh-server` uses `multiuserblazeserver` (as hard dependency) internally and do not support `blaze.server`. My proposal is to:

- change dependency from 'multiuserblazeserver' to `blaze.server`
- soften `blaze.server` usage in order to let users use a `blaze.server` out of it (serving on a different port)

**Comment by bryevdv** [comment]
This is no longer relevant.
