### ISSUE TITLE
Extend JSCallback support

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2346]
We should support JSCallbacks also for the following:

* [x] Range changes
* [x] ~~~Plot Initialization~~~
* [x] AjaxDataSource (that is called within `get_data` before and after getting the new data so that users can add a custom logic to manipulate the new data)
* [x] ~~~DOM resize events~~~
* [x] Hover tool
*  [x] ~~~Tap tool~~~

**Comment by bryevdv** [comment]
Perhaps DOM resize events too.

**Comment by bryevdv** [comment]
Hover has also been requested

**Comment by birdsarah** [comment]
TapTool please :) #2378

**Comment by fpliger** [comment]
@birdsarah right now you could use the JSCallback on the selection instead of the TapTool itself...

**Comment by birdsarah** [comment]
@fpliger - awesome - will give it a try.

**Comment by canavandl** [comment]
@birdsarah (this may be what @fpliger said), but TapTool has an "action" attr that will accept a Callback instance (see example: http://nbviewer.ipython.org/gist/canavandl/cc98e08716c067af3c70)

Is that enough for your usecase?

**Comment by birdsarah** [comment]
@canavandl - my understanding is that @fpliger is referring to the Callback on DataSources - https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L42 - which "runs in the browser whenever the selection is changed."

Action was introduced before Callback, and may actually be redundant now.

**Comment by bryevdv** [comment]
ping @chdoig who is interested as well. @canavandl please work on the range change callback next, that one will be needed for SciPy demos we want to create.

**Comment by colinfang** [comment]
@birdsarah Sorry for the noise,  I am still a bit confused about the difference between `action` and `callback`. Could you elaborate a little bit more? Or you meant `callback` would deprecate `action`?

**Comment by damianavila** [comment]
@bokeh/core, this is a meta-issue... it has to be splitted after discussion about a common interface for callbacks, so I would change the milestone to short-term and if you are working in one of the listed item, please reference this issue in a new one **specifically** dedicated to one of the points listed in the first post of the thread. Thanks!

**Comment by birdsarah** [comment]
Hi all, not entirely sure where the right place to put this is, so putting it here for now.

@bryevdv and I had a chat about how/why `Action` & `Callback` confuse me. Maybe no-one else suffers from this confusion, but I'm documenting it here in case anyone else wants to chip in and we want to make some last minute name changes before we're all really embedded in the current naming.

What is a callback? I have no idea what an appropriately highbrow source is to quote from so I'm going with [wikipedia](https://en.wikipedia.org/wiki/Callback_%28computer_programming%29) "a callback is a piece of executable code that is passed as an argument to other code, which is expected to call back (execute) the argument at some convenient time." This matches with my understanding of a callback.

Currently in Bokeh we have a parent class `Action` and two subclasses `OpenURL` and `Callback.`

As @bryevdv pointed out `OpenURL` is meant to be a "canned action" that is something common that people want to do and they don't have to write their own javascript.

The confusion started when I said that I thought that `OpenURL` should be subclass of `Callback`.....

....after hashing it out we realized that my confusion was names. It would make more sense to me if 

* Action -> Callback
* Callback -> CustomCallback

That is all Actions are callbacks in my generic understanding of the word. What we have currently called Callback is infact a `CustomCallback` where the user gets to specify their own JS code and we may want to make canned implementations like `OpenURL.`

@colinfang - I don't know if this helps.....

**Comment by canavandl** [comment]
Closing at resolved as callback -> CustomJS refactor as happened in 0.10.0
