### ISSUE TITLE
Link RemoteSource to Actions

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2347]
If we support linking `RemoteSources` to actions we can make those sources (`AjaxDataSource`, `BlazeDataSource`, ...) update only when action are fired without having to keep polling

**Comment by bryevdv** [comment]
ping @fpliger can you provide more detail?

**Comment by fpliger** [comment]
Sure. Let's say I have a REST API that I give to my `AjaxDataSource` or either a `BlazeDataSource` pointing to a blaze server and I just want to call them again when a slider or a TextInput changes its value (maybe passing the value of the input as a parameter on that API endpoint)... Maybe we could express this somehow like:

```
source = AjaxDataSource(..., polling_interval=-1)
slider=Slider(..., callback=source)
```

This means that source only sends a new request when slider calls it as a callback.. or something similar. 
Probably needs a better glance at how this could be really implemented but I hope this gives a general idea.

**Comment by bryevdv** [comment]
Something this specialized could (should) go in a custom extension.
