### ISSUE TITLE
Change color of each Bar in a Bar graph

### ISSUE THREAD

**Issue by moqca** [bokeh/bokeh#2349]
Is there a way to have each Bar on a Bar graph have a different color?
I want to color the bars based on their value. I was thinking that using a palette would work for this, but this changes the color for all bars.

**Comment by canavandl** [comment]
Q: Is there a way to have each Bar on a Bar graph have a different color?
A: Not really. The way the colormapper maps the color across the bars is that each "category" of bars are given the same color.

source: http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#bar-and-dot-charts

Solutions:

The hacky solution is to make a grouped bar chart that has only 1 group and each value is it's own category. This would allow you to apply a palette across the set of bars.

    from bokeh.charts import Bar, output_notebook, show, vplot
    from bokeh.palettes import Blues5

    output_notebook()

    data = {"a":[4,], "b": [6,], "c":[7,], "d":[2,], "e":[6,]}  ## makes each value a unique category
    ##data = [4, 6, 7, 2, 6] will make them all the same category

    plot2 = Bar(data, title='Unstacked example', stacked=False,
           xlabel='categories', ylabel='values', width=400, height=400, palette=Blues5,
           tools = "pan,wheel_zoom,box_zoom,reset,resize")

    show(plot2)

The better solution is to manually make a bar chart with Rects and relate each color it the Rect height.

source: http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#rectangles-and-ovals

**Comment by fpliger** [comment]
@canavandl well covers covers the current status of `Bar` implementation. My recommendation is to use `plotting` API for the time being.

That said, we have been including this use case in the discussions regarding improvements for the charts API.

**Comment by moqca** [comment]
Thank you both, that worked

**Comment by euri10** [comment]
I did it this way, relevant part is
```python
bar_source[i].data['color'] = [palette[i]]
```
the rest is just so you get the various variables

```python
    p = Bar(df, values='sec', label='label', tools='pan,wheel_zoom,box_zoom,reset,resize,hover')

    # axes range fix, bugged (https://github.com/bokeh/bokeh/issues/2975)
    min_y = min(df['sec'])
    max_y = max(df['sec'])
    dy = 0.1 * ((max_y + max_y) / 2)
    low = min_y - dy
    high = max_y + dy
    p.y_range = Range1d(low, high)

    # hover
    glyph_renderers = p.select(GlyphRenderer)
    bar_source = [glyph_renderers[i].data_source for i in range(len(glyph_renderers))]

    import colorsys

    def get_N_HexCol(N):

        HSV_tuples = [(x * 1.0 / N, 0.5, 0.5) for x in xrange(N)]
        hex_out = []
        for rgb in HSV_tuples:
            rgb = map(lambda x: int(x * 255), colorsys.hsv_to_rgb(*rgb))
            hex_out.append("".join(map(lambda x: chr(x).encode('hex'), rgb)))
        return hex_out

    palette = ["#" + toto for toto in get_N_HexCol(len(glyph_renderers))]
    print(palette)

    for i in range(len(glyph_renderers)):
        print(bar_source[i].data)
        bar_source[i].data['color'] = [palette[i]]

**Comment by euri10** [comment]
even simpler leveraging seaborn

```python
import seaborn as sns
palette = sns.color_palette("BuGn_r", len(glyph_renderers)).as_hex()

**Comment by rothnic** [comment]
@euri10, I'm working on the documentation to avoid pain points like this. What you had to do is exactly what the new charts interface is trying to avoid, a whole bunch of logic that is not relevant to creating a chart. There is currently built-in functionality that should allow you to do this.

See the [color attribute spec function](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/_attributes.py#L189). With the new charts, all of the attributes use an AttrSpec, which is simply a lazy evaluated mapper. The intent is that once I get more of this implemented, I could open up more for people to provide their own AttrSpecs, or easily generate custom ones that differ from the default behavior. See below:

```python
# simple use
Chart(df, x='a', y='b', color='c')
# equivalent
Chart(df, x='a', y='b', color=color(columns='c'))

# multiple columns
Chart(df, x='a', y='b', color=['c', 'd'])
# equivalent
Chart(df, x='a', y='b', color=color(columns=['c', 'd']))

# specifying palette
# import your palette here from whatever source
Chart(df, x='a', y='b', color=color(columns=['c', 'd'], palette=palette))
```

I plan for the `color` function (which produces a [ColorAttr](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/_attributes.py#L127)) to support more options at some point, which would provide easy ways for generating the color specifications.

**Comment by euri10** [comment]
many thanks, waiting 4 the color generator, that was much simpler than what I did :)

```python
    import seaborn as sns
    palette = sns.color_palette("GnBu_d", len(df.index.tolist())).as_hex()
    print(palette)

    p = Bar(df, values='sec', label='label', tools='pan,wheel_zoom,box_zoom,reset,resize,hover', color=color(columns=['sec'], palette=palette))

**Comment by rothnic** [comment]
You should be able to use it now, it just isn't yet documented in the user guide. Current behavior is it cycles the palette, then looks into the column(s) you are using for coloring for the distinct values (eg, 1, 2, 3 or (1, 'a'), (1, 'b'), (2, 'a'), etc.). It then assigns each distinct value a color. If the colors run out, since it is cycled, it just goes back to the first value in the palette.

We still need to deal with things like providing flexibility for sorting, or ensuring one distinct value gets a certain color, but the current implementation should meet most needs.

**Comment by euri10** [comment]
ok sounds clear enough, will try it, thanks a lot
once https://github.com/bokeh/bokeh/issues/2924 will be solved I'll have a
perfect Bar chart
amazing library thanks, I begin to love it a lot

**Comment by avishapiro** [comment]
@rothnic, @euri10 - How do I use the `color` function? Is it implemented yet? I get the error "NameError: name 'color' is not defined". Do I need an import statement? I've tried bokeh 0.10.0 and the development version. Thanks a lot!

**Comment by joshusre** [comment]
@avishapiro  - from bokeh.charts import color
