### ISSUE TITLE
HBox/hplot not working in IPython Notebook

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2350]
Related to issue #2284.

HBox/hplot doesn't appear to properly orient multiple plots (or plots and/or widgets) in the IPython notebook. This bug is not triggered in a static html output_file. There was talk in #2284 about adding a new issue, but I didn't see where anybody did it.

IPython Notebook example:
http://nbviewer.ipython.org/urls/gist.githubusercontent.com/canavandl/0a2a74764885b6b59206/raw/static_rgba_plot.ipynb

Static HTML example:
http://htmlpreview.github.io/?https://gist.githubusercontent.com/canavandl/0a2a74764885b6b59206/raw/static_rgba_plot.html

Bokeh 0.9.0

**Comment by birdsarah** [comment]
Note there is a workaround - wrap the hplot in a vplot - `show(vplot(hplot(p3, p4,)))`

**Comment by JosephCottam** [comment]
Oh...I just lost 20 minutes trying to figure out what I was doing wrong...The wrapping vplot(hplot(...)) work around still woks.

**Comment by VelizarVESSELINOV** [comment]
:+1: I also spent several minutes to found that the example hplot is not working... I hope will be fixed in the next version

**Comment by bryevdv** [comment]
@VelizarVESSELINOV the primary priority for `0.11` was the server, and secondarily, user defined models. The main focus of `0.11.1` (which will have a much shorter release cycle) is better and automated layout utilizing PhosphorJS.

**Comment by VelizarVESSELINOV** [comment]
No problem, maybe adjust the doc/examples or add a short notice that version 0.10 and 0.11 you need to do ```vplot(hplot(())``` and after 0.11.1 is fine.

My pain was to believe that in the examples and the output are correlated as the expected result of the code, so I spent time to check my code, until I copied the example and run it to see that is not working as expected in your doc.

Suggestion for further improve is to provide interactive doc jupyter so people can click and edit the examples and for you to be sure that the outputs are all the time up-to-date.

**Comment by birdsarah** [comment]
Confirm as part of #4392

**Comment by birdsarah** [comment]
This is now working. You can see it in action here: http://bokeh-cookbook.github.io/blog/2016/06/15/image_n_image_rgba_plot/

Fixed with #4343
