### ISSUE TITLE
Hovertool - How to enable hover for only certain plots in a figure?

### ISSUE THREAD

**Issue by ieatkittens** [bokeh/bokeh#2351]
I have a figure with three plots - one of which is a trendline of a median value for which I do not want hover enabled.  If I set tooltips to None for that line, however, it disables hover for all my relevant data points.

Is there a way to enable the hovertool selectively, or is it all-or-nothing?

**Comment by canavandl** [comment]
You'll want to define each plot individually, so that you can add the desired tools to each as an argument. Then you can visually group them together using a vplot or hplot

```
from bokeh.charts import Bar, output_notebook, show, vplot
from bokeh.palettes import Spectral3

output_notebook()

data = {"y": [6, 7, 2, 4, 5], "z": [1, 5, 12, 4, 2]}
cat = ['C1', 'C2', 'C3', 'D1', 'D2']

plot1 = Bar(data, cat=cat, title="Stacked example", stacked=True,
           xlabel='categories', ylabel='values', width=400, height=400, palette=Spectral3, 
           tools="hover")

plot2 = Bar(data, cat=cat, title='Unstacked example', stacked=False,
           xlabel='categories', ylabel='values', width=400, height=400, palette=Spectral3,
           tools = "pan,wheel_zoom,box_zoom,reset,resize")

show(vplot(plot1, plot2))
````

The result at nbviewer: http://nbviewer.ipython.org/urls/gist.githubusercontent.com/canavandl/0428dc20275dad80d6fb/raw/bar_example.ipynb

**Comment by ieatkittens** [comment]
Ahh - so there is no way to have a scatter with a Trendline (on the same Figure)  and only show the HoverTool for the points on the scatter?  We're trying to make some data dense reports and having one Figure that has both the Scatter and the Trendline would be ideal, but the HoverTool looks a bit messy when you mouseover the line.

**Comment by canavandl** [comment]
Ah - I misunderstood. Yes, it is possible to have the hovertool only pop up on specific plot objects. You'll have to use the bokeh.plotting api to create your scatterplot and set the "name" attribute to something. Then you'll have to create a HoverTool object (from bokeh.models) and set the "names" attribute of the hovertool to the list of names that it'll query for. Last, add the hovertool object to the "tool" attribute of your figure.

Source: http://bokeh.pydata.org/en/latest/docs/reference/models.html#bokeh.models.tools.HoverTool.names

Example:
```python
from bokeh.plotting import output_notebook, figure, show
from bokeh.models import HoverTool

output_notebook()

x = list(range(10))
y1 = [3,5,3,2,6,7,4,3,6,5]
y2 = [2,5,4,6,4,3,6,4,3,2]
y3 = [5,3,8,5,3,7,5,3,8,5]

hover = HoverTool(names=["foo", "bar"])

p = figure(plot_width=600, plot_height=300, tools=[hover,])
p.circle(x, y1, size=10, name="foo", color='red')
p.square(x, y2, size=10, name="bar", color='blue')
p.line(x=x, y=y3, color='black')
show(p)
```

**Comment by ieatkittens** [comment]
Ahh, brilliant!  That works perfectly.

**Comment by jolespin** [comment]
Is it possible to use `HoverTool` for one plot and then another dictionary for another plot? For example, if you had a network plot where you hovered over the nodes to get info about the nodes and then the connections for the weights?

**Comment by bryevdv** [comment]
Yes, you can configure separate hover tools for individual renderers:
```
r1 = p.circle(...)
r2 = p.line(...)

h1 = HoverTool(..., renderers=[r1]) # only for circles
h2 = HoverTool(..., renderers=[r2]) #only for line
```

**Comment by jolespin** [comment]
But when you use the `HoverTool` don't you give it to the tools argument in the `p = bokeh.plotting.figure` object before you can do `p.circle()` or `p.line()`?

**Comment by canavandl** [comment]
@jolespin 

you can do something like:

```
plot = figure(tools="")
circle = plot.circle(...)
line = plot.line(...)

hover = HoverTool(..., renderers=[circle]) # only for circles
plot.add_tools(hover)
```

**Comment by jolespin** [comment]
Hey thanks a  lot @canavandl .  I didn't know you could add tools that way.
