### ISSUE TITLE
Feature Request: Error Bar Plots

### ISSUE THREAD

**Issue by MaxNoe** [bokeh/bokeh#2352]
For scientists one hugely important feature would be plots with error bars und lower/upper limits like these:

http://matplotlib.org/examples/statistics/errorbar_limits.html

Also see this stackexchange question:
http://stackoverflow.com/questions/29166353/how-do-you-add-error-bars-to-bokeh-plots-in-python

**Comment by MaxNoe** [comment]
Any news on this?

**Comment by michaelaye** [comment]
:+1:

**Comment by bsipocz** [comment]
:+1:  

And thanks to @MaxNoe for the SO answer, that will do until it gets built in.

**Comment by bsipocz** [comment]
Now looking into it more closely, the SO solution is not working with interactive plots. Back to square one.

**Comment by MaxNoe** [comment]
What's the problem?

**Comment by bsipocz** [comment]
```
errorbar(pp, x='hjd', y='flux', xerr='fluxerr', source=s2)

​

source.callback = CustomJS(args=dict(s2=s2), code="""

        var inds = cb_obj.get('selected')['1d'].indices;

        var d1 = cb_obj.get('data');

​

        s2.get('data')['hjd'] = d1['hjd'][inds[0]]

        s2.get('data')['flux'] = d1['flux'][inds[0]]

        s2.get('data')['fluxerr'] = d1['fluxerr'][inds[0]]

        

        cb_obj.trigger('change');

        s2.trigger('change');

    """)



---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-524c4b97c72f> in <module>()
     30 #    pp.line(hjd[i], flux[i])
     31 
---> 32 errorbar(pp, x='hjd', y='flux', xerr='fluxerr', source=s2)
     33 
     34 source.callback = CustomJS(args=dict(s2=s2), code="""

<ipython-input-29-ce33a5d4f725> in errorbar(fig, x, y, xerr, yerr, color, source, point_kwargs, error_kwargs)
      7       x_err_y = []
      8       for px, py, err in zip(x, y, xerr):
----> 9           x_err_x.append((px - err, px + err))
     10           x_err_y.append((py, py))
     11       fig.multi_line(x_err_x, x_err_y, color=color, source=source, **error_kwargs)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

```

**Comment by MaxNoe** [comment]
You need to give it the data as something iterable.

**Comment by jacopo-chevallard** [comment]
+1

**Comment by andyfaff** [comment]
+1

**Comment by stvn66** [comment]
+1

**Comment by Apfelkuchen** [comment]
+1

**Comment by kippvs** [comment]
+1

**Comment by StevenCHowell** [comment]
@bokeh/dev, has there been consideration as to plotting errorbars?  Would this be best in `plotting.figure.errorbar`, i.e., as a glyph similar to circle?  

This method produces a nice result by wrapping existing code:
```
def errorbar(fig, x, y, xerr=None, yerr=None, color='red', 
             point_kwargs={}, error_kwargs={}):

    fig.circle(x, y, color=color, **point_kwargs)

    if xerr is not None:
        x_err_x = []
        x_err_y = []
        for px, py, err in zip(x, y, xerr):
            x_err_x.append((px - err, px + err))
            x_err_y.append((py, py))
        fig.multi_line(x_err_x, x_err_y, color=color, **error_kwargs)

    if yerr is not None:
        y_err_x = []
        y_err_y = []
        for px, py, err in zip(x, y, yerr):
            y_err_x.append((px, px))
            y_err_y.append((py - err, py + err))
        fig.multi_line(y_err_x, y_err_y, color=color, **error_kwargs)
```

I am thinking to try to implement this though it may take me a few weeks to get the time.  Please comment with any thoughts/recommendations.

**Comment by ArtyomKaltovich** [comment]
I think it should be 2 variant: user pass errors as param, and they are calculating automatically by code.

**Comment by bryevdv** [comment]
So I think there are a couple of levels here. Give +/- error values there are a variety of ways to indicate them visually:

* lines (stems) drawn between the +/- endpoints
* markers or segments (whiskers) drawn at the +/- endpoints 
* both of the above
* a filled area between the +/- sides

I think people will want all these ways, so any solution should cater to all of them.  

Given that, the first thing is that I think there is a missing useful `Annotation`, which is 

* `FilledArea`

Given two series and a dimension, (horizontal or vertical) it will draw a filled area between the two series. This differs from `PolyAnnotation` in that it specifically fills *between* two series, it's not an arbitrary polygon. It could perhaps be a subclass of `PolyAnnotation` to re-use implementation, though. This is useful on its own and could easily be a standalone PR. 

It might also make sense to have `Stem` and `Whisker` as new annotations too. Then we could have a  higher level function `bokeh.plotting.errorbars` or something that takes the `upper` and `lower` error, some visual configuration, and whatever other configuration is needed and constructs the appropriate lower level annotations to add to a plot.  

This is all very rough at the moment, though. Thoughts?

**Comment by bryevdv** [comment]
I think we'd want new `Annotations`, btw so that we could send `upper` and `lower` as actual data to BokehJS. If we do that, it opens up great possibilities with the new data spec transforms:
```
FilledArea(upper={'field': 'y':, 'transform': ADD_FIELD('upper_error')}, ...
           source=source)
```
Then (pending one open issue) if the `y` data or 'upper_error' columns were changed, everything would adjust automatically.

**Comment by bryevdv** [comment]
Lastly, I don't think at this point we should be automatically *computing* error bars. That is something for higher level facilities that are close to the original input data for an analysis to generate.

**Comment by ArtyomKaltovich** [comment]
@bryevdv 
About error computation. I think calculating standard deviation is enough. Also it is possible to pass function for error computing as a parameter. Mb this is even better: user can pass list of int (errors values) or function for error calculating.

**Comment by bryevdv** [comment]
@ArtyomKaltovich respectfully I still maintain my earlier statement. At this point, looking towards a 1.0 release, we are actively looking for ways to *shrink* the library, reduce dependencies, and present a smaller testing surface, in order to make Bokeh a rock-solid, more easily maintainable foundation for other tools to build upon at higher levels.

**Comment by ArtyomKaltovich** [comment]
Year, and than create this :)
>So I think there are a couple of levels here. Give +/- error values there are a variety of ways to indicate them visually:

>    lines (stems) drawn between the +/- endpoints
>    markers or segments (whiskers) drawn at the +/- endpoints
>    both of the above
>    a filled area between the +/- sides

Anyway, creating plots like this http://seaborn.pydata.org/_images/seaborn-barplot-1.png is important feature, and many scientists use it a lot.
So, mb it is better to add error parameter to bar() and circle() methods of figure, instead of creating separated methods.

**Comment by jbednar** [comment]
I very much agree with Bryan here -- there are lots of ways of defining
error bars, and just supporting one (e.g. stddev) is not going to be very
useful.  Bokeh is a low-level library, and it makes sense to simply pass in
the error bars lengths, computed however is appropriate for your field and
for your specific situation, and then Bokeh can handle plotting them.

Jim

**Comment by StevenCHowell** [comment]
> I don't think at this point we should be automatically computing error bars. That is something for higher level facilities that are close to the original input data for an analysis to generate.

> there are lots of ways of defining error bars, and just supporting one (e.g. stddev) is not going to be very useful

I completely agree.  There is too much misunderstanding about error estimates, particularly the difference between standard deviation and standard error of the mean.  

Automating the error calculation separates the user from the computation process, making it more likely they will not accurately represent the steps taken when presenting the data.  This would effectively move responsibility from the user to the plotting package, requiring them to lookup either in the docs or the code what they are actually representing.    

It is a simple thing for users to provide whatever error they want to show.

**Comment by michaelaye** [comment]
I second priority on user being able to pass in the errors. Much more important than any automatic calculation that just prevents the user from carefully thinking about what errors actually are.

**Comment by MaxNoe** [comment]
I also think bokeh should only do the visualisation part, not the statistics part.

**Comment by bryevdv** [comment]
I'd like to get to this in `0.12.6`. To summarize the current plan as I understand it. Three new annotations:

* `FilledArea`
* `Stem` 
* `Whisker`

**Comment by MaxNoe** [comment]
Arrows would also be great to mark upper and lower limits

**Comment by bryevdv** [comment]
Arrows already exist

**Comment by StevenCHowell** [comment]
Just to be clear, are these examples what you are referring to?
- `FilledArea`
![filled](https://www.quentinhuys.com/pictures/errorbar.jpg)
- `Stem`
![stem](http://matplotlib.org/_images/errorbar_demo2.png)
- `Whisker`
![whisker](https://root.cern.ch/root/html534/guides/users-guide/pictures/03000050.png)

**Comment by StevenCHowell** [comment]
Some considerations to keep in mind for the `Whisker` option, I have seen some plotting tools (Matplotlib or Matlab) make the Whisker width much larger when plot on a logarithmic axis.  This can obscure the data.  A simple solution is to switch to the `Stem` method of showing errorbars.  A more useful default would be that the whisker width consistently depends on the **visible axis range**.  Also, having control on the width of the whiskers (maybe as a multiplicative scale factor to the default value) could be useful.

**Comment by StevenCHowell** [comment]
In addition to being able to add errorbars to lines and scatter plots, it would be worthwhile to add them to the top (or potentially the bottom?) of vertical bar charts (or the right/left for horizontal bar charts).  This should be able to reuse most of the same code, just center the errorbars at the edge of the glyph.
![bar chart error](https://plot.ly/~PlotBot/51/control-vs-experimental.png)

**Comment by MaxNoe** [comment]
Is it possible to achieve this with the current arrow annotation?
http://matplotlib.org/_images/errorbar_limits_00.png

**Comment by StevenCHowell** [comment]
Another thing to keep in mind, related to log plots, is that when changing to a logarithmic axis, the errorbars should be rescaled to the logarithmic reference frame accordingly.  Mathematically, we scale from the `y` frame to the `y'` frame as 
```
y' = log(y) = ln(y) / ln(10)
```
Similarly, the error in `y`, we will use `dy`, is also transformed
```
dy'/dy = d/dy log(y) = d/dy ln(y) / ln(10)
dy'/dy = (1/y) / 2.303 = 0.434 / y
dy' = 0.434 dy / y
```
So instead of using `dy'`, the error should be `0.434 dy / y`.

**Comment by bryevdv** [comment]
@MaxNoe Absolutely, and with the `CustomJSTransform` in `0.12.5` you can compute the end points from the data points in the browser. 

@StevenCHowell that's roughly the breakdown, though for `Whisker` I would imagine just the whisker part, not the stem as well. 

The log considerations are important, thanks for bringing them up. It may necessary to just get a basic functionality added first and add refinements later.

**Comment by StevenCHowell** [comment]
> for Whisker I would imagine just the whisker part, not the stem as well.

Personally, I have not seen this used before (though I did find someone who [made the stems dashed](https://vaadin.com/vaadin-fw8-documentation-portlet/charts/webcomponents-api/img/charts-errorbar.png)).  @bryevdv, have you seen whiskers w/o stems much?  I wonder if the error limits could get confused as another data set or other points (though if they are close enough together in `x` it would start to look like dashed line resembling the `FilledArea` option).

FWIW, the combined whisker and stem representation was the default in Matplotlib 1.5 (2.0 dropped the whiskers) and also [Matlab](https://www.mathworks.com/help/matlab/ref/errorbar.html).  It may surprise/confuse users more familiar with the combined representation to see just whiskers, or to have to use both `Whisker` and `Stem` to get what seems a pretty standard representation.

**Comment by StevenCHowell** [comment]
Personally, I think that for most datasets the stem representation is less cluttered and sufficient. It seems others share this preference as Matplotlib changed their default.

**Comment by StevenCHowell** [comment]
To achieve 
> Mixed arrows / whiskers / stem

what would the API be like?

Would there be a unified `errorbar` method
```
p = bokeh.plotting.figure()
p.errorbar(x, y, xerr=xerr, yerr=yerr, error_style=style_array)
``` 
or would it use boolean arrays with a separate method for each errorbar type?
```
# define a mask to select how to display the errors
whisker_mask = np.array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0], dtype=bool)
arrow_mask = ~whiskers

p1 = bokeh.plotting.figure()
p1.Whiskers(x1[whisker_mask], y1[whisker_mask], yerr=yerr[whisker_mask])
p1.Arrow(x2[arrow_mask], y2[arrow_mask], yerr=yerr[arrow_mask])

p2 = bokeh.plotting.figure()
p2.line(x3, y3, y_whiskers=yerr[whisker_mask], y_arrows=[arrow_mask])
```

**Comment by StevenCHowell** [comment]
Note that to get the one directional arrows, @MaxNoe linked to, [Matplotlib uses `uplims` and `lolims` kwargs](http://matplotlib.org/examples/statistics/errorbar_limits.html).

**Comment by bryevdv** [comment]
> Personally, I have not seen this used before (though I did find someone who made the stems dashed). @bryevdv, have you seen whiskers w/o stems much? 

This concerns the set of low level models that is needed to support all the use cases. Higher level APIs could assemble them in other ways or in combination

**Comment by bryevdv** [comment]
relevant comment from another issue https://github.com/bokeh/bokeh/pull/5349#issuecomment-294331706

**Comment by StevenCHowell** [comment]
I have a colleague who just came to me trying to draw whisker errorbars.  Though somewhat of a hack, FWIW I modified the [`MultiLine](http://bokeh.pydata.org/en/latest/docs/reference/models/glyphs/multi_line.html#bokeh.models.glyphs.MultiLine.apply_theme) example to help him out.  I changed the definition of `xpts` and `ypts` using
```
h = 2.0/3
w = 1.0/3
xpts = np.array([0, w, w/2, w/2, 0, w])
ypts = np.array([0, 0, 0, h, h, h])
```
to produce this
![image](https://cloud.githubusercontent.com/assets/9484229/25149967/62a0c310-244e-11e7-94c6-c2d5ac69aa97.png)
It's a small step to customizing each one to his data.

**Comment by bryevdv** [comment]
The two merged PRs add support for an error band, and whisker style error bar annotations. I think it would still be good to add add a higher level `errorbar` function but let's leave that for a separate issue/PR.

**Comment by bsipocz** [comment]
@bryevdv @canavandl - Brilliant! I can't wait to try this out and get rid of my errorbar workarounds.

**Comment by portermahoney** [comment]
Whisker annotation works great for scatter plots.  Are there plans to get it working with vbar?

**Comment by bryevdv** [comment]
It should currently, are you saying you've tried and it doesn't?

**Comment by portermahoney** [comment]
Sorry, my mistake.  It does work!  Here's an example of scatter and vbar, incase it helps anyone else.  Thanks!

`x = [1,2,3,4,5]
        y = [6,7,2,4,5]
        p = figure(title='test', x_axis_label = 'x', y_axis_label = 'y')
        p.circle(x, y, size=10, color="red", legend='Temp.', alpha=0.5)
        base = x
        upper = [7,7.1,3,4.5,5.5]
        lower = [2,2,2,2,2]
        errors = ColumnDataSource(data=dict(base=base, lower=lower, upper=upper))
        p.add_layout(Whisker(source=errors, base='base', upper='upper',
        lower='lower'))

        bar_test = figure(title='test')
        bar_test.vbar(x = x, width = 0.5, top = y)
        bar_test.add_layout(Whisker(source = errors, base = 'base',
        upper = 'upper', lower = 'lower'))`

**Comment by bryevdv** [comment]
Great! :)

**Comment by varchasgopalaswamy** [comment]
Since interactive legends (on-click hide policy) work on an on-glyph basis,trying to hide scatter plots with whiskers on them don't work as expected - the scatter glyphs are hidden, but the whiskers remain. Is there a  way to create a glyph that combines both the marker and the whiskers into a single super-glyph?

**Comment by mattpap** [comment]
> Is there a way to create a glyph that combines both the marker and the whiskers into a single super-glyph?

No. There's an open issue for that (#177). However, this wouldn't work anyway, because whiskers are annotations, and those are governed by a separate set of rules. If whiskers were glyphs, this would work right now without compound glyphs, you would just need to add whisker glyph to legend's renderers set.

There are two things that could happen here. Either we can add a special case for annotations in legend (relax type constraint on `LegendItem.renderers`). Or we could rethink what is an annotation and what is not (another example is arrows which make sense in both setups, and not having arrow glyphs prohibit certain kinds of plots).

**Comment by JorisMeertBambrugge** [comment]
> > Is there a way to create a glyph that combines both the marker and the whiskers into a single super-glyph?
> 
> No. There's an open issue for that (#177). However, this wouldn't work anyway, because whiskers are annotations, and those are governed by a separate set of rules. If whiskers were glyphs, this would work right now without compound glyphs, you would just need to add whisker glyph to legend's renderers set.
> 
> There are two things that could happen here. Either we can add a special case for annotations in legend (relax type constraint on `LegendItem.renderers`). Or we could rethink what is an annotation and what is not (another example is arrows which make sense in both setups, and not having arrow glyphs prohibit certain kinds of plots).

Meanwhile, it there already a solution? Something like a Whisker-glyph? Thx

**Comment by maxnoe** [comment]
Yes, whiskers where introduced. See the original stackoverflow question:

https://stackoverflow.com/questions/46507628/adding-error-bars-on-top-of-bar-charts-in-bokeh/46517148#46517148

**Comment by JorisMeertBambrugge** [comment]
i understood from mattpap's explanation those aren't glyps but annotations. They don't work  together with dynamic legends like explained by varchasgopalaswamy? Or is there meanwhile a way to attach annotations to a legend item?

**Comment by bryevdv** [comment]
> Or is there meanwhile a way to attach annotations to a legend item? 

There is not.
