### ISSUE TITLE
Add support for `styles` in google map `map_options`

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#2354]
To add a lot of flexibility to the presentation of google maps, it would be nice to support the [styles](https://developers.google.com/maps/documentation/javascript/reference) property in map_options, which is simply some style json (see examples [here](https://snazzymaps.com/explore).  

I may be wrong but this could be a simple fix that checks [here](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/gmap_plot.coffee#L70) to see if anything is set for `styles` and if so, make it part of the map options.  I don't know how or if you'd expose it at this point in the python api, but it'd be nice for properties like this to be able to be passed on to the map call.

**Comment by bryevdv** [comment]
@hafen that would be really cool. I think the simplest route would be a property like
```
    styles = String(help='''docs''')
```
with the understanding that string contains valid JSON. A better solution would involve creating a new `JSON` property:
```
    styles = JSON(help='''docs''')
```
that can validate the supplied text as JSON, and perhaps try to auto-convert to JSON if passed something other than a string.

**Comment by hafen** [comment]
Yes actually a string would be very simple and would probably be the way people would want to specify it if they are building or grabbing styles from sites like snazzymaps.  I'd try a PR but it wouldn't be for at least a few weeks thanks to travel followed by travel followed by travel.

**Comment by bryevdv** [comment]
beat you to it @hafen :)

**Comment by hafen** [comment]
Hey awesome! :)  Thanks.
