### ISSUE TITLE
CrosshairTool lacks "dimension" property

### ISSUE THREAD

**Issue by schaunwheeler** [bokeh/bokeh#2357]
The doc strings for CrosshairTool say: "The crosshair tool draws a crosshair annotation over the plot, centered on the current mouse position. The crosshair tool may be configured to draw across only one dimension by setting the ``dimension`` property to only ``width`` or ``height``."

However, the actual CrosshairTool object lacks a "dimension" property, and attempting to set that property results in "AttributeError: unexpected attribute 'dimension' to CrosshairTool, possible attributes are name, plot, session or tags"

**Comment by schaunwheeler** [comment]
I just realized that this is simply a matter of inserting something like this into tools.py:

> dimensions = List(Enum(Dimension), default=["width", "height"], help="""
>     Which dimensions the crosshair tool is to track. By default,
>    the tool will draw crosshairs across both vertical and horizontal 
>     dimensions. If only "width" is supplied, only a horizontal line will
>     be drawn; If only “height” is supplied, only a vertical line will be 
>     drawn.
>     """)


How do you normally handle these kind of one-liner changes? Do you want me to do a full fork and pull request?

**Comment by bryevdv** [comment]
Hey @schaunwheeler small PR's a perfectly fine, and generally PR's are preferred. If you are *asking* for suggestions for how to make a more substantial PR :) Then this change could be accompanied by some User's Guide documentation support here: 

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/tools.rst

would certainly be welcome. But a PR with just this fix would also be accepted.
