### ISSUE TITLE
Animated line and animated glyph gallery examples are broken

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2359]
The animated line and animated glyph (server examples) in the gallery are static (not animating). I assume it's related to a problem with the bokeh server that updates the plots.

animated line:
http://bokeh.pydata.org/en/latest/docs/server_gallery/aw_animate.html

animated glyph:
http://bokeh.pydata.org/en/latest/docs/server_gallery/aw_animate.html

**Comment by bryevdv** [comment]
Need to add DO creds to pass wallet

**Comment by damianavila** [comment]
This is fixed... so I will close this one.
btw, @bryevdv, did you add the creds to the wallet?
