### ISSUE TITLE
clarify Resources for flask embed examples 

### ISSUE THREAD

**Issue by arsenovic** [bokeh/bokeh#2363]
i have seen the docs  on the [embed](https://github.com/bokeh/bokeh/tree/master/examples/embed) module, which are great.  however, it is unclear to me the best way to handle bokeh's `Resources` for either inline or CDN embedded plots in flask.  it seems that the resources should go in a template,  or someplace that is re-used as opposed to  passing plot_resources through every `render_template` call.

could you describe the best way to do this?

**Comment by birdsarah** [comment]
I'm not sure if I'm answering the question, but if I'm embedding a bokeh
plot in a web page, I just use bokeh.embed.components (
http://bokeh.pydata.org/en/latest/docs/reference/resources_embedding.html#bokeh.embed.components)
which returns the script and div tag.

I then manually put the bokeh js and any css I require in my app as
appropriate.

**Comment by arsenovic** [comment]
ok, perhaps i am messing up something simple.  if i pass the `script` and `div` from the output of  `components()` to the following  template, i get nothing. 

```
{% block styles %}
 {{ super()}}
 <link
    href="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.css"
    rel="stylesheet" type="text/css">
{% endblock styles %}


{% block scripts %}
 <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.js">
 {{ script|safe }}
{% endblock scripts %}
```

i am using (Flask-Bootstrap)[http://pythonhosted.org/Flask-Bootstrap/basic-usage.html#sample-application]  for the base templates.  

am i putting these in the wrong place?

**Comment by birdsarah** [comment]
Where's the div?

What does the actual source of the page you've produced look like - can you
stick it in a gist or pastebin?

**Comment by arsenovic** [comment]
https://gist.github.com/arsenovic/8a8a576e97c231169e17

**Comment by birdsarah** [comment]
You have a typo:
https://gist.github.com/arsenovic/8a8a576e97c231169e17#file-bokehembed-L51
needs a closing </script>

**Comment by birdsarah** [comment]
sorry I didn't notice this from the code snippet you posted before, took me a while to spot it when it was running in my browser.

**Comment by arsenovic** [comment]
!!!!!!!!!!!!!!!

thanks sorry for the noise
