### ISSUE TITLE
compat/seaborn/sinerror.py is broken

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#2365]
Really weird because seems to work before the last release and it is not working now...

Something interesting to mention... sometimes it appears OK, seems to be a random factor involved in some way...

![sin](https://cloud.githubusercontent.com/assets/1640669/7997874/759bb452-0b0a-11e5-8627-a4143a11922c.png)

**Comment by damianavila** [comment]
There is no traceback in the python or the js side...
pinging @bokeh/core for ideas... :wink:

**Comment by bryevdv** [comment]
Pretty sure it has to do with lack of control over glyph rendering order

**Comment by bryevdv** [comment]
There still seem to be issues here. Somehow the render order is still not being controlled. I wonder if this is on the python side tho. For reference, here are two screen caps of the violin plot taken one after the other:
![screen shot 2015-06-27 at 9 41 03 am](https://cloud.githubusercontent.com/assets/1078448/8392442/d1252486-1cb0-11e5-8bfb-8d46a7e1f15b.png)

![screen shot 2015-06-27 at 9 40 54 am](https://cloud.githubusercontent.com/assets/1078448/8392445/d43adb70-1cb0-11e5-8973-b3046916df7f.png)

@damianavila is it possible there is some indeterminacy in the order that renderers are generated  by `mplexporer` or `mpl.to_bokeh`?

**Comment by bryevdv** [comment]
As an aside it would be nice if the outlines could be handled by the patches glyph itself, but I am guessing thesis a result of how sns/mpl do things

**Comment by bryevdv** [comment]
Here's another one I haven't seen before
![screen shot 2015-06-27 at 9 52 49 am](https://cloud.githubusercontent.com/assets/1078448/8392488/50d13c8c-1cb2-11e5-8aba-3936f8bf2b6b.png)

**Comment by bryevdv** [comment]
@damianavila @fpliger @canavandl no the problem is that we are constructing uneven column data sources:
```
In [28]: print([len(x) for x in p.select(ColumnDataSource)[0].data.values()])
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 31, 2, 100, 31, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 100, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
```

**Comment by bryevdv** [comment]
I'm not sure if this is the same problem affecting the violin plot or not.

**Comment by damianavila** [comment]
>  uneven column data sources

We need to validate this... and I see you opened a PR on this matter, thanks!

> I'm not sure if this is the same problem affecting the violin plot or not.

It could be, we need to investigate on this side...

**Comment by bryevdv** [comment]
seaborn 0.6 changed the violin plot quite a bit, to the point that we can basically no longer process them. I think we well need a pretty thorough review of our MPL compat soon, possibly choosing some features to try and commit back to `mplexporter`.

**Comment by damianavila** [comment]
> I think we well need a pretty thorough review of our MPL compat soon, possibly choosing some features to try and commit back to mplexporter.

Yes, I agree...

**Comment by bryevdv** [comment]
@mattpap currently seaborn examples are rendering as (well as can be) expected. Can you comment on the re-open?

**Comment by bryevdv** [comment]
@mattpap I believe this issue is closed / was re-opened in error. I ran all the examples under consideration and could not reproduce any problems. Please re-open with details if there is a way to reproduce some problem (or open a new issue)
