### ISSUE TITLE
Patches doesn't render with reversed ranges

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2366]
See last chart on:

http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/notebooks/Patch%20%26%20Patches.ipynb

**Comment by birdsarah** [comment]
(tried on confirmed on 0.9 and 0.9.1-dev)

**Comment by jakirkham** [comment]
+1 Have seen this exact same problem and was wondering if I was doing something wrong. Reassured to see someone else had the same problem.
