### ISSUE TITLE
Minor Grid Lines

### ISSUE THREAD

**Issue by Lijantropique** [bokeh/bokeh#2368]
To enhance presentation it would be nice to have any tool to adjust minor grids. For example to go from:

![k1](https://cloud.githubusercontent.com/assets/5657134/8019834/acef52ac-0c30-11e5-895c-cfcacafd3cd4.png)

 to something like this one:

![k1_original](https://cloud.githubusercontent.com/assets/5657134/8019835/b1c64470-0c30-11e5-8c63-2625810bf1dd.png)

thanks a lot

**Comment by cstjean** [comment]
I would like to be able to specify where the gridlines are (eg. like in the above figure, "I want gridlines at x=[2, 3, 4, 5]"). I thought that this is what was asked in the question, and if so, it is not answered by the merged commit above.

**Comment by bryevdv** [comment]
My understanding was a request to be able to have minor grid lines turned on at all (which was not possible before). Any additional customization would be a new feature request (please open a new issue).

**Comment by bahkadypak** [comment]
The feature will allow not only look at pretty pix, but actually read values from it. Will be very useful from my pov.
