### ISSUE TITLE
JS build docs slightly broken

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#2369]
Right now the docs at http://bokeh.pydata.org/en/latest/docs/dev_guide/building.html#building-bokehjs-with-gulp instruct users to do:

    conda install -c javascript gulp

However, with conda 3.13.0 right now, doing this results in a 401 Unauthorized error:

    Fetching package metadata: ....Error: HTTPError: 401 Client Error: UNAUTHORIZED: https://conda.binstar.org/javascript/noarch/

The following command works, however:

    conda install -c https://conda.binstar.org/javascript gulp

**Comment by bryevdv** [comment]
This has always worked. Why doesn't this work now?

**Comment by pzwang** [comment]
I don't know.  This is with the latest version of conda.  Can you confirm it works for you?  I know that some things have been changing with binstar.org/anaconda.org, so maybe something's going on with their SSL certs?

**Comment by bryevdv** [comment]
Working fine for me atm:
```
bryan@0199-bryanv (git:master) ~/work/bokeh $ conda install -c javascript gulp
Fetching package metadata: ................
Solving package specifications: .
Package plan for installation in environment /Users/bryan/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    iojs-1.2.0                 |                1         5.5 MB

The following packages will be UPDATED:

    iojs: 1.2.0-0 --> 1.2.0-1

Proceed ([y]/n)? 

Fetching packages ...
iojs-1.2.0-1.t 100% |####################################################################################################################################################################| Time: 0:00:00   5.91 MB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#######################################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#######################################################################################################################################################################################| 100%
bryan@0199-bryanv (git:master) ~/work/bokeh $ conda update conda
Fetching package metadata: ..............
# All requested packages already installed.
# packages in environment at /Users/bryan/anaconda:
#
conda                     3.13.0                   py34_0  
bryan@0199-bryanv (git:master) ~/work/bokeh $ 
```

```
bryan@0199-bryanv (git:master) ~/work/bokeh $ conda --version
conda 3.13.0
```

**Comment by Maggie-M** [comment]
I seem to be having the same issue Peter's having, as well.

**Comment by bryevdv** [comment]
We should ping the conda/anaconda.org team and find out whether this is still supposed to work or not.

**Comment by srossross** [comment]
@pzwang, this is due to your binstar login being expired.

`conda` transforms the `-c javascript` into -c `https://conda.binstar.org/t/<BINSTAR-TOKEN>/javascript` 

This error could be be gracefully handled by conda.  See conda/conda#1233

To fix this in the short term you should be able to run `binstar login`

**Comment by Maggie-M** [comment]
I logged out, then back into binstar, and it's still hanging for me at the "fetching package metadata...." part.

I only have the two standard channels in my .condarc, so I can at least eliminate that as a possibility.
