### ISSUE TITLE
[bug] CrosshairTool missing dimension property

### ISSUE THREAD

**Issue by pank** [bokeh/bokeh#2370]
Hi,

the `CrosshairTool` class in `models/tools.py` is missing the `dimension` property.

You can add this to the class, and it works:
```
    dimensions = List(Enum(Dimension), default=["width", "height"], help=""" 
    Which dimensions the CrosshairTool moves in. By default, a cross
    is used. If only "width" is supplied, the crosshair will be
    constrained to span the entire vertical space of the plot. If only
    "height" is supplied, the crosshair will be constrained to span
    the entire horizontal space of the plot""")
```

Thanks,
Rasmus

**Comment by bryevdv** [comment]
This was fixed in https://github.com/bokeh/bokeh/pull/2360

**Comment by pank** [comment]
Bryan Van de Ven <notifications@github.com> writes:

> This was fixed in https://github.com/bokeh/bokeh/pull/2360

Ups.  Sorry for the noise!  Great project BTW!

**Comment by bryevdv** [comment]
no problem :) thanks!
