### ISSUE TITLE
bokeh.charts.Donut has hard dependency on pandas

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2373]
On creating a new conda environment to serve a flask app/embedded bokeh plot, I get an ImportError by trying to import anything from bokeh.charts (the app uses Line charts). It appears that ../builder/donut_builder.py has a hard dependency on pandas.

**Comment by damianavila** [comment]
This is linked with this issue: https://github.com/bokeh/bokeh/issues/1491

**Comment by fpliger** [comment]
I'd close this since we have already decided that pandas dependency is an acceptable dependency. @bokeh/core thoughts?

**Comment by damianavila** [comment]
>@bokeh/core thoughts?

I agree...

**Comment by mattpap** [comment]
As long as I can import everything but `bokeh.charts` without installing `pandas`, then sure. This kind of dependency is acceptable in an optional module. However, there are still questions to answer:

1. Do we test if basic bokeh's functionality work in a clean environment?
2. How to tell the user about this dependency? Typical approaches are to install all dependencies or none (and let user trial and error). If I was creating a (gentoo) portage package for bokeh, I would add a `charts` "use flag", that would imply adding `pandas` as a dependency. Can we do something like this with conda? I know there are "features", but I'm not sure this was meant to be used the same way as use flags in portage.

**Comment by bryevdv** [comment]
We have facilities now to print informative errors about optional dependencies, and it has also been mentioned in the docs.
