### ISSUE TITLE
Allow more subtle uses of Resources - provide lower-level JSResource & CSSResource.

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2375]
[bokeh.embed.file_html] (https://github.com/bokeh/bokeh/blob/master/bokeh/embed.py#L110) is pretty flexible as it allows you to parse in your own template. 

If plot_resources was handled a little differently it could provide a lot more flexibility.

I personally don't see a reason to always be lumping the JS and the CSS together. It seems to me that a lower level JSResource and a CSSResource, which Resources, is a wrapper around would allow a lot more flexibility.

For me, I always need the whole JS library. But I can easily use a fraction of the CSS.

**Comment by damianavila** [comment]
This request some sensible to me...
