### ISSUE TITLE
Make widgets proportional to plots

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2377]
This is a tricky one, but the widgets, e.g. slider, are proportional to the div their in and not the plot they're under or next to.

This can make out of the box design a little ugly.

Probably need a design default weigh in on this before implementing....also need to think through the various different combinations.

**Comment by bryevdv** [comment]
@birdsarah I am closing because I believe this is covered by other issues and the current layout work. Please re-open if you disagree.
