### ISSUE TITLE
Using np.NAN as seperator makes data serialization rough

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2380]
If you've mangled your data (in my case geo data) into the xs and ys that bokeh wants, with the required np.NAN as the seperator then you can't store that df as a csv or json as the np.NAN won't get handled right on the way back in. hdf works fine but has extra dependencies.

**Comment by birdsarah** [comment]
@bokeh/dev - any thoughts on this.

**Comment by mistakevin** [comment]
We can encode the backend `NaN` type to an `None` type instead, as that will translate to `null` when encoded. Or we could decode the json on the front end to translate `'NaN'` to the `null` object, but that might be a little expensive with big data sets.

**Comment by bryevdv** [comment]
So we will have to investigate. All the numeric columns of data go into typed arrays. The choice of `NaN` was probably to support putting all the data for "multi patches" in one typed array, to avoid having to create and deal with multiple typed arrays. So that does not mean we have to encode it as `NaN` on the front end where users see it, but we may be stuck with it inside BokehJS.

**Comment by birdsarah** [comment]
sort-of related is #737 discussing the use of NaN's to be multi-element seperators.

**Comment by bryevdv** [comment]
@birdsarah recent consensus as I understand it would have improvements in a separate `bokeh.geo` at some point, so closing (but please re-open if I am mistaken)

**Comment by birdsarah** [comment]
I just had this on a recent project. If we intend to continue supporting Patches and MultiLine which have meaningful NaNs in them this remains an issue.

**Comment by bigreddot** [comment]
What should otherwise happen when patches data has `NaNs`? What should get drawn when a single patch has "meaningful nans" in it?

**Comment by birdsarah** [comment]
I don't understand these questions at all.

I didn't think Patch supports NaNs. 

Also @bigreddot - is that you @bryevdv?

**Comment by bryevdv** [comment]
Yes, I had to make a new account to avoid sharing private repos with a client when using their GH integration. I thought this issue was about finding another representation that did not involve nans for the protocol

**Comment by birdsarah** [comment]
This issue could be re-written as the following use case which I have not been able to figure out.

1) Generate Patches data in a Pandas DataFrame - happily plot it with Bokeh
2) Save that DataFrame to CSV or JSON using df.to_csv() or df.to_json()
At a future time:
3) Read in the CSV or JSON using pd.read_csv() pd.read_json()
4) Use the same plotting code to plot the data from the "reconstituted" dataframe

I can't get this to work due to saving of np.NaN.

**Comment by bryevdv** [comment]
I understand now, thanks.

**Comment by bryevdv** [comment]
Now that numpy arrays are serialized using an encoding, nan's are no longer an issue. accordingly, closing this discussion.
