### ISSUE TITLE
Examples tests dependencies

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2385]
Just checking I'm write on this before I do a small documentation PR. Running all the tests via `nosetests` and get the failures: 

````
Shutting down ipython-notebook ...
[FAIL] FIX FAILURES AND RUN AGAIN
[FAIL]  /home/bird/Dev/birdsarah/bokeh/examples/compat/ggplot/density.py
[FAIL]  /home/bird/Dev/birdsarah/bokeh/examples/compat/ggplot/line.py
[FAIL]  /home/bird/Dev/birdsarah/bokeh/examples/compat/ggplot/step.py
[FAIL]  /home/bird/Dev/birdsarah/bokeh/examples/compat/ggplot/xkcd_density.py
[FAIL]  /home/bird/Dev/birdsarah/bokeh/examples/glyphs/calendars.py
[FAIL]  /home/bird/Dev/birdsarah/bokeh/examples/plotting/file/hover.py
[FAIL]  /home/bird/Dev/birdsarah/bokeh/examples/plotting/file/les_mis.py
```
The first 4 are ggplot dependency, and the next is icalendar dependency.

The last two just didn't load - not sure why.

**Comment by damianavila** [comment]
The last two are working for me from master... can you try cleaning your cache or open in privata/incognito mode?

**Comment by birdsarah** [comment]
Hi, they work for me too. They just didn't run in the tests. I ran them manually, they ran, and then I ran the tests again and the tests passed.

**Comment by birdsarah** [comment]
Should we add a note about examples dependencies in the dev docs?

**Comment by damianavila** [comment]
yes... you have this info available here: https://github.com/bokeh/bokeh/wiki/BEP-2:-Release-Management#pre-release-testing-check-list, but we should put it in the dev docs too...

**Comment by birdsarah** [comment]
Superseded by other discussions on dev setup like #2463.
