### ISSUE TITLE
Simple bokeh embed example

### ISSUE THREAD

**Issue by bonaime** [bokeh/bokeh#2387]
Hi,

I would like to embed bokeh in a simple html file. Here is my code:
````
#!/usr/bin/python

from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import components
from bokeh.templates import AUTOLOAD

AUTOLOAD
plot = figure()
plot.circle([1,2], [3,4])


script, div = components(plot, CDN)

print 'Content-type:text/html \n'

print '<!DOCTYPE html><html>'
print '<head>'
print script
print '</head>'

print '<body><h1>Test</h1>'


print div
print '</body></html>'
````

I think the problem is that  BokehJS is not loaded. But how can I do that ?

Thank you

**Comment by birdsarah** [comment]
I just submitted a PR that does this: http://nbviewer.ipython.org/github/birdsarah/bokeh/blob/gapminder_animated_bubble_example/examples/glyphs/animated_bubble/Gapminder%20-%20animated%20bubble%20plot.ipynb

You can see in the html template here: https://github.com/birdsarah/bokeh/blob/gapminder_animated_bubble_example/examples/glyphs/animated_bubble/gapminder_template.jade

In particular
- see [line 28](https://github.com/birdsarah/bokeh/blob/gapminder_animated_bubble_example/examples/glyphs/animated_bubble/gapminder_template.jade#L28) for how I load bokeh.min.js - you may well want to use the CDN link: http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.js

- and [line 6](https://github.com/birdsarah/bokeh/blob/gapminder_animated_bubble_example/examples/glyphs/animated_bubble/gapminder_template.jade#L6) where I load the CSS. Again, you may want to use the CDN css: http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.css

I have a preference for JS at the bottom of my html page - you don't have to do this. You just have to make sure it's inserted before the script tag that you got from calling `components.`

**Comment by bryevdv** [comment]
I think this has been answered / support should be directed to Mailing List

**Comment by mgrollins** [comment]
Here is a link to an example use of a template to embed a Bokeh plot in the latest stable release.This template is a jinja2 template, while above a jade template is referenced. I believe it is the same example though.
https://github.com/bokeh/bokeh/blob/0.10.0/examples/interactions/interactive_bubble/gapminder_template.jinja
