### ISSUE TITLE
scatter overwrites size column in CoumnDataSource

### ISSUE THREAD

**Issue by dwiel** [bokeh/bokeh#2388]
```
import numpy as np
import bokeh.plotting as plt
plt.output_notebook()

source = plt.ColumnDataSource(
    data=dict(
        a = [1,2,3,4,5],
        b = [1,2,3,4,5],
        c = np.array([0,10,20,30,40]),
        size = [True, False, True, False, True],
    )
)

print source.data['size']

fig = plt.figure()
fig.scatter('a', 'b', source=source, size=((source.data['c']+10)/5))
plt.show(fig)

print source.data['size']
```
Running the above results in the correct plot, but an altered value for the size column.  I wouldn't expect that rendering a scatter would overwrite my data in the datasource. stdout:
```
[True, False, True, False, True]
[ 2  4  6  8 10]
```
Also, this is especially troublesome when you want to use the same data source in multiple scatters but with different custom sizes.  The result is that the size data passed in to the scatter created last is used for all scatters since they are all trying to store their custom size array into the same 'size' column in the datasource.

**Comment by bryevdv** [comment]
@dwiel you can pass a column name for the size parameter:
```
fig1.scatter('a', 'b', source=source, size='size1')
fig2.scatter('a', 'b', source=source, size='size2')
```
where you have columns in `source` named `size1` and `size2`. 

That said, Bokeh should probably throw a `RuntimeError` if you try to pass in a literal array (which is automatically and implicitly put in a column of the same name) and the column with that name already exists.

**Comment by dwiel** [comment]
That definitely works around the problem, but it is still a bit un-intuitive to be required to do this:

```
source['size1'] = source['a'] > 1
fig1.scatter('a', 'b', source=source, size='size1')
source['size2'] = source['b'] > 1
fig2.scatter('a', 'b', source=source, size='size2')
```

vs

```
fig1.scatter('a', 'b', source=source, size=source['a'] > 1)
fig2.scatter('a', 'b', source=source, size=source['b'] > 1)
```

That said, throwing a `RuntimeError` definitely seems like a minimal solution to at least not cause unexpected behavior.

**Comment by bryevdv** [comment]
Unless I am misunderstanding the code above, technically the above is an error, and I would expect to see a validation warning. One of the assumption of `ColumnDataSource` is that all the columns are the same length, it's basically a cheap approximation to a `DataFrame`.

Regarding the unintuitive-ness, it's a trade-off, as always. When you pass a literal array, we have to manufacture a column in a column data source for you. We could certainly invent some random name for that synthetic column, but it's extremely useful to have a known, predictable name for the column (so it can be reliably referred to in callbacks or other places). Arguably, that's a much more important and common use case.

**Comment by dwiel** [comment]
yeah I definitely understand why it is the way it is.  I think the `RuntimeError` instead of overwriting existing data is probably a good middle ground.  I am having a hard time thinking of a case when you would actually want the scatter call to update an existing size ...

btw, I updated the example to be `* 10` instead of `> 1`, makes more sense, thanks.

**Comment by bryevdv** [comment]
Yes, that should be fine. :) 

I do want to implement the `RuntimeError` solution, But I wanted to search existing issues first. There is indeed already an issue: #2056 and there was a tentative PR at one point but it will need to be resurrected or redone (I don't recall why the PR was closed)

Closing this comment just because I don't think there is much else to add, but please re-open if there is more to discuss.

**Comment by bryevdv** [comment]
I should note the proposed solution there is a bit more strict, it basically disallows modifying a passed-in source in any way (even adding new columns that don't already exist), not just failing when an existing column would be overwritten. I think that rule is probably simpler and easier to reason about.

**Comment by dwiel** [comment]
cool thanks for improving bokeh!
