### ISSUE TITLE
Tools seems to be broken in latest version of chrome and chromium

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#2396]
Chromium version: Version 43.0.2357.81 Ubuntu 15.04 (64-bit)
Chrome version: Version 43.0.2357.125 (64-bit)

JSconsole: Nothing weird
Bokeh version: 0.9.0

Video of the behavior: https://www.flowdock.com/app/continuum/bokeh/threads/KCV-YFso9Pcy7KQju9dEmRYJ5VA

Only pan a wheel zoom works... any or the other does not seems to be selected...

I guess the first step is somebody else to try it with the same browser versions...

@bryevdv @birdsarah @fpliger

**Comment by mcneillj** [comment]
Nothing appears on the screen for me except for a hyperlink named "link" in Chrome.

Google Chrome: Version 43.0.2357.124 m (64-bit)
Bokeh version: 0.9.0

Works in Internet Explorer 11.0.09600.17843

**Comment by birdsarah** [comment]
I'm just uploading a video, but I now have Chrome - Version 43.0.2357.81 (64-bit) on Ubuntu 14.04 and it works fine.

chromium 41.0.2272.76 Ubuntu 14.04 (64-bit) is the same (also working)

**Comment by birdsarah** [comment]
https://www.youtube.com/watch?v=xBy8_eWd7OI

**Comment by damianavila** [comment]
Well, this is really weird... where could be the issue?? I don't think it is related with 15.04 or my desktop choice (gnome-shell), but I wondering if there is some issue there... I guess I should try other things to confirm...

**Comment by damianavila** [comment]
I tried with unity too and still I see the issue...

**Comment by damianavila** [comment]
OK.... that's really strange... but the issue seems the following... my laptop have touchscreen and for some reason (I don't know why) the tools are working if I touch my screen but not with the mouse... So, maybe chrome/ium is setting some flag when detect the touchscreen and disable the mouse event... that really interesting... and weird

**Comment by damianavila** [comment]
video or it did not happen... https://youtu.be/-9tnR2VZnkw

**Comment by damianavila** [comment]
OK, going to 
```
chrome://flags/#touch-events
```
and disable it... and it is working now... wow... this take me hours to figured out!!!

**Comment by almarklein** [comment]
Is there something we can do in Bokeh to prevent this? There's bound to be users who would have the same problem.

**Comment by bryevdv** [comment]
I'm sure it's platform/browser specific. Devices capable of mixed mode inputs are only going to become more common, so it's definitely worth investigating. I don't personally have access to such a device though, so it's a bit difficult.

**Comment by damianavila** [comment]
Docs will be added in #2481

**Comment by jsignell** [comment]
Why in other browsers can you use touch or mouse and in Chrome you have to choose?

**Comment by bryevdv** [comment]
Is this in regards to a touch enabled laptop? (I can't tell from your description) If so its probably partially because we don't actually have any hardware to test on, and also because at least in the past the library we use to UI events required a choice. Can you be more specific about what is happening vs what you expect to happen?

**Comment by jsignell** [comment]
Yeah I was having the same issue that damianavila was talking about where on Chrome on my touch enabled laptop, the plots only respond to touch. But on other browsers (firefox, edge) the plots respond to either touch or mouse without me going and disabling settings. This is not pressing, but it just seems odd and I wanted to bring your attention to it.

**Comment by damianavila** [comment]
@jsignell is the disable option I recommended in the docs working for you? Can you tell me with version of Chrome/ium you have? Thanks!

**Comment by jsignell** [comment]
@damianavila I am using 48.0.2564.48 and the disable option worked fine. I was just wondering why it was necessary at all, since the other browsers seemed fine using either input.

**Comment by damianavila** [comment]
This is something specific from the Chrome/ium side... they usually enable some flags by "default" whereas they are experimenting in their development road map... in this specific case, they are trying to be too smart with touch events, and this is causing issues only in specific situations. Not sure if we can provide a better solution that just the doc recommendation about the issue as we did it.

**Comment by jdugge** [comment]
I don't think this should be considered closed: telling users that they need to disable touch events in order to interact with Bokeh plots is not really an option, especially since things like [plotly.js](https://plot.ly/python/line-charts/) don't have the same problem.

You can test the behaviour without access to a touch-enabled device by setting chrome://flags/#touch-events to Activated: you won't be able to activate any of the tools.

Could this issue be reopened?

**Comment by jdugge** [comment]
Adding to the last comment: You can test the touch behaviour in Chrome using [Touch Emulation in Device Mode](https://developer.chrome.com/devtools/docs/device-mode#touch-emulation).

**Comment by jdugge** [comment]
Issue is being discussed at #1848
