### ISSUE TITLE
ipython complete kwargs on add_glyph

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2397]
This is a pretty minor annoyance, but as I know some work was done on this lately I thought I'd raise it.

If you're doing `plot.add_gyph(` there are kwargs like `selection_glyph` and `nonselection_glyph` which I'd like to be able to tab complete but they don't come up in ipython for me.

**Comment by bryevdv** [comment]
I don't know how to do this, and there has not been any other comment in ~3 years
