### ISSUE TITLE
standardize callback interface with args

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2412]
ref discussion in PR #2386 and issue #2346 in general

In bokeh/bokehjs/src/coffee/action/callback.coffee the Callback.execute method naively passes whatever object that it receives as the cb_obj. The intention is to pass back the object that the callback is defined on, but sometimes this information is insufficient (i.e. in HoverTool events where the mouse coordinates is relevant). This results in the creation of non-standard cb_obj 's that are confusing for the user.

Proposed is the form:

execute(cb_obj, cb_data)

Where cb_obj is always the object that the callback is defined on, and cb_data is any (optional) additional data (like all the mouse coords, etc. here).

**Comment by canavandl** [comment]
Other than HoverTool events over multiple, stacked glyphs, are there situations where it'd be helpful to have callbacks that pass multiple cb_objs?

i.e. should we use the below form?

execute([cb_objs], cb_data)

**Comment by bryevdv** [comment]
I think anything like that could just go in `cb_data`, personally. I like keeping `cb_obj` to on unambiguous meaning (`@`, the current object that triggered the callback) and putting anything else in `cb_data` as needed. Making it `[cb_objs]` would also add small complications/overhead to the JS code in all cases.
