### ISSUE TITLE
Tap / Hover tool doesn't work with circle with radius sometimes with datetime axis.

### ISSUE THREAD

**Issue by colinfang** [bokeh/bokeh#2417]
See [notebook](http://nbviewer.ipython.org/gist/colinfang/62431f9245cf311904e8)

Basically, If I use Circle with `radius`, the tapping doesn't work. But it works with `size`.

I believe it is due to the unit of radius as in my test some range of x-axis works, and others don't. It is strange since `radius_dimension = y` in my case.

**Comment by bryevdv** [comment]
Seems to be some actual bugs here

**Comment by bryevdv** [comment]
There has not been any additional comment on this in ~5 years so I am going to close. Realistically, I do not think circles with a *radius* make sense on datetime axes, because the aspect ratios are so very drastically mismatched.
