### ISSUE TITLE
Plotting large data.

### ISSUE THREAD

**Issue by waqarmalik** [bokeh/bokeh#2423]
Is there a limit on the data size bokeh will try to plot?

Please use the file at https://www.dropbox.com/s/woj8l1hwldavyxu/test.csv.zip?dl=0
I am able to plot this using other tools, but bokeh refuses to plot it using the following

```python
import pandas as pd

import bokeh.plotting as plt

server = 'http://127.0.0.1:5006'


df = pd.read_csv('test.csv')
df2 = df.iloc[1:100, :] # Note I'm able to plot a subset.

plt.output_server('fig', url=server)
fig = plt.figure(title='A vs B', width=500, height=500, logo=None) 
fig.scatter(df.b, df.a, color='blue', fill_alpha=0.2, size=5, legend='Test set')
plt.show(fig)
```

**Comment by bryevdv** [comment]
Bokeh is subject to browser stack size limits, which AFAIK cannot be changed, so the short answer is "yes, definitely". Someone is currently working on a webGL backend and improved binary transport, that would reduce our memory overhead, and allow us to raise the ceiling on the number of points that can be pushed to the browser. At some point tho, you would not want to push millions of points into the browser. This is where the Bokeh server can be useful for downsampling or other pre-rasterizations schemes to reduce the data. Can you let us know how much data/number of points is in the file you linked? It won't let me just download it without signing up for something, which I am not going to do.

**Comment by bryevdv** [comment]
Closing without any additional information.
