### ISSUE TITLE
Bokeh equivalent to matplotlib.imshow

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#2426]
It would be nice to be able to have an equivalent to matplotlib's imshow (http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.imshow) without having to write a an RGBAColormapper every time.

For example, to get a plot like @mrocklin blogpost images here: http://matthewrocklin.com/blog/work/2015/02/13/Towards-OOC-Slicing-and-Stacking/

![image](https://cloud.githubusercontent.com/assets/4940549/8288608/d65c3ed0-18dc-11e5-8a10-246faa7e6b87.png)

in matplotlib you just write:

```python
>>> from matplotlib import imshow
>>> imshow(x[1000] - x.mean(axis=0), cmap='RdBu_r')')
```

In Bokeh you currently need to write your own colormapper and use image_rgba().

We could add that functionality into image_rgba(). If you don't pass a palette, then use your input as the RGBA, and if you do pass a bokeh palette name, then you can pass your raw data and the RGBAColorMapper would then return the appropriate rgba values.

Maybe that would look something like:

```python
from bokeh.plotting import image_rgba
p.figure()
p.image_rgba(data, palette='RdBl11')
p.image_rgba(data_rgba) #When already passing the transformation
```

When working on the ocean slider demo 2.0 https://github.com/ContinuumIO/dask/issues/277 @jcrist already wrote a RGBAColorMapper to be able to draw similar plots in Bokeh:

```python
class RGBAColorMapper(object):
    """Maps floating point values to rgb values over a palette"""
 
    def __init__(self, low, high, palette):
        self.range = np.linspace(low, high, len(palette))
        self.r, self.g, self.b = np.array(zip(*[hex_to_rgb(i) for i in palette]))
    
    def color(self, data):
        """Maps your data values to the pallette with linear interpolation"""

        red = np.interp(data, self.range, self.r)
        blue = np.interp(data, self.range, self.b)
        green = np.interp(data, self.range, self.g)
        # Style plot to return a grey color when value is 'nan'
        red[np.isnan(red)] = 240
        blue[np.isnan(blue)] = 240
        green[np.isnan(green)] = 240
        colors = np.dstack([red.astype(np.uint8),
                          green.astype(np.uint8),
                          blue.astype(np.uint8),
                          np.full_like(data, 255, dtype=np.uint8)])
        return colors.view(dtype=np.uint32).reshape(data.shape)

colormap = RGBAColorMapper(-6, 6, RdYlBu11)
colormap.color(data)
```

I think it would be great if we could add that functionality directly into Bokeh. I was actually asked about better image support at Pydata Berlin and Spark Summit.

Thoughts @bokeh/dev?

**Comment by almarklein** [comment]
+1 for having an easier way to display images

**Comment by damianavila** [comment]
:+1: as well...

**Comment by tderond** [comment]
One of the big drawbacks is that the bokeh standard palettes only have a dozen-or-so hues.
However, if matplotlib has a colormap that suits your needs, it's pretty easy to convert it into a bokeh palette:

```python
import matplotlib as plt
import matplotlib.cm as cm
import numpy as np

colormap =cm.get_cmap("Blues") #choose any matplotlib colormap here
bokehpalette = [plt.colors.rgb2hex(m) for m in colormap(np.arange(colormap.N))]
print bokehpalette
```

**Comment by jakirkham** [comment]
Also interested in a simplified form of this. Related would be nice to see `plt.matshow`. Here's a nice example showing how `plt.matshow` works on some trivial data and how to get `bokeh` to do the same thing ( http://nbviewer.ipython.org/github/jakirkham/bokeh_examples/blob/master/Bokeh_Example_14.ipynb ). Feel free to reuse in any way you see fit.

**Comment by jakirkham** [comment]
Also, want to mention this one, which is more like `imshow`. ( http://nbviewer.ipython.org/github/jakirkham/bokeh_examples/blob/master/Bokeh_Example_04.ipynb )

**Comment by hal98x** [comment]
Recently I really wanted to use bokeh to display gridded data. I have not been able to make a similar example to Christine's work. Has the suggested functionality from this thread been implemented? If not please consider making it easier to apply a color ramp to an image map. 

Please update and/or provide a link to image_rgba function documentation with a detailed description of the inputs. Also please update and or provide a better example of how to use image_rgba. 

Sincerely,


Michael Wallace, PGp, P.Geo.

**Comment by bryevdv** [comment]
I feel like I must be missing something. How is this substantially different from `Figure.image`? It accepts a 2d scalar array, and a palette, and colormaps according to the palette on the client:

http://bokeh.pydata.org/en/latest/docs/gallery/image.html

This has been part of Bokeh for a very long time.

**Comment by hal98x** [comment]
Thanks @bryevdv I never found this page or example. The link shows me a more relevant example. I also found the bokeh api for image and image_rgba.

**Comment by bryevdv** [comment]
I think I tend to assume people go to the gallery straight away, and just look for something vaguely similar to what they need, but that's evidently not how everyone approaches the docs. If there are other places to mention this or provide examples, suggestions are welcome.

**Comment by bryevdv** [comment]
Changing to `discussion` until a concrete proposal different from `Figure.image` is drawn out explicitly.

**Comment by hal98x** [comment]
Thanks @bryevdv your assumption probably is 80% correct.I think the main issue I had is I found the example and wanted to extend it, so I went looking for the api documentation and found more examples/issues. If possible please add a crosslink between the example and the function description.  

so just to make sure the dw and dh are total width and height  and not the distance between pixel centers?

**Comment by bryevdv** [comment]
Yes, that is correct. More cross linking and indexing id definitely on the (long) to-do list.

**Comment by forman** [comment]
@bryevdv  "How is this substantially different from Figure.image?"

The substantial difference is that in matplotlib I can select from dozens of well-known and *well-investigated color maps* and that matplotlib generates *color map legends* so that I'm ready to publish my results. Afaik bokeh still lacks these two features which are already nicely shown by @chdoig. Maybe this is just another issue. 

My team would really like to replace the matplotlib plots in our app by bokeh one, as bokeh often looks better, has a much cleaner API, and is also much faster in general. But the missing image features make this a little difficult still.

**Comment by bryevdv** [comment]
more colormaps recently added, custom colormaps can be added anytime, legends now supported

**Comment by sannawag** [comment]
This example helped me. http://bokeh-cookbook.github.io/blog/2016/06/15/image_n_image_rgba_plot/
