### ISSUE TITLE
Make axis wheel zoom configurable

### ISSUE THREAD

**Issue by jcrist** [bokeh/bokeh#2427]
This would be nice for figures where aspect is important, but zooming is also desired. Could either turn off the individual axis zoom interactions (so only scrolling in the figure will zoom), or "link" the zooming on the axis so that zooming on x moves the y axis as well.

**Comment by nsh87** [comment]
Agreed. If I place my mouse below the X axis on a map and then scroll it will just zoom along that axis. Potentially quite problematic.

**Comment by bryevdv** [comment]
Sorry, this probably should have been labeled as a feature request. I agree that the "axis only" behavior should be configurable (it is currently always on).
