### ISSUE TITLE
Colormap in Charts Heatmap not representing density property

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#2429]
In the current Chart Heatmap, the default colormap doesn't represent a scale of values:

![screen shot 2015-06-22 at 5 15 47 pm](https://cloud.githubusercontent.com/assets/4940549/8294446/62837e58-1902-11e5-950b-d05e83fd097e.png)

Those colors just feel like set at random and don't have associated with them a scale or order where it's obvious what the density or values for each of them are, like in the employment example:

![screen shot 2015-06-22 at 5 17 32 pm](https://cloud.githubusercontent.com/assets/4940549/8294570/e6b5df72-1902-11e5-99dc-394d2083342b.png)

I believe that the current chart.Heatmap might be confusing and not very useful to users. I'd suggest changing the palette to a scale-aware one.

**Comment by sauliusl** [comment]
I will add to this: can we get colour scale near the charts?

Heatmaps are virtually meaningless without an associated colour scale.
There should always be a colorbar representing what each colour means. 
One exception to this rule is when the heatmap is for binary data. In this case one can intuitively assume that dark means '1' and light means '0'. 

As @chdoig mentions, the current example in the documentation is at best ridiculous as not only there is no colour scale anywhere in the plot, it is also non-intuitive and confusing. 
The US employment example is a bit cleaner, as there is a clear progression of colours, yet, I am not really sure what the colours mean too (i.e. is green - low employment/high unemployment or the other way around?).

As a side note green-red is terrible for colour-blind population. Blue-red is probably a better shout.

Also the hover effects should be optional in my opinion.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/35)
