### ISSUE TITLE
Improve docs on how to output notebook in glyphs  - ipython notebook examples

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#2430]
There are two notebooks examples in that use the glyphs interface:
https://github.com/bokeh/bokeh/tree/master/examples/glyphs

In those, it seems that you need the following to output to the notebook:

```python
from bokeh.util.notebook import load_notebook
load_notebook()

from bokeh.util.notebook import publish_display_data
from bokeh.embed import notebook_div
data = {'text/html': notebook_div(plot)}
publish_display_data(data)

# or

from IPython.core.display import HTML
from bokeh.embed import notebook_div
HTML(notebook_div(plot))
```

The docs http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#ipython-notebook mention the ```notebook_div()```, but not the other bokeh.utils that are required to render the plot properly in the notebook.

**Comment by canavandl** [comment]
haha. that is the vintage import method :) We should fix that.

**Comment by damianavila** [comment]
> haha. that is the vintage import method :) We should fix that.

Sorry, I don't get the vintage reference... can you explain?

@chdoig, you can use any of the form... if you use the second one, there is no need to use Bokeh's `publish_diplay_data`, because the IPython's `HTML` use the display machinery to show it... in fact, `publish_diplay_data` is a wrapper we do around the low level internal machinery of the display system in IPython.

**Comment by bryevdv** [comment]
I always just use `HTML` I don't remember the rationale for `publish_display_data`. Can we just get rid of it?

**Comment by damianavila** [comment]
>I always just use HTML I don't remember the rationale for publish_display_data. Can we just get rid of it?

Yep, probably (maybe HTML was not available when you made the wrapper?? well, I suppose you made it but I did not git blame you to me sure).
I will make an issue and assign it to me... we probably need a deprecate cycle in place to warn people about it...

**Comment by damianavila** [comment]
Well let's just use this issue itself to remove it...

**Comment by chdoig** [comment]
It's also possible to use ```plotting.output_notebook()``` and ```plotting.show(plot)``` for the glyphs interface. Seems simpler. Shouldn't we just encourage that? Or at least mention it in the docs? Or have examples with that?

It seems to indicate that those just work or should just be used in the plotting and chart interface: 
http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html

*This is a fairly low-level, explicit way to generate an HTML file. When using the bokeh.plotting or bokeh.charts interfaces, users will typically call the function output_file() in conjunction with show() or save() instead.*

**Comment by bryevdv** [comment]
Yes it works fine for all interfaces we should just encourage that. At the time that note was written I am guessing it didn't work so well with bokeh.models.

**Comment by damianavila** [comment]
>Shouldn't we just encourage that? Or at least mention it in the docs? Or have examples with that?

Yep, probably...

**Comment by damianavila** [comment]
> Yep, probably...

Well... I still like that glyph example show how to do thing in the low level way... so I am not in agreement with myself now :stuck_out_tongue_closed_eyes:

**Comment by bryevdv** [comment]
`output_notebook` and `show` are to be recommended in almost all cases for everyone, marking as `invalid` based on current status. There are a few examples that do show how to do it "from scratch".
