### ISSUE TITLE
DataRange1d Start and End Bug

### ISSUE THREAD

**Issue by lukebarnard1** [bokeh/bokeh#2431]
The following code should produce this image (which uses Range1d in place of DataRange1d):
![screen shot 2015-06-23 at 10 50 09](https://cloud.githubusercontent.com/assets/6750344/8302315/bca1221c-1995-11e5-9dc9-2c656906922c.png)
```python
from bokeh.plotting import figure, output_file, show
from bokeh.models import DataRange1d

output_file("range_bug.html")

# create a new plot with a range set with a tuple
p = figure(plot_width=400, plot_height=400)

# set a range using a Range1d
p.y_range = DataRange1d(start = 0.0, end = 10.0)
p.x_range = DataRange1d(start = 0.0, end = 20.0)

p.circle([1,2,3,4,5], [2,5,8,2,7], size=10)

show(p)
```
However, it actually produces this image:
![screen shot 2015-06-23 at 10 50 22](https://cloud.githubusercontent.com/assets/6750344/8302326/e47cccf0-1995-11e5-80dd-56e4fbcc559e.png)

In the documentation of the relevant properties of DataRange1d, ```start``` and ```end```, it is stated: 
```python
    start = Float(help="""
    An explicitly supplied range start. If provided, will override
    automatically computed start value.
    """)

    end = Float(help="""
    An explicitly supplied range end. If provided, will override
    automatically computed end value.
    """)
```

But the values are not being overridden, as seen in the second image. ```range_padding``` appears to be working, however.

As a final note, the ranges were working fine in 0.8.2. Since upgrading to 0.9.0, this has appeared as a bug for us.

**Comment by bryevdv** [comment]
@damianavila super annoying but has a quick fix, pushed PR and moved to 0.9.1
