### ISSUE TITLE
Document when the callback occurs on the  TextInput widget. 

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2448]
Was with @brevdev working on a plot and had a notion that the TextInput callback happened onchange (i.e. everytime you enter a character) actually it works when you press enter or leave a cell.

Where should we put this kind of documentation? It's not going to be auto-generated.

**Comment by bryevdv** [comment]
In the callback help string to start, and then reiterated in an example, ideally.

**Comment by birdsarah** [comment]
Probably missing something obvious as I haven't written docstrings for the autogenerated docs. But TextInput doesn't have a callback docstring as the callback's on the parent....

**Comment by bryevdv** [comment]
No, we will just have to not put it on the parent, and instead nstput it on individual classes in order to customize the docstring per-class.
