### ISSUE TITLE
DatetimeTickFormatter does not respect format when interval changes

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2450]
Hi,

not sure if I've coded this wrong, but see what you think:

1) Go to http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/notebooks/electa/Followers-2.ipynb
2) In the chart in the bottom, play with the Start and End making them bigger e.g. start - 2014/1/1
3) Now try making the range smaller e.g. start 2015/2/1 & end 2015/5/1.

When the interval switches to 15 day increments then the format isn't respected.

**Comment by birdsarah** [comment]
(want to check this is really a bug)

**Comment by azjps** [comment]
You can find the DatetimeTickFormatter behavior [here](https://github.com/bokeh/bokeh/blob/0c78cf646ec95d3c003c714c35a388db4b4ad834/bokehjs/src/coffee/ticking/datetime_tick_formatter.coffee). It seems that when the (x-range / # of x-axis ticks) is less than a month, the tick formatting switches to the "days" formatter (which defaults to "%m/%d"). So this should cause your formatting to stick:

```python
xaxis = DatetimeAxis(
    formatter=DatetimeTickFormatter(
      formats={"months": ["%B %Y"], "days": ["%B %Y"]}),
    **AXIS_FORMATS)
```

The DatetimeTickFormatter's documentation could definitely use some help.

**Comment by birdsarah** [comment]
Thanks @azjps, that's exactly it. Will do a small docs update to get us started.

**Comment by damianavila** [comment]
In fact, this should be closed after the PR is merged :wink:

**Comment by birdsarah** [comment]
well......i thought there was a bug. there isn't a bug. which is why i closed the issue. but fine either way.

**Comment by bryevdv** [comment]
Yes, the intent of the `DatetimeTickFormatter` is to be able to specify "scale appropriate" formatting across a large range of time scales.
