### ISSUE TITLE
css - hplot of Paragraph & TextInput

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2451]
See: http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/electa/Followers-2.ipynb

Maybe I've coded this wrong, but I wanted to use Paragraph as a label for the text input, but it's come out fairly misaligned.

**Comment by damianavila** [comment]
Can you try this outside the notebook? maybe there is some clashing with the css...

**Comment by birdsarah** [comment]
Sorry - also looks bad, just different bad :)

**Comment by bryevdv** [comment]
IMO we should get out of the `Paragraph`, `HBox`, and `VBox` business. I'd like to find ways to make it easier for users to use real HTML templates and layouts, and the new `components` is a great step in that direction. It would be fruitful to see if the same treatment can be applied to the `autoload` functions as well.

**Comment by birdsarah** [comment]
@bryevdv - yes - that sounds great.

**Comment by bryevdv** [comment]
I think all of this is covered by the current ongoing layout work. Please re-open if I am mistaken.

**Comment by birdsarah** [comment]
Re-opening until it's actually fixed!

**Comment by birdsarah** [comment]
Confirm as part of #4392

**Comment by bryevdv** [comment]
I had to fudge some data and make a few other small changes (`CustomJS` instead of `Callback`, use a simple axis type). This is what it looks like on master:
<img width="808" alt="screen shot 2016-06-11 at 9 00 02 pm" src="https://cloud.githubusercontent.com/assets/1078448/15988462/abcda1ec-3017-11e6-8f5f-70ef30dbbf7b.png">

**Comment by bryevdv** [comment]
FWIW it looks the same outside the notebook, and also with `Row` and `Column`

**Comment by birdsarah** [comment]
Agreed - this is not fixed.

**Comment by bryevdv** [comment]
Well I stupidly did not save the updated test example code, and we need to get out a release with the tornado fix ASAP, so moving to `0.12.7`

**Comment by bryevdv** [comment]
Unfortunately the original test case is no longer available, so I am going to close this as `norepro` there is a good chance it is covered by one of the many other overlapping issues.
