### ISSUE TITLE
Datetime axis from timestamps off by 1e3

### ISSUE THREAD

**Issue by jcrist** [bokeh/bokeh#2453]
```python
from bokeh.plotting import output_file, show, figure

output_file('test.html')
p = figure(x_axis_type='datetime')
p.line(x=[1e-3, 2e-3, 3e-3], y=[1, 2, 3])    # x in seconds since epoch
show(p)
```

![screen shot 2015-06-24 at 11 56 25 pm](https://cloud.githubusercontent.com/assets/2783717/8347589/1aa40e82-1acd-11e5-9f20-4357e7fef6a5.png)

x-axis is off by scaling of `1e3` (microseconds should be milliseconds).

**Comment by colinfang** [comment]
I think bokeh treats numbers as milliseconds since epoch, not seconds. So this is not a bug.
See issue 2416 for related info

**Comment by bryevdv** [comment]
@colinfang this is correct re: ms since epoch. Regarding the display I think this could be rectified with a custom formatter. Since plotting down to sub microseconds is fairly specialized I'm inclined to let that be the solution rather than adding more to the core library.

**Comment by mrocklin** [comment]
I would find it useful to optionally accept seconds somehow.  Many systems base times on seconds rather than milliseconds.  A custom formatter would be fine with me.  Is there an example somewhere that does this or something close on which I could base a solution?
