### ISSUE TITLE
Allow movement of axes

### ISSUE THREAD

**Issue by JWDebelius** [bokeh/bokeh#2456]
I work with a lot of stacked bar charts, and some complex data traces. Sometimes, it's really useful to view all the data together on a single axis, because it lets me see trends. Other times, I want to be able to separate out the data, and focus on a single set. It would be cool if there was a way to have transparent, linked axes in bokeh animated to allow the data to either be overlayed on what appears to be a single axis, or viewed on multiple axes.

**Comment by bryevdv** [comment]
I can't quite visualize what you are suggesting. Do you have any link or examples you can share?

**Comment by bryevdv** [comment]
Closing for lack of feedback.
