### ISSUE TITLE
TapTool doesn't respect names selector

### ISSUE THREAD

**Issue by colinfang** [bokeh/bokeh#2462]
Callback triggers everywhere you click on the canvas.

See [demo here](http://nbviewer.ipython.org/gist/colinfang/aa7b6f69784fa1df623d)

Looking at code https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/tool/gestures/tap_tool.coffee#L26, it seems as long as there is a click, the registered renderers would trigger the callback, NO MATTER WHERE the click is.

This behaviour is a bit counter-intuitive. Either we need a bit more documentation, or we change the behaviour that only a click on the registed glyph itself would trigger a callback.

**Comment by colinfang** [comment]
Ok, now I realized that it is indeed my misunderstanding. I should use selection callback instead of taptool callback for my use case. I think we need to explain a little bit more in the docs.

**Comment by damianavila** [comment]
> I think we need to explain a little bit more in the docs.

Can you make a stab on it? :wink:

**Comment by birdsarah** [comment]
@colinfang - just curious if that nbviewer link works for you. I get a console error: `TypeError: $(...).headroom is not a function`

**Comment by damianavila** [comment]
Nbviewer link works for me and I can see the console error...

**Comment by birdsarah** [comment]
works for me too - sorry - computer fail today. still got that console error, but am guessing that's not from the demo.

**Comment by colinfang** [comment]
I see OpenURL handles this problem by:

**Comment by bryevdv** [comment]
I believe this is now adequately covered by the discussions and examples in the "Adding Interactions" section of the users guide. If there are still specific suggestions, please open a new feature request issue.
