### ISSUE TITLE
Make new dev setup smoother

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2463]
This will probably need to be split into smaller concrete actions, but here's my experience setting up a new dev environment.

    $ conda create -n bokeh_dev_py34 python=3.4
    $ source activate bokeh_dev_py34

### Javascript
Follow the js isntructions here: http://bokeh.pydata.org/en/latest/docs/dev_guide/building.html#building-bokehjs - this all works well

### Python
Undocumented but the quickest way to get all the bokeh dependencies is to install bokeh and then uninstall it:

    $ conda install -c bokeh/channel/dev bokeh
    $ conda uninstall bokeh

Use @Maggie-M's awesome new script to see how you're doing

    $ python scripts/devdeps.py

Missing all the docs and dev packages:

    $ conda install -c bokeh beautiful-soup colorama pdiff boto nose mock coverage websocket-client graphviz pygments sphinx-bootstrap-theme sphinxcontrib-httpdomain

This fails because pdiff and sphinx-bootstrap-theme aren't on bokeh's conda channel. Try again:

     $ conda install -c bokeh beautiful-soup colorama boto nose mock coverage websocket-client graphviz pygments sphinxcontrib-httpdomain

Try the script again:

````sh
$ python scripts/devdeps.py

--------------------------------------------------------------------------------
You are missing the following Dev dependencies:
 *  pdiff

--------------------------------------------------------------------------------
You are missing the following Docs dependencies:
 *  graphviz
 *  sphinx-bootstrap-theme
````

So that's weird it still thinks graphviz is missing even though I conda installed it.

    $ conda uninstall graphviz
    $ pip install graphviz pdiff sphinx-bootstrap-theme

Nope there's no pip install pdiff.

    $ pip install graphviz sphinx-bootstrap-theme

..... research install pdiff ......

````sh
$  sudo apt-get install perceptualdiff
$ pip install pdiffer

Collecting pdiffer
  Using cached pdiffer-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/user/1000/pip-build-7gr2sjoy/pdiffer/setup.py", line 6, in <module>
        long_description=open('README.rst').read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
````

....... pdiff isn't available for python 3 .........

**Comment by birdsarah** [comment]
Then I tried to run the tests even though I don't have pdiff installed.

(I know that master is having some AR test fails so ignoring that).

* Javascript tests run fine.

````python
import bokeh
bokeh.test()
````

gives me
````python
ImportError: No module named 'blaze'
````

Running 

````sh 
$ nosetests
````

````python
ImportError: No module named 'ggplot'
ImportError: No module named 'matplotlib'
ImportError: No module named 'seaborn'
ImportError: No module named 'icalendar'
ImportError: No module named 'scipy'
ImportError: No module named 'sympy'
ImportError: No module named 'blaze'
````


Should we include `blaze, ggplot, matplotlib, seaborn, icalendar, scipy, sympy` in the devdeps.py script?

Not having pdiff didn't seem to affect the tests running - is that right?

**Comment by bryevdv** [comment]
Yes, you have to set an environment variable specifically to run with `pdiff` and that is typically only done on the one TravisCI job. I was wondering if we could make a conda meta-package with all the dev deps, that would be be even easier than a script I think.

**Comment by birdsarah** [comment]
That would be wonderful.

For now, my guide to dev setup is:

* For JS follow the existing docs
* For python, don't worry about pdiff and then:

````sh
$ conda create -n bokeh_dev_py34 python=3.4
$ source activate bokeh_dev_py34
$ conda install -c bokeh/channel/dev bokeh
$ conda uninstall bokeh
$ conda install -c bokeh beautiful-soup colorama boto nose mock coverage websocket-client graphviz pygments sphinxcontrib-httpdomain ggplot matplotlib seaborn icalendar scipy sympy blaze
$ pip install install graphviz sphinx-bootstrap-theme
````

**Comment by bryevdv** [comment]
FYI here is the documentation for `conda metapackage`:

http://conda.pydata.org/docs/commands/build/conda-metapackage.html

I think is is supposed to be fairly straightforward. We could make a meta package with all the standard+dev dependencies (but without bokeh itself) Then I think we can get it down to one command:
```
conda create -n dev_env -c bokeh/channel/dev bokeh
```

**Comment by damianavila** [comment]
I was thinking about this the other day when I clean all my envs...
The straight solution is to have a envs file collecting all the requirements and use `conda env`.

`conda env create -n bokeh2 -f=bokeh_dev.yml`

I put the env file on this gist: https://gist.github.com/damianavila/d2ed948b16d3c3383909

We can link it in the BEP-2, and we should probably make a reference in the devs docs or maybe add it to the repo itself (where?) 

**NOTE**: you should have the bokeh, mutirri and javascript channel on your .condarc, or you can do:

```
conda config --add channels bokeh
conda config --add channels mutirri
conda config --add channels javascript
```
to add them (you need to do it just once...

Thoughts welcome...

**Comment by bryevdv** [comment]
I still think a bokeh-dev metapackage would be even easier for people.

**Comment by damianavila** [comment]
Some more comment pdiff in the devdeps is not the pdiff we use... is pdiffer, this is why it is failing and we need to remove it from that script... anyway is TravisCI stuff like @bryevdv said.
Also, you need to use a system installed graphviz... if you use the conda one... you will see some weird things like we have in the TravisCI run... @bryevdv investigate around this, but not sure if he pinged the conda guys/gals about the issue...

**Comment by mistakevin** [comment]
Are we interested in adding an environment.yml? https://github.com/bokeh/bokeh/issues/2624

**Comment by damianavila** [comment]
I am interested :wink:

**Comment by bryevdv** [comment]
@bokeh/dev is there anything to do here?

**Comment by damianavila** [comment]
We can probably continue the discussion in 2624

**Comment by bryevdv** [comment]
OK, closing this from inactivity. If there are new questions or concrete proposals please open a new issue.

**Comment by damianavila** [comment]
Just for reference, this should make the trick: https://github.com/bokeh/bokeh/blob/master/scripts/dev_environment

**Comment by birdsarah** [comment]
@damianavila - that's awesome - i didn't see that sneak in! thanks.

**Comment by damianavila** [comment]
It got merged as a secondary thing whereas I was fixing another thing... we should make a note in the devs docs if it is not there....
