### ISSUE TITLE
datetime array & np.datetime time timezone mismatch

### ISSUE THREAD

**Issue by colinfang** [bokeh/bokeh#2475]
See [demo here](http://nbviewer.ipython.org/gist/colinfang/18e21fc5f6c6f633fa66).

This line of code https://github.com/bokeh/bokeh/blob/master/bokeh/protocol.py#L86 takes the input as utc time, ignoring the timezone info.

I think we should add a check if the input is time zone aware:

    obj = obj.astimezone(pytz.utc) if obj is timezone aware.

Any thoughts?

**Comment by colinfang** [comment]
Related #1135

**Comment by bryevdv** [comment]
Closing just because I think this is a dupe of #1135 I do think it would be a good idea. I looks like some people made and effort but got stuck, perhaps someone can revisit soon.
