### ISSUE TITLE
Hovertool - Update the tooltip instead of creating and destroying DOM elements

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2479]
As per discussion here:
- https://github.com/bokeh/bokeh/pull/2386#issuecomment-117341062

Hover was getting sluggish when over lots of points because of lots of DOM updating. Instead of creating and destroying DOM elements, we could take an approach more like CrosshairTool and just try updating the class and contents of an existing element.

**Comment by bryevdv** [comment]
Possibly relevant, code I threw together but have not had the occasion to use yet:

http://jsfiddle.net/4o1LLLn4/31/

I was interested in "fancy" bubbles where he arrow angle could be controlled in order to support visual dodging, but it's relevant here because it uses the CSS update approach

**Comment by birdsarah** [comment]
Possible related - #1512

**Comment by bryevdv** [comment]
The initial suggestion of this issue has been carried out, tooltips now show/hide and update instead of creating a new div every time.
