### ISSUE TITLE
heatmap.ipynb won't load on Chrome, Firefox (Mac)

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#2492]
Gives error `[Exception... "<no message>" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: http://localhost:8888/static/components/jquery/jquery.min.js?v=20150702103224 :: .send :: line 6" data: no]` on Firefox (Mac). Safari loads fine

**Comment by mistakevin** [comment]
Duplicating the notebook into _heatmap-Copy1.ipynb_ works fine. Renamed copied file to _heatmap.ipynb_, breaks again. Any thoughts on this weirdness? @damianavila

**Comment by damianavila** [comment]
Probably the ipynb is corrupted in some way, I will take a look...

**Comment by damianavila** [comment]
Well, it is loading for me in chrome, I can not replicate the behavior...
Are you using the incognito mode and hard cleaning you cache?

**Comment by mistakevin** [comment]
Clearing the cache did not seem to work for either browser, but opening incognito in Chrome works. Firefox fails in private window.

**Comment by damianavila** [comment]
How did you clean the cache in chrome? Did you use a hard-cleaning: http://superuser.com/a/512833?

**Comment by mistakevin** [comment]
Yeah, I cleared it from the "Clear Browsing Data" menu, disabled it in DevTools, and have it blocked on every page refresh with the [Cache Killer](https://chrome.google.com/webstore/detail/cache-killer/jpfbieopdmepaolggioebjmedmclkbap) extension. (which I highly recommend)

**Comment by damianavila** [comment]
That's weird... I don't know what else to suggest... I will try to reproduce again...

**Comment by birdsarah** [comment]
Just to note that, on linux (I know you were on a mac) it seems works fine - in py2 and py3 with 0.9.1rc.

**Comment by mistakevin** [comment]
Restarted computer. Same results. Can anyone with a Mac reproduce for my sanity?

**Comment by canavandl** [comment]
Haha. It doesn't work for me either. I'm on Trusty 14 (Ubuntu) and Chrome. I actually opened an issue about this a month or two ago (#2340), but nobody was able to reproduce.

**Comment by mistakevin** [comment]
@canavandl  🙌

**Comment by canavandl** [comment]
@mistakevin we're not crazy!

**Comment by birdsarah** [comment]
Hi @mistakevin, I booted into osx (a rare occurrence) and did the following:

````bash
 1875  conda create -n bokeh_test_py27 python=2.7
 1876  source activate bokeh_test_py27
 1877  conda install -c bokeh/channel/dev bokeh
 1878  conda install ipython-notebook
 1879  cd /Users/bird/anaconda/envs/bokeh_test_py27/Examples/bokeh/charts/notebook
 1880  ipython notebook
```` 
It worked :s - see screenshot below - with all three browsers and my osx info.  The only thing I can think of is - is your ipython notebook in the same env?

<img width="1440" alt="heatmap notebook" src="https://cloud.githubusercontent.com/assets/1796208/8501750/a9a22cae-21a8-11e5-83f2-0f2c2083fe01.png">

**Comment by mistakevin** [comment]
@birdsarah What version of iPython Notebook?

**Comment by birdsarah** [comment]
Hah - I'm already back in ubuntu so can't check easily, but it would be whatever version `conda install ipython-notebook` would give 10 minutes ago. So I'm guessing  ipython-notebook 3.2.0 (based on https://binstar.org/search?type=conda&q=ipython-notebook).

**Comment by canavandl** [comment]
So it works for me on Chromium and Firefox, but not Chrome...

**Comment by birdsarah** [comment]
In ubuntu or osx?

**Comment by canavandl** [comment]
Ubuntu

**Comment by canavandl** [comment]
I deleted the .ipynb_checkpoints/ directory and that didn't work.

**Comment by birdsarah** [comment]
Works on all for me (ubuntu 15.04):
* chromium - Version 43.0.2357.81 Ubuntu 15.04 (64-bit)
* chrome - Version 43.0.2357.130 (64-bit)
* firefox - 38 - 20150511103303

**Comment by birdsarah** [comment]
and your bokeh and your ipython notebook are all in the same env?

**Comment by mistakevin** [comment]
Oh Blah. It was AdBlock Plus blocking jQuery on that particular notebook. Lame.

**Comment by canavandl** [comment]
<internal screaming>

**Comment by birdsarah** [comment]
fwiw - I switched to Blur - https://dnt.abine.com/#register - from AdBlockPlus - which isn't quite the same thing but does stop me from being tracked around the internet and doesn't have such serious consequences.
