### ISSUE TITLE
Remove remaining vendor libraries from check in

### ISSUE THREAD

**Issue by kevincolten** [bokeh/bokeh#2493]
We could fork the library's repository into our bokeh organization and bring it in through npm/bower, or possibly look at [bower](http://bower.io/) to see if it's available. Forking it will help us keep track of the changes we make to it as well.

**Comment by mistakevin** [comment]
After assessing the remaining vendor libraries that are still checked into Git, there is a possible discussion of how we want to go forward with this. 

The JS libraries can be settled by forking the original vendor library in our bokeh organization, adding in our tweaks and pulling it in using [npm's GitHub integration](https://docs.npmjs.com/files/package.json#github-urls). This gives us the added benefit of keeping our libraries updated with the vendor by a simple pull request and (hopefully small) merge conflict resolves.

But CSS is a little trickier, we've gone and changed a lot of css class names to better scope our css, such as adding `bk-*`, etc. This keeps users using Bootstrap, FontAwesome, etc from importing or changing our custom css. This makes it more difficult to abstract out and updating a library, such as Bootstrap 3.1.1 -> 3.3.5. Also, we add some global tag css such as in this issue https://github.com/bokeh/bokeh/issues/2589, (with more issues listed in there).

If we wanted to stay up-to-date without spilling our css onto the end-user's css, we can investigate using "scoped" css, such as https://github.com/PM5544/scoped-polyfill or https://github.com/MaxGfeller/apply-css.

I'm not sure if I'm just too "pro-update" with external libraries. Do we plan on sticking with these library versions until the bitter end?

@bokeh/dev

**Comment by bryevdv** [comment]
We have gotten rid of many vendored libraries altogether and will still get rid of a few more. I think this issue can be closed.
