### ISSUE TITLE
MultiSelect appears broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2495]
Following code:

```
from bokeh.models.widgets import MultiSelect
from bokeh.io import output_file, show, vform

output_file("multi_select.html")

multi_select = MultiSelect(title="Option:", value=["foo", "quux"],
                           options=["foo", "bar", "baz", "quux"])

show(vform(multi_select))
```

results in:

![screen shot 2015-07-02 at 4 13 10 pm](https://cloud.githubusercontent.com/assets/1078448/8487964/3f73674a-20d5-11e5-8c7a-72588d3ac4ea.png)

**Comment by Liwink** [comment]
May I use Date Table to select data and interact with figure?
Is it difficult?
