### ISSUE TITLE
Use Bokeh.$ in server test template tab_play?

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2499]
Should we be using `Bokeh.$` instead of plain `$` in the test template tab_play?

https://github.com/bokeh/bokeh/blob/master/bokeh/server/templates/tests/tab_play.html#L17

````js
  function resizeRoot() {
    var winHeight = $(window).height();
    var winWidth = $(window).width();
    var bokehRootHeight=(winHeight * .95);
    var midPanelHeight = (bokehRootHeight * .65);
    var pyEdPaneHeight = (bokehRootHeight * .20);
    //alert('resize'+bokehRootHeight);
    $('#bokehRoot').height(bokehRootHeight);
    $('.midPanel').height(midPanelHeight);
    $('#bokehMidContainer').width(winWidth * .95);
    $('.bokeh-py-pane').width(winWidth * .85);
    $('.bokeh-py-pane').height(pyEdPaneHeight);
  };
````

I wasn't sure how to actually test this template so don't know what the outcome of this looks like.

**Comment by birdsarah** [comment]
I actually can't find anywhere that this is used - maybe we should remove it?

**Comment by damianavila** [comment]
Probably a leftover of previous thing... I guess we could remove it. @bryevdv do you remember something about this? Seems pretty old...

**Comment by bryevdv** [comment]
No idea what this is.
