### ISSUE TITLE
{Int,Number}Editor (cell editor) apperance is broken in all browsers

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#2500]
This editor should render increment/decrement arrows on the right, vertically stacked one on top the other. However, arrows are rendered horizontally, outside a cell.

**Comment by bryevdv** [comment]
@mattpap can you provide code to reproduce? Is this still an issue?

**Comment by bryevdv** [comment]
The current editors do not have arrows, but do work. If there is demand for inc/dec arrows, a separate feature request can be opened.
