### ISSUE TITLE
Error in embed/slideshow/app_reveal.py

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#2501]
Error in flask server `requests.exceptions.ConnectionError`

**Comment by birdsarah** [comment]
i only get that error if bokeh-server isn't running.

run `bokeh-server` from one terminal and then `python app_reveal.py` in the other.

**Comment by damianavila** [comment]
I can run the example but I have a cross origin problem... anyone else is seeing this behavior?

**Comment by birdsarah** [comment]
ok......this is weird...digging in more. i was happily playing with it in chrome. then i saw your message about cors. opened it up in ff and refreshed in chrome and then chrome got the cors......digging.

**Comment by mistakevin** [comment]
Working for me now.

**Comment by damianavila** [comment]
Yes, I had the server in multiuser mode... closing here...

**Comment by birdsarah** [comment]
totally can't reproduce what i saw.
