### ISSUE TITLE
No resize icon if the only tool

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2502]
Seen in examples on: `charts/./horizon` and `glyph/chloropleth' if the only tool selected is resize. Then the resize icon is missing. Although resize does work.

![chloropleth_resize_missing](https://cloud.githubusercontent.com/assets/1796208/8503139/b7da85de-21ba-11e5-9e98-808450577f57.png)

**Comment by bryevdv** [comment]
closing on the assumption that the resize tool is going away.
