### ISSUE TITLE
It should be easy to template bokeh plots

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2503]
Bryan and I had a fair amount of fun trying to template the spectrogram example.

It should have been easier. In particular there's a lot going on because you set the plot width in the python script.

I think this could be a lot easier with the responsive flag I've been wanting to do.  In general though, my goal would be, if I set up a bootstrap grid, my plots should just plonk into it as expected.

**Comment by bryevdv** [comment]
Agreed 100% the exact thought came to me last night.

**Comment by bryevdv** [comment]
I think this is / will be covered by the layout work as well as some of the previous work recently.
