### ISSUE TITLE
Use of Document and f.write in glyphs examples

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2505]
A lot of the glyphs examples use the following pattern:

````python
doc = Document()
doc.add(plot)

if __name__ == "__main__":
    filename = "daylight.html"
    with open(filename, "w") as f:
        f.write(file_html(doc, INLINE, "Daylight Plot"))
    print("Wrote %s" % filename)
    view(filename)
````

should we use something more bokehish

e.g.

````python
filename = "daylight.html"
output_file(filename)
show(plot)
````

**Comment by birdsarah** [comment]
Spoke to @bryevdv about this who pointed out that `output_file` is using the plotting interface, glyphs examples are all about the low-level stuff.

**Comment by bryevdv** [comment]
Well, not quite what I would say. It's fine to use output_file with the glyphs interface and that is probably recommended. It's part of bokeh.io and works for any and all interfaces. It should be the go-to default in all cases.  But a few examples that show how to do things "by hand" are ok too.

**Comment by damianavila** [comment]
Yes, please, keep at least one example with the lowest level thing for reference...
