### ISSUE TITLE
Seperate out data processing in examples

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2506]
Making a plot can often mean a lot of data processing. So the tradeoff in the examples is between a lot of data processing clutter and interesting visualizations.

Can we come up with a strategy / organizations to move the data processing out of the examples file, so that the main examples files just focus on the bokeh code.

This may not be a massive problem. Just a thought. The example that sparked this thought was glyphs/donut.py

**Comment by bryevdv** [comment]
I think most of the examples are fine, and then also that it is important to have *some* examples "show all the steps" even if there are alot or extra steps. Closing this for now but re-open if there are specifics to discuss.
