### ISSUE TITLE
Have Grid that respects bounds of axis

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2507]
In `examples/glyph/iris.py` the bounds parameter of LinearAxis is demonstrated.

Grids are also added to the plot.  On zoom out, the axis does not gain any extra tick marks, but the grid lines do continue.

![iris_grid_bounds](https://cloud.githubusercontent.com/assets/1796208/8504175/eeaab8ec-21cc-11e5-89f6-e0aa23d15564.png)

**Comment by bryevdv** [comment]
This is already configurable via `Grid.bounds`: 
```
from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers

colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'
p.xaxis.bounds = (3, 5)
p.xgrid.bounds = (3, 5)

p.circle(flowers["petal_length"], flowers["petal_width"],
         color=colors, fill_alpha=0.2, size=10)

output_file("iris.html", title="iris.py example")

show(p)
```
<img width="626" alt="screen shot 2018-02-19 at 12 47 28" src="https://user-images.githubusercontent.com/1078448/36396432-108a65a6-1573-11e8-8b2d-cd1d81644544.png">

It's possible this could be better documented. I think it would be a mistake to have something explicitly set/copy this from axis, say, but perhaps `'auto'` could mean take a cue from axis. I think this issue should also fix the spillover in minor ticks as well.
