### ISSUE TITLE
release testing automation and improvements 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2509]
It would be good to make the release testing process more regular, predictable and automated (where possible). We have some tools that help with this, but they are not as widely know 

* automation tools working on all platforms:
 - `create_envs.py` - create envs for all supported install configurations
 - `test_install.py` - run basic checks and `bokeh.test()` in specified environments 
 - `interactive_tester.py` - run through a examples, collecting feedback for the test matrix
* a test schedule for verifying and maintaining these tools (find and fix issues *before* the tools are needed for a release)
* clear, step by step test plan for all platforms with explicit commands to run
* determine how long (roughly) completing the test plan takes 
* update dev docs in one place with test plans and estimates 

Ideally we would start collecting data about how long the test plans actually take people to finish so the estimates can be improved/adjusted.

**Comment by damianavila** [comment]
@bryevdv are you closing this because you have some ideas about how to proceed forward?

**Comment by bryevdv** [comment]
I think there are other independent issues (e.g. investigating test management software) that cover this better.

**Comment by damianavila** [comment]
> I think there are other independent issues (e.g. investigating test management software) that cover this better.

Fair enough, thanks!
