### ISSUE TITLE
DOC: Broken plots in examples

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#2515]
Was looking back through the examples and found a few that were broken.

- [x] Shows traceback ( http://bokeh.pydata.org/en/latest/docs/tutorials/solutions/gallery/lines.html )
- [x] No data appearing ( http://bokeh.pydata.org/en/latest/docs/tutorials/solutions/gallery/style.html )
- [x]  Other Interfaces in the user guide ( http://bokeh.pydata.org/en/latest/docs/user_guide/concepts.html#other-interfaces )

**Comment by bryevdv** [comment]
@jakirkham Thanks for pointing these out. I had actually intended to remove the tutorial section there entirely, in favor of the new tutorial notebooks being developed at 

http://nbviewer.ipython.org/github/bokeh/bokeh-notebooks/blob/master/index.ipynb

But forgot to remove them before the release. We will probably just re-deploy the docs soon with these plots removed and a pointer to the new notebooks.

**Comment by jakirkham** [comment]
That sounds really cool. It seemed like reorganization of the examples was due. I like this move towards having them all in iPython notebooks.

**Comment by chendaniely** [comment]
- [ ] Other Interfaces in the user guide (http://bokeh.pydata.org/en/latest/docs/user_guide/concepts.html#other-interfaces)

**Comment by bryevdv** [comment]
That last one is actually Seaborn breaking us :) But we should change it until we can update to make it work again. Thanks for the careful reading!

**Comment by jakirkham** [comment]
@chendaniely, thanks. Added to the list.

**Comment by smartsammler** [comment]
@bryevdv
In the other Interfaces examples the "color" should be an "palette", shouldn't it? But if I change it like that, bokeh/compat/mplexporter/renderers/base.py breaks on line 192.
Or was this your point?
I'm sorry that I don't know seaborn yet and therefore just tried to get some of my matplotlib experience transfered to seaborn+bokeh—hopefully this helps you.

**Comment by bryevdv** [comment]
FYI The PR removes the old tutorials and replaces them with links to the new notebooks on nbviewer.

**Comment by jakirkham** [comment]
@bryevdv, I see you have merged these changes. How long does it take before these changes would appear on the website?

**Comment by bryevdv** [comment]
The next release (next week)

**Comment by bryevdv** [comment]
However, I have updated the currently deployed docs by hand, they should be on the website now.
