### ISSUE TITLE
TimeSeries.xlabel and ylabel should be properties?

### ISSUE THREAD

**Issue by eteq** [bokeh/bokeh#2519]
I've noted some confusing inconsistent behavior in the `TimeSeries` chart (while in the scipy 2015 Bokeh tutorial):

```python
ts = TimeSeries(somedata)
ts.title = 'A title'
show(ts)
```
Does exactly what I'd expect: yields a plot with the title.  However, neither of the following work:
```python
ts.xlabel = 'a label'
```
This raises an  ``AttributeError:  unexpected attribute 'xlabel' to Chart ... ``
```python
ts.xlabel('a label') # the docs say it's a *method*
show(ts)
```
which doesn't raise an error , but the resulting plot has no xlabel.

Not sure if this is a bug or a design choice, but either way it's a bit confusing.

**Comment by bryevdv** [comment]
`xlabel` works and is documented as a property in current releases.
