### ISSUE TITLE
DatetimeTickFormatter documentation incomplete

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2521]
Scipy 2015 user wanted to plot datetime data using non-Gregorian calendar (Julian time from astropy). Plotting his data yielded an datetime axis that was 00:40 to 00:45 min and not the expected format. It was unclear from the documentation how to properly plot his timeseries data (correct answer was likely using NumericalTickFormatter instead)

**Comment by bryevdv** [comment]
Tick formatters (including `NumeralTickFormatter`) now have fairly extensive docs/examples at: http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#tick-label-formats
