### ISSUE TITLE
Add some sort of aspect ration constraint when zooming/selection a plot area

### ISSUE THREAD

**Issue by ocefpaf** [bokeh/bokeh#2522]
In @chdoig awesome bokeh tutorial we saw the cool mapping example.  However, one can easily distort that map using bokeh's interactive interface.

Mapping and projections are a hard problem and I do not think that bokeh should re-invent the wheel.  Maybe bokeh could add an `aspect_ratio` constraint instead.  That way users could pass their projection formulas and it will guarantee the right aspect ratio.  For example:

```python
mercator = [x=1, y=np.cos(np.mean(ylims) * np.pi/180]

bokeh_plot.aspect_ratio=mercator
```

**Comment by bryevdv** [comment]
This is definitely already on the todo list, just has not been done, yet. 

refs: #474 #2427

**Comment by damianavila** [comment]
Although this was raised before, I think the concept about passing a projection formula is interesting to have it into account... I will make a comment in #474 referencing this idea...

**Comment by pzwang** [comment]
How does the projection help define the aspect ratio of the plot?  I'm just not grokking this somehow...

**Comment by ocefpaf** [comment]
A quick-and-dirty way to set the aspect ratio for [cylindrical projections](https://en.wikipedia.org/wiki/Mercator_projection#Cylindrical_projections), using raw matplotlib, would be:

```python
plt.subplot(111, aspect=(1.0/np.cos(np.mean(yaxis_data)*np.pi/180.0)))
```

**Comment by bryevdv** [comment]
But that has nothing to do with setting aspect ratios in general, right? Or am I missing something? Aspect ratio is a number, it can come from anywhere. I don't understand how it coming from a projection formula in some situations  would change anything in terms of what needs to be implemented.
