### ISSUE TITLE
(general) a suggestion that may help others learn the bokeh API

### ISSUE THREAD

**Issue by ericmjl** [bokeh/bokeh#2523]
I noticed myself struggling through the same issue when learning the `matplotlib` API - I simply couldn't map object name to figure element drawn, and didn't have a clear idea on what each object's attributes were either, and whether they are modifiable or not.

Would it help to have some example illustrations with code that helps us unify this knowledge? I am thinking a simple line chart example, but now with the object name for the legend, and the attributes that are modifiable, drawn out clearly, something like that. I am happy to put one together as an illustrative example, if I could also get commitment on help from the devs on whether I've got the API right or wrong.

**Comment by birdsarah** [comment]
Hi @ericmjl, have you seen this page: http://bokeh.pydata.org/en/latest/docs/reference/plotting.html

It's a bit buried and took me a while to find it, but i'm wondering whether it's what you're after or if you'd like other features.

**Comment by ericmjl** [comment]
@birdsarah Yup! This is one of those things that really helped with making plots. 

One of the specific places in christine's tutorial at scipy2015 was on doing styling. I found it difficult to figure out how to access the drawn objects and their properties. Is there documentation on this?

As for an illustration, I hand-drew one just to kickstart some ideas: https://www.evernote.com/l/AAOxCFLsMRNBxaOuPwjuUbPQEGZlJ4AI-aw

**Comment by bryevdv** [comment]
There is now much documentation on styling at http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html
