### ISSUE TITLE
Rendered slider* plots have missing bk-* classes

### ISSUE THREAD

**Issue by kevincolten** [bokeh/bokeh#2527]
May happen on more than just sliders.

```
s = Slider(start=0, end=92, value=1, step=1, title="Time", callback=callback)
show(vplot(s))
```

renders as:
![screen shot 2015-07-08 at 9 33 59 am](https://cloud.githubusercontent.com/assets/4411115/8572948/db3b2d56-2554-11e5-889c-caf6b7abce45.png)

but `script, div = components(s)` outputs code that renders as
![screen shot 2015-07-08 at 9 36 36 am](https://cloud.githubusercontent.com/assets/4411115/8572991/052749ce-2555-11e5-9e87-70b294cb17f6.png)

**Comment by birdsarah** [comment]
The slider template is a particular mess - you'll notice that the label and value are outside of that div so they're really hard to target. It's on my todo list as part of: #2374.

I'm going to add bk namespacing to that issue if that's ok.

**Comment by mattpap** [comment]
@birdsarah, just lets make sure to not confuse styling aid with a very disturbing bug (as it seems to me). Also there is some new hackery in `src/coffee/common/build_views.coffee` that may have something to do with this issue.

**Comment by bryevdv** [comment]
It's just alot of repo churn. Can you characterize the seriousness of the bug?

**Comment by bryevdv** [comment]
@mistakevin @birdsarah @mattpap can this be closed now?

**Comment by birdsarah** [comment]
It's still a bug. But I think it would better be described as widgets must be wrapped in a layout to be renderered correctly.

I hope my layout work is going to fix that. 

I suggest we keep it open.

**Comment by bryevdv** [comment]
@birdsarah can you comment if this was ever resolved by the layout work?

**Comment by mattpap** [comment]
@bryevdv, still an issue, though not for too long (#5502).

**Comment by bryevdv** [comment]
Moving to`0.12.6` since it should be closed with the linked PR

**Comment by bryevdv** [comment]
Moving to `0.12.7` since linked PR moved there
