### ISSUE TITLE
Internal Server Error on Quickstart

### ISSUE THREAD

**Issue by ericdill** [bokeh/bokeh#2529]
Was reading through the quickstart page of the docs this morning and ran into an Internal Server Error right below the "Bokeh Plot Server" bit.  Here is a screenshot. Is there any other information that I can provide that would be helpful?

![screenshot from 2015-07-09 12 25 50](https://cloud.githubusercontent.com/assets/6223243/8602121/11c12e5c-2636-11e5-9908-e7b89996c9fd.png)

**Comment by birdsarah** [comment]
Thanks for reporting @ericdill - I see it, we probably need to restart the bokeh-server that's powering that example.

**Comment by bryevdv** [comment]
It wasn't really set up in an especially scalable setup, I will ssh into the machine and try to get things started with more workers.

**Comment by bryevdv** [comment]
I've restarted everything. It was kind of a pain. More automation needed.

**Comment by ericdill** [comment]
The widget has been resurrected!  Good luck with the automation :smile:
