### ISSUE TITLE
compat/seaborn/violin.py is broken

### ISSUE THREAD

**Issue by adityaramesh** [bokeh/bokeh#2533]
The Seaborn [violin plot example](https://github.com/bokeh/bokeh/blob/master/examples/compat/seaborn/violin.py) no longer works, and gives the following error:

    Error
    Unable to generate Bokeh plot at /Users/bryan/work/bokeh/sphinx/source/docs/gallery/violin.rst:12:
    to_rgb: Invalid rgb arg “Set3” could not convert string to float: ‘set3’

The [corresponding webpage](http://bokeh.pydata.org/en/latest/docs/gallery/violin.html) on the Bokeh website also has the same problem.

**Comment by bryevdv** [comment]
Seaborn recently released a new version 0.6 and it broke our integration. It will take some time for us to adapt to it, in the mean time users will have to use Seaborn 0.5 if they want to have violin plots.

**Comment by adityaramesh** [comment]
Ok, thanks for the information.

**Comment by birdsarah** [comment]
closing this @adityaramesh, feel free to open if the 0.5 fix doesn't work for you.

**Comment by damianavila** [comment]
I reopened as a bug...

**Comment by bryevdv** [comment]
@damianavila this is fixed now?

**Comment by Maggie-M** [comment]
Yes, confirmed fixed.
