### ISSUE TITLE
New issue types - stale, questions, ...

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2536]
As the issues grow, there seems to be a need for some new issue labels. In particular a `type: stale` and `type: questions`

BEP-1 outlines how we currently deal with things and the need for a new discussion around types which should be mutually exclusive: https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management

**Comment by bryevdv** [comment]
I would regard `stale` as a resolution, not a type? I also would propose that `discussion` be retired, as it has collected features, bugs, questions all in a jumble. I think replacing with a `question` type is good. My personal view is that questions should not be left open indefinitely and that there should be some stated policy for expiring these issues (with explicit acknowledgement)

**Comment by bryevdv** [comment]
One other suggestion I would put forward is that every type should have a set of resolutions, and that everything eventually get a resolution. For `question` maybe `reso: answered` and `reso: stale` (or invalid maybe?)

**Comment by birdsarah** [comment]
+1 on `reso: answered` - I think that leaves us a way to mark a question as answered, people can re-open if the answer doesn't work for for some reason.

**Comment by birdsarah** [comment]
and yes `reso: stale` might be right. 

There are a lot of feature requests. They should be marked with `type: feature`.

I'd propose they also get marked with `reso: stale` if they don't get implemented after....say 6 months. We will still be able to view them all via issues filters, so they are not lost, but they clearly don't have sufficient current interest.

I would also suggest that items that have someone assigned to them, even if they are passed a standard cutoff period do not get marked as `stale`.

**Comment by birdsarah** [comment]
I hope I'm not taking this discussion off the rails, but I also think we're also using the milestones `long-term` and `short-term` as dumping grounds. In particular, `short-term` which has 238 open issues in it (and 42 closed ones - which maybe shouldn't be there).

If someone showed-up fresh to the bokeh project tomorrow, I don't think `short-term` and `long-term` give a decent picture of the trajectory of the project, in particular the short-term vision which is somewhat solidified.

Wrangling github issues to document something coherent without being too much overhead is tricky, so the straw-man suggestion that I have is to
- drop `short-term` & `long-term`
- have a milestone for whatever the next release is (which allows us to document what made it into the release)
- have a narrative, maybe on the wiki on the short-to-medium term priorities
- after a release, all tickets get flushed to no milestone (as opposed to being punted forward)

**Comment by bryevdv** [comment]
@birdsarah points 2 and 4 already happen, and point 3 happens to some degree (we used to better about updating the roadmap, and a new pass over it is definitely warranted).

I also agree that `short-term` and `long-term` are dumping grounds, but I I would also say that that is their intended purpose. After all, *every* open issue is suppose to be in one or the other. That is by definition a dumping ground. But the split between them is also intended to provide an extremely course funnel of "small effort" vs "long effort". (So I also would not have thought to try and triangulate the direction of the project from them, this has never occurred to me) I personally find this useful (although would welcome more discipline/review in their usage) and would advocate for keeping them. But maybe there are better names that don't have any potential "project direction" connotation.

**Comment by bryevdv** [comment]
Focusing the discussion, what about this set of types and resolutions:
* bug/feature/task: dupe, invalid, wontfix, completed, upstream 
* question: dupe, answered, invalid, onhold (stale?), upstream

This is my initial proposal. Are there cases/situations that are not covered? Maybe a new type "proposal" that must eventually be moved to one of the other types, or closed with some "rejected" status. This type would be for "discussions" that are not questions, and they would come with a built-in expiration after some period of no discussion.

**Comment by damianavila** [comment]
>Focusing the discussion, what about this set of types and resolutions:

>bug/feature/task: dupe, invalid, wontfix, completed, upstream

I think you forget `stale` as a new `reso`...

>question: dupe, answered, invalid, onhold (stale?), upstream

completed is really another way to say solved... and we will have `stale`, and I would like to see the `reso` options available for all the `type`s... I would not like to see special reso for special types...

So, I guess I would go with:

New type: question
New reso: stale


>This is my initial proposal. Are there cases/situations that are not covered? Maybe a new type "proposal" that must eventually be moved to one of the other types, or a pointer to a BEP, or closed with some "rejected" status. This type would be for "discussions" that are not questions, and they would come with a built-in expiration if discussion withers.

New tag: proposal (see below)

Also I agree that we need some expiration for the discussion, it can not live for ever... 3 month seems reasonable, I think... the same should go with the questions... but with a short expiration: 1 month

Additionally, I agree with @bryevdv about keeping the short and long term milestone... but maybe we start having two opened "next release"... I mean... today, I will have 0.9.2 and 0.9.3 milestone, so we can start planning the next point release early...

Thoughts?

**Comment by bryevdv** [comment]
I would not suggest `stale` as a reso for bugs features. My position is that those require affirmative resolution and should not expire, only questions and discussion/proposal should have a policy about "expiring". 

I'd be ok with `completed` for questions (instead of `answered`) 

There's something I don't like about `stale` (the particular word, not the concept for our process)

**Comment by damianavila** [comment]
> only questions and discussion/proposal should have a policy about "expiring"

I agree... 

>There's something I don't like about stale (the particular word, not the concept for our process)

What about `expired`, so we know we can not "expire" a bug or feature, but we expire a discussion or a question...

**Comment by bryevdv** [comment]
Now that we are actively shunting support questions to the ML, I don't think "answered" is reasonable. There is another issue do discuss a "referred" status, I will close this in favor of that.
