### ISSUE TITLE
Improvements to Legends with MultiLine

### ISSUE THREAD

**Issue by chendaniely** [bokeh/bokeh#2539]
In the ebola line tutorial #2538 I showed how you can use multi_line to draw multiple lines but if you try to pass a list of legend values you will get a TypeError:

```
p = figure(x_axis_type = 'datetime')
p.multi_line(xs=time, ys=case_country_values, color=colors, legend=type_country_name)
show(p)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-b8ed7f8253de> in <module>()
      1 p = figure(x_axis_type = 'datetime')
----> 2 p.multi_line(xs=time, ys=case_country_values, color=colors, legend=type_country_name)
      3 show(p)    

/home/dchen/anaconda3/envs/ipynb/lib/python3.4/site-packages/bokeh/_glyph_functions.py in func(plot, *args, **kwargs)
     41 
     42         if legend_name:
---> 43             _update_legend(plot, legend_name, glyph_renderer)
     44 
     45         for tool in plot.select(type=BoxSelectTool):    

/home/dchen/anaconda3/envs/ipynb/lib/python3.4/site-packages/bokeh/plotting_helpers.py in _update_legend(plot, legend_name, glyph_renderer)
    151         raise RuntimeError("Plot %s configured with more than one legend renderer" % plot)
    152     specs = OrderedDict(legend.legends)
--> 153     specs.setdefault(legend_name, []).append(glyph_renderer)
    154     legend.legends = list(specs.items())
    155     

/home/dchen/anaconda3/envs/ipynb/lib/python3.4/collections/__init__.py in setdefault(self, key, default)
    190     def setdefault(self, key, default=None):
    191         'od.setdefault(k[,d]) -> od.get(k,d), also set od[k]=d if k not in od'
--> 192         if key in self:
    193             return self[key]
    194         self[key] = default    

TypeError: unhashable type: 'list'
```

**Comment by birdsarah** [comment]
I'm not the most familiar with the plotting interface, but having played around with your example for a while, I can see why this would be nice.

Maybe would also be cool if it could accept a column name if you had something that looked like this:
````python
p.multi_line(source=ColumnDataSource(multiline_df), xs='xs', ys='ys', color='color', tags='legend')
````

**Comment by jisantuc** [comment]
Playing around today, would like to revive interest in this feature if possible. This does not appear to be a feature in 0.11 but makes a ton of intuitive sense, along the lines of passing a `factor` variable into `ggplot`.

**Comment by bryevdv** [comment]
So, @mattpap is doing some work (currently on a brief pause for other priorities), to improve selection handing and hit testing, and one of the things that will fall out of that is an "interactive legend" that has been often requested. Let's let all that work itself out, and then afterwards we can see how it might be possible to special case `MultiLine` and `Patches` without upsetting anything else.

**Comment by bryevdv** [comment]
@birdsarah does on of your open PRs allow for legends on multiline?

**Comment by birdsarah** [comment]
Yes, although I am 99% sure it wouldn't work for this specific use case. 

I think this is a natural follow-on feature though (and not just for multi_line).

At the moment the PR has a background assumption that someone passing a column name into legend call is an "advanced" user and basically only tries to look up a column name if the user has passed in a source into the glyph renderer function.

So it doesn't handle when users just pass in lists of data into glyph renderer and the source gets created for them. I had already thought it through a little and believe it would be a trivial addition, but I thought it would be better to get the core functionality in first to keep what is now a string of 5 PRs as reviewable as possible....plus it was 4am if I recall correclty :)

**Comment by birdsarah** [comment]
So when I said "Yes" I guess "No" would have been more correct :D

**Comment by spraveengupta** [comment]
Hi,

I am a new user to bokeh facing hardtime in getting color legend on multi line plots.
Any help is highly appreciated.

Regards,
Praveen

**Comment by bryevdv** [comment]
There are some new features that make using legends with multi_line possible, see, e.g.:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/multi_line.py

You will need a recent version of bokeh.

@birdsarah I think we can actually close this issue as a result?

**Comment by spraveengupta** [comment]
Hi bryevdv,

Thanks for a quick response.  I am struggling hard to get legend on top of the multi line plot.
Here is my code and output.   I tried many things however could not succeed.  Please help me in resolving this issue. 

```
import pandas as pd
import numpy as np
from bokeh.plotting import figure, show, output_file
from bokeh.models import FixedTicker

numlines=len(StateMktYear.columns)

p = figure(width=600, height=300) 

p.multi_line(xs=[StateMktYear.index.values]*numlines,
                ys=[StateMktYear[name].values for name in StateMktYear],
                 color=['green','red','blue','magenta','black'],
                line_width=2)

p.left[0].formatter.use_scientific = False
# p.legend='abc'
# p.legend.location='bottom_left'
p.axis.axis_label_text_font_size='14pt'
p.axis.axis_label_text_font='Times'
p.axis.major_label_text_font='Times'
p.xaxis.ticker=FixedTicker(ticks=[2012,2013,2014])
p.title='Demand Across Years'
p.axis.major_label_text_color='Black'
p.xaxis.axis_label='Year'
p.yaxis.axis_label='Demand'

show(p)
```

![bokeh](https://cloud.githubusercontent.com/assets/17037233/19195041/da631e8e-8c7d-11e6-8816-bf77b0fef45b.png)

**Comment by bryevdv** [comment]
@spraveengupta please use the public mailing list for general support questions: 

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

The issue tracker is for feature requests and bug reports.

**Comment by bryevdv** [comment]
This issue probably could have been closed but there are some remaining other things lacking with multi-line legends, i.e. they can't easily be put outside plot areas. Am going to re-purpose this issue for those.

**Comment by bryevdv** [comment]
#5303 covers making it easier to put legends outside the plot area, so I am going to close this
