### ISSUE TITLE
Size atribute for line incorrect in tutorials

### ISSUE THREAD

**Issue by MortalCatalyst** [bokeh/bokeh#2542]
I am referring to http://bokeh.pydata.org/en/latest/docs/tutorials/basic.html

```python
p1 = figure(plot_width=300, plot_height=300)
p1.line(x1, y1, size=12, color="red", alpha=0.5)

p2 = figure(plot_width=300, plot_height=300)
p2.line(x2, y2, size=12, color="blue", line_dash=[2, 4])

p3 = figure(plot_width=300, plot_height=300)
p3.line(x3, y3, size=12, line_color="orange", line_width=3)
```

However when I try and run it I receive an attribute error.

C:\Users\sayth\Repos\Bokeh>python lines.py
Traceback (most recent call last):
  File "lines.py", line 24, in <module>
    p1.line(x1, y1, size=12, color="red", alpha=0.5)
  File "C:\Users\sayth\Miniconda3\lib\site-packages\bokeh\_glyph_functions.py", line 37, in func
    glyph = _make_glyph(glyphclass, kwargs, glyph_ca)
  File "C:\Users\sayth\Miniconda3\lib\site-packages\bokeh\plotting_helpers.py", line 140, in _make_glyph
    return glyphclass(**kws)
  File "C:\Users\sayth\Miniconda3\lib\site-packages\bokeh\plot_object.py", line 90, in __init__
    super(PlotObject, self).__init__(**kwargs)
  File "C:\Users\sayth\Miniconda3\lib\site-packages\bokeh\properties.py", line 357, in __init__
    setattr(self, name, value)
  File "C:\Users\sayth\Miniconda3\lib\site-packages\bokeh\properties.py", line 371, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'size' to Line, possible attributes are line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, session, tags, visible, x or y

Has there been an update since the tutorials have been put together?

**Comment by bryevdv** [comment]
There have certainly been, and in particular there has been increased validation. Glyph functions no longer silently accept unknown properties. `size` has never been a property for `line` but was probably there from a copy-paste error. Perviously it was just silently ignored, now providing an unknown argument will raise an exception.

However, we are in the process of moving all the tutorial materials to IPython notebooks on nbviewer.org, so the existing tutorial content will be removed soon in favor of those notebooks. Accordingly, marking this `wontfix`.
