### ISSUE TITLE
Dropdown button example partially hidden in User Guide

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2549]
On the */user_guide/interaction.html* page of the Bokeh docs, the dropdown button example is hidden behind a code block.

<img width="388" alt="screen shot 2015-07-13 at 11 46 18 am" src="https://cloud.githubusercontent.com/assets/1417520/8655237/7b78ecbe-2955-11e5-95b9-88b93a4be55a.png">

**Comment by michaelaye** [comment]
:+1:

**Comment by bryevdv** [comment]
@birdsarah any ideas for a quick fix for this? is it just a `z-value` issue?

**Comment by bryevdv** [comment]
marking as `0.12` because I believe it has been fixed by recent work.

**Comment by bryevdv** [comment]
This is still an issue in `0.12`

**Comment by bryevdv** [comment]
Fixed at some point in `0.12`:

<img width="378" alt="screen shot 2016-06-27 at 8 32 59 am" src="https://cloud.githubusercontent.com/assets/1078448/16381386/ed854744-3c41-11e6-929c-a8456bab0e0f.png">

**Comment by birdsarah** [comment]
pretty sure it was #4651
