### ISSUE TITLE
Support CSS ColorNames in value()

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2560]
My understanding of the value tag was that you can explicitly say that something is not a column name.  As a result I would expect the following to work:

````python
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
from bokeh.properties import value
output_notebook()
f = figure(x_range=(0,3), y_range=(0,4))

f.circle([1], [3], radius=0.2, fill_color=value("LemonChiffon"))  # Does not work
f.circle([2], [3], radius=0.2, fill_color=value("lemonchiffon"))  # Does not work

show(f)
````

See a screenshot on #2559 

But the fill is just white in this case.

**Comment by bryevdv** [comment]
Yup definitely seems like a bug.

**Comment by bryevdv** [comment]
This has been fixed at some point in the recent refactors (see attached screenshot)

<img width="616" alt="screen shot 2015-12-16 at 8 56 36 pm" src="https://cloud.githubusercontent.com/assets/1078448/11860171/8f198bb8-a437-11e5-8a90-79ed116ae7c9.png">
