### ISSUE TITLE
Polar and rectangular coordinate glyphs don't match up?

### ISSUE THREAD

**Issue by cyrusmaher** [bokeh/bokeh#2561]
Here's a link to an example script:
https://www.dropbox.com/s/v8q5cyoqibj3bb3/test_bokeh.py?dl=0

And its output:
https://www.dropbox.com/s/lo9xxutkbk1h9q0/test.html?dl=0

I'm drawing a couple annular wedges and attempting to place rectangles centered within them. I also plot some scatter points to show the rectangular coordinate glyphs are consistent. I've checked my polar to rectangular conversion and it is correct as far as I can tell.

**Comment by bryevdv** [comment]
The "problem" is that the aspect ratio of the central plotting area is not 1-1 but the radius distance (in pixels) has to be measured in one dimension or the other, so things look wrong. Here is some background information:

	https://github.com/bokeh/bokeh/issues/517
	https://github.com/bokeh/bokeh/issues/1883

You can verify this is the case by looking at the two images below. The first is the plot as it is generated, in a 1000x1000 canvas, but with different amounts of padding around the edges causing the aspect ratio to be not 1-1 in the central area. Note in particular that the second annulus appears to extend past the max radius of 2. This is because the radius is measured in the x-direction by default. The second is after I have used the resize tool to resize the canvas until The second annular wedge goes exactly up to 2 on the y-axis. Now the rectangle "look" like they are in the right place. 

This is a fundamentally a mathematical issue, there are only really two options:

* Ensure the aspect ratio is always 1-1 when dealing with any glyphs that have radial dimensions

* Apply skew transformations to "squish" the glyphs appropriately for non-uniform aspects (e.g., circles would show visually as ellipses, not circles)

We re going to make it easier to fix the aspect ratio of the plot area, but the second option is a much longer term idea, if it ever happens at all (it's not clear anyone would want that).

**Comment by cyrusmaher** [comment]
I don't see the images you reference, but the issue makes sense. 

Do you have any recommendation on how to fix the aspect ratio in the meantime? I have the figure dimensions equal already, but I can't find the padding argument. I've also tried setting the axis bounds, but this doesn't seem to have the intended effect...

For what it's worth, I would support the "squish" solution. It seems like anything that restores the natural mapping between rectangular and polar coordinates would help keep the focus on the seamless beauty of the visuals :)

**Comment by bryevdv** [comment]
You can see how to set the minimum border padding here:

	http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#border

Additionally you can modify the tick label formatting and orientation to make sure your tick labels do not overrun the min border:

	http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#tick-label-formats
	http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#tick-label-orientation

It occurs that the "squish" solution could possibly be more easily implemented by mapping data coords to a synthetic 1-1 pixel range, and then applying canvas context scale transformations. That might make a nice PR for a new contributor, please let us know if you would be interested in making a stab at it. 

Bryan

**Comment by cyrusmaher** [comment]
This sounds like it would be my most involved PR so far, but I would consider giving it a shot with appropriate guidance and support.

Note that I'm not able to match up the glyphs by fixing the padding. Resizing can resolve the mismatch, but the ideal aspect doesn't appear to be 1-1 (screenshot below). 

https://www.dropbox.com/s/jbvzc2p1otu1fey/Screenshot%202015-07-14%2015.43.46.png?dl=0

In the meantime, I've found a workaround to avoid mixing polar and cartesian glyphs...

**Comment by bryevdv** [comment]
Can you you describe what you tried, to set the padding? I measured one of the internal grid squares, and the distance on both sides was very nearly equal. It looks like the padding on top is slightly less than the other sides, though.

**Comment by cyrusmaher** [comment]
Below is the relevant snippet from my script. I didn't see a way to set the exact border (as opposed to the minimum)...

```python
plot = bk.figure(width=500, height=500)
plot.min_border_left = plot.min_border_right = plot.min_border_top = plot.min_border_bottom = 20
```

**Comment by bryevdv** [comment]
That's too small, you need to set a minimum that will be *larger* than the space any labels, etc. will occupy. To help control reduce the space the labels occupy you can use the links to formatting and orientation above.

**Comment by cyrusmaher** [comment]
Here's the screenshot for a border of 100. A border of 200 is the same, only smaller:

https://www.dropbox.com/s/k11n0r77xk70yux/Screenshot%202015-07-14%2017.27.35.png?dl=0

**Comment by bryevdv** [comment]
Sorry, you'll also need to set the data bounds to be equal explicitly with `x_range` and `y_range`. By default bokeh tries to auto-range the plot, as you can see the data bounds in your screen shot are not equal (another way to not be 1-1 aspect).

**Comment by cyrusmaher** [comment]
That works! I was looking for the range arguments, but in the axis objects. I found this thread saying that `axis.bounds()` was the way to do it, not `x_range`, but that's old info: 

https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/8lgVFOzot68

**Comment by bryevdv** [comment]
It could probably be explained more carefully but that old thread is corrects. The bounds property controls the extent of where ticks and labels are drawn  on an axis, but the ranges specify the extent of an axis (whether ticks, labels are drawn in that region or not). See

http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#bounds

**Comment by cyrusmaher** [comment]
That makes sense! I think the confusion creeped in from the analogy to `pyplot.xlim`, which is most similar to `x_range` in its effect. Thanks for your help, and for all your hard work with bokeh! In case you're interested, below is a link to the visualization I'm working on. It's an (early stage) visualization of an individual's mitochondrial DNA sequence:

https://www.dropbox.com/s/lo9xxutkbk1h9q0/test.html?dl=0

**Comment by bryevdv** [comment]
That's awesome!

**Comment by fpliger** [comment]
@cyrusmaher that is really cool! Do you mind if I show that as an example during a public talk? (EuroPython conference)

**Comment by cyrusmaher** [comment]
I'm glad you like it!! What's the date of the talk? I brought this up with
my boss, and he is leaning in a positive direction, but hasn't decided yet.
We have a deadline tomorrow, but I should be able to bend his ear again on
Thursday...

**Comment by fpliger** [comment]
@cyrusmaher Sorry for the slow reply, got crushed at conference. It was on Monday so I didn't show anything... in any case I really like it. It'd be good to know for future occasions.. Of course we'll mention who's this work coming from. ;-)
