### ISSUE TITLE
Documents permanently collapsed on bokeh-server index page

### ISSUE THREAD

**Issue by ecprice** [bokeh/bokeh#2562]
When I create a bunch of documents and go to http://localhost:5006/ , I am supposed to be able to click on a document to display the associated plots.  The method for doing so involves using bootstrap to expand the appropriate div.  However, when I click on the document, the plot loads but the enclosing div remains collapsed so it is invisible (using Chrome on Ubuntu).

This appears to have stopped working with a173f6aa38daab9c08545495a05ce732a0f2e78c, which factored bootstrap/jquery out of the header.  Reverting that change fixes the issue for me.

**Comment by bryevdv** [comment]
Thanks for tracing that down. We don't actually install bootstrap into `bokeh.server.static` anymore AFAIK, so I can only assume you just happened to have an old copy around from a previous version somehow (or something). That page is really just intended as a simple engineering UI, so the collapsible div, while nice, does not really add much. We will probably resolve this by making the divs into simple direct links to the plot pages.

**Comment by ecprice** [comment]
It sure looks like it's still there: bokeh/server/static/bootstrap/js/bootstrap.min.js

**Comment by dwf** [comment]
@bryevdv As it turns out this was the same problem as #2787. The issue was apparently that bootstrap's CSS is added but its JS is not. The JS is still there, which is what enables my fix in #2792. It's a nice-to-have if it's not a big deal to keep it around.
