### ISSUE TITLE
reset tool doesn't work with streaming updates

### ISSUE THREAD

**Issue by ecprice** [bokeh/bokeh#2564]
If you having streaming updates, like server/examples/simple_stream.py , the xrange automatically grows to include the new points, which is great.

If you press the reset button, with or without zooming first, it returns to the original xrange, and it no longer seems possible to get the automatically growing range.

**Comment by bill10** [comment]
I have encountered a similar problem, not even with streaming. It seems that resize didn't recalculate the range of data after it was changed and used the range when the plot was created. Is there a way to set the range values for resize?

**Comment by bryevdv** [comment]
When using the recent `follow` property on data ranges, this can now be configured to reset to the end (or beginning) of the current data, instead of the original range. For an example, see:

https://github.com/bokeh/bokeh/tree/master/examples/app/ohlc
