### ISSUE TITLE
Attach a PanTool to a specific range

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2565]
I can add extra ranges to my plot as described here: http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#twin-axes

``` python
p.extra_y_ranges = {"foo": Range1d(start=0, end=100)}
p.circle(x, y2, color="blue", y_range_name="foo")
p.add_layout(LinearAxis(y_range_name="foo"), 'left')
```

I wanted to be able to add a PanTool for just one of my ranges, something like 

`p.add_tools(PanTool(x_range_name='bar', dimensions=['width']))`

When using this pan tool, only the one x_range, and the axes & glyph(s) attached to it would move. The other range/axes/glyphs would not move.

**Comment by bryevdv** [comment]
What is a use case for not having all ranges in one dimension synchronized? This would be a non-trivial change and there has not really been any other interest expressed in it, so I'd like to understand the motivation (or close)

**Comment by bryevdv** [comment]
Have not seen any rationale or wider interest expressed.
