### ISSUE TITLE
output_notebook resources

### ISSUE THREAD

**Issue by tonyfast** [bokeh/bokeh#2572]
I use gist frequently to share notebooks, code and ideas.  ``output_notebook`` uses ``INLINE`` Resources as a default and it creates an enormous file.  Files that are too large in a Gist will require the files to be edited locally and pushed to the Gist repository.

After some digging, I found how to use the ``CDN`` to render the notebooks.  Using the ``CDN`` Resource reduces the file size so that the gist can still be edited online.  

This [Gist](https://gist.github.com/tonyfast/fae0eacea79bbd28996d) describes this issue in a bit more detail.  But, ultimately the ``CDN`` reduces the file size by an order of magnitude for this particular example.

It might be valuable to consider a different default mode for the ``output_notebook`` method or at least provide a warning or message that there is a way to reduce the file size.

**Comment by damianavila** [comment]
This is a valuable observation... not sure about changing the default, but definitely some kind of warning could be added.

**Comment by birdsarah** [comment]
I am in favor of changing the default. I'm not sure what the rational for inline being the default is, but maybe it's "so it's a self-contained document.' 

To my mind, you would typically email that self-contained document to someone, so if they can get the document they can get the resources. I know I was initially shocked at the size of document produced and it took me a while to find mode='cdn.' And I know other users have experienced the same - a recent example: https://twitter.com/birdsarah/status/610451709408739329

I think it's a bad first impression, and it's not like we'd be disappearing the inline version, just changing the default.

On a semi-related note, I'd also love an argument where you could specify the url(s) where your assets live.

**Comment by tonyfast** [comment]
I also agree that the file size is an overarching bad impression judging from some stackoverflow posts I've seen.  If you are sharing a notebook and the limitation is whether Gist or Nbviewer can use it then the file does not need to be self contained.

Specifying other Url(s) for assets would be a great way for people to create reusable and portable style sheets.

**Comment by bryevdv** [comment]
I think I am being persuaded to support changing the default.

**Comment by damianavila** [comment]
As I said... I am not sure... but if a lot of people is asking for that, probably is something to change...

**Comment by birdsarah** [comment]
I should have said, my observations come from output_file, where I'd like to see the default be 'cdn.' But I can imagine the same arguments applying for output_notebook.

**Comment by birdsarah** [comment]
@damianavila you said "I am not sure" - can I ask why? I'd be curious to know what the thoughts were behind the original 'inline' default.

**Comment by bryevdv** [comment]
The motivation was exactly to have self-contained documents that are guaranteed to always work.

**Comment by damianavila** [comment]
> The motivation was exactly to have self-contained documents that are guaranteed to always work.

Essentially... there are potential scenarios where the connectivity is not guaranteed and having a self-contained document could be a solution... but I understand that maybe those scenarios are less frequent as time goes...

**Comment by bryevdv** [comment]
@damianavila or @birdsarah can one of you pose the question on the mailing list to solicit feedback?

**Comment by birdsarah** [comment]
on it.

**Comment by birdsarah** [comment]
done.

**Comment by schaunwheeler** [comment]
Just saw the link to this issue in the mailing list. I'm in favor of changing the default. Bokeh operates within a web browser, therefore it's fair to assume an internet connection. It's nice to have INLINE for when that assumption is false, but as an exception, not a rule.
