### ISSUE TITLE
Is there a way to see if a plot is "interacting?"

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2575]
Hi,

I'd like to trigger an event after someone's done interacting with a plot e.g. finished panning, so that not too many events are generated.

I feel like the level-of-detail work might have done some kind of detection like this - is there any state or event exposed externally?

Thanks,

Bird

**Comment by bryevdv** [comment]
Well, that work applies some rules of thumb and tunable parameters. How do you know when a pan is "over" exactly? Anyway right now tools set an "interctive timestamp" on the plot, that can be compared against the configurable timeout. You can see it here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/plot.coffee#L198

It would certainly be nice to factor it out into something more general/re-usable.

**Comment by bryevdv** [comment]
There is now the `lod_start` and `lod_end` events which are  available to `on_event` and `js_on_event`. These roughly correspond to when interactive actions are happening. If that is not sufficient please feel free to re-open.
