### ISSUE TITLE
draw_path not implemented when plotting Cartopy map

### ISSUE THREAD

**Issue by jclark754** [bokeh/bokeh#2580]
Hello, I am trying to use `show(mpl.to_bokeh())` when plotting a map using cartopy/matplotlib. When plotting using matplotlib, the following image is returned:
![figure_1](https://cloud.githubusercontent.com/assets/8108300/8751870/41eb1d9e-2c6d-11e5-830b-7cf7f692982d.png)

Using `show(mpl.to_bokeh())` instead of `plt.show()` results in a not implemented error here:
 `File "bokeh/mplexporter/renderers/base.py", line 365, in draw_path raise NotImplementedError()'`
The line that actually causes this issue is `ax = plt.axes(projection=ccrs.PlateCarree())`, when the map projection is drawn. 

I've seen PR #2543 where @bryevdv suggested implementing `draw_path` in the renderer and was wondering what the status was on this particular thought.

**Comment by bryevdv** [comment]
Closing this, as no further MPL compat work will be done until the upstream MEP 25 for a robust JSON serialization is implemented b. y the MPL project
