### ISSUE TITLE
ColumnDataSource.from_df class method doesn't return ColumnDataSource instance

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2581]
The ColumnDataSource from_df method is described in the docs as a class method, but it doesn't return a ColumnDataSource class but a dict "suitable for creating a ColumnDataSource". We should clarify the docs to express that it's a static method or actually have it return a class instance.

**Comment by colinfang** [comment]
I agree. For the moment we have to do `ColumnDataSource(ColumnDataSource.from_df(df))` which is a bit odd.

I would like the constructor of `ColumnDataSource` itself can deal with `df`, i.e. call `from_df` if it is a pandas dataframe

**Comment by birdsarah** [comment]
Can you clarify, @colinfang `column_data_source_df = ColumnDataSource(data_frame)` works just fine.

http://nbviewer.ipython.org/github/birdsarah/europython-2015-bokeh/blob/master/notebooks/ColumnDataSource.ipynb

**Comment by colinfang** [comment]
@birdsarah I am wrong. Thought `ColumnDataSource` only accepts a dict

**Comment by canavandl** [comment]
@colinfang I did too...

**Comment by birdsarah** [comment]
Why would you know, there's nothing in the docs that would indicate otherwise :( - I can only imagine that at some point in the past I passed it something random and got the error message `ValueError("expected a dict or pandas.DataFrame, got %s" % raw_data)`.

Definitely needs better documentation for instantiating too.

**Comment by canavandl** [comment]
Sarah is correct that (for at least 0.9.1), the ColumnDataSource __init__ method will accept a pandas.DataFrame object and return a CDS instance. I'll update the docs to reflect this shortly.

The other issue is what to do with the from_df method. We can: 
1. update the docs to describe it as a static method that returns a dict
2. change to code to make an actual class method (return a CDS instance)
3. remove the method entirely

I'm leaning towards option 3, unless people actually use the dict that the method returns. Option 2 seems to unnecessarily junk up the class and just copy the init method. Thoughts?

**Comment by bryevdv** [comment]
well, the initializer uses the dict it returns. So removing it would probably mean renaming it:
```
    @staticmethod
    def _data_from_df(df):
        pass

    def __init__(self. *args, **kw):
        # uses _data_from_df
```

**Comment by canavandl** [comment]
Yes - I think making it a private method that init uses seems to be the way to go.

**Comment by stauntonjr** [comment]
Was that method removed? It still "works" in Bokeh 1.2.0 and still returns a dict instead of a bokeh.models.sources.ColumnDataSource

**Comment by bryevdv** [comment]
@stauntonjr I don't really understand which method you are asking about. `from_df` returns a dict, as intended and documented, and has done so for many years now.
