### ISSUE TITLE
Slow plot rendering for 0.9.1

### ISSUE THREAD

**Issue by avanetten** [bokeh/bokeh#2582]
The time to render plots has increased ~7x in version 0.9.1 compared to previous versions.  I have a script to create a few plots which I'm running in Bokeh 0.9.1.  Commands are below

############
# Version 0.9.1
From the command line:
ipython

Within ipython:
In[1]: import bokeh
In[2]: print bokeh.__version__
0.9.1
In[3]: %paste   # plotting commands, with a timer
Time to create plots: 30.4073710442 seconds

###########
# Reverting back to Bokeh version 0.9.0
From the command line:
conda install bokeh=0.9.0
ipython

Within ipython:
In[4]: import bokeh
In[5]: print bokeh.__version__
0.9.0
In[6]: %paste   # exact same plotting commands, with a timer
Time to create plots: 4.40002202988 seconds
############

The resulting plots are the same, save for the much longer rendering time for the newest version of Bokeh.

**Comment by birdsarah** [comment]
It's going to be hard to look at this without your plotting code. Can you provide a sample?

**Comment by bryevdv** [comment]
Can you provide some code to reproduce? As well as information about platform, browser, etc? This will require investigation and anything to help focus the effort is useful.

**Comment by birdsarah** [comment]
too slow @bryevdv  :)

**Comment by bryevdv** [comment]
For reference: https://github.com/bokeh/bokeh/compare/0.9.0...0.9.1

A quick scan for changes under `bokehjs` didn't turn up anything that potentially looked like it could be a clear culprit. Doesn't mean there is not a culprint, but more information will definitely be needed to look at this.

**Comment by avanetten** [comment]
The exact script is quite long.  But the script below reproduces some the speed discrepancy, with Bokeh 0.9.0 ~3x faster than 0.9.1.  Basically, I'm just appending a bunch of circles and segments to a Plot object.  I'm using plots instead of figures because I'd like to update the ColumnDataSource within bokeh-server.  Platform is OS X 10.9.5.



    # -*- coding: utf-8 -*-
    """
    Created on Fri Jul 17 13:24:01 2015
    
    @author: avanetten

    ################
    Timing Stats (0.9.0 is faster than 0.9.1)
    
    conda install bokeh=0.9.0
    0.9.0
    Time to plot with Bokeh: 0.302934885025 seconds
    
    # conda update bokeh
    0.9.1
    Time to plot with Bokeh: 0.972449064255 seconds
    ################
    """

    import numpy as np
    import bokeh.plotting as bk
    import time
    import bokeh
    from bokeh.models import (
        Plot, LinearAxis, Grid, DataRange1d,
        PanTool, WheelZoomTool, BoxZoomTool, ResetTool, PreviewSaveTool)
    from bokeh.models.glyphs import (Circle, Segment)
    
    # initialize 
    numE = 20000
    numN = 20000    
    plot_height = 800
    plot_width = 1000
    title = "Timing Test"
    htmlout = "Timing_Test.html"
    
    # circles
    nodex = np.random.random(numN)
    nodey = np.random.random(numN)
    nsize = 5*np.ones(numN)
    ncolor = numN*['blue'] 
    nalpha = numN*[0.5]  
    nid = [str(i) for i in np.arange(numN)]
    
    # lines
    ex0 = np.random.random(numE)
    ex1 = np.random.random(numE)
    ey0 = np.random.random(numE)
    ey1 = np.random.random(numE)
    ewidth = np.ones(numE)
    ecolor = numE*['red'] 
    ealpha = numE*[0.3]  
    eid = [str(i) for i in np.arange(numE)]
       
    # ColumnDataSources
    nsource = bk.ColumnDataSource(
        data=dict(
            nid=nid,
            x=nodex,
            y=nodey,
            size=nsize,
            color=ncolor,
            alpha=nalpha
        )
    )    
    esource = bk.ColumnDataSource(
        data=dict(
            eid=eid,
            ex0=ex0, ey0=ey0,
            ex1=ex1, ey1=ey1,
            ewidth=ewidth,
            ecolor=ecolor,
            ealpha=ealpha
        )
    )  
    
    # plot
    ################
    # Start timer
    t0 = time.time()
    ################
    
    x_range = DataRange1d()
    y_range = DataRange1d()
    plot = Plot(x_range=x_range, y_range=y_range,
             plot_width=plot_width, plot_height=plot_height, title=title)
    plot.add_tools(PanTool(), WheelZoomTool(), BoxZoomTool(), 
                   PreviewSaveTool(), ResetTool())   
       
    # edges
    seg = Segment(x0="ex0", y0="ey0", x1="ex1", y1="ey1", \
            line_width="ewidth", line_color="ecolor", \
            line_alpha="ealpha")
    seg_glyph = plot.add_glyph(esource, seg)
        
    # circles
    circ = Circle(x="x", y="y", size='size', fill_color="color", \
            fill_alpha='alpha', line_color=None)
    circ_glyph = plot.add_glyph(nsource, circ)
            
    # save
    bk.output_file(htmlout)
    bk.save(obj=plot)
    
    ################
    # End Timer
    print bokeh.__version__ 
    print "Time to plot with Bokeh:", time.time() - t0, "seconds"
    ################
    
    # show
    bk.show(plot)

**Comment by bryevdv** [comment]
I can confirm a 3-4x slowdown on my machine with casual testing. The file sizes do not seem different:
```
-rw-r--r--  1 bryan wheel  3.4M Jul 17 13:57 090timing-cdn.html
-rw-r--r--  1 bryan wheel  4.9M Jul 17 13:46 090timing.html
-rw-r--r--  1 bryan wheel  3.4M Jul 17 13:57 091timing-cdn.html
-rw-r--r--  1 bryan wheel  4.9M Jul 17 14:08 091timing.html
```
So guessing it is some machinery in BokehJS proper. But it could also be a dependency was changed/updated so that will have to be looked at as well. 

@damianavila it's probably time to start thinking of how to integrate some basic performance metrics reporting into our testing/automation. Just a few sanity checks to know if performance has strayed out of bounds.

**Comment by bryevdv** [comment]
To add, I also see a problem with wheel zoom on this plot. It blanks, and then zooms. Box zoom seems to work ok.

**Comment by birdsarah** [comment]
I had a really quick look, the expensive line seems to me to be `bk.save(obj=plot)`

I tried removing the validation and it had no effect.

The new components feature?

**Comment by bryevdv** [comment]
So this is actually a good question, I was looking into possible changes in BokehJS, however, after some experimentation I would actually be somewhat surprised if the issue is in BokehJS. Will start poking around the serialization machinery.

**Comment by bryevdv** [comment]
And duh, of course it's not BokehJS, that's not what the timing was even measuring....

Looks like its the new `NaN` handling/checking:
```
bryan@0199-bryanv  /tmp $ python -m cProfile -s cumtime foo.py
0.9.2dev-bfab8ca-75-g133932b-dirty
Time to plot with Bokeh: 0.7666819095611572 seconds
         2103195 function calls (2079398 primitive calls) in 2.346 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    671/1    0.016    0.000    2.356    2.356 {built-in method exec}
        1    0.001    0.001    2.356    2.356 foo.py:18(<module>)
        2    0.001    0.000    1.526    0.763 io.py:268(save)
        2    0.007    0.003    1.525    0.763 io.py:329(_save_helper)
        2    0.006    0.003    1.506    0.753 embed.py:175(file_html)
        2    0.000    0.000    1.472    0.736 embed.py:37(components)
        2    0.000    0.000    1.183    0.592 embed.py:111(_append_plot)
        2    0.000    0.000    1.183    0.592 document.py:220(dump)
        2    0.000    0.000    1.176    0.588 serialization.py:84(dump)
        4    0.000    0.000    1.171    0.293 sources.py:177(vm_serialize)
        4    0.000    0.000    1.171    0.293 serialization.py:212(transform_column_source_data)
       12    0.268    0.022    1.160    0.097 serialization.py:192(traverse_data)
        1    0.000    0.000    0.831    0.831 io.py:204(show)
        1    0.000    0.000    0.831    0.831 io.py:239(_show_with_state)
        1    0.000    0.000    0.830    0.830 io.py:252(_show_file_with_state)
```
ping @mistakevin perhaps there are some optimizations we can look into

**Comment by bryevdv** [comment]
changing the `nalpha` and `ealpha` lines to use numpy arrays instead of python lists immediate recovers performance:
```
bryan@0199-bryanv  /tmp $ python foo.py
0.9.2dev-bfab8ca-75-g133932b-dirty
Time to plot with Bokeh: 0.22745704650878906 seconds
```
The `NaN` checking on python lists is probably going to be somewhat slow no matter what, but there may be improvements we can make. 

BTW, if you want all the alphas to be the same, just set it to a fixed value. Otherwise it's very wasteful in space and time. There is never a reason to do:
```
ealpha = 0.3*np.ones(numN)
```
I'm assuming your real code does not do that, and has alpha varying per point, but I wanted to mention it just in case.

**Comment by damianavila** [comment]
>@damianavila it's probably time to start thinking of how to integrate some basic performance metrics reporting into our testing/automation. Just a few sanity checks to know if performance has strayed out of bounds.

Yep, I agree... we can probably have some metric in selected examples...

**Comment by avanetten** [comment]
@bryevdv I didn't think to look into the numpy array vs list issue.  Thanks for the catch!   

In the newest version, I've often seen the non-fatal error of not all elements in ColumnDataSource being the same length.  I'm guessing that a ColumnDataSource is now essentially a 2-D numpy array, and therefore prefers numpy arrays of the same length as input.

**Comment by bryevdv** [comment]
@avanetten `ColumnDataSource` has always had an implicit assumption of non-raggedness (I tended to think of "cheap `DataFrame` but 2d-array makes sense too). But we do not advertise this assumption well in the beginning, and sometimes the code was forgiving too, but it is less so now.
