### ISSUE TITLE
Allow "?lod=20" in url similar to "?webgl=1"

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#2591]
WebGL can be turned on by the user by adding `?webgl=1` to the url. As pointed out by @mattpap, this could be generalized to allow setting more plot properties. Implementation is not hard. The question is whether we want to.

In situations where there are multiple plots on the same page, this feature does not make sense for properties like `title`. Some properties that *can* benefit:

* tools  - though do we even want users to be able to change the tools?
* plot_width - can be done via resize tool
* plot_height - dito
* toolbar_location
* logo
* lod_factor
* lod_interval: 300
* lod_threshold: 2000 - can be convenient to be able to scale this down on older hardware
* lod_timeout: 500
* webgl

Thoughts?

**Comment by almarklein** [comment]
ping @bokeh/dev , this is something that's fairly easy to implement. The difficult part is deciding whether we want it or not.

**Comment by almarklein** [comment]
@bryevdv any comments? This is something that can be implemented with a few lines of code. Let's make a decision so we can implement or close this.

IIRC you were not a big fan of the `?webgl=1` concept. Thinking about it again, I don't think this feature makes sense for any of the above properties, except those related to performance, which is user specific and cannot be predicted by the developer. E.g. on an older box, it could be helpful if a user could decrease the LOD factor to improve performance, without having to change any code.

I think my proposal would be to only allow `?lod=20` representing the `lod_factor`, and when set will set `lod_threshold` to 0.

**Comment by havocp** [comment]
* Another possible (conflicting? perhaps not?) use of the URL params is to let server apps use them, especially in scenarios like the happiness demo where there's another web app gatewaying the Bokeh app.

* Is the idea here that there would be some sort of buttons or similar for users to use to set these values? Or is it that when embedding, the embedding page would choose ? Something else? Or is it that users would edit the URL by hand? That last one (add the options by hand) seems least compelling to me; I'd expect the feature to be very rarely used in that case.

* I'm not sure what the pedantic rules are for query params vs `#fragment` but this seems a little more like something that should be in a fragment or perhaps a cookie, to me... can query params be changed without reloading the page for example ? Not sure.

**Comment by almarklein** [comment]
> Another possible (conflicting? perhaps not?) use of the URL params is to let server apps use them, ...

You can provide multiple query params, so it should not be conflicting unless we choose our names wrong.

> Is the idea here that there would be some sort of buttons or similar for users to use to set these values? Or is it that when embedding, the embedding page would choose ? 

When embedding or providing ui elements to set these properties, the calling code would have enough control to set things directly, so I guess this leaves it to allowing users to edit the URL by hand. The use case is that a user has a plot (which might or might not be created by herself) with a lot of points, and this would allow rendering it with WebGL (or with a lower LOD) to improve performance.


> can query params be changed without reloading the page for example ?

No.

>  ... this seems a little more like something that should be in a fragment 

I've looked at that when added `?webl=x`, but this did not really work, IIRC this was because a browser wont reload the page when only the `#frament` is changed, and this is a feature that needs to be picked up at plot initialization.

**Comment by almarklein** [comment]
Made a wiki page to collect ideas and thoughts:
https://github.com/bokeh/bokeh/wiki/Use-of-the-query-string-in-url-to-control-plot-properties

**Comment by bryevdv** [comment]
I think we will have to remove `webgl=1` to support breaking the webgl code out of the core library.  In which case there would be no remaining examples to emulate, and I'd be more inclined to drop this idea for simplicities sake. 

@bokeh/dev  ?
