### ISSUE TITLE
Update HoverTool's documentation with field formatting, etc.

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#2595]
This should include:
- [ ] formatting options (just copy or link documentation from `NumeralTickFormatter`)
- [ ] ability to reference complex field names using curly brackets, e.g. `@{My Field}`
- [ ] support for HTML templating

Perhaps formatting options should be moved to common location and just referenced from all other locations (there are at least three: tick formatter, hover tool and data table).

**Comment by bryevdv** [comment]
This is long overdue.
