### ISSUE TITLE
How to view plot on server

### ISSUE THREAD

**Issue by sc151491124** [bokeh/bokeh#2608]
I have run some examples that given in code, and the figure can show correctly. I wonder know how to view figure on IP:Port/bokeh. I want to show the figures to others and hope they can visit IP:Port/bokeh to  see the figures. I just found some documents in this page but I can do nothing but delete the document. Please help. Thanks!

**Comment by damianavila** [comment]
Related with #390, #2652, #2290
Can you see it one of this issue represent what you actually see?

Thanks!

**Comment by azjps** [comment]
I've had this problem (presumably the same one described by OP) for a long time and assumed it was something wrong with my setup, it looks most similar to the issue presented in [#2562](https://github.com/bokeh/bokeh/issues/2562). I have to admit that it made it pretty confusing how to start using bokeh-server. The only thing I wanted to add was that I get an error in the JS console when I click on one of the "bokehdoclabel" links:

```javascript
bokeh.js:41195: if (mod.Collection == null) {
Uncaught TypeError: Cannot read property 'Collection' of undefined
29.Collections @
bokeh.js:411954 7.load_models @
bokeh.js:43657(anonymous function) @
bokeh.js:5501117.jQuery.Callbacks.fire @
bokeh.js:3078217.jQuery.Callbacks.self.fireWith @ bokeh.js:3089417.jQuery.extend.Deferred.jQuery.each.deferred.(anonymous function) @ 
bokeh.js:3098417.jQuery.Callbacks.fire @
bokeh.js:3078217.jQuery.Callbacks.self.fireWith @ 
bokeh.js:30894done @
bokeh.js:3594717.jQuery.ajaxTransport.send.callback
```

**Comment by maccallum** [comment]
I'm currently having this problem running bokeh-server on an Ubuntu box and trying to view from a Mac on the same network. I start bokeh-server like this:
```
$ bokeh-server --ip xxx.xxx.xxx.xxx &
```

and then run my python code which looks like this:
```
from __future__ import print_function

import signal
import pyuv
import numpy as np
from bokeh.plotting import figure, show, output_server, cursession

output_server("CPULoadAverage", url="http://xxx.xxx.xxx.xxx:5006")
cursession().publish()

colors = ["red", "green", "blue"]
names = ["y1", "y2", "y3"]
legend = ["1 min", "5 min", "15 min"]
ds = []
p = figure(width=1000, height=500, title = "CPU Load Average")
for i in range(0, 3):
    p.line([], [], color = colors[i], name = names[i], legend = legend[i])
    ds.append(p.select(dict(name = names[i]))[0].data_source)
    
counter = -1

def timer_callback(timer_handle):
    global counter
    la = pyuv.util.loadavg()
    counter = counter + 1
    for i in range(0, 3):
        ds[i].data['x'].append(counter)
        ds[i].data['y'].append(la[i])
        cursession().store_objects(ds[i])
        cursession().publish()

loop = pyuv.Loop.default_loop()

timer = pyuv.Timer(loop)
timer.start(timer_callback, 0, 1)

show(p)
loop.run()
```

I'm running bokeh version 0.9.2 and Python 2.7.10

**Comment by maccallum** [comment]
I just rolled back to bokeh 0.8.2 and the problem doesn't exist---everything works as expected.

**Comment by ktrapeznikov** [comment]
I am having the same issue with 0.9.2. It works fine on OS X as localhost. However, when I deploy to a linux server, the links do not work on the index page. However, if I manually construct the url with the doc_id then the page is there.

**Comment by bryevdv** [comment]
Fixed in recent PR

**Comment by damianavila** [comment]
>Fixed in recent PR

For reference #2792
