### ISSUE TITLE
Improve Les Mis example

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#2610]
Two improvements need to be made:

1. Currently, the "non-interacting" squares read out as really really small floats, e.g. "1.27e-123".  We should change these actual values to 0, but also add an ability to suppress the hover tooltip to not display anything for those values.

2. It would be really nice to make the axis labels light up/change color to show when the user hovers over a square, like in the D3 version: http://bost.ocks.org/mike/miserables/

**Comment by bryevdv** [comment]
We can definitely enable hover highlighting with hover policy now. I'm not sure about the small values, that is actually surprising and will need a look.
