### ISSUE TITLE
server error http://bokeh.pydata.org/en/latest/docs/gallery.html

### ISSUE THREAD

**Issue by lac22** [bokeh/bokeh#2612]
The two animated examples 
http://bokeh.pydata.org/en/latest/docs/server_gallery/line_animate.html
http://bokeh.pydata.org/en/latest/docs/server_gallery/aw_animate.html

give internal server errors when you try to run them.

**Comment by damianavila** [comment]
@bryevdv, did you have access to restart this examples? Am I right?

**Comment by jakirkham** [comment]
Also, seeing this.

**Comment by bryevdv** [comment]
@damianavila I have not had time to do the migration to the AWS box yet, I am going to work on it tomorrow.

**Comment by bryevdv** [comment]
I have migrated the apps example to AWS and appear to be working fine. I have hand-editied deployed server gallery to point to these. I have removed the animated examples for now, because there is not currently a good way to automate their re-deploy. I will restore them with the new server work later in September.

**Comment by bryevdv** [comment]
I'll close this issue when I finish a PR later today to update the actual sphinx sources to point to the new locations.

**Comment by bryevdv** [comment]
Also now all the processes are managed by `supervisord`, ostensibly they will respawn in the event of a problem. There's also a small script that will re-recreate the deploy, but I will get that to you OOB.

**Comment by jakirkham** [comment]
@bryevdv, how long does it take before these changes would appear on the website?

**Comment by bryevdv** [comment]
They are there now

**Comment by jakirkham** [comment]
If that's the case, I am getting a 404 error when I visit either link.

**Comment by bryevdv** [comment]
The animated ones have been removed for now (https://github.com/bokeh/bokeh/issues/2612#issuecomment-132309554)

**Comment by jakirkham** [comment]
Oh, sorry. Thanks for setting me straight.
