### ISSUE TITLE
Mocha tests break using Node.js (vs Io.js)

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#2629]
`jsdom` v 4+ does [not work with Node](https://github.com/tmpvar/jsdom#install), which is breaking our Mocha tests when ran. Unless we are running Io.js somewhere, we should switch to [`node-jsdom`](https://github.com/darrylwest/node-jsdom), at least until the Node.js + Io.js merge, whenever that is.

**Comment by damianavila** [comment]
We are installing gulp in travisCI which intall io.js as a dependency

**Comment by mistakevin** [comment]
Javascript developers feel more comfortable using a javascript package manager like npm to install their packages, and most already have gulp installed using npm. I'm willing to bet that javascript channel is little known (as it was to me) to new contributors. Shouldn't we try to mirror their environments as much as possible with our builds?

**Comment by mistakevin** [comment]
And also, this version of jsdom should work with node and iojs, which will take care of developers in both parties

**Comment by damianavila** [comment]
I think you points are valid ones... it was some time in the past when BokehJS live as standalone package... I think that's make sense, and that would solve all the issues you raised, but I also know that in the past it was very difficult to make all this work. I guess that after 1.0 we can convince @bryevdv to make that step :stuck_out_tongue_winking_eye:

**Comment by bryevdv** [comment]
There's nothing that stops JS devs from using `npm` to install gulp? The conda packages are a concession to CIO devs or anyone that wants to use conda, but I don't see how it is a requirement for anyone to do so?

**Comment by damianavila** [comment]
>There's nothing that stops JS devs from using npm to install gulp? 

That's true... people can actually work inside the bokehjs directory as an standalone repo... it is just a matter of ... view. If I am a JS dev and find the JS project inside a python one, I guess I would wondering about the actual value the developers give to that package... it is something about how you present the thing to the world...

**Comment by mistakevin** [comment]
Multilingual (code-wise :wink:) developers will want to keep separate their packaging tools. Keeping up with your path is a nightmare already. I don't think the javascript/ channel in conda should be a prerequisite in developing bokeh, not just because I'm a javascript developer, but because it leaves me out since I have no trace of Io.js on my system but do have the required `gulp` that's needed. I think we were just lucky that `jsdom` was working before, it would have broke if whoever made the `gulp` package had decided to go with node.

**Comment by mistakevin** [comment]
The only other alternative is to ask javascript developers that they have [Io.js](https://iojs.org/en/index.html) installed if they want to be able to run the mocha tests, which is sort of a big ask, IMO.

**Comment by bryevdv** [comment]
FWIW it was a JS dev that put in `iojs` and the current version of `jsdom` IIRC correctly the older/other version of `jsdom` did not work for some reason.

**Comment by mistakevin** [comment]
I don't think using iojs was a mistake, it's just that it now adds the entire iojs platform as a hidden dependency to run the tests. `node-jsdom` works for me, and should work for iojs as well since it's a fork of node. 

Why is it we choose to install some javascript packages with conda and some with npm? It will be easier to maintain if we only use our `package.json`

**Comment by bryevdv** [comment]
I'm happy to entertain any concrete proposals to streamline our JS build/install process.

**Comment by mistakevin** [comment]
The only javascript tool I see installed by `conda` is `gulp` in [_meta.yml_](https://github.com/bokeh/bokeh/blob/master/conda.recipe/meta.yaml#L13), but in [_test_bokehjs.py_](https://github.com/bokeh/bokeh/blob/master/tests/test_bokehjs.py#L12) and [_setup.py_](https://github.com/bokeh/bokeh/blob/master/setup.py#L256) I see references to the `gulp` binary in _node_modules/_, (so we aren't even using the `conda` version) so we could probably just remove it from _meta.yml_ and the `javascript` channel from [_travis_install_](https://github.com/bokeh/bokeh/blob/master/scripts/travis_install#L27), but that would leave us with the `jsdom` problem since we no longer have iojs and node installed concurrently.

But if we go this route with `node-jsdom`, we can assure a new contributor with node or iojs installed that `npm install` in the _bokehjs/_ directory will install all JS deps needed, but `gulp` should still need to be installed globally with `npm install -g gulp` in order to use `gulp` instead of `./node_modules/.bin/gulp` in the command line.

The issue the JS dev was having was probably the same one I was having with back-versioning `jsdom` to 3.x. `npm` isn't recognizing the version tags, so someone forked the `jsdom` repository to continue developing a node version.

**Comment by mistakevin** [comment]
A sudden twist, `jsdom` and `node-jsdom` both depend on `contextify`. `jsdom` with iojs has apparently fixed the problem of `contextify` depending on python 2.7, and breaking on python 3.4, but `node-jsdom` will only work on 2.7. I found a fork of `jsdom` v5 with `contextify` taken out for this reason (and to help windows users). I am trying a build now without `javascript/gulp` and this new `jsdom-nogyp` package.
