### ISSUE TITLE
Dropdown always returning the last menu item...

### ISSUE THREAD

**Issue by ricleal** [bokeh/bokeh#2631]
The Dropdown appears to return always the last menu item no matter which item is selected.
I use ```cb_obj.get('action')``` to get the selected item. I haven't found any other suitable attribute...
I'm using bokeh 0.9.2.

Here some code:

```python
import numpy as np
import bokeh
from bokeh.models.widgets import Dropdown
from bokeh.io import output_file, show, vform
from bokeh.models import Callback
from bokeh.plotting import figure

output_file("dropdown.html")

# Dummy plot, otherwise the Dropdown button is partially hidden...
x = np.linspace(-2*np.pi,2*np.pi,100)
y = np.sin(x)
p = figure(title="Sin(x)", x_axis_label='x', y_axis_label='y')
p.line(x, y)


callback = Callback(args=None, code="""
        console.log(cb_obj)
        var cm_chosen = cb_obj.get('action');
        alert(cm_chosen);
    """)

menu = [("Item %s"%i, "item_%s"%i) for i in range(10) ]
dropdown = Dropdown(label="Dropdown button %s"%bokeh.__version__, type="success", 
                    menu=menu, callback=callback)  

show(vform(dropdown,p))
```

**Comment by bryevdv** [comment]
@ricleal note that with this PR you should use `cb_obj.get('value')`

**Comment by ricleal** [comment]
@bryevdv : Just to let you know that in the new version 0.9.3 the dropdown is working, but your suggestion ```cb_obj.get('value')``` returns ```undefined```. I have kept using the ```action``` attribute.

In the code above, replacing the ```Callback``` by:
```python
callback = CustomJS(args=None, code="""
        console.log(cb_obj)
        console.log(cb_obj.get('value'))
        console.log(cb_obj.get('action'))
        var cm_chosen = cb_obj.get('action');
        alert(cm_chosen);
    """)
```

In the Google Chrome console I have:
```
e {cid: "c-FED011EB2CFA4C93987F0E98AED12BE9", attributes: Object, collection: i, _changing: false, _previousAttributes: Object…}
undefined
item_5
```

**Comment by bryevdv** [comment]
@mistakevin can you make a new issue and fix this section up:

https://github.com/bokeh/bokeh/blob/ba4949061a8f7e7a0633158c650835d61f570090/bokehjs/src/coffee/widget/dropdown.coffee#L58

It's still setting `"action"` instead of `"value"`

**Comment by mistakevin** [comment]
@bryevdv For some reason, I was worried about making a larger change than necessary here, but I agree this makes it easier to understand.
