### ISSUE TITLE
On-demand re-rendering 

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#2639]
When running a bokeh-server via a script, is it possible for one push an update to the current document on-demand? For example, clicking a button widget might lead to loading a large amount of data, during which we might want to set the button's icon set to spinning first and disable the button, then load the data and perform other changes. [See also this post.](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/izMj1gwG8zA)

I can't think of an easy way to accomplish this, since there only seems to be one websocket update sent per from-server-update?

**Comment by azjps** [comment]
Here's a hacky solution: instead of having bokeh-server generate two responses to a single request, instead respond once with the loading animation (here, changing the icon's spin state), listen for this change (with a spin counter), and then perform the rest of response. [See this commit.](https://github.com/azjps/bokeh/commit/0f593d21b409bdddf68d1df4d3e4f299432ac39f) Perhaps some variation of this can already be done?

**Comment by azjps** [comment]
(Ideally we wouldn't have to incur the cost of having these additional request/response cycles, and instead have the ability to publish document updates from the bokeh-server whenever desired.)

**Comment by bryevdv** [comment]
I am working on a comprehensive solution, basically moving to a web socket wire protocol with Tornado server. I will have more information about the design, etc. soon.

**Comment by bryevdv** [comment]
Another planned change: splitting out actual data from Bokeh Models, so that they can be updated independently, and and that doc loads for just models are very fast (all models very lightweight)

**Comment by schaunwheeler** [comment]
All of that changes sound wonderful. Do you have a rough estimate of when those features will be available?

**Comment by bryevdv** [comment]
I think this discussion can be closed. New `bokeh serve` is more performant out of the box, and also already has an initial, much more efficient, streaming API (see `examples/app/OHLC`) with more improvements coming.
