### ISSUE TITLE
sphinxcontrib-napoleon extension loaded incorrectly

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#2651]
I believe in [_sphinx/source/conf.py_](https://github.com/bokeh/bokeh/blob/master/sphinx/source/conf.py#L34), `'sphinx.ext.napoleon'` should be `'sphinxcontrib.napoleon'` as per the [docs](http://bokeh.pydata.org/en/latest/docs/dev_guide/documentation.html#requirements)

**Comment by damianavila** [comment]
"As of Sphinx 1.3, the napoleon extension will come packaged with Sphinx under sphinx.ext.napoleon."

So we need to modified just the doc...

**Comment by mistakevin** [comment]
Probably a better way to go...
