### ISSUE TITLE
Should value() accept None

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2653]
The following example fails with a white screen of death and the JS error:
```
Javascript error adding output!
Error: spec for property 'line_color' needs one of 'value' or 'field'
See your browser Javascript console for more details.
````

````python
import numpy as np
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
from bokeh.properties import value

output_notebook()

theta = np.linspace(0, 8*np.pi, 100)[1:]
x = theta*np.cos(theta)
y = theta*np.sin(theta)

circleplot = figure()
circleplot.circle(x=x, y=y, size=20, line_color=value(None))
show(circleplot)
````

Normally `line_color=None` is serialized as `'line_color': None` in this case, it serializes as `{'line_color': {'value': None},` 

I think the second is more correct and should work and that line_color=None should always serialize to `{'line_color': {'value': None},`

**Comment by canavandl** [comment]
With the properties refactor by @bryevdv this has been resolved.

line_color=None is serialized to ``'line_color': {'value': None}`` and the plot renders

<img width="625" alt="screen shot 2016-02-20 at 9 50 06 pm" src="https://cloud.githubusercontent.com/assets/2198981/13200751/1a597b8a-d81c-11e5-9051-2b86e3b5ab05.png">
