### ISSUE TITLE
AjaxDataSource: Should accept 'reload_event' argument 

### ISSUE THREAD

**Issue by srossross** [bokeh/bokeh#2655]
Currently the `bokeh.models.AjaxDataSource` is only able to reload the data from a `polling_interval=INT` parameter.

It would be great if the `bokeh.models.AjaxDataSource` object would accept a `reload_event` parameter that could accept choice of `bound_change` or `timer` etc. and listen for these events and reload the data when triggered.

cc @bryevdv

**Comment by srossross** [comment]
This is the code that I am using to mimic this functionality:

How would I implement a `get_source` function to get the data_source here?

```js
    var plot;
    var rangeTimer;
    var fig_id;
    
    function rangeChanged(){
        console.log("rangeChanged!");
        //TODO: get source! how do I do this?
    };
    
    Bokeh.$(function(){
	    var fig_id = "{{fig_id}}";
	    plot = Bokeh.index[fig_id];
	    
	    plot.x_range.on('change:end', function(){
	       if (rangeTimer){clearTimeout(rangeTimer);}
	       rangeTimer = setTimeout(rangeChanged, 500);
	    });
	    
	    plot.y_range.on('change:end', function(){
	       if (rangeTimer){clearTimeout(rangeTimer);}
	       rangeTimer = setTimeout(rangeChanged, 500);
	    });
    
    });

```

@bryevdv

**Comment by bryevdv** [comment]
same comment as the other. At the present, in general I'd favor de-emphasizing the ajax source in favor of real bokeh server apps, or if need be, custom extensions.
