### ISSUE TITLE
AjaxDataSource: Should send Plot meta-data in request

### ISSUE THREAD

**Issue by srossross** [bokeh/bokeh#2656]
Could the `AjaxDataSource` object send meta-data in the ajax request? 

Either by http headers or url parameters. The most useful information would be the plot bounds. this would enable servers to send back only the currently used parts of the dataset.

cc @bryevdv

**Comment by bryevdv** [comment]
Has been no wider interest in this, and not there are other alternatives:

* bokeh server apps
* custom extensions

that could be used
