### ISSUE TITLE
bokehjs: ImageURL GlyphRenderer improvements

### ISSUE THREAD

**Issue by srossross** [bokeh/bokeh#2657]
When running:
```
    source = @model.get('data_source')
    source.set('data', {x: x, y: y})
    source.trigger('change', source)
```

In our use case it would be nice if `GlyphRenderer` had an option to keep the previous glyphs in the plot until all of the new glyphs have been loaded and displayed. 

This would be useful for zooming in a tile server application (like google maps) where the previous images are replaced by the similar images of a different scale. 

cc @bryevdv

**Comment by bryevdv** [comment]
For more context this is about building out a tiled map that uses open layer. The feature for `ImageURL` would basically mean that simple progressive refinement just "always worked". To clarify, this is only for `ImageURL`.

**Comment by bryevdv** [comment]
I believe this work was done, part of @brendancol 's `TileRenderer` additions.
