### ISSUE TITLE
Bokeh CDN doesn't support HTTPS

### ISSUE THREAD

**Issue by wzhd** [bokeh/bokeh#2659]
I just uploaded a plot rendered with `output_file('plot.html', mode='cdn')` to an HTTPS-enabled website. But the plot doesn't show up in Chrome and Firefox. Here is the error message in Chrome:
> Mixed Content: The page at '……/plot.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.pydata.org/bokeh/release/bokeh-0.9.1.min.css'. This request has been blocked; the content must be served over HTTPS.

and in Firefox:
> Blocked loading mixed active content "http://cdn.pydata.org/bokeh/release/bokeh-0.9.1.min.css"1 simple-plot-one.html

Please add support for HTTPS. Many websites have enabled HTTPS and HTTPS can't be selectively disabled for some pages.

**Comment by birdsarah** [comment]
Thanks for reporting this. I think we should support it.

Hopefully you know in the meantime how to host this content yourself so that you can serve your bokeh plots over https. If not, feel free to ask.

**Comment by wzhd** [comment]
Thanks for your quick response! I'm looking forward to it.

(Currently I'm using a http site to make use of the CDN. By using the 'inline' mode I managed to host it over https. However the HTML files usually get quite large, over 1MB, compared to the CDN versions, which are usually less than 200KB.)

**Comment by bryevdv** [comment]
I've started a conversation with the IT folks who will have to help with this. A quick look at the current cloud files interface it's not as simple as just flipping a switch.

**Comment by bryevdv** [comment]
BokehJS is now available through https:

https://cdn.pydata.org/bokeh/release/bokeh-0.10.0.min.js

Next steps, to update the default CDN resources to always use this. I would suggest doing this *after* the new server PR lands to avoid conflicts. 

ping @havocp @damianavila @mattpap

**Comment by wzhd** [comment]
This is wonderful!

**Comment by damianavila** [comment]
> Next steps, to update the default CDN resources to always use this. I would suggest doing this after the new server PR lands to avoid conflicts.

:+1:
