### ISSUE TITLE
bokeh needs migration guide

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#2662]
Even if we don't record migration guide on the go (which we really should), we should at least go through `git log -p examples/{glyphs,plotting,...}` and document all relevant changes. This should be made into a well established procedure for further releases.

**Comment by bryevdv** [comment]
I agree, but not necessarily about the milestone. This is the sort of thing I think a 1.0 release provides as a guarantee. (Which does mean we will need to have policies and tools in place before then)

**Comment by bryevdv** [comment]
Trying to find a sensible place in the docs. Do you have any specific thoughts? If not I am inclined to just make it an optional section at the end of the release notes `.rst` files.

**Comment by bryevdv** [comment]
Would look like this:
<img width="291" alt="screen shot 2015-09-23 at 6 57 45 pm" src="https://cloud.githubusercontent.com/assets/1078448/10062129/02b9a5b2-6225-11e5-9a66-9cb82e85b3d2.png">

**Comment by damianavila** [comment]
I am OK with that...

**Comment by bryevdv** [comment]
OK I pushed this to this to the misc docs branch, @mattpap if you think there is more to say please add to it.
