### ISSUE TITLE
non-selected glyphs changing color as well as alpha

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#267]
From iris.py, nearby circles should be red with low alpha, not blue with low alpha.

![screen shot 2014-01-12 at 11 35 10 am](https://f.cloud.github.com/assets/1078448/1896686/1728f4a6-7bb0-11e3-900d-bfdac2efd4d6.png)

**Comment by bryevdv** [comment]
The *default* policy is to set a fixed color, but this is now configurable in `0.12`:

```
from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers

colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

p = figure(title = "Iris Morphology", tools="box_select")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'

p.circle(flowers["petal_length"], flowers["petal_width"],
         color=colors, fill_alpha=0.2, size=10, nonselection_fill_color="fill_color")

output_file("iris.html", title="iris.py example")

show(p)
```
results in
<img width="130" alt="screen shot 2016-06-27 at 10 41 47 pm" src="https://cloud.githubusercontent.com/assets/1078448/16403195/6a813bd8-3cb8-11e6-8bcc-90e29d704ffe.png">

So, going to close now

**Comment by nscozzaro** [comment]
I'm making a scatter plot, and when I set nonselection_fill_color="fill_color" it throws an error: 
`Bokeh Error 
attempted to retrieve property array for nonexistent field 'fill_color'`

**Comment by bryevdv** [comment]
@nscozzaro For general support questions, please use the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
