### ISSUE TITLE
Slider not visible in plot+slider with output_server

### ISSUE THREAD

**Issue by rmchurch** [bokeh/bokeh#2672]
Perhaps I am using this all wrong. The code below makes a simple plot with a slider. When using output_file, everything works fine. When using output_server, the slider doesn't show up, and the browser error console says "Failed to load resource: the server responded with a status of 404 (not found)".
Do I need to do something more sophisticated like the slider app? (https://github.com/bokeh/bokeh/tree/master/examples/app/sliders_applet). I assumed naively that from the documentation (http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#id4) I just had to change the output_file to output_server ...

![image](https://cloud.githubusercontent.com/assets/1577108/9063291/b585c382-3a94-11e5-9a32-54d5df99d44c.png)

```
#!/usr/bin python

from bokeh.models.widgets import Slider
from bokeh.io import vform#output_file, vform#, show
from bokeh.plotting import figure, show, output_file, output_server

#using output_file, the figure and the slider show up
#output_file("slider.html")

#using output_server, only the figure shows up
output_server('slider')

p =figure()
p.line([1,2,3],[1,2,3])

slider = Slider(start=0, end=10, value=1, step=.1, title="Stuff")

show(vform(p, slider))
```

**Comment by bryevdv** [comment]
Appears to be a bug.

**Comment by bryevdv** [comment]
FYI that 404 is unrelated, it's complaining about a JS source map which is irrelevant to non-developers.

**Comment by rmchurch** [comment]
OK, just to be complete, I am using Bokeh v0.9.0, and have replicated on both OSX and Linux. Also, the sliders app (the sine wave) works fine (no problem using with bokeh-server).

**Comment by rmchurch** [comment]
Updated to v0.9.2 (with conda update bokeh) and the problem persists.

**Comment by bryevdv** [comment]
This pertains to the old server, which has been deprecated and removed and is completely unsupported. The new server now has many examples of simple and complicated widget layouts, both from the project and also from users, closing.
