### ISSUE TITLE
Poor text-wrapping for hovertool

### ISSUE THREAD

**Issue by jcrist** [bokeh/bokeh#2673]
Long strings seem to be only properly wrapped when the tooltip is to the right of the mouse. I could wrap the text manually, but the auto-textwrap in bokeh along with that makes it look odd.

**Example:**

Right:
![wrap_right](https://cloud.githubusercontent.com/assets/2783717/9072548/6f8f1450-3ac1-11e5-9f58-654a138ba704.png)

Left:
![wrap_left](https://cloud.githubusercontent.com/assets/2783717/9072550/7444b1c6-3ac1-11e5-86a9-78336450f5ea.png)

**Comment by bryevdv** [comment]
@jcrist is this still an issue? Can you add an MRE if so?

**Comment by jcrist** [comment]
Yes. On bokeh `0.12.15`:

```python
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models import HoverTool

output_file("toolbar.html")

source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=['aaaaa ' * 100 for i in range(5)]
))

hover = HoverTool(tooltips=[
    ("index", "$index"),
    ("(x,y)", "($x, $y)"),
    ("desc", "@desc"),
])

p = figure(plot_width=400, plot_height=400, tools=[hover],
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)
```

**Comment by bryevdv** [comment]
I think if you have very long tooltip values that falls into the realm of custom HMTL template tooltips. There you can control the output div explicitly with CSS to wrap or have whatever max-width you want.

**Comment by dbdean** [comment]
I think the point of this bug is that it works correctly when the tooltip is on the right, but not when it is on the left. This is clearly a bug, and not just a feature request. This is the same bug as #8052, which is a duplicate of #7991, and is currently affecting me.

**Comment by jsignell** [comment]
I think this is still an issue in bokeh 1.4.0. When the hover text displays to the left it overflows, but when it displays to the right text is wrapped properly. 

![Screenshot from 2020-02-03 17-06-03](https://user-images.githubusercontent.com/4806877/73695223-acc07c00-46a7-11ea-8276-7e5c7ba68f86.png)

![image](https://user-images.githubusercontent.com/4806877/73694975-2d32ad00-46a7-11ea-8940-8b6635fdf453.png)

**Comment by jsignell** [comment]
I think that `left` shouldn't be allowed to be <0 here, but it's not clear to me whether `clientWidth` needs to be smaller too https://github.com/bokeh/bokeh/blob/c1ff8c6fbdd3413dc6e3edf783dc344ea79c7b6d/bokehjs/src/lib/models/annotations/tooltip.ts#L85-L89
