### ISSUE TITLE
Fill in empty docstring for `models.tools.ToolEvents`

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2677]
It probably shouldn't be empty, but I'm not entirely sure what it should say.

**Comment by bryevdv** [comment]
I think maybe this is abandoned cruft that never got used:

https://github.com/bokeh/bokeh/search?utf8=✓&q=ToolEvents

**Comment by bryevdv** [comment]
Well, spoke too soon:

https://github.com/bokeh/bokeh/search?utf8=✓&q=tool_events&type=Code

The idea behind `ToolEvents` is a place were tools can record things like the geometry of a selection. For instance you want to do something with box that a box selection tool draws besides hit testing and selecting points. On the server, maybe kick off some computation. It's not really useful for that yet tho, it would need to have some defined properties added.

**Comment by bryevdv** [comment]
`ToolEvents` is going to go away in favor of the new general events system
