### ISSUE TITLE
Weird artifact on file_html generate docs

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2679]
http://bokeh.pydata.org/en/latest/docs/reference/resources_embedding.html#bokeh.embed.file_html

````python
 template=<Template memory:7f376f9fa5c0>, 
````

![screenshot from 2015-08-05 04 09 42](https://cloud.githubusercontent.com/assets/1796208/9076858/de713874-3b27-11e5-82f9-161d82924531.png)

I understand why it got there, but don't know how we'd fix it.

**Comment by bryevdv** [comment]
I can think of a few ways, Sphinx is amazingly customizable (just terribly documented). We could hook into the auto documented and pick through default args looking for Jinja templates during the early doctree build, or even fix this up with string munging on the output pass. Alternatively we could monkey patch the Jinja template repr during our docs build.
