### ISSUE TITLE
Investigate compiled paths 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#268]
This might be especially useful for markers, and might also allow for code deletion if we can specify the paths in a general enough way. (e.g. have one single "generic marker renderer" that takes a path)

Reference:

http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#canvaspathmethods

**Comment by bryevdv** [comment]
If we are going to be pursuing webGL I am inclined to close this. @pzwang thoughts?

**Comment by pzwang** [comment]
Yeah I think you're right.
