### ISSUE TITLE
Updating glyph style from JavaScript not working

### ISSUE THREAD

**Issue by migdard** [bokeh/bokeh#2682]
Here is a minimal example that triggers the issue. Basically the change of alpha level is not taken into account (same goes for colors).

```
from bokeh.document import Document
from bokeh.plotting import show, vplot, output_file
from bokeh.models import Plot, ColumnDataSource, DataRange1d, Callback
from bokeh.models.widgets import Slider
from bokeh.models.glyphs import Line
import numpy as np

x = np.arange(0, 10)
y = np.random.rand(10)
output_file('test.html')
ds = ColumnDataSource(dict(x=x, y=y))
xdr = DataRange1d()
ydr = DataRange1d()

plot = Plot(x_range=xdr, y_range=ydr, plot_width=400, plot_height=300)


l = Line(x='x', y='y', line_alpha=0.2)

alpha_cb = Callback(args=dict(line=l), code="""
    //alert(line.get('line_alpha')['value'])
    new_alpha = cb_obj.get('value');
    alpha = line.get('line_alpha');
    alpha['value'] = new_alpha;
    line.set('line_alpha', alpha);
""")

alpha_slider = Slider(start=0.0, end=1.0, step=0.1,  title='line alpha', callback=alpha_cb)

plot.add_glyph(ds, l)
doc = Document()
doc.add(vplot(plot, alpha_slider))
show(doc)
```

**Comment by bryevdv** [comment]
Seems like just need to add some plumbing so that the glyph renderer triggers a render when the glyphs update.

**Comment by bryevdv** [comment]
OK it's a little more complicated. Here is a diff that will make it "work":
```
diff --git a/bokehjs/src/coffee/renderer/glyph/glyph_renderer.coffee b/bokehjs/src/coffee/renderer/glyph/glyph_renderer.coffee
index 3a06fe5..b5b83eb 100644
--- a/bokehjs/src/coffee/renderer/glyph/glyph_renderer.coffee
+++ b/bokehjs/src/coffee/renderer/glyph/glyph_renderer.coffee
@@ -44,6 +44,10 @@ class GlyphRendererView extends PlotWidget
     @listenTo(@model, 'change', @request_render)
     @listenTo(@mget('data_source'), 'change', @set_data)
     @listenTo(@mget('data_source'), 'select', @request_render)
+    @listenTo(@mget('glyph'), 'foo', () ->
+        @glyph = @build_glyph(@mget("glyph"))
+        @set_data()
+    )
```
But this is not really a good or appropriate fix. There's definitely a bit more design work to do to clean things up. Some of the model/view relationships need clarification and improvement, and then the right plumbing set up between them.

**Comment by bryevdv** [comment]
@migdard there was one other (subtle) issue BTW.  The code
```
    alpha = line.get('line_alpha');
    alpha['value'] = new_alpha;
    line.set('line_alpha', alpha);
```
does not actually trigger a `'change'` event from Backbone, it detects that the actual object is the same (though it has been modified in place). The PR is a potential short term fix that will work if used correctly (see the example in the PR) but longer term something more clear and robust is desired.

**Comment by migdard** [comment]
Thanks Bryan, works as expected now.

**Comment by bryevdv** [comment]
@migdard just to clarify: you mean you got it to work with the 0.9.2 release? Or with by building BokehJS from the PR?

**Comment by migdard** [comment]
I built BokehJS by merging the PR into 0.9.2 source (commit 298d49e93).

**Comment by bryevdv** [comment]
OK that's what I thought just wanted to make sure :) This PR will probably be in an upcoming 0.9.3 point release in the next few weeks.

**Comment by bryevdv** [comment]
@migdard OK we will continue to make improvements in this area but the code in question should work now in master and upcoming 0.9.3
