### ISSUE TITLE
Our Webgl support does not work very well on Safari

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#2683]
On Safari, our webgl examples do not always work. Not sure if this is a bug of Safari or on our side. Need more datapoints.

Test pages:

* To test that webgl works: https://get.webgl.org/
* To test Bokeh webgl examples: https://dl.dropboxusercontent.com/u/1463853/bokeh/index.html 

Collecting what we know:

* On my OSX 10.6.8 (snow leopard) VM everything works as expected.
* On Sarah's machine (Mavericks) even the simple webgl example crashes Safari. (http://pastebin.com/NMg325hE)
* On Sarah's machine with intel card selected the iris example works, the others not (Program has unset variables error)
* On Sarahs' ipod (Yosemite) webgl works. Bokeh demos not sure (but might be a bit heavy ;))
* On Bryan's machine (Yosemite), webl works, but our Bokeh examples do not.
* On OSX and Chrome, everything works fine (which suggests its not purely a driver issue).

Conclusion so far: looks like something goes wrong between Safari and the driver, and the way we use webgl triggers that (in some situations).

**Comment by birdsarah** [comment]
Clarifications:
* I have not tested bokeh on the ipod. Only webgl support. Sorry for confusion.
* On intel, same errors were visible for all plots. But only iris worked - something different between circle and marker?

**Comment by almarklein** [comment]
Thanks for the clarifications. The circle and marker are the same, except for handling of `angle` (circle has no angle) and `radius` (circle allows radius in screen units). But in these examples we use none of that...

**Comment by jerlich** [comment]
On 10.10.5 with safari Version 9.0.1 (10601.2.7.2) bokeh webgl examples do not work. They don't show any data points. 

On Chrome it works.

The demo at get.webgl.org works.

**Comment by almarklein** [comment]
Documenting a log by @birdsarah 

LINE 10k
```
[Log] Bokeh: setting log level to: 'info' (line10k.html, line 20)
[Log] Program has unset variables: webgl_6937f9130000000f,webgl_178fd8140000000b,webgl_ecf075540000000e,webgl_fbcd74980000000c,webgl_33f7f2340000000d,webgl_21646f7300000008,webgl_84cec75c00000007,webgl_a0bcd92100000034,webgl_14b3a8a000000039,webgl_6369f0cf00000003,webgl_617ecf5200000005,webgl_2878fa3b00000037,webgl_7e01e5970000000a,webgl_b67f40000000003a,webgl_c51fce5a00000001,webgl_aff6441600000002,webgl_5956167000000006,webgl_96ab39a500000009,webgl_878aeb8f00000035,webgl_71adf36600000036,webgl_c8d4af8e00000004,webgl_751b8da600000038 (line10k.html, line 160)
```

SCATTER 10k
```
Program has unset variables: webgl_46b38cd600000009,webgl_d3ccbc5e00000007,webgl_72fa9d4500000005,webgl_6afad0d600000006,webgl_6e850c5500000008,webgl_5030d58b0000000b,webgl_f4f83be60000000a,webgl_5fcb6a4900000003,webgl_5956167000000004,webgl_c51fce5a00000001,webgl_aff6441600000002
```
The message about unset variables is produces by [gloo2.js](https://github.com/vispy/vispy.js/blob/master/scripts/gloo2.py#L311) (a thin oo webgl wrapper). Which seems to indicate some name mangling of glsl variables. Googling that brings up nothing.

**Comment by almarklein** [comment]
For the record, the cause is that in `gloo2.js` the shaders are detached before the info on attributes and uniforms is obtained. See also http://stackoverflow.com/questions/27237696/webgl-detach-and-delete-shaders-after-linking`
