### ISSUE TITLE
Transfer demos from Digital Ocean to AWS

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#2697]
@bryevdv asked me to create a GH issue for this:

Bokeh demos are currently running on the Digital Ocean box 162.243.42.178, e.g.

http://162.243.42.178:9000/v5.0/bokeh/ocean/

The Digital Ocean droplet is called `hugobokehdemos`.  It is an expensive one: 16GB RAM, 160GB SSD.  $160/month, or $2k a year.

We use this one for demos to show off Bokeh.

There is a newer AWS machine where all Bokeh demos should be.

This machine needs its demos (and data) transferred to that AWS system and then this machine needs to be shut down ASAP.

**Comment by ijstokes** [comment]
And please let me know the name of that AWS system once the DO system is taken down

**Comment by bryevdv** [comment]
Targeting next Monday or Tuesday to migrate this and other demos to one AWS box.

**Comment by bryevdv** [comment]
@ijstokes I am done with the DO box it can be shut off.

**Comment by bryevdv** [comment]
new demos are at, e.g. http://demo.bokehplots.com:5006/bokeh/stocks/
