### ISSUE TITLE
plot.text(legend="") results in console traceback and clipped legend rendering

### ISSUE THREAD

**Issue by Lingnik** [bokeh/bokeh#2698]
```python
plot.line(x, y1, legend="Change", line_width=2)
plot.circle(x, y2, legend="Peaks", fill_color="white", size=8)
plot.text(x3, y2, text=y3_data, text_color="blue", legend="x")
plot.text(x3, y2, text=y3_data, text_color="red", legend="y")
```

The legend should have two text glyph entries; x and y. If I render a text glyph before other (normal) glyphs, then all of the legend entries are blank, though space is allocated for them.
![image](https://cloud.githubusercontent.com/assets/478059/9140725/18e71872-3ce8-11e5-863c-e3dcb0c30a80.png)

```python
plot.text(x3, y2, text=y3_data, text_color="blue", legend="x")
plot.text(x3, y2, text=y3_data, text_color="red", legend="y")
plot.line(x, y1, legend="Change", line_width=2)
plot.circle(x, y2, legend="Peaks", fill_color="white", size=8)
```
![image](https://cloud.githubusercontent.com/assets/478059/9140760/43e83380-3ce8-11e5-8cd2-07e817839f78.png)

```
bokeh-0.9.2.js:53135
Uncaught TypeError: text_props.font is not a function
114.TextView.draw_legend @ bokeh-0.9.2.js:53135
87.GlyphRendererView.draw_legend @ bokeh-0.9.2.js:50016
77.LegendView.render @ bokeh-0.9.2.js:48049
50.PlotView._render_levels @ bokeh-0.9.2.js:44183
50.PlotView.render @ bokeh-0.9.2.js:44148
53.later @ bokeh-0.9.2.js:44617
```

The line that I commented here causes the legend to render correctly:
![image](https://cloud.githubusercontent.com/assets/478059/9140651/9d299b88-3ce7-11e5-89b7-0f910a9e00c1.png)

But also, sadly, does not show 'txt' in the color I specified for the glyph:
![image](https://cloud.githubusercontent.com/assets/478059/9140712/01a6b55a-3ce8-11e5-8a22-41226c61716b.png)

**Comment by birdsarah** [comment]
Confirmed on 0.9.2.

**Comment by canavandl** [comment]
So this seems to be two bugs.

First - passing a string (not a single element list) to the text glyph method causes the glyph renderer to try and find the matching column in the ColumnDataSource. When it doesn't find it, a NaN is rendered on the plot. Documentation of this should be improved and perhaps a better error message.

Second - the draw_legend method on the TextView model is broken with the error:
```coffeescript
TypeError: text_props.font is not a function
```
