### ISSUE TITLE
Rendering error on line when super zoomed in.

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2699]
I have a line chart of the IBM data that's in sampledata. 

When I'm super super zoomed in, the rendering gets a bit hairy.

![screencast-3](https://cloud.githubusercontent.com/assets/1796208/9146406/c6bba700-3d5c-11e5-8db8-9481efa8f90e.gif)

code to reproduce: https://gist.github.com/birdsarah/63f5add437d7477e3e93

**Comment by bryevdv** [comment]
I zoomed down to the minutes scale without issue on `0.12dev` (OS X safari) and could no longer reproduce. Closing, but please re-open if it still persists on some platforms.
