### ISSUE TITLE
How to style charts and API confusion from a newcomer

### ISSUE THREAD

**Issue by twiecki** [bokeh/bokeh#2704]
Just starting with bokeh and perhaps there is some value in me sharing my first hurdles.

I want to create a timeseries plot where the lines have different styles (e.g. linewidths). So I thought I'd start with the charts.TimeSeries which comes close. But then I'm not sure how to access the individual lines. I was half-expecting to find `charts.TimeSeries.glyphs` as a dict with all the glyphs that were created. Then I could individually change them as I see fit. Seems like glyphs can be given names if created individually, but I couldn't find how to do that.

I was also a bit confused that `TimeSeries` does not return a figure object, or that I can't seem to find the figure object anywhere.

Anyway, at the core there is the simple question of how to style existing charts but so far I found the API a bit hard to navigate for the above mentioned reasons.

**Comment by damianavila** [comment]
First of all, the chart interface is being discussed and rewritten, so some/several things can change in the future.

Second, you have generic argument to customize general things: http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#id1
Additionally, when you create a chart object, this chart is inherited from the Plot object, so you can access attributes and style things as you do with the plotting API. For instance:

```
import pandas as pd
from bokeh.charts import TimeSeries, output_file, show

AAPL = pd.read_csv(
        "http://ichart.yahoo.com/table.csv?s=AAPL&a=0&b=1&c=2000&d=0&e=1&f=2010",
        parse_dates=['Date'])

output_file("timeseries.html")

data = dict(AAPL=AAPL['Adj Close'], Date=AAPL['Date'])

p = TimeSeries(data, index='Date', title="APPL", ylabel='Stock Prices')
```

and now the `p` object is a plot object and you can access things there for further customization.

Probably @fpliger can give you more insight if you want to customize something specific...

**Comment by twiecki** [comment]
Thanks @damianavila. That `p` object is what I tried to use but couldn't find where the glyphs lived or how to style it further. How would you e.g. change the line style in `p`?

**Comment by damianavila** [comment]
For instance...

```
import pandas as pd
from bokeh.charts import TimeSeries, output_file, show
from bokeh.models import GlyphRenderer

AAPL = pd.read_csv(
        "http://ichart.yahoo.com/table.csv?s=AAPL&a=0&b=1&c=2000&d=0&e=1&f=2010",
        parse_dates=['Date'])

output_file("timeseries.html")

data = dict(AAPL=AAPL['Adj Close'], Date=AAPL['Date'])

p = TimeSeries(data, index='Date', title="APPL", ylabel='Stock Prices')

line = p.select(GlyphRenderer)[0]

line.glyph.line_color = 'blue'

show(p)
```

Hope it helps!

**Comment by twiecki** [comment]
Ah, I found `select()` but then didn't knew I had to pass in `GlyphRenderer`. Thanks!

In general, I don't think styling a plot that was created via a Chart class will be an uncommon pattern so maybe some syntactic sugar will help.

The other issue then is that I actually have multiple lines but since the order of glyphs changes every time I can't identify the one line I want to highlight. Ideally I'd like to name the glyphs created by TimeSeries, e.g. `TimeSeries(data, index='Date', title="APPL", ylabel='Stock Prices', name='aapl')`

**Comment by damianavila** [comment]
>Ah, I found select() but then didn't knew I had to pass in GlyphRenderer. Thanks!

I update the example... to just look for the Glyph... it is more straightforward....

> The other issue then is that I actually have multiple lines but since the order of glyphs changes every time I can't identify the one line I want to highlight. Ideally I'd like to name the glyphs created by TimeSeries, e.g. TimeSeries(data, index='Date', title="APPL", ylabel='Stock Prices', name='aapl')

Right now `TimeSeries` does not accept names for each series... otherwise it will be easy to `select` passing the name, for instance:

```python
        # Keyword arguments can be supplied in place of selector dict
        p.select({"name": "foo", "type": HoverTool})
        p.select(name="foo", type=HoverTool)
```

@fpliger I do not know if you discussed this in the charts meetings, I guess you already talked about this... if it is not the case, I guess this is important to take into account...

**Comment by fpliger** [comment]
@damianavila @twiecki This discussion comes in the right time as we have been discussed this new charts improvements for a long time and are starting an implementation.

We did touch this in our discussions, specially for what concerns the Glyphs datasources but the same can be applied to the glyphs. The "problem" with charts glyphs is that they are not always "just a low level  glyph" because many charts map more then one glyph to the same series and some other charts actually group/aggregate/facet the data... so it's not trivial (at least not always).

> TimeSeries, e.g. TimeSeries(data, index='Date', title="APPL", ylabel='Stock Prices', name='aapl')

The problem with this is that we don't know `data` and we need to have a mapping between data series and the names. It could work if we change `name` to `names` and have it as a `dict` so you can specify {"name_of_series": name_of_tag} but still there are a few implementations details to consider.

That said IMO it needs more thought, but we should definitely make it better for the next API.

**Comment by twiecki** [comment]
@fpliger 

> The problem with this is that we don't know data and we need to have a mapping between data series and the names. It could work if we change name to names and have it as a dict so you can specify {"name_of_series": name_of_tag} but still there are a few implementations details to consider.

Yes, that's what I had in mind. Also, if the colums have names (e.g. because a `DataFrame` was passed) it could just be inferred from there. Problems with duplicates though...

**Comment by twiecki** [comment]
Overall access via `select` feels pretty clunky. I wish there was just some data structure I could directly look at to fetch out what I need.

**Comment by twiecki** [comment]
Another thing I noticed is that apparently you can't pass data sources to Charts, only to figures? Do Charts support callbacks? My expectation was that charts are simply syntactic sugar that create common figures for you.

**Comment by fpliger** [comment]
> Overall access via select feels pretty clunky. I wish there was just some data structure I could directly look at to fetch out what I need. Since there's a limited number of glyphs, would p.lines be unreasonable?

I think it wouldn't work well. Charts don't use only one underlying glyph to build their higher level glyph and supporting an attribute for each glyph type is not straightforward. 

I'm working on the concept of a higher level composite glyph that may be the interface for this(see #2694) or maybe not.. it's really something that needs to be well thought.

> Another thing I noticed is that apparently you can't pass data sources to Charts, only to figures?

Charts and Figures are different things.. the former is a pre-build plot that is fully constructed by you for the most popular types of charts. It's really high level and user don't have have glyph level control over it out of the box. Thus charts have their own data source that is built for you.
Figure, instead, gives user full access to the almost everything you'd have on the glyph level interface... just in a much nicer way. In fact you can create glyphs on a figure and associate as many data sources you want.

They are really 2 different APIs with different goals.

Anyhow, the possibility to pass data sources to charts is something that is being considered (see #2039 for previous discussions) also in the new implementation.


> Do Charts support callbacks?

In which sense? A Chart does not support callbacks as much as a Figure does not support it. But the tools, widgets, etc... provided by the charts interface are the same user by the plotting interface so you should be able to use callbacks on those.

> My expectation was that charts are simply syntactic sugar that create common figures for you.

Yes and no.. there is really many different aspects to consider and the distance from the plotting and the charts interface is getting closer and closer but it's not just a matter of syntactic sugar. For many charts you need to group, compute, facet new data from the data provided by the user (i.e. bar, dots, donut, boxplot, histogram, ...) this, by itself, introduces a lot of aspects to consider. The plotting interface, on the contrary, have no logic.

**Comment by twiecki** [comment]
Thanks for the explanations @fpliger. The design constraints are more clear to me now. FWIW I created my plot now directly using glyphs and the figure interface which is pretty easy to work with.

**Comment by fpliger** [comment]
:+1:
