### ISSUE TITLE
(non-issue) Bokeh plots produce randomly ordered json objects

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#2711]
While typing this issue, I realized that while the json objects are not in a consistent order when sent to the front end, they are considered equivalent by [Canteen](https://github.com/platfora/Canteen) and the hashes will be testable. This is true as long as our examples **do not use random data**, as did the example I was playing with before and had me pulling my hair out. :dizzy_face:

@mattpap @bryevdv

**Comment by mattpap** [comment]
> do not use random data

Our examples use random data and it's unlikely this will ever change. However, our test runner seeds `random` and `np.random`, so you will get the same data and plots for every test run, unless there are other sources of randomness.
