### ISSUE TITLE
Gallery needs grid examples

### ISSUE THREAD

**Issue by michaelaye** [bokeh/bokeh#2724]
Currently one has to find grid plotting in the documentation, i think it would be nice to have a fast findable gallery example.

**Comment by birdsarah** [comment]
@michaelaye. We have some long standing issues to make our gallery & examples much better and I'm certainly hopeful this will happen in the not too distant future #1032 & #1350.

I know it's not the same, but I like to search in the examples folder, which has lots more examples than the gallery.

**Comment by bryevdv** [comment]
Intend to add some sections by basic topic before 1.0

**Comment by bryevdv** [comment]
There's currently two `gridplot` examples and several `row/column` examples. There are other newer issues covering gallery work so I am going to close this old one.
