### ISSUE TITLE
HTML escaping in HoverTool not working

### ISSUE THREAD

**Issue by vsajip** [bokeh/bokeh#2728]
This was reported in #1478 and closed as being fixed on 12 Feb 2015. However, it still appears in 0.9.2: if you have a category label `A & B`, the corresponding tooltip shows up as `A &amp; B`. The PR which supposedly fixed this (PR #1854) fixed a whole lot of issues and none of the related commit messages refer to this specific issue. A search of the diff for `escape` doesn't show up anything which looks like a fix. I might have missed it, of course - I'm not very familiar with Bokeh internals - `replace_placeholders` didn't seem to be doing what might be expected, since it seems to be related to replacing numeric values (I've got a non-numeric category label). Also, of course, I'm getting the wrong result in practice.

**Comment by bryevdv** [comment]
@vsajip I don't see any mention of HTML escaping in #1478? That issue had to do with allowing custom templates instead of the single fixed format that was previously available for tooltips.

**Comment by bryevdv** [comment]
ping @mattpap @mistakevin

**Comment by mistakevin** [comment]
@vsajip Can you post a barebones example?

**Comment by mattpap** [comment]
See tooltips in `glyphs/calendar` as an example.

**Comment by mattpap** [comment]
@vsajip, can you verify that PR #2736 fixes this issue.

**Comment by vsajip** [comment]
@mattpap Thanks for the fast response. I can't actually build BokehJS on my Ubuntu system (because for some reason `npm install` failed to install some things, and that's a rabbit hole I don't have time for right now) but if I make the equivalent changes by hand to bokeh.js , the `&amp;` goes away and is replaced by `&`. So I would say your change fixes the issue - thanks again! I'll leave the issue open but it can be closed when the PR is merged.
