### ISSUE TITLE
DataTables slickgrid api

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#2732]
A few questions regarding the DataTables/slickgrid api. Cursory searches didn't pull up previous discussion for these, but maybe someone knows how to do these without having to make any changes on the bokeh-server side.

* When a selection of a `ColumnDataSource` is made, it would be helpful to [jump to the first highlighted row](https://github.com/mleibman/SlickGrid/wiki/Slick.Grid#gotoCell) in the respective DataTable, otherwise if your data series is long it can take forever to find the highlighted row. I figured there would be a JSCallback that could achieve this but don't know how to get from a reference to a coffeescript view from a model? It would be nice regardless to expose this in the python api.
```python
        self.column_data_source.callback = models.Callback(
            args=dict(data_table=data_table),
            # Update the DataTable to point to the start of the selection
            code="""
              var indices = cb_obj.get('selected')['1d'].indices;
              var min_index = Math.min.apply(null, indices);
              console.log(indices, min_index);
              console.log(table.collection.models[0]);
              // Does not work
              data_table.collection.models[0].grid.gotoCell(min_index, 0);
            """)
```
* Is there support for copy+pasting from highlighted cells in slickgrid? I saw the [csv endpoint PR](https://github.com/bokeh/bokeh/pull/2382) but that would be a round-about way to just copy paste a few non-adjacent highlighted rows.
* The width of the slickgrid index doesn't seem to be draggable. So if the index has large values (for example, any datetime index which uses milliseconds since epoch), the index will not show anything meaningful, and on top of that you can't use copy+paste to figure out the values, but instead have to dig into the html.

If these are not possible now I will at least look into a PR for the first issue, but would like feedback first.

**Comment by datnamer** [comment]
+1 to more interactive slickgrid
