### ISSUE TITLE
Editable Static Figure Parameters

### ISSUE THREAD

**Issue by JoenyBui** [bokeh/bokeh#2733]
Is there any plans to have static html bokeh plots features (such as title, sub title, range, grid on/grid off, etc.) editable in the browser?  

What i've been delivering to my client is a stand along html page with multiple data se embededt inside a single histograms and/or pdfs.  But after using callbacks to switch between x and y datasets, I wasn't able to find a solution to have them edit the figure parameters so they could save it into there report.  Keep in mind I'm talking specifically about static web page.

**Comment by birdsarah** [comment]
Hi Joeny,

Bits of what your talking about may be possible already, maybe not. Can you
describe just one workflow that you imagine a user doing - perhaps for the
simplest case.

If it's going to be in a static page, it'll certainly require some JS from
you.

There are some plans for some work on something that will let users compose
bokeh dashboards etc. more readily. But that's not the same as what you're
asking, which seems to be users customizing charts and have some way of
capturing & reloading that state.

Best,

Bird

**Comment by JoenyBui** [comment]
Sarah,

I'm sure you're right that it's probably possible to inject javascript from the html components to the bokeh figures, but I was just thinking it would be noce to have bokeh link the components with python instead of injecting javascript.

The simple use case would be to add a text box and statically link it with the title of the figure.  Maybe there something I overlooked and its quite possible to do this easily.

But ultimately I think it would be great to have the user being able to have excel like control over the plot by editing specific parameters on how the plot is displayed.  Like adding legend or grids, changing colors, etc.... This would have to be build into BokehJS, because it is client side.  

Joeny

**Comment by birdsarah** [comment]
Sorry, I read this on email and thought it was a general question from the mailing list, not a feature request. So you mean you have a text box, that's generated independent from bokeh, just from your normal html template/code and then you make a client-side connection to your bokeh plot with it?

If yes, I totally understand the desire. I think lots more specifics would need to be fleshed out. And I'm also wary that the holy grail of BI software for a long-time has been the ultimate user configurable report.

**Comment by bryevdv** [comment]
I realize this is an old issue. As a concrete proposal, I would say that a simple and comprehendible thing would be to make sure any HTML query parameters are easily available to a "Doc init" callback, and then that callback could do whatever customization is desired based on those values. The doc init callback is still an open feature but I will link it here now and make note that this is requested as patrt of that work (and close this old discussion)

ref: https://github.com/bokeh/bokeh/issues/4272
