### ISSUE TITLE
Bug in vplot/hplot children argument

### ISSUE THREAD

**Issue by jxramos** [bokeh/bokeh#2740]
The small code snippet came from a small use case of mine where sample is a pandas dataframe and I'm iterating through the columns to render channel plots vs the time parameter, with time vs time left in for simplicity of the example.

    channelPlots = []

    for channel in myChannels :
        channelPlot = figure( width=1000, height=1000 , title=channel+ " Time Series" , x_axis_label = channel , y_axis_label = "TIME" )
        y           = sample.data['TIME' ]
        x           = sample.data[channel]
        channelPlot.scatter(x,y)
        channelPlots.append(channelPlot)

    # With a grid it works  
    #grid = GridPlot(children=[channelPlots], title="Time Series Channel Plots")

    # with a vplot it breaks
    grid = vplot( channelPlots )
    save(grid)

    Exception error is: expected an element of List(Instance(Widget)), got [[<bokeh.plotting.Figure object at 0x0000000009AA2128>, <bokeh.plotting.Figure object at 0x0000000006778CF8>, <bokeh.plotting.Figure object at 0x0000000011894C50>, <bokeh.plotting.Figure object at 0x00000000118DE390>, <bokeh.plotting.Figure object at 0x00000000118DEF98>, <bokeh.plotting.Figure object at 0x00000000118F2668>, <bokeh.plotting.Figure object at
0x00000000118EE7B8>, <bokeh.plotting.Figure object at 0x00000000118EE630>]]

and attempting both of these below threw the same exception...

    grid = vplot(children=channelPlots)
    grid = vplot(children=[channelPlots])
    Exception error is: Viewable object got multiple values for keyword argument 'children'

Same story using hplot

**Comment by birdsarah** [comment]
I'm not sure but it looks like it got a list of lists instead of a list,
which is what it was expecting - as per the error.

See:
https://github.com/bokeh/bokeh/blob/0c78cf646ec95d3c003c714c35a388db4b4ad834/examples/plotting/file/rect.py#L28

to call vplot, I think you need to pass all the plots as arguments not as a
list. Have you tried

grid = vplot(*channelPlots)

**Comment by jxramos** [comment]
Yep the argument unpacking method worked.
All of this begun on StackOverflow
http://stackoverflow.com/questions/32061861/how-to-send-list-of-figures-into-bokeh-vplot

I guess it was assumed just throwing the list at vplot should be supported?

**Comment by bryevdv** [comment]
This will all be superseded by the new layout work, closing this particular discussion.
