### ISSUE TITLE
BokehJS - Plumbing for updating views after model attribute update. Example: grid_line_alpha vs. grid_props.

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#2758]
When trying to manually update `renderer.grid_line_alpha` from JavaScript, I was not able to get the plot to successfully refresh.  With Bryan's help, I ended up updating `grid_props.alpha.fixed_value`.

This issue is larger than grid_line_alpha, its more than about view updates from model attribute updates.

I'm using the following hacky JS to update grid_line_alpha:

```
/**
 * Finds and returns grid renderer of specific plot
 */
B.getGridRenderers = function(tagName) {
    var plot = B.getPlotByTag(tagName);
    var gridRenderers = [];
    $.each(plot.renderers, function(index, value) {
        if (value.hasOwnProperty("grid_props")) {
            gridRenderers.push(value);
        }
    });

    return gridRenderers;
};

/**
 * Change Grid Alpha Property
 */
B.updateGridAlpha = function(tagName, val) {
    var plot = B.getPlotByTag(tagName);
    var renderers = B.getGridRenderers(tagName);

    $.each(renderers, function(index, value) {
        value.grid_props.alpha.fixed_value = val;
    });

    plot.request_render();
};
```

**Comment by bryevdv** [comment]
Nearly certain this is covered by work in the last year

**Comment by hyamanieu** [comment]
Is it documented how to change/update views dynamically? I am looking for a way to go from LinearAxis to DateTimeAxis dynamically (similar to #2765), but there is no documentation.
Thank you.

**Comment by pmicheletty** [comment]
+1 for this. Are there any examples of updating axes dynamically? I can't seem to get it to work

**Comment by bryevdv** [comment]
@hyamanieu @pmicheletty respectfully, please try to stay on-topic on issues. The OP has nothing to do with axes.
