### ISSUE TITLE
Resolve misleading property names in `Bokeh.index[<item_id>].renderers` and `Bokeh.index[<item_id>].model.renderers`

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#2759]
BokehJS: On of these are renderers, and the other are renderer_views.  Confusing names should be resolved

**Comment by bryevdv** [comment]
It's specifically `PlotView` that stores all the renderer views as `plot_view.renderers`

**Comment by birdsarah** [comment]
Hi, this is a change I've made as part of the layout work - as it was confusing me too!

**Comment by birdsarah** [comment]
Done in this commit: https://github.com/bokeh/bokeh/pull/4192/commits/b811f2eab65adc61115d5b3daec565a913ad3b99

May be a while before it's merged.
