### ISSUE TITLE
Matplotlib Basemap Toolkit aspects for Bokeh

### ISSUE THREAD

**Issue by roxyboy** [bokeh/bokeh#2763]
I'm trying to plot climate data with Bokeh and it would be nice to able to plot the data on maps. Right now I'm using the image function to plot something like pcolormesh but could you include improvements similar to basemap?

The figure I'm getting now using the image function in Bokeh:
<img width="776" alt="screen shot 2015-08-24 at 10 01 54" src="https://cloud.githubusercontent.com/assets/8934026/9441996/3a1e634e-4a47-11e5-8f0c-7d210211e6af.png">

Figure that I want using Bokeh:
<img width="613" alt="screen shot 2015-08-24 at 10 02 06" src="https://cloud.githubusercontent.com/assets/8934026/9442011/461100b2-4a47-11e5-8b01-42d94015d4ea.png">

**Comment by B3AU** [comment]
Hi,

Basemap is fine for large scale maps (world/continent/big country). For plotting data on more local maps I would like the ability to display mapbox/openstreemaps/googlemaps data in the background. 

cheers,
Beau

**Comment by dierssen** [comment]
Hi,
Any news on this item? I used the GMapPlot for Google Maps data, but I want to use the Basemap library. I was hoping that the source code of the https://www.youtube.com/watch?v=B-P3yA-P-sY demo could be found somewhere online, but I did not find it yet. Perhaps you guys found anything?
Greetings Werner.

**Comment by bryevdv** [comment]
@dierssen we have recently merged a PR that adds support for a wide variety of GIS tile sources. Bokeh glyphs, etc., can be draw on top of the tiled data. This will land in the `0.11` release, and before then, in a dev build. Perhaps that will satisfy your needs? I'm not aware of anyone working on anything with the actual Basemap component. I am not familiar with it except in name, it would probably take an interested new contributor to help get something started with it specifically.

**Comment by dierssen** [comment]
Hi Bryan, thanks for your quick response. When is the 0.11 release scheduled? Meanwhile I managed to save a Basemap image to PNG and load it then with the Bokeh image_rgba method, but that feels like a workaround. I tried mpl.to_bokeh but that method does not seem to support Basemap either. Plots stay blank/white.

Am I right that the https://www.youtube.com/watch?v=B-P3yA-P-sY demo does not use a projection, but just loads a world map image (JPG, PNG or TIFF) and zooms into that image? Anyway, as far as I can see, the Bokeh library is quite cool.

**Comment by bryevdv** [comment]
Another thing to mention is that MPL is working on much more robust JSON protocol for serialization. Whenever this is done it will be possible to have much more robust MPL compatibility. Perhaps this will be enough to make Baseman usable directly with Bokeh. But I don't know anything about how Baseman actually works, so I can't really say anything for sure. 

In the video linked above, it is only showing data, color mapped. There is a 4-d data cube of ocean temperature data, and depending on the screen resolution and data boundaries, the cube is sliced and down sampled on the fly, and then color mapped to an RBG image to show. The "land" you see is merely a coincidental artifact of the color mapped ("no data" pixels are colored black).

**Comment by bryevdv** [comment]
ping @mdboom

**Comment by bryevdv** [comment]
Oh, there is not yet a date set for `0.11` but my best current estimate would be the second half of November.

**Comment by mdboom** [comment]
Yes, the idea is that eventually a matplotlib figure could be exported to Bokeh.  Of course, how much it resembles the original data would be somewhat based on how much common functionality there is across the projects.  For example, it would easy enough to send over pre-projected data over to Bokeh, but you wouldn't gain a lot of functionality over just, say, exporting an SVG.  Long term, it would be nice to give Bokeh unprojected data and have it handle the projection so that you could reproject, pan/zoom in projected space etc.  (But I can't speak to what's on the Bokeh roadmap in that regard).

**Comment by bryevdv** [comment]
That's on the roadmap but it's a non-trivial chunk of work.

**Comment by dierssen** [comment]
Thanks guys! This answers a lot of my questions. I look forward to 0.11.

**Comment by bryevdv** [comment]
I think it's more likely at this point that functionality like this will go in to GeoViews so I will close this old discussion

cc @jbednar @philippjfr @jlstevens

**Comment by philippjfr** [comment]
Many of these features are supported in GeoViews including image projection, graticules, simple plotting of geographical features such as land masses. Custom non-flat geographical projections however are unlikely to be supported unless they land in bokeh or someone contributes to geoviews by writing the various custom bokeh models that would be required.

**Comment by jbednar** [comment]
Just to clarify, GeoViews *does* support non-flat geographical projections, via cartopy and proj4, for both inputs and outputs rendered with maplotlib and for inputs to Bokeh plots.  What it doesn't support is non-flat output projections like the one shown above.  Basically, GeoViews supports what the underlying libraries do here, and until Bokeh supports non-flat output projections, GeoViews non-flat projection plots won't be able to be interactive (with hover, zooming, etc.).
