### ISSUE TITLE
Tests we need

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2772]
Some issues have come up during the testing for the new 0.9.3 release, ideally we would have already had tests in our test suites that caught these issues when they came as PRs.
- all notebooks were broken by #2636 (hotfix: #2770) - I think I've been assuming that the examples tests would pick up broken notebooks. But weren't.
- introduction of canteen #2726 (hotfix: #2773) - caused a significant performance issue (that made bokeh unusable).

**Comment by bryevdv** [comment]
Examples tests pick up some classes of notebook failures, but not all (yet). Setting BOKEH_LOG_LEVEL="debug" will cause BokehJS to report on render times, perhaps these can be captured and compared against some baseline or limit during testing.

**Comment by birdsarah** [comment]
I had also noticed that the CI runs on travis were taking significantly longer for the selenium PR, but I thought it might be a travis blip and didn't join the dots. (hindsight is 20:20)

**Comment by birdsarah** [comment]
https://github.com/bokeh/bokeh/blob/master/bokehjs/test/test_source/test_column_data_source.coffee#L59 

just says `it "should raise an error if column lengths are inconsistent"` but doesn't have a test after it.

**Comment by birdsarah** [comment]
Can't see any tests for Selection Manager on ColumnDataSource in JS.

**Comment by birdsarah** [comment]
There appear to be no JS tests for tools.

**Comment by birdsarah** [comment]
Question for @bokeh/dev - is it ok to write selenium tests instead of bokehjs unit tests. 

Real example: #2779 - there was a bug in taptool - it wasn't executing callbacks. Writing the [selenium test](https://github.com/bokeh/bokeh/pull/2779/files#diff-eeca85dd450698995a3c65b327ea18fdR51) was a breeze, and is a fairly self-explanatory test. I then spent at least an hour trying to figure out how to write unit tests for the same problem. There are three factors here:
1) obviously, my lack of familiarity with testing Backbone views.
2) there are no existing examples of testing Backbone views for me to crib from 
3) it seems inherently messy - with lots of manual creation of dependent objects required - which seems flaky. Of course, given (1) I could be wrong about this.

@mistakevin said he would look into (3)

In the meantime, I would appreciate guidance.

**Comment by mattpap** [comment]
This issue isn't very specific on what's expected, besides having more tests, so I'm going to close it in favor of other issue in this topic.
