### ISSUE TITLE
Multiple legends

### ISSUE THREAD

**Issue by gonike** [bokeh/bokeh#2774]
When dealing with multiple axes as in https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/twin_axis.py, it would be nice to be able to generate multiple, distinct legends. This would enable the creation of a distinct legend for each axis, listing only the lines corresponding to this axis. These legends could be placed next to the corresponding axis. This would make the association between lines and axes perfectly clear, which otherwise is a typical problem of such plots.

Probably, there are more use cases for multiple legends, but this is the one I just stumbled upon.

Is there any way to do this right now?

**Comment by bryevdv** [comment]
It's possible to create multiple legends, and with new layout, possible to place them fairly arbitrarily
