### ISSUE TITLE
Enabling logging should be emphasized in documentation

### ISSUE THREAD

**Issue by chrismv48** [bokeh/bokeh#2777]
Hello,

First off, great library. Second, I'm not entirely sure if this qualifies as an issue but didn't know where else to post it.

I've been troubleshooting why my chart wasn't rendering as expected for 2 hours when I noticed the 'no handler found for logger' warning flash a few times. I turned logging on, and lo and behold got a nice error message which allowed me to solve the issue in a few seconds.

I'm not sure why these errors are being subverted to logging, but if you're sticking with that design choice, I would strongly urge you to emphasize to turn on logging in the quickstart/docs.

**Comment by bryevdv** [comment]
I'm afraid we're in a bit of a pickle. It's generally accepted practice that libraries should (by default) *enable* logging, but not *enforce* logging. The notion being that application writers using the library are in the best position to decide and dictate overall logging policy, and that a library should respect those decisions and not override them. 

That said, I certainly agree that finding some other path would be desirable. I'd definitely like to hear suggestions, perhaps there is some reasonable compromise to be made.

**Comment by bryevdv** [comment]
ping @mattpap didn't you recently make change related to this?

**Comment by bryevdv** [comment]
Logging has since been unconditionally enabled by default.
