### ISSUE TITLE
bokeh TimeSeries chokes on NaN values

### ISSUE THREAD

**Issue by ChristopheBernard** [bokeh/bokeh#2780]
TimeSeries generates an Exception if presented a TimeSeries containing a NaN at position 0. NaNs elsewhere are tolerated.

See the following snippet extracted/adapted from my code

#-Python code
import pandas as pd, numpy as np
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.charts import TimeSeries

Series=pd.Series(index=idx,data=np.random.randn(1000)).cumsum()
p=TimeSeries(Series, index=idx)
#-That works nicely
show(p)

#-now let's add a NaN in the middle
Series[100]=np.nan
p=TimeSeries(Series, index=idx)
#-That works nicely too
show(p)

#-now let's add a NaN in the beginning
Series[0]=np.nan
p=TimeSeries(Series, index=idx)
#-Kaboom
show(p)

**Comment by ChristopheBernard** [comment]
Bokeh 0.9.2, numpy 1.9.2, pandas 0.16.2

**Comment by azjps** [comment]
This seems to come down to the fact that the charts are constructing a y-range `Range1d` by taking the min and max of the y-values, and `min([np.nan, ..]) == max([np.nan, ..]) == np.nan` (and only when `nan` is the first entry in the list). It affects most of the charts, for example:
```python
from bokeh.plotting import show, figure
from bokeh.charts import Scatter
show(Scatter({"a": [(1.0, np.nan), (2.0, 2.0)]}))
```
The lower-level glyph plotting functions seem not to be affected by this.

Probably the easiest way to fix this is to use `np.nanmin/np.nanmax` everywhere in these range constructions instead of `min/max`.

**Comment by azjps** [comment]
@birdsarah @bryevdv Based on [BEP-3:Charts-interface](https://github.com/bokeh/bokeh/wiki/BEP-3:-Charts-interface) and issues like https://github.com/bokeh/bokeh/issues/2288, should this wait for refactors or should I go ahead and submit a hotfix PR? If it were up to me I'd refactor all of the `Range1d(start=min(min() for ..) - 0.1 * , end=max(max() for ..) + 0.1 * )` calls in `charts` into a static constructor for `Range1d`.

Also in general there should be fail-immediately validation that a `bokeh.properties.Float` cannot be `np.nan`, given that it later can't be serialized to json? There seem to be plenty of comments around in favor of more informative and direct error messages for issues like this.

**Comment by damianavila** [comment]
pinging @fpliger @rothnic who are working in chart refactor...

**Comment by fpliger** [comment]
This is something that should really be fixed on the new charts re-work.. 

@azjps I'm +1 if you want to submit a hotfix PR. It shouldn't take too much time and it's a valuable fix anyway.. :+1: 

Also, yes being more informative around validation is definitely a priority. :-)

**Comment by bryevdv** [comment]
We need to figure out `NaN` in general. I guess I have lost the thread of things recently. We used to be able to handle NaNs at least in some (possibly "nonstandard" but seemingly commonly supported)  way. Is this no longer the case? We have to be able to deal with them, though. If the only robust way is to ship some kind of sidecar "masked array", or the indices of `NaN` values explicitly, we can do that. The upcoming column data store on the new document structure is probably a good time/place to re-visit things. I am already planning on associating more metadata (type, and shape, e.g.) with each column, we could add other optional things like `NaN`  or `NA` masks as well. Inching closer to a "JS dataframe"...

**Comment by damianavila** [comment]
>We need to figure out NaN in general.

I completely agree, although I think the thing discussed specifically here could be solved with a quick Pr until a more encompassing resolution of the general problem is in place...

**Comment by VelizarVESSELINOV** [comment]
:+1:
