### ISSUE TITLE
Plot grid, xgrid, and ygrid not behaving as documented

### ISSUE THREAD

**Issue by tcr-ableton** [bokeh/bokeh#2781]
Hi!

### Needle in my foot

I'm trying to access a Timeserie and Bar charts xgrid and ygrid elements to change their look an feel. 
However the documentation mentions [here](http://bokeh.pydata.org/en/latest/docs/reference/plotting.html#bokeh.plotting.Figure.xgrid) that the `xgrid` and `ygrid` should be attributes, but when I inspect them in ipython they appear to be methods:

```python
>>> b = Bar([], xgrid=True, ygrid=True)
>>> b.xgrid
<bound method Chart.method of <bokeh.charts._chart.Chart object at 0x1081b6828>>
```

It occurs that the [Styling Visual Attributes](http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#grids) part of the documentation mentions them as being methods. However, the methods behavior does not appear to fit with the description. They are described as returning the grid object corresponding to their axis. Instead they are a method taking a boolean value and returning a Chart object.

```python
>>> b.xgrid?
Signature: b.xgrid(value)
Docstring: Chained method for xgrid option.
File:      ~/dev/projects/tools/kontrol/virtualenv/lib/python3.4/site-packages/bokeh-0.9.2-py3.4.egg/bokeh/charts/_chart.py
Type:      method
```

Which seems to be the expected behavior of the Chart constructor flag instead.

### Leading to the following problem

In the end I am unable to access the grid elements of my chart. I have tried using the select method over my charts:

```python
>>> from bokeh.models import Grid
>>> b.select({'type': Grid})
[<bokeh.models.grids.Grid at 0x10825ff60>,
 <bokeh.models.grids.Grid at 0x10825ff98>]
```

However their ``name`` field is empty, and it does not seem possible to distinguish them independently and know having only the object if it's bound to the xgrid or the ygrid.

Could you point me the idiomatic way to get both the xgrid and ygrid objects from a Chart object?

### Configuration

+ Bokeh 0.9.2
+ Python 3.4

It is very likely that my whole problem is caused by my misunderstanding of the tool, therefore thanks for your support!

PS: This ticket intentionally contains two issues, that could be perfectly splitted in two Github issue. Kept them together in order to keep the cause->consequence link :-)

**Comment by birdsarah** [comment]
Hi Theo,

Quick clarifying question: you said "the documentation mentions here" but
didn't I didn't see the link - can you post where you meant. It might hope
to unravel the confusion.

But yes, Bar is a Chart function that does all the hard work of assembling
together pieces from the Models interface. On each Model you'll find things
are attributes, but accessing those models from what the chart function
returns can require some digging.

You can see here a pretty convoluted example of me heavily customizing a
Bar Chart:
https://github.com/birdsarah/gtimelog-viz/blob/master/app/charts/today_summary.py#L22
( including the grid lines )

Sincerely,

Sarah Bird

**Comment by tcr-ableton** [comment]
Hi @birdsarah 

Thanks for your quick answer!

I've updated the ticket with the link right after posting it, so it is possible if you are following Github through mails this update didn't reach you:
- first link:  http://bokeh.pydata.org/en/latest/docs/reference/plotting.html#bokeh.plotting.Figure.xgrid
- second link: http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#grids

Thanks for the usage example. It looks quite like what I'm already doing, however it seems pretty specific to Bar in this case, and is manipulating only one of the grid elements.

As mentioned in the initial ticket, I also try to access both ``xgrid`` and ``ygrid`` attributes of a ``Timeserie`` chart. It makes things much trickier as the ``Grid`` object returned does not seem to expose attributes that allow to distinct them (which one is x, which one is y).

Do you have an example, or could point me a way to do that? :-)

To provide a little bit of context, I'm trying to unify the styling of multiple charts, according to a predefined declaration made in a dict. And it requires to be able to automatically access chart attributes like ``xaxis``, ``xgrid`` and so on.

Cheers,
Theo

**Comment by birdsarah** [comment]
I'm afraid I don't have an example using TimeSeries chart.

But you're looking at documentation for the Figure object returned by the
plotting function figure(), which is not the same as the Chart object.

You can probably do a timeseries quite happily using figure() - like
https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/stocks.py

**Comment by bryevdv** [comment]
Closing, `xgrid` now behave the same across all APIs
