### ISSUE TITLE
Create example of using Hover tool to display custom images

### ISSUE THREAD

**Issue by FedericoV** [bokeh/bokeh#2782]
It would be nice to show how someone can use the hovertool to display custom images using URL/URI upon hovering over a region of interest.  It would allow users to embed an additional dimension into plots.

**Comment by mattgeballe** [comment]
I'm a user interested in exactly this! :smile: 

I've been attempting to make scatterplots with image hover tooltips, but I've run into a problem getting rendering of the URL/URI to work in the Hover tool when it's stored in the ColumnDataSource.

Here is a small example I've been testing with if it's helpful:

```python
from __future__ import print_function

from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool

source = ColumnDataSource(dict(
    x = [1,2,3],
    y = [5,10,15],
    img = ["""<img src="http://www.woojr.com/wp-content/uploads/2009/04/a.gif" height="100" width="100">""", \
    """<img src="http://www.woojr.com/wp-content/uploads/2009/04/b.gif" height="100" width="100">""", \
    """<img src="http://www.woojr.com/wp-content/uploads/2009/04/c.gif" height="100" width="100">"""]
    ))

p = figure(title="Hover Images")

# Make scatterplot
p.circle("x", "y", fill_alpha=0.2, size=10, source=source)

# Retrieving img tag from ColumnDataSource results in it not being rendered:
tooltips = """ @img """

# Using one static url img tag works fine
# tooltips = """<img src="http://bokeh.pydata.org/en/latest/_static/bokeh-transparent.png">"""

hover = HoverTool(tooltips=tooltips)
p.add_tools(hover)
show(p)

```

**Comment by altosaar** [comment]
This example isn't working for me - it still shows the raw HTML instead of rendering images. Anyone else? I'm on bokeh 0.11.0.

**Comment by bryevdv** [comment]
You need to use a custom HTML tooltip:

http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#custom-tooltip

**Comment by altosaar** [comment]
Awesome - thanks a lot! That works :)

**Comment by mattgeballe** [comment]
Yes, my mistake in the code above was to try to store the entire HTML tag in the DataSource, rather than constructing the tag within the tooltip with only the URL in the DatSource.  The example that was added to the docs works.

**Comment by bryevdv** [comment]
@mattgeballe well we'd like to make the other way work too, via some `safe` flag that prevents the HTML escaping, but god this works for now.

**Comment by altosaar** [comment]
@bryevdv I think I'm missing something:

```
from bokeh.plotting import figure, output_file, show, ColumnDataSource, output_notebook
from bokeh.models import HoverTool

output_file("toolbar.html")

labels_with_math[0] = '<math id="S1.p1.1.m1.1" class="ltx_Math" alttext="\\mathaccent 869{X}" display="inline" xref="S1.p1.1.m1.1.cmml"><semantics id="S1.p1.1.m1.1a" xref="S1.p1.1.m1.1.cmml"><mover accent="true" id="S1.p1.1.m1.1.1" xref="S1.p1.1.m1.1.1.cmml"><mi id="S1.p1.1.m1.1.1.2" xref="S1.p1.1.m1.1.1.2.cmml">X</mi><mo id="S1.p1.1.m1.1.1.1" xref="S1.p1.1.m1.1.1.1.cmml">~</mo></mover><annotation-xml encoding="MathML-Content" id="S1.p1.1.m1.1.cmml" xref="S1.p1.1.m1.1"><apply id="S1.p1.1.m1.1.1.cmml" xref="S1.p1.1.m1.1.1"><ci id="S1.p1.1.m1.1.1.1.cmml" xref="S1.p1.1.m1.1.1.1">normal-~</ci><ci id="S1.p1.1.m1.1.1.2.cmml" xref="S1.p1.1.m1.1.1.2">X</ci></apply></annotation-xml><annotation encoding="application/x-tex" id="S1.p1.1.m1.1b" xref="S1.p1.1.m1.1.cmml">\\mathaccent 869{X}</annotation></semantics></math>'

source = ColumnDataSource(
        data=dict(
            x=[1, 2, 3, 4, 5],
            y=[2, 5, 8, 2, 7],
            desc=['A', 'b', 'C', 'd', 'E'],
            label = labels_with_math[0:5]
        )
    )

hover = HoverTool(
          tooltips=labels_with_math[0] # this works
#         tooltips="""@label""" # this doesn't work
    )


p = figure(plot_width=400, plot_height=400, tools=[hover],
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)
```

Hard coding the HTML label works:
![image](https://cloud.githubusercontent.com/assets/5317244/12428828/f5c8f050-beb4-11e5-9d86-fd43033b9bce.png)

But doing ` """@label"""` doesn't work:
![image](https://cloud.githubusercontent.com/assets/5317244/12428844/054316b4-beb5-11e5-9506-11ad5dcb0b66.png)

Any idea how I could fix this?

Thank you!

**Comment by bryevdv** [comment]
This needs the `safe` flag referenced in the the other issue (new functionality)

**Comment by altosaar** [comment]
Makes sense - thanks Bryan. I'll take a look at the `safe` flag options asap.
