### ISSUE TITLE
HoverTool with multiple axes

### ISSUE THREAD

**Issue by gonike** [bokeh/bokeh#2784]
When working with multiple axes, HoverTool seems to always display the tooltip corresponding to the second axis, regardless of whether I'm hovering over that data or not. The tooltip corresponding to the data of the first axis are - correctly - displayed, once I'm hovering over the data. Here's a minimal example.

    from bokeh.plotting import output_file, figure, show, ColumnDataSource
    from bokeh.models import Range1d, LinearAxis, HoverTool
    from numpy.random import normal, uniform

    meas_data_1 = normal(0, 1, 100)
    meas_data_2 = uniform(-0.5, 0.5, 100)

    output_file("myplot.html", title="My plot")
    tools = "box_zoom, wheel_zoom, pan, reset, resize, hover"
    fig = figure(width=500, plot_height=500, tools=tools)

    # Add a second y axis
    second_y_axis = "right"
    fig.extra_y_ranges = {second_y_axis: Range1d()}
    fig.add_layout(LinearAxis(y_range_name=second_y_axis), 'right')

    source_1 = ColumnDataSource(data=dict(x=range(0, len(meas_data_1)), y=meas_data_1))
    fig.line('x', 'y', source=source_1)
    source_2 = ColumnDataSource(data=dict(x=range(0, len(meas_data_2)), y=meas_data_2))
    fig.line('x', 'y', source=source_2, y_range_name=second_y_axis)
    hover = fig.select(dict(type=HoverTool))
    hover.tooltips = [("(x,y)", " (@x, @y)")]

    show(fig)

Is it possible to manipulate this behavior? In particular, I'd like bokeh to only show the tooltip of a line I'm actually hovering over...

**Comment by esvhd** [comment]
Not sure if this works but it might be worth a try: add tooltips for your each set of your glyphs separately. Check this list, there is example in the answer I provided:

http://stackoverflow.com/questions/29435200/bokeh-plotting-enable-tooltips-for-only-some-glyphs/32116970#32116970

**Comment by gonike** [comment]
Thanks for the hint, @esvhd ! While investigating your response, I noted that the apparently weird behavior in the above example stems from the specific data set. Actually, I think that the HoverTool is a bit 'overly sensitive' in displaying tooltips when the cursor isn't too close to a line, but apart of that, it seems to work as it should.

In particular, when replacing the 'measurement data' in the above example by 

    meas_data_1 = normal(0, 1, 100) + [i/25 for i in range(0, 100)]
    meas_data_2 = uniform(-1, 0, 100)

and specifying a range for the second axis

    fig.extra_y_ranges = {second_y_axis: Range1d(start=-1, end=3)}

everything seems to work fine.

Just for reference: Here's the same example, using your proposed approach, adding glyphs manually one at a time.

    from bokeh.plotting import output_file, figure, show, ColumnDataSource
    from bokeh.models import Range1d, LinearAxis, HoverTool
    from numpy.random import normal, uniform

    meas_data_1 = normal(0, 1, 100) + [i/25 for i in range(0, 100)]
    meas_data_2 = uniform(-1, 0, 100)

    output_file("myplot.html", title="My plot")
    fig = figure()

    second_y_axis = "right"
    fig.extra_y_ranges = {second_y_axis: Range1d(start=-1, end=3)}
    fig.add_layout(LinearAxis(y_range_name=second_y_axis), 'right')

    source_1 = ColumnDataSource(data=dict(x=range(0, len(meas_data_1)), y=meas_data_1))
    g1 = bkm.Line(x='x', y='y')
    g1_r = fig.add_glyph(source_or_glyph=source_1, glyph=g1)
    g1_hover = HoverTool(renderers=[g1_r], tooltips=[("(x,y)", " (@x, @y)")])
    fig.add_tools(g1_hover)

    source_2 = ColumnDataSource(data=dict(x=range(0, len(meas_data_2)), y=meas_data_2))
    g2 = bkm.Line(x='x', y='y')
    g2_r = fig.add_glyph(source_or_glyph=source_2, glyph=g2, y_range_name=second_y_axis)
    g2_hover = HoverTool(renderers=[g2_r], tooltips=[("(x, y)", " (@x, @y)")])
    fig.add_tools(g2_hover)

    show(fig)

Both versions seem to be equivalent, as would be expected.
