### ISSUE TITLE
Regression in bokeh-server (client side?)

### ISSUE THREAD

**Issue by dwf** [bokeh/bokeh#2787]
With bokeh 0.8.0, this behaves as expected:

```python
In [1]: from bokeh.plotting import figure, output_server, Session, push

In [2]: session = Session(root_url='http://127.0.0.1:5006/', load_from_config=False)

In [3]: output_server(docname='test alpha', session=session)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:bokeh.session:got read write apikey

In [4]: f = figure()

In [5]: f.line([0, 2, 4, 6, 8], [1, 9, 1, 9, 1])
Out[5]: <bokeh.plotting.Figure at 0x106922f60>

In [6]: push()
Out[6]:
[<bokeh.models.axes.LinearAxis at 0x1069c20b8>,
 <bokeh.models.formatters.BasicTickFormatter at 0x1069c22b0>,
 <bokeh.models.tools.ToolEvents at 0x1069c2748>,
 <bokeh.models.renderers.GlyphRenderer at 0x1069e1278>,
 <bokeh.models.grids.Grid at 0x103f25e48>,
 <bokeh.models.tools.WheelZoomTool at 0x1069c2a20>,
 <bokeh.models.glyphs.Line at 0x104b50780>,
 <bokeh.models.glyphs.Line at 0x1072bc2e8>,
 <bokeh.models.tools.PanTool at 0x10498c828>,
 <bokeh.models.axes.LinearAxis at 0x1069c2518>,
 <bokeh.models.grids.Grid at 0x1069c29b0>,
 <bokeh.models.tickers.BasicTicker at 0x1069c2198>,
 <bokeh.models.plots.PlotContext at 0x106922390>,
 <bokeh.models.tools.BoxZoomTool at 0x103f25ef0>,
 <bokeh.models.ranges.DataRange1d at 0x1069c2550>,
 <bokeh.models.tickers.BasicTicker at 0x1069c2780>,
 <bokeh.models.tools.PreviewSaveTool at 0x1069c24e0>,
 <bokeh.models.formatters.BasicTickFormatter at 0x1069c2898>,
 <bokeh.models.sources.ColumnDataSource at 0x1069c2fd0>,
 <bokeh.plotting.Figure at 0x106922f60>,
 <bokeh.models.tools.ResizeTool at 0x1069c2470>,
 <bokeh.models.tools.ResetTool at 0x1069c2828>,
 <bokeh.models.ranges.DataRange1d at 0x1069c2630>]
```

When I open a browser to http://127.0.0.1:5006/ I see a single document, "test alpha", and when I click on it, I see my plot. Adding additional plots works as expected.

On Bokeh 0.9.3 (and I was seeing the same on 0.9.2), the same thing results in the document name appearing at http://127.0.0.1:5006/ but clicking on it has no effect. `show()`, however, brings me to a URL starting with http://127.0.0.1:5006/ and correctly displays the plot, which leads me to believe that this is a regression in whatever client side code is driving the main bokeh-server web interface.

I was using two Python 3.4 conda environments to test this, one with 0.8.0, one with 0.9.3. I can provide additional details in case of difficulties reproducing.

**Comment by bryevdv** [comment]
Oh, I just want to make sure I understand: the full link to the plot (with the UUIDs) works fine, it's just the link on the index page at `http://127.0.0.1:5006/` doesn't work?

**Comment by dwf** [comment]
Hi Bryan,

The index page renders, and the document name (as a hyperlink) appears. On bokeh 0.8.0, when I click that hyperlink, the plot appears beneath it. On Bokeh 0.9.2/0.9.3, I click the hyperlink and nothing happens. If I use `show(f)` at the IPython prompt a web browser pops up to an URL at `http://127.0.0.1:5006/bokeh/doc/<uuid>` and the plot displays there, so that appears to work fine.

**Comment by dwf** [comment]
I've tested this on Chrome, Firefox and Safari, and in a Chrome incognito tab to rule out extension interference.

Each time I click, the Chrome JavaScript console reads:

```
bokeh.js:14769 Bokeh: load_models: start
bokeh.js:61066 Uncaught ./base: Unknown Collection HelpTool
```

**Comment by dwf** [comment]
Traceback:
```
Collections	@	bokeh.js:61066
load_models	@	bokeh.js:61119
(anonymous function)	@	bokeh.js:61683
fire	@	bokeh.js:5380
self.fireWith	@	bokeh.js:5492
deferred.(anonymous function)	@	bokeh.js:5582
fire	@	bokeh.js:5380
self.fireWith	@	bokeh.js:5492
done	@	bokeh.js:11536
callback	@	bokeh
```

**Comment by bryevdv** [comment]
So, realistically, there is not going to be any new work on the existing server. I'm not sure exactly what for a comparable facility will take in the new server. From my perspective, the index page was never really more than a dev/engineering UI, though I don't think we did a very good job about managing that expectation. What is important (and expected) is that the `/bokeh/doc/<uuid>` link works, which means you can use `autoload_server` to embed the plot, or you can simply navigate to that URL directly.

**Comment by bryevdv** [comment]
Tho, ping @mattpap any idea about the missing Collection? I just took a quick look and nothing looks amiss in `base.coffee` or `help_tool.coffee`.

**Comment by dwf** [comment]
> So, realistically, there is not going to be any new work on the existing server. I'm not sure exactly what a comparable facility will take in the new server. From my perspective, the index page was never really more than a dev/engineering UI, though I don't think we did a very good job about managing that expectation. 

I see. We were using it as a quick-and-dirty way of displaying groups of plots together in an experiment monitoring dashboard without writing a bunch of extra Flask code ourselves. It did that job quite well. We weren't really expecting it to grow too much beyond its current state but it was useful as-was.

I'm a little lost as to the role that a "document" plays in the new order of things in that case. It sounds, from what you've said and what the documentation on `autoload_server` says, like the main supported use case is embedding one plot at a time, using the `Plot` object itself. If so, what's the role of the "document" object or document name that gets tossed around?

**Comment by dwf** [comment]
I've bisected the problem (rebuilding bokehjs at each step) and found the culprit commit.

```
607c9204926e8d319541f570a3fcda85adebcaf7 is the first bad commit
commit 607c9204926e8d319541f570a3fcda85adebcaf7
Author: Travis Swicegood <development@domain51.com>
Date:   Tue Mar 31 12:32:20 2015 -0700

    Switch to using built-in jQuery UI prefixing

:040000 040000 27c6a7797205cc898a0ebcb377978a5878c17397 713648987e9bcce3e30e613440f5735507286c2c M	bokehjs
```

**Comment by bryevdv** [comment]
ping @mistakevin  quick thoughts?

@dwf `autoload_server` will work with layouts (grid plot, h/v box, etc) containing multiple plots/widgets.

**Comment by azjps** [comment]
> What is important (and expected) is that the /bokeh/doc/<uuid> link works, which means you can simply link or navigate to that URL directly to preview the plot (which show will do for you). 

But this url (right now) isn't easy to find on the index page? Shouldn't the index page "links" be hot-fixed to be actual links to the appropriate documents? The behavior of launching a web browser with the URL to the document is pretty counter-intuitive when launching bokeh-server from a remote server.

This is the same issue as posted in https://github.com/bokeh/bokeh/issues/2562 https://github.com/bokeh/bokeh/issues/2608 and probably many more. It almost caused me to give up using `bokeh` since I'd thought I was incapable of getting it to work.

**Comment by bryevdv** [comment]
Could you submit a quick PR to restore the links? Then we could easily make a dev build that contains it.

**Comment by dwf** [comment]
Bokeh 0.9.1 is actually where the bug shows up as far as releases go. The commit I bisected before was not the cause of the problem. I think I must have some sort of browser caching issue...

I'd like to submit a patch but I don't know the first thing about all of this jQuery/CoffeeScript voodoo.

**Comment by dwf** [comment]
Okay, I was wrong again. I've redone this bisect 3 times just to be sure, clearing my browser cache at each step. The culprit appears to be a173f6aa38daab9c08545495a05ce732a0f2e78c (that I've turned up consistently on each of the three times).

```
a173f6aa38daab9c08545495a05ce732a0f2e78c is the first bad commit
commit a173f6aa38daab9c08545495a05ce732a0f2e78c
Author: Travis Swicegood <development@domain51.com>
Date:   Tue Mar 31 09:58:03 2015 -0700

    Remove global jQuery / jQuery-UI in favor of bundled version

    This is a two pronged attack.  First, it removes the main jQuery and
    Bootstrap code from the global scope.  Those were being loaded and not
    used.  Second, it ensures that all generated code us being managed by
    `Bokeh.$` instead of dealing with any globally available jQuery.

    This should help isolate Bokeh's jQuery from the rest of the world.

:040000 040000 08fb327a9be099092b0899f60845ea3b4a84c5dc 5bddc7178365ccacbfa43b5f16ae3d2fd360654d M   bokeh
git bisect start
# good: [da429b96a9e264ede4222470c1fdc4aa3088930b] Merge pull request #2101 from bokeh/release_0.8.2
git bisect good da429b96a9e264ede4222470c1fdc4aa3088930b
# bad: [9f21bc95b443da35ce4b1fd23600e0705edd2014] Merge pull request #2301 from bokeh/release_0.9.0
git bisect bad 9f21bc95b443da35ce4b1fd23600e0705edd2014
# bad: [9c4626835010e15480fe4f27e761d4df253afbf3] Merge pull request #2141 from almarklein/gulp-tasks
git bisect bad 9c4626835010e15480fe4f27e761d4df253afbf3
# good: [b5efa6d3eeb6061b3ab0f087c6aaba0d51291400] run tests from python unit test
git bisect good b5efa6d3eeb6061b3ab0f087c6aaba0d51291400
# bad: [a0b9b778db2b5595f8fc38d0dd86d46faf2f7196] revert last change
git bisect bad a0b9b778db2b5595f8fc38d0dd86d46faf2f7196
# good: [248147fe304f3ca9b7241866cc08623bd2b4f662] fix typo and improve error output
git bisect good 248147fe304f3ca9b7241866cc08623bd2b4f662
# bad: [607c9204926e8d319541f570a3fcda85adebcaf7] Switch to using built-in jQuery UI prefixing
git bisect bad 607c9204926e8d319541f570a3fcda85adebcaf7
# good: [fb5e03ac61977b745bcb64917c5bf4ea6246bd87] Switch out to gulp as the main dependency
git bisect good fb5e03ac61977b745bcb64917c5bf4ea6246bd87
# bad: [2ee0894845a8a3a40422003973d7987655bc337e] Get rid of stray semi-colon
git bisect bad 2ee0894845a8a3a40422003973d7987655bc337e
# bad: [96303fc281fef3af00b7ec2257dfb5b4c37f9719] Ensure that jQuery UI is loaded on top of the correct jQuery
git bisect bad 96303fc281fef3af00b7ec2257dfb5b4c37f9719
# bad: [a173f6aa38daab9c08545495a05ce732a0f2e78c] Remove global jQuery / jQuery-UI in favor of bundled version
git bisect bad a173f6aa38daab9c08545495a05ce732a0f2e78c
# first bad commit: [a173f6aa38daab9c08545495a05ce732a0f2e78c] Remove global jQuery / jQuery-UI in favor of bundled version
```

**Comment by dwf** [comment]
I've managed to sort it out, the bug was a really stupid one that even a JS neophyte like me managed to figure out. #2792

**Comment by azjps** [comment]
:+1: Nice! There was another issue that had prevented this index page from working for me, at least for app plugins launched via `--script`. Custom widgets (i.e. classes with `extra_generated_classes`) don't get registered in the Collections list on the index page in `bokehjs/src/coffee/common/base.coffee`, and therefore its not possible to instantiate a model for the custom widget.

I'm afraid I don't know enough about this to suggest a fix, or even if its something worth fixing. The following hack works perfectly well for me though:

```coffeescript
  mod = _mod_cache[typename]
  # For custom apps that derive from VBox
  if not _mod_cache.hasOwnProperty(typename)
    mod = _mod_cache["VBox"]

  if not mod.Collection?
    mod.Collection = make_collection(mod.Model)
```

**Comment by damianavila** [comment]
>I'm afraid I don't know enough about this to suggest a fix, or even if its something worth fixing. The following hack works perfectly well for me though:

@azjps can you open another issue for this to continue the discussion of this specific problem? Thanks.
