### ISSUE TITLE
Opportunities for pyscript to efface JS for Bokeh users? 

### ISSUE THREAD

**Issue by datnamer** [bokeh/bokeh#2788]
I mentioned to @almarklein in his excellent flexx repo that there might be some opportunities for his transpiled python to JS known as "Pyscript" to be utilized in Bokeh:

1. Being able to  write callbacks in pyscript instead of JS. This would be an awesome feature given the sentiment on some issues on this list of desiring to avoid JS, Bokeh's vision  to do more stuff in python and the difficulty of wrapping every conceivable disred callback in Python.

2. Extend Bokeh models to other JS libraries using pyscript:  I think Bokeh is already moving in this direction of providing modularity and refocusing BokehJS on core competencies, which I think is great. Augmenting this core of BokehJS by using Pyscript to wrap specialized JS charting libraries seems like a natural extension of this path. Again I want to plug R's [HTML widgets](http://www.htmlwidgets.org/) as inspiration here. 

These would support being able to develop interactive client side reports in pure python syntax- which  would be fantastic.

**Comment by almarklein** [comment]
Just made #2799 to address the first point. As I mention in the PR, I think PyScript would need a bit more work before we go rely on it in Bokeh (unless we mark this functionality as experimental and py3k only).

**Comment by bryevdv** [comment]
There should be a separate issue to investigate extending support to python 2, but I think this issue can be closed since the flexx PR has been merged.
