### ISSUE TITLE
HTML Title (visible in browser tab) (EASY update?)

### ISSUE THREAD

**Issue by apiszcz** [bokeh/bokeh#2793]
V0.9.3 produces "Bokeh Plot" in the title area of the browser tab. Is there a way to set this to match the plot title or other string?

**Comment by bryevdv** [comment]
`output_file` accepts a title parameter:

http://bokeh.pydata.org/en/latest/docs/reference/resources_embedding.html#bokeh.io.output_file

**Comment by bryevdv** [comment]
As a suggestion, these kinds of support questions might be better asked in the Bokeh Users mailing list:

http://bokeh.pydata.org/en/latest/docs/reference/resources_embedding.html#bokeh.io.output_file

They will get a wider audience of potential people who could possibly help or answer, and also it will help keep the issue tracker more clear to focus on bugs and feature issues.
