### ISSUE TITLE
Allow Jinja templates in a vform 

### ISSUE THREAD

**Issue by tonyfast** [bokeh/bokeh#2796]
It would be pretty cool to use user-defined Jinja templates in Bokeh Apps.  I am thinking 

```
show( vform( [plot, md_template, plot2] ) )
```

``md_template`` would be something like a bokeh.model wrapped around a Jinja template that could accept column data source parameters.

**Comment by mattpap** [comment]
@tonyfast, can you elaborate at least a little bit on closing this issue. Was this discussed somewhere else, etc.?

**Comment by tonyfast** [comment]
@mattpap after re-reading it, I didn't think I wanted that anymore.  

Is this a thing worth discussing?
