### ISSUE TITLE
Project proposal: Tile manager in Bokeh

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#2803]
Working with datasets much larger than the currently visible screen area is commonplace across many fields, with additional data available by either panning to an area currently off screen, or by zooming in to see details. To provide fast interactive exploration of such datasets over a limited bandwidth connection, the geospatial data community commonly uses a tile-based approach (see e.g. http://wiki.openstreetmap.org/wiki/Tiles, or play around with maps.google.com or openstreetmap.org).  For such GIS applications, a fixed set of e.g. 256x256 tiles are pre-computed at the server, and only those relevant for the area and zoom level currently being displayed (plus maybe nearby tiles expected to soon be requested) are sent to the client.

There are many people who want to include GIS data in Bokeh, but there are also a lot of non-GIS applications with similar requirements -- a remote server with a large dataset, and a local client with a user who wants to pan and zoom to explore that data interactively.  For GIS applications, a pre-computed set of tiles is often sufficient (and efficient for serving tiles to a large number of simultaneous users), but for non-GIS applications the tiles often need to be rendered dynamically for a specific users, though they can (and presumably should be) cached once rendered and/or once they arrive at the client.

I'm personally involved at least three projects needing to support such interactivity, two of which have already developed custom tile-based approaches in Bokeh using ImageURL (one for GIS data, and one for other 2D but non geo-spatial data).  I'm sure many other applications already need this functionality as well.

After discussions with @bryevdv and @brendancol , we propose that Bokeh provide explicit support for this functionality, allowing sets of tiles to be generated, cached, and displayed easily, with minimal user code required.  After some minimal configuration (setting specific fixed zoom levels, tile sizes, etc.), Bokeh should transparently handle finding the appropriate tiles for a given plot, scaling them for intermediate zoom levels, arranging them properly next to each other, and updating them when required in response to user interaction or updated data from the server.  

It should be possible to have multiple overlapping sets of tiles, so that e.g. one could have tiles for static geospatial data in the background, dynamically computed tiles visualizing a remote dataset on top of the geospatial data, perhaps another static set of tiles with placenames on top of that, and then other Bokeh glyphs on the very top (circles, arrows, etc.).

Hopefully this functionality can be built soon, before we have dozens of competing partial implementations out in the wild!

**Comment by pzwang** [comment]
I'm +1 on this, and I feel that the backend should be implemented with blaze and dask.

**Comment by jbednar** [comment]
I agree, because in many cases the backend's job should be trivially parallelizable -- the computation of each tile should normally be able to be done independently, and typically with data distributed independently as well.

**Comment by ahmadia** [comment]
+1 on using Dask and Blaze for tile rendering (storage?), possibly on-demand as well.  I think we should also consider Anaconda Cluster as a more heavy-weight back-end.

I think we have some good ideas for how to implement the front-end.  I'd like to contribute where I can on this.

**Comment by bryevdv** [comment]
@bokeh/dev I think this can be closed, with @brendancol recent PRs?

**Comment by jbednar** [comment]
Those PRs definitely solve the geospatial issue, and should also work fine for any non-geo tile provider that's already set up.  But do we make it easy yet for people to launch such a custom tile provider for their own datasets, to be consumed by a Bokeh client?  We've definitely got the ability in-house for that, but I'm not sure it's something we've exposed to the users in a way that's easy for them to get started with.  @brendancol?

**Comment by brendancol** [comment]
@jbednar If the maximum extent of the custom tile set is `square`, then no problem.  User can override default values of `MercatorTileSource` or supply a User Defined Model.  There are some issues when using User Defined Models with the new bokeh server, but it is close.  The User Defined Model would look like this:

```
class CustomTileSource(TMSTileSource):
    __implementation__ = """
    _ = require "underscore"
    Util = require "util/util"
    TMSTileSource = require "renderer/tile/tms_tile_source"
    class CustomTileSource extends TMSTileSource.Model
      type: "CustomTileSource"

      initialize: () ->
        @set('x_origin_offset', 0)
        @set('y_origin_offset', 0)
        @set('initial_resolution', 134217.728)
        super

    module.exports =
      Model: CustomTileSource
    """
```

The above example creates a `CustomTileSource` class in Python and supplies the `__implementation__` in CoffeeScript with origin and resolution changed to fit the custom tiles.

**Comment by bryevdv** [comment]
So, thoughts on closing this particular issue?

**Comment by brendancol** [comment]
Yes, I will can help address any follow up issues as a separate issue.
