### ISSUE TITLE
Add max_retry_attempts and retry_interval_ms for ImageURLView

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#2805]
I would like to be able to retry loading an image within `image_url` if for some reason there is an error while requesting the image (e.g. HTTP 404).

I'd like to add two properties to Bokeh:

`max_retry_attempts`: int value for number of times to continue to attempt to load image.
`retry_interval_ms`: millisecond value for how often to retry in the event of load error.

then implement logic in `ImageURLView` for `img.onerror`

**Comment by canavandl** [comment]
ref issue: #2785
