### ISSUE TITLE
bokeh-server index page for plugins

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#2808]
Apologies if I butcher terminology.

Ref https://github.com/bokeh/bokeh/issues/2787, the index page won't be able to display [plugins](https://github.com/bokeh/bokeh/blob/master/bokeh/server/utils/plugins.py) (i.e. with ``extra_generated_classes``) launched by ``bokeh-server --script``, since these plugins won't have registered with the ``Collections`` object in ``base.coffee``.

If its not straightforward to register these plugins, it might be sufficient to (1) log a sensible warning when bokehdoclabel link is clicked (2) provide additionally a link to the document. If I have time I might be able to look into the latter.

**Comment by bryevdv** [comment]
This refers to the old `bokeh-server` which has been completely removed. It is no longer relevant to the new new > `0.11` server, so closing this.
