### ISSUE TITLE
Chaining callbacks (composite callback?)

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#2812]
I'm using CustomJS to install callbacks on a variety of widgets, but some of these callbacks need to execute code that's installed as a different callback.  Is it possible to have a composite CustomJS object that has a list of other CustomJS objects that it will call, in turn?  Or some other way to chain callbacks?

**Comment by brendancol** [comment]
I'd love to have a way to place callbacks in an external js file that could be referenced by function name and allow for syntax highlight and use of js tools like syntax linting.  If we had a `add_callback` method on bokeh objects then mult

Example (callback_example.py):

    p = figure(external_callbacks="callbacks.js")
    p.x_range.add_callback("change", "onXRangeChange")
    p.x_range.add_callback("change", "refreshData")

Example (callbacks.js):

    var onXRangeChange = function(plot, source) {
       ...do something here...
    }

**Comment by brendancol** [comment]
sorry didn't mean to close

**Comment by jbednar** [comment]
Yes, @brendancol, that would be really convenient!

**Comment by jbednar** [comment]
And/or an external Coffescript file...

**Comment by birdsarah** [comment]
Yes I agree. I think another part of this, might be the ability to easily know the identity of bokeh items on the page. Then you could easily write an external javascript file, that referenced different bokeh objects. This would mean the ability to specify a custom index or something similar, which obviously runs the risk of name clashes.

**Comment by bryevdv** [comment]
I think this now falls under https://github.com/bokeh/bokeh/issues/5983 which is basically to create a registry of named JS functions that can be called from Python. It would be a simple matter to expose a way to call them in JS too.
