### ISSUE TITLE
Do we want to deprecate callbacks in 0.10 or push out further?

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2815]
When I implemented #2634 (changing `Action` to `Callback` and `Callback` to `CustomJS`) I added a deprecation warning for 0.10. This now seems close. Should we push it out to 0.11?

**Comment by bryevdv** [comment]
It's already been broken for anyone that imported from `bokeh.models` and there was not too much clamor I think we should just change it.

**Comment by damianavila** [comment]
>and there was not too much clamor I think we should just change it.

:+1:
