### ISSUE TITLE
filled bands 

### ISSUE THREAD

**Issue by PBrockmann** [bokeh/bokeh#2821]
I would like to plot an filled area over an axis and for a specific range of values to indicate a specific area of interest as in the following image (vertical areas in grey are volcano episodes).

![filled_bands_on_xaxis](https://cloud.githubusercontent.com/assets/5402758/9731321/7a93c910-561c-11e5-955b-4e81c7e6f238.png)

I have already posted this request to bokeh google group as
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/EW_aKTHkQ_s
but allow myself to reference it as an issue.

The suggestion to use quads leads to a display set from -1000 to 1000
```
plot.quad(top=1000, bottom=-1000, left=1, right=5, color="#BBBBBB", alpha=0.5)
```

![quads](https://cloud.githubusercontent.com/assets/5402758/9731433/285ea664-561d-11e5-878e-2f33de3fb40a.png)

Reading http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#bands
an additionnal property "band_limits" to xgrid and ygrid would fit:
p.xgrid.band_limits = [1, 5]

**Comment by tobyhodges** [comment]
Take a look at `BoxAnnotation`. You can read about it here: http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#box-annotations
The example given in the User Guide linked above only uses the `top` and `bottom` parameters, but you can just as easily specify `left` and `right` for your shaded areas. 

Of course, if you might need to add a lot of these shaded areas, then you can build this annotation into a loop, or consider using `quad` or `rect` with a series of data describing each range that you want to highlight.

Hope this helps.

**Comment by PBrockmann** [comment]
Yes indeed. This feature is perfectly covered by http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#box-annotations
Thanks very much.

![boxannotation](https://cloud.githubusercontent.com/assets/5402758/9736832/d2744386-5643-11e5-9d8e-0fa3ee66c74b.png)
