### ISSUE TITLE
Have glyph methods return the glyph renderer, not the plot

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2829]
Currently, glyph methods return the plot they are on, which allows for chaining:
```
p = figure()
p.circle(...).line(...)
```
But my guess is this is rarely done, by anyone. It has been suggested that it would be more useful if the glyph method returned the renderer instead:
```
p = figure()
cr = p.circle(...)

# easily use `cr` in tools, set its properties, etc.
hover.renderers = [cr]
cr.nonselection_glyph.fill_alpha = 0.2
```
@bokeh/dev  thoughts? I would even suggest changing this for `0.10` if we are in agreement.

**Comment by bryevdv** [comment]
Setting as discussion for now but will change to `feature` if there is agreement.

**Comment by fpliger** [comment]
+10 on this and +1 for sticking it in `0.10`... it is a very nice shortcut. 

(sorry @damianavila .. I know you like the method chaining pattern :stuck_out_tongue_closed_eyes: )

**Comment by canavandl** [comment]
I'm :+1: on this also. I've never chained glyph methods (i.e. taken advantage of the returned plot obj). I do like the easier way to "get" the renderer than using the select syntax we have.

**Comment by damianavila** [comment]
Good bye chained method... I :heart: you, but there is no place for you here... :stuck_out_tongue_winking_eye:

**Comment by bryevdv** [comment]
Trend seems to be towards agreement then. Planning for `0.10` unless there is some strenuous objection.

**Comment by almarklein** [comment]
+1

**Comment by birdsarah** [comment]
:+1: yay - i might even start liking the `plotting` interface :wink:

**Comment by pzwang** [comment]
+1
