### ISSUE TITLE
CustomJS for Widgets on bokeh webpage

### ISSUE THREAD

**Issue by rafburzy** [bokeh/bokeh#2831]
Hi,

I'm new to bokeh and tried to copy paste example with slider widget from bokeh webpage to Jupyter notebook and it was not working. The code on webpage tries to import CustomJS module but such name could not be imported:
![image](https://cloud.githubusercontent.com/assets/9870222/9773118/c4994ace-5740-11e5-8641-a915837965d4.png)

Luckily on this nbviewer page http://nbviewer.ipython.org/github/ContinuumIO/bokeh-notebooks/blob/master/tutorial/06%20-%20interactions.ipynb it is corrected and instead of importing CustomJS, it imports Callback. Then all is working fine.
![image](https://cloud.githubusercontent.com/assets/9870222/9773178/217c9cd2-5741-11e5-9279-d0bc4c259e47.png)

Can this be updated on bokeh webpage http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#cutomjs-for-widgets ? Also there is a typo instead of CustomJS it says CutomJS.

**Comment by bryevdv** [comment]
What version of Bokeh are you using? The name of this class has recently changed.

**Comment by rafburzy** [comment]
Thanks for the quick response. I'm using bokeh 0.9.0. Let me update it to see if the issue has been solved.

**Comment by rafburzy** [comment]
I've just updated to bokeh 0.9.3 and now all works fine. So it is just the typo on the webpage that requires correction.

Thanks again

**Comment by bryevdv** [comment]
Thanks!
