### ISSUE TITLE
Using HoverTool to display arbitrary HTML

### ISSUE THREAD

**Issue by FedericoV** [bokeh/bokeh#2833]
from: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/8wcXT9vExH4 - Sarah Bird suggested I post this here:

Hi,

Upon a mouse-over event, I'd like to use the hover tool to display arbitrary HTML.  Basically, what I"m doing is this:

```
for idx in plot_df.index:
    plot_df.loc[idx, 'html_str'] = post_peer_review.loc[idx, [col1, col2]].to_html()
```

and then turning plot_df into a ColumnDataSource, and using the hovertool to display 'html_str'.  This however quotes the html, and does not display it.

Unfortunately, I cannot put the actual html into the hovertool and refer to values in the ColumnSource, because the information is coming from a separate dataframe and contains a variable number of rows.  It would of course be possible to put some clever javascript to nicely format a table depending on row numbers, but it would be much nicer to let pandas handle that for me.

Is there a way to get the hovertool to display the html without quoting it?

**Comment by birdsarah** [comment]
I think this would be a nice feature - I'm thinking of some kind of `safe` mark in the tooltips (similar to what is available in many templating languages).

**Comment by cyrusmaher** [comment]
+1. My use case is I have two glyphs that need to be presented differently in the tooltip. Where would we look in the codebase to add the "safe" flag?

**Comment by cyrusmaher** [comment]
Would another solution be to optionally accept an object mapping between tooltips and renderers?

**Comment by birdsarah** [comment]
> Where would we look in the codebase to add the "safe" flag?

I would start here:
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/tool/inspectors/hover_tool.coffee#L178

**Comment by cyrusmaher** [comment]
It seems like all that's needed is to add an if statement for this line?:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/util/util.coffee#L38

**Comment by bryevdv** [comment]
I think that's probably right

**Comment by cyrusmaher** [comment]
What do you think is the best way to add that flag, then propogate it down?

**Comment by bryevdv** [comment]
defer to @birdsarah for interface ideas

**Comment by birdsarah** [comment]
I was considering just a tooltips_safe=True flag, but I think it would be better to stick with a similar  paradigm for how we format numbers using `{}` so"

````python
x = ['<p>foo</p>', '<p>bar</p>']
y = [1, 2]
z = [1.22233, 3.446546]
HoverTool(tooltips='@z{0.00} --- @x{safe}'). 
````
I think safe is pretty well known for those coming from web world. This should also be pretty straight forward to implement.

**Comment by birdsarah** [comment]
if anyone was working on this and wanted to also add the documentation for how to format numbers at the same time that would be great - see #2595

**Comment by birdsarah** [comment]
two places for the documentation:
* in the HoverTool docstring, so it appears in the reference guide: http://bokeh.pydata.org/en/dev/docs/reference/models/tools.html#bokeh.models.tools.HoverTool.tooltips
* in the UserGuide:  http://bokeh.pydata.org/en/dev/docs/user_guide/tools.html#basic-tooltips

**Comment by cyrusmaher** [comment]
Are you looking for number formatting docs like the one for `NumberFormatter`?
http://bokeh.pydata.org/en/0.10.0/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.NumberFormatter

**Comment by altosaar** [comment]
+1, I really need this to render MathML / KaTeX math expressions in labels :)

**Comment by bryevdv** [comment]
@altosaar would you have any interest in working up a PR for a `safe` flag for hover tooltips? e.g.
```
@foo[safe]
```
prevents the escaping that happens near the end of:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/util/util.coffee#L38

@mattpap there appears to be some functionality that is not documented (or I don't know where it is). What is the "full" acceptable format for tooltip spec, including prefix, long name, format, etc. and what exactly do those do.

**Comment by altosaar** [comment]
I wish I had enough experience with JS/CoffeeScript to be of use here. I'll take a look when I can to try to understand what's going on though!

**Comment by bryevdv** [comment]
no worries, I'm just trying to ask more often when I can, just in case. The number of issues and requests is rapidly outstripping the current core contributor team size

**Comment by altosaar** [comment]
I git cloned the bokeh repo, commented out this line: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/util/util.coffee#L38 

I then rebuilt bokeh, and ran `python setup.py install --build_js`

Rerun the example still doesn't work though; it looks like it's still escaping the HTML. 

Should I be commenting out additional lines to understand what the `@foo[safe]` flag functionality should be?

**Comment by bryevdv** [comment]
Bokeh loads resources from CDN by default now. Try setting the environment variable `BOKEH_RESOURCES=inline` and try running again.

**Comment by altosaar** [comment]
Thank you - that worked! 

For posterity:

I was trying to do `export BOKEH_RESOURCES=inline` then `python setup.py install --build_js` and run the example in ipython notebook, but wasn't seeing the changes - bokeh wasn't respecting the BOKEH_RESOURCES environment variable.

To fix it, I had to run a `.py` script and explicitly setting the environment variable in the same line:

`BOKEH_RESOURCES=inline python example_script.py`

This prevented the HTML escaping and I can now see math in labels.

**Comment by mattpap** [comment]
> To fix it, I had to run a .py script and explicitly pass the environment variable in the same line:

This is how it works. `BOKEH_` shell variables work together with a bokeh rendering script or jupyter notebook. They do not affect `setup.py`. They also sometimes work with bokeh server (unfortunately only sometimes - this needs to be fixed).

**Comment by Zulko** [comment]
Just in case: has anyone found a workaround for this issue ?

**Comment by astraw38** [comment]
@Zulko 

I changed bokeh-0.12.3.js as follows to enable using ``@val{safe}`` (where val is the datatable column name):


```js
replace_placeholders = function(string, data_source, i, special_vars) {
  if (special_vars == null) {
    special_vars = {};
  }
  string = string.replace(/(^|[^\$])\$(\w+)/g, (function(_this) {
    return function(match, prefix, name) {
      return prefix + "@$" + name;
    };
  })(this));
  string = string.replace(/(^|[^@])@(?:(\$?\w+)|{([^{}]+)})(?:{([^{}]+)})?/g, (function(_this) {
    return function(match, prefix, name, long_name, format) {
      var ref, replacement, value;
      name = long_name != null ? long_name : name;
      value = name[0] === "$" ? special_vars[name.substring(1)] : (ref = data_source.get_column(name)) != null ? ref[i] : void 0;
      if (value == null){
          replacement = "???";
      }
      else if (format != null){
        if (format == "safe"){
          return "" + prefix + value;
        }
        else {
          replacement = Numbro.format(value, format)
        }
      } else {
        replacement = _format_number(value);
      }
      return "" + prefix + (_.escape(replacement));
    };
  })(this));
  return string;
};
```

**Comment by bryevdv** [comment]
@astraw38 perhaps you could submit a PR for this feature?

**Comment by astraw38** [comment]
Sure! I meant to, but got swamped with other work. I'm assuming you'll need some tests for it as well?

**Comment by bryevdv** [comment]
@astraw38 

* add a note the this "Hover Tool" section of [this users guide chapter](https://raw.githubusercontent.com/bokeh/bokeh/master/sphinx/source/docs/user_guide/tools.rst)
* add some info to [this docstring](https://github.com/bokeh/bokeh/blob/master/bokeh/models/tools.py#L619)
* add a small example (or update and existing one) to demonstrate the use
* have some kind of tests, though I note that there is currently no unit tests for anything in `core/util/templating.coffee`: https://github.com/bokeh/bokeh/tree/master/bokehjs/test/core/util

Of course, we'd be happy to help answer questions or give guidance about any or all of those, and collaborate directly on your branch, if you only have time to do some of them
