### ISSUE TITLE
bokeh/sampledata/us_states.py has lots of extra data points in Florida and California

### ISSUE THREAD

**Issue by afonit** [bokeh/bokeh#284]
As I was working on some visualizations, I noticed Florida and California both have  extra data in them:

![example_a](https://f.cloud.github.com/assets/1798497/1927681/e60c8ac0-7e63-11e3-9bbe-6a27b1163210.png)

from looking at:
http://continuumio.github.io/bokehjs/map_overlay.html
this was not always the case:
![example_b](https://f.cloud.github.com/assets/1798497/1927689/4f6c3c40-7e64-11e3-86e2-2d284862a960.png)

So somewhere along the line the underlying data for us_states.py was tweaked.

Additionally, does any one have a copy of the code for that example:
http://continuumio.github.io/bokehjs/map_overlay.html
(eg the ipython notebook for it)

I am curious to see how they came up with the logic to center the fragmented pie charts on the states and how to call the centering in bokeh for the overlayed glyphs on the state patches?

**Comment by tommycarstensen** [comment]
I've used matplotlib basemap to create this map:
http://tommycarstensen.com/rasmus_12:34417063:C:T.png

Is there an example/tutorial on how to achieve the same thing with Bokeh?

**Comment by bryevdv** [comment]
@tommycarstensen the GitHub issue tracker is for bug reports and feature requests only. For general support questions please use the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
