### ISSUE TITLE
Change the "text_align" field of the Text glyph class from Enum to StringSpec

### ISSUE THREAD

**Issue by PythonicPrime** [bokeh/bokeh#2840]
Currently "text_align" accepts an Enum of (left, right, center)

The field could instead accept a StringSpec list, similarly to how "text_color" accepts a ColorSpec list of colors, or "text" accepts a StringSpec list of strings

The use case is, for example, a classic bar chart made with Rects: when aligning the text labels to the bar chart, the positive values need to be aligned left, and the negative values need to be aligned right

Same change could be applied to "text_baseline" for the other direction of alignment

**Comment by bryevdv** [comment]
Just noting that to do this properly, should create an `EnumSpec` so that at least single values (the common case) are still validated against the enum. Also noting that this ought to apply to `LabelSet` as well.

**Comment by mattpap** [comment]
This was implemented in PR #10788.
