### ISSUE TITLE
Slider not responsive to attribute change

### ISSUE THREAD

**Issue by PythonicPrime** [bokeh/bokeh#2842]
Slider seems not to be listening to changes in "title" or "value", which are not rendered

**Comment by bryevdv** [comment]
@PythonicPrime can you confirm if this is still an issue with Bokeh `0.11.1` or newer? If so, can you can you provide a complete, minimal, runnable example of code that reproduces the problem, so that we can use it to start an investigation?

**Comment by PythonicPrime** [comment]
Hello Bryan, how is it going?

I was unable to upgrade from 0.10 to 0.11 (some of the custom libraries I developed to access the Backbone objects in JS break in the change, andI have not yet figured out how to fix them)

Will update on this once I manage to move to 0.11

**Comment by PythonicPrime** [comment]
To note: I believe this was an issue in 0.9, I have been using jquery sliders since posting this, so it is likely that the problem was already solved in 0.10

**Comment by bryevdv** [comment]
closing as stale, as no reports of problems like that have surfaced since the second gen bokeh server
