### ISSUE TITLE
Handling missing categorical values

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#2845]
Looking [here](http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#missing-points), missing values are handled by using NaN.

This seems to only work with numeric data.  When trying to plot lines with a categorical axis, putting NaN in errors the whole plot out.

In the case of plotting things like points, it is easy to handle missing values because you can just remove the whole record.  But when plotting lines, the missing value means that there should be a break in the line.  This should work for categorical as well as quantitative axes.

Here are two jsfiddles:

With NaN on x axis:
http://jsfiddle.net/s2Lkghbb/1/

With NaN on y (categorical) axis:
http://jsfiddle.net/8n0vw4tL/1/

**Comment by bryevdv** [comment]
@hafen can you point to an example in some other context that demonstrates this use-case? I am trying to imagine what exactly it means.

**Comment by bryevdv** [comment]
lots of work between then and now, closing until/unless a reproducer
