### ISSUE TITLE
Bug: Bokeh app member variable issues (__init__ and naming)

### ISSUE THREAD

**Issue by xdliao** [bokeh/bokeh#2847]
I tried to add some member variables to store some data for each object of SlidersApp
such as 

     class SliderApp(VBox):
    
          def __init__(self,*args,**kwargs):
            super(IVMMEdgeAnalyticsApp,self).__init__(*args,**kwargs)
            print "__init__ called!"
            self._raw_data = [1,2,3]

Problem 1: declaring the variable without underscore "\_"  (self.raw_data) causes unknown attribute error when trying to access it from other member functions
Problem 2: on each event (slider change), __init__ is called and the variable is reinitialized

The only way I could do is to use a global dictionary to cache these data using 
self.ref_id as key (seems that the same wed session is uniquely identified by ref_id even
though the instance id: id(self)  changes during the life cycle of the session.

Is there a way to add any member data which is not of type Plot,Widgets..

**Comment by bryevdv** [comment]
This refers to the old (and completely removed) `bokeh-server`, closing. Please see the examples in:

https://github.com/bokeh/bokeh/tree/master/examples/app

for current practice (which is generally simpler/easier)
