### ISSUE TITLE
Bug: x_range update for DatetimeAxis

### ISSUE THREAD

**Issue by xdliao** [bokeh/bokeh#2851]
I tried to update the x_range of a plot using p.x_range.start=new_value
and got an error. Seems that the x_range object is not initialized for datetime axis.

By the way, is there a simple call such as figure.auto_set_range() to refresh the
automatically generated  range after data source update? Also the ResetTool only remembers the initial range when the
plot is created which causes problem after data source is updated and data ranges are no longer the same.

It can be reproduced using the standard example: 
http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#datetime-axes

------------- This fails-----------
p = figure(width=800, height=250, x_axis_type="datetime") )
p.x_range.start = AAPL.Date.min()
Gets error: "ValueError: expected a value of type float, int8, int16, int32, int64, int or long, got 2000-01-03 00:00:00 of type Timestamp"

-------------------- This works --------------
p = figure(width=800, height=250, x_axis_type="datetime") ,
              x_range=(AAPL.Date.min(), AAPL.Date.max()))
p.x_range.start = AAPL.Date.min()

**Comment by bryevdv** [comment]
No, the problem is our type validation. It's expecting a time value of the "number of millesonds since epoch" variety, and you are trying to set it with some Pandas `Timestamp` object, so it is complaining with a `ValueError`. Setting from a `TimeStamp` is reasonable thing to do, just something that support for will have to be explicitly added.

**Comment by rsgoodwin** [comment]
Hi - I googled searched "bokeh x_range timestamp" and saw this older post.   The following code worked in bokeh 12.2.   i.e. it was ok to pass in a tuple of timestamps into x_range when the x_axis_type is "datetime".

However,  we recently updated to 12.5 (very happy we did),  but the code no longer works.  the ValueError is:

Code:

```
import pandas as pd
import numpy as np
from bokeh.plotting import figure, show, output_notebook
output_notebook()

# generate some data.  A datetime and some y variable.
N = 30
date_times = pd.date_range('2017-01-01', periods=N, freq='D')
df = pd.DataFrame({'date_time': date_times, 
                   'y_var' : np.random.randn(N)})

# set min and max date times for plotting
x_min = df['date_time'].min() - pd.Timedelta(days=0.1*N)
x_max = df['date_time'].max() + pd.Timedelta(days=0.1*N)

# Construct the plot
p1 = figure(x_axis_type='datetime',
            x_range = (x_min, x_max),
            plot_width=700, plot_height=400)

# add points and line
p1.line(df.date_time, df['y_var'])
p1.circle(df.date_time, df['y_var'])

# de-spine the minor ticks (looks better by default)
p1.yaxis.minor_tick_line_alpha=0

show(p1)

```
ValueError: expected an element of either Tuple(Float, Float), Seq(String) or Instance(Range), got (Timestamp('2016-12-29 00:00:00'), Timestamp('2017-02-02 00:00:00'))

**Comment by rsgoodwin** [comment]
Note:  in the meantime,  the workaround is to pass in x_range as a tuple of floats.  But which floats?  Took me some trial and error to figure this out,  so I thought I would re-post with the code that works.  

Basically,  cast the timestamp into a float by calling timestamp() and divide by 1000:

`x_range = (x_min.timestamp()*1000, x_max.timestamp()*1000),`

that small changes makes it work.

**Comment by bryevdv** [comment]
sorry, I should have mentioned that explicitly in my comment above. In any case, we will get it better sorted for `0.12.7`

**Comment by bryevdv** [comment]
This was fixed at some point, the code above now runs as expected.

**Comment by p9raffi** [comment]
Not sure if I am doing this wrong or if it wasn't fully sorted out, but when I do this:

`p.x_range.start=(df.iloc[:100].index.min())`

I get:

> ValueError: expected a value of type Real, got 2017-09-03 17:00:00 of type Timestamp

Doing this fixes it:

`p.x_range.start=(df.iloc[:100].index.min().value // 10 ** 9) * 1000`
