### ISSUE TITLE
High level charts are crashing Python

### ISSUE THREAD

**Issue by extratoro** [bokeh/bokeh#2859]
Hi,
did not find anything regarding this error. And not sure how to correct it.

When executing the code from the bar chart's [documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#bar-and-dot-charts), python is crahsing.
"Manual" charts are working correctly.
I am using conda 3.17.0, python 2.7.8 and bokeh is on 0.9.3 on a win7 and win10 64bits.

It seems to be related to hdf5 (though I do not know what this means or how it's used).

Nom de l’application défaillante python.exe, version : 0.0.0.0, horodatage : 0x53b4679e
Nom du module défaillant : hdf5.dll, version : 0.0.0.0, horodatage : 0x55887bd2
Code d’exception : 0x40000015
Décalage d’erreur : 0x0000000000021ad9
ID du processus défaillant : 0x2670

**Comment by extratoro** [comment]
I have the same problem with bokeh server. Here is the log:

 SUMMARY OF THE HDF5 CONFIGURATION
      =================================

General Information:
-------------------
                   HDF5 Version: 1.8.15-patch1
                  Configured on:
                  Configured by: Visual Studio 9 2008 Win64
                 Configure mode: CMAKE 3.2.3
                    Host system: Windows-5.2
              Uname information: Windows
                       Byte sex: little-endian
                      Libraries:
             Installation point: C:/aroot/stage/Library

Compiling Options:
------------------
               Compilation Mode: Release
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/x86_amd64/cl.exe
                         CFLAGS:  /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS:
                      AM_CFLAGS:
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
               Shared Libraries: YES
               Static Libraries: NO
  Statically Linked Executables: OFF
                        LDFLAGS:  /machine:x64
                     AM_LDFLAGS:
                Extra libraries: C:/aroot/stage/Library/lib/z.lib;C:/aroot/stage/Library/lib/z.lib
                       Archiver:
                         Ranlib:
              Debugged Packages:
                    API Tracing: OFF

Languages:
----------
                        Fortran: OFF
               Fortran Compiler:
          Fortran 2003 Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/bin/x86_amd64/cl.exe
                      C++ Flags:  /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags:
                   AM C++ Flags:

**Comment by bryevdv** [comment]
The HDF dependency always should have been optional, but in any case, it has been removed entirely since 0.9.3. That said, the particular issue seems to be some sort of upstream packaging problem.

**Comment by bryevdv** [comment]
You can try a recent dev build here: http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds or `0.10` will be out later this month.
