### ISSUE TITLE
Callbacks for all Select Tools

### ISSUE THREAD

**Issue by avanetten** [bokeh/bokeh#2860]
Currently, BoxSelectTool has callbacks enabled, but LassoSelectTool and PolySelectTool to do not.  It would be nice to be able to recreate with LassoSelect or PolySelect the custom box drawing of:
http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#customjs-for-tools

**Comment by respatialized** [comment]
I'd like to know what the priority for this feature is, and whether a solution to the issue I opened at #5829 might make this more feasible.

**Comment by bryevdv** [comment]
This is now possible with `bokeh.events`, which exposes selection geometries to both JS and python event callbacks.
