### ISSUE TITLE
GMap improvements

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2861]
As discussed on #1335 and some other random thoughts:
- [ ] don't trample on the data - currently if you wanted to, for example, add a hovertool with your latlongs in it, you'd need to duplicate your columns because we change the data values when we project. we should add new columns to the column data source and re-reference them.
- [ ] don't require a range input on instantiation - it's always going to be Range1d and we're going to trounce over whatever you set it to when we do the conversion anyway
- [ ] have a latlong ticker that converts back from mercator - add an attribute to range so you know if it's projected and in what coordinate space, that could let you go back and forth
- [ ] be able to format latlong in other latlong formats, not just decimal e.g. 50°52′10″N 115°39′03″W
- [ ] make reset work
- [ ] offer some kind of resize that preserves aspect ratio
- [ ] can we get smoother zoom (google maps increments zoom in 0.2 decimal increments)
- [ ] make zoom throttling user configurable
- [ ] check this works for streaming / updating data
- [ ] should it really be a chart function that uses a more generic low-level map plot. There's a whole bunch of stuff you want to pre-configure & specify that's pretty custom but you can't do whatever you want with it - so doesn't really feel like a plot any more.  I can imagine a low-level MapPlot that has helper functions for things like projecting ranges etc and then a series of geo charts that are all setup ready to go with arguments - like tick_format='decimal'.
- [ ] factor out projection code - https://github.com/bokeh/bokeh/pull/2857#discussion_r39656267

**Comment by bryevdv** [comment]
I was not aware of the non-integer zoom increments. We should maybe make that change immediately.

**Comment by birdsarah** [comment]
> I was not aware of the non-integer zoom increments. We should maybe make that change immediately. 
I can't figure out how to make it work properly so far though - I just get blank screens at lots of sub-increments.

**Comment by bryevdv** [comment]
Most of this was done for `0.12.5`
