### ISSUE TITLE
Respect <br> newlines in value strings for HoverTool tooltips

### ISSUE THREAD

**Issue by nrhine1** [bokeh/bokeh#2866]
Currently, there seems to be no way separate items in a tooltip with newline without writing a complicated CustomJS callback for the HoverTool or editing bokeh.js. This is an issue when items to be displayed are formatted into a long string, which can result in tooltips that violate the boundaries of the plot. When each data point is associated with a variable number of entries to be displayed, this becomes useful. A simple, yet inelegant, fix is presented here:

http://stackoverflow.com/a/32616279/209246

Here are images of the before and after behavior after applying the solution:

![0h1su](https://cloud.githubusercontent.com/assets/372326/9914874/f701702c-5c81-11e5-929d-53273dad6b84.png)

![fixed](https://cloud.githubusercontent.com/assets/372326/9914838/cef5e5b8-5c81-11e5-866c-c12d90cf844b.png)

**Comment by birdsarah** [comment]
Currently, I would do this with a custom tooltip. http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#custom-tooltip

You could argue that you don't want to have write out a custom tooltip, but there's certainly no need to write CustomJS to achieve this.

**Comment by nrhine1** [comment]
Can you elaborate on how you could iterate over variable sized entries in items with HTML only? (the 'items' entry for each data point is of arbitrary size)

**Comment by bryevdv** [comment]
You would need to apply your own CSS styling so that text inside a div word-wrapped. Here is an example:

http://jsfiddle.net/audetwebdesign/pTH6Y/

**Comment by nrhine1** [comment]
Ah, that's simple. Thanks!

**Comment by bryevdv** [comment]
@damianavila `discussion` doesn't need a `reso`?

**Comment by damianavila** [comment]
`discussion` **does not need** a milestone (although it could have one), but they **need** a `reso`... when a discussion is closed, I apply the more convenient `reso` label and attach the milestone because it was resolved in that time frame...
