### ISSUE TITLE
Review which examples from examples folder are run

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2873]
Having noticed that the charts tests weren't running as part of #2870, I found the file https://github.com/bokeh/bokeh/blob/master/tests/travis/test.yaml

Looking at this, as far as I can tell, we are also not running tests for:
- app
- cli
- interactions

We should revise this and see what examples we should be running and whether this is still the right set to be skipping.

**Comment by birdsarah** [comment]
Also worth noting at the same time I'm not sure the ipython notebook tests are running as we hope.

**Comment by birdsarah** [comment]
assigning @damianavila so he can look at the ipython notebooks not running. here's a screenshot from a recent run:
<img width="955" alt="screen shot 2015-09-17 at 1 09 37 pm" src="https://cloud.githubusercontent.com/assets/1796208/9944635/712a4bf6-5d3d-11e5-9517-c4e0bd25a6b8.png">

**Comment by bryevdv** [comment]
closing as stale (all those dirs are gone)
