### ISSUE TITLE
Is 'datetime' supposed to work the same for line plots as it is for bar charts?

### ISSUE THREAD

**Issue by jelmelk** [bokeh/bokeh#2883]
I created a line chart the image below using this code:

```
p=figure(x_axis_type='datetime')
p.line(df.index,df.counter, line_width=2)
show(p)
```

[![enter image description here](http://i.stack.imgur.com/48Z9R.png)](http://i.stack.imgur.com/48Z9R.png)

However, if I try to do the same using a bar chart with this code:

```
data = {"x":df.counter}
b = Bar(data, xscale='datetime')
show(b)
```

the scale is not correct:

[![enter image description here](http://i.stack.imgur.com/ZhXYf.png)](http://i.stack.imgur.com/ZhXYf.png)

Any possible reason to this, and could it be fixed?

**Comment by rothnic** [comment]
We are currently reworking Charts, initial PR being #2870, to be a bit closer to what you'd see from ggplot or the previous pandas plotting utils, so this will change anyways. I think what is happening is that it is using non-datetime data to produce a datetime scale.

As for line vs. bar, the chart will need to turn a potentially continuous-like time variable into a discrete one by binning and aggregating, which technically you could do with a line as well. The difference for you is that you are comparing a line glyph to a bar chart, which operate at different levels. The equivalent of the line glyph is the rect glyph, which would give you full control on what happens, but the rect glyph is a bit more involved to use than just passing x and y.

**Comment by jelmelk** [comment]
Thank you for the information. Can you please elaborate more on "it is using non-datetime data to produce a datetime scale".

I figured that they must operate on different levels, that's why the results are different. I'll get working on rect glyphs for the time being.

**Comment by bryevdv** [comment]
@jelmelk can you confirm if this is still an issue with Bokeh `0.11.1` or newer? If so, can you provide a complete, minimal, runnable example to reproduce the issue, that we can use to start an investigation?

**Comment by jelmelk** [comment]
The problem still exists, so at this point, I'm not sure if utilization might be the issue (`xscale` for bar charts, `x_axis_type` for lines)

```
import pandas as pd
import random
from bokeh.plotting import figure, show, output_notebook
from bokeh.charts import Bar

 rng = pd.date_range('1/1/2016', periods=72, freq='H')
myList = []
for i in range(72):
    myList.append(random.randint(100,500))

df = pd.DataFrame(data=myList, index=rng, columns=['count'])

output_notebook()

p = figure(width=800, height=250, x_axis_type="datetime")
p.line(df.index, df['count'], color='navy', alpha=0.5)
show(p)

b = Bar(df, label='count', xscale='datetime')
show(b)
```
I would have two columns in a dataframe, one is a `DatetimeIndex` and the other is the count. What I'm trying to achieve is being able to get the same x-axis format for bar as it is in the line figure

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/61)
