### ISSUE TITLE
Don't include entire bokeh.{js,css} inside the repository

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#2885]
An example is `bokeh/tests/myplot.html`. I'm not sure if this is even used anywhere (quick grep gave nothing). Note this increases significantly the size of the repository every time this file is updated and makes `git grep` harder to use.

**Comment by bryevdv** [comment]
+1

**Comment by birdsarah** [comment]
:+1: 

agreed on myplot.html - if its used the tests should fail without it and we can refactor them. if they don't fail then we should be able to get rid of it.

**Comment by mattpap** [comment]
It looks like `myplot.html` was added by accident in:
```
$ git log bokeh/tests/myplot.html
commit b89f96ab31563a825259ce2fc3d3296f60bea722
Author: Bryan Van de Ven <bryanv@continuum.io>
Date:   Thu Feb 26 09:13:51 2015 -0600

    simplify -- all funcs use default state (explicit states can just be manipulated directly with their methods)
```
I will just remove it.

**Comment by bryevdv** [comment]
Thanks sorry for the cruft.
