### ISSUE TITLE
Allow static data in a ColumnDataSource

### ISSUE THREAD

**Issue by anoother** [bokeh/bokeh#2886]
It would be nice to be able to provide static data in a ColumnDataSource, for eg. tooltips.

For example, I have a figure, with a number of line plots showing device temperatures. On hover, I would like to show device metadata - something which remains constant throughout the line, but differs between lines.

Currently, I have to do something like the following (see the `* len(readings)` stuff):

``` python
for device in dataframe:
        series = data[device]['temperatures']
        data_dict = {      
            'date': series.index, 
            'temperature': series.values,          
            'model': [data[device]['model']] * len(readings)
            'location': [data[device]['location']] * len(readings),
            'serial': [device] * len(readings),  
        }            
        source = plt.ColumnDataSource(data=data_dict)

        p.line(x='date', y='temperature', source=source)
        ...

hover = HoverTool(tooltips={
    'model': '@model',
    'location': '@location',
    'serial': '@serial',
})

p.add_tools(hover)
```

This is fine, except it's not lazily evaluated, so we end up with lots of generated data. Something that works akin to `itertools.repeat()` would be nice...

**Comment by tonyfast** [comment]
There are a few ways you could achieve the effect you are looking for.  

* You could use [custom tooltips](https://github.com/bokeh/bokeh/pull/2790) for each device you are visualizing.
* You could overlay glyphs and assign different tooltips the glyphs.  Check out [these notebooks for more on assigning different HoverTools to renderers](http://nbviewer.ipython.org/gist/tonyfast/986be221c6fb68286e74/).

**Comment by anoother** [comment]
I'll give those a try. Thanks!

**Comment by bryevdv** [comment]
Closing, this seems like a support/usage question
