### ISSUE TITLE
Something in bokeh.util.testing.py breaks making the docs

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2888]
After c6f0051a9352ad32cdf8f91496656c366d717944 and before fd2e7f4a41455a551aa4e9635a9ca41214c44c81 the docs were broken.

This must be because of something in the `bokeh.util.testing.py` file that was being imported by `bokeh.__init__.py`

We should identify what that was and maybe have a better cleanup of this in general. 

Could all the utils in there go in a conftest.py file?

**Comment by bryevdv** [comment]
@birdsarah this is fixed? (docs seem buildable...)

**Comment by bryevdv** [comment]
As docs are building, I have to believe this was resolved. Please re-open if there is still some outstanding issue.
