### ISSUE TITLE
Support multiple None entries per row in GridPlot

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#2891]
So I've just been playing around with adding marginal plots to the bokeh backend in [HoloViews](http://holoviews.org) and ran into some problems. When trying to embed a plot with marginals in a ``GridPlot`` the other rows and columns have to be padded with Nones, this often means inserting multiple ``None`` values in a single row. Here is an example of what I mean based on the ``gridplot`` example in the docs:

```python
import numpy as np
from bokeh.plotting import figure, gridplot, GridPlot, show, output_notebook

output_notebook()

N = 50

x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)

TOOLS = "pan,wheel_zoom,box_zoom,reset,save,crosshair"

l = figure(title="line", tools=TOOLS, plot_width=300, plot_height=100)
l.line(x,y)

aw = figure(title="annular wedge", tools=TOOLS, plot_width=100, plot_height=300)
aw.annular_wedge(x, y, 10, 20, 0.6, 4.1, inner_radius_units="screen", outer_radius_units="screen")

bez = figure(title="bezier", tools=TOOLS, plot_width=300, plot_height=300)
bez.bezier(x, y, x+0.4, y, x+0.1, y+0.2, x-0.1, y-0.2)

q = figure(title="quad", tools=TOOLS, plot_width=300, plot_height=300)
q.quad(x, x-0.2, y, y-0.2)

# specify "empty" grid cells with None
p = GridPlot(children=[[None, l, None], [q, bez, aw]])

show(p)
```

![image](https://cloud.githubusercontent.com/assets/1550771/9981111/dbfda472-5faa-11e5-9868-ad72a8d90573.png)

As you can see the ``aw`` plot ends up on the left of the second column, rather than what I'd expect:

```
________________________
|  None  |  line  |None|
------------------------
|        |        |    |
|  quad  | bezier | aw |  
|________|________|____|
```

Similarly when shuffling the plots around a little bit and specify two consecutive Nones:

```python
p = GridPlot(children=[[l, None, None], [q, aw, bez]])
show(p)
```

![image](https://cloud.githubusercontent.com/assets/1550771/9981130/d2ca69ca-5fab-11e5-9d95-c013ba8b36b0.png)

In this case you can see that it has actually dropped the quad plot completely. I've had a brief look to see why this doesn't already work but I got as far as the constraint solver but wanted to get your input before digging further.

It would be really great if this could be made to work as it would allow for some more flexible plot layouts. For now I suppose I can insert empty plots rather than Nones into the layout.

Edit:

Just implemented a workaround that inserts empty plots instead, I'll leave it here as a reference for the output I was hoping for:

![image](https://cloud.githubusercontent.com/assets/1550771/9982113/d8e724d4-5fc8-11e5-8176-8e51308540bd.png)

**Comment by birdsarah** [comment]
Verify as part of #4392

**Comment by birdsarah** [comment]
Confirmed this is working with the new `bokeh.layouts.gridplot` function. See screenshots below. Fixed in #4343. Big thanks to @philippjfr for providing a full working code sample - made this easy to test.

<img width="778" alt="screen shot 2016-06-15 at 4 21 50 am" src="https://cloud.githubusercontent.com/assets/1796208/16077977/fa657ba4-32b0-11e6-93dd-70c2ec43d659.png">

<img width="733" alt="screen shot 2016-06-15 at 4 21 07 am" src="https://cloud.githubusercontent.com/assets/1796208/16077987/02b35092-32b1-11e6-81e2-f16823bffc8b.png">

@philippjfr Note the new rotated side titles can cleanly accommodate the long annular wedge title:

<img width="739" alt="screen shot 2016-06-15 at 4 26 07 am" src="https://cloud.githubusercontent.com/assets/1796208/16078052/4f00cb28-32b1-11e6-9a16-d007ad9791c9.png">

@canavandl - is it me or is that right title just very slightly mis-aligned?

**Comment by birdsarah** [comment]
Here's the slightly updated code to produce the last example

```python
import numpy as np
from bokeh.plotting import figure
from bokeh.layouts import gridplot
from bokeh.io import show

N = 50

x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)

TOOLS = "pan,wheel_zoom,box_zoom,reset,save,crosshair"

l = figure(title="line", tools=TOOLS, plot_width=300, plot_height=100)
l.line(x,y)

aw = figure(title="annular wedge", title_location='right', tools=TOOLS, plot_width=100, plot_height=300)
aw.annular_wedge(x, y, 10, 20, 0.6, 4.1, inner_radius_units="screen", outer_radius_units="screen")

bez = figure(title="bezier", tools=TOOLS, plot_width=300, plot_height=300)
bez.bezier(x, y, x+0.4, y, x+0.1, y+0.2, x-0.1, y-0.2)

q = figure(title="quad", tools=TOOLS, plot_width=300, plot_height=300)
q.quad(x, x-0.2, y, y-0.2)

# specify "empty" grid cells with None
p = gridplot(children=[[None, l, None], [q, bez, aw]])

show(p)
```

**Comment by philippjfr** [comment]
Brilliant @birdsarah. You're all amazing and the layout overhaul is shaping up to be really great.
