### ISSUE TITLE
Need help with the plot streaming on a third-party client

### ISSUE THREAD

**Issue by episodeyang** [bokeh/bokeh#2892]
Hi All,

I just wrote a real-time collaborative jupyter client for my lab. It handles large notebook files very well and I just got bokeh plotting to work! (this is hard because bokeh plots are a few mB)

I am having trouble getting the streaming to work at the moment. Would some of you mind have a look? The reason I'm asking for help here is because in our setup the webclient served from a domain different from the bokeh-sever itself, and I keep getting connection error. 

Any help would be very appreciated. Our lab is trying to setup a data dashboard the streaming would be something very nice to have.

Here is what I have, feel free to message me on gitter! https://gitter.im/escherpad/help-desk

http://lesquare.escherpad.com/@yang.ge/A-Collaborative-Real-time-iPython-Jupyter-Client-for-Self-hosted-Jupyter-Servers-tcwtda0jqgbb

[![real-time collaborative iPython notebook demo](http://img.youtube.com/vi/si0QFaDStoo/maxresdefault.jpg)](http://www.youtube.com/watch?v=si0QFaDStoo)

Best, 
Ge

**Comment by bryevdv** [comment]
Sorry for not seeing this earlier, but that video shows the use of Matplotlib inside Jupyter, and has nothing to do with Bokeh.

**Comment by damianavila** [comment]
The bokeh server has been rewritten and you, probably, need to test it inside your setup. Feel free to reopen this if you find the same kind of problem with the new implementation.
