### ISSUE TITLE
CI error on current master (404/410 error with ggplot example notebook)

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#2897]
Maybe you are already aware of this. I believe it to be a sporadic failure, but I saw it when Travis CI ran `master` with the latest commit on my fork. ( https://travis-ci.org/jakirkham/bokeh/jobs/81420300 )

**Comment by bryevdv** [comment]
Closing, as I believe this has been resolved, although I think there are other new intermittent CI issues (but they are being addressed elsewhere)
