### ISSUE TITLE
White background does not increase size when resizing bigger than original size

### ISSUE THREAD

**Issue by samaust** [bokeh/bokeh#2898]
Tested on 0.9.3 release
When resizing larger than the original width and height, the white background behind the plot does not increase size. See screenshots below with a blue background.

Original size :
![original size](https://cloud.githubusercontent.com/assets/10716165/10010685/b4505920-60bc-11e5-8e93-6c00828406be.jpg)

Smaller :
![smaller](https://cloud.githubusercontent.com/assets/10716165/10010687/b7e95618-60bc-11e5-8c19-30d9f9090090.jpg)

Larger :
![larger](https://cloud.githubusercontent.com/assets/10716165/10010690/bc53fb54-60bc-11e5-90cf-c6bc8a7ab79d.jpg)

**Comment by bryevdv** [comment]
This has since been fixed (and is a dupe, but I can't find the other issue)
