### ISSUE TITLE
Paragraph text options

### ISSUE THREAD

**Issue by avanetten** [bokeh/bokeh#2905]
It would be nice to be able to format the Paragraph widget (http://bokeh.pydata.org/en/latest/docs/reference/models/widgets.markups.html)  akin to Plot titles (title_text_font, title_text_align, etc.).

**Comment by bryevdv** [comment]
A better (much simpler) short term solution: just allow configuration of a CSS class and/or id, so that users can style with their own CSS.

**Comment by artdijk** [comment]
Why only CSS. I think it is usefull if you can add HTML as well. That make s paragraph a kind of Iframe. Or maby add a widget iframe !

**Comment by bryevdv** [comment]
Closing this. `<p>` tags can't contain any markup inside them:

https://stackoverflow.com/questions/5441639/how-can-i-put-div-in-p

And trying to synthesize CSS to match python properties (when users could just set the CSS themselves) is a non-starter
