### ISSUE TITLE
reverse axis range with autoscale

### ISSUE THREAD

**Issue by bsipocz** [bokeh/bokeh#2907]
It would be very useful to be able to reverse the axis range while still having the autoscale mode on. 
It looks like that it's a missing feature, at least I didn't spot it in the docs or in the source code.

**Comment by tonyfast** [comment]
Can you expand on this a little further?  

Would you like to reverse the values on an axis and still take advantage of the scaling interactions?

Also, here is a discussion about [reversing axes](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/CJAvppgQmKo).

**Comment by bsipocz** [comment]
No, sadly the example doesn't work in my case as it sets a range for the figure. It may have worked if the second part would, when the range is given to the line object and not the figure, thus a different range could be assigned for each call.

My usecase is an interactive plot of time series of different objects that are selected from a scatterplot using a CustomJS callback. The y axis range is about 7 for all the objects, while the scatter for an individual one is at maximum around 1, but often only ~0.2. So I really need the the autoscale functionality when changing objects, otherwise the plot becomes meaningless.

**Comment by VelizarVESSELINOV** [comment]
Looks like very basic functionality in the other plot libraries (```invert_yaxis()```), I'm surprised that reverse axis is forcing you to know min, max before you put the data. I hope the discussion will be transformed into real action one day :+1:

**Comment by bryevdv** [comment]
`DataRange1d` models exposed a `flipped` property in a recent PR:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/ranges.py#L94

The can also now  auto-follow the leading or trailing edge of streaming or updating data within a fixed window.

**Comment by VelizarVESSELINOV** [comment]
Thanks, much appreciated :)
