### ISSUE TITLE
Open a bokeh-slickgrid fork

### ISSUE THREAD

**Issue by PythonicPrime** [bokeh/bokeh#2908]
As hinted in a post in the the forums (link at bottom), fork slickgrid to update it as a base for datatables:

To note a user on github has already done some work updating from mliebman's last updates:
https://github.com/6pac/SlickGrid

Post: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/-q-Uqs2tOOk

**Comment by datnamer** [comment]
@PythonicPrime  check out #2937

**Comment by damianavila** [comment]
Closing this one to continue the discussion on one place: #2937
