### ISSUE TITLE
FAQ code block needs wrap

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2911]
In the "Troubleshooting" section of the FAQ, the code block explaining touch events on Chrome extends beyond the normal line wrap:

<img width="1014" alt="screen shot 2015-09-25 at 1 15 28 pm" src="https://cloud.githubusercontent.com/assets/2198981/10108644/c30c5cf2-6387-11e5-91e3-af7503786113.png">

**Comment by bryevdv** [comment]
The FAQ will now live on the new site, it's still long line but now it has a scrollbar and I think that's ok

<img width="1269" alt="screen shot 2015-12-28 at 10 17 32 pm" src="https://cloud.githubusercontent.com/assets/1078448/12029446/e65e6c22-adb0-11e5-934d-a6d7d5b9ff5b.png">
