### ISSUE TITLE
Enable pip install from bokeh github repo

### ISSUE THREAD

**Issue by dennisobrien** [bokeh/bokeh#2912]
It would be nice to be able to install Bokeh from a github repo.  Many projects manage dependencies by using pip's requirements.txt.  Currently bokeh will not install from the github repo for a few reasons:

1. wait for user input on whether to build bokehjs or use an existing build
1. wait for user input on whether to delete an existing bokeh install before installing the new build
1. the build requires `npm install` being run on a fresh git clone.
1. building from a repo runs as `python setup.py egg_info`

The first two cases could be addressed by inputs with timeouts.  If no input is entered in some time frame (say 30 seconds) then the default value is used.

The last two cases can be fixed by some minor changes to setup.py.

I'm new to building bokeh, so I'm not sure what all the fallout might be from timed inputs or what reasonable default values are.

Here's a proposed patch that tries to address the three points:

```
diff --git a/setup.py b/setup.py
index b98eca9..2bace68 100644
--- a/setup.py
+++ b/setup.py
@@ -188,12 +188,23 @@ def getsitepackages():
     return sitepackages


+def input_with_timeout(prompt, timeout=30, default=None):
+    import select
+    print(prompt, end=" ")
+    i, o, e = select.select([sys.stdin], [], [], timeout)
+    if i:
+        val = sys.stdin.readline().strip()
+    else:
+        val = default
+    return val
+
+
 def check_remove_bokeh_install(site_packages):
     bokeh_path = join(site_packages, "bokeh")
     if not (exists(bokeh_path) and isdir(bokeh_path)):
         return
     prompt = "Found existing bokeh install: %s\nRemove it? [y|N] " % bokeh_path
-    val = input(prompt)
+    val = input_with_timeout(prompt, timeout=30, default="N")
     if val == "y":
         print("Removing old bokeh install...", end=" ")
         try:
@@ -261,8 +272,13 @@ def build_js():
     try:
         proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
     except OSError as e:
-        print(BUILD_EXEC_FAIL_MSG % (cmd, e))
-        sys.exit(1)
+        try:
+            # attempt to run `npm install`
+            subprocess.call(['npm', 'install'], shell=False)
+            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
+        except OSError as e:
+            print(BUILD_EXEC_FAIL_MSG % (cmd, e))
+            sys.exit(1)
     finally:
         os.chdir('..')

@@ -354,7 +370,7 @@ build process. How would you like to handle BokehJS:
 2) install last built BokehJS from bokeh/bokehjs/build
 """)
     mapping = {"1": True, "2": False}
-    value = input("Choice? ")
+    value = input_with_timeout("Choice? ", timeout=30, default="1")
     while value not in mapping:
         print("Input '%s' not understood. Valid choices: 1, 2\n" % value)
         value = input("Choice? ")
@@ -408,12 +424,14 @@ if len(sys.argv) == 2 and sys.argv[-1] == '--install_js':
     sys.exit(0)

 # check for 'sdist' and make sure we always do a BokehJS build when packaging
-if "sdist" in sys.argv:
+if "sdist" in sys.argv or "egg_info" in sys.argv:
+    cmd_arg = "sdist"
+    if "egg_info" in sys.argv: cmd_arg = "egg_info"
     if "--install_js" in sys.argv:
-        print("Removing '--install_js' incompatible with 'sdist'")
+        print("Removing '--install_js' incompatible with '{}'".format(cmd_arg))
         sys.argv.remove('--install_js')
     if "--build_js" not in sys.argv:
-        print("Adding '--build_js' required for 'sdist'")
+        print("Adding '--build_js' required for '{}'".format(cmd_arg))
         sys.argv.append('--build_js')
```

There are a few existing issues similar to this:  #1419 and #1031

**Comment by dennisobrien** [comment]
The bump from @dalogsdon reminded me of this issue.  I'll try to take a look at this again soon.

**Comment by bryevdv** [comment]
> wait for user input on whether to build bokehjs or use an existing build

well, `--build-js` and `--install-js` will prevent the CLI prompt

> wait for user input on whether to delete an existing bokeh install before installing the new build

could add an option to force this 

> the build requires npm install being run on a fresh git clone.

no getting around this

> building from a repo runs as python setup.py egg_info

Not sure anything about this

**Comment by bryevdv** [comment]
Closing, I think the requirement to install `npm` makes this infeasible. Please re-open if there is a concrete implementation prototype or suggestion.
