### ISSUE TITLE
docstring args don't match Builder function

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2915]
- https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/bar_builder.py#L41
- https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/line_builder.py#L36
- https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/scatter_builder.py#L34

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/32)
