### ISSUE TITLE
A way to delay zooming so scrolling through a page doesn't stop over bokeh plots

### ISSUE THREAD

**Issue by bkreider** [bokeh/bokeh#2919]
This has annoyed me for a very long time, but i just thought of a possible solution.  When scrolling through a blog post or article with bokeh plots, the second the cursor is over a bokeh plot with zooming enabled, the plot "goes crazy" and the scrolling stops.

Is there someway to introduce a delay to capturing scroll wheel events, so casual scrolling doesn't break the UX?  For example, if the mouse cursor is only over the bokeh plot for 200ms (500ms?), pass the scroll event to the parent instead of consuming it.  Then scrolling a web page happens naturally without this abrupt break.  I'm not sure how to balance this between true positives and these false positives. You certainly don't want to make it annoying to people trying to zoom the plot.

Example:  rapidly scroll through mrockland's blog post with your cursor in the middle of your browser window.  http://matthewrocklin.com/blog/work/2015/08/28/Storage/

**Comment by bkreider** [comment]
Maybe the problem is that mousing over a plot gives it focus rather than clicking once on the canvas to give it focus?

**Comment by humm** [comment]
I do agree with bkreider. Perhaps there could be an option, when creating the figure, to only allow focus after clicking on it ? This way the old behaviour is preserved, but bokeh plots can also be part of long web pages (for instance, in jupyter notebooks), without the user needing to slalom between them to scroll down the page.

**Comment by birdsarah** [comment]
There is an open ticket about this issue here:
https://github.com/bokeh/bokeh/issues/1450
