### ISSUE TITLE
Use numbro.js instead of numeral.js for formatting numbers

### ISSUE THREAD

**Issue by dennisobrien** [bokeh/bokeh#2922]
I ran across a bug using NumberFormatter in a DataTable TableColumn that contains `Infinity` or `-Infinity` values.  This turns out to be a bug in Numeral.js.  There are several issues filed related to this, and pull requests waiting, but the project seems to have stopped active development since July 2014.  From what I gather, development has moved to the fork Numbro.
https://github.com/foretagsplatsen/numbro

This causes a JavaScript exception
```
numeral(Infinity).format("0.0")
```

while this does not
```
numbro(Infinity).format("0.0")
```

Some related links:

- https://github.com/adamwdraper/Numeral-js/issues/242
- http://numbrojs.com/format.html

**Comment by dennisobrien** [comment]
Here's an example of the error.
```
from bokeh.io import output_notebook
output_notebook()

from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, NumberFormatter
import numpy as np
import pandas as pd


# create a data frame with some np.NaN and np.Infinity values
df = pd.DataFrame(data=[[1, 2, 3], [1, np.nan, 4], [np.inf, 0, -np.inf]], columns=['x', 'y', 'z'])
source = ColumnDataSource(df)

columns = [
    TableColumn(field='x', title='x', formatter=NumberFormatter(format="0.0")),
    TableColumn(field='y', title='y', formatter=NumberFormatter(format="0.0")),
    TableColumn(field='z', title='z', formatter=NumberFormatter(format="0.0")), 
]
data_table = DataTable(source=source, columns=columns, editable=False)

show(data_table)
```

The error in the Javascript console:
`Uncaught TypeError: Cannot read property 'length' of undefined`

**Comment by damianavila** [comment]
Completed by #3883, closing here...
