### ISSUE TITLE
Turn off Bar Plot sorting by category axis labels

### ISSUE THREAD

**Issue by tvaught** [bokeh/bokeh#2924]
Bar Chart data is being sorted against my wishes. The bars should probably retain the ordering of the column that is assigned to the label attribute (the DataFrame ordering).  Perhaps a `sort` attribute could be added in the event sorting is desired.

![image](https://cloud.githubusercontent.com/assets/110926/10176201/f7b45e4e-66b8-11e5-8908-5f4d63c3d43b.png)

**Comment by tonyfast** [comment]
I think this is related to #2935

**Comment by bryevdv** [comment]
@rothnic any suggestions on a spelling for this? I imagine the implementation will not be so difficult?

**Comment by tvaught** [comment]
How about a `sort_labels=False|'ascending'|'descending' ` argument to the `Bar` call?  Not sure why `labels` was chosen as a change from `cat` (or, better yet, `categories`, but I'll trust that there was a good reason.

**Comment by euri10** [comment]
I faced the same issue and "hacked" it with while it's being investigated
```python
plt.x_range = FactorRange(factors=df['label'].tolist())

**Comment by rbinnun2** [comment]
Thanks euri10, setting the x_range does the trick.

btw, the current sorting is causing a FutureWarning: 

'''
C:\Program Files\Anaconda\lib\site-packages\bokeh\charts\_attributes.py:78: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort(columns=columns)
'''

**Comment by spawnrider** [comment]
Just had the same warning that  @rbinnun2 :+1: 
```
d:\dev\python34\lib\site-packages\bokeh\charts\_attributes.py:78: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort(columns=columns)
```

**Comment by rothnic** [comment]
There are a number of places that you would want or not want to sort with charts. On one hand, you could say just pre-sort the data, on another you'd like to specify it through the chart interface in some way because you may want to assign colors in one order, then maybe the same data is used for the labels and you want that sorted in a different way. So it would be difficult to have a data structure passed in that communicates both cases. 

So I do think we want some specification on the input, and we have that built-in to the underlying components, but it needs to be exposed through each chart interface that is more pertinent to the specific chart.

I'll also look at fixing the warning.

**Comment by ahothan** [comment]
I have the same issue for ordering bars in each group:
https://github.com/bokeh/bokeh/issues/2935

By default it should use the same order as the legend - or at least an order that the user can control.
Until this is fixed, is the current ordering random or based on some logic which we can leverage to order in the way we want?
Just would like to find a good workaround.

**Comment by rbinnun2** [comment]
euri10's suggestion should do the trick, i..e, set the order using plt.x_range.

**Comment by ahothan** [comment]
I tried that and it does not work. The order of the labels is correct in my case (alphabetical in the label) but the order of bars in each group is still the same (that is different from the order in the legend which is alphabetical in the group). Not sure the original post is exactly the same as this issue.
If you look at the chart example, you also notice that the order of the bars in the group is different from the order in the legend (http://bokeh.pydata.org/en/0.10.0/docs/user_guide/charts.html#grouping)

**Comment by fpliger** [comment]
for that concern shutting off the sorting by category (which is the topic of this issue) it is currently possible with the `0.11` charts by explicitly specifying the column Attribute being used. In the case of the posted example you can:

```python
from bokeh.charts import Bar
from bokeh.charts.attributes import ColorAttr, CatAttr
from bokeh.charts.builders.bar_builder import BarBuilder

output_file('try_select.html')
data = pd.DataFrame({'labels':['b', 'a', 'd', 'c'], 'values': [1, 2, 3, 4]}, index=[1, 2, 3, 4])
plt = Bar(data, values='values', label=CatAttr(columns=['labels'], sort=False),)
show(plt)
```

this generates:

<img width="655" alt="screen shot 2015-12-23 at 12 48 24 pm" src="https://cloud.githubusercontent.com/assets/1084690/11982743/88865fba-a973-11e5-9736-3ee467bcbfe6.png">

**Comment by fpliger** [comment]
also sorting `FutureWarning` raised due to a `pandas` API deprecation is fixed

**Comment by fpliger** [comment]
the specific issue is fixed.. ordering groupped bars issue should be discussed on the related issue: #2935
