### ISSUE TITLE
Unable to "reset" categorical labels in a streaming example

### ISSUE THREAD

**Issue by ahmadia** [bokeh/bokeh#2931]
I'm streaming a Bokeh plot where the categorical labels of the data are changing with time.  In practice, I'm keeping an active set of categories that I'd like to be visible on the plot, and I need to be able to add and remove this set with time.

In practice, I'd like to be able to set:

```
        p1.y_range = FactorRange(factors=active_urls)
```

And then:

```
        cursession().store_objects(p1)
```

Unfortunately, this doesn't appear to have any effect on the current active factors.  This might be related to https://github.com/bokeh/bokeh/issues/1056 ?

Can anybody suggest a workaround or fix?

**Comment by tonyfast** [comment]
@ahmadia you need to directly change ``p1.y_range.factors`` the snippet below should work.

```
p1.y_range.factors = active_urls
cursession().store_objects(p1)
```

Bokeh server knows the state of a model in the figure.  This allows you to change its values without using a new model instance.

I tried this out in [this notebook](http://nbviewer.ipython.org/gist/tonyfast/f16164e213e1e22c3071/cat-axes.ipynb)

**Comment by ahmadia** [comment]
That fixed it!  Thanks, Tony :)
