### ISSUE TITLE
Use only `div` and `canvas` in the generated HTML

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#2933]
Currently we use tables as well. This is an easy way to accidentally mess up plot display.

**Comment by bryevdv** [comment]
@birdsarah is this still true?

**Comment by bryevdv** [comment]
Verified that it is not:

<img width="914" alt="screen shot 2016-07-02 at 11 30 45 pm" src="https://cloud.githubusercontent.com/assets/1078448/16543751/0622b4de-40ad-11e6-90d0-845eb4322376.png">

**Comment by birdsarah** [comment]
Yep, tried to get rid of all tables in layout PR. Sorry for being late to party.

**Comment by mattpap** [comment]
> Verified that it is not:

Yet the image contains `button`, `ul`, `span`, etc. Additionally there is issue #5102 regarding similar topic.

**Comment by bryevdv** [comment]
Already satisfied for core BokehJS, need to go through widgets to remove anything that still can reasonably be removed.

**Comment by mattpap** [comment]
I inspected all code for problematic HTML tags and we are mostly good. There are a few instances of `<ul>` and `<li>` in widgets. This is inherited from bootstrap and there isn't much we can do about this, other than getting rid of bootstrap, which we should do, but it's not in the scope of this issue.
