### ISSUE TITLE
Hadley Wickham Paper on framework for visualizing large and out of core datasets

### ISSUE THREAD

**Issue by datnamer** [bokeh/bokeh#2936]
Leaving this here in case there are good ideas for bokeh abstract rendering.

http://vita.had.co.nz/papers/bigvis.pdf

**Comment by bryevdv** [comment]
I think this is more relevant to `bokeh/datashader` ping @jbednar in case the reference is new/useful (but closing this issue to clear the tracker)

**Comment by jbednar** [comment]
Interesting, thanks!
