### ISSUE TITLE
Switch to phosphor spreadsheet in lieu of slickgrid? 

### ISSUE THREAD

**Issue by datnamer** [bokeh/bokeh#2937]
https://github.com/jupyter/spreadsheet 

I saw that @pzwang  recommended this instead of slickgrid on the bokeh google group. 

relevant: #2908

**Comment by bryevdv** [comment]
I think it would be great to have an example  that shows integration with phosphor datatable (i.e. a custom extension) but I don't think we would replace slickgrid because it supports more older browsers.
