### ISSUE TITLE
Integration with Polymer and Web Components elements?

### ISSUE THREAD

**Issue by datnamer** [bokeh/bokeh#2938]
Bokeh would be able to get lots of widgets for (almost) free if there was integration with the growing array of [Polymer](https://elements.polymer-project.org/) and [Web Components](http://webcomponents.org/) elements. 

Not sure if this can be done in a generic and technically feasible manner, but it would be cool. 

There is [proposal](https://github.com/jupyter-incubator/declarativewidgets) for Jupyter Widgets to do the same as mentioned in #805

**Comment by bryevdv** [comment]
This seems unlikely, until or unless someone with relevant knowledge and experience wants to come contribute. (I'm pretty much on learning curve overload already.)
