### ISSUE TITLE
Extend AjaxDataSource to support multiple y columns (feature request)

### ISSUE THREAD

**Issue by grahamrow** [bokeh/bokeh#2941]
Currently it seems that the (very useful) `AjaxDataSource` only support 'x', 'y' type plots. It would be wonderful to extend this in the manner of `ColumnDataSource` to support e.g. multi_line plots, for example:

```
source = AjaxDataSource(data_url=some_url)
plot = figure()
plot.multi_line(['x','x','x'], ['y1','y2','y3'], source=source)
```

Presently this can be hacked together by using separate `plot.line()` calls on the same plot, each with an independent data source, but this creates a lot of additional code and traffic. It would be convenient to jsonify all the data at once. Hopefully I'm not missing something!

**Comment by bryevdv** [comment]
That's not just a change to ajax data source, it's a fundamental change to how `multi_line` works. I would describe it as unlikely. However, since this issue, two avenues for accomplishing this sort of thing have opened up:

* Bokeh server applications
* Capability to create custom extension models
