### ISSUE TITLE
Feature request: Constrain zoom out to fixed range/domain

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2942]
On Twitter @nfaggian asked about being able to constrain the zoom tool to within a fixed range/domain on a plot. It sounds like a reasonable feature to me.

**Comment by tonyfast** [comment]
I was just looking at #1450 which asks for some similar improvements.

**Comment by tonyfast** [comment]
Are these constraints a feature on a the WheelZoomTool or on the axis?

**Comment by canavandl** [comment]
I'd imagine it'd be on the zoom tool where the python spelling would be like:

```python
from bokeh.models import WheelZoomTool
wheelzoom = WheelZoomTool(x_range=(0,100), y_range(0,100))
### or
wheelzoom = WheelZoomTool(x_min=0, x_max=100, y_min=0, y_max=100) 
```
Then on the BokehJS side, you just kill the zoom event if you're at the limit of the zoom range.

**Comment by nfaggian** [comment]
Folks! really glad to see this being discussed. Wonder if in the absence of constraints on the zoom the a fraction of the bounding box extent could be used to infer max/min zoom.

**Comment by tleeuwenburg** [comment]
+1 this would be pretty useful. Too easy to zoom/scroll away from the plot entirely, or zoom in crazy far. Thanks for thinking about it.

**Comment by canavandl** [comment]
A PR was recently merged to the BoxZoomTool where the zoom was killed if the zoom box was smaller than 5 pixels in height/width - assuming the user didn't intend the zoom and tried to "close" the box. I think it is a fairly opinionated feature, but feels very natural in terms of UX.

I'm becoming convinced that @nfaggian 's recommendation of adding zoom constraints based on the data ranges (perhaps a 1x data range buffer around the default range) would be a beneficial feature.
I can't immediately think of a use case where zooming way beyond the plot data is valuable to the user. 

To make this optional, we could add a zoom/pan_limit bool flag to the plotObject to make this optional.

It is kind of a big change. @birdsarah @bryevdv Do either you of have feedback on adding a scroll constraint in terms of UX and cases where it'd be a problem?

also ref issue #2427, #2565,

**Comment by tonyfast** [comment]
Would this proposal have any effect on the limits of the PanZoomTool?  If this does turn out to be a big change, is this the place to introduce aspect ratio on the zooming too?

**Comment by bryevdv** [comment]
I'm glad there is discussion on this we should implement some solution soon. Just so that it is on the radar: the complicating case is when there are multiple ranges.

**Comment by nfaggian** [comment]
@bryevdv Also really glad to see this being discussed! What about just using a factor of the maximum range in both x and y?

**Comment by birdsarah** [comment]
For me, if you're data is updating based on your ranges e.g. in a map or
in any kind of remote data source, then you definitely want to zoom
outside the current plot data.

Having said that having optional/configurable constraints would be super
helpful.

To my mind its particularly helpful when you are zooming out beyond plot
data that you can't see yet (because it needs to load from a server) as
it constrains that action appropriately when the user has no other
option for feedback.

**Comment by ACampbell22** [comment]
+1 on the ability to limit zoom. Accidentally zooming way out can be disorienting to the user.

**Comment by birdsarah** [comment]
I'm currently working on this.

**Comment by tleeuwenburg** [comment]
Thanks Sarah! :) That's great to hear. :)

On 22 November 2015 at 18:12, Sarah Bird <notifications@github.com> wrote:

> I'm currently working on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bokeh/bokeh/issues/2942#issuecomment-158734082>.
>



-- 
--------------------------------------------------
Tennessee Leeuwenburg
http://myownhat.blogspot.com/
"Don't believe everything you think"

**Comment by nfaggian** [comment]
This is excellent!
