### ISSUE TITLE
Slider doesn't work after WheelZoom on GMapPlot

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2943]
Can use the PanTool and the slider still works, but on using the WheelZoom, the slider stops working, the console isn't giving any hints.

http://nbviewer.ipython.org/github/mit-jp/cge-tools/blob/crem_presentation/crem_presentation/working/Maps.ipynb

**Comment by bryevdv** [comment]
@birdsarah the link is a 404 now

**Comment by bryevdv** [comment]
ping @birdsarah

**Comment by bryevdv** [comment]
ping @birdsarah

**Comment by birdsarah** [comment]
http://nbviewer.jupyter.org/github/mit-jp/cge-tools/blob/master/crem_presentation/working/Maps.ipynb

**Comment by birdsarah** [comment]
This is still an issue on this notebook, I should update to 0.11 and see if it's still a problem though.

**Comment by bryevdv** [comment]
@birdsarah any update?

**Comment by birdsarah** [comment]
I tried to quickly test this again, but I don't have the old example and it was proving time consuming to recreate - so no confirmation either way. It's fine to close and then we can always re-open if someone hits it.
