### ISSUE TITLE
Feature: add datetime support for BoxAnnotations

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2944]
The current BoxAnnotation only accepts NumberSpec values as inputs. This should be extended to accept datetime objs as well.

Future Span annotation should also have this support (#2899)

**Comment by johnnycakes79** [comment]
Thanks for opening the feature request @canavandl, for a StackExchange use case see: http://stackoverflow.com/questions/32946239/how-can-i-use-datetime-limits-on-x-axis-for-bokeh-boxannotation

**Comment by bryevdv** [comment]
This is the same issue as #5831 Although that issue is newer, I am closing this issue as the dupe since #5831 has a code sample and is already slated for `0.12.6`
