### ISSUE TITLE
plotting "large numbers" with webgl=True causes point coordinates to be miscalculated

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2945]
It appears that plotting "large numbers" (it seems to arise when values are >1e13), the coordinate of the rendered point is miscalculated. Using the WheelZoomTool on such a scatterplot will cause the points to stutter and jump around on the request_render event.

This is a non-trivial problem because it causes timeseries plots to be broken with webgl enabled, as the timeseries timestamps are over the threshold to induce this issue.

```python
from datetime import datetime as dt

from bokeh.plotting import figure, output_file, show

output_file('myplot.html')

xs = [1e15, 2e15, 2e15]
### or
xs = [dt(2014,1,1), dt(2014,1,2), dt(2014,1,3)]
ys = [1,2,3]

p = figure(webgl=True, x_axis_type='datetime')
p.scatter(x=xs, y=ys, size=15)

show(p)
```

<img width="580" alt="screen shot 2015-10-06 at 4 03 34 pm" src="https://cloud.githubusercontent.com/assets/2198981/10322569/f9775c96-6c43-11e5-85a5-a6075bd4e2be.png">

Python 3.4
Bokeh 0.10.0
Chrome 45.0.2454.101 (64-bit)

**Comment by canavandl** [comment]
After investigation w/ @bryevdv, this appears to be a floating point representation issue with Javascript

**Comment by almarklein** [comment]
In GL, all data is float32, does that explain things?

I don't understand the figure. It looks as if a large value on the x-axis causes the y-axis to go all weird, but is .... strange.

**Comment by almarklein** [comment]
There are tricks to pack float64 numbers into the rgba components and then unpack them. But that adds overhead and complexity.

    >>> np.spacing(np.float32(1e15))
    67108864.0

But still, the plot is not zoomed in, the origin is visible. So it's not the precision itself, I think ... mmm

**Comment by canavandl** [comment]
I'm sorry - I posted the wrong figure screenshot. I've updated the original issue to show that the y-values ( [1,2,3] ) are rendered correctly, and the x-values are incorrect.

**Comment by almarklein** [comment]
In the video you posted on FD I saw a wobbly effect, but I don't see that here, is that correct? The points are not in the correct place though. Maybe related to the data-to-screen coordinate transform?

**Comment by canavandl** [comment]
The wobble effect still happens on zoom events for the above.

Also, it appears if you make the x-values even larger (1e18) the wegbl enabled plot looks like:

<img width="586" alt="screen shot 2015-10-07 at 9 51 36 am" src="https://cloud.githubusercontent.com/assets/2198981/10341192/543135fe-6cd9-11e5-9a3d-e9d7aa363862.png">

**Comment by almarklein** [comment]
Yeah, I did get the effects when *not* using the datetime.

**Comment by almarklein** [comment]
Fiddled with the webgl precision classifiers (highp, mediump, lowp), but I don't see any difference.

**Comment by almarklein** [comment]
Ok, I've got it. PR on its way.
