### ISSUE TITLE
BokehJS 0.10 very verbose in the console using CDN

### ISSUE THREAD

**Issue by PythonicPrime** [bokeh/bokeh#2953]
Bokeh 0.10 is very verbose in the console using CDN resources. Setting BOKEH_LOG_LEVEL to any of the 5 permitted levels does not change this (the current level is 'info'). 

More details are included here: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/BmwmlM4VYx8

This is an excerpt of the console:

Bokeh: setting prefix to /
bokeh-0.10.0.min.js:16 Bokeh: load_models: start
bokeh-0.10.0.min.js:16 Bokeh: load_models: adding 78 new models to collections
bokeh-0.10.0.min.js:16 Bokeh: load_models: finished adding new models to collections
bokeh-0.10.0.min.js:16 Bokeh: load_models: starting deferred initializations of 78 new models
bokeh-0.10.0.min.js:16 Bokeh: Canvas initialized
bokeh-0.10.0.min.js:16 Bokeh: ToolManager: activating tool: PanTool (829741c7-96d5-47c1-83db-3b236057bea4) for event type 'pan'
bokeh-0.10.0.min.js:16 Bokeh: ToolManager: activating tool: WheelZoomTool (2bf0ec9f-b1ac-4a4e-886f-788ca5bd8395) for event type 'scroll'
bokeh-0.10.0.min.js:16 Bokeh: Plot initialized
bokeh-0.10.0.min.js:16 Bokeh: Canvas initialized
bokeh-0.10.0.min.js:16 Bokeh: ToolManager: activating tool: PanTool (0ba22578-467c-48e8-8a78-8dd0ca288506) for event type 'pan'
bokeh-0.10.0.min.js:16 Bokeh: ToolManager: activating tool: WheelZoomTool (f1ba1591-b6f1-4109-82dc-ba54cc08266d) for event type 'scroll'
bokeh-0.10.0.min.js:16 Bokeh: Plot initialized
bokeh-0.10.0.min.js:16 Bokeh: Canvas initialized
bokeh-0.10.0.min.js:16 Bokeh: ToolManager: activating tool: PanTool (f75883c0-1b28-47d1-8b54-a7b5f01e8d27) for event type 'pan'
bokeh-0.10.0.min.js:16 Bokeh: ToolManager: activating tool: WheelZoomTool (b5062956-bb65-45f7-b76d-ca6d219bf452) for event type 'scroll'
bokeh-0.10.0.min.js:16 Bokeh: Plot initialized
bokeh-0.10.0.min.js:16 Bokeh: Canvas initialized
bokeh-0.10.0.min.js:16 Bokeh: ToolManager: activating tool: PanTool (bea9beee-739e-4a3e-a031-0d43f531c3f2) for event type 'pan'
bokeh-0.10.0.min.js:16 Bokeh: ToolManager: activating tool: WheelZoomTool (d2599c47-aa6f-4244-b223-b33214c38cc3) for event type 'scroll'
bokeh-0.10.0.min.js:16 Bokeh: Plot initialized
bokeh-0.10.0.min.js:16 Bokeh: load_models: finished deferred initializations
bokeh-0.10.0.min.js:16 Bokeh: load_models: finish

**Comment by bryevdv** [comment]
It's possible explicitly setting a default to `info` unconditionally, then only overriding it if `bokehLogLevel` exists would solve this.

**Comment by PythonicPrime** [comment]
Thanks


Not sure I understand how to set the default to info (I set the env
variable to info, but it ignores it)

**Comment by bryevdv** [comment]
@PythonicPrime Sorry, I was making a note about a possible implementation of a solution in the next release. That said, you can try adding a JS snipped `Bokeh.set_log_level('info')` in your own HTML document (after BokehJS has loaded)

**Comment by PythonicPrime** [comment]
Got it , thanks!

**Comment by PythonicPrime** [comment]
This works, thanks

2015-10-12 15:09 GMT+01:00 Giuseppe Sette <gsp.sette@gmail.com>:

**Comment by bryevdv** [comment]
@birdsarah do you know if this ever got fixed?

**Comment by bryevdv** [comment]
I just tested this with `11dev3` from CDN and also with INLINE and found that explicit `BOKEH_LOG_LEVEL` was respected, and that the default log level was always set to `'info'`, so I am going to close. If I am mistaken and the issue can still be reproduced somehow, please re-open.

**Comment by birdsarah** [comment]
I haven't noticed it lately.
