### ISSUE TITLE
license requires notice on all notebooks?

### ISSUE THREAD

**Issue by scottdraves** [bokeh/bokeh#2957]
Hi Bryan & co, 

If you use bokeh in an ipython (or beaker) notebook, then the ipynb (bkr) file ends up containing bokeh.min.js (as well as fontawesome, jquery, and maybe more).  For redistribution, bokeh's license requires display of its copyright & disclaimer.  But this info is not generally displayed in notebooks.
They do display your logo though, and clicking it opens your web page.  This does not seem to satisfy
the terms though.

So my question is, are we (and everyone?) required to add the copyright and disclaimer? 

this question came from here: https://github.com/twosigma/beaker-notebook/issues/2651
because beaker has a bokeh demo in its tutorial, which is part of the application.

**Comment by bryevdv** [comment]
No. We will improve things to make it clear that normal usage is intended usage. See #2958

**Comment by scottdraves** [comment]
Thanks for the quick answer.

**Comment by bryevdv** [comment]
Resolved in #2958
