### ISSUE TITLE
Make license obligations easier and clearer to understand

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2958]
* [x] ~~~The wording of LICENSE.txt should be improved to make it unambiguous that normal, expected use does not constitute source redistribution.~~~

* [x] LICENSE.txt file should be included within the installed python lib of installed`conda` packages and `sdist` tarballs. 

* [ ] The text of the LICENSE.txt should be embedded directly into BokehJS. 

* [x] Suggest a `bokeh.license()` function to print the text of the license in the console. 

* [x] When moving from `grunt` to `gulp` the inclusion of license headers in minified BokehJS was lost. This must be restored and maintained under test (suggest grep for one of the known headers as sufficient)

**Comment by bryevdv** [comment]
Reference: https://github.com/twosigma/beaker-notebook/issues/2651

**Comment by bryevdv** [comment]
@pzwang any thoughts on the first bullet?

**Comment by mistakevin** [comment]
There is an [option to preserve the license](https://www.npmjs.com/package/gulp-uglify#options) in `gulp-uglify`

**Comment by bryevdv** [comment]
Seems to work.

**Comment by bryevdv** [comment]
@mistakevin any ideas about the third bullet? would be nice to automate from single `LICENSE.txt` source somehow.

**Comment by mistakevin** [comment]
Shouldn't be too hard, maybe just using [`gulp-concat`](https://www.npmjs.com/package/gulp-concat)

**Comment by bryevdv** [comment]
Well, `LICENSE.txt` is just plain text, it would also somehow need to be wrapped in a JS comment before using `gulp-concat`. Can you make a stab at this tomorrow?

**Comment by mistakevin** [comment]
yeah, I'll take a look

**Comment by bryevdv** [comment]
Thoughts on how to verify that the build minified BokehJS does contain the licenses in a test are also appreciated. It might need to be a python unit test? Not sure if there is a way to do it from the JS tests.

**Comment by bryevdv** [comment]
@mistakevin also thanks! Please just make any changes on the PR branch that is already open

**Comment by bryevdv** [comment]
Per discussion with @pzwang simply concating the standard BSD license text in BokehJS should be sufficient, not amendments are needed.

**Comment by mistakevin** [comment]
@bryevdv  So we want the text of https://github.com/bokeh/bokeh/blob/task/2958_license/LICENSE.txt inserted into bokeh.js and bokeh.min.js? And does it matter if it goes first or last? In case of source mapping issues arise.

**Comment by bryevdv** [comment]
@mistakevin yes inserted into both (as a comment) and I have no preference as to where.

**Comment by mistakevin** [comment]
@bryevdv Great. And I've managed to get all of the other licenses (well, all that match a certain pattern) into bokeh.min.js, as I noticed the `{ preserveComments: 'license' }` wasn't working, (see [issue here](https://github.com/terinjokes/gulp-uglify/issues/82)) Do we want those as well or just our license?

**Comment by mistakevin** [comment]
I now see the referenced issue above, we may want them all

**Comment by bryevdv** [comment]
Yes we do want them all.
