### ISSUE TITLE
GMap alignment still off in 0.10

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#2964]
Overlaying glyphs on a gmap plot is still causing trouble for me.  This is using rbokeh. Here's a simple example drawing Colorado's border over a map:

http://jsbin.com/gist/5a6c6682ca48a97c145b?html,output

Before, things resolved after zooming in a lot.  Now they are consistently off even when zooming in.  Does a projection transformation have to be made prior to sending the data to the spec?

**Comment by bryevdv** [comment]
That's not the intention, for sure. Ping @birdsarah

**Comment by andybak** [comment]
Does anyone know if there a workaround? Is it a constant offset or is a more complex transformation needed?

**Comment by bryevdv** [comment]
@hafen do you know the current status of this?

**Comment by bryevdv** [comment]
ping @hafen if you can, a test case would be very helpful

**Comment by aarora79** [comment]
I believe i am seeing a similar/same issue. Here is what i am doing:
- Have a world map with GMapPlot and some points marked on the map (i used circles for the points, identified by lat/long).
- Now i added a slider, similar to http://bokeh.pydata.org/en/latest/docs/gallery/slider.html .
- As i move the slider the javascript code in CustomJS gets triggered and it filters our some points and does a source.trigger('change'). The new set of points do get plotted but they are several pixels off..so the locations now move from say continental US to the Pacific Ocean.

So everything is working in the sense the points get included and excluded in the map exactly as i want just that the location gets messed up.

Any workarounds/solutions? I am using bokeh 0.12.3, python 3.5.2.

**Comment by aarora79** [comment]
@bryevdv @birdsarah any updates on this? I am making (i think) a really cool thing using GMapPlot and sliders and would love to see this working. Any updates/workarounds would be greatly appreciated.

**Comment by bryevdv** [comment]
No but I will add it to the `0.12.5` milestone to make sure to look at it sooner rather than later.

**Comment by bryevdv** [comment]
@hafen @aarora79 can either one of you provide a python script to reproduce the problem? I want to fix this for `0.12.5` but I need to be able to reproduce it.

**Comment by bryevdv** [comment]
I think this must have been fixed at some point. Using the following script:
```
from __future__ import print_function

from bokeh.util.browser import view
from bokeh.document import Document
from bokeh.embed import file_html
from bokeh.models.glyphs import Patch
from bokeh.models import (
     GMapPlot, Range1d, ColumnDataSource, GMapOptions, WheelZoomTool, PanTool
)
from bokeh.resources import INLINE

from bokeh.sampledata.us_states import data as states

API_KEY = "YOUR API KEY GOES HERE"

map_options = GMapOptions(lat=39.5501, lng=-105.7821, map_type="roadmap", zoom=6)

plot = GMapPlot(x_range=Range1d(), y_range=Range1d(), map_options=map_options, api_key=API_KEY)

source = ColumnDataSource(data=dict(x=states['CO']["lons"], y=states['CO']["lats"]))

patch = Patch(x="x", y="y", line_color="red", fill_color=None)
plot.add_glyph(source, patch)

doc = Document()
doc.add_root(plot)

plot.add_tools(WheelZoomTool(), PanTool())

filename = "maps.html"
with open(filename, "w") as f:
    f.write(file_html(doc, INLINE, "Google Maps Example"))
view(filename)
```
I get the following output zoomed out:

<img width="612" alt="screen shot 2017-02-23 at 12 28 58" src="https://cloud.githubusercontent.com/assets/1078448/23273196/ae6d1510-f9c3-11e6-8d5f-45ea5b4d55e5.png">

And zooming and panning around to a corner still looks good:

<img width="737" alt="screen shot 2017-02-23 at 12 28 51" src="https://cloud.githubusercontent.com/assets/1078448/23273202/b83767b2-f9c3-11e6-9028-33ed2e43360d.png">


If there is some reproducible problem that persists, please feel free to re-open this issue with code to reproduce and any other relevant info

**Comment by bryevdv** [comment]
I will add, with the above script and data if zoomed in far enough, I do see this:

<img width="286" alt="screen shot 2017-02-23 at 12 33 51" src="https://cloud.githubusercontent.com/assets/1078448/23273380/68d8fff4-f9c4-11e6-8041-28e7ead63c6c.png">

However the "states" data set is known to be vey coarse and at times wrong (the gulp coast of texas is a sraight line for example) so I chock this up to the data boundary data I have at hand not being great. Again, if anyone can reproduce a problem, please re-open, but a full example, including any necessary data (if you have a better source than "states" etc) *must be included*

**Comment by bryevdv** [comment]
For good measure, I modified the script to use counties data which is generally "higher resolution":

<img width="434" alt="screen shot 2017-02-23 at 12 47 19" src="https://cloud.githubusercontent.com/assets/1078448/23273860/4c4d0068-f9c6-11e6-9419-e48f34caf02c.png">

When zooming into the same corner things look better (again I propose because the boundary data is better):

<img width="464" alt="screen shot 2017-02-23 at 12 47 05" src="https://cloud.githubusercontent.com/assets/1078448/23273886/5cffe20e-f9c6-11e6-94c8-ab2f17b9adfb.png">
