### ISSUE TITLE
Add a color map which is based on fixed color points

### ISSUE THREAD

**Issue by justacec** [bokeh/bokeh#2968]
I think it would be great to add a new feature which would allow the user to create a color map which has flexible value tie points with specific colors.  Values which fall between the tie points would be linearly interpolated between those colors.  

The color mapper could be implemented by using the existing LinearColorMapper class as a base.  The class would have one required argument which would be the palette and would consist of a python dictionary using the keys to store the levels and the value to store the colors.  An optional alpha parameter could be specified to allow for transparency as well.

**Comment by justacec** [comment]
I have generated the necessary code for this and created a pull request (https://github.com/bokeh/bokeh/pull/2969) for review.

**Comment by bryevdv** [comment]
Somethingl like this would now be do-able as e.g a `CustomJSTransform` without even a custom extension. As we try to pare Bokeh down to a stable base for 1.0 i think thats a better place for specalied things like this.
