### ISSUE TITLE
Bar chart : would be amazing to be able to use DataFrame index as label

### ISSUE THREAD

**Issue by euri10** [bokeh/bokeh#2970]
following this little [discussion](http://github.com) I post here.
sometimes you want to plot a Bar graph from a DataFrame that contains a single column.
it would be amazing to be able to plot the values in that single column and have as a x-axis the index of the DataFrame.
```
import pandas as pd
from bokeh.charts import Bar
from bokeh.io import output_notebook, show

output_notebook()

dict = {'values': {u'A': 10, u'B': 20}}
df = pd.DataFrame(dict)
df['label'] = df.index

p = Bar(df, values='values',label='label')
show(p)
```

**Comment by bryevdv** [comment]
Thanks @euri10 !

@rothnic do you have any thoughts about spelling? I am inclined to think that if you omit `label`, then it tries to use the DataFrame index by default. So the example above would be spelled:
```
import pandas as pd
from bokeh.charts import Bar
from bokeh.io import output_notebook, show

output_notebook()

dict = {'values': {u'A': 10, u'B': 20}}
df = pd.DataFrame(dict)

p = Bar(df, values='values')
show(p)
```

**Comment by rothnic** [comment]
@bryevdv, @euri10  thanks, I'll take a look at it. To be clear, we just want it to be not be as verbose? The example provided in the first post works with the intended outcome right?

![image](https://cloud.githubusercontent.com/assets/452052/10412108/3cf0640e-6f41-11e5-92b8-eee435d61b92.png)

**Comment by euri10** [comment]
yes and yes ;)

**Comment by bryevdv** [comment]
Yes, specifically tho, a spelling to use the index of the dataframe without creating a new unnecessary column.

**Comment by bryevdv** [comment]
Yes, specifically tho, a spelling to use the index of the dataframe without creating a new unnecessary column. This line should never be necessary: 
```
df['label'] = df.index
```
just to use the index as a source for the plot.

**Comment by rothnic** [comment]
Closing this due to referenced commit that has been merged.
