### ISSUE TITLE
hoverTool snap_to_data point_policy and 'nearest' line_policy attribute doesn't work on circle or Scatter and line

### ISSUE THREAD

**Issue by aullrich2013** [bokeh/bokeh#2972]
I've been trying to use this in bokeh 0.10 and while the "previous" and "next" line_policy setting works, "nearest" does not, it interpolates.
Similarly, the snap_to_data point_policy doesn't select the center of a circle or scatter point

```
import numpy as np

from bokeh.plotting import figure, show, output_file, vplot
from bokeh.models import HoverTool
N = 100

x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)

output_file("legend.html", title="legend.py example")

myHover = HoverTool()
myHover.point_policy='snap_to_data'
TOOLS = ["pan,wheel_zoom,box_zoom,reset,save,box_select", myHover]

p1 = figure(title="Legend Example", tools=TOOLS)

p1.circle(x, y, legend="sin(x)", size=10)
p1.circle(x, 2*y, legend="2*sin(x)", color="orange", size=10)
p1.circle(x, 3*y, legend="3*sin(x)", color="green", size=10)


show(vplot(p1, p2))  # open a browser
```

**Comment by bryevdv** [comment]
I just tried this example (changing the last line to `show(p1)` there is no `p2`) and `snap_to_data` was behaving as expected, the hover tool was always centered on the center of the circle. `snap_to_data` only concerns the visual positioning of the hover tooltip, perhaps that was unclear? Or are you saying the tooltip is not visually centered on the circles? If so can you provide a screenshot, as well as more information about your browser and platform?

Regarding `nearest`, can you provide a minimal complete example that reproduces your issue?

**Comment by aullrich2013** [comment]
Ah, yes. I thought it would snap the x and y values to the center (actual) data values. I'd recommend that as a feature request if it's not on the backlog already. As to the Line, here's an example. I'm running os x 10.11 and Bokeh 0.10.

The graphic does behave as I'd expect. It was just the text values that I expected would also snap to the data position. Not that it's so useful now but here's a simple example where the graphic behaves as documented but the x/y values do not:

```
from bokeh.plotting import figure, output_file, show, output_notebook, ColumnDataSource
from bokeh.models import HoverTool, BoxSelectTool
output_notebook()
hover2 = HoverTool()
hover2.tooltips = [
    ("x,y", "($x, $y)")
]
hover2.point_policy='snap_to_data'
hover2.line_policy='nearest'#'prev'
hover2.always_active=False
TOOLS = ['box_zoom,box_select,resize,reset,crosshair',hover2]
p = figure(width=1024, height=500, tools=TOOLS)
p.line(range(20), range(20), line_width=5)
show(p)
```

**Comment by bryevdv** [comment]
So, the `$` template variables always refer to "mouse" or UI coordinates. If you have want *data* values from columns in the data source, use the `@` syntax:, 
```
hover2.tooltips = [
    ("x,y", "(@x, @y)")
]
```

**Comment by bryevdv** [comment]
More info: http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#hover-tool

**Comment by bryevdv** [comment]
I think the above info should resolve your question, if not please feel free to re-open.

**Comment by aullrich2013** [comment]
That resolves it. Thanks!
