### ISSUE TITLE
to_bokeh renders datetime ticks as integers

### ISSUE THREAD

**Issue by jfrydendall** [bokeh/bokeh#2973]
I am trying to port a pandas figure via the mpl.to_bokeh to a javascript opject for imbedding into my web-frame work. However, when I try to use the mpl.to_bokeh on a datetime axis the result is a integer valued tick axis.
As shown here:
![image](https://cloud.githubusercontent.com/assets/3465637/10418588/8d27a544-705f-11e5-8bba-ac30c21a45e3.png)
The example is straight from the github bokeh compat pandas example.
How can I get Bokeh to render the DateTimeAxis correctly via the to_bokeh?

 I am on Windows 8.1 64 bit Python 3.4 anaconda package with the Bokeh 0.10.0

**Comment by bryevdv** [comment]
Can you provide a complete, minimal example that reproduces this problem?

**Comment by jfrydendall** [comment]
Sure, the example from the compatibility page on Pandas shows the problem. The above figure is also derived from the code. 

import numpy as np
import pandas as pd

from bokeh import mpl
from bokeh.plotting import output_file, show

ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()

df = pd.DataFrame(np.random.randn(1000, 4), index=ts.index, columns=list('ABCD'))
df = df.cumsum()
df.plot(legend=False)

output_file("dataframe.html")

show(mpl.to_bokeh())

**Comment by jfrydendall** [comment]
I have been digging around in the code and the problem seems to stem from the matplotlib MPL and these functions calls:

In the function https://github.com/bokeh/bokeh/blob/master/bokeh/compat/mplexporter/utils.py - get_axis_properties 
There is a check for the axis scale: 
props['scale'] = axis.get_scale(), which will either return 'linear' or 'log' and is inherent from mpl. 

However, in the code https://github.com/bokeh/bokeh/blob/master/bokeh/compat/bokeh_renderer.py
make_axis(self, ax, location, props) there is a check against props['scale']:

if props['scale'] == "linear":
   laxis = LinearAxis(axis_label=ax.get_label_text())
elif props['scale'] == "date":
   laxis = DatetimeAxis(axis_label=ax.get_label_text())

However, the props['scale'] == 'date' can never be reached since MPL only provides either 'linear' or 'log' as mentioned above. Hence, the DateTimeAxis is never set and the plot will only display the bigint representation of the datetimes.

I have tried to monkey patch the xaxis scale by setting xaxis.set_scale('date') or axis.set_xscale('date') before the call to to_bokeh. However, the first option is deprecated since MPL 1.3 and latter option only allows 'log' or 'linear' keywords.

The only way around this problem that I found was to check for the type of the xaxis.major_formatter, if it is a pandas object than set props['scale'] = 'date'. 

if isinstance(formatter,TimeSeries_DateFormatter):
        props['scale'] = 'date'

However, this options depends on pandas to be available and does not check for datetime objects directly from MPL without pandas. 
However, for my needs this will fix the problem for now. I hope the you can provide a more robust solution.

**Comment by bryevdv** [comment]
@jfrydendall `mplexporter` is actually not part of Bokeh, it is an upstream library we rely on. You might consider submitting an issue on their issue tracker:

https://github.com/mpld3/mplexporter/issues

Comprehensive and robust support for MPL compatibility depends on MEP 25 (https://github.com/matplotlib/matplotlib/wiki/MEP25) but that is being developed by the MPL team and the schedule is not under our control.

**Comment by jfrydendall** [comment]
Thank you - I don't believe it is an mplexporer issue. The information about the axis format is provided by the mplexporter - it is located in the 'props' dictionary handed to the BokehRenderer Class method open_axes. The information is stored with the keywords 'xscale' or 'yscale' i.e props['xscale'] or props['yscale'].

However, open_axes only crawls through a subset of the props stored under 'axes'. So the information about the date formatter never reaches the make_axis method, hence, the figures never gets rendered with the date formatter axis.

**Comment by bryevdv** [comment]
@jfrydendall you seem to have developed a good understanding of the issue, do you think you can submit a Pull Request to fix the problem?

**Comment by jfrydendall** [comment]
Yes - I will take a shoot at it.

**Comment by bryevdv** [comment]
Awesome!
