### ISSUE TITLE
Web assembly

### ISSUE THREAD

**Issue by datnamer** [bokeh/bokeh#2974]
Not sure if this is relevant to bokeh (it is initially targeting c/c++) but here it is: https://github.com/WebAssembly/design 

They are eventually looking at supporting GC vm languages like python.

Even before than, maybe numba can work with emscripten (which will target web assembly) and/or typed JS arrays to compile numeric python code to work in the browser.

**Comment by mattpap** [comment]
This may be the future, but a really distant one. Closing for now. When there will be at least basic support in major browser then we can return to this.
