### ISSUE TITLE
stock_app errors and fixes

### ISSUE THREAD

**Issue by dcottle** [bokeh/bokeh#2977]
The new version of pandas may have broken the stock_app.
The error is traceable to the line 
header=False
in the function get_ticker_data.

Changing this line to
header=None
fixes the problem.

Also, unrelated to pandas, when a different ticker is selected from ticker1_select or ticker2_select, the graphs are updated, but the text from df.describe continues to describe the data for the initial 2 stocks.

I found that adding 
self.make_stats() 
to the function input_change after 
self.make_source()
fixed the problem.

**Comment by bryevdv** [comment]
I believe these issues were resolved with the `0.11` release. If there are still problems please feel free to re-open.
