### ISSUE TITLE
../tests/travis/nbexecuter.py tests not compatible w/ IPython=4.0

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2978]
running the ../tests/travis/nbexecutre.py test module raises the exception:

```bash
>>> from IPython.nbformat import read, NO_CONVERT, NotebookNode
ImportError: No module named 'nbformat'
```

when using IPython=4.0.0. It appears the nbformat module has been renamed or deprecated.

**Comment by damianavila** [comment]
nbformat is now an independent package and there were some changes, I had to revisit our machinery interacting with IPython/Jupyter, it is in my todo list. Assigning to myself...
