### ISSUE TITLE
Returned values in Bokeh

### ISSUE THREAD

**Issue by jskeesick** [bokeh/bokeh#2979]
Running bokeh  0.10.0-py34_0

Ok, I've got a couple issues here that I was told might be more than just user error. It seems that when I create a boxplot, the 1st, 3rd and median quartiles are rounding off to their nearest .5, but the min and max whiskers seem to be restricted to .25. Perhaps this is a somewhat simple setting / parameter I am missing...

However, the problem is further exacerbated by the fact that the min and max are displaying values both higher and lower than what the dataframe contain. The same data in Seaborn seems to display correctly, but in bokeh I'm getting odd values in both the min and max. 

Here is an example of what I'm currently seeing...

    w = BoxPlot(Evals, values='SCORE4', label='OFFERING', title="This is a title")

    show(w)

gives us...

![box](https://cloud.githubusercontent.com/assets/7778458/10441103/5b1aa4ac-7113-11e5-981f-febef085690d.png)

`In [67]:Evals[Evals.OFFERING==1].SCORE4.mean()`
`Out[67]:2.6666666666666665`

and...

    In [72]:Evals[Evals.OFFERING==1].loc[:,['OFFERING','SCORE4']]
    Out[72]:

ID | OFFERING | SCORE4
----|-----------|-------------
0 | 1 | 3
1 | 1 | 2
2 | 1 | 4
3 | 1 | 3
4 | 1 | 4
5 | 1 | 3
6 | 1 | 4
7 | 1 | 3
8 | 1 | 2
9 | 1 | 2
10 | 1 | 4
11 | 1 | 1
12 | 1 | 4
13 | 1 | 3
14 | 1 | 4
15 | 1 | 3
16 | 1 | 2
17 | 1 | 2
18 | 1 | 4
19 | 1 | 0
20 | 1 | 2
21 | 1 | 1
22 | 1 | 3
23 | 1 | 2
24 | 1 | 3
25 | 1 | 3
26 | 1 | 1

If further clarification is needed, I'll do my best to assist.

**Comment by bryevdv** [comment]
ping @rothnic

**Comment by pzwang** [comment]
Hey @jskeesick do you mind attaching the full code snippet that includes the sample data and whatnot?  Thanks!

**Comment by jskeesick** [comment]
I put together a simple example that gives me similar results. I hope this helps.

    import pandas as pd
    from bokeh.charts import BoxPlot
    from bokeh.io import output_notebook, show
    output_notebook()
    d = {'OFFERING' : [2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1],
         'SCORE' : [2,1,3,4,3,4,3,2,2,1,4,3,4,3,2,2,4,0,2,1,3,2,3,3,1,1]}

    data = pd.DataFrame(d)
    w = BoxPlot(data, values='SCORE', label='OFFERING', title="Title")

    show(w)

![box2](https://cloud.githubusercontent.com/assets/7778458/10468995/434dee5c-71d0-11e5-8e3e-778551caebe7.png)

    data[data.OFFERING==2].SCORE.mean()
    2.769230769230769

**Comment by bryevdv** [comment]
ping @canavandl please evaluate

**Comment by bryevdv** [comment]
ping @rothnic @fpliger this still appears to be an issue?

**Comment by fpliger** [comment]
yes.. this still happens and is definitely a bug. triaging...

**Comment by jskeesick** [comment]
I'm glad to hear it is repeatable, and that it's still being worked on. Up till now I didn't know if anyone else was able to see this error.

**Comment by fpliger** [comment]
:+1: thanks @jskeesick 

This is actually a regression introduced with the new charts design >= `0.10`

**Comment by fpliger** [comment]
@jskeesick I must step back, my apologies. I didn't consider your data shape well enough and must correct myself.

 In your case you have 2 columns with values and data is already grouped so you are telling boxplot to use one of the columns for values and the other for the labels (so it's doing so, which is not what'd expect). What you really want is to use the categorical columns ("SCORE", "OFFERING") for labels and their related values for the boxes computation.

So, back to your example, you should use the `blend` operator to tell `BoxPlot` to do so.. Here's how the code should look like:

```Python
import pandas as pd
from bokeh.charts import BoxPlot
from bokeh.charts import blend
from bokeh.io import output_notebook, show
output_notebook()
d = {'OFFERING' : [2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1],
     'SCORE' : [2,1,3,4,3,4,3,2,2,1,4,3,4,3,2,2,4,0,2,1,3,2,3,3,1,1]}

data = pd.DataFrame(d)
w = BoxPlot(data, values=blend('OFFERING', 'SCORE', name='values', labels_name='names'), label='names', title="Title")

show(w)
```

**Comment by fpliger** [comment]
@jskeesick I'm closing this as it's my understanding that it's a non-issue (well... a documentation issue that we are already addressing as part of improving charts documentation and examples). Please let me know if I'm missing something and should keep this open... 
Thanks!

**Comment by jskeesick** [comment]
Sorry for the very late return to this .... but I took a look at this, ran the code suggested. I'm certainly not afraid of admitting I might of implemented the package incorrectly, but the supplied code just throws an error.

```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-2-dc2f8f914236> in <module>()
      3 
      4 data = pd.DataFrame(d)
----> 5 w = BoxPlot(data, values=blend('OFFERING', 'SCORE', name='values', labels_name='names'), label='names', title="Title")
      6 
      7 show(w)

C:\Anaconda3\lib\site-packages\bokeh\charts\builder\boxplot_builder.py in BoxPlot(data, label, values, color, group, xscale, yscale, xgrid, ygrid, continuous_range, **kw)
     55     kw['y_range'] = y_range
     56 
---> 57     return create_and_build(BoxPlotBuilder, data, **kw)
     58 
     59 

C:\Anaconda3\lib\site-packages\bokeh\charts\_builder.py in create_and_build(builder_class, *data, **kws)
     57     # create the new builder
     58     builder_kws = {k: v for k, v in kws.items() if k in builder_props}
---> 59     builder = builder_class(*data, **builder_kws)
     60 
     61     # create a chart to return, since there isn't one already

C:\Anaconda3\lib\site-packages\bokeh\charts\_builder.py in __init__(self, *args, **kws)
    174 
    175             # handle input attrs and ensure attrs have access to data
--> 176             self._setup_attrs(data, kws)
    177 
    178         super(Builder, self).__init__(**kws)

C:\Anaconda3\lib\site-packages\bokeh\charts\_builder.py in _setup_attrs(self, data, kws)
    205             elif isinstance(attr, str) or isinstance(attr, list):
    206                 self.attributes[attr_name] = self.default_attributes[attr_name].clone()
--> 207                 self.attributes[attr_name].setup(data=source, columns=attr)
    208 
    209             else:

C:\Anaconda3\lib\site-packages\bokeh\charts\_attributes.py in setup(self, data, columns)
    107 
    108             if columns is not None:
--> 109                 self.set_columns(columns)
    110 
    111         if self.columns is not None and self.data is not None:

C:\Anaconda3\lib\site-packages\bokeh\charts\_attributes.py in set_columns(self, columns)
    100             # assume this is now the iterable at this point
    101             self.iterable = columns
--> 102             self._setup_default()
    103 
    104     def setup(self, data=None, columns=None):

C:\Anaconda3\lib\site-packages\bokeh\charts\_attributes.py in _setup_default(self)
     68 
     69     def _setup_default(self):
---> 70         self.default = next(self._setup_iterable())
     71 
     72     def _setup_iterable(self):

StopIteration: 

'''

**Comment by birdsarah** [comment]
are you on bokeh 0.11 which was released on jan 6th? there is also lots of new documentation with the release, maybe it covers your needs? try: http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#box-plots

**Comment by jskeesick** [comment]
I was not.. updating now and will take a look. 

Thanks,

**Comment by jskeesick** [comment]
Ok, I did update and got rid of the error (thank you), however, the proposed solution did not fix things. Instead of giving me two box plots, an offering 1 and offering 2 plot, with the appropriate plot, the plot produced had a box for score and one for offering. I went back to my example above and got the expected 2 plot chart of offering 1 and 2 but the numbers were still off. It should be noted that in both charts I had whiskers that were both below 0 and above 4 (beyond the numbers in either column). 

I created another chart with a larger data set (that I'm this side of positive was in the right configuration) and again saw numbers that were both above and below the provided data. I used the exact same data in a Seaborne plot and while ugly, displayed exactly as expected. (no 'value's above 4 or below 0)

```
	variable	value
4	Mar1	2
6	Mar1	4
10	Mar1	4
18	Mar2	1
24	Multi1	3
25	Multi1	3
26	Multi1	2
27	Multi1	0
28	Multi1	3
29	Multi1	3
30	Multi1	0
31	Multi1	4
32	Multi1	4
34	Multi1	4
35	Multi1	3
...
```

![image](https://cloud.githubusercontent.com/assets/7778458/12537828/4e9463be-c27e-11e5-92ef-2ca984d665f8.png)

**Comment by birdsarah** [comment]
I think you might be now stumbling into this issue: https://github.com/bokeh/bokeh/issues/3699

Feel free to add any experiences on that open issue.

**Comment by jskeesick** [comment]
I think this is still an issue, and not one related to the other one of equidistant whiskers.

I'm taking data that looks like this...

`
Item	  Question	Score	Section	  Event	Evaluator
34x	    Mar1	        4	        Maritime	  Boat	6
34x	    Mar2	        3	        Maritime	  Boat	6
34x	    Multi1	        3	        Multinet	  Boat	6
34x	    Multi2	        3	        Multinet	  Boat	6
34x	    Noise1	        4	        Noise	  Boat	6
`
and plotting a boxplot from that ... (here)

`e = BoxPlot(data=scores[scores['Item']=='34x'], values='Score', label='Question',title="Title")`

and getting the following...

![image](https://cloud.githubusercontent.com/assets/7778458/12738236/fec294ea-c92c-11e5-87c2-16cdea50ed03.png)

You can see on 'Ergo2' that the whiskers extend both below 0 and above 6. There are no scores in the db below 0 or above 4, so the other issue of symmetrical whiskers isn't the complete answer, though they could be connected as their doesn't seem to be any variance in the whisker length,  but they are also showing numbers that aren't true to the df either.

Hope this helps....
