### ISSUE TITLE
Iimproving ease of use of callbacks with bokeh.charts

### ISSUE THREAD

**Issue by bcipolli** [bokeh/bokeh#2982]
Was requested to create an issue, from the mailing list:

> > Can CustomJS be used with the charts interface in 0.10? What would I use for the source? Could I pass a dataframe to the callback ?
> 
> The short answer is "yes" but the longer answer is that it's probably not as convenient as it could be. In particular, passing the data frame will not work, you'd have to poke around and get the right data source and pass that in. Suggestions for simple and approachable spellings are welcome.
> 
> > Any example?
> 
> I'm afraid I don't have an example at hand. However, one way to find objects in side a collection of Bokeh models is to use the .select method to query the object graph. You can see more info here:
>        http://bokeh.pydata.org/en/latest/docs/reference/models/plots.html#bokeh.models.plots.Plot.select

**Comment by tonyfast** [comment]
Here's an example, but as stated it is not convenient.   

Bokeh.charts extracts only the necessary input data and metadata to build a chart.  After you create the bokeh object, you must find specific ways to access the Bokeh components you wish to apply callbacks to.

[This example creates a Scatter plot of the iris dataset](http://nbviewer.ipython.org/gist/tonyfast/82d2690007d25517be55/clickable-iris.ipynb).  In this example, I was able to retain the names of the iris species by creating a legend.  The legend made it possible to discover the DataSources I wanted to apply callbacks to.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/42)
