### ISSUE TITLE
Update sphinx version to fix documentation parsing issues for google style docstrings

### ISSUE THREAD

**Issue by rothnic** [bokeh/bokeh#2984]
Opened issue in sphinx, [this issue](https://bitbucket.org/birkenfeld/sphinx-contrib/issues/82/napoleon-return-type-containing-colons-is) appears to be fixed only for numpy style. Will need to make sure this is fixed when sphinx is updated. Meta.yaml has >1.3.1 so it should happen automatically.

Depends on sphinx-doc/sphinx/issues/2085

See screenshot below. Issue exists in the returns portion of the docstring:
![image](https://cloud.githubusercontent.com/assets/452052/10461526/59055784-719f-11e5-9dde-110d1a2a3b4e.png)

**Comment by bryevdv** [comment]
@rothnic Thanks I've found this annoying too.

**Comment by bryevdv** [comment]
According to the linked upstream issue this has been resolved.

**Comment by bryevdv** [comment]
Maybe now just broken in a different way
<img width="288" alt="screen shot 2015-12-16 at 10 42 43 pm" src="https://cloud.githubusercontent.com/assets/1078448/11861478/5c353a76-a446-11e5-9111-3299e2a9bc4f.png">

**Comment by rothnic** [comment]
@bryevdv, Looks to be fixed when using the napoleon extension directly, rather than relying on the built-in one.

![image](https://cloud.githubusercontent.com/assets/452052/12075092/07a2cfc2-b13a-11e5-87b9-c1217fdf7783.png)

To fix this, we just need to replace `'sphinx.ext.napoleon'` with `'sphinxcontrib.napoleon'` in conf.py, then add sphinxcontrib-napoleon as a dependency.

**Comment by bryevdv** [comment]
I didn't realize dev was going to continue separately,that's kind of silly. Can you put that in the docs PR?

**Comment by damianavila** [comment]
Reopening because we reverted 5f81424. We should put this on place after the release (we need to build the napoleon packages and dependencies).

**Comment by bryevdv** [comment]
This is currently working with newer versions of sphinx, etc.
