### ISSUE TITLE
TypeError: Bar() got multiple values for keyword argument 'values'

### ISSUE THREAD

**Issue by neerav1985** [bokeh/bokeh#2990]
Here is the code I ran and it gives `TypeError`:
    
    dd = df[['DATE','CLIENT','QUANTITY']]
    p = Bar(dd, label='CLIENT', values='QUANTITY', agg='sum',group='DATE',title="QUANTITY PER CLIENT AND DATE", legend='top_right')
    output_file("bar.html")
    show(p)

Here is the error:

```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-102-07be31a54f64> in <module>()
      2 dd['EXECUTED_QUANTITY'] = dd['EXECUTED_QUANTITY'].astype(float)
      3 
----> 4 p = Bar(dd, label='CLIENT', values='EXECUTED_QUANTITY', agg='sum', group='DATE',title="QUANTITY PER CLIENT AND DATE", legend='top_right')
      5 
      6 output_file("bar.html")

TypeError: Bar() got multiple values for keyword argument 'values'```

**Comment by fastinetserver** [comment]
I had an outdate version of bokeh:
pip freeze|grep bokeh
bokeh==0.9.0
And used to get the same error for the example below (copy pasted from this page http://bokeh.pydata.org/en/0.10.0/docs/quickstart.html)

    from bokeh.charts import Bar, output_file, show
    from bokeh.sampledata.autompg import autompg as df
    
    p = Bar(df, 'cyl', values='mpg', title="Total MPG by CYL")
    
    output_file("bar.html")
    
    show(p)

After running:
sudo pip install bokeh --upgrade
i have got bokeh==0.10.0, so everything works fine now.

**Comment by bryevdv** [comment]
Yes, there was change to `bokeh.charts` in 0.10 (which should be the last such). Glad it's working for you.

**Comment by bryevdv** [comment]
@neerav1985 please re-open if this is not the solution for you
