### ISSUE TITLE
Touch problems on all but the simplest cases

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2997]
Touch support was first introduced in 0.7.0, it worked for simple cases, but appears to have not worked for other cases even back then.

Since then, touch support has degraded further and even some simple cases don't work. I am working on a separate PR to get touch support back to the levels described here, but there's still more work to be done as the performance described here is not sufficient.

For reference see the following html and notebook (https://github.com/birdsarah/bokeh-miscellany/tree/master/touch)
* a standalone plot - https://rawgit.com/birdsarah/bokeh-miscellany/master/touch/scatter-070-single.html
* a set of vplots - https://rawgit.com/birdsarah/bokeh-miscellany/master/touch/scatter-070-vplot.html
* a set of hplots - https://rawgit.com/birdsarah/bokeh-miscellany/master/touch/scatter-070-hplot.html
* a notebook of plots - http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/touch/scatter-070.ipynb

You may have to load them locally to see the bounding box clearly. I have found the nbviewer link works best and highlights all the issues

Behavior observed (Note this is only for touch - mouse events are working just fine):

Single plot:

* at default page zoom:
 * pan tool - works as expected
 * box zoom and select - basically work as expected although there's a subtle offset
 * wheel zoom - works as expected - can be a little fidgety when the box tools are also on
* when page (not plot) is zoomed in:
 * pan tool - works as expected
 * box zoom and select - don't work properly - there's a large offset between where u select and where the box is
 * wheel zoom - sort of works, but it's clearly centered at an offset 

HBox & VBox

Generally, the first plot works, but the other plots - to the right or down the page - don't work - the bounding box is no-where near expected - similar to zoomed in on a single plot.

Specific observations:
* pan tool - on last VBox plot (4th in 4-plot VBox) pan is constrained in the y direction 
* pan tool - on last HBox plot (4th in 4-plot HBox) pan is constrained in the x direction
* pan tool - doesn't always behave as expected if the full plot isn't on the page
* box select & zoom - first plot behaves, others have a large offset
* wheel - just not quite right on everything but the first plot - a little hard to characterize

All of the above are made worse when zoomed into page.

Note: Although HBox and VBox are no longer in Bokeh, similar offset behavior has been observed with latest vplot and hplot

Notebooks: 
similar problems to above - offsets on bounding boxes, pan not working if plot not fully in view, etc.

**Comment by damianavila** [comment]
@birdsarah PR #4430 solve all the issues you raised here or there is some other ones to solve yet?

**Comment by birdsarah** [comment]
To the best of my knowledge, this was all solved.
