### ISSUE TITLE
How to order the stacked bar chart

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [bokeh/bokeh#2999]
I have a question on how can I change the order of the stacked bar chart.

An example is the Olympic medal bar chart in the tutorial of the chart interface.

How can I make the gold medal count at the bottom and bronze at the top?
![bar chart order](https://cloud.githubusercontent.com/assets/7532271/10540220/be6e021a-7438-11e5-8509-6c547ba2af1d.PNG)

**Comment by rothnic** [comment]
@Paul-Yuchao-Dong: by default the chart is doing the sorting. I've made some initial changes to allow turning off the sorting to produce the equivalent of this chart with the new version, but there is still more we could do.

**Comment by Paul-Yuchao-Dong** [comment]
@rothnic Many thanks! Or we could do some tweaking in pandas first ten feed it to Bokeh, but I am still not sure if the gold would be at the bottom for easier story telling.

**Comment by fpliger** [comment]
closing since this is fixed now.. it's possible to specify the `sort` argument to explicit attribute arguments
