### ISSUE TITLE
Hovers show up for lines that aren't being hit

### ISSUE THREAD

**Issue by jcrist** [bokeh/bokeh#3002]
Plot showing the issue is [here](https://rawgit.com/jcrist/0e3ae830bfff4fd0cb6b/raw/0b141c560f78b93a5ab31b445a0cf0645c130508/hover_overlap.html)

If you hover over the plot, sometimes multiple tooltips will show up, for lines that aren't being currently hovered over. 

This is on bokeh 0.10, shows up for bokeh 0.9 as well. Came up when working on profiling for dask, which is where this data came from. Code to create that plot:

```python
import bokeh.plotting as bp
from bokeh.models import HoverTool
bp.output_file('test.html')

data = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 4, 4, 4, 4, 5, 6, 7, 8, 8, 8, 9, 10, 0],
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 6, 6, 6, 6, 5, 4, 3, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, 3, 4, 3, 2, 1, 0, 1, 2, 1, 0, 0]]
time = [0.2505, 0.2510, 0.2511, 0.2581, 0.4891, 0.4936, 0.4945, 0.5020, 0.6182,
        0.6226, 1.5743, 1.6170, 1.6289, 1.6450, 1.6503, 1.6758, 1.6760, 1.6915,
        1.7010, 1.7172, 1.7319, 1.7481, 1.7671, 1.7855, 1.7983, 1.8124, 1.8308,
        1.8368, 1.8527, 1.8636, 1.8727, 1.8728]
labels = ['qr(vstack(tuple([getitem(...), getitem(...), getitem(...), ...])))',
          'many([_], [getitem(_, *)])',
          'qr(_apply_random(*, *, *, *, *))',
          'dot(getitem(_, *), getitem(getitem(...), *))']
colors = ['red', 'blue', 'green', 'purple']

p = bp.figure(x_range=[0, max(time)], plot_width=800, plot_height=300,
              tools="hover,save,reset,resize,xwheel_zoom,xpan")

for y, label, color in zip(data, labels, colors):
    source = bp.ColumnDataSource({'x': time, 'y': y, 'label': [label]*len(time)})
    p.line('x', 'y', line_color=color, line_width=3, source=source)

hover = p.select(HoverTool)
hover.tooltips = """
<div>
    <span style="font-size: 14px; font-weight: bold;">Task:</span>&nbsp;
    <span style="font-size: 10px; font-family: Monaco, monospace;">@label</span>
</div>
"""
bp.show(p)
```

**Comment by birdsarah** [comment]
ping @jcrist that rawgit link is 404ing for me - do you have a gist link?

**Comment by jcrist** [comment]
I'm getting that gist.github.com is down, so that might be it.

**Comment by gonike** [comment]
+1. This is really annoying; almost forced me to turn off the HoverTool. Not sure if this is related, but I sometimes find it really hard to get the HoverBox to display; it takes me several attempts approaching my cursor from all directions towards a data point to get it shown.

**Comment by bryevdv** [comment]
Have you all tried configuring the various hit-testing modes and interpolation policies that are available? For the gist above, it looks like it is using an "hline" to do hit-testing, i.e., any line that intersects a horizontal line through the current mouse position will result in a tooltip. Perhaps you want "mouse" mode, which only does hit testing immediately in a neighborhood of the mouse position. You can see the various different modes in action in this example:

https://github.com/bokeh/bokeh/blob/master/examples/charts/file/hover_span.py

@gonike It sounds like you actually have a different issue than the one described here? (display "too hard", rather that "too easy") can you provide more details, and especially actual code? There can definitely be difficulties, for instance, if you are hit testing circles, and you don't have a 1-1 aspect ratio. Mathematically, we have to choose one dimension to measure distance along, of your axes have wildy different scales, and the measurement is along the "small" one it can make the circles hard to hit. There are possible workarounds, but of course I am only purely speculating about what you might be experiencing. It is hard to offer anything concrete without a code sample.

**Comment by bryevdv** [comment]
@gonike I don't think I have any preference on the default. Perhaps you could submit a quick PR and then put the question to he mailing list to see if there are any strong opinions? A PR to add new examples to that section would be *extremely* welcome and appreciated.
