### ISSUE TITLE
Problems installing pytest-selenium

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3005]
@mattpap was recently left with a _dev version of pytest-selenium installed via conda, that didn't update to 1.0b1.

I can see it here: https://anaconda.org/bokeh/pytest-selenium/files?version=1.0b1dev50c8063

Maybe we should remove these from the channel?

ping @damianavila

**Comment by damianavila** [comment]
Yep, we should remove it to prevent further problems

**Comment by bryevdv** [comment]
@damianavila @birdsarah is this resolved?

**Comment by damianavila** [comment]
IIRC, I removed those some weeks ago... let's close this one.
