### ISSUE TITLE
Warn about version mismatches

### ISSUE THREAD

**Issue by ahmadia** [bokeh/bokeh#3008]
I found myself chasing ghosts in Bokeh this afternoon when I accidentally inlined the wrong JS version into our web application.  Perhaps Bokeh could try and detect when there are incompatible versions across the Python/JS interface?

**Comment by bryevdv** [comment]
I believe embedded JSON now includes a version, so this ought to be straightforward to check/warn about now.

**Comment by bryevdv** [comment]
A few helpful notes. 

The BokehJS version is available as `Bokeh.version` For reference is it built into `bokeh.js` here: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/main.coffee The version number itself is automatically updated by our build/release machinery. 

The version of python used to generate the JSON  is inserted here: https://github.com/bokeh/bokeh/blob/master/bokeh/document.py#L778-L785 

Right now, the versions should always be in sync. There might come a time when the project become more "independent" and we have to specify compatibility more explicitly, but for now it suffices to just warn loudly if thee version differ.

**Comment by bryevdv** [comment]
As for where to make the comparison, the `Document.from_json` method is probably a single point that could always work:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/document.coffee#L508

Right now it ignores the version passed in `json` but you would pull it out. I think you could compare it to `Bokeh.version` but accessing `Bokeh` like that may not be ideal. @mattpap is there a better way currently to get ahold of the version *inside* BokehJS code? (There is a sprint contributor interested in submitting a fix for this issue)

**Comment by bryevdv** [comment]
So if you made a `version.coffee` that was just:
```
version = '0.11.1`

module.exports = version
```
Then the version update script is just changed to update `version.coffee` instead of `main.coffee` and `main.coffee` it updated to something like:
```
Bokeh.version = require("version")
```

And then at the top of `document.coffee` the version should also be available as
```
version = require("version")
```

@mattpap comments welcome
