### ISSUE TITLE
Additional Features / Fixes for TileRenderer / TileSource

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3012]
- [x] Limit zoom level based on `min_zoom` and `max_zoom` properties
- [x] Expose global_alpha
- [x] Choose appropriate render `level` for TileRenderer.  Right now it uses glyph but this is problematic when renderering with other glyphs
- [ ] Add `GeographicTileSource` or `WGS84TileSource`
- [x] Take outline width into account when drawing tiles
- [ ] Add `VectorTileSource`
- [ ] Add example which includes circle, line, and patch glyphs
- [x] Replace `ProjectionUtils` class with `Proj4`
- [ ] Add plotting module support of simple use of tile renderer
- [ ] Fix `ResizeTool` to snap to correct aspect-ratio after resize
- [ ] Fix `DoubleTapTool` for fixed resolution zooming
- [ ] Add inverted axis support
- [ ] Add `attribution` property to display tile metadata (attempt to not violate terms of service for different tile providers)
- [ ] Add tile `wrapAround180`

**Comment by birdsarah** [comment]
"Choose appropriate render level for TileRenderer. Right now it uses glyph but this is problematic when renderering with other glyphs" I thought it was currently "underlay"

**Comment by birdsarah** [comment]
(re: labels - you can only have one `type` - see https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management#issue-types)

**Comment by brendancol** [comment]
So I thought that my glyph rendering issue was because of issues with 'level'.  It turned out it was bad logic for drawing newly created tiles.  This has been fixed now so I've marked that item as done.

**Comment by bryevdv** [comment]
Closing this as stale and too broad, please open individual issues for any specific things that could/should still be looked at.
