### ISSUE TITLE
Pandas sort deprecated in new charts, use sort_values instead

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#3014]
Getting this deprecation warning when using the new charts.

```
/anaconda/envs/training/lib/python3.4/site-packages/bokeh/charts/_attributes.py:78: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort(columns=columns)
```
Switch to using sort_values instead.

cc: @fpliger

**Comment by spawnrider** [comment]
Just had the same waning. See below :
```
d:\dev\python34\lib\site-packages\bokeh\charts\_attributes.py:78: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort(columns=columns)
```

**Comment by bryevdv** [comment]
There's not much we can do about this now, Pandas changed upstream, which is out of our control. If we move to `sort_values` then still-very-recent versions of Pandas will no longer work, which seems more undesirable than the warning.

**Comment by fpliger** [comment]
wait... this should be fixed! I made a change to use `sort_values` and use `sort` in case of the exception for older versions of pandas...

(didn't do this for examples though)

**Comment by bryevdv** [comment]
Maybe something slipped though? If there is a "compat" layer (I do seem to recall that now) then it would be great to use it on these cases.

**Comment by fpliger** [comment]
@bryevdv here's part of the fixes that I'm referring to: https://github.com/bokeh/bokeh/blob/master/bokeh/charts/attributes.py#L149-L152

I'm confused... the PR that is referring to this issue ( #3637 ) has nothing to do with with it. It's instead mostly docs and flakes fixes... Maybe it's because of a PR title (and intent) change?

**Comment by bryevdv** [comment]
#3637 originally update to `sort_values` directly but that change was reverted.

**Comment by fpliger** [comment]
Aaaah, now I see.. Yeap, this slipped. We can create a `compat` at bokeh level and put it there.. Otherwise, as it's a `charts` only thing we can just use `charts.utils`.
