### ISSUE TITLE
Axis location must be set on creation (documentation fix)

### ISSUE THREAD

**Issue by ahmadia** [bokeh/bokeh#3016]
If you'd like to create a figure with a non-default axis location (like a y axis on the right instead of the left), the location needs to be set when the axis is created.  

Situations where this works:
- When you create the figure
- When you create a second axis for the figure

If you try to modify `plot.yaxis.location` or `plot.xaxis.location` after the figure/axis has been created, this is "too late".  This needs to be somewhere in the documentation, maybe in a tips and tricks section or gallery for an axis on the right example?

**Comment by bryevdv** [comment]
Need example in user guide (plotting with high level glyphs) as well as explicit docstring content for refguide for `figure` (since it is an implicit kwarg parameter).

**Comment by bryevdv** [comment]
figure opts are auto-doc'd in refguide, and `location` prop no longer exists.
