### ISSUE TITLE
Stocks example bug with numpy v1.10.1

### ISSUE THREAD

**Issue by benjamin0** [bokeh/bokeh#3017]
The stocks.py example in /file, /notebook, & /server fails because numpy v1.10.1 doesn't recognize the dtype "M64".

```
File "examples/plotting/file/stocks.py", line 10, in <module>
    p1.line(np.array(AAPL['date'], 'M64'), AAPL['adj_close'], color='#A6CEE3', legend='AAPL')
TypeError: data type "M64" not understood
```

**Comment by PerryGrossman** [comment]
conda update anaconda indicates that 1.10.2 is the latest version:
(py35)perry@perry-Lemur-Ultra:~/Dropbox/Flask_tutorial$ conda update numpy
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /home/perry/anaconda3/envs/py35:
#
numpy                     1.10.2                   py35_0  
(py35)perry@perry-Lemur-Ultra:~/Dropbox/Flask_tutorial$ conda update anaconda
Using Anaconda Cloud api site https://api.anaconda.org

Also shown here:
(py35)perry@perry-Lemur-Ultra:~/Dropbox/Flask_tutorial$ python
Python 3.5.1 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.10.2'
>>> quit()

Do I need to pip install 1.11.0 until it included in the latest version of Anaconda?
If so, how?
I am not sure how to specify a version for updating. And I don't 1.11.0 here:
https://pypi.python.org/pypi?%3Aaction=search&term=numpy&submit=search

I am trying to do this:
http://bokeh.pydata.org/en/0.10.0/docs/gallery/stocks.html
as prep for this:
http://blog.thedataincubator.com/2015/09/painlessly-deploying-data-apps-with-bokeh-flask-and-heroku/

Perry

**Comment by bryevdv** [comment]
@PerryGrossman I apologize, but I am not following what you are trying to convey. Bokeh should be fairly indifferent to the numpy version, I'm not sure if you think you need a specific version, or if you are seeing a problem with a specific version, or...? It actually seems like you are more asking a question about conda / Anaconda than Bokeh, can you please elaborate?

**Comment by bryevdv** [comment]
@PerryGrossman I think I understand. You are looking at an old version of the example, before it was updated. Note the "0.10" in the link you gave:

http://bokeh.pydata.org/en/0.10.0/docs/gallery/stocks.html

That version is before the fix for this issue was applied. You need to use a more recent version of the example. You can always find the latest version by going to a link with "latest" in it, e.g.:

http://bokeh.pydata.org/en/latest/docs/gallery/stocks.html

**Comment by PerryGrossman** [comment]
Thanks, I was trying to update numpy; then I realized I should update
Bokeh. my bad.

works now, following
http://bokeh.pydata.org/en/0.11.0/docs/gallery/stocks.html
Perry

On Wed, Jan 27, 2016 at 10:23 AM, Bryan Van de Ven <notifications@github.com
> wrote:

> @PerryGrossman <https://github.com/PerryGrossman> I apologize, but I am
> not following what you are trying to convey. Bokeh should be fairly
> indifferent to the numpy version, I'm not sure if you think you need a
> specific version, or if you are seeing a problem with a specific version,
> or...? It actually seems like you are more asking a question about conda /
> Anaconda than Bokeh, can you please elaborate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bokeh/bokeh/issues/3017#issuecomment-175686824>.
>



-- 
PerryGrossman2008@gmail.com
 (617) 383-9061

**Comment by bryevdv** [comment]
Now worries, and if you need to use Bokeh `0.10`, the newer version of the example should work with Bokeh `0.10`, the main point is just that the example was updated to get rid of a deprecated NumPy type code, so you need to use the newest version of the example.
