### ISSUE TITLE
restore examples tests on travisci as default action

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3019]
In order to speed up TravisCI we disabled running examples tests by default (see #2934 ) because it was the big bottleneck and we don't really need to run those on every commit.

The drawback is that we don't run examples test at all now so the chances to have broken examples being merged on master is quite high ATM. That's actually what happened with #2986 

I propose to:

* restore examples tests running by default
* work on the examples cleanup to reduce time and verbosity
* have a [ci disable examples] magic to disable these tests (useful in the middle of a PR when you want a rapid iteration)

**Comment by damianavila** [comment]
>The drawback is that we don't run examples test at all 

This is not actually true... the merge commit is tested with example enabled, but this is a post-merge step, so maybe is too late...

>I propose to:

I am OK with the proposal, I can make that change if people agree on that... @bokeh/core

**Comment by damianavila** [comment]
I had +1 from @bryevdv and I guess some other team member are +1 as well, so I made a PR for this currently being tested.
