### ISSUE TITLE
Stricter docs build testing

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#3020]
Currently `make html` output is a mess, which hides new issues in the docs. Additionally, we either have to pay more attention to this kind of errors or make ci tests fail if `make html` failed.

**Comment by bryevdv** [comment]
@mattpap there are currently no Sphinx warnings or errors, and the four Charts related `RuntimeErrors` that pop up will be closed in an in-flight PR. OK to close?

**Comment by mattpap** [comment]
Still I would like to hear opinions if we should make sphinx errors fail a test run.

**Comment by bryevdv** [comment]
I would be fine with that.

**Comment by bryevdv** [comment]
Changing to `task`, @birdsarah [also agrees](https://github.com/bokeh/bokeh/pull/4239#issuecomment-215238918) that Sphinx warnings and errors should result in test failures.

**Comment by damianavila** [comment]
> Changing to task, @birdsarah also agrees that Sphinx warnings and errors should result in test failures.

:+1:

**Comment by bryevdv** [comment]
FYI I just made it so that  `bokeh-plot` directive failures error out of Sphinx immediately. I don't know whether e non-zero sphinx exit triggers build failure offhand tho

**Comment by bryevdv** [comment]
Actually the `bokeh-tree` directive will currently warn on non-tagged builds, because it needs a tag. Otherwise it just points at `master` and warns. We could make it not warn, in that case, I suppose.
