### ISSUE TITLE
Example apps error of "Cannot read property 'View' of undefined"

### ISSUE THREAD

**Issue by rothnic** [bokeh/bokeh#3021]
Running any of the apps under examples/app/* result in a `Cannot read property 'View' of undefined` in the JS console.

Issue exists on master as of this commit: https://github.com/bokeh/bokeh/commit/6dceae2325b45bbef2781799eb320748cfd41eab

The apps work with the current Bokeh v0.10 release.

These are being run with `bokeh-server --script /path/to/app.py`

**Comment by bryevdv** [comment]
Old server, closing as invalid
