### ISSUE TITLE
LogMapper can overwrite inputs, also falls over with one bad value

### ISSUE THREAD

**Issue by baderas** [bokeh/bokeh#3022]
Hi,

While using bokeh, I think I discovered a problem:
When drawing with quad(), you can pass multiple quads (lists of bottom, top, left, right values) to quad(), but when one top value is 0, all quads will be drawn with zero height.
If you pass the same values into seperate quad() calls, everything works.
It does not depend on what you set as y-range value (that was my first guess).

Code that produces test.html (showing the problem) and test2.html (how it should look like):
```
#!/usr/bin/python2
import bokeh.charts, bokeh.plotting
bokeh.plotting.output_file("test.html")
p = bokeh.plotting.figure(title="Test", y_axis_type="log", x_range=["a","b","c","d","e"], y_range=[0,1000], width=350, height=650)
bottom = [0, 0, 0, 0, 0]
top = [516.04, 2.426, 39, 0, 5.42803]
left = [0.5624999999999999, 1.5625, 2.5625, 3.5625, 4.5625]
right = [0.7625, 1.7625, 2.7625, 3.7625, 4.7625] 
p.quad(bottom=bottom, top=top, left=left, right=right, color="#ff0000", legend="Test")
bokeh.io.show(p)
p = bokeh.plotting.figure(title="Test2", y_axis_type="log", x_range=["a","b","c","d","e"], y_range=[0,1000], width=350, height=650)
bokeh.plotting.output_file("test2.html")
for i in range(0,len(top)):
    p.quad(bottom=bottom[i], top=top[i], left=left[i], right=right[i], color="#ff0000", legend="Test")
bokeh.io.show(p)
```

Tried it with Chromium and Firefox, no difference.
OS is Debian Jessie, Bokeh is version: 0.10.0

I append both output files as screenshots from Chromium:
![test](https://cloud.githubusercontent.com/assets/13378513/10710060/ae8fe1b0-7a46-11e5-9fe6-364334f2d47f.png)
![test2](https://cloud.githubusercontent.com/assets/13378513/10710061/ae93b2e0-7a46-11e5-8573-5b32363bce3f.png)

This could be somehow related to https://github.com/bokeh/bokeh/issues/1650

**Comment by bryevdv** [comment]
Hi @baderas, it's not #1650, you aren't re-using any plots twice. It didn't notice at first that you were using a log scale mapper. The plot renders correctly with a linear scale, so this appears to be a bug in the  log mapper.

**Comment by bryevdv** [comment]
For one thing, the mapper modifies the inputs under certain situations, which is certainly wrong:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/mapper/log_mapper.coffee#L56

But also seems to throw out all data, if any one element triggers a `nan` or `inf`:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/mapper/log_mapper.coffee#L66

**Comment by bryevdv** [comment]
I've adjusted the issue title accordingly.
