### ISSUE TITLE
Wrong variable names  in file_html() for Jinja2 template in documentation

### ISSUE THREAD

**Issue by baderas** [bokeh/bokeh#3023]
Hi,
in the documentation,  file_html(..) is somehow wrong: it says "variables to be used in the Jinja2 template. If used, the following variable names will be overwritten: title, js_resources, css_resources, plot_script, plot_div". See: http://bokeh.pydata.org/en/0.10.0/docs/reference/resources_embedding.html

I think *js_resources* must be *bokeh_css* and *css_resources* must be *bokeh_js*, according to https://github.com/bokeh/bokeh/blob/master/bokeh/embed.py. Otherwise it won't work for me.

The parameters js_resources=None, css_resources=None are not explained in detail, only named in the method's signature.

**Comment by birdsarah** [comment]
thanks for the report @baderas I've submitted a fix PR.
