### ISSUE TITLE
making (stacked) bar chart interactive?

### ISSUE THREAD

**Issue by stevenpollack** [bokeh/bokeh#3026]
I have a data set that tracks several countries' income statistics across multiple years and I'd like to visualize some of these statistics in a stacked bar chart with a year slider. 

I cannot seem to find a simple way to do this with `Bar` objects... Am I missing something?

**Comment by bryevdv** [comment]
high level `Bar` is suitable for quick EDA, notebook use, etc. For more interactive bar charts, recent `vbar` and `hbar` glyphs in `bokeh,plotting` probably better.
