### ISSUE TITLE
bug: stocks.app does not work with pandas .17 because read_csv doesn't accept Headers=False in .17

### ISSUE THREAD

**Issue by jeffneuen** [bokeh/bokeh#3031]
A quick change to Headers=0 and the example works fine.

**Comment by bryevdv** [comment]
ping @jreback what is the most-compatible-across-pandas-versions thing we should be doing?

**Comment by jreback** [comment]
header=None

**Comment by bryevdv** [comment]
Thanks! @jeffneuen would you be interested in submitting a PR to update this example (possibly others too)?

**Comment by jeffneuen** [comment]
Sure, would be happy to. I will look for other examples where the same issue applies, and then submit.

**Comment by fpliger** [comment]
this is done
