### ISSUE TITLE
BokehJS .get('').get('') not 

### ISSUE THREAD

**Issue by Golovior** [bokeh/bokeh#3032]
When i want to add the hover function to my graphs, this doesn't work.  
I filtered down into the error and found the row on which the error occurs.  
  
The error occurs on 39324 of version 0.10.0. This row contains  
`renderers = this.get('plot').get('renderers');`  
  
When looking into this, i found that this.get('plot').get() is not a function, but is undefined, which gives an error and so the catch block is being processed and the hovertool isn't added.

**Comment by bryevdv** [comment]
Hi @Golovior the hover tool works in may examples, so we will need more information (OS platform, browser) as well as a minimal, complete example set of code that reproduces the problem. For instance, I can't tell if you are starting from scratch from BokehJS, or using your own JS with python-created BokehJS code. There's not much that can be investigated based on this description.

**Comment by Golovior** [comment]
Hello Bryevdv,  
  
Sorry for the ambiguities.  
I have the website on CentOS 7 and using Google Chrome 46.0.2490.80.  
  
After checking for the version of Bokeh i've used, i saw that the version i downloaded isn't 0.10.0, but 0.8.0. I took this version from http://cdn.pydata.org/bokeh/release/bokeh-0.8.0.js, so maybe this is the source of the error. So i'm starting with BokehJS from scratch without any python-created BokehJS code.  
  
You mention examples. Are there any BokehJS examples, build on BokehJS itself? On http://bokeh.pydata.org/en/latest/docs/dev_guide/bokehjs.html there aren't much examples to work with.  
  
Thank you,  

Golovior

**Comment by bryevdv** [comment]
As an update, a recent PR added typescript port of `bokeh.plotting`: https://github.com/bokeh/bokeh/pull/4037

This work is new and ongoing, including adding documentation, which will be added soon in a separate PR (the code is needed in a project immediately, normally docs support would coincide)

**Comment by bryevdv** [comment]
issue #4134 for documenting JS APIs, continuing discussion there.
