### ISSUE TITLE
plotting/file/ajax_*.py examples are "interactive" (require server) 

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#3042]
Examples under `plotting/file` should simply generate an HTML file per example. `ajax_*.py` require a server as well (note the server is started automatically). This makes automatic processing of file (static) examples harder than necessary. There should be a separate category for "interactive" examples like `ajax_*.py`.

**Comment by bryevdv** [comment]
There is an interactive directory under examples, lets move the ajax examples there.

**Comment by bryevdv** [comment]
They've been moved.
