### ISSUE TITLE
Bokeh widgets not found

### ISSUE THREAD

**Issue by bcipolli** [bokeh/bokeh#3044]
I used `output_file` with `mode='cdn'`. When I try to load the plot, I get:
`GET http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.10.0.min.css 404 (Not Found)`
![image](https://cloud.githubusercontent.com/assets/4072455/10858985/5294c630-7f16-11e5-9e4f-e9138fa3041b.png)

Vesion info:
```
Python 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> bokeh.__version__
'0.10.0-61-g0876689-dirty'
```

**Comment by bryevdv** [comment]
We have not released dev build including the new split bokehjs yet. CDN will not work with source builds until then.

**Comment by bcipolli** [comment]
OK, would you consider erroring if a dev build requests `mode='cdn'`? Or warning that latest sources may not work, and outputting a URL that works?

Seems less than ideal for potential contributors that, in order to publish plots with `mode='cdn'`, I have to install vanilla `bokeh` and change my Python path to use it.

**Comment by bryevdv** [comment]
I think it does logger.warn actually, but of course Python does not configure a default logger unfortunately. Suggestions welcome.

**Comment by bcipolli** [comment]
Suggestions:
1. If you're in a dev build and use `mode='cdn'`, use the URL to the latest stable build, which should be computable from the version.
2. Use `warnings.warn` to detail that that's what you did, and that any features of the dev build will not be available.

Or, if that's not cool, then raise an exception (if that URL would never work) or warning (if there are scenarios where that URL would work in dev mode)

**Comment by bryevdv** [comment]
It's often the case that the "last release" of BokehJS will work, but every once in a while (like with the current very large server PR that is about to land) that is not the case. I thought maybe it did compute a "last usable" version already, but maybe not. @damianavila do you have any thoughts?

**Comment by damianavila** [comment]
>@damianavila do you have any thoughts?

Not sure...

>1. If you're in a dev build and use mode='cdn', use the URL to the latest stable build, which should be computable from the version.

I don't like that because it introduces a mismatch that can cover subtle bugs...

>2. Use warnings.warn to detail that that's what you did, and that any features of the dev build will not be available.

There is a message here: https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L88-L93, maybe we can use warning.warn here or use `info` in https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L90?

**Comment by bcipolli** [comment]
@damianavila It would be great if you can use `warning.warn` or some logging that shows by default (I guess `info` would do that?). Advanced bokeh devs who would set up logging would probably know this issue already; newer devs like me are the ones likely to hit the gotcha, and also not understand bokeh's logging usage/system.
