### ISSUE TITLE
Chart Request: Topological Data Analysis

### ISSUE THREAD

**Issue by datnamer** [bokeh/bokeh#3049]
Would be really cool and useful to have easy  TDA (for general data exploration) in python.

Intro: http://www.slideshare.net/paul_kyeong/topological-data-analysis-with-examples

More:
http://blog.revolutionanalytics.com/2014/01/topological-data-analysis-with-r.html
http://www.ayasdi.com/blog/bigdata/why-topological-data-analysis-works/

Code:
https://github.com/rosinality/knotter  (MIT and responsive dev)
http://danifold.net/mapper/legal.html  (GPL)
https://github.com/stephenhky/PyTDA

**Comment by bryevdv** [comment]
@datnamer this looks pretty interesting. I think on a technical level it boils down to network/graph support? We are in the middle of making some architectural changes that will make it easier to add new data store types that are fundamentally different from the tabular data store Bokeh currently uses exclusively. So for instance, a graph or GeoJSON data store. These are probably likely candidates for a `0.12` release.

**Comment by bryevdv** [comment]
I definitely think the nuts and bolts for this  falls under the network/graph work that is forthcoming. A request for a "high level" chart that abstracts this should go in https://github.com/bokeh/bkcharts
