### ISSUE TITLE
Toolbar Improvements: Active is programmable

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3054]
@brendancol just hit the example where he wanted to hide the toolbar (`toolbar_location=None`) but wanted zooming on.

We recently just turned zoomwheel (#3003) off by default, but the only way to turn it on is by clicking the toolbar icon.

We could add an argument to WheelZoomTool `active=True` for example, but it seems like we'd want something that worked across all tools and was consistent.

The challenge is that you should only have one tool active in a group at any one time. For WheelZoom this doesn't matter. It lives in the `scroll` group and there's only one tool in the `scroll` group, but for `pan` events in particular it's a problem.

I'm not entirely sure what a clean / obvious spelling is. We could have `active=True` on the invidivual models assuming that if you're using the Model interface you should know what you're doing and then have `figure` and `chart` have something like active_tools='list,of,tools' and it makes checks on it?

Worth noting that you can programmatically click the WheelZoomTool with if your toolbar is visible (but not if you've set `toolbar_location=None`)
````html
<script>
    Bokeh.$('.bk-button-bar-list[type="scroll"] button').click()
</script>
````

Update: if you have set `toolbar_location=None` you can reach into the guts of Bokeh to turn your WheelZoom on as follows:

````js
for (plot_index in Bokeh.index) {
 var plot_tools = Bokeh.index[plot_index].tools;
 for (tool_index in plot_tools) { 
   var tool = plot_tools[tool_index];
   if (tool.mget('tool_name') == 'Wheel Zoom') {
     tool.mset('active', true);
   }
 }
}
````

**Comment by dwf** [comment]
+1, it'd be really nice to be able to turn this on by default from Python.

**Comment by danaki** [comment]
I develop a Flask application and I need to click on wheel zoom every time I reload the chart. Please consider to make a setting in bokeh.charts.defaults. Would be great to configure the set of available tools by default too.

**Comment by esvhd** [comment]
+1 This would be very useful to do from Python from my side too. I was just searching for ways to do that.

**Comment by fingon** [comment]
+1 - while I just started looking hard at Bokeh, I instantly missed this (and found someone else did too; why wouldn't I want to use scrollwheel to interact with a canvas?).

I would like to select the 'selected tools' by default as well. I think probably clean way to do this would be to add second list to figure, e.g. select_tools=[] or equivalent with similar syntax as tools=, except it would select those by default.

**Comment by datascientette** [comment]
+1 I would also like the wheel zoom to be on by default

**Comment by daliagachc** [comment]
yep, this feature is really needed as otherwise it is not intuitive to first-time users

**Comment by b-trav** [comment]
+1 for turning on/off tools in python. Having panning on by default is painful on touchscreens.

**Comment by bryevdv** [comment]
Suggestions for how to spell this? The complication is that at most one of each gesture type can be active at at time. So the interface either needs to prevent e.g. two drag gesture tools from ever being activated simultaneously in the first place, or have some comprehendible and non-surprising way of remediating that situation.

**Comment by mrocklin** [comment]
Presumably bokeh has some runtime way to control having two on simultaneously (turn others off when any gets flipped on) so presumably this is only a problem during figure creation?  Could you raise an informative error if someone constructs a figure with multiple conflicting active tools?

**Comment by bryevdv** [comment]
Yes but that information is not inherent the tool itself. There is a tool manager that keeps track of active tools per gesture, and the active tool is simply the one that the manager is configured to pass those UI events on to. 

Putting this information on the tool as a simple `on` / `off` makes it very difficult to pick a default tool to activate, in the absence of any other input. It's not enough to just make one tool "on" by default from the python side, what tool gets turned on if that one tool is not added at all? Currently BokehJS refers to an internal priority to pick the best default tool to activate for whatever arbitrary collection of tools happens to be present. If the tool gets an `on`/`off` then the only reasonable default is "all off" which either really means 'pick one automatically' which is confusing, or truly means "all start off" which is undesirable.

**Comment by bryevdv** [comment]
So, proposal:
```
plot.active_drag = "auto"  # current behavior
plot.active_drag = None    # no active drag tool
plot.active_drag = "pan"   # activate a PanTool (if there is one, warn otherwise)
plot.active_drag = a_tool  # activate a specific tool instance 
```

**Comment by mrocklin** [comment]
Perhaps have a mirrored keyword argument on `figure`?

```python
figure(..., tools='hover,xwheel_zoom,box_zoom', on_tools='hover,xwheel_zoom')
```

As someone unfamiliar with Bokeh this introduces less cognitive load.  I think I'm also more likely to find this than a property on the figure.

**Comment by bryevdv** [comment]
Something like that could be a convenience API on top, but the actual mechanism would need to ultimately be expressed as Model properties, because that is what ultimately gets serialized.

**Comment by bryevdv** [comment]
Also, FYI any model properties can generally be set by passing them as kwargs. So,
```
figure(..., tools='pan,box_zoom', active_drag='pan')
figure(..., tools='pan,box_zoom', active_drag=None)
```
?

**Comment by bryevdv** [comment]
More fully fleshed out proposal:
```
    active_drag = Either(Auto, Instance(DragTool))
    active_scroll = Either(Auto, Instance(ScrollTool))
    active_tap = Either(Auto, Instance(TapTool))
```
So at the low level what is sent to BokehJS is one of: `"auto"` (current behavior), `None` (no active tool for that gesture), or an explicit tool instance.

Additionally, as a convenience on `Figure` (and perhaps `Chart`), one of the string tool names, e.g. `"pan"`, `"box_zoom"` can be passed into the initializer, which will convert the string argument to a specific `Tool` instance to actually set as the property value.

**Comment by bryevdv** [comment]
@dwf @esvhd @fingon @datascientette @daliagachc @b-trav Any chance one of you would be interested in working up a PR for this proposal (or one like it assuming, there is agreement) with some help? Everyone on the core team is pretty slammed with work for the time being.

**Comment by pzwang** [comment]
I think that ensuring that only one active gesture is turned on at a time is a laudable goal, that requires a bunch more API work, as this discussion shows.  Even with the `active_*` thing, you'd then have to ensure that that tool actually exists, or... do you create one by default?

In any case, I think 99% of people's needs could be met by *just* exposing the `active` model attribute on various tools in Python, without touching the JS.  Why not just do that for now, and solve the other problem down the road if/when people want an automated mechanism for ensuring there aren't two tools set to active?

**Comment by abelategui** [comment]
+1 for the option to activate WheelZoomTool  through Python

**Comment by nrasiwas** [comment]
+1 for the option to activate WheelZoomTool through Python

**Comment by pzwang** [comment]
I think that this is a really important thing to get into this release, even if it means delaying the release a little bit.

**Comment by bryevdv** [comment]
@dwf @esvhd @fingon @datascientette @daliagachc @b-trav  please take a look at the new PR

**Comment by b-trav** [comment]
Hi @bryevdv, I'd love to take a look, unfortunately I'm having some issues installing bokeh from github. I've not used the developer version of bokeh before, so am following [these instruction](http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup). I am using Ubuntu 14.04.4. I follow as far as cd'ing into `bokehjs`, however when I run `npm install`, I get the following:
`
npm ERR! not a package /home/btrav/tmp/npm-12834-0DIVdNSF/1466144537576-0.13068444072268903/tmp.tgz
npm ERR! Error: ENOENT, open '/home/btrav/tmp/npm-12834-0DIVdNSF/1466144537576-0.13068444072268903/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-88-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/btrav/Documents/bokeh/bokehjs
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/btrav/tmp/npm-12834-0DIVdNSF/1466144537576-0.13068444072268903/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
`

**Comment by bryevdv** [comment]
@b-trav I'm not sure that seems like an `npm` issue which is beyond my (very) basic Node expertise. Really I was just asking for comment on the spelling in the example code I included
