### ISSUE TITLE
Manually set color shading levels in adjacency matrix?

### ISSUE THREAD

**Issue by levithatcher** [bokeh/bokeh#3056]
In the Les Mis adjacency matrix example, shading is handled by alpha values from 0 to 1, see below. But what if one wanted all the shades to span from alpha values of 0.8 to 1.0 instead of (the default) being evenly distributed from 0 to 1? In other words, how can one manually set the alphas' shade levels?

Thanks!

http://bokeh.pydata.org/en/latest/docs/gallery/les_mis.html
```
source = ColumnDataSource(
    data=dict(
        xname=xname,
        yname=yname,
        colors=color,
        alphas=alpha,
        count=counts.flatten(),
))
```

**Comment by levithatcher** [comment]
Thanks for this fantastic library!

**Comment by bryevdv** [comment]
The alpha values are already being manually set. In `alpha` is just a list of alpha values, one for each cell in the matrix. If you want different alpha values, fill the array with whatever alpha values you'd prefer.

**Comment by bryevdv** [comment]
In particular the alpha values are computed here:
```
a = min(counts[i,j]/4.0, 0.9) + 0.1
alpha.append(a)
```
But that's just a scaling I made up because it looked reasonable, you can replace it with whatever different alpha scaling suits your use case.

**Comment by levithatcher** [comment]
Thanks for the quick response! Sorry for not being more clear--I see that the values for alpha are being manually set, but the color shades appear to break at fixed values of alpha (ie, at .2, .4, .6, .8, etc). How can I set the tell the shades to switch at (say) .5, .75, etc? Thanks!

**Comment by levithatcher** [comment]
Sorry to bother, but does anyone have an idea of how to make these color transitions not happen _only_ uniformly from 0 to 1?

**Comment by bryevdv** [comment]
Work to support this kind of more sophisticated color mapping is underway, starting with https://github.com/bokeh/bokeh/pull/3959 to add computed transforms. These will be used to provide additional ways to map colors on the client side. Closing this discussion in favors of the open PR and its associated issues.
