### ISSUE TITLE
Dynamic plot dimensions

### ISSUE THREAD

**Issue by jgoad** [bokeh/bokeh#3060]
I just saw this issue on google, but I didn't see it here so I figured I would bring it up. It would be great if I could tie up the plot dims to the containing div when I embed the figure. I'm using bootstrap but my bokeh figs don't resize with page zoom like all the other elements. 

It seems like a js hack is probably pretty easy, but my JS chops are slim to none and it seems like you all would probably want this to be built in. It seems like the idea of Bokeh is to avoid writing as much JS as possible for your figs.

Thanks.

**Comment by bryevdv** [comment]
Initial support for responsive plots was added in https://github.com/bokeh/bokeh/pull/2881 (which landed in release `0.10`) with more to come.  Please see: http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#responsive-dimensions
