### ISSUE TITLE
Setting responsive for figures in tabs results in buggy tabs

### ISSUE THREAD

**Issue by jgoad** [bokeh/bokeh#3061]
When you set figure.responsive=True for a figure that gets passed to Panel, which gets passed Tabs, results in buggy figures when clicking from tab to tab. It could be that Tabs or Panels leverages HBox, which would make this a known issue, but I'm reporting it as the docs asked.

**Comment by birdsarah** [comment]
thanks for the report @jgoad, a minimal code example really helps.

also could you say something more specific than "buggy figures" - what's not working for you?

Tabs/Panels doesn't use HBox to my knowledge so I would have expected it to work.

**Comment by jgoad** [comment]
Absolutely understand. I was rushing out of the office and really punted on
this one. I'm really just laying out some rect glyphs on a figure, setting
responsive to true, and then attempting to embed them in tabs. Without
responsive=True the tabs work as expect. With it, the first tab renders,
but all other tabs look to be very zoomed out.

**Comment by tonyfast** [comment]
[Here is an example of this issue](http://nbviewer.ipython.org/gist/tonyfast/9fc6f6930825bafb50a3).  It appears that responsive takes on the size of the DOM element when it is created and it doesn't update with the DOM element.

I think to start it would be good to consider upper and lower bounds for the responsive sizes.

**Comment by birdsarah** [comment]
@tonyfast thanks so much for the notebook. 

this is sad - sorry about that @jgoad.

I'll try and take a look soon.

**Comment by jgoad** [comment]
@birdsarah no worries. I really love bokeh. I don't think a ton of people set responsive so it makes sense you haven't run into this bug before. Also, it's free! :)

**Comment by birdsarah** [comment]
Layout has been completely overhauled, but tabs currently only support fixed layout. I have opened an issue for this #4404.
