### ISSUE TITLE
Bokeh live editor

### ISSUE THREAD

**Issue by spencerlyon2** [bokeh/bokeh#3062]
I'm working on beefing up the Julia bindings and am missing something like the [Vega Live editor](http://vega.github.io/vega-editor/index.html?spec=treemap). 

Could we create something similar for Bokeh? Something very similar to the vega editor would be great: json on left with the rendered bokeh visualization on the right.

**Comment by bryevdv** [comment]
The new server that was just merged (that is going into the next `0.11` release would actually support something like this very easily I think. It's probably possible to make a standalone page that does this too, but that would require a user to generate the JSON by hand, and that's probably a pain (Bokeh JSON spec is a bit more verbose, and to allow "sharing" objects has things like "object references")

Another option down the road that could work better for a standalone page would be a Vega(lite) bridge, something that can convert Vega into BokehJS JSON.

ping @pzwang in case you'd like to chime in

**Comment by datnamer** [comment]
Would the server work cross language ie with julia or r?

**Comment by bryevdv** [comment]
The new server should be alot easier to integrate with other languages. It has a notion of "spellings" which are really just different ways of creating a bokeh document in the server. An easy one to start would be a "JSON Spelling" which can simply consume some JSON that Julia or R emit, and build the document up from that. Later we might imagine actually having the ability to run an R script to generate the document directly in the server.

**Comment by bryevdv** [comment]
The "live editor" will be the bokeh server `--develop` mode, which is covered by another issue.
