### ISSUE TITLE
Document need to install futures on py27

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3068]
futures (`conda install futures` or `pip install futures`) is needed by the new bokeh server, but isn't caught by `devdeps.py` and also not listed under the install dependencies in the docs (http://bokeh.pydata.org/en/latest/docs/installation.html#install-dependencies)

Not sure where else people might look for the reference.

**Comment by bryevdv** [comment]
`futures` is a runtime dependency on py27, it should be reflected in the real runtime requirements, devdeps is to check additional things people should have installed for doing development.
