### ISSUE TITLE
curdoc, vplot, hplot role with new Document API 

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3074]
`curdoc`:

it has currently been moved from `plotting` to `io`. Conceptually it used to be a mid-level API structure only used for `plotting`. The move to `io` makes curplot available to other APIs (either low level `glyphs` and `charts`). IMO it's a good thing to have as it's probably useful vertically across different APIs levels. If it's the case we should probably make it more explicit and show it off also on `glyphs` and `charts`.

`vplot` and `hplot`:
The background for this issue came up when fixing `glyphs` examples that were broken. The reason they were broken was because if  you use`vplot` and `hplot` they auto create a "default" document object (`curdoc()` like `figure`). The problem is that glyphs usually create a new Document (or at least use to) and add your layout to the document with `doc.add` and it clashes with the `curdoc()` that is being created by `vplot` and `hplot`.

This is definitely a situation that we want to avoid. As `vplot` and `hplot` are just convenience around `VBox`, `HBox` and `curplot()`.

 So, the proposal is to:

* understand if we agree to promote `curdoc()` as global standard doc across all interfaces (if not we need to be sure that we don't have other *magic* overlapping with lower interfaces)
* remove `vplot` and `hplot` in favor of `VBox`,  `HBox` or some more straightforward replacement.

**Comment by birdsarah** [comment]
Fixed in #4392. There is no more creating of documents or auto-adding to them.
