### ISSUE TITLE
Move annotations section of User Guide into it's own page

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3078]
Annotations are useful whatever API level you're using, I think they should have their own page instead of being under plotting: http://bokeh.pydata.org/en/dev/docs/user_guide/plotting.html#adding-annotations

**Comment by birdsarah** [comment]
ping @canavandl @bryevdv - what do you think?

**Comment by canavandl** [comment]
I agree that it's reasonable.

**Comment by bryevdv** [comment]
Seems good, just need a stylistically consistent name, maybe *Annotating Important Things*
