### ISSUE TITLE
Remove logo_url from resources

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3083]

**Comment by bryevdv** [comment]
Leftover cruft from the first implementation. Now the image is base64 encoded as a CSS image. Perhaps this could be hooked up to override that, though.

**Comment by bs1234** [comment]
I'd really keen to override the bokeh image with another (user-specified) one.

However, I'm unlikely to be able to do this anytime soon - still have much to learn about git (and Python in general for that matter)

**Comment by bryevdv** [comment]
There is another issue to make the logo configurable. For now, since this cruft is not relevant, just remove it with this issue.
