### ISSUE TITLE
update docs to point to tagged release of bokeh examples

### ISSUE THREAD

**Issue by woodscn** [bokeh/bokeh#3084]
```
$ python
Python 3.4.3 |Anaconda 2.3.0 (x86_64)| 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> import bokeh.client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'bokeh.client'
>>> bokeh.__version__
'0.10.0'
>>> 
```

**Comment by birdsarah** [comment]
Can you explain more what you were looking for / trying to do. Currently, this issue is just a statement of fact.

**Comment by woodscn** [comment]
I was trying to run one of the examples. 
bokeh/examples/plotting/animated.ipynb

This was a clean ```conda install bokeh``` install.

**Comment by birdsarah** [comment]
not sure what's happening for you. but bokeh/examples/plotting/notebook/animated.ipynb is working for me.

<img width="745" alt="screen shot 2015-11-06 at 2 49 59 pm" src="https://cloud.githubusercontent.com/assets/1796208/11010704/c1215ecc-8495-11e5-8917-585b9e0b3402.png">

please provide further information. are you also running bokeh-server from the same 0.10.0 environment?

**Comment by woodscn** [comment]
I couldn't tell you; I just fired up the examples, and didn't get past step one for this one.

Where do you initialize bokeh-server from a conda install?

**Comment by birdsarah** [comment]
you should be able to run `bokeh-server` from the command line - if this instruction is missing from your notebook we should investigate further.

**Comment by caseyjlaw** [comment]
+1 on this one. 
I've been struggling on a few examples from this repo due to what I assumed were API changes related to v0.11. From the discussion here, bokeh.client is not in that category.

**Comment by birdsarah** [comment]
Please provide more information @caseyjlaw we can't fix "struggling on a few examples"

**Comment by woodscn** [comment]
This specific example fails, as I mentioned before. The exact error is reproducible using the code snippet I provided. 

https://github.com/bokeh/bokeh/blob/master/examples/plotting/notebook/animated.ipynb

I expected to be able to install bokeh using conda, open this example in a Jupyter notebook, and run it. I could not.

**Comment by birdsarah** [comment]
Alright, now we're on to something. 

You stated that your bokeh version is 0.10.0

So you need: https://github.com/bokeh/bokeh/blob/0.10.0/examples/plotting/notebook/animated.ipynb

(note that this is the `0.10.0` version not the `master` version)

To save you having to download these things from github. If you find your conda envrionment on your machine (which you'll be able to see the location of by typing `conda info` if you don't know it) there'll be a directory Examples which will have installed the examples that are appropriate for your installed version of Bokeh.

**Comment by woodscn** [comment]
That makes sense to me. Unfortunately, I didn't find the examples directory there when I went looking, which is why I grabbed it from github. I'll check again when I get back to my computer, in case I missed it.

**Comment by bryevdv** [comment]
The examples in master are newer than bokeh 0.10. They are too new, to be precise. We just merged a huge update to bokeh server to master. This is your problem. You need to run examples that come with bokeh 0.10 or under your bokeh to a dev release.

**Comment by caseyjlaw** [comment]
Oops, sorry. Although the documentation does suggest looking at examples in the master branch (e.g., at http://bokeh.pydata.org/en/latest/docs/gallery.html#gallery). 
This issue is labeled as a code one, but it is actually a doc issue.

**Comment by bryevdv** [comment]
Sure, maybe that link can be automated to point to the specific tag for the release.

**Comment by woodscn** [comment]
I'm not sure that examples are even included in the conda install for v 0.10. I did find the Examples directory in 0.9, but it's not there in 0.10.

**Comment by birdsarah** [comment]
I've just tested this out and I'm seeing a problem on python3.5 (I'm not sure if bokeh officially supports 3.5 yet - we don't test against it yet)

here's the difference:
## py 3.4
````sh
➜  ~  conda create -n bokeh-test-4 bokeh python=3.4
Fetching package metadata: ..........
Solving package specifications: .
Package plan for installation in environment /Users/caged/miniconda3/envs/bokeh-test-4:

The following NEW packages will be INSTALLED:

    bokeh:           0.10.0-nppy34_1
    [ some packages omitted for brevity ]
    pandas:          0.17.0-np110py34_0
    pip:             7.1.2-py34_0
    python:          3.4.3-2
    python-dateutil: 2.4.2-py34_0
    [ some packages omitted for brevity ]

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|######################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate bokeh-test-4
#
# To deactivate this environment, use:
# $ source deactivate
#
➜  ~  ls /Users/caged/miniconda3/envs/bokeh-test-4
Examples   bin        conda-meta include    lib        share      ssl
````
note Examples are available

## py 3.5
````sh
➜  ~  conda create -n bokeh-test-5 bokeh python=3.5
Fetching package metadata: ..........
Solving package specifications: ...........................
Package plan for installation in environment /Users/caged/miniconda3/envs/bokeh-test-5:

The following NEW packages will be INSTALLED:

    bokeh:           0.10.0-py35_0
    [ some packages omitted for brevity ]
    pandas:          0.17.0-np110py35_0
    pip:             7.1.2-py35_0
    python:          3.5.0-1
    python-dateutil: 2.4.2-py35_0
    [ some packages omitted for brevity ]

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|######################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate bokeh-test-5
#
# To deactivate this environment, use:
# $ source deactivate
#
➜  ~  ls /Users/caged/miniconda3/envs/bokeh-test-5
bin        conda-meta include    lib        share      ssl
````
Examples not available.

Also worth noting that if I do `conda create -n bokeh-env bokeh` that conda defaults to python 3.5 so I would get the undesired behavior by default.

@damianavila @bryevdv - maybe we shouldn't be putting out a 3.5 distro until we've tested it? Although I'm not sure we have a test for this anyway.

**Comment by damianavila** [comment]
@birdsarah, we did not put any 3.5 package out there... if there is one, I guess it was built by Ilan... but I explicitly did not build any 3.5 package until be sure everything was working OK... btw, it is in my plan to start testing 3.5 on Travis this week...

**Comment by woodscn** [comment]
Huh. I don't get the same results. 
```
~$ conda create -n bokeh-test-4 bokeh python=3.4
Fetching package metadata: ....
Solving package specifications: ........................................
Package plan for installation in environment ~/anaconda3/envs/bokeh-test-4:

The following NEW packages will be INSTALLED:

    bokeh:           0.10.0-py34_0     
    flask:           0.10.1-py34_1     
    itsdangerous:    0.24-py34_0       
    jinja2:          2.8-py34_0        
    markupsafe:      0.23-py34_0       
    numpy:           1.10.1-py34_0     
    openssl:         1.0.2d-0          
    pandas:          0.17.0-np110py34_0
    pip:             7.1.2-py34_0      
    python:          3.4.3-2           
    python-dateutil: 2.4.2-py34_0      
    pytz:            2015.7-py34_0     
    pyyaml:          3.11-py34_1       
    pyzmq:           14.7.0-py34_1     
    readline:        6.2-2             
    requests:        2.8.1-py34_0      
    setuptools:      18.4-py34_0       
    six:             1.10.0-py34_0     
    sqlite:          3.8.4.1-1         
    tk:              8.5.18-0          
    tornado:         4.2.1-py34_1      
    werkzeug:        0.10.4-py34_0     
    wheel:           0.26.0-py34_1     
    xz:              5.0.5-0           
    yaml:            0.1.6-0           
    zeromq:          4.1.3-0           
    zlib:            1.2.8-0           

Proceed ([y]/n)? 

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate bokeh-test-4
#
# To deactivate this environment, use:
# $ source deactivate
#
~$ ls anaconda3/envs/bokeh-test-4/
bin		include		share
conda-meta	lib		ssl
```

For Python 3.5, it's pretty much the same thing: 
```
~$ conda create -n bokeh-test-5 bokeh
Fetching package metadata: ....
Solving package specifications: ..............................
Package plan for installation in environment ~/anaconda3/envs/bokeh-test-5:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    itsdangerous-0.24          |           py35_0          16 KB
    pytz-2015.7                |           py35_0         173 KB
    pyyaml-3.11                |           py35_1         129 KB
    requests-2.8.1             |           py35_0         646 KB
    werkzeug-0.10.4            |           py35_0         403 KB
    flask-0.10.1               |           py35_1         135 KB
    pandas-0.17.0              |      np110py35_0         6.2 MB
    bokeh-0.10.0               |           py35_0         3.9 MB
    ------------------------------------------------------------
                                           Total:        11.5 MB

The following NEW packages will be INSTALLED:

    bokeh:           0.10.0-py35_0     
    flask:           0.10.1-py35_1     
    itsdangerous:    0.24-py35_0       
    jinja2:          2.8-py35_0        
    markupsafe:      0.23-py35_0       
    numpy:           1.10.1-py35_0     
    openssl:         1.0.2d-0          
    pandas:          0.17.0-np110py35_0
    pip:             7.1.2-py35_0      
    python:          3.5.0-1           
    python-dateutil: 2.4.2-py35_0      
    pytz:            2015.7-py35_0     
    pyyaml:          3.11-py35_1       
    pyzmq:           14.7.0-py35_1     
    readline:        6.2-2             
    requests:        2.8.1-py35_0      
    setuptools:      18.4-py35_0       
    six:             1.10.0-py35_0     
    sqlite:          3.8.4.1-1         
    tk:              8.5.18-0          
    tornado:         4.2.1-py35_1      
    werkzeug:        0.10.4-py35_0     
    wheel:           0.26.0-py35_1     
    xz:              5.0.5-0           
    yaml:            0.1.6-0           
    zeromq:          4.1.3-0           
    zlib:            1.2.8-0           

Proceed ([y]/n)? 

Fetching packages ...
itsdangerous-0 100% |################################| Time: 0:00:00 299.93 kB/s
pytz-2015.7-py 100% |################################| Time: 0:00:00 652.85 kB/s
pyyaml-3.11-py 100% |################################| Time: 0:00:00 613.69 kB/s
^[[Arequests-2.8.1   4% |#                               | Time: 0:00:00 316.98 requests-2.8.1 100% |################################| Time: 0:00:00   1.49 MB/s
werkzeug-0.10. 100% |################################| Time: 0:00:00   1.08 MB/s
flask-0.10.1-p 100% |################################| Time: 0:00:00 641.95 kB/s
pandas-0.17.0- 100% |################################| Time: 0:00:00   6.58 MB/s
bokeh-0.10.0-p 100% |################################| Time: 0:00:00   5.64 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate bokeh-test-5
#
# To deactivate this environment, use:
# $ source deactivate
#
~$ ls anaconda3/envs/bokeh-test-5/
bin		include		share
conda-meta	lib		ssl
```

**Comment by birdsarah** [comment]
that's interesting! can you do one more test to see if it makes a difference:

````sh
$ conda create -n bokeh-test-6 python=3.4
$ source activate bokeh-test-6
$ conda install bokeh
$ ls <wherever bokeh-test-6 env is>
````

lastly, what version of conda do you have, I am:
```sh
➜  ~  conda --version
conda 3.17.0
```

**Comment by woodscn** [comment]
I recently updated anaconda, to see if that fixed things; I don't remember what version I was on previously. I'll look and see if they've changed things to require a flag to include examples or something.

```
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
ls <bokeh-test-6-env>
bin		include		share
conda-meta	lib		ssl

~$ conda --version
conda 3.18.3
```

**Comment by woodscn** [comment]
Nothing's jumping out at me.

**Comment by HRKpython** [comment]
+1 Same Issue,  I fired up my bokeh server using "python bokeh-server" command.  My Python version is 2.7 and bokeh version: 0.10.0.  When I run the line_animate.py example, I will get this:

Traceback (most recent call last):
  File "line_animate.py", line 6, in <module>
    from bokeh.client import push_session
ImportError: No module named client

**Comment by bryevdv** [comment]
`bokeh.client` does not exist in version `0.10` you need to look at the tagged version of the repo appropriate to your installed version.

**Comment by bryevdv** [comment]
The "examples" link in the gallery has been made to point to a specific release now, so I am closing this. Also there is another issue to discuss other ways to make sure users are directed to versioned/tagged links in GH where appropriate.
