### ISSUE TITLE
y_axis_type='log' collapses values

### ISSUE THREAD

**Issue by shongololo** [bokeh/bokeh#3085]
When using the plotting parameter for a logged y axis:
```
y_axis_type='log'
```
Then the values collapse to the x axis and remain there regardless of panning and zooming. The issue only occurs for the y_axis_type parameter.

Safari browser on a Mac.

**Comment by bryevdv** [comment]
There are several example that use log axes, and they are all tested before release on multiple platforms. Perhaps you've uncovered a specific unknown bug condition, or misconfiguration that is easier to make than it should be. Can you supply a complete, minimal code sample that reproduces the problem? (A screenshot would also be appreciated). Thanks

**Comment by shongololo** [comment]
On further investigation it happens along either axis if any of the values is 0. (Presumably since log(0) is interpreted as negative infinity?)

When removing '0' values then it plots as expected.

Screenshot below of a log-log plot with the blue showing data without '0's and the yellow bumps along the bottom axis is from data with '0's.

![screen shot 2015-11-07 at 11 22 07 pm](https://cloud.githubusercontent.com/assets/4347878/11017874/6b49469c-85a6-11e5-95e8-62050fa76857.png)

**Comment by bryevdv** [comment]
I believe this was just fixed in master recently. It will be in the upcoming 0.11 release.

**Comment by shongololo** [comment]
awesome. Thanks.

**Comment by bryevdv** [comment]
Just be clear the fix is to map 0 to 0 which is not actually correct but seems to be what is most reasonable  (e.g the context was a bar chart on a log scale). If you have other requirements or suggestions please let us know
