### ISSUE TITLE
LinearColorMapper chokes on numpy.float32 used as maximum

### ISSUE THREAD

**Issue by dwf** [bokeh/bokeh#3086]
It's fine with Python floats but not `numpy.float32`. Bokeh 0.10.

**Comment by Zebreu** [comment]
Other charts (Scatter, Histogram) also show that problem, they failed with a non-obvious message ("Expected Column(Float) or Column(String) but got array([...])") when I was creating a DataFrame from a float32 numpy array (but works when using a float64 numpy array).

**Comment by bryevdv** [comment]
@dwf can you confirm if this is still and issue in `0.11.1`? If so can you provide a minimal test case?

**Comment by dwf** [comment]
Can't recall steps to reproduce but I'll try and dig them up. I believe I was using a Image glyph...

**Comment by bryevdv** [comment]
@dwf @Zebreu can either of you still reproduce this with `0.12.3` or newer? Can you provide a test case?

**Comment by bryevdv** [comment]
I am going to close this issue as stale. A huge amount of changes have happened at various levels that might impact this since the original report, and there is no test case to reproduce. If its found there is still some issue, please feel free to re-open with example code
