### ISSUE TITLE
Bar plot example seems to be broken

### ISSUE THREAD

**Issue by stroykova** [bokeh/bokeh#3092]
Here is my error [stacktrace](https://gist.github.com/stroykova/2905ca634b13fc494ba5)

Docs [example](http://bokeh.pydata.org/en/0.10.0/docs/reference/charts.html#bokeh.charts.Bar) also has error.

Error
Unable to generate Bokeh plot at /home/travis/build/bokeh/bokeh/sphinx/source/docs/reference/charts.rst:31:

Seen error when installed 0.10.0 after 0.9.0, where it was fine.

**Comment by bryevdv** [comment]
I believe the example in the docstring is out of date and does not use the new API.

**Comment by rothnic** [comment]
Closed by #2986. The example referenced comes from the bar_builder.py source and [has been updated](https://github.com/bokeh/bokeh/blob/8a0dd0b44d21124e5c0e30b2f7a419e551b35a52/bokeh/charts/builders/bar_builder.py#L65) for the 0.11 release.
