### ISSUE TITLE
Mark Document.add deprecated or remove TODO comment above it

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3103]
https://github.com/bokeh/bokeh/blob/5fab252f8fde29228b5a9bfafb53ece6c8d5d145/bokeh/document.py#L196-L210

This is a back-compat wrapper for `add_root()` - if we want to deprecate it at least document that it is, otherwise remove that TODO comment above it.

**Comment by mattpap** [comment]
PR #3212 was merged, so closing this issue.
