### ISSUE TITLE
Rename bokeh.application.spellings and SpellingHandler

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3105]
The current name is not clear.

We have:
 * abstract base class: `bokeh.application.spellings.SpellingHandler`
 * example subtypes (not all exist yet): `bokeh.application.spellings.ScriptHandler`, `RedisHandler`, `DirectoryHandler`, etc.

Some suggestions so far include:

 * bokeh.application.handlers.FormatHandler, ScriptHandler, RedisHandler, DirectoryHandler
 * bokeh.application.modifiers.DocumentModifier, ScriptModifier, RedisModifier, DirectoryModifier
 * bokeh.application.formats.Format, ScriptFormat, RedisFormat, DirectoryFormat
 * bokeh.application.sources.Source, ScriptSource, RedisSource, DirectorySource

**Comment by fpliger** [comment]
The tricky aspect of this is understanding what "spelling" is. The concept is that these are `document` modifiers in the sense that they can "feed" an `app`. This could mean we are using a spelling to add a datasource to the `document` (like the examples above) but also a spelling that actually builds a Figure/UI out of a JSON or YAML file. Right?

If this is correct then I'd be -1 for using `Source`. Also, `Format` is a bit too vague... I'm +0 on the others.. what about `Plugin`?

**Comment by havocp** [comment]
Bryan and I were liking "Handler" when we were talking yesterday - but instead of `FormatHandler` for the base class, maybe `AbstractHandler` or `ApplicationHandler` - thoughts?
We didn't think of Plugin though. `ApplicationPlugin` or something perhaps.

For me, Format, Handler, and Plugin are all better than Spelling.

**Comment by bryevdv** [comment]
I was thinking `ApplicationHandler` as the base.

**Comment by fpliger** [comment]
`ApplicationHandler` sounds good to me too.

**Comment by bryevdv** [comment]
This was done
