### ISSUE TITLE
multi_line and selection callback

### ISSUE THREAD

**Issue by chan-y-park** [bokeh/bokeh#3110]
Hi,

Is ``multi_line`` supposed to work with a selection callback? For example, when I draw a point plot from a data source, attaching a selection callback to the data source works well, i.e. it returns the index of the selected point, but when I use ''multi_line'' for the same data source and click a line, the callback gets nothing from ``cb_obj.get('selected')``.

**Comment by bryevdv** [comment]
Selection hit testing has not been implemented for multi line yet. It would make a nice small PR for a new contributor.

**Comment by bryevdv** [comment]
@chan-y-park this will be in `0.12.2`
