### ISSUE TITLE
Should `PlotObject.on_change` _and_ the callback itself both get an attribute name?

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3114]
Right now the attribute name is in both places:
```
def my_callback(attr, old, new):
  pass
model.on_change('foo', my_callback)
```

So in the above code, `attr` in the callback will always be `foo` since we only connect the callback to one attribute. I don't think it will be common for callbacks to look at `attr`, so having it there is a little bit of extra typing.

The current API does enable one callback to handle several attributes, but that seems a bit like a 10% rather than 90% case to me. To support it, we could have:
```
model.on_any_change(multi_callback)
```

Where the callback is called if ANY attribute changes and receives the attribute name... also people can do:
```
model.on_change('foo', lambda old, new: my_callback('foo', old, new))
```
which is a touch verbose... but since it isn't something commonly needed, perhaps it's enough to be possible rather than as-easy-as-possible.

Another possibility could be 'magic' - if the callback has three args we provide attr, if two args we don't - but I was thinking of using the same magic to omit calculating and providing the `old` arg, and I guess this trick can only be used to make one of the args optional or it gets ambiguous. Also this is sort of magic.

**Comment by fpliger** [comment]
+1 on having `on_change` and `on_any_change`.. at this point we could unify `Document` and `PlotObject` APIs (see #3115) and make `Document` only have `on_any_change` until we need to implement the more specific `on_change` function.

**Comment by havocp** [comment]
not worth changing the API at this point
