### ISSUE TITLE
Consider a `bokeh serve` example that loads/saves from Redis

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3116]
The main point of this exercise is to have a better answer on an issue like https://github.com/bokeh/bokeh/issues/3087

The old bokeh-server would load and save from Redis; it should be straightforward to have a script that you run with `bokeh serve myexample.py` which loads from Redis, and an accompanying simple function that saves to Redis (callable from a separate script). This would replicate the old server setup for people who were using it... they would run Redis, configure their server script to load from it, and configure their client script that previously used `output_server` to instead save to Redis. If there's no good way to watch Redis for changes, we could `add_periodic_callback` a poll callback perhaps.

To be clear, I'm not suggesting (at least for now, due to time limitations) putting the load/save from Redis functionality directly in Bokeh, but inlining them in the example - I think the functions to load and save a Document from Redis would be pretty short. If not then this idea looks not so good.

**Comment by mattpap** [comment]
I think we don't need to concern with redis anymore.
