### ISSUE TITLE
Expose the wheel zoom speed in Python

### ISSUE THREAD

**Issue by liuyxpp** [bokeh/bokeh#3125]
The sensitivity of the wheel zoom cannot be configured on the Python side. However, there is a `speed` property which can be set on the JS side. It would be better to expose this property to the Python side too.

**Comment by birdsarah** [comment]
@liuyxpp we are actually in the middle of a big clean-up to ensure that the properties on the python and JS side match each other. 

@havocp WheelZoomTool has a default for `speed` on the JS side (https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/tool/gestures/wheel_zoom_tool.coffee#L119) but not a python property.

However running the test in #3099 doesn't pick up this discrepancy. Thoughts?

**Comment by birdsarah** [comment]
Maybe the test only picks up differences in defaults not when there's missing properties?

**Comment by bryevdv** [comment]
@birdsarah maybe https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/tool/gestures/wheel_zoom_tool.coffee#L113

**Comment by birdsarah** [comment]
great spot @bryevdv, do you know why that would be?

**Comment by bryevdv** [comment]
Why that line exists? @havoc added that to get things working at all. Currently the client models add all kind of new attributes with abandon and most of them should not get serialized back to the server. But a few like this one should be, but were just overlooked. We should have been more careful in the first place and made client only "viewmodel" objects to store any new, extra, "not intended to be serialized" data, and and kept the main models pure and 1-1 in sync with Python (no extra attrs added). We still should do this some day.

**Comment by havocp** [comment]
Python would raise an exception at one point if it saw an unknown property... now it just warns. So I was having to mark tons of props as nonserializable. It sounds like the better fix here was to simply add the prop to Python.

**Comment by birdsarah** [comment]
thanks for the background @havocp and @bryevdv still learning how the all the pieces of the properties mechanism works.

**Comment by bryevdv** [comment]
We can certainly expose the speed, but unless we can also find a way to make a given speed somewhat uniform across browsers I am dubious of the utility. But changing to `feature` in any case.

**Comment by damianavila** [comment]
Reopening because the PR was reverted by https://github.com/bokeh/bokeh/pull/4831
