### ISSUE TITLE
output_server() does not work with bokeh.charts interface?

### ISSUE THREAD

**Issue by mmcdan** [bokeh/bokeh#3131]
Hello, I am having issues using bokeh.charts interface with output_server(). The charts do not render. I am having no issues using bokeh.plotting with output_server(). I can get the bokeh.charts interface to render if I user server=True and the .show() method. Is the use of output_server discouraged with the bokeh.charts interface? 
See examples below:

__bokeh.charts with output_file()__: This outputs a bar chart in the browser.
```python
from bokeh.charts import Bar, output_file, output_server, show
from bokeh.sampledata.iris import flowers

output_file("bar")
p = Bar(flowers, 'species', values='petal_length')
show(p)
```
__bokeh.charts with output_server()__: This renders a blank chart in the browser. bokeh-server is running.
```python
from bokeh.charts import Bar, output_file, output_server, show
from bokeh.sampledata.iris import flowers

output_server("bar")
p = Bar(flowers, 'species', values='petal_length')
show(p)
```

__bokeh.charts with server=True, .show()__: This outputs a bar chart in the browser. bokeh-server is running.
```python
from bokeh.charts import Bar, output_file, show
from bokeh.sampledata.iris import flowers

p = Bar(flowers, 'species', values='petal_length', server=True).show()
```

**Comment by havocp** [comment]
Are you using master or 0.10 ? On master, I think `server=True` isn't really using the server, see https://github.com/bokeh/bokeh/issues/3132 that I just filed.

**Comment by mmcdan** [comment]
Using bokeh 0.10.0. In my case it is hitting the server. If I do not start bokeh-server, I get an error. If I do start it, the plot shows up.

**Comment by bryevdv** [comment]
I'm not sure what's up with `0.10` but there is nothing we can do about it, the old server is already gone in master and will not be around in `0.11`. FWIW this is what happens on master:
```
/Users/bryan/work/bokeh/bokeh/charts/attributes.py:204: RuntimeWarning: Properties {'iterable'} were defined in two classes, one of them <class 'bokeh.charts.attributes.AttrSpec'>, as part of defining <class 'bokeh.charts.attributes.ColorAttr'>
  super(ColorAttr, self).__init__(**kwargs)
/Users/bryan/work/bokeh/bokeh/charts/attributes.py:231: RuntimeWarning: Properties {'iterable'} were defined in two classes, one of them <class 'bokeh.charts.attributes.AttrSpec'>, as part of defining <class 'bokeh.charts.attributes.DashAttr'>
  super(DashAttr, self).__init__(**kwargs)
/Users/bryan/work/bokeh/bokeh/charts/attributes.py:216: RuntimeWarning: Properties {'iterable'} were defined in two classes, one of them <class 'bokeh.charts.attributes.AttrSpec'>, as part of defining <class 'bokeh.charts.attributes.MarkerAttr'>
  super(MarkerAttr, self).__init__(**kwargs)
/Users/bryan/work/bokeh/bokeh/charts/attributes.py:140: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort(columns=columns, ascending=self.ascending)
/Users/bryan/work/bokeh/bokeh/charts/glyphs.py:99: RuntimeWarning: Properties {'line_color', 'fill_alpha'} were defined in two classes, one of them <class 'bokeh.charts.models.CompositeGlyph'>, as part of defining <class 'bokeh.charts.glyphs.PointGlyph'>
  super(PointGlyph, self).__init__(**kwargs)
INFO:bokeh.client.connection:Connection closed by server
```
ping @rothnic something to keep in mind as work on charts for `0.11`.

**Comment by bryevdv** [comment]
Here was the code I ran, for completeness:
```
from bokeh.sampledata.iris import flowers as data
from bokeh.charts import Scatter, output_server, show

scatter = Scatter(data, x='petal_length', y='petal_width',
                  color='species', marker='species',
                  title='Iris Dataset Color and Marker by Species',
                  legend=True)

output_server("foo")

show(scatter)
```

**Comment by havocp** [comment]
One thought - when you get a blank page often there's something in the javascript console.

**Comment by bryevdv** [comment]
Not in this case:
<img width="555" alt="screen shot 2015-11-16 at 1 14 21 pm" src="https://cloud.githubusercontent.com/assets/1078448/11191957/fa8e0004-8c63-11e5-9230-cc3a20329164.png">

**Comment by rothnic** [comment]
I think I remember some issues with rendering to server before the server refactor, but thought I fixed them enough to render the plot. There is a little bit more work I need to do once I get it working with the new server so that we can build interactive apps around a chart.

It seems like the issue we see is due to overriding properties on a parent class. If this isn't allowed with the new server, I can rework these types of configurations so they are input through init, since I was planning on doing this at some point anyways.

I'm looking into it and will hopefully have it fixed up on master in the next day or two.

**Comment by havocp** [comment]
I don't think those warnings about overriding properties are related, those are just general warnings that we need to refactor those classes a little bit.

**Comment by fpliger** [comment]
is it because you've already added `f` as root and you are reusing as child or just breaks with more the one root?

**Comment by havocp** [comment]
it's because it's both a root and a child. When you render a document to HTML, we render all the roots in a sequence (sort of in an implicit vbox). So if you also add a root plot to another container, that plot is in two places, which bokehjs doesn't support.

**Comment by fpliger** [comment]
Got it, thanks!

We could try to remove magic or try to detect the case and either try to "do the less worst solution" or raise an error so the user can fix it manually, or....? But this discussion would probably owe it's own issue/discussion? :)

**Comment by havocp** [comment]
yeah - it's already a validation warning, but it makes the convenience figure() API a little confusing I think. maybe a solution is to make embed.coffee ignore roots that are also in non-root layouts. Let's make an issue to discuss.
