### ISSUE TITLE
restore `Chart(server=True)`

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3132]
server=True mode was commented out at some point on master, it needs to be restored (or replaced with something that makes more sense with the new server, possibly? I haven't investigated the big picture).

See https://github.com/bokeh/bokeh/blob/2a3ad528279e3b329857d712b61fcca536a59cf8/bokeh/charts/chart.py#L123-L128

For how to fix it up: https://github.com/bokeh/bokeh/wiki/Porting-guide:-new-Bokeh-server

**Comment by bryevdv** [comment]
I think we should just remove this argument and use standard `bokeh.io` APIs for serving charts. ping @bokeh/core

**Comment by fpliger** [comment]
@bokeh/core shall I go ahead in this direction and remove `Chart.show`, and all the support for `document`, `notebook` and `server` arguments?

**Comment by bryevdv** [comment]
I would suggest this:
```
@deprecated("Bokeh 0.11", "use bokeh.io.show(...) instead")
def show(self):
    import bokeh.io
    bokeh.io.show(self)
```

**Comment by bryevdv** [comment]
But just to expand, I absolutely think *all* IO should eventually go through `bokeh.io` so there are not multiple things and ways to document.

**Comment by fpliger** [comment]
Cool.. will do it. Thanks
