### ISSUE TITLE
Tabs widget on Server

### ISSUE THREAD

**Issue by softengash** [bokeh/bokeh#3138]
Using bokeh 0.10.0

Using tabs widget for different kinds of charts. It works fine for static pages but running it on server makes all the charts on a single page below one another.(no tabs are created)

is this an expected behavior?

**Comment by birdsarah** [comment]
A code sample and a screenshot would help a lot - gives us something to debug and test against.

**Comment by softengash** [comment]
It doesn't create tabs.

--- sample code

from bokeh.models.widgets import Panel, Tabs
from bokeh.io import output_file, output_server, show
from bokeh.plotting import figure

output_server("test")

p1 = figure(plot_width=300, plot_height=300)
p1.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
tab1 = Panel(child=p1, title="circle")

p2 = figure(plot_width=300, plot_height=300)
p2.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=3, color="navy", alpha=0.5)
tab2 = Panel(child=p2, title="line")

tabs = Tabs(tabs=[ tab1, tab2 ])

show(tabs)

**Comment by bryevdv** [comment]
This also seems to affect current master. It's just not rendering the Tabs model at all for some reason:
<img width="917" alt="screen shot 2015-11-18 at 9 00 33 am" src="https://cloud.githubusercontent.com/assets/1078448/11244384/00e4cde6-8dd3-11e5-8516-41f0ab6385bb.png">

The right view is an `output_file` that works

**Comment by bryevdv** [comment]
@canavandl please evaluate

**Comment by canavandl** [comment]
This bug is present in the 0.11.0 release. @bryevdv is correct that the Tab model doesn't appear to load.

**Comment by canavandl** [comment]
In the example code above, it appears that the server command is adding the plots (p1 and p2) to the document instead of a Tab widget containing two Panels containing the plots (i.e. ``Tabs(Panel(p1), Panel(p2))``)

Essentially we need to remove the children plots from the document and then ``add_root`` the tab widget, like what happens with VBox/HBox -> vplot/hplot

**Comment by bryevdv** [comment]
This should fall out of the layout work but tagging `0.12` to make sure to check / verify.

**Comment by birdsarah** [comment]
Issue: https://github.com/bokeh/bokeh/issues/3650 covers the more generic case so marking this as a dupe.
