### ISSUE TITLE
relative protocol URLs for generated JS/CSS URLS?

### ISSUE THREAD

**Issue by ahmadia** [bokeh/bokeh#3143]
For example, 'cdn' mode for [Resources](http://bokeh.pydata.org/en/0.10.0/docs/reference/resources_embedding.html) hits the http:// CDN by default, instead of https.  Is it intended that if a user is serving up HTTPS, they are discouraged from using the CDN?  Should Bokeh provide the relative protocol url `//example.com` syntax structure instead?

**Comment by bryevdv** [comment]
It's already changed on master to always default to https
