### ISSUE TITLE
Improve document changed events chain (MultipleDispatching)

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3147]
Idea is to move logics away from session/document. Idea proposed is using [multiple dispathing](http://python-3-patterns-idioms-test.readthedocs.org/en/latest/MultipleDispatching.html). Something along the lines of: (untested!!)

```Python
class DocumentChangedEvent(object):
    def dispatch(self, receiver):
        if hasattr(receiver, '_document_changed'):
          receiver._document_changed(self)

class SessionCallbackAdded(DocumentChangedEvent):
    def dispatch(self, receiver):
        super(SessionCallbackAdded, self).dispatch(receiver)
        if hasattr(receiver, '_session_callback_added'):
          receiver._session_callback_added(self)
```

Receiver would have to attach like this I guess:

 ```Python
document.on_change(lambda event: event.dispatch(self))
```
That could maybe be a convenience method on Document, like:

 ```Python
class Document:
  def on_change_dispatch_to(self, receiver):
     self.on_change(lambda event: event.dispatch(receiver))
```

Original discussion: #3119

**Comment by datnamer** [comment]
Would it help to leverage this library: https://github.com/mrocklin/multipledispatch?

Its also used in blaze.

**Comment by fpliger** [comment]
> Would it help to leverage this library: https://github.com/mrocklin/multipledispatch?

@datnamer thanks for the suggestion. In this specific case I'd tend to avoid yet another dependency since out MD needs are not that hard/long to tackle. other @bokeh/core have strong opinions about this?

**Comment by fpliger** [comment]
Was thinking a bit more about this:

> Receiver would have to attach like this I guess:

>```
>document.on_change(lambda event: event.dispatch(self))
>```
> That could maybe be a convenience method on Document, like:
```
class Document:
  def on_change_dispatch_to(self, receiver):
     self.on_change(lambda event: event.dispatch(receiver))
```

and we'd end up having the problem of lambda capturing the original event dispatcher. So this https://github.com/bokeh/bokeh/blob/master/bokeh/document.py#L376 would not work anymore. We can surely deal with it but I don't have an option that makes me really happy...  For instance, having a `dict` of callbacks instead of `list` would let us track the original callback and do the job but, again, feel that using lambda is a bit of a hack. Maybe in this context we should talk more about `receivers` then `callbacks`? (but also in this case I don't think it's a perfect match..).

@bokeh/core , specially @havocp do you have thoughts/suggestions?
