### ISSUE TITLE
I can't update data in plot.quad, yet I can update data in plot.line or plot.circle as in "sliders_app.py"

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#3151]
I am using version 11 (the developer version). Using "sliders_app.py" as a template, I am trying to update a histogram as follows 
```
plot = Figure(title_text_font_size="12pt",
              plot_height=600,
              plot_width=600,
              tools="crosshair,pan,reset,resize,save,wheel_zoom",
              title="title",
              x_range=[0, 200],
              y_range=[0, 0.04]
        )

source = ColumnDataSource(data=dict(top=[], bottom=[], left=[], right=[]))
plot.quad('top', 'bottom', 'left', 'right', source=source, fill_color="blue", 
          line_color="blue")

def update_data():
    hist, edges = np.histogram(randomData, density=True, bins=100)
    source.data = dict(top=hist, bottom=np.zeros(len(hist)), 
                       left=edges[:-1], right=edges[1:])
```
I tried the following, it is not working either???
```
def update_data():
    source.data = dict(top=[0.02,0.02,0.02,0.02], bottom=[0,0,0,0], 
                       left=[0,50,100,150], right=[50,100,150,200])
```
However, if I just plot the following, it is working.
```
plot.quad(top=[0.02,0.02,0.02,0.02], bottom=[0,0,0,0], left=[0,50,100,150], 
          right=[50,100,150,200],fill_color="blue", line_color="blue")
```

**Comment by fpliger** [comment]
@charleywan2004 Quad positional arguments spec order is `left`, `right`, `top`, `bottom` so 

```python
plot.quad('top', 'bottom', 'left', 'right', source=source, fill_color="blue", line_color="blue")
```

should be:

```python
plot.quad('left', 'right', 'top', 'bottom', source=source, fill_color="blue", line_color="blue")

#or

plot.quad(top='top', bottom='bottom', left='left', right='right', source=source, fill_color="blue", line_color="blue")
```

I've double check and your code works for me with those changes.

Have you copied that code (or read) somewhere in our official docs, examples, etc? In that case can you let us know so we can check and fix if there is wrong information around?

thank you!

**Comment by fpliger** [comment]
@charleywan2004 do you have any update about this?

**Comment by charleywan2004** [comment]
It is my fault. I use the example from http://bokeh.pydata.org/en/0.10.0/docs/gallery/histogram.html

I thought 
p1.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
     fill_color="#036564", line_color="#033649",\
)
means the order of parameters are "top", "bottom", "left" and "right"

**Comment by fpliger** [comment]
Cool. Thanks for clarifying!
