### ISSUE TITLE
BUG in legend - Hovertool

### ISSUE THREAD

**Issue by HRKpython** [bokeh/bokeh#3157]
I tried to add a legend for each of the circle (lets assume three different categories). The legend does not working.
```
import numpy as np
from collections import OrderedDict
from bokeh.plotting import ColumnDataSource, figure, show, output_file
from bokeh.models import HoverTool

output_file("hover.html")
xx, yy = np.meshgrid(range(0,11,4), range(0,11,4))
x1 = xx.flatten()
y1 = yy.flatten()
N = len(x1)
radii = np.random.random(size=N)*0.4 + 1.7
cat = ['1','1','2','2','3','2','2','3','2']

source = ColumnDataSource(
    data=dict(
        x=x1,
        y=y1,
        radius=radii,
        cat = cat
    )
)

p = figure(title="Hoverful Scatter", tools='hover')

p.circle(x1, y1, radius=radii, fill_alpha=0.6, line_color=None, legend='cat')

hover =p.select(dict(type=HoverTool))
hover.tooltips = OrderedDict([
    ("(x,y)", "($x, $y)"),
])

show(p) 
```

**Comment by bryevdv** [comment]
Well, this is not a bug, this is the current intended behavior. The "auto" legend adds entries for each *renderer*, if you want to have three entries in the legend, you need a different circle renderer for each entry. If you have 100 circles from one circle renderer, how many legend entries should there be? There's no way to automatically guess every user's intention that I can think of, except to make the association between renderers and legend entries explicit as Bokeh does.

**Comment by bryevdv** [comment]
I should add, the higher level `bokeh.charts` API does make some attempts, but that is because it relies on Pandas, which has notions of groups and aggregations, etc. that can inform the legend creation.

**Comment by HRKpython** [comment]
I agree, I will try with three different circle renders.  Thanks for your help
