### ISSUE TITLE
bokeh server over internet

### ISSUE THREAD

**Issue by softengash** [bokeh/bokeh#3158]
using bokeh 0.10.0

My app is on my bokeh server. Is there any way my friend can access it over internet?

brought up bokeh server using localhost, 0.0.0.0 then tried to access it over internet using my public ip - not working
tried to bring up bokeh server using my public ip but it errors out

Kindly advice the right way.

**Comment by bryevdv** [comment]
It's definitely possible, the currently deployed examples in the server gallery demonstrate this. It's hard to say without more information, is it possible you do not have external access to ports enabled on the machine you are running (i.e., firewall config issue)? 

I should add, there is coming in `0.11` a completely new server that is drastically better than the old server. It is more robust, easier to deploy, and simpler to write apps for. We will have lots of examples and demos and documentation for it very soon.

**Comment by softengash** [comment]
Thanks for the update! Looking forward to 0.11 version.

For now I used ngrok for the resolution.
