### ISSUE TITLE
Error in simple date_time plot and zoom.

### ISSUE THREAD

**Issue by waqarmalik** [bokeh/bokeh#3163]
There are a few issues in simple scatter plot where one of the axis is date_time. Consider the following program where the plot should start at 00:00:00 of 05/20 and should continue for one day. 
Problem 1: (Minor) Bokeh starts plotting form 1000 hrs. This could be due to handling of time-zones.

Problem 2: (Major) Try using wheel zoom. The plot starts behaving very erratically and jumps all over the place. If I am over a point I would expect that point to be stationary while zooming.

Problem 3: (Major) Hover does not work correctly.

Using conda: 3.18.5, bokeh: 0.10.0, OS X: 10.9.5, Chrome: 46.0.2490.86, Firefox 38.3
```
import pandas as pd
import numpy as np
import bokeh.plotting as plt

def main():
  x = pd.date_range(start='2014-05-20', end='2014-05-21', freq='10min')
  y = np.sin(x.astype(int)/1400544000000000) + 0.5*np.random.rand(len(x))
  
  plt.output_file('zoom_test.html')
  TOOLS = 'xpan, xwheel_zoom, reset'
  p1=plt.figure(webgl=True, tools=TOOLS, x_axis_type="datetime")
  p1.scatter(x,y,size=19, color='blue', alpha=0.5)
  plt.show(p1)


if __name__=='__main__':
  main()
```

**Comment by waqarmalik** [comment]
The problem seems to be in webgl inteface. If I put webgl=False, the plot behaves well.

**Comment by waqarmalik** [comment]
Duplicate #3137

**Comment by bryevdv** [comment]
ping @birdsarah I am having trouble turning on the wheel zoom by clicking the button. It's not working at all on chrome for me, it just leaves this weird persistent highlight:
<img width="228" alt="screen shot 2015-11-18 at 4 16 03 pm" src="https://cloud.githubusercontent.com/assets/1078448/11256116/b3f87716-8e0f-11e5-8ac0-388d89f7b7f7.png">

however, when I can get it to zoom, it seems to be zooming correctly. can you try on a  recent dev build @waqarmalik 

Also it starts out in this configuration:
<img width="606" alt="screen shot 2015-11-18 at 4 15 16 pm" src="https://cloud.githubusercontent.com/assets/1078448/11256141/cd67fc44-8e0f-11e5-8ef8-f12650536cd4.png">
Are you saying that this is incorrect or that you see something different?

**Comment by bryevdv** [comment]
OK zooming with `webgl=True` does seem erratic on Firefox (webgl has never worked on safari on my laptop so I first tried with it off), @almarklein can you comment?

**Comment by bryevdv** [comment]
Perhaps this is only now exposed because of the large magnitude of the x coordinates.

**Comment by almarklein** [comment]
This has indeed been a problem and should now be fixed in master per #2956. If the bug is still there this certainly needs another look.

**Comment by bryevdv** [comment]
I was just trying on current master.

**Comment by damianavila** [comment]
@bryevdv maybe you are hitting this? http://bokeh.pydata.org/en/0.10.0/docs/faq.html#are-the-tools-not-working-in-chrome-cromium

**Comment by bryevdv** [comment]
Possibly, but I doubt it? It's never been a problem for me on chrome anywhere else.

**Comment by xdliao** [comment]
When time series plot zoom to within one hour, the x axis tick labels no longer has hour displayed
(such as :10, :15) which is makes it difficult to know which hour it is. The same issue of losing minute info when zoom into one minute window (displaying '6s','8s',...).
