### ISSUE TITLE
Changing tool in toolbar is unresponsive for animated line plots

### ISSUE THREAD

**Issue by rizzir** [bokeh/bokeh#3166]
Trying out live animation examples I faced an issue with the toolbar. If I try to change e.g. from the pan tool to the box zoom tool it sometimes does not work. The chance to work gets smaller with increasing the update rate. If I set the update rate to 10Hz (time.sleep(0.1)) I can see the annotation of the tool in the toolbar flicker with that frequency.

I've tried the following examples with Chromium 45 as well as Firefox 42 with Bokeh 0.10.0 but the result is the same:

https://github.com/bokeh/bokeh/blob/0.10.0/examples/plotting/server/line_animate.py
https://github.com/bokeh/bokeh/blob/0.10.0/examples/plotting/server/line_animate_widget.py

**Comment by bryevdv** [comment]
This discussion refers to the old `bokeh-server` which has been completely removed. I cannot reproduce the problem described with the new `bokeh serve` and the `examples/app/ohlc` streaming app. If a problem persists with Bokeh > `0.11` please open a new bug report with accompanying test case.
