### ISSUE TITLE
Slider ignores changes to the model

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3169]
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/widget/slider.coffee

If you update start/end/etc. the slider doesn't get updated. Just connecting `@render` to the change event seems to break, so the render method may need tweaking somehow.

**Comment by mdcb** [comment]
pls. note I only recently started experimenting with bokeh.

Is the issue more widespread than just sliders ?

In my application, different web browser clients send/receive data to a single 'compute node', I would need all my input widgets (e.g. sliders, etc.) to reflect the value currently used by the compute node
If a web client changes a value, I need the capability to set it on other browser clients.  Having that capability without triggering callbacks would be immensely useful too.

My prototype looks as follow:

```
[browser] <-----> [bokeh session] <<-----
                                         |------>> [server]
[browser] <-----> [bokeh session] <<-----

<<---->> can be zmq or nn_msg
[server] is where you implement the logic of the application (pull input, compute, publish output
```

**Comment by havocp** [comment]
Many of the coffeescript views have logic to update when the model changes, and they are supposed to in general, but slider does not. Of course it's possible that there are bugs in other views but they would be considered buggy if they don't notice model changes.

However, each bokeh session has its own state (in 0.11dev and beyond), they do not share the same model state.

**Comment by mdcb** [comment]
quickly playing from the slider example that brought me here in the first place; TextInput seemed to have the same issue, but I might be mistaken - will try and check more thoroughly.

**Comment by bryevdv** [comment]
@mdcb all components should respond appropriately when if their properties change. But much of the JS code was written a long time ago. We are in the middle of a big cleanup that should make it easier to make sure all the "plumbing" is correct in a more systematic way.

**Comment by mdcb** [comment]
Thanks, I will look forward upcoming updates.
btw. congrats all involved, very exciting project.

**Comment by alecgunny** [comment]
Just calling `@render` breaks because of the lines
```
    @$el.empty()
    html = @template(@model.attributes)
    @$el.html(html)
```
at the start of `render`.

https://github.com/alecgunny/bokeh/blob/slider_update/bokehjs/src/coffee/widget/slider.coffee

I created a dummy function called `pchange` that recreates `render` without these lines and it seems to get the job done correctly, though I'm sure there's a more elegant way of handling this.  Here's an example demonstrating what it does

https://github.com/alecgunny/bokeh_examples/blob/master/select_sliders.py

**Comment by bryevdv** [comment]
The issue was that those lines should only happen once. I moved them to the initializer and everything works great. This will be in the next dev build and `0.11` release.
