### ISSUE TITLE
Can button be disabled?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#3170]
In pyqt4, button can be set enabled True of False, e.g. self.Button.setEnabled(True).

Can we do the same for Button in Bokeh? e.g. Button  = Button(label="button", type="success"), where to setEnabled? Same question for other input widgets, such as selection, etc?

**Comment by birdsarah** [comment]
The JSON prototype of the button has a disabled property.

http://bokeh.pydata.org/en/latest/docs/reference/models/widgets.buttons.html#bokeh.models.widgets.buttons.Button

Unfortunately this isn't exposed on the python side at the moment.

**Comment by birdsarah** [comment]
(you could probably work around setting the button to disabled manually.

**Comment by bryevdv** [comment]
I think it is exposed via the `disabled` property:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/widget/button.coffee#L27

**Comment by bryevdv** [comment]
On the python side this is defined on `Component`

https://github.com/bokeh/bokeh/blob/master/bokeh/models/component.py#L12

**Comment by charleywan2004** [comment]
Thank you very much!

Yes, I can set "button.disabled" to True or False.

**Comment by birdsarah** [comment]
@bryevdv - are there ways we can better reflect this in the reference guide? Maybe we don't want to show all parameters that a model inherits, but in a case like this it would have been useful.

**Comment by birdsarah** [comment]
ps @charleywan2004 sorry for the confusion, I should have looked a bit closer.

**Comment by bryevdv** [comment]
Closing discussion for inactivity
