### ISSUE TITLE
`pull_session` should let you provide app_path, host, port

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3171]
It's a pain to construct / figure out the websocket url for pull_session:
https://github.com/bokeh/bokeh/blob/d06b4dd27402921bfb3d73d08e4b785c774ee280/bokeh/client/session.py#L43

It would be more logical I think to provide app_path, host, and port. Or provide a utility function that assembles a websocket url from server url and app_path... maybe `websocket_url_for_server_url` could take a base server url, and an app_path ? https://github.com/bokeh/bokeh/blob/d06b4dd27402921bfb3d73d08e4b785c774ee280/bokeh/resources.py#L30

**Comment by havocp** [comment]
Maybe we should standardize on providing "server url" plus "app path", which is also what output_server probably needs... output_server already takes the server url.

**Comment by birdsarah** [comment]
on #3279 you noted: 

> pull_session wants a thing like `ws://bokeh.allthedata.com/foo/ws`. So #3171 is that it should be maybe `pull_session(url='http://bokeh.allthedata.com', app_path='/foo')` or along those lines, and then it assembles it for you.

Can I suggest that the url should be configurable in a bokeh server config file. Otherwise, in a large webapp that's going to get repetitive.

**Comment by havocp** [comment]
`pull_session` is in a client not in the (bokeh) server though... in a server-that-is-a-bokeh-client like django or flask app you could make it a config option and then make a little wrapper?

```
def bokeh_pull(app_path):
  return pull_session(config.bokeh_server, app_path)
```

?
