### ISSUE TITLE
Can I specify the size of an input widget, e.g. slider? Can I specify the orientation of a slider?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#3178]
Can I specify the size of an input widget, e.g. slider? Can I specify the orientation of a slider, e.g. from horizontal to vertical?

I am trying to print out a nice report of a set of Bokeh input/output widgets from the web browser, and need to adjust the sizes of all the widgets. I can adjust the sizes of the charts but I don't know how to adjust the sizes of the input widgets. Is there component level property to specify (just like the "disabled" property)?

Is there any guideline or tool for printing out nice report from web browser?

**Comment by birdsarah** [comment]
Hi, I don't think so, I think they grow to the size of box they're in. When I've done this in the past, I've just put them in an html div and made that div the size I wanted.

**Comment by charleywan2004** [comment]
I am using bokeh interactive widgets and push it to bokeh server, I don't write html. I put a set of sliders in a VBoxForm. As you said, sliders change with the size of the box, so I can specify the size of the VBoxForm then, how to do that?
```
T_avg = Slider(title="T_avg (C)", name='T_avg', value=119, start=80, end=150)
P_avg = Slider(title="P_avg (kPa)", name='P_avg', value=215, start=150, end=250)
R_avg = Slider(title="R_avg (m3/d)", name='R_avg', value=4259, start=1000, end=7000)
AVG = VBoxForm(children=[T_avg,P_avg,R_avg])
```

**Comment by birdsarah** [comment]
I haven't tried this, but looking https://github.com/bokeh/bokeh/blob/0.10.0/bokeh/models/widgets/layouts.py#L27 all Layouts (inc. VBoxForm) accept a width and a height. Have you tried that?

**Comment by charleywan2004** [comment]
I tried 
```
T_avg = Slider(title="T_avg (C)", name='T_avg', value=119, start=80, end=150)
P_avg = Slider(title="P_avg (kPa)", name='P_avg', value=215, start=150, end=250)
R_avg = Slider(title="R_avg (m3/d)", name='R_avg', value=4259, start=1000, end=7000)
AVG = VBoxForm(children=[T_avg,P_avg,R_avg],width=25,height=75)
```
it does not change the size of the "VBoxForm"

**Comment by artemonster** [comment]
Setting a height of a parent Hbox/Vbox just crops the controls :/

**Comment by bryevdv** [comment]
Closing this discussion to clean up the tracker. There is currently comprehensive work being to improve  layout that will go into `0.12` when it is ready. 

To add: current sliders have an `orientation` property: http://bokeh.pydata.org/en/latest/docs/reference/models/widgets.inputs.html#bokeh.models.widgets.inputs.Slider.orientation 

I would very much like to replace the current sliders with new ones but the ones in mind don't support vertical (but the trade-off would give double sliders, date sliders, much better visuals...)
