### ISSUE TITLE
Helping users get the right versions of examples

### ISSUE THREAD

**Issue by lbrito1** [bokeh/bokeh#3186]
Hi, 

I'm trying to run [this example](https://github.com/bokeh/bokeh/blob/master/examples/embed/embed_multiple_responsive.py). I'm getting the following error:

    js_resources = resources.render_js()
    AttributeError: 'Resources' object has no attribute 'render_js'

Am I missing something? Bokeh is up-to-date as far as I know:

    lbrito@lbrito:~/Documents/code/snippets$ pip list | grep bokeh
    bokeh (0.10.0)

Any help is appreciated.

**Comment by bryevdv** [comment]
You are trying running the example from `master` which may use features that are newer than the latest release (as is the case here). You can either run the examples from a checkout that matches the release, e.g.:

https://github.com/bokeh/bokeh/blob/0.10.0/examples/embed/embed_multiple_responsive.py

or install a dev build to get the latest features:

http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

**Comment by bryevdv** [comment]
@bokeh/dev this seems to be happening with more frequency perhaps it might make sense to inch closer to git workflow, where HEAD `master` is always the latest release and new work is done on a `develop` branch.

**Comment by mattpap** [comment]
@bryevdv, does this happen that often to make devs suffer (I'm pretty sure most of us will make mistakes, by targeting wrong branch, long after this change)?

**Comment by bryevdv** [comment]
That's what I want to have a discussion about. :) According to my memory this is about the tenth time I have seen this "problem" on GH, SO, or the mailing list. I do agree it would impose a burden on developers.

**Comment by mattpap** [comment]
So my general opinion is that packages, installers, web site, etc. are for users' convenience and the repository is for developers' convenience. Thus I'm not completely against having a stable branch and possibly making it the default one, but that decisions regarding this shouldn't come from making the repository more accessible to users. Although I see a point in users choosing github/git to explore examples. I need to give this more thought.

**Comment by bryevdv** [comment]
(re-opening since we are having the discussion here) 

Yes conda ships the example, but using GH is currently pretty much the only option for pip users. Another option would be to move all the examples out into their own repo, and that repo could have `master` always be the latest release.

**Comment by bryevdv** [comment]
There's another one.

**Comment by damianavila** [comment]
>Another option would be to move all the examples out into their own repo, and that repo could have master always be the latest release, and the main repo could stay as-is.

I would go for this option if I have to choose... additionally people can download the examples as zip files from the "releases" in the proposed "example" repo...

**Comment by bryevdv** [comment]
I'm definitely not opposed to splitting the examples and possibly the docs into separate repos. I think we'd have to look into some `git-subtree` (or similar) solution to make things work smoothly for devs and CI testing. It's just going to be some tedious work to make all that happen, though.

**Comment by birdsarah** [comment]
I don't mind either way on splitting it out, but I think having all the examples rendered as part of our docs site would be very useful and would let us point to versioned examples.

I would suggest that sphinx and examples make up docs and are part of the same repo, and because we autogenerate a lot of docs I would lean to keeping everything in one place. 

Discussions on #1032 #1350 #1689 #1892 all relate to this issue.

**Comment by havocp** [comment]
Fixing the `examples` link on http://bokeh.pydata.org/en/latest/docs/gallery.html to be version-locked instead of to master might solve 20% (or 80%, who knows) of this problem.

**Comment by bryevdv** [comment]
That's a great idea I will do that today.

**Comment by mattpap** [comment]
That's a general advice as well. One should always provide github links with a specific version, otherwise they become meaningless very quickly.

**Comment by bryevdv** [comment]
I do try to do that on SO and other places, but if there are links in the current docs that point to master let's find them and fix them.

**Comment by bryevdv** [comment]
`bokeh-tree` and more careful answers seem to have reduced this problem
