### ISSUE TITLE
Installing dev build through pip, receiving standard release instead

### ISSUE THREAD

**Issue by lbrito1** [bokeh/bokeh#3188]
Following suggestions made on #3186, I'm trying to install the developer build following the [FAQ](http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds).

However, executing the pip snippet seems to install the standard release (0.10.0) instead of the developer build (0.11.0, right?):

    uninstalling bokeh (...)
    Proceed (y/n)? y
      Successfully uninstalled bokeh-0.10.0
    lbrito@lbrito:~/Documents/code/snippets$ pip install --pre -i https://pypi.anaconda.org/bokeh/channel/dev/simple bokeh --extra-index-url https://pypi.python.org/simple/
    Collecting bokeh
      Using cached bokeh-0.10.0.tar.gz
    (...)
    Installing collected packages: bokeh
      Running setup.py install for bokeh
    Successfully installed bokeh-0.10.0
    lbrito@lbrito:~/Documents/code/snippets$ pip list | grep bokeh
    bokeh (0.10.0)

What gives?

PS. If GH isn't the appropriate channel for this kind of question, please let me know. I'd be happy to post in the mailing list or wherever is most appropriate.

**Comment by bryevdv** [comment]
@lbrito1 GH is great, thanks!  But this may be an issue with anaconda.org support for pip installs in non-default channels, or it may be an issue with our  projectbuild automation not correctly uploading sdists for dev builds, so it will require some investigation. (Pretty much everyone here uses conda for day-to-day work.)

If you are amenable to using Anaconda/conda, that would be an immediate workaround. 

@damianavila do you offhand if the dev build automation is also supposed to create pip installable packages on the anaconda.org Bokeh dev channel?

**Comment by lbrito1** [comment]
Hi @bryevdv, I actually use conda locally so I'd be open to that, but I'm eventually going to deploy some (Flask) code to Elastic Beanstalk, which expects a (pip-syntax) requirements.txt, hence my interest in using pip commands only.

**Comment by bryevdv** [comment]
@lbrito1 well there will definitely be a pip-installable package on PyPI when we make the full release. It's only the dev builds that we keep on anaconda.org bokeh dev channel (so they don't get accidentally installed).

**Comment by damianavila** [comment]
@bryevdv @lbrito1 we produce a pip installable package for devel builds but for the latest one we hit a bug upstream: https://github.com/bokeh/bokeh/issues/3072

The fix is already on anaconda client but needs to be release. After that, we should have pip installable packages back...

**Comment by bryevdv** [comment]
Works now:
```
$ pip install --pre -i https://pypi.anaconda.org/bokeh/channel/dev/simple bokeh==0.12.0rc5 --extra-index-url https://pypi.python.org/simple/
Collecting bokeh==0.12.0rc5
  Downloading https://pypi.anaconda.org/bokeh/label/dev/simple/bokeh/0.12.0rc5/bokeh-0.12.0rc5.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.6MB 238kB/s 
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /Users/bryan/anaconda/envs/pippip/lib/python3.5/site-packages (from bokeh==0.12.0rc5)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.2.3 in /Users/bryan/anaconda/envs/pippip/lib/python3.5/site-packages (from bokeh==0.12.0rc5)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /Users/bryan/anaconda/envs/pippip/lib/python3.5/site-packages (from bokeh==0.12.0rc5)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.1 in /Users/bryan/anaconda/envs/pippip/lib/python3.5/site-packages (from bokeh==0.12.0rc5)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.7 in /Users/bryan/anaconda/envs/pippip/lib/python3.5/site-packages (from bokeh==0.12.0rc5)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /Users/bryan/anaconda/envs/pippip/lib/python3.5/site-packages (from bokeh==0.12.0rc5)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.3 in /Users/bryan/anaconda/envs/pippip/lib/python3.5/site-packages (from bokeh==0.12.0rc5)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Users/bryan/anaconda/envs/pippip/lib/python3.5/site-packages (from Jinja2>=2.7->bokeh==0.12.0rc5)
Building wheels for collected packages: bokeh
  Running setup.py bdist_wheel for bokeh ... done
  Stored in directory: /Users/bryan/Library/Caches/pip/wheels/ca/bd/ca/60428d81a01350049c5cfa45337be0c9383ad6271bd19b53bf
Successfully built bokeh
Installing collected packages: bokeh
  Found existing installation: bokeh 0.12.0
    Uninstalling bokeh-0.12.0:
      Successfully uninstalled bokeh-0.12.0
Successfully installed bokeh-0.12.0rc5
```
