### ISSUE TITLE
Example-breaking typo in the documentation

### ISSUE THREAD

**Issue by afshin** [bokeh/bokeh#3195]
I’m working off examples and I found a typo in the docs on this page: http://bokeh.pydata.org/en/0.10.0/docs/user_guide/embed.html#autoloading

    from bokeh.plotting import figure, push
    from bokeh.embed import autoload_server
    from bokeh.session import Session
    from bokeh.document import Document
    
    # alternative to these lines, bokeh.io.output_server(...)
    document = Document()
    session = Session()
    session.use_doc('population_reveal')
    session.load_document(document)
    
    plot = figure()
    plot.circle([1,2], [3,4])
    
    document.add(push)
    push(session, document)
    
    script = autoload_server(plot, session)

This code breaks because `document.add(push)` should instead be `document.add(plot)`

**Comment by bryevdv** [comment]
fixed in master
