### ISSUE TITLE
Retitle "Static" descriptor for serverless (server-free) examples

### ISSUE THREAD

**Issue by FirecatSue** [bokeh/bokeh#3196]
![bokeh-gallery-server-free](https://cloud.githubusercontent.com/assets/716256/11411060/27e6dc08-9392-11e5-8873-62b26ad657f8.png)

Suggested by @electronwill

**Comment by electronwill** [comment]
or maybe "All Local" or "Fully Local"

**Comment by electronwill** [comment]
fixed by https://github.com/bokeh/bokeh/pull/3197
