### ISSUE TITLE
legend with axis_label

### ISSUE THREAD

**Issue by jakkubu** [bokeh/bokeh#3199]
Using Bokeh 0.10.0

When using legend with orientation "bottom_right" + axis_labels the legend position seems not to "see" the label. As a consequence the legend is on axis. 
![selection_013](https://cloud.githubusercontent.com/assets/1984569/11423679/bf4259d8-9446-11e5-8844-0dba2e734179.png)

**Comment by mattpap** [comment]
@jakkubu, I wasn't able to reproduce this in bokeh 0.10 and 0.11-dev. Would you mind submitting a snippet of code, showing exactly how you are creating the plot?

**Comment by jakkubu** [comment]
@mattpap I use bokeh with it's server for streaming the data. 

If you add a renderer (eg. p.line) with empty data and then update data the legend will show on axis. The following code will produce such plot. After reloading the page the legend will move to correct spot. In one of my plot it's not correcting itself, but I cannot reproduce it in simple snippet. I'll look into it later.

Simple solution - put random data during renderer creation. 

    from bokeh.plotting import figure, show, push, cursession, output_server
    import time
    import random


    output_server("whatever")
    p = figure(plot_width=800, plot_height=400)

    p.line([], [], name="plot_name", legend="x pos")

    p.xaxis.axis_label = 'x values'
    p.yaxis.axis_label = 'y values'
    p.legend.orientation = "bottom_left"

    show(p)

    renderer = p.select(dict(name="plot_name"))
    data_src = renderer[0].data_source

    time.sleep(5)
    while True:
        data_src.data["x"].append(len(data_src.data["x"]))
        data_src.data["y"].append(random.random())
        cursession().store_objects(data_src)
        time.sleep(.5)

**Comment by bryevdv** [comment]
This has to do with the old `bokeh-server` which is long deprecated and removed. I haven't seen anything like this with recent code but if it can be reproduced with recent versions please open a new issue.
