### ISSUE TITLE
Database or REST based data

### ISSUE THREAD

**Issue by faical-yannick-congo** [bokeh/bokeh#3209]
I am not sure if this is the appropriate media to ask my question. So i apologize if it is not yet it is the one i thought of for now.
I am very new in Bokeh and on the user base side.
Is it possible to have my bokeh apps data not come from a single file or a static link but from a database or/and a REST API implementing dynamic queries of some sort. I want to know if it is already possible and what are the ways to do so before i dive into and mess with bokeh's code.
My application will be using a large set of data. The cross filter is the example i have been using as a test base for bokeh.
I am wondering if i can do it from the user side or if i have to switch to the developer side of bokeh. If you think it is the second and you have a quicker path through how i could solve this let me know. I am currently walking myself though Bokeh source code.
Yannick,
Thanks

**Comment by bryevdv** [comment]
From your description it sounds like you want the `AjaxDataSource`

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/ajax_source.py

**Comment by faical-yannick-congo** [comment]
Thank you very much @bryevdv. I will try this.
