### ISSUE TITLE
Improvements to events

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#3210]
Continuing discussion from https://github.com/bokeh/bokeh/pull/3191#issuecomment-160493686

Bokeh currently has some ways to keep track of changes/events, but its not very much "streamlined". E.g. you cannot let users pick a line without causing the line to be become part of the current selection.

cc @havocp @brendancol

**Comment by almarklein** [comment]
Copying in @havocp's comment:



We could model events as state changes (imagine model fields like latest_event or click_count, then you watch those for change). But that would be awkward, at least if it were the only API - maybe it would be fine on the protocol/implementation level, I don't know.

I don't love the current setup with callback for certain events, because it only works for client-side callbacks. I think it'd be nicer if both Model.on_change and something like Button.on_click existed, and if you passed a Python function to them you got a server callback, and if you passed a JavascriptCallback object to them you got a client callback, or something along those lines. Also we could have a way to compile Python to JS as we do for callback now thanks to Almar.

Some things will not work well if done server side, for example I think if you did any kind of click-and-drag functionality with server side callbacks for the click and drag events, it would probably work poorly. But other things like clicking a button I imagine would work very well with server-side callbacks.

I could imagine a mechanism not unlike properties.py, or maybe part of properties.py, for registering events that a class can generate? It could automatically create a corresponding property which would be the list of client-side callbacks...

Random ideas, all larger in scope than this PR of course.

**Comment by almarklein** [comment]
> We could model events as state changes (imagine model fields like latest_event or click_count, then you watch those for change).

That sounds similar to how I currently do "events" in Flexx, using a Reactive-Programming-like approach. I'm actually starting to think that RP is *not* a very good model for widget systems, especially visualization oriented apps. Here is [my proposal](https://github.com/zoofIO/flexx/issues/60) for changing Flexx' event system. Basically, I want to make things more simple/classical, but keep some of the niceties of the current system, such as the easy way to bind functions to events. It would also mean that Flexx moves from "signals" to properties, which makes me wonder about compatibility with Bokeh ...

> I could imagine a mechanism not unlike properties.py, or maybe part of properties.py, for registering events that a class can generate?

This is very much what I had in mind for Flexx as well. I think that it makes sense that for each property there is a corresponding event that gets fired when that property changes, and that other events can be defined in a similar way.

**Comment by bryevdv** [comment]
This was closed by #5941
