### ISSUE TITLE
Bokeh + IPython widgets: push_notebook() error?

### ISSUE THREAD

**Issue by ericmjl** [bokeh/bokeh#3215]
I have tried following the example provided in [this][1] notebook.

Everything runs correctly until the end, when I try running the interactive widgets. At that point, the browser returns: 

    Javascript error adding output!
    TypeError: ds is undefined
    See your browser Javascript console for more details.

As an alternative example, I tried creating a Button for a coin toss (notebook [here][2]), I found a similar issue.

When I comment out the `push_notebook()` line, the error message goes away. Naturally, though, the data are not updated, and so the plot is not updated either. 

Might this be an error with `push_notebook()`?

[1]: https://github.com/bokeh/bokeh/blob/master/examples/plotting/notebook/interact_basic.ipynb
[2]: https://github.com/ericmjl/systems-microbiology-hiv/blob/master/Bayesian%20Example.ipynb

**Comment by bryevdv** [comment]
I demo this example often, so it will take some investigation to reproduce in order to diagnose what problem you are experiencing. Can you provide information about what versions of bokeh, and ipython you are using? Platform and browser could also be useful.

**Comment by bryevdv** [comment]
Also FWIW `0.11` should have a much improved "notebook sync" functionality that uses Jupyter notebook comms directly.

**Comment by ericmjl** [comment]
Thanks @bryevdv! I'm currently on:

- `bokeh` 0.10.0
- `jupyter` 1.0.0
- `ipython` 4.0.0
- Mac OS X El Capitan 10.11.1
- Jupyter code tested in Firefox and Safari.

**Comment by bryevdv** [comment]
@ericmjl can you confirm if any issue remains with current Bokeh `0.11.1` If so, can you provide a complete minimal test case to reproduce the problem?

**Comment by bryevdv** [comment]
@damianavila I think you are too aggressive at labeling things as "discussion" :) IMO. any console error should automatically be considered a bug.

**Comment by damianavila** [comment]
>@damianavila I think you are too aggressive at labeling things as "discussion" :) IMO. any console error should automatically be considered a bug.

Probably... we probably need to just leave the issues unlabeled until I (or someone else) can assign the proper label... in this case, I did not put the `bug` label because I could not reproduce the issue at that time... but maybe I should be more flexible... I took the note!! There are several tiny problems with the issues and PR management that we need to fix in the future... I am thinking on that :wink:

**Comment by ericmjl** [comment]
hey guys, thanks for coming back to this! 😄 I just tested my [notebook][1] with the `push_notebook` line uncommented, and it works. Thanks! 👍

[1]: https://github.com/ericmjl/systems-microbiology-hiv/blob/master/Bayesian%20Example.ipynb

**Comment by bryevdv** [comment]
Awesome, thanks for letting us know!
