### ISSUE TITLE
Build documentation with canonical links to "latest"

### ISSUE THREAD

**Issue by ahmadia** [bokeh/bokeh#3217]
For example, the first search result here: https://www.google.com/search?q=bokeh+model currently points to http://bokeh.pydata.org/en/0.9.3/docs/reference/models.html instead of the latest version of the documentation.

If we inserted a canonical links to http://bokeh.pydata.org/en/latest/docs/reference/models.html in all versions of the documentation, Google would point to http://bokeh.pydata.org/en/latest/docs/reference/models.html whenever it would normally return a reference to the specific version of the documentation.  

This is extremely helpful if our URL structure is not changing but the interfaces/names of our functions/variables are.

**Comment by birdsarah** [comment]
I'm not completely understanding where these canonical links would get inserted. I think it's good to have version specific links it helps people post to SO etc. Maybe, like on the django docs, we could have a little top banned and an easy version switcher e.g. https://docs.djangoproject.com/en/1.6/topics/db/models/

**Comment by bryevdv** [comment]
@birdsarah my understanding is this is purely to hint to search engine indexers. So they don't e.g., return the `0.9.3` version of the docs for a search for "bokeh models" which is what Google does now.

**Comment by ahmadia** [comment]
Yup, here's a more concrete example:

Here's an example from another project: http://www.mcs.anl.gov/petsc/petsc-3.5.4/docs/manualpages/Sys/PetscInitialize.html

```
<HEAD> <link rel="canonical" href="http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Sys/PetscInitialize.html" />
```

If you search for `PetscInitialize`, you won't get older versions of PETSc documentation, but they're all still there/available.

**Comment by birdsarah** [comment]
Cool - thanks! Sounds like a great idea.

**Comment by bryevdv** [comment]
I'd like do do this sooner rather than later. Sphinx has alot of hooks, so I can vaguely imagine a couple of ways to accomplish this, but if anyone @bokeh/dev already has a concrete suggestion in mind please share it (and help save some investigations)

**Comment by bryevdv** [comment]
It's possible to derive the full benefit, we would also need to re-deploy the old versions with this same change. Can anyone comment?
