### ISSUE TITLE
Sometimes, "hbox1" shows up in the top of the page, sometimes, "hbox2" shows up in the top of the page?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#3221]
Sometimes, "hbox1" shows up in the top of the page, sometimes, "hbox2" shows up in the top of the page?
```
curdoc().add(hbox1)
curdoc().add(hbox2)
```
How to fix the order of "hbox1", "hbox2"?

**Comment by charleywan2004** [comment]
I found out order can be achieved by using VBox
```
vbox=VBox(children=[hbox1, hbox2])
curdoc().add(vbox)
```

**Comment by bryevdv** [comment]
This has been resolved as well, documents are now rendered in the order added.
