### ISSUE TITLE
Callback for switching data sources

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3222]
The gapminder example uses a technique of having a bunch of precomputed data sources and then switching out the data sources based on the slider value. 

It's a pattern I've used other times too.

It requires a bunch of wonky code and some JS knowledge though so thinking it's a good candidate for a pre-baked Callback like OpenUrl.

I can imagine ways this wouldn't be necessary, but I think it's also a fairly intuitive way to work with data (snapshots of a dataframe over time)

**Comment by mattpap** [comment]
This is something I considered for the initial implementation of callbacks. Definitively can be added. If there are other patterns that you considered as well, make sure to point them out in this issue.

**Comment by birdsarah** [comment]
It was a while ago, but other options I remember considering at the time for specific viz:

* squeezing all the data into rows so that you can pick a column name (s) by year e.g. your columns would be `1992_x, 1992_y
* having a main data source and swapping out columns from another source (maybe with some computing on the fly)

What I don't recall is why I these weren't good for me. Although the js is a little wonky, I find conceptually the pattern I have now is simple to reason about. 

But I'd love to hammer this out more if you have more thoughts.

**Comment by bryevdv** [comment]
This should be covered by the generic JS callback PR that was just recently merged, can attach JS callbacks to any property event just as you can with python

**Comment by bryevdv** [comment]
(please re-open if I am somehow mistaken)
