### ISSUE TITLE
Relax NO_GLYPH_RENDERERS validation

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#3223]
Currently `Plot` requires at least one `GlyphRenderer`, but with new additions, i.e. tile renderers, you can get a valid plot without glyph renderers. We have to add one more abstract base class and update `Plot`'s validation. See issue #3189 for details.

**Comment by damianavila** [comment]
This was closed but I am not sure if the validation was "relaxed" as proposed by the first message, can @bryevdv or @mattpap validate what the status of this one? Thanks!

**Comment by bryevdv** [comment]
Yes this was resolved (tile/dynamic map no longer throw validation errors)

**Comment by damianavila** [comment]
>Yes this was resolved (tile/dynamic map no longer throw validation errors)

Thanks!
