### ISSUE TITLE
Embedded chart not showing - Javascript Error

### ISSUE THREAD

**Issue by jdhaines** [bokeh/bokeh#3231]
Never posted an issue before, apologies for not doing this correctly.

I'm trying to show a plot on a hosted web page.  Displaying in an html file works correctly.

I'm getting a javascript error while trying to display the chart.  The error from chrome "inspect" tool is below:  bokeh.js is my file that came from the **autoload_static** python call.   For clarity I've switched away from the minified version.  I'll also put the relevant javascript code for the first two error lines below. 

```javascript
Uncaught TypeError: Cannot read property 'default_view' of undefined
    add_plot_static @ bokeh-0.10.0.js:61201
    inject_plot @ bokeh-0.10.0.js:61259
    (anonymous function) @ bokeh.js:43
    (anonymous function) @ bokeh.js:18
    s.onreadystatechange.s.onload @ bokeh.js:18
```
The error in firefox just says "TypeError: model is undefined"
The error in IE says "Unable to get property 'default_view' of undefined or null reference"  They all reference the same line "61201" in the bokeh-0.10.0.js file.

**add_plot_static**
```javascript
add_plot_static = function(element, model_id, model_type, all_models) {
  var model, view;
  load_models(all_models);
  model = base.Collections(model_type).get(model_id);
  view = new model.default_view({  # this is the marked error line
    model: model
  });
```

**inject_plot**
```javascript
if (info.bokehData === "static") {
    logger.info("  - using static data");
    return add_plot_static(container, info["bokehModelid"], info["bokehModeltype"], all_models);  # this line is called as the error line
```

This is the python script I used to generate the javascript and script call for embedding.
```python
# import csv using pandas
weight_data = pd.read_csv('weight_data.csv', parse_dates=['Date'])

# init output file for bokeh
# output_file('weight.html')

# init the chart, feed datetime axis type
chart = figure(x_axis_type='datetime', title='My Weight', x_axis_label='Date',
               y_axis_label='Weight (lbs)')

# generate the chart with specific details
chart.line(weight_data['Date'], weight_data['Weight'], color='navy',)

js, tag = autoload_static(chart, CDN, "http://www.joshhaines.com/js/bokeh.js")

# write each file
javascript_file = open('bokeh.js', 'w')
javascript_file.write(js)
javascript_file.closed

script_file = open('tag.html', 'w')
script_file.write(tag)
script_file.closed

# exit
```
The script tag it generates (and is plugged into my html file) is:
```html
<script
    src="http://www.joshhaines.com/js/bokeh.js"
    id="51fef957-42b0-4674-9d6b-8fccc28296b6"
    async="true"
    data-bokeh-data="static"
    data-bokeh-modelid="c3c3f62f-38c3-4d88-99d4-a71384422fe6"
    data-bokeh-modeltype="Plot"
    data-bokeh-loglevel="info"
></script>
```

I don't know enough about javascript to even attempt a fix.  Any information would be helpful.  I can't guarantee this is a bokeh problem.  In fact I'd guess it isn't, because embedding a basic line graph is probably a common use-case.  But the error is getting thrown in the bokeh-owned javascript file and my example is mostly copied from the AAPL stock example on the site.  I'll add any additional information needed.

**Comment by birdsarah** [comment]
The way I'm used to getting back the script and div tag for embedding bokeh is with embed.components 

http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#components

I see on the same page of the userguide that autoload_static is documented, unfortunately I haven't tried it. Are you really keen to use autoload_static?

**Comment by jdhaines** [comment]
I'm not set on any specific method of showing.  Changing to the outputs by using components(plot) worked great.  I think I misunderstood the autoload_static requirement.  I was thinking if I didn't want to spin up a local server to see it I'd need to use autoload_static for general hosting.  The components method does exactly what I wanted.

That said, I'm not sure if my initial issue is a bug or something different.  From what I could tell I followed the procedure correctly for using it.  I'll leave it up to someone else to decide whether to pursue the initial issue or not.  My reason for making this "issue" is resolved.  I've still got the initial files if anyone wants me to do further testing to track down the error in the OP.  

Thanks for the recommendation birdsarah!

**Comment by bryevdv** [comment]
Going to go ahead and close this, since the user reported a solution with `components`, additionally every gallery plot relies on `autoload_static` so I am confident that it is working as expected.
