### ISSUE TITLE
Tests for hover glyph

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3233]
I abandoned writing js tests for #3206 - the hover glyph which still need to be done - but the PR needed merging.

**Comment by bryevdv** [comment]
I'm just conceding that this will always come down to manual testing.

**Comment by mattpap** [comment]
> I'm just conceding that this will always come down to manual testing.

Perhaps in some cases, hover we already have a few hover tests, e.g.:
https://github.com/bokeh/bokeh/blob/0195875e331b5d95a387b4174213b2709e69b0e8/bokehjs/test/integration/regressions.ts#L1194
