### ISSUE TITLE
CI Build breakdown

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3236]
Some suggestions:
* JS, docs, and flake tests only need to run once, suggest one py3 test for all three
* Consider python + integration tests could be merged into one build, to share "install" cost. 
* Longest tests (both "examples" builds) should be run first together, so that their start times are not unnecessarily staggered. The current order adds ~5-10 minutes to every full run.

**Comment by bryevdv** [comment]
I'm also wondering about the value of caching. My informal observation is that it seems to be detecting changes and packing/uploading almost all the time, and that takes quite some time. More or less than without, I'm not sure.

**Comment by damianavila** [comment]
> I'm also wondering about the value of caching. My informal observation is that it seems to be detecting changes and packing/uploading almost all the time, and that takes quite some time. More or less than without, I'm not sure.

That's a good observation... I am thinking on that at well... we should time this somehow... I would be open to remove it to check if performs better...
