### ISSUE TITLE
Distinguish between "tight" and "nice fit" bounds policies on ranges

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3239]
Following on a discussion from #3175

From @pzwang:

> What is the way to distinguish between "tight" bounds policy and "nice fit" bounds policy? (Recall that "nice fit" is actually contingent on screen space transforms, because what's nice for a linear scale is not the same as what's nice for a log scale.)

From @birdsarah:

> Good question. Is that something we could address in a follow-on PR? At the moment, I believe this implementation gives you tight.

From @bryevdv:

> Data ranges interrogate renderers for their preferred bounds, so I think its actually the converse. The current behavior is to try and give "nice" bounds. Although, its dependent on the quality of the bounding box returned by the renderer, and not all of them do an equally good job.
> 
> "Strict" bounds is a simple enveloping of all the data in some set of columns in a data source or sources. It's the way column data sources originally behaved, and the reason for hacks like `range_padding`. (Sometimes "range padding" is useful, but it's not sufficient to implement "nice" bounds and thats what it what it was trying to be used for.) This behavior was replaced with the "ask the renderer" behavior some time ago.
> 
> We could certainly add back a range that does simple enveloping, and then maybe an `AutoRange` that has a policy that delegates to one of the specific types (I would not want to dump the strict enveloping code back into the current data range)

**Comment by bryevdv** [comment]
I haven't seen any demand for auto-ranging that is based on simple enveloping. The current data range has range padding which can be eliminated for "tighter" auto bounds (or can now be expressed as an absolute quantity instead of a percentage). I think this is sufficient.
