### ISSUE TITLE
Build new pytest-selenium package

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3243]
pytest-selenium https://github.com/davehunt/pytest-selenium

is now at 1.0 and has a 1.1 coming out shortly, can we build the conda packages and add them to our repo?

ping @damianavila - I'm pinging you as you did this last time, I'm happy to help any way I can.

**Comment by birdsarah** [comment]
ping @damian - can you do this - I have built all these packages and have them on my channel  (http://anaconda.org/birdsarah/packages) - let me know how I can get these onto bokeh's channel.

**Comment by damianavila** [comment]
AFAIK, you can transfer those packages from your channel into the Bokeh one (anaconda.org UI). Alternative, you can directly upload the packages to the bokeh channel.
Maybe the second option is the better one... so the packages are not remove them from your channel.
Ping me if you can't do it and I can build and upload myself... but should be easy for you as well...

**Comment by bryevdv** [comment]
@birdsarah is this done?

**Comment by birdsarah** [comment]
Sorry, yes, just completed this week.
