### ISSUE TITLE
Have Charts initialization parms match Figure initialization parms

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#3244]
Currently there are some initializations parameters you can pass when creating a Figure, such as background_fill_color and toolbar_location, which cause an error when passed when creating a chart, such as a Histogram. It would be easier for new users if the parameters related to the display of the chart that are accepted when creating a Figure would also work when creating a Chart. This would lower the cognitive load when switching between Charts and lower level plotting using Figures.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/28)
