### ISSUE TITLE
Tool icons should have the same dimensions

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#3250]
Currently:

```
BoxSelect.png:     PNG image data, 36 x 32, 8-bit/color RGBA, non-interlaced
BoxZoom.png:       PNG image data, 34 x 32, 8-bit/color RGBA, non-interlaced
Help.png:          PNG image data, 32 x 32, 8-bit/color RGB, non-interlaced
Inspector.png:     PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
LassoSelect.png:   PNG image data, 36 x 32, 8-bit/color RGBA, non-interlaced
Pan.png:           PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
PolygonSelect.png: PNG image data, 36 x 32, 8-bit/color RGBA, non-interlaced
Reset.png:         PNG image data, 40 x 32, 8-bit/color RGBA, non-interlaced
Resize.png:        PNG image data, 34 x 32, 8-bit/color RGBA, non-interlaced
Save.png:          PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
TapSelect.png:     PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
WheelZoom.png:     PNG image data, 44 x 32, 8-bit/color RGBA, non-interlaced
```

btw. Who is responsible for creating new icons, etc., after Lila's departure?

**Comment by bryevdv** [comment]
I think amenity created these. Now, maybe Victoria could help.

**Comment by VelizarVESSELINOV** [comment]
:+1: Any plan to move to vector icons, the current icons very pixelized?
Is it possible to customize or update the icons? The save icon is very old style...

**Comment by bryevdv** [comment]
If you know a visual designer who would want to help contribute to an OSS project, we'd be happy to do all of these things. :)

**Comment by VelizarVESSELINOV** [comment]
I will ask few friends for help, but also it is not so difficult to use basic icon and customize a little bit if needed: http://www.flaticon.com/

**Comment by VelizarVESSELINOV** [comment]
@bryevdv Where are stored all the icons? What it is current process to submit you new icons?

**Comment by canavandl** [comment]
Hi @VelizarVESSELINOV 

The icons are located at https://github.com/bokeh/bokeh/tree/master/sphinx/source/_images/icons (or the ./bokeh/sphinx/source/_images/icons directory of the project). In terms of submitting new icons, you'd have to open a PR where the files have been replaced with new image files.

Thanks again for contributing to the project!

**Comment by timsnyder** [comment]
If a visual designer were interested in working on this, I have a couple of questions that might be helpful for them:
* which size should we standardize on?  I'm assuming that it would be alright to make them all 44x32 or whatever the current largest size is.
* @bryevdv just to be sure, I'm reading [your reply above](https://github.com/bokeh/bokeh/issues/3250#issuecomment-167899286) to mean that you're okay with moving to vector graphics for the icons.  Do you have any thoughts on the format?  I was thinking of trying to be conservative and stick with [SVG1.1](http://caniuse.com/#feat=svg) but I'm not the graphical designer and I admit that I don't know what the best format would be.
* Does bokeh have a design guide?  This might be something that the core team has talked about but if you have anything written or are willing to talk to an artist about your goals, that might be helpful. 
* are their any other source artifacts than the ones checked into bokeh/bokeh?  I would think that there might be versions of the icons that don't have the anti-aliasing filter applied but if we want to move to vector art, I'm not sure that those would be too helpful anyway.
