### ISSUE TITLE
Confusing deprecation message in bokeh/models/plots.py

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#3257]
```
    @property
    def background_fill(self):
        warnings.warn(
            """
            Glyph property 'background_fill' will be deprecated in Bokeh
            0.12.0. Use 'background_fill_color' instead.
            """)
        return self.background_fill_color
```
It's already deprecated, i.e. in 0.11.0, so perhaps someone meant to write "removed". Further more, we have `bokeh.deprecate` module to handle deprecation, yet this uses bare `warnings.warn()`.

**Comment by bryevdv** [comment]
@mattpap agreed the message should be changed. AFAIK `bokeh.deprecated` will not work for our properties? But perhaps it can.

**Comment by mattpap** [comment]
>  AFAIK bokeh.deprecated will not work for our properties? But perhaps it can.

It looks like it doesn't, as visible in #3261, but I will check this out.
