### ISSUE TITLE
Overlapping Hover tooltips

### ISSUE THREAD

**Issue by gmur24** [bokeh/bokeh#3260]
Please assist. I'm having a problem with this. The hover tooltip should only generate one view at a time but it's not the case on the attached file.

 
![image](https://cloud.githubusercontent.com/assets/13022982/11627867/bcd52d98-9d28-11e5-98ea-1cadc00a722d.png)

**Comment by bryevdv** [comment]
@gmur24 as someone else mentioned, the GH tracker is primarily for development, and the Bokeh mailing list is intended for general support. Apart from there being a larger number of people there who could potentially help, keeping support questions there helps us keep out issue tracker under control. The mailing list is here:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
