### ISSUE TITLE
general charts examples improvements

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3270]
Collection of general improvements mentioned on merged PRs:
- [x] Rename `xyvalues` dataset in examples (It looks unusual, we should call these something else, everywhere. Even just generic `data` would be better.)
- [ ] simplify single examples
- [x] replace `OrderectDict`s with `dict`s
- [x] find a better data examples for `step`
- [x] `examples/charts/file/timeseries.py` overlaps with `stocks` example? (if so we should remove these)

**Comment by jbcrail** [comment]
I've started work on the first and third tasks.

**Comment by jbcrail** [comment]
Would this plot be a good replacement for the `step` example?
![postage_rates](https://cloud.githubusercontent.com/assets/6038/11959577/20438a86-a89c-11e5-9013-aa94c58bbe67.png)

**Comment by bryevdv** [comment]
Yes that seems better to me.

**Comment by fpliger** [comment]
> Yes that seems better to me.

+1

**Comment by jbcrail** [comment]
Add to existing #3395, or create new PR?

**Comment by bryevdv** [comment]
Seems to fall under a general charts improvement, here is fine.

**Comment by jbcrail** [comment]
Regarding task 5, `examples/charts/file/stocks_timeseries.py` creates one plot that overlaps with the four in `timeseries.py`, so I'll remove this example.

Also, the `stock_timeseries` example downloads MSFT data, but never plots it. Should I remove the data or add it to the plot?
