### ISSUE TITLE
CI generated documentation should be uploaded to S3

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#3272]
The same as we upload images and test reports. This will be useful to inspect documentation without need to build it locally. Further more, we could upload generated HTML files, conda package etc.

**Comment by bryevdv** [comment]
I don't think this is worth doing, the plots will not function because the `src` URLs for the scripts are like this:
```

<script
  src="/scripts/bokeh-plot-docs-user_guide-quickstart-inline-396b2966729a432fb5ad3714df0b5272.js"
  id="03a211a2-daf3-47e8-a637-137dc092a01c"
  data-bokeh-model-id="4e1322a1-1be5-4661-8322-7b3e34ce2cf2"
  data-bokeh-doc-id="180ccd7a-fb6e-45df-8260-95ef40b1b5f4"
  ></script>
```

and that won't work on S3.
