### ISSUE TITLE
Bokeh Prod issues

### ISSUE THREAD

**Issue by quasiben** [bokeh/bokeh#3275]
Under low stress bokeh server seems to have some protocol handling errors.  Several users reported errors from the console (also nginx) like the following:

### console
```
Bokeh: Unhandled ERROR reply to FA407C214347428090A609FFD122E432: AttributeError("'NoneType' object has no attribute 'value'",)
```

### nginx
```
ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): AttributeError("'NoneType' object has no attribute 'value'",)
DEBUG:bokeh.server.protocol.server_handler:  message header {u'msgid': u'FA407C214347428090A609FFD122E432', u'msgtype': u'PATCH-DOC'} content {u'references': [], u'events': [{u'new': 2.63894, u'kind': u'ModelChanged', u'model': {u'type':
u'Slider', u'id': u'd29d43c1-447a-4c4d-84ad-1d11daff73ce'}, u'attr': u'value'}]}
```

**Comment by bryevdv** [comment]
@havocp so it seems at a glance that looking up the model id in the `PATCH-DOC` returns `None` I'm not sure offhand what might cause that. Crosstalk/contamination between sessions, the ID is getting changed somewhere somehow, the model gets deleted?

**Comment by havocp** [comment]
I was seeing this too. Does it happen if we have only one server instance? One possibility is that we load the html with id's in it from one server, then connect websocket to a different server. But I don't know if that's it.
Our current config has no session affinity.

**Comment by havocp** [comment]
could also be related to disconnection (we have no keep-alive right now, and I'm not sure what nginx does by default)

**Comment by bryevdv** [comment]
I thought of session affinity, so ben restarted with one server and it still seems to be an issue.

**Comment by quasiben** [comment]
I now have it running with 15 -- perhaps swinging in the other direction could help ?

**Comment by quasiben** [comment]
I'm still able to reproduce the bug

**Comment by quasiben** [comment]
heh -- I realized that running n+1 server doesn't make a whole lot of sense if we don't change the port

**Comment by havocp** [comment]
Should be fixed by https://github.com/bokeh/bokeh/pull/3276
