### ISSUE TITLE
Configurable name for app_path / url

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3290]
Sorry if this is a dupe, I briefly searched but couldn't see an issue.

Right now I start bokeh server with different app code `bokeh serve foo.py bar.py fizz.py buzz.py`

Those things will then be served up at http://mybokehserver.com/foo http://mybokehserver.com/bar http://mybokehserver.com/fizz http://mybokehserver.com/buzz

These paths should be configurable.

My suggestion would be that you can do `Document.app_path` to set it.

**Comment by bryevdv** [comment]
There as been no perceptible demand for this so I am going to go ahead an close this discussion.
