### ISSUE TITLE
Add minimal support for data updates on charts

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3293]
This is not supported at all at the moment. The proposal is to support data updates but basically wiping all the renderers and recreating them. Although it's still "expensive" it's still a big win as it would avoid recreating the actual Chart which would avoid recreating the canvas on the JS side and the consequent annoying flickering.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/27)
