### ISSUE TITLE
Zoom Toggle Unselecting on Bokeh Site

### ISSUE THREAD

**Issue by VictoriaODell** [bokeh/bokeh#3298]
Hey, hello

I think the zoom options on the site gallery examples may not be up to date?
[This latest example](http://demo.bokehplots.com/sliders) allows you to unselect the zoom options.
<img width="456" alt="screen shot 2015-12-09 at 4 07 30 pm" src="https://cloud.githubusercontent.com/assets/10767430/11700373/0d794524-9e8f-11e5-9cee-35c2b6f55606.png">

Examples on the site makes you unselect a zoom option by selecting another. So you can't have anything unselected. Example [here](http://bokeh.pydata.org/en/latest/docs/gallery/image_rgba.html)
<img width="293" alt="screen shot 2015-12-09 at 4 07 35 pm" src="https://cloud.githubusercontent.com/assets/10767430/11700383/1532cd3a-9e8f-11e5-80f3-2e5d1521ea67.png">

**Comment by bryevdv** [comment]
@VictoriaODell this is fixed in the new release, I misunderstood your comment, thanks for the observations!
