### ISSUE TITLE
plotting/file/burtin.py has validation warnings

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#3301]
ERROR:/Users/mmari/Desktop/continuum/bokeh/bokeh/validation/check.pyc:E-1000     (COLUMN_LENGTHS): ColumnDataSource column lengths are not all the same: ColumnDataSource,     ViewModel:ColumnDataSource, ref _id: 519b3773-4400-4b9a-af34-a21c8c59882d
    ERROR:/Users/mmari/Desktop/continuum/bokeh/bokeh/validation/check.pyc:E-1000     (COLUMN_LENGTHS): ColumnDataSource column lengths are not all the same: ColumnDataSource,     ViewModel:ColumnDataSource, ref _id: c93293b6-b191-4feb-b21b-11c48dbd68cd

**Comment by bryevdv** [comment]
Fixed in recent work
