### ISSUE TITLE
validation warning for dynamic_map.py

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#3302]
ERROR:/Users/mmari/Desktop/continuum/bokeh/bokeh/validation/check.pyc:W-1001 (NO_GLYPH_RENDERERS): Plot has no glyph renderers: Figure, ViewModel:Plot, ref _id: 2d5c737d-8d7f-4b49-96d1-d75c6fb49d4a

**Comment by brendancol** [comment]
Relax NO_GLYPH_RENDERERS validation #3223: https://github.com/bokeh/bokeh/issues/3223

**Comment by bryevdv** [comment]
This does seem like a duplicate?
