### ISSUE TITLE
Use travis built-in machinery to upload things to s3

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3306]
Currently we use boto to upload test reports to s3.

Travis has a way of handling that for us.

* https://docs.travis-ci.com/user/uploading-artifacts/
* https://blog.travis-ci.com/2012-12-18-travis-artifacts/

```sh
 before_script:
   - "gem install travis-artifacts"
after_test:
  - "travis-artifacts upload --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
```

**Comment by mattpap** [comment]
`tests/travis/test` (originally `examples/test`) was meant to be used on CI (not only travis) and (very importantly) locally (thought this wasn't used much after all). As we plan to migrate to anaconda platform for CI, we shouldn't integrate heavily with travis CI.

**Comment by damianavila** [comment]
> As we plan to migrate to anaconda platform for CI, we shouldn't integrate heavily with travis CI.

:+1:  to this comment...
