### ISSUE TITLE
Legend Update 

### ISSUE THREAD

**Issue by brianpanneton** [bokeh/bokeh#3333]
I'm not sure where to ask this question and/or if it is a bug. 

I am attempting to hack together a streaming pie chart using wedges in 0.10.0. I have the pie chart working where wedges get added/updated.

My figure looks like this:
``` python
        plot = figure(toolbar_location=None,
                      plot_width=800,
                      plot_height=400,
                      title=question,
                      x_range=(-1.5, 3),
                      y_range=(-2, 2),
                      min_border=10,
                      min_border_left=50,
                      title_text_font_size='12pt')
        plot.xaxis.visible = None
        plot.xgrid.grid_line_color = None
        plot.yaxis.visible = None
        plot.ygrid.grid_line_color = None
```

and my update basically does this every few seconds:

``` python
            for i, (key, val) in enumerate(results[question].iteritems()):
                wedge = {}
                wedge['start'] = 2*pi*wedge_sum
                wedge_sum = (val/float(total)) + wedge_sum
                wedge['end'] = 2*pi*wedge_sum
                wedge['name'] = '{:.40} ({:.2f} %)'.format(key, val/float(total))
                wedge['color'] = colors[i%len(colors)]
                wedges.append(wedge)

            data[question[0]]._renderers = []
            for i, wedge in enumerate(wedges):
                data[question[0]].wedge(x=0, y=0, radius=1,
                                           legend=wedge['name'],
                                           start_angle=wedge['start'],
                                           end_angle=wedge['end'],
                                           color=wedge['color'],
                                           line_color='black',
                                           radius_units='data')
            sessions[question[0]].store_objects(data[question[0]])
```

My thought process was to clear all the wedges within the figure and redraw the updates. This part seems to work as I expected. However, once this occurs, the title and legend get redrawn incorrectly. The title disappears and the legend only has one item in it.

If I remove this line:
``` python
            data[question[0]]._renderers = []
```
The title does not disappear and the legend gets updated when new wedges are added. However the legend box size doesn't get updated, so it writes the new wedge label outside of the box.

I'm hoping there is a better way to achieve this. I can't seem to figure out how to access the legend to update it.

**Comment by brianpanneton** [comment]
Oh I also tried just removing the glyph renderers like such with no luck:

``` python
            rends = []
            for rend in data[question[0]]._renderers:
                if isinstance(rend, GlyphRenderer):
                    continue
                rends.append(rend)
            data[question[0]]._renderers = rends

```

**Comment by brianpanneton** [comment]
Is there a mailing list or better place to ask this question?

**Comment by bryevdv** [comment]
Hi @brianpanneton there is a public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

And for general support questions that is probably the best place to go, simply because there are more potential people who can answer questions there. However, I think what you have described is a small bug, either some plumbing that has never really been exercises and is not fully hooked up, or perhaps something that is too easy to misuse and should be warned about. It would help tremendously if you could post a minimal complete code sample to reproduce the issue, that speeds up getting started debugging vastly. 

I will say that everyone is currently entirely focused on specific priorities for the January 0.11 release, so it is unlikely this will get much attention until after that.

**Comment by brianpanneton** [comment]
The example is here:

``` python
import time
from numpy import pi
import random

from bokeh.plotting import figure, output_server, push
from bokeh.embed import autoload_server
from bokeh.session import Session

# Setup Charts
results = {'test1': 10, 'test2': 32, 'test3': 18, 'test4': 144}

session = Session('test', load_from_config=False)
output_server('test', session=session)

plot = None

# create a figure and add a wedge glyph to it
plot = figure(toolbar_location=None,
              plot_width=800,
              plot_height=400,
              title='test title',
              x_range=(-1.5, 3),
              y_range=(-2, 2),
              min_border=10,
              min_border_left=50,
              title_text_font_size='12pt')
plot.xaxis.visible = None
plot.xgrid.grid_line_color = None
plot.yaxis.visible = None
plot.ygrid.grid_line_color = None

push()
script = autoload_server(plot, session=session, public=True)
with open('bokeh_pie.html', 'w') as of:
      of.write("<html><head><title>Test</title></head><body>\n")
      of.write('<link href="http://cdn.pydata.org/bokeh/release/bokeh-0.10.0.min.css" rel="stylesheet" type="text/css">\n')
      of.write('<script src="http://cdn.pydata.org/bokeh/release/bokeh-0.10.0.min.js"></script>\n')
      of.write(script+'\n')
      of.write('</body></html>')
while True:
    total = sum(results.values())
    colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']
    wedges = []
    wedge_sum = 0
    for i, (key, val) in enumerate(results.iteritems()):
        wedge = {}
        wedge['start'] = 2*pi*wedge_sum
        wedge_sum = (val/float(total)) + wedge_sum
        wedge['end'] = 2*pi*wedge_sum
        wedge['name'] = '{:.40} ({:.2f} %)'.format(key, val/float(total))
        wedge['color'] = colors[i%len(colors)]
        wedges.append(wedge)

    plot._renderers = []

    for i, wedge in enumerate(wedges):
        plot.wedge(x=0, y=0, radius=1,
                   legend=wedge['name'],
                   start_angle=wedge['start'],
                   end_angle=wedge['end'],
                   color=wedge['color'],
                   line_color='black',
                   radius_units='data')
    plot.legend.glyph_width = 10
    #print 'after', data[question[0]].__dict__
    session.store_objects(plot)

    time.sleep(10)
    # change results
    for key in results:
        results[key] = random.randint(0, 100)
    print results
```

To run do the following (probably in 3 separate terminals):

1) bokeh-server 
2) python bokeh_pie.py
3) python -m SimpleHTTPServer 1234

Then open firefox and go to the bokeh_pie.html page. On initial load, everything looks correct. After 10 seconds it gets updated and the legend and title get screwed up. I have found out that if I refresh the page it gets corrected until the next update.

If you could point me in the correct direction to where the issue may be I can look into it.

**Comment by bryevdv** [comment]
This issue refers to the old `bokeh-server` which has been deprecated and entirely removed. The second generation bokeh server, i.e. `bokeh serve` is drastically better on all counts, and has much more accumulated usage and community knowledge.
