### ISSUE TITLE
Investigate better implementation for toolbar rendering 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3340]
issues: ref #3334

**Comment by birdsarah** [comment]
Can we put all of the `render` code into `initialize` which would make it clear that this only happens once. Or is the ordering of `initialize` vs `render` important?

**Comment by bryevdv** [comment]
Ostensibly we want to support updating the toolbar if the set of tools changes. I think that just means putting the render code in a method named something other than `render` and then that new method can be called from `initialize` and also set as the mode change callback.

**Comment by mattpap** [comment]
In the new layout everything is rendered only once per full layout update (first layout and every layout invalidation). Currently `render()` must not be called from `initialize()`.

**Comment by mattpap** [comment]
> Ostensibly we want to support updating the toolbar if the set of tools changes.

bokehjs in general needs to respect updates more, so this will be done together in one chunk of work.
