### ISSUE TITLE
Server mode that requires session ID to be provided

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3343]
In a configuration where some "gateway" app creates session IDs then redirects to bokeh server, we don't want bokeh server to generate session IDs itself. Right now I think we only generate a session ID in one place (in doc_handler.py). So there should be a way to turn this off, and if you don't pass in a valid session ID you would get an error page.

Questions:
 * what is this command line option called? `--disable-session-id-generation` ? It's a very lowlevel kind of option I think, and not blindingly obvious how to use it.
 * what is the error code? does it attempt to show a user-friendly-ish error page, or even a customizable one?

I was trying to think about whether we can do something higher level than the three options (this one and the two added in https://github.com/bokeh/bokeh/pull/3325 ):
 * `BOKEH_SECRET_KEY` (should maybe be available as `--secret-key` too)
 * `BOKEH_SIGN_SESSIONS` (should maybe be `--sign-sessions` too)
 * `--disable-session-id-generation`

Some combinations of these definitely don't make sense; for example, `--disable-session-id-generation` requires the other two to be enabled. So perhaps it could auto-enable the other two (more accurately, auto-enable `--sign-sessions` and complain if no secret key is set).

Secret key can make sense without signed sessions, because we could use it for other purposes; it's used for the fallback RNG generator if you don't have SecureRandom, already, for example.

Attempting to enumerate the sensible configurations:
 1. secret key only (nothing special with session ids but have a secret for other purposes)
 2. all three (session ids have to come from a "gateway" app in front of the bokeh server)
 3. secret key and signed sessions = True, disable id generation = False (when you want to prohibit made-up session names but do want to allow directly loading the app on bokeh server without a gateway)

So maybe the deal is:
 * secret key is a separate option
 * if you turn on signed sessions, it's an error if secret key isn't set
 * if you turn on `--disable-session-id-generation` it auto-enables signed sessions and it's an error if secret key isn't set

If those are the three cases, maybe we could call the option `--third-party-signs-sessions` or something like that instead of `--disable-session-id-generation`. But hard to come up with a name I love.

**Comment by bryevdv** [comment]
How about `--external-session-signing`

or

`--session-signing=internal|external|off`

to cover both the last options at once.

**Comment by havocp** [comment]
Could be good. More precisely it's something like `internal-and-external|external|off` I suppose (there's no way to disable external, as long as external has the key). `auto|external|off` ? ...
