### ISSUE TITLE
Larger color ranges (particularly gray scale)

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#3347]
Often I find myself using `bokeh` to plot some sort of image and overlay it with annotations. To do a reasonable job showing a grayscale image, I would really like to use more than a handful. I have tried using 256 grays, but this still feels limiting. Is there some possibility to have larger color ranges in `bokeh`? If there isn't some way to do this currently, what would be required to have this feature at some point?

**Comment by bryevdv** [comment]
@canavandl we coudl add a `grays` function similar to `viridis(...)` etc.

**Comment by bryevdv** [comment]
@HuntJSparra can you look at making a PR for this?

**Comment by HuntJSparra** [comment]
@jakirkham 
Any color ranges in particular you wanted? I am working to add functions similar to `viridis`, but was curious which palettes would be most useful to a user such as yourself.

Also, regarding the grays, I added the function for them, but only 256 can be displayed due to both hexadecimals just not having the precision for more than 256 and computers not being able to display more than 256 different shades of gray. Larger color ranges are possible with functions such as `magma` and should be with even simple color functions such as (working on it) `blues`.

**Comment by jakirkham** [comment]
> Any color ranges in particular you wanted? I am working to add functions similar to `viridis`, but was curious which palettes would be most useful to a user such as yourself.

I have been using `viridis` with `matplotlib` for some things lately and do like it. Though I must have missed that addition to `bokeh`. Are there some docs or examples I should look at for this functionality? Basically, color ranges that appear perceptually linear are great (the more the merrier). Glad to hear there are some options in that domain.

I often find myself wanting to indicate objects (via polygons or contours) in a larger image. So, having a perceptually linear color scheme for the larger image and having some more discretized color scheme for the objects (so overlaps or neighbors are easily distinguishable) is great.

> Also, regarding the grays, I added the function for them, but only 256 can be displayed due to both hexadecimals just not having the precision for more than 256 and computers not being able to display more than 256 different shades of gray. Larger color ranges are possible with functions such as magma and should be with even simple color functions such as (working on it) blues.

Yeah, I had a function like this that I was using locally (had another dependency). I'm glad there will be one in Bokeh proper. Though, I agree that 256 grays is pretty limiting. Perceptually linear color ranges can take longer paths and thus have more variety. So, that has been what I have tended towards of late.

I'm trying to place my finger on what it is that bothers me about the current grayscale representation (admittedly what I'm using is of my own construction). If I had to say, it is probably due to the fact that grayscale itself is not perceptually linear. Maybe having a luminance preserving conversion from something else that is perceptually linear like `viridis` to `gray` would be helpful. I know there would be some information loss in this conversion, but I think it would probably be better than handling the gray range linearly.

**Comment by HuntJSparra** [comment]
> Are there some docs or examples I should look at for this functionality? 

http://bokeh.pydata.org/en/latest/docs/reference/palettes.html has all palettes and related functions. Although, those functions are sort of hidden at the bottom of the page.

**Comment by jakirkham** [comment]
Ah, indeed, looks like the docs have been updated in the last day too. Thanks for the link.

**Comment by leopd** [comment]
I came here wanting color palettes larger than 256.  I wrote this simple workaround.  It's not perfect (doesn't do any interpolation between entries in the base palette) but works well enough.

```
def big_palette(size, palette_func):
    if size < 256:
        return palette_func(size)
    p = palette_func(256)
    out = []
    for i in range(size):
        idx = int(i * 256.0 / size)
        out.append(p[idx])
    return out
```

use like:

```
my_palette = big_palette(len(df),bokeh.palettes.plasma)
```
