### ISSUE TITLE
Session / Document vars

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3349]
Following on from discussion on #3279 

Background: Let's say I have an app that looks like: 

``` python
# foo.py
doc = curdoc()

params = dict(userid=None, params=None, auth_token=None)

def update_me():
    data = do_a_rest_call(params)
    source.data = data

doc.add_periodic_callback(update_me, 100)
```

What I want to do in the code that's going to work with this doc is pass in my new params.

Previously I have been able to set data by doing `pull_session`, then `session.document.get_model_by_name('source')` which returns my source and then I can update the source. Now I could make params a ColumnDataSource just to make this work, but that seems a little silly when I just want to be able to pass in some arbitrary object.  

from @havocp 

> You could probably make a custom model to hold the info, but that is ugly and I'd have to go figure out what it looks like (though @brendancol has been doing it a lot lately and may know right away). I think this is why Bryan wants to add Document.vars which would be a Dict(String,Any) auto-synced between client and server for exactly these kind of quick little pieces of data. Not sure there's a good answer right now.
> 
> I guess here you'd want them synced between your Django app (which is a client of bokeh server) and bokeh server, but not between the browser (which is also a client of bokeh server) and bokeh server.
> 
> That could get weird.
> 
> First brainstorm idea: some kind of "session create vars" that are available during the initial session creation script here, but not synced with the Document itself. Would presumably be passed to pull_session or push_session.

Actually what I want, in this particular case, is "session vars" - that is I set them up once when I call `pull_session` in my django code. However, I also need those vars to be available to the bokeh app code. And in my bokeh app code I can only reference `curdoc` so I'm completely open to them not necessarily being on the session.

**Comment by havocp** [comment]
If we implemented the hooks in https://github.com/bokeh/bokeh/wiki/Server-lifecycle-hooks , the session create hook could have access to some sort of session create vars (possibly just the query params from the request that results in creating the session ... )

However, something I don't have in that hooks idea is a way for the hooks to inject stuff into the main bokeh app script.

possibly the "session context object" and/or "application context object" could be available as global functions much like `curdoc()` or something like that. In that case wouldn't need the hooks at all for this use-case, just access to the "session context object" which would have some kind of session vars on it...

**Comment by birdsarah** [comment]
To see the motivating example in action, checkout:
* https://github.com/bokeh/bokeh-demos/blob/ca219a39aa015fd6db4849561c52955ec14e4d5c/happiness/happiness/views.py#L33
* https://github.com/bokeh/bokeh-demos/blob/ca219a39aa015fd6db4849561c52955ec14e4d5c/happiness/viz/individual.py#L38

In individual.py (the bokeh app) we have to:
* setup a ColumnDataSource
* add it to the document
* and then get the desired value out of the data source in my callback
In views.py (the web app) I have to:
* get my data source by name
* set data against it, making sure to use the correct dict key

I'm thinking it'll be as simple to spell as:
```python
# bokeh app
doc = curdoc()
doc.session_context['employee_id'] = -1  # Placeholder to get started

# web app
bokeh_session = pull_session
bokeh_session.context['employee_id'] = 6
```
Trying to incorporate @havocp's idea of a session context. If it was just a dictionary session_context then you wouldn't even need to set it up in the document, you could just try and use it if it's available.

**Comment by sima-jether** [comment]
Hello,
I'm new to bokeh and  and came across this issue when i searched a way to save information per document in an embedded bokeh server i use.
I'm currently implementing the solution presented in the happiness example, and saving the document's information that i need in a ColumnDataSource (in a dict), that i add to the root of the document.
The problem with this solution is that it causes the following error in the browser side: "Error rendering Bokeh items TypeError: t.default_view is not a constructor". Can i add the ColumnDataSource in a different way to avoid the error? is there another workaround/solution to saving document instance information?
I apologize in advance if it's not the right place to ask.

**Comment by bryevdv** [comment]
@mattpap I can confirm that 
```
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

source = ColumnDataSource()

plot = figure()
plot.circle([1,2,3], [4,5,6])

curdoc().add_root(plot)
curdoc().add_root(source)
```
on current master results in the message:
```
Error rendering Bokeh items  – TypeError: undefined is not a constructor (evaluating 'new t.default_view({model:t,parent:null})')
```
I thought there was a filter on roots now, and views were only constructed for "layoutables" ?

**Comment by bryevdv** [comment]
@sima-jether until this feature is finished, an option for including a "dummy" CDS without a warning would be to attach an invisible glyph and use its data source.

**Comment by sima-jether** [comment]
I'll do that, thanks!

**Comment by bryevdv** [comment]
I think this is ultimately the same goal as #3674, though perhaps spelled differently. I think making the synced object re-use existing machinery is better than making some new code path so closing this in deference to #3674
