### ISSUE TITLE
XSLT for JSON

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#335]
Hear me out.  I'm building a tool for displaying multiple glyphs on the same plot.  Some of the plots are related hierarchy.  There has to be a better way to specify glyphs

So for this set of columns
```
['category1', ['itemA', 'itemB', 'itemC'],
 'category2', ['itemA', 'itemB', 'itemC']]
```
I want every glyph for category1 to be red, and I want every itemA to have a triangle glyph, every itemB to have a circle glyph, and every itemC to have a rectangle.  How can I specify this succintly?

I think XSLT did things like this for xml.  What do you think?

I think this will come up frequently as people build things with Bokeh.  I currently need to solve this problem in JS, but it will come up in python too.

**Comment by bryevdv** [comment]
See #1515
