### ISSUE TITLE
Enable autoload_server from a static page

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3355]
Right now it isn't possible to autoload_server from a static page because every user would end up with the same session id (it's embedded in the autoload_server output).

 * first merge https://github.com/bokeh/bokeh/pull/3325
 * in _templates/autoload_js.js, add a session_id template parameter, and place it in render_items next to elementid
 * in _templates/autoload_tag.html remove the sessionid
 * in bokehjs/src/coffee/common/embed.coffee, rather than pulling the session id off the script tag, pull it from the render item
 * in embed.py, add a `?bokeh-session-id` query parameter if session_id passed in is not None, and leave this param out otherwise. Do not pass sessionid to the autoload_tag template.
 * in server/views/autoload_js_handler.py, copy the session id parameter handling from server/views/doc_handler.py so we gen a session id server side if needed and pass it to the autoload_js.js template.

Tricky part: _SessionCoordinates will autogenerate a sessionid client side if session_id is None, and we often "forward" this session id to other functions. We may want to try to generate the session id at the "last possible moment" so that when possible we can leave it for the server to generate. This could be done by making _SessionCoordinates store whether session_id was originally None, and if it is, it would only generate a session ID lazily when session_id property is accessed. We could then add a different property session_id_can_be_none or something, and when we pass the session id from _SessionCoordinates to another function, if the function accepts None, pass it session_id_can_be_none instead of session_id.

**Comment by birdsarah** [comment]
Thanks for writing this up @havocp havoc we have a couple of sites that want this feature.
