### ISSUE TITLE
New defaults in Bar Chart

### ISSUE THREAD

**Issue by aneeshvartakavi** [bokeh/bokeh#3357]
Previous versions of Bokeh would allow the plotting of a bar chart (using the high level interface) in the same order as the rows in the DataFrame. v0.10 appears to introduce automatic sorting on the labels. It would be nice to allow the user the option of turning off this default behavior.

It would also be nice if the agg function could accept `None` to just plot a Bar Chart without aggregation.

![bokeh label sorting](https://cloud.githubusercontent.com/assets/4122476/11852284/e7417734-a3eb-11e5-97b7-4314233a34db.png)

**Comment by bryevdv** [comment]
@fpliger is this still an issue?

**Comment by bryevdv** [comment]
closing as `bokeh.charts` has be moved to a separate project

**Comment by fpliger** [comment]
Jeez.... somehow embarassed I missed your question @bryevdv ... Sorry :)
