### ISSUE TITLE
Taylor Server demo needs .client

### ISSUE THREAD

**Issue by redraven984** [bokeh/bokeh#3359]
I would like to learn how to develop apps with Bokeh. I downloaded taylor_server.py and attempted to run it.

It looks like bokeh.client is only included in version 0.11, I have 0.10.

I downloaded the dev version as per the documentation but I dont know how to start the bokeh-server.  Please let me know how to do this. Also, please direct me to any tutorials there may be. it doesnt look like the documentation on interacting with the server and running background code is complete online.

**Comment by bryevdv** [comment]
HI @redraven984 you are correct that `bokeh.client` is a new feature of the upcoming `0.11` release. There are two options:

* It's possible to download pre-release "dev builds" very easily, see:

   http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

* Alternatively, you can find the version of the example matched to your specific Bokeh install, e.g.:

    https://github.com/bokeh/bokeh/tree/0.10.0/examples/app

**Comment by redraven984** [comment]
Thanks Bryan. Can you also help me with finding a little bit more of the documentation?

Im reading here, and Ive watched your youtube videos:
http://bokeh.pydata.org/en/latest/docs/user_guide/server.html

But the last few sections that I need arent there yet:

Downsampling with Server
Reacting to User Interactions
Building Bokeh Applications
Deploying for Production

Is there any place I can find these or should I just look through taylor_server for an example?

**Comment by brendancol** [comment]
@redraven984 this another good example which may help: https://github.com/bokeh/bokeh/tree/master/examples/app/stocks

**Comment by bryevdv** [comment]
Hi @redraven984 That link is to the docs of the latest release, which did not have the new server. We are still working hard to compose the Bokeh server documentation, and have it ready for the release on January 6th.  There is some initial documentation on the dev deploy of the docs, which is at 

http://bokeh.pydata.org/en/dev/docs/user_guide/cli.html

I hope to have more available for a new dev build next week. Right now for Bokeh server apps, the best resource is probably to learn by example/imitation, as @brendancol mentioned there are examples at 

https://github.com/bokeh/bokeh/tree/master/examples/app

Expect much more by the `0.11` release, however

**Comment by redraven984** [comment]
Thanks Bryan. Im looking forward to the release. Ill look through the examples too before then. Is there a good forum to ask questions? Its not appropriate to put it in issues.

**Comment by bryevdv** [comment]
Absolutely! The public mailing list is here:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
