### ISSUE TITLE
Opening same session of sliders example in two tabs breaks

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3361]
* be sure you have the fix in https://github.com/bokeh/bokeh/pull/3356 so the error fixed there won't confuse the issue
* Run `bokeh serve examples/app/sliders.py`
* Open two tabs to `http://localhost:5006/sliders?bokeh-session-id=foo` (so they have the same session)
* it is not necessary to interact with the app in any way

It is not typical to use the same session in two tabs, but in some local-notebook kind of scenarios we might do the equivalent, and in any case if our code is correct this should work.

The errors look like:

```
DEBUG:bokeh.server.session:Sending pull-doc-reply from session 'foo'
ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): RuntimeError('Cannot apply patch to Span-108FAC630C8C4966B57ABC4D2A36DD8D which is not in the document',)
DEBUG:bokeh.server.protocol.server_handler:  message header {'msgid': 'D2F4C9324B2747FC9A4006260D55EED6', 'msgtype': 'PATCH-DOC'} content {'references': [], 'events': [{'new': 'canvas', 'attr': 'render_mode', 'kind': 'ModelChanged', 'model': {'type': 'Span', 'id': 'Span-108FAC630C8C4966B57ABC4D2A36DD8D'}}]}
Traceback (most recent call last):
  File "/home/hp/checkout/bokeh/bokeh/server/protocol/server_handler.py", line 38, in handle
    work = yield handler(message, connection)
  File "/home/hp/bin/Anaconda-2.2.0/envs/py3/lib/python3.4/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/hp/bin/Anaconda-2.2.0/envs/py3/lib/python3.4/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/hp/bin/Anaconda-2.2.0/envs/py3/lib/python3.4/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/home/hp/checkout/bokeh/bokeh/server/session.py", line 36, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/home/hp/checkout/bokeh/bokeh/server/session.py", line 255, in _handle_patch
    message.apply_to_document(self.document)
  File "/home/hp/checkout/bokeh/bokeh/server/protocol/messages/patch_doc.py", line 80, in apply_to_document
    doc.apply_json_patch(self.content)
  File "/home/hp/checkout/bokeh/bokeh/document.py", line 682, in apply_json_patch
    raise RuntimeError("Cannot apply patch to %s which is not in the document" % (str(patched_id)))
RuntimeError: Cannot apply patch to Span-108FAC630C8C4966B57ABC4D2A36DD8D which is not in the document
```

**Comment by havocp** [comment]
The problem here appears to be that CrosshairTool unconditionally sets `spans` property during initialization, ignoring any `spans` property that may have been provided to its constructor: https://github.com/bokeh/bokeh/blob/c4a5a5b61a13437a2f8bd86ff7d6f61328a89e77/bokehjs/src/coffee/tool/inspectors/crosshair_tool.coffee#L45-L62

Because `spans` is a client-only property, we don't propagate the new spans models to the server, so the other sessions have never heard of them.

It's really a bug anytime the client modifies the document it was sent just purely as a side effect of constructing the client models/views, but we try to work around it here:
https://github.com/bokeh/bokeh/blob/c4a5a5b61a13437a2f8bd86ff7d6f61328a89e77/bokehjs/src/coffee/common/client.coffee#L232-L235

And we try to avoid sending client-only attributes here:
https://github.com/bokeh/bokeh/blob/c4a5a5b61a13437a2f8bd86ff7d6f61328a89e77/bokehjs/src/coffee/common/document.coffee#L319-L320

But, I _think_ the issue is that we fail to handle attributes of models that are not reachable from the server because the model itself is the value of a client-only attribute. In other words, we need to be sure the server will have a non-client-only attribute it can use to get to the model, before we send any events from that model.

If that's the issue, the errors here may be relatively harmless other than the errors thrown because the server is just getting change events on a model it doesn't care about. However one way it could break things is if we send multiple events in that initial PATCH-DOC we could drop events after the problem ones.
(initial patch-doc = https://github.com/bokeh/bokeh/blob/c4a5a5b61a13437a2f8bd86ff7d6f61328a89e77/bokehjs/src/coffee/common/client.coffee#L234-L235 )

We could fix this whole class of errors by not sending events from models the server can't see; but it may be hard to figure out which models those are. We could fix this specific error perhaps by just moving "spans" to the view or something.

**Comment by bryevdv** [comment]
> We could fix this whole class of errors by not sending events from models the server can't see; but it may be hard to figure out which models those are.

Or by having the models be sent, instead of doing any of this client side initialization of instances, which is the approach I had planned to pursue.

**Comment by havocp** [comment]
Agreed, ultimately the ideal would be to drop all that code computing initialize-generated events and instead just make it an error if those events occur. But could take quite some time to get there.

prioritizing removal of client-only models might make sense, vs client only props that are just plain values. i.e. try to reach a point where all models are in the document.

**Comment by bryevdv** [comment]
I could be mistaken, I think there are only 3-4 places. Spans, tickers, tooltips and maybe formatters.

**Comment by havocp** [comment]
This may be fixed now due to @bryevdv 's recent work, but we'd have to test it.

**Comment by fpliger** [comment]
@havocp this seems to still be broken.. I get a `TypeError: Cannot read property 'add_edit_variable' of undefined` on the JS console.

**Comment by havocp** [comment]
it looks like Bryan fixed the original error here but now there's a new one. Bryan says that error also happens if you just press reload on a non-bokeh-serve app (one of the output_server examples).

**Comment by havocp** [comment]
fwiw, I'm still getting the original error here, not the "cannot read property"

**Comment by havocp** [comment]
nevermind - I was using old minified JS files. I do get the new error now.

**Comment by havocp** [comment]
the immediate issue here is that we serialize all the LayoutBox attached to Plot, but we don't serialize the solver on each one; we then deserialize them without a solver, which throws an error. That's relatively easy to fix, but harder is that when Plot loads up later it already has LayoutBox that were serialized, but it creates a bunch of new ones anyway.

I'm working on rearranging Plot and LayoutBox to fix this.

**Comment by bryevdv** [comment]
Yah all that is a mess, after `0.11` I look forward to splitting `Plot` up into manageable, testable pieces (it actually used to be ~2x as big, tho, if you can believe it...)

**Comment by havocp** [comment]
I put a fix on https://github.com/bokeh/bokeh/pull/3472 but it just re-exposes the original error :-) so I will work on that one next. The PR doesn't close this bug but does make progress.

**Comment by havocp** [comment]
My original discussion of CrosshairTool was a bit wrong. `spans` is client-only, but the spans are placed in `plot.renderers` which is not client-only, and that's what creates confusion.

The bug I'd expect isn't quite what we see here... I'd expect that we'd see the spans from all tabs in every tab. However, we don't, instead the tabs don't know about spans from other tabs. That may mean there's a bug where we don't find the new spans in our "json diff" algorithm, or something, I'll have to investigate that.

As far as a fix - one approach would be to have separate spans for every tab, they would all be in all the tabs' renderers but perhaps that's ok. Another approach would be to find existing spans in the renderers if they are present and re-use them, so we'd share the crosshair spans across tabs (and I guess as you moused along, all the tabs would stay in sync).

This whole situation should hopefully not happen often in practice, though - normally two tabs each have their own session.

Unlike the Plot/LayoutBox problem, this one doesn't happen on reload - I think because the unloaded previous tab contents won't be sending any change events on the old crosshair spans, and this error is only on change events.

**Comment by bryevdv** [comment]
So all of these things works for me with this PR: 
* reload `plotting/server` example
* navigate away and back to `plotting/server` example
* crosshair tool on server `hover.py` (no console or browser errors)

If I have missed something please re-open

**Comment by bryevdv** [comment]
Realized this is a separate issue.
