### ISSUE TITLE
Improve model documentation

### ISSUE THREAD

**Issue by stefanseefeld** [bokeh/bokeh#3363]
Most DataSource classes have no or only very rudimentary documentation. For example, `ColumnDataSource` (most frequently used in examples) has this:

```
"Maps names of columns to sequences or arrays."
```

which is not very helpful to understand what this class is or does. Its base class (`DataSource`) has:

```
"A base class for data source types. DataSource is not generally useful to instantiate on its own."
```

which isn't helping either. What I'm looking for is some information about the concept of "DataSource", and how to use it (i.e., the "programming paradigm"). I get some idea by browsing the code, but "read the code" isn't really a good substitute for documentation... :-)

It would be great to fill in some of the holes between the very high-level (http://bokeh.pydata.org/en/latest/docs/user_guide/concepts.html) and the low-level API reference.

**Comment by bryevdv** [comment]
> "Maps names of columns to sequences or arrays."

I guess the issue is find ways to describe what this class is *done with*. Because that's literally almost all and exactly what it does, itself: It's basically window dressing around: `dict(str, array)`

**Comment by stefanseefeld** [comment]
Fair enough. The most valuable (missing) information is how any of those source classes are used, the glyph constructors (which aren't documented), or the Plot.add_glyph() method (which only very minimally documents the `source` argument with

    "a data source for the glyphs to all use"

(from http://bokeh.pydata.org/en/latest/docs/reference/models/plots.html#bokeh.models.plots.Plot).
It's hard to learn how to use any of these entities from reading the docs. I think an introductory tutorial that explains the programming model with a few simple examples would go a long way.

**Comment by bryevdv** [comment]
There is now an entire Users Guide section on data sources 

https://bokeh.pydata.org/en/latest/docs/user_guide/data.html
