### ISSUE TITLE
Bokeh Line chart not plotting complete pandas dataframe

### ISSUE THREAD

**Issue by laperk01** [bokeh/bokeh#3371]
I was linked here after I made a post on stackoverflow (http://stackoverflow.com/q/34335393/3012235).

I'm not sure if this is an issue because charts are currently being updated in Bokeh but I can no longer plot a complete dataframe using Line charts from Bokeh in my Jupyter notebook. Using this example from the docs:

    from collections import OrderedDict
    import numpy as np
    import pandas as pd
    from bokeh.charts import Line
    from bokeh.plotting import show, output_file
    from bokeh.charts import Chart, Line
    xyvalues = OrderedDict(
        python=[2, 3, 7, 5, 26, 221, 44, 233, 254, 265, 266, 267, 120, 111],
        pypy=[12, 33, 47, 15, 126, 121, 144, 233, 254, 225, 226, 267, 110, 130],
        jython=[22, 43, 10, 25, 26, 101, 114, 203, 194, 215, 201, 227, 139, 160],
    )

    # any of the following commented are valid Line inputs
    xyvalues = pd.DataFrame(xyvalues)
    #xyvalues = xyvalues.values()
    #xyvalues = np.array(xyvalues.values())

    output_file("lines.html", title="line.py example")
    chart = Line(xyvalues, title="Lines", ylabel='measures', legend=True)
    show(chart)

I get the following output which is clearly different to the example shown in the docs.
![line_chart_problem](https://cloud.githubusercontent.com/assets/5999823/11887065/8b847884-a584-11e5-87ad-9d6bbd4cda4d.png)

If I explicitly give the dataframe an index and pass all the columns like below then it gives the expected plot:

    xyvalues = pd.DataFrame(xyvalues, index=range(14))

    output_file("lines.html", title="line.py example")
    chart = Line(xyvalues, y=['python', 'pypy', 'jython'],
                 title="Lines", ylabel='measures', legend=True)
    show(chart)

My notebook specs:
>You are using Jupyter notebook.

>The version of the notebook server is 4.0.6 and is running on: Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec 6 2015, 18:08:32) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

>IPython 4.0.1 -- An enhanced Interactive Python.
>Bokeh version 0.10.0
>Chrome Version 47.0.2526.106 (64-bit)

This is my first bug report and I'm not really a developer so please be nice. :) I tried to determine my bokeh version using `python -c "import bokeh; print(bokeh.print_versions())"` but I got an attribute error in my terminal.
>Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>AttributeError: 'module' object has no attribute 'print_versions'

**Comment by brendancol** [comment]
My guess is that your issue would go away with updating to the current master branch. 0.11
<img width="637" alt="screen shot 2015-12-17 at 10 08 11 pm" src="https://cloud.githubusercontent.com/assets/433221/11889114/f8cf9970-a50a-11e5-9e34-fe6838a2d708.png">

**Comment by laperk01** [comment]
@brendancol Thanks, I upgraded to the 0.11.0dev4 through conda and its fixed now.
