### ISSUE TITLE
Improve charts create_tools

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3384]
Related suggestions:

This might be a clearer logic:

```
if len(self.tools) == 0:

    # if no tools customization let's create the default tools
    if tools is True:
        tools = DEFAULT_TOOLS
    elif tools is False:
        tools = []

    tool_objs = _process_tools_arg(self, tools)
    self.add_tools(*tool_objs)
```

Also "Only adds tools if given boolean and does not already have tools added to self." seems a bit obscure and complicated. 

Also this should be a private method as it's not intended for users to use..

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/25)
