### ISSUE TITLE
`Property.__delete__` does not send a change notification

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3386]
We support "revert to default" with `del model.prop` but it won't change-notify I don't thinK:
https://github.com/bokeh/bokeh/blob/0c5bb0039b2505d09f9d5360eff861ba466db85c/bokeh/core/properties.py#L464-L466

The needed code would be similar to the stuff in `apply_theme` I think, plus the fix should come with tests.
https://github.com/bokeh/bokeh/blob/0c5bb0039b2505d09f9d5360eff861ba466db85c/bokeh/core/properties.py#L874-L877

**Comment by bryevdv** [comment]
FYI new code location is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/core/property/descriptors.py#L497-L508
