### ISSUE TITLE
ok to add to cdnjs.cloudflare.com?

### ISSUE THREAD

**Issue by shapiromatron** [bokeh/bokeh#3397]
I'm interested in submitting a PR to https://github.com/cdnjs/cdnjs to add bokeh v 0.10.0 to their library; the rest of my site is loading from there and it's very quick. 

Is it ok for me to submit a PR?  I know right now the library is hosted on cdn.pydata.org; ok to put on cloudflare?

**Comment by bryevdv** [comment]
ping @damianavila @bokeh/core

**Comment by damianavila** [comment]
I think it would be nice to have some other sources for our js and css, but I would leave that to the users... I mean, I would not be opposed to also have them in some other place, but we (bokeh) should keep deploying into one "official" and standard place: cdn.pydata.org

**Comment by bryevdv** [comment]
That's pretty much my opinion too.

**Comment by shapiromatron** [comment]
Great; I'll go ahead and submit a PR then. Makes sense to have it hosted in different places as needed. Thanks!

**Comment by bryevdv** [comment]
Just FYI `0.11` will be available on January 6th as well.

**Comment by shapiromatron** [comment]
FYI: https://cdnjs.com/libraries/bokeh

**Comment by damianavila** [comment]
You missed some others: 

bokeh-widgets:

 * https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.0.js
 * https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.0.min.js
 * https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.0.css
 * https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.0.min.css

and the bokeh compiler:

* https://cdn.pydata.org/bokeh/release/bokeh-compiler-0.11.0.js
* https://cdn.pydata.org/bokeh/release/bokeh-compiler-0.11.0.min.js

**Comment by shapiromatron** [comment]
Sorry, missed these. Are they documented anywhere? I tried searching the docs and didn't find anything...

**Comment by damianavila** [comment]
> Sorry, missed these. Are they documented anywhere? I tried searching the docs and didn't find anything...

No problem, they were recently introduced... I am not sure there is a reference in the docs... any help with that is appreciated :wink:
