### ISSUE TITLE
Specify Histogram Bins - Feature Request

### ISSUE THREAD

**Issue by seanlaw** [bokeh/bokeh#3398]
I have a list of Pandas dataframes stored in dfs and I am plotting a grid (three columns) of histograms: 

```
hists = [Histogram(dfs[colname], 
           title=colname, 
           bins=20, 
          ) for colname in dfs.columns]
for h in hists:
    h.x_range = Range1d(-20, 20)
ncol = 3
hists = [hists[i:i+ncol] for i in range(0,len(hists),ncol)]
p = gridplot(hists)
```

However, I've noticed that while the number of bins (20) are the same in all of the plots, the width and location of each bin is inconsistent from plot to plot. I believe this is because each plot has a different x_range and the bins are generated using some optimized method. Instead, I'd like to be able to specify the width and location of each bin, maybe in the form of a list of tuples or something:

bins = [(-20, -15), (-15, -10), (-10, -5), (-5, 0), (0, 5), (5, 10), (10, 15), (15, 20)]  

Also, notice that I've set my x_range to (-20, 20) so I know my min/max are from all of the plots.

**Comment by rothnic** [comment]
The binning when specifying the number of bins is using the same function when you don't. The calculation that produces an optimum bin size is only executed if the number of bins is not provided, in which case it calculates a bin width and uses that to produce the number of bins.

For the case of inputting the number of bins, all that is happening is it produces a bin width based on the range of values provided to the chart. So, the only case where you'd get the same size is if each dataframe has the same min and max value.

So, we'd probably want to take a look at pandas.cut(), which is being used for the binning to see how you'd do what you want to do. The challenge gets into data that falls at the boundaries and how to handle it. Which bin would -15 go into? So, we'd need to say it is left or right include. But then, what if you have -20 and 20 in the data.  

The other option you mention of providing a bin width might be fairly easy, but as you mention, we'd need some way to specify where they are aligned to.

**Comment by rothnic** [comment]
Here is what pandas cut says for the bins input:

bins : int or sequence of scalars
If bins is an int, it defines the number of equal-width bins in the range of x. However, in this case, the range of x is extended by .1% on each side to include the min or max values of x. If bins is a sequence it defines the bin edges allowing for non-uniform bin width. No extension of the range of x is done in this case.

**Comment by papajohn** [comment]
If the `bins` argument of `charts.Histogram` accepted either an `int` or a sequence of scalars, its interface would be consistent with `pandas.cut` and `np.histogram`.

**Comment by kobejohn** [comment]
I generally prefer to see more detail where the detail is (the current optimized binning system) but here is a fixed-width use-case I ran into:

When multiple or stacked charts are used, variable binning can make comparison more difficult. Especially when presented to people who aren't accustomed to it, the difference in bin width and especially overlap of bins can distract from the information you want to present as they puzzle over why they are different.

**Comment by ndawe** [comment]
Disappointed to see I can't manually specify the binning with Bokeh yet (same with plot.ly). I want to show a histogram with a logarithmic x-axis but make the bins visually the same width. I could accomplish this if only I could specify the binning with a logspace array...

**Comment by ndawe** [comment]
Instead of what @seanlaw suggested above, just allow ``bins`` to be an array of the bin edges (no need for the list of tuples)

**Comment by bryevdv** [comment]
@ndawe the very small core team is stretched very thin at the moment. This would make a great task for a new contributor, and that would honestly be the fastest route to have this happen.  If you'd like to make a first PR to Bokeh we are always happy to answer questions and offer guidance.

**Comment by ndawe** [comment]
@bryevdv I'm definitely tempted

**Comment by bryevdv** [comment]
Awesome! when you're ready just let me know and I will write up some pointers and places to start looking at

**Comment by ndawe** [comment]
I'm ready to get started on this. Some pointers will be helpful. Thanks!

**Comment by bryevdv** [comment]
Hi @ndawe that's great. I was looking into the source code to try ro provide some guidance, and I noticed this. While the docstring for the `Histogram` function says this:

>       bins (int, optional): the number of bins to use. Defaults to None to auto select.

The actual undlerlying  property for the `HistogramBuilder` is this:

>     bins = Either(List(Float), Int, default=None, help="""
    If bins is an int, it defines the number of equal-width bins in the
    given range. If bins is a sequence, it defines the
    bin edges, including the rightmost edge, allowing for non-uniform
    bin widths.

Which seems to indicate that it might already possible to pass a lists of bin edges to define the bins.  A little more poking around shows that the `HistogramGlyph` appears to pass `bins` as-is to the `Histogram` stat here:

https://github.com/bokeh/bokeh/blob/master/bokeh/charts/glyphs.py#L964

which in turn seems to just use the value as-is in `np.histogram` here:

https://github.com/bokeh/bokeh/blob/master/bokeh/charts/stats.py#L428

Are we certain this is not already supported?  I guess the first step is actually to investigate whether the docstring is simply wrong.

**Comment by ndawe** [comment]
What about the javascript API?

**Comment by ndawe** [comment]
(going to try anyway now...)

**Comment by ndawe** [comment]
I confirm that bins can be a list of edges on the python side and it functions correctly

**Comment by bryevdv** [comment]
@ndawe well that's a pleasant surprise, would you mind making the (much smaller) PR to update that erroneously narrow docstring?

**Comment by bryevdv** [comment]
I'm going to close this and refer to it in the "collect small docs fixes" issue.
