### ISSUE TITLE
ToDos for new docs

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3404]
Docs site has had an overhaul #3389 (also #3403 and #3402). There will be some ToDos to get everyone happy with the new version. Lets collect them here:

Functional important
- [x] Search is broken
- [x] collapsible code block for the json prototypes is busted (e.g. http://bokeh.pydata.org/en/test/docs/reference/models/glyphs.html) - should be collapsed by default and then expand on click
- [x] decide what to do with blank pages: releases, dev_guide

Functional could wait
- [x] top left bokeh link should go back to bokehplots.com
- [x] when bokehplots.com is finalized, copy over the new footer

Functional - needs clarification:
- [ ] I think the refguide needs to be more expanded navigation too

Styling important
- [x] nested uls not rendering correctly - http://bokeh.pydata.org/en/test/docs/user_guide/tools.html
- [x] there are several horizontal scrollbar over the site (where it should not be)
- [x] narrower/lighter color bar for note/warning, less heavy weight in general / the Note is also awfully heavy. Maybe a narrower color bar and lighter bg grey (or none)
- [x] Return Type should not wrap
- [x] increase visibility of h2
Styling could wait (already a problem on bokeh.pydata.org)
- [x] remove background text color for inline code /  inline "code" is way too heavy, I'm not sure I like a bg fill for the text at all (no background - plum foreground)
- [x] method/attr/function descriptions indented or remarked 
- [x] not shown here, but I think in a page full of functions/methods, it is really hard to tell where one stops and the next starts. I'd almost like the entire description indented a bit underneath, e.g. "autoload_server"
- [x] At a certain heading level, things begin to be right aligned, which to me is less readable.

Small tweaks:
- [x] bad bullets on dev_guide/notes
- [x] bad ref in dev_guide/bindings
- [x] over formatting in dev_guide/bindings
- [x] reference/models/tiles the urls look wierd and one is misspelt
- [x ] reference/sphinxext.html bad bullets
- [x] tweak envars
- [x] remove hr in sphinxext

Missing content problems:
- [ ] "to be addeds" on dev_guide/notes
- [ ] empty pages (or nearly empty):
 - [ ] http://bokeh.pydata.org/en/dev/docs/user_guide/server.html
 - [ ] http://bokeh.pydata.org/en/dev/docs/reference/client.html
 - [ ] http://bokeh.pydata.org/en/dev/docs/reference/util.html 
 - [ ] http://bokeh.pydata.org/en/dev/docs/reference/tile_providers.html
 - [ ] http://bokeh.pydata.org/en/dev/docs/reference/themes.html
 - [ ] http://bokeh.pydata.org/en/dev/docs/reference/settings.html
 - [ ] http://bokeh.pydata.org/en/dev/docs/reference/server.html
 - [ ] http://bokeh.pydata.org/en/dev/docs/reference/mpl.html
- [x] blank home pages (my suggestion is that the top link actually takes you to the first page of content - except for reference which I think should have a cover page explaining what the reference guide is for) :
 - [x] docs/releases.html
 - [x] docs/dev_guide.html
 - [x] docs/reference.html
- [ ] /user_guide/cli.html - remove mention of things not yet implemented!

Misc:
- [x] gallery has empty left menu
- [x] gaps on home page images
- [x] check return_type on bokeh docstring vs bokeh.charts.Area return_type
- [ ] left collapse docs menu
- [x] migration note and docstring about @mattpap's changes to resources
- [x] user_guide/charts.html bad bullets

Broken plots:
- [x] user_guide/geo.html broken
- [x] user_guide/interaction.html - CustomJS with a Python function example is broken - needs to be built with python 3

Questions:
- [x] what do we want the drop down options to be
- [ ] what do we want the search facets to be (can be changed after final deploy)
- [ ] reference/core just has a bunch of stuff: "Enumeration....." is that right?
- [x] references/models/map_plots MapOptions missing JSON prototype

Can wait:
- [ ] search bar on search page to match
- [ ] display searched for text in search bar
- [ ] use responsive plots
- [ ] userguide/tutorials is undewhelming (and wierd after learning more)

Other:
- [x] add a site verification so we can submit requests for indexing on release - otherwise we're waiting for google to catch up
- [ ] can we have the first tab just be a search of latest? (we may just have to make our own tabs and multiple search engines for this)
- [x] note I've taken /en/dev/ out of the search results
- [x] migration note and docstring about @mattpap's changes to resources

**Comment by birdsarah** [comment]
From @bryevdv:
- [ ] I think the refguide needs to be more expanded navigation too
- [ ] collapsible code block for the json prototypes is busted

**Comment by birdsarah** [comment]
@bryevdv, 

> I think the refguide needs to be more expanded navigation too

also my note "decide what to do with blank page" 

Can we kill two birds with one stone and put a deeply expanded Table of Contents here: http://bokeh.pydata.org/en/test/docs/reference.html and then leave the side bar more collapsed?

**Comment by birdsarah** [comment]
- [ ] nested uls not rendering correctly - http://bokeh.pydata.org/en/test/docs/user_guide/tools.html

**Comment by birdsarah** [comment]
- [ ] Search is broken

**Comment by damianavila** [comment]
- [ ] there are several horizontal scrollbar over the site (where it should not be)

Using Chromium Version 47.0.2526.73 Ubuntu 15.04 (64-bit)

**Comment by birdsarah** [comment]
from @bryevdv 

- [ ] inline "code" is way too heavy, I'm not sure I like a bg fill for the text at all
- [ ] the Note is also awfully heavy. Maybe a narrower color bar and lighter bg grey (or none)
- [ ] Return Type should not wrap
- [ ] not shown here, but I think in a page full of functions/methods, it is really hard to tell where one stops and the ncxt starts. I'd almost like the entire description indented a bit underneath, e.g. "autoload_server"

**Comment by bryevdv** [comment]
The return type is evidently fixed in the standalone sphinx napoleon package. Also I added these bullets to the other issue?

**Comment by birdsarah** [comment]
what other issue?

**Comment by bryevdv** [comment]
oh, nm I meant at the top. On my phone I thought it was a brand new issue

**Comment by rothnic** [comment]
Here is what I notice:

- At a certain heading level, things begin to be right aligned, which to me is less readable.

![image](https://cloud.githubusercontent.com/assets/452052/12094971/65d60706-b2d1-11e5-8536-fae5bac93301.png)

- Napoleon sphinx extension needs to be used directly (see issue #2984). I am working on this. This fixes some returns formatting (see screenshot in issue).

**Comment by birdsarah** [comment]
@bokeh/dev There are lots of things that could be improved with the styling for the docs. However, I'd like to limit the scope of the feedback on this issue.

The docs got a makeover to bring them in line with bokehplots.com in doing so, I broke some things e.g. collapsible code blocks for bokehjs, horizontal scroll bars all over the place. 

This issue is about making sure the docs have come up to date with the bokehplots.com styling and haven't degraded from previous experience. I'd like to punt other changes to perhaps a more thoughtful / cohesive styling overhaul.

**Comment by damianavila** [comment]
>  I'd like to punt other changes to perhaps a more thoughtful / cohesive styling overhaul.

:+1:

**Comment by birdsarah** [comment]
The styling fixes that are marked as done have been pushed & deployed via commits to http://github.com/bokeh/bokehplots.com

**Comment by bryevdv** [comment]
>  I'd like to punt other changes to perhaps a more thoughtful / cohesive styling overhaul.

I'm OK with this in general with maybe one exception the background text color on inline code is incredibly bad. I use inline code all the time, so pages look like distractingly cluttered everywhere.

**Comment by birdsarah** [comment]
> I'm OK with this in general with maybe one exception the background text color on inline code is incredibly bad. I use inline code all the time, so pages look like distractingly cluttered everywhere.

OK, but I want to know exactly what you want it to be like, because I don't have a good solution: If you're not careful it looks too like the paragraph but just slightly odd. So I'm not sure what to do.

**Comment by bryevdv** [comment]
Oh, not the paragraphs. The inline code in the middle of sentences  E.g

Foo bar ``some code`` Vaz quux

**Comment by birdsarah** [comment]
More things:
* use responsive plots
* left collapse docs menu
* bad bullets on dev_guide/notes
* to be addeds on dev_guide/notes
* bad ref in dev_guide/bindings
* over formatting in dev_guide/bindings
* check return_type on bokeh docstring vs bokeh.charts.Area return_type
* reference/core just has a bunch of stuff: "Enumeration....." is that right?
* references/models/map_plots MapOptions missing JSON prototype
* reference/models/tiles the urls look wierd and one is misspelt
* reference/sphinxext.html bad bullets
* blank home pages:
 * http://localhost:5009/en/latest/docs/releases.html
 * 
* empty pages (or nearly empty):
 * http://bokeh.pydata.org/en/dev/docs/user_guide/server.html
 * http://bokeh.pydata.org/en/dev/docs/reference/client.html
 * http://bokeh.pydata.org/en/dev/docs/reference/util.html 
 * http://bokeh.pydata.org/en/dev/docs/reference/tile_providers.html
 * http://bokeh.pydata.org/en/dev/docs/reference/themes.html
 * http://bokeh.pydata.org/en/dev/docs/reference/settings.html
 * http://bokeh.pydata.org/en/dev/docs/reference/server.html
 * http://bokeh.pydata.org/en/dev/docs/reference/mpl.html
* what do we want the drop down options to be
* what do we want the search facets to be (can be changed after final deploy)
* gallery has empty left menu
* gaps on home page images
* userguide/tutorials is undewhelming (and wierd after learning more)
* user_guide/geo.html broken
* /user_guide/cli.html - remove mention of things not yet implemented!
* user_guide/interaction.html - CustomJS with a Python function example is broken - needs to be built with python 3
* ~~user_guide/charts.html bad bullets ~~

**Comment by birdsarah** [comment]
random to dos
* migration note and docstring about @mattpap's changes to resources
* consider removing gapminder notebook (keeps getting out of sync)

**Comment by birdsarah** [comment]
Why is bokeh.command not in reference?

**Comment by bryevdv** [comment]
Possibly an oversight, though the docstrings are written extensively and discursively, so they are the primary source for the user guide. Putting it in the ref guide would be a straight duplication. It's also nothing anyone would ever import from directly for any reason whatsoever.

**Comment by birdsarah** [comment]
fair enough - i just went looking because i was trying to find out how serve worked. I perceive "reference" as more authoritative.

**Comment by bryevdv** [comment]
I'd be inclined to add a reference for the command line command, as opposed to `bokeh.command`

**Comment by birdsarah** [comment]
- add a site verification so we can submit requests for indexing on release - otherwise we're waiting for google to catch up
- can we have the first tab just be a search of latest?

**Comment by damianavila** [comment]
@birdsarah can you create a new issue with the remaining tasks for the future (you don't need to write everything again, you can link the comments on this thread containing the tasks). If possible, I would like to have this issue closed as part of 0.11.0 release. Thanks!

**Comment by birdsarah** [comment]
@damianavila - yes I'll do that - thanks!
