### ISSUE TITLE
Pass palette or list of colors to hover_fill_color

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3405]
I want to be able to do the following, so that when I hover over an item, it just makes the same color but darker:

``` python
p = figure(tools='hover')
p.circle(
    x=[1, 2, 3, 4],
    y=[2, 4, 5, 6],
    fill_color=Spectral4, line_color=None, fill_alpha=0.6,
    hover_fill_color=Spectral4, hover_line_color=None, hover_fill_alpha=0.9,
)
```

Unfortunately this doesn't work, I get the error:  

```
File "~/bokeh/bokeh/bokeh/core/properties.py", line 1273, in validate
    raise ValueError("expected an element of either %s, got %r" % (nice_join(self.type_params), value))
ValueError: expected an element of either String, Dict(String, Either(String, Color)) or Color, got ['#2b83ba', '#abdda4', '#fdae61', '#d7191c']
```

**Comment by bryevdv** [comment]
I don't that's feasible without client side color mapping. The alternative is huge amount of data duplication between selected/nonselected/hover glyphs

**Comment by bryevdv** [comment]
Though, if you want to accomplish this: put the colors in a column of a data source and pass the field name for `flil_color` and `hover_fill_color`.

**Comment by birdsarah** [comment]
> I don't that's feasible without client side color mapping. 

@bryevdv - I don't get it

> Though, if you want to accomplish this: put the colors in a column of a data source and pass the field name for flil_color and hover_fill_color.

Right so:

This works, but my hovered circles are pink:

```
p = figure(tools='hover')
p.circle(
    x=[1, 2, 3, 4],  y=[2, 4, 5, 6], radius=0.5,
    fill_color=Spectral4, line_color=None, fill_alpha=0.6,
    hover_fill_color='pink', hover_line_color=None, hover_fill_alpha=0.1,
)
show(p)
```

This does exactly what I want, but I have to manually set up a ColumnDataSource:

```
p = figure(tools='hover')
source = ColumnDataSource( {
        'x': [1, 2, 3, 4],  'y': [2, 4, 5, 6],  'color': Spectral4,
})
p.circle(
    source=source
    x='x',  y='y', radius=0.5,
    fill_color='color', line_color=None, fill_alpha=0.5,
    hover_fill_color='color', hover_line_color=None, hover_fill_alpha=0.9,
)
show(p)
```

But this doesn't work:

```python
p = figure(tools='hover')
p.circle(
    x=[1, 2, 3, 4],  y=[2, 4, 5, 6], radius=0.5,
    fill_color=Spectral4, line_color=None, fill_alpha=0.6,
    hover_fill_color=Spectral4, hover_line_color=None, hover_fill_alpha=0.1,
)
show(p)
```

I agree that there would be data duplication because I'm asking you to create two columns for me that contain the `Spectral4` data - and if there was a performance issue I could manually create the ColumnDataSource and de-dupe the data. But in terms of API intuition, I expect the last example to work.

**Comment by bryevdv** [comment]
I don't think I am up to typing what would be very long discussion, maybe we can have a call?

**Comment by birdsarah** [comment]
Sure, there's no rush though, i just had missed your earlier responses and so was jotting down some notes.

I'm glad there is a way to make this work (by using ColumnDataSource) and I changed it from bug to feature, because clearly this is not a bug, the existing behavior is what you intended - even if I don't like it!

**Comment by bryevdv** [comment]
Tho for a short answer, the last example does not work because the glyph functions do not automatically create data source column for those extra fields, AFAIK but I suppose we could make it do so.

**Comment by birdsarah** [comment]
> the glyph functions do not automatically create data source column for those extra fields....but I suppose we could make it do so. 

I would propose we do it, but it's not high priority.

**Comment by bryevdv** [comment]
Noting that I believe now one could set `CustomJSTransforms` as the values. Those could e.g. apply a "darkening" or "lightening" transform to another existing column. It might be nice to package those up in some subclasses or something.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this. I think the proper solution is to use the shared CDS and I also think that using a CDS is much more familiar and well-socialized among Bokeh users than it was in 2016
