### ISSUE TITLE
Add support for persistent selection overlays

### ISSUE THREAD

**Issue by brittainhard** [bokeh/bokeh#3412]
Currently, when you select an area with the lasso tool, and release the mouse button, the dotted line area disappears. An option to keep the lasso outline visible might be a nice feature.

**Comment by bryevdv** [comment]
The main issue is to make sure that the persistent polygon overlay stays correctly positioned when the plot is panned and zoomed, etc. It may currently be the case that the mouse event screen coordinates are used directly to position the overlay. If so, would need to convert to data space as the intermediate "saved" coordinates.

**Comment by brittainhard** [comment]
Making progress on this. Current solution is to add a listener to PolyAnnotation to see when the underlying data changes, and then update the underlying data based on the data space.

**Comment by brittainhard** [comment]
@bryevdv , just giving you an update on my progress with this issue.

So my approach to this issue has been to keep the overlay visible rather than removing it when the panning is completed in [`_pan_end`](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/gestures/lasso_select_tool.coffee#L45-49), or when a different tool is selected and the [`_active_change`](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/gestures/lasso_select_tool.coffee#L14-16) callback runs. This is done when those functions call [`_clear_overlay`](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/gestures/lasso_select_tool.coffee#L51-52).

The interesting part is that [`render`](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/poly_annotation.coffee#L15-49) on [`PolyAnnotation`](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/poly_annotation.coffee#L7) is constantly updating the screen with new coordinates for the position of the overlay, which has the effect of keeping the overlay centered. Also, when the overlay is cleared in [`LassoSelectToolView`](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/gestures/lasso_select_tool.coffee#L7), [`PolyAnnotation`](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/poly_annotation.coffee#L7) is destroyed, but when the overlay persists, it remains instantiated.

Regardless, I hope to have a few commits and a PR up soon. Just wanted to give you an update on how things are going.

**Comment by bryevdv** [comment]
There has not been any wider interest expressed for this in 4 years so closing now
