### ISSUE TITLE
Band fill color issue display

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#3434]
There is some precision glitch with bottom band that is not displayed
![bokeh_fill_error](https://cloud.githubusercontent.com/assets/8209940/12029697/28eca1e0-ada6-11e5-99c5-950a699ea1b1.png)

```
"""Plot with Bokeh."""
from bokeh.plotting import figure, show
from bokeh.models import DataRange1d

yr = DataRange1d(start=0, end=20)

p = figure(y_range=yr)

p.circle(5, 5)

p.ygrid.band_fill_color = "green"
p.ygrid.band_fill_alpha = 0.1

show(p)

```

**Comment by bryevdv** [comment]
Thanks for the report! Hopefully this will be a simple fix.

**Comment by bryevdv** [comment]
One issue is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/grids/grid.coffee#L163-L164

Where extremal (max/min) range values are excluded. However just changing that (perhaps only in certain cases) would not solve the problem. A better solution is probably to update the function that draws grid bands:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/grids/grid.coffee#L25-L36

to always draw one more band (extending to the edge of the plot, whatever that is) after the loop, if the last region was a non-band region.

**Comment by MulticastMatt** [comment]
Sarah - javascript unit tests, want to have time to write them.  It's on the view, not on the model.  This isn't a Selenium test, it's a javascript test.  

Bryan - love to have a Selenium test too.
