### ISSUE TITLE
Hover tool improvements with multiple lines

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#3435]
<img width="225" alt="tooltipoverlap" src="https://cloud.githubusercontent.com/assets/8209940/12031691/007f4a6e-adc4-11e5-97f0-d69d856dce5d.png">

One of the main issues is the overlap between two tooltips, I don't have issue to have more than one tooltips, but I would like if possible to be positioned smartly in the empty space not one over another.
The second issue is that I didn't find option to access the line legend to know which line tooltip I'm reading.
If possible, I would like to access the line_color as well as it is available on the legend (label and line_color).
Another need is to access to the [x/y]_axis_label. For me it will be better tooltip default will be something like this:

```
hover.tooltips = [
    ('%if @legend', "@legend"),  # condition test if present...
    ('@x_axis_label', "@x"),
    ('@y_axis_label', "@y")
]
```
Last question: I'm not able to find how to enter a space character between the label and the value. As you can see on the last row the label is touching the value.

In my plot I'm using code similar to this:
```
p = figure(x_axis_label='Time ({})'.format(unit_x), y_axis_label='Depth ({}).format(unit_y))

for well in range(...):
     p.line(well_x, well_y, legend=well_name, line_color=well_color)
```

**Comment by bryevdv** [comment]
Hi @VelizarVESSELINOV I believe this is covered by #1512, so I am marking it as a dupe. It's one of the things I'd like to look at soon after `0.11`
