### ISSUE TITLE
Multiple series tooltips: not working example on StackOverFlow

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#3454]
As you can see the example is not working anymore from the comments.

http://stackoverflow.com/questions/27545842/hovertool-for-multiple-data-series-in-bokeh-scatter-plot

I got the same issue trying to use tooltips per line/scatter:
AttributeError: 'generator' object has no attribute 'tooltips'

Please provide proper guideline how to use hover for multiple series.

**Comment by bryevdv** [comment]
I've updated the response. The short answer is that we got repeated requests for `fig.circle(...)` to return the glyph renderer instead of returning the figure, so that change was made last year. The hover tool is on the figure, which is why searching for (now on the glyph renderer) did not find anything. The error message could be improved, however, so I am marking this issue a `bug` to improve the messaging.

**Comment by VelizarVESSELINOV** [comment]
Thank you for edits, now I managed to make it work for each ```p.line()```.

But as a consequence, I have new challenges:
<img width="182" alt="overhover" src="https://cloud.githubusercontent.com/assets/8209940/12066862/f1be8238-afa3-11e5-944a-494734e92a1f.png">

Any option to define a proper **name** for each HoverTool?

Today my code is sequential, but I'm planning to move to parallel insert of ```p.line()``` (I hope Bokeh is thread safe), any option to define the display **order** in the long list in the toolbar or in the legend box?

**UX** suggestion to be able to switch on/off all the hovers with one click and potentially add option for advanced users to select individual hovers to switch on/off, like Office is handling borders: http://www.excel-exercice.com/wp-content/uploads/2011/06/3D_Borders.png

**Comment by bryevdv** [comment]
@VelizarVESSELINOV First thanks for all your detailed feedback an suggestions. A question: do you have a different set of tooltips for each line? Or do you want individual control per line? If neither of those, you can also just make one tooltip that will interrogate all the renderers at once. 

Adding a name is a great idea, it will require a little new development. Can you make a separate feature request to cover enhancements to hover tool handing in the toolbar?

Also please be advised we are in the middle of a freeze for `0.11` and everyone is working furiously on docs and examples so there will likely not be movement on this until mid January.

**Comment by VelizarVESSELINOV** [comment]
As you can see the tooltip is almost the same, except legend and line_color that change for each object:

```
for number in range(10000):
    name = object_name(number)
    df = load_data(name)
    color = smart_color(number)

    l = p.line(df[x], df[y], legend=name, line_color=color)

    p.add_tools(HoverTool(renderers=[l], tooltips=[
        ('Name', name),
        ('Color', '<div id="rectangle" style="width: 12px; height: 12px; '
                  'margin-left: 5px; margin-right: 5px; '
                  'outline: #dddddd solid 1px; display: inline-block; '
                  'background-color:{}">'.format(color)),
        (x_label, "@x"),
        (y_label, "@y{int}")
    ]))
```

I would like to have single tooltip and be able to use ```@legend``` and ```@line_color```.

I will open another ticket specific of management of multi hover tools.

And I saw on you website very interesting functionality in 0.11dev7 for more interactive applications.

**Comment by mbhall88** [comment]
It would make sense to just allow for reference the `name` attribute in line?

Then you could just do

```
for number in range(10000):
    name = object_name(number)
    df = load_data(name)
    color = smart_color(number)

    l = p.line(df[x], df[y], legend=name, line_color=color, name=name)

    p.add_tools(HoverTool(tooltips=[
        ('Name', '$name'),
        ('Color', '<span class="bk-tooltip-color-block" '
                  'style="background-color:{}"> </span>'.format(color)),
        (x_label, "@x"),
        (y_label, "@y{int}")
    ]))
```

**Comment by bryevdv** [comment]
That would be great actually. Would you be interested in working up a PR yourself?

**Comment by mbhall88** [comment]
@bryevdv  I would love to help out. Although I wouldn't know where to start as I haven't worked on big production packages before and I must admit I don't know what you mean by PR? Happy to learn though if you don't mind pointing me in the right direction. Feel free to continue conversation via email if you want (or another means that is more convenient).

**Comment by bryevdv** [comment]
The `$name` special variable was added in `0.13.0`, so I am going to close this.
