### ISSUE TITLE
Named vars that could be used js side

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3455]
We've talking in #3349 about named vars on the document on the python side.

For testing it would be great if I could name something like the plot and have easy access to it JS side to get its attributes out for testing.

**Comment by havocp** [comment]
Do you mean a Dict(String,Any) that's synced with the client side, or a way to get a model by name?

Right now you can do `anymodel.document.get_model_by_name(name)` if you have access to any model in the document, for the latter.

**Comment by birdsarah** [comment]
@havoc - does that work in JS? How do I access the model? via `Bokeh.index`?

**Comment by havocp** [comment]
indeed, right now it's hard to get at models unless you're in a JSCallback, #3700 proposes fixing that

**Comment by mattpap** [comment]
Though this is an earlier issue, I will mark it as a duplicate of #3674, because it has more content and is being worked on in PR #6340.
