### ISSUE TITLE
maps_cities.py data disappears after pan/zoom

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3464]
ping @almarklein 

Other WebGL examples work fine. 

Could consider a *very* short self-contained fix for `0.11`

```
examples/glyphs/maps_cities.py:
 data disappears after pan/zoom
```

**Comment by almarklein** [comment]
The example is currently broken in master. But in #3888 it seems to work just fine (tested in FF/Chrome/Edge).

**Comment by bryevdv** [comment]
@almarklein is this completed?

**Comment by almarklein** [comment]
I think it is. It works for me, currently. Though when I tested a few times today it took ages for the map to show. Does google throttle because I keep reloading when testing or something? This example seems a bit fragile overall, but *this* issue seems fixed.
