### ISSUE TITLE
consider dynamic_map.py for deprecation

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3466]
ping @brendancol 

The data and undelying map quickly get out of sync

A _very_ short self contained fix could potentially be made. 

```
examples/plotting/file/dynamic_map.py:
 data overlays wrong after pan/zoom
```

**Comment by brendancol** [comment]
added this to the `examples_tweaks` branch

**Comment by bryevdv** [comment]
@brendancol fixes should be in their own PRs (sorry for confusion) the "shared" PRs are for docs-only changes. (Also that branch/PR has been merged already)

**Comment by bryevdv** [comment]
I merged the PR for a release workaround but will leave this issue open to further investigate the root causes.

**Comment by bryevdv** [comment]
The example is currently broken because the server in the example does not seem to be publicly serving images any longer, e.g this URL 

http://raster.nationalmap.gov/arcgis/rest/services/LandCover/USGS_EROS_LandCover_NLCD/MapServer/export?bbox=-17738291.271167893,-10610798.101869,4373412.271167893,11559823.101869&bboxSR=102100&size=567%2C565&imageSR=102100&format=png32&transparent=true&f=image

does not work.

I would actually propose to remove the example (and possibly deprecate dynamic image) and leave this sort of thing to geoviews. 

@bokeh/dev @brendancol @philippjfr @jlstevens thoughts? 

Moving to 0.12.7 because if we are to deprecate it needs to happen in the next release.

**Comment by philippjfr** [comment]
@bryevdv Could briefly describe what functionality dynamic map actually provided and how it relates to map tiles?

**Comment by bryevdv** [comment]
@philippjfr not really, AFIAK I think it can help with retrieving scaled images from sites that have a suitable REST API

**Comment by bryevdv** [comment]
A brief and admittedly incomplete search of GitHub did not turn up any real uses of `add_dynamic_map` that I could find. I'm personally +1 to remove.

**Comment by bryevdv** [comment]
OK well the remote source started working again:

<img width="634" alt="screen shot 2017-07-17 at 14 49 18" src="https://user-images.githubusercontent.com/1078448/28286861-32f0666e-6aff-11e7-9cb9-f1b4261f3c07.png">

@hsparra @philippjfr so yah as you zoom this in and out, dynamic image makes an AJAX query to the using the REST api template, and then displays the image returned. I think that is useful, but:

* current implementation has no tests == unmaintainable
* seems better suited for GeoViews at this point/in the near future

So I am going to go ahead with the deprecation.
