### ISSUE TITLE
Hover tool performance seems degraded

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3467]
ping @birdsarah I wonder if this is related to the "over render()" you noticed.

A *very* short and self-contained fix coud potentially be entertained. 

```
examples/plotting/file/texas.py:
 hover tool performance seems degraded / laggy
```

**Comment by bryevdv** [comment]
only sending inspect if "last inspect was empty" is too coarse, need to keep track per renderer.

**Comment by birdsarah** [comment]
fwiw texas seems very snappy to me today.
