### ISSUE TITLE
embed_responsive_with_height.py starts out wrong size

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3468]
ping @birdsarah @almarklein 

After resizing the window, the plot "pops" to a much larger size then is responsive

```
examples/embed/embed_responsive_with_height.py:
 starts out small and "pops" to full size on browser window resize
```

**Comment by birdsarah** [comment]
@bryevdv can you clarify, what I am seeing is that the initial resize doesn't happen, but then on resize it behaves as epxected. Seen this on FF and Safari.

If the window is small then on the initial load the plot is than the window for me.

Worth noting the console error: `this.el.parentNode is null` which only happens on the first call, and not for subsequent resizes.

**Comment by birdsarah** [comment]
here's a quick video of what it looks like for me
![resize_example](https://cloud.githubusercontent.com/assets/1796208/12079592/c429e766-b20c-11e5-9e46-7d2b3333632b.gif)

**Comment by bryevdv** [comment]
That sounds like a what I'm seeing
