### ISSUE TITLE
range / bounds problems on airports and iris_splom

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3470]
ping @birdsarah @brendancol 

```
examples/glyphs/airports_map.py:
 can't pan or zoom in/out in cases that should work
```

Very small fix could be entertained (or demo removed for now)

**EDIT**: `iris_splom.py` has some serious pan/zoom problems too. Setting `bounds=None` happens to fix, and I actually like that better, so I will change it to that. But it _should_ work with auto bounds

**Comment by brendancol** [comment]
https://github.com/bokeh/bokeh/pull/3474

**Comment by birdsarah** [comment]
`iris_splom` is interesting. @bryevdv - my hunch is that this isn't bounds per se, but because DataRange isn't getting re-updated when the new plots are added because if DataRange start and end change then bounds change (or at least that's what's meant to happen).

**Comment by bryevdv** [comment]
iris splom currently behaving per my expectations, I can't remember what this was about, so closing.
