### ISSUE TITLE
Reflect input widget state in URL

### ISSUE THREAD

**Issue by seibert** [bokeh/bokeh#3478]
This is a discussion issue for figuring out what kind of interface (if any) would make sense to allow input widget state to be reflected in the URL to a bokeh app.

Use cases include:

1. An external site wants to link to a Bokeh app and pre-populate the widget inputs with specific values when a user follows the link.
2. A user interacting with a Bokeh app has set some widget inputs to some specific values and would like to copy and paste a link to another user such that when the other user clicks on the link, the Bokeh app opens up in a similar state to what the first user sees.

There are a couple ways to go about this, with different amounts of effort from the app-author required.  For example:

* The app author could indicate specific widgets which should be reflected in the URL, and Bokeh would keep the URL (perhaps via URL parameters) in sync with the widget values.
* As an extension to the above approach, one could imagine letting the app author specify some kind of URL pattern which shows how URL path components map to widget values.   This starts to look more like a real webapp framework and may be getting too complex.

Another open question is whether the client-side plot state itself (visible axis range and current selections) can be reflected in a URL, allowing a link to be constructed that would recreate the entire visible state of the app.

**Comment by bryevdv** [comment]
This kind of bookmarking would be a nice feature, but it needs to be done in a non-ad-hoc way.

**Comment by bryevdv** [comment]
In `0.12.2` apps now have access to HTTP request arguments, and can use them to customize sessions accordingly. Since this request specifically concerns Bokeh apps, and that feature could be used to implement the kind of customization described, if desired, I am going to go ahead and close this.
