### ISSUE TITLE
Multiple hover tools management

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#3482]
As a followup of #3454 there are few challenges:
<img width="182" alt="overhover" src="https://cloud.githubusercontent.com/assets/8209940/12066862/f1be8238-afa3-11e5-944a-494734e92a1f.png">

Any option to define a proper **name** for each HoverTool?

**UX** suggestion to be able to switch on/off all the hovers with one click and potentially add option for advanced users to select individual hovers to switch on/off, like Office is handling borders: http://www.excel-exercice.com/wp-content/uploads/2011/06/3D_Borders.png

Today my code is sequential, but I'm planning to move to parallel insert of `p.line()` (I hope Bokeh is thread safe), any option to define the display **order** in the long list in the toolbar or in the legend box?

**Comment by WhereIsMySnake** [comment]
+1
That would be really cool to name hover tools. 
In some cases it is really hard to check/uncheck right tool

**Comment by bryevdv** [comment]
> That would be really cool to name hover tools. 

It's already possible to set a `name` property (and search for it with `.select`) on any Bokeh model.

**Comment by bryevdv** [comment]
Thing's are a bit different now, with hover tools now directly in the toolbar (not a popup) I am closing this in favor of https://github.com/bokeh/bokeh/issues/5497 which is more up to date about what needs to be fixed at this point
