### ISSUE TITLE
We fail to prevent boomerang on collections of models

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3483]
When the client sends changes to Plot.renderers for example, we go through this comparison: https://github.com/bokeh/bokeh/blob/218424dc4071f8b7b5203468391e2a3485555e7f/bokeh/server/protocol/messages/patch_doc.py#L57

On that line, one of `patch_new` and `event.serializable_new` is a list of Python Model objects, and the other is a list of JSON ref dicts (just the id/type/subtype). They do not compare equal so we send a useless notification back to the client boomeranging the same set of renderers. Fortunately the client seems to short-circuit things and doesn't send a boomerang back, so it ends there.

I don't know exactly why this happens or the right fix yet, but the bug could have bad implications; it could also affect dicts, and it could happen in some case where the client also fails to block boomerang, which would create an infinite ping-pong.

Then again we don't _know_ yet that it has bad implications, other than an extra message.

**Comment by havocp** [comment]
To fix this the first thing I'd do is copy the boomerang tests in test_client_server.py and modify the copy to test collections of models (at least list, dict of Instance). Presumably those new tests would fail, and then there would be a nice test case to fix.

However it's possible the tests wouldn't fail because the problem is specific to the way JS sends us the patch message; if so, we'd have to add a test over in test_client.coffee (which talks to the python server).

**Comment by bryevdv** [comment]
@havocp this is resolved (at least to a reasonable degree)? My recollection is ping-ponging made the histogram selection example unusable, and it works quite nicely now.

**Comment by havocp** [comment]
I think we may have worked around this somehow but the actual bug described here (nonsensical equality check between json and real models) may remain. But not sure.

**Comment by havocp** [comment]
wouldn't hurt to add tests for this case which would prove the bug status ...

**Comment by bryevdv** [comment]
@philippjfr any thoughts on this? We prevent ping-pong with the new `setter_id` correct from your numpy protocol PR, correct? There's also another PR for adding tests for this, so I'm inclined to close this one if you agree it's no longer relevant.

**Comment by philippjfr** [comment]
That's correct, I'd definitely close this one as the equality checking no longer happens. The issue to add tests for the new approach should remain open though. If you want to assign that to me I'd happy to have a look as well.
