### ISSUE TITLE
bokeh.resources.INLINE.render_js() unnecessarily exposes minor info about server in HTML (0.11.0.dev7)

### ISSUE THREAD

**Issue by mmcdan** [bokeh/bokeh#3488]
Hello, I am using bokeh.resources.INLINE.render_js() to embed bokeh's required JS resources.
I've noticed quite a few comments of the form:
````
/* BEGIN /path/to/bokeh_js_file.js */
\<js code here\>
/* END /path/to/bokeh_js_file.js */ 
````

This path exposes things like the username of the computer, path to python libraries, whether or not a virtual env is used, etc... None of this is a major security concern per se, but I don't think it should be available in the HTML for the world to see. It looks like this is done by the _inline method BaseResources (https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L305), so I assume the same problem occurs with bokeh.resources.INLINE.render_css().

Can we have this disabled by default?

**Comment by mattpap** [comment]
Agreed, always providing full path is unnecessary.

**Comment by bryevdv** [comment]
+1
