### ISSUE TITLE
collections.deque should serlialize

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3493]
Would be useful, e.g. in random walk demo notebook

**Comment by chalmerlowe** [comment]
In consultation with bryevdv, this appears to have been solved.
See the code below that uses deques to create points for circles and the resulting screenshot of a properly formatted circle plot.
```python
from bokeh.plotting import figure, output_file, show
from collections import deque
output_file("test_circle_deque.html")
p = figure(plot_width=400, plot_height=400)
x = deque([1, 2, 3, 4, 5])
y = deque([6, 7, 2, 4, 5])
p.circle(x, y, size=20, color="navy", alpha=0.5)
show(p)
```

<img width="496" alt="plot_w_deques" src="https://cloud.githubusercontent.com/assets/7291104/15790452/10392b80-296d-11e6-94a1-c46cf5df8969.png">

**Comment by bryevdv** [comment]
awesome when something fixes itself :)
