### ISSUE TITLE
Charts API documentation examples broken + documentation doesn't match function signatures

### ISSUE THREAD

**Issue by williamjshipman** [bokeh/bokeh#3496]
While trying to learn to use Bokeh in Python, I got confused by the charts API docs because some of the examples there produce errors and the function signatures don't match the docs. I'll take [bokeh.charts.Line](http://bokeh.pydata.org/en/latest/docs/reference/charts.html#bokeh.charts.Line) as an example:
1. The example code produces an error in the documentation, which I also receive when testing it on my laptop. Wrapping the NumPy array in a Pandas DataFrame and specifying y='column name' works.
2. The documentation describes a parameter `values`, but passing `values=...` to bokeh.charts.Line results in an exception:
   
   AttributeError: unexpected attribute 'values' to ChartOptions, possible attributes are filename,
   height, id, legend, name, notebook, responsive, server, session, tags, title, title_text_font_size,
   tools, width, xgrid, xlabel, xscale, ygrid, ylabel or yscale
3. I never did get Line to work with NumPy arrays. Are they supposed to?

**Comment by bryevdv** [comment]
There have been changes to the API in the last several months, although it is now stabilizing in a way we are happy with.

@fpliger @rothnic can you ensure that this and all examples are working in the docs for the upcoming `0.11` release?

**Comment by fpliger** [comment]
@williamjshipman thanks for your feedback. We are currently working on examples and documentation for the new release. The `Charts` documentation of the current major version (`0.10`) that you can find here: http://bokeh.pydata.org/en/latest/index.html is not up do date with the new charts you can find in the next upcoming `0.11` release ( you can already see the progress and many improvements here: http://bokeh.pydata.org/en/dev/index.html )

From your issue description it's hard to understand the version you have currently installed and the documentation version you are looking at. You don't seem to be using the latest `0.11` dev builds..

I'd suggest you to install the latest `0.11` dev build and start from there looking at the dev docs. We are currently working on those docs so they may change fast but this way you are getting the latest version and can report any issues you may find (either in the docs, examples or code..)

**Comment by williamjshipman** [comment]
@fpliger I'm using 0.10.0 installed with Anaconda 2.4.1, Python 3.5.1. I'll try out the 0.11 dev build. 

Perhaps a warning at the top of the `Charts` documentation for 0.10.0 stating that it is outdated is needed so other new users don't get as frustrated as I did. Will the `Charts` API still be changing so much from 0.11 to 0.12?

**Comment by bryevdv** [comment]
@williamjshipman I'm not so sure the `0.10` is out of date as that parts of it are erroneous. There is not much change at all (besides additions, new charts, etc) from `0.10` to `0.11` and I expect this will now be the norm going forward.

**Comment by bryevdv** [comment]
FYI I just created a new "dev build" `0.11.0dev9` you can see install instructions for dev builds here:

http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

Additionally, the RC1 will probably available by Monday.

**Comment by williamjshipman** [comment]
@bryevdv Glad to hear the API will be stabilizing. I'll give the new build a try.

**Comment by williamjshipman** [comment]
Great, got `0.11.0dev9` going in a new conda environment and the example with a NumPy array now runs.

Looking at the dev documentation for Line: http://bokeh.pydata.org/en/dev/docs/reference/charts.html#bokeh.charts.Line, the description for the `data` parameter is `a 2d data source with columns of data for each line.` However, the example actually shows using a 3x5 NumPy array (i.e. 3 rows x 5 columns) yet only three lines get plotted, meaning that each line corresponds to a row, not a column. Pandas DataFrames work as advertised - each column is one line.

Should I start a new issue for `0.11.0dev9` documentation errors?

**Comment by bryevdv** [comment]
@williamjshipman that would be very helpful and appreciated!

**Comment by bryevdv** [comment]
bokeh.charts has moved to https://github.com/bokeh/bkcharts this should be re-opened there if appropriate.
