### ISSUE TITLE
Cycle Colors for plots

### ISSUE THREAD

**Issue by ThomasLecocq** [bokeh/bokeh#351]
1) It would be a nice feature to have an automated loop over some defined palettes when plotting multiple lines on the same plot, similarly to the color_cycle of matplotlib. 

2) would be easy to support the color name abbreviations (c,b,g,...). When setting line_color="g", one gets a cool not-obvious traceback:

RuntimeError: Column name 'g' does not appear in data source <bokeh.objects.ColumnDataSource object at 0x7fbc2020ed10>

**Comment by damianavila** [comment]
I remember I wrote some cycle for Charts, it was a helper function, we can probably make it more general to close this issue... let me find it: https://github.com/bokeh/bokeh/blob/master/bokeh/charts/utils.py#L36-L57

@bryevdv, for the todo you put there,  I think you are thinking in the same... or you want to make something more elaborated?

**Comment by bryevdv** [comment]
@damianavila no I just think is is generally useful and should go up in `bokeh.plotting_helpers` or maybe `bokeh.helpers.plotting` if we really want to collect all the different utils/helpers in one place.

**Comment by damianavila** [comment]
OK, assigned to me...

Btw, I think this will also cover #632...

**Comment by fpliger** [comment]
> no I just think is is generally useful and should go up in bokeh.plotting_helpers or maybe bokeh.helpers.plotting if we really want to collect all the different utils/helpers in one place. 

I think the later is better in the long term..

**Comment by damianavila** [comment]
yes, I will go with the second option to have `helpers.plotting`, `helpers.mpl`, `helpers.charts`, etc...

**Comment by fpliger** [comment]
In that chase we should have a `generic` helpers bin where we collect helpers reused across all the API (like the case of `cycle_colors`, `cycle_palette`, etc..)

**Comment by damianavila** [comment]
yep... I agree...

**Comment by bryevdv** [comment]
Maybe:
```
helpers.deps       # for dealing with optional dependencies (pandas, numpy, etc)
helpers.misc       # general util
helpers.plotting   # general plotting helps, not just plotting.py 
```

**Comment by damianavila** [comment]
yep... sound good...

**Comment by fpliger** [comment]
we now have `charts.utils.cycle_colors`. This should be moved to a shared interface that both `plotting` and `charts` can use.

**Comment by bryevdv** [comment]
Closing since we have `cycle_colors` opening separate issues for follow on work.

**Comment by colinfang** [comment]
For ref, see #2201
