### ISSUE TITLE
having a __conda_version__.py under bokeh causes version to be wrong

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3515]
I had a __conda_version__.py file lurking under bokeh package and this was causing bokeh to get the wrong dev version for me from, for example, CDN.

A warning would have been very helpful. I didn't know to look for this.

**Comment by damianavila** [comment]
Copying what I put on the flow just for reference:

"to be sure to avoid this kind of problems next time you can "clean" your git space with

`git clean -xfdi`

that should remove any files and directories putting you in a clean start again...

in that way you should conserve your local branches ... no need to reclone...."

**Comment by mattpap** [comment]
I run into this issue myself recently. Being forced to periodically clean the repository isn't a solution here.

**Comment by damianavila** [comment]
> I run into this issue myself recently. Being forced to periodically clean the repository isn't a solution here.

Not suggesting that... we should address this somehow, just giving a quick workaround to keep working...

**Comment by mattpap** [comment]
Sure. btw. This is the ultimate git clean alias I use:
```
deep-clean = !sh -c 'git clean -dfx && git submodule foreach git clean -dfx'
```
