### ISSUE TITLE
Hovertool fails for rects with only negative heights.

### ISSUE THREAD

**Issue by RutgerK** [bokeh/bokeh#3517]
The hovertool fails to display when plotting `rects` with only negative heights. As soon as there is at least one positive height, all hovers are shown as expected. Based on this Stackoverflow question:
http://stackoverflow.com/questions/34516294/bokeh-hover-tool-works-on-one-serie-but-not-in-combined-series

A minimal example displaying this behavior (in 0.11.0dev9) is:

``` Python
from bokeh.plotting import figure, show

height = [-0.5, -1.0, -1.5]

x = [1,2,3]
y = [x / 2. for x in height]

p = figure(width=300, height=300, tools="hover")
p.rect(x=x, y=y, width=0.8, height=height)

show(p)
```

Changing the height to for example to:

```
height = [-0.5, 1.0, -1.5]
```

Makes all hovers work correctly again.

Its not explicitly mentioned in the docs that negative heights are allowed, but since they are displayed fine, i assume it is. Therefore the hovertool should also be able to show tooltips on them.

My system info:

```
Windows 7 64x
Python 3.4.3
Bokeh 0.11.0dev9
Firefox 43.0.3
```

**Comment by bryevdv** [comment]
I would regard negative heights for rectangles working as probably an accident, possibly it's the behavior of the low level canvas implementation to ignore sigh on width and height. What is the use case for negative heights?

**Comment by RutgerK** [comment]
For me none that i can think of, so I'm fine with no support for it. You can easily adjust the `y` value so that you never need a negative height, it doesn't add any functionality. And keeping the low-level API as simple and straightforward seems best to me. Perhaps in a high-level chart you could do some 'magic' behind the scenes, but even then i personally would prefer only one way of specifying the data, which is less confusing in the long term.

But perhaps it should be checked and handled more consistently? Or maybe raise a warning. Because the current behavior is quite confusing, i find the StackOverflow question a reasonable approach, and it wasn't obvious to me as well. It sometimes works, and sometimes doesn't, with no feedback at all.

**Comment by bryevdv** [comment]
I agree a warning is probably in order, we can certainly add validation to the Bokeh model properties for things like width and height that only make sense nonzero. I've updated this issue to be an issue for adding that.

**Comment by bilderbuchi** [comment]
One use case I encountered is stacked bar charts with all negative values, where the hovertool fails (if you flip the signs in the data, it works. 
(Incidentally, I'm currently trying to make stacked bar charts with mixed pos/neg values work nicely)

**Comment by bryevdv** [comment]
FWIW I have a VBar/HBar glyph branch I mean to make a PR out of soon.

**Comment by bryevdv** [comment]
This was actually fixed at some point:

<img width="459" alt="screen shot 2017-07-13 at 13 30 20" src="https://user-images.githubusercontent.com/1078448/28181850-a4410e96-67cf-11e7-8911-ac6786aad781.png">

closing accordingly
