### ISSUE TITLE
New Enhanced Statistical Plots, Box Plots, and Violin Plot Overlays

### ISSUE THREAD

**Issue by dragoljub** [bokeh/bokeh#3526]
Here is a nice example of more scientific oriented stats plots entirely built with bokeh glyfs. Would love to incorporate these into the new BoxPlot high-level charting interface.

Code is all here:
https://github.com/rsgoodwin/splot

![example1](https://cloud.githubusercontent.com/assets/2701562/12097074/808aef60-b2ce-11e5-8ccf-1ececabf1d09.PNG)
![example2](https://cloud.githubusercontent.com/assets/2701562/12097079/8487e186-b2ce-11e5-81db-67610f5330a8.PNG)

**Comment by fpliger** [comment]
@dragoljub sorry for the terribly slow reply...

Those look awesome! I'd be very very happy to help and work with you towards integrating these into  `charts`. Would you like to give it a try? :)

In that case let me know how and where we can help you. I think that most of the work would be to understand the data shape you are assuming in your bivar module and check the ajustments to integrate these (and the related computation) in the `Charts` and `Builders` machinery..

**Comment by dragoljub** [comment]
@fpliger thanks for taking a look. :+1: Please feel free run with the code linked above following the best practices for making bokeh charts.

The original goal was to use "[Tidy Data](http://vita.had.co.nz/papers/tidy-data.pdf)" formatted DataFrames. Much like [seaborn data-aware grids](http://stanford.edu/~mwaskom/software/seaborn/tutorial/axis_grids.html?highlight=tidy) ("In brief, that means your DataFrame should be structured such that each column is a variable and each row is an observation.") That is, long form data frames with indicator columns that describe observations of data points. This way you have more flexibility when dealing with missing data points compared to a fully pivoted data frame with many index aligned column series.

**Comment by fpliger** [comment]
We are considering some core additions that would make it much easier to draw glyphs like the `Violin` and have better relative reference (when considering nested [categorical] axis) so it's probably better to wait a bit on this..

**Comment by bryevdv** [comment]
As `bokeh.charts` has moved to a new `bkcharts` repo and as HoloViews will be supported as a high level API on top of Bokeh, I am closing this issue as not relevant to the bokeh core repo.
