### ISSUE TITLE
Notebook Output mode on 0.11.0dev10 gives JavaScript Error

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#3533]
When placing the code below in a new iPython notebook, I am seeing a JavaScript error. I added the basic specs below. If you need more details, feel free to ask.

Code:

    import bokeh.plotting
    import bokeh.plotting as bp

    bp.output_notebook()

Error:

    Javascript error adding output!
    ReferenceError: Bokeh is not defined
    See your browser Javascript console for more details.

Specs:

Mac: 10.9.5
Firefox: 43.0.1
Bokeh: 0.11.0dev10
iPython: 4.0.1
Notebook: 4.0.6
...

**Comment by bryevdv** [comment]
This is  dupe and should be fixed in the (literary just uploaded) RC1

**Comment by jakirkham** [comment]
Oh sorry, I looked but I must have missed it.

**Comment by jakirkham** [comment]
Yes, RC1 does seem to fix it. Thanks.

**Comment by bryevdv** [comment]
No worries, searching for issues is hard, there's lots of reasonable terms that could apply.
