### ISSUE TITLE
panning off plot causes panning to stop working (chrome)

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3535]
![bokeh](https://cloud.githubusercontent.com/assets/1796208/12102625/0c30fc40-b30a-11e5-846b-6f9219504c96.gif)

to reproduce:
- http://demo.bokehplots.com/apps/selection_histogram
- zoom in a little
- pan to the left and go off plot till plot is selected
- pan then stops working

reported for chrome on windows and osx

**Comment by bryevdv** [comment]
I can no longer reproduce this using the steps above (on chrome)
