### ISSUE TITLE
Charts + Bokeh Server: Scatter plot added twice

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3546]
When using charts api + `bokeh serve`, scatter plot is added twice:

Reproduction:

```python
from bokeh.models.widgets import HBox
from bokeh.sampledata.autompg import autompg
from bokeh.charts import Scatter
from bokeh.plotting import Figure
from bokeh.io import curdoc

d = {}
d['tools'] = 'pan,wheel_zoom'
d['data'] = autompg
d['x'] = 'mpg'
d['y'] = 'cyl'
d['xlabel'] = 'mpg'
d['ylabel'] = 'cyl'

s = Scatter(**d)
placeholder_fig = Figure(tools='pan,wheel_zoom')

b = HBox()
b.children = [placeholder_fig, s]
doc = curdoc().add_root(b)
```

**Comment by brendancol** [comment]
The upper-left plot should not be there

<img width="1295" alt="screen shot 2016-01-05 at 10 03 38 am" src="https://cloud.githubusercontent.com/assets/433221/12119866/c909965e-b393-11e5-99c5-e766d498416c.png">

**Comment by brendancol** [comment]
Issue is definite related to putting a chart in a box.  Example:
```python
from bokeh.sampledata.autompg import autompg as df
from bokeh.charts import Scatter
s = Scatter(df, x='mpg', y='hp', color='cyl', marker='origin',
                  title="Auto MPG", xlabel="Miles Per Gallon",
                  ylabel="Horsepower")
b = HBox()
b.children = [s]
doc = curdoc().add_root(b)
```


<img width="404" alt="screen shot 2016-01-24 at 1 26 24 pm" src="https://cloud.githubusercontent.com/assets/433221/12538384/31cef18e-c29e-11e5-8d99-17e47c8c0eab.png">

**Comment by brendancol** [comment]
when I remove from https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder.py

```python
curdoc()._current_plot = chart # TODO (havocp) store this on state, not doc?
if curstate().autoadd:
    curdoc().add_root(chart)
```

**Comment by havocp** [comment]
things we could do here:
 * add setter so you can `curstate().autoadd=False`
 * consider making containers like HBox auto-remove from root as vplot etc. do
 * consider making bokehjs display the problem in a more visible way (maybe if a dom node is already in the dom when the parent hbox gets it, show "this model is already displayed elsewhere" or something ? instead of displaying empty plot)

**Comment by bryevdv** [comment]
> add setter so you can curstate().autoadd=False

Sure, +1 

> consider making containers like HBox auto-remove from root as vplot etc. do

-1000 The goal is for models to not need much or any logic on the python side.

We know the full list of what models can have children, we already warn about this if I am not mistaken (BOTH_ROOT_AND_CHILD, I think) Is there any reason not to just fix this up automatically at serialization time? There's no way, with this "implicit state" usage, that this won't be a common situation. Given that, I think we should just deal with it in a way that gives the commonly expected result. We can document that behavior easily enough. 

> consider making bokehjs display the problem in a more visible way (maybe if a dom node is already in the dom when the parent hbox gets it, show "this model is already displayed elsewhere" or something ? instead of displaying empty plot)

I think this would be good to do, but it doesn't actually solve the problem at hand

**Comment by rothnic** [comment]
For the autoadd, I have an issue open with #3638. Right now I'm using that within any chart app to avoid the problem.

**Comment by havocp** [comment]
> We know the full list of what models can have children, we already warn about this if > I am not mistaken (BOTH_ROOT_AND_CHILD, I think) Is there any reason not to
> just fix this up automatically at serialization time?

why at serialization time instead of when you set children on the HBox? If you fix it at serialization time then you'll have a situation where calling push() or show() or push_session() modifies your Document, or where the Document is modified after the app script returns.

**Comment by havocp** [comment]
We do warn about this, but people aren't seeing or aren't understanding the warning it looks like.

**Comment by bryevdv** [comment]
> why at serialization time instead of when you set children on the HBox? If you fix it at serialization time then you'll have a situation where calling push() or show() or push_session() modifies your Document, or where the Document is modified after the app script returns.

Trying to avoid having logic in the models. How about checking (and modifying as needed) immediately on `add_root` then, that actually seems ideal?

**Comment by havocp** [comment]
the add_root is before the HBox exists I think, so there's no problem at that point

**Comment by bryevdv** [comment]
But the `HBox` is added as a root somewhere?

**Comment by havocp** [comment]
ah ok. that would catch the problem at least part of the time (when hbox children are passed in before adding it as root, which is hopefully the most common case).

**Comment by bryevdv** [comment]
Well, I'm suggesting a compressive check on every `add_root`, not just of the thing being added. Shouldn't this always catch everything? Or do you suppose that would be too expensive to do?

**Comment by havocp** [comment]
it wouldn't catch if you add the HBox and then set hbox.children after adding it is all I can think of.

**Comment by bryevdv** [comment]
I see. So then instead of adding logic to everything that has a `.children` can we just detect model changes that change `.children` and check there as well? I'm trying to keep this logic inside `Document`...

**Comment by havocp** [comment]
had this idea: it could work to do this in the same spot in document.py that we recompute _all_models ... as we recompute _all_models, also find all examples of this problem. That computation happens anytime "ref" properties are modified, or roots are added. The only tricky bit is that auto-fixing this problem will also modify _all_models, so would have to accumulate instances of the problem as _all_models is rebuilt, and then at the end (once we're in a consistent state again) apply any fixes (which should trigger another _all_models recompute).

**Comment by bryevdv** [comment]
>  The only tricky bit is that auto-fixing this problem will also modify _all_models, so would have to accumulate instances of the problem as _all_models is rebuilt, and then at the end (once we're in a consistent state again) apply any fixes (which should trigger another _all_models recompute).

I'm a little hazy on this. When is the fix ever anything other than "remove a model from roots" (which should not affect `_all_models` -- it's being removed because it is already the child a root)

**Comment by havocp** [comment]
> I'm a little hazy on this. When is the fix ever anything other than "remove a model from _roots" (which should not affect _all_models -- it's only being removed because it is already the child of another root)

True. I was mostly making a small practical point - in `_recompute_all_models` we iterate over the roots (and via `r.references()`, the models in each root), so if you modify the roots list while iterating over it, it might break. But in practice I think the check/fix here could be done after all that iterating has already been done... walk over _all_models looking for layout components, after _all_models has been computed. The main point is that `_recompute_all_models` should be called exactly when you need to re-run this check for components with multiple layout parents, so it's a place to hook into.

> I guess a cycle of children is another fun case to consider.

hopefully this is much less common for someone to do accidentally than the both-root-and-a-child situation :-)

**Comment by bryevdv** [comment]
This was fixed by the layout work and in particular the work to port the better python algorithm that replaces naive refcounting of models.
