### ISSUE TITLE
Add HTTPS to tile providers urls in `bokeh/tile_providers.py`

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3551]

**Comment by brendancol** [comment]
https://github.com/bokeh/bokeh/tree/task/make-tile-providers-use-ssl

- [ ] test all providers

**Comment by bryevdv** [comment]
Is this really the right thing to do? If I just navigate to either stamen or cartodb servers with https by hand I seem to get cert warnings at least initially:

<img width="572" alt="screen shot 2017-07-13 at 13 23 49" src="https://user-images.githubusercontent.com/1078448/28181524-9bee4f52-67ce-11e7-8ae4-45e468c58ca2.png">

**Comment by bryevdv** [comment]
Note that #7264 did not change the Stamen tiles: 

> I haven't changed the URL to the stamen tiles. They seem to be available through https but the certificate is invalid which results in browser showing an error message.

If they are ever successfully available HTTPS then a new issue should be made
