### ISSUE TITLE
Serve multiple plots using directory structure

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3555]
I'd like to take advantage of the directory structure for my bokeh app, but I have multiple plots that I'd like to serve. I'm currently doing `bokeh serve viz/individual.py viz/team.py`. I'd like to be able to do `bokeh serve viz` and have it run `/individual` and `/team`.

I may still need a main.py to somehow tell it to find all the plots.

I want a directory so I can take advantage of a global theme and lifecycle hooks, plus it's cleaner to run.

**Comment by bryevdv** [comment]
There has been no perceptible demand for this. I think this can be accomplished (including themes and lifecycle hooks) by following the examples under `howto/server_embed` especially the tornado example.
