### ISSUE TITLE
python callback example in user guide not rendering

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3562]
http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#customjs-with-a-python-function

Initially we thought this wasn't building because of python2 building the docs, but when trying to build locally I am not able to get it to build either.

I tried tweaking a couple of things which you can see in [this branch](https://github.com/bokeh/bokeh/compare/scratch_fix_flexx_example), but they didn't seem to improve.

ping @almarklein

**Comment by almarklein** [comment]
The problem is that PyScript needs to get the source code of the function being transpiled (which is done via inspect). During the doc building process, however, the examples are loaded in such a way, that inspect is unable the source code, which is why the example cannot be build.

**Comment by almarklein** [comment]
It actually says so in the HTML: "Unfortunately, the way that the docs are generated prevents PyScript from obtaining the Python source code, which is why the resulting plot is not shown on this page."

**Comment by bryevdv** [comment]
It should be removed from the docs then. Could put a link to source code for example and a static image if it would be useful.

**Comment by almarklein** [comment]
This got fixed.
