### ISSUE TITLE
Starting bokeh serve in subprocess

### ISSUE THREAD

**Issue by ChristianTremblay** [bokeh/bokeh#3567]
As bokeh serve is a tornado process that needs to run in the main thread, if a script needs to start the server, it cannot use a thread... and I'm not sure we could use a coroutine to start the serve inside another program.

For discussion, I tried importing the bootstrap... or the server ... and I always get stuck with the tornado IOLoop already running. 

Subprocess seems the way to go.

What would be the better way to start the process, keep track of it in case of a failure so it can be killed and restart.

I came out with this first attempt which start the server : 
```
    def startServer(self):
        if 'win' in sys.platform:
            commandToExecute = "bokeh.bat serve"
        else:
            commandToExecute = "bokeh serve"
        cmdargs = shlex.split(commandToExecute)
        #showDebug("EXECUTE BOKEH SERVE COMMAND '%s'" % cmdargs)
        p = subprocess.Popen(cmdargs, stdout=PIPE, stderr=PIPE)
        output, errors = p.communicate()
        if p.returncode:
            print('Failed running %s' % commandToExecute)
            raise Exception(errors)
        return output.decode('utf-8')
```

This is good until I restart the python kernel... the process continues to run as it is not "linked" to the app.

I keep in mind that in fact, I start a different python interpreter that runs the bokeh-script.py. It's then hard to retrive which python process is running the script (at least in Windows).

It would be possible to write the pid.id somewhere in a file at startup and retrieve it when needed... doesn't seem like a full elegant way though.

Would it be possible to consider a "standard" way in Bokeh to do that (an official bokeh function ?) 

The idea behind that is to be able to have a simple app to run by the user. Bokeh serve would be started in the background and the user don't have to bother.

Ideas welcome

**Comment by bryevdv** [comment]
My first instinct is to say this kind of thing is what process managers (e.g. supervisord, monit, systemd, upstart) are for, and that adding complexity to bokeh to duplicate existing tools (and in an inferior way, with almost certainly) is probably not a good idea. As a point of reference, we use supervisord and SaltStack to deploy both Nginx and the 8 Bokeh servers we run behind a the Nginx load balancer on http://demo.bokehlots.com

**Comment by ChristianTremblay** [comment]
My case is probably out of the standard focus. Technically, I only want to boekh server so I can update locally, plots with live data coming from what my app is reading on the building controllers network (bacnet).

I would have like a simple way to run a server from a script. I don't know what those process managers do... but from what I see... they seem targetted to heavy weight servers... much more than what I need for trending just a few points.

Actually though, there's no problem for me to just start the server manually or to rely on a subprocess... still at an early stage anyway.

I'm open to any suggestions. And guess I'll need to read some doc on process managers :-)

**Comment by ChristianTremblay** [comment]
Here's an extract showing my actual implementation of bokeh serve in a subprocess. It's probably not perfect but it seems to fit the need I actually have for a simple app running on my PC.

I'm using Anaconda on Windows.
Running the code from Jupyter Notebook
The subprocess is linked to the Jupyter Python session. Once started, the server will always run, until the Jupyter process will be terminated.

First, here's the code that will call the thread in which I start the subprocess.
This function, will try to start the server and poll localhost to look for connectivity

```
    def start_bokeh(self):
        try:
            logging.getLogger("requests").setLevel(logging.INFO)
            self.BokehServer = BokehServer()
            self.BokehServer.start()
            self.bokeh_document = BokehDocument(title = 'BAC0 - Live Trending')
            self.new_bokeh_session()
            self.bokeh_session.loop()
            attemptedConnections = 0
            while requests.get('http://localhost:5006').status_code != 200:
                time.sleep(0.1)
                attemptedConnections += 1
                if attemptedConnections > 10:
                    raise BokehServerCantStart
            self.bokehserver = True
        except OSError as error:
            self.bokehserver = False
            print('Please start bokeh serve to use trending features')
            print('controller.chart will not work')
        except RuntimeError as rterror:
            self.bokehserver = False
            print('Server already running')
        except BokehServerCantStart:
            self.bokehserver = False
            print("Can't start Bokeh Server")
            print('controller.chart will not work')
```

In my app, I've created class inheriting from thread... built one to deal with bokeh serve
```
class BokehServer(Thread):

    # Init thread running server
    def __init__(self, *, daemon = True):
        Thread.__init__(self, daemon = daemon)
        self.exitFlag = False
        #self.app = Application()
        #self.server = Server(Application(), io_loop= IOLoop(), extra_patterns=None, port=5006)
                
    def run(self):
        self.process()

    def process(self):
        # if self.started = True
        while not self.exitFlag:
            self.task()

    def startServer(self):
        if 'win' in sys.platform:
            commandToExecute = "bokeh.bat serve"
        else:
            commandToExecute = "bokeh serve"
        cmdargs = shlex.split(commandToExecute)
        #showDebug("EXECUTE BOKEH SERVE COMMAND '%s'" % cmdargs)
        p = subprocess.Popen(cmdargs, stdout=PIPE, stderr=PIPE)
        output, errors = p.communicate()
        if p.returncode:
            print('Failed running %s' % commandToExecute)
            raise Exception(errors)
        return output.decode('utf-8')
    
    def task(self):
        #self.startProcess('C:\\Users\\ctremblay.SERVISYS\\AppData\\Local\\Continuum\\Anaconda3\\bs.bat')
        try:
            self.startServer()
        except Exception:
            print('Bokeh server already running')
            self.exitFlag = True
        #bokehserve(['','serve'])

    def stop(self):
        self.bokeh_server.stop()
        self.exitFlag = True

    def beforeStop(self):
        """
        Action done when closing thread
        """
        pass
```

As said, it's actually working correctly, probably a little hacky, but it's a way to start a bokeh serve from a running app.

**Comment by bryevdv** [comment]
It turns out this will probably be needed for some of the work we'd like to do around turning notebooks into apps, so relabeling as a `feature`

**Comment by ChristianTremblay** [comment]
I will want to compare to what you think is the better way to handle this. Here is the code I use for BAC0

https://github.com/ChristianTremblay/BAC0/blob/master/BAC0/bokeh/BokehServer.py

**Comment by bryevdv** [comment]
A technique was demonstrated effectively by a user on the mailing list: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/LYmjTXzX43E
