### ISSUE TITLE
missing bokeh entry point (otherwise bokeh.bat) for Windows

### ISSUE THREAD

**Issue by stonebig** [bokeh/bokeh#3571]
hi,

on my windows, I have a "bokeh" file instead of a "bokeh.exe".

Wouldn't it be normal to get an entry point ? something like (but I guess slightly different)
````
    entry_points={
        'console_scripts': [
            'bokeh = bokeh.command.bootstrap:_main',
        ],
    },
````

**Comment by bryevdv** [comment]
Hi @stonebig thanks for the issue. None of us are really Windows users do it helps to have some input from folks with experience there. Could you possibly submit a pull request for this we could test out?

**Comment by stonebig** [comment]
I'm not an expert in entry point. currently trying to jus add a `bokeh.bat` with:
````
@echo off
rem Use python to execute the python script having the same name as this batch
rem file, but without any extension, located in the same directory as this
rem batch file
python "%~dpn0" %*
````

**Comment by stonebig** [comment]
when I launch it, Microsoft firewall wakes up in suspicion... is it normal ?

**Comment by ChristianTremblay** [comment]
There's a bokeh.bat inside Anaconda3 scripts (```Anaconda3\Scripts```)

Here's the content : 
```
@echo off
set PYFILE=%~f0
set PYFILE=%PYFILE:~0,-4%-script.py
"%~f0\..\..\python.exe" "%PYFILE%" %*
```

it allows to start bokeh serve correctly.

**Comment by ChristianTremblay** [comment]
You should be able to add port 5006 to an exception list in the firewall.
I think that it's something like a "New Rule" for inbound and outbound connections....

**Comment by stonebig** [comment]
the majority of windows users I know wouldn't dare imagining doing that

**Comment by ChristianTremblay** [comment]
That's why I usually disable the Windows Firewall :-)

**Comment by stonebig** [comment]
a breakthrough idea, I shall consider it :-)

**Comment by stonebig** [comment]
no fix ?

**Comment by bryevdv** [comment]
@stonebig it seemed like you had some possible ideas above, so if you could submit a pull request with them it would be a great help. Testing/debugging install and build issues is an enormous time sink, even more so when it means working in VMs, and anything that can help spread the effort is appreciated.

**Comment by stonebig** [comment]
it would be a blind fix, would you Appveyor check it works ?

**Comment by bryevdv** [comment]
It's not enough, but if it makes it though our CI testing, that's a good sign. :) Once the automated testing is passing, we can put effort into manual testing on VMs.

**Comment by stonebig** [comment]
ok, you have the good sign, but I don't think it means that it's a correct or bad fix.
