### ISSUE TITLE
Bokeh Histogram Attribute density doesn't work

### ISSUE THREAD

**Issue by ipolaco** [bokeh/bokeh#3576]
The att density (described below) doesn't seem to be working.

![screen shot 2016-01-07 at 5 19 32 pm](https://cloud.githubusercontent.com/assets/11196428/12184427/286a5630-b563-11e5-90a4-58931cb51cc5.png)

**Comment by sseemayer** [comment]
I'm having the same problem using bokeh 0.10.0 and Python 3.5.1 -- Some code to reproduce:

```
import numpy as np
import bokeh.charts
import bokeh.plotting

bokeh.plotting.output_file("histogram.html")

data = np.random.normal(size=1000)

hist = bokeh.charts.Histogram(data, density=True)
bokeh.charts.show(hist)
```

Result: 
![histogram](https://cloud.githubusercontent.com/assets/736556/12393538/9b70da64-bdf6-11e5-9d4f-7cf7ecaded54.png)

Note that the y-axis shows absolute counts, not a normalized frequency.

[bokeh_histogram.zip](https://github.com/bokeh/bokeh/files/94501/bokeh_histogram.zip)

**Comment by sseemayer** [comment]
Update: Also tried out the git HEAD (version 0.11.1dev1-42-gff5ccc6) which has the same problem.

**Comment by yipwendy713** [comment]
Confirm: have same issue. Is a fix on the way?

**Comment by birdsarah** [comment]
ping @fpliger @rothnic

**Comment by bryevdv** [comment]
This is definitely a bug, can confirm is is present in `0.12dev`

**Comment by bryevdv** [comment]
AFAICT the issue is the the new `HistogramGlyph` uses `bokeh.chart.stats.Bins`, which now uses `pd.cut` instead of `numpy.histogram`:

https://github.com/bokeh/bokeh/blob/master/bokeh/charts/stats.py#L337

So the first (hopefully easy?) issue is to communicate the `density` property to the `HistogramGlyph` (it is currently completely unused). The next issue is that the results of `pd.cut` need to be normalized, I don't think it accepts anything like a density parameter but I might be mistaken. 

Anyone here care to take a shot at a PR to fix?

**Comment by fpliger** [comment]
>> So the first (hopefully easy?) issue is to communicate the density property to the HistogramGlyph (it is currently completely unused). The next issue is that the results of pd.cut need to be normalized, I don't think it accepts anything like a density parameter but I might be mistaken.

@bryevdv at a glanceI think that restoring usage of `numpy.histogram` like < `0.10` would be easier instead.. If you don't have strong opinions I'd give it a try :)

**Comment by fpliger** [comment]
Ok, replacing `pd.cut` with `np.histogram` is very straightforward .. there are a few tweaks needed but I actually think it's a better approach (unless I'm missing something) as it allows easy access to density option and also avoids a couple of computation steps needed with `pd.cut`. More specifically, [here](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/stats.py#L353-L375).

**Comment by fpliger** [comment]
Only downside of replacing `pd.cut` with `np.histogram` is that they behave a bit differently. So:

```python
In [3]:
np.histogram(data, bins=3)
np.histogram(data, bins=3)

Out[3]:
(array([3, 3, 4]), array([ 0.,  3.,  6.,  9.]))


In [4]:
binned, bin_bounds = pd.cut(data, 3, retbins=True, include_lowest=True)
binned.value_counts()
​
Out[4]:
[-0.009, 3]    4
(3, 6]         3
(6, 9]         3
dtype: int64
````

but we could say the same for when in `0.10` we changed it. So I'd be +1 on changing... @bokeh/dev any objections? :)
