### ISSUE TITLE
animated.py stutters in Firefox but not in Chrome

### ISSUE THREAD

**Issue by ahhsia** [bokeh/bokeh#3577]
Using 0.11 from the conda bokeh channel (conda install -c bokeh bokeh) and running the new bokeh server. 
If I load the webpage in Chrome 47.0.2526, it looks fairly smooth at the 30ms update rate, but in Firefox 43.0 there is noticeable stuttering in the animation.

**Comment by bryevdv** [comment]
What platform?

**Comment by ahhsia** [comment]
Mac OSX (Yosemite)

**Comment by bryevdv** [comment]
Not all the canvas implementations are equal, BTW. My anecdotal experience has been that FF canvas implementation is the slowest. If that's where the issue lies there not much we can do about it.

**Comment by bryevdv** [comment]
The example performs smoothly on FF `48.0b3` on OSX with 30ms update. There is very little we could do to mitigate issues on older browsers.
