### ISSUE TITLE
Sizing plots, charts: Inconsistency between doc an api

### ISSUE THREAD

**Issue by aavanian** [bokeh/bokeh#3578]
Hi I encountered the following issue while migrating from v0.10 to v0.11

In v0.10:
one could size a ```Chart``` or a ```figure``` with the parameters ```width``` and ```height```.

In v0.11:
a ```figure``` will still size according to ```width``` and ```height``` and also according to ```plot_width``` and ```plot_height```)
a Chart won't size anymore according to those, even though the documentation still mentions these attributes (http://bokeh.pydata.org/en/latest/docs/reference/charts.html#core-classes). It will size according to ```plot_width``` and ```plot_height``` (as mentioned here: http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#dimensions)

Questions:
* Is it a doc issue? or height/width in Charts still serve a (different?) role
* Should this be added to the migration guide?
* Corollary question: what is the purpose of having two different set of parameters for what seems to be the same purpose?

**Comment by bryevdv** [comment]
Hi @aavanian some of the different interfaces have undergone periods of experimentation and development at different rates and by different people. I think we are at a place where most all of the interfaces are either very stable (`bokeh.models`, `bokeh.plotting`) or very close to it (`bokeh.charts`, being the newest). We are trying to bring into alignment and all the things that can be made in common. So I'd regard this as a docs issue. We are going to be refreshing and updating the `0.11` docs after-the-fact (not always ideal, but there are only so many hours in the day and we got as far as we could) so will update both the places you mention very soon.

**Comment by fpliger** [comment]
The docs mentioned here are the reference... a this point it would make sense to either fully remove `width` and `heigth` or add them back and start a deprecation cycle in `0.11.0` in any case I'd change the docs when also change the related code since those attributes would still be available (but ignore, as it is atm).
