### ISSUE TITLE
plot.image very slow

### ISSUE THREAD

**Issue by aplavin** [bokeh/bokeh#3579]
I tried a simple imshow-like piece of code with bokeh, and it works really slow for me: the image displays only about ~15 seconds after clicking Run. For about the first half of the delay I see mostly the python process to consume CPU, and for the second half - the browser process. This delay increases even more when the notebook server is accessed via the internet. For comparison, matplotlib shows the same image in just ~two seconds with both inline and notebook backends, even over the internet.

The code with bokeh 

Preparation:

    import bokeh.plotting as bp
    import numpy as np

    bp.output_notebook()

    img = np.random.rand(1024, 1024)

Actual plotting:

    plot = bp.figure(plot_width=512, plot_height=512,
                     x_range=[0, img.shape[0]], y_range=[0, img.shape[1]])
    plot.image(image=[np.flipud(img)], x=[0], y=[0],
               dw=[img.shape[0]], dh=[img.shape[1]])

    bp.show(plot)

Is there anything that can be done to speed it up?

**Comment by bryevdv** [comment]
At the moment, perhaps not. That is 2**20 elements converted to JSON, and back. We will be adding a binary transport option to the protocol soon, for both notebook comms and the Bokeh server over the network that sends raw data buffers directly into JS typed array views, but this is not ready yet. 

I will also mention that you are sending an image with 4x as many points as you have pixels. Given then, an immediate option is to downsample/peak pick before displaying.

**Comment by aplavin** [comment]
So, will wait for binary protocol then :) As for the pixel dimensions in my example, I just played with them to see if it makes any difference - in reality I need large images, about 1000x1000 and more, and several of them. Matplotlib isn't instantaneous in this case, but I didn't find anything faster.

**Comment by bryevdv** [comment]
I'm going to close this discussion, since there is no immediate action resulting. There is a separate issue (https://github.com/bokeh/bokeh/issues/2204) for the binary protocol that can be followed, that will be addressed when resources permit.

**Comment by izaid** [comment]
Any update on this? Any way to work around this? Would just be nice to show images in a reasonable amount of time.
