### ISSUE TITLE
Issue with datetime formatting with nanosecond resolution

### ISSUE THREAD

**Issue by pfennema** [bokeh/bokeh#3580]
Hi All,

I have the following issue with formatting the x-axis with a datetime string with nanosecond resolution as defined in pandas. Part of the code is below:

```
from pandas import to_datetime, Series
network = dict()
network['HeaderTransactTime'] = [ 1438585206104639227, 1438585215046327036, 1438585215816419176]
print ( to_datetime(Series(network['HeaderTransactTime'])))
network['NicTimestamp']       = [ 1, 2, 3]
p = figure(width=800, height=400  )  # ,x_axis_type="datetime"

p.xaxis[0].formatter = DatetimeTickFormatter(formats=dict(microseconds=[ "%f" ],
                                                      milliseconds=[ "%f" ],
                                                      seconds     =[ "%F" ],
                                                      minsec      =[ "%f" ],
                                                      minutes     =[ "%f" ],
                                                      hourmin     =[ "%f" ],
                                                      hours       =[ "%Y/%m/%d %H" ],
                                                      days        =[ "%Y/%m/%d" ],
                                                      months      =[ "%Y/%m" ],
                                                      years       =[ "%Y" ]))

p.line(network['HeaderTransactTime'], network['NicTimestamp'], color='green', alpha=0.5, legend='Price')
```

I'd like to have the x axis formatted as a timestamp, but unfortunately it does not work with the timestamps given.
The output of the 'to_datetime' is correct:
0   2015-08-03 07:00:06.104639227
1   2015-08-03 07:00:15.046327036
2   2015-08-03 07:00:15.816419176
dtype: datetime64[ns]

I tried several approaches with DatetimeTickFormatter, with and without the x_axis_type as 'datetime' but to no avail. Without the formatter applies I do get the raw number.
Is there a possibility to support the nanosecond resolution? (Also tried %N but that does not seem to work properly either).

Alternatively is there a possibility to use a formatter and return a custom string based on the input instead of giving a formats dict?

Thanks for the great library!

**Comment by pzwang** [comment]
Just saw this issue now... @pfennema dunno if this is still relevant, but FYI the DatetimeTickFormatter is the right place to try to configure this.  Unfortunately it looks like the `timezone` library we're using on the JS side only supports millisecond resolution.  (http://bigeasy.github.io/timezone/)

I agree that a custom callback function for tick formatting would be useful.  Now that we have `CustomJS` transcompilation technology, and with Custom Models support, I wonder if this is rather straightforward or if there might be some difficulties I'm not currently envisioning...

**Comment by pfennema** [comment]
Hi Peter, 

This is indeed still relevant as we want to plot our network latency
figures where the timstamps are with nanosecond granularity. On the
other hand we should be able to use the regular mechanisms to create an
x-axis with values. Still tinkering with this actually. 

Thanks for the reply! 

Peter Wang schreef op 2016-02-24 15:11:

> Just saw this issue now... @pfennema [1] dunno if this is still relevant, but FYI the DatetimeTickFormatter is the right place to try to configure this. Unfortunately it looks like the timezone library we're using on the JS side only supports millisecond resolution. (http://bigeasy.github.io/timezone/) 
> 
> I agree that a custom callback function for tick formatting would be useful. Now that we have CustomJS transcompilation technology, and with Custom Models support, I wonder if this is rather straightforward or if there might be some difficulties I'm not currently envisioning... 
> 
> --
> Reply to this email directly or view it on GitHub [2].

  

Links:
------
[1] https://github.com/pfennema
[2] https://github.com/bokeh/bokeh/issues/3580#issuecomment-188271191

**Comment by bryevdv** [comment]
This is definitely now do-able with a combination of:

* custom ticker
* custom tick formatter
* functickformatter (probably simplest)

and those are the best paths for such a specific use-case.
