### ISSUE TITLE
Request for a dual ended slider

### ISSUE THREAD

**Issue by jms90h5** [bokeh/bokeh#3590]
I have many places where I could use a "range" slider as it basically replaces the need to use two separate regular sliders. Note that a "range" slider has two drag points (for upper and lower values) rather than just the single drag point present in a normal slider.

Perhaps someone with the knowledge and bandwidth could extend Bokeh using the recently introduced user defined model capability to create this widget?.

As background, about a year ago issue #1982 was opened requesting a normal range slider.  The issue was subsequently closed with the apparent resolution that Bokeh already had a Slider.  There was an additional comment pointing out that the existing slider wasn't what the op was looking for and a link to an example of the desired widget.

**Comment by datnamer** [comment]
@almarklein Is there any way pyscript can be used to create a user defined model without needing to write coffescript?

**Comment by almarklein** [comment]
Right, now, pyscript can be used to define callbacks in Python, but not yet for user-defined models, though that is on our list of possible future work. 

I'd be +1 on a range slider btw. Maybe Phosphor JS should get one.

**Comment by datnamer** [comment]
Gotcha. Looking forward to that capability.

**Comment by lawremi** [comment]
I think this is a duplicate of #1996. 

Ideally it would be based on a `Range1d` model, which one could, for example, specify as the `x_range` on a plot to get automatic synchronization.

**Comment by bryevdv** [comment]
Yup, dupe, thanks
