### ISSUE TITLE
Import Error / Installation Error

### ISSUE THREAD

**Issue by nmvasani** [bokeh/bokeh#3597]
I'm using canopy/enthought python. I did a full installation via peppy "pip install bokeh" and all installed well...most current version as well. I can do "import bokeh" with no error. 

However I try:
"from bokeh.plotting import figure, show, output_file"

and get an import error:
ImportError: No module named plotting

I've tried reinstalling numerous times with no errors...can't figure it out.  Would appreciate any help.

**Comment by nmvasani** [comment]
PROBLEM SOLVED - there was no issue at all, I'm just a goof...my python script that was doing the import etc. was named "bokeh.py" so of course there was an error in looking for boke.plotting!!!!
Thanks for the help.

**Comment by Sloan0708** [comment]
Sorry , I got same error.
Can you help to give me some hint to solve this issue?
thanks

**Comment by bryevdv** [comment]
@Sloan0708 for general support questions please go to the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by fulcra-bailey** [comment]
Just found this same issue and no i don't wanna talk about it
