### ISSUE TITLE
PatchesView._mask_data() changes the draw order.

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#3601]
I think `patches()` should draw the patches in the order of the data.But it seems that `PatchesView._mask_data()` will changes the draw order randomly. Maybe it should return a sorted array .

Here is an example that demonstrate the problem:

https://ruoyu0088.gitbooks.io/book/content/evolution.html

if you slide the slider, it will add or remove triangles, finally it will become a firefox logo. But because the draw order is random, the triangles blink randomly.

run `fix()` that disable `_mask_data()` in console fix the problem.

**Comment by bryevdv** [comment]
Agreed that it would be preferable for the order to be stable, but it may prove to be technically infeasible or too expensive. Some investigation will be required before this feature can be definitively supported.

**Comment by jbednar** [comment]
Personally, I would think that having the patch elements drawn in any order other than that specified by the user, let alone in an unstable and arbitrarily changing order, is a bug.  not just the absence of a desirable feature.  This is very surprising behavior, and does not seem like something that would have been a reasonable design choice.

**Comment by bryevdv** [comment]
The reason the order changes is because the coordinates are stored in an RTree-like spatial index, and that index is queried against the current viewport to only render things that would actually be visible. The return results of the spatial index are not ordered, however. The performance increase when zoomed into a plot with many complicated patches is dramatic. So, not doing this would also be significant trade-off in some cases. I guess my initial thought is that if you need fine-grained control over ordering, you can make multiple patch or patches glyphs. The relative ordering of different glyphs *is* preserved.

**Comment by jbednar** [comment]
The reason this is coming up for us is that having multiple patch glyphs is extremely slow in our application, about 5 times slower than a single large glyph with the same data (see https://github.com/ioam/holoviews/pull/717). So performance is indeed an issue, but here we're not worrying about the zooming performance, just the initial view of the entire structure.  

I don't think it's accurate to say that it's about "fine-grained" control; it's about *any* control or indeed any predictability.  E.g. these are totally different plots, not just an issue of esthetics:

![image](https://cloud.githubusercontent.com/assets/1695496/16018848/e925ad96-316b-11e6-8038-cf7f0b4c775f.png)

Having good speed when zooming in, but having results that differ unpredictably as you zoom in, doesn't seem like a win.

**Comment by bryevdv** [comment]
Well, FWIW the use cases I had in mind at the time were e.g. choropleths, where the patches are disjoint and so the order is immaterial. I can appreciate this use case is different, it's just not one that I've seen much or even thought of two years ago. Perhaps the spatial index can be made optional, though I hate adding even more knobs and dials especially for extremely esoteric things. Open to suggestions.

**Comment by jbednar** [comment]
Ah, now it makes sense.  For choropleths, the ordering will only be visible when the borders aren't stored very accurately, and zooming on them will be common, so I can now see why such a tree would be a useful data structure.  But that's a pretty narrow application for plotting functionality like this, so I would expect that unstable behavior of this type to be something one could enable as a special optimization, not to be the default for all such calls.

**Comment by philippjfr** [comment]
@bryevdv How do you feel about optionally letting the user disable this optimization? I'm currently trying to bring filled 2d density plots to HoloViews but the fact that the draw order changes makes it fairly difficult, e.g. it starts out like this:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/31389706-d4d5c0c0-adc9-11e7-95cf-610c92d8a9a5.png)

But once I zoom out I get this:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/31389742-e86ca734-adc9-11e7-86df-fd2dfc4f05c4.png)

I don't think that is too niche a use-case to be supported.

**Comment by jbednar** [comment]
I would argue strongly that this optimization should be *off* by default, and then explicitly enabled in any examples we provide of choropleths. It's a very valuable optimization in cases where shapes are disjoint, but the behavior is completely incorrect otherwise, so it really does not seem appropriate to use an optimization like this in the general case.

**Comment by bryevdv** [comment]
In the absence of "patches with holes" this capability is obviously necessary to be able to reliably plot contour plots. So I am +1 on providing an option. But I disagree about changing the current default. I don't think most direct users of the Bokeh API will be making contour plots (it's hard, they will use HV, which can turn the value on or off as needed). But making cartograms directly with bokeh is much simpler, so I would judge that to be a more common usage scenario *in the context of direct use of the Bokeh API*. I think the default should cater to the common case.

**Comment by bryevdv** [comment]
Alternatively if it can be show to be efficient to sort the patches back to their original order, I'd support just doing that (and not adding any option/property)

**Comment by bryevdv** [comment]
@philippjfr I think it might suffice to simply sort the return value:
```
 _mask_data: (all_indices) ->
    xr = @renderer.plot_view.frame.x_ranges.default
    [x0, x1] = [xr.min, xr.max]

    yr = @renderer.plot_view.frame.y_ranges.default
    [y0, y1] = [yr.min, yr.max]

    bbox = hittest.validate_bbox_coords([x0, x1], [y0, y1])
    return @index.indices(bbox)
```
On the assumption that while the number of coords may be large, the number of individuals patches is probably not that big (1000s on the high end) just always sorting is probably OK.

**Comment by philippjfr** [comment]
That sounds fabulous! Totally agree that the number of patches is generally not that large. I do sometimes plot geometries with several thousand patches, but those are usually precisely the cases where they overlap and sorting is important.

**Comment by bryevdv** [comment]
If you have time to try before tomorrow afternoon CST this could go in 0.12.10

**Comment by bryevdv** [comment]
I can submit a PR but there is no-one included code or an MRE anywhere in this issue so someone else with code handy will have to test.
