### ISSUE TITLE
bokeh stacked graph not displaying on hover proper values

### ISSUE THREAD

**Issue by vasimkachhi** [bokeh/bokeh#3602]
i  am trying to plot Staked bar graph using bokeh._legacy_charts.Bellow is code i am using
import bokeh
from bokeh._legacy_charts import Bar, output_notebook, show
from bokeh.models import HoverTool, BoxSelectTool
output_notebook()
TOOLS="resize,pan,wheel_zoom,box_zoom,reset,previewsave,hover"
df = (sectors.T)
label = df.index.astype(str).values.tolist()
names=list(df.columns.values)
datadict={}
for row in names:
    datadict.update({str(row):df[row].astype(float).values})
TOOLS="resize,pan,wheel_zoom,box_zoom,reset,previewsave,hover"
bar = Bar(datadict,label,title = "Sectors bars", stacked = True ,legend=True,tools=TOOLS)
bar.select(dict(type=HoverTool)).tooltips = [('Value of ID',' $x'),('Value of Total','@cat')]
show(bar)

i m not geting proper valus of stact in graph
i want on hover it should display stack block name(value)
its imp and urgent so please look into it

Or maybe if i get legend value on hover even that will be good for me
Thanke in advance ,
Vasim Kachhi

**Comment by rothnic** [comment]
@vasimkachhi: see http://bokeh.pydata.org/en/latest/docs/gallery/stacked_bar_chart.html

This shows using the new charts interface with tooltips.

**Comment by bryevdv** [comment]
bokeh.charts has moved to https://github.com/bokeh/bkcharts this should be re-opened there if appropriate.
