### ISSUE TITLE
Bokeh 11 Barchart : Need a way to keep the original x labels order / to disable the lexical order sort

### ISSUE THREAD

**Issue by FabriceSalvaire** [bokeh/bokeh#3606]
I am using Bokeh to plot a kind of precomputed barchart/histogram where I give as input the x labels and their corresponding counts:

```
from bokeh.charts import Bar, output_file, show
data = {
    'labels': ('EN', 'PD', 'AD'),
    'counts': (10, 20, 30),
}
p = Bar(data, values='counts', label='labels')
output_file("bar.html")
show(p)
```

Unfortunately Bokeh 11 sort the x labels in lexical order, while I want to keep the given order. It was not the case for Bokeh 10.

Other minor issue: I have to clear the x and y label which are in English and irrelevant in my case "sum(counts)".

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/47)
