### ISSUE TITLE
Documentation is not so clear how to control height/width for responsive layout

### ISSUE THREAD

**Issue by FabriceSalvaire** [bokeh/bokeh#3608]
I am developing a responsive web application for desktop and mobile. The responsive option helps to adjust the figure width according to the device but I want to control also the aspect ratio since the figure height tend to be too large.

Apparently the page_height/width parameters could be used for this purpose but it is not so clear.

**Comment by bryevdv** [comment]
I'm not sure controlling the aspect is possible in the latest release. There is currently comprehensive work being done to improve every part of layout for Bokeh documents that will go into the `0.12` release when it is ready, so I am going to close this to clear up our tracker.
