### ISSUE TITLE
ajax_source.py broken on Windows 

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3613]
raises AttributeError: 'numpy.float64' object has no attribute 'append'

**Comment by bryevdv** [comment]
That's s py2 error (list comp variable reused) thought a fix had been checked in already.

**Comment by fpliger** [comment]
Ok. I'll check and close this if it has been fixed.. tnx

**Comment by bryevdv** [comment]
Moving to `0.12` to at least re-evaluate prior to release

**Comment by bryevdv** [comment]
Still an issue, appears the AJAX attempt is not happening or completing? navigating to `127.0.0.1:5050/data` shows the expected data is being served

<img width="553" alt="screen shot 2016-04-30 at 10 48 38 am" src="https://cloud.githubusercontent.com/assets/1078448/14937052/41271dcc-0ec1-11e6-9c68-1af80e50439e.png">

**Comment by bryevdv** [comment]
This is now only happening on Edge (works on FF and Chrome) and fails with a permission error:

<img width="657" alt="screen shot 2017-04-27 at 18 38 37" src="https://cloud.githubusercontent.com/assets/1078448/25508603/d21e024e-2b78-11e7-9c3b-b94d797fbc17.png">

That might just be a configuration problem in the example. In any event I am bumping this to `0.12.7`

**Comment by mattpap** [comment]
The latest error is likely result of PR #5630.

**Comment by bryevdv** [comment]
I'm going to close this. After some more research, it appears that Edge will refuse to load API endpoints from localhost, many people have reported issues around this. This is further borne out by the fact that navigating directly to the `/data` endpoint itself does not even work in Edge, but works fine in Chrome and FF. Additionally no one has reported real issues in the wild. Happy to re-open if a real problem with a non-localhost API can be demonstrated, or if anyone has any insight into an Edge configuration to work around this default restriction (I spent a little time with no success)
