### ISSUE TITLE
plotting/notebook/bollinger raises comm error on Windows

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3614]
raises Couldn't process kernel message Error: Could not open comm (IE only)

(Maybe this is a non issue since this should be one of the notebooks to be removed from examples...)

**Comment by bryevdv** [comment]
Moving to `0.12` to at least re-evaluate prior to release

**Comment by almarklein** [comment]
The example has been moved to the `bokeh-notebook` repository. Anyway, it seems to work fine on Windows on FF/Chrome/Edge.

**Comment by almarklein** [comment]
Marking as invalid because that what it is now. Feel free to adjust.
