### ISSUE TITLE
plotting/server/GeoJSon broken on Windows

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3615]
points keeps flashing and changing ranges

**Comment by bryevdv** [comment]
I believe that's expected, the example just needs to be improved.

**Comment by fpliger** [comment]
so.. shall we move to short-term?

**Comment by bryevdv** [comment]
No it shouldn't be hard to make a better example I don't think.

**Comment by bryevdv** [comment]
This example was improved to not do this.
