### ISSUE TITLE
Charts/Timeseries (STEP) chart is broken on Windows

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3616]
Renders non sense lines

**Comment by bryevdv** [comment]
Moving to `0.12` to at least re-evaluate prior to release

**Comment by bryevdv** [comment]
Still appears broken (FF and Chrome):

<img width="642" alt="screen shot 2016-04-30 at 10 42 13 am" src="https://cloud.githubusercontent.com/assets/1078448/14937016/3a569168-0ec0-11e6-9e20-f23fdb641de6.png">

**Comment by almarklein** [comment]
Confirmed. For reference, the plot should look more like the first (Line) plot of the same example.

The problem is in the generation: if I create the plot on Windows, it looks bad everywhere, even on Linux. Creating the same on Linux and viewing on Windows works fine.
