### ISSUE TITLE
Lots of warnings when using Bokeh in notebook

### ISSUE THREAD

**Issue by gregnordin** [bokeh/bokeh#3620]
For the following code I get lots of warnings when running Bokeh in a notebook (Mac OS X 10.10.4, Python 3.5, Bokeh 0.11, Ipython/Jupyter v.4.0):

	from bokeh.charts import Bar, show, output_notebook
	import pandas as pd

	output_notebook()

	data_dict = { 'numstudents' : [43, 22, 1, 
								   2, 54, 9, 
								   18, 10, 5,
								   14, 12, 3,
								   15, 11, 1,
								   14, 8, 2],
				  'language' : ['Matlab','Matlab','Matlab', 
								'C/C++','C/C++','C/C++', 
								'Java','Java','Java',
								'HTML/CSS','HTML/CSS','HTML/CSS',
								'Python','Python','Python',
								'Javascript','Javascript','Javascript'],
				  'skill_level' : ['Beginner','Intermediate','Expert', 
								   'Beginner','Intermediate','Expert', 
								   'Beginner','Intermediate','Expert',
								   'Beginner','Intermediate','Expert',
								   'Beginner','Intermediate','Expert',
								   'Beginner','Intermediate','Expert']
				}

	data_df = pd.DataFrame(data_dict)

	p = Bar(data_df, 
			values='numstudents', 
			label='language', 
			stack='skill_level',
			legend='top_right',
			title="ECEn 360 Student Self-Reported Programming Skills",
			tooltips=[('Students:', '@numstudents'), ('Language:', '@language')]
		   )
	show(p)

<img width="406" alt="screen shot 2016-01-08 at 11 26 27 pm" src="https://cloud.githubusercontent.com/assets/4380622/12237417/d24b8fae-b83b-11e5-95a0-afd223642bdc.png">

**Comment by bryevdv** [comment]
Resolved in current master (and probably in `0.11.1`): 

<img width="808" alt="screen shot 2016-04-07 at 3 28 16 pm" src="https://cloud.githubusercontent.com/assets/1078448/14365832/632a0306-fcd5-11e5-945f-809ec90f5254.png">
