### ISSUE TITLE
Tooltip doesn't show information when hover over bar graph elements

### ISSUE THREAD

**Issue by gregnordin** [bokeh/bokeh#3621]
I'm running Bokeh 0.11.0 on Mac OS X 10.10.4 with Python 3.5. I have the following code in a Jupyter Notebook:

```
from bokeh.charts import Bar, show, output_notebook
import pandas as pd

output_notebook()

data_dict = { 'numstudents' : [43, 22, 1, 
                               2, 54, 9, 
                               18, 10, 5,
                               14, 12, 3,
                               15, 11, 1,
                               14, 8, 2],
              'language' : ['Matlab','Matlab','Matlab', 
                            'C/C++','C/C++','C/C++', 
                            'Java','Java','Java',
                            'HTML/CSS','HTML/CSS','HTML/CSS',
                            'Python','Python','Python',
                            'Javascript','Javascript','Javascript'],
              'skill_level' : ['Beginner','Intermediate','Expert', 
                               'Beginner','Intermediate','Expert', 
                               'Beginner','Intermediate','Expert',
                               'Beginner','Intermediate','Expert',
                               'Beginner','Intermediate','Expert',
                               'Beginner','Intermediate','Expert']
            }

data_df = pd.DataFrame(data_dict)

p = Bar(data_df, 
        values='numstudents', 
        label='language', 
        stack='skill_level',
        legend='top_right',
        title="ECEn 360 Student Self-Reported Programming Skills",
        tooltips=[('Students:', '@numstudents'), ('Language:', '@language')]
       )
show(p)
```

The plot builds and displays just fine. The problem I am having is with the tooltip information as illustrated in the upper left of the plot image below. Note that to the right of "Students:" is "???" rather than the number of students at that skill level for that language (in this case it should be the number 9). My understanding from the documentation is that '@numstudents' should refer to the column 'numstudents', but the tooltip doesn't pick up the value from the column as it should, and as it correctly does in the case of the 'language' column. 

<img width="300" alt="screen shot 2016-01-08 at 11 07 02 pm" src="https://cloud.githubusercontent.com/assets/4380622/12237550/7d87d1c0-b83c-11e5-9928-82a500256f72.png">

**Comment by rothnic** [comment]
@gregnordin: the bar chart aggregates data in a generic way while keeping context of that aggregation. I think currently the transformed value is `height`. Try that instead of numstudents.

You can see the transformed data as part of the chart.renderers[i].data_source.data.

**Comment by gregnordin** [comment]
@rothnic: perfect--that fixed the problem! I don't think I could have figured this out on my own from the docs, which led me to believe that I needed to reference the column in the original dataframe from which the chart was constructed, so I really appreciate your help!

**Comment by fpliger** [comment]
Yup... you have to improve this otherwise it's not really discoverable or usable atm. As a first step we could mention this in the docs (iirc it's not there) and then maybe add an alias so the aggretated cols can == `height`?

**Comment by gregnordin** [comment]
I've run into another issue. The code below (slightly modified from my original post, intended to be used in a Jupyter Notebook) creates the html file [Programming_Skills_ECEn360_Win2016.html.zip](https://github.com/bokeh/bokeh/files/89363/Programming_Skills_ECEn360_Win2016.html.zip). This file opens and displays just fine in Safari (8.0.7) and Chrome (47.0.2526.106) but in Firefox (43.0.4) it just opens to a blank page. I was hoping to share the file with colleagues, but can't send it if I can't be sure it will open in whatever browser they use. Any idea what's wrong?

	from bokeh.charts import Bar, show, output_notebook, output_file
	import pandas as pd

	output_notebook()

	data_dict = { 'numstudents' : [44, 24, 1, 
								   2, 56, 10, 
								   19, 10, 6,
								   15, 12, 3,
								   16, 11, 1,
								   15, 8, 2],
				  'language' : ['Matlab','Matlab','Matlab', 
								'C/C++','C/C++','C/C++', 
								'Java','Java','Java',
								'HTML/CSS','HTML/CSS','HTML/CSS',
								'Python','Python','Python',
								'Javascript','Javascript','Javascript'],
				  'skill_level' : ['Beginner','Intermediate','Expert', 
								   'Beginner','Intermediate','Expert', 
								   'Beginner','Intermediate','Expert',
								   'Beginner','Intermediate','Expert',
								   'Beginner','Intermediate','Expert',
								   'Beginner','Intermediate','Expert']
				}

	data_df = pd.DataFrame(data_dict)

	p = Bar(data_df, 
			values='numstudents', 
			label='language', 
			stack='skill_level',
			legend='top_right',
			title="ECEn 360 Student Self-Reported Programming Skills",
			tooltips=[('Students', '@height out of 70 students in class'), 
					  ('Language', '@language'), 
					  ('Skill Level', '@skill_level')]
		   )

	output_file("Programming_Skills_ECEn360_Win2016.html")

	show(p)

**Comment by bryevdv** [comment]
I just tested this and it shows up as expected on FF `44.0b6`. Is there any output in your browser console?

**Comment by bryevdv** [comment]
Also if it is easy for you  to compare with another version of FF that would be useful information.

**Comment by gregnordin** [comment]
In the FF console I get:

ReferenceError: Bokeh is not defined

**Comment by fpliger** [comment]
Mmmm.. it works for me on FF both on master and the official `0.11` package. On FF `43.0.1`

**Comment by gregnordin** [comment]
@bryevdv and @fpliger: I just tried opening the html file in Windows 7.

Firefox 43.0.4: works fine

Chrome 47.0.2526.106 m: 
    I get a blank page with console output as shown in the attached screenshot
<img width="1680" alt="screen shot 2016-01-13 at 12 38 41 pm" src="https://cloud.githubusercontent.com/assets/4380622/12305607/e78a3cc2-b9f2-11e5-9111-d1af85494121.png">

**Comment by bryevdv** [comment]
I suddenly wonder if there is an issue with our CDN provider.  I will get our IT folks to investigate. A couple of options:

* use inline resources

* specify http instead of https for cdn resources (possibly)

**Comment by bryevdv** [comment]
ping @tpowellcio (will open it-help ticket as well)

**Comment by bryevdv** [comment]
@gregnordin It does indeed seem like there may be some issue with our ability to serve `https` over CDN. This will require some investigation from people that know much more about network admin than I do. Before `0.11` the default resources were `INLINE`, which will always work, even without any network connection. I would recommend using inline resources as an immediate-term fallback.

**Comment by gregnordin** [comment]
@bryevdv Thanks for letting me know. Regarding `INLINE`, I can see that that will work fine on my system, but I had planned to simply email the html file to my department colleagues for them to look at. I suppose I could put copies of the css & jss files on one of my own servers and point to them from within the html file, otherwise I'm not sure how to approach it.

**Comment by bryevdv** [comment]
@gregnordin If you use `INLINE` resources, then the resulting document is *completely* self-contained.If you email or otherwise transmit it to someone, they will be able to view it even without a network connection. The downside of course is a bigger thing to send --- it will have BokehJS embedded inside of it.

**Comment by gregnordin** [comment]
@bryevdv Sorry, I looked at this too quickly and confused inline with local :). Thanks for the clarification!

**Comment by gregnordin** [comment]
Yes, `output_file(<filename.html>, mode='inline')` works great! The resultant html file has no problems in any browser I've tried on Mac OS X and Windows 7.

**Comment by bryevdv** [comment]
@gregnordin great! We will get to the bottom of the intermittent CDN issue as quickly as we can.

**Comment by tpowellcio** [comment]
Looks like NetDNA who we currently link to changed their name to MaxCDN which has broken all our CDN links. https://www.maxcdn.com/blog/netdna-maxcdn-enterprise/
I will need the new URL that you want me to point cdn.pydata.org to in order to fix this.
Who has the credential of the old NetDNA account that can get me the new target URL?

**Comment by aiguofer** [comment]
wooo! I was looking around everywhere for this... 
looking at `chart.renderers[0].data_source.data` did the trick, although I was using a `Donut` so I needed to use `values` instead. Is this expected to change, or should there be some documentation around this?

**Comment by jonc125** [comment]
There definitely needs to be better documentation - I've just lost several hours trying to make this work for a `Donut` too. A few things I noticed:
* the documentation for `Donut` has a typo so that `hover_tool` is not documented on its own line.
* the `hover_tool` and `hover_text` options don't actually work, because they call `chart.add_tooltips` after `create_and_build` has called `chart.start_plot()` which is when the tooltips added via `add_tooltips` are read - if the list is empty at that point, a `HoverTool` is not created. So you have to use the `tooltips=` keyword argument to get any hovering happening.
* the examples for `Donut` therefore don't have any hover tooltips working.

**Comment by bryevdv** [comment]
@jonc125 there's currently not really an active maintainer for `bokeh.charts`, so any efforts you can provide to improve things there would certainly be appreciated. I can suggest perhaps looking at `bokeh.plotting` as an alternative, which is robust, stable, and well supported and demonstrated.

**Comment by jonc125** [comment]
I've created a PR with the fixes mentioned above, but will look at `bokeh.plotting` for future work.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/24)
