### ISSUE TITLE
Wrong BOKEH_RESOURCES argument in Developing Examples section for server demos

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#3622]
From http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#bokeh-dev:

"""
For Bokeh server examples, add BOKEH_DEV=true to the server invocation:

``` bash
BOKEH_DEV=true bokeh serve example-server.py
```

"""

Needs to set BOKEH_RESOURCES=server-dev (not absolute-dev) because the served plots aren't able to resolve the full paths of the js/css resources and need them as a URL.

**Comment by rothnic** [comment]
I'd like to add after working with server and bokehjs, it is kind of difficult at the moment. I'm going to list my understanding here that I had to find out by poking around, so feel free to correct me as needed. This information could be useful in the developers guide.

* Source maps don't work with server, get warnings about the maps referencing files not available, which may be associated with the following issues
* When using BOKEH_RESOURCES=server-dev, this tells server to use the bokeh/bokeh/server/static folder, which is only updated from setup.py (which is called by gulp install), which seems to defeat the purpose of the development mode
* --debugjs isn't currently accepted, which was previously used to turn on some of this functionality
* if server has to use the static folder, there is no gulp task that assists with building any changes and updating that folder while doing development with server and bokehjs
* the coffeescript source maps are not being generated ( i think this would appear as comments within the compiled js files)

This may need to go in another issue, but I see this as the development documentation for server is no longer valid.

**Comment by bryevdv** [comment]
previous text is now gone, nothing to update
