### ISSUE TITLE
Support swapping of axes/ranges without re-creating entire plot

### ISSUE THREAD

**Issue by rothnic** [bokeh/bokeh#3626]
This example server app simplifies what I am doing to support interactive charts. Based on the data selected, new ranges and axes can be required. 

https://gist.github.com/rothnic/18371807da60b288166f

This app renderers fine the first time, but on selector change to 'c' the axis will be changed to a CategoricalAxis. The initial error exists on the bokehjs side in axis.coffee, in the _computed_bounds method when get('ranges') results in [undefined, undefined].

An alternative approach I took was to leave all axis types in renderers and just setting visible the one I want to show. This also resulted in errors on the bokehjs side, but I was able to fix the error by adding `@_last_size = 0` below this line: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/renderer/guide/axis.coffee#L363

**Comment by rothnic** [comment]
Tracing the issue is kind of difficult with server at the moment, so documenting what I see so someone else doesn't have to trace through as much.

When `get('ranges')` is called, that results in calling `this._ranges` [in axis.coffee](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/renderer/guide/axis.coffee#L396). In that method, `get('dimensions')` is called, which refers to `@_dim`, which is set in [initialize_layout](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/renderer/guide/axis.coffee#L324). Within that method, it seems like the axis that I swap out has a side of `undefined` for [layout_location](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/renderer/guide/axis.coffee#L337).

`layout_location` seems to come from plot.coffee when checking [layout](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/plot.coffee#L712). 

So, it appears that the new axis isn't getting initialized for some reason, which I assume happens for each renderer, considering I don't see the issue when I just leave all the axes in the renderers and only set visible the one I want to see. I don't currently see where the new axis is being skipped over.

**Comment by rothnic** [comment]
What it appears that is happening is as the changes are made on the app side to swap out the axes, server immediately applies them, then bokehjs tries to update the renderering. It seems like the updates need to be delayed, and/or bokehjs needs to be less sensitive to missing ranges. What I'm not sure of is if the changes were delayed and sent at once if that would be rendered without errors on the bokehjs side.

**Comment by poeticcapybara** [comment]
Would that mean that the gist is already working, i.e., you can swap axis type? The gist is not working for me with 0.11.1
