### ISSUE TITLE
Charts: axis locations are not configurable

### ISSUE THREAD

**Issue by dloss** [bokeh/bokeh#3627]
In Bokeh 0.11.0 the Charts API (e.g. HeatMap) always places the xaxis `below` and the yaxis on the `left`. See `Chart.create_axes()`.

This should be configurable, so that the xaxis can be placed `above` and the yaxis on the `right`.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/23)
