### ISSUE TITLE
User Defined Models not working when embedding plot with `components`

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3632]
Doesn't seem like `User Defined Models` work when using `components` to embed plots.  In my case I was using a jinja template with BokehJS being imported from the CDN.  

The example below outputs an html file. I'm doing the jinja template rendering manually to reproduce my situation of having a pyramid server doing the template rendering.  The example throws the JS Error:

```
Uncaught Error: Module 'CustomTileSource' does not exists. The problem may be two fold. Either a model was requested that's available in an extra bundle, e.g. a widget, or a custom model was requested, but it wasn't registered before first usage.
```

```python
from bokeh.plotting import figure
from bokeh.models import Range1d, TMSTileSource
from bokeh.models import  WheelZoomTool, PanTool
from bokeh.embed import components

from jinja2 import Environment

class CustomTileSource(TMSTileSource):
    __implementation__ = """
    _ = require "underscore"
    Util = require "util/util"
    TMSTileSource = require "renderer/tile/tms_tile_source"
    class CustomTileSource extends TMSTileSource.Model

      type: "CustomTileSource"

      initialize: () ->
        @set('x_origin_offset', 0)
        @set('y_origin_offset', 0)
        @set('initial_resolution', 134217.728)
        super

    module.exports =
      Model: CustomTileSource
    """

from bokeh.resources import EMPTY
EMPTY.render()

html_template = """
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Embed Example</title>
        <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.11.0.min.css" type="text/css" />
        <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.11.0.min.js"></script>
        {{ bokeh_script|safe }}
    </head>
    <body>
    {{ plot | safe }}
    </body>
</html>
"""

x_range = Range1d(start=0, end=1200)
y_range = Range1d(start=0, end=800)

custom_service = 'http://localhost:8081/tiles/{filter_size}/{band}/{Z}/{X}/{Y}.png?clim=0.0,70.0'
extra_url_vars = {}
extra_url_vars['filter_size'] = '1.024'
extra_url_vars['band'] = '0'

tile_source = CustomTileSource()
tile_source.url = custom_service
tile_source.extra_url_vars = extra_url_vars

p = figure(x_range=x_range, y_range=y_range, plot_height=800, plot_width=800)
p.add_tools(WheelZoomTool(), PanTool())
p.add_tile(tile_source)

script, div = components(p)

content = Environment().from_string(html_template).render(bokeh_script=script, plot=div)

with open('example.html', 'w') as f:
    f.write(content)
```

**Comment by brendancol** [comment]
ping @mattpap

**Comment by birdsarah** [comment]
Not sure this'll work, but try:
* no safe on the div
* put the script after the div

I have also never seen that use of Environment(), but I'll assume you know what you're doing and that's not the problem (I'm not super familiar with Jinja).

**Comment by brendancol** [comment]
@birdsarah thanks for suggestions, but no dice.  Looking at the output script, the __implementation__ isn't present.  I'm a bit confused on how `Resources` works.  I could imagine that somewhere I need to explicitly add my new model, but not sure.  Components used to take `resources` as an argument, but that is now deprecated, and I'm not using `file_html` which I believe also takes a `resources` argument.

**Comment by birdsarah** [comment]
I have a sort-of fix for you.

https://github.com/birdsarah/bokeh-miscellany/blob/master/tests/3632_user_defined_models_components/bird_test.py

Results: https://rawgit.com/birdsarah/bokeh-miscellany/master/tests/3632_user_defined_models_components/bird_test.html

Where the js for User Defined Models comes from is still a bit of a mystery to me, but the embed method `_bundle_for_objs_and_resources` returns something you can use in place of resources to get your custom models.

Having said that, if I was wanting to use components, I would find this solution unsatisfactory as if I was building a site, I wouldn't want this coupled to loading resources.

Still digging.

**Comment by brendancol** [comment]
Great! Sounds fine for my purpose, although I just worry about longer term support.  Last round we got stuck unable to upgrade bokeh. @mattpap what do you think?

**Comment by birdsarah** [comment]
Please ignore above. You had the right idea with EMPTY.render() but it was in the wrong place.

Please see solution here: https://github.com/birdsarah/bokeh-miscellany/blob/master/tests/3632_user_defined_models_components/from_issue_solved.py

Here's the important bits:

1) Pass EMPTY to your template
````python
content = Environment().from_string(html_template).render(bokeh_script=script, plot=div, EMPTY=EMPTY)
```
2) Render in template, make sure you include the "bokeh-compiler" from CDN

````html
        <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.11.0.min.js"></script>
        <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-compiler-0.11.0.min.js"></script>
        {{ EMPTY.render()|safe }}
        {{ bokeh_script|safe }}

````

**Comment by brendancol** [comment]
holy moly! thats great!

**Comment by birdsarah** [comment]
I've closed this, but we may want to start a new issue, to make this work with components, but that's probably a fresh discussion. 

At the least we want to document this.

**Comment by fpliger** [comment]
@brendancol @birdsarah did this end up on a new issue? It'd be good to not loose track of this.

**Comment by birdsarah** [comment]
@fpliger thanks for the kick - see #3665

**Comment by fpliger** [comment]
sweet! thanks
