### ISSUE TITLE
anaconda still installs 0.10 instead of 0.11

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3634]
when installing bokeh via `conda create -n bokeh_env anaconda` version 0.10 is still install instead of 0.11

**Comment by damianavila** [comment]
I guess this would be solved with the next release of anaconda...

**Comment by bryevdv** [comment]
That's irrelevant, it should still be in the main repo and conda installable.

**Comment by damianavila** [comment]
>That's irrelevant, it should still be in the main repo and conda installable.

Both things are true... but I understand from @brendancol that he wanted the latest Bokeh installing anaconda and AFAIK, that will not happen until the anaconda metapackage is updated... and that, I guess, only happens with the anaconda release... although I could be missing something else.

**Comment by bryevdv** [comment]
Sorry I missed the "anaconda" part on a wrapped line on my phone. Agreed this can be closed.
