### ISSUE TITLE
Timeseries: Downsampling on server, chart pan and zoom slow even with LOD, and WebGL rendering problem

### ISSUE THREAD

**Issue by nothinkelse** [bokeh/bokeh#3635]
Hi. I have came to bokeh mainly for "high-performance interactivity over very large or streaming datasets" as stated in description. I started learning with bokeh just 2 days ago. Thus I started already with the currently newest version 0.11.0. 

I have a time series where events occur with frequency around 1 second. Thus for one week it is 7x24x3600=604 800 points. Thus downsampling data automatically on server and (in case of zoom) only sending the visible data to web browser is a very interesting feature. 

1) Is there any documentaiton on how to achieve downsampling of data on server with the new tornado bokeh server? (anything? I am willing to dig into it. I need to solve this issue for my project anyway)

2) Additional idea: would it be possible to write my own down-sampling function? E.g. on each zoom/pan my function with arguments such as current view window x,y,xwidth,ywidth would be called and my function would return a data to be plotted? Otherwise a situation might occur when the "default downsampling method" provided by bokeh might not be what people need.

I also like very much the LOD and WebGL functions in web browser. 

3) However even with LOD I still experience slow zooming. Is is possible to set how much the LOD should downsample the data? Or is it possible that LOD is not simplifying the data enough by default?
Here is an example:
      
      import numpy as np
      import matplotlib.pyplot as plt
      days=10
      pointsPerSecond=1
      numpoints=days*24*3600
      
      xx=np.arange(numpoints)
      randomPoints=np.random.rand(numpoints);
      randomPoints=randomPoints-0.5;
      timeseries=np.cumsum(randomPoints);
      print timeseries.nbytes/1024/1024, randomPoints.nbytes/1024/1024
      from bokeh.plotting import figure, show, output_notebook,output_server
      
      p = figure(title="Server Plot",webgl=False)
      p.line(x=xx,y=timeseries)
      output_server("test3")
      
      show(p)

![image](https://cloud.githubusercontent.com/assets/6547340/12264674/971a1308-b938-11e5-8f39-0531b30bedc3.png)

And it looks like this when zooming with the mouse scroll. Is it possible that even after LOD there are too many points? Zooming for this example is slow, choppy. (Running in chrome Version 47.0.2526.106 m, windows, Bokeh 0.11.0):

![image](https://cloud.githubusercontent.com/assets/6547340/12264689/bc387206-b938-11e5-8ac4-060b732e43b1.png)

4) When trying this with WebGL the rendering looks wrong:

Thse same code but reduced number of points *10 fold* (otherwise it was too slow) and enabled WebGL:

      import numpy as np
      import matplotlib.pyplot as plt
      ###reduced number of points to render 10-fold
      days=1
      pointsPerSecond=1
      numpoints=days*24*3600
      
      xx=np.arange(numpoints)
      randomPoints=np.random.rand(numpoints);
      randomPoints=randomPoints-0.5;
      timeseries=np.cumsum(randomPoints);
      print timeseries.nbytes/1024/1024, randomPoints.nbytes/1024/1024
      from bokeh.plotting import figure, show, output_notebook,output_server
      
      ###enabled WebGl
      p = figure(title="Server Plot",webgl=False)
      p.line(x=xx,y=timeseries)
      output_server("test3")
      
      show(p)

Result:

![image](https://cloud.githubusercontent.com/assets/6547340/12264811/886af056-b939-11e5-9dfb-c09da1096f9e.png)

X axis zoomed approx. 4 times, looks a bit better, but still not what one would expect:

![image](https://cloud.githubusercontent.com/assets/6547340/12264932/50d19888-b93a-11e5-901b-2e7b7bde21b6.png)

X axis zoomed 4 times again (16 times in total):

![image](https://cloud.githubusercontent.com/assets/6547340/12264945/690a9f30-b93a-11e5-9b8a-ed8416794e6d.png)

The  problems 3 and 4 would be probably avoided if down-sampling on the server occured.

**Comment by molszowy** [comment]
Hi team,

Our project heavily rely on Bokeh now but we want to use server-side downsampling as we have large datasets. I was searching everywhere and there is no documentation or comment whether this is really supported in 0.11 or not. Could someone let us know if this is implemented ? any examples much appreciated.

**Comment by bryevdv** [comment]
@molszowy Downsampling is highly specific to the application. It depends on many factors, the dimensionality of the data, what qualities you care to preserve most when downsampling, etc. The Bokeh Server is capable of running arbitrary python code in plot/data app callbacks. This makes it an *enabling technology* for users to easily implement their own kind of downsampling appropriate for their particular situation. 

That said, I would very much like to add some examples of "common" situations, help get people started. But as you can see we are about to hit 700 issues on the tracker. There are alot of users, and not very many developers, so work is absolutely rate-controlled by human limitations at the moment. Help and contributions are incredibly appreciated, more than ever. (I'm going to message the public mailing list later today to ask about how we can encourage more developers to join the project)

I will also mention a new project called DataShader has been created under the Bokeh GH organization. It's aim is to be able to automate, or at lease make the spelling of downsampling incredibly easy for very large (100s of millions of points or more), for some specific kinds of data sets.

A good place to start is the [DataShader GitHub repo](https://github.com/bokeh/datashader), and in particular, you might find this example notebook interesting: https://github.com/bokeh/datashader/blob/master/examples/nyc_taxi.ipynb  Finally I will mention that the DataShader team is having a webinar next week, you can find more information [here](http://go.continuum.io/datashader/)

**Comment by almarklein** [comment]
I confirmed the issue with webGL. The miter limit was not applied correctly, this is fixed in #3888.

**Comment by bryevdv** [comment]
@almarklein can this be marked completed? Do we need to split off separate issues?

**Comment by almarklein** [comment]
Let's consider the OP's questions/remarks:

> 1) Is there any documentaiton on how to achieve downsampling of data on server with the new tornado bokeh server?

I recon that the [server app examples](http://bokeh.pydata.org/en/latest/docs/gallery.html) are a good place to start. @bryevdv I think we might have other demos/examples related to downsampling of data on the server?

> 2) Additional idea: would it be possible to write my own down-sampling function? 

Unless I misunderstand the question, I'd answer the same as above.

> 3) However even with LOD I still experience slow zooming. Is is possible to set how much the LOD should downsample the data?

Yes: http://bokeh.pydata.org/en/latest/docs/reference/models/plots.html#bokeh.models.plots.Plot.lod_factor

> 4) When trying this with WebGL the rendering looks wrong:

This is now fixed.

**Comment by bryevdv** [comment]
I think this can be closed. I would also point the user at https://github.com/bokeh/datashader which is now probably en even better solution, and has explicit examples of large timeseries downsampling.
