### ISSUE TITLE
TravisCI failing every py27 examples test 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3636]
ping @mattpap 

I can't tell if it is `examples/glyphs.py` or `examples/glyph.ipynb` that is the problem. It ostensibly finishes the notebook, and crashes a few tests later while or after writing output for `glyphs.py`, but then it spits out a bunch of log/debugging that seems to be from the `glyph.ipynb` notebook. It is currently impossible to merge any PRs with clean tests now this happens every test run.

Ref: https://travis-ci.org/bokeh/bokeh/jobs/101701413#L1469

**Comment by canavandl** [comment]
The issue appears related to a regression in phantomjs@1.9.8. See issues:

https://github.com/n1k0/casperjs/issues/1068
https://github.com/ariya/phantomjs/issues/12697

In our test system we launch phantomjs (with glyph.py as a arg) as a subprocess and listen to stdout for a potential response.status='fail'. The regression in phantomjs causes a warn to be captured several times:

```
Unsafe JavaScript attempt to access frame with URL about:blank from frame
with URL file:///Users/lcanavan/dev/bokeh/examples/glyphs.html.
Domains, protocols and ports must match.
```

Then we try to pass this list of responses to python's json.decode which raises an exception.

The phantomjs folks didn't seem to get it fixed until the 2.0.0 release. The most recent phantomjs version in the npm package in our bokeh channel appears to only have 1.9.19, so we're running a buggy version.

There seem to be three solutions (I tested no. 1 and no. 3 locally):
1. Downgrade to phantomjs@1.9.7-15
2. Update npm and upgrade to phantomjs@2.0.0 (sort of assuming it's stable)
3. Add a '--web-security=false' flag to the phantomjs cmd (which silences these warns)

I vote for no. 1 (seems easiest)
