### ISSUE TITLE
Would need a Figure.step to create step line in plot

### ISSUE THREAD

**Issue by ChristianTremblay** [bokeh/bokeh#3644]
There's actually a step chart but I didn't find a way to simply add a step line to a Figure.

**Comment by dariemp** [comment]
I also need this

**Comment by tmandry** [comment]
Is there any way of doing this? Or does it require changing data in the arrays, like [this](http://stackoverflow.com/a/34888365)?

**Comment by bryevdv** [comment]
Came up recently, I think a `Step` glyph is warranted.

**Comment by SpinOneThird** [comment]
I would like to see this implementd. It is very useful in timeseries plotting, where linearly interpolating is misleading because it uses information from the future to plot between points.

**Comment by bryevdv** [comment]
Basic support (drawing only no hit testing) is merged Future work/requests should go in new issues
