### ISSUE TITLE
Discussion: Moving to document-unaware layouts (HBox, VBox, Tabs)

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#3650]
Issue:

"Dumb" layout widgets (HBox, VBox, Tabs) don't work with the `bokeh serve` command because they don't get added to Document. (note: by "dumb" I mean the layouts that are unaware of the document state)

```python
from bokeh.plotting import figure, output_file, show, curdoc
from bokeh.io import hplot
from bokeh.models.widgets import HBox, Panel, Tabs

# output to static HTML file
output_file("layout.html")

# add a circle renderer with a size, color, and alpha
p1 = figure(plot_width=400, plot_height=400)
p1.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

# add a patch renderer with an alpha an line width
p2 = figure(plot_width=400, plot_height=400)
p2.patch([1, 2, 3, 4, 5], [6, 7, 8, 7, 3], alpha=0.5, line_width=2)

HBox(p1, p2)
### results in implicit vplot(p1, p2) as `p1` and `p2` are added sequentially to curdoc, not the HBox
```

In order to get the "dumb" models to work, it's necessary to:
* Remove the children roots (here `p1` and `p2` from the document
* Add the layout (containing the children) to the document
(this is what the convenience hplot/vplot classes do)

Confusingly, using "dumb" layouts as a script:

```python
show(Tabs(tabs=[Panel(child=p1), Panel(child=p2)]) ### Works fine

show(HBox(p1, p2) ### raises validation error
ERROR:/Users/lcanavan/dev/bokeh/bokeh/core/validation/check.py:W-1004 (BOTH_CHILD_AND_ROOT): Models should not be a document root if they are in a layout box: Figure, ViewModel:Plot, ref _id: 1009, Figure, ViewModel:Plot, ref _id: 1033
```

This is an inconsistent interface as both "dumb" models should have the same behaviour.

The convenience layouts hplot and vplot work as expected for scripts and bokeh serve, but their naming isn't very good (they can hold more than just plots). There is no similar 'tab' convenience layout.

Proposal -

* Deprecate hplot and vplot
* the `show` command should accept 'dumb' layouts and modify the document accordingly (remove the child roots from the document and add the layout)
* the ``bokeh serve`` interface should include explicitly adding 'dumb' layouts as roots and modify the document accordingly 
* However, if there are no roots added to the document, bokeh could make a "best guess" of the components to include (and issue a warn)

Semi-related: this would solve the error raised when
```python
layout = hplot(p1, p2)
show(p1)
```
(Because the `hplot` command adds both plots to the curdoc)

Unresolved -
* What to do with Figure vs figure?

**Comment by canavandl** [comment]
ref issue #3138

**Comment by birdsarah** [comment]
Confirm as part of #4392.

Also will make a seperate issue to deal with tabs

**Comment by bryevdv** [comment]
@canavandl @birdsarah what if anything is left to do here?

**Comment by birdsarah** [comment]
No, I believe this is all good:
*  Row & Column and the new layout functions (bokeh.layouts.layout & bokeh.layout.gridplot) all work with bokeh server
* Tabs alone works with server, Tabs in a Column works with server

There is a separate issue already open to deal with the fact that tabs only work in fixed mode (#4404)

Fixed in #4343

**Comment by JasonSickler** [comment]
I've found that, running through a Bokeh Server, the Tabs widget will not work if no panels contain a figure.  Specifically, this works:

```
p1 = figure()
tab1 = Panel(child=p1, title="circle")

p2 = Button(label="Button 2", button_type="success")
tab2 = Panel(child=p2, title="line")

tabs = Tabs(tabs=[ tab1, tab2 ])
```

And this change to the first line (swapping a button in for the figure) fails to make the tabs, putting the contents of the tab panels into a single column:

```
p1 = Button(label="Button 1", button_type="success")
tab1 = Panel(child=p1, title="circle")

p2 = Button(label="Button 2", button_type="success")
tab2 = Panel(child=p2, title="line")

tabs = Tabs(tabs=[ tab1, tab2 ])
```

**Comment by bigreddot** [comment]
@JasonSickler This has been noticed by a few people very recently, can you open a new issue for this?

**Comment by JasonSickler** [comment]
Opened a new issue:  #5169
