### ISSUE TITLE
Unifying Bokeh and BokehJS project structure

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#3651]
Proposed
* [x] Remove ar (AbstractRendering) #3663
* [x] Remove HasParent class (move display_defaults into defaults)
* [x] Make BokehJS class structure match Bokeh class structure
* [x] Make BokehJS project structure match (python file glyphs.py -> glyphs/ dir on bokehjs)
* [x] Move "Spec" handling code "down" from `GlyphRenderer`
* [x] Align JS and python model properties (private JS props explicitly stored)

**Comment by canavandl** [comment]
Bokeh class structure:

* HasProps
  * Model
    * Component
      * Plot
      * Widget
        * specific widgets
    * Glyph
      * specific glyphs...
      * Marker
        * specific markers...
    * Renderer (is just an abstract base class)
      * Annotation
        * specific annotations...
      * GuideRenderer
        * Axis
        * Grid
    * TileSource
      * specific tiles...
    * Tool
      * specific tools...

BokehJS class structure:

* HasProperties
  * Plot (not subclass of Component)
  * Component
    * Widget
      * specific widgets
  * Glyph
    * specific glyphs...
    * Marker
      * specific markers...
  * Annotation
    * specific annotations...
  * GuideRenderer
    * Axis
    * Grid
  * TileRenderer
    * specific tile stuff...
  * Tool
    * ButtonTool
      * ActionTool
        * specific tools
      * GestureTool
        * specific tools
      * InspectTool
        * specific tools

Proposal -

1. Add `Model` as abstract base class of `HasProperties` to BokehJS
2. Remove `Renderer` abstract base class in Bokeh (have subclasses just inherit from `Model`)
  * To me, `Renderer` doesn't add much clarity over `Model` and only causes the code to diverge (i.e. is an Annotation a model or a renderer?)
3. Is it worth unifying the `Plot` and `Component` relationship?

**Comment by bryevdv** [comment]
Some possible observations: 

* rename JS `HasProperties` to `HasProps`
* Renderer` could be used to identify anything that draws to the canvas
* `Component` could be used to identify anything that could be layed-out (as DOM elements)
* There's more to the data sources hierarchy?
* There's also things like tickers and tick formatters

**Comment by bryevdv** [comment]
I would say the `HasProperties` -> `HasProps` rename, and adding `Model` base to BokehJS are not problematic or controversial, and could happen immediately as their own PR. In general we should do this work incrementally in any case.

**Comment by canavandl** [comment]
This is pending #3662 (removing HasParent)

**Comment by bryevdv** [comment]
Another thought: `Renderer` is where all the code to handle data specs, visual properties, etc, should go

**Comment by canavandl** [comment]
Current directory structure for bokeh and bokehjs

Bokeh
* application
  * ...
* charts
  * ...
* client
  * ...
* command
  * ...
* core
  * compat
  * validation
  * properties
  * more? query/state/templates
* models
  * widgets
    * specific widgets
  * annotations
  * callbacks
  * guides
  * glyphs
  * layouts
  * mappers
  * markers
  * plots
  * renderers
  * sources
  * tickers and tick_formatters
  * tiles
  * tools
* plotting (called api on bokehjs)
  * figure/helpers
* sampledata
  * ...
* server
  * ...
* sphinxext
  * ...
* themes
  * ...
* util
  * normal util stuff (logging, dependencies)
* colors (color util)
* document
* driving
* embed
* io (show/output_* stuff)
* model (Model base class in top-level of bokehjs)
* palettes
* resources (JS and CSS stuff)
* settings (environmental vars stuff)
* tile_providers

bokehjs/src/coffee:
* api (plotting on Bokeh side)
  * figure, plugin
* callback
  * customjs and open_url
* common (core on bokeh side?)
  * properties
  * some component stuff (component, layout_box, grid_plot, plot)
  * some events stuff
  * more?
* compiler
* layout
  * specific layouts...
* mapper
  * specific mappers...
* palettes
  * specific palettes
* range
  * specific ranges...
* renderer
  * annotation
    * specific annotations...
  * glyph
    * marker
      * specific markers...
    * specific glyphs...
  * guide
    * specific guides...
  * tile
    * specific tiles
    * some tile source stuff that should move to ../source
* source
  * specific sources...
* ticking
  * specific tickers...
  * specific tick_formatters...
* tool
  * actions
    * specific tools
  * gestures
    * specific tools
  * inspectors
    * specific tools
* util
  * couple of util modules
* widget
  * specific widgets...
api.coffee
main.coffee
model.coffee

**Comment by bryevdv** [comment]
Suggest a first PR that adds: `src/coffee/models` and moves things there as appropriate

**Comment by mattpap** [comment]
@bryevdv, @canavandl, this PR should include changing singular form to plural.

**Comment by canavandl** [comment]
Yup - will do @mattpap

**Comment by canavandl** [comment]
bokehjs has a "ticking" directory that contains what would be "tickers" and "formatters" on the bokeh side. Is it worth breaking the coffee files into two directories? @bryevdv

**Comment by bryevdv** [comment]
@mattpap changing what? the directory is already plural (on the python side) and should be on the JS side as well. There is just `model.coffee` which is singular because it contains the class `Model`.

**Comment by mattpap** [comment]
@canavandl, my directory structure for bokeh is different: no `guides` but `axes` and `grids` in `models/`. Where this comes from? I have most recent bokeh's `master`.

**Comment by canavandl** [comment]
@mattpap you're right. I was getting sloppy on my note taking and mentally grouped them all into guides. I'll fix the above comment.

**Comment by mattpap** [comment]
@bryevdv, I was referring to `git mv bokehjs/src/coffee/callback/customjs.coffee bokehjs/src/coffee/models/callbacks/customjs.coffee` (etc.)

**Comment by mattpap** [comment]
Or more readable: `coffee/callback -> coffee/models/callbacks`.

**Comment by bryevdv** [comment]
Yup, everything that is a model should go somewhere under `src/coffee/models`

**Comment by canavandl** [comment]
yes - and the sub models/ directories will be plural i.e. models/widgets and models/tickers

**Comment by mattpap** [comment]
@bryevdv, still not the thing, callback -> callback**s**.

**Comment by bryevdv** [comment]
I'm agreeing with you (apparently not very clearly)

**Comment by mattpap** [comment]
OK. On a side note, I should have used the one with bold face from the beginning.

**Comment by canavandl** [comment]
The stated goals (AFAIK) have been completed. This can be reopened if I am wrong.
