### ISSUE TITLE
Dropdown widget example is clipped in docs

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#3654]
http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#dropdown-menu

<img width="388" alt="screen shot 2016-01-14 at 3 50 15 pm" src="https://cloud.githubusercontent.com/assets/543576/12337191/8bfd8a3c-bad6-11e5-9da7-ee4a3f5a2e64.png">

**Comment by bryevdv** [comment]
dupe of #2549
