### ISSUE TITLE
Provide an interface to clip grid lines in both dimensions

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3655]
From @pzwang - if we change Grid.bounds to accept not just a tuple of (start, end), but actually take 2 tuples that define a rectangle, then we could clip the grid lines in the transverse dimension as well

@birdsarah - would this be better expressed in offset or % on the transverse

@bryevdv - I'd rather find another property name, the problem with having to give two tuples is its very hard to remember what it is what ... bounds and xbounds, "extent"?

**Comment by birdsarah** [comment]
This would mean in a plot like below, the horizontal grid lines could be prevented from extending all the way to the right (if you wanted to)

<img width="785" alt="screen shot 2016-01-14 at 1 15 19 pm" src="https://cloud.githubusercontent.com/assets/1796208/12337791/fe3f1be4-bac0-11e5-8a97-8bbace2ecc6d.png">

**Comment by birdsarah** [comment]
@pzwant: I suggested “transverse” because
 (1) it’s generic across the orientation of the grid, and 
 (2) it’s transverse to the main data dimension of the grid.  i’m not in love with that term, tho.

what about `clip_lines` or something along those lines? `line_clipping`, etc.

**Comment by bryevdv** [comment]
There just has not been any real community expression of interest in this in ~6 years, so I will close now.
