### ISSUE TITLE
seaborn.lmplot fit_reg=False produce no output with warning

### ISSUE THREAD

**Issue by danaki** [bokeh/bokeh#3657]
On a standalone Flask application based on flask example:
```python
@app.route("/")
def index():
    args = flask.request.args

    df = pd.DataFrame({'production_year': [1,2,3], 'price': [4,5,6]})
    sns.lmplot("production_year", "price", data=df, fit_reg=False)
    fig = mpl.to_bokeh()

    js_resources = INLINE.render_js()
    css_resources = INLINE.render_css()

    script, div = components(fig, INLINE)
    html = flask.render_template(
        'embed.html',
        plot_script=script,
        plot_div=div,
        js_resources=js_resources,
        css_resources=css_resources,
        _from=_from,
        to=to
    )
    return encode_utf8(html)
```

A grey square box with no output in it is produced with "Bokeh: could not set initial ranges" in JS console.

If fit_reg=True, then a regression line with no points is produced (seems ok and no JS warning).

(What I need is a simple scatter plot with jitter on x axis whish Bokeh doesn't support at the time?)

**Comment by bryevdv** [comment]
Bokeh relies on a third party module, `mplexporter` to provide limited Matplotlib (and hence Seaborn) compatibility. Better compatibility support depends on the completion of "Matplotlib Enhancement Proposal 25", which is outside of our control. 

Bokeh can certainly produce scatter plots trivially with its native APIs. If there is a way to get the actual data points of of Seaborn, I would suggest using them to create a Bokeh scatter plot directly.

**Comment by danaki** [comment]
Scatterplot in bokeh works, I just need some jitter which it doesnt provide. Seems that I need to do some jitter data modifications by myself. Please close this issue or convert it to feature request.

**Comment by bryevdv** [comment]
I think jitter is covered by #181 which we hope to get to soon.
