### ISSUE TITLE
Bar Plot plotting one value

### ISSUE THREAD

**Issue by afDeathscythe** [bokeh/bokeh#3661]
Hi,

I have discovered following "Bug".
If I have an array looking like this:

```
types = ["car","car","car","car"]
```

and then trying to plot a barplot to look how many and which items in the array exist like this:

```
output_file("Types.html")
typePlot = Bar(types, title="types", tools=TOOLS, xlabel="Types", ylabel="Frequency")
tP = vplot(hplot(typePlot))
show(tP)
```

I get the plot which i expected but if there is only one type of value in the array it does not write the name of the type under the bar as it does with normally two or more different types of values in the barplot.
I hope you can fix this.

Regards,

Marko

**Comment by almarklein** [comment]
That example code does nothing for me. This works, and shows the problem om my machine:
``` python

from bokeh.charts import Bar, output_file, show

types = ["car","car","car","car"]#, "duck", "duck", "cat"]

# Count occurances
df = dict(types=[], counts=[])
for name in set(types):
    df['types'].append(name)
    df['counts'].append(types.count(name))

output_file("Types.html")
typePlot = Bar(df, values='counts',label='types', title="types", xlabel="Types", ylabel="Frequency")
show(typePlot)
```
