### ISSUE TITLE
display image and color scale data in single plot/PNG

### ISSUE THREAD

**Issue by nikhartman** [bokeh/bokeh#3670]
I know this issue has been brought up in various forms here already, but I wanted to at least leave this notebook here. 

http://nbviewer.ipython.org/github/nikhartman/folkbooks/blob/master/bokeh_color_scales.ipynb

The real important issue isn't to be able to plot a "color bar" in the same style as matplotlib; it is to be able to display+save information about the color scale along with the plotted data. I'm open to any ideas that meet those conditions. 

Color bars are clearly mentioned in the future goals of this project, but what can we throw together now that gets me something I can use?

**Comment by birdsarah** [comment]
Thanks for documenting this @nikhartman, @bryevdv, is there a useful place in our collective consciousness for something like this? I know we want to implement colorbar, but in the meantime, this is a useful gist.

**Comment by birdsarah** [comment]
@SimonBiggs also did something similar here: https://simonbiggs.github.io/electronfactors see issue #1441.

**Comment by bryevdv** [comment]
FAQ for now maybe? I'd really like to try to bang out a UDF for a new axis or annotation type very soon.

**Comment by nikhartman** [comment]
What I started out thinking I wanted was the simplest working version of a colorbar as seen in @SimonBiggs plot. In the end, it still wasn't quite what I'd hoped for because of the inability to save that color scale information in a clear way. Maybe there isn't a good way to do it now.

I'll be glad if someone gets some use out of the notebook for now.

**Comment by bryevdv** [comment]
Closing this as a real `ColorBar` has been added to Bokeh some time ago (with Users Guide docs and examples)
