### ISSUE TITLE
Defining a JS callback using Python for Python 2.x

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#3675]
Since Flexx is currently  only available for Python 3.x, The CustomJS as Python functionality is only available on Python 3.x. Tasks needed to fix this:

* [x] Make Flexx' code work on Python 2.7 (https://github.com/zoofIO/flexx/pull/79)
* [x] Make Flexx' commonast module produce correct code using the ast module of Python 2.7
* [x] Make Flexx' test suite pass on Python 2.7
* [x] Update code in Bokeh that warns on 2.x
* [x] Update Bokeh's docs
* [x] Update pyscript to use JS-specific namespace (https://github.com/zoofIO/flexx/issues/76)
* [x] Update pyscript to use bound methods (avoid `that = this` stuff)
* [x] Flexx new release
* [ ] ~~Create conda package for Flexx~~
* [x] Change how legacy py is supported, to an approach that does not require translation, so we can make a noarch package.
* [x] Flexx release again (v0.3.1)
* [ ] Create noarch conda package for Flexx in the conda channel

**Comment by almarklein** [comment]
@damianavila I just released Flexx v0.3 to pypi. Can you please build a conda package again?

**Comment by almarklein** [comment]
@damianavila The conda recipe is done (its a noarch package). Just clone flexx and inside the repo do `conda build .`. I also uploaded the conda package here https://anaconda.org/pyzo/flexx/files

**Comment by damianavila** [comment]
Just for reference, I built and uploaded the noarch packages into the Bokeh org at anaconda.org.
