### ISSUE TITLE
Is there an example of bokeh server being deployed along with Flask to Cloud Foundry?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#3685]
I listened to ian hunston (http://www.ianhuston.net/)'s talk at (https://www.youtube.com/watch?v=XSXcz7rEzY4). It seems that we can build conda buildback and deploy anaconda python to cloud foundry.   

Is there an example of bokeh server being deployed along with Flask to Cloud Foundry?

**Comment by birdsarah** [comment]
I've never heard of one. This question is best posted to the mailing list https://groups.google.com/a/continuum.io/forum/#!forum/bokeh where the wider community can share their experiences.

**Comment by charleywan2004** [comment]
"damianavila added this to the 0.11.1 milestone 11 days ago". Does this mean "bokeh server deployed to cloud foundry" will be available soon in the release of 0.11.1?

**Comment by bryevdv** [comment]
No this is a discussion, it should not really have a milestone. As suggested, you'll probably get a better response by pinging the mailing list (or possibly SO) For instance, I've never used cloud foundry, so there's not much I can say that would be of help.

**Comment by damianavila** [comment]
Just to clarify, the discussion was ended before the 0.11.1 release, then I put that milestone there. In BEP1, discussion issues does not need to be milestoned immediately but it "could be" milestoned when the discussion end. I see some value into milestone the discussions, but I also see that it could be interpreted in the wrong way (as this issue show it). We should agree in something and modify BEP1 to include that decision.
