### ISSUE TITLE
Docs ToDos

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3688]
Cleaning up from: https://github.com/bokeh/bokeh/issues/3404

Missing content problems (this list needs re-checking):
- [x] "to be addeds" on dev_guide/notes
- [x] /user_guide/server.html - placeholder section titles
- [x] /user_guide/cli.html - remove mention of things not yet implemented!
- [ ] squished images http://bokeh.pydata.org/en/dev/docs/user_guide/notebook.html
- [ ] empty pages (or nearly empty):
  - [ ] http://bokeh.pydata.org/en/latest/docs/reference/server.html
  - [ ] http://localhost:5009/en/latest/docs/user_guide/tutorials.html

New content: 
- [ ] add an example for custom tiles to the user_guide geo page

Misc:
- [ ] left collapse docs menu
- [ ] subtle "top" to scroll to top would be helpful
- [ ] ~~automate the ALL_VERSIONS used for dropdown~~ (right now it adds the previosu version, but should be the latest one of any minor version)
- [ ] search bar on search page to match
- [ ] display searched for text in search bar
- [ ] use responsive plots
- [ ] userguide/tutorials is undewhelming (and wierd after learning more)
- [ ] too much white space on right side of gallery pages (due to no left menu)
- [ ] gallery design

Questions:
- [ ] what do we want the search facets to be (can be changed after final deploy)
- [ ] reference/core just has a bunch of stuff: "Enumeration....." is that right?
#### Search

Can we have the first tab just be a search of latest? (we may just have to make our own tabs and multiple search engines for this)

This doesn't seem to be possible - in particular:
- cannot seem to change the first tab
- cannot index latest

---
## Comments not yet distilled

I think the refguide needs to be more expanded navigation too

---

not shown here, but I think in a page full of functions/methods, it is really hard to tell where one stops and the next starts. I'd almost like the entire description indented a bit underneath, e.g. "autoload_server"

Here's another example of what I was mentioning: do the descriptions describe the thing above, or the thing below? Everything bleeds together. My first inclinations is that indenting all the descriptions would clearly (at least to me) indicate that they are "under" the thing above. Also BTW some the elements have the "before" pseudo elements (like "method") but others like these do not. 

<img width="480" alt="screen shot 2015-12-31 at 5 20 08 pm" src="https://cloud.githubusercontent.com/assets/1796208/12091068/23236b1a-b2c2-11e5-9997-b3de77c4ef76.png">

---

Here is what I notice:
- At a certain heading level, things begin to be right aligned, which to me is less readable.

![image](https://cloud.githubusercontent.com/assets/452052/12094971/65d60706-b2d1-11e5-8536-fae5bac93301.png)
- Napoleon sphinx extension needs to be used directly (see issue #2984). I am working on this. This fixes some returns formatting (see screenshot in issue).

---

random to dos
- migration note and docstring about @mattpap's changes to resources
- consider removing gapminder notebook (keeps getting out of sync)

---

Why is bokeh.command not in reference?

Possibly an oversight, though the docstrings are written extensively and discursively, so they are the primary source for the user guide. Putting it in the ref guide would be a straight duplication. It's also nothing anyone would ever import from directly for any reason whatsoever. 

fair enough - i just went looking because i was trying to find out how serve worked. I perceive "reference" as more authoritative.

I'd be inclined to add a reference for the command line command, as opposed to bokeh.command

---

**Comment by birdsarah** [comment]
The following snippets were removed from placeholder parts of docs on PR #3694:

#### `dev_guide/notes`

```
Managing examples
-----------------

*To be added:*

* examples' naming convention (e.g. _server suffix)
* adding examples to test.yml

Choosing right types
--------------------

*To be added:*

* choosing correct types for properties (don't use Any if possible)

Managing Python modules
-----------------------

*To be added:*

* update packages in setup.py when changing module structure

Managing external JS libraries
------------------------------

*To be added:*

* adding packages to and updating bokehjs/src/vendor

Maintaining secure variables in .travis.yml
-------------------------------------------

*To be added:*

* interactions with travis-ci from CLI (gem install --user-install travis)
* how to update secure values in .travis.yml (S3, flowdock)
```
#### `bokeh/command/subcommands/serve.py`

```
-*** DEVELOP MODE BELOW NOT YET IMPLEMENTED ***
-
-Additionally, the Bokeh server supports a "develop" mode, which will watch
-application sources and automatically reload the application when any of them
-change. To use this mode, add the ``--develop`` argument on the command line:
-
-.. code-block:: sh
-
-    bokeh serve app_script.py --develop
-
-.. note::
-    The ``--develop`` mode option should not be used in "production" usage.
```

**Comment by birdsarah** [comment]
@bryevdv - I've added your comment about the white space on the right of the gallery pages to this ToDo list.

**Comment by birdsarah** [comment]
need to add to this list idea of deploying the docs earlier - so google can index them, before making them switch to latest - which should be timed with build

**Comment by bryevdv** [comment]
Some of these things have been fixed (nearly empty pages, tutorial now links live notebooks from the top, squished images, ref/core docs, etc) Others I am just not concerned about (gallery whitespace). This issue as-is is hard to act on, so closing at this point.
