### ISSUE TITLE
Doc: data_source is not an expected attribute to Text

### ISSUE THREAD

**Issue by aavanian** [bokeh/bokeh#3698]
````
p = figure(x_range=self.xr, y_range=self.yr, title=index, tools='hover, crosshair', **plot_formats)
p.text(data_source=source, x='x', y='y', text=['test'], text_color="black", text_font_size="10pt")
````
results in 
````
AttributeError: unexpected attribute 'data_source' to Text, possible attributes are angle, angle_units, name, tags, text, text_align, text_alpha, text_baseline, text_color, text_font, text_font_size, text_font_style, visible, x, x_offset, y or y_offset
````

whereas docs mentioned data_source as a possible parameter (http://bokeh.pydata.org/en/latest/docs/reference/plotting.html)

**Comment by birdsarah** [comment]
The snippet you've posted looks like it should work to me.

Can you post a full sample that fails to run.

**Comment by bryevdv** [comment]
What version of Bokeh are you running? 

@birdsarah this is what happens in current versions:

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/helpers.py#L439-L442

`_pop_renderer_args` pops off `data_source` before anything hits the actual `Glyph` initializer, I think this has to be an older version of Bokeh.

**Comment by aavanian** [comment]
Here you go (I'm running 0.11):
````
from datetime import datetime
import bokeh
import bokeh.models as bkm
import bokeh.plotting as bkp
import numpy as np
import pandas as pd

print(bokeh.__version__)
bkp.output_notebook()
idx = pd.DatetimeIndex(start=datetime.now(), periods=250, freq='D')
data = pd.DataFrame(np.random.rand(250), index=idx)
source = bkp.ColumnDataSource({'x': data.index, 'y': data.values, 'Date': data.index.format()})

p = bkp.figure()
p.line(source=source, y='y', x='x')
p.text(data_source=source, x='x', y='y', text=[str(i) for i in range(250)])
````
Obviously, the text part is a bit silly in the above. Note that I managed to achieve what I wanted by passing directly lists of coordinates to the ```text()``` call, so I don't need a workaround. 

run in notebook:
![image](https://cloud.githubusercontent.com/assets/13487305/12501240/0222de2c-c0f6-11e5-8f47-1b0ee052c82b.png)

**Comment by bryevdv** [comment]
Oh, it's `source` (for all glyph methods, just like you have for `p.line`) Not sure offhand what's causing our automated docs to print it as `data_source`, will have to run it down.

**Comment by bryevdv** [comment]
Oh, because it's not automated, there's a docs template and it is wrong: 

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/helpers.py#L421

@aavanian would you mind submitting a quick PR to fix that line?
