### ISSUE TITLE
BoxPlot 1st and 4th whiskers are just of equal length

### ISSUE THREAD

**Issue by danaki** [bokeh/bokeh#3699]
![screen shot 2016-01-21 at 17 55 20](https://cloud.githubusercontent.com/assets/1043805/12485685/12e21b6c-c068-11e5-8a98-2596b9cdd0c3.png)

Here at the picture are example car prices which are skewed data. Seems that median 50%, 25% and 75% drawn correct, but 0% and 100% whiskers somehow of the same length and this is impossible because data are skewed and plus there're no price below zero in my sample data. The lower whisker must be way shorter.

**Comment by danaki** [comment]
From the https://en.wikipedia.org/wiki/Interquartile_range:

> The interquartile range is often used to find outliers in data. Outliers are observations that fall below Q1 - 1.5(IQR) or above Q3 + 1.5(IQR). In a boxplot, the highest and lowest occurring value within this limit are drawn as bar of the whiskers, and the outliers as individual points.

So whiskers start on first data point inside the 1.5 * IQR range, not just:
```
        self.w0 = self.q1 - (1.5 * self.iqr)
        self.w1 = self.q3 + (1.5 * self.iqr)
```

**Comment by danaki** [comment]
[bokeh-boxplot-whiskers.patch.txt](https://github.com/bokeh/bokeh/files/99691/bokeh-boxplot-whiskers.patch.txt)

**Comment by birdsarah** [comment]
ping @fpliger @rothnic - is @danaki's patch correct (this is not an area I'm confident in). If so @danaki, we'd love a PR if you feel confident doing that.

**Comment by fpliger** [comment]
@birdsarah It should be correct according to https://en.wikipedia.org/wiki/Interquartile_range (that is quite more detailed then) https://en.wikipedia.org/wiki/Box_plot.
Best would be to have a PR opened with a test (maybe with the same example shown in the first reference?). @danaki, would you be confident with that doing it?

**Comment by danaki** [comment]
My example data contains about 18K records, but from bar plot examples http://bokeh.pydata.org/en/0.10.0/docs/user_guide/charts.html#box-plots seems that "autompg" also drawn incorrectly. I'll try with PR.
