### ISSUE TITLE
Structured way to get at documents from JavaScript

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3700]
As discussed here, https://groups.google.com/a/continuum.io/d/msg/bokeh/-fPwXKBfWHs/qPeJeoT9BQAJ
people used to be able to get model objects from Bokeh.Collection, but that was sort of a hack; and they can still get them through Bokeh.index but I think that's also sort of ugly (because it's one of the only reasons anyone ever sees a BokehJS view; because it's a global that as far as I know we never remove anything from).

Here are some ideas for improved API to get at Document instances:
- track a map from _open_ session IDs to the list of ClientSession instances. Add global functions `Bokeh.get_sessions()` returning a list of ClientSession, and `Bokeh.get_session_by_id()` perhaps. When someone gets a session they can get `session.document`
- in embed.coffee, keep track of "rendered documents" ... export a global list rendered_documents, which would contain those documents that have an active DOM node from _render_document_to_element. I think on a `remove` event (the element is taken out of the DOM) we should remove the document from the global list, otherwise we would leak documents if an app is frequently making new ones.
- alternative idea... support running some JS when we create the 'render item', passing it the model or document that was rendered... the JS would be a JSCallback model inside the document itself possibly, like document.render_callback ?

There are probably lots of ways to do this, but I think it would be a mistake to expose the "docid" in public API for what it's worth, and we should avoid solutions that will leak documents if someone has an app that creates lots of documents.

**Comment by birdsarah** [comment]
Wanted to link up with https://github.com/bokeh/bokeh/issues/3352 which may have some overlap.

**Comment by birdsarah** [comment]
`Bokeh.documents` is now available in JS.
