### ISSUE TITLE
Handle slow callback functions (like querying a remote data source) when using x_range.on_change in Bokeh server

### ISSUE THREAD

**Issue by jdugge** [bokeh/bokeh#3702]
<sup>This started as [a question on Stackoverflow](http://stackoverflow.com/questions/34932010/handle-slow-callback-functions-when-using-x-range-on-change-in-bokeh-server)</sup>

I'm trying to use callback functions to generate new data in a Bokeh server plot when the axis range changes. This works fine in principle: I've attached the necessary function to the plot using p.x_range.on_change('end', my_callback_function), my_callback_function is executed and updates the plot.

The problem I'm facing is that the callback function can take a long time to complete, because I'm querying a server for new data (and then doing some downsampling). If the user pans the plot or zooms several steps while `my_callback_function` is still running, more `on_change` events are fired and new calls to `my_callback_function` pile up. This leads to the plot updating for a long time after the user has stopped panning or zooming.

 * Is there a way to cancel the execution of a callback function in case a new call is executed?
 * Or is it possible to specify that only one call to a callback function may be queued up at any one time?
 * What other ways are there to get data from a remote server when the range is updated, without locking up the Bokeh server?

I tried deactivating the callback while the function is running by setting `p.x_range.remove_on_change('end', my_callback_function)` at the start of `my_callback_function`, but apparently that deactivation doesn't happen until the call to `my_callback_function` is complete: new calls are still piling up.

I also tried using the `threading` library to run the data generating function in a separate thread while the callback function merely checks whether the data generating function is currently running. However, it seems like the new thread is never started (I don't see any output, at least, and the plot doesn't update).

Here's a minimal example:

```python
import bokeh.plotting
import numpy
import time

def generate_data(start, end):
    time.sleep(1)
    newx = numpy.linspace(start + 0.1 * (end - start), end - 0.1 * (end - start), 10)
    newy = numpy.random.rand(10)
    return newx, newy

def my_callback_function(param, old, new):
    # I tried deactivating the callback once it's running...
    # p.x_range.remove_on_change('end', my_callback_function)
    x, y = generate_data(p.x_range.start, p.x_range.end)
    ds.data = {
        'x': x,
        'y': y
    }
    # ... and activating it again when done, but that doesn't work, the function calls still pile up
    # p.x_range.on_change('end', my_callback_function)

x, y = generate_data(0, 10)

p = bokeh.plotting.figure(x_range=[0, 10])
l = p.line(x, y)
ds = l.data_source

p.x_range.on_change('end', my_callback_function)

bokeh.plotting.curdoc().add_root(p)
```

**Comment by birdsarah** [comment]
Hi @jdugge, I recall a conversation with @havocp about buffering events and not letting a buffer get too big....I'm not sure what happened with that - hopefully he can shed some light.

**Comment by havocp** [comment]
Oops, I had an email flagged to respond to this and never did it. Probably not relevant anymore, but for anyone wondering in the future - one way to handle this is to make your callback add a "next tick" handler, only if there isn't one already added (i.e. be sure you've added only one at a time - keep a variable for whether it's added/in-progress, and unset the variable at the end of the next tick handler). Then do the work in the next tick handler. A variation on this if you want to rate-limit updates is to add a timeout rather than a next tick handler, which will mean you only do the work every certain amount of time.

**Comment by jdugge** [comment]
Thanks for the tip, @havocp. Unfortunately, I still can't get this to work: the `next_tick_callback` also seems to block the thread, so the `x_range.on_change` callbacks still pile up.

Maybe I'm misunderstanding something? Here's the adapted test code:

```
import bokeh.plotting
import numpy
import time

def generate_data(start, end):
    time.sleep(1)
    newx = numpy.linspace(start + 0.1 * (end - start), end - 0.1 * (end - start), 10)
    newy = numpy.random.rand(10)
    return newx, newy

def range_callback_function(param, old, new):
    global in_progress
    print in_progress
    if in_progress:
        print "In progress, doing nothing"
    else:
        in_progress = True
        print "Adding callback"
        doc.add_next_tick_callback(tick_callback_function)

def tick_callback_function():
    global in_progress
    print "Tick callback function"
    x, y = generate_data(p.x_range.start, p.x_range.end)
    ds.data = {
        'x': x,
        'y': y
    }
    in_progress = False

in_progress = True
x, y = generate_data(0, 10)
in_progress = False

p = bokeh.plotting.figure(x_range=[0, 10])
l = p.line(x, y)
ds = l.data_source

p.x_range.on_change('end', range_callback_function)

doc = bokeh.plotting.curdoc()

doc.add_root(p)
```

**Comment by havocp** [comment]
if your callback does a sleep() then yes; to avoid this you need to use a tornado nonblocking sleep or nonblocking IO or put your IO in a thread.

**Comment by havocp** [comment]
well - with that sample code I'm not sure why you get pileup. but I would expect 1s latency

**Comment by havocp** [comment]
well, I would expect pileup but expect the piled up callbacks to all do nothing :-) sorry posting while distracted

**Comment by havocp** [comment]
useful detail: if your next tick callback is a Tornado coroutine, it will just work (wont run the callback again until all the async work is done).

**Comment by jdugge** [comment]
Thanks for the clarification, @havocp, the hint about the non-blocking function makes complete sense. Strangely, in my sample code there is a pile-up and the piled up function calls do regenerate the data. The `if in_progress: print "In progress, doing nothing"` branch is never executed.

My actual use case is accessing a MongoDB. I tried making that process non-blocking by using the Motor library (MongoDB for Tornado) with a `coroutine`, as you suggested, but the calls still pile up. Would you mind taking a look at that issue and pointing me in the right direction?

**Comment by jdugge** [comment]
Sorry for being so dense, but I still can't manage to get this to work, even with my simple test case. I've adapted the example to now do the following:

* simulate an expensive non-blocking data regeneration process using `tornado.gen.sleep(1)` in a `@gen.coroutine`
* every 0.1 seconds, a periodic callback checks whether the expensive non-blocking data regeneration process is currently active:
   * if the data regeneration process is currently active, do nothing
   * if the axis range has changed, add the data regeneration process to the `next_tick_callback`

However, the periodic callback is not executed while the data regeneration process is active. There's nothing blocking in the data regeneration process, but even though I'm using a `@gen.coroutine`, Bokeh blocks the periodic callback while waiting for the `next_tick_callback` to finish.

Could you tell me where I'm going wrong, or point me to an example that demonstrates how to use asynchronous callbacks?

Apologies for taking up so much of your time.

```python
import bokeh.plotting
from tornado import gen

@gen.coroutine
def update_data():
    global in_progress
    yield gen.sleep(1)
    in_progress = False


def my_periodic_callback():
    global in_progress
    if in_progress:
        # This line never runs, the periodic callback doesn't execute while the next_tick_callback is active
        print "in progress"
    else:
        print "regenerate data"
        in_progress = True
        doc.add_next_tick_callback(update_data)


p = bokeh.plotting.figure(x_range=[0, 10], y_range=[0,1000])
l = p.line(x=[0, 10], y=[0, 1000])

in_progress = False

doc = bokeh.plotting.curdoc()
doc.add_periodic_callback(my_periodic_callback, 100)
doc.add_root(p)
```

**Comment by bryevdv** [comment]
Sorry for the delayed response, there is alot going on... I can reproduce the behavior, and I believe it is a big. Hopefully not a fundamental limitation of Tornado in some way (I don't think it should be)

**Comment by bryevdv** [comment]
OK! If I change the `next_tick_callback` to standard tornado, i.e.:
```
ioloop.IOLoop.instance().add_callback(update_data)
```
Then it works as expected. @havocp do you have any quick thoughts as to why this might work but `next_tick_callback` doesn't?

**Comment by havocp** [comment]
Maybe both callbacks lock the document so they can't run at the same time. We auto-lock the doc from handler callbacks (but not from lifecycle callbacks).

**Comment by havocp** [comment]
I'm not sure we should keep the lock held while a coroutine is yielding. yielding still allows other sessions to make progress, but right now you can't avoid tying up the session your callback belongs to.

The lock guarantees that the document doesn't change during the yield at the moment. Which could be convenient sometimes and inconvenient other times.

**Comment by bryevdv** [comment]
@havocp can you point me to the lock? I tried tracing from `next_tick_callback` and I am not seeing where anything gets locked.

**Comment by havocp** [comment]
yeah it's in a decorator

**Comment by bryevdv** [comment]
So I guess the problem is that without the lock, any coroutine that modifies the document in a yield is in error, correct? Presumably with the potential for protocol errors as was seen in the other issue? Is there any way we could detect and complain loudly if this happens? i.e., some kind of "soft-lock" state that just makes sure to notice if the document is modified and complains in a meaningful way (more meaningful than a protocol explosion)

Alternatively, an option to the callback adding functions that toggles whether the lock is held in a yield? I'm not actually sure how we'd toggle it on/off at the right point offhand, though.

**Comment by havocp** [comment]
For the yields I don't think protocol corruption would happen since we'd still have the lock when actually running code. The problem is just that whenever you yield you have to be prepared for the client or another callback to change anything about the document. In general you'd want to avoid reading doc properties before a yield and then using them after a yield (currently that is safe to do).

my guess is that dropping the lock during yield is probably ok and perhaps less surprising than the current behavior. 

It might be nice to provide some way people can keep the lock across yields if necessary. not sure exactly how that would look. perhaps a decorator

**Comment by bryevdv** [comment]
Ok, I can try to explore it, but I guess my question is how to know when you are entering a yield? There's no hook AFAIK. What about a context manager:
```
with release_doc():
    yield gen.sleep(1)
```

**Comment by havocp** [comment]
I thought there was a way to do this, but I guess I was wrong; I forgot that the generator gets entirely hidden and all we get from the callback is a Future that represents the entire callback completing. I made a little program to play around with this.

```python
from tornado import gen
from tornado.ioloop import IOLoop

# Toggle this to see the two cases; where we wait for the
# callback's Future before we drop the lock, and where we don't.
with_wait_for_future = True

@gen.coroutine
def sample_callback():
  print("sample_callback entering")
  a = yield gen.sleep(0.5)
  print("sample_callback a=" + str(a))
  b = yield gen.sleep(0.5)
  print("sample_callback b=" + str(b))
  print("sample_callback exiting with result 42")
  raise gen.Return(42)

def stop_loop():
    print("exiting Tornado IOLoop")
    IOLoop.current().stop()

@gen.coroutine
def driver():
    print("driver entering")
    print("*  PRETEND WE TAKE A LOCK HERE")
    initial_future = sample_callback()
    print("driver initial_future=" + str(initial_future))
    if with_wait_for_future:
        print("driver yielding to wait for initial_future")
        result = yield initial_future
        print("driver result=" + str(result))
    else:
        print("driver just rolling ahead without waiting")
    print("*  PRETEND WE DROP THE LOCK HERE")
    IOLoop.current().call_later(3, stop_loop)
    print("driver exiting")

IOLoop.current().add_callback(driver)

print("starting Tornado IOLoop")
IOLoop.current().start()
```

Here is the output with_wait_for_future=True:
```
starting Tornado IOLoop
driver entering
*  PRETEND WE TAKE A LOCK HERE
sample_callback entering
driver initial_future=<tornado.concurrent.Future object at 0x7f1db35dc0f0>
driver yielding to wait for initial_future
sample_callback a=None
sample_callback b=None
sample_callback exiting with result 42
driver result=42
*  PRETEND WE DROP THE LOCK HERE
driver exiting
exiting Tornado IOLoop
```

And with_wait_for_future=False
```
starting Tornado IOLoop
driver entering
*  PRETEND WE TAKE A LOCK HERE
sample_callback entering
driver initial_future=<tornado.concurrent.Future object at 0x7f5cdc5bc0f0>
driver just rolling ahead without waiting
*  PRETEND WE DROP THE LOCK HERE
driver exiting
sample_callback a=None
sample_callback b=None
sample_callback exiting with result 42
exiting Tornado IOLoop
```

We do the equivalent of with_wait_for_future=True right now, here:
https://github.com/bokeh/bokeh/blob/master/bokeh/server/session.py#L45

yield_for_all_futures is our own utility that essentially deals with nested futures, I don't remember why we had nested futures, but anyway if a future contains a future we wait for the contained future too. In this simple case I think yield_for_all_futures can be thought of as equivalent to plain yield.

The relevant Tornado source is at http://www.tornadoweb.org/en/stable/_modules/tornado/gen.html#coroutine and the actual generator is driven in the Runner.run method (the send() calls are returning control to the callback). I don't see how we could hook into this, I guess.

Note that in the sample program, the part of the callback before the first yield always runs inside the lock. So this issue only arises when there's a yield in the callback.

We COULD drop the lock at the point of the _first_ yield - in fact I think it used to work that way by accident - but that's sort of a weird behavior I think, it doesn't make much sense that the first part of the callback has locking but none of the rest.

So maybe the best we could do is let people disable the lock for the entire callback, perhaps a `@without_document_lock` decorator? At that point they could use SessionContext.with_locked_document (https://github.com/bokeh/bokeh/blob/master/bokeh/server/application_context.py#L66 ) to modify the document, but of course they HAVE to use it; if they directly access curdoc() without taking the lock, stuff will explode. So a user who used our `@without_document_lock` decorator on a callback would be sort of bypassing the warranty and accepting some danger. (side note: not sure we have a way to get the SessionContext from inside the app handler script, but should be possible to add) (side note 2: perhaps we could arrange to unset curdoc() inside `without_document_lock` ?)

**Comment by omearac** [comment]
Hi everyone I just wanted to chime in and say this was exactly my problem for interactive downsampling in 0.11.1. The PR fixed my issue perfectly. Great work!

**Comment by tangfucius** [comment]
@omearac Can you show me how you actually use the decorators in the range callback? Have been trying to follow the examples but can't get it working.

**Comment by omearac** [comment]
Hey @tangfucius ! Okay yea I got it working by using the same code from the example here https://github.com/bokeh/bokeh/pull/4152  (at the top of the thread).

So basically you do a session.document.add_periodic_callback(my_sweet_periodic_callback, 400). Then in my sweet period callback function (which has no decorator) theres a global boolean variable in_progress. If it is false, then we session.document.add_next_tick_callback(update_data) where now the update_data function has two decorators @gen.coroutine and @without_document_lock. It is in here you can set new x-axis ranges and/or plot object data and at the end of the this update_data function you then set the global variable "in_progress" to be true. Hope this helps!
