### ISSUE TITLE
Use "Simple IDs" inside documents. 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3713]
UUID's made sense with the old server architecture, but I don't think they are necessary. I propose to make "Simple IDs" (i.e., 1000, 1001, 1002, ...) the default. 

@bokeh/dev thoughts?

**Comment by havocp** [comment]
if two sides of the websocket both add a model you need to avoid collisions, so you would at least need a per-process unique prefix (which is most easily implemented as a uuid...)

simple ids require all models to be created by the server, if there's no prefix

**Comment by bryevdv** [comment]
OK well simplifying UUIDs by keeping them but tacking on more to them seems like an anti-solution, so quick discussion, let's just keep things as they are.

**Comment by havocp** [comment]
The server could hand out a prefix to each connection during the initial handshake, and then the prefix could be something short. That's what X11 and dbus both do. The only downside is you have to pass the connection in to the Model constructor so it can get a prefix, which is probably not worth it.
