### ISSUE TITLE
Histogram and color

### ISSUE THREAD

**Issue by waqarmalik** [bokeh/bokeh#3716]
Bokeh 0.11.0

Consider the histogram example

```
from bokeh.charts import Histogram, output_file, show
from bokeh.sampledata.autompg import autompg as df

p = Histogram(df, values='hp', color='navy', title="HP Distribution")
output_file("histogram_color.html")
show(p)
```

The above example works, but if I use

```
p = Histogram(df['hp'], color='navy', title="HP Distribution")
```

I get the error

```
ValueError: cannot label index with a null key
```

Is this a known issue?

**Comment by birdsarah** [comment]
ping @fpliger

**Comment by epatters** [comment]
At least in 0.12.0, this bug is still present. Just ran into it.

**Comment by nicolasfguillaume** [comment]
Same here.  0.12.0, this bug is still present. Thanks

**Comment by MortezaMoghadd** [comment]
Even in 0.12.3, this bug is still present. Thanks

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/44)
