### ISSUE TITLE
Make sure we have an example for each of the viz types in www.datavizcatalogue.com

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#372]
A few of these are beyond scope of Bokeh, but most are not.

http://www.datavizcatalogue.com/

**Comment by mattpap** [comment]
- [ ] Arc Diagram
- [ ] Area Graph
- [ ] Bar Chart
- [ ] Box & Whisker Plot
- [ ] Brainstorm
- [ ] Bubble Chart
- [ ] Calendar
- [ ] Choropleth Map
- [ ] Circle Packing
- [ ] Donut Chart
- [ ] Dot Matrix Chart
- [ ] Flow Map
- [ ] Histogram
- [ ] Illustration Diagram
- [ ] Line Graph
- [ ] Marimekko Chart
- [ ] Multi-set Bar Chart
- [ ] Parallel Sets
- [ ] Pictogram Chart
- [ ] Pie Chart
- [ ] Population Pyramid
- [ ] Propotional Area Chart
- [ ] Radar Chart
- [ ] Radial Bar Chart
- [ ] Sankey Diagram
- [ ] Scatterplot
- [ ] Span Chart
- [ ] Stacked Area Graph
- [ ] Stacked Bar Graph
- [ ] Stem & Leaf Plot
- [ ] Tally Chart
- [ ] Timeline
- [ ] Timetable
- [ ] Tree Diagram
- [ ] Treemap
- [ ] Venn Diagram
- [ ] Word Cloud
- [ ] Candlestick Chart
- [ ] Chord Diagram
- [ ] Condegram Spiral Plot
- [ ] Density Plot
- [ ] Error Bars
- [ ] Flow Chart
- [ ] Gantt Chart
- [ ] Heat Map
- [ ] Hikkake Pattern
- [ ] Kagi Chart
- [ ] Network Diagram
- [ ] Nightingale Rose Chart
- [ ] Parallel Coordinates
- [ ] Point & Figure Chart
- [ ] Stream Graph
- [ ] Sunburst Diagram
- [ ] Violin Plot

**Comment by drorata** [comment]
If I may upvote for ``parallel-coordinates``. It has a limited implementation in ``matplotlib`, but without interactive components (like `brushing`) it is virtually useless for data studying. There is a nice [D3](https://syntagmatic.github.io/parallel-coordinates/) implementation and it would be very nice to have it in bokeh.

**Comment by scottcode** [comment]
I second the **Parallel Coordinates**, and I'd also like to upvote **Sankey Diagrams**. The [D3 implementation](http://bost.ocks.org/mike/sankey) is great, and the reason I'd really like to see it in Bokeh is to be able to apply crossfiltering to a Sankey.

**Comment by pzwang** [comment]
I've realized that Parallel coordinates is a particular specialization of Nomographs, which seems to be useful in general.  https://en.wikipedia.org/wiki/Nomogram

**Comment by MatthewSteen** [comment]
I third the **Parallel Coordinates** and **Sankey Diagrams** efforts.

**Comment by tbsexton** [comment]
Fourth, **Parallel Coordinates** and esp. **Sankey Diagrams** would be great, as I've tried to Frankenstein them together w/ matplotlib before.

**Comment by mathDR** [comment]
Hi all. Does anyone know the status of a treemap in bokeh?  Generating a static one is pretty trivial, but I wanted a dynamic one like Mike Bostock's example: https://bost.ocks.org/mike/treemap/

I was thinking of using anytree for the hierarchy and squarify for the layout.  Also, extending ZoomInTool and ZoomOutTool for dynamically moving up and down the hierarchy.

Thoughts?

**Comment by abytofpy** [comment]
Hi ! I've assembled some code to output a **treemap** example [here on github](https://github.com/abytofpy/BokehTreemap). A preview of the result is shown.
I'd be glad to improve this example with feedback.

**Comment by wautomaton** [comment]
Rick Lupton has widget project that might be a good reference point for sankey in bokeh

https://github.com/ricklupton/ipysankeywidget

**Comment by dofine** [comment]
Any updates on radar plot, please?

**Comment by bryevdv** [comment]
Closing this, this issue has served its motivational purpose. Many of these plots types will be more appropriate now in HoloViews and GeoViews and other tools built on top of a stable Bokeh core, or in some cases that do make sense for core bokeh (radial, radar plots) there are existing dedicated issues.

**Comment by jrversteegh** [comment]
Issue for adding radial/radar plots (polar in matplotlib) appears to be #657
