### ISSUE TITLE
Add an option to return items from select as a dictionary 

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3720]
At the moment `document.select({'type': ColumnDataSource})` will return a list of `ColumnDataSources`.

It would be a nice utility if it could alternatively return a dictionary of `ColumnDataSources` where the key is the model name (or fallback to id if name isn't available).

**Comment by birdsarah** [comment]
I'm considering closing this since I discovered that `document.select` can be passed `{'name': 'mything'}`.

It would be nice if document.select would just accept keyword arguments like `Plot.select` does.

**Comment by bryevdv** [comment]
FWIW I'm generally -1 on functions returning different types and things under different circumstances. Making the `select` functions match up better sounds good though

**Comment by birdsarah** [comment]
> FWIW I'm generally -1 on functions returning different types and things under different circumstances. 

Good point. I agree.
