### ISSUE TITLE
Add context manager for `pull_session` and `push_session` that closes the session for you

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3722]
I keep forgetting to close sessions. 

It would be nice if I could just do

``` python
with pull_session(session_id=....) as session:
    # do stuff with session
```

and then it automatically closes the session for you.

**Comment by birdsarah** [comment]
For the impatient, you can just use python's built in contextlib function `closing` (https://docs.python.org/3/library/contextlib.html#contextlib.closing)

from contextlib import closing
with closing(pull_session(session_id=...)) as session:
    # do stuff with session

This will automatically call `session.close()` when you're done - this was a revelation for me today!

**Comment by bryevdv** [comment]
Given that: 
* there's not been any additional demand for this
* "full" apps are almost always recommended over `bokeh.client`
* it can be accomplished via standard library tools in one line

I'm inclined to just close. Please re-open if you feel differently, however
