### ISSUE TITLE
Make `Document.select` interface match `Plot.select`

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3724]
It would be nice if `Document.select` would accept keyword arguments like `Plot.select` does.

Would apply to related method `select_one`,  `set_select` would be slightly more tricky but should probably be consistent.

Issue started after some thought on #3720

**Comment by bryevdv** [comment]
Didn't realize #8018 was a dupe of this, was completed in #8019

**Comment by bryevdv** [comment]
Scratch that, not quite a dupe

**Comment by bryevdv** [comment]
Neither of these functions gets much use at all (and less even than they used to) and there has not been any wider interest expressed. Closing this with no action.
