### ISSUE TITLE
Pandas required to use the server!

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3726]
In the happiness demo I am using `plotting.Figure` to make my plots.

When I setup a clean environment with only `bokeh` and `django` as the requirements, I got the following error. I don't use the charts interface at all, so I'm guessing this is a bug.

```sh
Failed to push document: RuntimeError('The bokeh.charts interface requires Pandas (http://pandas.pydata.org) to be installed.',)
/envs/happiness/lib/python3.5/site-packages/bokeh/client/connection.py in push_doc, line 231
```

**Comment by bryevdv** [comment]
Guessing this is the problem: https://github.com/bokeh/bokeh/blob/master/bokeh/model.py#L51-L66

A few options I can think of:

* restore pandas as a dependency
* try the imports incrementally (only import `bokeh.charts` if  lookup in `bokeh.models` fails)
* defer the pandas dependency warning until classes that actually use it are initialized

I guess the last would be the best, but a little bit of work. On the plus side it would let people use charts that *don't* need pandas without having to install it.

**Comment by mattpap** [comment]
On top of my head, I doubt charts should be preloaded. I need to verify this.

**Comment by bryevdv** [comment]
FYI this is a must-fix (one way or another) for `0.11.1` I'd like to have a fix in the next dev build (looks like tomorrow morning)

**Comment by birdsarah** [comment]
> defer the pandas dependency warning until classes that actually use it are initialized

Yes, that definitely seems best, but it sounds hard.

**Comment by bryevdv** [comment]
Looks like just this:
```
bryan@0199-bryanv (git:master) ~/work/bokeh/bokeh $ grip "import pandas"
./charts/attributes.py:
    5 : import pandas as pd
./charts/builders/donut_builder.py:
   81 :         import pandas as pd
./charts/builders/horizon_builder.py:
   56 :         import pandas as pd
./charts/builders/timeseries_builder.py:
   61 :         import pandas as pd
./charts/conftest.py:
    4 : import pandas as pd
./charts/data_source.py:
   17 : import pandas as pd
./charts/glyphs.py:
    6 : import pandas as pd
./charts/models.py:
    4 : import pandas as pd
./charts/properties.py:
   12 : import pandas as pd
./charts/stats.py:
   18 : import pandas as pd
./charts/tests/test_comp_glyphs.py:
    2 : import pandas as pd
./charts/tests/test_stats.py:
    6 : import pandas as pd
./charts/utils.py:
   24 : import pandas as pd
```

I'll make a stab...

**Comment by birdsarah** [comment]
tangent: `grip` looks like a useful wrapper on grep.

**Comment by bryevdv** [comment]
it's just:
```
alias grip='grin -I "*.py"'
```

**Comment by bryevdv** [comment]
Actually, this either has to be solved by removing the preload, or by adding back in pandas as a hard dependency. The preload brings in lots of the places that the more specific import would be anyway.

**Comment by bryevdv** [comment]
Nothing under `bokeh.charts` inherits from `Model` afaict I think the import can just be removed.
