### ISSUE TITLE
Difference between public and internal session lifetime units

### ISSUE THREAD

**Issue by jbcrail** [bokeh/bokeh#3730]
The Bokeh server's session lifetime flag, `--unused-session-lifetime`, expects values in milliseconds. This value is first assigned to `unused_session_lifetime_milliseconds` and eventually assigned to the Tornado flag, `unused_session_linger_seconds`.

When checking for unused sessions, `unused_session_linger_seconds` (actual units in milliseconds) is compared with `seconds_since_last_unsubscribe` (actual units in seconds). Session cleanup doesn't occur when expected.

Before working on a fix, I wanted to gather thoughts from @havocp and @bryevdv.

**Comment by havocp** [comment]
I think we should make everything be milliseconds so we don't get confused (almost everything is already).

**Comment by bryevdv** [comment]
Agreed
