### ISSUE TITLE
Matplotlib fill_between() dates not converted properly with to_bokeh()

### ISSUE THREAD

**Issue by woztheproblem** [bokeh/bokeh#3740]
I am using to_bokeh() to convery matplotlib (pyplot) graphs to bokeh figures.  I have some graphs that use matplotlib's fill_between() to shade between lines, using timeseries data.  The lines themselves graph at the appropriate times on the y axis, but the shaded area plots near 1970, as the times do not get converted correctly when the graph is converted to bokeh.  Here is some demo code to show the issue: 

```
%pylab inline
from bokeh import plotting as bplot
from bokeh import mpl as bmpl
import pandas as pd
x = pd.Series(range(72), index=pd.date_range('1/1/2011 00:00:00', periods=72, freq='H'))
x2 = 2*x
x.plot()
fill_between(x.index, x, x2)
bplot.output_notebook()
bplot.show(bmpl.to_bokeh(plt.gcf()))
```

If I comment out the last two lines, so it is a regular matplotlib plot, I get the shaded wedge, as desired (first attachment).  With the last two lines uncommented, I get the second attachment.  If I remove the fill_between() call, I get the third attachment, which shows that the line plot shows fine.  The 4th attachment shows the result of the fill_between call only.  

This is on bokeh 0.11.0, with matplotlib 1.5.1 and pandas 0.17.1.  
![screen shot 2016-01-25 at 3 46 13 pm](https://cloud.githubusercontent.com/assets/713139/12565645/0333f7e2-c37b-11e5-84bc-13b4488d7b2f.png)
![screen shot 2016-01-25 at 3 46 24 pm](https://cloud.githubusercontent.com/assets/713139/12565654/0fd34cb4-c37b-11e5-86fa-32322be117af.png)
![screen shot 2016-01-25 at 3 46 58 pm](https://cloud.githubusercontent.com/assets/713139/12565656/15831c98-c37b-11e5-9eee-a37e2cb41d37.png)
![screen shot 2016-01-25 at 3 47 14 pm](https://cloud.githubusercontent.com/assets/713139/12565658/18bc3aa2-c37b-11e5-80ef-066a0c7fc978.png)

**Comment by bryevdv** [comment]
Closing, MPL compat is deprecated and will be removed entirely in the near future.
