### ISSUE TITLE
Doc improvement regarding Windows installation : path issue for bokeh command

### ISSUE THREAD

**Issue by ChristianTremblay** [bokeh/bokeh#3746]
When installing Anaconda, "bokeh" will appear on the path and be accessible. That is not the case if we just pip install or build from source. I'm not aware of a way to automatically solve this issue... other than a script that would add bokeh to the path after the build... And that would probably be a manual operation.

This info should appear somewhere in the doc.

**Comment by bryevdv** [comment]
Closing this disucssion in favor of the task issue: https://github.com/bokeh/bokeh/issues/4119
