### ISSUE TITLE
Expose frame height/width to Bokeh server

### ISSUE THREAD

**Issue by jdugge** [bokeh/bokeh#3747]
In order to do server-side downsampling efficiently it's important to know the size of the axis area measured in pixels (e.g. for [M4 aggregation](http://www.vldb.org/pvldb/vol7/p797-jugel.pdf)).

Currently, it seems like there's no way for the Python script in the Bokeh server to learn about the dimensions of the axis area: there's a `figure.plot_width` attribute, but this refers to the overall width of the figure (including labels and margins), and it doesn't seem to get updated when the user changes the figure size using the `resize` tool.

It would be great if the axis size could be communicated to the Python backend somehow (perhaps in conjunction with a `axis_width.on_change` callback.

**Comment by bryevdv** [comment]
Hi @jdugge thanks for posting here, and also with the full use-case. Now that I know the reason for the request, I can say that we actually do plan on exposing the "frame" dimensions back to the server in the near future. This is not *exactly* what you are asking for, but I think it is actually more directly what you want (i.e., the dimensions of the central plot area, in order to inform a downsampling computation for data there). I will say some people have worked around the current capability using CusomJS callbacks, which might also work for you in the short term. @brendancol can you comment?

**Comment by brendancol** [comment]
hey @jdugge  yeah the frame object will help.  I'm currently making a callback example using frame and will pass it along when ready

**Comment by jdugge** [comment]
@brendancol: Can you estimate when the example might be ready? If you haven't had time to work on this, I'd be happy to come up with an example myself and contribute it here. In that case, maybe you could give me a pointer on the general process? @bryevdv mentioned using CustomJS callbacks, but I'm not sure how I can use that to feed information back to the server?

**Comment by brendancol** [comment]
@jdugge: so this isn't exposed to the server yet that i know of.  One callback example you may want to talk a look at is the `InteractiveImage` notebook callback from datashader which uses the plot frame object https://github.com/bokeh/datashader/blob/master/datashader/callbacks.py

check out https://github.com/bokeh/datashader/blob/master/datashader/callbacks.py#L58-L63

I would like to get the frame properties exposed to the server and will help champion that.  Sorry couldn't be more helpful at the moment.

**Comment by jdugge** [comment]
@brendancol: Thanks for getting back to me so quickly. From the `InteractiveImage` code you linked to I managed to cobble together an example that gets the current frame height and width and prints it to the JavaScript console.

However, I'm still at a loss how to get this information from the browser back to the Python process running in the Bokeh server. The `InteractiveImage` code uses the Jupyter Notebook `kernel.execute` function, but that isn't available on a Bokeh server.

Maybe I'm fundamentally misunderstanding your comment (and the Bokeh architecture) though and what you're saying is that at the moment it's impossible to communicate the frame dimensions to the Bokeh server, even if I extract them within the CustomJS callback? But surely there must be a way to push two numbers to the Bokeh server?

```python
import bokeh.plotting
import bokeh.io
import numpy

jscode = """
var id = '%s';
var plot = Bokeh.index[id];
console.log(plot.frame.get('width'))
console.log(plot.frame.get('height'))
"""

bokeh.io.output_notebook()

x = numpy.linspace(0, 10, 100)
y = x + numpy.random.random(100)

p = bokeh.plotting.figure(x_range=[0, 10])
mycallback = bokeh.models.CustomJS(code=jscode % (p._id), args=dict(x_range=p.x_range) )

l = p.line(x, y)
p.x_range.callback = mycallback

bokeh.plotting.show(p)
```

**Comment by bryevdv** [comment]
@jdugge you are correct that `InteractiveImage` is only relevant for the notebook. One of the many features we would like to add is a generic "namespace" model that can be used to sync arbitrary "variables" between client and server. That would be another way to communicate this info, no one has had the opportunity to work on it yet. In the mean, time one method I can think of is to use a dummy column data source that you pass to the CustomJS callback to sync "variables" like this.  That's definitely fairly "hacky" but it should also work.

**Comment by brendancol** [comment]
@jdugge Here is an example of the "hacky" appoarch of updating a dummy column data source:

```python
from bokeh.io import curdoc
from bokeh.models import CustomJS, ColumnDataSource
import numpy
import pdb

from bokeh.plotting import Figure

jscode = """
var id = '%s';
var cid = '%s';
var plot = Bokeh.index[id];
var ds = plot.renderers[cid].model.get('data_source');
var updated_data = {};
updated_data['x'] = [];
updated_data['y'] = [];
updated_data['fh'] = [plot.frame.get('height')];
updated_data['fw'] = [plot.frame.get('width')];
debugger;
ds.set('data', updated_data);
"""

# here is the server callback which will contain updated frame dimensions
def on_source_change(attr, old, new):
    print(new)
    pdb.set_trace()

x = numpy.linspace(0, 10, 100)
y = x + numpy.random.random(100)

p = Figure(x_range=(0, 10), y_range=(0,100))


column_data_source = ColumnDataSource(data=dict(x=[],
                                                y=[],
                                                fh=[],
                                                fw=[]))
column_data_source.on_change('data', on_source_change)
r = p.circle(x='x', y='y', source=column_data_source)
mycallback = CustomJS(code=jscode % (p._id, r._id), args=dict(x_range=p.x_range) )
p.x_range.callback = mycallback
curdoc().add_root(p)

```

**Comment by bryevdv** [comment]
@brendancol I think that will run into problems with uneven column lengths, if the circle render is actually used and there is more than one data point to plot. I had in mind a completely separate column data source, that gets passed as with `args` to the `CustomJS` initializer, that is used for nothing except passing the frame dimensions.

**Comment by brendancol** [comment]
Yes, much better.  @jdugge I have updated the example above accordingly...

**Comment by bryevdv** [comment]
I still think this needs a bit more to flesh it out. It only updates when the data ranges update, not when the  actual screen dimensions of the inner frame change, which can change independently  of the data range.  Also it needs `plot.get('frame')` not `plot.frame`

**Comment by bryevdv** [comment]
Here's an updated version: 
```
from bokeh.io import curdoc
from bokeh.models import CustomJS, ColumnDataSource
import numpy

from bokeh.plotting import Figure

jscode = """
var new_data = {};
new_data['height'] = [plot.get('frame').get('height')];
new_data['width'] = [plot.get('frame').get('width')];
console.log(new_data);
dims.set('data', new_data);
"""

def update_dims(attr, old, new):
    print(new)

x = numpy.linspace(0, 10, 100)
y = x + numpy.random.random(100)

p = Figure(x_range=(0, 10), y_range=(0, 100))

dims = ColumnDataSource(data=dict(width=[], height=[]))
dims.on_change('data', update_dims)

p.x_range.callback = CustomJS(code=jscode, args=dict(plot=p, dims=dims))

curdoc().add_root(p)
```
To really make this work, I think `jscode` has to (one time) add a callback to frame to make the update to the data as well.

Also aren't the frame width and height essentially the canvas width and height (not the inner dimensions)?

**Comment by bryevdv** [comment]
Yes, you'd need to look at `h_range` and `v_range` on the frame, which have the dimensions of the "inner" rectangular area.

**Comment by bryevdv** [comment]
This would be another use case for "plot lifecycle" js callbacks. Putting a callback on the data range to put a callback on the frame is pretty silly and annoying.

**Comment by jdugge** [comment]
@bryevdv, @brendancol Thanks so much, that works beautifully! Even without a callback on the `frame` object, this should be fine for my use case (pixel-precise downsampling). It's far more important that the data gets regenerated appropriately when the range changes than when the dimensions of the frame change.

Nonetheless, I did try to implement your suggestion for making the `jscode` add a callback to the `frame` object so the `dims` data source also gets updated when the frame dimensions change. I feel like I should be able to register the callback using the `add_dependencies` function of the `frame` object, but I haven't been able to figure out the correct syntax. If you find the time, a hint on how to register a JavaScript-side callback that monitors a property change would be much appreciated.

Anyway, I'm already pretty happy with the result of this discussion, so feel free to close this issue in case you don't have more time to spend on it. Thanks for all your hard work!

**Comment by bryevdv** [comment]
@jdugge ah that does seem reasonable, but `add_dependencies` is actually a method to note dependent attributes for computed properties. With any luck we will get rid of compute properties (and that method). BokehJS models are Backbone models, so you can add callbacks using the standard BB `listenTo` something like: ` @listenTo(model, 'change', callback)`

In any case I am glad it's working out already! I will go ahead and close this discussion for now

**Comment by bill10** [comment]
Great to see that this feature is added to 0.12. Does it mean that I can call p.frame.callback instead of p.x_range.callback to get frame size? Thank you

**Comment by allefeld** [comment]
I came across this issue searching for a solution for a similar problem as the OP's. I found that the frame size seems to be exposed now, as `frame_width` and `frame_height`. Unfortunately, these properties appear to be always `None`?

**Comment by danwild** [comment]
I just spent waay too long looking for this, and it was [right there in front of me all along...](https://docs.bokeh.org/en/2.4.1/docs/reference/plotting/figure.html#bokeh.plotting.Figure.inner_height)

If you're reading this, you probably want `inner_width` and `inner_height`
