### ISSUE TITLE
TimeSeries in Bokeh using a dataframe with index

### ISSUE THREAD

**Issue by manuvazquez** [bokeh/bokeh#3763]
I'm trying to use Bokeh to plot a Pandas dataframe with a `DateTime` column containing years and a numeric one. If the DateTime is specified as `x`, the behaviour is the expected (years in the x-axis). However, if I use `set_index` to turn the DateTime column into the index of the dataframe and then only specify the `y` in the TimeSeries I get time in milliseconds in the x-axis. A minimal example

```
output_file('fig.html')
test = pd.DataFrame({'datetime':pd.date_range('1/1/1880', periods=2000),'foo':np.arange(2000)})
fig = TimeSeries(test,x='datetime',y='foo')
show(fig)

output_file('fig2.html')
test = test.set_index('datetime')
fig2 = TimeSeries(test,y='foo')
show(fig2)
```

I would expect the same picture with both approaches. Also, after the second plot, the dataframe contains an extra column `index`

This happens in Bokeh 0.11 and Pandas 0.16.2. Browser is Chromium 48 in Linux.

Cheers!!

**Comment by jdugge** [comment]
The issue with the `DataFrame` containing a new column after the call to `TimeSeries` is also reported in #3899.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/22)
