### ISSUE TITLE
AJAJ Support for Hovertools?

### ISSUE THREAD

**Issue by nickstanisha** [bokeh/bokeh#3764]
So I have a scatter plot where each point represents an entity in a JSON data store.  When points in the scatter plot are hovered over, I would like to request, parse, and display certain fields of the JSON in a stylized way (for example: name, age, favorite color, etc.).  Is there currently support for this in Bokeh?

I know that you can write your own HTML for tooltips, so you could theoretically put some Javascript between \<script\> tags, but I haven't seen any examples online or any indication that it is supported.

**Comment by birdsarah** [comment]
Hi Nick,

This is possible, will require a little JS from you.

Here's the documentation on CustomJS for Hover:
http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#customjs-for-hover

The basic idea will be:

* set-up an empty/dummy data source that holds the data for the tooltips
* in your CustomJS code get the data you need and then fill it into the
custom data source.

For examples of updating a data source in a CustomJS there are more in
the docs and also in the examples folder: e.g.
http://nbviewer.jupyter.org/github/bokeh/bokeh/blob/master/examples/howto/Range%20update%20callback.ipynb

HTH,

Bird

**Comment by bryevdv** [comment]
Closing, as this is a support question which belongs on the mailing list.
