### ISSUE TITLE
BokehJS - get_model_by_name() - multiple name error

### ISSUE THREAD

**Issue by jeffreyjharris** [bokeh/bokeh#3771]
The 'name' property for a single named ColumnDataSource is getting added for each glyph in a plot. As a result, get_model_by_name() in javascript fails with an error.

**Example**:
In Python define a single ColumnDataSource with a 'name' property as the source for 2 glyphs:
```
x = list(range(-20, 21))
y = [abs(xx) for xx in x]
source = ColumnDataSource(data=dict(x=x, y=y),name='something')
p = figure(tools=TOOLS, width=300, height=300)
p.circle('x', 'y0', source=source)
p.line('x', 'y0', source=source)
show(p)
```

In Javascript attempt to access the single ColumnDataSource  by name.  get_model_by_name() errors as the name appears multiple times:  
```
 var source_name = 'something';
 var plot_ids = Bokeh._.keys(Bokeh.index)
 for (i = 0; i < plot_ids.length; i++) {
    var plot = Bokeh.index[plot_ids[i]]
    var d  = plot.model.document.get_model_by_name(source_name)   // error here.
    if( d != null ) { 
        		my_data = d.attributes.data
    }
 }
```

Environment:
Mac: OS X Yosemite (10.10.5)
Bokeh: 0.11.0
Browser: Safari (9.02)
Generating plot from spyder 2.3.8; python 3.5; conda environment.

If there is only a single glyph on the plot the above works, but fails with 2 or more glyphs referencing the same ColumnDataSource.

**Comment by bryevdv** [comment]
fixed at some point, this code working in `0.12`
```
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show
x = list(range(-20, 21))
y = [abs(xx) for xx in x]
source = ColumnDataSource(data=dict(x=x, y=y),name='something')
p = figure(tools="pan", width=300, height=300)
p.circle('x', 'y', source=source)
p.line('x', 'y', source=source)
show(p)
```
<img width="307" alt="screen shot 2016-07-03 at 12 17 54 am" src="https://cloud.githubusercontent.com/assets/1078448/16543872/b4c0397a-40b3-11e6-97e1-a14c07e8de5c.png">
