### ISSUE TITLE
BoxPlot chart crashing with pandas.cut() categorical data

### ISSUE THREAD

**Issue by chbrandt** [bokeh/bokeh#3772]
bokeh.**version** : '0.11.0'
pandas.**version** : '0.17.1'

 When I try to do `BoxPlot` using categorical data generated by Pandas 'cut' method, the code crashes with `ValueError: items in new_categories are not the same as in old categories`. The exception is raised by `pandas/core/categorical.py` code, but I suspect the source of the error comes from Bokeh. The reason I think it starts at Bokeh (`bokeh/charts/data_source.groupby()`) is because using the pandas.DataFrame builtin `boxplot()` function everything runs properly.

The following code should reproduce the error:

```
import numpy as np
import pandas as pd
signal = np.random.normal(0.5,0.1,900) 
instr = np.random.poisson(0.5,100)
sample = np.concatenate((signal,instr),axis=0)
np.random.shuffle(sample)
df = pd.DataFrame({'sample':sample})
nbins = 10
bins = np.linspace(0,1,nbins)
df['bins'] = pd.cut(df['sample'],bins)
from bokeh.charts import BoxPlot
p = BoxPlot(df,values='sample',label='bins')
```

If instead of `bokeh.charts.BoxPlot` we use Pandas' boxplot, everything works fine:

```
df.boxplot(column='sample',by='bins')
```

Am I doing something wrong?
If it's a bug, possibly related to pydata/pandas#10505?

ps: there is a notebook I made available for if it helps. The notebook has more steps then the strictly necessary ones (above), though: http://nbviewer.jupyter.org/github/chbrandt/pynotes/blob/master/issues/bokeh/boxplot_report.ipynb

Tnx

**Comment by bryevdv** [comment]
I think it issue is that Bokeh is not expecting the "tuples" (range objects?) that comprise `df['bins']`. If I so
```
df['foo'] = [str(x) for x in df['bins']]
```
and then 
```
p = BoxPlot(df,values='sample',label='foo')
```
Then I get the following output:
<img width="591" alt="screen shot 2016-04-08 at 2 54 40 pm" src="https://cloud.githubusercontent.com/assets/1078448/14395852/eb63fb90-fd99-11e5-96fb-5d759368b428.png">

ping @fpliger

**Comment by chbrandt** [comment]
Indeed. It happens when a category/group has no data at all (i.e, count is 0). When that happens, the underlying (temporary) pandas dataframe has its set of categories slightly modified to *not* include the categories/groups with no data points. That raises the "`ValueError`" exception.

Please, consider the lines below, from my (ipython session) error stack. Their importance here is just to show the `print` statements I added before the statements raising the expection, so that I/we could see what's going on there.
```
/home/chbrandt/.conda/envs/bokeh/lib/python2.7/site-packages/pandas/core/categorical.py in reorder_categories(self, new_categories, ordered, inplace)
    750             print('old',self._categories)
    751             print('new',new_categories)
--> 752             raise ValueError("items in new_categories are not the same as in "
    753                              "old categories")
    754         return self.set_categories(new_categories, ordered=ordered,

ValueError: items in new_categories are not the same as in old categories
```

The output of those `print` statements were:
```
('old', Index([u'(0, 0.111]', u'(0.111, 0.222]', u'(0.222, 0.333]', u'(0.333, 0.444]',
       u'(0.444, 0.556]', u'(0.556, 0.667]', u'(0.667, 0.778]',
       u'(0.778, 0.889]', u'(0.889, 1]'],
      dtype='object'))
('new', Index([u'(0.111, 0.222]', u'(0.222, 0.333]', u'(0.333, 0.444]',
       u'(0.444, 0.556]', u'(0.556, 0.667]', u'(0.667, 0.778]',
       u'(0.778, 0.889]', u'(0.889, 1]'],
      dtype='object'))
```

for a `df['bins']`:
```
In [11]: print df.groupby('bins').describe()
                          sample
bins                            
(0, 0.111]     count    0.000000
               mean          NaN
               std           NaN
               min           NaN
               25%           NaN
               50%           NaN
               75%           NaN
               max           NaN
(0.111, 0.222] count    4.000000
               mean     0.185796
               std      0.032048
               min      0.146416
               25%      0.168076
               50%      0.188323
               75%      0.206043
               max      0.220123
(0.222, 0.333] count   41.000000
               mean     0.295456
               std      0.030646
               min      0.230628
               25%      0.268799
               50%      0.301024
               75%      0.322251
               max      0.332008
(0.333, 0.444] count  210.000000
               mean     0.403149
               std      0.028687
               min      0.333867
               25%      0.384952
               50%      0.410550
...                          ...
(0.556, 0.667] std      0.030666
               min      0.556069
               25%      0.572129
               50%      0.598299
               75%      0.623799
               max      0.666195
(0.667, 0.778] count   48.000000
               mean     0.705072
               std      0.028176
               min      0.668035
               25%      0.682577
               50%      0.698252
               75%      0.720471
               max      0.773071
(0.778, 0.889] count    3.000000
               mean     0.797906
               std      0.018524
               min      0.783047
               25%      0.787529
               50%      0.792011
               75%      0.805335
               max      0.818660
(0.889, 1]     count   28.000000
               mean     1.000000
               std      0.000000
               min      1.000000
               25%      1.000000
               50%      1.000000
               75%      1.000000
               max      1.000000

[72 rows x 1 columns]
```

We can see the match between the missing category "`(0, 0.111]`", its contents and the raised exception.

**Comment by chbrandt** [comment]
If we slightly modify the original code example to include/guarantee that every category has at least one data point, we avoid the crash:
```
import numpy as np
import pandas as pd
signal = np.random.normal(0.5,0.1,900) 
instr = np.random.poisson(0.5,100)
sample = np.concatenate((signal,instr),axis=0)
nbins = 10
bins = np.linspace(0,1,nbins)
#
_b = bins[:-1]+np.diff(bins)/2          # new line, guaranteeing non-empty categories
#
sample = np.append(sample,_b)
np.random.shuffle(sample)
df = pd.DataFrame({'sample':sample})
df['bins'] = pd.cut(df['sample'],bins)

from bokeh.charts import BoxPlot
p = BoxPlot(df,values='sample',label='bins')

from bokeh.plotting import show,output_file
output_file('tmp.html')
show(p)
```

**Comment by chbrandt** [comment]
The code following code block add a couple of statements to the above one just to deal with `nan` values.

Thanks @bryevdv to highlight this issue on the original data handling.

The code below should just work. But take the line `_b = bins[:-1]+np.diff(bins)/2` out and the issue should show up again.

```
import numpy as np
import pandas as pd
signal = np.random.normal(0.5,0.1,900) 
instr = np.random.poisson(0.5,100)
sample = np.concatenate((signal,instr),axis=0)
nbins = 10
bins = np.linspace(0,1,nbins)

# Guarantee we'll have categories for "below 0" values (not the case here, but doesn't hurt to do it either)
bins = np.unique(np.insert(bins,0,sample.min()))
# Guarantee we'll have categories for "above 1" values
bins = np.unique(np.insert(bins,-1,sample.max()))

# --- HACK ---
_b = bins[:-1]+np.diff(bins)/2          # Guarantee non-empty categories
sample = np.append(sample,_b)
# ---

np.random.shuffle(sample)
df = pd.DataFrame({'sample':sample})
df['bins'] = pd.cut(df['sample'],bins,include_lowest=True)     # 'include_lowest' for left closed intervals

from bokeh.charts import BoxPlot
p = BoxPlot(df,values='sample',label='bins')

from bokeh.plotting import show,output_file
output_file('tmp.html')
show(p)
```

**Comment by bryevdv** [comment]
OK so it looks like my supposition about the ranges not working was incorrect? IIUC the problem was the `nan`. In that case it seems like some check to discard `nan` would solve this issue?

**Comment by chbrandt** [comment]
Sorry about the mess/too-much information.

- The problem occurs when there is *no data* in (at least) one DataFrame category (number of data points, "count" is zero)

- Your work-around *does* work! [https://github.com/bokeh/bokeh/issues/3772#issuecomment-207577091]
  - But it is not because Bokeh is not expeting "tuples".
  - It is because somewhere between Panda and Bokeh the set of categories is being changed: labels/ranges corresponding to categories with no data points are being dropped. [https://github.com/bokeh/bokeh/issues/3772#issuecomment-208273038]

**Comment by chbrandt** [comment]
OK. Went a bit deeper here and found the place where categories are being modified.

It is inside Pandas, not Bokeh.

Categories are being modified at line https://github.com/pydata/pandas/blob/master/pandas/core/groupby.py#L2179 from file `pandas/core/groupby.py`:
```
else:
    cat = self.grouper.unique()
```
and then, in the next line a function `reorder_categories()` raises the exception.

`self.grouper` is the categorical column `df['bins']` in our case.

So, after running the code snippet:
```
import numpy as np
import pandas as pd
signal = np.random.normal(0.5,0.1,900) 
instr = np.random.poisson(0.5,100)
sample = np.concatenate((signal,instr),axis=0)
np.random.shuffle(sample)
df = pd.DataFrame({'sample':sample})
nbins = 10
bins = np.linspace(0,1,nbins)
df['bins'] = pd.cut(df['sample'],bins)
```

we can see what is going on with the "bins":
```
In [8]: df['bins'].tail()
Out[8]: 
995    (0.333, 0.444]
996    (0.556, 0.667]
997    (0.333, 0.444]
998    (0.444, 0.556]
999    (0.333, 0.444]
Name: bins, dtype: category
Categories (9, object): [(0, 0.111] < (0.111, 0.222] < (0.222, 0.333] < (0.333, 0.444] < ... <
                         (0.556, 0.667] < (0.667, 0.778] < (0.778, 0.889] < (0.889, 1]]

In [9]: df['bins'].unique()
Out[9]: 
[(0.333, 0.444], (0.556, 0.667], (0.444, 0.556], NaN, (0.667, 0.778], (0.222, 0.333], (0.889, 1], (0.778, 0.889], (0.111, 0.222]]
Categories (8, object): [(0.111, 0.222] < (0.222, 0.333] < (0.333, 0.444] < (0.444, 0.556] <
                         (0.556, 0.667] < (0.667, 0.778] < (0.778, 0.889] < (0.889, 1]]
```

For some reason, Pandas is (blindly) dropping the empty category. I think that the DataFrame `unique()` function should not be doing so...

**Comment by fpliger** [comment]
Honestly I'm not sure the best way to deal with it.... I'll try to take a look at this later today.

**Comment by fpliger** [comment]
Ok, quick update... I think there's a broken logic on the `pandas` side since calling `df.groupby(spec_cols, sort=False)` with the first example code posted raises the error but `df.groupby(spec_cols, sort=True)` surprisingly doesn't and we could call this instead.. (making some changes since we will end up with a missing key) but it still trims the group with `count==0` which I don't think it should. 

I'm not sure I get the full picture here though since it actually seem to be related to `nan`s since adding `df['bins'] = df.bins.fillna('(0, 0.111]')` to the first code example seems to fix the issue. Maybe I'm overseeing something @chbrandt ?

**Comment by chbrandt** [comment]
@fpliger You are right: the issue is related to `nan`s. Filling the `nan` holes with some real value (for instance, "0") does solve the problem.

A comment on the "`df.groupby(..., sort=True|False)`" aspect: I didn't follow the whole processing, but at the the corresponding `if/else` [block](https://github.com/pydata/pandas/blob/master/pandas/core/groupby.py#L2166) the data is not guaranteed to have the same consistency when flowing on each side. Also, it is not clear to me what is desired to flow out of that block of code, once the `unique()` [function](https://github.com/pydata/pandas/blob/master/pandas/core/categorical.py#L1677) says "_Return the ``Categorical`` which ``categories`` and ``codes`` are unique. Unused categories are NOT returned._"

By all means -- I should point out -- it is not reasonable from my side to plot an empty dataset (for instance, the empty category). My fault on that. But what about put some level of verification anyway, and tell the user (s)he is trying to plot an empty container?

Thanks.

**Comment by fpliger** [comment]
> @fpliger You are right: the issue is related to nans. Filling the nan holes with some real value (for instance, "0") does solve the problem.
> 
> A comment on the "df.groupby(..., sort=True|False)" aspect: I didn't follow the whole processing, but at the the corresponding if/else block the data is not guaranteed to have the same consistency when flowing on each side. Also, it is not clear to me what is desired to flow out of that block of code, once the unique() function says "Return the Categorical which categories and codes are unique. Unused categories are NOT returned."

Yeap.. that's my concern as well. The no consistency leads me to think it's not intended..  I'll follow up with the `pandas` folks with this aspect.

The "not return unused categories" is a reasonable choice but I'd much better prefer a flag that let's the user specify if it wants the unused categories or not.


> By all means -- I should point out -- it is not reasonable from my side to plot an empty dataset (for instance, the empty category). My fault on that. But what about put some level of verification anyway, and tell the user (s)he is trying to plot an empty container?

@chbrandt  +1. That's a good suggestion and would hole users. So, to check if we are on the same page, could you provide an example that shows off this use case?

**Comment by chbrandt** [comment]
OK, I think so...
I can see two ways of approaching that:

1. to verify the consistency of `Boxplot(..., label)` data at the [function itself](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/boxplot_builder.py#L35) and possibly return `None` to the user if something looks faulty.
2. to verify the consistency of the data when the [chart object](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/boxplot_builder.py#L112) (or its parent, the [bar chart](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/bar_builder.py#L39) once the issue affects pops out there) is being constructed. If something is not OK though, the data should be fixed (hmm?) or an empty/null chart should be built.

Well, if that matters, usually I go with functional programming solutions (1), and if the solution is simple I try to ease the user (me:)) life handling the issue and warning a message; otherwise, if it's too complicated I just return `None` and an error message.

For instance, I'd go with:
```
def BoxPlot(df,values,label,check_categories=False,remove_unused_categories=True):
    """
    If 'label' is Pandas.Categorical, check whether there is any unused one.
    """
    if check_categories:
        from pandas import Categorical as pdcat
        if df[label].dtype == pdcat.dtype:
            gc = df.groupby(label).count()
            empties = gc.loc[gc['sample']==0].index.tolist()
            _msg = "Warning: dataset contains empty {} categories.".format(empties)
            if remove_unused_categories:
                df = df[[values,label]]
                df[label] = df[label].cat.remove_unused_categories()
                _msg += "Unused categories were removed from dataset."
                print(_msg)
            else:
                _msg += "Returning 'None' plot since I don't know how to handle empty datasets."
                print(_msg)
                return None
    from bokeh.charts import BoxPlot as bplot
    return bplot(df,values=values,label=label)
```
@fpliger is that what you were expecting with "use case"?

Thanks

**Comment by fpliger** [comment]
> I can see two ways of approaching that:
> 
> to verify the consistency of Boxplot(..., label) data at the function itself and possibly return None to the user if something looks faulty.
> to verify the consistency of the data when the chart object (or its parent, the bar chart once the issue affects pops out there) is being constructed. If something is not OK though, the data should be fixed (hmm?) or an empty/null chart should be built.

The aspect that is not great about both proposals is that they will break things (at some point) later.. and will break consistency about how we manage these things. So I'd rather propose to:

1. raise an error with a better and more meaningful message then "ValueError: items in new_categories are not the same as in old categories" 

or 

2. to raise a warning if we decide to automagically "fix" the dataset to remove the unused categories. 

The pro about 2 is that it "just works" and user will not have to bother about changing her/his original dataset but sometimes it doesn't mean it works the way user would expect.. Maybe we can have more opinions?

> @fpliger is that what you were expecting with "use case"?

I was expecting something like: "given thins input `data=.... ` I'd expect `BoxPIot(data, ...)` to ... So that's actually more then I was expecting, thanks. It's a valuable feedback :)

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/20)
