### ISSUE TITLE
BoxPlot chart wrongly ordering categorical data

### ISSUE THREAD

**Issue by chbrandt** [bokeh/bokeh#3773]
bokeh.**version** : '0.11.0'
pandas.**version** : '0.17.1'

When doing a BoxPlot chart with categories generated by Pandas `qcut()` function, the first category (data and label) are shift to the last position in the (x) axis.

Such plot can be seeing running the folowing code:

```
import numpy as np
import pandas as pd
signal = np.random.normal(0.5,0.1,900) 
instr = np.random.poisson(0.5,100)
sample = np.concatenate((signal,instr),axis=0)
np.random.shuffle(sample)
df = pd.DataFrame({'sample':sample})
nbins = 10
df['quantil'] = pd.qcut(df['sample'],nbins)
from bokeh.io import show,output_file
from bokeh.charts import BoxPlot
output_file('boxplot.html')
p = BoxPlot(df,values='sample',label='quantil')
show(p)
```

![image](https://cloud.githubusercontent.com/assets/482051/12674343/bdf21abe-c682-11e5-9c25-bfc43aaef3e1.png)

There is a notebook I made available for if it helps: http://nbviewer.jupyter.org/github/chbrandt/pynotes/blob/master/issues/bokeh/boxplot_report.ipynb

Tnx

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/19)
