### ISSUE TITLE
MPL shifting pandas boxplot

### ISSUE THREAD

**Issue by chbrandt** [bokeh/bokeh#3774]
bokeh.__version__ : '0.11.0'
pandas.__version__ : '0.17.1'

When using `bokeh.mpl` to display (in a notebook) the plot generated by `pandas.DataFrame.boxplot()` the resulting plot has its data shifted rightwards.
The following code snippets should reproduce it:
```
import numpy as np
import pandas as pd
signal = np.random.normal(0.5,0.1,900) 
instr = np.random.poisson(0.5,100)
sample = np.concatenate((signal,instr),axis=0)
np.random.shuffle(sample)
df = pd.DataFrame({'sample':sample})
nbins = 10
df['quantil'] = pd.qcut(df['sample'],nbins)

from bokeh.io import show,output_file
output_file('boxplot_mpl.html')

import matplotlib.pyplot as plt
df.boxplot(column='sample',by='quantil')
plt.ylim([0,1.1])
plt.xticks(rotation=90)

from bokeh import mpl
show(mpl.to_bokeh())
```
Here is the (wrong) figure:
![bxp_shift_wrong](https://cloud.githubusercontent.com/assets/482051/12674144/8fd04602-c681-11e5-9f6b-3aabdb8b62fe.png)

If instead we use (in place of the last two lines) matplotlib directly
```
plt.show()
```
we should see the correct plot:
![bxp_shift_right](https://cloud.githubusercontent.com/assets/482051/12674157/a934e4ae-c681-11e5-8f7a-fa6c8857de26.png)
 

There is notebook I made available, if it helps. At the very end of [this notebook](http://nbviewer.jupyter.org/github/chbrandt/pynotes/blob/master/issues/bokeh/boxplot_report.ipynb) we can see the difference/error.

[]

**Comment by chbrandt** [comment]
Related/same issues #2277 , #3130

**Comment by bryevdv** [comment]
@chbrandt is there any chance that you could take a look into this issue? There's now more issues/work than the current core dev team can really deal with directly, so I am trying to make a point to solicit new contributions. Any problem is almost certainly contained in one of the few files in `bokeh/core/compat`

**Comment by chbrandt** [comment]
@bryevdv  Sure.
