### ISSUE TITLE
bokeh serve callbacks from notebooks

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3776]
Apps generated from notebooks that have callbacks cannot automatically define callbacks that can be tested on the notebook easily and just work as serve side callbacks. We should find a way to make it possbile. 

One possibility could be to monkeypatch (on the server side) ipython widgets that can be used to interact with the bokeh plots/widgets on the notebook and create the related bokeh widget (to replace the notebook ones) on the server and make it available on the same document.

The downside of that is that users would not have much control on this widget and how it integrates with the layout (unless we don't provide something to spell that)

**Comment by brendancol** [comment]
@prudiger recently shared this example which calls a python function using CustomJS + notebook kernel.execute()

```python
import numpy as np

from bokeh.plotting import figure, output_notebook, show
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.io import push_notebook

output_notebook()
        
jscode="""
        // Define a callback to capture errors on the Python side
        function callback(msg){
            console.log("Python callback returned unexpected message:", msg)
        }
        callbacks = {iopub: {output: callback}};

        // Generate a command to execute in Python
        var ranges = {x0: x_range.attributes.start,
                      y0: y_range.attributes.start,
                      x1: x_range.attributes.end,
                      y1: y_range.attributes.end}
        var range_str = JSON.stringify(ranges)
        var cmd = "%s(" + range_str + ")"
        
        // Execute the command on the Python kernel
        var kernel = IPython.notebook.kernel;
        kernel.execute(cmd, callbacks, {silent : false});
"""

p = figure(plot_width=400, plot_height=400, x_range=(0, 10), y_range=(0, 10))

def normalize_points(ranges):
    """
    Normalizes the points into the current range and
    pushes the updated data via push_notebook.
    """
    xvals = np.linspace(ranges['x0'], ranges['x1'], 100)
    yvals = source.data['y']
    normed = (yvals - yvals.min()) / (yvals.max()-yvals.min())
    ranged = normed * (ranges['y1'] - ranges['y0']) + ranges['y0']
    source.data.update({'x': xvals,  'y': ranged})
    push_notebook()

source = ColumnDataSource(data=dict(x=np.linspace(0, 10, 100), y=np.random.rand(100)*10))
p.circle('x', 'y', source=source)
    
p.x_range.callback = CustomJS(
        args=dict(source=source, x_range=p.x_range, y_range=p.y_range), code=jscode % 'normalize_points')
p.y_range.callback = CustomJS(
        args=dict(source=source, x_range=p.x_range, y_range=p.y_range), code=jscode % 'normalize_points')

show(p)
```

**Comment by philippjfr** [comment]
I've made a PR on datashader (https://github.com/bokeh/datashader/pull/36 ) to support IPython kernel in the notebook. It works fairly well but it also still has some issues that I list there. In particular I've had to bypass the regular ``show`` machinery and rely on low-level private APIs because I couldn't get it to update multiple plots in the notebook.

**Comment by bryevdv** [comment]
Closing, given the work that went into `0.12.5` to support apps in notebooks.
