### ISSUE TITLE
Is there an equivalent to plot_object.dump()

### ISSUE THREAD

**Issue by jfrydendall** [bokeh/bokeh#3782]
I just upgraded to version 0.11.0 via conda.

Everything seems to work as expected. However, I see that the .dump() method is gone from the plot_object. Is there an equivalent to this method in 0.11.0?
Or can I reproduce the old .dump() by other means?

Thanks for a great product

**Comment by mattpap** [comment]
Yes, use `obj.to_json(False)`. Or you could use `obj.to_json_string(False)` .

**Comment by bryevdv** [comment]
if you'd like do generate the JSON that a script or app would generate from the command line, there is also the `bokeh json` command you can run.

**Comment by jfrydendall** [comment]
the `obj.to_json(False)` does not reproduce the `old obj.dump()` There is no plot data included in the returned JSON.

In my code  I have a intermediate step where I store the bokeh plot_obj to a database. I do so because I need to have a log of all previous events that has happen to the model I run. The model is very large and cannot be rerun again without it taken days of calculation time. 

So I pickle the plot_obj and save it to a database as a largebinary. I feed it in to the BokehScript via jinja and all_models. 

Does the `bokeh.embed import _standalone_docs_json_and_render_items` not reproduce the `.dump()` method?

**Comment by bryevdv** [comment]
See the implementation of https://github.com/bokeh/bokeh/blob/master/bokeh/command/subcommands/json.py

**Comment by mattpap** [comment]
@jfrydendall, so actually to reproduce `obj.dump()`, you have to go through a `Document`, e.g.:
```
from bokeh.models import Plot
from bokeh.document import Document
p = Plot()
d = Document()
d.add_root(p)
d.to_json()
```
This is pretty much what `_standalone_docs_json_and_render_items()`, though it does more and returns output for (possible) multiple documents.

**Comment by jfrydendall** [comment]
Thank you very much for you suggestions. It did not quite do what I wanted to it to do.

I have reverted back to version 0.10.0 for now. I will try to figure out how to use the new bokeh features within my current setup before upgrading my production line.

Keep up the good work.
