### ISSUE TITLE
Reduce size of code from Crossfilter-"lite" example

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3788]
A good strategy for crossfilter is to have one example version (shows callbacks, UDM, etc.) and another bokeh cli command called `xfilter` to be the whole shebang.  To make the xfilter-lite example, code should be reduced and as simple as possible to highlight how one can build a bokeh app.

**Comment by damianavila** [comment]
@brendancol can you put a little explanation about why it was closed... or a link to the PR implementing/addressing this? Thanks!
