### ISSUE TITLE
Linked Crosshair

### ISSUE THREAD

**Issue by adriantorrie** [bokeh/bokeh#3799]
I plot multiple time-series vertically, but haven't come across any options or documentation that having linked crosshairs is possible, so I'm requesting this as a feature to be added (if it exists then please point me i nthe right direction).

Being able to move the mouse on one chart and see the corresponding crosshair on another would allow for quick inspection.

This feature, if coupled with #3000, would be very nice indeed.

**Comment by birdsarah** [comment]
Yes, agreed, this would be a nice feature.

**Comment by davidtrem** [comment]
I'm wondering if the linked crosshair is still alive (?)
If yes, to add some more thought to it, I guess it would be perfect if the crosshair would
be full (i.e. both vertical and horizontal) on the graph where the mouse pointer is and
only "kind of" **extended to all the shared axis**. For example if we refer to the doc example:
http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/linking.html#linked-panning
there is three linked graphs (s1, s2, s3)
which are linked that way: s1.x=s2.x=s3.x and s1y=s2.y
then:
 - if the mouse point is either on graph 1 or 2 the full crosshair should appear at the same place on graph 1 and 2, and only a the vertical bar should appear on graph 3.
- if the mouse pointer is on graph 3 the full crosshair appear on graph 3 and only a vertical bar appear on graph 1 and 2

Any idea where I should start to dig in to implement such feature ?

**Comment by ilayn** [comment]
Is there any progress on this feature? Anything along these lines would be beneficial for my use case. 

For what is worth, my use case is a little more convoluted but please take it as food for thought. I don't expect this to be a feature to be added in the near future. I'm trying to draw Bode plots for control-theoretic purpuses. There are also the so-called Nyquist plots. 

The data has two parameters. The frequency and the corresponding response of the system which is a complex number. Hence the bode and nyquist are different representations of the same data. In the bode case, a pair of plots are drawn one for the magnitude of the complex number against frequency and the other is the argument(angle) of the complex number frequency. 

The nyquist diagram is basically marking the complex numbers on a real-imag plane hence define a curve parametrized with frequency. I've added an image below for something in action

![Bode_Nyquist_img](http://i.stack.imgur.com/Zmvsh.png)

Linking the crosshairs would be nice for me if I hover over the bode plot, the nyquist follows the curve wrt frequency. And similarly, if I hover over the nyquist curve the bode plots are snapped with the crosshair.

**Comment by alobbs** [comment]
Huge +1 for this one

**Comment by ilayn** [comment]
Since it is pinged let me put an amateurish solution I've did for the example above. Since things are logarithmically plotted it's a bit annoying to track the plot but hover over the right curves for easier tracking. 

http://nbviewer.jupyter.org/gist/ilayn/f8cf8b0a68c6839dbcc346884511e2ed

Please let me know if there is a smarter/easier way for this.

**Comment by alobbs** [comment]
@ilayn, thanks for the link!

It looks like you're solving a slightly different problem, though. As far as I understood, the request was for getting a applicable axis of the crosshairs plotted into contiguous charts.

Let's imagine, if I had two charts stacked vertically, this feature would draw the Y axis of the crosshairs in the at the same offset that my mouse pointer is currently at, just in the chart it is not currently over.

**Comment by kernc** [comment]
To satisfy both cases, perhaps that could be an option: whether crosshairs share screen (mouse) coordinates or data coordinates.

**Comment by graeme-hattan** [comment]
If anyone is looking for a workaround for this, I managed to get basic linked crosshair functionality with JavaScript callbacks. See my SO answer for more details - https://stackoverflow.com/a/51251614/2801913

**Comment by 1081** [comment]
> If anyone is looking for a workaround for this, I managed to get basic linked crosshair functionality with JavaScript callbacks. See my SO answer for more details - https://stackoverflow.com/a/51251614/2801913

Unfortunately, this workaround does not work anymore. Is there any update or progress?
I tried this workaround:
```python
def sync_crosshair(plots: list[Figure]) -> None:
    crosshair = CrosshairTool(dimensions="height")
    for p in plots:
        p.add_tools(crosshair)
```
