### ISSUE TITLE
Migrate from RS into AWS+S3 for CDN

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#3806]
We need to migrate from Rackspace
- [ ] modify build script to push JS and CSS into AWS+S3
- [ ] evaluate the migration of the files already uploaded and served

**Comment by bryevdv** [comment]
@damianavila is this still true?

**Comment by damianavila** [comment]
Yep... I guess we don't have great pressure now but eventually we need to do it...

**Comment by bryevdv** [comment]
AFAIK there is no pressure to do this. If it comes up we will open a new issue, or re-open this one
