### ISSUE TITLE
Interactive Bokeh plots in Jupyter notebooks, without a separate server

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#3813]
As mentioned in https://github.com/bokeh/datashader/pull/36#issuecomment-179192409, for the datashader project Philipp Rudiger, Brendan Collins, and I created an object that accepts a Python function callback (anything that creates a PIL image) and a Bokeh plot, and then regenerates the image on the plot whenever the user zooms or pans.  This works well with datashading, but it would also work well for any custom code that can generate an image covering a certain portion of data space on demand.

There's an example of how to use it in 
https://github.com/bokeh/datashader/blob/master/examples/nyc_taxi.ipynb (currently the last cell):

```python
import datashader as ds
from datashader.callbacks import IPythonKernelCallback
from datashader import transfer_functions as tf

def create_image(x_range, y_range, w, h, how='log'):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.points(df, 'dropoff_x', 'dropoff_y', ds.count('passenger_count'))
    image = tf.interpolate(agg, "lightpink", 'red', how=how)
    return image

p = base_plot()
IPythonKernelCallback(p, create_image, how='linear')
```

As you can see, it lets the user write code that's very simple, yet it provides full interactivity, without needing them to fire up Bokeh server, manage ports, etc.  This seems like useful functionality to have in Bokeh in general, but I'm not sure where it would fit in, or whether it will be needed after the planned better integration of Bokeh server with Jupyter. 

I'd like to see it extended in three ways:

1. A previous version of callbacks.py used bokeh's show(), but it didn't work for multiple cells, and so Philipp replaced it with a direct call to _repr_html.  It would be nice if show() worked instead.
2. It would be good if the same user code could work with both Jupyter and with Bokeh server, either by instantiating one object that does both (this one only works with Jupyter), or by making it more naturally available from Bokeh's usual output and show mechanisms.
3. Right now it's hardcoded to create an image_rgba object, but the same mechanism could be useful for other objects, e.g. to do dynamic downsampling of scatter plots by providing different data depending on the zoom level.  It seems possible to ask for an additional Python function to create the plot object and maybe to update it, but that might be tricky to set up.

Anyway, it would be great if someone on the Bokeh team working on integration with Jupyter could think about this (@damianavila?  @fpliger?).  Some of the code involved is magic, relying on parts of Bokeh and IPython that we aren't sure won't change, so it's important to look at the actual code involved. For now we're going ahead with this as part of the separate library (though with IPythonKernelCallback probably changing to a simpler name, e.g. InteractiveCell).

**Comment by bryevdv** [comment]
The current plan to address #3461 suggested by @pzwang is to use the Bokeh server code as a library. So, use notebook comms to shunt Bokeh protocol messages to all the server code that handles updates, etc., but not actually run things in a separate process. That would seem to be a viable path, and a simplication in some ways for the notebook. Going to close this to continue the discussion in the other issue, since I also think this covers what you are asking about here. But please re-open if I am off base.

**Comment by jbednar** [comment]
This sounds like a good idea to me!
