### ISSUE TITLE
Toolbar Improvements: Active is programmable

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#3816]
Be able to programmatically set active on a toolbar widget.

**Comment by bryevdv** [comment]
This is actually a dupe of #3054 There is more discussion and information there, so I am closing this issue in favor of that one

**Comment by bryevdv** [comment]
@damianavila I suddenly wonder if duplicates ought never to have a milestone. Thoughts?

**Comment by damianavila** [comment]
>@damianavila I suddenly wonder if duplicates ought never to have a milestone. Thoughts?

Maybe... not sure... the milestone is probably a quick reference about when this was closed a duplicate... and IIRC duplicates are removed from the changelog... so there should not be a problem, although I also understand your position... mmm... as I said, not sure...
