### ISSUE TITLE
Toolbar Improvements: Make tools independent of bar

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#3819]

**Comment by MulticastMatt** [comment]
Byran - some of the work has already been done.  Mateusz has been working on it.  
Mateusz - The idea is that we will have a tool manager and a toolbar.  Rip out all the presentation stuff from tools, put it into a toolmanager, etc.  I did a hack yesterday for JPM.  Want to separate toolbar from plotting area. 
Sarah - the presenation layer of the toolbar will be a widget you can put anywhere?
