### ISSUE TITLE
BEP 6: Bokeh Project Governance

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3828]
This issue is to discuss polices regarding project governance.  This can include topics such as "core" team membership, and (eventually) fiduciary responsibility. 

The related BEP is located here: https://github.com/bokeh/bokeh/wiki/BEP-6:-Project-Governance

**Comment by bryevdv** [comment]
I'd like to start a discussion around policies for admitting new members to @bokeh/core I propose something along the lines of:

* anyone can nominate anyone to join @bokeh/core 
* some *specific* and *documented* form of [Consensus Decision Making](https://en.wikipedia.org/wiki/Consensus_decision-making) is used to facilitate the decision. Suggestions: "unanimous consent", or "near unanimous (U-1) agreement"

**Comment by damianavila** [comment]
@bryevdv you probably will find useful the model we use in the Jupyter community: https://github.com/jupyter/governance/blob/master/governance.md

In fact all the repo is useful: https://github.com/jupyter/governance

**Comment by birdsarah** [comment]
I have a lot of experience with the model described as "blocking" on the wikipedia page (https://en.wikipedia.org/wiki/Consensus_decision-making#Blocking).  Happy to share when needed.

**Comment by chalmerlowe** [comment]
I took the pandas governance docs that have been approved for use by NumFOCUS and edited them.
Also edited the Comprehensive FSA doc that NumFOCUS uses as the binding agreement.
All the docs are hosted here:
[https://github.com/chalmerlowe/bokeh_governance](https://github.com/chalmerlowe/bokeh_governance)

This is all based on a previous email thread with @birdsarah @bryevdv et al
Open questions have been submitted directly to @bryevdv @birdsarah and NumFOCUS.

**Comment by bryevdv** [comment]
Bokeh is now NF sponsored, any governance will be though the NF  committee
