### ISSUE TITLE
Documentation: Chart Defaults 

### ISSUE THREAD

**Issue by achalddave** [bokeh/bokeh#3833]
The documentation for chart defaults seems to be missing. 

http://bokeh.pydata.org/en/latest/docs/reference/charts.html#module-bokeh.charts points to http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#userguide-charts-defaults which points back to the first link to get a list of the Chart Defaults. I can't seem to actually find the list on either of those links, however.

**Comment by bryevdv** [comment]
Yes those docs seems broken. AFAIK `chart.defaults` can just have any property set on it that `Chart` can have set (including properties from the `Plot` base class) and then it is used to set those properties on any chart subsequently created. I'd say there's a very reasonable chance `charts.defaults` gets deprecated in the near future. The recently added general theming mechanism needs a few more features, but it can apply to al the APIs uniformly. Having to maintain a special different thing just for charts is an unjustifiable maintenance cost in my opinion.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/45)
