### ISSUE TITLE
Passing arguments to callbacks inside an array instead of as formals

### ISSUE THREAD

**Issue by saptarshiguha** [bokeh/bokeh#3835]
Hello,
I'm using the rbokeh package and recently it's been (still in development) extended to pass callbacks.
Bokeh passes the arguments to a callback (such as layer references) as formals.

I have a callback that will access many many different layers : possibly a few hundreds. That would mean a function with a few hundred formals.

Is there a way to call the callback with these arguments in an array?

So instead of callback(cb_obj,cb_data, arg1,arg2,...., arg150) it would be callback(cb_obj, cb_data, [arg1,arg2,...,arg150])

I have no complaints with a callback of 150 arguments unless that causes performance issues.

**Comment by birdsarah** [comment]
Hi @saptarshiguha, our issue tracker is becoming too large to manage easily. We have to reserve it for feature requests and bug reports only, to have any hope of taming it. This kind of general support question should go to the general public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
