### ISSUE TITLE
duck typing

### ISSUE THREAD

**Issue by jonycgn** [bokeh/bokeh#3836]
hi,

i have identified at least two instances in which bokeh doesn't behave like i would expect it to, given standard python practices. both come down to violations of the duck typing principle (which is one of the foundations python is built on), and they make my code a lot clumsier than necessary. also, because the error messages involved are not very helpful, it took me a long time to actually figure out what's going on.

here's the first instance. it shouldn't matter what type of container you pass, as long as it behaves as it is expected to. simple example:

    import numpy
    from bokeh.plotting import figure, show
    t = numpy.arange(10)
    x = numpy.linspace(1, 2, 10)
    p = figure()
    p.multi_line([t], [x])
    show(p)

if i replace `p.multi_line([t], [x])` with `p.multi_line(numpy.array([t]), numpy.array([x]))`, i get the following error:

    /users-local/balle/anaconda/envs/2016-02-03/lib/python2.7/site-packages/bokeh/plotting_helpers.pyc in _process_sequence_literals(glyphclass, kwargs, source)
        134 
        135         if isinstance(val, np.ndarray) and val.ndim != 1:
    --> 136             raise RuntimeError("Columns need to be 1D (%s is not)" % var)
        137 
        138         source.add(val, name=var)

    RuntimeError: Columns need to be 1D (xs is not)

not only do i not understand what this error message is trying to tell me, it is also nonsensical in that all i did was exchange one iterable type (builtin list) by another one (numpy array). this shouldn't be an error at all, given that iterating a 2d numpy array behaves exactly the same way as iterating a list of 1d numpy arrays. so, if i already have 2d numpy arrays ts and xs which contain all of the data, i actually have to explicitly construct a list in order to make this example work:

    p.multi_line([t for t in ts], [x for x in xs])

this isn't very "pythonic" and makes the code less readable.

the second instance i ran into is about scalar types, and in a way it is even more fundamental. example:

    import numpy
    from bokeh.charts import Line, show
    data = {
        't': numpy.arange(10),
        0: numpy.linspace(1, 2, 10),
        1: numpy.linspace(2, 3, 10),
    }
    p = Line(data, x = 't', y = range(2))
    show(p)

here, if i construct the two data columns instead as

    data = {
        't': numpy.arange(10),
        0: numpy.linspace(1, 2, 10).astype(numpy.float32),
        1: numpy.linspace(2, 3, 10).astype(numpy.float32),
    }

i get the following error:

    /users-local/balle/anaconda/envs/2016-02-03/lib/python2.7/site-packages/bokeh/properties.pyc in __set__(self, obj, value)
        210                     break
        211             else:
    --> 212                 raise e
        213         else:
        214             value = self.transform(value)

    ValueError: expected an element of either String, Column(Float), Column(String), Column(Datetime) or Column(Bool), got 0    1.000000
    1    1.111111
    2    1.222222
    3    1.333333
    4    1.444444
    5    1.555556
    6    1.666667
    7    1.777778
    8    1.888889
    9    2.000000
    Name: value, dtype: float32

again, this error message really isn't very helpful in understanding what the problem is, and i only figured out that accidentally passing a different floating point type is the issue by extensive experimentation. what's more important, i believe this shouldn't be an error at all.

python code should not rely on explicit type checking wherever possible. this makes the code more portable, cleaner, and enables many of the nice things you can do with python.

since i haven't been trying out bokeh for a long time, it is possible that i'm missing a really good reason why it should behave in this way, but honestly i can't think of one. if that's the case, please tell me.

**Comment by jonycgn** [comment]
as an additional explanation, i was initally thrown off by the convention of calling an array of data a "column". i can see now that this originates from spreadsheets, where data is typically arranged in columns.

i have no experience with pandas, but quite a bit of experience with numpy arrays/tensors. so in the first example, if you represent all data as an "iterable of iterables", i.e., a 2d data structure/matrix, the 1d data "columns" are really in the rows of that matrix. this is why the first error message was quite confusing to me.

**Comment by bryevdv** [comment]
It probably helps to understand that Bokeh is not just a *Python* library, Bokeh is a *multi-language*, *cross-runtime* library. Alternatively, you might view the Bokeh python binding as a compiler to the JavaScript runtime. Either way, for this to work, the Python side of Bokeh has to ensure correct and efficient serialization of lots of kinds of data, and this makes being explicitly concerned with types unavoidable at a basic level. 

I personally don't think that this kind of "manifest typing" is especially novel for Python; there are several prior prominent examples I can think of off the top of my head, for instance TraitsUI, and the Traitlets library that the Jupyter/IPython project heavily employs. I can also attest that, early on, before there were type-based validation errors, Bokeh was incredibly easy for people to (mis-)use in ways that could not produce correct (or any) output in the browser, and when this happened the errors were opaque or nonexistent, and it was often nearly impossible to diagnose what the actual problem was without great effort. Adding type validation errors has been an unqualified improvement to maintainability, from the perspective of my personal experience. 

All that said, with respect to the specific items you point out:

For the first, the actual proper type is "ragged 1d sequence of sequences". That's what the BokehJS client code is expecting, and what it has to receive. It's certainly true that a non-ragged 2d Numpy array could be considered a special case of this general type. As such, it would not be unreasonable to consider supporting passing that as a value, if it can be serialized efficiently. If you'd like to add that as a separate feature request, please do. 

For the second, this just seems like a bug. I would expect that to work, and am surprised it does not. Aa] separate bug issue for that would be appreciated as well.

**Comment by bryevdv** [comment]
> i have no experience with pandas, but quite a bit of experience with numpy arrays/tensors.

It is true that the `ColumnDataSource` is widely useful, but I will concede that too much has been shoehorned into it out of expediency. We are currently adding different, more specialized kinds of data sources (e.g., data sources for GeoJSON data, and for multi-resolution tiled data sets). I'd like to support a very basic notion of "N-d arrays" explicitly in the protocol in the not too distant future. If you have experience and are interested, we can certainly use additional help.

**Comment by jonycgn** [comment]
i understand that bokeh needs the interoperability between several languages to accomplish its goal. however, i'm talking about the python interface, and the python interface should behave in a way that you would expect it to given python standard practices.

that said, i agree to your point that no type checking is probably a bad idea when data needs to be serialized. but that doesn't mean that you have to pin down all of the data types down to specifying exactly what classes are supported. for example, if all that is required is an iterable of iterables, where the inner iterable has some constraints on the datatype it contains, then you don't need to make any assumptions about the class of the outer iterable. in other words, just check for the type constraints that indeed would cause problems.

this might require some extra thought when writing the code, and it might even require parts of the interface to be designed differently. for example, it appears that `multi_line` also accepts 1d arrays as its inputs, effectively behaving like `line`. this could be a problem, because then it has to first check how many dimensions the data structure has that is passed in, which is not part of the standard iterable interface. however, if you make explicit in the interface that `multi_line` *always* expects an iterable of iterables, you will not need to check for this until you are actually serializing the data columns.

i guess i'm raising this point because i feel that people should be more aware of this as a design goal, not so much because of these two particular instances. as much as i would like to help, i really am "blessed" with enough work for the time being ...

**Comment by jonycgn** [comment]
also, yes, i have seen other examples where people try to impose a "strongly typed" style on python. i'm not too familiar with jupyter internals, but one example i know is cvxopt. i can't help to say, this kind of code takes away the fun of writing python ...

**Comment by birdsarah** [comment]
@jonycgn I'm going to close this issue. @bryevdv has proposed two next steps:

> For the first, the actual proper type is "ragged sequence of sequences". That's what the BokehJS client code is expecting, and what it has to receive. It's certainly true that a non-ragged 2d Numpy array could be considered a special case of this general type. As such, it would not be unreasonable to consider supporting passing that as a value, if it can be serialized efficiently. If you'd like to add that as a separate feature request, please do.

> For the second, this just seems like a bug. I would expect that to work, and am surprised it does not. A separate bug issue for that would be appreciated as well. 

We welcome continuing those two separate discussions on two new issues to keep things manageable.
