### ISSUE TITLE
Interaction stops working on chart reset

### ISSUE THREAD

**Issue by jms90h5** [bokeh/bokeh#3837]
The attached slightly modified version of the interact_basic notebook demonstrates a problem with v0.11.1 where the interaction of a notebook stops working if a CustomJS callback is registered that attempts to retrieve the selection and the user clicks the chart reset button. (There are other conditions that will trigger the behavior but this is the simplest one to recreate. I see the same behavior in a different application if I do something like a box zoom or select instead of a reset (although interestingly in this small example that doesn't seem to cause the problem.)  The error reported in the javascript error is "Cannot read property 'indices' of undefined".

[interact_basic.ipynb.zip](https://github.com/bokeh/bokeh/files/120376/interact_basic.ipynb.zip)

**Comment by birdsarah** [comment]
@jms90h5, can you post a link to a rendered notebook. If you upload your notebook to github or a gist, you can use http://nbviewer.jupyter.org/ to get the rendered version - this makes it much quicker to look at your issue (and nbviewer has a link to download the notebook).

(same applies for your other issues)

**Comment by jms90h5** [comment]
Here is the link on github :
https://github.com/jms90h5/issue_tests/blob/master/interact_basic.ipynb

And in nbviewer:
http://nbviewer.jupyter.org/github/jms90h5/issue_tests/blob/master/interact_basic.ipynb

**Comment by canavandl** [comment]
Hi @jms90h5

I'm unable to reproduce this on master. Registering the callback and clicking reset, then running the `interact` cell doesn't seem to break anything, nor the reverse.

What version of jupyter-client or ipython-notebook are you running?

**Comment by jms90h5** [comment]
After reporting this issue I had updated to the latest version of anaconda which reports IPython.__version__ as 4.0.3.  When I run this example notebook with the Bokeh 0.12.0dev1 build I also no longer see the bad behavior.  Although it always makes me feel a bit uncomfortable when a problem gets resolved or "goes away" without a complete understanding of why, it does appear to working correctly now.  I'll test the more complicated trigger situation separately and if there is still an issue there (hopefully not) create a different example that illustrates it.

**Comment by bryevdv** [comment]
@jms90h5 I agree that's not ideal, but sometimes underlying issues have multiple manifestations and it's not always evident that two issue have the same underlying cause. FWIW I think in this case it was probably this PR that fixed things: https://github.com/bokeh/bokeh/pull/3487

**Comment by jms90h5** [comment]
Yep,  It's easy to understand how that fix would be relevant to the behavior.  Thanks for the followup.
