### ISSUE TITLE
Two times the same figure in gridplot does not show

### ISSUE THREAD

**Issue by LukasDrude** [bokeh/bokeh#3841]
I modified the tutorial code from [nbviewer.jupyter.org](http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/04%20-%20interactions.ipynb).

The first call to the `show` function shows two different figures `s1` and `s2` successfully.

The second call should show two times the figure `s1` but it doesn't.

This might not be the standard use case, but it is for sure one of the errors people run into when learning to use the `gridplot` function.

```
from bokeh.plotting import show, output_notebook, figure, gridplot
from nt.visualization import plot_bokeh
output_notebook()

x = list(range(11))
y0, y1 = x, [10-i for i in x]

s1 = figure(width=250, plot_height=250)
s1.circle(x, y0, size=10, color="navy", alpha=0.5)

s2 = figure(width=250, height=250)
s2.triangle(x, y1, size=10, color="firebrick", alpha=0.5)

p = gridplot([[s1, s2]], toolbar_location=None)
show(p)

p = gridplot([[s1, s1]], toolbar_location=None)
show(p)
```

![image](https://cloud.githubusercontent.com/assets/1886882/12874448/5899639e-cdd4-11e5-80b6-d7760a380732.png)

**Comment by birdsarah** [comment]
I believe that bokeh won't behave properly if you try and have multiple instances of the same plot on the same page.

can you try making a small function that creates s1 and then displaying the 3 distinct instances.

**Comment by LukasDrude** [comment]
You are right. It does not want to show the same object twice (first row). If I call the function twice, therefore, two different objects are generated, the two figures appear.

```
from bokeh.plotting import show, output_notebook, figure, gridplot
output_notebook()

def create_s1():
    x = y = list(range(11))
    s1 = figure(width=250, plot_height=250)
    s1.circle(x, y, size=10, color="navy", alpha=0.5)
    return s1

s1 = create_s1()
p = gridplot([[s1, s1]], toolbar_location=None)
show(p)

p = gridplot([[create_s1(), create_s1()]], toolbar_location=None)
show(p)
```

![image](https://cloud.githubusercontent.com/assets/1886882/12972933/74e7a0c4-d0a9-11e5-970b-5527f2a4ae78.png)

**Comment by bryevdv** [comment]
As an aside they should be able to share a single data source, if desired. 

Bryan

**Comment by birdsarah** [comment]
> You are right. It does not want to show the same object twice (first row). If I call the function twice, therefore, two different objects are generated, the two figures appear.

Great, I'm going to close this issue as resolved then.

@LukasDrude, as a heads-up our issue tracker is growing unmanageable so we are having to be a bit more disciplined about directing people to the mailing list for general support questions, so that the issue tracker can be reserved for development-related discussions. 

So, in the future, can I recommend that you start at:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by LukasDrude** [comment]
@birdsarah, I considered this a bug, which is why I filed this issue. I am aware of possible workarounds and understand, that this bug is of  low importance.

**Comment by bryevdv** [comment]
What is the use case for this? "Fixing" it would require a serious effort, if it is possible at all, for almost no gain that I can perceive. I'd not be opposed to detecting the misuse, and warning loudly about it, though.

**Comment by LukasDrude** [comment]
@bryevdv: No, please to not fix it. I just wanted to point out unexpected behavior.
