### ISSUE TITLE
Histogram from existing bins and counts

### ISSUE THREAD

**Issue by papajohn** [bokeh/bokeh#3842]
Given a table of counts for different bins, I'd like to draw a histogram. E.g., the US Census publishes population counts binned by age, rather than a table of the exact age of every person in the US. Pre-counted and pre-binned data are quite common.

Ideally, the high-level `charts` interface should provide a way to display these data as a histogram with the same formatting as the existing `Histogram`. The closest current alternative, the existing `Bar` class, adds space between the bars and labels each bar rather than displaying a linear range.

Once the data have been counted (e.g., see below), it's not clear how to draw a histogram without enumerating all the counts, which would be prohibitive for large counts.

```
from bokeh.sampledata.autompg import autompg
only_mpg = autompg[['mpg']]
counted = only_mpg.groupby(pandas.cut(df['mpg'], 5)).count()
# Given bins and their counts, how can a histogram be rendered?
```

**Comment by birdsarah** [comment]
Hi @papajohn, our issue tracker is becoming too large to manage easily. We have to reserve it for feature requests and bug reports only, to have any hope of taming it. This kind of general support question should go to the general public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

I will close this issue for now. If I have misunderstood and this is a feature request, can you re-frame it as such and explain what your current solution is and the problems with it (ideally giving a minimal working example).
