### ISSUE TITLE
Donut missing legend

### ISSUE THREAD

**Issue by achalddave** [bokeh/bokeh#3843]
I'm trying to make a donut chart with percentages within the wedges, and a separate legend for the names of the wedges. The legend on the donut, however, seems to be empty.

Code:
```python
def pie_chart(values, labels, title):
    data = {'values': values}
    # Calculate percents for each value, used as wedge labels.
    data['percents'] = ['{:0.2f}'.format(100 * amount / sum(data['values']))
                        for amount in data['values']]
    donut = Donut(data, values='values', legend='top_left',
                  labels=labels, label='percents', title=title)
    show(donut)

pie_chart([2, 3], ['a', 'b'], 'test chart')
```

The result is the following:
<img width="424" alt="screen shot 2016-02-07 at 9 31 41 pm" src="https://cloud.githubusercontent.com/assets/1168881/12877498/3da49208-cde2-11e5-9042-0d31a6f1235f.png">

I had originally tried sending a message to the Google group (which seems to have been eaten up by the void?), as I thought I was doing something wrong, but as far as I can tell this seems to be the correct way to do what I would like, and there's no other documentation on adding a legend to a donut chart.

**Comment by achalddave** [comment]
I spent some time looking at this, and while I'm not familiar with the code, it appears that a legend is based on a list of `tuple(label, [GlyphRenderer])` pairs. Unfortunately, the `DonutBuilder` class [creates one `GlyphRenderer`](https://github.com/bokeh/bokeh/blob/88a1bb6babcaa758661d384885d5d0811673960a/bokeh/charts/builders/donut_builder.py#L227) for the entire donut (and another for the text). I can't seem to find a way to separate the individual wedges and associate them with a label in the legend.

It is possible to add something like
```python
self._legends.append(labels[0], aw)
```
after [line 232](https://github.com/bokeh/bokeh/blob/88a1bb6babcaa758661d384885d5d0811673960a/bokeh/charts/builders/donut_builder.py#L232), but this will only provide a legend for one wedge.

**Comment by birdsarah** [comment]
@achalddave this appears to be a regression - trying to add a legend to the example in the docs: http://bokeh.pydata.org/en/latest/docs/reference/charts.html#donut fails in the same way.

This may be a known issue because there isn't a legend glyph available for the Donut wedges. In which case it should, at least, be documented.

@fpliger - did this ever work?

**Comment by birdsarah** [comment]
@achalddave I've changed this from bug to feature to discussion. Here's why:

Legend currently isn't supported, so making it work would be a new feature.

I played around a little in a notebook to understand why: http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/3843.ipynb

The wedges are all part of one GlyphRenderer, and as a result it's not possible to add the individual pieces to the legend.

I can see how having a legend be populated by the rows of a ColumnDataSource would be useful in a number of settings.

I've changed this to a discussion, because I think I'd like to spawn two new issues. One is a documentation issue for donut; the second is a new legend feature that allows you to populate legend from rows of a ColumnDataSource.

**Comment by birdsarah** [comment]
@achalddave - are you ok with me closing this issue, given the two new issues created?

**Comment by achalddave** [comment]
Yup, thanks for checking and for following up with this!

**Comment by joshusre** [comment]
I'm unsure as to what point of the process were in here, but I could really use a legend for donut :\

**Comment by tommycarstensen** [comment]
+1

**Comment by stephperk** [comment]
So Donut() is deprecated. Not exactly sure why that and pie charts aren't a model we can construct more simply-- but okay, no problem. You can always create by hand with annular_wedges. If I am wrong about that, please let me know. 

So I constructed a donut chart glyph by glyph, but I am trying to figure out how to label the wedges on the chart and how to construct a legend with a list of strings. Can you please assist?

`angles = [92.90322580645162, 23.225806451612904, 63.87096774193549, 180.0]
start = [0, angles[0], sum(angles[:2]), sum(angles[:3])]
end = [start[1], start[2], start[3], 360]
colors = ["#003049", "#521a4a", "#d8247c", "#247cd8"]
p = figure(plot_width=400, plot_height=400)
p.annular_wedge(x=1, y=1, inner_radius=.4, outer_radius=1,
                start_angle_units='deg', end_angle_units='deg', start_angle=start, end_angle=end, color=colors, alpha=0.8)
show(p)`

**Comment by hhprogram** [comment]
I don't know if this is a viable solution for you. But I just recently ran into a similar problem (but I was using `wedge()`). My piechart had only 2 different sections that I wanted a legend for. And I just added an 'empty' wedge with the color set to the other non-labeled color of the original piechart and added that to my figure. See below:
`pieFigure = figure(x_range=(-1, 1), y_range=(-1, 1))
starts = [np.pi / 2, np.pi * 2 * percentAchieved + np.pi / 2]
ends = [np.pi / 2+ np.pi * 2 * percentAchieved, np.pi / 2 + 2*np.pi]
pieColors = ['blue', 'red']
#therefore, this first wedge will add a legend entry for the first color 'blue' and label it 'hello'
pieFigure.wedge(x=0, y=0, radius=.7, start_angle=starts, end_angle=ends, color=pieColors, legend="hello")
#this will add a legend entry for the 'red' color and label it 'bye'. Made radius zero to not make 
#another piechart overlapping the original one
pieFigure.wedge(x=0, y=0, radius=0, start_angle=starts, end_angle=ends, color=pieColors[1], legend="bye")`

Hope this work around helps!
