### ISSUE TITLE
Change location of tile renderers, tile source, image renderer and image source to match Bokeh

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3845]
Some of the BokehJS classes don't match Python structure and are simply in the wrong place.

**Comment by bryevdv** [comment]
@brendancol can you elaborate

**Comment by mattpap** [comment]
Tiles and sources are under the same directory in bokehjs. @brendancol, make sure to do this after #4141, otherwise you will get plenty of merge conflicts.

**Comment by bryevdv** [comment]
Ship has sailed on moving these.
