### ISSUE TITLE
Bar chart doesn't accept `Timestamp` for x-axis categories.

### ISSUE THREAD

**Issue by dragoljub** [bokeh/bokeh#3847]
I have a simple date time indexed data frame. I would like to plot bar plots with the date time on the x-axis and one of the values on the y-axis.

pandas 0.17.1
bokeh 0.11.0

```
import numpy as np
import pandas as pd
from bokeh.charts import Bar, show, output_notebook
output_notebook()

s = pd.date_range('2016-01-01', periods=100, freq='D')
df = pd.DataFrame(np.random.randint(0,5, size=(100,2)), columns=['A','B'], index=s)

data = df.resample('W', how='sum')
data.index.name='DATE'
data = data.reset_index()

data.head()
	DATE 	    A 	B
0 	2016-01-03 	9 	9
1 	2016-01-10 	13 	17

data.dtypes
DATE   datetime64[ns]
A               int32
B               int32
dtype: object

show(Bar(data, label='DATE', values='A'));
--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-50-9528b00e00f3> in <module>()
----> 1 show(Bar(data, label='DATE', values='A'));

D:\Python27\lib\site-packages\bokeh\charts\builders\bar_builder.pyc in Bar(data, label, values, color, stack, group, agg, xscale, yscale, xgrid, ygrid, continuous_range, **kw)
    302     kw['y_range'] = y_range
    303 
--> 304     chart = create_and_build(BarBuilder, data, **kw)
    305 
    306     # hide x labels if there is a single value, implying stacking only

D:\Python27\lib\site-packages\bokeh\charts\builder.pyc in create_and_build(builder_class, *data, **kws)
     65     chart_kws = { k:v for k,v in kws.items() if k not in builder_props}
     66     chart = Chart(**chart_kws)
---> 67     chart.add_builder(builder)
     68     chart.start_plot()
     69 

D:\Python27\lib\site-packages\bokeh\charts\chart.pyc in add_builder(self, builder)
    150     def add_builder(self, builder):
    151         self._builders.append(builder)
--> 152         builder.create(self)
    153 
    154     def add_ranges(self, dim, range):

D:\Python27\lib\site-packages\bokeh\charts\builder.pyc in create(self, chart)
    516         if chart is None:
    517             chart = Chart()
--> 518         chart.add_renderers(self, renderers)
    519 
    520         # handle ranges after renders, since ranges depend on aggregations

D:\Python27\lib\site-packages\bokeh\charts\chart.pyc in add_renderers(self, builder, renderers)
    145 
    146     def add_renderers(self, builder, renderers):
--> 147         self.renderers += renderers
    148         self._renderer_map.extend({ r._id : builder for r in renderers })
    149 

D:\Python27\lib\site-packages\bokeh\core\property_containers.pyc in wrapper(*args, **kwargs)
     16         self = args[0]
     17         old = self._saved_copy()
---> 18         result = func(*args, **kwargs)
     19         self._notify_owners(old)
     20         return result

D:\Python27\lib\site-packages\bokeh\core\property_containers.pyc in __iadd__(self, y)
     75     @notify_owner
     76     def __iadd__(self, y):
---> 77         return super(PropertyValueList, self).__iadd__(y)
     78 
     79     # x *= y

D:\Python27\lib\site-packages\bokeh\charts\builders\bar_builder.pyc in yield_renderers(self)
    179         attrs = self.collect_attr_kwargs()
    180 
--> 181         for group in self._data.groupby(**self.attributes):
    182             glyph_kwargs = self.get_group_kwargs(group, attrs)
    183             group_kwargs = kwargs.copy()

D:\Python27\lib\site-packages\bokeh\charts\data_source.pyc in groupby(df, **specs)
    264 
    265                 # get attribute value for this spec, given the unique column values associated with it
--> 266                 attrs[spec_name] = spec[label]
    267 
    268             yield DataGroup(label=group_label, data=data, attr_specs=attrs)

D:\Python27\lib\site-packages\bokeh\charts\attributes.pyc in __getitem__(self, item)
    202             self.setup()
    203 
--> 204         return self.attr_map[self._ensure_tuple(item)]
    205 
    206 

KeyError: (Timestamp('2016-01-03 00:00:00'),)
```

**Comment by birdsarah** [comment]
Hi,

The problem is that the Bar chart can't accept datetimes.

I took your code and made the bar chart work by converting the date
column to a string. You can see it here:
http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/Bar%20charts%20with%20dates.ipynb

The line I added is: data.DATE = data.DATE.apply(lambda x:
str(x).split(' 00:00:00')[0])

bar chart with dates

**Comment by birdsarah** [comment]
Hi,

The problem is that the Bar chart can't accept datetimes.

I took your code and made the bar chart work by converting the date
column to a string. You can see it here:
http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/Bar%20charts%20with%20dates.ipynb

The line I added is: 

```python
data.DATE = data.DATE.apply(lambda x: str(x).split(' 00:00:00')[0])
```

![index](https://cloud.githubusercontent.com/assets/1796208/12908463/9efb402c-ceac-11e5-981b-227bbd64ef64.png)

**Comment by birdsarah** [comment]
I'm in two minds as to whether Bar chart should accept timestamps. On the one hand, time is continuous and Bar charts are meant for discrete data.....on the other it is common to want to do this.

Thoughts @rothnic @bokeh/dev ?

**Comment by dragoljub** [comment]
@birdsarah Thanks for the feedback. I'm currently getting around this by using the pandas datetime accessor to pull out the date for day/week groupbys ```data.DATE = data.DATE.dt.date``` which works ok for day only labels. I was having issues with string representations of date times, or just hours in a day.

For example plot a stacked bar chart sum of events by hour in the last 24 hour period.

I vote for supporting time stamps in the bar chart, even if they are cast to strings automatically by bokeh. There are too many times when I have re sampled long time series by, day, week, month etc to show various aggregate trends over time. It would be ideal to not have to manually pull out date time parts to get the plots to work.

Now that I think about it, I wonder if the problem I was having with more date time strings was due to json serialization of the colon ':' :confused:  After re sampling in pandas I would not mind pulling out the ISO 8601 string representation if that can be used for bar labels.

**Comment by dragoljub** [comment]
So it turns out that my intuition was right about the ':' colons. If I transform my date-time column into strings and replace the colons with dashes ```data.DATE = data.DATE.apply(lambda x: str(x).replace(':','-'))``` everything works out great. However if you forget this little trick there is no warning and you jut get a blank plot.

With ```replace(':','-')``` works fine: :grinning: 
![good](https://cloud.githubusercontent.com/assets/2701562/12923424/8f26ffc0-cf0a-11e5-8b19-a7e0acad5c98.PNG)

Without ```replace(':','-')``` its just gives me a blank chart which is very misleading. Should we have warnings put in place when labels have colons? Is there any option to escape the colon for actually using colons in the chart labels?
![bad](https://cloud.githubusercontent.com/assets/2701562/12923427/912efbd8-cf0a-11e5-995e-598b3f7ccc6b.PNG)

**Comment by bryevdv** [comment]
Not currently but I hope to re-vamp then entire "categorical coordinates" system in the next month or two.

**Comment by dragoljub** [comment]
@bryevdv Cool. :smile: I'll close the issue since its not really a bug and more of a usage issue.

**Comment by jonashaag** [comment]
I just stumbled upon this too. Are there any plans to change Bokeh's behaviour here?

**Comment by bryevdv** [comment]
Yes (here is another open issue), but it is one priority among a long list of other priorities, and there are limited people/resources to work on everything.

**Comment by klonuo** [comment]
I'm using 0.12.4 and it seems like this is not yet implemented (although this was added in 0.12 milestone)
Or?

**Comment by jdmarino** [comment]
My use-case is daily p&l for a variety of strategies.  Seeing them stacked to add to the total makes visual sense.  The x-axis is not categories, but discrete periods (dates).  Perhaps that's the ideological resolution: although timestamps are continuous, in this case they are being used to label discrete periods (analogous to categories).   The downside of converting the dates to strings is that we don't get the nifty date formatting that a time-aware axis would give us.  
And, a line graphs isn't right because there is no connection between the dates (as there would be with a cumulative p&l graph).
Just my $0.02.

**Comment by birdsarah** [comment]
Please note bar charts have been moved out of bokeh core. See https://github.com/bokeh/bkcharts
Also, commenting on closed issues generally does not help move things forward.
