### ISSUE TITLE
Oval with height=width does not produce a circle

### ISSUE THREAD

**Issue by dbricare** [bokeh/bokeh#3848]
Hi,
I'm using bokeh 0.11.0 in a jupyter notebook and when I try to draw an oval with height and width equal, I don't get a circle.

```python
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import Range1d
output_notebook()

p = figure(plot_width=600, plot_height=600)

p.x_range = Range1d(0, 2)
p.y_range = Range1d(0, 2)

p.oval(x=1.0, y=1.0, width=1.0, height=1.0)
show(p)
```

**Comment by bryevdv** [comment]
Technically it's an oval (drawn with bezier segments), not an ellipse, and the width and height relate to the bezier control points. But it would probably be more useful (and simper actually) to just have an ellipse. With 700 open issues there is much more than the current team can get to in a hurry, would you be interested in working on a PR to add a real ellipse glyph, with some guidance/help?

**Comment by humm** [comment]
@bryevdv 
Sounds like fun. I would definitely be interested in developing the code for ellipses (having stumbled on the height != width bug myself). I could probably do it over the next two weeks. Would that work for you?

**Comment by canavandl** [comment]
@humm

**Comment by gwenzek** [comment]
I'm also interested in drawing ellipses. Did you work on it @humm ?

**Comment by humm** [comment]
Got no reply. I understand that the bokeh team is pretty busy. I wanted to avoid duplicating the work with someone else. And, I'd rather have some pointers to do it right. I have some spare time to take a crack at it this week. Is that okay with @bryevdv, @birdsarah or @canavandl?

**Comment by bryevdv** [comment]
@humm my apologies I missed your question. Certainly any time new contributors can contribute is a good time! As for pointers I would start by looking at the `rect` glyph, I believe it should really only be a couple of lines different on he JS side, and identical on the python side (just copy `Rect` and rename it appropriately)

**Comment by humm** [comment]
Alright thanks! I'll get right on it.
