### ISSUE TITLE
Problem with DataTable, last value is not printed

### ISSUE THREAD

**Issue by afDeathscythe** [bokeh/bokeh#3852]
Hi,

I have the following problem:

I have this data frame:

`df = {'type': ['protein_coding_intron', 'protein_coding_exon', 'lincRNA', 'antisense', 'misc_RNA', 'processed_pseudogene', 'rRNA', 'snRNA', 'processed_transcript', 'transcribed_unprocessed_pseudogene', 'unprocessed_pseudogene', 'sense_overlapping', 'unitary_pseudogene', 'Mt_tRNA', 'miRNA', 'snoRNA', 'transcribed_processed_pseudogene', 'sense_intronic', 'Mt_rRNA', 'TEC', 'macro_lncRNA', 'polymorphic_pseudogene', 'ribozyme', 'scaRNA', 'vaultRNA'], 'typeCounts': [5600, 3999, 380, 238, 212, 131, 131, 96, 88, 35, 18, 17, 14, 12, 11, 10, 9, 5, 2, 1, 1, 1, 1, 1, 1]}`

And I want to plot this with the following code:
```

typeP = Bar(df, title="Types", values='typeCounts', label=CatAttr(columns=['type'], sort=False),tools=TOOLS, xlabel="Types", ylabel="Counts")

typeData_table = DataTable(source=ColumnDataSource(df), columns=[TableColumn(field="type", title="Types"),TableColumn(field="typeCounts", title="Frequency")], width=500, height=500)
         
tPlot = vplot(
                hplot(typeP, typeData_table),
)

show(tPlot)
```

The only problem which occurs is that in the DataTable, the last value of the data frame (in this case vaultRNA and 1 is not printed in the data table.
Could this be a bug or may I missing something?

Thanks in advance

**Comment by bryevdv** [comment]
Seems like a bug, will mark is as such for more investigation.

**Comment by canavandl** [comment]
I wasn't able to reproduce the bug using the following code snippet:

```python
from bokeh.plotting import output_file, show
from bokeh.io import vplot, hplot
from bokeh.models.widgets import DataTable, TableColumn
from bokeh.models import ColumnDataSource
from bokeh.charts import Bar
from bokeh.charts.attributes import CatAttr

output_file('out.html')

df = {'type': ['protein_coding_intron', 'protein_coding_exon', 'lincRNA',
               'antisense', 'misc_RNA', 'processed_pseudogene', 'rRNA',
               'snRNA', 'processed_transcript',
               'transcribed_unprocessed_pseudogene', 'unprocessed_pseudogene',
               'sense_overlapping', 'unitary_pseudogene', 'Mt_tRNA', 'miRNA',
               'snoRNA', 'transcribed_processed_pseudogene', 'sense_intronic',
               'Mt_rRNA', 'TEC', 'macro_lncRNA', 'polymorphic_pseudogene',
               'ribozyme', 'scaRNA', 'vaultRNA'],
      'typeCounts': [5600, 3999, 380, 238, 212, 131, 131, 96, 88, 35, 18,
                     17, 14, 12, 11, 10, 9, 5, 2, 1, 1, 1, 1, 1, 1]
     }

typeP = Bar(df, title="Types", values='typeCounts',
        label=CatAttr(columns=['type'], sort=False),
        xlabel="Types", ylabel="Counts")

typeData_table = DataTable(source=ColumnDataSource(df),
                           columns=[TableColumn(field="type", title="Types"),
                                    TableColumn(field="typeCounts", title="Frequency")],
                           width=500, height=700)

tPlot = vplot(hplot(typeP, typeData_table))

show(tPlot)
```

<img width="1161" alt="screen shot 2016-02-21 at 8 58 00 pm" src="https://cloud.githubusercontent.com/assets/2198981/13208400/ff95beb8-d8dd-11e5-9e13-1ae394c27e95.png">

Can you try again w/ the most recent version of Bokeh (0.11.1)

**Comment by canavandl** [comment]
I'm going to close this issue as invalid (for good-housekeeping reasons). If you still have the problem, please reopen it and we'll figure out a fix.
