### ISSUE TITLE
Add ability to set browser tab title on server apps / non-`output_file` apps

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3853]
Basically looking to set the browser tab title.  This is currently available when using `output_file`, but having trouble finding it for server apps, or app that use `show`.

```
<head>
     <title>My Custom Title</title>
</head>
```

**Comment by ze-phyr-us** [comment]
This is really important when you have several plots open (and can't waste space on titles directly in the plot). Is there a rough ETA for 0.12?

**Comment by bryevdv** [comment]
This is settable via `curdoc().title` unless I am misunderstanding something.

**Comment by bryevdv** [comment]
Yup:
```
curdoc().title = "TEST TITLE"
```
<img width="184" alt="screen shot 2016-04-13 at 11 47 23 am" src="https://cloud.githubusercontent.com/assets/1078448/14501749/99f0cad6-016d-11e6-9915-f59b0b2d84f1.png">
