### ISSUE TITLE
Populate legend with rows of data

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3856]
This feature idea came up from the discussion on #3843.

Also see notebook: http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/3843.ipynb

Normally a legend is populated with a series of GlyphRenderers and their labels.

But if, as in the case of a Donut plot, there is one GlyphRenderer for each of the slices of the pie and the color is controlled by a column; you may well want a legend that is populated by the rows of a data source so that you can document the changing color (which is powered by a column of the ColumnDataSource).

I think this will also relate to making a client side colormappers

For example, in the gapminder example: http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/A1%20-%20Building%20gapminder.ipynb#Embedding I manually build a legend for each of the world's regions. This could be thought of as making a legend based on the data rows, but only displaying unique values.

**Comment by bryevdv** [comment]
I was just thinking this on the way home, thanks for making an issue I think it is a great idea. More generally, we have a notion of a "representative" point but I think that should be expanded to representative pointS, and then also make the label configurable as a column field as well. I think that would cover this case very well. (the reason to make the points configurable, suppose you have some "grouped" data in one source, and want a legend only for each glyph, not for every row -- you could configure the representative points to be one from each group)

**Comment by fedorova** [comment]
Do you have an example of how to use this feature?

**Comment by bryevdv** [comment]
Second example here:

https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#legends
