### ISSUE TITLE
Update Technical Vision part of docs to reference new Data Shader repo

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#3859]
http://bokehplots.com/pages/technical-vision.html

**Comment by bryevdv** [comment]
@pzwang probably best if you or @jbednar make a PR, so that it makes sure to say the things that you want.

**Comment by jbednar** [comment]
Ok, I'll do that.

**Comment by bryevdv** [comment]
that's actually on the static site now, no? ping @birdsarah I'm not sure how that gets re-deployed
