### ISSUE TITLE
`bokeh serve` and provide a directory with apps, or a `conf.d` location

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#3862]
It would be great to have bokeh serve act as a bokeh app web server that could detect new, changed, and removed apps from the file system without requiring a restart.  A few possibilities:
- point it at a directory, and all files matching some pattern are picked up as bokeh apps and served.  The server will respond to new, changed, and removed files in that directory.
- a `conf.d` like system where app configuration can be dropped in a single place, and then (perhaps) have the server respond to changes in the set of configuration files.
- `~/bokeh_apps`, analogous to `~/public_html` where users could drop their own bokeh apps and those matching some filename pattern would automatically be picked up and served.

**Comment by birdsarah** [comment]
ping @havocp

**Comment by havocp** [comment]
I agree this would be neat. Some of the work is the same as for "develop mode" (which is another open issue here someplace)

**Comment by havocp** [comment]
A version of this without dynamic reload (i.e. only scans the directory on startup) is almost trivial, so may be worth considering right away, vs. the dynamic-watch-and-reload which is more involved.

**Comment by bryevdv** [comment]
There just has not been any perceptible demand for this (comments or reactions here, questions on SO or the mailing list) in two years, so I am going to close with no action. Happy to consider a PR for this from anyone interested enough to take it on.
