### ISSUE TITLE
word cloud?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [bokeh/bokeh#3870]
Did I understand correctly, that a word cloud viz. is possibly forthcoming?

**Comment by bryevdv** [comment]
Hi @smartinsightsfromdata this kind of question is better posed to the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

There's no reason why anyone couldn't in principle create a word cloud using Bokeh, but we are working on a number of other important priorities at the moment, and creating this kind of example is not on our immediate planning schedule. Perhaps someone on the mailing list has done something, though.
