### ISSUE TITLE
MultiSelect: on_change method does not work properly

### ISSUE THREAD

**Issue by petermountanos** [bokeh/bokeh#3871]
I am having a problem with the MultiSelect widget in v0.11.1, particularly with the on_change method. It seems there's also [other people ](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/0OGyHe9tpGE)having this issue as well.
    
```python
from __future__ import print_function
from bokeh.models import MultiSelect, Select, CustomJS, VBox
from bokeh.io import curdoc


def update(attrname, old, new):
    print("""MultiSelect\nOptions: %s\nSelected:%s\n\n
             Select\nOptions:%s\nSelected: %s"""
          % (mscolors.options, mscolors.value, colors.options, colors.value))

# set up select widget
colors = Select(title="colors", options=["Red", "Green", "Blue"])
colors.on_change('value', update)
colors.callback = CustomJS(code="console.log('Select: ' + cb_obj.get('value'))")

# set up multiselect widget
mscolors = MultiSelect(title="Colors", options=["Red", "Green", "Blue"])
mscolors.on_change('value', update)
mscolors.callback = CustomJS(code="console.log('MultiSelect: ' + cb_obj.get('value'))")

curdoc().add_root(VBox(colors, mscolors))
````
Run using ```bokeh server --show main.py```.

As identified by @birdsarah changing the selected value on the UI doesn't actually update the HTML selected flags. Therefore, the ```on_change``` callback function can't properly listen for a change. However, if you check the JS console, the ```CustomJS``` callback clearly works. I've tried to debug the issue myself, but I can't seem to figure it out.

When changing the value of the Select widget, I'll get output in my Python shell like: 
```
Select
Options:['Red', 'Green', 'Blue']
Selected: Green

MultiSelect
Options: ['Red', 'Green', 'Blue']
Selected:[]
```
But when I change the value of the MultiSelect widget, I get no output in the Python shell. Like mentioned above, I get the expected output to the JS console. Thanks.

===Version Information===
Bokeh version: 0.11.1
Python version: 2.7.11-CPython
Platform: Darwin-15.3.0-x86_64-i386-64bit
Browser: Chrome

**Comment by bryevdv** [comment]
Guessing this is the problem:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/multiselect.coffee#L40

I'm not sure what (if any) rationale there was for making the Backbone update silent, but that would keep a server update message from being generated. If someone could make a PR that removes the `{silent: true}` (even without testing it, though great if you can build and test locally) that would be a huge help.

**Comment by bryevdv** [comment]
Guessing it is silent to prevent a further triggering of the `render_selection` method:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/multiselect.coffee#L30

But it might be harmless to call that again. If not (it it starts some infinite event ping-pong, e.g) that should be easy enough to short circuit.

**Comment by marco-c** [comment]
Is there a workaround for this issue?

**Comment by petermountanos** [comment]
Resolved via https://github.com/bokeh/bokeh/pull/3873

**Comment by marco-c** [comment]
The new version hasn't been released yet, so I was wondering if there's a workaround for the current 0.11.1.

**Comment by rs2** [comment]
@marco-c a local patch or a local build? Both worked for me.

**Comment by petermountanos** [comment]
@marco-c @rs2 Both worked for me as well.

**Comment by marco-c** [comment]
I wanted to avoid using a custom build, but I guess I'll do it (0.11.1 is unstable anyway).

By the way, I'm experiencing the same issue with `CheckboxButtonGroup` and `CheckboxGroup`.

**Comment by birdsarah** [comment]
@marco-c I made some tweaks that are now in 0.12.0rc3 - I know a lot of time has gone by, but maybe they help, if they dont' feel free to open another issue.
