### ISSUE TITLE
How do I do that in version 0.11 to push session into server?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#3879]
In version 0.10, I can run "bokeh serve" in command prompt, then

run "python .py" with a python file ending with 
"
session = push_session(curdoc())
session.loop_until_closed()
"

How do I do that in version 0.11 to push session into server?

**Comment by bryevdv** [comment]
@charleywan2004 I am afraid you have some misunderstanding somewhere. `bokeh serve` only came into existence with version `0.11`. Prior to that (in version `0.10` for instance) the was the old `bokeh-server`, which has been completely removed. Additionally the `session.loop_until_closed` was also added in `0.11`, and is still how to use the client API in `0.11` and newer.

Additionally, our issue tracker is becoming too large to manage easily. We have to reserve it for feature requests and bug reports only, to have any hope of taming it. This kind of general support question should go to the general public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
