### ISSUE TITLE
ncol and nrow in Legend object

### ISSUE THREAD

**Issue by napsternxg** [bokeh/bokeh#3880]
Is there a way in Bokeh to have the legend in a multi row column format like it is done in matplotlib. 

In matpltolib the legend object takes as input 2 additional optinal agruments ncol and nrow which defines how many rows and column the legend object should be split in. 

This is very useful when we have lots of legend items and its better to organize then into rows and columns. 

Can similar api be made available in bokeh.

**Comment by bryevdv** [comment]
This does not exist currently, but there was a recent PR that added support for horizontal orientations for legends. It might be nice to support more options like rows and columns as a feature, though. Would you be interested on working on a PR to add this capability, with some help?

**Comment by napsternxg** [comment]
Can you point me to the PR for horizontal orientation. I can try working on this using the approach from that PR.

**Comment by bryevdv** [comment]
@napsternxg absolutely, the merged PR is here:

https://github.com/bokeh/bokeh/pull/3731

I would say from the standpoint of the current interface, since there is already `orientation` now that can be horizontal or vertical, the most consistent thing would be a generic integer property  `grouping` that would specify how many rows (when `orientation` is horizontal) or how many columns (when `orientation` is vertical). It would have a default value of `1` which would keep the current behaviors as the default.  In the python code this would just be a new class attribute for `Legend`, something like:
```
    grouping = Integer(default=1, help=""" helps string here """)
```

The BokehJS side will be a little tricker, basically is uses the orientation to compute some layout values here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/legend.coffee#L40-L49

and then uses those values to actually render text and glyphs in the `render` function here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/legend.coffee#L118-L140

Those two sections would need to be expanded to take `grouping` into account. Take a look at that, if it seems like something you can do/would like to do with some help, we will certainly answer any questions you have.

**Comment by guillochon** [comment]
Hi, I have a legend with many labels, and neither the default horizontal/vertical orientations work for me, I need multiple columns/rows. Has there been any progress on this?

**Comment by birdsarah** [comment]
@guillochon, we're super thin at the moment and I don't think this high on the to do list - sorry to not have more news.

**Comment by brandondube** [comment]
Any update over a year later?

**Comment by bryevdv** [comment]
@brandondube if there were any updates, they would be here. The story here, as is the story with most all OSS projects, is that there is far more work to do, than people to do it. In such a situation, things come down to prioritization, and therefore some things will simply take a very long time. The only solution to that is for more people to get involved. I am happy to mentor any new contributors who would be interested in working on this.

**Comment by brandondube** [comment]
Well, how do I get started?  I couldn't even find the definition of `Legend` in the repo digging around fairly quickly in /bokeh/models.

**Comment by bryevdv** [comment]
@brandondube Awesome, first things first, Bokeh is a dual language library, with most of the actual work done in BokehJS. To work on this particular issue will require being able to modify and build BokehJS. The developers guide has a section on getting set up:

https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html

Once you can build BokehJS, you will find the python side definition of Legend here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/annotations.py#L99

Bokeh classes are almost all purely declarative, they just have typed property class attributes that define how they can be configured. For this issue, we will want to add probably a new property to specify how the legend layout is to be configured (or possibly, we might just want to expand the existing `orientation` property)

The BokehJS definition of Legend (where all the work happens) is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/annotations/legend.ts

Once you are set up with building and running a locally modified BokehJS we can discuss particulars of how best to proceed.

**Comment by thoth291** [comment]
It looks like there is no way to create multi-column legend in bokeh - I wonder if there is way to have a workaround by using two plots. **One of them would look like multi-column legend but would be simple annotations and react to tap by muting linked object on another plot.**
Sounds like horrible hack.

**Comment by bryevdv** [comment]
@thoth291 It does sound like a pretty fragile solution. In any case GitHub is not the appropriate venue to discuss support questions, for that use the Discourse https://discourse.bokeh.org

**Comment by iftenney** [comment]
FWIW, I found a reasonable workaround was to just add two legends, one for each column.
```
legend_items = list(zip(names, renderers))
legend_kw = dict(spacing=15,
                 label_text_font_size="13pt",
                 orientation='vertical')
legend = bokeh.models.Legend(items=legend_items[:2], 
                             location=(10,0), **legend_kw)
p.add_layout(legend, 'center')
legend = bokeh.models.Legend(items=legend_items[2:], 
                             location=(160,0), **legend_kw)
p.add_layout(legend, 'center')
```

Haven't tested with interactive legends, but this worked nicely for a static plot if you don't mind manually spacing them.

**Comment by Vel-San** [comment]
> FWIW, I found a reasonable workaround was to just add two legends, one for each column.
> 
> ```
> legend_items = list(zip(names, renderers))
> legend_kw = dict(spacing=15,
>                  label_text_font_size="13pt",
>                  orientation='vertical')
> legend = bokeh.models.Legend(items=legend_items[:2], 
>                              location=(10,0), **legend_kw)
> p.add_layout(legend, 'center')
> legend = bokeh.models.Legend(items=legend_items[2:], 
>                              location=(160,0), **legend_kw)
> p.add_layout(legend, 'center')
> ```
> 
> Haven't tested with interactive legends, but this worked nicely for a static plot if you don't mind manually spacing them.

Can confirm this has fixed my issue (feature linked above) on a Stacked Bar (Interactive) Graph. 

```
### Seperated Labels
legends_1 = Program_df_trend[:(len(Program_df_trend)/2)]
legends_2 = Program_df_trend[(len(Program_df_trend)/2):]

### Created Legends (Localtion kept 0, 0 for both and it didn't overlap
legend = Legend(items=[(x, [v[i]]) for i, x in enumerate(legends_1)], location=(
    0, 0), glyph_height=10, orientation="vertical", click_policy="hide")
p2.add_layout(legend, 'right')
legend = Legend(items=[(x, [v[i]]) for i, x in enumerate(legends_2)], location=(
    0, 0), glyph_height=10, orientation="vertical", click_policy="hide")
p2.add_layout(legend, 'right')
```

@iftenney Thanks for the help.
