### ISSUE TITLE
Proposal: remove need for output_file() and display in "native" window

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#3885]
I would like to discuss two related ideas:

1) Remove the need to require specifying an `output_file()`. Having to choose a name (and path) for an html file sits in the way of doing quick interactive plotting IMO. It feels like something of an export mechanism. 

1a) One simple solution is to automatically create an html file in a temp folder. We'd have to do a bit of management to clean up old html docs. 

1b) Alternatively, we could make the Python process serve the html file. This would require substantially more changes and design. This would lean towards making apps, not sure if this is an approach we want to support?.

2) The second proposal is to show the generated web page in a "native" window instead of adding a tab to a browser. I think this would give Bokeh a more interactive/native feel, similar to MPL. Of course, the "native" window would really be a web-browser in disguise, like [XUL](https://en.wikipedia.org/wiki/XUL) or [nwjs](http://nwjs.io/) or [Electron](http://electron.atom.io/). Flexx already has functionality to do this based on XUL (which is available anywhere where Firefox is installed), and Chrome. A similar approach should be possible based on Internet Explorer.

**Comment by mattpap** [comment]
@almarklein, I presume PR #3791 is related.

**Comment by almarklein** [comment]
@mattpap Ah yes, that sounds related. Does your solution allow `show()` without `output_file()`? i.e. take any example and remove the line with `output_file()`? Also, I think I may prefer to not have any visible html doc generated (i.e. generate it in a temporary place), though putting the html right next to the script also seems sensible.

**Comment by bryevdv** [comment]
from my perspective, this is all done already:
```
     bokeh html foo.py
```
generates an HTML file, not `output_file` or `show` required. And
``` 
    bokeh serve foo.py
```
serves a page, no `output_server` or `show` required.

I think we need to promote *these* as the canonical way to accomplish what you've asked. Anything else seems both redundant and confusing. 

As for native window, I have no thoughts either way, it's not something I care about personally but I could imagine other people would.

**Comment by almarklein** [comment]
I am thinking more of an interactive workflow from an IDE, not using the terminal. My experience is that most non-geek scientist are a bit scared of the command line, and much rather have a Matlab-like approach to generate a plot from an interactive session or a snippet/script inside an IDE.

**Comment by bryevdv** [comment]
In that case I think we can pursue/refine #3791 though personally I am not fond of having so many ways to do things.

**Comment by almarklein** [comment]
In general I agree that we want one, and just one obvious way to do it. Especially when API's are concerned. But different users have different workflows ...

**Comment by bryevdv** [comment]
I'm pretty -1 on all of this, after some reflection. I think it's possible to use existing APIs to achieve this, maybe we could show how and provide some utility functions in the docs, as opposed to add more things we have to actively maintain?

**Comment by almarklein** [comment]
@bryevdv point 1 is more or less covered by #3791. I made a quick PR to show what I mean with point 2 in #4161.
