### ISSUE TITLE
Server examples tests take screenshot of blank screen

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3897]
See, for example, the server plots at bottom of this report: https://s3.amazonaws.com/bokeh-travis/0.11.1-9c748ba/report.html 

According to @bryevdv the problem is a "hardcoded (wrong) session id"

**Comment by mattpap** [comment]
This is a duplicate of #3935 and perhaps other issues (what can be summed up as "server examples' tests don't work at all").
