### ISSUE TITLE
All test runs run for ~4 minutes before any testing begins

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3898]
Due to all our build and installation infrastructure, every test run must run for ~4minutes before any testing can begin.

Not sure what we can do, but it's clearly a source of great inefficiency.

**Comment by mattpap** [comment]
Building for each supported configuration is a feature, but rebuilding the same thing several times is a waste (and can be really annoying when tests fail just because we can't connect to npm's servers). I doubt you will be able to improve this much on travis ci. Caching was supposed to help, but was a source of pain on its own.

**Comment by bryevdv** [comment]
I was never quite sure how the caching works. We could revisit it... if it is possible too have it behave specifically, e.g. *only* like "if packages.json has not changed, used cached node_modules" and nothing else, I think that could be helpful. 

Without that, getting rid of phantomJS download and install  (e.g. if we switch to real browsers on sauce labs) would shave ~15 seconds of the beginning of every install. 

More fanciful ideas imagine one job that builds a no-arch package and uploads it to anaconda.org before other jobs start, somehow. Not sure if that's possible, it sounds complicated if so. 

Mostly I agree that there's probably not much room for improvement on TravisCI. Easily supporting this kind of "build first on one job, before running others" might be a useful feature to suggest to the the platform team.

**Comment by bryevdv** [comment]
We do have a no-arch package now. I'm not sure how difficult a "build" job that all other jobs depend on would be

**Comment by damianavila** [comment]
Fresh news: https://blog.travis-ci.com/2017-05-11-introducing-build-stages

**Comment by bryevdv** [comment]
Great I will make a new issue to explore that
