### ISSUE TITLE
Tools in notebook not working in chrome

### ISSUE THREAD

**Issue by dhirschfeld** [bokeh/bokeh#3905]
...but they do in firefox
![chrome](https://cloud.githubusercontent.com/assets/881019/13200422/36feb6da-d892-11e5-912d-a70a8c30b32a.gif)

**Comment by dhirschfeld** [comment]
Chrome info:
```
Google Chrome	48.0.2564.109 (Official Build) m (32-bit)
Revision	dee993990fa912f87e4d1eb5822d408be4896ea5-refs/branch-heads/2564@{#684}
OS	Windows 
Blink	537.36 (@dee993990fa912f87e4d1eb5822d408be4896ea5)
JavaScript	V8 4.8.271.19
Flash	20.0.0.306
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Command Line	"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Profile Path	C:\Users\dhirschf\AppData\Local\Google\Chrome\User Data\Default
Variations	47f591a-ce48e7a2
6345b824-3d47f4f4
e950616e-ca7d8d80
7c1bc906-f55a7974
770a425-ad0da21a
775ebbd7-ca7d8d80
c70841c8-a2567007
f15c1c09-ca7d8d80
fb124cc-803f8fc4
93731dca-3f4a17df
9e5c75f1-3e12a61c
f79cb77b-3d47f4f4
b7786474-64e7d9a
4ea303a6-ecbb250e
4117e878-3d47f4f4
7aa46da5-669a04e0
9736de91-ca7d8d80
dbffab5d-ca7d8d80
c8b9b12d-f23d1dea
6844d8aa-669a04e0
f47ae82a-86f22ee5
3ac60855-486e2a9c
ed1d377-e1cc0f14
75f0f0a0-4ad60575
e7e71889-e1cc0f14
b39ea213-d1372334
bd368a6b-d2c8e0a4
Compiler	MSVC
```

**Comment by jdugge** [comment]
I believe this may be the same bug as #2396 and  #2771: Bokeh doesn't handle touch events in Chrome correctly. A workaround is described in http://bokeh.pydata.org/en/0.10.0/docs/faq.html#are-the-tools-not-working-in-chrome-cromium: You can disable the touch events in Chrome. However, this will break things if your device actually does have a touchscreen.

**Comment by bryevdv** [comment]
That's a good suggestion, we should probably have thought/asked about that earlier. We use a JS library called Hammer.js to handle our UI mouse and touch events in a uniform way. There is a new version of the library, a first test might be to try and update the version we build with. If that does not work, we have to appeal to the community for some expertise to help. Another problem is that AFAIK no one on the team has a touchscreen laptop to test with.

**Comment by bryevdv** [comment]
also possible #1848

**Comment by andersrmr** [comment]
I have a touchscreen laptop running windows8.1/py2 with tools not responding on chrome notebook.  going to try firefox now.

**Comment by damianavila** [comment]
Closing as duplicated... will keep the discussion on #1848
