### ISSUE TITLE
Use `pytest-unmarked` for running unit tests?

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3906]
Previously there have been complaints that to run the unit tests you need to run

`py.test -m 'not (examples or integration or js)'`

I agree this is cumbersome, but didn't know of another solution.

I just ran across this py.test plugin which may help: https://pypi.python.org/pypi/pytest-unmarked

I've never used it but it gets a modest amount of downloads - worth trying?

**Comment by bryevdv** [comment]
Sure but it appears to be a single file, so I'd suggest we just vendor it in: https://github.com/alyssabarela/pytest-unmarked

**Comment by bryevdv** [comment]
That appears to depend on a private pytest api `_pytest.mark` so I'm not inclined to use it. This is not that big a deal, so closing.

**Comment by mattpap** [comment]
@damianavila, I'm curious why 'reso:completed' and not `reso:wontfix`?

**Comment by damianavila** [comment]
> @damianavila, I'm curious why reso:completed and not reso:wontfix?

Because the Github UI sometimes is broken... it happened to me a lot that I tried to set up one label and other is applied...

**Comment by mattpap** [comment]
@damianavila, OK.
