### ISSUE TITLE
Accessing Backbone Collections in Javascript

### ISSUE THREAD

**Issue by tonyfast** [bokeh/bokeh#3912]
Prior to 0.11 it was possible to access the specific glyphs and a data sources using the ``Bokeh.Collections`` API in the browser.  

```
Bokeh.Collections('GlyphRenderer').get(id)
Bokeh.Collections('Circle').get(id)
```

These syntaxes are not working in the newest version of Bokeh.  They return that `0` models are found, but they do not return an error.  Have the Backbone collections changed in the newest version of Bokeh?

**Comment by bryevdv** [comment]
Using `Collections` is still how BokehJS instantiates new models in documents AFACT: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/document.coffee#L198-L213

It looks like you are trying to find existing models? That might not work, in any case it probably won't work at some point, we are trying to get rid of most or all of our Backbone dependence. Use `document.get_model_by_id` instead: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/document.coffee#L126-L130

**Comment by tonyfast** [comment]
It is really nice to be able to access the Bokeh objects using just the ID and ignoring the type.  That's great!

I was able to get to the document using 
```javascript
bkdoc = Bokeh._.values( Bokeh.index )[0].model.document
```

Are there situations in a notebook where there may be multiple documents?

**Comment by bryevdv** [comment]
@tonyfast we "left the door open" in some of the API, but that capability is not currently used in any way.  That said, this is where documents get instantiated in BokehJS typically:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/embed.coffee#L142

We could potentially do something there to make getting at documents later, easier.

**Comment by mattpap** [comment]
Given PR #4078, we should provide an API for collecting objects withing the model graph. I think I will do this within the continued TS API effort, because I have to implement `select()`/`select_one()` API anyway.

**Comment by bryevdv** [comment]
@mattpap agreed but I think this discussion can be closed for several reasons: It's support (belongs on ML), other options have been given, and now Collections are gone.

**Comment by mattpap** [comment]
@bryevdv, actually, at the time I wasn't aware that the APIs are there, just maybe not exposed enough.
