### ISSUE TITLE
(Re)move `tests/compat`, `tests/glyphs`, `tests/notebook`

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3917]
Under the top-level directory there are three directories that I think need tidying up:
- tests/compat
- tests/glyphs
- tests/notebook

As far as I can tell the files under `tests/compat` and `tests/notebook` aren't used anywhere.

The files under `tests/glyphs` are all referenced by `__example__` property in `bokeh/models/glyphs.py` e.g. https://github.com/bokeh/bokeh/blob/master/bokeh/models/glyphs.py#L27

But I can't seem them referenced elsewhere. As such, `tests` doesn't seem like the right directory for them.

Proposals:
1) Delete [`tests/compat`](https://github.com/bokeh/bokeh/tree/master/tests/compat) and [`tests/notebook`](https://github.com/bokeh/bokeh/tree/master/tests/notebook)
2a) Move [`tests/glyphs`](https://github.com/bokeh/bokeh/tree/master/tests/glyphs) to `bokeh/models/__examples__`; or
2b) Move  [`tests/glyphs`](https://github.com/bokeh/bokeh/tree/master/tests/glyphs) to `bokeh/models/tests/examples`; or
2c) Move  [`tests/glyphs`](https://github.com/bokeh/bokeh/tree/master/tests/glyphs) to `bokeh/models/<???>` <suggestions welcome>

**Comment by bryevdv** [comment]
My intention was that they are simple enough to currently also be used as real image diff test sources, that is, actually ***failing*** the test when there is an image diff. 

in any case, they are only needed by the docs, I would not want to move them under the `bokeh` directory and actually ship them with the library, and I think they are too simple/boring to go under `examples`

**Comment by bryevdv** [comment]
Actually maybe `examples/reference` or something would do.
