### ISSUE TITLE
unexpected attribute 'width' to HistogramGlyph, similar attributes are bin_width

### ISSUE THREAD

**Issue by eklusman** [bokeh/bokeh#3921]
When I run this code:

```
import pandas as pd
from bokeh.charts import Histogram
df = pd.DataFrame([[0, 'A'], [0, 'A'], [1, 'A'],
                   [0, 'B'], [0, 'B'], [1, 'B']], 
                  columns=['level', 'unit'])
hist = Histogram(df, 'level', group='unit')
```

I get this error:

```
AttributeError: unexpected attribute 'width' to HistogramGlyph, similar attributes are bin_width
```

I would expect instead to get an actual graph.

My environment:

```
>>> bokeh.__base_version__
'0.11.0'
>>> bokeh.__version__
'0.11.0'
>>> bokeh.print_function
_Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)
```

I initially found this error when running in a jupyter notebook on Firefox 44.0.2 running on a MacBook Pro running OS X Yosemite 10.10.5, but I get the same error running plain python from the command prompt.  It's Python 3.4.4 |Anaconda 2.5.0 (x86_64)| in either case.

**Comment by bryevdv** [comment]
This seems to still be an issue on`0.12dev`

**Comment by ziemerz** [comment]
I'm experiencing this same bug in Bokeh version 0.12.4

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/16)
