### ISSUE TITLE
Downsampling dataset

### ISSUE THREAD

**Issue by apaytuvi** [bokeh/bokeh#3922]
Hello everybody,

I have a dataset with 600M points and i'd like to generate a heatmap with bokeh. Do you believe it is feasible with so many points? I was looking for examples for downsampling data with bokeh, but I didn't found any. Can you help me?

Thanks.

**Comment by bryevdv** [comment]
Hi @apaytuvi There's a few angles to consider. The Bokeh server let's you write apps that can run arbitrary python in response to widget events, range updates, selections, etc. So in that sense you can look at any of the existing app examples and modify those to do whatever kind of downsampling you'd care to implement. 

However, for that many points, you might also want to look at the [bokeh/datashader](https://github.com/bokeh/datashader) project, which is a separate but related project the explicitly helps to interactively visualize hundreds of millions to billions of points. You can also watch a very recent webinar describing and demoing data shader here: https://continuum-analytics.wistia.com/medias/8zu9idwoym

**Comment by jbednar** [comment]
Right -- datashader should work very well for this use case; see the [example notebooks](https://github.com/bokeh/datashader/tree/master/examples) in the repo for how to get started.  I'd first run the NYC taxi notebook on the taxi data, then change it to load and use a portion of your data instead.  Once you get the basics working, you can try modifying the OSM notebook example to use all your data.  It already works fine with 3 billion points, but the tricky bit is just to get the data into a form that you can work with.  We used an experimental fast-loading format called castra in our example, but anything that dask can load should be ok.
