### ISSUE TITLE
Add options to allow use of tile maps other than google maps

### ISSUE THREAD

**Issue by monkut** [bokeh/bokeh#3929]
A brief look at the source, it was unclear how the GMapPlot identifies google maps.

A simple option that would allow users to specify a base tile map url, and identify if it is TMS or Google XYZ would be nice.

Something like:

p = MapPlot(
    tilemap_url='http://mytilemapserver.com/',
    tilemap_type='tms',)

http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/

**Comment by mattpap** [comment]
`GMapPlot` is a special case. You can configure custom tile layers using models from `bokeh.models.tiles`. See https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/airports_map.py as an example.

**Comment by monkut** [comment]
Great! I'll check it out.

Shouldn't this be added to the 'Mapping Geo Data' section in the documentation?

http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html

**Comment by birdsarah** [comment]
@brendancol is working on new documentation I believe.

I'm going to close this issue, as I believe it's resolved.

**Comment by JeroenSchmidt** [comment]
@mattpap I am trying to do the same thing with another map from maptiler.com and im hoping you could help me figure out the tile png URL format. 

Im trying it for the following: https://www.maptiler.com/maps/#darkmatter//vector/2.95/25.87/24.3
