### ISSUE TITLE
Add higher high-level bokeh.charts interface

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#393]
Discussion in this issue of canned schematic plots to support. Ideas:
- [x] bars
- [x] boxplot
- [ ] chord diagram
- [ ] donut chart
- [ ] heatmap
- [x] histogram
- [ ] horizon chart
- [ ] marimekko
- [ ] nightingale rose
- [ ] parallel coordinates (requires layout)
- [x] scatter
- [ ] stacked area
- [ ] step 
- [ ] timeseries
- [ ] treemap
- [ ] violin
- [ ] dot plot

Checked box dos not indicate full, final completion, only that basic functionality is present.

**Comment by jolespin** [comment]
The crop circles plot looks really cool.  I would definitely use those
