### ISSUE TITLE
update DatetimeTickFormatter docstring with actual default formats from the JS side

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#3931]
This docstring:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/formatters.py#L323

should use these formats:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/formatters/datetime_tick_formatter.coffee#L71

... instead of their current placeholder values.

**Comment by bryevdv** [comment]
@pzwang refs to master have shifted. I don't understand, can you elaborate? What placeholder values?

**Comment by bryevdv** [comment]
Upcoming PR provides this for both docstrings and ref docs, which is the best interpretation I can make:

<img width="1293" alt="screen shot 2016-12-21 at 5 33 09 pm" src="https://cloud.githubusercontent.com/assets/1078448/21410048/a0199f1c-c7a3-11e6-8a39-56459bf2109f.png">
