### ISSUE TITLE
"Blog" examples on bokehplots.com

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3932]
We were discussing where we could put examples. 

There's a tension between:
* wanting to show off new features and demonstrate how to use a certain features; and
* having a maintainable set of examples in the repo

This proposal is to add a new section to bokehplots.com e.g. bokehplots.com/blog that could hold these one-time examples, but not be part of the core bokeh repo.

From an implementation point-of-view this would be very easy for standalone examples:
* bokehplots.com is built on [pelican](http://docs.getpelican.com/en/3.6.3/) which has blogs in mind as a technology
* I have built code to integrate bokeh plots into a pelican site before (cecp.mit.edu) and there were no surprises.
* to keep the code light, we would want to be able to specify CDN resources for a given version for a given blog post, which I haven't done before, but should be easy

Server examples I think would need to be i-framed in; or work in conjunction with demo.bokehplots.com.

Notebook examples I believe would be a separate problem.

Known concerns with this proposal are that:
* we'd need to keep something like this relatively fresh, posting, I would say at least once every 2 months.
* others.....please chip in

**Comment by birdsarah** [comment]
> we'd need to keep something like this relatively fresh, posting, I would say at least once every 2 months.

 that doesn't sound too bad to me, while I don't like writing, I do like making examples so I'd be up for volunteering at that frequency

**Comment by bryevdv** [comment]
@quasiben is setting up https://bokeh.github.io/blog/ so that there is any place at all to blog about `0.12` tomorrow. I regret we didn't get a chance to discuss this but now it is a matter of expediency. It seems dead simple and automatically builds on Travis CI, I think we should just go with that until given reason not to. Closing, but re-open if you feel strongly otherwise.
