### ISSUE TITLE
Move examples from bokeh-demos into main repo

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3933]
A while a go there was a discussion about consolidating all the different places our demos / examples live.

One of the proposals from that was that all demos from bokeh-demos (http://github.com/bokeh/bokeh-demos/) either get scrapped or moved into the main bokeh-demos repo (probably under the apps directory).

Some could also go into the "blog" proposed in #3932.

Thoughts?

Edit: Should have said, the motivating factor for this move is that we have too many examples spread across the place and they're currently not very discoverable.

**Comment by bryevdv** [comment]
I'd still like to delete `bokeh-demos`

**Comment by bryevdv** [comment]
The only thing left there AFAIK is `happiness` I'd propose updatding that (if necessary) and moving it, then deleting the repo

**Comment by birdsarah** [comment]
Yes, I agree, I think it's fairly out of date now - i.e. doesn't represent current best bokeh practice. I'd be fine with archiving bokeh-demos and just adding a new issue to re-do happiness.

**Comment by birdsarah** [comment]
> adding a new issue to re-do happiness.

Or adding a similar demo that covers more common use cases now we've had some time with the bokeh server.

**Comment by timsnyder** [comment]
I'm giving the server docs a readthrough and see the link to the outdated  https://github.com/bokeh/bokeh-demos/tree/master/happiness (in the [end of the Shared Publishing section](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#shared-publishing) ).

Are you guys still planning to create a replacement for or updated version of happiness?  If you could describe at a high-level a demo that would be a better replacement for happiness, that might be a good  thing for me to contribute.

**Comment by bryevdv** [comment]
> Are you guys still planning to create a replacement for or updated version of happiness? If you could describe at a high-level a demo that would be a better replacement for happiness, that might be a good thing for me to contribute.

Yes, definitely. My problem is that I don't know Django. Maybe it doesn't have to be Django though. I think the main thing to try and demonstrate in a replacement: A Bokeh app that interacts with a database, and one that shows per-user specific content.

**Comment by timsnyder** [comment]
Okay.  So looking at http://localhost:5009/en/latest/docs/user_guide/server.html#embedding-bokeh-server-as-a-library from master as well as https://github.com/bokeh/bokeh/tree/master/examples/howto/server_embed, it seems like having some kind of examples/howto/server_embed/django_embed.py would be sufficient to replace happiness.

I have minimal experience with Django.  I'll look through the existing examples in howto/server_embed.  It may be that the docs should just point there now regardless of whether they have a Django example there or are a complete replacement for happiness.

**Comment by timsnyder** [comment]
After having actually skimmed through happiness and the existing examples/howto/server_embed, I can see how having a bigger example like happiness would be nice.  

I also see how I should be able to change the way Django is running to use tornado.wsgi.WSGIContainer to run Django in Tornado.   Would that make happiness "better represent Bokeh best practicies" or did @birdsarah mean something else about happiness?

**Comment by bryevdv** [comment]
Right there's two possible goals: 

* add a Django example to `server_embed`, just to round out the flask/tornado/noteboobook suite of examples 

* add an example that show's how to integrate Bokeh server apps with databases and per-user content

I think they are both worthwhile, but if I had to prioritize I'd vote for the second.  The Happiness example happened to be Django, so it might first seem like a "two birds with one stone" situation to just update it. But I'm not so sure for a few reasons:

*  I think all the examples in `server_embed` should be "very simple" to just highlight the embedding usage. A new Django example there should be simple, not big and complicated. 
* I think it's not important whether the database/user example is in Django. It's purpose to is to example some more sophisticated usage. Given that neither of us knows Django well, it would be fine to me to re-do it in Flask, eg. The important part is that it demos db integration, etc. (and it should not go with the simple examples in `server_embed` even if it happens to use that technique)

**Comment by timsnyder** [comment]
Thanks for the great clarificiation.  I think I only have one last question.  If we were to have a bigger example like {{happiness}} come over into bokeh/bokeh, where would you want it to live?  examples/app?

**Comment by bryevdv** [comment]
`examples/app` seems reasonable to me

**Comment by bryevdv** [comment]
@timsnyder do you still intend on working on this? If not that's fine but I think I am going to close this issue as stale at this point.
