### ISSUE TITLE
Turn off server example until they actually run

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3934]
At the moment, I'm not sure of the value of running the server examples in the examples tests because they don't actually open in phantomjs for a screenshot.

With the new examples tests PR #3896, it would be easy to still run the code, but then not try and do the phantomjs and imagedif - which will save a bunch of time for now.

**Comment by bryevdv** [comment]
We have another issue to get the server tests actually running again. I don't want to spend effort to turn them off just to turn them back on again
