### ISSUE TITLE
How to get the server examples testable again

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3935]
The server examples tests don't currently work because the test doesn't know the session id that the server plot ends up running.

---
### Proposal 1: specify sessionid

To make them run, we could change code like:

``` python
session = push_session(curdoc())
```

to be:

``` python
session = push_session(curdoc(), sessionid="name of file")
```

This would be similar to a constraint we impose on the file examples, and means we would know where to look.

However, it has the massive downsides of:
- documenting a bad habit (specifying the sessionid isn't good practice)
- not working for all examples

---
### Proposal 2: add a --test option to bokeh serve

This would monkey patches the sessionid to be the same as the filepath of the example.

This has the disadvantages of:
- being more work than Proposal 1
- adding testing infrastructure into our main code

But it seems like a clean route

---

**Comment by birdsarah** [comment]
Ref: #3934

**Comment by bryevdv** [comment]
Update the report to omit broken server example for now

**Comment by bryevdv** [comment]
Will have to test server examples for `0.12.6` by hand at this point.

**Comment by bryevdv** [comment]
@canavandl I'm marking this issue closed but we should open a new separate issue to cover `examples/app` server examples
