### ISSUE TITLE
Issue while live adding new plots

### ISSUE THREAD

**Issue by the-neworder** [bokeh/bokeh#3937]
Hi,

I'd like to use the bokeh-client to start off with an initial plot in my html. Then every few seconds
I want to add an additional plot and have it appear without reloading the page.

Here an example I created where I try to do it. The document is created with one plot inside a VBox, every second an additional plot is added to the VBox:

```python
from bokeh.plotting import figure, show, output_file, output_server
from bokeh.document import Document
from bokeh.client import push_session
from bokeh.io import curstate, curdoc
from bokeh.models.layouts import VBox
curstate().autoadd = False

import time
import numpy as np

x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)

document = Document()

# create first plot
plot = figure( y_range=(-1.2, 1.2) )
plot.line(x,y,line_width=2, legend="x")

# add plot to the layout
layout = VBox(children=[plot])
document.add_root(layout)

session = push_session(document)
output_server("example.html")
session.show()

for i in range(5):
    time.sleep(1)
    # create additional plots
    plot2 = figure( y_range=(-1.2, 1.2) )
    plot2.line(x,y,line_width=2, legend="x")
    
    # add additional plots to the layout
    layout.children.append(plot2)
```

However I guess doing **layout.children.append** is kind of a hack. The first plot is completely correct, but the additional plots are empty:

![screenshot from 2016-02-25 16 04 51](https://cloud.githubusercontent.com/assets/17453385/13323424/aff50716-dbd9-11e5-846a-346cd6b51b35.png)

Is there a proper way to achieve what iam trying to do here?

**Comment by fpliger** [comment]
Changing from `discussion` to `bug` since I've tried this locally (changing the for look to use a callback function and `add_periodic_callback` instead )and the problem persists...

**Comment by bryevdv** [comment]
@fpliger please post the updated code in cases like this. The following code works as expected on master, so I am closing this as completed (but note, it's simplistic code, it will add new plots infinitely)

```
from bokeh.plotting import figure, show, output_file, output_server
from bokeh.client import push_session
from bokeh.io import curstate, curdoc
from bokeh.models.layouts import VBox
curstate().autoadd = False

import time
import numpy as np

x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)

# create first plot
plot = figure( y_range=(-1.2, 1.2) )
plot.line(x,y,line_width=2, legend="x")

# add plot to the layout
layout = VBox(children=[plot])

curdoc().add_root(layout)

session = push_session(curdoc())

def callback():
    # create additional plots
    plot2 = figure( y_range=(-1.2, 1.2) )
    plot2.line(x,y,line_width=2, legend="x")

    # add additional plots to the layout
    layout.children.append(plot2)

curdoc().add_periodic_callback(callback, 1000)

session.show()

session.loop_until_closed()
```
