### ISSUE TITLE
JS/CSS sourcemaps not loading

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#3940]
In master (commit cf82e80e6f6abada33c3dc7a2eaf1ddfe63348bd), JS and CSS sourcemaps don't load. One example is: `BOKEH_DEV=true python ./examples/plotting/file/texas.py`

The JS and CSS resources (non-minified load normally).

<img width="291" alt="screen shot 2016-02-25 at 1 23 32 pm" src="https://cloud.githubusercontent.com/assets/2198981/13331424/08aabea8-dbc3-11e5-970d-157f11eb3220.png">

The JS sourcemap has been generated and is accessible at the sourcemap url that is appended onto the bokeh.js file (`//# sourceMappingURL=bokeh.js.map`). I'm not getting any 404s from the sourcemap failing to load, it's just seems that the browser doesn't try to load the map

Chrome version 48.0.2564.116 (with the "load JS sourcemaps" flag enabled in the dev tools settings)

ping @mistakevin (in case i'm missing anything)

ping @mattpap (in case you have any insight)

**Comment by canavandl** [comment]
With the newest version of Chrome (Version 49.0.2623.87 (64-bit)), the sourcemaps started loading for me again. I'm not sure it was a bugfix or it changed a browser setting for me. However, the source files that are loaded are the compiled js and not the source coffeescript files.

The most recent gulp refactor breaks the transpilation (into the build/js/tree files) and bundling/sourcemapping/minification into two steps. I think this is so that the bokeh-compiler stuff can add files to the tree that are then bundled into the resource. But, since the sourcemaps are initialized/created in the second step, they are based on the tree files.

It's not clear to me how to get back to having the sourcemap map to the original coffeescript files, short of a pretty big rewrite. It's currently possible to read the JS files, which is not great/not horrible.

**Comment by mattpap** [comment]
I personally I don't use source maps with coffeescript, so it's an easy to miss feature. Restoring support should be fairly easy, because we just have to generate source maps for individually compiled files and then merge them (browserify takes care of this). As for custom model bundles, I'm not sure how much can be done, but it's likely we will get rid of the compiler and precompile custom models (this will be necessary anyway to support typescript).

**Comment by bryevdv** [comment]
> but it's likely we will get rid of the compiler and precompile custom models

+1

**Comment by bryevdv** [comment]
Given that we are migrating to TypeScript, this can be closed
