### ISSUE TITLE
HeatMap Color Value Binning

### ISSUE THREAD

**Issue by mjharrigan** [bokeh/bokeh#3946]
Color values do not seem to be mapping as expected to the given palette on bokeh (0.11.1) with Python 3. I would expect lowest (blue) values to be displayed under the normally distributed data.

```
import numpy as np
import seaborn as sns

from bokeh.plotting import show, output_file
from bokeh.charts import HeatMap

sz = 1000

gamma = list(np.random.gamma(1, 1, size=sz))
normal = list(np.random.normal(size=sz))

cols = gamma + normal
x = ['gamma']*sz + ['normal']*sz
y = list(range(sz)) + list(range(sz))

data = {'x': x, 'y': y, 'color': cols}

palette = sns.diverging_palette(220, 20, n=9).as_hex()

heatmap = HeatMap(data, x='x', y='y', values='color', stat=None, palette=palette)

output_file('tmp.html')
show(heatmap)

sns.palplot(palette)
sns.plt.show()
```

![screen shot 2016-02-26 at 12 51 35 pm](https://cloud.githubusercontent.com/assets/5809425/13360566/d3a39976-dc87-11e5-9f0b-752060fa7de3.png)

**Comment by fpliger** [comment]
this looks like a bug to me... @rothnic do you have any hint?

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/15)
