### ISSUE TITLE
Function links not rendering

### ISSUE THREAD

**Issue by electronwill** [bokeh/bokeh#3952]
http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html says "There are lots of marker types available in Bokeh, you can see details and example plots for all of them by clicking on entries in the list below:" but the entries in the list are not links. The first, asterisk, should probably link to http://bokeh.pydata.org/en/latest/docs/reference/plotting.html#bokeh.plotting.figure.Figure.asterisk .

**Comment by bryevdv** [comment]
This function locations at the bottom of:

https://raw.githubusercontent.com/bokeh/bokeh/master/sphinx/source/docs/user_guide/plotting.rst

Need to be updated. (Note: have to view as "raw" on GH, otherwise it tries to partially render the file in the browser)

**Comment by bryevdv** [comment]
For instance:
```
.. |annular_wedge|     replace:: :func:`~bokeh.plotting.Figure.annular_wedge`
```
should now be 
```
.. |annular_wedge|     replace:: :func:`~bokeh.plotting.figure.Figure.annular_wedge`

```

**Comment by bryevdv** [comment]
@electronwill do you want to make a quick PR for this?

**Comment by electronwill** [comment]
Ah, I see! Yes, I'll create a PR and link it from here.

**Comment by electronwill** [comment]
https://github.com/bokeh/bokeh/pull/3950/files now includes this fix.
