### ISSUE TITLE
Post the html reports generated on Travis to the PR

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3967]
It's annoying having to trawl through the TravisCI logs to find the links to the uploads of the html reports that are generated by our test suite.

@mattpap noted: "maybe we should consider posting a comment (or updating the initial one) with links to most recent reports, so that we don't have to search through lengthy logs of various builds. This is doable with GitHub's PR API."

@bryevdv commented: "I'd be +1 if we can update one comment repeatedly, I much less like the idea of many comments getting added (all but one of which are outdated)"

Personally, I think it would be easier to update the body of the PR, than it would be to edit a comment.

When I looked at this before, the annoying bit of updating a comment, is that you have to know the comment id of the one you want to change, which would mean having to parse comment text from a get request. This would work, but seemed meh to me.

I hadn't seen that the Github API has a PATCH for the body of a PR though: https://developer.github.com/v3/pulls/#update-a-pull-request

The other thing that's annoying is that each test run runs independently so you have up to 3 test runs potentially updating a PR or comment body independently.

None of these things are that difficult, they just push it over the bar from trivial in my opinion.

**Comment by mattpap** [comment]
> (...) it would be easier to update the body of the PR, than it would be to edit a comment.

By initial comment I meant the body of the PR.

> (...) so you have up to 3 test runs potentially updating a PR or comment body independently.

Potentially that's a source of a race condition (you have to read the content first, then update).

**Comment by bryevdv** [comment]
That's actually what I had in mind too.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this. The reports are pretty easy to find now, and if we move off TravisCI soonish, the work would be wasted.
