### ISSUE TITLE
Document usage of a reverse tunnel to an instance of a standalone server

### ISSUE THREAD

**Issue by machinelearningdeveloper** [bokeh/bokeh#3968]
This was already discussed on the Bokeh mailing list.

Per @bryevdv, insert new documentation at about the following location:

https://github.com/bokeh/bokeh/blame/master/sphinx/source/docs/user_guide/server.rst#L496

**Comment by machinelearningdeveloper** [comment]
I will issue a PR against this issue.

**Comment by bryevdv** [comment]
Brilliant, thanks!
