### ISSUE TITLE
Hover tooltip.

### ISSUE THREAD

**Issue by jdupl123** [bokeh/bokeh#3980]
When I scatter A large amount of data points, the hover tooltip often freezes and crashes because there are to points for it to display. It would be nice if there was a way to limit the number to points for which information is show shown when using the hover tooltip. i.e. pick clossest or first n points.

Cheers,
:)

**Comment by mattpap** [comment]
This https://github.com/bokeh/bokeh/wiki/Selection-and-Hit-test-Managements proposal is currently under implementation to fix this issue.

**Comment by mattpap** [comment]
Duplicate of issue #3823.
