### ISSUE TITLE
Scientific notation axis formatter with metric prefix

### ISSUE THREAD

**Issue by artemonster** [bokeh/bokeh#3982]
Would be very nice to have, if some high-resolution data of a value, lets say, 1.2345e+6 is displayed alternatively as 1.2 M'unit', 
or 7.6544e-9 as 7.65 p'unit',
or 1.111e-6 as 1.1 µ'unit',
where you can set your unit to any character(s), like 'm' or 's'. 
So when you actually zoom in and get to see more axis ticks, they are formatted accordingly, scaled up or down, as it is now with normal scientific notation.

**Comment by birdsarah** [comment]
The datetime formatter (http://bokeh.pydata.org/en/0.11.1/docs/reference/models/formatters.html#bokeh.models.formatters.DatetimeTickFormatter) has a similar option for choosing the format depending on the resolution - this seems like it would be a nice addition. Although we'd have to figure out the api.

**Comment by bryevdv** [comment]
This is duplicative of #4621 which will be completed with #4659
