### ISSUE TITLE
Add back the data_tables_server.py to examples tests

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3986]
In #3970 we disabled the `models/data_tables_server` example as it was a consistent source of examples test failures.

We should investigate why it was failing on travis and re-instate if possible.

Also worth noting that it's running old code with a deprecation warning in it:

```
data_tables_server.py:134: BokehDeprecationWarning: bokeh.models.sources.from_df was deprecated in Bokeh 0.9.3; please use ColumnDataSource initializer instead
  self.source.data = ColumnDataSource.from_df(df)
```

**Comment by bryevdv** [comment]
Example is gone, closing.
