### ISSUE TITLE
Updating a Span (line annotation) duplicates it

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#3993]
When updating an existing ``Span`` (line annotation) it is rendered again and again without deleting the old line.

Here is an example that reproduces the issue (adapted from [this](http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#spans) example in the documentation):

```python
from datetime import datetime as dt

from bokeh.sampledata.daylight import daylight_warsaw_2013
from bokeh.plotting import figure, show, output_file
from bokeh.models import Span

output_notebook()

p = figure(x_axis_type="datetime", y_axis_type="datetime")

p.line(daylight_warsaw_2013.Date, daylight_warsaw_2013.Sunset,
       line_dash='solid', line_width=2, legend="Sunset")
p.line(daylight_warsaw_2013.Date, daylight_warsaw_2013.Sunrise,
       line_dash='dotted', line_width=2, legend="Sunrise")

daylight_savings_start = Span(location=(dt(2013, 3, 31, 2, 0, 0) - dt(1970, 1, 1)).total_seconds()*1000,
                              dimension='height', line_color='green',
                              line_dash='dashed', line_width=3)
daylight_savings_end = Span(location=(dt(2013, 10, 27, 3, 0, 0) - dt(1970, 1, 1)).total_seconds()*1000,
                            dimension='height', line_color='red',
                            line_dash='dashed', line_width=3)
p.renderers.extend([daylight_savings_start, daylight_savings_end])

p.title = "2013 Sunrise and Sunset times in Warsaw"
p.yaxis.axis_label = 'Time of Day'

show(p)
```

When updating the line position like this:

```python
from bokeh.io import push_notebook
daylight_savings_start.set(location=(dt(2013, 1, 28, 2, 0, 0) - dt(1970, 1, 1)).total_seconds()*1000)
push_notebook() 
```

It will duplicate the line like this:

![image](https://cloud.githubusercontent.com/assets/1550771/13532095/91cc1542-e221-11e5-9f48-1f51046fa3d0.png)

**Comment by bryevdv** [comment]
I'm at a loss, the render path does not have any loops or repetitions:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/span.coffee#L62-L75

That could be responsible for this. ping @canavandl

**Comment by mattpap** [comment]
`Span` in canvas mode doesn't request render of the plot, so it doesn't remove previously painted stuff.

**Comment by bryevdv** [comment]
@mattpap good catch that is exactly it. Easiest solution is probably a branch here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/span.coffee#L19

if CSS mode, trigger `_draw_span` directly as it is now, if canvas mode, trigger `@plot_view.request_render`

**Comment by bryevdv** [comment]
@philippjfr since you are already set up to test that this works in the environment where the error surfaced, can you submit a small PR for this too?

**Comment by mattpap** [comment]
@bryevdv, yes, a simple inline `if` expression will do the trick.
