### ISSUE TITLE
Box Select tool doesn't work when x or y range is reversed

### ISSUE THREAD

**Issue by clairetang6** [bokeh/bokeh#3996]
Example below. Box select only works in the top-left plot, where both the x and y ranges are in the "normal" direction. Lasso select works on all of the plots though. 

```python 
from bokeh.plotting import Figure, output_file, show
from bokeh.models.sources import ColumnDataSource
from bokeh.io import gridplot

output_file('test_box_select.html')

data = ColumnDataSource({'x': [1, 2, 3, 4], 'y': [10, 5, 2, 6]})
plot_size_and_tools = {'plot_height': 200, 'plot_width': 200, 'tools':['lasso_select', 'box_select', 'reset']}

fig1 = Figure(x_range=[0, 5], y_range=[1, 11], x_axis_label="normal", y_axis_label="normal", **plot_size_and_tools)
fig1.circle(x='x', y='y', source=data)

fig2 = Figure(x_range=[0, 5], y_range=[11, 1], x_axis_label="normal", y_axis_label="reverse", **plot_size_and_tools)
fig2.circle(x='x', y='y', source=data)

fig3 = Figure(x_range=[5, 0], y_range=[1, 11], x_axis_label="reverse", y_axis_label="normal", **plot_size_and_tools)
fig3.circle(x='x', y='y', source=data)

fig4 = Figure(x_range=[5, 0], y_range=[11, 1], x_axis_label="reverse", y_axis_label="reverse", **plot_size_and_tools)
fig4.circle(x='x', y='y', source=data)

show(gridplot([[fig1, fig2], [fig3, fig4]]))
```

**Comment by clairetang6** [comment]
The problem seems to be the hit-testing with the rectangle produced by the box select tool when either range is reversed. When a range is reversed, the mapping from canvas units to data points causes smaller canvas units (e.g. left for an x-range) to be larger data units and vice versa. This is what we want for the display of the data, but it causes a bug in the hit-testing with [rbush](https://github.com/mourner/rbush), which expects rectangles to be defined by the coordinates of their corners in a specific order ([x1, y1, x2, y2] where x1 < x2 and y1 < y2). 

The box-select hit-testing for the circle marker is found in circle.coffee under the method `_hit_rect`. 

```coffee
 _hit_rect: (geometry) ->
    [x0, x1] = @renderer.xmapper.v_map_from_target([geometry.vx0, geometry.vx1], true)
    [y0, y1] = @renderer.ymapper.v_map_from_target([geometry.vy0, geometry.vy1], true)
    result = hittest.create_hit_test_result()
    #if x0 > x1 then [x0, x1] = [x1, x0]
    #if y0 > y1 then [y0, y1] = [y1, y0]
    result['1d'].indices = (x[4].i for x in @index.search([x0, y0, x1, y1]))
    return result
```

The commented code above was added by me and fixes this bug (for the circle glyph), and is in fact found earlier in circle.coffee in the `_mask_data` method. Here are the last five lines of that method, comments not added by me. 

```coffee
    # rbush expects x0, y0 to be min, x1, y1 max
    if x0 > x1 then [x0, x1] = [x1, x0]
    if y0 > y1 then [y0, y1] = [y1, y0]

    return (x[4].i for x in @index.search([x0, y0, x1, y1]))
```

There are two other places where `_hit_rect` (which is eventually called when box select is used) is found, in rect.coffee and marker.coffee. So adding these two lines of code in those three places would fix this bug for the circle, rect, and all the marker glyphs. But this bug could be fixed in other ways too, such as upstream by switching x1 and x0 in the geometry when the mapper is known to a "reverse" mapper, or maybe even downstream in rbush so that rbush will check to make sure the data is in the right order in its `search` function.

**Comment by bryevdv** [comment]
I watch the rbush repo, my impression is that the author would not accept such a change, so I think it's on us to fix this on our end. 

One option would be to enforce a convention, e.g. that `x0` is the "min" and `x1` is the "max". That's maybe something I should have done from the first, it would probably be a bit of a pain to do now. Maybe the easiest thing is to write a function that takes list `[x0, x1]` and returns a list `[xmin, xmax]` that way it could at least be used consistently and the intention would be made clear.
