### ISSUE TITLE
Pixel offsets for text annotating markers

### ISSUE THREAD

**Issue by DLFontenot** [bokeh/bokeh#3998]
Referencing `[Issue 2087](https://github.com/bokeh/bokeh/issues/2087)`,

The feature in the title was dismissed on the premise that "things like that should absolutely be a "labels" annotation of some sort and not a data glyph". Which I don't follow...

If annotations can only be made in the screen space, then they are incapable of following what they annotate if bokeh is zoomed. This issue can be easily [seen here in the element example](http://bokeh.pydata.org/en/0.11.0/docs/gallery/elements.html) by just box zooming onto a circle and its label. However, when you're working with bubbles of different sizes the issue is even more notable. The bigger the bubble, the more easily the label becomes offset.

**Comment by bryevdv** [comment]
I think there was some not-great communication, but "only made in screen space" that includes pixel offsets from data locations, which I expect to be the most common use case. There is an in-flight PR to add label annotations here: https://github.com/bokeh/bokeh/pull/3956 I'd encourage you to check that out and offer comments and guidance to help make sure it covers all the relevant use-cases. (I'm going to close this issue in favor of diccussion on the PR)
