### ISSUE TITLE
Data_table bug, undefined values

### ISSUE THREAD

**Issue by afDeathscythe** [bokeh/bokeh#3999]
Hi,

I got the following problem by plotting my values in a line figure + a Data_table for the visualization of my data, that in the Data_table of the bokeh plot, the values are defined as undefined (only in 2 plots).
If I print the Data_table in an additional .txt file, all the values are shown correctly.

The code looks like this:

```
igeP = figure(title=heading+"_igeJunction", tools=TOOLS, x_axis_label='Distances', y_axis_label='Counts')
        igeP.line(igeJuncDist, igeJuncCount)
             
igeData_table = DataTable(source=ColumnDataSource(igeData), columns=[TableColumn(field="igeJuncDist", title="Distances"), TableColumn(field="igeJuncCounts",      title="Count")], width=600, height=600)             
igePlot = vplot(hplot(igeP, igeData_table))
tab5 = Panel(child=igePlot, title="Intergenic-Exon Junction")
             
igeDataOutput = open(path+"_igeData.txt", "w")
igeDataOutput.write("Distances\tCount\n")
for i in range(0, len(igeJuncDist)):
    igeDataOutput.write(str(igeJuncDist[i]) + "\t" + str(igeJuncCount[i]) + "\n")
             
igeDataOutput.close()
```

Hope you can help me. :)

The files are attached below:
![plot](https://cloud.githubusercontent.com/assets/16720029/13564214/30423166-e448-11e5-828b-cc33ea229b25.png)

![plot1](https://cloud.githubusercontent.com/assets/16720029/13564522/a8f3fc32-e44a-11e5-892c-0c710cbdaf68.png)

[p62_igeData.txt](https://github.com/bokeh/bokeh/files/160974/p62_igeData.txt)

**Comment by dennisobrien** [comment]
Can you make a minimal example demonstrating this bug?  If you can include code that I can copy and paste into a notebook it would make things simpler.  As it is, I can see that the line plot is drawn using `igeJuncDist` and `igeJuncCount` (probably Pandas Series) while the DataTable is created using `igeData` (probably a Pandas DataFrame).  Can you verify that `igeData` has a column named "igeJuncCounts"?  I would expect `DataTable` to complain if the `TableColumn`s didn't match the `ColumnDataSource`.

**Comment by afDeathscythe** [comment]
sry here is the data structure, a dict with 2 arrays. igeJuncDist is an array like igeJuncCount

```
igeData = {
            'igeJuncDist'   : igeJuncDist,
           ' igeJuncCounts' : igeJuncCount       
}
```

**Comment by dennisobrien** [comment]
It looks like there is a leading space in ' igeJuncCounts'.

**Comment by afDeathscythe** [comment]
Yeah you can close it :) now it works^^
