### ISSUE TITLE
quickstart incorrectly states that default is inline - when it is cdn

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4003]
http://bokeh.pydata.org/en/0.11.0/docs/user_guide/quickstart.html#resources

@electronwill - can you take a look.

**Comment by electronwill** [comment]
Yes, it looks like Bryan added that Mar 4 2015.
https://github.com/bokeh/bokeh/commit/8ffa39710fdc9d070ff6974fc7ec9417767924ed

Did it just change recently?

In the command reference at:
http://bokeh.pydata.org/en/0.11.0/docs/reference/io.html#bokeh.io.output_file
the function signature says the default is cdn:
output_file(filename, title='Bokeh Plot', autosave=False, mode='cdn', root_dir=None)
but the mode parameter says the default is inline:
mode (str, optional) – how to include BokehJS (default: 'inline') One of: 'inline', 'cdn', 'relative(-dev)' or 'absolute(-dev)'. See bokeh.resources.Resources for more details.

What should it say currently? Would this draft be correct?

"To generate plots, the client library BokehJS JavaScript and CSS code must be loaded into the browser. By default, the output_file() function will load BokehJS from http://cdn.pydata.org . However, you can also configure Bokeh to generate static HTML files with BokehJS resources embedded directly inside, by passing the argument mode="inline" to the output_file() function."

**Comment by bryevdv** [comment]
I would just change the default to `'cdn'` in the docstring, and nothing else.

**Comment by electronwill** [comment]
Sorry, I think my post here was confusing. The current quickstart text does say that the default is "inline", as Sarah says, so I think that may need changing too. I've created a PR to make the possible changes clearer: https://github.com/bokeh/bokeh/pull/4011
