### ISSUE TITLE
point_policy = "follow_mouse" still snaps to the start of a line

### ISSUE THREAD

**Issue by DLFontenot** [bokeh/bokeh#4004]
IMO:
Lines should have the hovertool follow along the line.
but if this is not possible/important then it would make sense to have an option to decide if it snaps to the start or the end of the line. 

Major use case for this: cumulative distribution graphs
Right now the hovertool would imply that the last segment of a CDG was accumulated by the second to last point, and the last point isn't represented.  

e.g. treat x as people, y as the cumulative percentage of their contribution to something
```
x = [0,1,2,3,4]
#contribution = [1,2,4,3]
y = [0,.1,.3,.7,1]
info = ['none','a','b','c','d']
colors = ['red','yellow','red','yellow','red']

source = ColumnDataSource(
    data=dict(
    x=x,
    y=y,
    info=info
    )
)
    
TOOLS = "pan,wheel_zoom,box_zoom,reset,save,hover"
p = figure(tools=TOOLS)
lines = p.line(x=x, y=y, source=source, line_width=3)
circles = p.circle(x=x,y=y,color=colors,size=6)

hover = p.select(dict(type=HoverTool))
hover.renderers = [lines]
hover.point_policy = "follow_mouse"
hover.tooltips = OrderedDict([
            ("Info","@info")
            ])
show(p)
    
```

I should note, it is possible to "shift" the hover tool data so that the final point's info comes up when the final line is hovered, but it still snaps to the start of the line and is still misleading.

**Comment by bryevdv** [comment]
`point_policy` has no bearing on lines, since you have only configured a line glyph renderer, there is no change to the default behavior. You want `line_policy`:

http://bokeh.pydata.org/en/latest/docs/reference/models/tools.html#bokeh.models.tools.HoverTool.line_policy
