### ISSUE TITLE
Verify GMapPlot stays synced with image overlay

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#4005]
There was a report on the datashader repo that images were not staying synced with GMapPlot.

**Comment by bryevdv** [comment]
@brendancol can you elaborate or provide example code? If not I think this has to be closed.

**Comment by bryevdv** [comment]
In fact I am just going to pre-emptively close with `invalid`. If a reproducible issue appears, please re-open with a complete test case.
