### ISSUE TITLE
Allow for the injection of raw HTML code

### ISSUE THREAD

**Issue by justacec** [bokeh/bokeh#4008]
Currently, the Widget library contains a `Paragraph` and a `PreText` widget allowing the user to put basic text on the rendered page.  Neither of these widgets allows for the inclusion of formatted text using HTML markup.  A widget should be added to support the inclusion of raw HTML.  The widget can be a simple div named div tag.

**Comment by fabricevidal** [comment]
Same need here!

**Comment by birdsarah** [comment]
This is a good idea and I feel like we've had this request before, although I can't find another issue for it.

Can I suggest though that in the short-term you should be able to use a CustomModel to achieve the same. If one person made it and shared it then others could use.

**Comment by justacec** [comment]
@birdsarah I am not sure how I could make a CustomModel which nicely packages up the python and the JS code at the same time.  It seems easier to just make a div tag widget which could be used.  Just model it off the current paragraph widget and subclass it off the Markup widget.

**Comment by justacec** [comment]
@birdsarah I went ahead and put together a PR to address this.  There may be a better way to handle this.  Take a look and let me know.
