### ISSUE TITLE
output html to string

### ISSUE THREAD

**Issue by asullivan000** [bokeh/bokeh#4009]
To integrate with other methods of rendering html it would be very useful to have methods to output html into a string from the show() method

**Comment by bryevdv** [comment]
This are already two functions in ` bokeh.embed` that could be used before this:

http://bokeh.pydata.org/en/latest/docs/reference/embed.html#bokeh.embed.file_html
http://bokeh.pydata.org/en/latest/docs/reference/embed.html#bokeh.embed.standalone_html_page_for_models

One of them will likely be deprecated in the future.
