### ISSUE TITLE
Jupyter Notebook CSS is tied to the notebook structure

### ISSUE THREAD

**Issue by dalogsdon** [bokeh/bokeh#4012]
We have a [dashboard server](https://github.com/jupyter-incubator/dashboards_server) that executes notebook files and displays the output. I see some notebook-specific styling to clean up a few things in [continuum.less](https://github.com/bokeh/bokeh/blob/819663e2edc47aa4373b230412279aef6ef01ee0/bokehjs/src/less/continuum.less#L19). The `#notebook` selector bolts the styling to the notebook structure, but we need this styling to override some of our own table styling and would rather not mimic the notebook structure just to get this styling applied.

Is there some way this styling can be made less specific so that plots generated after loading `output_notebook` can get this styling? This may also be helpful in the future as Jupyter Notebook evolves into Jupyter Lab.

You can see the extra borders appearing around the Bokeh plot in this screenshot:

![image](https://cloud.githubusercontent.com/assets/6362426/13651800/8f1e047c-e60e-11e5-9d93-eef02da7aec2.png)

**Comment by bryevdv** [comment]
Version information is needed. This is a bug in current master and recent dev builds, but has never been present in any full release, AFAIK. If you are seeing this on a full release, that's important information, but we will need more information to try and reproduce it. If you are using a dev build I would suggest falling back to a full release, they are not guaranteed to be stable,

**Comment by bryevdv** [comment]
Regarding hooks for styling, it's possible, but a concrete proposal would go a long way towards advancing a discussion.

**Comment by dalogsdon** [comment]
We are using 0.11.1. The borders are our own styling for other tables, similar to Jupyter Notebook's [rendered_html](https://github.com/jupyter/notebook/blob/d71a59cc9fcf388b3de59950cfd63928b68c6780/notebook/static/notebook/less/renderedhtml.less#L57) output styling. The `#notebook ...` Bokeh styling I linked to above hides those borders, but we currently aren't making use of that style since it includes the `#notebook` ID selector.

**Comment by bryevdv** [comment]
Ah I see. @mattpap @birdsarah do either of you have suggestions? My CSS is not good enough to suggest an approach

**Comment by dalogsdon** [comment]
Regarding a proposal, I was thinking along the lines of not caring about the parent structure in the styles. Do they need to actually use the `#notebook` selector? I'm not familiar enough with Bokeh to know if the structure is always going to be the same across the different output modes.

The simple case could be to simply not use the `#notebook` selector and always have that border override styling applied. Will this break other cases?

If a more sophisticated approach is required, can the resources sent optionally include the extra styling if required? For example, when using `output_notebook` a `bokeh-notebook.css` could be sent along with the base CSS and contain these border overrides without the `#notebook` selector. Then for other (non-notebook) output methods just send the base CSS?

**Comment by bryevdv** [comment]
@dalogsdon as it turns out, removing `#notebook` might actually fix my other issue (with a little extra work). I'll have a PR up by tomorrow morning you can try out if you like.

**Comment by bryevdv** [comment]
@dalogsdon please try out #4013 if you can

**Comment by dalogsdon** [comment]
I tried it out, it seems to be working properly. My plot works fine and the borders are gone. I don't see any `#notebook` styling either.

It took me a while to realize I couldn't `pip install` from the repo like I did with plotly. This would definitely be handy when trying out Bokeh in a notebook. I eventually found #2912 and then just manually built & installed to try the changes.

**Comment by bryevdv** [comment]
@dalogsdon Thanks I am glad that is working, I will merge this soon. As for `pip`, BokehJS is actually written in CoffeeScript, and has a separate compilation step and also a separate npm install step. I'm not sure how we could reliably make all that work with just `pip install` unfortunately.

**Comment by bryevdv** [comment]
@bokeh/dev I will merge this tomorrow unless there is objection. ping @birdsarah

**Comment by bryevdv** [comment]
The `#notebook` selector has been removed.
