### ISSUE TITLE
BEP Proposal: Mandating PRs have associated issues (no issue PRs)

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4015]
Per mailing list discussion, there's interest in mandating that all pull requests have an issue that it addresses. Currently, having a related issue is only suggested.

This would help achieve the dichotomy where issues are for discussions of defects and/or feature requests while pull request discussions can focus on the code implementations and advisability of specific fixes or features.

This would also make searching the project history simpler, as relevant historical discussions are going to generally be located in the issue tracker (no need to also search the pull request tracker).

**Comment by birdsarah** [comment]
What about things like: https://github.com/bokeh/bokeh/pull/4018

It's a 5-line PR that fixes up a bug I spotted in an example. I did this as a "hotfix" PR - meaning I used the convention of putting hotfix in the branch name and therefore didn't put an issue it was fixing.

Would this convention still be allowed? It lowers the barrier for making small improvements.

**Comment by birdsarah** [comment]
Can you link to the mailing list discussion?

**Comment by bryevdv** [comment]
I think it was an office discussion. It's a slight burden but it's also an really annoying inconsistency that makes reporting and automation around reporting alot more fragile and difficult. To be clear, I'm personally fine with issues "after the fact" (though thats not preferable) but the point is that all issue related tags go outside PRs.

**Comment by damianavila** [comment]
Yep... having issues-pr makes the things complicated... I was not present in those discussion but I could not agree more. And yes... I know that it could be a little annoying to open an issue for a one line PR but it is conceptually the right thing to do and in fact, it just, probably, one more minute... so let's enforce it.
