### ISSUE TITLE
New reso - `reso:referred` label

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4019]
With an increasing number of issues on github, we need to direct support requests to the mailing list and close them straight away. At the moment we only have `reso:invalid` for this, which seems a little harsh to people reaching out for help.

Proposal is for new reso `reso:referred`. 

BEP 1 states that new reso's will only be considered after a discussion in a new BEP - I'm not sure how to do that, so am making an issue. ping @bryevdv @damianavila 

---

https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management
```
New reso values will only be considered after discussion in a new BEP, and must have accompanying documentation updates. 
```

**Comment by bryevdv** [comment]
I don't think we need a whole BEP just for that, maybe that ought to be changed. Personally I think a discussion here should suffice. I'm +1

**Comment by damianavila** [comment]
Yep, I agree with @bryevdv, in fact we maybe need to relax that requirement a little bit... but as I said, in this case, :+1:

**Comment by bryevdv** [comment]
OK for the sake of forward movement, I will add this `reso` and close this issue. I do think a pass over `BEP-1` is in order in the near future.

**Comment by damianavila** [comment]
> I do think a more through pass over BEP-1 is in order in the near future.

I agree... it is in my todo list since several weeks ago, but still I did not find time to make it...
