### ISSUE TITLE
Problem with sphinx.ext.napoleon when building docs

### ISSUE THREAD

**Issue by gonike** [bokeh/bokeh#4020]
I'm trying to build the docs for the first time right now, and I receive an 

    Extension error:
    Could not import extension sphinx.ext.napoleon (exception: No module named 'sphinx.ext.napoleon')

when doing `make all` in the sphinx directory. Could this be related to the discussion [here](https://github.com/bokeh/bokeh/issues/2984)? I'm quite new, have never worked with sphinx before, and am a bit unsure about how to proceed. Sphinx version is 1.2.3.

**Comment by bryevdv** [comment]
@gonike you need Sphinx > 1.3 (which has `sphinx.ext.napoleon` built in)

**Comment by gonike** [comment]
@bryevdv `conda list` says I have sphinx 1.3.5 - the 1.2.3 stated above appears when I do `make all` in the sphinx directory: "Running Sphinx v1.2.3"... and then, the cited extension error occurs. `sphinx-build --version` also displays `Sphinx (sphinx-build) 1.2.3`. Does this mean I somehow have multiple versions of sphinx installed and am using an older one?

**Comment by gonike** [comment]
There's something weird going on here, trying to sort it out...

**Comment by bryevdv** [comment]
Yes Sphinx changed their packaging between the versions and it broke my update too. If you look In site packages you'll see a sphinx directory and also an old egg IIRC. I'd just delete everything Sphinx related and re install Sphinx.

**Comment by gonike** [comment]
Maybe I'm too stupid, but I can't seem to resolve this (reinstalled everything multiple times): When I install everything on a python 3.4.4 env, installations pass without problems, but in the end I receive the error shown above. When I use a python 3.5 env, sphinx version looks fine, but I can't install (at least) ggplot and sphinxcontrib-httpdomain, which seem to be required according to [this doc page](http://bokeh.pydata.org/en/latest/docs/dev_guide/documentation.html)
What could I be doing wrong? Are you all using python 3.4.X or 3.5.X?
I'm installing those two packages using `conda install -n bokehdoc -c bokeh ggplot` and the same for sphinxcontrib-httpdomain.

**Comment by bryevdv** [comment]
No you're not stupid, this ate up a really silly arount of my time in the same way, I wish I could recall the exact solution. Can you check to see if there is anything "Sphinx" (with a capital initial S) laying around your site-packages?

**Comment by bryevdv** [comment]
Looking at my bash history, maybe I have it backwards and 1.3.1 is capital-S "Sphinx" and the old version is lowercase-s "sphinx"

**Comment by gonike** [comment]
Removing `sphinxcontrib-httpdomain` did the trick! For whichever reason, that package somehow caused an old version of sphinx to be used. Once I succeed building the docs I'll remove it from the list of required packages... speaking of which... ;)

**Comment by bryevdv** [comment]
What a mess! I'm glad it was a simple fix in the end

**Comment by enfeizhan** [comment]
@gonike Could you be more specific where to remove ``sphincontrib-httpdomain``. I am using 1.4.8 and still have the same issue.
