### ISSUE TITLE
How to update the Figure attributes (factor range of xaxis) after the Figure is created using bokeh server?

### ISSUE THREAD

**Issue by mada0304** [bokeh/bokeh#4022]
I was using bokeh serve 0.11.0 and and trying to add a widget to sort the points according to some criteria. Ideally, the categorical xaxis should be updated as well. But it turns out that there is no way to update the x_range after categorical xaxis is sorted. Even though I can update the value of x_range like below:

`fig.x_range=FactorRange(factors=countries)`

But the x_range in the figure is just not updated. Is this not supported yet?

**Comment by bryevdv** [comment]
@mada0304 first, this sort of general support question should be first directed to the public mailing list. Apart from a wider base of users who can potentially help, it also keeps the issue tracker clear for features and bugs. This is important because as you can see the issue tracker is getting quite large. 

That said, you might try changing the factors attribute of the existing range:
```
fig.x_range.factors = countries
```
instead of replacing the range wholesale.

**Comment by mada0304** [comment]
Thank you so much and it solved my issue magically. Actually, I was first time using Github... Sorry for the misbehavior and I would very like to know how to add it to the public mailing list as well.

**Comment by bryevdv** [comment]
No apologies needed! I am glad that worked, also the mailing list is just a "Google group" you can find it at:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by badbye** [comment]
`fig.x_range.factors = countries` seems does not work on the bokeh server.

**Comment by BravoRoot** [comment]
I was able to succesfully update the x_range of a figure in my project.
Here below is a working example of what I did. The trick I used is to make x_range = [] before assigning a new value. I came up with this method after I noticed that only on my first attempt of assigning it a value, it would work... 

Run using:
python -m bokeh serve --show update_x_range_of_figure_example.py

# made by BravoRoot

from random import randint

from bokeh.layouts import column, row
from bokeh.models import Button, TextInput, ColumnDataSource
from bokeh.plotting import figure, curdoc

curdoc().clear()

# on a buttoncallback I do the following
def button1_callback():
    new_value = randint(0, 9)
    my_value_array.append(new_value)
    value_index = len(my_value_array)

    new_label= "{} - {}".format(value_index,text_input1.value)
    my_label_array.append(new_label)

    plot1.x_range.factors = [] # <-- This is the trick, make the x_rage empty first, before assigning new value
    plot1.x_range.factors = my_label_array

    new_data = dict()
    new_data['my_labels'] = my_label_array
    new_data['my_values'] = my_value_array
    my_source.data = new_data
    print("Updated plot2")


my_value_array=[]
my_label_array= []

# Init the plot with x_range=[]
my_source = ColumnDataSource(data=dict(my_labels=[], my_values=[]))
plot1=figure(x_range=[],title="Update x_rage example - by BravoRoot")
plot1.vbar(x='my_labels', top='my_values', width=0.9, source=my_source)

# Intit a button and a textfield
button1 = Button(label="Add point")
button1.on_click(button1_callback)
text_input1 = TextInput(value="", title="Point label:")

# Configure layout of the UI
widgets = column(button1, text_input1)
plots = column(plot1)

# Put the button and plot in a layout and add to the document
curdoc().add_root(row(plots,widgets))

print("Done")

**Comment by bryevdv** [comment]
@BravoRoot @badbye Bokeh can only detect changes to most container properties when a *new object* is used to assign. The problem in your cases is that you are updating a list in place, then re-assigning the exact same list object. Bokeh does not see that change, and doesn't update the browser's value so when you update the data it references factors that never made it to the browser.  I.e., the following code makes your example work:
```
plot1.x_range.factors = list(my_label_array)  # Bokeh can detect new list object
```

**Comment by BravoRoot** [comment]
@bryevdv 
Thanks for the clear explanation. I tested it and you are absolutely right!
Best regards

**Comment by kylrth** [comment]
@bryevdv your comment should be placed somewhere prominent on the user guide. It cleared up a lot of misunderstandings for me.

> Bokeh can only detect changes to most container properties when a new object is used to assign.
