### ISSUE TITLE
BarChart behaving badly

### ISSUE THREAD

**Issue by krey** [bokeh/bokeh#4023]
`Bar({'x': [1,2,3,4,6,7], 'y':[3,4,5,2,3,4]}, label='x', values='y', bar_width=0.4)`
produces the following figure:
![bokeh](https://cloud.githubusercontent.com/assets/223908/13724966/8099fdf0-e863-11e5-8059-f323c4f658e8.png)

Instead of the expected one. Changing the code to
`Bar({'x': ['1','2','3','4','6','7'], 'y':[3,4,5,2,3,4]}, label='x', values='y', bar_width=0.4)`
works as expected

**Comment by bryevdv** [comment]
@krey Bar charts have categorical axes by definition, which I expect is the proximate cause of the problem. I guess there is a reasonable argument that `bokeh.chart.Bar` should automatically convert numeric scale values into discreet categorical labels. @fpliger thoughts?

**Comment by fpliger** [comment]
Yeap, that sounds reasonable...

**Comment by bryevdv** [comment]
`bokeh.charts` has been moved to the `bkcharts` repo. If necessary, this issue should be re-opend there.
