### ISSUE TITLE
Bokeh.charts tick

### ISSUE THREAD

**Issue by gmzero** [bokeh/bokeh#4024]
How do I change the ticks in the x axis? Say from int, I want to map it to a certain customized labels?

plot = Line(datax[['fake date', 'y']], x='fake date', y='y', color='gray', tools = 'hover')

**Comment by damianavila** [comment]
Can you please re-post this question on the mailing list? Thanks!!

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

Just for you info, your question is not invalid, we are just asking to post this kind of questions in the mailing list. We will use a better label in the future :wink:
