### ISSUE TITLE
Bokeh error on column lenght

### ISSUE THREAD

**Issue by Safariba** [bokeh/bokeh#4025]
I am using bokeh 0.11.0 in ipython 3.5 , when I want to create a plot, I have this error:

ColumnDataSource column lengths are not all the same: ColumnDataSource, ViewModel:ColumnDataSource, 

my column names are none for index column, ulid, date, time, and Rudsgmeasure

in #2491, you said that this issue will be fixed for 0.10.0 , but I still have the problem

Can you help me?

**Comment by bryevdv** [comment]
There's not much we can do without code to run to reproduce the problem. Can you provide a minimal, runnable code sample?

**Comment by Safariba** [comment]
```
output_file(BokehDir+ "/"+"plot.html", title="plot example")
plot = figure(tools= "reset,resize,wheel_zoom,hover",toolbar_location="right",x_axis_label='x', y_axis_label='y')
plot.circle(sdev.index[0:500], sdev.values[0:500], color= 'red', legend="printerDct-part1", line_width=2)
plot.diamond(sdev.index[0:1000], sdev.values[500:1000], fill_color="blue", legend="printerDct-part2")
plot.square(sdev.index[1000:1500], sdev.values[1000:1500], fill_color="green", legend="printerDct-part3")
show(plot)
```

![image](https://cloud.githubusercontent.com/assets/15015174/13745573/1f73eb70-e9ef-11e5-8c2c-c55ed4aa995d.png)


It finally shows the diagram but still it shows the error:
![image](https://cloud.githubusercontent.com/assets/15015174/13745595/3756f390-e9ef-11e5-84fe-7a622153d6cd.png)

**Comment by dennisobrien** [comment]
plot.diamond(sdev.index[0:1000], sdev.values[500:1000], fill_color="blue",
legend="printerDct-part2")

The first argument has 1000 elements and the second argument has 500
elements. Did you mean to say sdev.index[500:1000]?

**Comment by Safariba** [comment]
yes I meant sdev.index[500:1000]

plot = figure(tools= "reset,resize,wheel_zoom,hover",toolbar_location="right",x_axis_label='x', y_axis_label='y')
 plot.circle(sdev.index[0:500], sdev.values[0:500], color= 'red', legend="printerDct-part1", line_width=2)
 plot.diamond(sdev.index[500:1000], sdev.values[500:1000], fill_color="blue", legend="printerDct-part2")
 plot.square(sdev.index[1000:1500], sdev.values[1000:1500], fill_color="green", legend="printerDct-part3")
 show(plot)

**Comment by Safariba** [comment]
Actually | dont have the same error anymore!!!!

**Comment by bryevdv** [comment]
Glad to hear, closing now.
