### ISSUE TITLE
Using Linked brushing like technique to create second plot

### ISSUE THREAD

**Issue by rbiswas4** [bokeh/bokeh#4026]
There are a number of examples that show information about a point on a plot when the mouse hovers over that point. For example, http://demo.bokehplots.com/apps/movies shows data about the movie when the mousetip hover over the point representing the movie. 

What I want is to show a plot relating to this point instead of a text box (preferably on a second subplot).  Is this possible using bokeh? Can someone please recommend an example that does this ?

**Comment by damianavila** [comment]
Can you please re-post this question on the mailing list? Thanks!!

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by damianavila** [comment]
Just for you info @rbiswas4, your question is not invalid, we are just asking to post this kind of questions in the mailing list. We will use a better label in the future :wink:
