### ISSUE TITLE
docserver.py is not windows compatible

### ISSUE THREAD

**Issue by gonike** [bokeh/bokeh#4027]
The `docserver.py` script is not windows compatible since it uses `os.fork`. Is there an alternative way of running a doc server on windows?

**Comment by bryevdv** [comment]
You can probably just run `python -m http.serve` on the build results.

**Comment by bryevdv** [comment]
Alternatively, looking at the code:
```
    pid = os.fork()
    if pid != 0:
        # Parent process
        http_server.listen(PORT)
        IOLoop.instance().start()
    else:
        # Child process
        import time
        import webbrowser
        time.sleep(0.5)
        webbrowser.open("http://localhost:%d/en/latest/index.html" % PORT, new="tab")
```
The fork is just to be able to nicely open a web-browser, this could probably be put in a `try...except` block, or alternatively removed altogether, and the auto-browser open handled in the makefile somehow. But in the immediate term you can also just comment out everything except whats in the `try` block above
