### ISSUE TITLE
How to set CategoricalTickFormatter for display custom axis value

### ISSUE THREAD

**Issue by xgenvn** [bokeh/bokeh#4032]
Hi,
I want to display x axis as category names instead of showing raw number. I check through the documentation but there's no clue of how to do it. It should be something like **x_axis_type='datetime'** but which I can map the _[1..n]_ to _['a', 'b' ... ]_. Having hard time looking into the source but no way out. I'm not really sure whether it's **CategoricalTickFormatter** or **x_range_name** can handle this. Hope someone can give me a hint or any suggestion.

Thanks.

**Comment by bryevdv** [comment]
@xgenvn, this kind of general support question should go to the Bokeh public mailing list. There are more people there that can potentially help, additionally we need to keep the GH issue tracker reserved for features and bug reports to keep it manageable.

That said, there is information about categorical axes here:

http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#categorical-axes

As well as some examples in the gallery.

**Comment by xgenvn** [comment]
Sorry and It's okay now, I know I have to subclass the TickerFormatter or create new one.
Related to #3930 , it's simpler than I thought.
