### ISSUE TITLE
Line chart fails when I run it for the second time

### ISSUE THREAD

**Issue by Safariba** [bokeh/bokeh#4040]
For the first time, I have the correct output of line chart, but when I run the cell for the 2nd time it fails. I have to restart the kernel to be able to have it again.

`from bokeh.charts import Line

line = Line(df, title="Line chart", legend="top_left", ylabel='ryDf Values')

dvb.choose_output()

show(line)`

For the second time that I run, I have this error:  Data must be 1-dimensional

![image](https://cloud.githubusercontent.com/assets/15015174/13874633/766c631e-ecf9-11e5-9c34-d6a468d7a886.png)

![image](https://cloud.githubusercontent.com/assets/15015174/13874649/9099c0d8-ecf9-11e5-918a-98c77e755f19.png)

**Comment by brendancol** [comment]
hey @Safariba  It looks like you are sending in multidimensional array instead of a 1d array.

**Should work fine:**

```python
# create a new line chat with a title and axis labels
data = {}
data['1'] = np.random.randint(100, size=100)

p = Line(data, title="simple line example", xlabel='index', ylabel='data_value', width=400, height=400)

# show the results
show(p)

```

**Won't work:**
```python
# create a new line chat with a title and axis labels
data = {}
data['1'] = np.random.randint(100, size=100).reshape((10,10))

p = Line(data, title="simple line example", xlabel='index', ylabel='data_value', width=400, height=400)

# show the results
show(p)

```

**Comment by Safariba** [comment]
I dont think its the problem of the multi-dimensional data, because I have the results for the first time:

![image](https://cloud.githubusercontent.com/assets/15015174/13951148/52077228-f02f-11e5-97f0-80df2e413e42.png)

But if I change the code to only one dimension, the problem will be solved, but its no the thing that I want:

I changed the code to:
![image](https://cloud.githubusercontent.com/assets/15015174/13951190/99eb63a6-f02f-11e5-978f-f881e7bb5eaf.png)

and the result is:
![image](https://cloud.githubusercontent.com/assets/15015174/13951203/acafbe9c-f02f-11e5-888e-cb348442d3b3.png)


It only showed the index value!

**Comment by bryevdv** [comment]
I think Brendan was suggesting that you had columns that were themselves multidimensional, not that you had more than one column (which is fine)

**Comment by bryevdv** [comment]
closing for lack of update
