### ISSUE TITLE
Issue with webgl line plots on Windows only

### ISSUE THREAD

**Issue by muse-ee** [bokeh/bokeh#4043]
I've found an apparent bug in Bokeh's line plots that only appears on Windows, when webgl is enabled, and (apparently, although this has been more difficult to show conclusively) only with certain types of data. The code to produce this case is as shown below (where I've attached bad_case.npz, as well as the two resulting output files on my system). A few other notes:

1. I am running bokeh 0.11.1
2. The OS showing this issue is Windows 7, 64-bit edition
3. My python installation is 2.7.11, Anaconda 2.4.1 (64-bit edition)
4. The browser I'm using is Chrome version 49
5. I tried the same code on my Ubuntu linux machine at home and found that the webgl plot rendered correctly in that environment, so I conclude there is something about Windows that might be an issue here?

`import numpy as np`
`from bokeh.plotting import figure, output_file, show`
`npzfile = np.load('bad_case.npz')`
`f = npzfile['arr_0'] # Vector of frequency bins for spectrogram`
`dB = npzfile['arr_1'] # Vector of power density for each frequency bin (all negative numbers but no NaNs)`
`plot = figure(webgl=True)`
`output_file('spectrum_bad_webgl.html')`
`plot.line(f,dB)`
`show(plot) # Renders the spectrogram correctly`
`plot2 = figure()`
`output_file('spectrum_correct_no_webgl.html')`
`plot2.line(f,dB)`
`show(plot2) # Bizarre scaling issue`

[bad_case.zip](https://github.com/bokeh/bokeh/files/180821/bad_case.zip)

**Comment by bryevdv** [comment]
ping @almarklein

**Comment by almarklein** [comment]
Thanks for the report. Fortunately, this was fixed in #3888 (which was after the 0.11.1 release)
