### ISSUE TITLE
TraitError: The 'kernel' trait of a Comm instance must be a Kernel, but a value of type 'NoneType' (i.e. None) was specified.

### ISSUE THREAD

**Issue by great-thoughts** [bokeh/bokeh#4045]
I am getting this error
```
TraitError: The 'kernel' trait of a Comm instance must be a Kernel, but a value of type 'NoneType' (i.e. None) was specified.
```
I am trying to plot a list of vocab in 2D similar to the tutorial here:

However, I got this error. This is how I am doing it:

```
from param_config import config
from gensim.models import word2vec
from sklearn.manifold import TSNE
import numpy as np

model_name = config.feat_folder+"/300features_10minwords_10context"
model = word2vec.Word2Vec.load(model_name)
model_TSNE = TSNE(n_components=2, random_state=0)

vocabs = model.vocab.keys()
all_words = []
for vocab in vocabs:
    all_words.append(model[vocab])

model_TSNE.fit_transform(all_words)

from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=50, random_state=0)
svd_tfidf = svd.fit_transform(all_words[:10000])

from sklearn.manifold import TSNE

tsne_model = TSNE(n_components=2, verbose=1, random_state=0)
tsne_tfidf = tsne_model.fit_transform(svd_tfidf)


import bokeh.plotting as bp
from bokeh.models import HoverTool, BoxSelectTool
from bokeh.plotting import figure, show, output_notebook

output_notebook()
plot_tfidf = bp.figure(plot_width=900, plot_height=700, title="Web Summit 2015 tweets (tf-idf)",
    tools="pan,wheel_zoom,box_zoom,reset,hover,previewsave",
    x_axis_type=None, y_axis_type=None, min_border=1)

plot_tfidf.scatter(x=tsne_tfidf[:,0], y=tsne_tfidf[:,1],
                    source=bp.ColumnDataSource({
                        "tweet": vocabs[:10000],
                        "processed": vocabs[:10000]
                    }))

hover = plot_tfidf.select(dict(type=HoverTool))
hover.tooltips={"tweet": "@tweet (processed: \"@processed\")"}
show(plot_tfidf)
```

**Comment by bryevdv** [comment]
Version information for everything involved (notebook, bokeh, browser, OS) is needed to do any kin of investigation.

**Comment by great-thoughts** [comment]
now I am running the code from jupyter notebook. I am getting a different error:
The kernel appears to have died.
notebook: jupyter 4.0.6
OS: OS X YOSIMITE
bookeh: .11.1
browser: firefox 44.0.2

**Comment by bryevdv** [comment]
> now I am running the code from jupyter notebook. I am getting a different error: The kernel appears to have died.

I've never seen Bokeh affect a running kernel, and I can't think of mechanism that would let it, either. Can you verify whether your issue happens with all the bokeh code commented out or not?

**Comment by bryevdv** [comment]
I was going to try and run your code, but I don't know where `param_config` comes from. I can't find a conda or pip package for it.

**Comment by great-thoughts** [comment]
I have removed the "param_config" dependency. However, you need the word model file to be able to run my code. below are the links. 
https://drive.google.com/open?id=0Bzf8iECSHrSPVTVfUWFFT285Yzg
https://drive.google.com/open?id=0Bzf8iECSHrSPb1pkMVVmamQ1OW8
https://drive.google.com/open?id=0Bzf8iECSHrSPYlhZOGZsRjU3X3M
Appreciate it.
`from gensim.models import word2vec
from sklearn.manifold import TSNE
import numpy as np

model_name = "/300features_10minwords_10context"
model = word2vec.Word2Vec.load(model_name)
model_TSNE = TSNE(n_components=2, random_state=0)

vocabs = model.vocab.keys()
all_words = []
for vocab in vocabs:
    all_words.append(model[vocab])

model_TSNE.fit_transform(all_words)

from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=50, random_state=0)
svd_tfidf = svd.fit_transform(all_words[:1000])

from sklearn.manifold import TSNE

tsne_model = TSNE(n_components=2, verbose=1, random_state=0)
tsne_tfidf = tsne_model.fit_transform(svd_tfidf)


import bokeh.plotting as bp
from bokeh.models import HoverTool, BoxSelectTool
from bokeh.plotting import figure, show, output_notebook

output_notebook()
plot_tfidf = bp.figure(plot_width=900, plot_height=700, title="Web Summit 2015 tweets (tf-idf)",
    tools="pan,wheel_zoom,box_zoom,reset,hover,previewsave",
    x_axis_type=None, y_axis_type=None, min_border=1)

plot_tfidf.scatter(x=tsne_tfidf[:,0], y=tsne_tfidf[:,1],
                    source=bp.ColumnDataSource({
                        "tweet": vocabs[:1000],
                        "processed": vocabs[:1000]
                    }))

hover = plot_tfidf.select(dict(type=HoverTool))
hover.tooltips={"tweet": "@tweet (processed: \"@processed\")"}
show(plot_tfidf)`

**Comment by great-thoughts** [comment]
Problem solved. Yes the dead kernel wan not caused by booked.
