### ISSUE TITLE
Add a sort function to the JS implementation of ColumnDataSource

### ISSUE THREAD

**Issue by justacec** [bokeh/bokeh#4047]
It might be necessary for client side sorts of a ColumnDataSource based on some criterion.  Although this can be done in other ways, I think that the mot natural place for this would be directly in the ColumnDataSource module.

**Comment by bryevdv** [comment]
I have not perceived any strong demand for this, or concrete use-cases described, so I am going to close this discussion as stale. If someone really does need to do this, it's doable in JS from any `CustomJS` callback
