### ISSUE TITLE
improve documentation to support running unit tests locally

### ISSUE THREAD

**Issue by dennisobrien** [bokeh/bokeh#4049]
I was trying to run unit tests locally as I am working on a PR and I ran into several issues that could be avoided by some changes to the documentation.

After some trial and error, I figured out I needed:
- The dependencies mentioned here:  http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#dependencies  In hindsight this was pretty obvious, but we should add a link to this section from the page on testing.  http://bokeh.pydata.org/en/latest/docs/dev_guide/testing.html
- phantomjs - Fixed by `apt-get install phantomjs`
- perceptiondiff - Fixed by `apt-get install perceptiondiff`
- Download the sampledata.
- A few python modules.
  - ggplot
  - flexx
  - icalendar
  - mock
  - These should be added to the list of packages required for testing, or we should just say `pip install -r requirements.txt`.

Let me know if there are better ways to detail these instructions.

thanks,
Dennis

**Comment by birdsarah** [comment]
I added some information about this in a recent PR (https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/dev_guide/testing.rst). But still a lot more can be added - thanks for posting @dennisobrien

**Comment by bryevdv** [comment]
Setup and testing docs have been streamlined and improved.
