### ISSUE TITLE
Button Read is Slow In Bokeh Server

### ISSUE THREAD

**Issue by redraven984** [bokeh/bokeh#4053]
Hi All,

I recently discussed this issue in the Bokeh User Group. It appears that the button implementation in Bokeh is not capable of capturing button clicks when the update speed in the Bokeh Server is too fast. To give a concrete example, here is some sample code:

====================== Sample Code ==========================================
```
def update():
             print " Button Group State: " +str(button_group.active)

button_group = RadioButtonGroup( labels=["State 1", "State 2"], active=0)

# open a session to keep our local document in sync with server
session = push_session(curdoc())
curdoc().add_root(button_group)
curdoc().add_periodic_callback(update, 50)

session.show() # open the document in a browser
session.loop_until_closed() # run forever
```
==============================================================================

It appears that the active state switch will register if the callback update time is > 250ms (im sure this is computer dependent).

Things I have tried to remedy the problem:
1. Run slower - this working but is just not feasible in my application. I need to be running at 50ms or faster to keep ahead of a real time process.
2. Multithreading - Assign a new thread to the callback function. This does not seem to have any effect. 
3. Writing a handler function to be called "on_click". This function suffers from the same problem as just querying the active state.

Also the discussion topics that I started in the user group are here:
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/i23r_HhdWJU

and

https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/4ot4FHeOUPI

Thanks for your help. I am willing to experiment and help in developing a new fix for this issue.

**Comment by bryevdv** [comment]
I don't remember if I already mentioned but using the client API instead of a Bokeh App directly in the server is going to be at least double the overhead. It's twice as many network hops, JSON encoding/decodings, etc. I tried the following as a pure server Bokeh app (i.e., run with `bokeh serve --show foo.py`) and it did not seem to have any trouble keeping up w 50ms update
```
from bokeh.models.widgets import RadioButtonGroup
from bokeh.io import curdoc

def update():
    print(" Button Group State: " +str(button_group.active))

button_group = RadioButtonGroup( labels=["State 1", "State 2"], active=0)

curdoc().add_root(button_group)
curdoc().add_periodic_callback(update, 50)
```
There may not be much we can do to mitigate things in the client API case.

**Comment by bryevdv** [comment]
Just to check tho, @havocp there's not any explicit throttlng in the server anywhere?

**Comment by bryevdv** [comment]
Here's a little more involved test:
```
from bokeh.models.widgets import RadioButtonGroup
from bokeh.io import curdoc
import time

active = None
start = None
count = 0
last = None

def update():
    global active
    global start
    global count
    global last
    if start is None:
        start = time.time()
    else:
        count += 1
    now = time.time()
    if button_group.active != active:
        print(" Button Group State: " + str(button_group.active))
        print(" Callback time: " + str((now - start)/count))
        if last is None:
            last = now
        else:
            print( "Last: " + str(now - last))
            last = now
        active = button_group.active

button_group = RadioButtonGroup( labels=["State 1", "State 2"], active=0)

curdoc().add_root(button_group)
curdoc().add_periodic_callback(update, 10)
```
It's a bit hard to switch buttons quickly by hand with a mouse, but when I do try I see results like:
```
 Button Group State: 0
 Callback time: 0.011399769138051222
Last: 0.21723604202270508
```
Indicating that:
* the cb is executing about every 10ms
* 21 ms is an upper bound on update registering time

**Comment by bryevdv** [comment]
made the callback a little more efficient: 
```
from bokeh.models.widgets import RadioButtonGroup
from bokeh.io import curdoc
from time import time

active = None
last = None

def update():
    global active
    global last
    now = time()
    if button_group.active != active:
        print(" Button Group State: " + str(button_group.active))
        if last is None:
            last = now
        else:
            print( " Last: " + str(now - last))
            last = now
        active = button_group.active

button_group = RadioButtonGroup( labels=["State 1", "State 2"], active=0)

curdoc().add_root(button_group)
curdoc().add_periodic_callback(update, 10)
```
and got down to:
```
 Button Group State: 1
 Last: 0.14563703536987305
```

**Comment by bryevdv** [comment]
with a single plain button and `on_click` handlers:
```
from bokeh.models.widgets import Button
from bokeh.io import curdoc
from time import time

last = time()

def update():
    global last
    now = time()
    print(now - last)
    last = now

button = Button()
button.on_click(update)

curdoc().add_root(button)
```
I can get down to:
```

0.05761289596557617
```
I can't physically click any faster, and every click apparently has "immediate" (in terms of my human  perception) line printed (i.e. none are skipped or dropped).

I'm not sure it's going to be possible to do much better. Our design goals never had anything like hard real time requirements in mind. The priorities were ease of use while keeping in "human UX" timescales.

**Comment by redraven984** [comment]
Hi Bryan,

This is an interesting solution. I think what you are suggesting is removing the session commands. However, the second part of my application is to plot the data I am observing.

so the update function has something like this in it:

def update():

    // Read data
    data = callToDataStore(location)
    // Create new data column source
    newData = dict()

    // Now check radio button
    if button_group.active != 0:
         // now push up the new data
          source.stream(newData,100)


Can I have a real time plot without calling the Client API?

**Comment by bryevdv** [comment]
Actually can you clarify this:

> It appears that the active state switch will register if the callback update time is > 250ms (im sure this is computer dependent).

When I your code above with 50ms, I see all the state changes. are you saying they do not happen at all for you?

**Comment by bryevdv** [comment]
> Can I have a real time plot without calling the Client API?
That question is pretty broad, I'm not quite sure what you are asking. Perhap this example would be instructive:

https://github.com/bokeh/bokeh/tree/master/examples/app/ohlc

**Comment by redraven984** [comment]
I added a statement to my update function: print "Active button state is " + str(radioButtonGroup.active)

I observed that when the callback time is < 250ms it takes several seconds of updates to register the active state. The faster the callback, the longer it took. Above 250ms the change in active state is immediately printed.

**Comment by bryevdv** [comment]
It's updating visually instantaneously for me even if I put 10ms. What platform are you on?

**Comment by bryevdv** [comment]
Also is this across an actual network, or locally running?

**Comment by redraven984** [comment]
The server is running locally on a Windows 8 x64 machine. The processor is an i7 with 32 GB of RAM.

Is it possible that my version of Bokeh is already outdated? I have been using the streaming plot example (i think you sent it to me some time ago). If I comment out the client code, no Bokeh does not open up in my browser.

**Comment by bryevdv** [comment]
This is what I see, even with the client API, with 10ms cb time, ~8 updates in 5s, certainly not multiple seconds per update
![ezgif com-crop](https://cloud.githubusercontent.com/assets/1078448/13965464/619980d4-f03c-11e5-9f30-fc4f760551b7.gif)

>  If I comment out the client code, no Bokeh does not open up in my browser.

are you running it with `bokeh serve foo.py` ? You don't run it as a normal python script, you have to run it with the bokeh server.

**Comment by redraven984** [comment]
I am running it as bokeh serve foo.py. Although its interesting to note that if you have a server running in a command window, you can run the scripts from pycharm as normally and the interface will show up.

**Comment by bryevdv** [comment]
you have to add `--show` for a window to open up automatically

**Comment by redraven984** [comment]
Even with the show option it does not change anything. Let me see if I can pare down my application so I can post sample code.

**Comment by bryevdv** [comment]
What happens if you run the code I put above? Nothing substantial has changed wrt to server or usage since `0.11` some new things were added or made (optionally) easier

**Comment by redraven984** [comment]
Hi Bryan,

Here is my code pared down. Its obviously simplified because I cant share the exact application here:

import numpy as np
import ujson as json
from bokeh.client import push_session
from bokeh.driving import count
from bokeh.plotting import figure, curdoc, vplot, hplot
from bokeh.models import ColumnDataSource,Button
from bokeh.models.widgets import RadioButtonGroup, TextInput, Dropdown
from bokeh.io import gridplot
import gc

@count()
def update(t):
    data_service = #Connect to Data Service - No latency here, has been extensively tested
    print "radio button state is " + str(button_group.active)

    msg = receive data
    line_out = msg.body

    if line_out.find('{')!= -1:
        
      indx = line_out.index('{')
        final_index = line_out.index('}')

        parsed_json = json.loads(line_out[indx:final_index+1])

        # Prepopulate the new data column data source so that all cols stay the same
        newData = dict(time=[t], foo=[foo[-1]])

        if parsed_json['name']=='Foo':

            print parsed_json['name'] + " at " + parsed_json['curr.time']

            # Update the dashboard
            newData['foo'] = [float(parsed_json['value'])]

        source.stream(newData,100)

        # enable garbage collection
        gc.collect()

    else:
        pass


# Create the data column source
source = ColumnDataSource(dict(
    time=np.zeros(100), foo=np.zeros(100)))


# Set up the plots that will run in the dashboard
p_foo = figure(plot_width=250,plot_height=250,
                title_text_font_size='8pt',  toolbar_location=None)
p_foo.outline_line_color = "navy"
p_foo.outline_line_width = 7
p_foo.outline_line_alpha = 0.3
p_foo.background_fill_color = 'white'
p_foo.outline_line_color = None
p_foo.grid.grid_line_color = None
fooLine = p_foo.line(x='time', y='foo',color='navy', line_width=4, source=source)

button_group = RadioButtonGroup(
        labels=["State 0", "State 1"], active=0)


curdoc().add_root(p_foo)
curdoc().add_periodic_callback(update, 50)

**Comment by redraven984** [comment]
Let me try to run your code.

**Comment by bryevdv** [comment]
oh, well that's not runnable as-is, if I comment most everything out of `update` it opens a browser tab with  an empty plot.

**Comment by bryevdv** [comment]
Here is what I am running, streaming plot is updating immediately:
```
import numpy as np
import ujson as json
from bokeh.client import push_session
from bokeh.driving import count
from bokeh.plotting import figure, curdoc, vplot, hplot
from bokeh.models import ColumnDataSource,Button
from bokeh.models.widgets import RadioButtonGroup, TextInput, Dropdown
from bokeh.io import gridplot
from random import random
import gc

@count()
def update(t):
    print("radio button state is " + str(button_group.active))

    newData = dict(time=[t], foo=[random() + int(button_group.active)])
    source.stream(newData,100)

    gc.collect()



# Create the data column source
source = ColumnDataSource(dict(
    time=np.zeros(100), foo=np.zeros(100)))


# Set up the plots that will run in the dashboard
p_foo = figure(plot_width=250,plot_height=250,
                title_text_font_size='8pt',  toolbar_location=None)
p_foo.outline_line_color = "navy"
p_foo.outline_line_width = 7
p_foo.outline_line_alpha = 0.3
p_foo.background_fill_color = 'white'
p_foo.outline_line_color = None
p_foo.grid.grid_line_color = None
fooLine = p_foo.line(x='time', y='foo',color='navy', line_width=4, source=source)

button_group = RadioButtonGroup(
        labels=["State 0", "State 1"], active=0)


curdoc().add_root(hplot(button_group, p_foo))
curdoc().add_periodic_callback(update, 50)
```

**Comment by bryevdv** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1078448/13967655/6ad0358a-f046-11e5-8947-f2508e6219d0.gif)

**Comment by bryevdv** [comment]
well ok that looks pretty crappy after gif encoding but hopefully gives an idea, the delay is not on a human-perceptible time scale when I run it locally on this machine. Perhaps there is a windows performance issue?

**Comment by redraven984** [comment]
runs well for me too. Now I am really confused.

**Comment by bryevdv** [comment]
unrelated: it seems confusing/suboptimal that the button hover and pressed/selected are basically identical

**Comment by redraven984** [comment]
I timed the data download, the button state now works. We worked on using streaming plots. There isnt anything else.

**Comment by redraven984** [comment]
really? Well this is not a problem for me but I know at least a two people that are interested in the hover functionality. it could be confusing to them.

**Comment by bryevdv** [comment]
I just mean when you hover on top of the unselected button, it basically looks like the selected button. I think they should be visually different

**Comment by bryevdv** [comment]
Ok if I change cb time to 20 ms I do start to see a delay.

**Comment by redraven984** [comment]
My dashboard has 8 plots and 9 text input boxes. It could be that I see the effect at slower update speeds simply because there is very little in the test case?

Separately, did you change the commands that address the interface in my pared down script?
curdoc().add_root(hplot(button_group, p_foo))
curdoc().add_periodic_callback(update, 50)

I dont understand why it doesnt work in my code but it works fine in yours.

**Comment by bryevdv** [comment]
So you are streaming to 8 completely separate plots (i.e. different canvases)? How many points per plot, how big are the canvases?

**Comment by bryevdv** [comment]
you can try setting the environment variable `BOKEH_LOG_LEVEL=debug` to get some information in the browser console about how long setting data and rendering takes on your browser. I would not run it for long, it is very chatty output.

**Comment by redraven984** [comment]
Hi bryan,

I am running 8 completely separate canvases. 6 of them are 250x250 (HxW) and 2 of them are 400x400. All plots are updated in a streaming fashion as the data is observed.

I will try out the environmental variable. Can I just set this in my *.py script?

**Comment by bryevdv** [comment]
Probably, I've never tried. I set it on the command line usually.

**Comment by redraven984** [comment]
Hi Bryan,

I am trying to invoke the logging you suggested yesterday. Using the documentation I found that invoking the command requires something like this:
BOKEH_DEV=true bokeh serve example.py
or
BOKEH_LOG_LEVEL=debug bokeh serve example.py

However, neither of these work. I get the following message:
"'BOKEH_DEV' is not recognized as an internal or external command,
operable program or batch file."

Also, removing the session commands from my file leads to no dashboard on screen. In essence if I dont use the API there is no canvases created on screen and no update loop.

**Comment by havocp** [comment]
Setting the env var that way is unix shell syntax - the error message you give there is from Windows I believe. On Windows I think you can run a separate command like `SET BOKEH_LOG_LEVEL=debug` and then run the bokeh server. There may be other ways, I'm not a Windows expert by any means.

**Comment by redraven984** [comment]
The command you suggested did not give me an error. However, the server output is not changed.

**Comment by bryevdv** [comment]
After running with the env var set, the output is in the browser Javascript console, not the server output. That turns on logging in the client (the browser). 

> Also, removing the session commands from my file leads to no dashboard on screen. In essence if I dont use the API there is no canvases created on screen and no update loop. 

Server apps definitely don't need them (none of the hosted example on the demo site use them, for instance). The `session` stuff is only needed when updating to the server from a *separate* python process (connecting to the server from python is in fact the only purpose of session objects). Unfortunately I can't really say offer more concrete.

**Comment by redraven984** [comment]
Bryan, thanks for that explanation. Running the debug I find that there is some form of unhandled exception: 
Here is an example, although the hash varies: Bokeh: Unhandled OK reply to CD8339F56FDE4F39B20F453198478137

**Comment by bryevdv** [comment]
@redraven984 that message is harmless.  There is an open PR to improve server performance of streaming, I don't know if it will affect this issue, but it's worth keeping any eye on. It should be merged soon, with a new dev build out next week.

**Comment by bryevdv** [comment]
just checking in, @redraven984 have you had a chance to try the potential improvement in a dev build? otherwise the next release is out tomorow

**Comment by bryevdv** [comment]
@redraven984 FYI `0.12` is now out

**Comment by bryevdv** [comment]
closing for lack of update
