### ISSUE TITLE
Calling add_timeout_callback twice removes first callback

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#4054]
In code like the following:

```python
doc = curdoc()

doc.add_next_tick_callback(f)
doc.add_next_tick_callback(g)
```

It appears that only `g` gets called and `f` gets forgotten.  Is this expected?

cc @havocp

**Comment by havocp** [comment]
No, not expected by me at least. Unless f and g are the same function, then maybe.

**Comment by havocp** [comment]
One thing to investigate first here could be whether the second callback is actually _removed_ (is it still in our set of callbacks) or simply not _called_ (perhaps a "scheduling" problem where it's still there but gets starved). A test case as mentioned on chat would be helpful.

**Comment by mrocklin** [comment]
This issue also persists with multiple `add_periodic_callback` calls:

### add_next_tick_callback

```python
curdoc().add_next_tick_callback(lambda: print('hello'))
curdoc().add_next_tick_callback(lambda: print('world!'))

world!
```

### add_periodic_callback
```python
curdoc.add_periodic_callback(lambda: print('hello'), 100)
curdoc.add_periodic_callback(lambda: print('world!'), 100)

hello
hello
hello
hello
world!
hello
hello
hello
hello
world!
```

### My temporary solution:
```python
curdoc.add_periodic_callback(lambda: print('hello'), 99)
curdoc.add_periodic_callback(lambda: print('world!'), 100)

hello
world!
hello
world!
hello
world!
```

**Comment by havocp** [comment]
that periodic thing is deeply weird, I gotta say.

I don't see how we could be breaking tornado in this way :-/ we wrap the stuff a little bit but I don't see how it could result in running one of the periodics only 1/5 as much as the other when they have the same interval. Anyway. Obviously needs debugging.

**Comment by mrocklin** [comment]
This was likely due to issues in my code.  Closing for now.  I'll reopen with a minimal example if it pops up again.
