### ISSUE TITLE
Request: reorderable legends with chart API

### ISSUE THREAD

**Issue by msarahan** [bokeh/bokeh#4057]
I have plots like:

![screen shot 2016-03-22 at 11 14 52](https://cloud.githubusercontent.com/assets/38393/13998254/30f14a34-f104-11e5-9f22-c18060f315a2.png)

Unfortunately, the legend entries are in the opposite order of the content of the plot.  I can't flip around my columns because of assumptions I make in creating the area chart (negative data should be on the left of any input data frame.)  Code for that is at https://github.com/msarahan/bokeh/commit/c1dda0f2861355ab2189f6b7e8b2d1da2751b7f9

If legend entries were reorderable somehow, so that I could either flip the collection around, or arbitrarily order it by passing a list of keys, that would be very helpful.

**Comment by fpliger** [comment]
@msarahan [this branch ](https://github.com/bokeh/bokeh/tree/hotfix/charts_sort_legend_fix ) should fix legends ordering bug that prevented reversed ordering. Is this what you were looking for?

**Comment by msarahan** [comment]
Yes, I think that fixes this issue.  I have moved the code over to the
plotting API so that I get handles to the renderers more directly, but I
still appreciate this fix.

**Comment by fpliger** [comment]
Cool. I'll try to add the tests for that use case and get a PR ready this weekend. :+1:
