### ISSUE TITLE
When used with `stat=None`, `HeatMap` modifies original DataFrame

### ISSUE THREAD

**Issue by jat255** [bokeh/bokeh#4075]
As described in the title. When called with `stat=None`, the dataframe provided to `HeatMap` is modified. This should not happen.

See [this gist](https://gist.github.com/jat255/71daf4d3711e1d62127c) for a demonstration. The dataframe used in the notebook is available here: [dataframe.zip](https://github.com/bokeh/bokeh/files/192097/dataframe.zip)

```
$ bokeh info                                                                                                                                        [12:38:32] Python version      :  3.5.1 (default, Mar 20 2016, 19:11:32)
IPython version     :  4.1.2
Bokeh version       :  0.11.1
BokehJS static path :  /usr/local/lib/python3.5/site-packages/bokeh/server/static
```

**Comment by bryevdv** [comment]
ping @brendancol @fpliger this issue seems familiar, wasn't this already fixed in master?

**Comment by bryevdv** [comment]
Yes this appears to have been fixed in https://github.com/bokeh/bokeh/pull/3909 so closing. Please re-open if you continue to see issue in future dev builds or releases.
