### ISSUE TITLE
In Developer Guide, it's not obvious that "following pages" are indexed in the sidebar on the left

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#4076]
In http://bokeh.pydata.org/en/latest/docs/dev_guide.html#bokehjs there is this text:

    Hopefully, you will find all the information you need in the following pages. 

However, there is no additional pages after the text, so it just looks like the docs are blank.  Rather, the sidebar on the left contains the index, and it's not obvious that this is where people should look.  So, either we should rephrase the text to say "the sidebar on the left", or somehow we duplicate the index in the text body itself.

**Comment by waseem18** [comment]
Hello @pzwang I would like to work on this.
