### ISSUE TITLE
Preview/Save Widget on wrong layer

### ISSUE THREAD

**Issue by WhereIsMySnake** [bokeh/bokeh#4081]
On Docs side when selecting Preview/Save Widget od plot preview is hidden behind text (probably wrong z-index).
Link:
http://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html

**Comment by bryevdv** [comment]
That's really bizarre. @birdsarah any ideas? AFAIK nothing about the `z-order` of the preview save tool has changed, by maybe the new docs site CS has some interaction?

**Comment by almarklein** [comment]
Could this be related to #4058?

**Comment by almarklein** [comment]
Did some testing, and I looks like #4167 fixes this.

If I build the docs locally, the CSS is broken for some reason, so I tested by manipulating the DOM of the pydata docs using the browser dev tools

**Comment by bryevdv** [comment]
Getting rid of the modal entirely.
