### ISSUE TITLE
Unclear how to run bokeh command when exe not available

### ISSUE THREAD

**Issue by mdk73** [bokeh/bokeh#4092]
*Original title: bokeh serve: entry point with `if __name__ = '__main__':`*

I work with a standard python installation (not anaconda) on Windows 10, bokeh is installed with pip.

The standard way to start the bokeh server with 'bokeh serve' is not working:
The script 'serve' is not executed. The line 

```python
#!C:\Python34\python.exe
```

is not recognized. Windows asks, which app should be used to open the file...

The following modification of the file 'serve' worked for me:

```python
#!C:\Python34\python.exe
if __name__ = '__main__:
    import sys
    from bokeh.command.bootstrap import mainmain(sys.argv)_
```

On windows the script can now be invoked with:

```python
python -m bokeh serve
```

On Linux the standard way and the way described above should both work (though I can not test).

Additonally the server can be started from any python script, it is no longer necessary to start the server manually from a terminal:

```python
import subprocess
import time    # optionally, might be useful to give the server time to initialize
args = ['python', '-m', 'bokeh', 'serve']
p = subprocess.Popen(args) 

# optional delay for x seconds to give the server time to initialize
time.sleep(1)
```

I suggest 

1. to change the file 'serve' and use 'if __name__ ...' as shown above. 

2. to add the additional way to start the server with 'python -m bokeh serve' to the documentation.

**Comment by almarklein** [comment]
`python -m bokeh serve` should work regardless of the contents of the `serve` script. The `-m` flag means to "run" a module, in this case Bokeh, and will run the `__main__.py` in the bokeh package.

**Comment by almarklein** [comment]
Also, there is no script "serve", there should only be a script "bokeh".

**Comment by mdk73** [comment]
The file "serve" is in my installation located in 
C:\Python34\Scripts

But I am a bit confused now: I tried to change the script back to the original state to reproduce the windows message (which App should be used to open 'serve'...), but the bokeh server was starting cleanly.
So I am not able to reproduce the error, I should have copied the file before modifying it. My fault...

**Comment by almarklein** [comment]
That's what I meant; using `python -m bokeh` solved the issue. The changing of the `serve` script should not have any effect. In fact, I don't think Bokeh puts a file called `serve` in your environment. `serve` is a *subcommand* of the `bokeh` script/command.

**Comment by mdk73** [comment]
In an attemt to run a testscript for #4096 I could reproduce the problems I had when I was initially reporting this issue:

First attemt, from any directory:
```
PS C:\Users\mdk\Desktop\testscripts> bokeh serve .\foo.py
bokeh : Die Benennung "bokeh" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines
ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern
enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ bokeh serve .\foo.py
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (bokeh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Then I move to 
![image](https://cloud.githubusercontent.com/assets/2737768/14409487/d09ba390-ff14-11e5-8db6-0c1e87af6f00.png)
where a script 'bokeh' is located.

```
PS C:\Python34\Scripts> .\bokeh serve .\foo.py
```

gives me this popup-message:
![image](https://cloud.githubusercontent.com/assets/2737768/14409495/15a45e96-ff15-11e5-8ac1-eb49ad7209e8.png)

I choose 'Internet Explorer' and get
![image](https://cloud.githubusercontent.com/assets/2737768/14409507/4e26c786-ff15-11e5-8fdc-b82cd084c16c.png)

**Comment by almarklein** [comment]
@mdk73 Right. The points is that the `bokeh` script is written without extension, leaving Windows clueless on how to open the file (thus it asks you). On Linux, one can provide a shebang at the beginning of a file, but this does not do anything on Windows.

**Comment by jhdedrick** [comment]
Could someone point me toward the documentation of what's necessary to get a bokeh server running under Windows?  The documentation I can find still just blithely advises "bokeh serve --show myapp.py", with no further explanation.

**Comment by bryevdv** [comment]
@jhdedrick I'm not sure what you re asking, that's literally all you have to do to run locally:

<img width="1554" alt="screen shot 2018-02-21 at 11 10 47" src="https://user-images.githubusercontent.com/1078448/36500049-01aee864-16f8-11e8-8bf4-0ea7861fd010.png">

Perhaps you can clarify your question.
