### ISSUE TITLE
Fix phantomjs download failures

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4099]
Our travis CI tests are pretty much useless right now due to a trivial failure. Based on quick research we just have to provide our own download URL that can be configured through an env variable (see http://npmjs.com/package/phantomjs for details). I think we should just have to upload phantomjs binary (in correct version) to our S3 and change `.travis.yml` accordingly. Note that `npm install` is called in `conda.recipe/build.sh`, but I think changing `.travis.yml` is the right thing to do. If there other other ideas, please speak up, or preferably submit a PR.

**Comment by canavandl** [comment]
Here's a discussion of the issue on their GH: https://github.com/ariya/phantomjs/issues/13953

**Comment by canavandl** [comment]
it appears that Medium maintains a fork of phantomjs (now phantomjs-prebuilt post-2.0 release) that is hosted using Github Releases (not Bitbucket). I'll investigate to see if it works. It'd be nice to not have to maintain our own binary.

**Comment by bryevdv** [comment]
@mattpap seems to be better with #4123 please re-open if problems surface again.

**Comment by mattpap** [comment]
@bryevdv, updating phantomjs to 2.0+ version is obviously a way better solution. I just hope someone actually inspected test reports in that PR, to make sure that our testing framework still works. We should also investigate if they actually updated webkit to a reasonably modern version and e.g. remove typed array hack from `main.coffee` (@canavandl, if time permits, can you do this as well?).

**Comment by bryevdv** [comment]
All of the file examples report "no diff":

https://s3.amazonaws.com/bokeh-travis/121254034/examples.html

but notebook examples do appear to have an issue, e.g.:

https://s3.amazonaws.com/bokeh-travis/0.12.0dev6-f151f99/howto/charts/boxplot.png

**Comment by mattpap** [comment]
> All of the file examples report "no diff":

I also don't see any images (besides notebooks). I doubt that's intentional. Also, it may have been broken earlier.

**Comment by mattpap** [comment]
> e.g. remove typed array hack from main.coffee

I did this in #4141.
