### ISSUE TITLE
Plot resizing is broken

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4110]
In particular the example `embed_responsive_width_height.py`. This also breaks our phosphor+Bokeh demo.
In v0.11.1, the DOM looks like:
```
<div class='bk-plot'>  <-- this is what @el refers to
  <div class='bk-plot-wrapper'>
       <table> ... etc.
```

In master, the DOM looks like:
```
<div class='bk-root'>
    <div>  <-- this is what @el refers to
        <div class='bk-plot-wrapper'>
             <table> ... etc.
```

To resize, the plot queries the `clientWidth`and `clientHeight` of the parent node of its element. But this now fails, because of the extra layer.

As for a solution, I tried two things that both seem to work:
* Use the client size of `@el.parentNode.parentNode`. Or maybe safer: traverse upwards until meeting a node that is `bk-root`.
* Use client size of `@el.parentNode`, but set the CSS `height`of the `bk-root` to 100%.

Tasks:
* [x] @birdsarah @mattpap is that `<div>` intended? --> Yes
* [ ] Maybe not crucial for this issue, but somewhat related: there are still references to bk-plot in the code, was that supposed to be removed, or should the classless div above be a `bk-plot`
* [x] Fix the issue.
* [x] Selenium test to avoid having another regression like this (working on it)
* [x] Shortcut to allow (Phosphor) to set the width height to specific values, to avoid a DOM measurement.
* [x] Typing for `plot.resize_width_height()`

**Comment by mattpap** [comment]
This extra `<div>` comes from the fact that there are multiple code paths for adding rendered view to the DOM, depending on situation: static document (append), session (replace), static model (replace).

**Comment by mattpap** [comment]
Giving this another thought, this `<div>` must have always been there. `PlotView` is rendered with `@$el.html(@template())`, so there is an intrinsic wrapper `<div>`.

**Comment by almarklein** [comment]
I tried 0.11.1 and I got the DOM that I listed above.

**Comment by mattpap** [comment]
@almarklein, so you have to get parent of `bk-root`. But then, at least for responsive plots, we have to assume that there is one plot per `bk-root`.

**Comment by almarklein** [comment]
@mattpap yes, I think its best to stick with the original approach and get the parent of `bk-root`, but indeed we need to either assume or check that it is not a "sub-plot".

**Comment by almarklein** [comment]
@mattpap any idea of the spurious `bk-plot` references, or whether that classless div should be a `bk-plot`?
