### ISSUE TITLE
Release 0.12 Planning

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4126]
This Epic collects remaining work that must be completed for a `0.12` release.

**Comment by damianavila** [comment]
Nice, let's see how this Epic thing work out!

**Comment by damianavila** [comment]
FYI, from people not using the zenhub extension, they see this just like an issue with a normal Epic label... let's see later how things are shown when we add issues to the Epic...

**Comment by bryevdv** [comment]
@bokeh/dev OK I have added all the existing `0.12` milestone issues to this epic. I will make a quick stab at estimating some of the issues, and we can refine them all at the meeting friday.

**Comment by bryevdv** [comment]
@bokeh/dev I propose we use https://www.pointingpoker.com/ which is free and simple to help facilitate the planning meeting. Thoughts?

**Comment by bryevdv** [comment]
Closing this pre-release.
