### ISSUE TITLE
Charts documentation improvements

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#4140]
Charts documentation need improvements, especially regarding charts shared arguments and attributes. For instance, it's not easy to find information about charts legends on the user guide and the only mention to this parameter is on the Scatter Chart section, although it is a generic argument that can be used on any type of chart.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/14)
