### ISSUE TITLE
Strict trigger() and listenTo()

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4153]
Make `trigger()` and `listenTo()` verify if properties used are actually defined on the target object's model. This is continuation of #4141.

**Comment by mattpap** [comment]
I think that it's infeasible to fix this as-is. We won't get proper level safety anyway and investing time into this weak design is not worth the time. I would prefer to implement a proper signal, slot framework from ground up in TypeScript.

**Comment by bryevdv** [comment]
@mattpap so this can be closed?

**Comment by mattpap** [comment]
I will close this when new signaling API is on board, which I'm working currently on.
