### ISSUE TITLE
No text_font_size option for DataTable

### ISSUE THREAD

**Issue by warren-oneill** [bokeh/bokeh#4165]
How can I edit the size of text in the ```DataTable```? Unfortunately I can't pass ```text_font_size``` as in other classes.

**Comment by bryevdv** [comment]
Hi @warren-oneill General support questions should go to the mailing list, there is a wider audience of people who can potentially answer, and it helps us keep our tracker clear for issues and bugs. To answer your question, however, you probably want to look at using the HTML cell formatter:

http://bokeh.pydata.org/en/latest/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.HTMLTemplateFormatter
