### ISSUE TITLE
Lasso tool is unusable with large data and inconsistent with box select

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4172]
Lasso tool should only draw selection boundary during mouse activity and select data only when mouse gesture is over. This is what box select tool does. With the current behavior, it's close to impossible to use the tool with large data (e.g. try `plotting/file/color_scatter.py`). What I propose it to unify lasso tool's behavior with box select. Additionally we can have the current behavior of lasso tool added to box select under `realtime` option (default `False`). I'm not sure if we need both (maybe for small data it makes sense).

**Comment by mattpap** [comment]
Too lazy to actually check that both lasso and box select tools already have this option. Why do they have different defaults?

**Comment by mattpap** [comment]
Furthermore lasso select tool constantly renders anyway even if `select_every_mousemove` is set to `False`. This is because we mix annotations and overlays together and/or are not careful enough when dealing with events.

**Comment by bryevdv** [comment]
> Why do they have different defaults? 

No actual discussion was had or decision was made. It usually shows nicely with the current default, but I'm not opposed to changing it, either.

> Furthermore lasso select tool constantly renders anyway even if select_every_mousemove is set to False. This is because we mix annotations and overlays together and/or are not careful enough when dealing with events.

I don't understand why this is surprising? The overlay is drawn on the canvas, it has to trigger a re-render. I inferred from the issue that the problem was the cost/overhead of selection, not necessarily of the drawing. Is that correct, or not?

**Comment by bryevdv** [comment]
Unless you are proposing a second transparent canvas on top just to render overlays onto.  Which might be a useful optimization but is not trivial and would need some benchmarking to prove

**Comment by bryevdv** [comment]
The recent work to remove the duplicate extra renders seems to have qualitatively improved performance for me. On a 3yo MBP with Safari, the `color_scatter.py` example responds instantaneously as a lasso selection is made. I am moving this back into `short-term`

**Comment by bryevdv** [comment]
After two years, I am going to close this with no action. I am not inclined to change the defaults, and if people need to tweak things for performance on a specific set of data, they can.
