### ISSUE TITLE
session.show() shows blank page with example on version 0.12.0dev6

### ISSUE THREAD

**Issue by copperwire** [bokeh/bokeh#4175]
Using the [line_animate](https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/line_animate.py) provided opens a new blank tab with address `http://localhost:5006/?bokeh-session-id=bpBiwoKoMYGc1i2rrrjtxKS4FocTbW6UZn2vu5eNdmj0`

In the terminal the following error is printed : 
` [2558:2558:0414/173812:ERROR:CONSOLE(8)] "Uncaught Error: Script error for: google-analytics-bundle
http://requirejs.org/docs/errors.html#scripterror", source: chrome-extension://kgifkabikplflflabkllnpidlbjjpgbp/static/js/require.js (8)
`

**Comment by bryevdv** [comment]
I just tried this on `master` which is only a commit or two ahead of `0.12dev6` and it is working as expected. The above error makes me think there was a problem loading some script from CDN, are you certain there were not network issues on the machine you were testing on? Did you run the `bokeh serve` before running `line_animate.py` as described in the `README`?

**Comment by copperwire** [comment]
It turns out the error was related to the bokeh server as well as the problem. I assume they both come from the fact that a `bokeh serve` command had persisted through a system suspend.

**Comment by bryevdv** [comment]
I'm not sure I understand the scenario exactly. I am going to close this since you seem to have resolved things, but if you have time to provide a more detailed timeline of what exactly happened / what you ran, it might help us make the server more robust in the future.

**Comment by copperwire** [comment]
I'll do just that! 

A bokeh serve command had been running for  most of the day on my laptop which had been suspended twice during the day. 
I erroneously updated the `bokeh` package while the server was running from `0.12.0dev5` to `0.12.0dev5`. After which the server did not display the example. After a reboot and restarting the bokeh server the example works as expected.

**Comment by bryevdv** [comment]
Ah I see, yes that might cause problems. Towards `1.0` we do intend to offer much stricter guarantees around version compatibility but we are not quite there yet. Things often do work between versions, but we are currently in the middle of some BokehJS refactoring. This is why Bokeh server apps (`bokeh serve app.py`) serve the specific version of BokehJS themselves.

**Comment by bryevdv** [comment]
Also, thanks for the feedback!

**Comment by copperwire** [comment]
No problem! I'm writing a program for a research group using bokeh as the backbone. 

I'd love to contribute to the development if you've got a place to start?

**Comment by bryevdv** [comment]
As a matter of fact there is a `starter` tag! 

https://github.com/bokeh/bokeh/issues?q=is%3Aopen+is%3Aissue+label%3A%22tag%3A+starter%22

These are not necessarily trivial tasks, but they should be fairly self-contained.
