### ISSUE TITLE
Set default width and height for Markup widgets to None

### ISSUE THREAD

**Issue by justacec** [bokeh/bokeh#4180]
Currently, the Markup widgets use a default width and height of several hundred pixels.  I recommend that we change that to None by default which will not transmit any width or height cues to the browser.  The user can still use the properties if he or she wants, they would just by default be set to auto in the HTML.  I think this would be the expected behavior from the end users perspective.

**Comment by bryevdv** [comment]
This appears to have been done, as best as I can tell, @birdsarah can you confirm?
