### ISSUE TITLE
Add ability to reset bokeh.driving decorators to initial value

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#4182]
When building a server app and using the `bokeh.driving` decorators, I found wanted to be able to reset the decorator value back to the first value.  

Example:

```python

def on_select_box_change(attr, old, new):

    # restart from beginning
    reset_counter()

@count()
def increment_timeseries(c):
    ...

curdoc().add_periodic_callback(increment_timeseries, 1000)

```

**Comment by bryevdv** [comment]
> reset_counter()

which one?

Unfortunately all ways I can think that this might be done (callable objects as decorators, extra parameters the callback has to take, implicit global state) are all pretty bad. I'd be -1 on any of those.  I think if you need this kind of control, you can just use the `global` explicitly. Maybe there are other ways to accomplish this that I have not thought of though.

**Comment by bryevdv** [comment]
@damianavila I definitely consider this a feature request (and I am inclined to close it actually). Does this point to a need for a distinction between "proposed" features, and "agreed to work on at some point" features? I feel like you are using "discussion" to capture the former, but I don't think that is very descriptive, and that there are other discussions besides proposed features.

**Comment by damianavila** [comment]
The line in the distinction is grey... but you are right about this one... it is a feature request and the discussion comes later...

**Comment by damianavila** [comment]
Now the problem with feature is that I need to put it in a milestone... and that will make the author think that we are accepting the request somehow... after somebody close it...

**Comment by bryevdv** [comment]
Thinking about it more, I am going to close it as `wontfix`. If someone can think of a reasonable way to do this (that isn't one of the crappy ways I mentioned above) we can reconsider.
