### ISSUE TITLE
Line Chart should use the index of the DataFrame or Series as the x values

### ISSUE THREAD

**Issue by dennisobrien** [bokeh/bokeh#4183]
From the mailing list:

When a Line Chart is passed a Pandas Dataframe, it creates a new index based on row offsets and uses this for the x values.  It would be nice if the existing index labels were used.

Example from Daniel Krause:

```
if __name__ == '__main__':
    from bokeh.io import show, output_file
    from bokeh.charts import Line
    import pandas

    # a test DataFrame
    d = {'a': [0,1,2,3]}
    index = [10,20,30,40]
    df = pandas.DataFrame(data=d, index=index)
    print(df)

    output_file('test.html')

    plot_w = 500
    plot_h = 300

    p = Line(df, 
              title="Test", 
              plot_width = plot_w, 
              plot_height = plot_h,
              )
    show(p)
```

![image](https://cloud.githubusercontent.com/assets/1168692/14595480/711ca668-04f4-11e6-8f5f-1ca43095f70f.png)

I tested and verified this with Bokeh 0.11.1.  The situation is similar with a Series that has an index.

It's possible to work around this issue by adding a column for the index, but it would be nice to avoid this.

```
p = Line(data=df.assign(x=df.index), x='x', y='a', title="Test", plot_width=500, plot_height=300)
```

**Comment by crashMOGWAI** [comment]
Seen this with the other dataframe source functions as well. Having to re-index everything generates a lot of overhead.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/55)
