### ISSUE TITLE
document "bokeh sampledata" better

### ISSUE THREAD

**Issue by davidszotten** [bokeh/bokeh#4187]
The readme notes that the bokeh sample data is required, but that doesn't seem to include the `movies.db` required by the movies sample app

**Comment by bryevdv** [comment]
It's part of the standard `bokeh.sampledata` package that has to be downloaded before it can be used. You can get either as described here:

http://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html#sample-data

Or in newer versions of Bokeh, just by executing `bokeh sampledata` at the command line.  

Note: I'm changing this issue to reflect that `bokeh sampledata` needs to be documented in the users guide.
