### ISSUE TITLE
Remove the Resize Tool?! 

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4196]
Speak now or forever hold you peace :D

The new layout work has some conflicts with the resize tool.

In the new layout work sizes are determined from the outside-in, rather than the inside-out. 

In the layout work, the resize tool will be removed from the set of default tools and it may be made no-op (at least for a while) to move things forward.

After some discussion with @bryevdv we thought it would be good to get some feedback on whether the resize tool is useful at all, and if so to describe the use cases so we can be thoughtful about adding it back in.

It may be, for example, that resize tool is useful on the outside layout box (which may contain one or many plots) so that everything inside resizes to fit that new user specified size.

**Comment by damianavila** [comment]
We should ask for feedback in the mailing list as well...

**Comment by bryevdv** [comment]
That seems reasonable.

**Comment by crashMOGWAI** [comment]
If you have smarter layout in the pipe, then toss the resize.

**Comment by birdsarah** [comment]
Thanks for the feedback @crashMOGWAI. 

Message posted to mailing list: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/s7NdG10rY2o

**Comment by bryevdv** [comment]
changing this to `task` there are some +1's and no -1's I think we can proceed. All examples have already had resize tool removed. Just need to remove the tool itself in a deprecatable way that just omits the tool and doesnt break anything.

**Comment by bryevdv** [comment]
@pzwang I think you have opinions here

**Comment by bryevdv** [comment]
Marking this for `0.12.7` to add a deprecation of some sort, and remove in `1.0` @pzwang last chance to voice a different opinion.

**Comment by jakirkham** [comment]
Guess I missed this discussion. 😞 Really liked using the Resize Tool and it unfortunately makes it more difficult to work with my data now that it is gone. Is there an alternative proposed?

**Comment by bryevdv** [comment]
The issue with the the old resize tool is that it worked on a single plot, which, if you've just got a single plot, is probably OK. If you have a plot in the middle 10 other plots and a bunch of widgets, all the sudden what to do when that one plot resizes in the middle of all that other stuff, possibly with their own sizing modes, is just a problem we can't solve. So, what are some things we are/could do?

1) Make sure `sizing_mode` works 100% reliably in a few most-common cases, e.g single plots, grid plots, "column of widgets next to a plot", etc. I think this is already almost true, for these simple cases

2) Make it possible to embed different Bokeh app roots individually in templates. Together with 1), this is the relief valve for people that need more control than quick and simple Bokeh layouts can provide

3) A new suggestion by @mattpap Add a new tool for resizing *layouts* as a whole. This skirts the problem described in 1) where there is a local tool on one plot, but a global layout. In the single plot case this reduces to essential the old resize tool behavior. In more complicated cases, it become something that can be reasoned about. I should add this would sort of already be possible with 2) e.g. if you put the components in a resizable phosphorjs layout or similar

**Comment by nleclercq** [comment]
I recently gave `sizing_mode` a try but it didn't work for me (blank display in Jupiterlab). For this test, I had a single plot per document per embedded server instance.

**Comment by bryevdv** [comment]
Well, Jupyter lab itself, and our support for it, are bleeding bleeding edge, so that will certainly be a process over time.

**Comment by pzwang** [comment]
I do think #3 would satisfy 100% of the need for the classic ResizeTool behavior.  I suspect that people make plots and they're just not big enough, and it's nicer to be able to resize rather than have to rebuild the plot programmatically with a bigger width and height.

**Comment by jakirkham** [comment]
That or we zoom into an area of a plot and then decide we want to make the plot bigger as well to inspect it more closely.

**Comment by nleclercq** [comment]
> Well, Jupyter lab itself, and our support for it, are bleeding bleeding edge...

I sympathise :-) Jupyterlab is like a totally new env. I spent the last days to retrieve the behavior myapp used to have under the classic notebook.

**Comment by apiszcz** [comment]
Checking in.
So the resize tool is gone from 1.0?
