### ISSUE TITLE
Pan tool gets into weird state when drag is released outside the plot

### ISSUE THREAD

**Issue by sccolbert** [bokeh/bokeh#4199]
Running the example here: http://bokeh.pydata.org/en/latest/docs/gallery/burtin.html
1. Select the pan tool.
2. Drag the plot and release the mouse _outside_ the plot area.
3. Try to drag the plot again from _inside_ the plot area.
4. Observe that drag is disabled, but the plot will move when the mouse is released.

Clicking and releasing within the plot area _without_ dragging, will reset the tool behavior.

Example:

![browser](https://cloud.githubusercontent.com/assets/137289/14691743/03179838-0721-11e6-8779-2ae89f6aea44.gif)

**Comment by bryevdv** [comment]
What browser / platform? I can't reproduce this on OS X on Chrome or Safari

**Comment by sccolbert** [comment]
Chrome 50 on Windows 10

**Comment by dwillmer** [comment]
I've just reproduced on Chrome 49 on OS X, but can't reproduce with Firefox.

**Comment by sccolbert** [comment]
I can also reproduce on IE 11 and Edge, but FF 44 works fine.

**Comment by bryevdv** [comment]
can no longer reproduce disabled drag on recent Edge or Crome on Win 10

**Comment by sccolbert** [comment]
👍 Fixed on IE11 too
