### ISSUE TITLE
Add the ComputedTransforms to the DataSpec System

### ISSUE THREAD

**Issue by justacec** [bokeh/bokeh#4205]
Currently, to enable a Transform to be performed, the user must actively click on a control to force the calculation.  Integrating this into the DataSpec system will allow for the transformation to be performed on the fly without the need for a user to force the calculation.

**Comment by bryevdv** [comment]
Hi @justacec we can talk more soon, but a quick info dump.

All of the `*Spec` properties ultimately resolve into one of two JSON representations: 

* `{ 'value': 10 }`
* `{ 'field': 'foo' }`

There can also be a `'units'` field, but let's ignore that for now. The differences between all the different "spec" types on the python is really just to apply validation, and set `'units` correctly automatically. 

The entire point of a `DataSpec` really to distinguish (in the Bokeh JSON)  between cases like:

```
p.circle(x=10, ...) # x gets always has one fixed value
```
and 
```
p.circle(x='foo', source=source, ... ) # x takes values from source.data['foo']
```

Note that we have made it easy to write things like the above, but it's always possible to actually just provide the "spec" dicts as values:
```
p.text(text={ 'value', 'hello' }, ...)   # to a bokeh,plotting glyph method

Line(x={ 'field': 'foo' }, ...)  # or a bokeh.models Glyph object
```

Then on the BokehJS side there is lots of machinery to compute columns of screen coordinates for the various renderers, and it switches on the `value`/`field` distinction to do this work. The main point of doing this at all is to reduce the size of the data we have to encode and send to BokehJS (we could turn `x=10` into an array of `[10, 10, 10, 10, ...]` and send that via JSON, and then BokehJS could be simpler, only having to ever deal with arrays, but that gets very wasteful in terms of the JSON payload size)

---

So at the first, lowest level, this task is about allow the "spec" dictionaries to have a new optional key, something possibly like:
```
{ 'field': 'foo', 'transform': Jitter(width=0.5) }
```
Then on the BokehJS side where it computes all the columns for the actual renderers there woudl be an extra step to look for and apply any transform before giving the result to the renderer. 

After that, we can look at how to make this easy to spell, e.g. maybe it would be nice to do:
```
p.circle(x=jitter('foo'), ...)
```
and have that automatically translate to the equivalent of
```
p.circle(x={'field': 'foo', 'transform': Jitter()), ...)
```
---

In terms of the difficulty of the various parts, my rough though are that the last part (convenient spelling) is probably pretty simple and straightforward. Then making BokehJS use a transform at the right place if one is present is probably also not so bad. The most challenging part is getting the serialization/deserialization machinery working correctly and also having it well-tested.

**Comment by justacec** [comment]
@bryevdv Got it.  Thanks for the pointers.  This will get me started on thinking...  We can talk more about it later.

**Comment by justacec** [comment]
@bryevdv I have started to play with this and have made progress.  I implemented your suggested workflow above with no major problems.  I am having difficulty find out how:

    plt.Circle([0, 1, 2], [5, 4, 3])

Gets converted into a colum data source in the json.  

Anyway,  just wanted you to know I am making progress.
