### ISSUE TITLE
Sub/superscript in axis labels?

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#4209]
Not sure if this is presently possible in Bokeh, but can very basic math typesetting be used in the axis labels (such as sub/superscript)? HTML tags don't seem to work, neither does $$ or using ^ and _. Is this just not possible yet?

**Comment by guillochon** [comment]
Also: sub/super also don't seem to work for tooltip labels (they do work for the values, however). Presuming these issues are related.

**Comment by bryevdv** [comment]
Not yet but the recent `Label` PR laid the groundwork for integrating LaTeX support (via katex), and will hopefully make it into `0.12`. But, marking this as a dupe of #647
