### ISSUE TITLE
Built JS and CSS not included in NPM package

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#4210]
We need to include the built `bokeh.js` and `bokeh.css` with the npm package. Then add
`"main": "build/js/bokeh.js"` to our `package.json`

**Comment by bryevdv** [comment]
Technically speaking there are multiple part of bokeh now, e.g. `bokeh-widgets.js` I'm not sure if this necessarily means multiple npm projects or of one npm project can contain all the parts.

**Comment by mistakevin** [comment]
It's alright as long as we document it. You can bring in the different components via the `browser` object in `package.json`

**Comment by mistakevin** [comment]
For reference:
npmjs.org no longer allows you to [force a re-publish](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f) so we'll have to wait for the next version bump. @bokeh/core Who/what usually publishes to npm? Is it part of a CI build or manual?

The steps to publish are:
1. `npm login`
1. `npm version <update_type>` see [here](https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package)
1.`npm publish `

**Comment by bryevdv** [comment]
https://github.com/bokeh/bokeh/blob/b2ee48b1516b1a1d95cf67f0bb99177c437c69d9/scripts/build_upload.sh

**Comment by mistakevin** [comment]
Then https://github.com/bokeh/bokeh/issues/4216 should do the trick, hopefully

**Comment by mistakevin** [comment]
Re-opening this. The build on the CDN seems to be different than the `gulp build` build. That's what should go into the npm package. How/where is that generated?

**Comment by mistakevin** [comment]
cc @damianavila @mattpap @canavandl

**Comment by bryevdv** [comment]
It shouldn't be different. What difference are you seeing?

**Comment by canavandl** [comment]
There doesn't appear to be a bokeh-widgets.js file like there is for [http://cdn.pydata.org/bokeh/dev/bokeh-widgets-0.11.1dev3.min.js]. Was the 0.11.1 release pre-split?

**Comment by bryevdv** [comment]
Actual releases are under "release"

http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.1.js

**Comment by canavandl** [comment]
![giphy](https://cloud.githubusercontent.com/assets/2198981/14925056/10f06cf0-0e0b-11e6-9192-e1a04040b691.gif)

**Comment by mistakevin** [comment]
Is the `tree` directory also there?

**Comment by canavandl** [comment]
no ^

**Comment by mistakevin** [comment]
Ok, I think I've spun around. I'll re-close this since it solves the issue, but I think a little more work will have to go into being able to bring it in cleanly with browserify after all.
