### ISSUE TITLE
Controlling significant digits in ticks and tooltips for numbers in scientific notation

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#4214]
I have both large and small numbers that sometimes appear in my plots, which are small/big enough to trigger Bokeh's scientific notation logic. When this happens, it appears that the numbers are shown with 4 significant figures no matter what in both ticks and the tooltips. For the tooltips we have the option to use a formatting specification like `@x{1.11}`, but when I do this I find that some numbers in scientific notation are either rounded down or not displayed at all. Is there a way to control the number of significant digits in either (or both) the ticks and the tooltips for numbers in scientific notation?

**Comment by bryevdv** [comment]
Hi @guillochon are you saying that the properties described here:

http://bokeh.pydata.org/en/latest/docs/reference/models/formatters.html#bokeh.models.formatters.BasicTickFormatter

Do not function as advertised? Or that you did not know to try them?

**Comment by guillochon** [comment]
@bryevdv I did not know to try them, but that's only for the ticks correct? What about the tooltips?

**Comment by bryevdv** [comment]
@guillochon we use `numbro` for formatting hover tooltip fields. I am not sure if it is documented properly, here is a link directly to their docs:

http://numbrojs.com/format.html

Any of those formats should work. If you are interested, and have the time/ability,  a PR that adds that information to our docs would be appreciated.

**Comment by guillochon** [comment]
@bryevdv Which version of `numbro` is Bokeh currently using? There was an issue fixed in October regarding large numbers which I've also run into in Bokeh: https://github.com/foretagsplatsen/numbro/issues/106

**Comment by bryevdv** [comment]
We are actually using a fork in the Bokeh GH org with some locale customizations: 

https://github.com/bokeh/bokeh/blob/master/bokehjs/package.json#L48

Not sure what version that is based off offhand.

**Comment by bryevdv** [comment]
https://github.com/bokeh/numbro

Maybe it can be easily updated if need be, if you are familiar with it a PR to merge the latest release into the fork would certainly be welcome.

**Comment by guillochon** [comment]
Any guidance on using one of the tick formatters? I can't seem to find the documentation where an example is presented. Currently I'm just accessing the axis properties through the plot like so:

```
p4.xaxis.axis_label_text_font = 'futura'
```

How can I change the precision of the axis?

**Comment by bryevdv** [comment]
you can access the formatter by, e.g.:
```
p4.xaxis[0].formatter
```
I am going to close this as referred since we are making an effort to keep all support related dicussions on the mailing list, reserving the issue tracker for feature requests, tasks, and bugs. If you have interest in contributing a PR that refines the docs with any of this information, please let me know and we can re-open as a task.
