### ISSUE TITLE
ValueError: NaTType does not support timetuple

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#4215]
See http://stackoverflow.com/questions/18212247/convert-text-dates-to-dates-and-then-keeping-the-na-values
See https://github.com/pydata/pandas/issues/9513
See https://github.com/pydata/pandas/issues/12976

bokeh 0.11.1
pandas 0.18.0

pandas uses "pseudo-native" NaT for missing datetime64 values. These can't be jsonified at the moment. Arguably it's a `pandas` compatibility issue, but something that can be easily addressed.

core\json_encoder.py: 44

For desired features, please provide:
- Treat them as None or NaN

Please assign this issue to me.

```
In [78]: isinstance(pd.Timestamp(np.nan), datetime.datetime)
Out[78]: True

In [80]: pd.Timestamp('2015-04-16').timetuple()
Out[80]: time.struct_time(tm_year=2015, tm_mon=4, tm_mday=16, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=106, tm_isdst=-1)

In [81]: pd.Timestamp(np.nan).timetuple()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-81-bf30011ea8d1> in <module>()
----> 1 pd.Timestamp(np.nan).timetuple()

pandas\tslib.pyx in pandas.tslib._make_error_func.f (pandas\tslib.c:14736)()

ValueError: NaTType does not support timetuple
```

**Comment by bryevdv** [comment]
@rs2 thanks for the issue, I can only assign people from @bokeh/dev but certainly if you would like to work on this a PR would be very appreciated

**Comment by eddy-ojb** [comment]
Has this been addressed? I'm coming across the same issue:

"ValueError: NaTType does not support timetuple".

How do I get around this issue? Is there an option to ignore NaT's?

**Comment by rs2** [comment]
@eddy-ojb Yes, just filter `pd.NaT` values using `pd,isnull`.

**Comment by cherietopham11** [comment]
Would love for this to be reviewed. I need to group dates and include a group for null values.

**Comment by bryevdv** [comment]
@cherietopham11 I'm not sure what you are saying, a fix for this was merged 5 years ago. Are you using an ancient version of Bokeh? If not, and you can reproduce a bug, please open a new bug report with full details and *most especially a **complete** reproducer* using the *latest* Bokeh release.
