### ISSUE TITLE
Feature request - choropleth maps directly from data frame

### ISSUE THREAD

**Issue by pybokeh** [bokeh/bokeh#4221]
Hello, I've been spoiled by R's choroplethr package.  I think it would be great to be able to make choropleths directly from a data frame.  For state level choropleth, the data frame would look something like data in wide format where there is a state code column and a numerical values column.

choroplethr example [here](https://rpubs.com/arilamstein/map-projs-choroplethr-3-1-0)

**Comment by bryevdv** [comment]
This seems like something better suited for higher level Holoviews at this point. cc @philippjfr @jlstevens
