### ISSUE TITLE
remove or update accidentally committed template

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4222]
The file https://github.com/bokeh/bokeh/tree/master/examples/app/weather/templates was accidentally checked in during testing of the server templates PR. It should be removed, or better, updated with reasonable content.

**Comment by damianavila** [comment]
This was closed but I don;t see any PR reference, can you link it here @bryevdv? Thanks!

**Comment by bryevdv** [comment]
was closed by accident automatically by GH

**Comment by bryevdv** [comment]
I don't see this was closed?

**Comment by damianavila** [comment]
Wow, I swear I see this closed... but now is open and green... weird stuff... ok, sorry about the noise.

**Comment by birdsarah** [comment]
I just noticed this was removed. I think we should add it back for 0.12 as it's an important new feature to demo.

**Comment by bryevdv** [comment]
My plan is to demo it in crossfilter. If we have to drop crossfilter for now, I agree.

**Comment by AgrawalAmey** [comment]
Is there any example for this which I can refer to?

**Comment by bryevdv** [comment]
@AgrawalAmey please use the public mailing list or Stack Overlflow for general support questions, we reserve the issue tracker for bug reports and feature discussion in order to keep it remotely manageable.
