### ISSUE TITLE
Add dot chord chart

### ISSUE THREAD

**Issue by merqurio** [bokeh/bokeh#4227]
I just did a [Non-ribbon Chord Diagram](http://www.datavizcatalogue.com/methods/non_ribbon_chord_diagram.html) a couple of days ago. I just want to make it available to all. Non-ribbon Chord Diagram, or **DotChord** will support two data dimension. **Relationship** between _nodes_ and "**relevance**" of the _links_.

Right now the "relevance" is pictured as a variation in the opacity. I will add the preprocessing necessary to make this "relevance" automated if desired.

My design proposal is to keep it as similar to the [chord](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/chord_builder.py) as possible.

I would love to include maybe more data dimensions, but I'd like to hear what do you think about it first.
Any feedback or ideas are more than welcomed !!! 😁 Now it's a great moment to the discuss about it.

Photo to prove it.

![fig01](https://cloud.githubusercontent.com/assets/1485056/14770051/dac93a04-0a67-11e6-9398-ce1c36a2421f.jpg)

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/13)
