### ISSUE TITLE
Bar chart: column label was "color", plot colors were undefined

### ISSUE THREAD

**Issue by anasilviacs** [bokeh/bokeh#4229]
While doing a stacked bar plot, I passed on a column named "color" as the "label" argument, and the output plot was all white. If I asked for the legend to be shown, all the categories would be labelled as grey (the bars were all still white). Changing the name of the column to "unique_color" fixed it, but I assume this behaviour isn't intentional :)

**Comment by bryevdv** [comment]
@anasilviacs can you provide a minimal code sample that can be run to reproduce this issue?

**Comment by anasilviacs** [comment]
Sure. I've been playing with the kaggle "animal shelter" data and wanted to look at how the color of an animal affected its outcome (there are 5 possible outcomes). Here's the head of the table:
```
    outcome          color     total
0  Adoption   color_Agouti       0.5
1  Adoption  color_Apricot  0.333333
2  Adoption    color_Black  0.405533
3  Adoption     color_Blue  0.396347
4  Adoption  color_Brindle  0.412169
```

If I then do:

```python

p = Bar(df, label='color', values='total', agg='sum',
        stack='outcome', legend='bottom_right', plot_width=1000)
show(p)
```

I get the following image:

![bokeh_issue](https://cloud.githubusercontent.com/assets/17022777/14880003/c8b50fce-0d2c-11e6-95aa-67d89c73fc3c.png)


If I change the column name from `color` to `unique_color`:
![outcomepercolor](https://cloud.githubusercontent.com/assets/17022777/14880018/e1a83a2e-0d2c-11e6-95b5-f826c5f33f09.png)

**Comment by bryevdv** [comment]
Closing, as `bokeh.charts` has been removed to a different project and repo.
