### ISSUE TITLE
Feature Request: Calendar Charts

### ISSUE THREAD

**Issue by dhirschfeld** [bokeh/bokeh#4235]
Calendar charts which plot daily values grouped by both week and month are a good way to spot patterns in data:

e.g. https://developers.google.com/chart/interactive/docs/gallery/calendar#days

It would be nice to have an easy way to create these charts in bokeh given a daily timeseries of data.

**Comment by bryevdv** [comment]
There is a calendar example using models. Regarding a high level chart, bokeh.charts has moved to https://github.com/bokeh/bkcharts this should be re-opened there if appropriate.

**Comment by bryevdv** [comment]
https://github.com/bokeh/bokeh/blob/master/examples/models/file/calendars.py

**Comment by elmq0022** [comment]
Thanks Bryan!
