### ISSUE TITLE
Create a custom 404 page for Bokeh Docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4241]
As suggested [here](https://github.com/bokeh/bokeh/pull/4239#issuecomment-215233233) the JS warning banner for old/dev docs could try to redirect to users the same specific page, in the latest doc. But in cases where the specific page no longer exists, it would be better to have users land on something better than a default 404 page

Proposed to create a better designed and more informative 404 page for the docs site at http://bokeh.pydata.org 

Possible features:
- incorporate Bokeh logo
- provide link to current docs main page
- include the GCSE search box

**Comment by jsignell** [comment]
http://bokeh.pydata.org/en/latest/slfjsg
