### ISSUE TITLE
Add example with drawing networkx graphs

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4244]

**Comment by birdsarah** [comment]
If it's useful, I made this last year: http://nbviewer.jupyter.org/github/gmarkall/wot/blob/master/wot/notebooks/Visualize%20the%20WOT.ipynb

**Comment by mattpap** [comment]
It might, thought I already have code from my talk from last Wednesday.

**Comment by edurand** [comment]
@mattpap, I have been playing with Bokeh and networkx a little bit. I'd be really interested in seeing your slides / code if they are available somewhere...
