### ISSUE TITLE
Offline with Bokeh & IE11

### ISSUE THREAD

**Issue by crashMOGWAI** [bokeh/bokeh#4249]
Has anyone had issues with bokeh 0.11.1 while trying to use offline with IE11? Is there any special setup required to go offline with this browser that I'm missing?

**Comment by crashMOGWAI** [comment]
Oh duh... the saved figure html headers are trying to call back for the stylesheet/script
This issue only occurs on some of the browsers I've tried. The manifest will need to be edited to cache the essentials and provide offline alts.

**Comment by bryevdv** [comment]
No worries :)
