### ISSUE TITLE
Notebook rendering is broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4254]
It appears #4189 broke notebook rendering. Perhaps this is because the DOM is already loaded? I was not aware that notebook `show` currently went though the `autoload_js` template. A fix might be to split off the `onload` part into a wrapper that is only applied selectively.

**Comment by seanlaw** [comment]
@bryevdv Would it be better/easier to just have an extra argument for autoload_static() like:

autoload_static(..., onload=False)   # Which would be default and not add the event listener

and autoload_static(..., onload=True)  # Which would add an event listener to the JS

This way it doesn't break backwards compatibility and makes the onload it explicit

**Comment by bryevdv** [comment]
@seanlaw that might be a reasonable and quick fix! I do want to take this issue as an opportunity to do a little investigation and poking, I think our notebook loading is not as bulletproof as it once was so I would like to evaluate it top-to-bottom, and try to make it as simple and streamlined as possible.
