### ISSUE TITLE
[Feature Request] Pass ColumnDataSource to High Level Bokeh Charts

### ISSUE THREAD

**Issue by AlJohri** [bokeh/bokeh#4259]
I was trying to add a tooltip to a timeseries chart today and my one line chart became about 20 lines because I couldn't add a `ColumnDataSource` to the `Timeseries` high level chart interface.

This is the plot I started with:

```
hover = HoverTool(tooltips=[("(x,y)", "($x, $y)")])
p = TimeSeries(df, x='Date', y=['DEM16_WTA', 'REP16_WTA'], tools=hover)
```

**My goal is to add a tooltip to simply show the X value (as a date) and y value.**

There seem to be two options:

changing the HoverTool to support date formatting options #1239

OR (the seemingly easier)

passing in an additional ColumnDataSource

This way the variables from the `ColumnDataSource` will be passed on to the `HoverTool`

``` python
source = ColumnDataSource(df[['Date', 'LastPrice', 'DateStr']])
hover = HoverTool(tooltips=[("(x,y)", "(@DateStr, $y)")])
TimeSeries(df, x='Date', y=['DEM16_WTA', 'REP16_WTA'], tools=hover, source=source)
```

**Without the above feature, I am unable to use the high level `Timeseries` interface and have to reconstruct the plot using `p.line` manually setting everything from the axes labels, colors, legend location, default height width etc... very tedious.**

``` python
hover = HoverTool(tooltips=[("(x,y)", "(@DateStr, $y)")])

p = figure(
    plot_width=defaults.width, 
    plot_height=defaults.height, 
    x_axis_type="datetime")

for contract, df in pres16_wta.groupby('Contract'):
    source = ColumnDataSource(df[['Date', 'LastPrice']])
    source.add(df.Date.map(lambda x: x.strftime('%x')), 'DateStr')
    color = "blue" if contract == "DEM16_WTA" else "red"
    p.line(x='Date', y='LastPrice', color=color, legend=contract,
           line_width=2, 
           source=source)
p.add_tools(hover)

p.xaxis.axis_label = "Date"
p.yaxis.axis_label = "LastPrice"
p.legend.location = "top_left"
p.logo = None

show(p)
```

Would love to know if I'm missing something. Thanks!

**Comment by bryevdv** [comment]
It might be possible in certain specific cases (e.g. `TimeSeries`) In general the raw data passed in to a chart may be reduced or processed, and then the data actually sent to to BokehJS is some kind of derivation that is one step removed from the raw data. For instance, in a `Histogram`, none of the actual raw data is sent to the browser, only the derived data for drawing the histogram bars is. So while it might be possible to make `Histogram` accept column data sources as input, there'd be no way to "match up" columns for things like hover tool (since those data columns are not actually sent to the browser).

**Comment by AlJohri** [comment]
@bryevdv thanks that makes sense - I didn't realize this was more of a special case that may only work for `TimeSeries`, `Scatterplot` and maybe a few others - especially not `Histogram` or `Bar` charts that have an `agg` parameter etc.

I'm trying to make a relatively simple graph as I talked about above with addition of tooltips: http://nbviewer.jupyter.org/gist/AlJohri/3b99f3132cba41147f08938a8d0f5c08

would love to get your input on how to make this easier. [graph source code](https://gist.github.com/AlJohri/de75b244751c8bbeaedfe25fbaa4499d)

**Comment by nateGeorge** [comment]
Oh man, just came across the same problem with bar charts.  Thanks for the code sample @AlJohri !  More or less the same thing but with p.vbar() instead of p.line()

**Comment by tommycarstensen** [comment]
I have the same issue with `[bokeh.plotting.vbar](http://bokeh.pydata.org/en/latest/docs/reference/plotting.html#bokeh.plotting.vbar)` VS `[bokeh.charts.Histogram](http://bokeh.pydata.org/en/latest/docs/reference/charts.html#histogram)`. I'm just going to do my histogram with `vbar` or `quad` as shown here:
http://bokeh.pydata.org/en/latest/docs/gallery/histogram.html

**Comment by akasolace** [comment]
I have the same issue with vbar VS high level Bar.
I need both to have both on_change method  (possible only with vbar) and grouped bar on categorical x-axis (possible only with Bar)   (see example below)

If you have a suggestion on how I can achieve that with current bokeh version that would be much appreciated

![capture](https://cloud.githubusercontent.com/assets/1136496/24905258/9cb982ee-1eb3-11e7-944a-023c396f3e32.PNG)

**Comment by bryevdv** [comment]
bokeh.charts has moved to https://github.com/bokeh/bkcharts this should be re-opened there if appropriate.

**Comment by bryevdv** [comment]
@akasolace improvements to categoricals that would bette support that use case in `bokeh.plotting` are scheduled for `0.12.6` or `0.12.7`

**Comment by AlJohri** [comment]
thanks @bryevdv! is there a github issue to follow on the bkcharts repo for this feature?

**Comment by bryevdv** [comment]
@AlJohri the categoricals improvements are to core bokeh. There are a cluster of issues, this is one of them: https://github.com/bokeh/bokeh/issues/5847

There is not an issue in bkcharts relating to the original statement here ("pass CDS to charts") you are welcome to make one in `bkcharts`
