### ISSUE TITLE
There should be an actual click tool

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4261]
Currently we have tap tool which acts as a hybrid of select and inspect tool. It modifies selection on associated data sources and executes a callback. I would like to have a tool (or a mode) where I could execute a callback only. One option is to add (e.g.) `ClickTool` or add `select = Bool(True)` to `TapTool`. Perhaps we can get both sides by in one change by adding the later and making `click` tool alias to set `select=False`.

**Comment by bryevdv** [comment]
My vote would be to extend the current tool rather than adding a new, separate tool.

**Comment by crashMOGWAI** [comment]
Just a heads up, its TapTool in the code & Reference, TapSelectTool in UserGuide. 
Also has the tool attribute for setting as initially active or not been exposed yet?

**Comment by bryevdv** [comment]
@crashMOGWAI thanks for the heads up, that Reference is correct, and the user's guide should be changed. 

Setting active programmatically is WIP should be in the next release.

**Comment by mattpap** [comment]
> My vote would be to extend the current tool rather than adding a new, separate tool.

I went ahead with that. Just instead of `select = Bool` there is `behavior = Enum("select", "inspect")`, because `select` is already in use (a method on `Model`).

**Comment by mattpap** [comment]
Thanks to `SelectionManager.{select,inspect}` there is now nice symmetry between this tool's behavior.

**Comment by bryevdv** [comment]
@mattpap can you correct the User's Guide doc in this PR as well? I like the `Enum`, I think "behavior" is a little long-winded but I don't have a better suggestion either.

**Comment by mattpap** [comment]
@bryevdv, one unfortunate thing is that callback is executed always, even if there was no hit on a glyph. This behavior is inherited from selection tools, which allow to clear selection by clicking on empty space. I think that in inspect mode, `TapTool` should call callback only on successful hit, so simple things like `console.log("Click")` works as intended. The question remains what to do in select mode. If we do the same as in inspect mode, other facilities won't be affected (selection glyphs, etc.). I'm not sure if there is application for tap tool's callback being called with empty selection.

**Comment by mattpap** [comment]
@bryevdv, PR #4274 has a preliminary implementation.

**Comment by jaredsagendorf** [comment]
Actually, I need my tap tool to execute a call back when nothing is selected. I use my tap tool call back to modify some HTML elsewhere on the page, and when the selection is cleared, I want to clear that generated HTML.

I'm a little unclear how I can re-introduce this behaviour in 0.12. Currently, the default seems to be that no callback is called on an empty selection.
