### ISSUE TITLE
"Save Image" tool on bokeh gallery produces garbled view (Chrome and Firefox)

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#4262]
"Save Image" tool[1] on bokeh website http://bokeh.pydata.org/en/latest/docs/gallery/texas.html provides strange layout in both Firefox and Chrome (latest) on Mac OS X:

![screenshot 2016-04-28 21 33 56](https://cloud.githubusercontent.com/assets/293525/14956363/55c8557e-104d-11e6-9439-7e4037033c3e.png)

![screenshot 2016-04-28 21 34 04](https://cloud.githubusercontent.com/assets/293525/14956382/742e686e-104d-11e6-917d-d77762b9e506.png)

[1] 3.5" floppy disk -- haven't used one of those in >10 years! -- but I suppose people who have **never** used them still associate the icon/image with "save file?"

**Comment by bryevdv** [comment]
Based on some recent work it's almost 100% certain that the modal dialog is going away, to be replaced by a proper download dialog (where supported) or a new tab with just the image (where not supported).
