### ISSUE TITLE
Use a gradient as background in a Bokeh chart

### ISSUE THREAD

**Issue by GiannisIordanou** [bokeh/bokeh#4271]
To set the color of the background in Bokeh, you can do the following, found in the relevant [Bokeh documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#background):

```
from bokeh.plotting import figure, output_file, show

output_file("background.html")

# create a new plot with a title
p = figure(plot_width=400, plot_height=400)
p.background_fill_color = "beige"
p.background_fill_alpha = 0.5

p.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=10)

show(p)
```

Also, in the [Bokeh documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#specifying-colors) mentions the ways you can specify color:

> Colors properties are used in many places in Bokeh, to specify the
> colors to use for lines, fills or text. Color values can be provided
> in any of the following ways:
> 
> ```
> - any of the 147 named CSS colors, e.g 'green', 'indigo'
> - an RGB(A) hex value, e.g., '#FF0000', '#44444444'
> - a 3-tuple of integers (r,g,b) between 0 and 255
> - a 4-tuple of (r,g,b,a) where r, g, b are integers between 0 and 255 and a is a floating point value between 0 and 1
> ```

Based on the above it seems you can only set one color for the background.

I think it would be useful if there was a way to set a gradient as the background color in a Bokeh chart.

**Comment by bryevdv** [comment]
I'm going to roll this into #6135, I think it would fallout if that was implemented
