### ISSUE TITLE
Panels  Figures and Toolbars

### ISSUE THREAD

**Issue by crashMOGWAI** [bokeh/bokeh#4273]
I'm having issues when trying to set different panel toolbars  to their respective figures. 

The following method throws a bokeh\models\plots.py line202 ValueError: 
```
#Doesn't Work
TOOLS= [BoxZoomTool(),
        LassoSelectTool(),
        PanTool(),
        WheelZoomTool(),
        HoverTool(tooltips= [('THING1','@X'),
                             ('THING2', '@dFILE')])]

p1 = figure(tools = TOOLS)
tab1 = Panel(child=p1, title= 'ONE') 

p2 = figure(tools = TOOLS)
tab2 = Panel(child=p2, title= 'TWO')

tabs = Tabs(tabs=[tab1, tab2])
```
However, the following work around does.
```
#Does Work
TOOLS= [BoxZoomTool(),
        LassoSelectTool(),
        PanTool(),
        WheelZoomTool(),
        HoverTool(tooltips= [('THING1','@X'),
                             ('THING2', '@dFILE')])]

hoverTAGS = [('THING1','@X'),
             ('THING2', '@dFILE')]

p1 = figure(tools = 'box_zoom,lasso_select,pan,wheel_zoom,hover')
tab1 = Panel(child=p1, title= 'ONE') 

p2 = figure()
tab2 = Panel(child=p2, title= 'TWO')
p2.select_one(HoverTool).tooltips = hoverTAGS 

tabs = Tabs(tabs=[tab1, tab2])
```
The working technique results in a clone of the first panel with the same toolbar/interactions.

**Comment by crashMOGWAI** [comment]
The linked panning and brushing works, and bokeh is keeping track of the selections but it doesn't look like the selection_ & nonselection visual property helpers work across tabs.

**Comment by bryevdv** [comment]
The first scenario is not expected to work. Tools have a reference to the particular plot that that operate one, which means they cannot be shared between multiple plots. Each plot needs to have its own tool objects.
