### ISSUE TITLE
Python unit tests don't pass if `BOKEH_DEV=true`

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4277]
I use the environment variable `BOKEH_DEV=true` consistently when I'm developing. 

However, as that sets the BOKEH_MINIFIED environment variable it causes the python unit tests about Resources to fail specifically:

``` sh
bokeh/tests/test_resources.py::TestResources::test_server_with_versioner FAILED
bokeh/core/tests/test_state.py::TestState::test_default_file_resources FAILED
bokeh/core/tests/test_state.py::TestState::test_output_file FAILED
bokeh/core/tests/test_state.py::TestState::test_output_file_file_exists FAILED
```

I'm not sure if we should fix these tests or just make a note in the testing docs. Either's fine with me.

**Comment by mattpap** [comment]
btw. By unit tests you mean ` py.test -m 'not (examples or js or intergration)'? Would it be possible to add `unit` alias, so that it would simply be `py.test -m unit`?

**Comment by mattpap** [comment]
I see a lot more failures (34 in total). A few seem like real failures, but in general tests failures under `BOKEH_DEV=true` are expected to happen. The reason is that `BOKEH_*` variables take precedence over whatever is in the code. I think that for now we have to live with this and update documentation. In a longer term, we may want to simplify bokeh's configuration and in the mean time figure out how to make tests independent of external settings.

**Comment by mattpap** [comment]
btw2. Those tests are pretty presumptuous, e.g.:
```
    def test_simple_ids(self):
        import os
        os.environ["BOKEH_SIMPLE_IDS"] = "yes"
>       self.assertEqual(make_id(), "1001")
E       AssertionError: '6678' != '1001'
```
It would have been better to test if `make_id()` generates a value of the particular form, not for an explicit value. The reason this test works without `BOKEH_DEV` is that all other IDs are UUIDs, so here we actually start from the first identifier in simple form. However, if simple IDs were used anywhere else, then this could not work or even be nondeterministic (under parallel testing).

**Comment by birdsarah** [comment]
> By unit tests you mean ` py.test -m 'not (examples or js or integration)'?

Yes

> Would it be possible to add `unit` alias, so that it would simply be `py.test -m unit`? 

-m unit would mean marking all unit tests with pytest mark `unit`. Also see discussion here: https://github.com/bokeh/bokeh/issues/3906.

**Comment by bryevdv** [comment]
`-m unit` is now available with `implicit_mark`
