### ISSUE TITLE
Tests for WebGL

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4279]
Our WebGL functionality does not really have tests and I have been fixing it up after refactorings in bokehjs a few times now. I'd love to have a few tests for it to avoid this in the future.

* Can we run tests on selenium/saucelabs with webgl enabled?
* Do we actually test for image similarity yet?

cc @birdsarah

**Comment by almarklein** [comment]
> Can we run tests on selenium/saucelabs with webgl enabled?

It looks like we can not: https://saucelabs.ideas.aha.io/ideas/SLIDEA-I-54

Any other ideas?

Otherwise we should probably write up a short readme which lists the examples that should be run to test WebGL functionality.

**Comment by birdsarah** [comment]
> Can we run tests on selenium/saucelabs with webgl enabled?

I would have thought so, but your link certainly indicates no. Actually thinking about this it makes sense - they're probably running on virtualized hardware which wouldn't have GPUs. We could run our own selenium box and run some specialized tests on it. I think there are a set of testing infrastructure questions like this that we need to run through and set-up for 1.0.

> Do we actually test for image similarity yet?

Yes, there are two image diff tests currently. Matteusz and I have been debating some of the issues surrounding this, and so we should definitely proceed with caution in terms of image diff testing while we're still working out the most effective way to have visual diff tests.

**Comment by almarklein** [comment]
Ok, for now I added a text file that lists meaningful WebGL examples in #4269.

**Comment by birdsarah** [comment]
I checked with saucelabs and percy.io and neither offer webgl testing - due to virtualization.

However, we could have a test that runs locally (and skips on saucelabs) so, at the least, someone can run them for release even if they don't get run in CI.

**Comment by almarklein** [comment]
Without being able to use them in CI, I am not sure if its worth the effort to write automated tests. I already made a readme that lists the examples that use/test WebGL. I think I'll turn that into a script that actually runs all WebGL examples after which you can quickly inspect a few browser tabs. That should make webgl testing as easy as possible.

**Comment by bryevdv** [comment]
There's already the interactive tester. Maybe add a "webgl" category to it.

**Comment by almarklein** [comment]
The WebGL examples will be run in the interactive tester as part of the `plotting/file` tests. But I think we need something smaller and simpler to be able to quickly check whether WebGL still works (as expected), see #4417.

**Comment by bryevdv** [comment]
right, I'm suggesting adding a "webgl" category that just runs webgl tests, since that is your particular interest. It's OK (IMO) if the categories overlap. Alternatively, let's move all the webgl examples to one separate place.
