### ISSUE TITLE
Provide examples of using RemoteSource/AjaxDataSource in the docs

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#4286]
```
For desired features, please provide:
* Description of the desired feature
```

Both data sources are great alternatives to `ColumnDataSource` and can tremendously reduce the size of the page downloaded by the client and shift the logic from JavaScript to Python, e.g. when serving the data using a REST API.

**Comment by akingscote** [comment]
please do this!

**Comment by bryevdv** [comment]
Please see https://github.com/bokeh/bokeh/blob/master/examples/howto/ajax_source.py

**Comment by bryevdv** [comment]
Also FYI `RemoteDataSource` is just a base class at this point, it is not useful on its own.
