### ISSUE TITLE
Document title should take on plot title if not given

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4287]
As mentioned in #3791:

The user currently separately specifies a title for the plot and for the html page. It makes sense that this is possible, because a page can contain multiple plots, but in most cases a page is just one plot.

When the user does not specify output_file(), or calls it without providing a title, the page title should take on the title of the plot.

cc @mattpap

**Comment by bryevdv** [comment]
I'm -1 on magic that only works in a subset of cases. More than one plot is extremely common and this will not help in that case.
