### ISSUE TITLE
Make scroll-zoom click-to-enable in toolbar

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#4288]
Scroll-zoom is super handy, but I'd prefer to create plots with it disabled (I'm happy to set that myself), and when I want to use it to actually click on the toolbar to enable scroll-zoom.  This will avoid the super annoying problem of zooming in and out on a figure when I'm just trying to scroll a web page that contains a bokeh plot.

**Comment by bryevdv** [comment]
It's been disabled by default for some time, as demonstrated by scrolling on the page

http://bokeh.pydata.org/en/latest/docs/gallery/streamline.html

So if it is not disabled by default for you, then that is not expected, and more information is needed.

**Comment by mattpap** [comment]
@bryevdv, based on issue #4289, @ijstokes is still on bokeh 0.10, so that's the reason it doesn't work.

**Comment by bryevdv** [comment]
Fixed in later releases.
