### ISSUE TITLE
Clever way to snapshot layout and view

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#4289]
Publishing Jupyter Notebooks that contain Bokeh plots is something I do a lot.  The problem is that sometimes the "best" initial view for the plot is not the "default", so I want to do some client-side manipulation to get the plot into the view that I want "saved".  But (of course) the server side has no idea what my particular view looks like.  If there were some secret key-stroke that could display a little code snippet that i could cut-and-paste to add to my server-side code that would then initiate the plot in that particular client-side view that would be super -- then the published plot would (if I'm understanding correctly how things work) appear "just right".

**Comment by ijstokes** [comment]
Here is the example which inspired this:

https://anaconda.org/ijstokes/high-performance-io/notebook

And here is what I actually wanted it to look like (zoomed in to just 3.17 to 3.22 seconds):

![screenshot 2016-05-05 22 31 01](https://cloud.githubusercontent.com/assets/293525/15062745/2410998a-1311-11e6-9af6-d72f2173aa91.png)

**Comment by bryevdv** [comment]
I'm going to consider this part of #182
