### ISSUE TITLE
WebGL blurry on OS X, not visible in Safari

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#4293]
Hi all,

I'm noticing that WebGL output appears to be very blurry in Chrome/Firefox on OS X, and completely invisible in Safari. With WebGL disabled, the glyphs look crisp and clear:

<img width="504" alt="screenshot 2016-05-07 10 11 21" src="https://cloud.githubusercontent.com/assets/4998058/15092600/8f255ba8-143c-11e6-8c8c-f81ed922b77c.png">

With WebGL enabled, it becomes a blurry mess:

<img width="510" alt="screenshot 2016-05-07 10 11 04" src="https://cloud.githubusercontent.com/assets/4998058/15092606/9f158380-143c-11e6-8384-7d44f5551690.png">

...and on Safari none of the glyphs are visible! I've noticed the same behavior with line plots too, very blurry:

<img width="496" alt="screenshot 2016-05-07 10 21 46" src="https://cloud.githubusercontent.com/assets/4998058/15092632/8745cf84-143d-11e6-83ca-809e387620f0.png">

You can see the blurry version here: https://sne.space/sne/SN1987A-blurry/, the non-blurry version here: https://sne.space/sne/SN1987A/.

Any idea on how to improve the WebGL rendering? And how to make the plots work in Safari?

Thanks!

**Comment by bryevdv** [comment]
@guillochon webgl is currently not working for Safari yet, see  https://github.com/bokeh/bokeh/issues/2683 

@almarklein any ideas about the blurriness?

**Comment by almarklein** [comment]
It's a wee bit more "blurry" everywhere, because of antialiasing (without WebGL it looks more crisp, but also jaggy), I could see if I can tweak this though.

There is a point where the WebGL canvas gets blitted into the regular canvas, which is where a magical pixel offset is required. It might be that this offset ought not to be the same everywhere. I had to change it recently (#4292), probably because of a change in bokehjs. This is a point that might need some looking into ...

I always thought it looked blurrier in Firefox than on Chrome/Edge, but I just realized that is because in Firefox the plot is larger :) 

Could you please provide the source to create that plot, or a new screenshot with matching source so that I can reproduce and see if that amount of blur is expected?

**Comment by almarklein** [comment]
I just realized that the difference in blurryness could be larger on retina displayes, because with WebGL we might not take full advantage of the "subresolution" of the retina display, whereas 2D canvas might.

**Comment by bryevdv** [comment]
2D canvas definitely detects and applies the necessary scale factor on retina displays: 

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/util/canvas.coffee#L38-L48

**Comment by almarklein** [comment]
In #4293 I decreased the aa to get more crisp images. This should help, but there might be remaining causes of blurryness depending on the system.

**Comment by almarklein** [comment]
It seems that WebGL does not work well w.r.t. the hidpi trick (based on `window.devicePixelRatio`) that we do. From what I've read, `devicePixelRatio` is twice as high on retina displays, so it would explain the extra blurryness on OSX. It also explains why it looked more blurry on Firefox, which uses a higher zoom factor (thus higher `devicePixelRatio`) by default. Looking into it.

**Comment by bryevdv** [comment]
Well afaik it's not a trick, it's the right way to get crisp canvas drawing on hidpi displays. It would be unfortunate but I guess not surprising if webgl handling that case differently. But hopefully there's a way to make them work together.

**Comment by almarklein** [comment]
> Well afaik it's not a trick, it's the right way to get crisp canvas drawing on hidpi displays

I agree. Though its a method that does not seem documented well, except in a few blog posts, which makes it feel a bit like a "trick" :)

The point is that the `ctx.scale(ratio, ratio)` does not apply to the WebGL drawing (obviously). I am confident that this can be made to work, I just need to figure out where to scale what.
