### ISSUE TITLE
legend can't be updated via ColumnDataSource

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#4296]
source1 = ColumnDataSource(data=dict(x=[], y=[], legend=[]))
p1.line(x='x', y='y', legend='legend', source=source1, line_width=3, color="navy", alpha=0.5)

Legend can't be updated via ColumnDataSource

**Comment by bryevdv** [comment]
That's never going to work in general, and is not expected to work now. Actually for a whole variety of reasons:

*  `legend` is already not a `DataSpec` that hooks up to a source (just a simple regular property)
* one of the assumptions of ColumnDataSource is that is is a collection of lists/arrays that are ***all the same length** But a "legend" column would only make sense with at most one entry. 
* it's a property on the `Plot` the glyph function argument is just syntactic sugar / convenience to set it up

If you need to update the legend you will set attribute values on `Plot.legend`
