### ISSUE TITLE
Unexpected tool duplication warning when using different configurations of the same tool

### ISSUE THREAD

**Issue by liyanage** [bokeh/bokeh#4301]
I added the WheelZoom tool to a plot twice, but in two different configurations:

    tools = 'pan,xwheel_zoom,wheel_zoom,box_zoom,resize,reset,hover,save'

Observed: I'm getting this warning:

> UserWarning: WheelZoomTool are being repeated   warnings.warn("%s are being repeated" % ",".join(repeated_tools))

Expected: Different configurations of the same tool should not count as duplicates.

I worked around it by adding one of the two programmatically instead:

    tools = 'pan,xwheel_zoom,box_zoom,resize,reset,hover,save'
    figure = bokeh.plotting.figure([...], tools=tools)
    figure.add_tools(bokeh.models.tools.WheelZoomTool())

**Comment by bryevdv** [comment]
@liyanage can you explain more what the use-case is? `wheel_zoom` includes `xhweel_zoom` so there should not be any reason (or effect) to add both. What are you wanting to accomplish by adding both?

**Comment by liyanage** [comment]
I generally use the wheel_zoom, but I found that it is very useful to sometimes be able to switch to the xwheel_zoom separately just to change the time scale in the data set I'm plotting.

I will first use the regular zoom to get the y-range to where I need it, but then often I want to see more or less in the horizontal axis, without disturbing the vertical one.

**Comment by liyanage** [comment]
Am I overlooking something and there is some keyboard modifier for wheel_zoom that will restrict zooming to just one axis?

**Comment by bryevdv** [comment]
Oh I see, that had not occurred to me. I should mention that if  you wheel zoom over an axis area, you will get a zoom constrained to that axis, but would also agree that is not very discoverable.

**Comment by liyanage** [comment]
Oh that's perfect! I didn't know it does that, that definitely covers my need. Feel free to close this if you like.

**Comment by bryevdv** [comment]
OK closing, tho at some point we might want to consider ways to make the axis zoom more discoverable.
