### ISSUE TITLE
New title API & implementation

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4307]
This issue is a place to pick up the good conversation that started on #4282 about the new title API.

This is part of the New Bokeh Layout work #4164 

- [ ] Label annotation -> LabelSet & Label
- [ ] Title annotation
- [ ] New title API

**Comment by birdsarah** [comment]
Following phone calls with @pzwang @bryevdv @canavandl, we came to the following conclusions.

For annotations it may often make sense to have a single and a vectorized version of the same annotation. We will give these the same naming conventions: Label/LabelSet Arrow/ArrowSet - where the suffix Set indicates the ability for an annotation to be vectorized, that is it accepts a data source.

We will have a seperate title. It will have a property `title_alignment` (or something similar) that will, for now, accept `left`, `center`, `right`. If you set the title_alignment to `center` the title will move to the center of the layout box and the text_align (not available as a user configurable property) will be set to center. If you set the title_alignment to `right` the title will move to the right of the layout_box and the text_align will by right aka right justified.

Bokeh currently has no system for having one property that delegates to other properties so in order to achieve the above, Title will be similar to Label but will only offer a subset of features that Label has. It will offer an offset for positional tweaking.

The left/center/right make intuitive sense for a title above or below the plot, but don't for a rotated title on the left or right. Axis labels currently have the notion of an orientation and automatically rotate themselves depending on where they are placed on the plot. A second step for title will be to work on a conceptualization of orientation that we can use throughout Bokeh and which title will also use.

There is significant overlap between LabelSet and Text Glyph. There are some differences, but the only real conceptual difference being the render level ('annotation' vs 'canvas'). We should work to unify / streamline this. Do we want / need a Text Glyph?

**Comment by birdsarah** [comment]
For the API, we will have:

class Plot:
    title = String/Title/Label
    title_location = 'above', 'below', 'left', 'right'

On the JS side, the title will be added to the list of side renderers in the order that ensures the title is always the outer-most rendered item.

All other `title_` properties will be deprecated on Plot (title_standoff, title_text_align, title_text_alpha, title_text_baseline, title_text_color, title_text_font, title_text_font_size, title_text_font_style).

Speaking in terms of a title above the plot, we had agreed on having an x_offset parameter for title, but for not having a y_offset parameter (given that we're only having one offset, we would just name it offset). The `title_standoff` property is actually like a y_offset parameter. Now it existed for other horrible reasons - namely that we didn't have any way of properly positioning a title above the axis, but I just wanted to point this out in case we did want to consider keeping it. Conversely, I think we may want to have some kind of consistent way of doing min_border type things for all panels which would provide a means to get a padding should you want it.

**Comment by birdsarah** [comment]
@bryevdv @pzwang @canavandl - regarding a more global approach to orientation, I thought it was worth highlighting the recent introduction of SidePanel which started to bring some of the orientation pieces out of axis: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/layout/side_panel.coffee

It seems to me that SidePanel is exactly the right place to store all this logic. We can think of the whole panel and its coordinate system being rotated and then the placement of things inside it is relative to that coordinate system. This may mean that axis needs to be split into two side panels - one that displays ticks & tick labels and one that stores the axis label. I actually think this makes a LOT of sense as I would love to be able to not have axis labels be center aligned (I really don't like center alignment :D)

There is another related issue tucked in here about coordinates being relative to panels, which @canavandl and I have been discussing and we should probably implement more rigorously.

To explain, here's an example of placing a legend absolutely with and without a large left axis.

http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/Panel%20coordinates.ipynb

<img width="424" alt="screen shot 2016-05-11 at 11 41 58 am" src="https://cloud.githubusercontent.com/assets/1796208/15192289/65fb23f0-176d-11e6-9d8e-3e28867b3d65.png">

<img width="428" alt="screen shot 2016-05-11 at 11 42 14 am" src="https://cloud.githubusercontent.com/assets/1796208/15192304/701a0bbc-176d-11e6-9b45-105a112764bd.png">

The difference between the above and below plots is that an x and y axis label have been added.

The legend has stayed in exactly the same place but it has moved relative to the plot. The reason is that the x and y are relative to the canvas x and why which starts on the far outer corner (at the edge of all the axes). 

In the recent PR where I added the ability to add annotations to side panels, I implemented a "panel offset" for legend and label. That means that if `Label(x=0, y=0, ...)` is added to the `above` panel. `x=0` is relative to the above panel meaning that it will be in view. This was the only way that made sense to me. 

However, I did not implement this for 'center' panel which is the 'frame', as I didn't want to break existing behavior. But I think we should. I think that the position (which is `location` on Legend and `x`, `y` on Label) should always be relative to the panel in which it lives.

**Comment by birdsarah** [comment]
This isn't done yet. Part 1 was the title annotation. Part 2 is the new title API.

**Comment by damianavila** [comment]
Thanks for reopening... :wink: I will mark the PR as task then...

**Comment by damianavila** [comment]
Sorry @birdsarah, this is not clear to me now... Was the part 2 done and merged? In which PR, the big layout one?

**Comment by birdsarah** [comment]
Sorry, yes #4343

**Comment by damianavila** [comment]
Thanks!
