### ISSUE TITLE
Hover glyph should work without hover tool

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4310]
It seems unnecessary to having `hover_glyph` depend on hover tool. If you want just `hover_glyph` without tooltips, then you you have to set `tooltips=None` in a hover tool.

**Comment by birdsarah** [comment]
Would you mind if we labelled this a discussion not a task. I don't think that what you've said is a given and I'd like to talk through what the API would look like.

**Comment by birdsarah** [comment]
I totally see why the convenience your describing would be super helpful.

I just want to think through cases where, for example:

1) you've got some renderers with `hover_glyph` some without and you don't want hit testing on those without - default for hover hit testing is to attach itself to all renderers.
2) or you specify the `hover_glyph` but then you manually add a HoverTool with the tooltips; or you manually add the HoverTool for a different glyph

I haven't thought this through as my head's really in layout, maybe it's all easy and obvious, but I would like the different scenarios and expectations laid out before someone moves ahead with an implementation.

**Comment by bryevdv** [comment]
`bokeh.plotting` could probably synthesize and add a `HoverTool` for any glyphs methods that specify a `hover_glyph` policy. I don't think `bokeh.models` should do anything like that. There are a few issues:
* `hline`, `vline` hit-policies very common with hovers (I think), not sure how those could also be expressed easily 
* any potential issues / conflicts with explicitly user-added `HoverTool`? Basically is ther a "last one wins" problem? Maybe not, but not sure offhand.

**Comment by bryevdv** [comment]
closing as stale
