### ISSUE TITLE
Save button broken on master

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4313]
I get a console message:

```
TypeError: this.plot_view.canvas_view.canvas is undefined
```

**Comment by brittainhard** [comment]
@birdsarah Potential fix by changing [this line]
(https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/actions/save_tool.coffee#L8) to

```
canvas = @plot_view.canvas_view.ctx.canvas
```

This grabs the actual DOM canvas element, and lets you call functions like toDataUrl.
