### ISSUE TITLE
Integration tests should use Models unless explicitly testing the plotting or charts API

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4314]
Many of the integration tests (which I wrote) currently use `plotting.figure()`.

This makes the test code short, but it means we're adding extra moving parts into tests that are already complicated. 

Integration tests should only use the minimum models necessary to test the thing they're trying to test. 

e.g.https://github.com/bokeh/bokeh/blob/master/tests/integration/interaction/test_range_min_max.py

``` diff
-    plot = figure(
-        height=400, width=400, tools='pan,box_zoom,reset', x_range=x_range, y_range=y_range
-    )
-    plot.min_border = 0
-    plot.rect(x=[1, 2], y=[1, 1], width=0.9, height=0.9)
+    source = ColumnDataSource(dict(x=[1, 2], y=[1, 1]))
+    plot = Plot(plot_height=400, plot_width=400, x_range=x_range, y_range=y_range, min_border=0)
+    plot.add_glyph(source, Rect(x='x', y='y', width=0.9, height=0.9))
+    plot.add_tools(PanTool(), BoxZoomTool())
```

I've made this one change in a recent commit (https://github.com/bokeh/bokeh/pull/4308/commits/2d927c7eab5f6e59646d1ff1c212aaf4ff108a3c), but it should  be repeated for all appropriate integration tests.

**Comment by bryevdv** [comment]
All of the integration tests have been re-written. They will use `bokeh.plotting` and `bokeh.models` as appropriate going forward.
