### ISSUE TITLE
Need to be able to update the scale range on an existing graph

### ISSUE THREAD

**Issue by jms90h5** [bokeh/bokeh#4315]
We need the ability to manually modify the scale for an existing scatter plot to adjust to different data sets.  This is different than using the default autoscaling behavior in that the desired scale is set based on data displayed in a different chart.  Additionally it would be useful to be able to revert to autoscaling behavior after setting a specific data range. A discussion and example notebook can be found [here](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/6XSdyaUYt3c)

This application has up to 20 scatter (line) plots, each showing a single trace (waveform).  The user can interactively move forward and back through the dataset displaying the data available a specific point in time.  Originally we simply created the plots with the default autoscale and left it that way.  However, the users indicated that they would prefer to see the relative amplitudes.  This kind of data happens to look very similar at different scales but some graphs are typically many times larger in amplitude.  So even though calculating a fixed vertical scale that matches the largest current dataset makes many of the other graphs appear basically as flat lines, that's what they want to see.  Even though the users wanted to see a "fixed" scale adjusted to the size of the data in the "largest" graph for all the charts, we though it would still be useful to allow them to occasionally enable autoscaling to see the details in the smaller signals, which is why we were looking for the capability of reverting to autoscaling after setting a specified range.

**Comment by bryevdv** [comment]
Sorry this never got triaged. There is not enough information here to go, really we would need a code sample e.g. of what you would like to be able to do that does not work. There have been many updates and new hooks and features since this issue, so I am closing because it cannot be evaluated in the current context. Please open a new issue with details if this is still a relevant concern.
