### ISSUE TITLE
remove_root not working within a callback

### ISSUE THREAD

**Issue by phumke** [bokeh/bokeh#4320]
I attempted a hacky workaround to the bar chart data refresh limitation by attempting to remove the old bar chart and creating a new one each time the user pressed a button.  However it seems that the remove_root (and clear) didn't succeed when called within the callback - the original bar chart stays visible.

Here's a minimal code example that reproduces the issue:

(One note, the bottom two commented out lines work when then are uncommented, so remove_root appears to work during the initial call.)

```
import os
from bokeh.charts import Bar
from bokeh.models import Button
from bokeh.plotting import curdoc

prev_chart = None
doc = curdoc()

def callback():
    global prev_chart
    global doc

    data = get_data()
    bar = create_chart(data)

    doc.remove_root(prev_chart)
    doc.add_root(bar)

    prev_chart = bar

def create_chart(data):
    bar = Bar(data, title='The Data', values='count', label='date', group='grouping', legend='top_right')
    return bar

def get_data():
    data = dict(
            count=[5, 6, 3, 4, 7, 6, 10, 8],
            date=['2016-01-01', '2016-01-01', '2016-01-02', '2016-01-02', '2016-01-03', '2016-01-03', '2016-01-04', '2016-01-04'],
            grouping=['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B']
        )
    return data

init_data = ({'count': [1], 'date': ['1900-01-01'], 'grouping': ['A']})

bar = create_chart(init_data)
prev_chart = bar

button = Button(label="Refresh Data")
button.on_click(callback)

doc.add_root(button)
doc.add_root(prev_chart)

#doc.remove_root(prev_chart)
#doc.add_root(prev_chart)
```

I can include a screenshot and/or stacktrace if desired - but pressing the button doesn't change the view, and there is nothing printed within the server logs.

Other Details:

```
Chrome - Version 50.0.2661.102 m (64-bit)
Bokeh - 0.11.0
Conda - 3.19.1
Python - 3.5.1.final.0
Windows 7 Enterprise - SP1
```

Thanks for checking this out!  And by the way, Bokeh is an awesome library.  Well done on all the hard work you have put in!

**Comment by bryevdv** [comment]
This seems to have been resolved at one point, the above code is working for me. Please re-open if problems continue with `0.12.6` or future releases.
