### ISSUE TITLE
Put WebGL functionality in separate bokeh-gl.js?

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4321]
Currently, we have a `bokehgl.coffee` which kept growing as features were added. With over 1400 lines, its time to split it up into a few separate files. Further we could build a separate `bokeh-gl.js` (similar to `bokeh-widgets.js` to reduce the size of the main `bokeh.js`, though this needs some discussion to establish when WebGL support should be included.

Tasks:
- [x] Refactor into smaller chunks (#4341)
- [ ] Decide on building a separate `bokeh-gl.js`
- [ ] Build a separate `bokeh-gl.js` (#4331)?

**Comment by almarklein** [comment]
> There is a file size cost to splitting things up. Could we make a completely  separate and optional .js to reduce normal loads?

@bryevdv would that extra cost be due to the overhead for a "module"? What's that cost, proximately?

What do you mean with separate, more like a third party lib? If that means I can split that code up without affecting the total file size, that might be good.

How would optional actually work? At what point is decided a user/dev that webgl functionality is included in a plot?

**Comment by bryevdv** [comment]
I mean like we have already split bokeh-widgets.js off we could split off bokeh-gl.js potentially too. It not great that everyone who is never using webgl has to pay for 1400 lines of code all the time. 

Bryan

**Comment by mattpap** [comment]
By splitting off webgl stuff we should get at least 60 kB reduction in size of `bokeh.min.js`.
