### ISSUE TITLE
Bug --host '*' wildcard result in HTTP "403: Forbidden" error

### ISSUE THREAD

**Issue by ogrisel** [bokeh/bokeh#4325]
According to the [documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html#network-configuration) using `bokeh serve --host '*'` should accept connections on any IP address and port (possibly in combination with the `--address 0.0.0.0` flag).

However when I try for instance by adding an alternative IP address to the local host network interface:

```
sudo ip address add 192.168.99.37/24 dev wlan0
```

then launching `bokeh` with:

```
bokeh serve --address 0.0.0.0 --port 5006 --host '*'
```

and trying to access http://192.168.99.37:5006/ result in the following HTTP 403 page:

```
403: Forbidden
```

This bug is annoying when deploying services with docker orchestration tools such as docker-compose or kubernetes it is not always possible to know the public ip address that will be used to access the service ahead of time and configuring a public DNS is too cumbersome when in development mode.

**Comment by ogrisel** [comment]
#4326 has a fix for the master branch of bokeh (hopefully to be merged before the release of bokeh 0.12) but if you deployment requires bokeh 0.11.1 please feel free to patch it with:

https://github.com/ogrisel/docker-distributed/blob/1b7f25e6ec6a5b91d650c1eed44a5982a6173407/bokeh-0.11.1-fix-4325.diff

**Comment by danielfrg** [comment]
+10000

**Comment by danielfrg** [comment]
I love you so much, so many hours of pain but I found the answer! You are the best!

**Comment by ogrisel** [comment]
Hahaha. Glad I could help :)
