### ISSUE TITLE
If I pass unicode strings in bokeh.charts.TimeSeries parameters the x axis is misplaced

### ISSUE THREAD

**Issue by keobox** [bokeh/bokeh#4339]
- Description of expected behavior and the observed behavior

Expected behavior:
When I use a TimeSeries chart with custom x axis, If I pass to 'x', 'ylabel' or 'title' parameters a unicode string then the x scale in the chart is correct.

Observed behavior:
When I use a TimeSeries chart with custom x axis, If I pass to 'x', 'ylabel' or 'title' a unicode string then the x scale is misplaced by one place.
- Self-contained example code that generates the issue (if possible)

``` python
from bokeh.charts import TimeSeries
from bokeh.charts import show
from bokeh.charts import output_file
from collections import OrderedDict

df = OrderedDict([(u'Years', ['2005-12-31', '2006-12-31', '2007-12-31', '2008-12-31', '2009-12-31', '2010-12-31', '2011-12-31', '2012-12-31', '2013-12-31', '2014-12-31']), (u'Italy', [0.3358, 0.3121, 0.3704, 0.4668, 0.3766, 0.3385, 0.3804, 0.5319, 0.7068, 0.5174]), (u'France', [0.6582, 0.617, 0.6183, 0.7542, 0.7463, 0.6677, 0.7465, 0.7718, 0.956, 0.906])])
y_labels = [u'Italy', u'France']

# Issue with 'x','title' and 'y' parameters of TimeSeries,
# if I pass unicode strings the x axis
# is shiftfed by one step.
# Python 2.7.10, Bokeh 0.11.1
# I have to convert to plain strings
# x_label = 'Years'
# y_label = 'Euro/Lt'
x_label = u'Years'
y_label = u'Euro/Lt'
line = TimeSeries(df, x=x_label, y=y_labels, ylabel=y_label, legend='top_left', dash=y_labels, color=y_labels)

output_file('ts.html')
show(line)
```
- Stack traceback and/or browser developer tools console output
- Software version information output by `bokeh info` command
  Python version      :  2.7.10 (default, Oct 23 2015, 19:19:21) 
  IPython version     :  Not installed
  Bokeh version       :  0.11.1
  BokehJS static path :  /Users/ceplacan/usr/virtualenv/lib/python2.7/site-packages/bokeh/server/static

<img width="559" alt="observed" src="https://cloud.githubusercontent.com/assets/1519356/15364216/f971a664-1d1b-11e6-88a5-ca3ec19ddcd4.png">
<img width="569" alt="expected" src="https://cloud.githubusercontent.com/assets/1519356/15364268/2e16ae32-1d1c-11e6-8f16-16bffab88e8a.png">

**Comment by keobox** [comment]
The first picture shows the observed behavior.

**Comment by bryevdv** [comment]
I can definitely reproduce a problem (tho it looks a bit different for me) but only on python2, things work fine with either version and python3

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/12)
