### ISSUE TITLE
Multiline multiple (r, g, b) colors creates grey lines

### ISSUE THREAD

**Issue by alanhdu** [bokeh/bokeh#4340]
When specifying multiple `(r, g, b)` tuples for `figure.multi_line`'s color, the lines just turn up grey (ignoring the `(r, g, b)` tuples.

```python
p = figure()
p.multi_line([[0, 1], [1, 2]], [[1, 0], [1, 2]],
             color=[(255, 0, 0), (0, 255, 0)])
# works if we set color to ["red", "green"] or ["#FF0000", "#00FF00"] instead
show(p)    # The lines are just grey.
```

```bash
$ bokeh info
Python version      :  3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
IPython version     :  4.2.0
Bokeh version       :  0.11.1
BokehJS static path :  /home/alan/anaconda/envs/test/lib/python3.5/site-packages/bokeh/server/static
```

**Comment by alanhdu** [comment]
This gist (http://nbviewer.jupyter.org/gist/alanhdu/4b65dbac59c9c7956251c7bfc916b4f4) also helps show the bug.

**Comment by bryevdv** [comment]
I believe this is this issue: https://github.com/bokeh/bokeh/pull/3904

Unfortunately there's an ambiguity (no way to distinguish between lists of color tuples, and lists of lists of data), and for now the answer is basically to supply the colors a different way

**Comment by alanhdu** [comment]
Yeah, looks like a duplicate. Sorry for the noise.
