### ISSUE TITLE
Hover in charts not displaying data

### ISSUE THREAD

**Issue by billsanto** [bokeh/bokeh#4347]
It seems there is an issue with plots from bokeh.charts not showing data in the tooltip--at least for the Scatter and TimeSeries plots that I tried.  It will display grouping fields from the color or marker, but not x, y, or any other field in the dataframe.  

While I did see a workaround from http://blog.rtwilson.com/bokeh-plots-with-dataframe-based-tooltips/, but that does not seem well-suited when color and marker groups are used.  

In the code below, if the color and marker arguments are removed, then the tooltip shows no data at all.  As written, both are displayed in the plot, so the displayed content seems to correspond to the PointGlyph label arguments in ScatterBuilder.

```
from bokeh.sampledata.autompg import autompg as df
from bokeh.charts import Scatter, output_file, show
from bokeh.models import HoverTool

hover = HoverTool(
    tooltips = [
    ("cyl", "@cyl"),
    ("Weight", "@weight"),
    ("Acceleration", "@accel"),
    ('Horsepower', '@hp'),
    ('Origin', '@origin'),
])
tools = [hover]
scatter = Scatter(df, x='mpg', y='hp', color='cyl', marker='origin',
                  title="Auto MPG", xlabel="Miles Per Gallon",
                  ylabel="Horsepower", tools=tools)
output_file('test.html')
show(scatter)
```
![screen shot 2016-05-20 at 21 06 35](https://cloud.githubusercontent.com/assets/4108940/15446245/03bdcd9a-1edf-11e6-9b71-bf23cfce046d.png)

**Comment by birdsarah** [comment]
I made a notebook that hopefully explains what's going on: 
http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/Charts%20hover.ipynb

In short:

1) the whole data frame does not get pushed to the browser - only the 
data necessary for the chart

2) the data is processed so it doesn't end up with the same names

You could use the plotting api to get finer grained control 
(http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#scatter-markers), 
but you'd lose the convenience of the color and marker features.

Whilst I don't think we want to send all dataframes to the client by 
default, I do think what you're asking for is reasonable. Maybe we can 
add a "send all data" flag? I would suggest opening a feature request on 
github.

Best,

Bird


On 5/20/16 9:22 PM, billsanto wrote:
>
> It seems there is an issue with plots from bokeh.charts not showing 
> data in the tooltip--at least for the Scatter and TimeSeries plots 
> that I tried. It will display grouping fields from the color or 
> marker, but not x, y, or any other field in the dataframe.
>
> While I did see a workaround from 
> http://blog.rtwilson.com/bokeh-plots-with-dataframe-based-tooltips/, 
> but that does not seem well-suited when color and marker groups are used.
>
> In the code below, if the color and marker arguments are removed, then 
> the tooltip shows no data at all. As written, both are displayed in 
> the plot, so the displayed content seems to correspond to the 
> PointGlyph label arguments in ScatterBuilder.
>
> |from bokeh.sampledata.autompg import autompg as df from bokeh.charts 
> import Scatter, output_file, show from bokeh.models import HoverTool 
> hover = HoverTool( tooltips = [ ("cyl", "@cyl"), ("Weight", 
> "@weight"), ("Acceleration", "@accel"), ('Horsepower', '@hp'), 
> ('Origin', '@origin'), ]) tools = [hover] scatter = Scatter(df, 
> x='mpg', y='hp', color='cyl', marker='origin', title="Auto MPG", 
> xlabel="Miles Per Gallon", ylabel="Horsepower", tools=tools) 
> output_file('test.html') show(scatter) |
>
> screen shot 2016-05-20 at 21 06 35 
> <https://cloud.githubusercontent.com/assets/4108940/15446245/03bdcd9a-1edf-11e6-9b71-bf23cfce046d.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/bokeh/bokeh/issues/4347>
>

-- 

*Sarah Bird*
*/Developer, Bokeh/*

Continuum Analytics <http://continuum.io>

**Comment by birdsarah** [comment]
Edited: Sorry, I originally thought this was a mailing list question.

In future, I would note that support-type questions belong on the mailing list, and if you want to have a specific discussion about solving your problem, please do start it there. 

I will leave this issue open to be discussed as a feature request though.

**Comment by billsanto** [comment]
Thanks Sarah.  I was debating where to post this, but it seems like a bug since the tooltip is displaying ??? in lieu of data and guessed this would be appropriate, but I can post there next time.  

I'm not sure how much sending the whole dataframe would impact performance with wide dataframes, but at least it could be available by opting in as you suggested.  Alternatively, I think just sending the marker, color, x, y, plus any df fields specified in the Hovertool would be efficient and yield the expected behavior, if that is possible.

**Comment by birdsarah** [comment]
>  think just sending the marker, color, x, y, plus any df fields specified in the Hovertool

My thought is maybe that's a little too much magic. We could start with something simpler where you just manually pass in a list of columns from the dataframe you want available on the client side. If that's successful, maybe we could look at the extra automation you're suggesting. What do you think?

**Comment by billsanto** [comment]
If automating it is too difficult, a list is fine with me if that is what it takes to make it work.  

Thanks for posting your notebook.  After studying it, I did manage to get a correctly working example, using the charts API, in the case where there are no groups.  Once groups are added, I wasn't sure how to pack the data into the reduced number of rows, if it is even possible.  Notebook demo:

http://nbviewer.jupyter.org/github/billsanto/notebook_examples/blob/master/bokeh_hover_test.ipynb

![screen shot 2016-05-21 at 13 42 34](https://cloud.githubusercontent.com/assets/4108940/15450154/0458f0e2-1f5a-11e6-9ccb-37bd87ae733d.png)

**Comment by birdsarah** [comment]
Just to note that another user on the mailing list had a similar problem.

**Comment by Rubyj** [comment]
Indeed I did. Looking into this option now. I will have to take a look at the plotting API, but I am not using Jupyter Notebook and I am using a bar chart at the current moment.

**Comment by birdsarah** [comment]
Making bar charts using plotting got a lot easier with use of hbar and vbar, but they don't yet have hit testing, so you're stuck with Rect for the time being - sorry :S

**Comment by Rubyj** [comment]
Could probably test the hit in JS and then render the div/script for the hover that bokeh serves but I'm not sure if that's even possible from the Bokeh side

**Comment by birdsarah** [comment]
@Rubyj I don't understand your comment I'm afraid.

**Comment by Rubyj** [comment]
More simply put, would it be possible to send over the data frame to the front end and have the front end (JS) update the hover box?

**Comment by birdsarah** [comment]
@Rubyj are you suggesting something different from the suggestions already higher up on this issue? You can't literally send the data frame.

**Comment by Rubyj** [comment]
@billsanto I am having an issue with your solution. specifically in this line 
`    for field in fields_to_add:
        glyph_renderer.data_source.data[field] = list(df[field]) `

`field` is not in ` glyph_renderer.data_source.data` 

However, in your example field represents a field to add so why should that exist in the data source a.k.a the renderer fields?

**Comment by Rubyj** [comment]
@billsanto For example my output is 
tooltip_fields:  ['Count', 'Mean', 'SD', 'Min', 'Q1', 'Median', 'Q3', 'Max', '68', '95', '99.7']
renderer_fields:  ['Series 4', 'Series 3', 'Series 2', 'Series 1', 'Series 0']
fields_to_add:  ['Count', 'Mean', 'SD', 'Min', 'Q1', 'Median', 'Q3', 'Max', '68', '95', '99.7']
counts before adding:  [('Series 4', 1), ('Series 3', 1), ('Series 2', 1), ('Series 1', 1), ('Series 0', 1)]

but

`for field in fields_to_add:'
'    glyph_renderer.data_source.data[field] = list(df[field])`
throws a > KeyError: 'Count'

**Comment by Rubyj** [comment]
@birdsarah @billsanto Any idea if this will work for a violin chart or am I SOL

**Comment by birdsarah** [comment]
@Rubyj - sorry you're having problems, and I'd like to start up a conversation to try and help. But your comments are not furthering the discussion of the feature request of this issue.

Would you mind posting your questions to the mailing list https://groups.google.com/a/continuum.io/forum/#!forum/bokeh and then I hope you'll understand if I delete them from here so that we can keep this a feature discussion.

**Comment by Rubyj** [comment]
I did that a while ago and you pointed me here! The circles!

**Comment by birdsarah** [comment]
My intention was that you would be able to read this issue and get context on the problem you're facing and our proposed solutions for it.

**Comment by billsanto** [comment]
@Rubyj  I see that I neglected to create a parameter for the associated dataframe in the patch_renderer function, which is confusing if you haven't renamed your dataframe as df (it was using df from the first notebook cell).  If you call the function with your dataframe as the third argument, and replace the patch_renderer code, it should work.  

I don't know how long it takes to get the nbviewer to pull from github, but you can find the updated code here now: https://github.com/billsanto/notebook_examples/blob/master/bokeh_hover_test.ipynb

**Comment by birdsarah** [comment]
@billsanto - would you mind continuing this conversation on the mailing list if it needs to continue.

**Comment by Rubyj** [comment]
@billsanto I actually noticed that so I gave my dataframe the name df. Let's continue the conversation out of github 

https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/tCipfgHjrhs

**Comment by wu-song** [comment]
I just write a function with Basic Glyphs of bokeh to achieve the perfect Scatter with functional hover tooltip. You can give it a try.
https://github.com/wu-song/bokeh_based_visualization
