### ISSUE TITLE
Handle touch and mouse events for toolbar

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4354]
#4353 should fix the toolbar events for users with laptops with a touch screen - that have both mouse and touch events simultaneously.

The problem was here: https://github.com/bokeh/bokeh/blob/67c5c38c710d8c3a08d64893ed8c8aa273f31ac2/bokehjs/src/coffee/models/tools/button_tool.coffee#L14

Instead of manually describing the events, I think we should use Hammer as hammer has fallbacks in place to handle this kind of situation I believe (and we're already using hammer so it won't increase any overhead)

http://hammerjs.github.io/touch-action/
~~https://cdn.rawgit.com/hammerjs/hammer.js/master/tests/manual/touchaction.html (run this with both the chrome flag on and off to see)~~ (Edit: that doesn't do quite what I thought it did - we'll need to test hammer can actually help)

Some other things I found on the internet:
- http://www.html5rocks.com/en/mobile/touchandmouse/
- http://touchpunch.furf.com/

**Comment by bryevdv** [comment]
This is a very old discussion, and logs has changed since, so I am not sure what is actionable now
