### ISSUE TITLE
Line hover broken in master

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4356]
To reproduce run examples/howto/us_marriages_divorces.py on master.

<img width="531" alt="screen shot 2016-05-23 at 2 18 52 am" src="https://cloud.githubusercontent.com/assets/1796208/15466092/b7c7b2ac-208c-11e6-95f2-aa3cb5ed0925.png">

Let's definitely write a selenium test for this. There's already a hover test can use as an example. We don't need the selenium test to be a screenshot test as we can just check for the presence of the hover tooltip in the DOM with the correctly populated data.

**Comment by bryevdv** [comment]
This was broken by the properties cleanup PR. Needs to be `glyph._x`, etc. PR soon.
