### ISSUE TITLE
Feature request: more nonselection_* parameters

### ISSUE THREAD

**Issue by jesserobertson** [bokeh/bokeh#4361]
I'd like to be able to change the size of selected/non-selected glyphs in scatter plots.

From the docs:

> It is also possible to set the color and alpha parameters of a “nonselection” glyph. To do so, prefix any visual parameter with 'nonselection_'. For example, pass nonselection_alpha or nonselection_fill_alpha.

Would it be possible to extend this to a nonselection_size option as well? At the moment I can mock this out by having two sets of glyphs, one that shows on selection and one that shows on non-selection, like this:

```python
import numpy
from bokeh import plotting

# Random data to plot
xs = numpy.random.uniform(0, 1, 30)
ys = numpy.random.uniform(0, 1, 30)

# Generate plot
p = plotting.figure(tools='box_select')

# This gives me my selection styling
p.circle(xs, ys, size=10, alpha=0.6, fill_color='red', nonselection_alpha=0)

# This gives me my non-selection styling
p.circle(xs, ys, size=3, alpha=0, fill_color='black', nonselection_fill_color='black', nonselection_alpha=0.6)
plotting.show(p)
```

...but this is a bit of a pain with lots of linked variables between the two glyph sets, and could be hidden. 

Another option is to have a non-selection dictionary that provides styles but that might be too ugly for your API. :)

**Comment by jesserobertson** [comment]
Oh sorry, just noticed http://bokeh.pydata.org/en/0.9.3/docs/user_guide/styling.html#id19. My bad, please ignore me.

I'd note that this interface is not mentioned when talking about the glyphs in the documentation and this is a bit confusing - maybe something that could be tweaked?

**Comment by jesserobertson** [comment]
Ah actually, just found that the nonselection glyph doesn't change the size so maybe my feature request still stands then?

Here's a version using the manual glyph addition that _doesn't work_:

```python
import numpy
from bokeh import plotting, models

# Random data to plot
xs = numpy.random.uniform(0, 1, 30)
ys = numpy.random.uniform(0, 1, 30)
source = models.ColumnDataSource({'x': xs, 'y': ys})

# Generate plot
p = plotting.figure(tools='box_select')

# This gives me my selection styling
selected = models.Circle(x='x', y='y', size=10, line_color='red', fill_alpha=0.6, fill_color='red')

# This gives me my non-selection styling
nonselected = models.Circle(x='x', y='y', size=3, line_color=None, fill_alpha=0.6, fill_color='black')

p.add_glyph(
    source,
    nonselected,
    selection_glyph=selected,
    nonselection_glyph=nonselected
)

plotting.show(p)
```

**Comment by jesserobertson** [comment]
Here's a final version that seems to work but still requires the use of two glyph sets:

```python
import numpy
from bokeh import plotting, models

# Random data to plot
xs = numpy.random.uniform(0, 1, 30)
ys = numpy.random.uniform(0, 1, 30)
source = models.ColumnDataSource({'x': xs, 'y': ys})

# Generate plot
p = plotting.figure(tools='box_select')

# This gives me my selection styling
selected = models.Circle(x='x', y='y', size=10, line_color='red', fill_alpha=0.6, fill_color='red')

# This gives me my non-selection styling
nonselected = models.Circle(x='x', y='y', size=3, line_color=None, fill_alpha=0.6, fill_color='black')
invisible = models.Circle(x='x', y='y', size=10, fill_alpha=0, line_alpha=0)

p.add_glyph(
    source,
    nonselected,
    selection_glyph=invisible,
    nonselection_glyph=nonselected
)
p.add_glyph(
    source,
    invisible,
    selection_glyph=selected,
    nonselection_glyph=invisible
)

plotting.show(p)
```

**Comment by birdsarah** [comment]
duplicate: https://github.com/bokeh/bokeh/issues/2367

**Comment by birdsarah** [comment]
thanks for the report @jesserobertson feel free to add any thoughts to the other issue.
