### ISSUE TITLE
Allow unminified BokehJS to load in notebook

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4362]
Notebook requires "strict" mode, and some of our code fails this. The changes below allow BokehJS to be successfully loaded unminified.

this diff:
```
diff --git a/bokehjs/src/js/prelude.js b/bokehjs/src/js/prelude.js
index 1676dcb..2f3161c 100644
--- a/bokehjs/src/js/prelude.js
+++ b/bokehjs/src/js/prelude.js
@@ -9,7 +9,7 @@
 
             var m = cache[name] = {exports: {}};
 
-            function moduleRequire(x) {
+            var moduleRequire = function foo(x) {
                 var id = modules[name][1][x];
                 return newR
```

Plus these need fixing:

* `bokeh-compiler.js:6060`
```
   _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
```
* `bokeh-widgets.js:16111`
```
    if (formatter.format !== undefined) {
      var model = formatter;
      function format(row, cell, value, columnDef, dataContext) {
        return model.format(row, cell, value, columnDef, dataContext);
      }
      formatter = format
    }
```
* `bokeh-widgets:16883`
```
      function toggleCellClass(times) {
        if (!times) {
          return;
        }
        setTimeout(function () {
              $cell.queue(function () {
                $cell.toggleClass(options.cellFlashingCssClass).dequeue();
                toggleCellClass(times - 1);
              });
            },
            speed);
      }

```
---
Fixing just entails changing inner funcs to e.g., `var foo = function bar () {}` instead of just `function foo () {}`

**Comment by bryevdv** [comment]
@mattpap your help with how to automate this in our build process would be very appreciated. I think some of them are in vendor code so maybe update or just change.

**Comment by bryevdv** [comment]
The "lex" one is from `node_modules/spdx-expression-parse/parser.generated.js`

**Comment by bryevdv** [comment]
So `prelude.js` can just be fixed, and the vendored SlickGrid just updates. I'm not sure how to fix the "spdx" one it's not a stated dependency in `package.json` so not sure how we could try to update. I guess  we could fork it and use the fork like numbro. Alternatively, is there a gulp plugin that can just fix these automatically?

**Comment by bryevdv** [comment]
I'm also glad this only took like two hours of tedious digging to figure out the details of...

**Comment by bryevdv** [comment]
Was hoping that 
```
eslint  --fix --rule '{no-inner-declarations: ["error"]}'  bokeh-compiler.js
```
would work, but I guess this is not one of the fixable errors.

**Comment by mattpap** [comment]
> node_modules/spdx-expression-parse/parser.generated.js

Before we jump to conclusions with automation, etc., we should figure out why this is in the bundle at all. It looks like it shouldn't be there. Second thing is that, I think, we want to go away from bundling the compiler, so this will get fixed before 1.0 anyway.

**Comment by mattpap** [comment]
> Notebook requires "strict" mode

Is this a new thing in the notebook? What's the severity of this issue, e.g. can use bokeh in notebook version >= m.n?

**Comment by bryevdv** [comment]
Not sure. This started a few months ago at least, and it makes debugging in the notebook impossible.

**Comment by bryevdv** [comment]
I should add, I went through and deleted every `use strict` in our built sources by hand at one point, and still had the problem, so it definitely seems to be an issue with a change in the notebook, or our use of it. For instance, we did make a change here https://github.com/bokeh/bokeh/commit/426c61a3dd2e129c508212b4883a9975ff5df5e2 to use `application/javascript` perhaps that triggers more strict evaluation.

**Comment by bryevdv** [comment]
> Before we jump to conclusions with automation, etc., we should figure out why this is in the bundle at all. It looks like it shouldn't be there. Second thing is that, I think, we want to go away from bundling the compiler, so this will get fixed before 1.0 anyway.

I'm not sure it was in the bundle. There were only three reported instances of nested functions. I just fixed them all. This one may have ben superfluous, I didn't repeat the check without the compiler code changed to test that theory, though. I agree with not bundling the compiler as a goal, though.

**Comment by bryevdv** [comment]
FYI I think a test that checks this particular rule using eslint would be appropriate. We could start with this one, and add more checks over time.

**Comment by bryevdv** [comment]
Well I was hoping fixing `prelude.js` and the vendored widget files would suffice but that is not the case. If I leave `bokeh-compiler.js` as is the error still occurs. Fixing that file "by hand" removes the error, or alternatively applying this patch removes the error:
```
diff --git a/bokeh/resources.py b/bokeh/resources.py
index 9691a10..70bc1ce 100644
--- a/bokeh/resources.py
+++ b/bokeh/resources.py
@@ -207,7 +207,7 @@ class BaseResources(object):
                  path_versioner=None, components=None):
 
         self.components = components if components is not None \
-            else ["bokeh", "bokeh-widgets", "bokeh-compiler"]
+            else ["bokeh", "bokeh-widgets"] #, "bokeh-compiler"]
 
         self.mode = settings.resources(mode);           del mode
         self.root_dir = settings.rootdir(root_dir);     del root_dir
```

But that would mean custom models wouldn't really work by default?  This is unfortunate. The only option I can think of as a short-term fix is to apply a custom text-processing step to "fix up" the `bokeh-compiler.js` file as a last step. Are there any better options? @mattpap

**Comment by bryevdv** [comment]
On the premise that it might be a useful start, I have pushed a branch that fixes the vendored files and `prelude.js` 

https://github.com/bokeh/bokeh/tree/bryanv/4363_notebook_unminified

If there is something quick and safe to finish this out, work we should do it.

**Comment by bryevdv** [comment]
sorry, that last one actually seems to be in `coffee-script/parser.js` which makes more sense.
