### ISSUE TITLE
Bokeh Server w/ multiple processes

### ISSUE THREAD

**Issue by quasiben** [bokeh/bokeh#4363]
Optionally run Bokeh Server with multiple process.  This is useful when scaling an application especially when there are larger computational loads

```
bokeh serve file.py --nprocs N
```

**Comment by bryevdv** [comment]
suggest `--num-procs` instead, we tend towards the slightly more verbose. i would also say the default should remain `1` and I guess `0` is passed along as-is to mean "as many as there are cores"

**Comment by quasiben** [comment]
Agreed
