### ISSUE TITLE
add user guide documentation for Title and LabelSet annotations

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4368]
Missing:
* add user guide documentation for Title and LabelSet annotations
* update Label annotation user guide docs

**Comment by bryevdv** [comment]
new `Label`/`LabelSet` docs:

<img width="960" alt="screen shot 2016-06-24 at 7 12 20 pm" src="https://cloud.githubusercontent.com/assets/1078448/16353431/baaefd5a-3a3f-11e6-8525-19cca6f9c5c9.png">

**Comment by bryevdv** [comment]
new `Title` section:
<img width="952" alt="screen shot 2016-06-24 at 9 28 04 pm" src="https://cloud.githubusercontent.com/assets/1078448/16354241/a12bdbba-3a52-11e6-9a13-75388f83cd3b.png">

<img width="830" alt="screen shot 2016-06-24 at 9 28 15 pm" src="https://cloud.githubusercontent.com/assets/1078448/16354240/a12b1d9c-3a52-11e6-9aee-52b63d9ba1c0.png">
