### ISSUE TITLE
Spaced hierarchical index

### ISSUE THREAD

**Issue by afonit** [bokeh/bokeh#4369]
from a discussion on the mailing list:
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/Lq5LX6yH-fU

---

Currently bokeh can have hierarchical indexes on plots, but they are slotted for each tick, see in this example:

``` python
import pandas as pd
import datetime
from bokeh.charts import Bar, output_notebook, show

output_notebook()

data = {
    'month': ['2016-01-01','2016-02-01', '2016-01-01'],
    'work_location': ['site_a', 'site_a', 'site_b'],
    'nps': [50.0, 33.3, -25.0]
}

df = pd.DataFrame(data)

p = Bar(df, values='nps', label=['work_location', 'month'])
show(p)
```

Produces the following plot:
![plot_examples](https://cloud.githubusercontent.com/assets/1798497/15556956/825a2280-229e-11e6-90ae-24c2c839ea18.png)

On the left is the current, on the right the axis is parsed visually so it is easier/quicker to interpret and see the groups.

Here is an additional example:
http://news.infragistics.com/cfs-filesystemfile.ashx/__key/CommunityServer.Discussions.Components.Files/265/4718.Capture.PNG

Again, just floating the idea as I think it lends visual power to the graph in making the content of the axis (when it is hierarchical like this) easier to parse than the current look.

**Comment by birdsarah** [comment]
Thanks for kicking this off @afonit, two frequent use cases for me are: categories and sub-categories, and then displaying increasing units of time (months, quarters, years).

**Comment by birdsarah** [comment]
Related: #3091. They're very closely related but I would say not a dupe.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/50)
