### ISSUE TITLE
Ability to pass your own aggregation function to the high level charts?

### ISSUE THREAD

**Issue by afonit** [bokeh/bokeh#4370]
``` python
import pandas as pd
import datetime
from bokeh.charts import Bar, output_notebook, show

output_notebook()

# defining a custom function to use in the aggregation
def nps(x):
    return round(sum(x)/len(x)*100,1)

data_base = {
    'month': ['2016-01-01','2016-01-01','2016-01-01','2016-01-01','2016-02-01','2016-02-01','2016-02-01', '2016-01-01',
             '2016-01-01', '2016-01-01', '2016-01-01'],
    'work_location': ['site_a','site_a','site_a','site_a', 'site_a', 'site_a', 'site_a', 'site_b', 'site_b', 
                      'site_b', 'site_b'],
    'nps': [1, -1, 1, 1, -1, 1, 1, 0, 1, -1, -1]
}

df_base = pd.DataFrame(data_base)
```

When working in pandas I will frequently do an aggregation like this:

``` python
final_output = df_base.groupby(['work_location', 'month']).agg({'nps': nps})
```

When you look at that  it produces a multi-index dataframe.

My first question is - am I correct in that I cannot plot that?  I have tried a few way and it shows 'nonetype' is not iterable (I am assuming because the 'work_location' does not fill every row in the index (although I am not sure of the internals and if that is what is throwing the error)).

So my next thought was, when working with the initial code, why not do this:

``` python
p_base = Bar(final_output, values=nps, label=['work_location', 'month'])
show(p_base)
```

and do the aggregation and plotting in one stroke.

The last bit of code fails though because instead of using nps for the 'values='  I need to use one of:

Available aggregations are:
- 'sum'
- 'mean'
- 'count'
- 'nunique'
- 'median'
- 'min'
- 'max'

http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#bar-charts

So, Is there a way to pass a custom aggregation function, such as nps as I included in the code above, into the 'values=' for the high level charts?  Or would that not make sense with the goal of bokeh?

Just trying to flesh this idea out and see if I am thinking about it properly and if it aligns with the goals of bokeh.

**Comment by birdsarah** [comment]
ping @fpliger @rothnic - any thoughts about this.

@afonit - have you seen: 
- http://nbviewer.jupyter.org/github/bokeh/bokeh/blob/master/examples/howto/charts/deep_dive.ipynb
- http://nbviewer.jupyter.org/github/bokeh/bokeh/blob/master/examples/howto/charts/deep_dive-attributes.ipynb
- http://nbviewer.jupyter.org/github/bokeh/bokeh/blob/master/examples/howto/charts/deep_dive-composite_glyphs.ipynb

I'm not sure they have what you need - just highlighting.

**Comment by fpliger** [comment]
@afonit @birdsarah If I'm not misunderstanding the point here you are correct.. there is no way to pass custom agg functions atm. It has been on the radar for a while and would be certainly very helpful. 

Regarding your example, yes, it is not supported but I'd think the natural syntax to match the current design would be:

```python
p_base = Bar(final_output, values='nps', label=['work_location', 'month'], agg=nps)
```
.

That said.. I didn't try the example so there may be some tweaks to skip the multi-index df issue.... Will try to take a look later today.

**Comment by afonit** [comment]
@fpliger After having read through https://github.com/bokeh/bokeh/blob/056433ebcdf5cde778241d2bb135301b801357c9/bokeh/charts/builders/bar_builder.py

I see the more Bokeh way to do it would be:

```python
import pandas as pd
import datetime
from bokeh.charts import Bar, output_notebook, show

output_notebook()

# defining a custom function to use in the aggregation
def nps(x):
    return round(sum(x)/len(x)*100,1)

data_base = {
    'month': ['2016-01-01','2016-01-01','2016-01-01','2016-01-01','2016-02-01','2016-02-01','2016-02-01', '2016-01-01',
             '2016-01-01', '2016-01-01', '2016-01-01'],
    'work_location': ['site_a','site_a','site_a','site_a', 'site_a', 'site_a', 'site_a', 'site_b', 'site_b', 
                      'site_b', 'site_b'],
    'nps': [1, -1, 1, 1, -1, 1, 1, 0, 1, -1, -1]
}

df_base = pd.DataFrame(data_base)

p_base = Bar(df_base, values='nps', label=['work_location', 'month'])
show(p_base)
```

I think the point I am making here is currently this works:
```python
p_base = Bar(df_base, values='nps', label=['work_location', 'month'])
```
And the default aggregation is agg="sum", so we change change that to another preset like mean:
```python
p_base = Bar(df_base, values='nps', label=['work_location', 'month'], agg='mean')
show(p_base)
```

What I am talking about here, in the python example at the top of this comment, is for the ability to pass a custom function as an argument to the 'agg' parameter like this (so it picks up the nps function I defined earlier):
```python
p_base = Bar(df_base, values='nps', label=['work_location', 'month'], agg=nps)
show(p_base)
```

**Comment by fpliger** [comment]
@afonit that's exactly what I commented.. at least, this was the intent :)

**Comment by afonit** [comment]
@fpliger yes, I must have misread it, sorry about the additional noise in this report.

**Comment by fpliger** [comment]
all good. Just wanted to actually check it's the case. Thanks!

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/58)
