### ISSUE TITLE
Problem getting ggplot 0.6.8

### ISSUE THREAD

**Issue by garyrob** [bokeh/bokeh#4374]
I'm an anaconda user.

According to https://anaconda.org/bokeh/ggplot, I should be able to do 
  conda install -c bokeh ggplot=0.6.8
to install that version of ggplot. I'm using OS X 10.11.5, and that page shows a badge for OS X-64. (I'm running 64-bit anaconda Python.)

But when I run that command, I get:
Error:  Package missing in current osx-64 channels: 
  - ggplot 0.6.8*

**Comment by bryevdv** [comment]
HI @garyrob looking at the actual files:

https://anaconda.org/bokeh/ggplot/files

it appears `0.6.8` is only available for linux. `0.6.5` is available on all platforms though. I'd say the reporting re: platforms/versions is a little misleading. Perhaps you can file an issue with anaconda.org? There may be some other channels that have this tho, `anaconda search ggplot` shows lots of results.

**Comment by bryevdv** [comment]
Also, just FYI please use the public mailing list for general support questions, and reserve the issue tracker for core library bug reports and feature requests. It will help us keep our sanity. :)
