### ISSUE TITLE
border_line property on css text annotations causes text wrapping on plot edges

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4376]
[Example](https://github.com/bokeh/bokeh/blob/master/tests/integration/annotations/screenshots/base__test_title__test_title.png) 

Issue:
Adding a border_line to a css text annotation (Label or Title) causes the text_box to increase in size by the line width (i.e. the box increases by the width of the border_line). On annotations that touch the panel edge, this causes line wrapping.

ping @birdsarah

**Comment by birdsarah** [comment]
It would be good to find a re-usable solution for this. I'd like to be able to add css props (fill and border) to Rows & Columns but border would have a similar problem.

Have you tried outline.

**Comment by bryevdv** [comment]
Original MRE is a 404, closing as `norepro`
