### ISSUE TITLE
Add selenium test of overlaid canvas and css boxes to make sure bk-canvas-overlays position doesn't change

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4377]
Previously, we had a regression where removing an empty div in bk-canvas-overlays causes a (1,1) shift in overlay pixel location. We should add a selenium test to catch future regressions here.

One solution would be a canvas and css BoxAnnotation with the same locations/dimensions and moderate alpha. If/when the overlay (or canvas) position shifts, this would cause a fairly distinctive image diff failure.

Obviously, giving the test a descriptive name with a descriptive docstring would be helpful.

ping @birdsarah

**Comment by birdsarah** [comment]
> giving the test a descriptive name with a descriptive docstring would be helpful

@canavandl - yes. this is very important.

**Comment by bryevdv** [comment]
After so long with no code to reproduce it's unlikely that this will happen.
