### ISSUE TITLE
Is title padding working? 

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4382]
Just confirm it's working as expected. 

Also see #4381.

**Comment by canavandl** [comment]
Apart from bug that is fixed in #4411, `title_padding` appears to work as expected.

**Comment by birdsarah** [comment]
I'd prefer to close this when we've addressed the naming issue too.....

**Comment by damianavila** [comment]
@canavandl was the naming issue reference by @birdsarah solved at #4411 as well?

**Comment by bryevdv** [comment]
@birdsarah @canavandl can you comment? I think the answer is that this can be closed? `title_padding` and `title_align` was there anything else to decide? (Or is it some other different naming issue?)

**Comment by birdsarah** [comment]
I think `title_padding` should be renamed to `title_offset` (or something similar), but that is covered under #4381.

We may want to tweak the docstring which currently reads "Offset value to apply to the title alignment coordinate." In particular it's important to note that this number always pushes out the left of the text, so if the title_location is "right" and the `title_padding=10`, text will disappear off the bottom of the plot (see below), but you can use `title_padding=-10` in that case, so I think it's fine.

<img width="453" alt="screen shot 2016-06-15 at 7 33 50 am" src="https://cloud.githubusercontent.com/assets/1796208/16083878/85bb419c-32cb-11e6-960f-d1b43f3276ad.png">

**Comment by birdsarah** [comment]
happy to close this after the docstring pr gets merged.
