### ISSUE TITLE
Is min_border working?

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4383]
Original issues #3563, and was closed with early layout PR. Want to confirm its still working with #4392

**Comment by almarklein** [comment]
Nope, does not work. Looking into it.

**Comment by almarklein** [comment]
No, my mistake, I overlooked the line in the test code that sets the plot's `min_border` attribute. I tried all sorts of combinations of `min_border` and `min_border_left` etc. and all seems fine. Implementation LGTM too. Closing.
