### ISSUE TITLE
Help tool is not de-duplicated in ToolbarBox (gridplot toolbar)

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4385]
<img width="697" alt="screen shot 2016-05-30 at 2 29 03 pm" src="https://cloud.githubusercontent.com/assets/1796208/15658581/e703f5da-2672-11e6-9799-68f394cb49bf.png">

```python
import numpy as np

from bokeh.plotting import figure, gridplot, output_file, show

n = 50

x = np.linspace(0, 4*np.pi, n)
y = np.sin(x)

tools = "pan,wheel_zoom,box_zoom,reset,save,crosshair,help"

l = figure(title="line", tools=tools, plot_width=300, plot_height=300)
l.line(x,y, line_width=3, color="gold")

aw = figure(title="annular wedge", tools=tools, plot_width=300, plot_height=300)
aw.annular_wedge(x, y, 10, 20, 0.6, 4.1, color="navy", alpha=0.5,
    inner_radius_units="screen", outer_radius_units="screen")

bez = figure(title="bezier", tools=tools, plot_width=300, plot_height=300)
bez.bezier(x, y, x+0.4, y, x+0.1, y+0.2, x-0.1, y-0.2,
    line_width=2, color="olive")

q = figure(title="quad", tools=tools, plot_width=300, plot_height=300)
q.quad(x, x-0.2, y, y-0.2, color="tomato", alpha=0.4)

# specify "empty" grid cells with none
p = gridplot([[l, None, aw], [bez, q, None]])

output_file("grid.html", title="grid.py example")

show(p)
```

**Comment by birdsarah** [comment]
the problem is missing bit of code in `models/tools/toolbar_box.coffee` `_merge_tools`

**Comment by bryevdv** [comment]
Ping @mattpap @birdsarah This diff fixes the problem (on the assumption that at most one help tool is really ever needed), but maybe there is a better way:
```
diff --git a/bokehjs/src/coffee/models/tools/toolbar_box.coffee b/bokehjs/src/coffee/models/tools/toolbar_box.coffee
index 8d255f3..259b39a 100644
--- a/bokehjs/src/coffee/models/tools/toolbar_box.coffee
+++ b/bokehjs/src/coffee/models/tools/toolbar_box.coffee
@@ -87,6 +87,9 @@ class ToolbarBoxToolbar extends ToolbarBase.Model
           @gestures[event_type].tools.push(proxy)
           @listenTo(proxy, 'change:active', _.bind(@_active_change, proxy))
 
+    if @help.length > 0
+      @help = [@help[0]]
+
     for tool_type, tools of actions
       if tools.length > 0
         @actions = [make_proxy(tools)]
```

**Comment by birdsarah** [comment]
>  This diff fixes the problem (on the assumption that at most one help tool is really ever needed)

That assumption is valid if you're in the merge_tools method. Because the whole purpose of that method is de-deduping tools to one. I can't tell from your diff if that's where you've put this.

This solution doesn't follow the pattern of the other tools, I think that's fine given what the button does. But you could add some more checks in there to see whether the passed in tools have different help urls. For example the save button will save a picture for every plot in your grid. I don't think we want to open a tab for every plot in the grid, but do we want to warn if we squashed other urls?

**Comment by birdsarah** [comment]
I'm not sure what the old gridplot toolbar behavior was.
