### ISSUE TITLE
Missing layout tests

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4388]
No tests were written for:
- models/layouts/box.coffee
- models/tools/toolbar_\* - especially _init_tools and _merge_tools

box.coffee is mostly @havocp's layout algorithm. If we don't get round to writing tests, we should consider having it as a vendored file to discourge people from editing it.

The toolbarbox code was copy-pasted from the old gridplot.

In addition the python-side `layouts.layout` and `layouts.gridplot` are untested - but that module still needs some work / discussion so waiting for it to settle before testing.

**Comment by birdsarah** [comment]
This is definitely a very high priority but does not need to make it into 0.12 as it doesn't affect users.

**Comment by bryevdv** [comment]
I am going to hijack this issue to add tests for things marked "needs test" in #8085

**Comment by bryevdv** [comment]
The new baselines tests cover every example in minute detail

**Comment by mattpap** [comment]
I will consider this completed. Tests for certain code paths, like toolbar and gridplot, were added in various PRs, and other are not relevant anymore.
