### ISSUE TITLE
Extend functionality of box_ar & height_ar mode

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4389]
Currently for box_ar and height_ ar to function a plot with that mode needs to be wrapped in a layout with box mode on it.

Further more, box_ar only works for a single plot in a container.

This needs to be documented and improved.

**Comment by birdsarah** [comment]
@bryevdv - we should probably re-test if this is still true, but I see no reason why it wouldn't be. This needs to be well-explained for 0.12.

**Comment by bryevdv** [comment]
These modes don't exist anymore.
