### ISSUE TITLE
Legend is too tall (and maybe too wide) if more than two items

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4390]
See `examples/charts/file/scatter_multi.py` - at two or three legend items, the legend height is correct, but as number of legend items increases, the legend height increases inappropriately (but seemingly in proportion to the increase)

**Comment by almarklein** [comment]
@birdsarah Looked into it. Problem is not that legend is too hight, but that the items are not correctly divided in the available space. 

One thing that surprises me is that the `legend_spacing` is *also* used as padding. I.e.  the total padding is a combination of spacing and padding. This seems not how it is supposed to be. I am halfway in fixing that, but it seems so consistently applied that before I continue, I'd like to make sure we're on the same page about this.

**Comment by almarklein** [comment]
For reference, our docs say on `legend_spacing`: "Amount of spacing between legend entries."

**Comment by canavandl** [comment]
This line also doesn't work as intended: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/legend.coffee#L22-L24

`get_text_height(@visuals.label_text.font_value())` returns an object not a number

**Comment by birdsarah** [comment]
Thanks for looking into this. I needed to make a couple of changes for off-canvas to work, then thought I'd make a couple of changes for styling defaults, the found the code a little messy and un-tested and realized I shouldn't get sucked into it. I can't remember if i'm responsible for padding and spacing being the same (which i agree they shouldn't be). I think all clean-up would be great. The main thing i was hoping the new defaults would do is to give legend entries a little more breathing room than they had before.

**Comment by almarklein** [comment]
Thanks @canavandl, nice catch. I will fix that while I am in there.

**Comment by almarklein** [comment]
Also, the padding seems to be used as the margin as well ...
