### ISSUE TITLE
Layout - the clean-up

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4392]
PR #4343 got epic, so we want to merge as soon as possible. This issue collects a series of other issues that can be tackled as stand-alone PRs which clean-up either known bugs or follow-on features related to layout.

Note - this is a zenhub epic - please install zenhub plugin (free) to be able to see all the related issues: https://www.zenhub.io/

**Comment by birdsarah** [comment]
MIGRATION NOTE

The following examples had to be changed in order to run:

```diff
examples/app/fourier_animated.py
+curdoc().add_root(layout)

examples/app/selection_histogram.py
+curdoc().add_root(layout)

examples/app/timeout.py
+curdoc().add(p)

examples/plotting/server/animated.py
-session.show()
+session.show(p) 

examples/plotting/server/geojson_points.py
-session.show()
+session.show(p) 

examples/plotting/server/line_animate.py
-session.show()
+session.show(p) 

examples/embed/embed_responsive_width_height.py
+ complete overhaul the js method is gone and you now use sizing_modes to achieve the same
```

For server there were two types of fixes due to auto-magic going away (but allowing use of figure or Figure).

For the embed_responsive_width_height. This is a complete change. If anyone was using the JS `get_size_for_available_space` method (introduced in 0.11) - then they're going to have to change their code. I don't think many people are using this, and I consulted with @almarklein to make all these changes and to make sure good alternatives are available. He may be able to help write a migration note for the removal of this method.

ping @bryevdv

**Comment by bryevdv** [comment]
It looks like almost all the issues in this Epic are closed, I'm going to close this one, let's continue going forward in the the "Focus" epid for layout
