### ISSUE TITLE
Investigate / describe performance issues

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4395]
We have noticed that bokeh is slowing down - especially in the notebook. We need to investigate and describe this against 0.10 and 0.11.

Some thoughts:
- ~~the single solver on the document may be causing slow downs in the notebook - do we need multiple documents in the notebook~~
- there is more rendering happening than needs to - investigate where the listeners are coming from and pair down to the minimum

**Comment by bryevdv** [comment]
Another possibility to investigate to refine performance: https://github.com/bokeh/bokeh/pull/4171#issuecomment-218715556

**Comment by birdsarah** [comment]
The over-render seems to have been curtailed through a few recent PRs (the bug in throttle, and better initialization). One remaining issue is that we seem to need to call resize on document twice. See note on document.

**Comment by birdsarah** [comment]
Need to write this up properly, but quick bullet points:

* The notebook makes a NEW JS document per output cell. So everytime you run show you get a brand-new JS-side document, with a new solver, and all the constraints etc. need to be added.
* Because the python side only has one document then all the roots were coming down the pipe, all were being reinitialized in every cell even though we're only looking at one root in a given cell. 

This had the effect of:
* causing every cell to take the time it would take to load every root in the document even though only one is showing
* causing re-running a notebook to take longer and longer, because more and more roots are being added to the document (I think there's an open issue for this)
* causing duplicate edit variables when you try and re-show a cell that has widgets in it #4506 (i don't actually understand why this one happens, but i'm guessing widgets weren't properly cleaning up after themselves)

#4563 fixes this in a very trivial manner.

Ping @havocp need your thoughts and eyes on this issue.

----

There may be more solver optimizations

----

I noticed when profiling the JS that LinearAxis is taking up a lot of time. That might be because there are lots of them, but maybe there's an inefficiency in the code there. Could do some digging.

**Comment by bryevdv** [comment]
The axis time is due to text measurement and rendering. An improvement I started but never merged was a hidden canvas for measuring text so that all the ctx changes to set text properties  don't have to happen over and over.

**Comment by damianavila** [comment]
@nleclercq, I think you have things to add here (experience with this problem, we just talk a little bit at JupyterCon). I think it would be valuable if you share your issues and question here.
