### ISSUE TITLE
API - Name the responsive modes.

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4396]
There are currently 5 modes: `fixed`, `box`, `width_ar`, `height_ar`, `box_ar`

@havocp @almarklein @bryevdv have all mentioned concerns with these being non-obvious.

To recap what these modes do:
* fixed - the plot is just the size of the specified width & height
* box - the plot fills the available size in it's box - causing the plot to stretch & squeeze however
*  width_ar - the plot fills the available width but maintains the aspect ratio (calculated from the specified width and height)
* height_ar - the plot fills the available height - but maintains the aspect ratio (calculated from the specified width and height)
* box_ar - the plot fills the available height or width while maintaining the aspect ratio (calculated from the specified width and height)

I would greatly appreciate naming suggestions from @bokeh/dev.

Secondly these modes are passed into the `responsive` parameter of any Layout object. Is that the right parameter name. In 0.11 we have `responsive=True/False` on Plot. I have kept and expanded this, but we don't have to keep this. We could have, for example, `mode` on the layout objects Row, Column. I think responsive is a good parameter, but just wanted to bring it up.

**Comment by electronwill** [comment]
Perhaps [fixed, box, width_ar, height_ar, box_ar] could be renamed to [fixed, stretch, scale_to_width, scale_to_height, scale]. And maybe listed and explained in the order [fixed, stretch, scale, scale_to_width, scale_to_height].

**Comment by bryevdv** [comment]
I have a very strong bias against more than one underscore in a variable name to begin with, and it gets even worse if there's only one or two characters in between like `_to_` it's just a real pain to type.

**Comment by electronwill** [comment]
Good point-- scale_width and scale_height may be better.

**Comment by almarklein** [comment]
+1 for `[fixed, stretch, scale, scale_width, scale_height]`.

**Comment by bryevdv** [comment]
Yup, those seem pretty decent.

**Comment by bryevdv** [comment]
Changed to `task` I will make a PR to change the names

**Comment by birdsarah** [comment]
I'm not yet happy with the names proposed. I'm still thinking it through and talked through some of it with @bryevdv. Will try and consolidate thoughts today/

**Comment by birdsarah** [comment]
First-up, I think it's important to articulate that the responsive modes are trying to capture a series of constraints:
1) respond to changes in parent size - yes/no - currently fixed / others
2) keep a fixed aspect ratio when resizing - yes / no - currently _ar for yes
3) dimension is constrained by parent 's width/height/both

Second, I agree that scale seems to be a more intuitive way of expressing the fixed aspect ratio. 

Having said that, I don't like the triplet of `scale`, `scale_width`, `scale_height`. I think it implies that `scale_width` and `scale_height` are some kind of specialization of `scale`. Whereas, what is after the _ is an independent constraint. 

If we like `scale_width` and `scale_height`, I think the third should be some variant of  `scale_both`, `scale_box`, `scale_widthheight` - more suggestions welcome.

However, I don't like `scale_width`. To me, it implies you're scaling the width when you're actually *constraining* the width and *scaling* the height. 

So although the suggestions look clean, when I actually think about them they don't make sense to me.

I want to come up with a constructive suggestion, but I'm finding of snippets of time during the day, so I just thought I'd start with getting this up.

**Comment by bryevdv** [comment]
I'm OK with `scale_both` tho I personally prefer `scale`

regarding the question: does the `_width` in `scale_width` mean that width is what **is** scaled, or what **is not** scaled? That is a common and it seems often unavoidable problem. I recall another library that had a function `map_screen` and I could never remember if it was mapping *to* the screen coords, or *from* the screen coords... That sucks, but what can you do? The alternative is much longer names. For an actual function I am definitely OK with much longer names. For a "string enum" like this, I am much less enthusiastic about `scale_according_to_responsive_width` because errors/typos in string names are much more of a pain to debug, I think even with our validation machinery that is still true. 

So I'd explain `scale_width` as:

> Scale the element to the largest width allowed while preserving the original aspect ratio

which seems OK?

A slightly more verbose option I guess is `scale_by_width` but I personally don't like how that looks or how (not) easy it is to type.

**Comment by almarklein** [comment]
Plus one for `scale_both`, it puts the triple in context IMO. I agree with Bryan that `scale_width` does not necessarily mean "scale the width". Though an alternative could be a verb that more precisely represents what is being done to the width, like `constrain_width` (though that one is rather long). I'm going to shut up now to avoid this discussion from going on forever.

**Comment by bryevdv** [comment]
Proposal as I understand it:
```
    fixed -> fixed
      box -> stretch
   box_ar -> scale_both
 width_ar -> scale_width
height_ar -> scale_height
```
With these descriptions in the docs:

* `fixed` elements are not responsive. They will retain their original width and height regardless of any subsequent browser window resize events.

* `stretch` elements are completely responsive (independently in width and height) and will expand to occupy all available space, *even if this changes the aspect ratio of the element*

* `scale_width` elements will responsively expand according to the width available, *while maintaining the original aspect ratio* 

* `scale_height` elements will responsively expand according to the height available, *while maintaining the original aspect ratio* 

* `scale_both` elements will responsively expand to according to both the width and height available, *while maintaining the original aspect ratio*

**Comment by birdsarah** [comment]
I think `stretch` should be `stretch_both`, because I can easily imagine adding a `stretch_width` and a `stretch_height` mode.

Your descriptions are excellent @bryevdv. I would change "expand" to "resize" because they may be contracting not expanding.

**Comment by bryevdv** [comment]
Sure, `stretch_both` seems OK. I will try to have a PR later today. 

I actually have one question about the operation of `scale_both`: does it always scale to the the *larger* or the *smaller* of the two possibilities? Concretely: imagine a "wide" screen, and a "tall" plot. Is the plot as wide as the sreen (causing some to hang off the screen at the bottom) or it as tall as the screen (causing not to use up all the space?) Should there actually be two modes here? Is the right name then `scale_min` or `scale_max` (whatever the policy happens to be now? could implement the other later)

**Comment by almarklein** [comment]
I think it should be the *smaller* in general, since you want the whole plot to be visible. Most cases where this is not the case, there will be a vertical (`scale_width`) or horizontal (`scale_height`) scrollbar. I am not sure if `scale_max` would ever make sense, since it implies there is no scrollbar, so there would be not way for the user to view all of the plot, except resizing the window.

**Comment by bryevdv** [comment]
I agree is should be smaller too, I'm just not sure offhand if that is the case so I wanted to ask. in which I'd want to just be completely explicit about that in the description of `scale_both`

**Comment by almarklein** [comment]
> I'm not sure why scale_max implies no scrollbar? I'm a pretty bad web dev tho

In the `scale_both` case (and also in `scale_min` and `scale_max`), the plot's size can be restricted by both width and height, which means that the plot's container has a certain finite width and height, thus is not scrollable in any direction. Unless there is a use case where the actual width/height of a scrollable container is determined by other content, and we want the plot to take up the full space ... seems rather unlikely?

**Comment by birdsarah** [comment]
> I actually have one question about the operation of scale_both: does it always scale to the the larger or the smaller of the two possibilities? 

Yes, it always scales to the smaller of the two possibilities. The height and width provide constraints and the most constraining wins - at least that's how it's meant to work!

**Comment by birdsarah** [comment]
I posted this on the PR, but putting here for completeness of the discussion:

I never really liked "stretch", and just had a mini-revelation: what about `fill_both` instead of `stretch_both`. To my mind, `fill` seems intentional, but `stretch` sounds bad.

The corresponding `fill_width` and `fill_height` would also still be correct names if we ever decide to implement them.

**Comment by pzwang** [comment]
After skimming this thread, that's the conclusion I came to as well,
although I was going to propose the terms "maximize_width" and
"maximize_height".

The reason I slightly prefer maximize over fill is because fill is
also used to mean something else in the plotting context, i.e. fill_color.

On Tuesday, June 14, 2016, Sarah Bird <notifications@github.com> wrote:

> I posted this on the PR, but putting here for completeness of the
> discussion:
>
> I never really liked "stretch", and just had a mini-revelation: what about
> fill_both instead of stretch_both. To my mind, fill seems intentional,
> but stretch sounds bad.
>
> The corresponding fill_width and fill_height would also still be correct
> names if we ever decide to implement them.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bokeh/bokeh/issues/4396#issuecomment-225810194>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAhLWO07GkGQ-BhfWueuEYvA42BkqbtGks5qLmKXgaJpZM4IoFXB>
> .
>


-- 
*Peter Wang*
*CTO, Co-founder*

**Comment by bryevdv** [comment]
My pref is for the "fill" versions or else just keep it as it is. "fill_width" is pretty clearly not about colors, at least to me.

**Comment by birdsarah** [comment]
Peter, you may have skimmed too quickly.  Are you proposing:

```
fixed -> fixed
box -> maximize_both
box_ar -> scale_both
width_ar -> scale_width
height_ar -> scale_height
```

I still prefer
```
fixed -> fixed
box -> fill_both
box_ar -> scale_both
width_ar -> scale_width
height_ar -> scale_height
```

I think `fill_` & `scale_` are better disambiguated than `maximize_` and `scale_`. 

But writing it like that I think that `stretch_` and `scale_` are more direct partners......

**Comment by birdsarah** [comment]
I'm torn, when writing it out, `stretch_` and `scale_` to me are naturally different partners.

But when writing a line of bokeh code I prefer `p = figure(sizing_mode='fill_both')` `p = figure(sizing_mode='stretch_both')`

Given my indecision. I think we should leave it at stretch.

**Comment by bryevdv** [comment]
I actually agree now, too. "stretch" and "scale" do seem complementary to me.

**Comment by birdsarah** [comment]
Ref: #4527 finished this work by splitting out responsive and sizing_mode.

**Comment by pzwang** [comment]
Ah, I did skim too quickly.  Per Sarah's comment, I think that scale and stretch are natural complements, but they mean different things.  I think that "scale_to_width" and "scale_to_height" are slightly more clear, because "scale_width" could mean "scaling the width, to match the maximum available height".  Does that make sense?

**Comment by bryevdv** [comment]
Yes, agree in principal but in this case I have a stronger preference for more brevity. I'm OK with long function name, but not so OK with long "string things"

**Comment by pzwang** [comment]
Sure, I can appreciate the logic behind that: users are going to type them in wrong, and won't get instant feedback on why the desired behavior is not working.

However, I'm literally serious when I say that as I look at this, I'm not entirely sure if `scale_width` means that the width will get scaled appropriate to match a maximized height, or if it means that the plot will take the maximal width, and scale the height to preserve aspect ratio.  I think perhaps I've reached semantic saturation on these terms...

Taking an alternative look at this: really, there are two independent settings we're talking about:

  * width_policy: `fixed`, `stretch`, or `scale`
  * height_policy: `fixed`, `stretch` or `scale`

If one is set to `stretch` and the other is set to `scale`, then this is similar to the `scale_*` settings suggested previously.  In the case when both are set to `scale`, then (I think) it's the equivalent of `box_ar`.  If both are set to `stretch`, then it's the same as `fill_both`.

Maybe trying to take the 3 x 3 = 9 possibilities and compressing them down into 5 modes is not the best approach, and that's what's confusing me?

**Comment by almarklein** [comment]
Putting that in a table:

|  | fixed   | stretch        | scale         |   
|----------------|---------|----------------|---------------|
| fixed          | "fixed" | ?              | -             |   |
| stretch        | ?       | "stretch"      | "scale_width" |   
| scale          | -       | "scale_height" | "scale_both"  |   

The cases that our current approach can't cover is the combination of fixed with stretch (as fixed with scale is the same as "fixed"), though these cases are probably very rare.

What about having the policy consist of a string with the policy-names for both width and height, and allow a single policy string if they have the same policy:
* "fixed" == "fixed_fixed"  (currently "fixed")
* "stretch" == "stretch_stretch" (currently "stretch")
* "scale" == "scale_scale" (currently "scale_both")
* "fixed_stretch" and "stretch_fixed" would be new
* "scale_fixed" and "fixed_scale" would be disallowed
* "stretch_scale" to stretch width while scaling height (currently "scale_width")
* "scale_stretch" to stretch height while scaling width (currently "scale_height")

**Comment by birdsarah** [comment]
Small edit what @almarklein has labeled "stretch" is "stretch_both" on master.

**Comment by pzwang** [comment]
Actually, fixed in one dimension but stretched in another, is very common.  Imagine categorical axis on one axis, and some timeseries or heatmap thing on the stretch axis...

I don't like the concatenated strings because it's too implicit.  It's not obvious that `fixed_stretch` is radically different than `stretch_fixed`, and that's really hard to remember.  If we're to do this, I'd rather use commas or semicolons or something.  (Even then, that still seems a little magical.)

**Comment by birdsarah** [comment]
I don't think the table is quite appropriate.

There are two missing / unimplemented modes at the moment `stretch_width` and `stretch_height` (or whatever we want to call them). Here's my description of the full-set:

* fixed - on_master
* stretch_width - width grows to fit available space | fix the height - not on_master
* stretch_height - height grows to fit the available space | fix the width - not on_master
* stretch_both - width and height grow to fit availalbe space - on_master
* scale_width - width grows to fit available space | scale the height - on_master
* scale_height - height grows to fit available space | scale the width - on_master
* scale_height -  width and height grow to fit availalbe space but proportions maintained - on_master (with limited suppoer)

**Comment by birdsarah** [comment]
> Actually, fixed in one dimension but stretched in another, is very common.

Agreed - that's actually how our toolbars work at the moment - I even discussed implementing the modes yesterday with bryan but there seemed to be higher priorities.

**Comment by birdsarah** [comment]
Copying and pasting an earlier comment I made:

I think the responsive modes are trying to capture a series of constraints:
1) respond to changes in parent size - yes/no - fixed / others
2) keep a fixed aspect ratio when resizing - yes / no - scale_ / stretch_
3) dimension is constrained by parent 's width/height/both

**Comment by birdsarah** [comment]
Rewriting what @pzwang wrote to reflect what's currently true on master.

There are two independent settings we're talking about:

  * width_policy: `fixed`, `stretch`, or `scale`
  * height_policy: `fixed`, `stretch` or `scale`

* If one is set to `stretch` and the other is set to `scale`, then this is `scale_width` or `scale_height`.
* In both are set to `scale`, this is `scale_both`.
* If both are set to `stretch`, this is `stretch_both`.

Follow-on thoughts:

What we don't currently support is if one is set to `fixed` and the other is set to `stretch`, that would be `stretch_width` or `stretch_height`.

What I don't quite have a vision of is what would it be/look like if one is set to `fixed` and the other to `scale`.

What I like about having string combos is that we can add modes as we have them, and it's less verbose. What I like about the independent settings is that I do think it can be more obvious to learn.

**Comment by almarklein** [comment]
>  It's not obvious that fixed_stretch is radically different than stretch_fixed

I agree.

> What I don't quite have a vision of is what would it be/look like if one is set to fixed and the other to scale.

I think that the one set to `scale` would scale with the other to keep the aspect fixed, but since the other is fixed, it would essentially be fixed as well.

**Comment by pzwang** [comment]
> I think that the one set to scale would scale with the other to keep the aspect fixed, but since the other is fixed, it would essentially be fixed as well.

Sorta kinda not really... :-)

If the `fixed` dimension is updated programmatically in code, then the `scale` dimension will update.  But neither respond to changes in the plot area/window size.

**Comment by birdsarah** [comment]
> If the fixed dimension is updated programmatically in code, then the scale dimension will update. But neither respond to changes in the plot area/window size.

That makes a lot of sense @pzwang - thanks! This is why we keep you around :D 

So, what's the result of all this. This issue was closed because `fixed`, `stretch_both`, `scale_both`, `scale_width`, `scale_height` were implemented. 

Before the next freeze we are not going to be able to implement, and do the careful testing that's needed on all the new modes that are implied by having:

*    width_policy: fixed, stretch, or scale
*    height_policy: fixed, stretch or scale

**Comment by bryevdv** [comment]
Here's my $0.02:

mixing `fixed` and `scale` is complicated, hard to explain, only effects things in a "time-dependent" sequence of events, and isn't currently supported in any case. I propose to ignore it, entirely, forever. `stretch_width` and `stretch_height` (implying the other dimension is fixed) make good sense, but can be added cleanly later to the set of names we already have. So then, I'd like to just keep the PR as it is currently.

**Comment by almarklein** [comment]
> If the fixed dimension is updated programmatically in code, then the scale dimension will update. But neither respond to changes in the plot area/window size.

That is a possibility, but as I think of it, this is a policy on what to do when the available width changes, not when the plot's size property changes. We also do not apply the `scale` policy when the plot's size is changed programatically, because it may well be the intention of the user to change the aspect ratio.

**Comment by anthonytw** [comment]
Did the `stretch_width` and `stretch_height` policies make it in to another feature request, or can one be opened? I searched around a bit but wasn't able to find any new issues created to address the additional layout policies combining `fixed` and `stretch` modes but those would be incredibly helpful in designing more complicated layouts, something that doesn't seem possible now unless a completely fixed, non-responsive layout is used.

**Comment by kernc** [comment]
@anthonytw I don't think anyone yet took implementing `stretch_width` and `stretch_height` policies upon themselves. As advised, I opened an issue for it: https://github.com/bokeh/bokeh/issues/8229
