### ISSUE TITLE
Update all examples to use new layouts

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4397]
Fairly self-explanatory. All the examples should be updated to remove HBox/VBox etc and to use the latest layout functions. Some should also include the new reponsive features..

ToDo:
- [ ] fix up spectrogram
- [ ] crossfilter
- [ ] surface3d (just needs to be added) 
- [ ] weather (some new pandas date serialization problem?!)
- [ ] embed/animated.py ("model not in session")
- [ ] embed/widget.py (buttons slightly covered, needs widgetbox?)

**Comment by andreagrant** [comment]
I'm working on this!

**Comment by birdsarah** [comment]
Given that we're undeprecating HBox & VBox - we can still keep some examples that use them.

**Comment by andreagrant** [comment]
Should I pick a few to revert to the original versions and then commit?

**Comment by bryevdv** [comment]
My vote is to change them all to Row/Column. Providing synonyms is not the same as having to prefer or endorse them.

**Comment by birdsarah** [comment]
@andreagrant, there are no changes you need to make to your PR. There are just lots of other examples in plotting etc that need to be updated and was just making a note to myseld.
