### ISSUE TITLE
Line-up ToolbarBox (toolbars on gridplots) with the top of axes

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4398]
ToolbarBox is the toolbar widget that's used on gridplots (but you can use independently). It doesn't line up with the plot frame - as normal toolbar does - which makes for an inconsistent visual experience when you switch from single plot to multiple plots.

**Comment by bryevdv** [comment]
Haven't gotten any other feedback about this, closing for low interest.
