### ISSUE TITLE
Make toolbar right by default?

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4399]
With the new toolbar and title set-up, there's an increased chance that the title and toolbar might clash with each other. 

If that clash does happen, a user can set `toolbar_sticky=False`.

None-the-less, I wanted to propose moving the toolbar default position to the right side of a plot.

See examples/charts/file/scatter_multi.py for an example where a default right toolbar would be more pleasing.

**Comment by bryevdv** [comment]
I'm ok with changing the location to the right, but two comments:

* need to make sure vertical presentation looks as good as horizontal (at least in the past it seemed slightly clunkier)
* should make an issue to try and have sticky toolbar and titles always behave well together (truncate title with a fade and tooltip, if there's overlap, or dodge automatically)

**Comment by mattpap** [comment]
> need to make sure vertical presentation looks as good as horizontal

In PR https://github.com/bokeh/bokeh/pull/4291 they are made to look the same. Additionally tooltips and dropdowns work so that they always appear on screen.
