### ISSUE TITLE
Implement a default min_interval and max_interval for zoom bounds

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4402]
PR #4349 from @almarklein implements the ability to constrain zoom to a min-interval.

I'd like to add on to this and implement a defaults for min_interval and max_interval. It frustrates me that I often have zoom enabled, inadvertently do a scroll down (to go down a page) and then I've zoomed my plot out to something unusable - and more often than not to the point where the plot breaks and shows nothing at all.

I would propose something pretty extreme - like 2 orders of magnitude compared to the initial range.

Having decided not to implement a max_interval for zoom, as you can do that with bounds; this would mean setting a min-interval default and a bounds default.

**Comment by almarklein** [comment]
> Having decided not to implement a max_interval for zoom

We eventually *did* implement `max_interval` because there might be use-cases where it proves useful (this being one of them).

**Comment by birdsarah** [comment]
Perfect :D Sorry for missing that.

**Comment by bryevdv** [comment]
I am going to close this. There has not been any additional input from users requesting it. Additionally, having defaults that can only be computed on the JS side (i.e. because DataRanges) is a complicating case I'd prefer to avoid.
