### ISSUE TITLE
Confirm that toolbar works under streaming (ref #3334)

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4406]
Just spotted #3334 when cleaning up layout issues and want to confirm that we haven't re-broken this. ping @bryevdv in case you know of an example off the top of your head to test this.

**Comment by bryevdv** [comment]
Tested `plotting/server/animated.py` and the toolbar works perfectly well.

**Comment by birdsarah** [comment]
Sorry - wrong button - thanks.
