### ISSUE TITLE
Hover broken if column names contain a dash

### ISSUE THREAD

**Issue by dhirschfeld** [bokeh/bokeh#4408]
Example notebook at https://anaconda.org/dhirschfeld/brokenhover
![image](https://cloud.githubusercontent.com/assets/881019/15660243/dfdabf0a-271c-11e6-9d35-e8b631ff8af3.png)

**Comment by dhirschfeld** [comment]
...or a slash.

**Comment by bryevdv** [comment]
That's annoying, but hopefully a simple fix. @dhirschfeld or anyone else that would like to investigate, the tooltip text is rendered here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee#L188

Note on current master, hit-testing on lines needs a fix after the layout PR: https://github.com/bokeh/bokeh/issues/4356

**Comment by bryevdv** [comment]
fix for line hover in #4409

**Comment by dhirschfeld** [comment]
With having to know javascript, coffeescript and the respective build and dev tools there's a somewhat large barrier to contribution to bokeh and, unfortunately I don't think I've got the skills/knowledge to fix the problem :/ Something I'm working on though...

**Comment by mattpap** [comment]
@dhirschfeld, @bryevdv, the existing behavior is by design. We have to draw a line somewhere as to what is a column name, at least without using additional syntax. By default, column names are presumed to be name literals, so no dash is allowed (it's no LISP). However, you can use (almost) arbitrary column names if you enclose them in curly brackets, so `@{col-1}` does the trick. Perhaps this requires more exposure in the documentation.

**Comment by bryevdv** [comment]
Well that's fine as it goes but then we should detect and warn and possibly offer an optional automatic conversion on serialization. The names are ok in Python; they will show up.

**Comment by dhirschfeld** [comment]
The curly braces trick does work so I'm now using that. It seems to me though that you'd *always* want to use curly-braces to allow for arbitrary names, in which case it may make sense to just treat the names as if they had been enclosed in curly braces.

As it is this trick probably deserves a prominent mention in the docs...

**Comment by bryevdv** [comment]
Actually I have not seen many questions about this. There is docs support, and also this issue that users can refer too. Going to go ahead and close
