### ISSUE TITLE
feature request: support multiple `tool_event` types on a single tool

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4418]
Bokeh uses hammer.js to manage touch gestures. Currently we have a set of interaction types (e.g. "pan", "tap", "move") that registers a set of touch interactions onto the tool. For example, setting `event_type="pan"` sets `_pan_start`, `_pan`, and `_pan_end` methods on the tool.

For developing custom tools via user-defined models, it'd be nice to support composite event_types so that more complex touch interactions can be supporting.

Use case: adding a draggable span onto a plot. It'd be nice to have "tap" move the span to the mouse location AND support dragging via the pan interactions.

**Comment by natezb** [comment]
I'm working on a custom tool right now and think this would be useful.

I've only just gotten into the BokehJS code, so someone more knowledgeable please correct me. I see two main things that need to be done:

1.  Modify `UIEvents.register_tool()` to allow registering multiple event types.
2. Allow a single tool to be the "active tool" for multiple event types (drag/scroll/tap).

The latter seems a bit tricky as you need to make the multi-event-type tool mutually exclusive to the other overlapping tools.

**Comment by bryevdv** [comment]
This was done with the work to add multi-gesture edit tools.
