### ISSUE TITLE
Webby Dashboarding Improvements and Automation (epic)

### ISSUE THREAD

**Issue by brianray** [bokeh/bokeh#4426]
This issue describes functionality to allow a full function Dashboard in Bokeh. Some of this may live outside of the project; however, if it fits the bokeh design model it would benefit from improvements or include a full functional dashboard model.  The Title was discussed with @bryevdv and #pycon sprint 2016 team in Portland OR USA.

NOTE: This issue was created after the Webby stuff one by @birdsarah IIRC I have not fully audited this PR so would like to improve this issue as needed.

A couple of features for this:
 * Layout configuration - allows boxes to be moved with presumably plots inside. Can they talk to eachother?
 * User Configuration - logins/admin ... or should this be some other project
 * Data  Browser (excel like in browser)
 * Style configuration - CSS love

**Comment by birdsarah** [comment]
@brianray - without significant extra detail on each of the areas for improvement you've suggested, there just isn't enough here to go on.

Feel free to re-open with extra details in one or all of the topics, or to open detailed sub-issues.
