### ISSUE TITLE
running bokeh on nonstandard port

### ISSUE THREAD

**Issue by andreagrant** [bokeh/bokeh#4428]
I'm trying to run two bokeh servers at once (to compare 0.11 examples with versions I'm working on in a fork). I'm specifying a different port number when I launch the second server (bokeh serve --port 5007)

When I actually run the example (python population_server.py), a blank browser tab at localhost:5007 opens and then it immediately opens a second browser tab at localhost:5006 with a session ID string. This second tab is also blank. 

When I tried pasting the ?bokeh-session-id=FPb2nzUUSvtelWjzQK57dDEiNxJL4cvhtugcqLHYg4ke from the :5006 session into the URL of the :5007, it again opened a blank tab in :5006

**Comment by bryevdv** [comment]
you'll need to modify `population_server.py` to connect to the server on the different port. By default `push_session` connects to the default server URL. For general support questions like this, we ask that please use the public mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

So that we can reserve the issue tracker for bugs and feature requests.

**Comment by birdsarah** [comment]
@bryevdv - I asked andrea to open this issue.

It looked like a bug to me.

**Comment by birdsarah** [comment]
@bryevdv I'm re-opening this. At the least we need a better user experience. The behavior was very confusing. We even tried `python population_server.py --port 5007` it initially opened 5007 and then it opened another tab in 5006.

**Comment by bryevdv** [comment]
I believe it needs something like this:
```
session = push_session(..., url="localhost:5007")
```

I guess we could add checking and command line parsing of `sys.argv` to `population_server.py`? But all it would do is pass that on to `push_session` and it seems like a distraction to me, personally. There's no way not automagically have this line up. If you want to connect to a server on something other than the default ip/port, you have to tell it what that is.

**Comment by bryevdv** [comment]
I don't think there is anything that can be done, the port needs to be passed to `push_session`. If user's want to add command line parsing to do that, that's great but I don't see that as something bokeh should try to do automatically. Of course, in general I would discourage `bokeh.client` over real bokeh server apps in any case.
