### ISSUE TITLE
JS Property mismatches

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4432]
* JS Plot object has leftover text mixin for title. This is causing "invalid attribute"  messages being sent to the server:

> 2016-06-02 14:58:37,499 JSON had attr 'title_text_alpha'  on obj <bokeh.plotting.figure.Figure object at 0x10d09c080>, which is a client-only or invalid attribute that shouldn't have been sent

* unit test for properties is somehow not catching these and should be fixed.

**Comment by mattpap** [comment]
Possibly because `Plot` has still `title` text mixin (redundancy I was speaking about in PR #4312).

**Comment by bryevdv** [comment]
@mattpap the `title` mixin is erroneous, I was going to remove it in this PR. But I also wanted to fix whatever is wrong with `generate_defaults.py`. This mismatch was not caught because no defaults were generated *at all* for `Plot`  in the output of that script.

**Comment by bryevdv** [comment]
Well, I do think it would be better to check more than just leaves, since there are intermediate classes that are not abstract, and that might have defaults overridden. But the main reason lots of examples are not getting properly tested:
```
    # special case for date time tickers, class hierarchy and attributes are handled differently
    if name = "DatetimeTicker" and k = "tickers"
      continue
```
