### ISSUE TITLE
Gallery Example Issues

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#4433]
When resizing a plot, toolbar doesn't snap to the plot.

<img width="627" alt="screen shot 2016-06-01 at 1 06 24 pm" src="https://cloud.githubusercontent.com/assets/1417520/15789805/b8c9fa74-2993-11e6-865c-972a88284d62.png">

When toolbar appear on the side of a plot, they overlap y axis ticks.

<img width="224" alt="screen shot 2016-06-03 at 1 57 40 pm" src="https://cloud.githubusercontent.com/assets/1417520/15789812/bc8672aa-2993-11e6-889f-c3a9ce6df167.png">

**Comment by bryevdv** [comment]
This is sort of fixed, the toolbar now moves, but the resize handle does not:
<img width="718" alt="screen shot 2016-10-04 at 8 43 23 pm" src="https://cloud.githubusercontent.com/assets/1078448/19098513/44285e4a-8a73-11e6-8377-800ca67c196e.png">

Also the plot flashed badly when resizing

**Comment by bryevdv** [comment]
This was fixed at some point (possibly #6384)
