### ISSUE TITLE
Persistent ID generation

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#444]
Is there some way that we can generate predictable ids for objects in bokeh?  Maybe give the IDs some sort of semantic meaning, tool-ZoomTool-1 instead of "aerq238..".  If we can generate consistent IDs,  bokeh plots that are checked into version control will diff much better.  It also might be easier to manipulate a JSON representation by hand.   This is a nice to have,  but it could make Bokeh more approachable.

**Comment by bryevdv** [comment]
I think we have settled on UUIDs for all id's and allowing some kind of alias, so closing this. Re-open if there is still more to discuss.

**Comment by mattpap** [comment]
Just to note, we can generate stable IDs (through a counter) for debugging purpose (which is super useful when e.g. diffing generated JSON representations).
