### ISSUE TITLE
Test the throttle function that is used to throttle rendering

### ISSUE THREAD

**Issue by clairetang6** [bokeh/bokeh#4456]
The throttle function found in `bokehjs/src/coffee/core/util/throttle.coffee` is used to wrap each plot canvas's render function so that calls to render can be limited. This means that instead of calling `render`, any code path that needs to end in a re-render can call `request_render`, which only calls render once in each throttling interval. 

One thing to note is that when there is a `request_render`, we check if a render has occurred recently. If one has occurred within the throttling window and no render is scheduled, then we schedule a render for later. If a render has not occurred recently, then (if request animation frame is available) we say that a render is "pending" and then wait a short amount of time before calling render. This wait period makes it possible for additional `request_render`'s to hop onto this render. 

Recently, [a bug was fixed](https://github.com/bokeh/bokeh/pull/4442) where multiple calls to `request_render` would result in two renders instead of one. This was because the second `request_render` would see that a render had occurred recently (even though really it was only pending and waiting in the short wait period) and schedule a second render. Once the second render was scheduled, any other additional `request_render`'s would see that a render was scheduled and those would correctly do nothing.

This issue is for adding a test to make sure that throttling render has the correct behavior.

**Comment by bryevdv** [comment]
closing as stale
