### ISSUE TITLE
Creating custom plot/graph templates interactively

### ISSUE THREAD

**Issue by mayankpj** [bokeh/bokeh#4458]
I wanted to help with creating the following feature(s):

Use Case: a function that provides user with a default template of a chart which can then be interactively styled (usual colors, fonts) just like excel ! and be saved for use later.
As a result
Other users might have a gallery of such community submitted templates they can readily use.

If anyone can suggest how above might be done, I am willing to work on the same.

**Comment by mayankpj** [comment]
I am wondering if I can create a notebook extension similar to scratchpad plugin which pulls up a separate pad on click of a small button at the bottom right of the page. On this pad, all options can graphically be selected. This would then populate a dictionary of these options which can then be passed over to any plot using PlotName(data_variables, other_variables, **dict)

I welcome any suggestions as I am new to JavaScript.

**Comment by bryevdv** [comment]
This question seems to have much more to do with jupyter than bokeh. I'm willing to believe it's possible but I have no experience with jupyter extensions. I think you might have better luck in the jupyter project mailing list. 

Bryan

**Comment by mayankpj** [comment]
Thanks Bryan for your response!

You are right that this might be specific to jypyter, so i had another idea.
Is it a feasible and easy option to instead create an app which may open a webpage where the user can easily select the given options and can also see them in action, it may provide them a dictionary which they can copy-paste and use further.

Do-able?, I would appreciate any advice on this.

**Comment by bryevdv** [comment]
This is still too vague for me to know what's really being proposed I think the mailing list might be a better place to solicit implementation ideas about specific use-cases, or to try and discuss ideas that are not at a more concrete stage yet

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
