### ISSUE TITLE
Improvement: Bokeh GridPlot to allow to span plots  in gridplot

### ISSUE THREAD

**Issue by akasolace** [bokeh/bokeh#4460]
for example  p = GridPlot(children=[[f1, None], [f2, f3]]) should produce:
[f1]
[f2] [f3]

whereas p = GridPlot(children=[[f1], [f2, f3]])  should produce
[ - f1-  ]
[f2] [f3]

I hope it is clear

**Comment by birdsarah** [comment]
@akasolace, this isn't clear - what do you mean by "< h1>"?

Having said that, I think we have recently implemented what you're looking for. Is this the kind of thing you wanted: https://cdn.rawgit.com/birdsarah/bokeh-miscellany/master/new_layout_tests/dashboard.html

If yes, it is in bokeh master and will be in the next release.

**Comment by akasolace** [comment]
I understand your confusion ... I just realized my message is not displayed at all as expected ... I will fix it

**Comment by birdsarah** [comment]
Great.  `p = GridPlot(children=[[f1], [f2, f3]])` is now supported via the new layout function. See the link above and the examples: https://github.com/bokeh/bokeh/blob/master/examples/howto/layouts/dashboard.py#L90

**Comment by birdsarah** [comment]
Closed with #4343
