### ISSUE TITLE
Remove deprecated API usage from docs examples

### ISSUE THREAD

**Issue by bsipocz** [bokeh/bokeh#4466]
#4343 introduced a few deprecations, but didn't update the working examples in the docs. 
I'm opening this issue only as a heads up as haven't seen it mentioned in the PR, nor in any other open issues.

Examples e.g.: in ``./sphinx/source/docs/user_guide/layout.rst`` and its references.

**Comment by bryevdv** [comment]
Thanks for the reminder! We usually refresh docs durning the freeze, so we will probably get around to this next week.
