### ISSUE TITLE
bokeh.charts.Horizon has wrong behaviour

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4474]
examples/charts/file/horizon.py yields:

<img width="837" alt="screen shot 2016-06-10 at 6 04 41 pm" src="https://cloud.githubusercontent.com/assets/2198981/15981046/21c82e9a-2f36-11e6-8bbe-2a5c3d5c1218.png">

For a true horizon chart, it's unclear (to me) if the other stocks (APPL and MSFT) should be overlapping in the IBM row or the IBM-only row should be the chart. But doing both is wrong.

**Comment by birdsarah** [comment]
Hmmm.....that look right to me. I'd been assuming this was correct and reading it as the magnitude of AAPL and MSFT was lower than IBM always. - by usually a factor of two or more.

**Comment by bryevdv** [comment]
should be re-opened in https://github.com/bokeh/bkcharts if applicable
