### ISSUE TITLE
Imshow slow in notebooks

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4487]
Quoting Irwin:

Basically, the Bokeh version of imshow is unreasonably slow in Jupyter notebooks -- it takes a few seconds to display any image. Bryan and I debugged it a bit on Saturday, and concluded that it was due to a combination of 1) Bokeh serializing an image as a NumPy array of NumPy arrays (i.e., one NumPy array per row) and 2) serializing these NumPy arrays to JSON.
While both should ultimately be fixed, we're hoping that 1) is a quicker thing to solve and makes it usable. 

cc @bryevdv @izaid @philippjfr

**Comment by bryevdv** [comment]
some references: 

https://github.com/bokeh/bokeh/pull/5429
https://github.com/bokeh/bokeh/issues/2204

Flattening the array but still sending as JSON did not offer any improvement, but an experiment with base64 offered very substantial speedups. I'm going to close this issue, as a general binary array feature implementation is covered by #2204
