### ISSUE TITLE
Plots are rerendered on resize even if responsive="fixed"

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4488]
This is a big performance regression. Nicely visible in e.g. `plotting/file/color_scatter`, where it spins CPU when I try to resize chrome's developer tools' panel. Going further, even if not `"fixed"`, then if no actual resize happened, there should be no rerendering.

**Comment by bryevdv** [comment]
I'd say that the most important thing first is to prevent re-render when layout is fixed. That would basically get us back to where things were. Seems like it should be a somewhat easy fix too, but I could be wrong.

**Comment by birdsarah** [comment]
closed via #4638
