### ISSUE TITLE
Undeprecate VBox and HBox

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4496]
I would like names `VBox` and `HBox` to stay, because they are more meaningful to from UI point of view than the new counterparts.

**Comment by mattpap** [comment]
Additionally, `Column` could be confusing with data column. This is similar issue, yet not that significant, as with canvas.

**Comment by bryevdv** [comment]
Ping @pzwang

**Comment by birdsarah** [comment]
`Row` and `Column` are meaningful to me (coming from a web-development background and are the common paradigm in web-page layout being rows & columns).

BUT I can totally appreciate that `VBox` and `HBox` are more meaningful to others, and I think we have a very diverse user base.

So, I'm +1 on un-deprecating `VBox`, `HBox`. 

But just to be clear, I would also:
* keep `Row` and `Column`
* keep the deprecation of the `vplot`, `hplot` and other old layout functions.

One outstanding question: `Row` and `Column` are going to get matching layout functions `row` and `column` - which will have the function of making sure everything inside them has the same layout mode, and can also handle other conveniences (like allowing `responsive=True/False` as well as `sizing_mode='...'`). Should we also make matching `vbox`, `hbox` layout functions? (My vote would be yes - to keep everything consistent).
