### ISSUE TITLE
Plot's mixin fill:border should be line:border?

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4497]
This has been for awhile like that, but border should be a line, thus should implement line properties.

**Comment by bryevdv** [comment]
The border around the plot is a potentially large area, full of axes and other things. Why would that be line props?

**Comment by mattpap** [comment]
In such a case it doesn't seem to be a border, but some kind of **area**. You are right, with the current understanding, using fill properties is desired, but we should really change this name to something more meaningful (I'm not sure what really). It's confusing to use the same name for multiple things in one code base, see:
```
$ git grep :border
bokehjs/src/coffee/models/annotations/label.coffee:  @mixins ['text', 'line:border_', 'fill:background_']
bokehjs/src/coffee/models/annotations/label_set.coffee:  @mixins ['text', 'line:border_', 'fill:background_']
bokehjs/src/coffee/models/annotations/legend.coffee:  @mixins ['text:label_', 'line:border_', 'fill:background_']
bokehjs/src/coffee/models/annotations/title.coffee:  @mixins ['text', 'line:border_', 'fill:background_']
bokehjs/src/coffee/models/plots/plot.coffee:  @mixins ['line:outline_', 'fill:background_', 'fill:border_']
```

**Comment by bryevdv** [comment]
pretty much all the `line:border_` above I think would be better as `line:outline_` but think it's too late to change these at this point. Feel free to re-open if you disagree and have a concrete proposal
