### ISSUE TITLE
Cannot select individual rects and link to different urls

### ISSUE THREAD

**Issue by tailintalent** [bokeh/bokeh#4500]
Hi I'm plotting with rect tool to plot a list of rectangles:
`p.rect(xs, ys, widths, heights, fill_color="#F2583E", line_color="black",tags=rect_tags)`

I want it to have the following function: for different rectangles above, each link to a different url.
I try the following function:
```
url = "http://www.colors.commutercreative.com/@color/"
taptool = p.select(type=TapTool)
taptool.callback = OpenURL(url=url)
```
but it links to all the rectangles and cannot specify individual ones.

If I change it to
`taptool = p.select(type=TapTool, tags="sometag")`
to specify specific tags, the link will not work.

Could you help me how could I achieve my function?Thanks!

**Comment by birdsarah** [comment]
Please post this question to the bokeh mailing list where hopefully you'll get lots of support.

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

We need to keep github for bugs, or feature requests.
