### ISSUE TITLE
output_notebook trouble

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#4502]
I've been experiencing a couple of different errors when trying to run `output_notebook`.

1.  stuck on "Loading Bokeh..." : in this scenario BokehJS never fully loads and the little bokeh icon never appears.  I've solved this by making sure BOKEH_RESOURCES is set to 'CDN', then restarting notebook server.  If the problem persists, then I've found making a copy of the notebook, then deleting the copy to somehow help.

2. Loading Custom Models in the notebook, I get the following error:
```
Loading BokehJS ...
Javascript error adding output!
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
See your browser Javascript console for more details.
```
This could be specific to my custom model, but the model works in other circumstances, just not in the notebook.

3.
bokeh-compiler.js 404 error: Sometimes I get an error on loading bokeh-compiler.js.  I'm not getting it to repeat at the moment, but was happening a bunch yesterday.

In my heart, I know these problems are deterministic, but I have trouble reproducing them, or they seem to randomly fix themselves, only to return after restarting the notebook or updating my examples.

**Comment by sutartmelson** [comment]
I am seeing similar behavior. 

Had the same stuck on "Loading Bokeh". The little icon still never appears. And it seems to only be kinda of successful when I does "load". It sometimes opens to a new window and sometimes opens to a new window as well as displays in the notebook. Creating a new notebook seems to temporarily solve it. But only for the first play. 

I'm not seeing the second or third error described above. 

I wish I could be more precise, but the errors are very inconsistent. At least, so far as I can tell.

**Comment by bryevdv** [comment]
Versions?

**Comment by sutartmelson** [comment]
Just pulled master an few hours ago. jupyter v4.1.0. running in chrome.

**Comment by bryevdv** [comment]
running with `BOKEH_RESOURCES=inline` ?

@brendancol were you trying to use unminified resources? There was an issue for that that was just closed the other day. What you describe sounds like that issue.

**Comment by sutartmelson** [comment]
yup, running with BOKEH_RESOURCES=inline.

**Comment by bryevdv** [comment]
So I have seen the icon not show up, but I have never seen it hang, or not actually load. Will have to investigate.

**Comment by sutartmelson** [comment]
I should have specified.. Just as @brendancol said, after ensuring BOKEH_RESOURCES was properly set, it would no longer hang.

**Comment by bryevdv** [comment]
well, I'm not sure what that means. If you are using a released (even a dev build) and want CDN resources, you should not need to set anything. In fact I can't really think of any time to ever set `BOKEH_RESOURCES=cdn`. OTOH if you are doing dev and want to use locally built BokehJS, the proper setting is `inline`

**Comment by sutartmelson** [comment]
Yeah, I set it to inline, not to CDN.

**Comment by bryevdv** [comment]
Oh, that seems expected and normal then. @brendancol can you elaborate on your exact situation?

**Comment by bryevdv** [comment]
I believe this was versions  mismatch / configuration. I have not been able to reproduce in any testing, Feel free to re-open with more info if the issue persists.
