### ISSUE TITLE
Date Picker widget is unstyled

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4503]
ref: #4204

`DatePicker` was made to function in a PR for the issue above, but CSS styling to make it look good is not getting applied. Suspect this is because jq-ui created the date picker components internally with hard-coded CSS classes that don't have our `bk-` CSS prefix.

Question: If all of our DOM elements now reside under a `bk-root` div, can we use that in our CSS selectors, and remove the CSS prefixing entirely?

**Comment by uberscientist** [comment]
It looks like the datepicker elements are being appended to the `<body>` and not the `<div>` with the "bk-root" class, so even after removing all the bk- prefixing it didn't get styled until I gave the body tag the "bk-root" class.  Not sure how we'd want to move forward from here, if there's a need to keep everything encapsulated in the bk-div I'd have to think a lot harder, the easy way would be removing the `.bk-root` from being a selector requirement for the widgets.

**Comment by mattpap** [comment]
This was fixed in PR #6335.
