### ISSUE TITLE
Problem rendering un-wrapped sliders

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4507]
~~At least in the notebook.~~ This appears to only be a notebook problem

<img width="1109" alt="screen shot 2016-06-15 at 5 52 30 am" src="https://cloud.githubusercontent.com/assets/1796208/16080370/5fd85d4c-32bd-11e6-9c44-ebbf1266eb3d.png">

``` python
r_slider = Slider(start=0, end=255, value=init_color_value, step=1, title="R"
```

**Comment by birdsarah** [comment]
See #3893 - naked slider with components doesn't work

See #3346: 

In notebook:
* If `show(Row(r_slider))` - works and responds to specified width of slider
* If `show(WidgetBox(r_slider))` - does not respect width of slider - need to set width on WidgetBox
* If `show(r_slider)` does not respect size

In file:
* If `show(Row(r_slider))` - works and responds to specified width of slider
* If `show(WidgetBox(r_slider))` - nothing shows!!! (open another issue?)
* If `show(r_slider)` slider doesn't really show.

**Comment by birdsarah** [comment]
Updated this to be a general bug around naked sliders.

**Comment by birdsarah** [comment]
So, the latest state of things - just before 0.12.0dev12

* do not expect `show(Slider())` to work
* do expect `show(widgetbox(children=[Slider()]))` to work
* do expect `show(row(children=[Slider()]))` to work (because row auto-wraps slider into a widgetbox)

**Comment by bryevdv** [comment]
This now works:
```
from bokeh.plotting import curdoc
from bokeh.models import Slider

curdoc().add_root(Slider(start=0, end=10, value=2, step=1))
```
