### ISSUE TITLE
Axis doesn't correctly know / pad its height including ticker labels

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4509]
See: #4471 

<img width="610" alt="screen shot 2016-06-10 at 10 04 11 am" src="https://cloud.githubusercontent.com/assets/1417520/15968917/4f938f38-2ef3-11e6-841f-93df637bd3f6.png">

@bryevdv noted on the above screenshot "seems like we might want to increase the min border a bit? that "10" tick label has basically no space above it and abuts the window edge directly. Or maybe there are other ideas."

My reading of this is that Axis doesn't know about the height of its axis labels and/or isn't adding a nice default padding. 

Increasing `min_border` would solve the default case. But if your axis ticker label font was large you'd have the same problem. So I would propose fixing Axis.

**Comment by bryevdv** [comment]
After more thought, I think the `min_border` route is the best one, even though it would require a small extra work by users. The alternative, if we let the transverse dimensions of tick labels inform the padding on the cross axis  is that the padding above plot bobs up and down as the tick moves towards and away from the edge. That seems like it would look really bad. If people need space, they are better off requesting a permanent amoutn with `min_border`. Closing with no action.
