### ISSUE TITLE
Jitter import missing, affecting PR #4490

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#4513]
In PR #4490, running *examples/plotting/file/jitter.py* gives this error:

```
File "jitter.py", line 3, in <module>
    from bokeh.models import ColumnDataSource, Jitter
ImportError: cannot import name 'Jitter'
```

**Comment by birdsarah** [comment]
How are the examples tests passing at all if this import is missing?

**Comment by birdsarah** [comment]
ping @bryevdv

**Comment by birdsarah** [comment]
(that was as question to the universe, not you, Maggie)

**Comment by canavandl** [comment]
It was being imported (but unused) into bokeh/models/formatters.py then carried into the project namespace from there. I tried to remove the import to silence flake8 warns and we found out it wasn't ever directly imported into the bokeh/models/__init__.py

**Comment by bryevdv** [comment]
@birdsarah `Jitter` was imported into `models.mappers`, which was then making it available to `bokeh.models` transitively. This PR (correctly) removed the unused import in `mappers` and that's what triggered the test failure.
