### ISSUE TITLE
Resize Tool Should Not Be In Defaults

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4520]
There are too many cases in which the resize tool causes issues with the plot, toolbar, and widgets. Because of this, it would be best to remove it from the default toolbar in order to prevent the average user from encountering bugs. If they really want the resize tool, they can add it back it.

Also, there has been talk of removing the resize tool completely.

**Comment by birdsarah** [comment]
Yes, I thought there was an issue somewhere we agreed, at least, to remove it on defaults.

**Comment by bryevdv** [comment]
There's a discussion here about removing it entirely: https://github.com/bokeh/bokeh/issues/4196 But there was no decision I see about that. In the mean time we should definitely remove it from default tools.
