### ISSUE TITLE
Shout louder on bokehjs build fails

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4525]
I totally missed a syntax error when I was building bokeh recently because I was working on 3 things at once and the console error was pretty subtle

<img width="643" alt="screen shot 2016-06-15 at 3 16 45 pm" src="https://cloud.githubusercontent.com/assets/1796208/16099286/537813f4-330c-11e6-85ce-8410ef111ef9.png">

I think it shouldn't say "...Success!" at the top in this case.

**Comment by bryevdv** [comment]
Yes the intent was that it report failure, I think it used to, but maybe my checks on the subprocess are incomplete, or something else somewhere else changed.
