### ISSUE TITLE
Remove "legend" prefix in some of legend's properties

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4526]
Specifically: `legend_margin`, `legend_padding`, `legend_spacing`. See discusion in #4511.

**Comment by birdsarah** [comment]
I actually think there's a bunch of clean-up for legend properties.

Here they all are:
```python
    location = Either(Enum(LegendLocation), Tuple(Float, Float),
        default="top_right", help="""
    The location where the legend should draw itself. It's either one of
    ``bokeh.core.enums.LegendLocation``'s enumerated values, or a ``(x, y)``
    tuple indicating an absolute location absolute location in screen
    coordinates (pixels from the bottom-left corner).
    """)

    orientation = Enum(Orientation, default="vertical", help="""
    Whether the legend entries should be placed vertically or horizontally
    when they are layed out.
    """)

    border_props = Include(LineProps, help="""
    The %s for the legend border outline.
    """)

    border_line_color = Override(default="#e5e5e5")

    border_line_alpha = Override(default=0.5)

    background_props = Include(FillProps, help="""
    The %s for the legend background style.
    """)

    background_fill_color = Override(default="#ffffff")

    background_fill_alpha = Override(default=0.95)

    label_props = Include(TextProps, help="""
    The %s for the legend labels.
    """)

    label_text_baseline = Override(default='middle')

    label_text_font_size = Override(default={ 'value' : '10pt' })

    label_standoff = Int(5, help="""
    The distance (in pixels) to separate the label from its associated glyph.
    """)

    label_height = Int(20, help="""
    The minimum height (in pixels) of the area that legend labels should occupy.
    """)

    label_width = Int(20, help="""
    The minimum width (in pixels) of the area that legend labels should occupy.
    """)

    glyph_height = Int(20, help="""
    The height (in pixels) that the rendered legend glyph should occupy.
    """)

    glyph_width = Int(20, help="""
    The width (in pixels) that the rendered legend glyph should occupy.
    """)

    legend_margin = Int(10, help="""
    Amount of margin around the legend.
    """)

    legend_padding = Int(10, help="""
    Amount of padding around the contents of the legend.
    """)

    legend_spacing = Int(3, help="""
    Amount of spacing between legend entries.
    """)

    legends = List(Tuple(String, List(Instance(GlyphRenderer))), help="""
    A list of tuples that maps text labels to the legend to corresponding
    renderers that should draw sample representations for those labels.
    .. note::
        The ``legends`` attribute may also be set from a dict or OrderedDict.
        If a dict is used, the order of the legend entries is unspecified.
    """).accepts(
        Dict(String, List(Instance(GlyphRenderer))), lambda d: list(d.items())
)
```

Some thoughts: 
* location: I need to re-look into this, but i remember this annoyingly clashing with wanting to set location somewhere else..
* orientation: ok - although a little obtuse given what it does; and we use orientation differently internally when talking about axes and other things that can rotate based on their position. what it  does is put the legend in a row or a column - maybe layout would be better?
* border_: fine
* background_: fine
* label_standoff: I would scrap this in favor of label_padding - that operates like legend_padding; and/or could add a label_offset like title has
* label_height: as above (height and width are specified by the text props and then padding gives extra whitespace)
* label_width: as above
* glyph_height: keep - but add a glyph_padding
* glyph_width: as above
* legend_margin: to margin - as per this issue title
* legend_padding: to padding - as per this issue title
* legend_spacing: scrap - this can be handled with label_padding
* legends: I find legend.legends super confusing. propose legend_names or name_map or something more verbose

**Comment by almarklein** [comment]
![](https://docs.google.com/drawings/d/1CPaCCEdIsmP7GKojzeSrs6X4M4LBEPNmPKLKiz9iHpc/pub?w=450)

I agree we should get rid of `label_height` and `label_width`, since the text size is measure anyway. But I don't like the idea of `label_padding`, as it would mean that its padding would contribute to the legend padding. Moreover, making legend_padding (and glyph_padding) the only mechanism by which to control both the distance between glyph and label (i.e. `label_standoff`) and spacing, would be problematic for horizontal layouts where you generally want a (much) higher spacing than standoff.

With `label_width` and `label_height` removed, we're left with just 4 label-prefixed props, which I'd propose to rename:
* label_props -> text_props (same as in Label. btw, why does Title not have this?)
* label_text_baseline -> text_baseline
* label_text_font_size -> text_font_size (same as in Title)
* label_standoff -> just standoff, or perhaps text_offset?

> orientation: [...] we use orientation differently internally when talking about axes and other things that can rotate based on their position.

I think orientation is ok. To me it sounds exactly what it does, since its the same wording as in orientation of box and splitter layout in e.g. Qt and Phosphor. We also use `orientation` in `Slider` and in `Axis.major_label_orientation` (both `Enum("horizontal", "vertical")`).

> I find legend.legends super confusing. propose legend_names or name_map or something more verbose

I don't like these as they're not just names, nor is it strictly a map. What about `items` or `legend_items`?

**Comment by almarklein** [comment]
ping @birdsarah

**Comment by birdsarah** [comment]
I love that picture - thanks!

In that context I think `label_standoff` makes sense.

`legend.items` seems good to me.

"why does Title not have this" - we agreed that `Title` would have a simplified subset of properties. If you want to get all fancy, you can use Label.

**Comment by mattpap** [comment]
That will be a lot of deprecation warnings.

**Comment by birdsarah** [comment]
make `Legend.items` a list of `LegendItems`.

```python
class Legend(Annotations):
    items = List(LegendItem)
    # other legend props ...

class LegendItem(HasProps):
    label = StringSpec
    renderers = List(GlyphRenderer)
    # VALIDATION: all renderers.data_source must match
    # VALIDATION: if label is field, it muse be in renderers[0].data_source

class GlyphRenderer(Renderer):
    # No change from current glyph renderer 
```

See #5228 for the full background and the bigger picture of where this might go.

**Comment by birdsarah** [comment]
Hi, after looking at this a bit more, I think the following:
* change the items with legend_ prefix
* keep the `label_props` items because I think in future we may well want to add a legend title and their would be a matching set of `title_props`
* I also like keeping `label_with` and `label_height` as it lets people make the legend bigger should they wish too.

#5229 implements just these changes
