### ISSUE TITLE
Link to CSS colors in docs is broken, link address changed

### ISSUE THREAD

**Issue by cbcoutinho** [bokeh/bokeh#4530]
I was looking for all available colors in bokeh today when I came across the docs [here](http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#specifying-colors), where the following tries to go to w3schools.com; however, it is broken:

Specifically, this is broken:
   any of the [147 named CSS colors](http://www.w3schools.com/cssref/css_colornames.asp), e.g 'green', 'indigo'

I found the correct link to w3schools.com - it looks like they changed the link on their side.

http://www.w3schools.com/colors/colors_names.asp

**Comment by bryevdv** [comment]
Thanks for the catch @cbcoutinho would you be able to submit a PR to fix this? This is the file to update:

https://github.com/bokeh/bokeh/blob/9491d517a84edc528ac84970cb338b5c24ac1d66/sphinx/source/docs/user_guide/styling.rst

**Comment by cbcoutinho** [comment]
Ok I edited the file associated with the error. I'm not sure if I did the PR correctly - let me know if I need to change anything.

**Comment by bryevdv** [comment]
PR was perfect, thanks
