### ISSUE TITLE
Run test_code_quality with flake8 group

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4533]
The test_code_quality seems like it naturally belongs in the flake8 test group.

This was my travis run when I had a code_quality violation:
<img width="806" alt="screen shot 2016-06-16 at 8 41 40 am" src="https://cloud.githubusercontent.com/assets/1796208/16123013/39716eb4-339e-11e6-8e54-36223d77a1ed.png">

I think I would be clearer to have the unit tests passing but the flake8 group failing. We could rename the flake8_docs group to code_quality_docs too.

**Comment by birdsarah** [comment]
ping @mattpap

**Comment by bryevdv** [comment]
Agreed all code quality / flake tests should go in one test run

**Comment by bryevdv** [comment]
I have a PR for this in process that adds a `quality` set of tests to pytest for this and flake8
