### ISSUE TITLE
LassSelectTool Callback Not Declared

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4535]
Consistently having plots with the lasso tool such as the examples linked_brushing.py and color_scatter.py not displaying and throwing 'Error: LassoSelectTool.set('callback'): callback wasn't declared' in JS console in the latest dev build.

**Comment by bryevdv** [comment]
I think this is a version mismatch issue. The last dev build did not have the new callback added yet, so if you are running out of the repo, but using CDN resources, you'd see this. There is a new dev build later today that will have the change. Let's see if that solves things.

**Comment by bryevdv** [comment]
examples working on `0.12.0dev12` I think it was just a config issue, closing.
