### ISSUE TITLE
How to get port for cloud foundry?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#4545]
In order to deploy Bokeh Application to cloud foundry, I need to get the port number from the cloud environment. Servers such as Spyre and Flask can get port for Cloud Foundry programmatically, How can I get port for cloud foundry in Bokeh Application. My Bokeh application ends with "
curdoc().add_root(vbox)"
Here is Spyre and flask servers:
# Need to specify port for Cloud Foundry
port = int(os.getenv("PORT", 9099))
app = SafeZoneApp()
app.launch(port=port, host='0.0.0.0')

**Comment by bryevdv** [comment]
Hi @charleywan2004 we reserve our issue tracker for bug reports and feature requests. Please take general support questions such as this to the public mailing list (where there is also a bigger pool of people who can potentially help):

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh
