### ISSUE TITLE
Minified inline resources returns bad javascript

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#4553]
When using
```python
res = Resources(mode="inline", minified=True)
```
`res.js_raw` returns bad JavaScript, resulting in an `Uncaught SyntaxError: Unexpected token >` in the browser. I'm am transporting the scripts over JSON and inserting it into the DOM with jQuery if that will help to reproduce the bug
```python
return Response({"scripts": res.js_raw, "styles":res.css_raw })
````
```javascript
var $appends = $('<div></div>');
_.each(response.styles, function(style) {
  $appends.append('<style>' + style + '</style>');
 });
_.each(response.scripts, function(script) {
  $appends.append('<script type="text/javascript">' + script + '</script>');
});
$('#id').append($appends);
```
`minified=False` seems to work fine.

This is for Bokeh 0.12.0dev12

**Comment by mattpap** [comment]
@mistakevin, the resources are OK. It's JQuery that messes them up in `append()` at al. See "Regarding notebook failures" e-mail to bokeh-internal.

**Comment by mistakevin** [comment]
Interesting behavior on jQuery's part. I got around it by directly using the Document API
```javascript
_.each(plot.get('scripts'), function(script) {
  var scriptEl = document.createElement('script');
  scriptEl.type = 'text/javascript';
  scriptEl.text = script;
  this.el.appendChild(scriptEl);
}, this);
```
