### ISSUE TITLE
TMSTileSource map gets distorted on zoom along

### ISSUE THREAD

**Issue by monkut** [bokeh/bokeh#4556]
Following the example here:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/airports_map.py

I'm trying to drop in an OSM TMSTileSource in place of the original WMTSTileSource.

```
# create tile source
tile_options = {}
tile_options['url'] = 'https://b.tile.openstreetmap.org/{Z}/{X}/{Y}.png'
tile_options['min_zoom'] = 10
tile_options['max_zoom'] = 17
tile_source = TMSTileSource(**tile_options)
```

I noticed when I do this some tiles get displayed, but when trying to use zoom button with the mouse-wheel, the map image get's distorted along the x-axis.

WIth bokeh 0.11.1

**Comment by birdsarah** [comment]
@brendancol do you think this is a projection issue or just the normal problem because we don't have fixed aspect zoom.

**Comment by birdsarah** [comment]
@monkut can you clarify whether you were zooming with the mouse in the center of the plot or whether it was over an axis?

**Comment by monkut** [comment]
I tried at center and on the side an it still occurs.

btw here is my test code i'm running in Ipython notebook, but on execution checking/using the HTML page that opens when the cell is executed. Brower is chrome Version 51.0.2704.103 m.

```python 
from bokeh.models import (
    Range1d, TMSTileSource, ColumnDataSource, HoverTool,
)
from bokeh.plotting import figure, show, output_file
#from bokeh.sampledata.airports import data as airports

title = "Tokyo airports"
output_file("airports_map.html", title=title)


airports = {'x': [-99.502914],
            'y': [27.506748],
            'name': ["HND"],
            'elevation': [500]}
points_source = ColumnDataSource(airports)

# create tile source
tile_options = {}
tile_options['url'] = 'https://b.tile.openstreetmap.org/{Z}/{X}/{Y}.png'
tile_options['min_zoom'] = 10
tile_options['max_zoom'] = 17
tile_source = TMSTileSource(**tile_options)

# set to roughly extent of points
x_range = Range1d(start=min(airports['x']) - 10000, end=max(airports['x']) + 10000, bounds=None)
y_range = Range1d(start=min(airports['y']) - 10000, end=max(airports['y']) + 10000, bounds=None)

# create plot and add tools
p = figure(tools='wheel_zoom,pan', x_range=x_range, y_range=y_range, title=title)
p.axis.visible = False
hover_tool = HoverTool(tooltips=[("Name", "@name"), ("Elevation", "@elevation (m)")])
p.add_tools(hover_tool)
p.add_tile(tile_source)

# create point glyphs
p.circle(x='x', y='y', size=9, fill_color="#60ACA1", line_color="#D2C4C1", line_width=1.5, source=points_source)

show(p)
```

**Comment by monkut** [comment]
![image](https://cloud.githubusercontent.com/assets/1135529/16183348/cd345ff8-36eb-11e6-88b2-55553aeafa20.png)


Here's an image.  I'm trying to use the lat/long from the json file directly, perhaps it needs conversion from 4326 (wgs84) to 3857 (google maps) projection?

**Comment by bryevdv** [comment]
We now have both options for fixed aspect zoom (box or wheel) as well as `Plot.match_aspect` to request that 1-1 (or other) aspect be preserved at all times. I believe that should address the issues raised here, but please re-open if there is still some reproducible problem.
