### ISSUE TITLE
ggplot API Update

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4559]
The recent update to ggplot API broke all previous code.

Should the examples be update to work with the new API?

**Comment by birdsarah** [comment]
"The recent update to ggplot API broke all previous code."

Can you be a little more specific than "broke all previous code" - can you specify an example or examples that don't work. Most of bokeh is still working I'm assuming!

**Comment by bryevdv** [comment]
ggplot made breaking API changes between `0.6.5` (what we test with from the bokeh conda channel) and some more recent version. I'd like to update to `0.9.4` the most recent version for testing, but we will need to update our compat examples to match (and pin the version to `0.6.5` for testing before uploading the new packages... I have PR but it's not working yet)

**Comment by bryevdv** [comment]
PR to pin ggplot to `0.6.5` has been merged, will upload `0.9.4` packages now

**Comment by bryevdv** [comment]
new packages are uploaded, next step is a PR to update the examples and unpin the ggplot version
