### ISSUE TITLE
Generating a Figure with the Bokeh Server

### ISSUE THREAD

**Issue by ampruitt** [bokeh/bokeh#4564]
I ran across what seemed to be a glitch when I attempted to push a figure to a browser using a bokeh server.
The following lines seem the same:
"from bokeh.plotting import figure" and "from bokeh.plotting import Figure" (notice "Figure" is uppercased in the second one)
When trying to push one figure to the server using  "figure", two show up, one of which is correct and one of which is an empty glitch.
The following file contains a program that showcases the glitch.
If lines 11 and 19 are modified from "figure" to "Figure" the glitch disappears.

[figureProblem.txt](https://github.com/bokeh/bokeh/files/321203/figureProblem.txt)

**Comment by bryevdv** [comment]
This issue is well-discussed in the mailing list and the issue tracker, and is resolved in recent dev builds and the upcoming release.
