### ISSUE TITLE
Plot border gets covered up by things stuck on edge

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4574]
Easiest place to see it is on burtin example in this branch: https://github.com/bokeh/bokeh/pull/4576

<img width="918" alt="screen shot 2016-06-19 at 6 19 43 am" src="https://cloud.githubusercontent.com/assets/1796208/16177543/da7d0306-35e5-11e6-9d2c-f8f4bb1fae8a.png">

When the frame has a border it overlaps with the content on the outside.

**Comment by bryevdv** [comment]
Get rid of toolbar underline altogether?

**Comment by birdsarah** [comment]
> Get rid of toolbar underline altogether

I don't think that's the problem. I'm actually not sure what the problem is.

**Comment by bryevdv** [comment]
That appeared to be the problem when I zoomed in.

**Comment by birdsarah** [comment]
This also affects the bokehjs burtin example.

**Comment by birdsarah** [comment]
> Get rid of toolbar underline altogether?

I do think that's the issue now. I'll post some screenshots of what things look like without the underline. And we can decide under what circumstances we want to remove the outline - maybe all.
