### ISSUE TITLE
Gridplots broken except for fixed

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4581]
very bad!

**Comment by birdsarah** [comment]
commit 08c6bfb106d7313f3064c4ee90d86044ee91a82d is first bad commit

**Comment by birdsarah** [comment]
closed via commit c94a1d483e065c7c932922098edaef2122308df8 :s pushed to master. sincere apologies.

**Comment by damianavila** [comment]
> pushed to master

\o/ free :beers:
