### ISSUE TITLE
Add a series of screenshot tests for all the layout modes

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4582]
Almost all the layout modes were broken by a defaults update. Need to add some screenshot tests to ensure this doesn't happen again.

**Comment by birdsarah** [comment]
This is very high priority but does not need to make it into 0.12 as it doesn't affect users.

**Comment by mattpap** [comment]
Now we have a better solution for this problem, which are baseline tests that cover all examples and new bokehjs' integration test suite.
