### ISSUE TITLE
Using gridplot now gives a warning

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4583]
ToolbarBox must inherit from Box coffeescript side so that everything behaves correctly.

For the defaults tests to pass, that means it must also inherit from Box python side.

But that leads to the following warning when running a correctly functioning gridplot

WARNING:/Users/caged/Dev/bokeh/bokeh/bokeh/core/validation/check.py:W-1002 (EMPTY_LAYOUT): Layout has no children: ToolbarBox, ViewModel:ToolbarBox, ref _id: 1386

ping @bryevdv

**Comment by bryevdv** [comment]
@birdsarah solution is a function like this:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/layouts.py#L151-L155

On `ToolbarBox` that just immediately and unconditionally returns `None`.

**Comment by birdsarah** [comment]
Oh cool beans. I didn't think inheritance would just work for the warnings.

**Comment by birdsarah** [comment]
The other option would be to make the empty child toolbar, but that just feels wasteful.
