### ISSUE TITLE
Test that TypeScript API matches JS API

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4593]
Following discussion in last two comments of #4512.

As we add/change stuff in the Coffeescript code, we need to ensure to keep the TypeScript API up to date. Preferably there should be a test to ensure that they do. Ideally, such a test would check signatures and (to some degree) types), but a great first step would be a test that checks that all classes and all their public methods and properties _exist_ in the TS api.

I suspect that we can make the latter work with relative ease by means of a Python script that parses `.coffee` and `.d.ts` sources, create lists of classes/methods/properties on both sides, and compare these.

**Comment by almarklein** [comment]
cc @mattpap

**Comment by almarklein** [comment]
I just played a bit with this; it seems pretty easy to walk over the source files and collect class names, tough it would need some work to get rid of false positives (e.g. internal-only classes in coffeescript).

**Comment by bryevdv** [comment]
This should happen sooner than `long term`

**Comment by bryevdv** [comment]
Given that we are slowly just migrating entirely to typescript I am closing this as ultimately irrelevant.
