### ISSUE TITLE
Responsive view

### ISSUE THREAD

**Issue by JARVIS-Unifies** [bokeh/bokeh#4600]
Hi
I have made this interactive periodic table with Bokeh. The issue I am facing right now is the webpage is not automatically resizable. How do I fix that?

Here is the link to my project: http://www.ctcms.nist.gov/~knc6/periodic.html

Best Regards
Kamal Choudhary

**Comment by canavandl** [comment]
Hi @JARVIS-Unifies 

We try to limit the issue tracker to managing bugs and feature requests, so for user support please checkout out our [Gitter](https://gitter.im/bokeh/bokeh) or StackOverflow. So i'm going to mark this as invalid.

However, I suspect you want to set `responsive=True` within your figure (or Plot) init call. See docs: http://bokeh.pydata.org/en/latest/docs/reference/models/plots.html#bokeh.models.plots.Plot.responsive

**Comment by bryevdv** [comment]
FYI @canavandl we have `referred` now for these cases

**Comment by JARVIS-Unifies** [comment]
Hi

"Responsive" is a great feature in bokeh.
 It would be great if responsive works with vform in bokeh.
Do you guys know if anyone is working on it?

Best Regards
Kamal Choudhary

**Comment by bryevdv** [comment]
We are about to release the first stage of a major overhaul to layout for Bokeh in `0.12` I am not sure it will address your use case just yet but after this first initial push there are many smaller incremental improvements and fixes we will make.
