### ISSUE TITLE
Toggle button layout broken w/ new widgetbox

### ISSUE THREAD

**Issue by bgyarfas** [bokeh/bokeh#4601]
Spacing and layout of Toggle seem broken.
Running off of 0.12.0dev13. 
```
from bokeh.models import Button, Toggle
from bokeh.plotting import curdoc
from bokeh.layouts import widgetbox

button_1 = Button(label="Regular Button")

button_2 = Toggle(label="Toggle Button")

button_3 = Button(label="Regular Button")

curdoc().add_root(widgetbox([button_1, button_2, button_3]))
```

**Comment by birdsarah** [comment]
Thanks for sharing. Can you post a screenshot? I can definitely imagine this is a bug though. @bryevdv this is probably Toggle not having enough height -  guessing without seeing a screenshot though.

**Comment by birdsarah** [comment]
also, probably won't change anything @bgyarfas but can you reconfirm with the RC1 release that just came out last night.

**Comment by bgyarfas** [comment]
@birdsarah Yes, this was with RC1. See the screenshot below.
![image](https://cloud.githubusercontent.com/assets/6708431/16266403/ab4bd6a6-3852-11e6-99eb-2795ed486f98.png)

**Comment by birdsarah** [comment]
awesome thanks - I didn't realize this one was you too @bgyarfas - we're going to have to appoint you widget czar!

**Comment by Iceman121** [comment]
DataTable still renders weirdly.

![image](https://cloud.githubusercontent.com/assets/16691044/24633494/6e0bc3e8-18fb-11e7-92dc-08f749481514.png)

Any thoughts on how to rectify that?
