### ISSUE TITLE
No x-axis labels on bar graphs with a single bar

### ISSUE THREAD

**Issue by silentttone** [bokeh/bokeh#4602]
When a bar graph has a single bar the x-axis labels vanish. Is there a way to fix this? 

![screen shot 2016-06-20 at 4 19 30 pm](https://cloud.githubusercontent.com/assets/6374310/16213299/357d1d22-3703-11e6-9297-080b52ac2416.png)

**Comment by bryevdv** [comment]
Can you provide complete sample code to test with? It might be the case that it works in `0.12` pre-release candidates already.

**Comment by bryevdv** [comment]
With so many users now, trying to create test cases for every issue is an overwhelming burden. Providing  complete, minimal, runnable code to reproduce a problem is the surest and quickest way to get someone to look at an issue in depth.

**Comment by silentttone** [comment]
Thanks for letting me know. Here's a brief sample demonstrating the problem: 

```
from bokeh.charts import Bar, output_file, show, hplot

data = {'label': ['1'], 'value': [10]}
bar1 = Bar(data, values='value', label='label', title="Single Bar", plot_width=400, ylabel='Value')

data2 = {'label2': ['1', '2'], 'value2': [10,20]
}
bar2 = Bar(data2, values='value2', label='label2', title="Two Bars", plot_width = 400, ylabel='Value')

output_file("Example.html")
show(hplot(bar1, bar2))
```

**Comment by bryevdv** [comment]
This was evidently fixed at some point, here is a screen shot of that code off master (pre-`0.12.4`)

<img width="847" alt="screen shot 2016-12-20 at 5 57 19 pm" src="https://cloud.githubusercontent.com/assets/1078448/21372595/d5dce94a-c6dd-11e6-8975-b4d44241165f.png">
