### ISSUE TITLE
One pixel overlap of toolbar on top of plot's outline (bokehjs, burtin)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4610]
Pretty much outline is hidden along toolbar.

**Comment by birdsarah** [comment]
dupe of #4574?

**Comment by canavandl** [comment]
Is this related to: #4376 ?

i.e. Adding a border_line to a css box model causes the box to increase in size by the line width (i.e. the box increases by the width of the border_line)

**Comment by birdsarah** [comment]
I don't think so because it's canvas, but I don't know how we apply the border to canvas.

**Comment by birdsarah** [comment]
What I'm trying to say is I believe that the border is drawn on the canvas and not a css border.

**Comment by canavandl** [comment]
You're right that the border is drawn onto the canvas: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/plots/plot_canvas.coffee#L615

**Comment by mattpap** [comment]
@birdsarah, duplicate, just different examples are in consideration, but the problem the same.

**Comment by birdsarah** [comment]
I've noted that it also affects the burtin js example on #4574. Closing this so there's just one place to solve it. Feel free to add any extra details.
