### ISSUE TITLE
Hover Tool Has Own Column in IE

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4613]
Does not occur in Google Chrome or Firefox on Windows, or Safari on OS X. Appears to be an issue with IE on Windows 8.

Whenever there is an option for the hover tool in the toolbar, the toolbar divides into two columns with the hover tool having its own, separate column to the right. In many cases, this causes the toolbar to overlap the plot.

The screenshot is of the us_marriages_divorces.py example on rc1 (hover tool right of save tool):
<img width="838" alt="screen shot 2016-06-20 at 3 09 58 pm" src="https://cloud.githubusercontent.com/assets/19802403/16233321/938553ae-3793-11e6-9f06-08b4a133cf97.png">

**Comment by birdsarah** [comment]
Just to confirm that you tested this on RC1. 

I'm guessing that it's not that it has it's own column it's that it doesn't have sufficient height. 

Can you specify the IE version?

**Comment by HuntJSparra** [comment]
Tested and occurred on both RC1 and (earlier) dev13.

```
Windows 8.1
IE Version 11.0.1
```

**Comment by bryevdv** [comment]
@HuntJSparra can you see if #5379 (just merged) fixes this?

**Comment by HuntJSparra** [comment]
@bryevdv I do not currently have access to a computer or VM with Windows 8 and can't test it. Sorry.

**Comment by mattpap** [comment]
This was fixed in PR #7008.
