### ISSUE TITLE
Reset tool does not trigger x/y_range callback events

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#4614]
The reset tool obviously changes the extents of the axes, which should trigger any callback events attached to them but it does not appear to. I could swear there was an issue about this that was closed recently, but I can't find it now so I'm probably misremembering. I've tested it as part of 0.12rc1 and it still appears to be an issue there. This functionality is important for downsampling or any other callbacks that depend on the zoom level such as we make use of in datashader.

**Comment by bryevdv** [comment]
Would consider a very targeted small hotfix PR

**Comment by jbednar** [comment]
I strongly remember there being such an issue, but I really can't find it now either.  The issue dates to at least bokeh 11.1, and maybe earlier.
