### ISSUE TITLE
Slider widget broken on IE / Edge 

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4617]
Currently, the slider widget is broken to being essentially useless on IE / Edge.

Some affected examples:
* plotting/file/color_sliders.py
* plotting/file/slider.py
* test/slider_callback_policy.py

**Comment by almarklein** [comment]
@birdsarah @mattpap any idea of profound changes to the slider recently that might have caused this?

**Comment by almarklein** [comment]
Euh... wtf ... now it looks just fine. And I don't think I did anything??

Ok, if someone can double-check that sliders look ok on IE, then we can close this.

**Comment by bryevdv** [comment]
So when I run `sliders.py` on edge, the first slider does not seem to work but all the rest do

**Comment by bryevdv** [comment]
Oh, the slider policy is now `mouseup`:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/slider.py#L30

I think I'd like to change that back. they should all be the same, at least

**Comment by almarklein** [comment]
Ok, this was an env issue. It does not work on `https://cdn.pydata.org/bokeh/dev/bokeh-0.12.0rc1.min.css`, but it does with my local bokehjs. Is that even the correct rc?

**Comment by bryevdv** [comment]
I was testing with the rc installed by conda

**Comment by almarklein** [comment]
I tested off master, but maybe that was a bad idea ...

**Comment by birdsarah** [comment]
No profound changes to slider, but I did update the styling which can render it un-usable if it doesn't apply properly. So, the good news is any fix would likely just be ie specific CSS. I did try and multibrowser test this but def possible I missed something, also things have shifted again since then.

**Comment by almarklein** [comment]
Still strange that it works for bokehjs of master and not for the bokehjs in `cdn....bokeh-0.12.0rc1` ... was there a fix *after* the rc?

**Comment by bryevdv** [comment]
It was working from the rc for me.

**Comment by almarklein** [comment]
Ok, checked again; running fully in rc1 does work. I think I was running in master with the bokehjs rc1 from cdn. I'm assuming all is well then. Sorry for the noise.
