### ISSUE TITLE
TileRenderer glitches when axes label length changes plot height/width

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#4619]
reproduction:

``` python
from __future__ import print_function

from bokeh.models import Range1d, WMTSTileSource
from bokeh.plotting import figure, show, output_file

output_file("glitchy_wheelzoom_yaxis_labels.html")

# create tile source
tile_options = {}
tile_options['url'] = 'http://otile2.mqcdn.com/tiles/1.0.0/sat/{Z}/{X}/{Y}.png'
tile_source = WMTSTileSource(**tile_options)

x_range = Range1d(start=-20e6, end=20e6, bounds=None)
y_range = Range1d(start=-20e6, end=20e6, bounds=None)

# create plot and add tools
p = figure(tools='wheel_zoom,pan', x_range=x_range, y_range=y_range)
#p.yaxis.major_label_orientation = 'vertical' # uncomment to see fixed
p.add_tile(tile_source)
show(p)
```

In the case of displaying map tiles, plots must maintain the same resolution ratio (`x_range/width` to `y_range/height`). To achieve this, `TileRenderer` checks to see if the resolution ratios are correct, and if not, it snaps ranges/axes to the nearest integer zoom level. This is behavior now conflicts with the new behavior of axes labels which don't cut off and instead dynamically make the plot smaller.  Personally, I don't like displaying axes labels on maps, 

I would think the solution would be:
- short-term: fix `TileRenderer` so it doesn't change zoom level when resolution snapping
- medium-term: add a `Range2d(x_range, y_range, resolution_ratio=1)` model

**Comment by damianavila** [comment]
@brendancol why you label this one as an Epic... seems to be just a bug report unless I am missing something...

**Comment by bryevdv** [comment]
Unfortunately the test case no longer runs because the tiles source no longer seems to exist. There has been lots of work since this, so it's possible it's no longer an issue. But with nothing to test against I will close as `norepro` (happy to re-open with a new MRE)
