### ISSUE TITLE
responsive no longer supported?

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#4620]
Is the responsive keyword no longer supported in 0.12.0rc1?  In 0.11.1 I could pass it to `bokeh.plotting.figure`, and it would make the plot fill the container it was in:

```python
import bokeh
print(bokeh.__version__)
import bokeh.plotting as bp
from bokeh.models.tiles import WMTSTileSource

bp.output_notebook()
p = bp.figure(tools='pan,wheel_zoom,reset', x_range=(-13884029,  -7453304), y_range=(2698291, 6455972))
p.add_tile(WMTSTileSource(url="http://tile.stamen.com/toner-background/{Z}/{X}/{Y}.png"))
p.responsive = True
bp.show(p)
```

![image](https://cloud.githubusercontent.com/assets/1695496/16247425/4722eaf8-37cf-11e6-8eee-ca851c5448ca.png)

But in 0.12.0rc1, I get an error:

```python
0.12.0rc1
 BokehJS successfully loaded
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-58565180fe65> in <module>()
      7 p = bp.figure(tools='pan,wheel_zoom,reset', x_range=(-13884029,  -7453304), y_range=(2698291, 6455972))
      8 p.add_tile(WMTSTileSource(url="http://tile.stamen.com/toner-background/{Z}/{X}/{Y}.png"))
----> 9 p.responsive = True
     10 bp.show(p)

/Users/jbednar/anaconda/lib/python2.7/site-packages/bokeh/core/properties.py in __setattr__(self, name, value)
    722 
    723             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 724                 (name, self.__class__.__name__, text, nice_join(matches)))
    725 
    726     def set_from_json(self, name, json, models=None):

AttributeError: unexpected attribute 'responsive' to Figure, possible attributes are above, background_fill_alpha, background_fill_color, below, border_fill_alpha, border_fill_color, disabled, extra_x_ranges, extra_y_ranges, h_symmetry, height, hidpi, left, lod_factor, lod_interval, lod_threshold, lod_timeout, min_border, min_border_bottom, min_border_left, min_border_right, min_border_top, name, outline_line_alpha, outline_line_cap, outline_line_color, outline_line_dash, outline_line_dash_offset, outline_line_join, outline_line_width, plot_height, plot_width, renderers, right, sizing_mode, tags, title, title_location, tool_events, toolbar, toolbar_location, toolbar_sticky, v_symmetry, webgl, width, x_mapper_type, x_range, y_mapper_type or y_range

In [ ]:
```

**Comment by almarklein** [comment]
you want to set `responsive='scale_both'`, and if necessary call `plot.model.document.resize()` when the size of the container changed.

**Comment by bryevdv** [comment]
You can pass the bool to `figure` still but the actual property is an enum now.

**Comment by jbednar** [comment]
Thanks.  And that's a deliberate break in backwards compatibility?  E.g. it breaks the various datashader notebooks that have been distributed.

**Comment by bryevdv** [comment]
Yes, we could not find a technical way to support it and move forward.

**Comment by jbednar** [comment]
An enum that includes True and False as options wouldn't work, then?  Ah well.

**Comment by birdsarah** [comment]
> you want to set responsive='scale_both', and if necessary call plot.model.document.resize() when the size of the container changed.

It would be `sizing_mode=` not `responsive=`. Secondly I can't recommend the use of `scale_both` it's experimental at this point and you have to have decent web knowledge to make it work for you.

@jbednar I think you want `sizing_mode='scale_width'` and `responsive=True` is a synonym for that and still works, although, as you've noted not as a subsequent property setter.

**Comment by birdsarah** [comment]
Also, @almarklein I'd be shocked if `scale_both` works in the notebook where output cells don't have an inherent height.

**Comment by almarklein** [comment]
Ah, I missed that this was for the notebook. In that case `scale_width` is likely better, yes :)

**Comment by bryevdv** [comment]
closing this (I don't think there's anything left to discuss)

**Comment by bryevdv** [comment]
Well should add @jbednar you can still pass `responsive` as a keyword argument to `Figure` and charts initializers.

**Comment by bryevdv** [comment]
Actually I can add a python getter / setter that is deprecated for this, so I will.
