### ISSUE TITLE
Change default tool within gestures

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#4624]
I was searching online on how to change which tool is selected by default and came upon this Google Groups posting: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/VGR94XAbcwo, it was suggested by @bryevdv to create an issue for this but I couldn't find any issues referring to this specific enhancement.

In short, it would be great to change the default gesture to something else, I have had requests from users to change the default from "pan" to "box zoom" in some plots I present and am currently unable to satisfy that request.

**Comment by birdsarah** [comment]
I believe this was recently fixed. ping @bryevdv

**Comment by bryevdv** [comment]
This is done in a recent PR

**Comment by guillochon** [comment]
So this will be available in 0.12? How is it done in practice?

**Comment by bryevdv** [comment]
Here is the PR w details: https://github.com/bokeh/bokeh/pull/4552

**Comment by guillochon** [comment]
Great, thanks!
