### ISSUE TITLE
Save behavior on gridplot - potential for user confusion

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4632]
The new save button triggers a download of the plot image instead of bringing up the modal.
On a grid plot, this triggers a download of as many separate files as you have plots.
Chrome (and maybe other browser) bring up a dialog that checks whether you want to download multiple files or not. If you click block, then the next time you go back to that page then pressing the save button does nothing. It's pretty easy to correct - see video below - but feels like an area that could trip people up.

![multi-save-small](https://cloud.githubusercontent.com/assets/1796208/16274796/0aea6808-385c-11e6-9d68-b1a86aca237a.gif)

**Comment by bryevdv** [comment]
Well the old behavior triggered as many modals as there were plots. This isn't *too* much different but I can see how it could be confusing. The solution is probably a specialized proxy for the save tool.

**Comment by birdsarah** [comment]
> The solution is probably a specialized proxy for the save tool. 

Or just some docs in the short term. I don't think the behavior's bad, just potentially confusing if you hit "Block" and then come back later.

**Comment by bryevdv** [comment]
Given the new PNG and SVG exports which are much better options,  and our limited bandwidth, I think we will just have to live with the on-plot save-tool as is
