### ISSUE TITLE
Bokeh won't load in Pycharm notebook

### ISSUE THREAD

**Issue by msouder** [bokeh/bokeh#4634]
When I try to load bokeh in a Pycharm notebook, it hangs on "Loading BokehJS ..."  In Chrome, bokeh loads just fine when I access the server started by Pycharm.  I tried setting resources to CDN and INLINE but neither worked.  Both options work in Chrome.  I still tried to generate a scatter plot and it does not display in Pycharm (but does in Chrome).

I'm using Windows 7, 64-bit

PyCharm Community Edition 2016.1.4
Build #PC-145.1504, built on May 25, 2016
JRE: 1.8.0_77-b03 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

conda list -e
This file may be used to create an environment using:
$ conda create --name <env> --file <this file>
platform: win-64
alabaster=0.7.7=py35_0
anaconda=4.0.0=np110py35_0
anaconda-client=1.4.0=py35_0
anaconda-navigator=1.1.1=py35_0
argcomplete=1.0.0=py35_1
astropy=1.1.2=np110py35_0
azure=1.0.2=py35_0
babel=2.2.0=py35_0
basemap=1.0.8.dev0=np110py35_1
bcrypt=2.0.0=py35_0
beautifulsoup4=4.4.1=py35_0
biggus=0.13.0=py35_0
bitarray=0.8.1=py35_1
blaze=0.9.1=py35_0
bokeh=0.11.1=py35_0
boto=2.39.0=py35_0
bottleneck=1.0.0=np110py35_0
bzip2=1.0.6=vc14_2
cartopy=0.14.2=np111py35_0
cf_units=1.1=py35_0
cffi=1.5.2=py35_0
chest=0.2.3=py35_0
cloudpickle=0.2.1=py35_0
clyent=1.2.1=py35_0
colorama=0.3.7=py35_0
comtypes=1.1.2=py35_0
conda=4.0.7=py35_0
conda-build=1.20.1=py35_0
conda-env=2.4.5=py35_0
conda-manager=0.4.0=py35_0
configobj=5.0.6=py35_0
console_shortcut=0.1.1=py35_1
cryptography=1.3=py35_0
csvkit=0.9.1=py35_1
curl=7.45.0=vc14_1
cycler=0.10.0=py35_0
cython=0.23.4=py35_0
cytoolz=0.7.5=py35_0
dask=0.8.1=py35_0
datashape=0.5.1=py35_0
decorator=4.0.9=py35_0
dill=0.2.4=py35_0
docutils=0.12=py35_1
dynd-python=0.7.2=py35_0
et_xmlfile=1.0.1=py35_0
expat=2.1.0=vc14_1
fastcache=1.0.2=py35_0
flask=0.10.1=py35_1
flask-cors=2.1.2=py35_0
folium=0.2.1=py35_0
freetype=2.5.5=vc14_0
geos=3.4.2=vc14_1
gevent=1.1.0=py35_0
greenlet=0.4.9=py35_0
h5py=2.5.0=np110py35_4
hdf5=1.8.15.1=vc14_4
heapdict=1.0.0=py35_0
idna=2.0=py35_0
ipykernel=4.3.1=py35_0
ipython=4.1.2=py35_1
ipython_genutils=0.1.0=py35_0
ipywidgets=4.1.1=py35_0
iris=1.9.2=np111py35_0
itsdangerous=0.24=py35_0
jdcal=1.2=py35_0
jedi=0.9.0=py35_0
jinja2=2.8=py35_0
jpeg=8d=vc14_0
jsonschema=2.4.0=py35_0
jupyter=1.0.0=py35_2
jupyter_client=4.2.2=py35_0
jupyter_console=4.1.1=py35_0
jupyter_core=4.1.0=py35_0
libdynd=0.7.2=0
libpng=1.6.17=vc14_1
libsodium=1.0.3=0
libtiff=4.0.6=vc14_0
llvmlite=0.9.0=py35_0
locket=0.2.0=py35_0
lxml=3.6.0=py35_0
markupsafe=0.23=py35_1
matplotlib=1.5.1=np110py35_0
menuinst=1.3.2=py35_0
mistune=0.7.2=py35_0
mkl=11.3.1=0
mkl-service=1.1.2=py35_0
mock=2.0.0=py35_0
mpmath=0.19=py35_0
multipledispatch=0.4.8=py35_0
mysql-connector-python=2.0.3=py35_0
nbconvert=4.1.0=py35_0
nbformat=4.0.1=py35_0
netcdf4=1.2.2=np111py35_0
networkx=1.11=py35_0
nltk=3.2=py35_0
nose=1.3.7=py35_0
notebook=4.1.0=py35_2
numba=0.24.0=np110py35_0
numexpr=2.5.1=np110py35_0
numpy=1.10.4=py35_0
odo=0.4.2=py35_0
openpyxl=2.3.2=py35_0
openssl=1.0.2g=vc14_0
owslib=0.11.0=py35_0
pandas=0.18.1=np110py35_0
partd=0.3.2=py35_1
patch=2.5.9=1
path.py=8.1.2=py35_1
patsy=0.4.0=np110py35_0
pbr=1.8.0=py35_0
pep8=1.7.0=py35_0
pickleshare=0.5=py35_0
pillow=3.1.1=py35_0
pip=8.1.1=py35_1
ply=3.8=py35_0
proj.4=4.9.2=py35_vc14_0
psutil=4.1.0=py35_0
py=1.4.31=py35_0
pyasn1=0.1.9=py35_0
pycosat=0.6.1=py35_0
pycparser=2.14=py35_0
pycrypto=2.6.1=py35_3
pyepsg=0.2.0=py35_0
pyflakes=1.1.0=py35_0
pygments=2.1.1=py35_0
pyke=1.1.1=py35_0
pymongo=3.0.3=py35_0
pymysql=0.6.7=py35_0
pyopenssl=0.15.1=py35_2
pyparsing=2.0.3=py35_0
pyproj=1.9.5.1=py35_0
pyqt=4.11.4=py35_5
pyreadline=2.1=py35_0
pyshp=1.2.3=py35_0
pytables=3.2.2=np110py35_2
pytest=2.8.5=py35_0
python=3.5.1=4
python-dateutil=2.5.1=py35_0
pytz=2016.2=py35_0
pywin32=220=py35_1
pyyaml=3.11=py35_3
pyzmq=15.2.0=py35_0
qt=4.8.7=vc14_7
qtawesome=0.3.2=py35_0
qtconsole=4.2.0=py35_1
qtpy=1.0=py35_0
requests=2.9.1=py35_0
rope=0.9.4=py35_1
scikit-image=0.12.3=np110py35_0
scikit-learn=0.17.1=np110py35_0
scipy=0.17.0=np110py35_0
seaborn=0.7.0=py35_0
setuptools=21.2.1=py35_0
shapely=1.5.15=np111py35_0
simplegeneric=0.8.1=py35_0
singledispatch=3.4.0.3=py35_0
sip=4.16.9=py35_2
six=1.10.0=py35_0
snowballstemmer=1.2.1=py35_0
sockjs-tornado=1.0.1=py35_0
sphinx=1.3.5=py35_0
sphinx_rtd_theme=0.1.9=py35_0
spyder=2.3.8=py35_1
sqlalchemy=1.0.12=py35_0
statsmodels=0.6.1=np110py35_0
sympy=1.0=py35_0
tk=8.5.18=vc14_0
toolz=0.7.4=py35_0
tornado=4.3=py35_0
traitlets=4.2.1=py35_0
udunits2=2.2.20=vc14_1
unicodecsv=0.14.1=py35_0
vincent=0.4.4=py35_0
vs2015_runtime=14.00.23026.0=0
werkzeug=0.11.4=py35_0
wheel=0.29.0=py35_0
xlrd=0.9.4=py35_0
xlsxwriter=0.8.4=py35_0
xlwings=0.7.0=py35_0
xlwt=1.0.0=py35_0
yaml=0.1.6=0
zlib=1.2.8=vc14_2

**Comment by bryevdv** [comment]
AFAIK no-one on the core team uses or has any experience with PyCharm, this issue might be better taken up with them. Our notebook loading uses standard Jupyter APIs.

**Comment by msouder** [comment]
Ah, just found the issues page for Pycharm and they currently don't support javascript in notebooks.  Should have looked there first.

**Comment by bryevdv** [comment]
Ah, yes that makes Bokeh plots a non-starter then. Closing a `upstream`
