### ISSUE TITLE
Right titles are too far out

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4635]
I don't like the look of titles when title_location='right'. They're too far to the right and not visually connected with their plot. It's particularly bad on gridplots

<img width="1108" alt="screen shot 2016-06-22 at 10 40 59 am" src="https://cloud.githubusercontent.com/assets/1796208/16277015/dfd4dd60-3865-11e6-9a73-ecc18a5bca45.png">

**Comment by mattpap** [comment]
This was fixed in PR #7008.
