### ISSUE TITLE
TextInput not obeying width parameter

### ISSUE THREAD

**Issue by bgyarfas** [bokeh/bokeh#4636]
Trying to force a `TextInput` to a certain width does not work as it does with Sliders/MultiSelect/etc. (see last comment in #3346): 
```
from bokeh.models import (
    Slider,
    TextInput)
from bokeh.plotting import  curdoc
from bokeh.layouts import column
curdoc().add_root(column(children=[Slider(width=150)]))
```

I found a workaround to the above by adding `@$el.find('input').width(@mget('width'))` @ [https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/text_input.coffee#L31](url)

Also, a `Slider` with a specified `width` will not be the correct size in Chrome (51.0.2704.103 ) until the browser window is resized.
![image](https://cloud.githubusercontent.com/assets/6708431/16278076/838d8494-3883-11e6-9bea-d946e8e30441.png)
![image](https://cloud.githubusercontent.com/assets/6708431/16278089/8c68c4d4-3883-11e6-81c8-9954e825775f.png)
This behavior is not present on Safari, but _only on the first load within a tab/page_. On subsequent refreshes, with or without cache, the behavior is the same as in Chrome.

**Comment by bgyarfas** [comment]
If using a `widgetbox` then `curdoc().add_root(widgetbox(children=[Slider(width=150)]))` will not obey the `width` parameter. But, if you use `curdoc().add_root(widgetbox(children=[Slider()], width=150))` then it will, at least with the same buggy behavior described above.

**Comment by bgyarfas** [comment]
Buttons will also not obey the width parameter as well when in a `widgetbox`, although the `widgetbox` will obey. Running the following snippet:
```
button_1 = Button(label="Button 1")
button_2 = Button(label="Button 2")
curdoc().add_root(widgetbox(children=[button_1, button_2], width=150))
```
results in the Buttons resizing on browser window size change, but not to the correct size.
Before browser window size change:
![image](https://cloud.githubusercontent.com/assets/6708431/16279347/9e6798c2-3888-11e6-9631-f3d115b20dac.png)

**After:**
![image](https://cloud.githubusercontent.com/assets/6708431/16279335/8f274196-3888-11e6-91fe-fe330c0629d6.png)
Notice the width/height properties of the `widget-box` and `widget` get updated on a size change. But the Button doesn't, the Button is not the right size in these images (they're ~75px).
Putting the `width` param in the `Button` initialization does not work:
```
button_1 = Button(label="Button 1", width=150)
button_2 = Button(label="Button 2", width=150)
curdoc().add_root(widgetbox(children=[button_1, button_2]))
```

**Comment by nathanielatom** [comment]
I believe the `TextInput` not paying attention to its `width` parameter is once again an issue in bokeh `0.12.4`.

**Comment by ryanjdillon** [comment]
I'm on `0.12.6` and also having this problem.

**Comment by thoth291** [comment]
I'm at 0.12.7 - TextInput still ignores width

**Comment by gkep** [comment]
0.12.10 - TextInput still ignores width (Win10)

**Comment by Minhir** [comment]
0.12.15 - TextInput still ignores width (Linux)
