### ISSUE TITLE
Add ability to serve server resources from bokehjs build dir

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4648]
When I'm developing JS locally but need to use the server to test I do the following.

``` sh
$ cd bokeh/server/static
$ rm -rf css js
$ ln -s ../../../bokehjs/build/js js
$ ln -s ../../../bokehjs/build/css css
```

This links the server's static directory to the bokehjs directory.

I then do `export BOKEH_MINIFIED=false`.

Finally I can run by bokeh server apps, and then use gulp watch and my changes are automatically picked up. Before this I was running `python setup.py develop --build-js` all the time to have the resources copied over to static.

**Comment by bryevdv** [comment]
I'd support this if it was exposed just as an environment variable, and not a command line option.

**Comment by bryevdv** [comment]
This mostly affects @mattpap (who has his own process) and me. Honestly my preference is to just always rebuild everything as the safest and most comprehensible thing to do. If someone else feels strongly about this please, re-open.

**Comment by mattpap** [comment]
@bryevdv, I think this actually was implemented, because when I run `BOKEH_DEV=true python -m bokeh serve something`, resources are served from `bokehjs/build`. The only annoying thing is that I have to use `BOKEH_DEV=true BOKEH_RESOURCES=server-dev`, because resources are "absolute" and don't adapt to the backend.

**Comment by mattpap** [comment]
> (who has his own process)

This mostly isn't true anymore and I use whatever we have in the default build, just I take it to extreme, running individual tasks, skipping dependencies, etc., when I know the side effects, to decrease iteration time.
