### ISSUE TITLE
I have pushed bokeh application to cloud, button with call back does not work

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#4649]
I have pushed bokeh application to cloud, button with call back does not work

def PlayPause_handler(active):
    if active:
        curdoc().add_periodic_callback(update,1000)
    else:
        curdoc().remove_periodic_callback(update)

**Comment by bryevdv** [comment]
Did you find a solution ? What was the issue?

**Comment by charleywan2004** [comment]
I closed the issue. It is because the code in button handler is not working.

BTW, my colleague helped me put the following code in server.py code so
that cloud can assign port and address to bokeh server.

            ###start
            import os

            log.critical("About to start Bokeh server on port %s",
self._port)
            self._port = int(os.getenv("VCAP_APP_PORT"))
            self._address = '0.0.0.0'
            ###-end
         self._http.bind(self._port, address=self._address)
            self._http.start(1)
        except OSError as e:
            import errno
            if e.errno == errno.EADDRINUSE:
                log.critical("Cannot start Bokeh server, port %s is already
in use", self._port)
            elif e.errno == errno.EADDRNOTAVAIL:
                log.critical("Cannot start Bokeh server, address '%s' not
available", self._address)
            else:
                codename = errno.errorcode[e.errno]
                log.critical("Cannot start Bokeh server, %s %r", codename,
e)
            sys.exit(1)
