### ISSUE TITLE
Dialog broken

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4652]
* Dialog - not sure how to use it even (how to get it to appear); adding buttons list doesn't seem to work; adding plot for content gives solver error.

**Comment by fpliger** [comment]
@birdsarah Dialog seems to just be broken.... it takes either a string or a box as content but neither work. Here's a quick examples that *should* work:

```python
import numpy as np

from bokeh.layouts import row, widgetbox
from bokeh.models import CustomJS, Slider, Paragraph, Dialog, Button
from bokeh.plotting import figure, output_file, show, ColumnDataSource

x = np.linspace(0, 10, 500)
y = np.sin(x)

source = ColumnDataSource(data=dict(x=x, y=y))

plot = figure(y_range=(-10, 10), plot_width=400, plot_height=400)

plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)

descr_box = Paragraph(text='content loading...')

btn_close_loading = Button(label='Close Loading')
dialog_loading = Dialog(
    title='loading', content=row(descr_box), name='loading_dialog',
    buttons=[btn_close_loading], visible=True)



layout = row(
    dialog_loading,
    plot,
    widgetbox(btn_close_loading),
)

output_file("slider.html", title="slider.py example")

show(layout)
```

with box it raises:

<img width="726" alt="screen shot 2016-06-24 at 2 39 57 pm" src="https://cloud.githubusercontent.com/assets/1084690/16348777/3116a8a6-3a1a-11e6-9016-7a3dd9687d2b.png">

and with a string it raises:

<img width="1433" alt="screen shot 2016-06-24 at 2 34 31 pm" src="https://cloud.githubusercontent.com/assets/1084690/16348787/3f23ade0-3a1a-11e6-9f3f-e5178cea7f04.png">

**Comment by birdsarah** [comment]
Thanks @fpliger

**Comment by fpliger** [comment]
same code (replacing `row` with `vplot`) renders as:

<img width="1438" alt="screen shot 2016-06-24 at 2 56 54 pm" src="https://cloud.githubusercontent.com/assets/1084690/16349058/feb1617e-3a1b-11e6-8186-8fd8db2273dd.png">

**Comment by birdsarah** [comment]
That's perfect, thanks.

That's with 0.11.1?

**Comment by fpliger** [comment]
yup

**Comment by birdsarah** [comment]
@bryevdv I didn't get a chance to fix this; let me know if you have time.

**Comment by birdsarah** [comment]
(I couldn't reproduce the issues I was having with autocomplete before, so chagned this to be just about the dialog bug)

**Comment by birdsarah** [comment]
I'm working on this now.

**Comment by bryevdv** [comment]
AFAIK this is completely brokeh, but no one has complained about this, I'd say we can consider removing this as well.

**Comment by birdsarah** [comment]
agreed

**Comment by bryevdv** [comment]
`MIGRATION` to note its removal (even though it's not worked in ages)

**Comment by bryevdv** [comment]
I've update the issue title to reflect the actual work undertaken
