### ISSUE TITLE
Adding an unwrapped widget to document, may not render properly

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4657]
The following

``` python
r_slider = Slider(start=0, end=255, value=22, step=1, width=500, title="R")
show(r_slider)
```

gives

<img width="777" alt="screen shot 2016-06-23 at 1 08 45 pm" src="https://cloud.githubusercontent.com/assets/1796208/16318398/e4dc355e-3943-11e6-9601-e5418f9312fd.png">

Now as soon as you wrap that slider in a widgetbox, row, or column it's happy again.

This won't be true for more native html items like buttons and text, but could affect other more complex widgets - I haven't tried them all.

The reason, I believe, is that widgets get their height from their parent, so without it, they get stuck.

**Comment by bryevdv** [comment]
This was fixed at some point. 

The following code 
```

from bokeh.io import output_file, show
from bokeh.models import Slider

r_slider = Slider(start=0, end=255, value=22, step=1, width=500, title="R")
show(r_slider)

output_file("test.html")

show(p)
```
now yields

<img width="555" alt="screen shot 2017-05-11 at 23 08 00" src="https://cloud.githubusercontent.com/assets/1078448/25982028/b1e452d6-369e-11e7-908d-16e584cee5d3.png">
