### ISSUE TITLE
Google maps no longer working due to Api update?

### ISSUE THREAD

**Issue by RaulPL** [bokeh/bokeh#4658]
Hi, I was trying to run the google maps example from [http://bokeh.pydata.org/en/0.11.1/docs/user_guide/geo.html](url) however I got the following message:

![gmap](https://cloud.githubusercontent.com/assets/3116652/16316308/abdec75a-394b-11e6-9b75-ab3e55df4903.png)

I think this issue is due to the update in the Google maps API [http://googlegeodevelopers.blogspot.mx/](url), it now requires a key.

My bokeh info:
Python version      :  3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
IPython version     :  4.2.0
Bokeh version       :  0.11.1

I'm using Firefox in Ubuntu 15.10

**Comment by bryevdv** [comment]
Well, my initial reaction is: that sucks. built And then: not anything we can do about it, unfortunately. We don't have the financial means to provide a key built into Bokeh for all (user x maps x viewers). Perhaps this is something we can do to help users provide their own API keys, an env-var or configuration in `~/.bokeh`

ping @bokeh/dev

**Comment by birdsarah** [comment]
Yes, at the lease it should be easy to provide it via map options - maybe that just works - and its just a docs thing for us?

**Comment by birdsarah** [comment]
Thanks ever so much for the timely report @RaulPL!

**Comment by birdsarah** [comment]
also, if map_options does work then we should be able to get the documentation example working again without overtly revealing our key.

**Comment by bryevdv** [comment]
I'm not sure offhand how keys are provided, will have to investigate. If they can be passed via `map_options` then that provides an immediate avenue for users, otherwise I think it will require dev work to add a new hook.

**Comment by bryevdv** [comment]
There's no point in having a docs example "works" if there's no way for users to follow an example.

**Comment by birdsarah** [comment]
Looks like there's a very quick fix. Working up a PR.

**Comment by bryevdv** [comment]
Looking at:

https://developers.google.com/maps/documentation/javascript/tutorial#The_Hello_World_of_Google_Maps_v3

The key seems to have to go in the script tag:
```
 <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
    async defer></script>
```
So I don't see how this gets fixed without transmitting a key from python since the script tag is created in JS, not part of some template:
```
      window._bokeh_gmap_loads.push(build_map)
      window._bokeh_gmap_callback = () ->
        _.each(window._bokeh_gmap_loads, _.defer)
      script = document.createElement('script')
      script.type = 'text/javascript'
      script.src = "https://maps.googleapis.com/maps/api/js?v=3&callback=_bokeh_gmap_callback"
      document.body.appendChild(script)
```

**Comment by RaulPL** [comment]
@birdsarah no problem, I would like to help but I don't know much about JS =/

 Do you know if there is another way to plot an interactive map using Bokeh? I found this really cool video [bokeh tile provider demo](https://www.youtube.com/watch?v=YAls_da1cF4) but I don't know if the source code is open or if there is a similar example program somewhere.

**Comment by bryevdv** [comment]
@RaulPL there is a tile renderer example using OSM tiles here:

https://github.com/bokeh/bokeh/blob/76eb274502f5119102c60c9093fcc1a311453216/examples/models/tile_source.py

**Comment by RaulPL** [comment]
@bryevdv Thanks

**Comment by bryevdv** [comment]
Best solution for now is `api_key` property.

**Comment by RaulPL** [comment]
Hi @bryevdv, which bokeh do I have to install in order to have this solution?

**Comment by bryevdv** [comment]
This is in the latest `0.12` release candidate I just made. Instructions for installing dev/rc builds are on the  main docs site.

**Comment by dp6752** [comment]
@bryevdv could you give me URL of docs. TIA

**Comment by t0mst0ne** [comment]
Is it possible to support OSM map layer  ?

**Comment by birdsarah** [comment]
@t0mst0ne we do - http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html#tile-providers
