### ISSUE TITLE
Add missing widget callback integration tests

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4665]
See #4663 where I broke widget callbacks.

This should be easy to unit test.

**Comment by bryevdv** [comment]
There are now many selenium integration tests for most widgets:

https://github.com/bokeh/bokeh/tree/master/tests/integration/widgets

But I notice a few important ones missing, so I will re-purpose this issue to finish those tests out.

**Comment by bryevdv** [comment]
Recently added even more, will close this now
