### ISSUE TITLE
ArrowHead documentation

### ISSUE THREAD

**Issue by humm** [bokeh/bokeh#4669]
Styling the head of an Arrow annotation is not trivial. It seems there is a page missing from the documentation (for this file: https://github.com/bokeh/bokeh/blob/master/bokeh/models/arrow_heads.py for the type of the `end` attribute of the Arrow class here: http://bokeh.pydata.org/en/dev/docs/reference/models/annotations.html). 

Furthermore, the example in the user guide (http://bokeh.pydata.org/en/dev/docs/user_guide/plotting.html#arrows) could show an example of an arrow head with a different color (not just a different shape), for instance:
`p.add_layout(Arrow(end=VeeHead(line_color='blue'), x_start=0.5, y_start=0.7, x_end=0, y_end=0, line_color='red'))`

**Comment by bryevdv** [comment]
Was on my list, but an issue is good.

**Comment by bryevdv** [comment]
in PR:

<img width="933" alt="screen shot 2016-06-24 at 6 49 04 pm" src="https://cloud.githubusercontent.com/assets/1078448/16353202/8d2119fc-3a3c-11e6-9af6-768af7dc8fc2.png">
