### ISSUE TITLE
Draw Legend After WebGL glyphs

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#4679]
<img width="906" alt="screen shot 2016-06-24 at 6 50 29 pm" src="https://cloud.githubusercontent.com/assets/433221/16357521/c6f00a1c-3abe-11e6-8835-0e4bb17550d4.png">

**Comment by bryevdv** [comment]
@brendancol do not that you can put legends outside the plot area now, though. See `examples/models/legends.py`

**Comment by pythonUzer** [comment]
I just updated to 0.12.1 and reran the case I have that is the same issue as this one, but I am still seeing the issue. Has anyone tested this feature recently in 0.12.1 or am I the only with the continuing issue? Thanks for the help

**Comment by bryevdv** [comment]
Yes I tested your code from the issue with 0.12.1 and verified that the legend was on top.
