### ISSUE TITLE
Rendering issue with webgl for line with high framerate

### ISSUE THREAD

**Issue by Paradoxeuh** [bokeh/bokeh#4681]
Hi,

I've seen some rendering issue when the webgl option is True in bokeh. I'm using firefox 47.0 to draw a line of 512 points getting updated every 50 ms thanks to a bokeh server. Here is a screenshot with and without webgl + my code.

Thx for your work.

Edit : Same behavior at lower framerate (500 ms)

With webgl
![index](https://cloud.githubusercontent.com/assets/7406885/16363410/59e077f2-3bc9-11e6-8a73-fe092e84aaab.png)

Without webgl
![index2](https://cloud.githubusercontent.com/assets/7406885/16363411/59f63b78-3bc9-11e6-9d7d-38a81224f1d5.png)

`from bokeh.plotting import figure, show, output_server, curdoc
from numpy import random, arange

p = figure(title="Server Plot", webgl=False)
line = p.line(arange(512), random.rand(512))

def update():
     line.data_source.data["y"] = random.rand(512)

curdoc().add_periodic_callback(update, 50)

output_server()
show(p)
`

**Comment by birdsarah** [comment]
which version of bokeh are you using. i recall an issue like this being resolved. ping @almarklein

**Comment by Paradoxeuh** [comment]
I'm using Bokeh v0.11.1

**Comment by bryevdv** [comment]
This is a screen shot (OSX/Chrome) from `master` with `webgl=True`, is this what you are expecting?

<img width="648" alt="screen shot 2016-06-27 at 2 57 42 am" src="https://cloud.githubusercontent.com/assets/1078448/16372601/0822efd6-3c13-11e6-87f0-3cfa6e4a866d.png">

**Comment by Paradoxeuh** [comment]
It is, so I guess it depends on the OS/Browser we use. I'm on Ubuntu 16.04/FF 47.0. I'll try with Chrome.

Thanks for your answers !

**Comment by bryevdv** [comment]
@Paradoxeuh I am using pre-release code. The issue was present in `0.11.1` but has been subsequently fixed, and will be in the **next** release.

**Comment by bryevdv** [comment]
Since the issue appears to have been fixed, I am closing this. Please feel free to re-open if the issue persists with `0.12`
