### ISSUE TITLE
bokeh docs page always claims to refer to a previous version

### ISSUE THREAD

**Issue by talumbau** [bokeh/bokeh#4688]
This text is currently always at the top of the bokeh docs page:

<img width="1132" alt="screen shot 2016-06-28 at 11 02 43 am" src="https://cloud.githubusercontent.com/assets/1891418/16423047/1d45b14c-3d20-11e6-8731-80dd274e127b.png">

Not sure where to file this, but I'm sure someone can point me to the right place.

**Comment by damianavila** [comment]
Please hard-reload your browser and you should no longer see the warning.

**Comment by talumbau** [comment]
truth! thanks. closing.

**Comment by bryevdv** [comment]
Well if there's a way to make it not do that, we should make it not do that

**Comment by damianavila** [comment]
Some info here: http://stackoverflow.com/questions/118884/how-to-force-browser-to-reload-cached-css-js-files
