### ISSUE TITLE
Docs Version Dropdown Has Extra 0.11.1

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4692]
<img width="125" alt="screen shot 2016-06-29 at 9 03 12 am" src="https://cloud.githubusercontent.com/assets/19802403/16455156/f5c810b0-3dd8-11e6-84ad-06cac7ef7664.png">

**Comment by HuntJSparra** [comment]
@damianavila 
Issue has returned, presumably due to the work being done on the search feature.
<img width="164" alt="screen shot 2016-07-07 at 8 51 07 am" src="https://cloud.githubusercontent.com/assets/19802403/16655441/fa078a32-441f-11e6-8ceb-aacb2767b4df.png">

**Comment by bryevdv** [comment]
It's fixed in master, but this isn't going to go away on the actual site until the docs are re-deployed which has not happened.
