### ISSUE TITLE
Avoid showing <Bokeh Notebook handle for In[xx]> in Jupyter notebook

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#4697]
As much as I like to fill my notebooks with Bokeh plots, I find the return value of show (p) annoying and distracting, e.g. `<Bokeh Notebook handle for In[6]>` in 
http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/gallery/texas.ipynb

I personally do not use the handle that is returned, and so I'd be happier if `show()` just didn't return anything unless specifically requested in the call, as in `show(p,notebook_handle=True)`.  But if using the  handle is common for others, that might be tricky to change now.  

Maybe an option could be given to change this behavior at the start, as in `output_notebook(return_handles=False)`?

I'd even be ok with having `repr(handle)` or `str(handle)` (whichever one the notebook is showing) be "", but that's just because I never use the things. :-)

**Comment by jbednar** [comment]
BTW, I actually find it confusing that the output value for the cell isn't the plot itself.  I would have expected to see "Out [6]" next to the start of the plot, but instead it comes after.  To me, the output of the input cell should be the plot, because the input cell is creating a plot, but presumably there are technical reasons this doesn't happen in bokeh.  For what it's worth, that's how HoloViews works:

![image](https://cloud.githubusercontent.com/assets/1695496/16471118/572d24ca-3e20-11e6-8f44-0e0744ed32d7.png)

**Comment by rs2** [comment]
Just add a semi-colon at the end of the line that suppresses the output?

**Comment by jbednar** [comment]
That works, thanks. I think it will be mysterious to other Python programmers, but it does the job!

**Comment by damianavila** [comment]
> That works, thanks. I think it will be mysterious to other Python programmers, but it does the job!

Probably mysterious for other Python programmer but not so mysterious for Jupyter notebook users.

**Comment by jbednar** [comment]
If that's the approach the Bokeh maintainers would suggest for people using Bokeh in Jupyter, maybe the Bokeh examples should all have the semicolon added so that people will embrace it?

**Comment by damianavila** [comment]
> If that's the approach the Bokeh maintainers would suggest for people using Bokeh in Jupyter, maybe the Bokeh examples should all have the semicolon added so that people will embrace it?

Since the handle have some reasons to be visible from the Bokeh side, I would say that we need at least to mention this on the Bokeh docs for people not caring about the output. Not sure about the examples change...

**Comment by bryevdv** [comment]
I'm open to suggestions here... The goals are to be able to get the cell-specific handle that has wraps the notebook_comms for the bokeh doc that was published in a particular cell (so that it can be passed to `push_notebook` to update the plot in that specific cell). If there is some other or better way to do that, please speak up. Maybe we could keep a registry just like `In` and `Out`, `bokeh.io.Cell` or something. The other issue is they are (can be) somewhat big and expensive...

**Comment by damianavila** [comment]
I think the current implementation is clear, I would say just a mention in the docs about the possibility to get rid of the output with the semicolon is enough.

**Comment by bryevdv** [comment]
Well it also precludes the notion of having a rich repr for plots, and also the "registry" ids a might work better with the fixes that are in the other PR for "Run All" so I think it bears some discussion

**Comment by rs2** [comment]
Please bear in mind that bokeh handle is crucial for pushing updates to a particular plot, if you have more than one in your app, using bokeh.io.push_notebook. I'm upvoting the need for the return value.

**Comment by bryevdv** [comment]
@rs2 I am not proposing eliminating the capability in any way, only suggesting that it may be the case that some other mechanism for providing the handles may be much better. That would represent a breaking change, but better to find that out sooner than later. Specifically I am proposing something like:

```
from bokeh.io import Cell

# stuff

push_notebook(handle=Cell[17]) # handle for cell 17
```
A question is, can old handles be reaped? @damianavila is there any event when a cell is re-eval'ed and the old output cell is replaced with a new one?

**Comment by damianavila** [comment]
> A question is, can old handles be reaped?

What do you mean with that? Btw, I am not aware of any event like the one you described.

**Comment by bryevdv** [comment]
> What do you mean with that? Btw, I am not aware of any event like the one you described.

I mean when `In[7]` is re-executed, and `Out[7]` turns into `Out[34]` I want to be able to delete and old handle that might exist for `Out[7]`

**Comment by jbednar** [comment]
Seems like anything that is referring to cells by number will be brittle (breaking as cells are added and deleted), but I'm not sure how people use push_notebook in practice.

**Comment by bryevdv** [comment]
There's probably not a better solution to this than returning the handle directly. I agree it's ugly but the possibility for out-of-order execution basically breaks every happy assumption that might lead to something better.

**Comment by bryevdv** [comment]
I'd be OK considering a `kwarg` to make requesting a handle be explicit, though.

**Comment by jbednar** [comment]
Me too; seems like needing the handle is a relatively rare case, and confusing to everyone else.

**Comment by bryevdv** [comment]
Propose Jim's suggestion:

```
h = show(p, return_handle=True)  # defaults to false
```

**Comment by jbednar** [comment]
I'd be very happy with that.  People may also want to set return_handle=True in general (e.g. just to make their old code work); not sure if there is an easy way to provide that in Bokeh.

**Comment by damianavila** [comment]
> There's probably not a better solution to this than returning the handle directly. I agree it's ugly but the possibility for out-of-order execution basically breaks every happy assumption that might lead to something better.

Yep...

> Propose Jim's suggestion:

Sounds OK to me.

**Comment by bryevdv** [comment]
This was done, so I am closing this discussion

**Comment by jbednar** [comment]
Thanks!!
