### ISSUE TITLE
Feature: Add "dbl-click to reset zoom" on BoxZoomTool 

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4698]
Feature request:

Plotly has a nice interaction where a dbl click on the plot area with an active BoxZoomTool-equivalent will reset the plot ranges. See here: https://plot.ly/python/custom-buttons/

**Comment by canavandl** [comment]
For discoverability, they have a semi-transparent overlay on the right side that explains the interaction on the first time it's activated:

<img width="380" alt="screen shot 2016-06-29 at 6 33 59 pm" src="https://cloud.githubusercontent.com/assets/2198981/16472208/0aeb2a46-3e28-11e6-9b94-1d8dedf005a1.png">

**Comment by allenfrostline** [comment]
It's 2019 and I need exactly this feature... any updates?

**Comment by bryevdv** [comment]
> It's 2019 and I need exactly this feature... any updates?

If there were any updates they would be here. This would be a great issue for a new contributor, if you are interested in getting involved.

**Comment by bryevdv** [comment]
I would add: it's certainly possible for anyone to do this on their own, now, with a `CustomJS` event handler on double click events that sends a reset signal to the plot.

**Comment by allenfrostline** [comment]
Thanks. But may I ask of which object does would this js be? Would it be the figure that receives the double click event? Generally an event is attached to a widget.

**Comment by bryevdv** [comment]
I think you are asking for details about how to use a `CustomJS` on your own, which I am happy to discuss, but not on GitHub. Please open a topic on the Discourse, which is the appropriate venue for support discussions: https://discourse.bokeh.org/

**Comment by allenfrostline** [comment]
It turned out to be a one-liner (`p` is the figure object):

```py
p.js_on_event(DoubleTap, CustomJS(args=dict(p=p), code='p.reset.emit()'))
```

Hope this answer will help anyone like me a week ago. Cheers

**Comment by bryevdv** [comment]
Proposed at spring: Add to current `ResetTool`:

* `event_type: "doubletap" as "doubletap"`
* a corresponding `_doubletap` method that calls `this.plot_view.reset()` 

We might also want ot make this configurable if users want to disable it (e.g. to add other differnet double tap handlers)

**Comment by bryevdv** [comment]
Removing GFI as this is a little more involved and needs some discussion
> So think applying the GFI label to this issue might have been over-optimistic. Looking a little close, doubletap does participate in all the gesture-handling logic of the toolbar. I think some discussion is in order to determine the way forward (that’s why it’s not a GFI…. good first issues should be ready to work on without needing further decisions or discussion) One thing might could do is simply to make ResetTool be a GestureTool instead of an ActionTool That’s a slightly breaking change, but also there may be a little additional work required since it seems tap events are consolidated into a single TapEvent with a “type” in some places and that may not be convenient for the current toolbar logic

**Comment by London38** [comment]
> > It's 2019 and I need exactly this feature... any updates?
> 
> If there were any updates they would be here. This would be a great issue for a new contributor, if you are interested in getting involved.

it's 2022 now,, I'm hoping to see this features added            ◉ ◎

**Comment by MarcSkovMadsen** [comment]
I would also very much appreciate this feature. I see my team and users expecting a double click to reset the zoom because they are used to this from other frameworks.
