### ISSUE TITLE
Improve PyPy compatibility

### ISSUE THREAD

**Issue by alec-djinn** [bokeh/bokeh#4701]
Running the following code using PyPy and Jupyter notebook will raise several exceptions:

```
import numpy as np
import random
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
import bokeh

# plot inline
output_notebook()

# prepare some data
x = range(100)
y = [random.randint(0,100) for i in x]

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

# show the results
show(p)
```

The issue is related to the fact that numpy for PyPy doesn't have np.datetime64 implemented yet.
The solution is quite easy to implement and it is roughly described here: [http://stackoverflow.com/questions/37570376/is-there-any-2d-plotting-library-compatible-with-pypy/37588552#37588552](http://stackoverflow.com/questions/37570376/is-there-any-2d-plotting-library-compatible-with-pypy/37588552#37588552)

**Comment by bryevdv** [comment]
Can you try to work up a PR?

**Comment by alec-djinn** [comment]
Done
