### ISSUE TITLE
Focus: Notebook Stability and Improvements

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4703]
The notebook integration is currently shaky and not as performant as desired. This epic covers issues related to a comprehensive evaluation and improvement of Bokeh in the notebook. The issues below are a first cut, based on existing issues in the tracker, and may be modified based on discussions.

A central goal, implicit in the total collection of issues here, is to unify message handling and model synchronization by using the standard Bokeh protocol over notebook comms.

**Comment by Maggie-M** [comment]
This epic has been moved to [this project](https://github.com/bokeh/bokeh/projects/7)
