### ISSUE TITLE
Focus: Must-Have 1.0 Features 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4706]
The roadmap to a `1.0` is primarily concerned with bugfixes, stability, and performance. But there are a few high value features that woudl need to be present in anything called `1.0`. This epic collects those issues. 

The set of issues below is a first cut based on exiting issues and is subject to revision after discussion. In particular the "categorical" feature issues can probably be collected into a single issue.

**Comment by Maggie-M** [comment]
This epic has been moved to [this project](https://github.com/bokeh/bokeh/projects/1)
