### ISSUE TITLE
Investigate a test management product to help with QA (to replace "test matrix")

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4712]

**Comment by bryevdv** [comment]
I've messaged HipTest about a free OSS account, and will also take a look at Klaros TestManagement

**Comment by birdsarah** [comment]
There's also http://www.kualitatem.com/kualitee/ (I know the founders)

**Comment by bryevdv** [comment]
Until there is a dedicated group of individuals to use such a tool, it's not worth the overhead.
