### ISSUE TITLE
Multiple legend for enumerated list

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#4721]
It is possible to display several colors per glyph objects, but it is not possible to assign legend for each color.

Example of use case:
```python
enu = [0, 1, 2, 0, 1...0]
colors = {0: 'blue', 1: 'green', 2: 'red'...}
legends = {0: 'Foo', 1: 'Bar', 2: 'tata'...}
p.square(x, enu, color=colors, legend=legends)
```

Today the only way to have the needed plot it is to split `enu` column to individual enumerated lists and assign a color and legend for each.

The solution, it is suboptimal, adding more memory needed if I keep nan items or if I not I cannot use ColumnDataSource.

**Comment by birdsarah** [comment]
Duplicate: #3856
