### ISSUE TITLE
Possible speedup of model validation

### ISSUE THREAD

**Issue by danaki** [bokeh/bokeh#4735]
In my toy project with data shape (8033, 9) I see top 2 calls in profiler:

```
Calls   Total Time (ms) Per Call (ms)   Cumulative Time (ms)    Per Call (ms)   Function
171290  642.655 0.0038  1472.878    0.0086  /bokeh/core/properties.py:923(validate)
211867/112752   293.256 0.0014  2114.824    0.0188  /bokeh/core/properties.py:240(is_valid)
```

Taking about a minute in sum. I guess that pandas data frame already do some type checking and there's no reason to double validate. The rough estimates give about 2 validate() calls per data cell. Is it possible to reduce the number of unnecessary validations?

**Comment by bryevdv** [comment]
Quite possibly, but it's much more likely if you can provide some sample code to reproduce this situation.

**Comment by danaki** [comment]
I'm using flask with module Flask-profiler. Would you agree if I provide such sample app? I don't know how to use python's command line profiler yet.

**Comment by bryevdv** [comment]
Well, will take what you can provide, but ideally could extract just the parts relevant to Bokeh into a minimal test case. 

Like, this might just be a case of non-optimal usage that we need to document and warn against. But it's impossible to speculate without seeing what you are actually doing.

**Comment by danaki** [comment]
Ok, here it is:
```
import pandas as pd
from bokeh.charts import Bar
import cProfile


d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']), 'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
cProfile.run("p = Bar(df, label='a', stack='b')")
```

output related to properties.py:
```
      152    0.000    0.000    0.000    0.000 properties.py:136(_name)
       33    0.000    0.000    0.000    0.000 properties.py:140(default)
       18    0.000    0.000    0.000    0.000 properties.py:158(matches)
       18    0.000    0.000    0.000    0.000 properties.py:176(transform)
       47    0.000    0.000    0.000    0.000 properties.py:179(validate)
    29/10    0.000    0.000    0.001    0.000 properties.py:182(is_valid)
       48    0.000    0.000    0.001    0.000 properties.py:190(_get)
       48    0.000    0.000    0.001    0.000 properties.py:195(__get__)
       18    0.000    0.000    0.001    0.000 properties.py:203(__set__)
       80    0.000    0.000    0.001    0.000 properties.py:342(accumulate_from_subclasses)
        4    0.000    0.000    0.001    0.000 properties.py:359(__init__)
    73/46    0.000    0.000    0.002    0.000 properties.py:366(__setattr__)
        3    0.000    0.000    0.002    0.001 properties.py:380(clone)
        3    0.000    0.000    0.000    0.000 properties.py:390(properties_with_refs)
        3    0.000    0.000    0.000    0.000 properties.py:401(properties_containers)
       74    0.000    0.000    0.001    0.000 properties.py:410(properties)
        3    0.000    0.000    0.000    0.000 properties.py:442(changed_vars)
        3    0.000    0.000    0.000    0.000 properties.py:455(changed_properties)
        3    0.000    0.000    0.000    0.000 properties.py:458(changed_properties_with_values)
       74    0.000    0.000    0.001    0.000 properties.py:461(class_properties)
       17    0.000    0.000    0.000    0.000 properties.py:487(validate)
        6    0.000    0.000    0.000    0.000 properties.py:529(validate)
        6    0.000    0.000    0.001    0.000 properties.py:607(validate)
       15    0.000    0.000    0.000    0.000 properties.py:611(<genexpr>)
        6    0.000    0.000    0.000    0.000 properties.py:636(_is_seq)
        3    0.000    0.000    0.000    0.000 properties.py:669(validate)
        3    0.000    0.000    0.000    0.000 properties.py:674(<genexpr>)
        1    0.000    0.000    0.000    0.000 properties.py:733(instance_type)
        4    0.000    0.000    0.000    0.000 properties.py:745(validate)
       23    0.000    0.000    0.000    0.000 properties.py:838(type_params)
    15/11    0.000    0.000    0.001    0.000 properties.py:842(validate)
    32/23    0.000    0.000    0.001    0.000 properties.py:845(<genexpr>)
     10/5    0.000    0.000    0.000    0.000 properties.py:848(transform)
        6    0.000    0.000    0.000    0.000 properties.py:888(allowed_values)
        6    0.000    0.000    0.000    0.000 properties.py:892(validate)
```

47 calls of validate() for a small dataset.

**Comment by danaki** [comment]
Here:
```python
import pandas as pd
from bokeh.charts import Bar
import cProfile
import pstats
import random

d = {
    'one': pd.Series([random.randint(1, 10) for x in range(1, 10000)]),
    'two': pd.Series([random.choice('abcdeh') for x in range(1, 1000)])
}
df = pd.DataFrame(d)
cProfile.run("p = Bar(df, label='one', stack='two')", 'bokehstats')
p = pstats.Stats('bokehstats')
p.strip_dirs().sort_stats('tottime').print_stats(10)
```

produces output like this:
```
Sat Jul  2 23:40:35 2016    bokehstats

         961587 function calls (948212 primitive calls) in 0.983 seconds

   Ordered by: internal time
   List reduced from 758 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    42875    0.065    0.000    0.174    0.000 properties.py:923(validate)
   139809    0.043    0.000    0.072    0.000 {isinstance}
62871/57741    0.040    0.000    0.230    0.000 properties.py:240(is_valid)
    15062    0.027    0.000    0.377    0.000 properties.py:263(prepare_value)
     6917    0.026    0.000    0.392    0.000 properties.py:705(__setattr__)
23784/23771    0.024    0.000    0.167    0.000 properties.py:377(_get)
    24170    0.023    0.000    0.086    0.000 properties.py:1121(<genexpr>)
     9252    0.021    0.000    0.115    0.000 properties.py:422(_real_set)
      363    0.020    0.000    0.044    0.000 arrayprint.py:543(fillFormat)
54222/54153    0.017    0.000    0.019    0.000 {hasattr}
```

**Comment by bryevdv** [comment]
@danaki Thank you, that will make this much easier to look into.

As a side not, I note your two `df` columns are different lengths (1000 vs 10000), is that intentional? I am not certain that would produce meaningful output in real usage (though I am not suggesting it has bearing on the number of `validate` calls)

**Comment by bryevdv** [comment]
ping @fpliger @rothnic @havocp  My guess is that this is related to charts processing somehow, and that a similar `p.circle` call would not produce the same results, but that suspicion needs to be validated. I won't be able to look at this immediately, but I did just want to see if any ideas jump out.

**Comment by danaki** [comment]
@bryevdv No, it's my mistake. I wanted just to make the dataset bigger in order to produce more precise results. Just put any big number there.

**Comment by havocp** [comment]
If the ratio of 2 validate calls per cell remains the same as number of cells go up then I guess the performance is O(n) i.e. doing something for each cell. I'd probably proceed first by getting the stack trace for the per-cell validate calls (possibly the two different traces, that reflect validating each cell twice?).

If validation happens twice we could figure out why and potentially cut time in half by skipping one, though we'd still be O(n)

It's possible the validation code is treating these as plain old lists and not smart about data frames; if so special casing data frames could be helpful? I don't remember what the validation does but maybe we can validate the whole data frame in one shot.

Last resort could try to micro-optimize the actual per-cell code though that's probably not going to help as much as avoiding per-cell code would.

Just speculation though.

**Comment by bryevdv** [comment]
> It's possible the validation code is treating these as plain old lists and not smart about data frames; if so special casing data frames could be helpful? 

This is my guess (and hope)

**Comment by mattpap** [comment]
There are at least two reasons why this happens:

1. Validation is very slow due to its design (exceptions, eager pretty error formatting, ...).
2. Validation is triggered too often (`add() in `ColumnDataSource.__init__()` is a nice example).

**Comment by bryevdv** [comment]
moved to [bkcharts](https://github.com/bokeh/bkcharts/issues/9)
