### ISSUE TITLE
Cache aggregation data when using charts

### ISSUE THREAD

**Issue by danaki** [bokeh/bokeh#4736]
In my toy project I want to experiment with how my charts look. Since sometimes it takes a long times to aggregate data for Bar and Box plots, I spend most of the time waiting for result to appear on the screen. Is it possible to introduce a parameter for high level plot functions that will store aggregation internal data and reuse it without recomputing next time?

A parameter to Box() or Bar(), let's call it 'cache' would be a user defined object with get() and set() methods. It will be user responsibility to override it's methods in order to make it save intermediary data to disk etc.

**Comment by birdsarah** [comment]
This is a nice idea.

**Comment by bryevdv** [comment]
bokeh.charts has moved to https://github.com/bokeh/bkcharts this should be re-opened there if appropriate.
