### ISSUE TITLE
Put WebGL related code in CanvasPlot into a separate class.

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#4739]
See discussion in #4686. Some cleaning up was already done in the aforementioned PR, but it would be nice if PlotCanvas can stay agnostic about WebGL (except calling a functions in a few places).

**Comment by bryevdv** [comment]
Ideally, I would like to split all the "webgl" code into a separate `bokeh-webgl.js` JS module. This would be included in the resources automatically when `webgl=True`, but it might also be the nice if things could attempt to degrade gracefully if `webgl=True` but somehow the JS for it is not present. The motivation is that BokehJS needs to go on a serious diet, and it's not really reasonable to demand users who are just drawing small (up to thousands) of things to pay for the extra payload all the time.

**Comment by almarklein** [comment]
I agree.

**Comment by bryevdv** [comment]
this was fixed with #5233 AFAIK just did not get closed automatically

**Comment by bryevdv** [comment]
I'm going to close this one. The current larger goal is just to re-implement all rendering on top of some newer convenient webgl wrapper.

**Comment by almarklein** [comment]
Or wait for [WebGPU](https://en.wikipedia.org/wiki/WebGPU) ...

**Comment by bryevdv** [comment]
As much as I would delay love to restrict support to green-field APIs on only the newest browsers I think we will be stuck supporting relatively older platforms for quite some time. Ideally, someone would write a higher level library that can use fancy new things when they are available, and fall back to webGL when they are not. But I have no idea if anyone is planning such a thing.

**Comment by almarklein** [comment]
I expect that there would be polyfills that target WebGL; The WebGPU is quite high-level (unlike, say Vulkan). The WebGPU API can actually be implemented with desktop GL (they plan to do that [here](https://github.com/gfx-rs/wgpu). WebGL (also 2.0) would be missing a few features, but probably close enough for most stuff...

**Comment by bryevdv** [comment]
we will add it to the list of things to take a look at, this is 2020 work in any case
