### ISSUE TITLE
Easily control aspect ratio

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#474]
Includes being able to set aspect (e.g. if you want `1:1` aspect) and also have resize and zoom tools, etc. respect the existing aspect ratio.

**Comment by damianavila** [comment]
Interesting idea: https://github.com/bokeh/bokeh/issues/2522#issue-93385094

**Comment by cwhy** [comment]
I feel this limitation should gain more attention, at least for the aspect_ratio=1 case.
Now in bokeh there is no way to display a full image in its original aspect ratio.
If x_range and y_range is not set, open part of the image will be shown. If they are set, the image will be resized to the full figure size and will be distorted.

**Comment by bryevdv** [comment]
Hi @cwhy I agree this is a very important issue, but importance is unfortunately not the only issue to consider. There is also the unavoidable matter of available (human) resources, as well as the entire context of other competing (important) priorities, as well as any blockers that affect the order of work. In this case this feature has long been blocked by the need to re-vamp the low level layout system entirely first. To do otherwise would be to commit resources to "bolt on" a quick fix that would only get thrown away. With a very limited amount of time/work between the current team, that is jut not justifiable. 

However, the large layout work has been completed (or largely completed), so this implementation  feature can finally *begin* to be discussed in detail. Unfortunately we are also passed the point where we can "experiment" with APIs. Since this feature will require new APIs we have to be *certain* that its the right one, so there is a higher planning, testing, documentation burnen. Would you care to start the discussion? If you can describe how you might like to be able to "spell" this in Bokeh, that would be helpful.

**Comment by cwhy** [comment]
Hi @bryevdv, I feel that a similar one as matplotlib is quite sufficient.(http://matplotlib.org/api/axes_api.html#matplotlib.axes.Axes.set_aspect)
As for Bokeh, it would be something like 
f = bokeh.plotting.figure(aspect_ratio=1)
or 
f = bokeh.plotting.figure()
f.aspect_ratio=1

For the box-zoom function, if the aspect ratio is fixed, the box can be forced to the same ratio as well. Alternatively, just allow box-zoom to break the ratio.

Really appreciate the work on Bokeh from your guys~

**Comment by physinet** [comment]
I can't offer an elegant solution to this problem, but I've got something that almost works well enough for me. The problem I'm running into is that `fig.plot_width` and `fig.plot_height` include axes, titles, etc, but I'd like to control just the width and height of just the plot area. Any advice?

**Comment by jsignell** [comment]
This is a big deal in geo contexts as mentioned in [#2522](https://github.com/bokeh/bokeh/issues/2522#issue-93385094). The aspect ratio is respected by the wheel zoom and pan tool right? So probably the easiest solution is just to turn off the box-zoom tool, so that the user doesn't have access to tools that allow distortion.

**Comment by birdsarah** [comment]
> The aspect ratio is respected by the wheel zoom and pan tool right?

Just to be super clear. The answer to this question is "not always".
1) If you are hovered over an axis and do a wheel zoom, it will wheel zoom for that axis only stretching the plot out (@bryevdv I wonder whether we should remove that feature in favor of something more explicit)
2) It used to be that if you panned and had range bounds then the plot could get stretched out - but I may have fixed that.

**Comment by Imperssonator** [comment]
I'd like to add my support to this issue. As a materials scientist, I've started using bokeh to plot spatially-resolved structural data and I love the interactivity. Unfortunately the aspect ratio of nature is fixed, at least at sub-relativistic velocities.

**Comment by bryevdv** [comment]
@StevenCHowell FYI I have scheduled this for `0.12.7` I think all the necessary groundwork around layout is finally in place

**Comment by crashMOGWAI** [comment]
I agree aspect ratio manipulation is an important feature to have, but I have found the wheelzoom axis only stretching feature very convenient. @birdsarah I vote to keep it around.

**Comment by bryevdv** [comment]
The wheel zoom is very useful, but it should be made more configurable (i.e. off-able if you don't want it)

**Comment by bryevdv** [comment]
#6784 is a very promising PR we will iterate on it and get it merged ASAP after `0.12.7` is released
