### ISSUE TITLE
Feature request: Add bokeh.charts.defaults.legends=False to hide legends

### ISSUE THREAD

**Issue by danaki** [bokeh/bokeh#4742]
Found no mention in CHANGELOG so I suppose it's an unpredictable behavior or a missing documentation issue. It even not a problem, I could find an argument to switch off legends on every chart but is there a possibility to change such behavior (and other defaults) by providing a global option bokeh.charts.defaults?

**Comment by bryevdv** [comment]
ping @fpliger

**Comment by canavandl** [comment]
Without git bisecting the commit history, it's unclear to me why the legend behavior changed. I'd think it was accidentally introduced.

Apart from setting the `legend=False` kwarg inside of every chart class, it would be nice to have legends configurable from bokeh.charts.defaults. I'm going to rename this issue as a feature request to add that capability.

**Comment by bryevdv** [comment]
`bokeh.charts` had been moved to https://github.com/bokeh/bokeh/issues/4742

This issue should be re-opened there if necessary.
