### ISSUE TITLE
box selection should be based on Range model(s)

### ISSUE THREAD

**Issue by lawremi** [bokeh/bokeh#4745]
A common application of coordinated multiple views is to have an overview paired with a plot restricted to the region selected in the overview plot. Currently, this can only be done using a Javascript callback (I think). It would be nice if the box selection tool was based on a tuple of `Range1d` objects (which I guess would be a `Range2d`), so that we could use the range model as, e.g., the `x_range` on a plot. If this sounds reasonable, I could submit a PR.

**Comment by bryevdv** [comment]
Sorry this got overlooked and went untriaged. I think at this point a new `RangeAnnotation` would be needed.

**Comment by bryevdv** [comment]
I'd consider this a duplicate of https://github.com/bokeh/bokeh/issues/7795
