### ISSUE TITLE
bokeh.mpl.to_bokeh does not seem to handle sns.swarmplot correctly

### ISSUE THREAD

**Issue by gonike** [bokeh/bokeh#4746]
Here's an example of the problem:

```
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import bokeh.mpl
from bokeh.plotting import output_file, show

df = pd.DataFrame({'a': [1,1,1,1,2,2,2,2], 'b': [1,2,3,4,5,6,7,8]})
mplfig = plt.figure()
ax = mplfig.add_subplot(1,1,1)
sns.swarmplot(data=df, x='a', y='b', ax=ax)
# plt.show()
bokehfig = bokeh.mpl.to_bokeh(mplfig)
output_file("test.html")
show(bokehfig)
```
This just produces an empty gray axes box without axes labels, descriptions and anything inside it. It does not produce any errors, though. When replacing `swarmplot` by `violinplot` and leaving everything else untouched, everything seems to work fine and the resulting html file looks good. Note that `plt.show()` shows a correctly drawn swarmplot.

**Comment by bryevdv** [comment]
@gonike Bokeh relies on `mplexporter` an upstream library, for MPL support. It is not complete, and we have tried to make it clear in the docs that current MPL support is not complete. 

Comprehensive and robust support for MPL compatibility will ultimately depend on MEP 25 coming to pass (https://github.com/matplotlib/matplotlib/wiki/MEP25) But that work is being developed by the MPL team and the schedule is not under our control.
