### ISSUE TITLE
Custom CSS in Jupyter Notebooks

### ISSUE THREAD

**Issue by AlbertDeFusco** [bokeh/bokeh#4749]
I was attempting to use `bokeh.resrouces.Resources` to create a Resources object with custom CSS, particularly for the HoverTool. I order to do this I had to subclass Resources and write a method to add my own CSS. It would be really great if something like this was available.

``` python
from bokeh.resources import Resources

class myCDN(Resources):
    def add_css(self, input_css):
        _, self.extra_css = self._resolve('css')
        self.extra_css.append(input_css)

    @property
    def css_raw(self):
        _, raw = self._resolve('css')
        raw.extend(self.extra_css)
        return raw
```

An [example notebook](https://anaconda.org/defusco/custom-tooltips/notebook) is on my Anaconda Cloud channel.

**Comment by bryevdv** [comment]
@mattpap is working on similar things as part of other issues, so I will close this.
