### ISSUE TITLE
0.12: Axes conflict with toolbars with same position

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#4750]
This appears to be an issue relating to 0.12 where the toolbar conflicts with the axes if they have the same orientation, a live example is available here: https://sne.space/sne/SN2011by/, here's a screenshot of the behavior:
![image](https://cloud.githubusercontent.com/assets/4998058/16589459/eac9a734-42db-11e6-9170-b88f61367cdb.png)

Code for generating this plot is:
```python
        p2 = Figure(title='Spectra for ' + eventname, x_axis_label=label_format('Observed Wavelength (Å)'),
            y_axis_label=label_format('Flux (scaled)' + (' + offset'
            if (nspec > 1) else '')), x_range = x_range, tools = tools, #responsive = True,
            plot_width = 475, plot_height = 485, y_range = y_range, toolbar_location = 'above')
```

**Comment by bryevdv** [comment]
This was documented in the Migration Guide, there is a new `toolbar_sticky` setting which is `True` by default (because it works generally well and looks better with the new default right side toolbar location). But if you can't or don't want a toolbar on the right, you can set `toolbar_sticky=False`

**Comment by bryevdv** [comment]
FWIW I think in this particular case `toolbar_location = 'right'` (leaving `toolbar_sticky=True`) would look best, but I can also imagine you have other considerations or constraints that would make keeping it on top important.

**Comment by guillochon** [comment]
So I can have axes on all four sides of the plot. When I had it on the right-hand side, it was also overlapping with the axes. It is not just restricted to the top.

Also, the migration guide should be made more explicit; there is no reference to the `toolbar_sticky` option on either this page: http://bokeh.pydata.org/en/latest/docs/releases/0.12.0.html, or this page: http://bokeh.pydata.org/en/latest/docs/user_guide/layout.html

**Comment by guillochon** [comment]
Here I have not changed the `toolbar_location` option and the tools overlap with the right-hand axes: 
![image](https://cloud.githubusercontent.com/assets/4998058/16591209/72005eda-42e3-11e6-8d91-0456d75d7ba7.png)

This seems like a bug to me, currently you cannot have unsticky tools for a plot with axes on all four sides.

**Comment by bryevdv** [comment]
Oh weird, I know I wrote some more detailed notes about `toolbar_sticky` I thought they went into the migration notes but they seem to have gotten lost somehow. It was 12-16 hours days leading up to this release, apologies the omission, a result of simple human limits. Can you open an issue regarding better documentation for `toolbar_sticky` ?

**Comment by bryevdv** [comment]
@guillochon It's hard to say without seeing code. are you saying you set `toolbar_sticky=False` in that last plot?

**Comment by bryevdv** [comment]
To be more explicit: toolbars are *always* sticky now by default, you have to explicitly ask for non-stickiness by setting, e.g. `p.toolbar.toolbar_sticky = False`

**Comment by guillochon** [comment]
@bryevdv No, not touching `toolbar_sticky` or `toolbar_position` in that last plot. Code is:

```python
p1 = Figure(title='Photometry for ' + eventname,
    y_axis_label = 'Apparent Magnitude', tools = tools, plot_width = 485, plot_height = 485,
    x_range = (min_x_range, max_x_range), y_range = (min_y_range, max_y_range))
```

**Comment by bryevdv** [comment]
@guillochon The danger in any very flexible compositional system like Bokeh is that it can sometimes be possible to make combinations that don't make sense. This is one of those instances. We have optimized to make many common cases as good looking as possible, at the expense that some other cases that are less common (axes on all four sides) may need additional tweeks. 

We do try to help warn people about combinations that might not make sense, though. In fact, I would have expected you to see a validation warning here, did you not? Can you provide a complete example? It's very difficult to focus the discussion without running actual code.

**Comment by bryevdv** [comment]
Perhaps this concrete example will help you:
```
In [8]: from bokeh.plotting import figure, show

In [9]: from bokeh.models import LinearAxis

In [10]: p = figure()

In [11]: p.add_layout(LinearAxis(), 'right')

In [12]: p.add_layout(LinearAxis(), 'above')

In [13]: p.toolbar_sticky = False

In [14]: p.circle([1,2,3,4,5], [4,6,2,7,8])
Out[14]: <bokeh.models.renderers.GlyphRenderer at 0x101adb240>

In [15]: show(p)
```

<img width="604" alt="screen shot 2016-07-05 at 12 34 47 pm" src="https://cloud.githubusercontent.com/assets/1078448/16593830/e63d0604-42ac-11e6-9165-1345de21e029.png">

**Comment by bryevdv** [comment]
BTW the plots look quite interesting. I you'd be interested in writing something up about how you use bokeh in your domain, we have a new blog
