### ISSUE TITLE
0.12: Missing `toolbar_sticky` documentation on migration guide

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#4752]
There is no reference to the `toolbar_sticky` option on either this page: http://bokeh.pydata.org/en/latest/docs/releases/0.12.0.html, or this page: http://bokeh.pydata.org/en/latest/docs/user_guide/layout.html.

**Comment by bryevdv** [comment]
There's not much point in updating the old release notes at this point. The `toolbar_sticky` property is documented here:

http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#positioning-the-toolbar

so the layout page should probably just get a note with a link to that.

**Comment by bryevdv** [comment]
comment was added in https://github.com/bokeh/bokeh/pull/6506/commits/73e4552f3e2c3a5c85380b8bd135f527042729f9 This issue will close as soon as that PR is merged.
