### ISSUE TITLE
bokeh.palettes missing qualitative Brewer color maps

### ISSUE THREAD

**Issue by caryan** [bokeh/bokeh#4758]
Is there a reason the qualitative color maps are not included in `bokeh.palettes`?  I can send a PR if they weren't deliberately omitted. One issue is they wouldn't fit the naming convention e.g. how do you name the `Dark2` with 5 colors? `Dark2_5`?

**Comment by bryevdv** [comment]
A PR would be very appreciated. Please be sure to just note any provenance or licensing in comments in the `palettes.py`. I don't have strong feelings about the names, perhaps submit the PR and we can solicit the rest of @bokeh/dev for any opinions?
