### ISSUE TITLE
Reset button no longer appears on gridplots

### ISSUE THREAD

**Issue by patrickfuller** [bokeh/bokeh#4759]
After updating, gridplots no longer shows reset button. Example:

![no_reset](https://cloud.githubusercontent.com/assets/1449833/16620531/6c037c9a-4358-11e6-99f9-cf8264165000.png)

Code as plaintext:

```python
from bokeh.io import gridplot
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import HoverTool
output_notebook()

import bokeh
bokeh.__version__

first = figure(width=800, height=300, tools='pan,ywheel_zoom,box_zoom,reset,hover,save')
first.line([1, 2, 3], [4, 5, 6])
second = figure(width=800, height=300, tools='pan,ywheel_zoom,box_zoom,reset,hover,save')
second.x_range = first.x_range
second.line([1, 2, 3], [6, 5, 4])
p = gridplot([[first], [second]])
show(p);
```

**Comment by jbednar** [comment]
We had noticed that too and were trying to figure out what the problem was...

**Comment by bryevdv** [comment]
Will push another dev build tomorrow of Friday. FYI planning a `0.12.1` tiny bug fix release in a few weeks.

**Comment by bryevdv** [comment]
Fix in master
