### ISSUE TITLE
simplify passing information between bokeh app and autoload_server caller to permit controlling custom plots with widgets

### ISSUE THREAD

**Issue by jdimatteo** [bokeh/bokeh#4765]
Today there was some discussion between @bryevdv, @canavandl, and @jdimatteo on bokeh's gitter about a feature to pass URL arguments to new sessions.

The following repo shows a sliders bokeh app example:

https://github.com/beenje/flask_bokeh_app/blob/master/app.py

It would be helpful to pass additional info to the bokeh app when autoload_server is called in app.py:

```
autoload_server(model=None, app_path="/sliders")
```

For example, passing some id so that data specific to that id is plotted.

The general usage of plotting custom data and updating the plots with widgets seems unclear.  The happiness example doesn't appear to have any widgets: https://github.com/bokeh/bokeh-demos/tree/master/happiness .

I made some attempt at getting widgets working in a scenario where custom plots could be created in a flask app, but the widget callback "update_title" never got called:

https://github.com/jdimatteo/flask_bokeh_app/blob/widgets/app.py

**Comment by bryevdv** [comment]
passing of http args to server embed functions was done in https://github.com/bokeh/bokeh/pull/6415
