### ISSUE TITLE
bokeh.client example in user guide has a bug

### ISSUE THREAD

**Issue by Atlantic777** [bokeh/bokeh#4766]
There is a bug in example code in this [sphinx document](https://github.com/bokeh/bokeh/blob/09e7bc882bfaa3431593b356e0e0ae2daf52b551/sphinx/source/docs/user_guide/server.rst).

``` python
p = figure()
r1 = p.line([0, 4*pi], [-1, 1], color="firebrick")
r2 = p.line(x, y, color="navy", line_width=4)

session = push_session(curdoc())

@cosine(w=0.03)
def update(step):
    r2.data_source.data["y"] = y * step
    r2.glyph.line_alpha = 1 - 0.8 * abs(step)

curdoc().add_periodic_callback(update, 50)
session.show() # open the document in a browser
session.loop_until_closed() # run forever
```

Call to the `session.show()` function should have figure `p` for argument. This example is correct in examples directory [here](https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/line_animate.py).

I find this problem important because it took me some time to discover and solve the issue. Because the user_guide is starting point for many new bokeh users (like me) there are probably many more users affected.

I created fix (well, it was just a letter missing) and I would like to create PR connected to this issue, according to [guidelines for contributing](https://github.com/bokeh/bokeh/blob/master/.github/CONTRIBUTING.md).

Here's commit containing the fix: [Atlantic777/bokeh/commit/1225e51d9bb6b1...](https://github.com/Atlantic777/bokeh/commit/1225e51d9bb6b1e86cd7d48eeafcc5657f6edf6c)

Can you help me with merging this correction? Thanks!

**Comment by bryevdv** [comment]
Hi @Atlantic777 thanks for the catch. Can yout see if the instructions here make sense: https://help.github.com/articles/using-pull-requests/ You'll want to make  PR from your fork against `bokeh/bokeh`

**Comment by Atlantic777** [comment]
Thanks @bryevdv for the link but I got confused with putting tags on this issue. But since you've just done that, I can create PR and reference to this. If I do something wrong, please correct me. :)

**Comment by bryevdv** [comment]
@Atlantic777 ah, yes only members of @bokeh/dev can add GH issue labels, we might could be more clear about that. Thanks!
