### ISSUE TITLE
Hovertool shows incorrect values for data

### ISSUE THREAD

**Issue by carlshan** [bokeh/bokeh#4769]
I am new to Bokeh and trying to understand the API. I've set up a Jupyter Notebook and have code as follows:

```python
fake_data = {'ID': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
             'Total': [0.0, 20.0, 0.0, 6.0, 8.0, 0.0, 8.0, 5.0, 8.0, 1.0, 2.0],
             'Description': ['a', 'b', 'c','d', 'e', 'f', 'g', 'h', 'i', 'j', 'k']}

hover = HoverTool(
    tooltips = [
                ('ID', '$x'),
                ('Description', '@Description')
        ]
)

p = Scatter(data=fake_data, 
            x='ID', 
            y='Total', 
            tools=[hover])

output_notebook()
show(p)
```

However, surprisingly, I see the following:

<img width="598" alt="screenshot 2016-07-07 10 59 17" src="https://cloud.githubusercontent.com/assets/1524687/16663681/e0fd94d4-4431-11e6-9ac7-a1c96575299e.png">

The two things that concern me are:

1. The 'ID' values being displayed in the hovertool are not present in my data.
2. 'Description' does not show the data from the relevant 'Description' column in my data.

I would appreciate some insight into what is going on, and whether this is a Bokeh bug or a user error.

**Comment by bryevdv** [comment]
You've configured the "ID" field to display `$x`, which is  the x mouse position. Digging into it, it appears the correct field would be `@x_values` which is fairly cryptic. 

It appears the other column is not automatically included in the find chart data source, since it is not actually used to drive the chart. I think this is probably an area for improvement. ping @canavandl @fpliger is there any way to make this work with `Scatter` now?

As a workaround, I'd suggest using `bokeh.plotting` with the `circle` glyph renderer, the interaction of that API with the hover tool is much more straightforward. c.f. http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#hover-tool

**Comment by dhirschfeld** [comment]
I've seen this recently. Is this a difference between charts and a "normal" plot?

**Comment by bryevdv** [comment]
The glyph-based plots in `bokeh.plotting` have a very straightforward 1-1 relationship from the data to what is drawn on the screen: every visual aspect of a glyph is either a fixed value, or a column of values from a column data source. The hover tool integrates nicely with this expectation (and was also developed before `bokeh.charts` existed)

The relationship between charts is less direct. The data you pass to the chart is *not* necessarily the data that is needed to *draw*. And in fact the whole point of charts is to automatically do any grouping aggregations automatically. The data needed to *draw* is *derived* from the original data. But this means the straightforward mapping that suits the hover tool so well is not really applicable. The solution (as far as I see it) is to make what *can* be mapped in the final chart more discoverable and obvious, and also to allow "extra" columns like the one above to be passed along. Charts just have not caught up in this area yet.

**Comment by dhirschfeld** [comment]
Thanks for the info!

**Comment by carlshan** [comment]
That's helpful to understand and clarifies this behavior. I'll try replotting with the circle glyph and see how that goes.

**Comment by birdsarah** [comment]
There's an existing discussion on this same topic here: https://github.com/bokeh/bokeh/issues/4347

So marking this as duplicate.

**Comment by ldejuan** [comment]
In order to have the real values source the ColumnDataSource, the hoover tooltips should be configured as follows : 
hover = HoverTool(
        tooltips=[
            ("index", "$index"),
            ("(x,y)", **"(@x,@y)"),**
            ("desc", "@desc"),
        ]
    )
With '@' in front of x and y. IF not the behaviour is inconsistent:

**Comment by bryevdv** [comment]
If not, the behavior is undefined and unsupported. The only supported configurations are:

* generic CDS column access with `@` prefix: `@foo`, `@bar`, etc.
* a handful of special variables with `$` prefix: `$x`, `$sx`, etc. 

The discussion above regards the fact fact that charts do data manipulations, and create their own CDN columns, and maybe those column names are not obvious/easily discoverable.
