### ISSUE TITLE
Standalone Panels w/ figure as child doesn't render (server)

### ISSUE THREAD

**Issue by bgyarfas** [bokeh/bokeh#4772]
As title says. But it will render fine if it's in a Tab. No errors generated in JS or Python.

Running from a026fee

```
from __future__ import division

import numpy as np

from bokeh.plotting import figure, curdoc
from bokeh.models import Panel, Tabs

N = 512
img = np.empty((N,N), dtype=np.uint32)
view = img.view(dtype=np.uint8).reshape((N, N, 4))
for i in range(N):
    for j in range(N):
        view[i, j, 0] = int(i/N*255)
        view[i, j, 1] = 158
        view[i, j, 2] = int(j/N*255)
        view[i, j, 3] = 255

p = figure(x_range=(0,512), y_range=(0,512))

# must give a vector of images
p.image_rgba(image=[img], x=0, y=0, dw=512, dh=512)

# curdoc().add_root(p)  # Works
# curdoc().add_root(Tabs(tabs=[Panel(child=p, title='Panel', closable=True)]))  # Works
curdoc().add_root(Panel(child=p, title='Panel', closable=True)) # Doesn't work
```

**Comment by bryevdv** [comment]
I'm not sure panels were ever intended to be used like this, outside dialogs or tabs.

**Comment by bgyarfas** [comment]
Ah. The docs seemed to hint it could be standalone. Especially with the `closable` attribute. I could of sworn it used to work in the notebook around version 0.10 or 0.11.

[](http://bokeh.pydata.org/en/dev/docs/reference/models/widgets.panels.html)

**Comment by bryevdv** [comment]
Well I'm not entirely sure, we should let some others chime in about what is/should be.

**Comment by bryevdv** [comment]
Well there has been no response on this, I am inclined to close. `Panel` was definitely to be for panels *inside a tab*.
