### ISSUE TITLE
Docs: Subdivide User Guide

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4776]
The User Guide is becoming very long at this point with many extensive entries. It would be helpful if those entries were broken down into sub-entries similar to how bokeh.models in broken down in the Reference.

For example:
Adding Interactions (23 pages) could be broken down into Linking Plots (3 pages), Adding Widgets (8 pages), and CustomJS Callbacks (12 pages)

Breaking down the sections like this should (in theory) make it easier for new users to find what they are looking for and not be overwhelmed. It also gives them the illusion of faster progression when they finish a page.

**Comment by timsnyder** [comment]
I'd definitely be willing to help with work like this.  I asked about the [High-Level Charts Page](http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html) in gitter [on July 20, 2016 at 1:56 PM](https://gitter.im/bokeh/bokeh?at=578fc95175045f8767113ba7).  

High-Level Charts is 21 pages.  The page takes quite a long time to load with all of the charts on it.  I suggested that we split it into a page per chart type with a toplevel page that contains some intro material and an index of the type-specific pages.  @bryevdv [thought this sounded like a good idea](https://gitter.im/bokeh/bokeh?at=578fee35ac85f2507ae1afb2)

I would like the new "High-Level Charts" toplevel page to have a visual index simillar to (the gallery index)[http://bokeh.pydata.org/en/latest/docs/gallery.html#standalone-examples]. I worry that having a text-only list of the chart types might lose some of the current page's utility.  Some people find it easy to scrolling through a page until one of the charts grabs their eye and then drilling down.   Looking at  `gallery.rst` and then doing a bit of searching, I see the `bokeh-gallery` sphinx extension.  So, ideally that should probably be reused (possibly extended) for the new "High-Level Charts" page?

**Comment by bryevdv** [comment]
While I'd like to improve `bokeh-gallery` I think trying to re-use/re-purpose it here would be more trouble than its worth. Also, while I agree *only* text is not the most desirable, I'd also say *no* text is also not desirable. Off the cuff, I'd suggest:

* dedicated chapter for each plot type (each current section becomes a separate page)
* a main charts page with a vertical list of: screen shot and a paragraph of text for, linking to the individual chart pages. 

For simplicity's sake I'd say the main page should just have standard Sphinx sections so the sidebar nav works nicely, and internal links get generated. Then each section content can be the thumbnail and text description for that chart. 

Edit: Also I realized maybe you were thinking the same thing, with the "apps" part of the gallery,. That part is currently hand-coded. `bokeh-gallery` only handles the pure image/thumbnail stuff below.

**Comment by birdsarah** [comment]
Just a random note, I'm not sure the current docs template handles a third level of nesting - @bryevdv i think you recently ran into this, so we'd need to address that too.

**Comment by bryevdv** [comment]
Well, it seems to have a relatively minor issue with the nesting. Hopefully has a fairly simple fix. 

@timsnyder yes the screen shots could be taken manually then check them into the `sphinx/source/_images` dir. Generating screen shots, hopefully some day in the future.

**Comment by bryevdv** [comment]
Well the user guide is now many subsections so I am closing this.
