### ISSUE TITLE
Docs: Redirect header should include link to latest documentation

### ISSUE THREAD

**Issue by emmajane** [bokeh/bokeh#4784]
In Opera mini (iOS), the header for old documentation is not very useful as it contains only the text "THIS IS AN OLD VERSION" and does not include a redirect link.

The redirect link is present for Opera desktop; and Safari mobile...it's a problem specific to Opera mini for the documentation for 0.11.1. The 0.10.0 documentation is okay. I did a quick search through the code base, but I couldn't find the exact phrase.
# Works in 0.10.0

Sample URLs: http://bokeh.pydata.org/en/0.10.0/docs/user_guide/notebook.html
## Opera Mini (v14; iOS 9)

![img_1919](https://cloud.githubusercontent.com/assets/1299320/16724679/d2f9480c-474b-11e6-9591-f5168eb2afa5.PNG)
# Does Not Work in 0.11.1

Sample URLs: http://bokeh.pydata.org/en/0.11.1/docs/user_guide/notebook.html
## Opera Mini (v14; iOS 9)

![img_1869](https://cloud.githubusercontent.com/assets/1299320/16724246/bc24e9f8-4749-11e6-9fff-7d165a3f084f.jpg)
## Opera desktop:

![bokeh_docs_and_hr_info__unocha__-_flowdock](https://cloud.githubusercontent.com/assets/1299320/16724308/f907458c-4749-11e6-9fd0-f5b9de18f29a.png)
## Safari (iOS):

![img_1920](https://cloud.githubusercontent.com/assets/1299320/16724692/e4b260ba-474b-11e6-924c-715a6dadbb6f.PNG)

**Comment by birdsarah** [comment]
Thanks for the report @emmajane

**Comment by bryevdv** [comment]
I did update they last week but it seems not to show up until a here reload. Not sure how or if that can be made better yet

Thanks, 

Bryan

**Comment by damianavila** [comment]
See my comment here: https://github.com/bokeh/bokeh/issues/4688#issuecomment-229152483, maybe something along those lines??

**Comment by emmajane** [comment]
For what it's worth: although I have no memory of visiting the site previously, if I load the page in a private browser in Opera mini, the anticipated message appears:

![img_1920 1](https://cloud.githubusercontent.com/assets/1299320/16739275/3b6598ce-4791-11e6-920c-8c1c3e9e5985.PNG)

I am very comfortable with you closing this issue as "caching is horrible; already fixed". :)

**Comment by bryevdv** [comment]
missed the comment about being OK to close, will close now. Thanks!
