### ISSUE TITLE
Add a hex tiling glyph

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4786]
hex binning is useful (https://cran.r-project.org/web/packages/hexbin/vignettes/hexagon_binning.pdf) and I've seen a lot of cool hexmaps recently: http://www.theguardian.com/politics/ng-interactive/2016/jun/23/eu-referendum-live-results-and-analysis

<img width="592" alt="screen shot 2016-07-11 at 1 34 17 pm" src="https://cloud.githubusercontent.com/assets/1796208/16730682/396819cc-476c-11e6-879d-68624e486c22.png">

**Comment by crashMOGWAI** [comment]
merge with #4342

**Comment by bryevdv** [comment]
Drawing a hex glyph would be trivial, I guess the interesting part is integrating a hex coordinate system reasonably.

**Comment by birdsarah** [comment]
Well if it was basically a marker (so it was just an x y center) then users could figure it out for now.

Sarah Bird
sbird@continuum.io

**Comment by crashMOGWAI** [comment]
Would need to be more robust than a marker for feature rich binning visualizations

**Comment by bryevdv** [comment]
@birdsarah I'm -1 on adding a hard-to-use for things-people-really-want interface, and accumulating knowledge on here, SO and the mailing list that will only have to be updated/countered/deprecated later. Offhand, I think a `Hex`  glyphs might have:
```
origin = Tuple # cartesian axis coords to "anchor" hex coord system, default (0,0)

size = Float # how big the hex tiles grid is (measured along diag?)

angle = Float # global rotation about origin for the hex grid (optional)

hx = DataSpec # "hex" x coords -- should be integer only 

hy = DataSpec # "hex" y coords -- should be integer only 
```

This is off the top of my head. We should compare to what other systems do. Whatever we do, I think there are the same/similar problems that e.g. circles have in non 1-1 coordinate systems.

**Comment by stvn66** [comment]
Looking at the [matplotlib](https://github.com/matplotlib/matplotlib/blob/5443e8112842ce689d2edb738fedaf7344d41e04/lib/matplotlib/axes/_axes.py) and [R](https://github.com/edzer/hexbin) implementation of hexbin, this seems like two separate issues:
1. Adding a hexagon marker than can be used for representing data points
2. Adding a hexagonal binning and plotting algorithm  

The hexagonal binning and plotting algorithm could use hexagon markers/glyphs but this would likely lead to overlapping similar to issue #3315, in which histogram bars overlap.  Also, it makes sense for the hexagon marker (point 1) to have a symmetric shape regardless of the plot aspect ratio.  For binning and plotting data using a hexagonal grid, it would make sense to have non-symmetric hexagons which match the aspect ratio of the plot.  See attached demo showing a zoomed in version of [matplotlib's implementation](http://matplotlib.org/examples/pylab_examples/hexbin_demo.html).  
<img width="1366" alt="screen shot 2016-07-17 at 12 54 08 pm" src="https://cloud.githubusercontent.com/assets/9484229/16902224/0f5bc3c0-4c1e-11e6-92a4-f5d4329052c4.png">

**Comment by crashMOGWAI** [comment]
Agree with @stvn66. Looks like there are a couple of ideas bouncing around that could compliment each other as incremental development goals.
- hex glyph for data points/ markers
- 'respect aspect' mode for hex glyph (suggested by @brevdv in #4802)
- hex binning and plotting algorithm/ multi-purpose mesh or grid feature

**Comment by stvn66** [comment]
These examples from the [D3 gallery](https://github.com/d3/d3/wiki/Gallery) show two options of visualizing a hexbin plot: 

1. [Color Encoding](http://bl.ocks.org/mbostock/4248145) (used for the matplotlib implementation of hexbin)
2. [Area Encoding](http://bl.ocks.org/mbostock/4248146)

This second option may be more complicated to get the scaling of markers/glyphs to match the scaling of the plotting area when using different scaling for the x/y axes.

**Comment by StevenCHowell** [comment]
How much overlap is there between the bokehjs in rbokeh and python bokeh?  I just saw that rbokeh has [hexbin plots](http://hafen.github.io/rbokeh/#preview).

**Comment by bryevdv** [comment]
100% overlap, RBokeh uses the same BokehJS as-is. AFAIK (or have to assume) RBokeh supports hex charts by computing hexagon coordinates in R and drawing as `Patches`

**Comment by hafen** [comment]
That's correct.

**Comment by bryevdv** [comment]
This is obviously an old discussion but I'm interested in reviving it. I think there are two separate things, both worth doing:

* a `Hex` marker, that is just an x,y,size, angle scatter marker. This should pretty trivial. 

 * `HexTile`glyph that draws non-overlapping hex tiles in a hex tile coordinate system.

**Comment by bryevdv** [comment]
I've made #7638 to describe the marker, this issue can be for the hex tiling glyph

**Comment by bryevdv** [comment]
PR coming tomorrow

<img width="607" alt="screen shot 2018-03-22 at 22 00 46" src="https://user-images.githubusercontent.com/1078448/37812898-b9e896f8-2e1f-11e8-98a0-147e25b23ab9.png">

**Comment by birdsarah** [comment]
That's very exciting

Sent from my iPhone

On Mar 23, 2018, at 12:24 AM, Bryan Van de Ven <notifications@github.com> wrote:

PR coming tomorrow

**Comment by bryevdv** [comment]
@birdsarah do you know how the larger outlined regions in your original example are specified? I could imagine a couple of possible ways to spell that but not sure if there is a standard way

**Comment by tritemio** [comment]
In matplotlib the X-Y span is a rectangular range that is the range of the data or the regione defined by the `extent` keyword. Then, the keyword `mincnts` allows choosing a minimum count per bin for visible bins. Choosing  `mincnts=1`, shows only bins with at least one count. The result is similar to your example. With  `mincnts=0` (default), hex tiles will cover a rectangular region.

**Comment by bryevdv** [comment]
@tritemio this work is not concerned with binning, and it's not clear that core bokeh itself will have any binning built in. This PR adds a basic glyph for drawing regular (data-space) hex tiles in an axial coordinate system. This is the foundation upon which a "hexbin" command might be built (e.g. by Holoviews)

**Comment by tritemio** [comment]
I see, thanks for the clarification. So this is actually a rectangular binning plotted with contiguous hex tiles. Sorry if OT, any idea or references on how to compute (not plot) the actual hex binning?

**Comment by bryevdv** [comment]
> So this is actually a rectangular binning plotted with contiguous hex tiles. S

No, that is not correct. The block of the code with `floor` computes the axial *(q,r)* hex coordinate of the hexagon that contains each point, then a pandas groupby bins over those hex coordinates.

**Comment by tritemio** [comment]
Ops, thanks for the correction. I'll look into it more carefully!

**Comment by bryevdv** [comment]
@tritemio just as an update, I don't think that opaque code with floors is *correctly* doing a hex binning, at least not for the version of axial coords I am using. So we are looking to find or implement something a bit more straightforward and comprehensible

**Comment by bryevdv** [comment]
PR is merged with API docs and some examples. User's Guide docs coming in a separate PR.
