### ISSUE TITLE
Must stream updates to all existing columns 

### ISSUE THREAD

**Issue by satyag75** [bokeh/bokeh#4797]
Streaming a data frame with same  columns and index raises 'Must stream updates to all existing columns'
```
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
import pandas as pd

df = pd.DataFrame(index= pd.date_range('20160701', '20160710', freq='1T', name='time'), 
                                      columns=['X', 'Y'])
df['X'] = df.reset_index().index
df['Y'] = df.X * df.X

source = ColumnDataSource(df)
source.stream(df) 
```

**Comment by bryevdv** [comment]
Hi general support questions should go to the Bokeh mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

This is so that:

1) so that we can reserve the tracker for bug reports and feature requests
2) because there is a larger pool of potential people to answer questions. 

Additionally, please always provide *complete* error messages. In this case, the complete message is "Must stream updates to all existing columns ***(missing: time)***" The bolded part that you omitted is the clue to the problem, which I will note in passing:
```
In [22]: source.data.keys()
Out[22]: dict_keys(['time', 'X', 'Y'])

In [23]: df.keys()
Out[23]: Index(['X', 'Y'], dtype='object')

```
is that `df` does not have a "time" column.

**Comment by satyag75** [comment]
Hi, point taken about the process. That said, this is still an issue, so not sure why this was closed. Note that the ColumnDataSource was created and stream'd using the same dataframe with no structural changes to the dataframe in between (there is no addition or deletion of columns going on here), and it still fails. It seems both the constructor and stream() are converting 'time', the index, to a regular column, but the check in stream() is not taking index in to account. 

In fact, this also fails with a simple dataframe with default index. For example:

> In [13]: df = pd.DataFrame({'X' : range(100)})
> In [14]: source = ColumnDataSource(df)
> In [15]: source.stream(df)
>
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-15-fdf154a68872> in <module>()
> ----> 1 source.stream(df)
> 
> e:\3rdParty\Enthought1.5.5b\lib\site-packages\bokeh\models\sources.pyc in stream(self, new_data, roll
> over)
>     231                 raise ValueError("Must stream updates to all existing columns (missing: %s, e
> xtra: %s)" % (", ".join(sorted(missing)), ", ".join(sorted(extra))))
>     232             elif missing:
> --> 233                 raise ValueError("Must stream updates to all existing columns (missing: %s)"
> % ", ".join(sorted(missing)))
>     234             else:
>     235                 raise ValueError("Must stream updates to all existing columns (extra: %s)" %
> ", ".join(sorted(extra)))
> 
> ValueError: Must stream updates to all existing columns (missing: index)
>

**Comment by abudis** [comment]
Hey, I don't know if this is still relevant, but instead of passing a DataFrame, you can try to pass a dict:
`source.stream(df.to_dict(orient='list'))`. This helped me at least.
Cheers,
Artem.

**Comment by snowch** [comment]
This should probably be reopened?  I've just run into the same issue: https://stackoverflow.com/questions/44829730/error-thrown-from-periodic-callback-valueerrormust-stream-updates-to-all-exis

**Comment by bryevdv** [comment]
Bokeh no longer adds an index as if `0.12.6` what version are you using? (Always import to provide this information)

**Comment by snowch** [comment]
@bryevdv I'm `0.12.6` and the index appears to be added:

```
>>> import bokeh
>>> bokeh.__version__
'0.12.6'
>>> import pandas as pd
>>> import io
>>> data = io.StringIO("""Date,ALL_EXCL_FUEL,MOSTLY_FOOD,NON_SPECIALISED,TEXTILE,HOUSEHOLD,OTHER,NON_STORE
... 1986 Jan,1883154,747432,163708,267774,261453,281699,161088""")
>>> df_all = pd.read_csv(data)
>>> df_all['Date'] = pd.to_datetime(df_all['Date'])
>>> from bokeh.models import ColumnDataSource
>>> source = ColumnDataSource(df_all)
>>> source.data.keys()
dict_keys(['Date', 'ALL_EXCL_FUEL', 'MOSTLY_FOOD', 'NON_SPECIALISED', 'TEXTILE', 'HOUSEHOLD', 'OTHER', 'NON_STORE', 'index'])
```

**Comment by bryevdv** [comment]
Well, the original issue was about indices being added *on the client side* by the `DataTable` widget. That's seriously problematic because the index came out of nowhere, as far as python callbacks were concerned. That's not really the case here, though. An index is part of a pandas data frame, so it's pretty natural to include that, when converting a data frames to CDS. If you don't want it, there's no reason you couldn't just delete it. 

Perhaps there can be an argument to the CDS initializer to suppress including DataFrame indices, but that'd be a new feature, so a new issue would be appropriate.

**Comment by mwathi254** [comment]
ValueError: Must stream updates to all existing columns (extra: index)


was this fixed?

**Comment by mwathi254** [comment]
or is there a way of rewriting this time series loop
what i want to happen is commented out

#on first loop: load chart
#on other loops, update the chart
    #if its not already

@without_document_lock #free document for use in multiple threads
def chartUpdate(self, dfC, dfT, dfL):                                                 #keep chart up to date
    def updateData(dfC, dfT, dfL):                                                    #stream data (all of it)
        self.source1.stream(ColumnDataSource.from_df(dfC))
        self.source2.stream(ColumnDataSource.from_df(dfT))
        self.source3.stream(ColumnDataSource.from_df(dfL))
        self.upDating = False

    if self.firstLoop: #if this is the first loop
        colRow, self.source1, self.source2, self.source3 = self.chartPlot(dfC, dfT, dfL) #use this function to 
                                                                                                                                    #make a graph and 3 
                                                                                                                                    #sources from 3 df
        p = gridplot(colRow, toolbar_location="left", responsive=True) #build plot
        self.doc = curdoc()                                                                     #make document
        self.doc.add_root(p)                                                                  #bla
        self.doc.title = "3 Streams ."                                                      #bla 
        self.session = push_session(self.doc)                                      #bla
        show_session(self.session.id)                                                  #show plot
    else:                                                                    #but on subsequent loops

        pull_session(self.session.id)                           #grab session from server
        if self.upDating:                                            #if the update is already taking place, skip it
            print("Chart Updating.")
        else:                                                                #otherwise update plot
            self.upDating = True
            self.session.document.add_next_tick_callback(updateData(dfC, dfT, dfL)) #using dfs from 
                                                                                                                                    #new loop...
                                                                                                                                    #update chart
            print("Chart Updated")
        self.session.push()                                                                                                 #update chart
    self.firstLoop = False                                                                                              #make next loop new

**Comment by bryevdv** [comment]
> was this fixed?

it would be easier to answer your question if you had included version information.
