### ISSUE TITLE
Document notebooks more visibly

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#4798]
Right now it's too easy to miss the fact that Notebook examples exist, and that Bokeh works well with Notebooks.

**Comment by bryevdv** [comment]
I'm not really sure what the state of things was ~3 years ago. Today, there is a large set of live tutorial notebooks linked from the top banner of the docs, and from the github page, as well as statically available and linked to on nbviewer. There is also an entire separate chapter in the User's guide on notebooks, as well as several notebooks in the examples. I'm going to go ahead and close this.
