### ISSUE TITLE
Glyph/Zoom Sanity Check

### ISSUE THREAD

**Issue by crashMOGWAI** [bokeh/bokeh#4802]
To draw a static circle (stays true with axis transform), are my only options line or quadratic? Just making sure the following is the intended behavior. Mostly a sanity check for myself. Although, it does seem a little counterintuitive to set a radius based on an axis, but then disregard that axis when scaling.

Start:
![plot_start](https://cloud.githubusercontent.com/assets/17650526/16822093/db4ec6fa-491f-11e6-944e-25f39ef27cb4.png)

WheelZoomOut:
![plot_wheelzoomout](https://cloud.githubusercontent.com/assets/17650526/16822140/2049eda2-4920-11e6-8f41-e998a7b90238.png)

YAxisSkew: (wheel zoom over axis)
![plot_yskew](https://cloud.githubusercontent.com/assets/17650526/16822149/2ee9f6a4-4920-11e6-87b0-9979eb707962.png)

Source:

```
import math
from bokeh.plotting import figure
from bokeh.io import show

def ring():
    arc = (2 * math.pi) / 50
    points = []
    for p in range(50):
        (px,py) = rotate(0, 1, arc * p) 
        points.append((px,py))
    return points

def rotate(x, y, r):
    rx = (x*math.cos(r)) - (y*math.sin(r))
    ry = (y*math.cos(r)) + (x*math.sin(r))
    return (rx, ry)

points = ring()
p = figure(x_range=(-1.5, 1.5), y_range=(-1.5, 1.5), 
          tools='''pan,wheel_zoom,box_zoom,reset,previewsave''')
p.circle(0,0, radius=1.25, line_color="navy", line_width=2, fill_color=None)
p.circle([-1,0,1],[-1,0,1], size=20, line_color="red", line_width=2, fill_color=None)
p.line(x=[x[0] for x in points], y=[x[1] for x in points], line_width=2)

show(p)
```

**Comment by bryevdv** [comment]
Correct, there is no scaling applied to account for a non 1-1 aspect ratio. Currently it measures pixel distances along either the x- or y- dimensions (configurable) and draws a circles with that pixel radius. It's possible a "respect aspect" mode or flag could be added to circles, but that would be a new feature.

**Comment by bryevdv** [comment]
A `match_aspect` property was recently added to plots if you require a 1-1 apsect
