### ISSUE TITLE
Assign colors to a categorical variable, which is not the label

### ISSUE THREAD

**Issue by alexpetralia** [bokeh/bokeh#4807]
This issue is based on [this S.O. question](http://stackoverflow.com/questions/38364129/bokeh-bar-plot-color-bars-by-category).

I'm trying to have a similar effect which is achieved in R [here](http://stackoverflow.com/questions/6919025/how-to-assign-colors-to-categorical-variables-in-ggplot2-that-have-stable-mappin). I asked on the `bokeh` channel but we couldn't figure out a solution.

Again, here is my code:

```
from bokeh.charts import BoxPlot, Bar, output_file, show
from bokeh.sampledata.autompg import autompg as df
output_file("bar.html")
p = Bar(df, values='mpg', label='cyl', color='origin', legend="top_left",
            title="MPG Summary (grouped and shaded by CYL)")
show(p)
```

The problem is that the legend does not show just the `origin` variable, as it would in R, but instead shows tuples of the `cyl` and `origin` variable. Is there any way to change this behavior?

_bokeh version 0.12.0_

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/52)
