### ISSUE TITLE
layout vertical alignment with buttons

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#4817]
In the notebook tutorials, the first app example in 08 - server.ipynb seems to have a messed up alignment:

![image](https://cloud.githubusercontent.com/assets/4806877/16896161/7ee08dca-4b51-11e6-88b2-9c5ee390cdc9.png)

And this is the script that generates this outcome:

```
# hello.py 

from bokeh.io import curdoc
from bokeh.layouts import column, row
from bokeh.models.widgets import TextInput, Button, Paragraph

# create some widgets
button = Button(label="Say HI")
input = TextInput(value="Bokeh")
output = Paragraph()

# add a callback to a widget
def update():
    output.text = "Hello, " + input.value
button.on_click(update)

# create a layout for everything
#layout = VBox(children=[HBox(children=[button, input]), output])
layout = column(row(button, input), output)

# add the layout to curdoc
curdoc().add_root(layout)
```

**Comment by bryevdv** [comment]
Thanks for the report! 

@birdsarah for a first simple cut at improving horizontal layouts, what do you think about vertically  centering widgets within their divs? @havocp had ideas about inter-widget constraints to make everything "equal" out but maybe simple centered would be a quick short term improvement?

**Comment by havocp** [comment]
does this work out well right now with 2 plots instead of a button and an input, or no?

It's simple enough to make buttons and inputs use the same hints and align the same as plots but I think it gets weird if you have a button next to a plot since the button might end up huge?

would have to work through some examples to document the desired behavior first and then I think more smarts around widgets could be implemented. Would be great to have that.

**Comment by birdsarah** [comment]
I don't think this is a layout thing. @bryevdv any particular reason you think that?

That wierdness is because text inputs usually have a title/label; if you set css to display none then everything is fine; If they don't have a label then we need to set them to display none. Should be a simple fix - but would probable need to make sure the whole thing re-drew correctly if the title was updated.

<img width="580" alt="screen shot 2016-07-18 at 5 52 09 pm" src="https://cloud.githubusercontent.com/assets/1796208/16933083/627456c4-4d10-11e6-8252-9ec1fdbbd672.png">

<img width="555" alt="screen shot 2016-07-18 at 5 51 27 pm" src="https://cloud.githubusercontent.com/assets/1796208/16933087/659b083e-4d10-11e6-88af-d36e756066f0.png">

**Comment by bryevdv** [comment]
Well, I think "layout" covers alot of territory, not just the "solver layout" parts. (i.e., my proposed solution was a CSS solution)

Agree that's a potentially simple fix for the no-label case. Just for discussion, what's the ideal behavior in the case *with* the label? (is there a way to make the "I'm a label" screen shot above look better too)

**Comment by birdsarah** [comment]
Just for discussion, what's the ideal behavior in the case with the label? (is there a way to make the "I'm a label" screen shot above look better too)

-- Yeah - I think there's probably a lot of tweaking - I worked on making the widgets look nice in a vertical column; horizontally there are more inconsistencies and it's a harder problem. We need to enumerate all the different cases and how we want them to look.

And (coming back to that conversation from yesterday) I think that enumeration needs to be in some kind of centralized place that's something in between documentation and tests.

**Comment by guillochon** [comment]
It seems to me that the labels should sit outside of the widget bodies, as it stands now I have to manually adjust the button positions every time with CSS, or put them on a separate line, to avoid the misalignment visible with the label in @birdsarah's example.

**Comment by bill10** [comment]
Just as a temporary fix, how to set the title of textinput to display none? Thank you.

**Comment by birdsarah** [comment]
The problem I found when building the widget layout system is one of generalization. It's good to make the label line up with the top of a button to it's left, but if there's a slider on the left or radio buttons or other things then the alignment you'd want might be different. 

In the time I had I found no good general solution and focused on having a single column of widgets be pleasingly spaced which (if I recall correctly) is why there's extra space at the top of the label.

I am -1 on making a tweak to label that doesn't take into consideration all the many different ways plots & widgets can be laid out.

I am +1 on making it much easier to tweak the position of a widget by adding some kind of offset_x and offset_y property to all widgets. 

Related to this is a wishlist I wrote a while ago: https://github.com/bokeh/bokeh/issues/2374 - specifically "Allow user to specify and id or class or both" which should make custom tweaks much easier if you're good with CSS. I also still like the custom template idea from that list too.

**Comment by birdsarah** [comment]
I'm +1 on making an option to have the label completely disappear - @bill10 - this isn't currently possible in a way that will make it align - a PR needs to be made to make is work correctly.

**Comment by drafter250** [comment]
bootstrap 4 beta is out... would their switch to flexbox help with horizontal layout issues?

**Comment by mattpap** [comment]
@drafter250, we are switching away from bootstrap (for various reasons), so this won't help. In fact this should be handled by bokeh's layout system, but currently widgets aren't first class citizens in that system, so there are lots of problems with their positioning and sizing.

**Comment by YaelGreen65** [comment]
what is the work around for this problem:
<img width="580" alt="627456c4-4d10-11e6-8252-9ec1fdbbd672" src="https://user-images.githubusercontent.com/17108645/39968409-0f8c362c-56d5-11e8-9322-0353a223dee7.png">
Thanks a lot!

**Comment by bryevdv** [comment]
Just to note, this is how things stand after #8085:

* with a title on the text input

    <img width="639" alt="screen shot 2019-02-02 at 17 37 50" src="https://user-images.githubusercontent.com/1078448/52171407-75746380-2711-11e9-9dfe-2a870847fd98.png">

* with no title on the text input:

    <img width="640" alt="screen shot 2019-02-02 at 17 38 13" src="https://user-images.githubusercontent.com/1078448/52171403-668db100-2711-11e9-9fee-c76dea601b86.png">

**Comment by bryevdv** [comment]
The placeholder version seems like it might be the best option for now. I am not sure how we get to the "ideal" version, except by exposing explicit padding options, but @mattpap  might have new ideas based on the new layout system

**Comment by bjarthur** [comment]
is there a way to have a TextInput label appear to the left of the box instead of above it and left justified?

**Comment by bryevdv** [comment]
> is there a way to have a TextInput label appear to the left of the box instead of above it and left justified?

For that put a `Div` and  `TextInput` (without a label) together in a `Row` or a `GridBox`
