### ISSUE TITLE
Hover line width

### ISSUE THREAD

**Issue by aernlund** [bokeh/bokeh#4820]
Add hover_line_width option for hover tool.

**Comment by bryevdv** [comment]
@aernlund Can you elaborate on precisely what you are asking for? There is not enough context / information for me to know for certain.

**Comment by aernlund** [comment]
Sorry, I'm completely new bokeh as well as to contributing to projects on github.  Here is example code below:

p.rect('xname', 'yname', 0.9, 0.9, source=source,
       color='colors', alpha='alphas', line_color=None,
       hover_line_color='black', hover_color='colors', **hover_line_width=2**)

When I create a hover feature for rectangles, I can choose the color of the rectangle as well as the color of the line; hover line width (in bold) does not appear to be an option currently.  Hopefully, I'm not mistaken and wasting your time with this request.

**Comment by bryevdv** [comment]
@aernlund no apologies necessary, everyone starts out new and help new comers is an important task we are very happy to do!

I would actually expect that to work, so if it is not, I would characterize that as a bug. Definitely not a waste of time! Let me try to reproduce on the most current dev build.

**Comment by masoninman** [comment]
This would be extremely helpful. I think it's also related to #2367.

**Comment by bryevdv** [comment]
FYI this works:
```
r = p.rect('xname', 'yname', 0.9, 0.9, source=source,
       color='colors', alpha='alphas', line_color=None,
       hover_line_color='black', hover_color='colors')
r.hover_glyph.line_width=4
```

It's only the convenience API in `figure` that is limited. Perhaps it can be improved, though. Will investigate for future release.

**Comment by mjarosie** [comment]
Just double checked, PR #9153 fixes this issue.
