### ISSUE TITLE
devdeps.py doesn't check for test dependencies

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4824]
Was just working @stvn66 to get tests running locally, and when running `devdeps.py` it didn't report that flake8 and boto weren't installed which are needed by the tests to run.

I may have been directing @stvn66 incorrectly though.

ping @damianavila

**Comment by damianavila** [comment]
devdeps.py get quickly out of date... we should be review to check that actually is checking the proper dependencies... changing to task.
