### ISSUE TITLE
Feature: Make GET arguments available for bokeh server apps

### ISSUE THREAD

**Issue by bkueng** [bokeh/bokeh#4828]
GET arguments are an important feature of the web, so I think they should be available for server apps. 
They are complementary to session variables (#3349) and also mentioned [here](https://github.com/bokeh/bokeh/wiki/Use-of-the-query-string-in-url-to-control-plot-properties), but for the purpose of plot configuration.

I already have [working code](https://github.com/bkueng/bokeh/commit/3dfe97f6ad64e79f7658c9393a1afd290a4361f4) for it, but as per guidelines I open an issue first.

**Comment by bryevdv** [comment]
@bkueng I think alot of people will be happy to see such an addition! 

Here are some minor comments to keep in mind for a full PR :

* `get_arguments` is very similar to a typical "getter" name, and possibly confusing. Maybe `request_args` ? or similar

* `curdoc` seems like an OK place at a glance but at least a quick discussion about whether any other place is more appropriate. ping @havocp any comments?

* will need a test and some minimal documentation (can help with both)

* Discuss making this configurable, e.g. with a `--no-request-args` command line option or something? I don't know for certain, I am just imaging some people might want to precent access to the request args in some situations, but I may be wrong.

**Comment by bkueng** [comment]
Thanks @bryevdv for taking care of this!

**Comment by bryevdv** [comment]
Thanks to @SiggyF for the help with the PR!
