### ISSUE TITLE
figure.width does not update width

### ISSUE THREAD

**Issue by jgoecks** [bokeh/bokeh#4830]
Per this discussion thread, @birdsarah noted that it is a bug that `p.width` does not update `Figure` width:

https://groups.google.com/a/continuum.io/forum/#!msg/bokeh/UPxyrOWlz2o/jmkFpezwCAAJ

**Comment by birdsarah** [comment]
@bryevdv - can you provide the historical context for `figure.plot_width` and `figure.width` - why there are two different things and what they're meant to do differently?

**Comment by bryevdv** [comment]
What is `Figure.width`? I've never seen/used it, only `plot_width` I assumed the issue was referring to that

**Comment by bryevdv** [comment]
`figure` (not `Figure`) accepts and converts a `width` kwarg to `plot_width`:

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/figure.py#L542-L549

I am surprised `Figure.width` doesn't throw an "unknown property" exception (it doesn't, I checked). Some more investigation is required.

**Comment by bryevdv** [comment]
@birdsarah `width` and `height` are new --- they come from `LayoutDOM`. This probably requires some thought. I'd be OK with deprecating `plot_width` and `plot_height` *as properties* (with a long deprecation) but I think they will have to be kept as kwargs to `figure`

**Comment by Artimi** [comment]
Any updates with this issue? I have asked in mailing list https://groups.google.com/a/continuum.io/d/msgid/bokeh/57ad6bd1-d931-41a0-b281-2cb2b23ddc91%40continuum.io?utm_medium=email&utm_source=footer but with no response. I understand that you have a lot of issues to deal with but this is the last one preventing me from update.

I can put my two cents here: I've discovered that message is passed to browser through websocket:
```
{
	"references": [],
	"events": [{
		"model": {
			"type": "Plot",
			"id": "80a949bb-ca34-4978-877b-d8a5b6a66e57",
			"subtype": "Figure"
		},
		"kind": "ModelChanged",
		"new": 321,
		"attr": "height"
	}]
}
```
So the problem probably is in bokehjs not responding to this message.

**Comment by bryevdv** [comment]
There are no updates (if there were, they would be here) There are far more issues than there are people to work on them. I can't speculate when this will be looked at more closely.

**Comment by Artimi** [comment]
Just FYI I have workarounded this using callback from https://github.com/bokeh/bokeh/pull/5976#issuecomment-302219874:
```python
		self._resize_callback = bokeh.models.callbacks.CustomJS(
			code = '''
			var event = document.createEvent('HTMLEvents');
		        event.initEvent('resize');
		        window.dispatchEvent(event);
			'''
		)
		self._figure.js_on_change('width', self._resize_callback)
		self._figure.js_on_change('height', self._resize_callback)
```

**Comment by bryevdv** [comment]
The following code works with 1.1.0dev9:
```
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import Button
from bokeh.plotting import figure

plot = figure()
plot.circle([1,2,3], [4,5,6])

def update_width():
    plot.width=1200

button = Button()
button.on_click(update_width)

curdoc().add_root(column(plot, button))
```
Absent an actual complete minimal example script in this issue to begin with, I am closing and marking it completed.
