### ISSUE TITLE
Multiple GMap plots whiting out and multiple calls of gmap plot whiteing out in notebook. 

### ISSUE THREAD

**Issue by cenveoanalyst** [bokeh/bokeh#4835]
Hello, 

I am trying to build interactive bokeh plots using overlayed Google Maps. I am hoping to have similar functionality to regular bokeh plots, being able to call them multiple times in a notebook without issue. However, for Google Maps this doesn't yet seem to be the case. Exactly the first time I call exactly the first map in the following gist the map loads and works. All other maps display first my overlaid points, then pure whiteness. 

This is in Bokeh 0.12.0

https://gist.github.com/cenveoanalyst/8931355cd8ee7466808e0cc452666246

The issue tracker isn't the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).

For defects or deficiencies, please provide:
- Description of expected behavior and the observed behavior
- Self-contained example code that generates the issue (if possible)
- Stack traceback and/or browser developer tools console output
- Software version information output by `bokeh info` command

For desired features, please provide:
- Description of the desired feature

**Comment by cenveoanalyst** [comment]
In updating to 0.12.1 the same code produces the same result, but I am able to zoom in and out to have the regular map show. The overwritten dots are still not showing on the second plot. Testing with a smaller dot set produces the same result.

The JavaScript console shows:

```Bokeh: BokehJS plotting callback run at Tue Sep 06 2016 11:00:41 GMT-0500 (Central Daylight Time)
VM741:16 Bokeh: all callbacks have finished
utils.js:785 Could not open comm  --  Error: Class 67c6f9d5-5c99-4d1f-81da-c81242aae557 not found in registry (…)reject @ utils.js:785Promise.reject (async)CommManager.comm_open @ comm.js:85i @ jquery.min.js:4Kernel._handle_iopub_message @ kernel.js:1087Kernel._finish_ws_message @ kernel.js:924(anonymous function) @ kernel.js:915Promise.resolve (async)Kernel._handle_ws_message @ kernel.js:913i @ jquery.min.js:4
kernel.js:916 Couldn't process kernel message WrappedError {stack: "Error: Could not open comm↵  at new Error (native)….js?v=dda91b55a04855a1c133b176c7a48905:12878:33)↵", message: "Could not open comm", error_stack: Array[2]}error_stack: Array[2]message: "Could not open comm"stack: "Error: Could not open comm↵  at new Error (native)↵  at Error.WrappedError (http://192.168.54.103:8000/user/cenveo/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:12799:25)↵  at reject (http://192.168.54.103:8000/user/cenveo/static/notebook/js/main.min.js?v=dda91b55a04855a1c133b176c7a48905:12878:33)↵"__proto__: Error(anonymous function) @ kernel.js:916Promise.reject (async)CommManager.comm_open @ comm.js:85i @ jquery.min.js:4Kernel._handle_iopub_message @ kernel.js:1087Kernel._finish_ws_message @ kernel.js:924(anonymous function) @ kernel.js:915Promise.resolve (async)Kernel._handle_ws_message @ kernel.js:913i @ jquery.min.js:4
VM740:123 Bokeh: JS/Python version mismatch
VM740:123 Bokeh: Library versions: JS (0.12.0)  /  Python (0.12.1)
VM753:81 Bokeh: BokehJS plotting callback run at Tue Sep 06 2016 11:00:49 GMT-0500 (Central Daylight Time)
VM740:123 Bokeh: JS/Python version mismatch
VM740:123 Bokeh: Library versions: JS (0.12.0)  /  Python (0.12.1)
VM753:16 Bokeh: all callbacks have finished
VM740:123 Bokeh: Registering Jupyter comms for target f1161147-1da9-4fb9-9b30-b590fcaa89fb```

This while running Bokeh from CDN in 0.12.1.

**Comment by cenveoanalyst** [comment]
@bryevdv Here are the screenshots you requested of the behavior. 

![firstmap](https://cloud.githubusercontent.com/assets/17322855/18283461/f32d9c98-742a-11e6-9d34-f8b28c66424d.JPG)
![secondmapinitial](https://cloud.githubusercontent.com/assets/17322855/18283462/f331f9e6-742a-11e6-891f-0096f86779a9.JPG)
![secondmappost](https://cloud.githubusercontent.com/assets/17322855/18283460/f32ce118-742a-11e6-8ed8-390c9381f1d5.JPG)

**Comment by bryevdv** [comment]
@cenveoanalyst awesome thanks, can you recap what actions happened in between each for later reference?

**Comment by cenveoanalyst** [comment]
1. Loaded notebook and ran (my jupyterhub is rigged to do that automatically), first two images displayed. 
2. Zoomed in (on Chrome), second image displayed, no Bokeh glyphs.
