### ISSUE TITLE
Histogram should not use categorical bar for implementation.

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4837]
A combination of round-off and/or string conversions of floats to categories is causing histogram bars to often overlap. The motivation to re-use the bar code is understandable, but histograms are fundamentally continuous, not categorical, resulting in the shortcomings of the current implementation.

**Comment by bryevdv** [comment]
@jsignell Are there any artifacts from the sprint investigation that would be useful to include in this issue? Did you want to work on a PR for this? I understand if you do not have time I just wanted to make sure to offer the opportunity before diving into it.

**Comment by jsignell** [comment]
@bryevdv Thanks for checking in, but I definitely won't be submitting a PR for this. Our initial findings and ideas are comments off issue #3315

**Comment by bryevdv** [comment]
Ack I searched for an exiting issue but missed it. I will close this in favor of #3315 Thanks for helping to dig into the issue
