### ISSUE TITLE
Default mode to disallow updating individual columns

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4838]
I see this over and over in server apps questions:

```
source.data['foo'] = [...]
soruce.data['bar'] = [...]
```

The issue is that everyone of of those `.data['foo'] = whatever` lines triggers a _separate update_ and redraw. Apart from being inefficient, it often results in undesired visual tearing because the data is momentarily unsynchronized. The _bigger_ issue is that if the new columns are a different length than the old, then this also momentarily violates the fundamental assumption that columns _always_ all have the _same length_ which can result in real problems.

I have tried to socialize this in many places but it does not seem to be generating anything like "accepted wisdom". 

I'd like to propose disallowing this kind of update (somehow) by default, perhaps with a configuration setting that would allow people to do it if they really, really wanted to. Some kind of "batching" mechanism might also complement that option, but I would say... later, for that. 

ping @bokeh/dev @havocp

**Comment by bgyarfas** [comment]
I will say it feels very unnatural to have a `dict` like object (in this case the `.data`)  and not be able to change a single entry. I've haven't googled around but is there an immutable dict type that might be a more appropriate parent class for `ColumnDataSource`?

**Comment by bryevdv** [comment]
But it's not immutable. In fact the `.stream` and new `.patch` methods on CDS are specifically for appending or updating in place, extremely efficiently. Though maybe that's the point, they do it via a defined interface.

Part of this is historical, `.data` dates to back before the Bokeh server, and in the absence of the server, this is a non-issue. But that's the situation we are in now. I suppose another alternative then is to get rid of `.data` completely, and switch to prescribed interfaces like `.patch` for every kind of access. That would break code *everywhere* though, so I think we are passed the opportunity to make that kind of change. 

I agree it's not typical, but sometimes other important use-cases impose their own specific requirements. In this case, if the trade-off is between "weird dict" and "highly usable and efficient bokeh server" then we may have to settle for the "weird dict".

**Comment by timsnyder** [comment]
Maybe we need to make `.data` it's own dict-like class that gives us an easily configurable way to keep users from running off this cliff?  I would need to look more closely at CDS and the implementation of Python dict but it seems like the short-term solution would be an error from an overloaded `__setitem__` the error would happen only in server code.  One slight step better would be to do something that error'ed when bokeh server was starting with code that tries to do `.data.__setitem__()`.

I'd also be interested in looking at the guts of the server code to see how hard it would be to implement writes to CDS.data a delayed or "batched" way.  I've done this type of thing before in other frameworks and it would be a good way to learn the server code.  

For both the short-term and long-term plans, it seems like we need our own dict specialization for CDS that encapsulates the Bokeh server best-practices and gives us a layer to optimize for performance and the limitations of the update mechanisms while giving users easy dict semantics.

**Comment by bsipocz** [comment]
Ohh, please don't disallow it without having an option to keep the current behaviour, as it would brake my current workaround for errorbar plots (that I do to go around the problem mentioned on gitter here https://gitter.im/bokeh/bokeh?at=578d335aac85f2507ac01a6b). 

In my case the length of the new columns are always the same as the rest, as they are generated from the data already in the ColumnDataSource object. But maybe there could be a validation for it that raises a warning or even an error is the lengths are not matching?

**Comment by bryevdv** [comment]
This question seems to come up far less now. Perhaps the necessity of always having the same columns lengths has passed to "accepted wisdom" after all. Closing for now.
