### ISSUE TITLE
Error when using HoverTool and TapTool with TapTool in "inspect" behavior.

### ISSUE THREAD

**Issue by EngelOfChipolata** [bokeh/bokeh#4839]
TapTool callback is not triggered when using HoverTool and TapTool on a same plot with TapTool attribute  `behavior="inspect"`.

This can be reproduced with this code : https://github.com/EngelOfChipolata/bokeh_hover_tap_tools

When a glyph is clicked, the tooltip just disappears but the callback set in TapTool is not triggered. Furthermore, an error message is displayed in browser console : 

> TypeError: m is undefined
Bokeh</<["models/tools/inspectors/hover_tool"]</s</e.prototype._update()
 bokeh-0.12.0.min.js:17
Bokeh</<.backbone</</</y()
 bokeh-0.12.0.min.js:23
Bokeh</<.backbone</</</g()
 bokeh-0.12.0.min.js:23
Bokeh</<.backbone</</</p()
 bokeh-0.12.0.min.js:23
Bokeh</<.backbone</</</c.trigger()
 bokeh-0.12.0.min.js:23
Bokeh</<["common/selection_manager"]</o</e.prototype.inspect()
 bokeh-0.12.0.min.js:3
bound ()
 self-hosted:760
Bokeh</<["models/tools/gestures/tap_tool"]</i</e.prototype._select()
 bokeh-0.12.0.min.js:17
Bokeh</<["models/tools/gestures/tap_tool"]</i</e.prototype._tap()
 bokeh-0.12.0.min.js:17
Bokeh</<.backbone</</</y()
 bokeh-0.12.0.min.js:23
Bokeh</<.backbone</</</g()
 bokeh-0.12.0.min.js:23
Bokeh</<.backbone</</</p()
 bokeh-0.12.0.min.js:23
Bokeh</<.backbone</</</c.trigger()
 bokeh-0.12.0.min.js:23
Bokeh</<["common/ui_events"]</s</e.prototype._trigger_event()
 bokeh-0.12.0.min.js:3
Bokeh</<["common/ui_events"]</s</e.prototype._trigger()
 bokeh-0.12.0.min.js:3
Bokeh</<["common/ui_events"]</s</e.prototype._tap()
 bokeh-0.12.0.min.js:3
Bokeh</<["common/ui_events"]</s</e.prototype._hammer_element/</<()
 bokeh-0.12.0.min.js:3
Bokeh</<["hammerjs/hammer"]</</ct.prototype.emit()
 bokeh-0.12.0.min.js:35
Bokeh</<["hammerjs/hammer"]</</<.emit()
 bokeh-0.12.0.min.js:35
Bokeh</<["hammerjs/hammer"]</</K.prototype.tryEmit()
 bokeh-0.12.0.min.js:35
Bokeh</<["hammerjs/hammer"]</</<.process/this._timer<()
 bokeh-0.12.0.min.js:35
h/<()

Bokeh version : 0.12.0
Browser : Firefox 47.0
OS : Ubuntu 16.04

**Comment by bryevdv** [comment]
OK I have a PR incoming. Please note that at least in the code sample provided, the aspect ratio is not 1-1, so the hit-testing on circles is suboptimal. Recommend ensuring that that aspect ratio remains 1-1 or or using `size` which is measured in screen units, and does not suffer from this issue.
