### ISSUE TITLE
Support Altair / Vega(lite)

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4844]
https://github.com/ellisonbg/altair

> Altair provides a Python API for building statistical visualizations in a declarative
> manner. By statistical visualization we mean:
> - The **data source** is a `DataFrame` that consists of columns of different data types (quantitative, ordinal, nominal and date/time).
> - The `DataFrame` is in a [tidy format](http://vita.had.co.nz/papers/tidy-data.pdf)
>   where the rows correspond to samples and the columns correspond the observed variables.
> - The data is mapped to the **visual properties** (position, color, size, shape,
>   faceting, etc.) using the group-by operation of Pandas and SQL.
> 
> The Altair API contains no actual visualization rendering code but instead
> emits JSON data structures following the
> [Vega-Lite](https://github.com/vega/vega-lite) specification. For convenience,
> Altair can optionally use [ipyvega](https://github.com/vega/ipyvega) to
> display client-side renderings seamlessly in the Jupyter notebook.

We would like to be able to generate a bokeh plot from Altair. This is not a replacement for `bokeh.charts`. More details to follow. This may live in a seperate package.

**Comment by mrocklin** [comment]
I would also enjoy seeing this happen.

**Comment by bryevdv** [comment]
Per conversation with @pzwang, another approach is to make `bokeh-vega.js` component that can renderer vega specs directly *by BokehJS*,  instead of a Python facility to turn vega specs into Python Bokeh models.

**Comment by joelostblom** [comment]
Would this planned feature support the use of Altair plots in Bokeh dashboards? Or should this be tracked in a separate issue?

**Comment by bryevdv** [comment]
Closing. Given that [pyviz/panel](https://github.com/pyviz/panel) can combine Bokeh, altair, MPL, etc plots into one interactive dashboard, I think the need for this (and the justification to expend time/energy to add complexity to Bokeh core) is greatly diminished.
