### ISSUE TITLE
For bokeh.models.glyphs.Image, images are colormapped individually and not as a set

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4847]
Referring to this chunk of code: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/image.coffee#L23-L35

Currently, the only glyph that uses a ColorMapper is the `Image` glyph. In the implementation of `Image`, each image 2d array is individually color mapped instead of the set of images (as `Image` is vectorized).

This seems incorrect, as a visualization that consists of a bunch of tiled images would non-intuitively be colormapped by the min/min of each individual tile.

**Comment by bryevdv** [comment]
Closing in favor of #12355
