### ISSUE TITLE
create abstract base class for Legend and ColorBar (and future similar classes)

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4848]
ggplot describes legends and colorbars as guides (http://docs.ggplot2.org/current/guides.html).

Bokeh should refactor the `Legend` model to be a subclass of GuideRenderer (currently it's a subclass of `Annotation`). This will simplify the addition of a `ColorBar` model, as ColorBar and Legend can share some code (off-axis placement, etc) and make the docs easier to navigate.

Eventually (with the addition of a ColorBar), we would add an abstract `Legend` class.

**Comment by canavandl** [comment]
ColorBar was implemented without needing to do this in #4931

**Comment by birdsarah** [comment]
Was it still a good idea though? I'm not sure Legend's should be classed as annotations.

**Comment by canavandl** [comment]
There's definitely some overlap between Legends and ColorBars and future stuff-in-a-box-that-may-or-may-not-be-on-frame, like orientation, location and some padding stuff. I'll reopen and rename as something better.

**Comment by canavandl** [comment]
Currently Legend and ColorBar have some duplicated for `location` (the "top_left" or "bottom_right" LegendLocation enum) and padding and margin. However there's some Annotation base class code for panel offsets that's needed. This could probably all be unified better.

**Comment by bryevdv** [comment]
Agreed, I think `Legend` should become a `Guide`

**Comment by bryevdv** [comment]
this never happened, I am not so sure about bothering now anymore.
