### ISSUE TITLE
Code of Conduct needed

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#4854]
This is in preparation for seeking fiscal sponsorship from NumFocus (and because it's good idea to have, in general).

**Comment by Maggie-M** [comment]
Added a CoC to BEP 7, which can be found [here](https://github.com/bokeh/bokeh/wiki/BEP-7:-Code-of-Conduct)

**Comment by birdsarah** [comment]
Two Codes of Conduct that I like:
* https://github.com/sandstorm-io/sandstorm/wiki/Code-of-Conduct
* https://us.pycon.org/2016/about/code-of-conduct/

In particular from the Sandstorm CoC:
* a humanizing paragraph about why a CoC is useful.
* "Likewise any spamming, trolling, flaming, baiting or other attention-stealing behavior is not welcome."
* "Whether you're a regular contributor or a newcomer, we care about making this community a safe place for you and we've got your back." 
* "Please be kind and courteous. There's no need to be mean or rude."
* "Respect that people have differences of opinion and that every design or implementation choice carries a trade-off and numerous costs. There is seldom a right answer."

There's something about the Sandstom CoC that is personal and real, that I really like - it feels like something that they are very committed to.

From the PyCon CoC:
* "We value the participation of each member of the Python community and want all attendees to have an enjoyable and fulfilling experience. "
* "Be kind to others. Do not insult or put down other attendees."
* "Harassment includes offensive communication related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention."
* "Be careful in the words that you choose. Remember that sexist, racist, and other exclusionary jokes can be offensive to those around you. Excessive swearing and offensive jokes are not appropriate for PyCon."

I don't think these quite have it, but I think one of the important messages to get through is that typically when you're in a position of privilege it's very hard to see when you're disenfranchising others. 

I'd like Bokeh's Code of Conduct not just to be a place that describes bad behavior and how we will deal with it, but also a positive thing that describes the positive things we should all do to make it a positive environment. This is there already but maybe it can come through more.

I'll try and make some proposed edits at a later stage.

**Comment by chalmerlowe** [comment]
@bryevdv 
In looking at the governance documents in preparation for NumFOCUS fiscal sponsorship, I noticed that bokeh appears to have two BEP 7s
* one related to the code of conduct: [BEP 7 code of conduct](https://github.com/bokeh/bokeh/wiki/BEP-7:-Code-of-Conduct)
* one related to the PR process: [BEP 7 PR Branch Process](https://github.com/bokeh/bokeh/wiki/BEP-7:-PR-Branch-Process)

**Comment by bryevdv** [comment]
@chalmerlowe thanks I have deleted the branch process document

**Comment by bryevdv** [comment]
I also renamed BEP 7 to https://github.com/bokeh/bokeh/wiki/BEP-7:-Community-Code

**Comment by bryevdv** [comment]
Also, this should probably be BEP3 There were a number of documents called BEPs that were not really in the spirit of BEPs (they were working documents, not full proposals of anything). Consensus was to "reboot" the BEP sequence starting after the current BEP2. Also FYI  it was also generally agreed to migrate these documents elsewhere that supports better collaboration. Shared gdocs perhaps.

**Comment by damianavila** [comment]
We had some large discussion in Jupyter about the CoC, I think the document itself + discussion could be useful here are well: https://github.com/jupyter/governance/pull/23

**Comment by bryevdv** [comment]
@bokeh/dev 

Under the premise that a reasonable CoC (which I would consider one derived from the Contributor-Covenant to be), that can be incrementally improved in the future, is better than none, I propose to adopt this CoC coincident with the `0.12.5` release. 

@birdsarah I have tried to incorporate your suggestions, but further input is welcome.  I am also going to post an appeal to the ML for any final comments on this.

**Comment by bryevdv** [comment]
FYI I have moved bad "non-BEPs" and properly assigned the CoC to BEP-3

https://github.com/bokeh/bokeh/wiki/BEP-3:-Community-Code

**Comment by damianavila** [comment]
> Under the premise that a reasonable CoC (which I would consider one derived from the Contributor-Covenant to be), that can be incrementally improved in the future, is better than none, I propose to adopt this CoC coincident with the 0.12.5 release.

+1 on the proposal

**Comment by davclark** [comment]
I am currently mostly a user of Bokeh, but have participated in a variety of communities and have also been getting perspective on conduct here in my work in Baltimore schools. In particular, I have read @matthew-brett's extensive list of concerns on the Jupyter CoC (rec'd by @damianavila above) and they point to a thing called [restorative practice](https://en.wikipedia.org/wiki/Restorative_practices#Difference_between_restorative_justice_and_restorative_practices), which would be inclusive of restorative justice. 

The basic idea is that the community is oriented first towards understanding why the bad thing happened, and making things better. The goal is *not* to label the (putative) "offender" to be a "bad person," but rather to encourage them to contribute to the community's well-being. If someone causes harm, they are encouraged first to make things right with the person(s) harmed. The application of restorative practice / justice does not preclude potentially banning an individual from a community, but it makes it clear that such action is not the first tool at hand. It can actually facilitate healthier relationships with both individuals committing harm as well as those harmed.

To pick the specific example discussed in the Jupyter thread about "SpacedGirl" I think this post (from her) on why she was using "inflammatory" langauge is relevant:

https://github.com/swcarpentry/board/issues/111#issuecomment-217748744

It should not be surprising that Spaced Girl also expressed how she was harmed (more specifically, silenced).

That one event was incredibly burdensome for the community. We cannot know for sure, but a timely response by someone "on script" (as proposed earlier in that issue by @codersquid) expressing sincere concern for both sides' views and a clear request (or demand) to resolve the conflict off-list would be good for everyone. If appropriate, a follow-up can be made to the list after things have resolved.

In terms of character count, this could be a small change, and I'd be happy to contribute one if this seems on-point. Recognizing that I've already written something lengthy here, I won't inject more discussion unless there's genuine interest from at least a second person.

Thanks for reading!

**Comment by bryevdv** [comment]
@davclark In general I am immediately dubious of any system that places a burden on to the person who was harmed. If someone is subject by harassment, say, it is well and truly and *fundamentally not their responsibility* to do the fixing. Without details, this proposal sounds like that to me. 

However, the devil is in the details. So I will make the same statement I made (to no avail) to matthew in the other thread: It's far easier and better (possible at all, really) to evaluate concrete proposals than it is to evaluate sweeping proclamations. If as you say, proposed changes are small, I can say I'd be much more interested in considering and evaluating them on their own merits, as a opposed to having a long and unproductive meta-discussion *about* them or what they might be.

**Comment by matthew-brett** [comment]
The devil is not only in the details.

**Comment by bryevdv** [comment]
> The devil is not only in the details. 

This is an unhelpful comment. If you are not here to participate, please refrain from derailing.

**Comment by matthew-brett** [comment]
You're welcome to throw me off the thread - but the comment was not meant to be unhelpful, only to point out that a document is not only the details, but the main thrust and aim of the document.   When someone like Dav wants to move the document in a slightly different direction, not just on detail, but on substance, I think it's usual and healthy to throw that up for discussion first.

**Comment by davclark** [comment]
I tend to agree with your sentiment @bryevdv. A formal proposal via GitHub would seem to require making a pull request to the wiki repo (and I'm not even sure that's possible). So, let me start by including two chunks of potential text here:

From [Ubuntu's CoC](https://www.ubuntu.com/about/about-ubuntu/conduct):

> ### Take responsibility for our words and our actions

> We can all make mistakes; when we do, we take responsibility for them. If someone has been harmed or offended, we listen carefully and respectfully, and work to right the wrong.

Compare to the wording in [the BEP](https://github.com/bokeh/bokeh/wiki/BEP-3:-Community-Code):

> ### Our Pledge

> In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of [list elided].

These are very different models of "policing." To the credit of the BEP version, it does seem to be generally constructive to name specific practices that are harmful and unwelcome (like harassment).

Restorative justice is not widely discussed, and I was trying to be brief, but I see @bryevdv responding thus:

> I am immediately dubious of any system that places a burden on to the person who was harmed.

This means that this inference is there to be made, but I did not say that. To clarify, I probably should have linked as opposed to simply mentioning the [recommendation](https://github.com/swcarpentry/board/issues/111#issuecomment-217483972) from @codersquid.

Honestly, I expect this will almost never come up. When it does, probably it will often be a case of naming the offensive But in the rare case where there is an escalation of two people, both thinking they are in the right, it could be long, drawn-out thing, or it could be effectively nipped in the bud (by a moderator or facilitator) with the initial goal of conflict resolution as opposed to the goal of "keeping out bad people." In the latter case, "bad people" then have a grudge against the organization, which is bad for everyone. If you have two people who both think they are right, probably there is some learning that can happen.

Here's a proposed modification:

> ### Our Pledge

> We can all make mistakes; when we do, we take responsibility for them. If someone has been harmed or offended, we listen carefully and respectfully, and work to right the wrong. In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to combat harassment towards any participant in our project and our community, regardless of age, body size, [list elided].

And then some additional language here (see last sentence):

> ### Our Responsibilities

> Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior. Recognizing that some categories of inappropriate behavior may require interpretation (for example, "personal attacks"), maintainers will seek balanced input from affected parties prior to making a final determination, and encourage said parties to right any harms committed to the extent possible.

And / or a similar modification could be made to *Enforcement*.

Is the gist of what I'm proposing clear? It's not about protecting someone who is making derogatory or bigoted remarks. You don't really even need a code of conduct for that - just plain decency (which I think most open source communities strive for). The CoC will be most relevant in those cases that are unclear. The CoC itself is a way to either project a welcoming/nurturing or authoritarian face to new members. Ideally, new members feel good after reading it! "What a nice bunch of people!" they should think.

**Comment by bryevdv** [comment]
@matthew-brett  I will only repeat what I have repeated now, several times:

Saying something "needs to change" and then not actually ever supplying the proposed changes is not productive. There is nothing, literally nothing, that would help focus discussion better than an actual diff of the actual doc with actual words for it to contain.

**Comment by davclark** [comment]
Also - I am happy to provide a diff if that's more useful. I was trying for lowest cognitive load.

**Comment by davclark** [comment]
Another thought, and then honest I'm going to be quiet - I realize that I'm putting words in the Maintainer's mouths. I'm happy to help bear the load here as a moderator / facilitator if you feel my suggestion would be burdensome (and I recognize I can't completely unburden the maintainers in this respect).

**Comment by bryevdv** [comment]
@davclark I only wanted a concrete proposal to evaluate, and "diff" to my mind succinctly conveyed that aspect, which I consider important.  The above is also fine (it is concrete!) I am in the middle of about six things trying to get this release ready. I will commit to commenting in detail by tomorrow AM. (we have several days before the release, so this part need not be a hurry)

**Comment by davclark** [comment]
Cool - thanks for setting expectations. I'm a pragmatist. If you have other pressures+limitations for getting a code of conduct v1 out the door, I'm happy to engage on a v1.1 (or however semantic versioning dictates).

**Comment by bryevdv** [comment]
I would propose what I consider to be minor edits for brevity, parallelism and to be more direct in a few cases:

> We pledge to take responsibility for our own actions. If someone has been harmed or offended, we will listen carefully and respectfully, and work to right the wrong. In the interest of fostering an open and welcoming environment for all, we pledge to combat harassment towards any participant in our project and our community, regardless of age, body size, [list elided].

Specifically: not all wrongs are accidental, and the wording "We can all make mistakes" fails to account for all possible situations. I'd prefer not to make pre-rationalizations for events that haven't yet happened. The important point that (I think) we agree on is that everyone takes responsibility for their own actions. Great. 

Next para:

> Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior. Maintainers will seek input from all parties following any reports in order to make final determinations, and will encourage relevant individuals to right any harms committed to the extent possible.

This to me seems more clear especially re the actual expected process for everyone involved. 

>  Ideally, new members feel good after reading it! "What a nice bunch of people!" they should think. 

Respectfully, I feel that this is neither an important nor a proper goal. Modern technology allows one or a few people to nearly effortlessly marshal gang attacks that casually spew abuse and bile at individuals in torrents. I've been witness to this with people I care about. I can confidently say that the bar is lower than "What a nice bunch of people!" It's not a requirement to come into a place and like everyone, merely that everyone is respectful. So, the important bar is really **"I won't feel dangerously unsafe here"** *That* should be the goal, in my experience. It's an assurance that is distressingly hard to provide online in many cases these days, and if meeting that bar means sounding a bit stern as the leaders of a project, I personally say so be it.

**Comment by davclark** [comment]
You were already coming through as very respectful - even without calling it out explicitly, thank you. I take your point about online harassment, and it seems appropriate to prioritize. Honestly, such behavior baffles my mind and I agree it is clearly malicious. Moreover, you didn't turn it into an either-or situation - you clearly preserved the intent of my suggestions.

+1 on your edits.

**Comment by bryevdv** [comment]
Great, I've made the edits. I will plan to mark this as "Implemented" tomorrow, ahead of the release. I may have to put a my email in as placeholder temporarily if the proper alias can't be set up in time.

**Comment by pzwang** [comment]
Thanks for the thoughtful discussion here, and I like where this has converged.

In my experiences, there are two things that are true: (1) all major problems are actually people problems; (2) some people will be a-holes, and we should not allow tech to amplify their impact.

We are fortunate not to have attracted the latter, but I am imminently aware that it may happen.  When it does happen, the maintainers and the community as a whole should have the awareness that there is a gray zone where someone just doesn't know they have transgressed the mores of the community, and need a private chat to be brought up to speed.  But everyone should always be aware the mechanisms of technology can be used to absolutely enforce and ban those are actively subverting the mores of the community.

**Comment by bryevdv** [comment]
FYI just to add precision, I have marked the BEP `implemented`, as well as moved it in the TOC out of the "proposed" section.

**Comment by bryevdv** [comment]
(please note that all BEP's may be moved to a better platform than GH Wiki in the future)

**Comment by bryevdv** [comment]
Recording small changes added on 2020-05-03:

* Link to Conduct Subcommittee on the Project Roles document, so that potential submitters may know ahead of time who will receive any reports
* Add stanza for escalation to NF CoC in a case a report is about NF committee itself (covers every contingency)

I don't expect that that could be much to say about these clarifications, but please comment here if there is anything in need of further discussion or review. 

---

As  an aside, the`conduct@bokeh.org` email is monitored directly by the committee and also now directs any email reports to a private channel on the contributor Slack that only the committee can access. FYI as of this date there have been no reports come in since the CoC was implemented.
