### ISSUE TITLE
Wheel Zoom tool on Microsoft Edge

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4863]
On Bokeh 0.12.0 on Microsoft Surface with Edge, Wheel Zoom tool is not responding to pinch or zooming.

**Comment by birdsarah** [comment]
#4864 partially fixes this and means now that pinch zoom is working at least.

**Comment by mattpap** [comment]
I will assume this refers to the legacy version of Edge browser (EdgeHTML engine). If that's the case, then this issue won't be relevant anymore in bokeh 3.0. If the issue persist on newer versions of Edge, please reopen.
