### ISSUE TITLE
Resize tool doesn't work in a layout

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4865]
The resize tool is working again for a single plot (see #4857), but when the plot is in a layout, the other plots in the layout do not change correctly in response.

This, I believe, is because the parent of the plot (and any of its parents) need to be recomputed given this change.

For example, a row listens for "change:children", but the change is not to the children but to a property on one of the children.

I feel like this is a problem we have encountered elsewhere, but can't recall how it was solved. ping @mattpap @bryevdv 

Below is a gif of the behavior in a fixed layout. You can see that the plots on the row correctly position when the plot shrinks, but when it grows, they wrap onto the next line. This is because the width of the parent row is not being recomputed and is fixed at the initial width.

![resize-layout-fixed](https://cloud.githubusercontent.com/assets/1796208/17072200/3096feee-502c-11e6-91f9-9310c7840415.gif)

Below is a gif of the behavior in a scale_width layout. The resizing plot will not grow in width inspite of trying - I believe this is for a similar reason, but there may be additional subtleties.

![resize-layout-scale_width](https://cloud.githubusercontent.com/assets/1796208/17072133/a54b520e-502b-11e6-95e8-7ca67931f8dd.gif)

In stretch_both mode, the plot appears to not resize at all, but that's not surprising, because the stretch_both mode is designed to occupy all the available space and then divide it equally amongst the plots.

**Comment by mattpap** [comment]
Resize tool was removed.
