### ISSUE TITLE
Don't make space for element if not visible

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4867]
While working on dask webui with @mrocklin, we wanted to squish two plots together by removing the xaxis. Setting `p.xaxis.visible = False` visually removed the xaxis but there was still a space for it (This is because the layout and the axis rendering happen separately).

I think the expected behavior is that if something is not there things squash up appropriately.

Would this also extend to DataRanges changing if a glyph became not visible?

**Comment by birdsarah** [comment]
@pzwang's two cents on this issue was (paraphrasing): things should squish up by default, but only if there's an option to have things not squish when you don't want them to.

**Comment by mattpap** [comment]
Fixed in PR #8754.
