### ISSUE TITLE
User guide "responsive dimensions" needs updating

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4869]
http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#responsive-dimensions

Needs to be updated with new info about sizing_mode.

**Comment by jantman** [comment]
I couldn't get responsive graphs right until I found this issue, and then looked into sizing_mode.

**Comment by birdsarah** [comment]
Core team resources are stretched thin at the moment, and would certainly appreciate help on updating the docs @jantman

**Comment by jantman** [comment]
Apologies for a "please do this" post. I'm not entirely sure on how these really work, but I've opened #4994 to add a link to the sizing_mode docs.

**Comment by bryevdv** [comment]
No apologies necessary, and thanks for the PR!
