### ISSUE TITLE
Implement something like pcolormesh

### ISSUE THREAD

**Issue by dawehner** [bokeh/bokeh#487]
It would be really cool to have something like pcolormesh provided by matplotlib

http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.pcolormesh

**Comment by surajmehta** [comment]
Hello,
Just wanted to ask if anyone got this issue solved. I am trying to create something like the above example and would like to know how to do it in bokeh.
"
r = np.arange(0, 2*a ,0.01)
theta= np.linspace(0, 2 * np.pi ,100)

R, Theta = np.meshgrid(r, theta)
A,B = R*np.cos(Theta),R*np.sin(Theta)

def I(l,r,Theta):
    Z=np.zeros(R.shape,np.float64)
    Z[np.where(R<=a)] = jv(l, (x[m] * R[np.where(R<=a)]/ a)) * np.cos(l*Theta[np.where(R<=a)])
    Z[np.where(R>a)] = jv(l,x[m]) / kv(l, t[m]) * kv(l,(t[m] * R[np.where(R>a)]/ a)) * np.cos(l*Theta[np.where(R>a)])
    return Z

plt.pcolormesh(A, B, I(l,r,Theta))
plt.show()
"
this is the result:

![step index](https://cloud.githubusercontent.com/assets/5133687/14936256/1c45283e-0f2d-11e6-8406-f603545698a9.png)

￼Cheers

**Comment by birdsarah** [comment]
@surajmehta, try the mailing list for a question like this: https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
