### ISSUE TITLE
Autocomplete should start with a single character

### ISSUE THREAD

**Issue by npyoung** [bokeh/bokeh#4870]
The `AutocompleteInput` widget looks and works great in a Jupyter notebook (with `output_notebook`), but has styling and functional bugs when used with bokeh's server. For example:

```
from bokeh import plotting as bk
from bokeh.models import AutocompleteInput

ac = AutocompleteInput(title="Some countries", value='Albania', \
completions=['Albania','Austria','Australia','Angola','Argentina'])
bk.curdoc().add_root(ac)
```

Yields this when run with `bokeh serve`

![screen shot 2016-07-23 at 6 44 20 pm](https://cloud.githubusercontent.com/assets/1348767/17081238/7f3082bc-5105-11e6-8366-cda7eac14f3a.png)

Notice how the matched completions show up as an unordered list instead of a dropdown. Any bokeh widgets or figures below the autocomplete text box will cover up this list of completions. Also, when you enter characters, the text "[N] results are available..." appears, which does not happen in Jupyter notebooks.

Finally, `on_change('value', myfunc)` does not seem to get triggered when you try to use autocompletion options. If you type what you want directly without using the arrow keys and then press enter, `on_change` triggers successfully.

I noticed that when using `output_notebook`, bokeh gets its styling and javascript from a CDN. I tried replacing bokeh's static JS and CSS with the files from the CDN, which had no effect.

```
$ bokeh info
Python version      :  2.7.12 (default, Jul 22 2016, 17:42:15) 
IPython version     :  5.0.0
Bokeh version       :  0.12.0
BokehJS static path :  /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bokeh/server/static
```

**Comment by hsparra** [comment]
+1 on fixing the on_change()  working when using autocompletion.

**Comment by philippjfr** [comment]
``on_change`` seems to work for me but the styling is still broken in a server app. Presumably some JS/CSS isn't being loaded?

**Comment by rmelotte** [comment]
The styling issue seems to be gone in bokeh server as of 1.1.0dev11 (it seems it's not possible to trigger completions with one letter anymore so I used 2):
![image](https://user-images.githubusercontent.com/20061471/55066813-d881d700-507e-11e9-92d6-4b879eba1305.png)

Arrow keys still do not work, but I think it's expected in the recent versions ?

The on_change value however still has problems as described in #2259 .

**Comment by bryevdv** [comment]
I believe this is why >= 2 characters are needed to start:

https://github.com/bokeh/bokeh/blob/e2f5a9643c48a6c7a6acfa0530da58e3cd85eed6/bokehjs/src/lib/models/widgets/autocomplete_input.ts#L78-L81

All the other issues are resolved so re-purposing this issue for just this task. Also noting there some console logs in this file that should be removed.

**Comment by bryevdv** [comment]
@rmelotte #9116 adds a `min_characters` that can be configured to 1, but retains the default value of 2.

**Comment by bryevdv** [comment]
@rmelotte I would consider changing the default to 1 for Bokeh 2.0 in September. If you feel strongly please open a new issue to discuss.
