### ISSUE TITLE
Missing documentation on trigger function

### ISSUE THREAD

**Issue by OliverOliverOliverAnders** [bokeh/bokeh#4871]
Hi,

could you please add (more) documentation to the trigger function on sources. 

Kind Regards,
Oliver

**Comment by bryevdv** [comment]
Everything that is demonstrated in the various examples is basically it: `.trigger('change')` will trigger a `"change"` event from a a data source so that things get re-drawn, etc. There's no other usage I would expect users to to ever use.

**Comment by OliverOliverOliverAnders** [comment]
Hi,

thanks for the response. There is a one example 'Running a Bokeh Server' chapter in the current documentation using 'data':
    
ds.trigger('data',ds.data, ds.data)

Does it replace the data object?

Kind Regards,
Oliver

**Comment by tobyhodges** [comment]
Hi Oliver,

I've been playing around with this the last few days. My understanding is that, when you run `.trigger()` on a data source (as in your example above), you specify as arguments, the attribute of the data source that will be updated (`data` in the example), the old version, and the new version (both `ds.data` in this case). So, after running the line of code that you included above, `ds.data` would be updated with whatever new values have been specified.

I'm almost ready to push my changes to the toy script I've been working on. I'll be happy to post a link to it here afterwards, if you think that a few examples would be helpful?

All the best,

T

**Comment by tobyhodges** [comment]
You can see several examples of using `.trigger()` in [this script](https://github.com/tobyhodges/bokehTimer/blob/master/timer.py)., which renders a countdown timer in the web browser.

**Comment by OliverOliverOliverAnders** [comment]
Hi T,

thanks for your help.

Kind Regards,
Oliver

**Comment by bryevdv** [comment]
I am going to close this. Subsequent changes have rendered it unnecessary to use `trigger` in almost any situation (I can't find any example in the repo or docs that needs it anymore)
