### ISSUE TITLE
Arrows not updating from streaming data source

### ISSUE THREAD

**Issue by Lapin0t** [bokeh/bokeh#4872]
Hi, maybe I am doing it all wrong (I assume the documentation is WIP for app plots, events and stuff), but I am trying to plot arrows that are not annotations (my exact use case is drawing a directed graph)  and I can't get it to work.
The graph changes over time so I would like to write something like what I would do with Segments:

``` python
renderer = plot.arrow(end=Arrow(...), x0='x0', y0='y0', x1='x1', y1='y1', source=links)
```

Unfortunately, writing `plot.add_layout(Arrow(...), ..., source=links))` doesn't work. It don't know what exactly goes wrong, but nothing gets displayed. It might be that the render isn't updated as the source changes (I am updating it with `source.stream(new_data)` and the source is initially empty).

I am going to investigate to do it with something like [custom glyphs](http://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html#putting-it-together) but as I am not really fluent in js/coffee I may not achieve it that way either (that's why I am bringing this up here). Did I miss something? Is there a reason why arrows are annotations and not glyphs?

**Comment by bryevdv** [comment]
The use-cases we happened to have in mind are for arrows as annotations. Additionally we are very under-resourced at the moment. Being a general glyph has implications for spatial indexing and hit testing that annotations do not, arrows are also the first instance of a "compound" structure. We simply don't have the person power to investigate that avenue more fully right now. 

That said, passing a source should work just fine. But it's impossible to speculate what might be going wrong (either a bug or a usage error) without being able to run code. Can you provide a complete, minimal, run-able test case to reproduce the problem?

**Comment by Lapin0t** [comment]
I fully understand that my use case may not be very common and I satisfied myself with segments for now. Anyway, this sounds more like a weird corner case than a big design shortcoming to me.
After some trial error I got a quite minimal example: I am actually streaming from a periodic callback and the issue seems to originate from there. Here is a sample code that doesn't display any arrow:

```python
from random import randrange
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.layouts import layout
from bokeh.models import ColumnDataSource, Arrow, NormalHead

plot = figure()
source = ColumnDataSource(data={'x0': [], 'y0': [], 'x1': [], 'y1': []})
# if the plot only contains annotations it screws up range and scrolling
plot.circle(x=0, y=0)
plot.add_layout(
        Arrow(end=NormalHead(fill_color='black'), x_start='x0', y_start='y0',
        x_end='x1', y_end='y1', source=source))

def callback():
    source.stream({k: [randrange(10) for _ in range(5)] for k in ('x0', 'y0', 'x1', 'y1')})

curdoc().add_root(layout([[plot]]))
curdoc().add_periodic_callback(callback, 1000)
```

Obviously, this code doesn't fail if I replace the arrow plotting line with `plot.segment(x0='x0', y0='y0', x1='x1', y1='y1', source=source)`. Interestingly, this code still works as intended:

```python
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.layouts import layout
from bokeh.models import ColumnDataSource, Arrow, NormalHead

plot = figure()
source = ColumnDataSource(data={'x0': [], 'y0': [], 'x1': [], 'y1': []})
plot.circle(x=0, y=0)
plot.add_layout(
        Arrow(end=NormalHead(fill_color='black'), x_start='x0', y_start='y0',
        x_end='x1', y_end='y1', source=source))
curdoc().add_root(layout([[plot]]))
source.stream({'x0': [0], 'y0': [0], 'x1': [1], 'y1': [1]})
```

Just to be sure, I use bokeh 0.12.0 with python 3.4.3 and I launch the server with `bokeh serve --log-level debug --show test.py`

**Comment by bryevdv** [comment]
This does seem like a bug, I would expect the stream update from the callback to work

**Comment by bryevdv** [comment]
@Lapin0t There is a PR you can try out if you like #6281 For now you would have to build and install from source.  Also note I updated your code slightly in the test case there. Annotations do not participate in auto-ranging, so I added explicit x/y range bounds

**Comment by Lapin0t** [comment]
@bryevdv Thanks for clearing this out! This issue was raised in an old code i forgot about and for now i don't have the time to test it, but it seems okay to me.
