### ISSUE TITLE
graph 'running off'

### ISSUE THREAD

**Issue by adam-hubbell** [bokeh/bokeh#4875]
Sometimes, when an on_click/on_change method changes some part of the plot, the entire plot will move towards the bottom right corner of the space it was previously occupying, leaving an empty square in the middle of my document. I've run into this when changing the title, adding labels, and adding lines. Here's some example code that's know to cause the issue (this is run on the server), it tries adding a legend, and this causes the issue. 

```
from random import randint
from bokeh.plotting import Figure,curdoc
from bokeh.models.widgets import Select,Button
from bokeh.models import HBox,VBox,WidgetBox, VBox,HoverTool, WidgetBox, Label, WheelZoomTool, SaveTool, PanTool
from bokeh.io import curdoc
def make_plot():
    plot = Figure(x_axis_type="datetime", plot_width=700,tools=[HoverTool(tooltips=[("vol","$y"),("Date","@formDates")]),PanTool(),WheelZoomTool(),SaveTool()])
    plot.background_fill_color='#EAEBF0'
    plot.title.text = 'a title'
    plot.xaxis.axis_label ='x axis'
    plot.yaxis.axis_label = 'y axis'
    return plot

def make_widgets(plot):
    box = Select(title="Select",options=['a','b','c','d','e'])
    box5 = Select(title="Other Select", options=[])
    butt = Button(label = 'add some line')
    x_values=None
    y_values=None
    def box_change(attrname,old,new):
        box5.options.append(new)
        box5.value = box5.options[0]
    def box5_change(attrname,old,new):
        plot.title.text = "%s - %s" % (box.value,box5.value)
    def butt_click():
        nonlocal x_values
        nonlocal y_values
        y_values=[]
        x_values=[]
        for i in range(30):
            x_values.append(i)
            y_values.append(randint(0,999))
        line = plot.line(x_values,y_values,legend=str(randint(0,50)))
        line.data_source.data['x']=x_values
        line.data_source.data['y']=y_values
    box.on_change('value',box_change)
    box5.on_change('value',box5_change)
    butt.on_click(butt_click)
    return [box,box5,butt]

plot = make_plot()
widgets = make_widgets(plot)
curdoc().add_root(VBox(HBox(WidgetBox(*widgets),VBox(plot,height=1200)),width=1200))
```

**Comment by bryevdv** [comment]
ping @birdsarah in case you have any quick thoughts or pointers where to start. I think I've seen this in a couple of contexts.

**Comment by birdsarah** [comment]
I've seen this a few times too. I saw it when some WebGL stuff was broken. I think it's just the new way Bokeh looks when it's broken.  Not sure what other thoughts you were thinking of @bryevdv.

**Comment by bryevdv** [comment]
@birdsarah this happens without webgl, with the code above. My guess is that it has something to do with the frame layout coords computation so I was hoping for pointers where to start looking.

**Comment by birdsarah** [comment]
I just meant I've seen it a bunch, when a variety of different things were broken. I've seen it with tabs type stuff too if I recall.

What I'm trying to say is that we used to have the "white screen of death" when bokeh broke. And this is a new failure mode. 

To put another way, my hunch is that there is a problem in the above code that is breaking bokeh. The fact that you see the box disappearing to the right is just because bokeh is breaking.

**Comment by bryevdv** [comment]
OK, I cleaned up and pared down the example to be more minimal. In doing so I discovered that the `legend` argument to `line` is the proximate problem. If you restore the commented out `legend` in the code below, the original problem returns:
```
from random import randint

from bokeh.io import curdoc
from bokeh.layouts import row, column, widgetbox
from bokeh.models.widgets import Button
from bokeh.plotting import figure


def make_plot():
    plot = figure(x_axis_type="datetime", plot_width=700)
    plot.background_fill_color = '#EAEBF0'
    plot.title.text = 'a title'
    plot.xaxis.axis_label = 'x axis'
    plot.yaxis.axis_label = 'y axis'
    return plot


def make_widgets(plot):
    butt = Button(label='add some line')

    x_values = None
    y_values = None

    def butt_click():
        nonlocal x_values
        nonlocal y_values
        y_values = []
        x_values = []
        for i in range(30):
            x_values.append(i)
            y_values.append(randint(0, 999))

        # THE LEGEND IS THE PROXIMATE PROBLEM
        line = plot.line(x_values, y_values) #legend=str(randint(0, 50)))
        line.data_source.data = dict(x=x_values, y=y_values)

    butt.on_click(butt_click)

    return [butt]

plot = make_plot()

widgets = make_widgets(plot)

layout = column(row(widgetbox(*widgets), column(plot, height=1200)),
                width=1200)

curdoc().add_root(layout)
```

**Comment by bryevdv** [comment]
Another thing to mention, this is unproductive and probably just to be avoided:
```
line = plot.line(x_values,y_values,legend=str(randint(0,50)))
line.data_source.data['x']=x_values
line.data_source.data['y']=y_values
```
The last two lines just repeat what the first line did internally, and generate unecessary events.

**Comment by bryevdv** [comment]
Here is an even more minimal version (wanted to make sure the unusual closure/nonlocal usage was not related):
```
from random import randint

from bokeh.io import curdoc
from bokeh.layouts import row, column, widgetbox
from bokeh.models.widgets import Button
from bokeh.plotting import figure

plot = figure(x_axis_type="datetime", plot_width=700)
plot.background_fill_color = '#EAEBF0'


def cb():
    x_values = list(range(30))
    y_values = [randint(0, 999) for x in x_values]

    # THE LEGEND IS THE PROXIMATE PROBLEM
    plot.line(x_values, y_values, legend=dict(value=str(randint(0, 50))))

btn = Button(label='add some line')
btn.on_click(cb)

layout = column(row(widgetbox(btn), column(plot, height=1200)), width=1200)

curdoc().add_root(layout)
```

**Comment by bryevdv** [comment]
Stopping the server also stops the infinite JS console message, so I think perhaps the "overdrawing" is being caused by some kind of ping-ponging between the server and the browser.

**Comment by bryevdv** [comment]
In any event getting caught in some kind of infinite event loop:

<img width="1444" alt="screen shot 2016-12-10 at 4 17 16 pm" src="https://cloud.githubusercontent.com/assets/1078448/21076561/34f162fe-bef4-11e6-9af5-a299d9f59b7d.png">

**Comment by bryevdv** [comment]
OK, this version of this code is also instructive:
```
from random import randint

from bokeh.io import curdoc
from bokeh.layouts import row, column, widgetbox
from bokeh.models import Button, Legend, LegendItem
from bokeh.plotting import figure

plot = figure(x_axis_type="datetime", plot_width=700)
plot.background_fill_color = '#EAEBF0'
plot.add_layout(Legend(items=[]))

def cb():
    x_values = list(range(30))
    y_values = [randint(0, 999) for x in x_values]

    r = plot.line(x_values, y_values)
    plot.legend[0].items.append(
        LegendItem(label=dict(value=str(randint(0, 50))), renderers=[r])
    )

btn = Button(label='add some line')
btn.on_click(cb)

layout = column(row(widgetbox(btn), column(plot, height=1200)), width=1200)

curdoc().add_root(layout)
```
If run, this displays the line but not the legend, with errors like this reported:
```
ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): DeserializationError("Instance(GlyphRenderer) failed to deserialize reference to {'id': 'b78c69b5-0607-43eb-8b12-190b042296df', 'type': 'GlyphRenderer'}",)
DEBUG:bokeh.server.protocol.server_handler:  message header {'msgtype': 'PATCH-DOC', 'msgid': 'F4255E7EF639405E8E38C252949978B7'} content {'references': [{'attributes': {'label': {'value': '15'}, 'renderers': [{'id': 'b78c69b5-0607-43eb-8b12-190b042296df', 'type': 'GlyphRenderer'}], 'js_callbacks': {}, 'tags': [], 'name': None}, 'id': '5eaf71d6-9163-44b7-bc9b-b951b94be4e8', 'type': 'LegendItem'}], 'events': [{'new': [{'id': '5eaf71d6-9163-44b7-bc9b-b951b94be4e8', 'type': 'LegendItem'}], 'kind': 'ModelChanged', 'model': {'id': '7bb4e7e2-73fe-4137-9c25-5c20aa4db937', 'type': 'Legend'}, 'attr': 'items'}]}
```

I think this is related to some general problems with adding completely new models, especially if there are ref cycles. In this case, if the code is changed to `renderers=[]` then the reported errors disappear. 

I think this is related to the original problem. When "split up" like this, the problem manifests with the reference cycle errors. But when done using the `legend=` machinery, I think basically the same underlying problems are triggering a different code path that results in the ping-pong invalidation updates on the JS side.

**Comment by bryevdv** [comment]
Even with `renderers=[]` in the `LegendItem`, if `print(len(plot.legend[0].items))` is put at the end of the callback, we see weird/bad results like:
```
DEBUG:bokeh.server.session:Sending pull-doc-reply from session 'YtxFwLN5PUwPeAy61c1JpBsMFUVcaqFheKZKzlOnPWh2'
1
2
3
3
3
3
3
3
4
3
4
4
4
5
5
5
4
3
4
4
6
5
```

I do think something about the legend codepaths might be more complicated that other cases. But this is obviously wrong. 

@havocp is there any code to dump all the server messages? `debug` log level does not show them but I thought you might have had something at some point.

**Comment by bryevdv** [comment]
@clairetang6 I think your fix to array intersection may have also fixed this. There are still issues when running with your fix, but the major issues with the document models getting into a very bad state seems to be completely gone. What's weird is now the plot only updates when there *IS* a legend. 

That is, this works great with your fix:
```
from random import randint

from bokeh.io import curdoc
from bokeh.layouts import row, column, widgetbox
from bokeh.models.widgets import Button
from bokeh.plotting import figure

plot = figure(x_axis_type="datetime", plot_width=700)
plot.background_fill_color = '#EAEBF0'


def cb():
    x_values = list(range(30))
    y_values = [randint(0, 999) for x in x_values]

    plot.line(x_values, y_values, legend=dict(value=str(randint(0, 50))))

btn = Button(label='add some line')
btn.on_click(cb)

layout = column(row(widgetbox(btn), column(plot, height=1200)), width=1200)

curdoc().add_root(layout)
```

But this (without the legend) does not:
```
from random import randint

from bokeh.io import curdoc
from bokeh.layouts import row, column, widgetbox
from bokeh.models.widgets import Button
from bokeh.plotting import figure

plot = figure(x_axis_type="datetime", plot_width=700)
plot.background_fill_color = '#EAEBF0'


def cb():
    x_values = list(range(30))
    y_values = [randint(0, 999) for x in x_values]

    plot.line(x_values, y_values)

btn = Button(label='add some line')
btn.on_click(cb)

layout = column(row(widgetbox(btn), column(plot, height=1200)), width=1200)

curdoc().add_root(layout)
```
However by "not working" I just mean the plot does not update. he model/document corruption does not appear to be happening. So hopefully now there is maybe just some plumbing to fix up, which is a much simpler problem

**Comment by bryevdv** [comment]
OK, the current proximate problem with the non-legend version is that the property spec is not set correctly

<img width="321" alt="screen shot 2017-02-26 at 14 26 53" src="https://cloud.githubusercontent.com/assets/1078448/23343347/b72ea1aa-fc2f-11e6-8c6d-02f5e21249b3.png">

So I do think this is now just some kind of plumbing problem.

**Comment by bryevdv** [comment]
OK well digging a bit further, the problem happens in this code in the `HasProps` constructor:
```
  constructor : (attributes, options) ->
    @document = null

    ## straight from backbone.js
    attrs = attributes || {}
    if not options
      options = {}
    this.attributes = {}

    @properties = {}
    for name, {type, default_value} of @props
      if not type?
        throw new Error("undefined property type for #{@type}.#{name}")
      @properties[name] = new type({obj: @, attr: name, default_value: default_value})
```

When it calls the prop constructor, it passes itself as `obj` then the property constructor calls `obj.getv(name)` and this returns undefined, since the attributes aren's set up until immediately after this code block. Honestly I am more unsure of why this works at all in the cases when it seems to work.

**Comment by bryevdv** [comment]
OK well digging a bit further, part of the the problem happens in this code in the HasProps constructor:
```
  constructor : (attributes, options) ->
    @document = null

    ## straight from backbone.js
    attrs = attributes || {}
    if not options
      options = {}
    this.attributes = {}

    @properties = {}
    for name, {type, default_value} of @props
      if not type?
        throw new Error("undefined property type for #{@type}.#{name}")
      @properties[name] = new type({obj: @, attr: name, default_value: default_value})
```
When it calls the prop constructor, it passes itself as obj then the property constructor calls obj.getv(name) and this returns undefined, since the attributes aren's set up until immediately after this code block. This is interpreted as "use the default value" which happens to be null in this case, hence the result above. Honestly I am more unsure of why this works at all in the cases when it seems to work. I guess in the "initial doc init cases" that seem to work, something subsequent triggers an attr change which also triggers the property `init` again. 

I have a garbage fix, but hopefully it won't be too hard to turn it into a real fix.

**Comment by bryevdv** [comment]
OK the reason it works in the init case is because `attach_document` gets called on all new models then, which calls `prop.update`. This is not happening in patch doc on the new references. Adding a simple call to `attach_doc` on all new refs seems to fix the problem, and might be the best solution for now, but I want to investigate a little further.

**Comment by bryevdv** [comment]
For reference here is the diff that fixes all the examples:
```
diff --git a/bokehjs/src/coffee/document.coffee b/bokehjs/src/coffee/document.coffee
index e737182e3..274b2fdae 100644
--- a/bokehjs/src/coffee/document.coffee
+++ b/bokehjs/src/coffee/document.coffee
@@ -644,6 +644,8 @@ export class Document
         new_references[id] = value

     Document._initialize_references_json(references_json, old_references, new_references)
+    for id, obj of new_references
+      obj.attach_document(@)

     for event_json in events_json
       switch event_json.kind
```
All BokehJS tests pass with this. I am possibly inclined to add a new test to cover this case, and leve a more comprehensive cleanup/refactor to a separate issue
