### ISSUE TITLE
Tile attribution misaligned (see toolbar on right-side example)

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#4876]
ping @birdsarah

**Comment by birdsarah** [comment]
related to #4284

**Comment by birdsarah** [comment]
@mattpap, @bryevdv - this falls in my 1.0 bug collection.

**Comment by bryevdv** [comment]
What is this issue? Without a description, code, or screenshots I am inclined to close this.

**Comment by birdsarah** [comment]
see http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html#tile-providers
![screen shot 2017-05-31 at 8 04 33 pm](https://cloud.githubusercontent.com/assets/1796208/26660258/623295ec-463c-11e7-828d-261ba7585d46.png)

"ODBl" is popping out the side of the map

**Comment by bryevdv** [comment]
Awesome! thanks for the additional info @birdsarah

**Comment by mattpap** [comment]
This is another instance of issue where canvas is too big when toolbar is sticky.
