### ISSUE TITLE
INLINE from bokeh.resources has broken js?

### ISSUE THREAD

**Issue by lmcinnes** [bokeh/bokeh#4878]
I am working behind an airgapped network and want to get Bokeh working in my notebook. I have tried the following:

    from bokeh.resources import INLINE
    from bokeh.io import output_notebook
    output_notebook(resources=INLINE)

This gives an error

    Loading BokehJS ...
    
    Javascript error adding output!
    SyntaxError: property name line_alpha appears more than once in object literal
    Se your browser Javascript console for more details.

I am not really a javascript person so the console didn't seem that helpful. I could, however, look through the INLINE.js_raw and I found:

    >>> INLINE.js_raw[0][161041:161071]
    u',line_alpha:.3,line_alpha:.3})'

Which looks suspiciously bad.

For reference I am working off Anaconda 4.1.1, with Bokeh 0.12.0. Any suggestions for where and how to hack a file of javascript to remove a repeat would be appreciated (the relevant error seems to occur in the server/static/js/bokeh.min.js but I'm reluctant to just hack away at files I don't understand, and may not actually be the problem).

**Comment by mattpap** [comment]
This is due to a duplicated line in `bokehjs/src/coffee/models/annotations/poly_annotation.coffee`. Fixed in #4883.
