### ISSUE TITLE
Remove gear glyph from bokehjs to shrink resource size

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4879]
Since gear and gauge glyphs are rarely used, it'd be better to remove them from bokehjs and make them` __implementation__` glyphs in python.

**Comment by mattpap** [comment]
There is not such thing as gauge glyphs in bokeh. Besides this, I'm handling this in my current work regarding custom model precompilation.

**Comment by canavandl** [comment]
great - thanks @mattpap . I've updated the issue name to reflect that there isn't a gauge glyph.

**Comment by bryevdv** [comment]
Sorry, "gauge glyph" is a product of my aging mind.
