### ISSUE TITLE
"could not set initial ranges" since c098cb8ea218bdf7e503d2c4af099716740e5192

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4881]
"could not set initial ranges" warning appears in multiple examples since c098cb8ea218bdf7e503d2c4af099716740e5192. Verified on e.g. `plotting/file/color_scatter.py`.

**Comment by mattpap** [comment]
Everything works fine, I just didn't run `npm install` to update rbush. As long as we have to keep track of dependencies manually (and deal with other build related issues), lets not call a build system what we have in bokehjs. I just hope there is a JavaScript-specific tool out there which can be actually helpful (an equivalent of e.g. sbt would be great). I didn't find any yet.

**Comment by bryevdv** [comment]
Maybe there's done cheesy time stamp or hashing thing that could be fairly effective at warning if packages.json is new.
