### ISSUE TITLE
Allow User Defined Models to inherit from User Defined Models

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#4886]
To support external bokeh plugins, we need to be able to extend User Defined Models.  @mattpap any thoughts on this?

**Comment by mattpap** [comment]
@brendancol, in PR #4946, the `examples/models/custom.py` shows how to inherit from custom models.  This assumes all custom models ending up in one bundle. I'm not sure if this will be a problem or not. If so, this can be lifted, but for now I didn't want to solve possibly non-existent problems. Let me know if this matches your expectations for this issue. If not, feel free to elaborate on further expectations for this feature.

**Comment by mattpap** [comment]
I'm closing this, because custom models are now extensible. @brendancol, if there is anything missing in the current implementation, please reopen this with specific issues.
