### ISSUE TITLE
Sphinx Makefile creates a bad soft link

### ISSUE THREAD

**Issue by stvn66** [bokeh/bokeh#4909]
When compiling the documentation using the sphinx Makefile, a soft link is created in `sphinx/_build/html/` pointing to `../../../bokeh/server/static/` which is no longer a valid directory.  This was in the 12.0 version but has since been removed.  

I expect the Makefile should be updated to point at the correct directory or the directory should be returned to this location.

**Comment by bryevdv** [comment]
@stvn66 This directory definitely should and must exist, but it may not exist in a GH checkout until you run `setup.py` with `--build-js` or `--install-js` first. Can you confirm whether that resolves the issue for you? If so perhaps there is a better warning or fix. Regarding the PR, I'm not sure if the symlink is needed or actually used, offhand. It would require a little digging.

**Comment by stvn66** [comment]
I had not yet run the `setup.py` on the GH checkout I was working from.  Running this did create the directory.  I am closing this issue and removing the related pull request.
