### ISSUE TITLE
"bokeh serve foobar.ipynb --show" renders an empty page

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#4913]
`bokeh 0.12.1`

`bokeh serve foobar.ipynb --show` is expected to render an (interactive) representation of the notebook.
Using e.g. https://github.com/bokeh/bokeh-notebooks/blob/master/gallery/candlestick.ipynb results in an empty page, no js errors in the console.

**Comment by bryevdv** [comment]
@rs2 apologies if we have not set clear explanation. What you describe is not actually the expectation.  A notebook still has to do all the `curdoc` work, etc. that a python module version of an app does in order for `bokeh serve` to do anything with it. It's not currently expected that any arbitrary notebook be rendered by `bokeh serve`.
