### ISSUE TITLE
Using a Custom JSON Encoder

### ISSUE THREAD

**Issue by cperiz** [bokeh/bokeh#4918]
I am trying to pass a data source which consists of variables of type deque into the Bokeh server. Since Bokeh's JSON serialization currently does not support this format the probable best solution, right now, would be to allow one to write a custom JSON encoder. However, Bokeh currently does not allow for the specification of a custom JSON encoder in its software. This should be made possible.

**Comment by bryevdv** [comment]
I'm not certain this is a reasonable request, in general. Unlike the case where there is one or possibly two processes *both python* using the exact same custom serialization code at both ends, Bokeh is a multi-language project, and the other end of a completely general python custom serializer could need to be a corresponding custom JS serializer. Make the Bokeh JS serializer more extensible would be a much more involved process, and even were it done, it leaves open the door for very hard to debug mis-usages and the corresponding support burden. 

What *might* make sense is to have a way to adapt other types to the core set of Bokeh protocol types (which would be stable, and not change). If you'd care to work up a more detailed proposal for what that might look like from a user perspective, we'd be happy to consider it. 

Alternatively, a much shorter term solution is simply to make `deque` serializable by the built-in serializer. 

Thoughts @bokeh/dev ?

**Comment by cperiz** [comment]
I understand your point. I am not in a position to work up a more detailed proposal right now. If it doesn’t do much damage to the code, I would certainly appreciate it if you could make deque serializable by the built-in serializer.

**Comment by almarklein** [comment]
The relevant code is here: 
* https://github.com/bokeh/bokeh/blob/master/bokeh/core/json_encoder.py
* https://github.com/bokeh/bokeh/blob/master/bokeh/util/serialization.py

It should not be too hard to add support for `deque`. This is something we could do, though a PR from your end would ensure it will be added by the next release ;)

**Comment by cperiz** [comment]
If you do get it done, it would be much appreciated. If we manage to get down to resolving this we will certainly create a PR :)

**Comment by birdsarah** [comment]
Is this relevant: https://github.com/bokeh/bokeh/issues/3493

**Comment by bryevdv** [comment]
I just tried the code in #3493 and it still works fine on master. @cperiz can you provide some code where `deque` is failing?

**Comment by cperiz** [comment]
```python
from bokeh.plotting import figure, output_file, show, curdoc
from collections import deque
from bokeh.client import push_session
from bokeh.models import ColumnDataSource

session = push_session(curdoc())
p = figure(plot_width=400, plot_height=400)
x = deque([1, 2, 3, 4, 5])
y = deque([6, 7, 2, 4, 5])
source = ColumnDataSource(data=dict(x=x, y=y))
p.circle(x='x', y='y', size=20, color="navy", alpha=0.5, source=source)
session.show(p)

# Update plot
y = deque([6, 7, 2, 4, 10])
source.data['y'] = y
```

Here's a minimal code that fails the JSON serialization. I've attached part of the error that I get which comes from booked code:
```sh
/Users/charith/anaconda/lib/python2.7/site-packages/bokeh/core/json_encoder.pyc in default(self, obj)
     81             return obj.to_css()
     82         else:
---> 83             return self.transform_python_types(obj)
     84 
     85 def serialize_json(obj, encoder=BokehJSONEncoder, indent=None, **kwargs):

/Users/charith/anaconda/lib/python2.7/site-packages/bokeh/core/json_encoder.pyc in transform_python_types(self, obj)
     62             return float(obj)
     63         else:
---> 64             return super(BokehJSONEncoder, self).default(obj)
     65 
     66     def default(self, obj):

/Users/charith/anaconda/lib/python2.7/json/encoder.pyc in default(self, o)
    182 
    183         """
--> 184         raise TypeError(repr(o) + " is not JSON serializable")
    185 
    186     def encode(self, o):

TypeError: deque([1, 2, 3, 4, 5]) is not JSON serializable
```

We tested this with output_notebook() and push_notebook() and it doesn't suffer from this problem.

**Comment by bryevdv** [comment]
I think adding support for `deque` to the places where it is currently not working is reasonable (and probably not alot of work). I did confirm the above code still raises the error.

**Comment by bryevdv** [comment]
Confirmed the above code now works with #5615 

<img width="382" alt="screen shot 2016-12-27 at 9 18 25 am" src="https://cloud.githubusercontent.com/assets/1078448/21502458/844bd9b4-cc15-11e6-8131-7d9762355a6c.png">
