### ISSUE TITLE
Slider widgets do not seem to work with mobile devices (touchscreen swipe)

### ISSUE THREAD

**Issue by pythonUzer** [bokeh/bokeh#4919]
- Description of expected behavior and the observed behavior:
  Other widgets appear to work properly in web browser for mobile devices. Ideally one can swipe the screen and move the slider. Observed on chrome and firefox on android. It is unclear whether this would be considered a bug or feature.
- Sample code (from bokeh user guide):
```
  from bokeh.layouts import column
  from bokeh.models import CustomJS, ColumnDataSource, Slider
  from bokeh.plotting import Figure, output_file, show

output_file("callback.html")

x = [x*0.005 for x in range(0, 200)]
y = x

source = ColumnDataSource(data=dict(x=x, y=y))

plot = Figure(plot_width=400, plot_height=400)
plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)

def callback(source=source, window=None):
    data = source.get('data')
    f = cb_obj.get('value')
    x, y = data['x'], data['y']
    for i in range(len(x)):
        y[i] = window.Math.pow(x[i], f)
    source.trigger('change')

slider = Slider(start=0.1, end=4, value=1, step=.1, title="power",
                callback=CustomJS.from_py_func(callback))

layout = column(slider, plot)

show(layout)
```
- Stack traceback and/or browser developer tools console output:
  n/a
- Software version: 
  Python version      :  3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
  IPython version     :  4.1.2
  Bokeh version       :  0.12.1

**Comment by birdsarah** [comment]
You are correct that our slider is not very touch friendly. As a current work around, you can use a custom model extension to use something like the ion range slider which is much more touch friendly.

**Comment by bryevdv** [comment]
Marking `discussion` until there is a concrete proposal

**Comment by ttelfer** [comment]
@birdsarah could you explain how this is done or provide some links to documentation?

**Comment by bryevdv** [comment]
i just tried some of the deployed demo apps on a phone and swiping works for slider as expected. I assume this discussion was re: the old slider implementation so I am going to close now.
