### ISSUE TITLE
Add a type check to `show` for better error reporting

### ISSUE THREAD

**Issue by asmeurer** [bokeh/bokeh#4923]
Edit: was: `RuntimeError: Unable to save object of type '<class 'bokeh.models.renderers.GlyphRenderer'>'`

I'm trying to use Bokeh to do a simple function plot. I'm using the IPython notebook. 

```
xvals = np.linspace(-10, 10, 1000)
source = bokeh.models.ColumnDataSource(data=dict(x=xvals, y=np.sin(xvals)))

plot = bokeh.plotting.figure()
line = plot.line(source=source)
bokeh.charts.show(line)
```

This gives

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-1e1d5182cf85> in <module>()
      1 plot = bokeh.plotting.figure()
      2 line = plot.line(source=source)
----> 3 bokeh.charts.show(line)

/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/bokeh/io.py in show(obj, browser, new)
    302     if obj not in _state.document.roots:
    303         _state.document.add_root(obj)
--> 304     return _show_with_state(obj, _state, browser, new)
    305 
    306 

/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/bokeh/io.py in _show_with_state(obj, state, browser, new)
    320 
    321     if state.file or not shown:
--> 322         _show_file_with_state(obj, state, new, controller)
    323 
    324     return comms_handle

/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/bokeh/io.py in _show_file_with_state(obj, state, new, controller)
    325 
    326 def _show_file_with_state(obj, state, new, controller):
--> 327     filename = save(obj, state=state)
    328     controller.open("file://" + filename, new=_new_param[new])
    329 

/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/bokeh/io.py in save(obj, filename, resources, title, state, validate)
    398 
    399     filename, resources, title = _get_save_args(state, filename, resources, title)
--> 400     _save_helper(obj, filename, resources, title, validate)
    401     return os.path.abspath(filename)
    402 

/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/bokeh/io.py in _save_helper(obj, filename, resources, title, validate)
    458             doc = obj
    459         else:
--> 460             raise RuntimeError("Unable to save object of type '%s'" % type(obj))
    461 
    462         if validate:

RuntimeError: Unable to save object of type '<class 'bokeh.models.renderers.GlyphRenderer'>'

In [ ]:
```

If I first run `bokeh.io.output_notebook()` I get

```

Javascript error adding output!
TypeError: Cannot read property 'frame' of undefined
See your browser Javascript console for more details.
```

The console says

```
cdn.pydata.org/bokeh/release/bokeh-0.12.1.min.js:67 Bokeh: JS/Python version mismatch
cdn.pydata.org/bokeh/release/bokeh-0.12.1.min.js:67 Bokeh: Library versions: JS (0.12.0)  /  Python (0.12.1)
main.min.js:20239 TypeError: Cannot read property 'frame' of undefined(…)
```

**Comment by bryevdv** [comment]
you need to call show on `plot`. Also tell `line` which columns to use:

<img width="842" alt="screen shot 2016-08-03 at 5 29 36 pm" src="https://cloud.githubusercontent.com/assets/1078448/17384195/e83818cc-599f-11e6-8e78-c90a78f411ff.png">

I guess we need to put a type check in `show` to give better output.

**Comment by bryevdv** [comment]
This mismatch is a herring, there was a glitch with our last release build in updating the js version.

**Comment by bryevdv** [comment]
Also you do have to run `output_notebook` first, and almost definitely in a separate cell.

**Comment by bryevdv** [comment]
The `TypeError: Cannot read property 'frame' of undefined` has to do with the fact that you are showing something that is not show-able (a glyph renderer, instead of the plot).

**Comment by asmeurer** [comment]
Ahhh. The `'x'` and `'y'` arguments are also needed I guess (which makes sense since the data is a dictionary). By the way, any reason Bokeh doesn't automatically register Figure so that it just works if you type "plot" at the end of the cell in the notebook?

Also, I really want a `plot` function, akin to `matplotlib.pyplot.plot` that just does the right thing for function plotting. There's too much typing here just to plot a simple x vs. f(x). 

My goal here is to see if bokeh can be used as a backend for SymPy's `plot`. It looks promising so far. The next step is to see how hard it is to make it work with interactivity (so that it computes the data points if you drag the plot to the left or right).

**Comment by bryevdv** [comment]
Unless you need to control things like linked selections, there's no need to create your own `ColumnDataSource` explicitly. You can just:
```
from bokeh.plotting import show, figure

p = figure()
p.line([1,2,3], [4,5,6])

show(p)
```

There was a commented out `_repr_html` in the past, but it was very flaky. Time has to be allowed for BokehJS to load from CDN (or else use `INLINE` resources), if you do everything "too quickly" then things will fail. I've found no reliable way around this. 

A way to do the last thing you mentioned would be to add CustomJS callbacks on range changes that call the jupyter kernel execute JS API. This is what the DataShader `InteractiveImage` does.

**Comment by bryevdv** [comment]
There are also lower level ways to load BokehJS in the notebook that might be appropriate if you are "boxing" Bokeh in another library.

**Comment by asmeurer** [comment]
You don't include the Javascript with the conda package?

**Comment by bryevdv** [comment]
We do, the overwhelming preference was to switch to using `CDN` loading by default.

**Comment by asmeurer** [comment]
I'm not too worried about the API stuff for SymPy, since we would just be wrapping that. 

For the Javascript, though, what would be the cleanest way for us to handle it? It doesn't seem like calling `output_notebook()` automatically when the user does `plot` will work. We could also leave it to the user to do themselves (which we already require for matplotlib; the user has to type `%matplotlib inline` to get inline plots in the notebook).

**Comment by bryevdv** [comment]
If you want to do it for the user, and have it be reliable, use `INLINE` resources. But be aware that makes the saved notebooks considerably larger. 

Otherwise, it seems fine to have the user call it (or some function you make that wraps it) on their own. That's what Holoviews does. It might be helpful to ask @jbednar, et al for their input and experience using Bokeh as a backend for Holoviews.

**Comment by asmeurer** [comment]
Oh, I see why people wanted CDN to be the default :)

I am wondering if we should just use datashader. I saw @jbednar's excellent talk at SciPy, but it wasn't clear to me if it datashader requires computing all points beforehand, or if it also supports accessing the necessary points "on the fly". 

Also, if you want to move discussion this over to https://github.com/sympy/sympy/issues/11469 that's fine.

**Comment by bryevdv** [comment]
Quite possibly. DataShader computes on the fly. I'm not sure if that means it would be easier to use directly, or if would be easier to adapt some of it's machinery (e.g. `InteractiveImage`) for your own use. That's definitely a @jbednar question, though.

**Comment by jbednar** [comment]
Datashader is currently stateless, with no caching, indexing, or other computation done before the points are aggregated.  So I'm not sure what your needs for accessing things "on the fly" are, but I don't think there's any issue there.  Whether it's appropriate for sympy depends on the balance between the level of interactivity you are hoping to provide, versus the size of your datasets; see the datashader [FAQ](http://datashader.readthedocs.io/en/latest/#faq).  My usual recommendation would be to start with Bokeh, to get maximum interactivity, and move to datashader if you realize your datasets are too big and you're willing to give up some of the interactivity to be able to remove nearly all limitations on dataset size.

InteractiveImage has been very tricky to keep working well with different Bokeh versions, so I wouldn't recommend copying what it does internally in general; instead I'd hope we can move what it does into Bokeh itself so that it will work reliably across Bokeh versions.
