### ISSUE TITLE
Autoload_static seems to be broken in version 0.12

### ISSUE THREAD

**Issue by jnelson18** [bokeh/bokeh#4926]
As of version 0.12 (tried 0.12.0 , 0.12.1 , and  0.12.2dev1), the autoload_static function seems to be broken. Autoload_static still outputs a script tag and associated javascript, but when placed into an html document, the plot is in the uppermost left corner and has no toolbar. Furthermore, if any text is in the html, the plot will overlay the text and any other plot. I had a rather large working document that works in version 0.11, but not 0.12. The simple example from the [documents](http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html) shows the same error.

```python
from bokeh.resources import CDN
from bokeh.plotting import figure
from bokeh.embed import autoload_static

plot = figure()
plot.circle([1,2], [3,4])

js, tag = autoload_static(plot, CDN, "some/path")
```

 Python gives no errors. JavaScript also doesn't seem to give any errors, it may be in the CSS?
[BokehError.txt](https://github.com/bokeh/bokeh/files/403632/BokehError.txt)

I am using python version 3.5 and bokeh versions 0.12.0 and 0.12.1 and 0.12.2dev1 (still works in 0.11.x).

**Comment by birdsarah** [comment]
There was a fix to autoload_server in 0.12.1 - I wonder if it's related - ping @bryevdv

**Comment by bryevdv** [comment]
Probably, I used `autoload_static` in the blog post at https://bokeh.github.io/blog/2016/6/28/release-0-12-1/ but I had to put in an explicit `bk-root` div. Seems like the same template bug.

**Comment by bryevdv** [comment]
@jnelson18 the immediate workaround until a fix is released is to puttee script tag inside a `<div>` with `class="bk-root"` as is done here:

https://github.com/bokeh/bokeh.github.io/blob/source/content/blog/release-0-12-1/contents.lr#L85-L94

**Comment by bryevdv** [comment]
For reference here is the other issue: https://github.com/bokeh/bokeh/issues/4693

**Comment by bryevdv** [comment]
Tho looking at the fix in https://github.com/bokeh/bokeh/pull/4699 offhand I would have expected that to work for any script embed, either `autoload_server` or `autoload_static`. Will require some investigation.

**Comment by jnelson18** [comment]
The workaround worked in my case, I'll update if I find any other issues.
