### ISSUE TITLE
Event handler for width/height change of plot

### ISSUE THREAD

**Issue by bill10** [bokeh/bokeh#4927]
Good morning. Is there an event for size change of a plot? For x range, there is an event like
`fig.x_range.on_change('start', myfun)`

But none of the following works
`fig.on_change('plot_width', myfun)
  fig.on_change('width', myfun)
  fig.frame.on_change('width', myfun) #this one causes an error`

Any advice on how to capture the event of size change? Thank you.

**Comment by birdsarah** [comment]
No, that's not currently an event, but it would be reasonable to add one. I'm marking this as a feature.

**Comment by bryevdv** [comment]
The PR for read-only properties was merged, so this should be easy to add by simply adding readonly properties (which support the standard callback machinery)
