### ISSUE TITLE
Colorbar label ranges

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4934]
This is mostly a question for @canavandl.

With your implementation of ColorBar and of FuncTickFormatter will it be possible to have a colorbar like this where you explicitly spell out the ranges for people:

<img width="763" alt="screen shot 2016-08-08 at 2 43 59 pm" src="https://cloud.githubusercontent.com/assets/1796208/17497468/cee1ae12-5d76-11e6-85d8-fd4118ed6685.png">

**Comment by canavandl** [comment]
Close enough?

<img width="539" alt="screen shot 2016-08-08 at 7 04 13 pm" src="https://cloud.githubusercontent.com/assets/2198981/17500417/028d09d6-5d9b-11e6-84e5-07bef8fb31cb.png">

```python
import numpy as np

from bokeh.plotting import figure, show, output_file
from bokeh.models import ColorBar, LinearColorMapper, Plot, Range1d, BasicTickFormatter, LinearAxis, LogTicker, FixedTicker, FuncTickFormatter

output_file('cbar.html')

color_mapper = LinearColorMapper(palette="Spectral6", low=0, high=60)
ticker = FixedTicker(ticks=[5,15,25,35,45,55])
formatter = FuncTickFormatter(code="""
function(tick) {
    data = {5: '0-10', 15: '10-20', 25: '20-30', 35: '30-40', 45: '40-50', 55: '50+'}
    return data[tick]
}
""")

cbar = ColorBar(color_mapper=color_mapper, ticker=ticker, formatter=formatter,
                major_tick_out=0, major_tick_in=0, major_label_text_align='left',
                major_label_text_font_size='10pt', label_standoff=2)

p = Plot(x_range=Range1d(0,1), y_range=Range1d(0,1), width=500, height=500, toolbar_location=None)
p.add_layout(LinearAxis(), 'left')
p.add_layout(LinearAxis(), 'below')

p.add_layout(cbar)

show(p)
```

**Comment by birdsarah** [comment]
Nice!

**Comment by birdsarah** [comment]
Closing this as my question is answered.

**Comment by jainrp** [comment]
Hi:
When I run this code, I get warning as below and the plot is empty:
W-1001 (NO_DATA_RENDERERS): Plot has no data renderers: Plot(id='42629709-3675-4e38-bd08-1acf9ddb88e4', ...)

**Comment by bryevdv** [comment]
@jainrp The warning is expected (there are no glyphs). But the code is out of date. The callback convention was simplified so that only the function body is specified. On recent releases you would need:
```
formatter = FuncTickFormatter(code="""
    data = {5: '0-10', 15: '10-20', 25: '20-30', 35: '30-40', 45: '40-50', 55: '50+'}
    return data[tick]
""")
```

**Comment by bryevdv** [comment]
As an aside this is why current documentation is a better source of information that old issues:

https://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#functickformatter

**Comment by jainrp** [comment]
okay, thanks... Sorry I am somewhat new with this functionality so was trying to copy and paste to see what works. Will check the documentation in future as well for any changes
