### ISSUE TITLE
"Getting Set Up" section of documentation does not mention the base dependencies of Bokeh

### ISSUE THREAD

**Issue by stvn66** [bokeh/bokeh#4938]
When setting up a python environment for developing Bokeh, in addition to the dependencies listed in the [Getting Set Up page](http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup), one must also install the base dependencies for Bokeh.  @birdsarah mentioned a simple method for getting these dependencies by installing then removing Bokeh: `conda install bokeh && conda remove bokeh`.  Either something like this should be added to the documentation, or the explicit dependencies should be listed in addition to the development specific ones.

**Comment by bryevdv** [comment]
As long as you are editing this page can you also change
```
--build_js
--install_js
```
to 
```
--build-js
--install-js
```
which are the preferred forms.
