### ISSUE TITLE
Manual legend placement for charts API

### ISSUE THREAD

**Issue by kynan** [bokeh/bokeh#4941]
Using the basic plotting API the legend can be placed manually (most importantly off-canvas, #2865). It would be great to have support for off-canvas legend placement for the charts API too.

**Comment by birdsarah** [comment]
Totally agree. I thought there was an open issue for this, but I can't find it. @canavandl, might have been doing some related work lately with `auto` placement for colorbars.

But we need to define a full api - for `Chart` and for `Figure` keyword short cuts.

**Comment by kannanse** [comment]
Agree, need a legend location "outside" for Chart package to easily place the legends to the right of the chart. 

Often the legends within the chart overlap the data and I am forced to pan & re-align the plot.

Appreciate this ticket.

**Comment by joshusre** [comment]
Upvote for legend

**Comment by kannanse** [comment]
I tried chart.legend.location = (0.0,-30.0), but seems to remove the legend completely.

We have cases where the legend is longer than the chart & does not fully showup. Having the legend outside the chart is critical.

Has anyone been successful doing this on a BarChart API??

**Comment by tommycarstensen** [comment]
+1

**Comment by bryevdv** [comment]
`bokeh.charts` has moved to https://github.com/bokeh/bkcharts This issue should be re-opened there, if desired. However, it's better to look to HoloViews for a much more well-supported very high level API on top of Bokeh. `bkcharts` is effectively unmaintained t the moment.

**Comment by icfly2** [comment]
Great, another badly documented plotting interface to learn. I appreciate these are volunteer projects, but it is hard to get good enough and familiar to contribute back if there are so many changes.

**Comment by bryevdv** [comment]
@icfly2 I challenge you to go to the Bokeh docs site:

http://bokeh.pydata.org/en/latest/index.html

and come back with specific complaints. There are any number of improvements we can yet make to it, but after nearly 20 years of dealing with Open Source software, where many projects have literally zero docs, or a page or two, I stand by the Bokeh docs site as better, more complete, and more automated than 99% of OSS projects. It has a 100% complete reference guide, a gallery full of live example with code, a very large user's guide with hundred more live examples embedded, and a decent if not perfect developers guide as well. Please come back with actual constructive comments, those will actually be helpful.

**Comment by bryevdv** [comment]
Regarding "so many changes" the core essentials of `bokeh.plotting` API has been largely stable for *years*. The `bokeh.charts` API was jettisoned precisely because we didn't have the capacity to maintain it.

**Comment by icfly2** [comment]
This particular gripe was fueled by an extended amount of time spent looking for information that is on several different pages. In specific: [https://bokeh.pydata.org/en/latest/docs/reference/models/widgets.groups.html](https://bokeh.pydata.org/en/latest/docs/reference/models/widgets.groups.html )
contains the attributes of the widgets, while 
[https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html](https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html) contains the examples of how to add the widgets, but no information on how to get to the attributes. 

So while you are right in that the documentation is complete and automatic, if you don't know what you are looking for it is extremely hard to find the correct information. This isn't helped by the search function that gets you to the top level page for a certain result. (Though that is a read the docs quirk I think.)

So for direct actionable comment, a more complete example on the user guide to show best practice for the implementation of features would be helpful. Something I would be more than happy to help with, but as stated before I'm not confident I have any idea if what I do is best practice. I assume not.

**Comment by patricktokeeffe** [comment]
I know I'm grave digging here... but this complaint does have value:

> This particular gripe was fueled by an extended amount of time spent looking for information that is on several different pages.

I, too, find it annoying that when I finally find a relevant topic in the User Guide, I still wind up searching in the Reference API for the usage mechanics. Yes, Bokeh is heavily documented, but the documentation requires some familiarity to navigate effectively.
