### ISSUE TITLE
Resize doesn't work properly when output_file is used

### ISSUE THREAD

**Issue by cbcoutinho** [bokeh/bokeh#4944]
I made a small plot with explicitly defined width and height, but the resize tool doesn't work and causes the figure to wig-out. When no width/height is explicitly set, there seems to be no problem (EDIT: No actually, there is a problem either way).

Bokeh version 0.12.1
Chrome version Version 52.0.2743.116 m'
Notebook version 4.2.2
python version 3.4.5

I want to add the resize tool so that when I share my plot with colleagues, they can change the plot size how they would like, but at least the initial size is something I can control.

Sample code:

```
from bokeh.plotting import output_file, figure, show

import numpy as np

x = np.linspace(0,10,10)
y = x**2.0

output_file('test.html')

TOOLS = 'pan,box_zoom,wheel_zoom,resize,reset,save'

p = figure(x_axis_label="x", 
           y_axis_label="y", 
           tools=TOOLS, 
           toolbar_location="below",
           toolbar_sticky=False)

p.circle(x,y)

show(p)
```

Any ideas?

**Comment by bryevdv** [comment]
You code sample works as expected for me with both `0.12.1` and `master` on OSX Safari and Chrome `54.0.2816.4 dev`. Can you try the newer version of chrome to see if that makes a difference? What OS?

**Comment by birdsarah** [comment]
A screencast / screenshots of "wigging out" would also be helpful.

**Comment by cbcoutinho** [comment]
@bryevde When I open Chrome it says it is the highest version currently available. Should I need the development version of chrome to use bokeh? OS is Windows 7

@birdsarah I tried creating a video using camstudio, which immediately resulted in a 400mb .avi file - if I can figure out how to turn that into a small gif I will upload it. By wig-out, I mean clicking and holding the resize icon, and slightly moving to the right makes that corner of the figure suddenly jump two figure heights downwards. But then again, only sometimes. I will upload a video or screenshot asap. 

PS. Do you have a recommendation for recording quality screencasts?

**Comment by cbcoutinho** [comment]
Some screenshots I just took from the sample code posted earlier:

Initial plot:
![test1](https://cloud.githubusercontent.com/assets/12901868/17666264/b88c96a2-62ff-11e6-9dce-4412fc7feaf3.png)

Moving the mouse ever so slightly to the left causes the figure to jump downwards. The location of the mouse pointer was not included in the screenshot, so I highlighted where it was using a red dot:
![test2](https://cloud.githubusercontent.com/assets/12901868/17666333/1bb6a6a0-6300-11e6-85ec-30c10b8962da.png)

**Comment by bryevdv** [comment]
Unfortunately I can't seem to reproduce this which practically speaking means there's very little chance of finding a fix. I fired up a win7 VM and tried your code on `50.0.2661.94 m` and `52.0.2743.116 m` and it behaved exactly as I would expect.

**Comment by birdsarah** [comment]
I take a screen recording and then use ffmpeg and gifsicle to change it into a gif. I'm not sure whether those tools are available for windows.

**Comment by cp-boettcher** [comment]
Hello,
the resize bug still exist, but only when you explicitly define width and height!
@cbcoutinho You post a sample code.. Why is this missing?
You can check a example on my server: [resize_bug](http://mlu1ecjyhl7mthpo.myfritz.net/bug/)

**Comment by cbcoutinho** [comment]
Thanks for posting an example of the bug @cp-boettcher, indeed that's exactly what the bug looks like on my end.

The bug is still present on my Windows machine, but not on my Linux workstation. Also, to answer your question @cp-boettcher, the code snippet I posted continues to produce the bug on my end - regardless if the size is prescribed or not.

**Comment by cp-boettcher** [comment]
I get the bug only when the size is prescribed. But sometimes it would be better to set a default size.
Another interesting thing, I can reproduce the bug on my bokeh server too. bokeh-version 0.12.2

**Comment by cp-boettcher** [comment]
Hello,
with bokeh-version 0.12.4 resize works fine again!

The only thing is, that the resize icon doesn't move. 
![grafik](https://cloud.githubusercontent.com/assets/14564312/21927512/34372978-d986-11e6-8f5f-48c26f3f6269.png)
When you switch between the tools it appears again in the right place.

**Comment by mattpap** [comment]
Resize tool was removed.
