### ISSUE TITLE
bokeh serve error with directory format and --num-proc != 1

### ISSUE THREAD

**Issue by rheineke** [bokeh/bokeh#4945]
I am using the [directory format](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#directory-format) with a bokeh server that has a structure like:

```
fst_app
   |
   +---main.py
snd_app
   |
   +---main.py

```
If I set --num-procs to any integer other than 1, then I get the error message:

`ERROR:'DirectoryHandler' object has no attribute 'safe_to_fork'`

The command is:

`bokeh serve --num-procs 0 first_app snd_app`

The error occurs even with only one app specified, but I can explicitly pass --num-procs 1 without issue. I can also run the [single module format](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#single-module-format) with any number of processes.

**Comment by bryevdv** [comment]
Thanks for the report @rheineke this fix will be in `0.12.2` and any upcoming dev builds.
