### ISSUE TITLE
Plot title ignores sizing and appears italicized if number is provided but no units are specified

### ISSUE THREAD

**Issue by ieatkittens** [bokeh/bokeh#4948]
When setting `plot.title.text_font_size` to a number without providing any units (IE  `plot.title.text='20'`), the title defaults to 10pt and the text appears italicized regardless of the value set in plot.title.text_font_style (though it does respect the `plot.title.text_font_align` attribute). This behaviour doesn't match the behaviour if a non-number value is provided (which would cause the plot not to render).

If there is no default unit for sizing, I would expect that the behaviour would be the same as if I had provided a completely erroneous value (IE `plot.title.text_font_size='apples'`)

**Comment by bryevdv** [comment]
@mattpap what do you think about adding ` validate` to `FontSizeSpec` here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/properties.coffee#L257-L258

Also, why is the deprecation warning on the python side not getting triggered? When is `prepare_value` called?
