### ISSUE TITLE
Non-deterministic ordering of CSS resources for external resource loading.

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4950]
I was just using the new external resource loading feature of bokeh. I have a series of three css files. With css the ordering is important. It seems that the order that they're actually put into the document changes on each run.

ping @canavandl - is this likely or do you need more info?

**Comment by canavandl** [comment]
It looks like we're iterating through models in a dict, so the ordering isn't deterministic:

https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L284

I'll look into workarounds in a bit (and I've assigned myself in the issue)

**Comment by canavandl** [comment]
Here's the issue:

https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L293

We're deduplicating resources by casting to a set (which is unordered). We should either reassess the advisability of deduplicating (it's a big "magical", which isn't great) and decide to remove it or write a filter fxn.

**Comment by birdsarah** [comment]
Also JS is a problem too.
