### ISSUE TITLE
ModelExtensions - all resources from a whole module are loaded

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4951]
I setup a series of ModelExtensions with a base with the implementation and a bunch of subclasses for different skins.

``` python
class IonRangeSliderFlat(IonRangeSliderBase):
    __css__ = [
        "/css/ion.rangeSlider.css",
        "/css/ion.rangeSlider.skinFlat.css",
    ]


class IonRangeSliderHTML5(IonRangeSliderBase):
    __css__ = [
        "/css/ion.rangeSlider.css",
        "/css/ion.rangeSlider.skinHTML5.css",
    ]


class IonRangeSliderModern(IonRangeSliderBase):
    __css__ = [
        "/css/ion.rangeSlider.css",
        "/css/ion.rangeSlider.skinModern.css",
    ]
```

When I used one of them:

``` python
from ion_slider import IonRangeSliderFlat
s = IonRangeSliderFlat(..)
...
```

All the CSS from all the different subclasses were stuck into my html.

**Comment by birdsarah** [comment]
As a work around, putting the sub-classes in different files/modules prevented this.

**Comment by bryevdv** [comment]
@canavandl yah on further thought, the idea would be to only add resources for models that are actually in the document.

**Comment by bryevdv** [comment]
@birdsarah can you expand the original issue to a complete MRE?

**Comment by bryevdv** [comment]
noting this was solved fo the docs by adding a private API that the sphinx code can use to clear extensions in https://github.com/bokeh/bokeh/pull/7942 but need a general way to avoid this.

**Comment by mattpap** [comment]
This was fixed in PR #8749.

**Comment by bryevdv** [comment]
@mattpap do you have any objection to just making `_clear_extensions` public? There has not been much (any) complaint about this so I think it really only comes up in specialized situations like our docs. I think we could just make the method public for anyone who really does need it, and call it a day.

**Comment by bryevdv** [comment]
I intend to proceed as described above.
