### ISSUE TITLE
stack + group on bokeh.charts.Scatter creates surprising waterfall bar display

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#4955]
- Description of expected behavior and the observed behavior

`bokeh.charts.Scatter` accepts both `stack` and `group`. Used together appears to create some unexpected results, or would someone ever want to have a "waterfall" layout of grouped+stacked bars?
- Self-contained example code that generates the issue (if possible)

Second exercise here: https://github.com/bokeh/bokeh-notebooks/blob/master/tutorial/01%20-%20charts.ipynb (add `stack` without removing `group`)
- Stack traceback and/or browser developer tools console output

<img width="971" alt="screenshot 2016-08-12 15 45 53" src="https://cloud.githubusercontent.com/assets/293525/17639070/e6adc884-60a3-11e6-945c-799a81789710.png">
- Software version information output by `bokeh info` command

```
$ bokeh info
Python version      :  3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
IPython version     :  5.0.0
Bokeh version       :  0.12.1
BokehJS static path :  /Users/ijstokes/anaconda/envs/bokehtut/lib/python3.5/site-packages/bokeh/server/static
```

**Comment by bryevdv** [comment]
So, in a certain sense this seems "right", which is to say, I'm not sure it makes sense to group *and* stack on the *same* column. Can you describe a reasonable interpretation of that scenario (or point to other existing examples with other libraries)? If it doesn't make sense, the best and simplest thing would be to detect when this happens and issue an informative error.

**Comment by rthardin** [comment]
I ran in to this issue this afternoon. I have data from 4 different VMs. I can plot each VM side-by-side, and I can also stack them up to show the total:
![screen shot 2016-08-25 at 2 34 09 pm](https://cloud.githubusercontent.com/assets/1462450/17981968/f2636014-6ad3-11e6-8727-8064d60fcbd3.png)
![screen shot 2016-08-25 at 2 39 02 pm](https://cloud.githubusercontent.com/assets/1462450/17981974/f98e2b1c-6ad3-11e6-92ec-2c4cecf47738.png)

I want to compare this data set (green) to another data set (blue). I am using the `group` parameter for that (grouping by the data set):
![screen shot 2016-08-25 at 2 35 06 pm](https://cloud.githubusercontent.com/assets/1462450/17981978/fe6000d4-6ad3-11e6-8769-18ba04c92ff8.png)

When I combine `group` with `stack` to compare the stacked total, I expect something like this (please excuse my lousy Photoshop skills):
![stack_group](https://cloud.githubusercontent.com/assets/1462450/17982006/1172e448-6ad4-11e6-9ca7-1fb8a183d16c.png)

However, when I actually get looks like this:
![screen shot 2016-08-25 at 2 35 19 pm](https://cloud.githubusercontent.com/assets/1462450/17982022/21ef0630-6ad4-11e6-88f6-3a920d4b4e12.png)

I hope that makes sense - I'm not sure if the behavior I'm describing would break any other use cases.

**Comment by birdsarah** [comment]
Thanks for sharing this @rthardin - it's extremely helpful.

**Comment by birdsarah** [comment]
Also, it makes me very happy to see a grid of bokeh plots that someone's made for a realy life problem. We don't get to see that as often as we'd like.

**Comment by rthardin** [comment]
@birdsarah, thanks for your response. I've been using Bokeh at work for this kind of stuff since about 0.3. It's great, and keeps getting better!

**Comment by birdsarah** [comment]
>  I've been using Bokeh at work for this kind of stuff since about 0.3. 

WAT! I thought I was an insane early adopter and I got in the game at about 0.4. I remember showing it to @masoninman at the time, I was so excited and he just looked at me like I was crazy :D

**Comment by rthardin** [comment]
Wanted to check in on the discussion of this issue - @bryevdv, are the examples above helpful? Is there a way to produce the plot in the second-to-last example in Bokeh (i.e. stacked and grouped)? Thanks!

**Comment by bryevdv** [comment]
@rthardin there's not currently really anyone available to maintain `bokeh.charts` at the moment (anyone interested in that role would be warmly welcomed). For now I'd recommend using the recent `vbar` and `hbar` glyph methods added to `bokeh.plotting` instead.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/60)
