### ISSUE TITLE
Make plot with auto (100%) width/height

### ISSUE THREAD

**Issue by rornor** [bokeh/bokeh#4958]
I believe such method or argument does not exist, by browsing documentation extensively (figure width/height does not support something like 100%).
Poor man's solution to edit generated HTML file, then match `body.offsetWidth/Height` to `plot_width/height` is daunting.

Would you suggest other approach for 100% filled dashboard like plot?

**Comment by canavandl** [comment]
I believe that it's possible to use `sizing_mode='stretch_both'` to have a plot or group of plots/widgets to expand to fix the screen.

http://bokeh.pydata.org/en/latest/docs/reference/layouts.html#bokeh.layouts.gridplot

**Comment by rornor** [comment]
Very nice, thanks @canavandl 
It seems that gridplot accepts double iterator, so this worked much better than my manual JS intervention:
```python
p = gridplot([[fig]], sizing_mode='stretch_both')
show(p)
```

**Comment by canavandl** [comment]
Great. IIRC `figure` itself supports the `sizing_mode` kwarg. GridPlot accepts a double iterator because it's intended to contain rows of columns of plots.

I'm going to mark this as closed, but feel free to reopen if you have issues.

**Comment by rornor** [comment]
Right. Figure that accept `sizing_mode`, though it does not seem to be documented http://bokeh.pydata.org/en/latest/docs/reference/plotting.html#bokeh.plotting.figure.Figure
Probably it inherits this argument from elsewhere...

Thanks again @canavandl I'm finished here, please close this issue.
