### ISSUE TITLE
ImageURL example fails

### ISSUE THREAD

**Issue by xnx** [bokeh/bokeh#4959]
The ImageURL example at https://github.com/bokeh/bokeh/blob/master/tests/glyphs/ImageURL.py fails with 
`
RuntimeError: Models must be owned by only a single document, <bokeh.models.renderers.GlyphRenderer object at 0x1092b5f90> is already in a doc`

[Bokeh 0.12.1, Python 2.7 and 3.5]

**Comment by bryevdv** [comment]
Hi @xnx thanks for the report. The following diff will make those scripts runnable "normally":
```
$ git diff
diff --git a/tests/glyphs/ImageURL.py b/tests/glyphs/ImageURL.py
index 136a741..4e25ba0 100644
--- a/tests/glyphs/ImageURL.py
+++ b/tests/glyphs/ImageURL.py
@@ -1,9 +1,8 @@
 import numpy as np
 
-from bokeh.document import Document
 from bokeh.models import ColumnDataSource, Range1d, Plot, LinearAxis, Grid
 from bokeh.models.glyphs import ImageURL
-from bokeh.plotting import show
+from bokeh.io import curdoc, show
 
 url = "http://bokeh.pydata.org/en/latest/_static/images/logo.png"
 N = 5
@@ -43,7 +42,6 @@ plot.add_layout(yaxis,'left')
 plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))
 plot.add_layout(Grid(dimension=1, ticker=yaxis.ticker))
 
-doc = Document( )
-doc.add_root(plot)
+curdoc().add_root(plot)
 
 show(plot)
```
Would you be interested in contributing a PR to update all the scripts in that directory accordingly?

**Comment by xnx** [comment]
Aww, OK then.
