### ISSUE TITLE
DatePicker errors on input from Chrome on Windows 8.1

### ISSUE THREAD

**Issue by rheineke** [bokeh/bokeh#4965]
Using Chrome 52 on Windows 8.1, I find that DatePicker throws an error on any value chosen from the dropdown calendar. For same Chrome version on Mac OS X, I find that it always works.

I am using bokeh 0.12.0-1.

I have a bokeh server with the following code in app/main.py:

```
from bokeh.io import curdoc
from bokeh.models import DatePicker

curdoc().add_root(DatePicker())
```

and run with the command

`bokeh serve --log-level debug app`

The exception is:

```
2016-08-16 15:16:51,365 error handling message Message 'PATCH-DOC' (revision 1): ValueError('Unknown string format',)
2016-08-16 15:16:51,365   message header {'msgid': '8B5BE6EBF7044F8793268769745D6C7A', 'msgtype': 'PATCH-DOC'} content {'events': [{'new': 'Mon Aug 01 2016 00:00:00 GMT-0400 (Eastern Daylight Time)', 'model': {'type': 'DatePicker', 'id': '5f8ecfc4-a06e-428f-b21d-6ed1a34cefff'}, 'attr': 'value', 'kind': 'ModelChanged'}], 'references': []}
Traceback (most recent call last):
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/server/protocol/server_handler.py", line 38, in handle
    work = yield handler(message, connection)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/server/session.py", line 45, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/server/session.py", line 217, in _handle_patch
    message.apply_to_document(self.document)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/server/protocol/messages/patch_doc.py", line 92, in apply_to_document
    doc.apply_json_patch(self.content)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/document.py", line 955, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/core/properties.py", line 735, in set_from_json
    prop.set_from_json(self, json, models)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/core/properties.py", line 371, in set_from_json
    models)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/core/properties.py", line 323, in set_from_json
    return self.__set__(obj, json)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/core/properties.py", line 455, in __set__
    value = self.descriptor.prepare_value(obj.__class__, self.name, value)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/core/properties.py", line 274, in prepare_value
    value = self.transform(value)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/bokeh/core/properties.py", line 1529, in transform
    value = dateutil.parser.parse(value).date()
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/rheineke/anaconda/lib/python3.5/site-packages/dateutil/parser.py", line 555, in parse
    raise ValueError("Unknown string format")
```

**Comment by birdsarah** [comment]
Thanks for the report @rheineke - if you want to take a look at fixing it do let us know :D

**Comment by rheineke** [comment]
@birdsarah I think the right way to fix this issue is somewhere on the Javascript side. The datepicker input is '08/01/2016' so I assume Javascript is converting this to a datetime object and then serializing it again to 'Mon Aug 01 2016 00:00:00 GMT-0400 (Eastern Daylight Time)'. The serialization is probably using a system default datetime format. For me, the challenge is that I have very little idea how BokehJS works aside glossing over the [dev guide](http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup).

**Comment by rheineke** [comment]
Pretty sure the `d.toString()` call on line 26 of https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/date_picker.coffee just needs to be given an explicit date format string like `d.toString('yyyy-mm-dd')`

**Comment by sunpy02** [comment]
I got the same issue. I am on the latest Bokeh release. And also the calendar is not displayed with the correct style.

![datepicker](https://cloud.githubusercontent.com/assets/7226295/18056571/6637e4d4-6dda-11e6-82e5-de44d31dd6a3.PNG)

**Comment by omcodor** [comment]
encountered both the issues on Chrome 53,  Windows 7

@sunpy02 Style not working is open https://github.com/bokeh/bokeh/issues/4503

**Comment by bryevdv** [comment]
@birdsarah @bokeh/dev I think we should just remove `DateTimePicker` since we don't know how to fix it? (I'd suggest removing `Panel` as well) Thoughts?

**Comment by rheineke** [comment]
My comment from Aug 29 doesn't resolve the issue?:

Pretty sure the `d.toString()` call on line 26 of https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/date_picker.coffee just needs to be given an explicit date format string like `d.toString('yyyy-mm-dd')
`
I don't have a Bokeh development environment to test this, but it looks straightforward:

http://stackoverflow.com/questions/3066586/get-string-in-yyyymmdd-format-from-js-date-object

**Comment by birdsarah** [comment]
@bryevdv - Although we *should* just have a working DateTimePicker, we're short on bodies to do this. I'd say it's definitely better to not have a feature than to have a broken feature that we're not fixing.

**Comment by pkgandhi** [comment]
Is this issue still unresolved; I believe?

**Comment by bryevdv** [comment]
@pkgandhi the resolution will probably be to remove the date picker entirely. If you need a date picker, you best bet is to pick a nice JS one and create a custom extension for it:

http://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html

**Comment by pkgandhi** [comment]
Gotcha! Thanks Bryan!

**Comment by pkgandhi** [comment]
@bryevdv : Any relevant or simple example for this, meaning to create add an extension?

**Comment by bryevdv** [comment]
@pkgandhi all the examples of extension that I know of are in the link above.

**Comment by cp-boettcher** [comment]
I got the same issue with Internet Explorer 11. Bokeh Server 0.12.4.
[bokeh] Unhandled ERROR reply to E927B3FBA8B54BE88A9D2C2CF6180422: ValueError('Unknown string format',)
Firefox works fine. To resolve the style problem I put the missing jquery css file in the static folder. 
An Example with another  JS DatePicker would be helpful. 
But could a custom extension also communicate with the bokeh server?
After my datepick python code has to be executed.

**Comment by rheineke** [comment]
I have a relatively simple fix that has worked for me since I put this ticket in. I'll commit and make a pull request this weekend.

For anyone who wants to fix it now in bokeh 0.12.4, change line 1052 of bokeh/core/properties.py to
`value = dateutil.parser.parse(value.split(' (')[0]).date()`

Essentially, the problem is that Windows (Chrome) has a different default datetime format that includes the timezone in parentheses. The code change above intercepts this at deserialization in Python. A more elegant solution would be to specify the datetime format at serialization in JS.

**Comment by artur-scholz** [comment]
Hi! I find the date picker functionality very useful. It is still there in the current bokeh (0.12.9) put appears to be broken: 
```
date_picker = DatePicker()
date_picker.on_change("value", callback_datepicker)
def callback_datepicker(attr, old, new):
    print("this callback gets never called")
```
In the datepicker tool I select a date by clicking on it, but the on_change callback gets never called. Any idea? And what is the future for datepicker, will it be removed?

**Comment by bryevdv** [comment]
@artur-scholz please update your code sample to be complete (runnable without modification)

**Comment by mattpap** [comment]
> And what is the future for datepicker, will it be removed?

No. It was reimplemented recently from scratch and is going to stay. There may some issues though, especially with signal handling.

**Comment by artur-scholz** [comment]
I tried try provide a reproducible code with the notebook, but as it would need the bokeh server, it would be too much work. Let's see if we can sort this out in another way.

As you can see, I tried it with the "on_change" callback. Another way is to try it with a JS callback 
```
date_picker = DatePicker(callback=CustomJS(code="""console.log('Hello')"""))
```
This produces the log output on the browser, followed by an error message:
```
Hello  bokeh.min.js:4:1
[bokeh] Unhandled ERROR reply to D17DAC21882E439B9E8EE97DDCB56CE4: ValueError('Unknown string format',)  bokeh.min.js:1:3070
	ERROR http://localhost:5006/static/js/bokeh.min.js:1:3070
	Bokeh</<.client</o</t.prototype._steady_state_handler http://localhost:5006/static/js/bokeh.min.js:1:9709
	Bokeh</<.client</o</t.prototype._awaiting_ack_handler/this._current_handler</< http://localhost:5006/static/js/bokeh.min.js:1:9368
	Bokeh</<.client</o</t.prototype._on_message_unchecked http://localhost:5006/static/js/bokeh.min.js:1:8334
	Bokeh</<.client</o</t.prototype._on_message http://localhost:5006/static/js/bokeh.min.js:1:7546
	Bokeh</<.client</o</t.prototype.connect/</</t.socket.onmessage http://localhost:5006/static/js/bokeh.min.js:1:4571
```

**Comment by bryevdv** [comment]
> I tried try provide a reproducible code with the notebook, but as it would need the bokeh server, it would be too much work.
 
There are 10s (100s now?) of thousands of Bokeh users now, and ~700 issues. *Everyone* is going to have to do a little more work, so that the the few maintainers are not saddled with an *impossible* amount of work. 

As you say, this requires the bokeh server. (If you aren't using the sever currently, that's why it's not working. `on_change` only works with the server. It's not clear from your description how you are runing things. This is why complete reports are important) If you alreay have a notebook, you can just share a link to the notebook, it doesn't have to be inline here. Otherwise, you can put the code to reproduce  in plain python script that can just be run like `bokeh serve app.py` (this would actually be preferable).

**Comment by bryevdv** [comment]
I also only just realized this is not a new issue (was a phone when looking at it). @artur-scholz this is a distinct issue from anything earlier here. Please open a new separate issue with so this is not unnecessarily entangle with other platform dependent date picker issues.

**Comment by bryevdv** [comment]
@mattpap the original issue had to do with styling, I believe that can be closed? In order to keep things organized an separate I believe it should be if that is the case. Issues that meander from one thing to another are very difficult to follow and track.

**Comment by mattpap** [comment]
@bryevdv, this is a different issue, just people were reporting styling issues as well here. I'm not sure this one was actually fixed. I have a few things to test on windows anyway, so I will verify.

**Comment by artur-scholz** [comment]
@bryevdv I fully agree that providing more input from the user side is needed to keep an OSS project running. What I will do is to provide my codebase once its an a good shape. I am using bokeh to display timelines that reload upon panning, could be quite of interest to others.

And yes, I am working on an application making use of bokeh server; I tried though to set up a simple notebook script to demonstrate the error, but that won't work, as it needs the server interaction.

@mattpap I implemented your suggestions to change line 1050 of bokeh/core/properties.py to
value = dateutil.parser.parse(value.split(' (')[0]).date()

Now the error does not show up in the browser, but the on_change callback is still not reached (I had put a `import pdb; pdb.set_trace()`) at the first line of the callback function to make sure.

**Comment by volkerjaenisch** [comment]
@bryevdv I can confirm the findings of @artur-scholz. 
The problem is in date_picker.coffee.
`  _on_select: (date) =>
    @model.value = date.toString()
    @change_input()
`
Resulting on win10/IE to: "'Sun Sep 24 2017 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)'
Fix is easy. 
`  _on_select: (date) =>
    @model.value = date.toISOString()
    @change_input()
`
Resulting to: "2017-09-22T22:00:00.00Z"

The former cannot be parsed by dateutil:
`>>> value = dateutil.parser.parse('Sun Sep 24 2017 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)')
Traceback (most recent call last):
  File "/home/volker/workspace/eprofile/lib/python3.5/site-packages/python_dateutil-2.6.1-py3.5.egg/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format`

The later can be parsed.
>>> dateutil.parser.parse('2017-09-22T22:00:00.00Z')
datetime.datetime(2017, 9, 22, 22, 0, tzinfo=tzutc())

@bryevdv  Shall I create a GH-issue and a PR?

**Comment by bryevdv** [comment]
@volkerjaenisch yes please, and thanks for running this down
