### ISSUE TITLE
Reference docs don't show inherited properties

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4966]
I noticed this comment on #4958 from @rornor.

> Right. Figure that accept sizing_mode, though it does not seem to be documented http://bokeh.pydata.org/en/latest/docs/reference/plotting.html#bokeh.plotting.figure.Figure
> Probably it inherits this argument from elsewhere...

If you're trying to help yourself, going to the reference docs for a specific model I'm not sure you should have to go all the way up the class hierarchy to LayoutDOM manually to see that there's a sizing_mode option.

Thoughts @bryevdv?

**Comment by bryevdv** [comment]
I think they should, I thought they already did. Tho I can't find the `:inherited-members:` directive that would trigger that in current master. It would probably go here:

https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_model.py#L46-L51

**Comment by bryevdv** [comment]
So, yes adding `:inherited-members:` there does the trick, but it really explodes the list for eery model and includes a lot of noise most users will never care about. So, I'd like to do this, but I'd like to enhance the sphinx extensions to be able to group members differently and better, and to have some "advanced" groupings collapsed by default.

**Comment by jhdedrick** [comment]
I'm not sure if this should be a comment here or a new issue:
There is basically no documentation available for "sizing_mode".  The "Laying out Plots and Widgets" page https://bokeh.pydata.org/en/latest/docs/user_guide/layout.html is careful to instruct the user that consistent sizing modes are important, but doesn't say which options are available nor what they do.  You can find a one-line list of the legal values under "enums" https://bokeh.pydata.org/en/latest/docs/reference/core/enums.html but no info about functionality.

**Comment by bryevdv** [comment]
As stated above the docs for `sizing_mode` are down on a base class:

http://bokeh.pydata.org/en/latest/docs/reference/models/layouts.html#bokeh.models.layouts.LayoutDOM.sizing_mode

**Comment by bryevdv** [comment]
moving to 2.0 as a reminder to try setting full output again and seeing if the page sizes are tolerable before release.
