### ISSUE TITLE
Add documentation of ordering on external resources

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4968]
Following on from #4954:

From @canavandl:

> The code LGTM. Can you add a mention of resource ordering (both inter and intra-Models) to https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/extensions.rst#supplying-external-resources?

**Comment by bryevdv** [comment]
I'm no longer sure what was intended to be added, so without more detail I will close this.
