### ISSUE TITLE
Sharing Plot from Bokeh Server with People on Other Network

### ISSUE THREAD

**Issue by Akpadhy** [bokeh/bokeh#4969]
Lets say i have a server in Seattle where one of a person ran 
bokeh serve myapp.py 
script on linux shell.And I am trying to access that portal or link from London using my office laptop.However now i am not able to access it so what setting i need to do so that everyone can access it.

**Comment by bryevdv** [comment]
This kind of general support question belongs on the public mailing list, so that we can reserve the issue tracker for feature requests, bug reports, and dev-related discussions.

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh
