### ISSUE TITLE
Histogram Chart incorrectly stacks bars when distribution range is small

### ISSUE THREAD

**Issue by commondatageek** [bokeh/bokeh#4973]
When using Histogram on a distribution with a small range (say, 1000 samples from Uniform(0.55, 0.65)), it stacks the bars instead of laying them out side-by-side in a full distribution as I would expect.

See this gist: https://gist.github.com/aaronj1331/2fe891401f3a1a174995f9db0df24af0

Python version      :  3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
IPython version     :  5.1.0
Bokeh version       :  0.12.1
BokehJS static path :  /home/aaronj/anaconda3/envs/py3/lib/python3.5/site-packages/bokeh/server/static

<img width="751" alt="screenshot_8_17_16__9_09_am" src="https://cloud.githubusercontent.com/assets/349712/17741673/5277b322-645a-11e6-9518-9e6a2624090d.png">

**Comment by aaronj1331** [comment]
Other combinations of low/high parameters for Uniform yield different erroneous results.  Try, for example:

- low=5.5, high=5.6
- low=5.5, high=5.8

<img width="731" alt="screenshot_8_17_16__9_13_am" src="https://cloud.githubusercontent.com/assets/349712/17741842/fd6b8e8e-645a-11e6-823b-9a5f4c33bdc5.png">

**Comment by bryevdv** [comment]
charts are now in a new separate repo/project. Pleas re-open in https://github.com/bokeh/bokeh if this issue is still relevant.
