### ISSUE TITLE
Plot range reverts to initial range when line is added to plot

### ISSUE THREAD

**Issue by adam-hubbell** [bokeh/bokeh#4975]
I have a piece of code that's supposed to adds a line to a bokeh plot, using figure.line, then calls resize(), which alters the x and y range to fit all visible lines on the plot. When I click the button to run this method, the line appears, but the graph, no matter what lines are on the plot, resets it's x and y ranges to their initial values. When I set resize() to be called by a regular button press, the plot resizes as expected, it also resizes when I call resize at the end of a method that makes lines visible/invisible on checkbox click. 

here's an example of the debug messages I'm receiving:

> # creating a line
> ---
> 
> START VALUES:
> X:      0 to 50
> Y:      -20 to 20
> calculating range
> END VALUES:
> X:      -4 to 103
> Y:      -10 to 9
> ---
> # clicking resize
> ---
> 
> START VALUES:
> X:      0 to 50
> Y:      -20 to 20
> calculating range
> END VALUES:
> X:      -4 to 103
> Y:      -10 to 9
> ---
> # making invisible, then visible, the line (defaults to 0-100 for x and y)
> ---
> 
> START VALUES:
> X:      -4 to 103
> Y:      -10 to 9
> END VALUES:
> X:      0 to 100
> Y:      0 to 100
> ---
> ---
> 
> START VALUES:
> X:      0 to 100
> Y:      0 to 100
> calculating range
> END VALUES:
> X:      -4 to 103
> Y:      -10 to 9
> ---
> # add another line then click resize
> ---
> 
> START VALUES:
> X:      -4 to 103
> Y:      -10 to 9
> calculating range
> END VALUES:
> X:      -4 to 103
> Y:      -21 to 20
> ---
> ---
> 
> START VALUES:
> X:      0 to 50
> Y:      -20 to 20
> calculating range
> END VALUES:
> X:      -4 to 103
> Y:      -21 to 20
> ---

With the resize functionality, I would expect the start values for any given call to resize to always match the end values of the previous call, considering nothing else I'm doing resizes the plot. But when I call click resize after creating a line, you'll see that the start value for the second call to resize doesn't match the end value for the first call, which is where the issue lies. 

footnote:
If I put a "time.sleep(5)" at the end of resize, I find that I don't have time imported;). But after that, I find that the line doesn't show up on the plot until after it's finished sleeping(meaning add_line is finished), which is probably where the issue comes from.

```

from bokeh.plotting import figure,curdoc
from bokeh.models import DataRange1d
from bokeh.models.widgets import Button,CheckboxGroup
from bokeh.layouts import row,column
from numpy.random import randint

#this example is limited by the number of colors, but you should see the error
#before that point
colors = ['red','blue','green','yellow','orange','purple','gold','black','pink']

plot = figure(
    x_range=DataRange1d(start=0,end=50),
    y_range=DataRange1d(start=-20,end=20)
    )
lines = []
rsz_button = Button(label='resize')
add_line_button = Button(label = 'add a line')
line_onOff = CheckboxGroup()
coef = 1


def calc_range():
    global lines
    #finds the max and min x and y from all visiable lines
    xmin = float(99999)
    xmax = float(-99999)
    ymin= float(99999) 
    ymax = float(-99999)
    print('calculating range')
    for i in lines:
        if i.glyph.visible:
            if min(i.data_source.data['x']) <xmin:
                xmin =  min(i.data_source.data['x'])
            if  max(i.data_source.data['x']) >xmax:
                xmax = max(i.data_source.data['x'])
            if min(i.data_source.data['y']) <ymin:
                ymin =  min(i.data_source.data['y'])
            if max(i.data_source.data['y']) >ymax:
                ymax = max(i.data_source.data['y'])

    #add some padding to go around the lines
    pad = 0.05
    xpad = (xmax-xmin)*pad
    ypad = (ymax-ymin)*pad
    return xmin-xpad,xmax+xpad,ymin-ypad,ymax+ypad

def resize():#resizes the plot to fit the lines, print some debug statements
    print('\n_________________________________\nSTART VALUES:\nX:\t%d to %d\nY:\t%d to %d'
        %(plot.x_range.start,plot.x_range.end,plot.y_range.start,plot.y_range.end))
    if len(line_onOff.active) == 0 or len(line_onOff.labels)==0:
        #if there are no lines, default to 0-100 range
        plot.x_range.start = 0
        plot.x_range.end = 100
        plot.y_range.start = 0
        plot.y_range.end =  100
    else:
        xmin,xmax,ymin,ymax = calc_range()
        plot.x_range.start = xmin
        plot.x_range.end = xmax
        plot.y_range.start = ymin
        plot.y_range.end = ymax
    print('END VALUES:\nX:\t%d to %d\nY:\t%d to %d\n_________________________________\n'
        %(plot.x_range.start,plot.x_range.end,plot.y_range.start,plot.y_range.end))




def add_line():
    global coef # a coefficient that gets incremented as to better show my issue
    color_index = randint(0,len(colors))

    #add a line with a random color, use the color name as the checkbox label
    lines.append(
        plot.line(
            x=[i for i in range(0,100)],
            y=randint(low=-10*coef,high=10*coef,size=100),
            color=colors[color_index],
            line_width=3
            )
        )

    #remove the added color to avoid repeats
    colors.pop(color_index)

    #add the new line to the on/off checkbox group, and check that box
    #remove then unremove the callback to line_onOff so that resize only
    #gets called once per line addition
    line_onOff.remove_on_change('active',line_onOffChange)
    line_onOff.labels.append(lines[-1].glyph.line_color)
    line_onOff.active.append(len(line_onOff.labels)-1)
    line_onOff.on_change('active',line_onOffChange)

    #increment the coefficient
    coef+=1

    #call resize, here lies the error
    resize()


def line_onOffChange(attrname,old,new):

    #turn lines on/off 
    for i in range(len(line_onOff.labels)):
        if i in line_onOff.active:
            lines[i].glyph.visible = True
        else:
            lines[i].glyph.visible= False

    #call resize, it works here
    resize()

add_line_button.on_click(add_line)
rsz_button.on_click(resize)
line_onOff.on_change('active',line_onOffChange)

wids = column(add_line_button,rsz_button,line_onOff)
plot_col = column(plot)
every = row(wids,plot_col)
curdoc().add_root(every)

```

bokeh info output:

Python version      :  3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit
(AMD64)]
IPython version     :  4.1.2
Bokeh version       :  0.12.1
BokehJS static path :  c:\anaconda3\lib\site-packages\bokeh\server\static

**Comment by bryevdv** [comment]
Hi @adam-hubbell sorry this took so long to look at, we are stretched very thin at the moment. As it happens, you problem is this: 
```
plot = figure(
    x_range=DataRange1d(start=0,end=50),
    y_range=DataRange1d(start=-20,end=20)
    )
```
If you explicitly set `start` and `end` on a data range, then those values are taken as overrides of the automatic data ranging capability. That is, those are the values used for "resets", which is exactly what you are are seeing. 

I changed your code in two ways:
* just did `plot = figure()`
* removed the call to `resize` in `add_line`

And then it functioned as expected.

This does cause a "blank" plot to start, if you want to start with visible axes/grids, I could suggest maybe adding some sort of dummy invisible (`alpha=0`) renderer for the data ranges to work with at the very start. 

There are a few possible tasks that this suggests, please feel free to open other issues to discuss if you think they would be useful:

* policy for setting initial data range values without overriding reset behavior?
* policy to exclude invisible renderers from auto-ranging? (could then get rid of your `resize` func altogether)
