### ISSUE TITLE
Bokeh charts do not render when downloading a Jupyter notebook as HTML

### ISSUE THREAD

**Issue by slilienfeld** [bokeh/bokeh#4980]
I recently updated my version of Bokeh, and all charts look and work exactly as desired in the Jupyter notebook.  However, when downloading the notebook as HTML, none of the charts are showing up.  Version info is as follows:

Python version      :  3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) 
IPython version     :  5.0.0
Bokeh version       :  0.12.1

**Comment by bryevdv** [comment]
Are there any errors in the JavaScript console of your browser? 

@jbednar did you say you had seen similar?

**Comment by jbednar** [comment]
@bryevdv, sounds like a different issue; when I've had version combinations that made Bokeh charts disappear, they weren't in the notebook version either.

**Comment by philippjfr** [comment]
I just ran into this as well when I used nbconvert on a notebook. This is because this line in the ``output_notebook`` output fails when Jupyter is not available:

```python
var kernel = Jupyter.notebook.kernel
```

**Comment by slilienfeld** [comment]
Yeah just like @philippjfr I'm seeing an 

    Uncaught ReferenceError: Jupyter is not defined

in the JavaScript console of the HTML version of the notebook.

**Comment by bryevdv** [comment]
Well I think it's the same cause? Adding the line `var kernel = Jupyter.notebook.kernel` unconditionally was the mistake. If anything about the `kernel.execute` is to remain for the live notebook case, I guess we just need to test for the existence of `Jupyter` first, and and skip it if not present (on the assumption that it's a static notebook output)

**Comment by bryevdv** [comment]
This is the same of #4987
