### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by jobini** [bokeh/bokeh#4985]
Trying to make a bar chart from a Blaze dataframe `df`, I ended up with this error:

```
---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-3-6670bae09dbd> in <module>()
          2 from bokeh.io import output_notebook
          3 
    ----> 4 p = Bar(df,"overall",values = "wordcount",title="Bar Plot")
          5 
          6 output_notebook()
    
    /home/jobsism10/anaconda2/lib/python2.7/site-packages/bokeh/charts/builders/bar_builder.pyc in Bar(data, label, values, color, stack, group, agg, xscale, yscale, xgrid, ygrid, continuous_range, **kw)
        319     kw['y_range'] = y_range
        320 
    --> 321     chart = create_and_build(BarBuilder, data, **kw)
        322 
        323     # hide x labels if there is a single value, implying stacking only
    
    /home/jobsism10/anaconda2/lib/python2.7/site-packages/bokeh/charts/builder.pyc in create_and_build(builder_class, *data, **kws)
         66     # create the new builder
         67     builder_kws = {k: v for k, v in kws.items() if k in builder_props}
    ---> 68     builder = builder_class(*data, **builder_kws)
         69 
         70     # create a chart to return, since there isn't one already
    
    /home/jobsism10/anaconda2/lib/python2.7/site-packages/bokeh/charts/builder.pyc in __init__(self, *args, **kws)
        292             # make sure that the builder dimensions have access to the chart data source
        293             for dim in self.dimensions:
    --> 294                 getattr(getattr(self, dim), 'set_data')(data)
        295 
        296             # handle input attrs and ensure attrs have access to data
    
    /home/jobsism10/anaconda2/lib/python2.7/site-packages/bokeh/charts/properties.pyc in set_data(self, data)
        170             data (`ChartDataSource`): the data source associated with the chart
        171         """
    --> 172         self.selection = data[self.name]
        173         self._chart_source = data
        174         self._data = data.df
    
    TypeError: 'NoneType' object has no attribute '__getitem__'
```
The dataframe `df` looks like [this](http://i.stack.imgur.com/c30lf.png), with about 25 million entries in it.

The code used to try to make the bar chart was this:

   ```
 from bokeh.charts import Bar, show
 from bokeh.io import output_notebook
 p = Bar(df,"overall",values = "wordcount",title="Bar Plot")
 output_notebook()
 show(p)
```
Is this a bug, or are Blaze dataframes not completely supported yet?

**Comment by necaris** [comment]
@jobini Can you help us understand what you mean by a Blaze dataframe? How did you create the dataframe?

**Comment by jobini** [comment]
@necaris Sorry for being vague there. What I meant by it being a "Blaze dataframe" is that it is a [Blaze](http://blaze.readthedocs.io/en/latest/index.html) expression, resembling a Pandas dataframe. I created the dataframe by taking data from an Sqlite database, using the following code:
```
# Here, the Sqlite database is "sqlite_db.db" and 
# "table_in_db" is the table within the database 
# containing the data

df = data('sqlite:///sqlite_db.db::table_in_db')
```

**Comment by birdsarah** [comment]
@jobini - can you try taking the same data and sticking it into an actual pandas data frame. Charts is designed to work specifically with pandas dataframes, my guess is that there's a mismatch between the blaze and pandas dataframe apis.

**Comment by necaris** [comment]
@jobini Thanks for clarifying! I think I see where the confusion is coming from. In order to actually *fetch* the data from the Blaze expression, you need to `compute` it -- otherwise a Blaze expression simply represents operations needed to get data, rather than the data itself. To address @birdsarah's point about ensuring it is in a Pandas DataFrame, I would suggest this to create your plot:
```python
data = blaze.compute(df, return_type='core')  # return_type ensures a DataFrame
p = Bar(data, "overall", values="wordcount", title="Bar Plot")
```

**Comment by birdsarah** [comment]
Thanks for the blaze info @necaris - you learn something new every day!

**Comment by jobini** [comment]
@necaris, @birdsarah : Thank you for helping me out! I couldn't actually load the data into a Pandas DataFrame owing to its size (> 20GB) being greater than my system RAM. I was hoping that Blaze would function as an iterator of sorts and "stream" the data into bokeh. But I did learn something new today, thank you!

**Comment by necaris** [comment]
@jobini Unfortunately, there's no unified API for the result of `blaze.compute` yet (hence the use of the `return_type` argument) -- and it's not yet supported by Bokeh either. If you'd like to help make either of those happen, though, you'd be very welcome!

**Comment by bryevdv** [comment]
Seems like this has been sorted out
