### ISSUE TITLE
Allow elements to be placed in server templates

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#4986]
In https://github.com/dask/distributed/pull/434 I want to add a button to a bokeh server application that uses the `stretch_both` sizing scheme.  Putting the button in the normal layout causes some dead space due to the current 50/50 split scheme.  A workaround would be to place the button into the template.  

@birdsarah suggests that while this is possible normally, it's not yet possible for server templating.

**Comment by birdsarah** [comment]
We want something like components.

Possible related is that components doesn't work with Theme because it doesn't really mesh well with a document at the moment. #4952.

**Comment by bryevdv** [comment]
Unfortunately this will not make `0.12.6`
