### ISSUE TITLE
Problem with 'Run all' in Jupyter notebooks with bokeh 0.12.1

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#4987]
I can't seem to get 'Run all' to work with Bokeh in my Jupyter 4.1.0 notebooks for Bokeh 0.12.1 (seemed fine in 0.12.0):

![image](https://cloud.githubusercontent.com/assets/1695496/17791331/3c94cafc-6560-11e6-8dde-716bf3c4eb5d.png)

Any ideas?

**Comment by jbednar** [comment]
Code:

```
from bokeh.plotting import figure, output_notebook, show
from bokeh.resources import INLINE
output_notebook(resources=INLINE)
```

```
p = figure()
```

```
show(p)
```

**Comment by jbednar** [comment]
I made it use inline resources only because of the message it showed; it works the same without inline resources.

![image](https://cloud.githubusercontent.com/assets/1695496/17791475/fc46aba4-6560-11e6-98bf-3930c4ba5d4b.png)

**Comment by jbednar** [comment]
Nor is it important that show() is on its own line:

![image](https://cloud.githubusercontent.com/assets/1695496/17791540/4b4cd0de-6561-11e6-9de3-b4f9256d2cab.png)

**Comment by jbednar** [comment]
But it does work fine in bokeh 0.12.0:

![image](https://cloud.githubusercontent.com/assets/1695496/17791626/be239ade-6561-11e6-9157-6b24bd0fb4a4.png)
![image](https://cloud.githubusercontent.com/assets/1695496/17791635/c943f1a2-6561-11e6-8c61-0537a67de7f7.png)

**Comment by philippjfr** [comment]
It comes down to this bit of Javascript not executing in time:

```javascript
Bokeh.$("#%s").text("BokehJS successfully loaded");
var kernel = Jupyter.notebook.kernel
if (kernel.execute !== undefined) {
    kernel.execute("import bokeh.io; bokeh.io._nb_loaded = True");
}
```

When you hit ``Run all`` in the notebook a bunch the cells are queued on the kernel, so asynchronous execution will determine whether the ``Run All`` events or the explicit kernel.execute event is queued first. I don't really see any way around this except for removing the warning.

**Comment by jbednar** [comment]
Thanks!  Seems to work fine if I turn off the checking:

![image](https://cloud.githubusercontent.com/assets/1695496/17794342/25fa2c56-6574-11e6-9265-fdf457e1209a.png)

**Comment by bryevdv** [comment]
Suggest: make it optional (but default to ON), add a comment to the warning to explain how to turn it off for "run all" usage.

**Comment by jbednar** [comment]
That would help for now, especially if the way to turn it off is less distracting than what's currently required. Perhaps ``output_notebook(check=False)``?

**Comment by birdsarah** [comment]
This problem is also affecting us in our notebook tests e.g. https://s3.amazonaws.com/bokeh-travis/153752655/examples.html

`output_notebook(check=False)` sounds good to me.

**Comment by sushmit86** [comment]
from bokeh.resources import INLINE
output_notebook(resources=INLINE) does not seem to work

**Comment by bryevdv** [comment]
@sushmit86 Yes, the problem is specific to "Run All" and independent of the type of resources used.

**Comment by jbednar** [comment]
I can verify that with the latest dev build 0.12.2dev8-py_1 that includes PR #5014, the various datashader notebooks that I tested all work properly with Run All.  Thanks, @bryevdv and @philippjfr!
