### ISSUE TITLE
Warn on ragged length values in ColumnDataSource

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#5000]
Bokeh assumes that the values of a ColumnDataSource are all of the same length.  However users are able to break this contract easily and without being informed.
### Example

``` python
intended_data = {'a': [], 'b': [], 'c': []}

source = ColumnDataSource(intended_data)

actual_data = {'a': [1, 2, 3], 'b': [4, 5, 6]}
source.data.update(actual_data)
```

This may silently result in a client-side plot receiving no data, because the length of the shortest value is zero.  

Instead, it might be nice to raise a warning or exception to inform the user that they have uneven rows.  This might happen on the `update` call, when the data is packaged to be sent up to the client, or on the client side.

**Comment by bryevdv** [comment]
Suggest a specialized `PropertyValueDict` for CDS that can performs the checks that are appropriate and specific to CDS usage. 

https://github.com/bokeh/bokeh/blob/master/bokeh/core/property_containers.py#L122
