### ISSUE TITLE
Saving an image on retina screen saves at wrong resolution/size

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5009]
Here's what the image looks like on screen:

<img width="1038" alt="screen shot 2016-08-22 at 3 26 00 pm" src="https://cloud.githubusercontent.com/assets/1796208/17873831/bee8ebfe-687c-11e6-8558-1898bd4e6af4.png">

Here's the saved image:
![bokeh_plot-1](https://cloud.githubusercontent.com/assets/1796208/17873841/c858303c-687c-11e6-803a-4ed444092bd1.png)

It doesn't look so bad in the github window because the image has been scaled down, but opening it up natively looks bad - it's twice the size it should be.

**Comment by birdsarah** [comment]
ping @almarklein - I think of you as the hidpi guy - any thoughts on how to modify the save code to make this work: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/actions/save_tool.coffee#L16

**Comment by bryevdv** [comment]
Unfortunately changing this is probably not trivial. Look at the tool:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/actions/save_tool.coffee#L11-L19

We basically just make a URL to present what the browser pulls out of the canvas. But I don't think those blobs and image urls can be accessed / edited. The only solution I can think of is to make a one quarter size hidden canvas element, and re-render everything into it, then use that as the source the tool grabs data from. I had at one point wanted to to that anyway, to make the output image size configurable by the user.

**Comment by almarklein** [comment]
> The only solution I can think of is to make a one quarter size hidden canvas element, and re-render everything into it,

That would be my take as well. Tough make the size dependent on the hdpi ratio, or even make it configurable as you said.

**Comment by bryevdv** [comment]
Given that there are now export PNG and SVG functions I don't see justifying adding a lot of complexity to service the toolbar save tool. If users do use that and the image is larger or different than they want there are any number of ways to rescale them
