### ISSUE TITLE
Discrete/Categorical ColorMapper and ColorBar

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5013]
Add a CategoricalColorMapper that accepts palette and factors

```python
color_mapper = CategoricalColorMapper(
   palette=Spectral3,
   factors=["cat", "dog", "milk"],
)
```

@canavandl - we'd want color bar to use a CategoricalAxis and I'm not sure we could use image - maybe we could though. It's very similar to low-n palettes.

@bryevdv - `nan_color`, `high_color`, `low_color`. high/low don't make sense but out_of_range does. Which I see as different from No Data. Thoughts on naming.

**Comment by bryevdv** [comment]
we can punt on this for now right? It doesn't block the linear color mapper case? Offhand, maybe `extra_color` or something.

**Comment by birdsarah** [comment]
ping @hafen

**Comment by birdsarah** [comment]
Just trying to think through the API as it relates to LinearColorMapper @bryevdv.

**Comment by hafen** [comment]
Sorry I missed this.  It looks like there's still something I need to fix with my github notifications - I stumbled upon it while looking at the new color mapper feature.  I'm glad this looks like it will make it into 0.12.3.  I've been looking at https://github.com/bokeh/bokeh/pull/5091 and I think this looks great.  I was going to mention that having a categorical color mapper would have implications on being fed to a legend to create a legend automatically just like the linear color mapper appears to do for the color bar in 0.12.2.  I wonder how the categorical color mapper and its corresponding legend will be able to work together with potentially other glyphs being added for which additional custom legend entries might need to be added.

**Comment by birdsarah** [comment]
> I wonder how the categorical color mapper and its corresponding legend will be able to work together with potentially other glyphs being added for which additional custom legend entries might need to be added

Should work just fine. It's just a list of items and as many things as necessary can be added.
