### ISSUE TITLE
CustomJSTransform

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5015]
Adding new transforms is easy, but people should be able to self serve something like this:

``` python
from bokeh.models import CustomJSTransform

transform = CustomJSTransform.from_coffeescript(
    compute="""return 2*x""",
    v_compute="""
        vals = []
        for x in xs:
            vals.push(2*x)
        return vals
    """
)

.....

p.circle(x='x', y='y', size={field: 'x', transform: transform})
```

Just like https://github.com/bokeh/bokeh/pull/4659, user would _know_ that single `x` is passed to compute and array `xs` is passed to v_compute. User would specify a return value and would also be able to pass in args - like for CustomJS.

**Comment by birdsarah** [comment]
ping @hafen

**Comment by bryevdv** [comment]
This seems low-effort / high value so scheduling it for `0.12.5`

**Comment by souravsingh** [comment]
I am interested in working on the issue. How do I start?

**Comment by bryevdv** [comment]
HI @souravsingh it's going to be very similar to the `CustomJS` callback. I'd first suggest studying that, and it's JS implementation as well:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/callbacks.py
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/callbacks/customjs.coffee

It's probably the case that alot of that code can be re-used. 

Then the first step would be to define what the python class that will represent a `CustomJSTransform` should look like. It will be a subclass of `Transform` with some extra properties to represent the JS code for the transform.

**Comment by datnamer** [comment]
Can we do this with pyscript also?
