### ISSUE TITLE
Render js_raw before js_files

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5021]
I had a situation where I had custom models with external resources.

I wanted to use bokeh with `resources=local` but because in the template for bokeh_js - https://github.com/bokeh/bokeh/blob/master/bokeh/core/_templates/js_resources.html - files are rendered before raw, my document didn't load because I need bokeh loaded first.

I can't see any harm in switching the order.

**Comment by bryevdv** [comment]
@birdsarah should this be closed too?

**Comment by birdsarah** [comment]
No, I want to describe the issue better and we can see if its solvable.

**Comment by bryevdv** [comment]
I didn't notice the `resources=local` before, this seems very specialized. There have not been any other reports or requests in two years, and there is no reproducer available, so I am going to close this with no action.
