### ISSUE TITLE
bokehjs/test/size.coffee may test wrong files

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5027]
`gulp test` compiles files on-the-fly, so `bokeh.min.js` and other files are not rebuilt. This can lead to meaningless test results, especially when run locally. This doesn't affect travis ci, because we build and test in order, so everything is coincidentally OK.

**Comment by mattpap** [comment]
There is no easy way to implement this to the full extent and I don't want to maintain my own proper JS build system. We could just monitor our sources for changes, but really we have to include node_modules as well.

**Comment by bryevdv** [comment]
I'm perfectly happy to just have TravisCI failures be the signal that limits have been exceeded.
