### ISSUE TITLE
Rendered notebooks not working on nbviewer

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5040]
Just uploaded a rendered notebook to nbviewer and the plots aren't showing:

http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/Can%27t%20view%20on%20nbviewer.ipynb

console log says

```
ReferenceError: Jupyter is not defined
```

**Comment by bryevdv** [comment]
This is a duplicate of the issue Phillip is working on, it's fixed in his pr

**Comment by birdsarah** [comment]
Confirmed - I just tested it.

**Comment by canavandl** [comment]
completed in #5014
