### ISSUE TITLE
Charts defaults documentation seems circular

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5041]
http://bokeh.pydata.org/en/latest/docs/reference/charts.html#chart-options links to http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#userguide-charts-defaults which seems to link back to the first link - it's actually a link to the page but it's not clear.

**Comment by patricktokeeffe** [comment]
Yes, the `bokeh.charts.defaults` docs are circular. There doesn't seem to be an easy way to list the defaults either.

```
>>> from bokeh.charts import defaults; dir(defaults)
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'apply']
```

**Comment by rshin** [comment]
You can see a list of attributes from the 0.10 documentation: http://bokeh.pydata.org/en/0.10.0/docs/user_guide/charts.html#chart-defaults

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/46)
