### ISSUE TITLE
Webgl problem in stream app with multiple glyphs

### ISSUE THREAD

**Issue by xdliao** [bokeh/bokeh#5046]
The plot is regenerated all the time with the wrong scales 
when webgl is enabled and there are multiple glyphs depending on the same data source. 

Here is the summary:
- `webgl=False`, works for both single glpyh and multiple glyphs
- `webgl=True`, works only for single glyph
# Sample Code (based on stream.py)

```
#stream.py
from math import cos, sin

from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

#this is the data source we will stream to
source = ColumnDataSource(data=dict(x=[1], y=[0]))

#Enable webgl=True cause problem with the plot when we update both circle and line
p = figure(x_range=(-1.1, 1.1), y_range=(-1.1, 1.1), webgl=True)
p.circle(x=0, y=0, radius=1, fill_color=None, line_width=2)

p.circle(x='x', y='y', size=12, fill_color='white', source=source)
#!!!! No problem with webgl if we only plot circle, adding this will cause problem !!!!!
p.line(x='x', y='y', line_width=2, source=source) 


def update():
    x, y = source.data['x'][-1], source.data['y'][-1]
    new_data = dict(x=[x*cos(0.1) - y*sin(0.1)], y=[x*sin(0.1) + y*cos(0.1)])
    source.stream(new_data, rollover=8)

curdoc().add_periodic_callback(update, 200)
curdoc().add_root(p)


```

**Comment by bryevdv** [comment]
Can confirm on `0.12.2dev8`

<img width="650" alt="screen shot 2016-08-29 at 1 29 08 pm" src="https://cloud.githubusercontent.com/assets/1078448/18062457/96ed5e12-6dec-11e6-862f-dbcb6aaf721e.png">

With console output

<img width="671" alt="screen shot 2016-08-29 at 1 27 29 pm" src="https://cloud.githubusercontent.com/assets/1078448/18062438/8110732c-6dec-11e6-9790-5ef1c9e68a18.png">

**Comment by bryevdv** [comment]
ping @almarklein any thoughts?

**Comment by almarklein** [comment]
Not sure from the top of my head. I'd need to look into it.

**Comment by cbaus** [comment]
I have the same problem when drawing just a *single* line plot to a figure:
```
f = Figure(webgl=True)
l = f.line('time', 'y', color='black', source=source1)
def update_fig():
    ...
    source1.stream(dict(time=time, y=y))
doc.add_periodic_callback(update_fig, 50)
```

Are there any news regarding this? Cheers.

**Comment by bryevdv** [comment]
Well, good news/bad news, as of `0.12.6`lead up, the layout corruption is no longer an issue but it seems as though any streaming with webgl is not working (with the errors shown above)

**Comment by bc** [comment]
@bryevdv is webgl now compatible with streaming? Do you know of any examples? thanks

**Comment by bryevdv** [comment]
@bc does not appear to be working. Unfortunately the person who developed the initial webgl implementation is no longer contributing. So either 

* a very experienced webgl dev will have to step up, become a new contributor, and take ownership of webgl in Bokeh, or (more likely I guess) 
* one of the existing core devs, none of whom have any webgl experience, will have to learn from scratch and rebuild things from the ground up in a way that makes sense to them. That will likely take a very long time

**Comment by bc** [comment]
Ah I see. thanks for the speedy response @bryevdv
I will continue to work through some examples and try to improve performance through data vectorization with the base-bokeh

**Comment by mattpap** [comment]
Still an issue with the new backend implementation:
![image](https://user-images.githubusercontent.com/27475/134009109-cc9d2693-3306-40c3-9182-c595bdc1f4c2.png)

**Comment by ianthomas23** [comment]
Assigning myself.

**Comment by mattpap** [comment]
Just to note, this is purely a streaming issue, and if `update()` is changed to "manual" streaming (by just updating `source.data`) everything work as expected.

**Comment by ianthomas23** [comment]
This was fixed by #11686.
![screenshot](https://user-images.githubusercontent.com/580326/135272357-a892a4ef-47da-42e9-b560-726bb4fe3018.png)

**Comment by mattpap** [comment]
@ianthomas23, adding a regression test to bokehjs would be useful, especially as we have hardy an tests in this area.

**Comment by ianthomas23** [comment]
@mattpap Yes, there don't seem to be any streaming integration tests. I could add one with an initial render, then a call to `stream_to_column` with a rollover, then a rerender and image comparison. For all 3 backends.

**Comment by ianthomas23** [comment]
> I suppose you should use `ColumnDataSource.stream()` method.

Thanks, I will take a look at that.

> However, in any case, make sure that your tests fail without the fix.

Of course!
