### ISSUE TITLE
Feature request: add wheel pan tool

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5052]
Example Motivation:

When interacting with a time series plot, a user would like to pan through different time eras. This tool would be limited to a single dimension.

Why not WheelZoomTool?

I can imagine wanting to have a specific view window size (say 5 years) and want to explore my data with that specific aspect ratio.

Why not PanTool?

If the data range is much larger than the desired window (say there's 100 years of data but the visualization only "makes sense" when viewed in a 5 year view window, that'd be 20+ click-and-drag pans versus a smoother scrolling interaction.

**Comment by canavandl** [comment]
ping @jbednar

**Comment by jbednar** [comment]
Looks great, thanks!
