### ISSUE TITLE
Create nightly job to run all examples on all supported browsers

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5058]
Recent bug #5056 picked up the fairly subtle fact that map isn't supported on TypedArrays in Safari.

Given that there is now the option for cron travis jobs, we could create a nightly job that runs the examples on a set of browsers that we say we support.

**Comment by bryevdv** [comment]
We currently run all examples on FF and Chrome on windows/linux/osx on every push. I think that will do for now.

**Comment by bryevdv** [comment]
We also run JS unit tests in real browsers now, I'd actually at this point be most interested in running those on different browsers on different plats, on every push.

**Comment by birdsarah** [comment]
I *think* you could narrow this to just test the different JS engines. That is: v8 (chrome, chromium, edge, brave), gecko (firefox), webkit (safari). Off the top of my head I don't know what different mobile platforms are.

**Comment by bryevdv** [comment]
I've made a new separate issue re: unit tests. Maybe some day we can re-visit examples in more browsers but for now unit-tests are a more tractable problem.
