### ISSUE TITLE
Task: Refactor select tools

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5065]
For the select tools there are several issues necessitating a group refactor:
- [x] refactor duplicated `_save_geometry` view method out into parent `SelectTool` class
- [x] refactor duplicated `_emit_callback` view method out into parent `SelectTool` class
- [x] refactor `computed_renderers` from computed property to model method
- [x] cb_data (selection geometry) object is inconsistent across select tools
- [x] PolySelectTool lacks callback
- [x] solve inconsistency on `OpenURL` vs `CustomJS` callback handling
- [x] Add tests

**Comment by respatialized** [comment]
If this refactor also changes the fact that you can't access the geometry of a PolySelectTool, it would be very helpful. The ability to access the geometry of a PolySelectTool selection would allow for much more precise drawing of boundaries than using LassoSelectTool or BoxSelectTool. Is this still in the feature queue?

**Comment by canavandl** [comment]
I believe all of these improvements have been addressed in #6644 and #6693
