### ISSUE TITLE
Formatting dates documentation improvements

### ISSUE THREAD

**Issue by cenveoanalyst** [bokeh/bokeh#5070]
@bryevdv  requested that I formally open this to spur discussion of improvements for documentation improvements  to [the datetime formatter docs](http://bokeh.pydata.org/en/latest/docs/reference/models/formatters.html#bokeh.models.formatters.DatetimeTickFormatter
). 

The documentation seems to imply that one can do dict(time_value =["format"]) just for the specific value one wants to format. This worked <0.12.1 but is broken >0.12.1.. Per @bryevdv's clarification in Gitter, to set a specific date time format one can do something like:

```my_formats = DEFAULT_DATETIME_FORMATS()
my_formats.update(days=["%a,   %b %d"])
DatetimeTickFormatter(formats=my_formats)```

This achieves the desired result.

The issue tracker isn't the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).

For defects or deficiencies, please provide:
* Description of expected behavior and the observed behavior
* Self-contained example code that generates the issue (if possible)
* Stack traceback and/or browser developer tools console output
* Software version information output by `bokeh info` command

For desired features, please provide:
* Description of the desired feature

**Comment by bryevdv** [comment]
So we actually ended up going a different direction, and made individual field for all the scales, which is much easier to use, so the "default dict" is no longer needed. It's around for a while during a deprecation,but I'm closing this as invalid.

**Comment by cenveoanalyst** [comment]
@bryevdv , what's the new API for doing this? Will this make the switch over in 1.0?

**Comment by bryevdv** [comment]
The new api is that every key in the old dict, e.g. `"minces"` is now just a property `.minsec` on the formatter. The new api is available in `0.12.3` out in the next few days, but the old dict still works with a deprecation warning.

**Comment by bryevdv** [comment]
See the dev docs: http://bokeh.pydata.org/en/dev/docs/reference/models/formatters.html#bokeh.models.formatters.DatetimeTickFormatter

**Comment by jetychill** [comment]
Hey guys does anybody else have trouble when using Jinja2 Templating with the hovertool date formatting feature, it seem that the jinja engine is picking up the '@Date{%Y}' as logic for the jinja template itself any workarounds for this ?
