### ISSUE TITLE
New hover features

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5073]
- [ ] Add ability to style hover via python
- [x] Add ability to turn off pointer/arrow
- [ ] clean-up code around "custom" tooltips as it now has no impact on styling
- [ ] Add ability to customize the hit radius

**Comment by mattpap** [comment]
> Add ability to turn off pointer/arrow

This was done in #4907.

**Comment by birdsarah** [comment]
> This was done in #4907.

SCORE! 🎁

**Comment by bryevdv** [comment]
The hit radius task is a dupe of #2230 The other tasks I think we can just pass on
