### ISSUE TITLE
Legend from matplotlib does not appear with to_bokeh()

### ISSUE THREAD

**Issue by arendu** [bokeh/bokeh#5094]
When matplotlib's legend does not appear in the html plot when using to_bokeh().
Here is a code sample:
```
import matplotlib.pyplot as plt
from bokeh.plotting import figure, show, output_file, save
from bokeh.mpl import to_bokeh

if __name__ == '__main__':
    legend = ['x^2', '2x'] 
    fig = plt.figure()
    ax = fig.add_subplot(111)
    plt.plot(range(10), [x*x for x in range(10)], '-o')
    plt.plot(range(10), [2*x for x in range(10)], '-o')
    plt.legend(legend, loc='upper left')
    plt.show()
    bk = to_bokeh(fig)
    show(bk)

```

**Comment by bryevdv** [comment]
Current MPL compat relies on an incomplete and experimental third-party library that is no longer actively maintained. It is provided "as-is" only in the event that it is useful in some subset of use-cases, and with the explicit understanding that it is not complete. Any further work on MPL compat for Bokeh is waiting for the upstream implementation of a well-defined MPL JSON serialization protocol. We unfortunateluy cannot devote any extremely limited resources until this upstream foundation is available to build upon. 

If you are seeking to use Bokeh for its interactivity in the browser, etc. it is always recommended to directly use native Bokeh plotting interfaces such as `bokeh.plotting` in any case.
