### ISSUE TITLE
Colorbar feature requests

### ISSUE THREAD

**Issue by physinet** [bokeh/bokeh#5095]
I'm liking the recent work on ColorBars; they're looking great! Here are a couple of features I've thought of while playing around with them.
1. **Title positioning**: I would love to have a colorbar title on the side of the colorbar, rotated 90 degrees. Helpful if you want to have a long colorbar title.
2. **Interactions for ColorBar**: It would be cool to have tools that interact with the ColorBar in some way, either pan/zoom tools that let you shift and zoom the color range, or sliders that let you set the top and bottom limits of the color range. I've written a quick function that changes `color_mapper.low` and `.high` and then pushes the changes to the notebook, so that will hold me over for now.

**Comment by birdsarah** [comment]
These are nice feature suggestions. The title wouldn't be that hard although would be some work - both in terms of api planning and code. 

The interactions I think would be more complex, although I believe @mattpap was working on interactive legends at some point, which I think might overlap / mesh with this.

**Comment by bryevdv** [comment]
Ideally it would be nice if `Plots` could be positioned arbitrarily in other plots, then `ColorBar` could just be a special particular kind of `Plot` and get all the title functionality, etc stuff for free.

**Comment by physinet** [comment]
I'm managed to throw together something [here](http://nbviewer.jupyter.org/github/physinet/bokeh-colorbar/blob/master/Colorbar%20slider%20example.ipynb) that works well enough for me. It's probably not too useful for making headway into developing these features for real, but it demonstrates the basic interactions I had in mind. The sliders do weird things at the moment to avoid upper limit > lower limit, and I haven't bothered to get them to do more sensical things to fix this. And the JS callbacks are particularly poorly written; I'm pretty sure there's some code in there that doesn't actually do anything useful.

**Comment by bryevdv** [comment]
I don't think interactions on the colorbar will be forthcoming. There is a separate issue #7093 around colorbar titles so I will close this as a dupe.
