### ISSUE TITLE
Desired feature - ResetTool callback

### ISSUE THREAD

**Issue by nickb-402** [bokeh/bokeh#5098]
Please add callback feature to the ResetTool, so CustomJS callbacks may be used when pressing the Reset button on a figure.

**Comment by bryevdv** [comment]
FWIW This could definitely be accomplished with a custom extension that subclasses the current reset tool.

**Comment by ivan-usov** [comment]
Wasn't it fixed in #6877 ?

**Comment by bryevdv** [comment]
Yes thanks for the catch @ivan-usov marking as a dupe
