### ISSUE TITLE
Create conda package for most recent node.js

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5105]
This is continuation of PR #4946. At this point this isn't strictly necessary, but it would be nice to have a most recent version. Consider either 4.4.x LTS or 6.x. Do not use 5.x.

**Comment by mattpap** [comment]
@bokeh/dev, what's the appropriate channel of communication for this? It shouldn't be us creating packages, as it is very resource inefficient.

**Comment by damianavila** [comment]
I guess you can contact the anaconda team about it and ask for help. Pinging @csoja

**Comment by csoja** [comment]
which version of nodejs do you need? 4.4.7?

**Comment by mattpap** [comment]
@csoja, yes, 4.4.7 (most recent LTS version) is OK.

**Comment by mingwandroid** [comment]
If anyone can assign this to me that'd be great. I guess it may not be possible as I'm part of the team? Moving it to another project (conda? Anaconda Distribution?) should also allow that.

**Comment by bryevdv** [comment]
@mingwandroid Right, it won't let me assign. Can you make the issue linking to here, on one of those projects you are on and self-assign?

**Comment by canavandl** [comment]
conda-forge has nodejs=4.5.0 (https://anaconda.org/conda-forge/nodejs) and I think we've already have conda-forge as an extra channel in our meta.yaml. does that work for you @mattpap ?

**Comment by mattpap** [comment]
@canavandl, yeah, that works. We have `javascript` channel instead of `conda-forge`.

**Comment by damianavila** [comment]
>@canavandl, yeah, that works. We have javascript channel instead of conda-forge.

I think conda-forge channel was added recently by https://github.com/bokeh/bokeh/commit/be6f820b48baf24eb885f57a02435df7657ed0c7 and https://github.com/bokeh/bokeh/commit/60b177518e6f6ecbbd56389b4dfa19fb6430ce3a#diff-bd134fa847b11c75aba174f834eb80dfR15

**Comment by damianavila** [comment]
> I think conda-forge channel was added recently by be6f820 and 60b1775#diff-bd134fa847b11c75aba174f834eb80dfR15

This is something it should be audited later because of channel precedence we are installing a lot of packages from the conda-forge channel... at leat, that was what I saw when I last checked a travisCI run, but I did not have time to look further...

**Comment by mattpap** [comment]
@damianavila, yes, I was on an slightly older branch when checking this.

So, the only thing left is to remove `javascript` channel. I think we don't use anything from there anymore. Well, we may use `gulp` (I install it using conda), but that's not a requirement bokeh's conda package.

**Comment by canavandl** [comment]
Changing build process to install nodejs=4.4.* from conda-forge, obviating the need to build the package ourselves. 

Closing/marking as reso:upstream
