### ISSUE TITLE
bokeh.pydata.org warns that searching 0.12.1 is old but latest isn't pointing to 0.12.2 yet

### ISSUE THREAD

**Issue by timsnyder** [bokeh/bokeh#5107]
Here's the behavior:
- go to http://bokeh.pydata.org
 - it will redirect to http://bokeh.pydata.org/en/latest  -- at least it does for me, perhaps we have some kind of locale detection so that 'en' isn't what everyone gets?
 - It may be important to note that when I got to http://bokeh.pydata.org/en/latest v0.12.1 was selected as the version in the dropdown 'navigation-menu'
- enter a search in the 'search-bar' class 'input' at the top right of the page
- you get taken to http://bokeh.pydata.org/en/latest/search.html?q= with your encoded query on the end
- even though we're on a 'latest' URL and v0.12.2 is selected now in the 'navigation-menu' the pink background with firebrick text div warning us about viewing old docs is displayed

![image](https://cloud.githubusercontent.com/assets/83846/18312625/4c22d75a-74d0-11e6-830d-8d0c7a72f31b.png)

I think that I might have caught things during a release just at the right time to get really confusing results out of the search box. If the window when this behavior could be observed by users is small, I'm okay with this being marked wontfix and moving on.  However, I'm not positive that this was just unlucky timing and thought I should at least file an issue.  Perhaps there's a bug in whatever injects the pink div into the top of the page results?

**Comment by timsnyder** [comment]
Or perhaps http://bokeh.pydata.org/en/latest thinks latest is v0.12.1 but http://bokeh.pydata.org/en/latest/search.html thinks latest is v0.12.2?  In other words, there is an inconsistant definition of 'latest' somehow in the docs site?

**Comment by bryevdv** [comment]
Hard reload / cache reset will fix.

**Comment by timsnyder** [comment]
yup.  you're right.  

Is there a way that we could cause the caching to be invalidated when a new release is made?  Have others run into this enough to warrant spending any time looking into it?

**Comment by bryevdv** [comment]
I'd love to fix this, and I expect there is maybe even a simple solution, I just don't know offhand what it is. The code that is responsible for the banner is here:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/bokeh_theme/static/js/main.js#L15-L28

Maybe there is an argument to `$.get` or some other method of retrieving `version.txt` from the web server that forces it to always return and not cache?

**Comment by bryevdv** [comment]
Some of this information seems promising: 

http://stackoverflow.com/questions/8841425/how-to-set-cache-false-in-jquery-get-call
