### ISSUE TITLE
Seeking path forward for sharing custom extensions (e.g. sharing LaTeXLabel custom model)

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5108]
With the added support for external resources, we've added a route to generate LaTeX through the KaTeX library. Currently there's a custom model example [here](https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/source_examples/extensions_example_latex.py).

We're not likely to add LaTeX support (via KaTeX) to the core library because it would require adding 175kb (153kb JS + 22kb CSS) of resources and increase the minified library about ~20%, for a feature that only a subset of users need. This situation of wanting features that require external resources that make it unlikely to be merged into the core library is increasingly common in Bokeh (another example is adding Ion slider support).

So we need to find a solution to simplify finding/creating/sharing custom extensions.

I can imagine a sister repository of custom extensions that is downloaded programmatically (similar to how sample data is downloaded) to a `bokeh.ext` directory. Then users would be able to import from there via `from bokeh.ext import LaTeX` or similar.

In terms of doing the above, what would need to be included in the sister repo? A module containing: 
- the custom extension implementation
- a README
- an example file whose output could also be placed in a gallery page somewhere for discoverability?

**Comment by canavandl** [comment]
ping @MaxNoe to continue the discussion started in #647. Would something similar to the proposed system work for your use case? Anything you would add?

**Comment by birdsarah** [comment]
I randomly had a chat with @rgbkrk about `from bokeh.ext import LaTeX` type thing.

They had discussed something similar for Jupyter and decided against it - I may be over simplifying.

Also worth noting that django has a vibrant community of add-ons / plugins / extensions (see https://djangopackages.org/) but does not do this. There is a convention in the community to name your package `django-` e.g. :
* `pip install django-braces` then `from braces.views import LoginRequiredMixin`
* `pip install django-spreadsheetresponsemixin` then `from spreadsheetresponsemixin import SpreadsheetResponseMixin`

**Comment by canavandl** [comment]
Conversely, Pelican (the static site generator) does the monolithic repo of plugins things:

https://github.com/getpelican/pelican-plugins

I'd be curious what @rgbkrk 's reasoning was to go one way or the other.

**Comment by birdsarah** [comment]
I am not a fan of pelican plugin system. This is their installation instruction "The easiest way to install and use these plugins is to clone this repo." Using git should not be required in my opinion.

Second, my preference is for an identical experience between bokeh maintained plugins, like bokeh-geo will be, and community made and shared plugins. 

See the readme for this pelican plugin https://github.com/danielfrg/pelican-ipynb (which the blaze blog uses). Installation instructions: 

## Installation

Download this repo and put all the `.py` files it into an `ipynb` directory
into your `plugins` directory. The structure should look like this:

```
content
plugins
  ipynb
    __init__.py
    core.py
    ipynb.py
    liquid.py
    markup.py
    ... other files are optional ...
```

See specific modes notes for settings in the `pelicanconf.py`:

If you host your site on git (i.e. github pages) you could use it as a submodule:

```
git submodule add git://github.com/danielfrg/pelican-ipynb.git plugins/ipynb
```

**Comment by bryevdv** [comment]
re: "pip install" now everyone who wants to share a plugin has to become a package manager, that raises the bar miles above where I'd like it to be

I don't think users should have to use git directly but the plugin installer can interface with git easily enough behind the scenes. 

I also don't think `bokeh.geo` and community extensions are comparable. Neither in size (`bokeh.geo` will be an entire library) nor in the level of integration (every random plugin can't get a top level `bokeh.foo`)

**Comment by birdsarah** [comment]
I wasn't advocating that you'd have to pip install bokeh extensions. 

I was just trying to highlight another community's approach that works but doesn't try and put things into the main project's namespace.

I guess we should be careful to split out two things:

1) the conveniences / wrappers we can build for users to easily install plugins
2) what the usage looks like

To take a position, for the sake of discussion, trying to put user installable plugins into the bokeh core namespace seems like it will be difficult and unnecessary for ease of use.If a plugin is easy to find and install, then I don't think it matters if you type `from ionRangeSlider import Slider` or `from bokeh.ionRangeSlider import Slider`.

**Comment by bryevdv** [comment]
OK I misconstrued that as an endorsement. 


I don't think `from ionRangeSlider import Slider` works like I'd like, because we are back to people having to package for them to be available. How does `ionRangeSlider` get on your `sys.path`? To be clear, am not at all wed to `bokeh.ext`. Something like
```
FunThing = bokeh.load_extension("fun_thing")
```
would be fine too, if a bit more verbose. I might not have spelled it out, but this is what I have in mind:

* simple directory layout with `README.md`, `__init__.py`, and a conventional `model.py` (or whatever) plus any other associated files. 
* GitHub is a convenient, familiar easy place for people to host this kinds if directories. 
* To "install" extensions, these directories just get copied into `~/.bokeh/extensions` which also has an `__init__.py`
* the Bokeh plugin loading machinery facilitates loading modules from `~/.bokeh/extensions` transparently. There's various different ways this could look. The `bokeh.ext.fun_thing` could be made to work, or an explicit load function, whatever.

**Comment by birdsarah** [comment]
> I don't think `from ionRangeSlider import Slider` works like I'd like, because we are back to people having to package for them to be available. 

I don't think this is true.

> How does ionRangeSlider get on your sys.path?

I think there are a number of ways this could be achieved.......I will try and flesh out a concrete suggestion to spark conversation.

**Comment by rgbkrk** [comment]
One of the main reasons, IIRC, is that there were several slightly incompatible ways to provide namespace packages, pkgutil vs. setuptools, etc. @takluyver would know better from what I recall from the discussion.

**Comment by bryevdv** [comment]
I'm definitely not proposing to use namespace packages, which are a specific, defined thing.

**Comment by bryevdv** [comment]
Code probably speaks better:
```
# ext.py

import sys

class _ExtLoader(object):

    def __init__(self, wrapped):
        self._wrapped = wrapped

    def __getattr__(self, name):
        if hasattr(self._wrapped, name):
            return getattr(self._wrapped, name)
        else:
            if name == "__path__": return "<file>"

            # really, this would look for things in ~/.bokeh/extensions
            if name == "foo": return "FOO"

            raise NameError("unknown thing %s" % name)

sys.modules[__name__] = _ExtLoader(sys.modules[__name__])
```

Then:

```
In [1]: from ext import foo

In [2]: foo
Out[2]: 'FOO'

In [3]: from ext import bar
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-9358abee1bc2> in <module>()
----> 1 from ext import bar

/Users/bryan/anaconda/lib/python3.4/importlib/_bootstrap.py in _handle_fromlist(module, fromlist, import_)

/private/tmp/ext.py in __getattr__(self, name)
     13             if name == "__path__": return "<file>"
     14             if name == "foo": return "FOO"
---> 15             raise NameError("unknown thing %s" % name)
     16
     17 sys.modules[__name__] = _ExtLoader(sys.modules[__name__])

NameError: unknown thing bar
```

**Comment by MaxNoe** [comment]
Please! Do not reinvent the wheel. There is package management for python. It might be improvable. It might not be as convenient as it should be. But users know it and developers know it.

Whats wrong with `pip install bokeh_<name of extension>`. 

The user copying files by hand to some folders is no solution. What is your approach doing if you have multiple (conda/virtualenv) environments, where you want different versions of a plugin?

How would plan on versioning a plugin?

These problems are all solved (maybe not perfectly, but yet solved) when using a proper python package. And writing a `setup.py` file for a single-file module is not complicated and can probably copy pasted in 99.9% of the cases from some prototype bokeh extension.

**Comment by bryevdv** [comment]
> Whats wrong with pip install bokeh_<name of extension>.

Fora start, amongst Bokeh users there are ~3x as many `conda` installs every month than `pip` installs every month (currently 60k/mo vs 20k/mo) so a `pip install`-only solution fails to address the majority of users.

**Comment by takluyver** [comment]
The position we've wound up taking with both IPython and Jupyter is that reinventing package management is not worth any apparent benefits. It looks like you're building something simpler at first, but if it actually gets any significant use, pretty soon you've wound up reinventing package management badly. Unfortunately I don't have time to read and process all of the specific arguments in this thread, but from the outside it doesn't seem like Bokeh is so unusual as to be an exception.

Specific points I saw:

- pip vs conda: AIUI any pip package can trivially be turned into a conda package. I wrote a [wheel2conda](https://github.com/takluyver/wheel2conda) converter for packages with no compiled parts, and the [conda-forge](https://conda-forge.github.io/) guys have a more involved but more powerful way to automate creating conda packages.
- packages from Python vs R (etc.): if you wind up creating a cross-language package manager, that's a big wheel to reinvent.

**Comment by MaxNoe** [comment]
@takluyver I couldn't agree more

**Comment by bryevdv** [comment]
> It looks like you're building something simpler at first, but if it actually gets any significant use, pretty soon you've wound up reinventing package management badly. 

Part of the motivation is to *ensure that it is simpler*. I *never* want extensions to be able to depend on other extensions, for instance. With or without pip or conda, down that road lies madness.

**Comment by bryevdv** [comment]
As it stands anyone can create a pip (or conda) package to define a bokeh custom extension, including pinning to Bokeh version if appropriate. I had grander visions of a searchable plugin system ala VSCode, Sublime, or Atom, but realistically, that's probably not going to happen.
