### ISSUE TITLE
TestApiCrawler.test_get_crawl_dict fails if not run from top-level directory

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5109]
A common pattern is to run py.test from a lower-level directory to only run the tests under active development. This test

https://github.com/bokeh/bokeh/blob/master/bokeh/util/tests/test_api_crawler.py#L29

is written so that it only passes from the top-level. It should be refactored to use relative imports and/or cwd.

**Comment by canavandl** [comment]
ping @brittainhard

**Comment by birdsarah** [comment]
It also means that 

`python -c 'import bokeh; bokeh.test()'`

has stopped working. 

Tangentially - @bryevdv you were very vocal to keeping `bokeh.test()` when we switched to pytest - have you now moved over to running pytest? Can we get rid of `bokeh.test()`  - it's just extra code to maintain.

**Comment by bryevdv** [comment]
This API stuff is going away.
