### ISSUE TITLE
Bokeh npm install

### ISSUE THREAD

**Issue by rgbkrk** [bokeh/bokeh#5125]
I'm trying to load Bokeh in an electron context, which means I'm in node with a browser context. However, the object that `require('bokehjs')` returns has no methods (and isn't itself a function). Was there a packaging issue with the npm release or should I be requiring this differently?

**Comment by bryevdv** [comment]
ping @mattpap do you have any experience / ideas? 

To be honest, I think the npm package gets little to possibly no use at all, so it would not surprise me if there are issues with it. But I'm not sure what would be needed to fix. Basically we build a `bokeh.min.js` that has `Bokeh` object and I think that's what's uploaded.

**Comment by rgbkrk** [comment]
Ah, sure enough. That's sets a global `Bokeh` object.

<img width="742" alt="screen shot 2016-09-08 at 3 55 14 pm" src="https://cloud.githubusercontent.com/assets/836375/18369788/af2e2e6e-75dc-11e6-8697-a6900df2895a.png">

**Comment by rgbkrk** [comment]
Yeah, I'm hoping for a commonjs/ES6 export that could be loaded if used with webpack or browserify.

```
const Bokeh = require('bokehjs');
```

**Comment by rgbkrk** [comment]
I have suggestions for the build output, but I'm not sure what context this is currently used in. This built file looks like a browser dist rather than an npm package.

**Comment by bryevdv** [comment]
If you know how to do that I'm open to suggestion :) @mattpap might knowhow to accomplish this

**Comment by bryevdv** [comment]
We upload the dist to CDN and also ship it with the python library. We don't use the npm package for anything so changing it however seems fair game.

**Comment by mattpap** [comment]
According to #614 this is a solved issue. Anyway, `main` field in `package.json` wrongly points to `build/js/bokeh.js` bundle (this is where global `Bokeh` comes from) (looks like this was added just to shut npm up). Changing this to `build/js/tree/main.js` doesn't work and fails on imports from `vendor`. This should be hopefully easily fixable, because our tests run under node.js. Even with this fixed, `require("bokehjs")` won't bring widgets and plotting APIs to scope automatically. Though they can be imported separately (with some extra code as in `bokehjs/test/common/defaults.coffee`).

**Comment by mattpap** [comment]
We can create a different entry point for npm package, that would include everything (core, widgets, APIs).

**Comment by mattpap** [comment]
If anyone besides me wants to play with this, I couldn't find a way to actually build a npm package, just I can publish one, so I do this:
```
cd ~/tmp
npm install ~/repos/bokeh/bokehjs
```
to test the package. Installing from inside `bokeh/bokehjs` won't work.

**Comment by mattpap** [comment]
> This should be hopefully easily fixable, because our tests run under node.js.

Our tests use a custom module loader, so that's why `vendor` works there. I think we can use the same code in npm package, just at this point we have to have another entry point.

**Comment by mattpap** [comment]
@rgbkrk, @bryevdv, PR #5129 should fix this issue.

**Comment by bryevdv** [comment]
@rgbkrk can you take a look and comment?
