### ISSUE TITLE
Use decimal zoom level for WMTSTileSource

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#5126]
When a Bokeh plot includes both a WMTSTileSource and an another plot of some kind, such as the ImageRGBA plot in this example taken from https://anaconda.org/jbednar/landsat/notebook:

![image](https://cloud.githubusercontent.com/assets/1695496/18366496/82017f9a-75dc-11e6-8bf8-8014e06ec8d7.png)

the plot is very different than it would be had there been no tile source:

![image](https://cloud.githubusercontent.com/assets/1695496/18366409/2bef43ee-75dc-11e6-9443-a85d772928ea.png)

I.e., including the tile source changes both the aspect ratio and the bounding region of the plot (in data coordinates).  Changing the aspect ratio is arguably appropriate, though it would be much nicer just to be able to declare that on the data itself so that it would correctly have square pixels with and without the tile source.  But changing the bounding region is very rude; I want to show the data, not a huge area of tiles with my data in one tiny bit!

According to @brendancol, what's happening is that the tile source is forcing the display to an integer zoom level at the start, which is how some tile sources usually work online (not being able to re-render to levels in between).  But that doesn't seem appropriate here, because the wheel zoom and box zoom tools allow users to select arbitrary zoom levels.  So, can we please remove the snapping to an integer zoom level, at least by default, so that the explicitly requested bounding box in data coordinates can be respected?  

@brendancol suggests that it would not be difficult to snap to some specified number of decimal points instead of integer zoom levels, which would at least help alleviate the issue, though it wouldn't solve it for all possible bounding boxes.

The biggest practical problem with the current approach is that when notebooks are rendered by anaconda.org, they use the initial extent only, regardless of whether one has subsequently zoomed in, and so there's no way to upload notebooks that show the actual data; currently they only show this vast area of uninformative tile data.

It would also be nice to allow the requirement for a square aspect ratio to be expressed at the ImageRGBA or Scatter levels, so that geographic data will never get squashed whether or not there are underlying tiles, but that's not quite as urgent to fix.

**Comment by jbednar** [comment]
@brendancol, any hope this can be addressed soon?  I keep having to work around it when posting static notebooks to anaconda.org, by choosing very precise plot sizes that default to a reasonable zoom level, which is not something I want anyone to have to keep doing!

**Comment by bryevdv** [comment]
ping @brendancol any comments on this?

**Comment by bryevdv** [comment]
`match_aspect` is implemented, and the remaining discussion can be covered in the more recent #7006
