### ISSUE TITLE
Provide a helper method to move layout items

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5142]
Legends, for example, get auto-generated but put in the center list of renderers. If we want them off canvas we have to manually add them using `p.add_layout()`.

Propose adding a p.move_layout function that accepts a layout object and moves it to the requested panel. Throws an error if the object is not already in the list of renderers.

This isn't tested code, just an initial sketch:

``` python
def move_layout(self, obj, place):
        valid_places = ['left', 'right', 'above', 'below', 'center']
        if place not in valid_places:
            raise ValueError(
                "Invalid place '%s' specified. Valid place values are: %s" % (place, nice_join(valid_places))
            )
        if obj not in self.renderers:
            raise ValueError("object to be moved not yet in plot renderers")

        # Remove from current place
        for side in ['left', 'right', 'above', 'below']:
            side_renderers = getattr(self, side)
            if obj in side_renderers:
                  side_renderers.remove(obj)

        # Add to new place
        if place is not 'center':
             getattr(self, place).append(obj)
```

**Comment by mattpap** [comment]
I think this isn't needed anymore, because layoutable renderers are only added to side and center panels, but not to renderers. They are handled as renderers internally by plot views. So moving things around is a simple remove and insert from/to side and center panels.
