### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by Misfittech** [bokeh/bokeh#5143]
I can not place widgets on tabs in 0.12

```
from bokeh.models.widgets import Panel, Tabs,Toggle
from bokeh.io import output_file, output_server, show
from bokeh.plotting import figure

output_server("test")

startButton = Toggle(label="Start Test1",  button_type="success")
tab1 = Panel(child=startButton, title="circle")

startButton2 = Toggle(label="Start Test2",  button_type="success")
tab2 = Panel(child=startButton2, title="line")

tabs = Tabs(tabs=[ tab1, tab2 ])

show(tabs)
```

**Comment by TonyPlaysGuitar** [comment]
Yup, doesn't seem to work without at least one figure object...

If you really need only the widgets in tabs, I guess you could add a tiny empty figure:
````python
from bokeh.layouts import widgetbox, row 

startButton = Toggle(label="Start Test1", button_type="success")
startButton2 = Toggle(label="Start Test2", button_type="success")
startButton3 = Toggle(label="Start Test3", button_type="success")

p=figure(plot_width=1,plot_height=1)
p.toolbar_location = None

tab1 = Panel(child=row(startButton,p), title="Start button")
tab2 = Panel(child=widgetbox(startButton2,startButton3), title="More Start buttons")

tabs = Tabs(tabs=[ tab1, tab2 ])

show(tabs)
```

**Comment by bryevdv** [comment]
Interesting how different people converge on similar orthe problems at the same time. I ran into an issue with a completely empty pane locking up the browser recently. I'm not sure it's entirely the same issue, but I expect it is related to the layout computation. Ping @birdsarah any quick thoughts?

**Comment by birdsarah** [comment]
My quick thought is that it has to do with `children` (which was previously a concept on Tabs but not in Bokeh) and `get_layoutable_children` (a new concept added for layout) not being properly hooked up.

**Comment by birdsarah** [comment]
There's no reason for it not to work. It just needs some love and got unloved in the layout chaos.

**Comment by bryevdv** [comment]
I think work to fix this would also fix #5466 (so I marked it `dupe`) but that should be verified on any PR for this issue.

**Comment by azjps** [comment]
Was on the verge of submitting a new issue when I stumbled across the comment

> completely empty pane locking up the browser

Quite frustrating to debug since even the console and inspection windows freeze. Here's the example I coded up for the issue I was about to submit, in case of its any help for debugging:

```python
from bokeh.layouts import layout, column
from bokeh.plotting import curdoc, figure
from bokeh.models.widgets import Button, Panel, Tabs

curdoc().add_root(
  column(children=[
    Button(label="button"),  # just to show that nothing is clickable
    Tabs(tabs=[
      Panel(child=layout(  # [[Button(label="button2")]]  # <- if uncommented should work fine
                        ),
            title="tab",
           ), 
      Panel(child=figure(),  # including an empty figure so tabs show, due to #5143, #5466
            title="fig",
           ), 
      ]), 
    ])) 
```

**Comment by bryevdv** [comment]
I think this is fixed as of `0.12.6dev7` ? With this updated code:
```
from bokeh.layouts import layout, column
from bokeh.plotting import curdoc, figure
from bokeh.models.widgets import Button, Panel, Tabs, Toggle

from bokeh.layouts import widgetbox, row

startButton = Toggle(label="Start Test1", button_type="success")
startButton2 = Toggle(label="Start Test2", button_type="success")
startButton3 = Toggle(label="Start Test3", button_type="success")

p=figure(plot_width=1,plot_height=1)
p.toolbar_location = None

tab1 = Panel(child=row(startButton,p), title="Start button")
tab2 = Panel(child=widgetbox(startButton2,startButton3), title="More Start buttons")

tabs = Tabs(tabs=[ tab1, tab2 ])

curdoc().add_root(tabs)
```

I am getting this which seems to be correct?

<img width="459" alt="screen shot 2017-05-31 at 19 53 10" src="https://cloud.githubusercontent.com/assets/1078448/26660026/cf47a5d4-463a-11e7-9dbd-6a3f7671e41a.png">
<img width="431" alt="screen shot 2017-05-31 at 19 53 15" src="https://cloud.githubusercontent.com/assets/1078448/26660025/cf4628c6-463a-11e7-82d9-24d128b9f04a.png">

**Comment by bryevdv** [comment]
@Misfittech @TonyPlaysGuitar @azjps if you have the chance to test with `0.12.6dev7` (or later) and confirm that this is resolved it would be appreciated. '

cc @mattpap

**Comment by bryevdv** [comment]
@mattpap I was about to close this since the first two example codes in this issue look good:

<img width="350" alt="screen shot 2019-02-02 at 13 01 59" src="https://user-images.githubusercontent.com/1078448/52169332-24517900-26eb-11e9-96d7-4747c0898cbb.png">


<img width="355" alt="screen shot 2019-02-02 at 13 02 54" src="https://user-images.githubusercontent.com/1078448/52169334-2582a600-26eb-11e9-933f-6397d8f56ca9.png">

However, *my* example script above actually looks worse:

<img width="538" alt="screen shot 2019-02-02 at 13 05 19" src="https://user-images.githubusercontent.com/1078448/52169336-3501ef00-26eb-11e9-9ef7-df853c6eabcf.png">

That is *with* an "empty figure", if I delete the empty figure then things look good:

<img width="356" alt="screen shot 2019-02-02 at 13 06 47" src="https://user-images.githubusercontent.com/1078448/52169347-6a0e4180-26eb-11e9-99dc-214d3d6e385e.png">

<img width="350" alt="screen shot 2019-02-02 at 13 06 50" src="https://user-images.githubusercontent.com/1078448/52169348-6bd80500-26eb-11e9-9e45-9e7b008e400b.png">

I guess that is an improvement, since an empty figure should not be needed but still possibly worth investigating.

**Comment by bryevdv** [comment]
Oh, I just noticed my empty figure has width=1 and height=1 With more realisitic values, things look good:

<img width="334" alt="screen shot 2019-02-02 at 13 08 53" src="https://user-images.githubusercontent.com/1078448/52169365-b6f21800-26eb-11e9-86f1-01f21f4f3c17.png">

So the situation seems to be that real-world usage works great, but that the old hack does not.

**Comment by mattpap** [comment]
> Oh, I just noticed my empty figure has width=1 and height=1 With more realisitic values, things look good:

I suspect that there are errors in the JS console when setting width=1 and height=1?

**Comment by bryevdv** [comment]
Yes: 

> Error: invalid bbox {left: 6, top: 0, right: -4, bottom: 0}

I don't think a 1x1 canvas is valid usage so like I said, happy close if you agree

**Comment by mattpap** [comment]
Well, 1x1 canvas is valid if min_border == 0 and there are no side panels. However, in any case, silent failure like this isn't acceptable. For now I've been just throwing this exception whenever there are hard, unsatisfiable constraints, but this can and should be improved. I will hijack this issue to resolve that.
