### ISSUE TITLE
Wrong data shown in Gapminder example app / slider update failing

### ISSUE THREAD

**Issue by deeplook** [bokeh/bokeh#5152]
The Gapminder example app as provided in the latest release (0.12.2) shows the same data for 1964 _and_ 1965 after the slider is moved once from 1964 to 1965. The data shown remains that for 1965, even if the slider is moved back to 1964. Data for other years seem to be shown fine, when moving the slider. This is very easy to reproduce.

**Comment by bryevdv** [comment]
@deeplook there are several different examples based of the gapminder data, can you be more specific about exactly which one you mean?

**Comment by deeplook** [comment]
Ok, this is what I did to make the issue more reproducible right now (on Mac OS X).

``` bash
# Install Miniconda for Python 3.5 on Linux
# wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
# bash Miniconda3-latest-Linux-x86_64.sh -b -f -p ~/mc3

# Install Miniconda for Python 3.5 on Mac OS X
wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
bash Miniconda3-latest-MacOSX-x86_64.sh -b -f -p ~/mc3

~/mc3/bin/conda install -y bokeh==0.12.2
~/mc3/bin/conda install -y pandas # needed by gapminder demo

wget https://github.com/bokeh/bokeh/archive/0.12.2.tar.gz
tar xfz 0.12.2.tar.gz
cd bokeh-0.12.2/examples/app
~/mc3/bin/bokeh serve gapminder

# Then open http://localhost with indicated port (:5006).
# Then move year slider from 1964 to 1965.
# Any further moves between 1964 and 1965 will always show data from 1965
# and no longer from 1964.
```

**Comment by bryevdv** [comment]
@deeplook thanks for the info. Fairly heads down with some other responsibilities this week but will take a look as soon as I can.

**Comment by bryevdv** [comment]
Can confirm this is happening.
