### ISSUE TITLE
Deprecate output_server

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5154]
`output_server` has a number of deficiencies relative to native apps or even `bokeh.client`. I propose to deprecate it and remove it entirely before `1.0`

ping @bokeh/dev

**Comment by mattpap** [comment]
I presume it's possible to detect bokeh being run in a notebook? If so, we could remove `output_*()` functions altogether.

**Comment by damianavila** [comment]
> I presume it's possible to detect bokeh being run in a notebook?

Not possible to know if bokeh is running from a notebook or another client... the kernel does not know anything about the frontend. Several frontends could be potentially "tied" to the same kernel which makes the mapping prone to errors. For instance, I can start a notebook which connect the web frontend with a specific kernel, then I attach a jupyter console to the same kernel, if I ask the kernel from where I am triggering the command, and we previously "linked" it to the web client, it would tell me that I am/running from the web client but I actually used the jupyter console...

**Comment by bryevdv** [comment]
Right, the only way to "know" is to try and publish something and try to see if it fails or not. We in fact did just that a few years ago. Unfortunately it had some bad unintended side-effect (I don't remember the details) and had to be reverted in a hurry in the next release.

Also `output_file` and `output_notebook` are  used ubiquitously. Removing them would break mountains of code. But `output_server` I think we could nip in the bud if we do it soon.

**Comment by bryevdv** [comment]
@bokeh/dev any more thoughts? There seems to be a sudden spike in questions around `output_server` so I am definitely inclined to proceed with a deprecation. `output_server` is basically useless except for static plots and leads people to confusion when callbacks "don't work."

**Comment by mattpap** [comment]
@bryevdv, my understanding of server and its various entry points is insufficient for advice. Though I will vote +1 just for reducing the number of entry points.

**Comment by bigreddot** [comment]
There ar.e no -1 votes, so I will make this a task

**Comment by bryevdv** [comment]
No one chimed in to oppose, so I will make this a task

**Comment by mattpap** [comment]
@bryevdv, solving #5199 I was wondering why callbacks aren't called as expected although everything is set up properly and data flows the way it should between client and server. Yet, to experiment on, I chose the only example that uses `output_server()`. Switching to another example (using `push_session()`) "fixed" the issue immediately.

**Comment by bigreddot** [comment]
Yes, keeping `output_server` was a mistake. It's basically useless. There were so many things breaking/changing in `0.11` that I wanted to try and not add one more incompatibility, but it would have been better to make a clean break then.
