### ISSUE TITLE
OpenURL only works for TapTool but is accepted Callback instance everywhere

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5163]
Currently, a `OpenURL` callback can be set as the callback attribute anywhere across Bokeh, but only works when configured on a TapTool and maybe a ColumnDataSource (though it might open a window several times).

I'd recommend refactoring to only be allowed on a ColumnDataSource (this would be a breaking change), so that any selection (either TapTool or lasso/box select) would trigger the OpenURL. Code-wise, this should be straightforward and would allow us to unify the TapTool with the rest of the select tools (making the callback cb_obj and cb_data pattern similar).

**Comment by bryevdv** [comment]
This was made consistent.
