### ISSUE TITLE
Add support for _repr_html_ to HasProps and Model

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5164]
`_repr_html_` was originally implemented on `Plot` to render a plot immediately without need for `show()`, at al. This didn't work well, so the code was commented out to be revised in future. Recently, `_repr_pretty_` was implemented to get insight into objects' properties. This works nicely across the board, but could work better in the notebook.

`_repr_html` should be added, so that it produces a shortened version of what `_repr_pretty_` produces, with a `...` button which would expand object's properties, showing more `...` buttons for embedded objects.

This is a followup on #5153.

**Comment by mattpap** [comment]
@damianavila, do you know if something like this was done or attempted in other projects? I will be implementing this, but I don't want to do it for numpy arrays, lists, dicts and so on. For now I didn't find anything useful around the internet and IPython's documentation, but I'm not sure if my questions are wrongly formulated or I'm the first one to want this kind of behavior.

**Comment by damianavila** [comment]
I don't remember any project specifically doing this from the top of my head... probably pandas is one of the packages going a lot woth `_repr_html_` things... to show dataframes on the notebook, so maybe there is something there, but not sure. Very nice idea, btw...
