### ISSUE TITLE
Tabs Only Renders Right When At Least One Tab Contains A Figure

### ISSUE THREAD

**Issue by JasonSickler** [bokeh/bokeh#5169]
I've found that, running through a Bokeh Server, the Tabs widget will not render correctly (i.e. it puts the tab contents all together in series, without any tab structures, as per #3650) if no panels contain a figure.  Specifically, this renders as expected:

```
p1 = figure()
tab1 = Panel(child=p1, title="circle")

p2 = Button(label="Button 2", button_type="success")
tab2 = Panel(child=p2, title="line")

tabs = Tabs(tabs=[ tab1, tab2 ])
```

And this change to the first line (swapping a button in for the figure) fails to render the tabs as expected, putting the contents of the tab panels into a single column:

```
p1 = Button(label="Button 1", button_type="success")
tab1 = Panel(child=p1, title="circle")

p2 = Button(label="Button 2", button_type="success")
tab2 = Panel(child=p2, title="line")

tabs = Tabs(tabs=[ tab1, tab2 ])
```

Version Information:

```
Bokeh version:  0.12.2
Python version:  3.5.2 |Anaconda custom (64-bit)| (default, Jul 2 2016, 17:53:06)
```

**Comment by bryevdv** [comment]
Thanks for the report @JasonSickler I have run into this too.

**Comment by alanmitchell** [comment]
I have observed this problem as well.  My workaround has been to add an invisible Tab with a figure by using a blank title:

```python
fig1 = figure()
fig1.circle([0],[0])
tab_invsible = Panel(child=fig1, title='')

tabs = Tabs(tabs=[tab1, tab2, tab_invisible])
```
This will cause the Tabs to render properly.

**Comment by bryevdv** [comment]
confirmed this code works with #8085 
```
from bokeh.models import *
from bokeh.io import curdoc

p1 = Button(label="Button 1", button_type="success")
tab1 = Panel(child=p1, title="circle")

p2 = Button(label="Button 2", button_type="success")
tab2 = Panel(child=p2, title="line")

tabs = Tabs(tabs=[ tab1, tab2 ])

curdoc().add_root(tabs)
```

@mattpap  I agree it would be good to have a test
