### ISSUE TITLE
Viridis6 appears to be reversed 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5170]
<img width="311" alt="screen shot 2016-09-15 at 10 32 52 am" src="https://cloud.githubusercontent.com/assets/1078448/18556132/04dd3140-7b30-11e6-80bd-db7f4c336c4f.png">

**Comment by canavandl** [comment]
the offending line: https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/texas.py#L13

(should reverse a copy of the palette instead)

**Comment by mattpap** [comment]
It would be nice if it wasn't possible to mutate palettes. This is a responsibility of definition-site to guarantee this. This will, most likely, require API change.

**Comment by birdsarah** [comment]
You should have seen my face when I opened the palettes page in a tutorial yesterday.

And I believe I'm the one that put the bug in there!
