### ISSUE TITLE
Replacing jsnlog

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5171]
I'm not sure what was the rationale for choosing jsnlog, but this seems to be a bad choice. jsnlog is big (1kloc), by default tries to do AJAX calls, which leads to meaningless errors in js console when using `file://` protocol, it is obtrusive to the hosting environment (configures `window.onerror`) and doesn't preserve line numbers. I propose switching to e.g. `loglevel`, which is small, unobtrusive and preserves line numbers. ~~The only deficiency is lack of log message prefixing (with `Bokeh`), but otherwise it's not possible to maintain line numbers~~. I think that having correct line numbers is more important than a prefix (especially since switching to browserify, where we have one big blob of code). @bryevdv, I would like your feedback on this.

**Comment by bryevdv** [comment]
Agree at this point having line numbers is better.

**Comment by mattpap** [comment]
Actually it is possible to have both line numbers and prefixes.
