### ISSUE TITLE
Task: support updating computed transforms fields if dependencies change

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5174]
Currently, when a transform source field (or transform itself) is changed, the computed field isn't updated.

For example: when using a color mapper as a transform, if the color mapper instance or the field being transformed is updated, the `fill_color` attribute isn't computed.

``` python
p.patches('x', 'y', source=source,
          fill_color={'field': 'rate', 'transform': color_mapper},
          fill_alpha=0.7, line_color="white", line_width=0.5)
```

**Comment by canavandl** [comment]
Similarly, I could imagine using a computed transform to set the size property of a glyph based on some range values (or similar), then expecting the glyph size to change based on zoom level.

**Comment by birdsarah** [comment]
Agreed. This would be very useful. Thanks for bringing it up.

**Comment by bryevdv** [comment]
@canavandl I'd like to look at this, but can you provide a small complete test case?

**Comment by canavandl** [comment]
@bryevdv 

Either I was mistaken or the issue has since been resolved. It now appears that if you trigger a change event on the relevant `ColumnDataSource`, the computed transform column is recomputed as expected. It's not clear to me if a user should be expected to call `source.trigger('change')` after modifying a transformer (i.e. changing the jitter width) though, it's a little non-intuitive perhaps.

In the below example, clicking the button will rejitter the y-values of the rects.

```python
from bokeh.plotting import figure
from bokeh.io import show
from bokeh.layouts import Column
from bokeh.models import ColumnDataSource, CustomJS, Jitter
from bokeh.models.widgets import Button
from bokeh.palettes import Blues8

source = ColumnDataSource(data=dict(x=list(range(8)),
                                    color=Blues8,
                                    y=[0]*8))

jitter = Jitter(width=1.0)
cb = CustomJS(args=dict(jitter=jitter, source=source),
              code="source.trigger('change');")

button = Button(callback=cb, label="Re-jitter the y-values")

p = figure()
p.rect(x='x', width=1, height=5, source=source, fill_color='color',
       y={'field': 'y', 'transform': jitter})

show(Column(p, button))
```

**Comment by bryevdv** [comment]
>  It's not clear to me if a user should be expected to call source.trigger('change') after modifying a transformer

No that should not be necessary, so I'll leave this open for now
