### ISSUE TITLE
bokeh-compiler assignment to variable fails after import

### ISSUE THREAD

**Issue by CrystallineCat** [bokeh/bokeh#5177]
I'm loading bokeh into jupyter notebook from CDN, including bokeh-compiler. The assignment of the compiler to its variable fails due to it being undeclared (line https://github.com/bokeh/bokeh/blob/fff76c5d47f22cca0c672fc73d77fb3ff4717153/bokeh/resources.py#L413).

The bokeh version CDN provides me with is 0.12.2, my browser is Firefox 48.0, jupyter is 4.2.0.

I'm running the following code in the notebook:

```
import bokeh.io
import bokeh.resources

resources = bokeh.resources.Resources(
    mode = 'cdn',
    components = (
        'bokeh',
        'bokeh-compiler',
        'bokeh-widgets',
    ),
)

bokeh.io.output_notebook(resources)
```

This gives me the unhelpful "Compiler requested but failed to import" message in the log. The masked original exception turned out to be:

```
ReferenceError: assignment to undeclared variable coffee
Stack trace:
outer@http://localhost:8888/static/notebook/js/main.min.js?v=f8115aaf7a88fe8ef22f54c4da3b8915 line 20450 > eval:103:26
inline_js<@http://localhost:8888/static/notebook/js/main.min.js?v=f8115aaf7a88fe8ef22f54c4da3b8915 line 20450 > eval:96:17
run_inline_js@http://localhost:8888/static/notebook/js/main.min.js?v=f8115aaf7a88fe8ef22f54c4da3b8915 line 20450 > eval:151:9
@http://localhost:8888/static/notebook/js/main.min.js?v=f8115aaf7a88fe8ef22f54c4da3b8915 line 20450 > eval:172:7
run_callbacks/<@http://localhost:8888/static/notebook/js/main.min.js?v=f8115aaf7a88fe8ef22f54c4da3b8915 line 20450 > eval:46:65
run_callbacks@http://localhost:8888/static/notebook/js/main.min.js?v=f8115aaf7a88fe8ef22f54c4da3b8915 line 20450 > eval:46:5
load_libs/s.onload@http://localhost:8888/static/notebook/js/main.min.js?v=f8115aaf7a88fe8ef22f54c4da3b8915 line 20450 > eval:72:11
```

Adding "minified = False" to the Resources object doesn't affect this behaviour, neither does moving bokeh-widgets before bokeh-compiler.

**Comment by mattpap** [comment]
This is clearly a trivial bug. The reason this doesn't work specifically in the notebook, is that it uses `strict` mode, which doesn't allow code like this. This issue isn't going to be fixed, because runtime compilation (bokeh-compiler and all related offending code) was replaced with precompilation (in node.js) in 0.12.3 (to be released in next two weeks).
