### ISSUE TITLE
Colorbars for palettes that include white

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#5191]
The new colorbars often look good, but I'm curious about the decision to show them "bare", with no containing outline around the colored portion.  (@birdsarah, @canavandl) A large number of colormaps start or end with white, including the most basic of all colormaps, i.e. greyscale.  For instance, more than half of matplotlib's sequential colormaps end in white, and a similar percentage of bokeh's palettes end in nearly white values.  Any of these colormaps are at best confusing and at worst ambiguous when shown with the default colorbar styling:

![image](https://cloud.githubusercontent.com/assets/1695496/18647560/299ef15e-7e7c-11e6-86ad-2d6c5693663b.png)

Because there's no telling which colormap someone might end up using, it seems safer to have a very, very thin dark border around the colorbar, but are we meaning to assume that people will rarely be using such colormaps?  It's actually fairly difficult to enable an outline and get something usable.  E.g. just enabling the color using `bar_line_color='#000000'` doesn't work well:

![image](https://cloud.githubusercontent.com/assets/1695496/18647992/40134776-7e7e-11e6-887e-321ad52dafc7.png)

So one would have to change not just the outline, but the white tick bars, and also maybe the line width, making me expect that most people will just end up shipping colorbars that don't show the endpoint clearly. :-(

**Comment by birdsarah** [comment]
Choosing defaults is hard. I was greatly influenced by ggplot2's styling when I picked these defaults.

**Comment by mattpap** [comment]
We could use something like this https://github.com/bokeh/bokeh/blob/d2ce1971e4b984c7d30728b2378f7c959a3efd06/bokehjs/src/coffee/api/charts.coffee#L70 instead.

**Comment by jbednar** [comment]
@mattpap, I'm generally in favor of having defaults that vary for overall light or dark conditions, but I'm not sure how they would be used in this case. A colormap by definition will include a wide range of colors, some of which will typically have a contrast against black or white, others of which will not.  Are you suggesting that Bokeh should figure out the background color, then automatically choose an outline color to contrast with it?  That would be ok by me, but is more ambitious than I was imagining, which was just to use a tiny thin black outline by default, since that works well with the white backgrounds that are typical and people who use non-white backgrounds will always need to change various defaults anyway.

**Comment by bryevdv** [comment]
At the least a thin configurable border is easy to add.

**Comment by bryevdv** [comment]
This was already done at some point? 
```
    border_props = Include(LineProps, help="""
    The %s for the color bar border outline.
    """)

    border_line_color = Override(default=None)
```

**Comment by bryevdv** [comment]
Hrm I guess not, that property controls a border around the entire CB area:

<img width="539" alt="screen shot 2017-06-21 at 14 49 18" src="https://user-images.githubusercontent.com/1078448/27403676-dda31f08-5690-11e7-906f-1924c1f343d7.png">

@jbednar @canavandl any thoughts? We  re-purpose this property to only draw around the colorbar area, or add a new property for that and keep this one as is.

**Comment by canavandl** [comment]
@bryevdv you want:

```python
    bar_props = Include(LineProps, help="""
    The %s for the color scale bar outline.
    """)

    bar_line_color = Override(default=None)
```

**Comment by bryevdv** [comment]
Yup:

<img width="164" alt="screen shot 2017-06-21 at 15 36 20" src="https://user-images.githubusercontent.com/1078448/27405504-6c871976-5697-11e7-9931-c52b892decdc.png">


Thanks @canavandl will close this as completed. Not super happy with the property names but they will  do.

**Comment by bryevdv** [comment]
Oh, I just notice that @jbednar already knew this but objected to the color scheme. I think I will actually just mark this as `invalid`. We could switch to black ticks and a black outline by default and then we just have the exact same problem for colorers with black in them. What about palettes with *both*? There's not a universal default that will always look good, so this is just a case where people will have to take responsibility to set things the way they want.
