### ISSUE TITLE
HoverTool line_policy 'nearest' 'next' not working

### ISSUE THREAD

**Issue by jsqliu** [bokeh/bokeh#5198]
Plotting with logscale on the y-axis and datetime on the x-axis.

'nearest' acts the same as 'prev', tooltip on previous point showing data of previous point
'next' displays the tooltip centered on the next point but still shows the data for the previous point (referenced using @column)

Tested by moving the mouse along the segment directly connecting neighboring points.

Python 2.7.12 Anaconda
Bokeh 0.12.2
Ipython 4.2.0

**Comment by bryevdv** [comment]
Please supply a minimal complete example that reproduces the problem.

**Comment by jsqliu** [comment]
```
import pandas as pd
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models import HoverTool

df = pd.DataFrame({'y':[6, 7, 2, 4, 5], 'x':pd.date_range(end='now', periods=5)})

output_file("lines.html")

p = figure(title="simple line example", x_axis_label='x', y_axis_label='y',
           y_axis_type='log', x_axis_type='datetime')
p.line('x', 'y', legend="Temp.", line_width=2, source=ColumnDataSource(df))

hover = HoverTool(
    tooltips = [
        ('y', '@y'),
        ('x', '@x'),
    ],
    line_policy='next'
)
p.add_tools(hover)

show(p)
```

**Comment by bryevdv** [comment]
Great, thanks, that makes checking things out much more efficient. We are the middle of a release hustle and some conference and client deadlines as well, so this will later this year before anyone on the core team probably can take a look. If you dig into things and find any more useful information please do share it here.

**Comment by bryevdv** [comment]
Here is a screenshot, mouse was on segment before the tooltip. Hopefully just a  simple off by one somewhere. 

<img width="472" alt="screen shot 2017-03-24 at 11 49 00" src="https://cloud.githubusercontent.com/assets/1078448/24304615/ff33e5fc-1087-11e7-9b06-bf5565cbd78e.png">
