### ISSUE TITLE
Figure legend not merging glyphs on the same data

### ISSUE THREAD

**Issue by Rubyj** [bokeh/bokeh#5202]
So i have a legend created as follows:

```
    fig.line(x="Week of", y="% Under 14", source=source, line_width=2, legend="% Under 14 Days", line_color="blue")
    fig.circle(x="Week of", y="% Under 14", source=source, fill_color="white", size=8, legend="% Under 14 Days", line_color="blue")  
    fig.line(x="Week of", y="% Under 21", source=source, line_width=2, line_color="red", legend="% Under 21 Days")
    fig.circle(x="Week of", y="% Under 21", source=source, fill_color="white", size=8, legend="% Under 21 Days", line_color="red")  
```

Like in the example at http://bokeh.pydata.org/en/latest/docs/gallery/legend.html I would expect my legend to look something like:

![image](https://cloud.githubusercontent.com/assets/4855908/18720741/423adcac-7ffb-11e6-8acc-afd85efdd762.png)

However, my legend ends up looking like this:

![image](https://cloud.githubusercontent.com/assets/4855908/18720749/4ba4c79e-7ffb-11e6-8bcb-acdd4f1fa9d3.png)

Seems like a bug with the legend and the circles not being joined with the lines

**Comment by bryevdv** [comment]
Just by way of collecting information, can you see if things work with much simpler legend text (i.e. no spaces, no `%`) Perhaps there is some edge cases to fix up. ALso, if you can expand the code snippet to a complete runnable code sample that reproduces the issue that is probably the absolute biggest help in making in issue easier (and hence more likely) to be investigated.

**Comment by Rubyj** [comment]
I tried to recreate this issue in a very simple form with this code

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
from bokeh import plotting
from bokeh.io import show

fig = plotting.figure(width=1200, height=900)
    
fig.line(x=[1,2,3,4,5], y=[1,2,3,4,5], line_width=2, legend="Under 1", line_color="blue")
fig.circle(x=[1,2,3,4,5], y=[1,2,3,4,5], fill_color="white", size=8, line_color="blue", legend="Under 1")  
fig.line(x=[1,2,3,4,5], y=[1,1,1,1,1], line_width=2, line_color="red", legend="Under 2")
fig.circle(x=[1,2,3,4,5], y=[1,1,1,1,1], fill_color="white", size=8, line_color="red", legend="Under 2")  

show(fig)
```

With this code no legend appears at all!

**Comment by Rubyj** [comment]
@bryevdv I am using bokeh-0.12.3.dev4

**Comment by bryevdv** [comment]
@Rubyj Thanks very much for raising this issue, we were about to release `0.12.3` but this is a showstopper. Please do try to always include version information from the start in future bug reports.

**Comment by Rubyj** [comment]
@bryevdv Will do. Just just double checked that the legend is working with expected behavior in `0.12.2` but not at all in `0.12.3.dev4`

**Comment by bryevdv** [comment]
@birdsarah I suspect #5190 is what broke the original behaviour that has been around since the beginning. @brittainhard is wokring to verify the root cause. If this is the case, I don't think we can afford to break this functionality for the new functionality, so we will have to think carefully about how to accommodate both. 

As a suggestion, perhaps:
```
# explicitly use old behaviour
plot.circle(x, y, legend=value("foo"))

# explicitly use new "use a column" behaviour
plot.circle(x, y, legend=field("foo"))

plot.circle(x, y, legend="foo")
```
The question is what to do for the last. As I see it could:

* always do the old behavior, i.e. be the same as `legend=value("foo")`
* try to do `legend=field("foo")` if it can find a column named `"foo"` in the source, falling back to `legend=value("foo")` if not

The latter is possbly convenient but also possibly confusing.

**Comment by bryevdv** [comment]
I also just realized there is now `label` and `legend`? What the difference, those are both very similar and that is confusing.

**Comment by brittainhard** [comment]
@bryevdv @Rubyj breaking commit appears to be [c40c7966490775d13d3d92d500be7d57ab7ea577](https://github.com/bokeh/bokeh/pull/5089/commits/c40c7966490775d13d3d92d500be7d57ab7ea577)

**Comment by brittainhard** [comment]
@bryevdv 

It looks like there are two problems. 

First, if there is no source kwarg supplied, then the legend just doesn't render, regardless of whether you pass a legend kwarg, https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/helpers.py#L114-L118. This is just a control flow logic flaw.

Second, theres the problem with the legend glyphs not being joined, which i'm looking into now.

**Comment by bryevdv** [comment]
I'm inclined to think we should not try to be smart here: we leave `legend` exactly and only as it was before, and let `label` be exactly and only for the new convenient way
