### ISSUE TITLE
Need to resize window before DataTable row labels show up

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5207]
When initially showing a DataTable, the page needs to be resized before the row columns show up.
This appears to have been true since at least 0.12.0.

On initial opening:

<img width="790" alt="screen shot 2016-09-21 at 7 35 06 pm" src="https://cloud.githubusercontent.com/assets/1796208/18732611/8b8fbb84-8032-11e6-8d4e-e77b9015b5a4.png">

After a window resize:

<img width="799" alt="screen shot 2016-09-21 at 7 35 32 pm" src="https://cloud.githubusercontent.com/assets/1796208/18732615/96f6e420-8032-11e6-850c-c3e9820b118e.png">

**Comment by bryevdv** [comment]
This was fixed in some of the recent data table work.
