### ISSUE TITLE
Stop building noarch conda packages

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5209]
The status of no-arch packages seems unclear, and continuing to use them seems risky.  A new version of conda-build caused a release candidate build to partially fail (only after several hours and in the middle of the night, of course).

**Comment by bryevdv** [comment]
ping @bokeh/dev @kalefranz @ilanschnell @koverholt

Any comments or opinions welcome.

**Comment by ilanschnell** [comment]
Noarch, more precisely "Python noarch" packages have been a hack from the beginning, which I never really supported.  To me, there does not seem to be a natural way, to support them.  The current implementation (having the Python specific logic in a post-link script), although not ideal keeps the Python specific code outside of conda itself, which I consider a huge benefit.  There is currently an effort to improve Python noarch packages, but there is disagreement between Travis, Kale and myself which approach to take.

**Comment by almarklein** [comment]
My vote would be to finish that conda-forge feedstock. It will save a lot of work and/since there would be no more need for `noarch` or `conda-vonvert`.

**Comment by bigreddot** [comment]
@almarklein I don't understand you proposal or the relevance of conda-forge. We have to do more than just build conda packages, we have to upload to CDN, PyPI and docs. That's all going to happen in one single place, on TravisCI, for my sanity.

**Comment by damianavila** [comment]
> We have to do more than just build conda packages, we have to upload to CDN, PyPI and docs. That's all going to happen in one single place, on TravisCI, for my sanity.

Yep, that's a very important point... as an alternative @almarklein do you know what is missing in conda convert to support entrypoint properly? If we can fix that, it is jjust a matter to go back to conda convert and eventually use noarch packages when they are in a better position...

**Comment by kalefranz** [comment]
Much better boat h support will be included in conda 4.3. @soapy1 is actively working on it now.

**Comment by bryevdv** [comment]
@kalefranz what is the timeframe for 4.3?

**Comment by almarklein** [comment]
> We have to do more than just build conda packages, we have to upload to CDN, PyPI and docs.

Ah right. We started using `noarch` because it was supposed to make things easier w.r.t. `conda convert`. Making use of conda-forge fixes at least that problem. But I forgot about CDN etc.  On the other hand, conda-forge does fire up at least one instance of Travis, where we could potentially handle that?

**Comment by damianavila** [comment]
>On the other hand, conda-forge does fire up at least one instance of Travis, where we could potentially handle that?

We can potentially do that... but we have to wait for someone in conda-forge to actually make a release... and I would like to depend on us :wink: Additionally, we pass a lot of credentials using env variables in travisCI... I guess we would need to share those credentials with conda-forge to be able to run travis from them... I would probably be against that... but maybe I am too cautions.

**Comment by bigreddot** [comment]
I am also against that, and against making thing more complicated than they already are.

**Comment by bryevdv** [comment]
ping @kalefranz @soapy1 is there an update on 4.3 and reliable no-arch pacakges? I am trying to decided whether to proceed with getting rid of no-arch packages, or to wait things out.

**Comment by bryevdv** [comment]
There are new no-arch packages available with conda 4.3 but I would want to wait some time for more adoption of newer versions of conda before distributing Bokeh this way.
