### ISSUE TITLE
loading bokehjs via require doesn't correctly load bokeh

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5214]
So I've installed bokehjs from master:

``npm install ~/dev/bokeh/bokehjs``

but loading bokehjs via require doesn't import the correct namespace

node
```
const Bokeh = require('bokehjs')
> undefined
Bokeh.Plotting
> undefined
```

ping @mattpap

**Comment by bryevdv** [comment]
This won't work until the next full release?

**Comment by mattpap** [comment]
@canavandl, I just did the same, i.e. installed bokehjs locally and it works perfectly. Here's full output:
```
$ npm install ../repos/bokeh/bokehjs
/home/mateusz/tmp
└─┬ bokehjs@0.12.3-dev4 
  ├── es6-promise@3.0.2 
  ├── hammerjs@2.0.8 
  ├── jquery@2.2.4 
  ├── jquery-mousewheel@3.1.13 
  ├── jquery-ui@1.10.5 
  ├── numbro@1.6.2  (git+https://github.com/bokeh/numbro.git#b4ccab0574b07077d003590a5881a75df28ac723)
  ├─┬ proj4@2.3.15 
  │ └── mgrs@0.0.3 
  ├─┬ rbush@2.0.1 
  │ └── quickselect@1.0.0 
  ├─┬ root-require@0.3.1 
  │ └── packpath@0.1.0 
  ├── sprintf@0.1.5 
  ├── timezone@0.0.38 
  └── underscore@1.8.3 

npm WARN enoent ENOENT: no such file or directory, open '/home/mateusz/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
$ node
> b = require('bokehjs')
[Function]
> 
```

**Comment by mattpap** [comment]
What versions of node and npm do you have?

**Comment by mattpap** [comment]
Also note that `require("bokehjs")` return a factory function if `window` and `window.document` aren't present (which is the default under bare node.js), so testing for `Bokeh.Plotting` doesn't make sense. You would have to issue `Bokeh().Plotting`.

**Comment by mattpap** [comment]
@canavandl, everything works fine. You got `undefined` because the previous line is a statement, which has no return value. Try this:
```
> const b = require('bokehjs')
undefined
> typeof b
'function'
> typeof b().Plotting
Error: bokehjs requires a window with a document. If your runtime environment doesn't provide those, e.g. pure node.js, you can use jsdom library to configure window and document.
```
If you get the same output, then npm package works as expected.

**Comment by canavandl** [comment]
you are absolutely correct @mattpap. Having the import return a factory function was new to me. thanks again for making the previous fixes to support this.
