### ISSUE TITLE
task: better check that noarch package has been generated

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5215]
ref PR #5214

As part of pinning the conda, conda-build and conda-env versions #5214, a check was added to ensure that the noarch build was actually created and added to the $HOME/miniconda/conda-bld/noarch directory.

However, the check logic (ensuring that there 3 files in the noarch dir) is pretty fragile. A better check would ensure that build file with the correct name (e.g. bokeh-0.12.2rc1-py_1.tar.bz2) exists.

https://github.com/bokeh/bokeh/blob/master/scripts/travis_install#L36

**Comment by bryevdv** [comment]
this is no longer valid
