### ISSUE TITLE
Setting yAxis major label orientation causes bad positioning of labels

### ISSUE THREAD

**Issue by moualv** [bokeh/bokeh#5220]
Hi, i'm writting a small script which uses an y axis for every single line I want to draw. Because of the high number of axis I have, I want to put the major_label_orientation = 'vertical'. When I do this, all the major_labels appears shifted on an strange way. Also I've noticed that the figure.yaxis.major_label_orientation = 'vertical' works as expected. 

The code I've been using is: 

``` python
from bokeh.plotting import figure, output_server, show
from bokeh.models import LinearAxis, Range1d, CheckboxGroup, FixedTicker
from bokeh.io import curdoc
from bokeh.layouts import row
from bokeh.models.callbacks import CustomJS
from bokeh.palettes import Set3_12
from math import pi
import os
import csv
import operator

lines = []
lineIds = []
chart_figure = figure(title="Test execution report", x_axis_label='time (ms)', height=800, width=1600)
checkbox = 0
num_ticks = 8

def init():
    global chart_figure
    global lines
    output_server("test.html")
    chart_figure.extra_y_ranges = {}
    chart_figure.yaxis.major_label_orientation = 'vertical'

def draw_files():
    for filename in os.listdir('.'):
        if(filename.endswith('csv')):
            draw_file(filename)

def draw_file(filename):
    x, y, header = parse_csv(filename)
    column_id = 0
    for column in y:
        shield_id = filename + '_' + header[column_id + 1]
        draw_line(x, y[column_id], shield_id)
        column_id += 1

def parse_csv(filename):
    reader = csv.reader(open(filename))
    header = reader.__next__()

    x = []
    y = []
    for i in range(0, len(header) - 1):
        y.append([])

    for line in reader:
        count = 0
        for shield in line:
            if(count == 0):
                x.append(int(shield))
            else:
                y[count - 1].append(float(shield))
            count += 1

    return x, y, header

def draw_line(x, y, legend_name):
    global chart_figure
    global lines
    color = pick_color()
    lineIds.append(legend_name)
    chart_figure.extra_y_ranges[legend_name] = Range1d(start = min(y), end = max(y))
    ticks = get_ticks(min(y), max(y))
    ticker = FixedTicker(ticks=ticks)
    axis = LinearAxis(ticker = ticker, y_range_name = legend_name, axis_line_color = color)
    # Here is where I set to vertical
    axis.major_label_orientation = 'vertical'
    # --- 
    axis.major_label_text_align = 'center'
    axis.major_label_standoff = 10
    chart_figure.add_layout(axis,'left') 
    lines.append(chart_figure.line(x, y, legend=legend_name, line_width = 2, y_range_name=legend_name, line_color = color))

def pick_color():
    return Set3_12[len(lines) % 12]

def get_ticks(min, max):
    interval = (max - min) / num_ticks
    result = [min]
    for i in range(1, num_ticks - 1):
        result.append((min + interval * i))
    result.append(max)
    return result

def end():
    global chart_figure
    show(chart_figure)


init()
draw_files()
end()
```

The result with vertical orientation: 
![vertical](https://cloud.githubusercontent.com/assets/9383659/18779406/389a32fe-8179-11e6-8382-889347f067f8.png)

The result with horizontal orientation:
![horizontal](https://cloud.githubusercontent.com/assets/9383659/18779511/95c50012-8179-11e6-9974-769116e2f6a2.png)

**Comment by bigreddot** [comment]
@moualv This definitely seems a bug. By way of getting more information, can you try with an angled orientation instead of "vertical"? That should still let you save alot of space, and might be an immediate workaround if the problem is limited to handling of "vertical"

I also feel obliged to warn you: `output_server` is being deprecated, you should migrate to using the `bokeh.client` API, `push_session`, etc.

**Comment by bryevdv** [comment]
@moualv This definitely seems a bug. By way of getting more information, can you try with an angled orientation instead of "vertical"? That should still let you save alot of space, and might be an immediate workaround if the problem is limited to handling of "vertical"

I also feel obliged to warn you: output_server is being deprecated, you should migrate to using the bokeh.client API, push_session, etc.

**Comment by birdsarah** [comment]
ping @canavandl as you've dug a little into axis labeling

**Comment by moualv** [comment]
@bryevdv I'd also tried with float numbers in radians, but the labels appeared shifted too

**Comment by moualv** [comment]
Hi guys,
do you intend to fix this bug in short term? If not, could you give me some keys about how to find the problem? I'm very interested on fixing this bug, so I could work on it, actually

Regards,
Mauro

**Comment by bryevdv** [comment]
I believe this is fixed (or is being fixed currently), however, unfortunately I cannot run the example code to verify that since it assumes input files not included. If a problem still persists after `0.12.11` please re-open with a complete example that can be run for further investigation.
