### ISSUE TITLE
Make legends great again

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5228]
Legends are a somewhat unloved corner of Bokeh. See #4526 for some property changes for more consistent API.

One of their odd features is the specification of Legend.legends as `[('label', [glyph_renderer_1, glyph_renderer_2])]`

This allows for a sort-of implicit compound glyph renderers (that is two glyphs representing the same piece of data) which is very handy.

However, it has other limitations and doesn't handle many cases well e.g. 
- Having multiple rows in your legend that represent different visual views on the same glyph_renderer e.g. categorical coloring in gapminder plot
- Being able to select which visual version of a glyph renderer (the hover, selection, non-selection) you wish to be your legend item
- Setting properties of the glyph / label per legend item (e.g. one is bigger or has a bigger font)

PR #5089 started trying to support case (1) from above, but in doing so broke the ability to implictly build compound legend items when using figure - See issue: #5202 

@bryevdv and I had a think about what the ideal solution is, and, recognizing that getting there is a large chunk of work that may not happen any time soon, came up with a compromise solution that lays a path towards ideal while moving us forward without breaking everything.

Worth throwing in a definition at this point. A "compound glyph renderer" is where you have two or more Glyphs with the same data source, and the same data properties (x, y) (they are visually representing the same data concept), but optionally different visual properties (different colors, sizes, etc).

---
### Ideal Case

``` python
class Legend(Annotations):
    items = List(LegendItem)
    # other legend props see #5202 for more info

class LegendItem(HasProps):
    # Defines one (if label is value) or many (if value is field and there are multiple values) rows of a legend
    label = StringSpec
    renderer = GlyphRenderer
    representative = Number  # Which version of your glyph is your representative point (may be an index of your data source)
    kind = Enum(GLyphKind)  # Do you use the visual styling of the "glyph", "hover", "selection", "nonselection", "decimated" - all of which are specified on GlyphRenderer
    # Also in future legend item visual props

class GlyphRenderer(Renderer):
    data_source = Instance(ColumnDataSource)
    glyphs = List(GlyphSpec)  # Always a list so GlyphRenderers can always be compound, but are often lists of length 1
    x_range_name = String
    y_range_name = String
    level = Enum

class GlyphSpec(Model):
    # A collection of Glyphs that together specify the different views on a glyph
    glyph = Instance(Glyph)
    hover = Instance(Glyph)
    selection = Instance(Glyph)
    nonselection = Instance(Glyph)
    decimated = Instance(Glyph)
```

In this case a legend item can only have one label (`LegendItem.label`) and one data source (`LegendItem.renderer.data_source`). And in that way you always know: 
(a) The one true label
(b) If the label is a field, the one true data source

Because it is the renderer that knows how to draw itself it will know to go through and draw, for each row, each of its glyphs.

This has more questions to be answered:
- Problems with hovertool accepting this as an input to renderers?
- How do you do the syntactic sugar to build a compound vs a normal glyph renderer?
- How do you deprecate this smoothly?
- Any problems with server updates that we haven't thought of?

---
### Practical next step

Because this implies a fairly large change to GlyphRenderer which would be non-trivial, we propose the following intermediate solution which leaves the door open to move towards the above in the future

``` python
class Legend(Annotations):
    items = List(LegendItem)
    # other legend props ...

class LegendItem(HasProps):
    label = StringSpec
    renderers = List(GlyphRenderer)
    # VALIDATION: all renderers.data_source must match
    # VALIDATION: if label is field, it muse be in renderers[0].data_source

class GlyphRenderer(Renderer):
    # No change from current glyph renderer 
```

We will deprecated Legend.legends and transform Legend.legends into the new LegendItem spec. 

The most problematic aspect of this proposal is that you have a list of GlyphRenderers each with their own data_source which means that if label is a field, there is not "one true data source". We will add validation both python and js side to test that all data_sources are the same. (But problems may arise if people try and change the data source in a server app - but we think its worth waiting to see if that ever comes up - currently changing a whole data source is not the way we change data in a server app so shouldn't be a problem)

---
### Gotchas

The biggest gotcha that we see is what happens when properties are changed by server. At the moment the legend is only made at initialization and so this is somewhat irrelevant, but it's something to bear in mind in the future. I'm also not sure what the current state of nested watching is - e.g. we'd want the `renderer` to redraw when `renderer.glyphs[0].glyph.line_color` was changed by the server

---
### Plotting helpers

There are two pieces of magic that plotting (`p.circle()`, `p.line()` etc) do for us:
1 - Transform a legend kwarg to a Legend.item.label
2 - Decide whether we have a compound glyph or not

Even in the ideal situation although users could spell out their compound glyphs we would want plotting to do this seamlessly and not create extra work for people.

1 - Transform a legend kwarg to Legend.item.label
- If no source is passed with glyph renderer function call then assume label is a value() (not a field).
- If source is passed then, we take a look at legend string, and if it is in the column_names, then we assume it's a field(). If it's not we take it as a value().
- To be explicit use field(), value(). 

2 - Is compound?
Legend is compound if:
- label is the identical (key and value of StringSpec must match)
- if data source is the same column data source object

We only apply this magic when users use the legend kwarg of a glyph_function - which preserves existing behavior. They can always just build their own legend.

**Comment by birdsarah** [comment]
@bryevdv - I think, for now, we want if label is field then all data sources must match. Otherwise when people are using figure in the simplest way possible two different data sources will have been created.

**Comment by bryevdv** [comment]
mistakenly closed

**Comment by bryevdv** [comment]
I think this actually has been largely implemented, in any case I'd like to see focused issue for individual improvements going forward.
