### ISSUE TITLE
intermittently failing examples tests - ggplot_density and graphs

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5232]
The examples tests are occasionally failing. ggplot_density and graphs are standing out for me as ones that fail. Haven't been tracking - just noticing today.

**Comment by mattpap** [comment]
In general, there are a bunch of examples that fail (image diff) for no apparent reason, `ggplot`, `seaborn`, etc. It doesn't seem to be related to random data generation (we seed all known generators).

**Comment by philippjfr** [comment]
We use image diffs for comparison in holoviews and have found that seaborn output is not deterministic.

**Comment by mattpap** [comment]
For example, `compat/seaborn_tsplot.py` run 10 times generates 10 different outputs. Those aren't trivial differences at least per generated JSON, though visually they are hard to catch (some of ticks and lines being slightly translated).

**Comment by bryevdv** [comment]
If we are deprecating MPL support then there is no point in fixing this.

**Comment by mattpap** [comment]
@bryevdv, yeah, the point is that I will take those examples off image diff.
