### ISSUE TITLE
Plot not shown if DatetimeTickFormatter partially defined

### ISSUE THREAD

**Issue by hettlage** [bokeh/bokeh#5234]
A plot may not be shown if formats aren't provided for all time scales.

This is reproduced by the following code:

```python
from datetime import datetime as dt
from bokeh.models.formatters import DatetimeTickFormatter
from bokeh.plotting import Figure, output_file, show

output_file('bokeh.html')

p = Figure(title='Demo', x_axis_type='datetime')

x = [dt(2016, 1, 1, 0, 0, 0), dt(2016, 1, 1, 0, 0, 10)]
print(x[1].day, x[1].hour, x[1].minute, x[1].second)
y = [1, 2]

p.scatter(x=x, y=y)

p.xaxis.formatter = DatetimeTickFormatter(formats=dict(
    seconds=["%H:%M:%S"],
    # a plot is displayed if the following lines are *not* commented out
    # minsec=["%H:%M:%S"],
    # minutes=["%H:%M:%S"],
    # hourmin=["%H:%M:%S"],
)
)

show(p)
```

This has been tested with:

Python version      :  3.5.2 (default, Sep 25 2016, 19:32:42) 
IPython version     :  Not installed
Bokeh version       :  0.12.2

**Comment by bigreddot** [comment]
All datetime scales always have to be defined. We could probably add a validation check and error if this condition is not satisfied, but the condition will always be necessary. You can create a new dict with a copy of the defaults (that you can update however you like) by calling the function  [bokeh.models.formatters.DEFAULT_DATETIME_FORMATS]. Alternatively you can construct your own dict that has all those keys.

**Comment by hettlage** [comment]
Thanks! A validation check would be great. Alternatively (or in addition) you could perhaps make this clearer in the documentation - at the moment http://bokeh.pydata.org/en/latest/docs/reference/models/formatters.html has an example which *doesn't* include all datetime scales. :-)

**Comment by mattpap** [comment]
Alternatively, properly defined `DatetimeTickFormatter` shouldn't have `formats` field, but each `format`'s key should be `DatetimeTickFormatter`'s field. Especially that `formats` is a dict that fakes a struct.
