### ISSUE TITLE
Tickers and formatters have no documentation and examples

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#524]
- [x] Add documentation.
- [x] Use tickers/formatters in examples.
- [ ] Check if base classes aren't too generic (e.g. what's the relationship between `DaysTicker` and `DatetimeTicker`?).
- [ ] `BasicTickFormatter` seems to always allow scientific notation despite setting `power_limit_high` and `use_scientific=False` (maybe we could take advantage of `dtype` here and always disable scientific notation if array of integers is used?).
- [ ] Use specific type for `BasicTickFormatter.precision` (instead of `Any`).
- [ ] `_new_xy_plot()` handling of `FactorRange` is inconsistent with definition of `FactorRange` (expects `string_types` whereas `FactorRange.factors` is of type `Any`).
- [ ] `int` labels on categorical axis make first tick go off plot, but using `str` with the same values fixes the problem.

**Comment by bryevdv** [comment]
Ref docs exist, user guide ocumentation added in #2257

**Comment by damianavila** [comment]
@bryevdv, do you think is the docs enough to close this issue?

**Comment by bryevdv** [comment]
This issue covers more than just docs. Should probably create sub issues for the tasks.

**Comment by bryevdv** [comment]
Need to review for current relevance and create sub issues

**Comment by dhirschfeld** [comment]
FWIW I'm looking for info on how to use a `DaysTicker` and can't find any documentation or examples.

I want to have major ticks on every Mon with minor ticks on every other day and have the two ticklabel types formatted differently. It's something I can do (with a bit of effort) in matplotlib which I'm attempting to replicate in bokeh

**Comment by bryevdv** [comment]
General information about swapping out tickers is in the user's guide:

http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#tick-locations

specifics about `DaysTicker` are in the reference guide:

http://bokeh.pydata.org/en/latest/docs/reference/models/tickers.html#bokeh.models.tickers.DaysTicker

The current `DaysTicker` just takes a list of (integer) day numbers in a month, I don't think it can do what you want. But the good news is that Bokeh is very simple and easy to extend with your own custom models. Here is an example that a user contributed that makes a custom ticker to skip weekend dates:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/custom_datetime_axis.py

**Comment by dhirschfeld** [comment]
The example for `FixedTicker` is good as far as it goes, but there aren't examples for any of the other ticker types AFAICS. From the example I can see that it takes at least a `ticks` argument but it doesn't tell me anything about any other possible arguments.

The major usability issue I have is that the arguments aren't documented so there's no way to know what to pass to the constructor.  When a function/class just takes kwargs as an argument (e.g. `FixedTicker(**kwargs)`) it's *very* helpful to the user to have the required/optional arguments documented.

I know that's a lot of work and especially in a fast-moving project it may be unrealistic to keep the documentation up to date with the code until the changes settle down somewhat. In these cases examples can be very instructive.

If I can get it working I'll submit an example as a PR. My work-in-progress is at https://anaconda.org/dhirschfeld/bokeh-timeseries-example/notebook

**Comment by dhirschfeld** [comment]
The error message is at least explicit, but in the absence of documentation it's a bit hard to guess e.g. what the tags argument is supposed to do:
```python
>>> FixedTicker(a=1, b=2)
AttributeError: unexpected attribute 'b' to FixedTicker, possible attributes are desired_num_ticks, name, num_minor_ticks, tags or ticks

>>> FixedTicker(tags='a')
ValueError: expected an element of List(Any), got 'a'

>>> FixedTicker(tags=['a'])
<bokeh.models.tickers.FixedTicker at 0x44b2c18>
```

**Comment by bryevdv** [comment]
@dhirschfeld thanks for pointing this is a general documentation issue, but sometimes you are so familiar with something that you forget about it. In the reference guide, eery thing that is listed as a property can either be passed as a kwarg to the constructor, or set as an attribute. There is a general metaclass machinery that handles Bokeh class properties and they all work in a uniform and consistent way, on every Bokeh model.

**Comment by bryevdv** [comment]
So to be explicit, a `DaysTicker` as a `days` property, so you can either:
```
dt = DaysTicker(days=[1,5,10])
```
or 
```
dt = DaysTicker() # days = [] by default
dt.days = [1,2,5]
```
Every Bokeh model property behaves in exactly this same way.

**Comment by dhirschfeld** [comment]
I've got some tick locations as dates so I figure `DatetimeTicker` may be the way to go
```python
>>>majorticks
[Timestamp('2016-01-04 00:00:00', offset='30T'),
 Timestamp('2016-01-11 00:00:00', offset='30T')]
```
...but it doesn't seem to accept a list of datetimes? `possible attributes are desired_num_ticks, name, num_minor_ticks, tags or tickers`

**Comment by dhirschfeld** [comment]
Is there some way on a datetime axis to pass in a specific set of dates (in the same way as `FixedTicker` works for float axes)

**Comment by dhirschfeld** [comment]
I tried to use DateGapTcikerFromatter but with no joy so far

https://anaconda.org/dhirschfeld/bokeh-timeseries-example/notebook

**Comment by bryevdv** [comment]
@dhirschfeld `DatetimeTicker` is an *extremely* "high level" ticker, it tries to pick nice ticks automatically across a very wide range of scales, from microseconds, to centuries. It does not accept any list of fixed ticks, rather, it accepts a collection of `tickers` to use as the plot range crosses from scale to scale. 

I apologize if I was not very clear. There is not a ticker that I am aware of that does exactly what you describe (i.e. only pick ticks corresponding to Monday). I linked the `DateGapTickFormatter` with the intention of illustrating that it is *possible* for you to to create a custom to Bokeh in ways that suit your needs. In this case, it is probably instructive to look at the implementation of `FixedTicker`:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tickers/fixed_ticker.coffee

The relevant part is this:
```
  get_ticks_no_defaults: (data_low, data_high, desired_n_ticks) ->
    return {
      major: @get('ticks')
      minor: []
    }
``` 
This function take a hi/low data range and returns a list of tick locations for that range. Since it is a fixed ticker, it just always returns exactly the same set of ticks (whatever the `ticks` property on the model was set to). You could write your own ticker model,  with a different function there, that computes the timestamp of all the mondays in between `data_low` and `data_high` and returns those. Then the Axis would have ticks at every Monday.

**Comment by bryevdv** [comment]
Alternatively, if you only need a truly limited number of monday (don't anticipate users to pan outside the fixed set of monday you picked, e.g) then you can probably configure a fixed ticker with the timestamp (since epoch) expressed in milliseconds.

**Comment by dhirschfeld** [comment]
Thanks for your help with this, I'm not sure I've got the skills to operate on the JS side though.

Your alternative suggestion works (to a point) - if the user scrolls outside the plot range theres' not much point displaying nicely formatted ticklabels IMHO.
```python
ticks = [
    d.to_datetime64().astype('datetime64[ms]').view(np.int64)
    for d in majorticks
]
plot.xaxis[0].ticker = FixedTicker(ticks=ticks)
```
...however it seems that FixedTicker has no ability to distinguish between major and minor ticks?

**Comment by dhirschfeld** [comment]
The DateGapTickFormatter example runs fine standalone but when run in the *notebook* I get the below error:
```
Javascript error adding output!
Error: Module `DateGapTickFormatter' does not exists. The problem may be two fold. Either a model was requested that's available in an extra bundle, e.g. a widget, or a custom model was requested, but it wasn't registered before first usage.
See your browser Javascript console for more details.
```
![image](https://cloud.githubusercontent.com/assets/881019/13166816/30a5d050-d718-11e5-93f9-42216ee69cf1.png)

**Comment by bryevdv** [comment]
@mattpap This issue is a muddle. Most of the bullets are not about adding documentation. In any case there's not lots of docs and examples and some of the bullets seem no longer relevant. I'm closing this issue to clean things up. If there are still tasks to do, I'd highly suggest creating individual sub issues and collecting them in an Epic.
