### ISSUE TITLE
x_axis_type not in fuzzy matching for figure args

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5241]

**Comment by bryevdv** [comment]
This is because it's not a model property, it's just a thing that gets pulled out of kwargs, if it is present. Not sure we can make it work.

**Comment by bryevdv** [comment]
Ok, now `x_axis_type` *is* a property, on the `Options` for `Figure`. The options class initialize a bit differently, but now that `Options` exists, there *might* be a way to check "extra" kwargs against both `Options` and the glyph.
