### ISSUE TITLE
py.test prints garbage when there is a syntax error in *.py files

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5246]
By garbage I mean a dense block of text instead of a nicely formatted traceback. If you are patient enough, you can figure out what's wrong with your code, but it would be nice to get the usual output.

**Comment by mattpap** [comment]
The problem is with having `bokeh/charts/conftest.py` being part of bokeh module tree. py.test tries to import `conftest.py` files, this in turn import `bokeh` and fails and we get some bogus `ConftestImportFailure` exception. Removing that file restores the expected (well, more or less) py.test's behavior.

**Comment by bryevdv** [comment]
I've seen problems with this file before too, if we can just get rid of it, +1

**Comment by timsnyder** [comment]
I'm running into this after getting past #5888.  The full output I'm hitting looks like:
```
`-- (git)-[master]-> py.test -m 'not (js or examples or integration or quality)'
================================================ test session starts =================================================
platform linux -- Python 3.4.5, pytest-2.9.0, py-1.4.31, pluggy-0.3.1
rootdir: /home/tsnyder/bokeh, inifile: 
plugins: html-1.7, rerunfailures-1.0.1, selenium-1.2.1, variables-1.3, cov-2.3.1, xdist-1.15.0
collected 0 items / 1 errors 

======================================================= ERRORS =======================================================
_________________________________________________ ERROR collecting  __________________________________________________
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/py/_path/common.py:332: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/py/_path/common.py:378: in gen
    for p in self.gen(subdir):
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/py/_path/common.py:367: in gen
    dirs = self.optsort([p for p in entries
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/py/_path/common.py:368: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/_pytest/main.py:647: in _recurse
    ihook = self.gethookproxy(path)
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/_pytest/main.py:550: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/_pytest/config.py:297: in _getconftestmodules
    mod = self._importconftest(conftestpath)
../miniconda/envs/bokeh-dev-py34.1/lib/python3.4/site-packages/_pytest/config.py:322: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: (local('/home/tsnyder/bokeh/build/lib/bokeh/charts/conftest.py'), (<class 'py._path.local.LocalPath.ImportMismatchError'>, ImportMismatchError('bokeh.charts.conftest', '/home/tsnyder/bokeh/bokeh/charts/conftest.py', local('/home/tsnyder/bokeh/build/lib/bokeh/charts/conftest.py')), <traceback object at 0x7f75d2420e08>))
============================================== 1 error in 5.06 seconds ===============================================
```

The 'dense block of text' @mattpap mentions is the single line 'E' message from py.test that has a 

In my case, I just deleted the entire `build` directory tree that I had in my clone.  Rerunning py.test again seems to run the tests but then I run into something else that seems unrelated to the original problem.  
The attached [AttributeError_DoctestTextfile_fixturenames.txt](https://github.com/bokeh/bokeh/files/785071/AttributeError_DoctestTextfile_fixturenames.txt) shows the AttributeError I'm now hitting.


@mattpap can you clarify your earlier comment a bit? 
1. When you say 'Removing *that* file', which file do you mean? 
1. By 'expected (well more or less) ... behavior' do you also hit this `INTERNALERROR> AttributeError: 'DoctestTextfile' object has no attribute 'fixturenames'` issue?

Definite :+1: for fixing this.

**Comment by timsnyder** [comment]
In my case, it seems like a mixture of running `python setup.py install` and `python setup.py develop` led to this problem.
