### ISSUE TITLE
ColumnDataSource.prototype.get_length gives arbitrary results

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#525]
The implementation is as follows:

``` coffeescript
get_length: () ->
      data = @get('data')
      return data[_.keys(data)[0]].length
```

Due to arbitrary zero indexing, this not only can give unexpected results if one data source is shared for multiple purpose, but is also can give different results depending on the platform.

**Comment by bryevdv** [comment]
@mattpap this can be closed now?

**Comment by mattpap** [comment]
Actually, it still may return arbitrary results, because lengths aren't sorted.

**Comment by bryevdv** [comment]
Well I guess my point was that length should much more likely now be consistent. It's a pragmatic question.
