### ISSUE TITLE
Examples involving transforms using Math.random() fail image diff

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5254]
It's not possible to seed `Math.random()` due to security concerns. I hoped for phantomjs to allow to configure seed (e.g. as a command line option), but didn't have any luck with that so far. We could use a custom number generator, e.g. https://www.npmjs.com/package/random-seed, instead. That's a few extra kB and we will have full control over random number generation and reliable tests.

**Comment by mattpap** [comment]
Using custom generator may affect speed though.

**Comment by bryevdv** [comment]
@mattpap is `Math.random` needed in the actual library? Two alternatives come to mind:
* load `random-seed` from CDN in the example (if available via CDN)
* change the examples not to use random numbers 
Alternatively if it is absolutely needed, it seems it would only be needed in `bokeh-api.js`? That would be ok if there is no alternative.

**Comment by mattpap** [comment]
In PR #5713 I just disabled image diff for this example. It's the cheapest thing we can do about this right now.
