### ISSUE TITLE
How long will "add_periodic_callback()" last?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#5259]
I use the following code to schedule a daily report, yet after execute one or twice (i.e. 2 days), the callback stops to execute. 

```
def AutoPilotSchedule_handler(active):
    if active:
        curdoc().add_periodic_callback(dailyReport,3600000)
    else:
        curdoc().remove_periodic_callback(dailyReport)  
```

**Comment by bryevdv** [comment]
@charleywan2004 It should last as long as the session is open and connected. By default sessions have expirations, and time-out and disconnect after a period of inactivity. Do you see any output in the server console log about a session disconnecting? You can find more information about raising the log level and changing session expiration parameters here: http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html#module-bokeh.command.subcommands.serve

If you aren't seeing session disconnects, then perhaps there is a bug, though I would not look forward to trying to debug something that takes two days to reproduce. 

There amy also be better ways to structure whatever you are trying to do. It might be better to have some external cron job generate whatever data is needed for the report on a regular basis, and store it somewhere the bokeh app can see it. Then have a bokeh app just show whatever the "current" report state is, so it doesn't have to carry this long running state itself. But let's try to determine if there is a bug first.

**Comment by bryevdv** [comment]
Closing for lack of updates.
