### ISSUE TITLE
Plot updates cause heap to grow massively

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#5260]
So I've been working on updating plots from within the notebook and noticed that interaction really slows down after a lot of plot updates. I started profiling a little bit using the ``bokeh serve fourier_animated.py`` example on 0.12.3dev4 and found that the heap just keeps on growing, after about 30 seconds it had grown to 1 GB and the plot starts slowing down.

<img width="1435" alt="screen shot 2016-10-01 at 5 05 11 pm" src="https://cloud.githubusercontent.com/assets/1550771/19015285/4337777c-87f9-11e6-8a41-b1d2b6c77354.png">

It seems something is not being garbage collected. After a bit of investigation I found that there are a lot of LinearMapper instances that accumulate:

![image](https://cloud.githubusercontent.com/assets/1550771/19015302/862b78da-87f9-11e6-84d8-0ab2e59dc9c8.png)

and there also seem to be a lot of change events:

![image](https://cloud.githubusercontent.com/assets/1550771/19015305/b4f1b33c-87f9-11e6-9a54-644b0656e2f5.png)

Here's the heap allocation for the same example in 0.12.2:

<img width="1437" alt="screen shot 2016-10-01 at 5 13 34 pm" src="https://cloud.githubusercontent.com/assets/1550771/19015336/80c61eee-87fa-11e6-82bb-c8dffb70e7ca.png">

Bokeh 0.12.3dev4
Chrome Version 53.0.2785.116 (64-bit)
OS X 10.11.6

**Comment by philippjfr** [comment]
I've just gone back through the 0.12.3 dev releases and found this happens since 0.12.3dev1.

**Comment by bryevdv** [comment]
@philippjfr can you perform a `git bisect`? That would be an immense help. Now that we squash merge PRs there should not be many steps.

**Comment by philippjfr** [comment]
Will do.

**Comment by philippjfr** [comment]
Here's what ``git bisect`` says:

```
5117586cea3852589fa57ce8d440c1de84931b24 is the first bad commit
commit 5117586cea3852589fa57ce8d440c1de84931b24
Author: Mateusz Paprocki <mattpap@gmail.com>
Date:   Mon Sep 5 23:42:56 2016 +0200

    CartesianFrame.{xy}_mappers
```

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mattpap** [comment]
This commit isn't directly at fault, because it doesn't change much. What's different is that it changes `{x,y}_mappers` from cached, computed properties to getters, so now things are computed more often than before and there must be a preexisting memory leak around those properties, which is now more clearly visible.

**Comment by mattpap** [comment]
Looking at the code in `CartesianFrame` it's pretty obvious why this blows up without caching. I would prefer not to restore computed properties, so I will be looking for a different solution.

**Comment by bryevdv** [comment]
Is there any reasonable way we can test this? We could run one of these examples for 1 or 2 minutes, in one of the shorter builds. What's the most reliable way to look at memory consumption from a script? ping @birdsarah for ideas too

**Comment by bryevdv** [comment]
@mattpap if nothing else, we can resort to explicit getter functions that have to be called as functions.

**Comment by bryevdv** [comment]
@philippjfr can you test with master that this issue is resolved?

**Comment by philippjfr** [comment]
Testing now.

**Comment by philippjfr** [comment]
Working well for me, the JS heap now hovers around 30-50 MB on the fourier_example even after running it for a while. Thanks for the quick fix!

+1 on adding automated testing for this somehow, because it's easy to miss but really important.

**Comment by mattpap** [comment]
@philippjfr, regarding testing this I started issue #5269.
