### ISSUE TITLE
Split off Backbone.Events and don't depend on Backbone.Model if not necessary

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5264]
Some classes inherit `Backbone.Model` whereas they could simply inherit `Backbone.Events`. Changing this reduces memory footprint of instances of those classes and improves understanding (i.e. I just want event handling, but not everything else that `Model` allows).

**Comment by bryevdv** [comment]
> Some classes inherit Backbone.Model whereas they could simply inherit Backbone.Model

?

**Comment by mattpap** [comment]
@bryevdv, I meant "simply inherit `Backbone.Events`". Actually not inherit, but mix in, because `Events` isn't a class.
