### ISSUE TITLE
Improve mappers' inheritance structure

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5268]
Currently we have:

```
categorical_color_mapper.coffee:class CategoricalColorMapper extends ColorMapper.Model
categorical_mapper.coffee:class CategoricalMapper extends LinearMapper.Model
color_mapper.coffee:class ColorMapper extends Model
grid_mapper.coffee:class GridMapper extends Model
linear_color_mapper.coffee:class LinearColorMapper extends ColorMapper.Model
linear_mapper.coffee:class LinearMapper extends Model
log_color_mapper.coffee:class LogColorMapper extends ColorMapper.Model
log_mapper.coffee:class LogMapper extends Model
```
1. `GridMapper` seems unused, so I'm going to remove it (related to PR #5260).
2. `Mapper` abstract base class is needed.
3.  `CategoricalColorMapper` should be a `LinearColorMapper`, because `CategoricalMapper` is a `LinearMapper`, unless `CategoricalMapper` is wrongly defined.

@bryevdv, any feedback would be useful, especially about (3).

**Comment by bryevdv** [comment]
1) The idea (never implemented) was to have "2d" ranges that could trigger single events when either *or* both ranges changed. Then have 2d mappers on top of these. It's not clear to me that the former requires the latter, and as you say it's not in use, so I'm fine removing it and we can possibly revisit composite ranges later.

2) Agreed

3) Less clear on. It's probably true that you could implement a categorical mapper with a linear mapper but then that seems like it should be an implementation detail. It is not the right conceptual organization. A categorical mapper should never interpolate continuous values.

**Comment by bryevdv** [comment]
I will do this. I have it planned out already, just waiting on layout PR to finish to start.
