### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5273]
It's painful to look through `examples.log` at travis ci for actual errors. There are lots of warnings about column lengths, not using `value()` for `text_font_size`, etc. or related to external libraries.

Also, if we deprecate something, lets make sure that we removed all occurrences before merging. This may not be trivial to do everything manually, but you can take advantage of travis ci. Just remove the thing you're deprecating or replace deprecation with hard error (throw an exception) for a moment, run tests and when everything is fixed, restore deprecation.

**Comment by bryevdv** [comment]
Regarding the text one: That was ostensibly deprecated a long time ago. But I think perhaps the warning was swallowed or missed until now. So I'd actually propose at this late date "undeprecating" that one, and trying to to be smart about recognizing font sizes as values first, rather than fields.

**Comment by mattpap** [comment]
@bryevdv, it was swallowed, because deprecation code didn't use `BokehDeprecationWarning` and any warnings are only visible in `examples.log` and not directly in travis ci jobs' output. This way we aren't bothered with them too much. Until like me today, when I got some strange examples' failures and had to actually see what is going on. And the I scrolled through screens and screens of warning messages.

**Comment by bryevdv** [comment]
Well, we can proceed with really deprecating it, or not, but we need to come to a decision. It seems like the font size property could check that a string starts with a digit and if so treat it as a value. my guess is that lots of people rely on this at this point

**Comment by mattpap** [comment]
That may be the case. However, do we have any rules on field names? Because people could depend on having fields starting with digits. Not very likely but still. After all, `data` is a `dict`. In bokeh-scala I restricted allowed names to name literals.

**Comment by bryevdv** [comment]
if they do that, there is always `field("10pt")` as a fallback. We could also look for common font size suffixes (pt, px, etc) to be more narrow

**Comment by mattpap** [comment]
Of course, because this is localized to this specific property type. OK, lets proceed this way. Just I would use a regex to be specific on what we allow and what not.

**Comment by bryevdv** [comment]
Can you take care of that? I think it should go in for `0.12.3` tho I suppose we could also just remove the deprecation warning itself as a first step.

**Comment by mattpap** [comment]
Sure, I will remove the first commit from PR #5274 and implement this.

**Comment by bryevdv** [comment]
@mattpap do you have an estimate for this PR? This is one of the few remaining that I think must go in `0.12.3`

**Comment by mattpap** [comment]
@bryevdv, currently we have:
```
def prepare_value(self, cls, name, value):
       if isinstance(value, string_types):
            deprecated('Setting a fixed font size value as a string %r is deprecated, '
                       'set with value(%r) or [%r] instead' % (value, value, value))
            if len(value) > 0 and value[0].isdigit():
                value = dict(value=value)
        return super(FontSizeSpec, self).prepare_value(cls, name, value)
```
So, pretty much, I will have to undeprecate this?

**Comment by bryevdv** [comment]
Yes, I was proposing undeprecating this usage.
