### ISSUE TITLE
with --rerun, bokehjs test harness needs to reset directory

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5277]
Otherwise `os.chdir('bokehjs')` fails on the second attempt

An `os.chdir('..')` before the return code check at the end should fix.

**Comment by birdsarah** [comment]
:) you beat me to it.

pytest fixture with cleanup would be sensible I reckon.

**Comment by bryevdv** [comment]
@birdsarah can you elaborate? Are you proposing something specific and different than what I propose above? I'm not cure if "cleanup" is a technical term referring to some specific plugin or pytest feature, in this context
