### ISSUE TITLE
Typo in the Legend Location docs, and why "right_center" instead of "center_right"?

### ISSUE THREAD

**Issue by stvn66** [bokeh/bokeh#5288]
In the current documentation for the legend Location, there sentence says, "For legends in the to the central layout area, such as those created automatically..." but should actually say "For legends in the to the central layout area, such as those created automatically...."  I am fixing this right now.

Additionally, for the location commands, why do 6 of them have the vertical followed by the horizontal alignment but 2 of them have the horizontal followed by the vertical?  This inconsistency seems like it would lead to confusion.

**Comment by bryevdv** [comment]
marking this complete, @stvn66 can you open a separate issue to discuss the other?
