### ISSUE TITLE
Inconsistent Legend Location naming

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#5292]
When designating the location of a legend, the options are:
- "top_left"
- "top_center"
- "top_right" (the default)
- "right_center"
- "bottom_right"
- "bottom_center"
- "bottom_left"
- "left_center"
- "center"
  Of the 8 that options other than "center", why is the order for the orientation for 6 of them vertical followed by the horizontal alignment and 2 of them horizontal followed by the vertical? This inconsistency seems like it would lead to confusion.

For what it is worth, I noticed [Matplotlib](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.legend) uses '<vertical> <horizontal>'  (probably just following MATLAB). 

I see 3 options moving forward:
1. do nothing, force people to remember to use "<vertical>_<horizontal>" for top and bottom but "<horizontal> <vertical>" for center.
2. deprecate "left_center" and "right_center", changing them to "center_right" and "center_left". 
3. allow for both combinations for all 8 options, with a little more parsing i.e., add:
- "left_top"
- "center_top"
- "right_top" (the default)
- "center_right"
- "right_bottom"
- "center_bottom"
- "left_bottom"
- "center_left"

Thoughts?

**Comment by mattpap** [comment]
Before:
```
+-------------+---------------+--------------+
| top_left    | top_center    | top_right    |
+-------------+---------------+--------------+
| left_center | center_center | right_center |
+-------------+---------------+--------------+
| bottom_left | bottom_center | bottom_right |
+-------------+---------------+--------------+
```
After (given keeping `<vertical>_<horizontal>`):
``` 
+-------------+---------------+--------------+
| top_left    | top_center    | top_right    |
+-------------+---------------+--------------+
| center_left | center_center | center_right |
+-------------+---------------+--------------+
| bottom_left | bottom_center | bottom_right |
+-------------+---------------+--------------+
```
Makes sense. I'm not sure where this inconsistency comes from. I'm not sure if we want both, tough it would be easier to do than deprecating the old enumerations.
