### ISSUE TITLE
responsive layouts broken in master

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5294]
It appears that #5205 (Support passing suggested height/width values to document.resize method). Demonstrable with https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/bar_chart.py (resizing the page after initial load causes top two plots to disappear).

**Comment by bryevdv** [comment]
@canavandl I noticed a test for resizing is failing in https://github.com/bokeh/bokeh/pull/5293 but it has been passing otherwise?

**Comment by canavandl** [comment]
I have a fix coming imminently. I think it's passing the unit tests because of how the window is calling the resize event.

**Comment by bryevdv** [comment]
@canavandl any thoughts on #5293 welcome too
