### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by dnaura** [bokeh/bokeh#5297]
Hello,
Would it be possible to add a background image to the chart/figure/plot , like the "Mapping Geo Data" does ?
If we have for example a photography of a product and coordinates of defaults, it would be useful to locate the defaults visually.
Thanks.
David

**Comment by bryevdv** [comment]
There is no "background image" feature built into Bokeh. Is there are reason `image_rgba` or `image_url` could not work for this? You can change the "level" of the render if you need to, although I think image glyphs might already be "below".

**Comment by dnaura** [comment]
I don't understand how to use image_url in this case.
I don't want to change glyphs shape, but add a background for the overall frame (figure or chart).

**Comment by bryevdv** [comment]
renderer `level` is described here:

https://bokeh.pydata.org/en/latest/docs/reference/core/enums.html#bokeh.core.enums.RenderLevel

Additionally a Bokeh canvas could be made transparent and placed over an image. I do not believe there is demand to add more API to bokeh for this.
