### ISSUE TITLE
Feature: display HTML fields with HoverTool tooltips

### ISSUE THREAD

**Issue by Zulko** [bokeh/bokeh#5301]
Hi all !

In the templating system for HoverTool's tooltips, if I write "@myfield" and @myfield contains some HTML such as "<br/>", the html will be displayed as "raw text" instead of being used to format the content of @myfield.

Is there already any way to say "don't sanitize the content of the field" ? Otherwise it would be nice to have, as for now if you want to display a @field with complex information in the tooltip, there seems to be no way to format it nicely.

Thanks in advance !

**Comment by Zulko** [comment]
Just found out this is a duplicate of issue #2833:

https://github.com/bokeh/bokeh/issues/2833

Sorry for the noise. Bokeh's awesome by the way.

**Comment by bryevdv** [comment]
thanks for the kind words @Zulko
