### ISSUE TITLE
bokeh serve --show app/gapminder doesn't work

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5302]
Fails with `SyntaxError: encoding declaration in Unicode string`. Encoding line was added recently. Though the problem is with bokeh server, which should strip those lines before running a script.

**Comment by bryevdv** [comment]
Is this a py2 issue then? Working fine in py3 from `master`

**Comment by mattpap** [comment]
Yes.

**Comment by bryevdv** [comment]
Removing the encoding is the quickest fix for this release I assume? Can make separate issue for server to strip those out for next release?

**Comment by mattpap** [comment]
There are unicode characters in the file, so no.

**Comment by bryevdv** [comment]
Oh, I see, for the play/pause buttons... grr OK I will do it later today. 

For reference this is how `bokeh-plot` directive does it:

```
# need to remove any encoding comment before compiling unicode
pat = re.compile(r"^# -\*- coding: (.*) -\*-$", re.M)
source = pat.sub("", source)
```
should be fairly simple to add to Bokeh server code exec too, just will have to have tests.
