### ISSUE TITLE
app/surface3d doesn't work because custom model path is wrongly resolved

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5304]
This is a peculiar issue. The problem is that custom model's path skips one directory and points to `examples/app/surface3d.pyc` instead of `examples/app/surface3d/surface3d.pyc` and thus coffeescript implementation cannot be found. Easy solution is to restore `open(path).read()`. This doesn't however resolve the bug and custom module compiler still thinks it's somewhere else. I think this is a problem with how `bokeh serve app` runs scripts and paths aren't set up properly, but I have to verify this.

**Comment by mattpap** [comment]
Note that if changing to `open(path).read()`, then any `require()`s in `path` will fail anyway, but `surface3d` example doesn't use any.

**Comment by bryevdv** [comment]
Spectrogram is failing for the same reason. This used to work, I was running spectrogram constantly at strata

**Comment by bryevdv** [comment]
@mattpap OK the reason they worked in `0.12.2` is because they did `open(path)`

**Comment by bryevdv** [comment]
OK I will make a PR with the "quick fix" and open a separate issue for addressing the wider problem in `0.12.4` and we will note the limitation in the release notes.
