### ISSUE TITLE
embed/animated fails with "did not find model"

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5305]
`Error rendering Bokeh items  Error: Did not find model ID_HERE in session`.

**Comment by bryevdv** [comment]
Confirmed no output, and the message above in JS console.

**Comment by wangsheng1001** [comment]
I got the same error for the animated example.
Is there any solution?

**Comment by mattpap** [comment]
@wangsheng1001, not yet, we didn't have chance to get to this.

**Comment by jaritt** [comment]
Just in case it helps: 

I encountered the same error when using the embedded feature with server data (see http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#server-data). I used the exact example, which says that figure() auto adds the figure to curdoc(). On loading the generated Javascript, I got that error. However it worked fine, once I added the plot to curdoc manually: 

```
from bokeh.client import push_session
from bokeh.embed import autoload_server
from bokeh.plotting import figure, curdoc

# Apparently figure() doesnt auto add the plot to curdoc()
plot = figure(title="Linegraph", plot_width=300, plot_height=300)
plot.line(x=[1,2,3,4,5], y=[3,2,3,4,2])

# THIS LINE FIXED IT:
curdoc().add_root(plot)

session = push_session(curdoc())
script = autoload_server(plot, session_id=session.id)

# Just writing the html file
f = open("index.html", "w")
pre = "<!DOCTYPE HTML><html><head></head><body><p>Plot here:</p>"
post = "</body></html>"
f.write(pre + script + post)
f.close
```

**Comment by mattpap** [comment]
> # figure() function auto-adds the figure to curdoc()
> p = figure(x_range=(-11, 11), y_range=(-11, 11))

@bryevdv, is this true? I doubt it, because otherwise we wouldn't be able to layouts and such. It's `show()` at al. that does this.

**Comment by bryevdv** [comment]
It used to be true but is not anymore. I happened to fix and update this docstring last week.

**Comment by mattpap** [comment]
@bryevdv, OK. I was worried this is a deeper issue, but apparently it's just documentation and example(s) fixing what's required to be done.

**Comment by bryevdv** [comment]
Yes, a trivial fix I pushed a PR
