### ISSUE TITLE
embed/embed_multiple fails with unicode error on py2

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5306]
```
$ python embed_multiple.py 
Traceback (most recent call last):
  File "embed_multiple.py", line 80, in <module>
    f.write(html)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 672004: ordinal not in range(128)
```

**Comment by mattpap** [comment]
We have a tag for py3 but not py2.

**Comment by joshua-barber** [comment]
I am encountering the exact same issue using PY3 and Anaconda.

**Comment by bryevdv** [comment]
I can't reproduce this on python 3, @joshua-barber can you provide more system/platform information.

**Comment by joshua-barber** [comment]
I am using the [Jupyter data-science docker image](https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook). Package management on the image is handled by Anaconda, which I used to conda install Bokeh. All other Bokeh examples run with no issue; it is only the 'multiple embed' examples that throw the error @mattpap referenced. I haven't configured a Py2 env with Bokeh so I cannot confirm whether it occurs on **both** Py2 and Py3.

I will update this comment with more specific version info once I am at my dev laptop this afternoon.

**Comment by joshua-barber** [comment]
**[Correction**] The docker image is actually generated from this Dockerfile: [dockerfile.txt](https://github.com/bokeh/bokeh/files/591448/dockerfile.txt)

The referenced environment.yml is used to install:
- python=3.5
- Flask=0.11.1
- sqlalchemy=1.0.13
- psycopg2=2.6.2
- pandas=0.18.1
- pyyaml=3.12

A clean install of the Jupyter data-science image actually runs the examples with no issue. However I'm not clear on what it is in this docker image that is causing _only_ embed.py to fail and none of the other Bokeh examples.

**Comment by bryevdv** [comment]
@joshua-barber if you check out `master` and run the examples from there you should be able to confirm that they now function as expected. Please re-open if there is any continued problem.
