### ISSUE TITLE
BOKEH_DOCS_CDN = "local" clashes with BOKEH_DEV = True in bokeh_plot

### ISSUE THREAD

**Issue by djpugh** [bokeh/bokeh#5308]
In `bokeh_plot` there is an error generated if both variables are set as above:

```
Exception occurred:
  File "bokeh\resources.py", line 216, in __init__
    if self.mode not in ['inline', 'cdn', 'server', 'server-dev', 'relative', 'relative-dev', 'absolute', 'absolute-dev']:
ValueError: setting 'root_url' makes sense only when 'mode' is set to 'server'
```

`settings.docs_cdn()` is set to `local` but mode is set to `absolute-dev` and a `root_url` is set.

I'm not sure whether this is something to resolve in the settings or bokeh_plot or in the documentation, which suggests for `BOKEH_DOCS_CDN`:

```
BOKEH_DOCS_CDN¶

What version of BokehJS to use when building sphinx docs locally.

Note
Set to "local" to use a locally built dev version of BokehJS.
This variable is only used when building documentation from the development version.
```

**Comment by djpugh** [comment]
v0.12.3rc3

**Comment by bryevdv** [comment]
I'll have to think about it when I do some work on `:bokeh-plot:` they may just be incompatible

**Comment by bryevdv** [comment]
(FWIW I don't really ever use `BOKEH_DEV` but others do)

**Comment by bryevdv** [comment]
Upon further reflection, I don't think they are compatible, or perhaps that the cost to try and make them compatible is not justified. `BOKEH_DOCS_CDN=local` means that the local `docserver.py` that is run by `make serve` is that should provide the BokehJS for the docs. This is very convenient,  but is also explicitly at odds with `BOKEH_DEV=true` which AFAIK means that BokehJS should come from some separately started Bokeh server. I'd say just don't use `BOKEH_DEV=true` with local cdn option for docs building. If you have it set automatically in `bashrc` etc then can run, e.g.:
```
BOKEH_DEV=false BOKEH_DOCS_CDN=local make SPHINXOPTS=-v clean html serve
```
