### ISSUE TITLE
Add a colorblind and D3 palettes

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#5317]
I am interested in adding the seaborn color palettes, particularly the colorblind one.  I find these useful to load in then iterate through when plotting different curves.  Some of the palettes already included (Dark2, Set1, and Set2 from ColorBrewer) work reasonably well, but it would be good to have a better color blind option, and more options in general.  These are the 6 from seaborn I would like to add:

```
SEABORN_PALETTES = dict(
    deep=["#4C72B0", "#55A868", "#C44E52",
          "#8172B2", "#CCB974", "#64B5CD"],
    muted=["#4878CF", "#6ACC65", "#D65F5F",
           "#B47CC7", "#C4AD66", "#77BEDB"],
    pastel=["#92C6FF", "#97F0AA", "#FF9F9A",
            "#D0BBFF", "#FFFEA3", "#B0E0E6"],
    bright=["#003FFF", "#03ED3A", "#E8000B",
            "#8A2BE2", "#FFC400", "#00D7FF"],
    dark=["#001C7F", "#017517", "#8C0900",
          "#7600A1", "#B8860B", "#006374"],
    colorblind=["#0072B2", "#009E73", "#D55E00",
                "#CC79A7", "#F0E442", "#56B4E9"]
)
```

I have little experience with licensing, but looking at [seaborn BSD license](https://github.com/mwaskom/seaborn/blob/master/LICENSE) I believe we can use these as long as we copy the license in as a comment.  I have emailed Michael Waskom to confirm.

Thoughts?

**Comment by bryevdv** [comment]
Steve that would be great, and a PR would be welcome.

**Comment by stvn66** [comment]
I am thinking to also add the [vega categorical palettes](https://github.com/vega/vega/wiki/Scales#scale-range-literals) while adding the seaboard palettes (another BSD license).  Vega, catagory10, is the new default used by [matplotlib](http://matplotlib.org/devdocs/users/dflt_style_changes.html#colors-color-cycles-and-color-maps).  Any thoughts, for/against?  

Would this be better as a separate pull request?

**Comment by birdsarah** [comment]
I'm +1 on including the vega categorical palettes.

I'd also be +1 on changing our default for charts - which currently uses BlGnRd a lot - but I would say that's best done as a seperate PR.

**Comment by stvn66** [comment]
I posted some queries for opinions on the PR page, #5359.  Is it better to discuss here or there?

**Comment by stvn66** [comment]
I have another question, related to design.  Rather than have all the redundant lists for, currently used for the Brewer qualitative palettes:

```
     @property
     def Set2_3(self):
         return ["#66c2a5", "#fc8d62", "#8da0cb"]
     @property
     def Set2_4(self):
         return ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3"]
     @property
     def Set2_5(self):
         return ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3", "#a6d854"]
     @property
     def Set2_6(self):
         return ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3", "#a6d854", "#ffd92f"]
     @property
     def Set2_7(self):
         return ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3", "#a6d854", "#ffd92f", "#e5c494"]
     @property
     def Set2_8(self):
         return ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3", "#a6d854", "#ffd92f", "#e5c494", "#b3b3b3"]
```
would it be better to have slices of the complete palette?  Something like this:

```
     @property
     def Set2_3(self):
         return Set2_8[:3]
     @property
     def Set2_4(self):
         return Set2_8[:4]
     @property
     def Set2_5(self):
         return Set2_8[:5]
     @property
     def Set2_6(self):
         return Set2_8[:6]
     @property
     def Set2_7(self):
         return Set2_8[:7]
     @property
     def Set2_8(self):
         return ["#66c2a5", "#fc8d62", "#8da0cb", "#e78ac3", "#a6d854", "#ffd92f", "#e5c494", "#b3b3b3"]
```

This seems simpler.  Though once they are entered once, as long as there was not a typo, there no extra complexity to leave it.

**Comment by mattpap** [comment]
> would it be better to have slices of the complete palette?

This is an interesting idea worth pursuing, but if you would like to do this, make sure not to do it in one big PR. Having small focused PRs greately speeds up reviews.

**Comment by stvn66** [comment]
Here is an example plot of the proposed ordering for the colorblind ggplot2 palette.  
![bokeh_cycle_colors_cb_reodered](https://cloud.githubusercontent.com/assets/9484229/19480541/bcd859da-9518-11e6-8066-bb6d269ae114.png)

Adding this using the name `Colorblind` will clash with the seaborn palettes.  Any opinions on if we should actually incude the seaborn palettes?  If we want them both, I could add `sns` as a prefix/suffix to the seaborn ones.  Thoughts?

**Comment by gryBox** [comment]
> Having the Seaborn palettes may appeal to Seaborn users coming to Bokeh. **Any idea how heavily they are used?**

We use seaborn as our default colors including the background colors

**Comment by bryevdv** [comment]
@gryBox after a discussion on gitter it was decided to add just the vega and colorblind palettes, on the rationale that those (along with the brewer palettes) are the ones that are not easily obtainable via python already. But for users that prefer to use seaborn palettes, they can just import and get them from `sns` directly.

**Comment by stvn66** [comment]
This is one way to import the seaborn palettes
```
import seaborn.apionly as sns
palette = sns.palettes.color_palette('colorblind', 5).as_hex()  # use the first 5 colors from sns colorblind
```

**Comment by gryBox** [comment]
@stvn66    I like that ... better than what I was previously doing

**Comment by stvn66** [comment]
While working on this, I noticed the categorical [vega palettes](https://github.com/vega/vega/wiki/Scales), category10, category20, category20b, and category20c, are actually [from D3](https://github.com/vega/vega/commit/9018ef66ca0a64e755e388188561ab56e75a560c), or maybe even provotis (not familiar with this one).  I found a clear link to all four on D3, so I am going to use that license (plus I cannot find the provotis license).
