### ISSUE TITLE
Long "Bokeh Error"s don't wrap

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5322]
See e.g. https://s3.amazonaws.com/bokeh-travis/0.12.3rc6-564711d/plotting/file/custom_datetime_axis.png.

**Comment by bryevdv** [comment]
@mattpap @birdsarah is this a quick option?

http://www.w3schools.com/cssref/css3_pr_word-wrap.asp

**Comment by birdsarah** [comment]
that's not css property i'd use, but yes, it's just a css fix.

i would suggest: `white-space: pre-wrap;`

alternatively `overflow-x: auto;` because I think those error messages can be multi-lined and we want them to be shown as console output.
