### ISSUE TITLE
Improvements to deploy script

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5325]
The current deploy script is too fragile, and also has some bugs.

* When releasing, the version update needs to take into account the last dev or RC build, but the issues/changelog needs to take into account the last FULL release. This distinction is not made, causing errors in the changelog

* The script will add a line to docs for the release notes, even if that line already exists. 

In general, the script should:

* have extensive pre-checks that the environment is suitable for release (e.g. 
 - on master, up to date, no uncommited files
 - supplied versions actually make sense

* show results and have chekpoints along the way. i.e. "here's a diff of the changes I made, are they correct y/n?"

* I'm not sure we should push a separate branch to GitHub. It results in an extra build, and if we only merge the branch locally then we could have one clean place to safely "bail out" at the end (right before merging it) Doing two pushes means something can go wrong in between

It might make sense to have the script driven by python at the top level so that the UI, error reporting can be as clear an as uncluttered as possible.

**Comment by bryevdv** [comment]
ping @bokeh/dev @damianavila

**Comment by bryevdv** [comment]
The latest full release tag can be identified automatically

The latest "any" release tag (including dev or rc) can be identified automatically

These should be presented to the user for confirmation at the start

The proposed new version should be checked to be "greater" than the other version using `LooseVersion` or similar.

Whether or not to do a full release can be determined by the proposed tag. 

Then the script can be called more simply: `deploy 0.12.4` or `deploy 0.12.6rc2`

**Comment by bryevdv** [comment]
When running `deploy` the repo should be:
* on `master` 
* with no extra files or uncommitted changes
* up to date with GitHub `master`

If these checks fail, bail immediately

**Comment by bryevdv** [comment]
Before doing any work, confirm that the files to be updated actually currently have the correct previous version, otherwise bail early.

**Comment by bryevdv** [comment]
The script should make a test upload to CDN and error early if that fails.

**Comment by bryevdv** [comment]
OK, I have a script that just does checking so far:
```
================================================================================

            You are starting a Bokeh release deployment for '0.12.4'

================================================================================

!!! Running pre-checks for release deploy

[PASS] Running Python 3.x
[PASS] Command 'git' is available
[PASS] On master branch
[PASS] Checkout is clean
[PASS] Detected last dev/rc/full version '0.12.3' and last full release version '0.12.3'
[PASS] Files with version strings match expected last version '0.12.3'
[PASS] New version '0.12.4' is a valid Bokeh version (FULL RELEASE)
[PASS] New version '0.12.4' is newer than last version '0.12.3'
[PASS] CDN test file upload succeeded

!!! All pre-checks have passed
```

 It will fail unless:
* using py py3
* git is working, on clean master branch
* if last version tags and new version are valid bokeh versions
* new version is newer than the old version

There are also CDN upload and version string checks in the files to update, but they are stubs currently.

**Comment by damianavila** [comment]
This is looking good... eager to look into the PR when that is ready.
