### ISSUE TITLE
syntax error in util/deprecation.py

### ISSUE THREAD

**Issue by hstrey** [bokeh/bokeh#5330]
line 24:
    message += " " + extra.trim()
results in error: AttributeError: 'str' object has no attribute 'trim'

it should be instead:
    message += " " + extra.strip()

that fixes the problem.  I needed that change to get the happiness demo to run

Helmut Strey

**Comment by bryevdv** [comment]
Ping @mattpap

**Comment by mattpap** [comment]
Courtesy of dynamic typing and lack of testing. I mixed JavaScript with Python.
