### ISSUE TITLE
Depreciated example

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#5335]
https://github.com/bokeh/bokeh/blob/0.12.3/examples/embed/simple/simple.py

```
Because the ``resources`` argument is no longer needed, it is deprecated and no longer has any effect.
```

The link is also broken:
http://bokeh.pydata.org/en/latest/docs/user_guide/embedding.html#components

**Comment by bryevdv** [comment]
For reverence the link is 

http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#components
