### ISSUE TITLE
Strange behaviour of Rect-Glyph

### ISSUE THREAD

**Issue by busino** [bokeh/bokeh#5336]
Hello,
It looks like the `Rect` glyph has buggy behavior somewhere!!!
See attached example where you can `draw` a rectangle via `Selectbox`. After selecting the CustomJS will update the source of the `Rect` and the `Scatter`. The `Scatter`-Points and the `Rect`-Corner-Points do not match when using logarithmic scale.
Is this a bug?

```
from bokeh.plotting import figure, show
from bokeh.models.tools import BoxSelectTool
from bokeh.models.sources import ColumnDataSource
from bokeh.models.callbacks import CustomJS
from bokeh.io import output_file
from bokeh.models.glyphs import Rect


plot = figure(plot_width=600, plot_height=600,
              x_range=(0,20), y_range=(0,20),
              y_axis_type="log"
              )

# Initial Data
x = [10, 15]
y = [10, 15]

# Scatter
sc_source = ColumnDataSource(data=dict(x=x, y=y))
plot.scatter(source=sc_source, x='x', y='y', size=20)

# Rect
rect_source = ColumnDataSource(data=dict(x=[(x[0]+x[1])/2], y=[(y[0]+y[1])/2], width=[[x[1]-x[0]]], height=[y[1]-y[0]]))
rect = Rect(x='x',
            y='y',
            width='width',
            height='height',
            dilate=True,
            fill_alpha=0.3)
plot.add_glyph(rect_source, rect)

callback = CustomJS(args=dict(rect_source=rect_source, sc_source=sc_source), code="""
            var geometry = cb_data['geometry'];
            console.log(geometry);

            var width = geometry['x1'] - geometry['x0'];
            var height = geometry['y1'] - geometry['y0'];
            var x = geometry['x0'] + width/2;
            var y = geometry['y0'] + height/2;

            console.log(width, height, x, y);
            rect_source.data = {'x': [x], 'y': [y], 'width': [width], 'height': [height]};
            rect_source.trigger('change');

            sc_source.data = {'x': [geometry['x0'], geometry['x1']], 'y': [geometry['y0'], geometry['y1']]};
            sc_source.trigger('change');

""")
t = BoxSelectTool(callback=callback)
plot.add_tools(t)
plot.toolbar.active_drag = t


output_file('select_log.html')
show(plot)
```

Have a nice week,
Raphael

**Comment by bryevdv** [comment]
@busino thanks very much for the complete example to reproduce. Yes this seems like a bug. To draw itself, some glyphs like rect have to compute a "distance" between points and my hunch is that this is happening too late, in screen space. The assumption (which is broken by log scales) is that `x` and `y` are the center of the rectangle.

**Comment by busino** [comment]
Hi Bryan,

If you comment the `y_axis_type='log'` the `Rect` and `Scatter` are not matching on the first screen!

Raphael

**Comment by bryevdv** [comment]
@busino I'm not sure I understand the last comment? I ran your code and saw the mismatch with log scale and agree that it is a bug in that case. If I comment out the log axis, I see expected behaviour:

<img width="530" alt="screen shot 2016-10-11 at 9 30 42 am" src="https://cloud.githubusercontent.com/assets/1078448/19272159/786e9a26-8f95-11e6-9734-3a8ff9bdc5bf.png">

**Comment by bryevdv** [comment]
If you are seeing something different without a log scale, then more information is needed, versions, etc.

**Comment by busino** [comment]
Version: 0.12.3 always at the bleeding edge.

 * Comment `y_axis_type='log'`
 * No interaction
 * Capture image:

![capture](https://cloud.githubusercontent.com/assets/6582483/19272742/f6b2f6b4-8fc9-11e6-9a61-325453dcbecb.PNG)

**Comment by bryevdv** [comment]
@busino I just created a fresh bokeh `0.12.3` conda environment (OSX/Safari) and ran the code and got the correct result again. I can't reproduce what yo are seeing with the non-log axis. Can you provide more information? Platform, browser, etc. Are there any messages in the JS console?

**Comment by busino** [comment]
Platform: Windows 10 x64
Browser: Firefox 49.0.1
JS-Console:
```
[bokeh] setting log level to: 'info'
```

Reinstall latest bokeh with:
```
conda update bokeh -f
```
HTML Header:
```
<link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.css" type="text/css" />
        
<script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js"></script>
<script type="text/javascript">
    Bokeh.set_log_level("info");
</script>
```

**Comment by bryevdv** [comment]
OK thanks for the additional info, it may be next week before I can try to reproduce this on a VM, I am traveling all week.

**Comment by busino** [comment]
If you give me an entry-point I can give it a try fixing it.

**Comment by bryevdv** [comment]
@busino sure, tho I will say it's very weird that that is (apparently) platform or browser dependent. The first thing is that this is a problem in BokehJS, so you will have to get  a dev environment set up, and be able to build BokehJS locally:

http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup

Then you can run code with the env var `BOKEH_RESOURCES=inline` set to use the local BokehJS you built. Then the code that maps data to screen coords for rects is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/rect.coffee#L20-L28

That's were you could start with JS `console.log` or `debugger` statements.

**Comment by busino** [comment]
The issue with the `wrong initial` screen is an issue with integers/floats.
The initial data for the rect was:
```
x = [10, 15]
y = [10, 15]
```
setting them to `floats`:
```
x = [10., 15.]
y = [10., 15.]
```
resolved the `wrong initial` state.

I added a hovertool and printed `x,y,width,height` and saw what's going wrong.
Probably it's really a browser/platform issue.

Here is the updated script showing the main issue.

```
from bokeh.plotting import figure, show
from bokeh.models.tools import BoxSelectTool, HoverTool
from bokeh.models.sources import ColumnDataSource
from bokeh.models.callbacks import CustomJS
from bokeh.io import output_file
from bokeh.models.glyphs import Rect


plot = figure(plot_width=600, plot_height=600,
              x_range=(0,20), y_range=(0,20),
              y_axis_type="log"
              )

# Initial Data
x = [10., 15.]
y = [10., 15.]

# Scatter
sc_source = ColumnDataSource(data=dict(x=x, y=y))
plot.scatter(source=sc_source, x='x', y='y', size=20)

# Rect
rect_source = ColumnDataSource(data=dict(x=[(x[0]+x[1])/2], y=[(y[0]+y[1])/2], width=[[x[1]-x[0]]], height=[y[1]-y[0]]))
rect = Rect(x='x',
            y='y',
            width='width',
            height='height',
            dilate=True,
            fill_alpha=0.3)
rg = plot.add_glyph(rect_source, rect)

callback = CustomJS(args=dict(rect_source=rect_source, sc_source=sc_source), code="""
            var geometry = cb_data['geometry'];
            console.log(geometry);

            var width = geometry['x1'] - geometry['x0'];
            var height = geometry['y1'] - geometry['y0'];
            var x = geometry['x0'] + width/2;
            var y = geometry['y0'] + height/2;

            console.log(width, height, x, y);
            rect_source.data = {'x': [x], 'y': [y], 'width': [width], 'height': [height]};
            rect_source.trigger('change');

            sc_source.data = {'x': [geometry['x0'], geometry['x1']], 'y': [geometry['y0'], geometry['y1']]};
            sc_source.trigger('change');

""")
t = BoxSelectTool(callback=callback)
plot.add_tools(t)
plot.toolbar.active_drag = t

plot.add_tools(HoverTool(renderers=[rg], tooltips=[
                ("index","$index"),
                ("data (x, y)","($x, $y)"),
                ("data (w, h)","(@width, @height)"),
                ("data (x, y)","(@x{1.11}, @y{1.11})"),
                ("canvas (x, y)","($sx, $sy)"),
            ]))


output_file('select_log.html')
show(plot)
```

**Comment by bryevdv** [comment]
@busino are you using python 2?

**Comment by busino** [comment]
Python 2.7.12

**Comment by bryevdv** [comment]
OK, well that explains why things don't match up for you in the non-log case then. When you gave integers for `x` and `y` and then did:
```
x[0]+x[1])/2
```
Python 2 did a truncating division. I do think the "log axis" case is a bug, since I could reproduce it on python 3.

**Comment by bryevdv** [comment]
@busino Just FYI, I am removing all the issues related to the division usage to focus this issue on the one actual problem

**Comment by bryevdv** [comment]
ping @clairetang6 this might also be something worth looking into when you look at the other remaining log scale issue. I did just confirm this is still happening after the recent PRs.

**Comment by clairetang6** [comment]
ok! I will keep this on my radar. 

From an initial look, the rect glyph is defined by an x, y middle point and a height and width in data space and drawn with the parameters x0, y0, w, and h in screen space (sx0, sy0, sw, sh). sx0 and sy0 are calculated from sx and sy by sx0 = sx- sw/2 and sy0 = sy -sh/2. This won't work in log space because data values are not spaced equally in the two directions. The calculation of x0 needs to be done in data space and then it can be mapped to sx0.
