### ISSUE TITLE
how to draw a stacked bar with line in same page?

### ISSUE THREAD

**Issue by mudunzl** [bokeh/bokeh#5341]
The issue tracker isn't the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).

For defects or deficiencies, please provide:
* Description of expected behavior and the observed behavior
* Self-contained example code that generates the issue (if possible)
* Stack traceback and/or browser developer tools console output
* Software version information output by `bokeh info` command

For desired features, please provide:
* Description of the desired feature

**Comment by birdsarah** [comment]
The issue tracker isn't the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh)
