### ISSUE TITLE
Documentation: supporting JS str implementations of custom models

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5342]
When set as a string, the `__implementation__` attribute of a custom model expects coffeescript.  When writing a pure JS custom model, it's not possible to inline the JS implementation because Bokeh tries/fails to compile it. It would be nice to support an `__implementation_lang__` arg or similar.

**Comment by mattpap** [comment]
It is possible with:
```
from bokeh.utils.compiler import JavaScript
class Some(Model):
    __implementation__ = JavaScript("""
/* code here */
""")
```

**Comment by birdsarah** [comment]
Need to update http://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html#supplying-external-resources

And probably add further documentation around this.

**Comment by canavandl** [comment]
thanks @mattpap . @birdsarah I'll update my issue title to reflect the need for documentation

**Comment by bryevdv** [comment]
dupe of #7172 which I am adding docs for now
