### ISSUE TITLE
Embedding a server plot will override the window title

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5346]
![screen shot 2016-10-12 at 12 42 59 pm](https://cloud.githubusercontent.com/assets/2198981/19321040/6d0ff2bc-9079-11e6-8c26-ffde884896ac.png)

Embedding a server plot (using bokeh.embed.autoload_server, but I haven't tried other configurations including static plots) into a web page will override the window.title.

This should be configurable and off by default or not present.

**Comment by bryevdv** [comment]
I'm find with it just not setting the title on `autoload_server`

**Comment by bryevdv** [comment]
Added `MIGRATION` to note that browser titles are no longer set
