### ISSUE TITLE
net::ERR_INSECURE_RESPONSE for https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.css 

### ISSUE THREAD

**Issue by duerrp** [bokeh/bokeh#5350]
Expected behavior:
Bokeh plot loads as usual

Observed behavior:
Page stays blank, chrome's developer console says https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.css net::ERR_INSECURE_RESPONSE

Software version information output by `bokeh info` command:
Python version      :  2.7.12 (default, Jul  1 2016, 15:12:24) 
IPython version     :  5.0.0
Bokeh version       :  0.12.3
BokehJS static path :  /home/peter/.local/lib/python2.7/site-packages/bokeh/server/static

I assume something with the server configuration went wrong?

**Comment by ewjoachim** [comment]
Certificate for cdn.pydata.org expired at 2AM this morning.

**Comment by bryevdv** [comment]
The cert expired. This is being looked into this morning and will be resolved shortly. If this is the case,you could set the environment variable BOKEH_RESOURCES=inline to the local copy of BokehJS that ships with the library

**Comment by bryevdv** [comment]
Ultimately this was a people failure since there are multiple different organizations to coordinate. I have opened a discussion with all the relevant stakeholders to decide what processes we can put in place to protect against this happening again in the future.

**Comment by ewjoachim** [comment]
Pure curiosity, but is this discussion public ? Can you point to it ? Thank you :)

**Comment by bryevdv** [comment]
No it's just an email chain at the moment. I'll relay the outcomes when there are some.

**Comment by bryevdv** [comment]
The immediate issue should be resolved now please confirm

**Comment by bryevdv** [comment]
This has been resolved, I will be putting some notes about the SSL cert process in a wiki working document.

**Comment by duerrp** [comment]
Sorry for the delay. I can confirm it works now...
