### ISSUE TITLE
Document BOKEH_RESOURCES=inline in "Getting Set Up"

### ISSUE THREAD

**Issue by andresv** [bokeh/bokeh#5352]
I was trying out bokeh today and it did not work and there was no indication why it is so. Rendered plot was just blank.

@bryevdv said in gitter:

> there is currently a problem with the SSL cert for pydata.org Depending on the browser used, BokehJS will not load. This might be your problem. You can check the JS console as @AbelHeinsbroek suggests to confirm this. The IT folks are currently coordinating to get the certs re-established
> If this is the case, then in the mean time you could set the environment variable BOKEH_RESOURCES=inline to the local copy of BokehJS that ships with the library

It would be very good to document `export BOKEH_RESOURCES=inline` in http://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html#getting-started

**Comment by bryevdv** [comment]
I'm not sure about the Quickstart. The Bokeh CDN has only had two very short problems in ~4 years IIRC, so using `BOKEH_RESOURCES=inline` is definitely not the common case, and common is what I would expect in a quickstart. 

But a mention outside the dev guide would be nice for quick direct linking to, maybe in http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html ?

**Comment by bryevdv** [comment]
This is mentioned in a few places, now including 

https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html

I think that is sufficient
