### ISSUE TITLE
DateGapTickFormatter 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by dimon-st** [bokeh/bokeh#5357]
I'm trying to run a custom_datetime_axis ( https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/custom_datetime_axis.py ) on bokeh 0.12.3 and I get 

    261 
    262         if "error" in compiled:
--> 263             raise CompilationError(compiled.error)
    264 
    265         custom_impls[model.full_name] = compiled

CompilationError: <string>:DateGapTickFormatter:4:0:'import' and 'export' may appear only with 'sourceType: module'

---
Python version      :  2.7.12 |Anaconda 2.4.1 (64-bit)| (default, Jun 29 2016, 1
1:07:13) [MSC v.1500 64 bit (AMD64)]
IPython version     :  4.0.1
Bokeh version       :  0.12.3
BokehJS static path :  c:\anaconda2\lib\site-packages\bokeh\server\static

**Comment by bryevdv** [comment]
There are new changes in master. You need to run examples for your actual installed version.

**Comment by dimon-st** [comment]
Thanks
