### ISSUE TITLE
devdeps.py should include `nbformat` in developer dependencies

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#5358]
The [developer guide](http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-building-bokehjs) does not include `nbformat` in the developer dependencies but one of the tests, `bokeh/application/handlers/tests/test_notebook.py` requires this package.  It should also be added to `devdeps.py` test script.

**Comment by bryevdv** [comment]
@stvn66 I've been thinking maybe the best thing would be to auto generate a conda meta-package what has all the dev/test dependencies, directly from the `meta.yaml` then devs could just do e.g., `conda install -c bokeh bokeh-dev` or something. It would be nice to auto generate the list in the docs from the `meta.yaml` too.

**Comment by stvn66** [comment]
This sounds great.  It would avoid needing to update it as well.

**Comment by bryevdv** [comment]
I think I'm going to remove `devdeps.py` soon, in favor of something that interrogates the conda recipe directly.
