### ISSUE TITLE
Better deprecation path for extensions

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5360]
The recent switch to TS `import` in BokehJS will break existing extensions. Need one of the following:
- working but loud deprection (perhaps by automatically "fixing up" code if possible
- detection on the the python side and very load message with clear "fix-up" instructions

ping @mattpap comments?

**Comment by bryevdv** [comment]
Actually @mattpap I realized I may be completely off here, will the old `require` syntax also still work? If so this can be closed.

**Comment by mattpap** [comment]
@bryevdv, old syntax works, because new is compiled into the old one. However, there are still backwards incompatible changes, e.g. how models/views are imported, so this issue is valuable nevertheless.
