### ISSUE TITLE
Figure not resizing until browser is resized

### ISSUE THREAD

**Issue by alexbjorling** [bokeh/bokeh#5361]
With bokeh 0.12.3 (installed with pip), my figures aren't dynamically resizing. I've posted a description and code example as a [question on stackoverflow](http://stackoverflow.com/questions/39972162/dynamically-change-the-shape-of-bokeh-figure), but it seems more like a bug than a usage problem, so am posting here too just to draw attention to the issue.

Best,
Alex

**Comment by birdsarah** [comment]
Answered on SO.  I would suggest that you may want to open a new issue requesting the ability to trigger a document resize from server.
