### ISSUE TITLE
Notebook image diff tests broken due to "missing kernel"

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5375]
This seems to be some new jupyter notebook feature we need to account for in how we run during tests. 

<img width="625" alt="screen shot 2016-10-18 at 9 50 00 am" src="https://cloud.githubusercontent.com/assets/1078448/19483511/386d1936-951a-11e6-9ec5-a88e2ac54873.png">

ping @damianavila

**Comment by damianavila** [comment]
This is introduced by ourselves (not jupyter upstream), trough `nb_conda_kernels`, an nbextension creating  kernelspec on the fly pointing to your conda envs.

I don't remember the details of the image diff machinery... is it running on python2? Is it the only this ipynb failing or all of them are failing? Do you have any link to explore?

**Comment by bryevdv** [comment]
well it seems some of them are running now? 

https://s3.amazonaws.com/bokeh-travis/182676112/examples.html

I can't tell for sure, I'm not sure if left or right is current or expected (there's no logical reason it "should" be one or the other.. I will never be able to remember this without some kind of labeling)

**Comment by damianavila** [comment]
Latest runs I saw seems to work OK... for instance, https://s3.amazonaws.com/bokeh-travis/182947803/examples.html

**Comment by bryevdv** [comment]
@damianavila this is from today:

https://s3.amazonaws.com/bokeh-travis/183178428/examples.html

<img width="658" alt="screen shot 2016-12-12 at 11 12 16 am" src="https://cloud.githubusercontent.com/assets/1078448/21108757/e3af181e-c05b-11e6-8c96-3e6b0382703c.png">

**Comment by bryevdv** [comment]
Well, it's possible the left is "before" apparently, I don't actually know.

**Comment by bryevdv** [comment]
https://github.com/bokeh/bokeh/issues/5541

**Comment by bryevdv** [comment]
@damianavila According to @mattpap it is "current", "diff", "reference", which means the images on the left which are broken because of the startup dialog are in fact the "current" ones

**Comment by damianavila** [comment]
>@damianavila According to @mattpap it is "current", "diff", "reference", which means the images on the left which are broken because of the startup dialog are in fact the "current" ones

Thanks for the info!
