### ISSUE TITLE
Change palette references for the brewer qualitative palettes to be slices 

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#5376]
As discussed in pr #5359 and issue #5317, it would be better for redundant lists in `palettes.py` to be slices instead of repeating the list.

**Comment by bryevdv** [comment]
@StevenCHowell Did you intend to work on this? If not I might have someone else who could knock it out.

**Comment by StevenCHowell** [comment]
@bryevdv I just updated [palettes.py](https://github.com/bokeh/bokeh/blob/master/bokeh/palettes.py) but not [palettes.ts](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/api/palettes.ts) as I am less familiar with JavaScript.  Would the following be appropriate JS syntax:
```
export const Accent3     = Accent8.slice(:3)
export const Accent4     = Accent8.slice(:4)
export const Accent5     = Accent8.slice(:5)
export const Accent6     = Accent8.slice(:6)
export const Accent7     = Accent8.slice(:7)
export const Accent8     = [0x7fc97f, 0xbeaed4, 0xfdc086, 0xffff99, 0x386cb0, 0xf0027f, 0xbf5b17, 0x666666]
```
in place of 
```
export const Accent3     = [0x7fc97f, 0xbeaed4, 0xfdc086]
export const Accent4     = [0x7fc97f, 0xbeaed4, 0xfdc086, 0xffff99]
export const Accent5     = [0x7fc97f, 0xbeaed4, 0xfdc086, 0xffff99, 0x386cb0]
export const Accent6     = [0x7fc97f, 0xbeaed4, 0xfdc086, 0xffff99, 0x386cb0, 0xf0027f]
export const Accent7     = [0x7fc97f, 0xbeaed4, 0xfdc086, 0xffff99, 0x386cb0, 0xf0027f, 0xbf5b17]
export const Accent8     = [0x7fc97f, 0xbeaed4, 0xfdc086, 0xffff99, 0x386cb0, 0xf0027f, 0xbf5b17, 0x666666]
```

**Comment by bryevdv** [comment]
it's fine AFAIK but let's let @mattpap chime in when he can

**Comment by StevenCHowell** [comment]
Is there any issue with `Accent8` not being defined, or will `Accent7 = Accent8.slice(:7)` wait to execute until after `Accent8` is defined (similar to what is going on in the class definition of `palettes.py`)?
