### ISSUE TITLE
Make bokeh server posible to listen unix socket.

### ISSUE THREAD

**Issue by inakrin** [bokeh/bokeh#5383]
It could be very useful to run bokeh behind reverse proxy in  environments where only one port is available. (Heroku).

**Comment by bryevdv** [comment]
Please provide more elaboration. Example usage, etc.

**Comment by inakrin** [comment]
Well, heroku provides for each application only one port which is possible to use. If it was possible to bind bokeh on unix socket it would be possible use nginx as frontend proxy (proxying websocket requests to bohek, http requests to the webserver  backend), flask(or any other web-application) as webserver backend and bohek as plots backend.   
Flask is possible to bind on unix socket using gunicorn, but bohek can listen only tcp port for now.

**Comment by bryevdv** [comment]
@inakrin do you have a proposal for how this functionality would be exposed? What command would you want to be able to issue on the command line?

**Comment by inakrin** [comment]
I guess to keep compatibility  it should be another key. Something like bokeh server -b --bind unix://tmp/bokeh.sock  like gunicorn's key (http://docs.gunicorn.org/en/stable/run.html). But gunicorn supports also host:port argument for --bind. 
But client part also should be updated to be able connect to the socket.

**Comment by bryevdv** [comment]
@havocp any thoughts? Maybe just `--port` but I'm not sure how this would interact with any of the other command line args offhand

**Comment by havocp** [comment]
`--address` seems slightly more right than `--port` to me, with `--port` not permitted if `--address` has `unix:` in it ? 

Not sure what will need fixing for this to work, hopefully not too much stuff. I think we mostly get our base url from request.host which should still work.

**Comment by bryevdv** [comment]
yes, of course, that makes much more sense

**Comment by bryevdv** [comment]
@inakrin do you have any experience with network programming in python? If so, I'm happy to help you work up a PR, answer questions, etc. Just being realistic, that's probably the fastest route for this to get done, the core team is stretched incredibly thin at the moment.

**Comment by pitrou** [comment]
> Well, heroku provides for each application only one port which is possible to use.

Can you expand on this? Are you trying to run bokeh and nginx on the same machine? If so, using an arbitrary internal port should work.

**Comment by havocp** [comment]
It looks like Heroku may have changed behavior in 2013: https://blog.heroku.com/new_dyno_networking_model

**Comment by bryevdv** [comment]
If I read that correctly the "only one port" was the *old* behaviour? In which case I am inclined to close this issue.

**Comment by bryevdv** [comment]
Given the lack of feedback, and In light of 

> The new dyno networking model brings us closer to that goal: The dyno no longer imposes any restrictions on what ports an application can listen on. This improves out-of-the box compatibility with application frameworks that listen on multiple ports (for whatever reason). You can still only connect from the outside world to the port specified in the $PORT environment variable, but now you don't have to painfully reconfigure your web stack to stop it from listening on other ports.

I agree this can be closed. I believe the solution is as described above, to use an internal port on the private side of the proxy, possibly with some URL port mapping by nginx, should cover all the bases.
