### ISSUE TITLE
Small docs fixes

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#5384]
In addition to the typo fixed by #5378, there are other typos in the comments of the examples for the [styling documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html).  I am happy to go through and aggregate a list of the errors (documented here), then fix these.  These are the three I saw so far
- [ ] Background example says `# create a new plot with a title`
- [ ] Border example says `# create a new plot with a title`
- [ ] Outline example says `# create a new plot with a title`
- [ ] typos in `0.12.2` migration notes #5190
- [ ] docstring for `Histogram` should mention bin size (see: https://github.com/bokeh/bokeh/issues/3398)

**Comment by bryevdv** [comment]
@StevenCHowell fixing lots of small things in one PR sounds better than lots of small PRs so I am +1 on keeping this issue open as a place to collect small typos, etc for a while then fixing them all at once.
