### ISSUE TITLE
Legend labels expand keys even when not preceded by @

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#5385]
It appears that the parser of the legend label is a bit overzealous at the moment, it will replace labels that match dictionary names even when not preceded by an @ symbol. This leads to legends that are labeled by plot values, rather than the desired label name. As an example, in the plot below  the green points should be labeled by the letter `y`, which happens to match the `y` key in the `ColumnDataSource`.

<img width="485" alt="screenshot 2016-10-19 13 29 29" src="https://cloud.githubusercontent.com/assets/4998058/19530032/1fde25ea-9600-11e6-97b3-3737d79b880f.png">

```Python    
p1.circle(
    'x',
    'y',
    source=sources[-1],
    color=bandcolorf(band),
    fill_color="white",
    legend=bandname,
    size=4)
```

If I replace the letter `y` with something else that doesn't match any `ColumnDataSource` keys (in this case a capital `Y`), the label appears correctly:

<img width="491" alt="screenshot 2016-10-19 13 34 20" src="https://cloud.githubusercontent.com/assets/4998058/19530180/c1b4df12-9600-11e6-8595-88cc46d4a650.png">

**Comment by birdsarah** [comment]
This is new, but documented behavior: http://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#legends

"It is also possible to create multiple legend items for the same glyph when if needed by passing a legend that is the column of the column data source."

"If you do not want this automatic behavior, you can use the field() or value() functions from bokeh.core.properties, to be explicit about your intentions. See examples/app/gapminder/main.py for an example. Alternatively, you can not specify any legend argument, and manually build a Legend by hand. You can see an example of this in examples/models/legends.p"

**Comment by bryevdv** [comment]
This is a new feature to help generate legends more easily with less code when a single data source has groups of data. You can do one of two things:

* make the legend label and the column name differ (e.g. rename the column)
* use `legend=value('foo')` to be explicit that you don't want the auto grouping

**Comment by birdsarah** [comment]
Good looking graph btw @guillochon

**Comment by guillochon** [comment]
I guess I'm confused why the `@` notation was abandoned, wasn't that the common way of specifying a variable beforehand? Also, if I use `value('food')`, will all points be ungrouped?

**Comment by birdsarah** [comment]
The `@` notation is for HoverTool tooltips. It's never been used for Legend labels. Not sure where you got this notion.

**Comment by guillochon** [comment]
Sure, but there was no ability to include plot values in legend labels before. I would have thought it would adopt the same parsing convention as the tooltips, given that they are very similar. It would also be more flexible in the sense that you could format the legend labels (e.g. `y = my_y_values`).

By the way, what is the difference between `field` and `value`, if any?

**Comment by birdsarah** [comment]
Sorry, that we didn't call it out better.

value is an explicit value. field is an explicit CDS field.

So to get your thing working:

```python
from bokeh.core.properties import value
...
p.circle(legend=value('y'))
```

or i'm often lazy and don't use public api and do this:

```python
...
p.circle(legend={'value': 'y'})
```

**Comment by bryevdv** [comment]
@guillochon There are specific properties on some Bokeh models called `DataSpecs` These are generally used for thing can (but don't have to) be vectorized. Think of the `x` and `y` coordinates for `Circle`. You have have `x=10` (a value) or `x="some_column"` (a field). In the vast majority of cases, Bokeh can and will figure this out automatically, so we have not have to say much about it generally. But It's possible to be explicit, and that is what `field` and `value` do.

**Comment by guillochon** [comment]
Great, thanks @bryevdv and @birdsarah! Closing since my main issue was addressed.

**Comment by birdsarah** [comment]
@bryevdv and I are having an issue answering competition today :D
