### ISSUE TITLE
Clean up BEPs and migrate to Google docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5386]
The BEP process was created early on, intended as a means to govern major changes to the library. However, it may have been put in place too early. Almost all the current "BEP"s are not in intended sprit of a full proposal, commented on by a community. Rather they are more like scratch working documents without concrete suggestions. The lack of commentary is also probably due to the fact that the GH wiki is not suitable at all for collaborative editing and commenting. 

However, after `1.0`, a robust BEP process becomes much more important. But I think the existence of the "not-really-BEPs" puts the whole process in a confusing light. So, I propose the two immediate changes:
- Delete all current BEPs after BEP-2, i.e. start with a "clean slate"
- Migrate BEPs to Google docs

ping @bokeh/dev for discussion.

**Comment by damianavila** [comment]
I agree with your proposal.

**Comment by bryevdv** [comment]
Well, I have done the clean up part. I think rather than move existing BEPs to gdocs, the Wiki can be a place for final versions. New BEPs, if ever there are any, can be collaborated on gdocs before acceptance (or a PR I suppose) Accordingly, I am closing this.
