### ISSUE TITLE
The data are displayed but not the line

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#5394]
The line display when **source** is not there but as soon as i add **source** it disappears, only the data point are present
![screen shot 2016-10-22 at 1 03 47 pm](https://cloud.githubusercontent.com/assets/23002446/19622168/31866fb4-9858-11e6-84a5-060848d0d29f.png)

![pyjtoct20_1](https://cloud.githubusercontent.com/assets/23002446/19622178/8a7163a4-9858-11e6-996a-bef64a2ade4c.png)

pl = figure(plot_width=900, plot_height=650, title="JT Change",
                       tools="pan,wheel_zoom,box_zoom,crosshair,reset,hover,previewsave", x_axis_type="datetime")

            x=[]
            y= []

            for i in range(0,50):
                x.append(i)
                y.append(i)

            source = ColumnDataSource(data=dict(x=x,y=y, xm=xm, frqwrdtm=frqwrdtm))
            val1 = 'together'  # set first time
            l1 = 'together'

            def callback1(source=source):
                dat = source.get('data')
                val = cb_obj.get('value')
                x,y,xm, frqwrdtm = dat['x'],dat['y'],dat['xm'], dat['frqwrdtm']
                if val == 'children':
                    for i in range(0, 50):
                         y[i] = i+3 # frqwrdtm[2][i]
                        
                source.trigger('change')

            slctt21 = Select(title="Most Used Word 1:", value=val1,options=mstwrd, callback=CustomJS.from_py_func(callback1))
            slctt22 = Select(title="Most Used Word 2:", value=val, options=mstwrd)
            slctt23 = Select(title="Most Used Word 3:", value=val, options=mstwrd)

            wdgts1 = WidgetBox(slctt21)
            wdgts2 = WidgetBox(slctt22)
            wdgts3 = WidgetBox(slctt23)

            pl.line('x','y', legend='l1',line_color="tomato", line_width=2, source=source) 
            #pl.line(x=xm, y=frqwrdtm[0], legend='l1', line_color="tomato", line_width=2, source=source1)
            #pl.line(x=xm, y=frqwrdtm[1], legend=wrdfrqtm[1], line_color="blue", line_width=2)
            #pl.line(x=xm, y=frqwrdtm[2], legend=wrdfrqtm[2], line_color="limegreen", line_width=2)
            #pl.circle('x','y', fill_color='white', size=6)#, source=source1)
            pl.xaxis.major_tick_line_color = "firebrick"
            pl.xaxis.major_tick_line_width = 3
            pl.xaxis.minor_tick_line_color = "orange"
            pl.legend.location = "bottom_right"

            l3 = row([column([wdgts1,wdgts2,wdgts3]), pl])
            tab3 = Panel(child=l3, title='Change')
            # --------------------------------
            tabs = Tabs(tabs=[tab1, tab2, tab3])
            show(tabs)

I use
 r = plot_kmeans.circle('x','y', source=source)
in tab1 and it works with no problem.
I am using 0.12.3. I tried a lot of other configurations with the same missing line for now when I add **source**.

Pierre

**Comment by Pierretherenard** [comment]
I am going to write this code with no tab, clean of everything and report back

**Comment by Pierretherenard** [comment]
This is were I am:
frqwrdtm is a list of list. 
After having cleaned the "code" above the line display correctly. If i use something like
 source = ColumnDataSource(data=dict(x=x,y=y, z=z)) 
with z being one list this is working, same size of course as x and y. But if i have a list of list, the line does not display at all when source is 
source = ColumnDataSource(data=dict(x=x,y=y, frqwrdtm=frqwrdtm)).
I understand I could be writing z1, z2,z3,...,zx but that will not work. So my question is ,
is it possible to pass a list of list or a matrix to source?

Thank you

**Comment by Pierretherenard** [comment]
yes i can pass a list of list, going back to some other code, this is what I did...humm ok let me try something else

**Comment by Pierretherenard** [comment]
by doing this, the issue is fixed:
            for j in range(0,3):
                zd = []
                for i in range(0,len(xm)):
                   zd.append(frqwrdtm[j][i])
                z.append(zd)
                
            source1 = ColumnDataSource(data=dict(x1=x1, y1=y1, z=z))

May be some guru can let me know what the the difference between z(working) and frqwrdtm(not working), same data?

frqwrdtm = []
        fw1 = []
        fw2 = []
        fw3 = []
        wrdfrqtm = ['together','diversity','children']
        txtcurrent = [] # this will append the txt

        mdf = 1
        for txt in trnd:
            txtcurrent.append(txt)
            if len(txtcurrent) >= 3:
                vcttf = TfidfVectorizer(min_df=3, max_features=maxftr) # change min_df number
                vf = vcttf.fit_transform(txtcurrent)
                tfidf = dict(zip(vcttf.get_feature_names(), vcttf.idf_))

                if wrdfrqtm[0] in tfidf:
                    fw1.append(tfidf[wrdfrqtm[0]])
                else:
                    fw1.append(0)

                if wrdfrqtm[1] in tfidf:
                    fw2.append(tfidf[wrdfrqtm[1]])
                else:
                    fw2.append(0)

                if wrdfrqtm[2] in tfidf:
                    fw3.append(tfidf[wrdfrqtm[2]])
                else:
                    fw3.append(0)
            else:
                fw1.append(0)
                fw2.append(0)
                fw3.append(0)
        frqwrdtm.append(fw1)
        frqwrdtm.append(fw2)
        frqwrdtm.append(fw3)

Thank you

**Comment by bryevdv** [comment]
@Pierretherenard I'm afraid it is a bit difficult to parse your comments. GitHub supports marking code sections so that they are formatted properly. Can you please go back and edit the comments to properly format code, then I can comment?

**Comment by Pierretherenard** [comment]
I updated the marking. I hope this is what you wanted.

Thank you,
Pierre

**Comment by Pierretherenard** [comment]
Thank you for all the hard work. have fun, Pierre

**Comment by bryevdv** [comment]
@Pierretherenard As a gentle suggestion that would be helpful to the project, if you self-close an issue please indicate why

**Comment by Pierretherenard** [comment]
i know you don't want comment here after it is closed but i edited the code above and it did work, this is why i closed it. Thank you to let me know.

**Comment by bryevdv** [comment]
@Pierretherenard thanks for the info, it's useful to know because we have automated scripts for generating changelogs and such, and for them to work, all issues have to be tagged and labeled correctly according to our system. I only commented now because I only noticed it just now.
