### ISSUE TITLE
Please consider adding classifiers to setup.py

### ISSUE THREAD

**Issue by GadgetSteve** [bokeh/bokeh#5395]
For desired features, please provide:
* Many python packages provide classifiers in setup.py - these allow people browsing on [pypi](https://pypi.python.org/pypi?%3Aaction=browse), to locate packages that are suitable for their use by filtering on the licence, programming language, topic, intended audience, OS & so on.  A list of current classifiers can be found [here](https://pypi.python.org/pypi?%3Aaction=list_classifiers).

I would suggest adding at least the licence, platform, topic and intended audience classifiers, note that classifiers can be added multiple times, i.e. you could have all of the following classifiers:
```
Intended Audience :: Education
Intended Audience :: End Users/Desktop
Intended Audience :: Financial and Insurance Industry
```

**Comment by bryevdv** [comment]
There are far more conda package downloads of Bokeh than PyPI downloads, so as a result, I can't say this would be high priority, at least not to me. If you think it is important, we'd certainly consider a PR. That said, I'm not sure if the above ones are just meant to be for demonstration, but I don't think they are especially accurate, in the sense that they are far too limited and I would not at all want to give the impression that those were the *only* intended audiences.

**Comment by GadgetSteve** [comment]
@bryevdv it is entirely possible that, apart from the ease of installation of conda, the reason that there aren't more pypi downloads is that people aren't finding bokeh on there when browsing due to the lack of classifiers. Those tags given were indeed intended as an example not an exhaustive list of what would fit bokeh.

**Comment by bryevdv** [comment]
I find that explanation unlikely, but as I said, PRs are always welcome.

**Comment by GadgetSteve** [comment]
I would suggest the following list of classifiers:

Intended Audience :: Developers
Intended Audience :: Education
Intended Audience :: End Users/Desktop
Intended Audience :: Financial and Insurance Industry
Intended Audience :: Healthcare Industry
Intended Audience :: Information Technology
Intended Audience :: Legal Industry
Intended Audience :: Other Audience
Intended Audience :: Science/Research
License :: Freely Distributable
License :: OSI Approved :: BSD License :: 3 Clause New or Revised
Topic :: Office/Business :: Financial
Topic :: Scientific/Engineering :: Information Analysis
Topic :: Scientific/Engineering :: Visualization
Programming Language :: Python :: 2
Programming Language :: Python :: 3
Programming Language :: JavaScript

**Comment by GadgetSteve** [comment]
[PR](https://github.com/bokeh/bokeh/pull/5396) Raised.
