### ISSUE TITLE
FuncTickFormatter.from_py_func() example ValueError

### ISSUE THREAD

**Issue by EP-Guy** [bokeh/bokeh#5404]
I am trying the FuncTickFormatter.from_py_func() example and I get the error
`ValueError: Function 'func' may only contain keyword arguments.`

A MWE that produces this error is:
```
from bokeh.models import FuncTickFormatter
from bokeh.plotting import figure, show
import math

def ticker(tick):
    return math.floor(tick) + " + " + (tick % 1).toFixed(2)

p = figure(plot_width=400, plot_height=300)
         
p.yaxis.formatter = FuncTickFormatter.from_py_func(ticker)

p.circle([2, 4, 6], [1, 3, 5])

show(p)
```

I am running Bokeh version 0.12.3 and have flexx installed.

**Comment by birdsarah** [comment]
I'm not sure whether this'll work with `from_py_func` - have you seen an example of it working somewhere. ping @canavandl.

**Comment by EP-Guy** [comment]
This is actually based on the example given in the Bokeh user guide http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#functickformatter

**Comment by birdsarah** [comment]
Wow! I actually went to that example, but missed the `from_py_func` underneath.....tired eyes.

Those particular docs examples aren't spitting out plots so it seems like they're broken.

Thanks for the report.
