### ISSUE TITLE
"Hover" tool shows incorrect (and meaningless) information 

### ISSUE THREAD

**Issue by PanWu** [bokeh/bokeh#5405]
I loaded the classic Titanic data, and trying to plot a Bar chart, however, the "hover" tool shows some information that doesn't make any sense. I feel this might be a bug. Can anyone help with this? 

My system is Mac OS, with following packages
Python 2.7.12, 
Bokeh 0.12.3
jupyter (1.0.0)
jupyter-client (4.3.0)
jupyter-console (4.1.1)
jupyter-core (4.1.0)

<img width="510" alt="screen shot 2016-10-24 at 11 38 22 pm" src="https://cloud.githubusercontent.com/assets/7094433/19675403/006f184e-9a43-11e6-83d8-e45c4bf7a6cf.png">

**Comment by birdsarah** [comment]
It's not a bug, you just haven't configured the tooltips. Please ask support questions on the mailing list: https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by PanWu** [comment]
@birdsarah 

Thanks for the fast respond. However, I searched in the forum and didn't find the answer: the tutorial cannot be opened, and  even the example shown in the "bokeh/gallery" has this issue (incorrect hover), as shown below. Could you help with this one?

<img width="663" alt="screen shot 2016-10-25 at 8 13 02 am" src="https://cloud.githubusercontent.com/assets/7094433/19691931/e646c4c4-9a8a-11e6-9b1a-92744d98d2b1.png">

Thanks,

**Comment by bryevdv** [comment]
This is a dupe of #4861
