### ISSUE TITLE
Document x_axis_location parameter to figure

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5411]
It is not in reference guide: http://bokeh.pydata.org/en/latest/docs/reference/plotting.html

It also does not appear as a list of options when you mis-guess an option (presumably because it's not an actual property).

**Comment by bryevdv** [comment]
All the non-property kwargs that `figure` accepts could be documented better. I'd like to automate the process somehow, though (maybe some decorator that attaches some kind of specification for those args, together with help strings for them, to the function)

**Comment by birdsarah** [comment]
Or even something simple to start with like the "deprecated properties" attribute?

**Comment by bryevdv** [comment]
No half measures. Incoming on other `sphinxext` improvement PR:

<img width="721" alt="screen shot 2016-10-26 at 9 35 12 pm" src="https://cloud.githubusercontent.com/assets/1078448/19752591/40b7d4f4-9bc4-11e6-9b2d-5037b0269a88.png">

**Comment by bryevdv** [comment]
We should re-use `Options` for the charts config, and also for the messy server config.
