### ISSUE TITLE
Barplot legend displayed by default 

### ISSUE THREAD

**Issue by Distue** [bokeh/bokeh#5412]
Dear Bokeh Developers,

I would like to discuss the (changed) default behaviour of displaying the legend in the barplot of Bokeh. Currently, the legend seems to be displayed by default even if there is only data source as shown below:

[![bokeh-legend.png](http://s9.postimg.org/3rsb7sn8f/bokeh_legend.png)](http://postimg.org/image/obx56a2zf/)
(from http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html)

Technically this is wrong, because all labels have the same colour. Also, the legend is redundant, as the x-axis already displays the labels. 
This behaviour breaks the first four example plots of the tutorial http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html 

Therefore I would like to suggest to change the default behaviour for displaying the legend in the barplot to either False or even better to only display it when it makes sense (more than one color / type).

Best,
Tom

**Comment by birdsarah** [comment]
I agree. I'm not sure if this has always been like this or is a corner case we didn't consider when we updated the legends in the last release.

**Comment by Distue** [comment]
We saw a change of the default behaviour in the latest releases.

Please also consider this for Boxplots.

Thanks for your great work.

**Comment by bryevdv** [comment]
@Distue the original image link is now broken, can you edit the original issue an drag/drop the image into it so that it is persistent?

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/4)
