### ISSUE TITLE
Can't use categorical axis with figure using rects

### ISSUE THREAD

**Issue by will-emmerson** [bokeh/bokeh#5413]
I have the following code to draw a heatmap, one row for each parameter:

```
params = ['end_brick', 'comms']
date_range = [df['date'].min(), df['date'].max()]
source = ColumnDataSource(df)

p = figure(
    x_axis_type="datetime", x_range=date_range, y_range=params,
    tools='xpan, xwheel_zoom, reset, save, resize, hover', width=800, height=300,
)

for i, par in enumerate(params):
    p.quad(left='start', right='end', bottom=i, top=i + 1,
           color={'field': par, 'transform': cmaps[par]}, source=source)
```

The data looks like this:

```
        date  end_brick    comms  period               start                    end                          
0 2016-10-26       95.6  99.3333       1 2016-10-26 00:00:00  0 2016-10-26 08:00:00                            
1 2016-10-26       75.0  98.8889       3 2016-10-26 08:00:00  1 2016-10-26 16:00:00                            
2 2016-10-26       58.7  96.6667       5 2016-10-26 16:00:00  2 2016-10-27 00:00:00                            
3 2016-10-27       80.1  98.3333       1 2016-10-27 00:00:00  3 2016-10-27 08:00:00                                             
```

It works but as soon I go to zoom in or out, it disappears and the console error is:

```
Uncaught Error: Number property 'start' given invalid value: end_brick(…)
```

The graph works fine when I use y_range=(0, len(params)) but then I lose labels.

The same bug happens with other charts e.g. http://bokeh.pydata.org/en/latest/docs/gallery/boxplot_chart.html

It also happens with zoom_in and zoom_out tools.

**Comment by birdsarah** [comment]
Thanks for the report @will-emmerson. Just to clarify. The box zoom is working for me, but the wheel zoom is a mess - is that the same as what you're seeing.

Futhermore - reset is behaving oddly. Plot appears small and then gets bigger when you hit reset.

**Comment by will-emmerson** [comment]
Reset is working fine for me but I agree with everything else.

**Comment by RutgerK** [comment]
Maybe the reset is an issue specific to the example gallery? Related to how the plots are embedded in the page? I dont see it with my own plots in the notebook, only in Bokeh's gallery.

**Comment by Rubyj** [comment]
I am having the same issue with Violin plots and figures using vbars. When I try to wheel zoom the whole figure starts disappearing and moving.

**Comment by bryevdv** [comment]
@Rubyj can you try out the PR I just made?

**Comment by Rubyj** [comment]
@bryevdv Sure. Give me a few to build from source and I will let you know.

**Comment by Rubyj** [comment]
@bryevdv Just tested your PR. Fixes for wheel zoom on my violin plots and vbar figs

**Comment by bryevdv** [comment]
Great, it will be merged and in a dev build soon

**Comment by bryevdv** [comment]
Thanks everyone!
