### ISSUE TITLE
Extend TextInput with `placeholder` and `pattern`

### ISSUE THREAD

**Issue by busino** [bokeh/bokeh#5417]
`placeholder` and `pattern` are nice features in HTML to give the user info about the field and to validate the user-input.

Add `placeholder` and `pattern` to `TextInput` in python, extend `text_input.coffee` and the `text_input_template.eco`

**Comment by busino** [comment]
Just started to work on a PR.
`placeholder` works just fine - no problem.

But there is a big problem with `pattern`. 
In standard HTML the input is highlighted in red if user entered wrong values. This can be styled with `input:invalid`. But this is not working in `bokeh_js`. Everytime `value` is changed the input is rendered freshly. The `invalid` state gets lost (I think).
If I disable `@model.value = value` here: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/text_input.coffee#L35 
the highlighting works fine.

What is the motivation to render the input every time the value is changed?

**Comment by bryevdv** [comment]
I'm not sure offhand, re-rendering might be an unintended mistake. The `model.value = value` should be there, because that's what causes e.g. callbacks in a bokeh server to trigger when the value changes. But it might be a mistake to have that also trigger a re-render. What above removing this line instead: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/text_input.coffee#L22

**Comment by busino** [comment]
I'll give it a try.

**Comment by busino** [comment]
@bryevdv 

It only works if I comment L22 and L20
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/text_input.coffee#L20

`super(options)` is calling `initialize` from `LayoutDOM` which does:
```
bind_bokeh_events: () ->
    @listenTo(@model, 'change', @render)
```

I really don't know if this is a good idea. I'm not familiar with the code and `coffee` is absolutely new for me.
I'm happy to help improve things, but I don't want to waste to much of your precious time.
If there is a **JS/coffee-Master** around to decide if it's okay to remove these lines!
I can test and make a PR.

**Comment by bryevdv** [comment]
ping @birdsarah any quick thoughts? It seems like an input widget should not need to re-render on every model change. Should that line be in `LayoutDOM`? It seems maybe subclasses should be able to decide to do that or not

**Comment by bryevdv** [comment]
@busino if `placeholder` is working fine, why don't you work up a PR for just that first? And we will figure out the other part over time.

**Comment by bryevdv** [comment]
@busino can you make a separate issue (linking this one) for `pattern`?

**Comment by busino** [comment]
New issue created.
