### ISSUE TITLE
Not support python2?

### ISSUE THREAD

**Issue by iteratorlee** [bokeh/bokeh#5419]
The issue tracker isn't the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).

For defects or deficiencies, please provide:
* Description of expected behavior and the observed behavior
* Self-contained example code that generates the issue (if possible)
* Stack traceback and/or browser developer tools console output
* Software version information output by `bokeh info` command

For desired features, please provide:
* Description of the desired feature

**Comment by bryevdv** [comment]
Hi, please read and respect the guidelines for submitting issues, shown above. The issue tracker is reserved for feature requests and bug reports *only*. All general support questions (such as this one) should be directed to the public mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

For the record however, we test extensively and continuously on on python 2.7. No claims of compatibility are made for earlier versions of python.
