### ISSUE TITLE
It is not possible to set a Range1d with datetime.timedelta value

### ISSUE THREAD

**Issue by sanderroosendaal** [bokeh/bokeh#5426]
I am plotting a series of datetime.timedelta values on one of the axes of my chart. I am trying to constraint the axes minimum and maximum by: 

    yrange1 = Range1d(start=datetime.timedelta(minutes=1,seconds=45),end=datetime.timedelta(minutes=3,seconds=30))

plot.y_range = yrange1

Got the following: 

Exception Type:	ValueError
Exception Value:	
expected an element of either Float, Datetime or Int, got datetime.timedelta(0, 210)

Bokeh version 0.12.3
Python version 2.7.12

**Comment by bryevdv** [comment]
@mattpap is this a regression? I feel like timedelta's used to validate as floats?

**Comment by mattpap** [comment]
@bryevdv, it does validate as float, but what sense does it make to set bounds of an interval to a delta? `Range1d`'s `start` and `end` properties are defined as `Either(Float, Datetime, Int)`.

**Comment by mattpap** [comment]
It may have sense to allow `plot.x_range = timedelta(1, 20)`.

**Comment by bryevdv** [comment]
I think that is what the intention is, i.e. an axis that represents differences in time. But it seems that timedelata is not validating as float?

@sanderroosendaal can you provide a complete minimal test case that demonstrates the problem, at that can be run as-is, with no modification?

**Comment by sanderroosendaal** [comment]
@bryevdv Will do but not before tomorrow. Difficult to extract from my current django code to something clean, self-contained and concise. 

Basically, I have a pandas DataFrame where one of the columns is a pace (time/500m). I want the axis limits to always be between 1:40/500m and 3:30/500m, if the user selects to plot this column. The data have some much larger values. 
The pace column is a timedelta column. 

There are several ways to work around this, so feel free to drop the issue, but I just felt it should be possible to define axes ranges in timedelta.

**Comment by sanderroosendaal** [comment]
@bryevdv Here is an example 

[bokeh_timedelta.zip](https://github.com/bokeh/bokeh/files/563526/bokeh_timedelta.zip)

**Comment by sanderroosendaal** [comment]
Got it. You have to write the Range1d in milliseconds. Might be good to add a comment in the documentation.

**Comment by bryevdv** [comment]
Well, I'd suggest that it can and should be converted automatically, but let's wait for @mattpap to get back

**Comment by bryevdv** [comment]
I just noticed that timedelta types are processed in some of the same code paths as datetime types. As has been clarified in other discussions, this is not really appropriate. AFAIK there is nothing user visible about this, but it would be nice to clean this up internally as part of a PR to fix this.

**Comment by bryevdv** [comment]
Although I just noticed your referenced commit @miccoli , does that suffice to fix?

**Comment by bryevdv** [comment]
@miccoli I'd also like to apologize in advance for closing this with essentially the same commit. I normally am very fastidious about offering PRs to anyone else first, but I have to travel tomorrow and will be gone most of the week. In the interest of getting a fix to you and other users in a dev build as quickly as possible I went ahead and made the changes in the other combined PR.

**Comment by miccoli** [comment]
@bryevdv no need to apologise: my  miccoli/bokeh@0545753 is really trivial, so I do not claim any birthright or PR-right on this ;-) Far better to have the bug fixed as quickly as possible.

**Comment by gregmuellegger** [comment]
Thanks @bryevdv for fixing this. I just stumbled upon the same problem and can confirm that 1.0.0dev4 fixes it! Great work!
