### ISSUE TITLE
Extend TextInput with `pattern`

### ISSUE THREAD

**Issue by busino** [bokeh/bokeh#5434]
References to this issues #5417 #5433 

Check if we can add html5 input attribute `pattern` to `TextInput`-Widget.
This will improve user-entries e.g. for datetime, floats or text string like IP-addresses and so on.
But there seems to be an issue with the `TextInput`.  Change of the value is triggering a re-rendering on every value change.
@birdsarah any thoughts about re-rendering the widget on every value change.

If you can give feedback on this I'm willing to create a PR.

Thanks for the help.
Raphael

**Comment by bryevdv** [comment]
@busino I have an idea to try. The problem seemed to be a blanket event change handler:
```
@listenTo(@model, 'change', @render)
```
in `LayoutDom` here: 

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/layouts/layout_dom.coffee#L56

Propose narrowing the event handling in `LayoutDOM` to *only* the properties actually on `LayoutDOM` (the way it is currently written it will respond to subclass properties AFAIK, which is the problem. 

The four props on `LayoutDOM` are here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/layouts/layout_dom.coffee#L253-L256

So you'd want to make individual lines like:
```
@listenTo(@model, 'change:height', @render)
```

Then, in the input widget, you can delete just the `listenTo` in `initialize` and I think it will work as we want.

**Comment by busino** [comment]
I'll have a look...

**Comment by bryevdv** [comment]
@busino are you still interested in having a look at this issue?

**Comment by busino** [comment]
Hi Bryan,

Sorry, but I was covered with a lot of other work.
But let me try to fix it this or the next week. If this will not happen, 
you can close
the issue (in my point of view).

Raphael

**Comment by bryevdv** [comment]
@busino  I think this is a valuable change to make. There's no big hurry, my intention with asking was to give you the opportunity to make a Pull Request yourself, if that is something you are interested in doing, before working on it myself.

**Comment by busino** [comment]
Ah, that's very nice.

I'll send a PR as soon as possible.

Raphael

**Comment by busino** [comment]
Hey Bryan,

I was working on a fix but at the moment I'm really out of time to create a PR.
Feel free to fix the issue.
Thanks for your help and patience.

Raphael

**Comment by bryevdv** [comment]
Moving this out of `0.12.5` After some investigation this seems a bit more work, and also the property is not support at all in some common browsers like safari, will have to re-evaluate whether to pursue.

**Comment by busino** [comment]
Hi Bryan,
This is really a "nice to have feature".
At the moment I don't have the resources for a PR. 
But I think it would be nice if some one can have a look at the rendering going on on every value change.

Please feel free to close or to put it into the backlog.

Thanks for your commitment.

Raphael

**Comment by bryevdv** [comment]
GIven that this is not supported in all browsers and there has not been wider interest expressed, I will close this with no action.
