### ISSUE TITLE
x_axis_type = 'datetime' produces incorrect scale under certain circumstances (bokeh 0.12.3)

### ISSUE THREAD

**Issue by rsgoodwin** [bokeh/bokeh#5436]
The following code produces and plots a pandas time series with 16 regular week intervals starting from 2016-07-24 and ending 2016-11-06.  The datetime scale is improperly rendered and displayed.   Here is the code to reproduce the issue.  

```
# imports & config
import pandas as pd
import numpy as np
from bokeh.plotting import figure, show, output_notebook

output_notebook()

# create a times series dataframe
rng = pd.date_range('2016-07-24', periods=16, freq='W')
df = pd.DataFrame(np.random.randn(len(rng)), index = rng, columns=['Y'])

# view the tail of the data to compare to plot
df.tail()

# make and render the plot
p1 = figure(x_axis_type='datetime',
        title='Y vs Week Ending',
       plot_width=700, plot_height=400)

p1.xaxis.axis_label = 'Week Ending'
p1.yaxis.axis_label = 'Y'
p1.line(df.index, df['Y'])
p1.circle(df.index, df['Y'])
p1.yaxis.minor_tick_line_alpha=0

show(p1)
```
The first image shows the raw plot with points rendered on the x-axis after the max datetime in the data (bug).   

Also,  as a suggested improvement on the default behavior,  when plotting a  time series and treating datetime as a numeric,  continuous variable,  the scale jumps (distance between major ticks) should calculated to be of uniform size.   i.e.  we may expect scales to be drawn at 1,  3 , 7,  10 day intervals (constant number of days),   or 1, 2,  4 week intervals (also constant size).    Same for hours,  mins or seconds.  We would not plot a continuous datetime series that renders the scale interval to be "the 15th day of each month",  as that is no longer a uniform date time size (some months have more days than others).  The exception may be year scale data where it is generally acceptable to plot year as an interval if the data spans multiple years (and due to leap years,  there is a differing number of days).

One way to satisfy the variety of approaches would be to enable an option to plot datetime in an x-y plot as an ordinal (not continuous)  variable.   In this case,  each point is plotted with equal spacing relative the the previous point,  and tick labels are either all points (small number of data),  or every nth point to fill (but not overfill) the space.

![pre-zoom](https://cloud.githubusercontent.com/assets/2280241/19934677/bfc1968a-a0d4-11e6-88dd-aa3cefa29c94.png)
![post_zoom](https://cloud.githubusercontent.com/assets/2280241/19934678/c1fcd590-a0d4-11e6-8b4a-f66476eb3421.png)

This was originally posted as a question on stackoverflow:
http://stackoverflow.com/questions/40363802/bokeh-how-to-properly-set-control-xaxis-for-datetime-possible-bug

**Comment by patricktokeeffe** [comment]
> the last scale tick is for Nov 16, and there is a point aligned to what appears to be several days after that.

That tick is for Nov **20**16.. it's not very intuitive, but the year is contracted into the label.

Knowing this may change your perspective w.r.t. this comment:

> ...I really think the scale increments should be in equal number of days. However in this case, Bokeh plots the scale increments to be on the same day of [each] month...

What it's done is change the base unit from *day* to *month*, which is probably the more correct approach.

----
Copy of [my answer](http://stackoverflow.com/a/40732870/2946116) on SO.

**Comment by azjps** [comment]
You can change the tick labels by setting a [format string](http://bokeh.pydata.org/en/latest/docs/reference/models/formatters.html#bokeh.models.formatters.DatetimeTickFormatter) [default is `%b%y`] so that the year is confused as a day. I believe you can tinker with on what time scale the ticks bin from days to months via [datetime ticker](http://bokeh.pydata.org/en/latest/docs/reference/models/tickers.html#bokeh.models.tickers.DatetimeTicker), but that's just based on a skim of the docs.

**Comment by bryevdv** [comment]
Marking as a `discussion` until a concrete proposal emerges

**Comment by bryevdv** [comment]
Closing as stale, since no proposal ever surfaced. There are many ways to customize ticking:

* configurable formats on default axis
* day/month/week tickers
* custom tickers
* custom tick formatters
* functickformatter

There's now any number of ways to get exactly what ticking you want  wrt ticking.
