### ISSUE TITLE
x_axis_type = 'datetime' with incorrect scale

### ISSUE THREAD

**Issue by Corleo** [bokeh/bokeh#5444]
The millisecond scale shows 0ms when time is multiple of 1000ms instead of showing something like 1.0s (second.millisecond). 

The error can be reproduced by following code:
```python
from math import sin, pi
from bokeh.plotting import figure, curdoc

x = ["%4.3f" % i for i in range(0,2600,50)]
y = ["%0.6f" % sin(2*pi/2000*float(i)) for i in x]

tools = "xwheel_zoom,xwheel_pan,reset,save"
p = figure(plot_width=600, plot_height=300, tools=tools, active_scroll='xwheel_zoom', x_axis_type="datetime")
p.line(x, y)

curdoc().add_root(p)
```
![bokeh_plot](https://cloud.githubusercontent.com/assets/9902249/20048915/ecee1482-a4a6-11e6-9961-01badf289894.png)

Adding this code
```python
p.xaxis[0].formatter.milliseconds = ['%S.%1Ns']
```
solves this problem but it makes the scale fixed and when zooming in it creates another problem:
![bokeh_plot 1](https://cloud.githubusercontent.com/assets/9902249/20049302/69d9c4f8-a4a9-11e6-80fe-b7e2c538a235.png)

and using '%S.%3Ns' makes the scale noisy. This format is useful only when zooming in.

**Comment by bryevdv** [comment]
Well the first weird thing is that you are passing lists of strings. I would first say that the fact that that seems to work in any capacity is an unintended accident, and I would caution not to rely on it. 

The next observation is that it's important to remember that every value in the context of a datetime axis is a ***date***time. It important to note that a value like `500` is not just `500ms` it's "500ms past the epoch start date" And if you zoom out some you'll see that it starts to print data values when it can (as intended): 

<img width="355" alt="screen shot 2016-11-07 at 11 12 54 am" src="https://cloud.githubusercontent.com/assets/1078448/20067531/28681fba-a4db-11e6-82cf-30cc17d815f8.png">

If you have small time-only values (i.e. tracking measurements in some experiment, say) then that is probably not what you want. So then my real suggestion is that the `DatetimeTicker`  is probably not the best choice. But then the question of what would be better is more of a general support question, which really belongs on the mailing list, not the tracker.

**Comment by Corleo** [comment]
Hi, bryevdv, thank you for the quick answer. 

I haven't paid attention on that string lists. I made them this way because I was trying in first place to make a plot with seconds using float numbers like 1.002011, since after a period the time is base 10. But with this format I got 1000us scale. When I multiplied the values by 1e3 I got this strange millisecond scale with 0ms at ticks multiples of 1000ms.

And this also happens with propper datetime data plot, as this can be viewed zooming in the Bokeh's [Datetime Axes](http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#datetime-axes) exemple:

![bokeh_plot](https://cloud.githubusercontent.com/assets/9902249/20085284/e09f2452-a54e-11e6-90bf-13ac23f8fc6e.png)

I thought it was an odd behaviour and created this GH issue with 'bug' label in mind but somehow the label 'discussion' was created instead.

And indeed I'm working on small time-only values tracking measurements. I used DatetimeTicker because it's a really awsome feature and it's already done, but you are right when saying that DatetimeTicker isn't the best choice. It would be something like TimeTicker. 

Later I'll follow your suggestion and open a support question on the mailing list.

Thank you, bryevdv.

**Comment by bryevdv** [comment]
It's possible this will be re-labeled, but until an actual course of action is decided upon, `discussion` is most appropriate.

**Comment by bryevdv** [comment]
The default datetime scale is intended to work "generally well" across a wide range of time scales. But it can't satisfy every need. At this point there are many options for customization when the defaults are not suitable:
* configurable formats on the default axis
* custom tickers
* custom tick formatters including easy `FuncTickFormatter` 
* tick overrides

one of these is the proper path at this point.
