### ISSUE TITLE
If main.py is run by bokeh serve, warn about running with directory name instead

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5445]
Lots of reports of people running, e.g.
```
bokeh serve --show crossfilter/main.py
```
Which prevents all the features of "directory style" apps from being enabled.

**Comment by mattpap** [comment]
How are you going to distinguish if user intended `main.py` to be part of a "directory style" app or a standalone script? I presume only by name, so maybe instead of warning about this lets make
```
bokeh serve --show crossfilter
```
and
```
bokeh serve --show crossfilter/main.py
```
eqivalent. Unless I miss something here obviously.

**Comment by bryevdv** [comment]
I'm not sure it's simple to do that reliably, unfortunately.

**Comment by bryevdv** [comment]
Here is the current code:
```
    if os.path.isdir(path):
        handler = DirectoryHandler(filename=path, argv=argv)
    else:
        if path.endswith(".ipynb"):
            handler = NotebookHandler(filename=path, argv=argv)
        elif path.endswith(".py"):
            handler = ScriptHandler(filename=path, argv=argv)
        else:
            raise ValueError("Expected a '.py' script or '.ipynb' notebook, got: '%s'" % path)
```
Are you proposing something like:
```
    if os.path.isdir(path):
        handler = DirectoryHandler(filename=path, argv=argv)
    else:
        if path.endswith("main.py"):
            handler = DirectoryHandler(filename=basename(path), argv=argv)
        if path.endswith(".ipynb"):
            handler = NotebookHandler(filename=path, argv=argv)
        elif path.endswith(".py"):
            handler = ScriptHandler(filename=path, argv=argv)
        else:
            raise ValueError("Expected a '.py' script or '.ipynb' notebook, got: '%s'" % path)
```
?

I think that could break fairly badly for a `main.py` that *wasn't* part of a directory app (and how could we possibly tell the difference for sure) and I think it would have to be more annoyingly complicated to hand just `bokeh serve main.py` successfully too. I'd rather just warn on any path that ends with `main.py`, and give instructions how to run directory apps correctly.
