### ISSUE TITLE
Crashes on custom tools with coffeescript

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#5458]
I was getting 500 errors from my Bokeh server application for a while.  I was not getting any feedback in server logs or the browser developer console about what was going wrong (although my application does muck around a bit with logs, so this could be my fault).  

Bisecting lead me to the recent addition of a custom tool.  This tool includes custom coffeescript.  My user machine didn't have coffeescript so it's reasonable that this failed.  I can see two solutions to this:

1.  Provide a way to pre-compile coffeescript code to javascript when building my package and custom tool
2.  Provide loud error messages that the user needs to install a minimum version of nodejs

**Comment by bryevdv** [comment]
due of #5345
