### ISSUE TITLE
Multiselect height

### ISSUE THREAD

**Issue by Paradoxeuh** [bokeh/bokeh#5462]
Hi,

I am trying to change the height of a multiselect widget with no success so far. Is it something that can be done?

Cheers

**Comment by Paradoxeuh** [comment]
Adding this in the html <style> helped me. It could be good if I didn't have to manually change my html ;)

.bk-root select[multiple], .bk-root select[size] {
            height: 400px;
          }

**Comment by Paradoxeuh** [comment]
Adding this in the html helped me.

**Comment by SamDM** [comment]
Still a problem today, setting the height property of the `MultiSelect`:

```
pheno_select = MultiSelect(title="phenotype:", value=[],  options=[...])
```
Results in:
![image](https://user-images.githubusercontent.com/11174777/31959335-b09faa0a-b8f4-11e7-810f-e60aa92527af.png)

So the widget grows but the selection area remains too small.

**Comment by bryevdv** [comment]
Please provide a complete, minimal script to reproduce the issue.

**Comment by SamDM** [comment]
Ok, the following code

```
from bokeh.layouts import row, widgetbox
from bokeh.models.widgets import Button, MultiSelect
from bokeh.plotting import output_file, show, figure

multi_select = MultiSelect(title="issue5462:",
                           value=[],
                           options=["entry {}".format(x) for x in range(10)],
                           height=300)
button = Button(label="The space above is not filled by the Multiselect",
                button_type="success")

plot = figure(height=400, title=None)
plot.circle('x', 'y',
            source={'x': [x for x in range(10)], 'y': [x*x for x in range(10)]})

layout = row(widgetbox(multi_select, button), plot)

output_file("issue5462.html")
show(layout)
```
This yields:
![image](https://user-images.githubusercontent.com/11174777/31994911-a9101ce6-b982-11e7-9c39-17c7d7e6d21f.png)

Bokeh: 0.12.7
Python: 3.6
Browser: Firefox version 55.0.3 (64-bit)
Os: Manjaro Linux

**Comment by mattpap** [comment]
This is by design. Sizing accurately a multi select DOM element is not possible, so we leave its sizing to a web browser. You can manually set the number of visible items by setting `MultiSelect.size`, but the resulting element height is browser dependent and does't relate to widget height. There may be room for improvement here, but the best (and most expensive) option is to implement a multi select widget that doesn't depend on `<select>` element.

**Comment by SamDM** [comment]
> You can manually set the number of visible items by setting MultiSelect.size
That's actually what I was looking for, and it's actually in the docs, oops.

**Comment by bryevdv** [comment]
Thanks @SamDM glad you found what you needed
