### ISSUE TITLE
Titles over layouts a la "suptitle"

### ISSUE THREAD

**Issue by olavurmortensen** [bokeh/bokeh#5463]
This issue is in regard to a feature I would like to see in bokeh.

It would be nice to be able to make a title over a layout, similar to PyPlot's [suptitle](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.suptitle). For example, I make two figures `p1` and `p2` and then use `p3 = Row(p1, p2)`. Now `p1` and `p2` have their own titles, but there is no title over the entire plot.

In my opinion, this is an essential functionality to have in a plotting environment. I found some "hack" that was supposed to let you do it, but I couldn't even make it work.

**Comment by mattpap** [comment]
This should actually work with `gridplot()`, which currently ignores `title` property (see #1449). `Row` and `Column` are more generic elements of bokeh's layout system and they shouldn't carry additional content. We could, however, introduce a new layout model, lets say, `Panel`, which would have a `title` property, but this would boil down to `Column(children=[Label(text=title), Row(children=[plot1, plot2])])` anyway. I presume this is the "hack" you were talking about? If you have a code that is supposed to work, but doesn't, you can publish it here (or in a gist) and we may be able to help you sooner than a proper fix is implemented (which may take awhile).

**Comment by olavurmortensen** [comment]
`gridplot` doesn't have that effect for me. My code is below.

```
p1 = figure(title="Offline", x_axis_label='Time (sec)', y_axis_label='Bound')
p1.circle(offline_time[1:], offline[1:], size=5, color='red')
p1.plot_height=400
p1.plot_width=300

p2 = figure(title="Online 1 iter", x_axis_label='Time (sec)', y_axis_label='Bound')
s1 = p2.circle(online_1iter_time[1:], online_1iter[1:], size=5, line_color='green')
p2.plot_height=400
p2.plot_width=300

p3 = figure(title="Online 10 iter", x_axis_label='Time (sec)', y_axis_label='Bound')
s3 = p3.circle(online_10iter_time[1:], online_10iter[1:], size=5, line_color='blue')
p3.plot_height=400
p3.plot_width=300

p4 = gridplot([[p1, p2, p3]], toolbar_location='below')

show(p4)
```

and it produces the following graph:

![grtidplot](http://i.imgur.com/IG3S2HV.png)

Furthermore, the toolbar, even though it is connected to the gridplot object, downloads each graph separately instead of the entire plot in one image.

**Comment by bryevdv** [comment]
>  downloads each graph separately instead of the entire plot in one image. 

The plots are on separate HTML canvases, this is a technical limitation that will be hard to lift. There are ideas for how to possibly accomplish, but they will probably not happen in the short-term.

There isn't a picture at the suptitle link provided, I still don't understand what exactly is being asked for.

**Comment by olavurmortensen** [comment]
@bryevdv What I want is a title over the entire subplot, like in [this image](http://i.stack.imgur.com/u4Ecl.png), the "Long suptitle" text.

**Comment by bryevdv** [comment]
layout + `Div` seems to work

<img width="794" alt="screen shot 2016-11-16 at 11 57 49 am" src="https://cloud.githubusercontent.com/assets/1078448/20356956/21b1a2a2-abf4-11e6-9d6a-e561a5a6e28b.png">

----

As mentioned earlier, the individual plots are on separate HTML5 canvases, so this is probably the best solution that can be expected.

**Comment by bryevdv** [comment]
Of course one benefit of this is that you can style the div with HTML, CSS easily:

<img width="768" alt="screen shot 2016-11-16 at 12 04 26 pm" src="https://cloud.githubusercontent.com/assets/1078448/20357171/e7bcea7e-abf4-11e6-9ccc-89ce1632d7e9.png">

**Comment by olavurmortensen** [comment]
@bryevdv That's pretty good, thanks. How do I center the text though? `<center>` doesn't work, probably because its depricated in HTML5.

**Comment by bryevdv** [comment]
@olavurmortensen I am afraid I am not a CSS expert, so I can't really help. Since this is now more of a general support question, I am going to close (please use the mailing list for general support)

**Comment by eromoe** [comment]
Any simple way to add backgroud and center title ?
The pic is ugly under dark jupyter . 
![image](https://user-images.githubusercontent.com/3938751/66448512-568a5600-ea84-11e9-901f-02c813d0160a.png)

**Comment by bryevdv** [comment]
@eromoe certainly, but that is a support question so the appropriate venue is the project Discourse, not GitHub:

https://discourse.bokeh.org
