### ISSUE TITLE
Docstring not reflecting correct function signature.

### ISSUE THREAD

**Issue by sphinxligustri** [bokeh/bokeh#5467]
https://github.com/bokeh/bokeh/blob/master/bokeh/io.py#L572

Docstring references invalid function call. 

is: push_notebook(handle)
should be: push_notebook(handle=handle)

tag: docs

**Comment by bryevdv** [comment]
Hi @sphinxligustri I notice there is a PR referenced above, just FYIranch  it looks like you've made a PR from your branch to *your master branch* in your fork. For us to merge, you just need to make a PR from your branch to the master branch of *this* repo, i.e. `bokeh/bokeh`
