### ISSUE TITLE
Document that BoxZoomTool does not work on GMapPlot

### ISSUE THREAD

**Issue by duerrp** [bokeh/bokeh#5469]
* Description of expected behavior and the observed behavior:
Using the box zoom tool on GMapPlot, expect it to change the current view to the range selected by zoom tool. However, the view does not change
* Self-contained example code that generates the issue (if possible):
This is not self-contained (sorry), but here's how I use the tool
```
    plot = GMapPlot(x_range=DataRange1d(),
                    y_range=DataRange1d(),
                    map_options=map_options,
                    title="Foo",
                    api_key="Bar")
    plot.map_options.map_type = "hybrid"
    source = ColumnDataSource(
        data=dict(
            lon=foobar.lon,
            lat=foobar.lat,
        ))
    circle = bokeh.models.Circle(x="lon", y="lat")
    plot.add_glyph(source, circle)
    zoom = bokeh.models.WheelZoomTool()
    plot.add_tools(bokeh.models.PanTool(),
                   zoom,
                   bokeh.models.BoxZoomTool())
    plot.toolbar.active_scroll = zoom
    plot.title = "FooBar"
```
* Stack traceback and/or browser developer tools console output:
`bokeh-0.12.3.min.js:7 [bokeh] setting log level to: 'info'`
* Software version information output by `bokeh info` command:
```
Python version      :  2.7.12 (default, Jul  1 2016, 15:12:24) 
IPython version     :  5.0.0
Bokeh version       :  0.12.3
BokehJS static path :  /home/peter/.local/lib/python2.7/site-packages/bokeh/server/static
```

**Comment by bryevdv** [comment]
Unfortunately the box zoom tool is incompatible with `GMapPlot` for reasons outside our control. Google maps insist on controlling and maintaining aspect ratio at all times, do not allow setting the region boundary arbitrarily. 

However, we could warn and possibly automatically remove box zoom tools on gmap plots so that there isn't a non-functional tool present.
