### ISSUE TITLE
[ENH] Allow wrapping plots and widgets into custom DIV without compromising layouts functionality

### ISSUE THREAD

**Issue by cloud-rocket** [bokeh/bokeh#5470]
Creating complex dashboard with multiple charts in which each plot is complemented with few custom interaction widgets (buttons/scrolls) is almost impossible without supplemental html helpers.

It should be possible to put custom DIV around group of widgets/plots/layouts 

The ticket follow preliminary discussion:
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/3Kvf0N_6MrQ

**Comment by bryevdv** [comment]
@cloud-rocket how is this different from #5471?

**Comment by bryevdv** [comment]
In addition to the issue above, this should be covered by #7708 But closing for lack of response/information in any case.
