### ISSUE TITLE
Can callback on 1 widget apply to another widget?

### ISSUE THREAD

**Issue by dnaura** [bokeh/bokeh#5473]
Hello,
I can not manage to update a select widget options with an other widget slider for example.
If I have a table with 'x' and 'value' columns, a slider widget for 'x' and a select widget for 'value, and if I  want to filter table with 'x' higher than 10 for example, the datatable will be updated and also the plot  if any, but not the select widget. It will keep alll possible values in its options.
Maybe it is impossible to do it.
Can someone confirm?
Thanks.
David

**Comment by bryevdv** [comment]
The GitHub tracker is reserved for bug reports, feature requests, and development related discussion. Please take general support questions to the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
