### ISSUE TITLE
Use static file with bokeh serve

### ISSUE THREAD

**Issue by Paradoxeuh** [bokeh/bokeh#5483]
In the documentation I've seen that you can define a static folder in your bokeh serve folder.
"A static subdirectory that can be used to serve static resources associated with this application."
How do you load those static file ? I thought that flask was behind bokeh serve so I used "url_for" method to load my bootstrap.css but it crashes saying : 
UndefinedError: 'url_for' is undefined

Am I missing something here?

Thanks in advance for your answer

**Comment by Paradoxeuh** [comment]
For now, the only solution I found to include static files is

+app
----+templates
--------+css
------------custom.css
--------index.html

You can import "custom.css" with {% include 'css/custom.css'%} in "index.html.

**Comment by bryevdv** [comment]
You can make a static subdir under app/ that will be available as app/static and is served by tornados ststic file handler.

**Comment by bryevdv** [comment]
also just for future reference, general support questions should always go to the public mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

so that the issue tracker may be reserved for bug reports and feature requests
