### ISSUE TITLE
Custom grid lines with tiles and GIS data

### ISSUE THREAD

**Issue by BuggyMcBugFace** [bokeh/bokeh#5485]
I'd like to plot GIS data with a map background and meaningful axes (latitude, longitude).  

There are plenty of examples using data converted to Web Mercator projection (https://anaconda.org/amcinnes/crafter-map-locations/notebook) with tiles added in the background.  These examples all turn off grid lines because meters from lat, lon = (0,0) is useles to an end user.  GMapPlot will render with latitude and longitude, but isn't truly open source and currently doesn't even work in the user guide (http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html).

Is there a way to transform coordinates in the axes from Web Mercator projection to latitude and longitude (or better yet, any other arbitrary transform)?

**Comment by bryevdv** [comment]
Hi, 

The issue tracker is reserved for bug reports and feature requests and development-related discussions. For general support, please always use the public mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

where there is larger audience of potential people who can answer, and also where responses are better stored for future reference.

**Comment by bryevdv** [comment]
Also just FYI Google maps now requires an API key to function at all. This is outside our control. GMaps work just fine when a key is provided, but our previous docs infrastructure was not set up to provide a key in a way that could not just be "copy and pasted" and used by anyone. The latest dev docs have been updated and the plot displays as expected:

http://bokeh.pydata.org/en/dev/docs/user_guide/geo.html
