### ISSUE TITLE
(BAD_COLUMN_NAME): Glyph Reference Error

### ISSUE THREAD

**Issue by notslar-ralston** [bokeh/bokeh#5489]
Running the below bit of code:

```python
        else:

            unis = data[segby].unique()
            cmap = listed_color_map(len(unis))

            for i, uni in enumerate(unis):

                sdf = data.loc[data[segby] == uni]
                aggdf = sdf.groupby(group).agg(aggby)

                fig.line(x=aggdf.index.values,
                         y=aggdf[key].values,
                         legend=("%s: %s | %d %s" % (segby, str(uni), sum(aggdf[key].values), key)),
                         line_width=3.0,
                         alpha=0.6,
                         line_color=cmap[i])

        if xlims[k]:
            fig.set(x_range=Range1d(xlims[k][0], xlims[k][1]))
        if ylims[k]:
            fig.set(y_range=Range1d(ylims[k][0], ylims[k][1]))

        tab = Panel(child=fig, title=group)
        tabs.append(tab)

    plot_tabs = Tabs(tabs=tabs)
    show(plot_tabs)
```

And I'm getting this ```BokehError: attempted to retrieve property array for nonexistent field ''``` in my browser, and this in the console:

```python
ERROR:/Users/ralston/Projects/tqpy/venv/lib/python3.5/site-packages/bokeh/core/validation/check.py:E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name:  [renderer: GlyphRenderer(id='0d1ae966-c1aa-41a2-b1f1-0017d7837b1b', ...)]
```
If I run this code 3 times, it will work the first 2 times, and then throw an error the 3rd time. The data is right, and I have no idea how it can work _perfectly_ one time, then turn around and throw an error the next time.

Is this some type of bug in the check.py module?

Using ```bokeh (0.12.3)``` on a Chrome browser.

**Comment by bryevdv** [comment]
The error check code is extremely simple. It's saying that the value that was set for a glyph property is an empty string. 

First guess is that `cmap[i]` is getting set to the empty string somehow elsewhere in your code. However, please first turn to the public mailing list for general support. If it is determined that something is truly a bug, then an issue can be opened for it at that time. If you can confirm that `cmap[i]` is not the empty string when the error message occurs, please feel free to re-open. But not that without a complete runnable example to reproduce what you are seeing it will be difficult or impossible to look into.
