### ISSUE TITLE
Support --port 0 for random port

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#5492]
Sometimes we don't know a port that will be open apriori and we want a service to take a random open port.  The convention here is to specify port 0.  Bokeh currently reports the port as 0 when doing this:

```
mrocklin@workstation:~/workspace/bokeh$ bokeh serve examples/app/crossfilter/ --port 0
2016-11-29 10:27:45,282 Starting Bokeh server version 0.11.0dev2-4074-g9c73877-dirty
2016-11-29 10:27:45,285 Starting Bokeh server on port 0 with applications at paths ['/crossfilter']
2016-11-29 10:27:45,285 Starting Bokeh server with process id: 9766
```

It would be nice for it instead to select a random open port and report that port instead.  Tornado servers (and Python sockets generally) will follow this convention if you just call `TCPServer.listen(0)` or whatever.

**Comment by mrocklin** [comment]
OK, it looks like we're passing in port=0 as we should.  We probably need to just change the port attribute on the server object after we listen rather than before.

Here is a way to get the port from the server:

    >>> list(sa.server._http._sockets.values())[0].getsockname()[1]
    34874

**Comment by bryevdv** [comment]
@mrocklin it sounds like you already have an idea of the necessary changes, perhaps you could submit a quick PR

**Comment by mrocklin** [comment]
I do something like the following in my code:

```python
+++ b/bokeh/server/server.py
@@ -94,6 +94,7 @@ class Server(object):
         if 'port' in kwargs:
             self._port = kwargs['port']
 
+        # TODO: This fails to propogate port info to hosts if port==0
         tornado_kwargs['hosts'] = _create_hosts_whitelist(kwargs.get('host'), self._port)
         tornado_kwargs['extra_websocket_origins'] = _create_hosts_whitelist(kwargs.get('allow_websocket_origin'), self._port)
         tornado_kwargs['use_index'] = kwargs.get('use_index', True)
@@ -131,7 +132,7 @@ class Server(object):
 
     @property
     def port(self):
-        return self._port
+        return self._port or self._http._sockets.values())[0].getsockname()[1]
```

Note that handling zero ports means that Bokeh's whitelisting will fail if someone provides a hostname.  It might also be worth relaxing `_create_hosts_whitelist` to operate on any port if `port==0`
