### ISSUE TITLE
Avoid calling sys.exit in server code

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#5493]
Currently the server calls sys.exit if it can't find a good port.  If Bokeh intends to serve non-command-line applications (which I think it should) then it should probably raise here instead and handle the exception in the command line tool.

    bokeh/server/server.py::Server.__init__

**Comment by pitrou** [comment]
Formally, `sys.exit(...)` just raises `SystemExit`, so we could still catch that. But I agree that calling sys.exit doesn't make the error conditions very clear...
