### ISSUE TITLE
Document non-script and programmatic use 

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#5495]
When embeding Bokeh Server within other applications the standard bokeh script and command line interface may not be optimal.  However, scripts and command line are also the common case, and so rightfully dominate documentation.

It might be nice to have a small document detailing how to use Bokeh Server programmatically.  

To help myself with this I created this small minimal bokeh server example:

```python
# Create Tornado IOLoop
from tornado.ioloop import IOLoop
loop = IOLoop()


# Construct Bokeh Plot and Column Data Source
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

source = ColumnDataSource({'x': [], 'y': []})

plot = figure(title='my title')
plot.circle(source=source, x='x', y='y')

# Create simple Bokeh server application
from bokeh.application.handlers import FunctionHandler
from bokeh.application import Application

import random
def update():
    source.stream({'x': [random.random()],
                   'y': [random.random()]})

def modify_doc(doc):
    doc.add_periodic_callback(update, 100)
    doc.add_root(plot)

handler = FunctionHandler(modify_doc)
app = Application(handler)


# Construct and start Bokeh server around application
from bokeh.server.server import Server
server = Server({'/': app}, io_loop=loop, port=5000)
server.start(start_loop=False)


# Start everything
loop.start()
```

In particular I like that I get to specify and start the IOLoop myself. I like that the plot and data source are separate from the server. I like that I don't have to construct a script but can just use the FunctionHandler. I was very happy to find the FunctionHandler by the way. I suspect that I'll rewrite all of the dask web UI using this rather than using scripts.

**Comment by bryevdv** [comment]
Examples and a user guide section were previously added.
