### ISSUE TITLE
files hosted on `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [bokeh/bokeh#5496]
Hi, I'm from cdnjs. We want to provide CDN service of your lib, we already provide v0.9.3, v0.10.0 and v0.11.0 on https://cdnjs.com/libraries/bokeh. Still many version are not added, so we want to use `npm auto-update` to add every version on npm package automatically. 
And I want to confirm what files should be hosted on cdnjs.
I'm going to add files under `build` or `release`, can I only add the minfied files and its sources?
thank you!

https://github.com/cdnjs/cdnjs/issues/6745

**Comment by bryevdv** [comment]
Hi @maruilian11 It's certainly up to you whether you'd like to supply the un-minified files. Bokeh configures the minified versions by default, but users can override this preference. Please be aware that Bokeh is also been split into multiple components, and that that there is still probably more work yet to come in this direction. In particular there is currently also `bokeh-widgets` and `bokeh-api`

**Comment by bryevdv** [comment]
Closing, unless there are additional questions, then feel free to re-open

**Comment by maruilian11** [comment]
thank you, we will discuss it in cdnjs.
