### ISSUE TITLE
Is bokeh npm package installable?

### ISSUE THREAD

**Issue by stefanv** [bokeh/bokeh#5500]
When trying to install bokeh via npm, I see:

```
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/jquery' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'bokehjs'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

Also, does Bokeh really need to depend on jquery?  We specifically avoid that dependency in our project, and it's not immediately obvious why BokehJS needs it.

Other errors spotted:

```
npm ERR! code E404
npm ERR! not a package /tmp/npm-8724-K0tFZp42/github.com/bokeh/numbro.git
```

**Comment by mattpap** [comment]
@stefanv, `npm install bokehjs` should work fine. This was actually fixed in last release. npm is very unreliable, so I suggest to repeating install after some time, it usually helps with this kind of errors. Otherwise, this may be related to node/npm version. It would be helpful if you could provide this.

**Comment by mattpap** [comment]
> Also, does Bokeh really need to depend on jquery?

It does. We use jquery for DOM manipulation in core bokehjs, widgets (jquery-ui), etc. However, besides increasing size of bokehjs, it shouldn't affect your environment as jquery is included as a private dependency ("no conflict" in jquery's terms). We try to keep bokehjs as little obtrusive to the hosting environment as possible, so the only global change you should see is `Bokeh` global namespace. This particular failure isn't even related to jquery itself, but to jquery's typings required for our TypeScript API.

**Comment by bryevdv** [comment]
@stefanv This seems to be working fine for me:
```
[bryan:~/work/bokeh]$ npm install bokehjs                                                                                         (bryanv/5479_gridplot_tools)
/Users/bryan/work/bokeh
└─┬ bokehjs@0.12.4-dev8
  ├── @types/es6-promise@0.0.32
  ├── @types/hammerjs@2.0.33
  ├── @types/jquery@2.0.34
  ├── @types/jquery-mousewheel@3.1.5
  ├── @types/jqueryui@1.11.31
  ├── @types/proj4@2.3.2
  ├── @types/rbush@2.0.2
  ├── @types/sprintf@0.0.28
  ├── @types/timezone-js@0.0.28
  ├── @types/underscore@1.7.36
  ├── es6-promise@3.0.2
  ├── font-awesome@4.7.0
  ├── hammerjs@2.0.8
  ├── jquery@2.2.4
  ├── jquery-mousewheel@3.1.13
  ├── jquery-ui@1.10.5
  ├── numbro@1.6.2  (git+https://github.com/bokeh/numbro.git#b4ccab0574b07077d003590a5881a75df28ac723)
  ├─┬ proj4@2.3.15
  │ └── mgrs@0.0.3
  ├─┬ rbush@2.0.1
  │ └── quickselect@1.0.0
  ├─┬ root-require@0.3.1
  │ └── packpath@0.1.0
  ├── sprintf@0.1.5
  ├── timezone@1.0.6
  └── underscore@1.8.3
```

If you are still experiencing problems, please re-open with additional information (platform, versions, exact commands used, etc)

**Comment by stefanv** [comment]
Thanks, @bryevdv.  I'll try again: like @mattpap mentions, npm is quite brittle, so it could be packages in the cache etc.  I'll do a clean start.

**Comment by stefanv** [comment]
@bryevdv @mattpap Have you seen this before?

```
$ npm install bokehjs
npm WARN package.json jquery-form@3.50.0 No repository field.
npm ERR! fetch failed https://github.com/bokeh/numbro.git#b4ccab0
npm ERR! fetch failed https://github.com/bokeh/numbro.git#b4ccab0
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/es6-promise' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'bokehjs'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.6.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "bokehjs"
npm ERR! cwd /home/stefan/projekte/cesium/cesium_web
npm ERR! node -v v4.3.1
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! not a package /tmp/npm-26910-rRnd95_x/github.com/bokeh/numbro.git
```

```
$ npm --version
1.4.21
```

```
$ uname -a
Linux carbo 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux
```

**Comment by mattpap** [comment]
@stefanv, `types/es6-promise` install fine for me. Either this was a temporary nodejs.org's failure or usage of very outdated node/npm caused this. I recommend using node 6.x (LTS, comes with npm 3.x). This what bokeh depends on and what we use for development. node 4.x was a source of constant issues.

**Comment by mattpap** [comment]
Actually, there is also numbro failing in that log, so this must be node 4.x's fault. You can install most recent version from `conda-forge` channel (and possibly `bokeh`).

**Comment by stefanv** [comment]
Thanks, @machinelearningdeveloper It's quite frustrating that the npm system is so brittle :/  Maybe I'll look into yarn.
