### ISSUE TITLE
GridPlot layout lost after "Reset" (in Jupyter inline plotting)

### ISSUE THREAD

**Issue by tbezemer** [bokeh/bokeh#5501]
I use an n x 3 (row x col) grid plot layout to plot a varying number of plots on the same page in Jupyter. When I use the zooming tool to view certain details of one of the plots, I usually click the reset button afterwards, to return to the initial view.

When I press reset on the toolbar in a grid plot view (at least in Jupyter notebook) the plots are not re-rendered in the original grid plot layout, but rather stacked one after the other. Also, the plots do not retain their initially set size (300x300 pixels).

Some pictures below (My apologies - I am working on a 13" MacBook and I currently do not have access to a bigger, higher resolution screen, so the view is clipped).

**The initial (desired) view:**
![schermafbeelding 2016-12-02 om 11 04 45](https://cloud.githubusercontent.com/assets/8499859/20830100/45a9e862-b87f-11e6-84f4-7f0361ffc4b4.png)

**The view after 'reset':**
![schermafbeelding 2016-12-02 om 11 05 01](https://cloud.githubusercontent.com/assets/8499859/20830099/45a935ac-b87f-11e6-9369-0077586f14cd.png)
**.. and scrolled down a little**
![schermafbeelding 2016-12-02 om 11 05 09](https://cloud.githubusercontent.com/assets/8499859/20830098/458c820e-b87f-11e6-9253-c2ff7be2ebcc.png)

**Comment by bryevdv** [comment]
This has to do with charts getting their width and heigh configured in a different way. Need to make sure `plot_width` and `plot_height` are also set.

**Comment by bryevdv** [comment]
closing, `bokeh.charts` is gone.
