### ISSUE TITLE
bokeh doesn't play well with `pip install -e`

### ISSUE THREAD

**Issue by pitrou** [bokeh/bokeh#5510]
`pip install -e .` is very useful when working from a git checkout. Unfortunately, this doesn't play well this Bokeh's setup.py: the setup.py asks a question and waits for user input, but the question is hidden in the default `pip` verbosity level, leading to assume that the script has hanged.

Furthermore, when you solve this issue with `pip install -vvv -e .`, the whole JS-building process is done twice: once for the underlying `build`, once for `install`.

**Comment by bryevdv** [comment]
I doubt there is much that can be done. The Bokeh build is a large multi-language one that builds two different libraries for two different runtimes. If there are concrete suggestions we can certainly discuss them, though.

**Comment by bryevdv** [comment]
Closing, absent any additional feedback
