### ISSUE TITLE
Consider externalizing font-awesome's icons (or removing altogether)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5513]
Currently `bokeh-widgets.min.css` is at 524 kB. Externalizing icons reduces this to 220 kB and removing font-awesome entirely reduces size to 181 kB.

**Comment by bryevdv** [comment]
+1 the icons are not regularly used AFAIK, if they can be shipped only when needed (or indeed if they are not needed) that's great.

**Comment by birdsarah** [comment]
I think they'd be an excellent candidate for a bokeh org maintained plugin/extension as opposed to part of core.

Sarah Bird
sbird@continuum.io
