### ISSUE TITLE
Excessive cpu load on Raspberry Pi

### ISSUE THREAD

**Issue by donour** [bokeh/bokeh#5521]
I am experiencing spurious, high cpu usage on Raspberry Pi 3 hardware in all hosted applications. This includes includes the sample apps from the main repo.

On my four core ARM raspberry pi 3, three of the cores are are pegged at 100% after initial page load. CPU usage stays the same, even after the session times out. I have included profile info below, but it looks like the process is busy-waiting on the tornado poll function.

I experience this behavior for the 0.12.3 release in Raspbian and my own build from the current head. I _cannot_ replicate the behavior on x86. 

* numpy-1.11.something
* tornado-4.4.2

Here is the output from python's cProfile.run()
--

2016-12-09 04:33:48,117 Starting Bokeh server version 0.12.3
2016-12-09 04:33:48,180 Using develop mode (do not enable --develop in production)
2016-12-09 04:33:48,182 Starting Bokeh server on port 5006 with applications at paths ['/racepi_bokehapp']
2016-12-09 04:33:48,184 Starting Bokeh server with process id: 5116
2016-12-09 04:33:54,656 200 GET /racepi_bokehapp (192.168.11.10) 3885.27ms
2016-12-09 04:33:54,969 WebSocket connection opened
2016-12-09 04:33:54,971 ServerConnection created

Interrupted, shutting down
         1271481 function calls (1081323 primitive calls) in 304.084 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      445  290.588    0.653  290.588    0.653 {method 'poll' of 'select.epoll' objects}
   288360    1.278    0.000    1.401    0.000 {isinstance}
        9    0.936    0.104    0.936    0.104 {method 'execute' of 'sqlite3.Cursor' objects}
41853/2740    0.834    0.000    1.592    0.001 model.py:205(_visit_value_and_its_immediate_references)
75503/6951    0.497    0.000    1.653    0.000 properties.py:244(is_valid)
44541/24484    0.447    0.000    1.417    0.000 encoder.py:288(_iterencode_list)
    70433    0.406    0.000    0.937    0.000 properties.py:1124(<genexpr>)
      230    0.389    0.002    1.015    0.004 doccer.py:12(docformat)
76657/24586    0.315    0.000    1.524    0.000 encoder.py:341(_iterencode_dict)
        5    0.307    0.061    0.307    0.061 {method 'fetchall' of 'sqlite3.Cursor' objects}
    19428    0.291    0.000    0.291    0.000 {repr}
      170    0.225    0.001    0.225    0.001 encoder.py:212(iterencode)
     6579    0.170    0.000    0.298    0.000 properties.py:991(validate)
      238    0.148    0.001    0.250    0.001 doccer.py:128(indentcount_lines)
    19153    0.143    0.000    0.433    0.000 encoder.py:236(floatstr)
    81822    0.141    0.000    0.141    0.000 properties.py:240(validate)
      159    0.138    0.001    0.138    0.001 decoder.py:372(raw_decode)
 1021/879    0.133    0.000    1.106    0.001 {all}
    69136    0.129    0.000    0.129    0.000 {method 'append' of 'list' objects}
     6408    0.120    0.000    0.120    0.000 {method 'expandtabs' of 'str' objects}
    12034    0.117    0.000    0.135    0.000 {method 'join' of 'str' objects}
27828/24588    0.116    0.000    1.619    0.000 encoder.py:417(_iterencode)
     6421    0.099    0.000    0.099    0.000 {method 'splitlines' of 'str' objects}
     5577    0.098    0.000    2.222    0.000 properties.py:267(prepare_value)
13503/12709    0.097    0.000    0.939    0.000 {getattr}
14939/14747    0.091    0.000    0.130    0.000 {hasattr}

**Comment by bryevdv** [comment]
Hi, thanks for the detailed report. However, I want to be realistic about what it might take to have this fixed.

First you mention that things appear to be busy-waiting in the Tornado loop. If so, then this would seem to be an upstream problem for the Tornado project to decide to address. I'd encourage you to also file an issue there. 

Perhaps there is a workaround we could use, but none of the core devs have any experience with ARM or RasbPi, or access to any RasbPi to debug with. By far the most likely way that this will ever be addressed is if you  (or someone else with the hardware and the experience) were to submit a PR to fix things, which we would certainly be very happy to review and test on standard platforms.

**Comment by donour** [comment]
Bryan: Thanks for your candor. I'm scratching my head myself, trying to figure out why this happens on ARM but not not other places. One thing that comes to mind is that select.epoll() seems to take a really long time (600+ms) on empty socket buffers. As you said, this is probably not bokeh's fault.

I'll keep digging. If I find anything to mediate the issue from the application, I'll report it back here.

Thanks!

**Comment by bryevdv** [comment]
@donour great thanks, I look forward to anything you discover. I'd definitely love to help make things better for this use-case if we can

**Comment by donour** [comment]
I have verified that this also happens with the latest release of tornado and with both epoll and old-school select(), inside the tornado IOLoop. I'm very perplexed.

**Comment by audiolion** [comment]
on a related note, I was trying to figure out what was causing immense slowness in my page load times, I cProfiled my bokeh function which uses the plotting lib to construct a plot and return it.

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.039    0.039 /Users/ryanar/Code/py-fitness/py_fitness/py_fitness/workout/views.py:25(bokeh_avg_workouts_per_day)
  729/716    0.000    0.000    0.013    0.000 /Users/ryanar/.virtualenvs/fit_dev/lib/python3.5/site-packages/bokeh/core/properties.py:391(__get__)
  644/631    0.001    0.000    0.012    0.000 /Users/ryanar/.virtualenvs/fit_dev/lib/python3.5/site-packages/bokeh/core/properties.py:381(_get)
  330/317    0.000    0.000    0.012    0.000 /Users/ryanar/.virtualenvs/fit_dev/lib/python3.5/site-packages/bokeh/core/properties.py:403(_get_default)
```

the `core/properties.py` calls `_get`, `__get__`, and `_get_default` a bunch of times.

For reference here is my code:

```
@profile
def bokeh_avg_workouts_per_day(user):
    DAY_OF_WEEK = {
        0: 0,
        1: 0,
        2: 0,
        3: 0,
        4: 0,
        5: 0,
        6: 0
    }
    data = user.workout_workout_author.extra({'day': 'extract(dow from date)'}).values('day').annotate(count=Count('id')).values('day', 'count')

    x_factors = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    plot = figure(title="Average Workouts per Day", height=1000, width=1000, responsive=True)
    plot.title.align = "center"
    plot.xaxis[0].axis_label = "Day of Week"
    plot.yaxis[0].axis_label = "Number of Workouts"

    if not data:
        today = timezone.now().date()
        plot.line(x_factors, [], line_width=2)
        notice = Label(x=40, y=150, x_units='screen', y_units='screen',
            text="No data yet. Record a workout!", render_mode='css',
            background_fill_color='white', background_fill_alpha=1.0)
        plot.add_layout(notice)
    else:
        workout_range = user.workout_workout_author.aggregate(min=Min('date'), max=Max('date'))
        weeks = weeks_between(workout_range['min'], workout_range['max'])

        for item in data:
            DAY_OF_WEEK[item['day']] += 1
        plot.line(x_factors, [i/weeks for i in DAY_OF_WEEK.values()], line_width=2)

    script, chart = components(plot, CDN)
    return (script, chart)
```

it is running the `if not data:` block

**Comment by bryevdv** [comment]
@donour have you inquired with the Tornado project about any issues on ARM?

@audiolion respectfully I don't think that is related to this issue at all, can you please open a different issue to discuss, and delete the comment here to keep this issue focused? Thanks

**Comment by bryevdv** [comment]
I hope new tornado releases might be helpful but this is otherwise outside out control, so I am closing
