### ISSUE TITLE
Bokeh doc website not rendered correctly in IE 11 on Win 7

### ISSUE THREAD

**Issue by jxrossel** [bokeh/bokeh#5522]
When I browse to http://bokeh.pydata.org/en/latest/, all the central content is missing, as shown on the 1st message here:
[https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/_MfdWjKLnNU](url)

This behaviour has been confirmed. Apparently (as reported by "Bryan van de Ven"), the rendering is fine on Edge/Win10 and IE11/Win10.

**Comment by bryevdv** [comment]
Any ideas @birdsarah ? There is an unrelated library issue #5523 causing some plots to not show up on windows to, but this main page issue is purely a web issue I think (e.g. the hero does not render at all for some reason, which is not Bokeh-related)

**Comment by mattpap** [comment]
Are there any errors in JS console?

**Comment by bryevdv** [comment]
This is for the front page:

<img width="544" alt="screen shot 2016-12-09 at 9 50 30 am" src="https://cloud.githubusercontent.com/assets/1078448/21054895/00aeb636-bdf5-11e6-9340-9da86bff6563.png">

**Comment by bryevdv** [comment]
Also some of the gallery examples fail, e.g. `unemployment.py`:

<img width="411" alt="screen shot 2016-12-09 at 9 54 01 am" src="https://cloud.githubusercontent.com/assets/1078448/21055027/77ddf67c-bdf5-11e6-8098-5b4853fc35b9.png">

**Comment by bryevdv** [comment]
possible ref: https://code.google.com/archive/p/crypto-js/issues/81

Can we just use `Uint8Array` ?

**Comment by mattpap** [comment]
> note: only fails on Win7 AFAIK

According to MDN, IE 11 support was added as of KB2929437, so it may behave differently on different platforms.

**Comment by bryevdv** [comment]
@birdsarah #5529 did not seem to fix this. There are no longer any HTML validation errors, so I am at the point where I don't know what else to try. The new docs at at:

http://bokeh.pydata.org/en/dev/
