### ISSUE TITLE
Consistent keyword arguments, e.g., `xlabel` vs `x_axis_label`

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#5530]
I noticed for labeling axes, `charts` uses `xlabel` while `plotting` uses `x_axis_label`.  I am not sure how they ended up different but I wonder if there are other keyword arguments that also differ unnecessarily.  It would be nice to move toward a more consistent usage but would create problems in existing code and tutorials.  I thought this thread could be used for discussing this and other inconsistent keyword arguments.

For this specific case, `xlabel` is used in [MATLAB](https://www.mathworks.com/help/matlab/ref/xlabel.html) and [matplotlib](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.xlabel) and I found `x_axis_label` is used in some ruby libraries, [Gruff](http://www.rubydoc.info/gems/gruff/0.7.0/Gruff%2FBase%3Ax_axis_label) and [ImageParadise](http://www.rubydoc.info/gems/image_paradise/0.0.11/ImageParadise%2FGruff%2FBase%3Ax_axis_label).  I would vote to unify on `xlabel`.

**Comment by bryevdv** [comment]
`x_axis_label` has been around a long time for better or worse, and it is demonstrated in lots of videos, notebooks, etc. Personally I think breaking it at this point would not be a user-friendly action.

**Comment by bryevdv** [comment]
If necessary this issue can be re-opened in the `bkcharts` repo.
