### ISSUE TITLE
Label image diff results "expected" vs "actual"

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5541]
I have no idea whether this is an old problem being fixed or a new problem showing up:

<img width="658" alt="screen shot 2016-12-12 at 11 12 16 am" src="https://cloud.githubusercontent.com/assets/1078448/21108939/926b733e-c05c-11e6-9ce3-7e05ef65d542.png">

My mind will 100% never be able to remember this arbitrary convention without some kind of labeling, because there is not particular reason it should be one way or the other. 

@mattpap can you say 1) which way it actually is, and 2) where to look to add a label to the output?

**Comment by mattpap** [comment]
It's "current", "diff" and "reference". This should have been labeled for a long time, but there is simple logic behind this. The "current" image always exists, so it's first and is followed by "optional" images. Like with function arguments, optional come last. "diff" vs. "reference" may seem arbitrary though.

**Comment by mattpap** [comment]
> "expected" vs "actual"

I would prefer we didn't use "expected" to refer to "reference" images, because this implies that there exists a set of expected outcomes and this is utterly not true. The reason is that we can't decide computationally (at least within the framework and test model we use) whether the difference is an intentional change or not. Saying "expected" implies that every difference is a bug, though most of the time it's an intentional change.

**Comment by bryevdv** [comment]
That's fine, I just care about being able to know which is which.

**Comment by bryevdv** [comment]
@mattpap In this report:

https://s3.amazonaws.com/bokeh-travis/183601852/examples.html

Why are these reported as "no diff" ?

<img width="623" alt="screen shot 2016-12-13 at 9 47 49 am" src="https://cloud.githubusercontent.com/assets/1078448/21147050/4ffa511a-c119-11e6-94cc-b133ee6335e5.png">

**Comment by mattpap** [comment]
@bryevdv, I'm not sure, but the original examples' testing code didn't allow to proceed to image diff in presence of JavaScript errors. You would get "FAILED" example instead and JavaScript error message in the log. This isn't true anymore after changes early this year, so this may be the effect. Note also that currently there is no way to learn about JavaScript errors in Travis CI's log. One has to go through images for this purpose (as shown in your comment).

**Comment by damianavila** [comment]
Well... I am really note sure the left is current... see this PR where I remove nb_conda_kernels an other extensions... when I see the report: https://s3.amazonaws.com/bokeh-travis/184359356/examples.html

At the right you have the naive notebooks... without any extension... so, my guess is that the left image is the reference? Or am I missing something?

ping @mattpap @bryevdv

**Comment by mattpap** [comment]
@damianavila, see https://github.com/bokeh/bokeh/blob/master/tests/examples/examples_report.jinja#L60. In order you have `png_url` (current), `diff_url` and `ref_url`.

**Comment by damianavila** [comment]
>@damianavila, see 

Understood, thanks!!

**Comment by mattpap** [comment]
This was done in PR #5713.
