### ISSUE TITLE
Periodically update a figure in a Jupyter notebook?

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#5548]
Hi,
Is there a way to periodically update a figure in a Jupyter notebook?
Let's say that I would like something like bokeh/examples/plotting/server/animated.py in notebook cell instead of a browser tab.
Thanks for your help.
Nicolas.

**Comment by bryevdv** [comment]
Hi, 

In order to have some hope of being maintainable, the GitHub issue tracker is reserved for bug reports and feature requests and dev-related discussions only. For general support, the public mailing list is appropriate:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

**Comment by nleclercq** [comment]
Oops, I was almost sure I was wrong to post here but I've seen entries marked as "discussion" so...
Anyway, my question is already on the google group.
Thanks.

**Comment by bryevdv** [comment]
@nleclercq yes there is a `discussion` tag but it is for dev-related discussion, i.e. "this seems like a bug but that still needs to be determined for sure" or "this is a feature request but we still need to decide how and what to do with it (if anything)"
