### ISSUE TITLE
Selenium testing with latest firefox

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5559]
There have been a number of moving pieces in selenium land that affect our testing:

* Selenium has had a major update to 3.0 - https://seleniumhq.wordpress.com/2016/10/13/selenium-3-0-out-now/
* pytest-selenium 1.7 - only works with selenium >= 3
* mozilla has new firefox drivers Marionette & geckodriver (still a little unclear on the relationship between the two) - Marionette is enabled by default in selenium 3 - https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver - https://github.com/mozilla/geckodriver
* these new drivers kick in at Firefox 48

So, if we were in a happy, modern world, we would use Selenium 3, pytest-selenium, and versions of firefox newer than 48 (current version of firefox is 50).

Unfortunately, the new web drivers aren't finished yet and don't currently support features that we're using in our test suite like "moveto" - https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status

At some point in the late summer selenium tests stopped working for me and @bryevdv locally, but continued to work on our integration tests. This is because SauceLabs currently only supports up to Firefox 45 on Linux: https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

I don't know why they haven't added new versions - they've added them for OSX and MacOSX - but see the note from the Firefox 48 release about Marionette https://wiki.saucelabs.com/display/DOCS/2016/08/12/Firefox+48+is+now+available Firefox 50 release notes: https://wiki.saucelabs.com/pages/viewpage.action?pageId=66295944

PR #5552 adds pins for our selenium and pytest-selenium versions as well as docs on how to get the selenium tests running locally.

Until mozilla finish their new webdrivers, we cannot update to the latest versions of firefox and selenium. When we do we may need to also switch to testing on MacOSX or Windows instead of Linux by default due to the lack of newer firefox versions.

Finally, it's worth noting that there are other webdrivers like chrome, ie, etc. I picked Firefox initially because with selenium 2, firefox worked out of the box without the dependency of a separate driver. However, with the switch to geckodriver, and selenium 3, that nicety is going away. 

All our tests run on Firefox, and a few run on chrome as well (those marked with a pytest mark "cross_browser"). Both run on Linux.

We could pick a different default - the most likely being chrome.

However, a quick attempt to just run all the tests on chrome didn't work, so that would take effort. Although selenium has the promise of write once, run anywhere, that's never been exactly the case. In our case, the custom code that checks for errors, waits for alerts etc. seems to be somewhat firefox specific (as that's what I was developing to).

There's a chance that things will improve as WebDriver is now a proper w3c spec.

So, for now the easiest thing is to wait. Times to revisit this:
- a bug comes up that is firefox > 48 specific
- geckodriver updates
- saucelabs stops supporting firefox < 48

Another factor to throw into the mix: chrome headless is coming along nicely. It may be that we'll be able to switch out saucelabs almost entirely in favor of running our selenium tests against chrome headless on travis ci. This would be good for external contributors too. It'll be a few months probably before chrome headless is available for Linux and it may be much longer before it's available for MacOS and, in particular, Windows which could cause problems for local development. But regardless, I imagine that any platform or browser specific bugs will always have to go through Sauce Labs.

**Comment by bryevdv** [comment]
Closing this. I am in the process of (re-)adding selenium tests that run locally.
