### ISSUE TITLE
Correctly deprecating ImageRGBA cols and rows properties

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#5562]
As part of #5544 we are changing how 2D arrays are serialized in bokeh and in reworking that code @bryevdv noticed that unlike the ``Image`` glyph,  the ``ImageRGBA`` glyph supports setting  ``rows`` and ``cols`` properties and setting the image data to a flattened 1D-array. This is both inconsistent and a bit weird so it was suggested that this option should be deprecated.

The question now is how best to do this deprecation. Most of the deprecations currently either rename or move an existing property rather than deprecating it entirely so there is no standard approach here. Currently I see two options:

1) My initial suggestion was to add hidden ``_rows`` and ``_cols`` props which matching rows and cols setter and getter properties write into.

2) As an alternative @bryevdv suggested defining a ``DeprecatedNumberSpec`` property
which would emit a warning on validation.

Neither approach is great, however currently when I try to implement the second approach I noticed that the ``validate`` method is fired twice when supplying the property value to the constructor, causing the deprecation warning to be duplicated. Suggestions welcome on how to correctly perform this deprecation, it would also good to figure out why the value is being set and validated twice in the constructor.

**Comment by mattpap** [comment]
Maybe use this:
```
rows = NumberSpec(None, help="""
    The numbers of rows in the images
    """).asserts(lambda _, __: False, "rows is deprecated, bla", soft=True)
```
Though it would be nice to use `bokeh.util.deprecation` for this. We could extend `asserts()` accordingly.

**Comment by philippjfr** [comment]
Seems like a much nicer solution, @bryevdv any thoughts? What would it take to support this?

**Comment by mattpap** [comment]
@philippjfr, PR #5564.

**Comment by philippjfr** [comment]
Awesome, happy to merge that into my PR.

**Comment by bryevdv** [comment]
the idea and the PR are good tho my preference would be to limit #5564 to just extending capability and leave using that capability (to deprecate rows and cols) in the array protocol PR
