### ISSUE TITLE
TypeError: unorderable types: NoneType() < str()

### ISSUE THREAD

**Issue by infpsyndrome** [bokeh/bokeh#5575]
TypeError occured when running the simple scatter plot example with python 3.5  

[](http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#tooltips)

```
from bokeh.charts import Scatter, output_file, show
from bokeh.sampledata.autompg import autompg as df

p = Scatter(df, x='mpg', y='hp', title="HP vs MPG", color="navy",
            xlabel="Miles Per Gallon", ylabel="Horsepower")

output_file("scatter.html")
show(p) 
```

**Comment by mattpap** [comment]
@infpsyndrome, I can't reproduce this. What version of bokeh do you use? Also, can you provide full traceback of this error?

**Comment by bryevdv** [comment]
@infpsyndrome More information is definitely needed. I can't reproduce any problems with Bokeh `0.10`, `0.11` or `0.12.3` with python 3.5

**Comment by infpsyndrome** [comment]
I tried it with a new code
