### ISSUE TITLE
Auto-conversion to ColumnDataSource

### ISSUE THREAD

**Issue by bgbg** [bokeh/bokeh#5578]
Many times, we want to pass a data structure to a plotting function as a data source. To do so, an explicit conversion is required. Often, the converted object does not serve any purpose, except for the conversion itself.  The modification to handle various supported data structures, such as pandas DataFrame and dicts, is pretty trivial, as you can see [here][1]. Is this a good idea to perform auto-conversion? What are the potential hazards of the way I handled this?

[1]: https://github.com/bgbg/bokeh/commit/aa459a7a89b715c3c8fea9a8cc8a7a5fad5cae9a

**Comment by bryevdv** [comment]
Thoughts, @bokeh/dev ?

I'm fairly neural but, if done I'd prefer using something like:
```
from bokeh.util.dependencies import import_optional
pd = import_optional('pandas')

if pd and isinstance(pd.DataFrame, source)
   # do conversion and update kwargs
```

**Comment by bgbg** [comment]
The version you provided, @bryevdv , indeed looks cleaner. However, it will not handle other cases that `ColumnDataSource.__init__` can handle, such as a dict for example. Not only that, my proposal is future-safe. If and when `ColumnDataSource` is able to read additional sources, this particular code will not need any changes. Plus, `ColumnDataSource` already performs all the needed tests and assertions.

**Comment by mattpap** [comment]
If `ColumnDataSource` contains all necessary logic, lets not duplicate it in the plotting API.

**Comment by bryevdv** [comment]
Fair enough, I'd have go go look to see what exactly happens on failure in CDS. Given the comments above I might then instead suggest to catch whatever CDS throws in the plotting API, and wrap that in a more contextual exception `"Could not convert data_source to CDS, reason: ..."`

**Comment by bryevdv** [comment]
Looks like it raises `ValueError` if not passed a `dict` or `DataFrame`:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L89

@bgbg If you wanted to update your code in a PR that catches `ValueError`, and raises a more contextualized error message, it would gladly be accepted.
