### ISSUE TITLE
Adding size attribute to MultiSelect model

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#5579]
Small feature request: it would be nice to have an attribute to toggle number of visible elements in MultiSelect. Note that this can't exactly be controlled by CSS (the height property can be used, but I'm not sure if there's an easy way to set it to exactly match the height of the options). Since the options can be dynamically set, it seems reasonable to me to also let the size attribute be dynamically set.

This is implemented in these commits: [commit1](https://github.com/azjps/bokeh/commit/504910486751c5e947edd9217f186ede87f82b48), [commit2 which is an unrelated typo fix](https://github.com/azjps/bokeh/commit/0ff1290210af58b59cbecbcd84e98dc6d1248349) I haven't submitted a PR yet, noticed that PR etiquette dictates to submit an issue first.

**Comment by bryevdv** [comment]
Hi, 

Those changes look great, a PR would be welcome. When appropriate we ask for tests and docs. In this case the docs are the help string you've included already, and the automated defaults tests will ensure the JS/python sides stay in sync. The only thing really to do is first make a feature request issue on GH, then reference that issue from the PR. 

Thanks!

Bryan
