### ISSUE TITLE
Custom context arguments for the jinja template

### ISSUE THREAD

**Issue by bkueng** [bokeh/bokeh#5583]
I have a bokeh server app with custom `templates/index.hml`, and I'd like to pass custom arguments to the `render()` method of jinja. I see that I can access the jinja template with `curdoc().template`, but the [doc](http://jinja.pocoo.org/docs/dev/api/#jinja2.Template) says this is an immutable object.

`embed._html_page_for_render_items` already has an argument `template_variables` but it seems to be unused for the server. Can we make this available to the server app?

**Comment by bryevdv** [comment]
Yes, it would amount to:

* modifying `embed.server_html_page_for_session` to accept a `template_variables` argument that it passes to `_html_page_for_render_items` (the parameter should defaultsto `None` and pass an empty dict to `_html_page_for_render_items`in that case)
* pull `.template_variables` (or whatever) off of the document, and passing them to `server_html_page_for_session` [in this code for the server]( https://github.com/bokeh/bokeh/blob/master/bokeh/server/views/doc_handler.py#L33)
* make `Document` add an attribute `template_vars` that defaults to an empty dict, on initialization

@bkueng would you be interested in working up a PR for this?

**Comment by bkueng** [comment]
Seems doable. Yes, I'll take a shot at it.

**Comment by bryevdv** [comment]
@bkueng great! Please let me know if I can help in any way, or answer any questions.
