### ISSUE TITLE
Some WebGL not working on Safari

### ISSUE THREAD

**Issue by veenits** [bokeh/bokeh#5589]
Hi,

I'm trying to run the example in models/map_cities.py to see a plot of cities. However, when I run it using the `python map_cities.py` command, I see the html output in browser as below - 

![screen shot 2016-12-19 at 4 04 39 pm](https://cloud.githubusercontent.com/assets/1811809/21330790/e49b0540-c604-11e6-9479-de4e6d30c877.png)

Is this expected behavior? Basically, I am trying to use this example to plot/fill states/countys with a desired color and hover information.

Here is my `bokeh info` output - 

    Python version      :  2.7.12 |Anaconda 2.0.1 (x86_64)| (default, Jun 29 2016, 11:09:23)
    IPython version     :  4.1.2
    Bokeh version       :  0.12.3
    BokehJS static path :  //anaconda/lib/python2.7/site-packages/bokeh/server/static

**Comment by bryevdv** [comment]
That example demonstrates webgl capabilities, we will need specific information about OS, hardware, platform, and browser to be able to investigate. It would help greatly if you can also try the example on other platform/browser combinations.

**Comment by VeenitShah** [comment]
Okay. I just checked. It works on Google Chrome, but not on Safari Version 10.0.1 (11602.2.14.0.7). 

<img width="235" alt="screen shot 2016-12-19 at 4 09 59 pm" src="https://cloud.githubusercontent.com/assets/1811809/21330956/b4d5826c-c605-11e6-9bb7-ac75e37cb66b.png">

This is what I see in Google Chrome Version 52.0.2743.116 (64-bit)

<img width="1013" alt="screen shot 2016-12-19 at 4 11 48 pm" src="https://cloud.githubusercontent.com/assets/1811809/21330994/e84487f6-c605-11e6-9e03-220fceddf33b.png">

**Comment by bryevdv** [comment]
Safari reports:
```
RuntimeError: RuntimeError:OpenGL got errors (after draw): 1282
``` 
For scatter type plots. 

@almarklein do you have any input offhand for what might cause this error code?

**Comment by almarklein** [comment]
Were there any other errors in the browser console? There unusually are. Its hard to go on this error message alone :)

**Comment by bryevdv** [comment]
I had hoped to make WebGl a focus of `0.12.7` but it will have to be `0.12.8` cycle

**Comment by ayoungs** [comment]
I tried the examples/webgl, in bokeh 0.12.11.  The Tabs example of marker_compare does not work in Safari 11.0.1 on MacOS High Sierra, nor does it work in Safari Technology Preview 11.1.  However, it does work in Chrome.  Other examples, like iris_blend, line_compare, line10k, and clustering work fine in Safari.

**Comment by bryevdv** [comment]
I haven't had any opportunity to look at this. The original GL support author is no longer working on Bokeh, and I personally have no relevant GL experience so fixing this will be a large personal investment. I don't expect to be able to devote any time to scaling a new learning curve anytime int he immediate future. Best scenario is someone with webGL experience decides to pitch in and help out. The success of OSS is dependent on many people making contributions.

**Comment by bryevdv** [comment]
Just updating, currently not working for me on safari:

* `marker_compare.py`

* `scatter10k.py`
