### ISSUE TITLE
GMapOptions are not dynamically applied

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#5592]
Any changes to GMapOptions (such as the map style) are only picked up at creation/initialization time, and subsequent changes are not picked up by BokehJS.  In https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee, we will need to add a handler that listens for changes to the GMapOptions and applies them.

The `styles` attribute of `map_options` is particularly important, because it's quite conceivable that users will want to dynamically change the visual appearance of the map (or turn on/off certain map features via styling).

**Comment by bryevdv** [comment]
@pzwang Do you have a test code handy?
