### ISSUE TITLE
mpl.to_bokeh doesn't render second y axis

### ISSUE THREAD

**Issue by amichaut** [bokeh/bokeh#5593]
The second ax generated by twinx command isn't converted by to_bokeh.

Code example:
```
from pylab import *
from bokeh.plotting import figure, output_file, save
from bokeh.mpl import to_bokeh

fig,ax=plt.subplots(1,1)
ax.plot([1,2])
ax2 = ax.twinx()
ax2.plot([6,0])
f=to_bokeh(fig)
output_file('test.html')
save(f)
```
`ax2` isn't rendered in the bokeh figure

**Comment by bryevdv** [comment]
Bokeh's current MPL compat relies on an incomplete third party library that is no longer maintained. It is provided completely as-is, just in case it proves useful under limited circumstances. No further work will happen on Bokeh MPL interop until and unless the MPL project implements MEP 25 and provides a consistent JSON serialization scheme to target
