### ISSUE TITLE
MultiSelect widget, losing focus causes "viewport" to change

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#5597]
From discussion on #5580:

> One (albeit more minor) problem that continues with this implementation is that when scrolling down a `<select>` with a lot of options, when the focus drops off the `<select>` it scrolls back to the top. When this implementation causes the `<select>` to regain focus, it will have been scrolled so that the selected elements are on the bottom of the viewable options. So the viewable options may change and there's also the distraction of seeing the options and scrollbar flicker.

**Comment by azjps** [comment]
Another example: if we append `text` to a `Div` or `PreText`, etc, which has a vertical scrollbar, it will I guess re-render the HTML element, causing the text to be scrolled to the top. Example application: a simple widget which implements a [logging handler](https://docs.python.org/2/library/logging.handlers.html) to show users the underlying python's process logger output. A custom extension can be implemented which automatically scrolls to bottom on render (e.g. like some shells do) but that also might not be that user-friendly.

**Comment by bryevdv** [comment]
My guess is that this may be fixed after the complete layout overhaul in 1.1 in any case without a complete MRE to actually run, this issue is no longer useful.
