### ISSUE TITLE
New Feature:  Create Bokeh Dashboard

### ISSUE THREAD

**Issue by arita37** [bokeh/bokeh#5601]
Bokeh is good for generating individual Graphs.

But, the framework is still lacking elements to generate a full Dashboard : 
  Mutiple graphs, tables together in ONE HTML file/page.

This example:   https://plot.ly/dashboard/jackp:16820/present

Other tools like Plot.Ly and Tableau are much easier to create full Dashboard with many graphs/elements.....
If you can : 

   **Show more example of complex Dashboard (at least 5 graphs +2 tables) in one page.**

   **Setup a sub-library of Bokeh for Dashboard organization (ex with pre-template of dashboard) and component of dashboard.....**

You will help people to use Bokeh internally (otherwise we need to go to Plot.Ly.....).

**Comment by dmargol1** [comment]
Plotly is a valid comparison, but I think Tableau is targeting a very different audience than Bokeh (at least currently).

That said, standing up multiple graphs in a single page isn't that difficult.  There is significant documentation around laying out multiple elements here: http://bokeh.pydata.org/en/latest/docs/user_guide/layout.html

Additionally, there is a Bokeh server example with 3 graphs, two drop down menus, and a table on a single page here: https://demo.bokehplots.com/apps/stocks

Is this basically what you are looking for, or are there elements that you feel are missing?

**Comment by arita37** [comment]
Hello,

Thanks for example that I have seen it.
Am not sure how to formulate it.
But, those examples are pretty simple in term of layout (mainly 1 column).

If you have at Plot.ly example below (Shell), and others : Layout are more natural/better design/complex.

So, my questions :

1) Can we do Grid layout ? (Mutiple colums/ rows with different size)

2) Can we mix 2 grid layout in a column way (we can scroll down) ?

3) Is possible to have more concrete case example of real Dashboard ?
(Maybe a directory where users can put their examples/ pick up templates).


4) Pre-designed Grid Dashboard template where we just need to add the graph/widget would be very useful.



























On 23 Dec 2016, at 11:04, Daniel Margolis <notifications@github.com> wrote:

Plotly is a valid comparison, but I think Tableau is targeting a very different audience than Bokeh (at least currently).

That said, standing up multiple graphs in a single page isn't that difficult. There is significant documentation around laying out multiple elements here: http://bokeh.pydata.org/en/latest/docs/user_guide/layout.html

Additionally, there is a Bokeh server example with 3 graphs, two drop down menus, and a table on a single page here: https://demo.bokehplots.com/apps/stocks

Is this basically what you are looking for, or are there elements that you feel are missing?

―

**Comment by bryevdv** [comment]
This is an old issue, and is really too vague to be actionable.
