### ISSUE TITLE
Templates should be exposed as functions (API) and not raw jinja2 templates

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5604]
There is documentation in templates, but it would be better to simply have functions with arguments and defaults values. @bryevdv, if there are no objections I will schedule this for 0.12.4.

**Comment by bryevdv** [comment]
Isn't that pretty much already the case? The templates are not really for general use, they are used by functions like `notebook_div` and `output_file`. The documentation on them is for me and other developers and completeness and should stay in any case.

**Comment by bryevdv** [comment]
Definitely re-iterating that the APIs are those in `bokeh.embed` and `bokeh.io` etc, I dont think we not need yet another layer here.
