### ISSUE TITLE
Properties with defaults not considered "changed"

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#561]
Added:
```
    resize_plot = Bool(True)
``` 
to `objects.Plot`, however the value does not make it to bokehjs without an explicit assignment to it in the `Plot` initializer. The reason is because:
```
    def vm_props(self):
        """ Returns the ViewModel-related properties of this object. """
        props = self.changed_properties_with_values()
        props.pop("session", None)
        return props
``` 
is what happens in `PlotObject`. 

One option is to always return all properties. This could be ok, but it increases the size of the generated json, and also clobbers all the bokehjs defaults. We would have to recreate the defaults we want entirely on the python side. This also breaks lots of `to_glyphspec` tests, naturally. 

Another option might be to make properties with defaults always be considered "changed" I attempted this:
```
diff --git a/bokeh/properties.py b/bokeh/properties.py
index 0492145..4326cef 100644
--- a/bokeh/properties.py
+++ b/bokeh/properties.py
@@ -517,6 +517,14 @@ class HasProps(object):
         self._changed_vars = set()
 
         props = self.properties()
+        for prop in props:
+            if prop in self.__class__.__dict__:
+                if self.__class__.__dict__[prop].default is not None:
+                    setattr(self, prop, self.__class__.__dict__[prop].default)
         for key, value in kwargs.items():
             if key in props:
                 setattr(self, key, value)
```
This breaks fewer tests, but also breaks a some plots. Defaults for `LineProps` are now showing up as `undefined`. 

Maybe there are other solutions?

@pzwang, @mattpap thoughts?

**Comment by havocp** [comment]
I think this one was obsoleted by https://github.com/bokeh/bokeh/pull/3190 in particular https://github.com/bokeh/bokeh/commit/150757540bde1a4c39af819408a66190d3ce64aa

We currently send all values even those that are defaults, but once we fix all coffee/python discrepancies we can switch over to `include_defaults=False` for what we send. In any case things are now well-defined.
