### ISSUE TITLE
Windows setup.py build from source and versioneer

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#5613]
On fresh install from current bokeh master on Windows 8.1, I can run `python setup.py install --build-js` but `import bokeh` will cause a complaint that version cannot be detected. (Note that I have cygwin installed but I am not using cygwin nor cygwin-git, using `cmd.exe` and windows git installation in `%PATH%`.) This seems to be a known issue on [versioneer issue tracker](https://github.com/warner/python-versioneer/issues/14), but I thought I would file it as an issue here for easier searching. I understand that it would probably take non-trivial work to update the version of versioneer, but it would be nice to make a note in the windows developer guide docs. (Assuming I'm not missing something of course.) I would be happy to submit a PR for such but I don't know how to deal with this besides manually substituting `git_refnames="0.12.x"; git_full="0.12.x"` every time I run `setup.py`. 

git version: 2.10.2.windows.1
```python
(env2016) C:\projects\bokeh\examples\custom>python -m bo
keh serve .
Traceback (most recent call last):
  File "C:\Anaconda\envs\env2016\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Anaconda\envs\env2016\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Anaconda\envs\env2016\lib\site-packages\bokeh-0.12.4dev9_20_ge4da7e7-
py2.7.egg\bokeh\__init__.py", line 16, in <module>
    from .util.version import __version__; __version__
  File "C:\Anaconda\envs\env2016\lib\site-packages\bokeh-0.12.4dev9_20_ge4da7e7-
py2.7.egg\bokeh\util\version.py", line 36, in <module>
    __base_version__ = base_version()
  File "C:\Anaconda\envs\env2016\lib\site-packages\bokeh-0.12.4dev9_20_ge4da7e7-
py2.7.egg\bokeh\util\version.py", line 34, in base_version
    return VERSION_PAT.search(__version__).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by bryevdv** [comment]
@azjps we have made some minor modifications to the generated `_version.py`, but not many:

https://github.com/bokeh/bokeh/commits/master/bokeh/_version.py

Updating to a newer versioneer might remove the need for many of the modifications, it's probably worth a quick attempt.

**Comment by azjps** [comment]
If this is something that doesn't require much outside knowledge I can give it a quick go.
