### ISSUE TITLE
CategoricalColorMapper ColorBar

### ISSUE THREAD

**Issue by js3711** [bokeh/bokeh#5618]
I have a use case for CategoricalColorMapper to work with the ColorBar class similar to how LinearColorMapper works

The default behavior would be to display the Categorical names next to the particular color value.

**Comment by bryevdv** [comment]
@js3711 can you elaborate some? Things that are helpful for feature requests:

* detailed description of need
* references to similar examples in other systems
* API / sample code proposals to consider

**Comment by js3711** [comment]
@bryevdv thank you, I should have been more clear in my previous post.

It is nice how the ColorBar class works with a LinearColorMapper:
mapper = bkmap.LinearColorMapper(palette=colors, low=min_val, high=max_val)
color_bar = ColorBar(color_mapper=mapper, ticker=FixedTicker(ticks=ticks), label_standoff=12, location=(0,0))
plot.add_layout(color_bar,'right')

It would be nice if the ColorBar class would work the same with a CategoricalColorMapper:
mapper = bkmap.CategoricalColorMapper(factors=categories, palette=colors)
color_bar = ColorBar(color_mapper=mapper, label_standoff=12, location=(0,0))

Extra nice if the ColorBar class automatically detected how the factors were mapped to colors and applied tick marks like so:
![image](https://cloud.githubusercontent.com/assets/15849929/21530592/d9e782ce-cd0f-11e6-911c-5323b32f9383.png)

**Comment by bryevdv** [comment]
@js3711 Thanks for the additional information. I agree this would be a useful addition. There is some planned work to improve how categorically are handled generally in Bokeh, and it probably makes sense to get that work out of the way first. 

That said, I do think that "categorical-like" labels on colorbars are currently accomplishable using custom tick formatters.

ping @birdsarah for FYI and any thoughts

**Comment by bryevdv** [comment]
I'm going ot unmark this as GFI because I expect it might actually be fairly involved. Also adding to 2.3 because I think it is fairly overdue.
