### ISSUE TITLE
Minor, use HTML for input labels

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#5623]
Currently all HTML tags in input labels are handled as raw text. However, there are significantly more cases where we'd want to be able to use HTML tags in input labels than the other way around. Examples: adding a link, a help dialog icon, some simple styling, etc.

**Comment by bryevdv** [comment]
This seems reasonable but bumping to `0.12.8`

**Comment by mattpap** [comment]
Given that one can achieve this with a `Div` and a layout, e.g.:
```py
from bokeh.io import save
from bokeh.layouts import column 
from bokeh.models.widgets import TextInput, Div

label = Div(text="""<b>Input <span style="color: red;">value</span>:</b>""")
input = TextInput(placeholder="Enter value ...")

save(column([label, input]))
```

![image](https://user-images.githubusercontent.com/27475/54467613-8db2b600-4786-11e9-80c3-613a397dbfcc.png)

I'm going to reject this. `label` property is meant for only immediate convenience. It's also quite likely that we will deprecate this at some point and provide this feature in terms of pre-defined layouts.
