### ISSUE TITLE
Bokeh server reports "None" port when there is a port conflict. 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5629]
When starting a bokeh server on the default port when another server is already running, the port number is incorrectly reported in the error message:
```
$ ../../bin/bokeh serve --show spectrogram
2016-12-28 13:57:32,400 Starting Bokeh server version 0.12.4dev10-77-g450e64c-dirty
2016-12-28 13:57:32,401 Cannot start Bokeh server, port None is already in use
```

**Comment by souravsingh** [comment]
@bryevdv I am interested in working on the issue. How do I start?

**Comment by bryevdv** [comment]
HI @souravsingh that's great! 

The actual message is printed here in a `report_server_init_errors` context manager:

https://github.com/bokeh/bokeh/blob/master/bokeh/command/util.py#L118

and that context manager is used here:

https://github.com/bokeh/bokeh/blob/master/bokeh/command/subcommands/serve.py#L563

The issue seem to be that the default for `--port` starts out as `None`, which is not set to the real default until inside `Server` (which is inside `report_server_init_errors`, which is the problem):

https://github.com/bokeh/bokeh/blob/master/bokeh/server/server.py#L112

So an idea might be to set the `DEFAULT_SERVER_PORT` inside `serve.py` in that `server_kwargs` dict. 

Let me know if I can answer any more questions!
