### ISSUE TITLE
examples/test: bokeh-server failures aren't reported

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#563]

**Comment by damianavila** [comment]
The server failures are somewhat reported in TravisCI, do we want to elaborated more on that, or the current situation is enough? For me, I think it is enough (we have the js console failure and that is enough hint to start researching into the problem... thoughts?

**Comment by mattpap** [comment]
Server failures are available in `examples.log`, by design. However, if there is a problem during server start-up, you won't get any feedback, besides a timeout failure (very helpful). Something has to be done about this. Thought I'm not sure if this isn't a different issue.

**Comment by bryevdv** [comment]
I personally think we should eventually separate the real server tests (which are really integration tests) out from simple unit tests, and that we should wait until then to do anything about better reporting.

**Comment by bryevdv** [comment]
There are currently not good tests for server besides the unit tests, but this issue refers to the old `bokeh-server` so I am closing it
