### ISSUE TITLE
Fix documentation of 'bokeh html foo.py'

### ISSUE THREAD

**Issue by verdimrc** [bokeh/bokeh#5634]
The [user guide](http://bokeh.pydata.org/en/latest/docs/user_guide/concepts.html#output-methods) shows an example of `bokeh html foo.py`, however the `foo.py` seems to be missing two lines.

The full code should be:
```python
from bokeh.io import curdoc    #This is missing from userguide
from bokeh.plotting import figure 

p = figure() 
p.line(x=[1, 2, 3], y=[4,6,2]) 

curdoc().add_root(p)    #This is missing from userguide
```

**Comment by tdsmith** [comment]
This is also necessary in order for `bokeh serve` to display anything except a blank screen.

**Comment by bryevdv** [comment]
@tdsmith @verdimrc can one of of you submit the tiny PR to update? There are ~650 issues in the tracker. It is actually an *enormous help* if users can make small PRs for the issues they are amply capable of fixing. The file is here:

https://raw.githubusercontent.com/bokeh/bokeh/master/sphinx/source/docs/user_guide/concepts.rst

**Comment by tdsmith** [comment]
Yep, working on it.

**Comment by bryevdv** [comment]
Great, thanks!!
