### ISSUE TITLE
Should the canvas coordinates be removed from the default hover tooltip?

### ISSUE THREAD

**Issue by bgbg** [bokeh/bokeh#5635]
Now that #4861 is fixed, let me ask whether the canvas coordinates should appear in the default hover tooltip? I think that having the data coordinates alone will help reduce the visual noise. I can't think of a situation where knowing the canvas coordinates of a point on the graph had real value for me.

**Comment by bryevdv** [comment]
I wouldn't object to changing this, but I also don't care if it is not changed, so I will close this issue as stale. The default is really just demonstrative, I can't imagine any case where anyone using the hover tool does not set a real tooltip value that makes sense for their actual data.
