### ISSUE TITLE
patches incorrectly draws boundaries from GeoJSONDataSource in latest development version on a bokeh server

### ISSUE THREAD

**Issue by agoodm** [bokeh/bokeh#5636]
Today I decided to test bokeh 0.12.4dev13 with an app I am currently developing. It involves plotting US states on a map via the `GeoJSONDataSource`. When I attempt to do so, for the states which have discontinuities in their boundary (eg, their geometry is `MultiPolygon`), the boundaries are drawn incorrectly, as shown here:

![example](https://puu.sh/t5j0B/94615168c2.png)

The code I used is a slightly modified version of the example shown in #4935 
```python
from bokeh.io import output_notebook, show
import json
from bokeh.models import GeoJSONDataSource, HoverTool
from bokeh.plotting import figure, curdoc
from shapely import affinity
from shapely.geometry import mapping, shape

def get_us_coords():
    with open('/Users/goodman/data/boundaries/us_states_simplified_albers.json') as us_states_file:
        geojson = json.loads(us_states_file.read())
        for i, f in enumerate(geojson['features']):
            if f['properties']['NAME'] == 'Alaska':
                geom = affinity.translate(shape(f['geometry']), xoff=1.2e6, yoff=-4.8e6)
                geom = affinity.scale(geom, .45, .45)
                geom = affinity.rotate(geom, 30)
                f['geometry'] = mapping(geom)
            elif f['properties']['NAME'] == 'Hawaii':
                geom = affinity.translate(shape(f['geometry']), xoff=4.75e6, yoff=-1.1e6)
                geom = affinity.scale(geom, 1.15, 1.15)
                geom = affinity.rotate(geom, 30)
                f['geometry'] = mapping(geom)
    return GeoJSONDataSource(geojson=json.dumps(geojson))

geojson = get_us_coords()

x_range = (-3e6, 3e6)
y_range = (-2e6, 1.5e6)

ar = (x_range[1] - x_range[0]) / (y_range[1] - y_range[0])
width = 800

fig = figure(
    plot_width=width, plot_height=int(width / ar),
    x_range=x_range, y_range=y_range,
    x_axis_type=None, y_axis_type=None, min_border=0,
    tools='tap', toolbar_location=None, outline_line_color=None
)
fig.grid.visible = False
fig.add_tools(HoverTool(tooltips='@NAME'))
fig.patches(xs='xs', ys='ys', line_color='#333333', line_width=1, fill_alpha=0.5, source=geojson)
curdoc().add_root(fig)
```
These two issues are probably related, but it should be noted that I can't reproduce the problem when running the notebook version of this example, it only happens when I run the above code in a bokeh server. Additionally, I did not have this issue with 0.12.3. Here is the output from `bokeh info`:
```
Python version      :  2.7.11 |Anaconda custom (x86_64)| (default, Dec  6 2015, 18:57:58) 
IPython version     :  5.1.0
Bokeh version       :  0.12.4dev13
BokehJS static path :  /Users/goodman/opt/lib/python2.7/site-packages/bokeh/server/static
```
and my browser is Chrome Version 55.0.2883.95 (64-bit)

The only thing unusual in the logging from `bokeh serve` was:
```
2016-12-29 18:11:42,150 E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name: xs, ys [renderer: GlyphRenderer(id='66d3e82f-ab8d-4973-aebb-dc71b1878e4c', ...)]
```
But I was also getting this message in 0.12.3, and there didn't seem to be any problems.

**Comment by bryevdv** [comment]
ping @birdsarah @philippjfr does geojson renderer use nans for breaks? could something about the new array protocol have effect here?

**Comment by philippjfr** [comment]
@bryevdv I just played around with it and I can confirm this is likely something to do with the array protocol or maybe some of the changes we made to bokeh server. It initially seems to get set up just fine, but when the GeoJSONSource on the JS end receives the JSON representation it converts it to regular column data, which ends up getting sent back to Python, which apparently causes this issue.

The quickest fix I managed to apply was to have the ``GeoJSONDataSource`` inherit directly from ``DataSource`` not ``ColumnDataSource``, which works with some minor tweaks to data source validation in the python plotting functions and renderers. However, the correct thing to do is probably to stop it from sending back the converted data from client.

**Comment by bryevdv** [comment]
@philippjfr can you open a separate issue to discuss general column-ish data sources and improvements?

**Comment by philippjfr** [comment]
Sure, it'll mostly just be a summary of the discussion in the PR that was merged, does that sound okay?

**Comment by bryevdv** [comment]
Yes I just don't want to forget out things with this issue closed

**Comment by SereneWizard** [comment]
Sorry for barging in late. But if you have not solved the multipolygon issue yet, exploding it to polygons could be helpful. [Here is a helpful link](https://gist.github.com/mhweber/cf36bb4e09df9deee5eb54dc6be74d26).
