### ISSUE TITLE
New App Example: Exploding Pivot Charts

### ISSUE THREAD

**Issue by mmowers** [bokeh/bokeh#5640]
I would like to contribute an example bokeh app, and @bryevdv suggested I make an issue for this. Our discussion is here: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/DbPRiwxQ90o.

The app creates pivot charts from data, similar to Excel's pivot chart functionality, but with the additional ability to explode into multiple filterable charts. I started from Bokeh/examples/app/crossfilter, but most of the current code is new. The app is fully functional, but the code could certainly be improved. For example, I've introduced a few workarounds (e.g. using html ids like classes) that may have more robust implementations in Bokeh.

Here is the repo: https://github.com/mmowers/superpivot

Thanks!

**Comment by julienschroder** [comment]
Awesome!
Thanks for the contribution, great example of what can be done!

**Comment by mmowers** [comment]
A few thoughts/questions on making this up-to-par for contribution:
1. The initially blank plots area may be off-putting for some. However, I intentionally want the code to be agnostic to the data source, so I'm trying to avoid pre-selecting widgets based on the default data source. Should I include some helpful text on the page, or do people think this is intuitive enough?
2. Is my use of global variables acceptable?
3. Is there a way of adding classes to widgets? I couldn't find this, so I'm using ids like classes, and this makes the python, css, and js messier.
4. I use a try-except block to handle python 2-3 compatibility for urllib. Is there a different, more-recommended way?

Some more thoughts for later improvements:
1.  It would be great to allow users to upload csvs from the browser to the app, so that they don't have to enter the path to their csv file. Is there an upload widget or some other combination of features that would allow for this?
2. @bryevdv also recommended perhaps adding a loading icon for use cases like this. Is this task in the works?

Thanks again.

**Comment by bryevdv** [comment]
Hi @mmowers thanks for pushing on this, a number of CI / build fires have cropped up and are taking up lots of my time.

1) I think they are OK to start, but it might not hurt to have a default CSV example that gets loaded in the absence of a user provided one
2) If there's a way to factor things without them (maybe a class that encapsulates all the data for a CSV file) I think that would be preferable
3) There is now a `css_classes` property
4) I think using `six` would be fine / preferable. Bokeh depends on it so it should always be available

Next questions:

1) Not really, but I also had another idea for this example, though it would be a little work. There are new examples about how to embed a server programmatically inside, e.g. a Flask app: https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/flask_embed.py If that were done, then it would be possible to combine fairly common flask type things (e.g. a file downloader I assume) together with the bokeh app. I think that would be a really great thing to show, but also I recognize that that is more work

2) the foundations for this should be available in the next few weeks.

**Comment by mmowers** [comment]
Thanks much @bryevdv!

I've updated the code to use `css_classes` and `six`.

Let me know if you think it's now good enough for contribution, or if the refactor in 2) (first section) is necessary. If the refactor is necessary, I may need a little more guidance or to do some more research myself on how to refactor properly.

The embedded Flask app sounds like it would be a great addition. I'm partial to contributing the current functionality first and perhaps adding Flask later, if possible.

Regarding the initially-blank plots area 1) (first section), it occurred to me that if this example app would be shown on https://demo.bokehplots.com/, we wouldn't want the data source field, so we'd have to modify the code slightly for the demo. In which case, we might as well give the widgets an initial configuration that displays plots too...

**Comment by mmowers** [comment]
OK, I finally got around to refactoring so that no global variables are declared within functions. That's done now, and I've added a pull request: #5894.
