### ISSUE TITLE
Line renderer raises the "without value specification" when a ColumnDataSource is used

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#5648]
bokeh 0.12.3

Line renderer raises the JS error, while Circle renderer works as expected. There's probably a workaround to define a separate source column for each value of width (highly inefficient).

```python
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show
from bokeh.io import output_notebook, push_notebook

output_notebook(hide_banner=True)

source = ColumnDataSource(dict(x=[1.2, 3.4], y=[3.2, 4.5], sz=[20.5, 40.1], lw=[1.1, 2.2]))

plot = figure()
plot.circle('x', 'y', source=source, size='sz') # This line works fine
plot.line('x', 'y', source=source, line_alpha2='sz') # This line raises 
# Uncaught Error: attempted to retrieve property value for property without value specification
show(plot)
```

**Comment by mattpap** [comment]
Currently `Line` glyph only supports scalar values for `line_*` properties. This seems like some sort of optimization or what not (@bryevdv?). The offending line is https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/line.coffee#L13.

**Comment by bryevdv** [comment]
`line` only draws one single line, it's. It meaningful for it to have vectorized line properties. Perhaps you want `multi_line`?

**Comment by mattpap** [comment]
@bryevdv, so we have to make the API reflect this limitation.

**Comment by bryevdv** [comment]
Agreed, I thought it did already.
