### ISSUE TITLE
Feature request: keyboard control over tools

### ISSUE THREAD

**Issue by jordansamuels** [bokeh/bokeh#5651]
After discussing with @bryevdv on chat, I'm submitting a feature request to be able to control tools with the keyboard.  Either of the following would be very helpful:

1. Ability to use a modifier key like shift or alt to change a `wheel_zoom` tool to an `xwheel_zoom` or `ywheel_zoom` tool.  

2. Ability to change activated tools with a keyboard shortcut.

These would help in viewing very rich time series plots, since typically wants to keep the plot re-zoomed to fill the view panel.  Of course, if that were done automatically, that would be even better - but I'm not sure it's possible.

**Comment by azjps** [comment]
Would be interested in this also, automatic re-zooming will be more useful for the case of multiple plots sharing a common axis (e.g. the datetime axis for time series plots).

**Comment by rsandler00** [comment]
Also, having different mouse buttons activate different tools. For example, panning w/ left mouse button and box-zooming w/ right mouse button

**Comment by bryevdv** [comment]
Looking over old issues, sorry this did not get discussed/triaged earlier. Unfortunately project resources are extremely spread thin. I recognize that it's not a great answer, but I think these kinds of ideas will have to be left to custom extensions, so I am closing this with no action.
