### ISSUE TITLE
Add tests to ensure server events do not boomerang client-side

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#5653]
As part of #5544 significant changes to the way the bokeh server detects whether an event that is about to be sent was triggered by another event that was just received. The new approach ensures that events are associated with a ``setter`` or ``setter_id`` and if a ``ClientSession`` detects that it is the original setter of an event it ignores it. On the Python side there are tests that the setter is propagated appropriately for all event types but on the JS side there are no such tests. There should be at least a few tests for each event type ensuring that events do not boomerang.

**Comment by bryevdv** [comment]
@philippjfr you are already assigned :)

**Comment by philippjfr** [comment]
Ah, well I better get on it then :)
