### ISSUE TITLE
0.12.3 resize tool uses plot_width for initializing plot_height

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#5655]
`bokeh` `0.12.3`

Repro steps:
* Execute this *complete code sample* :smile:
```python
from bokeh.plotting import figure, show
from bokeh.io import output_notebook, push_notebook

output_notebook(hide_banner=True)

plot = figure(
    tools='pan,resize,reset', 
    plot_width=600, 
    plot_height=200, 
)
show(plot)
```
* Click and hold left mouse button on the resize tool.
* Note: until the mouse is moved the plot is as expected, even after the click.

Unexpected behavior:
* Move the mouse a bit while holding the left button down.
* The vertical size of the plot is immediately set to 600 from 200.
* The resize icon moves off the tools toolbar towards the middle of the plot.

Expected behavior:
* use `plot_height` not width to initialize `plot_height` :smile: 
* The resize button should remain in the toolbar.

**Comment by bryevdv** [comment]
@rs2 some screen shots would help

**Comment by rs2** [comment]
@bryevdv Try the snippet above

**Comment by bryevdv** [comment]
Sorry, my point was that I am in the middle of a release and overwhelmed with tasks. I don't have time at the moment to try any snippets, so a screen shot would provide a nearly-immediate way to help triage this issue, which is a huge help. Also, please note: *complete* code samples, that can be run exactly as-is are *far, far better* than snippets. Presumably an issue reporter has that at hand, and could provided it easily. If project maintainers have to construct runnable code around snippets for 1000 issues that becomes an unmanageable burden for a few people, quickly.

**Comment by rs2** [comment]
@bryevdv Found the bug, let me do a quick PR. 1 char change only :smile:

**Comment by rs2** [comment]
@bryevdv PR open for review: https://github.com/bokeh/bokeh/pull/5657
