### ISSUE TITLE
Using multiple variation of tools causes a UserWarning

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#5656]
`bokeh` `0.12.3`

Repro:
* Add `tools='box_select,xbox_select,wheel_zoom,xwheel_zoom'` to `figure`.
* Get: `site-packages\bokeh\plotting\helpers.py:387: UserWarning: BoxSelectTool,WheelZoomTool are being repeated`

Expected behavior:
The code references the same classes, but instantiates them with different properties and expects different behavior. The warning should not appear in this case.

**Comment by mattpap** [comment]
This is a duplicate of issue #5135.

**Comment by rs2** [comment]
@mattpap Thank you! My bad (homework not done properly)
