### ISSUE TITLE
Drop source maps from our build

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5660]
At least temporarily, until we have a simpler build pipeline. Source maps were broken on and off over past years and, I think, caused more harm than good for development. Also using source maps is very unreliable when combined with coffeescript, because generated code can often surprise you and it's much better to debug the actual javascript.

**Comment by bryevdv** [comment]
I'm personally fine with this. Lately (the last few months) I have not even been able to debug at all sometimes due to some problem with source maps. I can read pure JS even if I don't like writing it.

**Comment by mattpap** [comment]
I'm hoping that when we unify our workflow with typescript, then having reliable source maps won't be an issue.

**Comment by mattpap** [comment]
Source map support was fixed in PR #6585.
