### ISSUE TITLE
tool labels appears empty on hover

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#5661]
On the [development version of the docs](http://bokeh.pydata.org/en/dev/docs/gallery/stocks.html) when you hover over a tool the tool label shows up as blank:

<img width="255" alt="screen shot 2017-01-06 at 10 52 09 am" src="https://cloud.githubusercontent.com/assets/4806877/21723393/3dbd6a62-d3fe-11e6-9519-efd4e25d710e.png">

In the [latest release](http://bokeh.pydata.org/en/latest/docs/gallery/stocks.html) this does not seem to occur:

<img width="262" alt="screen shot 2017-01-06 at 10 52 19 am" src="https://cloud.githubusercontent.com/assets/4806877/21723398/40e8621e-d3fe-11e6-85d3-379c10f22f96.png">

**Comment by bryevdv** [comment]
@birdsarah any ideas where to look? If this is a quick fix I'd like to make it over the weekend before release

**Comment by jsignell** [comment]
@bryevdv I can try to look for it. I just need to get set up.

**Comment by bryevdv** [comment]
Thanks! LMK if I can answer any questions or help with anything

**Comment by jsignell** [comment]
The text is there, but the styling is messed up. I set it to black from the console and this is what it looks like:
<img width="140" alt="screen shot 2017-01-06 at 5 19 26 pm" src="https://cloud.githubusercontent.com/assets/4806877/21734995/64767f5a-d434-11e6-92bd-211ae9fb14a5.png">
 
In the non-documentation example it looks like this:
<img width="118" alt="screen shot 2017-01-06 at 5 19 52 pm" src="https://cloud.githubusercontent.com/assets/4806877/21735000/7275e5b4-d434-11e6-9a90-9ce80aa9f4ac.png">

**Comment by bryevdv** [comment]
That's weird. ping @mattpap are you aware of any CSS changes that might have intersected with this?

**Comment by mattpap** [comment]
The theme we use in docs sets `button { color: #fff }` in `main.css` and this gets propagated to tool buttons, which don't specify foreground color. I'm not sure what has changed recently. To fix this we either set color explicitly or reopen #2933 and fix it properly.

**Comment by mattpap** [comment]
Related issue #5102.
