### ISSUE TITLE
Conda package uses prelink script

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#5663]
When installing the latest rc of 0.12.4 from the `bokeh` channel, `conda` issues the following warning.

```bash
$ conda install -c bokeh/label/dev bokeh
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /opt/conda:

The following packages will be UPDATED:

    bokeh: 0.12.3-py35_0 defaults --> 0.12.4rc1-py_1 bokeh/label/dev

Proceed ([y]/n)? 

Unlinking packages ...
[      COMPLETE      ]|################################################################################################################################| 100%
Linking packages ...
[bokeh               ]|                                                                                                                                |   0%
Package bokeh/label/dev::bokeh-0.12.4rc1-py_1 uses a pre-link script. Pre-link scripts are potentially dangerous  discouraged.
This is because pre-link scripts have the ability to change the package contents in the
package cache, and therefore modify the underlying files for already-created conda
environments.  Future versions of conda may deprecate and ignore pre-link scripts.
[      COMPLETE      ]|################################################################################################################################| 100%
```

**Comment by bryevdv** [comment]
Yes this needs to be sorted out. There's a new kind of "noarch" package available now, but I don't want to rely on it until there is greater adoption of the new conda versions required to install it. An  alternative for users is to only use packages in the default repo -- @ilanschnell rebuilds those as not-noarch packages. But that would exclude installing dev builds at least for now, and there is also sometimes a few days lag getting new bokeh releases in the default channel.

**Comment by bryevdv** [comment]
This will be resolved in #5735

**Comment by sbourdeauducq** [comment]
What is the exact solution for this problem? We and a number of other projects have it, and we would appreciate clear instructions on how to fix it.

**Comment by sbourdeauducq** [comment]
It seems the solution is to change "noarch_python: true" into "noarch: python", but then it won't install at all because it requires conda 4.3, but when having the conda-forge channel present only conda 4.2 can be installed. I am absolutely amazed by how commonplace this kind of obnoxious breakage seems to be when using conda.

**Comment by bryevdv** [comment]
>  I am absolutely amazed by how commonplace this kind of obnoxious breakage seems to be when using conda.

Speaking as an OSS maintainer, it's this kind of unproductive comment that is demoralizing and burnout-inducing in OSS devs. I empathize with any frustrations you have, but building software for hundreds of thousand of users is hard, especially when you started with no users and can't read the future. If you enjoy free software, please find a way to channel your frustrations into something usefu and productive (i.e., help out).
