### ISSUE TITLE
Problem Updating Large Data on Scatter Plot Using "add_next_tick_call_back"

### ISSUE THREAD

**Issue by wanglouis49** [bokeh/bokeh#5665]
I am implementing an app with a minimum case similar to the [Updating From Threads example](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#updating-from-threads). It contains an expensive numerical computation, so we want to load the page with a scatter plot first while letting a thread to do the work. Once the computation is done the thread updates the scatter plot thru "add_next_tick_call_back" with one shot. However, the problem here is that when the size of the data is large (in my case more than 50,000 points), the scatter plot will show the updates first and then suddenly disappear. We've been debugging this for a few days and couldn't figure out how to solve it. We suspect it has something to do with the buffer size. Or, is there any better way to do it?

```
from functools import partial
from random import random
from threading import Thread
import time
import numpy as np
from os.path import dirname, join
import ipdb

from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure
from bokeh.document import without_document_lock

from tornado import gen


# When the size gets too large, it has some problems
size = 50000


# this must only be modified from a Bokeh session callback
data = dict(pca_x=np.zeros(size), pca_y=np.zeros(size))
source = ColumnDataSource(data=data)

# This is important! Save curdoc() to make sure all threads
# see then same document.
doc = curdoc()

@without_document_lock
@gen.coroutine
def update(x, y):
    source.data['pca_x'] = x
    source.data['pca_y'] = y
    #ipdb.set_trace()

def blocking_task(size):
    time.sleep(2)  # simulating the expensive computation
    x = np.random.uniform(low=-1, high=1, size=size)
    y = np.random.uniform(low=-1, high=1, size=size)
    doc.add_next_tick_callback(partial(update, x=x, y=y))
    #ipdb.set_trace()

p = figure(x_range=[-1, 1], y_range=[-1,1])
l = p.scatter(x='pca_x', y='pca_y', source=source)

doc.add_root(p)

thread = Thread(target=blocking_task, args=(size,))
thread.start()
```

**Comment by bryevdv** [comment]
@wanglouis49 without any details or context, it is impossible to tell if this is a bug report (which the issue tracker is for) or a support request (which the issue tracker is NOT for). My best guess is that you are looking for help and support, in which case the appropriate place to go is the mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

**Comment by wanglouis49** [comment]
I'm sorry this is the first time I post an issue here so somehow I post it without finishing my problem description.  I'm writing the description right now and I'm sure it's an interesting one.

**Comment by bryevdv** [comment]
Leaving as `discussion` until things are futher characterized. Can you possibly try with `0.12.4rc1` ? The new array protocol may have some bearing on this.

**Comment by wanglouis49** [comment]
@bryevdv Thank you for your reply. I've tried it with 0.12.4rc1. Unfortunately, it still has the same problem.

**Comment by bryevdv** [comment]
Well, this just worked with me on OSX/Safari with `size=200000`. So this is evidently a platform specific issue. Can you provide more information about platform and browser versions? Unfortunately there may not be anything possible to do directly. Different browsers have different inherent limitations that we have no control over. I would suggest in any case that with this many points you should probably be looking at [Datashader](http://datashader.readthedocs.io/en/latest/) anyway. Even with a 1000x1000 pixel canvas, with 50k points, each point can only take up 20px without overlap, which will already not be the case with `size=5` circle sizes. Datashader is intended to solve both the problems here: 

* bandwidth compression of large datasets
* effective and efficacious visual representation of data when there is overplotting

**Comment by wanglouis49** [comment]
I'm on OSX  and tried both with Safari and Chrome. ```size=200,000``` worked for me on Safari but not Chrome. Yes, it seems to be a platform specific issue. [OSX: 10.11.5; Chrome: 55.0.2883.95; Safari: 9.1.1; Bokeh: 0.12.4rc1; Numpy: 1.11.2]

I would like to add some followups and seek for your advice. Our app has 3 scatter plots and multiple histograms placed on separate tabs. All of them are linked thru one ColumnDataSource, and there are callbacks to allow for points selection from either of them. Therefore, we have a relatively big ColumnDataSource - but not necessarily with lots of columns - it may contains lots of column. Each plot is generated from one or two of them for histograms and scatter plots, respectively.

I modified my previous minimum example as below to better illustrate my case. You may notice the ColumnDataSource has many columns. We let the page load first and wait on a thread for the expensive backend algorithms to update the scatter plots. For one scatter plot we only update two columns ```pca_x``` and ```pca_y```. Now if we have ```size=20,000``` it works for Safari but not Chrome. If ```size=50,000`` the points will disappear on both Chrome and Safari.

I'm starting to use Datashader but I would like to understand why the points will disappear. I was wondering do you have any idea?


```
from functools import partial
from random import random
from threading import Thread
import time
import numpy as np

import bokeh
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure
from bokeh.document import without_document_lock

from tornado import gen

print "Bokeh version: ", bokeh.__version__
print "Numpy version: ", np.__version__
print "Tornado version: ", tornado.version

# When the size gets too large, it has some problems
size = 50000


# this must only be modified from a Bokeh session callback
data = dict(
	pca_x=np.zeros(size), 
	pca_y=np.zeros(size),
	a=np.zeros(size),
	b=np.zeros(size),
	c=np.zeros(size),
	d=np.zeros(size),
	e=np.zeros(size),
	f=np.zeros(size),
	g=np.zeros(size),
	h=np.zeros(size),
	i=np.zeros(size),
	j=np.zeros(size),
	k=np.zeros(size),
	l=np.zeros(size),
	m=np.zeros(size),
	n=np.zeros(size),
	)
source = ColumnDataSource(data=data)

# This is important! Save curdoc() to make sure all threads
# see then same document.
doc = curdoc()

@without_document_lock
@gen.coroutine
def update(x, y):
	source.data.update({'pca_x': x, 'pca_y': y})

def blocking_task(size):
    time.sleep(1)
    x = np.random.uniform(low=-1, high=1, size=size)
    y = np.random.uniform(low=-1, high=1, size=size)
    doc.add_next_tick_callback(partial(update, x=x, y=y))

p = figure(x_range=[-1, 1], y_range=[-1,1])
l = p.scatter(x='pca_x', y='pca_y', source=source, size=1)

doc.add_root(p)

thread = Thread(target=blocking_task, args=(size,))
thread.start()
```

**Comment by wanglouis49** [comment]
@bryevdv Could you kindly take a look at the updated case?

**Comment by bryevdv** [comment]
@wanglouis49 As I mentioned different browsers have different inherent limitations, e.g. stack size limits. If the app is bumping up against those, it will probably fail in unpredictable ways. We have no control over these browser limits whatsoever. I note that you are creating 16x50k = 800k total elements. I can almost guarantee this will bring down most browsers. My best suggestion is still to look to data shader. 

Ping @jbednar in case you'd like to add any comments.

**Comment by jbednar** [comment]
I agree completely -- Bokeh developers can't help with limitations of the various available browsers, and no matter what Bokeh does, a large enough dataset will always end up causing problems if all of the data needs to be transferred into the browser.  

Luckily, this seems like a perfect use case for datashader.  With datashader, the size of the dataset will no longer matter at all at the browser level -- datashader transfers only a fixed-size image to the browser, regardless of the number of points involved. So I'd recommend following some of the notebooks at https://github.com/bokeh/datashader/examples and https://anaconda.org/jbednar/notebooks instead of using pure Bokeh.

**Comment by wanglouis49** [comment]
Cool!! thank you very much for your feedbacks.
