### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#5666]
Verify Bokeh functions full with python 3.6 before next Anaconda release cutoff.

**Comment by bryevdv** [comment]
> When is that? Shouldn't this issue be resolved for 0.12.4?

~10 days, so yes, to the extent possible. Preliminary testing seems fine, but I would like to make as thorough a survey as possible.

**Comment by bryevdv** [comment]
I tested almost all the apps, several notebooks, and several random plotting and charts examples. I think things are fairly safe, or at least safe enough for now. I'll leave this issue up for getting py3.6 into CI testing.
