### ISSUE TITLE
Integration test reports are garbled

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5670]
See e.g. https://s3.amazonaws.com/bokeh-travis/189879574/tests/pytest-report.html. Styles and images aren't loaded (404).

**Comment by bryevdv** [comment]
@birdsarah any quick ideas what could possibly cause this? If the styles are stored somewhere else externally maybe one of us accidentally did something to them.

**Comment by mattpap** [comment]
btw. This is needs to be fixed ASAP.

**Comment by birdsarah** [comment]
Bryan mentioned it to me yesterday. I will try and look at it this week. The first thing I was going to try was pinning pytest-html to 0.10 ish

**Comment by mattpap** [comment]
Pinning pytest-html to 1.7 worked.
