### ISSUE TITLE
Plots overlays pop window

### ISSUE THREAD

**Issue by Orasporas** [bokeh/bokeh#5674]
Hi, so i have problem that plots overlays pop window as showed in screenshot. My code is here https://github.com/Orasporas/zintistyrimas/blob/master/mainveik.py

![screenshot from 2017-01-08 19-19-09](https://cloud.githubusercontent.com/assets/23524922/21752310/7c9e10ce-d5de-11e6-80f8-494081d1ff44.png)

**Comment by bryevdv** [comment]
@Orasporas did you mean to close this issue?

**Comment by Orasporas** [comment]
Yes, i found solution, just have to make z index number for pop windows
like 99 and it worked, no overlay(overlap).

**Comment by bryevdv** [comment]
OK thanks for the update. If you think there is a place where additional documentation would help please let us know (or make a small pull request)
