### ISSUE TITLE
Permission Denied error when invoking show() from inside Jupyter Notebook

### ISSUE THREAD

**Issue by tinloaf** [bokeh/bokeh#5677]
Hi,

I'm using bokeh 0.12.3 and jupyter 1.0.0. I'm writing some code that produces a simple bar chart and calls show() on this bar chart inside the notebook.

Here's the backtrace that I get:
```
PermissionError                           Traceback (most recent call last)
<ipython-input-3-e94210215dfe> in <module>()
      1 results = r._get_results()
----> 2 v.visualize(results, None, None)

/home/lukas/src/tcpsp/TCPSPsuite/scripts/visualizer.py in visualize(self, results, x_axis, y_axis)
     11         chart = Bar(df, 'job_count', values='elapsed', agg='mean')
     12 
---> 13         show(chart)

/home/lukas/.virtualenvs/tcpsp/lib/python3.5/site-packages/bokeh/io.py in show(obj, browser, new, notebook_handle)
    312     if obj not in _state.document.roots:
    313         _state.document.add_root(obj)
--> 314     return _show_with_state(obj, _state, browser, new, notebook_handle=notebook_handle)
    315 
    316 

/home/lukas/.virtualenvs/tcpsp/lib/python3.5/site-packages/bokeh/io.py in _show_with_state(obj, state, browser, new, notebook_handle)
    330 
    331     if state.file or not shown:
--> 332         _show_file_with_state(obj, state, new, controller)
    333 
    334     return comms_handle

/home/lukas/.virtualenvs/tcpsp/lib/python3.5/site-packages/bokeh/io.py in _show_file_with_state(obj, state, new, controller)
    335 
    336 def _show_file_with_state(obj, state, new, controller):
--> 337     filename = save(obj, state=state)
    338     controller.open("file://" + filename, new=_new_param[new])
    339 

/home/lukas/.virtualenvs/tcpsp/lib/python3.5/site-packages/bokeh/io.py in save(obj, filename, resources, title, state, validate)
    394 
    395     filename, resources, title = _get_save_args(state, filename, resources, title)
--> 396     _save_helper(obj, filename, resources, title, validate)
    397     return os.path.abspath(filename)
    398 

/home/lukas/.virtualenvs/tcpsp/lib/python3.5/site-packages/bokeh/io.py in _save_helper(obj, filename, resources, title, validate)
    462         html = standalone_html_page_for_models(obj, resources, title)
    463 
--> 464         with io.open(filename, "w", encoding="utf-8") as f:
    465             f.write(decode_utf8(html))
    466 

PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.5/runpy.html'
```

It seems like I'm not the only one experiencing the problem: see for example https://github.com/yhat/rodeo/issues/211

I'm pretty sure the problem is in _detect_filename() in io.py: If no filename to save a chart to is supplied, it tries to save the file (with an autodetected filename) into the directory of the currently executing file (more exactly: the file executing in the topmost stackframe, which is assumed to be the main file being run.) This fails spectacularly if that file is located in a read-only location as is the case when you run an jupyter notebook, which on my system seems to use "/usr/lib/python3.5/runpy.py" to run the notebook.

I think the cleanest solution would be to use a temporary directory if no save-to directory is specified. If no directory is specified, the user is probably not really interested in the file, but only needs it temporarily: This happens in the show() method, for example.

Is there a reason for saving temporary files in the directory of the script? In that case, should the save() method be amended by a "temporary" argument (with default False), which in turn tells _detect_filename() to use a temporary directory? In that case, show() could set that flag and avoid the permission problem…?

I'd be willing to cook up a pull request if I get any feedback on how you think this problem should be solved.

**Comment by bryevdv** [comment]
Hi, can you provide a complete sample code? It's hard to say anything concrete when speculation is required. For instance, the code path taken suggests you have executed `ouptut_file` at some point (which would explain things). Is this the case? Providing a complete minimal code sample is the most efficient way to help us help you.

**Comment by tinloaf** [comment]
D'Oh, the problem does actually not arise when output_notebook() is properly called, since then save() seems not to be called at all… Sorry, that was kinda stupid on my side.

However, I'm still not sure whether to consider this a bug or not: With output_file(), it is probably safe to assume that the caller of show() is interested in the file. Still, just assuming that it should be put into the directory of the topmost executing file…? I do not have a better idea, though. I'll close this bug (since it works for notebooks when you set them up properly).

**Comment by bryevdv** [comment]
@tinloaf no worries, I will re-open this for discussion because I do think you have a possible valid issue about assumed file location. 

Ping @philippjfr (I think you added this feature?) for thoughts?

**Comment by philippjfr** [comment]
@bryevdv I'm afraid I have no real idea what's going on here. I don't think I ever touched anything to do with file saving or file locations. Maybe I just don't understand the actual issue.

**Comment by bryevdv** [comment]
@philippjfr no worries, someone added a feature to save to an implicit filename and I misremembered it as you. I think it may have actually been @almarklein

**Comment by mattpap** [comment]
We may need to add additional clause in `_detetect_filename()`, something along `os.access(parent_dir, os.W_OK | os.X_OK)`.

**Comment by mattpap** [comment]
Also file name detection magic could be disabled in IPython. This can be detected with `if IPython is None or IPython.get_ipython() is None:`. Alternatively we could use `join(os.getcwd(), "unnamed.%s" % ext)`. @bryevdv, any preference?

**Comment by bryevdv** [comment]
I'm honestly not very fond of the feature at all so I am probably not the best person to ask. @almarklein do you have an opinion about @mattpap question?

**Comment by almarklein** [comment]
A bit late to the party, sorry; I still get Bokeh emails, but they get in a seperate folder which I stopped checking.

@bryevdv yes it was @mattpap and me who introduced this feature. I'm surprised that we don't have some sort of test for writability of the file name. Maybe we should test that the filename is relative to `os.path.expanduser('~')`, and use the temp dir otherwise.

As for @mattpap's questions, I don't really follow, can you provide some context?

**Comment by bryevdv** [comment]
@tinloaf A PR would be appreciated, are you still interested in working on one? 

My personal preference is just to always use a writable temp directory. I think the observation that if someone is calling `show` without `output_file`, they they probably just want to see the result in a file, and don't really care about a file. I think that actually fills in a gap that currently exists. 

@mattpap @almarklein does that sound ok? I think wanting `show` to "just work" i.e. open a browser with the output without a filename is reasonble. I think if you *do* want the file, it is not too much to require that the filename be specified to mark that interest.

**Comment by almarklein** [comment]
I completely agree.

**Comment by bryevdv** [comment]
@tinloaf I think we have agreement (always use tmp file) Are you still interested in working up a PR?

**Comment by tinloaf** [comment]
Hi. Sorry, didn't check on this issue for a while. Il'll cook comething up! This shouldn't be to complicated.

**Comment by jsignell** [comment]
@bryevdv I can't recreate this anymore. Possibly it got fixed as collateral on another PR.

**Comment by bryevdv** [comment]
@jsignell are you sure the destination for the output file was to a read-only location? I'd be surprised if any recent work resolved this.

**Comment by jsignell** [comment]
@bryevdv I see now.
