### ISSUE TITLE
BokehJS reloads everytime a Jupyter Notebook autosaves

### ISSUE THREAD

**Issue by grromrell** [bokeh/bokeh#5697]
Unclear whether this is intended behavior or not. Everytime a Jupyter notebook autosaves (or manually saves for that matter) BokehJS reloads, causing all of the plots to reload as well. This causes a severe interruption of workflow, as every 2-3 minutes the entire notebook freezes up and all plot must refresh. I did not have this issue prior to 0.12.0

**Comment by grromrell** [comment]
Here is what I see in the console when the notebook saves:

Bokeh: BokehJS not loaded, scheduling load and callback at Tue Jan 10 2017 14:41:21 GMT-0600 (Central Standard Time)
VM727:47 Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-0.12.1.min.js
VM727:47 Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.1.min.js
VM727:47 Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-compiler-0.12.1.min.js
VM728:22 Bokeh: BokehJS is being loaded, scheduling callback at Tue Jan 10 2017 14:41:21 GMT-0600 (Central Standard Time)
VM727:40 Bokeh: all BokehJS libraries loaded
VM727:86 Bokeh: BokehJS plotting callback run at Tue Jan 10 2017 14:41:22 GMT-0600 (Central Standard Time)
bokeh-0.12.1.min.js:3 Bokeh: setting log level to: 'info'
VM727:68 Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-0.12.1.min.css
VM727:70 Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.1.min.css
VM728:81 Bokeh: BokehJS plotting callback run at Tue Jan 10 2017 14:41:22 GMT-0600 (Central Standard Time)
VM727:17 Bokeh: all callbacks have finished

**Comment by bryevdv** [comment]
I can't reproduce this on `0.12.4` with s simple notebook. Can you provide a sample notebook that exhibits the problem and much more detailed information about your system, versions, etc.

**Comment by grromrell** [comment]
I did some more digging and it only occurs when using conda "nb_conda_kernels." The environment I am using now has the latest Bokeh (0.12.4), the latest Jupyter (4.1.1), the latest nb_conda_kernels (2.0,0) and the latest nb_conda (2.0,0). I am using Ubuntu 16.04, but have replicated the error on Windows 8 as well. It happens with a plot of any size. Hopefully this helps replicate the problem. This may be an issue to raise over at anaconda-nb-extensions instead, though it looks like activity there is pretty dead.

**Comment by bollwyvl** [comment]
I do recall this from some earlier versions, but thought we had mostly figured those out.

Also having difficulty reproducing this, but have only fired it up on osx... will have a look on a vm when I get one set up!

Neither `nb_conda` nor `nb_conda_kernels` has any save hooks that i can recall/find (though nbpresent does).

> Jupyter (4.1.1)

Hm... notebook just went to 4.3.1, but the `jupyter` metapackage is still `1.0.0`.

It really would help if you could drop in here:
- a (preferably minimal) notebook that exhibits the condition
- the output of `conda list`
- the output of `jupyter nbextension list`

Thanks!

**Comment by grromrell** [comment]
Oops I thought I was on the latest jupyter notebook. Upgrading to 4.3.1 solved this issue. Sorry the confusion!

**Comment by bollwyvl** [comment]
hooray!
