### ISSUE TITLE
not necessary loop in weather example? 

### ISSUE THREAD

**Issue by chananshgong** [bokeh/bokeh#5699]
see the update plot method below in the [main.py](**url**)
```
def update_plot(attrname, old, new):
    city = city_select.value
    plot.title.text = "Weather data for " + cities[city]['title']

    src = get_dataset(df, cities[city]['airport'], distribution_select.value)
    for key in STATISTICS + ['left', 'right']:
        source.data.update(src.data)
```

Why do we need the for loop over key ?
Isn't a single `source.data.update(src.data)` enough?

**Comment by bryevdv** [comment]
I think it was just an accident. I am guessing the original code looped and updated individual keys, which is usually discouraged. Probably someone updated to use `update` in a hurry but forgot to remove the loop. Would you like to make a Pull Request to update the example?
