### ISSUE TITLE
Setting Selected Property of ColumnData does not Change Selected Row.

### ISSUE THREAD

**Issue by chananshgong** [bokeh/bokeh#5701]
To get the selected rows of a DataTable you access the property  `source.selected['1d']['indices']`. I tried to set the property so selection is based on code, but it doesn't work. What other way do I have to set the selected rows (preferably with python not JS) ?
In the example below, based on the documentation, I set the selected row to be equal `3` but the table is not selected in the browser.
```
from datetime import date
from random import randint

from bokeh.io import output_file, show
from bokeh.layouts import widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

output_file("data_table.html")

data = dict(
    dates=[date(2014, 3, i + 1) for i in range(10)],
    downloads=[randint(0, 100) for i in range(10)],
)
source = ColumnDataSource(data)

columns = [
    TableColumn(field="dates", title="Date", formatter=DateFormatter()),
    TableColumn(field="downloads", title="Downloads"),
]
data_table = DataTable(source=source, columns=columns, width=400, height=280)
source.selected['1d']['indices'] = [3]
show(widgetbox(data_table))
```

**Comment by jsvp** [comment]
I have a similar issue. I need to change the selection programmatically based on a list of indices and cannot find a way to implement this. Have you figured out a way to do this?

**Comment by bryevdv** [comment]
This was fixed at some point. Original code with update for `selected.indices`:

```
from datetime import date
from random import randint

from bokeh.io import output_file, show
from bokeh.layouts import widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

output_file("data_table.html")

data = dict(
    dates=[date(2014, 3, i + 1) for i in range(10)],
    downloads=[randint(0, 100) for i in range(10)],
)
source = ColumnDataSource(data)

columns = [
    TableColumn(field="dates", title="Date", formatter=DateFormatter()),
    TableColumn(field="downloads", title="Downloads"),
]
data_table = DataTable(source=source, columns=columns, width=400, height=280)
source.selected.indices= [3]
show(widgetbox(data_table))
```

yields:

<img width="401" alt="screen shot 2018-05-10 at 12 03 41" src="https://user-images.githubusercontent.com/1078448/39888645-459096c4-544a-11e8-9a0d-a19251a58273.png">

**Comment by BCoat** [comment]
@bryevdv  I have tried your solution in a Jupyter notebook with the version 12.16 of bokeh and cannot make it work. (Got a source.selected equal to None) 
I don't understand in which environment your answer was meant to work.

**Comment by bryevdv** [comment]
@BCoat the code above works fine in a notebook:

<img width="829" alt="screen shot 2018-05-17 at 08 44 12" src="https://user-images.githubusercontent.com/1078448/40181360-c860e3da-599d-11e8-815b-fbb8f166367e.png">

The most likely explanation is that you have a different version of Bokeh installed in the environment that has the notebook, so that you are not actually using the version of Bokeh that you intend to be. In any case, this seems to be a support/usage question now, so I'd request further discussion move to the mailing list.

**Comment by BCoat** [comment]
Thanks, for the quick answer. Indeed that must be this kind of mistake from me. Sorry for posting here, I was not aware of the functioning of issues and support/usage of the project.
