### ISSUE TITLE
Dropdown not working with Bokeh 0.12.4

### ISSUE THREAD

**Issue by eleanor2017** [bokeh/bokeh#5703]
Hello, 

I have updated Bokeh 0.12.4 and the dropdown menu is not working.
The issue is here : http://stackoverflow.com/questions/41307136/dropdown-not-working-with-bokeh/41578773?noredirect=1#comment70364816_41578773

I am using Jupyter Notebook and my code is the following  : 
```
from bokeh.io import output_notebook, show
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, CustomJS, Select
from bokeh.plotting import figure
import pandas as pd
output_notebook()

url = "http://ichart.yahoo.com/table.csv?s=%s&a=0&b=1&c=2000&d=0&e=1&f=2015"
AAPL = pd.read_csv(url % "AAPL", parse_dates=['Date'])
MSFT = pd.read_csv(url % "MSFT", parse_dates=['Date'])
IBM  = pd.read_csv(url % "IBM",  parse_dates=['Date'])
max_price = max(AAPL['Close'].max(), MSFT['Close'].max(), IBM['Close'].max())

source = ColumnDataSource({
    'xAAPL' : AAPL['Date'], 'yAAPL' : AAPL['Close'], 'yAAPLp' : AAPL['Close'],
    'xMSFT' : MSFT['Date'], 'yMSFT' : MSFT['Close'], 'yMSFTp' : MSFT['Close'],
    'xIBM'  :  IBM['Date'], 'yIBM'  :  IBM['Close'], 'yIBMp'  :  IBM['Close']
})

p = figure(width=500, height=250, x_axis_type="datetime", y_range=[0, max_price+10])
r_aapl = p.line('xAAPL', 'yAAPL', source=source, color='navy',  alpha=0.5)
r_msft = p.line('xMSFT', 'yMSFT', source=source, color='red',   alpha=0.5)
r_ibm  = p.line('xIBM',  'yIBM',  source=source, color='green', alpha=0.5)

callback = CustomJS(args=dict(r_aapl=r_aapl, r_msft=r_msft, r_ibm=r_ibm), code="""
    f = cb_obj.value;
    r_aapl.visible = false;
    r_msft.visible = false;
    r_ibm.visible = false;
    if      (f == "AAPL") { r_aapl.visible = true; }
    else if (f == "MSFT") { r_msft.visible = true; }
    else if (f == "IBM")  { r_ibm.visible = true; }
    else {
        r_aapl.visible = true;
        r_msft.visible = true;
        r_ibm.visible = true;
    }
""")

shares = ['AAPL', 'MSFT', 'IBM', 'All']
multi_select = Select(title="Select Shares:", value=shares[3], options=shares, callback=callback)
show(column(multi_select, p))
```

The problem is I see the dropdown menu but not the graph.
If I change my code for  : 
```
source = ColumnDataSource({
    'xAAPL' : AAPL['Date'].tolist(), 'yAAPL' : AAPL['Close'].tolist(), 'yAAPLp' : AAPL['Close'].tolist(),
    'xMSFT' : MSFT['Date'].tolist(), 'yMSFT' : MSFT['Close'].tolist(), 'yMSFTp' : MSFT['Close'].tolist(),
    'xIBM'  :  IBM['Date'].tolist(), 'yIBM'  :  IBM['Close'].tolist(), 'yIBMp'  :  IBM['Close'].tolist(),
})
```
then I see the graph but the dropdown menu is not working.

I use ubuntu 16.04 LTS
I try to work on Firefox and Chrome but I get the same problem in both browser.
The environment version are into the attached file (as well as the way I have created the environment).
 And javascript is version 1.7

[environment.txt](https://github.com/bokeh/bokeh/files/699815/environment.txt)

**Comment by bryevdv** [comment]
(formatted, added some missing imports)

@eleanor2017 is there any output in your Browser java script console?

**Comment by eleanor2017** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/24685589/21863596/19dad244-d80c-11e6-9818-8cbc5fed6c68.png)

**Comment by bryevdv** [comment]
@eleanor2017 I am looking for the output of the "javascript console" which should show a bunch of log messages. I am trying to see if there are JS errors being reported. It should look something like this:

<img width="1224" alt="screen shot 2017-01-11 at 1 44 46 pm" src="https://cloud.githubusercontent.com/assets/1078448/21863813/8cba8dd4-d804-11e6-9c12-41a9f5112da5.png">

 and should be accessible via:

```
To open the dedicated Console panel, either:

Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac).
```

**Comment by eleanor2017** [comment]
With Firefoz and FireBug here are the messages : 
![screenshot2](https://cloud.githubusercontent.com/assets/24685589/21863951/78cf54ae-d80d-11e6-80fb-0d437d4cd8ad.png)

**Comment by bryevdv** [comment]
OK well an immediate problem is that the version of Bokeh that your notebook sees is not `0.12.4`, it is `0.12.0`. Is it possible that you updated Bokeh in a different env from where your notebook is installed?

**Comment by bryevdv** [comment]
resolved on gitter: notebook env/bokeh env mismatch
