### ISSUE TITLE
Move abstract out of properties.py

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5704]
Want everything in `properties.py` to be of interest to users, `abstract` is almost certainly never. 

Propose `has_props.py` or `model.py` @mattpap do you have a preference?

**Comment by mattpap** [comment]
I think it belongs to `has_props.py`, given that there are no other decorators of this kind (otherwise, they could get their own file).

**Comment by mattpap** [comment]
Or maybe we should add `bokeh.properties.decorators`?

**Comment by bryevdv** [comment]
I've already started putting it in `has_props.py` I think that's fine until there is more than one decorator :)
