### ISSUE TITLE
Italic, vertical axis labels don't look good

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5714]
See e.g. https://s3.amazonaws.com/bokeh-travis/0.12.4-0385aa9/charts/file/iris_blend.png. It looks like each letter is drawn with different angle.

**Comment by mattpap** [comment]
This actually may be a bug in phantomjs, or just phantom using outdated webkit.

**Comment by mattpap** [comment]
This was a problem with phantomjs.

**Comment by p-himik** [comment]
@mattpap I can reproduce this error.
- bokeh=0.13.0=py35_0
- phantomjs=2.1.1=0
- selenium=3.12.0=py35_0

An example for y-axis:
![image](https://user-images.githubusercontent.com/4410314/44262697-2bbcbd00-a246-11e8-8012-438319bc4e73.png)

An example for x-axis with `major_label_orientation` set to `'vectical'`:
![image](https://user-images.githubusercontent.com/4410314/44262719-40995080-a246-11e8-8fe8-4f17a3cd32af.png)

**Comment by p-himik** [comment]
Vertical axes with `axis_label_text_font_style = 'normal'` still look broken.

**Comment by p-himik** [comment]
Perhaps this issue could be reopened or transferred to another one for the browser replacement? Especially since PhantomJS is abandoned at this point.

**Comment by bryevdv** [comment]
There's already an issue to make chromedriver the default.

**Comment by p-himik** [comment]
@bryevdv Could you please link it?
I've just checked all open issues that contain "chrome" or "chromedriver", and there's nothing related, unless I'm incredibly blind (which is, of course, always a possibility).
There definitely **was** an issue regarding moving test image diff to a headless Chrome (#6594), but it's been implemented, and it affects only tests.

**Comment by p-himik** [comment]
FWIW, headless Firefox didn't work because it lacks `log` command, but headless Chrome worked fine, apart from the fact that I had to file https://bugs.chromium.org/p/chromium/issues/detail?id=875241

**Comment by bryevdv** [comment]
@p-himik I can't find the issue I was thinking of, where I recalled making a specific comment about making chrome headless the default at some point. In any case, since the issue is not locatable (perhaps it was only tangentially related) would you mind making a new issue to switch the default export driver to be chromedriver. I believe there is still work to do, last I checked on retina displays the device pixel ratio was not being handled correctly.
