### ISSUE TITLE
Bad formatting in selected docstring

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5718]
Ends up rendering like this

<img width="680" alt="screen shot 2017-01-13 at 10 38 03 am" src="https://cloud.githubusercontent.com/assets/1796208/21937294/71c87792-d97c-11e6-929f-ebf03c695e8a.png">

Guessing bad use of bullets is causing some text to be bold and the whole thing to be unclear.

While there the wording in this docstring could be a lot clearer.

**Comment by bryevdv** [comment]
For reference the docstring is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L16

A better approach is probably a `code-block:: python`` that just gives the dict in "exploded" form, which comments inline describing each key.
