### ISSUE TITLE
text_align attribute in NumberFormatter not doing anything

### ISSUE THREAD

**Issue by ianlcassidy** [bokeh/bokeh#5721]
When making a `datatable`, I want to right align numerical values in the table, but when I set the `text_align` attribute in `NumberFormatter`, the values continue to remain left aligned.  Here is my enviornment:
* Python 2.7.12 :: Anaconda 4.1.1 (64-bit)
* numpy==1.11.1
* pandas==0.18.1
* bokeh==0.12.4
* Windows 7, Chrome

And here is a code snippet:
```
import pandas as pd
import numpy as np
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, NumberFormatter, TableColumn
from bokeh.plotting import show

df = []
for ii in range(1, 11):
    df.append({'x': ii, 'y': 1000 * np.random.rand()})
df = pd.DataFrame(df)

source = ColumnDataSource(data=df)

columns = [
    TableColumn(field='x', title='Col 1'),
    TableColumn(field='y', title='Col 2',
                formatter=NumberFormatter(format='$0,0.00',
                                          text_align='right')),
]

dt = DataTable(source=source, columns=columns, width=500, height=200, row_headers=False)

show(dt)
```

Here is the output I am getting in my Jupyter Notebook:
![untitled](https://cloud.githubusercontent.com/assets/6929405/21940662/53797720-d993-11e6-9a39-a1f2a6d11f80.png)

I would expect that the dollar amounts in `Col 2` would be right aligned, but they aren't.

**Comment by CatalinLB** [comment]
I have the same Problem. Same Environment (Browser Safari and Mozilla)

**Comment by mathfish** [comment]
I have the same/similar issue trying to center text using StringFormatter(). 

Setting text_align = "center" does not affect change

**Comment by shea-parkes** [comment]
Not only do I have the same issue... the default should be right aligned for numbers.  I know this seems trivial, but it is really important to be able to generate a professional looking result.

**Comment by mbreuilly** [comment]
I have the same issue.
I have tried to right align both : 
- numerical values with the attribute `formatter=NumberFormatter(text_align='right')`
- strings with the attribute `formatter=StringFormatter(text_align='right')`
the values both numerics and strings remain left aligned. 

Here is my environment:

- Python: 3.4.3
- numpy==1.13.1
- pandas==0.19.1
- bokeh==0.12.9
- Ubuntu 14.04, Firefox 50.0.2

**Comment by tomanizer** [comment]
I have the same issue:
- python: 3.6.1
- bokeh==0.12.13

**Comment by mauropu** [comment]
It would be nice to be able to work on it.
Is there anything written, that does not waste your time, to understand the level of knowledge necessary to try to fix an error like this?
