### ISSUE TITLE
Widgets do not work in nested layouts

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#5722]
Versions: linux, chrome version 55.0.2883.87 and firefox 47.0, bokeh master, python 2.7.6. Also tested on Windows 8.1 with bokeh master, python 2.7.12.

In the following `bokeh serve` example, I can interact with the last button on the page but not the first (hovering above, clicking etc all do nothing). I'm clueless as to how this issue may be arising so the title of this issue might not exactly be accurate. It might have nothing at all to do with nested layouts but I haven't yet reproduced an example without nested layouts.

- If you unset `position: relative` from the `empty_div_element` css (e.g. with css classes `bk-widget bk-layout-fixed`, in your browser developer) all the buttons magically work again. This I have to admit utterly baffles me. Didn't find any mentions in issue tracker regarding `position: relative`. 
- If you change various properties regarding `nested_layout` below, for example changing the `layout` box to a `column`, then the buttons work.
- The `widgetbox`es in the below example don't affect the outcome, I just added it to be safe.

This example comes from bisecting a significantly more complicated layout, and I'm not exactly sure how easy it will be to get the more complicated layout to work without understanding why this example fails.

```python
from bokeh.layouts import column, layout, widgetbox
from bokeh.models.widgets import TextInput, Button, Div 
from bokeh.plotting import curdoc

nested_layout = layout([[
                         widgetbox([TextInput(),
                                    Button(label="nested"),
                                   ]) 
                       ]], responsive=True)
curdoc().add_root(
    column([
            nested_layout,
            widgetbox([Button(label="not nested"),
                       Div(text="empty_div_element"),
                      ])
           ], 
           responsive=True))
```

**Comment by bryevdv** [comment]
I'm going to go ahead and close this. I ran the above code with various sizing modes set, and the nested widgets we functional in all cases. Probably fixed during #8085
