### ISSUE TITLE
Unable to link download CSV button to datatable using CustomJS

### ISSUE THREAD

**Issue by ianlcassidy** [bokeh/bokeh#5723]
I am attempting to follow the [Export Data to CSV](https://demo.bokehplots.com/apps/export_csv) demo by linking a download `Button` to a `datatable`.  It is currently not working in Jupyter Notebook or in my Flask/Bokeh web app.  Here is my environment:
* Python 2.7.12 :: Anaconda 4.1.1 (64-bit)
* numpy==1.11.1
* pandas==0.18.1
* bokeh==0.12.4
* Windows 7, Chrome

And here is a code snippet:
```
import pandas as pd
import numpy as np
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.models.widgets import DataTable, NumberFormatter, TableColumn, Button
from bokeh.plotting import show
from bokeh.layouts import column

df = []
for ii in range(1, 11):
    df.append({'x': ii, 'y': 1000 * np.random.rand()})
df = pd.DataFrame(df)

source = ColumnDataSource(data=df)

columns = [
    TableColumn(field='x', title='Col 1'),
    TableColumn(field='y', title='Col 2',
                formatter=NumberFormatter(format='$0,0.00',
                                          text_align='right')),
]

dt = DataTable(source=source, columns=columns, width=500, height=200, row_headers=False)

callback = CustomJS(args=dict(source=source), code="""
            var data = source.get('data');
            var filetext = 'x,y\n';
            for (i=0; i < data['x'].length; i++) {
                var currRow = [data['x'][i].toString(),
                               data['y'][i].toString().concat('\n')];

                var joined = currRow.join();
                filetext = filetext.concat(joined);
            }

            var filename = 'data.csv';
            var blob = new Blob([filetext], { type: 'text/csv;charset=utf-8;' });

            //addresses IE
            if (navigator.msSaveBlob) {
                navigator.msSaveBlob(blob, filename);
            }

            else {
                var link = document.createElement("a");
                link = document.createElement('a')
                link.href = URL.createObjectURL(blob);
                link.download = filename
                link.target = "_blank";
                link.style.visibility = 'hidden';
                link.dispatchEvent(new MouseEvent('click'))
            }
        """)
button = Button(label='Download', button_type='success', callback=callback)

show(column(dt, button))
```

Here is the output I get in my Jupyter notebook:
![untitled](https://cloud.githubusercontent.com/assets/6929405/21941445/c702261c-d996-11e6-8a24-cb81c42c3d96.png)

But, when I click the download `Button` nothing happens.  Here is the error message that I get in my console:
```
Uncaught SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:11
    at r.CustomJS.r._make_func (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:11)
    at r.func (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:11)
    at r.CustomJS.r.execute (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:11)
    at e.i.AbstractButtonView.e.change_input (cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.4.min.js:1)
    at e.i.ButtonView.e.change_input (cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.4.min.js:1)
    at HTMLDivElement.dispatch (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:66)
    at HTMLDivElement.o.dispatch (cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.4.min.js:171)
    at HTMLDivElement.m.handle (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:65)
```

Here is the error message I get when I run my Flask/Bokeh app on localhost:
```
Uncaught TypeError: Cannot read property '0' of undefined
    at r.eval (eval at <anonymous> (bokeh-0.12.4.min.js:11), <anonymous>:8:42)
    at r.CustomJS.r.execute (bokeh-0.12.4.min.js:11)
    at e.i.AbstractButtonView.e.change_input (bokeh-widgets-0.12.4.min.js:1)
    at e.i.ButtonView.e.change_input (bokeh-widgets-0.12.4.min.js:1)
    at HTMLDivElement.dispatch (bokeh-0.12.4.min.js:66)
    at HTMLDivElement.o.dispatch (bokeh-widgets-0.12.4.min.js:171)
    at HTMLDivElement.m.handle (bokeh-0.12.4.min.js:65)
```

Not sure if this is a JS error or a Bokeh bug.

**Comment by ianlcassidy** [comment]
Nevermind, this was a silly mistake on my end...

**Comment by bryevdv** [comment]
> Nevermind, this was a silly mistake on my end... 

Happens to us all :) Can you describe what happened, in case it is also useful to someone else in the future?

**Comment by ianlcassidy** [comment]
Sure.

So, the `Uncaught SyntaxError: Invalid or unexpected token` error was something weird with the formatting of my inline `callback` script.  Once I placed the script in the separate file and read it in, things magically worked.

The `Uncaught TypeError: Cannot read property '0' of undefined` error was due to the fact that I was trying to reference data that didn't exist.  I was able to debug this using the console.

**Comment by covelloz** [comment]
Hey Ian,

I know this issue is closed and you figured out a work-around by using a separate file.
However, I figured out the exact cause of the error `Uncaught SyntaxError: Invalid or unexpected token`

It is because you were not escaping the \n character. 
Because "code" is a string in the python code, you need to escape the backlash: \\n

Thanks for writing up this code! It will be extremely helpful for me to have the ability to download the data to CSV.

`import pandas as pd
import numpy as np
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.models.widgets import DataTable, NumberFormatter, TableColumn, Button
from bokeh.plotting import show
from bokeh.layouts import column

df = []
for ii in range(1, 11):
	df.append({'x': ii, 'y': 1000 * np.random.rand()})
df = pd.DataFrame(df)

source = ColumnDataSource(data=df)

columns = [TableColumn(field='x', title='Col 1'),TableColumn(field='y', title='Col 2',formatter=NumberFormatter(format='$0,0.00',text_align='right'))]

dt = DataTable(source=source, columns=columns, width=500, height=200, row_headers=False)

callback = CustomJS(args=dict(source=source), code="""
	var data = source.data;
	var filetext = 'x,y\\n';
	
	for (i=0; i < data['x'].length; i++) {
		var currRow = [data['x'][i].toString(), data['y'][i].toString().concat('\\n')];
		var joined = currRow.join();
		filetext = filetext.concat(joined);
	}	
	
	var filename = 'data.csv';
	var blob = new Blob([filetext], { type: 'text/csv;charset=utf-8;' });
	
	//addresses IE
	if (navigator.msSaveBlob) {
		navigator.msSaveBlob(blob, filename);
	}

	else {
		var link = document.createElement("a");
		link = document.createElement('a')
		link.href = URL.createObjectURL(blob);
		link.download = filename
		link.target = "_blank";
		link.style.visibility = 'hidden';
		link.dispatchEvent(new MouseEvent('click'))
	}
""")

button = Button(label='Download', button_type='success', callback=callback)

show(column(dt, button))`

**Comment by ianlcassidy** [comment]
@covelloz Good to know.  I was able to get my code to work without the double backslash.  The main problem I was having before was incorrect/too many columns when converting my datatable to a CSV (i.e., the initial `var filetext` line to specific the column names.  I agree that the double backslash should also be in there.

**Comment by adarshr00711** [comment]
is there any way to download the data table as excel and not as csv because i tried this for another application in which the contents have "," in between the words which causes the sentences to be split into different tabs

**Comment by adarshr00711** [comment]
what should be the change in script so as to download it as excel as changing the extension from csv to .xlsx doesnt work

**Comment by bryevdv** [comment]
That would require the browser till be able to generate excel files, which as far as I know, is not possible at all.  You could possibly write a python callback on a bokeh server app, but you have to know then that the file is saved where the server is running, not where the user is viewing the app (unless by coincidence you are running the app locally)

**Comment by bryevdv** [comment]
Probably a much more viable solution would be to change the JS choose to generate rules with some other separator besides commas, or to wrap each individual item in quotes, so that Excel can parse the file.
