### ISSUE TITLE
[Feature Request] Allow FunctionHandler to Include Lifecycle Hooks and Themes

### ISSUE THREAD

**Issue by wanglouis49** [bokeh/bokeh#5728]
Please refer to the [thread on Google Groups](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/4Uc3kVak9nA).

**Comment by bryevdv** [comment]
This is probably already possible by adding a server lifecycle handler explicitly to the application, but could probably be made simpler.

**Comment by bryevdv** [comment]
There has not been any additional commentary supporting this, so I am going to go ahead and close for inactivity. As stated, it's possible to subclass lifecycle handler and add it to an application, which is the intended usage, if there is ever more call for it in the future, we can re-consider adding more convenience.
