### ISSUE TITLE
BokehJSONEncoder can't serialize numpy int64s in Bokeh 0.4.4

### ISSUE THREAD

**Issue by hashtonmartyn** [bokeh/bokeh#573]
Recently I updated from Bokeh 0.4.2p1 to 0.4.4 and found that I couldn't create Segments with my code anymore. There's a short discussion around the piece of code which looks to have changed and resulted in this error here: https://github.com/ContinuumIO/bokeh/commit/da21e5c27457a97f5a174d85af094c2be50d8d6f

I'm having a hard time extracting my code to reproduce this into a standalone snippet so I've written two short unit tests to show that there has been a change in functionality in BokehJSONEncoder/NumpyJSONEncoder. You can find a gist of this here https://gist.github.com/hashtonmartyn/11274525

In Bokeh 0.4.2p1 both if these unit tests pass but in 0.4.4 test_default_numpy_int64_returns_python_float raises this exception

Traceback (most recent call last):
  File "D:\Dropbox\Dropbox\NetBeansProjects\playground\test_BokehJSONEncoder.py", line 38, in test_default_numpy_int64_returns_python_float
    encoded_float = self.encoder.default(np_int64)
  File "C:\Python27\lib\site-packages\bokeh\protocol.py", line 70, in default
    return self.transform_python_types(obj)
  File "C:\Python27\lib\site-packages\bokeh\protocol.py", line 61, in transform_python_types
    return super(BokehJSONEncoder, self).default(obj)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 7 is not JSON serializable

I hope that's enough information to go on but if you want anything else I'm happy to help.

**Comment by damianavila** [comment]
@hashtonmartyn @philliproso can you check if this is still an issue in the latest release? Thanks!

**Comment by bryevdv** [comment]
As there have been no more reports on this in ~3 years, and as there is also now a different encoding for numpy arrays that might reasonably be expected to have solved this, I am going to close this for inactivity

**Comment by bryevdv** [comment]
If this can still be reproduced by recent versions of Bokeh, please re-open, or open a new issue
