### ISSUE TITLE
Tests broken again, this time due to `AttributeError`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5731]
Tests fail with:
```
______ ERROR collecting tests/integration/interaction/test_wheel_zoom.py _______
tests/integration/integration_tests_plugin.py:45: in pytest_generate_tests
    if metafunc.config.option.driver == "SauceLabs":
E   AttributeError: 'CmdOptions' object has no attribute 'driver'
```
All test runs are affected, because the error happens during test collecting by py.test.

**Comment by mattpap** [comment]
See e.g. https://travis-ci.org/bokeh/bokeh/jobs/191920177.

**Comment by mattpap** [comment]
This is most likely caused by software update. I think that for the purpose of testing we should pin all packages to specific versions, so that we don't end up with situations like this and we have reproducible environments for consecutive travis ci and local tests.

**Comment by bryevdv** [comment]
I think we should pin all the testing infrastructure packages. I don't think we should pin *everything*. If updating to the latest NumPy breaks things, that's actually a fact we would want to know.

**Comment by bryevdv** [comment]
At a glance, I actually can't find any difference between any `selenium` or `pytest-*` versions between passing and failing tests

**Comment by bryevdv** [comment]
Checked further, there are no package differences in the last conda install for "The following NEW packages will be INSTALLED" at all.

**Comment by bryevdv** [comment]
This is actually failing in our code, I am not sure what has changed since the package versions are identical:
```
def pytest_generate_tests(metafunc):
    # hasattr(metafunc.function, "foo") is like doing item.get_marker("foo")
    # This is ugly, but unfortunately there's not currently a better interface
    # https://github.com/pytest-dev/pytest/issues/1425
    if hasattr(metafunc.function, "cross_browser"):
        if metafunc.config.option.driver == "SauceLabs":
            cross_browser_list = [
                {
                    "browserName": "firefox",
                    "platform": "Linux",
                    "version": None
                },
                {
                    "browserName": "chrome",
                    "platform": "Linux",
                    "version": None
                },
            ]
            metafunc.fixturenames.append('test_browser')
            metafunc.parametrize('test_browser', cross_browser_list, ids=["firefox", "chrome"])

```

**Comment by bryevdv** [comment]
OK, this is one thing that has changed. As tests start:

OLD:
```
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.31, pluggy-0.4.0
sensitiveurl: .*
rootdir: /home/travis/build/bokeh/bokeh, inifile: setup.cfg
plugins: base-url-1.2.0, html-1.7, rerunfailures-1.0.1, selenium-1.6.0, variables-1.3, xdist-1.14, cov-2.3.1
```

NEW:

```
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.31, pluggy-0.4.0
rootdir: /home/travis/build/bokeh/bokeh, inifile: setup.cfg
plugins: html-1.7, rerunfailures-1.0.1, variables-1.3, xdist-1.14, cov-2.3.1
```

The "new" report is missing several plugins reported in the "old" report, even though they are installed. Where/what is this report generated by? pytest? ping @birdsarah

**Comment by bryevdv** [comment]
Notably, the `selenium` plugin does not appear to be being loaded, which probably explains the immediate problem.

**Comment by bryevdv** [comment]
OK, suspiciously, the packages that are not loading are ones that warn about pre-link scripts, and the version of conda *has* changed. I will try pinning conda to see if that fixes

**Comment by bryevdv** [comment]
Even with the pin, it's still doing this toward the end:
```
The following packages will be UPDATED:
    conda:           4.1.11-py27_0           --> 4.3.4-py27_0 
    conda-env:       2.5.2-py27_0            --> 2.6.0-0      
    requests:        2.9.1-py27_0            --> 2.12.4-py27_0
```
In the tests that worked previously, conda was updated to `4.2.15` at this stage

**Comment by bryevdv** [comment]
Interesting, the python 3 tests DID pass with the pin.

**Comment by bryevdv** [comment]
I think there are two issues:

* `conda install` with `--use-local` on python 2 is ignoring pinned packages. 

This is the same section on py3:

```
The following packages will be UPDATED:
    conda:    4.1.11-py34_0 --> 4.1.11-py34_1 conda-forge
    pyyaml:   3.11-py34_1   --> 3.12-py34_0              
    requests: 2.9.1-py34_0  --> 2.12.4-py34_0          
```
It does NOT update to conda `4.3.4`

also, when that happens the tests pass. So second issue:

* new version of conda warns about pre-link scripts but also broke them somehow.

ping @msarahan @kalefranz

**Comment by bryevdv** [comment]
adding `==4.2.15` to the `conda install --use-local` line fixes that section but then conda tries to update itself on the DEPS_TEST install for no reason.

**Comment by bryevdv** [comment]
Welp. Installing nodejs at the end forces a conda update too
```
+conda install --yes nodejs
Fetching package metadata ...........
Solving package specifications: ..........
Package plan for installation in environment /home/travis/miniconda:
The following packages will be UPDATED:
    conda: 4.2.15-py27_0 --> 4.3.4-py27_0
```

**Comment by bryevdv** [comment]
OK, last change seems to have tests running.

**Comment by bryevdv** [comment]
I had to put the conda version in meta.yaml section test/requires Can't put 4.2 in pinned because that conflicts with something else (conda-build I think) that needs 4.1

**Comment by bryevdv** [comment]
@mattpap I do want to pin everything in `DEPS_TEST` but I would like to make an effort to get the entire build up to current versions first. This means getting rid of no-arch packages on the bokeh channel, for one. Both for the test deps we host there, and for the bokeh packages themselves.

**Comment by bryevdv** [comment]
I'm going to get a local test env set up with docker. I will merge the current PR for this issue and make a new issue for more comprehensive build/test infrastructure overhaul
