### ISSUE TITLE
Server Embed Example Standalone doesn't print 

### ISSUE THREAD

**Issue by chanansh** [bokeh/bokeh#5737]
see example here: 
https://github.com/bokeh/bokeh/blob/0.12.4/examples/howto/server_embed/standalone_embed.py

Once `server.start()` is reached, the code doesn't returns and the print below doesn't work:

    print('Opening Bokeh application on http://localhost:5006/')

Moroever, I think the lines:

    io_loop.add_callback(server.show, "/")
    io_loop.start()

Are not reached.
Why does the example put some of the code under "__name__='__main__' and some outside of it?

**Comment by mattpap** [comment]
> Why does the example put some of the code under `name='main'` and some outside of it?

Usually this is done to make code importable, but without actually evaluating side-effecting code (writing to disk, starting servers, etc.). In this case all this code seems unnecessary. This seems to be a new example and I see more similar code in bulk commit 1c0433 that added it, so maybe this is a leftover.

**Comment by bryevdv** [comment]
When I run `python standalone_server.py` this example runs as expected, including printing the message and opening a browser:
<img width="1169" alt="screen shot 2017-01-15 at 8 52 26 am" src="https://cloud.githubusercontent.com/assets/1078448/21963426/1546ce80-db00-11e6-9def-3c2256fd3bf3.png">

Please provide more information about your system, how you installed, how you ran the example, confirm versions, etc.

**Comment by bryevdv** [comment]
> Usually this is done to make code importable, but without actually evaluating side-effecting code (writing to disk, starting servers, etc.). In this case all this code seems unnecessary.

It's just meant to be demonstrative here, many actual real world uses cases along these lines will need to have a main check.

**Comment by bryevdv** [comment]
@chanansh can you provide additional information?

**Comment by Avernial** [comment]
By default the `Server.start` method starts event loop and blocks further execution. Try to call `Server.start` method with argument `start_loop=False`.

```
server = Server(*args, **kwargs)
server.start(start_loop=False)
```

**Comment by bryevdv** [comment]
This is not the case:

https://github.com/bokeh/bokeh/blob/master/bokeh/server/server.py#L167-L176

The examples under consideration are new to Bokeh version `0.12.4`. Please upgrade to Bokeh `0.12.4` in order to run them. Also, please take care to make sure that you are always running versions of the examples that *match the version of Bokeh you have installed*.
