### ISSUE TITLE
Add native BokehJS support for TopoJSON

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#574]
https://github.com/mbostock/topojson/wiki

It would be nice to have a datasource that consumes/wraps TopoJSON, and modify certain glyph renderers (like `patches`, `multi_line` and `segment`) were made aware of its object model (https://github.com/topojson/topojson-specification/blob/master/README.md#2-topojson-objects).  We might even need to introduce a new renderer or two for it, which could also encode things like transforms (which, at the moment, would be outside the scope of our existing glyph renderers).

**Comment by kylepollina** [comment]
I would like this feature if possible in the future. Topojson in nice to work with
