### ISSUE TITLE
Can't set WidgetBox width

### ISSUE THREAD

**Issue by marcuskd** [bokeh/bokeh#5741]
Setting the width of a WidgetBox containing a TextInput doesn't work. Example code below (worked for v0.12.3 but not v0.12.4 - the WidgetBox still appears with the default width.

------------

from bokeh.models.widgets.inputs import TextInput
from bokeh.models.layouts import WidgetBox, Column
from bokeh.plotting import show

ti = TextInput(title = 'Enter text:')

c = Column(children = [WidgetBox(ti,width = 1000)])

show(c)

**Comment by axil** [comment]
Same behavior here. WidgetBox doesn't respect the width parameter anymore.

**Comment by bryevdv** [comment]
This seems to have been fixed at some point. Running the code on `master` with widths 100 and 1000 now yields:

<img width="473" alt="screen shot 2018-05-10 at 18 28 49" src="https://user-images.githubusercontent.com/1078448/39901918-1af227f8-5480-11e8-8aee-35c880eadb00.png">
<img width="838" alt="screen shot 2018-05-10 at 18 29 00" src="https://user-images.githubusercontent.com/1078448/39901919-1b0435c4-5480-11e8-8b65-1a65964acaac.png">
