### ISSUE TITLE
Use only one of global.isNaN and isStrictNaN

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5744]
Those have different corner case behavior and some of our code depends on the non-strict nature of `global.isNaN`. Unify this and have only one `isNaN().`

**Comment by mattpap** [comment]
@bryevdv, we have a lot of lines like this (especially in glyphs):
```
if isNaN(sx[i]+sy[i]+sinner_radius[i]+souter_radius[i]+_start_angle[i]+_angle[i])
 ```
This check doesn't consider infinities. Does it make sense to proceed with rendering with infinities? There is also a lot of lines like:
```
if isNaN(intermediate) or not isFinite(intermediate)
```
where we consider infinities. Would it make sense to use the same approach for both? There are also cases where we use `isFinite()` without `isNaN()`. Can those be treated the same?

**Comment by bryevdv** [comment]
I think there is some latitude to make things consistent in whatever way you think makes sense. Here is the behavior that needs to be maintained:

> If there are NaNs in a column, nothing should be plotted for the corresponding items, but all non-NaN items should otherwise plot normally. 

Regarding the `isFinite` it will have to be examined individually I think. There's no sensible way to plot `inf` but I think there are some properties like a "max interval" or something for some of the tickers, where `inf` is used to mean "unbounded"
