### ISSUE TITLE
SSL Certificate error

### ISSUE THREAD

**Issue by grechut** [bokeh/bokeh#5745]
HTTPS connection cannot be established when trying to open any of the Bokeh's examples (which require HTTPS via HSTS).

E.g. url: https://demo.bokehplots.com/apps/selection_histogram.

Probably the certificate has expired.

![image](https://cloud.githubusercontent.com/assets/1018985/22023357/20153ed8-dcc6-11e6-8d21-83e69d343df0.png)

**Comment by bryevdv** [comment]
This was supposed to have been handled... looking into it..

**Comment by bryevdv** [comment]
Should be resolved now

**Comment by grechut** [comment]
Yes, works :) 👍
