### ISSUE TITLE
charts.Scatter Inline tooltips from Pandas data source have double data views

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#5750]
Hopefully a picture is worth a thousand words:

<img width="930" alt="screenshot 2017-01-17 17 37 22" src="https://cloud.githubusercontent.com/assets/293525/22043267/df0a8954-dcdc-11e6-9553-7c449ddc6f0b.png">

Notice the tooltip.  It has an erroneous "bonus" tooltip under it with labels "index, data(x,y), canvas(x,y)".  If I pick a point more on the left of the plot (so the tooltip appears to the right of the data point) I instead get the values for this erroneous "bonus" tooltip.

This is caused by inlining the tooltip into the `bokeh.charts.Scatter()` call:

```
s = Scatter(data=autompg[autompg.make.isin('ford volkswagen honda'.split())],
            x='yr', y='mpg', color='make',
            height=400, width=800, title='Fuel efficiency of selected vehicles from 1970-1982',
            tools='hover, box_zoom, lasso_select, save, reset',
            tooltips = [
              ('Make','@make'),
              ('MPG', '@mpg'),
              ('hp',  '@hp')])
```

* Description of expected behavior and the observed behavior

There shouldn't be a second set of tooltips underneath the intended tool tip.

* Self-contained example code that generates the issue (if possible)

See above code

* Stack traceback and/or browser developer tools console output

See above image

* Software version information output by `bokeh info` command

```
Python version      :  3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
IPython version     :  5.1.0
Bokeh version       :  0.12.4
BokehJS static path :  /Users/ijstokes/anaconda/envs/dspyr/lib/python3.5/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
```

**Comment by bryevdv** [comment]
FYI `bokeh.charts` does not really have an active maintainer at the moment. I may step into that work but it will be several months before I can.

**Comment by Maggie-M** [comment]
moving to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/2)
