### ISSUE TITLE
Location in ColorBar offsets from axis

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5761]
See screenshot

This is a Label with `x=0, y=0 x_units='screen', y_units='screen'` and a ColorBar with `location=(0,0)`. Both added `above`. I would expect them to be in the same x position, but they are not.

Sorry I haven't put together minimal runnable example yet.

<img width="270" alt="screen shot 2017-01-18 at 6 02 57 pm" src="https://cloud.githubusercontent.com/assets/1796208/22088289/a4da63e0-dda8-11e6-901e-aca0d8e9fbfd.png">

**Comment by birdsarah** [comment]
confirmed with @canavandl that this is because the ColorBar translates for the frame offset - which is a good default in many instances.

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/color_bar.coffee#L148

but would be good to be configurable

**Comment by mattpap** [comment]
This was fixed in recent layout work (somewhere in 0.12.x).
