### ISSUE TITLE
does websocket-client version impact bokeh server deployment?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#5763]
![websocket](https://cloud.githubusercontent.com/assets/15861395/22107906/893cc800-de1e-11e6-903c-6a12db472f10.png)

In my cloud deployment requirement, I use 
![pip](https://cloud.githubusercontent.com/assets/15861395/22108107/8154ee32-de1f-11e6-9b8f-b2bfc99364d3.PNG)
without specifying version. 

Does websocket-client version impact bokeh server deployment? because previously working version is not working any more, The code can start the server, it is the import websocket does not work and giving me the attached error.

**Comment by bryevdv** [comment]
(FYI this would probably be better more appropriate on the mailing list)

Bokeh does not use or import the `websocket-client` package anywhere:
```
[bryan:~/work/bokeh/bokeh]$ grip websocket |grep import                                                                                   (master)
   14 : from tornado.websocket import websocket_connect, WebSocketError
   24 : from .utils import ManagedServerLoop, url, ws_url, http_get, websocket_open
    6 : from tornado.websocket import websocket_connect
   14 : from tornado.websocket import WebSocketHandler, WebSocketClosedError
   18 : from bokeh.server.tests.utils import ManagedServerLoop, url, ws_url, http_get, websocket_open
    9 : from bokeh.resources import _get_cdn_urls, websocket_url_for_server_url
```
 It used to use it for testing the old bokeh server, but that has been long removed. AFAIK tornado also does not depend on `websocket-client`, it has its own websocket code built in. Creating a new env with just tornado seems to confirm this:
```
$ conda create -n test tornado
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/bryan/anaconda/envs/test:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0
    pip:        9.0.1-py36_1
    python:     3.6.0-0
    readline:   6.2-2
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0
    tk:         8.5.18-0
    tornado:    4.4.2-py36_0
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1
    zlib:       1.2.8-3

Proceed ([y]/n)?
```

My guess is that something else in your app is using or pulling it in and does not like the new version.  It looks like the exception is being raised from code that is not part of Bokeh, but I can't really tell anything from the screenshot. For logs and error message, full text copied and pasted is always preferable to screenshots.

**Comment by bryevdv** [comment]
no updates, so closing. Re-iterating that Bokeh itself does not use or depend on `websocket-client` in any way.
