### ISSUE TITLE
Build/test optimizations

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5768]
With adding python 3.6, I propose consolidating all the unit tests to one job that:

* builds BokehJS (once)
* runs BokehJS unit tests (once)
* Then for each python version
  - creates conda env
  - `setup.py install --install-js` into env
  - runs unit tests using that python

This should run all the unit tests (even if earlier ones fail) and print a prominent summary at the very end of the job. This should result in a single ~10 minute job instead of four 6-8 minute jobs. 

Additionally:

* sample data is only needed (I believe) on examples tests and flake_docs, it should not be installed for other jobs. 
* combining conda installs will also save non-negligible time. E.g. do 
    
    ```
    conda install --yes $DEPS_BUILD $DEPS_RUN $DEPS_TEST
    ```

    using whatever minimal subset of deps is appropriate for the job. This will reduce the number of repodata downloads and dependency resolutions. 

* also propose renaming `flake_docs` to `packaging` or something. It tests all the things leading up to actually deploying Bokeh assets (e.g linting, docs and basic conda package building) and on tagged releases, also actually does the uploads

* on tagged releases, have all other jobs bail even earlier (they currently install miniconda, etc.) there is no need for this. 

* start using *new* no-arch packages once conda 4.3 install base is large enough

**Comment by mattpap** [comment]
> propose consolidating all the unit tests to one job that:

I would actually prefer to split them even more, because I like to see more fine-grained high-level status. However, this is unrealistic given travis ci simplistic view of jobs. One thing to note that when proceeding with consolidation, it will be harder to learn what actually failed, as one will have to scroll through a lot of logs.

**Comment by bryevdv** [comment]
> I would actually prefer to split them even more, because I like to see more fine-grained high-level status. However, this is unrealistic given travis ci simplistic view of jobs. One thing to note that when proceeding with consolidation, it will be harder to learn what actually failed, as one will have to scroll through a lot of logs.

Agree in principle. But to clarify my "combined job" would 

* only snow error output, not lots of normal successful output
* would summarize everything in one place at the end

which I think will help with that

**Comment by bryevdv** [comment]
There is another issue to implement stages. Closing this issue in favor of that one.
