### ISSUE TITLE
autoload_static uses Jquery .data() 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5778]
This function

https://api.jquery.com/jquery.data/

was used in `embed.coffee`:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/embed.coffee#L147

**Comment by mattpap** [comment]
No wonder it wasn't caught earlier, because it's not being used anywhere. There are just a few trivial unit tests that show that something like `data-bokeh-*` properties exist.

**Comment by bryevdv** [comment]
Fix for this should add at least a few tests
