### ISSUE TITLE
Investigate kdbush 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5783]
Possibly worth investigating, from the author of RBush:

> One recommendation I have is that if your list of points is static (you don't need to add/remove points after indexing), you should use kdbush, my other indexing library that performs point indexing 5-8x faster than RBush.

https://github.com/mourner/rbush/issues/63#issuecomment-268854922

**Comment by mattpap** [comment]
kdbush doesn't work with rectangles, only points, so this could be used for anything that uses `_xy_index` and other glyphs would have to fall back to rbush.

**Comment by bryevdv** [comment]
Investigation completete
