### ISSUE TITLE
Lossless compression of binary data

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#5792]
The addition of `base64` encoding of array data (particularly `float32` data) in PR ( https://github.com/bokeh/bokeh/pull/5544 ) has been a huge help already. This has had a big impact on reducing overall file sizes and making large data that much easier to work with in the browser.

That said, I find myself in a situation where I'm eager to do some compression too. In particular, I recently generated a summary data figure of some analysis and it was pushing ~30MB. Given the desire to share these figures as attachments in email, this is getting to an uncomfortable size. While I can certainly run compression on the file itself, the result is not an HTML file. So it immediately limits one on the devices that they can view the results with and requires the user have access to the right decompressor. Not to mention, in my past experience, performance begins to suffer with large HTML files on lower end computers.

When inspecting the file, I found ~95% was one giant `base64` blob. Given this data is not already compressed (just coming from a `float32` NumPy array) and does have some repetition, it seems like a good candidate for compression. However as this compression may need to be done in response to interaction (user selection), it needs to be fast. As such, it is ok to forego optimal compression for something that is quick with decent compression. Am curious to hear any thoughts and/or recommendations on this subject.

xref: https://github.com/bokeh/bokeh/issues/2204#issuecomment-103504754 (added in edit)

**Comment by jakirkham** [comment]
So, I did a bit of research in my own work. I'll summarize it here, but more details can be found in issue ( https://github.com/nanshe-org/nanshe_workflow/issues/24 ) and xrefs from there.

I limited myself to compression algorithms that had both Python and JavaScript implementations. Further I required pure JavaScript implementations that play well in the browser, which ends up being a pretty strict requirement, but provides a great deal of freedom down the road. This ends up implying easy access and algorithms that have been around awhile. Additionally, I required the implementations be maintained and show some recent activity.

Being a Python user primarily when it comes to working with data, it made sense to me that the compression happen on the Python side before creating a figure with Bokeh. This left decompression to happen in JavaScript. This asymmetry has a few interesting implications.

First, many JavaScript compression implementations provided the decompression library separate from the rest of the compression library, so this halves the size of the external requirement. Second, as the Python side is already doing a lot of heavy computation that takes much longer than preparing the plot, it doesn't tend to be as much of an issue for the compression to be a little slow. Third, as interaction is happening on the JavaScript side, it becomes paramount that decompression be fast. Fourth, type returned by JavaScript decompression libraries is pretty important for speed. In fact, as compression was being used exclusively on array data, anything that didn't take and return some sort of `TypedArray` was basically useless for this case. The reason being an extra conversion step would have to occur, which almost always included a copy, which ate up precious time.

To start, I picked 3 standard compression algorithms that fit these requirements: ZLIB, BZIP2, and LZMA. These are pretty standard compression methods and one can find a good variety of implementations to work with in both languages. Python 3 includes all of them in the standard library. Python 2 requires a backport for LZMA, but includes the rest in the standard library.

Before jumping into code, I played with compressing the data in Python to see how ZLIB, BZIP2, and LZMA did. What I found was ZLIB and BZIP2 did similarly (BZIP2 did only slightly better), but BZIP2 took a lot longer both for compression and decompression. While one could increase the compression level on BZIP2 to try to improve the compression ratio, it came at a cost of slower decompression speed. Comparatively LZMA's decompression speed improved as the compression level was bumped and had a somewhat better compression ratio than the other two. Given BZIP2's lackluster performance and the dearth of maintained JavaScript implementations, I skipped this one and stuck with LZMA and ZLIB for testing implementations.

In Python I used the stock standard library or a backport if it was needed. In JavaScript, I used [pako]( https://nodeca.github.io/pako ) for a ZLIB implementation and [LZMA-JS]( http://nmrugg.github.io/LZMA-JS ) for an LZMA implementation. I found that LZMA does a bit better than ZLIB when it came to compression ratio and it was a bit slower for decompression. This was with maxed out compression settings on LZMA. Changing the default ZLIB compression settings did not make a significant difference in compression ratio or size.

In the end, I went with ZLIB as it did a decent job and did not hurt interactivity. I may switch to LZMA in the future to improve compression ratio, but held off due to some concerns w.r.t. LZMA-JS and interactivity.

I don't know that Bokeh should include compression as a stock feature, but maybe it could be an extension library. One of the challenging points I ran into with Bokeh is I don't know know of a good way to decompress the data before the plot loads or to decompress data used by other objects (e.g. `Figure`s) before they display. In my case, I had an empty plot that I pushed data into based on a callback. To perform the compression, I found that myself doing it in this callback, which is a bit undesirable. Something that would make solving this problem easier would be to have an event for HTML (re)load that a callback could handle and do this decompression during. Alternatively, this might be possible through custom objects, but it feels a bit heavy handed.

**Comment by bryevdv** [comment]
Bokeh now supports an unencoded pure binary transfer of arrays. This has afforded a huge speedup over the base64 encoding, e.g. no possible to interactively scrub changes to ~1500x1500 images. If someone *really* needs compression on top of this, its now possible to do it themselves: send compressed data as a binary array, and decompress in BokehJS with a custom extension. There is also the possibility of using DataShader with Bokeh for very large images (c.f. recent demo of 4 8000x8000 images simultaneously being linked zoomed). 

with these options, I can't see a justification for adding this complexity directly to core bokeh, so closing this now.

**Comment by jukiewiczm** [comment]
@bryevdv 
Is the purely binary transfer of arrays possible to switch on/off? I'm creating standalone bokeh documents, not using the server. I can't really see it documented anywhere and it seems by data is encoded with base64 by default.

Adding some minimal example of custom compression to the documentation would really help as well.

**Comment by philippjfr** [comment]
Binary transfer is only used for transferring arrays via a websocket connection when using bokeh server or using push_notebook in Jupyter. The initial plot state has to be sent as a single JSON blob and therefore only supports base64 encoding.
