### ISSUE TITLE
bokeh calls logging.basicConfig()

### ISSUE THREAD

**Issue by pitrou** [bokeh/bokeh#5793]
When run as a library, bokeh calls logging.basicConfig() in `bokeh.document`. This changes configuration of the root logger (including its default level), even though the embedding application may not expect or want this. Instead, bokeh should just configure its own logger.

**Comment by bryevdv** [comment]
@pitrou can you submit a small PR?

**Comment by bryevdv** [comment]
@pitrou I should perhaps be more explicit. I've only ever used logging in basic ways, so I'm not sure what you are asking for, in detail. You will need to be much more explicit about the change you are suggesting, or (preferably) just submit a PR with the small change.
