### ISSUE TITLE
Cannot plot Histogram on Ubuntu 14.04

### ISSUE THREAD

**Issue by dopatraman** [bokeh/bokeh#5795]
I'm using Python 2.7 and Bokeh 0.12.4 on Ubuntu 14.04. I have a data frame like so:

```
         msrp  price
compact   1.0    1.0
sedan     2.0    3.0
suv       3.0    5.0
sport     4.0    7.0
```
made this way:
```
import pandas as pd
from bokeh.charts import Histogram, output_file, show

s = pd.Series([1,2,3,4], index=['compact', 'sedan', 'suv', 'sport'], dtype='float64')
s2 = pd.Series([1,3,5,7], index=['compact', 'sedan', 'suv', 'sport'], dtype='float64')
df = pd.DataFrame({'msrp': s, 'price': s2})

output_file('test.html')
p = Histogram(df['msrp'], title='Test')
show(p)
```

When I run this, I get the following error:
```
ValueError: expected an element of either Column(Float), Column(Int), Column(String), Column(Date), Column(Datetime) or Column(Bool), got 0    2
dtype: int64
```

This is puzzling because when I examine the `msrp` series, I get:

```
>>> df['msrp']
compact    1.0
sedan      2.0
suv        3.0
sport      4.0
Name: msrp, dtype: float64
```
Note that `dtype` reads as a Float. what am I doing wrong? I should note that all other chart types work properly.

**UPDATE**
The example on the docs dont work either:
```
from bokeh.sampledata.autompg import autompg as df
p = Histogram(df['hp'], title='Test')
```
Same error. Is this a known issue? If so, the docs should be updated...

**Comment by dopatraman** [comment]
bump

**Comment by bryevdv** [comment]
All of the code above is working for me. Can you confirm that you are running the version of bokeh that you think you are? i.e. what is the value of `bokeh.__version__` ?

**Comment by bryevdv** [comment]
Additionally, the email I clicked to respond to this issue just had the one word "bump". Please do not do this. It is not helpful. There are more than 700 issues, and only a few core devs, all of whom are human beings with the same finite number of hours in the day that you have. There is absolutely no way to guarantee that any particular issue can receive attention in any particular amount of time.

**Comment by dopatraman** [comment]
This seems to be a problem only on Ubuntu 14.04. It is working fine on OS El Capitan.

**Comment by dopatraman** [comment]
To answer your questions, `bokeh.__version__` evaluated to `0.12.4`. I have tried using versions 0.12.3 as well as 0.11.0, all have this issue on Ubuntu 14.04.

**Comment by dopatraman** [comment]
As for the mailing list comment, i understand this, which is why i deleted the comment. My apologies. If your resources are strained, I'd love to join the core team in debugging this. I just need some guidance on navigating the code base.

**Comment by bryevdv** [comment]
@dopatraman No worries, and certainly any help is appreciated. There are not any known or expected compatibility issues around this kind of thing. I will try to get a VM set up this weekend to see if I can reproduce the problem on Ubuntu 14.04 locally. If you want to poke around, the top level Histogram code is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/histogram_builder.py

but it makes use of quite a bit of lower level more general machinery in `bokeh.charts` (that I'm actually not especially familiar with yet)

**Comment by bryevdv** [comment]
Other useful information: What pandas and numpy versions? Does changing these versions help? How did you install bokeh?

**Comment by StevenCHowell** [comment]
@bryevdv,I can test this on my Ubuntu 14.04 machine tonight. I can also try the dev installation. No need for you to setup a VM (not yet anyway).

**Comment by bryevdv** [comment]
@StevenCHowell great thanks, look forward to hearing what you find

**Comment by StevenCHowell** [comment]
I just tried to reproduce this error but everything worked for me.  

Here is the information about my system (shows it is Ubuntu 14.04):
```
➜  thor: bokeh_5795/> uname -r
3.13.0-107-generic
➜  thor: bokeh_5795/> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

Here is the information about the new conda environment I setup for testing this:
```
➜  thor: scratch/> conda create -n py27 python=2.7 pandas numpy scipy 
➜  thor: scratch/> source activate py27
(py27) ➜  thor: scratch/> conda install ipython jupyter
(py27) ➜  thor: scratch/> conda install bokeh=0.12.4
```

Here are the package versions I have:
`bokeh.__version__`: `0.12.4`
`pandas.__version__`: `0.19.2`
`numpy.__version__`: `1.11.3`

@dopatraman are these the same version numbers you are using?  Did you try testing in a fresh conda environment?  This can make sure another packages has not corrupted your `lib/python/site-packages/` directory.  I doubt this would be your problem but is your ubuntu system up to date?  

I am not sure what else to recommend.  I use bokeh on Linux regularly (Ubuntu 14.04 and 16.04) without any compatibility issues.

**Comment by bryevdv** [comment]
I only have a Ubuntu `16.04 LTS` VM handy, but the code works fine on that as well. Regarding compat with linux I should add, all out automated CI testing, including image diff tests and selenium tests, happens on linux. One of the core devs is also pretty much exclusively a linux user. Given that, I think this is some kind of installation of configuration issue on your end. 

I still maintain that the most likely scenario is that when you run the script you are running a different python install with a different (older) version of Bokeh. The message you are seeing is exactly what an older version of Bokeh would complain about. Did you put the `print(bokeh.__version__)` in the same script when you run it? If not, can you do that? That will unequivocally inform whether the Bokeh version is really `0.12.4`. If it is, the my next guess is that somehow your install is corrupted and you have parts of an old version hanging around.

**Comment by cjguttormsson** [comment]
I am getting the same problem with a similar environment. I have Ubuntu 14.04, Python 3.4.3, and Bokeh 0.12.4. When I attempt to run step_chart.py from the 0.12.4 examples, located [here](http://bokeh.pydata.org/en/latest/docs/gallery/step_chart.html), I get the error:

    ValueError: expected an element of either String, Column(Float), Column(String), Column(Datetime) or Column(Bool), got 0      0

**Comment by StevenCHowell** [comment]
It is possible though not likely that something else in you site-packages directory is corrupting things.  Maybe you already did this but it would be good to verify.  Can you try creating a new virtual environment, installing bokeh fresh, then test it again? 

If you using [anaconda](https://www.continuum.io/downloads), to create a new environment you would run  the following:
```
$> conda create -n bokeh_test python=3.4 bokeh=0.12.4
$> source activate bokeh_test
```
If you try another python version (maybe 2.7, or 3.6), do you get the same behavior?

**Comment by bryevdv** [comment]
I definitely think this is some kind of installation corruption.

**Comment by StevenCHowell** [comment]
@caseyclements I have had experiences where code from a collaborator messed up my anaconda installation (I always use virtual environments now).  With this error being relatively uncommon, if it persists after trying another virtual environment, I recommend a fresh installation of anaconda.  You do not need to remove/replace your old one, put it in a different location and do not add it to you path.  After it is installed, navigate to the bin directory and run commands from that directory (notice the `./`'s):
```
$> ./conda create -n bokeh_test python=3.4 bokeh=0.12.4
$> source ./activate bokeh_test
```

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/51)
