### ISSUE TITLE
bokeh 0.12.4 needs Python 3.3 but this isn't documented anywhere

### ISSUE THREAD

**Issue by danio** [bokeh/bokeh#5796]
Bokeh `0.12.4` fails to plot from numpy data sources when using python 3.3. 

This is because PR #5544 introduced `base64.b64encode(array.data)` into bokeh/util/serialization.py, and `b64encode` is unable to handle `memoryview` (which is used by numpy). Python addressed this in http://bugs.python.org/issue17839 but that was only released in python 3.4. It's not an issue under python 2.7.

e.g. the following code
```
from bokeh.plotting import figure, show
import numpy as np
x = np.random.rand(5)
y = np.random.rand(5)
p = figure()
p.line(x, y)
show(p)
```
will cause the exception:
```
.../bokeh/bokeh/util/serialization.py in encode_base64_dict(array)
    271     '''
    272     return {
--> 273         '__ndarray__'  : base64.b64encode(array.data).decode('utf-8'),
    274         'shape'        : array.shape,
    275         'dtype'        : array.dtype.name
TypeError: expected bytes, not memoryview
```

I don't consider this to be an error with bokeh, but should be documented so that downstream distributions can use the correct version (e.g. [CentOS 6.8 SCL](http://mirror.centos.org/centos/6/sclo/x86_64/rh/) only supports python 3.3, but they have updated to use bokeh 0.12.4).

**Comment by mattpap** [comment]
Just to note, we don't test bokeh under Python 3.3 since late 2015 (bokeh 0.10).

**Comment by danio** [comment]
Related: PR #2743 removed support for 3.3
