### ISSUE TITLE
Do not rely on conda-forge for any packages on Travis

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5803]
Just waited an hour for a build to fail. 

MPL is pinned to `<2.0`
```
+PINNED_PKGS='notebook ==4.2.3
matplotlib <2.0'
```

Later in the actual release build conda-forge is added, and apparently it has `2.0rc2` available, which is also apparently `<2.0` ?? Technically true I guess
```
The following packages will be UPDATED:
    freetype:   2.5.5-2                       --> 2.6.3-1              conda-forge
    icu:        54.1-0                        --> 56.1-4               conda-forge
    matplotlib: 1.5.3-np111py34_1             --> 2.0.0rc2-np111py34_2 conda-forge
```

This causes the doc build to fail:
```
     PlotScript error:
     Traceback (most recent call last):
       File "/home/travis/miniconda/lib/python3.4/site-packages/bokeh-0.12.5.dev9-py3.4.egg/bokeh/application/handlers/code_runner.py", line 81, in run
         exec(self._code, module.__dict__)
       File "/home/travis/build/bokeh/bokeh/sphinx/source/docs/user_guide/examples/concepts_other_interfaces.py", line 12, in <module>
         scale="count", inner="stick")
       File "/home/travis/miniconda/lib/python3.4/site-packages/seaborn/categorical.py", line 2350, in violinplot
         ax = plt.gca()
       File "/home/travis/miniconda/lib/python3.4/site-packages/matplotlib/pyplot.py", line 949, in gca
         return gcf().gca(**kwargs)
       File "/home/travis/miniconda/lib/python3.4/site-packages/matplotlib/pyplot.py", line 586, in gcf
         return figure()
       File "/home/travis/miniconda/lib/python3.4/site-packages/matplotlib/pyplot.py", line 535, in figure
         **kwargs)
       File "/home/travis/miniconda/lib/python3.4/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
         return new_figure_manager_given_figure(num, thisFig)
       File "/home/travis/miniconda/lib/python3.4/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
         canvas = FigureCanvasQTAgg(figure)
       File "/home/travis/miniconda/lib/python3.4/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
         FigureCanvasQT.__init__(self, figure)
       File "/home/travis/miniconda/lib/python3.4/site-packages/matplotlib/backends/backend_qt4.py", line 63, in __init__
         _create_qApp()
       File "/home/travis/miniconda/lib/python3.4/site-packages/matplotlib/backends/backend_qt5.py", line 136, in _create_qApp
         raise RuntimeError('Invalid DISPLAY variable')
     RuntimeError: Invalid DISPLAY variable
     
```

--- 

We have no control over what goes on conda-forge, making the process fragile. The time cost of fixing and debugging release build failures is absolutely too high to bear. **All** conda pacakges should come from either:

* bokeh channel
* defaults channel

and **nowhere** else.

**Comment by bryevdv** [comment]
These are all the packages installed or upadated during a release build: 
```
The following NEW packages will be INSTALLED:
    cairo:      1.14.6-0          conda-forge
    ecdsa:      0.13-py34_0                  
    fabric3:    1.12.post1-py34_0 conda-forge
    harfbuzz:   1.0.6-1           conda-forge
    pango:      1.40.1-0          conda-forge
    paramiko:   1.17.2-py34_0     conda-forge
    pixman:     0.34.0-0          conda-forge
The following packages will be UPDATED:
    freetype:   2.5.5-2                       --> 2.6.3-1              conda-forge
    icu:        54.1-0                        --> 56.1-4               conda-forge
    matplotlib: 1.5.3-np111py34_1             --> 2.0.0rc2-np111py34_2 conda-forge
The following packages will be SUPERCEDED by a higher-priority channel:
    fontconfig: 2.12.1-2                      --> 2.11.1-6             conda-forge
    notebook:   4.2.3-py34_0                  --> 4.2.3-py34_0         conda-forge
    pillow:     4.0.0-py34_0                  --> 4.0.0-py34_0         conda-forge
    pyqt:       5.6.0-py34_2                  --> 4.11.4-py34_2        conda-forge
    qt:         5.6.2-3                       --> 4.8.7-3              conda-forge
    qtconsole:  4.2.1-py34_1                  --> 4.2.1-py34_1         conda-forge
```

**Comment by mattpap** [comment]
>  (...) it has 2.0rc2 available, which is also apparently <2.0 ?? Technically true I guess

It depends on how `<` is defined, but I can imagine such variation. So how to we specify that we want 1.x branch?

**Comment by mattpap** [comment]
> `RuntimeError: Invalid DISPLAY variable`

We already guard against this on Travis CI.

**Comment by mattpap** [comment]
This:
```
conda  install --dry-run -c conda-forge 'matplotlib=1*
```
pulls correct version. However, you can't add a lower bound and this:
```
conda  install --dry-run -c conda-forge 'matplotlib=1*,>=1.5.2
```
fails with invalid package specification.

**Comment by bryevdv** [comment]
> We already guard against this on Travis CI.

Not sure what this means, this was the error that failed the build.

Anyway, I fixed the MPL issue with a more specific pin. Then the `fabric3` install from CF broke things by updating unrelated pkgs from CF. Fixed that by adding `-c defaults` on command line to explicitly be a higher precedence. Things are working for now, and I was able to procduce a dev build. 

Got instructions on how to copy between channels:
```
$ anaconda copy conda-forge/fabric3/1.12.post1 --to-owner bokeh
```
which will make it much easier to migrate anything we need off of the CF channel.

**Comment by mattpap** [comment]
> Not sure what this means, this was the error that failed the build.

We used configure `DISPLAY`, so that matplotlib wouldn't fail. I looked for this and apparently this code was removed at some point.

**Comment by mattpap** [comment]
> Anyway, I fixed the MPL issue with a more specific pin

Yeah, but do you actually know if what I tried to investigate in my earlier comment is possible in conda? I mean specifying `1.x` branch and lower bound?

**Comment by bryevdv** [comment]
> Yeah, but do you actually know if what I tried to investigate in my earlier comment is possible in conda? I mean specifying 1.x branch and lower bound?

I don't but according to the conda folks the current behavior is a bug (the rc should not have matched < 2.0)

**Comment by bryevdv** [comment]
currently just used for `fabric3` I believe

**Comment by bryevdv** [comment]
In addition to `fabric3` it looks like we also use the old version of selenium:
``
    selenium:                 2.53.5-py27_0      conda-forge
```

@mattpap this is for image diff tests? We should re-work those to use our new `export` capability, in order to get rid of this old dependency and also to dogfood the export continuously.

**Comment by mattpap** [comment]
@bryevdv, this is for integration tests. There are some very py.test fragile plugins used there. Image diff tests don't use selenium.

**Comment by bryevdv** [comment]
@mattpap right, of course (I need a vacation)

I will look at building `fabric3` on the bokeh channel. @canavandl do you have any notion offhand of how difficult it would be to update pytest to use a version of selenium available on `defatuls` or bokeh channel?

**Comment by canavandl** [comment]
> @bryevdv, this is for integration tests. There are some very py.test fragile plugins used there. Image diff tests don't use selenium.

I think the image diff tests do use selenium (at least the screenshot ones do).

We use selenium=2.53.5 because it's compatible with the ancient FireFox 45 version that's available on SauceLabs that we use to run our integration tests. I don't know why, but SauceLabs seems uninterested in updating their Linux browsers. I'd classify changing this as difficult.

**Comment by bryevdv** [comment]
Right the saucelabs screenshot tests use it, but not the examples tests that run on TravisCI. Maybe we can upload this package to a `bokeh` channel then, I'll look at that as well at some point.

**Comment by canavandl** [comment]
> Right the saucelabs screenshot tests use it, but not the examples tests that run on TravisCI
correct.

I believe that is correct.

**Comment by mattpap** [comment]
Just to define the vocabulary (at least what I use), "image diff" are examples' tests (no selenium). "sauce labs" are integration tests (use selenium). Both generate image diffs in the end, but by different means.
