### ISSUE TITLE
Many patch glyphs is *really* slow

### ISSUE THREAD

**Issue by econoraptor** [bokeh/bokeh#5804]
I've been trying to implement overlapping shapes using `patches` where I can control the order in which each shape is drawn.  After seeing this issue https://github.com/bokeh/bokeh/issues/3601 I decided to try looping over the shapes and using `patch` for each one.  For 460 mostly rectangular shapes it took ~30 seconds for all the `patch` glyphs to be applied.  

I had this problem with 0.12.3 so I upgraded to 0.12.4 and gave it a try, but there was no improvement.  It might have gotten a little slower, but I'm not certain since the timing is very sensitive to small changes with this many glyphs.

Although this reproduction has a lot of overlap, my original shapes do not.

Here's a reproduction:

```
from random import randint
import time

from bokeh.layouts import column
from bokeh.plotting import figure, curdoc


plot = figure(x_range=(0, 100), y_range=(0,100))

coords = []
for i in range(300):
    x = []
    y = []
    for j in range(3):
        x.append(randint(0, 100))
        y.append(randint(0, 100))

    coords.append([x, y])

start_time = time.time()
prev_time = start_time
for c in coords:
    plot.patch(x=c[0], y=c[1])
    now_time = time.time()
    print(now_time - prev_time)
    prev_time = now_time

print(prev_time - start_time)

curdoc().add_root(column(plot))
```

**Comment by bryevdv** [comment]
The improvements in `0.12.4` only apply to (some) numpy arrays. I would not expect any improvements with using plain python lists.

**Comment by bryevdv** [comment]
Additionally, you are creating a separate `patch` for every glyph. This was unclear. It would be much more efficient to "vectorize" things with the `patches` glyph method instead.

**Comment by bryevdv** [comment]
As a concrete example, this code renders 1500 patches (using `patches`) in under one second
```
import numpy as np
import time

from bokeh.plotting import figure, curdoc

xs, ys = [], []

for i in range(1500):
    xs.append(np.random.random(3)*100)
    ys.append(np.random.random(3)*100)

start_time = time.time()
plot = figure(x_range=(0, 100), y_range=(0,100))
plot.patches(xs=xs, ys=ys)
print(time.time() - start_time)

curdoc().add_root(plot)
```

**Comment by econoraptor** [comment]
The problem I was trying to solve was to control the draw order for each shape.  As https://github.com/bokeh/bokeh/issues/3601 details, `patches` does not give this control.  The suggestion you make in that issue is to use multiple `patch` or `patches` glyphs.  I have since reduced the number of glyphs to a sufficiently performant number by assigning each shape to a `patches` glyph based on how many overlaps above it there are.

**Comment by bryevdv** [comment]
I see. Unfortunately using a separate patch for every different patch slices things in a way that is going to be less performant. Basically, it creates a separate data source for ever patch, and adds alot of overhead. The `patches` glyph was created to solve that problem, but of course it has other trade-offs, in order to optimized for performance. If you have a case that is not served by either of these two, it might be possible to create a custom glyph extension that optimizes for your specific needs:

http://bokeh.pydata.org/en/dev/docs/user_guide/extensions.html
