### ISSUE TITLE
Line not displayed for "flat" TimeSeries

### ISSUE THREAD

**Issue by loujine** [bokeh/bokeh#5807]
When I try to display a "flat" TimeSeries (i.e. all values y equal) I encountered the following bugs:
- the line is not displayed (except, apparently, if y=[1,1,1...])
- the y axis on the left side shows one tick with the value None instead of the numerical value

Tested in a clean virtualenv with bokeh 0.11.1 and 0.12.4

Minimal example showing cases with y=0,0,0 (no line, None) / y=1,1,1 (line displayed, None) / y=1,2,1 (normal behavior)

```python
from bokeh.charts import TimeSeries, show, output_file, vplot
from datetime import datetime as dt

tsline = TimeSeries(
    {'x': [dt(2017,1,1), dt(2017,1,2), dt(2017,1,3)],
     'y': [0.,0.,0.] },
    x='x', y='y',
)
tsline2 = TimeSeries(
    {'x': [dt(2017,1,1), dt(2017,1,2), dt(2017,1,3)],
     'y': [1.,1.,1.] },
    x='x', y='y',
)
tsline3 = TimeSeries(
    {'x': [dt(2017,1,1), dt(2017,1,2), dt(2017,1,3)],
     'y': [1.,2.,1.] },
    x='x', y='y',
)
output_file("ts.html")

show(vplot(tsline, tsline2, tsline3))
```

System information:
debian sid, example tested with firefox/chromium

$ bokeh info
Python version      :  2.7.13 (default, Dec 18 2016, 20:19:42) 
IPython version     :  5.1.0
Bokeh version       :  0.12.4
BokehJS static path :  ~/.virtualenvs/bokeh/local/lib/python2.7/site-packages/bokeh/server/static
node.js version     :  v6.9.4
npm version         :  3.10.10

**Comment by bryevdv** [comment]
I agree this is a bug. However, there is currently no maintainer for `bokeh.charts` There will be no-one that can look at this in the immediate future. My recommendation for now is to use the `bokeh.plotting` API, which can also plot time series data without a problem: 

http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#datetime-axes

**Comment by loujine** [comment]
But the plotting API doesn't have the builder_type='step' option, right?

**Comment by Maggie-M** [comment]
moving to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/1)
