### ISSUE TITLE
Overlapped rects' borders are drawn on top of other rects

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#5809]
Bokeh version: 0.12.4

```python
import bokeh.plotting as bp

f = bp.figure(width=500, height=500)
f.rect([-1, 0, 0, 1], [0, -1, 1, 0], width=1.5, height=1.5,
       color=['red', 'green', 'blue', 'yellow'])
```

![bokeh_plot 1](https://cloud.githubusercontent.com/assets/4410314/22378980/ff03bfa4-e4e9-11e6-9bec-b49ca180dfee.png)

I guess one would expect that the lines have the same z-order as the area inside rects.

**Comment by bryevdv** [comment]
All the fills are done, then all the border lines are stroked. To do otherwise would probably, unfortunately have drastic performance implications for plots with many rectangles. But some investigation is needed.

**Comment by bryevdv** [comment]
I think the best option I can suggest is to set `line_color=None` which will hopefully suffice in many/most cases

<img width="535" alt="screen shot 2017-10-10 at 19 07 33" src="https://user-images.githubusercontent.com/1078448/31416379-4ccb22c2-adee-11e7-9d5b-246d1545303f.png">
