### ISSUE TITLE
Don't rely on TypedArray.map

### ISSUE THREAD

**Issue by pstoeckl** [bokeh/bokeh#5810]
As of Bokeh 0.12.4, when plotting typed data (e.g. typed NumPy arrays) on a plot with logarithmic axis scaling, an error occurs and the plot fails to display on some older browsers.

Minimal example: following plot fails to display on Chrome v44; set `y_axis_type` to `'linear'` and it displays without issue.

```
import numpy

from bokeh.plotting import figure, curdoc

x = numpy.arange(0,10,0.1,dtype='float64')
y = numpy.arange(2,12,0.1,dtype='float64')

fig = figure(y_axis_type='log')
fig.line(x,y)
                
curdoc().add_root(fig)
```

Approximate browser stacktrace (from minified source) is
```
Uncaught TypeError: t.map is not a function
  window.Bokeh.Bokeh.models/mappers/log_mapper.r.LogMapper.e.v_map_to_target
  window.Bokeh.Bokeh.models/canvas/cartesian_frame.r.CartesianFrame.e.map_to_screen
  window.Bokeh.Bokeh.models/plots/plot_canvas.r.PlotCanvasView.e.map_to_screen
  window.Bokeh.Bokeh.models/glyphs/glyph.r.GlyphView.e.map_to_screen
  window.Bokeh.Bokeh.models/glyphs/glyph.r.GlyphView.e.map_data
  window.Bokeh.Bokeh.models/renderers/glyph_renderer.r.GlyphRendererView.e.render
  window.Bokeh.Bokeh.models/plots/plot_canvas.r.PlotCanvasView.e._render_levels
  window.Bokeh.Bokeh.models/plots/plot_canvas.r.PlotCanvasView.e.render
  window.Bokeh.Bokeh.core/util/throttle.r.throttle.i
```
where `t` in question is a `Float64Array`. Probable candidate is thus lack of support for `%TypedArray%.map()` on Chrome <=44; Safari, IE, Opera and Firefox <38 may thus be similarly affected. 

Can also verify that this issue did not come up under Bokeh 0.12.1 on Chrome, and that Firefox 39 has no issues with log scaling under Bokeh 0.12.4.

Related: Issue #5056

**Comment by bryevdv** [comment]
Put this in `0.12.6` but if we have time it might be better sooner in `0.12.5`
