### ISSUE TITLE
LinearColorMapper does not return usable string/dictionary

### ISSUE THREAD

**Issue by MatthewBurke1995** [bokeh/bokeh#5812]
I was looking through the <a href="http://bokeh.pydata.org/en/latest/docs/gallery/unemployment.html"> unemployment.py </a> Bokeh example in the Bokeh gallery and was trying to get it to work for my own use but the fill_color attribute wasn't accepting the LinearColorMapper as an input. 

The particular code in question is:

```
mapper = LinearColorMapper(palette=colors)
...
p.rect(x="year", y="month", width=1, height=1,
       source=source,
       fill_color={'field': 'rate', 'transform': mapper},
       line_color=None)
```
and the error is:
```
ValueError: expected an element of either String, Dict(String, Either(String, Color)) or Color, got {'field': 'rate', 'transform': <bokeh.models.mappers.LinearColorMapper object at 0x000001B0A82957B8>}
```
I have the latest version of Bokeh and I tried it in several IDE's but the error is consistently there.

**Comment by bryevdv** [comment]
The ability to add a transform like that is s fairly recent addition. The error message indicates that you are using a version of Bokeh that is older than the introduction of this feature. You will need to update your installed version of Bokeh for this code to function. 

The link to the example you have above is to the `latest` docs. If you are not running the latest version of Bokeh, please take care to make sure you are looking at docs and examples appropriate to the version you actually have installed

**Comment by bryevdv** [comment]
I do note you say that you have the latest version installed, but it is 100% the case that whatever python you are running is not seeing the latest version. Perhaps you have multiple environments, and Bokeh is updated in a different one than the python, or you have some other installation problem.
