### ISSUE TITLE
Conda convert windows packages cause an error

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5818]
Reference: #5814 

According to @kalefranz

> For a workaround, either remove the info/paths.json file in the package tarball itself (if you have access to it on anaconda.org), or remove it locally after it's been unpacked to

**Comment by mattpap** [comment]
windows?

**Comment by bryevdv** [comment]
Yes, also there is an open PR to conda to fix this, so hopefully we can just wait for that an upgrade to solve this.

**Comment by bryevdv** [comment]
updating to just released `conda-build` version `2.1.3` should resolve this.

**Comment by bryevdv** [comment]
There is still a conda-build bug that needs to be fixed, will bump again when it is ready.

**Comment by bryevdv** [comment]
When #5870 is merged I will start a dev build and we can see if the new conda-build fixes the windows issues (it should)

**Comment by bryevdv** [comment]
`0.12.5dev12` is available and should be working on windows please re-open if there is any continued problem
