### ISSUE TITLE
Why I can't use OperURL in widget callback (e.g. button callback)?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#5819]
See the following code, clicking the button does not open 'http://www.cnn.com/'

from bokeh.models.widgets import Button
from bokeh.io import output_file, show, vform
from bokeh.models import OpenURL, TapTool

output_file("button.html")
button = Button(label="Foo", callback=OpenURL(url='http://www.cnn.com/'), type="success")
show(vform(button))

**Comment by bryevdv** [comment]
`OpenURL` is specifically designed and only useful for opening URLs in response to *selection* events. It is not a general purpose thing. Perhaps we need to make that more clear in the documentation. For something like this you can just use a `CustomJS` callback with a single line of JS (e.g. `window.open("some.url.com");`)
