### ISSUE TITLE
Using line_color=None with adjacent glyphs leaves white-ish lines

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#5820]
Bokeh version: 0.12.4

```python
import bokeh.plotting as bp

f = bp.figure(width=500, height=500)
f.patches([[1, 2, 1, 0], [2, 3, 2, 1]], [[0, 1, 2, 1], [-1, 0, 1, 0]],
          fill_color='blue', line_color=None)
```
![bokeh_plot 2](https://cloud.githubusercontent.com/assets/4410314/22415672/d9d36928-e6fb-11e6-9b79-14de7dc362c5.png)

It's not always there - I guess it strongly depends on chosen colors.
An example of a more complex plot:
![image](https://cloud.githubusercontent.com/assets/4410314/22415625/7b473ce0-e6fb-11e6-85f7-0792f4fa8c79.png)
And a very similar plot, only drawn with one of R packages:
![image](https://cloud.githubusercontent.com/assets/4410314/22415632/8b7d342a-e6fb-11e6-987f-054e301f0333.png)
As you can see, there are no white lines in the image from R. I guess it really boils down to different antialiasing methods, but I don't know for sure.

**Comment by afonit** [comment]
Interestingly when one zooms in all the way, you do see jagged edges that give a perforated look to sides of the squares that are joined to each other:

![image](https://cloud.githubusercontent.com/assets/1798497/22523630/128d269e-e88e-11e6-9ac0-b832618d9758.png)

**Comment by bryevdv** [comment]
Possibly an artifact of the `line_join` property, could try changing it and see how ir if it looks different.

**Comment by afonit** [comment]
Bryan,
I had tried that and some of the other options, though I admit to not trying every permutation/combination.
[http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#line-properties](url)

**Comment by afonit** [comment]
I don't see any permutations that smooth out the drawing of the patches.
I did this in the notebooks so I could quickly scroll through the output and see if any smoothed out.

```python
import bokeh.plotting as bp
import time

bp.output_notebook()

line_dash_options = ['solid', 'dashed', 'dotted', 'dotdash', 'dashdot']
line_join_options = ['miter', 'round', 'bevel']

for l_dash in line_dash_options:
    for l_join in line_join_options:
        f = bp.figure(width=500, height=500, y_range=(0.9999998,1.0000002), x_range=(0.0000000,0.0000003), title=l_option+' '+
                     l_join)
        f.patches([[1, 2, 1, 0], [2, 3, 2, 1]], [[0, 1, 2, 1], [-1, 0, 1, 0]],
                  fill_color='black', line_color=None, line_dash=l_dash, line_join=l_join)
        bp.show(f)
```

**Comment by bryevdv** [comment]
I'm not sure offhand, we don't normally change smoothing settings, except to turn them off and restore the previous setting for images, e.g.
```
    old_smoothing = ctx.getImageSmoothingEnabled()
    ctx.setImageSmoothingEnabled(false)

    # render stuff

    ctx.setImageSmoothingEnabled(old_smoothing)
```
Another option to try: set the line color to the same as the fill color and leave a width 1 outline. It's possible (idk offhand) that aliasing for line stroking is different for filled regions, and that a line of some sort is needed for better behavior in certain situations.

**Comment by bryevdv** [comment]
If this kind of adjacent filled figure is needed I think the only answer is simply to also supply the line color:
```

from bokeh.plotting import output_file, show

import bokeh.plotting as bp

f = bp.figure(width=500, height=500)
f.patches([[1, 2, 1, 0], [2, 3, 2, 1]], [[0, 1, 2, 1], [-1, 0, 1, 0]],
          fill_color='blue', line_color='blue')

output_file("test.html")
show(f)
```
Produces no line in between:
<img width="573" alt="screen shot 2017-10-13 at 10 43 34" src="https://user-images.githubusercontent.com/1078448/31554498-62652b02-b003-11e7-8a02-babf53e8d9a2.png">
As far as I can tell this is simply the operation of the HTML canvas that we must live with. The line that is stroked around a filled area is not completely disjoint form the interior area, so if you want things to abut as closely as possible the stroke step is needed as well.
