### ISSUE TITLE
restore pip installable dev builds

### ISSUE THREAD

**Issue by ahamiltonian** [bokeh/bokeh#5827]
The pip installation of the dev builds does not work.  Following the instructions on the dev guide http://bokeh.pydata.org/en/dev/docs/dev_guide/setup.html#devguide-setup only installs the most recent stable release, not the dev.

Thanks,
Andrew

**Comment by bryevdv** [comment]
Per FD conversation, use command
```
anaconda -t <token> upload -u bokeh <conda or sdist file> -l dev --force --no-progress
```

**Comment by bryevdv** [comment]
Confirmed dev build instructions successfully install `0.12.5rc3` via pip
