### ISSUE TITLE
augment MPL api to allow for linked brushing

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#583]
the current bokeh API lets you do linked brushing (And other linked things) if you create an explcit datasource and pass in column names rather than arrays.  It would be nice if we could also do this with the MPL API - check if a source kwarg is passed in and if so, use the data source obj instead of making a new one

**Comment by damianavila** [comment]
In fact, the behaviour is the linked panning (the datasource object is shared)... probably we need to support NOT linked panning and probably add brushing too...

**Comment by bryevdv** [comment]
I don't think we are going to spend any additional effort on MPL compat until (if) MEP 25 happens.
