### ISSUE TITLE
Need to use different sintaxis when using command "bokeh serve" in Windows command line.

### ISSUE THREAD

**Issue by fraserpal** [bokeh/bokeh#5834]
This issue was originally commented and resolved [here](http://stackoverflow.com/questions/41936031/bokeh-server-not-working-when-deployed-from-windows-server/41980870#41980870). One of the possible arguments to use is `--host='*'` to allow any host. The use of this argument appears somewhere in the documentation I do not find right now, anyway in Linux it works properly. But when used in Windows Command Prompt, not any host is allowed to connect as it is supposed to be. After making some tests with the sintaxis in Windows, the conclussion is that correct way to use arguments is `--host '*'` or `--host=*`. 
Using `--host='*'` is literally interpreted in Windows, hence no wildcard is applied. This issue is probaly obvious for advanced users, but for beginners as me may be not so clear. Thanks to @bryevdv for the help.

![bokeh2 1](https://cloud.githubusercontent.com/assets/20949300/22511196/27ec39ba-e895-11e6-9bb7-acc544614119.JPG)
![bokeh4](https://cloud.githubusercontent.com/assets/20949300/22511197/2800feae-e895-11e6-86f6-0e64fdb2b3e2.JPG)

**Comment by bryevdv** [comment]
@bokeh/dev I have labeled this as a documentation task, I think that's the minimum that is necessary. If there are better ways to handle things on Windows, that would be good to know and perhaps try as well. 

@fraserpal I don't think it is obvious at all, so thanks for raising the issue so we can make it clearer for everyone

**Comment by bryevdv** [comment]
I've resolved this by not demonstrating the `-foo=bar` syntax at all anywhere anymore. If there are still more questions in the future we can add more explicit notes/warnings then.
