### ISSUE TITLE
Properties' docstrings

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#584]
Currently we have:
```python
In [1]: from bokeh.objects import *

In [2]: p = Plot()

In [3]: p.x_range?
Type:        NoneType
String form: None
Docstring:   <no docstring>

In [4]: Plot.x_range?
Type:        NoneType
String form: None
Docstring:   <no docstring>
```
`_3` is expected behavior, because we access property's value (`x_range`'s default value is `None`). However, `Plot.x_range` also gives access to the value, instead of to the property itself. Currently the only way, I know of, to get access to a property of an object, is to use `lookup_descriptor()` (`bokeh.properties`). If we allowed to access properties through a class, then, with some improvements to properties, we could have a docstring per property.

**Comment by bryevdv** [comment]
Well, we have per-property docstrings now, but `help` and `?` evidently look at the objects class:
```
In [11]: Plot.x_range?
Type:            Instance
String form:     Instance(Range)
File:            /Users/bryan/work/bokeh/bokeh/properties.py
Docstring:       The (default) data range of the horizontal dimension of the plot.
Class docstring:
Instance type property for referneces to other Models in the object
graph.

In [12]: Plot.x_range.__doc__
Out[12]: '\n    The (default) data range of the horizontal dimension of the plot.\n    '

In [13]: Plot.x_range.__class__.__doc__
Out[13]: ' Instance type property for referneces to other Models in the object\n    graph.\n\n    '
```
Not sure there is much to do about this, or how much I care.

**Comment by bryevdv** [comment]
Anyway I am content with `Plot.x_range?` working tho, so closing. If there is more to add tho, @mattpap or @pzwang please re-open.
