### ISSUE TITLE
to_bokeh doesn't show bars on seaborn.barplot

### ISSUE THREAD

**Issue by ArtyomKaltovich** [bokeh/bokeh#5840]
As I understand, bokeh don't have methods for bars with error, so I decided to use seaborn, I have follow code:
sns.set_style("whitegrid")
plot = sns.barplot(data=[[1,2], [3,4]])
plot.get_figure().savefig('1.jpg')

l = layout([[widgetbox(*controls), to_bokeh(plot.get_figure())]])
save(l)
It save normal plot, like that, but bokeh shows only error line, and no bars.
http://seaborn.pydata.org/_images/seaborn-barplot-2.png

**Comment by bryevdv** [comment]
Hi @ArtyomKaltovich Bokeh relies on mplexporter an upstream library, for MPL support. mplexporter is not complete (and is also currently unmaintained), and we have tried to make it clear in the docs that current MPL support is thus also not complete, and is merely offered as-is, for cases when it happens to be useful.

Comprehensive and robust support for MPL compatibility will ultimately depend on MEP 25 coming to pass (https://github.com/matplotlib/matplotlib/wiki/MEP25) But that work is being developed by the MPL team and the schedule is not under our control.
