### ISSUE TITLE
image_url clipping image within plot bounds

### ISSUE THREAD

**Issue by clairetang6** [bokeh/bokeh#5841]
Different parts of the image are clipped depending on where the toolbar is.

![image](https://cloud.githubusercontent.com/assets/4241244/22575198/ed3d7ef8-e968-11e6-8cbb-cfd3e2870a8f.png)

![image](https://cloud.githubusercontent.com/assets/4241244/22575185/e175d2f0-e968-11e6-855d-051a4193d095.png)

```python
from bokeh.plotting import show, figure, output_file
from bokeh.layouts import row, column

output_file("image_url_test.html")

figure_kws = {'x_range': (0, 100), 'y_range': (100, 0), 'plot_height': 300, 'plot_width': 300}

fig1 = figure(**figure_kws)
fig1.image_url(url=['http://bokeh.pydata.org/en/latest/_images/image_t.png'], x=[0], y=[0], w=[100], h=[100])

fig2 = figure(toolbar_location="above", **figure_kws)
fig2.image_url(url=['http://bokeh.pydata.org/en/latest/_images/image_t.png'], x=[0], y=[0], w=[100], h=[100])

fig3 = figure(toolbar_location="left", toolbar_sticky=False, **figure_kws)
fig3.image_url(url=['http://bokeh.pydata.org/en/latest/_images/image_t.png'], x=[0], y=[0], w=[100], h=[100])

fig4 = figure(toolbar_location="below", toolbar_sticky=False, **figure_kws)
fig4.image_url(url=['http://bokeh.pydata.org/en/latest/_images/image_t.png'], x=[0], y=[0], w=[100], h=[100])

show(column(fig1, fig2, fig3, fig4))
```

Commenting out `ctx.clip()` at [L61](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/image_url.coffee#L61) in image_url.coffee fixes this, so it looks like something is wrong with the frame's left, bottom, width, height properties. 

![image](https://cloud.githubusercontent.com/assets/4241244/22575362/fccf4756-e969-11e6-81ea-c1c1cfede2ff.png)

**Comment by Imperssonator** [comment]
Experiencing same issue with toolbar on side, curiously other glyphs do not get clipped - will try clairetang's suggestion and report back:

<img width="835" alt="screen shot 2017-05-09 at 12 43 02 pm" src="https://cloud.githubusercontent.com/assets/7574900/25862197/3d9601d0-34b5-11e7-96e8-aa124cf3f922.png">

`plot_width=800
plot_height=600
x_col='Sfull'
y_col='CorrLen'
x_label='S_Full'
y_label='Decay Length (nm)'
p=figure(responsive=False,
         x_axis_label = x_label,
         y_axis_label = y_label,
         width = plot_width,
         height=plot_height,
         active_scroll='wheel_zoom'
        )

x_range = df[x_col].max()-df[x_col].min()
y_range = df[y_col].max()-df[y_col].min()

cds = bokeh.models.ColumnDataSource(
    df
)
cds_spin = bokeh.models.ColumnDataSource(
    df_spin
)
cds_shear = bokeh.models.ColumnDataSource(
    df_shear
)
# cds.data['volume_fraction'] = [ v*5 for v in cds.data['volume_fraction'] ]

images = p.image_url(
    source=cds,
    x=x_col,
    y=y_col,
    w=350, #x_range*0.02,
    h=350, #y_range*0.02*plot_width/plot_height,
    w_units='screen',
    h_units='screen',
    url='file_url',
    anchor='center',
    global_alpha=.001
)

p.circle(
    source=cds_spin,
    x=x_col,
    y=y_col,
    fill_color='color',
    size=20,
    fill_alpha=0.8,
    line_color='black'
)

p.square(
    source=cds_shear,
    x=x_col,
    y=y_col,
    fill_color='color',
    size=20,
    fill_alpha=0.8,
    line_color='black'
)

p.add_tools(
    bokeh.models.HoverTool(
        tooltips=[
            ('S full', '@Sfull'),
            ('Decay Length (nm)','@CorrLen'),
            ('Image Size (um)','@ImageSize'),
            ('Process','@Process')
        ]
    )
)

p.y_range.callback = bokeh.models.CustomJS( args= {
        'x_axis': p.x_range,
        'y_axis': p.y_range,
        'images': images.glyph,
        'cds': cds,
        'points': p.renderers[6].glyph
    }, 
    code=coffee.compile("""
    ddata = Bokeh._.max(cds.get('data')[points.get('x').field]) - Bokeh._.min(cds.get('data')[points.get('x').field])
    dx = x_axis.get('end') - x_axis.get('start')
    if dx/ddata > .0001
        images.set 'global_alpha', .001 + (.9)*Math.exp( -1*Math.pow(dx/ddata-.0001,2)/.014)
    """,bare=True)
)

p.axis.major_label_text_font_size='16pt'
p.xaxis.axis_label_text_font_size = "16pt"
p.yaxis.axis_label_text_font_size = "16pt"
output_notebook()
show(p)
`

**Comment by bryevdv** [comment]
This appears to have been fixed at some point:

<img width="265" alt="screen shot 2018-05-08 at 20 01 00" src="https://user-images.githubusercontent.com/1078448/39793493-98f6e3dc-52fa-11e8-8203-d40ad7f4129b.png">
