### ISSUE TITLE
Categorical axis labels are not distributed evenly.

### ISSUE THREAD

**Issue by haje01** [bokeh/bokeh#5842]
If you create a figure with a categorical axis, axis labels are not distributed evenly.
In some cases they are concentrated in one side, and some cases they are scattered randomly.

Bokeh version: 0.12.4

Sample code:

    factors = ["abc", "def", "ghi", "klm", "abc", "def", "ghi", "klm", "ghi", "klm", "ghi", "klm", "abc", "def"]
    x = [50, 20, 10, 30, 40, 6, 15, 48, 50, 20, 10, 30, 40, 6]

    p = figure(y_range=factors)
    p.circle(x, factors)
    show(p)

**Comment by bryevdv** [comment]
This is a usage error. The factors for the axis, i.e. for `y_range` in this case, must a *unique* list of factors, in the order that you want them to appear. It cannot have duplicates, as your list does. Then the coordinates for glyph functions can then be whatever combination of the factors you need, have duplicates etc.

**Comment by bryevdv** [comment]
if you need further assistance, the proper place for general support questions is the mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

**Comment by haje01** [comment]
I fixed my code and it works nicely:

    factors = ["abc", "def", "ghi", "klm"]
    p = figure(y_range=factors)

    categories = ["abc", "def", "ghi", "klm", "abc", "def", "ghi", "klm", "ghi", "klm", "ghi", "klm", "abc", "def"]
    x = [50, 20, 10, 30, 40, 6, 15, 48, 50, 20, 10, 30, 40, 6]

    p.circle(x, categories)
    show(p)

Thank you!
