### ISSUE TITLE
Nested categorical axes

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5847]
Placeholder feature request for nested categorical axes (I would have thought we have an issue for this, but couldn't see it)

**Comment by mattpap** [comment]
@birdsarah, I presume #516 is what you're looking for?

**Comment by birdsarah** [comment]
I don't think so. 

I want the a kind of twin axes (http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#twin-axes) but for categoricals. 

So when categoricals have a natural hierarchy you can display this.

e.g. you have: Coffee Drinkers & Tea Drinkers AND Men & Women So you want the outer axis to just show Men | Women and the inner axis to show Coffee, Tea, Coffee, Tea

**Comment by afonit** [comment]
@birdsarah Perhaps related to this one?
https://github.com/bokeh/bokeh/issues/4369

**Comment by bryevdv** [comment]
There's a cluster of related issues that are not very clearly separated right now. I will have to try and make a better stab at outlining all the different work in detail.

**Comment by bryevdv** [comment]
This was accomplished in the categorical refactor
