### ISSUE TITLE
Implement Legend(orientation="auto/best/optimal/...")

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#585]
Currently only fixed orientation is possible: `"top_right"`, `"top_left"`, etc. It would be great to make `Legend` find an orientation where it covers minimal area of a plot.

**Comment by bryevdv** [comment]
I am going to close this. Offhand, I don't know how we'd compute such a heuristic reliably, not even in the "simple" static case, nevermind if pan/zoom interactivity is allowed. But this issue also is back from a time when legends could not be places outside the plot area. Now that that is possible, that is the best solution for always avoiding covering any data, especially in the potential presence of interactive range changes.
