### ISSUE TITLE
Drop in performance executing the same code N times

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#5852]
Hi all,
The following code reveal a drop in performance.  
In short, 'show' and 'push_notebook' execution time increase each time cell#3 is executed. 
I would have expected a constant execution time.
Nicolas.

How to use the example:
You can run cell#3 up to MAX_RUN times. 
Plots f1 & f2 display the 'show' and 'push_notebook' execution time history for the last 'RUN' runs.

#### cell#1
```
from bokeh.io import output_notebook, push_notebook
from bokeh.plotting import figure, show, ColumnDataSource
from IPython.display import clear_output
import numpy as np
import time
output_notebook()
```

#### cell#2
```
N=20
M=1
RUN = 0
MAX_RUN = 10

st = np.zeros((MAX_RUN*N), dtype=np.float64)
pnt = np.zeros((MAX_RUN*N*M), dtype=np.float64)

x = np.linspace(0, 10, 250)
y = np.linspace(0, 10, 250)
xx, yy = np.meshgrid(x, y)
```

#### cell#3
```
if RUN < MAX_RUN:
    for i in range(N):
        clear_output()
        # generate data 
        d = np.sin(i*xx) * np.cos(i*yy)
        p = figure(x_range=(0, 100), y_range=(0, 100))
        ds = ColumnDataSource(data=dict(image=[d]))
        # plot data
        p.image(image='image', x=0, y=0, dw=100, dh=100, source=ds, palette="Spectral11")
        t0 = time.time()
        h = show(p, notebook_handle=True)
        sti = i +  RUN * N
        st[i +  RUN * N] = time.time() - t0
        for j in range(M):
            # update data 
            d = np.sin(2*i*xx) * np.cos(2*i*yy)
            ds.data.update(dict(image=[d]))
            # update plot
            t0 = time.time()
            push_notebook(handle=h)
            pnti = j + (i + RUN * N)
            pnt[j + (i + RUN * N)] = time.time() - t0  

RUN += 1
            
f1 = figure(plot_width=800, plot_height=200, title="show exec. time in sec.)")
f1.line(y=st[0:RUN*N], x=[i for i in range(RUN*N)]) 
show(f1)

print("min show exec. time: {:.4f}".format(np.min(st)))
print("max show exec. time: {:.4f}".format(np.max(st)))

f2 = figure(plot_width=800, plot_height=200, title="push_notebook exec. time in sec.")
f2.line(y=pnt[0:RUN*N*M], x=[i for i in range(RUN*N*M)]) 
show(f2)

print("min push_notebook exec. time: {:.4f}".format(np.min(pnt[0:RUN*N])))
print("max push_notebook exec. time: {:.4f}".format(np.max(pnt[0:RUN*N*M])))
```

**Comment by nleclercq** [comment]
Here are more figures (from [google discussion group](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/g_12wsie0E0)):

In our application, an image is acquired line-by-line on a remote system. The full image data is periodically polled from the system (drt) and displayed in a Jupyter notebook. The associated image plot is updated using calls to push_notebook. Note that we don't use the bokeh server - and don't want to actually :-) Everything is asynchronously scheduled using the "Tornado IOLoop approach" - which works smoothly. 

The first figure below shows the image refresh performances (prt) obtained during a first acquisition sequence. Refresh time being proportional to the image size,  we observe the expected linear increase. At the end of the acquisition, the 1 Mpixels image is updated in approx 1.75s. 

![capture d ecran 2017-02-13 a 14 17 29](https://cloud.githubusercontent.com/assets/19185982/22887403/3f1164d2-f202-11e6-9298-4973c70ae61e.png)

Starting a new acquisition sequence, one would expect the refresh time to drop down to the one observed at the beginning of the first sequence  - something like 0.15 s. Unfortunately, it doesn't and remains at the value reached at the end of the first sequence! Here is what we obtain, at the beginning of the second acquisition sequence:

![capture d ecran 2017-02-13 a 14 20 40](https://cloud.githubusercontent.com/assets/19185982/22887404/3f18d2da-f202-11e6-8a52-eb3c035804e1.png)

Does anybody see what could explain this behavior? 
Thanks.

**Comment by nleclercq** [comment]
Removing the plots from the document before each acquisition sequence solves the problem.

**Comment by mattpap** [comment]
@bryevdv, should this and similar issues have `reso: completed`?

**Comment by bryevdv** [comment]
discussions don't require resolutions.
