### ISSUE TITLE
Jupyter Interactors.ipynb apparently broken

### ISSUE THREAD

**Issue by rebcabin** [bokeh/bokeh#5855]
in bokeh/examples/howto/notebook_comms/Jupyter%20Interactors.ipynb

next to last line

    show(p, notebook_handle=True)

produces the basic visualization, PLUS, the output line

    <Bokeh Notebook handle for In[5]>

last line 

    interact(update, f=["sin", "cos", "tan"], w=(0,100), A=(1,5), phi=(0, 20, 0.1))

produces the following

    <function __main__.update>

The basic visualization shows, but no interactors show, i.e., no drop-down, no sliders.

Mac OSX El Capitan, Python 2.7.13, no Anaconda, everything else seems nominal

**Comment by bryevdv** [comment]
This example is working for me as expected. It is impossible to diagnose or provide help without detailed and complete information, which is why the issue template asked for version information to be provided. E.g. what is your notebook version? ipywidgets version? browser and version?

**Comment by rebcabin** [comment]
Jupyter 4.2.1
ipywidgets info full trace below (looks like 1.2.6)
Chrome Version 55.0.2883.95 (64-bit)

$ pip install ipywidgets
Requirement already satisfied: ipywidgets in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python2.7/site-packages (from ipywidgets)
Requirement already satisfied: ipykernel>=4.2.2 in /usr/local/lib/python2.7/site-packages (from ipywidgets)
Requirement already satisfied: widgetsnbextension>=1.2.6 in /usr/local/lib/python2.7/site-packages (from ipywidgets)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python2.7/site-packages (from ipywidgets)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python2.7/site-packages (from traitlets>=4.2.1->ipywidgets)
Requirement already satisfied: decorator in /usr/local/lib/python2.7/site-packages (from traitlets>=4.2.1->ipywidgets)
Requirement already satisfied: jupyter-client in /usr/local/lib/python2.7/site-packages (from ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python2.7/site-packages (from ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: notebook>=4.2.0 in /usr/local/lib/python2.7/site-packages (from widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: backports.shutil-get-terminal-size in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipywidgets)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipywidgets)
Requirement already satisfied: gnureadline; sys_platform == "darwin" and platform_python_implementation == "CPython" in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipywidgets)
Requirement already satisfied: appnope; sys_platform == "darwin" in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipywidgets)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipywidgets)
Requirement already satisfied: pickleshare in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipywidgets)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipywidgets)
Requirement already satisfied: jupyter-core in /usr/local/lib/python2.7/site-packages (from jupyter-client->ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python2.7/site-packages (from jupyter-client->ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: backports.ssl-match-hostname in /usr/local/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: backports-abc>=0.4 in /usr/local/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: certifi in /usr/local/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: singledispatch in /usr/local/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: terminado>=0.3.3; sys_platform != "win32" in /usr/local/lib/python2.7/site-packages (from notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: nbconvert in /usr/local/lib/python2.7/site-packages (from notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: jinja2 in /usr/local/lib/python2.7/site-packages (from notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: nbformat in /usr/local/lib/python2.7/site-packages (from notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python2.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipywidgets)
Requirement already satisfied: pathlib2; python_version in "2.6 2.7 3.2 3.3" in /usr/local/lib/python2.7/site-packages (from pickleshare->ipython>=4.0.0->ipywidgets)
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from singledispatch->tornado>=4.0->ipykernel>=4.2.2->ipywidgets)
Requirement already satisfied: mistune!=0.6 in /usr/local/lib/python2.7/site-packages (from nbconvert->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: pygments in /usr/local/lib/python2.7/site-packages (from nbconvert->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: bleach in /usr/local/lib/python2.7/site-packages (from nbconvert->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: testpath in /usr/local/lib/python2.7/site-packages (from nbconvert->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python2.7/site-packages (from nbconvert->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python2.7/site-packages (from nbconvert->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python2.7/site-packages (from jinja2->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python2.7/site-packages (from nbformat->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 in /usr/local/lib/python2.7/site-packages (from bleach->nbconvert->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: configparser>=3.5; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from entrypoints>=0.2.2->nbconvert->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)
Requirement already satisfied: functools32; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook>=4.2.0->widgetsnbextension>=1.2.6->ipywidgets)

**Comment by bryevdv** [comment]
None of that looks out of the ordinary at a glance. `interact` is not a Bokeh function, so my initial suggestion, since you state it is the widgets that are not showing up, is to file an issue on the `ipywidgets` issue tracker, not on the Bokeh tracker.

**Comment by rebcabin** [comment]
ok, ty. Verified it also does not work on Firefox ESR 45.7.0

**Comment by rebcabin** [comment]
The missing piece was (apparently)

    jupyter nbextension enable --py --sys-prefix widgetsnbextension

**Comment by bryevdv** [comment]
Is this new? or maybe it's something that conda handles automatically

**Comment by rebcabin** [comment]
I don't know. I found it by running the sample notebooks on ipywidgets. The "Controller" sample initially failed and then gave me that prescription. I ran it, then ran all the samples in ipywidgets (they all worked, now). Then I ran the Bokeh sample above and it worked. 

I have been unable to run Anaconda along with other Python tools I need on my Mac. It seems to be 'either-or'. If I run Anaconda, other stuff breaks. I feel lucky that I was able to back out of Anaconda and get the other stuff working again. Anaconda is now a "third rail" in my brain.

**Comment by bryevdv** [comment]
Anaconda is 100% self-contained in one directory. It does not affect the system python or any other python at all, in any way. Removing it is a trivial measure of deleting that one directory. However, if you are having problems, I'd recommend the Anaconda mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/anaconda

**Comment by bryevdv** [comment]
Can you elaborate on why packages you had trouble with in connection to Anaconda?

**Comment by rebcabin** [comment]
It was a painful experience and I didn't write down and don't remember every detail because I was in a hurry to deliver some results. My take-aways (right or wrong) are (1) I have a bunch of corporate apps and packages that think they "own" Python on my machine. (2) Also, Apple (infamously) "owns" Python on macs. Needing to move quickly, I followed instructions here and there and Frankensteined my corporate stuff into working condition. I installed Anaconda to access some open source things and started getting version conflicts and "missing package" messages. In a panic, I didn't diagnose; I just backed out of Anaconda, the corporate stuff resumed working and I brain-filed Anaconda (rightly or wrongly) into the "do not touch" category. I have been able to keep things working with minimal manual labor since then, and this issue is the first surprise I've had in a long time. I don't use virtual envs (I have successfully in the past), and I realize that I could have better hygiene with them, but it's just another moving piece. I am sure that one day soon I shall have to pave the machine; at that time, I'll insist on the breathing time to try to bring things up in a more disciplined fashion.

**Comment by rebcabin** [comment]
I remembered something: it has to do with PYTHON_HOME or some such as an environment variable. One or other of my Frankenstein pieces or corporate installers either overwrote that silently in my .bashrc, or told me to change it, or told me to take it out. I think that was the source of my problems: lots of drama and gymnastics over environment variables. Once I got it settled, I try to leave it alone.

**Comment by krisklau** [comment]
Hi, 

I had the exact same problem (interact not working from the example). Running the above command solved my issue. 

This is on a fresh Ubuntu MATE 16.04  install, using latest anaconda. Attached is the output from conda info. 
[anaconda_info.txt](https://github.com/bokeh/bokeh/files/1367015/anaconda_info.txt)
[uname-a.txt](https://github.com/bokeh/bokeh/files/1367016/uname-a.txt)
