### ISSUE TITLE
Update install.rst documentation

### ISSUE THREAD

**Issue by kdheepak** [bokeh/bokeh#5858]
The [BokehJS Standalone](http://bokeh.pydata.org/en/0.12.4/docs/installation.html#bokehjs-standalone) section is currently written as follows :

> If you would like to use BokehJS as a standalone JavaScript library, there are two easy ways to get any published release.

To my understanding, only one way is described. What is the other way? Is it documented elsewhere? 

Also, the BokehJS API is not mentioned anywhere in the documentation.

**Comment by bryevdv** [comment]
That "two ways" is either a mistake or some ancient historical cruft. Theoretically BokehJS is also obtainable via `npm` but I can't comment as to the practical nature of that possibility. I'd support updating this sentence, but let's make a new issue/PR for further clarifications.
