### ISSUE TITLE
instance of Figure class in BokehJS does not have reference to xaxis and yaxis

### ISSUE THREAD

**Issue by kdheepak** [bokeh/bokeh#5861]
The function [Bokeh.Plotting.Figure._process_guide](https://github.com/bokeh/bokeh/blob/3995f0f67c0a2a090d06b7b5e50ca31e654da131/bokehjs/src/coffee/api/plotting.coffee#L302-L323) can return the axis object.

Currently, the following does not work

``` javascript
// javascript
p = figure()
p.circle(...)
p.xaxis

Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at http://localhost:5000/static/js/bokeh-api-0.12.4.js:1430:26
    at Array.filter (native)
    at Figure.get (http://localhost:5000/static/js/bokeh-api-0.12.4.js:1429:50)
    at <anonymous>:1:2
```

because of these [lines](https://github.com/bokeh/bokeh/blob/3995f0f67c0a2a090d06b7b5e50ca31e654da131/bokehjs/src/coffee/api/plotting.coffee#L121-L127).

**Comment by mattpap** [comment]
`Axis` is not exported from `models/index` anymore. Need to check if all abstract bases are exported.
