### ISSUE TITLE
Tabs.active doesn't reflect actual active tab

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#5864]
A call "Tabs.active" doesn't reflect actual active tab of the widget.

**Comment by ajasja** [comment]
@nleclercq You'll get better answers if you post a minimal example demonstrating the problem as well as stating which version of bokeh and python you are using.

**Comment by nleclercq** [comment]
@ajasja Here a piece of code illustrating the problem. I'm using Bokek 0.12.4 and Python 2.7.5.

`import bokeh.models.widgets as bkhwidgets
from bokeh.io import show, output_notebook
from bokeh.plotting import figure
output_notebook()
tl = list()
for t in ['t1', 't2', 't3']:
    tl.append(bkhwidgets.Panel(child=figure(plot_width=400, plot_height=200), title=t))
tabs = bkhwidgets.Tabs(tabs=tl)
hdl = show(tabs, notebook_handle=True)`

Whatever is the selected tab, a call to `tabs.active` returns 0.

**Comment by ajasja** [comment]
@nleclercq I'm quite new to bokeh, but are you running this with a bokeh server? 
If not, I don't think that the pyhon kernel and the javascript can synchronize. When you click on the widgets only java-script is executed. 

The reverse does work, so if you do in another cell:

```
tabs.active = 2
hdl = show(tabs, notebook_handle=True)
```

Then the correct tab will be displayed. 

[Tabs](http://bokeh.pydata.org/en/latest/docs/reference/models/widgets.panels.html) does have a javascript callback, so you can run some JS there, but I know this is not the best solution.

**Comment by nleclercq** [comment]
I see. I'm not running the code in a bokeh server context.
BTW, what i'm was trying to do is totally natural with ipywidgets and I couldn't image that it will not work with the amazing Bokeh framework.
Thanks.

**Comment by ajasja** [comment]
@nleclercq Have you tried to display a Bokeh plot in an ipywidgets panel? That was my first thought, but I couldn't get it working (Something about an unclean json...)
```
import ipywidgets as widgets
children = []
for t in ['t1', 't2', 't3']:
    children.append(figure(plot_width=400, plot_height=200))
tab = widgets.Tab(children=children)
tab
```
![image](https://cloud.githubusercontent.com/assets/19926/22890935/0d98cfd8-f20e-11e6-8b4e-a126d1e93d23.png)

**Comment by azjps** [comment]
See this [section in the documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#python-callbacks-with-jupyter-interactors). To my knowledge, there's no way to synchronize changes made on the HTML/JS side back to python except through bokeh server.

**Comment by nleclercq** [comment]
@ajasja Thanks for trying with ipywidgets.Tab. As I mainly use ipywidgets that's what I tried first before switching to bokeh.Tabs. Thanks again.

@azjps I'm trying the '[embed approach](https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/notebook_embed.ipynb)' of the server.

**Comment by ajasja** [comment]
@nleclercq  I guess you've seen also the [example](https://github.com/bokeh/bokeh/blob/master/examples/howto/notebook_comms/Jupyter%20Interactors.ipynb) with Ipywidgets? Although there the plot is show in a seperate cell and you would somehow have to "fake" a tab.

**Comment by nleclercq** [comment]
Finally, here is what I have done:

First, let's call 'C' the python class to which the 'tabs selection changed' callback is attached.  
Instances of C are stored into a 'global' (i.e. easily accessible) repository - a simple dict in my case.
The idea is to pass the JS callback the C instance 'key'.  It then becomes trivial to 'build' a python command within the JS callback context and ask the IPython kernel to execute it. 
On JS side, the callback argument 'cb_obj' provides us with everything we need concerning the Tabs wigets state - notably its 'active' tab.  

BTW, I think we can close this issue.

```
import bokeh.models.widgets as bkhwidgets

class C(object):
    def __init__(self):
        c_repository[self.uid] = self
        self.tabs_widgets = bkhwidgets.Tabs(...)
        self.tabs_widgets.name = self.uid
        self.tabs_widgets.js_on_change('active', self.tabs_custom_js_callback())
  
    def tabs_custom_js_callback(self):
        return CustomJS(args=dict(tabs=self.tabs_widgets), code="""
            /// build python kernel command: invoke 'tab_selection_changed' on 'c_repository[tabs.name]'
            var imp = "from myPythonModule import c_repository;"
            var call = "c_repository[".concat(tabs.name,"].tab_selection_changed(")
            var arg  = cb_obj.properties.active.spec.value.toString()
            var cmd  = imp.concat(call, arg, ")")
            console.log(cmd)
            /// ask the python kernel to execute the command
            var kernel = IPython.notebook.kernel
            kernel.execute(cmd)
        """)

    def tabs_selection_changed(self, active_tab): 
        # user selected 'active_tab' 
        <do the job> 
```
