### ISSUE TITLE
Add 'source' parameter to bokeh.charts objects

### ISSUE THREAD

**Issue by jeweinberg** [bokeh/bokeh#5865]
I was wondering if it would be possible to add the 'source' parameter to Bokeh.Charts objects. This would be helpful in connecting plot interactions to the .charts objects. Right now, I have to create a boxplot manually with the .plotting objects and the script is quite tedious. It would be nice if the .charts BoxPlot() class just let users update its source so interactivity can be done on that object.

**Comment by Maggie-M** [comment]
moving to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/40)
