### ISSUE TITLE
Need help showing strings in tooltips

### ISSUE THREAD

**Issue by csmith82** [bokeh/bokeh#5866]
I'm trying to create a program that will plot data from excel and have the tooltips show various pieces of information about each point.  So far I'm able to plot the data (in this case Parameter2 v Parameter1) and hover over to see the numerical x and y values.  Within the DataFrame there are Equipment values which reference the equipment used to create the samples.  I'm having issues correctly referencing the corresponding equipment value.  Any help would be appreciated.
```
hover = HoverTool(tooltips = [
                **("Equipment", 'dataset.Equipment.values'),**
                ("data (using @) (x,y)", "(@x, @y)"),
                ])

TOOLS=[hover]
def mscatter(p, x, y):
    p.scatter(x, y,
            line_color="#6666ee", fill_color="#ee6666", fill_alpha=0.5, size=12)

def mtext(p, x, y, textstr):
    p.text(x, y, text=[textstr],
         text_color="#449944", text_align="center", text_font_size="10pt")
output_file("example.html")

p = figure(title="Stuff", tools = TOOLS)
mscatter(p, x=dataset.Parameter1.values, y=dataset.Parameter2.values)
show(p)
```

![image](https://cloud.githubusercontent.com/assets/25753326/22901107/e1f61c48-f1ed-11e6-8967-6839fe70430a.png)

**Comment by csmith82** [comment]
Ok, I found some example script and rewrote mine, this seems to work so far.


dataset = pd.DataFrame(arr)
dataset.columns = [headers]
dataset.replace('', np.nan, inplace=True)
Eq = list(dataset.Equipment)
EOT = list(dataset.EOT)
source = ColumnDataSource(
        data=dict(
            x=dataset.Temperature.values,
            y=dataset.Capacitance.values,
            tool=Eq,
            effox = EOT
            
        )
    )

hover = HoverTool(
        tooltips=[
            ("index", "$index"),
            ("x", "(@x)"),
            ("y", "(@y)"),
            ("Equipment", "@tool"),
            ("Effective Oxide Thickness", "@effox"),
        ]
    )

p = figure(plot_width=400, plot_height=400, tools=[hover, ],
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)

**Comment by bryevdv** [comment]
I'm glad it's working however in the future, please direct general support questions to the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

The tracker is reserved for bug reports and feature requests *only* in order to try and keep it manageable.
