### ISSUE TITLE
Multy-figure embedding: ValueError: To render a Model as HTML it must be part of a Document

### ISSUE THREAD

**Issue by Sklavit** [bokeh/bokeh#5869]
**Expected behavior:** you can use  `bokeh.embed.components` with tuple as argument as stated in [documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#components)
**Observed behavior:** you will receive `ValueError: To render a Model as HTML it must be part of a Document`

**Cause**: Despite of documentation, **components** don't work with tuples, it works only with lists. Code debugging shows direct place of issue:
```
# file bokeh/model.py

class _ModelInDocument(object):
    # 'models' can be a single Model, a single Document, or a list of either
    def __init__(self, models):
        from .document import Document

        self._to_remove_after = []
        if not isinstance(models, list):  # ISSUE IS HERE: in case of components((m1, m2)), models is tuple
            models = [models]
```

**Proposed solution:**
- change documentation
- OR change code for real support of tuples

**Relevant info:**
Bokeh version: 0.12.3
Python: 3.4.5

**Example:**
```
from bokeh.plotting import figure
from bokeh.embed import components

x1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y1 = [0, 8, 2, 4, 6, 9, 5, 6, 25, 28, 4, 7]
x2 = [2, 5, 7, 15, 18, 19, 25, 28, 9, 10, 4]
y2 = [2, 4, 6, 9, 15, 18, 0, 8, 2, 25, 28]

p1 = figure()
p1.scatter(x1, y1)

p2 = figure()
p2.scatter(x2, y2)

script, div = components((p1, p2))
print(script)
print(div)
```

**Comment by bryevdv** [comment]
@Sklavit it sounds like you have a pretty good grasp on the issue.  If you'd like to submit a PR for either  solution you mention, we'd be happy to accept it.

**Comment by jsignell** [comment]
What about replacing this line: 

`if not isinstance(models, list)` with `if hasattr(models, "__iter__")`

**Comment by bryevdv** [comment]
or use something like 
```
from collections import Iterable

if not isinstance(models, Iterable):
```

**Comment by bryevdv** [comment]
The code around this was reworked some time ago, which evidently fixed this issue as a side-effect. I can no longer reproduce any issue with the example code above.
