### ISSUE TITLE
Validation on server_cycle.py

### ISSUE THREAD

**Issue by ricardovinci** [bokeh/bokeh#5876]
Hi everyone,

As I asked here https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/54GrmBRdNZM

I was trying to validate a token on my server_cycle.py more specifically at def on_session_created(session_context):

I think it would be a great feature for Bokeh if we had an option to destroy the session right there and return an error and/or show an error page, e.g.

def on_session_created(session_context):
 .
 .
 .
#tokenNotValid
else
 session_context.destroy()
 return Error

Best,

Ricardo

**Comment by bryevdv** [comment]
Additionally, potentially of interest, tornado provides a hook for getting the current validated user:

http://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.get_current_user

There's not currently any easy way for Bokeh users to use this hook, but we could make a way for users to provide a function to validate a user. @ricardovinci is your use case validating a user identity? Or something else? Some context would help with filling in the bigger picture.

**Comment by ricardovinci** [comment]
Hi @bryevdv,

Thanks for the quick reply!

I am validating if a user is authorized to make a request to the bokeh server. The request to the bokeh server is made by a different system, that's why I do it through a token. I get an oAuth token from the URL and I validate it on a different microservice through an HTTP request. I'm calling the validate function bellow on my server_cycle.py and based on the JSON response I get I would like to for example throw an error.
```

def validate_token(mytoken):
 url = "https://mymicroservice.com/validate/user"
 headers = {'Accept': 'application/json', 'Host': 'mymicroservice.com', 'Authorization': mytoken}	
 r = requests.get(url, headers=headers)	
 if not r.status_code == requests.codes.ok:
  return None
 data = r.json()
	
return data

```

So what I would like to do on my server_cycle.py is something like:

```
def on_session_created(session_context):
 try:
 mytoken = args.get('token')[0].decode("UTF-8")
 except:
 mytoken = ""
 #calling  validate function here
 myjson = validate_token(mytoken)

if myjson.isTokenValid
 pass
else
 session_context.destroy()
 return someKindOfError
```

**Comment by bryevdv** [comment]
This seems tangentially related to #9074 and the recent auth hooks work. I think this can be closed. Currently you can use auth hooks to prevent sessions from being created at all, and redirect to whatever landing/login page you like, if there is not an authenticated user. And in the near future the session id's will become proper tokens that encode whatever entitlements you want (in addition to conventional ones such as "not before" or "expires as"). I think that would provide everything asked for here in one way or another.
