### ISSUE TITLE
 bokehjs API widget examples

### ISSUE THREAD

**Issue by GuyAllard** [bokeh/bokeh#5877]
It would be beneficial to include example of how to use widgets from the Bokeh JS API as none of the current BokehJS examples demonstrate this.

This issue was submitted in response to [this thread on the discussion group](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/Bf7LWTdiR5I)

**Comment by mortonjt** [comment]
Note, this would be really nice to have.  At the moment, is not clear how to interact with the bokehjs interactive plots.  This especially useful to have in scenarios where one cannot get a bokeh-server up and running, and are restricted to creating static html pages.

**Comment by bryevdv** [comment]
@mattpap I'd like to close this can consolidate under the general BokehJS examples issue #6574
