### ISSUE TITLE
Make "bokeh finished rendering heuristic" work with non-plot examples

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5879]
Currently they time out, because "finished" event isn't ever triggered.

**Comment by bryevdv** [comment]
@mattpap @canavandl FYI there is a `tilesloaded` event in the GMap API:

https://developers.google.com/maps/documentation/javascript/events
https://stackoverflow.com/questions/8677261/google-map-v3-map-loaded-event

Although it also looks like there is are suggestions to trigger off `idle`

For ImageURL and `TileRenderer` I think we can definitely have the actual image render trigger code to set a condition variable, then as soon as all the conditions are met (however many tiles/images there are) a "done" for that renderer can be generated. 

cc @jbednar
