### ISSUE TITLE
Support embed bokeh into apache zeppelin

### ISSUE THREAD

**Issue by zjffdu** [bokeh/bokeh#5885]
[Apache Zeppelin](https://zeppelin.apache.org/) is a web-based notebook that enables interactive data analytics. I'd like integrate bokeh into Apache Zeppelin as Jupyter notebook. As the first step, I just want to visualize the chart in zeppelin directly.

**Comment by zjffdu** [comment]
Sorry, I didn't find way to add tags to Labels, maybe I miss something.

**Comment by bryevdv** [comment]
Thanks @zjffdu !

**Comment by canavandl** [comment]
@zjffdu 

The Zeppelin support PR was including in the latest dev release. You can install and try it out via ``conda install -c bokeh/label/dev bokeh=0.12.6dev2``. Thanks again for the feature.

**Comment by zjffdu** [comment]
Thanks @bryevdv @canavandl for helping to merge this PR.
