### ISSUE TITLE
tests/examples/examples_report_plugin.py assumes clone has a remote named origin

### ISSUE THREAD

**Issue by timsnyder** [bokeh/bokeh#5888]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant pacakges)
* bokeh master sha 3e802d4f6
* conda environment on anaconda.org [tsnyder/bokeh-dev-py34.1-170217-0714](https://anaconda.org/tsnyder/bokeh-dev-py34.1-170217-0714)
* I'm running on a Centos7 VM
* git version 1.8.3.1

#### Description of expected behavior and the observed behavior
The tests are failing to run for me because I don't have a remote named 'origin' in my clone.  When working in a Fork&PR workflow, I generally dislike using the default remote 'origin' and prefer to have two remotes named:
* upstream - points to the upstream repo, in our case bokeh/bokeh
* mygh - points to my github fork.  In my case, tsnyder/bokeh

I do this because I have a hard time remembering whether I cloned from bokeh/bokeh or timsnyder/bokeh.  If I don't have a remote named origin, but instead use a descriptive name, I don't have to try and remember.  I just push to mygh and pull from upstream.

#### Complete, minimal, self-contained example code that reproduces the issue
No code changes required.  Steps to reproduce:
```
git config --get-regexp remote.origin && git remote rename origin not-named-origin
py.test -m 'not (js or examples or integration or quality)'
```

##### Observed behavior:
```
.-(~/bokeh)---------------------------------------------------------------------------------------(tsnyder@centos7vm)-
`-- (git)-[master]-> py.test -m 'not (js or examples or integration or quality)'
fatal: Not a valid object name origin/master
Failed to get version for origin/master
```

##### Expected behavior:
I expect that it would work without a remote named 'origin'.  
#### Stack traceback and/or browser JavaScript console output
n/a

#### Screenshots or screencasts of the bug in action
n/a

#### Bug Origin
It looks like @mattpap added the `--diff-ref` option to `examples_report_plugin.py` in #5713.  Just mentioning you so that you have a chance to comment on the intended default behavior of `--diff-ref`.

#### Suggested Fix
It may be better to use the special reference named '@{upstream}' as documented by [gitrevisions(7)](https://www.kernel.org/pub/software/scm/git/docs/gitrevisions.html)

Or, if the intent is to always check against bokeh/bokeh master, regardless of the current branch, we should do a reverse lookup for the correct remote name to use.

I'm going to try out my fix and submit a PR for this.

**Comment by mattpap** [comment]
@timsnyder, the choice of `origin` was a bit presumptuous and `master@{upstream}` seems the right thing to do. I'm glad you did the research, as I did't know about this useful syntax.

**Comment by bryevdv** [comment]
@timsnyder thanks for the detailed and thorough issue report! It looks like @mattpap jumped on a PR with your solution, but there's plenty of things to work on :)

**Comment by timsnyder** [comment]
@mattpap, I'm glad to have shown you something useful.  I can confirm that I get past this issue after pulling your change.

Thanks!
