### ISSUE TITLE
Tick Label Formatting Causes Non-Functional Zooming With WMTSTileSource

### ISSUE THREAD

**Issue by pjkottke** [bokeh/bokeh#5890]
The below working example for a broken and working WMTSTileSource. When zooming in with the mouse wheel, the "broken" plot will jump between zoom levels and is unable to zoom in fully. By specifying a fixed precision for the tick labels, normal zoom behavior is functioning in the "working" example. Another, non github, post mentioned that this is likely due to the way the plot area resizes to accommodate tick label precision, which then forces the zoom level to change creating a loop at certain zoom levels.

Note that sometimes, depending on how fast you scroll, you can skip the zoom level that is causing the issues.

I am running bokeh version 0.12.4 on windows and the issue appears on both Chrome and IE.

```
from bokeh.plotting import figure, show
from bokeh.models import WMTSTileSource
from bokeh.models.formatters import PrintfTickFormatter
from bokeh.models.widgets import Panel, Tabs

x_start = -1.1538e7
y_start = 4.306e6
y_diff = 0.005e6

broken_fig = figure(width=750, height=600, x_range=[x_start,x_start+y_diff], y_range=[y_start,y_start+y_diff])
working_fig = figure(width=750, height=600, x_range=[x_start,x_start+y_diff], y_range=[y_start,y_start+y_diff])

tile_source = WMTSTileSource(url='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.jpg')
broken_fig.add_tile(tile_source)
tile_source = WMTSTileSource(url='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{Z}/{Y}/{X}.jpg')
working_fig.add_tile(tile_source)

working_fig.xaxis[0].formatter = PrintfTickFormatter(format="%+02.5e")
working_fig.yaxis[0].formatter = PrintfTickFormatter(format="%+02.5e")

show(Tabs(tabs=[Panel(child=broken_fig,title='Broken'),Panel(child=working_fig,title='Working')]))
```

**Comment by bryevdv** [comment]
This seems like more of a support and usage question. There may just be situations where the auto sizing is incompatible with other features. In those instances you can:
* set `min_border`, etc to specify a permanent border large enough to accommodate any expected tick lenght
* rotate the ticks so hey are parallel to the axis, not perpendicular
