### ISSUE TITLE
Typo (missing comma) in example code for labels

### ISSUE THREAD

**Issue by HenningTimm** [bokeh/bokeh#5902]
In the example for labels on the annotations page of the user guide, a comma in the parameter list is missing, resulting in a syntax error when copy-pasting it.

Specifically, line 171 of  [annotations.rst](https://github.com/bokeh/bokeh/blob/d90175c36d4e1473f7c13ce91eb47bd890f5a3eb/sphinx/source/docs/user_guide/annotations.rst)

    Label(x=70, y=70, x_units='screen' text='Some Stuff', render_mode='css',

should be:

    Label(x=70, y=70, x_units='screen', text='Some Stuff', render_mode='css',

Can/ should I create a PR to fix this?

**Comment by bryevdv** [comment]
That would be appreciated, thanks!
