### ISSUE TITLE
Hover Inspection does not work for all glyphs

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#5907]
Using [Hover Inspection](http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#hover-inspections) with glyphs other than a circle does not work, or at least square a diamond (I did not test further).  A simple test is to replace `circle` in the linked example with `square`.  

In this screenshot below, I copied the example, added circles vertically offset by 100, then replaced the original circles by squares.  You can see that when I hover, only the circles are highlighted.

![image](https://cloud.githubusercontent.com/assets/9484229/23221437/1811f930-f8f3-11e6-91c9-d48d7f7839ed.png)

As there is no error thrown in python, I wonder if the bug is on the js end.

**Comment by bryevdv** [comment]
Is there any JS console output?

**Comment by bryevdv** [comment]
Simple explanation, `_hit_span` is not implemented on `Marker`
