### ISSUE TITLE
Unable to right align tick labels 

### ISSUE THREAD

**Issue by kdheepak** [bokeh/bokeh#5914]
The following is a MWE based on @MatejKovacic's example from the gitter channel.

``` python
# coding: utf-8

from bokeh.plotting import figure, show, output_notebook
from bokeh.models import PrintfTickFormatter

output_notebook()

x = range(0, 100)
# average temerature on both sensors
y = range(0, 100)
#temperature on single sensor only
y_red = y
y_yellow = y

p = figure(plot_width=900, 
           plot_height=400,
           tools="save",
           x_range=['really_long_label_{}'.format(i) for i in x], 
           y_range=(round(min(y),0)-1,round(max(y),0)+2), 
           x_axis_location='below')

p.vbar(x=x, width=0.7, bottom=0, top=y, color="firebrick")

p.xaxis[0].formatter = PrintfTickFormatter(format='%s')
p.xaxis.major_label_orientation = "vertical"

p.line(x, y_red, line_width=2, line_color="red")
p.circle(x, y_red, line_width=2, line_color="red", fill_color="red", size=4)

p.line(x, y_yellow, line_width=2, line_color="yellow")
p.circle(x, y_yellow, line_width=2, line_color="yellow", fill_color="yellow", size=4)

show(p)
```

![bokeh_plot](https://cloud.githubusercontent.com/assets/1813121/23266379/dd92d632-f9a4-11e6-87e2-52756b024530.png)

It appears that one cause of the issue might be that [ctx.fillText](https://github.com/bokeh/bokeh/blob/3995f0f/bokehjs/src/coffee/models/axes/axis.coffee#L106) is not sufficient for right aligning text. It seems that the [textalign](https://www.w3schools.com/tags/canvas_textalign.asp) property of a `ctx` must be used.

Currently at this point, no matter that "padding" I use in the PrintfTickFormatter, I am unable move the labels below the xaxis.

@bryevdv Thoughts?

**Comment by bryevdv** [comment]
I can confirm this issue. This should not have anything do do with the formatter, which is only responsible for numeric tick locations into text tick labels. The positioning of those labels is handled by the axis. The axis is supposed to measure the label text and use the reported size both to inform the layout system as well as to position the label. My guess is there is some logic problem specific to the `"vertical"` setting, although it's possible there is a more general error that just shows up in some cases . 

However, for an immediate workaround, I found that using numeric values for the orientation may help. For instance:
```
p.xaxis.major_label_orientation = math.pi/2
```
results in 

<img width="805" alt="screen shot 2017-02-23 at 10 20 49" src="https://cloud.githubusercontent.com/assets/1078448/23267909/c38b7232-f9b1-11e6-8e92-16bbff7a0384.png">

**Comment by kdheepak** [comment]
Awesome, that's a good workaround for now.
