### ISSUE TITLE
FuncTickFormatter.from_py_func not working properly

### ISSUE THREAD

**Issue by fredzett** [bokeh/bokeh#5917]
My below code example doesn't produce any result (but also no error message). Based on user guide I would have expected this code to work. 

```
x = np.arange(10)
y = [random.uniform(0,5000) for el in x]
xfactors = list("abcdefghi")
yrange = Range1d(0,5000)
p = figure(x_range = xfactors, y_range = yrange,y_minor_ticks = 10)
p.circle(x,y, size = 14, line_color = "grey" , fill_color = "lightblue", fill_alpha = 0.2)

def ticker():
    a = '{:0,.0f}'.format(tick).replace(",", "X").replace(".", ",").replace("X", ".") 
    return a

#If I comment below line out, code is running just fine
p.yaxis.formatter = FuncTickFormatter.from_py_func(ticker)

show(p)
```

If I comment the FuncTickFormatter line out the code is just running fine. Also the defined function ticker works if I use it outside this code.

Seems like the feature is not working properly. 

I posted this question on stackoverflow and with some help was able to fix my issue using javascript code. However, I would still be interested to know if there is a solution using from_py_func or if this is a bug. 

Thanks
Fred!

P.S.: this is my first activity on github. So please be gentle on me if I didn't see the obvious solution...;-)

**Comment by mattpap** [comment]
Bokeh uses flexx library to convert Python to JavaScript. It looks like `"...".format(tick)` is not supported by flexx. You could use `"..." % tick` instead, if an equivalent format exists. You may want to follow up with with flexx's developers to resolve this issue (https://github.com/zoofIO/flexx).

**Comment by mattpap** [comment]
> this is my first activity on github.

Sure. Next time please submit a complete example, including imports, so that I can copy, paste and run the code. In Python community including complete imports the default. Also, include error messages, including output from JS console. Additionally, use triple backticks to format a block of code (https://guides.github.com/features/mastering-markdown/).

**Comment by bryevdv** [comment]
I'm going to go ahead and close this to clear up the tracker. For additional support type questions please do come by the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

Or the gitter chat channel.
