### ISSUE TITLE
LOD in linked plots

### ISSUE THREAD

**Issue by herm** [bokeh/bokeh#5937]
When I have two linked plots (via `x_range=plot1.x_range`)  and move them only the plot I'm moving by hand gets LOD mode applied. This effectively makes the whole moving operation slow again. LOD should be applied to all plot being moved.

Version: 0.12.4

**Comment by bryevdv** [comment]
There's a straightforward simple way to accomplish this unfortunately, but we will take a look at it as resources permit.

**Comment by bryevdv** [comment]
Actually, this work might offer a path: https://github.com/bokeh/bokeh/pull/5941#issuecomment-283993187

**Comment by jrderuiter** [comment]
Would also be interested in this!
