### ISSUE TITLE
WebGL lines show wrong data if input contains NaNs

### ISSUE THREAD

**Issue by herm** [bokeh/bokeh#5939]
When trying to plot data using WebGL the output is wrong if there is at least one NaN in the data. It doesn't matter if the NaN is in x or y. 

I've attached an example that plots numbers in the range of (-1, 1). In first plot the whole dataset is plotted and in the second plot the first x value is set to NaN. 

The first plot shows the expected result, while the second plot shows values far outside the expected region of (-1,1). The actual range of data being shown depends on the zoom settings. Sometimes it's over 9000. 
![bokehnan](https://cloud.githubusercontent.com/assets/753225/23457591/d6ba9182-fe78-11e6-8418-6b2b683c669e.png)

Tested with both Chromium and Firefox.

[BokehWebGLNaN.ipynb.zip](https://github.com/bokeh/bokeh/files/810497/BokehWebGLNaN.ipynb.zip)

**Comment by bryevdv** [comment]
Unfortunately the original author of of BokehJS webgl support is no longer an active contributor. It will take time for someone new to come up to speed, so this will not make it in time for `0.12.6`, moving to the next milestone.

**Comment by bryevdv** [comment]
I had hoped to make WebGl a focus of `0.12.7` but it will have to be `0.12.8` cycle

**Comment by bryevdv** [comment]
closing in favor of https://github.com/bokeh/bokeh/issues/8489 which has a runnable MRE
