### ISSUE TITLE
Categorical columns as labels in bokeh Bar charts cause error 

### ISSUE THREAD

**Issue by areshytko** [bokeh/bokeh#5940]
Bar chart doesn't accept categorical column as a label

```python
df = pd.DataFrame({'foo': [1, 0, 1, 1, 0]})
df.foo = df.foo.astype('category')
plt = Bar(df, label='foo')
show(plt)

```

This raises an error:

`ValueError: expected an element of either Column(Float) or Column(String), got [1, 1, 1]
Categories (2, int64): [0, 1]`

IMHO this is an issue, because by it's nature the label variable in bar charts is of categorical nature. And in pandas dataframes they often **are** typed as categorical. Converting them to object before using charts in interactive sessions makes Bar chart basically unusable.

**Comment by bryevdv** [comment]
bokeh.charts has moved to https://github.com/bokeh/bkcharts this should be re-opened there if appropriate.
