### ISSUE TITLE
LaTeX Label example is broken in dev docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5954]
Currently at [dev docs](http://bokeh.pydata.org/en/dev/docs/user_guide/extensions_gallery/latex.html#userguide-extensions-examples-latex):

<img width="1189" alt="screen shot 2017-03-05 at 15 22 58" src="https://cloud.githubusercontent.com/assets/1078448/23591555/a38ce5de-01b7-11e7-9670-97ab083b817a.png">

**Comment by bryevdv** [comment]
"Wrapping a JavaScript Library" also broken:

http://bokeh.pydata.org/en/dev/docs/user_guide/extensions_gallery/wrapping.html#userguide-extensions-examples-wrapping

<img width="843" alt="screen shot 2017-03-05 at 15 25 38" src="https://cloud.githubusercontent.com/assets/1078448/23591582/02e9f166-01b8-11e7-8f37-cdcda77e3705.png">

**Comment by bryevdv** [comment]
`examples/app/surface3d` and `examples/models/external_resources.py` do work, though, so hopefully this is just some small thing that did not get updated recently. Need to note any migration notes that are necessary if they haven't been already.

**Comment by mattpap** [comment]
In general, the issue of handling text vs. HTML is a mess across bokeh (especially in annotations).
