### ISSUE TITLE
add source parameter to Span or create SpanSet

### ISSUE THREAD

**Issue by agilly** [bokeh/bokeh#5962]
This is not a bug but rather a feature request.

The `Label` text annotation currently has a very useful corresponding `LabelSet` companion that allows to define a `ColumnDataFrame` as `source` for the text boxes.

It would be helpful to have an equivalent `SpanSet` object to draw multiple spans from a `ColumnDataFrame`. Currently, to arrive at the same result one has to hack one's way using `ray` objects bound to a data frame.

Current way:
```python
# rays used as spans, y is a large negative number for vertical spans
p.ray(x='x', y='y', color='firebrick', length=0, angle=90, angle_units='deg', alpha='alpha', source=ray_source)
```

Proposed way:
```python
spans=SpanSet(location='x', dimension='height', line_color='firebrick', alpha='alpha', source=span_source)
p.add_layout(spans)
```

```

**Comment by bryevdv** [comment]
This seems reasonable. Checking, do you have the ability and interest to work this up in a PR? The `LabelSet` code should be a fairly reasonable comparison and we are happy to answey any dev-related questions.

**Comment by bryevdv** [comment]
ping @agilly sorry I should have used your GH name in the previous message to notify you

**Comment by agilly** [comment]
Sorry for the delay. Interest, certainly; ability, not sure. This would certainly be a first. It might take some time until I get my bearings. So far I can see 3 files that would need to be modified/created:

- **bokehjs/src/coffee/models/annotations/index.ts**, modified with something like `export {SpanSet} from "./span_set"`
- **bokehjs/src/coffee/models/annotations/span_set.coffee**, which should be modelled after `label_set.coffee`
- **bokeh/models/annotations.py**, for the class definition.

Is there anything else (apart from the docs)?

**Comment by bryevdv** [comment]
@agilly Yes that's pretty much it for the implementation. The PR would need also need a basic "test the default values" test like this:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/tests/test_annotations.py#L223

I'm happy to advise or help contribute on any or all of those (including the docs which is just a line to add things to the refguide and a small section in the users guide)

**Comment by bryevdv** [comment]
@behinger if there were any update, it would be here. Resources are very limited right now, we are happy to help/advise anyone who would like to work on a PR earlier than the core team is able to look at it.

**Comment by bryevdv** [comment]
PR had to be reverted, unfortunately, due to errors on master after merge.

**Comment by mattpap** [comment]
In PR #12677 `HSpan` and `VSpan` glyphs were implemented, which allow to achieve what was proposed in this issue. Additionally, existing vectorized annotations will be replaced with glyphs (see e.g. PR #13344).
