### ISSUE TITLE
JS error on callback

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#5963]
On current master, 

Python version      :  3.5.3 | packaged by conda-forge | (default, Feb 10 2017, 07:09:50) 
IPython version     :  5.2.2
Bokeh version       :  0.12.5dev14-12-gcdc46df
node.js version     :  v6.6.0
npm version         :  3.10.3

With freshly built bokehjs, I am getting an error when trying to call CustomJS from a button. For example when running examples/plotting/file/line_on_off.py I get this error message:

```sh
Uncaught ReferenceError: exports is not defined
    at r.eval (eval at <anonymous> (line_on_off.html:32), <anonymous>:4:23)
    at r.CustomJS.r.execute (line_on_off.html:208)
    at t.i.CheckboxGroupView.t.change_input (line_on_off.html:414)
    at HTMLDivElement.dispatch (line_on_off.html:594)
    at HTMLDivElement.o.dispatch (line_on_off.html:616)
    at HTMLDivElement.g.handle (line_on_off.html:593)
```

![out](https://cloud.githubusercontent.com/assets/4806877/23719693/6363cf68-040a-11e7-9b08-b5fbcb6e569f.gif)

This error is also mentioned in #5488

**Comment by jsignell** [comment]
@mattpap

**Comment by mattpap** [comment]
@jsignell, next time please submit JS tracebacks using unminified resources. The easiest is to use `BOKEH_DEV=true python some.py`. This will set a few more things, e.g. debug logging. You can find out more about this in dev guide. This works for file examples. Server and notebook are a bit more tricky to deal with.

**Comment by jsignell** [comment]
Ok thanks for the tip!
