### ISSUE TITLE
Linked Brushing with pandas DataFrame

### ISSUE THREAD

**Issue by CarlAndersson** [bokeh/bokeh#5987]
Linked brushing for data stored in padas DataFrames require conversion to ColumnDataSource.
Is it possible to implement linked brushing for DataFrame inputs?

MWE below show the differences. In the top gridplot the linked brushing is not working, but in the bottom gridplot it is working.
The extra conversion step seems unnecessary. 

`
from bokeh.plotting import figure, show, output_notebook
from bokeh.models import ColumnDataSource
from bokeh.layouts import gridplot
import numpy as np
import pandas as pd

output_notebook()
TOOLS = 'lasso_select,reset'

df = pd.DataFrame({'x':np.arange(5), 'y':np.arange(5)**2, 'z':np.arange(5)**3})

left=figure(tools=TOOLS,width=300,height=300)
right=figure(tools=TOOLS,width=300,height=300)
left.scatter('x','y',source=df)
right.scatter('x','z',source=df)
show(gridplot([[left,right]]))

cds = ColumnDataSource(df)

left=figure(tools=TOOLS,width=300,height=300)
right=figure(tools=TOOLS,width=300,height=300)
left.scatter('x','y',source=cds)
right.scatter('x','z',source=cds)
show(gridplot([[left,right]]))
`

**Comment by bryevdv** [comment]
Linking in Bokeh is is expressed by (and requires) sharing a *Bokeh model*. There is no getting around this.  In the case of linked brushing, it is a Bokeh ColumnDataSource that needs to be shared. There is no good way to make the first case, where (purely as a convenience) completely new CDS's are created for the passed in DataFrames, work like the second case.
