### ISSUE TITLE
Remove deprecated output_server

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5989]
The existence of `output_server` complicates #5979 considerably. It was deprecated in `0.12.3` and although two releases is a somewhat short deprecation cycle:

* it is hardly functional to begin with
* it is not demonstrated anywhere in the docs, examples, etc.
* have not seen any questions regarding it on ML, SO, etc. anytime recently. 

Will remove, to help make #5979 simpler.

**Comment by mattpap** [comment]
> although two releases is a somewhat short deprecation cycle

Given our capabilities this is more than enough.

**Comment by bryevdv** [comment]
Great. I am proceeding with a PR for this now, before continuing on the other PR. I am also removing `push`. Although it was not technically deprecated, it has zero use without `output_server`. Getting rid of both then allows to remove alot of other ugly cruft as well.
