### ISSUE TITLE
Pass HTTP request arguments to autoload_server and pull_session

### ISSUE THREAD

**Issue by anniea** [bokeh/bokeh#5992]
#4858 makes it possible to pass HTTP requests arguments to app documents. However, the functions `autoload_server` and `pull_session` do not allow for sending request parameters, because they already add a query string to the URL.

For instance, `autoload_server` adds `/autoload.js?bokeh-autoload-element=...&bokeh-session-id=...` to the end of the URL. If I add the query string `?N=10` to the end of my `app_path`, then the URL will result in `?N=10/autoload.js?bokeh-autoload-element=...&bokeh-session-id=...` which is not a valid URL.

It would be great if there was a way to pass request arguments to these functions so that they automatically add it to the URL in a correct way.

**Comment by kevinsa5** [comment]
I ran into this wall also.  My use-case is having flask call `autoload_server`, and I wanted it to simply forward any request parameters through to bokeh.  It then used the return `script` variable as an input to a flask template.  Here is my workaround, if you simply must be able to do this before the feature is added: 

```
@app.route('/amped')
def amped():
    script = autoload_server(model = None, app_path="/amped")
    # this is pretty hacky -- flask can't pass its GET request parameters directly, so we have to do it this way
    # `script` is a string that looks like this (the first character is a newline):
    """
<script
    src="http://localhost:5006/amped/autoload.js?bokeh-autoload-element=6b813263-05df-45a5-bd91-e25c5e53c020"
    id="6b813263-05df-45a5-bd91-e25c5e53c020"
    data-bokeh-model-id=""
    data-bokeh-doc-id=""
></script>
"""
    # so to add on the necessary parameters, we have to insert them manually.  hopefully we won't need to urlencode anything.
    # note that request.args = a MultiDict, so be careful of duplicate params
    # http://werkzeug.pocoo.org/docs/0.11/datastructures/#werkzeug.datastructures.MultiDict
    
    script_list = script.split("\n")
    script_list[2] = script_list[2][:-1]
    for key in request.args:
        script_list[2] = script_list[2] + "&{}={}".format(key, request.args[key])
    script_list[2] = script_list[2] + '"'
    script = "\n".join(script_list)
    return render_template("amped.html", script = script)
```
This goes in and manually edits the script tag returned by `autoload_server`.  It doesn't url-encode any of the request arguments, so beware!  In my specific case, this is acceptable, but in general it may not be.  Hopefully this is useful to other people with this problem.

**Comment by kevinsa5** [comment]
I've looked at the source code for `autoload_server` and it seems like this can be implemented quite easily, at least for GET request parameters.  Just allowing an optional argument of a list of (key, value) tuples and then having something like this near the bottom of the function:

```
for key, value in request_parameters:
    src_path = src_path + "&{}={}".format(key, value)
```
would be most of the additions.  URL-encoding the keys and values would be good too.  I would be happy to do the work for this, but I have no experience with contributing to other people's repos on github.  If someone could point me to an explanation of the process of making a PR, adding code tests, documentation, etc, I'd love to contribute this to Bokeh!

**Comment by jxramos** [comment]
Nice moves @kevinsa5 , I see what you're doing, modifying the src url tucked into the script tag's string. I too would like to see the source updated on autoload_server to permit pushing parameters down into the Bokeh documents.

**Comment by bryevdv** [comment]
Too late for `0.12.6` but I have scheduled for the following milestone.
