### ISSUE TITLE
Renderers argument is getting over-ridden on BoxSelectTool

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#5994]
Python version      :  3.5.3 
Bokeh version       :  0.12.4 (bug also in current master)

The renderers kwarg in BoxSelectTool seems to be getting over-ridden. So even if only a subset of the available renderers is specified, all renderers are used instead. To reproduce:

change https://github.com/bokeh/bokeh/blob/master/examples/models/file/data_tables.py#L59 
to `select_tool = BoxSelectTool(renderers=[cty], dimensions='width')`

When plot renders, the box select tool should only select the blue points, but instead, it selects both.

**Comment by bryevdv** [comment]
This is actually because both glyphs share a data source, and selections on data sources propagate to all glyphs that use that source by design (linked brushing). To have independent selections, separate data sources would be needed.
