### ISSUE TITLE
Flask Embed Example Needs Template?

### ISSUE THREAD

**Issue by cogerk** [bokeh/bokeh#5996]
When trying to run the flask_embed example (copy/pasted code into a file in my application directory), I need an embed.html template.  Easy enough for me to add this .html file myself, but what if a templates directory was already available for this example?

Location of example I used:
https://github.com/bokeh/bokeh/blob/0.12.4/examples/howto/server_embed/flask_embed.py

Screenshot of error:
![screen shot 2017-03-15 at 11 54 17 am](https://cloud.githubusercontent.com/assets/9560816/23965738/3312db58-0976-11e7-9f80-668d46760161.png)

**Comment by bryevdv** [comment]
This file does already exist in current master:

https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/templates/embed.html

If you've moved/copied the example you'll need to copy that templates directory too, or supply your own, or update the example to load something different or have a template inline in the code.
