### ISSUE TITLE
Button layout and label valign 

### ISSUE THREAD

**Issue by ttal** [bokeh/bokeh#6001]
The button widget layout seems to be off when multiple buttons are placed close to one another (small value for height), causing the clickable area to potentially be shifted from the text itself.  This may be just a text alignment issue, not sure.
 
For example, if a few buttons are placed in a column with height=5, the text itself is not actually clickable (easier to see when it's a "link" button):
```
buttons = [Button(label='button', button_type="link", height=5) for i in range(5)]
layout = column(children=[i for i in buttons])
curdoc().add_root(layout)

````

**Comment by bryevdv** [comment]
@ttal please provide a *complete* minimal test case to reproduce the issue, as requested in the issue template. In cases such as this, a screenshot is also immensely helpful.

**Comment by ttal** [comment]
@bryevdv this is actually complete (modulus imports).  Should run in serve mode:
```
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models.widgets import Button

buttons = [Button(label='button2', button_type="link", height=5) for i in range(5)]
layout = column(children=[i for i in buttons])
curdoc().add_root(layout)
```
The screenshots do a better job explaining what I mean - the first shot shows that even though the cursor is on the link, the link is not highlighted (the clickable area is shifted up).  The second shot shows the cursor well above the link, which is highlighted.

![screenshot2](https://cloud.githubusercontent.com/assets/4337021/24065490/b2c7b248-0b28-11e7-8ac6-1842588830ab.jpg)
![screenshot1](https://cloud.githubusercontent.com/assets/4337021/24065487/aea531f4-0b28-11e7-835b-95a64c73842b.jpg)

**Comment by bryevdv** [comment]
I'm honestly not sure when `"link"` was a valid button type. I am not sure it ever was *intentionally*. In any case it's definitely not now:
```
ValueError: invalid value: 'link'; allowed values are default, primary, success, warning or danger
```
So, closing.
