### ISSUE TITLE
Toolbar tooltips are blank in examples/app/crossfilter

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#6006]
<img width="243" alt="screen shot 2017-03-17 at 12 26 39 pm" src="https://cloud.githubusercontent.com/assets/1417520/24055214/30e7be82-0b0d-11e7-87a0-163d6488d3b9.png">

![untitled](https://cloud.githubusercontent.com/assets/1417520/24055253/5be068d2-0b0d-11e7-9e9d-d2e510502dc5.png)

**Comment by mattpap** [comment]
@Maggie-M, are you sure this is on top of most recent `master`? For me, the example looks completely different and doesn't even show toolbar (`toolbar_location=None`). With toolbar enabled tooltips display as expected.

**Comment by bryevdv** [comment]
@mattpap it's the crossfilter app, I've updated the title
