### ISSUE TITLE
 Dashed line turns solid when zoomed in

### ISSUE THREAD

**Issue by SiltSmart** [bokeh/bokeh#6007]
Hi,

I'm plotting a time series of two lines, one is solid, one dashed. As the time series is long I have to zoom in quiet a bit to see details. I would expect the line to keep their line style, but from a certain zoom level the dashed line turns solid and the two lines and not distinguishable.

The first screenshot below shows the two lines at a y-axis range from 0 to 40. Both appear as defined, one solid, one dashed. For the second screenshot I zoomed in to a y-axis range of 0 to 35 and both lines appear solid.
![zoom_40](https://cloud.githubusercontent.com/assets/25102804/24056366/bff7e550-0b19-11e7-988f-6b55813e8453.JPG)
![zoom_35](https://cloud.githubusercontent.com/assets/25102804/24056375/c763348e-0b19-11e7-9cd1-b5d0d0ee9999.JPG)

Here is a short example that reproduces the bug. At start-up the line is dashed, as defined. When you zoom in to a axis range of e.g. 0.1 to 0.1001 (just click the buttons) the line turns solid. If you then zoom out to a range of 0.1 to 0.1002 it becomes dashed again.

I noticed that this effect depends on the line width and the dash/whitespace length. E.g. when I change the line_dash to [1,10], the line turn solid at 0.1 to 0.1002, instead of 0.1 to 0.1001.

```
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Button, TextInput
from bokeh.layouts import layout, column
from bokeh.plotting import figure

def update_x():
    f.x_range.start = float(text_x_min.value)
    f.x_range.end = float(text_x_max.value)
def update_y():
    f.y_range.start = float(text_y_min.value)
    f.y_range.end = float(text_y_max.value)

x = [0.1,2,3]
y = [0.1,2,3]

source = ColumnDataSource({'x':x,'y':y})

f = figure()

line = f.line(x='x', y='y', source=source, line_dash=[2,10], line_width=1)

text_x_min = TextInput(value=".1", title="Min. x Axis:")
text_x_max = TextInput(value=".1001", title="Max. x Axis:")
button_x = Button(label='Set x Axis')
button_x.on_click(update_x)
text_y_min = TextInput(value=".1", title="Min. y Axis:")
text_y_max = TextInput(value=".1001", title="Max. y Axis:")
button_y = Button(label='Set y Axis')
button_y.on_click(update_y)

lay_out = layout([[column(f, text_x_min, text_x_max, button_x, text_y_min, text_y_max, button_y)]])

curdoc().add_root(lay_out)
```

Here are the software version info:

Bokeh version 0.12.4
Python 3.5.2 :: Anaconda 4.3.0 (64-bit)
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Original Install Date:     9/6/2016, 4:37:41 PM
System Boot Time:          3/15/2017, 5:22:23 PM
System Manufacturer:       ASUSTeK COMPUTER INC.
System Model:              X555LAB
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 61 Stepping 4 GenuineIntel ~2397 Mhz
BIOS Version:              American Megatrends Inc. X555LAB.600, 1/5/2016
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     8,093 MB
Available Physical Memory: 3,691 MB
Virtual Memory: Max Size:  9,373 MB
Virtual Memory: Available: 3,199 MB
Virtual Memory: In Use:    6,174 MB
Browser: Google Chrome Version 57.0.2987.110 (64-bit)

**Comment by bryevdv** [comment]
I can confirm this occurs on Chrome 57.0.2987.98 (64-bit) and FF 52.0 (64-bit) on OSX, but does *NOT* happen on Safari.  Unfortunately if this is due to some browser limitation that may be nothing much that can be done except for wait for browsers to catch up (we have zero control or input over browser capabilities). But it's possible there is some workaround or different usage that could help. We will have to investigate some time after the next release. 

In the mean time my only suggestion for a workaround is to use a different retinal variable to distinguish the lines (e.g. color or thickness)

**Comment by SiltSmart** [comment]
Interesting. Another possible workaround could be to change the line_dash parameter dynamically, depending on level of zoom.

**Comment by bryevdv** [comment]
This is still an issue in Chrome  61.0.3163.100 and FF 57.0b6

Zooming in on FF, this definitely seems to be a browser rendering issue:

<img width="106" alt="screen shot 2017-10-12 at 19 28 19" src="https://user-images.githubusercontent.com/1078448/31525105-949654a0-af83-11e7-8a34-da627db5611c.png">

I don't thing there is anything we can do about this, unfortunately. I can only reiterate the suggestion to use different retinal variables such as color or weight if zooming over wide scales is required, or to set zoom min ranges if not and dashing is desired.
