### ISSUE TITLE
Bokeh Hovertool shows ???? when not on a circle glyph, but I want it to disappear

### ISSUE THREAD

**Issue by doctor-cool** [bokeh/bokeh#6009]
I am currently using a hovertool on one of my plots and whenever I hover over a circle glyph it shows the data that I want to see about the point in question. Whenever I take my cursor off the glyph, however, the hovertool shows me ????. Is it possible to have the hovertool information disappear when the cursor is NOT over any point (circle glyph)?

**Comment by bryevdv** [comment]
Hi, 

as stated in the GH issue template, we reserve the GH issue tracker for bug reports, feature requests, and dev-related discussion *only*. All usage or general support questions should go to the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
