### ISSUE TITLE
Add support for click events on categorical axes

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#601]
This should be supported on client and server side. As an example consider two plots where one has years on an axis and clicking that year updates another plot with data from only that year. Obviously this can be solved with widgets, but the behavior proposed here can be more intuitive for users, at least in some contexts.

*(deleted unrelated discussion about categorical zooming below)*

**Comment by jiss2891** [comment]
This is still wanted?

**Comment by mattpap** [comment]
This is currently being worked on (in a broader setting) (scheduled for 2.3 release).

**Comment by bryevdv** [comment]
@mattpap is there any current work open regarding this? If not I intend to self-assign to work on the near future. I would generalize this to a generic axis click event that reports any click location, numeric or categorical.

**Comment by mattpap** [comment]
There is none.
