### ISSUE TITLE
Add object integrity validation

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#602]
For example, currently when one uses a `CategoricalAxis`, but by mistake uses non-`FactorRange` together with it, then he will get a bogus error message in JS ("undefined has no property length", or similar). The same goes for referencing non-existent fields in glyphs, forgetting to specify required object references (when the default is `None`, which is often wrong in itself), etc.

**Comment by bryevdv** [comment]
@mattpap do you think our currently built out validation machinery covers this issue?

**Comment by mattpap** [comment]
@bryevdv, not at all. We don't have any object **integrity** validation.

**Comment by bryevdv** [comment]
I am going to add as many basic sanity checks as I can for 0.9.1:
* unequal column data source lengths
* references to column names that don't exist
* no renderers
* no glyph renderers
* missing ranges
* bad range types for axes

I figure these checks should happen at the start of/before serialization. I was going to make a function for each check, associate with a specific numbered error or warning, e.g.:
```
W1003 : plot [xyz] has no renderers
```
or 
```
E1005 : Column lengths in data source [abc] are not all the same
```
all warnings and errors will be logged, and if there are any errors, and exception all also be raised. Plus add a `BOKEH_STRICT` env var to raise exceptions on warnings too. 

@bokeh/dev  thoughts on this plan?

**Comment by bryevdv** [comment]
As motivation, see e.g. #2393

**Comment by bryevdv** [comment]
Just to clarify, some machinery to support validation has been added and some checks as well. But we should continue to add even more integrity and validation checks.

**Comment by damianavila** [comment]
Yep, we should add a new issue for that... done here: #2480
