### ISSUE TITLE
Problem with Bokeh Tools.

### ISSUE THREAD

**Issue by RamonGuixa** [bokeh/bokeh#6029]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

**Comment by bryevdv** [comment]
@RamonGuixa I think there was a problem with your issue submission, there is no content above.

**Comment by RamonGuixa** [comment]
I have last version of Bokeh and Python 3
With low quantity of data, Bokeh Tools work well, but with high quantity of data: pan , resize and wheelzoom colapses the htlm image.
With around two year ago version was all working correctly.
I can send two examples with extension htlm to show the problem, but  they are not supported here.
Please tell me how can I send this files.
Ramón

**Comment by bryevdv** [comment]
@RamonGuixa the best thing to provide would be a minimal script to reproduce the problem, which you could simply include here, or in a separate gist. (https://gist.github.com)

**Comment by RamonGuixa** [comment]
I do not know how to reduce to minimal script.
The script reads finatial data on excel sheet, creates a pandas dataframe and some columns of this data frame are plotted with axis x as datetime and the other columns as finantial candels o,h,l,c plus many lines and dots and asterisks.
The issue is that the script has failed with the updating of bokeh.
If I have a dataframe of 1 year dates it is working correctly, but if I expand to 17 years appears the issue

**Comment by bryevdv** [comment]
It's probably not going to be possible to investigate this without some code to reproduce. Can you clarify exactly what data sizes you are talking about?

**Comment by RamonGuixa** [comment]
Attached the script.
[Velas.txt](https://github.com/bokeh/bokeh/files/858399/Velas.txt)

**Comment by RamonGuixa** [comment]
14 * 4312 is dataframe dimensions

**Comment by RamonGuixa** [comment]
If I reduce to 14*250, Every things is correct.

**Comment by RamonGuixa** [comment]
If you give me some email address I can attach the two html files that clarifies issue a lot

**Comment by bryevdv** [comment]
Can you just attach put them in a gist? 

FYI we are in the middle of a release this week, then I am gone for two weeks. So if you have a pressing  need, my best advice is to simply not update for now. 

FWIW I tried this script with 60k circles:
```
import numpy as np

from bokeh.plotting import figure, show, output_file

N = 60000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 0.5
colors = [
    "#%02x%02x%02x" % (int(r), int(g), 150) for r, g in zip(50+2*x, 30+2*y)
]

TOOLS="pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"

p = figure(tools=TOOLS)

p.circle(x, y, radius=radii,
          fill_color=colors, fill_alpha=0.6,
          line_color=None)

output_file("color_scatter.html", title="color_scatter.py example")

show(p)  # open a browser
```
and it works fine. However and OHLC chart will have more than one glyph, it may simply be outside Bokeh's capability.

**Comment by RamonGuixa** [comment]
Thanks. I can manage the issue. It is most tedious to avoid the use of pan and wheel tool.

**Comment by bryevdv** [comment]
OK, if you need help with displaying larger data sets, DataShader may be of some use

https://github.com/bokeh/datashader
