### ISSUE TITLE
BoxZoomTool and BoxSelectTool doesn't clear the overlay when end event is off the plot frame

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6030]
v bokeh 0.12.5dev16
python3
Chrome 57

BoxZoomTool and BoxSelectTool doesn't clear the overlay when end event is off the plot frame

<img width="1036" alt="screen shot 2017-03-21 at 12 26 57 pm" src="https://cloud.githubusercontent.com/assets/2198981/24155129/b59def9e-0e31-11e7-9eba-4053328b04d7.png">

<img width="633" alt="screen shot 2017-03-21 at 12 26 50 pm" src="https://cloud.githubusercontent.com/assets/2198981/24155134/bc70567c-0e31-11e7-895c-60a0d9962386.png">

**Comment by mattpap** [comment]
Looks like a side effect of PR #5349.

**Comment by mattpap** [comment]
btw. The other image is a nice gem.

**Comment by bryevdv** [comment]
> btw. The other image is a nice gem.

That's a missing google API key, not in our control.

**Comment by mattpap** [comment]
> That's a missing google API key, not in our control.

I know and it's not the point. What I meant is "Oops! Something went wrong" text below a failing component. Nice coincidence.

**Comment by mattpap** [comment]
The reason for failure is pretty obvious, but I'm not sure how to fix this. WIP.
