### ISSUE TITLE
NA values correctly skipped in linear scale but not in log scale

### ISSUE THREAD

**Issue by zebulon2** [bokeh/bokeh#6035]
Hi,

I have an issue with plotting "NA" values (as imported with a CSV reader on R) as lines when using a log scale. Here is the code example in a Jupyter notebook:
```
from bokeh.plotting import figure, show, output_notebook
import numpy as np

# prepare some data
x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0.01, 0.03, 0.1, 'NA', 1, 3, 10, 30]
#chartData = {"x": x, "y": y}

# output to Jupyter notebook
output_notebook()

# create a plot
p = figure(plot_width=600, plot_height=400,
          )

p.line(x, y, line_width=2)
# show the results
show(p)
```
![bokeh_plot_na_linear](https://cloud.githubusercontent.com/assets/1568591/24194686/ebeb77f2-0eee-11e7-85ca-66777bc82a73.png)

The 'NA' value is correctly skipped and shows as a break in the line.

Now if I plot the same data but using a log scale for the Y axis:

```
# create a plot
p2 = figure(plot_width=300, plot_height=250,
y_axis_type="log",
          )

p2.line(x, y, line_width=2)
# show the results
show(p2)
```
![bokeh_plot_na_log](https://cloud.githubusercontent.com/assets/1568591/24194696/f17de862-0eee-11e7-969c-6b96f8a194da.png)

As you can see, the 'NA' value is arbitrarily plotted at the level of the X axis (whatever the Y axis range I can specify). It also happens when using numpy.nan instead of 'NA'.

Am I doing anything wrong? Is this a bug, and is there a workaround, other than removing the 'NA' data (which is a pain for large matrices and multiple line plots, where the 'NA' are not always consistently sampled in series)? Thanks in advance.

**Comment by bryevdv** [comment]
Seems like a bug. I'm not aware of any workarounds offhand except either to segment the data by hand or possibly pre-transform the data to a log scale yourself

**Comment by zebulon2** [comment]
Thanks bryevdv. I wish I could help but am unfamiliar with Bokeh source code. Any pointers of where to look?

**Comment by bryevdv** [comment]
@zebulon2 sorry I was maybe unclear, those suggestions were for actions you could take as a user (in your code) to possibly work around the bug until it is fixed.

Though if you are interested in possibly working on a fix in Bokeh itself, and asking about where to get started, I'm happy to advise and answer questions to help you get started (just let me know)

**Comment by zebulon2** [comment]
I really meant I would like to help fix this issue in Bokeh code, but am unsure I have the skills for it. If you can advise where to look it would be great. There must be some code that is responsible for the gaps in the line, which is not used (or working properly) when the axis is switched to log scale.

I also tried plotting with a 0 in the y data series. I get the same issue in log scale, suggesting there may be a simple fix for 0/NA/None value in the code, but it is not appropriate. I am more than happy to look but cannot do any promise :)

**Comment by bryevdv** [comment]
I think the problem is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/mappers/log_mapper.coffee#L41-L42

For some reason the log mapper is explicitly mapping non-finite values to 0. So a quick fix would be to change that behavior. But testing will require building and running a local BokehJS. There's some more info at 

http://bokeh.pydata.org/en/dev/docs/dev_guide.html

about getting set up and building locally. I'd say take a look at that and let me know what other questions I can answer.

**Comment by zebulon2** [comment]
Thanks a lot, I will see what I can do. Just two comments:

1. What I am curious about is why the gap works fine in linear scale: is there some code that leads to skipping the data before plotting? And therefore, is it a problem with the order in applying the data reading and the log mapper? If the log mapper is replacing NaN with 0s, and then the data reading is done, then it would not skip that point. Would it be possible to reverse the processes here?

1. I just noticed the problem also occurs with negative values. If I use:
```
y = [0.01, 0.03, -1, 0.3, 1, 3, 10, 30]
```
then the plot looks like this:
![bokeh_plot](https://cloud.githubusercontent.com/assets/1568591/24203618/2a60bdd4-0f0e-11e7-8647-0636a81dbb5d.png)
Hence, there may be another piece of code that also treats negative numbers as 0?

**Comment by zebulon2** [comment]
I was browing past issues and found this: https://github.com/bokeh/bokeh/issues/2162
Apparently this is the same issue, fixed for points but not for lines. The screenshots in the last post look to have the same issue than the one I reported. In this thread and the code they mention two hotfixes for it: https://github.com/bokeh/bokeh/pull/5477 and https://github.com/bokeh/bokeh/pull/5561. Could these be the ones to fix?

**Comment by bryevdv** [comment]
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/mappers/log_mapper.coffee#L39-L42

The line above calls `Math.log` to produce `value` so any non-positive starting value will be non-finite. That would explain all the behavior described in this issue. 

Regarding linear vs log, the linear mapper (presumably) preserves non-finite values when mapping from "data space" to "screen space". Then when actually rendering, the line `_render` (which uses already mapped data) interprets non-finite screen coordinates as a gap:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/line.coffee#L6-L25

**Comment by zebulon2** [comment]
OK. I am not a coffee developer, but can understand the intent of the code here. The gap i caused by the
``drawing = false`` statement if I understand well. Am I correct? So why in log scale the ``if !isFinite(sx[i]+sy[i]) and drawing`` statement on line https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/line.coffee#L11 not true? This "trick" of not drawing would be acceptable as well in log scale, no?

**Comment by bryevdv** [comment]
Those issues were different. One was about axis rendering and the other was about a but that propagated non-finite values in a buggy and unintended way (causing finite values to mis-render)

**Comment by zebulon2** [comment]
OK, sorry for intersperse the issues. So the question is why the https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/line.coffee#L6-L25 tests responsible for stopping drawing behave differently for linear and log scales?

**Comment by zebulon2** [comment]
One thing I try to understand: why is it necessary to replace a NaN or infinite value with 0 aith
if https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/mappers/log_mapper.coffee#L39-L42? Why not returning the NaN that would be caught by https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/line.coffee#L6-L25? Am I right to think this is the problem? The log mapper replaces NaN with 0, and then the line code is applied, but since it finds a 0, it draws it?

**Comment by zebulon2** [comment]
What about this fix in place of https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/mappers/log_mapper.coffee#L38-L49:
```
      for i in [0...xs.length]
        value = (Math.log(xs[i]) - inter_offset) / inter_scale

        if not isNaN(value) and isFinite(value)
          result[i] = value*scale + offset
        else
          result[i] = value
return result
```

Here we keep the NaN/infinite but scale directly if value is positive. I suppose the replacement with a 0 was used for the loop in https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/mappers/log_mapper.coffee#L46-47.

**Comment by bryevdv** [comment]
> The gap i caused by the drawing = false statement if I understand well. Am I correct? 

Exactly, that is correct

> The log mapper replaces NaN with 0, and then the line code is applied, but since it finds a 0, it draws it?

Yes I believe that's the crux of the problem.

Your above solution might work, it might also work to just not do the test for non-finite at all in the original code (just always use `value` as-is. If you can build locally (and run examples with the env var
`BOKEH_RESOURCES=inline` set) then you can see if either or both solves the immediate problem. 

Then the question would be to make sure there is not something else depending on the weird "turn nan's to zero" behavior

**Comment by zebulon2** [comment]
> Your above solution might work, it might also work to just not do the test for non-finite at all in the original code (just always use value as-is.)
I initially thought that it needed to replace NaN with 0 not to fail the transform ``value*scale + offset``. But maybe that calculation works fine with NaNs?

> Then the question would be to make sure there is not something else depending on the weird "turn nan's to zero" behavior
Sure, but anyway this should be corrected. One cannot replace NaN with an arbitrary value, this is recipe for further trouble.

**Comment by bryevdv** [comment]
> I initially thought that it needed to replace NaN with 0 not to fail the transform value*scale + offset. But maybe that calculation works fine with NaNs?

Well, `NaN` values should be propagated, per IEEE 754, so if `value` is `NaN`, I'd expect `value*scale + offset` to also be `NaN`. 

> Sure, but anyway this should be corrected. One cannot replace NaN with an arbitrary value, this is recipe for further trouble.

I definitely agree.

**Comment by zebulon2** [comment]
Hi, I have tested my patch and it works. I have also commented out https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/mappers/log_mapper.coffee#L24-L25 which look to have the same purpose but for single values instead of vectors.

Note that the crucial part of test is not isNaN, but isFinite: when using 'NA' as a value, it tests positive only to the not isFinite test. Probably it divides by 0.

I tried the BokehJS tests and got 4 failures linked to the changes. It expects -Infinity to be equal to 10 or 0 depending on the test, and Infinity to be equal to 100. This is with ColorBar._tick_coordinates method and Range1d ranges vector map. Now I was wondering: is the test correct? Or does it pass under the assumption that Nan and Infinites are equal to some values?

**Comment by bryevdv** [comment]
@zebulon2 Awesome! I'm not sure offhand about the tests, I think the next best step would now be to make a PR with the proposed changes. It will be easier for me and others to see the test failures on our automated CI machinery. Then we can discuss whether the tests or something else needs to change in the PR itself.

**Comment by zebulon2** [comment]
Sure. I have done a fork already and will submit a PR soon.
