### ISSUE TITLE
Support *args and **kwargs in add_next_tick_callback

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#6041]
This is a minor inconvenience, but it would be nice for `curdoc().add_next_tick_callback` to support `*args` and `**kwargs`

    doc.add_next_tick_callback(func, *args, **kwargs)

Currently the solution is to wrap these in a lambda:

    doc.add_next_tick_callback(lambda: func(*args, **kwargs))

This is low priority, I just thought I'd report it.  This is also what Tornado does:

```python
In [1]: from tornado.ioloop import IOLoop

In [2]: IOLoop.add_callback?
Signature: IOLoop.add_callback(self, callback, *args, **kwargs)
Docstring:
Calls the given callback on the next I/O loop iteration.

It is safe to call this method from any thread at any time,
except from a signal handler.  Note that this is the **only**
method in `IOLoop` that makes this thread-safety guarantee; all
other interaction with the `IOLoop` must be done from that
`IOLoop`'s thread.  `add_callback()` may be used to transfer
control from other threads to the `IOLoop`'s thread.

To add a callback from a signal handler, see
`add_callback_from_signal`.
File:      ~/Software/anaconda/lib/python3.6/site-packages/tornado/ioloop.py
Type:      function
```

**Comment by bryevdv** [comment]
Would still like to do but bumping to a later milestone.

**Comment by bryevdv** [comment]
OK, There has not been further interest expressed in this, and, given the unexpectedly deep rabbit hole this went down last time I tried to implement it, I am going to close this issue with no action.

**Comment by bryevdv** [comment]
@bokeh/dev FYI I added a `reso: noaction` label. This is roughly analogous to `reso: wontfix`, except for feature requests.
