### ISSUE TITLE
middle and bottom plot won't pan in y-dimension in custom/gears/gears.py demo on FireFox

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6051]
OSX
Firefox 52
Bokeh 0.12.5rc1

Middle and bottom plot won't pan in y-dimension in custom/gears/gears.py demo on FireFox

**Comment by bryevdv** [comment]
Can confirm. Bizarre.

**Comment by jsignell** [comment]
Also zoom does not affect y location.
<img width="464" alt="screen shot 2017-03-23 at 12 54 49 pm" src="https://cloud.githubusercontent.com/assets/4806877/24259662/eaff89e4-0fc7-11e7-908c-9cc09495cb4b.png">

**Comment by mattpap** [comment]
@bryevdv, also box zoom overlay is offset from cursor position (in the last plot it's not visible at all, but we can assume it's just offset off canvas).

**Comment by mattpap** [comment]
It's likely that `UIEvents._bokify_*()` compute `sx` and `sy` improperly in FF.
