### ISSUE TITLE
Toolbar icons can be highlighted/selected on Safari

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6052]
OSX
Safari 10.10.3
Bokeh 0.12.5rc1

Toolbar icons can be highlighted/selected on Safari. I was just able to select over the whole icon, but now I'm only able to select between them for a screenshot.

<img width="70" alt="screen shot 2017-03-23 at 12 39 24 pm" src="https://cloud.githubusercontent.com/assets/2198981/24256003/cd889128-0fc5-11e7-8632-7c9f1846d5c1.png">

**Comment by bryevdv** [comment]
dupe of https://github.com/bokeh/bokeh/issues/4295 ?

**Comment by canavandl** [comment]
Similar. My issue is related to the toolbar icons while #4295 seems related to the canvas.

**Comment by bryevdv** [comment]
It was inspired by the canvas behavior but I think `user-select` ought to be disabled everywhere. I'm OK either way though, if you prefer a separate issue (just needs tags then)

**Comment by canavandl** [comment]
I was being unclear. I'll comment on #4295 and close this, I was just trying to be clear how it was different.

**Comment by canavandl** [comment]
closed as dupe of #4295
