### ISSUE TITLE
Issues with examples/plotting/server/animated.py

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#6054]
bokeh 0.12.5rc1
osx
Chrome | Firefox | Safari
![out](https://cloud.githubusercontent.com/assets/4806877/24259201/96ef7414-0fc6-11e7-907a-0a346c038901.gif)

 - missing glyph in Chrome and FF
 - color doesn't match across browsers
 - FF animation is jerky
 - screen size of figures is different in different browsers

**Comment by bryevdv** [comment]
some comments:

* The update rate is pushing things a bit. It could probably be reduced to 50-60 hz instead. 
* the different screen size maybe safari/OSX scaling? i.e. I can `apple +` and `apple -` to make canvas's bigger or smaller in safari, but the "scaled" number of pixels is always correct 
* not sure I see a color difference?
* the missing glyph is weird, that should be run down

**Comment by jsignell** [comment]
> not sure I see a color difference?

there is a yellow column in safari that shows as green in the other two.

**Comment by mattpap** [comment]
You can also see that at x=0 and y in [5, 10] there is an invisible bar. I'm pretty sure that the behavior shown in Safari is the correct one.

**Comment by mattpap** [comment]
I can reproduce this in Chrome 57 on Linux.
