### ISSUE TITLE
pandas, sort_values not working properly

### ISSUE THREAD

**Issue by LuckyGem** [bokeh/bokeh#6060]
hi, I was trying to create three columns with sorted value of total_month, total_week and total_hours.
month  week hours
1             1         1
2             2        2
3             3        3
but when I try to create three different columns with ascending order, only the month works. The order for week and hours are pretty arbitrary and I have no idea what is going on.
newDF=df.sort_values(by=[duration],inplace=False,ascending=True)
df[sortedX]=newDF[duration]

Thank you

**Comment by bryevdv** [comment]
Hi, this is the issue tracker for the Bokeh project. However, your question seems to concern the Pandas library, which is a different project. You may have more luck on the Pandas project issue tracker:

https://github.com/pandas-dev/pandas/issues
