### ISSUE TITLE
remove the hover menu item, and keep the hover function working

### ISSUE THREAD

**Issue by Danny-Hazelcast** [bokeh/bokeh#6064]
Feature request.

I would like to remove the hover menu item, and keep the hover function working

**Comment by bryevdv** [comment]
@mattpap could this be implemented quickly for `0.12.5` ? This would open a viable workaround for users that have many hovertools until we can implement the "combined" menu item

**Comment by bryevdv** [comment]
Tentatively adding to `0.12.5` in case it is feasible

**Comment by pecey** [comment]
Is there a way to achieve the same in BokehJS?
