### ISSUE TITLE
Touch events fail in device mode under chrome devtools

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6065]
The following code in `core/ui_events.coffee`:
```
_bokify_hammer: (e, extras={}) ->
    if e.pointerType == 'mouse'
      x = e.srcEvent.pageX
      y = e.srcEvent.pageY
    else
      x = e.pointers[0].pageX
      y = e.pointers[0].pageY
```
fails with "can't read property pageX of undefind". `e.pointers` is empty. However, `e.changedPointers` isn't and contains valid coordinates. Just to note, `e.srcEvent.{pageX,pageY}` are valid as well. I'm not sure if this is a bug in hammer or we use hammer improperly.

@bryevdv, do you know why this code is written like this?

**Comment by bryevdv** [comment]
Not sure. Another possibility is that perhaps it's something that changed between hammer versions. Current docs say this:

<img width="595" alt="screen shot 2017-03-24 at 13 21 34" src="https://cloud.githubusercontent.com/assets/1078448/24308136/e1c276de-1094-11e7-85cb-c144c58f3069.png">

I'm not sure if `changedPointers` should always be used, or be used as a fallback.

**Comment by mattpap** [comment]
@bryevdv, yeah, this documentation isn't much helpful. Additionally, why 'mouse' is handled differently?

**Comment by mattpap** [comment]
OK, I why. It's because `pointers` is empty in this case as well. I will go ahead and use `changedPointers` in all scenarios.

**Comment by mattpap** [comment]
Also, it would be nice to check if we deal with multi-point touch events properly, e.g. pinch (I presume we).

**Comment by mattpap** [comment]
It's possible to remote debug a phone or a tablet from chrome devtools. I didn't try it yet, but what's in documentation looks very promising.

**Comment by jmodica1** [comment]
Hi - has there been any additional knowledge gained on this topic? I run into this issue myself and would be interested in any fix, hack, etc.

Thanks!
