### ISSUE TITLE
dirty flag

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#607]
we should we either remove the concept of dirty and just send everything to the server,or we should fix dirtyness (can we?)  or is there another API around this that makes sense?

**Comment by damianavila** [comment]
@hhuuggoo, can you add a brief explanation about why are you closing the issue... it would be nice to have it from an educational/informative point of view... essentially for the new contributors we are having now...

**Comment by hhuuggoo** [comment]
Yea I just closed it because I opened it and it was old and I don't think we are going to worry about it right now
