### ISSUE TITLE
general feature request: accept tuples in addition to lists as input

### ISSUE THREAD

**Issue by tommycarstensen** [bokeh/bokeh#6072]
I was doing a pie chart. This example with a colour tuple fails (the plot is generated, but the colours are the default ones):

    p = Donut(dataseries, color=('violet', 'green', 'orange', 'yellow', 'red', 'blue'))

Whereas it works with lists:

    p = Donut(dataseries, color=['violet', 'green', 'orange', 'yellow', 'red', 'blue'])

The documentation does say `color` has to be a string or a list, but perhaps worth raising an error then, if a tuple is passed? Preferably tuples should also work. And of course it would be even greater, if I could pass a dictionary corresponding to my dataseries.

I had some other function, which didn't accept tuples. It's a wee bit annoying.

Thank you for a great module/tool!

**Comment by bryevdv** [comment]
This was evidently overlooked earlier, when `bokeh.charts` was deprecated and removed, all issues should have also removed.
