### ISSUE TITLE
Rectangles misaligned in 0.12.5-dev

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#6073]
One of my plots sometimes misbehaves in 0.12.5-dev when it behaves fine in 0.12.4.  I apologize that I don't have a reproducible case. 

I have a plot where I create rectangles with various integer x-values and widths of that x value divided by two.  This *should* make it so that the left boundary of the rectangle is always at zero.  This usually works, but sometimes the rectangles jump a bit to the right.  This is in a server application where these values are frequently updated.  I've attached an image of a failure below.  I apologize that I don't have more information.  My hope is that this reminds someone of a recent change that might result in such behavior.

![bad-workers-2](https://cloud.githubusercontent.com/assets/306380/24332161/b3d231e8-120f-11e7-877f-7f7096487cac.png)

**Comment by bryevdv** [comment]
Not offhand. I would be helpful to try and confirm that the values set in python are all in fact always 0, perhaps an assert?

**Comment by bryevdv** [comment]
Closing, without an MRE we can't do much for something like this.
