### ISSUE TITLE
Axes with Bytes ticks chooses odd values

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#6074]
The tick values chosen when using a Byte-valued numeric tick formatter don't correspond to round numbers:

![image](https://cloud.githubusercontent.com/assets/306380/24333609/1ed9e828-1229-11e7-833a-18d94bec8279.png)

I suspect that there are internal reasons for this, but thought I'd report.

Bokeh version 0.12.4, Python 3.5, Ubuntu 16.04

**Comment by bryevdv** [comment]
@mrocklin can you please provide a minimal test case?

**Comment by canavandl** [comment]
I'm going to mark closed as referred. The solution is to use: 

```python
plot.xaxis.ticker = AdaptiveTicker(mantissas=[1, 256, 512], base=1024)
```

Please reopen if you think I've closed this incorrectly.

**Comment by mrocklin** [comment]
I just ran into this again, found this issue, and made the proposed change.

Things still work. I think it might be wise to make it a default though, if that is easy.

**Comment by bryevdv** [comment]
@mrocklin Well, formatting with byte approximations is not the common case, and there is definitely not any straightforward way to modulate the default ticker, based on a customized formatter. I think documentation support would be reasonable here
