### ISSUE TITLE
feature request: make CheckboxGroup accept kwarg title

### ISSUE THREAD

**Issue by tommycarstensen** [bokeh/bokeh#6077]
It would be great, if `CheckboxGroup` of `bokeh.models.widgets` could accept the key word argument `title` just like `RangeSlider` and other widgets. Thanks.

**Comment by bryevdv** [comment]
@mattpap does the recent `GroupBox` intersect with this?

**Comment by bryevdv** [comment]
I would consider that method to the appropriate way for users to add a title to a group of checkboxes at this point then.
