### ISSUE TITLE
prefix bug on "Active Bokeh Applications" page

### ISSUE THREAD

**Issue by aguayoff** [bokeh/bokeh#6080]
I use a command like "bokeh serve --prefix=prefix app1.py app2.py" to serve my applications.
If I then access ip_address/prefix I can see a list of my applications running but the link points to ip_address/app1 instead of ip_address/prefix/app1.
I think this can be solved by changing  [bokeh/bokeh/server/views/root_handler.py](https://github.com/bokeh/bokeh/blob/master/bokeh/server/views/root_handler.py), line 32
from
`self.render("app_index.html", items=self.applications.keys())`
to
`self.render("app_index.html", items=[self.prefix+k for k in self.applications.keys()])`

regards.

**Comment by bryevdv** [comment]
@aguayoff would you be interested in submitting a PR for this?
