### ISSUE TITLE
hover tooltips update impossible

### ISSUE THREAD

**Issue by jjouganous** [bokeh/bokeh#6085]
Hello,
I'm currently tring to update a hover tool tooltips on a select widget change, adding fields selected 
by the user via the widget.
I couldn't find any way to do that properly. The only (very bad) solution I came up with is to add a new hover tool on change.
Maybe the tooltips update could be an interesting new feature to include.
I join a minimal example.

Thanks for this great tool! :)

Julien

```python
from bokeh.layouts import widgetbox, layout
from bokeh.models.widgets import MultiSelect
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure

import pandas as pd



df_test = pd.DataFrame({'x':[1, 2, 3, 4], 'height':[2, 3, 4, 5], 'col1':['a', 'b', 'c', 'd'], 'col2':[2, 4, 6, 8], 'col3':['mon', 'tues', 'wed', 'fri']})
df_test['y'] = df_test.height / 2.0

datasource = ColumnDataSource({"x":[], "y":[], "height":[]})

p = figure(width=800, height=500, x_range=datasource.data['x'])
p.rect(x="x", y="y", width=0.8, height="height", source=datasource, color="#2171b5", alpha=0.6)

hover = HoverTool(tooltips=[("x", "@x"), ("y", "@y")])
p.add_tools(hover)

# fields selection
ms = MultiSelect(title="column selection", value=[], options=['col1', 'col2', 'col3'], width=200)

def update(attribute, old, new):
    v = ms.value
    df_plot = df_test[['x', 'y', 'height']+v] # not usefull here but mimics what I do in my full code.
    p.x_range.factors = list(df_plot.x)
    datasource.data = ColumnDataSource.from_df(df_plot)

    # hover tool : my current (bad) solution
    tt = [(x, '@'+x) for x in v]
    p.add_tools(HoverTool(tooltips=[("x", "@x"), ("y", "@y")]+tt))

    # what I'd like to do:
    #hover.tooltips = [("x", "@x"), ("y", "@y")]+tt




ms.on_change('value', update)

# layout
l = layout([[widgetbox(ms), p]])

curdoc().add_root(l)
curdoc().title = "bokeh app"
```

**Comment by mattpap** [comment]
>  `hover.tooltips = [("x", "@x"), ("y", "@y")]+tt`

This should work. I will need to debug this this see what's going on.

**Comment by jjouganous** [comment]
Indeed, I expected this line to work but if I do that, the hover does not display at all.
If it can help, I'm working with Bokeh version 0.12.4 on Google Chrome 56.0.2924.87

**Comment by mattpap** [comment]
The problem is that tooltips are partially treated as a part of plot rendering pipeline and partially as a separate entity. Due to this, only tooltips that were constructed during initial setup of a plot are fully initialized and working. Updating `tooltips` causes new `TooltipView`s to be constructed, but not fully initialized. `bind_bokeh_events` isn't called and `change:data` events are ignored.

**Comment by jjouganous** [comment]
I see. Thank you for your feedback!
Is there a way to temporarily by pass this issue, for instance by deleting the hover before creating a new one (instead of just adding new hover tools on each change as I'm doing currently)?

**Comment by harmbuisman** [comment]
I have the same problem with Bokeh version '1.1.0'. The label part of the tooltip updates, but the value part does not, e.g. for hover.tooltips = [ (value, "@value"),] I get only value to update, not the number behind @value.

When I run in output_notebook() mode in a Jupyter notebook a show(figure) call does trigger the update of the @value as well, so the definition is correct. 

In standalone mode I do not know how to trigger the show, but it does have the same problem.

Could it be that this has regressed (I couldn't get the TS code to work)? Any suggestions how to force the update?

**Comment by bryevdv** [comment]
@harmbuisman at this point please open a new separate issue with e current reproducer
