### ISSUE TITLE
Dynamic Background Colour

### ISSUE THREAD

**Issue by Cosbgn** [bokeh/bokeh#6087]
Is possible in bokeh to change background colour dynamically? 
For example something like this http://jsfiddle.net/rdLw31s6/ (made with highcharts)?

I would like to have the previous month average for example in blue. I don't find any reference to background colour in the user guide. Can anyone point me to the right direction? Thanks

**Comment by bryevdv** [comment]
@Cosbgn In order to keep things manageable, the GitHub tracker is reserved for bug reports and feature requests and dev-related discussion.  For general support and assistance, please use the project mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
