### ISSUE TITLE
Styling reverts to default while panning and zooming

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#6090]
bokeh = 0.12.5rc3
python = 3.6
browser = Chrome, Firefox, Safari

While a plot is zoomed or panned, the lines appear gray rather than retaining their styling. This doesn't occur when the zooming or panning occurs as a result of linking. As shown below when interacting with the plottting/file/vector.py example.

![out](https://cloud.githubusercontent.com/assets/4806877/24569943/d7ff6984-1636-11e7-8668-aebd11d38326.gif)

**Comment by mattpap** [comment]
In the left plot LOD (level of detail) mode is triggered, but that does't propagate to linked plots. There's a recent issue #5937 requesting allowing this.
