### ISSUE TITLE
hover_span.py example is avoiding hover tooltip overlap

### ISSUE THREAD

**Issue by timsnyder** [bokeh/bokeh#6093]
#### software version info
Bokeh: 0.12.5rc3-24-ga70424fb0
I have source examples below, so I'll skip all of the other environment stuff.

#### Description of expected behavior and the observed behavior
`examples/charts/file/hover_span.py` creates a gridplot of the same dataset iterating through possible combinations of HoverTool:
*  [`mode`](http://bokeh.pydata.org/en/0.12.4/docs/reference/models/tools.html#bokeh.models.tools.HoverTool.mode)
* [line_policy](http://bokeh.pydata.org/en/0.12.4/docs/reference/models/tools.html#bokeh.models.tools.HoverTool.line_policy)

To illustrate the behavior of 'spanned' hover vs 'mouse' hover, the data should be plotted the same way The  example plots the dataset differently for `hline` and `vline` hover

#### Complete, minimal, self-contained example code that reproduces the issue
`examples/charts/file/hover_span.py` on 0.12.5rc3-24-ga70424fb0

I think that it really needs to be patched with:
```
diff --git a/examples/charts/file/hover_span.py b/examples/charts/file/hover_span.py
index f71640025..5e26c2aca 100644
--- a/examples/charts/file/hover_span.py
+++ b/examples/charts/file/hover_span.py
@@ -10,23 +10,23 @@ defaults.height = 300
 
 TOOLS='box_zoom,box_select,hover,crosshair,reset'
 
-TOOLTIPS = [ ("y", "$~y"), ("x", "$~x") ]
+TOOLTIPS = [ ("y", "$~y"), ("year", "$~x{0}") ]
 
 data = data[['Biology', 'Business', 'Computer Science', "Year"]]
 data = pd.melt(data, id_vars=['Year'],
                value_vars=['Biology', 'Business', 'Computer Science'],
                value_name='Count', var_name='Degree')
 
-vline = Line(data, y='Count', color='Degree', title="Lines VLine", ylabel='measures',
+vline = Line(data, x='Year', y='Count', color='Degree', title="Lines VLine", ylabel='measures',
              tools=TOOLS)
 
-hline = Line(data, y='Count', color='Degree', title="Lines HLine",
+hline = Line(data, x='Year', y='Count', color='Degree', title="Lines HLine",
              ylabel='measures', tools=TOOLS)
 
-int_vline = Line(data, y='Count', color='Degree', title="Lines VLine Interp",
+int_vline = Line(data, x='Year', y='Count', color='Degree', title="Lines VLine Interp",
                  ylabel='measures', tools=TOOLS)
 
-int_hline = Line(data, y='Count', color='Degree', title="Lines HLine Interp",
+int_hline = Line(data, x='Year', y='Count', color='Degree', title="Lines HLine Interp",
                  ylabel='measures', tools=TOOLS)
 
 scatter_point = Scatter(data, x='Year', y='Count', color='Degree',
```

Note, the patch adds `x='Year'` to the plots that are currently missing it.

I'll submit a PR for this later today.

**Comment by bryevdv** [comment]
this example is gone with `bokeh.charts`
