### ISSUE TITLE
No error / warning on vbar bottom > top (and HoverTool not working)

### ISSUE THREAD

**Issue by GPistre** [bokeh/bokeh#6097]
If the bottom of a vbar is superior to the top, no error or warning is raised, but any hover tool defined for this vbar will not work. (version 0.12.4)

```
from bokeh.plotting import figure, output_file, show
from bokeh.models import HoverTool

output_file("tooltip.html")

fig = figure(width=1200, height=900, x_range=['1'])

step0 = fig.vbar(x=1, bottom=0, top=1, width=0.5)

fig.add_tools(HoverTool(renderers=[step0], tooltips='some text'))

show(fig)

```

will work fine, but with

```
fig = figure(width=1200, height=900, x_range=['1'])

step0 = fig.vbar(x=1, bottom=1, top=0, width=0.5)

fig.add_tools(HoverTool(renderers=[step0], tooltips='some text'))

show(fig)
```

no text will appear on hover on the vbar.

**Comment by yschroeder** [comment]
I have the same issue. I like how the vbar gracefully ignores bottom and top being swapped and still draws correctly. However, I also noticed that the HoverTool does not show the tooltip. It works fine for other rectangles in the same vbar, where bottom and top are not swapped.

I consider it a bug, that the tooltip is not showing up.

**Comment by bryevdv** [comment]
This now works.
