### ISSUE TITLE
Tests didn't appropriately catch wrong cursor being set (test interpreter handles comparisons differently?)

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6101]
Related to PR #6100 

https://github.com/bokeh/bokeh/blob/master/bokehjs/test/common/ui_events.coffee#L53-L111

There was a bug in ui_events.coffee in what type of cursor was set. The relevant code chunk checked ``if active_inspectors?`` to see if there were any active inspectors (it's a bool value and not an undefined as I thought).

The mocha interpreter seems to have eval-ed ``if false != null`` as false while a browser seems to (correctly) eval it as true. It's unclear why this happened.

**Comment by bryevdv** [comment]
I don't think this is relevant any longer
