### ISSUE TITLE
Custom models in a Jupyter Notebook require `output_notebook()` to be called after model is defined

### ISSUE THREAD

**Issue by codypiersall** [bokeh/bokeh#6107]
If a custom Bokeh model is defined in a Jupyter notebook _after_ `output_notebook()` is called and a figure attempts to add the glyph to the plot, it fails with a Javascript error.  Calling `output_notebook()` after the model is created makes the rendering work.

An example notebook demonstrating the issue is [here](https://github.com/codypiersall/bokeh-custom-model).  It just re-implements the `Line` model as a custom model and attempts to `show()`.

**Comment by bryevdv** [comment]
@mattpap any comments? Offhand this makes sense to me, if the extension bundles are loaded at `output_notebook` time and not at `show` time. Can you confirm if that is the case? Are there any other issues or planned work to address this (is this a dupe?)

**Comment by codypiersall** [comment]
If this is expected behavior, maybe it could be documented on the [notebook page](http://bokeh.pydata.org/en/latest/docs/user_guide/notebook.html) of the user guide?

**Comment by bryevdv** [comment]
@codypiersall sorry, I didn't mean this is expected, only that it is understandable. It should be fixed, I am only trying to determine if this issue is needed or if there are others that already cover it.

**Comment by bryevdv** [comment]
I wonder if a simple hack solution could be: if `output_notebook` has already been called, then `show` could call it again before showing. If not I think documentation support will have to suffice.

**Comment by bryevdv** [comment]
I just tried my idea above, and it does not work. I think we should just add a note in the notebook chapter the docs and in the custom extension chapter

**Comment by bryevdv** [comment]
Doing that seems to result in a pause and also infinite console errors tho, so I think I still favor just resolving this with docs support:

<img width="1227" alt="screen shot 2018-06-27 at 12 54 56" src="https://user-images.githubusercontent.com/1078448/41990904-61b21ee2-7a09-11e8-9e66-00abe4351bb4.png">

**Comment by bryevdv** [comment]
Have adde this as a docs task to #8208, will track there
