### ISSUE TITLE
Notebook embed example is not working

### ISSUE THREAD

**Issue by ecerami** [bokeh/bokeh#6109]
Thanks for adding notebook embedding of Bokeh apps.

A few things:

1.  On your recent blog post:  https://bokeh.github.io/blog/2017/4/5/release-0-12-5/, under "Bokeh Apps Fully Support in Jupyter Notebooks", you have a link to an example:  https://github.com/bokeh/bokeh/blob/0.12.5/examples/howto/server_embed/tornado_embed.py.  I believe the link should actually go to:  https://github.com/bokeh/bokeh/blob/0.12.5/examples/howto/server_embed/notebook_embed.ipynb

2.  The notebook_embed example does not seem to work.  I am using bokeh 0.12.5.  The example as is does not display any bokeh components.  However, if I add the notebook_url, I do see bokeh.  For example, instead of:

show(app)

I have:

show(app, notebook_url="localhost:8889")

The bokeh slider and plot now appear correctly, but moving the slider has no effect.

**Comment by bryevdv** [comment]
Hi,

Thanks for the catch on the URL. Would you mind submitting a PR to update it? The file is here:

	https://github.com/bokeh/bokeh.github.io/blob/source/content/blog/release-0-12-5/contents.lr

That will be the quickest way to get it changed. 

Regarding notebook itself, providing notebook_url may be necessary in some cases, since the jupyter project steadfastly refuses to provide any information about the front-end to the kernel. So that it not unexpected. If the app is not functioning though, please open a GH issue with all the relevant details and information (versions, browser console logs, etc).

Thanks,

Bryan

**Comment by ecerami** [comment]
Thanks @bryevdv.  I submitted a pull request to fix the blog post URL.  Will work on providing additional info regarding the web app next.

**Comment by ecerami** [comment]
Here is the additional info:

Python 2.7.11 (default, Jan 22 2016, 08:28:37) 
Jupyter notebook:  5.0.0-da34fba
Bokeh: 0.12.5
OS:  Mac OS X 10.10.5
Browser:  Chrome Version 56.0.2924.87 (64-bit)

Movie of slider not working:

![embed](https://cloud.githubusercontent.com/assets/1009066/24828332/6308a058-1c28-11e7-93ef-5f91e36da30a.gif)

Browser console messages:

![screenshot_1651](https://cloud.githubusercontent.com/assets/1009066/24828307/1393851a-1c28-11e7-83bd-dd92aa8be16f.png)

**Comment by ecerami** [comment]
Digging into this further, this was a pandas issue with df.rolling(), and had nothing to do with bokeh.  Upgrading to the latest pandas version fixed everything.  Closing.

**Comment by bryevdv** [comment]
These kinds of errors show up prominently in the console when running `bokeh serve` at the command line. We will have to see if there is some technical way to surface them better in the notebook setting.

**Comment by avinashmaheshjoshi** [comment]
I seem to be facing the same issue (app not showing up. Different error). I am using the notebook linked above. Snapshot below,

Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17)
jupyter-client==5.2.3
jupyter-core==4.4.0
jupyterhub==0.9.1
Bokeh: 0.12.16
OS: Mac OS X 10.13.6
Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)


![image](https://user-images.githubusercontent.com/1736298/44572605-f8c47d00-a7a1-11e8-9f81-692141f0b0c8.png)
