### ISSUE TITLE
Only one figure is rendered correctly after refresh jupyte notebook

### ISSUE THREAD

**Issue by zjffdu** [bokeh/bokeh#6116]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh: 0.12.5
Jupyter: 5.0
Python: 3.5.2
OS: Mac OS
browser: Chrome

#### Description of expected behavior and the observed behavior
I have 2 jupyter cells which would plot one figure respectively. If I refresh the jupyter notebook, only one can be rendered correctly, the other would stuck in `Loading BokehJS`.

#### Screenshots or screencasts of the bug in action

![image](https://cloud.githubusercontent.com/assets/164491/24864828/01bd6cb8-1e38-11e7-92bc-ba2da5b89693.png)

**Comment by bryevdv** [comment]
Hi, it is required that the BokehJS runtime be loaded into the browser before anything can be displayed. For this reason, we always demonstrate calling `output_notebook` in a cell by itself first, before any plots. Can you confirm that things work if you do that? Unfortunately I am not sure there is any technical way to make things work robustly the way you have them.

**Comment by zjffdu** [comment]
I have called `output_notebook` in each cell as in the screenshot. This issue enforce me to rerun all the cells when I open a notebook.  What I want is to get all the figures correctly when I open the notebook.

**Comment by bryevdv** [comment]
Right, I'm asking what happens if you do things the way that all the example notebooks do things: a single output notebook call at the top. Before sny plots and not in the sane cell as any plots.

**Comment by zjffdu** [comment]
Thanks @bryevdv , it works when I call `output_notebook` in the first cell, and only call it once there.
