### ISSUE TITLE
Autocomplete Input appearance differs between notebook and html file output

### ISSUE THREAD

**Issue by lmcinnes** [bokeh/bokeh#6121]
#### Software version info

Bokeh version 0.12.2
Python version 3.5.2
Notebook version 4.2.0
MacOS 10.10.5
Chrome version 57.0.2987.133 (64-bit)

#### Description of expected behavior and the observed behavior

When displayed in the notebook using ``output_notebook`` the Autocomplete looks very nice with an appropriate dropdown menu when offering input suggestions. When ``output_file`` is used instead the result is rather less attractive -- it essentially looks unformatted. This also occurs if a notebook is converted to html via jupyter-nbconvert (the result is the same as the ``output_file`` appearance).

#### Complete, minimal, self-contained example code that reproduces the issue

In notebook the following is sufficient:

    from bokeh.plotting import show, output_notebook, output_file
    from bokeh.models.widgets import AutocompleteInput
    
    output_notebook()
    
    input_widget = AutocompleteInput(completions=['pok', 'wer', 'foo', 'bar', 'baz'], title='test')
    show(input_widget)

The typing (for example 'b') in the resulting widget a very nice looking drop down menu appears. If instead we use:

    from bokeh.plotting import show, output_notebook, output_file
    from bokeh.models.widgets import AutocompleteInput
    
    output_file('autocomplete_input.html')
    
    input_widget = AutocompleteInput(completions=['pok', 'wer', 'foo', 'bar', 'baz'], title='test')
    show(input_widget)

The result is different in appearance (and less attractive).

#### Screenshots or screencasts of the bug in action

<img width="402" alt="notebook autocompleteinput" src="https://cloud.githubusercontent.com/assets/11962885/24887144/b833109e-1e27-11e7-8263-a2938b6cb46d.png">
<img width="404" alt="html autocompleteinput" src="https://cloud.githubusercontent.com/assets/11962885/24887147/bc3c952a-1e27-11e7-838e-d673c93e2806.png">

**Comment by bryevdv** [comment]
I can reproduce this. My best guess is that the default styling has gotten removed or messed up at somehow, but that in the notebook some notebook CSS is overriding in a coincidentally pleasant.

Thoughts @mattpap ?

**Comment by lmcinnes** [comment]
For reference the relevant css to make the styling appear the same as in the notebook requires the addition of

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.min.css" type="text/css">

to the html file. Then things seem to look better. Not sure how to get bokeh to output that at the moment, so I'm just adding it by hand for now.

**Comment by bryevdv** [comment]
As there is a documented workaround, I am pushing this to the next milestone

**Comment by bryevdv** [comment]
@mattpap was this fixed with removal of jqui?

**Comment by mattpap** [comment]
@bryevdv, yes.

**Comment by tkchris93** [comment]
I am on version 0.12.7rc3 and though the styling is now correct in html, clicking on a word in the dropdown only sometimes completes the word in the input box. I have not been able to see any pattern as to when it works and when it doesn't. I tried this using the same code in the original post. 

```
from bokeh.plotting import show, output_notebook, output_file
from bokeh.models.widgets import AutocompleteInput

output_file('autocomplete_input.html')

input_widget = AutocompleteInput(completions=['pok', 'wer', 'foo', 'bar', 'baz'], title='test')
show(input_widget)
``` 
I'm using Chrome if that's relevant. If it would be more appropriate to start a new issue, let me know.

**Comment by bryevdv** [comment]
@tkchris93 new issue would be appropriate, thanks
