### ISSUE TITLE
RangeSlider Bug

### ISSUE THREAD

**Issue by crashMOGWAI** [bokeh/bokeh#6123]
This bug was introduced with 0.12.5 drop. 

![capture](https://cloud.githubusercontent.com/assets/17650526/24928106/d7aad8cc-1ec6-11e7-9066-8aad974dcc24.PNG)
```
from bokeh.io import output_file, show
from bokeh.layouts import widgetbox
from bokeh.models.widgets import RangeSlider
output_file("range_slider.html")
range_slider = RangeSlider(start=0, end=10, range=(1,9), step=.1, title="Stuff")
show(widgetbox(range_slider))

```
Env:
Python 3.5
Bokeh 0.12.5
Windows

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mattpap** [comment]
PR #5774 will fix this, as long as it's ever finished.

**Comment by covelloz** [comment]
PR #5774 looks awesome @mattpap. The current slider is very limited, only taking in float values. Sliders are probably one of the important components of interactive graphs/dashboards. Having extra flexibility with customization would make Bokeh that much more powerful. Hope it launches with 0.12.6! Godspeed ^^

**Comment by mattpap** [comment]
@covelloz, unfortunately there are some unforeseen interactions between PR #5774 and how bokehjs' layout handles widgets, and it's unlikely this will be resolved for 0.12.6. I'm currently targeting 0.12.7.

**Comment by covelloz** [comment]
:(. In the meantime, since the current range slider is buggy, is there an easy way to implement the ion range slider or provide an example of customizing this widget (say, to use dates like DateRangeSlider) in the examples/ directory for 0.12.5/6?
http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/widget.html

The code is provided and well commented but it's a little tough to follow. I haven't tried utilizing it yet. I play around with it.

**Comment by bryevdv** [comment]
@mattpap the problem just seems to be that it's triggering a real render far to often. Things seem to be working fine with this patch:
```
diff --git a/bokehjs/src/coffee/models/widgets/range_slider.coffee b/bokehjs/src/coffee/models/widgets/range_slider.coffee
index 685618bfb..08c12be65 100644
--- a/bokehjs/src/coffee/models/widgets/range_slider.coffee
+++ b/bokehjs/src/coffee/models/widgets/range_slider.coffee
@@ -14,7 +14,10 @@ export class RangeSliderView extends InputWidgetView

   initialize: (options) ->
     super(options)
-    @connect(@model.change, @render)
+    @connect(@model.properties.start.change, @_render)
+    @connect(@model.properties.end.change, @_render)
+    @connect(@model.properties.step.change, @_render)
+    @connect(@model.properties.orientation.change, @_render)
     @$el.empty()
     html = @template(@model.attributes)
     @$el.html(html)
@@ -26,10 +29,10 @@ export class RangeSliderView extends InputWidgetView
       @callbackWrapper = throttle(() ->
         @model.callback?.execute(@model)
       , @model.callback_throttle)
-    @render()
+    @_render()

-  render: () ->
-    super()
+  _render: () ->
+    @render()
     max = @model.end
     min = @model.start
     step = @model.step or ((max - min)/50)
```
Is there a reason not to just do this, at least for now?

**Comment by bryevdv** [comment]
It seems to me with the above change that setting `range` programmatically might now work (and the problem definitely shows up if you connect value to render) but it's currently completely unusable in all cases right now, and this patch would seem to make it usable in most all use-cases.
