### ISSUE TITLE
Issue upgrading from Bokeh 0.12.4 to 0.12.5 with IE 11

### ISSUE THREAD

**Issue by blacknapkins** [bokeh/bokeh#6127]
I encountered a problem upgrading from Bokeh 0.12.4 to 0.12.5 on Windows 10/7 with Python 3.5.

Using the code below from the User Guide Getting Started page.

```python
from bokeh.plotting import figure, output_file, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

# show the results
show(p)
```

In Chrome, Edge and IE 11 with Bokeh 0.12.4 the result is as expected.

![bokeh_ok](https://cloud.githubusercontent.com/assets/14756121/24931447/3838c9a4-1f05-11e7-873c-e973164e09fb.PNG)

In IE 11 with Bokeh 0.12.5 I get the following error, Chrome and Edge perform as expected.

Screenshot:
![bokeh_invalid](https://cloud.githubusercontent.com/assets/14756121/24931291/9e45a7a4-1f04-11e7-9848-339ab0b8ace6.PNG)

**Comment by bryevdv** [comment]
Thanks @blacknapkins we will look into it as soon as possible

**Comment by mattpap** [comment]
Side effect of PR #5730. In `core/util/eq.ts` we use the following code:
```
toString.call(expr)
```
where `toString` should be an alias to `Object.prototype.toString`, which it isn't. However, global `window` has all its members accessible without `window.` prefix, so there is a "global" `toString()` function. In most browsers it doesn't matter what `this` in that function is bound to, but IE has its own requirements and thus "Invalid calling object" error.

This is a trivial mistake in copying code, but it really shows how badly messed up tools we have to use.

**Comment by mattpap** [comment]
I will submit a fix tomorrow.

**Comment by blacknapkins** [comment]
@mattpap  thanks for looking at this.

**Comment by bryevdv** [comment]
@blacknapkins The fix has been merged. There will be a dev build available probably later today, if you can test with it that would be a great help.

**Comment by blacknapkins** [comment]
@bryevdv thanks for this. I am happy to test this. I have set up an environment in Anaconda to point to the dev builds and will keep an eye on it.

**Comment by canavandl** [comment]
We're created a dev release with this PR that can be installed via ``conda install -c bokeh/label/dev bokeh=0.12.6dev1``. Let us know if you're able to try it and it doesn't work.

**Comment by blacknapkins** [comment]
@canavandl  Thanks for pointing me at the dev build. It has resolved my issue.

I have tested the build with no fault found under the following configurations with Python 3.5 .

OS:
Win 7
Browsers:
Chrome, IE11, Firefox

OS:
Win10
Browsers:
Chrome, IE11, Edge

I have used the test case I identified and also a slightly more complicated example.

Thanks for the effort.

**Comment by canavandl** [comment]
fantastic. thanks

**Comment by covelloz** [comment]
Thanks @canavandl for the dev release fix. I came across the same issue. Dev build fixed it.

**Comment by David-Herman** [comment]
Hello @canavandl  . One question, do you have a CDN for developer builds available. The documentation does not not document this and I would I am encountering an issue with IE and BokehJS 012.5/6?

**Comment by canavandl** [comment]
@David-Herman the package for dev builds are uploaded to our CDN, so they should work normally. But the 0.12.6 official release, containing the fix for this issue, has been released and should be installable via normal methods.

**Comment by bryevdv** [comment]
We publish dev build (including CDN resources)  in order to have a means to develop and test and exercise our own build infrastructure. Secondarily it's also useful to get pre-built packages into people's hands for testing or evaluation. But the release tags and CDN resources ***are absolutely 100% NOT guaranteed to remain forever***. Dev builds should absolutely never be used for anything "permanent" or if you still decide to do that, should use "inline" resources instead of CDN resources. Dev build CDN resources *will* be cleaned and removed someday.
