### ISSUE TITLE
MultiLine hit_test fails if line_width property utilized

### ISSUE THREAD

**Issue by shea-parkes** [bokeh/bokeh#6130]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 0.12.5
Python 3.5.2
Windows 10
Chrome 57.0.2987.133

#### Description of expected behavior and the observed behavior

Expected for the TapTool to select Glyphs.  Instead, BokehJS throws an uncaught exception.

To make it work as expected, just disable the use of `line_width` attribute.  (I, of course, would like to use `line_width`...)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import bokeh.models as bkm
import bokeh.plotting as bkp
import bokeh.events as bke
import bokeh.layouts as bkl

src_vertices = bkm.ColumnDataSource(
    data={
        'x': [
            0,
            0,
            1,
            1,
        ],
        'y': [
            0,
            1,
            1,
            0,
        ],
    }
)
src_edges = bkm.ColumnDataSource(
    data={
        'xs': [
            [0, 0],
            [0, 1],
        ],
        'ys': [
            [0, 1],
            [0, 1],
        ],
        'ids': [
            [0, 1],
            [0, 2],
        ],
        'widths': [
            2,
            3,
        ],
    }
)

ref_wheelzoomtool = bkm.WheelZoomTool()

fig = bkp.figure(
    tools=[
        bkm.PanTool(),
        ref_wheelzoomtool,
        bkm.TapTool(),
        bkm.ZoomInTool(),
        bkm.ZoomOutTool(),
        bkm.ResetTool(),
        bkm.SaveTool(),
    ],
    active_scroll=ref_wheelzoomtool,
)
fig.multi_line(
    xs='xs',
    ys='ys',
    line_width='widths', # THIS IS THE LINE THAT BREAKS IT
    color='grey',
    source=src_edges,
    name='edges',
)
fig.circle(
    x='x',
    y='y',
    source=src_vertices,
    name='vertices',
    size=10,
)


bkp.output_file(
    "c:\scratch\example.html",
)
bkp.show(fig)
```

#### Stack traceback and/or browser JavaScript console output
```
bokeh-0.12.5.min.js:7 Uncaught Error: attempted to retrieve property value for property without value specification
    at e.r.Property.t.value (bokeh-0.12.5.min.js:7)
    at e.r.MultiLineView.e._hit_point (bokeh-0.12.5.min.js:32)
    at e.r.GlyphView.r.hit_test (bokeh-0.12.5.min.js:31)
    at e.r.GlyphRendererView.e.hit_test (bokeh-0.12.5.min.js:36)
    at e.r.SelectionManager.e.select (bokeh-0.12.5.min.js:8)
    at e.r.TapToolView.e._select (bokeh-0.12.5.min.js:39)
    at e.r.TapToolView.e._tap (bokeh-0.12.5.min.js:39)
    at p (bokeh-0.12.5.min.js:7)
    at _ (bokeh-0.12.5.min.js:7)
    at s (bokeh-0.12.5.min.js:7)
    at t.r.Events.trigger (bokeh-0.12.5.min.js:7)
```

#### Screenshots or screencasts of the bug in action

![image](https://cloud.githubusercontent.com/assets/5782892/24937443/bac2b77e-1efe-11e7-8bbb-1c5444203254.png)

**Comment by bryevdv** [comment]
The hit testing path for multiline assumes non-vectorized properties:

<img width="1113" alt="screen shot 2017-04-12 at 11 11 21" src="https://cloud.githubusercontent.com/assets/1078448/24967771/ce3d56b6-1f70-11e7-85a5-39991401f3c3.png">

**Comment by bryevdv** [comment]
Note the PR to add hit testing to segments does this too (for now), so it should also be fixed up in whatever same way (and other instance of this checked for in the codebase as well)

**Comment by bryevdv** [comment]
Fairly sure the best solution is to use `cache_select`:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/visuals.coffee#L26

**Comment by bryevdv** [comment]
Will make the same change in the segment PR directly
