### ISSUE TITLE
Installation error: OSError: [Errno 1] Operation not permitted:

### ISSUE THREAD

**Issue by cnhemachena** [bokeh/bokeh#6141]
Hello,

I am trying to install Bokeh via pip and I get the following errors:

---------------------------------------------------------------------

Cains-MacBook-Pro:~ cnhemachena$ sudo pip install bokeh
Password:
The directory '/Users/cnhemachena/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/cnhemachena/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting bokeh
  Downloading bokeh-0.12.5.tar.gz (7.0MB)
    100% |████████████████████████████████| 7.0MB 119kB/s 
Collecting six>=1.5.2 (from bokeh)
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=1.2.3 in /Library/Python/2.7/site-packages (from bokeh)
Requirement already satisfied: PyYAML>=3.10 in /Library/Python/2.7/site-packages (from bokeh)
Collecting python-dateutil>=2.1 (from bokeh)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 165kB/s 
Requirement already satisfied: Jinja2>=2.7 in /Library/Python/2.7/site-packages (from bokeh)
Requirement already satisfied: numpy>=1.7.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from bokeh)
Requirement already satisfied: tornado>=4.3 in /Library/Python/2.7/site-packages (from bokeh)
Requirement already satisfied: futures>=3.0.3 in /Library/Python/2.7/site-packages (from bokeh)
Requirement already satisfied: MarkupSafe in /Library/Python/2.7/site-packages (from Jinja2>=2.7->bokeh)
Requirement already satisfied: singledispatch in /Library/Python/2.7/site-packages (from tornado>=4.3->bokeh)
Requirement already satisfied: certifi in /Library/Python/2.7/site-packages (from tornado>=4.3->bokeh)
Requirement already satisfied: backports_abc>=0.4 in /Library/Python/2.7/site-packages (from tornado>=4.3->bokeh)
Installing collected packages: six, python-dateutil, bokeh
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-ZXcdNt-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
Cains-MacBook-Pro:~ cnhemachena$ 

---------------------------------------------------------------------
Your assistance would be much appreciated.

**Comment by bryevdv** [comment]
That error is coming from `pip` itself, not Bokeh. It appears to be reporting a permissions error, which indicates perhaps that you are trying to install into a location for which you do not have the necessary file permissions. In any case the tracker is for bug reports, not general help and support. Please move this discussion to the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
