### ISSUE TITLE
Regression in Legend positioning

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#6142]
I've been running into issues with legend positioning recently and it seems this is a regression in 0.12.5. Comparing the docs Styling Visual Attributes guide section for positioning legends outside the plot area between 0.12.4 and 0.12.5 reveals this:

[0.12.4](http://bokeh.pydata.org/en/0.12.4/docs/user_guide/styling.html#outside-the-plot-area)

<img width="614" alt="screen shot 2017-04-14 at 1 16 53 am" src="https://cloud.githubusercontent.com/assets/1550771/25028907/26c615e4-20b0-11e7-95e7-cff30b25ac25.png">

[0.12.5](http://bokeh.pydata.org/en/0.12.5/docs/user_guide/styling.html#outside-the-plot-area)

<img width="613" alt="screen shot 2017-04-14 at 1 17 23 am" src="https://cloud.githubusercontent.com/assets/1550771/25028912/2d27fb6e-20b0-11e7-9f00-be8d6ca42a5d.png">

**Comment by ea42gh** [comment]
+1

**Comment by bryevdv** [comment]
So, I note that if this is used:
```
legend = Legend(items=[
    ("sin(x)"   , [r0, r1]),
    ("2*sin(x)" , [r2]),
    ("3*sin(x)" , [r3, r4]),
], location=(0, 330))
```
Then the result is:

<img width="699" alt="screen shot 2017-05-08 at 14 13 36" src="https://cloud.githubusercontent.com/assets/1078448/25820896/8e3a0888-33f8-11e7-8851-174d409a387b.png">


So I think the regression might simply be a mixup between view and screen coordinates (i.e. inverted y-axis) 

On the one hand that means it should be easy to fix, on the other hand I kind of think the new behaviour with 0 being at the bottom with positive coords above might be preferable....

ping @mattpap @canavandl for thoughts.

**Comment by mattpap** [comment]
@bryevdv, this may be it. I had a hard time dealing with this weird choice of coordinate system when working on interactive legends (this is where regression occurred).

**Comment by bryevdv** [comment]
Thinking a bit I suppose the reasoning for the previous indexing was that it might be more common to want to offset the legend from the top. I wonder if there is a way to have the best of all worlds, with negative offsets being down from the top, and positive offsets being up from the bottom? Maybe that is too complicated... if so we should probably just restore the old behavior.

**Comment by philippjfr** [comment]
I have no strong preference but I do think that treating positive and negative offsets differently might be confusing. I'd probably prefer restoring the old behavior for backwards compatibility. That said is there any way the location could be specified in relative plot coordinates (i.e. in the range 0-1 relative to the plot height and width) so that I could specify a fixed offset offset independent of the size of the plot?
