### ISSUE TITLE
Clarify tornado dependency

### ISSUE THREAD

**Issue by chinasaur** [bokeh/bokeh#6147]
I see some documentation claiming tornado >= 4.0 is required, some claiming >= 4.3.  I'm stuck with an even earlier version, so I'm furthermore curious to know whether these are verified hard requirements, or if earlier versions just haven't been tested?

**Comment by chinasaur** [comment]
Okay, so far I see that bokeh imports tornado.locks, which is new in 4.2.  So at least >= 4.2 is confirmed.

**Comment by bryevdv** [comment]
Yes there are definitely features that we used from Tornado 4.3 in the server. (I don't remember the details but I remember the discussion about adopting them). Of course, it may be possible for some specific use-case and app that things might work. You'd have to try things and see. 

It probably also bears mentioning explicitly that tornado is only needed at all if you are making bokeh server app. Tornado is not needed to make standalone documents. If there are more questions, the mailing list is a better place:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
