### ISSUE TITLE
Plot.add_layout should be renamed Plot.add_guide

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6150]
It's confusing because:
* GuideRenders (and annotations) are added via this method
* Layouts are a different set of Bokeh models (Rows, Columns, etc) and don't use this method

**Comment by mattpap** [comment]
* annotations aren't guides
* add_layout makes some sense, because this method is tightly bound to manipulation of canvas layout

**Comment by mattpap** [comment]
The right approach would be to make side panels first class citizens, then you would just issue `plot.left.append(axis)`.

**Comment by bryevdv** [comment]
`plot.left.append(axis)` would be great if it can be made to work.

**Comment by mattpap** [comment]
It's doable, but even with #5976 it will be a major piece of work.

**Comment by bryevdv** [comment]
this is a dupe of #5303
