### ISSUE TITLE
Error with ColumnDataSource in 0.12.5

### ISSUE THREAD

**Issue by lsuttle** [bokeh/bokeh#6153]
Creating a ColumnDataSource from a pandas dataframe in 0.12.5 causes an error that was not present in 0.12.4. It appears that the difference is that 0.12.5 is adding the index to the first column. Error is below. Note the 0, 1, and 2 before the actual values. These are not present in 0.12.4 and I cannot find documentation for why they were added or how to get around them.

```
ValueError: Unrecognized range input: '0    $100
1    $200
2    $400
Name: bin, dtype: object'
```
Code used to replicate the error:

```
def make_bar(df, x, y, title):
    """ Creates a bar chart in bokeh"""
    p = figure(title=title,
               x_range= df.data[x], webgl=True,
               plot_width=400,
               plot_height=400)
    p.vbar(x= x,
           width=0.5,
           bottom=0,
           top=y, color="darkgreen",
           source = df)
    return p

df = pd.DataFrame([
    {"bin": '$100', 'count': 100},
    {"bin": '$200', 'count': 200},
    {"bin": '$400', 'count': 400}
])

src = ColumnDataSource(data=df) # convert to bokeh column source
p = make_bar(src, 'bin', 'count', 'Title', format='None')
```

**Comment by bryevdv** [comment]
Bokeh CDS has been adding an index to converted data frames for a long time (a few years at least). Nothing about this changed with `0.12.5` (though we are considering making this behaviour configurable) so I'm not sure why you would only see an issue now. Can you update the code above to provide a complete example that can be run as-is for further investigation?

**Comment by lsuttle** [comment]
I have fixed my version to 0.12.4 because it does not give me the issue. 

What would make an example more complete? I'm new to reporting issues.

**Comment by bryevdv** [comment]
> What would make an example more complete? I'm new to reporting issues.

No problem, the report is appreciated. In this case, there are missing imports, and it's not clear whether additional code to `show` `output_file`, etc is needed.

**Comment by bryevdv** [comment]
Closing because there was no follow up to provide an MRE and no other users have reported any similar issue.
