### ISSUE TITLE
Docs failing to build within conda env

### ISSUE THREAD

**Issue by maxgamurar** [bokeh/bokeh#6170]
OS: ubunty 16 x64
Conda 4.2.13 | Python 2.7
Creating conda env with following yml:

~~~~
name: bokeh-docs
channels:
  - defaults
dependencies:
  - python=2
  - sphinx=1.5
  - bokeh
~~~~

and getting following error after activating source and running make html:
~~~~
Extension error:
Could not import extension bokeh.sphinxext.bokeh_index_toctree (exception: No module named packaging.version)
Makefile:32: recipe for target 'html' failed
make: *** [html] Error 1
~~~~

**Comment by bryevdv** [comment]
Many more things are needed in order to build the docs. Basically everything in this this `meta.yaml`:

https://github.com/bokeh/bokeh/blob/master/conda.recipe/meta.yaml

You can also see what travis does, here:

https://github.com/bokeh/bokeh/blob/master/scripts/travis_install
