### ISSUE TITLE
Disable HoverTool Per Glyph

### ISSUE THREAD

**Issue by um8ra** [bokeh/bokeh#6171]
Version: 0.12.5
Browser: All (using "components" function to pass script/div)
Python Version: 3.5+

Description:
I have a stacked bar chart. I would like to have a hovertool describe ALL fields in the bar chart for a given bar. I've accomplished this by having individual quad glyphs for each color, and a transparent one over all of them. I'd like the hovertool to be enabled on the single transparent one, and disabled on the other ones (it is redundant).

Example: Each of the stacked bars has a single (from top to bottom) transparent glyph with all the data I want. The others have simple X/Y coordinates. I want to be able to disable the lower green glyph I am also hovering over.

![image](https://cloud.githubusercontent.com/assets/16314441/25233100/3c669868-25a3-11e7-877a-fdf52f2eca7b.png)

**Comment by bryevdv** [comment]
In order to keep the tracker manageable, it is reserver for bug reports, feature requests, and development related discussion. For general help and support, the project mailing list is the appropriate place:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
