### ISSUE TITLE
Add numeric input widget

### ISSUE THREAD

**Issue by herm** [bokeh/bokeh#6173]
Currently the only way I could find to input numbers directly is by using sliders. However if the range is quite large or you require high precision this is impractical. Currently I'm using a TextInput and casting, but a new widget which accepts numbers without casting would be useful. This could translate to `<input type="number">` in HTML.

**Comment by herm** [comment]
There is some WIP code here:
https://github.com/herm/bokeh/tree/number_input

It already works but the design doesn't look right.

**Comment by bryevdv** [comment]
@herm If you'd like to submit a PR, we would be happy to help you iterate on the development.

**Comment by mattpap** [comment]
This was added in PR #8678.
