### ISSUE TITLE
HoverTool vline/hline models for Line glyph (_hit_span method) causes non-intuitive tooltips to appear

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6174]
HoverTool vline/hline models for Line glyph (_hit_span method) causes non-intuitive tooltips to appear. I would expect the same tooltip behavior as the commented-out scatter:

If I hold the cursor at (3.9, 3.5)

<img width="413" alt="screen shot 2017-04-20 at 1 13 19 pm" src="https://cloud.githubusercontent.com/assets/2198981/25241118/3743c9be-25cb-11e7-9b64-db7d61a4fa46.png">

Otherwise, If I hold the cursor at (4.1, 3.5)

<img width="2" alt="screen shot 2017-04-20 at 1 13 15 pm" src="https://cloud.githubusercontent.com/assets/2198981/25241125/3a8d2d86-25cb-11e7-9592-d8fb0004b4cd.png">

At no point along y=3.5 will the top point be inspected. The user has to move the mouse up to y=4. Is this the intended behavior?

Code to reproduce.
```python
from bokeh.plotting import figure, show
from bokeh.models import HoverTool

p = figure(plot_width=400, plot_height=400, tools='')
# p.scatter(x=[1,2,3,4,5], y=[4,2,4,5,3])
p.line(x=[1,2,3,4,5], y=[4,2,4,5,3])

h = HoverTool(mode='vline')
p.add_tools(h)
show(p)
```

Bokeh 0.12.6dev2
Chrome 58
Python 3.5

**Comment by bryevdv** [comment]
The default `line_policy` is `nearest` which computes a standard 2d norm from the mouse position. It's possible and probably better to compute only the distance to the line, when using a line.
