### ISSUE TITLE
dynamically added LegendItem gets disconnected from renderer

### ISSUE THREAD

**Issue by chupach** [bokeh/bokeh#6190]
here below is some code demonstrating that dynamically added legend items get sometimes disconnected from the associated renderer. The javascript console shows some corruption.

This instable behaviour somehow means that it should be in principle possible to reliably implement this app (bokeh 0.12.5, safari or firefox, python 3.5)

The app exhibits a figure with a plot and an empty Legend. A LegendItem can be added dynamically and clicked with hide policy, or removed (Toggle widget).

At first (sometimes), everything works well, sometimes for several rounds of toggling on/off the LegendItem and clicking on it, until it does not anymore: 
- when toggling on (the line is visible), the LegendItem is faded : It is disconnected from the line. Sometime toggling off and back on when line is disconnected revives the app.
- sometimes, clicking the LegendItem stops acting on the line visibility
- sometimes, the line gets lost (clicking on LegendItem and then removing the LegendItem), no way to recover.
- In above cases, renderer callbacks are not working anymore.

Inspecting the Legend object after adding a LegendItem object which is disconnected from its renderer in the js console, we notice that :
_Legend.changed.items[0].renderers[0] =  {type: "GlyphRenderer", id: "c18880eb-1602-4710-b207-29573a9c7c32", visible: false}_
i.e. it is somehow corrupted: a dict instead of a renderer object.

On the other hand, when the LegendItem is properly connected to the renderer, we have:
Legend.changed.items[0].renderers[0] =  [e]
where e is a renderer object as expected.

and an inelegant way to cure it might be to explicitly set again the renderer array of LegendItem after declaring it.

```
from bokeh.io import curdoc
from bokeh.models import CustomJS,ColumnDataSource
from bokeh.layouts import layout,row,column
from bokeh.plotting import figure
from bokeh.models import Legend,LegendItem
from bokeh.models.widgets import Toggle

b = Toggle(label='add/remove leg')

source = ColumnDataSource(dict(index=[0,1,2],x=[1,2,3],dn=[3,2,1]))
p = figure(plot_width=800, plot_height=250)
r_dn = p.line(x='x',y='dn',legend='down',name='gr_dn',source=source)

leg = p.legend[0]
leg.items.pop()
leg.location = 'top_right'
leg.click_policy="hide"
leg.inactive_fill_alpha={'value': 0.8}
leg.inactive_fill_color={'value': 'white'}

def b_cb(x):
    print('toggle',x)
    if x:
        li = LegendItem(label='down',renderers=[r_dn])
        p.legend[0].items.append(li)
    else:
        p.legend[0].items.pop()

b.on_click(lambda x: b_cb(x))

js_callback_gr = CustomJS(code="""console.log('callback gr',cb_obj);""")
r_dn.js_on_change('visible',js_callback_gr)

def callback_gr(attr,old,new):
     print('renderer changed',attr,old,new)
r_dn.on_change('visible',callback_gr)

curdoc().add_root(column(b,p))

```

**Comment by bryevdv** [comment]
I am no longer able to reproduce any problems with this code using current `master`, either error messages in the JS console or server logs, or unexpected behavior in the plot itself. I toggled the button and the legend visibility ~200 times in all sorts of configurations, in rapid fire and with pauses in between. 

If this is still an issue on Bokeh > 0.13 please re-open with more information.
