### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'tooltips'

### ISSUE THREAD

**Issue by gopal10sep** [bokeh/bokeh#6194]
```
`import bokeh.plotting as bp
from bokeh.plotting import figure
from bokeh.models import HoverTool
bp.output_notebook()
row_selector = np.where(users_per_subreddit>5)
tbf = bp.figure(plot_width=900, plot_height=700, title="Subreddit Map by Most Informative Dimensions",
       x_axis_label = "Dimension 0",
       y_axis_label = "Dimension 1",
       tools="pan,wheel_zoom,box_zoom,reset,hover,previewsave",
       min_border=1)
tbf.scatter(
    x = embedded_coords[:,0][row_selector],
    y = embedded_coords[:,1][row_selector],
    radius= np.log2(users_per_subreddit[row_selector])/6000,
    source=bp.ColumnDataSource({"subreddit": subreddits[row_selector]})
).select(HoverTool).tooltips = {"/r/":"@subreddit"}


tbf.show()`
```

> After importing the bokeh, I am trying to plot a clustering graph. I am newbie to this. This snippet is giving the following error:
```


`AttributeError                            Traceback (most recent call last)
<ipython-input-14-51346c59c121> in <module>()
      9     radius= np.log2(users_per_subreddit[row_selector])/6000,
     10     source=bp.ColumnDataSource({"subreddit": subreddits[row_selector]})
---> 11 ).select(HoverTool).tooltips = {"/r/":"@subreddit"}
     12 
     13 # s1 = fig.scatter(x=x,y=y1,color='#0000ff',size=10,legend='sine')

AttributeError: 'generator' object has no attribute 'tooltips'`


```

> What to do??? Can someone tell me what possibly is going wong here?

**Comment by mattpap** [comment]
Use `select_one(...)` or `list(select(...))[0]`.

**Comment by bryevdv** [comment]
Additionally @gopal10sep please do not use the GH issue tracker for general support, as we reserve it for bug reports and feature requests only, in order to keep it manageable. For general help and support the best place is the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by gopal10sep** [comment]
OKay @bryevdv  I wont post here from now on.
`
tbf.scatter(
    x = embedded_coords[:,0][row_selector],
    y = embedded_coords[:,1][row_selector],
#     x = embedded_coords[:,44][row_selector],
#     y = embedded_coords[:,51][row_selector],
    color= colormap[clusters[row_selector]], 
    radius= np.log2(users_per_subreddit[row_selector])/6000, 
    source=bp.ColumnDataSource({"subreddit": subreddits[row_selector]})
).select_one(dict(type=HoverTool)).tooltips = {"/r/":"@subreddit"}
`

 But  can you help me out with this, on using this still I am getting this error:
'''
`
AttributeError                            Traceback (most recent call last)
<ipython-input-38-549581fd6910> in <module>()
     39     radius= np.log2(users_per_subreddit[row_selector])/6000,
     40     source=bp.ColumnDataSource({"subreddit": subreddits[row_selector]})
---> 41 ).select_one(dict(type=HoverTool)).tooltips = {"/r/":"@subreddit"}
     42 #).list(select(dict(type=HoverTool)).tooltips = {"/r/":"@subreddit"})
     43 

AttributeError: 'NoneType' object has no attribute 'tooltips'`
'''

**Comment by gopal10sep** [comment]
@mattpap  Can you help me with this?
`
tbf.scatter(
    x = embedded_coords[:,0][row_selector],
    y = embedded_coords[:,1][row_selector],
    color= colormap[clusters[row_selector]], 
    radius= np.log2(users_per_subreddit[row_selector])/6000, 
    source=bp.ColumnDataSource({"subreddit": subreddits[row_selector]})
).select_one(dict(type=HoverTool)).tooltips = {"/r/":"@subreddit"}`

On using select_one, i am getting this error: 

`
AttributeError                            Traceback (most recent call last)
<ipython-input-38-549581fd6910> in <module>()
     39     radius= np.log2(users_per_subreddit[row_selector])/6000,
     40     source=bp.ColumnDataSource({"subreddit": subreddits[row_selector]})
---> 41 ).select_one(dict(type=HoverTool)).tooltips = {"/r/":"@subreddit"}
     42 #).list(select(dict(type=HoverTool)).tooltips = {"/r/":"@subreddit"})
     43 

AttributeError: 'NoneType' object has no attribute 'tooltips'`

@bryevdv  I will keep that in mind and wont post here. The google groups is pretty inactive. That is why I posted here.
