### ISSUE TITLE
Conda has bad MD5 for new Bokeh Version

### ISSUE THREAD

**Issue by crwilcox** [bokeh/bokeh#6195]
MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.continuum.io/pkgs/free/linux-64/bokeh-0.12.5-py35_0.tar.bz2'.
download saved to: /home/nbcommon/anaconda3_410/pkgs/bokeh-0.12.5-py35_0.tar.bz2
expected md5 sum: c2fba6bfe68e74efb944aa414dbf4558
actual md5 sum: c5790a64ee8a2095d46535793819807c

this is running an update on bokeh (The following packages will be UPDATED: bokeh:        0.11.1-py35_0     --> 0.12.5-py35_0)

This occurred while running: ~/anaconda3_410/bin/conda install --yes libgfortran seaborn holoviews bokeh scikit-bio pillow pywget pymongo pymysql pyodbc psycopg2

**Comment by kalefranz** [comment]
Well I can confirm that there's something up.

```
$ curl -sS https://repo.continuum.io/pkgs/free/linux-64/bokeh-0.12.5-py35_0.tar.bz2 | md5
c5790a64ee8a2095d46535793819807c
$ curl -sS https://repo.continuum.io/pkgs/free/linux-64/repodata.json | jq .packages | jq '.["bokeh-0.12.5-py35_0.tar.bz2"].md5'
"c2fba6bfe68e74efb944aa414dbf4558"
```

**Comment by kalefranz** [comment]
From the source of truth:

```
$ md5sum bokeh-0.12.5-py35_0.tar.bz2
c2fba6bfe68e74efb944aa414dbf4558  bokeh-0.12.5-py35_0.tar.bz2
```

**Comment by kalefranz** [comment]
So the edge cache might be stale.  I'll invalidate it manually.

**Comment by crwilcox** [comment]
Thanks for looking into this @kalefranz!

**Comment by kalefranz** [comment]
Ok looks like it's fixed.

```
$ curl -sS https://repo.continuum.io/pkgs/free/linux-64/bokeh-0.12.5-py35_0.tar.bz2 | md5
c2fba6bfe68e74efb944aa414dbf4558
```

I don't think it's too much of an issue if this happens on occasion.  But more than that, and we're going to have to figure out root cause and also a process to automatically detect these issues.

**Comment by bryevdv** [comment]
Thanks @kalefranz
