### ISSUE TITLE
examples/app/movies/main.py doesn't work on Safari 10.1 due to websocket issue

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6196]
examples/app/movies/main.py doesn't work on Safari 10.1 due to websocket issue

<img width="1414" alt="c9bdc4c0-2a6c-11e7-9161-683103c91217" src="https://cloud.githubusercontent.com/assets/2198981/25445981/55e1b682-2a86-11e7-9486-9e573a93384d.png">

However, if I I reduce the data size, even by half:

movies = movies[::2]

Then it starts working. I believe I may have heard something about safari changing the default max websocket frame size. I thought that was for the future. Perhaps it's not for the future, and somehow is interacting with other changes here. If there is a way to raise that limit we could investigate.

Here's some related discussion from the ML:

https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/websocket$20safari%7Csort:relevance/bokeh/KvrSS3CMBC4/mU0ekn1WAQAJ

MacOS
Safari 0.10.1
Bokeh 0.12.5

**Comment by bryevdv** [comment]
This might be the relevant webkit issue:

https://bugs.webkit.org/show_bug.cgi?id=170463

not sure I'd consider this a regression if its not our fault :)

**Comment by bryevdv** [comment]
According to later comments that issue is fixed in "Safari Technology Preview r28" so it would be useful to tests the movies example against that, to see if it is in fact the same issue. Will have to investigate how to get/install it.

**Comment by bryevdv** [comment]
FYI the current safari technology preview fixes this problem:

https://developer.apple.com/safari/technology-preview/

I am not sure what can be done but wait for the next safari release, there is at least usually rapid adoption of new versions. As far as I know there is nothing we can do on our end.

**Comment by bryevdv** [comment]
I"m reluctantly closing this as `upstream`. Several more people and organizations have commented on the webkit issue, but there is no mention of any workaround.

**Comment by bryevdv** [comment]
Looking now there are some mentions of workarounds but I don't think any of them are tenable:

* "chunk" sent data --- there is no clear guidance on what a save size would be. I'm also not sure how we could do this with Bokeh's protocol. It would be at least weeks of work to make very risky lowest-level changes with no guarantee of success

* add delays --- the delays mentioned are on the order of hundreds of milliseconds. This would cripple Bokeh's performance and interactivity.

**Comment by hsparra** [comment]
It seems to me it would be best just to wait for an update to Safari. The options all seem high risk with low to poor payback.
