### ISSUE TITLE
client.coffee sets binary type incorrectly 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6199]
At this line:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/client.coffee#L138

the code does:
```
@socket.binarytype = "arraybuffer"
```

But the actual property name is `binaryType` (camel case). Offhand I am not sure why this does not cause problems, at least for tests (i.e. it might only affect multi-frame payloads.. we don't use those yet but we do test them at least superficially... but maybe not with actual array content) This probably has to change before real binary protocol work though

**Comment by mattpap** [comment]
If we don't send binary content, then this error is harmless. The default value is `blob`.

**Comment by bryevdv** [comment]
Yes, as I said we definitely don't (yet) in actual releases, I thought there was a test for this though. We definitely intend to investigate the zero-encoding binary transfer with a separate frame for each array (so no extra copies to/from).
