### ISSUE TITLE
HTMLTemplateFormatter still uses underscore

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6207]
This was missed in the work to remove underscore:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/cell_formatters.coffee#L112

ping @mattpap

**Comment by jizg** [comment]
@mattpap is there any workaround now for this issue, something like include underscore manually. I tried someway but all not work.

**Comment by jizg** [comment]
Tried to extend existing HTMLTemplateFormatter as follows
`from bokeh.models.widgets import HTMLTemplateFormatter

class MyHTMLFormatter(HTMLTemplateFormatter):
    __javascript__ = ["https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"]
    __implementation__ = """
import {HTMLTemplateFormatter} from "models/widgets/cell_formatters"
export class MyHTMLFormatter extends HTMLTemplateFormatter
  type: 'MyHTMLFormatter'
"""

colorformater =  MyHTMLFormatter(template=colorTemplate)
`
Worked like a charm. Thanks @bryevdv for your hint.

**Comment by mattpap** [comment]
@bryevdv, that was left on purpose. I plan to separate data table from the rest of widgets and as data table's code is huge anyway, keeping underscore there doesn't make much difference. On the other hand, I don't want to see this horrible templating code in core bokehjs anymore.

**Comment by mattpap** [comment]
I see, we are missing an import here.

**Comment by mattpap** [comment]
@jizg, including underscore manually should work as well, just make sure it's loaded before any bokehjs code.

**Comment by bryevdv** [comment]
@mattpap what is the solution for the core library, though? Maybe this? 

https://www.npmjs.com/package/underscore.template

Looks like 3kb unminified.

**Comment by bryevdv** [comment]
@jizg this should be resolved in master and available in the next dev build and full release.

**Comment by farscape2012** [comment]
@bryevdv @mattpap 
I have tested in a dev build. It was working. The bokeh version is '0.12.6rc3' from this link [http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds](url)
