### ISSUE TITLE
for gmap in notebook, output_notebook() cannot be in previous cell

### ISSUE THREAD

**Issue by bendichter** [bokeh/bokeh#6209]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 0.12.5
python: '3.5.1 |Anaconda 2.4.1 (x86_64)| (default, Dec  7 2015, 11:24:55) \n[GCC 4.2.1 (Apple Inc. build 5577)]'
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.0.3)
jupyter-core (4.1.0)
IPython 4.1.2
OS: mac 10.11.6
browser: chrome 57.0.2987.133 (64-bit)

#### Description of expected behavior and the observed behavior
gmaps inline on jupyter notebooks displays a grey square sometimes. The first time I ran this code it worked as expected, but the next few times it just showed up as a grey square with "google" at the bottom left. Every now and then it works as expected again, but that's about 5% of the time, and I can't figure out why it works sometimes. I found a work-around that it works correctly every time if `output_notebook()` is in the same cell as `show()`

#### Complete, minimal, self-contained example code that reproduces the issue
This does not work in notebook:
```python
from bokeh.models import GMapOptions
from bokeh.plotting import show, gmap, output_notebook
output_notebook()

map_options = GMapOptions(lat=37.769183, lng=-122.3940887, map_type="roadmap", zoom=13)
plot = gmap(key, map_options)
show(plot)
```

This does work:
```python
from bokeh.models import GMapOptions
from bokeh.plotting import show, gmap, output_notebook

output_notebook()
map_options = GMapOptions(lat=37.769183, lng=-122.3940887, map_type="roadmap", zoom=13)
plot = gmap(key, map_options)
show(plot)
```

#### Stack traceback and/or browser JavaScript console output
The funny thing is the few times that this works as expected in the original setting, there is an error in the JavaScript console:
```javascript
bokeh-0.12.5.min.js:35 Uncaught TypeError: Cannot read property 'maps' of undefined
    at e.r.GMapPlotCanvasView.e._build_map (bokeh-0.12.5.min.js:35)
    at e.r.GMapPlotCanvasView.e._map_hook (bokeh-0.12.5.min.js:35)
    at e.r.PlotCanvasView.e.render (bokeh-0.12.5.min.js:36)
    at n (bokeh-0.12.5.min.js:17)
```
All of the other times there is no error.

#### Screenshots or screencasts of the bug in action
works:
<img width="771" alt="screen shot 2017-04-27 at 7 21 30 pm" src="https://cloud.githubusercontent.com/assets/844306/25511893/dc17da30-2b7e-11e7-959d-9762aea0b569.png">

doesn't work:
<img width="771" alt="screen shot 2017-04-27 at 7 21 08 pm" src="https://cloud.githubusercontent.com/assets/844306/25511896/e1053880-2b7e-11e7-8f75-9dc75ed90328.png">

**Comment by bryevdv** [comment]
We will have to do some investigation to see what if anything can be done. The notebook environment puts up some constraints we have no control over. 

ping @mattpap

**Comment by mattpap** [comment]
@bryevdv, this looks like a bug introduced recently, but I didn't have chance to investigate this yet.

**Comment by bryevdv** [comment]
This was fixed at some point, the original "does not work" code works fine, including on cell or notebook re-executions
