### ISSUE TITLE
Issue with test build 0.12.6dev3 on Windows 7 with IE11

### ISSUE THREAD

**Issue by blacknapkins** [bokeh/bokeh#6212]
I encountered an issue with test build 0.12.6dev3 uisng IE11 on Windows 7 with Python 3.5.3

Using the code below from the User Guide Getting Started page.

```python
from bokeh.plotting import figure, output_file, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

# show the results
show(p)
```

Expected result
![good_simple_line](https://cloud.githubusercontent.com/assets/14756121/25532884/b87eca22-2c26-11e7-8621-1970f0430d70.PNG)

Actual result:

![bokeh_obj_doesnt_support](https://cloud.githubusercontent.com/assets/14756121/25532905/c5477902-2c26-11e7-8e34-a780bba03207.PNG)

In Chrome, with the above configuration, the result is as expected.

Build 0.12.6dev2 does not have this issue.

**Comment by mattpap** [comment]
@blacknapkins, can you provide output from IE's dev console, preferably full stack trace of this error if available?

**Comment by mattpap** [comment]
@bryevdv, can we use unminified resources for dev docs? This would allow me to debug more easily without rebuilding bokehjs on substandard platforms and users could provide more meaningful error reports.

**Comment by mattpap** [comment]
Or provide additional version of dev docs that are debugging friendly, because e.g. `safely()`, though user friendly, is a debugging nightmare.

**Comment by bryevdv** [comment]
sure probably, make an issue for it though

**Comment by blacknapkins** [comment]
@mattpap  I have the following. I am happy to provide more if you give me some pointers on how to.

console:
![ie_output_28_04_2017](https://cloud.githubusercontent.com/assets/14756121/25533743/858ed1b8-2c29-11e7-83a9-aee156f7c501.PNG)

call stack:

![call_stack_01](https://cloud.githubusercontent.com/assets/14756121/25533777/a6015628-2c29-11e7-83e7-ca06978401d1.PNG)

**Comment by mattpap** [comment]
@blacknapkins, thanks, though I already figured it out.

**Comment by bryevdv** [comment]
@mattpap if this is quick/easy please prioritize it or describe the fix. I'd like this to be in the next dev build.

**Comment by mattpap** [comment]
@bryevdv, unfortunately I was too fast saying I know what's going on here. After initial investigation I think that there's a bug in IE (a timing issue). Possibly removal of `delay()`s in PR #5976 caused this, but I didn't verify this yet.

**Comment by blacknapkins** [comment]
@mattpap I have produced more detailed stack traces for this bug.

IE 11

![ie_11](https://cloud.githubusercontent.com/assets/14756121/25842687/c4911724-349c-11e7-8143-d9f98b98382b.png)

Chrome

![chrome](https://cloud.githubusercontent.com/assets/14756121/25842696/cacd8140-349c-11e7-8f7d-f9ee2b170c12.PNG)


They appear to be identifical to the original ones in PR 6244. 
Therefore it Looks like the changes on branch mattpap/4153_signalling have resolved this issue.

I note that the changes in PR 6244 have a different issue that appears in IE 11 but not Chrome.

**Comment by mattpap** [comment]
IE doesn't support support `new Event()` constructor (which I use for finished rendering heuristic). In fact we don't need this in IE at all, so I can just put this code behind if-statement of try-catch.

**Comment by blacknapkins** [comment]
@mattpap Great, if you need me to do anything to test this at some point in the future let me know then.

**Comment by al6ayb** [comment]
Hi,
the issue of IE not supported still persists. Even on 0.12.6. Latest I could manage to produce working output on IE is on 0.12.6dev2

**Comment by bryevdv** [comment]
@al6ayb please do not spam old closed issues, it makes things much harder on us to distinguish what is truly new and what is not. If it turns out an issue is not new, we will mark as a dupe and reopen the old issue after that determination. Please open new issues with all the relevant info.

**Comment by bryevdv** [comment]
I should add, I did testing with Bokeh 0.12.6 on IE so information to reproduce will definitely be needed.

**Comment by blacknapkins** [comment]
I gave 0.12.6 a quick try with IE 11 with this example. It looks ok.
