### ISSUE TITLE
Button callback to select all checkboxes in CheckboxGroup does not work in Python 2.7.12

### ISSUE THREAD

**Issue by cbdelavenne** [bokeh/bokeh#6219]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Browsers:
- Firefox 53.0 (32-bit)
- Chrome Version 58.0.3029.81 (64-bit)

Python:
- `Python 2.7.12`
- `bokeh 0.12.5`

OS: Windows 10 Pro 64-bit 

#### Description of expected behavior and the observed behavior
Create a button to toggle a checkbox group (selecting and unselecting all checkboxes on button click).
Does not work on Python `2.7.12` with `bokeh 0.12.5`

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.io import show
from bokeh.layouts import widgetbox, row
from bokeh.models.widgets import Button, CheckboxGroup
from bokeh.plotting import curdoc, output_file

output_file("states.html", title="states")

states_list = ["Alabama", "Alaska ", "Arizona", "Arkansas", "California",
               "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
               "Hawaii", "Idaho ", "Illinois", "Indiana", "Iowa", "Kansas",
               "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
               "Michigan ", "Minnesota", "Mississippi", "Missouri", "Montana",
               "Nebraska", "Nevada ", "New Hampshire", "New Jersey",
               "New Mexico", "New York", "North Carolina", "North Dakota",
               "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island",
               "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah",
               "Vermont", "Virginia", "Washington", "West Virginia",
               "Wisconsin", "Wyoming"]

states = CheckboxGroup(
    labels=states_list,
    active=[0, 1])


def update():
    states.active = list(range(len(states_list)))

select_all = Button(label="select all")
select_all.on_click(update)

group = widgetbox(select_all, states)

layout = row(group)

curdoc().add_root(layout)
curdoc().title = "states"

show(layout)
```
Source: http://stackoverflow.com/a/39562653/295246

#### Stack traceback and/or browser JavaScript console output
No traceback and nothing of significance in the JS Console output.

#### Screenshots or screencasts of the bug in action
![select_all_bokeh](https://cloud.githubusercontent.com/assets/15895662/25580519/9c5c722e-2e4f-11e7-87cd-37a8e59c9a2d.gif)

**Comment by bryevdv** [comment]
@cbdelavenne thanks for the extremely detailed report! We will look at things as soon as we can (hopefully something simple). I've marked this as `plat:windows` for now as this code works for me on OSX

**Comment by danielluque13** [comment]
I have the same problem with a button and a bokeh serve, it simply does not work and Im in OSX too.

**Comment by bryevdv** [comment]
@danielluque13 many examples with buttons are tested regularly. Please always provide details (versions, etc), a complete code sample, and a description of how you run things. Otherwise there is nothing concrete we can investigate.

**Comment by DuCorey** [comment]
@cbdelavenne  I'm unable to replicate this bug on my windows machine. Can you confirm that you are using the Bokeh server to serve the file, i.e. running from the command line `bokeh serve --show select_all_states.py` where _select_all_states_.py is the file which contains your example code? From looking at your browser console output it doesn't seem to be like you are. You should see `[bokeh] Websocket connection 0 is now open` & `Bokeh items were rendered successfully`. Without running the Bokeh server you can't use just a python callbacks.

**Comment by bryevdv** [comment]
@DuCorey thanks for the good catch, I agree that this now seems like a usage error. (I missed also the `show` call in in the code sample).  I did fire up a VM to test this and when *run as a bokeh app* (i.e. *not* with just `python test.py`) things work:

<img width="705" alt="screen shot 2017-07-11 at 12 49 46" src="https://user-images.githubusercontent.com/1078448/28082248-93dea44e-6637-11e7-983a-78a105adbff2.png">

So I'm going to go ahead and close this. @cbdelavenne if you believe this is in error please re-open with additional information.
