### ISSUE TITLE
Add a `FilledArea` option to the Weather Server App example

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#6224]
It may be nice to apply `FilledArea`, from PR #6177, to the [weather](https://demo.bokehplots.com/apps/weather) example (though probably part of a different PR). It looks like for the [smoothed option](https://github.com/bokeh/bokeh/blob/master/examples/app/weather/main.py#L24-L27), the code is simply averaging, then using `quad` to draw lots of rectangles and would look better as a `FilledArea`.  I wonder if the "Actual" data shown using "discrete" would look worse if shown using 'FilledArea`.

What thoughts do people have about replacing some or all of the Weather example `quads` with `FilledArea`?  Or maybe add `FilledArea`/`quad` as another drop-down (I do not think it would not make much sense under Distribution drop-down)?

**Comment by bryevdv** [comment]
@StevenCHowell seems reasonable to me. I'd suggest keeping rects for the discrete and switching to filled area for the continuous. That way more things are demonstrated in one app. If you have time to work up a PR it would be very appreciated.

**Comment by bryevdv** [comment]
Will re-open if someone else wants to submit a PR
