### ISSUE TITLE
Discussion: Improvements to integration test infrastructure

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6231]
I wanted to start a discussion about the current status of integration testing. AFAICT, the current state is:

* ~10 hard-fail image tests covering annotations and bokeh.plotting things
* ~10 non-hard fail BokehJS examples
* a bunch of non-hard fail Bokeh file/server/notebook examples (server and notebook tests are currently broken and skipped)
* Semi-related, ~10 selenium-based, interaction tests

Improvements I think we could make
* Have hard-fail tests for all basic glyphs and layout-able models (grids, axes) with base screenshots in the repository (perhaps using the current `export` infrastructure).
* Add a lot more interaction tests related to tools, user callbacks, etc. I've also experimented with interaction tests for bokeh server examples (to test event passing) that seem valuable enough.

Questions:
* What are the concepts we need to be testing in the notebook? That they work (i.e. resources are loaded and the plot renders) and sizing modes? Anything else?
* What are the concepts we need to be testing in the server?
* Do we want to hard-fail on any examples tests? Which and why would that be?
* Do we want to stay on SauceLabs? Being stuck with Firefox 45 is suboptimal and with export capabilities and/or chrome headless, we may be able to move away from it.
* Mattpap mentioned wanted to start migrate interaction (selenium) tests to JavaScript. What's the benefit of doing that?

related:
#5800 
#5559

ping @mattpap @bryevdv

**Comment by mattpap** [comment]
> Mattpap mentioned wanted to start migrate interaction (selenium) tests to JavaScript. What's the benefit of doing that?

The fewer abstraction layers there are between a test and the tested code, the better chance that your actually tests something useful. Otherwise you may not know if there's a real bug in the library or abstraction layers are at fault. Obviously this doesn't mean we shouldn't tests those layers, but this has to be done with understanding, especially that bokehjs used via JSON protocol and JS API exhibit subtle changes in behavior.

**Comment by mattpap** [comment]
> Do we want to stay on SauceLabs?

As far as I remember, we were promised that we will be able to tests bokehjs on different platforms and web browsers regularly. For now this didn't happen, but we must have a way to test in all browsers we allegedly support. Optimally we should test a range of versions of each browser and provide a lower bound on what we fully support.

**Comment by canavandl** [comment]
>> Do we want to stay on SauceLabs?

>As far as I remember, we were promised that we will be able to tests bokehjs on different platforms and web browsers regularly. For now this didn't happen, but we must have a way to test in all browsers we allegedly support. Optimally we should test a range of versions of each browser and provide a lower bound on what we fully support.

Per the SauceLabs open source support page (https://saucelabs.com/open-source), we get 5 concurrent VMs to test on. We could greatly expand our testing on their infrastructure to include Windows/OSX and Chrome/IE/Safari.

**Comment by bryevdv** [comment]
> We could greatly expand our testing on their infrastructure to include Windows/OSX and Chrome/IE/Safari.

This would definitely be valuable, esp Windows/IE testing which right now is basically non-existent. It's also worth remembering that he current selenium tests have absolutely on occasion found serious problems that were not found in unit tests and would have gone into releases. 

> Being stuck with Firefox 45 is suboptimal and with export capabilities and/or chrome headless, we may be able to move away from i

is here any roadmap or statement from SL about possibly upgrading this version?

> What are the concepts we need to be testing in the notebook? That they work (i.e. resources are loaded and the plot renders) and sizing modes? 

There's plenty else but it would be incredibly valuable just to even get back to this point. 

> What are the concepts we need to be testing in the server?

It would be reassuring to do some basic UI interaction, slider scrubbing, etc. and verify that the expected synchronization is happening.
