### ISSUE TITLE
Bokeh plotting package does not show cached plots in jupyter notebook unless the bokeh import is above the first plot.

### ISSUE THREAD

**Issue by 00krishna** [bokeh/bokeh#6232]
Ran into an issue where Bokeh was not showing cached plots in the Jupyter notebook. So I have a jupyter notebook (notebook version 5.0.0) in which I have some bokeh plots. The notebook is pretty large now, so it does take a bit of time to load. Anyhow, when I was using Matplotlib the images in the notebook would be cached. That way I would not need to rerun them each time I ran the notebook.

Bokeh has the same ability to cache the images, but I could not seem to get the cached images to show up.  I was not even sure if the images were being cached.

I figured out the solution, and it might be a bug in the Bokeh system. So like many other folks I used the Jupyter notebook extensions, including the `initialization cells` extension. This extension allows me to run a set of cells as soon as a notebook opens. I keep my initialization cells as the very bottom of my notebook, because I don't want users to mess with the settings. So I had my Bokeh imports in an initialization cell at the very bottom of my notebook, but I had the bokeh plots higher up in my notebook. 

When I did this, the bokeh plots would not show cached images. I would have to rerun each plot, and then the plot displayed just fine. So by simply moving the bokeh imports above the first notebook plot cells I was able to resolve the issue and the cached plots all showed up. 

Here is an example:

If I had a plot earlier in the notebook:

```
from bokeh.sampledata.iris import flowers

colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'

p.circle(flowers["petal_length"], flowers["petal_width"],
         color=colors, fill_alpha=0.2, size=10)


show(p)
```
Then lower in an initialization cells I had

```
from bokeh.resources import INLINE
import builtins
import os, sys
import time
import pyugend
import datetime
from IPython.lib import deepreload
builtins.reload = deepreload.reload
from ipywidgets import widgets
from IPython.display import display
from bokeh.io import show, output_notebook
from bokeh.layouts import gridplot
from bokeh.palettes import Viridis3
from bokeh.plotting import figure
from bokeh.charts import defaults
from bokeh import mpl
defaults.width = 700
defaults.height = 700

output_notebook(resources=INLINE)
#output_notebook()
#notebook_handle=True
%reload_ext autoreload
time.sleep(1)
```
I am running ubuntu linux 16.04--though the problem also occurred on my partner's Macbook. I was using Chrome, but my partner uses both Chrome and Firefox. I am using Anaconda 4.3.17 x64 with bokeh version 0.12.4. The notebook is version 5.0.0.

**Comment by bryevdv** [comment]
Bokeh does not cache images. It always runs real JavaScript code to generate the plot on an HTML canvas. Because of this, it is absolutely necessary that BokehJS be loaded using `output_notebook` *before* any calls to `show`, etc. I don't see that there will ever be any way around this.
