### ISSUE TITLE
Fail gracefully when PR is submitted from a fork

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6240]
E.g. this https://travis-ci.org/bokeh/bokeh/jobs/229123339 appears to fail, but everything is OK, just upload is not possible. Solution, just don't upload. This seems like a regression, but I'm not sure.

**Comment by bryevdv** [comment]
I think this should be fixed but moving to `0.12.7` because of priority. The frequency of PRs from forks is low, and it also doesn't *actually* fail.

**Comment by mattpap** [comment]
> (...) it also doesn't actually fail.

Yeah, I didn't notice a the time that there was one actual failure. Still, knowing a PR is from a fork, we shouldn't attempt at uploading anything.

**Comment by bryevdv** [comment]
Agreed, just not as important as some other things first
