### ISSUE TITLE
Make radius dimension configurable for circles

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#626]
The notion of a "circle with radius" implicitly assumes 1-1 aspect ratio. If the aspect is not 1-1, the "proper" thing would be to draw ellipses. However, it is often desired to draw circles anyway, even with non 1-1 aspect As a practical matter we have to pick one dimension to measure screen distance along. Currently this dimension is fixed to be the `x` axis. Propose making the dimension configurable with a `radius_dim` parameter that takes the following values:
* `"x"` measure screen distance along x-axis
* `"y"` measure screen distance along y-axis
* `"min"` use min screen distance
* `"max"` use max screen distance

**Comment by damianavila** [comment]
status: low priority

**Comment by bryevdv** [comment]
Accidental push to master. Screenshot attached below (would have been in PR)

![screen shot 2015-02-09 at 11 18 41 am](https://cloud.githubusercontent.com/assets/1078448/6111346/c7f8b8f2-b04d-11e4-8525-892108b0d2f6.png)

**Comment by Venedictos** [comment]
Hello 

Please i intend to produce a bubble graph in Bokeh, but do not seem to find a way of supplying different values for size. A CDS with x,y and z columns. Have used p.circle(x,y, size=z, source=source), radius and radius_dimensions do not take a column. Any help please! Thanks
![image](https://user-images.githubusercontent.com/13404635/58475013-b66f0880-8144-11e9-878a-91ccddf9153e.png)

**Comment by bryevdv** [comment]
@Venedictos There are several ways to have many circles with different sized, but GitHub is not the appropriate place to ask suppose questions.  Please ask again on the [Bokeh Discourse site](https://discourse.bokeh.org)

**Comment by Venedictos** [comment]
@bryevdv thanks. I will. Cheers
