### ISSUE TITLE
Adding new sub-layouts fails to set documemt

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6261]
ref: #5856 

BOTH versions of @cutright code in the referenced issue "good" and "bad" do not work (for the same reason), namely, `.document` on the newly added layout is `null`

Hopefully this is just a small oversight, and making sure `document` is set on new models in `PATCH-DOC` updates is all that is needed

ping @mattpap 

<img width="1061" alt="screen shot 2017-05-08 at 17 49 16" src="https://cloud.githubusercontent.com/assets/1078448/25828628/d4dba1ca-3416-11e7-8ded-c146860d428f.png">

Here is the "good" version of the code without tabs (that is now also failing):
```
from bokeh.layouts import layout, row
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Select, Button, Tabs, Panel

from bokeh.plotting import figure
from bokeh.io import curdoc

source = ColumnDataSource(data={'x': [0, 1, 2, 3, 4],
                                'y': [0, 1, 4, 9, 16]})


def update():
    pass


def button_add_selector_row():
    layout_query.children.append(AddSelectorRow().row)


class AddSelectorRow:
    def __init__(self):
        self.select_category = Select(value="option1", options=["option1", "option2"])
        self.row = row([self.select_category])



# set up layout
plot = figure(plot_width=1000, plot_height=400)
plot.line('x', 'y', source=source)

# Set up initial buttons
main_add_selector_button = Button(label="Add Selector", button_type="default", width=400)
main_add_selector_button.on_click(button_add_selector_row)
layout_query = layout([[main_add_selector_button], [plot]])

curdoc().add_root(layout_query)

update()
```

The referenced issue has the other version (with tabs)

**Comment by mattpap** [comment]
This code has the last usage of document for layouting purpose, which I wasn't able to remove in PR #5976. So, although we should make sure that document is set properly (which I think it is eventually) and used only when available (which is likely the reason for failure), this code will be moved to the the view and use `is_root` to determine if a box is a root or not.

**Comment by bryevdv** [comment]
@mattpap please prioritize this and other layout issues ahead of any other work.
