### ISSUE TITLE
Task: Start testing and building for Python=3.6

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6266]
Task: Start testing and building for Python=3.6

**Comment by mattpap** [comment]
@canavandl, can you expand? We already test on 3.6, though we use 3.4 for examples, docs and integration tests.

**Comment by krishamehta** [comment]
@canavandl I can help if you can expand it more.

**Comment by canavandl** [comment]
You're right. I misread the Travis Matrix.
