### ISSUE TITLE
Why not pin latest tornado?

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#6271]
1. Create a new `conda` environment: `conda create -n foo jupyter python`
2. Activate `foo`
3. Run `conda install bokeh`

You get a downgrade warning. Why not pin the latest version of `tornado`?

```
The following NEW packages will be INSTALLED:

    bokeh:    0.12.5-py36_0
...

The following packages will be DOWNGRADED due to dependency conflicts:

    tornado:  4.5.1-py36_0  --> 4.4.2-py36_0

Proceed ([y]/n)? n
```

PS Which project owns `conda` packaging for `bokeh`?

**Comment by bryevdv** [comment]
@rs2 I am not sure what you are asking. Continuum Analytics is responsible for the contents of the conda `defaults` channel. When it became clear that the new version of tornado (released *after* the latest Bokeh release) was completely incompatible with Bokeh, I asked CIO to patch the dependency in `defaults` to exclude tornado 4.5 explicitly, which they did, and which explains the result you are seeing. What are you suggesting should be different?

**Comment by rs2** [comment]
`>> was completely incompatible with Bokeh`

Thank you, that is actually hugely helpful!

**Comment by bryevdv** [comment]
FYI the incompatibility has been resolved in master and dev builds, and the next release will support tornado 4.5
