### ISSUE TITLE
unexpected attribute 'lang' to CustomJS, possible attributes are args, code, js_callbacks, name or tags

### ISSUE THREAD

**Issue by LuckyGem** [bokeh/bokeh#6277]
when I try to run
checkbox.callback = CustomJS(args=dict(l0=l0, l1=l1, l2=l2, checkbox=checkbox),
                             lang="coffeescript", code="""
l0.visible = 0 in checkbox.active;
l1.visible = 1 in checkbox.active;
l2.visible = 2 in checkbox.active;
""")
error occurred: 
unexpected attribute 'lang' to CustomJS, possible attributes are args, code, js_callbacks, name or tags
May I know how to fix this? Thank you

**Comment by bryevdv** [comment]
The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).
