### ISSUE TITLE
documentation link not working right

### ISSUE THREAD

**Issue by TidyData** [bokeh/bokeh#6279]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
IE11 & Firefox

#### Description of expected behavior and the observed behavior
menu selection should not disappear so fast

#### Complete, minimal, self-contained example code that reproduces the issue
I click on the 0.12.5 number looking to get 0.12.4 documentation and the older revision list disappears too fast before I can click on it

#### Screenshots or screencasts of the bug in action
![image](https://cloud.githubusercontent.com/assets/22264476/25967252/6013c6f0-3642-11e7-9599-434d78195ea9.png)

**Comment by bryevdv** [comment]
I fixed this with a CSS update to the `bokehplots.com`
