### ISSUE TITLE
Implement TravisCI stages to improve CI builds

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6283]
TravisCI announced a new "Stages" feature:

https://blog.travis-ci.com/2017-05-11-introducing-build-stages

This allows for having some builds depend on an earlier one finishing first, as well as using artifacts from earlier builds warm a cache for subsequent builds. This should allow us to restructure out CI build in a way that only needs to do downloads, installs, and BokehJS builds one time. Also it might be possible for releases to have their own dedicate stage, which would probably be cleaner.

**Comment by mattpap** [comment]
Fixed by PR #6542.
