### ISSUE TITLE
Plot continues panning even when the pan tool is inactive

### ISSUE THREAD

**Issue by jlstevens** [bokeh/bokeh#6284]
The easiest way to reproduce this issue is to compare the docs for [0.12.4](http://bokeh.pydata.org/en/0.12.4/docs/user_guide/plotting.html):

<img src="https://cloud.githubusercontent.com/assets/890576/26038429/201f925c-3900-11e7-8791-e7ab6b2cb6ab.gif" width="300">

with the behavior of the same example in the [latest docs](http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html):

<img src="https://cloud.githubusercontent.com/assets/890576/26038431/22e378f0-3900-11e7-88da-f5328852c39b.gif" width="300">

As you can see in the second example, disabling the pan tool no longer seems to disable panning behavior (as it should).

**Comment by canavandl** [comment]
This was resolved in #6214 and should be available via the 0.12.6dev4 release. Please reopen this issue if you still experience the regression in master.

**Comment by jlstevens** [comment]
@canavandl Thanks for the heads up! I'll try the dev release to make double check it is working as expected.
