### ISSUE TITLE
Add migration note for removal of Document.resize()

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6287]
Apparently this was advertised and needs a replacement. This is a follow up on PR #5976.

**Comment by bryevdv** [comment]
@mattpap what is the status of this / what is the proper guidance for anyone that was using it?

**Comment by mattpap** [comment]
@bryevdv, I didn't write this yet. One should use `view.resize()` instead, or
```
for (var view_id in Bokeh.index) {
   Bokeh.index[view_id].resize()
}
```

**Comment by mattpap** [comment]
I added a note in PR #6384.
