### ISSUE TITLE
Browser rendering extremely slow when many figures in a gridplot

### ISSUE THREAD

**Issue by Boubsi** [bokeh/bokeh#6294]
Hi all,

when I have many figures in a gridplot, browsers take a very very long time to render the html file, even if the data is very small. 
For instance, when I run
```
import bokeh.plotting as bplt
import bokeh.io as bio
n_rows = 10
n_columns = 6
data_x = [1, 2, 3]
data_y = [1, 2, 3]
grid = []
for __ in range(n_rows):
    row = []
    for __ in range(n_columns):
        sub_fig = bplt.figure(width=200, height=100)
        sub_fig.line(data_x, data_y)
        row.append(sub_fig)
    grid.append(row)

fig = bplt.gridplot(grid)

bplt.reset_output()
bio.output_file('test.html')
bplt.save(fig)
```
and then open the 'test.html' file in a browser (firefox 53.0.2 or chromium 58.0.3029.96, on ubuntu 16.04 LTS), it takes 40 seconds to render, with 100 % use of one of my CPU (cf below)
![cpu_bokeh](https://cloud.githubusercontent.com/assets/28712155/26098160/1cd42450-3a27-11e7-9dae-58cb1691407e.jpeg)

Moreover, when the html file is open, the memory used increases by 400 Mo, even if the html file only weights 380 ko.

Do you know if there is a workaround for this problem? Maybe, this slowness is due to one special feature of bokeh, I could bypass?
Otherwise, is there a chance that bokeh will soon optimize the rendering of multiple plots? 
I would love to use bokeh in my project, but I need to make this kind of plots and the rendering time is two long.

Thank you for your work!

EDIT:  bokeh==0.12.5

**Comment by mattpap** [comment]
@Boubsi, which version of bokeh?

**Comment by bryevdv** [comment]
@Boubsi if you need 60 static plots, it's possible bokeh is not the right tool for you. The features for interactivity, streaming, layout, etc are not free, they come with trade-offs. Generally speaking, Bokeh is better with fewer plots, that each have more data, than it is with very many plots with a little data. It's possible there are optimizations we can make to improve things in some case but I expect this general statement will always be true to a degree. 

That said, the next release should have options for PNG and SVG export so perhaps Bokeh would be useful for generating static images ahead of time, that you can embed as images.

**Comment by Boubsi** [comment]
@mattpap: bokeh==0.12.5
@bryevdv: thank for the info. Indeed, maybe I will have to render my html files with matplolib + mpl3d (there is not such low rendering problems when many subplots are in stake), but the possibility to make a bokeh server would have been a great feature for my project in future...
A compromise would be to find a solution for the plots to be rendered successively instead of waiting that all plots are genereted before rending the all page (from the user point of view, it could be acceptable): do you think I would be possible to do that? Maybe by cutting my figure as several subfigures, generate html for each one of them and embed them some wrapper?

**Comment by bryevdv** [comment]
@Boubsi templating individual app elements individually is still an open feature request: 

https://github.com/bokeh/bokeh/issues/4986

There are other ways of splitting things up, and they might possibly be helpful, but it's hard to say anything specific without more details. However, this is venturing into the territory of "general support question" so I'd ask that the discussion continue on the mailing list, rather than the issue tracker:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by David-Herman** [comment]
@bryevdv Thank you for your response.

I am also working with Bokeh for use in a dashboard and can end up with 12-40 plots. So the use case of many plots is not uncommon. In my case specifically, I am using Tabs() to group the plots into groups. Perhaps modifying the default behavior to render only upon tab click per each tab would be helpful to decrease the initial page load time but still allow a user to serve additional plots per a single page load.

**Comment by Boubsi** [comment]
@David-Herman 
I want to try something like what you're suggesting, using a bokeh server and RadioButtonGroups. For instance, when a RadioButton is pushed, the data of the glyph's figure are replaced. Il hope it will allow me to reduce the number of figures, thus decreasing the initial page load.

**Comment by David-Herman** [comment]
@Boubsi 

In my case I am serving the content via Django. So I am outputting the div and script via components and then embedding them via the Django template for rendering into HTML.  I am considering using Bootstrap tabs in place of Bokeh and the wrapping the script within another script that runs on button press. I haven't yet prototyped this yet.

**Comment by jmc416** [comment]
bokeh==0.12.6
I have a similar use-case, and see slow loading times

**Comment by bryevdv** [comment]
@jmc416 as I stated above, Bokeh cannot satisfy every use case. It has made purposeful tradeoffs to cater towards very high interactivity. If you need 60 plots on a page ("similar to the OP") then Bokeh is probably not the right tool for your scenario.

**Comment by modulusmath** [comment]
At the risk of muddying the waters, I had the same issue but w/only 6 plots. At first it took about 1-3 second and then, it took about 90+ seconds (it did finish) to render what was once quick plotting. 

I didn't change anything in terms of the plotting BUT started to integrate pandas and other things in my script and probably fussed w/the packages. 

I really think my python packages got inconsistent (I had Ubuntu managed python3.x as well as an anaconda install). As I'm somewhat new to python so was just happy it was working paid no mind to the proper setup until it got slow. 

I only sorted out my issue after trying to sort out my packages when I also noticed I needed to do:

from bokeh.layouts import gridplot
instead of
from bokeh.io import gridplot

because I was also getting: ImportError: cannot import name 'gridplot' all of a sudden.

Probably my error but my (6 plots page) are super fast now (actually they seem even faster than when I started!)

Currently using 0.12.10 bokeh w/Spyder 3.2.4(Ananconda w/python 3.6) on Ubuntu  16.04.1 LTS  works great as well as the OS supplied python (which happens to be 3.5)

I realize the report is anecdotal as I didn't take detail notes as I was fumbling with my setup but I hope this may help.

**Comment by jmc416** [comment]
Thanks for your responses. I just wanted to mention that switching to a more powerful graphics card (GeForce GTX 960M from Intel skylake integrated graphics) reduces the load time from about >10s to <1s.

**Comment by synapticarbors** [comment]
Just ran into the same issue plotting the evolution of a bunch of parameters for an MCMC run. My use case involves line plots with 10-60 subplots, with 1-10 lines per plot, each with 100-1000 data points. I'm seeing load times of close to 60 seconds using Bokeh 0.12.4. 

Bokeh made it so easy to generate a really useful and beautiful visualization. I'm not sure what can be done about the performance piece, but wanted to add my voice to the crowd that would find it really useful to improve performance in this regime.

**Comment by mattpap** [comment]
> Bokeh 0.12.4

This is almost a year old version of bokeh. For a discussion about performance this needs to be the most recent one. A lot can change in a month and in a year we are speaking about quite different piece of software. Though, as other posts indicate, not that much changed with regards to multi-plot performance.

**Comment by mattpap** [comment]
So far we were able to reduce the rendering time of the original example by half (more or less). From here there is much room for improvement across bokehjs, and especially in layout subsystem, which currently dominates initialization time of a multiple plot system with small data size.

**Comment by intijk** [comment]
I have a image which is quite small, with RGB channel
```
croppedImage.shape
(30, 29, 3)
```
I use below code to draw it 
```
p = figure(plot_width=400, plot_height=400, match_aspect=True, output_backend="webgl")

for i in range(croppedImage.shape[0]):
    #for j in range(croppedImage.shape[1]):
    for j in range(29):
        c=tuple((croppedImage[i][j]*255).astype(int).tolist())
        p.rect(j,croppedImage.shape[0]-i,width=1, height=1, color=c)
show(p)
```

It would take more than 3 min to render the result. When `p.rect()` line is commend, it return instantly.

**Comment by mattpap** [comment]
@intijk, this is a different issue, and bokeh isn't optimized for this, but for having a single (or few) `p.rect()` (or other glyphs) with vectorized inputs. Additionally, `webgl` backend may heavily influence initialization time when a lot of glyphs are being used (see #4888).

**Comment by bryevdv** [comment]
@intijk to be more explicit, Bokeh glyphs are *vectorized*. It is always preferable and more performant e.g. to have *one* call to `rect` with a 100 rows of data (to draw 100 rects) than the converse (i.e. 100 calls to `rect`, that each draw only 1 rect). This is an explicit design choice and is unlikely to change.

**Comment by intijk** [comment]
@bryevdv then how to give those rect different colors?

**Comment by bryevdv** [comment]
@intijk please take support questions outside the tracker (i.e. to the public mailing list, or SO, or bitter) and also please refer to the docs as vectoring colors is one of the most fundamental things that is done in almost every published example e.g. https://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html#more-examples

**Comment by intijk** [comment]
Sorry for post to the wrong place, but anyway, thank you for the vectorization suggestion. It improved the performance a lot.

**Comment by gblack686** [comment]
Just started using Bokeh and love it. I'm experiencing these same load time issues and wondering if the plot points (glyphs) are the main reason for the lag or if other parts of the code will inhibit performance at similar rates.

**Comment by bryevdv** [comment]
@gblack686 one reason for slow performance with many figures was that we had been using a constraint based solver for computing overall layout. While it was an attractive idea for several reasons, it also had serious drawbacks. It is being removed in #8085 and replaced with a much simpler and faster layout system. So basically: stay tuned for upcoming developments.

**Comment by bryevdv** [comment]
I upped this to 150 plots with #8085 and it ran and rendered in about 3 seconds on my macbook

**Comment by soerendip** [comment]
Same problem.

**Comment by bryevdv** [comment]
@soerendip Then my best guess without more information is that you need to update your Bokeh version to 1.1 or newer (please always, always include version information up front)
