### ISSUE TITLE
Surface3d reference to vis.js missing

### ISSUE THREAD

**Issue by florence8627** [bokeh/bokeh#6298]
The following error is showing when trying to run the surface3d example 

**Error rendering Bokeh items  ReferenceError: vis is not defined**

I think the link to the vis.js is missing in the html.
Adding the following in initialize in surface3d.coffee solved the problem

    url = "https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.min.js"

    script = document.createElement('script')
    script.src = url
    script.async = false
    script.onreadystatechange = script.onload = () => @_init()
    document.querySelector("head").appendChild(script)

**Comment by bryevdv** [comment]
This example is working fine for me, and the HTML file already includes that script:

  https://github.com/bokeh/bokeh/blob/master/examples/app/surface3d/templates/index.html#L27

More information is needed.

**Comment by bryevdv** [comment]
@florence8627 can you provide more information? All the things that were asked in the issue template, basically: bokeh and OS and browser versions, how you installed, what exact command you ran, etc.

**Comment by florence8627** [comment]
Bokeh: 0.12.4-22-g665c397
Browser: Firefox 52.1.1 32bit
OS: windows 8
Command used: bokeh serve --show  app/surface3d/main.py
![error](https://cloud.githubusercontent.com/assets/5196058/26228324/307620ce-3c7c-11e7-86ea-82ed80bf2e3c.jpg)

I know vis.js is referenced in index.html, but it just seems that doesn't get added...I checked it in the inspector. Is there anything I did wrong here ?

**Comment by bryevdv** [comment]
> Bokeh: 0.12.4-22-g665c397 
 
@florence8627 This is very unusual. Can you described how you've installed Bokeh? It appears you are running off a random Git commit that's not even a dev build tag

**Comment by florence8627** [comment]
Possibly through "conda install bokeh". 
But I just removed the old bokeh package (0.12.4-22-g665c397), installed a new version
"0.12.6dev5"
The problem remains.
The example code are from checking out the git repo

**Comment by bryevdv** [comment]
@florence8627 it's not possible to have conda installed (or pip installed) a bokeh that would report a version like that. That format of version string can *only* come from an install from a source install from a Git repository. 

In any case `0.12.6dev5` is working for me on OS X on Safari, FF and Chrome:

<img width="963" alt="screen shot 2017-05-18 at 23 58 56" src="https://cloud.githubusercontent.com/assets/1078448/26233859/05e51ef6-3c26-11e7-9129-04382c425bce.png">

So it's possible this is a windows specific problem. I don't have a windows VM handy though, so it will probably next week before I can try to reproduce on windows.

**Comment by bryevdv** [comment]
I am unable to reproduce a problem on windows, and there has been no update. I do still believe this was an installation or system problem of some sort. Please feel free to re-open if a reproducible sequence can be provided with recent bokeh versions

**Comment by deets** [comment]
Just a quick note, because I stumbled over this: it happened for me under Linux (bokeh server 0.13.0). The root cause was me passing the python-file to bokeh serve --app, instead of just the directory surrounding it. This works for "normal" graphs, but apparently dealing with template-overrides doesn't work in that case.

**Comment by bryevdv** [comment]
@deets that is expected and documented behavior. Directory format apps afford extra features, but have to be run using the directory. There is a loud warning about this as well:
```
(base) ❯ bokeh serve surface3d/main.py
/Users/bryanv/work/bokeh/bokeh/command/util.py:91: UserWarning:
It looks like you might be running the main.py of a directory app directly.
If this is the case, to enable the features of directory style apps, you must
call "bokeh serve" on the directory instead. For example:

    bokeh serve my_app_dir/

If this is not the case, renaming main.py will supress this warning.
```
