### ISSUE TITLE
Sample code DateGapTickFormatter doesn't work on version 0.12.5, with python 3.5.2 platform.

### ISSUE THREAD

**Issue by doncat99** [bokeh/bokeh#6299]
with the sample code custom_datetime_axis.py in the example->plotting->file folder, I can't remove date gaps still.

**Comment by bryevdv** [comment]
With 0.12.5 that example is working as expected an intended. If you are saying that it does something different than what you want, that is a general support questions. General support questions should not go in the issue tracker, they should go in the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
