### ISSUE TITLE
Zeppelin - bokeh0.12.6dev fails to load js and css

### ISSUE THREAD

**Issue by paramdutta** [bokeh/bokeh#6305]
Trying to use bokeh 0.12.6dev with Zeppelin 0.7.1 to tryout the Zeppelin support.

jconsole shows that the following resources are not accessible:
https://cdn.pydata.org/bokeh/dev/bokeh-0.12.6dev5+7.ge73da3e21.min.js
https://cdn.pydata.org/bokeh/dev/bokeh-0.12.6dev5+7.ge73da3e21.min.css

Source code:
```python
import numpy as np

import bokeh

from bokeh.layouts import row, widgetbox
from bokeh.models import CustomJS, Slider, MultiSelect
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.embed import file_html
from bokeh.resources import CDN

bokeh.io.reset_output()

x = np.linspace(0, 10, 500)
y = np.sin(x)

source = ColumnDataSource(data=dict(x=x, y=y))

plot = figure(y_range=(-10, 10), plot_width=400, plot_height=400)

plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)

callback = CustomJS(args=dict(source=source), code="""
    var data = source.data;
    var A = amp.value;
    var k = freq.value;
    var phi = phase.value;
    var B = offset.value;
    x = data['x']
    y = data['y']
    for (i = 0; i < x.length; i++) {
        y[i] = B + A*Math.sin(k*x[i]+phi);
    }
    source.trigger('change');
    run
""")

amp_slider = Slider(start=0.1, end=10, value=1, step=.1,
                    title="Amplitude", callback=callback)
callback.args["amp"] = amp_slider

freq_slider = Slider(start=0.1, end=10, value=1, step=.1,
                     title="Frequency", callback=callback)
callback.args["freq"] = freq_slider

phase_slider = Slider(start=0, end=6.4, value=0, step=.1,
                      title="Phase", callback=callback)
callback.args["phase"] = phase_slider

offset_slider = Slider(start=-5, end=5, value=0, step=.1,
                       title="Offset", callback=callback)
callback.args["offset"] = offset_slider

multi_select = MultiSelect(title="Option:", value=["foo", "quux"],
                           options=[("foo", "Foo"), ("bar", "BAR"), ("baz", "bAz"), ("quux", "quux")])
layout = row(
    widgetbox(multi_select),
    widgetbox([amp_slider, freq_slider, phase_slider, offset_slider]),
    plot
)

output_notebook(notebook_type='zeppelin')
show(layout)
```

**Comment by canavandl** [comment]
@paramdutta How did you install Bokeh?

I'm surprised that it's trying to load from https://cdn.pydata.org/bokeh/dev/bokeh-0.12.6dev5+7.ge73da3e21.min.js and not https://cdn.pydata.org/bokeh/dev/bokeh-0.12.6dev5.min.js

If you built from master, you'll have to set a ``BOKEH_RESOURCES=inline`` environmental variable to load from your local build. Otherwise, you can install from conda: ``conda install -c bokeh/label/dev bokeh=0.12.6dev5``

**Comment by mattpap** [comment]
> I'm surprised that it's trying to load from

This is because the version contains `+` in place of `-` in some case (like here):
```
0.12.6dev5+7.ge73da3e21.min.js
         ^^^
```
and code in `bokeh.resources` works only with `-`. I already encountered this problem once and had to modify bokehjs to accept `+` as well. @paramdutta, what platform do you use?

**Comment by mattpap** [comment]
> ```
> source.trigger('change');
> run
> ```

On an unrelated note `run` isn't defined anywhere and you should update this code to `source.change.emit()` (this is new in 0.12.6-dev).

**Comment by bryevdv** [comment]
> This is because the version contains + in place of - in some case (like here):

This is the versioneer output, the `+7.ge73da3e21` means 7 commits after the `0.12.6dev5` tag, with the hash `ge73da3e21`. Which is fine, we don't upload CDN resources for every build so this version does not need to conform to CDN naming conventions. 

Also FWIW I think this could only ever happen by running off master

**Comment by mattpap** [comment]
>  Which is fine, we don't upload CDN resources for every build so this version does not need to conform to CDN naming conventions.

But we have code in `bokeh.resources` for dealing with dev versions and even warning users that using CDN resources in such scenario likely won't work. This only works with dashes in version string. Why sometimes versions are reported with `+`? In my opinion this is a bug and either we should use canonical version strings everywhere or accept `+` and `-`, as bokehjs does.

**Comment by bryevdv** [comment]
I'd *much* prefer to make our `resources` code understand standard versioneer strings for versions off master, than to custom patch versioneer to do something different than it normally does.

**Comment by bryevdv** [comment]
e.g. we can certainly drop anything everything after `+` and that would be simple to to. But should come with a loud warning, as there will never be a guarantee that such a configuration will actually work.

**Comment by paramdutta** [comment]
@canavandl 
What is the pip equivalent for conda install -c bokeh/label/dev bokeh=0.12.6dev5?
Thanks

**Comment by bryevdv** [comment]
http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

**Comment by paramdutta** [comment]
@bryevdv 
Thanks. I simply downloaded the gz file and pip installed it. It worked. I will try out complex examples next.

@canavandl, @mattpap 
Thanks.

Since I am not looking at building bokeh as such, this issue resolved for me.
