### ISSUE TITLE
Bug: hover_text displays extra values for Donut chart

### ISSUE THREAD

**Issue by jvivian** [bokeh/bokeh#6307]
Ideally I'm just doing something wrong, but after looking at several examples and ensuring my dataframe format is correct, I think I'm encountering a bug.  Regardless, Bokeh is an awesome package so thanks for all the great work!

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

- Python (2.7.11)
- bokeh (0.12.5)
- jupyter (1.0.0)
- jupyter-client (4.2.2)
- jupyter-console (4.1.1)
- jupyter-core (4.3.0)
- jupyterthemes (0.15.4)
- pandas (0.18.1)
- Mac OS Sierra (Version 10.12.4)
- Google Chrome Browser (58.0.3029.110)

#### Description of expected behavior and the observed behavior
- Expected Behavior: hover_text in `Donut` plot should show one value
- Observed Behavior: hover_text shows multiple values, all zero except for one row. The inner-circle of the Donut correctly shows one value, while the outer layer shows multiple rows.

#### Complete, minimal, self-contained example code that reproduces the issue
```python
import pandas as pd
from bokeh.charts import Donut, show

tissues = ['adrenal', 'bladder', 'breast', 'cervix', 'colon', 'esophagus', 'kidney', 
           'liver', 'lung_adenocarcinoma', 'lung_mesothelioma', 'lung_squamous', 'ovary', 
           'pancreas', 'prostate', 'skin', 'head_and_neck', 'stomach', 'testis', 
           'thyroid', 'uterus_carcinosarcoma', 'uterus_endometrioid']
tcga_t = ['77', '407', '1092', '303', '287', '181', '530', '369', '513', '87', '498', 
          '420', '178', '494', '102', '1040', '413', '148', '504', '57', '180']
tcga_n = ['0', '19', '113', '3', '41', '13', '72', '50', '59', '0', '50', '0', '4', 
          '51', '1', '88', '36', '0', '59', '0', '23']
gtex = ['125', '9', '178', '10', '140', '379', '27', '110', '287', '287', '287', '88', 
        '165', '100', '556', '556', '173', '165', '278', '78', '78']

tc = pd.DataFrame()
tc['counts'] = [int(x) for x in gtex + tcga_t + tcga_n]
tc['dataset'] = ['gtex' for _ in xrange(len(gtex))] + \
                ['tumor' for _ in xrange(len(tcga_t))] + \
                ['normal' for _ in xrange(len(tcga_n))]
tc['tissue'] = tissues * 3

# Bokeh plot
d = Donut(tc, label=['dataset', 'tissue'], values='counts', text_font_size='6pt', hover_text='counts')

show(d)
```

#### Screenshots or screencasts of the bug in action
![screen shot 2017-05-18 at 4 07 29 pm](https://cloud.githubusercontent.com/assets/7576256/26227096/280a1248-3be5-11e7-85c3-f2c2ea9d6586.png)

![screen shot 2017-05-18 at 4 07 48 pm](https://cloud.githubusercontent.com/assets/7576256/26227099/2cf2f1da-3be5-11e7-8e4d-b5a3924f6a3b.png)

**Comment by bryevdv** [comment]
HI, `bokeh.charts` have moved to a new separate repo and projects. All issues should go here:

https://github.com/bokeh/bkcharts
