### ISSUE TITLE
Sliders :: CustomJS Can Not Dynamically Change Title

### ISSUE THREAD

**Issue by covelloz** [bokeh/bokeh#6308]
@mattpap 

Sorry to keep bothering about sliders! Not sure if this is a bug or just simply not implemented.
I can dynamically update the callback object's start, end, & value attributes as I please in JS and I see the updates visually. However, the **title** attribute doesn't seem to want to update visually. The actual object value does change; I have confirmed by using console.log()

    reset_output()
    output_file("slider_callback.html")
    callback_slider = CustomJS(code = '''
        console.log(cb_obj.title);
        if (cb_obj.value == 0) {
           cb_obj.title = "foo";
        }
        else {
            cb_obj.title = "bar";
         }  
       cb_obj.trigger('change');
    ''')
    slider = Slider(start = 0, end = 1, value = 0, step = 1, title = "YOU SHALL NOT CHANGE ME!")
    layout = column(slider)
    show(layout)

**Comment by mattpap** [comment]
Title is rendered only during initialization of `Slider`.

**Comment by mattpap** [comment]
> `cb_obj.trigger('change');`

This line is unnecessary. The only reason to use this is when mutable data structures are involved and you modified data first and then attempted to assign a property. In such scenario new data is equal to old data (modification in-place) and no change signals are emitted. This is a common occurrence with `ColumnDataSource.data` property.

**Comment by covelloz** [comment]
Thanks Matt! I think making the Title attribute be mutable would be a good feature until nouislider or something similar is fully implemented. It would give users the ability to use the slider to display dynamic string values which can be [ad hocly] used for dates, categories, etc. Also, being able to _hide_ or _unhide_ the value attribute would be awesome. For example

Something like:
```
 slider = Slider(start = 0, end = 1, value = 0, step = 1, hidden_value=True, title = "")
```

**Comment by mattpap** [comment]
Currently it's possible to hide value when `title = None`.

**Comment by mattpap** [comment]
>  I think making the Title attribute be mutable would be a good feature (...)

All properties are mutable and bokehjs is supposed to act when their values change. However, it's a common occurrence that particular models don't listen to change signals or their rendering logic is flawed (as it is with `Slider`, which listens properly, but doesn't render).

**Comment by bryevdv** [comment]
@mattpap do you have a branch for this already that's just not pushed? If not I will move it to `0.12.7`

**Comment by jdsalmonson** [comment]
I just stumbled on this bug: my Slider( ... , title = "foo", ..), using a CustomJS callback, will only display the title with the initial slider value; it won't update along with the slider.  As mentioned above, setting title = None removes the title entirely, which is at least not wrong.  I'm using bokeh 1.4.0 and python 3.7.6.  Is there a plan to fix this?

**Comment by bryevdv** [comment]
@jdsalmonson you have to set `plot.title.text`. Passing `title` to `figure` is a convenience for creating and configuring a `Title` object (which has a `text` attribute that is the real source of truth).
