### ISSUE TITLE
reopen jupyter notebook only show the last figure 

### ISSUE THREAD

**Issue by sshuair** [bokeh/bokeh#6312]
before close the jupyter notebook file :
<img width="1030" alt="2017-05-21 10 29 15" src="https://cloud.githubusercontent.com/assets/5787131/26284780/80a08efe-3e75-11e7-872d-233b6c435181.png">

then I close the `Untitled.ipynb` and reopen it. it shows:
<img width="1000" alt="2017-05-21 10 29 35" src="https://cloud.githubusercontent.com/assets/5787131/26284789/b039b5fa-3e75-11e7-8e6a-d43e2ef2820b.png">

the first figure do not plot , only show ` Loading BokehJS ...`  
I have tried plot three and four figures , and it comes the same result. Only the last plot correct, other only show ` Loading BokehJS ...`  
is this a bug or some setting can slove it ?

**Comment by bryevdv** [comment]
`output_notebook` and `show` both rely on the notebooks cell publishing machinery, and putting them in the same cell can cause them to interfere with each other. Always put `output_notebook` as the last thing in a cell near the top of your notebook.

**Comment by sshuair** [comment]
It works. Thanks!!! 👍
