### ISSUE TITLE
HeatMap Issue

### ISSUE THREAD

**Issue by albspe** [bokeh/bokeh#6314]
I have Python 3.4.3 and installed Bokeh (0.12.5) and Pandas (0.20.1). I am trying to use HeatMap without success:

I tried the following:
```
from bokeh.charts import HeatMap, output_file, show

# (dict, OrderedDict, lists, arrays and DataFrames are valid inputs)
data = {'fruit': ['apples']*3 + ['bananas']*3 + ['pears']*3,
        'fruit_count': [4, 5, 8, 1, 2, 4, 6, 5, 4],
        'sample': [1, 2, 3]*3}

hm = HeatMap(data, x='fruit', y='sample', values='fruit_count',
             title='Fruits', stat=None)

output_file('heatmap.html')
show(hm)
```
and I get the following error:

```
AttributeError: 'pandas._libs.interval.Interval' object has no attribute 'split'
```
I have seen the same issue reported by others, but no solutions. Any idea?

**Comment by albspe** [comment]
Tried to reinstall some of the packages. Now the error is:

```
ValueError: Binned colors can only be created for one column of                                  numerical data.

```

**Comment by bryevdv** [comment]
`bokeh.charts` has moved to a new separate project and repo, all new issues should go here:

https://github.com/bokeh/bkcharts

I will mention, however, that the very recent pandas 20.1 introduced a breaking API change. As `bkcharts` does not really have a maintainer at the moment, your best options are to stick with pandas 0.19.1 or to use the stable `bokeh.plotting` API instead

**Comment by albspe** [comment]
Thanks!!!
