### ISSUE TITLE
Bug in ScreenDistanceSpec serialization

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#6316]
Unfortunately I haven't been able to create a small reproducible example for this issue but I think I've tracked down why it occurs. The specific error I'm referring to is this:

>ValueError: expected an element of either String, Dict(Enum('field', 'value', 'transform'), Either(String, Instance(Transform), Float)) or Float, got {'units': 'screen', 'field': 'size'}
 
The traceback mentions this line:

```python
def to_serializable(self, obj, name, val):
    d = super(ScreenDistanceSpec, self).to_serializable(obj, name, val)
    d["units"] = "screen" <----
    return d
```

The issue appears to be that in descriptors.py the container object is passed through to be serialized:

```python
self.property.to_serializable(obj, self.name, getattr(obj, self.name))
```

And the ``DataSpec.to_serializable`` just passes the container object through without making a copy, which means ScreenDistanceSpec tries to directly modify the container triggering the ValueError. The error occurs in 0.12.6dev{4, 5} but not 0.12.5. I'll continue trying to make a minimal example as currently I can only trigger it with a holoviews gridplot of scatter points.

**Comment by mattpap** [comment]
>  but not 0.12.5

btw. Last commit (57068d6) that touches this code was merged in 0.12.4.

**Comment by philippjfr** [comment]
Thanks, I'll do a bisection to figure out the actual source of the issue then.

**Comment by bryevdv** [comment]
I think having the superclass always  return a new dict is reasonable. There is one branch where it is not doing that:

https://github.com/bokeh/bokeh/blob/master/bokeh/core/properties.py#L1489

There also seems to be a branch that could return `None` (at the top) not sure if that's actually not a real concern in practice or if it should be guarded against in subclasses.

Can you make a PR for this and test it out?
