### ISSUE TITLE
DeprecationWarnings on Python 3.6

### ISSUE THREAD

**Issue by pitrou** [bokeh/bokeh#6317]
We get the following deprecation warnings in our CI jobs:
```
distributed/bokeh/tests/test_scheduler_bokeh.py::test_simple
  /home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/bokeh/util/callback_manager.py:19: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    return getargspec(callback.func)

distributed/bokeh/tests/test_scheduler_bokeh.py::test_TaskProgress_empty
  /home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/bokeh/core/property/bases.py:173: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
    return new == old
```

Bokeh version is 0.12.5.

**Comment by pitrou** [comment]
Another one:
```
  /home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/bokeh/core/json_encoder.py:52: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
    NP_EPOCH = np.datetime64('1970-01-01T00:00:00Z')
```

**Comment by bryevdv** [comment]
Code for `NP_EPOCH` has already changed in master. I'm pretty overwhelmed atm so a small PR for the others would be appreciated.

**Comment by mattpap** [comment]
> `inspect.getargspec()` is deprecated, use `inspect.signature()` or `inspect.getfullargspec()`

What about 2.7? Clearing this deprecation means we will need to use different approaches for different Python versions, which is manageable if hidden behind an utility function.

**Comment by bryevdv** [comment]
> What about 2.7? Clearing this deprecation means we will need to use different approaches for different Python versions, which is manageable if hidden behind an utility function. 

Absolutely true that a version check is unavoidable now, +1 to defining an internal `getargspec` that hide the check.

**Comment by bryevdv** [comment]
@pitrou As far as I have been able to determine, there is absolutely no "correct" way to generically  compare two arrays that might be type incompatible, that does not generate that future warning when they are type incompatible. I thought that was the purpose of `array_equal` but it also raises the warning. I have filed the issue https://github.com/numpy/numpy/issues/9210 but would not expect anything to change anytime soon. I think you will just have to live with this for now, or precondition your usage to avoid changing dtypes

**Comment by pitrou** [comment]
> there is absolutely no "correct" way to generically compare two arrays that might be type incompatible

What do you call "type incompatible"? Please post an example of what you mean.

**Comment by bryevdv** [comment]
It's in the issue I linked

**Comment by bryevdv** [comment]
Tho I just realized your message above is actually different from the FutureWarning. But I've tried to update the `matches` function and it causes other tests to fail. 

I would have thought this:

```
            if new is None or old is None:
                return new is old

            if isinstance(new, np.array) and isinstance(old, np.array):
                return np.array_equal(new, old)

            if isinstance(new, np.array) or isinstance(old, np.array):
                return False

            return new == old
```

would be equivalent to 
           if new is None or old is None:
                return new is old
           else:
                 return new == old
``` 
but apparently not

**Comment by pitrou** [comment]
Well, `np.array` isn't a class, you want `np.ndarray`.

**Comment by pitrou** [comment]
Also, you don't need the `None`-specific code, as `None` behaves normally with equality.

**Comment by bryevdv** [comment]
!!! grrr...

The `None` is to avoid the FutureWarning when possible:
```
In [37]: a == None
/Users/bryan/anaconda/bin/ipython:1: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  #!/Users/bryan/anaconda/bin/python
```

**Comment by pitrou** [comment]
But how can you get a comparison to None since you are already excluding ndarrays in the if statements above?

**Comment by pitrou** [comment]
Let's sum it up:
```python
>>> def eq(new, old):
...:    if isinstance(new, np.ndarray) and isinstance(old, np.ndarray):
...:        return np.array_equal(new, old)
...:    if isinstance(new, np.ndarray) or isinstance(old, np.ndarray):
...:        return False
...:    return new == old
...:
>>> a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> a = np.arange(9)
>>> b = a + 1
>>> eq(a, b)
False
>>> eq(a, None)
False
>>> eq(None, b)
False
>>> eq(5, 6)
False
>>> eq(5, 5.0)
True
```

**Comment by pitrou** [comment]
Great :-)

**Comment by bryevdv** [comment]
Actually I think just this will do:
```
if isinstance(new, np.ndarray) or isinstance(old, np.ndarray):
            return np.array_equal(new, old)

        return new == old
```
since there is no future warning in this case:
```
In [45]: np.array_equal(a, None)
Out[45]: False
```
