### ISSUE TITLE
Weird behavior when you pass less colors than points

### ISSUE THREAD

**Issue by mcsalgado** [bokeh/bokeh#632]
In this code I'm plotting 100 points but I specified just 7 colors:

```python
import numpy as np
from bokeh.plotting import *
output_notebook()

x = range(100)
y = range(20)*5
radii = [2]*100
colors = ('#000', '#f00', '#0f0', '#00f', '#aaa', '#ff0', '#0ff')

circle(x,
       y,
       radius=radii,
       fill_color=colors,
       line_color=None)

show()
```
![canvas](https://cloud.githubusercontent.com/assets/1109234/3000240/21ebd9a8-dd21-11e3-8380-5dae929a31a9.png)

This mistake can be very subtle to notice if you're dealing with lots of points and colors. It'd be nice if bokeh warned the user instead of just silently doing this weird thing.

**Comment by birdsarah** [comment]
closed via #2470 - see demo of error here: http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/tests/632_wierd_behavior_when_less_colors_than_points.ipynb
