### ISSUE TITLE
Remove CSS 'bk-' prefixing

### ISSUE THREAD

**Issue by uberscientist** [bokeh/bokeh#6332]
While working on issue #4503 I agreed that attempting to remove the "bk-" CSS prefix would help because of how jquery-ui widgets generate elements and how _prefix_ui in bokeh was being implemented and used.

There's worry this may cause breakages for people using the bk- prefixed stylesheets/code and there will be the need for a deprecation release.

**Comment by bryevdv** [comment]
ping @mattpap I know you've been thinking of this, I requested this issue so we could discuss it. Now that everything is under a `bk-root` element, can we just remove the prefix? There is definitely potential for breakage if anyone was styling using the `bk-` prefix selectors. But we haven't ever really demonstrated that so I'm not sure that practice is widespread.

**Comment by mattpap** [comment]
`bk-root` only protects the hosting web page from being polluted by bokeh, but not bokeh being affected by the web page. At this point I don't see a way to reliably support prefixing and I think it will be easier for both sides to just remove them. I would like to go one step further and remove jquery and jquery-ui altogether and let users provide them. This will significantly reduce widgets bundle and won't penalize users wanting only basic widgets like buttons or forms.

**Comment by mattpap** [comment]
Actually, removal of prefixes implies removal of jquery-ui and this implies removal of jquery. This is good, just a lot more work.

**Comment by bryevdv** [comment]
@uberscientist as I suspected, this task needs a more involved discussion. Would you be interested in a different task? Specifically, would you want to look at fixing the Datepicker by replacing it entirely with a lightweight one that has no JQ dependency? This one:

https://github.com/dbushell/Pikaday

looks fairly promising but there might be others to consider

**Comment by bryevdv** [comment]
Just for later reference, as of `0.12.6`, here are the things that depend on jqui
```
models/widgets/autocomplete_input.coffee:
models/widgets/cell_editors.coffee:
models/widgets/data_table.coffee:
models/widgets/date_picker.coffee:
models/widgets/range_slider.coffee:
models/widgets/slider.coffee:
```
And these are the ones that depend only on standard JQ
```
models/widgets/cell_formatters.coffee:
models/widgets/checkbox_button_group.coffee:
models/widgets/checkbox_group.coffee:
models/widgets/dropdown.coffee:
models/widgets/jqueryable.coffee:
models/widgets/radio_group.coffee:
models/widgets/tabs.coffee:
```

**Comment by mattpap** [comment]
@bryevdv, more representative is this:
```
$ git grep -l '\$el' bokehjs/src/coffee/models/widgets/
bokehjs/src/coffee/models/widgets/abstract_button.coffee
bokehjs/src/coffee/models/widgets/autocomplete_input.coffee
bokehjs/src/coffee/models/widgets/cell_editors.coffee
bokehjs/src/coffee/models/widgets/checkbox_button_group.coffee
bokehjs/src/coffee/models/widgets/checkbox_group.coffee
bokehjs/src/coffee/models/widgets/date_picker.coffee
bokehjs/src/coffee/models/widgets/date_range_slider.coffee
bokehjs/src/coffee/models/widgets/div.coffee
bokehjs/src/coffee/models/widgets/dropdown.coffee
bokehjs/src/coffee/models/widgets/input_widget.coffee
bokehjs/src/coffee/models/widgets/jqueryable.coffee
bokehjs/src/coffee/models/widgets/markup.coffee
bokehjs/src/coffee/models/widgets/multiselect.coffee
bokehjs/src/coffee/models/widgets/panel.coffee
bokehjs/src/coffee/models/widgets/paragraph.coffee
bokehjs/src/coffee/models/widgets/pretext.coffee
bokehjs/src/coffee/models/widgets/radio_button_group.coffee
bokehjs/src/coffee/models/widgets/radio_group.coffee
bokehjs/src/coffee/models/widgets/range_slider.coffee
bokehjs/src/coffee/models/widgets/selectbox.coffee
bokehjs/src/coffee/models/widgets/slider.coffee
bokehjs/src/coffee/models/widgets/tabs.coffee
bokehjs/src/coffee/models/widgets/text_input.coffee
bokehjs/src/coffee/models/widgets/toggle.coffee
bokehjs/src/coffee/models/widgets/widget.coffee
```
which means everything under widgets uses jquery.

**Comment by mattpap** [comment]
Also bootstrap's components would have to be rewritten, which is the biggest pain, because otherwise I was able to clean up 80% of our widgets in under an hour.

**Comment by bryevdv** [comment]
perhaps https://github.com/thednp/bootstrap.native

**Comment by uberscientist** [comment]
"Actually, removal of prefixes implies removal of jquery-ui and this implies removal of jquery."

I don't see this line of reasoning, but I'll run with it.

I can see how the libraries are bloated relative to how the project uses them... the native bootstrap seems like it could work too. As I consider the future I ask: will bootstrap.native keep up with bugfixes, or will we be happy forking it ourselves if the maintainer goes MIA? Or will we end up spending more time swapping twitter bootstrap back in 2 years from now?

Anyway, I'm down to integrate pikaday! I'll give it a shot on another branch, while doing the prefix removal I found some overzealous substitution that probably needs fixing (or just replacing with native bootstrap): https://github.com/bokeh/bokeh/blob/9650b109b62d385d372eecc1f9d5a511bf4a3d49/bokehjs/src/vendor/bootstrap-3.1.1/less/mixins.less#L307

**Comment by mattpap** [comment]
> I don't see this line of reasoning, but I'll run with it.

The reason for the implication is that everything bokehjs adds to DOM is under `.bk-root` element. However, jquery-ui adds stuff to DOM on its own where ever it pleases. This way, if we provide jquery-ui and user doesn't, then things still don't work, because jquery-ui styling isn't applied outside `.bk-root`. This situation is similar to what we have now, just less severe. Alternatively, if we provide jquery-ui and user provides one, then we have two, possibly and likely conflicting versions. The best approach is to allow users configure this on their own and let bokehjs assume existence of globally available jquery-ui. This way we don't penalize users who don't want complex widgets. This approach is still suboptimal, because of lack of package management (version control) in web browsers. Our preference is to provide everything bokehjs, at least core bokehjs, needs on our own, so that we have complete control of all dependencies.

**Comment by mattpap** [comment]
> As I consider the future I ask: (...)

We already use very outdated dependencies (like bootstrap or jquery-ui) due to prefixing, so switch to bootstrap.native wouldn't change much. However, we use only button, dropdown and tabs from bootstrap, and my plan is to just integrate necessary parts of those components directly into bokehjs and maintain the code on our own. We really don't want dependency on bootstrap and it was a big mistake (though an understandable one) to do so.

**Comment by uberscientist** [comment]
Makes sense! Thanks for taking the time to explain.

I'm ready to work on the pikaday integration, but was wondering if I should wait until other things get settled.

If we're dropping jQuery we should still have a `$` selector function like this right? https://gist.github.com/ofca/5577178

Last week I removed all the bk- prefixes (save for bk-root) and the tests pass, I'm not sure if I should just ditch that since @mattpap was making blazing fast progress on (80% under an hour) and start working from wherever we're at now.

Let me know!
