### ISSUE TITLE
MultiSelect freezes IE 11 on change

### ISSUE THREAD

**Issue by decatur** [bokeh/bokeh#6333]
When changing the selection on a MultiSelect widget, IE11 dies.

```
from bokeh.plotting import curdoc
from bokeh.models.widgets import MultiSelect

def change_callback(attr, old, new):
    print(new)
    
select = MultiSelect(title='Select source', value=['a'], options=['a','b'])
select.on_change('value', change_callback)
curdoc().add_root(select)
```
Bug confirmed with Bokeh 0.12.4 and IE11.0.9600. change_callback handler is called once (['b'] is printed), then IE hangs. No problem with Select-Widget (single).
See also https://stackoverflow.com/questions/41839541/bokeh-multiselect. A related issue could be https://github.com/bokeh/bokeh/issues/5832.

**Comment by bryevdv** [comment]
@decatur can you test `0.12.5`, and ideally with a `0.12.6` dev build? Dev builds are easily installable:

http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

Can you verify this problem is limited to IE11 and not other browsers?

**Comment by bryevdv** [comment]
For reference I cannot reproduce any problem with either of those on OSX/Safari.

**Comment by blacknapkins** [comment]
I have tried the given example on Win 7 IE 11 with the same issue; a crash occurs after the ['b'] is printed. I used Bokeh 0.12.6dev6. 
Chrome and Firefox do not display this behaviour.
The IE 11 JS console does not display any information prior to the crash occurring. 

With IE 11 connected I get the following output every so often, which may or may not be connected.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\bok_0_12_6dev6\lib\site-packages\bokeh\ser
ver\views\ws.py", line 167, in on_pong
    self.latest_pong = int(codecs.decode(data, 'utf-8'))
ValueError: invalid literal for int() with base 10: ''
2017-05-29 18:43:48,447 received invalid integer in pong b''

**Comment by bryevdv** [comment]
@blacknapkins thanks for the update. It's unfortunately probably too late to do anything about this for `0.12.6` but I have slated it for a look for the following release. 

FYI AFAIK the message about the pong is annoying, but harmless. We've not been able to track down a solid repeatable test case for it but it never seems to interfere with expected behavior either.

**Comment by blacknapkins** [comment]
@bryevdv  thanks for the info wrt the pong, I had a vague memory of seeing that somewhere but couldn't find it when I had a quick look.

**Comment by decatur** [comment]
Yes, we have the exact same symptoms as @blacknapkins observes. Because he did already test against the dev build, I will refrain (sitting behind a not so cooperative corporate firewall). 
Btw, corporate policies often dictate the deployed browser, which also often is IE exclusively.

**Comment by bryevdv** [comment]
The code above now works on Win 10 / IE 11 with 1.1.0dev9, so I will close this. Can re-open if a problem persists and can be made reproducible
