### ISSUE TITLE
Feature request: configurable maximum upload size for Tornado server

### ISSUE THREAD

**Issue by bkueng** [bokeh/bokeh#6338]
I'd like to lift the default maximum Tornado upload size of 100MB. This requires adding a limit to [server.Server](https://github.com/bokeh/bokeh/blob/master/bokeh/server/server.py#L85), which then passes it to [tornado.httpserver.HTTPServer](https://github.com/bokeh/bokeh/blob/master/bokeh/server/server.py#L131) as `max_buffer_size=`.

**Comment by bryevdv** [comment]
@bkueng I'd be happy to accept a PR that makes this parameter configurable.

**Comment by bkueng** [comment]
Ok, I'll do that
