### ISSUE TITLE
Move canvas2svg to separate optional bundle

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6345]
Move canvas2svg to optionally loaded bundle (like webgl)

**Comment by birdsarah** [comment]
I ran examples/howto/layouts/dashboard.py with the bollinger plot set to svg output_backend.

The patch bleeds outside the plot area. Maybe this is captured by an above point, but I thought I'd mention it.
![screen shot 2017-05-30 at 7 20 41 pm](https://cloud.githubusercontent.com/assets/1796208/26610445/1ff83666-456d-11e7-8bd2-e4f6d88ac274.png)
![screen shot 2017-05-30 at 7 20 28 pm](https://cloud.githubusercontent.com/assets/1796208/26610450/2246f092-456d-11e7-9cb8-21d6828ac801.png)

**Comment by mattpap** [comment]
canvas2svg was integrated into bokehjs' core in PR #10402.
