### ISSUE TITLE
Possible issue with 0.12.6dev6 incompatible scale and range

### ISSUE THREAD

**Issue by blacknapkins** [bokeh/bokeh#6346]
I am experimenting with bkcharts BoxPlot. I encounter a possible problem with 0.12.6dev6 when I try the standard example below in the user manual

```python
from bokeh.charts import BoxPlot, output_file, show
from bokeh.layouts import row
from bokeh.sampledata.autompg import autompg as df

box = BoxPlot(df, values='mpg', label='cyl', title="Auto MPG Box Plot", plot_width=400)
box2 = BoxPlot(df, values='mpg', label='cyl', color='cyl',
               title="MPG Box Plot by Cylinder Count", plot_width=400)

output_file('box.html')
show(row(box, box2))
```

With 0.12.4 and 0.12.6dev3 (Chrome only as IE11 has issues with this) the display is as the user manual.

With 0.12.6dev6 I get the following output

E-1009 (INCOMPATIBLE_SCALE_AND_RANGE): A Scale is incompatible with one or more
ranges on the same plot dimension: incompatibility on x-dimension: FactorRange(i
d='46bd3843-bd2e-4746-b34e-e29ec300a369', ...)/LinearScale(id='4375fca0-19df-48f
8-b19e-e89de0837ee0', ...) [Chart(id='28ec8b99-553a-4d32-a76d-5a12d1b5c72c', ...
)]
E-1009 (INCOMPATIBLE_SCALE_AND_RANGE): A Scale is incompatible with one or more
ranges on the same plot dimension: incompatibility on x-dimension: FactorRange(i
d='8a1b9155-d635-4bcd-a2ed-f7e32bc8bce7', ...)/LinearScale(id='50272b26-f291-428
1-8d11-1e091ad4034b', ...) [Chart(id='8edfacbd-b285-4e73-b244-a5646500c05f', ...

Chrome and IE11 display an associated error as below
```
Bokeh Error
Range FactorRange is incompatible is Scale LinearScale
```

I have tried importing from bokeh.charts and bkcharts with no difference found.

I am on Windows 7 with python 3.5

**Comment by bryevdv** [comment]
@blacknapkins thanks for the report however this should go in https://github.com/bokeh/bkcharts

**Comment by blacknapkins** [comment]
Ooops, I'll put it there.
