### ISSUE TITLE
Layouts with multiple Tab widgets don't work

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6348]
Layout with multiple Tab widgets don't work. The second tab widget isn't rendered and only the first plot in that widget is rendered, while the other plots are hidden in the DOM.

reproducible with examples/models/files/glyphs.py example

Bokeh=0.12.6dev6
Chrome 58
Python 3.5

**Comment by mattpap** [comment]
This was fixed in PR #7008.
