### ISSUE TITLE
How to set up a server on Heroku using Bokeh 

### ISSUE THREAD

**Issue by anto0084** [bokeh/bokeh#6353]
Hey fellow coders! 
I'm new to python and to bokeh, but for the purpose of my project I'm required to set up a Heroku server with Bokeh. However it seems to be harder than it should be. 

The farthest I got was using the 'heroku open' command on the shell and the website tries to load it until it get the error 'timed out':

<img width="1103" alt="screen shot 2017-05-31 at 10 40 21 am" src="https://cloud.githubusercontent.com/assets/14222863/26637488/9a327312-45ed-11e7-9e07-038a3d9d3407.png">

**according to Heroku console the build succeeded but the app times out. 

This is my Procfile setup btw:
`web: bokeh serve --port=$PORT --host=frozen-ocean-13783.herokuapp.com --host=* \
     --address=0.0.0.0 --use-xheaders bokeh_example_app.views.py'

and my requirements.txt:

_appdirs==1.4.3
appnope==0.1.0
bleach==2.0.0
bokeh==0.12.5
certifi==2017.4.17
cffi==1.9.1
chardet==3.0.3
conda==4.3.16
cryptography==1.7.1
cycler==0.10.0
decorator==4.0.11
Django==1.11.1
entrypoints==0.2.2
gunicorn==19.7.1
html5lib==0.999999999
idna==2.5
ipykernel==4.6.1
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
MarkupSafe==1.0
matplotlib==2.0.2
mistune==0.7.4
nbconvert==5.2.1
nbformat==4.3.0
notebook==5.0.0
numpy==1.12.1
packaging==16.8
pandas==0.19.2
pandas-datareader==0.2.1
pandocfilters==1.4.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.17
Pygments==2.2.0
pyOpenSSL==16.2.0
pyparsing==2.2.0
python-dateutil==2.6.0
pytz==2017.2
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.3.0
requests==2.17.3
requests-file==1.4.1
simplegeneric==0.8.1
six==1.10.0
terminado==0.6
testpath==0.3.1
tornado==4.5.1
traitlets==4.3.2
urllib3==1.21.1
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==2.0.0
whitenoise==3.3.0_

and my project folder structure:

<img width="487" alt="screen shot 2017-05-31 at 10 37 44 am" src="https://cloud.githubusercontent.com/assets/14222863/26637355/45a8816a-45ed-11e7-8f1e-6ae451676b26.png">

I tried majority of the answers online for this issue however nothing helped, please help.

**Comment by bryevdv** [comment]
There are several resources online now, including this recent blog post:

https://samirak93.github.io/analytics/Deploy-bokeh-server-plots-using-heroku.html
