### ISSUE TITLE
Continuous colors in bokeh.charts.scatter

### ISSUE THREAD

**Issue by tweeter0830** [bokeh/bokeh#6355]
Is there a way to plot a continuous color on a scatter plot using the charting interface?

This is a very common thing to do in scientific and engineering plots, but it looks like the chart interface only plots by unique values.

[https://matplotlib.org/examples/shapes_and_collections/scatter_demo.html](See this for an example matplotlib plot)

**Comment by bryevdv** [comment]
The `bokeh.charts` API has split off into a new separate project and repo. All new issues should go there:

https://github.com/bokeh/bkcharts

Additionally, general support questions should go to the mailing list, not issue trackers:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
