### ISSUE TITLE
Task: Add support for bokeh.io.export to StringIO or BytesIO

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6360]
Instead of only writing to a file location, add support for bokeh.io.export to StringIO or BytesIO object.

**Comment by nanvel** [comment]
```
from bokeh.embed import file_html
from bokeh.resources import CDN

...

html = file_html(
    column(...),
    resources=CDN
)
```

**Comment by bryevdv** [comment]
Users can use `get_screenshot_as_png` to get an image object instead of writing a file
