### ISSUE TITLE
Customize warning formatter

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#6362]
I'm trying out the imminent bokeh release with the dask dashboard.  I get hundreds of lines like the following:

```python
/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/bokeh/models/sources.py:91: BokehUserWarning: ColumnD)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
```

Clearly I'm doing something wrong in my code, and it's great to know about it.  However, two things would make this nicer:

1.  Getting some sort of information about the cause of the failure.  It looks like an informative error message was attempted, but rather than getting a nice result I get the code instead.
2.  These are filling up my terminal at the rate that I update my plots.  It might be nice to only warn once or twice.

**Comment by bryevdv** [comment]
@mrocklin are you saying there is not an accompanying line that *does* have the formatted message?

**Comment by mrocklin** [comment]
That is correct.  I just get those two lines repeated.

**Comment by bryevdv** [comment]
@mrocklin I'm at a bit of a loss, I would expect this:
```
In [1]: from bokeh.models import ColumnDataSource

In [2]: source = ColumnDataSource(data=dict(a=[1], b=[1,2]))
/Users/bryan/work/bokeh/bokeh/models/sources.py:91: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('a', 1), ('b', 2)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
```

As you can see this is identical to yours, except your output has truncated the line that has the actual information in it. The "extra" line with the code is alway how I've seen `warnings.warn` work, I also think its annoying but am not aware of any way to turn it off. Is there something that could be truncating your log lines on your end?

**Comment by bryevdv** [comment]
Re: the "code" the only solution seems to be to monkey patch the `warnings` module, which I would not be in favor of:

https://stackoverflow.com/questions/2187269/python-print-only-the-message-on-warnings

**Comment by bryevdv** [comment]
@mrocklin I am definitely in favor of making the output prettier (i.e. not include the line of code for the warning itself, which is pretty useless). I suspect the truncation is somehow a problem on your end, though. 

I am -0.5 on rate limiting the warning. Ragged column lengths is a serious usage error, and has been a support burden for us for years. The warning is meant to be annoying, very annoying.

**Comment by mrocklin** [comment]
OK, yes, I've verified that something on my end was squashing that bit of the warning message.  It's somewhat odd that only part of the message came through, but given that I'm doing weird things this probably isn't worth diving into further.  

On the plus side I've now resolved the underlying issue on my end that was creating the warnings, so that's a plus :)

**Comment by bryevdv** [comment]
I've changed the task to reflect the part that seems reasonable (a better formatter for warnings)

**Comment by mattpap** [comment]
I would like to add this particular warning is a warning for users' convenience, so that a lot of broken code didn't just suddenly stop working. This will be changed to an exception at some point (pre-1.0 I presume).
