### ISSUE TITLE
ImageRGBA error during change events

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#6365]
Since https://github.com/bokeh/bokeh/pull/6313 was merged there is an error in the ``ImageRGBA._set_data`` method where it is being passed two copies of the source. This means that the ``indices``variable incorrectly refers to the source resulting in an error on this line

```coffeescript
if indices? and indices.indexOf(i) < 0
```

    Exception in Comm callback TypeError: e.indexOf is not a function

because the source does not have an ``indexOf`` method. I haven't tried reproducing this using bokeh server yet but here is a minimal example to reproduce this in the notebook:

```python
    from __future__ import division
    
    import numpy as np
    
    from bokeh.plotting import figure, show, output_notebook
    from bokeh.io import push_notebook
    from bokeh.models import ColumnDataSource
    
    output_notebook()
    
    N = 20
    img = np.empty((N,N), dtype=np.uint32)
    view = img.view(dtype=np.uint8).reshape((N, N, 4))
    for i in range(N):
        for j in range(N):
            view[i, j, 0] = int(i/N*255)
            view[i, j, 1] = 158
            view[i, j, 2] = int(j/N*255)
            view[i, j, 3] = 255
    
    p = figure(x_range=(0,10), y_range=(0,10))
    
    cds = ColumnDataSource(data=dict(image=[img]))
    
    # must give a vector of images
    p.image_rgba(image='image', source=cds, x=0, y=0, dw=10, dh=10)
    
    handle = show(p, notebook_handle=True)  # open a browser
    
    img[:20, :20] += 10
    cds.data['image'][0] = img
    push_notebook(handle=handle)
```

Tested on: bokeh 0.12.6dev7

**Comment by bryevdv** [comment]
@philippjfr can you try to make a server version? It is vastly harder to debug BokehJS in the notebook.

**Comment by philippjfr** [comment]
Sure I'll try, I am somewhat suspecting the server may not be affected though, since that has been tested by others recently.

**Comment by philippjfr** [comment]
Okay I was wrong, server is also affected, here is the example:

```
from __future__ import division

import numpy as np
    
from bokeh.plotting import figure
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
    
N = 20
img = np.empty((N,N), dtype=np.uint32)
view = img.view(dtype=np.uint8).reshape((N, N, 4))
for i in range(N):
    for j in range(N):
        view[i, j, 0] = int(i/N*255)
        view[i, j, 1] = 158
        view[i, j, 2] = int(j/N*255)
        view[i, j, 3] = 255
    
p = figure(x_range=(0,10), y_range=(0,10))
    
cds = ColumnDataSource(data=dict(image=[img]))
    
# must give a vector of images
p.image_rgba(image='image', source=cds, x=0, y=0, dw=10, dh=10)

def cb():
    img[5:10, 5:10] += 1
    cds.data['image'] = [img]

doc = curdoc()
doc.add_root(p)
doc.add_periodic_callback(cb, 500)
```

**Comment by bryevdv** [comment]
@mattpap here is the proximate cause of this problem:

<img width="949" alt="screen shot 2017-06-01 at 09 52 47" src="https://cloud.githubusercontent.com/assets/1078448/26685564/2040da6c-46b0-11e7-8223-dc42c257b289.png">

is there an implicit signature for all slot callbacks? The signature for this set data is:
```
set_data: (request_render=true, indices) ->
```
so given how the `emit` code works this seems to have only ever worked by accident. What exactly should all callbacks look like?

**Comment by mattpap** [comment]
@bryevdv, I presume this
```
bokehjs/src/coffee/models/renderers/glyph_renderer.coffee:    @connect(@model.data_source.change, @set_data)
```
is the true offending line. It's almost always wrong to connect slots like this because methods like `set_data()` aren't intended to be used as callbacks and it's really hard to maintain function signatures. Previously it worked, because `sender` wasn't added at the end of argument list of a slot.Things worked by coincidence. The proper solution is to provide explicit callback instead of just `@set_data`, i.e.:
```
@connect(@model.data_source.change, (request_render) -> @set_data(request_render))
```
It doesn't matter if you use `->` or `=>`. `this` will be maintained anyway, because this uses `@connect()`. The story would be different if the above connection was established as in:
```
@model.data_source.change.connect((rr) => @set_data(rr))
```
Then `=>` is obligatory.

**Comment by mattpap** [comment]
> `set_data: (request_render=true, sender, indices)`

Yeah, but we don't want to maintain `sender` all across the API, especially that `sender` is unrelated to `set_data()`'s logic.

**Comment by mattpap** [comment]
Actually this:
```
@connect(@model.data_source.change, (request_render) -> @set_data(request_render))
```
is also wrong, because `change` signal is of void type, so doesn't emit any arguments. The original code was doubly lucky, because first it used `undefined` for  `indices` and second it used `undefined` for `request_render`, which gives `set_data(undefined)` -> `set_data()` -> `set_data(true)` given how default arguments are implemented in translation to ES5.

**Comment by mattpap** [comment]
Also, now I think I made a mistake with including sender in `emit()`, given that bokehjs is full of those ill-defined callbacks. By mistake I mean I should have added it later and fixed all slot connections first.

**Comment by mattpap** [comment]
Also, as soon as TS will be fully on-board, such errors won't be possible anymore and one would get nice error messages about differing signatures.

**Comment by mattpap** [comment]
Also, previously we had even worse bugs, e.g. `@connect(@model.change, @plot_view.request_render)` (assuming `@ != @plot_view`), which resulted in mismatched `this` and, to my big surprise, didn't fail immediately.

**Comment by mattpap** [comment]
@bryevdv, I submitted I PR (#6373).

**Comment by bryevdv** [comment]
@philippjfr this should be fixed in master now
