### ISSUE TITLE
Proposing a Bokeh Draw tool

### ISSUE THREAD

**Issue by caffeine-potent** [bokeh/bokeh#6370]
Code  would work like this   
 
```
ds = ColumnDataSource({'x': [], 'y': []})  
tool = DrawTool(source = ds, x = "x", y = 'y') 
my_plot.add_tools(tool)  

```  
The draw tool draws points on your plot.  A column data source of your choice is updated with the position of these dots. The point placement/min-resolution is dependent on your zoom level.    
  
An example that can be used in the documentation would be drawing points and fitting lines/curves to those points.   
  
Does anyone here have the patience to walk me through the development of this tool? I would like to start contributing other tools in the future.

**Comment by bryevdv** [comment]
ping @philippjfr @jlstevens

**Comment by jlstevens** [comment]
@caffeine-potent Definitely sounds very similar to a tool we are currently working on. @philippjfr from the description, do you think this fits into our plans for editing related tools?

**Comment by philippjfr** [comment]
Yes, we're building a tool just like that, which will be part of a bigger suite of drawing and editing tools. Our DrawTool will probably be slightly more general letting us draw both points and lines. We'll make sure to keep you updated on our progress.

**Comment by caffeine-potent** [comment]
@philippjfr   
Thanks for the response.  
Do you have any notes on your plans for the drawing or editing tools?

**Comment by jlstevens** [comment]
@caffeine-potent The general plan is to write a number of tools that are broken up along two axes: a specification of *what* you are editing and then the type of action (insert, draw, move vertex etc). Then we have a plan to group these tools together into more powerful and general tools that merge the individual functionalities together.

**Comment by caffeine-potent** [comment]
@jlstevens   
Thanks for the response! I'm really looking forward to this! 

 As for this issue. I'm not certain yet about GIT etiquette yet. Should this remain an open issue until the feature in question is released?

**Comment by bryevdv** [comment]
Yes I think so, @jlstevens @philippjfr maybe a wiki page working document to discuss an outline requirements would be good? 

FYI @caffeine-potent just to set expectations, both Bokeh and HV are in the middle of getting releases out next week so there probably won't be much activity (even discussion) until after then.

**Comment by jlstevens** [comment]
> Yes I think so, @jlstevens @philippjfr maybe a wiki page working document to discuss an outline requirements would be good?

Good idea!

> FYI @caffeine-potent just to set expectations, both Bokeh and HV are in the middle of getting releases out next week so there probably won't be much activity (even discussion) until after then.

I do hope to have a rough prototype to show before then, even with the HoloViews release to work on. I'll keep you updated!

**Comment by LinuxChristian** [comment]
Hi Guys,

I am also working on a project where this feature would be great.
Do you have a rough estimate of when you might release this? And perhaps a link to the wiki page?

**Comment by jlstevens** [comment]
@LinuxChristian 

We recently completed a prototype of one of these tools and we should now be able to make rapid progress on the remaining draw/edit functionality. It should be available for testing in a PR soon - hold on a little longer and you'll be able to try it out!

**Comment by busino** [comment]
That sounds perfect. 

I have a project where I plan to use **bokeh** to draw on a photo-image.
The end-user should be able to mark POIs (Points of interest) with a circle-glyph.
The functionality should be _insert_, _drag_ and _delete_ these points.  
Drawing a line and dragging the end-points would be great too.

I'm looking forward to test or contribute to this feature.

**Comment by LinuxChristian** [comment]
That sounds great! I ended up hacking together a quick polygon creation and editing tool through the powerful CustomJS functionality but would prefer a build in solution. Looking forward to testing it.

**Comment by ShivaSmith** [comment]
Hi.. any updates on the DrawTool?  To be able to click and drag: points, lines, rect's, poly's would be super useful!!  I'd be happy to help test.  Thanks!

**Comment by philippjfr** [comment]
[Here](https://anaconda.org/philippjfr/drawing_tools/notebook) are demos of my current prototypes.  I hope to meet @bryevdv next week to figure out if and how we can get them into bokeh and discuss how to improve them. There's still quite a bit of iteration on the UI and various features to do.

**Comment by ShivaSmith** [comment]
Thanks very much for posting your demos!  I'll definitely check them out.  

Glad to see progress continuing on these vital features!  It will be really great to see them integrated into Bokeh.

**Comment by ShivaSmith** [comment]
Hi @philippjfr, when I run your notebook I'm seeing:

```
----> 7 from earthsim.tools import (attach_vertex_editing, CDSStream, save_shapefile,
      8                             attach_box_drawing, attach_point_add, attach_poly_drawing)
      9 

ModuleNotFoundError: No module named 'earthsim'
```

I searched everywhere I could think of for earthsim (GitHub, Google, pypi, etc.) but couldn't seem to find it.  I think I have all the other packages your notebook references installed ok.

I found a reference to EarthSim here -- https://github.com/conda/conda/issues/5867
it references: https://github.com/ContinuumIO/EarthSim/issues/80

But https://github.com/ContinuumIO/EarthSim no longer exists... ;) :).

Can I get it from somewhere?  :)... Thanks!

**Comment by busino** [comment]
@philippjfr 

Thanks for sharing your example.

Would be great to get access to the sourcecode of the magical `EarthSim` package.

**Comment by bryevdv** [comment]
Unfortunately EarthSim is client work, we are unable to share it.

**Comment by philippjfr** [comment]
Right, for now I can't share it, in future EarthSim will be open-source, but all the tools work should migrate out of there to some upstream package anyway.

**Comment by busino** [comment]
Hmmm...

What are the plans? 
When can we expect to get something (in a release or sample code)?

For me it would be great to get some example code as a starting point for implementing a _DrawTool_.

My deadline is end of this year to have a working _Web-DrawTool_.
I'm really interested in using or implementing it with **bokeh** and not with other js/canvas toolkits.

In my case I only have **points** and **lines** (defined by 2 points).

If you have a look what google-maps is providing for geometry generation:
* **Marker**
  * Point Glyph
* **Draw a line**
  * Line (2Points)
  * Line Multiple Points
  * Polygon (Multiple Points, Closed)

For the User-Interaction it would be great to have simple drag and drop possibilities for the given points.

My suggestion is to have a **Edit-Mode** that enables _inserting, editing_ and _deleting_ geometry items.

## Edit-Mode

### Create
_OnClick_ create point
_OnDoubleClick_ finish creation
_OnClick_ on _start-point_ create a polygon

### Edit

Markers/Points/Line-Points are highlighted when hovering. 
On Click-Down the point can be moved. 
On Click-Up the Point is placed on the new position. 

Lines are highlighted when hovering
On Click-Down the whole line/polygon can be moved. 
On Click-Up the Point is placed on the new position. 

### Delete

Select Geometry _OnClick_
Press _Delete_ geometry is deleted

Delete of sub-entities (points, lines) of a geometry is not clear to me.


Thanks for your feedback.

**Comment by busino** [comment]
@philippjfr 
What is the best way to start implementing a Point Editor like this:
http://mpld3.github.io/examples/drag_points.html
- Drag Points
+ Insert New Points
+ Delete Points
Do you have some code snippets around that you can share?

What about #7149, is there some example code around?

Would be great to get some _Kick-Off-Code_.

**Comment by busino** [comment]
Hui,
I have a small example setup:
Notebook: https://gist.github.com/busino/649924470274059094064b2ccef97faf
Script: https://gist.github.com/busino/7f59c8c03e13c62983090722dc5de40e
It's a little bit hacky.
I would prefer to have the possibility to hover a point and drag without clicking the point for selection and click again for release.
Any hints are welcome how to improve such a Labeling-App, Yes it's used to identify frog individuals....

**Comment by philippjfr** [comment]
https://github.com/bokeh/bokeh/pull/7415 adds an initial set of drawing/editing tools along with some documentation on how to use them. The current tools include:

* BoxDrawTool: Allows drawing, dragging and deleting ``Rect`` glyphs on one or more renderers

* PointDrawTool: Allows adding, dragging and deleting point-like glyphs (of ``XYGlyph`` type) on one or more renderers

* PolyDrawTool: Allows drawing, selecting and deleting ``Patches`` and ``MultiLine`` glyphs on one or more

* VertexEditTool: Allows editing the vertices of one or more ``Patches`` or ``MultiLine`` glyphs and if enabled allows dragging and deleting entire lines or polygons.

If anyone has got some time to test these or have suggestions about naming, UI or API that would be very helpful. We're hoping to merge these asap.

**Comment by bryevdv** [comment]
Im going to go ahead and close this by #7415 Any future work should go in separate focused issues.
