### ISSUE TITLE
Feature request: Rotation

### ISSUE THREAD

**Issue by tobsecret** [bokeh/bokeh#6378]
When making circular plots like in http://circos.ca/, using Arc and AnnularWedge glyphs is quite handy. However, users often want to rotate the plot around the center of the coordinate system.
Now of course one can write an update function and connect it to a slider but a rotation tool that does not require communication with the server would be preferable.

Could look something like this:
```
plot = figure()
rotate = RotationTool(x=0, y=0)
plot.add_tools(rotate)
```

It would disable panning and show a hand instead of the cursor that upon click onto a point of the plot would let you rotate what is displayed in the plot relative to the x and y coordinates specified in the RotationTool() instance.
![feature request bokeh rotation tool](https://cloud.githubusercontent.com/assets/10303623/26757604/8d4ad870-488f-11e7-9322-95dcc4ef0152.png)

**Comment by bryevdv** [comment]
It's definitely possible to create a tool to do this right now, as an extension to Bokeh:

http://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html

I am slightly inclined to think that for a specialized tool like this, that that is in fact the best approach. BokehJS is already a fairlylarge library as JavaScript libraries go, and the goal right now is really to make BokehJS smaller, not bigger. So we have to consider careful when adding new code, whether it is something that will be valuable to the majority of users.

**Comment by tobsecret** [comment]
Thanks for the consideration. I will hit up the mailing list then!

**Comment by bryevdv** [comment]
Going to go ahead and close this. I have not perceived a strong general demand so I continue to thing a custom tool is the way to go.

**Comment by rigidlab** [comment]
@tobsecret Did you end up writing an custom RotationTool ? 

Thanks

**Comment by tobsecret** [comment]
No, I am no longer working on this project.
