### ISSUE TITLE
Support line annotations like span but with slope

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#6386]
In addition to the vertical and horizontal spans annotations, it would be nice to have a line annotation that can be sloped and can be specified by a point and a slope (or maybe optionally two sets of points which might be more useful if an axis is categorical), where the line does not terminate but continues across the extent of the canvas.

The reason for this request is that it is often desired to place a reference line or a fitted regression line that is not horizontal or vertical, and it is desired for this line to continue beyond the span of the data, or the span of the data is not known at the time of specifying the line, or it is not convenient to specify the line in terms of points to connect at the extent of the data. Especially in the case of superposing a linear regression line, a reference line is easiest specified by a y-intercept and a slope.

**Comment by bryevdv** [comment]
This seems reasonable and simple, @hafen would you want to try and submit the PR with some guidance?

**Comment by canavandl** [comment]
If you're ok w/ specifying a line via two sets of (x,y) pairs, it'd be possible to do so with an Arrow annotation with the arrow heads set to ``None``. Obviously, that doesn't accomodate your intercept/slope proposal though.

**Comment by bryevdv** [comment]
I think this merits it's own annotation, both because of the different interface but also because of the unbounded behavior

**Comment by hafen** [comment]
Yikes I let this one go. @bryevdv do you mean to submit an empty PR with guidance?

**Comment by bryevdv** [comment]
I meant would you want to try and develop the PR if we are available to answer questions and provide technical direction?
