### ISSUE TITLE
Selection tool regression

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#6388]
Using bokeh 0.12.6dev7 the selection tools appear to be broken in certain cases. A minimal example that reproduces the issue uses a set of ``points`` and ``multi_line`` glyphs:

```
from bokeh.plotting import figure, output_notebook, show

# output to static HTML file
output_notebook()

p = figure(plot_width=400, plot_height=400, tools=['box_select'])

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

p.multi_line([[1, 3, 2], [3, 4, 6, 6]], [[2, 1, 4], [4, 7, 8, 5]],
             color=["firebrick", "navy"], alpha=[0.8, 0.3], line_width=4)

# show the results
show(p)
```

When trying to apply a box_select in this example the console issues the following warning:

```
Uncaught TypeError: Cannot read property 'update_through_union' of null
    at e.r.SelectionManager.e.select (bokeh-0.12.6dev7.min.js:2)
```

And the box_select is never applied. I suspect this is probably related to https://github.com/bokeh/bokeh/issues/6202 but haven't had the time to investigate further. I can confirm it happens in both 0.12.6dev6 and 0.12.6.dev7.

**Comment by bryevdv** [comment]
`MultiLine` does not support box selection. For me on Safari the box selection is applied, but the console message needs to be fixed in any case. Fairly sure the selection manager just needs to explicitly ignore cases where the hit test result is null.

**Comment by philippjfr** [comment]
>For me on Safari the box selection is applied, but the console message needs to be fixed in any case.

I was testing in Chrome and never got it to apply the box simply keeps tracking my cursor. Same issue with lasso_select.
