### ISSUE TITLE
Test that bokehjs is npm-installable

### ISSUE THREAD

**Issue by SimonBiggs** [bokeh/bokeh#6389]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokehjs 0.12.5

#### Description of expected behavior and the observed behavior
I expect to be able to run npm install bojehjs@0.12.5 without error.

Observe error at kiwi. I have submitted a kiwi pull request that might fix this https://github.com/bokeh/kiwi/pull/2

Will need to update package.json within bokehjs to point to the new commit hash of kiwi after the pull request is accepted.

#### Complete, minimal, self-contained example code that reproduces the issue
npm install bojehjs@0.12.5

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mattpap** [comment]
bokeh 0.12.5 was completely broken with respect to this and just installing typescript shouldn't help with this. I fixed this for 0.12.6-dev, where kiwi is installed from `kiwi-prebuilt` branch.

**Comment by SimonBiggs** [comment]
Hi Mateusz,

Thanks for letting me know. Sorry for highlighting something you already
knew about. I'll point my npm install to 0.12.6-dev.

Thank you.

**Comment by bryevdv** [comment]
No apologies needed @SimonBiggs thanks for the report. @mattpap can this be closed then?

**Comment by mattpap** [comment]
> can this be closed then?

I would like to test somehow that bokehjs is npm-installable. This've been an ongoing issue, where bokehjs package being broken and fixed in multiple consecutive recent releases.

**Comment by bryevdv** [comment]
OK, I have labeled it accordingly

**Comment by SimonBiggs** [comment]
@mgruesbeck For others who are having issues with the current state of this in npm I made the following changes to my `package.json` as a temporary solution:

```json
"scripts": {
  "preinstall": "mkdir bokeh; cd bokeh; git init; git remote add -f origin https://github.com/bokeh/bokeh.git; git config core.sparseCheckout true; echo \"bokehjs\" >> .git/info/sparse-checkout; git pull --depth=1 origin 0.12.6; cd .."
},
"dependencies": {
   "bokehjs": "file:bokeh/bokehjs"
}
```

**Comment by bryevdv** [comment]
@mattpap is this still relevant? It occurs to me that there is not really anything at all we can do in CI automation about this, since we can't test that BokehJS is npm-installable until it is published to npm, and that only happens as the last step of a release-deploy.  

Adding a manual check to try to do an npm install at release time seems reasonable but that should go on a wiki checklist or something.

**Comment by mattpap** [comment]
We can test, because "npm installable" doesn't mean whether bokehjs can be installed from npmjs.com, but whether `npm pack` produces a usable package. I want to migrate bokehjs' tests from depending on the source of bokehjs to using the package, which would be a test this issue demands.

**Comment by mattpap** [comment]
Since PR #12635, we are building bokehjs' package (`node make pack`, a part of `node make build`) in CI and bokeh's tests and examples depend on that package. The package is also uploaded as an artifact, for manual inspection and testing. So I will consider this good enough for now.
