### ISSUE TITLE
JavaScript Errors when plotting from a ColumnDataSource populated with a pandas DataFrame containing column named field

### ISSUE THREAD

**Issue by VolkerH** [bokeh/bokeh#6406]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh version 0.12.5
Python version 3.6
Pandas version 0.20.1
Anaconda, Mac OS X Sierra

#### Description of expected behavior and the observed behavior

Populating a `ColumnDataSource` with a pandas data frame that contains a column named `field` causes subsequent JavaScript errors when trying to plot.
The same code works if the name of the column is changed or the column is omitted.

#### Complete, minimal, self-contained example code that reproduces the issue

Jupyter notebook at this gist.

https://gist.github.com/VolkerH/068143c9d3be8255041e1734dc8c64db

Or just the  python code:

```
import pandas as pd
from bokeh.plotting import figure, output_notebook, show, ColumnDataSource
from bokeh.models import HoverTool
# Create two data frames, one has a column named 'field'
df_with_field_column = pd.DataFrame.from_dict({'treatment': ['aa', 'bb', 'cc', 'dd'], 'date': [0.23, 0.45, 0.75, 1.30], 'C': ['uyfyurf','yfytf','uyfdty','adeff'], 'I':['20160917_abc','20160917_def','20160917_ghi','20160917_jkl'], 'field':[0, 1, 2, 3]})
df = pd.DataFrame.from_dict({'treatment': ['aa', 'bb', 'cc', 'dd'], 'date': [0.23, 0.45, 0.75, 1.30], 'C': ['uyfyurf','yfytf','uyfdty','adeff'], 'I':['20160917_abc','20160917_def','20160917_ghi','20160917_jkl']})
s = ColumnDataSource(data=df)
s_with_field_column = ColumnDataSource(data=df_with_field_column)

s.to_df()
s_with_field_column.to_df()

f = figure()
f.circle('date', 'date', source=s)
output_notebook()
show(f)

f2 = figure()
f2.circle('date', 'date', source=s_with_field_column)
output_notebook()
show(f2)
```

#### Stack traceback and/or browser JavaScript console output

```
Javascript error adding output!
Error: field value for property 'data' is not a string
See your browser Javascript console for more details.
```
#### Screenshots or screencasts of the bug in action
<img width="593" alt="pandas_column_field" src="https://user-images.githubusercontent.com/2210044/26882595-1e3aa30c-4b9b-11e7-8de6-3b283efa9df4.png">

Credits also to @tobyhodges who helped me narrow down the bug.

**Comment by bryevdv** [comment]
Can confirm this on master as of `0.12.6rc3`

**Comment by tobyhodges** [comment]
weird! glad to see that you isolated the root cause of the problem, @VolkerH 

I wonder if there are any other special column names that will mess up BokehJS?

**Comment by mattpap** [comment]
> I wonder if there are any other special column names that will mess up BokehJS?

`value` and possibly `units`.

**Comment by bryevdv** [comment]
The proximate cause is that `spec.field` has the actual data not the field name:

<img width="199" alt="screen shot 2017-06-07 at 09 41 11" src="https://user-images.githubusercontent.com/1078448/26884482-76ff27be-4b65-11e7-841f-8e7ddb8d8f0e.png">

Also just friendly FYI, unless specifically notebook related, it's alot better for use to get `output_file` style examples (I need to update the issue template to say this). Debugging JS in the notebook adds a lot of complexity.

**Comment by mattpap** [comment]
@bryevdv, it's actually `Property._init()` that's at fault. A simple solution is to make `field` and `value` detection more strict, but I would like to look closer at this, because I don't like those plain objects being used for specs.

**Comment by mattpap** [comment]
> It would be helpful to see if an identical version made with bokeh.models suffers the same issue.

It's a universal problem with vectorized properties.

**Comment by arnav31** [comment]
Hi, 
I'm trying to run a python notebook but facing this error - name 'ColumnDataSource' is not defined.
I saved the data as source with the relevant information in a key value pair and then using this source to be called in p.line
Can someone tell me what am i doing wonrg?

**Comment by bryevdv** [comment]
This was fixed at some point:

<img width="520" alt="screen shot 2019-03-07 at 4 05 06 pm" src="https://user-images.githubusercontent.com/1078448/53997883-d1585080-40f2-11e9-817d-ddbac2bbaca1.png">
