### ISSUE TITLE
HoverTool broken with multi_line plots in 0.12.5

### ISSUE THREAD

**Issue by zebulon2** [bokeh/bokeh#6416]
Hi,

I noticed a regression in 0.12.5 from 0.12.4 using the hover tool in a multi-line plot. 
This was verified in Windows 7, with Firefox and Chrome, using both Python 2.7 and 3.5.
The hover tool works with circle plots (as in the documentation), but not with a multi_line plot. Using a multi_line plot, the console indicates a JS error: "TypeError: renderer.glyph.sx is undefined" when the cursor is hovered above a point of the multi-line. The multi-lin graph renders fine (and other tools like zooming do work). This works with 0.12.4.

Here is a code example:
```
from bokeh.plotting import figure, show, ColumnDataSource
from bokeh.models import HoverTool
        
source = ColumnDataSource(
                data=dict(
                    x=[[1, 3, 2], [3, 4, 6, 6]],
                    y=[[2, 1, 4], [4, 7, 8, 5]],
                    desc=['a', 'b'],
                )
            )
        
hover = HoverTool(
                tooltips=[
                    ("index", "$index"),
                    ("(x,y)", "($x, $y)"),
                    ("desc", "@desc"),
                ]
            )
        
p = figure(plot_width=400, plot_height=400, tools=[hover],
                   title="Mouse over the dots")
        
p.multi_line('x', 'y', line_width=2, source=source)
       
show(p)
```

**Comment by bryevdv** [comment]
@zebulon2 thanks for the report. It looks like "nearest" mode has always been bokeh for MultiLIne, but it happened to also become the default mode in general in 0.12.5 IIRC. I will try my best to get this in for `0.12.6` but in any case in the mean time, the other `line_policy` modes (e.g interp, next, prev) should work

**Comment by zebulon2** [comment]
Thank you @bryevdv. Good to know about line_policy.
