### ISSUE TITLE
Tabs widget cannot contain a figure

### ISSUE THREAD

**Issue by samuelandjw** [bokeh/bokeh#6417]
bokeh 0.12.5, Python 3.4.6 on Mac OS 10.11.6, Chrome or Safari
In the Python bokeh server script that will be shown below, I attempted to attach a bokeh figure object to a Panel object, which in turn was fed into a Tabs object. The Tabs object was placed beside a Div object. One would not expect the Tabs object overlap with the Div object in any way. However, it turned out that the Tabs object cannot contain the figure object (indicated by the short line above the figure), and the figure object covered part of the Div object.

MWE:
```
from bokeh.plotting import figure
from bokeh.models import Div
from bokeh.layouts import layout
from bokeh.models.widgets import Panel, Tabs
from bokeh.plotting import curdoc


fig = figure(plot_width=700, plot_height=500)

div = Div(width=1000)

div.text = "something<br>something<br>something<br>something<br>something"

tab1 = Panel(child=fig, title="tab1")

tabs = Tabs(tabs=[ tab1 ])

curdoc().add_root(
    layout([[tabs,div]])
)
```
Screenshot of Chrome:
![image](https://user-images.githubusercontent.com/374391/26936917-92955d5c-4ca2-11e7-978a-23ec3c7b12e0.png)

**Comment by bryevdv** [comment]
FYI @mattpap this is not currently fixed by #5518 so I'm going to mark it for `0.12.7`

**Comment by mattpap** [comment]
`Tabs` need to be properly done from scratch as part of layout.

**Comment by bryevdv** [comment]
Output with #8085 

<img width="783" alt="screen shot 2019-01-30 at 19 02 05" src="https://user-images.githubusercontent.com/1078448/52027821-921a5c80-24c1-11e9-9f77-1187bb3c3312.png">
