### ISSUE TITLE
Silence selenium webdriver's debug logs

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6422]
For example:
```
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:44439/wd/hub/session/e57c7b90-4c98-11e7-ad72-37ec85bd325b/execute {"sessionId": "e57c7b90-4c98-11e7-ad72-37ec85bd325b", "args": [], "script": "return window._bokeh_render_complete;"}
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
```
is repeated a hundred of times (https://travis-ci.org/bokeh/bokeh/jobs/240983753).

**Comment by bryevdv** [comment]
ping @canavandl in case you have some input

**Comment by mattpap** [comment]
This is actually a problem also locally when static image export tests fail.

**Comment by mattpap** [comment]
The same problem appears in integration tests under failure. We need to silence those webdriver and possibly other debug logs.

**Comment by bryevdv** [comment]
I am going to close this, AFAIK this was about very verbose output coming out of saucelabs specifically. Failures of new selenium tests on TravisCI seem much more comprehensible.
