### ISSUE TITLE
Hover tool showing canvas coordinates instead of data coordinates.

### ISSUE THREAD

**Issue by w1res** [bokeh/bokeh#6429]
I still seem have issue #4861, which has been closed as solved, on line plots. The issue is that the data values indicated by the HoverTool are changing based on cursor position. In my example below, you can see that the y value changes based on cursor position.

I'm running Bokeh 0.12.5, Anaconda Python 3.6.0, Windows 10 machine, 64 bit.

Here is an example:

```
import numpy as np
import bokeh.plotting as plt
import bokeh.models as pltm

x = np.arange(100)
y = x**4

fig = plt.figure()
fig.add_tools(pltm.HoverTool())
fig.line(x, y)
plt.show(fig)
```

Here is the result. You can see that I get two different values of y, depending on where my cursor is positioned. The way I understand it, canvas should give the position of the cursor, and the other value should display the value of the indicated data point.

![1](https://user-images.githubusercontent.com/2823875/26991077-f784a9b4-4d26-11e7-945b-af6f3fcacfb6.png)

![2](https://user-images.githubusercontent.com/2823875/26991078-fa307350-4d26-11e7-8031-0090d89f77eb.png)

**Comment by bryevdv** [comment]
I don' think this is the same as #4861 In that issue, no data coordinates were shown at all (instead, canvas coordinates were show). In your case it is clearly showing data coordinates, it is just not showing the correct ones in all cases, possibly due to an interaction with `line_policy` which as of `0.12.5` is "nearest"

**Comment by bryevdv** [comment]
This was a misunderstanding. The "data" in this refers to the data space coordinate directly under the cursor, not of a data point in the column data source. So these results are entirely expected -- if the cursor position changes, the data coordinate of the new cursor position must also change. To get the CDS column value, use the `@colname` syntax from the users guide
