### ISSUE TITLE
figure.image: discontinuity at images border

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6430]
The following code  build a single image from several 'tiles'. Once assembled, the latter are supposed to form a "continuous" image but we observe discontinuities - white lines here - between tiles. The position of these discontinuities changes the number of tiles (see `nr` and `nc` variables). It looks like a rounding problem in the tiles anchoring.  

FYI, this is true with both 0.12.6.rc3 and rc4.

```
import numpy as np
from bokeh.plotting import figure, show, output_notebook, output_file

nr = 10
nc = 10

dtype=float

x = np.linspace(0, nr, nr, endpoint=False, dtype=dtype)
y = np.linspace(0, 1, 1, endpoint=False, dtype=dtype)
xv, _ = np.meshgrid(x, y)

tiles = [xv for i in range(nr)]

x = np.zeros(nr, dtype=dtype)
y = np.linspace(0, nr, nr, endpoint=False, dtype=dtype)
dw = np.full((nr,), nc, dtype=dtype)
dh = np.full((nr,), 1, dtype=dtype)

f = figure(x_range=(0, nc), y_range=(0, nr))
f.image(image=tiles, x=x, y=y, dw=dw, dh=dh, palette="Spectral11")

output_file("foo.html")
show(f)
```

<img width="608" alt="capture d ecran 2017-06-10 a 11 13 51" src="https://user-images.githubusercontent.com/19185982/27001621-059ace5e-4dcf-11e7-831c-55af6a6d0a34.png">

**Comment by bryevdv** [comment]
This is a fundamental problem when images are scaled in any way. The real solution is to make sure you carefully size both the plot region and the images to ensure that the pixel dimensions exactly line precisely in the way that you want. But that is not something Bokeh can do automatically. 

Alternately, image glyphs have a `dilate` property tht always forces the rounding to occur in a way that makes the images bigger. Depending on your needs, this may provide a "good enough" solution to get rid of gaps:

http://bokeh.pydata.org/en/dev/docs/reference/models/glyphs/image.html#bokeh.models.glyphs.Image.dilate

**Comment by nleclercq** [comment]
`dilate`works. Thanks.
