### ISSUE TITLE
Proxied reset tool is very inefficient

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6431]
E.g. in grid plot it works on each plot individually, resulting in N full relayouts, thus resulting in a significant delay between tool button click and any changes on screen. Fortunately, number of repaints is only N (not N^2), because of throttled paint.

**Comment by bryevdv** [comment]
We could just revisit wether reset tool should reset plot sizes. Or, we could add an option and make it not reset sizes by default. Reseting size seems much less important to me, especially since ResizeTool is not nearly as emphasized and visible as it used to be

**Comment by bryevdv** [comment]
Resize tool is removed.
