### ISSUE TITLE
selecting a line from a multi-line when one is already selected causes an error

### ISSUE THREAD

**Issue by clairetang6** [bokeh/bokeh#6433]
The error (copied and pasted at the bottom from console) is raised when you use the tap tool to select one of the lines of the multi-line when one is already selected. There is no error if there is nothing selected or if there are multiple lines selected (selected using a box select on other data in a shared CDS). 

You can see the error using the example below and or examples/plotting/file/multi_line.py
```python
import numpy as np
from bokeh.layouts import row
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
from bokeh.io import show

N = 9
x = np.linspace(-2, 2, N)
y = x**2

xpts = np.array([-.09, -.12, .0, .12,  .09])
ypts = np.array([-.1,   .02, .1, .02, -.1])

source = ColumnDataSource(dict(
        xs=[xpts*(1+i/10.0)+xx for i, xx in enumerate(x)],
        ys=[ypts*(1+i/10.0)+yy for i, yy in enumerate(y)],
        x=np.arange(9),
        y=np.arange(9)
    )
)

fig1 = figure(tools=['tap'])
fig1.multi_line(xs="xs", ys="ys", line_color="#8073ac", line_width=4, source=source)
fig2 = figure(tools=['box_select', 'tap'])
fig2.circle(x='x', y='y', source=source)

show(row(fig1, fig2))
```

The error looks to be caused by the equality algorithm, used by HasProps when it sets attributes, for the hit-test-result/selection object ({'0d':.., '1d': .., '2d':.. }) when the ['2d']['indices'] object doesn't inherit from Object.prototype. After more digging, it seems like that happens after the ['2d']['indices'] objects get "merged" by core/util/object merge because that function returns an object created by Object.create(null). An easy fix seems to be changing that line to Object.create(Object.prototype).

```
Uncaught TypeError: b.hasOwnProperty is not a function
    at eq (bokeh.js:4821)
    at eq (bokeh.js:4821)
    at eq (bokeh.js:4821)
    at Object.isEqual (bokeh.js:4832)
    at Selector.exports.HasProps.HasProps._setv (bokeh.js:1390)
    at Selector.exports.HasProps.HasProps.setv (bokeh.js:1447)
    at Selector.exports.Selector.Selector.update (bokeh.js:3124)
    at SelectionManager.exports.SelectionManager.SelectionManager.select (bokeh.js:3032)
    at TapToolView.exports.TapToolView.TapToolView._select (bokeh.js:25476)
    at TapToolView.exports.TapToolView.TapToolView._tap (bokeh.js:25456)
```

**Comment by bryevdv** [comment]
@clairetang6 can you submit a quick PR? I'm not sure we could put it in `0.12.6` but if the change is small and isolated enough we could evaluate it. Is this a regression or has this behavior always been present?

**Comment by clairetang6** [comment]
I just tested on a few dev releases before [the PR that add merge to object.ts](https://github.com/bokeh/bokeh/pull/6202), and it was working then. I'll submit a PR. The object.ts merge is only used in this one case of merging 2d selections, so it is quite isolated.

**Comment by bryevdv** [comment]
Great, let's plan on including it then
