### ISSUE TITLE
"bokeh serve" on official example shows a blank webpage

### ISSUE THREAD

**Issue by ywangwh** [bokeh/bokeh#6434]
#### Environment:
> OS: macOS 10.12.5
> Python: 3.6.0 (x86-64)
> browser: Chrome 58.0.3029.110 (64-bit), Safari
> Bokeh: 0.12.5
> anaconda: custom-py36_0
> conda: 4.3.21-py36_0

#### Description of expected behavior and the observed behavior
Expected: browser shows the chart
Observed: blank webpage

#### Complete, minimal, self-contained example code that reproduces the issue
fourier_animated.py from official **examples/plotting/server** folder:
[fourier_animated.py.zip](https://github.com/bokeh/bokeh/files/1066287/fourier_animated.py.zip)
Use command **bokeh serve fourier_animated.py --show**

#### Stack traceback and/or browser JavaScript console output

> 2017-06-11 15:42:50,357 Starting Bokeh server version 0.12.5
> 2017-06-11 15:42:50,361 Starting Bokeh server on port 5006 with applications at paths ['/fourier_animated']
> 2017-06-11 15:42:50,361 Starting Bokeh server with process id: 12616
> 0:54: execution error: “"http://localhost:5006/fourier_animated"”不理解“open location”信息。 (-1708)
> 2017-06-11 15:43:11,117 Failed to connect to server: HTTP 599: Timeout during request
> 2017-06-11 15:43:11,119 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x1103a8748>: Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)
> File "session.py", line 298, in push:
> raise IOError("Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)") Traceback (most recent call last):
>   File "/Users/yo/anaconda/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 81, in run
>     exec(self._code, module.__dict__)
>   File "/Users/yo/Development/python/bokeh/examples/plotting/server/fourier_animated.py", line 175, in <module>
>     session = push_session(curdoc())
>   File "/Users/yo/anaconda/lib/python3.6/site-packages/bokeh/client/session.py", line 86, in push_session
>     session.push(document)
>   File "/Users/yo/anaconda/lib/python3.6/site-packages/bokeh/client/session.py", line 298, in push
>     raise IOError("Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)")
> OSError: Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)
>  
> 2017-06-11 15:43:11,128 200 GET /fourier_animated (::1) 20358.16ms
> 2017-06-11 15:43:11,129 404 GET /ws?bokeh-protocol-version=1.0&bokeh-session-id=rTFzXtpvEXeDpZFrps4UDMe81PeukDWSEM9EpihCmlVy (::1) 0.42ms
> 2017-06-11 15:43:11,430 WebSocket connection opened
> 2017-06-11 15:43:11,430 ServerConnection created

#### Source code of the blank webpage
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Bokeh Application</title>
        
<link rel="stylesheet" href="static/css/bokeh.min.css?v=1bb409ee97bc7539326089bbfc2aad84" type="text/css" />
<link rel="stylesheet" href="static/css/bokeh-widgets.min.css?v=de1aa4588db0ebb1076588c26ac1e07c" type="text/css" />
        
<script type="text/javascript" src="static/js/bokeh.min.js?v=d5277ec06271e90def555abd13cd3b2f"></script>
<script type="text/javascript" src="static/js/bokeh-widgets.min.js?v=ff67b7fa94bb9ebef0e0e2c97f8c95f0"></script>
<script type="text/javascript" src="static/js/bokeh-gl.min.js?v=dac0ba7cb19b33bf935e67b96a95b546"></script>
<script type="text/javascript">
    Bokeh.set_log_level("info");
</script>
        <style>
          html {
            width: 100%;
            height: 100%;
          }
          body {
            width: 90%;
            height: 100%;
            margin: auto;
          }
        </style>
    </head>
    <body>
        
        <div class="bk-root">
            <div class="bk-plotdiv" id="982535fd-0189-4d6d-a7cf-bfa8ebfb7ce9"></div>
        </div>
        
        <script type="text/javascript">
            (function() {
          var fn = function() {
            Bokeh.safely(function() {
              var docs_json = {};
              var render_items = [{"elementid":"982535fd-0189-4d6d-a7cf-bfa8ebfb7ce9","sessionid":"aFOeoEtS9qJKYD3nm4JepfNudksEYlscUHLIHDJlt7aP","use_for_title":true}];
              
              Bokeh.embed.embed_items(docs_json, render_items);
            });
          };
          if (document.readyState != "loading") fn();
          else document.addEventListener("DOMContentLoaded", fn);
        })();
        
        </script>
    </body>
</html>
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/12015132/27009250-d0a9b956-4ebb-11e7-9c13-a258272d568c.png)

![image](https://user-images.githubusercontent.com/12015132/27009318-658b7900-4ebd-11e7-8452-866d00a36686.png)

**Comment by bryevdv** [comment]
The examples in that folder demonstrate using `bokeh.client` to connect a separate process to the server. They are not run in the manner you are attempting. Please see the README in that directory for instructions:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/README.md

**Comment by ywangwh** [comment]
@bryevdv 

Thanks for your reply.

I was reading the online official [document](http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html) and used command from that document...  >_<

I should read the README in local directory first... Sorry...

**Comment by lopamudra26pal** [comment]
I am trying to execute the crossfilter example (https://github.com/bokeh/bokeh/blob/master/examples/app/crossfilter/main.py) code on my local machine.
OS: Wondows 10
Python: 3.6.0 (x86-64)
browser: IE 11.0
Bokeh: 0.12.5
anaconda: custom-py36_0
conda: 4.3.21-py36_0

I have tried running it using following two ways but the issue still persists, ie. I end up viewing a blank webpage.
$bokeh serve script.py --show
and
$ bokeh serve
$ python script.py

Can someone please suggest how can I solve this issue.

**Comment by canavandl** [comment]
@lopamudra26pal There is a bokeh 0.12.5 and tornado 4.5.1 incompatability issue that you're likely hitting. I'd suggest upgrading to bokeh 0.12.6.

**Comment by lopamudra26pal** [comment]
@canavandl , thanks for the prompt reply. It worked.

**Comment by lopamudra26pal** [comment]
I implemented the crossfilter graph with our data. Issue faced - When outputting the result with bokeh.io.show method, I get the desired graph but with no interactions possible. However if I run the script as a bokeh application using "bokeh serve script.py --show", I get a blank webpage. I tried figuring out the issue for quite a while but still cannot identify what might possibly be the problem. The script works fine with the bokeh team's sample data though.  Any suggestions would really be helpful.
[crossfilter_graph.txt](https://github.com/bokeh/bokeh/files/1098271/crossfilter_graph.txt)
[crossfilter_graph.txt](https://github.com/bokeh/bokeh/files/1098272/crossfilter_graph.txt)



Note:- Our data does not have any integer or float values. Hence I have commented out the continuous and quantileable parts from the original example code.

**Comment by bryevdv** [comment]
@lopamudra26pal for general support and usage questions please use the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by Pretender451** [comment]
@bryevdv We are experiencing the same symptoms as OP and your link to the README is 404. Do you have an updated link please?

**Comment by Pretender451** [comment]
@canavandl Thanks for the headsup about possible incompatability issues. Do you know if this holds for 0.12.4 also? I am using that older version so that i can use Datashader.

**Comment by bryevdv** [comment]
@Pretender451 The link is a 404 because those examples have been removed. Prominently displaying this kind of usage, where `bokeh.client` is used to run an app "outside" the bokeh server, was a mistake on our part. That usage has inherent and unavoidable drawbacks and shortcomings, and was an unwarranted source of increased issues as a results. This usage is officially discouraged by the project and will no longer be demonstrated.

If you are running `012.4` then it is definitely incompatible with Tornado 4.5, you will have to use Tornado 4.4.x

**Comment by Pretender451** [comment]
Thanks so much @bryevdv as it worked. And for replying so fast. I wish i'd asked sooner as i've been pulling my hair out with this for a couple of days now, but i always try to bother people on GitHub only as a last resort. 

Now i move on to trying to get Holoviews and Datashader working with it. Any tips or pointers to the clearest documentation on that would also be very much appreciated as i'm quite confused by linking these all at the moment, but i realise this is not supposed to be the forum for that. Thanks again.

**Comment by jbednar** [comment]
On Fri, Feb 2, 2018 at 10:34 AM, Pretender451 <notifications@github.com>
 wrote:

> Now i move on to trying to get Holoviews and Datashader working with it.
> Any tips or pointers to the clearest documentation on that would also be
> very much appreciated as i'm quite confused by linking these all at the
> moment, but i realise this is not supposed to be the forum for that. Thanks
> again.


We've recently set up pyviz.org to help demonstrate how all these projects
fit together.  I'd recommend going through the tutorial at that site, which
sets up an environment including all of those packages along with examples
of how to use each of the projects separately and together.  Stay tuned to
that site; we'll be trying to put a lot more useful stuff there over the
next few months!

**Comment by Pretender451** [comment]
Brilliant! Thanks @jbednar . That's really helpful to know that [http://pyviz.org](http://pyviz.org) is where the most uptodate developments are going on. I had been searching for 'last updated' type dates on some of the other pages where i was piecing together bits of guidance and examples but without much joy. That would have saved some hair pulling to know which of those was the most uptodate but understood how complex this is to manage, especially when things are progressing so fast. Thanks again, and for all the work putting together these great tools.

**Comment by jbednar** [comment]
Just to clarify, I don't want to claim that pyviz.org is the most up to date; it's probably the opposite. pyviz.org is where we show how all the various projects fit together to solve problems, and as such the most bleeding-edge features are likely to be better documented in each individual project, whereas how to use them together is documented at pyviz.org.  We'll be updating *all* of the websites over the next few months, but yes, it's a continual struggle to keep up with the rate at which each of these projects are progressing!

**Comment by Pretender451** [comment]
Thanks for the clarification @jbednar . Very much appreciated. I tend to bleed at the edge and prefer a stable system of interactions where i can get it. I have enough complexity to manage elsewhere, so [http://pyviz.org](http://pyviz.org) might be the place for me anyway. Thanks again and all the best.
