### ISSUE TITLE
bokeh/jupyter-notebook coexistence problems

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6440]
Attached is a notebook highlighting some bokeh/notebook coexistence problems I observe.

**Observed symptoms:** 
ipywidgets slider callback not called anymore, lost of ipython auto-completion mecanism

**Dependencies:** 
the notebook requires ipywidgets to run properly

**Context:** 
Chrome 59.0.3071.86 on macOS 10.12.5

- bokeh                     0.12.6rc4                py36_0    bokeh/channel/dev
- conda                     4.2.13                   py36_0    conda-forge
- conda-env                 2.6.0                         0    conda-forge
- ipykernel                 4.5.2                    py36_0    conda-forge
- ipyleaflet                0.3.0                    py36_0    conda-forge
- ipython                   5.3.0                    py36_0    conda-forge
- ipython_genutils          0.1.0                    py36_0    conda-forge
- ipywidgets                6.0.0                    py36_0    conda-forge
- jupyter_client            5.0.0                    py36_0    conda-forge
- jupyter_core              4.3.0                    py36_0    conda-forge
- notebook                  5.0.0                    py36_0    conda-forge
- tornado                   4.4.2                    py36_0    conda-forge
- traitlets                 4.3.1                    py36_0    conda-forge
- widgetsnbextension        2.0.0                    py36_0    conda-forge

**How to reproduce the problem:**

1. Run cell 1, play with the slider, check that the `widgets.Label` is properly updated from the slider callback
2. Goto cell 2, type `widgets.<tab>`, check that the ipython auto-completion works
3. Goto cell 3, execute a `Run All Below` from the Cell menu, two live bokeh plots should appear
4. Goto back to cell 1, confirm that the slider callback is NOT called anymore
5. Goto cell 2, confirm that the ipython auto-completion does NOT work anymore
6. Goto back to cell 1, re-execute the cell, the slider callback now works properly
7. Goto to cell 2, the ipython auto-completion is also back

Here is the [code and the notebook](https://github.com/nleclercq/jupyter-for-controls/tree/master/bokeh-data-streaming-for-notebook)

**Comment by bryevdv** [comment]
ping @damianavila do you have any offhand comment as to what circumstances might cause this? A Bokeh server embedded directly inline in a notebook with `show`does piggy back on the notebook's IOLoop but according to @nleclercq this is not an issue of the Bokeh code on the loop CPU starving other things.

**Comment by damianavila** [comment]
This *could* be related with the recent integration of jedi completions in ipython, maybe... but not sure.
Pinging @Carreau, he can probably add some thoughts on this one.

**Comment by bryevdv** [comment]
@nleclercq can you check to see if this occurs with older versions of the notebook?

**Comment by damianavila** [comment]
> @nleclercq can you check to see if this occurs with older versions of the notebook?

Alternative, there is some way to disable the jedi completion and test if this is causing the issue.

> Jedi can also be completely deactivated by using the `c.Completer.use_jedi=False` option.

**Comment by nleclercq** [comment]
I disabled `jedi`but, unfortunately, the problem is still there. 

FYI, if I re-execute the code creating the initial ipywidgets slider **while** the bokeh plots are still asynchronously refreshed by the underlying app, then, things go back to the expected behavior - i.e. autocompletion is back and the slider callback is called again. It seems that opening the bokeh plots "kills" something in the notebook env that's is restored when I re-execute ipywidgets code.

**Comment by nleclercq** [comment]
FYI, inserting a new cell in the notebook also has the same positive effect - i.e. the completion is back in the new cell and the slider callback is called again.

**Comment by nleclercq** [comment]
Ok, I think I finally located the problem. I was using [this trick](https://nbviewer.jupyter.org/gist/minrk/049545c1edcf20415bb3d68f16047628) to route some outputs to a specific notebook cell. Don't ask me why but the 'workaround frontend' described in @minrk example has a side effect on ipywidgets behavior.  Removing this part of the code solves the problem - i.e. I can still redirect outputs to particular cell and the ipywidgets have expected behavior. So this has nothing to do with bokeh. Sorry for that. 

ping @damianavila (FYI)

**Comment by bryevdv** [comment]
Thanks for the update @nleclercq and glad you figured it out!

**Comment by damianavila** [comment]
Thanks for the update @nleclercq.
Did you open an issue about this in some of the jupyter repos? If not, I guess it will be a good idea to, at least, report it. Thanks in advance!

**Comment by nleclercq** [comment]
@damianavila ok, will do that asap.
