### ISSUE TITLE
Canvas outline does not cover top of canvas 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6450]
See e.g `burtin.py`

<img width="888" alt="screen shot 2017-06-12 at 21 46 00" src="https://user-images.githubusercontent.com/1078448/27063657-8c717b5e-4fb8-11e7-9360-9171c8d04943.png">

**Comment by mattpap** [comment]
`bokehjs/examples/burtin` doesn't exhibit this behavior.

**Comment by mattpap** [comment]
Those examples aren't identical. `plotting/file/burtin` uses `title=""` and `bokehjs/examples/burtin` uses `title=null`. Empty title is at fault here. Changing title to `title=None` fixes the problem.

**Comment by bryevdv** [comment]
I would argue they ought to behave the same in this case

**Comment by mattpap** [comment]
This was fixed in PR #6448.
