### ISSUE TITLE
Add an option to disable column titles in DataTable

### ISSUE THREAD

**Issue by iandow** [bokeh/bokeh#6454]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

This issue is being reported for bokeh version 0.12.6.

DataTable widgets do not include an option to hide column titles. It would be nice to have that option.  

Coincidentally, the `row_headers` property is poorly named. It turns on/off the index column, but its name seems to suggest it would toggle column titles. Perhaps that option should be redefined.

#### Complete, minimal, self-contained example code that reproduces the issue

```
data = dict(
        dates=[date(2014, 3, i+1) for i in range(10)],
        downloads=[randint(0, 100) for i in range(10)],
    )
source = ColumnDataSource(data)

columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]

data_table = DataTable(source=source, columns=columns, row_headers=False, editable=True)
```

#### Screenshots or screencasts of the bug in action

<img width="463" alt="screenshot" src="https://user-images.githubusercontent.com/1383911/27066925-73e0f548-4fbc-11e7-90c7-3761de80b990.png">

**Comment by bryevdv** [comment]
Apparently one reason this may not have been done is that slick grid does not support it directly. But there may be some workarounds

https://stackoverflow.com/questions/19580402/show-or-hide-slickgrid-header-filter-row-at-runtime
https://stackoverflow.com/questions/2728265/how-to-remove-the-header-in-slickgrid

Whenever this issue s tackled, we should repurpose `row_header` property for it, and make a new property to show/hide the index column
