### ISSUE TITLE
Restart saucelabs jobs if  `Sauce could not start your job`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6459]
The current situation with randomly failing tests due to third party issues is annoying.

**Comment by bryevdv** [comment]
@mattpap trying to ping you on FD

**Comment by TarunKhandelwal** [comment]
Facing similar issue with intermittent failures.
Any alternate?

**Comment by mattpap** [comment]
We don't use sauce labs anymore. If this changes, please reopen.
