### ISSUE TITLE
Pivot app y-axis not updating correctly in examples

### ISSUE THREAD

**Issue by jlstevens** [bokeh/bokeh#6460]
Using Python 2 and Bokeh 0.12.6rc5 I noticed the following issue with the pivot app while spot testing:

```
bokeh serve --show pivot/
```

![pivot_spot_test](https://user-images.githubusercontent.com/890576/27085877-6db3506c-5048-11e7-9164-b668f1578f66.gif)

I've also noticed these messages in the terminal:

```
2017-06-13 14:49:13,369 error handling message Message 'PATCH-DOC' (revision 1): TypeError("cannot concatenate 'str' and 'int' objects",)
2017-06-13 14:49:17,036 error handling message Message 'PATCH-DOC' (revision 1): TypeError("cannot concatenate 'str' and 'int' objects",)
```

**Comment by mattpap** [comment]
> I've also noticed these messages in the terminal:

So, hopefully this is a problem with the example itself. Are there any errors in js console?

**Comment by bryevdv** [comment]
pretty sure it is, this is a new example and also ambitious and sophisticated, it probably needs some gentle attention

**Comment by bryevdv** [comment]
closing, pivot example was removed due to lack of a maintainer
