### ISSUE TITLE
optimizations or opt-out for array property comparisons

### ISSUE THREAD

**Issue by nicain** [bokeh/bokeh#6470]
Minimal example here:
https://gist.github.com/nicain/dfaa88e98a4a373b11ce2319e349da8d

When a ColumnSourceData is updated, the js_on_change fails to fire a CustomJS callback.  In the example, the data is modified by a python callback attached to a button; the button itself fires off to the standard out without any issue.  I can attached the CustomJS to a js_on_click for the button, and it fires to the console (commented out in the example), but the same callback attached to the ColumnDataSource fails.

bokeh (0.12.6); 
tornado (4.5.1)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
notebook (5.0.0)
firefox (52.0 64-bit)

@nleclercq reports seeing this issue in bokeh 0.12.5

**Comment by mattpap** [comment]
The reason event handler isn't called is because `source` is not part of the document. Neither of models added in `add_root()` references it. This would work if you added a plot. You could try adding `source` as another root, but that should fail, because sources aren't meant to be added like this.

**Comment by nicain** [comment]
Thanks @mattpop!  Adding source as an additional root did work, for exactly one button press:
`curdoc().add_root(row(widgetbox(button)))
curdoc().add_root(source)`

There was alot of complaining in the console too.

Since we are now in discussion mode, two questions:
 
1. General best-practice: I have never seen an example that calls doc.add_root more than once (its usually a layout with lots of sub-layouts); is this best practice, or is this function intended to be used more than once?
2.  Would it make sense to add a feature request that allows otherwise unreferenced ColumnDataSource instances to be registered properly?  I have a particular use case in mind, so I can try and mock up  a simple version of the application that lead me down this road.

**Comment by mattpap** [comment]
> Adding source as an additional root did work, for exactly one button press:

This is because you're updating it with the same data. Use a random value or a counter of some sort instead of `str` and it should trigger events.

**Comment by mattpap** [comment]
> have never seen an example that calls doc.add_root more than once

It's not common, but there are scenarios where it's useful. For example in jupyter-notebook every cell is `add_root()`. It's also useful in custom embeddings, templates, etc. The difference between two root plots and a column of two plots, is that roots are separate entities, they aren't layoutable, so plots' axes won't line up. Roots only share a document for communication and bookkeeping purpose. So, for example, if you have a dashboard with two plots and you want to have linked behavior (e.g. panning one plot pans the other), then plots need to be in one document. However, if our layout system doesn't allow for what you need, you can provide your own HTML template, embed those plots there, and you will use multiple roots for this purpose.

**Comment by mattpap** [comment]
> Would it make sense to add a feature request that allows otherwise unreferenced ColumnDataSource instances to be registered properly?

Actually, in PR #6340 I'm working on a generic mechanism for adding "extra stuff" to a document. In that PR, you would use `curdoc().add_var("whatever", source)` to include `source`.

**Comment by nicain** [comment]
> Use a random value or a counter of some sort 
Nailed it!  

> have never seen an example that calls doc.add_root more than once
Your explanation on this is super-useful!

> Actually, in PR #6340 I'm working on a generic mechanism for adding "extra stuff" to a document.
Looks great, can't wait to see what you come up with.  

Ill paste my example in gist when I get some spare time today.

**Comment by nicain** [comment]
> Ill paste my example in gist when I get some spare time today.

@mattpap Check out this gist for a minimal example that lead me to this:

https://gist.github.com/nicain/c8c926285c7bd69b70347a95064ca645

Basically I wanted to send out the csv version of my pandas dataframe that I am viewing in the DataTable.  I could have just used the CustomJS on the original source, but this way the same code to format the csv file does the work in both python land and JS; the functionality for pandas to_csv is nice, better than I can do in JS without spending all afternoon!  

> Actually, in PR #6340 I'm working on a generic mechanism for adding "extra stuff" to a document.

Will this PR allow me to do what I am hacking around here (I don't really need dowload_source to be a ColumnDataSource, but rather a js_on_change aware string)?

**Comment by nleclercq** [comment]
> This is because you're updating it with the same data

@mattpap Does this means that the underlying implementation compare the new data byte per byte - whatever is the size of each dimension? I guess no. So what do you mean? Thanks.

**Comment by bryevdv** [comment]
> Does this means that the underlying implementation compare the new data byte per byte - whatever is the size of each dimension? I guess no. So what do you mean? Thanks.

It does mean that. For semantic consistency we strive to only trigger property updates when the new value is actually different from the old value. AFAIK numpy array comparisons fail fast, as soon as any shape or value is different. So unless you have the pathological case where the new array only differs by e.g. the very last element, this should still be quite efficient.

**Comment by nleclercq** [comment]
Ok. So, is there is way to shortcut the array comparison in case we know the data actually changed. 
For instance, I have an upstream events system that push data only is something changed. In this case, a `force_update=True` could help - notably for big images.

**Comment by bryevdv** [comment]
There is nothing present currently. It's possible that could be added, it would probably have to either be a "global" configuration of some sort, or a more specialized API for updating (i.e. some function, instead of assignment). 

It might be worth considering, since apparently I was mistaken about `np.array_equal` failing early, it always scans the entire array (which is both surprising and disappointing)

**Comment by bryevdv** [comment]
One thing that could be implemented immediately that might be helpful: we could compare the first elements of the arrays, before going to `np.array_equal`. Under the assumption that arrays that are different, are often *completely different* this would be a quick and safe way to offer an dramatic speedup in that case.

**Comment by mattpap** [comment]
> we could compare the first elements of the arrays, before going to `np.array_equal`

First you would have to check shapes and at this point you're just reimplementing that function.

**Comment by bryevdv** [comment]
> That's truly disappointing.

Agreed. I contemplated forking NumPy immediately to work on a short-circuiting ufunc in C (and I still may) but even so that doesn't help with current and old numpy versions.

**Comment by bryevdv** [comment]
doing that yields a 1000x improvement when the first element is different:
```
In [20]: def array_equal(a1, b1):
    ...:     try:
    ...:         a1, a2 = asarray(a1), asarray(a2)
    ...:     except Exception:
    ...:         return False
    ...:     if a1.shape != a2.shape:
    ...:         return False
    ...:     if a1.flatten[0] != a2.flatten[0]:
    ...:         return False
    ...:     return bool(asarray(a1 == a2).all())
    ...:

In [21]: %timeit array_equal(a, b)
The slowest run took 6.33 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 573 ns per loop
```
vs 925 us with `np.array_equal`

**Comment by mattpap** [comment]
> `if a1.flatten[0] != a2.flatten[0]:`

As shapes are the same at this point, maybe you could just compare flattened representations? I'm not sure if that makes sense.

**Comment by nleclercq** [comment]
IHMO, bokeh should not systematically deal with 'data changed?'. As a user, I (almost :-) know what I'm doing. What's about an `enable/disable comparaison` at ColumnDataSource level? 

BTW, a data size changed detection would also boost the performance - if dat size change, no need to compare anything - an update will be systematically required.

**Comment by bryevdv** [comment]
@nleclercq data changed will be risky and require care, I am talking about what could be done immediately that is both safe and an improvement, as this would seem to be:

```
n [52]: def array_equal(a1, a2):
    ...:     try:
    ...:         a1, a2 = np.asarray(a1), np.asarray(a2)
    ...:     except Exception:
    ...:         return False
    ...:     if a1.shape != a2.shape:
    ...:         return False
    ...:     if a1.flat[0] != a2.flat[0]:
    ...:         return False
    ...:     return bool(np.asarray(a1 == a2).all())
    ...:

In [53]: array_equal(a, b)
Out[53]: True

In [54]: %timeit array_equal(a, b)
1000 loops, best of 3: 983 µs per loop

In [55]: b[0] = 10

In [56]: %timeit array_equal(a, b)
The slowest run took 8.61 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.43 µs per loop
```

re data size, that *is* already short circuited by `np.array_equal` that will return `False` immediately. So if your images are of different shapes then nothing discussed here will really offer any improvement.

**Comment by nleclercq** [comment]
@bryevdv I was simply talking about providing a way to disable the 'systematic comparaison' in case "I know" that an update is required.

**Comment by mattpap** [comment]
>  maybe you could just compare flattened representations?

With something like `all(a == b for a, b in itertools.izip(a1.flat, a2.flat))`

**Comment by bryevdv** [comment]
@nleclercq yes that's basically it. There is a quick shunt to `array_equal` for arrays, so dropping in a nearly identical replacement (that always returns the same true/false, just sometimes more quickly) is fairly low risk. Adding a global flag to disable array checking completely, or API to enable disabling checks in specific instances, means new logic, new or updated tests, and additional documentation. I'm not opposed to this, I just think it's on a weeks-to-few-months horizon, whereas the `quick_array_equal` drop in could happen very soon.

**Comment by bryevdv** [comment]
@mattpap that's really fast when things differ, but *much* slower when things are indentical:
```
In [64]: def array_equal(a1, a2):
    ...:     try:
    ...:         a1, a2 = np.asarray(a1), np.asarray(a2)
    ...:     except Exception:
    ...:         return False
    ...:     if a1.shape != a2.shape:
    ...:         return False
    ...:     return all(a == b for a, b in zip(a1.flat, a2.flat))
    ...:

In [65]: %timeit array_equal(a, b)
10 loops, best of 3: 152 ms per loop

In [66]: b[0] = 10

In [67]: %timeit array_equal(a, b)
The slowest run took 7.52 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.01 µs per loop
``` 
NB using `zip` because Python 3

**Comment by nicain** [comment]
FWIW, this accomplishes what I was trying to in my original issue:

```from bokeh.io import curdoc
from bokeh.models.widgets import Button
from bokeh.layouts import row, widgetbox
from bokeh.models import ColumnDataSource, CustomJS
from bokeh import events

button = Button(label = 'Send HelloWorld to console')

source = ColumnDataSource(data=dict())

jscb = CustomJS(code='''
console.log('HelloWorld');
''')

button.js_on_event(events.ButtonClick, jscb)

def send_hello_world_to_console():
    source.data = {'data':['str']}
    print 'Confirm that python CB worked'

button.on_click(send_hello_world_to_console)

curdoc().add_root(row(widgetbox(button)))

**Comment by bryevdv** [comment]
@nicain I am going to leave this open, I think the array property optimizations would be useful to some people (e.g. @mrocklin would probably be interested for the task dashboard) I've change the title to reflect the shifted focus, however.

**Comment by bryevdv** [comment]
I'm not sure what there is to do at this point, there have been various performance improvements and validation config options added, so it's hard to know where this old issue stands. Closing as stale, please open a new issue with new details to consider changes for contemporary Bokeh versions.
