### ISSUE TITLE
[Feature request] Less obvious logos

### ISSUE THREAD

**Issue by traverseda** [bokeh/bokeh#6473]
I'm working on a commercial project.

I'd like to support bokeh, and make it obvious that we're using bokeh. But right now the prominent placement of the logo makes it easy to mistake the logo for a UI element.

What I'd like it an optional "Made with bokeh" watermark somewhere on the chart. Something that can't be mistaken for a UI element.

Right now I need to just turn the logo off completely with "p.logo = None", lest our users get confused.

**Comment by bryevdv** [comment]
This seems fine to me tho it seems to me that this could be achieved with a with a low alpha `Label` positioned by absolute screen coordinates. Or are you thinking of something different?

**Comment by traverseda** [comment]
Where it's part of bokehs branding it would be nice if it was consistent across different code bases and a well-documented default option.

I'll do that for the time being, but it would probably be a good idea to lower the friction on this as much as possible.

**Comment by bryevdv** [comment]
Sure I appreciate the sentiment. Once you have something you like the way it looks maybe you can post a screenshot here for concrete reference? (understand if you cannot share, however)

**Comment by traverseda** [comment]
No worries, I'm using sample data at this stage of the project.

**Comment by bryevdv** [comment]
I very much appreciate the sentiment, but in cases where the usual logo is not appropriate, it's really fine to just omit it completely. I'd prefer that to adding more API surface :)
