### ISSUE TITLE
New panels to a Tabs widget does appear

### ISSUE THREAD

**Issue by nicain** [bokeh/bokeh#6474]
https://gist.github.com/nicain/5a0236b688c166cb195d61e7735bcdcd

Given the behavior of modifying the "children" attribute of a layout, I expected adding a new tab to work in a similar fashion.  In the gist above, I think that pressing the button should add a new tab (and new figure), but it doesn't seem to work.

bokeh 0.12.6
firefox 54 and Chrome 58

**Comment by nicain** [comment]
I can fake out the behavior I am after by building an entirely new Tab widget and attaching it directly to the layout: 

https://gist.github.com/nicain/fccc9a83ac0b382ba093b0e4548fe904

However, the Tab that I am trying to create dies intermittently; this can be caused by pressing the button several times.  When this happens, the Firefox Developer Edition reports the following error at the console:

TypeError: p is undefined[Learn More]  bokeh.min.js:1:16787
	Bokeh</<["core/build_views"]</r.build_views/m< http://10.128.48.86:5109/static/js/bokeh.min.js:1:16787
	Bokeh</<["core/build_views"]</r.build_views http://10.128.48.86:5109/static/js/bokeh.min.js:1:16727
	Bokeh</<["models/layouts/layout_dom"]</r.LayoutDOMView</e.prototype.build_child_views http://10.128.48.86:5109/static/js/bokeh.min.js:29:12585
	Bokeh</<["models/layouts/layout_dom"]</r.LayoutDOMView</e.prototype.initialize http://10.128.48.86:5109/static/js/bokeh.min.js:29:9745
	t http://10.128.48.86:5109/static/js/bokeh.min.js:22:1446
	e http://10.128.48.86:5109/static/js/bokeh.min.js:1:19724
	e http://10.128.48.86:5109/static/js/bokeh.min.js:29:9545
	t http://10.128.48.86:5109/static/js/bokeh-widgets.min.js:3:5117
	t http://10.128.48.86:5109/static/js/bokeh-widgets.min.js:2:31122
	Bokeh</<["core/build_views"]</r.build_views http://10.128.48.86:5109/static/js/bokeh.min.js:1:17026
	Bokeh</<["models/layouts/layout_dom"]</r.LayoutDOMView</e.prototype.build_child_views http://10.128.48.86:5109/static/js/bokeh.min.js:29:12585
	Bokeh</<["models/layouts/layout_dom"]</r.LayoutDOMView</e.prototype.rebuild_child_views http://10.128.48.86:5109/static/js/bokeh.min.js:29:12445
	Bokeh</<["models/layouts/widget_box"]</r.WidgetBoxView</e.prototype.connect_signals/</< http://10.128.48.86:5109/static/js/bokeh.min.js:29:20838
	Bokeh</<["core/signaling"]</u</t.prototype.emit http://10.128.48.86:5109/static/js/bokeh.min.js:2:25827
	Bokeh</<["core/has_props"]</r.HasProps</t.prototype._setv http://10.128.48.86:5109/static/js/bokeh.min.js:1:25466
	Bokeh</<["core/has_props"]</r.HasProps</t.prototype.setv http://10.128.48.86:5109/static/js/bokeh.min.js:1:26002
	Bokeh</<.document</r.Document</t.prototype.apply_json_patch http://10.128.48.86:5109/static/js/bokeh.min.js:22:20616
	Bokeh</<.client</i</t.prototype._handle_patch http://10.128.48.86:5109/static/js/bokeh.min.js:1:10900
	PATCH-DOC/< http://10.128.48.86:5109/static/js/bokeh.min.js:1:2945
	Bokeh</<.client</o</t.prototype._for_session http://10.128.48.86:5109/static/js/bokeh.min.js:1:3822
	PATCH-DOC http://10.128.48.86:5109/static/js/bokeh.min.js:1:2911
	Bokeh</<.client</o</t.prototype._steady_state_handler http://10.128.48.86:5109/static/js/bokeh.min.js:1:9709
	Bokeh</<.client</o</t.prototype._awaiting_ack_handler/this._current_handler</< http://10.128.48.86:5109/static/js/bokeh.min.js:1:9368
	Bokeh</<.client</o</t.prototype._on_message_unchecked http://10.128.48.86:5109/static/js/bokeh.min.js:1:8334
	Bokeh</<.client</o</t.prototype._on_message http://10.128.48.86:5109/static/js/bokeh.min.js:1:7546
	Bokeh</<.client</o</t.prototype.connect/</</t.socket.onmessage http://10.128.48.86:5109/static/js/bokeh.min.js:1:4571

**Comment by mattpap** [comment]
Tabs are currently broken beyond repair. They will be redone from scratch for 0.12.7 or 0.12.8.

**Comment by mattpap** [comment]
On a side note, when submitting a block of code or a traceback, use proper formatting (triple backquotes, see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by mattpap** [comment]
Actually, this particular issue is trivial to fix and is fixed in PR #6335.
