### ISSUE TITLE
bokeh in the Jupyter notebook: embedded server and sessions lifecycle management

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6475]
I'd like this issue to be the first of a series of discussions about the integration of bokeh in the Jupyter notebook. As a first step, I would suggest to focus on a specific topic: **how to attach bokeh [live] plots to a particular notebook cell and manage their life cycle properly**. The idea is to identify what is, or will be, the best practices to manage "per cell bokeh plots" created from either  code cells or python scripts.

**Comment by nleclercq** [comment]
I finally choose to create a [dedicated repo](https://github.com/nleclercq/jupyter-for-controls). Concerning the (bokeh server) sessions lifecycle management, my conclusion is the following: bokeh <= 0.12.6 does not provide a way to properly release bokeh objects on both python and JS side. Hope 0.12.7 will fix this. 

The study I made on this resources management topic is fully detailed in [this notebook](https://github.com/nleclercq/jupyter-for-controls/blob/master/about_sessions_life_cycle.ipynb).

**Comment by bryevdv** [comment]
@nleclercq I think these things are important to figure out, so I am re-opening the issue.

**Comment by nleclercq** [comment]
@bryevdv I think I'm done with my evaluation of bokeh. IMHO, that's the tool with need. However, its current implementation (0.12.6) doesn't totally fit with the way we would like to use it in the jupyter notebook and we have to wait for a solution from your side to turn our work into a production tool.  I did my best to explain everything in [this notebook](https://github.com/nleclercq/jupyter-for-controls/blob/master/about_sessions_life_cycle.ipynb). Hope you bokeh gurus will find an hour to devote to it cause I'm convince that or request has a interest for any notebook user. Thanks.

**Comment by bryevdv** [comment]
@nleclercq we definitely want to improve things. There are lots of ways to use the notebook, and your use case just seems to be one we have not considered fully. But your feedback will be very valuable towards improving things.

**Comment by bryevdv** [comment]
I can't actually identify a specific complaint or suggestion in the linked notebook. There have been numerous improvements since Jun, to `push_notebook` as a better option, fixing some memory leaks, and much improved performance with a binary protocol. I am going to close this issue as somewhat stale and vague. Please feel free to open new issues to report or suggest specific things in recent versions.
