### ISSUE TITLE
Editable data tables not modifying python source.data - bokeh server 0.12.6

### ISSUE THREAD

**Issue by Signapur** [bokeh/bokeh#6478]
Upgrading to 0.12.6, I found that my editable data tables changes where no longer being shown when I called the data.source on the python side of my application. It showed the original value of the data source. However on the JS side the data.source was being properly updated to the new values.

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Browser: Chrome 58.0.3029.110
OS: Windows 7 

Environment on which the bug is found
```
- bkcharts=0.2=py35_0
- bokeh=0.12.6=py35_0
- jinja2=2.9.6=py35_0
- markupsafe=0.23=py35_2
- mkl=2017.0.1=0
- numpy=1.13.0=py35_0
- pip=9.0.1=py35_1
- python=3.5.3=3
- python-dateutil=2.6.0=py35_0
- pyyaml=3.12=py35_0
- requests=2.14.2=py35_0
- setuptools=27.2.0=py35_1
- six=1.10.0=py35_0
- tornado=4.5.1=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
```

Environment on which there is no bug
```
- bokeh=0.12.5=py35_1
- jinja2=2.9.6=py35_0
- markupsafe=0.23=py35_2
- mkl=2017.0.1=0
- numpy=1.13.0=py35_0
- pip=9.0.1=py35_1
- python=3.5.3=3
- python-dateutil=2.6.0=py35_0
- pyyaml=3.12=py35_0
- requests=2.14.2=py35_0
- setuptools=27.2.0=py35_1
- six=1.10.0=py35_0
- tornado=4.4.2=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
```

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.io import curdoc
from bokeh.models import *
from bokeh.layouts import row, column

x = [1, 2, 3, 4]

source = ColumnDataSource(data=dict(x=x))
columns = [
    TableColumn(field="x", title="x", sortable=True, formatter=NumberFormatter(format='0.')),
]
data_table = DataTable(source=source, editable=True,
                       columns=columns, sizing_mode='fixed')

button_print_py_func = Button(label="Print Python")


def print_python(source=source):
    data = source.data
    print(data)


button_print_py_func.on_click(print_python)

button_print_js = Button(label="Print JS")
button_print_js.callback = CustomJS(args=dict(source=source), code="""
    var data = source.data;
    console.log(data)
""")

buttons = row(button_print_py_func, button_print_js)
layout = column(data_table, buttons)

curdoc().add_root(layout)
```
I expect when I'm printing the data on the python side to see in the terminal the updated values, but on 0.12.6, I see the original source.data not the ones in the table. This was not case with 0.12.5. 
For both version the current values are properly shown on the JS console.

I don't know if this is related, but I also found that on 0.12.5 source.data included an index column which can be seen on both the JS console and the terminal this index column was removed in 0.12.6.

**Comment by bryevdv** [comment]
@mattpap I can confirm this but am definitely confused. Looking at the code, cell editors call `setField` which calls `_update_source_inplace` which is this:
```
 _update_source_inplace: () ->
    @source.properties.data.change.emit(@, @source.attributes['data'])
    return
```
That should trigger an update on the server, no? I guess I would be less surprised if this failed on both sides, I don't understand yet how it could fail to update just one side.

**Comment by mattpap** [comment]
> That should trigger an update on the server, no? 

No, you have to call `HasProps._tell_document_about_change()`, which is called only by `HasProps.setv()`, not not in relationship with `change` signal. I think `setv()` is pretty wrong in its logic, but I have to give this a closer look. To me, the relationship between `attr:change`, `change` and server updates, and now server events, wasn't ever very well defined.

**Comment by danwang123** [comment]
I am using bokeh 2.0.1, my editable data tables changes showed the original value of the data source. No update from new editable data tables. Could you help to check? Thanks!
