### ISSUE TITLE
31 Dec 49 Dateformatter()

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#6479]
Why is there a difference of one day between the print of the date and the Dateformatter?
I am working on the Table. Please disregard any code with the Vbar.

```    
        from bokeh.layouts import row
        from bokeh.models import ColumnDataSource, WidgetBox, HoverTool
        from bokeh.models.widgets import  DataTable, DateFormatter, TableColumn

        xu = [1,2,3]
        ttnwwrd = [90, 78, 150]
        dte = [100,200,300]
        da = []
        for i in range(1,31):
            da.append(datetime.strptime("{}-Dec-49".format(i), '%d-%b-%y').date())
            print(datetime.strptime("{}-Dec-49".format(i), '%d-%b-%y').date())
        #da.append(datetime.strptime("30-Dec-49", '%d-%b-%y').date())
        #da.append(datetime.strptime("31-Dec-17", '%d-%b-%y').date())
        print(datetime.strptime("31-12-49", '%d-%m-%y').date())
        #print(da)

        sourcet5 = ColumnDataSource(data=dict(x=xu,top=ttnwwrd,date=dte))
        p5 = figure(plot_width=500, plot_height=650, title="test",
            tools = "pan,wheel_zoom,box_zoom,reset,hover,previewsave") #, x_axis_type = "datetime")
        # x = "x",
        glyph = VBar(x="x", top="top", bottom=-1, width=.5, fill_color="#b3de69")
        p5.add_glyph(sourcet5, glyph)
        people = ['un', 'deux','trois']
        sourcedt1 = ColumnDataSource(data=dict( da=da))

        columns1 = [
            #TableColumn(field="people", title="People",  default_sort="descending"),
            TableColumn(field="da", title="Date", formatter=DateFormatter()),
        ]
        dttbl1 = DataTable(source=sourcedt1, columns=columns1, width=320, height=630)
        wdgtdt1 = WidgetBox(dttbl1)
        hover = p5.select(dict(type=HoverTool))
        hover.tooltips = [("New words", "@top"),('date',' @date')]
        l5 = row(p5,wdgtdt1)
        show(l5)
```

**Comment by Pierretherenard** [comment]
no worries i am going to change the date by one day. I guess it has to be +1 micro second on timestamp to be that day if not it is still yesterday.

**Comment by bryevdv** [comment]
@Pierretherenard well that seems at least a little alarming/unexpected, so I'd like to take a look at this at some point in the next release cycle. But the code is not complete (some missing imports) and also seems to have extra extraneous bits. If you can, it would be very helpful if you could make a quick pass to clean up the test case.

**Comment by Pierretherenard** [comment]
I am not sure if I should open a new one for this but here some other "fun" stuff with table:
I am working with English and French words, which means that some of the French words have accent. The table column does not sort the e accent like e. The word 'métis' should have been right after the word 'met' and not just before 'nation' after all the m word, unless there is a special property that I missed. This is just a sample of a project.
Thank you for asking me for the quick pass. At one point I will have to dig in.

![screen shot 2017-07-25 at 11 33 33 am](https://user-images.githubusercontent.com/23002446/28587785-33e468a2-712d-11e7-9ff2-63516166f288.png)

**Comment by Pierretherenard** [comment]
and here is the code to test the table sort with accent, met and méteo should be near each other.
 def test3():
        from bokeh.layouts import row
        from bokeh.models import ColumnDataSource, WidgetBox, HoverTool
        from bokeh.models.widgets import  DataTable, DateFormatter, TableColumn
        word = ['met', 'méteo','no','mute','mill','mole']
        sopeople = ColumnDataSource(data=dict( word=word))
        columns1 = [
            TableColumn(field="word", title="word",  default_sort="descending"),
        ]
        dttbl1 = DataTable(source=sopeople, columns=columns1, width=320, height=630)
        wdgtdt1 = WidgetBox(dttbl1)
        l5 = row(wdgtdt1)
        show(l5)

**Comment by bryevdv** [comment]
@Pierretherenard combining different things in one issue makes if difficult for us to manage, track and plan, please make  a separate issue for new concerns

**Comment by bryevdv** [comment]
I believe this has been resolved. There is another open issue in tables with the last row not showing up, but the rows do show up now match as best I can tell. Please re-open if a problem persists

**Comment by bryevdv** [comment]
<img width="954" alt="screen shot 2017-10-12 at 19 04 14" src="https://user-images.githubusercontent.com/1078448/31524575-2e2ccd78-af80-11e7-837f-8e99f5b2d70f.png">
