### ISSUE TITLE
Regression with stacked rectangles

### ISSUE THREAD

**Issue by jjouganous** [bokeh/bokeh#6493]
Hello,
I've just updated bokeh, from 0.12.4 to 0.12.6, and I notice unexpected behaviors on a stacked rectangles plot based on the following example : 
[http://bokeh.pydata.org/en/0.12.5/docs/gallery/stacked_bar_chart.html](url).
I isolated a minimal example. The expected plot, that I get with version 0.12.4 is given below:
![example_0 12 4](https://user-images.githubusercontent.com/15675162/27273545-ce5699de-54cf-11e7-8c8b-0dddecfa7de5.png)
Under version 0.12.6, some rectangles are plotted unexpectedly as negative values: 
![example_0 12 6](https://user-images.githubusercontent.com/15675162/27273594-09d939b2-54d0-11e7-94c5-b9fc278cfd20.png)
The minimal code I used for these plots is given below:

```
from bokeh.layouts import layout
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

import pandas as pd
import numpy as np


df = pd.DataFrame({'cat2':['AAA', 'BBB'], 'y_g1':[0.0, 1.0], 'y_g2':[0.0, 2.0],
                   'y_g3':[3, 2.0], 'g_1':[0.0, 2.0], 'g_2':[0.0, 0.0],
                   'g_3':[6.0, 0.0]})


datasource2 = ColumnDataSource({"cat2":[], "y_g1":[], "y_g2":[], "y_g3":[], "g_1":[], "g_2":[], "g_3":[], "gamme_cd_1":[], "gamme_cd_2":[]})

plot2 = figure(width=1000, height=700, x_range=list(datasource2.data["cat2"]))

plot2.rect(x="cat2", y="y_g1", width=0.8, height="g_1", source=datasource2, color="#CD7F32", alpha=0.6, name='rect_gamme1')
plot2.rect(x="cat2", y="y_g2", width=0.8, height="g_2", source=datasource2, color="silver", alpha=0.6, name='rect_gamme2')
plot2.rect(x="cat2", y="y_g3", width=0.8, height="g_3", source=datasource2, color="gold", alpha=0.6, name='rect_gamme3')
plot2.xaxis.major_label_orientation = np.pi/4
plot2.xgrid.grid_line_color = None
#plot2.y_range.start = 0

plot2.x_range.factors = list(df.cat2)
datasource2.data = ColumnDataSource.from_df(df)


l1 = layout([[plot2]], sizing_mode='fixed')

curdoc().add_root(l1)
curdoc().title = "Test"
```

Thanks!!

Julien

**Comment by bryevdv** [comment]
This was fixed at some point, code on `master` now produces:

<img width="865" alt="screen shot 2018-05-10 at 18 27 42" src="https://user-images.githubusercontent.com/1078448/39901853-e305b79c-547f-11e8-9d61-6d218dbbaaa9.png">

**Comment by jjouganous** [comment]
Thank you!
