### ISSUE TITLE
Bokeh `json`, `png`, `svg` commands require explicitly adding root to curdoc

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6494]
Bokeh `html`, `json`, `png`, `svg` commands require explicitly adding root to curdoc. It'd be nice to be able to correctly infer the root from the script state.

Bokeh 0.12.7dev1

**Comment by bryevdv** [comment]
The easiest thing to do is probably just patch `show` to perform `curdoc().add_root` I think that would provide useful capability in a a majority of cases. If there are some weird corner cases they can be dealt with as they arise.

**Comment by bryevdv** [comment]
Not a priority
