### ISSUE TITLE
Multiselect selection highlight no longer present when programmatically selected

### ISSUE THREAD

**Issue by Zyell** [bokeh/bokeh#6501]
Moving from Bokeh 0.12.5 to 0.12.6 on python 3.6, I found that the when selecting items in the multiselect from a python callback, they were no longer highlighted in the browser.  Selecting manually in the browser works fine.  My use case is a select all button or checkbox.  In the below code, clicking the "Select All" button would highlight and select all values in the multiselect widget under Bokeh 0.12.5.  Under 0.12.6, the values are selected, but there is no highlighting showing the selection in the browser.  Manually selecting does show this highlighting, only programmatic selection is affected.

```python
from bokeh.layouts import widgetbox, column
from bokeh.models.widgets import MultiSelect
from bokeh.plotting import curdoc
from bokeh.models import Button


multiselect =  MultiSelect(title="stuff", options = ['a', 'b', 'c', 'd', 'e'])


def callback():
    print('before', multiselect.value)
    multiselect.value = multiselect.options
    print('after', multiselect.value)


button = Button(label="Select All")
button.on_click(callback)

curdoc().add_root(column(widgetbox(button), widgetbox(multiselect)))
```

**Comment by bryevdv** [comment]
Confirmed, thanks for the test case @Zyell I've added to `0.12.7` milestone, under the assumption that it should probably be a simple fix. Some chance it will slip tho, if that is not the case.

**Comment by Zyell** [comment]
I just tested this with 0.12.7dev12 and it works once again!  I don't know what changed to cause this exactly, but I think we can close this issue.  Thanks!

**Comment by resenganalytics** [comment]
the issue  still happens with version 0.12.13 , running as server on Ubuntu 16.04 and clients Chrome/Firefox.

**Comment by edresch** [comment]
Issue also still happens with v 0.12.14 on Firefox
