### ISSUE TITLE
Programmatically setting the active Tab does not change the tab in 0.12.6 & 0.12.7

### ISSUE THREAD

**Issue by Zyell** [bokeh/bokeh#6502]
When moving from Bokeh 0.12.5 to 0.12.6 on python 3.6, setting the active tab programmatically no longer changes the tab in the browser.  Clicking on the "Switch Tabs" button generated by the below code should cause the active tab to switch to Tab 2, but no longer does this under Bokeh 0.12.6. Maybe this is related to Issue #6501 ?

```python
from bokeh.layouts import column, widgetbox
from bokeh.models.widgets import Div, Tabs, Panel
from bokeh.plotting import curdoc
from bokeh.models import Button

label1 = Div(text='Tab 1')
label2 = Div(text='Tab 2')
panel1 = Panel(child=widgetbox(label1), title='Tab 1')
panel2 = Panel(child=widgetbox(label2), title='Tab 2')
tabs = Tabs(tabs=[panel1, panel2])


def callback():
    print('before', tabs.active)
    tabs.active = 1
    print('after', tabs.active)


button = Button(label="Switch Tabs")
button.on_click(callback)

curdoc().add_root(column(widgetbox(button), tabs))
```

**Comment by Zyell** [comment]
I performed this test once again with bokeh 0.12.7dev12 and the response has changed.  Previously, clicking the "Switch Tabs" button made no difference.  Now, if you are on Tab 1 and click "Switch Tabs" to change to tab 2 programmatically, something must be changing behind the scenes.  Clicking on Tab 2 does not visually change to Tab 2 like it used to.  I have to click on Tab 1 (which is currently visually selected) and then click on Tab 2 to switch.  If I never click the button, I can move back and forth between the tabs normally.  It's almost like the tabs have switched, but the visual rendering is just not updating.  This is distinctly different than the behavior in 0.12.6.  Hopefully this will help in debugging!

**Comment by Zyell** [comment]
I tested with the release of 0.12.7 today and the issue remains.  I'm not sure if this helps, but using a CustomJS callback also will not switch the tabs.

**Comment by Zyell** [comment]
After going through the source for a while, I built a custom widget extending the Tabs widget so that you can programmatically set the active tab once again.
```python
from bokeh.models.widgets import Tabs


JS_CODE = """
import * as p from "core/properties"
import {Tabs, TabsView} from "models/widgets/tabs"


export class CustomTabsView extends TabsView

    connect_signals: () ->
        super()
        @connect(@model.properties.active.change, () => @render())


export class CustomTabs extends Tabs
  type: "Tabs"
  default_view: CustomTabsView

"""

 
class CustomTabs(Tabs):
    __implementation__ = JS_CODE
```

The key part was connecting the signal for the active property so that when it changed the tab would switch.  When I was debugging the Tabs, I noticed clicking on them didn't seem to initiate a render but still switches the tabs.  After applying the connection, it now renders whenever the active property changes through mouse selection or programmatic selection.  I know that you are planning to rewrite the tabs, but until that time, maybe this fix could bring back this functionality?

**Comment by bryevdv** [comment]
@mattpap is this just missing plumbing? Should @Zyell submit a PR that just adds 
```
@connect(@model.properties.active.change, () => @render())
```
to the built in implementation?

**Comment by mattpap** [comment]
Yes, but I'm surprised this doesn't enter an infinite loop when clicking on a tab.
