### ISSUE TITLE
user guide docs clerical error

### ISSUE THREAD

**Issue by RageCooky** [bokeh/bokeh#6507]
http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#bars
![20170620161302](https://user-images.githubusercontent.com/2822225/27323261-899a6078-55d3-11e7-9751-007332a1bb14.png)
Just start learning bokeh . . .
Is these should be "vbar" ?

**Comment by bryevdv** [comment]
@RageCooky Thanks for the report! This has been fixed in https://github.com/bokeh/bokeh/pull/6506/commits/1aba9a2c29785d045773fe7b5adabcedbb511dcb and the issue will close automatically when that PR is merged.

**Comment by mattpap** [comment]
@bryevdv, you need to update the PR.

**Comment by bryevdv** [comment]
Thanks for the reminder, done
