### ISSUE TITLE
Multiple callbacks for same model call only last callback

### ISSUE THREAD

**Issue by Andres-Hernandez** [bokeh/bokeh#6508]
If a model has multiple callbacks attached to a property, only the last callback is actually called, but it is called multiple times

Here is a small example that shows the problem:

```python
from bokeh.layouts import column
from bokeh.models import CustomJS, ColumnDataSource, Slider
from bokeh.plotting import Figure, output_file, show

output_file("js_on_change.html")

x = [x*0.005 for x in range(0, 200)]
y = x

source1 = ColumnDataSource(data=dict(x=x, y=y))

plot1 = Figure(plot_width=400, plot_height=400)
plot1.line('x', 'y', source=source1, line_width=3, line_alpha=0.6)

callback1 = CustomJS(args=dict(source=source1), code="""
    var data = source.data;
    var f = cb_obj.value
    console.log("callback1");
    x = data['x']
    y = data['y']
    for (i = 0; i < x.length; i++) {
        y[i] = Math.pow(x[i], f)
    }
    source.trigger("change");
""")

source2 = ColumnDataSource(data=dict(x=x, y=y))

plot2 = Figure(plot_width=400, plot_height=400)
plot2.line('x', 'y', source=source2, line_width=3, line_alpha=0.6)

callback2 = CustomJS(args=dict(source=source2), code="""
    var data = source.data;
    var f = cb_obj.value
    console.log("callback2");
    x = data['x']
    y = data['y']
    for (i = 0; i < x.length; i++) {
        y[i] = Math.pow(x[i], f)
    }
    source.trigger("change");
""")

slider = Slider(start=0.1, end=4, value=1, step=.1, title="power")
slider.js_on_change('value', callback1)
slider.js_on_change('value', callback2)
print(slider.js_property_callbacks)
layout = column(slider, plot1, plot2)

show(layout)
```

Changing the slider changes only the second plot. Moreover, one can see in the console, that callback2 is being called twice every time the slider is updated. If one adds three plots, again, only the last callback actually gets executed, but three times. So the observed behaviour is that the last callback is called the number of times that there are callbacks. 

What I would expect, is that each of callbacks in slider.js_property_callbacks would be called. 

 Software version info:
bokeh: 0.12.5
python: 3.6.0
OS: windows 8
browser: chrome Version 58.0.3029.110

**Comment by canavandl** [comment]
I was able to reproduce this also.

ping @mattpap

**Comment by SafwanAhmad** [comment]
Is there a plan to fix this issue?

**Comment by bryevdv** [comment]
Given that there is a workaround (i.e. combine the two code snippets into one call back, which may be annoying but is always possible), and given that it is a much less common use-case, there are many other priorities ahead of this, so I can't speculate when it might be gotten to

**Comment by bryevdv** [comment]
After changing to current syntax `source.change.emit()` the code above now works fine. Closing as resolved.
