### ISSUE TITLE
How to retrieve the json representation of a Document

### ISSUE THREAD

**Issue by manubaum** [bokeh/bokeh#6511]
Calling bokeh.io.output_file writes a html file containing the json representation of a document to the file System. Is there a way to directly retrieve the json representation of the document as it is embedded in the html in the 'var docs_json = ...'?

**Comment by mattpap** [comment]
There is `Document.to_json()` to get a serialization of a document, but that's not enough to make it useful for bokehjs to consume. There isn't currently a public API for this, though you could use `bokeh.embed._standalone_docs_json_and_render_items()`. As with any private function, this can change at any time without warning. We may need to provide a public version.

**Comment by manubaum** [comment]
Thanks for your suggestions! I will have a look.

**Comment by canavandl** [comment]
There's also a ``bokeh json`` command. 

http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html#module-bokeh.command.subcommands.json

**Comment by bryevdv** [comment]
This came on the mailing list a few days ago, so I'm re-opening. There, I thought `Document.from_json(doc.to_json())` but found out it didn't ("models can't be owned by more then one document") We should probably add a `copy` flag to `from_json` that ignores existing document refs and points to the new document. Possibly should remake all model id's as well.

**Comment by mattpap** [comment]
For that you have `Document.destructively_move()`.

**Comment by bryevdv** [comment]
> For that you have Document.destructively_move().

That does not accept JSON, which is what is being asked for.

**Comment by bryevdv** [comment]
`bokeh.embed.util.standalone_docs_json_and_render_items` is now a public, defended API that is safe to use (It is "internal" or "advanced", but will be maintained under test):

https://github.com/bokeh/bokeh/blob/master/bokeh/embed/util.py#L177
