### ISSUE TITLE
Add a link to bokehjs package on npmjs.com

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6513]
Similarly to what we have for conda and pypi.

**Comment by bryevdv** [comment]
Before we do this its probably worth revisit what and how we actually publish to npmjs. We are just uploading core `bokeh.js` now?

**Comment by mattpap** [comment]
npm uploads everything you have in root directory, except npm ignored files and git ignored (?), so I think we upload everything, though I'm not sure if those other files are importable.

**Comment by mattpap** [comment]
We also need to improve bokehjs' readme, because currently it's pretty sparse on information.
