### ISSUE TITLE
Bokeh Error Range FactorRange is incompatible is Scale LinearScale with components(plot

### ISSUE THREAD

**Issue by darahsten** [bokeh/bokeh#6518]
Hi there, 

This is my first posting. I believe this to be an issue. I stand to be corrected if otherwise.
So I get this Bokeh Error Range FactorRange is incompatible is Scale LinearScale with 
script, div = components(plot) whenever plot is having a categorical x-axis. I believe it should be
an issue with Bokeh plots because using output_file without dismantling components returns a clean
 plot.
As you can see, in the image below, the problem is occurring entirely inside the scripts generated by Bokeh.
![bokeherror](https://user-images.githubusercontent.com/7501274/27411832-b156a3b0-56f0-11e7-8b68-f5c1102e3336.png)
I am using Bokeh 0.12.6 with python 3.5 and django 1.9
```
x = ['a', 'b', 'c']
p = figure(title="Simple demo graph", x_axis_label="x-axis",
               y_axis_label="Y-axis"l,  x_range=x)
y = [2,4,6]
p.line(x, y, line_width=2, legend="Line", color="green")
script, div = components(p)
#for Django in get_context_data(self, **kwargs)
context["script"] , context["div"]= script, div
return context

#then in my template with imports
{{ script | safe }}</div>
{{ div |safe }}
```
When I do 
```
output_file("somefile.html")
show(p)
```
Bokeh displays the graph.

**Comment by bryevdv** [comment]
@darahsten are you 100% certain that you are not creating the plot with `0.12.5` (or earlier) but including  BokehJS resources for `0.12.6` in your template? That would explain not only the error in the browser, but also the fact that it works when you `output_file`

**Comment by darahsten** [comment]
Hi Just for your review, here is the head 
`{% load staticfiles %}
<head>
    <title> Land Transactions </title>

        <meta charset="utf-8">
        <title>Bokeh Scatter Plots</title>

        <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.6.min.css" type="text/css" />
        <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.6.min.js"></script>

        {% if scripts %}
            {% for jscript in scripts %}
                {{ jscript | safe }}</script>
            {% endfor %}
        {%endif %}

`

**Comment by bryevdv** [comment]
@darahsten OK I am going to go ahead close this issue. It sounds like you might just have a conda/virtualenv mixup (has happened to me plenty of times) Making sure to use matching version of Bokeh and BokehJS should solve the problem for you.

**Comment by David-Herman** [comment]
@bryevdv Hello,

I am also getting the same error message in my case I am using BokehJS only. 0.12.5 works with my code but on 0.12.6 it throws the following error trace on chrome. 

Uncaught Error: Range FactorRange is incompatible is Scale LinearScale
    at CartesianFrame.exports.CartesianFrame.CartesianFrame._get_scales (bokeh-0.12.6.js:11319)
    at CartesianFrame.exports.CartesianFrame.CartesianFrame._configure_scales (bokeh-0.12.6.js:11348)
    at CartesianFrame.exports.CartesianFrame.CartesianFrame.initialize (bokeh-0.12.6.js:11267)
    at CartesianFrame.exports.HasProps.HasProps.finalize (bokeh-0.12.6.js:1365)
    at CartesianFrame.HasProps (bokeh-0.12.6.js:1350)
    at CartesianFrame.Model [as constructor] (bokeh-0.12.6.js:7198)
    at CartesianFrame.LayoutCanvas [as constructor] (bokeh-0.12.6.js:1880)
    at new CartesianFrame (bokeh-0.12.6.js:11261)
    at PlotCanvas.exports.PlotCanvas.PlotCanvas.initialize (bokeh-0.12.6.js:19588)
    at PlotCanvas.exports.HasProps.HasProps.finalize (bokeh-0.12.6.js:1365)

IE gives the following error.

**Comment by David-Herman** [comment]
SCRIPT5022: Range FactorRange is incompatible is Scale LinearScale

**Comment by bryevdv** [comment]
@David-Herman please make a new separate issue

**Comment by David-Herman** [comment]
ok
