### ISSUE TITLE
Deprecate ToolEvents

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6521]
The `ToolEvent` class does not work well at all. It should be replaced with new style events from `bokeh.events` that tools can generate when appropriate. 

Adding this to `0.12.7` because we should try to mark all planned deprecations by `0.12.7` if possible. 

ping @jlstevens

**Comment by canavandl** [comment]
Does it need to be replaced with an BokehEvent or just removed? ToolEvents don't seem to do any eventing, but appears to just store a list of tool geometries for SelectTool and TapTool (so we've inconsistently used it anyway)

I'm not aware how commonly it's used, so perhaps we could just remove it?

**Comment by bryevdv** [comment]
It has be *extremely* rarely publicized. I would suggest a compromise: effectively remove it entirely (i.e. don't try to "make it work" with new events) but make it have an `__init__` that prints a detailed and informative message about how to adapt existing usage to new events.

**Comment by bryevdv** [comment]
It would be nice (and I don't think too hard) to add a "Selection" event at the same time, that all the select tools could simply report a selection geometry with. Without that, there is not quite parity.
