### ISSUE TITLE
selection_histogram example: "selected" change doesn't work

### ISSUE THREAD

**Issue by enfeizhan** [bokeh/bokeh#6522]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 0.12.6
python: 3.6
notebook: 5.0.0
jupyter: 1.0.0
jupyter_client 5.0.1
jupyter_console: 5.1.0
jupyter_core: 4.3.0
ipython: 6.0.0
ipython_genutils: 0.2.0
OS: ubuntu 16.04
brower: Chrome 58.0.3029.110 (64-bit)
#### Description of expected behavior and the observed behavior
Distribution of selected circles will be shown in histogram. However, as shown in the screenshot down the bottom, the histograms don't change after circles selected.

However, the example from this (url)[https://demo.bokehplots.com/apps/selection_histogram] works:
![screenshot from 2017-06-22 14-09-52](https://user-images.githubusercontent.com/8487127/27417028-88e91e76-5754-11e7-89cb-570b6a51f846.png)
 
#### Complete, minimal, self-contained example code that reproduces the issue
Code was copied from the selection_histogram.py. Added `output_notebook()`/`output_file(filename)` and `show(layout)` to be shown in notebook/browser tab.
#### Stack traceback and/or browser JavaScript console output
No error reported.

There are the print-outs while running the example code in console:
```
Bokeh: BokehJS not loaded, scheduling load and callback at Thu Jun 22 2017 13:57:19 GMT+1000 (AEST)
VM393:83 Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-0.12.6.min.js
VM393:83 Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.6.min.js
VM393:76 Bokeh: all BokehJS libraries loaded
VM393:139 Bokeh: BokehJS plotting callback run at Thu Jun 22 2017 13:57:19 GMT+1000 (AEST)
bokeh-0.12.6.min.js:2 [bokeh] setting log level to: 'info'
VM393:108 Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-0.12.6.min.css
VM393:110 Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.6.min.css
VM393:53 Bokeh: all callbacks have finished
VM396:134 Bokeh: BokehJS plotting callback run at Thu Jun 22 2017 13:57:42 GMT+1000 (AEST)
VM396:52 Bokeh: all callbacks have finished
```
#### Screenshots or screencasts of the bug in action
![selection](https://user-images.githubusercontent.com/8487127/27416846-609740ac-5753-11e7-8f63-78c30d11e345.png)

By the way, think this might be related. On the right hand side of the screenshot, I try to call `show(curdoc())` it encountered an error of missing `references` attribute.

**Comment by bryevdv** [comment]
This is a Bokeh server application. It has to either be run using the bokeh server, e.g.
```
bokeh serve --show selection_histogram.py
```
from the command line (i.e. not in a jupyter notebook or normal python interpreter). Or, if you want to see it inline in a jupyter notebook, you'd have to adapt it to create a proper application object to show, similar to this example:

https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/notebook_embed.ipynb

It's probably worth referring to the general background information regarding bokeh server applications and the ways they can be run here:

http://bokeh.pydata.org/en/latest/docs/user_guide/server.html

**Comment by enfeizhan** [comment]
@bryevdv Thanks that notebook example works. However, it doesn't work when accessed from a remote client's view. Jupyter notebook reports 403 tornado websocket error.

**Comment by bryevdv** [comment]
@enfeizhan I'm not sure I understand what you are trying to do from that description, but this sounds more like a support/usage question, so the mailing list is more appropriate for further discussion:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by enfeizhan** [comment]
@bryevdv Actually, after a day of jumping between two computers. I think this is a bug and have fixed it in bokeh.io.

What I tried to do was running a jupyter server on one computer and then opening up notebook_embed.ipynb on another computer through internet. The `show(app)` didn't show any figure.

This is caused by this line `script = autoload_server(url='http://127.0.0.1:%d%s' % (server.port, app_path))`  in the function `_show_notebook_app_with_state`. 

This is fine when jupyter notebook is run on localhost. But suppose now my server ip is 10.0.1.1 and client ip is 10.0.1.2. When this line is called, it creates js code on server (10.0.1.1). The code is sent to the client (10.0.1.2). When the browser on client sees this js code, it tries to fetch the figure from 127.0.0.1 instead of the server (10.0.1.1).

So I fixed the bug by changing the line to
```
script = autoload_server(url='http://%s:%d%s' % (notebook_url.split(':')[0], server.port, app_path))
```
In this case, you can specify the server ip by calling `show(app, notebook_url='10.0.1.1:8888')`. Now the browser on the client computer correctly sees to the bokeh server is on the server ip.
