### ISSUE TITLE
Wrong display of cyrillic characters with bokeh serve

### ISSUE THREAD

**Issue by funkindy** [bokeh/bokeh#6523]
Windows 10, Python 3.5, Bokeh 0.12.6, various browsers.
The code to reproduce encoding problem:

```
from bokeh.plotting import figure
from bokeh.layouts import layout
from bokeh.io import curdoc

x = [1, 2, 3]
y = [1, 2, 3]

p = figure(title="Результаты АК")
p.circle(x, y)

curdoc().add_root(p)
```
When i _--show_ this on _bokeh serve_ i get encoding problems with figure title (which is in russian language):

![s5hpgpb](https://user-images.githubusercontent.com/17568549/27431095-a8cdf4ae-5764-11e7-8708-4ffa3c29eef0.png)

But if not using _serve_ and just do this locally:

`show(p)`

there is no encoding problems observed:
![ajbnopk](https://user-images.githubusercontent.com/17568549/27431194-12339be2-5765-11e7-968d-5ac349e2264e.png)

Still didnt find a solution to maintain correct encoding on bokeh application.

**Comment by bryevdv** [comment]
possibly related to #6437

**Comment by bryevdv** [comment]
Fixing a similar issue on the demo site required setting 
```
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
``` 
I think windows users needing unicode may have to set these I don't see how bokeh can be responsible for this.
