### ISSUE TITLE
py.test bokeh/tests/test_io.py doesn't kill phantomjs precesses

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6525]
Run:
```
py.test bokeh/tests/test_io.py
ps aux | grep phantom
```

**Comment by bryevdv** [comment]
This can be seen at the end of TravisCI test output as well.

**Comment by mattpap** [comment]
@canavandl, this is still an issue, at least on my system. Running `py.test bokeh` leaves about 14 phantomjs instances.
