### ISSUE TITLE
Allow click on graph to follow link

### ISSUE THREAD

**Issue by yerfdogyrag** [bokeh/bokeh#653]
I'd like to have a way of making it so that clicking on a graph will allow going to a new url, opening a new window, or copying a value to the clipboard.  Essentially, this would be similar to the HoverTool, but for clicks.

**Comment by damianavila** [comment]
This is somewhat addressed by #1854, at least the open url thing...

**Comment by bryevdv** [comment]
Yes I think this can be closed as a dupe.

**Comment by mattpap** [comment]
Technically #1795 is a duplicate of this one, but it doesn't really matter.

**Comment by bryevdv** [comment]
Yes, I am not rigid about choosing issues to label as dupes. We don't always catch them soon enough, so my policy is to keep whichever one has gotten the real discussion.
