### ISSUE TITLE
remove requests as runtime dependency?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6543]
This only seems to be used for one sampledata download, in which case we should find a different way to grab the data with stdlib functions and remove the dependency.

ping @mattpap

**Comment by mattpap** [comment]
There are some other uses:
```
$ git grep "\(import\|from\)\s*requests"
bokeh/command/subcommands/tests/test_serve.py:import requests
bokeh/sampledata/daylight.py:import requests
tests/examples/collect_examples.py:import requests
tests/plugins/bokeh_server.py:import requests
tests/plugins/bokeh_server.py:from requests.exceptions import ConnectionError
tests/plugins/jupyter_notebook.py:import requests
tests/plugins/jupyter_notebook.py:from requests.exceptions import ConnectionError
```

**Comment by bryevdv** [comment]
right every other use is a test. I don't mind it being a test dependency, but it should't be a runtime dependency if all it is needed for is `daylight.py` sampledata

**Comment by bryevdv** [comment]
Specifically would like to remove from this list:

https://github.com/bokeh/bokeh/blob/master/setup.py#L89-L100

and add to tests section in `meta.yaml`

**Comment by bryevdv** [comment]
Tangentially: are numpy and tornado needed as *build* dependencies?

**Comment by canavandl** [comment]
It appears that the ``requests`` usage is deadcode (we've checked in the downloaded csv and don't actually do the download). We should just delete the download function and remove the dep.

**Comment by bryevdv** [comment]
+1
