### ISSUE TITLE
Patch bug: patch slices must have positive (start, stop, step) values, got slice(0, 200, 50)

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6545]
In [.../0.12.6/examples/howto/patch_app.py](https://github.com/bokeh/bokeh/blob/0.12.6/examples/howto/patch_app.py) at line 59, changing `slice(50, 151, 20)` to `slice(0, 200, 50)`generates the following error: `ValueError('Patch slices must have positive (start, stop, step) values, got slice(0, 200, 50)',)`. 

As far as I know, `0` is supposed to be a valid slice index. Only negative values are prohibited.

**Comment by bryevdv** [comment]
right that might be worth changing, for now I would imagine `slice(None, 200, 50)` might work

**Comment by nleclercq** [comment]
right, `slice(None, 200, 50)` works

**Comment by bryevdv** [comment]
marking for `0.12.8` as there is a workaround (though if you'd like to look at it I am happy to advise)
