### ISSUE TITLE
Image for Jitter Example on Gallery does no reflect example

### ISSUE THREAD

**Issue by David-Herman** [bokeh/bokeh#6550]
Hello,

The  [gallery](http://bokeh.pydata.org/en/latest/docs/gallery.html) link to the [jitter example](http://bokeh.pydata.org/en/latest/docs/gallery/jitter.html) does not have consistent images for this example.

![image](https://user-images.githubusercontent.com/22305345/27605175-d708a59c-5b49-11e7-9adc-2719f9f40a14.png)

![image](https://user-images.githubusercontent.com/22305345/27605200-eca241ec-5b49-11e7-84ed-ede2ea0f9658.png)

**Comment by bryevdv** [comment]
Thanks for the report @David-Herman Updating those thumbnails is still currently a manual process, so it's often easy to overlook or forget there is a corresponding thumbnail at all, if the underlying example changes. If you'd like to make a PR to up update the thumbnail, it would be appreciated. The image to change is  located here:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/_images/gallery/jitter.png

**Comment by David-Herman** [comment]
ok thanks, made PR. I did try looking at the new export to png functionality in 0.12.6 but could not get phantomJS to install to automate the process of updating the images, assuming you can choose the output size of the image in the function call.

**Comment by bryevdv** [comment]
Right I'd like like eventually automate things more with the new png/svg exports but that will be a larger project.  Thanks!
