### ISSUE TITLE
[proposal] optimizing ColumnDataSource for patching

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6552]
Use case: visualization of 1D or 2D data streams with known dimensions which content is delivered by bunches of N points (possibly N rows or N columns for 2D). 

So far, with bokeh 0.12.6,  one would have to create a `column` with the appropriate dimensions, to fill it with NANs (or zeros) then to push it on JavaScript side for display. It means that the 'first plot update' requires a full buffer of NANs to be transferred on the wire. For big images, this is clearly a performance bottleneck. 

A possible solution would be to enhance the `ColumnDataSource` with an initialization mechanism allowing to create the 'empty' buffer on JavaScript side without having to transfer it. Something like: this `column` is a `m x n matrix` initialized with NANs that will be patched with incoming data.

**Comment by bryevdv** [comment]
This seems like a not-unreasonable ask but I am not sure when it might be prioritized, and it seems like if necessary it could be added non-disruptively after a 1.0 release. So, putting it in `short-term` for now. 

Happy to help anyone who wants to work on it sooner than than the core devs can get to, though.

**Comment by bryevdv** [comment]
So: 

* there has not been any follow on interest in this
* subsequent to this a vastly more efficient binary array transport was added

Given that, I will close this with no action on the grounds that adding complexity to maintain to Bokeh for this specialized use case is no longer really justified, and it keeps in line with Python's "explicit is better than implicit"

If anyone wants to submit a PR for this (with tests) we could consider it.
