### ISSUE TITLE
ColumnDataSource.patch: 'first rows' bug

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6554]
Here is a bokeh app highlighting what could a bug in the JavaScript part of `ColumnDataSource.patch`. 

To summarize, when patching an image row by row, it seems that the 'first rows' are not properly patched or, at least, displayed. In fact, the very first one is 'sometimes' [1] properly patched and displayed but the next `N` ones are not. It seems that, **for a given update period**,  `N` is constant - whatever are the dimensions of the image (i.e. N is the same in all displayed images). It is important to note that increasing the update period, decreases `N` but doesn't solve the problem [2]. The same behavior is observed when we remove the biggest images for the example.  Finally, the problem has also been observed on a single 1000x500 image. 

Edit: the symptom is observed with a 'newly displayed' plot. If we reset the image data and start patching an existing plot from the the first row, everything works properly.  This is proved by [this example](https://github.com/nleclercq/jupyter-for-controls/blob/master/03_about_columndatassource_patch.ipynb) - clone [this repo](https://github.com/nleclercq/jupyter-for-controls) to give it a try.

The provided code (see below) highlights the problem. Usage: save the following code as 'patch_bug_app.py' then type `bokeh serve --show patch_bug_app.py` at commande line. 

**Some images produced by this example are quite big and take a ten of seconds to show up in the browser. So, be patient.**

- [1]: set `update_period_ms` to 100 ms and comment out the last 2 `il2.append`
- [2]: set `update_period_ms` to 2500 ms with all images enabled then do the same at 250 ms and compare

```
# This is a Bokeh server app. To function, it must be run using the
# Bokeh server at the command line:
#
#     bokeh serve --show patch_bug_app.py

import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import gridplot
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

# a 2D data source delivering an image row by row
class PatchedImage(object):
    
    def __init__(self, iw=1000, ih=1000):
        self._cds = None
        self._inc = 4
        self._row_index = 0
        self._iw, self._ih = iw, ih
        x, y = np.linspace(0, 10, self._iw), np.linspace(0, 10, self._ih)
        xx, yy = np.meshgrid(x, y)
        self._full_image = np.sin(xx) * np.cos(yy)
        
    @property
    def width(self):
        return self._iw
    
    @property
    def height(self):
        return self._ih
    
    def setup_figure(self):
        f = figure(plot_width=250, 
                   plot_height=250, 
                   x_range=(0, self._iw), 
                   y_range=(0, self._ih))
        f.image(image='img',
                x=0, 
                y=0, 
                dw=self._iw, 
                dh=self._ih, 
                source=self.cds)
        return f
        
    @property
    def cds(self):
        if self._cds is None:
            img_buffer = np.empty((self._ih,self._iw))
            img_buffer.fill(np.nan)
            self._cds = ColumnDataSource(data=dict(img=[img_buffer]))
        return self._cds
    
    def start(self, up=250):
        f = self.setup_figure()
        curdoc().add_periodic_callback(self.update, up)
        curdoc().add_root(f)
            
    def update(self):
        if self._row_index >= self._ih:
            # done: full image received
            return
        #print("row index: {}".format(self._row_index))
        start = self._row_index
        start_wr6545 = start if start else None # workaround for bokeh bug #6545 
        end = self._row_index + self._inc
        s1, s2 = slice(start_wr6545, end), slice(None)
        #print("s1/s2: {}/{}".format(s1, s2))
        index = [0, s1, s2]
        new_data = self._full_image[s1, s2].flatten()
        self._cds.patch({ 'img' : [(index, new_data)] })
        self._row_index = end
            

il1 = list()
il1.append(PatchedImage(10, 10))
il1.append(PatchedImage(25, 25))
il1.append(PatchedImage(50, 50))
il1.append(PatchedImage(75, 75))

il2 = list()
il2.append(PatchedImage(100, 100))
il2.append(PatchedImage(250, 250))
il2.append(PatchedImage(500, 500))
il2.append(PatchedImage(1000, 1000))

il = il1 + il2

layout = gridplot([[i.setup_figure() for i in il1], [i.setup_figure() for i in il2]])

curdoc().add_root(layout)

update_period_ms = 250
for i in il:
    curdoc().add_periodic_callback(i.update, update_period_ms)
```

**Comment by nleclercq** [comment]
@bryevdv Seems to be fixed by 0.12.7. I don't observe the symptom anymore.

**Comment by bokeh-integrations** [comment]
Good to hear I will close then

**Comment by bryevdv** [comment]
Good to hear, closing for now
