### ISSUE TITLE
Individual widget styling

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6555]
In some contexts, controlling the background color of a button is much more than an aesthetic problem. For instance, the [Tango control framework uses colors](http://www.taurus-scada.org/en/latest/users/ui/ui_colors.html) to code the state of devices spread over the network. It's consequently convenient to be able to control the styling properties of any widget associated with a particular device. 

By extension, it would be great to  extend the bokeh widgets model with some styling attributes allowing to control things like the foreground or background color, the font style, etc.

**Comment by bryevdv** [comment]
I'm potentially interested in exposing a way to do this, but really only by providing an easier way to update CSS. Currently you can set or change `.css_classes` but maybe there is a way to accept and apply raw CSS rules. Basically I think it would be a mistake and a maintenance nightmare to try and add Bokeh properties corresponding to, and duplicating, arbitrary CSS.

**Comment by nleclercq** [comment]
That sounds like Chinese to me :-) I'm a real dummy in web related stuffs and I don't know anything about CSS. Anyway, I fully trust you.

**Comment by bryevdv** [comment]
@mattpap is there a dupe issue for this (sending stylesheets as part of resource bundles) ?

**Comment by bryevdv** [comment]
Closing as inactive discussion. `css_classes` option already mentioned
