### ISSUE TITLE
using ``export_png`` or ``save`` without filename from within jupyter notebook saves png file to lib/python

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6560]
Using ``bokeh.io.export_png``, ``bokeh.io.export_svg`` or ``bokeh.io.save`` from within a jupyter notebook without specifying an output filename causes the file to be written to lib/python (on my machine it's '/Users/lcanavan/miniconda3/envs/bokeh/lib/python3.5/runpy.png'.

It's likely due to how if there's no filename arg, we infer the name of the script the document is in. A notebook is apparently executed by this ``runpy.py`` script in lib/python, so that's the generated name.

Is there a consistent way to get the path of a jupyter notebook from inside the session?

Bokeh 0.12.7dev3

**Comment by mattpap** [comment]
I'm pretty sure a similar problem was already handled at some point. `runpy` in file name is familiar to me.

**Comment by damianavila** [comment]
> Is there a consistent way to get the path of a jupyter notebook from inside the session?

Nop, because the kernel does not know anything about the server... by design.

You have **hacky** ways to do it, some useful references:

* https://github.com/jupyter/notebook/issues/1000
* https://stackoverflow.com/questions/12544056/how-do-i-get-the-current-ipython-notebook-name
* https://stackoverflow.com/questions/41782255/how-to-get-the-current-jupyter-notebook-servers-in-python

**Comment by bryevdv** [comment]
Personally I am fine with making filenames required at all times.

**Comment by mattpap** [comment]
I personally like this feature, though it needs some refinement in corner cases.

**Comment by hsparra** [comment]
For automatically generated names, it would be nice to have the timestamp or something similar so it could be identified in what order the PNGs were generated, such as with a batch or unattended process.

**Comment by wqp89324** [comment]
Anyway to specify the location where export_png saves the file? either a local location or on aws?
