### ISSUE TITLE
Discussion: should ``bokeh.io.export_svgs`` coerce all Plot.output_backend values to SVG?

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6561]
There's been an instance of user confusion where they passed a layout to ``bokeh.io.export_svg`` and no SVGs were created. The issue was that they hadn't activated the SVG backend for any of their plots using the ``Plot.output_backend="svg`` attr. Should ``export_svg`` coerce all plots in a layout to be SVG plots to prevent this issue? Is this going to cause more confusion than be helpful?

There's currently a warning when ``export_svg`` doesn't capture any SVG plots, ``WARNING:bokeh.io:No SVG Plots were found.``. Could it be more clear?

Bokeh 0.12.7dev3

**Comment by bryevdv** [comment]
In general I think the export functions should be free to coerce whatever property values they need to (e.g. plot size or backend) as long as they restore them.

**Comment by canavandl** [comment]
will require doing something like: https://github.com/bokeh/bokeh/blob/master/bokeh/embed.py?utf8=%E2%9C%93#L261

**Comment by bryevdv** [comment]
There hasn't been alot of clamor or confusion over this, so just going to close for now. Can revisit if people start having issues or request it.
