### ISSUE TITLE
Add more examples to bokehjs

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6574]
Existing examples don't show much. We need to show a reasonable selection of features. This is related to issue #5877.

This should include:
- [ ] plotting API
- [x] categorical axes (PR #6647)
- [ ] layouts
- [ ] widgets

**Comment by David-Herman** [comment]
Thank you, Also perhaps you can include elements of my existing questions.
https://stackoverflow.com/questions/44784697/bokehjs-title-text-alignment

**Comment by mattpap** [comment]
A new set of examples was added under [bokehjs/test/integration/examples](https://github.com/bokeh/bokeh/tree/796ac4803ae500c9d17b36b5751746472e5a3705/bokehjs/test/integration/examples) across multiple recent PRs. Those examples are under visual tests, the same as we use for visual integration testing.
