### ISSUE TITLE
Bokeh server plots not showing in Internet Explorer

### ISSUE THREAD

**Issue by ojss** [bokeh/bokeh#6579]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
OS: Windows 7(Enterprise edition)
Python: 2.7.13
Bokeh: 0.12.6
Browser: Internet explorer 11
#### Description of expected behavior and the observed behavior
Expected: Tried out the sine wave example in demos. Plot is expected to show up when webpage is first opened(localhost:5006)

Observed: Plot shows for a fraction of a second and then vanishes. Only when I modify the sliders a bit, does the graph reappear properly. This happens with every example.
**However** the plots on https://demo.bokehplots.com show up fine.

#### Complete, minimal, self-contained example code that reproduces the issue
Use the sliders example in the repo.

#### Stack traceback and/or browser JavaScript console output
```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: custom_app
HTML1300: Navigation occurred.
File: custom_app
[bokeh] setting log level to: 'info'
[bokeh] Websocket connection 0 is now open
[bokeh] WidgetBox mode is fixed, but no width specified. Using default of 300.
Bokeh items were rendered successfully
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/10680833/27789720-38f18358-600b-11e7-9c39-3163b11f7164.png)

**Comment by bryevdv** [comment]
@mattpap Any thoughts offhand?

**Comment by mattpap** [comment]
No. Lack of error messages is the worst case scenario here. Mostly likely something is `undefined` at some point and overuse of `?` operator allows for a silent failure.

**Comment by ojss** [comment]
The weirdest part is that the plots on the demo site work perfectly.

Another thing I just noticed was this: when I embed the server in a Ipython notebook, it works perfectly in chrome but on IE i got this error message: `object doesn't support this action` and the IE debugger was pointing to a `throw` statement somewhere.

**Comment by bryevdv** [comment]
> The weirdest part is that the plots on the demo site work perfectly.

The demo site is running at least a few versions behind, I have not had the opportunity to re-deploy with current Bokeh versions.

**Comment by ojss** [comment]
May I please know which version exactly?

**Comment by bryevdv** [comment]
Looks like `0.12.3`

**Comment by djmannion** [comment]
I have come across this issue in some of my own code. I have found that converting the numpy arrays to lists (using ``.tolist()``) prior to creating or updating a ``ColumnDataSource`` fixes the problem.

I have tried doing this with the sliders example, and it seems to work OK in Internet Explorer after making these changes.

**Comment by bryevdv** [comment]
This was fixed in https://github.com/bokeh/bokeh/issues/6982 and will be present in `0.12.10`

**Comment by cloud-rocket** [comment]
it appears once again in 0.12.13:

Looks like it disappears on second render and it is similar problem as this one - https://github.com/bokeh/bokeh/issues/6217
