### ISSUE TITLE
TapTool(behavior='inspect', callback=OpenURL()) can't work due to empty selection

### ISSUE THREAD

**Issue by niki-sp** [bokeh/bokeh#6580]
bokeh v 0.12.6 on Ubuntu 17.04

`TapTool(behavior='inspect')` is incompatible with OpenURL callback. Apparently OpenURL can't find selection information from inspect tool.

**Comment by bryevdv** [comment]
Please provide a complete minimal code sample that reproduces the problem.

**Comment by bryevdv** [comment]
Actually, given that this can be accomplished with a few lines of JS in a `CustomJS` callback, and I'm somewhat inclined to deprecate/get rid of the `OpenURL` callback entirely, I am going to close this.
