### ISSUE TITLE
deprecate OpenURL?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6581]
`OpenURL` has slightly different semantics that standard callbacks, causing confusion and problems (e.g. https://github.com/bokeh/bokeh/issues/6580). I'd like to propose deprecating it in `0.12.7` and removing in `1.0` The change would be accompanied by documentation support in the user's guide showing how to do the same sort of thing with a standard `CustomJS` callback, and a deprecation message pointing there. 

ping @bokeh/dev

**Comment by canavandl** [comment]
I'm supportive of this. The OpenURL callback has been (to me) a greater source of confusion than value due to it's non-standard semantics.

**Comment by bryevdv** [comment]
OK I had a better/simpler idea: simply fix the tap tools dumb calling convention to match the standard one, and keep open url (but update it to continue working). It seems to be a popular thing, so this avoids a deprecation, but makes the tap tool callback useful with "normal" CustomJS which was the main problem.
