### ISSUE TITLE
print a number in bokeh app

### ISSUE THREAD

**Issue by moshiour** [bokeh/bokeh#6587]
Hi,

Is there any way to show a output number with bokeh app? 

For example, I would like to see the calculated results with figures
=======================
import numpy as np
from bokeh.plotting import output_file, figure, show

x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)

output_file("legend_labels.html")

p = figure()

p.circle(x, y, legend="sin(x)")

t=30
print(t)
show(p)
================================
I am using Bokeh 0.12.6 with python 3.6
 
Thank you in advance!!!!!!!!!!

with best regards,

Moshiour

# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

**Comment by bryevdv** [comment]
As stated above, the issue tracker is not the place for general support and usage questions. For that please use the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
