### ISSUE TITLE
Save tool not functioning for webgl backend figures 0.12.6 regression

### ISSUE THREAD

**Issue by DuCorey** [bokeh/bokeh#6592]
Currently when using the save tool with a plot that has been generated with WebGL nothing will happen.  The image will not be saved and no errors are reported in the console. 

This is a depreciation from 0.12.5 where the image saving works correctly.

There's also an error in the current webgl docs. The first example is used to illustrate the plot when not using webgl, but the code includes webgl in it.

```
output_file("scatter10k.html", title="scatter 10k points (no WebGL)")

p = figure(output_backend="webgl")
```

#### Complete, minimal, self-contained example code that reproduces the issue
Go to http://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html and the save button does not work for any of the webgl plots.
```
import numpy as np

from bokeh.plotting import figure, show, output_file

N = 10000

x = np.random.normal(0, np.pi, N)
y = np.sin(x) + np.random.normal(0, 0.2, N)

output_file("scatter10k.html", title="scatter 10k points (with WebGL)")

p = figure(output_backend="webgl")
p.scatter(x, y, alpha=0.1)
show(p)
```

If we got back to the 0.12.5 docs http://bokeh.pydata.org/en/0.12.5/docs/user_guide/webgl.html the save button works without an issue.

```
import numpy as np

from bokeh.plotting import figure, show, output_file

N = 10000

x = np.random.normal(0, np.pi, N)
y = np.sin(x) + np.random.normal(0, 0.2, N)

output_file("scatter10k.html", title="scatter 10k points (with WebGL)")

p = figure(webgl=True)
p.scatter(x,y, alpha=0.1)
show(p)
```

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Browser: Chrome 59.0.3071.115
OS: Windows 7

**Comment by DuCorey** [comment]
I believe I found the reason for this behavior. The current [save function](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/plots/plot_canvas.coffee#L665) checks for "canvas" or "svg" output_backend and does not check for "webgl" thus the save action is not dispatched.

Looking at the file history, previously (0.12.5) even when using webgl the save function worked identically for both default canvas or webgl i.e. saving straight to png. Can I assume that this behavior is still warranted? If so I think I can manage a fix for it myself and open up the PR.

**Comment by bryevdv** [comment]
@DuCorey A PR would be helpful and appreciated, thanks!
