### ISSUE TITLE
Add support for headless chrome/chromium

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6594]
At some point this should replace phantomjs in our image diff tests.

**Comment by mattpap** [comment]
I tested on Windows, and Chrome 61 (I presume also 60) does support headless mode and works perfectly. At this point there is no real reason to stick to phantomjs. We will need conda packages for chrome, and we will be able to proceed with integration.

**Comment by normaljosh** [comment]
colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'

p.circle(flowers["petal_length"], flowers["petal_width"],
         color=colors, fill_alpha=0.2, size=10)
         
export_png(p, filename=r"PATH.png",  webdriver=driver)

**Comment by normaljosh** [comment]
I was able to get bokeh working with headless chrome, on windows 10 and chrome 62. 

steps I took: 

- Install chrome webdriver from [https://sites.google.com/a/chromium.org/chromedriver/downloads](https://sites.google.com/a/chromium.org/chromedriver/downloads)
- Save driver file and note executable path
- use code below:

```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

options = Options()
options.add_argument("start-maximized")
options.add_argument("disable-infobars")
options.add_argument("--disable-extensions")
options.add_argument('--headless')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'PATH_TO_DRIVER')

from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers
from bokeh.io import export_png

#create some bokeh figure 'p'

export_png(p, filename=r"PATH.png",  webdriver=driver)
```

**Comment by eileenjkim** [comment]
Thanks @normaljosh - that script runs for me. However, it seems that the export_png using chrome takes a screenshot of the html file opened in a web browser, as opposed to what using phantomJS did - grab a picture of the whole plot. Any ideas on how to make your script pull the whole plot? A workaround is probably to minimize my html plot size so that it fits in a web browser, but would prefer to avoid that route if possible.

**Comment by dimab0** [comment]
I've got the same problem as Eileen, with the window size being too small.
