### ISSUE TITLE
Server url hard coded as localhost. With possible fix.

### ISSUE THREAD

**Issue by enfeizhan** [bokeh/bokeh#6598]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 0.12.6
python: 3.6
notebook: 5.0.0
jupyter: 1.0.0
jupyter_client 5.0.1
jupyter_console: 5.1.0
jupyter_core: 4.3.0
ipython: 6.0.0
ipython_genutils: 0.2.0
OS: ubuntu 16.04
brower: Chrome 58.0.3029.110 (64-bit)
#### Description of expected behavior and the observed behavior
What I tried to do was running a jupyter server on one computer and then opening up notebook_embed.ipynb on another computer through internet. The `show(app)` didn't show any figure.

This is caused by this line `script = autoload_server(url='http://127.0.0.1:%d%s' % (server.port, app_path))`  in the function `_show_notebook_app_with_state`. 

This is fine when jupyter notebook is run on localhost. But suppose now my server ip is 10.0.1.1 and client ip is 10.0.1.2. When this line is called, it creates js code on server (10.0.1.1). The code is sent to the client (10.0.1.2). When the browser on client sees this js code, it tries to fetch the figure from 127.0.0.1 instead of the server (10.0.1.1).

So I fixed the bug by changing the line to
```
script = autoload_server(url='http://%s:%d%s' % (notebook_url.split(':')[0], server.port, app_path))
```
In this case, you can specify the server ip by calling `show(app, notebook_url='10.0.1.1:8888')`. Now the browser on the client computer correctly sees to the bokeh server is on the server ip.

**Comment by bryevdv** [comment]
@enfeizhan are you interested in working up a small PR with this change?

**Comment by enfeizhan** [comment]
@bryevdv Sure. Already working with the fixed version.
