### ISSUE TITLE
bokeh server url hard coded as over  http.

### ISSUE THREAD

**Issue by enfeizhan** [bokeh/bokeh#6599]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 0.12.6
#### Description of expected behavior and the observed behavior
In function `_show_notebook_app_with_state` of `io.py`, the url for `autoload_server` is hard coded as http. Maybe an option can be developed to choose https where secure communication is required.

**Comment by bryevdv** [comment]
Now here:

https://github.com/bokeh/bokeh/blob/master/bokeh/io/notebook.py#L442

**Comment by bryevdv** [comment]
@enfeizhan There is now a PR for this feature. You can explicitly provide the protocol when supplying `notebook_url`. Can you test the PR? I don't know how to run the notebook such that a URL would be "https"

**Comment by bryevdv** [comment]
I believe this is now fixed but I do not have the capacity to test directly. Please re-open if any issue persists.
