### ISSUE TITLE
Downloading dependencies from scripts/deps fails

### ISSUE THREAD

**Issue by DuCorey** [bokeh/bokeh#6600]
I'm attempting to build Bokeh on the latest commit 90b941d. I'm following the recent changes to the build [guide](https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/dev_guide/setup.rst) as done in #6527, but the installing dependencies part fails. Here is the terminal output.

```
(bokeh-dev) corey@corey-UX31A:~/Projects/Coding/bokeh$ conda install `python scripts/deps.py build run test`
Traceback (most recent call last):
  File "scripts/deps.py", line 17, in <module>
    metadata, _, _ = api.render('conda.recipe')
ValueError: not enough values to unpack (expected 3, got 1)
Fetching package metadata .........

PackageNotFoundError: Package missing in current linux-64 channels: 
  - copying

```
I've had this fail on both my linux and windows machine. The only difference in the error message being the channel name in the `PackageNotFoundError`.

Furthermore, compared to the previous setup documentation, the part about building Bokehjs using gulp has been removed completely ([link](https://github.com/bokeh/bokeh/blob/0.12.6/sphinx/source/docs/dev_guide/setup.rst#building-bokehjs)). Is this step being moved elsewhere in the docs or are there plans to remove in a later release?

**Comment by bryevdv** [comment]
Oh, conda build changed. You will have to use <3.x for now

**Comment by bryevdv** [comment]
Moving this to `0.12.8` the solution (for now anyway) is just to not use `conda-build` 3.x I think the script will have to be written to use YAML directly and not use `conda-build` at all (the way it used to be basically) since I was not aware that `conda-build` can only be installed in root envs, which severely limits the utility of the scripts.

**Comment by mattpap** [comment]
> since I was not aware that conda-build can only be installed in root envs

That's a weird limitation, but maybe there are reasons.

**Comment by bryevdv** [comment]
This was done at some point, `scripts/deps.py` does not currently use the conda build API any longer
