### ISSUE TITLE
Circle radius with radius_units='data' not round?

### ISSUE THREAD

**Issue by rsgoodwin** [bokeh/bokeh#6603]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh=12.4
python=3.6.1
notebook=5.0
os=Windows 10
browser=edge, chrome
monitor resolution = 4k and 3000x2000 tested.

#### Description of expected behavior and the observed behavior
*expected behavior*:  A circle with center 0,0  and a specific radius=r should extend in x and y direction such that xmin, xmax = ymin, ymax = +/- r

*actual behavior*:  The xmin, xmax = +/-r as expected,  however,  the ymin, ymax does not extend to +/-r.  It appears the conversion between screen pixels and plot units is different in x vs y.  

Note:  The square below is plotted just as a reference.  On the monitor,  the square is not actually square - it is physically longer in Y direction (measured with a ruler).  This my be part of the problem.  However,  one might expect that a circle and square drawn with equal centers such that length of square = diameter of circle would result in the circle being nested perfectly in the square, with tangents at the center of the squares sides.

Perhaps I need some other "data" in the plot to force the scale differently? 

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, output_notebook, show
output_notebook()
```

trial 1 = no plot width, height specified (or set to equal values)

```
p = figure()
p.rect(0, 0, 300, 300, line_color='black')
p.circle(x=0, y=0, radius=150, line_color='black', 
         fill_color='grey',  radius_units='data')
p.axis.minor_tick_out = 0
show(p)
```

Changing the plot dimensions,  can get circle to fit in square with ~these settings

```
p2 = figure(plot_width=500, plot_height=465)
p2.rect(0, 0, 300, 300, line_color='black')
p2.circle(x=0, y=0, radius=150, line_color='black', 
         fill_color='grey',  radius_units='data')
p2.axis.minor_tick_out = 0

show(p2)
```

#### Stack traceback and/or browser JavaScript console output
NA

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/2280241/28071432-bfdc9f0c-6604-11e7-928c-99ce906f4f0f.png)

![image](https://user-images.githubusercontent.com/2280241/28072068-a549096c-6606-11e7-98f9-fa8e67dd4ea6.png)

**Comment by bryevdv** [comment]
It's not that the circles are not round (they are) it's that the squares are not square, because the distance per pixel is different in the x vs y directions. i.e., the "pixel" aspect ratio, and "data space" aspect ratios do not match. 

See #517 

You can either:

* arrange things so that the pixel and data aspect ratios match (i.e. by controlling the border around the central plot area and the data space ranges)

* use absolute pixel distances for everything

There is an open issue be able to specify an aspect ratio for the central plot region and have bokeh maintain it.

**Comment by rsgoodwin** [comment]
Got it - thanks! - I will review #517 in more detail.   

FYI - From my R lattice days,   there was aspect= attribute that could be set to "fill', 'xy', a ratio or 'iso'.  When set to 'iso',  the x and y axis are set such that relation of physical distance and screen distance were the same for both axis.  I guess it must know something about the screen x and y resolution,  so it would not have to maintain anything.  Here is the definition from the R Lattice PDF:  

![image](https://user-images.githubusercontent.com/2280241/28073357-4b388d9a-660a-11e7-9bb6-d6be3ad64aaa.png)

**Comment by bryevdv** [comment]
@rsgoodwin I think if you can assume square pixels, you don't need to know the density. The first step for us is to be able enforce and aspect ratio on the central plot area (in terms of pixels) Once that is possible I think we can add some futher configuration to plots or ranges to enforce that the "data" aspect ratio always matches the screen one.

**Comment by alexeymuranov** [comment]
> It's not that the circles are not round (they are) it's that the squares are not square

I disagree: the square is a square, because both sides measure 300 according to the marks on the axes.

If we are talking about the physical sizes on a screen, then nothing is a perfect square or a circle, and different screens can produce different results.

**Comment by bryevdv** [comment]
> I disagree: the square is a square, because both sides measure 300 according to the marks on the axes.

You are incorrect. The axes measure **DATA SPACE**, not pixels. The issue is that "300" in the x direction takes up a **different number of pixels** than "300" in the y direction.
