### ISSUE TITLE
"TapTool" is incorrectly called "TapSelectTool" in the reference documentation

### ISSUE THREAD

**Issue by MarcusOlivecrona** [bokeh/bokeh#6606]
"TapTool" is incorrectly called "TapSelectTool" in the reference documentation
-------------------------------------------------------------------------------------------------------

In the Bokeh documentation, "TapTool" is described under the name "TapSelectTool".

See http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html.

Attempting to import "TapSelectTool" under bokeh 0.12.6 gives an Import Error. Importing and using "TapTool" works just fine.

**Comment by bryevdv** [comment]
@MarcusOlivecrona can you check the link you provided? There is neither TapTool nor TapSelectTool on the page linked.

**Comment by MarcusOlivecrona** [comment]
@bryevdv You're right, I made an edit to the correct link.

Here is a screen shot of the docs:

![image](https://user-images.githubusercontent.com/23477216/28124207-4a84da7e-6723-11e7-9af7-284e82ecb3b1.png)

Here is a screenshot from bokeh/models/tools.py in bokeh 0.12.6:

![image](https://user-images.githubusercontent.com/23477216/28124347-ae4ff322-6723-11e7-9a30-9d3d99a0a2a7.png)

And here trying to import both "TapSelectTool" and "TapTool" (only succeeding for the second):
![image](https://user-images.githubusercontent.com/23477216/28124631-8d3db966-6724-11e7-80be-89f4be7ce160.png)

**Comment by bryevdv** [comment]
@MarcusOlivecrona awesome, thanks
