### ISSUE TITLE
Updating Layout in Tabs Widget

### ISSUE THREAD

**Issue by gmomo** [bokeh/bokeh#6613]
Hello,

I have a Stacked Bar Chart using Charts module which is modified using a dropdown menu. In the update() function, it creates a new chart and adds it to the layout.(disp_row.children[0] = p_bar). This works fine as standalone, but when I put the entire layout in a Tabs widget, the callback destroys all other plots. 
I know, about the vbar method, but I have 9 rows of stacked data and it becomes to cumbersome. 

Any help regarding this ? TIA.

**Comment by mattpap** [comment]
Which version of bokeh do you use?

**Comment by gmomo** [comment]
0.12.5

**Comment by gmomo** [comment]
Hi, 

It is working fine in 0.12.6. Thanks a lot.
