### ISSUE TITLE
Best way to update Streams when running Holoviews 

### ISSUE THREAD

**Issue by shaginhekvs** [bokeh/bokeh#6617]
When using holoviews DynamicMap attached to a Stream (times) like below and running a Bokeh Server , which is the best way for updating the Stream from another thread. Bokeh Server description says that its' best to use doc.add_next_tick_callback but the update using doc.add_next_tick_callback doesn't change the plot, and the plot has to be directly updated by using times.event(....). Is it safe to update the times stream in such a manner without going through the add_next_tick_callback method? If not then what else can be done in this situation?

```
dmap=hv.DynamicMap(rectangle,streams=[times])
hv_progressBar=renderer.get_plot(dmap,doc)
         
times=Stream.define('times',x=pd.to_datetime(dt.now()).value,x_end=pd.to_datetime(dt.now()).value,xr_start=pd.to_datetime(dt.now()-td(weeks=10)).value,xr_end=pd.to_datetime(dt.now()).value)()

def add_progress_callback(start_time,end_time,x_bot_lim,x_up_lim):
     print('creating times event')
     times.event(x=pd.to_datetime(start_time).value,x_end=pd.to_datetime(end_time).value,\
                 xr_start=pd.to_datetime(x_bot_lim).value,xr_end=pd.to_datetime(x_up_lim).value)
     '''
     doc.add_next_tick_callback(partial(times.event,x=pd.to_datetime\
                                        (start_time).value,x_end=pd.to_datetime(end_time).value,\
                                        xr_start=pd.to_datetime(x_bot_lim).value,xr_end=pd.to_datetime(x_up_lim).value))
     '''
```

**Comment by bryevdv** [comment]
@shaginhekvs holoviews is a separately maintained project with its own developers and repo. Issues that intersect with holoviews can best be addressed by the holoviews developers, so they should be filed in the holoviews issue tracker

https://github.com/ioam/holoviews
