### ISSUE TITLE
BokehJS not loading in jupyterlab

### ISSUE THREAD

**Issue by timothydmorton** [bokeh/bokeh#6637]
When I run `output_notebook()` in a notebook under JupyterLab, I get a message reading "Loading BokehJS ..." but I don't get the friendly "BokehJS 0.12.6 successfully loaded." message that appears when I run the same from a notebook outside the Lab environment.  Subsequently, when I try to `show()` a bokeh figure, nothing appears.  I'm running Bokeh 0.12.6 and jupyter 4.3.0 with python 3, using Chrome 58.0.3029.110 on Mac OS 10.11.6.

**Comment by bryevdv** [comment]
JuptyterLab integration is still an ongoing process, I can't speculate when it will be done.

**Comment by timothydmorton** [comment]
Alright, good to know-- thanks!

**Comment by Lenz81** [comment]
Here is the corresponding discussion from the jupyterlab issues page:
[https://github.com/jupyterlab/jupyterlab/issues/2710](https://github.com/jupyterlab/jupyterlab/issues/2710)

**Comment by tobsecret** [comment]
Here the explanation the Jupyterlab devs gave me:
>Bokeh is inlining a <script> tag in its HTML output. We disallow arbitrary script execution in outputs in JLab because it's a huge security risk and the JLab extension system makes it easier to build Javascript viewers for things in a safer fashion.

**Comment by dclong** [comment]
Is there anyway to talk to developers of JupyterLab to make an exception for Bokeh to run JS script?

**Comment by bryevdv** [comment]
I'm 100% certain that they would not do that.

**Comment by bryevdv** [comment]
Hey all, I am closing this discussion in favor of #6700 which will be the high level coordination issue for this task
