### ISSUE TITLE
Bokeh.Bar bar_width not working!

### ISSUE THREAD

**Issue by Jerryzhuht** [bokeh/bokeh#6640]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh = 0.12.4, IE, IBM, WIN7

#### Description of expected behavior and the observed behavior
in p= Bar(....)
I specify bar_width = 1 (or 2,3...)
the plot doesn't change.

**Comment by bryevdv** [comment]
`bokeh.charts` is no longer part of Bokeh. It is now a separate repo and project: https://github.com/bokeh/bkcharts All issues regarding it should be filed there. However I should add that there is currently no one maintaining `bkcharts`. For a high level API on top of Bokeh, http://holoviews.org/ is already better than `bokeh.charts` and more importantly, is maintained by an active team.
