### ISSUE TITLE
export_csv example under 0.12.7dev11 doesn't resize table

### ISSUE THREAD

**Issue by larisahax** [bokeh/bokeh#6642]
Running example export_csv from https://github.com/bokeh/bokeh/tree/master/examples/app/export_csv

under 0.12.7dev11 the table doesn't resize and extra rows are filled with 'undefined', '$NaN'.
The number of rows is 248 and doesn't change when moving the slider.
The rows after 248 are not shown.

Under 0.12.6 everything works perfect.

**Comment by bryevdv** [comment]
ping @mattpap can confirm this in `master` have not had a chance to bisect yet.

**Comment by bryevdv** [comment]
<img width="1081" alt="screen shot 2017-07-19 at 09 20 33" src="https://user-images.githubusercontent.com/1078448/28371791-89c1bcc6-6c63-11e7-97f9-74a50521e2cf.png">
