### ISSUE TITLE
Bokeh not readaing python dictionaries

### ISSUE THREAD

**Issue by nagnath006** [bokeh/bokeh#6646]
`Bar` Chart Not taking python dictionaries.
`import pandas as plt
import sqlite3
from bokeh.charts import Bar, output_file, show
from bkcharts import *
from datetime import datetime,date
from dateutil import parser

con = sqlite3.connect("database.sqlite")
cur = con.cursor() 	 	
age_set = {}

today = date.today()
for i in cur.execute('select player_name,birthday from player LIMIT 30'):
    x =  str(i[0]).split(' ')
    formatted_date = parser.parse(i[1])
    age= today.year - formatted_date.year - ((today.month, today.day) <    

(formatted_date.month,formatted_date.day))
    age_set[i[0]] = age

bar2 = Bar(age_set, values='timing', label=['interpreter', 'sample'],
           agg='mean', title="Python Interpreters", width=400)
output_file('area.html')
show(bar2)`

Console showing     **raise TypeError('Input of table-like dict must be column-oriented.')
TypeError: Input of table-like dict must be column-oriented.** error.

**Comment by bryevdv** [comment]
`bokeh.charts` is no longer part of Bokeh. It is now a separate repo and project: https://github.com/bokeh/bkcharts All issues regarding it should be filed there. However I should add that there is currently no one maintaining `bkcharts`. For a high level API on top of Bokeh, http://holoviews.org/ is already better than `bokeh.charts` and more importantly, is maintained by an active team.
