### ISSUE TITLE
Add more x axis ticks and labels to datetime axis...

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#665]
From stackoverflow: http://stackoverflow.com/questions/23915275/how-do-you-add-more-x-axis-ticks-and-labels-to-datetime-axis-using-pythons-boke

The user wants to add more ticks and label in his/her candlestick plot.
We discussed this issue with @bryevdv, adding some points below:
* one solution would be to add a "desired_n_ticks" property to axis.coffee and have it pass that value to  to ticker.get_ticks (right now it uses the default of 6, always)
* there is no way to make a hard specification of the number of ticks on the existing tickers, you'd need to make a new ticker that doesn't try to be so smart

**Comment by rht** [comment]
:+1:  this issue is a blocker

**Comment by bryevdv** [comment]
Another option that might work more simply with the existing code is to add `min_ticks` property, but I'd have to look more closely. There are probably cases when there is no set of "nice numbers" with the required minimum size, and then what do you do?

**Comment by bryevdv** [comment]
See #1668

**Comment by damianavila** [comment]
This was solved in #2186
