### ISSUE TITLE
Documentation for `CrosshairTool` not updated

### ISSUE THREAD

**Issue by jrwalk** [bokeh/bokeh#6651]
(bokeh 0.12.6, Python 3.6.1, OSX 10.11.4)

At present, the documentation for `bokeh.models.CrosshairTool` states that the attribute `dimensions` expects a list of the selected plotting dimensions (e.g., 'width' and/or 'height').  In the current version, however, this attribute expects a String of one of the enumerated values ('width','height','both') (this is reflected in the docstring of the code itself).

**Comment by bryevdv** [comment]
@jrwalk If you could submit a quick Pull Request to fix this it would be extremely appreciated.

**Comment by jrwalk** [comment]
@bryevdv done in PR #6652
