### ISSUE TITLE
HoverTool formatters attribute missing

### ISSUE THREAD

**Issue by kyletm** [bokeh/bokeh#6661]
It appears that the `formatters` attribute is missing from HoverTool. I followed the [User Guide](http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields) as well as attempted running the [sample code](https://github.com/bokeh/bokeh/blob/3224d8e8a362574096df6a2a5ba47db6f5802533/sphinx/source/docs/user_guide/examples/tools_hover_tooltip_formatting.py) from GitHub to replicate the User Guide and received the following error:

"AttributeError: unexpected attribute 'formatters' to HoverTool, possible attributes are anchor, attachment, callback, js_event_callbacks, js_property_callbacks, line_policy, mode, name, names, plot, point_policy, renderers, show_arrow, subscribed_events, tags or tooltips"

Versions: Bokeh 0.12.6, Python 3.6.1, Anaconda 4.4.0

Expected Behavior: I should be able to reproduce the exact same graph as shown in the User Guide.

Observed Behavior: I received the aforementioned `AttributeError`.

Self Contained Code Example: Attempt to run the [source code for the User Guide HoverTool formatter](https://github.com/bokeh/bokeh/blob/3224d8e8a362574096df6a2a5ba47db6f5802533/sphinx/source/docs/user_guide/examples/tools_hover_tooltip_formatting.py) to replicate the error.

Full traceback:

Traceback (most recent call last):

  File "<ipython-input-6-3750417ce8da>", line 1, in <module>
    runfile('/Users/hca482/Documents/GitHub/bokeh-0.12.6/sphinx/source/docs/user_guide/examples/tools_hover_tooltip_formatting.py', wdir='/Users/hca482/Documents/GitHub/bokeh-0.12.6/sphinx/source/docs/user_guide/examples')

  File "/Users/hca482/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/Users/hca482/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/hca482/Documents/GitHub/bokeh-0.12.6/sphinx/source/docs/user_guide/examples/tools_hover_tooltip_formatting.py", line 43, in <module>
    mode='vline'

  File "/Users/hca482/anaconda/lib/python3.6/site-packages/bokeh/model.py", line 226, in __init__
    super(Model, self).__init__(**kwargs)

  File "/Users/hca482/anaconda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 241, in __init__
    setattr(self, name, value)

  File "/Users/hca482/anaconda/lib/python3.6/site-packages/bokeh/core/has_props.py", line 277, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))

AttributeError: unexpected attribute 'formatters' to HoverTool, possible attributes are anchor, attachment, callback, js_event_callbacks, js_property_callbacks, line_policy, mode, name, names, plot, point_policy, renderers, show_arrow, subscribed_events, tags or tooltips

**Comment by bryevdv** [comment]
You have an installation problem/corruption, or you are running a different (older) version of Bokeh than you think you are (possibly you installed bokeh in one environment, but are running python out of another environment with tho older version installed).Or possibly you have not updated Bokeh? Bokeh `0.12.6` is newer than Anaconda 4.4, so unless you have updated explicitly, you are running Bokeh 0.12.5 (which is too old for the hover tool formatters feature)
