### ISSUE TITLE
Legend click policy on touchscreens

### ISSUE THREAD

**Issue by jhowe8** [bokeh/bokeh#6662]
I have tried using a an iphone, a samsung Note 2 (android) and a touch screen laptop to click the legends on or off, but to no avail. Only clicking with a mouse has proved successful.

bokeh version: 0.12.6
python version: 2.7

sample code:
plot.legend.click_policy = "hide"

**Comment by mattpap** [comment]
~~Depends on PR #14028~~. It's coincidentally fixed by PR #14028.
