### ISSUE TITLE
PackageNotFoundError

### ISSUE THREAD

**Issue by lhaeberle** [bokeh/bokeh#6663]
this issue is probably an anaconda one: see https://github.com/ContinuumIO/anaconda-issues/issues/3427

To export Bokeh plots to *png files I need to install

`conda install selenium phantomjs pillow`

but a PackageNotFoundError occurs:

```
[root@HE sensorAll]# conda install selenium phantomjs pillow
Fetching package metadata .........

PackageNotFoundError: Package missing in current linux-64 channels: 
  - selenium

[root@HE sensorAll]# conda install phantomjs pillow
Fetching package metadata .........

PackageNotFoundError: Package missing in current linux-64 channels: 
  - phantomjs

```
This happens on both macOS (Sierra) and CentOS Linux release 7.3.1611 (Core)
Anaconda  and Bokeh are up to date:

```
b|503|~$ bokeh --version
0.12.6

[root@HE sensorAll]# anaconda --version
anaconda Command line client (version 1.6.3)
[root@HE sensorAll]# conda update conda
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /root/anaconda3:
#
conda                     4.3.22                   py36_0  
```
Any idea where to find both selenium and phantomjs? Thanks.

**Comment by bryevdv** [comment]
I believe the user guide instructions should point at the bokeh channel, e.g. 
```
conda install selenium phantomjs pillow
```
ping @canavandl

**Comment by canavandl** [comment]
I see that I have phantomjs installed from conda-forge. (so ``conda install -c conda-forge phantomjs``)

**Comment by bryevdv** [comment]
C-F won't support python 3.4 so I think we will be stuck putting these on the Bokeh channel

**Comment by lhaeberle** [comment]
Thank you, installation worked...
