### ISSUE TITLE
Update sliders in examples 

### ISSUE THREAD

**Issue by clairetang6** [bokeh/bokeh#6666]
Some of the sliders in various example apps and example plots (including some in the documentation) need to be updated to work well with the new defaults. 

For example, with the new default format of "0,00" in ohlc:
![ohlc](https://user-images.githubusercontent.com/4241244/28508102-43d070d0-6fed-11e7-8c97-842644295756.gif)
and gapminder:
![image](https://user-images.githubusercontent.com/4241244/28508126-737f8154-6fed-11e7-99ff-b88d55dd610f.png)

And with the new default step of 1, sliders.py should be updated to have specified smaller step. 

I also wonder if it might be possible to set the format based on other values, like the step if that's provided.

**Comment by bryevdv** [comment]
this was done, integer steps now show as integers
