### ISSUE TITLE
Creating a ColumnDataSource with a DataFrame makes it impossible to use streaming

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#6667]
Bokeh 0.12.6

Executing
```python
from bokeh.models import ColumnDataSource
import pandas as pd

d = pd.DataFrame({'a': [1]})
cds = ColumnDataSource(d)
cds.stream(ColumnDataSource.from_df(d))
```
leads to
```
AttributeError: 'Series' object has no attribute 'extend'
```

The reason is that `ColumnDataSource._data_from_df` uses `DataFrame.to_dict('series')` but `PropertyValueDict._stream` assumes the columns to be lists, or at least something that has `extend` method.

On a related note - probably making `steam` also accept a raw `DataFrame` would make the interface more cohesive.

**Comment by bryevdv** [comment]
@p-himik Thanks for the report. Would you be interested in working up a small PR to improve things? The current core team is pretty swamped so I can almost certainly guarantee that you would be able to get to this before we would. The only real complication is that we don't want to introduce a hard dependency on pandas, so the code will need to use our `optional_import` to see if pandas is present before type checking (or else maybe a duck typing check for [`Series.append`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.append.html) would work too)

**Comment by p-himik** [comment]
I'll definitely try sometime during the week.

**Comment by bryevdv** [comment]
Awesome, let me know if I can answer any questions!

**Comment by 0zeroth** [comment]
I happened to be working around that problem. Below is an example workaround, and the comments point out exactly where the problems happen in bokeh code (as far as I managed to figure out). Hope this may be useful.

The relevant part is in the `callback()` function, and is as simple as converting the dataframe to a `dict` of `np.ndarray` objects.

```
import six
from bokeh.application import Application
from bokeh.application.handlers import FunctionHandler
from bokeh.document import Document
from bokeh.models import ColumnDataSource
from bokeh.plotting import Figure

from bokeh.server.server import Server

import pandas as pd
import numpy as np

def modify_doc(doc):
    """

    :param Document doc:
    :return:
    """
    df = pd.DataFrame(
        index=pd.date_range('now', periods=30, freq='T'),
        columns=['A', 'B', 'C'],
        data=np.cumsum(np.random.standard_normal((30,3)), axis=0)
    )

    cds = ColumnDataSource(df)
    figure = Figure(x_axis_type="datetime")
    figure.line("index", "A", source=cds)
    figure.line("index", "B", source=cds)
    figure.line("index", "C", source=cds)

    doc.add_root(figure)

    store = {'df': df}
    def callback():
        # Two problems with bokeh 0.12.6
        #
        # 1. PropertyValueDict._stream checks for np.ndarray but not for pd.Series,
        #    so we need to convert to a dict of np.values ourselves
        #
        # 2. By this point, by some magic, the index has been transformed to milliseconds since epoch
        #    I couldn't figure out where - it happens during serialization but where does that change
        #    get persisted back to the ColumnDataFrame obejct?
        #    Anyway, we need to make that transformation manually...
        #
        df = store['df']
        new_df = pd.DataFrame(
            index=df.index + pd.to_timedelta('30m'),
            columns=df.columns,
            data=np.random.standard_normal((30,3))
        )
        # cds.stream(df)        # This would be nice!

        stream_data = {}
        for k,v in six.iteritems(ColumnDataSource.from_df(new_df)):
            tmp = v if isinstance(v, np.ndarray) else v.values
            if tmp.dtype.kind=='M':
                tmp = tmp.astype('datetime64[us]').astype('int64') / 1000.
            stream_data[k] = tmp

        cds.stream(stream_data)
        store['df'] = new_df

    doc.add_periodic_callback(callback, 1 * 1000)

if __name__ == '__main__':

    bokeh_app = Application(FunctionHandler(modify_doc))
    server = Server({'/': bokeh_app})
    server.run_until_shutdown()
```

**Comment by p-himik** [comment]
@bryevdv Would it make sense to also allow Series streaming - to just add one row to a ColumnDataSource?

**Comment by bryevdv** [comment]
@p-himik apologies for any confusion, thats what I was suggesting about, that the streaming code should check for Pandas series and use `Series.append` to implement streaming on series. Though perhaps there is a better way to implement that ads an entire row at once.

**Comment by p-himik** [comment]
@bryevdv Could you please elaborate on your comment in `bokeh/core/property/containers.py`?
```python
        # TODO (bev) Currently this reports old differently for array vs list
        # For arrays is reports the actual old value. For lists, the old value
        # is actually the already updated value. This is because the method
        # self._saved_copy() makes a shallow copy.
```
Below it, we indeed see
```python
L = self[k]
L.extend(new_data[k])
```
which edits the list in-place. Is there anything preventing us from writing `data = self[k] + new_data[k]` and calling `__setitem__` as in the case of `np.ndarray` instead?
If nothing other than the performance considerations are there any consequences of reporting `old` as being the same as `new_data`?

**Comment by 0zeroth** [comment]
Below is my final solution, that wraps the solution I posted above into a class. Hope it helps.

One nasty bit is I need to duplicate the serialization code that converts the datetime. It is copied from `bokeh.util.serialization.transform_array` but I only copied a small part of the entire function.

I would suggest the bokeh code that does this be factored our a little so it can be re-used - but if someone copies this for use double check you don't need all of the cases handled in `bokeh.util.serialization.transform_array`

A further complication is the data stored in the `ColumnDataStore` changes between construction and serialization. So you get different behaviour is you `construct -> stream -> connect to document` vs `construct -> connecto to document -> stream`. 

The second case is really the only usual one, but I played with the first one during unit-testing, and was surprised that cases that worked there would fail in production. In particular, the conversion from `datetime64` to `int` only happens after the model is serialised.

```
class PatchedColumnDataSource(ColumnDataSource):
    """Extend ColumnDataSource to better handle Pandas dataframes"""

    # These are undocumented in bokeh, but required to inform bokeh about what to use on the BokehJS side
    # Since we only want to modify some functionality on the python side,
    #  we tell bokeh to use the parent JS object
    # See https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/nbGXAqsE564
    __subtype__ = "PatchedColumnDataSource"
    __view_model__ = "ColumnDataSource"

    def stream(self, new_data, rollover=None, setter=None):
        # Two problems with bokeh 0.12.6
        #
        # 1. PropertyValueDict._stream checks for np.ndarray but not for pd.Series,
        #    so we need to convert to a dict of np.values ourselves
        #
        # 2. By this point, by some magic, the index has been transformed to milliseconds since epoch
        #    I couldn't figure out where - it happens during serialization but where does that change
        #    get persisted back to the ColumnDataFrame obejct?
        #    Anyway, we need to make that transformation manually...
        #
        if isinstance(new_data, pd.DataFrame):
            stream_data = {}
            for k,v in six.iteritems(ColumnDataSource.from_df(new_data)):
                tmp = v if isinstance(v, np.ndarray) else v.values

                if tmp.dtype.kind=='M':
                    tmp = tmp.astype('datetime64[us]').astype('int64') / 1000.    # See bokeh.util.serialization.transform_array
                stream_data[k] = tmp
        else:
            stream_data = new_data

        super(PatchedColumnDataSource, self).stream(stream_data)
```

**Comment by p-himik** [comment]
Ping @bryevdv 
I'm still not sure what the implications of that TODO are. :)

**Comment by bryevdv** [comment]
@p-himik sorry I missed the question

> If nothing other than the performance considerations are there any consequences of reporting old as being the same as new_data?

It's an annoying quirk but I also think it's a corner case not often encountered in real practice. Basically, I'd say don't worry about that at all, at least for now.

**Comment by p-himik** [comment]
@bryevdv But is there any reason not to use `list1 + list2` instead of `list1.extend(list2)`? Why I asking, is that it would not only remove that long `TODO`, but also somewhat simplify the code that I'm writing. If there are no objections against using `list1 + list2`, I'd go with it.
The performance difference is negligible, I think:
```
%timeit list(range(10000)).extend(list(range(10000)))
1000 loops, best of 3: 1.87 ms per loop

%timeit list(range(10000)) + list(range(10000))
100 loops, best of 3: 2.32 ms per loop
```

**Comment by bryevdv** [comment]
@p-himik I can't think of any reason *offhand* besides efficiency, but this is also at a very low level so there may be details I am forgetting. A quick smoke test would be to just make the change and see if any tests break. 

That said I think your benchmark is a bit flawed, it's testing the time to execute `list(range(10000))` every time, which is considerable. I looked at this:

```
In [7]: x = list(range(10000))

In [8]: y = list(range(10000))

In [9]: %timeit x + y
10000 loops, best of 3: 65.5 µs per loop

In [10]: %timeit list(range(10000)).extend(list(range(10000)))
1000 loops, best of 3: 352 µs per loop

In [11]: %timeit list(range(10000)).extend(y)
10000 loops, best of 3: 195 µs per loop
``` 
Under the assumption that the difference in the last two, 352 - 195 = 157, accounts for one of the list creations, then we can approximate 195-157 = 38ms as the actual time difference for just the `extend` operation. That's almost a 2x difference which I would say is not insignificant. There are folks using Bokeh in very intensive applications and are already asking to find places to reduce overhead. I think my inclination is to keep things as fast as possible in this one code path.
