### ISSUE TITLE
Bokeh gallery thumbnail size

### ISSUE THREAD

**Issue by michaelaye** [bokeh/bokeh#6668]
Using Chrome on macOS 10.12.5 on a laptop (hence small window size), the icons for the server examples appear very small on the Bokeh gallery page.

I'm actually mightily impressed about the auto-scaling thumbnails, have never seen something like that (and I'm W3-ing since the beginning ;), but I feel the auto-scale factor could be improved a bit.

<img width="717" alt="screenshot 2017-07-24 13 15 08" src="https://user-images.githubusercontent.com/69774/28540348-4b962e6a-7072-11e7-936f-735c9186b3db.png">

**Comment by bryevdv** [comment]
Thanks for the report, we are just using Bootstrap for this section but will investigate ways to make it better across browsers

**Comment by bryevdv** [comment]
Going to close this with `noaction`. I'd like to re-do the gallery format in a significant way that will obviate this issue, but that will be tracked elsewhere
