### ISSUE TITLE
Axes' tick labels are trimmed when moving plot

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#6676]
According to the output of `Bokeh.version` in the JS console, the page at https://demo.bokehplots.com/apps/sliders uses Bokeh 0.12.3. If you move the plot around (say, move it up to see negative values on the Y axis), you'll see that the plot width changes to make all axes' tick labels visible.

Now, if you serve the same app with Bokeh 0.12.6, you'll notice that the behavior is different - the width is not changed and the labels get trimmed.

Probably it's normal as many people desire a constant size of the plot itself. In this case, is there any way to make sure that the axes' tick labels are not trimmed at least within some range?

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mrocklin** [comment]
I may have run into this as well.  I was working with a streaming timeseries plot.  I found that my tick labels on both sides were removed.  At the suggestion of @bryevdv I was able to fix this by setting values for `fig.min_border_top` and `fig.min_border_bottom`.

**Comment by mattpap** [comment]
@mrocklin, fixing this will be next big chunk of layout work after I'm done with PR #7008.

**Comment by mrocklin** [comment]
Thanks @mattpap .  Also, no rush from me.  My short term needs are met with the workaround.
