### ISSUE TITLE
Streaming numpy datetime64 data does not work

### ISSUE THREAD

**Issue by 0zeroth** [bokeh/bokeh#6681]
Related to #6667 - but in addition to that issue the datetime data also needs special treatment. 

My comment on #6667 contains a complete example and also the workaround, but I thought a ticket explicitly mentioning the datetime64 problem would be useful.

**Comment by bryevdv** [comment]
This seems like it should be a quick fix (unless I am mistaken) so I will take a stab at it for the coming release.

**Comment by bryevdv** [comment]
@0zeroth I did start looking at this. It turns our there are some complications, but I will push a PR soon so they can be discussed in a more focused way.
