### ISSUE TITLE
CDSVIEW_SOURCE_DOESNT_MATCH error when running bokeh App in Jupyter notebook. 

### ISSUE THREAD

**Issue by zjffdu** [bokeh/bokeh#6682]
#### Description of expected behavior and the observed behavior
Bokeh App doesn't work in Jupyter notebook. I got CDSVIEW_SOURCE_DOESNT_MATCH error when running bokeh App in Jupyter notebook. 

#### Complete, minimal, self-contained example code that reproduces the issue
The example here doens't work for bokeh master, but works for bokeh 0.12.6
https://github.com/ecerami/pydata-essentials/blob/master/bokeh/bokeh_notebook_embed.ipynb

#### Stack traceback and/or browser JavaScript console output
This is the error I see in jupyter.
```
E-1010 (CDSVIEW_SOURCE_DOESNT_MATCH): CDSView used by Glyph renderer must have a source that matches the Glyph renderer's data source: GlyphRenderer(id='013c6919-274a-4b6f-8d71-eec0f1ad73ec', ...)
E-1010 (CDSVIEW_SOURCE_DOESNT_MATCH): CDSView used by Glyph renderer must have a source that matches the Glyph renderer's data source: GlyphRenderer(id='016e0581-6159-4ec1-9714-5109229c776c', ...)
E-1010 (CDSVIEW_SOURCE_DOESNT_MATCH): CDSView used by Glyph renderer must have a source that matches the Glyph renderer's data source: GlyphRenderer(id='064ec7d4-6842-4530-b61d-c8f5c22ac6e7', ...)


```
#### Screenshots or screencasts of the bug in action
<img width="1127" alt="screen shot 2017-07-27 at 8 41 37 pm" src="https://user-images.githubusercontent.com/164491/28670599-0a216192-730c-11e7-9b2a-9dcd89947608.png">

**Comment by bryevdv** [comment]
@zjffdu looking at your code, I see you are using `Historgram` from `bkcharts` which is certainly the source of the problem. So any issue should be filed in the new separate `bkcharts` repo:

https://github.com/bokeh/bkcharts

however, I should also advise you that no one is currently maintaining `bkcharts` so I can't speculate on when (or if) any fix might occur. As alternatives, I would suggest:

* create your histogram using `bokeh.plotting` APIs, e.g. http://bokeh.pydata.org/en/latest/docs/gallery/histogram.html 

* try out HoloViews, which is the officially recommended very High Level API for Bokeh http://holoviews.org/ which has an active team maintaining it

* don't upgrade Bokeh to `0.12.7`

**Comment by zjffdu** [comment]
@bryevdv  I may find the root cause. It is due to bokeh js failed to load. 

I try to use both CDN and INLINE, but both fails. Here's the error I see in chrome console. Any clues ?

CDN:
<img width="898" alt="screen shot 2017-07-29 at 7 18 50 pm" src="https://user-images.githubusercontent.com/164491/28744406-d9edd734-7492-11e7-962a-a2d2e742f3f2.png">

INLINE:
![image](https://user-images.githubusercontent.com/164491/28744408-dfe8e304-7492-11e7-9b63-e0c101a2b009.png)

**Comment by bryevdv** [comment]
CDN is not going to work off master, CDN resources are only published for full releases, dev builds, and release candidates. The second issue was a build bug that affected notebooks, and the fix was pushed to master yesterday. 


However, as I said earlier, *this is not the appropriate forum for bkcharts issues* Accordingly, I am locking comments. Please feel free to file an issue in the correct place https://github.com/bokeh/bkcharts
