### ISSUE TITLE
accent are sorted last in sorted Tablecolumn

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#6683]
```
from bokeh.layouts import row
from bokeh.models import ColumnDataSource, WidgetBox, HoverTool
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn
word = ['met', 'méteo','no','mute','mill','mole']
sopeople = ColumnDataSource(data=dict( word=word))
columns1 = [
TableColumn(field="word", title="word", default_sort="descending"),
]
dttbl1 = DataTable(source=sopeople, columns=columns1, width=320, height=630)
wdgtdt1 = WidgetBox(dttbl1)
l5 = row(wdgtdt1)
show(l5)
```
This table show you mixed of inserted words not sorted. One of the word as un accent.

![screen shot 2017-07-27 at 8 03 50 am](https://user-images.githubusercontent.com/23002446/28677385-39e836f4-72a2-11e7-95c9-6d60d1df8358.png)
This sorted Table display the sorted word and the word "méteo" should be contiguous of the word "met" and before "mill".

![screen shot 2017-07-27 at 8 04 07 am](https://user-images.githubusercontent.com/23002446/28677571-b336438e-72a2-11e7-96b6-917662d2fec8.png)

**Comment by bryevdv** [comment]
Useful refs: 

http://www.jstips.co/en/javascript/sorting-strings-with-accented-characters/
https://github.com/mleibman/SlickGrid/blob/gh-pages/examples/example-multi-column-sort.html
