### ISSUE TITLE
Bug in "Running a Bokeh Server" page

### ISSUE THREAD

**Issue by ChrisDSaldivar** [bokeh/bokeh#6687]
The following code is missing a closing parenthesis in the [user guide](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html).

```
from os.path import dirname, join
from helpers import load_data

load_data(join(dirname(__file__), 'data', 'things.csv') # <-- Missing Parenthesis
```

Should be:
```
from os.path import dirname, join
from helpers import load_data

load_data(join(dirname(__file__), 'data', 'things.csv'))
```

**Comment by bryevdv** [comment]
Thanks for the report @ChrisDSaldivar would you be able to submit a small PR to fix things? That would actually be a huge help. The file to edit is here:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/server.rst
