### ISSUE TITLE
Patches and MultiLine Array data does not work with the server 

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#6690]
Bokeh 0.12.6

Consider the code:

```python
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

import numpy as np


ds = ColumnDataSource(data=dict(xs=np.array([[0, 0.5, 1, 0.5]]),
                                ys=np.array([[0.5, 0, 0.5, 1]]),
                                colors=['#0000ff']))

f = figure(width=500, height=500)
f.patches(xs='xs', ys='ys', source=ds)

curdoc().add_root(f)
```

There's no figure, and you can see the following in the JS console:
```
[bokeh] data source has columns of inconsistent lengths
```
And if you check the data attribute of the `ColumnDataSource` on the JS side, you'll see:
```
Object {ys: Float64Array(4), xs: Float64Array(4), colors: Array(1)}
```

**Comment by bryevdv** [comment]
Well, JavaScript fundamentally has no multidimensional typed arrays, so things will always be flattened on the JS side. But we do send shape dimensions along with numpy arrays so that the flattened arrays can be made sense of. Not sure what's gone amiss in this particular case.

**Comment by bryevdv** [comment]
ping @philippjfr thoughts?

**Comment by p-himik** [comment]
@bryevdv "Always" - you mean when we need to keep type information? Because I keep seeing arrays of arrays in JS when I use `np.array` of `int64`.

**Comment by bryevdv** [comment]
OK, always *when it is possible* JS does not offer an 64 bit integer typed array, so converting in that case is not possible. We are confined by the inherent limitations of javascript in many instances.

**Comment by bryevdv** [comment]
The shape info is making it properly to JS, I think this is just a dumb problem with `get_length`, it should consult `_shapes[0]` for the length when it is present

<img width="449" alt="screen shot 2017-10-19 at 13 05 02" src="https://user-images.githubusercontent.com/1078448/31786452-27c63aac-b4ce-11e7-9e3d-8c01c7242d51.png">

**Comment by bryevdv** [comment]
OK there is indeed a simple fix for the proximate problem but then the code still does not work. I think `Patches` (and probably `MultiLine` too) are currently incompatible with server apps. I think the somewhat complicated `_set_data` code that `Image` and `ImageRGBA` have that deals with shapes, etc, will need to be factored out for use by all four of these glyphs that have non-scalar column values. I will re-title the issue appropriately

**Comment by philippjfr** [comment]
I've used ``Patches`` and ``MultiLine`` on the server recently, so I'm fairly sure it works as long as you pass lists of arrays rather than an 2D array.

**Comment by bryevdv** [comment]
@p-himik Actually I think this is a usage issue. This works:
```
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

import numpy as np


ds = ColumnDataSource(data=dict(xs=[np.array([0, 0.5, 1, 0.5])],
                                ys=[np.array([0.5, 0, 0.5, 1])],
                                colors=['#0000ff']))

f = figure(width=500, height=500)
f.patches(xs='xs', ys='ys', source=ds)

curdoc().add_root(f)
```
<img width="482" alt="screen shot 2017-10-23 at 15 33 22" src="https://user-images.githubusercontent.com/1078448/31911825-8b4c8e82-b807-11e7-9972-187de4c5748e.png">


This difference is that instead of passing a 2d array, I have passed a *list of 1-d arrays* . Since in general a columns of patches can all have any different number of point, we have to support "ragged" arrays as the interface, i.e. a list of arrays, as I have done above.
