### ISSUE TITLE
WheelZoom on tablet: it doesn't change direction.

### ISSUE THREAD

**Issue by Nemecsek** [bokeh/bokeh#6694]
Following the tutorial at http://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html#userguide-quickstart I found something strange on the very first example "Simple line example".

I'm using an Android 6.0 tablet+Chrome 59.0 and zoom in/out using two fingers. 

Zooms are both very fast: it is easy to lose track of the glyph (it would be nice to reduce the zoom factor: now a minimal finger movement means a dramatic zoom change).

The real issue comes out of this: when zooming in too fast, the instinctive action is to zoom out without releasing the two fingers, as in any other app. But even if the distance of the fingers is now reducing, the glyph continues to zoom in. It stops only when fingers are released and a new zoom out is restarted.

The same problem happens when zooming out.

Another issue is that the central point of zoom is not exactly between the fingers, as it should be. When zooming in a glyph, it follows one of the fingers instead of remaining centered.

**Comment by bryevdv** [comment]
Unfortunately, I don't have access to to an android tablet, or funds to acquire one, so it's not actually likely that this can be fixed any time soon. I'd love to help anyone who does, get started working on fixing this. If someone see this and wants to work on it, please comment, and we will re-open. But for now I am forced to close this as `wontfix`
