### ISSUE TITLE
Pandas version requirement on Raspberry Pi 2/3

### ISSUE THREAD

**Issue by scottlittle** [bokeh/bokeh#6695]
Make pandas version 0.15 a minimum requirement for Bokeh.  Most desktop users are not using old versions of pandas, so they would not notice this, but the Raspberry Pi 3 (Raspbian Jessie) installs version 0.14 by default.  This version of pandas does not have an implementation of timedelta required by Bokeh.  This issue is fixed with an upgrade of the pandas package, but bokeh should have a minimum requirement of 0.15 nonetheless.  This issue is described in more detail on stackoverflow: https://stackoverflow.com/questions/45012958/attributeerror-module-object-has-no-attribute-timedelta/45392091#45392091.

**Comment by bryevdv** [comment]
The only part of bokeh that had a hard dependency on Pandas was `bokeh.charts`, which is now  moved to a separate repo and project. When Bokeh 1.0 is released and the current compat/deprecation shim is removed, then `bkcharts` can depend on Pandas (>0.15, or whatever) If you'd like to file an issue there, the issue tracker is located here: https://github.com/bokeh/bkcharts But please not `bkchart` does not currently have a maintainer. 

As for the current core Bokeh library, we make efforts to be able to handle pandas *if and when users pass pandas data structures.* But pandas data structures are in no way *required* to use bokeh, so we will not add pandas as a hard dependency, in order not to burden users with installing pandas if they don't need or want it.
