### ISSUE TITLE
BokehJs fails to load in Zeppelin

### ISSUE THREAD

**Issue by zjffdu** [bokeh/bokeh#6696]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh_master (commit hash 376baaad276f787a3bacd66e13490ba7f3121000)
python: 3.4.5
notebook: apache zeppelin
OS: Mac OS
Browser: Chrome 59.0.3071.115

#### Complete, minimal, self-contained example code that reproduces the issue

The following code fails to run in apache zeppelin

```
%python

from bokeh.layouts import row, widgetbox
from bokeh.models import Select
from bokeh.charts import Histogram
from bokeh.io import show, output_notebook
from bokeh.application.handlers import FunctionHandler
from bokeh.application import Application
import pandas as pd
import bokeh
import sys

print(bokeh.__version__)
print(bokeh.__file__)
print(sys.version_info)

from bokeh.resources import INLINE
output_notebook(resources=INLINE, notebook_type='zeppelin')


```
#### Stack traceback and/or browser JavaScript console output

<img width="1402" alt="screen shot 2017-07-30 at 9 07 18 am" src="https://user-images.githubusercontent.com/164491/28749810-87344144-7506-11e7-8ace-14d0f3ef0400.png">

Here's what I see after click the error link:

<img width="1057" alt="screen shot 2017-07-30 at 9 10 21 am" src="https://user-images.githubusercontent.com/164491/28749824-0a5cf958-7507-11e7-8429-c27bf98dd486.png">

**Comment by zjffdu** [comment]
I suspect it is due to changes in `autoload_js.js` or `autoload_nb_js.js`, but I am not an expert of javascript. The errors here doesn't give me a clean clue. @bryevdv @mattpap Could you give me some help on how to diagnose this kind of issue ? Thanks

**Comment by zjffdu** [comment]
It looks like it is due to INLINE bokeh js loading. Because I also fails to load bokehjs in INLINE mode in bokeh 0.12.6. But CDN works for 0.12.7

**Comment by mattpap** [comment]
This is an effect of a know bug in jquery (or actually a feature, because it's by design). This only affects minified resources. To work around this, one shouldn't depend on jupyter notebook's ability to publish mixed HTML & JS, because this goes through `$.html()` and gets butchered, but publish them separately. This is done in `output_notebook(notebook_type="jupyter")`, but for whatever reason, `output_type="zeppelin"` behaves differently. This needs to be changed to allow minified resources to work properly.

**Comment by zjffdu** [comment]
Thanks @mattpap I am not sure the mechanism of jupyter.  I am trying to understand the underlying mechanism, but I could not find the bokehjs in the html of jupyter note. Not sure how jupyter load the js.  Do you know that? Thanks

**Comment by bryevdv** [comment]
@mattpap the Zeppelin notebook display literally just does this:
```
def _publish_zeppelin_data(html, js):
    print('%html ' + html)
    print('%html ' + '<script type="text/javascript">' + js + "</script>")
```
Do you know what might need to change (some kind of escaping?) I don't know.

**Comment by mattpap** [comment]
>  the Zeppelin notebook display literally just does this:

And this is exactly why it fails. '`<script ...>' + js + '</script>'` goes through `$.html()` and gets butchered by jquery.  I don't know why there is a special case there. If this is supposed to work, HTML and JS have to be embedded separately, by using `publish_display_data()` or some other API. Maybe there is `%javascript` magic, though I would prefer using a proper API instead.

**Comment by bryevdv** [comment]
Is zeppelin based on jupyter at all? Serious question I don't know. I'm not sure those things exist in zeppelin notebooks.

**Comment by zjffdu** [comment]
Zeppelin doesn't depends on jupyter and it doesn't use jupyter api. I don't understand what `embedded separately` means. Could you explain more to me ? Maybe I can try to do the similar for zeppelin like jupyter.

**Comment by zjffdu** [comment]
ping @mattpap

**Comment by bryevdv** [comment]
I believe all of this has been resolved for some time
