### ISSUE TITLE
Bands wrongly coloured

### ISSUE THREAD

**Issue by Nemecsek** [bokeh/bokeh#6698]
Following the examples in the User Guide, bands are wrongly coloured when panned up and down. 
http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#bands
Try to pan (slowly) up and down to see the effect.

There are probably 2 errors involved: 
1) the bottom line, when incomplete, has the same color of the line above. When incomplete, the top line looks always light blue; 
2) the line count to determine the color is based on the lower major tick on y: when you pan up/down colors are no more consistent and change during movement. It would be nice to start the color line count on the real "0" instead of on the lower major tick on y so on pan the bands would keep their own color. Of course the same problem applies when zooming in/out, but there is nothing that can be done about it. 
![bokeh_plot](https://user-images.githubusercontent.com/25978536/28767998-4a7e963e-75d6-11e7-8d28-4339478a3f2b.png)

**Comment by bryevdv** [comment]
HI @Nemecsek thanks for the issue. Sorry I was not able to look at it until now. I have made a PR that fixes the first issue (end bands not correct). I am going to punt on the mod suggestion as it is somewhat more involved (and thus more risky). But the PR makes things better for plots that do not pan/zoom, or those that only do so in a cross-dimension.
