### ISSUE TITLE
Bokeh / JupyterLab integration 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6700]
Updated high level design principles:

* [ ] mime bundle for loading BokehJS

    The `output_notebook()` function generates a mime bundle looks like 

    ```
    {'application/javascript': js, 
      'application/vnd.bokeh.bootstrap_bokehjs': ''}
    ```
     In the classic notebook, it ignores the bokeh mimetype and runs the JS. In JLab, the Bokeh mimetype has a higher precedence, so it ignores the JS mimetype.

    * For the classic notebook  the JS will load the Bokeh mini-extension to register for the `show` mime type. Additionally BokehJS will be loaded from CDN or for `inline` resources, from the JS in the bundle itself. 

   * For JLab the Bokeh mini-extension will be previously installed via usual JLab mechanisms. The extension will load BokehJS from CDN or for `inline` resources, from the locally installed Bokeh package. (via a REST endpoint??)

* [ ] mime bundle for showing standalone docs and applications

    The `show(...)`  function generates a mime bundle that looks like

    ```
    'application/vnd.bokeh.show`: JSON
    ```

    Where JSON is the serialized Bokeh Document and any additional metadata (versions, comm ids etc)

**Comment by jasongrout** [comment]
> does JupyterLab expose anything that would reliably permit detection of when code is running in JupyterLab?

When python code is displaying in lab, or when javascript is running lab? If the former, it's impossible for python code to tell if it's displaying to lab - it may be displaying to many different frontends at the same time, including lab and other frontends. If the latter - well, the javascript will be a lab plugin, so yes, it knows it is running in lab.

**Comment by bryevdv** [comment]
@jasongrout what I take from  that is that is will be fundametally impossible to have a single (Python) function `show(plot)` what works in both the classic notebook and in JupyterLab, do you disagree? That seems like a pretty terrible situation.

**Comment by jasongrout** [comment]
> @jasongrout what I take from that is that it will be fundametally impossible to have a single (Python) function show(plot) what works in both the classic notebook and in JupyterLab, do you disagree? That seems like a pretty terrible situation.

No, not at all. `display(plot)` should construct a display_data message that is agnostic to the frontend. The frontend (e.g., a plugin in the frontend) should take that message and do something that makes sense to display it.

**Comment by bryevdv** [comment]
> display_data message

Where is this documented for the classic notebook and for jlab? How can a python function `output_notebook` install the JS handler for this function in the classic notebook? Right now in the notebook, users can do:
```

# imports

output_notebook()

plot = figure(...)

show(plot)
```
and that just works, with no additional steps, no extension building or work required outside the classic notebook. That can't change, because there's going on five years of accumulated info and demonstration of that usage.

**Comment by blink1073** [comment]
The ability to display custom mime types was added to Notebook 4.3+ here: https://github.com/jupyter/notebook/pull/1866.    Here is an example implementation of a notebook renderer: https://github.com/jupyterlab/jupyterlab_json/blob/master/nbextension/src/renderer.js.   The `output_notebook()` function could become a deprecated no-op, and `show()` would use the custom mime type handling.

**Comment by jasongrout** [comment]
This would require each frontend have a bokeh extension installed in order to render the mimetype.

**Comment by jasongrout** [comment]
(For the classic notebook, though, you might be able to forego an extension and just register your mimetype with the notebook using javascript in your output_notebook() function)

**Comment by bryevdv** [comment]
> (For the classic notebook, though, you might be able to forego an extension and just register your mimetype with the notebook using javascript in your output_notebook() function)

if `ouput_notebook` unconditionally publishes JS will it always just get silently ignored in JLab? If so then yes that might work

**Comment by jasongrout** [comment]
Right now, Lab ignores any script tags in the text/html mimetype, but the notebook executes it. So that's one way to do that.

**Comment by bryevdv** [comment]
I'll be honest and say this prospect petrifies me. The current implementation for the classic notebook, which was created using the tools that existed at the time, before any of this mime API exsisted, has eaten up person-months of time with bugs and instabilities.

**Comment by jasongrout** [comment]
> has eaten up person-months of time with bugs and instabilities.

That's *precisely* why we wanted to create a much more robust extension system, à la JupyterLab. The original notebook was not meant to be extended, and trying to extend it meaningfully was hard and error-prone. So to quote the movie Moana, on behalf of the JLab team: "You're welcome!" :)

**Comment by bryevdv** [comment]
> That's precisely why we wanted to create a much more robust extension system, à la JupyterLab. The original notebook was not meant to be extended, and trying to extend it meaningfully was hard and error-prone. So to quote the movie Moana, on behalf of the JLab team: "You're welcome!" :)

@jasongrout I get it, and I hope all the promises turn out, I'm just saying based on my current experience, which is the only experience that I have to draw on: I'll believe it's easy and care free when I see it... I look forward to being pleasantly surprised.

**Comment by jasongrout** [comment]
> I'll believe it's easy and care free when I see it

The JLab team (especially @blink1073 and @sccolbert who really dove deep into the extension work) would probably agree that it hasn't been easy or carefree to develop it ("person-months of [dealing with] bugs and instabilities [in browsers, packaging systems, etc.]" would just *start* describing the work they've done), but we hope the end product will be a great experience.

That said, we're certainly glad when people willing to live on the bleeding edge test things and write extensions to help us iron out issues. So we welcome your involvement!

**Comment by jasongrout** [comment]
But back to the issue - do you see the way forward now?

**Comment by bryevdv** [comment]
> But back to the issue - do you see the way forward now?

Assuming we try the `output_notebook` publishes JS for the classic notebook to install the handler, that gets ignored in JLab" route, is there a way in classic notebook to know when the handler is installed? We try to block `output_notebook` until it is certain things that will be subsequently needed are actually in place (or show a giant error on timeout). Right now, that trigger of success `window.Bokeh` being present. What can we wait on/check for if the JS code installs a handler? 

The problem situation trying to avoid: user executes "run all cells" and a cell with show executes before the JS published by `output_notebook` is actually finished installing the handler.

**Comment by bryevdv** [comment]
Actually, how will things work with BokehJS and JLab at all? What happens when a new version is released? Will BokehJS be embedded in static notebooks? We had a huge outcry about large notebooks and a huge call to use CDN resources by default. How is that supposed to work with JLab?

Do we need instead to consider a tiny shim npm module that loads the appropriate BokehJS version from CDN?

**Comment by blink1073** [comment]
You can check for the existence of the mimetype in [OutputArea.append_map](https://github.com/gnestor/notebook/blob/4cf93c8c5769b035df598796b7d43153ef3c5b89/notebook/static/notebook/js/outputarea.js#L988).

**Comment by sccolbert** [comment]
A JLab extension can do whatever it wants, including execute script tags. Installed extensions are implicitly trusted. So the Bokeh extension could loads it's JS once on app startup, and then execute whatever extra stuff is contained in the mime bundle (if needed) when it's rendering the output.

**Comment by bryevdv** [comment]
> A JLab extension can do whatever it wants, including execute script tags. Installed extensions are implicitly trusted. So the Bokeh extension could loads it's JS once on app startup, and then execute whatever extra stuff is contained in the mime bundle (if needed) when it's rendering the output.

ping @mattpap @philippjfr @jlstevens I think this is potentially important information. Based on this I think we should consider making a small stable (unchanging, versionless) extension that then loads the property BokehJS version from CDN from the local copy in the package. This would allow us to punt on the NPM packages for BokehJS itself for now, and proceed immediately. 

I think this would mean lazy loading, i.e. the call to `display_data` includes the Bokeh version and that's when the load happens if necessary. But maybe the extension can inspect an installed Bokeh for its version on startup.

**Comment by jlstevens** [comment]
@bryevdv That does sounds like a very promising avenue to experiment with first.

**Comment by bryevdv** [comment]
@jasongrout @sccolbert are there any hooks when statically rendering? A meta-extension that loads BokehJS from CDN or the local package would *by far* the most manageable scenario for us, but I am not sure how embedded/inline BokehJS resources (e.g. in order to have static notebooks that work behind an airgap) for a statically rendered notebook could work in that case. The actual BokehJS source code would need to be include in the statically rendered output.

**Comment by sccolbert** [comment]
What do you mean by "hooks"?

Assuming you mean something like "load your stuff", then each extension defines an "activate" function which is called on app startup. That function returns a `Promise` which it resolves when activation is "done". The app waits until all extensions are "done" loading before the user can interact with it. You could load your static JS assets there by putting a `<script>` tag on the page, and resolving the promise when the script is done loading.

**Comment by sccolbert** [comment]
If you need to ship the source as part of the mime bundle, you can do something similar. In your mime renderer, check to see if you already loaded the source for a particular version, and if not, slap the script tag on the page for that version at that time.

**Comment by bryevdv** [comment]
> If you need to ship the source as part of the mime bundle

That might work

**Comment by sccolbert** [comment]
But if you're packaging up a platform with a known version of Bokeh, that extension can just be installed upfront, so the bokeh assets are loaded any time the app is run. Then you don't need to ship the sources with each mime bundle.

**Comment by sccolbert** [comment]
Or taken a step further, the Bokeh extension could bundle a number of version, and the mime renderer can request the Bokeh API object for a particular version when it needs to render. The extension could load those versions on-demand.

**Comment by bryevdv** [comment]
> and the mime renderer can request the Bokeh API object for a particular version when it needs to render.

I am unclear what all the renderer can do / has access to. The mime renderer is JavaScript, correct? How does it request loading BokehJS from local disk (absolutely needed for developing Bokeh, among other things)? It seems to me that for inline resources the python side of things would have to send the BokehJS as part of the display message, as originally suggested. (Especially in the static render case)

**Comment by sccolbert** [comment]
The mime renderer has access to whatever you give it access to as part of your extension. When you create your extension package (Javascript), it can load the JS resources in a number of ways:

- bundle multiple versions of the JS source in the package itself
- load the JS source from CDN using a script tag
- load the JS source from a url pointing to somewhere in the server root
- load the JS source from disk by making REST request to the appropriate endpoint

I'm not sure where "static rendering" enters into the JLab equation.

**Comment by bryevdv** [comment]
> I'm not sure where "static rendering" enters into the JLab equation.

Maybe it doesn't, I am assuming that JLab will have a similar capability to save pure HTML/JS files  ala statically rendered notebooks, e.g. like http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/quickstart/quickstart.ipynb that can still be viewed without a running kernel. Is that not the case? 

If that is the case then for inline resources (what you'd want behind an air gap) then that HTML output needs to have BokehJS *embedded inside the HTML* for things to work.

**Comment by bryevdv** [comment]
Where can we find an example or docs for how to construct and send a display_data message?

**Comment by jasongrout** [comment]
You can implicitly use it like we do in the jupyterlab-fasta project - see the example in the readme: https://github.com/jupyterlab/jupyterlab-fasta

To explicitly send such a message, here's how we do it in ipywidgets: https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget.py#L671

**Comment by bryevdv** [comment]
Actually for loading BokehJS is there any reason we couldn't just use another mime-type? Then `output_notebook` would either load Bokeh BokehJS from CDN or load it from the `display_data` message. I am assuming a renderer could install `window.Bokeh` to be used later by other renderers?

**Comment by blink1073** [comment]
The extension is a singleton, it can keep a reference to the shared state.  An example is the `WidgetManager` used by [ipywidgets](https://github.com/jupyter-widgets/ipywidgets/blob/1ab39c03304d3fafe6654d1ac8fdbc6c2baa4c35/packages/jupyterlab-manager/src/plugin.ts#L94).

**Comment by sccolbert** [comment]
You already need to install an extension in order to make the mime renderer available, so why not just load the `window.Bokeh` in that extension, rather that shipping all that JS over the wire in each mime bundle?

**Comment by bryevdv** [comment]
> You already need to install an extension in order to make the mime renderer available, so why not just load the window.Bokeh in that extension, rather that shipping all that JS over the wire in each mime bundle?

That's what I was suggesting, one mime extension to load `window.bokeh`, either from CDN or from local source (used once, by `output_notebook`) and another mime extension to send just Bokeh doc JSON that uses the previously loaded BokehJS

**Comment by sccolbert** [comment]
Those can both be the same extension.

**Comment by sccolbert** [comment]
To be clear a "mime extension" is just a simplified version of a full-blown jlab extension. You can create a single JLab extension which enables everything we're talking about.

**Comment by bryevdv** [comment]
What is he best method to determine if an output cell has been deleted in both notebook 4.3+ and JuplyterLab. We currently set up a MutationObservers when we show bokeh apps inline, so that the appropriate tear-down and resource release can happen.

**Comment by bryevdv** [comment]
> Right now, Lab ignores any script tags in the text/html mimetype, but the notebook executes it. So that's one way to do that.

@jasongrout JLab ignores, but not silently:

<img width="336" alt="screen shot 2017-08-08 at 12 42 48" src="https://user-images.githubusercontent.com/1078448/29086598-c96607e4-7c38-11e7-879c-82990b200e9b.png">

Is there a programmatic way to silence this warning for a particular output cell? If not, I am back to not knowing how to proceed in a way that

* works for both classic notebook 4.3+ and JupyterLab
* doesn't break 4+ years of guidance all over the internet (i.e. keeps `output_notebook`)
* doesn't issue warnings for normal correct usage

**Comment by jasongrout** [comment]
> Is there a programmatic way to silence this "JavaScript output is disabled in JupyterLab" warning for a particular output cell?

Great question - I didn't realize there was a warning. @blink1073, @sccolbert?

**Comment by jasongrout** [comment]
Perhaps we can log a warning to the console, but not in the output? I realize it's a balance.

**Comment by blink1073** [comment]
In JupyterLab, the bokeh manager can connect to each created bokeh widget's `disposed` [signal](https://github.com/phosphorjs/phosphor/blob/23b9d075ebc5b73ab148b6ebfc20af97f85714c4/packages/widgets/src/widget.ts#L95).

In the classic notebook, there is a `clear_output.CodeCell` [event](https://github.com/jupyter/notebook/blob/da2d54f73e5aa2f8f5285b2e477b15407dc2e9c3/notebook/static/notebook/js/codecell.js#L524) and a `delete.Cell` [event](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/notebook.js#L1163) that you can spy on. 

We had a request for the warning because otherwise from a user standpoint it wasn't clear why the anticipated JavaScript output was being suppressed.

**Comment by bryevdv** [comment]
> We had a request for the warning because otherwise from a user standpoint it wasn't clear why the anticipated JavaScript output was being suppressed.

@blink1073 That makes perfect sense in general, but it would be useful to be able to override and suppress it intentionally for specific purposes. Is that feasible?

**Comment by sccolbert** [comment]
That message is generated by the mime renderer (IIRC). If you are creating your own mime renderer for bokeh, it shouldn't be a problem.

**Comment by sccolbert** [comment]
> That message is generated by the mime renderer (IIRC). If you are creating your own mime renderer for bokeh, it shouldn't be a problem.

This is wrong. Looking for where that message is generated. The default mime renderers log to the console.

**Comment by sccolbert** [comment]
Ok here's what's generating that message for the JS output:
https://github.com/jupyterlab/jupyterlab/blob/c956182b6027566146d49d0efa2b91ebb260f4e3/packages/rendermime/src/widgets.ts#L402

If you write your own mime renderer, it wouldn't use this class, so you wouldnt get the message.

**Comment by blink1073** [comment]
If Bokeh use the `JavaScript` display function from `ipython`, it will generate this output.

**Comment by blink1073** [comment]
Yep, [here](https://github.com/bokeh/bokeh/blob/170b23fa85d5bdea9ebc8914361f570ed4fa2e11/bokeh/util/notebook.py#L35)

**Comment by blink1073** [comment]
Those lines could be modified to `publish_display_data({'text/html': '<script> + js + </script>' + html})`, which would only show the console log in JupyterLab.

**Comment by bryevdv** [comment]
We don't use `JavaScript`, we do this:
```
    if notebook_type=='jupyter':
        publish_display_data({'text/html': html})
        publish_display_data({'application/javascript': js})
```
Whichseems to be equivalent as fas as getting the warning is concerned. In any case, since there is not any way to know if we are in the notebook, or in jupyterlab, we evidently must find a single solution that works for both. So I would like to unconditionally publish JS code that *installs the mime extension* when `output_notebook` is called:

* In the classic notebook, This JS registers the extension, and all further work goes through `display` with a mimetpye
* in JLab, this JS is just ignored! the extension is installed via normal JLab means and all further work goes though `display` with a mime type

That would satisfy the requirements as I see them:

* works for both classic notebook 4.3+ and JupyterLab
* doesn't break 4+ years of guidance all over the internet (i.e. keeps output_notebook)
* doesn't issue warnings for normal correct usage

But for this to be viable, there would need to be way to selectively suppress the warning in JLab, i.e. it needs to be ignored *silently*. Is it possible to add this capability? I am asking for it to be added. 

Otherwise, what are the alternative?

**Comment by jasongrout** [comment]
I think @sccolbert is right - there should *also* be a mimetype that is bokeh-specific. In jlab, the bokeh renderer has precedence, so the html and javascript mimetypes are ignored, and you don't get a message.

**Comment by mattpap** [comment]
> `publish_display_data({'text/html': '<script> + js + </script>' + html})`

Does this go through jquery at any point?

**Comment by blink1073** [comment]
In the classic notebook, yes.  In JupyterLab there is no global jquery.

**Comment by bryevdv** [comment]
I agree there should be a mime type! But the mime extension needs to be *installed* in classic notebook! I am proposing to have `output_notebook` do that, and since there is no way to switch on classic/jlab, to have it do that unconditionally. 

>  Does this go through jquery at any point?
I don't know. BokehJS itself does not rely on JQ at all. This is what `publish_display_data` does: 
```
import IPython.core.displaypub as displaypub
    try:
        displaypub.publish_display_data(source, data)
    except TypeError:
        displaypub.publish_display_data(data)
```

**Comment by blink1073** [comment]
We could provide a default mime renderer in JupyterLab that is a higher priority than `application/javascript` that is a no-op for this purpose.  Then the call would be:

`publish_display_data({'application/javascript': js, '<suppress_in_jlab>', '' })`

**Comment by jasongrout** [comment]
> I agree there should be a mime type! But the mime extension needs to be installed in classic notebook! I am proposing to have output_notebook do that, and since there is no way to switch on classic/jlab, to have it do that unconditionally.

Since the bokeh extension will already be installed in jlab, you can still include a bokeh-specific mimetype (maybe `application.vnd.bokeh-ignore` :) that essentially is 

Yeah, @blink1073 beat me to it. What he said.

**Comment by sccolbert** [comment]
>  So I would like to unconditionally publish JS code that installs the mime extension when output_notebook is called:

That's not how the extension mechanism works. The user will install the bokeh extension into jupyter lab *as a separate step*. **You are not able to install extensions by shipping code from the kernel to the client**.

You can put multiple mime types in a single bundle, and jupyterlab will pick the "best" renderer based on what's available to service the various types contained in the bundle.

You *separately installed* bokeh extension should do this:

1. Register a mime renderer for bokeh-specific mimetypes (like `application/vnd.bokeh.js`)
2. Load the bokeh js from cdn (or wherever) the first time a bokeh renderer is created
3. Render the data for the plot.

**Comment by bryevdv** [comment]
> That's not how the extension mechanism works. The user will install the bokeh extension into jupyter lab as a separate step. You are not able to install extensions by shipping code from the kernel to the client.

In the *classic notebook*? Because I outlined this plan to install a mime renderer this way way up above and there was no comment to this effect then

**Comment by sccolbert** [comment]
No sorry, in jlab. I misunderstood you.

**Comment by sccolbert** [comment]
I think the missing piece for you is that you can ship multiple mime types in the same bundle, and have your jlab renderer take precedence over the default `application/javascript` renderer.

**Comment by bryevdv** [comment]
OK, in that case then I think what @blink1073  suggested would be perfect solution. Just to be clear, that involves some small work on the Jupyter side, correct?

**Comment by jasongrout** [comment]
> We could provide a default mime renderer in JupyterLab that is a higher priority than application/javascript that is a no-op for this purpose.

I would really hesitate setting a precedent for a no-op mimetype that is specific to a frontend.

**Comment by jasongrout** [comment]
> OK, in that case then I think what @blink1073 suggested would be perfect solution. Just to be clear, that involves some small work on the Jupyter side, correct?

If you register that no-op mimetype in your bokeh extension, there's no need for any changes in jlab.

**Comment by sccolbert** [comment]
> If you register that no-op mimetype in your bokeh extension

Why is a no-op mimetype needed, if there's a mimetype/renderer with higher precedence?

**Comment by bryevdv** [comment]
> If you register that no-op mimetype in your bokeh extension, there's no need for any changes in jlab.

OK that was not evident from earlier discussion, or from the docs that I was looking at. Will have to give it a try.

**Comment by jasongrout** [comment]
> Why is a no-op mimetype needed, if there's a mimetype/renderer with higher precedence?

As I understand it, there are two types of messages he is talking about. One is an html+javascript message that should only be run in the classic notebook, that installs the extension in the classic notebook. The other is a rendering message that actually has a plot. The discussion above is about the first type of message.

**Comment by bryevdv** [comment]
> As I understand it, there are two types of messages he is talking about. One is an html+javascript message that should only be run in the classic notebook, that installs the extension in the classic notebook. The other is a rendering message that actually has a plot. The discussion above is about the first type of message.

Yes this is exactly correct.

**Comment by jasongrout** [comment]
So you register a jlab mimetype renderer for the first type, say with a mimetype of `application/vnd.bokeh.bootstrap_classic_notebook_extension`, and in jlab that is a no-op to render. You also register your more standard `application/vnd.bokeh.plot` mimetype, with whatever you do to render it.

**Comment by sccolbert** [comment]
> So you register a jlab mimetype renderer for the first type, say with a mimetype of application/vnd.bokeh.bootstrap_classic_notebook_extension, and in jlab that is a no-op to render.

If the bundle doesn't include any `application/javascript` at all, would a no-op renderer be needed? If there is no renderer for any mimetype, the output item will be empty by default.

**Comment by jasongrout** [comment]
Are you saying that if the first message type is just `{'text/html': '<script>...</script>'}`, then nothing is noted to the user (is there a message to the console?), and the js is not run in jlab, so it effectively is a no-op renderer?

**Comment by blink1073** [comment]
As @mattpap said, bokeh relies specifically on the `application/javascript` mimetype in the classic notebook.

**Comment by bryevdv** [comment]
> So you register a jlab mimetype renderer for the first type, say with a mimetype of application/vnd.bokeh.bootstrap_classic_notebook_extension, and in jlab that is a no-op to render. 

OK, that seems potentially possible. But I'd like to refer back to @mattpap comment:

> I ask, because embedding complex javascript in HTML and passing it through jquery ($.html() in particular) fails quite often. For example, using inline bokeh.min.js in the notebook is possible only with application/javascript MIME.

We didn't used to pubslish to `application/javascript` in the classic notebook, we had to switch to that because things just stopped working otherwise at some point. Are you saying if we do (in the classic notebook):
```
   publish_display_data({'application/vnd.bokeh.bootstrap_classic_notebook_extension': js })
```
that there is a way to make it behave otherwise identically to  `application/javascript` in the classic notebook?

**Comment by sccolbert** [comment]
I'm saying if bokeh only sends messages with bokeh-specific mimetypes, and there are no renderers for those types, then nothing will happend.

**Comment by blink1073** [comment]
They will need to run at least some JS in the classic notebook to register a mimetype handler.

**Comment by blink1073** [comment]
Wait, no, that can be done with a notebook extension.

**Comment by jasongrout** [comment]
> Wait, no, that can be done with a notebook extension.

They don't want to require the user to install a notebook extension in the classic notebook.



> Are you saying if we do (in the classic notebook):
> 
>    publish_display_data({'application/vnd.bokeh.bootstrap_classic_notebook_extension': js })
> that there is a way to make it behave otherwise identically to application/javascript in the classic notebook?

I'm saying your `output_notebook()` mimebundle looks like `{'application/javascript': js, 'application/vnd.bokeh.bootstrap_classic_notebook_extension': ''}`. In the classic notebook, it ignores the bokeh mimetype and runs the js. In jlab, the bokeh mimetype has a higher precedence, so it ignores the js mimetype.

**Comment by bryevdv** [comment]
@jasongrout has summarized things perfectly above. I will try to run some preliminary experiments to validate this design approach. 

Please also know I'm not trying to be snarky, or short with anyone. If I have seemed so (or been so) I apologize. I genuinely appreciate any and all help, because this perception is the source of my extreme frustration and stress right now:

<img width="531" alt="screen shot 2017-08-08 at 17 12 34" src="https://user-images.githubusercontent.com/1078448/29097071-8e5dae48-7c5d-11e7-902c-6ad9a18d711e.png">

**Comment by bryevdv** [comment]
>  In jlab, the bokeh mimetype has a higher precedence, so it ignores the js mimetype.

It still seems to print the warning

<img width="475" alt="screen shot 2017-08-10 at 14 50 51" src="https://user-images.githubusercontent.com/1078448/29189230-62bce31a-7ddb-11e7-827d-849e3af3ed64.png">

**Comment by jasongrout** [comment]
> @jasongrout is this just because the bokeh mimetype is not installed? i.e. will go away as soon as it is?

Yes.

**Comment by bryevdv** [comment]
OK great, I just wanted to make sure there was not some explicit step we would need to take

**Comment by bryevdv** [comment]
closed again #6818

**Comment by mrocklin** [comment]
For those of us who are interested in using Bokeh plots in JupyterLab is there a combination of conda dev builds that we can use to get things running?  For example is the following sufficient?

    conda install bokeh jupyterlab -c conda-forge -c bokeh/dev

**Comment by bryevdv** [comment]
@mrocklin No, you will need to install the jlab extension as well. It's not published to npmjs.org yet (later this week) so you'll have to install from source: https://github.com/bokeh/jupyterlab_bokeh

**Comment by rsinha25** [comment]
Hi Team, is there any update on this. I am trying to run bokeh app with JLab but with no success. Even installed the labextension mentioned above, but it still doesn't work!

**Comment by canavandl** [comment]
@rsinha25 Bokeh=0.12.9 should work w/ JupyterLab=0.27.0 and the jupyterlab_bokeh=0.1.0 (0.0.1?) extension. Can you share more about how it's not working?

**Comment by rsinha25** [comment]
My bad, was at Bokeh=0.12.7, upgrading and checking. Also jupyterlab_bokeh=0.0.1 right?

**Comment by canavandl** [comment]
> Also jupyterlab_bokeh=0.0.1 right?

I believe that is correct (there's only one released version)

**Comment by rsinha25** [comment]
@canavandl , it works like a charm. Kudos on the amazing work. (y)

**Comment by dclong** [comment]
I'm trying Bokeh with JupyterLab. I have the jupyterlab_bokeh extension installed using the following command.
```
sudo jupyter labextension install jupyterlab_bokeh
```
However when I run the code
```
from bokeh.plotting import figure, output_notebook, show
output_notebook()
```
I got the following error message.
```
Loading BokehJS ...
JavaScript output is disabled in JupyterLab
```
I'm using the latest version of JupyterLab and Bokeh. Is the jupyterlab_bokeh extension not ready for new versions of JupyterLab and Bokeh?

**Comment by blink1073** [comment]
Not quite yet: https://github.com/bokeh/jupyterlab_bokeh/pull/6

**Comment by canavandl** [comment]
@dclong We've merged/published a new jupyterlab_bokeh extension version (0.1.0). Please upgrade your extension and try again.

**Comment by dclong** [comment]
@blink1073 @canavandl 

Thank you. Will give the new release a try.

**Comment by monteirotorres** [comment]
Still does not work for me. 
    
    Loading BokehJS ...
    JavaScript output is disabled in JupyterLab


JupyterLab v0.28.11
Known labextensions:
   app dir: /opt/anaconda3/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.28.2  enabled  OK
jupyterlab_bokeh
        jupyterlab_bokeh v0.1.0  enabled  OK

**Comment by blink1073** [comment]
Hi @monteirotorres, which version of bokeh do you have `pip list | grep bokeh`?    This was added in the 0.12.8 release.

**Comment by bryevdv** [comment]
Additionally, please execute `import bokeh; bokeh.__version__` *in the notebook* to confirm that jupyter is using the version of bokeh you think it is.

**Comment by canavandl** [comment]
@monteirotorres I think you need jupyterlab_bokeh 0.2.0 for jupyterlab 0.28.x compatibility. Please trying uninstalling/reinstalling the labextension and let us know if it doesn't work.

**Comment by monteirotorres** [comment]
Thank you @blink1073  and Thank you @blink1073, @bryevdv  and @canavandl . Just upgrading the Bokeh from 0.12.5 to 0.12.10 was sufficient. 

@canavandl , I was not able to find a version higher than 0.1.0 for the jupyterlab_bokeh extension, but it worked nevertheless.

Thanks

**Comment by bryevdv** [comment]
@monteirotorres Not to be overly critical, but this is why it is important to always include complete version information with each and every report, from the start. Support for JLab did not exist before Bokeh version 0.12.8, so this could have been resolved immediately (without sending three people scrambling) if you had stated the version up front.

**Comment by monteirotorres** [comment]
Noted, I'll keep that in mind @bryevdv . thank you!

**Comment by nickdex** [comment]
Hi,

I am still getting output disabled message.

### Versions
bokeh - 0.12.16 (checked in lab as suggested by @bryevdv )

> Additionally, please execute import bokeh; bokeh.__version__ in the notebook to confirm that jupyter is using the version of bokeh you think it is.

jupyter lab - 0.32.1
jupyterlab_bokeh extension - 0.5.0 enabled ok

Am I missing something?

**Comment by bryevdv** [comment]
@nickdex AFAIK that's the message that jupyterlab displays when something tries to publish raw javascript in an output cell. If that's happening, that 100% means that jupyterlab is not using the bokeh extension, but I can't really speculate why that might be. It's working fine for me:

<img width="1593" alt="screen shot 2018-06-09 at 22 07 23" src="https://user-images.githubusercontent.com/1078448/41198453-88faa464-6c31-11e8-8079-48538b1c40ea.png">

**Comment by tiagopereira** [comment]
Just tried the [Basic Interactor Demo](https://github.com/bokeh/bokeh/blob/0.13.0/examples/howto/notebook_comms/Jupyter%20Interactors.ipynb) in JupyterLab and the interactive part doesn't work (plot does not update). Any idea why? The plot shows fine, and the notebook runs as expected in jupyter notebook.

I'm using:

```
bokeh 0.13.0
jupyterlab_bokeh 0.5.0
jupyterlab  0.32.1
jupyter_core  4.4.0
jupyter_client 5.2.3
```

**Comment by bryevdv** [comment]
@tiagopereira there was a regression. This fix is merged to master but not yet in a release https://github.com/bokeh/bokeh/pull/8123
