### ISSUE TITLE
Unit Testing Downstream

### ISSUE THREAD

**Issue by jbrockmendel** [bokeh/bokeh#6701]
The recent `bokeh.io._get_screenshot_as_png(layout)` has made unit testing apps using bokeh much easier.  Props all around.

Right now I'm just testing these by manually checking the output once, saving it, and checking that future screenshots match this canonical version byte-for-byte.  This appears to be failing in at least three ways:

1) OSX vs Ubuntu are producing slightly different images.  It looks like the fonts in graph titles are slightly different.
2) Py2/Py3 appear mismatched
3) [Something Changed Since Yesterday] mismatch.  Maybe apt-get update changed... something?

So the question is: is there a different supported way of doing unit testing downstream?

`bokeh.__version__` is 0.12.6 for all cases mentioned.

**Comment by bryevdv** [comment]
I'm not sure I have much to offer except "lock down all your dependency versions". Even then, I expect that the tools will exhibit differences across platforms that we simply have no control over. This kind of unit test downstream was not really in mind when this feature was developed. 

ping @canavandl for any thoughts

**Comment by jbrockmendel** [comment]
Got it, thanks.  Feel free to close this one.
