### ISSUE TITLE
Plot multiple lines using grouping

### ISSUE THREAD

**Issue by dclong** [bokeh/bokeh#6703]
Suppose I have data in a pandas DataFrame and there's a column defining grouping. What is the best way to plot lines by group using Bokeh?

**Comment by bryevdv** [comment]
As stated in the issue template, the GH issue tracker is reserved for bug reports and feature requests. I it is not an appropriate venue for general technical support questions. For that, use the project mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
