### ISSUE TITLE
``bokeh.plotting.figure`` doesn't add Figure to curdoc

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6706]
AFAICT ``bokeh.plotting.figure`` doesn't add Figure to curdoc. There are multiple examples with inline documentation that describes such a behavior, but I can't see from the implementation or via manual testing that this actually happens.

We should either change the documentation or actually implement this behavior.

bokeh 0.12.7dev13

**Comment by bryevdv** [comment]
It used to, it does not (and should not) any longer. Adding to `curcoc` is done by `show` when you call `show(p)`

**Comment by canavandl** [comment]
> It used to, it does not (and should not) any longer. Adding to curcoc is done by show when you call show(p)

Thanks for the clarification. I'll modify the appropriate examples that I'm seeing that mention the old behavior.
