### ISSUE TITLE
Plot zoom out stops working if a single range bound is reached

### ISSUE THREAD

**Issue by rabryan** [bokeh/bokeh#6708]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh - 0.12.6
python - 3.5.2
OS - ubuntu 
browser - firefox 54.0 (64-bit)

#### Description of expected behavior and the observed behavior
Using the scroll wheel zoom tool on a plot with x_range bounds explicitly set, you should always be able to zoom out until the start and end bounds are reached.  Currently, once a single bound is reached (say by panning to the right until the 'end' bound is hit), zoom out is disabled (i.e. it behaves as if _both_ bounds have been reached).

I would expect that once a single bound is hit, the range maintains fixed along that bounds while increasing the range in the other direction until the bounds in that direction is hit.
#### Complete, minimal, self-contained example code that reproduces the issue

Run examples/howto/prevent_user_zooming_to_far.py  Follow these steps:

- On the "Multiple ranges" graph, zoom in to show data in range Jan03 to Sep03
- then pan all the way to the right until you reach the x_range 'end' bound
- (you are now correctly prevented from panning further to the right)
- attempt to zoom out using wheel zoom tool
- (you are unable to zoom out to view all data using wheel zoom)

**Comment by rabryan** [comment]
The root cause of this behavior seems to be in the following lines in `_update_ranges_individually` in plot_canvas.coffee

```
 # Cancel the event when hitting a bound while scrolling. This ensures that
 # the scroll-zoom tool maintains its focus position. Disabling the next
# two lines would result in a more "gliding" behavior, allowing one to
# zoom out more smoothly, at the cost of losing the focus position.
if is_scrolling and hit_bound
     return
```

https://github.com/bokeh/bokeh/blame/master/bokehjs/src/coffee/models/plots/plot_canvas.coffee#L380

Since `hit_bound` gets set even if one bound is still not hit, this prevents zooming out to reach the full bounds.  One fix would just be to pass `is_scrolling = false` when zooming out, but I'm not sure if this is the best solution

**Comment by bryevdv** [comment]
> I would expect that once a single bound is hit, the range maintains fixed along that bounds while increasing the range in the other direction until the bounds in that direction is hit.

There was a lengthy discussion at the time range bounds were added and the consensus was that the current behavior is the desired behavior

**Comment by rabryan** [comment]
Ok, sorry I didn't see that discussion.  IMO it feels like the zoom tool just stops working for no apparent reason.   Especially with a time series plot of streaming data that is typically bounded on the right to the most recent data point.

**Comment by kernc** [comment]
Duplicate of https://github.com/bokeh/bokeh/issues/5821.
