### ISSUE TITLE
Increase the number of zoom levels available to Bokeh Tile sources

### ISSUE THREAD

**Issue by euandekock** [bokeh/bokeh#6709]
The current version of Bokeh pre-calculates the number of available zoom resolutions for Mercator (and by inheritance BBox) Tile sources. In the *bokehjs/src/coffee/models/tiles/mercator_tile_source.coffee* file this is hard-coded on line 19 as:

 `@_resolutions = (@get_resolution(z) for z in [0..30])`

This assumes we can only ever zoom to level 30, but there are cases where this is insufficient. In my example, I use an ArcGIS server as a BBox tile source, visualising aerial photography at a much higher resolution than commercial services provide.

Attached is an example of the resolution we need to be able to zoom to. (We do have imagery at a few more levels of zoom, but they look less meaningful than this one). If I change the range of resolutions to 50 I can reach all these levels, but maybe this should be a configurable option.

I have only tested this by modifying the generated *bokeh.js* files directly, but I understand that the coffee file is the original source.

![railway](https://user-images.githubusercontent.com/2726868/28862522-ebee9664-7797-11e7-82f6-b34c7f67496a.png)

**Comment by bryevdv** [comment]
@euandekock It seems reasonable not to hard code this, or at least to increase the limit as a short-term fix. Would you be interested in working up a PR for this? The few core devs are all in the middle of large PRs at the moment so outside PRs for things like this is actually a huge help and very appreciated.

**Comment by euandekock** [comment]
I've submitted a pull request. I found that these values are actually already defined as options, that can be configured in the definition as a Tile Source:

`BBoxTileSource(url="", use_latlon=False, max_zoom=40, min_zoom=0)`

The pull request just uses these values now, so it's a more permanent fix than I'd originally planned.
