### ISSUE TITLE
div widgetbox() - links hard to catch

### ISSUE THREAD

**Issue by lhaeberle** [bokeh/bokeh#6710]
I'm using Bokeh to show real-time sensor data (http://78.47.139.7/sensorUfg). In order to add a little headline I use a div widget which also contains two links.
`<a target="_blank" href="http://muench.... </a>`
`<a target="_blank" href="https://twitter.... </a>`  
Please find detailed code and used versions below.

My 'problem': it is quite hard (but not impossible) to catch these links. I've got no idea if this is related to my code or to the widgetbox. Every hint welcome.

Code:
```
# create a div to use as a headline
div = Div(text='''<!DOCTYPE html>
    <head>
        <meta charset="UTF-8">
        <title>Headline Sensor°°° page http://78.47.139.7/sensorUfg</title>
        <style>
            /* unvisited link */
            a:link {
                color: brown;
            }
            /* visited link */
            a:visited {
                color: darkblue;
            }
            /* mouse over link */
            a:hover {
                color: Orange;
            }
        </style>
    </head>
    <font size="5">Real-Time Fine Dust Sensor°°°  </font>
    <font size="3">
        location: <b> <a target="_blank" href="http://muenchen.maps.luftdaten.info/#11/48.1400/11.5600">Unterfoehring/Germany</a></b>
        twitter: <b><a target="_blank" href="https://twitter.com/1000Rzeczy">@1000Rzeczy</a></b>
    </font>''',
    width=750, height=5)

headline = widgetbox(div)

# create a column of plots
cp = column(p, q, r)

# link the plots to get 'common' tool results (!!! parameter ncols wrong documented ->as parameter int)
gp = gridplot(children=[[cp]], toolbar_location='above', merge_tools=True)

# show all the stuff above
curdoc().add_root(headline)
curdoc().add_root(gp)
curdoc().title = 'Sensor°°°'  # browser tap title

# Add a periodic callback (every 1000 milliseconds)
curdoc().add_periodic_callback(update, 1000)

```
Running these versions:
Server:
```
CentOS Linux release 7.3.1611 (Core)
conda list |grep bokeh
bokeh                     0.12.6 
bokeh -v
0.12.6
```
Client:
mac os Sierra, Crome, Safari, Firefox

**Comment by mattpap** [comment]
>  it is quite hard (but not impossible) to catch these links.

What do you mean by "catching a link"?

> ```
> # create a div to use as a headline
> div = Div(text='''<!DOCTYPE html>
>    <head>
>        <meta charset="UTF-8">
>        <title>Headline Sensor°°° page http://78.47.139.7/sensorUfg</title>
>        <style>
>```
`Div.text` should be an HTML fragment (possibly an IFrame), but not a HTML document.

**Comment by lhaeberle** [comment]
If you 'mouse over' the link it is hard to find a position the link really works (and in this case the color also changes to Orange).
In case I run this 'div code'  separately in a browser window it works quite smooth.

**Comment by mattpap** [comment]
@lhaeberle, what does `update` do? Or preferably post complete a example example, such that I could work with.

**Comment by lhaeberle** [comment]
@mattpap thanks a lot for your help! While preparing an example for you I found the issue: the headline (widgetbox(div)) overlapped the plot. After changing the div size (height=15)  it works as smooth as it should. 

Again, thank you very much!
