### ISSUE TITLE
Is there mistake on bokeh/core/state.py ?

### ISSUE THREAD

**Issue by leevei** [bokeh/bokeh#6711]
In the function output_notebook  there is assigned 
`self.notebook_type = notebook_type` 
whereas in function notebook_type it is 
`self._notebook_type = ...`.
The only variable returned is 
`_notebook_type`, which would seem like the correct assignment in first case.

Or am I missing something?

**Comment by bryevdv** [comment]
No, the code is `state.py` is correct. This is an example of [Python getter/setter properties](https://stackoverflow.com/questions/6304040/real-world-example-about-how-to-use-property-feature-in-python)
