### ISSUE TITLE
add visible property to models

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#6713]
Would it be possible to add a "visible" property to bokeh models ? 
When set to False It would just add 'display: none' to the style of the div containing the model; or even replace the style of the div with just 'display: none' which would also remove the space between that element and others divs.
When set to True the div containing the model would go back to its default style.
This would allow to quickly show/hide plots, widgets, or Row / Column layouts

**Comment by mattpap** [comment]
Some models, like renderers, support `visible` property. This can be extended to other models.
