### ISSUE TITLE
can I install bokeh on AWS lambda?

### ISSUE THREAD

**Issue by LuckyGem** [bokeh/bokeh#6716]
hi, I am trying to use AWS Lambda to produce a interactive webpage once there is an update in my s3 bucket, I am wondering if anyone has successfully installed Bokeh on AWS lambda. Which zip file should I upload to AWS Lambda? I previously installed using conda, I did not see any bokeh zip file on the website. Thanks a lot.

**Comment by kevinsa5** [comment]
This should be posted to the google group, not the bug tracker.  You can use `pip install -t folder --use-wheel package_name` to install `package_name` into `folder`, which you can then include in your lambda zip package.

**Comment by bryevdv** [comment]
For reference the group is at:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
