### ISSUE TITLE
Linking plots is order dependent, failing when Figure x_range is passed to Step

### ISSUE THREAD

**Issue by douglasmacdonald** [bokeh/bokeh#6720]
For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh.__version__  '0.12.6'
sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)
Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

#### Description of expected behavior and the observed behavior

Case 1) Works: linking plots instantiating Step first and then passing x_range to the instantiation of Figure scrolling works.

Case 2) Fails: linking plots instantiating Figure  first and then passing x_range to the instantiation of Step does not link the scrolling.

The graphs are generated in case 2 but the linked scrolling does not.

**Comment by bryevdv** [comment]
`Step` is part of the old `bokeh.charts` which has been removed to a new separate `bkcharts` repo. The cause of this problem has to do with the way `bkcharts` works, so any issues should go in the other repository:

https://github.com/bokeh/bkcharts

However, please be advised: ***bkcharts is currently completely unmaintained*** For a high level API on top of Bokeh that is officially endorsed and actively maintained, consider HoloViews:

http://holoviews.org/
