### ISSUE TITLE
0.12.6 HoverTool not in gridplot with merged tools

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#6723]
The HoverTool does not appear in the toolbar of gridplot layouts since 0.12.6 when merged tools is True.

**Comment by julioasotodv** [comment]
Indeed, it does not appear even if all models inside the gridplot include it.

**Comment by bryevdv** [comment]
This is a duplicate of https://github.com/bokeh/bokeh/issues/5497

**Comment by julioasotodv** [comment]
Indeed.Perhaps rocheseb agrees and closes it.

**Comment by bryevdv** [comment]
Thanks, I meant to close it a minute ago but got distracted.
