### ISSUE TITLE
DatePicker not updating enabled/disabled

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6728]
this seems to just be a case of missing plumbing (I don't see any change handlers hooked up) 

ref: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/frzcAhV7zYw

test code:

```
from bokeh.layouts import widgetbox
from bokeh.models import widgets
from bokeh.plotting import curdoc

def change_time():
    print('previous values: ', time.value, time.min_date, time.max_date)
    time.value = '2015-11-10'
    time.min_date = '2015-10-01'
    time.max_date = '2015-12-30'
    print('changed values: ', time.value, time.min_date, time.max_date)

time = widgets.inputs.DatePicker(title="Intervention", value='2015-11-02', min_date='2015-11-01', max_date='2015-12-01')
button = widgets.Button(label="Change time", button_type="success")
button.on_click(change_time)
layout = widgetbox([time,button])

curdoc().add_root(layout)
```

**Comment by mb-magnitude** [comment]
This bug also affects properties like disabled; so you can't enable/disable a DatePicker programmatically.

Is there a revised milestone for this bug, given we are > 0.12.8?

**Comment by bryevdv** [comment]
there is an inflight PR for #8934 that will fix the original reported issue (dupe) but it will not affect anything with enabled/disabled so I will re-purpose this issue for that. 

@mb-magnitude there is no update, if there were it would be here. There are unfortunately many more issues than contributors at the present time so some things will simply take a long time to get to.

**Comment by bryevdv** [comment]
Noting for the future that DatePicker is one of the few remaining widgets that needs selenium tests added.

**Comment by bryevdv** [comment]
#9509 fixes this and many other datepicker issues (as well as adds selenium tests) but note that the implementaton was switched to Flatpickr, and also now date values can *only* be expressed as ISO date strings, or `datetime.date` and nothing else (in particular no more datetime values which caused endless trouble with time zones)
