### ISSUE TITLE
Setting range_padding to 0 can lead to an empty plot

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#6730]
Bokeh 0.12.6

Running
```python
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, curdoc

ds = ColumnDataSource(dict(x=[0], y=[0]), name='initial_ranges_fix_ds')
p = figure(width=200, height=200)
p.circle(x='x', y='x', source=ds)
p.x_range.range_padding = 0

curdoc().add_root(p)
```

leads to
![image](https://user-images.githubusercontent.com/4410314/29001087-2226e506-7aa9-11e7-827c-93a07be1022e.png)

while JS console shows only
```
[bokeh] setting log level to: 'info'
bokeh.min.js:1 [bokeh] Websocket connection 0 is now open
bokeh.min.js:22 Bokeh items were rendered successfully
```

The issue is gone if `x` column has some different values - adding more dots on the same vertical line will still result in an empty plot.
Setting `range_padding` to a value other than 0, however small, leads to a correctly rendered plot.

The reason, it appears, is that the lines
```coffee
        if max == min
          span = @default_span
```
are present only in the `if range_padding? and range_padding > 0` section in `DataRange1d._compute_range`.

**Comment by bryevdv** [comment]
Thanks for another detailed report @p-himik A small PR would be helpful and appreciated (no worries if you aren't able to)
