### ISSUE TITLE
Setting visible=False doesn't work with glyph functions

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#6731]
Bokeh 0.12.6

```python
from bokeh.plotting import figure, curdoc

p = figure()
p.triangle(x=[0], y=[0], visible=False)
c = p.circle(x=[1], y=[1])
c.visible = False

curdoc().add_root(p)
```

The triangle is visible, although it should not be.
The circle is invisible.

The issue is that `bokeh.plotting.helpers._pop_renderer_args` uses `if val` instead of `if val is not None`.

**Comment by bryevdv** [comment]
Thanks for the details report @p-himik do you mind submitting a quick PR?
