### ISSUE TITLE
doc howtos broken - pandas not encoding querystring

### ISSUE THREAD

**Issue by andresmrm** [bokeh/bokeh#6732]
The howtos here seem not to work:
https://github.com/bokeh/bokeh/tree/0.12.6/examples/howto/server_embed
Error and fix can be found here:
https://stackoverflow.com/questions/45414715/embedding-bokeh-server-as-a-library-tornado-error

A possible code fix is to add these lines:

    b, i, q = data_url.partition('?')
    data_url = b+i+requests.utils.quote(q)

before this line:
https://github.com/bokeh/bokeh/blob/0.12.6/examples/howto/server_embed/flask_embed.py#L20

And also `import requests`. Or use `urllib`:

    data_url = b+i+urllib.parse.quote(q)

But I think `urllib` syntax for Python 2 is different from the above. So maybe `requests` is preferred.

**Comment by bryevdv** [comment]
@andresmrm thanks for the report. It appears we do already list `requests` as a "test dependency" (i.e. it is required to run some example) so it seems like it would be OK to rely on it here as well. Would you be able to submit a small PR to make the change? Note that *all* of the "server embed" examples in 

https://github.com/bokeh/bokeh/tree/0.12.6/examples/howto/server_embed

use this same dataset URL, so they would all need this small change I imagine. I am in the middle of another huge PR so if you are able to make this change it would be a great help, and appreciated.

**Comment by bryevdv** [comment]
BTW last I checked this was working for me, so I wonder (offhand) if this is a platform specific issue in some fashion. In any case, escaping is the correct thing to do.

**Comment by andresmrm** [comment]
I just noticed the examples in `master` work well, because they are using local data:
https://github.com/andresmrm/bokeh/blob/master/examples/howto/server_embed/flask_embed.py#L20
https://github.com/bokeh/bokeh/blob/master/bokeh/sampledata/sea_surface_temperature.py#L12

The examples I linked are from `0.12.6`. Not sure where I got the link for that repository tag (probably the docs). Anyway, that is the version in pip, and that version doesn't come with local `sea_surface_temperature` sample data, so you may still want to fix the escaping.

I made this commit, tested it, and it seems ok:
https://github.com/andresmrm/bokeh/commit/4b14df6685a21156bf2029348838d41d824b9b76
Not sure how to PR to a tag (`0.12.6`)... But I think you can pick it anyway if you want.

**Comment by bryevdv** [comment]
@andresmrm please accept my apologies, I forgot that the example was recently changed to use local data at the SciPy sprint. So there is not actually any more need to fix up the example in this way. Accordingly, I am going to close this issue.
