### ISSUE TITLE
plots don't render in dev docs due to missing resources

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6739]
The docs incorrectly looking for `/en/0.12.7dev15/static/js/bokeh-gl.min.js` instead of `dev`

ping @bryevdv

**Comment by bryevdv** [comment]
Fairly certain I fixed the `test` deploy case and broke the dev and regular cases here

https://github.com/bokeh/bokeh/pull/6654/commits/f98188289472ef4b013dd82c65ffd55e9c382eb7#diff-fb8614bfb85117b76215c540120c0e03R91
