### ISSUE TITLE
Customized Div not rendering

### ISSUE THREAD

**Issue by bmtgoncalves** [bokeh/bokeh#6745]
Hi,

I'm trying to derive the Div class so I can customize (slightly) it's behavior. Since MyDiv is a Div (it has all the Div methods, etc...) I would expect that this would work without problems. Indeed, if I add a print(div.text)  or a print(div.params) I get the expected results.

Unfortunately, the resulting html file only displays an error message:

"Model `MyDiv' does not exist. This could be due to a widget or a custom model not being registered before first usage."

Any ideas about what's wrong? I'm using 

* Python 3.5.2 :: Anaconda 4.2.0 (x86_64)
* Bokeh 0.12.6
* OSX 10.12.6
```
from bokeh.io import show
from bokeh.layouts import widgetbox, layout
from bokeh.models.widgets import Div
from bokeh.core.properties import Dict, String, Any

class MyDiv(Div):
    code = """
        Woot %(mess)s
    """
    params = Dict(String, Any)

    def __init__(self, **kwargs):
        params = {}

        kwargs["render_as_text"] = False
        kwargs["text"] = self.code % {"mess": "wooo"}

        super().__init__(**kwargs)
        self.params = params

div = MyDiv()
controls = [div]
inputs = widgetbox(*controls, sizing_mode='fixed')
l = layout([
    [div],
], sizing_mode=sizing_mode)

show(l)
```

**Comment by mattpap** [comment]
This is because every model has to have a corresponding javascript implementation. However, you can force bokeh to reuse an implementation of a super class by adding:
```
__subtype__ = "MyDiv"
__view_model__ = "Div"
```
to your model.

**Comment by bmtgoncalves** [comment]
Great, that fixed it. Thank you for the quick reply.

Perhaps it would be worth adding this example to the documentation? I tried digging through it without much luck and this might be a relatively common case?

**Comment by bryevdv** [comment]
@bmtgoncalves I think that would be a nice addition, we are all pretty underwater with work at the moment. If you wanted to add a short "Python-only Sublcassing" section to this document:

https://raw.githubusercontent.com/bokeh/bokeh/master/sphinx/source/docs/user_guide/extensions.rst

we would be pleased to have you contribution.

**Comment by bmtgoncalves** [comment]
Ok, I'll take care of it as soon as I meet my deadline for this project next week :)
