### ISSUE TITLE
Image overlay on Google Maps

### ISSUE THREAD

**Issue by bmtgoncalves** [bokeh/bokeh#6754]
Hi,

I'm trying to create this effect: https://developers.google.com/maps/documentation/javascript/examples/overlay-simple using Bokeh. See code below. It all seems to work fine, except that when I open the gmap_plot.html file I see the image flashing and being immediately replaced by the original google map. If I understand it correctly, this means that the map is being written on top of the image, despite the fact that I'm explicitly setting the level to 'image'. This seems to only happen with image overlays, as I do the same thing with a Circle and it shows up fine. The order in which the Circle and ImageURL are added to the plot seems to not make a difference.  

I'm using:

Bokeh 0.12.6
Python 3.5.2 :: Anaconda 4.2.0 (x86_64)
OSX 10.12.6

```
from bokeh.io import output_file, show
from bokeh.models import (
    GMapPlot, GMapOptions, ColumnDataSource, Circle, DataRange1d, PanTool, WheelZoomTool, BoxSelectTool
)
from bokeh.models.glyphs import ImageURL
from bokeh.plotting import figure

map_options = GMapOptions(lat=62.323907, lng=-150.109291, map_type="roadmap", zoom=11)
fig = figure()
plot = GMapPlot(
    x_range=DataRange1d(), y_range=DataRange1d(), map_options=map_options
)
plot.api_key = "GOOGLE_MAPS_API_KEY"

source = ColumnDataSource(
    data=dict(
        lat=[40.4774],
        lon=[-74.2589],
    )
)

source2 = ColumnDataSource(
    data=dict(
        url=["https://developers.google.com/maps/documentation/javascript/examples/full/images/talkeetna.png"],
        x=[-150.287132],
        y=[62.281819],
        dx=[0.281524],
        dy=[0.118652]))

circle = Circle(x="x", y="y", size=15, fill_color="blue", fill_alpha=0.8, line_color=None)
plot.add_glyph(source2, circle, level='image')
img = ImageURL(url='url', x='x', y='y', w='dx', h='dy', anchor='bottom_left')
plot.add_glyph(source2, img, level='image')
plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())

output_file("gmap_plot.html")
show(plot)

```

Screenshot:

![screen shot 2017-08-09 at 2 59 21 pm](https://user-images.githubusercontent.com/537205/29139006-64591220-7d13-11e7-80b6-8d385a428931.png)

The console is clean with no errors. Any ideas about what's going on? 

Best,

Bruno

**Comment by bryevdv** [comment]
Sorry this missed getting triaged earlier. I think this is a usage problem. The underlying coordinate system is actually in meters (i.e. Web Mercator northings and eastings.) I think if you convert your image url coords to web mercator then things will work as expected. If that is not the case, please re-open.
