### ISSUE TITLE
ColorMapper special colors do not support alpha

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#6755]
Back in https://github.com/bokeh/bokeh/issues/5324 I described a bug handling RGB(A) tuples as special colors (nan_color, low_color and high_color) for color mappers. While that issue was partially resolved actually specifying an alpha value using this tuple was not supported. This is a problem that's particularly annoying in geographic contexts where you want to see the background to see the context of the Image you are viewing. Here is a small example demonstrating the issue:

```python
arr = np.random.rand(100, 100)
arr[:50, :50] = np.NaN

p = figure(x_range=(-.5, .5), y_range=(-.5, .5), width=300, height=300)
p.scatter(x=np.random.rand(100)-.5, y=np.random.rand(100)-.5)
r = p.image(image=[arr[::-1]], x=-.5, y=-.5, dw=1, dh=1, palette=hv.Cycle('Reds').values)

# Set nan color
r.glyph.color_mapper.nan_color = (0, 0, 0, 0)
show(p)
```

<img width="277" alt="screen shot 2017-08-10 at 11 24 31 am" src="https://user-images.githubusercontent.com/1550771/29166514-89789b88-7dbe-11e7-902c-3aeb4fd24ac6.png">

Additionally either due to issues parsing the rgba string or due to Javascript's 31-bit limitation of bitwise math you can get weird results like this:

```python
r.glyph.color_mapper.nan_color = (255, 255, 255, 0.5)
```

<img width="279" alt="screen shot 2017-08-10 at 11 24 39 am" src="https://user-images.githubusercontent.com/1550771/29166533-a2ea4742-7dbe-11e7-8d1b-2049f8356e5e.png">

The output I would expect in this case looks like this:

<img width="258" alt="screen shot 2017-08-10 at 11 26 03 am" src="https://user-images.githubusercontent.com/1550771/29166549-ba5eb520-7dbe-11e7-8f38-ae201d5afa3d.png">

I have already worked up a fix since we need this functionality urgently and will submit a PR shortly.

**Comment by jbednar** [comment]
Thanks for documenting this longstanding problem.
