### ISSUE TITLE
Random data in server examples causes image diff to fail

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6762]
The following examples:

- models/server/widgets
- plotting/server/responsive
- plotting/server/selection_histogram

fail. File examples' tests configure a seed (stdlib, numpy) to generate stable images. If possible, this should be extended to server examples, or those shouldn't use random data. If nothing works, those examples shouldn't participate in image diff, but that's the final measure (no image diff makes examples pretty useless).

**Comment by canavandl** [comment]
That's for creating an issue and assigning me. I'll get to this tonight/tomorrow.
