### ISSUE TITLE
legend title

### ISSUE THREAD

**Issue by mullenkamp** [bokeh/bokeh#6769]
I was wondering if an option can be added to bokeh to add titles to legends?
This is similar to a question that was asked here:
[Any way to create a legend title in Bokeh?](https://stackoverflow.com/questions/38155099/any-way-to-create-a-legend-title-in-bokeh
)

Something consistent with the bokeh syntax like:
```
p.legend.title = 'Legend Title'
```

**Comment by bryevdv** [comment]
This capability does not yet exist, but has recently been brought up by a few different folks (ping @jlstevens @philippjfr) So I've slated it for `0.12.8` However, it should not be a lot of work, so we'd be happy to help anyone that can work on it sooner than we are able to get to it.

**Comment by philippjfr** [comment]
Yes, I'd love to get this functionality into bokeh but I probably won't find the time in the near future.

**Comment by mattpap** [comment]
I'm marking this as part of layout work, because it would a nice opportunity to bring layout to annotations.

**Comment by bryevdv** [comment]
> I'm marking this as part of layout work, because it would a nice opportunity to bring layout to annotations.

That seems like overkill? Drawing a title above the existing legend seems like a trivial thing to do, what need is there to complicate it by bringing in layout?

**Comment by mattpap** [comment]
Sure, in isolation this is definitively an overkill, and if someone wants to just add this feature then go ahead. However, I would like to have a broader look at how we layout annotations, because having a title on a legend shouldn't be a special case, but should nicely flow from canvas layout. I have some thoughts on this subject based on failings with my recent tutorial.

**Comment by birdsarah** [comment]
@mattpap, did this end up being included in layout work?

**Comment by mattpap** [comment]
Not yet, but it's work in progress.
