### ISSUE TITLE
Task: Add user warn/error to ColumnDataSource.from_df method about DataFrame containing "index" column

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6770]
There's some weirdness around using pandas DataFrames to create ColumnDataSources for graph visualization in Bokeh. Currently Bokeh requires the GraphRenderer.node_renderer.data_source to have a column named "index". This column is the reference for the edge's start and end values.

The issue is that creating a ColumnDataSource with a pd.DataFrame with:
* an unnamed Index
* a column named "index"

The resulting CDS will have a "index" column containing the dataframe (capital-i) Index and not the column. This is a gotcha in pandas where ``df.index`` refers to the Index but ``df["index"]`` refers to a column named "index".

Bokeh 0.12.7dev16

**Comment by canavandl** [comment]
Thinking about it some more, this is a non graph-specific issue related to the ColumnDataSource._from_df method. I think the best behavior would be to warn/error users about the ambiguity in such a situation.

**Comment by crashMOGWAI** [comment]
Agree with the warning. The issue is easy to mitigate once identified, and a little nudge in the right direction is always helpful.

**Comment by bryevdv** [comment]
MRE:

```
In [1]: import pandas as pd

In [2]: df = pd.DataFrame(dict(index=[0.0, 1.1, 2.2]))

In [3]: from bokeh.models import ColumnDataSource

In [4]: s = ColumnDataSource(df)

In [5]: s.data
Out[5]: {'index': array([0, 1, 2])}
```
