### ISSUE TITLE
Task: Fix-up skipped app examples for examples tests

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6771]
The following app examples are skipped in the examples tests manifest for a variety of reasons:
```
skip: ["gapminder", "pivot", "simple_hdf5", "spectrogram", "surface3d", "stocks"]
```
They should be fixed up and unskipped.

bokeh 0.12.7dev16

**Comment by mattpap** [comment]
The current situation is:
```
no_diff: ["gapminder", "surface3d"]
skip: ["simple_hdf5", "spectrogram", "stocks"]
```
which is as good as it will get. This was fixed in PR #8652.
