### ISSUE TITLE
Bokeh legend location

### ISSUE THREAD

**Issue by ciornav** [bokeh/bokeh#6773]
Hello,

not sure if is the right place to submit a issue.  Found a incoherence between documentation and code.  In bokeh.plotting the legend location  : http://bokeh.pydata.org/en/0.10.0/docs/user_guide/styling.html#location
is written that the orientation property should be used for the location of the legend :

Location
The location of the legend labels is controlled by the orientation property. Valid values for this property are:

"top_right"

"top_left"

"bottom_left"

"bottom_right"

The default location is "top_right".

Actually not """p.legend.orientation = "bottom_left"  '""
should be used but """p.legend.location = "bottom_left"  """

Didn't found how to contribute elsewhere.

Thanks,

# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by mattpap** [comment]
The documentation, you're referring to, is several years old. The most recent version of bokeh is 0.12.6 (http://bokeh.pydata.org/en/latest/).

**Comment by mattpap** [comment]
> Didn't found how to contribute elsewhere.

The proper place would be either the mailing list or gitter channel. Both links are above (under "read and follow these instructions carefully").

**Comment by bryevdv** [comment]
For reference, here is the current (and correct/up to date) documentation for legend locations:

http://bokeh.pydata.org/en/0.12.6/docs/user_guide/styling.html#location
