### ISSUE TITLE
SVG backend not correctly coloring glyphs in legends 

### ISSUE THREAD

**Issue by varchasgopalaswamy** [bokeh/bokeh#6775]
In bokeh 0.12.6, trying to use the svg backend with a legend of multiple glyph colors sets all the glyphs to use the color of the last glyph loaded into the legend. What should happen is that I should see a red diamond and blue square, but instead when using the svg backend, you see a blue diamond and square in the legend. 

```
import bokeh.plotting as bp
import bokeh.models as bm
fig = bp.figure(output_backend='svg')
cross = fig.diamond(x=1,y=1,color='red')
square = fig.square(x=2,y=1)
legends = [['circle',[cross]],['square',[square]]]
legend = bm.Legend(items=legends)
fig.add_layout(legend,'left')
bp.show(fig)
```
gives 
![image](https://user-images.githubusercontent.com/2359219/29385200-d45774d6-82a4-11e7-801b-b1148a4ddb45.png)

whereas 
```
import bokeh.plotting as bp
import bokeh.models as bm
fig = bp.figure(output_backend='canvas')
cross = fig.diamond(x=1,y=1,color='red')
square = fig.square(x=2,y=1)
legends = [['circle',[cross]],['square',[square]]]
legend = bm.Legend(items=legends)
fig.add_layout(legend,'left')
bp.show(fig)
```
gives 
![image](https://user-images.githubusercontent.com/2359219/29385223-e895897e-82a4-11e7-985d-d726f80274e1.png)

as expected. I'm running this in a jupyter notebook, with python3.5.2, installed using conda4.3.24 on Firefox on RHEL7

**Comment by bryevdv** [comment]
Thanks for the detailed report @varchasgopalaswamy there's nothing we can do about it in time for the next release but I have slated it to be looked at for `0.12.8` 

cc @canavandl

**Comment by varchasgopalaswamy** [comment]
When you patch this, could you push it to a nightly?

**Comment by varchasgopalaswamy** [comment]
Another, probably related bug - if you use the `circle_x`, `circle_cross` glyphs, the cross or x will render, but the surrounding marker will not when using the svg backend.

**Comment by bryevdv** [comment]
That sounds like it is probably related, and possibly points to an issue in the underlying third-party`canvas2svg` library that is used to implement this feature, which to be honest, would not the best scenario to have try and deal with. But we will take a look after the next release is out.

**Comment by varchasgopalaswamy** [comment]
Also, trying to hide markers using`legend.click_policy=hide` behaves as expected on the plot, but acts rather strangely for the legend.

Both on:
![image](https://user-images.githubusercontent.com/2359219/29388245-e35f4f96-82b1-11e7-9242-53ba9693114b.png)

Red Square hidden: 
![image](https://user-images.githubusercontent.com/2359219/29388273-fafdeb94-82b1-11e7-8b66-cf2b40966179.png)

Blue Square hidden:
![image](https://user-images.githubusercontent.com/2359219/29388282-0dcfd3f4-82b2-11e7-9c6b-209ca121e53d.png)

Both squares hidden:
![image](https://user-images.githubusercontent.com/2359219/29388294-1bf7d12a-82b2-11e7-9ab6-bb96a73dfa94.png)

**Comment by bryevdv** [comment]
> Also, trying to hide markers usinglegend.click_policy=hide behaves as expected on the plot, but acts rather strangely for the legend.

Although we probably need to make this clearer, the SVG output mode is really intended to support the generation of static image exports. That it "works" somewhat in the interactive case is purely an accident, and making it actually work comparable to HTML canvas in real browsers is not a priority.
