### ISSUE TITLE
Feature request: Selecting glyphs that affect auto-scale

### ISSUE THREAD

**Issue by cloud-rocket** [bokeh/bokeh#6776]
I am having multiple glyphs in live streaming data. The auto-scale functionality works fantastic, but now I am willing to add extra (semantic) glyphs which should not affect the auto-scaling.

Doing it from scratch will require to calculate min/max on server side (at least for initial load), because there is no BokehJS callback on load (which on it's own might be a great and easy to implement feature).

(originated from here - https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/lSEiI-ROnPg)

Thanks,
Meir Tseitlin

**Comment by bryevdv** [comment]
This can be done by setting the `.renderers` on the range:

https://bokeh.pydata.org/en/latest/docs/reference/models/ranges.html#bokeh.models.ranges.DataRange.renderers
