### ISSUE TITLE
bokeh plotting with timestamp

### ISSUE THREAD

**Issue by LuckyGem** [bokeh/bokeh#6777]
hi, when I tried to plot a time series using my data frame, this is the first two columns of my dataframe. 
         dpsomega time                dpsomegafail rate      other test......      
0  2017-07-02 14:23:43           0.056075                   ....
1  2017-07-07 14:24:08           0.187328   
2  2017-07-07 14:23:53           0.064470   
3  2017-07-08 14:24:03           0.114504   
4  2017-07-04 14:23:58           0.091387  
5                  NaN                        NaN                   
6                  NaN                        NaN                 
7                  NaN                        NaN                  
8                  NaN                        NaN                   
9                  NaN                        NaN                  

I tried to use 
fig=TimeSeries(failDF, x = "test time", y = "test fail rate",builder_type='point',xscale="datetime")
but I got the following errorValueError: expected an element of either String, Column(Float), Column(String), Column(Datetime) or Column(Bool), got 0    2017-07-02 14:23:43
1    2017-07-07 14:24:08
2    2017-07-07 14:23:53
3    2017-07-08 14:24:03
4    2017-07-04 14:23:58
5                    NaN
6                    NaN
7                    NaN
8                    NaN
9                    NaN
did this error occur because of the NaNs? I am pretty sure that the data type of the timestamp is string. May I know what's wrong with my code? Thanks.

**Comment by bryevdv** [comment]
@LuckyGem `TimeSeries` is part of the old `bokeh.charts` which has been removed to a new separate `bkcharts` repo. The cause of this problem has to do with the way bkcharts works, so any issues should go in the other repository:

https://github.com/bokeh/bkcharts

However, please be advised: bkcharts is currently completely abandoned and unmaintained So, there is no guarantee when or if ever issues there may get fixed. For a high level API on top of Bokeh that is officially endorsed and actively maintained, consider HoloViews:

http://holoviews.org/
