### ISSUE TITLE
HoverTool.renderers accept List(Renderer) but supports only List(GlyphRenderer)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6781]
This made sense when `GlyphRenderer` was the only type of renderer. However, now we have annotations, tiles, etc., and those don't work with `HoeverTool` and others (fail due to missing `data_source` property). We should either make tools work with all types of renderers or use a different base class in properties (`GlyphRenderer`).

My initial idea was to have a tooltip for a `Label` and I tried to use `HoverTool`, because there is no intrinsic support for tooltips in annotations.

**Comment by bryevdv** [comment]
I would have to be convinced of the utility of hover tool over annotations, so my first thought is that the definition should be tighten up what hover tool accepts.
