### ISSUE TITLE
Get Current Plot Ranges

### ISSUE THREAD

**Issue by bokehuser85** [bokeh/bokeh#6782]
Requesting a feature to get the current plot ranges from python i.e. Plot.x_range.get() -->[0.54, 4.56] 

This would be especially useful when linked plots may need to be dynamically generated because their total view would contain too much data to maintain in memory.

**Comment by bryevdv** [comment]
This would have to be in the form of a read-only property, e.g. 
```
p.x_range.computed_start
p.x_range.computed_end
```
or possibly 
```
p.x_range.computed_range # reports computed [start, end]
```

**Comment by nleclercq** [comment]
An bokeh event announcing ranges changes would also be a great feature to have.

**Comment by bryevdv** [comment]
In fact this is already possible, data range `start` and `end` update on pan, zoom, reset, etc:
```
from bokeh.io import curdoc
from bokeh.plotting import figure

p = figure()
p.line([1,2,3], [4,6,5])

p.x_range.on_change('start', lambda attr, old, new: print("Start", new))
p.x_range.on_change('end', lambda attr, old, new: print("End", new))

curdoc().add_root(p)
```
<img width="908" alt="screen shot 2017-11-07 at 17 19 37" src="https://user-images.githubusercontent.com/1078448/32523203-ea0e52c8-c3df-11e7-9c30-25d04e85baa4.png">

**Comment by gsteele13** [comment]
Ok, I'm a bit of a noob. I'm trying to get the current zoom range after an interactive zoom in a notebook. 

I start with this: 

```
import numpy as np

from bokeh.plotting import figure, show
from bokeh.io import output_notebook, push_notebook
from bokeh.models import ColumnDataSource, Range1d
from bokeh.layouts import column, row

import ipywidgets as widgets

output_notebook()
```

Then I create a plot:

```
# Magnitude plot
source1 = ColumnDataSource()
x = np.linspace(0,1,100)
y = x**2
xr  = Range1d()
source1.data = dict(x=x, y=y)
p1 = figure(plot_width=600,plot_height=400, x_range = xr)
p1.line('x', 'y', source=source1)
p1.xaxis.axis_label =  "Test"
target = show(p1, notebook_handle=True)
```
Then I zoom around a bit, and in the next cell I check what the value of the x-range is:
```
p1.x_range.start
```
Regardless of what I zoom to, the value of `p1.x_range.start` is always  `0`. Am I missing something here? 

Thanks!
Gary

**Comment by bryevdv** [comment]
@gsteele13 `show` with notebook handles is for *one-way* Python->JS updates only. If you want to have bi-directional updates back to Python, you would need to embed a Bokeh server app in the notebook. Happy to discuss but the appropriate venue is the project Discourse: https://discourse.bokeh.org/

**Comment by gsteele13** [comment]
Sure, of course, added it here:

https://discourse.bokeh.org/t/getting-zoom-current-zoom-setting-back-into-python/5819

Cheers,
Gary
