### ISSUE TITLE
Make notebook display extendible by external libraries

### ISSUE THREAD

**Issue by zjffdu** [bokeh/bokeh#6788]
#### Description of expected behavior and the observed behavior
I'd like to embed bokeh app into Apache Zeppelin just as embed bokeh app in Jupyter

**Comment by bryevdv** [comment]
Re-purposing this issue to cover making the notebook display code path generally extensible.

**Comment by zjffdu** [comment]
@bryevdv I created bkzep, I have manaully verify it, could you help review it ? Thanks
https://github.com/zjffdu/bkzep
