### ISSUE TITLE
Weird import error python2

### ISSUE THREAD

**Issue by nexusblake** [bokeh/bokeh#6792]
Sorry im not a native english speaker, so my language isnt very good.
First of all i was trying to install bokeh because someone tell me is very similar to Shiny (Rstudio), so i installed the bokeh following the instructions in the website(im using Ubuntu 16.04). Basically i installed every dependence and then tried installing bokeh via pip. everything went well, no errors, but went i try to run the example script:

```
from bokeh.plotting import figure, output_file, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

# show the results
show(p)

```
i get the error that the module isnt installed:
```
 File "/home/bokeh.py", line 1, in <module>
    from bokeh.plotting import figure, output_file, show
ImportError: No module named plotting
```
tried everything, then i found out that the entire script cant be run(using: python file.py), but single lines can. So i started from there. Trying to find a solution, i installed anaconda and created a new enviroment with all the needed dependencies and i got the same issue. Cant run a entire python script, but if i execute python in terminal and then line by line i can execute the script. Aaand right now isnt working at all, neither line by line nor trying to execute the entire script.
```
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import bokeh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bokeh.py", line 1, in <module>
    from bokeh.plotting import figure, output_file, show
ImportError: No module named plotting
>>> exit()

```
Dont know how to fix the issue. by the way.. bokeh just works line by line? 
tried removing everything related to bokeh and then installing from pip and conda again, with no success
hope you can help me

Greetings :)

**Comment by bryevdv** [comment]
It looks like you have a local module you created yourself called `bokeh.py` in your path. In that case since Python 2 does not default to absolute imports, it will try to import from your `bokeh.py` instead of the actual bokeh library that is installed. 

As a gentle reminder for the future: general support questions (like this one) should go to the public mailing list, not the issue tracker:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
