### ISSUE TITLE
Duplicated threads are started for embedding bokeh app in Jupyter

### ISSUE THREAD

**Issue by zjffdu** [bokeh/bokeh#6795]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh: 0.12.7-dev (commit hash 53283eeb52eb5a0080e0e14c1354f6e6f0e21e7e)
Python: 3.5
Notebook: Jupyter

#### Description of expected behavior and the observed behavior
Only one thread should be started, but if you run the following code snippet. You will notice `start blocking_task` display 2 times which prove that 2 duplicated threads are started.  

#### Complete, minimal, self-contained example code that reproduces the issue

```
from functools import partial
from random import random
from threading import Thread
import time

from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure

from tornado import gen

def modify_doc(doc):
    
    # this must only be modified from a Bokeh session allback
    source = ColumnDataSource(data=dict(x=[0], y=[0]))
    @gen.coroutine
    def update(x, y):
        source.stream(dict(x=[x], y=[y]))

    def blocking_task():
        print("start blocking_task")  
        while True:
            # do some blocking computation
            time.sleep(0.1)
            x, y = random(), random()

            # but update the document from callback
            doc.add_next_tick_callback(partial(update, x=x, y=y))

    p = figure(x_range=[0, 1], y_range=[0,1])
    l = p.circle(x='x', y='y', source=source)

    doc.add_root(p)

    thread = Thread(target=blocking_task)
    thread.start()


    # Set up the Application 
handler = FunctionHandler(modify_doc)
app = Application(handler)

doc = app.create_document()
show(app, notebook_url='localhost:8888')

```

#### Screenshots or screencasts of the bug in action
<img width="749" alt="screen shot 2017-08-22 at 2 08 10 pm" src="https://user-images.githubusercontent.com/164491/29551015-6117ce82-8743-11e7-882d-2ed09f3aa71b.png">

**Comment by bryevdv** [comment]
cc @canavandl

**Comment by zjffdu** [comment]
ping @canavandl in case you miss it.

**Comment by bryevdv** [comment]
@zjffdu This is a usage error. You have the unecessary line:
```
doc = app.create_document()
```
right before you call `show`. This action triggers `modify_document` but then immediately throws the result away. Delete this line and the app shows with only one print printed.
