### ISSUE TITLE
hbar issue stacked bar chart

### ISSUE THREAD

**Issue by stevensallright** [bokeh/bokeh#6803]
Hi,

I've created a horizontal stacked bar chart using `hbar` and experienced some strange behavior where bars with value 0 show up as a thin sliver.

Here's a picture of said bar chart:
![bokeh_hbar](https://user-images.githubusercontent.com/20945964/29607298-b2dfa38e-87e8-11e7-8e3d-dbcf288971a8.png)

I'm using Bokeh 0.12.5 and Pandas 0.19.2  with Chrome.
Thanks.

**Comment by mattpap** [comment]
You will need to test this on 0.12.6, as this is the most recent stable version. If this still doesn't work as expected, you need to provide a minimal code example for us to reproduce the problem.

**Comment by stevensallright** [comment]
Just upgraded and the issue persists.

Here is my code:

```
data = pd.DataFrame({
    'Project': ['1', '2', '3', '4'],
    'stack_1': [0, 0, 0, 0],
    'stack_2': [50, 75, 50, 40],
    'stack_3': [100, 75, 75, 40],
    'data_1': [50, 75, 50, 40], 
    'data_2': [100, 75, 75, 40], 
    'data_3': [120, 75, 75, 40], 
    'Fulfilled': [50, 75, 50, 40],
    'Fulfilled with new hires': [50, 0, 25, 0],
    'Not fulfilled': [20, 0, 0, 0], 
})

red = '#de2d26'
green = '#2ca25f'
amber = '#fec44f'
colors_ = [red, amber, green]
bar_opts = dict(y='Project', height=0.75)

hover = HoverTool(tooltips=[
    ('Project Name', '@Project'),
    ("Fulfilled demand", "@{Fulfilled}{int}"),
    ("Fulfilled with new hires", "@{Fulfilled with new hires}{int}"),
    ("Not fulfilled", "@{Not fulfilled}{int}"),
])

p = figure(plot_width=1000, plot_height=300, y_range=data['Project'].tolist()[::-1], 
           title='Chart', tools=[hover])

source = ColumnDataSource(data)

p.hbar(left='stack_1', right='data_1', source=source, **bar_opts, color=colors_[2], alpha=0.8)
p.hbar(left='stack_2', right='data_2', source=source, **bar_opts, color=colors_[1], alpha=0.8)
p.hbar(left='stack_3', right='data_3', source=source, **bar_opts, color=colors_[0], alpha=0.8)

show(p)
```
The bars for projects 2, 3, and 4 illustrate my issue.

**Comment by bryevdv** [comment]
You'll probably need to set the line color for the bar to None

**Comment by stevensallright** [comment]
@bryevdv I'm sorry I'm not sure I understand. Is there  way to set a condition on the coloring of the bars? Like have the color be None if the added amount to the stacked bar is 0.

If so could you point me to an example?
Thanks.

**Comment by stevensallright** [comment]
@bryevdv I see. Thanks!

**Comment by bryevdv** [comment]
@mattpap I am inclined to close this? I don't think there are any actionable changes we can make

**Comment by mattpap** [comment]
@bryevdv, sure, it seems that this is something that a higher level API should be concerned of.
