### ISSUE TITLE
nbconverted static notebooks fail to render

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6808]
After recent JLab work, running e.g. 
```
jupyter nbconvert --to html quickstart.ipynb
```
results in a JS console error:
```
TypeError: undefined is not an object (evaluating 'root.Jupyter.OutputArea')
```
and no plots displayed. 

Possible that the test just needs to be protected better to be skipped entirely in the static case.

Using `nbconvert 5.2.1` with
```
jupyter_client            5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
notebook                  5.0.0                    py36_0
```

cc @canavandl

**Comment by bryevdv** [comment]
Here is the relevant code:
```
var OutputArea = root.Jupyter.OutputArea;
if ((root.Jupyter !== undefined) && (OutputArea.prototype.mime_types().indexOf(MIME_TYPE) == -1)) {
  register_renderer(root.Jupyter.notebook, OutputArea);
}
```
I think it needs to be more like
```
if ((root.Jupyter !== undefined) {
  var OutputArea = root.Jupyter.OutputArea;
  if (OutputArea.prototype.mime_types().indexOf(MIME_TYPE) == -1)) {
    register_renderer(root.Jupyter.notebook, OutputArea);
  }
}
```

**Comment by bryevdv** [comment]
Though.... if the rendered is not registered, how do the subsequent cell shows (which only make mime display calls) actually do anything? I guess I would expect that `root.Jupyter` would be present in statically rendered notebooks so that rendered mime display calls work?

cc @jasongrout @blink1073 what are we mssing about making things displayed with the mime type mechanism work in statically rendered notebooks?

**Comment by bryevdv** [comment]
For reference, the output cells after calls to `show` in an nbconverted notebook are completely empty.

**Comment by blink1073** [comment]
What rendered after `nbconvert` when using the old JavaScript injection method?   The standard way to handle this is include a fallback mime type that is recognized by `nbconvert`.  I believe ipywidgets creates an html-only representation for static rendering.

**Comment by bryevdv** [comment]
@blink1073 previously we published the full necessary HTML/JS in the output cells

**Comment by bryevdv** [comment]
@blink1073 where can we find what ipywidgets does, to study it?

**Comment by bryevdv** [comment]
@damianavila do you know where I can find out information or docs about the "fallback mime types" for `nbconvert` that @blink1073  mentions? A google search or searching for "mime" in the nbconvert site search did not turn up any useful results.

**Comment by bryevdv** [comment]
> The standard way to handle this is include a fallback mime type that is recognized by nbconvert"

This makes me think we might have to put the bokeh JSON in the `display_data` metadata arg to avoid sending it multiple times, if rendering statically means adding additional fallback mime types to render in the static context. 

My *extreme* worry here is that this means  in order to support the `nbconvert` case that in addition to maintaining the new mime output code across two platforms, will have to *also* add back all the gorpy garbage to publish raw HTML/JS as `text/html` or something too.

**Comment by bryevdv** [comment]
@SylvainCorlay do you have any insight here?

**Comment by blink1073** [comment]
Here is the file that embeds the JavaScript for widgets in the classic notebook: https://github.com/jupyter-widgets/ipywidgets/blob/master/widgetsnbextension/src/embed_widgets.js

@jasongrout and I should talk about this today (we're at JupyterCon).

**Comment by bryevdv** [comment]
@blink1073 right, that uses:
```
var VIEW_MIME_TYPE = "application/vnd.jupyter.widget-view+json"
```
which seems works because nbconvert knows somethign about it:
```
            'NbConvertBase': {
                'display_data_priority' : ['application/vnd.jupyter.widget-state+json',
                                           'application/vnd.jupyter.widget-view+json',
                                           'application/javascript',
                                           'text/html',
                                           'text/markdown',
                                           'image/svg+xml',
                                           'text/latex',
                                           'image/png',
                                           'image/jpeg',
                                           'text/plain'
                                          ]
                },
```
https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/html.py#L48

(at least knows enough not to discard it)

**Comment by bryevdv** [comment]
FYI this is closed because JLab support is being reverted so the `0.12.7` release can happen
