### ISSUE TITLE
AutocompleteInput does not complete word when option is clicked

### ISSUE THREAD

**Issue by tkchris93** [bokeh/bokeh#6822]
I am using MacOS, Bokeh 0.12.7rc3, python 2.7.13, and Google Chrome to view a static html file generated by Bokeh. Clicking on a word in the autocomplete dropdown only sometimes (~25%) completes the word in the input box. I have not been able to see any pattern as to when it works and when it doesn't. There is no additional information to share from the javascript console.

```
from bokeh.plotting import show, output_file
from bokeh.models.widgets import AutocompleteInput

output_file('autocomplete_input.html')

input_widget = AutocompleteInput(completions=['pok', 'wer', 'foo', 'bar', 'baz'], title='test')
show(input_widget)
```

**Comment by mattpap** [comment]
This is a bizarre bug.

**Comment by guojunchi11** [comment]
This happens to me, too.  
Also, I can not use the down arrow on the keyboard to select, have to use the mouse

**Comment by RafaelPais** [comment]
Same behavior in bokeh 0.12.13, any update about this?

**Comment by bryevdv** [comment]
@RafaelPais  sorry, unfortunately not. Generally speaking, there is currently a large excess of issues relative to the number of core contributors, meaning some things will simply not be able to get done for a long time, unless new contributors get involved. If you have the interest and ability, I'm happy to point you in the right direction to get started.

**Comment by RafaelPais** [comment]
@bryevdv Many thanks for the prompt reply. Yes, I'm interested in contributing. I'll take note of the documentation available in the Getting Set Up section on DEVELOPER GUIDE. However, I will be very pleased if you can direct me to code related to autocomplete. I have a special interest in solving this problem.

**Comment by bryevdv** [comment]
@RafaelPais Absolutely, the python model is defined here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/widgets/inputs.py#L65

I doubt there is much to see or do there, but just for reference. All the work is done in the JS implementation, which is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/autocomplete_input.ts

**Comment by DanielaBreitman** [comment]
This issue still occur seems to occur in bokeh==0.13.0. Is there any workaround?

**Comment by magee256** [comment]
I'm still seeing this in bokeh==1.0.1, [this pull request](https://github.com/bokeh/bokeh/pull/8126) references a layout rework that should fix the issue. Is that rework still ongoing?

**Comment by linusmarco** [comment]
I'm also still experiencing this issue in 1.0.0. 

@mattpap, is the layout rework still ongoing? I didn't see a link to an issue or PR where you referenced the work [here](https://github.com/bokeh/bokeh/pull/8126#issuecomment-427103652), but it looks like the [AutocompleteInput TS code](https://github.com/bokeh/bokeh/blame/master/bokehjs/src/lib/models/widgets/autocomplete_input.ts) hasn't been updated recently so my guess is that it's still in progress. 

Are you open to a new PR on this?

**Comment by mattpap** [comment]
This is fixed in PR #8085.

**Comment by chaoukiiiii** [comment]
Hello, I'm facing the same issue in 1.0.4, how to solve it? any update?

**Comment by linusmarco** [comment]
@chaoukiiiii, PR #8085 referenced above is still pending. It's a massive PR and looks like there's still a bit of work to be done on it.

**Comment by mattpap** [comment]
Hopefully it will be merged tomorrow. We will see how that goes.

**Comment by bryevdv** [comment]
@mattpap FYI I would say the original code above works, in that the drop down always seems to show up with the correct suggestions now. However, it only seems possible to choose a selection by clicking on it, i.e. can't arrow down and press enter. Fine making that a new issue but I think it's a reasonable expectation for this widget.

**Comment by bryevdv** [comment]
Would suggest follow on issues re: specific UX interaction improvements
