### ISSUE TITLE
Tap events not registering during MouseMove events 

### ISSUE THREAD

**Issue by kdesimone** [bokeh/bokeh#6826]
I'm working on an interactive animation running on the bokeh server. Glyphs move around the figure and users are instructed to click on these while in transit. I noticed that Tap events only registered back on the server when the mouse was stationary. I figured this was due to some kind of bottleneck sending events back to the python environment from the client.  Thus, I modified the CustomJS example found [here](https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#userguide-interaction-jscallbacks) to see if these Tap events registered on the client side (see below). This does not seem to make a difference—if you slowly move the mouse around the figure and click (or double-click) you will not see tap (or double-tap) events register. The mouse must be stationary to register taps.

This behavior was described as unexpected by @bryevdv  on the [google group](https://groups.google.com/a/continuum.io/d/msg/bokeh/CZ_gy1KV3UM/rpaImvEDCgAJ).

Is it possible to glean tap events while moving the mouse?

Minimal example:
```
import numpy as np
from bokeh.io import show, output_file
from bokeh.plotting import figure
from bokeh import events
from bokeh.models import CustomJS, Div
from bokeh.layouts import row

def display_event(div, attributes=[], style = 'float:left;clear:left;font_size=0.5pt'):
    "Build a suitable CustomJS to display the current event in the div model."
    return CustomJS(args=dict(div=div), code="""
        var attrs = %s; var args = [];
        for (var i=0; i<attrs.length; i++ ) {
            args.push(attrs[i] + '=' + Number(cb_obj[attrs[i]]).toFixed(2));
        }
        var line = "<span style=%r><b>" + cb_obj.event_name + "</b>(" + args.join(", ") + ")</span>\\n";
        var text = div.text.concat(line);
        var lines = text.split("\\n")
        if ( lines.length > 35 ) { lines.shift(); }
        div.text = lines.join("\\n");
    """ % (attributes, style))

p = figure(tools="")
div = Div(width=1000)
layout = row(p, div)

## Events with attributes
point_attributes = ['sx','sy']                     # Point events
point_events =  [events.Tap, events.DoubleTap]
for event in point_events:
    p.js_on_event(event,display_event(div, attributes=point_attributes))

output_file("js_events.html", title="JS Events Example")
show(layout)
```

My environment that produces this behavior:
OSX 10.12
python 3.6.1
bokeh 0.12.5, 0.12.6, 0.12.7
chrome 60.0.3112.101, safari 10.0, firefox 55.0.3

**Comment by bryevdv** [comment]
Marking `discussion` for now we will take a closer look after the release.

**Comment by kdesimone** [comment]
This is due to hammer.js hardsetting various timing/distance parameters, I think. 

https://github.com/hammerjs/hammer.js/blob/a28c530297f6e66785476013a6c9162305a2ce42/src/touchactionjs/touchaction-constructor.js#L97

**Comment by bryevdv** [comment]
There are a couple of options: 

* Has hammer already changed/fixed/updated this? If so, we can bump the version that Bokeh uses. That's quick and easy to try.

* We could try to submit a PR upstream

* We could for into the Bokeh GH org and build from a patched version.

@kdesimone do you know (if not can you try to check) whether the newest version of Hammer still has the same hard coded value?

**Comment by kdesimone** [comment]
Looks like the current version has the same hard coded values. For instance, [Tap](https://github.com/hammerjs/hammer.js/blob/master/hammer.js#L1343) and [Press](https://github.com/hammerjs/hammer.js/blob/master/hammer.js#L1430).

For my own purposes, I modified the bokehjs/node_modules/hammer/hammer.js to have hardcoded values that suit my application needs, and I rebuild bokeh. This has seemed to get me the behavior I want, although perhaps I broke some other functionality that I've not discovered yet.

This approach will get me by for a while, but is probably prone to missteps. @bryevdv  — is there any other workflow you'd suggest?

**Comment by bryevdv** [comment]
@kdesimone I think it's fine if it works for you I just expect patching a dependency and rebuilding BokehJS is probably more than most users will want to do. :) So I'd like to find a solution works for everyone built into the core library. Would you mind opening and issue on the Hammer GH tracker to discuss this (cc me)? It would be good to know if it could be changed or made possibly made configurable. They might also be able to comment on why the value is what it is, or if there are any known or expected bad outcomes of changing it. If they seem amenable to making a change that's preferable. If not, we can consider making a fork.

**Comment by bryevdv** [comment]
also, thanks for looking into this!

**Comment by kdesimone** [comment]
https://github.com/hammerjs/hammer.js/issues/1139

**Comment by bryevdv** [comment]
Brilliant, thanks. Hopefully we hear back something good soon, if not we can look at forking.

**Comment by kdesimone** [comment]
OK great sounds. Thanks for your attention on this.

**Comment by kdesimone** [comment]
I've been perusing the hammer.js GH issue tracker. It doesn't seem like anyone is actively maintaining it.  Last closed issue I could spot from an admin was October 2016.

**Comment by bryevdv** [comment]
@kdesimone that's unfortunate. We can look at making a fork into the Bokeh org, and testing the change out more throughly. I'd like @mattpap to help, he's out for a few more weeks, so it will be that long at least, just to set expectations.

**Comment by kdesimone** [comment]
thanks @bryevdv, that timeline sounds fine to me.

**Comment by kdesimone** [comment]
Hey @bryevdv bumping this just since I just updated my bokeh version but can't find the hammerjs files that I used to edit to get the low latency behavior I wanted.

Any update here?
