### ISSUE TITLE
RangeSlider css_classes not being updated anymore

### ISSUE THREAD

**Issue by andresmrm** [bokeh/bokeh#6841]
It seems in 0.12.7 the `css_classes` attribute of the RangeSlider is not being updated anymore by the callbacks. It was working in 0.12.6.
In the example below, both the text input and the slider starts with the `initial` class as expected. When the slider changes, both should gain the `sent-later` class, but only the text input is gaining it...

```
from bokeh.io import curdoc
from bokeh.models import TextInput, RangeSlider
from bokeh.layouts import widgetbox
from bokeh.layouts import column
from bokeh.models import Div

div1 = Div(text="""
        <style>
        .sent-later {
            border-radius: 0.5em;
            padding: 1em;
            border: 3px solid #2397D8;
        }
        </style>
""")


def on_slider_change(attr, old, new):
    slider.css_classes.append('sent-later')
    text.css_classes.append('sent-later')
    print(slider.css_classes)
    print(text.css_classes)


text = TextInput(
        value=str(2),
        title='Population Beta:')

slider = RangeSlider(
        start=0,
        end=10,
        value=(0, 2),
        step=1,
        title='Population Beta')

slider.css_classes = []
slider.css_classes.append('initial')
text.css_classes = []
text.css_classes.append('initial')

slider.on_change('value', on_slider_change)

curdoc().add_root(column(div1, widgetbox(text, slider)))

```

**Comment by bryevdv** [comment]
@andresmrm The entire slider widget implementation was replace so that we could jettison jquery entirely. Thanks for your patience. 

@mattpap I suspect it's this:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/abstract_slider.coffee#L24-L26

Looks like `render` (whose `super` is what calls `_render_classes`) will only ever be called once.

**Comment by bryevdv** [comment]
@mattpap actually after some more investigation, the updated value for `css_classes` is never different as far as I can tell. It's either not getting sent at all, or getting ignored/dropped on the floor for some reason on the BokehJS side

**Comment by bryevdv** [comment]
Yah, if these are added to the example code:
```

slider.js_on_change('css_classes', CustomJS(code='console.log("SLIDER")'))
text.js_on_change('css_classes', CustomJS(code='console.log("TEXT")'))
```
no messages are ever shown.

**Comment by bryevdv** [comment]
FYI I was trying this change to BokehJS:
```
❯ git diff
diff --git a/bokehjs/src/coffee/models/widgets/abstract_slider.coffee b/bokehjs/src/coffee/models/widgets/abstract_slider.coffee
index 3f5f3e550..9cca899d1 100644
--- a/bokehjs/src/coffee/models/widgets/abstract_slider.coffee
+++ b/bokehjs/src/coffee/models/widgets/abstract_slider.coffee
@@ -25,6 +25,9 @@ export class AbstractSliderView extends WidgetView
       # XXX: temporary workaround for _render_css()
       super()

+    debugger
+    @_render_classes()
+
     if @model.callback?
       callback = () => @model.callback.execute(@model)
```
If I also make this change to the example code:
```
    slider.css_classes = ['sent-later'] #.append('sent-later')
    text.css_classes = ['sent-later'] #append('sent-later')
```
Then the CSS updates as expected. So one thing seems to be an issue with change detection on `.append`

**Comment by bryevdv** [comment]
Without the code change above the text css updates but the slider does not. @mattpap do you consider the extra call to `@_render_classes()` to be acceptable? If so I will make a PR.

I'll have to look into the `.append` thing

**Comment by bryevdv** [comment]
OH, I am almost certain it does not work because it is `Seq` now, instead of `List`. Was it `List` previously? perhaps we can make it `List` with an `.accepts` to convert tuples?

**Comment by bryevdv** [comment]
cc @mattpap for thoughts

**Comment by bryevdv** [comment]
The route suggested above works,I will create a PR
