### ISSUE TITLE
Bug: bokeh.io.push_notebook is broken

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6844]
bokeh.io.push_notebook is broken in the 0.12.7 release because the comms_handle isn't returned from bokeh.io._show_with_state.

Example:
jupyter notebook examples/howto/notebook_comms/basic_usage.ipynb

Caused by: https://github.com/bokeh/bokeh/pull/6799/files#diff-ab5e8987987503b1248b3f5c707e056dL318

Bokeh 0.12.7

ping @bryevdv

**Comment by bryevdv** [comment]
Oh I see, @rs2 mentioned this on bitter but I understood to mean the `push_notebook` was not returning which is expected. I also tested the notebooks but not well enough. What is working is the handle for "last shown". For an immediate workaround, this could be accessed right after `show`:

```
state.last_comms_handle 
```
