### ISSUE TITLE
Categories on yaxis with hbar fails to set initial ranges

### ISSUE THREAD

**Issue by DuCorey** [bokeh/bokeh#6846]
I'm working with the new nested categorical range introduced in 0.12.7. I'm trying to emulate the behavior of nested categories but on the yaxis, as shown to work on the xaxis. Currently when running my code I'm getting a warning stating the axis could not be rendered and something that vaguely looks like a plot appears.

Is the nested category reserved only for the x_axis or is this a bug? 

#### Complete, minimal, self-contained example code that reproduces the issue

Here's a slightly modified code taken from the fruits example [here](https://bokeh.pydata.org/en/0.12.7/docs/user_guide/categorical.html#grouped) .
```
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, FactorRange
from bokeh.plotting import figure

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ['2015', '2016', '2017']

data = {'fruits' : fruits,
        '2015'   : [2, 1, 4, 3, 2, 4],
        '2016'   : [5, 3, 3, 2, 4, 6],
        '2017'   : [3, 2, 4, 4, 5, 3]}

# this creates [ ("Apples", "2015"), ("Apples", "2016"), ("Apples", "2017"), ("Pears", "2015), ... ]
x = [ (fruit, year) for fruit in fruits for year in years ]
counts = sum(zip(data['2015'], data['2016'], data['2017']), ()) # like an hstack

source = ColumnDataSource(data=dict(x=x, counts=counts))

p = figure(y_range=FactorRange(*x), plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

p.hbar(y='x', right='counts', height=0.9, source=source)

p.x_range.start = 0
p.y_range.range_padding = 0.1
p.ygrid.grid_line_color = None

show(p)

```

#### Stack traceback and/or browser JavaScript console output
```
[bokeh] could not set initial ranges
r.PlotCanvasView.e.set_initial_range @ bokeh-0.12.7.min.js:30
```

#### Screenshot
![bokeh_plot 55](https://user-images.githubusercontent.com/27960786/29896290-761cb53c-8daa-11e7-8160-fa9f68e1202b.png)

**Comment by mattpap** [comment]
Setting `p.x_range.end` (e.g. to 6) fixes the problem. Without its value is `NaN` and thus can't set initial ranges.

**Comment by bryevdv** [comment]
It should definitely work on the y-axis though it occurs to me I neglected to actually add any examples or docs that do that, I think. Offhand I think this points to HBar (and possibly VBar) not reporting their data bounds correctly, at least not when there are categoricals involved.

**Comment by DuCorey** [comment]
Good news it would seem that #6883 also fixed this issue. Closing this issue.

**Comment by bryevdv** [comment]
Always a pleasant surprise, thanks for the update @DuCorey
