### ISSUE TITLE
Extend BoxZoomTool and PanTool to trigger Python on_change events

### ISSUE THREAD

**Issue by rmchurch** [bokeh/bokeh#6849]
I implemented a custom extension to BoxZoomTool and PanTool to determine when a zoom or pan is complete, to allow triggering Python callbacks. This simplifies the current workflow of watching the x_range and y_range changes, and seems more intuitive (do this when the zoom or pan ends or starts). I realized it would be a simple addition to the codebase, but wanted to run it past devs if a PR would be accepted.

Basic idea is to add a Boolean "zoom_end" and "pan_end" property to the coffee script BoxZoomTool and PanTool class definitions respectively, then flip these at the end of the _pan_end call (i.e. ```@model.zoom_end = !@model.zoom_end```). Then you could do:
```
zoomtool = BoxZoomTool()
pantool = PanTool()
def zoom_callback(attr,old,new):
  #do something Pythonic
zoomtool.on_change('zoom_end',zoom_callback)
def pan_callback(attr,old,new):
  #do something Pythonic
pantool.on_change('pan_end',zoom_callback)
f = figure(tools=[zoomtool,pantool])
```

**Comment by bryevdv** [comment]
Hi we  definitely always appreciate contributions, however in this particular case, the desired functionality already exists with `bokeh.events`:

https://github.com/bokeh/bokeh/blob/master/examples/howto/events_app.py#L137-L140
