### ISSUE TITLE
Log-axis label layout issue

### ISSUE THREAD

**Issue by davidgardenier** [bokeh/bokeh#6850]
Bokeh 0.12.7 seems to introduce a layout error when adding an title to a log-axis. The axis-title is suddenly shifted upwards and cut off.

Using the log-axis example as basis and adding an axis-title seems to replicate the problem:

**MWE**
```
import numpy as np

from bokeh.plotting import figure, show, output_file

x = np.linspace(0.1, 5, 100)

p = figure(title="log axis example", y_axis_type="log",
           y_range=(0.001, 10**22))

p.line(x, np.sqrt(x), legend="y=sqrt(x)",
       line_color="tomato", line_dash="dotdash")

p.line(x, x, legend="y=x")
p.circle(x, x, legend="y=x")

p.line(x, x**2, legend="y=x**2")
p.circle(x, x**2, legend="y=x**2",
         fill_color=None, line_color="olivedrab")

p.line(x, 10**x, legend="y=10^x",
       line_color="gold", line_width=2)

p.line(x, x**x, legend="y=x^x",
       line_dash="dotted", line_color="indigo", line_width=2)

p.line(x, 10**(x**2), legend="y=10^(x^2)",
       line_color="coral", line_dash="dashed", line_width=2)

p.legend.location = "top_left"

p.yaxis.axis_label = 'New ylabel'  # Here is the problem

output_file("test.html", title="log plot example")

show(p)  # open a browser
```

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/14091346/29929346-8dc0c2f2-8e6b-11e7-826d-18194e41f988.png)

Let me know if additional information is needed

**Comment by mattpap** [comment]
This affects both horizontal and vertical log axes. Labels position isn't fixed and seem to depend on position of ticks. This makes me think that this may not be a regression, but a design issue revealed by layout fixes.

**Comment by mattpap** [comment]
So this is by design and an effect of using data space coordinates for laying out axis label. In case of log axis, its label is correctly positioned in the middle of the panel, just in log space, thus deviation to the right or top.

**Comment by mattpap** [comment]
This is also a nice example of bad code reuse. The reason for this bug is reuse a function responsible for painting tick labels, to paint axis label. This works fine as long as mapping from data space to screen space is linear.

**Comment by bryevdv** [comment]
I"m sure this was introduced when I tried to tame the tangled nightmare that is `Axis.coffee`
