### ISSUE TITLE
Plots which contain glyph's with infinite bounds fail to set initial ranges when match_aspect is set to True

### ISSUE THREAD

**Issue by DuCorey** [bokeh/bokeh#6851]
From my understanding, some glyphs can have infinite bounds when they are added to a plot without any initial data, but the plot still has a well defined glyph. 

In the current implementation of match_aspect, calculations will be done on these +- Infinity values and return NaNs which then cause the failure to set the initial ranges.

I'll be pushing a PR, by the end of this week to rectify this issue. My current idea is to simply skip calculations on those infinity values.

**Comment by bryevdv** [comment]
I think the terminology is a bit different than how I would describe, i.e. I think if there are no glyphs with no bounds then the bounds are simply undefined, tho we have historically tried to just set an arbitrary default bound e.g. (0,1) in those cases.

**Comment by DuCorey** [comment]
Looking at the JS, when I have a glyph with no bounds and a glyph with bounds. The value for bounds is +- infinity for the min and max for x and y. Bokeh have no issue rendering these bounds. The issue is that my code operates on those infinity values and returns a NaN value for the new calculated bounds. Bokeh can then no longer render the bounds.

My current idea is to simply check if any value in bounds is infinite and will not try and fix the aspect ratio on it.

**Comment by bryevdv** [comment]
OK, but worth mentioning that default `inf` state of "glyph bounds" is really an internal implementation detail. If the glyph does not report any bounds then the `DataRange` will interpret `inf`s as "no bounds could be set" and they apply the arbitrary default. We just need to do something similar to hand that case explicitly when `match_aspect` is true (exactly as you are suggesting)

**Comment by DuCorey** [comment]
Is there any internal utility function for checking if bounds are infinite? Currently I have 
```
for k, v of bounds
        if isFinite(v.maxX) and isFinite(v.minX) and isFinite(v.maxY) and isFinite(v.minY)
```

**Comment by bryevdv** [comment]
> Is there any internal utility function for checking if bounds are infinite? Currently I have

No, but you could add a Box method for `is_empty` here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/util/bbox.ts

**Comment by DuCorey** [comment]
@bryevdv There already exists `isEmpty `function in [core/util/object.ts](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/util/object.ts) which checks the size of objects. Although right now it is imported in the `plot_canvas.coffee` it is unused. I wouldn't want the new function to lead to confusion down the line with them having names too similar.

How about `is_rect_empty`?

**Comment by bryevdv** [comment]
>  Although right now isEmpty is imported in the plot_canvas.coffee it is unused.

FYI I'm generally +1 on ongoing code gardening, if you want to remove the unused import in this PR

Regarding the method, I'd actually prefer a property `empty`:

```
get empty(): bool { return .... }  # not sure if correct type is bool or boolean...
```

so that `if box.empty {...}` works

**Comment by mattpap** [comment]
`boolean`. Also, it would prefer it to be named `is_empty`.

**Comment by bryevdv** [comment]
@DuCorey let's go with `is_empty` I think context will prevent any confusion.
