### ISSUE TITLE
HoverTool not rendering on HBar glyphs in 0.12.7

### ISSUE THREAD

**Issue by jrwalk** [bokeh/bokeh#6852]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

python 3.5.2 (also tested in 3.6.2 with same result)
bokeh 0.12.7
OSX 10.11.4
Chrome 60.0.3112.113

#### Description of expected behavior and the observed behavior

In a figure with `HBar` glyphs and a `HoverTool` specified, the Hover tooltips are not rendering in bokeh 0.12.7.  Confirmed the same code running in 0.12.6 renders the `HoverTool` as expected.  Prior code displaying `HoverTool`s on `VBar` glyphs still works under 0.12.7.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.io import curdoc
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, Range1d, HoverTool

source = ColumnDataSource(data={'x1': ['a','b'], 'x2': [1,2]})
p = figure(tools="hover",y_range=["a","b"])
p.x_range = Range1d(0,3)
p.hbar(y="x1", right="x2", source=source, height=0.9)
p.select(HoverTool).tooltips = [("x1","@x1"), ("x2","@x2")]

curdoc().add_root(p)
```

#### Stack traceback and/or browser JavaScript console output

no errors generated.

**Comment by mattpap** [comment]
Looks like hit testing is broken. This may be connected to issue #6846.

**Comment by mattpap** [comment]
@jrwalk, please provide a complete example next time (with imports). This reduces time needed to reproduce an issue.

**Comment by bryevdv** [comment]
There was a mailing list or SO note above `vline` an `hline` hit testing working. Pretty sure it's just not implemented but should be trivial to add. Would be good to try and get that working at the same time this is fixed.

**Comment by jrwalk** [comment]
@mattpap sorry about that!  Yes I've noticed the issue in #6846 as well.

**Comment by bryevdv** [comment]
will have a PR shortly
