### ISSUE TITLE
DateFormatter not working in Tables

### ISSUE THREAD

**Issue by ongietorri** [bokeh/bokeh#6859]
Hi,

I tried using the DateFormatter but it does not work anymore in the last version (0.12.7).

I think it's a regression as this works in 0.12.6.

Minimal example to test with: http://bokeh.pydata.org/en/latest/docs/user_guide/examples/interaction_data_table.html

You can see in the example that the dates are not correctly formatted.

Switching back to 0.12.6 and running the exact same example, the dates are correctly displayed.

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by bryevdv** [comment]
@mattpap this was broken in your PR to remove JQuery, there were lines like
```
date = $.datepicker.formatDate(@getFormat(), new Date(value))
``` 

commented out but not replaced. Looking into alternatives.

**Comment by mattpap** [comment]
@bryevdv, just use `tz` as everything else, though format may need updating.

**Comment by mattpap** [comment]
`DateEditor` also wasn't finished, but that's a bit more work to get pikaday working in this setup.

**Comment by bryevdv** [comment]
I am looking at using moment, pikaday works well with it and maybe we can use it with moment-timezone to replace tz

**Comment by mattpap** [comment]
`moment` is huge (~150 kB), that's why it's excluded from pikaday.

**Comment by bryevdv** [comment]
? 

<img width="377" alt="screen shot 2017-09-04 at 15 42 22" src="https://user-images.githubusercontent.com/1078448/30038198-a9a0cbe2-9187-11e7-93e3-196dd78b3a8c.png">

**Comment by bryevdv** [comment]
Tho, I can't get it to include... I added to `package.json` and then used `import` is there something else? Supposedly newest versions include their own typings (no need for `@types/moment`) what am I missing?

**Comment by mattpap** [comment]
My bad, `moment.min.js` is 51 kB, which is still a lot (e.g. jquery worth). btw. The measure we use is minified and non-gzipped.

**Comment by bryevdv** [comment]
At this point I'd just like to get it working for my own edification, can you tell me what I am missing?

**Comment by mattpap** [comment]
I need to see what you actually did (a PR would be useful), but I suspect there may be something wrong with bundling.

**Comment by mattpap** [comment]
@bryevdv, you have to remove `moment` from widget bundle exclusion list (https://github.com/bokeh/bokeh/blob/master/bokehjs/gulp/tasks/scripts.ts#L101). I'm not sure right now, but I suspect that moment (and pikaday) may be include twice (once in wdigets and tables) if used in tables.

**Comment by bryevdv** [comment]
OK will just try to get things working with `tz`
