### ISSUE TITLE
Slider keyboard arrows no longer work 0.12.7

### ISSUE THREAD

**Issue by rmchurch** [bokeh/bokeh#6862]
The Slider in v0.12.7 no longer responds to keyboard arrows. Confirmed with 0.12.6 it was working.
System: Mac OSX, El Capitan 10.11.6, Chrome 60.0 64-bit

**Comment by bryevdv** [comment]
The entire slider implementation was changed to a different underlying slider library so that the last remnant of JQ could be jettisoned. Will have to investigate whether its possible to add this capability back or not. 

cc @mattpap

**Comment by mattpap** [comment]
That was in incidental feature. It shouldn't be a big task to implement this in new sliders.

**Comment by Pierretherenard** [comment]
An issue lately: For example if I have 100 numbers on a slider it seems to be possible to see them all one step at a time. If you have 1000 numbers, good luck to have the number 2 and plenty of other. I have a slider with ~2000 elements... The slider fails to show 6 to 10 on every 10 elements, having the keyboard will may be remove the issue to not be able to see all the elements.

**Comment by Pierretherenard** [comment]
slider = Slider(start=1, end=1000, value=1000, step=1, title="SLIDER")
        wdgsld = WidgetBox(slider)

**Comment by bryevdv** [comment]
So unfortunately on OSX at least, the merged PR works in Chrome, but not in Safari

**Comment by bryevdv** [comment]
It doesn't work in safari because *amazingly*, Safari ignores `tabindex` unless a user explicitly turns it on in options:

https://stackoverflow.com/a/1914496/3406693

Closing as `upstream`
