### ISSUE TITLE
DataTable autoEdit expose

### ISSUE THREAD

**Issue by rmchurch** [bokeh/bokeh#6864]
Would be nice to expose autoEdit option of SlickGrid for DataTable (changes so a single-click instead of double begins editing cell). I wrote custom extension below, may think of giving as optional parameter though.

```
import * as p from "core/properties"
import {DataTable, DataTableView} from "models/widgets/tables/data_table"

export class customDataTableView extends DataTableView

	render: () ->
		super()

		@grid.setOptions({autoEdit:@model.autoEdit})

export class customDataTable extends DataTable
	default_view: customDataTableView
	type: 'customDataTable'

	@define { autoEdit: [p.Bool,false] }
```

**Comment by bryevdv** [comment]
@rmchurch If you submit a PR to add this to the built-in table with `autoEdit` changed to `auto_edit` to match the property naming convention, I will be happy to merge it. You will probably be able to get to it much sooner than anyone else (some folks are out the entire next month and others are switching projects)
