### ISSUE TITLE
rect shape gets out of figure when panned or zoomed with WebGL

### ISSUE THREAD

**Issue by vtphan** [bokeh/bokeh#6867]
Anaconda, bokeh 0.12.7
rect shape gets out of figure when panned or zoomed.  See figure:

<img width="615" alt="screen shot 2017-09-01 at 8 30 12 pm" src="https://user-images.githubusercontent.com/937726/29991858-992b6612-8f54-11e7-81ba-0ea0aa760da6.png">

	fig = figure(
		plot_width = DIM[2,0][0],
		plot_height= DIM[2,0][1],
		x_range = main_fig.x_range,
		y_range = (-3.5,2),
		tools=['reset,tap,xwheel_zoom',a_hover],
		toolbar_location=None,
		active_scroll="xwheel_zoom",
		output_backend="webgl",
		logo=None,
	)
	fig.xgrid.grid_line_color = None
	fig.xaxis.axis_label_text_font_style = "normal"
	fig.xaxis.axis_label_text_font_size = "14pt"
	fig.xaxis[0].formatter = NumeralTickFormatter(format="0")
	fig.ygrid.grid_line_color = None
	fig.yaxis.visible = False

	fig.rect(
		x = 'x',
		y = 'y',
		width = 'width',
		height = 'height',
		color = 'color',
		fill_alpha = 'fill_alpha',
		line_alpha = 'line_alpha',
		line_width = 'line_width',
		nonselection_color = 'color',
		width_units = 'data',
		height_units = 'data',
		name = 'gene_product',
		source = source
	)

**Comment by bryevdv** [comment]
This is a webgl specific problem

**Comment by vtphan** [comment]
Wow.  Not setting the backend_parameter to webgl fixes it.  Thanks.

**Comment by mattpap** [comment]
Unfortunately we have limited capabilities to test the webgl implementation, which means it slowly deviates from the default rendering algorithm.

**Comment by bryevdv** [comment]
My intent is to redo GL support from the ground up, probably based on ReGL, but that is a large undertaking, and certainly will have to happen post-1.0

**Comment by David-Herman** [comment]
I wanted to leave a note that I observe the same behavior when using the graph network plotting capability in Bokeh. Circles properly respect the boundary and edges cross over the axes.

![image](https://user-images.githubusercontent.com/22305345/33098474-8c4bc448-cedb-11e7-8314-cf2df7be9954.png)

**Comment by bryevdv** [comment]
I hope some day to be able to re-do the entire webGL backend using something like ReGL but that's a substantial project, outside my current experience, an there are many other priorities ahead of it. So it probably won't be any time soon unless someone else decides to take it up first.
