### ISSUE TITLE
Unable to render <, >, & in DataTable

### ISSUE THREAD

**Issue by tkchris93** [bokeh/bokeh#6873]
I am using Bokeh 0.12.7, python 2.7.13, macOS, and Chrome.

I am unable to render the less than, greater than, and ampersand characters (I assume there are others as well) in a DataTable. The DataTable instead gives the HTML representation (&lt; &gt; &amp;) .

```
from bokeh.io import output_file, show
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn
output_file('table.html')

source = ColumnDataSource(data=dict(chars=['>', '<', '&']))

columns = [TableColumn(field='chars', title='Characters')]
table = DataTable(source=source, columns=columns)
show(table)
``` 
<img width="146" alt="screen shot 2017-09-02 at 11 59 50 am" src="https://user-images.githubusercontent.com/10438787/29997666-52d965ce-8fd6-11e7-89f3-0a337c7aa5c5.png">

**Comment by mattpap** [comment]
Special characters are transformed twice in `StringFormatter`.
