### ISSUE TITLE
Example Code for Graph Layout Providers in documentation not working

### ISSUE THREAD

**Issue by busino** [bokeh/bokeh#6875]
Hi,

Thanks for the _graph_ module... that's great.

But If I run the example-code from http://bokeh.pydata.org/en/latest/docs/user_guide/graph.html#layout-providers
I get two errors.

### IO
`show('graph.html')` have to replaced with ``save('graph.html')``
Otherwise there is an error with:

```
lib\json\encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

TypeError: keys must be a string
```

### Fill color
Other error with _fill_color_ of the _Oval_
Because the `fill_color` cannot be found in data-source.
When I remove the _fill_color_ argument from _Oval_ everything works fine.

```
graph.node_renderer.glyph = Oval(height=0.1, width=0.2, fill_color="fill_color")
```
to
```
graph.node_renderer.glyph = Oval(height=0.1, width=0.2)
```

Bokeh Version: 0.12.7
Platform: Windows 10 x64
Python: 3.6

Have a nice week-end
Raphael

**Comment by bryevdv** [comment]
@busino the example code you link was literally executed by the docs build system to generate the plot immediately below. I also just ran the code myself without any issue. I think something odd is going on with your system specifically, but the best place to hash that out is the mailing list:

https://groups.google.com/a/anaconda.com/forum/#!forum/bokeh

**Comment by busino** [comment]
@bryevdv 

Tested with new environment and still see the error. Probably a platform issue.
Which setup did you run the code?

My Setup:
environment.yml
```
name: bokeh_c_env_py36
dependencies:
- python=3.6
- ipython
- bokeh=0.12.7
```

conda config
```
channels:
  - defaults
```

Reproduce:
```
cmd> conda env create -f environment.yml
cmd>activate bokeh_c_env_py36
cmd> ipython
In [1]: import bokeh
In [2]: bokeh.__version__
Out[2]: '0.12.7'
In [3]: run graph.py
E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name: fill_color [renderer: GlyphRenderer(id='8eb7dd2f-3eb9-463f-bf3b-0093755317a0', ...)]
```

Can you check with the same setup?

Raphael
