### ISSUE TITLE
Remove all server examples that use session.loop_until_closed

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6887]
Another user having issues using `bokeh.client` to run apps "outside" a Bokeh server. Text of mailing list response:

> There are some current issues with using bokeh.client (i.e. push_session and loop_until_closed) with some features (e.g. events and streaming)
>
> However, even without these current bugs, I cannot stress enough (and evidently have not been able to stress enough, despite trying to) that this usage of bokeh.client is absolutely, 100% NOT ADVISED. Using bokeh.client in this way (with the app running "outside" the server) has inherent drawbacks that will never be overcome (described in the user's guide).
>
> Whether you are running "bokeh serve app.py" or using a FunctionHander and embedding a Bokeh server programmatically in a script or a notebook, it is always, without fail, better to run the app IN a Bokeh server.
>
> The *only* use I would ever advise using bokeh.client for is to pull specific session for an app running normally a Bokeh server, for the purpose of "tweaking it". This might be useful e.g. for serving customized versions of an app to different users looking at a Flask or Django page. 
>
> FYI I am basically almost to the point where I am going to remove every example in the repo that uses "session.loop_until_closed" under the premise that ever demonstrating it in the first place was a great mistake. 

I'd like to discuss that last point. Specifically, I'd like to:

* completely remove `examples/plotting/server` and `examples/model/server`
* demonstrate a good "tweak a session" use of `bokeh.client`
* make `session.loop_until_closed` print a loud warning that it is not advised for any real (non-toy) usage

cc @bokeh/dev

**Comment by bryevdv** [comment]
As a trivial example, here is a trivial "tweaking a session" usage that I consider reasonable for `bokeh.client`
```
from flask import Flask, render_template

from bokeh.client import pull_session
from bokeh.embed import server_session

app = Flask(__name__)

@app.route('/', methods=['GET'])
def bkapp_page():
    session = pull_session(url="http://localhost:5006/sliders")
    session.document.roots[0].children[1].title.text = "Special Sliders A Specific User!"
    session.push()
    script = server_session(None, session.id, url='http://localhost:5006/sliders')
    return render_template("embed.html", script=script, template="Flask")

if __name__ == '__main__':
    app.run(port=8080)
```
Here the app is running in the server normally, i.e. run with `bokeh serve sliders.py` (it could also be embedded) but we can pull one session, and customize it, and then serve that one specific session to one specific user. That is the *only* usage of `bokeh.client` I deem acceptable (and even many times that could be avoided with HTML request args)

**Comment by bryevdv** [comment]
I added a enormous warning for `0.126.8`:

```
❯ python animated.py

animating... press ctrl-C to stop
/Users/bryan/work/bokeh/bokeh/client/session.py:353: UserWarning:

!!!! PLEASE NOTE !!!!

The use of `session.loop_until_closed` and `push_session` to run Bokeh
application code outside a Bokeh server is HIGHLY discouraged for any real use.

Running application code outside a Bokeh server with bokeh.client in this way
has (and always will have) several intrinsic drawbacks:

* Fast binary array transport is NOT available! Base64 fallback is much slower
* All network traffic is DOUBLED due to extra hop between client and server
* Server *and* client process must be running at ALL TIMES for callbacks to work
* App code run outside the Bokeh server is NOT SCALABLE behind a load balancer

The bokeh.client API is recommended to use ONLY for testing, or for customizing
individual sessions running in a full Bokeh server, before passing on to viewers.

For information about different ways of running apps in a Bokeh server, see:

    http://bokeh.pydata.org/en/latest/docs/user_guide/server.html

  warnings.warn(BOKEH_CLIENT_APP_WARNING)
```

and plan to remove/convert all the `*/server` examples  for `0.12.9`

**Comment by canavandl** [comment]
I agree w/ removing the usage of client sessions in the examples. I think the examples tests should work without the client session stuff (which may have been an original motivating factor). Do you propose encouraging users to use ``bokeh serve`` to run the server examples or adding some subprocess code to the ``__main__`` conditional so that it runs via ``python example.py``?

**Comment by axil** [comment]
There're a lot of references to 'widget.py' in the internet, it is also referenced in the https://github.com/bokeh/bokeh/tree/master/examples/embed page.  Is it possible to recover this example in a proper way (without push_session and loop_until_closed functions)?
