### ISSUE TITLE
CustomJS for Hover no longer working - bokeh 0.12.7

### ISSUE THREAD

**Issue by blanchardmatt** [bokeh/bokeh#6891]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 0.12.7

#### Description of expected behavior and the observed behavior
The official example of CustomJS for Hover is failing with bokeh 0.12.7.
in the console, there is an error: Cannot read property 'indices' of undefined

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource, HoverTool, CustomJS

output_file("hover_callback.html")

# define some points and a little graph between them
x = [2, 3, 5, 6, 8, 7]
y = [6, 4, 3, 8, 7, 5]
links = {
    0: [1, 2],
    1: [0, 3, 4],
    2: [0, 5],
    3: [1, 4],
    4: [1, 3],
    5: [2, 3, 4]
}

p = figure(plot_width=400, plot_height=400, tools="", toolbar_location=None, title='Hover over points')

source = ColumnDataSource({'x0': [], 'y0': [], 'x1': [], 'y1': []})
sr = p.segment(x0='x0', y0='y0', x1='x1', y1='y1', color='olive', alpha=0.6, line_width=3, source=source, )
cr = p.circle(x, y, color='olive', size=30, alpha=0.4, hover_color='olive', hover_alpha=1.0)

# Add a hover tool, that sets the link data for a hovered circle
code = """
var links = %s;
var data = {'x0': [], 'y0': [], 'x1': [], 'y1': []};
var cdata = circle.data;
var indices = cb_data.index['1d'].indices;
for (i=0; i < indices.length; i++) {
    ind0 = indices[i]
    for (j=0; j < links[ind0].length; j++) {
        ind1 = links[ind0][j];
        data['x0'].push(cdata.x[ind0]);
        data['y0'].push(cdata.y[ind0]);
        data['x1'].push(cdata.x[ind1]);
        data['y1'].push(cdata.y[ind1]);
    }
}
segment.data = data;
""" % links

callback = CustomJS(args={'circle': cr.data_source, 'segment': sr.data_source}, code=code)
p.add_tools(HoverTool(tooltips=None, callback=callback, renderers=[cr]))

show(p)

```

#### Stack traceback and/or browser JavaScript console output
VM295:7 Uncaught TypeError: Cannot read property 'indices' of undefined
    at r.eval (eval at <anonymous> (bokeh-0.12.7.min.js:25), <anonymous>:7:34)
    at r.CustomJS.r.execute (bokeh-0.12.7.min.js:25)
    at e.r.HoverToolView.e._emit_callback (bokeh-0.12.7.min.js:35)
    at e.r.HoverToolView.e._inspect (bokeh-0.12.7.min.js:35)
    at e.r.HoverToolView.e._move (bokeh-0.12.7.min.js:35)
    at e.<anonymous> (bokeh-0.12.7.min.js:2)
    at t.emit (bokeh-0.12.7.min.js:2)
    at t.r.UIEvents.t.trigger (bokeh-0.12.7.min.js:2)
    at t.r.UIEvents.t._trigger (bokeh-0.12.7.min.js:2)
    at t.r.UIEvents.t._mouse_move (bokeh-0.12.7.min.js:3)

**Comment by bryevdv** [comment]
cc @clairetang6 @canavandl does anything here seem familiar or recently changed?

**Comment by bryevdv** [comment]
@canavandl I think maybe this change broke it:

https://github.com/bokeh/bokeh/blame/40f1d350b5ce19630ccb727ca6fe5989b600df96/bokehjs/src/coffee/models/renderers/glyph_renderer.coffee#L279

the proximate problem is that indices is `false` in some cases now. Tho this code also seems problematic in hover tool:

```
_emit_callback: (geometry) ->
    r = @computed_renderers[0]
    indices = @plot_view.renderer_views[r.id].hit_test(geometry)
```
the call back only ever grabs indices for the first of N renderers?

**Comment by bryevdv** [comment]
well actually it just always returns a bool:
```
return not indices.is_empty()
```
So I guess HoverTool needs to be updated but wasn't, will have to look into it

**Comment by bryevdv** [comment]
So,I think the old implementation was broken, and that example working was a coincidence. I'm not sure the example will be able to continue working without some modification, though.

**Comment by hafen** [comment]
I'm experiencing the same issue in 0.12.9. The `cb_data.index` is only ever `true` or `false`.

**Comment by bryevdv** [comment]
Changing the `indices` line in the callback fixes:
```
var indices = cb_data.renderer.data_source.inspected['1d'].indices;
```

I guess the question is whether `cb_data.index` should be fixed up somehow, or if this more explicit route is just preferable in any case. @hafen @clairetang6 any thoughts? To "fix" it I think `_emit_callaback` could set index using basically the line above instead of using the hit test result (which is not a bool for if there was  hit)

**Comment by bryevdv** [comment]
Here is a diff that fixes the example as-is:
```
diff --git a/bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee b/bokehjs/src/coffee/models/tools/inspectors/
index 1c993efbc..7dcf5128a 100644
--- a/bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
+++ b/bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
@@ -298,27 +298,32 @@ export class HoverToolView extends InspectToolView
     return null

   _emit_callback: (geometry) ->
-    r = @computed_renderers[0]
-    indices = @plot_view.renderer_views[r.id].hit_test(geometry)
+    for r in  @computed_renderers

-    canvas = @plot_model.canvas
-    frame = @plot_model.frame
+      did_hit = @plot_view.renderer_views[r.id].hit_test(geometry)
+      if not did_hit
+        continue

-    geometry['sx'] = canvas.vx_to_sx(geometry.vx)
-    geometry['sy'] = canvas.vy_to_sy(geometry.vy)
+      index = r.data_source.inspected

-    xscale = frame.xscales[r.x_range_name]
-    yscale = frame.yscales[r.y_range_name]
-    geometry['x'] = xscale.invert(geometry.vx)
-    geometry['y'] = yscale.invert(geometry.vy)
+      canvas = @plot_model.canvas
+      frame = @plot_model.frame

-    callback = @model.callback
-    [obj, data] = [callback, {index: indices, geometry: geometry, renderer: r}]
+      geometry['sx'] = canvas.vx_to_sx(geometry.vx)
+      geometry['sy'] = canvas.vy_to_sy(geometry.vy)

-    if isFunction(callback)
-      callback(obj, data)
-    else
-      callback.execute(obj, data)
+      xscale = frame.xscales[r.x_range_name]
+      yscale = frame.yscales[r.y_range_name]
+      geometry['x'] = xscale.invert(geometry.vx)
+      geometry['y'] = yscale.invert(geometry.vy)
+
+      callback = @model.callback
+      [obj, data] = [callback, {index: index, geometry: geometry, renderer: r}]
+
+      if isFunction(callback)
+        callback(obj, data)
+      else
+        callback.execute(obj, data)

     return
```

That said, I don't think it's a great example anymore now that graph and graph selection policies are merged. I would prefer to come up with a better hover callback example at the same time as fixing this, that does not "simulate" a graph.
