### ISSUE TITLE
bokeh-tables-0.12.6.min.js not found on the server

### ISSUE THREAD

**Issue by fedorov** [bokeh/bokeh#6894]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

**bokeh 0.12.6**, python 3.5.3, jupyter notebook, macOS, Chrome 60 (but I don't think this is relevant)

#### Description of expected behavior and the observed behavior

Failure to load, apparently due to missing file on server: https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.6.min.js is not found.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure 
from bokeh.io import output_notebook, show
output_notebook()
```

#### Stack traceback and/or browser JavaScript console output

![image](https://user-images.githubusercontent.com/313942/30122022-37180bb0-92fb-11e7-9aaf-c1fce44a5cd6.png)

**Comment by bryevdv** [comment]
That file is new with `0.12.7` It does not (will not ever) exists for any earlier versions. But more to the point, earlier version so Bokeh would never try to load that file on their own, they don't know anything about it (it didn't exist prior). You have some sort of problem in your installation or configuration.

**Comment by fedorov** [comment]
You are right, it was indeed a problem with my installation. I had 0.12.7 installed, and then did "pip install -I bokeh=0.12.6" to revert, and that's when I encountered the problem I mentioned above. After I completely uninstalled bokeh, and installed 0.12.6 from scratch, things started working again as before.
