### ISSUE TITLE
Bokeh DateRangeSlider returns tuple of integers instead of dates

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#6895]
In 0.12.7 the DateRangeSlider `.value` returns a tuple of integers. Additionally, in order to convert them back to dates you have to divide by 1000 (i.e. `datetime.fromtimestamp(the_tuple[0]/1000)`).

Expected behavior: Return a tuple of Date objects.

```
from datetime import datetime
from bokeh.models.widgets import DateRangeSlider
from bokeh.io import curdoc

def date_range_update(attrname, old, new):
    print('-- range values:', date_slider.value)
    # Works
    d1 = datetime.fromtimestamp(date_slider.value[0] / 1000) 
    # Does not Work, gives error
    d2 = datetime.fromtimestamp(date_slider.value[0])

date_slider = DateRangeSlider(value=(date_start,date_end), start=date_start, end=date_end)
date_slider.on_change('value', date_range_update)

curdoc().add_root(date_slider)

```

**Comment by ImHimanShoe** [comment]
after searching through all the date function I find the solution in the issues of Bokeh.
That divide by 1000 was tricky to catch, thanks!!

**Comment by bryevdv** [comment]
@ImHimanShoe FYI the PR linked above added convenience methods that will return datetime types
