### ISSUE TITLE
Suggestion to support PNG for compressing raster data

### ISSUE THREAD

**Issue by jlstevens** [bokeh/bokeh#6896]
This feature request follows a discussion I had with @bryevdv where we proposed that PNG data might be a much more space efficient way of storing raster data client-side.

This came to my attention when comparing this  holoviews example using [matplotlib](http://holoviews.org/gallery/demos/matplotlib/mandelbrot_section.html) which results in a notebook that is 1.9MB in size while the [bokeh version](http://holoviews.org/gallery/demos/bokeh/mandelbrot_section.html) was still 5.4MB in size  *after* having tried to aggressively bring down the size of the notebook.

In the Bokeh version, I cast the data from float64 to float32 and then downsampled the array by 4x along both directions for what should be a 32x overall reduction in the space required but this is still twice the size of the matplotlib version which uses the PNG format for each frame.

It might be nice to have a mechanism in Bokeh whereby images are stored (and transferred?) as PNG to make use of the lossless image compression offered by the format.

**Comment by bryevdv** [comment]
Would support a new glyph, e.g. `ImagePNG`

**Comment by bryevdv** [comment]
This seems unlikely to ever happen. Happy to re-open if someone wants to submit a PR.
