### ISSUE TITLE
DateRangeSlider mouseup callback_policy calling before mouseup

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#6897]
In 0.12.7, the DateRangeSlider `on_change` callback with `callback_policy="mouseup"` is called as the slider is moved instead of waiting until there is a mouse-up.

```
from bokeh.models.widgets import DateRangeSlider
from bokeh.io import curdoc

def date_range_update(attrname, old, new):
    print('-- In date_range_update() --', date_slider.callback_policy)

date_slider = DateRangeSlider(value=(date_start,date_end), start=date_start, end=date_end,callback_policy='mouseup')
date_slider.on_change('value', date_range_update)

curdoc().add_root(date_slider)
```

**Comment by bryevdv** [comment]
@hsparra the `callback_policy` does not apply to python callbacks, only the `CustomJS` ones set as the slider's `callback` property

**Comment by hsparra** [comment]
Is there any plan to make it so sliders can be set for python callbacks so they only perform the callback on mouse-up?

**Comment by bryevdv** [comment]
@hsparra Some investigation is required to see what might be possible, or what is missing in order to implement this feature.

**Comment by bryevdv** [comment]
callback policies are gone. However things work as intended with the new corresponding `value_throttled` property
