### ISSUE TITLE
Add pips to noUiSlider

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [bokeh/bokeh#6899]
As discussed in #6861, discussion about adding pips to the noUiSlider interface:

@bryevdv : a PR to add support for a "pips" dict to existing slider (just pass as-is to nouislider)

**Comment by Karel-van-de-Plassche** [comment]
So, would you mean just pass the whole dict to noUiSlider? That would mean the user would have to supply a dict with at least the 'mode' and 'density' to get nice formatting. Maybe split it up in a boolean flag 'show_pips' and a dict 'format_pips' with some sane defaults?

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by Karel-van-de-Plassche** [comment]
I have solved this by moving to the contribution-style ion.RangeSlider, so this can be closed. See https://github.com/Karel-van-de-Plassche/bokeh-ion-rangeslider.
