### ISSUE TITLE
Add range-snapping to noUiSlider

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [bokeh/bokeh#6900]
As discussed in #6861, a separate request to add range-snapping to noUiSlider.

@bryevdv: another PR to add range snapping

**Comment by Karel-van-de-Plassche** [comment]
I don't think this PR would make sense without manual range-setting, see #6901

**Comment by bryevdv** [comment]
cc @mattpap for discussion

**Comment by Karel-van-de-Plassche** [comment]
I have solved this by moving to the contribution-style ion.RangeSlider, so this can be closed. See https://github.com/Karel-van-de-Plassche/bokeh-ion-rangeslider.
