### ISSUE TITLE
Manual setting of range in noUiSlider

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [bokeh/bokeh#6901]
As discussed in #6861, a separate request to add setting the ranges manually to noUiSlider.

@bryevdv: last PR to add support for manual values (need some discussion of API, new model vs adding to existing)

**Comment by Karel-van-de-Plassche** [comment]
The API of noUiSlider needs the 'range' attribute to be a dict with at least 'min' and 'max', and then XX% for optional values. Current API reads the 'start' and 'end' model attributes to set this: {min: start, max: end}.

Option 1: The new 'range' attribute would overwrite this if it's set:
```coffeescript
range: {min: start, max: end}
```
to
```coffeescript
range: @model.range or {min: start, max: end}
```
Option 2: Keep the old start-end, and only set optional ranges with dict:
```coffeescript
range = {min: start, max: end}
Object.assign(range, @model.range);
range: range
```

**Comment by bryevdv** [comment]
@mattpap your input in the best approach here is welcome. I've mulled a few options over but I'm not super happy with anything that's come to mind.

**Comment by bryevdv** [comment]
Hi @Karel-van-de-Plassche I am going over old discussions. Is this (and the other two related issues) still something you are interested in? If not I think we can/should close these issues. If it is, now that you have already made several PRs I think just submitting a PR that can focus discussions around actual code is the best way to proceed.

**Comment by Karel-van-de-Plassche** [comment]
I have solved this by moving to the contribution-style ion.RangeSlider, so this can be closed. See https://github.com/Karel-van-de-Plassche/bokeh-ion-rangeslider.
