### ISSUE TITLE
multi_line and categorical axis

### ISSUE THREAD

**Issue by robin-vjc** [bokeh/bokeh#6907]
Hi all,

unless I am missing something, it looks like there might be some problem plotting `multi_lines` when an axis is categorical (**bokeh version: 0.12.7**).

Minimal setup to reproduce the problem in a Jupyter notebook:

```
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook()

factors = ["a", "b", "c"]
p = figure(plot_width=400, plot_height=400, y_range=factors)
p.multi_line(xs=[[1,2,3], [1,2,3]], ys=[["a","c","b"], ["b","a","c"]], line_width=2)
show(p)
```
Throws the following error:
```
Javascript error adding output!
TypeError: Cannot read property 'c' of undefined
See your browser Javascript console for more details.
```
While the following code, which is identical except for the fact that both axis are numerical, functions correctly:
```
p = figure(plot_width=400, plot_height=400)
p.multi_line(xs=[[1,2,3], [1,2,3]], ys=[[2,1,0], [3,2,2]], line_width=2)
show(p)
```

**Comment by bryevdv** [comment]
I'm not sure we will be able to do anything about this. There's a fundamental ambiguity and I don't see any way straightforward way that it could be resolved, if it can be at all. The only workarounds I can suggest at present are:

* use multiple `line` calls instead
* use numeric "synthetic" coordinates instead (may require experimentation if any range padding is used)

**Comment by robin-vjc** [comment]
Thanks - I am indeed currently using multiple `p.line` calls. 

I am not sure what the ambiguity is that you are referring to, but if you come up with some ways to fix it and indicate to me what would need to be done, I'd be happy to try to help with this.

Regards and thanks for your work.

**Comment by bryevdv** [comment]
@robin-vjc by ambiguity,I mean this:

When you have a sequence of "nested categories", say for grouped vbars, it looks like:

```
x = [ ["west", "sales"], ["west", marketing"], ["east", "sales"], ["east", marketing"]]
```
But that's exactly the same form as for multiline. I am not sure there is any way to reconcile or disambiguate this. The handling of the property values and columns is at a very low level so it's not something that could be handled at the level of `MultiLine` itself. Which doesn't mean impossible, but does mean risky and expensive and for a single corner case with workarounds, probably not something that can be prioritized any time soon.

**Comment by mahrz** [comment]
This is however breaking the use cases where the number of lines are not known and depend on the data source. For example, we have a data source where each line has a different data dependent color and the coordinates are categorical. This is currently not achievable with bokeh > 0.12.7, but was possible up to bokeh 0.12.6. Or is there another workaround? 

I do not quite understand what you meant by using numeric synthetic coordinates instead. Do you mean using a three times nested list for the coordinates of the multiline glyph?

**Comment by bryevdv** [comment]
> I do not quite understand what you meant by using numeric synthetic coordinates instead.

I mean that categories are mapped to numerical coordinates internally, and you could just pass those numbers in stead of the string factor names. Roughly speaking if you have categories ["a", "b", "c"] then those will map to (0.5, 1.5, 2.5), but things like range padding can affect the mapping, so some fine tuning may be required. 

But there are lots of ways that might also work. Another option is simply don't use real  factors coordinates or a real categorical axis at all. Instead use numeric coordinates, with a regular axis, and change how the axis displays tick values by making a [tick formatter](https://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#tick-label-formats). (i.e. to show different label names for specific tick locations). Or even simpler, using tick label overrides. This is probably what I'd actually suggest to try to start.  Here is a simple example:
```
from bokeh.io import output_file, show
from bokeh.models import FuncTickFormatter
from bokeh.plotting import figure

output_file("test.html")

p = figure(x_range=(0,4))
p.xaxis.ticker = [1,2,3]
p.xaxis.major_label_overrides = {1: "foo", 2: "bar", 3: "baz"}

p.multi_line(xs=[[1,2,3], [1, 1, 2, 3]], ys=[[2, 3, 2], [4, 5, 5, 4]])

show(p)
```

<img width="605" alt="screen shot 2017-10-27 at 10 34 39" src="https://user-images.githubusercontent.com/1078448/32112320-8c0ecf30-bb02-11e7-9f5b-089c6851b7a8.png">

As I said I simply don't know how this could be fixed and still maintain support for nested categories. Nested categories were a crucial feature addition (so to be explicit and unambiguous: nested category support is *more important* than multi-line on categorical ranges), so this will just have to be an odd corner case to work around, I am afraid.
