### ISSUE TITLE
Running output_notebook with hide_banner=True broken

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#6908]
Using latest master ``output_notebook`` is broken when using the ``hide_banner`` option, e.g. in the example below the plot does not display unless I set ``hide_banner=False``.

```python
from bokeh.io import output_notebook
from bokeh.plotting import figure, output_file, show

output_notebook(hide_banner=True)

p = figure(plot_width=400, plot_height=400)

p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

show(p)
```

The JS console reveals the following errors:

```
Bokeh: ERROR: autoload.js configured with elementid 'bdb33685-6dc0-4eb1-8acb-60291c9a5833' but no matching script tag was found. 
(unknown) Bokeh: ERROR: Unable to embed document because BokehJS library is missing
```

**Comment by bryevdv** [comment]
This should hopefully be a fairly simple fix. We are abusing the autoload template to show the banner div (it's usually for the display div). The real solution is to not re-use the autoload template or at least not re-use `elementid`, but there's probably something simpler in the immediate term.
