### ISSUE TITLE
The new feature Filter (CDSView) not behaving has expected.

### ISSUE THREAD

**Issue by afonit** [bokeh/bokeh#6910]
Moving this over from the mailing list to a github issue at Bryan's request.

Here is the mailing list post:
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/OFrEpYWsTvk

Background:
I am using some of the new features, and trying to combine http://bokeh.pydata.org/en/0.12.7/docs/user_guide/categorical.html#visual-dodge with boolean filters http://bokeh.pydata.org/en/0.12.7/docs/user_guide/data.html#booleanfilter
I am changing the visual dodge to have the data all in a column (like one would have to do with altair)
So I am creating a view for each of the three vbar data sets
but it is not working.

Here is the example:

```python
from bokeh.core.properties import value
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from bokeh.transform import dodge
from bokeh.models import ColumnDataSource, CDSView, BooleanFilter

output_notebook()

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ['2015', '2016', '2017']

data = {'fruits' :['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries',
                  'Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries',
                  'Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries'],
        'date': ['2015','2015','2015','2015','2015','2015',
                '2016','2016','2016','2016','2016','2016',
                '2017', '2017','2017','2017','2017','2017'],
        'nums': [2, 1, 4, 3, 2, 4,
                 5, 3, 3, 2, 4, 6,
                 3, 2, 4, 4, 5, 3]
       }

source = ColumnDataSource(data=data)

view2015 = CDSView(source=source, filters=[BooleanFilter([True if date == '2015' else False for date in source.data['date']])])
view2016 = CDSView(source=source, filters=[BooleanFilter([True if date == '2016' else False for date in source.data['date']])])
view2017 = CDSView(source=source, filters=[BooleanFilter([True if date == '2017' else False for date in source.data['date']])])

p = figure(x_range=fruits, y_range=(0, 10), plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

p.vbar(x=dodge('fruits', -0.25, range=p.x_range), top='nums', width=0.2, source=source, view=view2015,
       color="green", legend=value("2015"))

p.vbar(x=dodge('fruits', 0, range=p.x_range), top='nums', width=0.2, source=source, view=view2016,
       color="red", legend=value("2016"))

p.vbar(x=dodge('fruits', 0.25, range=p.x_range), top='nums', width=0.2, source=source, view=view2017,
       color="blue", legend=value("2017"))

p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"

show(p)
```
The above produces the following output:
![image](https://user-images.githubusercontent.com/1798497/30210297-0eb949f2-946a-11e7-81af-e4731ee7a818.png)

If one comments out the view from the second and takes out the whole third like this:
```python
p = figure(x_range=fruits, y_range=(0, 10), plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

p.vbar(x=dodge('fruits', -0.25, range=p.x_range), top='nums', width=0.2, source=source, view=view2015,
       color="#c9d9d3", legend=value("2015"))

p.vbar(x=dodge('fruits', 0, range=p.x_range), top='nums', width=0.2, source=source, #view=view2016,
       color="#718dbf", legend=value("2016"))

#p.vbar(x=dodge('fruits', 0.25, range=p.x_range), top='nums', width=0.2, source=source, view=view2017,
#       color="#e84d60", legend=value("2017"))
```

Then you get the below output:
![image](https://user-images.githubusercontent.com/1798497/30210340-44c9edc6-946a-11e7-99a8-e85bb2b36ab9.png)
Which makes the 2016 a mix of the other numbers - but the vbar is showing up (just for testing out scenarios).

Bryan in the mailing list noted this behavior:
"
If you move the 2016 values to the front, than that's the one that gets displayed. I have a quick hunch that things are only displaying if the first view filter value happens to be True.

If I change one of the vbars to circle, then that does show up in addition to the bars. So this seems like a bug with filters and repeated use of the same glyph, perhaps.
"

**Addendum**:
The reason for wanting the filters to work with data arranged in this way is I want to develop a more sophisticated plot where I am going to use some other columns to add another glyphs that will give information/context for the data.  Here is a concrete example that I already use:
![image](https://user-images.githubusercontent.com/1798497/30211526-5dabbfcc-946f-11e7-8e4d-8d2fa6446586.png)

But was trying to use some of the new features noted up top so I could collapse the pars into a pre/post for each period and also add in my circle glyphs to show the volume of data that each vbar has within the specified time period.

**Comment by clairetang6** [comment]
Fixed by PR 6967 above: 
![image](https://user-images.githubusercontent.com/4241244/31296041-ccd91ea8-aa95-11e7-9ede-760e5109e5df.png)
