### ISSUE TITLE
bokeh.io.push_notebook doesn't work in Jupyter Lab

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6919]
bokeh.io.push_notebook doesn't work in Jupyter Lab

**Comment by bryevdv** [comment]
This should fall out of re-implementing `push_notebook` to use the real Bokeh protocol but I'm not sure if there is another issue for that.

**Comment by bryevdv** [comment]
As is #6945 does *not* fix this, at least not yet. @canavandl you said there was some different way of creating/connecting comms for jlab?

**Comment by bryevdv** [comment]
ping @canavandl if you can point me to docs or a reference I can try to make a stab at this.

**Comment by bryevdv** [comment]
More info in this discussion: https://gitter.im/jupyter/jupyter?at=59dd4d56e44c43700a19879a

This do work when opening a *single notebook* wit JLab from the command line, but *do not work* when just starting JLab and opening a notebook from the UI

**Comment by mrocklin** [comment]
Just thought I'd add a +1 on this.  I'd love to see this resolved.  I have been pushed back to the classic notebook (or avoided bokeh) fairly regularly because of this.

**Comment by bryevdv** [comment]
This was duplicated by #7566 but the other issue was the one that got closed by the PR
