### ISSUE TITLE
Unprotected IPython imports break Bokeh without notebook installed 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6922]
There is at least one in `bokeh.io`

**Comment by bryevdv** [comment]
@Pierretherenard  if you will be around for the next hour or so, and are willing/able to help pleas stop by https://gitter.im/bokeh/bokeh-devI a going mohave an RC2 soon you could test with

**Comment by bryevdv** [comment]
Regarding the un-release, I already:

* deleted the bokeh channel conda package
* deleted the pypi package
* deleted the CDN resources including the examples tarball
* deleted the new docs and pointed `latest` back to `0.12.7

However, it just occurs to me that the NPM package has been updated and they absolutely will not allow real deletions. We will have to go ahead and publish `0.12.9` after all. But I am still glad to remove all the `0.12.8` artifacts

**Comment by bryevdv** [comment]
Tho actually the NPM upload is the very last thing that happens before the examples tarball. It will not change due to any changes in this PR. We an just let it fail and keep the one that is already uploaded there.

**Comment by Pierretherenard** [comment]
report: I ran 0.12.8 with IPython installed and all went well.

**Comment by bryevdv** [comment]
@Pierretherenard Yes but that is not acceptable, ipython is not a dependency of Bokeh, we have to fix this by ensuring that no part of Bokeh unconditionally imports ipython. i.e. is has t work *without* ipython installed

**Comment by Pierretherenard** [comment]
I totally understand.

**Comment by bryevdv** [comment]
OK this is merged and RC2 is building. @Pierretherenard if you are still around and can test with RC2 in about 10 minutes that would be very valuable

**Comment by Pierretherenard** [comment]
I am still around, i uninstalled the last booked and ipython

**Comment by bryevdv** [comment]
@Pierretherenard OK great! RC2 is now up, I have tested but would very much like a second confirmation. please report back here or at https://gitter.im/bokeh/bokeh-dev I appreciate your help!

**Comment by bryevdv** [comment]
FYI @Pierretherenard I am going to call you out and thank you in the release blog (unless you indicate that you would not like me to)

**Comment by bryevdv** [comment]
Documenting I have tested with RC2:

* notebooks with CDN and inline resources, and jlab with CDN resources
* nbconverting all of the above to HTML
* a sample of file examples with CDN and inline resources
* a sample of app examples

**Comment by Pierretherenard** [comment]
I only use pip, I am not familiar with clone if this what you want me to do. but as soon as it is available  via pip i can run it

**Comment by bryevdv** [comment]
@Pierretherenard can you try:
```
pip install --pre -i https://pypi.anaconda.org/bokeh/channel/dev/simple bokeh --extra-index-url https://pypi.python.org/simple/
```

**Comment by bryevdv** [comment]
I've also now tested RC2 pip installed into an env without ipython in various ways

**Comment by Pierretherenard** [comment]
I try the pip above and i got 0.12.7 successfully installed. the code is running right now with now problem

**Comment by bryevdv** [comment]
@Pierretherenard brilliant, THANK YOU

I am going to re-attempt a 0.12.8 build now. If it fails, will bump to 0.12.9

**Comment by Pierretherenard** [comment]
from pip install bokeh i still get successfully installed 0.12.7 not 0.12.8

**Comment by bryevdv** [comment]
@Pierretherenard PyPi will not allow re-use of versions so the release build failed. I am building 0.12.9 now

**Comment by bryevdv** [comment]
@Pierretherenard 0.12.9 is now available via pip

**Comment by Pierretherenard** [comment]
installed and running fine.
the booked website still at 0.12.7

**Comment by bryevdv** [comment]
I am seeing it updated to 0.12.9 can you do a force reload on your browser?

**Comment by Pierretherenard** [comment]
yes 0.12.9 perfect thank you very much. have a good night

**Comment by Pierretherenard** [comment]
I guess you are writing it right now
https://bokeh.pydata.org/en/latest/docs/releases/0.12.9.html

![screen shot 2017-09-11 at 11 48 08 pm](https://user-images.githubusercontent.com/23002446/30311771-bc1851fe-974b-11e7-870a-7ada6c9383f9.png)

**Comment by bryevdv** [comment]
No that's a result of our automation, I will need to rename the release file and redeploy the docs manually.

**Comment by bryevdv** [comment]
Up now: https://bokeh.pydata.org/en/latest/docs/releases/0.12.9.html

**Comment by Pierretherenard** [comment]
yes!

**Comment by Juanlu001** [comment]
> However, it just occurs to me that the NPM package has been updated and they absolutely will not allow real deletions.

I wonder why :joy:
