### ISSUE TITLE
Allow reset tool to only emit reset event, and skip built-in reset code

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6927]
So far, `Range1d._initial_start` & `Range1d._initial_end` are private JS attributes. Because the content of a plot might change - e.g. an image which size evolves - it's necessary to be able to change the initial range limits so that the proper scale is displayed  when the user clicks on the `ResetTool` button.

**Comment by bryevdv** [comment]
@mattpap Your thoughts welcome. Another possibility is to configure the reset tool explicitly with the values it should use for resets.

**Comment by bryevdv** [comment]
Thinking about this more, I think what I would instead suggest is making it so that the `ResetTool` can suppress calling the built-in `Plot.reset` method, then users could reset to whatever coordinates they want with a JS or python callback on the "reset" event.

**Comment by bryevdv** [comment]
Well unfortunately this would be slightly harder. *All* the tool does is emit the reset event. The plot listens for the event and calls its own `reset` method. So suppressing this with a configuration on the tool would require coupling them together in a bad way. To do this reasonably it will have to be a configuration of `Plot`, telling it to ignore `reset` events.

**Comment by bryevdv** [comment]
Turns out it is more reasonanble to make this a configuration of the plot:
```
plot.reset_policy = "event_only"
```
so that is what #8838 does

**Comment by bryevdv** [comment]
@nleclercq this will be in 1.1.1dev2 later today
