### ISSUE TITLE
"Slider" widget: omitting a required argument does not produce error message

### ISSUE THREAD

**Issue by JennaVergeynst** [bokeh/bokeh#6931]
Hi,

For python 3.5.4 and bokeh 0.12.7: 
using the Slider widget requires the argument 'value', 'start' and 'end', but, there is no error message telling so when you omit one of these. Would be useful to have one here I think.

Example code (copied from another issue, but with the value argument omitted), to run with:
bokeh serve --show test.py

```
# test.py

import numpy as np
from bokeh.io import curdoc
from bokeh.layouts import row, widgetbox
from bokeh.models import ColumnDataSource, formatters
from bokeh.models.widgets import Slider, PreText
from bokeh.plotting import figure

data = np.array([1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1])
source = ColumnDataSource(dict(x=data, y=range(11)))
mytext = PreText(text="{}".format(source.data['x']))

def update_data(attr, old, new):
    new_data = data * new
    source.data['x'] = new_data
    mytext.text = "{}".format(new_data)

plot = figure(x_range=(0,50))
plot.hbar(right='x', y='y', source=source, line_width=3, line_alpha=0.6, height = 7)
offset = Slider(title="offset", start=0, end=3, step=1) # here I omitted value=0
offset.on_change('value', update_data)
curdoc().add_root(row(offset, plot, mytext, width=800))
curdoc().title = "Slider"
```

**Comment by bryevdv** [comment]
@mattpap we could probably make this an issue to add explicit declarations for parameters that can be optional (or not-optional, whichever is less common)

**Comment by mattpap** [comment]
@bryevdv, I pretty sure there was an issue created for that as early as 2014, but I can't find it now. The feature is easy to implement, but reviewing and updating all properties is a pain. We have to do it anyway for static typing in bokehjs, or else we will have a lot of complaints from the type system.

**Comment by cbanek** [comment]
This also hit me on the first time using a slider, I put in start and end, but not value.  The slider rendered, but upon clicking it, it would show as NaN and not move.  It wasn't obvious what I had done wrong, but an error message (or in my case, starting value at start) would have been really helpful.

**Comment by jsignell** [comment]
Just  ran into this and wanted to say that it might be nice not to make all of start, end, and value required. If start and end are defined we should at least be able to pick a starting value halfway between them or at ==start. Current behavior is to set value to 0 regardless of start and end - which leads to dragging through NaNs.

**Comment by bryevdv** [comment]
@jsignell I think `start` and `end` need to be required. Using `start` as `value` when `value` is not specified seems OK

**Comment by bryevdv** [comment]
@mattpap offhand I think we should make `optional=True` the default to preserve current behavior. That would also allow us to proceed incrementally. At some point maybe we make it so the optional specification just has to be explicit for all properties (some future major release). Where do you imagine enforcing this requirement? Is it OK for values to be unset to start, as long as they are set some time before serialization (i.e. is this a late validation check?) or would you raise errors on any initialization/setattr?

**Comment by bryevdv** [comment]
Confirming this is still an issue with 3.0 update MRE:
```
import numpy as np
from bokeh.io import curdoc
from bokeh.layouts import row
from bokeh.models import ColumnDataSource, formatters
from bokeh.models.widgets import Slider, PreText
from bokeh.plotting import figure

data = np.array([1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1])
source = ColumnDataSource(dict(x=data, y=list(range(11))))
mytext = PreText(text="{}".format(source.data['x']))

def update_data(attr, old, new):
    new_data = data * new
    source.data['x'] = new_data
    mytext.text = "{}".format(new_data)

plot = figure(x_range=(0,50))
plot.hbar(right='x', y='y', source=source, line_width=3, line_alpha=0.6, height = 7)
offset = Slider(title="offset", start=0, value=0, end=3, step=1) # here I omitted value=0
offset.on_change('value', update_data)
curdoc().add_root(row(offset, plot, mytext, width=800))
curdoc().title = "Slider"
```
@mattpap I think some recent property changes would allow error for unset?

**Comment by mattpap** [comment]
`Slider.value` is already `Required(Float)`, so it should fail, but doesn't during serialization (both standalone and server embed). bokehjs fails with expected `Error: Slider(p1168).value is unset`. In fact, if you add `print(offset.value)` after slider construction, you will get:
```py
Traceback (most recent call last):
  File "/home/mateusz/repo/bokeh/some/some6931.py", line 20, in <module>
    print(offset.value)
  File "/home/mateusz/repo/bokeh/src/bokeh/core/property/descriptors.py", line 240, in __get__
    raise UnsetValueError(f"{obj}.{self.name} doesn't have a value set")
bokeh.core.property.descriptors.UnsetValueError: Slider(id='p1060', ...).value doesn't have a value set
```
It's clearly a bug that serializer allows unset values.

**Comment by mattpap** [comment]
Also, though it's an orthogonal issue, it wouldn't hurt if this failed more gracefully than showing empty screen and some exceptions in the JS console:
```js
Error rendering Bokeh items: Error: Slider(p1168).value is unset
    at PrimitiveProperty.get_value (properties.js:106:1)
    at Slider.get [as value] (has_props.js:111:1)
    at SliderView._calc_to (abstract_slider.js:144:1)
    at SliderView.render (abstract_slider.js:78:1)
    at RowView.render (layout_dom.js:107:1)
    at RowView.build (layout_dom.js:359:1)
    at RowView.render_to (layout_dom.js:334:1)
    at render_view (standalone.js:19:1)
    at async render_model (standalone.js:26:1)
    at async add_document_standalone (standalone.js:39:1)
plot_canvas.js:396 Uncaught TypeError: Cannot read properties of undefined (reading 'top_panel')
    at FigureView._measure_layout (plot_canvas.js:396:1)
    at FigureView.measure_layout (layout_dom.js:288:1)
    at RowView.measure_layout (layout_dom.js:286:1)
    at RowView.compute_layout (layout_dom.js:295:1)
    at RowView._after_resize (layout_dom.js:32:1)
    at RowView.after_resize (ui_element.js:116:1)
    at ResizeObserver.<anonymous> (ui_element.js:100:1)
```
