### ISSUE TITLE
Major labels for time series to start / label January of each year

### ISSUE THREAD

**Issue by esvhd** [bokeh/bokeh#6933]
Currently when you plot some **multi-year** time series in Bokeh, the x-axis major labels don't seem to follow an obvious convention, e.g. **starting at 1st or 31st Jan each year**, which is what `pandas.DataFrame.plot()` does. 

Please see example below. Unfortunately I cannot upload files from this machine at work. 

Starting x-axis labels at **Jan each year** for time series offers many benefits, for example seasonality becomes visually obvious. At the moment with Bokeh I'd have to either zoom in or add tooltip notes to get a quick look at the exact date for example.

I know this can be achieved if you play around with the labels manually, but would it be possible to have this enabled as **default** when x-axis is `datetime`?

Thank you.

```
%matplotlib inline
import numpy as np
import pandas as pd
import bokeh.plotting as bkp
import bokeh.models as bkm

from bokeh.resources import INLINE
bkp.output_notebook(resources=INLINE)

dates = pd.date_range('2010-03-01', periods=60, freq='M')
data = np.random.rand(len(dates))
df = pd.DataFrame(data, index=dates, columns=['data'])
df.plot(marker='o')

# now plot in bokeh
plot_width=750
plot_height=400
title = 'Dates do not start at 1st Jan'

source = bkp.ColumnDataSource(df)
p = bkp.figure(plot_width=plot_width, plot_height=plot_height,
               title = title,)

# add current dots
glyph = bkm.Line(y='data', x='index')
p.add_glyph(source, glyph)

p.xaxis[0].major_label_orientation = 3.1415926/4
p.xaxis[0].formatter = bkm.DatetimeTickFormatter(months=['%Y-%b'],
                                                 years=['%Y'],
                                                 days=['%Y-%m-%d'])
bkp.show(p)
```

**Comment by bryevdv** [comment]
Apologies I am not quite sure what you are asking for. Do you mean if the data start in September that the plot axis should still start in January? If so, I can't say I'd ever support making that a default behavior.

**Comment by esvhd** [comment]
Yes, but thinking about this again, it's not just about the major x-axis labels, but also the intervals. 

For example for a monthly time series starting in Sept 2000 and ends and Sept 2016, when we plot it, `pandas` default behaviour is that you'll have the **major** x-axis labels marked at Jan 2001, Jan 2002, Jan 2003, with **minor** ticks marked quarterly. Behaviour for daily time series is similar also.

What I do like in the `pandas` version is that **major labels start at beginning of each year, the minor intervals show the quarters**, this is a very natural way for us to look at time series. It's quite easy to visually compare say March over March, or Q2 versus Q2, on a yearly basis. 

Currently `Bokeh` major labels could start somewhere mid year, not necessarily at quarter start/end, and the intervals are set every 5 months by default. An interval of 5 makes sense for numerical/decimal x-axis, but less so for time series spanning over years in my view.

I attached examples of both here, which is produced by the example code I provided in the first post.

For me I deal with a lot of financial time series, many of which exhibit various seasonality effects. Being able to roughly see annual, quarterly effect is very useful. 

Note that in the `Bokeh` version below, the major labels don't show **any** same month of the year. e.g. you can see Jul 2010, but July does not appear again in any other major labels. Either you have to count the minor ticks, or have to write some formatting code to line them up.

Hope I'm explaining myself clearly?

![screenshot from 2017-09-25 22-03-53](https://user-images.githubusercontent.com/7330385/30830879-737ebd82-a23d-11e7-842d-2e1878df4d34.png)

![screenshot from 2017-09-25 22-02-13](https://user-images.githubusercontent.com/7330385/30830884-76e2259a-a23d-11e7-8cad-d82f9d92b888.png)

**Comment by bryevdv** [comment]
Bokeh does not tick at a 5 month interval, it only ticks in 1, 2, 6, and 12 month intervals:
```
        MonthsTicker(months=list(range(0, 12, 1))),
        MonthsTicker(months=list(range(0, 12, 2))),
        MonthsTicker(months=list(range(0, 12, 4))),
        MonthsTicker(months=list(range(0, 12, 6))),
```
 However, looking closer, it does makes a very course approximation that `ONE_MONTH = 30 * ONE_DAY`. I am sure the plot above is actually ticking every six "months" under this approximation. I'd suggest the first best improvement is to figure out how to make the month ticker less naive. That's probably a prerequisite to doing any further work regarding aligning on years or quarters.

**Comment by esvhd** [comment]
That would be a good start. 

Had a quick look, only found references to `ONE_MONTH` in `bokeh/models/tickers.py` and a couple of `coffee` scripts. Looks like the logic is applied in `bokehjs/src/coffee/models/tickers/months_ticker.coffee`? 

I see the [code](https://github.com/bokeh/bokeh/blob/170b23fa85d5bdea9ebc8914361f570ed4fa2e11/bokehjs/src/coffee/models/tickers/months_ticker.coffee#43) here:

```
  initialize: (attrs, options) ->
    super(attrs, options)
    months = @months
    interval = if months.length > 1
        (months[1] - months[0]) * ONE_MONTH
      else
        12 * ONE_MONTH
    @interval = interval
```
Unfortunately `coffee` is out of my area of expertise... :(

**Comment by bryevdv** [comment]
Thinking about this, I do believe that this can be accomplished already without any code changes. It's possible to create a composite ticker similar to the existing datetime ticker that only generates ticks on the quarter months, then also the appearance can be easily changed with the standard datetime tick formatter, or if necessary a func tick formatter.
