### ISSUE TITLE
hover tool stops working after zooming

### ISSUE THREAD

**Issue by bje-** [bokeh/bokeh#6935]
bokeh version 0.12.9
python version 2.7.12
Firefox version 55

I have added a hover tool to my plot using:

r = p.patches(xs='x', ys='y', color='color', legend='label',
                      source=source, line_color='black', line_width=0.5)

hover = HoverTool(tooltips=[
        ("Description", "@label"),
        ("Location", "@location"),
], renderers=[r])

p.add_tools(hover)

It works great, until I use the box zoom tool to zoom in. Then the hover tool stops working. Using the reset button restores the hover tool on the reset plot.

**Comment by bje-** [comment]
Also observed when loading the generated file into Chrome.

**Comment by bryevdv** [comment]
@bje- platform specific problems are often some of the most difficult to fix. They definitely require being able to reproduce the problem start investigating. Please update the issue with a complete code sample to reproduce the problem that can be run as-is.

**Comment by bje-** [comment]
@bryevdv Shall do.

**Comment by bryevdv** [comment]
ping @bje- if you have time to provide the MRE that would be appreciated

**Comment by bryevdv** [comment]
Without an MRE we have nothing we can investigate. I am closing for now. Please re-open if code to reliably reproduce this can be made available.
