### ISSUE TITLE
CategoricalColorMapper only supports sequence of strings as factors?

### ISSUE THREAD

**Issue by wangsix** [bokeh/bokeh#6939]
Just updated from 0.12.6 to 0.12.9 and realized that now CategoricalColorMapper only accepts sequence of strings as factors. Is there a reason for this? Previously it is possible to use sequence of integer as factors, which works nice with numerical labels from machine learning outputs.

I know it`s quite trivial to convert int to string, but still wondering why this restriction.

**Comment by bryevdv** [comment]
Recent work to re-work categoricals in Bokeh from the ground up made a number made a number of huge improvements, including getting rid of the horrible and unworkable system for categorical offsets, e.g. "foo:0.3" etc. It made the offset an optional last component of a tuple/list. But that makes an ambiguity with other usages if categories are allowed to be numbers. Perhaps there is a way to resolve this but I couldn't think of one. The other improvements far outweighed losing numeric categories (as you say it's easy to convert them to strings)
