### ISSUE TITLE
Allow dynamic HoverTool contents for GraphRenderer - both nodes and edges

### ISSUE THREAD

**Issue by ghilios** [bokeh/bokeh#6940]
I'm trying to show properties when hovering over nodes (and edges) in a graph. The nodes can have different types, and therefore different properties. This doesn't seem possible, and here's what I've run into:

1. HoverTool tooltips can be only a String or a list of (String, String) tuples. Ideally I could provide a function that provides the list of (String, String) tuples, but this is blocked by the HoverTool constructor
2. I tried providing a String containing html, but this can't seem to have anything dynamic other than a hardcoded list of variable names. I tried having a property in the data source be a list of K,V pairs that I could loop through. The moment I added a <script> tag, I got a number of errors in the python parts
3. HoverTool has some [code](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee#L324 )to receive a function for Tooltips, but from what I can tell it would have to return html. The [python model](https://github.com/bokeh/bokeh/blob/master/bokeh/models/tools.py#L724) doesn't allow tooltips to be a function.
4. I can't tell whether CustomJS could be useful here for this. Regardless, it seems to be [broken now](https://github.com/bokeh/bokeh/issues/6891)

Ultimately, I'd like to show properties for each node *and* edge whenever I mouse over them. I also don't see a way to do this at all for edges, unless I'm missing something. Does anyone have a recommendation?

**Comment by ghilios** [comment]
The closest idea I can come up with is to create a custom Inspection Tool. Does this sound like the right path?

**Comment by bryevdv** [comment]
@ghilios There are lots of use-cases, so new graph capability was designed with extensibility in mind. The inspection policies for graphs (e.g `NodesAndLinkedEdges` or `NodesOnly`) are themselves Bokeh modes. So it's possible to write you a custom extension to implement a new different policy (e.g. nodes and edges, but separate, not linked). You can see the implementations of the built in policies here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/graphs/graph_hit_test_policy.coffee

I'm happy to discuss further but this seem more like a support question, so I'll suggest moving to the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
