### ISSUE TITLE
How to dynamically change the number of labels in each point of a hovertool in bokeh ? So for example if I hover in one point the number of labels will be 1 and upon next plot the number of label maybe 2 or any number ?

### ISSUE THREAD

**Issue by subho22** [bokeh/bokeh#6942]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by bryevdv** [comment]
As stated above in the issue template, th GitHUb tracker is not the appropriate place for general support questions. For that, you should use the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
