### ISSUE TITLE
Bar Chart with Additional Values in Mouse Hover

### ISSUE THREAD

**Issue by rodolfobolconte** [bokeh/bokeh#6944]
I would like to know how do I display the value of the total (among other additional values) with the hover mouse in bar charts as it is not working. Follow the code:

from bokeh.charts import Bar, show
from bokeh.models import ColumnDataSource, HoverTool

data = {'Total': [2, 13, 5], 'ID': [0, 1, 2], 'Desc': [4, 5, 6]}
p = Bar(data, label='ID', values='Total', width=400, tools='hover')
hover = p.select(dict(type=HoverTool))
hover.tooltips = [('Value of ID','@ID'), ('Value of Total','@Total')]

show(p)

**Comment by bryevdv** [comment]
The old `bokeh.charts` (including `Bar`) have been moved to a separate project [`bkcharts`](https://github.com/bokeh/bkcharts). You could file this issue there, but please know that `bkcharts` is ***currently unmaintained***, so it is unlikely any response will occur. 

However, you do not and should not need to use `bkcharts` for bar charts. Core Bokeh recently got a complete refresh of its categorical data handling, including making many different kinds of bar charts (stacked, grouped) as well as categorical heat maps, jittered categorical scatters, and joy plots, all very easy with `bokeh.plotting`. See more here:

https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html

Any follow on support questions should go to the mailing list as described in the issue tracker:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
