### ISSUE TITLE
color mapping in circle fill colors does not take current view (CDSView) into account

### ISSUE THREAD

**Issue by GenericUser123** [bokeh/bokeh#6947]
bokeh 0.12.8rc2, Tornado 4.5.1, Windows 10, Firefox 55.0.3, python 3.6.1

The attached code shall demonstrate a bug:
The source contains 5 data points as a simple example.
The y-values equal to 1 shall be filtered (using BooleanFilter) and additionally colored green, using a linear color mapper.

Filtering works, only the points number 1, 2 and 5 are plotted.
But the coloring is "green, green, blue", instead of "green, green green" as expected.
It seems to take into account the indices of the points number 1,2 and 3 and not of 1,2 and 5.
So obviously the coloring is based on the original, non-filtered source and does not take the current provided view into account.

I would appreciate if this bug could be solved.
And also, if anyone has an idea of a work around in the meantime.

Thanks a lot and best regards,
Juerg

```
# code goes here between backticks
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, CDSView, BooleanFilter, LinearColorMapper
from bokeh.io import show

data = {'x_values': [1, 2, 3, 4, 5],
        'y_values': [1, 1, 0, 0, 1]}

colors = ["blue", "green"]
boolean_colors = LinearColorMapper(palette=colors, low=0, high=1)



source = ColumnDataSource(data=data)

booleans = [True if val == 1 else False for val in source.data['y_values']]

view1 = CDSView(source=source, filters=[BooleanFilter(booleans)])

p=figure()
p.circle("x_values","y_values", size=20, source=source, view=view1, fill_color={'field': "y_values", 'transform': boolean_colors})

show(p)
```

**Comment by bryevdv** [comment]
cc @clairetang6
