### ISSUE TITLE
y_range doesn't understand numpy arrays

### ISSUE THREAD

**Issue by hiramf** [bokeh/bokeh#6951]
in the example below, `source2` works, but `source` does not. In order to get `source` to work, I have to add a `tolist()` clause (i.e. `y_range=source.data['fruits'].tolist()`)

    import pandas as pd
    import numpy as np
    import random
    from bokeh.io import push_notebook, show, output_notebook, show
    from bokeh.plotting import figure
    from bokeh.models import ColumnDataSource
    output_notebook()

    f = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
    c = random.sample(range(0,100), 6)
    df = pd.DataFrame({'fruits':f, 'counts':c})

    source = ColumnDataSource(df)
    source2 = ColumnDataSource(data=dict(fruits=f, counts=c))

    p = figure(y_range=source.data['fruits'], plot_height=250, title="Fruit Counts",
           toolbar_location=None, tools="")
    p.hbar(y='fruits', right='counts', height=0.9, source=source)
    show(p)

    print(type(source.data['fruits'])) ## <class 'numpy.ndarray'>
    print(type(source2.data['fruits'])) ## <class 'list'>

**Comment by bryevdv** [comment]
@hiramf would you be interested in contributing a PR for this? It should just need a new two-line if test in this function to handle arrays:

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/helpers.py#L340

as well as a test added in this area:

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/tests/test_helpers.py#L180
