### ISSUE TITLE
export_png errors if a directory does not exist

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#6964]
If a filename with a directory is passed to `export_png` and the directory does not exist then the command errors with a `FileNotFoundError: [Errno 2] No such file or directory:`. I would expect it to create a directory as a convenience just like it is creating a file.

```
from bokeh.plotting import figure
from bokeh.sampledata.autompg import autompg as df

plot_opts = dict(toolbar_location=None, background_fill_color=None, border_fill_color=None, 
                 outline_line_color=None, plot_width=600, plot_height=300)

plot = figure(title="mpg vs hp", **plot_opts)
plot.circle(x=mpg, y=hp, color='blue', source=df)

export_png(plot, filename="new_dir/plot.png")
```

**Comment by bryevdv** [comment]
I'm not sure, I think my personal preference might be a better error message (stating that the directory is missing) I don't know that I'd want directories to be created automatically. In case of an error in specifying the path it greatly magnifies the possibilities of bad/annoying things happening.

**Comment by bryevdv** [comment]
@bokeh/dev any other thoughts? I am inclined to close this. Basically, I think its much more likely that I will make some mistake specifying a directory, and I would not want Bokeh to amplify my mistakes by creating directories silently.

**Comment by canavandl** [comment]
I agree. I think silently creating directories is an anti-pattern.
