### ISSUE TITLE
Push session url

### ISSUE THREAD

**Issue by kiluvya** [bokeh/bokeh#6974]
I am trying to understand how Push sessions url works, but every scenarion gives me error.

For example: in my Django app, I can stream bokeh app with the following code
```
   #views.py
    session = pull_session(url = "http://localhost:5006/the_app")
    bokeh_script=autoload_server(None,url = "http://localhost:5006/the_app", session_id= session.id)    
    return render(request, u'map.html', {u'the_script': bokeh_script})
```

pull_session Url, allows me to get pull the session id of an application that is running on that url.
So, with push_session_url I expected it to be where I want my app to go. I tried to put something like this below
`session = push_session(curdoc(), session_id=topic, url="http://127.0.0.1:8000/the_app/")`
But it will not START, it will display error
 `OSError: Cannot push session document because we failed to connect to the server (to start the server, try the 'bokeh serve' command)
`

I am sure boke server is running with command "bokeh serve"
How does push_session url work?
An example will be better. Or how will you push_session to url   ""http://127.0.0.1:8000/the_app/" and display it there?

Thanks.

**Comment by bryevdv** [comment]
@kiluvya The GitHub issue tracker is reserved for feature requests an bug reports only, please ask general support and usage questions on the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
