### ISSUE TITLE
TypeError: OutputArea.prototype.mime_types is not a function

### ISSUE THREAD

**Issue by conicRelief** [bokeh/bokeh#6975]
Hi, I'm trying to run the following code
```
from bokeh.plotting import figure, show, output_notebook
output_notebook()
```  
 and get this error  
  
`TypeError: OutputArea.prototype.mime_types is not a function`  
  
... any thoughts on what the issue might be?

**Comment by canavandl** [comment]
We need more information to help diagnose the issue.

What version of Bokeh is this?
Is this in the classic notebook or Jupyter Lab or something else? What version?
What browser/OS is this?

**Comment by conicRelief** [comment]
as far as i can tell it's the classic notebook. I don't use conda. 
  
Chrome  
Windows 10

jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0  

bokeh==0.12.9

**Comment by bryevdv** [comment]
You will have to upgrade to notebook >= 5.0, or downgrade Bokeh. There is no technical path to make Bokeh compatible with both the new JupyterLab, and with older classic notebook versions. As of Bokeh 0.12.9 and all future versions of Bokeh Notebook 5.0 is the minimum supportable version.
