### ISSUE TITLE
Feature Request: Custom CSS classes on Label (and other rendered models)

### ISSUE THREAD

**Issue by rbu** [bokeh/bokeh#6977]
I would like to present certain ```Label```s with custom styles when embedding them. I appreciate there are many styling options exposed as ```text_``` properties, but seems infeasible to attempt to cover the full range of CSS properties.

Thus, I propse to add a ```Renderer``` level property ```css_classes``` similar to what #5503 did for ```LayoutDOM``` models. I particularly need this for ```Label``` and ```LabelSet``` elements, but I guess all elements that render to DOM elements could be covered easily.

**Comment by bryevdv** [comment]
@rbu I think unfortunately that it would be awkward and possibly a source of increased support questions/burden to add an interface that only works some of the time (CSS render mode) but not other times (default canvas render mode). Additionally, even in the CSS rendering case, I think there are ambiguities about what to do when the a value set by css_classes conflicts with a property value. I think if you need specialized label rendering beyond what's in the code library, then it might make more sense for you to create your own custom extension:

https://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html

cc @bokeh/dev @canavandl in case there are other/different thoughts.

**Comment by rbu** [comment]
@bryevdv, thank you for the feedback.

I already noticed significant differences in rendering between canvas and css mode, as seen in the [many warnings](https://bokeh.pydata.org/en/latest/docs/reference/models/annotations.html), so I was not aware you consider that to be a problem. However, I appreciate you trying to reduce the differences instead of increasing them. In this case, I would like to add, the behavior seems pretty self-explanatory to me: "css classes will only be added when css rendering is used," so I would not expect much user confusion and support.

Regarding your point of conflicting values between properties set in any custom css versus model-level properties, I'd weigh in and add that different values for a property on different levels of hierarchy is one of the strengths in CSS. While it allows to shoot yourself in the foot (when you have too many layers of conflicting changes), I consider it a feature to have layers that allow more specific adaptations (for example, adding a css-class to an annotation that causes it to have a different font color and border-radius all other labels).

Nevertheless, thank you for pointing our the extensions documentation. I have not used that feature yet, but I'll consider that as an alternative route.

**Comment by bryevdv** [comment]
perhaps an alternative idea would be to add a `safe` flag that supresses any HTML escaping (in CSS render mode). We could also potentially suppress setting any CSS baed on Bokeh proprties when `safe` is True, That would be a much simpler and well-defined interaction I think.

**Comment by bryevdv** [comment]
I'm going to close this in favor of https://github.com/bokeh/bokeh/issues/8113 That issue is about making it possible to programmatically fix hover tooltops at specific locations.  Tooltips already support a rich HTML formatting option so that would accomplish "rich labelling" without having to further complicate `Label`
