### ISSUE TITLE
0.12.6: Rect/Circle are painted even if the position is None

### ISSUE THREAD

**Issue by Nemecsek** [bokeh/bokeh#6983]
**Rect** and **Circles** (didn't try **Ellipse**, etc.) are painted even if the Y position is _None_.
Here is a working example for Jupyter. I have some data for months, but the last 3 months are missing.
The rect for None should be invisible, but it is painted at position 0:

```
import pandas as pd
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

output_notebook()

months = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()    
avg = [378.698, 398.911, 389.112, 354.642, 357.627, 376.175, 415.014, 400.439, 442.276, None, None, None]
    
source = ColumnDataSource(dict(months=months, avg = avg))

for m,a in zip(months, avg):
    print("{}: {}".format(m,a))
                           
p = figure(x_range=months, plot_width=800, plot_height=300, toolbar_location=None, title=None)

p.rect(x="months", y="avg", source=source, width=.4, height=10, color="blue", fill_alpha=1, line_color=None)
# p.circle(x="months", y="avg", source=source, size=10, color="red", fill_alpha=1, line_color=None)
    
show(p)
```

The same is not true for **vbar**: they behave well.
This can be a workaround: based on the value of avg I create avg_bottom, the same values minus a offset. avg will be the top of vbar, avg_bottom the bottom:

```
import pandas as pd
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

output_notebook()

months = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()    
avg = [378.698, 398.911, 389.112, 354.642, 357.627, 376.175, 415.014, 400.439, 442.276, None, None, None]

avg_bottom = [] 
for i in avg:
    avg_bottom.append(i-10 if i is not None else None)

source = ColumnDataSource(dict(months=months, avg = avg, avg_bottom=avg_bottom))

for m,a in zip(months, avg):
    print("{}: {}".format(m,a))
                           
p = figure(x_range=months, plot_width=800, plot_height=300, toolbar_location=None, title=None)

p.vbar(x="months", top="avg", bottom="avg_bottom", source=source, color="blue", fill_alpha=1, width=.4, line_color=None)
    
show(p)
```

I assume it is something that could be easily fixed.

**Comment by bryevdv** [comment]
> I assume it is something that could be easily fixed.

I'm not sure it should be "fixed", the intent with columns in CDS is that they are homogeous in type. I  would describe violating this (i.e. passing `None` instead of a number) as undefined behaviour.

**Comment by Nemecsek** [comment]
Bryan, what if a value is not available?
I assume 'None' would be a choice and could completely avoid the print.

**Comment by clairetang6** [comment]
@Nemecsek, using np.NaN instead of None works the way you intend. I think the ability to deal with missing values is useful and Bokeh does already support it, but parts of the handling of missing values might be accidental.

**Comment by bryevdv** [comment]
A `None` value gets rendered as `null` in the JSON. Then `null + 5 == 5` on the JavaScript side, because JavaScript. Changing the current behavior would require making every glyph render path quite a bit heavier and more complicated. Given that, and that there are several other potential ways to handle missing data, i.e.:

* use nan's
* use CDS views
* don't send missing data
* `CustomJSTransform` to map nulls to nans

I am going to close this.
