### ISSUE TITLE
Tooltip points to wrong place in area charts

### ISSUE THREAD

**Issue by benlindsay** [bokeh/bokeh#6984]
macOS Sierra version 10.12
Python version 3.6.2
Jupyter version 1.0.0
Bokeh version 0.12.6

I have a stacked area plot showing memory usage over time on a shared machine, and I have a hover tool to show which user I'm hovering over. I'd like the tool tip to point to at least part of the right area, but this is not guaranteed. Here's the code I have running in a Jupyter Notebook:

```
import pandas as pd
import bkcharts as bkc
import bokeh.io as bki
import bokeh.models as bkm
import bokeh.plotting as bkp
bki.output_notebook()
cols = ['user_1', 'user_2', 'user_3', 'remaining']
df = pd.DataFrame({cols[0]: [2, 4, 3, 5],
                   cols[1]: [1, 1, 1, 2],
                   cols[2]: [3, 2, 2, 1],
                   cols[3]: [2, 1, 2, 0]})
df = df[cols]
p = bkc.Area(df, stack=True, xlabel='Date', ylabel='Memory', legend='top_left')
renderers = p.renderers[1:len(df.columns)+1]
for r, label in zip(renderers, df.columns):
    p.add_tools(bkm.HoverTool(renderers=[r], tooltips=[('Label:', label)]))
p.legend[0].items = list(reversed(p.legend[0].items))
bkp.show(p)
```

With this setup, if for example, I hover over the blue `user_2` area, a tooltip with the correct label shows up, but it's pointing at `user_1`. Here's an image:

![image](https://user-images.githubusercontent.com/9361152/31022193-0768e62e-a506-11e7-8310-638b1c279abd.png)

The tooltip locations to trend in the right direction (i.e. the y position of `remaining` > `user_3` > `user_2` > `user_1`), but I feel like it could do better and actually ensure that it's pointing at the correct area.

**Comment by bryevdv** [comment]
The old `bokeh.charts` (including `Bar`) have been moved to a separate project [`bkcharts`](https://github.com/bokeh/bkcharts). You could file this issue there, but please know that `bkcharts` is ***currently unmaintained***, so it is unlikely any response will occur. 

However, you do not and should not need to use `bkcharts` for bar charts. Core Bokeh recently got a complete refresh of its categorical data handling, including making many different kinds of bar charts (stacked, grouped) as well as categorical heat maps, jittered categorical scatters, and joy plots, all very easy with `bokeh.plotting`. See more here:

https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html

Any follow on support questions should go to the mailing list as described in the issue tracker:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
