### ISSUE TITLE
Oval selection does not update color (does not support hit testing)

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#6985]
When using an oval for a graph node, the oval's color is not updated when selected.

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 0.12.9

#### Description of expected behavior and the observed behavior
Expected behavior is that the fill_color would be updated like it is with a Circle glyph. Uncomment the Circle glyph lines in the code to see the expected behavior.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import math

from bokeh.io import show, output_notebook
from bokeh.plotting import figure
from bokeh.models import GraphRenderer, StaticLayoutProvider, Oval, TapTool, Circle
from bokeh.palettes import Spectral8
output_notebook()

N = 8
node_indices = list(range(N))

plot = figure(title="Graph Layout Demonstration", x_range=(-1.1,1.1), y_range=(-1.1,1.1),
              tools="", toolbar_location=None)

graph = GraphRenderer()

graph.node_renderer.glyph = Oval(height=0.1, width=0.2, fill_color="red")
graph.node_renderer.selection_glyph = Oval(height=0.1, width=0.2, fill_color="blue")
# graph.node_renderer.glyph = Circle(size=15, fill_color="red")
# graph.node_renderer.selection_glyph = Circle(size=15, fill_color="blue")
graph.node_renderer.data_source.data = dict(
    index=node_indices)

graph.edge_renderer.data_source.data = dict(
    start=[0]*N,
    end=node_indices)

### start of layout code
circ = [i*2*math.pi/8 for i in node_indices]
x = [math.cos(i) for i in circ]
y = [math.sin(i) for i in circ]

graph_layout = dict(zip(node_indices, zip(x, y)))
graph.layout_provider = StaticLayoutProvider(graph_layout=graph_layout)

plot.renderers.append(graph)
plot.add_tools(TapTool())

# output_file("graph.html")
show(plot)

```

**Comment by bryevdv** [comment]
Sorry this missed being triaged. This has nothing to do with graphs. Ovals (and ellipses) do not yet support any kind of hit testing, so selections do not work on them at all. Presumably if someone can track down "point in oval" / "point in ellipse" hit testing code it would be straightforward to implement `_hit_point` for point hit testing at least.
