### ISSUE TITLE
Allow toolbar in side panels and drop sticky property

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6990]
Although `toolbar_sticky` is the default, it rarely works properly, e.g. overlapping with axes, unless you stick to default configuration. Allowing toolbars in side panels would allow us to properly maintain relationship between toolbar and axes, annotations, etc. I'm not sure about the details right now, because toolbar is a `LayoutDOM`, so there may be some deeper changes needed. Those changes may be necessary anyway as we want to have off-canvas legends (situation isn't exactly the same, but it's close). This could also allow us to merge `Plot` and `PlotCanvas` again, if desired. It would also, in a longer term, allow us to have multiple toolbars (e.g. main split or having separate animation toolbar) and sharing one panel between a toolbar and e.g. a legend.

**Comment by bryevdv** [comment]
I don’t care what the implementation is, as long as there is a way (and it is the default) thatvyhe toolbar abuts the plot area directly as it does now. Having the toolbar abut the plot area looks infinitely better than having it float off, and having ugly visual design is a not insignificant competitive disadvantage

**Comment by bryevdv** [comment]
Ie maybe the toolbar goes in a side panel and it has the optional ability to override padding on its side to zero.

**Comment by mattpap** [comment]
By default there is not padding (or in fact margin), so it would behave like an axis, i.e. it would stick to the frame. Non-sticky toolbar would be implemented similarly to legends, which maintain their own margins (although I would like to unify this across all entities that are allowed in panels).
