### ISSUE TITLE
Bad positioning of ColorBar for 'above' and 'below'

### ISSUE THREAD

**Issue by ceball** [bokeh/bokeh#6993]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

* bokeh 0.12.9 and current master
* python: `'3.6.2 |Anaconda, Inc.| (default, Sep 30 2017, 13:47:48) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'`
* notebook: 5.0.0
* OS: OS X 10.12.6
* browser: Chrome Version 60.0.3112.113 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior

Expected (and what happens with 0.12.7):

<img width="640" alt="screen shot 2017-10-01 at 4 28 43 pm" src="https://user-images.githubusercontent.com/1929/31056638-950eb6da-a6cc-11e7-8c72-668c7b62af4b.png">

Observed (with 0.12.9 and current master):

'above'
<img width="642" alt="screen shot 2017-10-01 at 4 29 01 pm" src="https://user-images.githubusercontent.com/1929/31056640-a5a69148-a6cc-11e7-9a52-f29dc59105c2.png">

'below'
<img width="625" alt="screen shot 2017-10-01 at 5 11 04 pm" src="https://user-images.githubusercontent.com/1929/31056654-feceba16-a6cc-11e7-846a-762ec4cac261.png">

Note: apparently no problem with 'left' or 'right':

<img width="609" alt="screen shot 2017-10-01 at 5 12 10 pm" src="https://user-images.githubusercontent.com/1929/31056646-cbc709de-a6cc-11e7-8150-05a417e2fd2f.png">

#### Complete, minimal, self-contained example code that reproduces the issue

From https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#color-bars (plus minor alteration to specify location)

```python
import numpy as np

from bokeh.plotting import figure, output_file, show
from bokeh.models import LogColorMapper, LogTicker, ColorBar

output_file('color_bar.html')

def normal2d(X, Y, sigx=1.0, sigy=1.0, mux=0.0, muy=0.0):
    z = (X-mux)**2 / sigx**2 + (Y-muy)**2 / sigy**2
    return np.exp(-z/2) / (2 * np.pi * sigx * sigy)

X, Y = np.mgrid[-3:3:100j, -2:2:100j]
Z = normal2d(X, Y, 0.1, 0.2, 1.0, 1.0) + 0.1*normal2d(X, Y, 1.0, 1.0)
image = Z * 1e6

color_mapper = LogColorMapper(palette="Viridis256", low=1, high=1e7)

plot = figure(x_range=(0,1), y_range=(0,1), toolbar_location=None)
plot.image(image=[image], color_mapper=color_mapper,
           dh=[1.0], dw=[1.0], x=[0], y=[0])

color_bar = ColorBar(color_mapper=color_mapper, ticker=LogTicker(),
                     label_standoff=12, border_line_color=None, location=(0,0), 
                     orientation="horizontal")

plot.add_layout(color_bar, 'above')

show(plot)
```

#### Stack traceback and/or browser JavaScript console output

n/a

#### Screenshots or screencasts of the bug in action

(see above)

**Comment by bryevdv** [comment]
AFAICT there were no changes to the color bar itself in that time. But there were to `plot_canvas.coffee` and `cartesian_frame.coffee` which might be likely suspects.

**Comment by bryevdv** [comment]
bisecting with BokehJS dependency changes is a pain, so I'll do it, working on it now

**Comment by bryevdv** [comment]
Here is the bad commit:

https://github.com/bokeh/bokeh/commit/3a28aa0387fcb2b0572ad7ef7693b8318259a93b

IIRC this was to use screen instead of data bounds to position axes labels correctly in the center, even if log scales were used.

**Comment by mattpap** [comment]
What changed in particular in that commit is that panels don't overlap each other in corners, and now any entities in panels must position themselves relative to panels and not canvas.

**Comment by mattpap** [comment]
Obviously ColorBar has custom handling of its position, so doing the right thing breaks its behavior.

**Comment by ceball** [comment]
Thanks for doing the narrowing down work for me! And then thanks for fixing it so fast :)
