### ISSUE TITLE
Incorrect module path format when building bokehjs on windows

### ISSUE THREAD

**Issue by cpa-level-it** [bokeh/bokeh#7004]
I think I found a bug when building bokehjs on windows.
The path format of the modules inside the `.json` files of the `build\js` folder is incorrect.

It looks like this 
`client\\connection`
Instead of 
`client/connection`

With the incorrect format, the compiler won't be able to find the module dependencies and will fail.
The problem arises in the function `resolve_deps` of `compiler.py`

```python
    def resolve_deps(deps, root):
        custom_modules = set([ model.module for model in custom_models.values() ])
        missing = set(deps) - known_modules - custom_modules
        return resolve_modules(missing, root)
```

In this code `deps` are expressed as path to the module in the unix format but `known_modules` are expressed as path using the windows format. As the formats are different, the comparaison will always fail, `missing` will just contains all the modules (even the existing ones) and `resolve_modules` will fail.

I think the error comes from the file `bokehjs/gulp/linker.ts` I think it should always generate the `.json` files using the unix path format even if running on windows.

**Comment by mattpap** [comment]
>  I think it should always generate the .json files using the unix path format even if running on windows.

Yes, especially because they aren't file system paths, but module paths, and those should use only forward slash.

**Comment by xavArtley** [comment]
solved in https://github.com/bokeh/bokeh/pull/8565
