### ISSUE TITLE
The inherited width should be set to 100% and up to the user to implement margin and padding restrictions

### ISSUE THREAD

**Issue by mcurry7** [bokeh/bokeh#7014]
**Here is a link to the line that is in contention:**
https://github.com/bokeh/bokeh/blob/08020a31393630a2bda1bb083564492d14669264/bokeh/core/_templates/file.html#L33

When inheriting a sizing parameter it should always be 100% up to the user to be in control of the restrictions. This should be done entirely via the users own HTML setup of the layout or via a set of control options in the doc object, I would think.

**Comment by bryevdv** [comment]
@birdsarah this looks to be your change from #4343 Do you remember any context or rationale for us hard coding a width?

**Comment by mattpap** [comment]
I presume it's a stylistic thing. Otherwise a plot would end up directly on the left edge of a web browser.

**Comment by bryevdv** [comment]
Probably. Perhaps a parameter to override is the best option to keep s sensible default for directly viewed app pages

**Comment by mattpap** [comment]
Also, setting width/height altogether is necessary for responsive modes to work properly. There is is also a margin that overwrites the browsers' arbitrary default.

**Comment by mattpap** [comment]
> Perhaps a parameter to override is the best option to keep s sensible default for directly viewed app pages

Possibly yes, but I would also like to give this some more thought, because I has bothered me for awhile now, that core functionality to work depends on some piece of CSS in a template.
