### ISSUE TITLE
No loggers

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#7018]
This message started recently appearing instead of (e.g. validation) logs:
```
No handlers could be found for logger "/home/mateusz/repos/bokeh/bokeh/core/validation/check.pyc"
```
I presume this has something to do with logic in `bokeh.util.logconfig` and `bokeh.settings`.

Example code:
```python
from bokeh.embed import file_html
from bokeh.plotting import figure
from bokeh.resources import INLINE

f = figure()

h = file_html(f, INLINE)
```

**Comment by bryevdv** [comment]
I don't actually see any output or message at all when I run that on py3

**Comment by bryevdv** [comment]
Did you mean to not have the `f.text` line? If I remove that I see the warning:
```
~/tmp
❯ python test.py
W-1001 (NO_DATA_RENDERERS): Plot has no data renderers: Figure(id='5d1e1084-43ba-488d-b6b2-54a8842f114e', ...)
```

**Comment by mattpap** [comment]
> Did you mean to not have the f.text line? If I remove that I see the warning:

Yes.

**Comment by mattpap** [comment]
So this is a Python 2 issue. On Python 3 I see the warning as expected.
