### ISSUE TITLE
Extra Y Range = None (bokeh 0.12.6 works; 0.12.9 issue)

### ISSUE THREAD

**Issue by um8ra** [bokeh/bokeh#7019]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh=0.12.9 (problem) 0.12.6 (works)
Python=3.5.3
OS=Windows 10 (Django dev environment)
Django=1.11.5 (irrelevant to problem)
#### Description of expected behavior and the observed behavior
I expect when y_range_name=None for the data to be plotted on the default y range. This was the behavior in 0.12.6. When running in 0.12.9, I must do a type-check on arguments and see if y_range_name is none, and if so, call fig.line(x,y) rather than fig.line(x,y, y_range_name=None). I frequently use secondary axis, so being able to pass None to a function when I want it plotted on the main y axis was nice.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, show
x = list(range(10))
y = list(range(10))
fig = figure()
fig.line(x, y, y_range_name=None)
show(fig)
```

#### Stack traceback and/or browser JavaScript console output
TypeError: b is undefined[Learn More]  bokeh-0.12.9.min.js:27:202
	r.GlyphView</r.prototype.set_data https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:27:202
	r.GlyphRendererView</e.prototype.set_data https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:31:21253
	r.GlyphRendererView</e.prototype.initialize https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:31:19529
	t https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:22:1349
	e https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:1:18195
	e https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:31:30682
	e https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:31:18428
	r.build_views https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:1:15182
	r.PlotCanvasView</e.prototype.build_levels https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:30:26257
	r.PlotCanvasView</e.prototype.initialize https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:30:19286
	t https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:22:1349
	e https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:1:18195
	e https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:30:17506
	r.build_views https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:1:15182
	r.LayoutDOMView</e.prototype.build_child_views https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:29:7465
	r.LayoutDOMView</e.prototype.initialize https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:29:4607
	t https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:22:1349
	e https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:1:18195
	e https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:29:4407
	e https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:30:7536
	n https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:22:22455
	h https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:22:23134
	r.embed_items https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:22:25486
	embed_document file:///C:/Users/a0221560/AppData/Local/Temp/tmpp8y0hum4.html:41:19
	fn/</< file:///C:/Users/a0221560/AppData/Local/Temp/tmpp8y0hum4.html:45:19
	fn/< file:///C:/Users/a0221560/AppData/Local/Temp/tmpp8y0hum4.html:36:16
	i https://cdn.pydata.org/bokeh/release/bokeh-0.12.9.min.js:36:7411
	fn file:///C:/Users/a0221560/AppData/Local/Temp/tmpp8y0hum4.html:35:13

#### Screenshots or screencasts of the bug in action
![bokeh](https://user-images.githubusercontent.com/16314441/31280394-d1c0a126-aa71-11e7-8972-3326fc31c7d4.png)

**Comment by mattpap** [comment]
You should use `fig.line(x, y, y_range_name="default")` instead. If `None` worked before, it's likely it was just a coincidence.

**Comment by um8ra** [comment]
That works. Thank you!
