### ISSUE TITLE
Scatter plot displays point markers properly in Firefox, but they are invisible in Chrome

### ISSUE THREAD

**Issue by chelsell** [bokeh/bokeh#7026]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Chrome: Version 61.0.3163.100 (Official Build) (64-bit)
Firefox: 55.0.3 (64-bit)
OS: macOS Sierra, 10.12.6 (16G29)
Jupyter: ﻿1.0.0
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Bokeh: 0.12.4

#### Description of expected behavior and the observed behavior
I have a scatter plot generated from a jupyter notebook and saved as an HTML. In Firefox, it works perfectly. In Chrome, I see the hover text and whited out areas where points in the plot should be, but the colors don't show up. I would expect them to be the same, give or take.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import pandas as pd
from bokeh.plotting import figure, show, output_file
from bokeh.models import (
    ColumnDataSource, HoverTool, SingleIntervalTicker, Slider, Button, Label,
    CategoricalColorMapper,)

N = 10000
x = np.random.uniform(low=0, high=80, size=N)
y = np.random.uniform(low=6000, high=12000, size=N)

colors = [
    "#%02x%02x%02x" % (int(r), int(g), 150) for r, g in zip(50+2*x, 30+2*y)
]

TOOLS="crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"

df = pd.DataFrame({'xi': x, 'yi': y, 'colori': colors})

p = figure(tools=TOOLS)

p.scatter('xi', 'yi',
          fill_color='colori', fill_alpha=0.6,
          line_color=None, source=df, name="Outlying Phenotypes from a Large Behavioral Screen")
p.add_tools(HoverTool(tooltips="@yi", show_arrow=False, point_policy='follow_mouse'))

output_file("color_scatter.html", title="color_scatter.py example")

show(p)  # open a browser

```

#### Screenshots or screencasts of the bug in action
# firefox
<img width="621" alt="image" src="https://user-images.githubusercontent.com/14339148/31354194-4bdb236c-acea-11e7-91a1-b2374b67f2c8.png">

# chrome
<img width="641" alt="image" src="https://user-images.githubusercontent.com/14339148/31354172-39be2364-acea-11e7-8d27-45f291120c05.png">

**Comment by bryevdv** [comment]
@chelsell Thanks for the detailed report. We do not have sufficient resources as a team to go back and update previous releases. So my first ask from you is: try this code with the latest release `0.12.9` and ideally with the latest dev build `0.12.10dev2` to see if this issue exists in current versions or not. If not, we can close this issue.

**Comment by bryevdv** [comment]
@chelsell This is a usage error. You are generating bad color values. The `"%02x"` does not truncate to two places and you are feeding in values well outside `(0-255)` for the blue channel.

**Comment by chelsell** [comment]
Thanks @bryevdv, didn't realize I was behind a version!
