### ISSUE TITLE
Server docs are misleading

### ISSUE THREAD

**Issue by LinuxChristian** [bokeh/bokeh#7031]
#### Software
Affects everything from v0.12.5 until latest.

#### Description of expected behavior and the observed behavior
According to the documentation https://bokeh.pydata.org/en/0.12.9/docs/user_guide/server.html#accessing-the-http-request I should be able to do,

```
args = curdoc().session_context.request.cookies
```

This option was however removed due to issue #5901 where `_RequestProxy` was introduced. Just spend a lot of head scratching getting `curdoc().session_context.request.headers` working.

I suggest updating the docs to reflect that only arguments are allowed for requests.

**Comment by bryevdv** [comment]
Thanks for the report. The core devs are all overtasked at the moment. If you have the opportunity, this  is the file to update:

https://raw.githubusercontent.com/bokeh/bokeh/master/sphinx/source/docs/user_guide/server.rst

A small PR would be appreciated.

**Comment by LinuxChristian** [comment]
Here you go 😄 

#7034
