### ISSUE TITLE
Hover Tool does not display over vbar glyphs clipped by plot border

### ISSUE THREAD

**Issue by Jacob-Barhak** [bokeh/bokeh#7032]
This happens on Windows 7x64,  Python 2.7.11 , Anaconda 2.4.1 (64-bit),  Bokeh 0.12.9, problem recreated on Firefox, IE11 and Chrome.

#### Description of expected behavior and the observed behavior
When hovering over a glyph that extends beyond the plot border, it is still expected to see the tooltip. However, it does not display properly on a bar graph where the bar is clipped by the plot border. 

See code below to recreate the problem in the file 'BarPlotTest.html'. If hovering over bars over x positions 3 and 4 that extend beyond the plot region the hover tool does not show up. And it may be very useful in such cases to show values beyond the plot region. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
# -*- coding: utf-8 -*-

from __future__ import division
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import file_html
from bokeh.models import Range1d , HoverTool, ColumnDataSource   


MyHover1 = HoverTool(
	tooltips=[
		( 'Parameter', '@Param{%s}'),
		( 'Parameter Value', '@Value' ),  
	],
	formatters={
		'Param' : 'printf',   
		'Value' : 'numeral', 
	},
)    

Plot = figure(title = 'Title', x_axis_label = 'TitleX', y_axis_label = 'TitleY', tools=[MyHover1], x_range = Range1d(0, 6), y_range = Range1d(-0.1, 1.1))
Plot.xaxis.major_label_orientation = "vertical"

BarSources = ColumnDataSource(data=dict(Param=[1,2,3,4,5], Value=[0.5,0.6,18,-1,0.3]))
Plot.vbar(x='Param', source = BarSources, width = 0.7, bottom = 0 , top = 'Value', fill_color = 'black', line_color='black')


Html = file_html(Plot, CDN, 'my plot')
OutFile = open('BarPlotTest.html','w')
OutFile.write(Html)
OutFile.close()

```

**Comment by bryevdv** [comment]
HI, this is actually a usage issue. It's not that bar is clipped, it's that the *center* of the bar is off screen. By default the `point_policy` is `"snap_to_data"` which means the tooltip should position it self always at the "center of mass" of a glyph. If you move your plot so that the bar is partially off screen, but the *center* is visible, you can see this:

<img width="566" alt="screen shot 2017-10-10 at 13 11 43" src="https://user-images.githubusercontent.com/1078448/31402861-e41d819c-adbc-11e7-8dbb-93707717e9ea.png">

If you expect this situation, you can/should set the `point_policy` to `"follow_mouse"`, the the tooltip will always be visible:

<img width="504" alt="screen shot 2017-10-10 at 13 11 56" src="https://user-images.githubusercontent.com/1078448/31402908-11bbe152-adbd-11e7-996d-6edd61b89b28.png">

Here is a  your code, updated:
```
from __future__ import division
from bokeh.plotting import figure, output_file, show
from bokeh.models import Range1d , HoverTool, ColumnDataSource


MyHover1 = HoverTool(
    tooltips=[
        ( 'Parameter', '@Param{%s}'),
        ( 'Parameter Value', '@Value' ),
    ],
    formatters={
        'Param' : 'printf',
        'Value' : 'numeral',
    },
    point_policy="follow_mouse"
)

Plot = figure(title = 'Title', x_axis_label = 'TitleX', y_axis_label = 'TitleY', tools=["pan,wheel_zoom", MyHover1], x_range = Range1d(0, 6), y_range = Range1d(-0.1, 1.1))
Plot.xaxis.major_label_orientation = "vertical"

BarSources = ColumnDataSource(data=dict(Param=[1,2,3,4,5], Value=[0.5,0.6,18,-1,0.3]))
Plot.vbar(x='Param', source = BarSources, width = 0.7, bottom = 0 , top = 'Value', fill_color = 'black', line_color='black')


output_file("foo.html")

show(Plot)
```

**Comment by Jacob-Barhak** [comment]
Thanks Bryan,

This fixed my problem and looks great - much appreciated.

However, you may wish to consider reopening this issue. You see, this has to do with default behavior. By default the user expects their information to display and not be clipped out. If the default policy allows clipping out hover tool information, then perhaps it is not the best.

I am sure you considered visual esthetics when you considered default behavior, yet unless there are counter examples where data is not displayed properly using the follow_mouse policy then it may be a superior default. You may wish to consider replacing the default behavior in one of the next releases.

In any case, the resolution here is sufficient whatever you decide.
