### ISSUE TITLE
User Guide, tweak to "ranges" doc

### ISSUE THREAD

**Issue by tag** [bokeh/bokeh#7042]
### Description of expected behavior and the observed behavior
In the ["User Guide" > "Plotting with Basic Glyphs" > "Setting ranges"](https://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#setting-ranges), it says at the bottom of the section:

> Ranges can also accept a min and max property that allow you to specify the edges of the plot that you do not want the user to be able to pan/zoom beyond.

1. As someone new to Bokeh, this isn't super helpful.
2. This doesn't seem entirely accurate, as I can't find a `min` or `max` property
3. There is no example code.

### Suggested fix
I suggest something like the following, with added links to relevant documentation pages.

> [Ranges](https://bokeh.pydata.org/en/latest/docs/reference/models/ranges.html) can also accept a `bounds` property that allow you to specify the edges of the plot that you do not want the user to be able to pan/zoom beyond. 
> 
> ```
> # set a range using a Range1d
>  p.y_range = Range1d(0, 15, bounds=(0, None))
>  ```

As a suggestion, perhaps moving this code snip and explanation up and combining it with the previous example would make the most sense.

### Two related notes
I'm happy to open these as separate issues, but perhaps they can most easily be solved in the comments here.

1. The [Developer Guide](https://bokeh.pydata.org/en/latest/docs/dev_guide/documentation.html#devguide-documentation) has some instructions for proposing issues and pull requests for what I assume is the [auto-generated documentation](https://bokeh.pydata.org/en/latest/docs/reference.html). However, I cannot find the [User Guide](https://bokeh.pydata.org/en/latest/docs/user_guide.html) in the repository, and thus don't know how to best propose changes to that documentation. Hence this Issue.

2. There isn't a great explanation for the difference between `DataRange1d` and `Range1d` in the [auto-generated documentation](https://bokeh.pydata.org/en/latest/docs/reference/models/ranges.html). It'd be nice to have a sentence explaining the difference. (The answer *is* there, but it requires a bit of textual parsing, and flipping back and forth comparing the two. A simple contrasting sentence would be super helpful.)

**Comment by bryevdv** [comment]
@tag If you would like to submit edits to the docs that would certainly be helpful and appreciated. The small core team is fairly underwater so user contributions are critically important. The Sphinx ReST source files for the user's guide are here:

https://github.com/bokeh/bokeh/tree/master/sphinx/source/docs/user_guide
