### ISSUE TITLE
bokeh server sessions not released correctly

### ISSUE THREAD

**Issue by bjonen** [bokeh/bokeh#7044]
I am running the following on python 2.7, bokeh 0.12.9. 

```
from bokeh.plotting import figure
from bokeh.io import curdoc
from bokeh.layouts import layout

# eating some memory
GB = 1024*1024*1024

# take 500MB
largevar = "a" * int(0.5*GB)

# minimal setup
p = figure()
l = layout([p])
curdoc().add_root(l)
curdoc().title = 'minimal'
```
When I open multiple tabs of this app, each claim 500MB. After closing the tabs the memory consumption remains the same. I am not sure what the timeout is but I have waited at least 10 minutes without any change.

**Comment by bryevdv** [comment]
Adding this line to the end of `Document.destroy_sessions` seems to fix:
```
    def delete_modules(self):
        ''' Clean up sys.modules after the session is destroyed.

        '''
        for module in self._modules:
            if module.__name__ in sys.modules:
                del sys.modules[module.__name__]
        self._modules = None
```
i.e. `destroy_sessions` was deleting from `sys.modules` but `self._modules` was still being retained. This suggests possibly that the document is not being released as well, but this is important enough that it bears making sure everything is deleted here. Leaked modules are much more problematic than leaked documents.

**Comment by bjonen** [comment]
Thanks this fixes the issue on my machine.
