### ISSUE TITLE
Datepicker returns one day earlier than picked in IE

### ISSUE THREAD

**Issue by volkerjaenisch** [bokeh/bokeh#7048]
Using datepicker in FF and IE revelas. The returned date from IE is one day earlier than selected.
Example. Selected is 23.09.2017T00:00:00GMT+2: -> FF 23.09.2017, IE 22.09.2017.
The date.ToISOString() functions behaves differently on FF and IE. In FF only the date part is used -> "22.09.2017". IE takes into account the timezone (in this case Europe/Berlin GMT+2) and shifts the time to UTC before calculating the ISO-String. So 23.09.2017:00:00:00GMT+2 becomes 22.09.2017 22:00:00UTC -> "22.09.2017".
Fix will be to change : 
```
  _on_select: (date) =>
    @model.value = date.toISOString()
    @change_input()
```
to  :
```
  _on_select: (date) =>
    @model.value = date.getFullYear().toString()+'-'+date.getMonth().toString()+'-'+date.getDate().toString() 
    @change_input()
```
If this is OK for everybody then I will prepare a PR

**Comment by bryevdv** [comment]
This seems OK to me but I would suggest a comment with the code to explain the change. @mattpap do you have any other input? Is there any simpler way to accomplish this?

**Comment by volkerjaenisch** [comment]
I would add the text of this issue as a comment in the code. That never ever one will have the idea to change it back. :-)

**Comment by bryevdv** [comment]
a comment link to the issue is probably fine too :)

**Comment by volkerjaenisch** [comment]
Yes, but a few additional lines to explain the issue can
not be wrong.

**Comment by volkerjaenisch** [comment]
My proposed function does not work: date.getMonth is returning 8 for September. This can be coped with by adding +1 but I think this is ugly. And maybe this behavior will change in the future breaking our code. But I found date.getDateString() which returns on FF as well as IE a correct date string. Also this date is parseable by dateutils.

**Comment by bryevdv** [comment]
NOTE: #9509 re-fixes this and many other datepicker issues (as well as adds selenium tests) but note that the implementatoon was switched to Flatpickr, and also now date values can *only* be expressed as ISO date strings, or `datetime.date` and nothing else (in particular no more datetime values which caused endless trouble with time zones)
