### ISSUE TITLE
plotting/file/categorical_scatter_jitter needs a seed

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#7053]
Or it has not to participate in image diff.

**Comment by bryevdv** [comment]
I thought we did some kind of monkey patching to inject a seed for plots that have random elements?

**Comment by mattpap** [comment]
Yes, but that doesn't work for with bokehjs-based jitter. I think there is another example like that doesn't participate in image diff.

**Comment by bryevdv** [comment]
Ah sure. Well if there's not some good way to do it I'd be in favor of adding a section that just recrds a rendered image but does not diff. It's still very valuable (to me) to be able to see that this (and possibly other examples) do render, at a glance in the report, even if there is no diff we can do.

**Comment by mattpap** [comment]
This is why there is a distinction in our examples' tests between not running js (and thus rendering any images) at all, running js but not computing image diff, and doing both.

**Comment by bryevdv** [comment]
>  running js but not computing image diff

How is that accomplished? I will make a PR to do that

**Comment by mattpap** [comment]
> How is that accomplished?

https://github.com/bokeh/bokeh/blob/9d80bbc5cab1d14b04c340f3da206878cc328304/examples/examples.yaml#L18.
