### ISSUE TITLE
Linked brushing does not work on second plot in gridplot

### ISSUE THREAD

**Issue by madmanwithabike** [bokeh/bokeh#7062]
Box selection on either plot should update the selection on the other plot (and does on the left hand plot), however trying to select on the right hand plot will not release the selection box (right click to escape). Same behaviour not seen with the lasso select tool.

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh: 0.12.9, 0.12.10
Python: 3.6.3
Notebook: 5.1.0
OS : Windows 10
browser: chrome, firefox

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
from bokeh.plotting import *
from bokeh.models import (PanTool, WheelZoomTool, BoxZoomTool, ResetTool, BoxSelectTool, LassoSelectTool)

source = ColumnDataSource(
    data=dict(
        time=np.r_[0:10],
        one=np.r_[0:10],
        two=2*np.r_[0:10],
        three=3*np.r_[0:10]
    )
)

TOOLS = [PanTool(),WheelZoomTool(),BoxZoomTool(),ResetTool(),BoxSelectTool(), LassoSelectTool()]

p2 = figure(tools=TOOLS,width=300,height=300)
c2 = p2.circle('time', 'one', source=source,size=4,fill_color='green',line_color=None)
c3 = p2.circle('time', 'two', source=source,size=4,line_color=None)

p3 = figure(tools=TOOLS, width=300, height=300)
c4 = p3.circle('time','three', source=source,size=4, fill_color='firebrick',line_color=None)
p3.x_range = p2.x_range

p = gridplot([[p2,p3]])

show(p)
```
#### Stack traceback and/or browser JavaScript console output

I'm afraid I know very little about JavaScript, but console gives this error whenever mouse released:

bokeh-0.12.9.min.js:2 Uncaught TypeError: Cannot read property 'hit_test' of undefined
    at e.r.SelectionManager.e.select (bokeh-0.12.9.min.js:2)
    at e.r.SelectToolView.e._select (bokeh-0.12.9.min.js:34)
    at e.r.BoxSelectToolView.e._do_select (bokeh-0.12.9.min.js:34)
    at e.r.BoxSelectToolView.e._pan_end (bokeh-0.12.9.min.js:34)
    at e.<anonymous> (bokeh-0.12.9.min.js:2)
    at t.emit (bokeh-0.12.9.min.js:2)
    at t.r.UIEvents.t.trigger (bokeh-0.12.9.min.js:2)
    at t.r.UIEvents.t._trigger (bokeh-0.12.9.min.js:2)
    at t.r.UIEvents.t._pan_end (bokeh-0.12.9.min.js:2)
    at Array.<anonymous> (bokeh-0.12.9.min.js:2)

#### Screenshots or screencasts of the bug in action

![2017-10-17 17_35_59-bokeh plot](https://user-images.githubusercontent.com/32389848/31677394-929bd1e2-b362-11e7-9772-8791e81700f2.png)

**Comment by bryevdv** [comment]
Problem is renderer views getting bad values included:

<img width="377" alt="screen shot 2017-10-17 at 13 01 44" src="https://user-images.githubusercontent.com/1078448/31680976-867f0f4a-b33b-11e7-833e-1a7d1e3c1fb6.png">
And the reason is this code:
```
                   r_views = function () {
                        var j, len, results;
                        results = [];
                        for (j = 0, len = renderers.length; j < len; j++) {
                            r = renderers[j];
                            results.push(this.plot_view.renderer_views[r.id]);
                        }
                        return results;
                    }.call(this);
                    sm.select(r_views, geometry, final, append);
```
`renderers` may contain renderers from different plots, but this code assumes the plot in question will have *all* of them. It should probably just filter/ignore missing values for `this.plot_view.renderer_views[r.id`
