### ISSUE TITLE
Feature Request: Stacktrace on "error handling message" 

### ISSUE THREAD

**Issue by volkerjaenisch** [bokeh/bokeh#7065]
When a python callback fails with an exception one will see a log line like 
```2017-10-18 03:21:44,374 error handling message Message 'PATCH-DOC' (revision 1): AttributeError("'NoneType' object has no attribute 'group'",)```
in the log.
This is not really helpful. I would like to see an additional stacktrace.

**Comment by bryevdv** [comment]
copied response from gitter:

> sure we can try, not sure how much will be able to do, that comes from the websocket hander code. It got a "patch" message from the client, and tried to apply it to the python document, and failed. It's very likely that the stack trace will always be exactly identical in every such case, and not especially useful. A better idea is possibly to try and put more information in the exception message. (e.g. the property name that was attempting to be set, and the model type it was on)

**Comment by mattpap** [comment]
> It's very likely that the stack trace will always be exactly identical in every such case, and not especially useful. 

Any additional information (at last file and line) is always useful. We shouldn't prevent such information if we really don't have a good reason for this (maybe security or something).

**Comment by bryevdv** [comment]
> Any additional information (at last file and line) is always useful. We shouldn't prevent such information if we really don't have a good reason for this (maybe security or something).

It's always going to be the same line. It's not Python code in an app that is triggering this. This message is triggered when an update comes back from the client that can't be applied. Maybe that happened ultimately as a result of some python code called earlier, or maybe a user scrubbed a slider. There is no way to say. There's just an update from the client that failed, and information stops there. The exception will always be in the exact same spot in the handler code.

**Comment by bryevdv** [comment]
So I Iooked more into this, and the very best and only thing we could do is to also log the detailed message contents. But we already do that! You just have to raise the log level to "debug" to see it:

https://github.com/bokeh/bokeh/blob/e2f5a9643c48a6c7a6acfa0530da58e3cd85eed6/bokeh/server/protocol_handler.py#L103
