### ISSUE TITLE
ImportError: cannot import name '_event_for_attribute_change'

### ISSUE THREAD

**Issue by rnsaway** [bokeh/bokeh#7074]
from bokeh.document.util import _event_for_attribute_change
ImportError: cannot import name '_event_for_attribute_change'

source code, bokeh 12.10 imported...

```
'''
import matplotlib as mpl
import holoviews.plotting.bokeh
import holoviews as hv
hv.extension('bokeh')

'''
```

doing this via django...

**Comment by bryevdv** [comment]
HV relied on some private APIs that are changing. You will need to update your HV to the new version.

**Comment by rnsaway** [comment]
i just installed  latest version of hv....??

**Comment by bryevdv** [comment]
Release may be imminent, in any case this is an HV issue, you should raise the issue on their tracker.
