### ISSUE TITLE
Changing Title attributes does not work as expected in Bokeh server

### ISSUE THREAD

**Issue by volkerjaenisch** [bokeh/bokeh#7075]
To reproduce. A title is firstly aligned left. After a change of the user it shall be positioned centred. 
test.py
```
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models.widgets import TextInput
from bokeh.layouts import column

text = TextInput(title="title", value='my sine wave')

p = figure(plot_width=400, plot_height=400, title='Hello')

p.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=10)

p.title.align='left'
                    
# Set up callbacks
def update_title(attrname, old, new):
    p.title.text = text.value
    p.title.align = "center"

text.on_change('value', update_title)

root = column(text, p)
doc = curdoc()
doc.add_root(root)
```
```
bokeh  serve --port=5000 test.py
```
Enter text. The text is aligned at the center, but starting right of the center.
Same holds for font size and probably other parameters.

**Comment by mattpap** [comment]
> The text is aligned at the center, but starting right of the center.

This is fixed in PR #7008.

**Comment by mattpap** [comment]
Otherwise problems with updating title (or layout in general) are covered by other issues (e.g. #6932).

**Comment by volkerjaenisch** [comment]
Sorry, for bothering you with a reiterated issue. I did not find the other issues, related. How to avoid such thing in future. Shall I post the issue in gitter first before publishing it as an issue here?

**Comment by mattpap** [comment]
This isn't a completely reiterated issue. The bug related to centering titles is something new and by coincidence I fixed it earlier today. Otherwise, searching existing issues is the right thing to do before submitting an issue. However, duplicates are unavoidable. I often can't find my own issues on github.

**Comment by volkerjaenisch** [comment]
Thank you for restoring my pride :-)
