### ISSUE TITLE
notebook_url="*" fails in show()

### ISSUE THREAD

**Issue by AbdealiJK** [bokeh/bokeh#7080]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
 - OS - Client is a Mac the server is a RHEL
 - Browser - Chrome 61.0.3163.100
 - Bokeh - 0.12.9
 - Python - 3.5
 - Jupyter notebook - 6.1.0

#### Description of expected behavior and the observed behavior
`notebook_url="*"` does not seem to work. I was expecting that if I use * I would not need to specify the notebook_url at all, but giving * gives me a error in the chrome console.

#### Complete, minimal, self-contained example code that reproduces the issue

I'm running: https://github.com/bokeh/bokeh/blob/e701d301504a258ff447e8a17ddbb09637231fac/examples/howto/server_embed/notebook_embed.ipynb 

#### Stack traceback and/or browser JavaScript console output

When running: `show(app)`, I get the following in JS console:
```
GET http://localhost:44602/autoload.js?bokeh-autoload-element=7694aee3-80ba-4db2-a3ec-3861ae2a5521&bokeh-app-path=/&bokeh-absolute-url=http://localhost:44602 net::ERR_CONNECTION_REFUSED
```
Which is expected as default value is localhost, and I am hosting it on a web server.

When running: `show(app, notebook_url="myip:myport")` (with appropriate values for ip/port it works!

When running: `show(app, notebook_url="*")`, I get the following in JS console:
```
GET http://%2A:37016/autoload.js?bokeh-autoload-element=3a056287-4e60-407c-9134-74a9df5f14d5&bokeh-app-path=/&bokeh-absolute-url=http://*:37016 net::ERR_NAME_NOT_RESOLVED
```
Which is not expected as the docs state:
```
It is also possible to pass ``notebook_url="*"`` to disable the
standard checks, so that applications will display regardless of
the current notebook location
```

**Comment by bryevdv** [comment]
@AbdealiJK in the code above you say you are trying `show(app="*")`, but this is never correct, and not what the docs state. Do you mean `show(app, notebook_url="*")` ? If so, what happens with `notebook_url="*:*"` or `notebook_url="myip:*"` ?

**Comment by bryevdv** [comment]
I've run a majority of examples, the only issues I've run into (neither showstoppers)


toolbars3 seems messed up:

<img width="644" alt="screen shot 2017-10-24 at 19 03 18" src="https://user-images.githubusercontent.com/1078448/31974208-cb90c88a-b8ef-11e7-9f62-e209fb9f642e.png">

sliders overlap plot in dashboard.py (I think this might be an old issue):

<img width="284" alt="screen shot 2017-10-24 at 18 44 32" src="https://user-images.githubusercontent.com/1078448/31974216-e90f3298-b8ef-11e7-8eb9-f2d0284f0b31.png">

**Comment by AbdealiJK** [comment]
Thanks for the replies. You're right I mistyped app="*"
I haven't had a chance to try the variations you mentioned yet. Will be able to test this in a few hours though. The results you're showing in the above message are using which variation?

**Comment by bryevdv** [comment]
@AbdealiJK Sorry, the above comment with images was meant for a different issue (I will delete it)

**Comment by AbdealiJK** [comment]
Here is my report on trying out more things:
### `myip:myport`
Works!

### `myip:*`
Gives warning and error:
```python
bokeh/server/util.py in create_hosts_whitelist(host_list, port)
    119             try:
--> 120                 int(parts[1])
    121             except ValueError:

ValueError: invalid literal for int() with base 10: '*'
```

### `*:myport`
Gives warning and no output/error

### `*:*`
Gives warning and error:
```python
bokeh/server/util.py in create_hosts_whitelist(host_list, port)
    119             try:
--> 120                 int(parts[1])
    121             except ValueError:

ValueError: invalid literal for int() with base 10: '*'
```

### `*`
Gives warning and no output/error

**Comment by bryevdv** [comment]
OK, the proximate problem is that 
```
url = _server_url(notebook_url, server.port)
```
returns things like `http://*:56417/` when `notebook_url="*"`, and then the ultimate problem is that we are trying to use `notebook_url` both to specify the server URL, and the allowed origin and I'm not sure that's feasible. In general I am not sure there's a robust way to make it work without just needing the specify the complete URL, the jupyter folks are not willing to provide a supported API for obtaining the notebook URL, and there's nothing we can do about that (see, e.g. https://groups.google.com/forum/#!topic/jupyter/7tQOGKqeov8).  My inclination at this point is simply to remove that line from the docs.

**Comment by bryevdv** [comment]
@AbdealiJK I am sorry there is not a better resolution to this. Please feel free to lobby the Jupyter devs to relax their position on this matter, we would love to be able to provide a better user experience.
