### ISSUE TITLE
User guide still refers to bokeh.embed.notebook_div

### ISSUE THREAD

**Issue by ceball** [bokeh/bokeh#7081]
https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/embed.rst still refers to `from bokeh.embed import notebook_div`. This is out of date, right? If so, I'd be happy to try to update these docs while I update some code in another project to 0.12.10.

<img width="1284" alt="screen shot 2017-10-20 at 9 08 35 pm" src="https://user-images.githubusercontent.com/1929/31839875-e396ce60-b5da-11e7-8a96-70dc8996bba5.png">

**Comment by bryevdv** [comment]
@ceball can you make a PR to delete and/or mention `notebook_content` instead?
