### ISSUE TITLE
FactorRange regression: plot does not get updated when factors change.

### ISSUE THREAD

**Issue by lukauskas** [bokeh/bokeh#7083]
#### Software version info (bokeh, python, notebook, OS, browser, any other relevant packages):

Bokeh (affected) 0.12.10, 0.12.9, 0.12.7, 0.12.10rc2 
Bokeh (working as expected): 0.12.6

OS: docker image [lukauskas/bokeh](https://hub.docker.com/r/lukauskas/bokeh/)
Python: 3.6

Browser: Chrome 61.0.3163.100 

#### Description of expected behavior and the observed behavior

Since 0.12.7 onwards, when updating factors of a FactorRange, the plot does not get updated any more.

In the example below, I create a plot with a factor x axis containing factors ['a', 'b', 'c'].
This plot has a circle drawn at the location x='a', y=1.
When the button is pressed, the factors on the axis are changed to ['d', 'c', 'b', 'a'].
I would expect the circle to move within the image to the new location of the factor 'a'.
Instead, the circle stays in the same position, but the factors update. So now the circle is effectively at the location x='d', y=1.

#### Complete, minimal, self-contained example code that reproduces the issue

Here's the code for a minimal example to reproduce it (run it via `bokeh serve`).

```
from bokeh.models import FactorRange, Button
from bokeh.plotting import figure, curdoc
from bokeh.layouts import layout

button = Button()
x_range = FactorRange(factors=['a', 'b', 'c'])
fig = figure(x_range=x_range)
fig.circle(['a'], [1], size=20, color='navy')

def change_range():
    print('Changing range')
    x_range.factors = ['d', 'c', 'b', 'a']

button.on_click(change_range)

l = layout([[button],
            [fig]]
)
curdoc().add_root(l)
```

If you paste this code to a file `app/main.py` then you can use the following `Dockerfile` to reproduce everything:

```
ARG VERSION=0.12.10
FROM lukauskas/bokeh:${VERSION}
COPY ./app /app
```

To run it:
```
docker build --build-arg VERSION="0.12.10" -t bokeh .
docker run --rm -p 5100:5100 --name bokeh_cont bokeh
```

Access the plot at `http://127.0.0.1:5100`.
Replace the version number if needed.

#### Screenshots or screencasts of the bug in action

After button click in 0.12.10: 

![image](https://user-images.githubusercontent.com/108413/31863698-8959e464-b751-11e7-8993-91b1b8ab169f.png)

After button click in 0.12.6 (expected behaviour):

![image](https://user-images.githubusercontent.com/108413/31863709-b93a90c0-b751-11e7-9332-11792a1b5c5b.png)

**Comment by bryevdv** [comment]
Categorical support was reworked from the ground up in `0.12.7`. Many long standing problems and missing features were addressed but some broken eggs were probably inevitable too. My immediate guess is that the even to the range to trigger a recompute of the mapping is happening too late, after the plot redraw.

**Comment by lukauskas** [comment]
I am not sure where it fails. It almost looks like mapping is not recomputed at all to me.

As a workaround, I found that updating the source after changing of the factors allows the plot to be drawn correctly.

```python
from bokeh.models import FactorRange, Button, ColumnDataSource
from bokeh.plotting import figure, curdoc
from bokeh.layouts import layout

button = Button()
x_range = FactorRange(factors=['a', 'b', 'c'])
fig = figure(x_range=x_range)
data = dict(x=['a'], y=[2])
source = ColumnDataSource(data=data)
fig.circle(x='x', y='y', size=20, color='navy', source=source)

def change_range():
    print('Changing rage')
    x_range.factors = ['d', 'c', 'b', 'a']

    # Trigger source update. Workaround for Isue #7083
    source.data = source.data


button.on_click(change_range)

l = layout([[button],
            [fig]]
)
curdoc().add_root(l)
```

**Comment by bryevdv** [comment]
@mattpap (built on #7363) this fixes the problem, do you agree?
```
diff --git a/bokehjs/src/coffee/models/ranges/factor_range.ts b/bokehjs/src/coffee/models/ranges/factor_range.ts
index a196fc510..570a76550 100644
--- a/bokehjs/src/coffee/models/ranges/factor_range.ts
+++ b/bokehjs/src/coffee/models/ranges/factor_range.ts
@@ -128,12 +128,12 @@ export class FactorRange extends Range {
   initialize(attrs: any, options: any): void {
     super.initialize(attrs, options)
     this._init()
-    this.connect(this.properties.factors.change, () => this._init())
-    this.connect(this.properties.factor_padding.change, () => this._init())
-    this.connect(this.properties.group_padding.change, () => this._init())
-    this.connect(this.properties.subgroup_padding.change, () => this._init())
-    this.connect(this.properties.range_padding.change, () => this._init())
-    this.connect(this.properties.range_padding_units.change, () => this._init())
+    this.connect(this.properties.factors.change, () => this.reset())
+    this.connect(this.properties.factor_padding.change, () => this.reset())
+    this.connect(this.properties.group_padding.change, () => this.reset())
+    this.connect(this.properties.subgroup_padding.change, () => this.reset())
+    this.connect(this.properties.range_padding.change, () => this.reset())
+    this.connect(this.properties.range_padding_units.change, () => this.reset())
   }

   reset(): void {
diff --git a/bokehjs/src/coffee/models/renderers/glyph_renderer.coffee b/bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
index 7d7ab76c2..49da451e5 100644
--- a/bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
+++ b/bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
@@ -75,6 +75,12 @@ export class GlyphRendererView extends RendererView
     @connect(@model.properties.view.change, () -> @set_data())
     @connect(@model.view.change, () -> @set_data())

+    for name, rng of @plot_model.frame.x_ranges
+      @connect(rng.change, () -> @set_data())
+
+    for name, rng of @plot_model.frame.y_ranges
+      @connect(rng.change, () -> @set_data())
+
     @connect(@model.glyph.transformchange, () -> @set_data())

   have_selection_glyphs: () -> @selection_glyph? && @nonselection_glyph?
```
The change to `reset` from `_init` in range signal handlers causes a `range.change` to be emitted. But this is also not sufficient, as that only triggers a `request_redraw` and not a data re-mapping. The loops in the glyph add that.

**Comment by mattpap** [comment]
> this fixes the problem, do you agree?

I have no idea right now. I need to familiarize myself with this code.

**Comment by bryevdv** [comment]
I guess a better question is: "is there a better way to trigger a `set_data` on a glyph renderer from a range change. This seems OK so I will probably add it to the linked PR in a separate commit
