### ISSUE TITLE
datepicker position varies if <div bk-root> is embedded 

### ISSUE THREAD

**Issue by volkerjaenisch** [bokeh/bokeh#7092]
We noticed that the datepicker calendar "jumps away" from the datepicker widget if the bokeh site is embedded elsewhere. We checked that this is no CSS collision.
The cause is the defective calculation of the absolute position of the calendar widget by bokeh in datepicker.coffee. This calculation uses the bk-root-DIV as reference point, not taking into account that the position of the bk-root-DIV may not be to located at <0:0> coordinates.

I would like to fix this. But I have some questions to the makers first:

- I suppose all this fiddling with absolute position is to avoid that the calendar does not pop up at a place out of the current viewport. E.G. if the datepicker widget is near the edge. If this is not the case a relative positioning would be quite easier and more robust.
-  If the former defined use case is truly important I do not understand:
    - Why not use a JS lib like Keep-in-View to accomplish the task?
    - If JS libs are a no go (to keep the codebase small and the dependencies low), why not pin the 
calender to the viewport instead.

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by bryevdv** [comment]
@volkerjaenisch I'm making a concerted effort to close issues that are not presently actionable, i.e. fo do not have a reproducer provider. I would be happy to re-open this if you can provide a test script to reproduce the problem
