### ISSUE TITLE
broken DataTable SelectEditor

### ISSUE THREAD

**Issue by chupach** [bokeh/bokeh#7101]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by chupach** [comment]
at some point between 0.11 and 0.12 / 0.12.10rc2, SelectEditor stopped presenting the options in DataTable (true for ff,safari,chrome).
Here below the code illustrating the failure (double click on right column fails to present the options)

JS console error when double click:
TypeError: undefined is not an object (evaluating 'n.length')

There is also a strange message in the console coming at first:
"jquery-ui is required to enable DataTable.reorderable"


from bokeh.layouts import widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, SelectEditor
from bokeh.plotting import curdoc

doc = curdoc()
s = ColumnDataSource(data=dict(x=['a','b']))
columns = [TableColumn(field="x", title="x", editor=SelectEditor(options=['a','b','c']))]
table = DataTable(source=s, columns=columns, row_headers=False,editable=True,selectable=True)

box = widgetbox(table)
doc.add_root(box)

**Comment by bryevdv** [comment]
@chupach That's nearly a two year window between 0.11 and now. If you can narrow things down it would be an immense help.

**Comment by bryevdv** [comment]
@mattpap the issue happens here:

<img width="475" alt="screen shot 2017-10-26 at 12 26 11" src="https://user-images.githubusercontent.com/1078448/32067458-e9edef42-ba48-11e7-85e1-1c782b535b34.png">

and the problem seems to be that `this.model` does not actually refer the model:

<img width="494" alt="screen shot 2017-10-26 at 12 26 17" src="https://user-images.githubusercontent.com/1078448/32067469-f4d27acc-ba48-11e7-8c52-0b348fbe9e2c.png">

Any ideas?

**Comment by mattpap** [comment]
This was likely introduced when SlickGrid was updated (~0.12.6). `this.model` is maintained in a different way in cell editors than in other models, so this is likely the reason why this doesn't work.

**Comment by ongietorri** [comment]
hi,
I too face an error which may related to this issue:
* Bokeh 0.12.10: double click on editable datatable cell: OK
* Bokeh 0.12.11: double click on editable datatable cell: KO. Cell is left blank and the inner text has disappeared.

**Comment by ongietorri** [comment]
here's a minimal example:

    from bokeh.io import output_notebook, show
    from bokeh.models.widgets.tables import DataTable
    from bokeh.models import ColumnDataSource, TableColumn
    output_notebook()

    d = {"one" : [1,2,3], 'two': [4,5,6]}
    ds = ColumnDataSource(d)

    columns = [ TableColumn(field="one", title="A"),  TableColumn(field="two", title="B"), ]
    dt = DataTable(source=ds, columns = columns, editable = True)
    show(dt)

Any chance this bug gets resolved in the next release? It's quite important imo, as it prevents the user from being able to copy text from a cell...

Thanks

**Comment by bryevdv** [comment]
This is fixed in master, probably by https://github.com/bokeh/bokeh/pull/7347

<img width="616" alt="screen shot 2018-02-05 at 08 13 56" src="https://user-images.githubusercontent.com/1078448/35808803-a22496a8-0a4c-11e8-95eb-d13c7ec13ce2.png">
