### ISSUE TITLE
bokeh channel version of nodejs is no longer in sync with upstream anaconda/nodejs

### ISSUE THREAD

**Issue by memetb** [bokeh/bokeh#7104]
At present this is impeding compilation of custom bokeh extensions due to a version check @ https://github.com/bokeh/bokeh/blob/master/bokeh/util/compiler.py#L142

Also probably a good idea in the long term not to let versions diverge too much.

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by mattpap** [comment]
`defaults` contain the correct version. `bokeh` channel lags behind. I think we should just point to `defaults` and update the error message to `(...) npm install nodejs (...)`.
