### ISSUE TITLE
Slider does not display values when end is far

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#7111]
This was not an issue with 0.12.6.
I have a slider with 2000 elements (I know). The slider cannot display all the elements. 1 ok, then the next one is 7 and on. It seems to jump 7 at a time. With a 1000 it jumps by 3. 500, it jumps by 2.

I am using 0.12.10

```
    def test311():
        from bokeh.models import Slider
        divtest = Div(
            text="""test test test test """,
            width=200)

        slider = Slider(start=1, end=2000, value=2000, step=1, title="SLIDER")
        wdgsld = WidgetBox(slider)
        l0 = column([divtest,wdgsld])
        # output_file("test0.html",title='0')
        tab0 = Panel(child=l0, title='0')
        tabs = Tabs(tabs=([tab0]))
        show(tabs)

```

**Comment by bryevdv** [comment]
@Pierretherenard The underlying slider implementation changed completely in 0.12.7 from a JQ based slider to NoUISlider which has many benefits unavailable in the JQ slider. I am sure this explains any behavior differences. However, I am not sure what you mean by "working" previously: Unless you have 2000 pixels to accommodate all 2000 values, then I don't see how did scrubbing the slider by one pixel would ever be able to avoid jumping by some larger increment.

**Comment by Pierretherenard** [comment]
It is working on my site and you can see all 2276 elements using the arrow keys on the slider. I will use the NoUISlider from now on. Thank you

**Comment by bryevdv** [comment]
You haven't provided a link to the site, so I can't view it to understand what you mean by "working". Do you mean full navigation of the slider values was possible, but only by using the arrow keys? If so, that's a different statement, and adding in arrow support to the new slider implementation is something that could be considered.

**Comment by Pierretherenard** [comment]
My bad, you are right even with 0.12.6 the full navigation could only be done with the arrow keys. I think this was discussed before. Yes this will be great if the arrow keys can come back.

**Comment by bryevdv** [comment]
arrow keys support was added since this discussion
