### ISSUE TITLE
rendering issues after resizing network graph

### ISSUE THREAD

**Issue by gryBox** [bokeh/bokeh#7119]
Hi,

The issue: `bokeh 12.1` does not render a network graph correctly after resizing.   **This only occurs on (large?) graphs**.  Do you think it depends on hardware? 

### Original:
![image](https://user-images.githubusercontent.com/16763201/32116204-4c8f37c0-bb0f-11e7-90c3-3691eca3e95e.png)

### Error:

![image](https://user-images.githubusercontent.com/16763201/32116158-1d7e15d2-bb0f-11e7-8dec-f52b9679f03f.png)

Steps I took:

1. A couple of `Box Zooms`
2. A couple of 'Pans`
3. And finally a `resize`

**Comment by bryevdv** [comment]
@gryBox without a minimal complete script that reproduces the issue, it's not possible to investigate.

**Comment by gryBox** [comment]
@bryevdv Fair enough,  I will put something together.

**Comment by gryBox** [comment]
@bryevdv I am closing this.  It's just noise that might get corrected with other fixes going on.
