### ISSUE TITLE
DataTable in Tab not displaying contents (with minimal example)

### ISSUE THREAD

**Issue by alexspili** [bokeh/bokeh#7120]
Bokeh 0.12.10
Python 2.7.13 :: Anaconda custom (x86_64)
No terminal or JS console errors
Mentioned in #6794 and may be related to #6925, but I have tried to remove all confounding factors in the minimal example that follows.

*Bug#1:*
DataTable contents inside a tab *sometimes* do not show up until the user scrolls down.
It happens when:
-	The number of rows exceeds the table height
-	**AND** the table is embedded in tab#2 or greater
Note that the vertical scrollbar displays correctly even when the rows do not.

*Bug#2* (possibly related to Bug#1):
The horizontal scrollbar appears when you start scrolling (although I think it shouldn’t) and hides the last row. Switching back and forth between tabs will make it disappear until you scroll again.

**TO VIEW:** 
[Minimal example live demo](http://34.209.204.254:5006/test_tab_tables)

**TO REPRODUCE:**
```
# bokeh serve --show test_tab_tables.py
from bokeh.io import curdoc
from bokeh.layouts import row
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Panel, Tabs

source_A = ColumnDataSource( dict(numbers=range(10)) )
columns_A = [ TableColumn(field="numbers", title="numbers") ]
data_table_A1 = DataTable(source=source_A, columns=columns_A,  reorderable=False, width=200, height=300)
data_table_A2 = DataTable(source=source_A, columns=columns_A,  reorderable=False, width=200, height=300)

tab_A1 = Panel(child=data_table_A1, title="works OK")
tab_A2 = Panel(child=data_table_A2, title="works OK too")
tabs_A = Tabs(tabs=[ tab_A1, tab_A2 ], width=500)

# The following tabs and tables are identical to the previous, except for the number of rows
source_B = ColumnDataSource( dict(numbers=range(50)) )
columns_B = [ TableColumn(field="numbers", title="numbers") ]
data_table_B1 = DataTable(source=source_B, columns=columns_B,  reorderable=False, width=200, height=300)
data_table_B2 = DataTable(source=source_B, columns=columns_B,  reorderable=False, width=200, height=300)

tab_B1 = Panel(child=data_table_B1, title="works OK")
tab_B2 = Panel(child=data_table_B2, title="needs scrolling first!")
tabs_B = Tabs(tabs=[ tab_B1, tab_B2 ], width=500)

curdoc().add_root(row(tabs_A, tabs_B))
```

**Comment by zaript** [comment]
I have encountered this bug. In two tabs I have two tables created from same dataframe, but using different sources. Table in the tab, that is active by default, is visible. When I open second tab, the table is empty until I scroll downs.

**Comment by cutright** [comment]
Issue persists in 0.12.11

**Comment by codeape2** [comment]
Reproduced in Jupyter notebook: https://notebooks.azure.com/anon-kjzgba/libraries/bokeh-examples (bokeh_issue_7120.ipynb)

**Comment by pmicheletty** [comment]
+1 for this. I have the same issues with data not appearing until you scroll as well as a hidden last row when tables exceed the height dimension. Also using tabbed panels, windows 10, and google chrome (although I have tested with other web browsers with the same effect).

**Comment by iamnancy07** [comment]
+1. Using bokeh 0.12.11 on windows 10, google chrome, can not display the last row and I am not using tab. Also a separate but related issue is how to display the top result instead of bottom result with scroll bar at the bottom.

Thanks!

**Comment by jimbasquiat** [comment]
Same here "can not display the last row and I am not using tab"

**Comment by u98106** [comment]
I see a similar issue after updating the source of the DataTable post a filter. On scrolling or sorting the filtered out table, the table rendering suddenly disappears. My setup: bokeh: 0.13.0. Running inside Jupyter. Filtering with multiselect's. Re-assigning to table.source on a button.on_click. Would be happy to learn any update plan. Thanks.

**Comment by bryevdv** [comment]
results with #8085 

<img width="470" alt="screen shot 2019-01-30 at 19 05 35" src="https://user-images.githubusercontent.com/1078448/52027963-0ead3b00-24c2-11e9-9952-7884c3503695.png">
