### ISSUE TITLE
cannot import name CDSView

### ISSUE THREAD

**Issue by wochner** [bokeh/bokeh#7123]
from bokeh.models import CDSView

produces error "Import error: cannot import name CDSView."

Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32

Bokeh Version 0.12.10

**Comment by bryevdv** [comment]
You have a local installation problem of some kind. If you are using ipython or the notebook, perhaps you installed Bokeh into a different conda or venv environment than you intended.
```
In [1]: import bokeh

In [2]: bokeh.__version__
Out[2]: '0.12.10'

In [3]: from bokeh.models import CDSView

In [4]:
```
