### ISSUE TITLE
vertical slider

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#7127]
I tried the orientation="vertical" for the slider but it doesn't work, whatever the size of the height for the widgetbox. I tried as well without the tab for the same result.

0.12.10, python 3.5

#### Complete, minimal, self-contained example code that reproduces the issue

```
    def test311():
        from bokeh.models import Slider
        divtest = Div(
            text="""test test test test """,
            width=200)

        slider = Slider(start=1, end=1000, value=1, step=1, title="SLIDER ")
        slider2 = Slider(start=1, end=100, value=100, step=1, title="SLIDER 1", orientation="vertical")
        wdgsld = WidgetBox(slider, width=1000)
        wdgsld1 = WidgetBox(slider2, height=100)
        l0 = column([divtest,wdgsld,wdgsld1])
        # output_file("test0.html",title='0')
        tab0 = Panel(child=l0, title='0')
        tabs = Tabs(tabs=([tab0]))
        show(tabs)

```

#### Screenshots or screencasts of the bug in action
![screen shot 2017-10-29 at 9 39 28 pm](https://user-images.githubusercontent.com/23002446/32154967-b16da62a-bcf1-11e7-9f54-48a974f4540b.png)

**Comment by bryevdv** [comment]
@Pierretherenard can you update your code to be a complete, standalone script than we can just run as-is?

**Comment by bryevdv** [comment]
Also `examples/models/file/sliders.py` is working for me: 

<img width="508" alt="screen shot 2017-10-31 at 09 09 25" src="https://user-images.githubusercontent.com/1078448/32228077-408f1198-be1b-11e7-9e4c-3d9d00500fb2.png">

So in addition to a complete script, more information about your browser and platform is needed.

**Comment by mattpap** [comment]
`models/file/sliders` works only because there is the left column which contributes to overall layout height, thus slider height. Rendering vertical sliders broken pretty much in all other scenarios.

**Comment by bryevdv** [comment]
OK, it was not evident that example relied on coincidental things to function.

**Comment by mattpap** [comment]
> OK, it was not evident that example relied on coincidental things to function.

I didn't know my self before this issue.

**Comment by andy3andy33** [comment]
i faced similar problem, but it was solved after i specify the height.

**Comment by alaindebecker** [comment]
`examples/models/file/sliders.py` is working any more as of 2020-10-02.
(FireFox, Edge, Chrome)

![image](https://user-images.githubusercontent.com/2980348/94912520-1186dd00-04a8-11eb-8edf-a3224fb379a5.png)

**Comment by mattpap** [comment]
There's an open issue #10444 regarding this.
