### ISSUE TITLE
When embeding bokeh server to flask, AttributeError: 'NoneType' object has no attribute '_id' shows up

### ISSUE THREAD

**Issue by bigmoumou** [bokeh/bokeh#7128]
I just want to embed the bokeh server into flask

I tried the following simple example but just cannot understand what's going on...

(python version = 2.7.12)
(bokeh version = 0.12.10)
(flask version = 0.12.2)

app.py
```
from flask import Flask, render_template
from bokeh.embed import autoload_server
from bokeh.client import pull_session

app = Flask(__name__)

@app.route("/")

def index():
	session = pull_session(url="http://localhost:5006/test_for_animation")
	bokeh_script = autoload_server(None, url="http://localhost:5006/test_for_animation", session_id=session.id)
	return render_template("index.html", bokeh_script=bokeh_script)

if __name__ == "__main__":
	app.run(debug=True)
```

test_for_animation.py
```
from bokeh.models import HoverTool, CrosshairTool, ColumnDataSource
from bokeh.layouts import widgetbox, row
from bokeh.plotting import figure, curdoc
from bokeh.models.widgets import TextInput, Button
from random import randrange

f=figure(x_range=(0,11), y_range=(0,11))
source = ColumnDataSource(data=dict(x=[], y=[]))
f.circle(x="x", y="y", size=8, color="olive", source=source)

def update():
	new_data = dict(x=[randrange(1,10)], y=[randrange(1,10)])
	source.stream(new_data, rollover=15)
	print(source.data)

curdoc().add_root(f)
curdoc().add_periodic_callback(update, 1000)
```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
<body>
	<h3>I am a heading</h3>
	<div>
		{{bokeh_script|safe}}
	</div>
	<h3>I am a footer</h3>
</body>
</html>
```

The error is

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 291-452-623
/usr/local/lib/python2.7/dist-packages/bokeh/util/deprecation.py:34: BokehDeprecationWarning: bokeh.embed.autoload_server was deprecated in Bokeh 0.12.7 and will be removed, use bokeh.embed.server_document or bokeh.embed.server_session instead.
  warn(message)
127.0.0.1 - - [30/Oct/2017 12:57:09] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Oct/2017 12:57:09] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bigmoumou/Desktop/python/bokeh/tutorial/animation/app.py", line 10, in index
    bokeh_script = autoload_server(None, url="http://localhost:5006/test_for_animation", session_id=session.id)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/embed/__init__.py", line 62, in autoload_server
    return server_session(model, session_id, url, relative_urls, "default", arguments)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/util/api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/embed/server.py", line 188, in server_session
    modelid   = model._id,
AttributeError: 'NoneType' object has no attribute '_id'

**Comment by bryevdv** [comment]
This is a regression from `0.12.9` that happened during the refactoring that split up `embed.py`. The case where `model` is `None` is no longer correctly handled, it should pass the empty string to the template if `model` is `None`. 

Thanks or the report @bigmoumou

**Comment by bryevdv** [comment]
@bigmoumou This was fixed i #7133 and will be part of the upcoming `0.12.11` release. In the mean time, you can use `0.12.9` or pass a model instead of `None` (i.e. a document root perhaps)

Please not, you shoudl not use `autoload_server`. As the log output indicates, it is deprecated and *will be removed* prior to a 1.0 release. Use `server_session` (or `server_document` if you don't need to do any session customization)

**Comment by bigmoumou** [comment]
Is there any example about embedding bokeh-server to flask for the newest bokeh version 0.12.10 or 0.12.9?  Because even can I find many good examples in 2017, most of these examples cannot work now, especially many of them use the `autoload_server` which is going to be removed in the future. If there is any example step-by-step like this one (which is not work now): [https://gist.github.com/Wildcarde/6841f00f0a0cd52ade09964a0fdb5684] will be really helpful ! I really wants to embed these cool bokeh animations into my personal website :)

**Comment by bryevdv** [comment]
The code in the linked PR is a simple example of such.

**Comment by bigmoumou** [comment]
Thanks for the code, but there is another problem happen.

(python version = 2.7.12)
(bokeh version = **0.12.9**)   <-   now I go back to the version 0.12.9 
(flask version = 0.12.2)

First, I run the command `bokeh serve test_for_animation.py --allow-websocket-origin=localhost:8080` as the PR said. 
Then run the `python app.py`
Both bokeh-server and app.py work well, but when I go to http://127.0.0.1:8080/
there is another error on the website console:
```
connection.js:54 WebSocket connection to 'ws://localhost:5006/test_for_animation/ws?bokeh-protocol-version=1.0&bokeh-session-id=M2ZOQVSFjOUJSkg5OvZiq80bcKpJGgFLGkJhVKNXTesy' failed: Error during WebSocket handshake: Unexpected response code: 403

[bokeh] Failed to connect to Bokeh server Error: Could not open websocket
```

app.py
```
from flask import Flask, render_template
from bokeh.client import pull_session
from bokeh.embed import server_session
app = Flask(__name__)

@app.route('/', methods=['GET'])
def bkapp_page():
    session = pull_session(url="http://localhost:5006/test_for_animation")
    script = server_session(None, session.id, url='http://localhost:5006/test_for_animation')
    return render_template("index.html", script=script)

if __name__ == '__main__':
    app.run(port=8080, debug=True)
```
test_for_animation.py
```
from bokeh.models import HoverTool, CrosshairTool, ColumnDataSource
from bokeh.layouts import widgetbox, row
from bokeh.plotting import figure, curdoc
from bokeh.models.widgets import TextInput, Button
from random import randrange

f=figure(x_range=(0,11), y_range=(0,11))
source = ColumnDataSource(data=dict(x=[], y=[]))
f.circle(x="x", y="y", size=8, color="olive", source=source)

def update():
	new_data = dict(x=[randrange(1,10)], y=[randrange(1,10)])
	source.stream(new_data, rollover=15)
	print(source.data)

curdoc().add_root(f)
curdoc().add_periodic_callback(update, 1000)
```

index,html
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
<body>
	<h3>I am a heading</h3>
	<div>
		{{script|safe}}
	</div>
	<h3>I am a footer</h3>
</body>
</html>
```

**Comment by bryevdv** [comment]
The code above works fine for me. Are you using a version of safari older than the most recent? Until recently here was a bug in webkit that caused websockets to fail. Many other people and projects were bitten by this bug. But it It's an upstream problem we have zero control over, there's no remedy I can suggest except to make sure you have the newest safari (or use chrome or firefox)

**Comment by bryevdv** [comment]
For reference it is working for me with safari Version 11.0 (13604.1.38.1.6)

**Comment by bigmoumou** [comment]
My OS is Ubuntu 16.04 and I'm using Google Chrome 62.0.3202.75. 
l will open a new issue ! 

Really thanks a lot !

**Comment by clemy83** [comment]
Hello Folks,

I am unable to Embedding Bokeh server plots in Flask

I modified the code to workaround the deprecated function "autoload_server". I am now using the function "server_session". But this also fails to render the chart on the browser. The error message is as follows(in bold):

**WebSocket connection to 'ws://localhost:5006/random_generator/ws?bokeh-protocol-version=1.0&bokeh-session-id=cPBINc6PtO6YHf3mFISMwj4XEsTeB0gLWRVibSmM39Ju' failed: Error during WebSocket handshake: Unexpected response code: 403

[bokeh] Failed to connect to Bokeh server Error: Could not open websocket**

I am working on Ubuntu 18.04, Python 3.6, Bokeh (0.13.0), Google Chrome - Version 67.0.3396.99, Firefox - 60.0.2 (64-bit)

Is there a workaround for this issue?

thank you in advance for your comments :-)

**Comment by bryevdv** [comment]
@clemy83 403 is a "permission denied" error code, so I this seems like a configuration/usage support question. As such I's ask that further discussion happen on the  mailing list and not the tracker unless we can identify a bug or other issue that requires dev action. https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by clemy83** [comment]
Hey thank you for the reply. I played around a bit and I think I sorted out the "permission denied" error. 
However I am getting the following error now:

**Error:**
Firefox can’t establish a connection to the server at ws://localhost:5006/random_generator/ws?bokeh-protocol-version=1.0&bokeh-session-id=afl5ZCoUi6xySziZWGF3SFSHfL6KXigCVL9V1iezdPsA. connection.js:58 
[bokeh] Failed to connect to Bokeh server Error: Could not open websocket


**Code**
#####################################################################
##random_generator.py
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from random import randrange

f=figure(x_range=(0,11), y_range=(0,11))

source = ColumnDataSource(data=dict(x=[],y=[]))

f.circle(x='x',y='y', size=8, fill_color='olive', line_color='yellow', source=source)

def update():
   new_data= dict(x=[randrange(1,10)],y=[randrange(1,10)])
   source.stream(new_data, rollover=15)
   print(source.data)

curdoc().add_root(f)
curdoc().add_periodic_callback(update, 1000)
##############################################################

##app.py
from flask import Flask, render_template
from bokeh.embed import server_document, server_session
from bokeh.client import pull_session
# instantiate flask app
app = Flask(__name__)
# Create inddex page function
@app.route("/")
def index():
   session = pull_session(url="http://localhost:5006/random_generator")
   bokeh_script=server_session(model=None, url="http://localhost:5006/random_generator",session_id=session.id)
   return render_template("index.html",bokeh_script=bokeh_script)
# run the app
if __name__ == "__main__":
   app.run(debug=True)
##############################################################

##index.html
<!DOCTYPE html>
<html lang="en">
   <head>
     <meta charset="utf-8">
     <title> I am a tittle</title>
     <link rel="stylesheet" href={{url_for('static', filename='css/main.css')}}/>
   </head>
   <body>
        <h3>I am a heading</h3>
        <div>
          {{bokeh_script|safe}}
        </div>
        <p> I am a paragraph </p>
   </body>
</html>
##############################################################

#main.css

h3 {
color : olive;
}
##############################################################

**Folder structure**
BokehProject ---> Static --->main.css
                      ---->Templates --->index.html
                      ----> app.py
                      ----->random_generator.py
##############################################################
**Command used for running the app**

1. Bokeh server random_generator.py --allow-web-socket-origin = localhost:5006
2. python3 app.py

##############################################################
**Environment details**
Ubuntu 18.04, Python 3.6, Bokeh (0.13.0), Google Chrome - Version 67.0.3396.99, Firefox - 60.0.2 (64-bit)

##############################################################
**Observations**
1. The bokeh chart is rendered as expected when directly connecting to Bokeh server
2. The Flask application is launched but the Bokeh plot is not rendered
2. The error is consistent in both google and Firefox browsers
3. The error was reproduced in two different machines(a VM and a standalone machine) of same configuration. 

##############################################################

NOTE: I was not sure if  this update had to go into the mailing list as suggested. Please advice.

**Comment by selvamaran** [comment]
Bokeh server random_generator.py --allow-web-socket-origin = localhost:5006
use: 127.0.0.1.5000 or  127.0.0.1.5006 instead of  localhost:5006
