### ISSUE TITLE
Allow update of DataTable headers

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#7129]
Currently you can update the columns of a DataTable but cannot update the headers. It would be nice to be able to update the headers. A use case is when using a dropdown to select what data to show in a plot and updating a DataTable to show details. Currently you have to use a Div and update with HTML generated from the selected data.

**Comment by hsparra** [comment]
The table headers can be updated by creating new TableColumns and replacing the "old" table columns. Something like:

```
 # Update Data Column Titles by creating new columns
new_x_col = TableColumn(field= 'xs', title = xs_column.title)
new_y_col = TableColumn(field= 'ys', title = ys_column.title)
data_table.columns[0] = new_x_col
data_table.columns[1] = new_y_col
```

**Comment by bryevdv** [comment]
OK I'd regard that as expected behavior, so I will close this.
