### ISSUE TITLE
Adding legends through the JS interface

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#713]
There seems to be no way to specify proper legend titles for multiple lines through the js plotting interface.

https://github.com/ContinuumIO/bokeh/blob/master/bokehjs/src/coffee/common/plotting.coffee#L242

I think it makes most sense to add a "legend_text" property to each renderer.  Otherwise you have to have js code get references to actual renderer objects.

**Comment by mattpap** [comment]
This is actually possible with the new bokehjs' plotting API. Fixed in #4037.
