### ISSUE TITLE
[BokekJS] Unable to use CustomJS in BokehJS

### ISSUE THREAD

**Issue by Astrum42** [bokeh/bokeh#7130]
Trying to port a custom callback on x_range from Bokeh to BokehJS, I made 3 attempts that are documented from line 35 to line 40.
I can't figure out whether CustomJS is not working as expected or whether it shall not be used in BokehJS (which would make sense).
Maybe this issue can be resolved simply by documentation update, or maybe there is a bug to fix.
Thanks for having a look!
Cheers,
A.

```
<!DOCTYPE html>
<html style="width:97%; height:97%;">
<head>
	<link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.10.css" type="text/css" />
	<script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.10.js"></script>
	<script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-api-0.12.10.js"></script>
	<!-- The order of CSS and JS imports above is important. -->
	
</head>
<body style="width:100%; height:100%;">
	<div id="myPlot">
	</div>
	<script type="text/javascript">
	// data to plot
	var source = new Bokeh.ColumnDataSource({
		data: { x: [0,1,2,3,4,5,6,7,8,9], y: [0,1,4,-2,2,5,0,2,1,1] }
	});

	// make the plot and add some tools
	var tools = "pan,crosshair,wheel_zoom,box_zoom,reset,save";

	var plot = Bokeh.Plotting.figure({
		title:"demo plot",
		tools: tools,
		toolbar_location:"above",
		sizing_mode:"stretch_both"
	});
	//sizing_mode:"stretch_both"
	
	var scatterData = plot.line({ field: "x" }, { field: "y" }, {
		source: source,
		line_width: 2
	});
	
	//Attempt#1:
	plot.x_range.callback=function(){console.log(plot.x_range.start);};
	//Attempt#2:
	//plot.x_range.callback=Bokeh.CustomJS({args:{"plot":plot},code:"console.log(plot.x_range.start);"});
	//Attempt#3:
	//plot.x_range.callback=Bokeh.CustomJS({callback:function(){console.log(plot.x_range.start);}});
	
	// Show the plot, appending it to the end of the current
	// section of the document we are in.
	Bokeh.Plotting.show(plot,document.getElementById("myPlot"));
	</script>
</body>
</html>
```

**Comment by bryevdv** [comment]
cc @mattpap another case that may be possible, but if it is I don't know how. Please confirm if there is a way, and we will use this issue to add documentation. Otherwise, we can use the issue for whatever changes are needed to support JS callbacks in direct BokehJS usage.

**Comment by mattpap** [comment]
`Range.callback` this is the one case where callback can only be specified by `CustomJS`. All other allow using a function as well.

**Comment by mattpap** [comment]
> `plot.x_range.callback=function(){console.log(plot.x_range.start);};`

This needs to be implemented.

> plot.x_range.callback=Bokeh.CustomJS({args:{"plot":plot},code:"console.log(plot.x_range.start);"});

Missing `new`. Should be `new Bokeh.CustomJS(...)`.

> plot.x_range.callback=Bokeh.CustomJS({callback:function(){console.log(plot.x_range.start);}});

This isn't going to work.

**Comment by mattpap** [comment]
> `plot.x_range.callback=function(){console.log(plot.x_range.start);};`

Another alternative is `plot.x_range.callback=function(range){console.log(range.start);};`.
