### ISSUE TITLE
Prove of concept: Caching of nodeJS compilation on model bundling

### ISSUE THREAD

**Issue by volkerjaenisch** [bokeh/bokeh#7131]
Dear Bokeh developers!

A while ago we shortly discussed on Gitter that in Bokeh server the compile time to generate the custom model JS inline is slow and should be cached.
Here we present a simple prove of concept for a caching of the nodeJS compilation that holds even when more than one disjunct models were delivered by a single bokeh server instance.

In bokeh/bokeh/util/compiler.py
```
def calc_cache_key():
    """There is no metadata than the Model classes,
        so this is the only base to generate a cache  key.
       We build the model keys from the list of model.full_name(s).
       This is ineffective but possibly a better solution can be found found.
       It is still at least an order of magnitude faster faster than the nodeJS :-)
    """

    models = Model.model_class_reverse_map.values()
    custom_model_names = ""

    for cls in models:
        impl = getattr(cls, "__implementation__", None)

        if impl is not None:
            model = CustomModel(cls)
            custom_model_names += model.full_name

    key = hashlib.sha256(custom_model_names.encode('utf-8')).hexdigest()
    return key

def bundle_all_models():
    if not hasattr(Model, '__cache'):
        Model.__cache = {}
    key = calc_cache_key()
    if key in Model.__cache:
        return Model.__cache[key]
    else:
        Model.__cache[key] = bundle_models(Model.model_class_reverse_map.values()) or ""
        return Model.__cache[key]
    if not Model.__cache[key]: #this is probably overkill
        Model.__cache[key] = bundle_models(Model.model_class_reverse_map.values()) or ""
    return Model.__cache[key]

#    return bundle_models(Model.model_class_reverse_map.values()) or ""
```
Cheers,
Volker

**Comment by bryevdv** [comment]
cc @mattpap I know you have more extensive plans but this is a serious pain point for more than a few users now, we need to offer some kind of relief on a more immediate time scale.  So if this something like this can be put in and won't affect your future plans at the API level, I think we need to consider it.

**Comment by mattpap** [comment]
This is more or less what I intend to implement. The difference would be what's included in the hash.

**Comment by bryevdv** [comment]
@mattpap can you briefly describe what you intend? I believe @volkerjaenisch and @sandarum are willing and able to work on this, which would free us to concentrate on other issues.

**Comment by mattpap** [comment]
I would just implement `__hash__` on `CustomModel` and `Implementation`, and take full model path, implementation and dependencies into account. But for this simple use case just full model path may be sufficient. I was looking forward more to being able to store and reuse compiled bundles.

**Comment by volkerjaenisch** [comment]
@mattpap I agree fully that my proposal is more a hack than a solution.

_Most efficiently would be to have the custom models (and their dependecies) precompiled and cached and reused to simply be plugged together in the bundling. But this solution as nice it may be is out of reach, yet._

So we have to go to bundle larger chunks. So we identified the `bundle_all_models()` routine as a good point to leverage on. To do the caching at this point we need a `__hash__` as key for the cache.

I do not agree to include so much information as you propose in the `__hash__`. I vote for a better `__hash__` coming from metadata pushed down from upper code levels. 

**The fundamental question is: How to identify the current "model set" to be bundled.** 

A "model set" I denote the collection of Custom Models including their dependencies to deliver a certain "view". I am not so familiar with your terminology maybe a "view" is a "document".

For example there may be a "view1" depending on "model set" (custom model A and custom model B), as well as a "view2" depending on "model set" (cmC and cmB). A "model set" has a 1:1 relation to a view.

**Currently at the time of bundling the code does not know for which "view" it is bundling. Aka for what "model set".**

Maybe some more information from tornato could be pushed into Bokeh (The request, the view, etc) so deep that the bundler can make use of it. Currently there are only a hand full of entry points utilizing `bundle_all_models()` if we could make the entry points add the cache key we would be done `bundle_all_models(view.key)`. 

**If we can solve this problem our cache key for bundling simply is the "view", or a hash the view provides.**
