### ISSUE TITLE
Create a bokehjs style dict interface for python

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#714]
I find the bokehjs dictionary style interface for describing glyphs and plots to be very useful.  The dictionary/list interface makes it easier to programatically construct plot descriptions.

**Comment by bryevdv** [comment]
Going to close this old discussion, but will leave a few comments:

* factoring some code between `bokeh.plotting` and `bokeh.charts` might leave an opening for something like this 
* might consider an outside PR based on common code described above.
