### ISSUE TITLE
Add option for disabling spatial indexing

### ISSUE THREAD

**Issue by jxramos** [bokeh/bokeh#7145]
To support drawing there needs to be a means to disable spatial indexing to respect the rendering of glyphs based on the row order of a ColumnDataSource such that the first set of rows are plotted first followed by subsequent rows of data each stacking atop one another in z-order.

This simple example demonstrates the behavior that needs to be supported

```
import pandas
import numpy
from bokeh.application.handlers import FunctionHandler
from bokeh.application import Application
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure
from bokeh.server.server import Server

def modify_doc(doc):
    df = pandas.DataFrame()

    theta = numpy.linspace( 0 , 2*numpy.pi , 20 )
    colors = ['yellow' if (c % 2 == 0) else 'blue' for c in range(len(theta))]

    df['X'] = numpy.cos(theta)
    df['Y'] = numpy.sin(theta)

    source = ColumnDataSource(data=df) # does this change the order?

    plot = figure()
    plot.circle('X', 'Y', source=source, radius=0.22 , fill_alpha=1, color=colors)

    plot.add_tools( HoverTool( tooltips=[ ( '(x,y)', '$x,$y') , ( 'index' , "$index" ) ] ) )
    doc.add_root(plot)


bokeh_app = Application(FunctionHandler(modify_doc))

# Setting num_procs here means we can't touch the IOLoop before now, we must
# let Server handle that. If you need to explicitly handle IOLoops then you
# will need to use the lower level BaseServer class.
server = Server({'/': bokeh_app})
server.start()

if __name__ == '__main__':
    print('Opening Bokeh application on http://localhost:5006/')

    server.io_loop.add_callback(server.show, "/")
    server.io_loop.start()

```
![image](https://user-images.githubusercontent.com/13857038/32261073-64dc58d0-be89-11e7-9a34-4d5e918b3b91.png)

And a link to the corresponding [StackOverflow question](https://stackoverflow.com/questions/46984970/does-a-columndatasource-change-the-row-order-when-deriving-from-a-dataframe/47002355#47002355) that triggered this issue.

**Comment by bryevdv** [comment]
This seems to have been resolved at some point in other work:

<img width="625" alt="screen shot 2018-06-30 at 23 05 49" src="https://user-images.githubusercontent.com/1078448/42131583-3413859e-7cba-11e8-9991-2d8a07409aee.png">

There is no way to disable spatial indexing, but AFAIK indices are processed in order now. Please re-open if there is still a reproducible issue.
