### ISSUE TITLE
[BokehJS] Add model selector

### ISSUE THREAD

**Issue by Astrum42** [bokeh/bokeh#7147]
In the present use case, a plot is created using server-side python code and injected into the following jinja template before a flask server returns the resulting html document.

The page contains javascript code meant to modify the plot directly in the browser without any further client-server interaction.

I could not find a way for accessing and manipulating already existing plot elements, and assuming there is indeed not yet a way to do so, I would like to propose the implementation of a '.find()' function that can return lists of handles to instances of Bokeh elements (like figures, glyphs, data sources, ...).

The idea would be to use those handles allow web page events (button click, dropdown menu value selection, text input, ...) to modify the plot (add data point, change line color, ...).

```
<html>
<head>
    <link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.10.css" type="text/css" />
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.10.js"></script>
    <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-api-0.12.10.js"></script>
    <!-- The order of CSS and JS imports above is important. -->
</head>
<body>
    <div id="myPlot">{{bokeh_html}}</div>
    <script type="text/javascript">
	//get current figure
	var plot = Bokeh.find('figure')[0];
	
	//change figure title
	plot.title='updated plot';
	
	//get line glyph
	var line = plot.find('line')[0];
	
	//change line color
	line.color='red';
	
	//add data  data point (10,-1) to data source
	var source = line.source;
	source.data['x'].push(10);
	source.data['y'].push(-1);
	
	//update display (may not be needed, but still useful to get the plot_view handle and call methods like "plot_view.layout()").
	var plot_view = Bokeh.Plotting.show(plot,document.getElementById("myPlot"));
	
    </script>
</body>
</html>
```

**Comment by p-himik** [comment]
Bokeh already has [get_model_by_name](https://bokeh.pydata.org/en/latest/docs/reference/document.html#bokeh.document.document.Document.get_model_by_name). The reference is for Python, but many JS classes are mirroring Python classes, including `Document`. I think that it does exactly what you need.

**Comment by jeffreyjharris** [comment]
Reiterating Eugene's comment:  if you assign the `name` property of a Bokeh model in Python, you can then use [get_model_by_name](https://bokeh.pydata.org/en/latest/docs/reference/document.html#bokeh.document.document.Document.get_model_by_name) in JavaScript to get the model.
Python:
```python
# Assign a name to model objects so we can reference in JavaScript
p = figure(name='myPlot')
cds = ColumnDataSource(some_df, name='myDatasource')
```
JavaScript
```javascript
// Get model objects by name
p = Bokeh.documents[0].get_model_by_name("myPlot")
cds = Bokeh.documents[0].get_model_by_name("myDatasource")
```

**Comment by bryevdv** [comment]
Since there is a potential solution available, and there was no further discussion about it, I am going to go ahead and close this.
