### ISSUE TITLE
Better control of data ranges/alignment

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#715]
There are a couple of issues here. 

When I build a multi y range plot, each range will have a different 0.
imagine to y ranges: {left:[-100,100], right:[-250, 200]}  for those two ranges 0 will be very close but not exactly aligned.  

It is also concievable that you would want 0 to line up at the bottom of the screen, top of the screen, or some percentage offset.  I'm not sure what an API that fixes this should look like.  I am sure other people will run into this problem.

**Comment by bryevdv** [comment]
I don't think this is a valid request. If the plot has two ranges `[-100, 100]` and `[-250, 200]` then their respective zeros ***can't*** line up, by definition. It is the endpoints that have to match up, which means the internal points are wherever they are. Making the zeros line up would involve some kind of distortion. If appropriate, you can certainly choose your own ranges such that the zeros of each are coincident. Please re-open with more information if I have misunderstood something.
