### ISSUE TITLE
ImportError: No module named charts

### ISSUE THREAD

**Issue by patelhardik** [bokeh/bokeh#7152]
I already went through https://github.com/bokeh/bokeh/issues/4419
But I face same problem:

I have installed latest packages for Python2.7.14
numpy>=1.13.1
pandas>=0.21.0
bokeh >=0.12.10

my test file is very simple

File is:

#/usr/bin/env python

import os, sys
import pandas as pd
import numpy as np

import bokeh.io --> WORKS
import bokeh.charts --> Doesn't WORK

This throws below error:

 import bokeh.charts
ImportError: No module named charts

**Comment by bryevdv** [comment]
The old `bokeh.charts` have been moved to a separate project [`bkcharts`](https://github.com/bokeh/bkcharts). You could file this issue there, but please know that `bkcharts` is ***currently unmaintained***, so it is unlikely any response will occur. You can look to HoloViews for a very high level API built to on Bokeh that is actively maintained, or use the `bokeh.plotting` API

Any follow on support questions should go to the mailing list as described in the issue tracker:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
