### ISSUE TITLE
Standalone mode: images referenced in CSS files are missing

### ISSUE THREAD

**Issue by jxrossel** [bokeh/bokeh#7156]
Hi,

I'm using bokeh without the CDN (intranet only) and the CSS file bokeh-tables.css (at least) refers to images that I can't find in the git repository (e.g. GrpCheckboxY.png, GrpCheckboxN.png, sort-desc.gif, ...). Would it be possible to add these images to the library files ?

**Comment by bryevdv** [comment]
@mattpap I am not sure what we could do about this, ideas?

**Comment by mattpap** [comment]
We can inline them using LESS' macros (as we already do with e.g. tool button icons). One thing to consider, though, is maintenance burden, if we intend to update slickgrid on any regular basis.

**Comment by bryevdv** [comment]
Update our fork ourselves you mean? It's fairly rare by my estimation.

**Comment by bryevdv** [comment]
@mattpap should we move this to a `task` ?

**Comment by bryevdv** [comment]
@mattpap Is this still relevant?

**Comment by mattpap** [comment]
I don't recall fixing anything so most likely yes.

**Comment by bryevdv** [comment]
Just commenting that I did not realize that those images were for the heavy "chromed" column headers. I am :-1: on changing the flat look that has been established for a long time now. Perhaps we can add less macros for "empty" images just to silence the errors?

**Comment by mattpap** [comment]
> Perhaps we can add less macros for "empty" images just to silence the errors?

This is what I intend to do. I got confused by this relying on missing images and not using `background-image: none;`.
