### ISSUE TITLE
Embedding Bokeh not behaving as expected for reveal.js or WebSlides

### ISSUE THREAD

**Issue by eddy-ojb** [bokeh/bokeh#7159]
### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages):
I am using:
- Bokeh 0.12.10 and also tested with Bokeh 0.12.11dev1
- python 3.6.2
- notebook 5.0.0
- browser=Chrome
- WebSlides 1.5.0
- reveal.js 3.5.0.

### Description of expected behavior and the observed behavior

I have two images listed below relating to WebSlides and reveal.js, respectively:

#### WebSlides:
Issue: Bokeh toolbar misaligned on an otherwise empty slide:

https://imgur.com/ZqnAus8

#### reveal.js:
Issue: The bokeh plot is not centered in the screen as expected - it contains itself in a much wider container automatically. If you use a cross-hair , it mis-aligns with the cursor. So does the hover tool:

https://imgur.com/zonGoY5

Does this happen with the Bokeh team? I would be keen to hear what software versions the team use if they don't experience this.

### Complete, minimal, self-contained example code that reproduces the issue
In order to repeat the WebSlides problem:

1) Download the source code for WebSlides https://github.com/webslides/webslides/

2) Get a Bokeh plot and obtain the div and script components. The one from the tutorial will do: 
https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html

3) Insert div, script and link in relevant locations in the WebSlides boiler plate code, which can be found in the 'index' html. The plot 'div' goes inside a 'section' (which is a slide). A compiled html example can be found in the here: 
https://1drv.ms/u/s!ApUjKldoMhhBg7YXxVgnLkIvdw6Reg

#### Example HTML code for WebSlides:
```
<!doctype html>
<html lang="en" prefix="og: http://ogp.me/ns#">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link
        href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.10.min.css"
        rel="stylesheet" type="text/css">

        <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.10.min.js"></script>


    <BOKEH SCRIPT IS PLACED HERE>


    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,700,700i%7CMaitree:200,300,400,600,700&amp;subset=latin-ext" rel="stylesheet">

    <!-- CSS WebSlides -->
    <link rel="stylesheet" type='text/css' media='all' href="static/css/webslides.css">

    <!-- Optional - CSS SVG Icons (Font Awesome) -->
    <link rel="stylesheet" type='text/css' media='all' href="static/css/svg-icons.css">

  </head>
  <body>

    <main role="main">
      <article id="webslides" class="horizontal">

        <section>

          <div class="bk-root">
              <div class="bk-plotdiv" id="dac8b20e-c981-49a6-8c18-cf0ca0ddc43a"></div>
          </div>

        </section>

      </article>

    </main>

    <script src="static/js/webslides.js"></script>
    <script>
      window.ws = new WebSlides();
    </script>

    <script defer src="static/js/svg-icons.js"></script>

  </body>
</html>
```

For reveal.js, it's a similar layout of html, just download from github,  insert the div in to the 'section' component in the boilerplate 'index' html to repeat the bug.

**Comment by eddy-ojb** [comment]
Update: I've found that components don't work in either case but that an iframe of an html works in both so I am going down the route of using this for now. Apologies if this seems very obvious to the team, I am new to working in html.

**Comment by bryevdv** [comment]
I'm glad you found a workaround. I don't know anything about WebSlides, the reveal may just be a CSS conflict to look at, but it will take probably someone with more HTML/CSS chops than I have to fix it.

**Comment by aparkerlue** [comment]
Using an iframe is a good solution. It allows you to do [lazy loading](https://github.com/hakimel/reveal.js/#lazy-loading) on large Bokeh plots.

**Comment by bryevdv** [comment]
Given that is a reasonable workaround expressed here, I'm going to close this. If someone who is actually familiar with these other tools is available to work on this, we can consider re-opening.
