### ISSUE TITLE
Draggable legends

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#716]
It would be nice if legends could be dragged around the plot.  I'm not sure if this would be a tool or how it would be implemented.

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by MulticastMatt** [comment]
Sarah - I'd like to see tests--we don't have a lot of good Selenium/Unit Tests.

**Comment by naifrec** [comment]
hello `bokeh` people :) is this implemented yet? if not, will it ever be? Thank you!

**Comment by bryevdv** [comment]
This is open, which signals that it is not implemented, but there is an intention to do so. As for when, I can't speculate. The current small team is (over)saturated with work. The only thing that can fix that situation  is for more people to decide to become new contributors. I'd be happy to help anyone get started or provide guidance on this or any other issue.

**Comment by bryevdv** [comment]
I'm actually inclined to close this at this point. After five years there has only been a minuscule amount of interest expressed here, and actually thinking about it, I am not sure what it really adds. Similar to the old resize tool, there's no way to persist any changes made this way, they would disappear on any page load. 

I will go ahead and close now, if there is some strenuous objection (or especially commitment to work on) from @bokeh/dev we could consider re-opening.
