### ISSUE TITLE
Convenience method to get data from filtered data source in a Python callback

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#7163]
Currently in a Bokeh App using filtered DataSources to get the data that the user sees on a plot or in a DataTable, you have to do something like:

```
d = plot_source.to_df()
d[d[view1.filters[0].column_name] == view1.filters[0].group]
```
And this is for the simple case of a single view with a single filter.

It would be great if there was a convenience function to get the data as it has been filtered by the CDSView.

**Comment by bryevdv** [comment]
Not sure this is possible in general. The code above relies on Pandas, but pandas is not required and note guaranteed to be present. The grouping actually happens on the client side, so to do it in general we'd have to implement our own groupby and I'm just not inclined to go down that route.
