### ISSUE TITLE
Axes labels misplaced on multiple extra_x_ranges

### ISSUE THREAD

**Issue by doiko** [bokeh/bokeh#7164]
I have tried to add multiple extra_x_ranges on a plot and the labels failed to be placed on the correct position. Probably related to the offset used when more than one extra_x_ranges is used.

I am using python 2.7 with Bokeh 0.12.10
In the example bellow axis label 'foo2' is misplaced over axis foo3 and label 'foo3' is missing.
Code to replicate:
![untitled](https://user-images.githubusercontent.com/33360731/32397602-e17d6f60-c0ea-11e7-96e1-a65122753b40.png)
```
from bokeh.plotting import figure, show
from bokeh.models import Range1d, LinearAxis


plot = figure(title=None, x_axis_location=None, y_axis_location=None)
plot.extra_y_ranges ['MD'] = Range1d(start=0, end=1)
plot.add_layout(LinearAxis(y_range_name='MD', axis_label = 'MD [m]'), 'left')
plot.extra_x_ranges ['foo1'] = Range1d(start=0,end=1)
plot.add_layout(LinearAxis(x_range_name='foo1', axis_label = 'foo1'), 'above')
plot.extra_x_ranges ['foo2'] = Range1d(start=0,end=10)
plot.add_layout(LinearAxis(x_range_name='foo2', axis_label = 'foo2'), 'above')
plot.extra_x_ranges ['foo3'] = Range1d(start=0,end=1)
plot.add_layout(LinearAxis(x_range_name='foo3', axis_label = 'foo3'), 'above')


plot.line(x = [0,1], y = [0,1], legend = 'foo1', x_range_name='foo1', y_range_name='MD')   
plot.line(x = [10,0], y = [0,1], legend = 'foo2', x_range_name='foo2', y_range_name='MD', color='red')   
plot.line(x = [0,0.5], y = [0.5,0], legend = 'foo3', x_range_name='foo3', y_range_name='MD')   

show(plot)
```

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by mattpap** [comment]
This works correctly in PR #7108, so maybe we will have one issue for free.

**Comment by mattpap** [comment]
This also work on `master`.

**Comment by mattpap** [comment]
I would add this example as a test though.

**Comment by bryevdv** [comment]
@mattpap can you do this today, or let me know where you want it added and I will do it.

**Comment by bryevdv** [comment]
@mattpap this does not appear to be fixed in master at the moment

**Comment by mattpap** [comment]
This is what I see in Chrome:

![image](https://user-images.githubusercontent.com/27475/34389419-c8ca0a90-eb39-11e7-99d9-5fbf1531ec57.png)

I will submit with a PR later today. Hopefully this isn't a browser-dependent issue.
