### ISSUE TITLE
Potential DataTable bug causes gallery example "export_csv" not working properly

### ISSUE THREAD

**Issue by TerryTsao** [bokeh/bokeh#7165]
I'm very new to Bokeh, so please let me know if and where I'm not reporting this bug appropriately so I can do better next time.

In this gallery example ["export_csv"](https://demo.bokehplots.com/apps/export_csv), there is obvious bug with the display inside the DataTable.

To reproduce this bug, go to that [example link](https://demo.bokehplots.com/apps/export_csv). And then:

1. Move the range slider to range: Min(90k+), Max(110k), so that the bug can be easily observed.
2. Move the Min slider carefully left and right. And look at the result in the DataTable, specifically for **Jamaal Osinski   $102,777.70**, as this is the most obvious data point.
3. When moving the bar to the right, you will notice **$NaN** appear.
4. When moving the bar to the left, you will notice that this particular data point of **$102,777.70** does not appear every time when it should.

As I was saying, I'm very new to Bokeh. I guess this might be duplicate of some other issues, like [#6863](https://github.com/bokeh/bokeh/issues/6863). But as I'm not familiar with how Bokeh works internally, I'm not sure if this has already been brought up by others.

**Comment by bryevdv** [comment]
This is resolved in `master` and the fix will be in the next release:

<img width="1005" alt="screen shot 2017-11-06 at 16 54 52" src="https://user-images.githubusercontent.com/1078448/32468283-3bbd944e-c313-11e7-95cf-18cb14bc011e.png">
