### ISSUE TITLE
Minor: online release notes show 0.12.10 as 0.12.0

### ISSUE THREAD

**Issue by ceball** [bokeh/bokeh#7166]
https://bokeh.pydata.org/en/latest/docs/releases/0.12.10.html

<img width="1367" alt="screen shot 2017-11-05 at 12 33 44 am" src="https://user-images.githubusercontent.com/1929/32410796-2b4903c6-c1c1-11e7-958d-418e9caa59c5.png">

**Comment by ivan-usov** [comment]
Seems, it was already mentioned in #7121 and fixed in #7122
