### ISSUE TITLE
Node.js 6.10 is required for custom model but is not available is the Bokeh Anaconda channel

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7167]
After upgrading one of my projects from 0.12.6 to 0.12.10 I received:
```
RuntimeError: node.js v6.10.0 or higher is needed to allow compilation of custom models ("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)
```
However, Bokeh Anaconda channel at https://anaconda.org/bokeh/nodejs contains only v6.6
It would be nice to always have the required version of Node.js available in Anaconda so that applications are easily deployable with `enviroment.yaml` - maybe some test could be created for it somewhere.

**Comment by p-himik** [comment]
Or maybe the error should say to install node.js using `conda install -c conda-forge nodejs`?

**Comment by mattpap** [comment]
Correct version of `node.js` is available in `defaults` channel. The error message was updated in PR #7136 to reflect that.
