### ISSUE TITLE
WebDriverException when using export_png

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7168]
Bokeh v0.12.10

When I try to use `export_png` in my application, I receive (pretty-printed):
```
{
  "errorMessage": "'undefined' is not an object (evaluating 'window.Bokeh.documents')",
  "request": {
    "headers": {
      "Accept": "application\/json",
      "Accept-Encoding": "identity",
      "Connection": "close",
      "Content-Length": "349",
      "Content-Type": "application\/json;charset=UTF-8",
      "Host": "127.0.0.1:32956",
      "User-Agent": "Python-urllib\/3.5"
    },
    "httpVersion": "1.1",
    "method": "POST",
    "post": "{\"sessionId\": \"ae4dd6f0-c218-11e7-8813-fba0ae2a2a1f\", \"script\": \"\\n\/\/ add private window prop to check that render is complete\\nwindow._bokeh_render_complete = false;\\nfunction done() {\\n  window._bokeh_render_complete = true;\\n}\\n\\nvar doc = window.Bokeh.documents[0];\\n\\nif (doc.is_idle)\\n  done();\\nelse\\n  doc.idle.connect(done);\\n\", \"args\": []}",
    "url": "\/execute",
    "urlParsed": {
      "anchor": "",
      "query": "",
      "file": "execute",
      "directory": "\/",
      "path": "\/execute",
      "relative": "\/execute",
      "port": "",
      "host": "",
      "password": "",
      "user": "",
      "userInfo": "",
      "authority": "",
      "protocol": "",
      "source": "\/execute",
      "queryKey": {
        
      },
      "chunks": [
        "execute"
      ]
    },
    "urlOriginal": "\/session\/ae4dd6f0-c218-11e7-8813-fba0ae2a2a1f\/execute"
  }
}
```

Apparently, `Bokeh.documents` can still be uninitialized when the page is loaded by Selenium.
Maybe `wait_until_render_complete` should use `WebDriverWait` to also check that `Bokeh.documets` exists?

**Comment by p-himik** [comment]
Adding
```python
def is_bokeh_loaded(driver):
    return driver.execute_script('return !!(window.Bokeh && window.Bokeh.documents);')

WebDriverWait(driver, 5, poll_frequency=0.1).until(is_bokeh_loaded)
```
before `driver.execute_script(_WAIT_SCRIPT)` seem to fix the problem. Is this an acceptable solution?

**Comment by bryevdv** [comment]
@p-himik that seems like a pretty reasonable thing to do. I guess it would be nice to understand the conditions that necessitate that since it has not been run into by other folks that I have heard at least. 

cc @canavandl any thoughts?

**Comment by normaljosh** [comment]
I am getting the same bug with export_png:


  "errorMessage": "undefined is not an object (evaluating 'doc.is_idle')",
  "request": {
    "headers": {
      "Accept": "application\/json",
      "Accept-Encoding": "identity",
      "Connection": "close",
      "Content-Length": "349",
      "Content-Type": "application\/json;charset=UTF-8",
      "Host": "127.0.0.1:51886",
      "User-Agent": "Python http auth"
    },
    "httpVersion": "1.1",
    "method": "POST",
    "post": "{\"script\": \"\\n\/\/ add private window prop to check that render is complete\\nwindow._bokeh_render_complete = false;\\nfunction done() {\\n  window._bokeh_render_complete = true;\\n}\\n\\nvar doc = window.Bokeh.documents[0];\\n\\nif (doc.is_idle)\\n  done();\\nelse\\n  doc.idle.connect(done);\\n\", \"args\": [], \"sessionId\": \"8346b220-ce0b-11e7-8561-e908b7afeb5c\"}",
    "url": "\/execute",
    "urlParsed": {
      "anchor": "",
      "query": "",
      "file": "execute",
      "directory": "\/",
      "path": "\/execute",
      "relative": "\/execute",
      "port": "",
      "host": "",
      "password": "",
      "user": "",
      "userInfo": "",
      "authority": "",
      "protocol": "",
      "source": "\/execute",
      "queryKey": {
        
      },
      "chunks": [
        "execute"
      ]
    },
    "urlOriginal": "\/session\/8346b220-ce0b-11e7-8561-e908b7afeb5c\/execute"
  }
}

**Comment by AzraelDD** [comment]
Mine seems to be the same problem. (Which is based on the bokeh group topic: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/BmO8sk2IB5Y)

@bryevdv To me it seems like the condition is the following:
_After the layout has been added to the root, exporting the png of a fig is not possible anymore._
Please see this gist, which shows the export both working and not working:
https://gist.github.com/AzraelDD/c4573f531fbc52cf5d0811d81d30a3fa

**Comment by Orasporas** [comment]
I'm having the same error when trying save plots on button click when values are put in textinput and plots have been updated:
```def exppng():
	export_png(plot1, filename="p1.png")
button.on_click(exppng)
```
Just "export_png(plot1, filename="p1.png")" shows no error and works

**Comment by pushkartalwalkar** [comment]
I'm having the same error when trying save plots on button click when values are put in textinput and plots have been updated:

def exppng():
	export_png(plot1, filename="p1.png")
button.on_click(exppng)
Just "export_png(plot1, filename="p1.png")" shows no error and works

Same error as this !

**Comment by bryevdv** [comment]
@p-himik would you be able to submit the small PR with the fix you described above?

**Comment by AzraelDD** [comment]
I implemented the merged PR in my local files, but the example I refered to before still does not work as expected:
https://gist.github.com/AzraelDD/c4573f531fbc52cf5d0811d81d30a3fa
After the layout has been added to the root, exporting the png of a fig is not possible anymore. 

Should that become a separate issue?

**Comment by p-himik** [comment]
@AzraelDD I've created #7621 since it has a completely different root cause.
