### ISSUE TITLE
Missing Application variable in example/howto/server_embed/flask_embed.py

### ISSUE THREAD

**Issue by ChristianTremblay** [bokeh/bokeh#7170]
```
server = Server({'/bkapp': modify_doc}, allow_websocket_origin=["localhost:8000"])
```

`modify_doc` should be used by a handler to modify the document inside an application
This line result in a _static_path error.

PR will follow

**Comment by bryevdv** [comment]
The example in master is updated to use s new feature that automatically applies a handler and creates an application. To be safest, always check out the version of the example specifically for the release tag.

**Comment by ChristianTremblay** [comment]
Ho, I see now. I should have pull the tag of the version I was using... Better luck next time :)
This caused me some headaches when I was trying to make it work. 
That said, some comments would have been really useful.
