### ISSUE TITLE
export_png saves transparent regions

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7174]
Bokeh v.0.12.10

Consider this screenshot:
![image](https://user-images.githubusercontent.com/4410314/32429412-22ff05fc-c2fd-11e7-9beb-042252c9495e.png)
If you change the background color of the image to e.g. red you'll see that there're many transparent regions. While it's easy to set some solid color to the title, it's rather hard to do so for the lines between plots and the bottom left region.
Maybe we could implement a flag to `export_png` that would allow a user to provide background color, which by default would be white?

**Comment by bryevdv** [comment]
cc @canavandl thoughts?

**Comment by bryevdv** [comment]
@p-himik Going through some old issues. is this still needing attention? Do you have a simple reproducer available?

**Comment by p-himik** [comment]
@bryevdv Seems like it's been fixed - I couldn't reproduce it and there's relevant documentation here: https://docs.bokeh.org/en/latest/docs/user_guide/export.html?highlight=export_png#exporting-png-images
