### ISSUE TITLE
notebook_div is removed in 0.12.10, but document about is still there

### ISSUE THREAD

**Issue by zjffdu** [bokeh/bokeh#7176]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 0.12.10

#### Description of expected behavior and the observed behavior

`notebook_div` is removed in 0.12.10, but document is still there. https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html

Need to remove document.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.embed import notebook_div
```

#### Stack traceback and/or browser JavaScript console output

```
ImportError: cannot import name 'notebook_div'
```

**Comment by bryevdv** [comment]
This was already fixed in https://github.com/bokeh/bokeh/pull/6969
