### ISSUE TITLE
Inline HTML render does not work

### ISSUE THREAD

**Issue by SpikingNeurons** [bokeh/bokeh#7178]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
System:  3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
Python:  3.6.1
Bokeh :  0.12.10
Browser: Chrome

#### Description of expected behavior and the observed behavior
I am trying to display generated HTML content inside notebook. It should show plot, but I get error in rendering html.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
import io
from IPython.display import HTML
from jinja2 import Template

from bokeh.embed import components
from bokeh.resources import INLINE
from bokeh.util.browser import view
from bokeh.themes import Theme
from bokeh.plotting import figure

x1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y1 = [0, 8, 2, 4, 6, 9, 5, 6, 25, 28, 4]

p1 = figure(title='DARK THEMED PLOT')
p1.scatter(x1, y1)

theme = Theme(json={
    'attrs': {
        'Figure': {
            'background_fill_color': '#2F2F2F',
            'border_fill_color': '#2F2F2F',
            'outline_line_color': '#444444'
            },
        'Axis': {
            'axis_line_color': "white",
            'axis_label_text_color': "white",
            'major_label_text_color': "white",
            'major_tick_line_color': "white",
            'minor_tick_line_color': "white",
            'minor_tick_line_color': "white"
            },
        'Grid': {
            'grid_line_dash': [6, 4],
            'grid_line_alpha': .3
            },
        'Circle': {
            'fill_color': 'lightblue',
            'size': 10,
            },
        'Title': {
            'text_color': "white"
            }
        }
    })

script, div = components(p1, theme=theme)

template = Template('''<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Bokeh Scatter Plots</title>
        {{ js_resources }}
        {{ css_resources }}
        {{ script }}
        <style>
            body {
                background: #2F2F2F;
            }
            .embed-wrapper {
                width: 50%;
                height: 400px;
                margin: auto;
            }
        </style>
    </head>
    <body>
        <div class="embed-wrapper">
        {{ div }}
        </div>
    </body>
</html>
''')

js_resources = INLINE.render_js()
css_resources = INLINE.render_css()

filename = 'embed_simple.html'

html = template.render(js_resources=js_resources,
                       css_resources=css_resources,
                       script=script,
                       div=div)

# Finally render fails
HTML(html)
```

#### Stack traceback and/or browser JavaScript console output
outputarea.js:456 SyntaxError: Unexpected token >
    at eval (<anonymous>)
    at Function.globalEval (jquery.min.js:4)
    at init.domManip (jquery.min.js:5)
    at init.append (jquery.min.js:5)
    at OutputArea._safe_append (outputarea.js:453)
    at OutputArea.append_execute_result (outputarea.js:490)
    at OutputArea.append_output (outputarea.js:323)
    at OutputArea.handle_output (outputarea.js:254)
    at output (codecell.js:376)
    at Kernel._handle_output_message (kernel.js:1196)
OutputArea._safe_append @ outputarea.js:456
OutputArea.append_execute_result @ outputarea.js:490
OutputArea.append_output @ outputarea.js:323
OutputArea.handle_output @ outputarea.js:254
output @ codecell.js:376
Kernel._handle_output_message @ kernel.js:1196
i @ jquery.min.js:4
Kernel._handle_iopub_message @ kernel.js:1223
Kernel._finish_ws_message @ kernel.js:1015
(anonymous) @ kernel.js:1006
Promise resolved (async)
Kernel._handle_ws_message @ kernel.js:1006
i @ jquery.min.js:4

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/2289914/32479770-bf79bfec-c38b-11e7-81fa-e6e02c70b73a.png)

**Comment by mattpap** [comment]
You have to embed JavaScript and HTML separately. Jupyter notebook's `HTML` class uses jquery's `$.html()` which has known issues with dealing with complex JavaScript code (as bokeh.js is).
