### ISSUE TITLE
Make it possible to add tools to bokehJS without modifying bokeh source

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#718]
There should be a method for js developers to add onto the bokeh system by creating tools in js, without modifying the core bokehJS tree.  This will make it easier for people to customize bokeh.  There should be method in Bokeh.Plotting (the js side) to specify these adhoc tools.  

The python interface should also be able to specify these adhoc tools.

Actually this concept should probably be extended to every type of bokehJS object.  There should be examples too.

**Comment by bryevdv** [comment]
This is covered by the custom models capability going into `0.11`
