### ISSUE TITLE
TypeError: Item in ``from list'' must be str, not unicode

### ISSUE THREAD

**Issue by jmbertoncelli** [bokeh/bokeh#7183]
(snake27.10) [root@nuke ~]# jupyter --version
4.4.0

bokeh: 0.12.10-py27_0 conda-forge

(snake27.10) [root@nuke ~]# python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
import numpy as np
from bokeh.layouts import *
from bokeh.plotting import *
from bokeh.models import *
from bokeh import *
output_notebook()
```
#### Stack traceback and/or browser JavaScript console output
 TypeError: Item in ``from list'' must be str, not unicode 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-c15b34911720> in <module>()
      4 from bokeh.models import *
      5 
----> 6 from bokeh import *
      7 output_notebook(verbose=True)

TypeError: Item in ``from list'' must be str, not unicode

**Comment by bryevdv** [comment]
I'm not sure at all what this might be (never seen anything like it) However, it does not matter. As of Bokeh `0.12.9` Bokeh only supports classic jupyter notebooks >= 5.0. There is absolutely no technical path that allows for supporting older versions, and JupyterLab at the same time. Suporting JupyterLab is a critical mandate, so older notebook versions cannot be supported. You can:

* downgrade your Bokeh version
* updgrade your Jupyter notebook version
* use JupyerLab
