### ISSUE TITLE
HoverTool data not completely matching when using CDSView filters in bokeh 0.12.11dev2

### ISSUE THREAD

**Issue by Zyell** [bokeh/bokeh#7189]
When using the HoverTool with a custom tooltip in conjunction with a CDSView of any kind, the data does not match up.  If you use the default tooltips, you will find that the index matches appropriately to the glyph being hovered over.  However, when you use a specific column from the data source in a tootip, it will not match the glyph being hovered over.

This was tested with python 3.6 and bokeh versions: 0.12.10, 0.12.11dev2 in a notebook and embedded in an html page.

```python
import pandas as pd
import numpy as np
from bokeh.models import CDSView, BooleanFilter, ColumnDataSource, HoverTool
from bokeh.plotting import figure, show
from bokeh.io import output_notebook

output_notebook()


df = pd.DataFrame([{'xs': [1, 3, 2], 'ys': [2, 1, 4], 'name':'a'},
                   {'x': 5, 'y': 2, 'xs': np.array([np.nan]), 'ys': np.array([np.nan]), 'name':'b'},
                   {'xs':[3, 7, 6, 6], 'ys': [3, 3, 4, 4], 'no_hover': True, 'name':'c'},
                   {'xs':[3, 4, 6, 6], 'ys': [4, 7, 8, 5], 'name':'d'},
                   {'x': 7, 'y': 5, 'xs': np.array([np.nan]), 'ys': np.array([np.nan]), 'no_hover': True, 'name':'e'},
                   {'x': 2, 'y': 7, 'xs': np.array([np.nan]), 'ys': np.array([np.nan]), 'name':'f'}
                   ])
source = ColumnDataSource(data=df)
p = figure(plot_width=400, plot_height=400, tools='hover')

view1 = CDSView(source=source, filters=[BooleanFilter(list((df['x'].notnull()) & (df['no_hover'] != True)))])
view2 = CDSView(source=source, filters=[BooleanFilter(list((df['x'].isnull()) & (df['no_hover'] != True)))])
view3 = CDSView(source=source, filters=[BooleanFilter(list((df['x'].isnull()) & (df['no_hover'] == True)))])
view4 = CDSView(source=source, filters=[BooleanFilter(list((df['x'].notnull()) & (df['no_hover'] == True)))])
a = p.circle(x='x', y='y', source=source, view=view1, radius=0.5)
p.circle(x='x', y='y', source=source, view=view4, radius=0.5, color='red')
b = p.patches(xs='xs', ys='ys', source=source, view=view2)
p.patches(xs='xs', ys='ys', source=source, view=view3, color='red')
hover = p.select(dict(type=HoverTool))
hover.renderers = [a]
hover.tooltips = [('name', '@name'),
                 ('index', '$index'),
                 ('no_hover', '@no_hover')]
p.add_tools(HoverTool(renderers=[b], tooltips=[('name', '@name'),
                                              ('index', '$index')]))
show(p)
```
If you run this code, you will notice that the index in the tooltip is correct in every case, but the "name" is not.  It is as if the hover tool ignores the filtered view entirely except where the index is concerned.  The special variables are always correct, while everything else is wrong.  I believe this is related to issue #6955.

In searching for a workaround, I found what I believe is the [problematic line in hover_tool.coffee](https://github.com/bokeh/bokeh/blob/ae7c6d9d1a9cf1f8c8862027104a1e5a38aca529/bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee#L278).
In this line, instead of i, index should be passed to _render_tooltips.  I built the following Custom Hover Tool in order to have a workaround for this issue:

```python
from bokeh.models import HoverTool

JS_CODE = """
import * as p from "core/properties"
import {HoverTool, HoverToolView} from "models/tools/inspectors/hover_tool"


export class CustomHoverToolView extends HoverToolView

    _render_tooltips: (ds, i, vars) ->
        i = vars['index']
        super(ds, i, vars)


export class CustomHoverTool extends HoverTool
  type: "HoverTool"
  default_view: CustomHoverToolView
  tool_name: "C_Hover"
  icon: "bk-tool-icon-hover"

"""


class CustomHoverTool(HoverTool):
    __implementation__ = JS_CODE
```
I can submit a pull request if you would like, I just need to re-setup my environment first.  I just wanted to get this issue and workaround posted in case others run into this same issue.

**Comment by bryevdv** [comment]
cc @clairetang6

**Comment by bryevdv** [comment]
@Zyell I believe your fix may be the correct one, a PR would be appreciated.
