### ISSUE TITLE
Investigate PyJamas for logic and api portions

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#719]
I think that we could get mileage out of PyJamas especially for API portions of bokeh.  If constructed properly, we could write the same logic for plotting APIs and get that for free in JS.  This wouldn't work for API portions that depend on NumPy or Pandas.  

Normally I think that language to language converters are a bad idea (GWT, PyJamas) because the power of JS comes from understanding the DOM and browsers.  GWT especially pretends that you can build decent apps without understanding the substrate.  For pure logic though, compilers do a great job of putting out the same working code in two languages.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
