### ISSUE TITLE
Review mapping ranges from data to/from screen space

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#7191]
This is a follow up on PR #7108, specifically the idea behind `r_invert()` and `r_compute()`. Original discussion https://github.com/bokeh/bokeh/pull/7108#pullrequestreview-74484016.

**Comment by bryevdv** [comment]
@mattpap what is the actual task? Or can this be closed?

**Comment by mattpap** [comment]
There were concerns regarding behavior and semantics of `r_*` functions. Given that the affected code has worked without issues so far and our limit capabilities, I think we can safely close this. This issue can be reopened in future if there is new motivation for assessing those functions.
