### ISSUE TITLE
Ion slider extension example broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#7193]
The Ion slider extension example here (when deployed with `0.12.11dev3` is broken:

https://bokeh.pydata.org/en/dev/docs/user_guide/extensions_gallery/widget.html#userguide-extensions-examples-widget

The issue appears to be in the Ion code itself, perhaps we are misusing it and a change uncovered this, or perhaps something changed to actively break it:

<img width="1045" alt="screen shot 2017-11-08 at 12 52 38" src="https://user-images.githubusercontent.com/1078448/32568415-c96af0d6-c483-11e7-91cf-6630d7a71df9.png">

cc @mattpap

**Comment by bryevdv** [comment]
Any chance this is related to the CS2 changes?

**Comment by mattpap** [comment]
> Any chance this is related to the CS2 changes?

Yes, it's an easy fix.
