### ISSUE TITLE
Bokeh 0.12.10 does not display graph from reloaded notebook

### ISSUE THREAD

**Issue by Zygonie** [bokeh/bokeh#7194]
I did not try with another version of Bokeh, but when whereas all is going well on a given notebook, the graph disappears when I close then reload the notebook. I understand it is not a static graph such like matplotlib, but is there a way to display a graph in a saved notebook ?

**Comment by bryevdv** [comment]
@Zygonie I am unable to reproduce any issue with Bokeh `0.12.10` and notebook `5.0.0`. You will need to provide more information and details about your specific situation. Here is a notebook after I "Ran all",  saved, then exited and restarted the notebook server:

<img width="705" alt="screen shot 2017-11-09 at 09 53 58" src="https://user-images.githubusercontent.com/1078448/32614987-1ae39994-c534-11e7-82cd-8d1b47bd4c93.png">

**Comment by Zygonie** [comment]
Ok, I reproduce what you said so I had to dig further to find what was going on.

Jupyter is running in a docker container. When I work in the same session, the graph is displayed after the notebook is closed as you said. But when I stop the container, restart it and reload the notebook, the graph disappears. Do I have to save some data from the container locally (by creating a volume) ?

**Comment by bryevdv** [comment]
@Zygonie I am afraid I don't know, as I have only passing familiarity with Docker. However, this seems to be a support/usage question, so I would request that the discussion continue on the mailing list, rather than the GH tracker: https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
