### ISSUE TITLE
Request for improvement to ColumnDataSource documentation in reference to multi_line()

### ISSUE THREAD

**Issue by David-Herman** [bokeh/bokeh#7198]
Hello,

I just wanted to comment on the mutli_line behavior. Several parameters are NumberSpec's which seemed to be ignored silently and the default values used due to the structure of the column datasource required for multi_view. In addition, the unique column data source consisting of a list of lists prevents the filtering of the data set using CDSView. In addition, if I use a CDS I cannot use an iterable for the other parameters such as color (passing in a source and a list of colors throws and error below).

A brief comment on my use case. I have two plots, one shows a scatter plot of averages. The other shows a plot of frequency vs time. I am using a hovertool JS callback to highlight the respective circle and line(s).  I had hoped to pass the multi_line CDS to the JS callback arg to change the alpha values.

In my prior code I used a for loop to plot out many lines. I had wanted to pass a nested dictionary of models to the JS callback but the JS call back expects models or strings only in a dictionary. I could go back and use a dictionary comprehension but that seems a bit messy.

```
plot.multi_line(xs='dates',ys='kde',
                                color = '#c50000',
                                line_alpha='alpha',
                                line_width = 'linewidth',
                                source =source)
```

```
_process_sequence_literals(glyphclass, glyph_ca, source, is_user_source)
  File "C:\WinPython-64bit-2.7.10.3\python-2.7.10.amd64
\lib\site-packages\bokeh\plotting\helpers.py", line 296, in _process_sequence_li
terals
    raise RuntimeError(_GLYPH_SOURCE_MSG)
RuntimeError:
Supplying a user-defined data source AND iterable values to glyph methods is
not possibe. Either:

Pass all data directly as literals:

    p.circe(x=a_list, y=an_array, ...)

Or, put all data in a ColumnDataSource and pass column names:

    source = ColumnDataSource(data=dict(x=a_list, y=an_array))
    p.circe(x='x', y='x', source=source, ...)
```

**Comment by David-Herman** [comment]
I am running Bokeh 12.10

**Comment by bryevdv** [comment]
I don’t know how to interpret several of the statements above. Please provide a complete minimal runnable example to clarify.

**Comment by David-Herman** [comment]
Ok, here was my confusion with use of multi_line and using a CDS. I had assumed that the shape of the data structure must match from the notice on the user guide below.

> Note
There is an implicit assumption that all the columns in a given ColumnDataSource all have the same length at all times. For this reason, it is usually preferable to update the .data property of a data source “all at once”.

Rather, the length of each column must match but the individual elements in each column may consist of scalars or lists as long as the parent list length matches.

As such the following code (analogous to the user guide example) will work fine.
```
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource, CDSView
p = figure(plot_width=400, plot_height=400)
source = ColumnDataSource(data=dict(x=[[1, 3, 2], [3, 4, 6, 6]],
                          y=[[2, 1, 4], [4, 7, 8, 5]],
                          color=["firebrick", "navy"],
                          alpha=[0.8, 0.3] ))
p.multi_line(xs='x',ys='y',color='color',alpha='alpha',line_width=4,source=source)

show(p)
```
![image](https://user-images.githubusercontent.com/22305345/32661183-e8fc4d70-c5f3-11e7-8261-773089665fd2.png)

Similary the CDSView works fine with the following code.
```
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource, CDSView,GroupFilter
p = figure(plot_width=400, plot_height=400)
source = ColumnDataSource(data=dict(x=[[1, 3, 2], [3, 4, 6, 6]],
                          y=[[2, 1, 4], [4, 7, 8, 5]],
                          color=["firebrick", "navy"],
                          alpha=[0.8, 0.3] ))
view = CDSView(source=source, filters=[GroupFilter(column_name='color', group='firebrick')])
p.multi_line(xs='x',ys='y',color='color',alpha='alpha',line_width=4,source=source, view=view)

show(p)
```
![image](https://user-images.githubusercontent.com/22305345/32661277-601c878a-c5f4-11e7-8985-db179c81926d.png)

So I am changing the title of my issue to reflect that this is an understanding regarding the use of the multi_line and CDS data structure as referenced in the documentation. Perhaps adding a note or example to the following documentation would resolve future questions.

https://bokeh.pydata.org/en/latest/docs/user_guide/data.html#columndatasource
https://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#multiple-lines
