### ISSUE TITLE
H-Bar Plot is not updating

### ISSUE THREAD

**Issue by saijena17** [bokeh/bokeh#7209]
Hello everyone. I am using windows 10 and working on .py file(Bokeh server)
#### Description of expected behavior and the observed behavior
Here is a code which should update according to the list inserted in the update function. I am stuck with this for which I can't move forward in my project. @birdsarah @bryevdv . Please help me with this problem. Thank You in advance
#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models import Title
from bokeh.models.widgets import Panel, Tabs
from bokeh.models import Arrow, OpenHead, NormalHead, VeeHead
from bokeh.models import Legend
from bokeh.models import HoverTool, Range1d
from bokeh.models import FactorRange 
#importing numpy and pandas
import numpy as np
import pandas as pd
from math import *
import random


#importing Bokeh Library and files
from bokeh.io import show, output_file
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, Select
from bokeh.plotting import figure
from bokeh.layouts import layout, widgetbox, column, row, gridplot
from bokeh.models import HoverTool,LassoSelectTool,WheelZoomTool,BoxZoomTool,ResetTool,PanTool
from bokeh.models.widgets import Div
from bokeh.transform import dodge
from bokeh.core.properties import value
from bokeh.palettes import GnBu3, OrRd3
from bokeh.plotting import reset_output

#defining source variable
source = ColumnDataSource({'x': [], 'y': []})
i=1
X=[]
curdoc().clear()


def update():
	global i
	x=[2,3,4]
	global X
	X=[i*n for n in x]
	new={'x':X,'y':[0.5,1.5,2.5]}
	print(X)
	i=i/1.1  
	source.stream(new)
	
curdoc().add_periodic_callback(update,10000)

#HORIZONTAL BAR PLOT
fig= figure(plot_width=1000,plot_height=300,x_axis_label='k',title='Power',toolbar_location="above",tools="")
fig.outline_line_color = "navy"
fig.hbar(y='y', right='x',height=0.4,color=OrRd3[1],source=source)


curdoc().add_root(fig)
curdoc().title = "Live updating"

```

**Comment by bryevdv** [comment]
This is a usage error. The plot is updating, but all your new bars are shorter then the original bars, so there is no visible change. If you set the alpha much lower, the updates are evident:

<img width="902" alt="screen shot 2017-11-17 at 11 30 13" src="https://user-images.githubusercontent.com/1078448/32960535-cbf6d014-cb8a-11e7-8aea-15085668d197.png">

Note that if you are wanting to update the existing bars, not add new ones, you probably want `patch` instead `stream`. However, I'd request that further discussion be moved to the mailing list or SO as it is a support question.
