### ISSUE TITLE
legend unduly added to figure (causing then "more than one legend renderer" error) 

### ISSUE THREAD

**Issue by chupach** [bokeh/bokeh#7210]
tested on bokeh 0.12.10/11dev with py3.6

#### Description of expected behavior and the observed behavior

This minimal example declares 2 figures and a label, and add a legend to both figures.

A x-range callback is added to the first figure with a dictionary consisting of a label.
As soon as doing so, fig[0].select(Legend) has suddenly two items, the second being the Legend of the second figure. 

Very weird...this is bugging me so much

I believe that is NOT an intended behavior. This is rather severe bug in my opinion as it prevents managing legends.

Also to be told: 
The bogus legend is not in fig[0].legend but only in fig[0].select(Legend).
I was unable to find a workaround, to find a way to remove it from fig select result

# code goes here between backticks

```python
from bokeh.io import curdoc
from bokeh.layouts import layout,row,column, widgetbox, gridplot
from bokeh.plotting import figure
from bokeh.models import CustomJS,ColumnDataSource,Label,Legend

figs = [figure(),figure()]
label = Label(x=2, y=0, x_units='screen', y_units='screen',text='', render_mode='css')
figs[1].add_layout(label)

dic_xrange_cb = {'label': label}
figs[0].x_range.callback = CustomJS(args=dic_xrange_cb,code="""console.log(cb_obj);""")

for fig in figs: fig.add_layout(Legend())
for fig in figs: print('legend:',fig,fig.select(Legend))
```

**Comment by p-himik** [comment]
Actually, it's a somewhat documented behavior:
```python
def select(self, *args, **kwargs):
    ''' Query this object and all of its references for objects that
    match the given selector.
[...]
```

The counter-intuitive part here is that `figs[1]` is referenced in `label.plot`.

@bryevdv Maybe the plot attribute of labels should not be treated as a reference here?

**Comment by mattpap** [comment]
There are two items, because `figure()` creates its own default legend. I recall that there may have already been a discussion for initializing the default legend lazily.

**Comment by mattpap** [comment]
> The counter-intuitive part here is that figs[1] is referenced in label.plot.

This is because `add_layout()` sets `plot` property automatically. In general, one shouldn't reuse models, unless it's required by design, e.g. sharing ranges for linked plot effect.

**Comment by chupach** [comment]
Hello, thanks a lot for the thoughts, 
Unfortunately, I am sorry for that, I still don't understand any of the comments actually: 

0. declare figures
1. after adding label to fig1 layout: none of the figs have a legend 
2. after adding the x-range callback to fig0,  figs still have no legend
3.then, after adding a legend to fig0, fig0 has a legend
4. **after adding a legend to fig1, fig0 has both the original fig0 and the fig1 legend, fig1 has a legend**

if x-range callback wouldn't have been added, both figs would have a single legend.
(btw, in the larger project, the plots are x-range linked)

here, no model reuse, not related to fig1 referenced in label plot, imho
Still in the dark...

**Comment by bryevdv** [comment]
`select` searches *all available references`. Annotations (e.g. `Label`) have a back reference to their plot, this is the point of linkage. You have:

> fig0 -> CustomJS -> .args -> Label -> .plot -> fig1 

since there is a connection of any sort, *all the models* reachable from fig0 will be queried. Both fig0 and fig1 are part of the collection of references and both have legends, hence selecting on fig0 will yield both legends. (but not the converse, fig0 is not "reachable" from fig1)

We could discuss adding some kind of restrictions, e.g. maybe only search one level deep, or exclude other figures when searching from figure. But those would be new features. The intent of `select` is to query the entire reachable object graph so I would describe this behavior as 100% expected and intended.

**Comment by chupach** [comment]
Thanks Bryan, that's clear !
but then, fig0 has 2 legends: adding glyphs with legend (using legend arg in figure) results in the aforementioned error..."more than one legend renderer", isn't that's a bit restrictive or non ideal ?

**Comment by bryevdv** [comment]
@chupach can you update your code to be complete? The code above does not demonstrate that further warning message.

**Comment by chupach** [comment]
here it is:
the two commented lines at the end can replace the arg legend='label' in fig.line directly above in order to get rid of message:
Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x1146afe48>: Plot Figure(id='298c0335-c8a1-413c-b72c-052e34f2004e', ...) configured with more than one legend renderer
thx.

`from bokeh.io import curdoc
from bokeh.layouts import layout,row,column, widgetbox, gridplot
from bokeh.plotting import figure
from bokeh.models import CustomJS,ColumnDataSource,Label,Legend,LegendItem

figs = [figure(),figure()]
label = Label(x=2, y=0, x_units='screen', y_units='screen',text='', render_mode='css')
figs[1].add_layout(label)

dic_xrange_cb = {'label': label}
figs[0].x_range.callback = CustomJS(args=dic_xrange_cb,code="""console.log(cb_obj);""")

for fig in figs: fig.add_layout(Legend())

source = ColumnDataSource(data={'x':[1,2,3],'y':[2,4,5]})
r = figs[0].line(source=source,x='x',y='y',legend='label')
#li = LegendItem(label='label',renderers=[r])
#figs[0].legend[0].items.append(li)

s = figs[1].line(source=source,x='x',y='y',legend='label')
curdoc().add_root(figs[0])`

**Comment by bryevdv** [comment]
This issue has gotten a bit stale. I am not sure what action there is to take. In the code above, simply removing the line
```
for fig in figs: fig.add_layout(Legend())
```

also fixes the code, and I would contend that if using `bokeh.plotting.figure` then adding legends manually like that is not recommended or necessary practice. If you want that level of control you would want to use the lower level `Plot` and `bokeh.models` directly.
