### ISSUE TITLE
IE11-incompatible syntax in bokeh/core/_templates/autoload_nb_js.js?

### ISSUE THREAD

**Issue by ceball** [bokeh/bokeh#7212]
I think template strings are not supported by IE11.

https://github.com/bokeh/bokeh/blob/6e094574c6ebfc8667f26700c2c132a830a3d2a7/bokeh/core/_templates/autoload_nb_js.js#L63

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

* bokeh 0.12.10 (but the code is in master - see above)
* IE 11.0.9600.17420

<img width="376" alt="screen shot 2017-11-14 at 4 48 26 pm" src="https://user-images.githubusercontent.com/1929/32792894-6e3aeeb8-c95c-11e7-936d-6cf8f16a436f.png">

#### Complete, minimal, self-contained example code that reproduces the issue

The hard part is running Windows/IE11 :(

I downloaded https://github.com/bokeh/bokeh/blob/0.12.10/examples/howto/notebook_comms/Basic%20Usage.ipynb, ran it (on mac), saved it as [html](https://github.com/bokeh/bokeh/files/1471805/Basic.Usage.html.gz) (attached as gzip), and then tried to open it using IE11.

#### Stack traceback and/or browser JavaScript console output

<img width="628" alt="screen shot 2017-11-14 at 5 03 19 pm" src="https://user-images.githubusercontent.com/1929/32793496-f9a12bba-c95d-11e7-95ad-c4866121a93b.png">

**Comment by mattpap** [comment]
@ceball, can you submit a PR?

**Comment by ceball** [comment]
Yes, I can. I'm just collecting IE11 issues at the moment, to be tackled (tested) together...
