### ISSUE TITLE
Canvas image smoothing in IE11

### ISSUE THREAD

**Issue by ceball** [bokeh/bokeh#7213]
On the left is IE11/Windows; on the right is Chrome/Mac:

<img width="1384" alt="screen shot 2017-11-14 at 8 45 57 pm" src="https://user-images.githubusercontent.com/1929/32805068-3e861dae-c980-11e7-9ba8-7ec94eb143cb.png">

I started from http://bokeh.pydata.org/en/latest/docs/gallery/image.html, set `N=10`, ran it in a notebook on Mac, saved as html, and then viewed the html in IE11 (left) and Chrome (right).

I think IE11 has image smoothing on for canvas by default, maybe? https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled may be useful for testing the smoothing setting in IE. 

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

* bokeh 0.12.10
* IE 11.0.9600.17420 on Windows 7 (VirtualBox VM on Mac)

<img width="376" alt="screen shot 2017-11-14 at 4 48 26 pm" src="https://user-images.githubusercontent.com/1929/32792894-6e3aeeb8-c95c-11e7-936d-6cf8f16a436f.png">

**Comment by bryevdv** [comment]
We fix up like six different browser specific canvas image smoothing properties already but I guess it’s still not enough:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/util/canvas.coffee#L18

**Comment by bryevdv** [comment]
We are already setting the property in your link @ceball

**Comment by ceball** [comment]
I think this doesn't matter as much as IE11, but same thing in Edge 14:
 
<img width="870" alt="screen shot 2017-11-15 at 12 00 17 am" src="https://user-images.githubusercontent.com/1929/32811604-937d8b18-c998-11e7-92ae-f5091b9f0083.png">

15 and 16 are fine:

<img width="880" alt="screen shot 2017-11-15 at 12 00 48 am" src="https://user-images.githubusercontent.com/1929/32811646-c7a5a9d4-c998-11e7-9248-ea39d0cc8ab8.png">

<img width="890" alt="screen shot 2017-11-14 at 11 59 44 pm" src="https://user-images.githubusercontent.com/1929/32811673-edcfa484-c998-11e7-95b1-12a57b206d09.png">

**Comment by ceball** [comment]
I got to those results via https://developer.microsoft.com/en-us/microsoft-edge/tools/remote/

I was looking for a way to run IE11 without the VM pain I've been experiencing so far, but unfortunately you have to sign up for a plan to get IE11. It seems like they (https://www.browserstack.com/) do offer free access for open source projects:

<img width="496" alt="screen shot 2017-11-15 at 12 02 53 am" src="https://user-images.githubusercontent.com/1929/32811703-14bab44e-c999-11e7-8714-2955592014e7.png">

(Though from skimming bokeh's issues, I see this kind of service is something you're already doing/have considered.)

**Comment by bryevdv** [comment]
Honestly seems like an IE bug but if you can track down another browser specific canvas setting to add to our fixups it’s easy to try.

**Comment by ceball** [comment]
`msImageSmoothingEnabled`, maybe?

<img width="1040" alt="screen shot 2017-11-15 at 12 54 41 am" src="https://user-images.githubusercontent.com/1929/32812978-a9c22c2e-c99f-11e7-8567-0c6899fae97c.png">

<img width="1040" alt="screen shot 2017-11-15 at 12 53 14 am" src="https://user-images.githubusercontent.com/1929/32812985-b20b8ab0-c99f-11e7-9794-30c197a84ef1.png">

**Comment by jbednar** [comment]
>msImageSmoothingEnabled

The name of that sounds like someone somewhere in MS found a bug and rather than actually fixing it, added a hack, thereby making everyone's life that little bit worse?  Sigh.

**Comment by ceball** [comment]
(Possibly related SO post that we could answer later: https://stackoverflow.com/questions/44928435/prevent-bokeh-image-interpolation-antialiasing)
