### ISSUE TITLE
No longer able to load BokehJS in jupyter notebook (Firefox 57)

### ISSUE THREAD

**Issue by aeroaks** [bokeh/bokeh#7227]
I am trying to run Bokeh in the notebook.
![image](https://user-images.githubusercontent.com/3954144/32888584-07fc1bfa-cac8-11e7-8cb3-a8efa2857715.png)

Console response
```
[I 12:11:22.624 NotebookApp] Kernel restarted: b19aebf8-a2a7-4575-a0cb-2ff2a2abd06b
[I 12:11:24.250 NotebookApp] Adapting to protocol v5.1 for kernel b19aebf8-a2a7-4575-a0cb-2ff2a2abd06b
[I 12:13:01.038 NotebookApp] Saving file at /coater_processing.ipynb
[I 12:14:57.164 NotebookApp] Kernel restarted: b19aebf8-a2a7-4575-a0cb-2ff2a2abd06b
[I 12:14:58.251 NotebookApp] Adapting to protocol v5.1 for kernel b19aebf8-a2a7-4575-a0cb-2ff2a2abd06b
[I 12:15:01.001 NotebookApp] Saving file at /coater_processing.ipynb
[W 12:15:20.861 NotebookApp] 404 GET /static/components/preact-compat/preact-compat.min.js.map (127.0.0.1) 1.50ms referer=None [W 12:15:20.869 NotebookApp] 404 GET /static/components/proptypes/index.js.map (127.0.0.1) 2.00ms referer=None
[W 12:15:20.876 NotebookApp] 404 GET /static/components/preact/preact.min.js.map (127.0.0.1) 1.50ms referer=None
[I 12:17:01.026 NotebookApp] Saving file at /coater_processing.ipynb
```
JS Console log in the browser
```
failed to load library https://cdn.pydata.org/bokeh/release/bokeh-gl-0.12.10.min.js 4 main.min.js:207:9
```

Packages installed in conda environment
```
bleach==2.0.0
bokeh==0.12.10
certifi==2016.2.28
colorama==0.3.9
cycler==0.10.0
decorator==4.1.2
entrypoints==0.2.3
et-xmlfile==1.0.1
html5lib==0.999999999
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
jdcal==1.3
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-core==4.3.0
jupyterlab==0.27.0
jupyterlab-launcher==0.4.0
MarkupSafe==1.0
matplotlib==2.0.2
mistune==0.7.4
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.0.0
numpy==1.12.1
olefile==0.44
openpyxl==2.4.8
pandas==0.20.3
pandocfilters==1.4.2
patsy==0.4.1
peewee==2.10.1
pickleshare==0.7.4
Pillow==4.2.1
prompt-toolkit==1.0.15
psutil==5.2.2
Pygments==2.2.0
PyMySQL==0.7.9
pyparsing==2.2.0
pyserial==2.7
python-dateutil==2.6.1
pytz==2017.2
pywin32==220
PyYAML==3.12
pyzmq==16.0.2
requests==2.14.2
scikit-learn==0.19.0
scipy==0.18.1
simplegeneric==0.8.1
six==1.10.0
statsmodels==0.8.0
testpath==0.3.1
tornado==4.5.2
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
win-unicode-console==0.5
wincertstore==0.2
XlsxWriter==0.9.8
```

**Comment by bryevdv** [comment]
@aeroaks I am able to reach that file (both by hand and by Bokeh to load it automatically) My guess is  that you had a temporary network issue.

**Comment by aeroaks** [comment]
Having the same issue, tried right now! @bryevdv  Have you tried with the new Firefox?

**Comment by bryevdv** [comment]
Yes it's working fine:

<img width="868" alt="screen shot 2017-11-16 at 08 52 24" src="https://user-images.githubusercontent.com/1078448/32897533-8665e84e-caab-11e7-9781-a30f06a16601.png">

Can you reach the file by navigating to the link directly:

https://cdn.pydata.org/bokeh/release/bokeh-gl-0.12.10.min.js

If not this is definitely a network issue on your end.

**Comment by aeroaks** [comment]
I can access the js file on the browser!

**Comment by bryevdv** [comment]
I am afraid I don't know what to suggest otherwise offhand, except to try inline resources (either by passing to `output_notebook`) or by setting env `BOKEH_RESOURCES=inline` before launching the notebook.

**Comment by bryevdv** [comment]
@aeroaks I believe this is a local configuration issue of some kind on your end. As such, I'd ask that it move to the [mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) for now, which is a more appropriate place for support type questions. If a reproducible configuration can be found to demonstrate a problem, we can re-open this issue.
