### ISSUE TITLE
Chord Diagram -> Links not connecting to ideogram correctly

### ISSUE THREAD

**Issue by DGMichael** [bokeh/bokeh#7228]
I am generating a plot in Bokeh using the chord diagram function.  The network edges connect to but then overlap the ideogram of the circle. This can be seen in the example here at the top and bottom of the circle.

https://bokeh.pydata.org/en/0.12.3/docs/gallery/chord_char 

I am using:
Python 3.6, Anaconda
Bokeh
iMac...reproducing the issue on Safari and Chrome.

**Comment by bryevdv** [comment]
@DGMichael the Chord chart is part of the old `bokeh.charts` API that has long sine been deprecated and removed to a reparate repo and project https://github.com/bokeh/bkcharts The appropriate place to file an issue would  be there, however I am compelled to inform that no one is maintaining the project and it is unlikely that any response or future work will occur.

**Comment by DGMichael** [comment]
Thanks Bryan - I’ll go back to circos in perl for this figure.

**Comment by bryevdv** [comment]
FWIW At this point the best place to consider adding a high level Chord diagram that uses Bokeh underneath would be Holoviews: https://github.com/ioam/holoviews I'd encourage you to make a feature request on their tracker.

**Comment by philippjfr** [comment]
I've now had multiple requests for a Chord diagram, so I've opened a feature request on our issue tracker (https://github.com/ioam/holoviews/issues/2137).

**Comment by DGMichael** [comment]
Thanks Bryan - Holoviews looks impressive.  I ended up working through the Circos course to make the figure.  It was in Perl but great documentation…massive amounts of great documentation!
