### ISSUE TITLE
Dictionary API for axes

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#723]
I'm working on the JS plotting.coffee interface to expose more flexibility with configuring legends.  Simple list/dictionary APIs that are interpretted into an object graph by plotting.coffee work very well for interactive charts.  Eventually I want to have the same dictionary API built in python, that way a user can interactively customize a chart with a JS interface, and have simple code-gen to build the same plot from python.

Right now this is the format I'm thinking of
```
yaxes[
{
        type:'linear',
        axis_label:false, // or a string for the label
        y_range_name: "default", // default to default, you can
                                                 // specify an alternative range
        location:"left"  // not sure how to handle this
    },
    {
        type:'categorical',
        location:'min',
        axis_label:"categories",
    }

```

**Comment by bryevdv** [comment]
The old JS API is gone.
