### ISSUE TITLE
Spectrogram example image broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#7230]
Extension needs an update:

<img width="590" alt="screen shot 2017-11-17 at 10 19 22" src="https://user-images.githubusercontent.com/1078448/32957284-df4f3b74-cb80-11e7-87fc-e018769d3d26.png">

which means there may be a migration note needed?

cc @mattpap

**Comment by bryevdv** [comment]
@mattpap this was broken here https://github.com/bokeh/bokeh/commit/234a1ff9e5b2bcd68b8be773afe6d15aeb6b8448#diff-1dcf42dcefdc014a6023fc8f4f6471f8

Can you take a look? Just fixing the `sx` line by making it `@x` is not sufficient. There are additional issues (the entire image is either shifter or compressed into a small band at the bottom)

**Comment by mattpap** [comment]
@bryevdv, I will fix this now.

**Comment by mattpap** [comment]
@bryevdv, after changing to `@x` everything seems to work fine. Plots are shifted, but this is because one of them has `min_border` set, and all other align correctly.
