### ISSUE TITLE
Equivalent vmin, vmax Matplotlib in Bokeh

### ISSUE THREAD

**Issue by joseQSR** [bokeh/bokeh#7235]
Hello everyone.
I am not secure if is the correct place for my problem. If it is not, I apologize and I beg to redirect me to the right place. I am a new user of bokeh. Although the question is very simple I have not found the answer. In the bokeh library, what is the equivalent of vmin and vmax of Matplolib imshow? For example, in Matplolib I use vmin and vmax with these values

`im = ax.imshow(image_data, vmin = 0.1, vmax = 0.8, origin = 'lower')`

However, If I use Bokeh I get a different result,

`p1 = figure(title="my_title",x_range=[min_x,image_data.shape[0]],y_range=[min_y, image_data.shape[1]], toolbar_location=None)`
`p1.image(image=[image_data], x=[min_x],y=[min_y],dw=[image_data.shape[0]],dh=[image_data.shape[1]], palette="Spectral11")
color_bar = ColorBar(color_mapper=color_mapper, ticker=LogTicker(),
                             label_standoff=12, border_line_color=None, location=(0,0))`

What is my error? Thanks in advance

![sof](https://user-images.githubusercontent.com/26483685/33012015-f192411c-cddf-11e7-8d49-6cb79702e030.png)

**Comment by ivan-usov** [comment]
Hi @joseQSR , check the 'low' and 'high' properties of ContinuousColorMapper class (or LinearColorMapper/LogColorMapper as its subclasses).
https://bokeh.pydata.org/en/latest/docs/reference/models/mappers.html

**Comment by joseQSR** [comment]
Perfect! thanks!
