### ISSUE TITLE
file_html giving js syntax error when it is a plot showing a image

### ISSUE THREAD

**Issue by softwaremechanic** [bokeh/bokeh#7237]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
    * bokeh 0.12.10
    * Chrome Version 62.0.3202.75 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior
      plotting an image and converting to html should generate correct js and html that renders.
#### Complete, minimal, self-contained example code that reproduces the issue

This html file is expected to load in the browser and display the image, instead:
it gives this [error](https://imgur.com/CUQtubM).  

CreateListFromArrayLike called on non-object. 

```
# code goes here between backticks
>>> from bokeh.plotting import figure
>>> from bokeh.resources import CDN
>>> from bokeh.embed import file_html

>>> def show_image(image, **kwargs):
...     p = figure(x_range=(0, 10), y_range=(0, 10), **kwargs)
...     p.image(image=[image], x=0, y=0, dw=10, dh=10, palette='Spectral11')
...     return p
... 
>>> show_image('/home/anand/workspace/smecorner/asr_demo/Mansi_english.flac.png')
>>> html=file_html(show_image('english.flac.png'), CDN, 'mpyl')
>>> with open('test.html', 'w') as fd:
...   fd.write(html)
```

#### Screenshots or screencasts of the bug in action
  https://imgur.com/CUQtubM

P.S: Tried the same file on firefox developer version.. just get diff error: `second argument to Function.prototype.apply must be an array`

**Comment by mattpap** [comment]
What you want to use is:
```
p.image_url(url=[image], x=0, y=0, dw=10, dh=10, palette='Spectral11')
```
Unfortunately bokeh's type system didn't prevent you from using wrong function.

**Comment by anandjeyahar** [comment]
Ugh.. There's no way to pass a file system path then? I was trying to avoid serving the image files separately and was hoping bokeh will pick up the image and embed it in html, which i can then serve. 

Anyways, thanks. will try image_url and update.

**Comment by mattpap** [comment]
In such a case you can load an image yourself and use either `image()` or `image_rgba()`, see https://github.com/bokeh/bokeh/issues/1699#issuecomment-88312102 as an example. The same can be achieved with PIL. There are quite a few solutions available on StackOverflow. Alternatively, it should be possible to use `image_url()` with [data URI](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) enconding, but I didn't test if this actually works.

**Comment by bryevdv** [comment]
@anandjeyahar Browsers are optimized to load, cache, and display images that are served. If an image is encoded and embedded inside a Bokeh document, all of that optimization is circumvented, Now, there still may be a reason its worth doing that, and there are ways to do it as @mattpap linked to, but making tradeoffs like that should be a conscious choice, which is why Bokeh does not do it "automatically.
