### ISSUE TITLE
document get_screenshot_as_png better

### ISSUE THREAD

**Issue by wqp89324** [bokeh/bokeh#7238]
Currently the export_png function in export.py is like the following: 

```
    image = get_screenshot_as_png(obj, height=height, width=width, driver=webdriver)

    if filename is None:
        filename = default_filename("png")

    image.save(filename)

    return abspath(filename)
```
It returns the abspath of the file saved, but is it possible to update it to also return/expose the image? This way it will be easy to save the PIL.Image.Image file to an object in memory, and return file data back in a format that an AWS clients put_object function will accept as the Body parameter:
```
    png_img = export_png(bokeh_fig, filename="xxx")
    in_mem_file = io.BytesIO()
    png_img.save(in_mem_file, format="png")
    _s3.Bucket(bucket_name).put_object(Key="yyy", Body=in_mem_file.getvalue())
```

**Comment by bryevdv** [comment]
@wqp89324For now you can just use `get_screenshot_as_png` directly? It's marked as `dev` API but that still means it will be a public, stable API. It could certainly use some better documentation support. 

I guess the two options are:

* document `get_screenshot_as_png` better, and promote it as the expected way to get images as data
* add a mode for `export_png` to do that

In general I'm usually -1 on having a function return different types (i.e. a file path vs image data) with different inputs, so my inclination is to prefer the first option.

**Comment by wqp89324** [comment]
@bryevdv 
I would agree the first option is fine, but currently in bokeh/bokeh/io/__init__.py, I did not see any import on "get_screenshot_as_png".
How can I import this function into my code?

Thank you so much!

**Comment by bryevdv** [comment]
Since it's considered dev/advanced it i in the sub module `bokeh.io.export` we could also consider making it "general" and moving it into `bokeh.io` I don't have a super strong opinion about that I guess I'd be -0, especially if the `export_png` docs link to it

**Comment by wqp89324** [comment]
@bryevdv 
I guess I'm asking a stupid question but here it is. When I do:
```
from bokeh.io.export import get_screenshot_as_png
```
I get the error: "ImportError: No module named 'bokeh.io.export'; 'bokeh.io' is not a package"

Could you please help?

Thank you so much!

**Comment by bryevdv** [comment]
This was all recently refactored as part of a larger cleanup effort. None of the common public APIs changed but the dev APIs are being shuffled as appropriate. You will need install `0.12.10` or newer for this function at that location, which will be  permanent stable location going forward

**Comment by bryevdv** [comment]
Triaging this issue to document `get_screenshot_as_png` more visibly.

**Comment by Roald87** [comment]
@bryevdv Could you elaborate on what exactly would you like to see added to the current documentation?

**Comment by bryevdv** [comment]
@Roald87 sorry I did not see this until now. I think the following woud be good:

* make sure the function docstring is thorough and complete

* add a section to the sphinx user guide about using this function to get back image objects directly with a few lines of example code.

**Comment by Roald87** [comment]
@bryevdv I've had a look at it, but I think it is rather complicated. At least I'm not quite sure what a `LayoutDOM` object is and how to use it.
