### ISSUE TITLE
Bokeh auto range whitespace is asymmetrical for rects

### ISSUE THREAD

**Issue by TiemenSch** [bokeh/bokeh#7239]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 0.12.10
Python 3.6.3 (anaconda)

#### Description of expected behavior and the observed behavior
I would expect the automatic range that Bokeh select for it's plot around some p.rect() to be quite **tight and symmetrical**. Instead, it shows a lot more whitespace near the origin. 

#### Complete, minimal, self-contained example code that reproduces the issue
```python
from bokeh.plotting import figure
from bokeh.io import output_file, show
output_file('./proto-plot.html')
p = figure()
p.rect([1.5, 7.0], [1.5, 7.0], [4, 7], [4, 7],
       fill_color=None, line_color='blue', line_width=3)
show(p)
```

#### Screenshots or screencasts of the bug in action
![example image](https://snag.gy/zy9aMS.jpg)

#### tightness
In Matplotlib, they have resorted to a helper function ``tight_layout`` that re-evaluates the contents of the frame and gets a snappier fit. That solution feels a little 'dirty' though.

**Comment by bryevdv** [comment]
This is an issue specific to `Rect`. It's doing this:
```
  max_wh2_bounds: (bds) ->
    return {
        minX: bds.minX - @max_w2,
        maxX: bds.maxX + @max_w2,
        minY: bds.minY - @max_h2,
        maxY: bds.maxY + @max_h2,
    }
``` 
where the "w2" and "h2" values are the single max width/height for *any* rect.  This is an optimization for hit testing that generally works well for "scatter" type plots with lots of small glyphs, but can lead to results like the above for auto ranging with fewer, bigger ones. We can probably just store the rects themselves in the spatial index though, which would make bounds reporting more accurate.

**Comment by bryevdv** [comment]
> We can probably just store the rects themselves in the spatial index though, which would make bounds reporting more accurate for rects.

Well, we can't actually do just that, remembering the reason `Rect` is more complicated is that it can be rotated an arbitrary angle. 

@TiemenSch In the mean time I would suggest using `quad` or `vbar` or `hbar` instead of `rect`, they are all axis-aligned and should all report bounds more carefully.

**Comment by bryevdv** [comment]
Given that 

* `quad` or `vbar` or `hbar` all work as workarounds
* managing the ranges explicitly is also an option
* unclear what the right behavior could even be in log or categorical spaces
* this is only a big concern in a subset of all cases

I am just going to close this as `wontfix`
