### ISSUE TITLE
Consistent text description for dictionary API

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#724]
There are a bunch of places that text styling occurs in a bokeh plot.  Off the top of my head this includes axis labels, the title, and legends.  There should be a common dictionary format for describing this text and it should hang off a common keyname.

```
yaxes:[
    {type:'linear',
     y_range_name:'default',
     axis_label:'height',
     text_props:{font:'helvetica', font-size:'14px',  font-decoration:'bold', color:'green'}
}]
```

**Comment by bryevdv** [comment]
There was a time when I might have liked to make things more hierarchical, like this, but I think the opportunity has passed. What we have now is common key name suffix, (e.g., `foo_font`, `bar_font') and I don't think changing that is really an option at this point.
