### ISSUE TITLE
Feature offer: metric prefix ticker

### ISSUE THREAD

**Issue by ignamv** [bokeh/bokeh#7252]
type: feature

Hi,

I made a TickFormatter that uses [Metric Prefixes](https://en.wikipedia.org/wiki/Si_prefixes) like k, M, G, T. This is very useful in electronics, where everything is expressed using these prefixes. People reading exponential notation have to mentally convert to the nearest metric prefix.

This is how it looks:

![image](https://user-images.githubusercontent.com/408363/33240411-3ebb95d4-d294-11e7-8254-282e332a3202.png)

This is how it handles large/small values:

![image](https://user-images.githubusercontent.com/408363/33240418-663b7322-d294-11e7-8f23-44329b483fdd.png)

**Comment by bryevdv** [comment]
I think given the lack of resources, and that this an be accomplished with a `FuncTickFormatter`, I will close this with no action.
