### ISSUE TITLE
Websocket connection failed: Could not decode a text frame as UTF-8

### ISSUE THREAD

**Issue by marami52** [bokeh/bokeh#7258]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 0.12.10
Python 3.5.2
OS:  Debian GNU/Linux 8 \n \l
Browser: Chrome Version 62.0.3202.75 (Official Build) (32-bit)

#### Description of expected behavior and the observed behavior
I just ran `sliders.py` example in a cloud IDE. After running `bokeh serve sliders.py`, application starts successfully but "sliders" inside the app do not work due to the disconnection of websockets.

#### Complete, minimal, self-contained example code that reproduces the issue
[sliders.py](https://github.com/bokeh/bokeh/blob/master/examples/app/sliders.py)

#### Stack traceback and/or browser JavaScript console output

```
jovyan@723a1c5ed119:/ride/work$ bokeh serve slider.py2017-11-27 22:48:22,222 Starting Bokeh server version 0.12.10 (running on Tornado 4.5.2)
2017-11-27 22:48:22,236 Bokeh app running at: http://localhost:5006/slider
2017-11-27 22:48:22,236 Starting Bokeh server with process id: 1010
2017-11-27 22:48:32,431 200 GET /slider (127.0.0.1) 227.85ms
2017-11-27 22:48:33,045 304 GET /static/js/bokeh.min.js.map (127.0.0.1) 21.90ms
2017-11-27 22:48:33,270 304 GET /static/js/bokeh-widgets.min.js.map (127.0.0.1) 12.01ms
2017-11-27 22:48:33,281 304 GET /static/js/bokeh-gl.min.js.map (127.0.0.1) 10.76ms
2017-11-27 22:48:33,298 304 GET /static/js/bokeh-tables.min.js.map (127.0.0.1) 16.36ms
2017-11-27 22:48:33,304 101 GET /slider/ws?bokeh-protocol-version=1.0&bokeh-session-id=921uNn1bcE7xberrZu14eVIR8bYqlreNILyBbk5tJtbU (127.0.0.1) 0.46ms
2017-11-27 22:48:33,304 WebSocket connection opened
2017-11-27 22:48:33,304 ServerConnection created
2017-11-27 22:48:46,676 WebSocket connection closed: code=None, reason=None
```

Here is the link of the ws connection:
`wss://xxx.xxx.io:8443/ab5ecbe542b14aedaf7511985b0ff697/p5006/slider/ws?bokeh-protocol-version=1.0&bokeh-session-id=921uNn1bcE7xberrZu14eVIR8bYqlreNILyBbk5tJtbU`

#### Screenshots or screencasts of the bug in action
![bokeh](https://user-images.githubusercontent.com/16093950/33295378-d7b4f5f0-d389-11e7-9245-7c5e3caebed4.png)

**Comment by bryevdv** [comment]
According to [this SO answer](https://stackoverflow.com/questions/19304157/getting-the-reason-why-websockets-closed-with-close-code-1006):

> Note that Chrome will often report a close code 1006 if there is an error during the HTTP Upgrade to Websocket (this is the step before a websocket is technically "connected"). For reasons such as bad authentication or authorization, or bad protocol use 

My first guess would be that the cloud service has some kind of proxy in front that is not properly configure to proxy `wss` web sockets

**Comment by bryevdv** [comment]
So actually, I would request that we take this discussion to the mailing list for now to explore whether there are usage issue first:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

If it is determined there is an actual bug of some sort we can re-open this or make a new issue, as appropriate.
