### ISSUE TITLE
Npm detection on Windows x64 fails

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7259]
If Node.js is installed as instructed, from the default channel using just `conda install nodejs`, `node` executable file and `npm` executable file will be in different locations:
```
(bokeh-test) C:\Users\p-himik>where npm
C:\Users\p-himik\Anaconda3\envs\bokeh-test\npm
C:\Users\p-himik\Anaconda3\envs\bokeh-test\npm.cmd
```

```
(bokeh-test) C:\Users\p-himik>where node
C:\Users\p-himik\Anaconda3\envs\bokeh-test\Library\bin\node.exe
```

Arguably, Node.js installation in the default channel is broken, since Node.js from `conda-forge` has executables in one place:
```
(bokeh-test) C:\Users\p-himik>where npm
C:\Users\p-himik\Anaconda3\envs\bokeh-test\npm
C:\Users\p-himik\Anaconda3\envs\bokeh-test\npm.cmd
```

```
(bokeh-test) C:\Users\p-himik>where node
C:\Users\p-himik\Anaconda3\envs\bokeh-test\node.exe
```

The same result is achieved if working with the root environment.

**Comment by p-himik** [comment]
My bad - it's not the actual path itself since it's not included in the detection, but the absence of `.cmd` extension. Just `npm` is a shell script that can't be run in `cmd`.

**Comment by mattpap** [comment]
Looks like a duplicate of #6462.

**Comment by p-himik** [comment]
You're right, I'll add the information there.
