### ISSUE TITLE
Issue when updating a graph after clicking on a glyph bar

### ISSUE THREAD

**Issue by TomTomFox** [bokeh/bokeh#7262]
Hello everyone,

First of all, thank you for your work.

I did a small app server using bokeh which works fine under bokeh version 0.12.05 but not with the 0.12.11

#### software version info:
Windows 10
Anaconda 16.2
Python 3.6
Bokeh 0.12.11 / But works fine with version 0.12.05
Tested under Firefox 56 and Chrome 62

#### 
I am expecting the graph to update when I click on a bar and show another graph.
But when I click two times on a bar the graph disapears

May be the fact that my function "function_source" is called recursively is a problem.

Here is the code:

```
from bokeh.plotting import figure, curdoc
from bokeh.models import ColumnDataSource

import math

RESET ={'0d': {'glyph': None, 'indices': []}
                 , '1d': {'indices': []}
                 , '2d': {'indices': {}}}
OUTSIDE = {'0d': {'glyph': None, 'get_view': {}, 'indices': []}
                 , '1d': {'indices': []}
                 , '2d': {'indices': {}}}

init = ['BAR1', 'BAR2', 'BAR3', 'BAR4']
first_click = ['BAR5', 'BAR6', 'BAR7', 'BAR8', 'BAR9', 'BAR10']
second_click = ['BAR11', 'BAR12']

init_value = [7,3,4,9]
first_click_value = [9,3,7,2,9,5]
second_click_value = [1,8]

data_src = dict(segmentation=init, prix=init_value)
source = ColumnDataSource(data=data_src)

p = figure(x_range=init
            , y_range=(0,10)
            , plot_width=1000
            , plot_height=600
            , title="Awesome graph"
            , toolbar_location='below'
            , tools = "tap,wheel_zoom,box_zoom")

p.vbar(x='segmentation'
       , top='prix'
       , width=0.8
       , source=source
       )

p.xaxis.major_label_orientation = math.pi/6

count=0
# create a callback that will add a number in a random location
def function_source(attr,old,new):
    global count

    if new==RESET:
        print('reset')
        return
    elif new==OUTSIDE:  
        print('outside')
        count-=1
        count=max(count, 0)
    else:
        print('inside')
        print('click on bar indice', new['1d']['indices'][0])
        count+=1
        count=min(count, 2)
       
    print('count', count)
    if count==0:
        source.data = dict(segmentation=init, prix=init_value)
        p.x_range.factors=init
    elif count==1:
        source.data = dict(segmentation=first_click, prix=first_click_value)
        p.x_range.factors=first_click
    else:
        source.data = dict(segmentation=second_click, prix=second_click_value)
        p.x_range.factors=second_click
    
    source.selected.update(RESET)
    
    
source.on_change('selected',function_source)    
curdoc().add_root(p)
```

![image](https://user-images.githubusercontent.com/34096816/33395457-d34d0512-d545-11e7-9952-f66480703dd1.png)

Thank you

**Comment by bryevdv** [comment]
cc @mattpap @clairetang6 naturally hours after we discuss the notion that setting selections is believe to be rare, there is an example/question about it... If you have any immediate thoughts about this please chime in

@TomTomFox I'm not sure offhand, we will look into it as soon as we are able. Please be advised, however: The way selections are handled in Bokeh is currently being completely overhauled, and will probably necessitate some breaking changes. We regret this, but the selection handling has been in bad need of re-doing for a long time, but we only now have resources to tackle it (and any breaking changes must be made before a 1.0 release).

**Comment by bryevdv** [comment]
@TomTomFox I am not entirely sure about your exact intent, but with code just merged to master (will be in a dev build next week) you can examine and set `source.selected.indices`, which is jusst a list of indices, instead of the complicated dict structure. Some minor tweaking to your code shows updates happening.

**Comment by bryevdv** [comment]
Closing, as the selection refactor PR was merged
