### ISSUE TITLE
Bokeh on Cloud9

### ISSUE THREAD

**Issue by mgmoulton** [bokeh/bokeh#7263]
I did not get a chance to respond before you closed the topic.

The html file you generated works fine, but so does an html file I get if I add output_file(my.html).

I cannot the get show() command or the Bokeh server to work.  Both generate a blue screen.

**Comment by bryevdv** [comment]
My response was that this is very likely a usage problem, i.e. a support question, and that the appropriate place for support questions is the mailing list, and *not* the issue tracker, which I will now reiterate: the appropriate place for technical support is the [public mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh)

Please respect this request,  and continue any discussion there. I will add that you stand a much better chance of finding help if you include ***much more*** information. Screenshots, code, console logs. All the things mentioned in the issue template. It is nearly impossible to respond meaningfully or helpfully with as little information as you have given to go on.
