### ISSUE TITLE
svg & Arrow triggers Exception

### ISSUE THREAD

**Issue by waywatcher** [bokeh/bokeh#7271]
Minimal example:
```
plot = figure()
plot.output_backend = "svg"
plot.add_layout(Arrow(end=OpenHead()))
export_svgs(plot, "test.svg")
```
Throws this warning
_WARNING:bokeh.io.export:The webdriver raised a TimeoutException while waiting for a 'bokeh:idle' event to signify that the layout has rendered. Something may have gone wrong._

and fails to render Plot properly.
using bokeh-0.12.11.

**Comment by bryevdv** [comment]
You’ll have to provide much much more information for us to have any hope of investigating. A *complete* minimal example to start, as well as platform information and a list of all relevant package versions including selenium and phantomjs and descriptions of how you installed them.

**Comment by bryevdv** [comment]
@waywatcher will you be able to provide the requested information? If not this issue will have to be closed as un-actionable.

**Comment by bryevdv** [comment]
Closing for lack of information. Pleas feel free to re-open if more information can be provided.
