### ISSUE TITLE
Codec error on windows

### ISSUE THREAD

**Issue by gepcel** [bokeh/bokeh#7272]
### Versions

    os: Windows 10 x64 Professional with Chinese language
    python: 3.6.3
    bokeh: 0.12.10
    tornado: 4.5.2

#### Error 1: 

On windows system, if a script file with some charactor other than ascii is saved in utf-8 codec, and then run `bokeh serve script.py`, an error will be given like:

    D:\>bokeh serve --show script-utf8.py
    ERROR:'gbk' codec can't decode byte 0xad in position 201: illegal multibyte sequence

There is a similar [SO question](https://stackoverflow.com/questions/46187520/python-trouble-with-encoding-on-windows-when-run-bokeh-serve-bokeh-plotting-li). I've figured this out in the answer. It's because the [line of code](https://github.com/bokeh/bokeh/blob/f3d13963a36130ec126f0a1e87d3abcf8e5870f7/bokeh/application/handlers/script.py#L53) as mentioned open the file in the default codec ('gbk' in this case).

#### Error 2
If the script file is changed to gbk codec, then the file can be opened properly. But another kind of error will be given:

```
D:\>bokeh serve --show script-gbk.py
2017-12-03 09:50:29,811 Starting Bokeh server version 0.12.10 (running on Tornado 4.5.2)
2017-12-03 09:50:29,816 Bokeh app running at: http://localhost:5006/script
2017-12-03 09:50:29,817 Starting Bokeh server with process id: 1544
--- Logging error ---
--- Logging error ---
--- Logging error ---
Exception ignored in: <bound method Future.__del__ of <tornado.concurrent.Future object at 0x0000025F39BE77F0>>
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tornado\concurrent.py", line 341, in __del__
    tb = traceback.format_exception(*self._exc_info)
  File "C:\Anaconda3\lib\traceback.py", line 117, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "C:\Anaconda3\lib\traceback.py", line 510, in __init__
    self._load_lines()
  File "C:\Anaconda3\lib\traceback.py", line 522, in _load_lines
    self.__context__._load_lines()
  File "C:\Anaconda3\lib\traceback.py", line 522, in _load_lines
    self.__context__._load_lines()
  File "C:\Anaconda3\lib\traceback.py", line 522, in _load_lines
    self.__context__._load_lines()
  [Previous line repeated 3 more times]
  File "C:\Anaconda3\lib\traceback.py", line 520, in _load_lines
    frame.line
  File "C:\Anaconda3\lib\traceback.py", line 282, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Anaconda3\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "C:\Anaconda3\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Anaconda3\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "C:\Anaconda3\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 199: invalid continuation byte
```

I haven't located the source code of this error. But I managed to give a simplest example, and it has something to do with `gbk` charactor in the pandas data file directory.

### Example code:

Codes of this example: 
```python
import pandas as pd
from bokeh.io import curdoc
from bokeh.layouts import layout
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

# Set up data
d = pd.read_csv('d:/中文.csv', index_col=0)
source = ColumnDataSource(data=dict(x=d.x, y=d.y))

# Set up plot
plot = figure(plot_height=400, plot_width=400, title="my sine wave",
              tools="crosshair,pan,reset,save,wheel_zoom",
              x_range=[0, 12], y_range=[-2.5, 2.5])
plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)
curdoc().add_root(plot)
```
The codes is saved in `gbk` codec named `script-gbk.py`, and `utf-8` codec named `script-utf8.py` seperately.

### Data used in this example:

```python
import numpy as np
import pandas as pd

N = 200
x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)
d = pd.DataFrame(dict(x=x, y=y))
d.to_csv('d:/中文.csv')
```

**Comment by bryevdv** [comment]
@gepcel do you have any concrete suggestion for a course of action? This is not an area of expertise for me so I an uncertain what a good way to proceed would be.

**Comment by gepcel** [comment]
If to make all things easy, changing this line to the following, makes all two errors go away. Maybe add some instruction in the doc that all scripts file should be saved in 'utf-8' codec, and even more some exception messages when it's not.

```python
with open(filename, 'r', encoding='utf8') as f:
```

And from what I tests, scripts files in other codec (eg: 'gbk') all works as long as there's no non-ascii charactor in paths. I can use Chinese charactor in 'title', 'tick-label', ... almost everything other than a `path`. So if someone can locate and fix this, `bokeh` then is more robust and advanced. Then we can maybe make 'utf-8' the default, and `bokeh serve --encoding other_codec` to use aother codec.

**Comment by bryevdv** [comment]
@gepcel That seems reasonable. Would you be able to make a small PR to make that change?

**Comment by gepcel** [comment]
@bryevdv 
To make sure, do you mean change [here](https://github.com/bokeh/bokeh/blob/f3d13963a36130ec126f0a1e87d3abcf8e5870f7/bokeh/application/handlers/script.py#L53) to:

```python
with open(filename, 'r', encoding='utf8') as f:
```

This is simple enough that I can do.

**Comment by bryevdv** [comment]
@gepcel actually after thinking a bit more, that won't quite work because we still currently support python 2.7 which does not support and `encoding` keyword for `open`. We will need to find a solution that works for python 2.7 as well.

**Comment by mattpap** [comment]
`io.open()` supports `encoding` on 2.7. I'm pretty sure we already discussed we should be using `io.open()` instead of `open()`.

**Comment by bryevdv** [comment]
@gepcel I think this should work:
```
with io,open(filename, 'r', encoding='utf8') as f:
```
look forward to your PR!

**Comment by bryevdv** [comment]
I believe this was resolved in https://github.com/bokeh/bokeh/pull/8202
