### ISSUE TITLE
Chord diagram not showing connections

### ISSUE THREAD

**Issue by robroc** [bokeh/bokeh#7285]
System info:
Bokeh 0.12.7
Python 3.6 
pandas 0.19.2
Windows 7, 64-bit
Chrome 62
Jupyter notebook 4.3.1 on Anaconda 4.3.30

Chord diagram made in Jupyter notebook from pandas dataframe with 169 rows does not render edges between nodes. The edges show up briefly in grey when the chart is panned, but promptly disappears. Same with the exported HTML file. 

It also takes a very long time to process the code, to load the chart, and sometimes crashes the notebook tab. HTML export file is huge at 341 MB. Network tab in Chrome registered a 31.4 second load time.

See animated gif for the behaviour.

![bokeh](https://user-images.githubusercontent.com/1219001/33676419-acfa7bfe-da83-11e7-9f96-7c704967ec2f.gif)

Code:

```
import pandas as pd
from io import StringIO
from bokeh.charts import Chord, output_file
from bokeh.io import show, output_notebook
output_notebook()

data = StringIO('''Destination	Newfoundland and Labrador	Prince Edward Island	Nova Scotia	New Brunswick	Quebec	Ontario	Manitoba	Saskatchewan	Alberta	British Columbia	Yukon	Northwest Territories	Nunavut
Newfoundland and Labrador	0	330	3450	1250	685	8625	515	420	6595	1090	45	255	300
Prince Edward Island	235	0	1665	1270	295	2875	210	115	1075	490	20	25	30
Nova Scotia	2895	1670	0	6800	2635	16700	1140	920	7080	3920	105	460	220
New Brunswick	1245	1095	5750	0	4645	9130	710	435	4275	1635	90	195	135
Quebec	810	380	2265	4370	0	32635	1500	940	5550	6480	165	130	130
Ontario	5690	2595	16815	9480	54235	0	12235	6615	33790	37725	645	805	850
Manitoba	330	85	1030	745	1515	11060	0	4100	6575	4980	80	185	165
Saskatchewan	380	185	1265	870	1670	11785	6045	0	18120	7445	225	530	65
Alberta	6290	1905	14370	9355	15645	72960	14055	21840	0	66290	755	2445	175
British Columbia	1630	690	5115	2610	10275	50065	10810	11375	73655	0	1625	1080	190
Yukon	55	20	195	85	170	900	240	105	730	1430	0	275	80
Northwest Territories	165	30	380	200	310	1350	240	155	1200	745	110	0	125
Nunavut	155	25	270	140	235	965	110	70	170	265	30	100	0
''')

df= pd.read_csv(data, sep='\t')
df = pd.melt(df, id_vars='Destination', var_name = 'Origin', value_name = 'Migrants')
df = df[df.Target != df.Source]
chord_from_df = Chord(df, source='Origin', target='Destination', value='Migrants')
output_file('chord-diagram-bokeh.html', mode='inline')

show(chord_from_df)
```

**Comment by bryevdv** [comment]
`Chord` is part of `bokeh.charts` which was deprecated and subsequently removed from Bokeh quite some time ago. There will be no further development on it. There is an [open issue to add a Chord chart to Holoviews](https://github.com/ioam/holoviews/issues/2137) which is a high level API on top of Bokeh, and the appropriate place for this type of feature at this point.
