### ISSUE TITLE
Sort application names in index page

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#7289]
When I create a Bokeh server application I provide a dictionary of named applications:

```python
Server({'foo': ..., 'bar': ...})
```

When I go to the index.html page of my bokeh server it would be convenient to have these sorted alphabetically.  That does not appear to currently be the case.

![image](https://user-images.githubusercontent.com/306380/33723780-8eb6aeb6-db3b-11e7-948a-df4caa506e7a.png)

Is there a way to acheive this?

**Comment by bryevdv** [comment]
Not AFAIK. If you'd like to make a tiny PR this is probably the place:

https://github.com/bokeh/bokeh/blob/master/bokeh/server/views/root_handler.py#L32
