### ISSUE TITLE
HoverTool with attachment="vertical" incorrectly positions tooltips

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7291]
Bokeh 0.12.13

I think it happened after the recent change of the coordinates origin.
When you create `HoverTool` with `attachment="vertical"`, the tooltip is supposed to be above a point when the point is below the center of the plot, and below the point when it's above the center of the plot. Right now, the directions are swapped.

**Comment by bryevdv** [comment]
cc @mattpap
