### ISSUE TITLE
ColumnDataSource missing `get` method in CustomJS?

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#7301]
When trying to run this [example]( https://github.com/jakirkham/bokeh_examples/blob/master/Bokeh_Example_16.ipynb ) with `bokeh` 0.12.13, I tried to select the polygons shown in the left. However I encounter the following error in the JavaScript debugger. Environment file included in details below. Running Firefox 57.0.1 on macOS 10.11.6. Can provide more details if needed.

```javascript
TypeError: cb_obj.get is not a function
```

<details>
<summary>Environment:</summary>

```yaml
# filename test_environment.yml
name: test
channels:
- bokeh
- conda-forge
- defaults
dependencies:
- bokeh=0.12.13=py_0
- appnope=0.1.0=py27_0
- backports=1.0=py27_1
- backports.shutil_get_terminal_size=1.0.0=py_3
- backports_abc=0.5=py27_0
- blas=1.1=openblas
- bleach=2.0.0=py27_0
- ca-certificates=2017.11.5=0
- certifi=2017.11.5=py27_0
- configparser=3.5.0=py27_0
- decorator=4.1.2=py27_0
- entrypoints=0.2.3=py27_1
- enum34=1.1.6=py27_1
- functools32=3.2.3.2=py27_1
- futures=3.2.0=py27_0
- html5lib=0.999999999=py27_0
- ipykernel=4.7.0=py27_0
- ipython=5.5.0=py27_0
- ipython_genutils=0.2.0=py27_0
- jinja2=2.10=py27_0
- jsonschema=2.6.0=py27_0
- jupyter_client=5.1.0=py27_0
- jupyter_core=4.4.0=py_0
- libgfortran=3.0.0=0
- libsodium=1.0.15=1
- markupsafe=1.0=py27_0
- mistune=0.8.3=py_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py27_0
- ncurses=5.9=10
- notebook=5.2.2=py27_1
- numpy=1.13.3=py27_blas_openblas_201
- openblas=0.2.20=6
- openssl=1.0.2m=0
- pandoc=2.0.4=0
- pandocfilters=1.4.1=py27_0
- pathlib2=2.3.0=py27_0
- pexpect=4.3.0=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_0
- prompt_toolkit=1.0.15=py27_0
- ptyprocess=0.5.2=py27_0
- pygments=2.2.0=py27_0
- python=2.7.14=1
- python-dateutil=2.6.1=py27_0
- pyyaml=3.12=py27_1
- pyzmq=16.0.2=py27_2
- readline=6.2=0
- scandir=1.6=py27_0
- setuptools=38.2.4=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.11.0=py27_1
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_1
- terminado=0.8.1=py27_0
- testpath=0.3.1=py27_0
- tk=8.5.19=2
- tornado=4.5.2=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- webencodings=0.5=py27_0
- wheel=0.30.0=py_1
- yaml=0.1.7=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- futures-compat=1.0=py2_0
prefix: /zopt/conda2/envs/test
```

</details>

**Comment by mattpap** [comment]
`HasProps.get()` and `set()` were deprecated over a year ago and removed recently. Use `getv()` or `setv()` if there is a reason for that. The preferred way of accessing or modifying model properties is though usual JavaScript attributes, so e.g. `cb_obj.data` and `cb_obj.data = {...}`.

**Comment by jakirkham** [comment]
Thanks for the info. Will give that a try.

Honestly did not know they were deprecated. Guessing this deprecation was coming through in the JavaScript console. Is it possible to pick up these BokehJS deprecation warnings on the Python side as well?

**Comment by mattpap** [comment]
This was communicated though standard `console.warn()`. I would expect jupyter notebook to print those in cell output, as it already is very chatty about everything else, but maybe this case isn't implemented. 

> Is it possible to pick up these BokehJS deprecation warnings on the Python side as well?

It's not possible currently, but something that could potentially be implemented. However, I think we will have to rethink overall error handling in callbacks and cutomsj, because currently it's either JS console or nothing.

**Comment by jakirkham** [comment]
I see. Yeah hadn't seen the warning in the notebook. If you know of some way to get to the notebook to be more vocal about these JavaScript warnings, would be happy to try something like this.

Ok. Should I open a new issue or is there one already?
