### ISSUE TITLE
DataTable editing regression

### ISSUE THREAD

**Issue by zaript** [bokeh/bokeh#7304]
#### Software versions:
bokeh 0.12.11, 0.12.13
MacOS (latest Chrome, Firefox, Safary), Windows 10 (Opera)

#### Description of expected behavior and the observed behavior
Expeted to get table with editable fields. Got table with non-editable fields.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, TableColumn, DataTable, IntEditor

def make_doc(doc):
    source = ColumnDataSource({'Field': [x for x in range(3)]})
    table = DataTable(
        source=source,
        columns=[TableColumn(field="Field", title='Field', editor=IntEditor())],
        editable=True
    )
    doc.add_root(table)

make_doc(curdoc())
```

#### Stack traceback and/or browser JavaScript console output
JS console output:
```
TypeError: this.args is undefined[Learn More]
[405]/c</t.prototype.render
cell_editors.js:23
[405]/c</t.prototype.initialize
cell_editors.js:19
t
view.js:20
e
dom_view.js:9
t
cell_editors.js:13
t
cell_editors.js:267
makeActiveCellEditable
slick.grid.js:2641
setActiveCellInternal
slick.grid.js:2540
gotoCell
slick.grid.js:3117
handleDblClick
slick.grid.js:2373
dispatch
jquery.js:3815
[414]/r.dispatch
jquery.event.drag-2.3.0.js:382
add/m.handle
```

**Comment by bryevdv** [comment]
cc @mattpap error is here:
```
CellEditorView.prototype.render = function () {
            _super.prototype.render.call(this);
            this.args.container.appendChild(this.el);
            this.el.appendChild(this.inputEl);
            this.renderEditor();
            this.disableNavigation();
            return this;
        };
```
or in the original source:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/tables/cell_editors.coffee#L27

Unless I am mistaken this means no cell editors currently function. Was there a change in calling convention to `render` ?

**Comment by mattpap** [comment]
This is an order of initialization issue. Looking at the code this shouldn't ever have worked.

**Comment by mattpap** [comment]
I remember now. This was broken when making constructors adhere to ES6 standard, that doesn't allow `this` access before super constructor is called. The new order gets in conflict with when `render` is called.
