### ISSUE TITLE
AttributeError: 'function' object has no attribute 'safe_to_fork'

### ISSUE THREAD

**Issue by devNaresh** [bokeh/bokeh#7310]
Bokeh Server standalone server application is giving Attribute Error.
cmd -- `python standalone_embed.py`
https://github.com/bokeh/bokeh/blob/0.12.13/examples/howto/server_embed/standalone_embed.py

**Comment by bryevdv** [comment]
@devNaresh The issue template specifically asked for version and platform information. Why did you ignore it. We cannot investigate without that information. Offhand my guess is that you are running a `0.12.13` example but actually have an older version of Bokeh installed. If that is not the case, please feel free to re-open *with the requested information*.
