### ISSUE TITLE
Add support for line breaks in Label

### ISSUE THREAD

**Issue by PhML** [bokeh/bokeh#7317]
The code below does not render the \n as a new line (Bokeh 0.12.13)

```python
from bokeh.plotting import figure, output_file, show
from bokeh.models import  Label

output_file("test.html")
fig = figure()
fig.line(x=range(10), y=range(10))
label = Label(x=2, y=8, text="New\nLine")
fig.add_layout(label)
show(fig)
```
A similar issue (#994) was solved by #6879.

**Comment by birdsarah** [comment]
Ref a SO enquiry: https://stackoverflow.com/questions/48203055/bokeh-label-does-not-support-multi-line

**Comment by bryevdv** [comment]
In the mean time, as a workaround, the `text` glyph does support line breaks.

**Comment by birdsarah** [comment]
Can text be positioned on plot in screen units (so it doesn't move on pan)? (I did look at docs, but couldn't figure it out).

**Comment by bryevdv** [comment]
No,  glyph coordinates are data space

**Comment by birdsarah** [comment]
Thanks (sorry, it's been a minute - lots to remember)

**Comment by hiramf** [comment]
Any updates on this? Working with some *very* long categorical labels and text wrapping would be awesome.

**Comment by levaid** [comment]
I would like to +1 this issue. I would like to add labels to some complex data, but they also need background, and only the Label can do it.

**Comment by Cuahchic** [comment]
I also would love this feature please!

**Comment by garrettseepersad** [comment]
+1

**Comment by QingFengpoor** [comment]
+1 .  This feature can reduce a lot of trouble.

**Comment by harabat** [comment]
Any updates on this?

**Comment by TarekHC** [comment]
Just to show some more interest on this... I give a +1!

**Comment by nikeshm** [comment]
+1 to this! This feature would certainly help a lot.

**Comment by GilShoshan94** [comment]
+1

**Comment by jonn-smith** [comment]
This would be very helpful to me as well.

**Comment by varunchaturmutha** [comment]
Line break for axis labels!

**Comment by RolandRitt** [comment]
+ 1

**Comment by theresepol** [comment]
+1

**Comment by jakobjgu** [comment]
+1

**Comment by mullimanko** [comment]
+1

**Comment by shenshan** [comment]
+1

**Comment by Patrickens** [comment]
+1

**Comment by kansiator** [comment]
+1

**Comment by nabilahmed739** [comment]
+1 for text wrapping or multiline in legend labels

**Comment by tal-z** [comment]
+1 here as well!

**Comment by mcwrinn** [comment]
+1  !  thanks
