### ISSUE TITLE
Reset tool fails for multirange when one range has no info

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#732]
it fails here.
https://github.com/ContinuumIO/bokeh/blob/multirange/bokehjs/src/coffee/common/plot.coffee#L340-L360

In my app I frequently have a second Y range that has no axes applied or range info.  That causes `start-end` to be `NaN`  because `infinity + -infinity = NaN`.

@bryevdv what was the idea behind checking for `good_vals`?  I want to understand the intent.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
