### ISSUE TITLE
components not working with notebook show in the same cell

### ISSUE THREAD

**Issue by ericmjl** [bokeh/bokeh#7323]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

`bokeh`: 0.12.11
`python`: 3.6
OS: macOS
Browser: Safari

#### Description of expected behavior and the observed behavior

When using components with stacked vbar or hbar, an error is thrown. In the notebook environment, I have no issues displaying the figure.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
from bokeh.plotting import figure
from bokeh.io import output_notebook, show
from bokeh.embed import components
from bokeh.models import ColumnDataSource

output_notebook()

data = {'class': ['a', 'b'],
        '2015': [1, 2],
        '2016': [2, 3],
        '2017': [3, 5]}

source = ColumnDataSource(data)

years = ['2015', '2016', '2017']
p = figure(y_range=data['class'])
p.hbar_stack(stackers=years, y='class', source=source, height=0.5, color=['red', 'blue', 'green'])
components(p)
```

#### Stack traceback and/or browser JavaScript console output

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/embed/standalone.py in _add_doc_to_models(doc, models)
    322                 try:
--> 323                     doc.add_root(model)
    324                     models_to_dedoc.append(model)

~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/document/document.py in add_root(self, model, setter)
    242         finally:
--> 243             self._pop_all_models_freeze()
    244         self._trigger_on_change(RootAddedEvent(self, model, setter))

~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/document/document.py in _pop_all_models_freeze(self)
    922         if self._all_models_freeze_count == 0:
--> 923             self._recompute_all_models()
    924 

~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/document/document.py in _recompute_all_models(self)
    945         for a in to_attach:
--> 946             a._attach_document(self)
    947         self._all_models = recomputed

~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/model.py in _attach_document(self, doc)
    552         if self._document is not None and self._document is not doc:
--> 553             raise RuntimeError("Models must be owned by only a single document, %r is already in a doc" % (self))
    554         doc.theme.apply_to_model(self)

RuntimeError: Models must be owned by only a single document, ColumnDataSource(id='d7459854-95b5-4527-9108-e85dc7ee6693', ...) is already in a doc

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-23-9ba2b2821a0e> in <module>()
      2 p = figure(y_range=data['class'])
      3 p.hbar_stack(stackers=years, y='class', source=source, height=0.5, color=['red', 'blue', 'green'])
----> 4 components(p)

~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/util/api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/embed/standalone.py in components(models, wrap_script, wrap_plot_info, theme)
    209 
    210     # 2) Append models to one document. Either pre-existing or new and render
--> 211     with _ModelInDocument(models, apply_theme=theme):
    212         (docs_json, render_items) = standalone_docs_json_and_render_items(models)
    213 

~/anaconda/envs/my_env/lib/python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/embed/standalone.py in _ModelInDocument(models, apply_theme)
    304         doc.theme = apply_theme
    305 
--> 306     models_to_dedoc = _add_doc_to_models(doc, models)
    307 
    308     if settings.perform_document_validation():

~/anaconda/envs/my_env/lib/python3.6/site-packages/bokeh/embed/standalone.py in _add_doc_to_models(doc, models)
    329                            'single document). This may indicate a usage '
    330                            'error.'.format(child, model))
--> 331                     raise RuntimeError(msg)
    332     return models_to_dedoc
    333 

RuntimeError: Sub-model (id='d7459854-95b5-4527-9108-e85dc7ee6693', ...) of the root model Figure(id='464f72aa-dbc1-4bc1-8fab-98089aed6744', ...) is already owned by another document (Models must be owned by only a single document). This may indicate a usage error.
```
#### Screenshots or screencasts of the bug in action

No screenshots necessary.

**Comment by ericmjl** [comment]
I believe this is going to be common between vbar and hbar. This issue does prevent me from using stacked vbar and hbar in other applications.

**Comment by bryevdv** [comment]
It's neither, `components` is having a bad interaction with the notebook because of the way we have to create a document for every output cell. I'm not sure that there is anything we can do except add a warning in the docs. For comparison, this code works fine outside the notebook:
```
# code goes here between backticks
from bokeh.plotting import figure
from bokeh.io import output_notebook, show
from bokeh.embed import components
from bokeh.models import ColumnDataSource

output_notebook()

data = {'class': ['a', 'b'],
        '2015': [1, 2],
        '2016': [2, 3],
        '2017': [3, 5]}

source = ColumnDataSource(data)

years = ['2015', '2016', '2017']
p = figure(y_range=data['class'])
p.hbar_stack(stackers=years, y='class', source=source, height=0.5, color=['red', 'blue', 'green'])
components(p)
```

**Comment by bryevdv** [comment]
@ericmjl Actually your given code works fine:

<img width="928" alt="screen shot 2017-12-15 at 09 33 56" src="https://user-images.githubusercontent.com/1078448/34048930-22e51416-e17b-11e7-9b78-555cb29cb52e.png">

I'm guessing you really have `show` and `components` in the same cell? That will never able to work.

**Comment by ericmjl** [comment]
Hi @bryevdv! When run your way, with everything in a single cell, everything works fine. However, when the code are split up into multiple cells, then the error shows up. 

I've listed the steps below in case it's useful to reproduce.

Run the following code above in a Jupyter notebook.

```
# Cell 1
from bokeh.plotting import figure
from bokeh.io import output_notebook, show
from bokeh.embed import components
from bokeh.models import ColumnDataSource

output_notebook()

# Cell 2
data = {'class': ['a', 'b'],
        '2015': [1, 2],
        '2016': [2, 3],
        '2017': [3, 5]}

source = ColumnDataSource(data)

# Cell 3

years = ['2015', '2016', '2017']
p = figure(y_range=data['class'])
p.hbar_stack(stackers=years, y='class', source=source, height=0.5, color=['red', 'blue', 'green'])
script, div = components(p)
show(p)
```

On first run, everything works just fine.

Comment out `show(p)`, then re-run cell 3. The error will show up. 

If I merge Cell 2 and Cell 3 afterwards, no errors are thrown. 

If I could ask, why is it that with the ColumnDataSource specified in a different cell, the error shows up?

-----

> I'm not sure that there is anything we can do except add a warning in the docs stating that components is not useful inside the notebook

Agreed, and I also think it'll be useful to throw a warning or something. I was using `components()` in the notebook environment because I wanted to get the JavaScript and HTML string out from a long, complicated analysis that I had already written but wasn't ready to refactor out of a notebook, so that I could embed it in a separate Reveal.js presentation. (Reveal.js embedding is probably not one of the use cases the bokeh team has encountered often, I'm guessing, given the number of questions surrounding it.)

**Comment by ericmjl** [comment]
(btw, happy to put in a short PR for the warning, if you're okay with it.)

**Comment by bryevdv** [comment]
> If I could ask, why is it that with the ColumnDataSource specified in a different cell, the error shows up

@ericmjl Offhand, I'm not sure. As I mentioned the nature of the notebook requires us to jump through alot of weird hoops 

>(btw, happy to put in a short PR for the warning, if you're okay with it.)

 For sure, I think that would be a good idea, ideally in the `components` docstring as well as the user guide embedding section.  My *guess*  is that `components` will always work if it is in a cell that does not also have a call to `show`. If you concur, I think that's probably the best pointed guidance we can provide.
