### ISSUE TITLE
output_png and output_svgs fails in the Settings.phantomjs_path( ) function.  

### ISSUE THREAD

**Issue by SweetsRepo** [bokeh/bokeh#7327]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh:
  bokeh==0.12.13
Related Dependencies:
  Pillow==4.3.0
  selenium==3.8.0
  phantomjs-prebuilt==2.1.16
Python:
  python==3.6.3
OS:
  Windows 7 and Windows 10
Run in: 
  Cmder and Command Prompt
 
#### Description of expected behavior and the observed behavior
Expected Behavior:
  When calling the export_png function the plot should be exported to the filename given. 

Observed Behavior 1:
  Function fails because BOKEH_PHANTOMJS_PATH environment variable does not get set on install of 
  bokeh or phantomjs. Related traceback is shown in Traceback 1 below. 

  Manually set variable to the install location of phantomjs:
  set BOKEH_PHANTOMJS_PATH=C:\Users\Christopher\AppData\Roaming\npm\phantomjs.exe

Observed Behavior 2:
  Function fails due to Popen([phantomjs_path, '--version'], stdout=PIPE, stderr=PIPE) returning OSError: 
  [WinError 193]. Related traceback is shown in Traceback 2 below. 

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.io import export_png
from bokeh.plotting import figure, output_file, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

export_png(p, filename="plot.png")
```
#### Stack traceback and/or browser JavaScript console output
Traceback 1:
D:\PythonWorkspace\bokeh_bug>python bug.py
Traceback (most recent call last):
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\util\dependencies.py", line 62, in detect_phantomjs
    proc = Popen([phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 17, in <module>
    export_png(p, filename="plot.png")
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\util\api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\io\export.py", line 83, in export_png
    image = get_screenshot_as_png(obj, height=height, width=width, driver=webdriver)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\util\api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\io\export.py", line 167, in get_screenshot_as_png
    detect_phantomjs()
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\util\dependencies.py", line 66, in detect_phantomjs
    "npm install -g phantomjs-prebuilt"')
RuntimeError: PhantomJS is not present in PATH. Try "conda install phantomjs" or  "npm install -g phantomjs-prebuilt"

Traceback 2:
Traceback (most recent call last):
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\util\dependencies.py", line 62, in detect_phantomjs
    proc = Popen([phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug.py", line 17, in <module>
    export_png(p, filename="plot.png")
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\util\api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\io\export.py", line 83, in export_png
    image = get_screenshot_as_png(obj, height=height, width=width, driver=webdriver)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\util\api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\io\export.py", line 167, in get_screenshot_as_png
    detect_phantomjs()
  File "C:\Users\Christopher\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bokeh\util\dependencies.py", line 66, in detect_phantomjs
    "npm install -g phantomjs-prebuilt"')
RuntimeError: PhantomJS is not present in PATH. Try "conda install phantomjs" or "npm install -g phantomjs-prebuilt"

**Comment by bryevdv** [comment]
@SweetsRepo It is not appropriate for Bokeh to set any environment variables, including `BOKEH_PHANTOMJS_PATH` for two reasons:

* Generally speaking, env vars are for *users* to set to override how libraries and programs work, and not the converse. And even if we wanted to, there is no system mechanism to allow us to. It would have to be something that a package manager (with access to modify system/shell configuration) does at library install time, and we have no control over that. 

* Even if we could and wanted to, we don't know what value to set it to which is actually the heart of the matter. We make an effort to locate `phantomjs` in some sort-of standard locations , but if it is not installed in a place that Bokeh knows to look in, then *only you* have the information to fix that. 

At best, we could add mention of `BOKEH_PHANTOMJS_PATH` in the error message, so user's have a better idea of how to set it explicitly themselves when Bokeh can't locate phantomjs. Would you be interested in making a small PR to do that?

**Comment by SweetsRepo** [comment]
@bryevdv These are fair points, however does not fully mitigate the issue I was trying to bring up. If you follow the function calls from phantomjs_path down, you end with a call to _get( ) which returns return self._environ.get("BOKEH_PHANTOMJS_PATH", default). Even after you've added this environment variable the detect_phantomjs( ) function fails. However running the line 
'''
proc = Popen(f"{phantomjs_path} --version", shell=True)
''''
Instead of 
''''
proc = Popen([phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
''''
Note that I have now tested in both Windows and Ubuntu 16.04 and this change is only needed in Windows-based systems. 

I can work on creating a PR which tells users they should set the BOKEH_PHANTOMJS_PATH variable, as well as adds in the above change to detect_phantomjs( ). In the PR I won't use an f-string to run the process, that way it will work for python versions older than 3.6

**Comment by bryevdv** [comment]
@SweetsRepo IIRC the use of `shell=True` is usually discouraged, as it presents a potential security risk. I wonder if there are other alternatives to explore first?

**Comment by p-himik** [comment]
Related, at least because of the explanation about `Popen` on Windows and executable files extensions: #6462

@SweetsRepo You set `BOKEH_PHANTOMJS_PATH` to an incomplete path - you have to make it end with `.exe` or whatever's more appropriate.

**Comment by SweetsRepo** [comment]
@bryevdv That is correct. Technically using Pipes is discouraged when calling subprocess.wait( ), perhaps that should change as well?

> This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.
> 
As far as safer ways to check if phantomjs is installed I'm going to see if shutil.which( ) works for detecting it. Haven't used it extensively so I'm not sure what the limitations of the function are. 

@p-himik I've reviewed the my environment variables and realized I initially set it with a .exe extension. Must have mistyped it above; edited now. I've also tried with the .cmd extension as I saw there is a phantomjs.cmd in the folder. This had no affect either.

**Comment by SweetsRepo** [comment]
So I set up an alternative which uses shutil.which( ) to get the path to phantomjs. This will only work in Python 3 and above, so I have left in the original code with a check for if the user is running Python 2. I do have one issue where some underlying process is not being closed. Originally I thought this was the selenium.WebDriver but that doesn't appear to be the case. Any thoughts?

**Comment by bryevdv** [comment]
@SweetsRepo I am not sure offhand, do you want to go ahead and submit a PR? I think that will help focus attention and also allow for other to try out, test etc. Thanks for looking into this!

**Comment by bryevdv** [comment]
Should add: Py2 check is not ideal but I would accept it.

**Comment by SweetsRepo** [comment]
Added pull request. Changed py2 check to a try-except statement.
