### ISSUE TITLE
BokehTornado : TypeError: __init__() got an unexpected keyword argument 'host'

### ISSUE THREAD

**Issue by gst** [bokeh/bokeh#7336]
Hi,

this is with bokeh 0.12.13, I get this traceback :

```
  File "/home/gregory.starck/CRISP-ML/virtualenv-dask-01/local/lib/python2.7/site-packages/bokeh/server/server.py", line 394, in __init__
    tornado_app = BokehTornado(applications, extra_websocket_origins=extra_websocket_origins, prefix=self.prefix, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'host'
```

effectively the `BokeyTornado` class `__init__` method doesn't have this kwarg..

this is with dask-scheduler but the problem is all in bokeh itself.

I can provide a patch if need to be..

**Comment by bryevdv** [comment]
The `host` parameter was deprecated and subsequently removed entirely, several releases ago. You will probably need to upgrade your version of Dask (newer versions have accommodated this change) or downgrade your version of Bokeh.

**Comment by bryevdv** [comment]
c.f. https://bokeh.pydata.org/en/latest/docs/releases/0.12.5.html#host-parameter-obsoleted

**Comment by gst** [comment]
Hi @bryevdv 

thx for quick answer :)
sorry but I don't see any bokeh version above 0.12.13 .. 
where are all these versions ?

thx.

**Comment by bryevdv** [comment]
@gst There are none, `0.12.13` is the latest version. You either need a *newer Dask* (that works with recent Bokeh versions, or an *older Bokeh* (that works with older Dask version)

**Comment by gst** [comment]
have upgraded my dask to latest version (from 0.14.3 to 0.16.0) but still getting the same traceback ? 

.. ah, had to update `distributed` as well. and now it's ok.

thx for infos.
