### ISSUE TITLE
arrow keys don't work if the step of Slider is very small.

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#7349]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

* Jupyter notebook:  5.2.1
* bokeh: 0.12.13

#### Description of expected behavior and the observed behavior

If the step of sliders is very small, arrow key can modify the value of the slider correctly.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models import Slider
from bokeh.layouts import row
from bokeh.io import output_notebook, show
output_notebook()

s1 = Slider(name="s1", start=0, end=1, step=0.01, value=0, format="0[.]00000")
s2 = Slider(name="s2", start=0, end=0.01, step=0.0001, value=0, format="0[.]00000")
show(row(s1, s2))
```

#### Screenshots or screencasts of the bug in action

![bokeh-slider](https://user-images.githubusercontent.com/826871/34368138-eaee9aa4-eaf4-11e7-9881-6e9c18c5f435.gif)

**Comment by bryevdv** [comment]
The issue appears to be that the underlying nouislider is always still returning default two decimal  digits from calls to `.get` regardless of `format` cc @mattpap
