### ISSUE TITLE
Inconsistent conversion of np.nan to JSON data in bokehjs

### ISSUE THREAD

**Issue by yhey** [bokeh/bokeh#735]
When plotting from DataSource with output_file, depending on whether the list-like is numpy.ndarray and other conditions, a numpy.nan is converted sometimes to "NaN" (with quotes) and sometimes to just NaN (without quotes) in the JSON data structure in the resulting html page.

For example:
<pre>
from bokeh.plotting import *
import numpy as np
source = ColumnDataSource()
x = list(range(0, 6))
source.add(name="x", data=x)
y = list()
y.append([np.nan]*6)
y.append([None]*3 + [np.nan]*3)
y.append([np.nan]*3 + [None]*3)
y.append([1.0]*3 + [np.nan]*3)
y.append([np.nan]*3 + [1.0]*3)
y.append([None]*2 + [np.nan]*2 + [None]*2)
y.append([np.nan]*2 + [None]*2 + [np.nan]*2)
y.append([1.0]*2 + [np.nan]*2 + [1.0]*2)
y.append([np.nan]*2 + [1.0]*2 + [np.nan]*2)
for idx,yi in enumerate(y):
    source.add(name="y%d"%idx, data=yi)
    source.add(name="yr%d"%idx, data=np.array(yi))
output_file("test.html")
hold(True)
for idx in range(0, len(y)):
    scatter("x", "y%d"%idx, source=source)
    scatter("x", "yr%d"%idx, source=source)
show()
</pre>
In the resulting html, some of the np.nan are converted to "NaN" while others to NaN.

This difference does not affect the displayed plot in any apparent way (in either case, the associated glyphs are not drawn). However, NaN is not a valid JSON value and an attempt to extract the JSON data structure from the html to be parsed in external tool would fail. It would be nice if np.nan is consistently converted to "NaN" in JSON when output_file() is used.

Thanks.

**Comment by birdsarah** [comment]
HI, I'm not sure when, but somewhere along the way, it looks like this got fixed. If you now try and run your code, you get the error

````python
ValueError: Out of range float values are not JSON compliant
````
If you replace with 'NaN' then valid json is spat out.

You can see my test here: http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/tests/735_conversion_of_npnan.ipynb

I had to modify your code slightly to work with latest version of bokeh - but I believe it's a fair representation.

**Comment by artifex85** [comment]
birdsarah- do you have a new link to that test code? The one you have seems to be broken.

Thanks!

**Comment by birdsarah** [comment]
http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/735_conversion_of_npnan.ipynb
