### ISSUE TITLE
Performance regression for rect related to rbush

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#736]
This jsFiddle doesn't quite reproduce it.  
http://jsfiddle.net/9MnrL/3/
In my application I have seen very poor performance when plotting ~500 rects (with 2000 NaNs).

Here is the performance hotspot.
https://github.com/ContinuumIO/bokeh/blob/master/bokehjs/src/coffee/renderer/glyph/rect.coffee#L33-L39

Isn't rbush only used for hit testing?  Could the _set_data be a no-op when the hover tool isn't activated?

**Comment by birdsarah** [comment]
i'm not sure whether this is still an issue, but for reference.

the lines being referred to above in rect.coffee at the time of issue creation are:

````coffeescript
    _set_data: () ->
      @index = rbush()
      pts = []
      for i in [0...@x.length]
        if not isNaN(@x[i] + @y[i])
          pts.push([@x[i], @y[i], @x[i], @y[i], {'i': i}])
      @index.load(pts)
````

here is _set_data and _index_data today:

````coffeescript
  _set_data: () ->
    @max_w2 = 0
    if @distances.width.units == "data"
      @max_w2 = @max_width/2
    @max_h2 = 0
    if @distances.height.units == "data"
      @max_h2 = @max_height/2

  _index_data: () ->
    @_xy_index()
````

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
