### ISSUE TITLE
Dual x-axis tickers not working when axes separated

### ISSUE THREAD

**Issue by AlbertDude** [bokeh/bokeh#7362]
bokeh 0.12.13

When adding a second x-axis, the tickers don't work if the original axis is placed below the plot (default) and the second x-axis is placed above.

The combination of first x-axis below, second x-axis above is the only one that misbehaves.  Both axes above, both below, or first above and second below work as expected.

```
import bokeh.plotting as BPlotting
import bokeh.models as BModels
num_chans = 6
x = [16, 32, 64, 96, 128]  
y = [10, 15, 20, 24, 25]   
ticks = x                         
ticks_t = [i*num_chans for i in x]
spacer = 1.2
p = BPlotting.figure( x_axis_type='log', x_range=(ticks[0]/spacer, ticks[-1]*spacer) )
p.line('x', 'y', source=BPlotting.ColumnDataSource(data=dict(x=x, y=y)))
p.xgrid.ticker       = BModels.FixedTicker(ticks=ticks)
p.xaxis[0].ticker    = BModels.FixedTicker(ticks=ticks)
p.xaxis[0].formatter = BModels.PrintfTickFormatter(format="%d kbps/ch")
p.extra_x_ranges['total'] = BModels.Range1d(start=ticks_t[0]/spacer, end=ticks_t[-1]*spacer)
p.add_layout( BModels.LogAxis(x_range_name='total'), 'above' ) # doesn't work
#p.add_layout( BModels.LogAxis(x_range_name='total'), 'below' ) # works as expected
p.xaxis[1].ticker    = BModels.FixedTicker(ticks=ticks_t)
p.xaxis[1].formatter = BModels.PrintfTickFormatter(format="%d Tot kbps")
BPlotting.output_file('dual_x.html')
BPlotting.save(p)

```

Broken case (first axis 'below', second axis 'above'):
![image](https://user-images.githubusercontent.com/34693869/34478518-23db6f58-ef56-11e7-8068-5d74e83dcbbc.png)

Working case (first axis 'above', second axis 'below'):
![image](https://user-images.githubusercontent.com/34693869/34478537-49ccaefc-ef56-11e7-914e-031d89e1c5d9.png)

See: https://groups.google.com/a/continuum.io/forum/?utm_source=digest&utm_medium=email#!topic/bokeh/s4u5xUPVQr4

**Comment by bryevdv** [comment]
@AlbertDude I would characterize this as a usage issue. There is no guarantee that the order of the axis in `p.xaxis` has any particular order, but you are assuming one. If I change your code to:
```
p.xaxis[0].ticker    = BModels.FixedTicker(ticks=ticks_t)
p.xaxis[0].formatter = BModels.PrintfTickFormatter(format="%d Tot kbps")
```
Then I get:

<img width="624" alt="screen shot 2018-09-13 at 15 49 31" src="https://user-images.githubusercontent.com/1078448/45520089-9f31eb80-b76c-11e8-9329-8989ba23b745.png">

You can set a `name` property on the axes and then use the `select` method to search for a particular axis more robustly. This is a support question tho, for more appropriate for the mailing list
