### ISSUE TITLE
Developing with JavaScript JSFiddle not working in Firefox 57.0.3 (macOS 10.13.2)

### ISSUE THREAD

**Issue by BrandonCW** [bokeh/bokeh#7364]
The example at the bottom of [this page](https://bokeh.pydata.org/en/latest/docs/user_guide/bokehjs.html#userguide-bokehjs) is not working in Firefox 57.0.3. The relevant JS Fiddle is [here](https://jsfiddle.net/bokeh/ck5udmxb/?utm_source=website&utm_medium=embed&utm_campaign=ck5udmxb). I've checked in Safari 11.0.2 and Chrome 63.0.3239.84 and it works correctly in both.

**Comment by bryevdv** [comment]
That fiddle was actually deleted as part of a cleanup of project-related accounts. At this point I think I'll leave this task to remove it from the docs. There are other issues to address pure BokehJS related improvements when there are resources available to work on them

**Comment by bryevdv** [comment]
closed in #7940
