### ISSUE TITLE
issues with shared ServerSession/Document

### ISSUE THREAD

**Issue by ivan-usov** [bokeh/bokeh#7365]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh/0.12.13
chrome/63.0.3239.108
firefox/57.0.1
python/3.6.2
ubuntu/16.04

#### Description of expected behavior and the observed behavior
Following documentation on `--session-ids` argument and `bokeh-session-id` parameter ([session-id-options](https://bokeh.pydata.org/en/latest/docs/reference/command/subcommands/serve.html#session-id-options)) one can create multiple `ServerConnection`s to the same `ServerSesssion` _via_ passing the same session id (e.g. 'http://localhost:5006/app_name?bokeh-session-id=test') to multiple clients. The server architecture clearly allows it ([applications-sessions-and-connections](https://bokeh.pydata.org/en/latest/docs/dev_guide/server.html#applications-sessions-and-connections)). But sharing a session this way doesn't seem to play well with some models of the bokeh library, at least it leads to visual glitches and various inconsistencies between clients on many bokeh examples.

#### Complete, minimal, self-contained example code that reproduces the issue
1) https://github.com/bokeh/bokeh/tree/master/examples/app/ohlc 
Clients will compete for setting the data range values.

2) https://github.com/bokeh/bokeh/blob/master/examples/app/fourier_animated.py
https://github.com/bokeh/bokeh/blob/master/examples/app/image_blur.py
https://github.com/bokeh/bokeh/blob/master/examples/app/line_on_off.py
A toolbar disappears on consequent clients, and somewhat confuses the toolbar of the first client.

3) https://github.com/bokeh/bokeh/blob/master/examples/app/selection_histogram.py
Histograms disappear on consequent clients.

I didn't check all the examples for issues. Also some of them work correctly, at least I couldn't spot any misbehaviour (e.g. [population](https://github.com/bokeh/bokeh/blob/master/examples/app/population.py)).

I believe, this is not the main use-case for bokeh, but sometimes sharing the `Document` instance can be handy, e.g. when it contains large binary data blobs, while all users only need to see the same 'representation' of that data.

**Comment by bryevdv** [comment]
@ivan-usov This is definitely not the main use-case for Bokeh as you say, however certainly we'd like to have it work as well as possible. I believe I have noticed this before, so it's good to have an issue to track it. Unfortunately I'm not sure offhand what a fix would look like so it will take some investigation and I don't know offhand when it might be able to be prioritized.

**Comment by bryevdv** [comment]
Realistically we are not going to have resources to devote to this use-case, which I consider basically out-of-scope. Managing sessions with id's explicitly is useful for customizing sessions before serving them to a particular user. The intent was not for "google docs" style sharing, though it may work reasonably well in some cases in a YMMV kind of way.
