### ISSUE TITLE
Option for different NaN handling for line glyph

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#737]
I'm plotting dataframes with NaNs.  I expect lines to be continuous, but because of the NaN's they are a bunch of line segments.  It's a simple change in the line renderer to enable NaN ignoring. 

Comment out these lines
https://github.com/ContinuumIO/bokeh/blob/master/bokehjs/src/coffee/renderer/glyph/line.coffee#L37-L39

What do you think of creating an option on the glyphspec to enable this behaviour?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by andresmrm** [comment]
I'm trying to plot multiple time series, each with different periodicity, on the same figure.
Still no solution for it?

**Comment by bryevdv** [comment]
All the discussion so far has been too abstract for me. I don't do much work with time series. What is needed:

* a full complete, minimal script of the code you'd like to be able to write, including any data
* screenshot of what that currently produces, that is somehow undesirable
* a description of what it should do instead of what it currently does 

At this point all that should go in a new issue

**Comment by andresmrm** [comment]
While creating a small example, I found a way to work around the problem: drawing each line with a "clean" X axis. Instead of using the same DataSource for all the lines, I create one for each line, and remove the rows that have `nan` at Y.

This work around is enough for me, so I'm not openning a new issue for now.
What do you say, should we still add a plot line option to "join the dots"?

```
import pandas as pd
from numpy import rec, nan
from bokeh import palettes
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource


def create_figure():
    fig = figure(title='Prisional Pop by Country')
    fig.xaxis.axis_label = 'Year'
    fig.yaxis.axis_label = 'Prisional Pop'
    return fig


data = rec.array([
    (1992, 501.,  nan, 487.,  74.),
    (1995, 592., 109., 622.,  92.),
    (1998, 655., 115., 688.,  nan),
    (2001, 685., 112., 636., 133.),
    (2004, 725., 122., 588., 183.),
    (2007, 758., 124., 613., 220.),
    (2010,  nan, 123., 609., 253.),
    (2012, 707.,  nan,  nan, 287.),
    (2013,  nan, 121.,  nan,  nan),
    (2014, 693., 119., 471., 307.),
    (2015, 666., 118.,  nan,  nan),
    (2016,  nan,  nan, 448.,  nan),
    (2017,  nan,  nan, 433., 316.)],
    dtype=[('Ano', '<i8'),
           ('EUA', '<f8'), ('China', '<f8'),
           ('Rússia', '<f8'), ('Brasil', '<f8')])

df = pd.DataFrame(data)
x = df.columns[0]
ys = df.columns[1:]

# This way the lines are NON CONTINUOUS.
fig1 = create_figure()
data_source = ColumnDataSource(data=df)
for y, color in zip(ys, palettes.Dark2_8):
    fig1.circle(x, y, source=data_source, color=color, size=5)
    fig1.line(x, y, source=data_source, line_width=3, color=color)
show(fig1)

# This way the lines are CONTINUOUS.
fig2 = create_figure()
for y, color in zip(ys, palettes.Dark2_8):
    data_source = ColumnDataSource(data=df[[x, y]].dropna(axis=0, how='any'))
    fig2.circle(x, y, source=data_source, color=color, size=5)
    fig2.line(x, y, source=data_source, line_width=3, color=color)
show(fig2)
```

**Comment by tomasrojasc** [comment]
Hi! I really need this feature, since I am ussing data from two different sensors so when I merge the two dataframes of the sensors, in order to have interactivity, I get discontinuities but not because of my data is bad, but because many points where one sensor has data, the other does not

**Comment by bryevdv** [comment]
Hi @tomasrojasc Any change in line rendering would be have to added behind a flag (that is off by default). Are you interested to work on this? I would say at this point that the best chance for this to be added is for a new contributor to decided that it is important enough to work on.

**Comment by tomasrojasc** [comment]
Hi @bryevdv I can give it a shot but I really dont know if I will be able to do it

**Comment by JohannesFischerInnio** [comment]
Hi @tomasrojasc 
I had the same issue that I needed the data in the same ColumnDataSource, as i am lacking good enough coding experience I came up with the following workaround, which I thought would be worth sharing:

`#GitHub example
df=pd.merge_asof(df, df2, left_index=True, right_index=True) #merge the two timeseries-dataframes, add the values of df2 to nearest values of df
duplicated=df.duplicated(subset=['new_column']) #get duplicated values (created by merge_asof)
df.loc[duplicated, ['new_column']] = np.NaN #remove duplicated values
df['new_column'] = df['new_column'].interpolate() #interpolate values`

This creates the interpolated values. It is perfectly fine as long as you are using the line output, if you switch to circle it shows a lot of in reality non existing datapoints:
![image](https://user-images.githubusercontent.com/81354631/116529934-bf8f2400-a8dd-11eb-8c01-3019252bb97a.png)
