### ISSUE TITLE
BoxAnnotation should work with ColumnDataSource

### ISSUE THREAD

**Issue by dnlwgnd** [bokeh/bokeh#7375]
Hi,

I found that a BoxAnnotation cannot currently fetch its parameters (like top, bottom) from a attached ColmunDataSource (via source argument).
Other Annotations (like Arrow) can already do this.
I would appreciate to see this implemented.

For instance, I'd like to do this:
`
fig.add_layout(BoxAnnotation(left='starttime', right='enddtime', bottom='startvalue', source=data, fill_color='green', fill_alpha=0.3))
`

Daniel.

**Comment by bryevdv** [comment]
I agree that the annotations are not consistent in this regard (see also `Label` vs `LabelSet`) In the mean time I'd suggest that any of `Rect`, `Quad`, `VBar` or `HBar` could generally be used as a substitute for box annotations

**Comment by dnlwgnd** [comment]
well yes, that certainly is a workaround.
How could I get the "unbounded" nature of the `BoxAnnotation `(ie. when the `top `property is not set) and have the box extend until the boundaries of the plot, possibly maintaining this even when panning the plot?

**Comment by bryevdv** [comment]
Closing inactive discussion. There does not seem to be enough interest to warrant adding complexity, and there are workarounds.

**Comment by chrisjcameron** [comment]
Consistent behavior across annotation classes is not "adding complexity" -- it is reducing complexity. I hope you will reconsider adding this feature as an investment in user experience.

**Comment by bryevdv** [comment]
@chrisjcameron As said above there won't complete consistency any time soon, see e.g. `Label` / `LabelSet` with two models for with/without source vs `Arrow` and `Band` which have a single model that accepts a source. It's too late to break those APIs, so we will be stuck with both. Id' be happy to consider either approach for `BoxAnnotation`, probably with a preference to add a `source` property. But I doubt it's something the very limited core team resources will be available for in the near future. We'd be happy to advise/provide guidance if you'd like to look into a PR.

**Comment by daniel-raimi-zlatic** [comment]
I am also very interested in this feature. Although I do not think I am suited to make a PR.

I am currently using the Quad workaround, although it is causing me heartache where I have to manually set the y limits of the axes when the data source changes on a callback.

Is there anyway this can be reopened?

**Comment by tomasero** [comment]
Hi! I am also very interested in this feature. I am streaming data and would want to have BoxAnntations extend as new data comes in. Would it be possible to reopen this?

**Comment by mattpap** [comment]
@tomasero, can you motivate why do you specifically need `BoxAnnotation` or alternatively what's missing from equivalent glyphs? In bokeh, glyphs are meant for dealing with data (including streaming), whereas annotations are for singular data points or unrelated to data altogether. Data support in annotations is more of a historical artifact than a well thought out feature.
