### ISSUE TITLE
Feature Request: When using figure.image, add a mask array similar to matplotlib's mask when using imshow.

### ISSUE THREAD

**Issue by jkquijas** [bokeh/bokeh#7380]
When using the .image function of the Figure class, it would be nice to be able to specify a mask array (boolean, perhaps) so that when initializing it with a numpy matrix, only the values specified by the mask are displayed. This is already implemented in the Heatmap class. Would be nice to see it in image.py

**Comment by bryevdv** [comment]
@jkquijas For new feature request proposals, more detail is better. At least some of the things like the following are really needed:

* links to other implementations in other libraries
* screen shots
* proposed new syntax for Bokeh
* description of use-cases/motivation to help with docs
* suggestions for examples to add to the project

**Comment by bryevdv** [comment]
Closing for lack of any response.
