### ISSUE TITLE
Example `flask_embed.py` doesn't work in local network in Internet Explorer

### ISSUE THREAD

**Issue by gepcel** [bokeh/bokeh#7381]
There's an example of [flask_embed.py](https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/flask_embed.py). It runs fine in both Chrome and IE. 

But I need to run in a local network (eg: via "http://192.168.1.2:8000/"), so I changed line 44 to:

```python
server = Server({'/bkapp': modify_doc}, allow_websocket_origin=["192.168.1.2:8000"])
```

And line 56 to:

```python
app.run(host="192.168.1.2", port=8000)
```

After these changes, "http://192.168.1.2:8000" works fine in Chrome, but not in IE, the IE console information is:

```
HTML1300: 进行了导航。
192.168.1.2:8000
Bokeh: BokehJS not loaded, scheduling load and callback at Mon Jan 08 2018 18:58:55 GMT+0800 (中国标准时间)
   "Bokeh: BokehJS not loaded, scheduling load and callback at"
   [date] Mon Jan 08 2018 18:58:55 GMT+0800 (中国标准时间)

Bokeh: injecting script tag for BokehJS library:  http://localhost:5006/static/js/bokeh.min.js?v=15c391efcd2d880600216acd13aa97ff
Bokeh: injecting script tag for BokehJS library:  http://localhost:5006/static/js/bokeh-widgets.min.js?v=4fab6c0812b586bd3b599927148ddee2
Bokeh: injecting script tag for BokehJS library:  http://localhost:5006/static/js/bokeh-tables.min.js?v=c7b9e0042fcdcc9186ff88b239811602
Bokeh: injecting script tag for BokehJS library:  http://localhost:5006/static/js/bokeh-gl.min.js?v=2f4a9a9e9f8b300c68c4ed24b5f4979a
Bokeh: all BokehJS libraries loaded
Bokeh: BokehJS plotting callback run at Mon Jan 08 2018 18:58:55 GMT+0800 (中国标准时间)
   "Bokeh: BokehJS plotting callback run at"
   [date] Mon Jan 08 2018 18:58:55 GMT+0800 (中国标准时间)

[bokeh] setting log level to: 'info'
Bokeh: injecting CSS: http://localhost:5006/static/css/bokeh.min.css?v=06206b4cbc8ea56b6016931bd1976f7f
Bokeh: injecting CSS: http://localhost:5006/static/css/bokeh-widgets.min.css?v=509e292d9a7ef7e9eb8382fcde7b4a6e
Bokeh: injecting CSS: http://localhost:5006/static/css/bokeh-tables.min.css?v=aa783ffa4e290813a295a99cce2f8b5d
Bokeh: all callbacks have finished
[bokeh] Will inject Bokeh script tag with params {"elementid":"8bec92ea-088e-455e-b1d9-625601d19ce5","sessionid":"EiGs1Y2zxSWDDl8Z8yViTF7GCLkUd85oUMLCESzTXLzs","use_for_title":false}
[bokeh] websocket creation failed to url: ws://localhost:5006/bkapp/ws
[bokeh]  - SecurityError
[bokeh] Failed to connect to Bokeh server SecurityError
```

**Environment**:

python: 3.6.3
bokeh: 0.12.13
flask: 0.12.2
Chrome: 63.0.3239.84
Internet Explorer: 11.192.16299.0
os: Windows 10 x64

**Comment by bryevdv** [comment]
Is there any bokeh server console output in then command terminal?

**Comment by bryevdv** [comment]
Tho it seems like this might be a bug in IE:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12090409/

**Comment by bryevdv** [comment]
@gepcel can you follow the instructions listed here to capture additional console log messages:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/12a7b3b8-d81d-4605-99fa-a79e19e5a81a/new-websocket-with-wss-gives-security-error?forum=iewebdevelopment

Hopefully that will shed more specific light on the "why"

**Comment by bryevdv** [comment]
Also possibly relevant, but not certain:

https://github.com/qzind/qz-print/issues/39

**Comment by gepcel** [comment]
@bryevdv Thank you, [qzind/qz-print#39](https://github.com/qzind/qz-print/issues/39) works. To make things easy for other people, I'll quote it here:

```
IE11 blocks websocket connections to localhost by default.

To unblock, click the Gear, Internet Options, Security, 
Local Intranet, Sites, Uncheck the first checkbox.
```
![image](https://cloud.githubusercontent.com/assets/6345473/8088985/1db5781e-0f73-11e5-9a6f-b76b728f0aeb.png)

**Comment by bryevdv** [comment]
Thanks for the update @gepcel that seems a bit annoying but I am not sure there is any way around it, so it's good to document here
