### ISSUE TITLE
Error in documentation for Handling Categorical Data

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7386]
At https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html the documentation says:
```
p = figure(x_range=FactorRange(field=fruits), ... )
```

I believe `field` has to be changed to `factors`.

**Comment by bryevdv** [comment]
@p-himik No that is correct, it is referencing the line
```
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
```
a few lines above.

**Comment by bryevdv** [comment]
Sorry, doing too many things at once, you are correct
