### ISSUE TITLE
Tap events respond outside plot area

### ISSUE THREAD

**Issue by marcuskd** [bokeh/bokeh#7390]
In the example below, the Tap event works but also seems to work outside the right hand side of the plot area, up to the edge of the toolbar. If you click within the toolbar, the controls work, but it also updates the plot. You can also click below the toolbar and the plot updates. The problem appeared in 0.12.11 onwards.

Software versions...
Bokeh 0.12.13
Python 3.5.2
Firefox 57.0.4 (64 bit)

```
from bokeh.models.sources import ColumnDataSource
from bokeh.plotting import Figure
from bokeh.io import curdoc
from bokeh.events import Tap

fig = Figure()
line_src = ColumnDataSource(data={'x': [0, 1], 'y': [0, 1]})
line = fig.line('x', 'y', source=line_src)


def update_data(event):
    line_src.data['x'][1] = event.x
    line_src.data['y'][1] = event.y
    fig.renderers.remove(line)
    fig.renderers.append(line)

fig.on_event(Tap, update_data)

curdoc().add_root(fig)
```

**Comment by bryevdv** [comment]
@marcuskd There are two separate problems here, can you split this issue? The first example is just tap responding outside the plot area. That's (I assume) a fairly simple fix. 

The second is a more general problem with synchronizing things added after the initial render. 

I'll rename this issue to reflect the first problem.

**Comment by marcuskd** [comment]
@bryevdv - Issue split as requested. New issue is 'Disappearing Toolbar', #7497.

**Comment by marcuskd** [comment]
Sorry - closed by accident!

**Comment by bryevdv** [comment]
Thinking about this more, I am maybe inclined instead to add an `inside` field that is true if the point is inside the plot frame. That way we would not preclude building interactions that involve the axes, etc.

**Comment by marcuskd** [comment]
So in the example `update_data` function above I'd use the condition `if event.inside:` ? That sounds sensible to me.
