### ISSUE TITLE
building applets in bokeh experience

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#740]
I've experimented with a few mechanisms of building applets, (there are currently multiple ways of doing this in the code base).  I would like to take the time to settle on one clear approach, and then remove /cleanup all the cruft

Initially, I started by creating 2 classes, a ModelForm class, which displays a number of input widgets and coerces their types into it's properties (so if you have a selector which is named "counts", and a field of counts, which is an int, the value of the select box is coerced into an int)  And had that coupled with an Applet class, The Applet class had an add_route function which would register the route with the bokeh server.  

( to be continued..)

**Comment by bryevdv** [comment]
I think we have a handle on this with the recent "SimpleApp" discussions.
