### ISSUE TITLE
2D Interaction or Virtual Joystick

### ISSUE THREAD

**Issue by mccarthyryanc** [bokeh/bokeh#7404]
I have an app that uses two sliders to adjust two parameters in a plot. But, what I really would like is a 2 dimensional "slider" or virtual joystick. There is a javascript module, [Nipplejs](https://github.com/yoannmoinet/nipplejs), that does exactly what I want. Here is a [demo](http://yoannmoinet.github.io/nipplejs/#demo). Is it possible to get a similar interaction in Bokeh?

My first thought was to add an additional plot with a javascript callback that got mouse cursor displacement on click events, but I am not sure how to go about this... and there might be a better way.

**Comment by bryevdv** [comment]
My guess is that you would want to create a custom extension:

https://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html

However, the Mailing List would be the appropriate place to have that discussion, not the tracker.
