### ISSUE TITLE
Sliders broken in IE11 in 0.12.10+

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#7436]
demo.bokehplots.com runs 0.12.10dev2 so you cannot see this problem by using those examples.

See screenshots from IE11 in Win7 and Win10 below in various combinations below:

Win7 - IE11 - 0.12.10
![screen shot 2018-01-18 at 6 51 17 pm](https://user-images.githubusercontent.com/1796208/35129595-f2ff8b88-fc81-11e7-902c-f5bf470c7c3a.png)

Win7 - IE11 - 0.12.11
![screen shot 2018-01-18 at 6 52 15 pm](https://user-images.githubusercontent.com/1796208/35129602-fbc821e4-fc81-11e7-8e31-e7ad326bc6fc.png)

Win7 - IE11 - 0.12.13
![screen shot 2018-01-18 at 6 53 08 pm](https://user-images.githubusercontent.com/1796208/35129612-02a77f1e-fc82-11e7-92c3-5df27e413368.png)

Win10 - IE11 - 0.12.10 next to 0.12.10dev2 (working)
![screen shot 2018-01-18 at 6 59 19 pm](https://user-images.githubusercontent.com/1796208/35129628-0e363b4a-fc82-11e7-802f-6da3e148bb93.png)

Error message - "Object does not support property or method isInteger"

**Comment by birdsarah** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

isInteger is not supported by IE11 - so I guess this isn't a surprise :D

**Comment by bryevdv** [comment]
@birdsarah oh, this should have been fixed by https://github.com/bokeh/bokeh/pull/7396 last week. Can you try the latest dev build?

**Comment by birdsarah** [comment]
My bad. Clearly a dupe. Pleaser do close.

Sent from my iPhone

On Jan 18, 2018, at 7:19 PM, Bryan Van de Ven <notifications@github.com> wrote:

@birdsarah oh, this should have been fixed by #7396 last week. Can you try the latest dev build?
