### ISSUE TITLE
Table Covers Other Widget When Table Is On The Left

### ISSUE THREAD

**Issue by neuron878** [bokeh/bokeh#7444]
Python 3.6.3
Bokeh 0.12.13
Pandas 0.22.0
Spyder 3.2.6

Firefox 57.0.4
Windows 7

I would expect the table and widget to not overlap under any circumstance.  However, the table covers the widget when placed to the left of the widget.  Manually changing the size of my browser window or the table columns doesn't appear to fix the problem.

This may be related to [https://github.com/bokeh/bokeh/issues/7443](url)

```
import pandas as pd

from bokeh.layouts import row, widgetbox
from bokeh.models.widgets import MultiSelect, TableColumn, DataTable
from bokeh.models import ColumnDataSource
from bokeh.io import show

df = pd.DataFrame(data={
        'category': ['shirt', 'pants', 'coats'],
        'number': [5, 8, 5],
        })

source = ColumnDataSource(df)

table = DataTable(source=source, columns=[
        TableColumn(field="category", title="Category"),
        TableColumn(field="number", title="Number")
        ])

dropdown = MultiSelect(title='Category', value=list(df.category.unique()),
                       options=list(df.category.unique()))

t = widgetbox(table)
d = widgetbox(dropdown)

r = row(t, d)
show(r)
```

![image](https://user-images.githubusercontent.com/35700321/35234327-64e90508-ff66-11e7-92c9-3ef721b70fd1.png)

**Comment by bryevdv** [comment]
Sorry for the late triage, the core team is fairly underwater.

**Comment by mattpap** [comment]
![image](https://user-images.githubusercontent.com/27475/53673966-157ac980-3c8b-11e9-93f5-983ed6747993.png)
