### ISSUE TITLE
"TypeError: hits.map is not a function" when hovering over MultiLine

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7448]
Bokeh 0.12.14dev4

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/multi_line.ts#L89
`hits` is an object, it doesn't have `map` member.

CC @mattpap

**Comment by mattpap** [comment]
Looks like an effect of another bug decaffeinate, which was used to convert this file from CoffeeScript to ES6.
