### ISSUE TITLE
BokehJS TypeError "legend is undefined"

### ISSUE THREAD

**Issue by synapticarbors** [bokeh/bokeh#7451]
I'm a long time user of Bokeh from the python interface side and have recently begun playing around with using it directly on the client-side from BokehJS. While the mapping between the python api and the js api are fairly similar, I've run into a few problems where python code in examples or in stuff I've previously written doesn't map the way that I anticipated.

Using Bokeh 0.12.13 directly in browser (Firefox 58.0) attempting to change the `legend` property of a figure produces the error:

```
TypeError: p.legend is undefined
```

A minimal reproducible example is: 

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>TEST</title>
    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.css" type="text/css" />
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js"></script>
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-api-0.12.13.min.js"></script>
  </head>
  <body>
    <script type="text/javascript">
        var plt = Bokeh.Plotting;
        var tools = "box_zoom,reset,hover,previewsave";
        var plot_width = 500;
        var plot_height = 110;
        var bg_fill = 'white';
        var p = plt.figure({tools: tools,
                plot_width: plot_width, plot_height: plot_height, sizing_mode: 'scale_width',
                background_fill_color: bg_fill});

        var x = Bokeh.LinAlg.linspace(-0.5, 20.5, 10);
        var y = x.map((v) => v*0.5 + 3.0);

        var lines = new Bokeh.ColumnDataSource({data: {x: x, y: y}});

        p.line({field: 'x'}, {field: 'y'}, {source: lines, legend: 'abc'});

        p.legend.location = 'top_left';

        plt.show(p);
        
    </script>
  </body>
</html>

```

If the offending line is changed to `p._legend.location = 'top_left';`, then the legend location is modified as expected. This seems like a private variable that I shouldn't be accessing.

Another python->js translation that I haven't been able to figure out is:

```
p.yaxis[0].formatter = bokeh.models.NumeralTickFormatter(format="$0")
```

Not related to the main issue, but suggestions would be appreciated.

**Comment by mattpap** [comment]
bokehjs' plotting API doesn't fully implement bokeh's Python APIs yet. bokeh's `Figure.legend`, `Figure.xaxis` and `Figure.yaxis` are tricky to implement, because they allow to act on multiple objects at once. For now you can use `_legend` and `xaxis`, `yaxis` (which just return the first found axis in given dimension). We are currently working on getting bokehjs' APIs in good shape, so in a release or two those gaps should be filled in.

**Comment by synapticarbors** [comment]
@mattpap -- Thanks for the update. I had discovered using `yaxis` without an index from digging in the source code. How would you specify the `NumeralTickFormatter`? Could you provide a complete translation of that line in python to how it should be written in javascript?

Other python api stuff that didn't map cleanly to javascript:

- Setting a common range that links plots when zooming:

```
const one_day = 8.64e7;  // 1 day in milliseconds
const date_dt_min = Bokeh.LinAlg.min(cds.data.date_dt) - 2 * one_day;
const date_dt_max = Bokeh.LinAlg.max(cds.data.date_dt) + 2 * one_day;

const date_range = new Bokeh.Range1d(date_dt_min, date_dt_max);
...
p.x_range = date_range;
// Set x_range on different figures to the same date_range object
```

- Restricting tooltips to certain lines using `hover.name` (this caused no hover behavior):

```
...
p.line(x1, y1, {name: 'a'});
p.line(x2, y2, {name: 'b'});
p.line(x3, y3, {name: 'c'});
const hover = p.toolbar.select_one(Bokeh.HoverTool);
hover.names = ['a', 'c'];  // expect to lines a and c to be hover-able but b should not
```

**Comment by mattpap** [comment]
> `p.yaxis[0].formatter = bokeh.models.NumeralTickFormatter(format="$0")`

```typescript
p.yaxis = new Bokeh.NumeralTickFormatter({format: "$0"})
```

In general if you want to construct a bokeh's model, you must precede it with `new`. Instead of Python's keyword arguments, one uses literal objects that emulate keyword arguments. Also the namespace is flat, so `Bokeh` namespace contains all the models (this maybe change as there are name conflicts).

> `const date_range = new Bokeh.Range1d(date_dt_min, date_dt_max)`

This syntax had been supported, but we had drop it due to technical reasons, so you will write `new Bokeh.Range1d({start: date_dt_min, end: date_dt_max})`.

> Restricting tooltips to certain lines using `hover.name` (this caused no hover behavior):

This one looks fine. I may need to debug this say more.

btw. There are a few examples available at https://github.com/bokeh/bokeh/tree/master/bokehjs/examples. Those are written in TypeScript, but if you ignore the types, then you will get JavaScript (ES6 to be precise).

**Comment by mattpap** [comment]
JavaScript is a nasty language, so `NumeralTickFormatter(format="$0")` translates to:
```typescript
var format = "$0" // global
NumeralTickFormatter(format)
```
Not exactly what one would expect.

**Comment by synapticarbors** [comment]
Here's an example of `hover.names` not working:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>TEST</title>
    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.css" type="text/css" />
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js"></script>
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-api-0.12.13.min.js"></script>
  </head>
  <body>
    <script type="text/javascript">
        var plt = Bokeh.Plotting;
        var tools = "box_zoom,reset,hover,previewsave";
        var plot_width = 500;
        var plot_height = 110;
        var bg_fill = 'white';
        var p = plt.figure({tools: tools,
                plot_width: plot_width, plot_height: plot_height, sizing_mode: 'scale_width',
                background_fill_color: bg_fill});

        var x = Bokeh.LinAlg.linspace(-0.5, 20.5, 10);
        var y = x.map((v) => v*0.5 + 3.0);
        var y2 = x.map((v) => v*v*0.5 + 3.0);

        var lines = new Bokeh.ColumnDataSource({data: {x: x, y: y, y2: y2}});

        p.line({field: 'x'}, {field: 'y'}, {source: lines, legend: 'abc', name: 'abc'});
        p.line({field: 'x'}, {field: 'y2'}, {source: lines, legend: 'xyz', name: 'xyz', color: 'Red'});

        var hover = p.toolbar.select_one(Bokeh.HoverTool);
        hover.names = ['abc', ];
        hover.tooltips = [
            ['x', '@x']
        ];

        p._legend.location = 'top_left';

        plt.show(p);
        
    </script>
  </body>
</html>
```

If you comment out `hover.names = ['abc', ];` then hover displays the `x` value on both lines. If you try to set `hover.names`, then you get no hover behavior. 

Also (again, sorry for hijacking this issue with other questions), is there a way to insert different figures into different divs? On the python side, I'd use `bokeh.embed.components(figs)` where `figs` was a dict of `bokeh.plotting.figure`.  When I try to do something like:

```javascript
plt.show(p1, document.getElementById("plot_1"));
plt.show(p2, document.getElementById("plot_2"));
```

I get the error `Error: models must be owned by only a single document`.

**Comment by mattpap** [comment]
> is there a way to insert different figures into different divs?

Sure, `show()` is just a convenience wrapper over the underlying APIs. This:

```javascript
var doc = new Bokeh.Document();
doc.add_root(p1);
doc.add_root(p2);

var div1 = document.getElementById("plot_1");
var div2 = document.getElementById("plot_2");

Bokeh.embed.add_model_standalone(p1.id, div1, doc);
Bokeh.embed.add_model_standalone(p1.id, div2, doc);
```
should do the trick (though I didn't actually test it).

**Comment by synapticarbors** [comment]
That seemed to work in terms of positioning the plots where I want. The only issues are:

- The hover tool tips are displayed unformatted in the white space below both plots.
- Neither of the plots have toolbars.

**Comment by mattpap** [comment]
Right. Those `<div>` elements must be children of `<div class="bk-root">` to make bokeh's CSS to apply correctly, so there should be:
```html
<div class="bk-root">
  <div id="plot_1"></div>
  <div id="plot_2"></div>
</div>
```
in your HTML. Or alternatively you can have:
```html
<div class="bk-root">
  <div id="plot_1"></div>
</div>
<div class="bk-root">
  <div id="plot_2"></div>
</div>
```
Just make sure that you don't end up with `<div class="bk-root" id="plot_1"></div>`. This isn't going to work due to limitations of CSS.

**Comment by synapticarbors** [comment]
Perfect. That fixes the issues. Thanks for all of your help. I definitely find it easier working with Bokeh from the Python side, but it's been a great learning experience trying to replicate some of this directly with BokehJS.

**Comment by mattpap** [comment]
> I definitely find it easier working with Bokeh from the Python side, (...)

That's not unexpected. Originally bokehjs wasn't meant to be used like this, so those APIs aren't final, nor fleshed out in any significant manner yet.

**Comment by bekerov** [comment]
New line declared as shown below, but i cant figure out how insert legend
```
 var line = new Bokeh.Line({
  x: {field: column},
  y: {field: date_column},
  line_color: PALLETE[line_idx],
  line_width: 2,
  line_alpha: 0.7,
  // legend: plot_config_line // THIS LINE IS DOESN'T WORK
});
var glyph = group.add_glyph(line, source);
```
