### ISSUE TITLE
Revert nouislider rev update

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#7452]
Sliders work perfectly in standalone docs but are badly broken in server apps:

<img width="316" alt="screen shot 2018-01-23 at 16 39 58" src="https://user-images.githubusercontent.com/1078448/35304734-3b566d38-005c-11e8-9df9-988559d4e467.png">

as well as distinct sliders being inappropriately linked in other server apps.

**Comment by mattpap** [comment]
Only vertical sliders are broken, though across the board. It would be more effective to figure out the difference, rather that going back and forth between versions.

**Comment by bryevdv** [comment]
certainly agree that would be preferable, but nothing jumped out from a quick look. I'm still recovering from being sick (again... this year is off to a great start) but if you want to take a look and find something I'll happily close this with a fix, instead.

**Comment by mattpap** [comment]
I will fix this, especially this is something trivial, because slider handles are just offset by negative widget width, and otherwise work perfectly well.

**Comment by bryevdv** [comment]
You will need to also run the OHLC demo. Scrubbing the left slider causes the right slider to update as well

**Comment by mattpap** [comment]
I removed all bokeh's CSS and all customizations, and it still doesn't work. Lets revert those changes (just whatever you do, make sure to update `package-lock.json` as well).

**Comment by bryevdv** [comment]
OK, I'll try to get to it today.
