### ISSUE TITLE
NumberInput for using HTML5 input type "number"

### ISSUE THREAD

**Issue by alexomics** [bokeh/bokeh#7453]
Similar to #6492 I have been trying to add a `NumberInput` widget, that would extend (most likely) `InputWidget`. I've been unable to follow the directions because it looks like coffee script is no longer being used and I don't know what to do.

This would be useful for inputs where only numbers are expected, such as plot dimensions, as entering [a-z] into these inputs prevents updating a plot until they are removed; as well as better user experience with mobile devices (numeric keyboard).

I think this should be a simple addition as the field requires similar parameters to `Slider` (step, min, and max) while also using similar properties as `TextInput` (value and placeholder). If anybody can point me in the right direction, I would be happy to give it a go.

**Comment by mattpap** [comment]
This was added in PR #8678.
