### ISSUE TITLE
Grid without Axis?

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#746]
Currently to create a grid I have to do `xgrid = Grid(plot=plot, axis=xaxis, dimension=0)`. If I don't specify `axis`, I will get `Cannot read property 'get_obj' of undefined`. It used to be possible to have a grid without an axis, and `iris_splom` was a good example showing this. In 23679b7a1ad5a1bd7e6c1233ce3eec2596f72702 this example was "updated" to match recent changes, but `xax` and `yax`, and related logic, are still there, so I'm not sure if this is just a temporary difficulty or the design was broken, or maybe grid without an axis doesn't make sense? A different story is that specifying an axis and a dimension in a grid is redundant, because an axis already knows its dimension.

**Comment by bryevdv** [comment]
Can now create `Grid` and pass explicit `Ticker` (will not happen automatically though)
