### ISSUE TITLE
bokeh.core.properties.Date#transform fails on Windows

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7460]
Bokeh 0.12.14dev4

`bokeh.core.properties.Date#transform` catches `ValueError`, but it doesn't work on Windows.
On windows, the exception for invalid values is `OSError`.

**Comment by bryevdv** [comment]
Three hours later I can finally run (a subset of) tests on Windows. Will make a PR with a test for windows so that in the future when we run windows unit tests continuously it will be there.

**Comment by bryevdv** [comment]
@p-himik what usage triggers this error?

**Comment by bryevdv** [comment]
@mattpap it looks as though you added this logic in https://github.com/bokeh/bokeh/commit/4b6fe7f5217d67203073b5e4feb484ce2123929b:

```
 +    def transform(self, value):
 +        value = super(Date, self).transform(value)
 +
 +        if isinstance(value, (float,) + integer_types):
 +            try:
 +                value = datetime.date.fromtimestamp(value)
 +            except ValueError:
 +                value = datetime.date.fromtimestamp(value/1000)
```
Can you explain this more clearly?  The `Data.fromtimestamp` docs report:
> Return the local date corresponding to the POSIX timestamp, such as is returned by time.time(). This may raise OverflowError, if the timestamp is out of the range of values supported by the platform C localtime() function, and OSError on localtime() failure. It’s common for this to be restricted to years from 1970 through 2038. Note that on non-POSIX systems that include leap seconds in their notion of a timestamp, leap seconds are ignored by fromtimestamp().

> Changed in version 3.3: Raise OverflowError instead of ValueError if the timestamp is out of the range of values supported by the platform C localtime() function. Raise OSError instead of ValueError on localtime() failure.

Is this an attempt to work around that? Are there not date values that potentially should be decoded in the second way, but that would pass through the `try` by pure concidence?

**Comment by mattpap** [comment]
> > Can you explain this more clearly? 

> mattpap committed on Apr 15, 2014

Sure, why not. But jokes aside, I have no idea, but it's likely that this was copied from some other bokeh's code that handled dates (maybe serialization).

**Comment by bryevdv** [comment]
I have a vague recollection of values being set in python in seconds, then coming back from the client in milliseconds, and that causing problems. I guess this attempts to handle that, but I definitely don't think it's a good solution.
