### ISSUE TITLE
Unable to reuse sessions of a server application

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7461]
Bokeh 0.12.14dev4

```python
from tornado.ioloop import IOLoop

from bokeh.plotting import figure
from bokeh.server.server import Server


def setup_plot(doc):
    p = figure()
    p.line([1, 2, 3], [3, 2, 1])
    doc.add_root(p)


io_loop = IOLoop.current()

server = Server(setup_plot, io_loop=io_loop)

server.start()
io_loop.start()
```

1. Start the code
2. Go to http://localhost:5006/?bokeh-session-id=1
3. Open JS console, check that there're no errors
4. Refresh the webpage
5. Behold `Error rendering Bokeh items  TypeError: Cannot read property '_left' of undefined` in the JS console

Preliminary analysis shows that the issue is most likely caused by `Plot._init_toolbar_panel` - it adds a new panel each time the page is refreshed. The old panel is not being removed properly at the top of the function because `this._toolbar_panel` is not set by the document JSON.

At this point, this stuff is rather beyond my expertise with Bokeh, so any pointers would be appreciated.

**Comment by bryevdv** [comment]
@p-himik if you have a chance can you try out some previous releases to see if you can narrow down to just what release this stopped working on (or if it is new in master)?

**Comment by p-himik** [comment]
@bryevdv I worked on `0.12.10` and has stopped working on `0.12.11`.

**Comment by p-himik** [comment]
Most likely, it was because of cb2e3dcd7d2c37b5b334befc8c67d0c91845a5ff

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mattpap** [comment]
I can't reproduce this with `master`. Are there any specifics to the first point? Maybe this depends on factors in included in this issue.

**Comment by bryevdv** [comment]
@mattpap I can definitely reproduce the error with exactly the code above, on `master` or latest dev build:

<img width="796" alt="screen shot 2018-01-29 at 14 54 24" src="https://user-images.githubusercontent.com/1078448/35533858-6571b526-0504-11e8-9422-393ba34c3e0f.png">


That said, the page still to render despite the console error

**Comment by mattpap** [comment]
@bryevdv, how to you run this code?

**Comment by bryevdv** [comment]
@mattpap run the code with `python` then navigate to  http://localhost:5006/?bokeh-session-id=1 and reload

**Comment by mattpap** [comment]
I was able to finally reproduce this with minified resources. With non-minified (dev) resources I can't reproduce this in any browser, etc.

**Comment by bryevdv** [comment]
Weird, I just ran with non-minified and it still happened.  Let's poke at this quickly and see if we can get it in then cut an rc

**Comment by mattpap** [comment]
This gets annoying, because I can't get dev resources to reproduce this, sources maps for minified resources are broken (known bug in the minifier) and pretty-printing of non-source-mapped minified resources crashes the browser.

**Comment by p-himik** [comment]
@mattpap Have you tried some other browser? I don't think I had problems with viewing pretty-printed Bokeh sources in Google Chrome. Also, I was able to reproduce it on the dev resources there.

**Comment by bryevdv** [comment]
@mattpap Here is some possible useful info: The problem shows up in `_paint_levels`, there are two `ToolbarPanelView` for some reason, and one of them has no `.panel`:
<img width="745" alt="screen shot 2018-02-02 at 11 35 49" src="https://user-images.githubusercontent.com/1078448/35746720-5a58e2d4-080d-11e8-8764-844ee3a27949.png">

**Comment by mattpap** [comment]
@bryevdv, I see. There are two, because state management is naive, as I didn't consider this scenario.

**Comment by mattpap** [comment]
@bryevdv, @p-himik, a fix is available in PR https://github.com/bokeh/bokeh/pull/7489.
