### ISSUE TITLE
setting range end or start through CustomJS not working

### ISSUE THREAD

**Issue by Zyell** [bokeh/bokeh#7475]
Setting the range start or end through a CustomJS callback is not functioning in bokeh 0.12.4dev5, python 3.6 on Linux or Windows in the chrome browser.  I found this when upgrading from 0.12.10, where this worked, to test some functionality.  The following code will illustrate the issue:

```python
from bokeh.io import show, output_file
from bokeh.plotting import figure
from bokeh.layouts import column
from bokeh.models import CustomJS, Slider

output_file('testing_range_setting.html')

p = figure()
p.line(x=[1, 2, 3, 4, 5], y=[1, 2, 3, 4, 5])

callback = CustomJS(args=dict(x=p.x_range), code="""
var end = cb_obj.value;
x.end = end;
    """)

sld = Slider(start=0.1, end=10, value=1, step=.1,
             title="X-range", callback=callback)

show(column(sld, p))
```
I haven't been able to isolate the issue, but no exceptions are thrown in the browser.

**Comment by p-himik** [comment]
It appears to also work on Bokeh 0.12.13

**Comment by bryevdv** [comment]
ping @mattpap

**Comment by mattpap** [comment]
This is a more fundamental issue, because setting `DataRange1d.end` doesn't work (doesn't propagate) and more over gets overwritten with the old value.

**Comment by bryevdv** [comment]
Setting `DataRange1d.end` has always previously worked.

**Comment by mattpap** [comment]
I bisected this to 2b7ec42, specifically, commenting out this code:

https://github.com/bokeh/bokeh/blob/9a09914465dc7f37f52d74c1362f1b4d67ed7485/bokehjs/src/coffee/models/renderers/glyph_renderer.ts#L94-L104

restores the original behavior.

**Comment by mattpap** [comment]
I'm not sure how this code influences the bad behavior, but what happens, is that as soon as `DataRange1d.end` is set, it is overriden with the old value based on `Line` glyph's bounds.

**Comment by mattpap** [comment]
The only thing that prevents the bad behavior is `set_data_timestamp` in `PlotCanvas.paint()`, which with the new code is invalidated.

**Comment by bryevdv** [comment]
@mattpap That change was made in https://github.com/bokeh/bokeh/pull/7363

The reason was so that when a factor range changed, the necessary re-mapping in `set_data` would occur. I suppose we could be more selective and only connect `FactorRange` instances. Open to other ideas though

**Comment by mattpap** [comment]
This seems reasonable.

**Comment by bryevdv** [comment]
Perhaps the range itself could report whether this kind of hookup is needed, then we wouldn't have to tip check at least

**Comment by bryevdv** [comment]
@mattpap are you going to make a PR or do you want me to?
