### ISSUE TITLE
PlotCanvasView#build_levels removes only glyphs when renderers change

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7476]
Bokeh 0.12.14dev4

Brought to light by https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!topic/bokeh/wsiTB4r38OM

If you add some non-glyph renderer (e.g. a BoxAnnotation) and then remove it by changing `plot.renderers` list, the renderer will still be displayed because of https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/plots/plot_canvas.ts#L563-L565

**Comment by bryevdv** [comment]
@p-himik thanks for the report. This seems like it should be a straightforward fix to just delete from all levels.
