### ISSUE TITLE
"theme.yaml" file is missing for the "flask_embed.py"

### ISSUE THREAD

**Issue by wangyingxie** [bokeh/bokeh#7487]
For the "flask_embed.py" file, the "theme.yaml" file is missing. Thus, please note to add this file to your directory. 

Here is one example of the file:

https://github.com/bokeh/bokeh/blob/master/examples/app/clustering/theme.yaml

**Comment by bryevdv** [comment]
It's not missing, it is right here:

https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/theme.yaml

**Comment by wangyingxie** [comment]
Sorry about that, I am new to the github. Yes, I found it in the previous folder. Thanks!
