### ISSUE TITLE
In a stacked bar chart there is no way to add tolltips for segments in column

### ISSUE THREAD

**Issue by ClaudiuCreanga** [bokeh/bokeh#7492]
If you have a stacked bar chart you would want to add different values in tooltips for each segment in a column. Currently there is no way of doing that as I'm aware: 

```
from bokeh.core.properties import value
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from bokeh.models import HoverTool

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ["2015", "2016", "2017"]
colors = ["#c9d9d3", "#718dbf", "#e84d60"]

data = {'fruits' : fruits,
        '2015'   : [2, 1, 4, 3, 2, 4],
        '2016'   : [5, 3, 4, 2, 4, 6],
        '2017'   : [3, 2, 4, 4, 5, 3]}

source = ColumnDataSource(data=data)

p = figure(x_range=fruits, plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

p.vbar_stack(years, x='fruits', width=0.9, color=colors, source=source,
             legend=[value(x) for x in years])


tooltips = HoverTool(
tooltips=[
    ("2015", "@2015"),
    ("2016", "@2016"),
    ("2017", "@2017"),
    ("index", "$index")
    ]
)

p.add_tools(tooltips)

show(p)
```
You can see that values from the column appear over all segments. 
Bokeh version 0.12.13  
Python version 3.6.3

**Comment by bryevdv** [comment]
So I think the most reasonable immediate solution at the core Bokeh level is simply to have `vbar_stack` return a list of the renderers it creates. Then separate hover tools could be made for each. That would be a little bit of work, but also higher level tools like Holoviews could use that facility to do this sort of thing automatically for users if then wanted.

**Comment by ClaudiuCreanga** [comment]
@bryevdv could we have an example of the code with how we can achieve this? https://user-images.githubusercontent.com/1078448/37690635-809d8ed8-2c69-11e8-8810-15532790bbae.gif Thanks so much!
