### ISSUE TITLE
Bokeh Panel(closable=True) doesn't make 'x' appear on the Panel title and closable by user

### ISSUE THREAD

**Issue by Aso1977** [bokeh/bokeh#7498]
Hi, 
I am running your example for Panel and Tabs in bokeh. The 'closable=True' not working as expected.
Tested on Ubuntu 16.04, Chrome and Firefox browsers.
Using Bokeh 0.12.13 server and Python 3.6. 
Nothing special showed in the debugging.

Thanks

```
from bokeh.models.widgets import Panel, Tabs
from bokeh.io import output_file, show
from bokeh.plotting import figure
from bokeh.io import curdoc


output_file("slider.html")

p1 = figure(plot_width=300, plot_height=300)
p1.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
tab1 = Panel(child=p1, title="circle")

p2 = figure(plot_width=300, plot_height=300)
p2.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=3, color="navy", alpha=0.5)
tab2 = Panel(child=p2, title="line", closable=True)

tabs = Tabs(tabs=[ tab1, tab2 ])

curdoc().add_root(tabs)
```

**Comment by mattpap** [comment]
This attribute was complete ignored during implementation.

**Comment by bryevdv** [comment]
It appears `closable` was removed before 1.0 @mattpap should this be changed to `feature` or just closed?

**Comment by philippjfr** [comment]
I'd love to have the ability to close tabs. I'd vote to keep this open as a feature request.

**Comment by mattpap** [comment]
What should be the desired behavior? Should it remove panels from children or mark them as hidden (in some way) or both (configurable)?

**Comment by mattpap** [comment]
`closable` wasn't ever implemented. I must have removed it from the API when moving tabs from widgets to layouts.

**Comment by philippjfr** [comment]
Good question, I guess I'd expect it to drop the child by default, marking it as hidden is an interesting idea but raises the question of how you would then restore it.
