### ISSUE TITLE
Allow defining custom tooltip for certain tools

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#7499]
When using some of the more specific tools, e.g. the drawing tools, you might want to add multiple copies of the same tool and assign different semantics to each tool instance. As a simple example I wrote a demo that allows drawing two types of polygons to annotate the foreground and background of an image. In this case it is difficult to distinguish the two tool instances. It would therefore be nice if it were possible to assign the tools custom tooltips to distinguish between them.

Currently the tooltip simply reflects the ``tool_name`` on the model but it would be great if that could be overridden by another property. I think this only makes sense for certain types of tools, most likely the draw tools and maybe also the select tools.

**Comment by jbednar** [comment]
It would also be great if the icon could be overridden, for the same reason.  It might be difficult to support (and to provide) arbitrary new icons for each new usage, but at least some of the drawing tools can be used for quite different things and we could provide a selection of such icons to be chosen when instantiating the tool...

**Comment by mattpap** [comment]
> Currently the tooltip simply reflects the `tool_name`

No, tooltip is generated by a getter, which you can override. This is done in e.g. pan tool, which comes in three variants, pan, x-pan and y-pan, and all have different tooltips. 

> It would also be great if the icon could be overridden, for the same reason.

It can be. `icon` is defined as class attribute, but one can override it with a getter. Once again pan tool is a great example, as it has different icons for its each variant.

**Comment by philippjfr** [comment]
Thanks @mattpap, great to know this is already overridable at the JS level.

**Comment by jbednar** [comment]
But it sounds like there has to be a subclass for each variant?  Here it's about a Python user wanting to instantiate the same tool multiple times with different info each time.

**Comment by philippjfr** [comment]
No I was wrong about that before, at the JS level you can define a getter, for the pan tool it looks like this:

```javascript

  get tooltip(): string {
    return this._get_dim_tooltip("Pan", this.dimensions)
  }

  get icon(): string {
    switch (this.dimensions) {
      case "both":   return "bk-tool-icon-pan"
      case "width":  return "bk-tool-icon-xpan"
      case "height": return "bk-tool-icon-ypan"
    }
  }
```

**Comment by jbednar** [comment]
Ok, I guess then we can put in a few canned variants to choose from...

**Comment by philippjfr** [comment]
I've now made a PR to allow defining custom tooltips. After discussing the customizability of icon a bit we decided that it's probably easiest to offer a few alternative icons for specific edit tools and then offer a way to override the default. Does that seem sensible @bryevdv?

**Comment by philippjfr** [comment]
>sure, maybe just extend what CustomAction already does.

Could you clarify? With the current code it will use ``action_tooltip`` by default and ``custom_tooltip`` if it is defined. Once fully deprecated we would simply have the `CustomActionModel.tooltip` getter return the `custom_tooltip` as well and move the default `action_tooltip` string onto `custom_tooltip`.

**Comment by bryevdv** [comment]
I thought we were talking about icons? `CustomAction` let's users specify a custom icon.

**Comment by philippjfr** [comment]
Sorry, I was getting confused between this issue and the PR.

**Comment by philippjfr** [comment]
Yes, that makes perfect sense, I didn't realize that icon also accepts a base64 image, which gives a lot more flexibility.
