### ISSUE TITLE
Sphinx Bokeh Extension Script Directory Sorting

### ISSUE THREAD

**Issue by hallyourbase** [bokeh/bokeh#7505]
When adding specified directories to the `bokeh_plot_pyfile_include_dirs` the sphinx sorting of the source docs does not properly sort based on the directories or python files containing bokeh.

[This line](https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_plot.py#L268) seems to be catered specifically to the bokeh doc structure with the 'examples' directory. 

Ideally the sorting should put any directories specified in the sphinx configuration variable `bokeh_plot_pyfile_include_dirs` to be parsed first. I ran into the issue where not all of the python files containing bokeh code would be parsed before the `bokeh-plot` directive in a source doc RST was found which would result in a sphinx error when trying to build.

I was able to get my structure working which has two bokeh source directories under my normal RST source directory so it is something like:

Top level doc repo
--> source
|----> bokeh_dir_1
|----> Rest
|----> Of
|----> RSTs
|----> Z_bokeh_dir_2

I swapped out the previously linked line with:

```python
docnames.sort(key=lambda x: 0 if x.startswith(tuple(env.app.config.bokeh_plot_pyfile_include_dirs)) else 1)
```
This sorting method probably needs improvement, I don't think it will work if the desired directories are in lower depths of directories.

**Comment by bryevdv** [comment]
@hallyourbase would definitely be happy to merge a PR to add a `bokeh_plot_pyfile_include_dirs` (or similar name) config option.

**Comment by hallyourbase** [comment]
@bryevdv `bokeh_plot_pyfile_include_dirs` is already a config option ([here](https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_plot.py#L318)), the way the extension handles the sorting based on the contents of the option is the issue. Unless I am misunderstanding your comment.

**Comment by hallyourbase** [comment]
Correct. I think all it needs for proper functionality is the resulting sort to put all of the source bokeh python files in those directories specified in that config variable at the beginning of the `docnames` list so that they get parsed and the associated plot code generated before any `bokeh-plot` directive is reached in RST files which references the python file. That is my current understating anyway. I have not completely become familiar with all the ins and outs of the extension or sphinx extensions in general.

**Comment by bryevdv** [comment]
Yes I think that is correct. If you'd like to submit a PR I think that would be easiest for you to test on your end, and would be simple for me to test out on the project docs as well.
