### ISSUE TITLE
Sphinx bokeh-plot directive has no method for centering plot in generated html

### ISSUE THREAD

**Issue by hallyourbase** [bokeh/bokeh#7506]
When using the bokeh sphinx extension to embed bokeh plots in sphinx RST based documentation there is no way to center the resulting plots in the page. Some sort of additional configuration argument to `source-position` like `vertical-alignment` or something would be much appreciated.

**Comment by bryevdv** [comment]
I don't actually understand what is being requested here. Centering vertically is not really a sensible notion for HTML pages, which may have arbitrary length, with arbitrary content above and below. As this issue has been inactive with no follow for some time, I am going to go ahead and close. We can consider re-opening with a more detailed proposal.
