### ISSUE TITLE
'export_png' from bokeh.io triggers 'deprecated' warning from Selenium using PhantomJS

### ISSUE THREAD

**Issue by RedactedCode** [bokeh/bokeh#7510]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

'vanilla' Python installation.
No Anaconda, no virtualenv.
Packages installed with pip (9.0.1)

Python (3.5.0)

bokeh (0.12.13)

DateTime (4.2)
Jinja2  (2.10)
Pillow  (5.0.0)
PyYAML (3.12)
requests (2.18.4)
selenium (3.8.1)
six (1.11.0)
tornado (4.5.3)

PhantomJS (2.1.1) - only version that will work on my platform.

PuppyLinux 5.6.1 (32-bit, Ubuntu "Precise", kernel 3.2.44)

#### Description of expected behavior and the observed behavior

Expected:

Installation guide for bokeh should accurately reflect current versions of
dependencies.

Simple code should run without errors or warnings.

Observed:

Selenium prints warning that PhantomJS is deprecated when using 'export_png'.
Output file appears to be generated OK however.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure
from bokeh.io import export_png

p = figure(plot_width=400, plot_height=400)
p.vbar(x=[1, 2, 3], width=0.5, bottom=0,
       top=[1.2, 2.5, 3.7], color="firebrick")
       
export_png(p, filename="plot.png")

```

#### Stack traceback and/or browser JavaScript console output

/usr/local/lib/python3.5/site-packages/selenium/webdriver/phantomjs/webdriver.py:49:
UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless 

#### Screenshots or screencasts of the bug in action

None

**Comment by mattpap** [comment]
It looks like we will have to move to headless chrome sooner than later.

**Comment by bryevdv** [comment]
ping @hsparra just an FYI, the project is going to have to migrate to Chrome headless as a default, though that really needs to wait for conda packages. Clients who need to stay on PhantomJS for reasons may have to manage their selenium version explicitly to avoid these warnings (or in the future, to have it work at all)

**Comment by mattpap** [comment]
> (...) though that really needs to wait for conda packages.

Perhaps we should be more vocal for having those packages made. This is really the only obstacle from using headless chrome by default.

**Comment by bryevdv** [comment]
I have requested that Chrome Headless be added to Anaconda `defaults`: https://github.com/ContinuumIO/anaconda/issues/1279

**Comment by RedactedCode** [comment]
As I don't use anaconda, is it feasible for me (as a very naive user) to change over to headless  chrome (or ff)?

**Comment by bryevdv** [comment]
@RedactedCode This issue is just about making CH the default webdriver, which we would not want to do until CH is easily installable via conda. If you have installed it some other way, you can pass an explicit `webdriver` argument to the export functions.

**Comment by grifball** [comment]
got a really nasty error when I tried to use export_png today. Would've been a lot nicer if it had told me to install phantomjs (it isn't included in selenium anymore). Instead I got this:
`
Traceback (most recent call last):
  File "generate_images.py", line 19, in <module>
    export_png(p)#, filename="./plot.png")
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/site-packages/bokeh/util/api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/site-packages/bokeh/io/export.py", line 83, in export_png
    image = get_screenshot_as_png(obj, height=height, width=width, driver=webdriver)
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/site-packages/bokeh/util/api.py", line 190, in wrapper
    return obj(*args, **kw)
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/site-packages/bokeh/io/export.py", line 165, in get_screenshot_as_png
    web_driver = driver if driver is not None else _create_default_webdriver()
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/site-packages/bokeh/io/export.py", line 303, in _create_default_webdriver
    phantomjs_path = detect_phantomjs()
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/site-packages/bokeh/util/dependencies.py", line 78, in detect_phantomjs
    proc = Popen([phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/subprocess.py", line 1258, in _execute_child
    executable = os.fsencode(executable)
  File "/anaconda3/envs/graphing-web-project/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Comment by bryevdv** [comment]
> it isn't included in selenium anymore

@grifball We don't have any control when things change out from under, and only have much bandwidth to react. As this is a pure python side concern, a PR to make a better error message would be a great task for a new contributor, and certainly appreciated.

**Comment by grifball** [comment]
Sure! I'll try and do that after work

**Comment by bryevdv** [comment]
Great!

**Comment by bryevdv** [comment]
The PRs are still only in master, not yet a release. You would currently have to install a dev build to see the fixes.
