### ISSUE TITLE
Publish packages on npmjs.com for dependencies that we forked

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#7512]
This seems to be the logical next step in streamlining bokehjs' build. It would also slash `npm install` time by half or more.

**Comment by mattpap** [comment]
The time improvement argument isn't valid anymore with npm >= 5.6.

**Comment by bryevdv** [comment]
If that's the case, let's close this? This would be a much heaver process than just changing a tag on a forked repo in our org. I will proactively close this now, but if you feel strongly otherwise, certainly re-open.
