### ISSUE TITLE
Update examples and add documentation for Selection model

### ISSUE THREAD

**Issue by clairetang6** [bokeh/bokeh#7516]
The new Selection model which represents data sources' selections and inspections was added in [PR 7261](https://github.com/bokeh/bokeh/pull/7261). This issue is for updating examples, adding documentation, and potentially adding examples.

One example that can be added is how to set a selection on a network graph plot and then apply a policy. This would, for example, allow someone to set a selection based on node indices and then have the linked edges highlighted through the NodesAndLinkedEdges policy. 

- [x] update all examples to use new `Selection` model
- [ ] expand docs around the `Selection` model
- [x] Add a migration section to release notes (programmatically updated selections will break)

**Comment by bryevdv** [comment]
@clairetang6 I've updated examples and added the migration not, as well as exposed the module in the reference guide. I think more would be good but let's make a new issue for that.
