### ISSUE TITLE
Out of range float values are not JSON compliant with numpy arrays

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#7523]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 0.12.14

#### Description of expected behavior and the observed behavior

I get an error on both the client and server like the following:

    ERROR:bokeh.server.protocol_handler:error handling message Message 'PULL-DOC-REQ' (revision 1): ValueError('Out of range float values are not JSON compliant',)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.server.server import Server
from bokeh.plotting import figure, ColumnDataSource
import numpy as np

def handle_doc(doc):
    source = ColumnDataSource({'x': [], 'y': []})
    fig = figure()
    fig.line(x='x', y='y', source=source, line_width=1)

    data = {'x': np.array([  1.,   0.,  np.nan,   1.,   0.,  np.nan,
                             1.,   0.,  np.nan,   1.,   0.,  np.nan,
                             1.,   0.,  np.nan]),
            'y': np.array([  2.,   1.,  np.nan,   2.,   3.,  np.nan,
                             2.,   2.,  np.nan,   2.,   0.,  np.nan,
                             2.,   4.,  np.nan])}
    doc.add_root(fig)
    source.stream(data)
    # source.data.update(data)  # this works fine


apps = {'/': handle_doc}

server = Server(apps, port=5000)
server.start()

import tornado.ioloop
tornado.ioloop.IOLoop.current().start()
```

#### Stack traceback and/or browser JavaScript console output

```
[bokeh] setting log level to: 'info'
connection.js:194 [bokeh] Websocket connection 0 is now open
connection.js:188 Error: Error reply ValueError('Out of range float values are not JSON compliant',)
    at connection.js:131
    at es6-promise.js:281
    at f (es6-promise.js:290)
    at p (es6-promise.js:268)
    at MutationObserver.r (es6-promise.js:102)
(anonymous) @ connection.js:188
connection.js:189 [bokeh] Failed to repull session Error: Error reply ValueError('Out of range float values are not JSON compliant',)
(anonymous) @ connection.js:189
connection.js:221 [bokeh] Lost websocket 0 connection, 1006 ()
connection.js:105 [bokeh] Websocket connection 0 disconnected, will not attempt to reconnect
```

**Comment by mattpap** [comment]
The problem with `nan` (and `inf`) is that it must be passed via a numpy array, which is the case here. This may indicate that `stream()` converts to a list, which later can't be serialized.

**Comment by mattpap** [comment]
This will work if you change:
```
source = ColumnDataSource({'x': [], 'y': []})
```
to
```
source = ColumnDataSource({'x': np.array([]), 'y': np.array([])})
```
The reason is that the properties system tries to concatenate `[]` with a numpy array, and this results in a list, which later fails to serialize. This code is at fault:

https://github.com/bokeh/bokeh/blob/4f45e7480add13f6ab7dc9c781454107967dfbbe/bokeh/core/property/containers.py#L381-L391

A simple solution would be to add `or isinstance(new_data[k], np.ndarray)`.

**Comment by mrocklin** [comment]
That's quite helpful.  Thank you for the rapid response @mattpap !
