### ISSUE TITLE
Lag caused by adapting figure axis during pan action

### ISSUE THREAD

**Issue by AzraelDD** [bokeh/bokeh#7529]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Official Bokeh examples viewed in Edge and Chrome (Edge's poor performance is best for worst-case example) in Windows 10

#### Description of expected behavior and the observed behavior
If you zoom or pan a figure it often happens that the axis range changes in such a way that the axis needs to be redrawn. For example when the y_range [9, 99] changes to [10, 100] the extra digit requires more space and the axis is moved to the right. When such a redraw occurs while you keep panning, a lag happens. In single plots this is hardly noticeable, but in a more complicated grid with lots of figures it becomes annoying.

I would suggest the following:
Only adapt the location of the axis once the user ends the panning (i.e. after the mouse click is released). This way the user will not "feel" the lag, because there is no interaction while the redraw happens.

#### Complete, minimal, self-contained example code that reproduces the issue
https://bokeh.pydata.org/en/latest/docs/gallery/iris_splom.html
Zoom out and pan to the range [-10000, -5000]. Then pan up and down, such that -10.000 appears and disappears at the lower end. You can see how the y-axis is moved left and right, and you will feel a lag.

Regards

**Comment by AzraelDD** [comment]
For future reference, workarounds are discussed here:
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/9u8Q34FhUKY

**Comment by bryevdv** [comment]
I'm going to close this and defer to #7771
