### ISSUE TITLE
Update documentation after removal of `Range1d(start, end) syntax`

### ISSUE THREAD

**Issue by nanthony21** [bokeh/bokeh#7531]
I am trying to create a new Range1d object from within a CustomJS call, but I am getting the error `TypeError: Bokeh.Range1d is not a constructor`. I have tried `Bokeh.Range1d` which is what is shown in the documentation and I have also tried `Bokeh.Models.Range1d`. 

Upon further inspection it appears that these references are undefined. `Bokeh.Widgets` and `Bokeh.Tables` both contain all of the expected constructors but `Bokeh.Models` is empty except for properties like `bind`, `call`, `arguments`, etc.

When I look in the sources panel of the browser terminal I see bokeh-gl.min.js, bokeh-tables.min. js,bokeh-widgets.min.js, and bokeh.min.js. This has me wondering if there is a bokeh-models.min.js

This has been tested on OSX 10.13.3, Firefox and Chrome, Python 3.5.4, and Bokeh 0.12.11 through 0.12.14

**Comment by p-himik** [comment]
Models are in the main file, there's no separate file.
You should use `Bokeh.Models('Range1d')` instead.

The mention of `Bokeh.Range1d` in the documentation is probably something that got changed in the code but not in the documentation. After all, the "Developing with JavaScript" page says: "The BokehJS APIs are new as of version 0.12 and may undergo some changes before a 1.0 release."

**Comment by nanthony21** [comment]
Thanks, that helps. Is there somewhere I can find more information about the current API?
Running `var rng = Bokeh.Models("Range1d")` sets rng equal to `function e()`. However, if it try to call this function, `rng()` i get `TypeError: n.setv is not a function`. If I try to assign the result of `Bokeh.Models("Range1d")` to the x_range property of a Figure object I get `Error: Instance property 'x_range' given invalid value: undefined`.

The example given in "Developing with Javascript" is: 
```
// create some ranges for the plot
var xdr = new Bokeh.Range1d({ start: -0.5, end: 20.5 });
var ydr = Bokeh.Range1d(-0.5, 20.5);

// make the plot
var plot = new Bokeh.Plot({
    title: "BokehJS Plot",
    x_range: xdr,
    y_range: ydr,
    plot_width: 400,
    plot_height: 400,
    background_fill_color: "#F2F2F7"
});
```

How would something like this be done in the current implementation?

**Comment by p-himik** [comment]
It would be
```javascript
const Range1d = Bokeh.Models('Range1d');
var xdr = new Range1d({start: 1, end: 2});
```

Please ask further support questions on Bokeh Gitter, on Bokeh mail channel, or on StackOverflow with `bokeh` tag.

**Comment by mattpap** [comment]
> `var ydr = Bokeh.Range1d(-0.5, 20.5);`

We had to remove this syntax recently, though it looks like documentation wasn't updated.

**Comment by mattpap** [comment]
> `Bokeh.Range1d`

This is available when `bokeh-api(.min).js` is included. Otherwise one has to use `Bokeh.Models("Range1d")`, as @p-himik suggested. This will likely get simplified in near future.

**Comment by nanthony21** [comment]
Thanks, that got it working.
