### ISSUE TITLE
HowerTool detection broken for categorical axis

### ISSUE THREAD

**Issue by Tikonderoga** [bokeh/bokeh#7532]
For chart with categorical X-axis HoverTool is not providing correct tooltip $x.
Apparently, it was broken between bokeh 0.12.6 and 0.12.13 (and still not working in 0.12.14)

Sample code:
```
from bokeh.io import show, output_file
from bokeh.plotting import figure

tools = 'box_zoom, save, reset, hover'
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']

p = figure(x_range=fruits, plot_height=250, title="Fruit Counts",
           toolbar_location=None, tools=tools)

y_values = [5, 3, 4, 2, 4, 6]
p.line(fruits, y_values)

p.y_range.start = 0

hover = p.select(dict(type=HoverTool))
hover.tooltips = [
    ("Value", "$y"),
    ("Object Size/Operation", "$x")
]

show(p)

```

Bokeh 0.12.6, correct behavior 

![correct_hover_0126](https://user-images.githubusercontent.com/36517077/36278082-4bcf86dc-1258-11e8-9382-0b0b722c823d.jpg)

Bokeh 0.12.14, incorrect behavior 

![incorrect_hover_01214](https://user-images.githubusercontent.com/36517077/36278081-4bb19280-1258-11e8-8582-ecf8a2876e15.jpg)

Tested on 
* bokeh: 0.12.13, 0.12.14
* OS: Windows 7, Ubuntu 16
* Browser: Firefox 58

**Comment by philippjfr** [comment]
Try changing that to:

```python
hover.tooltips = [
    ("Value", "@{y}"),
    ("Object Size/Operation", "@{x}")
]
```

**Comment by Tikonderoga** [comment]
@philippjfr Thank you. Apparently I missed something in the change log.

**Comment by bryevdv** [comment]
I'm not sure the change was intentional but I'm not sure the original behavior wrt to categoricals was intentional, either. However reporting the underlying synthetic range seems reasonable going forward
