### ISSUE TITLE
Add tool with custom help information

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#7535]
I would like a tool to exist that, when clicked from the toolbar opens a large tooltip with custom HTML.  This would allow plot creators to include a caption or instructions on how to interpret or use the plot.  Does something like this already exist?  If not then is it in scope?

**Comment by philippjfr** [comment]
Sounds like a great suggestion to me and we discussed something similar to be able to add instructions for the new drawing tools. I think this would be useful to a lot of people.

**Comment by mattpap** [comment]
This is definitively in scope, and improved toolbar's customization ability is long overdue.

**Comment by bryevdv** [comment]
Personally I would be more inclined suggesting adding a `CustomJS` hook to the existing `HelpTool`

**Comment by mrocklin** [comment]
Quick check, can I use CustomJS without using node on my machine or the user's machine and without complicating my build system?  I think last time I tried a custom widget (possibly more complex) I found that it required node in various places.

**Comment by bryevdv** [comment]
`CustomJS` with pure JS code supplied should not need node AFAICT (correct me if I am mistaken, @mattpap)

**Comment by mattpap** [comment]
`CustomJS` is a special case that doesn't need node by default. Though this means no dependencies, etc., just pure JS.

**Comment by bryevdv** [comment]
This can now be accomplished with a `CustomAction` toolbar button.
