### ISSUE TITLE
Patch glyph draw lag in Firefox under certain zoom conditions

### ISSUE THREAD

**Issue by Timmeh42** [bokeh/bokeh#7536]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python version is 3.6.1
Bokeh version is 0.12.14
Browser is Firefox (Quantum) 58.0.2 64bit
Operating System is Windows 10

Issue does NOT appear on browsers:
Chrome Version 64.0.3282.167 (Official Build) (64-bit)
Microsoft Edge 41.16299.248.0
Microsoft Internet Explorer 11.248.16299.0

#### Description of expected behavior and the observed behavior
Plot draws a single Patch glyph using data from a file (1359 points).
Pan around the plot using the pan tool. Panning should produce minimal lag.
Next, zoom using the scroll-wheel tool so that the rightmost twenty-or-so steps of the plot are visible.
Panning around now produces noticeable lag such that the plot only draws a couple times per second.

The *expected* behaviour would be no difference in draw lag between different zoom levels.

Furthermore, zooming into the top-left data values does not produce the lag, nor the bottom-left corner.

#### Complete, minimal, self-contained example code that reproduces the issue

(Note: 'buys', 'amounts', and 'prices' refer to the original use of this plot as a market depth plot.)
```
import json
from bokeh.plotting import figure
from bokeh.io import show
from bokeh.models import ColumnDataSource

fil = open('sampledata.txt', 'r')
b, s = json.loads(fil.read())
fil.close()

#b['amounts'] = [-n for n in b['amounts']]

buys = ColumnDataSource(data=b)

plot = figure(lod_threshold=None, plot_width=1600)
plot.patch('prices', 'amounts', source=buys, fill_color='#00a000', line_alpha=0)
show(plot)
```
[sampledata.txt](https://github.com/bokeh/bokeh/files/1733724/sampledata.txt)

'sampledata.txt' is the file containing the json data used to draw the patch glyph; only roughly half the data is used in this example.
Unfortunately I have not been able to reproduce the issue with data generated in any different way.

NOTE: vertically flipping the data (uncomment the list comprehension in the middle) makes the issue disappear. However, subtracting a flat value (8000000) from the data to make the data all negative does not remove the issue.

#### Screenshots or screencasts of the bug in action
The 'Paint' event takes significantly longer when the issue is happening.
![unzoomed_performance](https://user-images.githubusercontent.com/20143631/36341405-693f2c0a-13f6-11e8-9c29-3b3a6853f293.jpg)
![zoomed_performance](https://user-images.githubusercontent.com/20143631/36341406-696ce960-13f6-11e8-9e26-ba0ddb41b796.jpg)

Note: I tested the glyph rendering itself in the patch.ts code by using console.time - and no difference was apparent in the time it took to render at either zoom level (both was ~4ms) even when the lag issue was happenning, ie. the issue is at least not in the glyph-specific code.

I'm unsure if the above is clear enough, or even if anyone else will be able to replicate it; but I thought it best to put it in an issue anyway.

**Comment by bryevdv** [comment]
Thanks for the detailed report @Timmeh42 we will investigate it more as we are able

**Comment by bryevdv** [comment]
With 1.1.0dev9 I can no longer produce any issue with the above code with recent FF (65.0.2) on either Win10 or OSX. Either we did something that improved things, or it was an upstream problem in older FF we would not be able to control, so closing now.
