### ISSUE TITLE
Exporting to PNG; phantomjs error

### ISSUE THREAD

**Issue by ahuang11** [bokeh/bokeh#7544]
Windows Subsystem Linux
Python 3.6.3 Anaconda 64 bit
Chrome
bokeh = 0.12.14

When saving to a bokeh plot to png I get
```RuntimeError: PhantomJS is not present in PATH. Try "conda install phantomjs" or             "npm install -g phantomjs-prebuilt"```

And I saw the [issue](https://github.com/bokeh/bokeh/issues/7327) and this [PR](https://github.com/bokeh/bokeh/commit/9dbebeb8170cc16c7e34a1d003d253e494a8bcb8#diff-9773c1b6f19d42fd0af19d6913002f4cR67).

So I tried running the steps by hand.
```
>>> from subprocess import Popen
>>> from subprocess import PIPE
>>> phantomjs_path = shutil.which('phantomjs')
>>> phantomjs_path
'/home/solactus/anaconda3/bin/phantomjs'
Popen([phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/solactus/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/solactus/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/solactus/anaconda3/bin/phantomjs'
```
And when I looked up the [error ](https://stackoverflow.com/a/27777324/9324652) and try adding 'sh' like this:
```
>>>Popen(['sh', phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
<subprocess.Popen object at 0x7fc46df93908>
```
It doesn't error out; so I was thinking maybe adding the 'sh' to line 67 of `bokeh/util/dependencies.py`?

Here's a quick sample code that was taken from the previous issue.
```
from bokeh.io import export_png
from bokeh.plotting import figure, show

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

export_png(p, filename="plot.png")
```

**Comment by mattpap** [comment]
Can you show us output from `file /home/solactus/anaconda3/bin/phantomjs`? Or, assuming it's a standard shell script, its contents. It's likely that the anaconda package is just broken. Additionally, phantomjs isn't part of `defaults` channel anymore, so we will need to change installation instructions. Version installed from `conda-forge` channel works correctly.

**Comment by ahuang11** [comment]
Okay, I tried reinstalling both bokeh and phantomjs thru conda-forge, but doesn't work for me. Here's the output of /home/solactus/anaconda3/bin/phantomjs. I suspect it has something to do with me using Windows Subsystem Linux.

```python
x = Popen(['sh', phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
In [18]: x.communicate()
Out[18]:
(b'',
 b'/home/solactus/anaconda3/bin/phantomjs: 1: /home/solactus/anaconda3/bin/phantomjs: \x90\xec\x03: not found\n/home/sola
ctus/anaconda3/bin/phantomjs: 1: /home/solactus/anaconda3/bin/phantomjs: \x80L\x04\x08\x10\x0f\x811\x01\x01\x01\xa2\x01\x
f0\x03\x01*\x05\x01Y\x05\x01r\x05\x01\x96: not found\n/home/solactus/anaconda3/bin/phantomjs: 1: /home/solactus/anaconda3
/bin/phantomjs: @: not found\n/home/solactus/anaconda3/bin/phantomjs: 1: /home/solactus/anaconda3/bin/phantomjs: \x80L\x0
4\x1b: not found\n/home/solactus/anaconda3/bin/phantomjs: 2: /home/solactus/anaconda3/bin/phantomjs: \x901\x0b\x18\x15\x0
3\x88\x1ei\x04\x02\x90*\x14\x07\x17X\xad@\x07@\x9b@\x08\x18\x12: not found\n/home/solactus/anaconda3/bin/phantomjs: 1: /h
ome/solactus/anaconda3/bin/phantomjs: \x97\x0c\x04@8: not found\n/home/solactus/anaconda3/bin/phantomjs: 2: /home/solactu
s/anaconda3/bin/phantomjs: @!: not found\n/home/solactus/anaconda3/bin/phantomjs: 1: /home/solactus/anaconda3/bin/phantom
js: \x80L\x04: not found\n/home/solactus/anaconda3/bin/phantomjs: 1: /home/solactus/anaconda3/bin/phantomjs: cannot creat
e \x01xvA@\x90\xec\x03\x80L\x04\x98\x05: Directory nonexistent\n/home/solactus/anaconda3/bin/phantomjs: 1: /home/solactus
/anaconda3/bin/phantomjs: \x7fELF\x02\x01\x01\x02: not found\n/home/solactus/anaconda3/bin/phantomjs: 4: /home/solactus/a
naconda3/bin/phantomjs: \x12\xa2: not found\n/home/solactus/anaconda3/bin/phantomjs: 5: /home/solactus/anaconda3/bin/phan
tomjs: \x12\x9f\x06\x12\xa2\x16\x12!\x13\x12\x05\x06\x12\xd4\x02\x12r\r\x11\xbf\x0e\x12\x04\x0f\x12M\x14\x12+\x17\x12\xb6
\x16\x12\xb8\r\x11\xe6\x16\x12Z\x13\x12\x81\x10\x12R\x02\x12\x07\x11\x12J\r\x12\x8c\x06\x12\x1a: not found\n/home/solactu
s/anaconda3/bin/phantomjs: 6: /home/solactus/anaconda3/bin/phantomjs: \x12*\x06\x12o\x13\x12\xbd\x0f\x12\x8c\x10\x12@\x04
\x12: not found\n/home/solactus/anaconda3/bin/phantomjs: 1: /home/solactus/anaconda3/bin/phantomjs: Syntax error: word un
expected (expecting ")")\n')
```

Thanks for your help!

**Comment by bryevdv** [comment]
@ahuang11 can you attach the output asked for above by @mattpap

**Comment by ahuang11** [comment]
Sorry, I misread; I thought `x.communicate` is the output.

Here's `file /home/solactus/anaconda3/bin/phantomjs`
```
02-20 19:01 /mnt/c/Users/Solactus/GOOGLE~1/Bash/sketches: 
/home/solactus/anaconda3/bin/phantomjs: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses sh
ared libs), for GNU/Linux 2.6.26, BuildID[sha1]=d0f2a21ff9e0b82113a2095e7cbca7dceaba88fb, stripped 
```

**Comment by bryevdv** [comment]
@ahuang11 It's possible this is an upstream issue: https://github.com/Microsoft/WSL/issues/1884 I just don't know enough (anything at all really) about WSL to say more. Checking for / trying `sh` unconditionally in `dependencies.py`  is not appropriate for all platforms, but perhaps we could give it a try on the event of an `OSError`. If there is a way to more narrowly identify this exact situation that would be preferable. I guess we could check the exception for `exec format error` but if there's any better option I'd love to hear.

**Comment by bryevdv** [comment]
@ahuang11 also would you want to work up a PR for this? No one on the core team uses windows regularly, this will happen much faster with your participation, just FYI.

**Comment by ahuang11** [comment]
That's understandable because I don't know anything about it either.

And actually, when I changed it to 'sh' in the source, I still wasn't able to produce png images so I don't think my "quick fix" fixed anything at all.

Thanks for your help though!

**Comment by bryevdv** [comment]
@ahuang11 ah I see, I think I am inclined to close this as `wontfix` in that case. I hate to do that, but realistically available resources/knowledge vs priority dictates that will be the outcome regardless. If you do find a workaround that generates images on WSL please post it here, we can re-open.

As a final thought: does it work if you install `phantomjs` some other way besides using conda?

**Comment by ahuang11** [comment]
Haha, amazing; I just tried doing this on my laptop which has the latest (?) Windows build (version 1709) and tried installing selenium with conda-forge (which I didn't do [or forgot how I did] on my desktop), and I was able to successfully export it to a png! Should I reopen this then?

**Comment by bryevdv** [comment]
>  Should I reopen this then?

No, I'll point the maintainers of the `defaults` channel at this info, perhaps they can adopt whatever recipe C-F is using. Or possibly it was a Windows bug after all that resolved upstream. 

> How do I tell it to use headless versions of Chrome/Firefox?

I haven't done it myself yet so I can't offer any specifics. The export functions accept a `webdriver` parameter, and there is a way to get a chrome web driver object from selenium

**Comment by PanditPranav** [comment]
I was facing the same issue for my python 3.7 environment which was not the root.  I was able to solve it by installing phantomjs in the root. 

> Windows Subsystem Linux
> Python 3.6.3 Anaconda 64 bit
> Chrome
> bokeh = 0.12.14
> 
> When saving to a bokeh plot to png I get
> `RuntimeError: PhantomJS is not present in PATH. Try "conda install phantomjs" or "npm install -g phantomjs-prebuilt"`
> 
> And I saw the [issue](https://github.com/bokeh/bokeh/issues/7327) and this [PR](https://github.com/bokeh/bokeh/commit/9dbebeb8170cc16c7e34a1d003d253e494a8bcb8#diff-9773c1b6f19d42fd0af19d6913002f4cR67).
> 
> So I tried running the steps by hand.
> 
> ```
> >>> from subprocess import Popen
> >>> from subprocess import PIPE
> >>> phantomjs_path = shutil.which('phantomjs')
> >>> phantomjs_path
> '/home/solactus/anaconda3/bin/phantomjs'
> Popen([phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/solactus/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
>     restore_signals, start_new_session)
>   File "/home/solactus/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> OSError: [Errno 8] Exec format error: '/home/solactus/anaconda3/bin/phantomjs'
> ```
> 
> And when I looked up the [error ](https://stackoverflow.com/a/27777324/9324652) and try adding 'sh' like this:
> 
> ```
> >>>Popen(['sh', phantomjs_path, "--version"], stdout=PIPE, stderr=PIPE)
> <subprocess.Popen object at 0x7fc46df93908>
> ```
> 
> It doesn't error out; so I was thinking maybe adding the 'sh' to line 67 of `bokeh/util/dependencies.py`?
> 
> Here's a quick sample code that was taken from the previous issue.
> 
> ```
> from bokeh.io import export_png
> from bokeh.plotting import figure, show
> 
> # prepare some data
> x = [1, 2, 3, 4, 5]
> y = [6, 7, 2, 4, 5]
> 
> # create a new plot with a title and axis labels
> p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')
> 
> # add a line renderer with legend and line thickness
> p.line(x, y, legend="Temp.", line_width=2)
> 
> export_png(p, filename="plot.png")
> ```
I was facing the same issue for my python 3.7 environment which was not the root.  I was able to solve it by installing phantomjs in the root.

**Comment by zbarry** [comment]
> I was facing the same issue for my python 3.7 environment which was not the root. I was able to solve it by installing phantomjs in the root.

My scenario (which might have been yours) was running a JupyterLab server from one conda environment and the notebook python kernel from another. `conda install -c conda-forge Phantomjs` in the JupyterLab conda environment instead of the kernel environment solved the problem.
