### ISSUE TITLE
TextInput selection drops on layout recomputation

### ISSUE THREAD

**Issue by ivan-usov** [bokeh/bokeh#7545]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
The issue appeared in bokeh/0.12.11, still exist in 0.12.14.
Probably, was introduced in #7197 

#### Description of expected behavior and the observed behavior
TextInput selection drops on layout recomputation, which makes it very difficult to change a content of editable fields in e.g. data streaming applications when this recomputation happens regularly/periodically under certain circumstances.

#### Complete, minimal, self-contained example code that reproduces the issue
1) Run the example with `bokeh serve`
2) Press the button to start a series of axis updates that cause layout recomputation
3) Try to edit the TextInput field during these updates
```
from time import sleep
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import Plot, DataRange1d, ColumnDataSource, LinearAxis, Line, Button, TextInput

plot = Plot(x_range=DataRange1d(), y_range=DataRange1d())
source = ColumnDataSource(dict(x=[0, 1], y=[0, 1]))
plot.add_glyph(source, Line(x='x', y='y'))
plot.add_layout(LinearAxis(), place='left')

def button_callback():
    for _ in range(10):
        source.data.update(y=[0, 10e3])
        sleep(1)
        source.data.update(y=[0, 1])
        sleep(1)

button = Button(label="Periodic layout update")
button.on_click(button_callback)

text_input = TextInput(value="Try to edit this")

curdoc().add_root(column(plot, button, text_input))
```

**Comment by bryevdv** [comment]
Sorry this got overlooked. Callbacks should not ever `sleep` directly. That will block the bokeh server. If you need things to happen periodically, use periodic callbacks, and if you need to do other kinds of blocking work, put it in other threads as described here:

https://bokeh.pydata.org/en/latest/docs/user_guide/server.html#updating-from-threads

**Comment by ivan-usov** [comment]
Hi @bryevdv , indeed, the blocking operations should have been put into coroutines, however, this doesn't affect the core of the issue. Following is the updated example with the same problem: editing TextInput drops on layout recomputation, which can be very unfortunate in various streaming applications at moments when users need to interact with TextInput fields.

```python
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import Plot, DataRange1d, ColumnDataSource, LinearAxis, Line, Button, TextInput
from tornado import gen

plot = Plot(x_range=DataRange1d(), y_range=DataRange1d())
source = ColumnDataSource(dict(x=[0, 1], y=[0, 1]))
plot.add_glyph(source, Line(x='x', y='y'))
plot.add_layout(LinearAxis(), place='left')

doc = curdoc()

@gen.coroutine
def update():
    if source.data['y'] == [0, 1]:
        source.data.update(y=[0, 10e3])
    else:
        source.data.update(y=[0, 1])

def button_callback():
    doc.add_periodic_callback(update, 1000)

button = Button(label="Add periodic layout update")
button.on_click(button_callback)

text_input = TextInput(value="Try to edit this")

doc.add_root(column(plot, button, text_input))
```
