### ISSUE TITLE
Gridplot / rowplot broken (bokeh version 0.12.14)

### ISSUE THREAD

**Issue by FedericoV** [bokeh/bokeh#7548]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh version: 0.12.14
Ubuntu 14.04

- Python: 3.5.4 |Anaconda custom (64-bit)| (default, Nov 20 2017, 18:44:38) 
[GCC 7.2.0]
- IPython: 6.2.1
- Bokeh: 0.12.14

#### Description of expected behavior and the observed behavior
Attempting to reproduce the simple gridplot example: https://bokeh.pydata.org/en/latest/docs/user_guide/layout.html#rows gives this error.  I get the same error using column plots or grid plots (complaints about lists not having references).

#### Stack traceback and/or browser JavaScript console output

AttributeError                            Traceback (most recent call last)
<ipython-input-90-3090ee2a5888> in <module>()
     19 
     20 # put the results in a row
---> 21 show(row(s1, s2, s3))

~/src/anaconda3/lib/python3.5/site-packages/bokeh/util/api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

~/src/anaconda3/lib/python3.5/site-packages/bokeh/io/showing.py in show(obj, browser, new, notebook_handle, notebook_url)
    126 
    127     if obj not in state.document.roots:
--> 128         state.document.add_root(obj)
    129     return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
    130 

~/src/anaconda3/lib/python3.5/site-packages/bokeh/document/document.py in add_root(self, model, setter)
    241             self._roots.append(model)
    242         finally:
--> 243             self._pop_all_models_freeze()
    244         self._trigger_on_change(RootAddedEvent(self, model, setter))
    245 

~/src/anaconda3/lib/python3.5/site-packages/bokeh/document/document.py in _pop_all_models_freeze(self)
    921         self._all_models_freeze_count -= 1
    922         if self._all_models_freeze_count == 0:
--> 923             self._recompute_all_models()
    924 
    925     def _recompute_all_models(self):

~/src/anaconda3/lib/python3.5/site-packages/bokeh/document/document.py in _recompute_all_models(self)
    929         new_all_models_set = set()
    930         for r in self.roots:
--> 931             new_all_models_set = new_all_models_set.union(r.references())
    932         old_all_models_set = set(self._all_models.values())
    933         to_detach = old_all_models_set - new_all_models_set

AttributeError: 'list' object has no attribute 'references'

**Comment by FedericoV** [comment]
Dug into this a bit more: I reset the notebook and everything worked ok, but apparently there was some implicit state that I messed with that caused it not to work.

I will try to see if I can make this reproducible: for now, it's working, and getting it to a situation where it doesn't work is somewhat complicated.

**Comment by bryevdv** [comment]
This seems exceedingly uncommon (it's never happened to me nor have I seen other reports). That doesn't mean it shouldn't be fixed if possible, but we will need to reproduce first. I will close this with `norepro` now but we can re-open any time it becomes reproducible.

**Comment by aaronwflee** [comment]
I'm facing this exact problem and error message -- restarting notebook hasn't helped me yet. Any ideas?

Bokeh 0.12.15
Python 3.6.5

**Comment by bryevdv** [comment]
As I stated above, what we need to be able to investigate is a complete minimal script to reproduce the problem

**Comment by pde** [comment]
@bryevdv [here's a simple reproduction](https://colab.research.google.com/drive/1Om2vF-2-mZA-vLcS9KyA6aUXZiywWwsY#scrollTo=pT4Qn5kkwRJG).

**Comment by bryevdv** [comment]
@pde why are you calling `curdoc().add_root(...)` ? In order to function in the notebook at all Bokeh has to do some gymnastics with documents on over individual cell eval. We don't demonstrate the kind f usage you have anywhere. You should just call `show`
