### ISSUE TITLE
bokeh channel on anaconda.org contains broken version of packaging?

### ISSUE THREAD

**Issue by ceball** [bokeh/bokeh#7549]
It seems that `conda install -c bokeh bokeh` doesn't work on win-64. I think the reason is because `conda install -c bokeh packaging` doesn't work:

<img width="640" alt="screen shot 2018-02-20 at 10 19 48 pm" src="https://user-images.githubusercontent.com/1929/36455764-8ba1508e-1699-11e8-8c1e-b5dac7065d68.png">

If I install packaging from conda-forge or defaults, I don't have a problem installing packaging.

I seem to get the problem whether using latest available conda 4.4 or latest available conda 4.3. The problem also showed up on another machine (on appveyor, as part of a much larger installation of packages).

I have not yet tested win-32.

Not sure that this is the right place to make this issue, but I wanted to record it somewhere.

**Comment by bryevdv** [comment]
I've removed `packaging` from the bokeh channel
