### ISSUE TITLE
Make BoxEditTool match PolyDrawTool UI

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#7553]
The new [drawing tools in Bokeh 0.12.14](http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html) are great, but there seems to be one inconsistency: BoxEditTool uses a shift tap to start a new shape, while PolyDrawTool uses double tap.  In both cases the user is starting an operation that will involve collecting multiple taps at different locations, so it seems to me that this should be the same user action in both cases. To make the interfaces more consistent, and possibly to make box drawing more feasible on tablets, can BoxEditTool be changed to start with a double tap instead of a shift tap?

**Comment by mattpap** [comment]
Let me know when this will be worked on, because currently UI events are under a complete rewrite.

**Comment by bryevdv** [comment]
I would be +0 to making it startle with *either*, so that the current behavior does not change or go away.

**Comment by jbednar** [comment]
Seems fine for both to start with *either* a shift-tap or a double-tap, sure!

**Comment by bryevdv** [comment]
@philippjfr would you be able to add this?

**Comment by philippjfr** [comment]
I'd be happy to, presumably not for 0.12.15 though?

**Comment by bryevdv** [comment]
If you can do it before friday, then yes

**Comment by philippjfr** [comment]
Okay, worked up a PR.
