### ISSUE TITLE
bokeh layout rows and columns not responsive on scale_width or scale_height

### ISSUE THREAD

**Issue by Zyell** [bokeh/bokeh#7554]
I recently upgraded from bokeh 0.12.10 to 0.12.14 (Python 3.6 on both Linux and Windows using Chrome) and found that many of my apps were broken due to scale_width not functioning as it used to.  The change appears to have occurred after 0.12.10.  I found two possibly related issues, #7454 and #7270, and one of them mentions a pull request which I also believe to be the culprit for this behavioral change, #7008.  

Below is a piece of code I used to confirm the behavior difference between 0.12.10 and 0.12.14 (and all releases in between behave like 0.12.14):
```python
from bokeh.plotting import figure, output_file, show
from bokeh.layouts import column, row

output_file('layout_issue.html')

plots = []
for i in range(15):
    p = figure(plot_width=400, plot_height=400)
    p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
    plots.append(p)

show(column(row(*plots), sizing_mode='scale_width'))
```

If you run this code, you will see that in bokeh 0.12.10, the plots will wrap at the width of the view screen in order to fit within the width of the screen.  In bokeh 0.12.14, these plots stay in a single row and extend beyond the screen to the right.

I found the aforementioned issues and took a look at the suggested pull request.  I found that layout.less had been altered.  You will see that the lines containing CSS class declarations for bk-layout-fixed, bk-layout-scale_width, and bk-layout-scale_height have been [removed](https://github.com/bokeh/bokeh/pull/7008/files#diff-4e802fe0944cb0aa4b36e3ad30323c78L3).  However, if you look at the div elements created by the above script, you will find that these class declarations are still applied to the generated divs based on your selected sizing mode.  Because of the flex box selections present now in layout.css [using nowrap](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/less/layout.less#L4), the fixed layout is the default and only available choice no matter the sizing mode you choose.

I got around this by redefining those dropped css classes in an html template.  I set the attributes of these classes to important in order to override those previous settings.  It also looks like the div is given an explicit height and width.  This will cause the wrapping of the plots to overflow onto subsequent elements in a page when embedded.  Overriding the height and/or width back to auto corrects this issue when embedding the plots in another page, as demonstrated in the below code:
```python
from bokeh.plotting import figure
from bokeh.layouts import column, row
from bokeh.embed import components
from bokeh.resources import CDN

plots = []
for i in range(15):
    p = figure(plot_width=400, plot_height=400)
    p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
    plots.append(p)
final = column(row(plots), sizing_mode='scale_width')
html_structure = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    {CDN.render()}
    <style>
        .bk-layout-scale_width {{
          height: auto !important;
          flex-wrap: wrap !important;
          -webkit-flex-wrap: wrap !important;
        }}
        .bk-layout-scale_height {{
          width: auto !important;
          flex-wrap: wrap !important;
          -webkit-flex-wrap: wrap !important;
        }}
    </style>
</head>
<body>
{"".join(components(final))}
<div>Testing a trailing element</div>
</body>
</html>
"""
with open('plot.html', 'w') as ph:
    ph.write(html_structure)
```

I've tested this in my use cases and played with the scale_height a little (though I don't use this much).  I can't speak to other layout scaling options, but I use scale_width a lot.

I'm not sure if placing the above css classes into layout.less is the best way to go.  I'm not sure what the overall vision is for layout responsiveness.  But, using the css class statements above restored some vital functionality for me.  I do think that the sizing mode language on the docs doesn't really match the behavoir in the layout.  It makes sense for a single plot where an aspect ratio is indeed preserved.  But, for a row that wraps to multiple lines as the viewport changes, there is no preservation of a "row aspect ratio".  So, like I said, I'm not sure the direction you want to take things, but I'm happy to make a pull request for the above CSS classes in layout.less.  Until then, hopefully this workaround will help others who may have run into this same issue.

**Comment by mattpap** [comment]
> `column(row(*plots), sizing_mode='scale_width')`

I'm not sure how to interpret this. `column()` applies `sizing_mode` only to its direct children (`row()` in this case), so plots won't be scaled at all (I presume that's the point here). In any case, I went ahead and tested all sensible combinations of this setup, and everything seems to work correctly now. I'm going close this as fixed. If there is something that doesn't work, please reopen.
