### ISSUE TITLE
datetime issue: between the datetime view of x_label and the real value corresponding is shifted 10 days

### ISSUE THREAD

**Issue by xexiyong** [bokeh/bokeh#7557]
For I watch the demo application in this link,the figure with title 'AAPL' and 'GOOG',its x label value is shifted 10 days.
[https://demo.bokehplots.com/apps/stocks](url)
For example,first I focus on a fixed x label time-point with mouse, the datetime value is 2010; and I scale up the figure with 'Wheel Zoom' tools, the datetime value is July 10, 2010; and scale up again,the datetime value is 07/01, 2010.
Is this problem a bug?it may be affect the view of the web page.

**Comment by bryevdv** [comment]
@xexiyong I can see why this could be confusing. The `Jul 10` label does *not* mean July 10, 2010, rather it means "July 2010" (i.e. the 10 refers to the year 2010) and then when you zoom in further, you can see it specially means July 1st (of 2010). 

It's possible the default date time printing formats could be tweaked or improved at some scales. You can see the default formats here: 

https://bokeh.pydata.org/en/latest/docs/reference/models/formatters.html#bokeh.models.formatters.DatetimeTickFormatter

If you have specific ideas for changes, please feel free to open a new issue with those suggestions (or just a PR that implements them). Of course, the values are completely configurable so you can immediately set the formats to new values if you want the printed date values to always be more detailed, e.g.

**Comment by xexiyong** [comment]
Thanks for remind me!
