### ISSUE TITLE
CheckboxButtonGroup active list broken in 0.12.14

### ISSUE THREAD

**Issue by AzraelDD** [bokeh/bokeh#7562]
### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 0.12.14
Windows 10
Firefox

### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.models.widgets import CheckboxButtonGroup
from bokeh.layouts import column
from bokeh.io import curdoc

def cbg_callback(active):
    print(active)

cbg = CheckboxButtonGroup(labels=['foo', 'bar', 'baz'], active=[0, 1, 2])
cbg.on_click(cbg_callback)

layout = column(cbg)
curdoc().add_root(layout)
```

### Description of expected behavior and the observed behavior
When clicking on button 0 'foo' four times, we get the following print:
#### Expected (output in 0.12.13)
```
[1, 2]
[0, 1, 2]
[1, 2]
[0, 1, 2]
```

#### Observed in 0.12.14
```
[1, 2]
[1]
[]
[0]
```
As you see, the active list status behaves strangely. 
Pressing only button 2 'baz' repeatedly actually produces the expected output, but the second click on 1 deselects 2 as well.
A little more testing with longer lists of buttons seems to indicate that each button deselects the ones that have a higher index, one after the other.

Pressing button 0 in a five button group (all start active):
```
[1, 2, 3, 4]
[1, 2, 3]
[1, 2]
[1]
[]
[0]
```
Pressing button 2 in a five button group (all start active):
```
[0, 1, 3, 4]
[0, 1, 3]
[0, 1]
[0, 1, 2]
```

I hope there is a simple fix!

### Edit
You don't even need to run the code above. Just go to the examples to see the issue:
https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html#checkbox-button-group

Maybe it has to do with this commit?
https://github.com/bokeh/bokeh/commit/75460498f061aa1ae1b1f4aab2a27eb3890782f6#diff-cf1ec3cccc01a186330ccab9f26b5542

**Comment by bryevdv** [comment]
@mattpap This is a pretty bad bug, we should fix it for the next release. I started looking into it and quickly got frustrated, the value of `checkbox.checked` seemed entirely unreliable, presumably for some JSBS reasons I don't know about. Explicitly managing and checking the active list does work:
```
  change_input(i: number): void {
    const active: number[] = []

    const labels = this.model.labels
    for (let j = 0; j < labels.length; j++) {
      if (i != j) {
        if (includes(this.model.active, j)) {
          active.push(j)
        }
      }
      else {
        if (!includes(this.model.active, j)) {
          active.push(j)
        }
      }
    }

    this.model.active = active

    if (this.model.callback != null)
      this.model.callback.execute(this.model)
  }
}
```

Of course, that's not great since it calls `include` in a loop every time, which is presumably quadratic. But perhaps the usual number of checkboxes is small enough that this is OK. If you have a better fix I'd love to use it, though.

**Comment by bryevdv** [comment]
Ok, this also works and is considerably simpler and not quadratic:
```
  change_input(i: number): void {
    const active = copy(this.model.active)
    if (includes(active, i))
      removeBy(active, (j) => i == j)
    else
      active.push(i)

    active.sort()

    this.model.active = active

    if (this.model.callback != null)
      this.model.callback.execute(this.model)
  }
}
```
I will prepare a PR based on this.

**Comment by bryevdv** [comment]
Another advantage of the second version is that it can be moved to the model and put under test.
