### ISSUE TITLE
'ServerSession' object has no attribute 'session_context'

### ISSUE THREAD

**Issue by aayla-secura** [bokeh/bokeh#7580]
Using version 0.12.14 with python3.6. When there is at least one active session, accessing `server_context.sessions`, where `server_context` is a `bokeh.server.application_context.BokehServerContext` instance passed to my `on_server_loaded` handler, results in the following `AttributeError`:

```
  File "/usr/local/lib/python3.6/dist-packages/bokeh/server/application_context.py", line 40, in sessions
    result.append(session.session_context)
AttributeError: 'ServerSession' object has no attribute 'session_context'
```

The relevant lines of `server/application_context.py` are:

```
    @property
    def sessions(self):
        result = []
        for session in self.application_context.sessions:
            result.append(session.session_context)
        return result
```

Each item in the list `self.application_context.sessions` is a `bokeh.server.session.ServerSession` instance and does not have a `session_context` attribute.

It's not clear to me how one gets the session context (a `bokeh.server.application_context.BokehSessionContext` instance) from the session object. Also, should `server_context.sessions` return a list of `bokeh.server.session.ServerSession` instances or `bokeh.server.application_context.BokehSessionContext` instances?

**Comment by bryevdv** [comment]
What exactly are you trying to accomplish? By and large all the classes you've mentioned are not really useful or intended for general users.

**Comment by aayla-secura** [comment]
I'm following the approach given [here](https://groups.google.com/a/continuum.io/d/msg/bokeh/qVVfCUu_eow/cDZjQcVbBQAJ)
to start a single ThreadPoolExecutor on_server_load and have it update all active sessions with the data that it gets. But I can't access the session contexts, hence their `with_locked_document` methods.

In any case, this looks like a bug.

**Comment by bryevdv** [comment]
@aayla-secura I'm happy to look at this if you can provide a Minimal Reproducing Example code.

**Comment by bryevdv** [comment]
Also, to answer your question, I think one way is to go through `session.document.session_context`, which might just be the right change to make in general. But I'd like to try it out in your MRE.

**Comment by aayla-secura** [comment]
@bryevdv , you are right, session.document.session_context works, I think that would be the fix. Here's a MRE:

```
# server_lifecycle.py

from time import sleep
from threading import Thread

def updater(server_context):
    while True:
        sleep (1)
        try:
            sessions = server_context.sessions  # this fails
        except AttributeError as e:
            print(str(e))
            sessions = server_context.application_context.sessions
        for s in sessions:
            try:
                session_context = s.doc.session_context  # this works
            except AttributeError as e:
                print(str(e))
            return

def on_server_loaded(server_context):
    thread = Thread(target=updater, args=[server_context])
    thread.daemon = True
    thread.start()
```

This in a directory with an empty `main.py` prints the error when a session if first created.
