### ISSUE TITLE
Strange behavior in live plot with timestamp

### ISSUE THREAD

**Issue by HyETBV** [bokeh/bokeh#7589]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
python 3.6
bokeh 0.12.13
tornado 4.5.3

#### Description of expected behavior and the observed behavior

Offset in data with a live plot.
I create a live plot using data from a can bus. in a thread, i gather the data, and save it in a dictionary with a timestamp generated with cur_time = time.time()
data["time"] = cur_time
data["value"] = 95.0

then i append this data to a bigger dataframe:
if self.total_data is not None:
    self.total_data = self.total_data.append(
        pandas.DataFrame.from_dict(data), ignore_index=True
    )
else:
    self.total_data = pandas.DataFrame.from_dict(data)

this step has a sleep in it:
time.sleep(0.05)
This is done in a thread, and i check the timestamps that are in this dataframe, and they are correct.
(because i also log the dataframe in a file). i tail the dataframe to keep the size limited

Then, on a periodic callback (of 500ms), i add the data to the columnsource
df = self.devices[key]["update_thread"].total_data  # .to_json(orient="records")
    self.devices[key]["overview_data"].data = dict(
        time=df["time"],
        value=df["value"] 
)

checked the timestamps at this function, still good.
this updates the plots like i want them (showing only a subset of the data), however, the time on the plot and the correct time is not correct
![image](https://user-images.githubusercontent.com/35219732/36889411-2147090a-1dfa-11e8-87fc-2b87ee571c82.png)
and when i check the corresponding timestamp using datetime, i get the correct time.
print(datetime.datetime.fromtimestamp(timestamp).strftime('%T'))
09:04:41
i also noticed when i zoomed out, the date was wrong too.

any ideas what is going on here?

**Comment by bryevdv** [comment]
Does your python side data have any timezone associated? The most consistent thing we have been able to do absent more expertise and help was to make Bokeh always timezone naive. Dates are passed to BokehJS "as is" without any TZ information (i.e. assumed to be a local time)

**Comment by bryevdv** [comment]
Additionally @HyETBV please provide a *complete* reproducing example, as the issue template asks for. We must be able to run code to reproduce a problem in order to investigate it.

**Comment by HyETBV** [comment]
``` python3.6
import numpy
import time
from bokeh.models import ColumnDataSource, DatetimeTickFormatter
from bokeh.plotting import figure
from bokeh.layouts import column
from bokeh.io import curdoc
import pandas

plot = figure(
    plot_height=800,
    plot_width=1024,
    title="Overview",
    toolbar_location="right",
    tools="box_zoom,pan,reset,save,wheel_zoom",
    y_range=[0.0, 1.0],
    x_axis_type='datetime')
plot.xaxis.axis_label = "Time"
plot.xaxis.axis_label_text_font_size = "14pt"
plot.yaxis.axis_label = "Value"
plot.yaxis.axis_label_text_font_size = "14pt"
plot.xaxis.formatter = DatetimeTickFormatter(
    microseconds=['%T:%3Nms'],
    milliseconds=['%T:%3Nms'],
    seconds=["%T"],
    minutes=["%T"],
    hours=["%T"])
source = ColumnDataSource(data=dict(
            time=[],
            value=[]
        ))
plot.circle(
    x="time",
    y='value',
    source=source,
    line_width=3,
    line_alpha=0.6,
    color="#000000",
    fill_alpha=0.2
)

data = dict()
data["time"] = [time.time()]
data["value"] = [numpy.random.random()]
total_data = pandas.DataFrame.from_dict(data)


def update_plot():
    global total_data
    data = dict()
    data["time"] = [time.time()]
    data["value"] = [numpy.random.random()]
    total_data = total_data.append(pandas.DataFrame.from_dict(data), ignore_index=True)
    print(total_data)
    source.data=dict(
        time=total_data["time"],
        value=total_data["value"]
    )

curdoc().add_root(column(plot))
curdoc().add_periodic_callback(update_plot, 500)
```

**Comment by HyETBV** [comment]
and i noticed, when i zoom out to the year level, that the year is 1970, januari, so it seems that is has a problem with scientific notation of large numbers. pandas changes the timestamp to a scientific number. when you print it, it is the same, but when you look at the whole dataframe, it is on scientific notation. could this be the problem?

**Comment by bryevdv** [comment]
@HyETBV Bokeh denotes timestamps as "Millseconds since epoch". But `time.time` returns *seconds` since epoch. (Pandas uses nanoseconds) Bokeh can automatically convert a variety of datetime formats automatically to the right value.s But if you want to work with floating point timestamps directly, you will have to make sure they are are milliseconds since epoch (it's just a raw number, Bokeh has no way of knowing if it is correct or not). I.e. for your code, use:
```
data["time"] = [time.time()*1000]  # convert to MS since epoch
```

**Comment by HyETBV** [comment]
thank you!!! i wouldn't be able to figure this out without your help! thank you
