### ISSUE TITLE
Bokeh renders a blank page

### ISSUE THREAD

**Issue by mxmaslin** [bokeh/bokeh#7593]
The code can be found here - http://bokeh.pydata.org/en/latest/docs/user_guide/quickstart.html#userguide-quickstart
Each code example is not working.
![screen shot 2018-03-04 at 14 50 06](https://user-images.githubusercontent.com/5699809/36945202-bf0494b0-1fbb-11e8-91ae-5bed9e49e2f0.png)
![screen shot 2018-03-04 at 14 51 45](https://user-images.githubusercontent.com/5699809/36945203-c1b2a5b2-1fbb-11e8-9800-ce120eb330ff.png)

**Comment by bryevdv** [comment]
None of the code on the page you linked is for a Bokeh server applications. Those are all just plain python scripts, e.g. to be run `python plot.py`. Bokeh server is only necessary if you want to hook plots up to real python callbacks. See https://bokeh.pydata.org/en/latest/docs/user_guide/server.html
