### ISSUE TITLE
Bug: DataTable View doesn't rerender on table.source.change.emit()

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#7597]
DataTable View doesn't rerender on table.source.change.emit()

Is currently:
```
this.connect(this.model.source.properties.data.change, () => this.updateGrid());
```

Should be:
```
this.connect(this.model.source.change, () => this.updateGrid());
```

Warning - I hand-modified the BokehJS source and making this change appeared to dramatically hurt render performance. I would take care to check that this problem isn't introduced by a PR.

To reproduce (the right table should updated after a selection on the left-side plot:

```
from random import random

from bokeh.layouts import row
from bokeh.models import CustomJS, ColumnDataSource
from bokeh.plotting import figure, output_file, show
from bokeh.models.widgets import DataTable, TableColumn

output_file("test.html")

x = [random() for x in range(500)]
y = [random() for y in range(500)]

s1 = ColumnDataSource(data=dict(x=x, y=y))
p1 = figure(plot_width=400, plot_height=400, tools="lasso_select, box_select", title="Select Here")
p1.circle('x', 'y', source=s1, alpha=0.6)

s2 = ColumnDataSource(data=dict(x=[], y=[]))
p2 = figure(plot_width=400, plot_height=400, x_range=(0, 1), y_range=(0, 1),
tools="", title="Watch Here")
p2.circle('x', 'y', source=s2, alpha=0.6)

columns = [TableColumn(field="x", title="X"),
TableColumn(field="y", title="Y"), ]
dt = DataTable(source=s2, width=400, height=280, columns=columns)

s1.callback = CustomJS(args=dict(s2=s2), code="""
var inds = cb_obj.selected['1d'].indices;
var d1 = cb_obj.data;
var d2 = s2.data;
d2['x'] = []
d2['y'] = []
for (i = 0; i < inds.length; i++) {
d2['x'].push(d1['x'][inds[i]])
d2['y'].push(d1['y'][inds[i]])
}
# s2.properties.data.change.emit(); # causes table update
s2.change.emit(); # doesn't update table
""")

layout = row(p1, p2, dt)

show(layout)
```

**Comment by bryevdv** [comment]
> Warning - I hand-modified the BokehJS source and making this change appeared to dramatically hurt render performance. I would take care to check that this problem isn't introduced by a PR.

@canavandl can you clarify this statement? I'm not sure if you mean the change should or should not be made.

**Comment by bryevdv** [comment]
This would seem to be a cause of #7745 I am not sure if it has always been this way, or if it was changed at some point. I think the issue is that non-`.data` updates to sources should either not update the table, or use some different code path. Since this only affects a CustomJS use, and only a subset of that I think I wonder if we ought to just keep it the way it is. (We can always do what we need internally)

**Comment by bryevdv** [comment]
But, maybe this would work now since selection is a model:

```
this.connect(this.model.source.selection.change, () => this.updateSelection())
this.connect(this.model.source.change, () => this.updateGrid())
```

**Comment by bryevdv** [comment]
Well, that does not work as-is because `this.source` is actually ` ColumnarDataSource`:
```
src/lib/models/widgets/tables/data_table.ts(124,36): error TS2551: Property 'selection' does not exist on type 'ColumnarDataSource'. Did you mean 'select_one'?
```
