### ISSUE TITLE
Global alpha for image_rgba plot

### ISSUE THREAD

**Issue by marcuskd** [bokeh/bokeh#7600]
It's currently not possible to set a global alpha for image_rgba plots. 

Example code:

```
import numpy as np
from bokeh.plotting import figure, show, output_file

N = 20
img = np.empty((N, N), dtype=np.uint32)
view = img.view(dtype=np.uint8).reshape((N, N, 4))
for i in range(N):
    for j in range(N):
        view[i, j, 0] = int(i/N*255)
        view[i, j, 1] = 158
        view[i, j, 2] = int(j/N*255)
        view[i, j, 3] = 255

p = figure(x_range=(0, 10), y_range=(0, 10))

# Solid line to show effect of alpha...
p.line([0, 10], [10, 0], color='red', line_width=2)
# Attempt to set global alpha of 0.5...
p.image_rgba(image=[img], x=0, y=0, dw=10, dh=10, alpha=0.5)

show(p)
```

The red line from top left to bottom right is not visible behind the image.

Software versions...
Bokeh 0.12.14
Python 3.6.4
Firefox 58.0.2 (64-bit)
Ubuntu MATE 16.04.4 LTS

NB: I'm working on a solution following conclusion of PR#7570.

**Comment by bryevdv** [comment]
Thanks @marcuskd !

**Comment by philippjfr** [comment]
I'm really excited about this, just a quick question for clarification. How does the global alpha interact with an alpha channel on an RGBA? Will it just multiple it by the global alpha?

**Comment by marcuskd** [comment]
Yes, that's what it should do. I've included an example which demonstrates this.
