### ISSUE TITLE
bokeh should not instance its loggers using: logging.getLogger(__file__)

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#7602]
bokeh (0.12.4) is using the following call to instantiate some of its loggers:
`logger = logging.getLogger(__file__)` 

See bokeh/Document.py@line 20 for an example. 

Such loggers are impossible to control, in terms of logging level, cause their name is based on the path in which bokeh is installed - i.e. generically speaking, accessing such a logger is almost impossible. 

```
import logging
logging.Logger.manager.loggerDict
```

```
'/home/informatique/ica/leclercq/anaconda/lib/python2.7/site-packages/bokeh/core/validation/check': <logging.PlaceHolder at 0x7f5b5dfc6590>,
'/home/informatique/ica/leclercq/anaconda/lib/python2.7/site-packages/bokeh/core/validation/check.pyc': <logging.Logger at 0x7f5b5dfc64d0>,
'/home/informatique/ica/leclercq/anaconda/lib/python2.7/site-packages/bokeh/document/document': <logging.PlaceHolder at 0x7f5b5dfc6350>,
'/home/informatique/ica/leclercq/anaconda/lib/python2.7/site-packages/bokeh/document/document.pyc': <logging.Logger at 0x7f5b5dfc6290>,
'/home/informatique/ica/leclercq/anaconda/lib/python2.7/site-packages/bokeh/events': <logging.PlaceHolder at 0x7f5b5df98cd0>,
'/home/informatique/ica/leclercq/anaconda/lib/python2.7/site-packages/bokeh/events.pyc': <logging.Logger at 0x7f5b5df98c10>,
'/home/informatique/ica/leclercq/anaconda/lib/python2.7/site-packages/bokeh/model': <logging.PlaceHolder at 0x7f5b6335f0d0>,
'/home/informatique/ica/leclercq/anaconda/lib/python2.7/site-packages/bokeh/model.pyc': <logging.Logger at 0x7f5b633a2dd0>,
```

We consequently see warnings in the notebook cells that could be safely ignored - e.g.:
`DEBUG: Deleting 0 modules for <bokek.document.document.Document object at 0x......>`

IHMO, in the provided example, the name of the logger should be `bokeh.document`.

**Comment by bryevdv** [comment]
They should all be `logging.getLogger(__name__)`. If you could make a PR to update any errant log inits that are not like that, it would be very appreciated.

**Comment by nleclercq** [comment]
done #7603
