### ISSUE TITLE
cb_obj.get / _pymeth_get.call issue

### ISSUE THREAD

**Issue by limorgu** [bokeh/bokeh#7606]
Dear bokeh community,

Thanks again for all the great work on this library, it's awesome. 

I wrote some code with it two-three months ago and tried to rerun it today for different data (its purpose is to create an interactive map with a slider that can also play an animation by pressing an external button). I encountered some surprising issues. 

Currently, neither the slider nor the button work. It is due to errors in callback/CustomJS.from_py_func functionality. Here's the error I see on the browser side:

>  Uncaught TypeError: Cannot read property 'apply' of undefined
>     at e._pymeth_get (eval at n._make_func (bokeh-0.12.13.min.js:1), <anonymous>:5:54)
>     at cb (eval at n._make_func (bokeh-0.12.13.min.js:1), <anonymous>:21:21)
>     at eval (eval at n._make_func (bokeh-0.12.13.min.js:1), <anonymous>:29:1)
>     at n.execute (bokeh-0.12.13.min.js:1)
>     at e.<anonymous> (bokeh-0.12.13.min.js:1)
>     at t.emit (bokeh-0.12.13.min.js:1)
>     at e._setv (bokeh-0.12.13.min.js:1)
>     at e.setv (bokeh-0.12.13.min.js:1)
>     at e.set [as value] (bokeh-0.12.13.min.js:1)
>     at e._slide (bokeh-widgets-0.12.13.min.js:1)

And here's my code that probably caused it:
```


def update(p=p,source=europe_source, slider=years, window=None):
        data=source.data
         print("here", data["level"])
         v = cb_obj.get("value")
         print("here", v)
         data["level"] = [x for x in data[v]]
         data["levelb"] = [x for x in data[str(v)+"b"]]
         p.title.text = "SocDems in Europe, " + v
         source.trigger("change")

    years.js_on_change("value", CustomJS.from_py_func(update))
    output_file("euro_inter.html")

  callback = CustomJS(args=dict(p=p, source=europe_source, years=years), code="""
        
        var data = source.data;
        var f = cb_obj.active;
        var j = 1999;

        if(f == true){
            mytimer = setInterval(replace_data, 500);             
        } else {
            clearInterval(mytimer);
        }

        function replace_data() {
             if (j==2017) return;
             j++;
             if(data[j] === undefined) {
                 j=1999;
             }
      
             data['level'] = data[j];
             data['levelb'] = data[j+'b'];
             years.value = j;
             CustomJS.from_py_func(update);
             source.change.emit();
        }
        """)
```

As you can see, using print statements and other hints I managed to narrow down the problem to this line: `v = cb_obj.get('value')`, which gets translated to javascript as `v = _pymeth_get.call(cb_obj, "value");` and raises this issue in 

```
var _pymeth_get = function (key, d) { // nargs: 1 2

    ####if (this.constructor !== Object) return this.get.apply(this, arguments);####

    if (this[key] !== undefined) {return this[key];}

    else if (d !== undefined) {return d;}

    else {return null;}
};
```

It causes the same problem with bokeh 0.12.13 and 0.12.14. When I try to downgrade to previous versions other things break strangely. 

Anyone seen this before or have an idea of what I'm up against? This code worked many times before and I was quite sad to see it doesn't anymore. I would much appreciate any insight/idea. 

Thanks,
Limor

**Comment by bryevdv** [comment]
`obj.get('foo')` was a very old syntax that was deprecated and support for it was eventually removed at some point. You should just use standard (and much simpler) attribute access, i.e. `obj.foo`

**Comment by limorgu** [comment]
Thanks so much for quick response. Problem solved :)
