### ISSUE TITLE
Feature Request: make bokeh work with the brave browser

### ISSUE THREAD

**Issue by ea42gh** [bokeh/bokeh#7616]
brave browser `https://www.brave.com`

* simple scatter plots are truncated to the viewport, (axes labels and titles are outside the viewing area)
* the bokeh save tool results in an html file rather than png,

**Comment by bryevdv** [comment]
The first at least sounds like a usage error: Unless a reactive sizing mode is explicitly chose, plots are drawn in the size given, regardless of viewport size.

Not sure about he second, but the core team definitely does not have the resources to look into a niche browser. We can barely keep up with major browsers. Happy to consider a PR but closing this for now until a PR shows up.
