### ISSUE TITLE
`save` creates non-working files when used with widgets

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7621]
Bokeh v0.12.15dev2

```python
from bokeh.document import Document
from bokeh.models import Button
from bokeh.plotting import figure, save, output_file

fig = figure()
fig.x([0], [0])

button = Button(label="Button")

d = Document()
d.add_root(fig)
d.add_root(button)

output_file('fig.html')
save(fig)
```

Now, if you open `fig.html` in your browser, you should see `Uncaught Error: Model 'Button' does not exist.`

The reason is that `bokeh.embed.bundle.bundle_for_objs_and_resources` checks just the passed models for widgets (`fig` in this case), but `bokeh.embed.util.standalone_docs_json_and_render_items` saves the whole document JSON.

It's hard for me to say how it should work ideally. Most likely, there should be some common function used by `save` that extracts only relevant models from a document, and only those models are checked for widgets and bundled as a JSON.

**Comment by bryevdv** [comment]
@p-himik What is the use case for ever doing this? I'm more inclined to just stipulate that this sort of thing is undefined and unsupported, unless there is a compelling motivation.

**Comment by mattpap** [comment]
I would argue this is a bug, because even if `save()` is called with a particular root, there may be some code (e.g. CustomJS) referencing other roots, so it should be saving entire document with all its dependencies.

**Comment by mattpap** [comment]
In fact if you replace widgets with (still not implemented) namespaces, then this makes even more sense.

**Comment by p-himik** [comment]
@bryevdv At the very least, current behavior prevents code like this from running correctly: https://gist.github.com/AzraelDD/c4573f531fbc52cf5d0811d81d30a3fa
I'd say that if you have a bunch of widgets, then exporting as PNG only a figure or a set of figures, without the widgets, is an understandable desire.

**Comment by bryevdv** [comment]
OK, that makes sense.

**Comment by bryevdv** [comment]
> Most likely, there should be some common function used by save that extracts only relevant models from a document, and only those models are checked for widgets and bundled as a JSON.

In the short term at least, it seems much safer to go the other direction. This tiny diff solves the problem by always bundling the entire document:

```
index 7f6e76308..fc4c31b78 100644
--- a/bokeh/embed/standalone.py
+++ b/bokeh/embed/standalone.py
@@ -275,10 +275,10 @@ def file_html(models,
     '''
     models = check_models_or_docs(models)

-    with _ModelInDocument(models, apply_theme=theme):
+    with _ModelInDocument(models, apply_theme=theme) as doc:
         (docs_json, render_items) = standalone_docs_json_and_render_items(models)
         title = _title_from_models(models, title)
-        bundle = bundle_for_objs_and_resources(models, resources)
+        bundle = bundle_for_objs_and_resources([doc], resources)
         return html_page_for_render_items(bundle, docs_json, render_items, title=title,
                                            template=template, template_variables=template_variables)
```

I agree that could probably be improved but I think I'd rather make a small safe change now, even if it is not the most efficient solution, and leave a more sophisticated change for later work. Thoughts @p-himik @mattpap ?

**Comment by mattpap** [comment]
I would argue that this is the right solution. In fact, I've been battling with `models` vs `doc` dichotomy in templates PR (#7708) and the best solution so far is to always work with complete documents and use `models` for templating purpose only.

**Comment by bryevdv** [comment]
@mattpap OK, should I make this small PR or wait for you to finish?

**Comment by bryevdv** [comment]
for testing, with this change, the following in app exports work:
```
# -*- coding: utf-8 -*-
'''
After the layout has been added to the root, exporting the png of a fig is
not possible anymore
With "bokeh serve export_test.py", the console output for me is the following:
doc_layout works
fig works
Layout is added to root
doc_layout works
fig throws error
'''
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from bokeh.layouts import layout, widgetbox
from bokeh.io import export_png
from bokeh.models.widgets import Button


def download():
    try:
        export_png(doc_layout, filename="export doc_layout.png")
        print('doc_layout works')
    except Exception as ex:
        print('doc_layout throws error:', ex)
    try:
        export_png(fig, filename="export fig.png")
        print('fig works')
    except Exception as ex:
        print('fig throws error:', ex)


source = ColumnDataSource({'x': [2, 3, 4], 'y': [0.5, 1.5, 2.5]})
fig = figure(plot_width=1000, plot_height=300)
fig.hbar(y='y', right='x', height=0.4, source=source)

button = Button(label="Download")
button.on_click(download)
doc_layout = layout([[widgetbox(button)], [fig]], sizing_mode='fixed')

#download()  # Test 1

print('Layout is added to root')
curdoc().add_root(doc_layout)
curdoc().title = "Export PNG test"

#download()  # Test 2
```
despite a spurious warning:
```
2018-04-23 14:08:25,065 The webdriver raised a TimeoutException while waiting for                      a 'bokeh:idle' event to signify that the layout has rendered.                      Something may have gone wrong.
```

**Comment by mattpap** [comment]
>  OK, should I make this small PR or wait for you to finish?

I will finish this as this intersects with other changes.

**Comment by bryevdv** [comment]
@mattpap is this fixed in the templates PR? A fix for this should go in this week, even if we have to punt on templates this release.

**Comment by mattpap** [comment]
@bryevdv, no, if you want, go ahead with the proposed change. In fact, it should have been done separately anyway.

**Comment by bryevdv** [comment]
OK I will push a PR later today

**Comment by AzraelDD** [comment]
Sorry for opening this up again, I can create another issue if you want to... but for me the example code (that seems to be supposed to work now) does not work.

Here is the code, once more (GitHub preview shows the code without line breaks... hope that is fixed in the actual post)

```python
# -*- coding: utf-8 -*-
'''
After the layout has been added to the root, exporting the png of a fig is
not possible anymore
With "bokeh serve export_test.py", the console output for me is the following:
doc_layout works
fig works
Layout is added to root
doc_layout works
fig throws error
'''
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from bokeh.layouts import layout, widgetbox
from bokeh.io import export_png
from bokeh.models.widgets import Button


def download():
    try:
        export_png(doc_layout, filename="export doc_layout.png")
        print('doc_layout works')
    except Exception as ex:
        print('doc_layout throws error:', ex)
    try:
        export_png(fig, filename="export fig.png")
        print('fig works')
    except Exception as ex:
        print('fig throws error:', ex)


source = ColumnDataSource({'x': [2, 3, 4], 'y': [0.5, 1.5, 2.5]})
fig = figure(plot_width=1000, plot_height=300)
fig.hbar(y='y', right='x', height=0.4, source=source)

button = Button(label="Download")
button.on_click(download)
doc_layout = layout([[widgetbox(button)], [fig]], sizing_mode='fixed')

#download()  # Test 1

print('Layout is added to root')
curdoc().add_root(doc_layout)
curdoc().title = "Export PNG test"

#download()  # Test 2
```

I start the server with `bokeh serve export_test.py`. After I click the Download button, the following output is generated:

```You are generating standalone HTML/JS output, but trying to use real Python
callbacks (i.e. with on_change or on_event). This combination cannot work.

Only JavaScript callbacks may be used with standalone output. For more
information on JavaScript callbacks with Bokeh, see:

    http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html

Alternatively, to use real Python callbacks, a Bokeh server application may
be used. For more information on building and running Bokeh applications, see:

    http://bokeh.pydata.org/en/latest/docs/user_guide/server.html

doc_layout works
fig throws error: Message: {"errorMessage":"undefined is not an object (evaluating 'document.getElementsByClassName('bk-root')[0].children[0].getBoundingClientRect')","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"171","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:62171","User-Agent":"selenium/3.12.0 (python linux)"},"httpVersion":"1.1","method":"POST","post":"{\"script\": \"\\nreturn document.getElementsByClassName('bk-root')[0].children[0].getBoundingClientRect()\\n\", \"args\": [], \"sessionId\": \"5f2d8590-7620-11e8-94ca-bf888776a2b5\"}","url":"/execute","urlParsed":{"anchor":"","query":"","file":"execute","directory":"/","path":"/execute","relative":"/execute","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute","queryKey":{},"chunks":["execute"]},"urlOriginal":"/session/5f2d8590-7620-11e8-94ca-bf888776a2b5/execute"}}
Screenshot: available via screen
```
First, I have no clue where the standalone HTML warning is coming from, despite having used Bokeh for quite a while now. But that is not the main problem now. I still cannot save the png of a figure, once it has been included in a layout and added to root. If I comment out the line with "download()  # Test 1", the correct png is generated.
Am I doing someting wrong? Or did I misunderstand what was actually fixed?

**Comment by bryevdv** [comment]
> I have no clue where the standalone HTML warning is coming from, despite having used Bokeh for quite a while now.

It's a completely new error message. It's an attempt to get immediate feedback to users who e.g, try to use `on_change` with`output_file` (which won't work), because I have had to explain why that cannot work more times than I can count at this point, and and exhausted answering the same question again and again. Unfortunately, one of the hardest issues in a large piece of composable software is managing combinatorial complexity. You've discovered an unforseen interaction in a combination of use that just wasn't considered when this well-meaning error message was added, namely that `export_png` basically has to make a standalone version of the document just to make a screenshot, even if you are doing it from inside a real bokeh app. This is a new issue that will have to be resolved, please open a new GitHub issue with this information so we can track it cleanly.
