### ISSUE TITLE
IPython notebook interface is stateful and buggy

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#763]
Subsequent bokeh plots update previous plots in unexpected ways.   Starting with the rects ipython notebook, I executed a cell that looked like this
```
p = rect(x, y, 4, 2, 
     width_units="screen", height_units="screen", 
     color="#ff0000")
show()
```
The plot looked like this
![image](https://cloud.githubusercontent.com/assets/40453/3471870/78d66420-02c6-11e4-9a49-3e8c81ffef23.png)

Next I executed this cell
```p.line([2,4,6],[-1,0.5, 1])
show()```
That updated the existing plot, which is expected because of ```p.line```.
![image](https://cloud.githubusercontent.com/assets/40453/3471895/be4599d6-02c6-11e4-9394-85c2ae2343c8.png)

Next I executed this cell
```
# variable width and height
rect(
    x, y, 0.01*np.exp(1+0.1*x), 0.2*abs(np.cos(x)),
    fill_color="green", line_color=None, fill_alpha=0.6
)
show()
```
That didn't update the first two plots, and drew the expected green sine wave.
Next I executed
```
# angle
rect(x, y, 0.05, 0.1, color="#4444aa", angle=-np.pi/6)
show()
```
That produced a blue angled sine wave.

Then I went back and executed
```
p.line([2,4,6],[-1,0.5, 1])
show()
```
This resulted in a blue sine wave which was completely unexpected.  

I think there are a couple of bugs with the bokeh ipython interface like this.  Try using it in anger for a while, go back and tweak previous cells.  I have gotten bokeh into a state where no matter what I changed about a rect call, the same plot was emitted.  I had to clear all output, save, then reload the notebook and re-execute each cell.

**Comment by bryevdv** [comment]
This is being incrementally fixed with the ongoing removal of global state from `plotting.py` so I am going to close this. The change to `figure()` to return `Plot`s and the upcoming removal of deprecations in 0.8 already go a long way. Re-open if there are new issues to discuss.
