### ISSUE TITLE
Signal peaking on zoom-out

### ISSUE THREAD

**Issue by platise** [bokeh/bokeh#7632]
According to this example:
- http://isotel.net/slides/Plot-HighPeaks.slides.html

The (numpy.min(r[mdu.ch_idx(3)]), numpy.max(r[mdu.ch_idx(3)]) ) for ch3 (blue) is: (-4136, -4123)

When zooming out, unreal very high peaking (peak-to-peak values) of the signal occurs. As seen on picture below signal amplitude exceeds 100 peak-to-peak instead of only 13 from the min/max. 

I would have expected the chart to condense peaks only and not to enlarge them.

Running bokeh 0.12.14 from jupyter-labs 0.31.12 on firefox@linux 58.0.2.

Zoom-in, showing a correct amplitude:

![screenshot from 2018-03-15 05-58-47](https://user-images.githubusercontent.com/7982797/37445093-01b99f78-2816-11e8-9b37-af6566ef24f9.png)

Zoom-out with incorrect amplitude:

![screenshot from 2018-03-15 05-53-09](https://user-images.githubusercontent.com/7982797/37445074-d03d4e18-2815-11e8-83e0-a4b8d85614f2.png)

**Comment by bryevdv** [comment]
I can't reproduce the drawing issue:

<img width="930" alt="screen shot 2018-03-15 at 08 09 30" src="https://user-images.githubusercontent.com/1078448/37472059-60592488-2828-11e8-9062-d14258d5040e.png">

However, something about the Rise (?) slide embedding is playing havoc with interactive tools, the plot is getting wrong window coordinates. Can you confirm whether any problems occur outside slides or not (i.e. a real notebook or output files) Additionally can you describe m ore exactly how you get to zoomed image you have? or better, provide a screencast?

**Comment by platise** [comment]
Same scenario with `output_file`

    r = mdu.acquire(N=10000)

    plot = figure(title='Voltage Input', x_axis_label="[s]", y_axis_label='[LSB]', 
              plot_width=750, plot_height=400, background_fill_color='darkgray', 
              border_fill_color='lightgray')

    plot.line(r[0], r[mdu.ch_idx(3)], line_width=3, color='blue', legend='ch3')
    plot.line(r[0], r[mdu.ch_idx(7)], line_width=3, color='green', legend='ch5')
    output_file("test.html")
    show(plot)

[output2file-peaking1.html.gz](https://github.com/bokeh/bokeh/files/1816140/output2file-peaking1.html.gz)

To reproduce: use the 3rd tool (mouse wheel, from the top to change scale), and then wheel on X axis only, so that only X axis scales. Scale in/out and you should see it.

**Comment by bryevdv** [comment]
> The starting screen, already shows a bit high amplitude:

FYI the line width is 3 and it is quite zoomed out, the width of the line itself is going contribute to discrepancies when zoomed far out. 

Doe this happen only when zooming one axis? or does it happen with box zoom or with wheel zoom?

**Comment by bryevdv** [comment]
I still can't reproduce any problems, even with the HTML file you linked:

<img width="827" alt="screen shot 2018-03-15 at 09 51 15" src="https://user-images.githubusercontent.com/1078448/37478062-81004f14-2836-11e8-9926-e6fa9e76400a.png">

<img width="778" alt="screen shot 2018-03-15 at 09 51 36" src="https://user-images.githubusercontent.com/1078448/37478074-8427c172-2836-11e8-86c7-473c6a777349.png">

**Comment by bryevdv** [comment]
@mattpap I don't have a linux VM available, can you try out the links above on linux/FF?

**Comment by bryevdv** [comment]
OK I was thinking about it backwards, here is a demonstration, there is a discrete jump in vertical size while zooming out:

![screenflow](https://user-images.githubusercontent.com/1078448/37484180-0e2b33be-2845-11e8-8663-ca9477d0e169.gif)

**Comment by platise** [comment]
Great ;)

**Comment by bryevdv** [comment]
how many points is this? Can you provide a minimal script to reproduce?

**Comment by bryevdv** [comment]
I will say ahead of time that in my experience all canvas implementations have various failure modes, and densely overlapping lines is one I know has cropped up as causing problems in some cases. If that is the case here then we will not be able to do anything, except advise to render using something like data shader which provides more control over rasterization at the python level.

**Comment by platise** [comment]
Here it is 100 points per channel only. Just condense (zoom-out X) and you will see it getting bigger.

[output2file-peaking2.html.gz](https://github.com/bokeh/bokeh/files/1816683/output2file-peaking2.html.gz)

**Comment by platise** [comment]
It could be rounding in scaling issue (assumption), maybe the order of Y value calculation could/should be changed to work-around.

**Comment by bryevdv** [comment]
@platise thanks for the file, more than anything else, a complete script to reproduce is what will be valuable, because that is what is necessary to experiment. 

For instance. when I zoom that out, it eventually flattens out to the line width. The  line is never going to be thinner than the line width you specify. line width 3 is actually quite thick. Do you see similar results with thinner widths? That's the sort of thing we could try ourselves with code to run.

**Comment by bryevdv** [comment]
Which isn't to say that there isn't some bug as well, but again that will require more investigation to determine.

**Comment by platise** [comment]
With line width=1 it is OK so it is related ti the line width > 1, already at 2 issues comes out:

[output2file-peaking3.html.gz](https://github.com/bokeh/bokeh/files/1817905/output2file-peaking3.html.gz)

I am sampling real data from a hardware (one channel is 50 Hz noise and the other is more or less short-cut). Resulting samples are in `r` is then the input of the chart. So one way is to copy the embedded data vector from the html and re-plot.

**A hint on condensing**

Assuming a set `S` of `(x,y)` points and zoom-out ratio at which subsequent points `(x1,y1)` and `(x2,y2)` fall into the same x-point on the screen, so `x1 == x2`, then connecting lines of the plot converts into the vertical lines. 

Assuming a very large data set, i.e. above the first example has 10k points, but it could have also 100k points or more, plotting individual points, lines between them, becomes meaningless, and rather a set `S` is translated into a new condensed set `Sd` in which:
- for all points that share the same `x` on the screen a new line at point `x` is a vertical line between min() and max() values of the points from set `S` that share the same `x` on the screen
- min/max presentation will give a user a clear view of possible peaks even when zooming far out, but to make a plot more interesting, another brighter line could be drawn over it, with y2 - y1 = specified line width, and center value as average of the points condensed at `x`
- above case can be further extended to more gradients the next level showing standard deviation sigma=1, then sigma=3, so a total plot would have (starting from darker color): peak-to-peak lines, sigma=3, sigma=1, and final average point with height of specified line width

Long ago I applied such concept to one of my plotter and result is nice:

![sgscope](https://user-images.githubusercontent.com/7982797/37503939-a7be45d4-28db-11e8-8d6e-bf94718b7cd1.png)

**Comment by bryevdv** [comment]
@platise I'd be happy to discuss further, but at this point it's more of a support question and per the project process, I'll request it move to the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
