### ISSUE TITLE
Color scatter example in Gallery shows nothing in browser

### ISSUE THREAD

**Issue by secsilm** [bokeh/bokeh#7633]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
 
- Python: `Python 3.6.4 :: Anaconda custom (64-bit)`
- bokeh: `0.12.14`
- OS: Windows 10
- Chrome: `64.0.3282.186`

#### Description of expected behavior and the observed behavior

I run the [Color scatter example in Gallery](https://bokeh.pydata.org/en/latest/docs/gallery/color_scatter.html) and the html file is generated. But It shows nothing in my chrome.

#### Complete, minimal, self-contained example code that reproduces the issue

The code is same as the example.

```python
import numpy as np

from bokeh.plotting import figure, show, output_file

N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = [
    "#%02x%02x%02x" % (int(r), int(g), 150) for r, g in zip(50+2*x, 30+2*y)
]

TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"

p = figure(tools=TOOLS)

p.scatter(x, y, radius=radii,
          fill_color=colors, fill_alpha=0.6,
          line_color=None)

output_file("color_scatter.html", title="color_scatter.py example")

show(p)  # open a browser
```

#### Stack traceback and/or browser JavaScript console output

Chrome console output:

```
Uncaught Error: Model 'Slider' does not exist. This could be due to a widget
                     or a custom model not being registered before first usage.
    at Object.i.Models (bokeh-0.12.14.min.js:1)
    at Function.t._instantiate_object (bokeh-0.12.14.min.js:1)
    at Function.t._instantiate_references_json (bokeh-0.12.14.min.js:1)
    at Function.t.from_json (bokeh-0.12.14.min.js:1)
    at bokeh-0.12.14.min.js:1
    at bokeh-0.12.14.min.js:1
```

![](https://i.imgur.com/TqNhghY.png)

#### Screenshots or screencasts of the bug in action

It shows nothing.

![](https://i.imgur.com/ohE3hKP.png)

[Here](https://gist.github.com/secsilm/d6e6c0458614c477f47293ccda54532e) is the generated html file.

**Comment by bryevdv** [comment]
I expect this must be a dupe of https://github.com/bokeh/bokeh/issues/7621 somehow. Are you running in a Jupyter notebook by chance?

**Comment by secsilm** [comment]
@bryevdv Nope, I run the code in windows cmd terminal. I also tried running this in a Jupyter notebook, but it didn't work, same error.

**Comment by bryevdv** [comment]
@secsilm I am not really sure. I can say with 100% confidence that this is something weird specific to your situation. I cannot reproduce any issues on windows or OSX, additionally the code in the docs is the same code used to generate all the accompanying plots in the docs build process. Can you possibly try things on a different machine or OS just fo comparison?

**Comment by bryevdv** [comment]
@secsilm additionally can you put the HTML output file you get in a gist or other accessible link

**Comment by secsilm** [comment]
@bryevdv OK, I will try this code in another machine. I have put the HTML file in a gist. [Here](https://gist.github.com/secsilm/d6e6c0458614c477f47293ccda54532e) it is.

**Comment by bryevdv** [comment]
@secsilm There is lots of stuff in the gist output that could not have possibly come from the code you have in the OP (or the corresponding code in the docs).  

There is a hover tool with that has fields like "Unemployment Rate" and (Long, Lat)" configured that are nowhere in the code at all:

> {"attributes":{"callback":null,"point_policy":"follow_mouse","tooltips":[["Name","@name"],["Unemployment rate)","@rate%"],["(Long, Lat)","($x, $y)"]]},"id":"c18218c0-eaf8-45b3-8f3e-9117fa541931","type":"HoverTool"}

There are also several Sliders and CustomJS callbacks that could not possibly come from that code. The CustomJS has this code:

> "\n    var data = source.data;\n    var A = amp.value;\n    var k = freq.value;\n    var phi = phase.value;\n    var B = offset.value;\n    x = data['x']\n    y = data['y']\n    for (i = 0; i &lt; x.length; i++) {\n        y[i] = B + A*Math.sin(k*x[i]+phi);\n    }\n    source.change.emit();\n"

This looks suspiciously like the code for the *sliders* example, not the colormapped circles code. I am not sure what the mixup could be. Does this file already exist? What if you change to a new filename that you are certain does not exist?

**Comment by bryevdv** [comment]
There's also a data source with this data:

> "data":{"name":["Anderson","Andrews","Angelina","Aransas","Archer","Armstrong","Atascosa","Austin","Bailey","Bandera","Bastrop","Baylor","Bee","Bell","Bexar","Blanco","Borden","Bosque","Bowie","Brazoria","Brazos","Brewster","Briscoe","Brooks","Brown","Burleson","Burnet","Caldwell","Calhoun","Callahan","Cameron","Camp","Carson","Cass","Castro","Chambers","Cherokee","Childress","Clay","Cochran","Coke","Coleman","Collin","Collingsworth","Colorado","Comal","Comanche","Concho","Cooke","Coryell","Cottle","Crane","Crockett","Crosby","Culberson","Dallam","Dallas","Dawson","DeWitt","Deaf Smith","Delta","Denton","Dickens","Dimmit","Donley","Duval","Eastland","Ector","Edwards","Ellis","El Paso","Erath","Falls","Fannin","Fayette","Fisher","Floyd","Foard","Fort Bend","Franklin","Freestone","Frio","Gaines","Galveston","Garza","Gillespie","Glasscock","Goliad","Gonzales","Gray","Grayson","Gregg","Grimes","Guadalupe","Hale","Hall","Hamilton","Hansford","Hardeman","Hardin","Harris","Harrison","Hartley","Haskell","Hays","Hemphill","Henderson","Hidalgo","Hill","Hockley","Hood","Hopkins","Houston","Howard","Hudspeth","Hunt","Hutchinson","Irion","Jack","Jackson","Jasper","Jeff Davis","Jefferson","Jim Hogg","Jim Wells","Johnson","Jones","Karnes","Kaufman","Kendall","Kenedy","Kent","Kerr","Kimble","King","Kinney","Kleberg","Knox","La Salle","Lamar","Lamb","Lampasas","Lavaca","Lee","Leon","Liberty","Limestone","Lipscomb","Live Oak","Llano","Loving","Lubbock","Lynn","McCulloch","McLennan","McMullen","Madison","Marion","Martin","Mason","Matagorda","Maverick","Medina","Menard","Midland","Milam","Mills","Mitchell","Montague","Montgomery","Moore","Morris","Motley","Nacogdoches","Navarro","Newton","Nolan","Nueces","Ochiltree","Oldham","Orange","Palo Pinto","Panola","Parker","Parmer","Pecos","Polk","Potter","Presidio","Rains","Randall","Reagan","Real","Red River","Reeves","Refugio","Roberts","Robertson","Rockwall","Runnels","Rusk","Sabine","San Augustine","San Jacinto","San Patricio","San Saba","Schleicher","Scurry","Shackelford","Shelby","Sherman","Smith","Somervell","Starr","Stephens","Sterling","Stonewall","Sutton","Swisher","Tarrant","Taylor","Terrell","Terry","Throckmorton","Titus","Tom Green","Travis","Trinity","Tyler","Upshur","Upton","Uvalde","Val Verde","Van Zandt","Victoria","Walker","Waller","Ward","Washington","Webb","Wharton","Wheeler","Wichita","Wilbarger","Willacy","Williamson","Wilson","Winkler","Wise","Wood","Yoakum","Young","Zapata","Zavala"]


Which again, is nowhere in the code you have provided, or in any of the example in the repository either. Can you describe more fully any other code you may have tried to run in relation to this script?

**Comment by bryevdv** [comment]
The long and the short of it is, you have output that seems to combine data and models from at least three different examples. Have never seen anything like this ever, so it will be necessary to know more exactly what steps you have followed.

**Comment by secsilm** [comment]
@bryevdv Thank you for your detailed explanation. I reruned the code in my computer and it finally worked! I guess the reason is that I runed several exzample code one by one in a single python process and didn't call `reset_output` between each(didn't konw that function before) yesterday. Thank you again.
