### ISSUE TITLE
sizing_mode='scale_width' makes plot 1 or 2 pixels too wide in notebook

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#7645]
![screenshot from 2018-03-17 15-58-15](https://user-images.githubusercontent.com/1796208/37559894-0ca65d58-29fc-11e8-9c1b-0cffcf903830.png)

Any plot with `sizing_mode='scale_width'` in jupyter notebook has a scroll bar underneath it.

Tested on:
* Firefox (Linux and OSX)
* Chrome (OSX)
* Safari (OSX)

It is the broken on 0.12.6, 0.12.7, 0.12.9 0.12.10, 0.12.14 and 0.12.15dev3

It is good on 0.12.5 

![screenshot from 2018-03-17 15-58-51](https://user-images.githubusercontent.com/1796208/37559901-28994cbe-29fc-11e8-909c-24216f468815.png)

The problem does not show up in nbviewer for me, only in live notebooks.

While briefly investigating, I did notice that test `test_scale_width_plot_starts_at_correct_size` had been marked with @pytest.mark.xfail between 0.12.5 and 0.12.6. - https://github.com/bokeh/bokeh/blob/master/tests/integration/interaction/test_sizing_mode.py#L106

**Comment by bryevdv** [comment]
Thanks for the nudge @birdsarah
