### ISSUE TITLE
allow custom formatter when using the hover tool

### ISSUE THREAD

**Issue by scaine1** [bokeh/bokeh#7647]
**Background**
The python library geoviews ([http://geoviews.org/](url)) uses bokeh as a backend when interactive plotting geographical data is required. 
Typically data on a latitude/longitude grid is converted to a Web Mercator projection and displayed using bokeh.

**The Issue**
When using the hover tool on data transformed in to Web Mercator format, the user is shown the transformed values for latitude/longitude rather than the original latitude/longitude values.
Attached is an image that shows this issue 

![geoviews_hover](https://user-images.githubusercontent.com/2906750/37561540-bba2b27c-2aa4-11e8-965f-a14b1b913ed6.png)

There have some discussions on how to solve this issue at https://github.com/ioam/geoviews/issues/100 and it seems the consensus would be that the nicest way to solve the problem would be if a custom formatter could be applied to the hover tool.
This would allow the Web Mercator transformed data could be transformed back to latitude/longitude values when displayed by the hover tool.

As this feature does not already exist I expect that it may be a niche issue relating to geoviews, however would adding a custom formatter to the hover tool be something you would be willing to consider?

**Comment by bryevdv** [comment]
@scaine1 I think my immediate preference would be to : 

* add a generic `CustomJSFormatter` that is similar to several other "CustomJS" type models elswhere in Bokeh.

* Add an example that demonstrates how to use it to format mercator values

* Holoviews and other high level tools can use it to provide "built in" support at that level

**Comment by scaine1** [comment]
sounds ideal to me!

**Comment by bryevdv** [comment]
@scaine1 Are you interested in working up this feature as a contribution? (Just asking, I could not tell if that's what you meant above by willing to consider)

**Comment by scaine1** [comment]
Unfortunately at this point I think it is beyond my abilities.
When I said  ".. willing to consider .." I meant would the bokeh team be willing to consider adding this feature for me and other geoviews users. Sorry for not being clear.
Having said that,  if you don't have anyone to work on it I could potentially dedicate some time over the next couple of months to learn how bokeh works and come up with a solution.

**Comment by bryevdv** [comment]
@scaine1 no worries I just wanted to clarify. I think this is useful enough that I will probably try to get to it sooner rather than later, but if you are looking to get involved with a project don't let that stop you, there's plenty of other issues :)
