### ISSUE TITLE
A varying type renderer

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#765]
Would it be possible to make a renderer that had an attribute of glyph type?
The glyph spec would look like this from JS.
```
{renderer:'varying',
 x:  [1, 2, 3, 4, 5],
 y:  [1, 2, 3, 4, 5],
 renderer_types: ['asterisk',  'circle',  'circlex', 'cross', 'invertedtriangle']}
```
This would result in an asterisk, circle, circlex, cross, and invertedtriangle to be renderered in a diagonal line across the plot.  I realize that there are other ways to come up with a clean api for multiple glyph types, but with this renderer, you could update the data source to change renderer_types to ['invertedtriangle', 'asterisk',  'circle',  'circlex', 'cross'] and end up with a scrolling animation as you continue cycling the renderer_types array.

**Comment by bryevdv** [comment]
Thinking about this more I don't think the low level interface is the place for this. Some higher level functions could just as easily coordinate this.
