### ISSUE TITLE
Regression when plotting images with non-binary array types

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#7652]
Using bokeh master and the most recent dev releases there appears to be a regression plotting array types which cannot be serialized as binary data, i.e. the list of lists image format and dtypes that are not supported in JS (such as int64) are affected:

```
VM30002:100 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
```

Here is a small reproducible example:

```python
import numpy as np
from bokeh.plotting import figure, show, output_file

N = 500
x = np.linspace(0, 10, N)
y = np.linspace(0, 10, N)
xx, yy = np.meshgrid(x, y)
d = (np.sin(xx)*np.cos(yy)*100).astype('int64')
# Also reproducible using list-of-lists format
# d = [[0, 1, 2, 3], [4, 5, 6, 7]]

p = figure(x_range=(0, 10), y_range=(0, 10))

# must give a vector of image data for image parameter
p.image(image=[d], x=0, y=0, dw=10, dh=10, palette="Spectral11")

output_file("image.html", title="image.py example")

show(p)  # open a browser
```

My guess is that some change was made to image rendering in JS, which didn't take into account the fact that the image data can be a 1D typed array or a 2D regular array type. If I had to guess I think the changes to global alpha could be causing this but I haven't yet had time to do a bisection.

**Comment by bryevdv** [comment]
> If I had to guess I think the changes to global alpha could be causing this but I haven't yet had time to do a bisection.

That would be surprising to me but I've certainly been wrong before.

**Comment by mattpap** [comment]
This is likely a regression after PR #7610.
