### ISSUE TITLE
path error connecting to the absolute url

### ISSUE THREAD

**Issue by comisdark** [bokeh/bokeh#7665]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 14.0.2
anaconda python 3.6
Windows 10
chrome / firefox / edge

my topology is a standard bokeh server app with tornado 15 (also tried with last version of 14) and a bottle web site that embeds server documeents.

#### Description of expected behavior and the observed behavior
* in the bokeh app, i created a route to /charts/time_series
* in the web server, i can  server_document(localhost:5006/charts/time_series', arguments=[1,2,3,4,5])

I see the chart displayed as expected.

* view the page source and copy the absolute url, removing the bokeh session arguments:  localhost:5006/charts/time_series?data=[1,2,3,4,5]

* the function bokeh calls successfully gets the data argument and deserializes it but the tornado server produces the following (approximate) output

can't find /charts/static/ .... css, js, and other asssets 

it has built the path incorrectly.

* Change the route to /time_series and repeat the process

the plot appears as expected.

**Comment by bryevdv** [comment]
I don't really have a clear notion of what's actually occurring, or how to reproduce. I am going to close with `norepro`. If you have an opportunity to provide a complete MRE to reproduce things, we can take a closer look.
