### ISSUE TITLE
Flask using js_resources tag results in syntaxerror

### ISSUE THREAD

**Issue by nick-larsson** [bokeh/bokeh#7670]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
uname -a
Linux Zorro-HP-Z620-24 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 
Chrome:Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Python 2.7.12
Pip:
altair==1.2.1
aniso8601==2.0.0
appdirs==1.4.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.3
bokeh==0.12.14
bs4==0.0.1
certifi==2018.1.18
click==6.7
cycler==0.10.0
decorator==4.0.11
dominate==2.3.1
enum34==1.1.6
et-xmlfile==1.0.1
Flask==0.12
Flask-Bootstrap==3.3.7.1
Flask-Moment==0.5.1
Flask-RESTful==0.3.6
Flask-Script==2.0.5
Flask-WTF==0.14.2
functools32==3.2.3.post2
futures==3.2.0
fuzzywuzzy==0.14.0
ipython==5.5.0
ipython-genutils==0.2.0
isodate==0.5.4
itsdangerous==0.24
jdcal==1.3
Jinja2==2.9.5
lxml==3.7.2
MarkupSafe==0.23
matplotlib==2.0.0
networkx==1.11
numpy==1.12.0
openpyxl==2.4.2
packaging==16.8
pandas==0.19.2
pathlib2==2.3.0
Pattern==2.6
pexpect==4.2.1
pickleshare==0.7.4
Pillow==5.0.0
pkg-resources==0.0.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pyexpander==1.7.0
Pygments==2.2.0
pygraphml==2.2
pyparsing==2.1.10
python-dateutil==2.6.0
python-Levenshtein==0.12.0
pytz==2016.10
PyYAML==3.12
rdflib==4.2.2
scandir==1.6
selenium==3.10.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
SPARQLWrapper==1.8.0
subprocess32==3.2.7
tornado==4.5.3
traitlets==4.3.2
vega==0.4.4
visitor==0.1.3
wcwidth==0.1.7
Werkzeug==0.11.15
WTForms==2.1
xlrd==1.0.0

#### Description of expected behavior and the observed behavior
I followed the very simple example but see this error in the chrome console-> 
VM1122:3 Uncaught SyntaxError: Unexpected token >
Even a non javascript person can see there is a problem (second replace):
replace(/</g,"&lt;").replace(></t.length;e++){var>/g,"&gt;")},t}(d.Model);n.Cell
The cause seems to be the inclusion of the 
js_resources|safe tag in the template. Removing this fixes the problem. Putting the tag before or after the css has no effect. I am trying to get a slider with a python callback to work and I see no events and was led to believe that the fix for this is to include the js_resources. Since this does not work I am stuck. Is this a bug or a user error? Looks like a bug as I have followed the example and even simplified further.
#### Complete, minimal, self-contained example code that reproduces the issue

```
======================
Template:
<!doctype html>
<html lang="en">
  <head>
    <meta charset='utf-8' />
    <meta http-equiv='content-type' content='text/html; charset=utf-8' />

    <title>Embed Demo</title>

    {{ js_resources|indent(4)|safe }}

    {{ css_resources|indent(4)|safe }}


    {{ plot_script|indent(4)|safe }}

  </head>
  <body>
    <!-- A simple form for changing the graph -->
    <p> Select your settings: </p>
    <form name="color_button" method='GET'>
        Color:
        <select name="color">
            <option {{ "selected" if color|indent(4)|safe == "Red" }} value="Red">Red</option>
        </select>
        <br>
        <button type="submit">Submit</button>
    </form>
    {{ plot_div|indent(4)|safe }}
    <p> Demonstrates some very simple embedding into a webpage</p>
  </body>
</html>


======================
Python:
  	    js_resources = INLINE.render_js()
	    css_resources = INLINE.render_css()
            return render_template("simple.html",
				   color="Red",
                                   plot_script="",
                                   plot_div="<div></div>",
				   js_resources=js_resources,
				   css_resources=css_resources)
  

```

#### Stack traceback and/or browser JavaScript console output
VM1122:3 Uncaught SyntaxError: Unexpected token >
    at DOMEval (VM1086 jquery.js:82)
    at domManip (VM1086 jquery.js:5782)
    at jQuery.fn.init.append (VM1086 jquery.js:5918)
    at jQuery.fn.init.<anonymous> (VM1086 jquery.js:6012)
    at access (VM1086 jquery.js:3976)
    at jQuery.fn.init.html (VM1086 jquery.js:5979)
    at Object.<anonymous> (VM1086 jquery.js:9828)
    at fire (VM1086 jquery.js:3305)
    at Object.fireWith [as resolveWith] (VM1086 jquery.js:3435)
    at done (VM1086 jquery.js:9242)
VM1120:3 [bokeh] setting log level to: 'info'

**Comment by bryevdv** [comment]
This is a usage/support question, please take it to the mailing list, per project guidelines

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
