### ISSUE TITLE
Add a spinner widget

### ISSUE THREAD

**Issue by ongietorri** [bokeh/bokeh#7675]
Is it possible to create a widget that has text input for entering numeric values, with up/down buttons and arrow key handling?

https://en.wikipedia.org/wiki/Spinner_(computing)

![](https://upload.wikimedia.org/wikipedia/commons/9/95/Tabstop-spinner-gedit.png)

Thanks

**Comment by suraj-deshmukh** [comment]
you can use Div and add spinner input <input type="number" name="quantity" min="1" max="5"> and have a callback to get the selected value

**Comment by bryevdv** [comment]
I don't know that we will be able to prioritize this especially soon. In the mean time, you could make a custom extension:

https://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html

Otherwise, adding this would make a nice PR for a new contributor.

**Comment by bryevdv** [comment]
closed by #8678
