### ISSUE TITLE
Add warnings when bad configuration passed to gridplot

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#7678]
I was just struggling a little with gridplot. 

Initially, because I needed to pass `ncols` if I just wanted to pass a list of plots, and then because my plot generation function wasn't returning a plot so it was a hot mess.

This is a feature request to add some extra checking and warnings / hints to silly users of gridplot like me.

**Comment by bryevdv** [comment]
Do you have a test case? I don't quite understand fully what led to a mess.

**Comment by bryevdv** [comment]
Ok I don't really know at all what are the situations need warning about, I am going to close this for now. If you have time to add some examples of bad usage that led to problems and should have warnings, we can re-open.
