### ISSUE TITLE
Make it possible to use pytest-xdist for all tests

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7679]
Currently, running something like `pytest -n auto` results in an error - different nodes collect different test.

**Comment by p-himik** [comment]
Also, running `python -m unit -n auto` doesn't result in the same error, but fails a bunch of tests because, I think, ports for `bokeh serve` are predefined.

**Comment by bryevdv** [comment]
@p-himik I'm going ahead and closing this because it's not especially a priority for me, and it's been been inactive for quite a while. If you are ever interested in reviving it we can definitely re-open
