### ISSUE TITLE
GMapPlot not rendering

### ISSUE THREAD

**Issue by OxygenLithium** [bokeh/bokeh#7688]
#### Software version info
- Bokeh 0.12.15dev6
- Python 3.6.3
- Windows 10
- Tested with Chrome and Edge

#### Expected behavior and the observed behavior
- Expected GMap plot to be displayed in browser window.
- Bokeh frame and window generates correctly, but no map shown. 
- Equivalent to when an invalid API key is provided.
- Same program and API key worked in Bokeh 0.12.14

#### Tested using example shown below from Bokeh docs:
```
from bokeh.io import output_file, show
from bokeh.models import (
  GMapPlot, GMapOptions, ColumnDataSource, Circle, Range1d, PanTool, WheelZoomTool, BoxSelectTool
)

map_options = GMapOptions(lat=30.29, lng=-97.73, map_type="roadmap", zoom=11)

plot = GMapPlot(x_range=Range1d(), y_range=Range1d(), map_options=map_options)
plot.title.text = "Austin"

# For GMaps to function, Google requires you obtain and enable an API key:
#
#     https://developers.google.com/maps/documentation/javascript/get-api-key
#
# Replace the value below with your personal API key:
plot.api_key = "MY_API_KEY"

source = ColumnDataSource(
    data=dict(
        lat=[30.29, 30.20, 30.29],
        lon=[-97.70, -97.74, -97.78],
    )
)

circle = Circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8, line_color=None)
plot.add_glyph(source, circle)

plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool())
output_file("gmap_plot.html")
show(plot)

```
#### Screen Capture
![bokehcapture](https://user-images.githubusercontent.com/36341776/37864501-e067d624-2f67-11e8-8174-e14f8cd390ec.PNG)

**Comment by bryevdv** [comment]
@mattpap This is a recent regression, probably from the TypeScript port work. I can reproduce on OSX as well as windows. Initially there is nothing in the console, but try to pan and you will see:

> TypeError: undefined is not an object (evaluating 'this.map.panBy')

**Comment by bryevdv** [comment]
@OxygenLithium Thank you for bringing this to our attention, we are just finishing up a huge overhaul of the codebase, there are some rough edges as a result

**Comment by mattpap** [comment]
Additionally none of the gmap code is tested due to API key requirement.
