### ISSUE TITLE
Inconsistent raising of E-1009 depending on whether x_range defined in kwargs or outside.

### ISSUE THREAD

**Issue by MelvinYin** [bokeh/bokeh#7689]
**Software Version Info**
**Bokeh**: `0.12.14`, `0.12.15dev6`
**Python**: `3.6.4`
**OS**: `Windows`
**Browser**: `Microsoft Edge`

**Description**
When setting the `x_range` of a `figure` to `FactorRange`, if this is done in the `kwargs` when creating `figure`, error E-1009 will not be raised if `x_scale` is not set to `CategoricalScale()`. Whereas, if `x_range` is set after (via `figure.x_range`), E-1009 will be raised if `x_scale` is not set. 

Error message:
`E-1009 (INCOMPATIBLE_SCALE_AND_RANGE): A Scale is incompatible with one or more ranges on the same plot dimension: incompatibility on x-dimension: FactorRange(id=...)/LinearScale(id=...),...`

**Sample Code**

(Full)
```
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, FactorRange, CategoricalScale
from bokeh.plotting import figure

output_file("test.html")
data = dict(a=[1, 2], b=[2, 3])
source = ColumnDataSource(data=data)
p = figure(x_range=FactorRange(*data))
p.x_range = FactorRange(*data)
p.x_scale = CategoricalScale()
p.x(x='a', y='b', source=source, size=10)
show(p)
```
(No error)
```
p = figure()
p.x_range = FactorRange(*data)
p.x_scale = CategoricalScale()
```
(No error)
```
p = figure(x_range=FactorRange(*data))
```
(No error)
```
p = figure(x_range=FactorRange(*data))
p.x_range = FactorRange(*data)
```
(Error)
```
p = figure()
p.x_range = FactorRange(*data)
```

**Comment by MelvinYin** [comment]
I'm guessing here, but is the intention that if `x_range` is set when constructing `function` but `x_scale` is not specified, then a compatible `x_scale` will automatically be set, but if `x_range` is set after `function` has been constructed, to avoid wiping out any user-specified `x_scale`, this error should be triggered?

**Comment by bryevdv** [comment]
Not intention, so much as what is possible. In any event yes if you set things in `figure` we have the opportunity to do the right thing. If you change one part after the fact, we don't, and that warning is the prompt to let you know that more manual configuration is necessary.

**Comment by MelvinYin** [comment]
That's true. Has it been considered that `x_scale` be made explicit in the examples, such as this:
https://bokeh.pydata.org/en/latest/docs/gallery/bar_nested_colormapped.html
Considering that `p.x_range.range_padding` is set after, it is rather tempting to pull `x_range` outside as well. This is also where I first encountered the issue, when trying to understand `FactorRange`.

Thanks for the clarification!

**Comment by bryevdv** [comment]
I would be happy to have one (or maybe two) examples that show how to use `scale` explicitly, but would not want to do the in general. It's usually not necessary, so adding would over complicate the examples in an unnecessary way. I think it would be more compelling if we had implemented a `CustomJSScale` but that has not happened yet. In any case if you have an example with explicit scales, happy to consider a PR that adds it.

**Comment by MelvinYin** [comment]
Yup I agree, was reading through the source code, it will make the line `self.x_scale = _get_scale(self.x_range, opts.x_axis_type)` rather pointless if `x_scale` is set explicitly. 

Sure, I'm still trying to understand how `Scale` and `Range` work together, will prepare an example if I can get it to work consistently. Thanks for your time!

**Comment by bryevdv** [comment]
My pleasure. For your question: essentially: ranges are define start/end coordinates (even for categorical ranges, there is an underlying synthetic coordinate system with a start/end). A scale is a transformation that maps "data space" coordinates to pixel coordinates on the canvas.
