### ISSUE TITLE
bokeh.io.notebook._server_url logic error produces faulty URL

### ISSUE THREAD

**Issue by cbanek** [bokeh/bokeh#7701]
Version: master/head

The logic in bokeh.io.notebook._server_url used to generate the URLs to put as origin and notebook URLs in the javascript has some issues.

```
import bokeh.io.notebook
print(bokeh.io.notebook._server_url('http://localhost', 12345))
print(bokeh.io.notebook._server_url('https://localhost', 12345))
print(bokeh.io.notebook._server_url('localhost', 12345))
```

http:12345/ - wrong
https:12345/ - wrong
http://localhost:12345/ - correct

**Comment by bryevdv** [comment]
@cbanek the reason for the output you see is that URL is always expected to have a port included, i.e.
```
_server_url("http://foo.com:8888", 10) == "http://foo.com:10/"
```
Given that this is an internal function, and we always demonstrate passing a notebook URL with a port, I am inclined to just close this. If we find more people running into an issue in a user-facing way we can reconsider.
