### ISSUE TITLE
Sharing of BoxZoomTool/BoxSelectTool between plots of different sizes creates wrong overlays

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7703]
Bokeh 0.12.15dev7

```python
from bokeh.io import show
from bokeh.layouts import row
from bokeh.models import BoxSelectTool, BoxZoomTool, ResetTool
from bokeh.plotting import figure

tools = [BoxZoomTool(), BoxSelectTool(), ResetTool()]
f1 = figure(width=500, height=500, tools=tools)
f1.x([0], [0])
f2 = figure(width=200, height=200, tools=tools,
            x_range=f1.x_range, y_range=f1.y_range)
f2.x([0], [0])

show(row(f1, f2))
```

![image](https://user-images.githubusercontent.com/4410314/37979678-641de668-3213-11e8-9469-8cf091a9ec4f.png)

To be honest, I have no clue whether this should be even considered a bug.

**Comment by bryevdv** [comment]
Sharing tools has never been supported that I can recall

**Comment by bryevdv** [comment]
In fact IIRC this actually used to generate an error, but I think we removed plot back references on tools, which is what was used to determine if a tool was trying to be re-used. This issue could be for adding better warnings/validation, or we could just close it. I don't have strong opinions, I haven't seen any SO or ML questions about this so I don't think it comes up much.

**Comment by bryevdv** [comment]
I'm inclined to just close it. If we see a spike in questions or posts about it we can re-open to add some kind of validation.
