### ISSUE TITLE
Axis types

### ISSUE THREAD

**Issue by davidgardenier** [bokeh/bokeh#7709]
I've noticed that I often absentmindedly will change `x_axis_type` from `log` to `lin`, assuming it should be a three letter abbreviation. Or indeed the other way around, from `linear` to `logarithmic`. Both cases cause an error as the correct arguments should be either `linear` or `log`. Would it be possible to adapt the `x_axis_type` and `y_axis_type` keywords to accept `lin` instead to `linear`? This would provide consistency in the arguments.

MWE in Bokeh 0.12.14:
```
import numpy as np
from bokeh.plotting import figure, show, output_file

x = np.linspace(0.1, 5, 100)
p = figure(x_axis_type="lin")
p.line(x, np.sqrt(x))
show(p)
```

**Comment by bryevdv** [comment]
@davidgardenier I can't say this is something I would consider a priority, which is the reason I am going to close this. However, adding *just to `figure`* would be a pure python side task that should be accessible to most python programmers. If you'd like to submit a PR, we can re-open the issue then. The place that would need updating is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/figure.py#L79-L84

You would need to add an `.accepts` clause to each of those properties to convert `"lin"` to `"linear"` (and update the helpstring as well, and ideally add a unit test)
