### ISSUE TITLE
Unexpected warning with update of multi_line 

### ISSUE THREAD

**Issue by stjemkes** [bokeh/bokeh#7710]
Running a code which is a deviation from the Selection Histogram code you post on the web.
Instead of histograms i am showing a multi_line plot at the right hand side
centre plot is a scatter plot. 

code is relatively straight forward:
#############################################################################
yr = Range1d(start=1050,end=1.e-2) # reverse y-axis
pv = figure(toolbar_location=None, plot_width=200, plot_height=p.plot_height, y_axis_type="log",
            x_range=(150, 350), y_range=yr, min_border=10, min_border_left=50, y_axis_location="right")

pv.xaxis.major_label_orientation = np.pi/4
pv.background_fill_color = "#fafafa"

pv.multi_line(xs=xst, ys=yst, line_color="grey", alpha=0.5) 
hv2 = pv.multi_line(xs=xst[:], ys=yst[:], line_color="tomato")

def update(attr, old, new):
    inds = np.array(new['1d']['indices'])
    print("inds {}".format(inds))
        
    new_xst = []
    new_yst = []
    for i in inds:
        new_xst.append(xst[i])
        new_yst.append(yst[i])
    
    hv2.data_source.data["xs"] = new_xst
    hv2.data_source.data["ys"] = new_yst
########################################################################
rest is as per original code (except i removed the histograms)

after selecting a set of points from my scatter plot i have (i print the inds list to double check as you can see):
---------------------------------------------------------------------------------
inds [690 774 950 797 858 254 801 747 773 823 771 859 796 207 750 909 825 772
 691 658 206 798 852 826 659 752 915 746 660 949 842 748 779 822 874 925
 964 824 948 961]
/home/stephen/.local/lib/python3.6/site-packages/bokeh/models/sources.py:138: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('xs', 40), ('ys', 992)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
-----------------------------------------------------------------------------------------------------------------

the inds shows the indices of the 40 points i have selected, in the initial plot there are 992 cases. 
what is seen is that the xs data is updated in the warning statement, but the ys not. 
The plot displays the expected behaviour: i get a red line on top of some grey lines.

If i select a different set of points same thing happens:

---------------------------------------------------------------------------------------------
inds [129 127 185 714 249 711 686 769 740  60 688 309 182  54  53 743 126 472
 742 745  52 118 744  51 770  58  55 194 130 124 189 195  47 120 123 121
 193 119 713 715 190 192 197  57 308 689 252 687 115 652 682 183 651  50
  59 471 186 117 114 131 132 199 198 122]
/home/stephen/.local/lib/python3.6/site-packages/bokeh/models/sources.py:138: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('xs', 64), ('ys', 40)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
------------------------------------------------------------------------------------
etc,
-------------------------------------------------------------------------------------------------------
inds [132]
/home/stephen/.local/lib/python3.6/site-packages/bokeh/models/sources.py:138: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('xs', 1), ('ys', 64)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
inds [ 54  53 743 126 472 742 745 194 124 195  52 131 199 198 122]
/home/stephen/.local/lib/python3.6/site-packages/bokeh/models/sources.py:138: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('xs', 15), ('ys', 1)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))

It bothers me a little that i get the warning. But for rest system seems to work nicely.

**Comment by bryevdv** [comment]
@stjemkes Thanks for your interest in Bokeh. This is a general support/usage question. In order to focus the GH issue tracker for development, it is reserved for bug reports and feature requests only. We request that help discussions be taken to SO or the public mailing list: https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
