### ISSUE TITLE
Clear documentation to explain how and from where to import Bokeh objects

### ISSUE THREAD

**Issue by imiu** [bokeh/bokeh#7718]
I noticed that the object(s) can be imported from different places. This could be a source of confusion as user might question what's the right place to import from. So, it should be one source of truth.
For example,`Button` can be imported as `from bokeh.models import Button` or  `from bokeh.models.widgets`  probably more. In that respect, the documentation/reference/user guide page(s) should have a link to explain imports from Bokeh. Also, modules seem to contain a mixture of objects. For example, `bokeh.models.widgets` has both, `Div` and `Button` even though the two elements belong to two different categories; `Div` is structural and `Button` is behavioral. That being said, it might be optimum to structure modules based on the properties of the objects. With current structure, it seems more of a 'look-around to find what you need' ...:)

**Comment by imiu** [comment]
I agree with you. Maybe is just me being too rigorous and trying to eliminate any shadow of confusion. Thinking from user's perspective, I expect that is going a diverse poll of people that will use Bokeh; some with a good understanding of programming and some from fields loosely related to programming interested in putting something together quickly to present their data. That's the angle where I was coming from.

**Comment by bryevdv** [comment]
`bokeh.models` definitely intentionally collects all the models to make them available in one place on purpose. So I think `from bokeh.models import Button` is what I would advocate for, and what we will try to demonstrate consistently.  Although I don't expect the submodule layout to change, telling users to use `bokeh.models` as the "right way" to do things, does give us the cover to make changes down in the hierarchy if we really must. That said, for this to really be reasonable,  we'd need to re-arrange the reference guide to reflect this. Currently everything is split out. Depending on this discussion, this issue might server for that task.


Regarding things outside `bokeh.models`, currently all public API functions, classes, etc are being tagged as `general` or `dev`. The "general" objects are all included in top level modules e.g. `bokeh.io`  for common things like `show`, and the "dev" objects are only available in submodules, e.g. `bokeh.io.notebook` for less common things like `get_comms`. But both `general` and `dev` function are intended to be stable, maintained API.

**Comment by bryevdv** [comment]
Thinking more about this I think I will just close this, there is a nice discussion here now that we can point to is they want more information. But mostly, it really is a matter of preference and personal style, and after some reflection, I don't want to wade into that :)
