### ISSUE TITLE
Remove botched DataTable.row_headers deprecation code in 0.12.15

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#7719]
I've just updated from 0.12.14 to 0.12.15

I'm getting the following failure from my server-side code:

    E           AttributeError: unexpected attribute 'row_headers' to DataTable, similar attributes are index_header

OK I think, possibly this attribute went away.  Lets see how bad things look if I just don't specify it at all.

But when I remove it from my figure I get the following error on the client

    connection.js:189 [bokeh] Failed to repull session Error: property DataTable.row_headers wasn't declared

**Comment by bryevdv** [comment]
Was completely mis-named, it had nothing to do with row headers. The correct property name is described in the migration notes:

https://bokeh.pydata.org/en/latest/docs/releases/0.12.15.html#datatable

**Comment by mrocklin** [comment]
For how far back in Bokeh version history is this term valid?  I'm trying
to learn if I need to add special logic to adjust for different bokeh
versions.

**Comment by mrocklin** [comment]
OK, thanks.  I'll add a version check in Dask code.

**Comment by bryevdv** [comment]
I'll leave this open as a task to remove the useless deprecation properties. 

Sorry for the issue, there's only so much I can do on my own. Happy to accept downstream tests for a `downstream` Bokeh CI job, or help integrate bokeh dev builds into downstream tests.

**Comment by mrocklin** [comment]
Not a big problem.  I appreciate the quick triage.

**Comment by mrocklin** [comment]
If you did want a test suite you might consider the following

```python
pip install distributed
py.test distributed/bokeh
```

It's just one project, but we do touch a non-trivial amount of Bokeh's API at this point.
