### ISSUE TITLE
Plots not reacting to sliders inside flask.

### ISSUE THREAD

**Issue by halidaee** [bokeh/bokeh#7724]
Hello,

Using Bokeh 0.12.15 with flask, via "bokeh serve". My bokeh dashboard features sliders to dynamically update the plots. When I visit the site hosted by flask, the plot responds to the sliders for the few second or so, and then stops reacting, until I refresh the page. In contrast, if I directly visit the page hosted by the Bokeh server (i.e. localhost:5100/my_bokeh_page), then no problems arise; the sliders are fully functional throughout the entire session.

This problem seems to have arisen sometime after Bokeh 0.12.13. Reverting to 0.12.13 fixes the problem entirely. (Haven't tried 0.12.14)

**Comment by bryevdv** [comment]
In order to investigate we need a complete runnable example and instructions to reproduce. Are you able to provide these?

**Comment by halidaee** [comment]
Sure. Attached complete, minimal runnable example in the .zip below. 

It involves a simple bokeh plot where you choose a per unit value and get a linear plot showing total value depending on number of units produced.

I run it using
bokeh serve bokeh_test.py --allow-websocket-origin=127.0.0.1:8080 --allow-websocket-origin=localhost:5100 --port 5100 &
python flask_server.py

The problem is true both on my local installation and on a similar setup via EC2 (using Apache)




[Archive.zip](https://github.com/bokeh/bokeh/files/1866894/Archive.zip)

**Comment by bryevdv** [comment]
Well, I can reproduce this, but I am at a loss. What's even stranger is if I kill the flask server, then the interaction starts working again. So the websocket connection to the app is not being broken (that would also show up in logs and it doesn't). I also see the BokehJS internal slider callback being called even when the interaction is not working.  But what does stop during the time when its not working is patch event notifications on the server. So it appears something is causing outbound websocket event messages to be suppressed while flask is running, but as  of yet I have no idea what that could be.

**Comment by bryevdv** [comment]
With trace logging on, it's easy to see on the server: as soon as flask is killed, a long backlog of previous messages arrives all at once. So I guess the question is then: are they getting queued but unsent on the client side? Or are they getting sent but queued up on the server side? Will have to instrument BokehJS to log more info in its websocket send function.

**Comment by bryevdv** [comment]
@halidaee as a possible workaround, I am unable to reproduce any problem if I use `server_document` instead:
```

@app.route('/')
def bkapp_page():
    myscript = server_document(myurlstr)
    return render_template("embed.html", myscript = myscript, template="Flask")
```
Which also leads me to suspect the problem has to do with the fact that Flask has pulled a session. Perhaps it is getting garbage collected but not disconnecting properly, causing updates to hang.

**Comment by bryevdv** [comment]
@halidaee This also seems to fix the issue with the original code:
```
@app.route('/')
def bkapp_page():

    # pull a new session from a running Bokeh server
    mysession = pull_session(url=myurlstr)

    # generate a script to load the customized session
    myscript = server_session(None, mysession.id, url=myurlstr)
    mysession.close()
    return render_template("embed.html", myscript = myscript, template="Flask")
```
Can you confirm? 

I currently suspect that something about the way the session (the one opened by flask) is garbage collected is causing problems.

**Comment by bryevdv** [comment]
I've triaged this for `0.12.16` given the workaround information above I am not going to apply `CRITICAL`

**Comment by bryevdv** [comment]
An alternative to `__del__` might be to make `ClientSession` a context manager:

```
with pull_session(url=myurlstr) as mysession:

    myscript = server_session(None, mysession.id, url=myurlstr)
    return render_template("embed.html", myscript = myscript, template="Flask")
```

That said, I don't expect `ClientSession` to be involved in any cyclic references, in which case a  `__del__` should be safe.
