### ISSUE TITLE
Docs - JSON Prototype does not expand

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#7744]
See, for example, https://bokeh.pydata.org/en/latest/docs/reference/models/sources.html#bokeh.models.sources.ColumnDataSource

Clicking on JSONPrototype it does not expand.

Tested on chrome and firefox on linux.

**Comment by bryevdv** [comment]
Possibly related, site JS code does not like the new tutorial link

<img width="931" alt="screen shot 2018-04-03 at 23 10 01" src="https://user-images.githubusercontent.com/1078448/38291364-42e664d0-3794-11e8-8813-15f94a9fe513.png">

**Comment by bryevdv** [comment]
That was the problem. I made a local fix on the prod box, I will push a PR to fix future deploys tomorrow.

**Comment by bryevdv** [comment]
for reference, screening out external links solved:
```
    // Add current class to the section of docs we're in
    var nav_links = $('.nav-link.doc-head a');
    nav_links.each(function(i, nav_link) {
      var href = nav_link.href;
      if (href.startsWith("https://bokeh.pydata.org")) {
        var href_part = href.split('docs/')[1].split('.html')[0];
        if (href_part.split('/').length > 1) {
          href_part = href_part.split('/')[0]
        }
        if (loc_part == href_part) {
          $(this).addClass('current');
        }
      }
    });
```
