### ISSUE TITLE
PointDrawTool : no python side update of the data source

### ISSUE THREAD

**Issue by poldavezac** [bokeh/bokeh#7745]
In Bokeh: 0.12.15,  python 3.6.4 & firefox 59.0.2

I tried the [PointDrawTool](https://bokeh.pydata.org/en/latest/docs/user_guide/examples/tools_point_draw.html)  example modifying it for use with the bokeh server and removing the table widget. See code below

I find that the source is updated on the javascript side but **not** on the python server side: the python data change event is never triggered. On the other hand, the selection change event is triggered on both sides but without the source's data being updated in python.

A workaround is to add the widget again, possibly with a height and width set to 0. 

The code:
```
from bokeh.plotting import figure, Column, curdoc
from bokeh.models import DataTable, TableColumn, PointDrawTool, ColumnDataSource, CustomJS

p = figure(x_range=(0, 10), y_range=(0, 10), tools=[""],
           title='Point Draw Tool')
p.background_fill_color = 'lightgrey'

source = ColumnDataSource({
    'x': [1, 5, 9], 'y': [1, 5, 9], 'color': ['red', 'green', 'yellow']
})

renderer = p.circle(x='x', y='y', source=source, color='color', size=10)
columns = [TableColumn(field="x", title="x"),
           TableColumn(field="y", title="y"),
           TableColumn(field='color', title='color')]
table = DataTable(source=source, columns=columns, editable=True, height=0, width = 0)
source.on_change("selected", lambda attr, old, new: print("python changed selected", new))
source.on_change("data", lambda attr, old, new: print("python changed data", new))
source.js_on_change("selected", CustomJS(code = 'console.log("javascript: change selected", cb_obj)'))
source.js_on_change("data", CustomJS(code = 'console.log("javascript: change data", cb_obj)'))

draw_tool = PointDrawTool(renderers=[renderer], empty_value='black')
p.add_tools(draw_tool)
p.toolbar.active_tap = draw_tool

curdoc().add_root(Column(p))

```

python console:
```
2018-04-04 10:14:00,904 Starting Bokeh server version 0.12.15 (running on Tornado 4.5.2)
2018-04-04 10:14:00,909 Bokeh app running at: http://localhost:5006/toto
2018-04-04 10:14:00,909 Starting Bokeh server with process id: 30817
2018-04-04 10:14:01,588 200 GET /toto (127.0.0.1) 220.16ms
2018-04-04 10:14:01,972 101 GET /toto/ws?bokeh-protocol-version=1.0&bokeh-session-id=7YdOmfAtA3Jn38ry9QkTNoWpu2EOC1CiFRKYH81ubuKi (127.0.0.1) 1.34ms
2018-04-04 10:14:01,973 WebSocket connection opened
2018-04-04 10:14:01,974 ServerConnection created
python changed selected Selection(id='B7B1F1C26934499D8C622D851B9CD564', ...)
python changed selected Selection(id='E989B4D359664AE3924315EAD66C998C', ...)
```

browser console:
```
[bokeh] setting log level to: 'info'
logging.js:131
[bokeh] Websocket connection 0 is now open
connection.js:194
[bokeh] document idle at 302 ms
document.js:188
Bokeh items were rendered successfully
embed.js:262
javascript: change selected 
Object { _subtype: undefined, document: {…}, destroyed: {…}, change: {…}, transformchange: {…}, attributes: {…}, properties: {…}, _set_after_defaults: {…}, _pending: false, _changing: false, … }
bokeh.min.js:3:1
javascript: change selected 
Object { _subtype: undefined, document: {…}, destroyed: {…}, change: {…}, transformchange: {…}, attributes: {…}, properties: {…}, _set_after_defaults: {…}, _pending: false, _changing: false, … }
bokeh.min.js:3:1
javascript: change data 
Object { _subtype: undefined, document: {…}, destroyed: {…}, change: {…}, transformchange: {…}, attributes: {…}, properties: {…}, _set_after_defaults: {…}, _pending: false, _changing: false, … }
```

**Comment by bryevdv** [comment]
cc @philippjfr

**Comment by philippjfr** [comment]
@bryevdv I can reproduce but I can't currently explain it, any idea why the data source would be emitting ``js_on_change`` events but no ``on_change`` events?

**Comment by bryevdv** [comment]
Not offhand but I will triage it based on you your comments

**Comment by poldavezac** [comment]
I'm not sure whether this belongs here or in a different issue:

when the the data change event does trigger in the server (i.e if a DataTable has been added), the selection event in the server still occurs first. This is probably not optimal as it means that the server doesn't yet know about the latest data values. It would likely simplify the users' life to have the events trigger in the opposite order.

**Comment by bryevdv** [comment]
@philippjfr another issue, not sure if it is related. This example:

https://bokeh.pydata.org/en/dev/docs/user_guide/tools.html#pointdrawtool

Used to continuously update the data table when a point is moved, now it only updates at drag end. Not sure if there's an issue with the tool or the table but we should figure out (and make a new issue as appropriate)

**Comment by bryevdv** [comment]
@mattpap this diff fixes the table not updating mid-drag:
```
diff --git a/bokehjs/src/lib/models/tools/edit/edit_tool.ts b/bokehjs/src/lib/models/tools/edit/edit_tool.ts
index 3e6fe825d..def230871 100644
--- a/bokehjs/src/lib/models/tools/edit/edit_tool.ts
+++ b/bokehjs/src/lib/models/tools/edit/edit_tool.ts
@@ -75,7 +75,7 @@ export abstract class EditToolView extends GestureToolView {
       }
     }
     for (const renderer of renderers) {
-      renderer.data_source.change.emit();
+      renderer.data_source.properties.data.change.emit();
     }
     this._basepoint = [ev.sx, ev.sy];
   }
``` 
Is that expected? It seems like either of those should work to update the table. I'm still trying to run down why python events are not being generated. Perhaps because there is no actual assignment to `.data`

**Comment by bryevdv** [comment]
OK I have a potential fix, PR incoming. @poldavezac note that what I can make work, and all that we will be able to support for now, is python updates at the *end* of the edit (not continuously during the drag)
