### ISSUE TITLE
Trouble with HoverTool & vbar_stack

### ISSUE THREAD

**Issue by dustinmichels** [bokeh/bokeh#7758]
Hi!

I want to add a `HoverTool` to a `vbar_stack` plot. I'm trying to emulate this example from this docs:
https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html#hover-tools

I was getting an error because `p.vbar_stack` did not return a list of renderers, as the docs suggested, by simply `None.` I get the same error when I run the code example in the docs verbatim.

 ### Meta-data
- version: '0.12.14'
- macOS / firefox
- JupyterLab

**Comment by bryevdv** [comment]
The docs are for 0.12.15 and the feature is brand new. You need to upgrade to use it.

**Comment by dustinmichels** [comment]
Okay, all is working now. Thanks a lot!!
