### ISSUE TITLE
Copy & paste from datatable

### ISSUE THREAD

**Issue by rupgr** [bokeh/bokeh#7762]
I don't believe it is possible already, but could you add the ability to copy & paste from the datatable.
My use case would be for copying and pasting between Bokeh and Excel.
Many thanks!

**Comment by bryevdv** [comment]
It appears there is nothing built into SlickGrid, but there may be some hope to follow this example:

http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html

**Comment by Nicoowr** [comment]
I took a look at the code in the link and it appears we need the SlickGrid object to set up the copy/paste tool : 
      `grid = new Slick.Grid("#myGrid", data, columns, options);`
      `grid.setSelectionModel(new Slick.CellSelectionModel());`
      `grid.registerPlugin(new Slick.AutoTooltips());`
Do you know how we could get it from bokeh? So far, using customJS, I have only been able to get the "div" object containing the table. I could recreate the table from it in JS but this seems an absurd way to do it...
