### ISSUE TITLE
Make API decorators more debugging friendly

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#7774]
Currently we have the following code in `core.util.api`:
https://github.com/bokeh/bokeh/blob/87a2e9a93b8e5d87ddef7de6a08b50810301512f/bokeh/util/api.py#L182-L194
This makes every API call go through `wrapper`, which is incredibly annoying during debugging. I'm not sure why wrapping is needed for functions and methods. I removed the wrapper and used the same code for classes and functions/methods, and there are no test failures. Is this a Py2/3 thing or else?

**Comment by bryevdv** [comment]
The same thought occurred to me the other day, so I am OK with not using a decorator, and we can get rid of the API spec tests while we are at it as @p-himik suggests as well. We just need to come up with some reasonably enforceable or verifiable convention for denoting version levels on functions so that we can accurately report "This function was added in version x.y.z" in the docs.

**Comment by bryevdv** [comment]
Alternatively, as you say we can keep the decorator but not make a wrapper function, I think it's only there because that's typical and I made a wrapper out of habit, but it does not really add anything in this case.

**Comment by bryevdv** [comment]
@mattpap Oh, yes this is a py2 thing:
```
(py27) ❯ python
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 11:07:58)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foo(object):
...     def bar(self): pass
...
>>>
>>> Foo.bar.__bkv__ = 1.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'instancemethod' object has no attribute '__bkv__'
```
So any path involving annotating methods themselves in py2 will involve a wrapper. I'm OK with some docstring convention  especially if we could automate checking that it's always done.

**Comment by p-himik** [comment]
I'm definitely in favor of some convention. One way to implement it would be a git push hook that would check all changed files, get all new/changed functions and check that all public ones were described in the documentation. But it's a bit involved.

On bokeh-dev Gitter I asked about Python 2 support, but nobody seemed to notice. Are there any defined plans on dropping Python 2 support altogether, given its EOL in less than 2 years?

**Comment by bryevdv** [comment]
FYI I am working on a test to rip out the decorators and the spec tests. 

We do need to have a discussion about a timeline for dropping py 2 support but given that various groups have made significant financial contributions to the development of Bokeh, those discussions need  to involve them as well.
