### ISSUE TITLE
Feature-request: Selection-Bar

### ISSUE THREAD

**Issue by heoa** [bokeh/bokeh#7795]
This is a feature-request for a Selection-Bar. You can see an example about Selection-Bar [here](https://webapps.qlik.com/masters/index.html#/2018-stats/). I am interested to help to do this feature but I need to understand a few things.

**How would you implement Selection-Bar on Bokeh? With Extension or build it to the base package?**

**Comment by bryevdv** [comment]
Hi @heoa I think this would be a good addition, and I think that now all the necessary parts are in place to make it fairly straightforward to add to the core library. Here is what I would suggest:

* Have a new `RangeTool`, declared on the Python as roughly:

    ```
    class RangeTool(Tool): 
        x_range = Instance(Range1d)
        y_range = Instance(Range1d)
    ```

* On the JS side, the implementation will *have* a `BoxAnnotation` and it will use the ranges to set the dimensions of the box
  - One of the ranges may be `None`, in this case the box spans that entire dimension 
  - The tool will respond to drag events: if the drag starts in the middle of the box, the entire box is moved (by updating the ranges appropriately). If the drag starts near a border, only that border is moved (by updating the range)
  - The tool will respond to move move events, and if the mouse is near a border, will display some kind of handle or highlight 

With this in place you could do something like:
```
p1 = figure(...)

p2 = figure(...)
pe.add_tool(RangeTool(x_range=p1.x_range))
```
then be able to control the range of `p1` by manipulating the box on `p2`. You could also add any standard JS or python callbacks to the ranbes for other behaviours. 

I think this would be a fantastic task for a new contributors. Are you interested in working up a PR for this? I am not sure of your background, so I do not know if this is enough context and information to get started, but can always go into more detail.

**Comment by heoa** [comment]
Is there any demo yet available? I would like to learn bokeh better with this.

**Comment by bryevdv** [comment]
https://bokeh.pydata.org/en/dev/docs/gallery/range_tool.html
