### ISSUE TITLE
Missing documentation of `--show` option for command line `bokeh serve`

### ISSUE THREAD

**Issue by aweinstein** [bokeh/bokeh#7797]
The [documentation of the bokeh server](https://bokeh.pydata.org/en/latest/docs/user_guide/server.html) mentions the `--show` options to open automatically a browser tap with the application. This works as expected. However, the command line help of the `bokeh` command line does not mention this option:

```
$ bokeh --help
usage: /home/ajw/.local/anaconda/bin/bokeh [-h] [-v]
                                           {html,info,json,png,sampledata,secret,serve,static,svg}
                                           ...

positional arguments:
  {html,info,json,png,sampledata,secret,serve,static,svg}
                        Sub-commands
    html                Create standalone HTML files for one or more
                        applications
    info                print information about Bokeh and Bokeh server
                        configuration
    json                Create JSON files for one or more applications
    png                 Create standalone PNG files for one or more
                        applications
    sampledata          Download the bokeh sample data sets
    secret              Create a Bokeh secret key for use with Bokeh server
    serve               Run a Bokeh server hosting one or more applications
    static              Serve bokehjs' static assets (JavaScript, CSS, images,
                        fonts, etc.)
    svg                 Create standalone SVG files for one or more
                        applications

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
```
I'm running bokeh 0.12.13 and Python 3.6, from a standard Anaconda installation.

**Comment by mattpap** [comment]
Use `bokeh serve --help`.

**Comment by aweinstein** [comment]
@mattpap Thanks. So perhaps saying something like "See 'bokeh <command> --help' to read about a specific subcommand'" (inspiration from `git --help`) when running `bokeh --help` might be clearer?

**Comment by bryevdv** [comment]
@aweinstein AFAIK this kind of setup for `--help` for commands with subcommands is fairly typical, but certainly often good to be as explicit as possible. If you'd like to submit a PR to set `parser.description` or `parser.usage` here:

https://github.com/bokeh/bokeh/blob/master/bokeh/command/bootstrap.py#L55

We'd be happy to have your contribution.

**Comment by mattpap** [comment]
@bryevdv, I already created a PR.

**Comment by aweinstein** [comment]
Thanks @mattpap and @bryevdv for looking into this.
