### ISSUE TITLE
Bokeh 0.12.15 throws TypeError on Touch Devices when dragging

### ISSUE THREAD

**Issue by rbu** [bokeh/bokeh#7801]
* python: 2.7.14
* Bokeh 0.12.15
* Browser: Mobile Safari 11.3/11.4 on iPad or iPhone

#### Description of expected behavior and the observed behavior
We're rendering a basic line plot with bokeh. This worked fine in 0.12.14 and before. After upgrading to 0.12.15, it starts throwing errors when I touch the graph:

```TypeError: undefined is not an object (evaluating 'e.pageX')```

The code responsible was introduced in 675aacf72a:
```js
  protected _get_sxy(event: TouchEvent | MouseEvent | PointerEvent): {sx: number, sy: number} {
    // XXX: jsdom doesn't support TouchEvent constructor
    function is_touch(event: TouchEvent | MouseEvent | PointerEvent): event is TouchEvent {
      return typeof TouchEvent !== "undefined" && event instanceof TouchEvent
    }
    const {pageX, pageY} = is_touch(event) ? event.touches[0] : event // XXX: assuming at last one touch
...
```

@dwt debugged this down to the event being a `TouchEvent`, but its `touches` array has length 0. A safer way to access the page offsets can be seen in [Waves.js](https://github.com/fians/Waves/blob/master/src/js/waves.js#L129)

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by mattpap** [comment]
> A safer way to access the page offsets can be seen in Waves.js

This code isn't correct either, at last according to specification.

**Comment by dwt** [comment]
Can't reproduce the issue with this change applied.
