### ISSUE TITLE
Findable and tunable html error boxes please

### ISSUE THREAD

**Issue by varhub** [bokeh/bokeh#7802]
It's pretty difficult to do anything useful with bokeh errors like raised by `_burst_into_flames` when it declares an anonymous div element.

Here you are a graphical example of a webpage with navbars:

![image](https://user-images.githubusercontent.com/5702557/38885435-2c1b2a30-4273-11e8-87ea-c5e1dd7070b3.png)
```
<div style="background-color: rgb(242, 222, 222);border: 1px solid rgb(169, 68, 66);border-radius: 4px;display: inline-block;font-family: sans-serif;margin-top: 5px;min-width: 200px;padding: 5px 5px 5px 10px;"><span title="close" aria-label="close" style="background-color: rgb(169, 68, 66); border-radius: 0px 4px 0px 0px; color: white; cursor: pointer; float: right; font-size: 0.8em; margin: -6px -6px 0px 0px; padding: 2px 5px 4px;">x</span><h3 style="color: rgb(169, 68, 66); margin: 8px 0px 0px; padding: 0px;">Bokeh Error</h3><pre style="white-space: unset; overflow-x: auto;">attempted to retrieve property array for nonexistent field 'pinkkk'</pre></div>
```

Implied code is at https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/safely.ts#L6 and will be extremelly useful that it includes css class.

Pull request attempt can be found here: https://github.com/varhub/bokeh/pull/1
It is my first PR here, so let me known what do you need to close this issue.

**Comment by mattpap** [comment]
We sure can add a CSS class that would act as a handle. However, this particular error box was introduced for critical errors that would otherwise leave a user with an empty screen and errors in JS console. Usage errors, like in this case, should have been handled earlier (preferably in bokeh's Python API) and definitively more gracefully.

**Comment by bryevdv** [comment]
@varhub We'd love to have a PR from. Just to note, you have made that PR against your own fork of the repo. For us to merge it, you'll need to make a new PR from your branch, to the master branch of *this* repo.

**Comment by varhub** [comment]
@mattpap , I agree with you. However I reached it because I'm using [embed#components](https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#components).
Perhaps I only need to check plot syntax at python side. Do you known if there is a way to check plot before or inside *embed* method?

Yes @bryevdv , I did a temporary PR because issue was not created and leack ticket ID at PR neither branch name. Guessing that PR is ok, so I will create it ;)
