### ISSUE TITLE
surface3d example color fixed to z axis

### ISSUE THREAD

**Issue by dfudge1977** [bokeh/bokeh#7814]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python version 2.7.13
Anaconda2 Distribution 4.4.0 Community Edition
Bokeh version 0.12.5
nodejs version 9.11.0
Windows 8.1 Pro (Build 9600)
Chrome Version 65.0.3325.181 (Official Build) (64-bit) 

#### Description of expected behavior and the observed behavior
Trying to set the surface color to something other than the z axis values but the surface color does not change.

#### Complete, minimal, self-contained example code that reproduces the issue

Example was:
```
value = np.sin(xx/50) * np.cos(yy/50) * 50 + 50
source = ColumnDataSource(data=dict(x=xx, y=yy, z=value, color=value))
surface = Surface3d(x="x", y="y", z="z", color="color", data_source=source, width=600, height=600)
```

Example Updated to:
```
value = np.sin(xx/50) * np.cos(yy/50) * 50 + 50
color = np.linspace(0, 1, value.shape[0])
source = ColumnDataSource(data=dict(x=xx, y=yy, z=value, color=color))
surface = Surface3d(x="x", y="y", z="z", color="color", data_source=source, width=600, height=600)
```

#### Screenshots or screencasts of the bug in action
The image looks like the following regardless of what the 'color' argument is set to.
![image](https://user-images.githubusercontent.com/38538452/39009900-f300c340-43da-11e8-96e8-76ce91995a21.png)

**Comment by bryevdv** [comment]
Looks like the example in the docs will need updating as well. 

https://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/wrapping.html
