### ISSUE TITLE
Rendering occurs on mouse move when hover tools is enabled

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#7819]
It looks like a recent regression, but I didn't have a chance to track it yet. The problem is that hover tool updates inspection indices, which triggers code in CDSView, because it listens on `source.change` signal. `CDSView` then triggers code in `GlyphRenderer`, because it listens on `view.change`, and this causes rendering to happen on every mouse move.

**Comment by bryevdv** [comment]
Proximate cause seems to be https://github.com/bokeh/bokeh/pull/7617

**Comment by bryevdv** [comment]
Well, this is hard. Not responding to inspections brings back #7397

**Comment by bryevdv** [comment]
cc @clairetang6

**Comment by bryevdv** [comment]
I've reverted the other PR for now, so closing this.
