### ISSUE TITLE
BBoxTileSource Not Rendering WMS Imagery

### ISSUE THREAD

**Issue by mccarthyryanc** [bokeh/bokeh#7825]
I started a discussion on the [Google Group](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/qtIlSlad0og) and it was suggested I create bug post here.

I'm trying to add a BBoxTileSource in Bokeh where the imagery is exposed via WMS, so I'm testing against the USGS Topo [data](https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer). However, I am getting an `NS_ERROR_NOT_AVAILABLE` message from the Firefox console when I try to pan and zoom:
![image](https://user-images.githubusercontent.com/997120/39147184-d1989b4a-46ed-11e8-8cc6-8f2078f09b10.png)

Here is my app:
```python
#! /usr/bin/env python
import sys
import logging
from bokeh.plotting import figure
from bokeh.layouts import row
from bokeh.models import ColumnDataSource, Range1d, BBoxTileSource
from bokeh.io import curdoc

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

# USGS TOPO
url = ('https://basemap.nationalmap.gov/arcgis/services/'
       'USGSTopo/MapServer/WMSServer?service=WMS&'
       'request=GetMap&version=1.3.0&BGCOLOR=0xFFFFFF&&format=image/png&'
       'crs={crs}&layers={layer}&width={width}&height={height}')

# USGS Test
crs = 'EPSG:3857'
xmin = -8904681
ymin = 3863947
xmax = -8894269
ymax = 3870320

layer = '0'
width = 900
height = 600

url_set = url.format(crs=crs, width=width, height=height, layer=layer) + \
          '&bbox={XMIN},{YMIN},{XMAX},{YMAX}'

x_range = Range1d(start=xmin, end=xmax, bounds=None)
y_range = Range1d(start=ymin, end=ymax, bounds=None)
 
fig = figure(tools='wheel_zoom,pan',
              x_range=x_range,
              lod_threshold=None,
              plot_width=width,
              plot_height=height,
              background_fill_color='white',
              y_range=y_range,)

tile_source = BBoxTileSource(url=url_set)
fig.add_tile(tile_source)

# Some Testing glyphs
source = ColumnDataSource(
    data=dict(lat=[ymin, ymin, ymax, ymax ],
              lon=[xmin, xmax, xmin, xmax ])
)

fig.circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8,
           source=source)

layout = row(fig)
curdoc().add_root(layout)
curdoc().title = "WMS Viewer"
```

System Specs:
  * Ubuntu 16.04
  * python 3.6
  * Bokeh 0.12.15

Installed via conda:
```bash
conda create -n wms-env bokeh python=3.6 -c conda-forge
```

**Comment by brendancol** [comment]
@bryevdv @mccarthyryanc hey folks.  I do have a little bandwidth....I'll take a look and get back

**Comment by brendancol** [comment]
@mccarthyryanc  A couple of things to note:

- Looks like there was a missing `styles` parameter in your WMS url.  I believe this is required in WMS 1.3.0 (maybe before also).  If you don't know which `styles`, you can set it to an empty list.

- You probably want each tile to be 256x256 instead of 600x900 so you can benefit from updating only the edges of the map when panning.

- Removing axis labels is also a decent idea.

- Below is an screenshot of what your example looks like with changes

<img width="903" alt="screenshot 2018-04-26 08 14 53" src="https://user-images.githubusercontent.com/433221/39307992-f0fb69fc-4929-11e8-9ccf-5f68811676a9.png">

```python
import sys
import logging
from bokeh.plotting import figure
from bokeh.layouts import row
from bokeh.models import ColumnDataSource, Range1d, BBoxTileSource
from bokeh.io import curdoc

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

# USGS TOPO
url = ('https://basemap.nationalmap.gov/arcgis/services/'
       'USGSTopo/MapServer/WMSServer?service=WMS&'
       'request=GetMap&styles=&version=1.3.0&BGCOLOR=0xFFFFFF&&format=image/png&'
       'crs={crs}&layers={layer}&width={width}&height={height}')

# USGS Test
crs = 'EPSG:3857'
xmin = -8904681
ymin = 3863947
xmax = -8894269
ymax = 3870320

layer = '0'
width = 256
height = 256

url_set = url.format(crs=crs, width=width, height=height, layer=layer) + \
          '&bbox={XMIN},{YMIN},{XMAX},{YMAX}'

x_range = Range1d(start=xmin, end=xmax, bounds=None)
y_range = Range1d(start=ymin, end=ymax, bounds=None)

fig = figure(tools='wheel_zoom,pan',
              x_range=x_range,
              lod_threshold=None,
              plot_width=900,
              plot_height=600,
              background_fill_color='white',
              y_range=y_range,)
fig.axis.visible = False
fig.toolbar_location = 'above'

tile_source = BBoxTileSource(url=url_set)
fig.add_tile(tile_source)

# Some Testing glyphs
source = ColumnDataSource(
    data=dict(lat=[ymin, ymin, ymax, ymax ],
              lon=[xmin, xmax, xmin, xmax ])
)

fig.circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8,
           source=source)

layout = row(fig)
curdoc().add_root(layout)
curdoc().title = "WMS Viewer"
```

**Comment by brendancol** [comment]
@bryevdv @HuntJSparra @jbednar There was a proper WMS layer which I believe was part of Bokeh-Geo.  Was bokeh-geo ever open-sourced?  If so, where does it live?  I believe that layer extended `BBoxTileSource` and filled in the `styles` url param which was the source of the issue above.

**Comment by mccarthyryanc** [comment]
@brendancol thanks for the fix and tip on the tile width/height!

**Comment by jbednar** [comment]
No, nothing has happened on bokeh-geo in recent memory; it's still a work in progress.  Would certainly be nice for that to change!

**Comment by bryevdv** [comment]
@brendancol Thank you! I do not know that I would have never figured that out. I am afraid I don't know anything about bokeh-geo. I am going to go ahead and close this particular issue but if there are simply things we can do to improve what's in bokeh currently please open specific topic issues.
