### ISSUE TITLE
Incorrect datetime axis formatting on high zoom levels.

### ISSUE THREAD

**Issue by gardster** [bokeh/bokeh#7832]
Software versions:
python 3
bokeh versions: 0.12.15, 0.12.6
OS: Ubuntu, MacOS
Browser: safari, chrome

On observe zoom levels date suddenly jumps to 17 days forward.
![screen shot 2018-04-25 at 2 59 11 pm](https://user-images.githubusercontent.com/1862559/39244429-4f85ae7e-4899-11e8-988a-9323793e7226.png)
![screen shot 2018-04-25 at 2 59 26 pm](https://user-images.githubusercontent.com/1862559/39244439-537a1718-4899-11e8-8849-4f09650bb3d3.png)

Steps to reproduce:
1. run code below
2. Unzoom with the mouse wheel
3. Look at x-axis values

```
import bokeh.plotting as bp
from bokeh.models import DatetimeTickFormatter
from datetime import date

x = [date(2017,3,1), date(2017,3,2), date(2017,3,3), date(2017,3,4), date(2017,3,5), date(2017,3,6)]
y = [1, 2, 1, 2, 1, 2]

myPlot = bp.figure(height = 600,
               width = 800,
               x_axis_type = 'datetime',
               y_range=(0,3))
myPlot.xaxis[0].formatter = DatetimeTickFormatter(days='%b %d')
myPlot.circle(x, y, size = 25, color='red')
bp.output_file('bug.html', title = 'bug')
bp.show(myPlot)
```

**Comment by AzraelDD** [comment]
> On observe zoom levels date suddenly jumps to 17 days forward.

As a non-nativ speaker, maybe I simply do not understand your question/problem correctly, but:
- In the first plot you see points from "Mar 01" to "Mar 06". Here the number represents the day of the month.
- In the second plot you see a couple of points starting at "Mar17". In this label, which is written without the whitespace between month and number, the number represents the year. Therefore the label seems correct to me.

If this seems confusing to you, _maybe_ you can find a way to change the style of the label. You could start looking here: https://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#numeraltickformatter

**Comment by gardster** [comment]
Oh! Now I understand: `17` is not a day. It is last numbers of the year. So it is not a bug, but it looks pretty weird that Bokeh uses different formatter at some zoom levels when I'm explicitly set a formatter functions.

**Comment by bryevdv** [comment]
@gardster you only set the formatter for values in  "days" scale, if you want the same formatter across all scales you'll need to set them all. It might be helpful to have a function on `DatetimeTickFormatter` that does that, i.e. `formatter.set_all_scales('%b %d')`. I am going to go ahead and close this as `discussion` now but if you want to submit a PR for something like that we'd be happy to re-open and consider it.
