### ISSUE TITLE
html formatter has a small typo

### ISSUE THREAD

**Issue by jimbasquiat** [bokeh/bokeh#7840]
Have been trying to use the example for the html formatter template that is presented [here.](https://bokeh.pydata.org/en/latest/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.HTMLTemplateFormatter)

But the 'a' tags i was creating using that example were not working - see (resolved) SO questions [here](https://stackoverflow.com/questions/50086517/html-template-formatter-not-working) and [here](https://stackoverflow.com/questions/50086856/javascript-a-tag-incorrect-redirection). 

I found the solution though - Instead of 
<a href=”<%= url %>”><%= value %></a>
the template should be
<a href=<%= url %>><%= value %></a> 
(without the quotes around the url variable. - Those quote where creating a invalid adress.

I was encouraged by SO user BigRedDot to flag that issue here in the issue tracker.

**Comment by bryevdv** [comment]
Just to note, I believe the quotes *should* be there, but that they were getting rendered incorrectly as "fancy" start/end quote pairs instead of basic ascii quotes
