### ISSUE TITLE
It's not clear if poly select works until there are three points chosen

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#7847]
There should be some way to show chosen points before poly annotation appear. Otherwise I always have a feeling that the tool is broken.

**Comment by bryevdv** [comment]
I am not sure anyone uses this tool, I rather wish I'd never added it, but it's better to keep it at this point.

**Comment by bryevdv** [comment]
I would consider deprecating this tool for 2.0 cc @bokeh/dev

**Comment by bryevdv** [comment]
I plan to remove this in 2.0 unless there is someone else who wants to pick ip maintenance of this tool
