### ISSUE TITLE
x-axis with datetime doesn't dispaly correctly when hoovered on

### ISSUE THREAD

**Issue by dclong** [bokeh/bokeh#7857]
As the first screenshot shows that the x-axis is formatted correctly but the 2nd screenshot shows that mouse-hovering-on does display the datetime but rather a numeric value. 

![image](https://user-images.githubusercontent.com/824507/39610942-54c38458-4f86-11e8-9e1b-12e47133102b.png)
![image](https://user-images.githubusercontent.com/824507/39610956-6e7cf546-4f86-11e8-954a-0492c77d5274.png)

And below is the code to generated the plot. 
```
from bokeh.plotting import figure, output_notebook, show
import numpy as np
output_notebook()

p = figure(
    title = 'Impression ...', 
    x_axis_label = 'Date', 
    x_axis_type = 'datetime',
    y_axis_label = 'Number of Impressions (K)', 
    tools = 'hover,pan,wheel_zoom,box_zoom,reset,previewsave'
)
p.line(imprsn_spc.imprsn_dt, imprsn_spc.num_imprsn/1E3, line_color = 'blue')

show(p)
```

**Comment by bryevdv** [comment]
You need to apply a datetime formatter as described in the docs:

https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields
