### ISSUE TITLE
Update docstring for on_change

### ISSUE THREAD

**Issue by imiu** [bokeh/bokeh#7860]
#### Update documentation

Update docstrings in the snippet below (https://github.com/bokeh/bokeh/blob/master/bokeh/model.py#L404) to make it clear that handler is able to support multiple callback functions. Ex: `widget.on_change('value', callback1, callback2, ..., callback_n)`

```
    def on_change(self, attr, *callbacks):
        ''' Add a callback on this object to trigger when ``attr`` changes.
        Args:
            attr (str) : an attribute name on this object
            callback (callable) : a callback function to register
        Returns:
            None
        '''

```

**Comment by bryevdv** [comment]
@imiu setting expectations, do you intend to submit a PR for this?
