### ISSUE TITLE
Major Label Overrides not accepting dictionary 

### ISSUE THREAD

**Issue by andre-vauvelle** [bokeh/bokeh#7884]
#### Description of expected behavior and the observed behavior
When overriding ticks I'm unable to pass a dict unless wrapping in eval(str()).

Although I found a fix I'm kinda curious why this is happening... Newbie coder 👍 
#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.layouts import row
from bokeh.plotting import figure, show, output_file

factors = range(0,4)
labels = ['Ed', 'Jon', 'Christian', 'Ed']
x =  [50, 40, 65, 10]

dot = figure(title="Categorical Dot Plot", tools="", toolbar_location=None,
            y_range=[0-1,max(factors)+1], x_range=[0,100])

dot.segment(0, factors, x, factors, line_width=2, line_color="green", )
dot.circle(x, factors, size=15, fill_color="orange", line_color="green", line_width=3, )

factor_labels = dict(zip(factors, labels))
dot.yaxis.major_label_overrides = factor_labels
#dot.yaxis.major_label_overrides = eval(str(factor_labels))
```
Gives 

#### Stack traceback and/or browser JavaScript console output
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-224-fea246dbd58f> in <module>()
----> 1 show(dot)

~\Anaconda3\lib\site-packages\bokeh\util\api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

~\Anaconda3\lib\site-packages\bokeh\io\showing.py in show(obj, browser, new, notebook_handle, notebook_url)
    135     if obj not in state.document.roots:
    136         state.document.add_root(obj)
--> 137     return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
    138 
    139 #-----------------------------------------------------------------------------

~\Anaconda3\lib\site-packages\bokeh\io\showing.py in _show_with_state(obj, state, browser, new, notebook_handle)
    162 
    163     if state.notebook:
--> 164         comms_handle = run_notebook_hook(state.notebook_type, 'doc', obj, state, notebook_handle)
    165         shown = True
    166 

~\Anaconda3\lib\site-packages\bokeh\util\api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

~\Anaconda3\lib\site-packages\bokeh\io\notebook.py in run_notebook_hook(notebook_type, action, *args, **kw)
    294     if _HOOKS[notebook_type][action] is None:
    295         raise RuntimeError("notebook hook for %r did not install %r action" % notebook_type, action)
--> 296     return _HOOKS[notebook_type][action](*args, **kw)
    297 
    298 #-----------------------------------------------------------------------------

~\Anaconda3\lib\site-packages\bokeh\util\api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

~\Anaconda3\lib\site-packages\bokeh\io\notebook.py in show_doc(obj, state, notebook_handle)
    506     from ..embed.notebook import notebook_content
    507     comms_target = make_id() if notebook_handle else None
--> 508     (script, div, cell_doc) = notebook_content(obj, comms_target)
    509 
    510     publish_display_data({HTML_MIME_TYPE: div})

~\Anaconda3\lib\site-packages\bokeh\util\api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

~\Anaconda3\lib\site-packages\bokeh\embed\notebook.py in notebook_content(model, notebook_comms_target, theme)
     83     # has models with the same IDs as they were started with
     84     with _ModelInEmptyDocument(model, apply_theme=theme) as new_doc:
---> 85         (docs_json, render_items) = standalone_docs_json_and_render_items([model])
     86 
     87     item = render_items[0]

~\Anaconda3\lib\site-packages\bokeh\util\api.py in wrapper(*args, **kw)
    188         @wraps(obj)
    189         def wrapper(*args, **kw):
--> 190             return obj(*args, **kw)
    191 
    192         wrapper.__bkversion__ = version

~\Anaconda3\lib\site-packages\bokeh\embed\util.py in standalone_docs_json_and_render_items(models)
    228     docs_json = {}
    229     for k, v in docs_by_id.items():
--> 230         docs_json[k] = v.to_json()
    231 
    232     return (docs_json, render_items)

~\Anaconda3\lib\site-packages\bokeh\document\document.py in to_json(self)
    779         # this is a total hack to go via a string, needed because
    780         # our BokehJSONEncoder goes straight to a string.
--> 781         doc_json = self.to_json_string()
    782         return loads(doc_json)
    783 

~\Anaconda3\lib\site-packages\bokeh\document\document.py in to_json_string(self, indent)
    808         }
    809 
--> 810         return serialize_json(json, indent=indent)
    811 
    812     def validate(self):

~\Anaconda3\lib\site-packages\bokeh\core\json_encoder.py in serialize_json(obj, pretty, indent, **kwargs)
    211         indent = 2
    212 
--> 213     return json.dumps(obj, cls=BokehJSONEncoder, allow_nan=False, indent=indent, separators=separators, sort_keys=True, **kwargs)

~\Anaconda3\lib\json\__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 
    240 

~\Anaconda3\lib\json\encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

~\Anaconda3\lib\json\encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

TypeError: keys must be a string

**Comment by bryevdv** [comment]
Your code works as-is for me on master with no errors:

<img width="224" alt="screen shot 2018-05-10 at 08 08 42" src="https://user-images.githubusercontent.com/1078448/39876924-61124076-5429-11e8-871a-5190635e30ab.png">

If there ever was a big, it's been fixed since (your issue did not state any version info, please **always** provide version info)

In any case there is no reason to do things this way, Bokeh has built-in support for real categorical factors:

https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html
