### ISSUE TITLE
Exporting DataTable to png broken

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#7885]
Using bokeh master it appears that exporting a DataTable to png is broken. This appears to be a regression in 0.12.16 as it's working in 0.12.15. Here is a minimal reproducible example:

```python
from bokeh.io import export_png
from datetime import date
from random import randint

from bokeh.io import output_file, show
from bokeh.layouts import widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

output_file("data_table.html")

data = dict(
        dates=[date(2014, 3, i+1) for i in range(10)],
        downloads=[randint(0, 100) for i in range(10)],
    )
source = ColumnDataSource(data)

columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280)

export_png(data_table, filename="table.png")
```

>UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffd' in position 879408: ordinal not in range(256)

**Comment by bryevdv** [comment]
Can you narrow it down to a last working dev build?

**Comment by mattpap** [comment]
Also, what version of Python and what platform do you use? I can't reproduce anything in Python 2/3 on Linux. Additionally, can you show the full traceback. Having only the last bit doesn't really help with determining what's the origin of this error.

**Comment by mattpap** [comment]
Actually, I can reproduce on Python 3, just with development mode disabled (I presume inline resources are the problem):
```
Traceback (most recent call last):
  File "some17.py", line 22, in <module>
    export_png(data_table)
  File "/home/mateusz/repos/bokeh/bokeh/io/export.py", line 80, in export_png
    image = get_screenshot_as_png(obj, height=height, width=width, driver=webdriver)
  File "/home/mateusz/repos/bokeh/bokeh/io/export.py", line 175, in get_screenshot_as_png
    file.write(b(html))
  File "/home/mateusz/miniconda/envs/bk3/lib/python3.6/site-packages/six.py", line 626, in b
    return s.encode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffd' in position 879897: ordinal not in range(256
```

**Comment by mattpap** [comment]
Digging a bit in embed code, I realized that `html_file()` used in `export_png()` produces a UTF-8 encoded string, well sort of due to this function:

https://github.com/bokeh/bokeh/blob/fa1face4fe5f83d835436ffddc96ed62ba67b4a9/bokeh/util/string.py#L8-L21

This function either does a transform `unicode -> str` on Python 2 or `str -> str` on Python 3. It should, however, do `str -> bytes` transform on Python 3. What am I missing, because this seems obviously wrong and then causes all sorts of issues down the pipe?

If remove encoding from `file_html()` (`html_page_for_render_items()` to be specific) and then use `f = io.open(filename, mode="w", encoding="utf-8"); f.write(html)` for saving generated HTML, then this works reliably on both Python 2 and 3.

**Comment by mattpap** [comment]
> Regarding the function itself, I'm not sure, it has been in use for years.

bokeh.embed, bokeh.io and bokeh.server heavily depend on it. So far I removed 15 instances for the purpose of testing alternative approaches.

**Comment by philippjfr** [comment]
Sorry for the incomplete traceback and thanks for tracking down the issue. I'm not sure if it's related but the escaping of the INLINED resources also seems to have changed, seems like that could at least in theory account for the differences.

**Comment by philippjfr** [comment]
I'm still tracking it down, but when I build the holoviews docs using bokeh master I'm currently seeing the INLINE JS appearing unescaped, which appears to break things completely, e.g. I'm seeing HTML less than (``&lt;``) or unescaped quotes show up, which means the JS won't parse. We're already switching to a better system which doesn't have these issue I think, so it's not critical, but something does appear to have changed.

**Comment by bryevdv** [comment]
@philippjfr that actually seems very worrisome, if you can help track it down I think that would be very valuable

**Comment by philippjfr** [comment]
>I do think a bisection would help inform the appropriate immediate-term response

I'll try to track it down.

**Comment by bryevdv** [comment]
@philippjfr Can you detail the process to evaluate builds for this difference? I'd like to do a bisection today, but I need to know what to look for.

**Comment by bryevdv** [comment]
It's not actually inline vs cdn, it's minified vs non-minified

**Comment by philippjfr** [comment]
>It's not actually inline vs cdn, it's minified vs non-minified

Is that for the original bug or the other issue? I'll have a go at figuring out when that happened now.

**Comment by bryevdv** [comment]
> Is that for the original bug or the other issue? I'll have a go at figuring out when that happened now.

That's for the original bug. I think the PR I just pushed handles that in a minimal way (tho please check it out on your code). What I am most interested in now is the "unescaped" output: where and how it occurs, and when it started.

**Comment by philippjfr** [comment]
Okay, I must have done something else wrong during that build where the inline JS wasn't escaped, I just did a full bisect between 0.12.15 and current master and couldn't reproduce the issue again.

**Comment by bryevdv** [comment]
@philippjfr OK, thanks for doing this, I was worried about something being foundationally broken somehow right before release. Can you check the PR? I made one more push but I think it is ready now
