### ISSUE TITLE
plot & sliders do not work in bokeh.embed

### ISSUE THREAD

**Issue by KriegReisfeld** [bokeh/bokeh#7888]
The following is python code to embed slider.py of examples in html.
Although plot and slider are displayed on a browser, they do not cooperate.

`import numpy as np`
`from bokeh.embed import components`
`from bokeh.util.browser import view`
`from bokeh.resources import INLINE`
`from bokeh.io import curdoc`
`from bokeh.layouts import row, widgetbox`
`from bokeh.models import ColumnDataSource`
`from bokeh.models.widgets import Slider, TextInput`
`from bokeh.plotting import figure`
`from jinja2 import Template`

`# Set up data`
`N = 200`
`x = np.linspace(0, 4*np.pi, N)`
`y = np.sin(x)`
`source = ColumnDataSource(data=dict(x=x, y=y))`
`# Set up plot`
`plot = figure(plot_height=400, plot_width=400, title="my sine wave",`
`tools="crosshair,pan,reset,save,wheel_zoom", x_range=[0, 4*np.pi], y_range=[-2.5, 2.5])`
`plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)`

`# Set up widgets`
`text = TextInput(title="title", value='my sine wave')`
`offset = Slider(title="offset", value=0.0, start=-5.0, end=5.0, step=0.1)`
`amplitude = Slider(title="amplitude", value=1.0, start=-5.0, end=5.0, step=0.1)`
`phase = Slider(title="phase", value=0.0, start=0.0, end=2*np.pi)`
`freq = Slider(title="frequency", value=1.0, start=0.1, end=5.1, step=0.1)`

`# Set up callbacks`
`def update_title(attrname, old, new):`
    `plot.title.text = text.value`

`text.on_change('value', update_title)`

`def update_data(attrname, old, new):`
    
   ` # Get the current slider values`
   ` a = amplitude.value`
    `b = offset.value`
    `w = phase.value`
   ` k = freq.value`
    
    # Generate the new curve
    x = np.linspace(0, 4*np.pi, N)
    y = a*np.sin(k*x + w) + b

    source.data = dict(x=x, y=y)

`for w in [offset, amplitude, phase, freq]:`
    `w.on_change('value', update_data)`

`# Set up layouts and add to document`
`inputs = widgetbox(text, offset, amplitude, phase, freq)`

`curdoc().add_root(row(inputs, plot, width=800))`
`curdoc().title = "Sliders"`

`# Get JavaScript/HTML resources`
`script, (div1, div2) = components((plot, inputs))`
`js_resources = INLINE.render_js()`
`css_resources = INLINE.render_css()`

`template = Template('''<!DOCTYPE html>`
    `<html lang="en">`
   ` <head>`
   ` <meta charset="utf-8">`
    `<title>Widget</title>`
   ` {{ js_resources }}`
    `{{ css_resources }}`
   ` </head>`
   ` <body>`
    `{{ div1 }}`
    `{{ div2 }}`
    `{{ script }}`
   ` </body>`
    `</html>`
    `''')`

``filename = 'widget.html'``

`html = template.render(js_resources=js_resources,`
                       `css_resources=css_resources,`
                       `script=script,`
                      ` div1=div1, div2=div2)`

`with open(filename, 'w') as f:`
   ` f.write(html)`

**Comment by bryevdv** [comment]
@KriegReisfeld when you embed with `components`, you are making a *standalone* Bokeh doc that is only HTML and JS. If you want to have *real Python callbacks*, i.e. `on_change` instead of `js_on_change` then this will not work, because viewers web browsers have no capability to execute python code. TO do this you have to run your code as an app on the Bokeh server. For more information, see:

https://bokeh.pydata.org/en/latest/docs/user_guide/server.html
