### ISSUE TITLE
Step Glyph Support for Gaps from Missing/Non-Finite Data Points (inf, nan)

### ISSUE THREAD

**Issue by nathanielatom** [bokeh/bokeh#7890]
Similar to the missing data points support for `line` and `multi_line` glyphs.

Complete, minimal, self-contained example code:
```
from bokeh.plotting import figure, output_file, show
p = figure(plot_width=400, plot_height=400)

# add a line renderer with a NaN
nan = float('nan')
p.step([1, 2, 3, nan, nan, 8, 9, 10], 
            [6, 7, 2, nan, nan, 4, 5, 7], line_width=2)

show(p)
```

<details><summary>observed behaviour</summary>

![step_nan](https://user-images.githubusercontent.com/3137319/39888997-9d0e4b3e-5464-11e8-9ee4-a6098e08fbc6.png)
 * the `before` mode is shown here, but there's similar output for all modes
 * this sample code uses `float('nan')`, but the same behaviour is observed with `numpy.nan`, `float('inf')`, and `numpy.inf`.

</details>

#### Desired Behaviour
is for the diagonal line segment to be absent in this example. More generally, any `inf` and `nan` data points should show as a gap in the stepped line. The start and stop of the gap should be consistent with the `mode`.

<details><summary>bokeh info</summary>
<p>

Python version      :  3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:54:01) 
IPython version     :  6.3.1 
Bokeh version       :  0.12.15 
BokehJS static path :  /Users/Atom/.anaconda/envs/py3/lib/python3.6/site-packages/bokeh/server/static 
node.js version     :  v10.0.0 
npm version         :  5.6.0 

</p>
</details>

**Comment by nathanielatom** [comment]
I don't have any TypeScript experience, but from looking at the source for [line](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/glyphs/line.ts) and [step](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/glyphs/step.ts), it looks like there would need to be some logic in `_render` that uses `isFinite` and tracks a `drawing` state. If there's interest, I could tackle a PR with some guidance.

**Comment by nathanielatom** [comment]
Hi @bryevdv, I followed the dev guide, it was pretty straightforward for the most part. I ran into #7854 when building, and #7897, #7898, #7899, and #7900 when running the tests. Currently I have all the tests passing locally except for the example and integration tests.

To try out whether my local changes have any effect, I made some naive edits to step.ts and managed to generate the following plot:

![bokeh_plot 42](https://user-images.githubusercontent.com/3137319/39984991-eef0ed94-572a-11e8-8cf1-8d1e3ff942ae.png)

I'm pretty sure it still doesn't handle the general case / other `mode`'s yet though, since like you said that's probably a little more complicated.

**Comment by nathanielatom** [comment]
I also have a question: what's the purpose of `last_index` in line.ts? I can't figure out why or when this code block executes: 
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/glyphs/line.ts#L35
Is it related to `nan` support?

**Comment by bryevdv** [comment]
Fairly sure that when LOD (Level-of-Detail) downsampling is occurring during interactive events is happening, that will cause the (non-adjacent) decimated points to be connected
