### ISSUE TITLE
Dev how to: Develop/extend bokehjs

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [bokeh/bokeh#7894]
Currently the documentation on developing bokehjs is a bit lacking. Let's collect some things that could be written down for new devs:

- Maybe some general guidance how to set up a quick sane TypeScript dev environment (Might be outside the scope, maybe some links to existing how-to's?)
- How to build using 'gulp'
- How to run standalone BokehJS tests/examples in TypeScript
- How to use the build BokehJS in python tests/examples.

**Comment by mattpap** [comment]
The documentation has been gradually improved, especially recently (e.g. PR #11513). Any new concerns about the build, testing, etc. processes should be submitted as new issues.
