### ISSUE TITLE
All gallery examples bundle unnecessary extension code

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#7905]
All the gallery examples have the code for ion range slider, surface3d, etc. Perhaps we will need to run every export for the gallery in a separate process to avoid this. Alternatively, is there an easy way to clear out any custom models that the sphinx extension could do between exports?

cc @mattpap

**Comment by bryevdv** [comment]
just running an `output_file`/`show` type example does not include everything, so I think this problem is specific to `autoload_server`, and possibly `components` since it also uses `bundle_all_models`

**Comment by mattpap** [comment]
This sounds correct. We include all bundles when we can't predict what will be used.
