### ISSUE TITLE
Tile source attribution font size

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#7908]
Would it be possible to reduce the default font size on the [attributions for tile sources](https://github.com/bokeh/bokeh/blob/a0572fa40c3a59b72ba56a8c300e0ad06a044a23/bokeh/models/tiles.py)?

![image](https://user-images.githubusercontent.com/1695496/40062037-e05bceca-581f-11e8-87b6-75dac06cfc3f.png)

Seems like it just needs to be barely readable, while the current size is overwhelming for smaller plots.  Maybe 30% of the tick label size would work?

**Comment by bryevdv** [comment]
30% of the *default* tick label size? I don't think the font should vary based on user-configured tick label size. In any case sure, happy to merge a PR.

**Comment by jbednar** [comment]
Looks like it's set to 9pt right now:

https://github.com/bokeh/bokeh/blob/a0572fa40c3a59b72ba56a8c300e0ad06a044a23/bokehjs/src/coffee/models/tiles/tile_renderer.coffee#L50

If that's 9pt, then maybe 4pt?

**Comment by bryevdv** [comment]
I don't really have a strong opinion here, so am happy to change to whatever works for you.
