### ISSUE TITLE
Bokeh plot doesn't display in notebook on another machine

### ISSUE THREAD

**Issue by benlindsay** [bokeh/bokeh#7909]
When I generate a simple plot in a Jupyter Notebook like so:

```
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook()
p = figure(plot_width=400, plot_height=400)
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=15, line_color="navy", fill_color="orange", fill_alpha=0.5)
show(p)
```

I can close the notebook and reopen it, and the bokeh plot will be visible without running the notebook. I can move the notebook to anywhere else on the same machine, open the Jupyter notebook, and see the plot without running the notebook. Now if I scp that same notebook to a different machine (copying between a Linux machine and a Mac) and open the Jupyter notebook, I just see `Loading BokehJS ...` and there's no plot. The same thing happens even with inline resources like

```
from bokeh.resources import INLINE
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook(resources=INLINE)
```

If I run the notebook from the command line with `jupyter nbconvert` I also get a notebook with just `Loading BokehJS ...`. Is there a way to prevent the plot from disappearing? I don't understand why a notebook that would display a graph immediately on opening it would not display the same graph if it's on another machine.

Here are some (maybe) useful specs:

### Linux machine:

```
bokeh                     0.12.15                  py36_0
...
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36he59e554_1
jupyter_core              4.4.0            py36h7c827e3_0
jupyterlab                0.32.0                   py36_0
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
...
python                    3.6.4                hc3d631a_3
```

### OSX 10.12.1

```
bokeh                     0.12.15                  py36_0
...
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.2                    py36_0
jupyter_console           5.2.0            py36hccf5b1c_1
jupyter_core              4.4.0            py36h79cf704_0
jupyterlab                0.32.0                   py36_0
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
...
python                    3.6.4                hc167b69_1
```

### Browser:
Google Chrome Version 66.0.3359.170 (Official Build) (64-bit)

**Comment by benlindsay** [comment]
Wow, thank you for such a fast response! I missed that section when learning Bokeh, and it seems to be in a pretty prominent and logical place, so that's all on me. I'm glad the solution to my problem is so simple though. Thanks for all your work on this package! It's great.

**Comment by bryevdv** [comment]
Thanks for the kind words!
