### ISSUE TITLE
Code quality tests fail due to pandas' regression

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#7916]
See https://github.com/pandas-dev/pandas/issues/21071. I will pin pandas to version 0.22 for now.

**Comment by stonebig** [comment]
problem is there again with pandas-0.23.3 (from cgohlke).

**Comment by stonebig** [comment]
remark: I still have the "loosing my outliers" issue on Python-3.7.0 / numba-0.39.0  windows 64 bit (cgohlke compilation, not anaconda).
