### ISSUE TITLE
Different behavior between Bokeh and BokehJS with AjaxDataSource

### ISSUE THREAD

**Issue by jburgy** [bokeh/bokeh#7933]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Tested with bokeh 0.12.16 in chrome 64 on win7

#### Description of expected behavior and the observed behavior

AjaxDataSource behaves differently when document is created in JavaScript or in python.  My investigation revealed an order of operations issue.  The Bokeh.Plotting api calls .finalize() on a default CDSView instance.  As a consequence the CDSView indices are not properly recomputed when source.data updates.

#### Complete, minimal, self-contained example code that reproduces the issue

My MCVE replaces lines 8-20 and 27 of [ajax_source.py](https://github.com/bokeh/bokeh/blob/master/examples/howto/ajax_source.py) by the below javascript

```javascript
const source = new Bokeh.AjaxDataSource({data_url: "http://localhost:5050/data", polling_interval: 100});
const p = Bokeh.Plotting.figure({height: 300, width: 800,
    background_fill_color: "lightgrey", title: "Streaming Noisy sin(x) via Ajax"});

p.circle({field: 'x'}, {field: 'y'}, {source: source});
p.x_range.follow = "end";
p.x_range.follow_interval = 10;

Bokeh.Plotting.show(p, document.currentScript.parentElement)
```
First discussed [here](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/iUOrabQuKsg)

**Comment by mattpap** [comment]
This was fixed in PR #8696.
