### ISSUE TITLE
Using on_event with string names in Python2.7

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [bokeh/bokeh#7935]
As discovered in #7893, trying to set `on_event` with a string (i.e. `"tap"` instead of `events.Tap`) currently fails with:

``` python
=================================== FAILURES ===================================
 Test_standalone_docs_json_and_render_items.test_log_warning_if_python_event_callback 
self = <bokeh.embed.tests.test_util.Test_standalone_docs_json_and_render_items object at 0x7f6f7a9a5950>
caplog = <_pytest.logging.LogCaptureFixture object at 0x7f6f7a9a57d0>
    def test_log_warning_if_python_event_callback(self, caplog):
        d = Document()
        m1 = EmbedTestUtilModel()
        c1 = _GoodEventCallback()
        d.add_root(m1)
    
>       m1.on_event('tap', c1)
bokeh/embed/tests/test_util.py:155: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = EmbedTestUtilModel(id='b0037dfa-87fa-48d7-82ea-df2b14d2aff4', ...)
event = 'tap'
callbacks = (<bokeh.embed.tests.test_util._GoodEventCallback object at 0x7f6f7a9a5d90>,)
    def on_event(self, event, *callbacks):
>       if not isinstance(event, str) and issubclass(event, Event):
E       TypeError: issubclass() arg 1 must be a class
bokeh/util/callback_manager.py:31: TypeError
```

We should:
- [ ] Add tests that check setting `on_event` with a string
- [ ] Fix `bokeh/util/callback_manager.py` to accept strings in Python2.7

**Comment by bryevdv** [comment]
Hrmm well now I am confused, there are already lots of tests in `bokeh/util/tests/test_callback_manager.py` that already use string event names and also pass on py 2.7 currently

**Comment by mattpap** [comment]
> well it's unicode if the test is in the test_util.py file

Why is that? Anyway, using `six.string_types` is the right thing to do.

**Comment by bryevdv** [comment]
> Why is that? Anyway, using six.string_types is the right thing to do.

I expect the `# -*- coding: utf-8 -*- ` in `bokeh.models.glyphs` affects anything that imports any model (including this test, but not the other)

**Comment by mattpap** [comment]
> I expect the `# -*- coding: utf-8 -*-` in bokeh.models.glyphs (...)

I see. It's still needed on 2.x due to `Bézier` in a docstring.
