### ISSUE TITLE
ResetTool doesn't restore initial plot when using WMTSTileSource and x/y_range

### ISSUE THREAD

**Issue by lgasnier** [bokeh/bokeh#7936]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 0.12.16
python 3.6.4
OS linux
browser Firefox, Chrome

#### Description of expected behavior and the observed behavior
ResetTool doesn't restore initial plot when using WMTSTileSource and x/y_range.
Therefore, the match aspect is not preserved.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure
from bokeh.models.tiles import WMTSTileSource
from bokeh.io import show
from bokeh.io import output_file

output_file("test_tilesource_reset.html")

xmin = 200000
xmax = 200000 + 1000000
ymin = 5000000
ymax = 5000000 + 1000000

p = figure(width=500, height=700,
           x_range=(xmin, xmax),
           y_range=(ymin, ymax),
           tools="pan,wheel_zoom,reset")
p.axis.visible = False

wmts = WMTSTileSource(url="http://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png")
p.add_tile(wmts)

p.quad(top=[ymax], bottom=[ymin], left=[xmin],
       right=[xmax], color="#B3DE69", alpha=0.5)
show(p)
```

**Comment by philippjfr** [comment]
Thanks for filing this, this was on my to-do list to file as well. The cause of this is that the tile source enforces an equal aspect ratio and if your initial extent does not match it will reset to the originally supplied extent not the extent that the tile source set. I would argue that the tile source should update the initial extents to avoid this issue, but @bryevdv should chime in too.

**Comment by bryevdv** [comment]
Sounds good to me if that's what you'd like to implement.

**Comment by philippjfr** [comment]
>Sounds good to me if that's what you'd like to implement.

Okay great, I'll do that.
