### ISSUE TITLE
Column selection, instead of row selection, for a widget box table

### ISSUE THREAD

**Issue by bobleeswaggs** [bokeh/bokeh#7943]
Selection of columns, instead of rows, in a widget box table would be a great feature. Since a lot of the data inserted into plots comes from pandas dataframes or dictionaries, its natural to see lines (or bars, dots, etc.) as columns in a table, rather than rows. Selection of the columns could then highlight / mute that line or other lines for clear visibility in a linked plot, or various other callback functions in someones code.

I  previously posted to StackOverflow with questions on how to implement this (if available), and was directed to some CustomJS code which, with some tampering, would work for all applications. However, I was also recommended to post it here, as I may not be the only person looking for a solution to this.

**Comment by bryevdv** [comment]
@bobleeswaggs can you add a link that references the SO discussion?

**Comment by bryevdv** [comment]
Closing inactive discussion
