### ISSUE TITLE
Selected indices are not repainted if they are updated on the python side

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#7944]
When `source.selected.indices` is updated in python side the figure is not repainted. Check the button callback

    from bokeh.io import curdoc
    from bokeh.models import ColumnDataSource
    from bokeh.plotting import figure
    from bokeh.layouts import column
    from bokeh.models.tools import LassoSelectTool, TapTool
    from bokeh.models.widgets.buttons import Button
    from bokeh.models.callbacks import CustomJS

    source = ColumnDataSource(dict(
        x=[1, 2, 3, 4, 5, 6],
        y=[1, 2, 3, 4, 5, 6],
    ))

    p = figure(
        plot_height=300,
        tools='',
    )
    p.circle( x='x', y='y', size=20, source=source)

    lasso_select = LassoSelectTool(
        select_every_mousemove=False,
    )
    tap = TapTool()
    tools = (lasso_select, tap)
    p.add_tools(*tools)

    def update_selection_programmatically():
        source.selected.update(indices=[4])           # indices is updated but the update event (source.change.emit();) is not triggered
                                                      # the figure is not repainted and the points are not marked as selected
    bt = Button(
        label="Update Selection",
        button_type="success",
        width=50
    )

    bt.on_click(update_selection_programmatically)

    # this works fine

    # bt.callback = CustomJS(
    #     args=dict(source=source),
    #     code="""
    #         source.selected.indices = [4];
    #         source.change.emit();
    #     """
    # )

    def update_selection(attr, old, new):
        print('>> NEW SELECTION: {}'.format(new.indices))
        # new.indices = [0]       # this works fine here

    source.on_change('selected', update_selection)

    curdoc().add_root(column([p, bt]))

**Comment by bryevdv** [comment]
Note to verify #8143  falls under this work

**Comment by johncthomas** [comment]
I figured out a work around for this
```
# When this does not update the visible selections 
source.selected.indices = new_indicies

#  This causes the selections to be visible
source.data = source.data```

Specifically this is when running a server in version 13.0. Obviously not ideal but it worked for me.

**Comment by jakirkham** [comment]
Have you retried with Bokeh 1.0.x?

**Comment by chesucr** [comment]
Yes, I have just tried it again and now works fine without any workaround! I close the issue then :) at least on Windows 10
