### ISSUE TITLE
WebGL doesn't support rectangels neither quads in Bokeh

### ISSUE THREAD

**Issue by Abdulmalek97** [bokeh/bokeh#7952]
WebGL is only supporting circles and lines at this moment and is really slow to non-working with rectangles. Is that something that will be solved soon?

**Comment by bryevdv** [comment]
> WebGL is only supporting circles and lines at this moment and is really slow to non-working with rectangles. Is that something that will be solved soon?

Unfortunately probably not. The person who used to maintain Bokeh webgl support no longer contributes to the project. I'd like very much to re-found all of webgl support, and perhaps even all rendering altogether on something like ReGL, but I have zero GL experience, so it will require a large investment of time and learning and implementation work to make happen. It will be the end of the year at best before I might have bandwidth to start down that road. Obviously is someone with deep WebGL experience wanted to come in and work on things before then, we'd be very happy to have those contributions.
