### ISSUE TITLE
Image hover broken on axes with inverted range

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#7959]
When plotting an image on an axis with an inverted range the hover tool behaves incorrectly. This example reproduces the issue (note the ``y_range=(10, 0)``):

```python
import numpy as np
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models import HoverTool

output_file("tools_hover_tooltip_image.html")

ramp = np.array([np.linspace(0, 10, 200)]*20)

data = dict(
    image=[ramp], squared=[ramp**2], pattern=['smooth ramp'],
    x=[0], y=[5], dw=[20], dh=[10]
)

cds = ColumnDataSource(data=data)
hover = HoverTool(tooltips=[
    ('index', "$index"),
    ('pattern', '@pattern'),
    ("x", "$x"),
    ("y", "$y"),
    ("value", "@image"),
    ('squared', '@squared')], )

p = figure( x_range=(0, 20), y_range=(10, 0), tools=[hover, 'wheel_zoom'])
p.image(source=cds, image='image', x='x', y='y', dw='dw', dh='dh', palette="Inferno256")
show(p)
```

<img width="554" alt="screen shot 2018-06-05 at 1 28 44 pm" src="https://user-images.githubusercontent.com/1550771/40975933-6b140f50-68c4-11e8-84e9-726593daa003.png">

Version: Bokeh 0.13.0dev5-2-g0504e1fa8

@jlstevens

**Comment by mattpap** [comment]
Is this really a problem with hover or the image is in a wrong location? Changing `y_range` doesn't affect the placement of the image.

**Comment by philippjfr** [comment]
>Shouldn't the image be flipped when an axis is inverted?

While it might be argued that the image should flip automatically, this has never been the case, so I'd argue it's going to cause major compatibility issues to switch this behavior now. If you want to properly position the image on a flipped axis you currently have to change the x/y coordinate of the image. It may have been less confusing if I had done that in the example above, which would look like this:

```python
data = dict(
    image=[ramp], squared=[ramp**2], pattern=['smooth ramp'],
    x=[0], y=[10], dw=[20], dh=[10]
)
```

This also does not work when hovering.

**Comment by philippjfr** [comment]
@jlstevens Any chance you can look into this since you're most familiar with the code?

**Comment by jlstevens** [comment]
I'll try to have a look at this soon although I don't know messy/hard it will be to fix.
