### ISSUE TITLE
Reassigning axis ticker causes app tabs and plots to disappear

### ISSUE THREAD

**Issue by ZviBaratz** [bokeh/bokeh#7960]
Hi all,

General info:
> Python version      :  3.6.5 (default, May  3 2018, 10:08:28) 
> IPython version     :  (not installed)
> Bokeh version       :  0.12.16
> BokehJS static path :  /home/flavus/PycharmProjects/cortical_layers/venv/lib/python3.6/site-packages/bokeh/server/static
> node.js version     :  v9.11.1
> npm version         :  5.8.0

My app uses tabs. Strangely, whenever I try to edit the tick labels by reassigning the ticker attribute of the x-axis of a specific plot (either as a list or a FixedTicker instance), the tabs disappear and no plots are displayed (only widgets). I'm not really sure how to create a minimal example that reproduces the issue, but for a slightly more complete picture: I have a tab with an area plot and another tab with a bunch of other plots (images) and widgets. The area plot in the first tab has 1000 ticks, which are currently mashed into a single black line under the plot. I'm trying to reduce the number of labels by reassigning the ticker attribute. 

Before:
![image](https://user-images.githubusercontent.com/22370149/40994044-dc56a602-6903-11e8-9b5b-ea31068c2790.png)
+
![image](https://user-images.githubusercontent.com/22370149/40994083-f8fbb6bc-6903-11e8-87f1-b0310786011d.png)

Becomes:
![image](https://user-images.githubusercontent.com/22370149/40994097-09e27790-6904-11e8-8b60-cf7947358bbd.png)

The line of code that causes this is:
`plot.xaxis.ticker = FixedTicker(ticks=list(range(0,1001,50))[1:])`
Same for:
`plot.xaxis.ticker = list(range(0,1001,50))[1:]`

Also, if anyone knows how to reverse the legened order that would be super helpful :)

Hope this makes sense and thank you all so much for your amazing work,
Zvi

**Comment by bryevdv** [comment]
I'm not quite following, you mean:

* you change the code to use a different ticker, then re-run, and then there is a problem? or,

* you change the ticker dynamically while the app is running, and then there is the problem?

If the latter, the solutions is to not replace the entire ticker. Instead, update the existing ticker in place:

```
plot.xaxis.ticker.ticks = list(range(0,1001,50))[1:]
```

**Comment by ZviBaratz** [comment]
Hi @bryevdv ,
Thank you for your reply! 
I might be going about this completely the wrong way, but what I am trying to do is reduce the number of tick labels so that instead of showing each of the 1000 labels on the x-axis it will display only one in 50. I was trying to do that by assigning a new ticker, but that caused the aforementioned unexpected behaviour. I tried using the method you suggested but now I get:
`AttributeError: '_list_attr_splat' object has no attribute 'ticker'`

**Comment by bryevdv** [comment]
Sorry, it should actually be 
```
plot.xaxis[0].ticker.ticks = list(range(0,1001,50))[1:]
```

properties like `xaxis` are actually lists, as a convenience we make it so that top level properties of all items can be set with `plot.xaxis.foo = 10` or whatever, but for sub properties, e.g. the `ticks` on a ticker item, you have to be explicit about which item.

**Comment by ZviBaratz** [comment]
Now I'm getting:

`AttributeError: unexpected attribute 'ticks' to CategoricalTicker, possible attributes are js_event_callbacks, js_property_callbacks, name, subscribed_events or tags`

Perhaps I'm supposed to create the plot with a different kind of Ticker..?

**Comment by bryevdv** [comment]
Oh, it was not at all evident that you are using a categorical axis. I am sure there is some approach to make things better for you but this is veering into a support discussion so I have to ask that is move to the public mailing list and off the GH tracker which we reserver for bug reports and feature requests. 

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by bryevdv** [comment]
(Regarding the problem with replacing the ticker wholesale, there is an issue somewhere else regarding just not allowing that at all)
