### ISSUE TITLE
Log axis minor ticks wrong position 

### ISSUE THREAD

**Issue by syntonym** [bokeh/bokeh#7976]
If a log axis is chosen the most lower minor ticks are in the wrong position, they are "inverted":

![bokeh_plot](https://user-images.githubusercontent.com/4145309/41098403-8694c038-6a5b-11e8-9838-66774f2d3679.png)
The blue circles show where the y axis minor ticks should have been. If one would "invert" the minor ticks below the last major major tick it would be correct. If one pans slightly lower (so that a another major tick is visible) the behavior is not visible anymore:
![bokeh_plot 2](https://user-images.githubusercontent.com/4145309/41098488-d2a71692-6a5b-11e8-8b78-819dae1e08e0.png)
This should be reproducable on any bokeh plot with log axis, but often the ticks are automatically chosen in such a way that it is not visible.

Tested on:
Bokeh Version: 0.12.16
Numpy: 1.14.4
Firefox 60.0
Python: 3.6.5
OS: Linux, Archinux, Kernel Version 4.16.8-1

Code to reproduce the first figure:
```
from bokeh.plotting import Figure
from bokeh.io import show

p = Figure(y_axis_type="log")
p.circle(y=list(range(1, 11)), x=[1]*10)
p.y_range.start = 1.0001
p.y_range.end = 1e3

show(p)
```

**Comment by bryevdv** [comment]
This problem affects all minor ticks before the "first" one, regardless of what the first one is. If you scroll up far enough the problem surfaces again. This diff fixes the issue by extending the ticks down below the visible range:
```
diff --git a/bokehjs/src/lib/models/tickers/log_ticker.ts b/bokehjs/src/lib/models/tickers/log_ticker.ts
index a504ecad4..0146fc539 100644
--- a/bokehjs/src/lib/models/tickers/log_ticker.ts
+++ b/bokehjs/src/lib/models/tickers/log_ticker.ts
@@ -67,9 +67,8 @@ export class LogTicker extends AdaptiveTicker {
       const endlog = Math.floor(log_high * 1.000001)
       const interval = Math.ceil((endlog - startlog) / 9.0)

-      ticks = range(startlog, endlog + 1, interval)
+      ticks = range(startlog-1, endlog+1, interval)
         .map((i) => Math.pow(base, i))
-        .filter((tick) => data_low <= tick && tick <= data_high)

       if (num_minor_ticks > 0 && ticks.length > 0) {
         const minor_interval = Math.pow(base, interval) / num_minor_ticks
```
but I am not sure if removing the filtering has any adverse implications, or if there is a different approach that might be better. More investigation needed.
