### ISSUE TITLE
High (probably unnecessary) CPU load due to is_valid calls.

### ISSUE THREAD

**Issue by thomasetter** [bokeh/bokeh#7977]
python 3.6 on linux 4.16, tested with the latest (as of 2018-06-07) bokeh dev version and with 0.12.16

This example exhibits bokeh slowness and high CPU usage:

``` python
from bokeh.plotting import figure
from bokeh.layouts import layout
from bokeh.models import Div, CustomJS
from bokeh.io import curdoc
import os

# prepare some data
x = range(0,100)
y = range(0,100)
os.environ['BOKEH_VALIDATE_DOC'] = "0" # This does nothing for this example

def create_plot():
    # create a new plot with a title and axis labels
    p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

    # add a line renderer with legend and line thickness
    p.line(x, y, legend="Temp.", line_width=2)
    return p

plots = []

for i in range(0,50):
    plots.append(create_plot())

l = layout(plots)

curdoc().add_root(l)
```

The high CPU usage is partially in the browser, but that only lasts a few seconds, however in the server, it uses *100% CPU for up to 20 seconds* (on an 8-th gen Intel CPU) even after the page seems fully rendered in the browser.

`bokeh serve --show example.py`

[**Flamechart**](https://gistpreview.github.io/?f1fa42b4aeea8f0e3f42b43863980221/bokeh_flame.html
)

Most of the time seems to be spent doing validations with `self.validate()` which throws an expensive (there is a lot of string concatenating/formatting) error the message of which is then [ignored in `is_valid`](https://github.com/bokeh/bokeh/blob/16cfb18ab72c35bb6e6c59888545b509cedd0b9f/bokeh/core/property/bases.py#L256).

I am not sure whether is_valid should not be called here or if it should be cheaper to call.

Setting [BOKEH_VALIDATE_DOC](https://bokeh.pydata.org/en/latest/docs/dev_guide/env_vars.html#bokeh-validate-doc) to false does not seem to help as it hits no code path which checks that variable. It is checked here:
```
$ git grep 'perform_document_validation'
bokeh/application/application.py:        if settings.perform_document_validation():
bokeh/embed/notebook.py:    if settings.perform_document_validation():
bokeh/embed/standalone.py:    if settings.perform_document_validation():
bokeh/settings.py:    def perform_document_validation(self, default=True):
```

The flamechart has been created using [pyflame](https://github.com/uber/pyflame):
`sudo pyflame -s 20 -p {PID} -o prof.txt`

and [FlameGraph](https://github.com/brendangregg/FlameGraph):
`flamegraph.pl prof.txt > _bokeh_flame.html`

**Comment by bryevdv** [comment]
The exception is not ignored, it is converted into a Boolean value that signals whether validation succeeded or not. If there is some validator that is doing too much work we just need to figure out what it is. 

In passing, I will also say that 50 plots on a page is not a good use scenario for Bokeh, given the its tradeoff choices, and if that is what you need you may want to look at other tools.

**Comment by mattpap** [comment]
The current approach is indeed inefficient. Though the numbers are a little different for me: validations takes 3 seconds and rendering 13 seconds. Still, 3 seconds for validation way too much.

**Comment by bryevdv** [comment]
I'm testing out the approach I desired above right now

**Comment by bryevdv** [comment]
@thomasetter can you try things out with #7980 and report back. Things seem qualitatively better to me but you have immediate experience with some better quantitative tools that would be valuable.

**Comment by bryevdv** [comment]
I've also just realized ` BOKEH_VALIDATE_DOC` controls something else and entirely unrelated (whole document integrity checks, vs fine grained type checks like these)

**Comment by bryevdv** [comment]
@thomasetter thanks for the quick feedback and detailed report, we will definitely get this merged before the next release. Nearly all of Bokeh's imports are at the top level, but sometimes there is a technical reason why this is not possible (i.e a circular import dependency maybe) I will take a look at the `prepare_value` case more closely though.

**Comment by bryevdv** [comment]
Actually I think in the past this probably was a circular dependency. Properties can form object graphs with `HasProps` objects that have properties that themselves refer to other `HasProps` objects. That a situation that can lead to circular module imports without care. But there was a large cleanup and refactor of the properties system maybe a year ago, and I think that it's no longer the case, `has_props.py` only depends on the property descriptors module which is very ight, and not on properties themselves. I will move import up to the top now, and get a dev build out.

**Comment by bryevdv** [comment]
@thomasetter I have mode those changes and also moved a few more function imports I found elsewhere. I also changed `is_valid` to just always suppress details. After closer inspection I realized this function is precisely and only used for internal type checking, and no exception escapes it, so to this should be cleaner at the call sites. 

Can you test one more time with the updated PR? Then we will get this merged

**Comment by thomasetter** [comment]
Thanks, tested #7980 again and it looks good, the is_valid CPU time is now ~10% vs ~20% before and the expensive imports do not appear anymore.

[Updated Flamegraph](https://gistpreview.github.io/?f1fa42b4aeea8f0e3f42b43863980221/bokeh_flame_with_7980.html)

Another improvement is also that the Flame graph is much nicer to read now which will make future optimizations easier.
