### ISSUE TITLE
CheckboxButtonGroup and RadioButtonGroup can not be disabled

### ISSUE THREAD

**Issue by ivan-usov** [bokeh/bokeh#7981]
python/3.6.5
bokeh/0.13.0dev8-1-gdfefc4242
firefox/60.0.1

Setting the `disabled` property to True doesn't affect neither CheckboxButtonGroup nor RadioButtonGroup widgets. The expected behaviour is that this should be consistent with CheckboxGroup and RadioGroup, where the `disabled` property correctly deactivates the widgets.

To see the difference, one could use the 'Disable widgets' toggle in the following bokeh app, which changes the state of `disabled` property of all the above-mentioned widgets.
```
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import CheckboxButtonGroup, CheckboxGroup, RadioButtonGroup, RadioGroup, Toggle

checkbox_button_group = CheckboxButtonGroup(
    labels=["Option 1", "Option 2", "Option 3"], active=[0, 1])

checkbox_group = CheckboxGroup(
    labels=["Option 1", "Option 2", "Option 3"], active=[0, 1])

radio_group = RadioGroup(
    labels=["Option 1", "Option 2", "Option 3"], active=0)

radio_button_group = RadioButtonGroup(
    labels=["Option 1", "Option 2", "Option 3"], active=0)

def disable_toggle_callback(state):
    if state:
        checkbox_button_group.disabled = True
        checkbox_group.disabled = True
        radio_button_group.disabled = True
        radio_group.disabled = True

    else:
        checkbox_button_group.disabled = False
        checkbox_group.disabled = False
        radio_button_group.disabled = False
        radio_group.disabled = False

disable_toggle = Toggle(label="Disable widgets")
disable_toggle.on_click(disable_toggle_callback)

layout = column(checkbox_button_group, checkbox_group, radio_button_group, radio_group, disable_toggle)

curdoc().add_root(layout)
```

**Comment by jsignell** [comment]
Just ran into this and can't quite figure out what's going on. It seems like the signals are all connected up properly.

**Comment by jsignell** [comment]
I don't think this is fixed. I am still seeing the same issue of the widgets not being disabled when running the code snippet above.

**Comment by mattpap** [comment]
You will need to provide more details. I just tested in Chrome and FF, and it works correctly.

**Comment by jsignell** [comment]
I am seeing: 

<img width="300" alt="Screen Shot 2019-03-18 at 10 33 55 AM" src="https://user-images.githubusercontent.com/4806877/54538027-e5f5dd80-4969-11e9-8996-378921816652.png"> <img width="300" alt="Screen Shot 2019-03-18 at 10 33 49 AM" src="https://user-images.githubusercontent.com/4806877/54538034-e8f0ce00-4969-11e9-9cb1-08f4db3c75c1.png" align="right">

The button group widgets are not disabled when disabled is toggled to True.

**Comment by mattpap** [comment]
Let's start from making sure that you're using most recent bokehjs (it's easy to get that wrong with the server). If bokehjs is up-to date, then I will need platform details, etc. (under assumption that this is a platform specific bug).

**Comment by jsignell** [comment]
My bad @mattpap - I was using inline and forgot to rebuild bokehjs. Thanks for the help :)
