### ISSUE TITLE
Add support for copy and paste into DataTable

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#7989]
In many scenarios a user might want to add data to bokeh and the DataTable provides one way to enter data. In addition to the ability to insert new rows into a DataTable (as suggested in https://github.com/bokeh/bokeh/issues/7988), it would be very convenient to be able to copy & paste data into the table. Apparently this is not supported by Slickgrid directly but there is an existing extension to enable it [here](https://github.com/Celebio/SlickGrid/blob/master/plugins/slick.cellexternalcopymanager.js).

**Comment by bryevdv** [comment]
dupe of #7762

**Comment by philippjfr** [comment]
Sorry, should have checked myself.
