### ISSUE TITLE
Add clear tool to clear out one or more datasources

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#7990]
The draw and edit tools are very useful to annotate a plot, however often you want to be able to both add and delete these annotations without having to select each drawn glyph and deleting it manually. It would therefore be useful to add a clear tool which can be given one or more data sources to clear. The implementation would be quite straightforward since the tool would simply have to iterate over the supplied CDS columns and set each to an empty array.

**Comment by bryevdv** [comment]
Now that there is a `CustomAction` toolbar button tool, I am more inclined to just add a `clear` method to CDS that any JS action or callback could use.

**Comment by philippjfr** [comment]
>I am more inclined to just add a clear method to CDS that any JS action or callback could use.

That seems reasonable especially once I've made the PR to be able to customize tooltips and icons and ensured that merged toolbars only deduplicate certain tools.

**Comment by bryevdv** [comment]
OK I will make a quick PR for this now.

**Comment by bryevdv** [comment]
@philippjfr FYI I just realized perhaps I misunderstood, I added a CDS `clear` method on the JS side, was that your actual request?

**Comment by philippjfr** [comment]
>@philippjfr FYI I just realized perhaps I misunderstood, I added a CDS clear method on the JS side, was that your actual request?

No I think we're fine. You can now easily define a CustomAction tool that calls CDS.clear() on any number of CDSs you give it correct? In which case that covers my request, especially once I can customize the tooltip/icon for the CustomAction tool.

**Comment by bryevdv** [comment]
> You can now easily define a CustomAction tool that calls CDS.clear() on any number of CDSs you give it correct?

Yes, exactly
