### ISSUE TITLE
Line plot does not have conditional line colour

### ISSUE THREAD

**Issue by JoshuaC3** [bokeh/bokeh#7997]
Expected to be able to have changing colours of lines in line plots depending on a value (from the same or another columns in a source).

the below code works when used with `circle` instead of `line`.

<details><summary>Pip Freeze</summary>
<p>
atomicwrites==1.1.5  <br/>
attrs==18.1.0  <br/>
backcall==0.1.0  <br/>
bleach==2.1.3  <br/>
bokeh==0.12.16  <br/>
certifi==2018.4.16  <br/>
click==6.7  <br/>
colorama==0.3.9  <br/>
cycler==0.10.0<br/>
Cython==0.28.3<br/>
decorator==4.3.0<br/>
entrypoints==0.2.3<br/>
html5lib==1.0.1<br/>
ipykernel==4.8.2<br/>
ipython==6.4.0<br/>
ipython-genutils==0.2.0<br/>
ipywidgets==7.2.1<br/>
jedi==0.12.0<br/>
Jinja2==2.10<br/>
jsonschema==2.6.0<br/>
jupyter==1.0.0<br/>
jupyter-client==5.2.3<br/>
jupyter-console==5.2.0<br/>
jupyter-core==4.4.0<br/>
kiwisolver==1.0.1<br/>
MarkupSafe==1.0<br/>
matplotlib==2.2.2<br/>
mistune==0.8.3<br/>
mkl-fft==1.0.2<br/>
mkl-random==1.0.1<br/>
more-itertools==4.2.0<br/>
nbconvert==5.3.1<br/>
nbformat==4.4.0<br/>
notebook==5.5.0<br/>
numpy==1.14.3<br/>
packaging==17.1<br/>
pandas==0.23.0<br/>
pandocfilters==1.4.2<br/>
parso==0.2.1<br/>
peewee==3.5.0<br/>
pickleshare==0.7.4<br/>
pluggy==0.6.0<br/>
prompt-toolkit==1.0.15<br/>
py==1.5.3<br/>
Pygments==2.2.0<br/>
PyMySQL==0.8.1<br/>
pyparsing==2.2.0<br/>
pytest==3.6.0<br/>
python-dateutil==2.7.3<br/>
pytz==2018.4<br/>
pywinpty==0.5.3<br/>
PyYAML==3.12<br/>
pyzmq==17.0.0<br/>
qtconsole==4.3.1<br/>
Send2Trash==1.5.0<br/>
shell-utils==0.5.0<br/>
simplegeneric==0.8.1<br/>
six==1.11.0<br/>
SQLAlchemy==1.2.8<br/>
terminado==0.8.1<br/>
testpath==0.3.1<br/>
tornado==5.0.2<br/>
traitlets==4.3.2<br/>
wcwidth==0.1.7<br/>
webencodings==0.5.1<br/>
widgetsnbextension==3.2.1<br/>
wincertstore==0.2<br/>
</p>
</details>

```
import pandas as pd

from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, LinearColorMapper


df = pd.DataFrame({
    'xx': range(10), 'yy': [2, 1, 3, 1, 1.5, 2.5, 1, 2, 3, 2.5]
})

source = ColumnDataSource(df)

p = figure(width=200, height=200)

color_mapper = LinearColorMapper(palette='Magma256', low=1, high=3)

p.line(x='xx', y='yy', source=source, fill_color={'field': 'yy', 'transform': color_mapper})

show(p)

```

#### Stack traceback and/or browser JavaScript console output

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-200-8f1b6e2296fa> in <module>()
     15 color_mapper = LinearColorMapper(palette='Magma256', low=1, high=3)
     16 
---> 17 p.line(x='xx', y='yy', source=source, fill_color={'field': 'yy', 'transform': color_mapper})
     18 
     19 show(p)

fakesource in line(self, x, y, **kwargs)

c:\anaconda\envs\missing-data-estimator\lib\site-packages\bokeh\plotting\helpers.py in func(self, **kwargs)
    751             mglyph_ca = None
    752 
--> 753         glyph = _make_glyph(glyphclass, kwargs, glyph_ca)
    754         nsglyph = _make_glyph(glyphclass, kwargs, nsglyph_ca)
    755         sglyph = _make_glyph(glyphclass, kwargs, sglyph_ca)

c:\anaconda\envs\missing-data-estimator\lib\site-packages\bokeh\plotting\helpers.py in _make_glyph(glyphclass, kws, extra)
    307     kws = kws.copy()
    308     kws.update(extra)
--> 309     return glyphclass(**kws)
    310 
    311 

c:\anaconda\envs\missing-data-estimator\lib\site-packages\bokeh\model.py in __init__(self, **kwargs)
    217         self._id = kwargs.pop("id", make_id())
    218         self._document = None
--> 219         super(Model, self).__init__(**kwargs)
    220         default_theme.apply_to_model(self)
    221 

c:\anaconda\envs\missing-data-estimator\lib\site-packages\bokeh\core\has_props.py in __init__(self, **properties)
    234 
    235         for name, value in properties.items():
--> 236             setattr(self, name, value)
    237 
    238     def __setattr__(self, name, value):

c:\anaconda\envs\missing-data-estimator\lib\site-packages\bokeh\core\has_props.py in __setattr__(self, name, value)
    269 
    270             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 271                 (name, self.__class__.__name__, text, nice_join(matches)))
    272 
    273     def __str__(self):

AttributeError: unexpected attribute 'fill_color' to Line, similar attributes are line_color

**Comment by mattpap** [comment]
> `p.line(x='xx', y='yy', source=source, fill_color=...)`

It should be `line_color`. The error message indicates this as well.

**Comment by JoshuaC3** [comment]
@mattpap My apologies. Copied the wrong cell from a notebook. Updated with correct kwarg and correct error. Please reopen.

**Comment by bryevdv** [comment]
Lines do not support fill colors (there is nothing to fill). It's not clear what you are expecting but this is a support/usage question so it belongs in the mailing list, not the issue tracker.

**Comment by JoshuaC3** [comment]
@bryevdv `line_color`  not `fill_color`.

I would expect the line to change color depending on the value of the field option. In this case it is the `yy` column, but could be some other `zz`.

Currently is throws the above error when I try to use it. It is hard to know (from my POV) if this is a bug or the lack of a feature. It seems from what you have said here, it is the latter. I have raised it as a feature request in the mailing list.
