### ISSUE TITLE
DatePicker date offset on Chrome/OSX - wrong dates, off by 1,000 years in some cases

### ISSUE THREAD

**Issue by MikeWoodward** [bokeh/bokeh#8009]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 12.16
Python 3.6.3 (Anaconda 3)
Spyder 3.2.8
Mac OSX High Sierra 10.13.5
Chrome 67.0.3396.87 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior

There is an offset of a day for min/max/value settings in the DatePicker widget

#### Complete, minimal, self-contained example code that reproduces the issue

```

from bokeh.layouts import (
    column,
    row,
)

from bokeh.models.widgets import (
    DatePicker,
)

from bokeh.plotting import output_file, reset_output, show


date0 = '1950-10-20'
datepicker0 = DatePicker(
    title=date0,
    min_date=date0,
    max_date=date0,
    value=date0,
)

date1 = '1969-12-31'
datepicker1 = DatePicker(
    title=date1,
    min_date=date1,
    max_date=date1,
    value=date1,
)

date2 = '1972-01-31'
datepicker2 = DatePicker(
    title=date2,
    min_date=date2,
    max_date=date2,
    value=date2,
)

date3 = '2018-10-20'
datepicker3 = DatePicker(
    title=date3,
    min_date=date3,
    max_date=date3,
    value=date3,
)

date4 = '1969-12-31'
datepicker4 = DatePicker(
    title=date4,
    min_date=date4,
    max_date=date4,
    value=date4,
)

date5 = '1989-07-14'
datepicker5 = DatePicker(
    title=date5,
    min_date=date5,
    max_date=date5,
    value=date5,
)

p = column(row(datepicker0, datepicker1, datepicker2), 
           row(datepicker3, datepicker4, datepicker5))
reset_output()
output_file('test.html')
show(p)


```

**Comment by MikeWoodward** [comment]
There's another related issue I've been unable to duplicate in self-contained code. When updating the min_date, max_date, and value attributes via a callback, the date is sometimes shifted by two days for recent days (in the last year). If you change these attributes to dates in the 1960's, the offset can be two years or more.

I 'm trying to create a smaller example, but here's the line of code that updates one on the attributes:
            self.panel.child.children[1].children[0].children[0].value = \
                min_date
when min_date is 1969-12-31, the value actually displayed is Wed Apr 05 1967

My example is a work project I can't share, but I might be able to produce a smaller sample that shows this behavior. Let me know if it would be helpful.

**Comment by MikeWoodward** [comment]
This might be the same as #8015 

I've looked at the problem more closely. The Bokeh DatePicker attributes min_date, value, and max_date all seem to be behaving consistently if you set and get them via the API. The problem seems to be in the implementation of the DatePicker in Chrome. 

If you choose values on the picker GUI which are just a month apart, you see the year change incorrectly. My guess is, we have  two different date representations and the translation between the two is broken.

**Comment by bryevdv** [comment]
@MikeWoodward I think you are correct that this is the same as #8015 so I am going to close this as  a duplicate and leave a note there the verify that a solution to that issue truly resolves this as well.
