### ISSUE TITLE
Expose the more detailed geometry data to the tap tool

### ISSUE THREAD

**Issue by euandekock** [bokeh/bokeh#8013]
When a callback is written for the tap_tool, it exposes the screen geometry of the point that was tapped, available as 
```
cb_data["geometries"]["sx"]
cb_data["geometries"]["sy"]
```
However, to be truly useful it should also provide the converted data coordinates as 
```
cb_data["geometries"]["x"]
cb_data["geometries"]["y"]
```
 This would emulate the hover tool functionality. (Apart from calling one geometry and the other geometries)

There are many cases where it is useful to know exactly what the data values are when a point is tapped. On a line, the point tapped may be somewhere between two distant points, and we need the extrapolated values for that exact point along the line.

Currently, the only way to get these values is to hack an additional callback on the hover tool, and save the values in a CDS so we can interrogate them during the tap tool callback. This is very expensive as we are using the hover event to continually store this data even if we never hit the tap tool.

Below is a current example of this hack:
```
# Create a CDS so we can store the hover x and y coordinates.
locator = ColumnDataSource(name="pred_locator", data=dict(x=[0], y=[0]))

# Define a call back for the hover tool
callback_hover = CustomJS(args=dict(locator=locator), code="""
         geometry = cb_data["geometry"];
         locator.data["x"][0] = geometry["x"];
         locator.data["y"][0] = geometry["y"];
         """)

# define a callback for the tap tool
callback_tap = CustomJS(args=dict(locator=locator), code="""
         geometry = cb_data["geometries"];

         var y_data_val = locator.data["y"][0];
         var y_screen_val = geometry["sy"]; 
         alert("Tapped at " + y_screen_val + ", actual value is " + y_data_val);
         """)


plot.add_tools(HoverTool(callback=callback_hover))
plot.add_tools(TapTool(callback=callback_tap))

```
This is related to the original request to expose the geometry to the tap tool.

Expose Geometries to TapTool Callbacks #4082

**Comment by bryevdv** [comment]
> Currently, the only way to get these values is to hack an additional callback on the hover tool, and save the values in a CDS so we can interrogate them during the tap tool callback. 

I don't see why this would be necessary. You should be able to turn the screen coordinates into data coordinates the same way that other code does internally, e.g.

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/tools/inspectors/hover_tool.ts#L201-L206

**Comment by euandekock** [comment]
Thanks for your comment Bryan, and after reviewing this in greater depth, I agree that it can be done as you suggest, using cb_obj and cb_data to access the values required. 

(cb_obj is only valid in the tap tool callback from version 0.12.7 onwards)

This is a working example:
```
            const sx = cb_data.geometries.sx;
            const sy = cb_data.geometries.sy;
            console.log("Tap at Screen points SX: " + sx + " SY: " + sy);
            
            const x = cb_obj.plot_model.frame.xscales['default'].invert(sx)
            const y = cb_obj.plot_model.frame.yscales['default'].invert(sy)
            console.log("Tap at Data points X: " + x + " Y: " + y);
```
However, this does require a deep understanding of the internal structure of the rendering objects, and may result in very breakable code if the internal calls are ever refactored. 

As far as I am aware, this level of detail is not documented and these values are probably useful enough to be included, and to provide some consistency between the tap and hover behaviour.

I'll leave this open for now as I may attempt to implement it if I get a chance, but my javascript and typescript is limited (as is my time right now).

**Comment by euandekock** [comment]
**Disclaimer**: The above example code works in my use case, where I am clicking on a multi_line glyph. It may break if multiple objects are selected, or if the underlying renderer is something else - again my knowledge of the internals of how the renderer manages the scales and how the cb_obj changes when multiple different glyphs are selected in a single tap.

**Comment by bryevdv** [comment]
@euandekock that will always return the x/y coords on the default scale. For most plots, that's all there is. If there are multiple/twin axes, then there coud be non-default scales, but I think that's something that could be left as an advanced case. I would be perfectly fine adding that conversion of `sx` and `sy` here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/tools/gestures/tap_tool.ts#L11

If you'd like to put together a small PR I'd be happy to help you work through it.

**Comment by bryevdv** [comment]
Additionally it would be good to make a few words about what is in the `geometries` object here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/tools.py#L382

**Comment by euandekock** [comment]
Hi @bryevdv ,

I don't have permission to push a commit up to Bokeh, so I've attached two files here (in a gz)  that should resolve this issue. Please can you create a pull request for this change.

The change does correctly handle the case of multiple axis as each glyph initiates a separate callback. It behaves much like the Hover tool does in that it no longer uses the PointGeometry interface as a basis for the geometries object, but creates a new object with the extra x and y variables included.

[8013_taptool_fix.tar.gz](https://github.com/bokeh/bokeh/files/2144737/8013_taptool_fix.tar.gz)

**Comment by euandekock** [comment]
Hi @bryevdv,

I have submitted a PR with the changes to both files referenced above. Please advise if you need anything further for this.

Regards,

Euan.

**Comment by bryevdv** [comment]
I'm currently traveling due to a death in the family, I will look I at it next week.

**Comment by bryevdv** [comment]
@euandekock Looking at things mode closely I think there is a better approach. I think in fact that we should move away from `.callback` entirely, and over to the more general events system that was added last. With that you can use `on_event` (in server apps) or `js_on_event` (for JS callbacks). And those already all add data space coordinates to the callback event data. 

What is missing, is that tap tool fires the event unconditionally. Presumably you only want to have events and callbacks if e.g. an actual circle was hit? If so that seems like a configurable flag could be added in a non-breaking way to `TapTool` so that it only fires events when a hit occurs. If that sounds good we an rename this issue.

**Comment by bryevdv** [comment]
For reference, in case you have not seen the more recent `bokeh.events` style:

https://github.com/bokeh/bokeh/blob/master/examples/howto/js_events.py
https://github.com/bokeh/bokeh/blob/master/examples/howto/events_app.py

Basically what I now suggest is putting effort into the better `bokeh.events` codepaths, instead of the `.callback` machinery which is very old and ad-hoc, and possibly up for deprecation at some point anyway.

**Comment by euandekock** [comment]
Looking at the events subsystem, it appears to be a at a lower level than the callback system, and operates independently of any of the underlying chart glyphs.

In the events.py code:

```
class PointEvent(PlotEvent):
    ''' Base class for UI events associated with a specific (x,y) point.

    Attributes:
        sx (float) : x-coordinate of the event in *screen* space
        sy (float) : y-coordinate of the event in *screen* space
        x (float) : x-coordinate of the event in *data* space
        y (float) : y-coordinate of the event in *data* space

    Note that data space coordinates are relative to the default range, not
    any extra ranges, and the the screen space origin is at the top left of
    the HTML canvas.

    '''
```


It can be seen that all the x and y coordinates are reported relative to the default ranges. All events just report the underlying geometry with no attempt to relate this to any glyphs that may lie under the area being reported.

In order for this to replace the callback functionality we would need to re-code many of the callbacks to raise custom events that provide this extra layer of information rather than trying to bend the current set of events to fit.

In the case of TapTool we'd need to raise a "select_glyph" event for each glyph that was hit with the appropriate axis specific range conversions applied, and additional data that identifies which glyph is being triggered.

Each of the Select tools would need to raise a "select_glyph" event for each glyph in the selected area, but providing an appropriate data type - Vector arrays of the appropriate geometry for Box, Poly and Lasso for all data items that are selected.

All of the events should be able to pass both the actual selection point (x, y) in the correct range, and also the correct geometries for all the selected points - or at least the offsets to the data for the selections (eg the current `cb_data.source.selected.indices` and `cb_data.source.selected.multiline_indices[]` indices) as well as an identifier for which glyph is being triggered.

The events would also need to be sensitive to which glyphs are associated with the tool, and only raise events for these.

**For now I'd like to suggest that we push the current changes to extend the callbacks without worrying too much about the inconsistencies in naming etc, and start a separate discussion on adding glyph specific events to the event subsystem that will replicate the callback functionality properly.**

**Comment by euandekock** [comment]
@bryevdv 

Given that all the other tools already implement data coordinates in much the same way as I was initially proposing, can we still consider the pull request I submitted. This will at least put the Tap Tool on an equal footing with all the other callback based tools, and will provide a base level of functionality to replicate with the new events.

We can then consider a more formal redesign to move all callback functionality across to the events system.
