### ISSUE TITLE
If the "selector" argument is explicitily set to the "select" method, an empty list is returned

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#8018]
A small bug.

If I write manually the argument name `selector` using the `select` method, the returned valueis an empty list, however the `select_one` works well.

    from bokeh.io import output_notebook, show, push_notebook
    output_notebook()

    from bokeh.models import ColumnDataSource, CustomJS, IndexFilter, CDSView
    from bokeh.plotting import figure

    source = ColumnDataSource(dict(
        x=[1, 2, 3, 4, 5, 6],
        y=[1, 2, 3, 4, 5, 6],
    ))

    p = figure(
        plot_height=300,
        tools='lasso_select'
    )

    rc = p.circle(
        x='x',
        y='y',
        size=20,
        source=source,
        fill_alpha=1.0,
        line_alpha=1.0,
    )
    rc.tags = ['GR', 'GRS']

    rs = p.select(dict(tags=['GR']))
    rs = p.select_one(dict(tags=['GR']))

    rs = p.select(selector=dict(tags=['GR']))         # returns an empty list
    rs = p.select_one(selector=dict(tags=['GR']))

These are the [code declarations](https://bokeh.pydata.org/en/latest/docs/reference/model.html#bokeh.model.Model.select)

    def select(self, selector):
        ''' Query this object and all of its references for objects that
        match the given selector.

        Args:
            selector (JSON-like) :

        Returns:
            seq[Model]

        '''
        return find(self.references(), selector)

    def select_one(self, selector):
        ''' Query this object and all of its references for objects that
        match the given selector.  Raises an error if more than one object
        is found.  Returns single matching object, or None if nothing is found
        Args:
            selector (JSON-like) :

        Returns:
            Model
        '''
        result = list(self.select(selector))
        if len(result) > 1:
            raise ValueError("Found more than one object matching %s: %r" % (selector, result))
        if len(result) == 0:
            return None
        return result[0]

**Comment by bryevdv** [comment]
The problem is that `Plot` overrides the `select` defined on `Model` with a different version for some reason.
