### ISSUE TITLE
Datatable and Glyph selections not linking properly

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8021]
One ref is: https://github.com/bokeh/bokeh/issues/2323#issuecomment-395032022

Alternatively, run `models/file/data_tables.py` The first selection of glyphs updates the table selection. No subsequent selection does. 

Possibly related to #8014 as well, the issue may be that there is inconsistency in when and whether `selected` is changed vs `selected.indices`

ANY solution to this must provide the following

* documention (in a wiki, docs, somewhere) of all known expected requirements of tables. 
* provide runnable examples that can be used to exercise all the requirements

Additionally, this would be a good chance to get some kind of selenium tests up and running, either run ourselves on travis or run again on sauce labs. The whack-a-mole with table regressions has to stop.

**Comment by bryevdv** [comment]
also possibly related #7944

**Comment by chaseharper** [comment]
Hello, 

First of all, thank you for Bokeh, it is an excellent library!  I have been having the same or a similar issue as described above and was wondering if any resolution or work around is available for this?

I do not have any experience with and do not quite understand callbacks, but I am thinking a call back from the TapTool and a Callback on the DataTable could achieve the functionality.

Simply put, I have a Figure and DataTable displaying on the same page with a shared ColumnDataSource.  I am not sure if any of the following information is necessary or relevant but below are some other observations I have made:

I am using Bokeh Server to launch my script
- Upon initial launch of the page selecting any row on the DataTable will repeatedly select the corresponding glyph on the Figure.
- Selecting a glyph on the Figure will 'break' this functionality.
- Upon initial launch of the page selecting a glyph on the Figure will bring the corresponding row on the DataTable into view, however this only works once.
- (I discovered this one by accident, I left the page loaded after I shut down the bokeh server)  once you shut down the bokeh server {ctrl+c in the command prompt} selecting a glyph on the Figure will repeatedly select the corresponding row on the DataTable; however the inverse behavior described above where you can select a row on the DataTable and the corresponding glyph on the Figure no longer works.

Again thank you for Bokeh!
