### ISSUE TITLE
Expose `view.indices` in python

### ISSUE THREAD

**Issue by lgasnier** [bokeh/bokeh#8024]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 0.13
python 3.6.5
OS linux
browser Firefox

#### Description of expected behavior and the observed behavior
In the example below, `renderer.view.indices` can be used in `CustomJS` javascript code to update `y_range.factors` but not in python to initiate the factors. It would be useful for a complex view with several filters.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import output_file, show

from bokeh.models import (FactorRange,
                          CustomJS,
                          ColumnDataSource,
                          CDSView,
                          GroupFilter,
                          Select)
from bokeh.layouts import widgetbox, column
from bokeh.plotting import figure

output_file("test_view_indices.html")

source = ColumnDataSource(dict(
    cat=['foo', 'bar', 'baz', 'qux', 'corge', 'grault', 'qux', 'corge', 'garply'],
    val=[5, 10, 1, 7, 8, 5, 3, 2, 4],
    grp=['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b']
    ))

p = figure(title="Test CDSView Select FactorRange", y_range=[], width=400, height=400) 
group_filter = GroupFilter(column_name='grp', group='a')
view = CDSView(source=source, filters=[group_filter])

# Initiate p.y_range.factors
# --------------------------
# p.y_range.factors = [source.data['cat'][i] for i in view.indices]
# Can't access view.indices in python

p.y_range.factors = ['foo', 'bar', 'baz', 'qux', 'corge']

r = p.hbar(y='cat', height=0.5, right='val', 
           source=source, view=view)


code = """
    var grp = cb_obj.value;
    group_filter.group = grp;
    
    source.change.emit();
    
    var idx = [];
    for (var i = 0; i < renderer.view.indices.length; i++) {
        idx.push(renderer.view.indices[i]);
    }
    console.log(grp, JSON.stringify(idx));
    var factors = [];
    factors = source.data['cat'].filter((value, index, arr) => idx.includes(index));
    console.log(JSON.stringify(factors));
    plot.y_range.factors = factors;
"""
cb = CustomJS(args={'group_filter': group_filter,
                    'renderer': r,
                    'source': source,
                    'plot': p},
               code=code)
select = Select(title="Categ:", value="a", options=[("a", "Cat a"), ("b", "Cat b")], callback=cb)

layout = column(select, p)
show(layout)


```
#### Stack traceback and/or browser JavaScript console output
If `p.y_range.factors = [source.data['cat'][i] for i in view.indices]` line is uncommented:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-a98b27a896a2> in <module>()
     22 view = CDSView(source=source, filters=[group_filter])
     23 
---> 24 p.y_range.factors = [source.data['cat'][i] for i in view.indices]
     25 # Can't access view.indices
     26 

AttributeError: 'CDSView' object has no attribute 'indices'
```

**Comment by bryevdv** [comment]
Might be possible as a readonly property

**Comment by bryevdv** [comment]
@lgasnier actually I just realized that you are trying to do this in a standalone document, that is never going to be possible. The view filters are applied and computed *in the browser*, at which point there is no python process around. I believe that this can be accomplished for Bokeh server apps only, since in that case there is a persistent python process connected to the Bokeh document.

**Comment by bryevdv** [comment]
Additionally, investigation reveals that containers such as `List` do not currently support `readonly`. It might be possible to add, but would require a fairly extensive amount of testing since it is low level machinery that would need to be updated. Since there is non-trivial risk/effort and the request was not actually for server apps (and since the only possible workaround for standalone apps has been suggested) I am going to close this with no action.

**Comment by lgasnier** [comment]
Sorry, I didn't understand that view filters occur in the browser.
Thanks for your investigation.

**Comment by bjfar** [comment]
This is an old question, but I cannot figure out how to do something done here in modern Bokeh. In the OP code JS they access the view indices in javascript via a renderer like so:

```
    var idx = [];
    for (var i = 0; i < renderer.view.indices.length; i++) {
        idx.push(renderer.view.indices[i]);
    }
```

however this doesn't seem to work anymore. `renderer.view.indices` seems to still exist, but `renderer.view.indices.length` doesn't, and nor does `renderer.view.indices[i]` appear to be a valid way of accessing the indices anymore.

**Comment by mattpap** [comment]
`indices` is not an array, thus you can't index it like that. The equivalent is `indices.get()`, though it also supports iterable protocol, so you can use:
```ts
const indices = [...renderer.view.indieces]
```
or in a loop:
```ts
const indices = []
for (const i of renderer.view.indices) {
  indices.push(i)
}
```
