### ISSUE TITLE
Draw and Edit tools event handling on server broken

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8032]
Playing around with the draw and edit tools on bokeh server that even after https://github.com/bokeh/bokeh/issues/7745 was resolved many actions don't seem to trigger Python side events. Specifically drawing a new point using PointDrawTool and drawing box using the BoxEditTool seems to trigger no event at all on the Python end, and the PolyEditTool seems to cause an endless chain of events being sent. The fix in https://github.com/bokeh/bokeh/pull/7818/files addressed the missing updates using on point drag events by explicitly setting the data:

```python
      // This is only needed to call @_tell_document_about_change()
      renderer.data_source.data = renderer.data_source.data
```

I'd be happy to put together a PR to fix this in other cases, but I still don't quite understand why this is necessary. Shouldn't property change events be sufficient?

```python
data_source.properties.data.change.emit()
```

**Comment by bryevdv** [comment]
I'm not sure, but there is no point in making PRs for these things until we can find a way to maintain them under test.
