### ISSUE TITLE
Unhandled exception in application causes all later sessions to fail

### ISSUE THREAD

**Issue by kti-matt** [bokeh/bokeh#8034]
## The problem

In a "bokeh serve" application, if there is an unhandled exception in the main code, all new sessions after the exception do not work.

Background: https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/BZpiJJ4TO2M

## Expected behaviour

The preferred behaviour would be that an unhandled exception would only affect the session that caused the exception, and sessions started later would continue to work. Other frameworks typically isolate exceptions so that if a request causes an exception, only that request is affected.

## Versions

Bokeh: 0.13.0
Python: 3.5.2

## Example application

The below example application is copied from https://bokeh.pydata.org/en/latest/docs/user_guide/server.html#single-module-format, except it raises an exception in 33% of new sessions.

To duplicate the issue, do:
1. Run "bokeh serve myapp.py"
2. Open a browser to http://localhost:5006/boom. If you don't see "Exception: boom!" in the console, you can click the "Press Me" button to see numbers appear.
3. Refresh the page until you see "Exception: boom!" in the console. The Bokeh app won't appear in the browser.
4. Refresh the page again. The app still doesn't appear. This demonstrates that later sessions are affected.
5. Restart the server and refresh the page. If the exception isn't raised, the app will load. It will work until a new session triggers the exception.

```
# myapp.py

from random import random

from bokeh.layouts import column
from bokeh.models import Button
from bokeh.palettes import RdYlBu3
from bokeh.plotting import figure, curdoc

# create a plot and style its properties
p = figure(x_range=(0, 100), y_range=(0, 100), toolbar_location=None)
p.border_fill_color = 'black'
p.background_fill_color = 'black'
p.outline_line_color = None
p.grid.grid_line_color = None

# add a text renderer to our plot (no data yet)
r = p.text(x=[], y=[], text=[], text_color=[], text_font_size="20pt",
           text_baseline="middle", text_align="center")

i = 0

ds = r.data_source

# create a callback that will add a number in a random location
def callback():
    global i
    
    # BEST PRACTICE --- update .data in one step with a new dict
    new_data = dict()
    new_data['x'] = ds.data['x'] + [random()*70 + 15]
    new_data['y'] = ds.data['y'] + [random()*70 + 15]
    new_data['text_color'] = ds.data['text_color'] + [RdYlBu3[i%3]]
    new_data['text'] = ds.data['text'] + [str(i)]
    ds.data = new_data

    i = i + 1

# add a button widget and configure with the call back
button = Button(label="Press Me")
button.on_click(callback)

boom = random()
print(boom)
if boom < 0.3333:
  raise Exception('boom!')

# put the button and plot in a layout and add to the document
curdoc().add_root(column(button, p))
```

Example console output:

```
(venv) $ bokeh serve myapp.py 
2018-06-27 12:59:45,343 Starting Bokeh server version 0.13.0 (running on Tornado 5.0.1)
2018-06-27 12:59:45,345 Bokeh app running at: http://localhost:5006/myapp
2018-06-27 12:59:45,345 Starting Bokeh server with process id: 13979
0.5604607908584933
2018-06-27 13:00:06,274 200 GET /myapp (::1) 96.25ms
2018-06-27 13:00:06,437 101 GET /myapp/ws?bokeh-protocol-version=1.0&bokeh-session-id=OxhSy81ZBM8URWfk6wp7OTH7bTictF12u6pI8o7fkIUs (::1) 0.64ms
2018-06-27 13:00:06,437 WebSocket connection opened
2018-06-27 13:00:06,438 ServerConnection created
0.6452850662545722
0.2762922805351794
2018-06-27 13:00:11,120 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7feae4861a58>: boom!
File "myapp.py", line 46, in <module>:
raise Exception('boom!') Traceback (most recent call last):
  File "/home/matt/Clients/QEye/venv/lib/python3.5/site-packages/bokeh/application/handlers/code_runner.py", line 163, in run
    exec(self._code, module.__dict__)
  File "/home/matt/Clients/QEye/isolate/myapp.py", line 46, in <module>
    raise Exception('boom!')
Exception: boom!
 
2018-06-27 13:00:11,125 200 GET /myapp (::1) 25.45ms
2018-06-27 13:00:11,132 WebSocket connection closed: code=1001, reason=None
2018-06-27 13:00:11,207 101 GET /myapp/ws?bokeh-protocol-version=1.0&bokeh-session-id=Y5IlTpoIxVs42drth0tKZonyuwGnUNM3zKK6OAG5eg6n (::1) 0.60ms
2018-06-27 13:00:11,208 WebSocket connection opened
2018-06-27 13:00:11,208 ServerConnection created
```

**Comment by bryevdv** [comment]
Offhand, catching exceptions around here is probably what is necessary

https://github.com/bokeh/bokeh/blob/70f111deb85ee8a9b5b2de845b24b439d64c93a0/bokeh/application/application.py#L153-L174

**Comment by bryevdv** [comment]
Actually issue is that once a hander is marked "failed" it is never reset before the next use.

**Comment by bryevdv** [comment]
Here is a minimal diff that fixes things, but more work is needed, there may be module cleanup or other explicit work that needs to happen to avoid memory leaks, etc. 
```
(base) ❯ git diff
diff --git a/bokeh/application/handlers/code.py b/bokeh/application/handlers/code.py
index 8b96158f5..5a40eb90e 100644
--- a/bokeh/application/handlers/code.py
+++ b/bokeh/application/handlers/code.py
@@ -135,9 +135,6 @@ class CodeHandler(Handler):
         '''

         '''
-        if self.failed:
-            return
-
         module = self._runner.new_module()

         # One reason modules are stored is to prevent the module
@@ -151,7 +148,6 @@ class CodeHandler(Handler):
         old_doc = curdoc()
         set_curdoc(doc)
         old_io = self._monkeypatch_io()
-
         try:
             def post_check():
                 newdoc = curdoc()
diff --git a/bokeh/application/handlers/code_runner.py b/bokeh/application/handlers/code_runner.py
index f2135875e..62a13e4fc 100644
--- a/bokeh/application/handlers/code_runner.py
+++ b/bokeh/application/handlers/code_runner.py
@@ -130,9 +130,6 @@ class CodeRunner(object):
             Module

         '''
-        if self.failed:
-            return None
-
         module_name = 'bk_script_' + make_id().replace('-', '')
         module = ModuleType(str(module_name)) # str needed for py2.7
         module.__dict__['__file__'] = os.path.abspath(self._path)
@@ -150,6 +147,9 @@ class CodeRunner(object):
                 if expected post-conditions are not met after code execution.

         '''
+        self._failed = False
+        self._error = None
+        self._error_detail = None
         try:
             # Simulate the sys.path behaviour decribed here:
             #
```

**Comment by bryevdv** [comment]
Ok, more specifically, this was the way it was because `CodeRunner` may detect and fail on bad code during initialization. So we can't just "reset" the failed state every time, at least not entirely. I think adding a second internal flag to `CodeRunner` will alleviate the issue, though.

**Comment by xhongyi** [comment]
I still have this problem on Bokeh version 1.0.1

**Comment by ltalirz** [comment]
@bryevdv Confirming that this issue still exists in bokeh 1.0.4 and bokeh 1.2.0.
I think this issue should be reopened.

To reproduce, just copy the code from the issue, run `bokeh serve myapp.py` and refresh the page a few times.

**Comment by bryevdv** [comment]
@ltalirz I can't reproduce any problem, so you will have to be more specific with detail. If I run the OP code with Bokeh 1.2.0 and refresh the pages many time, then a page is displayed whenever there is not an exception, and a page is not displayed whenever there is an exception. That is the expected behavior. If the app code that a user writes blows up, there is nothing we can do about that. It is expected that a new working session should work after a previous exception, and that is what I see.

**Comment by ltalirz** [comment]
@bryevdv my apologies - you are absolutely right: for this example app, reloading the page will bring it back to life. 
The reason I thought this was still an issue was that I encountered it in one of my apps, where the app remained dead after the error (under bokeh 1.0.4). I will try to make a minimum example to demonstrate this.

**Comment by bryevdv** [comment]
@ltalirz no worries, if you encounter are real reproducible issues with the latest release, at this point please open a new issue (we can link back here if appropriate)

**Comment by ltalirz** [comment]
Ok: So, it seems to happen *only* when moving the app into a directory, and only with bokeh 1.0.4:
```
mkdir myapp
mv myapp.py myapp/
bokeh serve myapp
```
Now, the app remains "dead" after the first exception.

**Comment by bryevdv** [comment]
@ltalirz I am not sure why that works at all. Directory style apps are required to have a `main.py` (that is what the sever looks for). If that works at all with `myapp.py` I think it is unintentional/accidental

> With bokeh 1.2.0 (which, by the way, is far more responsive), everything seems to be working fine even in this case.

👍

**Comment by ltalirz** [comment]
sorry - I meant main.py
