### ISSUE TITLE
implement ipython widget API

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#805]
if we duplicate the ipython widget API, people should be able to cut and paste from an ipython notebook that uses ipython widgets, into a script that uses bokeh widgets, and then end up with an app-ified version of their ipython notebook.

If we do this completely, we should be able to hook into the ipython publish_display_data stuff to render matplotlib plots along side bokeh ones (though you shouldn't need to do this, but if we do it completely then everything that works in the notebook would work completely outside)

@pzwang @mattpap @bryevdv what do you think?

**Comment by damianavila** [comment]
>I think this can be closed with the addition of push_notebook, thoughts @damianavila ?

As @hhuuggoo mentioned, the scope of the issue in broader than the `push_notebook`... 
Things are starting to fall into some kind of stable API in the IPython widget stuff... so I will take a look on this issue soon (still some things running but probably will be merged for 3.0 release).

**Comment by datnamer** [comment]
+1

There is some interesting stuff going on in this realm:

https://github.com/jupyter-incubator/declarativewidgets
https://github.com/jupyter-incubator/dashboards 

Declarativewidgets has the advantage of integrating with  the Web Components and Polymer elements.

**Comment by bryevdv** [comment]
My feeling after 1-1 discussions with @pzwang and others is to close this discussion. ipywidgets work great with `push_notebook`. If folks want to use notebooks as a way to develop bokeh apps then they should be using bokeh widgets
