### ISSUE TITLE
Inaccurate rendering around 0 on tall bars

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8060]
I have a distribution with very tall bars, and a few really short bars.

When I plot a close up to just see the short bars, you can see that the tall bars do not correctly start at 0, they start just above 0.

![bokeh_plot](https://user-images.githubusercontent.com/1796208/42401557-a83f4e9e-8165-11e8-97a8-13519632291d.png)

![bokeh_plot](https://user-images.githubusercontent.com/1796208/42401540-9c833822-8165-11e8-9eb2-108eb26ac561.png)

You can keep zooming in to the bottom of those tall bars and it will still always render just above 0:

![bokeh_plot](https://user-images.githubusercontent.com/1796208/42401589-d5a42d96-8165-11e8-832f-15c02916db3c.png)

Data: https://github.com/birdsarah/bokeh-miscellany/blob/master/all_counts.csv
Code: https://github.com/birdsarah/bokeh-miscellany/blob/master/all_counts.py
Rendered html: http://htmlpreview.github.io/?https://github.com/birdsarah/bokeh-miscellany/blob/master/all_counts.html

```python
import pandas as pd
from bokeh.io import output_file, show
from bokeh.layouts import layout
from bokeh.plotting import figure

data = pd.Series.from_csv('all_counts.csv')
p_all = figure(tools='save', title='all')
p_all.vbar(data.index, top=data.values, width=0.9)

p_close = figure(tools='save, box_zoom, reset', title='closeup', x_range=(0, 250), y_range=(0, 20))
p_close.vbar(data.index, top=data.values, width=0.9)

l = layout([[p_all], [p_close]])
output_file('all_counts.html')
show(l)
```

**Comment by birdsarah** [comment]
All from Linux.

The above grabs are from Firefox 63.

The effect is worse on Chrome (67):

![bokeh_plot 3](https://user-images.githubusercontent.com/1796208/42401628-156a6828-8166-11e8-9fe4-c18f1d488bc3.png)

**Comment by bryevdv** [comment]
This isn't about zero, it's about canvas bugs rendering rects with endpoints way outside the viewport. PR incoming, but need to find a way to test.
