### ISSUE TITLE
Dashboard example

### ISSUE THREAD

**Issue by Wario7** [bokeh/bokeh#8064]
Hello,

Thank you for continuously developing Bokeh. I believe is a minor issue with the Bokeh Dashboard example bokeh/examples/app/dash/. I downloaded the folder 'Dash' and ran Bokeh serve --show Dash, and everything ran perfectly. However, when I changed the folder name 'Dash' to something else, the CSS did not render completely. It seems static/css/custom.min.css is hardcoded with the Dash name.

I would like to replicate Dash example to run multiple Bokeh apps, and hence why I needed to change one of the folder's name.

Thank you!

**Comment by bryevdv** [comment]
@Wario7 I am not sure what action you would have us take. The example  is just that, and an example.  In particular, the CSS is just a random dashboard template found online, it is not meant to be "official" or be endorsed in any particular way. It's meant only to be illustrative of how anyone might go about constructing a dashboard with a template of their own. I.e. if you need further or different customizations to what is there, you would need to make those yourself. However, as a support question that is appropriate or the mailing list, not the issue tracker.
