### ISSUE TITLE
Zoom and pan v. slow when hover tool is enabled for large datasets

### ISSUE THREAD

**Issue by lukasz-migas** [bokeh/bokeh#8070]
Hi,

Since I've been using Bokeh I have encountered a problem when plotting large 1D datasets using the `line` plotting function. The encountered issues related to an inconsistent behaviour of the zooming functions (either box zoom or wheel) when the hover tool is enabled. These include:
1. When using the `box_zoom `and zooming on any random area of the 1D plot, the operation is extremely slow, whereas if I zoom in the x-direction only (using the entire y-axis range) it is fast.
2. When using the x-axis box zoom (`xbox_zoom`), the operation is slow again which is unexpected since the box zoom in the x-axis (with entire y-axis range) is fast.
3. Same goes for panning when hover tool is enabled it becomes extremely slow.

The behaviour goes back to normal (i.e. fast zooming) when the hover tool is disabled. Is there a reason for this behaviour and any suggestions on I can avoid this?

Here is a minimal example that demonstrates the issue:
```
from bokeh.plotting import figure, show, output_file
from numpy import arange
from numpy.random import randint
TOOLS = "pan,wheel_zoom,box_zoom,reset,save,hover,xbox_zoom"

n_points = 50000
xvals = arange(n_points)
yvals = randint(0, 10000, n_points)

p = figure(tools=TOOLS, title="Random")
p.line(xvals, yvals, line_color="gray")
show(p)
```

My system:
bokeh: 0.12.16 (also in 0.13.0)
OS: Windows 7
Browser: Chrome, Firefox

**Comment by bryevdv** [comment]
50k points is pushing the envelope for standard Bokeh, and depending on the use case is simply out of scope depending on the situation. 

* [Use Holoviews + Datashader](http://holoviews.org/user_guide/Large_Data.html) The datashader package is flexible pre-rasterizer that was created for large data sets (millions/billions of points) but can work fine with 50k. Coupled with Holoviews it can be used from a high level API to drive interactive Bokeh plots that are responsive past what standard Bokeh can offer. 

* Try [Bokeh's webgl renderer](https://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html) This was added to extend Bokeh's capabilities into the larger data sizes, but fill disclosure there are known issues, and there is also currently no maintainer for Bokeh's webgl. It may or may not work depending on browser and use case.
