### ISSUE TITLE
Support preprend on stream

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8072]
Recently asked for something like:
```
source.stream(..., mode="prepend")
```
which would cause new values to be inserted at the beginning of CDS columns, instead of the end. 

Places that will need updating:

* add parameter to function def 

    https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L296 

* update python `data` dict properly, based on the param: 

    https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L296

* Create `ColumnsStreamedEvent` with the proper flag for prepend/append

    https://github.com/bokeh/bokeh/blob/master/bokeh/core/property/containers.py#L351
    https://github.com/bokeh/bokeh/blob/master/bokeh/document/events.py#L337

* Update JS typings for source

    https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/api/typings/models/sources.d.ts

* JS stream API and plumbing:

    https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/sources/column_data_source.ts#L187
    https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/sources/column_data_source.ts#L13

    https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/document.ts

*  various relevant python test locations

    https://github.com/bokeh/bokeh/blob/master/bokeh/models/tests/test_sources.py
    https://github.com/bokeh/bokeh/blob/master/bokeh/core/property/tests/test_containers.py
    https://github.com/bokeh/bokeh/blob/master/bokeh/document/tests/test_events.py
    https://github.com/bokeh/bokeh/blob/master/bokeh/document/tests/test_document.py

* various JS tests for streaming

**Comment by bryevdv** [comment]
Actually, since the potential implementor is no longer available and there has not otherwise been any great interest expressed in this feature, I am just going to close. It occurs to me that if streaming scatter points, the order does not matter, and if streaming line data and needing to "prepend" then the order of the data could simply be reversed, and existing append used.

**Comment by johan12345** [comment]
> and if streaming line data and needing to "prepend" then the order of the data could simply be reversed, and existing append used.

This is true if only prepend is needed. But if both prepend and append are needed for the same plot (e.g. one wants to automatically load missing data when scrolling in any direction), this does not work, right?

**Comment by bryevdv** [comment]
@johan12345 you could split the data into halves between two sources. One that you append to, and another reversed that you "prepend" to. Just to be clear no one has ever actually asked for this, it would be non-trivial to implement and maintain, would likely not perform well, and has a workaround for most (if not all) cases, it's *extremely* unlikely that we will ever do anything here.
