### ISSUE TITLE
Overzealous deduplication of tools for merge_tools

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#8074]
Bokeh has a handy `merge_tools` option, which merges all tools from across plots into a single toolbar, removing any resulting duplicate tools.  That's great, but because it both merges the toolbars and removes duplicate tools, it can't be used when multiple instances of the same tool have been added. For instance, in the left-hand plot here there are multiple PolygonDraw tools:

![image](https://user-images.githubusercontent.com/1695496/42521489-a4a3b3e4-842e-11e8-97ee-a6bcf667c98f.png)

but with `merge_tools=True`, only one of them is retained in the final plot:

![image](https://user-images.githubusercontent.com/1695496/42524738-fe90f850-8436-11e8-8290-f2be4a79e03b.png)

Is there any way that Bokeh could detect that the two original tools are *not* duplicates, and in fact have been configured differently and thus shouldn't be combined together?  Or maybe some tools like the drawing tools should just never be combined when merging?  I'm not sure of precisely the correct solution, but it seems like the current behavior could be improved.

**Comment by bryevdv** [comment]
Deduping was added back when there were only tools like pan and zoom. I'm happy to accept a PR that restricts dupe checking to a specific small list of tool types (i.e. pan, etc)

**Comment by philippjfr** [comment]
>I'm happy to accept a PR that restricts dupe checking to a specific small list of tool types (i.e. pan, etc)

Great, I'll probably be starting on various bokeh PRs when I return from holiday so hopefully that will be ready for the 1.0 release.

**Comment by bryevdv** [comment]
@philippjfr do you still intend to look at this soon or should I change the milestone?
