### ISSUE TITLE
Some markers throw "ValueError: Invalid marker type .."

### ISSUE THREAD

**Issue by lstappen** [bokeh/bokeh#8079]
#### ALL software version info 
Python 3.5.2
Bokeh 0.13.0
OS: Ubuntu 16.04
Using jupyter notebook

#### Description of expected behavior and the observed behavior
Hi!
it seems that not all types (listed here: https://bokeh.pydata.org/en/latest/docs/reference/models/markers.html) of bokeh.models.markers working in this scenario: p.scatter("marker" = <str> ..) 

It works fine for:
  ['asterisk','cross','diamond','hex','square','triangle','x']
It throws an ValueError for:
  ['invertedtriangle','squarecross','circlex','circlecross','diamondcross', 'squarex',]
  e.g. ValueError: Invalid marker type 'InvertedTriangle'. Use markers() to see a list of valid marker types.

Maybe I am wrong, but both should be suitable in this case?

#### Complete, minimal, self-contained example code that reproduces the issue

```
#source['f_markers'] -> list with aligned marker to data

    for m in set(source['f_markers']):
        idx = [i for i in range(len(source['f_markers'])) if m == source['f_markers'][i]]
        source_tmp[m] = ColumnDataSource(data=dict( x       = [source['x'][i] for i in idx],
                                                    y        = [source['y'][i] for i in idx],
                                                    texts    = [source['texts'][i] for i in idx],
                                                    clusters = [source['clusters'][i] for i in idx],
                                                    l_colour = [source['l_colour'][i] for i in idx],
                                                    f_colour = [source['f_colour'][i] for i in idx]
                                                    ))
        p.scatter('x', 'y', line_color='l_colour', legend='top_left', marker=m, fill_color='f_colour', fill_alpha=0.4, size=15, source=source_tmp[m])

```
Regards,
Lukas

**Comment by bryevdv** [comment]
@lstappen can you please expand the code to be a *complete* script that can be immediately run to be investigated, as request?

**Comment by bryevdv** [comment]
Actually, the issue is that you are spelling them wrong. It is e.g. `"inverted_triangle"`, not `"invertedtriangle"`. As the error message states, you can get a list of the valid options by calling the `markers()` function:
```
In [7]: markers()
Available markers:
 - asterisk
 - circle
 - circle_cross
 - circle_x
 - cross
 - diamond
 - diamond_cross
 - hex
 - inverted_triangle
 - square
 - square_x
 - square_cross
 - triangle
 - x
 - *
 - +
 - o
 - ox
 - o+
```

**Comment by lstappen** [comment]
Hi @bryevdv 
Thanks, you are absolutely right. Sry for the inconvenience. 

One last question: How do I get a list like you instead of an "TypeError: 'module' object is not callable"? What I am doing wrong here:
```
from bokeh.models import markers
markers() #print(markers())
```

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-73-a37ce638f024> in <module>()
>       1 from bokeh.models import markers
>       2 
>      3 markers()
> TypeError: 'module' object is not callable

Thanks!

**Comment by bryevdv** [comment]
The `markers` function is in `bokeh.plotting`
