### ISSUE TITLE
ray glyphs not working when figure's y_axis_type='log'

### ISSUE THREAD

**Issue by davidwang20** [bokeh/bokeh#8082]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Using bokeh 0.13.0 on jupyter notebook, Mac, Safari

#### Description of expected behavior and the observed behavior
When a ray is placed on a figure with y_axis_type='log', the ray does not appear on the figure when plotted. However, when y_axis_type is 'linear', the ray works fine.

#### Complete, minimal, self-contained example code that reproduces the issue
```
p = figure(y_axis_type='log')
p.ray(x=[0], y=[0], length=0, angle=np.pi/2, line_width=1)
p.ray(x=[0], y=[0], length=0, angle=np.pi*3/2, line_width=1)
show(p)
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/25164585/42774841-cfc13e8a-8900-11e8-81c8-8be2f95f142a.png)

**Comment by bryevdv** [comment]
What exactly is supposed to happen? I can't think of a sensible interpretation of what a ray on a log scale should be or do.

**Comment by davidwang20** [comment]
well given that on a linear scale these angles produce a vertical bar, I'd say something similar should happen on the log scale. Whether at non-vertical/horizontal angles it should be visually transformed according to the log transform or still a straight line is probably a debatable issue

**Comment by davidwang20** [comment]
here it is on the linear scale
![image](https://user-images.githubusercontent.com/25164585/42776786-1bb57680-8906-11e8-9dad-58b4371fadc3.png)

**Comment by bryevdv** [comment]
It looks like you want some kind of infinite vertical line? The appropriate way to achieve that is with a `Span` annotation:

```
from bokeh.models import Span
p = figure(y_axis_type='log', x_range=(-5, 5), y_range=(10e-10, 10e10))
span = Span(location=0, dimension='height', line_color="red")
p.add_layout(span)
```

<img width="642" alt="screen shot 2018-07-16 at 13 38 20" src="https://user-images.githubusercontent.com/1078448/42776755-a23625f0-88fd-11e8-936e-2e77c5aa66d8.png">

Since a ray in the completely general (i.e. not purely vertical or horizontal) sense is not really sensical on a log scale, and a reasonable alternative is presented, I am closing this `wontfix`

**Comment by davidwang20** [comment]
I see. The reason I used the ray glyph instead of span was so that I could add it to a plot legend and click to hide. Is there any way to do that with a span annotation?

**Comment by bryevdv** [comment]
No, but in that case I would suggest a single `line` is better anyway:

```
from bokeh.io import output_file, show
from bokeh.models import Legend, LegendItem
from bokeh.plotting import figure

from bokeh.models import Span
p = figure(y_axis_type='log', x_range=(-5, 5), y_range=(10e-10, 10e10))
span = Span(location=0, dimension='height', line_color="red")

r = p.line(x=[1,1], y=[10e-20, 10e20])
p.add_layout(span)
p.add_layout(Legend(items=[LegendItem(label="span", renderers=[r])]))

show(p)
```

<img width="599" alt="screen shot 2018-07-16 at 13 46 59" src="https://user-images.githubusercontent.com/1078448/42777116-bb485b8e-88fe-11e8-8039-04d7d1673b0f.png">


As this has now entered "general support question" territory I have to request that further discussion move to the mailing list.
