### ISSUE TITLE
Improve reliability, performance and feature coverage of the layout

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#8084]
This is a meta issue addressing specific issues with the layout (`tag: layout`). 

* [x] words_and_plots.py
    blank until browser resize, DOM text on top of iris plot after

* [x] models/glyphs.py
    tab bars truncated

* [x] dash
    range plot on top of (covering) the line plot

* [x] gapminder
    widgets on top of scatter plot
    plot can overlap top of text below
    Play/Pause does not work

* [x] movies
    FIXED_SIZING_MODE warning
    huge gap between top text and bokeh content, until browser resize, then snaps to place

* [x] OHLC
    would be nice if sliders and button were vertically aligned

* [ ] spectrogram (issue #8710)

    - [x] slider label overlaps text above
    - [ ] would be nice if right plot top/bottom border aligned with tops/bottoms of plots to the left

* [ ] integration/glyphs/hex_tile (issue #8711)

    Last column of plots has too narrow left panel (minus sign is cut). This isn't strictly an issue with the new layout, but a problem with the range-based aspect management scheme, which doesn't work well with old layout either, causing infinite update loops (e.g. plotting/file/aspect).

* [ ] add `GridPlot` model and make handling of a toolbar an implementation detail

* [x] finalize implementation of flow layout (`HTMLBox`, `Div`, some other widgets)

* [x] add support for tabs scrolling (or some other mechanism, e.g. a dropdown)

- [x] Fix performance for larger dashboards with many widgets, divs etc. (see https://github.com/bokeh/bokeh/pull/8085#issuecomment-459345949 for an example app)

- [x] Ensure that changes to width/height and other layout related properties trigger a new layout

- [x] Avoid slider widgets cutting off the handle and text (see https://github.com/bokeh/bokeh/pull/8085#issuecomment-459207880)

**Comment by mattpap** [comment]
(based on https://github.com/bokeh/bokeh/pull/8085#issuecomment-451315916)

@mattpap I went though maybe ~80% of examples. Things are generally very good but I wanted to leave some observations for you before merging, at least 1 or 2 need some attention:

* [x] ~~line_compare.py~~
    line join/end options have no effect

* [ ] marker_compare.py
    Tabs run off screen

* [x] ~~sizing_mode.py~~
    changes to dropdown have no effect at all
    FIXED_SIZING_MODE warning

* [ ] events_app.py,  js_events.py
    pan/mouse move events no longer triggering (TypeError: undefined is not an object (evaluating 't.frame.xscales')) this seems like fix will be simple

* [x] ~~prevent_user_zooming_or_panning_too_far.py~~
    weird interaction with bounds, pops cursor off plot when attempting to pan up

* [ ] words_and_plots.py
    blank until browser resize, DOM text on top of iris plot after

* [ ] models/glyphs.py
    tab bars truncated

* [x] ~~surface3d~~
    blank (TypeError: undefined is not an object (evaluating 'models.map')) seems like fix will be simple

* [ ] dash
    range plot on top of (covering) the line plot

* [ ] gapminder
    widgets on top of scatter plot
    plot can overlap top of text below
    Play/Pause does not work

* [ ] movies
    FIXED_SIZING_MODE warning
    huge gap between top text and bokeh content, until browser resize, then snaps to place

* [ ] OHLC
    would be nice if sliders and button were vertically aligned

* [ ] spectrogram
    slider label overlaps text above
    would be nice if right plot top/bottom border aligned with tops/bottoms of plots to the left 

* [ ] integration/glyphs/hex_tile

    Last column of plots has too narrow left panel (minus sign is cut). This isn't strictly an issue with the new layout, but a problem with the range-based aspect management scheme, which doesn't work well with old layout either, causing infinite update loops (e.g. plotting/file/aspect).

**Comment by philippjfr** [comment]
TODO

- [ ] Fix performance for larger dashboards with many widgets, divs etc. (see https://github.com/bokeh/bokeh/pull/8085#issuecomment-459345949 for an example app)
- [ ] Ensure that changes to width/height and other layout related properties trigger a new layout
- [ ] Avoid slider widgets cutting off the handle and text (see https://github.com/bokeh/bokeh/pull/8085#issuecomment-459207880)

**Comment by bryevdv** [comment]
I'll consolidate everything in this issue later today. For now just a reminding myself about Tabs when width is too small.

**Comment by bryevdv** [comment]
@mattpap @philippjfr OK I have consolidated the remaining open issues into the top. We need to prioritize these. For reference, I would like to release 1.1 next week -- monday or tuesday. The critical things I am aware of are:

* tab re-layout
* perf issue desribed by @philippjfr 

are there others? Please edit the issue at the top to highlight or call out anything that should be regarded as critical for 1.1

**Comment by philippjfr** [comment]
Just to provide a bit more color for the performance issue, I've recorded some screencasts comparing the before and after.

[Here is a screencast](https://imgur.com/a/RvBFvOD) of the sample app with 1.0.4 and here is the performance profiling output for two events:

![screen shot 2019-02-12 at 6 29 36 pm](https://user-images.githubusercontent.com/1550771/52659110-816fda80-2ef4-11e9-81d4-cf549d867201.png) 

[Here is a screencast](https://imgur.com/a/3DTq3Bu) of the sample app with current master and here is the performance profiling output for two events:

![screen shot 2019-02-12 at 6 16 56 pm](https://user-images.githubusercontent.com/1550771/52659145-90568d00-2ef4-11e9-8f63-5222b3040542.png)

You can see that it goes from 100 ms in 1.0.4 (which feels instantaneous) to about 1 second on master (with a noticeable lag). It's slightly better when the profiler is not enabled.

**Comment by mattpap** [comment]
> , I would like to release 1.1 next week -- monday or tuesday.

That's unrealistic in my opinion. I would say last week of February (in two weeks) would be better.

**Comment by bryevdv** [comment]
ok, I think @philippjfr wanted more time as well, but I would say it is important to have 1.1 before the end of the month.

**Comment by bryevdv** [comment]
FYI regarding the issue above, removing some of the redundant/extraneous nesting did result in a significant improvement. But @philippjfr will post more info later.

**Comment by mattpap** [comment]
I already investigated this in the PR. De-nesting will help, but the problem is with super slow measurement procedure of arbitrary HTML components. When replaced by a constant, speed improves a factor of 10-20, which translates to layout under 50ms in my VM.

**Comment by philippjfr** [comment]
I've been able to reduced the nesting in my example by one level by eliminating the use of widget boxes in panel. That indeed makes a fair difference but it would of course still be great if we could speed up the measurement procedure.

**Comment by philippjfr** [comment]
Should I be opening new issues for other issues I've encountered? If I display the app example in a notebook and navigate away from and back to the notebook tab this is what happens to the layout:

![screen shot 2019-02-13 at 1 32 07 pm](https://user-images.githubusercontent.com/1550771/52715283-f1816d80-2f93-11e9-9326-ba2f7a9ec8fd.png)

**Comment by mattpap** [comment]
@philippjfr, yes, this one in particular deserves individual treatment.

**Comment by birdsarah** [comment]
>  The critical things I am aware of are .....

I would include the lack of axis alignment (#8643) as a critical issue. If everyone runs 1.1 and all their plots have moved I would imagine it will be regarded as a serious regression. The whole point of the original layout PR was that things were aligned. You could already lay things out.

**Comment by bryevdv** [comment]
> You could already lay things out.

Yes and no :) There were lots of ways to break the original layout before the solver existed. And after it was added there were easily obtainable combinations of stretch/scale modes that led to bad results, or just nothing rendering at all. Also the solver overhead made it impossible to have more than ~10 plots on a page. I've gotten explicit feedback from users that fixing these bugs and limitations is far  more pressing, especially when you consider typical dashboards don't seem to rely on this capability. A random GIS image search for "dashboard" mostly yields a lot of individual stretchy plots in a individual cells:

<img width="250" alt="screen shot 2019-02-13 at 08 32 35" src="https://user-images.githubusercontent.com/1078448/52727396-f8938600-2f69-11e9-94e8-cacb81cd1a2a.png">

<img width="250" alt="screen shot 2019-02-13 at 08 41 21" src="https://user-images.githubusercontent.com/1078448/52727950-2c22e000-2f6b-11e9-95f8-1255651a1e09.png">

Just this kind of simple thing (which has no fancy alignment) is what people are clamoring to be able to do, and to be frank, what they are sometimes choosing to use other tools for, for lack of. In hindsight I'd say I would say that in prioritizing the alignment capability, I optimized for the wrong feature up front (that decision is entirely on me).

So where are we now? I think it's possible to restore the the axis alignment, and that we should work towards that. AFAIK @mattpap has concrete ideas about a grid-span approach. But I don't think we should wait months to release if that's how long it takes with part time resourcing. Or in other words that ultimately, if it really comes down to it, the user pain points that have actually come up in real experience are acute enough that fixing them would justify this one step back for now. 

Would like others thoughts, though.

**Comment by birdsarah** [comment]
I'm going to agree with you while disagreeing very strongly :-D

1) You buried the lead, alignment is largely working! That was not clear from your comment or from responses to my issue. Check out this tortured version of the gridplot example which, aside from the left title looks great

![screenshot from 2019-02-14 00-36-59](https://user-images.githubusercontent.com/1796208/52767728-fd4f4d00-2ff0-11e9-9fc3-f1d4d6f843b7.png)

That's with stretch_both, but all sizing modes look good (except scale_both but not in a way that's unovercome-able)

I am guessing that the issue is alignment when a plot spans multiple columns of a grid. I am happy to agree that's a secondary consideration.

----

2) When alignment is really important

2a) I have spent a lot of the last 6 months looking at grids of plots. If they all have, for example, the same x-axis but different quantities on the y-axis you want to be able to scan for patterns. I don't think that my experience is uncommon. I think that science-y use cases should hold equal weight to dashboard-y use cases. As I said earlier, the fact that grids work make me less concerned.

2b) In the equal weighting of dashboardy-to-sciency...to offer some counter examples, matplotlib and ggplot provide options for alignment, a quick search yielded these two tutorials covering how to get things lined up: https://www.python-course.eu/matplotlib_multiple_figures.php, https://www.andrewheiss.com/blog/2017/08/10/exploring-minards-1812-plot-with-ggplot2/. 

3) It seems dangerous to compare a rate of complaints about things that need to be fixed, with an absence of complaints about a thing that works

**Comment by birdsarah** [comment]
@mattpap is that left-title-when-no-axis issue a known issue. Let me know if not and I'll open an issue.

**Comment by philippjfr** [comment]
So I decided to have a look at the performance issues myself and immediately got quite confused by the profiler output. According to this it looks like the sized utility is making a bunch of calls to the inline function which computes the size:

![screen shot 2019-02-21 at 7 37 54 pm](https://user-images.githubusercontent.com/1550771/53196591-5847fc00-3610-11e9-963b-c5c5153cfeff.png)

But if I look at the sized utility function it should only ever run the content_size utility once. So unless I don't know how to read the profiler output this makes zero sense. Any idea what's going on there @mattpap?

**Comment by mattpap** [comment]
@philippjfr, in grids and nested layouts measures are taken in batches, and this is nicely visible in this profile. A single widget will have its measurement function called multiple times with different viewports, to optimize its size. Some of those measurements could be eliminated or at least cached (in future development). However, the major source of slowdown is nicely shown in violet color. This is CSS layout triggered by widgets' measurement function. Unfortunately I significantly underestimated how inefficient the approach is. But now worries, I'm hoping to have a PR fixing this tomorrow.

**Comment by mattpap** [comment]
> Avoid slider widgets cutting off the handle and text

@philippjfr, is this sill an issue? Slider now allocates more space to accommodate for the handle, so it should look better.

**Comment by philippjfr** [comment]
It seems to be fine now, and one can always increase the margin if necessary.
