### ISSUE TITLE
Use generators instead of lists

### ISSUE THREAD

**Issue by pratapvardhan** [bokeh/bokeh#8092]
For built-in Python functions use generators instead of lists.

For example in  `./bokeh/core/enums.py:121`

```
attrs = dict([ (value, value) for value in values ])
```

can be

```
attrs = dict((value, value) for value in values)
```

Similarly, there are other instances of these `list` creations -- should we clean these up to use generators instead?

If the dev's think so too, I'll submit a PR.

**Comment by bryevdv** [comment]
@pratapvardhan sure but as long as you are doing that, might as well use dictionary generators:
```
attrs = { value: value for value in values }
```
