### ISSUE TITLE
--allow-websocket-origin flag for jupyter-notebook

### ISSUE THREAD

**Issue by axil** [bokeh/bokeh#8096]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 0.13.0
python 3.6.4
notebook 5.4.0
Linux debian-s-1vcpu-1gb-lon1-01 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
Chrome

#### Description of expected behavior and the observed behavior
I'm running a "notebook_embed" example with a jupyter running on a non-standard port:

    jupyter-notebook --no-browser --port 8080

I'm getting an error

    ERROR:bokeh.server.views.ws:Refusing websocket connection from Origin 'http://localhost:8080';
    use --allow-websocket-origin=localhost:8123 to permit this; currently we allow origins 
    {'localhost:8888'}  
    WARNING:tornado.access:403

I expect to see a slider and a plot.

Standalone bokeh has this flag, but jupyter-notebook doesn't yet have it.

#### Complete, minimal, self-contained example code that reproduces the issue
see https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/notebook_embed.ipynb

**Comment by bryevdv** [comment]
The notebook does not allow access to the front end hostname/port as a matter of policy. We have no control over this. You have to set this value yourself, by explicitly passing `notebook_url` to `show`. If you are unhappy with this, please feel free to lobby the Jupiter team to change their decision.

**Comment by axil** [comment]
Actually it's not about changing the main port programmatically. I'm quite happy with setting it in the command line. The problem is that embedding the server into the notebook (as described in the official example "notebook-embed.ipynb") opens a second socket connection. And jupyter allows doing so only when the notebook itself runs from the standard 8888. For example even 8889 breaks this example from working.

**Comment by bryevdv** [comment]
I've run the example notebook on different ports many times. That message about a refused connection is a bokeh message, not from the notebook. It's telling you what I already said: you have to set notebook_url yourself to match the current notebook url.

**Comment by soerendip** [comment]
Unfortunately, the port is sometimes not known before the notebook has started. Is there a way to get the port from the running notebook and set it dynamically?

**Comment by bryevdv** [comment]
@soerendip I have asked the Jupyter developers to provide some supported capability to obtain the port for years, and they consistently refuse. There is, unfortunately, nothing I can do about that. I can only suggest you make a request directly to the Jupyter project on their issue tracker.

**Comment by gowestyang** [comment]
The solution is in the error message:

 `
import os
os.environ["BOKEH_ALLOW_WS_ORIGIN"] = '0lj9hh483va927cadklatiu5affjj5cn3b349he4cl71d36qc4p6'
`

Replace the long string in my example to whatever in your error message.
