### ISSUE TITLE
RangeTool Unusable after selection change

### ISSUE THREAD

**Issue by prinsniels** [bokeh/bokeh#8103]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 0.13.0
python 3.5.2
firefox 61.0.1 (no other browsers tested)
ubuntu 16.04 LTS

#### Description of expected behavior and the observed behavior
When dragging the most left side of the RangeTool selection box past the most right side of 
the selection box, the selection box becomes unresponsive. 
- It's no longer possible to change the selection via RangeTool selection box.

I would expect;
- the selection box to be responsive after the occurrence 
- the left side of the selection box to  become the right side of the selection box.  

#### Complete, minimal, self-contained example code that reproduces the issue
Reproduction;
- download the DASH example from https://github.com/bokeh/bokeh/tree/master/examples/app/dash
- run the app via 'bokeh serve --show dash'
- in the network activities area, select the left side of the selection box and drag it to the right, past the right side of the selection box
- the error will occur, it's no longer possible to interact with the selection box 

#### Stack traceback and/or browser JavaScript console output
Error: invalid bbox {x0: 532.2222175882293, y0: 2, x1: 531.9715398667136, y1: 48.3125} bbox.js:44
e
bbox.js:44
o</h</t.prototype.interactive_bbox
box_annotation.js:102
o</h</t.prototype.interactive_hit
box_annotation.js:112
o</u</t.prototype._hit_test_renderers
ui_events.js:176
o</u</t.prototype._trigger
ui_events.js:190
o</u</t.prototype._mouse_move
ui_events.js:337
o</u</t.prototype._configure_hammerjs/<
ui_events.js:61

#### Screenshots or screencasts of the bug in action
![screenshot from 2018-07-24 10-15-33](https://user-images.githubusercontent.com/8694100/43125556-ac6e696e-8f2a-11e8-8d55-a5b8a504c9f6.png)

**Comment by bryevdv** [comment]
AFAICT this was fixed in #8806
