### ISSUE TITLE
Feature Request: VerticalLine marker (equivalent to marker='|' in matplotlib)

### ISSUE THREAD

**Issue by gregmuellegger** [bokeh/bokeh#8109]
There is an extensive list of markers available in bokeh: https://bokeh.pydata.org/en/latest/docs/reference/models/markers.html

What I am missing is an equivalent for the `marker='|'` in matplotlib: https://matplotlib.org/examples/lines_bars_and_markers/marker_reference.html

My usecase is to denote different types of events on a timeline, so that it looks like this:
![image](https://user-images.githubusercontent.com/88278/43193195-a0307ed2-8fff-11e8-8c2e-327e3e65d022.png)

A circle or asterisk is not fine grained enough for this as the horizontal space taken by the marker is too broad so that the actual center of different markers is hard to compare visually.

**Comment by bryevdv** [comment]
@gregmuellegger this would be a good task for a new contributor, would you be interested in working up a PR for it with some guidance?

**Comment by gregmuellegger** [comment]
@bryevdv Yes! I would like to give it a try. I've setup the environment like explained here: https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup

I assume the next steps will be:

- Adding a Marker Glyph model
- Adding the corresponding code in bokehjs
- Adding an example containing the glyph
- Write tests
- Write documentation
- Update the object list here: https://bokeh.pydata.org/en/latest/docs/dev_guide/models.html

Are these the necessary steps? Did I forget something?

**Comment by gregmuellegger** [comment]
I have a problem though executing the following command:

```
$ python setup.py develop --build-js
Building BokehJS... Failed.

ERROR: 'node make build' returned the following

---- on stdout:
    npm >=6.0 <7.0 is required. Current version is 5.6.0.


---- on stderr:

```

Even though I installed nodejs via `conda install -c bokeh nodejs`.

Do you know where this might be coming from?

**Comment by mattpap** [comment]
@gregmuellegger, you need to `npm install -g npm` to get the most recent version.
