### ISSUE TITLE
Visualizing Tree Structure

### ISSUE THREAD

**Issue by OnurYigitArpali** [bokeh/bokeh#8111]
I realized that there is no example to visualize tree structure. So, we have been working on tree visualizing especially decision trees. We contacted the community on gitter and we are advised to create PR. I am creating this issue in preparation for our PR.

**Comment by Rgtemze** [comment]
#8112 is related to this.

**Comment by bryevdv** [comment]
Thanks for the info @OnurYigitArpali In this particular case, I would prefer to have the PR itself be the issue. We do use and prefer "issue PRs" in some cases. I will copy the text above to the PR and close this issue
