### ISSUE TITLE
bokeh on Google Colaboratory (missing bokehJS)

### ISSUE THREAD

**Issue by ahuang11** [bokeh/bokeh#8116]
Chrome
bokeh==0.13.0

A simple bokeh plot isn't showing; seems like bokehJS is missing on Google Colaboratory

```
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()

# create a new plot with default tools, using figure# creat 
p = figure(plot_width=400, plot_height=400)

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=15, line_color="navy", fill_color="orange", fill_alpha=0.5)

show(p) # show the results
```

![image](https://user-images.githubusercontent.com/15331990/43359012-170260f0-9250-11e8-83fb-776874349731.png)

**Comment by bryevdv** [comment]
Looks like they are blocking external JS loads. You will have to take this up with them, there is nothing we could do about it.

**Comment by bryevdv** [comment]
Actually, it does look like the CDN resources are loading. Is still say this is something to take up with them. We test with classic Jupyter notebook and Jupyter lab. That's all we have resources to support so if it's not working on some like Google collab they will have to fix whatever they broke on their end, or offer some guidance.

**Comment by bryevdv** [comment]
It is possible, for instance, that they block execution of Java script, even if the CDN files load, which is something only they could control.
