### ISSUE TITLE
Update documentation for how to use Bokeh Server with JupyterHub environment

### ISSUE THREAD

**Issue by cbanek** [bokeh/bokeh#8120]
In https://github.com/bokeh/bokeh/pull/7686#issuecomment-403549738,
it was suggested that I should update the docs concerning notebooks about how to use the new functionality to enable using the Bokeh server in a JupyterHub environment.

This issue tracks creating docs for this.

**Comment by bryevdv** [comment]
Awesome, thanks @cbanek for looking into this
