### ISSUE TITLE
rename joyplots to ridgeplots

### ISSUE THREAD

**Issue by zanarmstrong** [bokeh/bokeh#8128]
Hi Bokeh team, 

I love the data you used to illustrate your [joyplot.py](https://bokeh.pydata.org/en/latest/docs/gallery/joyplot.html) example. The dataset is such a good application of this chart type. 

A number of other viz libraries have started using the term "ridgeline plots" instead of "joy plots", including Seaborn, R, Semiotic, and Bostock's examples. 

In Observable, Bostock [explained](https://beta.observablehq.com/@mbostock/d3-ridgeline-plot) that: "This form is also known as a joy plot for its notable use on the cover of Joy Division’s Unknown Pleasures album. This name is controversial as it references the sexual slavery practices of the Nazis during World War II. However, Joy Division sought to draw attention to the danger of fascism to society, not to celebrate it."

More details from Claus Wilke, who had created ggjoy (now ggridges): https://serialmentor.com/blog/2017/9/15/goodbye-joyplots

I just recently learned from a colleague about this darker history of such a seemingly joyful name (and the name itself is pretty new... only started being called joyplots in 2017). I happened to be in the repo looking for something else, and thought I'd give you guys a head's up while I was here so you can decide what makes sense for the Bokeh examples. 

Thanks for all your great work!

**Comment by bryevdv** [comment]
@zanarmstrong would you be interested in submitting a PR to do this?

**Comment by zanarmstrong** [comment]
Happy to do it. 

To set expectations on timing, it might be a little while before I get to it. But, there is no rush :).

**Comment by bryevdv** [comment]
@zanarmstrong great, look forward to your contribution!

**Comment by bryevdv** [comment]
Also just to help when you get started I think these are the only four places that need updating:

https://github.com/bokeh/bokeh/search?q=joy&unscoped_q=joy

**Comment by bryevdv** [comment]
@zanarmstrong I'd like get this done before 1.0 which is close-ish, just a friendly heads up that I (or someone else) might take a poke at this in the near future if you don't have the bandwidth to

**Comment by zanarmstrong** [comment]
Thanks for doing this. Sorry for my dropping the ball on it!
