### ISSUE TITLE
Cannot display full datetime

### ISSUE THREAD

**Issue by kdodia** [bokeh/bokeh#813]
As noted in [this](http://stackoverflow.com/questions/24680318/bokeh-datetime-axis-should-show-all-yyyy-mm-dd-hh-mm-ss) SO question, Bokeh's datetime axis does not expose the full datetime, but a contextual subset of labels based on the zoom level.

**Bugfix**
An option should be made to enable full datetime rendering at all levels.

**Feature**
Optionally, a string formatting (along the lines of strftime) syntax could also be exposed.

**Comment by damianavila** [comment]
I think this is also covered by #1854, I am right @mattpap?

**Comment by mattpap** [comment]
No, I don't improve date handling in that PR.

**Comment by damianavila** [comment]
OK, thanks!

**Comment by joaquin386** [comment]
Is this issue still around?

**Comment by bryevdv** [comment]
Well, there is nothing added to the core library specifically, but unlike when the question was first posed, it's now possible for users to extend Bokeh with their own custom model classes, including their own custom `TickFormatters`. For example, here is an example from a recent StackOverflow thread that formats log tick labels as just the exponent:
```
from bokeh.plotting import figure, output_file, show
from bokeh.models.formatters import TickFormatter

x = [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
y = [10**xx for xx in x]

output_file("log.html")

class MyTickFormatter(TickFormatter):
    __implementation__ = """
        Model = require "model"

        class MyTickFormatter extends Model
          type: 'MyTickFormatter'

          doFormat: (ticks) ->
            return ("#{ Math.log10(tick) }" for tick in ticks)

        module.exports =
          Model: MyTickFormatter
    """

# create a new plot with a log axis type
p = figure(plot_width=400, plot_height=400,
           y_axis_type="log", y_range=(10**-1, 10**4))

p.line(x, y, line_width=2)
p.circle(x, y, fill_color="white", size=8)

# use the custom TickFormatter
p.yaxis[0].formatter = MyTickFormatter()


show(p) 
```

There is already a very broad "built-in" capability with the existing `DateTime` and `Printf` tick formatters. This does not cover every potential situation, but trying to explicitly cover every such use case in the core library would make it unmaintainable and difficult to use as well  With custom models, user's have absolute control and capability to do what they need in any situation. I am inclined to just say that this extension capability is now the answer to the question, and to close this issue. Thoughts @bokeh/dev ?

**Comment by bryevdv** [comment]
To be clear, the extension process can still be made more convenient, and certainly needs more explicit documentation, but the library has grown to a point that we have to be more considered an conservative about what to add, because "yes is forever" in terms of maintenance.

**Comment by canavandl** [comment]
Conversely, you specify a DatetimeTickFormatter with all of the zoom levels set to the full datetime format that you want ( @joaquin386 ) :

```python
DATETIME_FORMAT = dict(
    microseconds=["%m/%d/%y %I:%M:%S %p"],
    milliseconds=["%m/%d/%y %I:%M:%S %p"],
    seconds=["%m/%d/%y %I:%M:%S %p"],
    minsec=["%m/%d/%y %I:%M:%S %p"],
    minutes=["%m/%d/%y %I:%M:%S %p"],
    hourmin=["%m/%d/%y %I:%M:%S %p"],
    hours=["%m/%d/%y %I:%M:%S %p"],
    days=["%m/%d/%y %I:%M:%S %p"],
    months=["%m/%d/%y %I:%M:%S %p"],
    years=["%m/%d/%y %I:%M:%S %p"],
)

formatter = DatetimeTickFormatter(formats=DATETIME_FORMAT)
```

**Comment by bryevdv** [comment]
There is also a proposal in #4462 to add another built-in capability that would let users specify a python function (to be compiled to JS automatically) for purposes of formatting ticks. This also seems like a better solution since it is both general and simple. Bokeh already has alot of "knobs and dials" and I am loathe to add more for very specific cases.  Combined with the info from @canavandl which also works with current releases, I am going to close this issue as `invalid`
