### ISSUE TITLE
Docstrings not clear for dimension property for Band, Span and Whisker class

### ISSUE THREAD

**Issue by cao-jacky** [bokeh/bokeh#8131]
In using Whisker to plot error bars on figures there is a lack of information associated with the ``dimension`` property - it is not clear how you should use it. 

The correct method is to specify ``dimension=height`` for error bars aligned in the ``y``-direction and ``dimension=weight`` for error bars aligned in the ``x``-direction. 

The docstrings should be updated for this property to help users on how to use it.

**Comment by bryevdv** [comment]
@cao-jacky here is the location of the helps string for that property if you'd like to submit a PR that would be appreciated 

https://github.com/bokeh/bokeh/blob/master/bokeh/models/annotations.py#L1021-L1023
