### ISSUE TITLE
Turn off self.validate checks during update

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#8138]
When running a Bokeh server with streaming updates in my application I often find that bokeh takes up 30% of the CPU time, about half of which is consumed by the following self.validate checks:

```diff
diff --git a/bokeh/core/property/bases.py b/bokeh/core/property/bases.py
index d28aa2b..a50ed9e 100644
--- a/bokeh/core/property/bases.py
+++ b/bokeh/core/property/bases.py
@@ -260,7 +260,7 @@ class Property(PropertyDescriptorFactory):
 
         '''
         try:
-            self.validate(value, False)
+            # self.validate(value, False)
         except ValueError as e:
             return False
         else:
@@ -275,7 +275,7 @@ class Property(PropertyDescriptorFactory):
 
     def prepare_value(self, obj_or_cls, name, value):
         try:
-            self.validate(value)
+            # self.validate(value)
         except ValueError as e:
             for tp, converter in self.alternatives:
                 if tp.is_valid(value):
```

I would like some way to disable these, preferably without clobbering with other users' Bokeh experience (my bokeh server application is often embedded within other Jupyter sessions, where the user may use Bokeh on their own).

So some questions:

1.  Does the current environment variable solution with `BOKEH_VALIDATE_DOC=0` disable these checks?
2.  Is there some way I can turn them off programmatically,rather than tweaking an environment variable?  
3.  Is there some safe way that I can mark all of the properties that I care about as being safe and not needing validation, while not affecting other users' experience?

Some thoughts:

1.  Can we construct a function that propagates through a figure, CDS, or doc and marks all properties as not needing to be validated?
2.  Can we temporarily set a global before and after calling update/stream/patch that signals bokeh to not validate during that period but unset it directly afterwards?

    ```python
    with bokeh.no_validate:
        source.update(...)
    ```

Follows on from https://github.com/bokeh/bokeh/issues/6042

**Comment by bryevdv** [comment]
1) No, `BOKEH_VALIDATE_DOC` only affect document validation checks at serialization time, not property type validation 

2) There is a way to turn off document validation checks programmatically, there is not a way to turn of property type validation checks. 

3) No, but only vacuously, because there is currently no way at all to mark any properties as not needing validation

Regarding possible implementations, I guess it boils down to how fine grained we would like to be. Options:

* mark individual properties, definitely tedious without some helper API

* mark code blocks with context managers, could be OK but not my pref

* mark entire update functions with a decorator, i.e.

    ```
    @without_property_validation
    def update(attr, old, new):
        # do stuff
    ```

My personal preference is the decorator, but I am open to arguments why other approaches are better.

**Comment by mrocklin** [comment]
The decorator would be fine with me if that would work on the Bokeh side.  As a performance-conscious Bokeh user I'm pretty willing to do stuff on my end to make this happen.

**Comment by bryevdv** [comment]
@mrocklin great I am happy to collaborate on this. Ideally, a PR would add:

* an implementation of the decorator (I think you have a handle on how this would look)
* docstring for the decorator
* new subsection in "Running a Bokeh Server" users guide chapter
* a test that verifies the operation of the decorator, offhand probably via mocking the validate function somehow

I'd say put up a PR with whatever subset of that you are free to finish and I will take it from there.

**Comment by mrocklin** [comment]
Is it OK to communicate the "don't validate" message through some global variable that the result of the decorator mutates while calling?  Or is there some more clever way?

**Comment by bryevdv** [comment]
I think it's ok to start with that. Or if you want to wrap the global state in some API function that'd be ok. I suppose that has the added benefit of being accessible to e.g. someone wanting to speed up standalone plot generation in a flask app
