### ISSUE TITLE
Span location cannot accept datetime whereas Labels can deal with it.

### ISSUE THREAD

**Issue by jasonsross** [bokeh/bokeh#8142]
OK I hope this is an easy one. I'm working with spans and labels for the spans and I see that the Span object requires an Integer location meaning you have to do a little bit of conversion to your datetime data whereas Labels can accept a datetime object directly for the x argument and automatically converts it to microseconds since epoch. So when I make a span and a label for the span next to it, I'm coding the x-axis location differently (saving a bit of code by not converting the location for the Label)

Since the formulation for automatic conversion of datetimes to integer exists for Labels, it would be nice to use the same thing for Span's and thus relax the integer type requirement for the location argument.

**Comment by bryevdv** [comment]
@jasonsross This is an easy one, tho the few core devs are underwater with other tasks right now, so perhaps you can work up a PR? 

You need to add a `.accepts` clause to the `location` property of `Span` here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/annotations.py#L850-L852

You can find a model of exactly the kind of change necessary here on `Label`:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/annotations.py#L588

As a bonus, both `Label` and `Span` could use a short test to verify that the datetime conversion happens, which would help ensure there are no future regressions.

**Comment by jasonsross** [comment]
OK I will try working on it now.

**Comment by bryevdv** [comment]
Great! let me know if I can answer any questions

**Comment by jasonsross** [comment]
@bryevdv Sorry I'm new to package development so hoping you can provide a little guidance before I submit my PR.

I've followed the How to Contibute guide, forked bokeh, created a branch with this issue# and name, edited the location argument of the Span class in annotations.py and committed it to my local branch (code below since it's short)


```
class Span(Annotation):
    """ Render a horizontal or vertical line span.

    """

    location = Float(help="""
    The location of the span, along ``dimension``.

    Datetime values are also accepted, but note that they are immediately
    converted to milliseconds-since-epoch.
    """).accepts(Datetime, convert_datetime_type)
"""
```


I'm just at a little loss about what to do with the test_annotations.py script in order to verify datetime conversion happens. I tried modifying the test_Span() method as follows and calling it to ensure no assertion errors, is that what you meant?

```
def test_Span():
    line = Span(location = pd.to_datetime('2018-01-01'))
    assert line.plot is None
    assert type(line.location) is float
```

**Comment by bryevdv** [comment]
The first change looks perfect. Regarding the test, I would make a new function to test this, that will provide better granularity if there is ever a regression. As far as what to test, checking that it is a float is an improvement, but ideally you could compare the actual value, i.e. based on:
```

In [1]: from bokeh.models import Label

In [2]: import pandas as pd

In [3]: label = Label(x=pd.to_datetime('2018-01-01'))

In [4]: label.x
Out[4]: 1514764800000.0
```

I think you could write a test similar to:
```
def test_Span_accepts_datetime_location():
    obj = Span(location = pd.to_datetime('2018-01-01'))
    assert obj.location = <ms since epoch for date time value>
```

and if you are feeling generous, a similar test for `Label` that sets `x` and `y` from datetimes
