### ISSUE TITLE
Figure reset tool NOT trigger data source selected event on Mac

### ISSUE THREAD

**Issue by shaunrong** [bokeh/bokeh#8143]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 0.13.0, installed through `conda install bokeh`

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:14:23)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

OS MacOS 10.13.6

Browser Chrome Version 67.0.3396.99 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior

When replicating a gallery demo [Stock](https://demo.bokehplots.com/apps/stocks) locally, the figure reset tool won't trigger the code line [`source.on_change('selected', selection_change)`](https://github.com/bokeh/bokeh/blob/master/examples/app/stocks/main.py#L133). 

Notice when at the demo [web page](https://demo.bokehplots.com/apps/stocks), everything works fine, if we hit reset on any one of the figures, the table stats will update. However, locally, if we hit reset on any figure, it will only remove selected data from the correlated figures but the table stats won't update.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

#### Screenshots or screencasts of the bug in action
![screen shot 2018-08-07 at 11 44 36 am](https://user-images.githubusercontent.com/2459831/43795820-56f68ab2-9a37-11e8-99b4-a9583113c3dd.png)
![screen shot 2018-08-07 at 11 44 41 am](https://user-images.githubusercontent.com/2459831/43795823-58ff8d5e-9a37-11e8-9c1a-8d1b78ab6c27.png)
![screen shot 2018-08-07 at 11 44 44 am](https://user-images.githubusercontent.com/2459831/43795835-5dedc18c-9a37-11e8-8501-f1e8ea681be3.png)

**Comment by bryevdv** [comment]
This is almost certainly the same underlying issue as #7944 and #8021

**Comment by shaunrong** [comment]
@bryevdv Is there any work around on this problem right now? Or we should wait till 0.13.x for it to be fixed.

**Comment by bryevdv** [comment]
Try using 
```
source.selected.on_change('indices', selection_change).
```
which is probably simply what will be the way of doing things we will be able to support going forward

**Comment by shaunrong** [comment]
Just tried it. This didn't work. @bryevdv

**Comment by shaunrong** [comment]
@bryevdv Thanks for the help and suggestions. Just tried it on 0.12.16. It didn't work either.

**Comment by bryevdv** [comment]
I don't have any other suggestions except to wait for a fix. This still seems like #7944 since the immediate plot does rest selection, and only the linked plots do not. It's possible some older versions might not have the issue, I don't know for certain. You might be able to craft an alternate approach  using `CustomJS` but this is a usage/support question and GH is not the appropriate place.

**Comment by shaunrong** [comment]
Yeah. I'm gonna wait for a fix. I find that it's more likely that when the reset tool resets selection, it doesn't trigger the 'selected' callback function. This can be verified simply as putting a print statement in the callback function. When resetting the figures, there are no print outputs.
