### ISSUE TITLE
PolyDraw and PolyEdit tools should have options to snap to existing vertices

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8148]
The PolyDrawTool and PolyEditTool allow drawing arbitrary polygons and multi-lines, which has worked well so far. However often when working with these tools you want to connect multiple lines and/or polygons, which is currently basically impossible because you will never hit the exact same point multiple times. Therefore it would be very useful for these tools to be able to snap to existing vertices.

Currently I envision this working by ensuring that both of these tools define a vertex renderer, which mirrors the data in the multi-line/patches data source. If enabled the tools can then check whether the draw or edit actions are close to an existing vertex and snap to it if that is the case.

**Comment by orena1** [comment]
Should this be closed as the ticket was merged?

**Comment by bryevdv** [comment]
@philippjfr can comment

**Comment by philippjfr** [comment]
Thanks @orena1. This should indeed be considered completed.
