### ISSUE TITLE
DateSlider missing dates

### ISSUE THREAD

**Issue by njrs92** [bokeh/bokeh#8151]
**Description of the problem:**
When using DateSlider two errors mutually exclusively occur;  March 1st is missed and the slider jumps from Feb 28 to Mar 2nd or Feb 28th is missed, and the slider jumps from Feb 27 to Mar 1st. 

**Working Code with error**
```

    from tornado.ioloop import IOLoop
    from bokeh.application.handlers import FunctionHandler
    from bokeh.application import Application
    from bokeh.layouts import column
    from bokeh.models import ColumnDataSource, Slider
    from bokeh.server.server import Server
    from bokeh.layouts import widgetbox
    from bokeh.models.widgets import DateSlider

    import datetime
    from datetime import date

    io_loop = IOLoop.current()

    def modify_doc(doc):

        slider = DateSlider(title="Date Range: ", start=date(2017, 1, 1), end=date(2017,12, 31), value=(date(2017, 9, 7)), step=1)
        doc.add_root(widgetbox(slider))

    bokeh_app = Application(FunctionHandler(modify_doc))
    server = Server({'/': bokeh_app}, io_loop=io_loop)
    server.start()

    if __name__ == '__main__':
        print('Opening Bokeh application on http://localhost:5006/')

        io_loop.add_callback(server.show, "/")
        io_loop.start()


```
**Platform**
Bokeh 0.13.0
python 3.6
Windows 7 - 64bit
Chrome 68.0.3440.106

**Comment by bryevdv** [comment]
Your start/end/step comprises 365 distinct points, but the default slider width is only 300 pixels. It is physically impossible for some dates not to be skipped in this configuration, as the slider can onkly move in whole pixel increments. You can 

* make the slider much wider with the `width` param, or
* use a different widget, e.g. a date picker
