### ISSUE TITLE
Feature Request: Hide some (but not all) tools from toolbar

### ISSUE THREAD

**Issue by TimEwing** [bokeh/bokeh#8153]
It would be useful to have the ability to select which tools are shown in the toolbar. 
Some types of tools (HoverTool, ZoomTool, TapTool) are useful at all times and could be hidden to reduce visual clutter, while others (ZoomInTool, ResetTool) are only useful if the toolbar is shown.

**Comment by p-himik** [comment]
FWIW, it's possible to hide `HoverTool` and `CrosshairTool` by specifying `toggleable=False`.

**Comment by zoeangell** [comment]
Hi, I am part of a software engineering team, and we are interested in contributing to this issue. Can I be assigned?

**Comment by bryevdv** [comment]
Hi @zoeangell Bokeh is a volunteer OSS projects. We don't generally make use of assignments, except occasionally a core team member may self-assign to indicate their own intentions. You've indicated your interest here, the next step would be to ask questions/start discussions regarding any up-front design or implementation issues you want to clarify, or simply to submit a Pull Request for consideration.

**Comment by zoeangell** [comment]
Hi @bryevdv thanks for the clarification!
