### ISSUE TITLE
Feature request: bold italic font specification

### ISSUE THREAD

**Issue by smsaladi** [bokeh/bokeh#8156]
It would be convenient to configure text as both bold and italic (at the same time). I think something like any of the following might be nice ways of specifying this:

```python
text_font_style = 'bolditalic'
text_font_style = 'bold+italic'
text_font_style = 'italicbold'
```

Associated SO question: https://stackoverflow.com/questions/51772232/simultaneous-bold-and-italic-text-in-bokeh/51772730#51772730

Perhaps issue #596 refers the ability to change `font_style` at all

**Comment by bryevdv** [comment]
@smsaladi Thanks for the issue, the current enum values are exactly  permissible values to set for HTML canvas, and we would want to continue making sure bokeh allowed values are consistent with the allowed values on the canvas. That means only separating with a single space, eg:
```
text_font_style = "bold italic"
```
