### ISSUE TITLE
pytest doesn't work any more in bokeh's repository

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#8159]
`pytest`, `pytest bokeh`, `pytest -m unit`, etc. all fail with:
```
argparse.ArgumentError: argument --driver: conflicting option string: --driver
```
I'm pretty sure I have all packages install in correct versions. The same behavior persists on both python 2 and 3.

**Comment by bryevdv** [comment]
I think this means you have old junk installed in site-packages, or are using a different version of bokeh to run the tests than that which is check out for testing

**Comment by mattpap** [comment]
Removing unused pytest-* packages resolved this issue.

**Comment by philippjfr** [comment]
I had a similar problem when I had ``pytest-remotedata`` installed in my environment. I imagine you also have some pytest extension installed which defines a ``driver`` argument.

**Comment by philippjfr** [comment]
Sorry, page hadn't updated with your latest replies when I posted that.
