### ISSUE TITLE
bokeh_css and bokeh_js resources are reversed in FILE.html template

### ISSUE THREAD

**Issue by bitcom77** [bokeh/bokeh#8160]
in bokeh/bokeh/core/_templates/file.html as well as the documentation
the jinja2 tags for the resources are probably accidentally reversed:

      {% block resources %}
        {% block js_resources %}
          {{ bokeh_css | indent(8) if bokeh_css }}
        {% endblock %}
        {% block css_resources %}
          {{ bokeh_js | indent(8) if bokeh_js }}
        {% endblock %}
      {% endblock %}

should probably be:
      {% block resources %}
        {% block js_resources %}
          {{ bokeh_js | indent(8) if bokeh_js }}
        {% endblock %}
        {% block css_resources %}
          {{ bokeh_css | indent(8) if bokeh_css }}
        {% endblock %}
      {% endblock %}

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by mattpap** [comment]
I wonder how that happened. It doesn't look like a copy & paste error.
