### ISSUE TITLE
TileRenderer cache is not invalidated when URL changes

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8164]
When updating a TileSource URL the TileRenderer does not invalidate the existing cache which means as you zoom you will now get a mixture of old and new tiles. It seems the TileRenderer has an internal caching scheme that considers only the zoom level and location of the tile (i.e. in most cases the X/Y/Z 
 parameters of the tile source), the cache keys should probably also include the tile source URL to ensure that old tiles are not fetched from the cache when the URL has changed.

**Comment by jlstevens** [comment]
Caching  per URL makes a lot of sense to me and I find it hard to imagine a scenario where you *wouldn't* want that behavior.

**Comment by jsignell** [comment]
It seems to me that it isn't just the URL that would change. I think it should be that if the TileSource gets updated, that should trigger a rerender and dump the cache.

**Comment by philippjfr** [comment]
Got annoyed with this again and decided to fix it in #8594.
