### ISSUE TITLE
numpy.dtype size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#8165]
This:
```
RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
```
is printed all over examples' tests output. It would be nice get rid of this.

**Comment by bryevdv** [comment]
I've pinged the AD team about it

**Comment by bryevdv** [comment]
Response just now:

> That warning is a result of packages (SciPy, pandas, etc) which are compiled with an older version of NumPy which are run with a newer NumPy.  It is safe to ignore.  The numpy developers are planning on filtering out that message in future releases.

**Comment by bryevdv** [comment]
ref: https://github.com/numpy/numpy/issues/11628
