### ISSUE TITLE
Add to KaTeX users

### ISSUE THREAD

**Issue by ylemkimon** [bokeh/bokeh#8167]
Hey there, KaTeX maintainer here. Not really an issue. I'd like to ask if Bokeh would mind adding your logo to KaTeX user list? (https://github.com/Khan/KaTeX/pull/1569, preview availabe at https://deploy-preview-1569--katex.netlify.com/en/users.html) This is a really cool project! 😄

**Comment by bryevdv** [comment]
@ylemkimon Just FYI Bokeh does not use KaTex directly, at least not yet. We have published one example that shows how users can create a custom extension themselves, that integrates KaTeX output into a Bokeh plot. We'd like to make KaTeX output a fully supported buit-in feature, but I'm not sure when that might be able to happen. If you still think that adding it appropriate, I am happy to.

**Comment by bryevdv** [comment]
Also, looking at the linked issue, I think you are only asking for permission, and not any specific action on our part, so I will close this now, but please reply if I have misunderstood.

**Comment by ylemkimon** [comment]
@bryevdv Thank you ❤️
