### ISSUE TITLE
Strange behavior with BoxSelectTool when click+dragging on toolbar

### ISSUE THREAD

**Issue by TimEwing** [bokeh/bokeh#8168]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Windows 7, Chrome 68.0.3440.106 64-bit
#### Description of expected behavior and the observed behavior
Observed behavior: When clicking and dragging on the toolbar with an active  BoxSelectTool or BoxZoomTool, out-of-bounds boxes can be produced by dragging to the right. 

Expected behaviour: Not this.

#### Complete, minimal, self-contained example code that reproduces the issue
In https://bokeh.pydata.org/en/latest/docs/user_guide/graph.html#interaction-policies, click and drag to the right on the toolbar.

#### Screenshots or screencasts of the bug in action
![bokeh_bug](https://user-images.githubusercontent.com/8890627/44108491-cfe6d05a-9fb7-11e8-8d13-e074f425ccbe.png)

**Comment by bryevdv** [comment]
I'm unable to drag right off the canvas on OSX/Chrome, but I can initiate selections outside the plot frame. Ignoring mouse events outside the plot frame seems sensible.

**Comment by mattpap** [comment]
This was fixed at some point. A regression test is needed.

**Comment by philippjfr** [comment]
Great to hear this was fixed I was going to file a bug indicating that using the box-select context menu would initiate a new selection which was quite problematic.
