### ISSUE TITLE
Update license id to use the proper SPDX short license id

### ISSUE THREAD

**Issue by sabgit** [bokeh/bokeh#8174]
The current value `New BSD` does not match any of the valid SPDX licenses:
https://github.com/bokeh/bokeh/blob/d30171fcb0217a9eaa2729110f17444c70494efd/setup.py#L128

Can you please update it to `BSD-3-Clause` ?
https://spdx.org/licenses/BSD-3-Clause.html

$ pip show bokeh
Name: bokeh
Version: 0.13.0
License: New BSD

**Comment by bryevdv** [comment]
@sabgit do you intend to submit the PR?

**Comment by bryevdv** [comment]
@sabgit Just a head's up: I have no interest in this one way or another. If it is not important enough to you to submit a trivial PR, then I will just close this issue at the end of the week.

**Comment by bryevdv** [comment]
Closing with no response. Happy to accept a PR for this anytime.
