### ISSUE TITLE
plotting now working in jupyter notebook on bokeh v0.13.0

### ISSUE THREAD

**Issue by wujun** [bokeh/bokeh#8177]
my Jupyter notebook environment is below:

The version of the notebook server is: 5.5.0
The server is running on this version of Python:
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Current Kernel Information:
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

and
OS: MacOS 10.13.5
Install bokeh by pip3 
run any scripts in jupyter notebook cell, not any picture is showed

**Comment by wujun** [comment]
sorry, I almost supply further clue about the above issue: if I downgrade to bokeh v0.12.4 everything looks fine

**Comment by bryevdv** [comment]
I just ran a half day workshop for 25 students with bokeh 0.13 and notebook 5.x a few days ago and no one had any issues. So for now I must assume this is some configuration or environment issue on your end. Please continue this discussion on the mailing list until/unless we can isolate a real issue that requires attention on our end. 

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
