### ISSUE TITLE
Color as third dimension for an unknown number of items in a list's column

### ISSUE THREAD

**Issue by tolandwehr** [bokeh/bokeh#8182]
I've got a long list of rivers whose items can be plotted formidably in a scatter plot by numeric values of two rows.

The problem can be basically reproduced with any excel-list with more than thousand rows.

I wanna use the names of the rivers, noted in another column of the list, to color the dots differently. There are far are too many names, that I could create a "color-list" manually. 

I could be awkwardly looping, but there must be a nice and neat way that somebody has already carried out - and I'm not that much into programming, that I know how to transfer my problem on [this ](http://bokeh.pydata.org/en/latest/docs/gallery/color_scatter.html) color list produced by equidistant randomization. However, I presume it must be sth close.

Furthermore, I would love to take the names of the rivers as options in a dropdown chart - which is basically the reason why want to switch from Seaborn to Bokeh, as the internet told me clearly that Seaborn is not for interactivity. However take a look at the attached image produced with Seaborn to see what I finally would love to produce - moreover, the mess should make clear of why I wanna have the dropdown feature.

![2](https://user-images.githubusercontent.com/41265731/44514214-cd696180-a6bf-11e8-9321-071c18de489b.PNG)

**Comment by AzraelDD** [comment]
Github issues should be for actual "issues", i.e. bugs or changes you would like to propose.
If I understand correctly, you should try to seek "advice" in the Bokeh Discussion:
https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
Please include a minimal working example to show what you already tried and what is not working as desired.
Also, admittedly, I don't understand your desired result... How is the color derived from the name? What is the dropdown supposed to do?

What I will say is this: In the table (ColumnDataSource object ``my_source``) you can have one column named e.g. 'my_color' which contains a color (hex value) for each row in the table. You can then refer to that color while contructing the figures elements:

``p.circle(x='year', y='something', source=my_source, color='my_color')``
You will still somehow have to create that list of colors, though. To help with that, you would need some kind of rule for how the colors should look like.

**Comment by tolandwehr** [comment]
Thanks for the answer. I'll check your link asap. I was a little undecided, in how far it's an issue, but as it's about efficiency and I couldn't find a way after two hours of searching, I hoped it was.

Thing is, when you have a column of a list that's too long for counting all of its respective items with different names, is their a neat way to do this? E.g., if the respective column consist of 'animal names' (elephant-elephant-horse-cat-elephant-giraffe-elephant-and so on for ages) and you want any animal to have its own color in the scatter plot (and by this its own dropdown category) can you do this nifty? In seaborn, you just gotta enter the respective column in the category called 'hue' and it does thos automatically. I'm on my Smartphone right now (so I can't show you the code), but I post you the respective code asap as I'm back on my PC *promise*. But how do you do this in Bokeh in efficient manner (that's not looping through the whole list)?

**Comment by bryevdv** [comment]
@tolandwehr As @AzraelDD the GH issue tracker it not the appropriate place to seek help with usage or general support questions. Please use the mailing list, or StackOverflow.
