### ISSUE TITLE
Example app "dashboard" unsuccessful on wide screen

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8188]
All wide plots get too tall and everything gets cut off

![screenshot from 2018-08-25 17-46-36](https://user-images.githubusercontent.com/1796208/44623236-f55aef80-a88e-11e8-905f-fc3c7295d914.png)

Simplest first step would be to set a max-width on the dashboard css.

**Comment by birdsarah** [comment]
Little bit of CSS to look like this

![screenshot from 2018-08-25 17-52-42](https://user-images.githubusercontent.com/1796208/44623275-b8dbc380-a88f-11e8-9737-b96f4e1bc72b.png)

**Comment by birdsarah** [comment]
There are still a number of issues with it at various break points though. Just needs a little love.

**Comment by bryevdv** [comment]
So AFAICT this is due to setting the mode to be `scale_width` everwhere, which, it's doing exactly what is asked. I think the stretch modes make much more sense, and things almost work with those set:

<img width="1863" alt="screen shot 2019-02-18 at 20 20 49" src="https://user-images.githubusercontent.com/1078448/52989979-d14e1600-33ba-11e9-9d1a-e193a377b03a.png">

(This is with current master after layout PR)

cc @mattpap

**Comment by bryevdv** [comment]
I think the template is mostly to blame. With this diff:
```
❯ git diff
diff --git a/examples/app/dash/main.py b/examples/app/dash/main.py
index 469d480f8..6621cdf36 100644
--- a/examples/app/dash/main.py
+++ b/examples/app/dash/main.py
@@ -19,17 +19,17 @@ from bokeh.sampledata.stocks import AAPL
 dates = np.array(AAPL['date'], dtype=np.datetime64)
 source = ColumnDataSource(data=dict(date=dates, close=AAPL['adj_close']))

-p = figure(plot_height=110, tools="", toolbar_location=None, #name="line",
-           x_axis_type="datetime", x_range=(dates[1500], dates[2500]), sizing_mode="scale_width")
+p = figure(plot_height=250, tools="", toolbar_location=None, #name="line",
+           x_axis_type="datetime", x_range=(dates[1500], dates[2500]), sizing_mode="stretch_width")

 p.line('date', 'close', source=source, line_width=2, alpha=0.7)
 p.yaxis.axis_label = 'Traffic'
 p.background_fill_color="#f5f5f5"
 p.grid.grid_line_color="white"

-select = figure(plot_height=50, plot_width=800, y_range=p.y_range,
+select = figure(plot_height=80, plot_width=800, y_range=p.y_range,
                 x_axis_type="datetime", y_axis_type=None,
-                tools="", toolbar_location=None, sizing_mode="scale_width")
+                tools="", toolbar_location=None, sizing_mode="stretch_width")

 range_rool = RangeTool(x_range=p.x_range)
 range_rool.overlay.fill_color = "navy"
@@ -43,7 +43,7 @@ select.background_fill_color="#f5f5f5"
 select.grid.grid_line_color="white"
 select.x_range.range_padding = 0.01

-layout = column(p, select, sizing_mode="scale_width", name="line")
+layout = column(p, select, sizing_mode="stretch_both", name="line")

 curdoc().add_root(layout)

diff --git a/examples/app/dash/templates/index.html b/examples/app/dash/templates/index.html
index 906d2cf62..851046b29 100644
--- a/examples/app/dash/templates/index.html
+++ b/examples/app/dash/templates/index.html
@@ -36,7 +36,7 @@
       <div class="row">
```
Things look good maximized on a super wide screen:

![Screen Shot 2019-04-04 at 10 28 18 PM](https://user-images.githubusercontent.com/1078448/55605383-1f2f9b00-5729-11e9-9e95-81e4b343e787.png)

Tho it's still possible to cut things off if you really make the aspect small:

![Screen Shot 2019-04-04 at 10 28 33 PM](https://user-images.githubusercontent.com/1078448/55605399-31a9d480-5729-11e9-91bd-7d2eb768d914.png)

Looks good with larger aspect too:

<img width="870" alt="Screen Shot 2019-04-04 at 10 30 49 PM" src="https://user-images.githubusercontent.com/1078448/55605424-5bfb9200-5729-11e9-88cc-55c8768e7f8c.png">

@birdsarah would this be enough to close this issue?

**Comment by birdsarah** [comment]
This is a big improvement. My only concern is the table cut off on the very last screenshot, where it doesn't look like there's a horizontal scroll available to see it. Still, happy enough.
