### ISSUE TITLE
Bokeh release process discussion

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#819]
This is a meta issue to discuss about how we build our release process to be really effective. First, I think we need to collect all the task we have to do before the release... and then, we have to clearly assign a task to each one. In this way, we avoid task duplication, we cover all the testing we need to cover and the release work is effectively done.
 
I will start to add things we need to cover, but I encourage you to do the same, because we need to have a clear picture of all the task involved before doing anything else...

Thanks.

**Comment by bryevdv** [comment]
@damianavila @lexicalunit is there anything else to discuss here?

**Comment by lexicalunit** [comment]
I'm still happy to hack away on the script whenever. But since I don't actually use the script myself, I'm not sure what requirements/desires there are for the script.

**Comment by damianavila** [comment]
@lexicalunit, some things from the top of my head:

* py3 compatibility
* the filtering works well, but after tagging all the issues correctly, the script outputs the PRs when you use the `-c` option. It would be nice to filter by PR, I mean, check if the "issue" is actually a PR and remove it from the validation output...
* last time I run the script, it failed because it does not acept `...` in the title of the issues (is interpreted in some weird way, check this thread for more info: https://www.flowdock.com/app/continuum/bokeh/threads/Ko9DhXiEtMmaJS_EUvXIFQ1yoG1

**Comment by damianavila** [comment]
And @bryevdv, since this is a meta issue for release things, I would like to keep it open until we finish the complete automation of the release process (which I would like to develop in the next weeks as soon as time permits).

**Comment by bryevdv** [comment]
@damianavila can this be closed now?

**Comment by damianavila** [comment]
Let's close this one and open specific issues to deal with enhancements...
