### ISSUE TITLE
export_svgs() is much slower with multi_line

### ISSUE THREAD

**Issue by Restmon** [bokeh/bokeh#8192]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh                     0.13.0                   py36_0
#### Description of expected behavior and the observed behavior
Expected behavior is that export_svgs(multi_line()) takes somewhere between 1 to x times more time compared to export_svgs(line()) when multi_line() contains x lines. The observed behavior is that:
<table>
 <tr>
  <th>nr_lines_for_multiline</th>
  <td>4</td>
  <td>2</td>
  <td>1</td>
 </tr>
 <tr>
  <th>multi_line() with export_svgs()</th>
  <td>7.68s</td>
  <td>7.2s </td>
  <td>6.89s </td>
 </tr>
 <tr>
  <th>line() with export_svgs()</th>
  <td>0.09s</td>
  <td>0.08s</td>
  <td>0.12s</td>
 </tr>
 <tr>
  <th>multi_line() without export_svgs()</th>
  <td>0.02s</td>
  <td>0.02s</td>
  <td>0.02s</td>
 </tr>
 <tr>
  <th>multi_line()/line() </th>
  <td>70</td>
  <td>70</td>
  <td>70</td>
 </tr>
 <tr>
  <th>multi_line()/line()/nr_lines_for_multiline </th>
  <td>17.5</td>
  <td>35</td>
  <td>70</td>
 </tr>
</table>
The time it takes for multi_line() is 70 times line(), regardless of how many lines is in multi_line(). It seems that calling export_svgs(), when used with multi_line(), has some constant overhead that takes 6.5 seconds.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import output_file, show
from bokeh.layouts import gridplot
from bokeh.palettes import Viridis3
from bokeh.plotting import figure, show, ColumnDataSource, save, output_notebook, output_file, reset_output
from bokeh.palettes import plasma
from bokeh.models import HoverTool
import time
from bokeh.io import export_svgs

nr_lines_for_multiline = 4;#1 to 4
#%%px
# set up directory
scriptName = 'Untitled'
script_outdir = ('./' + scriptName)

colors = plasma(nr_lines_for_multiline)
hover = HoverTool(tooltips=[("data (x,y)", "($x, $y)")])
hover = HoverTool(tooltips=[("data (x,y)", "(@x, @y)")])
TOOLS=[hover]

### hover tool with line
p0=figure(width=400, height=200, tools=TOOLS)
p0.line([x for x in range(1,256)],[x+2 for x in range(1,256)])
start_time = time.time()
reset_output()
output_notebook()
show(p0)
print("line(): time including export_svgs()")
print("--- %s seconds ---" % (time.time() - start_time))                                  
                                   
xx = [x+1 for x in range(0,256)]
y0 = xx
y1 = [10 - i for i in xx]
y2 = [abs(i - 5) for i in xx]
y3 = [abs(i - 3) for i in xx]
y=[y0,y1,y2,y3][0:nr_lines_for_multiline]        

### hover tool with multi_line
x_list, y_list, legs = [], [], []
hover = HoverTool(tooltips=[("data (x,y)", "($x, $y)")])
hover = HoverTool(tooltips=[("data (x,y)", "(@x, @y)")])
TOOLS=[hover]

start_time = time.time()
p1 = figure(width=400, height=200, tools=TOOLS)
for i in range(0,nr_lines_for_multiline):
    x_list.append( xx )
    y_list.append( y[i] )
    legs.append( str( xx[i] ) )

source = ColumnDataSource( dict(x=x_list,y=y_list,legs=legs,colors=colors) )    
l = p1.multi_line( xs='x', ys='y', legend='legs', color='colors', source=source )
p1.output_backend = "svg"
export_svgs(p1, filename="./Untitled")
print("multi_line(): time including export_svgs()")
print("--- %s seconds ---" % (time.time() - start_time))


hover = HoverTool(tooltips=[("data (x,y)", "($x, $y)")])
hover = HoverTool(tooltips=[("data (x,y)", "(@x, @y)")])
TOOLS=[hover]
start_time = time.time()
p2 = figure(width=400, height=200, tools=TOOLS)
source = ColumnDataSource( dict(x=x_list,y=y_list,legs=legs,colors=colors) )    
l = p2.multi_line( xs='x', ys='y', legend='legs', color='colors', source=source )
p2.output_backend = "svg"
print("multi_line(): time excluding export_svgs()")
print("--- %s seconds ---" % (time.time() - start_time))

hover = HoverTool(tooltips=[("data (x,y)", "($x, $y)")])
hover = HoverTool(tooltips=[("data (x,y)", "(@x, @y)")])
TOOLS=[hover]
start_time = time.time()
p3 = figure(width=400, height=200, tools=TOOLS)
source = ColumnDataSource( dict(x=x_list,y=y_list,legs=legs,colors=colors) ) 
l = p3.multi_line( xs='x', ys='y', legend='legs', color='colors', source=source )
p3.output_backend = "svg"
print("multi_line(): time excluding export_svgs()")
print("--- %s seconds ---" % (time.time() - start_time))

# make a grid
grid = gridplot([[p1, p2], [None, p3]])

start_time = time.time()
# show the results
reset_output()
output_notebook()
#show(p1)    
show(grid)
print("time show(grid) takes")
print("--- %s seconds ---" % (time.time() - start_time))


```

#### Screenshots or screencasts of the bug in action
nr_lines_for_multiline = 4;#1 to 4
![image](https://user-images.githubusercontent.com/38109823/44659139-7e933300-aa03-11e8-853c-535550201d61.png)

**Comment by bryevdv** [comment]
Thanks for the detailed report. Unfortunately there may not be anything we can do about this. Bokeh relies extensively on a third party library that converts HTML canvas calls to SVG  in order to implement `export_svgs`. However last I checked that project did not seem to be actively maintained, and I am not aware of an suitable replacement.

**Comment by Restmon** [comment]
So export_svgs() is implemented does not work well with multi_line() but works well with line().
Some difference between multi_line() and line() must have triggered this. I wonder whether you know what is the difference that triggered the difference.

**Comment by bryevdv** [comment]
@Restmon No, unfortunately it could be various places, all outside out control, and I don't offhand have any idea which:

* It could be an issue with the outside `canvas2svg` JS library that actually does the conversion
* It could be in an issue with the HTML canvas itself

In the latter case, it might even be that it's only a problem with specific browsers. You might find that it works perfectly quickly with some browsers but not others. Unfortunately, as I said we have no control over these things, so the best thing I can suggest is to use line instead of multi-line.

**Comment by bryevdv** [comment]
@Restmon actually looking at your code, you are not timing the same things really. You do not appear to be timing `line` with `export_svgs` at all, only `multi_line`. The "line(): time including export_svgs()" block never calls `export_pngs` so I don't really see how this is a valid comparison. `export _svgs` is an inherently slow operation, Bokeh has to fire up a selenium webdriver and browser instance,  send page data and let it render headless, then retrieve the results. There is no better way, giving browser security models that restrict local file operations.
