### ISSUE TITLE
Possible Improvement: Data Format for MultiLine

### ISSUE THREAD

**Issue by stelehm** [bokeh/bokeh#8195]
While trying to use Bokeh for the visualization of sensor data, I noticed that the multi_line glyph does expect data in a (for me at least) unusual format.
I have measurements of multiple sensors with timestamps. So my data looks like the following:
time     | sensor id | value
day1    |  1            |  0.5
day1    |  2            | 0.6
...etc

In the source code I found the comment: "The data for the ``MultiLine`` glyph is different in that the vector of values is not a vector of scalars. Rather, it is a "list of lists"." 
So to use MultiLine, I have to restructure the data. 
Instead of creating two list of lists, it would be convenient to be able to chose one attribute according to which the values are assigned to a specific line.  So something like: 
`p.multi_line(xs="date", ys="value", lines="sensor id" , source=src)
`

Making MultiLine work like this, would make the glyph (imho) more consistent with how data and attributes are used for other glyphs in Bokeh.
Is there a reason, why it is set up the way it is?

Kind regards

**Comment by bryevdv** [comment]
If you want something like this, you could consider CDSViews with multiple calls to `line` (each with a different subset view). We would definitely not consider changing the multi line (or patches) API behavior at this point.
