### ISSUE TITLE
[Feature request] Add .copy method to ColumnDataSource

### ISSUE THREAD

**Issue by guzwaatensen** [bokeh/bokeh#8196]
Hi,

I'm writing a webapp with bokeh where the user can select data from a list of ColumnDataSources. The selected DataSource is used to update another Datasource that is driving a plot. The user can then maipulate the data. He should also be able to revert changes. However, changing the data source accociated with the plot also changes the DataSource it was updated from, so the original state is lost. While there is a workaround using patch or stream to dissasemble, copy and then reassemble the source instead of updating, it would be much more convinient to be able to just copy the source.

(Note: both copy.copy and copy.deepcopy do not work)

Minimal example below:
```
from bokeh.models import ColumnDataSource
import pandas as pd

src1 = ColumnDataSource(pd.DataFrame({'a':[0,0,0],'b':[1,1,1]}))
src2 = ColumnDataSource()
src2.data.update(src1.data)
src2.patch({'a':[(slice(3),[1,1,1])]})
# src1.data:
# {'a': array([1, 1, 1], dtype=int64),
# 'b': array([1, 1, 1], dtype=int64),
#  'index': array([0, 1, 2], dtype=int64)}
# with a copy method 'a' should remain [0,0,0] in src1
```

**Comment by guzwaatensen** [comment]
**addendum:**
If you replace:
```
 scr2.data.update(src1.data)
```
with
```
 scr2.data.update(src1.data.copy())
```
it also doesn't work, which I assume isn't intended behaviour?

**Comment by guzwaatensen** [comment]
**Addendum 2:** (sorry about that)
Found a method to create a clean copy:
```
deepcopy(src1.data)
```
results in an error as mentioned in the OP, but:
```
deepcopy(src1.data.copy())
```
creates an independent copy.

**Comment by bryevdv** [comment]
@guzwaatensen I guess I would suggest the best way to do this is to implement the `__copy__` and `__deepcopy__` hooks described here:

https://docs.python.org/3/library/copy.html

This is a pure Python change (no BokehJS changes) that seems accessible to you, would you be interested in working up a PR with some help/discussion? I can state fairly certainly that it will happen much more quickly in that case. 

The basic thing to know is that the `.data` attribute is not a plain Python dict, it is a specially instrumented dict subclass that affords all the automatic syncing, etc that Bokeh can do. 
```
In [10]: from bokeh.sampledata.iris import flowers

In [11]: s = ColumnDataSource(flowers)

In [12]: type(s.data)
Out[12]: bokeh.core.property.containers.PropertyValueColumnData

In [13]: type(s.data)
Out[13]: bokeh.core.property.containers.PropertyValueColumnData
```
I believe to make a shallow copy, just calling the `dict` initializer would suffice:
```
In [14]: d = dict(s.data)

In [15]: type(d)
Out[15]: dict
```
This new plain dict could be used to initialize a new CDS. To make a deep copy, I believe you could now call `deepcopy` on the plain dict. Once you verify that you agree,  I'd propose you make `__copy__` and `__deepcopy__` methods that do these. 

We could also consider allowing the CDS initializer to accept another CDS as input, and make a copy to init itself.

**Comment by bryevdv** [comment]
This all does seem to be accurate:
```
In [26]: s3 = ColumnDataSource(data=d)

In [30]: s3.data['sepal_width'] is s.data['sepal_width']
Out[30]: True

In [32]: d2 = copy.deepcopy(d)

In [35]: s3 = ColumnDataSource(data=d2)

In [36]: s3.data['sepal_width'] is s.data['sepal_width']
Out[36]: False
```

**Comment by bryevdv** [comment]
@guzwaatensen Are you interested in working up a PR for this? If not, I think the proper methods are simple enough, and documented in this issue, that we we would just close this issue. I'll close it at the end of the week unless you indicate otherwise. Of course we can always re-open in the future if this is important enough for anyone to do.

**Comment by guzwaatensen** [comment]
@bryevdv Sorry for the radio silence, I will work up a pull request, was just busy with other things.
Basically I will implement the `__copy__` and `__deepcopy__` hooks as you suggested. I will also change the constructor of  `ColumnDataSource` so that if it is initialized with a `PropertyValueColumnData` container the default behaviour is to create a deep copy of said source. I will add an example of this to the docstring, so that the behaviour is clear. However, I'm assuming this will require some discussion still. 
I can't think of any reason why you would initialize a `ColumnDataSource` with the `PropertyValueColumnData` property of another `ColumnDataSource` without the intend to make a copy but who knows. The right thing to do is probably to add a `copy` keyword argument to the constructor that is `True` by default.

If one amends my intial test case: 

```
from bokeh.models import ColumnDataSource
import pandas as pd

df = pd.DataFrame({'a':pd.np.array([0,0,0]),'b':pd.np.array([1,1,1])})
src1 = ColumnDataSource(df)
src2 = ColumnDataSource()
src2.data.update(src1.data)
src2.patch({'a':[(slice(3),[1,1,1])]})
```

It seems obvious that `df['a']` retains `[0,0,0]` so here copy already is the default behaviour. But if someone sets `copy` to `False` especially with large datasets they would certainly assume that memory is shared not only for initializing with `PropertyValueColumnData` but also for using `pandas.DataFrame`.
Which - without having looked at the source yet - I assume is a bit trickier then just implementing the hooks and adding a copy step to `ColumnDataSource.__init__`.

What is your opinion on the matter?

**Comment by bryevdv** [comment]
@guzwaatensen awesome, I look forward to it. No apology needed, just trying more lately to actively tend garden of the tracker :) 

> I can't think of any reason why you would initialize a ColumnDataSource with the PropertyValueColumnData property of another ColumnDataSource without the intend to make a copy but who knows. The right thing to do is probably to add a copy keyword argument to the constructor that is True by default.

Oh, sorry, I might have  not been as clear as I should have. I agree it should make a copy. I think the only question in my  mind is whether it should be shallow or deep by default.

**Comment by guzwaatensen** [comment]
@bryevdv Ah understood, In that case I will put deep as the default behaviour in my request (since that is what I need ;-)). That should be a simple 1 line change if the team disagrees with this default.

**Comment by bryevdv** [comment]
@guzwaatensen I made a late edit (bad habit) expressing a shallow copy preference. This is not an especially strong preference, but since we do have some difference of opinion it might to to seek other  inputs. @mattpap do you have an any preference? Should things like
```
ColumnDataSource(data=s1.data)
ColumnDataSource(s1)
```
create shallow or deep copies by default? My rationale for suggesting shallow copies is that it is more similar to what you get if you just passed a plain python dict around to multiple CDSes, and that doing the more expensive thing should be an explicit choice.

**Comment by guzwaatensen** [comment]
@bryevdv I've submitted a Pull Request with the necessary changes. `ColumnDataSource` is now set to make a shallow copy by default.
