### ISSUE TITLE
`bokeh.plotting.figure()` doesn't like single-quotes in the args.

### ISSUE THREAD

**Issue by rtruxal** [bokeh/bokeh#8203]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
```
λ python --version && ipython --version && jupyter notebook --version && bokeh --version
Python 3.6.6 :: Anaconda, Inc.
6.5.0
5.6.0
0.13.0
```
Then Windows 10 and firefox for the browser.    

#### Description of expected behavior and the observed behavior
already wrote all this: https://stackoverflow.com/a/52131638/6293857  

#### Complete, minimal, self-contained example code that reproduces the issue

```
# (In `jupyter notebook`)
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()

p = figure(plot_width=400, plot_height=400)
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5],
         size=15,
         line_color='navy',
         fill_color='organge',
         fill_alpha=0.5
        )
show(p)
```
This spits out:
```
ERROR:bokeh.core.validation.check:E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name: organge [renderer: GlyphRenderer(id='08fdc635-20f8-474d-b923-e36e40f68628', ...)]

```

#### Stack traceback and/or browser JavaScript console output
See above^^
#### Screenshots or screencasts of the bug in action
Everything is here: https://stackoverflow.com/a/52131638/6293857

**Comment by ivan-usov** [comment]
You have a typo in `fill_color='organge'`

**Comment by mattpap** [comment]
It would be nice to use `difflib` to help with such obvious spelling mistakes, similarly to what we do in `HasProps.__setattr__()`.
