### ISSUE TITLE
Adding/Updating Boilerplate Code

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#8207]
As part of the NumFocus small grant, we are funded to "Update all Bokeh source files with common boilerplate and header format (started but not yet finished)". The work should cover the following directories:

- [x] Top Level (#8220)
- [x] _testing
- [x] application (#8245)
- [x] client (#8276)
- [x] colors (#8293)
- [x] command (#8313)
- [x] core (#8341)
- [x] document
- [x] embed
- [x] io
- [x] models
- [x] plotting
- [x] protocol
- [x] sampledata
- [x] server
- [x] sphinxext
- [x] tests
- [x] themes
- [x] util

Non-directory:
- [x] Copyright
- [x] Update __all__ for transitive imports

Note that test module boilerplate varies from the standard.

**Comment by bryevdv** [comment]
BTW as long as we are doing this work we should also update the copyright statement. Since there has never been any CLA or copyright assignment agreement put in place it should now properly read:

> Copyright (c) 2012 - 2018, Anaconda, Inc., and Bokeh Contributors. All rights reserved.

I'd say let's make one PR at the end that just does this with some automated search/replace script in one swoop.

**Comment by HuntJSparra** [comment]
Do you want the "boxes" extended or the ``All rights reserved.`` moved down a line?

It currently looks a bit odd (in at least my opinion) as:
```
#-----------------------------------------------------------------------------
# Copyright (c) 2012 - 2018, Anaconda, Inc., and Bokeh Contributors. All rights reserved.
#
# Powered by the Bokeh Development Team.
#
# The full license is in the file LICENSE.txt, distributed with this software.
#-----------------------------------------------------------------------------
```

**Comment by bryevdv** [comment]
If we are going to add a line, let's subtract others:

```
#-----------------------------------------------------------------------------
# Copyright (c) 2012 - 2018, Anaconda, Inc., and Bokeh Contributors. 
# All rights reserved.
#
# The full license is in the file LICENSE.txt, distributed with this software.
#-----------------------------------------------------------------------------
```
Definitely wait to do this until the end, though, so this can be automated

**Comment by jbednar** [comment]
"Powered by the Bokeh Development Team"?

I'm not sure what this line adds...

**Comment by bryevdv** [comment]
@HuntJSparra I am pretty sure `_testing` is already done, but let me know when you think this is complete and can be closed.

**Comment by HuntJSparra** [comment]
It should be a small PR since only screenshot.py still needs boilerplate. After that, all that is needed is to check transitive imports in the directories I added boilerplate to early on and to replace the copyright.

**Comment by HuntJSparra** [comment]
@bryevdv is the following what was settled on for the new copyright?
```
#-----------------------------------------------------------------------------
# Copyright (c) 2012 - 2019, Anaconda, Inc., and Bokeh Contributors. 
# All rights reserved.
#
# The full license is in the file LICENSE.txt, distributed with this software.
#-----------------------------------------------------------------------------
```

**Comment by bryevdv** [comment]
Looks good to me
