### ISSUE TITLE
Add sizing_mode="stretch_width" and "stretch_height"

### ISSUE THREAD

**Issue by kernc** [bokeh/bokeh#8229]
Bokeh 0.13 and 1.0-dev. [`LayoutDOM.sizing_mode`](http://bokeh.pydata.org/en/latest/docs/reference/models/layouts.html#bokeh.models.layouts.LayoutDOM.sizing_mode) should accept values `"stretch_width"` and `"stretch_height"`. The values behave like `"scale_width"` and `"scale_height"`, but _without maintaining the aspect ratio_, i.e. keeping the other dimension fixed. These options, ["promised"](https://github.com/bokeh/bokeh/issues/4396#issuecomment-226805358) and [commonly](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/NzJvujZ3D74) [sought-for](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/wLFGYrb1xSM), would come in handy and empowering when building more complex layouts.

**Comment by mattpap** [comment]
In 1.0 (after PR #8085 is merged), it will be possible to control layout much more finely by setting sizing policy independently for both dimensions and setting aspect ratio independently as well on top of that.
