### ISSUE TITLE
Some typo in the Guide

### ISSUE THREAD

**Issue by ppplinday** [bokeh/bokeh#8235]
Hi:

I am newer in boker and I find some typo in the guide:
[https://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html](url)

In the Hex Tiles session's code, I think `output_file("hex_coords.py")` should be `output_file("hex_coords.html")`

Hope to fix this typo thx!

**Comment by bryevdv** [comment]
@ppplinday thanks for the report. This is the file to change:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/examples/plotting_hex_tile_basic.py#L7

Can you submit a Pull Request to fix it?

**Comment by bryevdv** [comment]
fized by #8236
