### ISSUE TITLE
Strict "image diff" selenium tests

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8260]
There is a class of tests we currently do not support: Sometimes when performing some interaction the inspectable result is a ultimately only what is drawn on canvas as a result. To validate these kinds of things we should be able to initiate the interaction (i.e. a selenium test), and then subsequently capture an image and compare the output to a reference. (This is the part we do not currently support)

* [x] legend an legend item updates (https://github.com/bokeh/bokeh/pull/8256)

**Comment by mattpap** [comment]
Visual integration tests should be added to bokehjs' `test:integration`. I added a test for PR #8256 in PR #10737.
