### ISSUE TITLE
Add note of  BOKEH_PHANTOMJS_PATH environment variable on missing phantomjs 

### ISSUE THREAD

**Issue by monkut** [bokeh/bokeh#8263]
I'm using bokeh 0.13.0 with python 3.6 to auto-generate charts in an AWS lambda environment to send to SLACK.

The AWS lambda environment is a bit restrictive and it's not *easy* to install packages or set the system PATH.  (or I couldn't find an easy way)

I looked for a way to set the phantomjs path, but didn't come across anything.  I just ran across this issue mentioning the existence of `BOKEH_PHANTOMJS_PATH`.

It would be helpful if this was available in the exception raised.

*dependencies.py detect_phantomjs*
```
...
    except OSError:
        raise RuntimeError('PhantomJS is not present in PATH or BOKEH_PHANTOMJS_PATH. Try "conda install phantomjs" or \
            "npm install -g phantomjs-prebuilt"')

    return phantomjs_path
```

**Comment by bryevdv** [comment]
@monkut please submit the small PR to add this and I will merge it
