### ISSUE TITLE
"Models must be owned by only a single document" error appears when splitting files

### ISSUE THREAD

**Issue by ltalirz** [bokeh/bokeh#8265]
When writing a bokeh app with multiple [Panels](https://bokeh.pydata.org/en/latest/docs/reference/models/widgets.panels.html#bokeh-models-widgets-panels), it seems to matter whether the same code is put into one python file or split across multiple files.
I'm not sure whether this is intended behavior, but at the very least it is very unexpected for a bokeh newcomer like me.

As a minimum working example, let's consider a simplification of the [tabs example](https://bokeh.pydata.org/en/latest/docs/reference/models/widgets.panels.html#bokeh.models.widgets.panels.Tabs) with only a single tab (you can also clone the code [on github](https://github.com/ltalirz/bokeh-panel-conundrum)).

```python
# panels.py
from bokeh.models.widgets import Panel, Tabs
from bokeh.io import output_file, show, curdoc
from bokeh.layouts import layout
from bokeh.plotting import figure

output_file("slider.html")

p1 = figure(plot_width=300, plot_height=300)
p1.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
tab1 = Panel(child=p1, title="line")

tabs = Tabs(tabs=[ tab1 ])

l = layout(tabs)
curdoc().add_root(l)
```
`bokeh serve panels.py --show` works fine; reloading the page also works fine.

Now, let's use essentially the same code, but split it into two separate files:
```python
# panels.py
from bokeh.models.widgets import Tabs
from bokeh.io import output_file, show, curdoc
from bokeh.layouts import layout
from bokeh.plotting import figure

output_file("slider.html")

from panel1 import tab1

tabs = Tabs(tabs=[ tab1 ])

l = layout(tabs)
curdoc().add_root(l)
```
and
```python
# panel1.py
from bokeh.plotting import figure
from bokeh.models.widgets import Panel

p1 = figure(plot_width=300, plot_height=300)
p1.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

tab1 = Panel(child=p1, title="line")
```
`bokeh serve panels.py --show` still works fine, but reloading the page gives the following error:
`Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x10eac2c50>: Models must be owned by only a single document, Grid(id='db7c1991-fde0-4287-abf3-8488b03517a6', ...) is already in a doc`

It seems, now that `tab1` lives in `panel1.py`, some "bokeh magic" stopped working.

Edit: panel1.py updated (was missing tab1 line)

P.S. Running bokeh 0.13.0 on MacOSX 10.13.6, and using Chrome 68.0

**Comment by bryevdv** [comment]
App code is executed new to generate a document for *every session that connects*. Every session must get its own unique set of Boken objects, so the app code always must generate *new instances*, so that different users are isolated. However, Python caches imports, and we cannot do anything about that. The implication is that Bokeh objects cannot be module global variables. 

If you want to split up the app code into multiple modules, that's fine, but you will need to encapsulate all Bokeh object creation inside functions that always return  new instance.

---

As an aside, in the future, please refer usage/support questions such as this to the mailing list first.

**Comment by hklarner** [comment]
I am using the same setup as @ltalirz for plotting geo data. This necessity of creating new instances of bokeh models also affects the import of tiles. That is, put the tile provider also inside the function that creates the tabs:
```
def create_tabs():
    from bokeh.tile_providers import CARTODBPOSITRON
    ...
```
Otherwise you get a runtime error:
> RuntimeError: Models must be owned by only a single document, WMTSTileSource(id='1003', ...) is already in a doc

**Comment by bryevdv** [comment]
@hklarner there is a new function for creating standard tile providers in the next release (and using the module attributes week be deprecated)

**Comment by icfly2** [comment]
I'm glad this was here and not on the mailing list, saved me a few hours digging.

**Comment by bryevdv** [comment]
@icfly2 the mailing list was retired, and replaced with a highly searchable Discourse (with all the old mailing list imported) https://discourse.bokeh.org

**Comment by misterjoa** [comment]
Hello, same problem here when refreshing a page. Self-contained example included.

```
pip freeze

astroid==2.3.2
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
bokeh==1.3.4
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
future==0.18.1
importlib-metadata==0.23
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
iso8601==0.1.12
isort==4.3.21
jedi==0.15.1
Jinja2==2.10.3
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.0
lazy-object-proxy==1.4.2
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==7.2.0
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.1
numpy==1.17.3
packaging==19.2
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.0
prometheus-client==0.7.1
prompt-toolkit==2.0.10
ptyprocess==0.6.0
Pygments==2.4.2
pylint==2.4.3
pyparsing==2.4.2
PyQt5==5.13.1
PyQt5-sip==12.7.0
pyqtgraph==0.10.0
pyreadline==2.1
pyrsistent==0.15.4
pyserial==3.4
python-dateutil==2.8.0
PyYAML==5.1.2
pyzmq==18.1.0
qtconsole==4.5.5
Send2Trash==1.5.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.3
typed-ast==1.4.0
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==0.6.0
```

```
#!/usr/bin/env python

import random

from bokeh.driving import count
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure

from functools import partial

from bokeh.application.handlers import FunctionHandler
from bokeh.application import Application
from bokeh.server.server import Server

from tornado.ioloop import IOLoop

UPDATE_INTERVAL = 10
ROLLOVER = 100

def main():

    source = ColumnDataSource({"x": [], "y": []})

    @count()
    def update(x):
        y = random.random()
        source.stream({"x": [x], "y": [y]}, rollover=ROLLOVER)

    def create_doc(source, doc):

        #doc = curdoc() NO ! Otherwise page is blank

        p = figure()
        p.line("x", "y", source=source)

        doc.add_root(p)
        doc.add_periodic_callback(update, UPDATE_INTERVAL)

        return doc

    io_loop = IOLoop.current()

    bokeh_app = Application(
        FunctionHandler(
            partial(create_doc, source)
            ))

    server = Server(
        {'/': bokeh_app},
        io_loop=io_loop
        )

    server.start()
    io_loop.start()

if __name__ == '__main__':
    main()
```

**Comment by bryevdv** [comment]
@misterjoa you have a global `source = ColumnDataSource({"x": [], "y": []})` That is the problem. This is not a bug. You cannot re-use Bokeh models between sessions, period.
