### ISSUE TITLE
Cannot "filter" Factor Range

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8270]
I know this was a feature because I added it myself and recall thinking hard with @bryevdv about the mechanics and semantics. Edit: While initial filtering by bounds was possible, and still is by just setting a subset as factors, as explained by @bryevdv in his comment, I'm not sure that it ever worked with server / updating.

The functionality appears to have been deleted in this commit: https://github.com/bokeh/bokeh/commit/fb17bfe473dde87b32f455b6d4081e2b2032b83d#diff-f3b8e12ce32809fa2f1838c966433ade

And in the 0.12.7 release notes it says "bounds on FactorRange are now given in synthetic coordinate units" but nothing more, and nothing pertaining to the previous role of bounds to limit the view on a FactorRange.

I have a plot, there are ~500 possible categorical values, that form my y_range. At any given point, based on the filters I've selected, only a handful will be displayed.

What is the currently supported way to achieve what I'm trying to do?

**Comment by bryevdv** [comment]
You should just set `factors` to the ones you want to display on the axis, coordinates outside this set are just ignored:
```
from bokeh.plotting import figure, show

factors = ["a", "b", "c", "d", "e", "f", "g", "h"]
x =  [50, 40, 65, 10, 25, 37, 80, 60]

dot = figure(y_range=["a", "b", "c"], x_range=[0,100])

dot.segment(0, factors, x, factors, line_width=2, line_color="green", )
dot.circle(x, factors, size=15, fill_color="orange", line_color="green", line_width=3, )

show(dot)
```

<img width="533" alt="screen shot 2018-09-21 at 07 53 59" src="https://user-images.githubusercontent.com/1078448/45888692-87adc080-bd73-11e8-91d1-b6700e6270fa.png">

**Comment by bryevdv** [comment]
In case it was not clear, you can change/update `factors`at any point. I don't see why this needs to remain open

**Comment by birdsarah** [comment]
I got pulled away while writing this post, apologies for the delay between the reopen and posting.

I'm asking about something slightly different. However, I'm no longer sure this used to work.

See this code:

```
from bokeh.io import curdoc
from bokeh.layouts import row
from bokeh.models import ColumnDataSource, Select
from bokeh.plotting import figure

factors = ["a", "b", "c", "d", "e", "f", "g", "h"]

data_1 = {
    'x': [30, 40, 50],
    'y': ['a', 'b', 'c']
}
data_2 = {
    'x': [10, 20, 80],
    'y': ['f', 'g', 'h']
}
data_3 = {
    'x': [15, 25, 35],
    'y': ['d', 'a', 'b']
}

source = ColumnDataSource(data_1)
plot = figure(y_range=factors, x_range=[0, 100])
plot.hbar(right='x', y='y', height=0.8, source=source)

select = Select(title="picker", value="1", options=["1", "2", "3"])


def update_data(attr, old, new):
    if select.value == "1":
        data = data_1
    if select.value == "2":
        data = data_2
    if select.value == "3":
        data = data_3
    source.data = data


select.on_change('value', update_data)

curdoc().add_root(row(select, plot))
```

It produces plots like this, as the selector changes:

![screenshot from 2018-09-21 13-14-29](https://user-images.githubusercontent.com/1796208/45899296-0a4d7480-bda2-11e8-8668-bdb4477c8675.png)
![screenshot from 2018-09-21 13-12-15](https://user-images.githubusercontent.com/1796208/45899297-0a4d7480-bda2-11e8-9149-41150753956e.png)

What I am trying to have happen - which I was trying to do by updating bounds - is not have the empty rows displayed - which is what I meant by "filtering".

**Comment by bryevdv** [comment]
As I mentioned, you can update `factors` at any time:
```
def update_data(attr, old, new):
    if select.value == "1":
        data = data_1
        plot.y_range.factors = data_1['y']
    if select.value == "2":
        data = data_2
        plot.y_range.factors = data_2['y']
    if select.value == "3":
        data = data_3
        plot.y_range.factors = data_3['y']
    source.data = data
```

<img width="704" alt="screen shot 2018-09-22 at 01 16 49" src="https://user-images.githubusercontent.com/1078448/45913681-3d751f80-be05-11e8-8f0c-1816fa6d660c.png">

**Comment by birdsarah** [comment]
Dammit!!!! I did not figure that out. Thanks so much. :hugs:
