### ISSUE TITLE
Missing ";" in try_run.js

### ISSUE THREAD

**Issue by nicain** [bokeh/bokeh#8271]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Anaconda 4.5.11 python 2.7.14 Bokeh 0.13.0

#### Description of expected behavior and the observed behavior

When exporting a script/div using components in Bokeh, I need to programmatically zap newlines and place the generated <script> in my template.  However this exposed a missing ";" in the js template, that will crash the rendering on the client side.  

https://github.com/bokeh/bokeh/blob/13baccbb2835f7d5831c22b5cf68214e89c02618/bokeh/core/_templates/try_run.js#L17

**Comment by bryevdv** [comment]
@nicain please submit a PR and I will merge it

**Comment by nicain** [comment]
PR at https://github.com/bokeh/bokeh/pull/8272

**Comment by bryevdv** [comment]
Thanks @nicain
