### ISSUE TITLE
Unhelpful error when passing invalid argument to gridplot

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8273]
I often find myself assembling a list of plots and then writing:

    $ show(gridplot(plots, n_cols=4))

This will give the following error:

```python
TypeError                                 Traceback (most recent call last)
<ipython-input-25-656b46f60be9> in <module>()
----> 1 show(gridplot(plots, n_cols=4, toolbar_location=None))

~/Dev/bokeh/bokeh/bokeh/layouts.py in gridplot(*args, **kwargs)
    320         row_tools = []
    321         row_children = []
--> 322         for item in row:
    323             if merge_tools:
    324                 if item is not None:

TypeError: 'Figure' object is not iterable
```

The problem is that I wrote `n_cols` instead of `ncols`. At this point I've done this dozens and dozens of times. Every time I come back to bokeh after a gap, this always trips me up and I forget the ncols/n_cols thing and think there's some more fundamental mistake.

Can we validate the input to gridplot better?

One of my favorite features about bokeh is the helpful suggestions when you mess up a parameter. I know this is completely different, and nothing to do with the property machinery, but none-the-less a similar experience would be awesome.

**Comment by bryevdv** [comment]
I think the issue here specifically is that these functions accept a `kwargs`, but AFAICT don't need to. Maybe something was different previously but at the moment these functions pick values out of `kwargs` but don't pass the `kwargs` on to other functions or otherwise do anything with them. In that circumstance, there should just be regular python function parameters with default values, which would result in typical and familiar (and useful) error messages directly from Python.

**Comment by bryevdv** [comment]
In cases where we do need to have `kwargs` the patter should be that each level of function call should strip off any values specific to it, and the the last function in the chain should check that there are no "extras". This is already automatically the case for kwargs that ultimately get passed to initialized a Bokeh model (e.g. `column`)

**Comment by birdsarah** [comment]
Following up on your question for the closed PR. I don't think it's necessary to allow the syntax 
`gridplot(p1, p2, p3, p4)`.

I think one way of doing things is good. And children are consistently a list of plots throughout the layouts.

**Comment by bryevdv** [comment]
I tend to agree, but there are some examples that do use that syntax, and I am a little hesitant to break them

**Comment by birdsarah** [comment]
This is the last release to break APIs - live a little :D

**Comment by bryevdv** [comment]
ok ok

**Comment by 02akshay** [comment]
Try this gridplot([p1,p2],[])

**Comment by bryevdv** [comment]
@02akshay You will have elaborate, without context it's not obvious what point you are trying to make. Are you saying that snippet works? doesn't work? does something unexpected?
