### ISSUE TITLE
bokeh core fails JSON serialization with byte types included in CDS

### ISSUE THREAD

**Issue by tumlinson** [bokeh/bokeh#8275]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 0.13.0, Safari, MacOSX High Sierra 

#### Description of expected behavior and the observed behavior

I have encountered an error that only emerged when I ported code to python 3.6 and bokeh 0.13 
If a ColumnDataSource includes objects of type "byte", JSON serialization will fail (see traceback at the bottom of this issue). The error is actually thrown by the JSON serialization code (outside bokeh). 

The transform_python_types method on class BokehJSONEncoder exists to catch particular types that will trip up the JSON serializer (like pandas stuff). It *does not* catch byte types, it just passes them on. Rather than chase down all the places this happens in the original code, I tried adding 
a test to catch this in bokeh/core/json_encoder.py like so: 

try:
      return obj.decode()
except AttributeError:
       pass

This works to catch the byte types, but it might be better to do this elsewhere. 

See below for my slight edit to the sliders.py example, to which I added a few lines of code that create the error. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
''' Present an interactive function explorer with slider widgets.
Scrub the sliders to change the properties of the ``sin`` curve, or
type into the title text box to update the title of the plot.
Use the ``bokeh serve`` command to run the example by executing:
    bokeh serve sliders.py
at your command prompt. Then navigate to the URL
    http://localhost:5006/sliders
in your browser.
'''
import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import row, widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Slider, TextInput
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool, Circle


# Set up data
N = 200
x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)
source = ColumnDataSource(data=dict(x=x, y=y))


# Set up plot
plot = figure(plot_height=400, plot_width=400, title="my sine wave",
              tools="crosshair,pan,reset,save,wheel_zoom",
              x_range=[0, 4*np.pi], y_range=[-2.5, 2.5])

plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)


#------lines that generate JSON serialization error --------- 
c_array = np.array([b'#FB0006',b'#118CFF',b'#B7E0FF',b'#FB0006',b'#118CFF']) 
test_cds = ColumnDataSource(data=dict(x=[1., 2., 3., 4., 5.], y=[-2., -1., 0., 1., 2.], 
                                  color=c_array, labels=["1", "2", "3", "4", "5"])) 
test_circles = plot.circle('x','y', source=test_cds, fill_color='color') 
#----------------------------------------------------------- 


# Set up widgets
text = TextInput(title="title", value='my sine wave')
offset = Slider(title="offset", value=0.0, start=-5.0, end=5.0, step=0.1)
amplitude = Slider(title="amplitude", value=1.0, start=-5.0, end=5.0, step=0.1)
phase = Slider(title="phase", value=0.0, start=0.0, end=2*np.pi)
freq = Slider(title="frequency", value=1.0, start=0.1, end=5.1, step=0.1)


# Set up callbacks
def update_title(attrname, old, new):
    plot.title.text = text.value

text.on_change('value', update_title)

def update_data(attrname, old, new):

    # Get the current slider values
    a = amplitude.value
    b = offset.value
    w = phase.value
    k = freq.value

    # Generate the new curve
    x = np.linspace(0, 4*np.pi, N)
    y = a*np.sin(k*x + w) + b

    source.data = dict(x=x, y=y)

for w in [offset, amplitude, phase, freq]:
    w.on_change('value', update_data)


# Set up layouts and add to document
inputs = widgetbox(text, offset, amplitude, phase, freq)

curdoc().add_root(row(inputs, plot, width=800))
curdoc().title = "Sliders"
```

#### Stack traceback and/or browser JavaScript console output

townes:luvoir_simtools tumlinson$ bokeh serve --show sliders.py 
2018-09-24 11:29:54,063 Starting Bokeh server version 0.13.0 (running on Tornado 5.0.2)
2018-09-24 11:29:54,066 Bokeh app running at: http://localhost:5006/sliders
2018-09-24 11:29:54,066 Starting Bokeh server with process id: 83914
2018-09-24 11:29:54,299 200 GET /sliders (::1) 83.22ms
2018-09-24 11:29:54,358 101 GET /sliders/ws?bokeh-protocol-version=1.0&bokeh-session-id=QSDz95FJA2762AUWOjy5ukIOYktOqazC9isQzmbTl5Si (::1) 0.62ms
2018-09-24 11:29:54,358 WebSocket connection opened
2018-09-24 11:29:54,358 ServerConnection created
OBJ: b'#FB0006'
2018-09-24 11:29:54,364 error handling message Message 'PULL-DOC-REQ' (revision 1): TypeError("Object of type 'bytes' is not JSON serializable",)

**Comment by bryevdv** [comment]
I"m actually going to go ahead and close on that basis. Would consider re-opening if a more motivating example can be provided, along with a concrete proposal for how what Bokeh could do with bytes that would be appropriate *in general*.

**Comment by tumlinson** [comment]
So, using colors was a bad example. You're right they should be strings. However, the effect is the same even if the byte type array is not assigned to plot colors, and in fact even if the byte type array is not used in the plot - it merely has to be present in the CDS. 

In this code, "test_array" has byte type. Including it in the CDS yields the same JSON serialization error even though it is not used in construction of the Figure. 

So it seems worth looking into as any byte type element of CDS appears to throw the error. 

At the very least it seems sensible for bokeh to throw a warning, or document that CDS cannot contain byte since they will not serialize. Otherwise users will not know to avoid them. 

''' Present an interactive function explorer with slider widgets.
Scrub the sliders to change the properties of the ``sin`` curve, or
type into the title text box to update the title of the plot.
Use the ``bokeh serve`` command to run the example by executing:
    bokeh serve sliders.py
at your command prompt. Then navigate to the URL
    http://localhost:5006/sliders
in your browser.
'''
import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import row, widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Slider, TextInput
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool, Circle


# Set up data
N = 200
x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)
source = ColumnDataSource(data=dict(x=x, y=y))


# Set up plot
plot = figure(plot_height=400, plot_width=400, title="my sine wave",
              tools="crosshair,pan,reset,save,wheel_zoom",
              x_range=[0, 4*np.pi], y_range=[-2.5, 2.5])

plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)


#------lines that generate JSON serialization error --------- 
test_array = np.array([b'one',b'two',b'three',b'four',b'five']) 
test_cds = ColumnDataSource(data=dict(x=[1., 2., 3., 4., 5.], y=[-2., -1., 0., 1., 2.], 
                                 test=test_array, labels=["1", "2", "3", "4", "5"])) 
test_circles = plot.circle('x','y', source=test_cds) 
#----------------------------------------------------------- 


# Set up widgets
text = TextInput(title="title", value='my sine wave')
offset = Slider(title="offset", value=0.0, start=-5.0, end=5.0, step=0.1)
amplitude = Slider(title="amplitude", value=1.0, start=-5.0, end=5.0, step=0.1)
phase = Slider(title="phase", value=0.0, start=0.0, end=2*np.pi)
freq = Slider(title="frequency", value=1.0, start=0.1, end=5.1, step=0.1)


# Set up callbacks
def update_title(attrname, old, new):
    plot.title.text = text.value

text.on_change('value', update_title)

def update_data(attrname, old, new):

    # Get the current slider values
    a = amplitude.value
    b = offset.value
    w = phase.value
    k = freq.value

    # Generate the new curve
    x = np.linspace(0, 4*np.pi, N)
    y = a*np.sin(k*x + w) + b

    source.data = dict(x=x, y=y)

for w in [offset, amplitude, phase, freq]:
    w.on_change('value', update_data)


# Set up layouts and add to document
inputs = widgetbox(text, offset, amplitude, phase, freq)

curdoc().add_root(row(inputs, plot, width=800))
curdoc().title = "Sliders"
