### ISSUE TITLE
Linked plotting does not work when MultiLine is involved

### ISSUE THREAD

**Issue by albertogomcas** [bokeh/bokeh#8281]
bokeh 0.13.0
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
IPython 6.2.1

I wanted to create two linked figures where the link is not the usual point<->point but point<->line (actually I just care about the point->line direction).

Below is example code that plots the center of gravity of each line (glyph) on the left and the glyphs themselves on the right.

However, when selecting the points, the figure on the right stays unchanged.

```
import numpy as np

from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, DataRange1d
from bokeh.models.glyphs import MultiLine
from bokeh.io import show
from bokeh.layouts import row

TOOLS = "box_select,reset"

N = 9
x = np.linspace(-2, 2, N)
y = x**2

xpts = np.array([-.09, -.12, .0, .12,  .09])
ypts = np.array([-.1,   .02, .1, .02, -.1])

xs = [xpts*(1+i/10.0)+xx for i, xx in enumerate(x)]
ys = [ypts*(1+i/10.0)+yy for i, yy in enumerate(y)]

xdr = DataRange1d()
ydr = DataRange1d()

source = ColumnDataSource(dict(
        x=[np.mean(xsi) for xsi in xs],
        y=[np.mean(ysi) for ysi in ys],
        xs=xs,
        ys=ys,
    )
)

TOOLS = "box_select,reset"

plot1 = figure(title=None, x_range=xdr, y_range=ydr, plot_width=300, plot_height=300, tools=TOOLS)
plot1.circle(x='x', y='y', source=source)

plot2 = figure(title=None, x_range=xdr, y_range=ydr, plot_width=300, plot_height=300, tools=TOOLS)

glyph = MultiLine(xs="xs", ys="ys", line_color="#8073ac", line_width=2)
plot2.add_glyph(source, glyph)

show(row(plot1, plot2))

```
![image](https://user-images.githubusercontent.com/8244088/46141422-234b9f00-c254-11e8-9229-d3352918e8a1.png)

**Comment by bryevdv** [comment]
AFAIK multi-line does not yet support rect hit-testing, i.e. it does not support `BoxSelectTool`

**Comment by philippjfr** [comment]
Note that it does work if you replace:

```python
glyph = MultiLine(xs="xs", ys="ys", line_color="#8073ac", line_width=2)
plot2.add_glyph(source, glyph)
```

with:

```
plot2.multi_line(xs='xs', ys='ys', source=source, line_color="#8073ac", line_width=2)
```

Not sure why it would be different but that's a viable workaround for now.

**Comment by bryevdv** [comment]
That is well and truly bizarre. I'd recommend everyone typically do things that way anyway, unless there is a specific need or reason to use the very low level API. But we should figure out what the distinction is here, if perhaps only to document it.

**Comment by bryevdv** [comment]
Actually on further thought, this is exactly expected behavior. The `figure` methods are higher level and do things like automatically configure selection/non-selection glyphs behind the scenes, if none are supplied. But glyph objects like `MultiLine` are low level and do not do anything like that. You would need to manually set up everything, e.g. selection/non-selection glyphs.
