### ISSUE TITLE
Autohide toolbar

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#8284]
Right now, when a Bokeh plot has a toolbar, the toolbar is always visible.  This helps people see the tools that are available, but it is distracting when one is primarily reading through a long document, looking at several plots and not wishing to interact with any one of them.  

To support this usage, I'd prefer that the default behavior is that the tools are visible only when the mouse is actually inside the plot area, and otherwise they are silently hidden (which would then also apply on export, providing a cleaner exported figure). Presumably the tools could be set to be invisible (alpha=0) whenever the mouse is outside the plot area?  

An implementation of this would be to add an option `autohide` to `Toolbar`, and once supported we could debate whether it should be True or False by default.

**Comment by bryevdv** [comment]
Just an FYI noting that it is expected @jsignell to work on this after #8085 is merged

**Comment by mattpap** [comment]
This will require more work than just adding an option to a toolbar. Currently toolbar, as a part of a plot, can be only located in side panels, in which case any kind of hiding doesn't make sense. There is no way to add a toolbar to the center layout. In #8085 I stared implementing "anchor layout" to allow this, but this is far from being finished.

**Comment by bryevdv** [comment]
@mattpap the example upon which this is based, simply hides the toolbar without altering the layout. That is expressly all that is wanted. The toolbar does not need to be in the center layout, it just needs to allocate space as if it were going to draw, but then not actually draw (unless the cursor is inside w hit region)

**Comment by jbednar** [comment]
Not actually drawing it is fine, but it's also fine to draw it but using transparent pixels; whatever is easier.  Hopefully we wouldn't have to resort to a div on top of the toolbar, because that would interfere with a page where the background isn't a solid color.
