### ISSUE TITLE
Permanent labels on Networkx graph

### ISSUE THREAD

**Issue by codercahol** [bokeh/bokeh#8289]
Following up on https://stackoverflow.com/questions/49848966/how-to-add-permanent-name-labels-not-interactive-ones-on-nodes-for-a-networkx since the problem hasn't been addressed yet and I couldn't find an existing issue that covered it. 

It is really painful to add labels to networkx graphs currently, would be awesome if this could be improved.

**Comment by bryevdv** [comment]
@canavandl do you have any thoughts about this? I can imagine a few possible avenues for both syntax and implementation but I'd appreciate your thoughts.

**Comment by gmlevin** [comment]
One option would be to include the label as part of the glyph. Have a standard attribute that would label the node, or have a parameter to glyph that says where to pull the label text from (`@label` to pull the text from `node['label']`).

The association could then be used to define the label and the hover text (`label="@label", hover="@hover"`)

**Comment by fbidu** [comment]
Hello, did we have any updates on this? I just stumble into this while trying to accomplish the same task
