### ISSUE TITLE
Embedding Chart objects in a webpage

### ISSUE THREAD

**Issue by eco32i** [bokeh/bokeh#829]
Right now there is no obvious way to get a Chart object back in a form that can be embedded in a webpage (can't call `components` function on a Chart object and the underlying `plot` is not exposed).

I was able to work around it be passing the Chart `__init__` method a dict (called `response`) and then writing into it in `Chart.show()`. Is this a reasonable approach or are you planning on implementing this in a different way? While dict works for my use case (django) writing JSON might be a better idea in general.

**Comment by ZZZWWW** [comment]
Is there any way to do this under 0.9.0? I tried .chart.plot and it doesn't work (it works under 0.7.1). It says the time series has no attribute chart. I'm sure I've imported right

**Comment by bryevdv** [comment]
Charts *are* plots now. Try `show(mychart)` or `components(mychart)`
