### ISSUE TITLE
The "css_classes" attribute on DataTable object does not work

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#8290]
I have been trying to add a css class to the data table object but the class is never added. Is this an issue or it is on purpose?

    from bokeh.models import ColumnDataSource
    from bokeh.models.widgets.tables import DataTable, TableColumn
    from bokeh.io import curdoc

    source = ColumnDataSource(dict(
        x=[1, 2, 3, 4, 5, 6],
        y=[1, 2, 3, 4, 5, 6],
    ))

    columns = [
        TableColumn(field="x", title="X"),
        TableColumn(field="y", title="Y"),
    ]

    table = DataTable(
        source=source,
        columns=columns,
        css_classes=['data_table_class']
    )
            
    curdoc().add_root(table)

If I print `dir(table)` the `css_classes` attribute exists

**Comment by bryevdv** [comment]
This appears to be fixed in master (probably #8085):

<img width="627" alt="screen shot 2019-02-18 at 18 39 09" src="https://user-images.githubusercontent.com/1078448/52986450-83caac80-33ac-11e9-9d18-2f579d9d6c5e.png">

so closing,
