### ISSUE TITLE
A tiny typo in the document about GraphRenderer

### ISSUE THREAD

**Issue by komo-fr** [bokeh/bokeh#8299]
I found a tiny typo in the document about `GraphRenderer` while working on other PRs.

**attr y_range_name**
https://bokeh.pydata.org/en/latest/docs/reference/models/renderers.html#bokeh.models.renderers.GraphRenderer.y_range_name
> A particular (named) y-range to use for computing screen locations when rendering graphs on the plot. If unset, use the default -range.

It seems that it is '"y-range", not "-range”.

I think that this line is to be modified.
If there is not problem, I will send a PR.
https://github.com/bokeh/bokeh/blob/a01ae6ecb6726cb97ae1997e57d62f0cdf6adacc/bokeh/models/renderers.py#L205-L206

**Comment by bryevdv** [comment]
@komo-fr absolutely, also I would say for small changes like this it's also fine to just submit a PR directly. We have a preference for separate issue+PR in most cases, but we can also accommodate combined "issue PRs" and for very small things it should reduce the burden on contributors. 

Thanks for your attention and contributions!

**Comment by komo-fr** [comment]
@bryevdv
OK, I will do so from the next time.
Thank you for your kind advice!
