### ISSUE TITLE
Manual selected change event does not trigger js callbacks

### ISSUE THREAD

**Issue by ibestvina** [bokeh/bokeh#8305]
Consider the following example which has a plot, div and a button. Div should show the number of selected points, and the button should clear the selection. However, although the selection is cleared in the plot, div is not updated (i.e. `source.js_on_change` callback is not triggered).

```
from bokeh.plotting import figure, output_file, show
from bokeh.layouts import widgetbox, gridplot
from bokeh.models import ColumnDataSource
from bokeh.models import Div, Button
from bokeh import events
from bokeh.models.callbacks import CustomJS

from bokeh.sampledata.iris import flowers

output_file('clear_selection_button.html')

div = Div(text='Len: 0', width=200, height=20)
source = ColumnDataSource(flowers)
button = Button(label='Clear selection', button_type='success')

callback_select = CustomJS(args={'div':div, 'source':source}, code="""
div.text = 'Len: ' + source.selected.indices.length;
""")

callback_click = CustomJS(args={'source':source}, code="""
source.selected.indices = [];
source.change.emit();
""")

button.js_on_event(events.ButtonClick, callback_click)
source.js_on_change('selected', callback_select)

p1 = figure(plot_height=300, plot_width=300, tools=['box_select', 'reset'])
p1.circle(x='petal_length', y='petal_width', source=source, color='black')

show(gridplot([[p1], [widgetbox(div)], [button]]))
```

 Tried on Firefox (61), Chrome (69) and Edge (42). Windows 10 64bit. Bokeh 0.13.

As a side question: it would seem to me that, idiomatically, the correct thing to use here would be `source.selected.change.emit()`, which seems to exist (at least JS doesn't complain), but it produces neither of the two expected effects: updating the plot and updating the div. Is it even supposed to work?

**Comment by npeirson** [comment]
Agreed, here's my attempt, didn't do anything. The [DataSource abstract](https://bokeh.pydata.org/en/latest/_modules/bokeh/models/sources.html#DataSource) has a callback instance, and neither python nor js produces any error, so idk.

```
from bokeh.io import output_file,show
from bokeh.models import ColumnDataSource
from bokeh.models.callbacks import CustomJS
from bokeh.models.widgets import Button
from bokeh.layouts import layout

output_file('sadface.html')
button = Button(label='click me pls')
cds = ColumnDataSource(dict(x=[0,1,2,3],y=[4,5,6,7]))

def change_something(cds=cds):
	print('{}\n{}'.format(cds.data['x'],cds.data['y']))
	cds.data['x'] = [6,6,6,6]
	cds.change.emit()

def something_changed(something='nothing'):
	print('im a good lil boy') # this doesn't print

button.callback = CustomJS.from_py_func(change_something)
cds.callback = CustomJS.from_py_func(something_changed)

l = layout([[button]])
show(l)
```

Repeated clicks demonstrate (in console) that the exchange takes place, but the callback never triggers:
```
0,1,2,3
4,5,6,7

6,6,6,6
4,5,6,7

6,6,6,6
4,5,6,7
```

**Comment by bryevdv** [comment]
You are setting `source.selected.indices = []`, you should have
```
source.selected.js_on_change('indices', callback_select)

```

**Comment by ibestvina** [comment]
Sorry if I'm missing something, but setting it to the line you suggest gives me exactly the same results. Selection in the plot updates, but the div element remains unchanged.

**Comment by npeirson** [comment]
Per-attribute hookups suggests that `ColumnDataSource.data.callback = my_callback` should work, and, although it calls no errors, it is indeed no different than before.

**Comment by bryevdv** [comment]
@ibestvina Good news/bad news. This code (with my suggestion):
```
callback_select = CustomJS(args={'div':div, 'source':source}, code="""
div.text = 'Len: ' + source.selected.indices.length;
""")

callback_click = CustomJS(args={'source':source}, code="""
source.selected.indices = [];
""")

button.js_on_event(events.ButtonClick, callback_click)

source.selected.js_on_change('indices', callback_select)
```
Works the #8310 Pull Request branch. #8310 should be merged later today, and will be part of the next release. 

#8310 fixes an unfortunate mistake made earlier, namely that BokehJS would itself sometimes replace the *source.selected* value with an entirely new Selection. That has a number of bad consequences, including what you see here (i.e. the callbacks you added were to a specific Selection object that the plot started with, then it disappeared when it BokehJS replaced it) However, #8310 fixes things so that Bokeh never replaces *source.selected*, it only ever updates properties on the existing selection, e.g. *source.selected.indices* This leads to much more comprehensible semantics (and is now also able to be maintained under test since our CI infrastructure for selenium tests has been restored). 

So, that's good news for the very near future. I am not sure I have any good workaround to advise for current releases. In any event, this specific same problem covered by the linked issues in #8310 so I am closing this as a `duplicate`.

**Comment by bryevdv** [comment]
@npeirson the `.callback` property is very old, I'd almost forgotten it. It dates from years before the general `.on_change` machinery. I would advise not to use it, and to only use `.on_change`. AFAIK we do not demonstrate `.callback` anywhere in the docs and have not for a long time.

**Comment by npeirson** [comment]
I learned about it from reading the source code. I'll try the on_change methods, instead, though. Cheers.

**Comment by bryevdv** [comment]
@npeirson thanks I am updating the property help string in the source code for that `.callback` property to point to `source.selected.on_change`

**Comment by Tisagh** [comment]
> 
> 
> @npeirson thanks I am updating the property help string in the source code for that `.callback` property to point to `source.selected.on_change`

I was banging my head against a wall because I delivered a program to a client which suddenly stopped producing the selected indices and I couldn't figure out why until I saw this.

Initial code was working fine up to a few weeks ago:
` #create callback for displaying the number of selections and push to file
        sel_call = CustomJS(args={'div': div, 'source': source}, code="""
        div.text = 'Selected: ' + source.selected.indices.length + '<br/> Indices: ' + source.selected.indices;
        var out = "Indices: " + source.selected.indices;
        var file = new Blob([out], {type: 'text/plain'});
        var elem = window.document.createElement('a');
        elem.href = window.URL.createObjectURL(file);
        elem.download = 'selected-indices.txt';
        document.body.appendChild(elem);
        elem.click();
        document.body.removeChild(elem);
        """)

        #Trigger for change in selection
        source.js_on_change('selected', sel_call)`

I made the changes as noted and it works like a charm again. Thank a million.

**Comment by artemklopow** [comment]
> @ibestvina Good news/bad news. This code (with my suggestion):
> 
> ```
> callback_select = CustomJS(args={'div':div, 'source':source}, code="""
> div.text = 'Len: ' + source.selected.indices.length;
> """)
> 
> callback_click = CustomJS(args={'source':source}, code="""
> source.selected.indices = [];
> """)
> 
> button.js_on_event(events.ButtonClick, callback_click)
> 
> source.selected.js_on_change('indices', callback_select)
> ```
> 
> Works the #8310 Pull Request branch. #8310 should be merged later today, and will be part of the next release.
> 
> #8310 fixes an unfortunate mistake made earlier, namely that BokehJS would itself sometimes replace the _source.selected_ value with an entirely new Selection. That has a number of bad consequences, including what you see here (i.e. the callbacks you added were to a specific Selection object that the plot started with, then it disappeared when it BokehJS replaced it) However, #8310 fixes things so that Bokeh never replaces _source.selected_, it only ever updates properties on the existing selection, e.g. _source.selected.indices_ This leads to much more comprehensible semantics (and is now also able to be maintained under test since our CI infrastructure for selenium tests has been restored).
> 
> So, that's good news for the very near future. Bad news is that I am not sure I have any good workaround to advise for current releases, so I can only suggest to wait until a future release with #8310 merged. In any event, this specific same problem covered by the linked issues in #8310 so I am closing this as a `duplicate`.

Thanks! It helped me.
