### ISSUE TITLE
Ratify Project Roles document

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8308]
I have created a draft of *BEP-4: Project Roles* I would like to discuss and agree on any changes in the next week so that it may be marked "Implemented" before the 1.0 release. The draft is here:

https://github.com/bokeh/bokeh/wiki/BEP-4:-Project-Roles

cc @mattpap @birdsarah @canavandl (also @pzwang)

**Comment by bryevdv** [comment]
Things that could be added: 

* schedules (even just loose or encouraged) for meetings. 
* any other roles?
* ?

**Comment by bryevdv** [comment]
Just setting a timebox: Absent any comments, I will plan to close this issue and mark the BEP as "implemented" Wednesday morning

**Comment by birdsarah** [comment]
(I'm swamped at the moment, but am reading all your emails, and my lack of response is agreement).

**Comment by bryevdv** [comment]
I am just recording some minor changes I made on 2020-05-03:

* Add section to record NumFocus Project Committee membership
* Delineate that the NF committee is responsible for use of funds approvals
* Explicitly list the "conduct sub-committee" members 

I don't expect that there should be any contention around these changes but please comment here if there is anything that requires additional discussion.
