### ISSUE TITLE
[Feature Request] ‘from_networkx’ function for a fixed layout

### ISSUE THREAD

**Issue by komo-fr** [bokeh/bokeh#8311]
# Summary
Currently (ver 0.13.0) Bokeh, `from_networkx` function always requests a layout function. 
Personally I think that it is more useful to be able to convert a graph structure using **a fixed layout** as well as layout functions.

# Detail
## Use Cases
I think that this feature is particularly useful in the following scenes.

(A) The case where **the user wants to specify a fixed layout that customizes the position by oneself** instead of using a layout function.
- For example, a transportation network associating nodes with geographical positions.

(B) The case where **the user wants to calculate a layout before calling `from_networkx`** since the calculation time is too long.	
 - Currently, layout is calculated every time `from_networkx` is called. Therefore, it takes time to try to recreate `GraphRenderer` many times. It will become a large problem in the case of a large graph.

I think that it’s a general case to use a fixed layout.

## Workaround
I currently handle a fixed layout by the following methods. But they are **NOT** fundamental solutions.

1. Specify a layout function (eg `nx.spring_layout function`, etc.) as **a dummy** and then update the `layout_provider` attribute with a fixed layout.
    -  [Code Example](http://nbviewer.jupyter.org/github/komo-fr/networkx2bokeh_note/blob/master/notebooks/networkx2bokeh_layout_for_custom_position.ipynb)
2. Prepare a function that returns a fixed layout (dict) and pass it in the argument `layout_function`.
    - [Code Example](http://nbviewer.jupyter.org/github/komo-fr/networkx2bokeh_note/blob/master/notebooks/use_function_return_layout.ipynb#Workaround)

### Problem
Workaround (1) solves use case (A), but it  does **NOT** solve use case (B).
It seems that workaround (2) can solve both use case (A) and (B), **BUT** I think that it’s a bother.
Therefore I hope for a fundamental solution.

# Expected Result
1. Be able to specify a fixed layout in `from_networkx`
2. Or, be able to use `from_networkx` without a layout function

# Solution
I imagine there are several methods of implementation as below, but I don't really have a strong opinion.
If Bokeh has an API design policy and future vision, I would like to follow them.

## Before
https://github.com/bokeh/bokeh/blob/e46ef320ff33be0b64be9d8fbd2eea2ad86aa24c/bokeh/models/graphs.py#L35-L109

### Approach 1. Add a new function for graphs with a fixed layout
- Add a new function apart from the existing `from_networkx`.
- The difference from `from_networkx` is that it is passed a fixed layout (dict) as an argument.

[Code & Usage Example](http://nbviewer.jupyter.org/github/komo-fr/networkx2bokeh_note/blob/master/notebooks/draft_from_networkx_for_fixed_layout.ipynb#Approach-1.-Add-a-new-function-for-graphs-with-fixed-layout)

### Approach 2. Update `from_networkx` to handle both fixed layout and layout function
- Rename `layout_function` to `layout` and allow to receive both dictionary and function.
- If `layout`  is a function, execute the function and calculate the layout. Otherwise, set it directly to `graph_renderer.layout_provider` in `from_networkx`.
- It is **NOT** backward compatible with 0.13.0 since the argument name changes.

[Code & Usage Example](http://nbviewer.jupyter.org/github/komo-fr/networkx2bokeh_note/blob/master/notebooks/draft_from_networkx_for_fixed_layout.ipynb#Approach-2.-Update-from_networkx-to-handle-both-fixed-layout-and-layout-function)

### Approach 3. Update `from_networkx` so that it can be called without a layout function
- Make `layout_function` an optional argument.
- The user manually sets a fixed layout after calling `from_networkx`. 

[Code & Usage Example](http://nbviewer.jupyter.org/github/komo-fr/networkx2bokeh_note/blob/master/notebooks/draft_from_networkx_for_fixed_layout.ipynb#Approach-3.-Update-from_networkx-so-that--it-can-be-called-without-a-layout-function)

## Or Other Approaches
Other people may have better ideas.

I'm often bothered by this problem, so I'm interested in sending a PR.

**Comment by bryevdv** [comment]
I'd suggest:

2b) which is exactly as 2) above but doesn't rename the parameter. I think it is slighltly off ideal, but it is simplest for users and maintains backwards compat. It's a bit of a reach, but a "pure mathematical" definition of a function is just a particular kind of mapping, so I think we an stretch a little and justify a fixed layout to be a kind of "layout_function"

Otherwise:

3b) check for `layout` in kwargs and use that in preference to `layout_function`, but use `layout_function` if it is given. Add a check to make sure both are not specified. We can later deprecate `layout_function`

**Comment by bryevdv** [comment]
@komo-fr also worth adding: If you'd like this in 1.0 then Friday is a pretty firm deadline, but it can of course always go in a later release if you are not free before then.

**Comment by komo-fr** [comment]
@bryevdv 
I appreciate your suggestion and the important notice about the release.

I agree with 2b).
Really, I want to support 3b). Also, I think that I can implement 3b) if I have time.　
However, considering the time taken for review and testing, I think it would be better for me to support 2b) in order to meet the deadline.

I will send a PR  as soon as possible.
Thank you for sparing your precious time for me.
