### ISSUE TITLE
Bokeh fails to render widgets in Jupyter when notebook server is remote

### ISSUE THREAD

**Issue by rcthomas** [bokeh/bokeh#8315]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

* bokeh: 0.13.0
* python: 3.6.5
* notebook: 5.7.0
* jupyterlab: 0.34.12
    * @jupyter-widgets/jupyterlab-manager v0.37.4  enabled  OK
    * jupyterlab_bokeh v0.6.2  enabled  OK
* OS: Linux for server, Mac for client
* Browser: various, including Chrome for Mac 69.0.3497.100

#### Description of expected behavior and the observed behavior

When I run `jupyter lab` on my laptop locally, I can make the included cell of code render a button.  But if I start up `jupyter lab` remotely, e.g. through JupyterHub or using an ssh tunnel, it does not render the button.

In the JavaScript console in Chrome I see errors like: `Failed to load resource: net::ERR_CONNECTION_REFUSED http://localhost:43107/autoload.js?bokeh-autoload-element=03d156b5-8641-44be-b235-1e84da033d72&bokeh-absolute-url=http://localhost:43107&resources=none`

I have confirmed that if I run jupyter lab on the remote host, and also run a browser on that remote host, it does render the button as I expect.  It looks like the `localhost` bit here is just wrong but I haven't figured out how it is getting in.  It is reminiscent of #6598?

```
from bokeh.io import output_notebook, show
output_notebook()

from bokeh.layouts import column
from bokeh.models.widgets import Button

def modify_doc(doc):
    button = Button(label="Say HI")
    layout = column(button)
    doc.add_root(layout)
        
show(modify_doc)
```

**Comment by bryevdv** [comment]
@rcthomas I believe this the information you need was added in #8121 which was a follow on to the actual implementation work in #7686. I'm not a user of remote notebooks, so I will have to defer to the other participants in those issues/PRs.
