### ISSUE TITLE
Non-uniform widget width

### ISSUE THREAD

**Issue by omnesia0rg** [bokeh/bokeh#8316]
(BokehJS 0.13.0)
(bokeh==0.13.0)

Using the same width for different widgets results in different actual widths.
The below MWE shows this behaviour for the Select, Button, MultiSelect and TextInput widgets.
```
from bokeh.layouts import Column, WidgetBox
from bokeh.models.widgets import Select, Button, MultiSelect, TextInput
from bokeh.io import show, output_notebook
output_notebook()

w=200
show(
    Column(
        WidgetBox(Select(value="SelectInBox", options=["SelectInBox"]), width=w),
        WidgetBox(Button(label="ButtonInBox"), width=w),
        
        Select(value="SelectNoBox",options=["SelectNoBox"], width=w),
        Button(label="ButtonNoBox", width=w),
        MultiSelect(width=w),
        TextInput(width=w)
    )
)
```
Output:
![2018101109 20 25_screenshot_sel](https://user-images.githubusercontent.com/24209580/46787215-55bac900-cd37-11e8-86b9-50ead05d967e.png)

Widgets with optional labels have additional padding on the right side, which makes them render smaller than the supplied width. The container for the widget with its label has the correct size though.

The amount of padding is also not the same between different widgets that have labels.

The default widths for the Select and Button widget when wrapped in a WidgetBox differ in the same way.

**Comment by bryevdv** [comment]
@mattpap is this covered by #8085 ? I feel like this issue is a duplicate, in any case.

**Comment by bryevdv** [comment]
@omnesia0rg thanks for the report, I am going to go ahead and close this as duplicative, please watch #8085 for comprehensive layout developments and improvements scheduled for 1.1
