### ISSUE TITLE
screen units for x,y

### ISSUE THREAD

**Issue by waqarmalik** [bokeh/bokeh#833]
I've followed examples where size, and width,height can be set in screen units.
Is there something similar for x, y. I'm trying to display a fixed size information box on the plot. (x_units, y_units does not seem to work)

    from bokeh.plotting import *
    
    output_file("rect.html", title="rect.py example")
    
    figure(title='Test1', tools="pan,wheel_zoom", plot_width=400, plot_height=400)
    rect([0], [0], 50, 30, width_units='screen', height_units='screen', color="red")
    
    figure(title='Test3', tools="pan,wheel_zoom", plot_width=400, plot_height=400)
    rect([0], [0], 50, 30, x_units='screen', y_units='screen', width_units='screen', height_units='screen',color="blue")
    
    show()

**Comment by bryevdv** [comment]
Gah, this should have been fixed ages ago.

**Comment by schlichtanders** [comment]
in the bokeh version 0.12.3 this feature seems to have gone.
are there plans to include it again?

**Comment by bryevdv** [comment]
@schlichtanders Trying to maintain spatial indices for selection and hover hit testing on mixed data/screen coordinates for glyphs proved too difficult. If you need screen units that probably means you actually need an annotation of some sort, and annotations, e.g `BoxAnnotation` *do* support screen coordinates and dimensions (but do not participate in hit testing for selections)

**Comment by schlichtanders** [comment]
Thanks for the explanation.
I am searching for a way to mirror something like the background Grid
shading with boxes of different colours indicating something...

I now will take a boy with very high size, however a Screen units height
and a Screen units y value would have done the Trick even better.

If you know of a feature to implement "infinite" rects,
I am glad to hear. (something like rays only with shape units for the width
would do too but this wasn't possible so far)

**Comment by bryevdv** [comment]
Yes, `BoxAnnotation` supports "infinite bounds" as well. That is what you want

**Comment by schlichtanders** [comment]
If I think again about it, I guess the selection feature is not that crucial in this "background information" scenarios.
thanks a lot for explaining and helping

**Comment by schlichtanders** [comment]
True you said this and probably i will take those for now.
However, of course, it would be awesome to have at least the option to
combine this with bokeh's already impressive selection feature.

Thank you very much
