### ISSUE TITLE
Autohide toolbar quirks

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#8332]
### Does not become hidden when mouse moves slowly off canvas
When `toolbar.autohide == True`, the toolbar remains visible if you let your mouse drift slowly off the edge.

![slowly](https://user-images.githubusercontent.com/4806877/46954334-4a7cdb80-d05e-11e8-9935-8720b99c47cb.gif)

### Interacting with the plot causes the toolbar to disappear
It reappears when the mouse is moved. 

**Proposal:** I think this behavior could be resolved by keeping track of visible state either on the model or on the renderer.

![pan_wheel_autohide](https://user-images.githubusercontent.com/4806877/47460453-89243b80-d7ac-11e8-8020-984a2373e66d.gif)

```python
from bokeh.plotting import figure, show

plot = figure(width=400, height=400, title='Toolbar Autohide')
plot.line([1,2,3,4,5], [2,5,8,2,7])
plot.toolbar.autohide = True

show(plot)
```

<details>
<summary>Version</summary>
<br>

```
Python version      :  3.6.6
IPython version     :  5.8.0
Tornado version     :  4.5.3
Bokeh version       :  1.0.0dev11
node.js version     :  v8.10.0
npm version         :  6.4.1
```
</details>

**Comment by jsignell** [comment]
We should probably move it out of the milestone. If we don't catch the mouse leaving the area I don't see how we could know that the toolbar should be hidden.

**Comment by philippjfr** [comment]
I would suggest either reopening this issue or I could file a new one. In many, many cases the autohide behavior does not work for me, specifically in the single plot case it does not work for me in a notebook and when using a ProxyToolbar I could not get it to work at all.

**Comment by bryevdv** [comment]
Let's open a fresh issue.

**Comment by mattpap** [comment]
I tested `autohide` in notebook and jlab on 3.0-dev.7 and everything seem to work fine. Please start an issue with specifics, so that I know how the environment may affect bokehjs.
