### ISSUE TITLE
Y-Range for negative value

### ISSUE THREAD

**Issue by djangoliv** [bokeh/bokeh#8334]
The y_range automatic calculation does not support negative values.
The code below have a y_range like [-1, 3] instead of [-8,3]

```
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from bokeh.io import show

data = {
    'values': [1,2,3,-8],
    'left': range(10),
    'right':range(1,11),
}
source = ColumnDataSource(data)
plot = figure(title=None)
plot.quad(
    source=source,
    bottom=0,
    top='values',
    left='left',
    right='right',
)
show(plot)
```
I know I can do `plot = figure(title=None, y_range=[-10, 10])`
but the y_range can change ( in CustomJS callback that modify source).
Regards

**Comment by bryevdv** [comment]
Thanks for the report @djangoliv
