### ISSUE TITLE
Feature request: using string as label in a slider

### ISSUE THREAD

**Issue by mauropu** [bokeh/bokeh#8338]
Good morning
I am writing a little (very little) BI with bokeh.
The slider at today can use only number.
Is possible to define string in the slider?
In this way I can animate the dashbord of BI
Kind regards
Mauro

**Comment by bryevdv** [comment]
Bokeh uses noUIslider as its implementation:

https://refreshless.com/nouislider/

AFAICT it does not support string/categorical labels or ranges. Unfortunately I we definitely do not have the resources to change out our slider implementation at this time. However, Bokeh is extensible:

https://bokeh.pydata.org/en/1.0.4/docs/user_guide/extensions.html

And in fact there is a complete example of how to wrap a different slider library here:

https://bokeh.pydata.org/en/1.0.4/docs/user_guide/extensions_gallery/widget.html#userguide-extensions-examples-widget

So you could write a custom extension to use a slider slider library to use categorical labels. 

Given that there is this possibility for users to create their own solution, and the unlikelihood that we will be able to make any change to the core library slider at this time, I am closing
