### ISSUE TITLE
Bug with tiles and ranges during the first figure loading

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#8354]
Actually I am not sure if it is a bug or am I doing anything wrong. Let me know

Checked on Bokeh 0.13.0

**Steps to reproduce the bug**

This is happening only in the first figure loading.

1. Plot a map with a scatter glyph with fixed or automatic ranges
1. Click on the map or on some sample. Then the vertical range changes

Check the GIF below to see the behaviour

If I comment the line `map1.add_tile(tile_source)` to remove the tile source then the range behaviours are normal.

This is the code (minimal example)

    from bokeh.io import output_notebook, show, push_notebook
    from bokeh.models.tiles import WMTSTileSource
    from bokeh.plotting import figure, Figure
    output_notebook()

    from bokeh.models import ColumnDataSource, Range1d, Circle
    from bokeh.plotting import figure
    import pandas as pd
    import numpy as np

    df = pd.DataFrame({'X_WMTS': np.array([-1053015.59120989, -1072774.8008257 , -1087346.52217054,
        -1091153.64875567, -1099491.47861608, -1107183.6554299 ,
        -1117191.27765222, -1146724.33855967, -1177470.78191677,
        -1214106.02633684, -1262474.34508651, -1311287.94179936,
        -1360257.38579933, -1406477.23837669, -1458318.72523912,
        -1501955.96563009, -1546116.40762778, -1589308.37005557,
        -1633390.8884097 , -1677039.26074974, -1720899.1401223 ,
        -1764391.66517523, -1808218.14870054, -1851911.0488369 ,
        -1895848.851853  , -1939641.93953108, -1983112.20068585,
        -2027127.92734551, -2059811.32984242, -2092338.88505221,
        -2125055.68339635, -2157416.25936996, -2189765.70339449,
        -2222994.57139627, -2255488.73075883, -2287971.75817231,
        -2320577.23702566, -2353449.88265691, -2385610.08354709,
        -2418571.78477098, -2450876.70099919, -2483715.9507832 ,
        -2527286.39947969, -2570545.15360196, -2613859.56746962,
        -2646554.1019156 , -2679716.17822292, -2711553.5525898 ,
        -2744804.68448975, -2777521.48283389, -2809247.53770997,
        -2863927.67158763, -2907965.66214545, -2956567.75182579,
        -3005459.2721822 , -3038176.07052634, -3070113.63243493,
        -3103453.81992752, -3136148.3543735 , -3198298.02608338,
        -3259379.03068165, -3309049.78747361, -3351039.49940084,
        -3379926.90726169, -3417263.46447375, -3480459.5393971 ,
        -3551960.04833361, -3624061.68252042, -3695395.21222075,
        -3765515.35947143, -3837694.91730179, -3900712.88103986,
        -3981018.76169813, -4051650.97860646, -4123207.14728838,
        -4194596.3367341 , -4265384.40092955, -4336806.98622251,
        -4408140.51592284, -4480876.67120717, -4553490.37505162,
        -4597595.15730391, -4645473.6702941 , -4675741.43984079,
        -4701623.22145023, -4706042.60523472, -4710205.95419039,
        -4719801.69429677, -4733260.22073367, -4795298.57295277,
        -4786827.1597034 , -4776351.99561975, -4763984.40019262,
        -4753553.76390529, -4743935.75990075, -5012683.27457387,
        -5025830.10643656, -5078306.11439651, -5081623.43522215,
        -5083482.47071839, -5129969.49007366, -5241834.44637182,
        -5502956.57592561]), 'Y_WMTS': np.array([
        4914393.17435343, 4914480.79336707, 4914656.03373153,
        4914539.20647563, 4914115.71928288, 4914583.01653428,
        4914641.43024879, 4914743.65508239, 4915006.52380982,
        4914217.93866321, 4914363.96818867, 4914509.99987807,
        4914334.76211046, 4946411.40518537, 4981018.9036926 ,
        5024828.16427532, 5069088.29266124, 5113448.06754093,
        5158478.19320584, 5203270.58741918, 5248517.51398303,
        5293678.84928275, 5339532.06559023, 5385059.68314787,
        5431336.2132169 , 5477381.34851629, 5524063.81756131,
        5570297.67485582, 5629601.24000696, 5687965.32128936,
        5747318.97787082, 5807682.04039284, 5868087.79428053,
        5928553.16443884, 5989522.17421942, 6051352.21572224,
        6113228.95704575, 6175857.19177578, 6238746.04176021,
        6301849.51265215, 6365377.41471618, 6429718.75264878,
        6516502.80481585, 6603976.93076141, 6692570.55533001,
        6758518.94420974, 6826839.41153644, 6894699.80128242,
        6962824.36462925, 7032241.41920981, 7102137.84543597,
        7220828.7621808 , 7315637.86423591, 7425903.63833862,
        7535080.04676747, 7608746.16358524, 7684421.66868061,
        7760936.28212792, 7837732.98140179, 7899332.01514114,
        7961437.90791959, 8011139.35543124, 8053518.4321829 ,
        8083732.48201117, 8121034.64767258, 8146465.71356387,
        8161110.7111051 , 8174683.0194359 , 8189145.64366744,
        8202574.12668435, 8215983.47838833, 8229961.02277085,
        8245469.26009489, 8259196.68037274, 8273431.0540993 ,
        8287363.91019633, 8301652.58067782, 8316431.18017458,
        8330092.44859512, 8338279.27075056, 8345988.91350429,
        8349415.55019557, 8354149.13523997, 8355167.0313774 ,
        8357225.38079345, 8358775.05486268, 8359262.16250993,
        8360391.49029903, 8362119.03193683, 8380637.98233119,
        8378484.28986652, 8375332.59601498, 8372293.15368155,
        8368678.51410577, 8365553.16839582, 8354746.57899756,
        8342055.76903334, 8289666.66944142, 8281226.718201  ,
        8274963.2614895 , 8195012.20700107, 7853753.08384841,
        7111982.83868035]), })

    source = ColumnDataSource(df)
    tile_options = {
        'url': ("https://server.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{Z}/{Y}/{X}/")
    }
    tile_source = WMTSTileSource(**tile_options)
    map1 = Figure(
        plot_height=300,
        plot_width=300,
        output_backend='webgl',
        tools='pan,box_zoom,box_select,lasso_select,wheel_zoom,tap,save,reset,crosshair',
        x_axis_type='mercator',
        y_axis_type='mercator',
    )
    map1.axis.visible = True
    map1.add_tile(tile_source)
    map1.scatter(
        x='X_WMTS',
        y='Y_WMTS',
        source=source,
        color='#00FF00',
        fill_alpha=1.0,
    )
    show(map1)

![tile bug](https://user-images.githubusercontent.com/11211829/47359757-cbc31680-d6cd-11e8-9f63-c255ad9452da.gif)

**Comment by philippjfr** [comment]
I'm not sure why this would be triggered by a tap but I suspect this is due to code in the TileRenderer which changes the axis ranges to ensure that the aspect ratio is correct.

**Comment by chesucr** [comment]
I have just check with the 1.0 version and now it is working fine

**Comment by bryevdv** [comment]
Happy surprise!
