### ISSUE TITLE
Compiler issue on Windows, importing modules is not working because of backslash incompatibility

### ISSUE THREAD

**Issue by deluksic** [bokeh/bokeh#8355]
I was trying to follow the example for simple custom model on windows, and I ran into the issue where BokehJS compiled .json files look like this:

> ["base","client\\\\connection","client\\\\session","core\\\\bokeh...

and should look like:

> ["base","client/connection","client/session","core/bokeh...

This makes the compiler fail because it can't find the specified modules, specifically on these lines:

```
def resolve_modules(to_resolve, root):
        resolved = {}
        for module in to_resolve:
            if module.startswith(("./", "../")):
               ^
```

Ultimately, I get
```
RuntimeError: no such module: core/dom
```
I'm sorry if this is repost, I couldn't find anyone with the same issue.

For now, workaround is to replace all `\\` to `/` in all `bokeh/bokeh/server/static/js/*.json` files.

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by bryevdv** [comment]
@mattpap I feel like there was a similar issue closed already?

**Comment by xavArtley** [comment]
https://github.com/bokeh/bokeh/pull/8565

**Comment by bryevdv** [comment]
Thanks @xavArtley !
