### ISSUE TITLE
DataTable crashes layout if 'field' is key in ColumnDataSource data

### ISSUE THREAD

**Issue by cutright** [bokeh/bokeh#8356]
Bokeh 0.13.0
Mac OS 10.13.3
python 2.7.10
Safari 11.0.3

If 'field' is a key in the data of ColumnDataSource, bokeh serve cannot generate a layout including a DataTable using this ColumnDataSource.  This only fails if the DataTable is in the layout, the DataTable may exist if not in the layout.

The following code will fail.  If you replace 'field' in variables with almost anything else, the code works.

```
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import TableColumn, DataTable
from bokeh.io import curdoc
from bokeh.layouts import column


variables = ['x', 'y', 'field']
source = ColumnDataSource(data={v: [i] for i, v in enumerate(variables)})
table = DataTable(source=source, columns=[TableColumn(field=v, title=v) for v in variables])
curdoc().add_root(column(table))
```

**Comment by bryevdv** [comment]
Very bizarre, I had some notions about possible failure modes but none of them seem to be right,. Things are falling over before the session is even fully realized.

**Comment by bryevdv** [comment]
Ok, this is probably the correct fix, but will need rigorous tests
```
diff --git a/bokehjs/src/lib/core/properties.ts b/bokehjs/src/lib/core/properties.ts
index ca469e63f..c6f4a48eb 100644
--- a/bokehjs/src/lib/core/properties.ts
+++ b/bokehjs/src/lib/core/properties.ts
@@ -132,7 +132,7 @@ export class Property<T> extends Signalable() {
     else
       this.spec = {value: attr_value}

-    if (this.spec.field != null && !isString(this.spec.field))
+    if (this.dataspec && this.spec.field != null && !isString(this.spec.field))
       throw new Error(`field value for property '${attr}' is not a string`)

     if (this.spec.value != null)
```

**Comment by RunOrVeith** [comment]
I have just experienced a similar bug. However, my data does not contain the keyword "field". Instead, I am using a networkx graph with a node named "field".
The error message I get from the firefox dev console is also quite cryptic:

`Error: field value for property 'graph_layout' is not a string`.

To reproduce, I used
```python
import networkx as nx
from bokeh.models.graphs import from_networkx
from bokeh.models import Circle
from bokeh.plotting import figure
from bokeh.plotting import show


G = nx.Graph()
G.add_node("field")  #  <-- This is the problem

fig = figure()
graph = from_networkx(graph=G, layout_function=nx.random_layout, center=(0, 0), dim=2)
graph.node_renderer.glyph = Circle(size=10, fill_color="blue")
fig.renderers.append(graph)
show(fig)
```

The commit above fixes this issue, however I am not sure (especially due to @bryevdv's comment "this is probably the correct fix" and the cryptic error message)  if the bug is not more general than only a keyword "field", hence me commenting here.
