### ISSUE TITLE
DataTable fit_columns=True not working with Chrome

### ISSUE THREAD

**Issue by Skap95** [bokeh/bokeh#8358]
Hi, 

As said in the documentation DataTable got the attribute fit_columns, this attribute setting as True must hide the horizontale scrolling bar. 

> fit_columns
property type: Bool
Whether columns should be fit to the available width. This results in no horizontal scrollbar showing up, but data can get unreadable if there is no enough space available. If set to True, columns’ width is understood as maximum width.

Working fine on Firefox but not with Chrome .... 
```
from bokeh.plotting import output_file, show, reset_output
from bokeh.models.widgets import DataTable, TableColumn
from bokeh.models import ColumnDataSource
x=[1,2,3,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
y=[2,1,2,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
source_zoom_j=ColumnDataSource(data=dict(x=x, y=y))
columns_j=[
        TableColumn(field="x", title="X"),
        TableColumn(field="y", title="Y"),
    ]
table=DataTable(source=source_zoom_j, 
            columns=columns_j, 
                width=600, 
                height=100, 
                editable=False, 
                index_position=None,
                fit_columns=True)  
output_file("test.html")
show(table)
reset_output() 
```
Chrome:
![image](https://user-images.githubusercontent.com/23317880/47417476-582a1380-d778-11e8-9663-9ba2c79e24f4.png)

Firefox: 
![image](https://user-images.githubusercontent.com/23317880/47417505-67a95c80-d778-11e8-9c61-4efd165bdcbe.png)

Versions:
Python: 3.7.0
Bokeh: 0.13.0
OS: Windows
Browser: Chrome

**Comment by bryevdv** [comment]
This is working for me on master with Chrome (probably fixed in #8085)

<img width="670" alt="screen shot 2019-02-18 at 19 54 07" src="https://user-images.githubusercontent.com/1078448/52989163-08bac380-33b7-11e9-9949-f0abeca8afaf.png">
