### ISSUE TITLE
JS Error when I set a new Circle to a selection_glyph in a scatter glyph

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#8365]
Version 1.0.0
    OS: Windows 10
    Ptyhon version: 3.6.5

This was working on the 0.13.0 version. When I plot a Scatter glyph and then I set a new Circle to the `selection_glyph` I get the error when I select some samples. An easy workaround is to use `p.circle()` instead of `p.scatter()`

    from bokeh.io import output_notebook, show, push_notebook
    output_notebook()

    from bokeh.models import ColumnDataSource, Circle
    from bokeh.models.widgets.buttons import Button
    from bokeh.plotting import figure, curdoc
    from bokeh.layouts import gridplot
    from bokeh.layouts import row, column
    import numpy as np

    N = 500
    source = ColumnDataSource(dict(
        x=list(range(0,N)),
        y=np.random.randint(300, size=(N)),
    ))

    p = figure(
        plot_height=400,
        plot_width=400,
        tools='lasso_select,pan'
    )

    rc = p.scatter(
        x='x',
        y='y',
        size=3,
        source=source,
        marker='circle',  # by default
    )

    rc.selection_glyph = Circle(
        line_color='red',
        line_alpha=1.0,
        fill_color='yellow',
    )

    show(p)

![image](https://user-images.githubusercontent.com/11211829/47566224-4c328300-d92b-11e8-8659-1b4b54ff67a6.png)

**Comment by bryevdv** [comment]
@chesucr this is fallout from https://github.com/bokeh/bokeh/pull/8285

As `scatter` returns a new `Scatter` glyph now, that's what has to be used instead of `Circle` (selection/nonselection glyph typed must match original glyph type)

```
rc.selection_glyph = Scatter(
    line_color='red',
    line_alpha=1.0,
    fill_color='yellow',
)
```
<img width="754" alt="screen shot 2018-10-26 at 07 52 59" src="https://user-images.githubusercontent.com/1078448/47574323-2d64ca00-d8f4-11e8-8e9d-ef1f1675888f.png">

**Comment by chesucr** [comment]
Nice! I have read, in your latest blog post, about the new scatter glyph, but I missed that a new Scatter object was created. Thank you Bryan, and sorry for the wrong issue :/

**Comment by chesucr** [comment]
Also, the error message was a bit confusing. Maybe some specific error message, about the wrong glyph assignment, would be helpful
