### ISSUE TITLE
Bokeh data table selection event not working after version upgrade 1.0.0

### ISSUE THREAD

**Issue by false9striker** [bokeh/bokeh#8366]
After bokeh version 1.0.0 upgrade I get not subscriptable error on data table row click. This was working perfectly fine with version 0.13 Details below :

```
tblSource.selected.on_change('indices', table_select_callback) 

def table_select_callback(attr, old, new):

    try:
        selected_index = tblSource.selected["1d"]["indices"][0]
        selectedId = str(tblSource.data["idList"][selected_index])

        print(selectedId)
    except IndexError:
        pass


```

#### Stack traceback and/or browser JavaScript console output

```
2018-10-25 10:18:19,784 error handling message Message 'PATCH-DOC' (revision 1) content: {'events': [{'kind': 'ModelChanged', 'model': {'type': 'Selection', 'id': '4937'}, 'attr': 'indices', 'new': [2]}], 'references': []}: TypeError("'Selection' object is not subscriptable",)

$ bokeh --version
1.0.0
```

SOF - https://stackoverflow.com/q/53013832/649451

**Comment by bryevdv** [comment]
This usage was disallowed in 0.12.15:

https://bokeh.pydata.org/en/latest/docs/releases.html#selections

The current and supported mechanism for accessing selections, that is now rigorously maintained under unit and integration tests, is to access `selected.indices`, etc.

**Comment by false9striker** [comment]
Thanks! 👍
