### ISSUE TITLE
histogram example should take edges as argument to make_plot

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8369]
The function `make_plot` in https://bokeh.pydata.org/en/latest/docs/gallery/histogram.html

Doesn't take `edges` as an input. The code still runs correctly, but it would be more consistent if we were passing along edges too.

The method in question:

```
def make_plot(title, hist, x, pdf, cdf):
    p = figure(title=title, tools='', background_fill_color="#fafafa")
    p.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:],
           fill_color="navy", line_color="white", alpha=0.5)
    p.line(x, pdf, line_color="#ff8888", line_width=4, alpha=0.7, legend="PDF")
    p.line(x, cdf, line_color="orange", line_width=2, alpha=0.7, legend="CDF")

    p.y_range.start = 0
    p.legend.location = "center_right"
    p.legend.background_fill_color = "#fefefe"
    p.xaxis.axis_label = 'x'
    p.yaxis.axis_label = 'Pr(x)'
    p.grid.grid_line_color="white"
    return p
```

**Comment by Maggie-M** [comment]
Whoops, I accidentally pushed this change to master, rather than making a branch for it, but I think it should be done now!

https://github.com/bokeh/bokeh/commit/bd4c9267cf300b6c41b611c0817d8c8fc24561c9
