### ISSUE TITLE
Garbage collection of export_png() 

### ISSUE THREAD

**Issue by chyan26** [bokeh/bokeh#8374]
I am using export_png() for producing images.  However, the phamtonjs process does not go away when program is fiished.  After running the program for few times, I need to clean the phamtonjs process before it eat up all memory.  

Therefore, I am writing to ask a possible way to do garbage collection after export_png() is done.

**Comment by philippjfr** [comment]
I've noticed the same thing. In holoviews we use static export to generate thumbnails for our examples, and when building the docs I end up with about 100 phantomjs processes, which use an inordinate amount of CPU.

**Comment by mattpap** [comment]
Issue #6525 seems related.
