### ISSUE TITLE
Export CSV example more useful if you don't have to hard code headers in download.js

### ISSUE THREAD

**Issue by GenevieveBuckley** [bokeh/bokeh#8379]
The example code at bokeh/examples/app/export_csv would likely be more useable if you didn't have to specify in advance what the datatable column headings were in download.js

@jni recently went to some effort to work out a nicer way of doing this for one of our own projects, and we thought we'd share the solution here for others to benefit from as well. 

#### Description of expected behavior and the observed behavior
Expected behavior: I want to be able to pass in any kind of table, with arbitrary numbers of columns, and arbitrary column headings.
Actual behavior: It doesn't work unless you edit the download.js file which contains hard-coded column header names.

**Comment by GenevieveBuckley** [comment]
@jni - you don't seem to have a fork of the bokeh repo. I've got a branch with the changes here https://github.com/GenevieveBuckley/bokeh/tree/export-csv-example

Do you want to fork that branch and put a PR in yourself? It's your hard work!

**Comment by bryevdv** [comment]
Certainly happy to consider a PR to make the example more general
