### ISSUE TITLE
Line example is too complicated

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#839]
I took a look at http://nbviewer.ipython.org/github/ContinuumIO/bokeh-notebooks/blob/master/tutorial/exercises/basic/01-lines.ipynb

This example is way too complex.
```
# Skip the first point because it can be troublesome
theta = np.linspace(0, 8*np.pi, 10000)[1:]

# Compute the radial coordinates for some different spirals
lituus = theta**(-1/2)          # lituus
golden = np.exp(0.306349*theta) # golden
arch   = theta                  # Archimedean
fermat = theta**(1/2)           # Fermat's

# Now compute the X and Y coordinates (polar mappers planned for Bokeh later)
golden_x = golden*np.cos(theta)
```
  It requires readers to understand advanced polar math, numpy, python and bokeh.  This severely limits your audience.  Why not use simple python arrays, and list comprehensions.  I think the examples should demonstrate the simplest ways to use bokeh, not the most advanced complexities that bokeh is capable of.

**Comment by bryevdv** [comment]
Ongoing, but first example has been made very simple already.

**Comment by bryevdv** [comment]
So, this immediate issue is completed. The line tutorial now only makes use of python list literals. So, I am closing this as completed. 

There are lots of tutorial improvements to make I want to make a clean master issue with linked subissues to start work from.
