### ISSUE TITLE
"Tile Cannot Extend" SystemError when exporting plot with legend placed outside and above plot area

### ISSUE THREAD

**Issue by kpfmcgrath** [bokeh/bokeh#8391]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh: 1.0.0
Python: 3.7.0
phantomjs: 2.1.1
Selenium: 3.14.1

#### Description of expected behavior and the observed behavior
Expected behavior:
Plot exports correctly to a PNG file.

Observed behavior:
Webdriver raises a TimeoutException and reports a SystemError 'tile cannot extend outside image'.
This only happens if the legend is placed in the 'above' location.  Other locations seem to export without issue.
Also, this occurs when called from a callback function.  Calling _export_graphs()_ immediately after the _curdoc().add_root(layout)_ call works without a problem.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
from bokeh.io import curdoc, export_png
from bokeh.layouts import column
from bokeh.models import Legend, Button
from bokeh.plotting import figure, output_file


def export_graphs():
    print("Exporting...")
    export_png(p, 'plot.png')
    print("Done")


x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)

output_file("legend_labels.html")

p = figure(toolbar_location="above")

r0 = p.circle(x, y)
r1 = p.line(x, y)

r2 = p.line(x, 2*y, line_dash=[4, 4], line_color="orange", line_width=2)

r3 = p.square(x, 3*y, fill_color=None, line_color="green")
r4 = p.line(x, 3*y, line_color="green")

legend = Legend(items=[
    ("sin(x)"   , [r0, r1]),
    ("2*sin(x)" , [r2]),
    ("3*sin(x)" , [r3, r4]),
], location=(0, -30))

# Adding legend above the graph area causes issue.
p.add_layout(legend, 'above')

export_button = Button(label='Export Graph')
export_button.on_click(export_graphs)

layout = column(p, export_button, sizing_mode='fixed')

curdoc().add_root(layout)

# This command works.
# export_graphs()
```

#### Stack traceback and/or browser JavaScript console output
Exporting...
2018-11-01 08:57:30,117 The webdriver raised a TimeoutException while waiting for                      a 'bokeh:idle' event to signify that the layout has rendered.                      Something may have gone wrong.
2018-11-01 08:57:30,224 error handling message Message 'PATCH-DOC' (revision 1) content: {'events': [{'kind': 'ModelChanged', 'model': {'type': 'Button', 'id': '2114'}, 'attr': 'clicks', 'new': 1}], 'references': []}: SystemError('tile cannot extend outside image')

**Comment by bryevdv** [comment]
Sorry this got missed and was never triaged. However I just tested with #8085 and it works (but not with 1.0.4) so I will mark it to be resolved by that PR. Fix will be in 1.1
