### ISSUE TITLE
Bokeh doesn't load resources correctly when loading saved notebook

### ISSUE THREAD

**Issue by mstewart141** [bokeh/bokeh#8392]
Opening this issue on request of Luke Canavan per a discussion on twitter about bokeh plotting with `nteract`'s `papermill`.

First off, I love the library and I thank y'all for the hard work.

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python 3.6.1, confirmed issue on local macbook and on ec2 instances, as well as in ubuntu docker.
```
bokeh==1.0.0
geoviews==1.5.3
holoviews==1.10.7
```

#### Description of expected behavior and the observed behavior
Expected behaviour: plots render the same way when generated through a triggered notebook as when they are run by opening the notebook and clicking "run all cells".

Actual behaviour: notebook registers and displays the holoviews (if using holoviews) and bokeh "extension insignia" but silently produces no plots when run via `papermill`.

#### Complete, minimal, self-contained example code that reproduces the issue
Notebook to be run via papermill:
`my_notebook.ipynb`
```
import warnings
warnings.filterwarnings('ignore')

import geoviews as gv
import holoviews as hv  # or import bokeh directly, same

hv.notebook_extension('bokeh') # NOTE: when set to `matplotlib` everything works
gv.extension('bokeh') # NOTE: when set to `matplotlib` everything works

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

%matplotlib inline

from my_module import *

# NOTE: both of the below are passed in to the NB via `papermill` parameters cell
# NOTE: problem persists even if everything is hard-coded in and params are omitted
locals()[fn_name](**fn_params)
```

Please note that the issue persists when using simply bokeh or holoviews (bokeh backend) plots as well, this just happens to be what I was working on. The screen grab below shows matplotlib backend producing various plots, including simple ones, that are not output by bokeh:
```
# inside `my_module`
def a_fn_named_fn_name():
    dallas_zips_raw = gpd.read_file("tx_texas_zip_codes_geo.min.json")

    dallas_zips = dallas_zips_raw.astype({c: float for c in ("INTPTLON10", "INTPTLAT10")}).query(
        """(-97.54 < INTPTLON10 < -96.483) and (32.53 < INTPTLAT10 < 33.158)"""
    )
    # plot a geopandas df using geoviews (removing both from the equation does not mitigate issue)
    dallas_zips_plot = gv.Polygons(gpd.GeoDataFrame(dallas_zips), vdims=[], label="DFW")
    papermill.display("test0", "TEST0")
    papermill.display("test", dallas_zips_plot)
```

#### Stack traceback and/or browser JavaScript console output
None, no warnings either, rather, a silent failure to produce plots.

#### Screenshots or screencasts of the bug in action
This is the screen grab from `matplotlib` (for bokeh backend the holoviews and bokeh insignias appear but no plots):
![image](https://user-images.githubusercontent.com/19676394/47945612-6b4b8a80-dec0-11e8-922b-82364a36a98e.png)

**Comment by philippjfr** [comment]
Thanks for filing this, while I haven't tried it papermill looks really great and it would be great if we could get it to work with bokeh plots. While the same issue you describe here probably applies to bokeh itself as well, it might make more sense to migrate this specific issue over to the holoviews repo.

**Comment by mstewart141** [comment]
Thank you for your holoviews tutorials on youtube :)

I believe this is a bokeh issue and not related to holoviews, per say. This is my belief because:
- holoviews matplotlib backend works
- matplotlib directly works

- holoviews bokeh backend does not work
- bokeh directly does not work

However, I am happy to migrate the issue if that is for the best.

**Comment by philippjfr** [comment]
You're right that it is probably both a bokeh and a holoviews issue. Due to the way bokehJS is loaded it may however be the case that even if this is fixed at the bokeh level somehow, holoviews might apply similar changes. I'd be happy to wait for this to be solved in bokeh first and then revisit though.

**Comment by canavandl** [comment]
I think the issue likely has the same root cause as described here: https://github.com/bokeh/jupyterlab_bokeh/issues/49#issuecomment-409651117

@mstewart141 (thanks for opening the issue BTW) If you have a second, do you mind trying the suggested workaround of loading Bokeh like:

```
from bokeh.plotting import output_notebook, figure, show

output_notebook(hide_banner=True)
```

In terms of writing a fix, is there a better way to handle the missing DOM element (https://github.com/bokeh/bokeh/blob/13baccbb2835f7d5831c22b5cf68214e89c02618/bokeh/core/_templates/autoload_js.js#L79) which happens when notebooks are executed asynchronously? Is it acceptable to just not add the ``BokehJS is loaded`` banner but still load in such a case?

**Comment by mstewart141** [comment]
i will try that out!

**Comment by mstewart141** [comment]
the `output_notebook(hide_banner=True)` did not appear to have any effect; the plot does not render with this setting enabled

**Comment by philippjfr** [comment]
Thanks for investigating @canavandl. @mstewart141 If you get the time could you try whether trusting the notebook as suggested in step 2 fixes your issues with holoviews generated bokeh plots?

**Comment by mstewart141** [comment]
Yes, sounds good; I will definitely try that!

**Comment by mstewart141** [comment]
trusting worked!!! tyvm all. 

not at all your fault, but notebooks should at least make a good faith effort to surface to me, the end user, that there is additional content that was suppressed for security reasons: otherwise it appears as a silent failure!

**Comment by lyons7** [comment]
If anyone is here with a problem with bokeh and nteract after closing the notebook and having issues with a plot / map showing up inline, the suggestion from @canavandl to do:
```
from bokeh.plotting import output_notebook, figure, show

output_notebook(hide_banner=True)
```

totally worked ! **And** it also suppresses the annoying (imo) popping open of an html file in a separate browser window! 🎉 🎉 🎉
