### ISSUE TITLE
"CustomJS for Selections" Example in Docs Broken

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#8393]
In the latest version of the docs, it appears [this example]( https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-selections ) is broken. This is also true of the example in the Bokeh 1.0.0 docs. Selecting points in the plot on the left does not result in points being shown in the right plot. Compare this to [the same plot using Bokeh 0.13.0]( https://bokeh.pydata.org/en/0.13.0/docs/user_guide/interaction/callbacks.html#customjs-for-selections ), which seems to work without issues.

**Comment by jlcoto** [comment]
I think this is related to the LassoSelectTool. I was trying to use it for a project with version 1.0.1, however I saw that the `cb_obj.selected.indices;` was not returning anything at all. Furthermore, I suspect that the callback is not being executed when lasso select is used. In version 0.13.0 this does not appear to be a problem, as mentioned by @jakirkham.

**Comment by jakirkham** [comment]
It’s not limited to the lasso tool. Can get this with the tap tool as well.

**Comment by jlcoto** [comment]
Thank you very much, @philippjfr! I was not aware of the change starting bokeh 1.0. If no one beats me to it, I will submit a PR updating the docs in the coming days 😄.

**Comment by jakirkham** [comment]
Thanks @philippjfr. Should that code work with Bokeh 0.13.0 as well or only with 1.0.0+?

**Comment by philippjfr** [comment]
I think that code should work since bokeh 0.12.15.

**Comment by jakirkham** [comment]
Hmm...interesting...for some reason the callback doesn't seem to ever be called for me on Bokeh 0.13.0.

**Comment by philippjfr** [comment]
Odd, I'll try to track down what caused the change in 1.0.0.

**Comment by jakirkham** [comment]
Have another case that is similar to this example that runs the callback the first time, but then doesn't run it again. I'll try to put it together in some form that can be played with more easily and share it.

**Comment by jakirkham** [comment]
Thanks for pointing that out. Indeed it works fine with Bokeh 1.0.0+.

That should be fine for our needs. Just wanted to make sure there wasn't something else we need to change too. ;)

**Comment by jakirkham** [comment]
Also, for clarity, it appears the updated example works fine for Bokeh 1.0.0+. So there must be some other issues that were still present in 0.13.0 that caused the callback to not work.

**Comment by bryevdv** [comment]
Bokeh 0.13 had a unfortunatel regression around this, there is not much to do about it now except upgrade (or downgrade, I suppose). The version of above is correct for 1.0 and, more imporantly, is what is now maintained under new continuous integration tests. 

Can someone on this issue submit the small PR to update the example? The relevant file is here:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections.py
