### ISSUE TITLE
Legend shows wrong keys when key (str) is the same as input data in Figure.line

### ISSUE THREAD

**Issue by MelvinYin** [bokeh/bokeh#8394]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
python==3.6.6
bokeh==1.0.1
pandas==0.23.4

Ubuntu 18.04

#### Description of expected behavior and the observed behavior
For Figure.line, when legend parameter has the same string value as the x parameter, legend in the actual plot shows wrong values. Instead of the legend string, it shows actual values of the x data.

#### Complete, minimal, self-contained example code that reproduces the issue
Adapted from "Hiding Glyphs" section of "Interactive Legends" in bokeh documentation, here:
https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/legends.html#hiding-glyphs

```
import pandas as pd

from bokeh.palettes import Spectral4
from bokeh.plotting import figure, output_file, show
from bokeh.sampledata.stocks import AAPL, IBM, MSFT, GOOG
from bokeh.models import ColumnDataSource

p = figure(plot_width=800, plot_height=250, x_axis_type="datetime")
p.title.text = 'Click on legend entries to hide the corresponding lines'
![correct plot](https://user-images.githubusercontent.com/20134486/47952195-7f69b780-dfa6-11e8-9316-305db52dc1fb.png)
![plot with error](https://user-images.githubusercontent.com/20134486/47952196-842e6b80-dfa6-11e8-8562-ab533c731ac4.png)



for data, name, color in zip([AAPL, IBM, MSFT, GOOG], ["AAPL", "IBM", "MSFT", "GOOG"], Spectral4):
    df = pd.DataFrame(data)
    df['date'] = pd.to_datetime(df['date'])
    cds = ColumnDataSource.from_df(df)
    new_CDS = dict()
    for key, value in cds.items():
        if key == 'date':
            key = key + "_" + name
        new_CDS[key] = list(value)
    
    # To get original example plot
    # p.line('date_' + name, 'close', line_width=2, color=color, alpha=0.8,
    #        legend=name, source=new_CDS)

    # To get broken legend plot
    p.line('date_' + name, 'close', line_width=2, color=color, alpha=0.8,
           legend='date_' + name, source=new_CDS)

p.legend.location = "top_left"
p.legend.click_policy="hide"

output_file("interactive_legend.html", title="interactive_legend.py example")

show(p)

```

#### Screenshots or screencasts of the bug in action
![correct plot](https://user-images.githubusercontent.com/20134486/47952285-c60be180-dfa7-11e8-8234-b0b5abdc1ff6.png)
![plot with error](https://user-images.githubusercontent.com/20134486/47952286-c86e3b80-dfa7-11e8-8532-6e97b3147502.png)

**Comment by bryevdv** [comment]
@MelvinYin This is expected behaviour. The default action is to try and make "groupby" legends if your legend name matches a column name as it does here.  There has been some back and forth about whether that was a good default or not. It makes some complicated much simpler, but it also leaves this pitall. In any case the solution is to explicitly tell Bokeh that the legend is a value and not a CDS field:

```
from bokeh.core.properties import value
p.line('date_' + name, 'close', line_width=2, color=color, alpha=0.8,
           legend=value('date_' + name), source=new_CDS)
```

<img width="822" alt="screen shot 2019-02-18 at 18 59 43" src="https://user-images.githubusercontent.com/1078448/52987414-dfe30000-33af-11e9-914a-3001d88970c0.png">
