### ISSUE TITLE
Omit colon in hover tooltips if first tuple entry is empty

### ISSUE THREAD

**Issue by dnnr** [bokeh/bokeh#8399]
This is a suggestion for a very tiny improvement (but still...) of the presentation of HoverTool's tooltips.

Currently, something like this:
```
tooltips=[
    ('Date', '@date{%F}'),
    ('Balance', '@hours{(0.[00])} hours'),
    ('', '@days{0.[0]} days'),
],
```
...gets rendered like this:
![image](https://user-images.githubusercontent.com/2630359/48025830-c1306480-e144-11e8-98f5-ca5ad0f4980a.png)

I'm suggesting to remove the colon from the third row by omitting it whenever the first string in a tuple is empty.

It seems that for more sophisticated presentations, people are supposed to use custom tooltips. So there are probably no plans to add any complexity to the default tooltips.

However, I'd say this small adjustment makes the default behavior considerably more useful/powerful without making things worse for any use-case (...that I could think of).

**Comment by mattpap** [comment]
Sounds reasonable. Can you submit a PR?

**Comment by dnnr** [comment]
I intended to accompany this issue with a PR, but I failed trying to pretend-to-know-what-I'm-doing my way through the code far enough to figure out how to do it. And I don't know TypeScript, which appears to be necessary here.

That said, I'm happy to take a hint and give it a try. The general area of the responsible code would probably help.

**Comment by mattpap** [comment]
In:

https://github.com/bokeh/bokeh/blob/2dffa184f7e264f4d0c5a460fde20b9107eeb69c/bokehjs/src/lib/models/tools/inspectors/hover_tool.ts#L400

you will have to replace `"${label}: "`, with `label.length != 0 ? "${label}: " : ""`.
