### ISSUE TITLE
Box-Zoom on geomaps changes map ratio

### ISSUE THREAD

**Issue by iconberg** [bokeh/bokeh#8400]
Hi,

if i use the box zoom on maps, the maps is changing his ratio and get stretched or squezzed according to the zoombox ratio.

previous zoom box usage:

![ratio1](https://user-images.githubusercontent.com/8441455/48052099-549a8180-e1a7-11e8-95e7-eb7e97f0f1cb.png)

after zoom box usage (and zooming out with wheel tool, the ratio has already changed before wheel tool):

![ratio2](https://user-images.githubusercontent.com/8441455/48052109-5d8b5300-e1a7-11e8-9b4c-96e9815fac7a.png)

This is always happen if i use the zoom box, except i make a 1:1 zoom box.

**Comment by philippjfr** [comment]
When you add the BoxZoomTool to your plot simply ensure that you enable the match_aspect option:

```python
BoxZoomTool(match_aspect=True)
```

**Comment by bryevdv** [comment]
As @philippjfr notes, the solution is to set `match_aspect=True` There are plenty of cases where that behaviour  is not necessary or desirable, so it is not True by default.
