### ISSUE TITLE
Incorrect Image import from bokeh.models

### ISSUE THREAD

**Issue by ivan-usov** [bokeh/bokeh#8401]
The content of `bokeh/models/__init__.py` indicates the intention that all model classes should also be importable from `bokeh.models`. However, importing `Image` directly from `bokeh.models` brings into scope a class outside of `bokeh.models` package probably due to name collision with other indirect imports.
```
>>> from bokeh.models.glyphs import Image as I1
>>> from bokeh.models import Image as I2
>>> I1
<class 'bokeh.models.glyphs.Image'>
>>> I2
<class 'bokeh.core.property.visual.Image'>
```
I would expect either consistency of imports, or `bokeh.models` should not provide this interface at all, so that only the first line is a valid option.

bokeh/1.0.1 has this issue
bokeh/0.13.0 doesn't have this issue and correctly imports identical classes

**Comment by mattpap** [comment]
This is an unfortunate side effect of Python's import system by default. We are currently in the process of adding `__all__` to all modules (as a part of issue #8207), so this will be resolved eventually, though it may take a while, given the budget for resolving that issue. A PR is always welcome to resolve this particular instance.

**Comment by bryevdv** [comment]
cc @HuntJSparra let's try to take care of this in the next batch of work
