### ISSUE TITLE
Feature request: add support for setting the DataTable row height

### ISSUE THREAD

**Issue by dennisobrien** [bokeh/bokeh#8411]
The current implementation of `DataTable` does not allow the user to override the default row height (25px).  This has been requested a few times on in the google group ([here](https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/datatable$20row$20height|sort:date/bokeh/QLCbnzX1cFY/uWZUxDAEBAAJ) and [here](https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/datatable$20row$20height|sort:date/bokeh/ItFqOH3iRac/Pr2T58K2AgAJ)).  It doesn't seem to be solvable with custom CSS.  SlickGrid does expose `rowHeight` as a [grid option](https://github.com/6pac/SlickGrid/wiki/Grid-Options).

I'll make a PR to add this option.

**Comment by dennisobrien** [comment]
Just to provide a little more detail, I'm proposing to add an attribute `row_height` to the `DataTable` class.  The default value would be 25 (pixels) which matches the default in SlickGrid.

**Comment by jundl77** [comment]
any update to this? I think this is a nice idea
