### ISSUE TITLE
Add axis label formatters (sprintf-style, etc.)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#842]
This should be used to fix `population_server` example, so that it doesn't show negative numbers for males and perhaps use percentages instead of [0, 1]-normalized numbers.

**Comment by mattpap** [comment]
For `DataTable` number formatting I added `numeraljs` to dependencies. With some improvements (it doesn't support scientific notation), it could be used for axis label formatting.

**Comment by bryevdv** [comment]
lots of those `numeraljs` modes look useful, no scientific notation is an odd omission.
