### ISSUE TITLE
Apache documentation typo

### ISSUE THREAD

**Issue by jaroli** [bokeh/bokeh#8425]
I think there is a typo in the documentation about Apache reverse proxy:
https://bokeh.pydata.org/en/latest/docs/user_guide/server.html#apache

The loaded module should be:
`a2enmod proxy_http`
instead of
`a2enmod http_proxy`

**Comment by mattpap** [comment]
Seems to be a common mistake. Can you submit a PR fixing this?

**Comment by jaroli** [comment]
This is my first PR, hope it is OK.
