### ISSUE TITLE
Can't get gridplot to work in BokehJS.

### ISSUE THREAD

**Issue by heistermann** [bokeh/bokeh#8428]
I am trying to reproduce an example from the [Bokeh docs](https://bokeh.pydata.org/en/latest/docs/user_guide/bokehjs.html#bokeh-charts-pie) that uses `gridplot`.

```
var plt = Bokeh.Plotting;

var pie_data = {
    labels: ['Work', 'Eat', 'Commute', 'Sport', 'Watch TV', 'Sleep'],
    values: [8, 2, 2, 4, 0, 8],
};

var p1 = Bokeh.Charts.pie(pie_data);
var p2 = Bokeh.Charts.pie(pie_data, {
    inner_radius: 0.2,
    start_angle: Math.PI / 2
});
var p3 = Bokeh.Charts.pie(pie_data, {
    inner_radius: 0.2,
    start_angle: Math.PI / 6,
    end_angle: 5 * Math.PI / 6
});
var p4 = Bokeh.Charts.pie(pie_data, {
    inner_radius: 0.2,
    palette: "Oranges9",
    slice_labels: "percentages"
});

plt.show(plt.gridplot([p1, p2, p3, p4]));
``` 

Here is a [JSFiddle](https://jsfiddle.net/ujf98cqk/). `plt.show` with a single plot works, but shows a blank when using `plt.show(plt.gridplot([p1, p2, p3, p4]));`. Any ideas? I have been trying with `0.12.5` and `1.0.0`, but to no avail.

**Comment by mattpap** [comment]
Actually both versions don't fully work in jsfiddle. If you open up the JS console of your web browser, you will see that bokehjs' CSS files were blocked. Change the protocol (http -> https) of CSS resources in the fiddle, and plots should render fine.

**Comment by heistermann** [comment]
Thanks for the swift reply! I changed the URL/protocol of the CSS resources accordingly, but the problem persists (while the JS console does not report any error). 

Here is the updated fiddle: https://jsfiddle.net/ajvur6gf/

Should I post elsewhere? Since I used the exact same example as the Bokeh docs, I suspected this might be a kind of bug, so I thought I'd better raise an issue...

**Comment by mattpap** [comment]
> `plt.gridplot([p1, p2, p3, p4])`

This should be actually `plt.gridplot([[p1, p2, p3, p4]])`. `gridplot()` expects a nested list of plots. I wonder how the image in the documentation was generated. Would you mind sending a PR fixing the docs?

**Comment by heistermann** [comment]
You're right - making this a nested list fixes the issue. Thanks! Please see #8429.
