### ISSUE TITLE
Feature Request: Expose sort_columns in JS DataTable object

### ISSUE THREAD

**Issue by jgriffi6** [bokeh/bokeh#8444]
Hi,

I would like the ability to get the current sort columns and sortAsc of a DataTable within JS.  The motivation is that currently when I sort, then make a selection on another widget that triggers a call back that may result in a change in the ColumnDataSource, then the table is no longer sorted.  What I would like to be able to do, is to collect the sort columns in the callback that changes the data.  Then, I can have the server pre-sort the data and send it back to my application.  In this way the sort will essentially be preserved.  

I have downloaded the trunk, and made some changes in https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/widgets/tables/data_table.ts

[data_table.ts.txt](https://github.com/bokeh/bokeh/files/2590733/data_table.ts.txt)

I've added an array property to DataTable: sort_columns, which is updated in DataTableView.render() specifically this.grid.onSort.subscribe(...).

I think I would have preferred a dynamic function that returns the sortColumns, but could not figure out how to access the 'grid' object from within the DataTable object.

Thanks,
Justin

**Comment by bryevdv** [comment]
> I think I would have preferred a dynamic function that returns the sortColumns, but could not figure out how to access the 'grid' object from within the DataTable object.

It's' not going to be accessible, at least as things are currently. The grid belongs to the view, and models do not have forward references to any views. Agree however that a real model property is not a great solution, as it might seem as though it is user-settable, which is not the case. How about setting a private attribute on the model, and having a public getter (or method) that returns its value?

**Comment by jgriffi6** [comment]
Thanks @bryevdv for the suggestion.  I will submit a PR once I feel comfortable with the update (and hopefully others too once I get a better handle on js/ts!).

About the private suggestion, if I declare a private attribute to the model, then I still need a public setter so that the view, which has the grid, would be able to update the value.  So I think it is better than having a public model property, but there is then still a public method that one could assume they could call unless I am missing something?
[data_table.ts.diff.txt](https://github.com/bokeh/bokeh/files/2627522/data_table.ts.diff.txt)

Thanks,
Justin
