### ISSUE TITLE
SVG not displaying scatter output

### ISSUE THREAD

**Issue by cphalpert** [bokeh/bokeh#8446]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh: 1.0.1
IPython: 6.5.0

#### Description of expected behavior and the observed behavior
I expect the chart below to contain both navy and red circles. The red circles are displayed, but the navy circles created by the .scatter method do not appear.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, show
from bokeh.io.export import get_svgs
from IPython.display import SVG

p = figure(plot_width=400, plot_height=400)
p.scatter([-1, -2, -3, -4, -5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5, marker='circle')
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="red", alpha=0.5)
p.output_backend = 'svg'
# show the results
SVG(get_svgs(p)[0])
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/1086968/48685596-13ca4180-eb85-11e8-8d27-a17785a00e97.png)

**Comment by mattpap** [comment]
Seems to be a problem with all circle-type markers and `scatter()`:

![image](https://user-images.githubusercontent.com/27475/48703126-19f70700-ebf3-11e8-8beb-65adf1876fb0.png)

**Comment by mattpap** [comment]
There are errors in JS console:
```
canvas2svg.js:536 Attempted to apply path command to node g
(...)
```
(hidden when using `get_svgs()` or `export_svgs()`). This may indicate a bug in the underlying library canvas2svg. The unfortunate part is that this library isn't maintained anymore, so we may need to fork it and fix things on our own.

**Comment by kawairine** [comment]
Hi,

I also ran into this problem, and I was wondering if there is a quick solution to this? 

Thank you.

**Comment by bryevdv** [comment]
@kawairine I am afraid there is not. As mentioned above, Bokeh SVG output capability depends on a third party library and that library is no longer maintained at all. We will have to either re-do all of the SVG functionality, or find and integrate another new library that is maintained, or take ownership of the existing dependency. All of those are fairly heavy-lift tasks. I can't speculate when they might be gotten to with the current core team. We could really use help from new contributors to improve this situation faster.
