### ISSUE TITLE
Unable to load the HTML page

### ISSUE THREAD

**Issue by swat1234** [bokeh/bokeh#8447]
I have written a basic code as below.
 When i execute from Jupyter, it saves the html with a chart.
But when i execute with the bokeh serve --show app.py, it is showing a blank page

from bokeh.plotting import figure, output_file, show

p = figure()
p.circle([1, 2, 3], [4, 5, 6], color="orange")

output_file("foo.html")

show(p)

I got  exception **"Exception in onResRdy: TypeError: Cannot read property 'htmlRes' of undefined"**, when the page loaded
Can any one help me with this error

**Comment by jsignell** [comment]
That isn't a bokeh server setup. To just display your plot from the command line you can do:

```bash
python app.py
```

A browser tab should open with your plot in it. To setup a bokeh server app, you need to add the plot to the current document:

```python
from bokeh.plotting import figure, curdoc

p = figure()
p.circle([1, 2, 3], [4, 5, 6], color="orange")

curdoc().add_root(p)
```
 You can learn more about that [here](https://bokeh.pydata.org/en/latest/docs/user_guide/server.html).
