### ISSUE TITLE
fill_color argument in circle not working

### ISSUE THREAD

**Issue by julioasotodv** [bokeh/bokeh#8450]
Running `bokeh==1.0.1`

It looks like the fill_color argument for circle is not working anymore.

```python
from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers

colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'

p.circle(flowers["petal_length"], flowers["petal_width"],
             fill_color=colors, fill_alpha=1.0, size=10)

output_file("iris.html", title="iris.py example")

show(p)
```

Circles should have fill color, but they don't...

Am I just doing something wrong?

Thank you!

**Comment by julioasotodv** [comment]
Oh nevermind. It was just because the customer is using an ancient version of Firefox. My bad.

Sorry for the inconvenience!

**Comment by mattpap** [comment]
Obsolete web browser was my bet when seeing such a trivial feature failing.
