### ISSUE TITLE
API specification `server_session` broken by #7708

### ISSUE THREAD

**Issue by complyue** [bokeh/bokeh#8454]
https://github.com/bokeh/bokeh/pull/7708/files#r235605875

_Originally posted by @complyue in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDIzNTYwNTg3NQ==/comments/review_comment_

**Comment by bryevdv** [comment]
cc @mattpap AFAICT it's true we are definitely completely discarding `modelid` at this point.

**Comment by bryevdv** [comment]
This is actually a duplicate of https://github.com/bokeh/bokeh/issues/8499
