### ISSUE TITLE
Maps in Google Colab

### ISSUE THREAD

**Issue by RandomForestRanger** [bokeh/bokeh#8456]
I'm trying to display a gmap in google colab, and failing. Possibly due to inexperience. Here's what I did:

```
!pip install -q xlrd
!pip install bokeh

from bokeh.io import output_notebook 
from bokeh.io import output_file, show
from bokeh.models import ColumnDataSource, GMapOptions
from bokeh.plotting import gmap

output_notebook()

output_file("gmap1.html")
map_options = GMapOptions(lat=30.2861, lng=-97.7394, map_type="roadmap", zoom=11)

#     https://developers.google.com/maps/documentation/javascript/get-api-key
p = gmap("AI... <my API key> ", map_options, title="Austin")

source = ColumnDataSource(
    data=dict(lat=[ 30.29,  30.20,  30.29],
              lon=[-97.70, -97.74, -97.78]))
p.circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8, source=source)

show(p)
```

And I get crickets. Tumbleweed. Nothing. Output is blank. I'm sure the fault is mine, but am self-teaching to code, so at a loss. Any ideas, please?

**Comment by bryevdv** [comment]
I have never used Google Colab and I doubt any other core contributors have either. Is there any error output in the browsers JS console? Does your code function in "regular" jupyter notebooks?

**Comment by bryevdv** [comment]
@RandomForestRanger can you comment on the questions above? We will not be able to diagnose anything without more information.

**Comment by RandomForestRanger** [comment]
@bryevdv apologies. I have only ever coded used Colab - I'm a self-taught  noob. However, I've just downloaded Anaconda Navigator and used their jupyter notebook. Exact same code, and it works 100%... So it's something in Colab, I think.

**Comment by bryevdv** [comment]
Ok well, I doubt we will be able to do much about this, simply due to lack of resources. I am going to close this but certainly if anyone is a regular collab user and wants to work on this and contribute a solution we'd be happy to consider it.
