### ISSUE TITLE
embeds with json_item missing toolbar/interactivity

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8457]
Running this example:

https://github.com/bokeh/bokeh/blob/master/examples/embed/json_item.py

Will display plots, but the toolbars are missing, and none of the interactivity (e.g. panning which should be the active tool) responds either.

@mattpap have you seen this in any other situations, or do you have and ideas what might cause that? The embed goes through nearly the same code path, only a small wrapper around `Bokeh.embed._embed_items` There are no messages in the console log and nothing really jumps out. FWIW the toolbar button divs are present with the correct CSS classes but have 0 height. 

If you can identify a root cause I can take a closer look. This is a somewhat important priority, I have a prototype serverless-based "imgur for Bokeh plots" working, but it's not useful to deploy until this is resolved.

**Comment by mattpap** [comment]
`bk-root` is missing, thus CSS isn't applied. I need to investigate further to see if this is a problem with the example or a bug in the embed code.

**Comment by mattpap** [comment]
In the long term I want to make all principal (non-styling) CSS a part of bokehjs code (inline element styling). In fact PR #8085 goes a long way in this direction, assuming I ever finish it.

**Comment by bryevdv** [comment]
Ah, yes. Changing the div to this fixes:
```
  <div class="bk-root" id="bokeh_content"></div>
```
I guess the only question is whether that can/should happen automatically.

**Comment by mattpap** [comment]
> It seems like Bokeh.embed.embed_item could add this class to the div, is there any reason not to?

I'm not sure right now. I need to investigate embed code, because I don't remember what were the design requirements there (if any). In fact, I would like to remove `bk-root` altogether, because it seems to cause more problems than it solves.

**Comment by bryevdv** [comment]
>  I would like to remove bk-root altogether, because it seems to cause more problems than it solves.

I think in that case the best short-term solution is just to have `Bokeh.embed.embed` add the class, that way it's never exposed to users.
