### ISSUE TITLE
EOL for Python 2

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8463]
This issue is to discuss the timeline for dropping Python 2 support. The draft BEP is here:

https://github.com/bokeh/bokeh/wiki/BEP-5:-Python-2-Support-Timeline

Comments, edits, suggestions for additions or changes are welcome, including discussion of the substance of the proposal. 

cc @bokeh/core  @pzwang

**Comment by bryevdv** [comment]
Just to timebox things: Absent and objections or unresolved comments/dicussions, I will plan to close this issue and mark the BEP as accepted (and sign the Python 3 statement) on Friday December 7.

**Comment by mattpap** [comment]
> (...) and sets Python>=3.4 as the minimum supported Python version.

This is way too low in my opinion. I would consider 3.5 or even 3.6 as a more viable minimum version, because 3.5 adds e.g. `typing` module and 3.6 adds variable annotations. However, given that 3.8 is scheduled to be released for October 2019, I would even consider 3.7. These days there isn't much excuse for people for not upgrading their Python within the 3.x branch.

**Comment by bryevdv** [comment]
> These days there isn't much excuse for people for not upgrading their Python within the 3.x branch.

I think we have to be fairly conservative here. Many users are subject to bureaucratic constraints imposed by their work or organization. Python 3.3 was EOLed last year but I can't find anything stating a planned date for 3.4 EOL yet. It will be ~5 years old next year though. I would consider 3.5 as a minimum but I'd like to see:

* thoughts from several people about this
* information about whether many/any other PyData projects are moving to 3.5 min

**Comment by ivan-usov** [comment]
EOL of currently active python versions can be found on devguide:
https://devguide.python.org/#branchstatus

But all those planned EOL dates can still be adjusted (according to their statement "Dates in italic are scheduled and can be adjusted.")

From a project/library with a large user base one would normally expect a support for all currently active python branches.

**Comment by mattpap** [comment]
> https://devguide.python.org/#branchstatus

Based on this, the EOL for 3.4 is 2019-03-16 (I will take it as the final date; I expect extensions would be done reasonably early before such deadline, say half a year before). So we can safely increase the version to 3.5.

Besides EOL, every release has a status assigned. 3.4 and 3.5 currently have `security` status assigned, which means "only security fixes are accepted and no more binaries are released, but new source-only versions can be released". I would presume that users of such old Python versions shouldn't expect new versions libraries with new features and non-security related bugfixes. I don't see a point punishing majority of our users for a few, slowly adopting ones, unless my statistic is wrong and such users aren't a minority. So I would say that Python 3.6 is the minimum version we should support.

**Comment by bryevdv** [comment]
Python 3.5 is as low as I would want to consider, and only on the basis that 3.4 should be officially EOL by then.

**Comment by bryevdv** [comment]
@bokeh/dev reminder that I intend to execute this BEP on Friday absent any unresolved issues. Currently I think the only question (maybe?) is 3.4 or 3.5? Are there any strenuous objections using 3.5? It will be EOL by then and has already been dropped off Anaconda distributions.

**Comment by bryevdv** [comment]
I have made the issue to request Bokeh's inclusion: 
https://github.com/python3statement/python3statement.github.io/issues/161

**Comment by mscuthbert** [comment]
My sense is that Python 3.4 usage has dropped to quite insignificant levels.  When I dropped support for it for my project (music21) I heard nary a peep from users.  I think that three previous versions (3.7, 3.6, 3.5) is enough to support while still getting to take advantage of new paradigms.  Even if bokeh wants to support four versions, by the time of the release this would probably be 3.5–3.8.

**Comment by bryevdv** [comment]
@mscuthbert thanks for the useful information about your project. FYI I did update the BEP to state python 3.5 as I was marking it "Implemented". We can certainly leave some room to re-evaluate things at the time next year, but I expect the situation then will track your experience, and 3.5 with stay as the  most appropriate choice.
