### ISSUE TITLE
Enhancement Request: Option to Freeze left hand Columns

### ISSUE THREAD

**Issue by barrettjamesr** [bokeh/bokeh#8468]
Hi, I love the conditional formatting of Bokeh, but I noticed that it doesn't allow you to freeze the left hand columns for large tables that have horizontal scrolling.

My understanding is that Bokeh is similar to slick-grid, so I'd like to request something like this:
https://github.com/mleibman/SlickGrid/issues/208

This is different to being able to manually reorder columns as per (https://github.com/bokeh/bokeh/issues/6286). It would mean the first x columns would be frozen in place when scrolling left-right

Would that be possible?

**Comment by bryevdv** [comment]
There is in fact an existing issue and current ongoing discussion on the active fork:

https://github.com/6pac/SlickGrid/issues/26

If there is anything we can use, it will be there, but ideally this can just go directly in upstream.

**Comment by 6pac** [comment]
Hi All, yes this is in progress, but our bandwidth is also quite limited. The core grid appears to be stable, but all the plugins and add-on controls on are still being assessed. Watch this space.

**Comment by bryevdv** [comment]
@philippjfr this was done in 2.2?

**Comment by philippjfr** [comment]
This was indeed done, you can now freeze the first N columns by setting `frozen_columns=N`.
