### ISSUE TITLE
Crossfilter example in notebook not looking good

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#847]
I've been looking at running the crossfilter example in a notebook:
http://nbviewer.ipython.org/github/chdoig/my-tests/blob/master/crossfilter.ipynb

And looks something like this:
![screen shot 2014-07-15 at 5 03 40 pm](https://cloud.githubusercontent.com/assets/4940549/3592470/59b58d72-0c72-11e4-9674-e0107cd75af9.png)

I've been able to eliminate the double scrolling bar...
![screen shot 2014-07-15 at 5 05 11 pm](https://cloud.githubusercontent.com/assets/4940549/3592483/aaeb99a2-0c72-11e4-8af3-feceb13ee528.png)

by removing `<table>`, `<tbody>`, `<tr>` and `<td>` containing the panels and plots (I don't think we need a table for layout, we can just use CSS properties): 
![screen shot 2014-07-15 at 5 53 09 pm](https://cloud.githubusercontent.com/assets/4940549/3592497/e4b8667e-0c72-11e4-87a1-0447c39c034a.png)

The next problem to make it similar to the one displayed in the server: 
![screen shot 2014-07-15 at 5 58 56 pm](https://cloud.githubusercontent.com/assets/4940549/3592533/a14abeae-0c73-11e4-9530-5b694d5c6d62.png)

is that in the notebook the classes col-md-X don't exist, so it doesn't inherit those properties...:
![screen shot 2014-07-15 at 4 54 33 pm](https://cloud.githubusercontent.com/assets/4940549/3592538/c0c583a4-0c73-11e4-9115-cd3c6303c489.png)

...because the ipython notebook doesn't have `bootstrap.css` but one called `bootstrap-tour.css` which doesn't contain the `col-md-X` classes that we are using.
![screen shot 2014-07-15 at 4 55 31 pm](https://cloud.githubusercontent.com/assets/4940549/3592554/e7f6359a-0c73-11e4-8337-40b57d8538dd.png)

Ideas:
-Add classes in out bokeh.css file?
-JS script to append the bootstrap.css file to overwrite the bootstrap-tour.css?
-Check why the IPython notebook doesn't use bootstrap, some incompatibilities between classes?

**Comment by birdsarah** [comment]
@chdoig i'm wondering whether we can close this. here's a screenshot from me running your code on 0.9.1. I don't know when it got fixed, but it looks fixed. 

![847 on bokeh 091](https://cloud.githubusercontent.com/assets/1796208/8562299/0d937296-2531-11e5-879f-363d6d7b8597.png)

**Comment by damianavila** [comment]
Seem OK to me, let's get this closed. @chdoig if you see something wrong, let us know...
