### ISSUE TITLE
Updating css_classes on layout elements has no effect

### ISSUE THREAD

**Issue by jtanx** [bokeh/bokeh#8471]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 1.0.1

#### Description of expected behavior and the observed behavior
Updating `css_classes` on any layout element (tested on row/column/widgetbox) has no effect - even though setting `css_classes` as part of the initial creation works

#### Complete, minimal, self-contained example code that reproduces the issue

```py
from bokeh.models.widgets import Button
from bokeh.layouts import row

b = Button(label='click')
# The row will have the css class 'a'
r = row(b, css_classes=['a'])

# The row will never get the css class 'b'
b.on_click(lambda: r.css_classes.append('b'))

curdoc().add_root(r)
```

**Comment by bryevdv** [comment]
possibly related to https://github.com/bokeh/bokeh/issues/8290 tho it looks like a specific cause was identified for tables in that issue.
