### ISSUE TITLE
Latest for Developer Guide Documentation is 1.0.1

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#8473]
The bokeh.pydata.org documentation's Developer Guide section links to the 1.0.1 version instead of 1.0.2.

From https://bokeh.pydata.org/en/latest/docs/dev_guide.html on Safari:
![screen shot 2018-11-29 at 9 21 30 pm](https://user-images.githubusercontent.com/19802403/49264663-2f530900-f41d-11e8-801e-9422e03b7f7d.png)

Manually typing in https://bokeh.pydata.org/en/1.0.2/docs/dev_guide.html does direct to the correct page.

**Comment by bryevdv** [comment]
unfortunately sometimes it's necessary to do a force-reload (e.g. apple-r) to make the page update. Maybe theres something we could do different or better but I've never been able to figure anything out.
