### ISSUE TITLE
Plot y-axis label blurry on windows 10

### ISSUE THREAD

**Issue by anthonydouc** [bokeh/bokeh#8478]
Not sure if there is a current open issue capturing this, but on windows 10 the the y-axis labels are particularly distorted. It looks like it is somewhat zoomed out, so when zooming in at 200-250% it looks alot closer to how it does on osx. 

The same thing occurs across google chome and firefox. Edge is actually a bit better.

Mac osx (google chrome)
<img width="612" alt="iris_mac" src="https://user-images.githubusercontent.com/11044560/49335670-21cc9780-f646-11e8-981e-e8ef05d7d0ed.png">

Windows 10 chrome (100% zoom)
![iris_win10_100](https://user-images.githubusercontent.com/11044560/49335679-60625200-f646-11e8-8431-0c1f2e02f114.png)

Windows 10 chrome (200% zoom)
![iris_win10_200](https://user-images.githubusercontent.com/11044560/49335686-88ea4c00-f646-11e8-8e22-5305e8e4994e.png)

**Comment by mattpap** [comment]
Can you try out different fonts (we use helvetica by default) and see if the problem persists (set `axis_label_text_font` property)? We don't have reliable access to windows (especially 10) machines, so it may take a while for us to get to this issue.

**Comment by anthonydouc** [comment]
Google chrome, with times new roman (zoom at 100%):
![bokeh_plot 29](https://user-images.githubusercontent.com/11044560/49676405-bc592a80-facd-11e8-9ea4-10f5c089d09b.png)

Google chrome, with times new roman  (zoom in to 200%):
![bokeh_plot 30](https://user-images.githubusercontent.com/11044560/49676437-d4c94500-facd-11e8-80fc-24c756586fc4.png)

Edge, with times new roman (zoom at 100%):
![bokeh_plot](https://user-images.githubusercontent.com/11044560/49676587-69cc3e00-face-11e8-9728-4157d77041a3.png)

**Comment by xavArtley** [comment]
Windows 10 chrome:
I don't notice a real blur problem at any zoom level :
![image](https://user-images.githubusercontent.com/18531147/54155175-df380980-4443-11e9-8875-cec32a7c7afe.png)

![image](https://user-images.githubusercontent.com/18531147/54155262-0bec2100-4444-11e9-9752-c8361e865599.png)

![image](https://user-images.githubusercontent.com/18531147/54155364-43f36400-4444-11e9-944b-e3348a4de264.png)

**Comment by anthonydouc** [comment]
> Windows 10 chrome:
> I don't notice a real blur problem at any zoom level :
> ![image](https://user-images.githubusercontent.com/18531147/54155175-df380980-4443-11e9-8875-cec32a7c7afe.png)
> 
> ![image](https://user-images.githubusercontent.com/18531147/54155262-0bec2100-4444-11e9-9752-c8361e865599.png)
> 
> ![image](https://user-images.githubusercontent.com/18531147/54155364-43f36400-4444-11e9-944b-e3348a4de264.png)

Which version of bokeh are you using

**Comment by xavArtley** [comment]
1.1.0devx

**Comment by anthonydouc** [comment]
It still looks blury to me. Even in the images you sent through at 100% zoom the text looks distorted - when you zoom further in it looks improved. I suspect it would be associated with a canvas drawing issue

**Comment by mattpap** [comment]
> I suspect it would be associated with a canvas drawing issue

Most likely that's the case and there may be nothing we can do about it in general. However, it would be good to know what advice to give users in future. @anthonydouc, can you try using non-italic or unstyled font, or a different font altogether for the vertical axis? Maybe there is a combination that works more reasonably.

**Comment by mattpap** [comment]
Actually, I already asked earlier for a different font, so lets focus on styling this time.

**Comment by jxramos** [comment]
@anthonydouc  I'm interested in the context of the blurriness. Is it something you're finding directly in the browser? Are these images you present generated by the save button floppy disk icon on the bokeh toolbar? Are these screenshots?
When I download the images as served by gitHub here I actually find different resolutions, the Mac version being twice as large...

```
Mac osx (google chrome):        Width 1224, Height 1188, Bit depth 32 
Windows 10 chrome (100% zoom):  Width 618 , Height 599 , Bit depth 32 
```

**Comment by bryevdv** [comment]
>  the Mac version being twice as large...

That's a function of the retina display and the corresponding different device pixel ratio on the mac

**Comment by anthonydouc** [comment]
> @anthonydouc I'm interested in the context of the blurriness. Is it something you're finding directly in the browser? Are these images you present generated by the save button floppy disk icon on the bokeh toolbar? Are these screenshots?
> When I download the images as served by gitHub here I actually find different resolutions, the Mac version being twice as large...
> 
> ```
> Mac osx (google chrome):        Width 1224, Height 1188, Bit depth 32 
> Windows 10 chrome (100% zoom):  Width 618 , Height 599 , Bit depth 32 
> ```

Sorry have not had time to look further into this. 
Although the images attached are screenshots, they are observed directly in the browser.

But perhaps those issues are related? When you zoom in at 200% it seems to not be blurry.

**Comment by bryevdv** [comment]
Have not looked at this article in detail but it does claim that the approach we have taken is "outdated" and presents an alternative method for dealing with a blurry canvas. Possibly worth investigating when time permits

https://medium.com/wdstack/fixing-html5-2d-canvas-blur-8ebe27db07da

**Comment by mattpap** [comment]
This article doesn't bring anything new to the picture. We use the same HiDPI approach as everyone else. If this was a problem with pixel density, we would see other artifacts as well. I observed this problem before in phantomjs, which leads me to conclusion that this may be just an issue with an outdated browser. Unfortunately we didn't ask for the version of chrome being used. Then there's a possibility that there was a regression in chrome at some point affecting font rendering on this particular platform.

**Comment by anthonydouc** [comment]
> This article doesn't bring anything new to the picture. We use the same HiDPI approach as everyone else. If this was a problem with pixel density, we would see other artifacts as well. I observed this problem before in phantomjs, which leads me to conclusion that this may be just an issue with an outdated browser. Unfortunately we didn't ask for the version of chrome being used. Then there's a possibility that there was a regression in chrome at some point affecting font rendering on this particular platform.

Happy to check to see if the same problems occur and provide a chrome version if that is helpful.

**Comment by mattpap** [comment]
Actually, we still use `backingStorePixelRatio`. I must have removed this in PR that got stalled. Though I doubt this affects anything. I will submit a PR and we will see if this changes anything.

**Comment by bryevdv** [comment]
I will have an rc1 out this weekend with the change. I'd say it would be good to test with it @anthonydouc but fair warning we are probably just going to have to close this issue regardless as there is just not anything else I think we could do or change.

**Comment by bryevdv** [comment]
Absent any feedback/further information, I am closing this as stale
