### ISSUE TITLE
Example bokeh app 'export_csv' does not work on Safari

### ISSUE THREAD

**Issue by GenevieveBuckley** [bokeh/bokeh#8480]
Example bokeh app 'export_csv' does not work on Safari. 

As discussed here: https://github.com/bokeh/bokeh/pull/8381#issuecomment-434561611 When you launch the example in Safari and click the 'Download' button you get an error message that says "Safari can't open the page" instead of the expected download of a csv file.

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
MacOS Mojave
Safari Version 12.0.1 (14606.2.104.1.1)
bokeh version 1.0.1
 
#### Description of expected behavior and the observed behavior
Expected behaviour: When you click the 'Download' button, a csv file with the selected data should be downloaded.
Observed behaviour: When you click the 'Download' button you get an error message that says "Safari can't open the page".

#### Complete, minimal, self-contained example code that reproduces the issue

```
$ git clone https://github.com/bokeh/bokeh.git
$ cd bokeh/examples/app/export_csv
$ bokeh serve main.py
```
Then open http://localhost:5000/main in Safari and click the 'Download' button.

#### Stack traceback and/or browser JavaScript console output
No stack traceback observed.

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/30920819/49487631-71ee6880-f897-11e8-91ca-47db32a4644c.png)

**Comment by bryevdv** [comment]
This just worked for me on Safari Version 12.1 (14607.1.40.1.4) Realistically, all we are going to be able to do is document the version that works and suggest people upgrade to that version or newer. Eventually the problem will decline on its own.

**Comment by bryevdv** [comment]
worked, I should add, with 1.1rc3
