### ISSUE TITLE
Plot with tight axes and matching aspect ratio

### ISSUE THREAD

**Issue by mcrot** [bokeh/bokeh#8486]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 1.0.1 (installed via pip)
python: Python 3.7.0 (default, Jun 28 2018, 13:15:42), via miniconda
OS: Ubuntu 18.04.1 LTS
Browser: Firefox 63.0.3 (64 bit)

#### Description of expected behavior and the observed behavior

I would like to have a plot with 
- axes and data ranges limited to given bounds (initially and while zooming)
- a square on screen should match a square in data space (matching aspect ratio)

So far I cannot manage to have both. I'm using the `match_aspect=True` switch when creating the figure. When using `start` and `end` when initializing the data ranges, the aspect ratio on screen doesn't match to the aspect ratio in data space. When leaving out `start` and `end` arguments, the data ranges shown are much larger than the given bounds.

##### Case A (using `start` and `end`) 

```
from bokeh.models.ranges import DataRange1d
from bokeh.plotting import figure, show

sx = 10
sy = 5
x_range = DataRange1d(start=0, end=sx, bounds=(0,sx))
y_range = DataRange1d(start=0, end=sy, bounds=(0,sy))
plot = figure(x_range=x_range, y_range=y_range, match_aspect=True)
plot.rect(x=[0,sx,sx,0,sx/2], y=[0,0,sy,sy,sy/2],
          height=1, width=1) # plots a square at each corner and in the middle
show(plot)
```

In the results, the axes bounds are correct, but the aspect ratio doesn't match, since the square in the middle doesn't look like a square:

![correct_bounds_but_no_square](https://user-images.githubusercontent.com/9113541/49601801-1b605780-f987-11e8-93e4-99ab46ebeab9.png)

##### Case B (not using `start` and `end`)

Same code as above, but
```
x_range = DataRange1d(bounds=(0,sx))
y_range = DataRange1d(bounds=(0,sy))
```
Here there is a square, but the bounds are too large, e.g. the `y` range goes up to more than 8:
![square_but_wrong_bounds](https://user-images.githubusercontent.com/9113541/49601859-464aab80-f987-11e8-8bce-3fc8fa2fe58b.png)

*Additionally, the wheel zoom tool doesn't work. It works in Case A.* 

I've also tried to use `range_padding` when initializing the ranges without success.

Another idea I had was to set `plot_width` and `plot_height` accordingly to the data
space, but this doesn't work in general because in my real-life example I also have other
elements like colorbar or axes in the plot which widths I don't know beforehand.

#### Stack traceback and/or browser JavaScript console output

No traceback, Javascript output:
```
[bokeh] setting log level to: 'info' bokeh-1.0.1.min.js:31:38198
[bokeh] document idle at 104 ms bokeh-1.0.1.min.js:31:101288
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://cdn.pydata.org/bokeh/release/bokeh-1.0.1.min.js
Source-Map-Adresse: bokeh.min.js.map[Weitere Informationen]
```
(I don't think this is relevant)

**Comment by bryevdv** [comment]
@mcrot the bounds are not too large, the bounds are adjusted specifically to make things that are square in data space, be square in pixels too. Without all that extra space at the top and bottom, you just get the first image (where the rects are not square in pixels)

It sounds like you have a situation where your data is is much "wider" than it is "tall"? If that's the case, and you also want matched aspect there are only two possbilities:

* put up with the extra space needed to match the aspect ratio in a roughly square canvas
* also make your canvas much wider than it is tall, so that aspect can be match with smaller range adjustments.

**Comment by mcrot** [comment]
@bryevdv thanks again, I understand why it has to be like this. I'll discuss both possibilities with my colleagues for our use case. 

If we decide to put up with the extra space, it would be nice to have the wheel zoom which doesn't work for me in case B. Can someone reproduce this? Should I open a new issue on that?

**Comment by bryevdv** [comment]
@mcrot let's keep issues distinct. If wheel zoom is not working with match aspect please open a new issue with a small script to reproduce.

**Comment by mcrot** [comment]
Ok, thanks, sorry for reopening this, I didn't expect that would happen because of my extra comment.

**Comment by bryevdv** [comment]
It didn't re-open AFAICT (no worries either way)

**Comment by mcrot** [comment]
:smile: 

Just for reference, I've opened #8487 because of the wheel zoom in this special case.
