### ISSUE TITLE
Tooltip '$name' not working with tuple-style definition

### ISSUE THREAD

**Issue by jnettels** [bokeh/bokeh#8488]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 1.0.2
Python 3.7
Windows 10
Edge, Firefox, Chrome

#### Description of expected behavior and the observed behavior

A short while ago, the shortcut ``tooltips='$name: @$name'`` was introduced to allow an easier definition of tooltips for multiple elements:
https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html#hover-tools

- ``HoverTool(tooltips)`` expects an element of either String or List(Tuple(String, String)).
- The ``$name`` special variable in the example uses the string method.
-  It does not work properly using the tuple-style definition. With ``tooltips=[('$name', '@$name')]`` the ``'@$name'`` looks up the numeric value properly, but ``'$name'`` shows the string  ``$name`` in the tooltip, instead of the column headers ``foo`` and ``bar``
- Therefore I do not see a way to combine the ``'$name'`` lookup with additional information, e.g. for the x-axis

#### Complete, minimal, self-contained example code that reproduces the issue

```
# -*- coding: utf-8 -*-
import pandas as pd
from bokeh.plotting import figure, show
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.layouts import row

x_col = 'TIME'
df = pd.DataFrame(
        index=pd.DatetimeIndex(data=['2019-02-14 05:00:00',
                                     '2019-02-14 06:00:00',
                                     '2019-02-14 07:00:00',
                                     ],
                               name=x_col),

        data={'foo': [90.13185525,
                      90.87019377,
                      91.50974425,
                      ],
              'bar': [60]*3,
              })

print(df)

p1 = figure(x_axis_type='datetime', output_backend='webgl',
           active_scroll='wheel_zoom', title='$name is fine')
p2 = figure(x_axis_type='datetime', x_range=p1.x_range, y_range=p1.y_range,
            active_scroll='wheel_zoom', title='$name not working')

source = ColumnDataSource(data=df)
for y_col in df.columns:
    p1.line(x_col, y_col, legend=y_col+' ', source=source, name=y_col)
    p2.line(x_col, y_col, legend=y_col+' ', source=source, name=y_col)

hover1 = HoverTool(tooltips='$name: @$name')
hover2 = HoverTool(tooltips=[('$name', '@$name'),  # '$name' seems bugged
                             (x_col, ' @{'+x_col+'}{%y-%m-%d %H:%M:%S}')],
                   formatters={'TIME': 'datetime'})
p1.add_tools(hover1)
p2.add_tools(hover2)

show(row(p1, p2))

```

**Comment by bryevdv** [comment]
@jnettels The first value of the tuple format has only ever been intended or interpreted as a plain string label to be displayed, exactly as given. I would thus regard this behavior as expected. Offhand I would say if you need something beyond that, that is what hover tool templates are for, e.g. 

https://bokeh.pydata.org/en/1.0.2/docs/gallery/bar_stacked.html
https://bokeh.pydata.org/en/1.0.2/docs/user_guide/tools.html#custom-tooltip

I suppose it's possible we could allow substitutions in the label field, but I am lukewarm on that idea, at best. 

cc @mattpap

**Comment by jnettels** [comment]
Thanks for the clarification. This does of course make sense and I would accept this being the intended behaviour. I just hope you see where my expectation came from - others might make the same mistake.

The following is how I usually solve this specific problem (Creating a hover with the y-value of the current line and the x-value). However, it leads to issue #5497 because I have to create a new hovertool for each line in my plot.

```python
# -*- coding: utf-8 -*-
import pandas as pd
from bokeh.plotting import figure, show
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.layouts import row

x_col = 'TIME'
df = pd.DataFrame(
        index=pd.DatetimeIndex(data=['2019-02-14 05:00:00',
                                     '2019-02-14 06:00:00',
                                     '2019-02-14 07:00:00', ],
                               name=x_col),
        data={'foo': [90.13, 90.87, 91.50, ],
              'bar': [60, 61, 62], })
print(df)


p1 = figure(x_axis_type='datetime', output_backend='webgl',
            active_scroll='wheel_zoom', title='Using $name')
p2 = figure(x_axis_type='datetime', x_range=p1.x_range, y_range=p1.y_range,
            active_scroll='wheel_zoom', title='Standard solution')

source = ColumnDataSource(data=df)

r2_list = []
for y_col in df.columns:
    p1.line(x_col, y_col, legend=y_col+' ', source=source, name=y_col)
    r2 = p2.line(x_col, y_col, legend=y_col+' ', source=source, name=y_col)
    r2_list.append(r2)

hover1 = HoverTool(tooltips='$name: @$name')
p1.add_tools(hover1)

for r in r2_list:  # Add one HoverTool for each renderer in figure p2
    label = r.name  # Use the name we stored earlier for the label
    # Create a hover with the y-value of the current line and the x-value
    hover = HoverTool(tooltips=[(label, "@{"+label+"}"),
                                (x_col, ' @{'+x_col+'}{%y-%m-%d %H:%M:%S}')],
                      formatters={'TIME': 'datetime'},
                      renderers=[r])
    p2.add_tools(hover)

show(row(p1, p2))
```

The above may serve as an example for anyone with the same problem.

-------------
Steering away from the bug report, in the direction of a support question (which I do not expect to be answered here on GitHub, but I will ask anyway):
Is there a more elegant solution that does not create multiple hover tool icons?

**Comment by bryevdv** [comment]
> Is there a more elegant solution that does not create multiple hover tool icons

Unfortunately not yet. That capability existed a long time ago, but it was lost in a large refactor, and has yet to be restored.

**Comment by bryevdv** [comment]
not sure why this was left open
