### ISSUE TITLE
Document Licenses of included projects

### ISSUE THREAD

**Issue by dwt** [bokeh/bokeh#8495]
We're trying to be diligent about (checking/) showing all the licenses of the dependencies we use in our project, and to this end, it proves rather difficult to extract the licenses of the bundled js dependencies that bokeh ships.

To my understanding it is not enough to show for bokeh, that it is just under the new BSD-Clause, as all the bundled dependencies licenses would also need to be shown (as we are in effect using them too).

My workaround for now is to manually install bokeh from source, build BokehJS and then inspect the built up NPM-repo for all the installed tools, it would be much better however if the Bokeh-project has an always up to date document (on the website or in the repository) that lists all the licenses that it contains - bonus points if it's a plaintext file.

What do you think? Can you provide such a document?

**Comment by dwt** [comment]
Ideally, the License file of [BokehJS](https://github.com/bokeh/bokeh/blob/master/bokehjs/LICENSE) should include all the licenses of the bundled projects. I.e. something along the lines:

Parts of BokehJS are goverened by these licenses: ...

Some examples of what I mean:
* https://github.com/numpy/numpy/blob/master/LICENSE.txt
* https://github.com/kwgoodman/bottleneck/blob/master/bottleneck/LICENSE

I can provide more if necessary - but I believe that this is at least very much something one should do, if not actually a requirement, as you get all those licenses and their obligations if you include bokeh in your project.

**Comment by dwt** [comment]
To expand some more, it is really not easy to be sure what code you are actually vendoring, especially in any automated fashion if one just starts from the built bokeh wheel or sdist. So the aim would be to make it possible for integrators to correctly quote the licenses and copyrights that come along when using bokeh in a project.

**Comment by bryevdv** [comment]
Hi @dwt 

Thanks for raising the issue. It's unclear to me how the runtime boundary intersects with license requirements. There has been much debate , e.g., about around how linking of binary executables and libraries intersect with license requirements, and I view this as at least analogous. The examples you cite all involve vendoring of python packages in other python packages, all of which is directly used by the immediate installing user. But this situation is different in that, while Bokeh distributes JS libraries, the ultimate user of the code is not (necessarily) whoever installed Bokeh, but rather it is whoever loads a page containing the JS code that "uses" it. Bokeh (and the immediate user of Bokeh) are not directly executing the JS code, they are producing artifacts that distribute the JS code. The user of that code is the viewer of the result, whoever that might be. 

So, at the moment, things I feel confident stating:

* we certainly need the right to *distribute* the JS code with the package. I believe this right is implicit in the fact that the JS package authors have *themselves* published their package to NPM, a site whose sole purpose is to (re-)distribute such software that package authors voluntarily publish to NPM. 

* we are obliged to include JS package license in any bundled JS that we in turn distribute, and we do ensure that we meet this obligation, including for all minified JS bundles.  

It's unclear to me that there is any further obligation for us to discharge. Before embarking on a course of action involving real work, ideally I would like to see an actual legal opinion from an actual lawyer about this specific scenario of non-JS together with JS distribution. Failing that, I would be interested to see other of how other projects in the real world handle this. Can you point to any examples that specifically handle this same situation?

In any case, it's worth explicitly examining things that could be done, even if it is not clear whether they are obliged to be done:

* Add a blank statement to the LICENSE file that makes clear that Bokeh produces output that includes vendored JS code and that the licenses for those projects is included direction in the BokehJS files. 

* Publish instructions in the dev docs to easily see the licenses for vendored JS code in a particular release. [Following this article](https://medium.com/@fokusman/the-easiest-way-to-check-all-your-npm-dependency-licenses-753075ef1d9d) the steps are roughly:
  - clone Bokeh repo, then `git checkout <relesase tag>`
  - `cd bokehjs`, then `npm i -g license-checker`
  - run `license-checker --exclude 'MIT, MIT OR X11, BSD' --production --summary`
  
* Automate the above process in the build/release process somehow. 

At present, my own bandwidth for Bokeh work has been reduced, at least for some time going forward. I'd be happy to consider PRs for any or all of the above tasks, as well as help provide help/guidance, if you are interested in helping contribute to the project.

FWIW, as of current master (~1.0.2) the results of the above steps are:

```
(base) ❯ license-checker --exclude 'MIT, MIT OR X11, BSD, ISC, UNLICENSE' --production --summary
├─ Apache-2.0: 6
├─ WTFPL: 1
└─ Unlicense: 1
```

cc @bokeh/core additional opinions would be welcome here

**Comment by bryevdv** [comment]
A fourth option would be to add a CI test that executes those steps and fails if they change, so that new licenses are not accidentally added without consideration. Then LICENSE could be update with a static list of the current license types, which would be valid as long as the test continues to pass.

**Comment by dwt** [comment]
Sorry I had so little time to respond to this. I really like what you have provided in the pull request. In an ideal world I would also like to have the concrete projects listed in the license, but hey.... :-)
