### ISSUE TITLE
"WARNING:bokeh.resources:root_url should end with a /, adding one" spam

### ISSUE THREAD

**Issue by gotyaoi** [bokeh/bokeh#8496]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 1.0.2
python 3.6.5
OS CentOS-7.5.1804

#### Description of expected behavior and the observed behavior

After adding the "prefix" parameter to a bokeh.server.server.Server, the logs get "WARNING:bokeh.resources:root_url should end with a /, adding one" on autoload.js requests.

I think this is because in tornado.py it normalizes the prefix to have a slash only at the beginning:

https://github.com/bokeh/bokeh/blob/master/bokeh/server/tornado.py#L161-L165

then uses this prefix value when initializing the Resources object:

https://github.com/bokeh/bokeh/blob/master/bokeh/server/tornado.py#L377-L379

and then the Resources object complains about the lack of slash at the end:

https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L89-L91

#### Complete, minimal, self-contained example code that reproduces the issue

N/A

#### Stack traceback and/or browser JavaScript console output

N/A

#### Screenshots or screencasts of the bug in action

N/A

**Comment by gotyaoi** [comment]
also, the slash at the beginning of the prefix doubles up with the slash at the end of the root_url, added here:

https://github.com/bokeh/bokeh/blob/master/bokeh/server/views/autoload_js_handler.py#L34-L40

producing a double slash in static urls here:

https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L502

**Comment by bryevdv** [comment]
Ugh. The totality of these codepaths was made by different people and there is pretty inconsistent handling of expectations of URL formats throughout. I'm tempted to just disable this warning for now, and save a thorough review of URL handling for later.
