### ISSUE TITLE
Clarify how axes can be labelled

### ISSUE THREAD

**Issue by NTAWolf** [bokeh/bokeh#850]
I.e. explicitly state that x_axis_label exists :-)

It is hard to find out how to put labels on the axes (use x_axis_label='my label' in the figure or plot call), as it does not appear in any of the examples on the [front page of Bokeh's website](http://bokeh.pydata.org/index.html), nor in the [documentation](http://bokeh.pydata.org/docs/reference.html). I didn't find it in [the tutorials](http://bokeh.pydata.org/tutorial/index.html) either.
I found out through [Twitter](https://twitter.com/BokehPlots) (!), where there was a link to [an example](http://nbviewer.ipython.org/github/kdodia/examples/blob/master/world_cup_scoring.ipynb) that uses axis labels.

Perhaps a solution could be to simply list "all plot style keyword parameters" (mentioned in [the docs](http://bokeh.pydata.org/docs/reference.html) under `bokeh.plotting.figure()`) in the documentation?

**Comment by damianavila** [comment]
Doc reference is done. We still need to update examples in the tutorial (and maybe more generally) to use labels (plots w/o labels is not a good practice to have).

**Comment by birdsarah** [comment]
I was also struggling to change font of axes through charts interface, documenting that would be great.

**Comment by bryevdv** [comment]
addressed in #2257

**Comment by damianavila** [comment]
OK, let's get close it...
