### ISSUE TITLE
Support environment variable in addition to --allow-websocket-origin

### ISSUE THREAD

**Issue by kuuji** [bokeh/bokeh#8502]
Hey folks! 

This is more of a feature request

I'm running bokeh in docker in multiple environment and being able to specify an environment variable `BOKEH_ALLOWED_WS_ORIGIN` with a list of domains instead of using `--allow-websocket-origin` would make my life easier. 

Docker does not support environment variables in `CMD` and that would force me to write a small wrapper script to run bokeh, which is not ideal.

I can work on a PR if you think that's something worth supporting. I wanted to get your opinions on this first.

**Comment by bryevdv** [comment]
@kuuji I'd be happy to have a PR that adds that, my only comment is that it should go through the existing [`bokeh.settings` machinery](https://github.com/bokeh/bokeh/blob/master/bokeh/settings.py) and that ideally it would always return a list (so probably add a new `_get_list` that splits on whitespace or whatever separator you decide on)

**Comment by kuuji** [comment]
Will do. Thanks for the advice @bryevdv
