### ISSUE TITLE
Bokeh cannot import PointDrawTool

### ISSUE THREAD

**Issue by tusharriat** [bokeh/bokeh#8511]
Hello,

I have the following configurations in my computer:
 Python 3.6.3 :: Anaconda, Inc.
 Windows 7 Professional, Version 6.1 (SP1)
 Bokeh: 0.12.9

I get the following error when I try to import the PointDrawTool from bokeh.models import PointDrawTool:

from bokeh.models import PointDrawTool
 Traceback (most recent call last):

File "", line 1, in 
 from bokeh.models import PointDrawTool

ImportError: cannot import name 'PointDrawTool'

How should I resolve it?

**Comment by mattpap** [comment]
> Bokeh: 0.12.9

You need to install appropriate version of bokeh that supports this functionality (at least 0.12.14, preferably the most recent version 1.0.2).
