### ISSUE TITLE
Strip out IPython magics when serving notebooks

### ISSUE THREAD

**Issue by jlstevens** [bokeh/bokeh#8513]
When nbconvert is used in `NotebookHandler` to convert notebooks into vanilla Python code ( supporting `bokeh serve notebook.ipynb`) any IPython magics are converted into a call involving `get_ipython` which is then undefined and causes a failure.

This means that any notebook using one of the common magics such as `%time` or `%%timeit` cannot be served with bokeh server. Supporting magics in bokeh server probably isn't technically possible (and typically wouldn't even make much sense) so it would probably be better to strip them out with an nbconvert preprocessor to allow the notebook to be served in some form (instead of always resulting in an error).

**Comment by jbednar** [comment]
This functionality would be really useful to me when writing serveable notebooks.  It might be helpful to print a warning message saying that IPython-specific code XXX has been stripped out in case any one is confused.

**Comment by bryevdv** [comment]
Happy to have a PR for this.
