### ISSUE TITLE
Simple layout editor

### ISSUE THREAD

**Issue by JEGBergqvist** [bokeh/bokeh#8515]
**Long-term feature / project request:** A graphical layout editor (minimum viable product-level)

**Purpose:** Simplify the design of full-blown rich-client-style GUI applications. 
**Intended use:** Tool for programmers using Bokeh as a framework to create web-based data-related applications.
**Background:** Bokeh is powerful, but may be considered slightly cumbersome from a usability perspective for creating mid-size to extensive GUI designs.
**Value proposition:** Lower the initial threshold for new developers / users / "customers" to use Bokeh as the go-to solution when selecting technology for web-based data-related tool implementation.

_**Suggested requirement specification:**_
**- GUI:** Drag-and-drop WYSIWYG-style layout, with static icons for GUI elements / Widgets.
**- Output:** Python code snippet generating the corresponding array of Layout objects and Widgets
**- Important 1:** Possibility to update existing layouts => Store the core layout as JSON, enabling re-generation of the Python code (i.e. the "array-based DOM Layout tree")
**- Important 2:** Possibility to add generic GUI elements, represented graphically as plain boxes just showing the name of the element type. This effectively opens up for custom-made elements to be included in the layout editor.
**- Good-to-have:** It would be a nice feature for the editor to allow for additional valid parameters to be specified (like disabled, title, etc) in addition to the implicit height and width parameters (the latter ones taken from the direct graphical manipulation of box-shaped representations of the GUI elements). Even more slick would be, as a user of the editor, to get help with what extra parameters are available for each type of GUI element.

**Comment by bryevdv** [comment]
I'll be honest @JEGBergqvist and state that while this sounds very nice, I think it is probably out of scope for the core library project. It seems like something better suited to be built on top of Bokeh, as a separate application project. 

Setting aside the question of scope, there is a further question of resources. At the moment, there is currently no longer any person paid to work on Bokeh full time, or near to full time. Without some  time/effort commitments from some new contributors with the right sort of experience in building this sort of tool, or some financial commitments form organizations to hire people with the right experience to help, I think the chances of something like this happening are quite slim.

**Comment by bryevdv** [comment]
cc @bokeh/core

**Comment by JEGBergqvist** [comment]
Yes, in that case it does seem a bit far-fetched, agreed. Anyways, if the situation would change in the future, I have quickly put down some thoughts on how such an editor could work, in the form of a pseudo YAML example. I do understand there is no resources to go on, but it's a start at least. 


[layout_editor_implementation_thoughts.yaml.txt](https://github.com/bokeh/bokeh/files/2700498/layout_editor_implementation_thoughts.yaml.txt)
