### ISSUE TITLE
Overlapping attribution for labels tiles

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#8519]
The automatic tile source attributions are very helpful for following the terms of service of tile providers, but they don't work well for the STAMEN_TONER_LABELS tile set, which is meant to be overlaid on another set of tiles:

![image](https://user-images.githubusercontent.com/1695496/50376071-702de000-05cd-11e9-8c18-a0fc24b66194.png)

Maybe we can have an attribute specifying the attribution text position for a `TileSource`, and have that default to starting on the left for the labels tiles and on the right for the rest?  Even just allowing the user to adjust it without having appropriate defaults would be a big help here.

**Comment by mattpap** [comment]
Currently attribution is just a bunch of custom HTML and CSS. There is issue #4284 open for making attribution a proper model and bringing it under layout. With this work done, implementing what's proposed in this issue would be trivial and would allow for great amount of flexibility.

**Comment by mattpap** [comment]
An example of stacked attributions:
![image](https://github.com/bokeh/bokeh/assets/27475/281057ae-98f3-4a21-beb2-31bfad54eb53)
