### ISSUE TITLE
npm packages support show bokeh in vue

### ISSUE THREAD

**Issue by cclc** [bokeh/bokeh#8527]
hi
I wrote an npm package for bokeh to make it easier to display in vue
https://www.npmjs.com/package/bokeh-vue

you can try it and give me some suggestions for improvement
:)

**Comment by bryevdv** [comment]
Hi @cclc I'm actually not familiar with Vue, so I can't really offer any advice. The issue tracker has a fairly narrow audience. I'd suggest posting this on the mailing list where there is a much bigger pool of users who may be interested to know about or, or able to comment on it:


https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
