### ISSUE TITLE
Autoreloader cannot find bokeh on reload

### ISSUE THREAD

**Issue by johny1614** [bokeh/bokeh#8529]
I type command to serve my project:
`bokeh serve --show proj.py --dev proj.py`
By now everything works - I see correct results in my browser.

Later after changing and saving file proj.py bokeh tries to reload page and it crashes with message:

> can't open file 'D:\Anaconda\envs\pyt27\Scripts\bokeh': [Errno 2] No such file or directory

I have such file (precisely it's bokeh.exe seeing details of the file).
Also I have D:\Anaconda\envs\pyt27\Scripts in PATH environmental variable.
My environment:

bokeh: 1.0.2
python: 2.7.15
windows 7

**Comment by bryevdv** [comment]
I wonder if this is actually a Tornado issue. All we do on the Bokeh side besides calling watch on the extra files that need watching, is ultimately to pass `autoreload=True` to `tornado.web.Application` 

@bdarnell do you have any insights here?

**Comment by bryevdv** [comment]
@johny1614 can you execute the app with `bokeh.exe` from the command line, instead of `bokeh` ? If so, does that work? That simply may be the solution on windows, in which case we could add documentation about it.

**Comment by bdarnell** [comment]
I don't know anything about these `.exe` wrappers, but I doubt invoking the script as `bokeh.exe` will make a difference. I've personally done very little work on windows (or anaconda for that matter); the only thing I'm sure I've tried on windows involving autoreload is invoking `c:\pythonXY\python.exe -m tornado.autoreload -m tornado.test`. 

Autoreload is sensitive to the `sys.argv` and `sys.executable` variables. Paths containing spaces have been problematic on windows before although comments indicate we've worked around those problems. Python 3.4 introduced some features that make autoreload slightly more robust.

**Comment by bryevdv** [comment]
Ah that's another idea for starting the bokeh server:
```
python -m bokeh serve
```
That might provide a workable `sys.argv` in all cases.

**Comment by bryevdv** [comment]
@johny1614 can you try out the suggestions above and report back? None of the core team is a regular windows user, so two minutes of your time would save much more effort on our end.

**Comment by xavArtley** [comment]
I tried your idea @bryevdv and indeed its a workaround the issue

**Comment by johny1614** [comment]
I'm sorry, just realised there is a response.
running python -m bokeh seve proj.py --dev proj.py
Gives another error:

```
Traceback (most recent call last):
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\__main__.py", line 76, in <module>
    main()
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\__main__.py", line 62, in main
    from bokeh.command.bootstrap import main as _main
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\command\bootstrap.py", line 55, in <module>
    from .util import die
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\command\util.py", line 33, in <module>
    from bokeh.application import Application
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\application\__init__.py", line 31, in <module>
    from .application import Application
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\application\application.py", line 39, in <module>
    from ..document import Document
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\document\__init__.py", line 29, in <module>
    from .document import DEFAULT_TITLE ; DEFAULT_TITLE
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\document\document.py", line 43, in <module>
    import jinja2
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\jinja2\__init__.py", line 41, in <module>
    from jinja2.bccache import BytecodeCache, FileSystemBytecodeCache, \
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\jinja2\bccache.py", line 23, in <module>
    import tempfile
  File "D:\Anaconda\envs\pyt27_2\lib\tempfile.py", line 32, in <module>
    import io as _io
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\io\__init__.py", line 52, in <module>
    from .export import export_png
  File "D:\Anaconda\envs\pyt27_2\lib\site-packages\bokeh\io\export.py", line 32, in <module>
    from tempfile import mkstemp
ImportError: cannot import name mkstemp
```
I inserted into file export.py a simple print line with sys.argv. Somehow it is called correctly at first time running a server, but only after reload it finds difficulties to import mkstemp (having same sys.argv).

**Comment by bryevdv** [comment]
@johny1614 do you have this issue with any of the published examples? e.g. `sliders.py`

**Comment by johny1614** [comment]
yup. Same error with sliders.py

**Comment by bryevdv** [comment]
Is there any chance your python installation is corrupted somehow? can you try in a fresh env?

**Comment by johny1614** [comment]
Using different environment (windows 8.1) - same situation.

**Comment by xavArtley** [comment]
@bryevdv sorry for my late response I han't seen you referenced me
yes I reported success on Windows 7 using `python -m bokeh serve --dev`

**Comment by bryevdv** [comment]
@xavArtley would you mind making the small PR to document that windows users will need to run  bokeh server in this way for `--dev` to function? I think that is all we are able to do.
