### ISSUE TITLE
Memory leak when plotting multiple plots in a row

### ISSUE THREAD

**Issue by dbk123** [bokeh/bokeh#8532]
I've got some code that causes a memory leak when run in Jupyter Lab (but seems OK in Jupyter Notebook).  Not sure if the problem is bokeh or Jupyter Lab, but I thought I would let folks know about it here.  When run, the memory associated with the localhost process continually (and fairly rapidly) grows until the notebook becomes unresponsive and crashes. The code is creating a row of three very simple bokeh plots as shown below. The problem occurs using both Safari and Chrome browsers on the Mac.  Happy to provide more info if needed.

![](https://user-images.githubusercontent.com/16540538/50568836-f2cd4280-0d25-11e9-8b8f-2ed043d2ddb3.png)

**Comment by bryevdv** [comment]
Much more information is needed, all the versions of relevant packages, a link to a runnable notebook to reproduce, and a more thorough description of the process involved. Usually memory leaks are associated with repetitive process, are you saying memory starts growing after only one invocation of this cell? Or you are running over and over? Or?

**Comment by dbk123** [comment]
Hi Bryan,

Thanks for your response.  The problem occurs when the cell is just run once.  I have attached a simple version of a notebook (zipped) created to help isolate the problem  that causes the problem (on both Windows and Macs), as well as, a listing of package versions.  

[Package Versions.txt](https://github.com/bokeh/bokeh/files/2720893/Package.Versions.txt)
(zipped)
[MemoryLeakTest.zip](https://github.com/bokeh/bokeh/files/2720885/MemoryLeakTest.zip)

**Comment by bryevdv** [comment]
@dbk123 I can confirm the issue with Bokeh 1.0.3 and jlab 0.35.3, however it goes away when I change your notebook to what I would consider recommended and standard usage (i.e. the usage demonstrated in every example notebook). Namely, to load BokehJS first, in its own cell:

<img width="841" alt="screen shot 2019-01-02 at 21 38 23" src="https://user-images.githubusercontent.com/1078448/50624625-efc58400-0ed6-11e9-9a03-73be7f7fa187.png">

Can you confirm this also fixes things for you? 

I am not sure why this should happen. Historically, integrating with jupyter has been an enormous resource sink, so we may simply opt to try and detect and abort with an error message about proper usage unless there is some simple obvious fix. 

cc @canavandl

**Comment by bryevdv** [comment]
Actually now I am unable to reproduce again even after going back to the original notebook.

**Comment by bryevdv** [comment]
Yah I am not able to reproduce this again despite many different attempts. What version of the juptyerlab bokeh extension did you install? That is not included in the python package output above.

**Comment by bryevdv** [comment]
The `output_notebook` notion seems like it was a red-herring. But I am not sure what else to suggest as I have still be unable to reproduce the issue again after it happened once. Though, have you tried explicitly clearing all output cells and putting `output_notebook` in its own cell before re-running? Perhaps there is some errant state that is being stored in the saved notebook. That is the only thing I can think of.

**Comment by dbk123** [comment]
This sure is weird - I moved the output_notebook() in and out of it's own cell and I can not get the memory leak to reoccur.  Geesh...

**Comment by bryevdv** [comment]
OK, I have not had time to look closely, but for future reference here is the script that gets sent as part of the "load" mime bundle. My guess is that some race condition interferes with the timeout failsafe or "is loading" detection, and causes the JS libraries to loaded over and over infinitely.
```

(function(root) {
  function now() {
    return new Date();
  }

  var force = true;

  if (typeof (root._bokeh_onload_callbacks) === "undefined" || force === true) {
    root._bokeh_onload_callbacks = [];
    root._bokeh_is_loading = undefined;
  }




  if (typeof (root._bokeh_timeout) === "undefined" || force === true) {
    root._bokeh_timeout = Date.now() + 5000;
    root._bokeh_failed_load = false;
  }

  var NB_LOAD_WARNING = {'data': {'text/html':
     "<div style='background-color: #fdd'>\n"+
     "<p>\n"+
     "BokehJS does not appear to have successfully loaded. If loading BokehJS from CDN, this \n"+
     "may be due to a slow or bad network connection. Possible fixes:\n"+
     "</p>\n"+
     "<ul>\n"+
     "<li>re-rerun `output_notebook()` to attempt to load from CDN again, or</li>\n"+
     "<li>use INLINE resources instead, as so:</li>\n"+
     "</ul>\n"+
     "<code>\n"+
     "from bokeh.resources import INLINE\n"+
     "output_notebook(resources=INLINE)\n"+
     "</code>\n"+
     "</div>"}};

  function display_loaded() {
    var el = document.getElementById("1001");
    if (el != null) {
      el.textContent = "BokehJS is loading...";
    }
    if (root.Bokeh !== undefined) {
      if (el != null) {
        el.textContent = "BokehJS " + root.Bokeh.version + " successfully loaded.";
      }
    } else if (Date.now() < root._bokeh_timeout) {
      setTimeout(display_loaded, 100)
    }
  }


  function run_callbacks() {
    try {
      root._bokeh_onload_callbacks.forEach(function(callback) { callback() });
    }
    finally {
      delete root._bokeh_onload_callbacks
    }
    console.info("Bokeh: all callbacks have finished");
  }

  function load_libs(js_urls, callback) {
    root._bokeh_onload_callbacks.push(callback);
    if (root._bokeh_is_loading > 0) {
      console.log("Bokeh: BokehJS is being loaded, scheduling callback at", now());
      return null;
    }
    if (js_urls == null || js_urls.length === 0) {
      run_callbacks();
      return null;
    }
    console.log("Bokeh: BokehJS not loaded, scheduling load and callback at", now());
    root._bokeh_is_loading = js_urls.length;
    for (var i = 0; i < js_urls.length; i++) {
      var url = js_urls[i];
      var s = document.createElement('script');
      s.src = url;
      s.async = false;
      s.onreadystatechange = s.onload = function() {
        root._bokeh_is_loading--;
        if (root._bokeh_is_loading === 0) {
          console.log("Bokeh: all BokehJS libraries loaded");
          run_callbacks()
        }
      };
      s.onerror = function() {
        console.warn("failed to load library " + url);
      };
      console.log("Bokeh: injecting script tag for BokehJS library: ", url);
      document.getElementsByTagName("head")[0].appendChild(s);
    }
  };var element = document.getElementById("1001");
  if (element == null) {
    console.log("Bokeh: ERROR: autoload.js configured with elementid '1001' but no matching script tag was found. ")
    return false;
  }

  var js_urls = ["https://cdn.pydata.org/bokeh/release/bokeh-1.0.3.min.js", "https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.3.min.js", "https://cdn.pydata.org/bokeh/release/bokeh-tables-1.0.3.min.js", "https://cdn.pydata.org/bokeh/release/bokeh-gl-1.0.3.min.js"];

  var inline_js = [
    function(Bokeh) {
      Bokeh.set_log_level("info");
    },

    function(Bokeh) {

    },
    function(Bokeh) {
      console.log("Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-1.0.3.min.css");
      Bokeh.embed.inject_css("https://cdn.pydata.org/bokeh/release/bokeh-1.0.3.min.css");
      console.log("Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.3.min.css");
      Bokeh.embed.inject_css("https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.3.min.css");
      console.log("Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-tables-1.0.3.min.css");
      Bokeh.embed.inject_css("https://cdn.pydata.org/bokeh/release/bokeh-tables-1.0.3.min.css");
    }
  ];

  function run_inline_js() {

    if ((root.Bokeh !== undefined) || (force === true)) {
      for (var i = 0; i < inline_js.length; i++) {
        inline_js[i].call(root, root.Bokeh);
      }if (force === true) {
        display_loaded();
      }} else if (Date.now() < root._bokeh_timeout) {
      setTimeout(run_inline_js, 100);
    } else if (!root._bokeh_failed_load) {
      console.log("Bokeh: BokehJS failed to load within specified timeout.");
      root._bokeh_failed_load = true;
    } else if (force !== true) {
      var cell = $(document.getElementById("1001")).parents('.cell').data().cell;
      cell.output_area.append_execute_result(NB_LOAD_WARNING)
    }

  }

  if (root._bokeh_is_loading === 0) {
    console.log("Bokeh: BokehJS loaded, going straight to plotting");
    run_inline_js();
  } else {
    load_libs(js_urls, function() {
      console.log("Bokeh: BokehJS plotting callback run at", now());
      run_inline_js();
    });
  }
}(window));
```
If this can ever be reproduced again. it would be good to try and have the browser dev tools open and quickly find the output cell in the dom explorerer. If it has a huge and growing number of `<script>` tags added, that would be consistent with this hypothesis.

**Comment by bryevdv** [comment]
That said I don't know why it would become un-reproducible after it stops. Again I can only assume there is some lingering output state in saved notebooks interacting with the plugin code.

**Comment by dbk123** [comment]
I agree with closing this until/unless I can come up with a consistent example.  Appreciate your help on this!
