### ISSUE TITLE
Open Typescript files as UTF-8?

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#8562]
In PR #8202, Bokeh was changed to open Python3 scripts explicitly as UTF-8, to avoid differences in the default behavior between Windows and other platforms.  I think this fixed problems we used to have with special characters like Play and Pause that worked on Mac and Linux but not Windows (https://github.com/pyviz/pyviz/issues/109).

Is there any reason not to make the same change for Typescript files used for custom models in Bokeh, i.e. always loading them as UTF-8?  We're having the same problem as we did previously for Python, but now for Typescript, i.e. with special characters that work fine in string literals on Mac and Linux platforms but fail on Windows (https://github.com/pyviz/panel/pull/209/files). As best I can see, UTF-8 is the typical encoding for Typescript files as well (or at least is claimed to be in an answer to SO https://github.com/palantir/tslint/issues/2810), so it seems like the same fix is appropriate.

Without this fix we'll keep finding that we have to remove otherwise readable characters from our source files and replace them with gibberish if we want them to work on Windows...

**Comment by bryevdv** [comment]
Seems OK to me offhand.

**Comment by jbednar** [comment]
@mattpap, ok by you as well?

**Comment by mattpap** [comment]
Sure, but as far I can tell, we already open all files as UTF-8 in compiler's module.

**Comment by jsignell** [comment]
Yeah I agree with @mattpap. It seems like we already do this. In particular I am looking at: https://github.com/bokeh/bokeh/blob/d260c429451a04b1fc00f593ef98f10ce1392e57/bokeh/util/compiler.py#L199-L200 

I guess in the case you are talking about @jbednar, the model might not be getting `FromFile` in this block:

https://github.com/bokeh/bokeh/blob/d260c429451a04b1fc00f593ef98f10ce1392e57/bokeh/util/compiler.py#L257-L264

**Comment by bryevdv** [comment]
What would certainly be useful to start is a failing test case.

**Comment by bryevdv** [comment]
I'm inclined to agree. Maybe it is possible to suggest or push changes upstream? From a distance it seems you all are taxing the limits of `nbformat`
