### ISSUE TITLE
tabs with sizing mode 'scale_width' renders empty page

### ISSUE THREAD

**Issue by brcnblc** [bokeh/bokeh#8564]
When I render column layouts with property sizing_mode = 'scale_width' , I encounter empty tab pages. Same thing happens if sizing mode is 'scale_height' or 'stretch_both'.

Page is rendered normally if I use 'fixed' as sizing_mode.

Column1 includes 1 external toolbar and 2 figures, Column 2 includes 1 external toolbar and 1 figure.
Each column is rendered properly with relative sizing modes if they are shown separately with show. The problem persists even I drop the external toolbar from the column array.

The only object that can be seen is the half of the bokeh logo at left side of the screen.

Best Regards.

```
# Not self containing code

#from main program
strat.showTabs(sizing_mode = 'scale_width' ) #produces empty page
strat.showTabs(sizing_mode = 'fixed' ) #produces normal page

#from main class
def showTabs(self,sizing_mode = 'scale_width'):
        tabs = []
        for chartTabName,chartTabValues in self.chartTabs.items():
            chartTabInstance = chartTabValues['instance']
            tabName = chartTabInstance.tabName
            tabLayout = chartTabInstance.getLayout(sizing_mode=sizing_mode)
            tabs.append(Panel(child = tabLayout, title = tabName))
        tabPage = Tabs(tabs = tabs)
        output_file("temp/tabs.html")
        show(tabPage)

#from chart class
def getLayout(self,sizing_mode = 'scale_width'):
        plotArray = []
        plotArray.append(self.toolBarBox)

        for chartName in self.__plots:
            plotArray.append(self.__plots[chartName])
    
        return column(plotArray, sizing_mode = sizing_mode)
```
Bokeh version is. 1.0.4
MacOs Mojave 10.14.2
Python Python 3.7.1
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Normal View with fixed size (Tab 1)( sizing_mode = 'fixed')
![normaltab1](https://user-images.githubusercontent.com/29043834/51085299-fdd19b00-1747-11e9-8b15-aacf20d10782.jpg)

Normal View with fixed size (Tab 2)( sizing_mode = 'fixed')
![normaltab2](https://user-images.githubusercontent.com/29043834/51085327-6456b900-1748-11e9-8096-f75dd198d545.jpg)

Screenshots or screencasts of the bug in action
Abnormal view Tab1 (Same view as Tab2) (sizing_mode = 'scale_width')
![abnormaltab](https://user-images.githubusercontent.com/29043834/51085186-9ebf5680-1746-11e9-9559-29005761d615.jpg)

**Comment by bryevdv** [comment]
@brcnblc it's really absolutely necessary to have a complete test case in issues. For instance, I had hoped to see if #8085 solves this issue, only to come here and find that I can't test anything at all because there is no minimal complete example. Accordingly I am closing this as `norepro`. Hopefully #8085 (which will be part of Bokeh 1.1) fixes your issues. If not, please feel free to add a *complete* test script, and we can re-open.
