### ISSUE TITLE
Tile provider causes "Model must be owned by only a single document" error

### ISSUE THREAD

**Issue by RunOrVeith** [bokeh/bokeh#8566]
**System**:
Bokeh 1.0.4
python 3.6
Ubuntu 18.04

#### Description of expected behavior and the observed behavior

**Expected:** When using a `tile_provider` such as `CARTODBPOSITRON`, the object that is imported globally can be attached to more than one document.
**Actual:** A RuntimeError is raised, because the tile provider already is part of a document.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.tile_providers import CARTODBPOSITRON
from bokeh.plotting import figure
from bokeh.io import show


def test():
    fig = figure(plot_width=1000, plot_height=1000,
                 active_scroll="wheel_zoom",
                 x_range=(49., 49.5), y_range=(30., 30.5),
                 x_axis_type="mercator", y_axis_type="mercator",
                 )

    fig.add_tile(CARTODBPOSITRON)
    show(fig)

test()
test()
```

Traceback:

```
Traceback (most recent call last):
  File "/home/veith/.PyCharmCE2018.3/config/scratches/scratch.py", line 18, in <module>
    test()
  File "/home/veith/.PyCharmCE2018.3/config/scratches/scratch.py", line 15, in test
    show(fig)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/io/showing.py", line 142, in show
    return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/io/showing.py", line 180, in _show_with_state
    _show_file_with_state(obj, state, new, controller)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/io/showing.py", line 163, in _show_file_with_state
    filename = save(obj, state=state)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/io/saving.py", line 86, in save
    _save_helper(obj, filename, resources, title, template)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/io/saving.py", line 148, in _save_helper
    html = file_html(obj, resources, title=title, template=template)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/embed/standalone.py", line 307, in file_html
    with OutputDocumentFor(models, apply_theme=theme, always_new=_always_new) as doc:
  File "/home/veith/Tools/pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/embed/util.py", line 137, in OutputDocumentFor
    doc.add_root(model)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/document/document.py", line 304, in add_root
    self._pop_all_models_freeze()
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/document/document.py", line 1018, in _pop_all_models_freeze
    self._recompute_all_models()
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/document/document.py", line 1041, in _recompute_all_models
    a._attach_document(self)
  File "/home/veith/vscen/lib/python3.6/site-packages/bokeh/model.py", line 609, in _attach_document
    raise RuntimeError("Models must be owned by only a single document, %r is already in a doc" % (self))
RuntimeError: Models must be owned by only a single document, WMTSTileSource(id='1001', ...) is already in a doc
```

Moving the import into the function solves the issue:

```python
from bokeh.plotting import figure
from bokeh.io import show


def test():
    from bokeh.tile_providers import CARTODBPOSITRON  # Importing here works

    fig = figure(plot_width=1000, plot_height=1000,
                 active_scroll="wheel_zoom",
                 x_range=(49., 49.5), y_range=(30., 30.5),
                 x_axis_type="mercator", y_axis_type="mercator",
                 )

    fig.add_tile(CARTODBPOSITRON)

    show(fig)

test()
test()
```

This is neither very intuitive, nor mentioned in the [documentation](https://bokeh.pydata.org/en/latest/docs/reference/tile_providers.html) (as far as I have seen).

**Comment by philippjfr** [comment]
This was reported on two previous occasions (see https://github.com/bokeh/bokeh/issues/4770 and https://github.com/bokeh/bokeh/issues/6590), which were both closed. I do strongly agree that this is unexpected and unintuitive. I'm not sure what the best solution is but providing already instantiated models does not seem like the best way to ship these default tile sources.

**Comment by RunOrVeith** [comment]
As a quick fix I'd suggest at least adding a comment in the documentation. (sorry for the duplicate, but I thought if the issues are closed this should be a new issue).

**Comment by bryevdv** [comment]
> This was reported on two previous occasions (see #4770 and #6590), which were both closed. I do strongly agree that this is unexpected and unintuitive. I'm not sure what the best solution is but providing already instantiated models does not seem like the best way to ship these default tile sources.
 
#4770 was closed because it only referred to this problem in the context of Bokeh server apps, and that problem was solved by using the "module hack" to always return a new instance of the object on import or access, and that works for server apps because each session does an import. But that obviously does not help in instances like this where there is only one import. 

As for workarounds, I would also expect this to work:
```
import bokeh.tile_providers as tp

def test():
    ...
    fig.add_tile(tp.CARTODBPOSITRON)
```
I'd be amenable to adding functions for generating built in tile provider instances, changing all the examples to use the functions, and deprecating the direct attribute access (which we can easily do since they go through a getter already). Obviously executing that deprecation is Bokeh 2.0 timeframe.

**Comment by RunOrVeith** [comment]
That would make sense to me. Is there anything I should do for this?

**Comment by bryevdv** [comment]
@RunOrVeith If you have the ability to submit a PR for this, it would absolutely be appreciated. I think given the current situation vs where we would like to go will make it a little awkward but not too bad. I'd propose this:

* make a new method `get_provider(self, provider_name)` that can return a new instance of a tile provider when called like `get_provider(STAMEN_TONER_BACKGROUND)
* in the future (2.0) `STAMEN_TONER_BACKGROUND`, etc, can be string consts or enums. For *right now*, since they are properties, that is what `get_provider` will have to switch on to return the right new instance
* the current properties should also get 2.0 depreciation warnings with explicit advice to use `get_provider*

If you'd like to look into it and need more information, please let us know

**Comment by RunOrVeith** [comment]
I've implemented this now, in what I am assuming is a way that requires minimal effort to actually do the deprecation for bokeh 2.0.

Here are the things I did:

- Implement  `get_provider`. It accepts the provider name as a string (case does not matter), or an
element of a new enum `Provider`. This function creates the tile provider accordingly and returns the new instance of it. (At first I switched on the existing properties, but that was not really a good solution IMHO, especially when the enum is available. It would require catching the deprecation warning, for example).
- Issue deprecations in the existing properties for the providers
- Update the test cases to assert the deprecation warning, and add a new testcase that tests `get_provider`. (The functionality of the other test cases is not duplicated, so that has to be done when the real deprecation happens).
- Update the docstring of `tile_providers`
- Update all examples (that I could find).

Example snippets:

```python
from bokeh.tile_providers import STAMEN_TONER

# Works, but raises BokehDeprecationWarning:
# "BokehDeprecationWarning: CARTODBPOSITRON was deprecated in Bokeh 2.0.0 and will be removed, use get_provider(Provider.CARTODBPOSITRON) instead."

from bokeh.tile_providers import get_provider, Provider

# Use the new enum for tile types
p1 = get_provider(Provider.CARTODBPOSITRON)

# Also works with string names (upper and lower case)
p2 = get_provider("CARTODBPOSITRON")
```


There are a few things which I am not sure about:

- Whether I used the right deprecation protocol (I used `bokeh.util.deprecation.deprecated`)
- Whether I found all examples 
- Whether the docstring is what you expect/the right format. I am not sure how to document the enum values
- Whether I found all examples

Please let me know if anything is not what you expected/should be changed!

**Comment by bryevdv** [comment]
@RunOrVeith This is super helpful, can you go ahead and make a Pull Request, and we then can discuss any technical details there? Offhand my only comment is that the deprecation message should read more like:

> TileProvider literal attributes, including CARTODBPOSITRON, were deprecated in Bokeh 1.1 and will be removed in a future 2.0 release. Use get_provider(tile_providers.CARTODBPOSITRON) or get_provider("CARTODBPOSITRON") instead.

**Comment by RunOrVeith** [comment]
Yes, you were too fast for me to make the pull request :smile: 
Is there a specific function you use for such a deprecation instead of `bokeh.util.deprecation.deprecated`, or should I just issue a `BokehDeprecationWarning` directly?

**Comment by RunOrVeith** [comment]
This should also be kept in mind for #8560
