### ISSUE TITLE
increased options for name/id/title on server docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#857]
propose:

* `id` - Always present, unique, auto-generated. Always has associated URL on the server. Can be UUID in general case but might be nice to have "dev" mode that just generates increasing integer `id`'s for easier readability when debugging.

* `name` -  optional alias for an id. Is unique also, in the sense that storing a new doc (with a new id) with an already existing `name` does one of these two things:
 - makes the `name` point to the new `id` (warning in the process)
 - reports a duplicate `name` error (and does not store the doc)

  This policy should be selectable. Doc names also have an associated URL on the server.

* `title` - this is a HTML title used for any HTML docs that get generated. Has nothing to do with `name` or `id` or any server URL. If not present, falls back to `name` if that's not present, falls back to... `id`? or some generic title?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
