### ISSUE TITLE
[DOCS] Add reference to conda env var setting in dev-guide

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#8570]
I just got setup again with a fresh bokeh-dev env and that docs are looking really great! I did find myself wanting to add env vars to my conda activate command and was wondering if there should be a link from [dev-guide getting started](https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/dev_guide/setup.rst) to [conda-env managing environments](https://conda.io/docs/user-guide/tasks/manage-environments.html#saving-environment-variables) or if the contents from that section should be duplicated.

**Comment by bryevdv** [comment]
I don't know about this feature / don't use it, so I would not know what to say in the dev docs. I also think maybe it's a fairly advanced/specific case and that it's better to keep the dev setup as simple and streamlined as possible. So, closing. But if you feel strongly and want to make a PR we can consider it.
