### ISSUE TITLE
`scripts/deps.py` does not install phantom_js

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8571]
Have been running through a fresh install and build and followed the dev instructions here: https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html

To install dependencies I ran:  
    
    conda install `python scripts/deps.py build run test` 

After doing this if you run `py.test -m unit` or `py.test -m "unit and not selenium"`, the tests will fail because phantom_js is not installed.

We should either update the documentation or the script to install phantom_js while it's a dependency.

**Comment by bryevdv** [comment]
hrm I thought the `npm install` step did this but evidently not?

**Comment by mattpap** [comment]
> hrm I thought the npm install step did this but evidently not?

bokehjs doesn't depend on phantomjs, so no, though it used to.

**Comment by bryevdv** [comment]
> bokehjs doesn't depend on phantomjs, so no, though it used to.

Ah, OK. An addition to the dev guide is definitely in order then

**Comment by bryevdv** [comment]
Actually I think there is a conda package for it on all platforms in which case we should just add it the right section in `meta.yaml`

**Comment by bryevdv** [comment]
Scratch that, `phantomjs` is not available on linux and our configured conda channels, which is unfortunate. I guess this will have to be a docs-only fix
