### ISSUE TITLE
transforms.py is missing property unit tests

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8572]
Noticed today that the Transforms in `bokeh/models/transforms.py` are missing simple properties unit tests - like those in `bokeh/models/tests/test_annotations.py`

**Comment by bryevdv** [comment]
Definitely agree. I think it would be nice to define a consistent conventional approach to testing properties across the whole codebase. Offhand:

* We have the JS "defaults test" which ensures that the defined properties and their defaults match up exactly on the Python and JS sides. This is absolutely critical and good, but it's not sufficient. 

* We don't have 100% coverage of properties and values on the Python side, and we have different kinds of tests for the conceptual purpose all over. 

Ideally, I think we would have:

* a standard conventional *way* to test python model properties, and a standard conventional place to test them (i.e. I think this is an important enough task that it's worth not mixing testing e.g. `Plot` properties with other non-property unit tests) 

* a conventional place/directory format for these tests

* a meta-test that fails if there is not 100% coverage (modulo any explicit exceptions)

If we have that, together with the JS defaults test, I think everything will be appropriately locked down to guard against accidental changes or drift, and with conventions it becomes easier to document and convey expectations to new contributors. (Start to finish "how to add a new model" or "how to add a new property" walkthroughs would be *great*)

**Comment by Nkarnaud** [comment]
Just added some few test cases in  `bokeh/models/transforms.py`  and run the test successfull.
