### ISSUE TITLE
MultiPolygons can end up in broken state on updates

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8573]
I'm still actively investigating what is going wrong here, but when working with MultiPolygons I can reliably get into a state where the `GlyphRendererView.all_indices` attribute is out of sync with the actual length/indices of the data source which triggers errors like this during rendering:

```
bokeh-1.0.4.js:15124 Uncaught TypeError: Cannot read property 'length' of undefined
    at MultiPolygonsView._render (VM17814 bokeh-1.0.4.js:15124)
    at MultiPolygonsView.GlyphView.render (VM17814 bokeh-1.0.4.js:13699)
    at GlyphRendererView.render (VM17814 bokeh-1.0.4.js:21744)
    at PlotCanvasView._paint_levels (VM17814 bokeh-1.0.4.js:20643)
    at PlotCanvasView.paint (VM17814 bokeh-1.0.4.js:20607)
    at PlotCanvasView.repaint (VM17814 bokeh-1.0.4.js:20539)
    at PlotCanvasView.<anonymous> (VM17814 bokeh-1.0.4.js:20420)
    at Signal0.Signal.emit (VM17814 bokeh-1.0.4.js:3207)
    at Signal0.emit (VM17814 bokeh-1.0.4.js:3220)
```

Specifically it often breaks on this line in multi_polygon.ts:

```typescript
for (let j = 0, endj = sxs[i].length; j < endj; j++) {
```

I'm still trying to put together a reproducible example and/or digging further to figure out why the CDSView is not triggering an update in the GlyphRendererView.all_indices, which would prevent things from getting out-of-sync, but I thought I'd start by filing the issue in case someone has some idea what might be the cause of this.

**Comment by bryevdv** [comment]
I definitely don't, so a way to reproduce is going to be critical.

**Comment by philippjfr** [comment]
Okay thanks, I'm still digging. I can reproduce it easily in holoviews but only when I'm rendering complex shapefiles, so I'm still struggling to extract a pure bokeh example.

**Comment by philippjfr** [comment]
The only other observation I can make is that the error becomes less likely if I use smaller, less detailed polygons.

**Comment by philippjfr** [comment]
Bokeh is not at fault here, I tracked the bug down, the CDS data was being updated with data in the incorrect (patches) format. Sorry about the noise.
