### ISSUE TITLE
"Models must be owned by only a single document" when reusing server port

### ISSUE THREAD

**Issue by tete1030** [bokeh/bokeh#8579]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 1.0.4
Python 3.6.8 :: Anaconda custom (64-bit)
Jupyter notebook 5.7.4
macOS 10.14.2, Ubuntu 16.04
Chrome 71.0.3578.98

#### Description of expected behavior and the observed behavior

Copy the following codes into a jupyter notebook (at least version 5.1.0). 

When firstly execute `In[2]`, there is only one "Handler called" printed and the Button rendered normally. Then run `In[2]` again, two lines of "Handler called" are printed, Button is still normal. However at the third time and followers, one "Handler called" is printed and the server side reported error "Models must be owned by only a single document".

If then I wait for at least 5 minutes (I didn't measure exactly how long) and execute `In[2]` again, it just works normally again with only one "Handler called" printed.

P.S. Notebook needs to be at least 5.1.0, otherwise re-running of notebook cell will not trigger a `clear_output` event, thus the `destroy_server` will not be called at bokeh server side. In this case you need to manually clear output to release the port as in https://github.com/bokeh/bokeh/issues/7466#issuecomment-361690363. 

_**If the `port` is set to random choosing, this problem is gone.**_

#### Complete, minimal, self-contained example code that reproduces the issue

In[1]:
```python3
from bokeh.plotting import output_notebook
output_notebook()

def test():
    from bokeh.models.widgets import Button
    from bokeh.layouts import layout
    from bokeh.io.state import curstate
    from bokeh.io.notebook import show_app

    test_btn = Button(label="Test")
    mylayout = layout([test_btn])
    def modify_doc(doc):
        print("Handler called")
        doc.add_root(mylayout)

    show_app(
        modify_doc,
        curstate(),
        notebook_url="http://localhost:8888",
        port=12345) # port=0 is okay
```

In[2]:
```python3
test()
```

#### Stack traceback and/or browser JavaScript console output

```
ERROR:tornado.application:Uncaught exception GET /autoload.js?bokeh-autoload-element=1019&bokeh-absolute-url=http://localhost:12345&resources=none (::1)
HTTPServerRequest(protocol='http', host='localhost:12345', method='GET', uri='/autoload.js?bokeh-autoload-element=1019&bokeh-absolute-url=http://localhost:12345&resources=none', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/server/views/autoload_js_handler.py", line 60, in get
    session = yield self.get_session()
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "<ipython-input-1-dfd207c7ef75>", line 14, in modify_doc
    doc.add_root(mylayout)
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 304, in add_root
    self._pop_all_models_freeze()
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 1018, in _pop_all_models_freeze
    self._recompute_all_models()
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 1041, in _recompute_all_models
    a._attach_document(self)
  File "/Users/texot/anaconda3/lib/python3.6/site-packages/bokeh/model.py", line 609, in _attach_document
    raise RuntimeError("Models must be owned by only a single document, %r is already in a doc" % (self))
RuntimeError: Models must be owned by only a single document, Column(id='1004', ...) is already in a doc
ERROR:tornado.access:500 GET /autoload.js?bokeh-autoload-element=1019&bokeh-absolute-url=http://localhost:12345&resources=none (::1) 19.38ms
```

#### Screenshots or screencasts of the bug in action

First time run:
![image](https://user-images.githubusercontent.com/4312115/51491138-64aa2080-1de8-11e9-8d3c-e2789109c27a.png)

Second time:
![image](https://user-images.githubusercontent.com/4312115/51491172-7a1f4a80-1de8-11e9-9105-6a72684da221.png)

Third time:
![image](https://user-images.githubusercontent.com/4312115/51491235-a76bf880-1de8-11e9-8509-b623f6ce2991.png)

**Comment by bryevdv** [comment]
This is a usage error, and the resulting error is expected and intended. *Every* Bokeh model for the embedded app must be generated fresh every time the `modify_doc` function, so that every invocation of the `show_app` function creates a completely new and self-contained app document. I.e you cannot have Bokeh models "outside" the function. The reason for this is simply that having a mixture of automatically synchronizing dual-runtime (Python/JS) objects smeared across notebooks cells that can executed repeatedly and out of order, is *impossible to reason about effectively*. you should closely emulate the existing notebook app examples, e.g. https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/notebook_embed.ipynb

**Comment by bryevdv** [comment]
Another way to state this: Bokeh apps  are actually more like recipes that create collections of Bokeh objects. Every time the recipe is used (here, `modify_doc`) it must create a brand new collection.

**Comment by tete1030** [comment]
Thank you for your explanation. But I'm still a little confused. I cannot see anything except the port number is not new. I think `mylayout` as well as its children that will be passed to `add_root` are new objects every time I call `test()`, isn't it?

I'm not sure if `modify_doc` itself is a brand new function object each time `test()` gets called, but the reference to `mylayout` inside `modify_doc` should have been updated (maybe in `modify_doc.__code__.co_freevars`, I'm not sure). When the `modify_doc` function gets called in a new server, it should execute `doc.add_root` with new `mylayout`.

**Comment by tete1030** [comment]
I probably see your points. Do you mean `modify_doc` could be called multiple times with only one `show_app` called? In my code the Model objects are generated only for every `show_app` call, but it should be for every `modify_doc` call, is that correct?

**Comment by bryevdv** [comment]
Yes that's exactly it, I could (and should) have stated things as succinctly as that.

**Comment by tete1030** [comment]
Thanks!

**Comment by drpeterfoster** [comment]
FYI, I stumbled into a "solution" for this when working in a jupyter notebook... 
```
import bokeh.plotting as bop
bop.output_notebook()

p = bop.figure(some plot)
bop.show(p)  # happily plots inline in notebook

bop.output_file('foo.html')
bop.save(p)  # joyfully packages the plot and saves it as expected

try:
    bop.reset_output()
    bop.output_notebook()
    bop.show(p)  # angrily yells at me about single ownership
except:
    bop.output_notebook()
    bop.show(p)  # ...aaaaaaand we're back to happy inline plotting.
```
¯\_(ツ)_/¯

**Comment by bryevdv** [comment]
@drpeterfoster that would be an unrelated issue, since it does not involve the situation with emedded Bokeh server apps described above. That said, I can't reproduce anything like you describe:

<img width="562" alt="Screen Shot 2019-06-06 at 5 16 56 PM" src="https://user-images.githubusercontent.com/1078448/59074143-12d9d280-887f-11e9-9471-d7b4f983e4b3.png">

**Comment by misterjoa** [comment]
Same problem when refreshing page using self-contained server/app : https://github.com/bokeh/bokeh/issues/8265#issuecomment-545413436

**Comment by bryevdv** [comment]
@misterjoa please do not cross-post like this. I have replied describing your usage error in the other issue.
