### ISSUE TITLE
bokeh server on_change from selected glyph not working on v 1.0.4

### ISSUE THREAD

**Issue by johntfoster** [bokeh/bokeh#8581]
I'm trying to use Bokeh's (server) `on_change` method to trigger an action when a glyph is selected (either with `tap` or `lasso_select`), but I can't even get it working for even a simple print statement. Here is a minimal example that shows the problem.

```
from bokeh import plotting as bplt
from bokeh import layouts as blayouts
from bokeh import models as bmodels
from bokeh import io as bio

fig = bplt.figure(tools="lasso_select, tap")

source = bmodels.ColumnDataSource(dict(x=[1,0], y=[0,1]))

r = fig.circle('x', 'y', source=source, size=20)

def handler(attr, old, new):
    print('Hello')

source.on_change('selected', handler)
bio.curdoc().add_root(blayouts.layout([[fig]]))
```

This works on version 0.13, but not on 1.0.4

**Comment by bryevdv** [comment]
This is not correct usage. There was a regression and confusion during the 0.13. release that allowed that to function when it should not. The change for 1.0, which is not maintained rigorously under continuous testing, was outlined in the release/migration notes:

https://bokeh.pydata.org/en/latest/docs/releases.html#handling-of-selections
