### ISSUE TITLE
TypeError: index is not a valid DatetimeIndex or PeriodIndex

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#8585]
Looks like pandas 0.24.0 brought some backwards incompatible changes, e.g. https://travis-ci.org/bokeh/bokeh/jobs/484595447#L1287.

**Comment by bryevdv** [comment]
Fun. I am fine if you want to just skip the one test in your PR for now. We can use this update for a proper fix to the one sample data file.

**Comment by mattpap** [comment]
I fixed this in https://github.com/bokeh/bokeh/pull/8085/commits/8f6f99937c779b869e999bf639d6f294a15d52eb. I mean, it seems to work, but I'm not sure if this is the right thing to do.

**Comment by bryevdv** [comment]
@mattpap That seems reasobable, but it would be more helpful I think to have that change in a standalone PR
