### ISSUE TITLE
[Feature request] Allow DataTable to take its natural height

### ISSUE THREAD

**Issue by bmerry** [bokeh/bokeh#8595]
This probably applies to other widgets as well, but it's particularly annoying for DataTables. I have a Column with a DataTable followed by other elements. I would like the DataTable to behave like normal HTML layout i.e. take as much vertical space as needed to show all the rows, with the following elements appearing immediately below the last row. Even if I know in advance how many rows there will be, there is no portable way to turn that into a height in pixels.

**Comment by mitchm17** [comment]
Simple short-term fix would be to set the height=30*len(data in columns)
You can use this for now until it gets added in. Good luck!
