### ISSUE TITLE
BokehJS examples to use in node js or angular

### ISSUE THREAD

**Issue by Shekharrajak** [bokeh/bokeh#8596]
Hi,

I have installed bokehjs using `npm install bokehjs --save` in Angular application.(means  package.json contains `    "bokehjs": "^1.0.4"` as dependency).

after build I see 

```
No name was provided for external module 'bokehjs' in output.globals – guessing 'Bokehjs'
```

In application : 

```
import * as Bokehjs from 'bokehjs';

```

```
   const plt = Bokehjs.Plotting;
    console.log(plt);   // undefined

```

```
    console.log(Bokehjs);
```
output : 
```
{version: "1.0.4", embed: {…}, protocol: {…}, _testing: {…}, logger: Logger, …}
Models: ƒ (name)
documents: []
embed: {add_document_standalone: ƒ, add_document_from_session: ƒ, embed_items_notebook: ƒ, kernels: {…}, BOKEH_ROOT: "bk-root", …}
index: {}
logger: Logger {_name: "bokeh", _log_level: LogLevel, trace: ƒ, debug: ƒ, info: ƒ, …}
protocol: {Message: ƒ, Receiver: ƒ, __esModule: true}
safely: ƒ safely(fn, silent)
set_log_level: ƒ set_log_level(level)
settings: Settings {_dev: false}
version: "1.0.4"
_testing: {results: {…}, init: ƒ, record: ƒ, count: ƒ, clear: ƒ, …}
__esModule: true
__proto__: Object}
```

```
    console.log(`Bokehjs ${Bokehjs.version}`); // 1.0.4
```

I want to run [chart example](https://github.com/bokeh/bokeh/blob/master/bokehjs/examples/charts/charts.ts) in my angular application

**Comment by Shekharrajak** [comment]
I also tried with adding these lines in tsconfig.json file : 


```
"*": [
        "node_modules/bokehjs/build/js/tree/*",
        "node_modules/bokehjs/build/js/types/*",
        "node_modules/bokehjs/src/lib/external/*"
      ]
```

**Comment by mattpap** [comment]
This was mostly fixed in PR #8085, though some follow up is needed.

**Comment by StewSchrieff** [comment]
Does anyone have a working example of an Angular 2+ project that uses BokehJs? 

I'm new to Bokeh and am fighting similar issues. Would love to see a working copy of a project

**Comment by Shekharrajak** [comment]
@StewSchrieff , I started a project to use bokehJS node module in Angular 7 : https://github.com/Shekharrajak/ng-bokeh

The issue I faced is here : https://github.com/Shekharrajak/ng-bokeh/issues/1
