### ISSUE TITLE
Layout broken in hidden tabs after an update

### ISSUE THREAD

**Issue by cutright** [bokeh/bokeh#8614]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh > 1.0.4
python 2.7
Mac OS 10.14.2
Safari 12.0.2 and Chrome 71.0

#### Description of expected behavior and the observed behavior
If the source data for a figure is updated, the layout for currently unselected tabs appear to be redrawn incorrectly.  Run the code below and click the update data button to observe the layout failure.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import curdoc
from bokeh.models import Button, Tabs, Panel, TextInput
from bokeh.layouts import column
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure


def update_options():
    source.data = {'x': [x for x in range(5)],
                   'y': [y**2 for y in range(5)]}


button = Button(label='Update Data')
button.on_click(update_options)

source = ColumnDataSource(data=dict(x=[], y=[]))
plot = figure()
plot.circle('x', 'y', source=source)

layout1 = column(TextInput(title='Text Input:'), plot)
layout2 = column(TextInput(title='Text Input:'), button)

tab1 = Panel(child=layout1, title='tab1')
tab2 = Panel(child=layout2, title='tab2')
tabs = Tabs(tabs=[tab1, tab2])

curdoc().add_root(tabs)

```

#### Change above code to place button in first tab and issue is resolved in Tab 1, but remains in Tab 2
```
from bokeh.io import curdoc
from bokeh.models import Button, Tabs, Panel, TextInput
from bokeh.layouts import column
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure


def update_options():
    source.data = {'x': [x for x in range(5)],
                   'y': [y**2 for y in range(5)]}


button = Button(label='Update Data')
button.on_click(update_options)

source = ColumnDataSource(data=dict(x=[], y=[]))
plot = figure()
plot.circle('x', 'y', source=source)

layout1 = column(TextInput(title='Text Input:'), button, plot)
layout2 = column(TextInput(title='Text Input:'))

tab1 = Panel(child=layout1, title='tab1')
tab2 = Panel(child=layout2, title='tab2')
tabs = Tabs(tabs=[tab1, tab2])

curdoc().add_root(tabs)
```

#### Stack traceback and/or browser JavaScript console output
[bokeh] setting log level to: 'info'
connection.js:182 [bokeh] Websocket connection 0 is now open
plot_canvas.js:776 [bokeh] could not set initial ranges
t.set_initial_range @ plot_canvas.js:776
document.js:86 [bokeh] document idle at 138 ms
index.js:65 Bokeh items were rendered successfully

#### Screenshots or screencasts of the bug in action

**Code set 1 before updating data**
<img width="667" alt="before" src="https://user-images.githubusercontent.com/4778878/52150737-7edccd80-2636-11e9-9c88-fe4f9d9e63a7.png">
**Code set 2 after updating data**
<img width="667" alt="after" src="https://user-images.githubusercontent.com/4778878/52150745-8308eb00-2636-11e9-8f56-854e4fe31ce0.png">
**Code set 2 before updating data**
<img width="613" alt="before2" src="https://user-images.githubusercontent.com/4778878/52150907-fdd20600-2636-11e9-859a-86935676718c.png">
**Code set 2 after updating data**
<img width="613" alt="after2" src="https://user-images.githubusercontent.com/4778878/52150915-03c7e700-2637-11e9-8e31-9a9e0c52c7f7.png">

**Comment by birdsarah** [comment]
(also same on ff)

**Comment by bryevdv** [comment]
Safari as well, and adding some initial data so that the plot has axes at start does not help. FWIW I don't think this has anything specifically to do with CDS at all, I'd speculate this is purely a (re-)layout issue that happens to be triggered by this (but probably other things as well). @mattpap continuing speculation, is there a simple way to force a recomputation of layout every time a tab becomes visible?

**Comment by mattpap** [comment]
Well, the problem is exactly with layout recomputation, no need to speculate here. I suppose one could rebuild the layout with `Bokeh.index[id].rebuild()` (this ignores all state and starts from scratch, but will maintain open tab index).

**Comment by bryevdv** [comment]
@mattpap so then this diff fixes the problem
```
diff --git a/bokehjs/src/lib/models/layouts/tabs.ts b/bokehjs/src/lib/models/layouts/tabs.ts
index cfa70ae2a..4283d614c 100644
--- a/bokehjs/src/lib/models/layouts/tabs.ts
+++ b/bokehjs/src/lib/models/layouts/tabs.ts
@@ -102,6 +102,7 @@ export class TabsView extends LayoutDOMView {
       hide(child_view.el)

     show(child_views[i].el)
+    this.rebuild()
   }
 }
```
presumably this is more expensive? In the absence of another solution it would still seem to be advised especially since it only affects tabs
