### ISSUE TITLE
JSON_ITEM not found

### ISSUE THREAD

**Issue by ewittry** [bokeh/bokeh#8618]
>>> from bokeh.embed import json_item
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'json_item' from 'bokeh.embed' (/opt/anaconda3/lib/python3.7/site-packages/bokeh/embed/__init__.py)

`$ /opt/anaconda3/bin/conda install bokeh`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/anaconda3
              HTTPS_PROXY=<set>         
               HTTP_PROXY=<set>         
          LD_LIBRARY_PATH=:/usr/lib64:/mu/sdk/unixODBC/2.3.1-gcc443-rhel5-64/etc:/mu/sdk/teradat
                          a/teradata16_20/teradata/client/16.20/lib64                           
                 NO_PROXY=<set>                                                                 
                     PATH=/usr/local/bin:/usr/bin:/mu/sdk/teradata/teradata16_20/teradata/client
                          /16.20/bin:/bin:/opt/miniconda/bin:/mu/bin:/mu/sdk/anaconda/bin/:/usr/
                          bin/:/u/pesoft/lib:/u/prbdata/bin:/u/pesoft/bin:/u/prbsoft/bin:/u/prbd
                          ata/bin:/u/summary/bin:/home/prbesda/app/prod/linux:/home/prbetech/scr
                          ipts/prb_flash_et_scripts                                             
       REQUESTS_CA_BUNDLE=<not set>                                                             
            SSL_CERT_FILE=<not set>                                                             
               http_proxy=<set>                                                                 
              https_proxy=<set>                                                                 

     active environment : None
       user config file : /home/ewittry/.condarc
 populated config files : /home/ewittry/.condarc
          conda version : 4.5.11                
    conda-build version : 3.15.1                
         python version : 3.7.0.final.0         
       base environment : /opt/anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch  
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch  
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch  
                          https://repo.anaconda.com/pkgs/r/linux-64   
                          https://repo.anaconda.com/pkgs/r/noarch     
                          https://repo.anaconda.com/pkgs/pro/linux-64 
                          https://repo.anaconda.com/pkgs/pro/noarch   
          package cache : /opt/anaconda3/pkgs                         
                          /home/ewittry/.conda/pkgs                   
       envs directories : /home/ewittry/.conda/envs                   
                          /opt/anaconda3/envs                         
               platform : linux-64                                    
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/3.10.0-514.2.2.el7.x86_64 rhel/7.3 glibc/2.17
                UID:GID : 58352:3624                                                                                    
             netrc file : None                                                                                          
           offline mode : False

**Comment by bryevdv** [comment]
`json_item` is a recent addition in version 1.0. The issue is almost 100% certainly that your installed version of Bokeh is too old. If you want to use it you will need to upgrade to > 1.0. If you think you have a version newer than 1.0 installed, then you either have some kind of conda/virtualenv  confusion and are not using the version you intend to be using, or you have a corrupted install. In any case, this is a support issue, so it should be on the mailing list, not GitHub
