### ISSUE TITLE
Use utf-8 encoding to open notebook file.

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#8625]
Currently,  `ipynb` file is opened by following code:

```
        with open(filename) as f:
            pass
```

https://github.com/bokeh/bokeh/blob/master/bokeh/application/handlers/notebook.py#L117

I suggest to open the file with `encoding="utf-8"`, otherwise the serve command will raise error on Windows system.

**Comment by bryevdv** [comment]
@ruoyu0088 would you like to submit a PR for us to consider?
