### ISSUE TITLE
DateRangeSlider returns datetime instead of date

### ISSUE THREAD

**Issue by YMRTN** [bokeh/bokeh#8628]
DateRangeSlider has two options, returning a tuple of UNIX epochs or conveniently returning a tuple of datetimes, as explained in #6895.

I think it would be logical to have an option to return a tuple of dates, with the same time resolution as the actual DateRangeSlider. 

This could be fixed by adding a second convenience function very similar to the one defined in #6895.

**Comment by bryevdv** [comment]
@YMRTN would you like to submit a PR? In all likelihood will be able to do so faster than anyone else will be able to get to it.

**Comment by bryevdv** [comment]
> Please be aware that this is my first contribution to an open source project.

That's awesome! I have a day full of meetings but I should be able to take a look and comment on anything later today/tonight.
