### ISSUE TITLE
Stocks Example is not working properly 

### ISSUE THREAD

**Issue by ahmetbaglan** [bokeh/bokeh#8633]
https://github.com/bokeh/bokeh/tree/master/examples/app/stocks

The example suppose to change the stats according to the selected points. For some reason 

        def selection_change(attrname, old, new):
            print('lol')
            t1, t2 = ticker1.value, ticker2.value
            data = get_data(t1, t2)
            selected = source.selected.indices
            if selected:
                data = data.iloc[selected, :]
            update_stats(data, t1, t2)

        source.on_change('selected', selection_change)

The code never prints 'lol'.

**Comment by bryevdv** [comment]
This example is tested and run regularly. How did your run this Bokeh application? It had to be run e.g. `bokeh serve stocks.py` and not just `python stocks.py`

**Comment by ahmetbaglan** [comment]
Thanks for very quick reply. Yes I am running with `bokeh serve stocks.py`.

Also can you ckech the link in the gallery. I think it doesn't work either. 
https://demo.bokehplots.com/apps/stocks

Thanks

**Comment by ahmetbaglan** [comment]
I just tried it with version 0.12.6, 

Than it prints 'lol' but throws the following ERROR 

ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): AttributeError("'PropertyValueDict' object has no attribute 'indices'",)

I believe this is something with the version 1.0.4

**Comment by bryevdv** [comment]
The code in the example is wrong. I'm not sure when/how it got reverted to the old/bad way. The correct way to do this from version 1.0 forward is:
```
source.selected.on_change('indices', selection_change)
```

Would you like to make a PR to fix things?

**Comment by ahmetbaglan** [comment]
Yes,  it is working now! That was the line to change. 

Thank you so much : )

**Comment by ahmetbaglan** [comment]
Maybe I should leave the issue open so that you can change the example lin

**Comment by bryevdv** [comment]
@ahmetbaglan would you like to submit a Pull Request to update the file? It can even be done directly from the GH web UI (just make sure there is no trailing whitespace or our linter will complain)

**Comment by ahmetbaglan** [comment]
I just did :)

Have a nice day.
