### ISSUE TITLE
Incorrect Layout with column of Div's (with 1.1dev2/3)

### ISSUE THREAD

**Issue by mgagcode** [bokeh/bokeh#8637]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
python 3.6
bokeh 1.1dev3 (also observed problem with 1.1dev2)
bokeh css/js 1.0.4
jquery 3.1.0
Google Chrome Version 72.0.3626.96 (Official Build) (64-bit)
FireFox 65.0 (64-bit)
Host OS: Ubuntu 18.04

#### Description of expected behavior and the observed behavior
Expect non-overlapping column of Div sections.
Observed that the second row is overlapping the first row.
The issue does not happen in the last released bokeh.  I did not try 1.1dev1. 
Issue occurs in Google Chrome and FireFox.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from flask import Flask

from bokeh.layouts import layout, row
from bokeh.models.layouts import Spacer
from bokeh.models.widgets import Div
from bokeh.models.widgets.buttons import Button
from bokeh.embed import components

from dominate.tags import *
import dominate
from dominate.util import raw

app = Flask(__name__)

@app.route('/')
def index():
    d = dominate.document(title="test")
    with d.head:
        bokeh_version = '1.0.4'
        link(href="https://cdn.pydata.org/bokeh/release/bokeh-{bokeh_version}.min.css".format(
            bokeh_version=bokeh_version), rel="stylesheet", type="text/css")
        script(src="https://cdn.pydata.org/bokeh/release/bokeh-{bokeh_version}.min.js".format(bokeh_version=bokeh_version))
        link(href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-{bokeh_version}.min.css".format(
            bokeh_version=bokeh_version), rel="stylesheet", type="text/css")
        script(src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-{bokeh_version}.min.js".format(bokeh_version=bokeh_version))
        link(href="https://cdn.pydata.org/bokeh/release/bokeh-tables-{bokeh_version}.min.css".format(
            bokeh_version=bokeh_version), rel="stylesheet", type="text/css")
        script(src="https://cdn.pydata.org/bokeh/release/bokeh-tables-{bokeh_version}.min.js".format(bokeh_version=bokeh_version))

        script(src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js")
        meta(charset="UTF-8")

    doc_layout = layout()
    b_login = Button(label="LOGIN", width=50)
    doc_layout.children.append(row(Div(text="""<h1>{}</h1>""".format("title"), width=100), Spacer(width=100), b_login))
    doc_layout.children.append(Div(text="""Version: {}""".format("1.0.1"), width=200))
    doc_layout.children.append(Div(text="message", width=600))

    _script, _div = components(doc_layout)
    d.body += raw(_script)
    d.body += raw(_div)
    return "{}".format(d)

app.run(host="0.0.0.0", port=6800, debug=False)
```

#### Stack traceback and/or browser JavaScript console output
Google Chrome console output:
```
bokeh-1.0.4.min.js:31 [bokeh] JS/Python version mismatch
P.from_json @ bokeh-1.0.4.min.js:31
bokeh-1.0.4.min.js:31 [bokeh] Library versions: JS (1.0.4) / Python (1.1.0dev3)
P.from_json @ bokeh-1.0.4.min.js:31
```
#### Screenshots or screencasts of the bug in action
![screenshot from 2019-02-09 13-38-20](https://user-images.githubusercontent.com/40646488/52524898-0dbd9b80-2c70-11e9-82f7-b1c16575211a.png)

**Comment by mattpap** [comment]
> bokeh-1.0.4.min.js:31 [bokeh] Library versions: JS (1.0.4) / Python (1.1.0dev3)

You are mixing different versions of bokeh and bokehjs. That's not going to give good results. You will have to use either dev CDN resources (for a dev release) or build bokehjs locally otherwise.

**Comment by mgagcode** [comment]
Is it documented somewhere what the link is?  It should be documented here,

    https://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

But I don't see it...  I believe its something like this,

    https://cdn.pydata.org/bokeh/dev/bokeh-1.1dev3.min.css

**Comment by mgagcode** [comment]
The link is,

https://cdn.pydata.org/bokeh/dev/bokeh-1.1.0dev3.min.css

And that did fix this bug.  Will Close.
