### ISSUE TITLE
manual_grid layout example has lost it's core functionality in layout PR

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8642]
The layout example `example/howto/layouts/manual_grid.py` used to end like this

```python
paragraph = Paragraph(text="We build up a grid plot manually. Try changing the mode yourself.")
MODE = 'fixed'
widgets = widgetbox([paragraph], sizing_mode=MODE)
row_1 = row([spacer_1, p1, spacer_2], sizing_mode=MODE)
row_2 = row([p2, p3, p4], sizing_mode=MODE)
layout = column([widgets, row_1, row_2], sizing_mode=MODE)

show(layout)
```

The point was to provide an example that would reformat itself under the different sizing modes for users to test out the effect of these different modes.

The new layout syntax is much cleaner, and I'm excited to see that the end now looks like this:

```python
paragraph = Paragraph(text="We build up a grid plot manually. Try changing the mode yourself.")

grid = GridBox(children=[(p1, 0, 1), (p2, 1, 0), (p3, 1, 1), (p4, 1, 2)])
layout = column([paragraph, grid])

show(layout)
```

But the core functionality of this example in accepting different sizing modes has been removed. It should be restored.

**Comment by bryevdv** [comment]
But to "try it out" the user had to edit a file, and re-run code. This is a high hurdle and some people just might be viewing the result and not even have the code to run at all (e.g a gallery). I never liked that text, for this reason. I'd rather expand or make similar examples to `plotting/file/sizing_mode.py` which have a live drop down to set different sizing modes and see immediately how things change

**Comment by bryevdv** [comment]
Or perhaps other way of putting it, I would be happy to have the original text as a comment in the source code, where it is clear that the necessary change is a change in the code. Having it be actual text in the HTML page is confusing ("where/how do I change it??")

**Comment by birdsarah** [comment]
Switching it to an app with a live dropdown would be so much better. I'm pretty sure that didn't work / didn't work well when I made the original example.
