### ISSUE TITLE
dashboard.py example not behaving as expected after the layout PR

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8643]
``examples/howto/layouts/dashboard.py``

Running from master locally, I get this.

![screenshot from 2019-02-11 09-49-39](https://user-images.githubusercontent.com/1796208/52574694-70cf3f80-2de2-11e9-8a69-68af9850d5cf.png)

I see the following problems:
* The axes edges of the plots are not aligned on the left or right sides.
* The sliders should have more space to the left
* The sliders  should fill the space alotted to them.

Note that this example was explicitly coded up for the last layout PR to be challenging with the left title, the missing toolbar on the right middle plot, and the 1-2-3 layout, and the sliders.

**Comment by birdsarah** [comment]
Here's a screenshot from 1.0.4

![screenshot from 2019-02-11 09-58-19](https://user-images.githubusercontent.com/1796208/52575339-a4f73000-2de3-11e9-88b1-4ae553240364.png)

The axes are aligned, but the sliders do not look great either. I misremembered that bit :D
I think they should be ideally, left aligned with the axes. Although that may be out of scope.

I'm indifferent about stretching them.

**Comment by bryevdv** [comment]
@birdsarah the issue with some axis alignments is known, but I am not sure there is an issue so this can serve as a good one for tracking it. AFAIK @mattpap has a plan or idea for how to restore that but I am not sure how much of a lift it will be.

**Comment by mattpap** [comment]
Lack of axis alignment is a side effect of lack of grid spans in the new layout. This will be implemented at some point. Sliders are too short, but that's a known issue. Everything is tracked in issue #8084.

**Comment by bryevdv** [comment]
Just FYI this things look different as of 1.1.0dev9:

<img width="1341" alt="screen shot 2019-03-07 at 12 13 36 pm" src="https://user-images.githubusercontent.com/1078448/53986263-81699180-40d2-11e9-8441-b1484a3e2d03.png">

**Comment by bryevdv** [comment]
If we are advocating for using grids to achieve this now, we should update this to look better with newest guidance.

**Comment by bryevdv** [comment]
@mattpap This diff gives what I would consider a good result:
```
diff --git a/examples/howto/layouts/dashboard.py b/examples/howto/layouts/dashboard.py
index 7613e735b..1ddac2811 100644
--- a/examples/howto/layouts/dashboard.py
+++ b/examples/howto/layouts/dashboard.py
@@ -1,6 +1,6 @@
 import numpy as np

-from bokeh.layouts import grid, column
+from bokeh.layouts import grid
 from bokeh.models import CustomJS, Slider, ColumnDataSource
 from bokeh.plotting import figure, output_file, show

@@ -39,7 +39,7 @@ def slider():

     plot = figure(
         y_range=(-10, 10), tools='', toolbar_location=None,
-        title="Sliders example")
+        title="Sliders example", plot_height=250)
     plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)

     callback = CustomJS(args=dict(source=source), code="""
@@ -68,7 +68,9 @@ def slider():
     offset_slider = Slider(start=-5, end=5, value=0, step=.1, title="Offset", callback=callback)
     callback.args["offset"] = offset_slider

-    widgets = column(amp_slider, freq_slider, phase_slider, offset_slider)
+    widgets = [amp_slider, freq_slider, phase_slider, offset_slider]
+    for x in widgets + [plot]:
+        x.sizing_mode = "stretch_width"
     return [widgets, plot]
```

Is there a better/cleaner way to express this? The main thing is that everything is stretch_both except the middle row (otherwise the sliders vertical space expands way too much).

**Comment by bryevdv** [comment]
Here is the nice result (which resizes well and smoothly):

<img width="1228" alt="Screen Shot 2019-04-04 at 9 07 19 PM" src="https://user-images.githubusercontent.com/1078448/55603079-b5f65a80-571d-11e9-8845-e28fbfed45dc.png">

I think it'd be nicer id the sliders matched up with the axes but can live withotu

**Comment by mattpap** [comment]
> I think it'd be nicer id the sliders matched up with the axes but can live without.

That never worked. However, this can be implemented with the new layout, because because "axis alignment" can work with arbitrary lines.

**Comment by mattpap** [comment]
Just to note. This example can be made to work as expected, however there are at least two bugs that prevent the existing setup doing so. I'm working on a fix.
