### ISSUE TITLE
Use cross-browser compatible CSS for testing

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8645]
Detected during #8636 

Running on OSX, differences pop up frequently (but not all the time):

```
tests/test_examples.py::test_file_examples[/Users/bryanv/work/bokeh/examples/models/file/anscombe.py-example0-config0]
[INFO] Example run in 0.973s
[INFO] Example rendered in 1.180s
[JS] {log} file:///Users/bryanv/work/bokeh/bokeh/server/static/js/bokeh.js:3481:21 [bokeh] setting log level to: 'info'
[JS] {info} file:///Users/bryanv/work/bokeh/bokeh/server/static/js/bokeh.js:7592:34 [bokeh] document idle at 92 ms
[FAIL] BASELINE DOESN'T MATCH (make sure to update baselines before running tests):
[FAIL] diff --git a/tests/baselines/examples/models/file/anscombe b/tests/baselines/examples/models/file/anscombe
[FAIL] index b6f4e621e..6d0b5a762 100644
[FAIL] --- a/tests/baselines/examples/models/file/anscombe
[FAIL] +++ b/tests/baselines/examples/models/file/anscombe
[FAIL] @@ -1,6 +1,6 @@
[FAIL] -Column bbox=[0, 0, 984, 871]
[FAIL] -  Div bbox=[5, 5, 974, 61]
[FAIL] -  GridBox bbox=[0, 71, 984, 800]
[FAIL] +Column bbox=[0, 0, 984, 923]
[FAIL] +  Div bbox=[5, 5, 974, 65]
[FAIL] +  GridBox bbox=[0, 123, 800, 800]
[FAIL]      Plot bbox=[0, 0, 400, 400]
[FAIL]        LinearAxis bbox=[24, 376, 371, 24]
[FAIL]        LinearAxis bbox=[0, 29, 24, 347]
[WARN] generated and reference images differ: 51.23% of pixels
```

Chrome was run with
```
/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --headless --remote-debugging-port=9222 --disable-gpu https://chromium.org
```

Version : `Google Chrome 69.0.3489.0 canary`

And tests were run with:
```
py.test -s -v -m examples --tb line --diff-ref origin/master -k examples
```

**Comment by bryevdv** [comment]
I suppose the first thing to check is whether this might be due to a difference in chrome version. Otherwise @mattpap please let me know what diagnostic information you'd like me to collect (and possibly how)

**Comment by mattpap** [comment]
I would start with version number. I'm using 72, but I'm not sure what Travis CI uses (it says stable, which should be 72 as well). Though I doubt this is the reason. Another useful thing would be to see test output for entire test suite. At this point I'm not sure if it's only Div and Select causing problems, widgets in general or more.

**Comment by mattpap** [comment]
> `--disable-gpu`

This isn't necessary anymore (unless you've been experiencing any issues running without it).

**Comment by mattpap** [comment]
Can you try `node make test:integration`? This test includes all widgets and works for me on Windows with Chrome 72. I'm trying to run examples' tests on Windows as well, but that fails with a bunch of different errors (bad paths, unicode, etc.), so it may take awhile to get it working.

**Comment by mattpap** [comment]
Examples' tests on Windows give one failure `integration/layout/grid_axis_alignment_no_toolbar`, but that example is totally broken and it doesn't seem to be layout related. Hopefully upgrading Chrome on OSX will fix other failures. If that's the case, we will have to make sure to always use Chrome stable for baseline (and image diff) testing.

**Comment by bryevdv** [comment]
@mattpap I re-ran things locally with Chrome 72, there are about 45 failures. `examples.out` and `sphinx.out` are here:

e6c97431cd5bd2092d4417a9efaf76da

**Comment by bryevdv** [comment]
Just realized the GH diff of baselines is probably easier to digest:


[baseline.txt](https://github.com/bokeh/bokeh/files/2857432/baseline.txt)

**Comment by mattpap** [comment]
That's just great. Well, I will finish PR #8646 and then try figure out what's going on here.

**Comment by mattpap** [comment]
@bryevdv, can you apply this patch and show me generated baseline for models/file/widgets? Maybe I will be able to spot some differences in the computed CSS.
```diff
diff --git a/bokehjs/src/lib/models/layouts/layout_dom.ts b/bokehjs/src/lib/models/layouts/layout_dom.ts
index 3f2b490..c543646 100644
--- a/bokehjs/src/lib/models/layouts/layout_dom.ts
+++ b/bokehjs/src/lib/models/layouts/layout_dom.ts
@@ -305,9 +305,17 @@ export abstract class LayoutDOMView extends DOMView {
   }
 
   serializable_state(): {[key: string]: unknown} {
+    const style: {[key: string]: string} = {}
+    const computed = getComputedStyle(this.el)
+    for (let i = 0; i < computed.length; i++) {
+      const property = computed[i]
+      style[property] = computed.getPropertyValue(property)
+    }
+
     return {
       ...super.serializable_state(),
       bbox: this.layout.bbox.rect,
+      style,
       children: this.child_views.map((child) => child.serializable_state()),
     }
   }
diff --git a/tests/test_examples.py b/tests/test_examples.py
index dc6cdd2..8c15c67 100644
--- a/tests/test_examples.py
+++ b/tests/test_examples.py
@@ -124,12 +124,15 @@ def _create_baseline(items):
             type = item["type"]
 
             bbox = item.get("bbox", None)
+            style = item.get("style", None)
             children = item.get("children", [])
 
             line = "%s%s" % ("  "*level, type)
 
             if bbox is not None:
                 line += " bbox=[%s, %s, %s, %s]" % (bbox["left"], bbox["top"], bbox["width"], bbox["height"])
+            if style is not None:
+                line += " style=%s" % style
 
             line += "\n"
 
```

**Comment by mattpap** [comment]
Actually, as I think this is a difference in font, can you open models/file/widgets.html in Chrome and inspect the select widget (second column, third item) and check the computed font-family ("Computed" tab in CSS inspector; use filter to find font-family). Linux and Windows agree on Arial. Unfortunately `getComputedStyle()` is unable to resolve the actual font being used.

**Comment by mattpap** [comment]
A cursory google search reveals that Helvetica Neue should be the default on OSX (given our CSS). I will need to figure out how to force a common font (I suppose Arial) without modifying CSS and examples.

**Comment by bryevdv** [comment]
Ah, sure a different default would make a tidy explanation. Do you still need me to run with that patch?

**Comment by mattpap** [comment]
No, it actually wouldn't be helpful here after all. However, if you could verify what font is being used (as explained in my earlier comment).

**Comment by bryevdv** [comment]
@mattpap seems a bit confusing:

<img width="548" alt="screen shot 2019-02-12 at 16 52 38" src="https://user-images.githubusercontent.com/1078448/52678487-aa896e80-2ee6-11e9-99b0-a1ad66d98798.png">

**Comment by bryevdv** [comment]
Possibly relevant: https://infinnie.github.io/blog/2017/systemui.html

**Comment by mattpap** [comment]
This is unreasonable, but what to expect from web technologies. However, I think the problem is actually with font-size, due to `pt` units that we use in our CSS. On linux and windows font-size == 13.3333px.

**Comment by mattpap** [comment]
btw. Safari is one of few browser that implement this and enable this by default (system-ui).

**Comment by bryevdv** [comment]
@mattpap correct, that screenshot is from chrome. 

FWIW some sites say simply to have per-platform profiles, which seems unpleasant especially hard to update or add new ones. Perhaps we simply only run these tests on linux and skip them elsewhere. Alternatively we could make these tests run in docker....

**Comment by mattpap** [comment]
So actually I noticed that on linux and windows user agent styles also overwrite ours. This is because our styles are implemented incorrectly, allowing CSS cascade to prefer UA styles over ours. I fixed this in PR #8652.

**Comment by mattpap** [comment]
For future reference, Chrome's user agent styles:

https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css

**Comment by mattpap** [comment]
@bryevdv, can you try once again if you have a chance (`models/file/widgets` and `node make test:integration`)? With the new HTML measurement scheme maybe there will be some improvement.

**Comment by mattpap** [comment]
This issue isn't relevant anymore after PR #10101. However, I actually figured out the root cause of this issue in the new devtools testing framework of bokehjs. The problem was with inconsistent fonts and inconsistent font rendering settings of headless chrome across platforms.
