### ISSUE TITLE
DeprecationWarning: the way of importing the ABCs will stop working in python 3.8

### ISSUE THREAD

**Issue by elhossary** [bokeh/bokeh#8649]
bokeh\plotting\helpers.py:21: DeprecationWarning: Using or importing the ABCs from
'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

**Comment by mattpap** [comment]
What version of bokeh this refers to? As far I can tell this was fixed in `master` (PR #8631).

**Comment by elhossary** [comment]
I am using 1.0.4.
each time I run my tests in pycharm, I get this warning.
bokeh\plotting\helpers.py     LINE 21

**Comment by bryevdv** [comment]
It is fixed in master but there's not been a release yet. Please note that even after our fix, this still comes up in tests because some upstream dependencies have not fixed it yet.
