### ISSUE TITLE
grid_axis_alignment_no_toolbar is broken in Windows (32-bit)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#8650]
`examples/integration/layout/grid_axis_alignment_no_toolbar`:

![image](https://user-images.githubusercontent.com/27475/52644650-81191480-2edf-11e9-9905-eb5b000448f1.png)

All axes should be in 0 to 10, 10^3, 10^6, 10^9 ranges. All major browsers are affected the same way. I suspect this may be due to 32-bit system architecture. It would be good if someone with 64-bit windows could run this example for comparison.

**Comment by mattpap** [comment]
Looking at those glyphs, it's pretty clear to me that this is an overflow-kind issue.

**Comment by mattpap** [comment]
This is a problem with numpy. The code uses `10**9 * np.arange(10)` which overflows, because `dtype` defaults to platform `int` which is 32-bit in size.

**Comment by bryevdv** [comment]
The code in our example uses that? Seems like an easy fix to make the type explicit then
