### ISSUE TITLE
Text wrapping in Div after layout PR

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8654]
On current master after the layout PR the sizing behavior for ``Div`` is hugely improved however there is one new behavior which is quite frustrating. By default it seems the Div now wraps any text in it depending on the length of the string. Here's a reproducible example of the issue:

```python 
tinput = TextInput(value='Some text')
div = Div(text='Some Text')

tinput.js_link('value', div, 'text')

Row(children=[tinput, div])
```

![div_text](https://user-images.githubusercontent.com/1550771/52741709-ec411480-2fcd-11e9-9e6a-bd9e8d17da85.gif)

Since Divs can be quite helpful for adding labels, titles and short snippets of instructions this can be quite annoying. Even if there was a convenient workaround here that would be very helpful.

**Comment by mattpap** [comment]
If you want a label, I would start with `Div(..., style={"white-space": "nowrap"})`. Alternatively fixed width would be useful, to avoid the widget to fit into the available space (this behavior may be a bug, I need to look closer at this).

**Comment by philippjfr** [comment]
>Div(..., style={"white-space": "nowrap"})

Thanks, that's a viable workaround for now. Specifying a fixed width does not eliminate the issue unfortunately.
