### ISSUE TITLE
Custom Widget in doc strange display in 1.1.0dev6

### ISSUE THREAD

**Issue by xavArtley** [bokeh/bokeh#8680]
I was looking at custom examples in doc for version 1.1.0
https://bokeh.pydata.org/en/dev/docs/user_guide/extensions_gallery/

and I noticed some difference in the Custom Widget example : 
 - 1.0.4 :
 
![image](https://user-images.githubusercontent.com/18531147/53246996-79f9bf80-36b2-11e9-879b-4213dfba286e.png)

 - 1.1.0dev6 :

![image](https://user-images.githubusercontent.com/18531147/53247030-97c72480-36b2-11e9-8e77-7f7861d4f0aa.png)

**Comment by mattpap** [comment]
Also needs update after PR #8689.

**Comment by mattpap** [comment]
`custom/font-awesome` needs an update as well.
