### ISSUE TITLE
Allow at least partial alignment of fixed sized frames

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8684]
The new ``frame_width`` and ``frame_height`` properties generally work pretty well however they seem to be at least partially ignored in a Row, Column or GridBox layout. This occurs specifically when one plot in the layout has a title and another do not.

Here is a reproducible example:

```python
from bokeh.plotting import figure
from bokeh.layouts import Row

f1 = figure(frame_width=200, frame_height=200, title='A')
f1.scatter([0, 1, 2], [1, 2, 3])

f2 = figure(frame_width=200, frame_height=200)
f2.scatter([0, 1, 2], [1, 2, 3])

Row(children=[f1, f2])
```

![screen shot 2019-02-24 at 2 29 22 am](https://user-images.githubusercontent.com/1550771/53294303-05bb3b00-37dc-11e9-8142-fbb022c2b969.png)

If the title is removed both plots correctly respect the specified size, even if a colorbar is added for example:

![screen shot 2019-02-24 at 2 30 18 am](https://user-images.githubusercontent.com/1550771/53294307-27b4bd80-37dc-11e9-950b-fa575b21bbe0.png)

**Comment by mattpap** [comment]
Currently grid doesn't respect fixed inner box dimensions at all. I fill fix that, but the result will be as follows:

![image](https://user-images.githubusercontent.com/27475/53749959-db870e80-3ea8-11e9-89ae-e27796c2cbf2.png)

Currently inner alignment is computed after layout computed outer dimensions, and inner dimensions can't affect outer dimensions. This can be improved, especially to handle more advanced scenarios like inner box aspect management, but that's a bigger chunk of work for the future.

**Comment by mattpap** [comment]
I suppose with `height_policy="fit"` (or `"max"`) or `"fixed"` with sufficiently large `height`, there could be room for single axis alignment.
