### ISSUE TITLE
Problem to set Rollover argument for stream 

### ISSUE THREAD

**Issue by johnDavis1365** [bokeh/bokeh#8690]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 1.0.4
Python3
OS ---> Windows10
#### Description of expected behavior and the observed behavior
Specifying the rollover to the value less than 10 don't have any affect.
For instance if you set the rollover value to 6 on next call you will see 10 points on the graph.
#### Complete, minimal, self-contained example code that reproduces the issue
Here is part of my code.
```
# code goes here between backticks
df1 = dataFrame.loc[(dataFrame['x'] >= float(self.dropdownRSS.value))]
            newDataFrame = ColumnDataSource(df1)
            sizeOfDataFrame = int((len(df1.index)))
            self.source.stream(newDataFrame.data, rollover=sizeOfDataFrame)
```

**Comment by bryevdv** [comment]
@johnDavis1365 part of code will not suffice, we must be able to reproduce a problem before we can investigate it. We need a *complete* script to reproduce, including any necessary data or files, and detailed instructions. Otherwise we will have to close this as `norepro`

**Comment by johnDavis1365** [comment]
@bryevdv Thank you for your respond.
I am not able to upload my code here since it has lots of dependencies as I am receiving data packets through socket and stream data using source.stream.
Even by using simple code that uses the source.stream you may be able to reproduce problem. 
Just set the rollover value < 10 and if i understand properly from the rollover description, it will define maximum column size to be graph.
Thanks,

**Comment by bryevdv** [comment]
@johndavis1365 if it can be reproduced with a simple code, *provide that code*. Asking core devs to speculate and guess and try to generate reproducers is a huge burden. OSS requires collaboration from users.

**Comment by johnDavis1365** [comment]
Ok sure. I understand your concern. I'll look for it and will update this.
Thank you Bryan.

**Comment by bryevdv** [comment]
Going to go ahead and close as `norepro` We can certainly re-open if an MRE becomes available.
