### ISSUE TITLE
HoverTool(mode='vline') and Zoom

### ISSUE THREAD

**Issue by mayl** [bokeh/bokeh#8705]
I've noticed that with "large-ish" (6 columns, 253k points each) there seems to be an interaction between having the `HoverTool(mode='vline')` on and being able to zoom.  If the `HoverTool` is toggled on in the browser and `mode='vline'` is set, when I try to zoom Bokeh will latch up and never recover.  If the `HoverTool` is toggled off I don't hit this issue.  If the dataset is "small enough" I also don't seem to hit the issue. 

My data is a set of 6 temperature time series read from a tab seperated text file.  My intent is to plot all 6 sensor readings as line-graphs with a vertical cursor with hover tooltips that display the data for each line.  The below achieves that for me, but results in the broken zooming behavior.  Is there a better way to write this to avoid the broken zooming behavior?

```python
import numpy as np
import bokeh.plotting as plt
import bokeh.tools as tools
from bokeh.palettes import Set1_9 as palatte
import itertools

import_data= np.loadtxt("data.dat", delimiter='\t').transpose()
time = import_data[0]
data = import_data[1:]
colors = itertools.cycle(palatte)

plt.output_file("temperatures.html", mode='inline')
p = plt.figure(title="Temperature Data", x_axis_label="time", y_axis_label="Temperature")

for idx, line, color in zip(itertools.count(0), data, colors):
    name="sensor{}".format(idx)
    p.line(time, line, color=color, name=name, legend=name)

p.add_tools( tools.HoverTool(mode='vline', tooltips="$name: @y") )
p.add_tools( tools.CrosshairTool(dimensions="height"))

plt.show(p)
```

**Comment by bryevdv** [comment]
@mayl in order to investigate things we must be able to actually run code and reproduce the problem. Please provide a `data.dat` file (or update the MRE to generate synthetic data, etc)

**Comment by bryevdv** [comment]
Closing as `norepro`. Can reopen if a self-contained, runnable MRE is provided. Otherwise, offhand, ~1.5M points is relatively alot for Bokeh, given it's overhead to support high interactivity. Consider using Holoviews+Datashader to generate Bokeh plots that work for millions/billions of points.
