### ISSUE TITLE
Add support for spans do grid layout

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#8710]
This is a follow up on issue #8084. Technically speaking this is a regression since the old layout. This is needed to restore functionality of `examples/app/spectrogram`, etc.

**Comment by bryevdv** [comment]
Just out of curiousity, how big a lift do you think this is?

**Comment by mattpap** [comment]
I'm not sure, because I need to figure out how to measure track sizes (under all supported sizing policies), implement new internal data structures that will allow spanning layouts across grid cells, adjust axis alignment algorithm, etc. Definitively it's a bigger chunk of work.

**Comment by bryevdv** [comment]
Is there anything simple but dumb (and unobtrusive for later) that could be done to cover the 80% case? i.e. could we set min border for top and bottom to be the max value of every plot in a row? And similarly min border left of every plot in a column? I.e. punt on nested cases for now until you can work out a general solution, but do enough to get basic and common cases looking more like they used to?

It will be hard toargue this is not a breaking change. The other alternative is to push 1.1 back which I am fine with but I am not sure how that would impact @philippjfr @jlstevens @jbednar Perhaps they could use 1.1 rc builds in client work for now?

**Comment by philippjfr** [comment]
>It will be hard to argue this is not a breaking change. The other alternative is to push 1.1 back which I am fine with personally, but I am not sure how that would impact @philippjfr @jlstevens @jbednar Perhaps they could use 1.1 rc builds in client work for now?

We are at least a 1.5 weeks away from being ready to push out new releases for our stuff so I'd be happy to postpone for that long. Does that seem like sufficient time? A new dev/rc release would be sufficient for the time being.

**Comment by philippjfr** [comment]
>adjust axis alignment algorithm

Will that intersect at all with the axis alignment issue for fixed inner dimensions or is that a whole other chunk of work?

**Comment by mattpap** [comment]
> Will that intersect at all with the axis alignment issue for fixed inner dimensions (...)

To some extent yes, depending on the layout. I will keep that issue in mind fixing this one.
