### ISSUE TITLE
Displaying plot in notebook quickly after output_notebook raises JS error

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8713]
Since https://github.com/bokeh/bokeh/pull/8682 was merged displaying a plot in a notebook environment raises a JS error if it is run before ``output_notebook`` has had time to initialize Bokeh properly. A simple way to reproduce this is by simply putting ``output_notebook`` and ``show`` in the same cell in a clean notebook and running it:

```python
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
from bokeh.resources import INLINE

output_notebook(resources=INLINE)

p = figure()
p.circle([1, 2, 3], [1, 2, 3])

show(p)
```

>Javascript error adding output!
>TypeError: Cannot read property 'set_log_level' of undefined
>See your browser Javascript console for more details.

**Comment by mattpap** [comment]
I think this is specific to `INLINE` resources. I tested PR #8682 with server resources.
