### ISSUE TITLE
BAD_EXTRA_RANGE_NAME validation can be incorrect

### ISSUE THREAD

**Issue by poldavezac** [bokeh/bokeh#8723]
The following will produce an incorrect BAD_EXTRA_RANGE_NAME
```
a = figure()
b = figure()
b.extra_x_range = {'myx': Range1d(start = 0, end = 1)}
b.circle(..., x_range_name = 'myx')

check_integrity(a) #--> ok
check_integrity(b) #--> ok

c = CustomJS(code = "", args = {"b": b})
a.x_range.callback  = c

check_integrity(a) # --> ko
```
The reason is that in the last check_integrity:

1. the circle glyph belonging to "b" is known to "a" through its "a.x_range.callback". 
2. the _check_bad_extra_range_names uses the extra ranges from "a" rather than "b".

It seems that in _check_bad_extra_range_names, one should only iterate over the layout's renderers.

**Comment by bryevdv** [comment]
@poldavezac Can you provide a complete real example of how this situation could arise in actual practice? i.e. without calling `check_integrity` manually yourself? Bokeh serializes entire documents at a time, not individual models, so I'd like to understand how this could affect real-world usage before expending effort on changing it.

**Comment by poldavezac** [comment]
The manual calling was purely for facilitating testing. The problem occurs automatically when the document is loaded. In my real-world case, I could not load a document comprising 2 figures (a time series and it's histogram), both sharing their y-axis range and with an extra y-axis slaved to the others through a callback. 

As far as investigations go, I do think I pinpointed the problem : the check iterates over all references rather than only the figure's layout. It ends up looking for extra ranges belonging to another figure. I personally monkeypatched bokeh that way and it works. I could be missing something though.

**Comment by bryevdv** [comment]
@poldavezac would you like to contribute your local solution as a PR? That would greatly accelerate getting a change into the project.

**Comment by jxrossel** [comment]
In 1.3.4, this error is still triggered incorrectly in the following case:

```
from bokeh.models import Range1d, LinearAxis, Legend
from bokeh.layouts import gridplot
from bokeh.embed import components

def plot_on_extra( p, legs ):
    """
    create twin axes and plot something on it
    """
    
    # init
    extra_range_name = 'extra'
    y_range_name = dict( y_range_name=extra_range_name )
    
    p.extra_y_ranges = { extra_range_name: Range1d( 0, 2 ) }    
    p.add_layout( LinearAxis( **y_range_name ), 'right' )
    lright = p.line( [0,2], [0,2], **y_range_name )
    legs.append( ( '1-extra', [ lright ] ) )

# inits
legs = []
extra_on_2nd_not_1st = True

p1 = figure()
l1 = p1.line( [0,3], [0,3] )
legs.append( ( '1', [ l1 ] ) )

if not extra_on_2nd_not_1st:
    # Doesn't create the bug
    plot_on_extra( p1, legs )

p2 = figure()
l2 = p2.line( [ 0,1], [0,1] )
legs.append( ( '2', [ l2 ] ) )

if extra_on_2nd_not_1st:
    # Creates the bug, but only if (1) Legend, (2) extra not defined on 1st figure
    plot_on_extra( p2, legs )

# Necessary to create the bug. NB: using [legs[0]] would not create it
legend = Legend( items=legs, location=(10, 0) )
p1.add_layout( legend, 'right' )

model = gridplot( [ p1, p2 ], ncols=1, plot_width=500 )
script, div = components( model )
```

Note: to get the bug, the extra axis must be on the 2nd figure (only) and the legend must cover both figures

**Comment by jxrossel** [comment]
Ok, maybe it's related to the unsupported shared legend (?): https://github.com/bokeh/bokeh/issues/7607
