### ISSUE TITLE
Tabs width set on width of contents - truncating tabs

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#8726]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
```
Python version      :  3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
IPython version     :  7.1.1
Tornado version     :  5.1.1
Bokeh version       :  1.1.0dev8
BokehJS static path :  /Users/jsignell/conda/envs/panel-dev/lib/python3.6/site-packages/bokeh/server/static
node.js version     :  v7.10.0
npm version         :  4.2.0
```
#### Description of expected behavior and the observed behavior
The width of the tabs seems to be set based on the width of the item inside the tab without taking the width of the title into account. The result is a truncated tabs object where you can't click on the second tab ( because it isn't visible). 

I originally raised this as https://github.com/pyviz/panel/issues/284

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models.widgets import Panel, Tabs, Button
from bokeh.io import output_notebook, show
from bokeh.plotting import figure

output_notebook()

tab1 = Panel(child=Button(label='+', width=30), title="This is a long title")
tab2 = Panel(child=Button(label='-', width=30), title="This is another long title")
tabs = Tabs(tabs=[ tab1, tab2 ])

show(tabs)

```
#### Screenshots or screencasts of the bug in action
<img width="814" alt="screen shot 2019-03-07 at 9 20 29 am" src="https://user-images.githubusercontent.com/4806877/53962962-4d827200-40ba-11e9-8bae-e7297706c9c5.png">

**Comment by mattpap** [comment]
> Tabs width set on width of contents

This is by design, however, minimum width should be set, so that at least one tab is fully visible.

**Comment by jsignell** [comment]
The width needs to be large enough to see the title of every tab. If possible the titles should have a max_width set to 100%/n_tabs and they should wrap or overflow.

**Comment by jbednar** [comment]
Seems like the overall tabs width should be set to max(width_of_current_tab_contents, total_width_of_tab_titles).

**Comment by mattpap** [comment]
> max(width_of_current_tab_contents, total_width_of_tab_titles)

This will look very bad if there are many tabs. A good example is https://github.com/bokeh/bokeh/blob/master/examples/models/file/glyphs.py.

**Comment by jsignell** [comment]
I think it is better for things to look bad than to be non-functional. In that example there are tabs that are not visible. That is why I am proposing truncating tab title width.

<img width="632" alt="screen shot 2019-03-07 at 10 00 05 am" src="https://user-images.githubusercontent.com/4806877/53965814-e071db00-40bf-11e9-8d4a-1dec1b5b4f03.png">

**Comment by jbednar** [comment]
> This will look very bad if there are many tabs. 

How are people to use many tabs, if they aren't visible?

**Comment by mattpap** [comment]
@jsignell, what version of bokeh are you testing? This isn't `master`.

**Comment by jsignell** [comment]
No it's 1.1.0dev8.

**Comment by mattpap** [comment]
Tabs' behavior changed since then. Always report your issues off `master`.

**Comment by jsignell** [comment]
I did list the version at the top, but you are right. I am building master now.

**Comment by mattpap** [comment]
> Bokeh version       :  1.1.0dev8

Well, you indicated that you use an obsolete version. My assumption is that any member of the broader dev team always reports issues on top of `master`, to avoid problems like in this issue.

> node.js version     :  v7.10.0
> npm version         :  4.2.0

Speaking about versions. This software is years old and not supported. To build bokehjs you will have to upgrade this.

**Comment by jsignell** [comment]
```
Python version      :  3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
IPython version     :  7.2.0
Tornado version     :  5.1.1
Bokeh version       :  1.1.0dev9+2.g1138433
BokehJS static path :  /Users/jsignell/conda/envs/bokeh-dev/lib/python3.6/site-packages/bokeh-1.1.0.dev9+2.g1138433-py3.6.egg/bokeh/server/static
node.js version     :  v11.6.0
npm version         :  6.5.0
```

Ok so you have added the right and left scroll-like behavior. It still gets truncated to the point where you can't see a tab title for small widths. 

<img width="775" alt="screen shot 2019-03-07 at 10 19 40 am" src="https://user-images.githubusercontent.com/4806877/53967110-90484800-40c2-11e9-9050-8fe52122907e.png">

**Comment by bryevdv** [comment]
(Just an FYI unless you specify `BOKEH_RESOURCES=inline` (or pass an arg to `output_notebook` for inline resources) then the above is loading `1.1.0dev9` BokehJS from CDN. In this specific instance I think that also happens to be master, but in general it's not. I pretty much always use `BOKEH_RESOURCES=inline` when working on master to make sure I am using local resources.)

Are there examples of other art we can compare? Offhand I would expect a tabs pane widget to size itself based on the content, but make sure that there is a mechanism to overflow or access tab titles if that width is too small.

**Comment by jsignell** [comment]
I have BOKEH_RESOURCES=inline as an env var on this environment. Is something indicating that BokehJS is coming from CDN?

I think there are two separate issues here. One is that with the current behavior the Tabs model needs a min width that is greater than the scroll icon. 

The other is more up for discussion about what to do in the case of long titles. I think that having tab titles overflow is the clearest option. This is what chrome does for instance:
<img width="565" alt="screen shot 2019-03-07 at 11 23 24 am" src="https://user-images.githubusercontent.com/4806877/53971767-7e1ed780-40cb-11e9-9504-d1e0f62a9702.png">

Compared to bokeh:
<img width="571" alt="screen shot 2019-03-07 at 11 17 05 am" src="https://user-images.githubusercontent.com/4806877/53971442-efaa5600-40ca-11e9-9db7-de329cddb7b3.png">

But chrome might go too far in the overflow since in bokeh users can't just delete tabs:
<img width="245" alt="screen shot 2019-03-07 at 11 12 28 am" src="https://user-images.githubusercontent.com/4806877/53971834-a73f6800-40cb-11e9-85f4-48f3a1a99f38.png">

Another option might be to implement a real scroll rather than the arrow buttons. This is what vscode does for instance.

**Comment by bryevdv** [comment]
> is something indicating that BokehJS is coming from CDN?

The "BokehJS 1.1.0dev9 successfully loaded" in your screen cap. Tho I suppose this is simply because master is actually at 1.1.0dev9 by coincidence just at at this moment.

**Comment by jsignell** [comment]
Got it. I am on latest:

<img width="754" alt="screen shot 2019-03-07 at 11 52 41 am" src="https://user-images.githubusercontent.com/4806877/53973864-8da01f80-40cf-11e9-866c-094127d7b1f7.png">

**Comment by mattpap** [comment]
One thing to consider, when comparing with other systems, is the context in which this kind of layout is being used. In case of Chrome there is a main window and tabs that fit into that view. In bokeh's case, tabs take their preferred size based on the content of the tabs (header isn't involved). If you want to compare things directly, then bokeh's tabs should be initialized with `width_policy="max"`. Unfortunately this doesn't work. Looks like tabs don't respect sizing modes.

**Comment by thoth291** [comment]
Is this: https://github.com/holoviz/panel/issues/983 the same issue?
How to fix the width of the tabs so that this wouldn't happen?

**Comment by philippjfr** [comment]
@thoth291 This is a separate issue, this issue was about the tabs header collapsing your issue is about spaces being stripped from the title.

**Comment by philippjfr** [comment]
I think what you want is an equal_header_width option (would need to find a better name) on tabs that ensures that the tab headers are all the same width.
