### ISSUE TITLE
Tooltip on widgets

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#8727]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
```
Python version      :  3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
IPython version     :  7.2.0
Tornado version     :  5.1.1
Bokeh version       :  1.1.0dev9+2.g1138433
BokehJS static path :  /Users/jsignell/conda/envs/bokeh-dev/lib/python3.6/site-packages/bokeh-1.1.0.dev9+2.g1138433-py3.6.egg/bokeh/server/static
node.js version     :  v11.6.0
npm version         :  6.5.0
```

#### Description of expected behavior and the observed behavior
I think that widgets should have a kwarg that allows tooltips to be set on them - this kwarg could possibly be called `title` or `help`. Note that the toolbar buttons have tooltips already.

Originally raised as https://github.com/pyviz/panel/issues/254

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.models.widgets import Button
from bokeh.io import output_notebook, show

output_notebook()

button = Button(label='+', width=30, title='tooltip text')
show(button)
```

**Comment by bryevdv** [comment]
Useful ref: https://www.w3schools.com/css/css_tooltip.asp

It would be great if someone who has actual visual design opinions took the lead on this since most of the work seems to be deciding how things should look

**Comment by mattpap** [comment]
We already have an implementation of tooltips for the purpose of hover tools. Also, there is HTML `title` attribute that can be used for creating simple text-only tooltips, which we use with toolbar buttons. It seems to me that this is mostly an API issue.

**Comment by bryevdv** [comment]
@mattpap right for widgets we should use the the HTML `title` property for sure. Browsers handle that automatically, no need to use our hover tooltips, which only exist because they have to for canvas. Is there already a way to generally set `title` on our widgets? If not, you are reiterating what's already been suggested: add a way to set `title` (and I added, have someone with design opinions choose the CSS styling for those)

**Comment by MarcSkovMadsen** [comment]
One more vote for introducing this very much needed feature

**Comment by bryevdv** [comment]
Just noting that this potentially overlaps with possible upcoming CZI grant work (if awarded)
