### ISSUE TITLE
Changing Bokeh Slider callback_policy from throttle to mouseup not working

### ISSUE THREAD

**Issue by EdTheEagle** [bokeh/bokeh#8731]
I would like to move freely between 2 callback policies of the slider, "mouseup" and "throttle".

It turns that I can change from "mouseup" to "throttle", but when the callback policy is "throttle" it seems the overwrite of the callback_policy attribute does nothing and the slider remains in "throttle" mode.

I've raised it on stackoverflow before, but people are running into the same issue.

https://stackoverflow.com/questions/54983601/changing-bokeh-slider-callback-policy-from-throttle-to-mouseup-not-working

Stand alone code to show the behavior:

    from bokeh.layouts import column
    from bokeh.models.callbacks import CustomJS
    from bokeh.models.sources import ColumnDataSource
    from bokeh.models.widgets import Slider, RadioButtonGroup
    from bokeh.application.handlers import FunctionHandler
    from bokeh.application import Application

    # this is the real callback that we want to happen on slider mouseup

    def modify_doc(doc):
        def cb(attr, old, new):
            print("UPDATE", source.data['value'])

        # This data source is just used to communicate / trigger the real callback
        source = ColumnDataSource(data=dict(value=[]))
        source.on_change('data', cb)

        # add a slider with a CustomJS callback and a mouseup policy to update the source
        slider = Slider(start=1, end=10, value=1, step=0.1, callback_policy='mouseup')
        slider.callback = CustomJS(args=dict(source=source), code="""
            source.data = { value: [cb_obj.value] }
        """)

        def changeMode(attr, old, new):
            if modeSelect.active==0:
                slider.callback_policy='throttle'
                print('settings adjusted to throttle')
                print(slider.callback)
                print(slider.callback_policy)
                print(slider.callback_throttle)
            else:
                slider.callback_policy='mouseup'
                print('settings adjusted to mouseup')
                print(slider.callback)
                print(slider.callback_policy)
                print(slider.callback_throttle)

        modeSelect = RadioButtonGroup(labels=["continuous", "on release"], active=1,button_type='success')
        modeSelect.on_change('active', changeMode)

        doc.add_root(column(modeSelect,slider))

    handler = FunctionHandler(modify_doc)
    app = Application(handler)

    show(app)

**Comment by bryevdv** [comment]
@EdTheEagle your code behaves exactly as expected for me with 1.1.0dev9 / master Please confirm whether you still see any issue with a Dev Build:

https://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

Otherwise I will assume this has been fixed sometime recently and will close this accordingly. 

Also, FYI, the issue template specifically asked for several important pieces of information, such as OS and Bokeh version. It makes it much harder for us to help when you do not provide the information asked for in the template.

**Comment by bryevdv** [comment]
Closing, happy to re-open with more information.

**Comment by EdTheEagle** [comment]
@bryevdv I have just moved from 0.13 to 1.04 (on Win10) and the issue above still persists. As you mentioned, the issue would not arise in the 1.1.0dev9 version, but I havent installed that version yet. I will await the new version and then check again.

**Comment by bryevdv** [comment]
@EdTheEagle There is no need to wait until the next full release. Dev builds are easily installable with pip or conda according to the link I gave above.
