### ISSUE TITLE
GMap plots not working in the notebook and INLINE resources

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8733]
The following code: 
```
from bokeh.io import output_notebook, show
from bokeh.models import GMapOptions
from bokeh.plotting import gmap
from bokeh.models import Label

output_notebook()

map_options = GMapOptions(lat=30.2861, lng=-97.7394, map_type="roadmap", zoom=13)

# replace with your google api key
p = gmap("API-KEY", map_options)

show(p)
```
Generates no output, and the following console error:

> ReferenceError: Can't find variable: _bokeh_gmaps_callback

This is on master but evidently at least on 1.0.4 as well

**Comment by bryevdv** [comment]
Update: this seems to be confined to inline resources

**Comment by bryevdv** [comment]
And now I can't reproduce a problem at all anymore. Notebooks, who knows.

**Comment by bryevdv** [comment]
Actually I guess it is failing with 1.1.0dev9 / master with inline resources, but not 1.0.4

**Comment by mattpap** [comment]
It's an easy fix, I will submit a PR later today.
