### ISSUE TITLE
Elevate our code of conduct

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8741]
I was looking at some CoC stuff for another project and thought I would take a quick look at Bokeh's and realized that it's not featured prominently or at all on any of the standard bokeh landing pages.

I was thinking a mention along with a sentence about being an open, diverse and inclusive community would be nice. Propose the following pages:
* https://bokeh.pydata.org/en/latest/
* https://bokeh.pydata.org/en/latest/docs/dev_guide.html
* https://bokeh.pydata.org/en/latest/docs/contribute.html
* https://bokeh.pydata.org/en/latest/docs/contact.html
* https://bokeh.pydata.org/en/latest/docs/team.html
* https://github.com/bokeh/bokeh

**Comment by bryevdv** [comment]
@birdsarah I think all of those locations seem reasonable. Are you planning to submit the PR?

**Comment by pavithraes** [comment]
Points from an old discussion on Discourse with @bryevdv 

A note about the CoC could be added to:
- [ ] The main repo README: https://github.com/bokeh/bokeh/blob/master/README.md
- [ ] Developer guide: https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/dev_guide.rst
- [ ] Front page site (https://bokeh.org)
  - Footer: https://github.com/bokeh/bokeh.org/blob/master/_includes/footer.html
  - The “team” page: https://github.com/bokeh/bokeh.org/blob/master/_includes/team.html
- [ ] Blog site (https://blog.bokeh.org) footer: https://github.com/bokeh/blog.bokeh.org/blob/master/_includes/footer.html
- [ ] Demo site (https://demo.bokeh.org) footer: https://github.com/bokeh/demo.bokeh.org/blob/master/index.html
- [ ] Pinned topics in this Discourse, e.g at a minimum a sentence here: https://discourse.bokeh.org/t/about-the-community-support-category/16 but we could consider adding a note to all the pinned topics in all the categories

**Comment by pavithraes** [comment]
I missed the footer in docs.bokeh.org :/
