### ISSUE TITLE
When line_width is set to 0 the glyph boundaries don't disappear

### ISSUE THREAD

**Issue by PavloFesenko** [bokeh/bokeh#8746]
For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 1.0.4, python 3.6.6, notebook Kaggle, OS Windows 10, browser Chrome

#### Description of expected behavior and the observed behavior
I am trying to remove the glyph boundaries by using `line_width=0` but they don't disappear. As a temporary fix I use `line_alpha=0` instead.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, output_file, show

output_file("patch.html")

p = figure(plot_width=400, plot_height=400)

p.patch([1, 2, 3, 4, 5], [6, 7, 8, 7, 3], fill_color='white', line_width=0)

show(p)
```

#### Screenshots or screencasts of the bug in action
![Linewidth bug](https://user-images.githubusercontent.com/16855796/54425498-c49cb380-4715-11e9-8ba3-d8cb966444d6.PNG)

**Comment by bryevdv** [comment]
This is the unfortunate behavior of the underlying HTML canvas (I just tested on Safari in a codepen to be sure). There is nothing we can do to change that. Since there are accepted method to suppress lines (set `line_color=None` or `line_alpha=0`) I'm inclined to just close this as `upstream`

@bokeh/dev any other thoughts?

**Comment by jbednar** [comment]
That does seem like the fault of the HTML canvas, but I think people will still consider it a Bokeh bug.  Would it be reasonable for BokehJS to work around it by forcing line_color=None when line_width is set to 0?  It's very annoying and strange to have to do this, and I suspect that doing it would cause other problems, e.g. if line_width is then set to a non-zero value the color will mysteriously still be None.  But if there is a way to do it without having confusing side-effects like that, it would be nice to do so, as the current behavior seems very clearly wrong from the user perspective.

**Comment by bryevdv** [comment]
It's clearly wrong, but it is it important? It would take some amount of effort to fix correctly, and it has evidently only been noticed once in ~6 years. So my prompt is really about justifying time/effort.

**Comment by philippjfr** [comment]
I do remember noticing this and working around it myself a few times by setting ``line_alpha=0``. If there is indeed no good and easy fix here I'd also be inclined to say that it's not worth the invested effort or additional complexity.

**Comment by bryevdv** [comment]
Right now the "visuals" are hard wired to look at a single property to determine whether drawing or stroking should occur:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/core/visuals.ts#L25

To fix this properly, that would need to be generalized

**Comment by jbednar** [comment]
I agree; a bad or very difficult fix isn't worth it.  But if there is a good, easy fix, I'd say it's worth it; people will often not report something like this if there's a workaround.  Sounds like there isn't, but if generalizing that approach is useful for some other reason, addressing this problem could be considered.

**Comment by bryevdv** [comment]
One possible reason to do something: Currently `line_color=None` actively suppresses the call to `ctx.stroke` whereas `line_alpha=0` still calls `ctx.stroke` but the result just happens to be invisible. If this were generalized then we could prevent code execution for invisible configurations in all cases.
