### ISSUE TITLE
Taptool not working in 1.0.4

### ISSUE THREAD

**Issue by wochner** [bokeh/bokeh#8759]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 1.0.4
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0] on linux, SUSE Linux Enterprise Server 12 (x86_64)
Firefox 60.5.2esr (32-Bit)

#### Description of expected behavior and the observed behavior

Expect the server to print "tap". Nothing happens. This still works in version 0.13.0. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models.widgets import Tabs, Panel
from bokeh.layouts import layout

def draw_spread_scatter():
    chart = figure(plot_width=1200, plot_height=800,
               tools="save,pan,box_zoom,reset,tap",
               x_axis_type="datetime")
    
    d = {'one': [1., 2., 3., 4.],
        'two': [4., 3., 2., 1.]}

    sn = chart.scatter(x='one',
                 y='two',
                 source=d)
    
    def tap_callback(attr, old, new):
        print('tap')
        
    sn.data_source.on_change('selected', tap_callback)    

    return chart

# set layout 
tab1 = Panel(child=draw_spread_scatter(),title="Spread Scatter")

tabs = Tabs(tabs=[tab1])

l = layout([
    [tabs]
    ])

curdoc().add_root(l)

```

#### Stack traceback and/or browser JavaScript console output

python@t-srh-pam02:/home/wochner/bokeh> python -m bokeh serve tap_issue.py --allow-websocket-origin=t-srv-pam02:5007 --port 5007
2019-03-17 18:29:57,195 Starting Bokeh server version 0.13.0 (running on Tornado 4.5.3)
2019-03-17 18:29:57,198 Bokeh app running at: http://localhost:5007/tap_issue
2019-03-17 18:29:57,198 Starting Bokeh server with process id: 18632
2019-03-17 18:30:54,867 200 GET /tap_issue (10.103.3.81) 116.80ms
2019-03-17 18:30:55,420 101 GET /tap_issue/ws?bokeh-protocol-version=1.0&bokeh-session-id=HJpI09OsCaLaWfNf3AMRgoLZao6Ihd9JT5ijy9wmYw35 (10.103.3.81) 0.74ms
2019-03-17 18:30:55,420 WebSocket connection opened
2019-03-17 18:30:55,420 ServerConnection created
tap

**Comment by bryevdv** [comment]
Please see the migration Guide for 1.0, specifically the section "Handling of Selections"
