### ISSUE TITLE
export_png fails when extending existing bokeh widgets

### ISSUE THREAD

**Issue by rmelotte** [bokeh/bokeh#8769]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

```
bokeh: 1.1.0.dev9
python: 2.7.15
OS: Linux debian 4.9.0-8-amd64 (debian 9)
browser: firefox 65.0.2
```

#### Description of expected behavior and the observed behavior

I'm trying to export figures to files, and I have a custom widget that I use to get float inputs from the user. When the custom widget is created, export_png fails to load bokeh.

##### Expected
Exporting a figure should work no matter what custom widgets are created.

##### Observed
When export_png is used an a custom widget is created, it fails with "Bokeh was not loaded in time. Something may have gone wrong.".

#### Complete, minimal, self-contained example code that reproduces the issue
Here is a small example that fails to export a figure.
It works again if you comment out the class declaration and instanciation (FloatTextInput and ftextinput).
```
from bokeh.models import TextInput
from bokeh.io import export_png, curdoc
from bokeh.layouts import layout
from bokeh.plotting import figure


JS_CODE = """
import {TextInput} from "models/widgets/text_input"
export class FloatTextInput extends TextInput 
  type: "FloatTextInput"
"""

class FloatTextInput(TextInput): 
    __implementation__ = JS_CODE
    # FloatTextInput does some input validation on value change (left out for readability)

ftextinput = FloatTextInput()

textinput = TextInput()

fig = figure()
layout = layout([textinput, fig])
curdoc().add_root(layout)

export_png(fig, "out.png")
```

#### Stack traceback and/or browser JavaScript console output

```
2019-03-19 13:58:23,850 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7fbafcd005d0>: Bokeh was not loaded in time. Something may have gone wrong.
File "wait.py", line 80, in until:
raise TimeoutException(message, screen, stacktrace) Traceback (most recent call last):
  File "/home/rmelotte/anaconda3/envs/cdotool/lib/python2.7/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/home/rmelotte/Documents/bokeh-experiments/custom_model_exports_fails.py", line 31, in <module>
    export_png(fig, "out.png")
  File "/home/rmelotte/anaconda3/envs/cdotool/lib/python2.7/site-packages/bokeh/io/export.py", line 92, in export_png
    image = get_screenshot_as_png(obj, height=height, width=width, driver=webdriver)
  File "/home/rmelotte/anaconda3/envs/cdotool/lib/python2.7/site-packages/bokeh/io/export.py", line 210, in get_screenshot_as_png
    wait_until_render_complete(web_driver)
  File "/home/rmelotte/anaconda3/envs/cdotool/lib/python2.7/site-packages/bokeh/io/export.py", line 282, in wait_until_render_complete
    raise_with_traceback(RuntimeError('Bokeh was not loaded in time. Something may have gone wrong.'))
  File "/home/rmelotte/anaconda3/envs/cdotool/lib/python2.7/site-packages/bokeh/io/export.py", line 280, in wait_until_render_complete
    WebDriverWait(driver, 5, poll_frequency=0.1).until(is_bokeh_loaded)
  File "/home/rmelotte/anaconda3/envs/cdotool/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
RuntimeError: Bokeh was not loaded in time. Something may have gone wrong.
```

I tried to port FloatTextInput's JS_CODE to Typescript, but the issue remains the same.
I also have other custom widgets (mainly extending Row and Column) and they work fine with export_png.

**Comment by bryevdv** [comment]
Currently the timeouts are hardcoded, e.g.

https://github.com/bokeh/bokeh/blob/a59a777d4d01846cc16e78662208258c86faabf7/bokeh/io/export.py#L278

There's no way to anticipate how long things might take with an arbitrary combination of user extensions and specific OS/hardware. I think the best we can hope to do is expose this timeout as a configurable value that users can bump higher if their specific needs require more time.

**Comment by bryevdv** [comment]
@rmelotte would you be interested in working up a PR for this? It is definitely accessible to anyone with moderate Python experience and would help get a fix in faster.

**Comment by rmelotte** [comment]
@bryevdv Thanks for your help.

I tried tweaking the timeouts manually, but unfortunately it doesn't seem to solve the issue.

I tried setting it as high as 300 seconds, but it still fails on the example given here (although I can confirm it waits for 300 seconds).

Beside, do you have a clue on why it fails when extending TextInput, but not when extending Column ? Is TextInput more expensive to compile ?

**Comment by bryevdv** [comment]
If it's not the timeout then I am afraid I have no idea what the issue could be at the moment.

**Comment by rmelotte** [comment]
You're right, I could reproduce the issue with 1.1.0dev9, but it's gone in 1.1.0dev10.

Thanks!
