### ISSUE TITLE
Spinner jumps to low after one click, regardless of step

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8786]
1.1dev11,  OSX Safari and FF

clicking the down button on the spinner jumps to the low bound after at most 1 click, regardless of the step value

```py
import numpy as np
from bokeh.models import ColumnDataSource, CustomJS, ColorPicker, Spinner
from bokeh.plotting import Figure, show
from bokeh.layouts import row, widgetbox

data = np.random.rand(20, 2)
cds = ColumnDataSource(data=dict(x=data[:, 0], y=data[:, 1]))

p = Figure(x_range=(0, 1), y_range=(0, 1), plot_width=350, plot_height=350)
r = p.circle(x='x', y='y', source=cds, color="red", size=8)

w = ColorPicker(title="Gylp Color", color="red", height=20, width=100)
cb = CustomJS(args={'r': r}, code="""
r.glyph.fill_color = cb_obj.color
r.glyph.line_color = cb_obj.color
""")
w.js_on_change('color', cb)


w2 = Spinner(title="Glyph size", low=1, high=20, step=0.1, value=8, width=100)
cb = CustomJS(args={'r': r}, code="""
r.glyph.size = cb_obj.value
""")
w2.js_on_change('value', cb)

show(row(widgetbox(w2, w), p))
```

**Comment by bryevdv** [comment]
This logic appears to be at fault:

https://github.com/bokeh/bokeh/blob/e1f427e7afd5867f498a51b4bc08ca26bd3053cd/bokehjs/src/lib/models/widgets/spinner.ts#L24-L29****

**Comment by bryevdv** [comment]
This almost fixes things:
```
   const fn = () => {
      const {step} = this.model
      this.input_el.step = step.toFixed(log10(1 / step))
    }
    this.connect(this.model.properties.step.change, fn)
```

With this change, the first step (up or down) is too small but then all subsequent steps work. 

@mattpap can you comment? I realize the step needs to be converted to an appropriate precision string, but setting from `value.toFixed` does not correct in any case.

**Comment by bryevdv** [comment]
Moving to 1.1, this is a serious bug that makes `Spinner` unusable

**Comment by xavArtley** [comment]
@bryevdv 
can you try with this code?
```
connect_signals(): void {
    super.connect_signals()
    this.connect(this.model.properties.low.change, () => {
      const {low, step} = this.model
      if (low != null)
        this.input_el.min = low.toFixed(log10(1 / step))
    })
    this.connect(this.model.properties.high.change, () => {
      const {high, step} = this.model
      if (high != null)
        this.input_el.max = high.toFixed(log10(1 / step))
    })
    this.connect(this.model.properties.step.change,  () => {
      const {step} = this.model
      this.input_el.step = step.toFixed(log10(1 / (10*step)))
    })
    this.connect(this.model.properties.value.change, () => {
      const {value, step} = this.model
      this.input_el.value = value.toFixed(log10(1 / step))
    })
    this.connect(this.model.properties.disabled.change, () => {
      this.input_el.disabled = this.model.disabled
    })
  }
```
Sorry I'm at home I don't have much time to work on this

**Comment by xavArtley** [comment]
The problem with round is the comprison to a min avlue wich cannot be reach from the value and the step define.
A solution would be to compute reachable `virtual_min` and `virtual_max` and make computations from these values.
However I don't know how it should behave when we reach bounds. Setting the value to the min define by the user (then the initial value could be not reachable again) or set it to the virtual min max

**Comment by bryevdv** [comment]
> However I don't know how it should behave when we reach bounds. Setting the value to the min define by the user (then the initial value could be not reachable again) or set it to the virtual min max

Yes that explanation makes sense. Probably best to make it configurable and leave it to users. As a default I would personally say second option is best.
