### ISSUE TITLE
codebase tests fail on Windows

### ISSUE THREAD

**Issue by samaust** [bokeh/bokeh#8789]
There's two issues with ```\tests\codebase\test_python_execution_with_OO.py```: 

* It generates a long command that exceeds the 8191 Cmd.exe character limit
* It generates backslashes that need to be replaced by dot

**Comment by bryevdv** [comment]
@samaust More than anything else. these tests just need to be run by the CI. I'm perfectly OK to just skip them on windows. The slight risk is that a developer on windows pushes a PR with problems that are not detected until the CI runs, but they will be detected, and could then be fixed. 

Would you mind submitting a PR to skip these tests on Windows?
