### ISSUE TITLE
Range tool gets stuck at minimum width

### ISSUE THREAD

**Issue by zfei** [bokeh/bokeh#8793]
Working with range tool in Bokeh 1.0.4. All is well except when the box is squeezed to the minimum, the selector doesn't function any more (can't be dragged or resized, see the screenshot below).

![range_tool_stuck](https://user-images.githubusercontent.com/1736058/54990527-eb9c9480-4ff5-11e9-945a-8fa80c2345db.gif)

It can be quickly reproduced in the Bokeh range tool demo - https://bokeh.pydata.org/en/latest/docs/gallery/range_tool.html.

The counterpart in Plot.ly offers an interesting solution where the bars simply reverses when dragged to the other side - https://plot.ly/~PythonPlotBot/1855.embed

Would really appreciate it if this can be fixed or even better, the same trick can be done in Bokeh :)

**Comment by bryevdv** [comment]
Letting it flip seems like a reasonable thing to do.

**Comment by zfei** [comment]
Thanks @bryevdv !

And sorry there's another minor issue - when the range box goes out of bounds via wheel scroll, the box can no longer be dragged or resized from the out-of-bound side:

![range_tool_oob](https://user-images.githubusercontent.com/1736058/55078418-16a9e580-50d5-11e9-8e34-db95ddeae5e6.gif)

Since the `x_range` is linked between the range tool and the figure, I'm not exactly sure if there's a neat way to fix this unless the zoom level is capped?

**Comment by pzwang** [comment]
Looks like the issue might be that `_calc_dim()` in `box_annotation.ts` doesn't actually do clipping?

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/annotations/box_annotation.ts#L60

**Comment by bryevdv** [comment]
@zfei except for the fact that the drawing isn't clipped, I think that behavior is correct. If you pan the edge of the range tool box outside the plot bounds by some means, then it should not be accessible.

**Comment by bryevdv** [comment]
Oh, it's not clipping because the default render mode is `"css"`, that would be small pain to fix. I am tempted to change the default to `"canvas"` for the time being. 

Making it pan-able if one side is out of bounds is a simple fix (change condition to be whether the number of final sides in bounds is GEQ initial sides in bounds)

**Comment by bryevdv** [comment]
I pushed a WIP PR that fixes all these issues (note: cropping fixed by switching to canvas render mode), but I will need to add tests later before it can be merged.

**Comment by zfei** [comment]
Wow, thank you so much guys!
