### ISSUE TITLE
Make layout respect aspect ratio with scale_height sizing mode

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8821]
@mattpap 

* All sizing modes seem to work well except possibly height scaling. Check `sizing_mode.py` to confirm. I'm fine with stating a limitation or known issue I just want your comment. 

* I've had to set explicit widths on several widgets to prevent them from stretching across the entire screen (see the forthcoming docs PR for the commits) Maybe this is fine/expected but perhaps we are missing some guidance.

I tested every other non-reference example on OSX/Safari and everything looks fantastic (any small issues were previously known). I will try to do some spot windows testing soon.

**Comment by bryevdv** [comment]
I should add I have not yet updated the widget width baselines yet

**Comment by mattpap** [comment]
The first is a bug. I will fix this today. The other is explained [here](https://github.com/bokeh/bokeh/pull/8822#discussion_r272940106).

**Comment by mattpap** [comment]
> I should add I have not yet updated the widget width baselines yet

I wonder if #8645 was fixed. If not, I will update baselines when you're done updating examples.

**Comment by bryevdv** [comment]
> I wonder if #8645 was fixed. If not, I will update baselines when you're done updating examples. 

It is not AFAIK, I took the new values from the CI diffs after minimally inspecting them.
