### ISSUE TITLE
Incorrect axis labels for negative timedeltas.

### ISSUE THREAD

**Issue by djbarker** [bokeh/bokeh#8827]
#### Software versions 

Python == 3.6.4
Bokeh == 1.03
Jupyter == 4.4.0
Numpy == 1.14.3
OS == Fedora 28
Browser == Chrome 72

#### Description

Timedeltas sees to mostly work with `x_axis_type="datetime"` but they are incorrectly rendered if negative. They are off by a factor of 10 and the lowest is incorrectly rendered as 0. 

#### Example Code

```python
import numpy as np
from bokeh.plotting import figure
from bokeh.io import show

p = figure(x_axis_type="datetime", height=300)
x = np.arange(np.timedelta64(-1, "s"), np.timedelta64(0, "s"), np.timedelta64(5, "ms"))
y = np.sin(np.linspace(0, 2*np.pi, len(x)))
p.line(x, y)
show(p)
```

#### Screenshot

![bokeh_plot](https://user-images.githubusercontent.com/4553538/55785644-b63e7f00-5aaa-11e9-9a8a-35db5b2e4bca.png)

Axis should read "-1000 ms, -800 ms, -600 ms, ... -100 ms" (or "-1 s")

**Comment by bryevdv** [comment]
So the values are making it to BokehJS as expected. I.e. turning off the datetime axis yields:

<img width="613" alt="Screen Shot 2019-04-09 at 4 38 13 PM" src="https://user-images.githubusercontent.com/1078448/55841926-28808500-5ae6-11e9-98d5-7016cade77d8.png">

So this is either an error with the datetime axis, or a usage issue. After a little thought I am inclined to think it is perhaps the latter. Mainly for the reason that timedeltas *are not* datetime values, so a datetime axis is really not appropriate. Datetime values identify a specific moment in time. Timedeltas obviously do not do that at all, the represent an interval between datetimes. 

As a concrete example of how a datetime axis is not correct to use for timedeltas: with big enough values, a default datetime axis would start labeling timedelta tick values with things like "July", which is nonsense. 

There are various ways to do this the "right" way. One would be to use a `PrintfTickFormatter` to add the `ms` unit:

```
import numpy as np
from bokeh.models import PrintfTickFormatter
from bokeh.plotting import figure
from bokeh.io import show

p = figure(height=300)
x = np.arange(np.timedelta64(-1, "s"), np.timedelta64(0, "s"), np.timedelta64(5, "ms"))
y = np.sin(np.linspace(0, 2*np.pi, len(x)))
p.xaxis.formatter = PrintfTickFormatter(format="%5.0f ms")
p.line(x, y)
show(p)
````
which yields:

<img width="621" alt="Screen Shot 2019-04-09 at 4 44 48 PM" src="https://user-images.githubusercontent.com/1078448/55842117-fcb1cf00-5ae6-11e9-88bd-93691582fd52.png">

**Comment by bryevdv** [comment]
One thing we could consider doing is to add a convenience `TimedeltaTickFormatter`. That could make labeling timedeltas a bit easier (wouldn't have to look up and configure the printf formatter) and also could be more flexible across different scales of timedeltas i.e. it could start labeling big deltas with units like "months" or "years" (but not as *specific* months or years like a datetime)

**Comment by florentbr** [comment]
I had the exact same need but noticed later that `datetime` doesn't work well with time deltas. 
I managed to automatically format seconds as either `s` `ms` `µs` `ns` `ps` with a `FuncTickFormatter` :

```python
JS_FORMAT_X = "for(var n=-1,v=tick;v&&!(v|0);++n)v*=1e3;return v&&+v.toPrecision(5)+' '+('mµnp'[n]||'')+'s'"
p.yaxis.formatter = bokeh.models.FuncTickFormatter(code=JS_FORMAT_X)
```
