### ISSUE TITLE
[BUG] App is extremely slow - most CPU is wasted on 'paint' method

### ISSUE THREAD

**Issue by ofirbit** [bokeh/bokeh#8836]
#### Description of expected behavior and the observed behavior
Hi. I have some realtime bokeh charts in my web application. The page displays one chart with 4 panels. Each panel gets around 2-3 new points every 1 second (I think that's not much). Attached my profiling output. In general the website works too slow and you can feel the lags when you work with the app. Seems like Bokeh takes almost all CPU. The attached profiling is when the website is completely idle (didn't touch anything).

#### Versions
Bokeh 0.12.15
Python 2.7.4
Working with Internet Explorer (tried also chrome, getting almost the same results)

#### Complete, minimal, self-contained example code that reproduces the issue
I'm simply working with a bokeh server and a script in the website as described in the embedding manual.

#### Screenshots or screencasts of the bug in action

![image](https://user-images.githubusercontent.com/45560972/56083589-9226c900-5e2f-11e9-9fc8-738fef0cb023.png)

**Comment by bryevdv** [comment]
@ofirimubit We 100% absolutely must have the exact code you were using (or *some* complete script to reproduce what you are seeing) to be able to investigate problems like this.

**Comment by bryevdv** [comment]
@ofirimubit I also just noticed this is reported with 0.12.15. The recent 1.1. release overhauled the entire layout system and very likely fixed whatever you are seeing. Please try again with Bokeh 1.1. and report back .

**Comment by bryevdv** [comment]
Closing for lack of response / no details with current releases
