### ISSUE TITLE
Unable to plot pdf and cdf lines with new charts.Histogram

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#884]
Trying to reproduce the old histogram tutorial with the new charts.Histogram, I'm unable to plot the pdf and cdf lines (except for the normal distribution). There is no hold() method to plot a line on top nor a way to pass variables (except mu and sigma in the normal distribution) to get the lines rendered directly in the Histogram plot.

**Comment by bryevdv** [comment]
@fpliger is this still relevant?

**Comment by bryevdv** [comment]
`bokeh.charts` has moved to https://github.com/bokeh/bkcharts this should be re-opened there if appropriate.
