### ISSUE TITLE
bar_color Slider not updating

### ISSUE THREAD

**Issue by EdTheEagle** [bokeh/bokeh#8843]
bokeh=1.1.0
python=3.6.2
notebook=Jupyter Notebook
OS= Win 10
Browser=Chrome

In the new version of Bokeh 1.1.0, the bar color does not change anymore when updated, which was working in version 1.0.4. I've added an example below where you can see that the bar_color attribute is being updated but the color changes are not visible. Initiation with another color (change startColor) does work.

```
from bokeh.layouts import layout
from bokeh.models.widgets import Slider
from bokeh.application.handlers import FunctionHandler
from bokeh.application import Application
from bokeh.io import show, output_notebook
output_notebook()

colors = ['#000008','#00001F','#0084FF','#00CAFF','#32FF4D']
startColor = 4

def plotter(doc):    
    def processChange(attr, old, new):
        print('old '+str(groupSlider.bar_color))
        groupSlider.bar_color = colors[new-1]
        print('new '+str(groupSlider.bar_color))
        
    groupSlider = Slider(start = 1, end =5, step = 1, value = startColor,title = 'Group',width=100,bar_color=colors[startColor-1])           
    groupSlider.on_change('value', processChange)
       
     
            
    doc.add_root(groupSlider)
handler = FunctionHandler(plotter)
app = Application(handler)
show(app)

```

**Comment by bryevdv** [comment]
AFAICT there's never been event plumbing hooked up to respond to changes in `bar_color`, my best guess is that the color bar we being excessively re-rendered and so changing `bar_color` appeared to work by coincidence. 

cc @mattpap
