### ISSUE TITLE
[FEATURE] Stacked Areas and Lines

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8848]
Strangely, I can't find a suitable issue for this. Anyway, I will submit a PR later this week to add support for this:

<img width="925" alt="Screen Shot 2019-04-17 at 10 21 36 PM" src="https://user-images.githubusercontent.com/1078448/56338595-80129680-615f-11e9-98b8-e97d0ca5bb47.png">

Implementation is basically done, needs docs and tests. Would not mind some feedback on a couple of questions:

* The `harea` and `varea` only have *fill* props currently. The rationale is that AFAICT these kinds of charts never outline the sides/bottom. Does that seem reasonable? 

* x1 and x2? or x0 and x1? 

cc @bokeh/core @bokeh/dev @pzwang for any comments before submitting

**Comment by bryevdv** [comment]
For good measure here is how it will look horizontal or negative:

<img width="712" alt="Screen Shot 2019-04-17 at 10 29 33 PM" src="https://user-images.githubusercontent.com/1078448/56338798-69207400-6160-11e9-94c6-f5a6f33b930d.png">

<img width="698" alt="Screen Shot 2019-04-17 at 10 30 04 PM" src="https://user-images.githubusercontent.com/1078448/56338799-6b82ce00-6160-11e9-9d35-9fc4311a772d.png">

**Comment by birdsarah** [comment]
> The rationale is that AFAICT these kinds of charts never outline the sides/bottom. Does that seem reasonable?

I think that's reasonable. There are certainly workarounds if we decided not to. Excited to see this.

**Comment by bryevdv** [comment]
@birdsarah do you think it would be OK to ship a first cut of this w/o working hover support? Patch does not currently support hit testing, and I am not sure what it would take to get things working well

**Comment by wabu** [comment]
Does hover work on the borders at least? Had the problem in holoviews and created an invisible lines overlay to get hover on these ...

**Comment by bryevdv** [comment]
Stacked area has no border of its own, as discussed above. But hover currently would work on a corresponding stacked line added alongside.

**Comment by birdsarah** [comment]
> @birdsarah do you think it would be OK to ship a first cut of this w/o working hover support? Patch does not currently support hit testing, and I am not sure what it would take to get things working well

I did not know that patch doesn't support hit testing....that has surprised me. I got it working in this PR https://github.com/bokeh/bokeh/pull/3399/files if there's anything you can crib from that.

I'm more taken aback by the fact that we don't have hit testing on patches, than I am concerned about having it in this case.

**Comment by bryevdv** [comment]
*Patches* has hit-testing, *Patch* does not, because it's one of the weirdo glyphs that isn't actually vectorized, so will need some special casing.

**Comment by birdsarah** [comment]
Cool. Thanks! I think it's fine to move ahead....and maybe open an issue for patch hover?

**Comment by bryevdv** [comment]
OK I will push and merge a quick PR for this later today, so I can include these areas in the hatching pr
