### ISSUE TITLE
Better API for applet model contruction

### ISSUE THREAD

**Issue by samchrisinger** [bokeh/bokeh#885]
Hi,

I'm working on a Bokeh applet that renders a visualization based on a schema with fields unknown until runtime. Following the applet examples in the source(https://github.com/ContinuumIO/bokeh/blob/master/examples/plotting/server/stocks.py), I made a Model class to contain widget attributes. Given that I don't know the fields of the model ahead of time I tried to dynamically add class variables like:
``` setattr(MyModel, key, Float(1.0))```
but this approach fails because (as far as I understand the source) the model class's __field_defs are set in a parent class's initialization function. As a result I've ended up implementing: 
```
def ESModelFactory(schema):
    attrs = {
        'input_specs': []
    }
    for key,value in schema.iteritems():
        if key == '__global':
            continue
        if value['type'] == 'string':
            attrs[key] = String(default=value['cats'][0])
            attrs['input_specs'].append({
                'widget': Select,
                'name': key,
                'value': value['cats'][0],
                'options':  value['cats']
            })
        if value['type'] == 'date':
                attrs[key+'_max'] = Float(1.0)
                attrs[key+'_min'] = Float(1.0)
                attrs['input_specs'].append({
                    'widget': Slider,
                    'name': key+'_max',
                    'value': 1.0,
                    'start': 0,
                    'end': 1.0
                })
                attrs['input_specs'].append({
                    'widget': Slider,
                    'name': key+'_min',
                    'value': 0,
                    'start': 0,
                    'end': 1.0
                })
    return type('ESModel', (VBoxModelForm,), attrs)
```
Specific details aside, this seems like a less than optimal way to meet my use case. 

Is there another cleaner way to do this using existing Bokeh APIs? Otherwise maybe there could be a method for modifying __field_defs after class definition?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
