### ISSUE TITLE
[FEATURE] Merged tickers

### ISSUE THREAD

**Issue by cpitclaudel** [bokeh/bokeh#8855]
**Is your feature request related to a problem? Please describe.**

I'm plotting a time series.  I'd like the x axis (dates) to display evenly spaced ticks (one per year, then one per month at closer zoom levels, etc.), *plus* fixed ticks, one under data point.  This would allow readers to know exactly which date each point corresponds to.

**Describe the solution you'd like**

`CompositeTicker` is very close to what I need, but it requires each ticker to operate at different scale.  I'd like a `MergedTicker` that combines two or more tickers; I'd use `DatetimeTicker` and a `FixedTicker`.

**Describe alternatives you've considered**
I can use a `FixedTicker`, but I lose the smooth zooming behavior of `DatetimeTicker`.

Thanks for the hard work!

**Comment by bryevdv** [comment]
@cpitclaudel Are you expecting to be able to format the ticks from each ticker independently? Would you be willing to work on this, with some guidance?

**Comment by cpitclaudel** [comment]
No, I think a single formatter would work for my use case (adding ticks).  If there's a chance it might get accepted, I could have a look.

**Comment by bryevdv** [comment]
> No, I think a single formatter would work for my use case (adding ticks). If there's a chance it might get accepted, I could have a look.

Single formatting for merged ticks is much more tractable, I'd be happy to accept a PR for a merged ticker. I'd definitely appreciate if you did try to take a look first. It's in the project's interest to help more people become acquainted with Bokeh core development, so I'd definitely prefer to start by investing time trying to help new people work up their own PRs. To give some idea of the final amount of code involved, I expect the Merged ticker to be about the same size (and very similar structure) to the FixedTicker:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/tickers/fixed_ticker.ts

You will need to be able to build and test with BokehJS locally. This should be fairly complete setup guide now:

https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html

And the "Extending Bokeh" has a nice overview of how the Python and JS sides are related:

https://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html

A final `MergedTicker` will be almost the same as `FixedTicker`, it will just have a property to accept a list of "sub" tickers, and then the "get ticks" method will just loop over all of those and collect the ticks in one result.

**Comment by bryevdv** [comment]
@cpitclaudel were you still interested in making a PR for this?

**Comment by cpitclaudel** [comment]
I haven't found time to work on it, unfortunately :/

**Comment by bryevdv** [comment]
I think a `CombinedTicker` (or `MultiTicker`) would be useful, so I have triaged it `feature` tho I don't know when I'll be able to look at it.

**Comment by bryevdv** [comment]
Since there has been no further interest expressed for this, I will go ahead and close now. 

I will also not that a `CustomJSTicker` was also recently added to Bokeh, affording complete control over tick location selection. Existing tickers could be combined in the customJS code for the ticker, explicitly serving this purpose.
