### ISSUE TITLE
Update Tile Provider example for "Mapping Geo Data" User Guide

### ISSUE THREAD

**Issue by chunkily** [bokeh/bokeh#8867]
Currently the provided example generates a deprecation warning for importing the `CARTODBPOSITRON` tile provider from `bokeh.tile_providers`.

**Comment by bryevdv** [comment]
@chunkily There are various examples, please link to the specific one you found

**Comment by chunkily** [comment]
This [tile provider maps example](https://bokeh.pydata.org/en/latest/docs/user_guide/geo.html#tile-provider-maps) is the one I'm referring to.
