### ISSUE TITLE
How to read an html file having a figure and show it my bokeh application

### ISSUE THREAD

**Issue by ga53vap** [bokeh/bokeh#8869]
I am facing the issue of not being able to read an html file containing a figure and show it in my bokeh application.
The Div markup provided works just fine if a the content of the html file is a text, but not something else.

For example, here I am creating a plot and saving it as an html and reading the html file back using Div:

from bokeh.plotting import figure, output_file
from bokeh.models.widgets import Div
from os.path import dirname, join

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html", title="line plot example")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

HTML_filename = join(dirname(_file_), "lines.html")
myHTML= Div (text=open(HTML_filename).read(), render_as_text=False, width=650, height=100)
show(myHTML)

This results in a blank html web page. Why?!

**Comment by bryevdv** [comment]
First off, `output_file` does not `save` anything, it merely indicates where things should be saved. You need to call `save(p)` or `show(p)` to actually generate the HTML file. But beyond that, Bokeh aside, I'm  really not sure stuffing an entire other web page content with its own `head` etc. in a div like this would be expected to work, in general. This is certainly not how we intended Bokeh content to be embedded. For that there are various specific APIs like `json_item` and `components`:

https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html

How to effectively use those is really a support question, though, so I'd ask that this conversation move to the mailing list.

**Comment by bryevdv** [comment]
I guess I would only add: If you insist on going this path, I think you would need to wrap the other page content in an `IFrame` in the div, but again, I explicitly don't recommend "embedding" this way.

**Comment by jbednar** [comment]
I agree this approach throws up all sorts of issues, but it's worth mentioning that many Panel users have recently been asking for similar functionality, for various reasons.  I  haven't yet fully convinced myself that they really *should* want that, or whether there is a better approach in each case, but they are definitely asking for it and expecting it to work.

Would you recommend using `components()` rather than `save()` for such users, generating a fragment that's easier to embed rather than what's meant to be a standalone HTML file?

**Comment by bryevdv** [comment]
> Would you generally recommend using components() rather than save() for such users, generating a fragment that's easier to embed rather than what's meant to be a standalone HTML file?

These days I would recommend `json_item` first

**Comment by ga53vap** [comment]
Thank you bryevdv.
What I am actually trying to do is, read an html file containing a matplotlib figure (converted to html using mpld3 library) and embed it in my Bokeh app.
I am doing this since that there's no function in Bokeh similar to pcolormesh function in matplotlib ( providing smooth transition and good resolution in 2D plots)

here is an example of what I am doing:
```
import matplotlib.pyplot as plt
import numpy as np
from math import exp
from scipy.integrate import quad
import mpld3

Resolution=60
amp=1
T0=2
a = np.linspace(0.1, 5, Resolution)
b = np.linspace(0.1, 5, Resolution)
W = np.zeros((Resolut, Resolution))

for i in range (0,Resolution):
    for j in range (0,Resolution):
        def integrand1(t):
            output = a[i]**-0.5 * amp * (t-b[j])/a[i] * exp(-( (t-b[j])/a[i] )**2.0)
            return output
        W[i][j]=quad(integrand1, T0, 15)[0]

fig, ax = plt.subplots()
im = ax.pcolormesh(a,b,W)
#plt.show()


fig.colorbar(im, ax=ax)
ax.set_title('An Image', size=20)

mpld3.fig_to_html(fig)
mpld3.show()
mpld3.save_html(fig, "AnImage.html")
```

![image](https://user-images.githubusercontent.com/45017235/56692701-0f312880-66e3-11e9-9f41-09fa014ba017.PNG)

Where on the other hand if bokeh is used with the same resolution:

```
from bokeh.plotting import Figure, show
import numpy as np
from math import exp
from scipy.integrate import quad
from bokeh.models import ColumnDataSource, LinearColorMapper

Image = Figure(x_range=(0, 5), y_range=(0, 5),
                            x_axis_label='b', y_axis_label='a',
                            title="An Image",  width=400, height=400)
Image_source = ColumnDataSource(data={'a': [],'b':[],'W':[]})
color_mapper = LinearColorMapper(palette="Spectral11")

Resolution=60
amp=1
T0=2
a = np.linspace(0.1, 5, Resolution)
b = np.linspace(0.1, 5, Resolution)
W = np.zeros((Resolut, Resolution))

for i in range (0,Resolution):
    for j in range (0,Resolution):
        def integrand1(t):
            output = a[i]**-0.5 * amp * (t-b[j])/a[i] * exp(-( (t-b[j])/a[i] )**2.0)
            return output
        W[i][j]=quad(integrand1, T0, 15)[0]

Image_source.data = {'a': [a],'b':[b],'W':[W]}
Image.image(image="W", source=Image_source, color_mapper=color_mapper, x=0, y=0, dw=5, dh=5)
show(Image)
```
![bokeh image](https://user-images.githubusercontent.com/45017235/56693908-d6df1980-66e5-11e9-8204-13f4cbca6b53.PNG)


Please note that the mpld3 library also provides `save_json()` function which save a JSON representation of a figure to file.
Now what do you suggest?

**Comment by jbednar** [comment]
If that's the only reason to use MPL, that's not a very good reason! :-)  E.g. you can have smooth colormaps in Bokeh if you use a 256-color palette:

![image](https://user-images.githubusercontent.com/1695496/56695916-e5aad980-66af-11e9-8a59-407b2f5ca543.png)

Or you can use HoloViews to generate a Bokeh figure; HoloViews interpolates shorter colormaps in the same way as MPL:

![image](https://user-images.githubusercontent.com/1695496/56695954-06732f00-66b0-11e9-9180-63a7ea450cb0.png)

**Comment by bryevdv** [comment]
> What I am actually trying to do is, read an html file containing a matplotlib figure (converted to html using mpld3 library) and embed it in my Bokeh app.

I don't understand the original issue then -- it's only about embedding Bokeh HTML output and has nothing at all about embedding images (or whatever) from MPL. That's a completely separate question, and putting `img` tags in bokeh divs is well demonstrated. In any case, I'd like to re-iterate that this seems to be a support question, so I'd ask again that it continue on the mailing list, not the issue tracker.

**Comment by jbednar** [comment]
(a) the original issue never says that it was a *Bokeh* figure, though that was confusing!, and (b) the output from mpld3 is not an image, it's interactive HTML, so embedding an image doesn't address it.  In any case, sure, would be appropriate for the mailing list.

**Comment by bryevdv** [comment]
I think it does explicitly say that it means Bokeh content: 

> For example, here I am creating a plot and saving it as an html and reading the html file back using Div

The following code creates a plot using Bokeh, attempts to save it as html (but forgot to call save) and then tries to load that html back

**Comment by jbednar** [comment]
Sure, but it says that's just an example.  Yes, misleading, but not inaccurate, and trying to express things in a way that is relevant to the repo the issue is filed on is generally a good thing...
