### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MaralAfris** [bokeh/bokeh#8870]
Info:
Python 3.7.3
bokeh 1.0.4

Hi,

I run a bokeh server to plot data in different tabs and handle events from the main server app in order to update all plots when someone clicks on one of the plots.
So far I do it using Selection, which works fine but I would like to do it using Tap and/or DoubleTap.
The problem is that it seems Tap and DoubleTap do not generate events on the server. I can trigger a callback on a plot using those but can't get an event in the server.

Is it the intended behavior? If so, is there a way to trigger a custom server event from the local callback?

Here is an example, here I would like to see the print:
Server Unknown event <bokeh.document.events.Tap object at 0x...>

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from bokeh.io import curdoc
from bokeh.events import Tap
from bokeh.models.widgets import Tabs, Panel
from bokeh.models import Selection, ColumnDataSource
from bokeh.plotting import figure
import pandas as pd

def on_local_tap(event):
    print('Local event', event, event.x)

def on_plot_select(event):
    print('Server Select event', event.document, event.new[0])


def on_unknown_event(event):
    print('Server Unknown event', event, event.attr, event.model)


def on_event(event):
    ''' Filters events according to usage '''
    if isinstance(event.model, Selection):
        on_plot_select(event)
    else:
        on_unknown_event(event)


source = ColumnDataSource(pd.DataFrame({'x': [x for x in range(10)],
                                        'q': [1 for x in range(10)]}))
p = figure(tools='tap, box_select')
p.line('x', 'q', source=source)
p.on_event(Tap, on_local_tap)

tab1 = Panel(child=p)
tabs = Tabs(tabs=[tab1])

curdoc().add_root(tabs)
curdoc().on_change(on_event)
```

**Comment by bryevdv** [comment]
I just confirmed that things are working as expected both js and server side in `examples/howto/events_app.py`:

<img width="492" alt="Screen Shot 2019-04-25 at 9 53 08 PM" src="https://user-images.githubusercontent.com/1078448/56784305-a14d3580-67a4-11e9-9df1-7c3c9417afc6.png">

<img width="945" alt="Screen Shot 2019-04-25 at 9 53 19 PM" src="https://user-images.githubusercontent.com/1078448/56784307-a3af8f80-67a4-11e9-83a6-50b6c0619ee6.png">

Given that, since I don't really understand what you are trying to accomplish, I will ask that this conversation move to the mailing list as it really seems to be a support/usage question. 

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by bryevdv** [comment]
I will add: I just noticed you are trying to use a box select tool with a line, which is not currently supported. Line only supports point and span hit testing util someone implements box hit testing (there are open questions about what should happen with highlighting that have never been answered)

**Comment by bryevdv** [comment]
I will also add: `curdoc().on_change` only has to do with changes  model properties. It has nothing to do with events like tap. There is no notion of document events right now. Only events associated with specific models. Basically everything in `events_app.py` is everything supported.

**Comment by MaralAfris** [comment]
I see, is there a way to get the document from the local events?

I am trying to update all plots in the document when an event arrives: when someone clicks on one of the plots, it creates a span at that position which is also placed in other plots.

I would avoid having to keep trace of each figure, so I used the document from server event in order to get plots from there so far.

Really impressed by the reactivity on the issue by the way :)

Thanks for the feedback !

**Comment by bryevdv** [comment]
> I see, is there a way to get the document from the local events? 

I don't actually know what you mean by local events. This isn't terminology we have every used in the project.

**Comment by MaralAfris** [comment]
Oh, sorry.
I mean, when I go in the callback from the figure that I define with on_event, in the callback can I get the document I work on in some way in order to update the rest of the figures in it?

**Comment by bryevdv** [comment]
You should always be able to refer to `curdoc()` on the python side, even in callbacks

**Comment by MaralAfris** [comment]
Oh great. That solves my problem thanks :)
