### ISSUE TITLE
.eps output format

### ISSUE THREAD

**Issue by tarikaltuncu** [bokeh/bokeh#8871]
Hi there! 

I believe many scientists use .eps output format when using matplotlib simply because it's both vectoral, smaller size, and Latex natively supports eps format.

Although Bokeh support svg output which could be converted to any format manually using an external tool, if possible, please think about adding support to export directly in .eps format. 

This would help many people.

Best,

**Comment by bryevdv** [comment]
@tarikaltuncu This would pretty much be 100% contingent on locating a suitable existing tool that can do the conversion. Ideally, a Python library (available on all platforms) that could be leveraged directly by the Bokeh codebase internally. We could also consider running an external process if the only thing available is some command line tool, as long as the tool is available on all platforms. A quick online search was not very promising. The closest thing I could find is `svg2pdf` which is of course, not the same thing. If you would like to see this happen, I urge you to help out directly, by doing some research and trying to find a tool the project could use to support EPS output, and reporting back. Having that information will make for a much stronger, and more consider-able proposal.

**Comment by bryevdv** [comment]
@tarikaltuncu have you had a chance to look in to existing tools?

**Comment by bryevdv** [comment]
Seems unlikely we can do anything here.

**Comment by Abhishek-Deshmukh** [comment]
Hey,
From what I was able to find, [cairoSVG](https://github.com/Kozea/CairoSVG) has svg to pdf, ps and [last year they added in eps](https://github.com/Kozea/CairoSVG/pull/295) as well.
I would be happy to try to somehow integrate it in this if there isn't any problem.

**Comment by bryevdv** [comment]
@Abhishek-Deshmukh cairoSVG is not at all relevant unfortunately. None of Bokeh's rendering happens in Python. All the rendering is done in the browser, either by HTML or WebGL canvas, or via limited browser support for SVG. This is why options are are extremely limited (nonexistent, really)

**Comment by bryevdv** [comment]
@Abhishek-Deshmukh Certainly if you want to give something a try. Please be aware that:

* SVG support currently has some known limitations and bugs
* We would only have `cairoSVG` be an optional dependency

**Comment by Abhishek-Deshmukh** [comment]
Ahh I see, I guess people can just export svg from bokeh and convert it to eps using cairoSVG.

Is the implementation of this really required tho? I mean, mentioning it in the documentation should be fine. From what I'm guessing the code will be equally lengthty whether bokeh gave an API point for it or someone uses cairoSVG after.

**Comment by bryevdv** [comment]
Happy to accept a docs-only PR to add a section to the Exporting chapter too
