### ISSUE TITLE
Add hover support for Patch, HArea, and VArea

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#8872]
Reminded by #8848 that we don't have hover support for `patch`.

We do have hover support for patches, but, as @bryevdv notes "Patch does not, because it's one of the weirdo glyphs that isn't actually vectorized, so will need some special casing."

**Comment by bryevdv** [comment]
Optimistically added to 1.1.1 but more likely to push back to 1.1.2

**Comment by bryevdv** [comment]
Well, will probably be later. It's not hard to add hit testing to Patch, VArea, and HArea, but it's not actually useful unless https://github.com/bokeh/bokeh/pull/7617 is also fixed.

**Comment by bryevdv** [comment]
closed by #9084
