### ISSUE TITLE
Uploading actual releases to conda bokeh/label/dev

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8874]
This suggestion sounds weird at first but uploading the final releases to the bokeh dev channel on anaconda.org results in a much more consistent experience for anyone trying to use the bleeding edge version of bokeh, which is usually the intention behind specifying a dev channel.

As an example if you tried to  ``conda install -c bokeh/label/dev bokeh`` between the 9th of April and the 13th of April you would have ended up with bokeh 1.1.0rc5, which would have been behind the most recent released version. I'd therefore argue that real releases should be tagged with both main and dev tags when uploaded to anaconda.org.

**Comment by bryevdv** [comment]
I'm fine with this if someone wants to submit a PR. Bonus points for going through old releases on anaconda.org and adding tags to them as well.

**Comment by bryevdv** [comment]
OK I took care of the anaconda.org part. Now that the heavy lifting work of making two four clicks is out of the way, @philippjfr can you make the PR to update here

https://github.com/bokeh/bokeh/blob/dc8cf49e4e4302fd38537ad089ece81fbcca4737/scripts/build_upload.py#L359-L363

I'm not sure if there is way to add both channels to the second upload command? Maybe the safest thing to do is to just copy the "dev" upload line to the else block and do them both in separate commands? Tho maybe uploading the same filename in succession is problematic? I don't know, definitely a quick experiment or consult with the internal repo team would be in order.

**Comment by philippjfr** [comment]
You can definitely add multiple labels, it's what we do for pyviz projects. Note however that ``-c`` is deprecated and has been replaced with ``--label``/``-l``. I'll make a PR in a second.

**Comment by philippjfr** [comment]
For reference [here](https://github.com/pyviz/pyctdev/blob/master/pyctdev/_conda.py#L537) is what we use for pyviz projects.
