### ISSUE TITLE
Autocomplete widget value attribute does not reflect selected value , display entered value 

### ISSUE THREAD

**Issue by internshipdeco** [bokeh/bokeh#8877]
![issue](https://user-images.githubusercontent.com/36809439/56949863-aa962380-6b51-11e9-8101-a234ce29e85e.png)

my code is this , i don't know where i m getting wrong. it display whatever value i have entered. fail to  displaying values after selecting from options 

def my_text_input_handler(attr, old, new):
    print("Previous label: " + old)
    print("Updated label: " + new)
text_input = AutocompleteInput()
text_input.completions = ["hello","goodbye","hi","gud"]
text_input.on_change("value", my_text_input_handler)

curdoc().add_root(text_input)

**Comment by bryevdv** [comment]
@internshipdeco The issue template asked for lots of specific information about versions. Please provide it or we will have to close this issue for lack of information needed to investigate.

**Comment by bryevdv** [comment]
Actually, this sounds like the broken behavior before version 1.1 so I am just going to pro-actively close this since no version information was provided. If you can demonstrate an issue with version 1.1 and provide full details, we can re-open

**Comment by internshipdeco** [comment]
@bryevdv, thanks for replying ,i m using PyCharm with following specification,
bokeh info : 
Python version      :  3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 12:45:02) [MSC v.1900 32 bit (Intel)]
IPython version     :  (not installed)
Tornado version     :  6.0.2
Bokeh version       :  1.1.0
BokehJS static path :  C:\Users\shrikrishna_y\PycharmProjects\CaptialChart\venv\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)

on_change('value', myfunc) does not seem to get triggered when you try to use autocompletion options. If you type what you want directly without using the arrow keys and then press enter, on_change triggers successfully. 

from bokeh.models.widgets.inputs import AutocompleteInput
from bokeh.io import curdoc, show
def my_text_input_handler(attr, old, new):
    print("Updated label: " + text_input.value)
text_input = AutocompleteInput()
text_input.completions = ["hello","good","target","helpful"]
text_input.on_change("value", my_text_input_handler)
curdoc().add_root(text_input)

hope all this information is enough
