### ISSUE TITLE
Plot in Tooltip

### ISSUE THREAD

**Issue by sebhan2** [bokeh/bokeh#8878]
Hello,
I am trying  to create a hovertool box with a custom figure inside the tooltip box. The figure should show a line based on values that are saved in an object variable. Is there a way to accomplish this. 
Thanks for your help!
Best regards

**Comment by jogehl** [comment]
I have an similar problem. I want to plot some things in the free space inside of a circle. Is there any way to do this?
Kind regards

**Comment by bryevdv** [comment]
There is nothing built in to Bokeh to put plots inside hover tooltips. It might be possible to accomplish something with a Custom HTML hover or even a customjs tooltip field. However, the issue tracker is not the appropriate place to iterate and experiment on something like that, so I I'll as that we move this discussion to the mailing list for now:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

If that discussion results in any tangible detailed feature requests, we can then open issues on the tracker.

**Comment by jogehl** [comment]
You can use SVG line plots to plot a line or other shapes in the tooltip. If you don't use any JavaScript it can be easily inserted in the HoverTool from boke
