### ISSUE TITLE
[FEATURE] Export to PNG without phantomjs

### ISSUE THREAD

**Issue by ispmarin** [bokeh/bokeh#8881]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).

**Is your feature request related to a problem? Please describe.**
I´m having to export my graphs to PNG because they´re getting very large and vey slow to plot from a Jupyter notebook. I also need to communicate these results in different formats and html is not an option. I´m also working on a restricted platform, so installing non-python dependencies are impossible.

**Describe the solution you'd like**
A method that I can call to export the graphics directly, without having to render in phantomjs or other external libraries.

**Describe alternatives you've considered**
The only real alternative in my case is to do a screenshot of the graph from the notebook, what is very cumbersome.

**Additional context**
My main problem is my restricted environment, where I can´t install anything outside Python packages and just a few at that. The plot rendering time is another component, and if it takes 3 minutes to generate my graph layout, exporting would take way longer.

**Comment by mattpap** [comment]
There is no way around having some sort of web browser around to render bokeh plots. bokeh, the Python library, is just a convenient API on top of a (JSON) visualization specification, which is rendered by bokehjs, which requires a web browser to run, either a full fledged one, a headless one (e.g. phantomjs) or a Frankenstein node.js environment trying to emulate a web browser. phantomjs can be installed without administrator permissions with conda or possibly with pip (I'm not sure how much that's actually worth). Alternatively you could reuse a web browser installed on your system, either Chrome or Firefox. Both support headless rendering these days. See https://github.com/bokeh/bokeh/issues/8176 for how to achieve this.

**Comment by bryevdv** [comment]
Just to expand on @mattpap's excellent answer about the current state of affairs. I will mention that from time to time, and especially very early on ~5 years ago, the idea of a non-browser backend was bandied about. E.g. a library that could ingest BokehJSON and render using Cairo or Age or whatever. However:

* that would be a huge effort to accomplish
* the result would never be able to be guaranteed to match browser output exactly
* it could not work at all with (but would have to not fall over if given) Bokeh widgets
* we have nowhere near the resourcing needed to undertake such a task

So, it's never been done, and I don't expect it ever will be. Tho if anyone wants to try, I would certainly be happy to advise from a distance.
