### ISSUE TITLE
[BUG] ColumnDataSource with callback assigned triggers bug when selected.indices is changed by another callback

### ISSUE THREAD

**Issue by dtork** [bokeh/bokeh#8882]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages):
MacOS High Sierra, version 10.13.6
Python3
Bokeh Server version 1.1.0
Pandas 0.24.1
Google Chrome version 73.0.3683.103 (Official Build) (64-bit) 

#### Description of expected behavior and the observed behavior
Added a callback to ColumnDataSource_parent (CDS_parent) so that when a row is selected in CDS_parent another ColumnDataSource_child (CDS_child) is changed in terms of data values and selection (i.e. clear any selection). This seems to work fine except when CDS_child has a callback assigned to it. Same problem arises when a button is assigned a callback that tries to reset the selection in CDS_parent. My hypothesis is that when a CDS has a callback assigned to it then a bug is triggered preventing any callback from changing `selected.indices` of the CDS.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import pandas as pd
from bokeh.io import curdoc
from bokeh.layouts import column, row
from bokeh.models import (
    ColumnDataSource, Button,
    DataTable, TableColumn, PreText
)

# Data setup
df_data = pd.DataFrame(
    {
        'parent': ['p1', 'p1', 'p1', 'p2', 'p2', 'p3', 'p3', 'p3'],
        'child': ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8'],
        'age': [10, 12, 17, 20, 22, 30, 31, 35],
    }
)

df_parent = (
    df_data.groupby('parent', as_index=False)
        .agg({'child': 'count', 'age': 'mean'})
        .rename(columns={'child': 'num_children', 'age': 'avg_age'})
)

# Widgets for parent DataTable
text_parent = PreText(text="""
1. Select parent row in table (left)
> Table (right) is populated with children of the selected parent
2. Select/highlight a child from table (right)
3. Select a different parent row in table (left)
> New set of children show up and selection in child table is reset/unhighligted
4. Click button (red) below to clear selected row in table (left)
> Fail, see command terminal for error
""", height=180, width=None)

source_parent = ColumnDataSource(df_parent)
datatable_parent = DataTable(
    source=source_parent,
    columns=[
        TableColumn(field="parent", title="parent", width=10),
        TableColumn(field="num_children", title="num_children", width=10),
        TableColumn(field="avg_age", title="avg_age", width=10),
    ], editable=False, selectable=True, sortable=True, height = 120
)
button_parent = Button(label='Clear selected row in table above', button_type="danger")

# Widgets for child DataTable
text_child_a = PreText(text="""
1. Select a row in table (left)
2. Click on button below to clear selected row (Success)
""", height=140, width=None)

text_child_b = PreText(text='Row number selected below: ', height=30)
source_child = ColumnDataSource(pd.DataFrame())
datatable_child = DataTable(
    source=source_child,
    columns=[
        TableColumn(field="parent", title="parent", width=10),
        TableColumn(field="child", title="child", width=10),
        TableColumn(field="age", title="age", width=10),
    ], editable=False, selectable=True, sortable=True, height = 120
)
button_child = Button(label='Clear selected row in table above', button_type="success")

# Callback functions
def callback_source_parent(attr, old, new):
    selected_row_index = new[0]
    parent_selected = source_parent.data['parent'][selected_row_index]
    source_child.data = ColumnDataSource(df_data[df_data['parent']==parent_selected]).data
    source_child.selected.indices = [] # This works because source_child doesn't have a callback assigned to it???

def callback_button_parent():
    source_parent.selected.indices = [] # This fails because source_parent has a callback assigned to it???

def callback_source_child(attr, old, new):
    print('Row number selected below: {}'.format(new[0]))
    text_child_b.text = 'Row number selected below: {}'.format(new[0])

def callback_button_child():
    source_child.selected.indices = [] # This works because source_child doesn't have a callback assigned to it?

# Callback assignments
button_parent.on_click(callback_button_parent)
source_parent.selected.on_change('indices', callback_source_parent)
button_child.on_click(callback_button_child)
# source_child.selected.on_change('indices', callback_source_child)

page = row(
    column(text_parent, datatable_parent, button_parent),
    column(text_child_a, text_child_b, datatable_child, button_child)
)

curdoc().add_root(page)
```

#### Stack traceback and/or browser JavaScript console output
error handling message Message 'EVENT' (revision 1) content: '{"event_name":"button_click","event_values":{"model_id":"1010"}}': IndexError('list index out of range')

#### Screenshots or screencasts of the bug in action
N/A

**Comment by bryevdv** [comment]
Hi. the `IndexError` is to a logic error in you program. Your button click callback does this:
```
source_parent.selected.indices = []
```

This (appropriately) triggers your `callback_source_parent` callback, which immediately tried to access a non-existent list element:
```
selected_row_index = new[0]  # new is an empty list, you set it up above
```

In the future, if it is not 100% certain that an issue is in your code, or with Bokeh itself, please start on the mailing list first:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by dtork** [comment]
@bryevdv Thanks for the quick response. Next time I'll post in the mailing list first :-)

**Comment by dtork** [comment]
The thing I didn't realize was that calling `def callback_button_parent` to execute the line `source_parent.selected.indices = []` triggered `def callback_source_parent` where `new=[]`

**Comment by bryevdv** [comment]
> The thing I didn't realize was that calling def callback_button_parent to execute the line source_parent.selected.indices = [] triggered def callback_source_parent where new=[]

Just to clarify why that happens, it is because you set up this here:
```
source_parent.selected.on_change('indices', callback_source_parent)
```

`source_parent.selected.indices = []` is a change to `source_parent.selected.indices` so the above calls the callback you indicated
