### ISSUE TITLE
TextInput value attribute not updating in JupyterLab

### ISSUE THREAD

**Issue by rtadewald** [bokeh/bokeh#8883]
My issue is pretty simple. The TextInput widget is not responsive to updates.

![Screenshot from 2019-05-01 11-25-42](https://user-images.githubusercontent.com/22618324/57021971-1df86d80-6c04-11e9-9e1d-25d2709fcdf4.png)

**Comment by bryevdv** [comment]
@rtadewald It's not expected to. Bi-drectional updates require the bokeh server (that is what maintains the websocket connection between the browser front end an the python process). It is possible to embed bokeh server apps in notebooks. please see the documentation and examples e.g

https://github.com/bokeh/bokeh/blob/1.1.0/examples/howto/server_embed/notebook_embed.ipynb

**Comment by rtadewald** [comment]
Got it! It worked now.

Thank you so much.
