### ISSUE TITLE
[FEATURE] add a setter for Document.template_variables

### ISSUE THREAD

**Issue by arabidopsis** [bokeh/bokeh#8894]
**Is your feature request related to a problem? Please describe.**

You are able to set a template on a bokeh document but you can't
set any template_variables. e.g.
```
curdoc().template = 'mytemplate.html'
curdoc().template_variables = {'important': 'stuff'} # no...
```
This monkey patch works:

`curdoc()._template_variables =  {'important': 'stuff'}`

**Describe the solution you'd like**

add a setter to `Document.template_variables` to overwrite or merge new template
arguments... possibly checking for bokeh reserved names e.g. root, roots

**Describe alternatives you've considered**
Monkey patching using `_template_variables`

**Additional context**
None

**Comment by bryevdv** [comment]
@arabidopsis FWIW the intended usage is that you *update* the existing dict, not replace it, i.e.
```
curdoc().template_variables['important'] = 'stuff' 
```
or
```
curdoc().template_variables.update(new_vars)
```
That said, I can't offhand see the harm in adding a setter, either, as long as it did some minimal sanity checking. If you would like to submit a Pull Request to add a setter that:

* ensures the value is a dict
* ensures all the keys are strings
* adds a simple test 

Then I would accept it.

**Comment by bryevdv** [comment]
@arabidopsis are you interested in submitting a PR for this?

**Comment by bryevdv** [comment]
Actually the docs already state this:

> Custom variables can be passed to the template via the curdoc().template_variables dictionary in place

Since there was no response about submitting a PR, I will go ahead and close this out
