### ISSUE TITLE
Allow Select to accept non-string option values

### ISSUE THREAD

**Issue by FChmiel** [bokeh/bokeh#8898]
I think it would be useful to have the Select widget values to be any object: for example it maybe useful for the `select.value` to point to a function.

Consider this (hypothetical) instance of a Select widget:

    select = Select(title="Options:",
                    value=do_1,
                    options=[(do_1,"option_1"), (do_2,"option_2"), (do_3,"option_3"), (do_4,"option_4")])

where `do_n` is a previously defined function. I have chosen to have` (value, label)` pairs as options so a user could select an option and the relevant function could be accessed by accessing the value attribute of my widget (i.e., `select.value`). Currently this isn't supported and I will have to store my functions in a dictionary with suitable keys selected by the widget. 

There is a related issue (bug?) that the value attribute fed to initiate the Select widget can only be a String. It would be nice to  to support this kind of functionality:

    select = Select(title="Options:",
                    value=1,
                    options=[(1,"option_1"), (2,"option_2"), (3,"option_3"), (4,"option_4")])

Currently this does not work but in some instances is required (i.e., when using the select widget to access a list and a default value is required).

**Comment by jbednar** [comment]
The [Param](http://param.pyviz.org) library works like this, with the value of a Selector being an actual item (integer, function, etc.) and the [Panel](http://panel.pyviz.org) library being used to make a corresponding Bokeh widget.  See e.g. the `select_fn` parameter in the [Panel Param docs](https://panel.pyviz.org/user_guide/Param.html).  This doesn't change whether Bokeh itself could or should act like this, but I think it does let you do the sort of thing you're asking for, and it might be an approach to consider.

**Comment by FChmiel** [comment]
Thanks for the suggestion, I'll have a read and see if this would be an appropriate solution.

**Comment by bryevdv** [comment]
@FChmiel every Bokeh property is automatically synced between Python and JavaScript, which then implies that the only allowable values are things that *can be* synced. So we could definitely consider expanding the types from string to include numbers or even Bokeh models potentially. But bare Python functions have no JavaScript counterpart, so they will never be an option.

**Comment by bryevdv** [comment]
@FChmiel can you provide the related issue you mentioned? If they are very similar we should consolidate to one issue.

**Comment by FChmiel** [comment]
Ah of course. It would be nice for it to include numbers but understand it can't include a general python function. 
Could you clarify what you mean by 

> can you provide the related issue you mentioned?

Do you mean raise a bug report? 

The issue I though was you can feed in` (value, label)` pairs as option, where value is an `int `and label is a `str`. You cannot however set a default value of the `value` argument to be an `int`. 

I've tested this by plotting graphs but I imagine my values were being converted from ints to strs somewhere, so there may not actually be an issue.

**Comment by bryevdv** [comment]
> Do you mean raise a bug report?

@FChmiel no I think I misinterpreted this:

> There is a related issue (bug?) that the value attribute fed to initiate the Select widget can only be a String. It would be nice to to support this kind of functionality:

to mean there is a related GH issue here somewhere. 

This issue is great for figuring out how to expand supported values in `Select`

**Comment by bryevdv** [comment]
Unfortunately this will be a little more work than I thought, as I started looking into it. Basically, the widget will have to keep track of the value type explicitly, so that it can return values as given. (Right now the DOM element values are stored as strings, so they will have to be converted as necessary) 

Also It occurs to me maybe we could make something with functions work with a little cleverness. Basically a Bokeh model that represent a Python function that would just be a placekeeper on the JS side, but would have a `__call__` so that it behaves nicely for calling. That might be useful ground work for the "simple RPC" task too. So, I'd like to do a proper job on this, but it won't happen before the next release next week.

**Comment by jbednar** [comment]
Sounds good; thanks for looking into this!

**Comment by bryevdv** [comment]
This seems like a nice feature but not crucial and we are behind for 1.4 so I am bumping this out to `short-term` @jbednar if any of your team has bandwidth I am happy to advise on this to get it done sooner (or any other issues of interest to you)
