### ISSUE TITLE
[BUG] Drawn Rectangles no moving with mouse correctly

### ISSUE THREAD

**Issue by sirspoon** [bokeh/bokeh#8900]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Python Version: 3.6.5
bokeh Version: 1.1.0
Browsers: Edge, Chrome,

#### Description of expected behavior and the observed behavior

The rectangle tool when moving drawn rectangles over-exaggerates the movements of the mouse, it's like it's on ice. Rectangle expected to move as per mouse. Thanks.

#### Complete, minimal, self-contained example code that reproduces the issue

```

import bokeh
from bokeh.layouts import layout, row, column
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource
from bokeh.models import Plot      
from bokeh.models import FreehandDrawTool, BoxEditTool
from bokeh.models.tools import HoverTool, WheelZoomTool, BoxZoomTool, UndoTool,RedoTool,ResetTool, SaveTool, PanTool, CrosshairTool, LassoSelectTool

x_range=300
y_range=400

p1=figure(x_range=(0.0, x_range+0.0), y_range=(0.0-y_range,0.0), title="p1",
   toolbar_location="right", tools='', x_axis_location="above")
p2=figure(x_range=p1.x_range, y_range=p1.y_range, title="p2",
   toolbar_location="right", tools='', x_axis_location="above")
p1.y_range.bounds=((0.0-y_range),0.0)

### add shared tools.
wheel_zoom = WheelZoomTool()
pan_tool = PanTool()
box_zoom = BoxZoomTool()
reset = ResetTool()

tools = (wheel_zoom, box_zoom,  pan_tool, reset)
p1.add_tools(*tools)
p2.add_tools(*tools)

#### draw rectangles code
source_r=ColumnDataSource( {"x":[1],"y":[1],"width":[0.1], "height":[0.1]})
r1=p1.rect('x','y','width','height',source=source_r, fill_alpha=0, line_width=4, line_color="yellow", line_alpha=0.8)
r2=p2.rect('x','y','width','height',source=source_r, fill_alpha=0, line_width=4, line_color="yellow", line_alpha=0.8)
boxtool=BoxEditTool(renderers=[r1, r2])
p1.add_tools(boxtool)
p2.add_tools(boxtool)

eg_row=row(p1,p2)

output_file('eg_issue2.html')
show(eg_row)

```

**Comment by philippjfr** [comment]
Seems to be related to the fact that you are reusing the same ColumnDataSource in both plots which seems to be causing the offsets to be applied twice. I don't think tools should be reused across plots like this for this reason, I'd suggest creating two separate BoxEditTools:

```python
boxtool=BoxEditTool(renderers=[r1])
boxtool2=BoxEditTool(renderers=[r2])
p1.add_tools(boxtool)
p2.add_tools(boxtool2)
```

**Comment by sirspoon** [comment]
ok, thanks for explaining. My issue was that originally I only had one toolbar present so you wouldn't have to click on individual tools to draw on individual plots, one toolbar to rule them all.  I guess I'll stick without the rectangles for now until it's implemented (hopefully) at some point in the future.. Many thanks.
