### ISSUE TITLE
[BUG] layout accepts name as keyword arg but doesn't pass to underlying objects

### ISSUE THREAD

**Issue by zdgriffith** [bokeh/bokeh#8903]
#### software version info
bokeh 1.0.4
python 3.7.1

#### Description of expected behavior and the observed behavior
`bokeh.layouts.layout()` should be capable of taking a `name` argument for use in embedding as described [here](https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#standard-template).  Currently you can pass a `name` but it fizzles silently.
#### Complete, minimal, self-contained example code that reproduces the issue

```

from bokeh.plotting import figure
from bokeh.layouts import layout

if __name__ == "__main__":
    fig = figure()
    fig2 = figure()
    lay = layout([fig, fig2], name='test')
    print(lay.name)

```

output:

```
(base) $ python test_layout.py
None
```

Looking at the [underlying code](https://github.com/bokeh/bokeh/blob/master/bokeh/layouts.py#L182), this could be fixed by having `_create_grid()` in `bokeh.layouts` take the remaining `kwargs` and pass to the `column()` or `row()` calls.  I'd be happy to contribute a PR for this provided a fix doesn't already exist that I missed.

**Comment by bryevdv** [comment]
This is is till present in 1.1.1dev so a PR would definitely be appreciated!
