### ISSUE TITLE
[BUG] TextInput widget does not allow entering text on mobile devices

### ISSUE THREAD

**Issue by kassbohm** [bokeh/bokeh#8908]
On mobile devices with Android and Chrome:

Observation: When opening html produced the Python-code below: It's **impossible to enter text**, because keyboard opens but closes immediately after opening.

Expected behaviour appears when opening the same html on Chrome-Desktop on laptop and/or tablet.

```
from bokeh.plotting import show
from bokeh.models import CustomJS, TextInput, Paragraph
from bokeh.layouts import column

message = 'You entered text: '

text_banner = Paragraph(text=message, width=200, height=100)

def cb(text_banner=text_banner):
    user_input = str(cb_obj.value);
    message = 'You entered text: ' + user_input
    text_banner.text = message

text_input = TextInput(value="", title="Enter:", callback=CustomJS.from_py_func(cb))
layout = column(text_input, text_banner)

show(layout)

```
I was told on https://gitter.im/bokeh/bokeh?source=orgpage that mobile devices are currently not tested. But I submit this bug for the case, that this situation will change.

**Comment by bryevdv** [comment]
It would be great if anyone with an android device could test out the text input on this hosted demo:

https://demo.bokeh.org/movies

It's quite possible this is simply resolved at this point but I don't have access to an android device to test.

**Comment by xavArtley** [comment]
I can enter text in input. However it's  hard to release the focus to close the keyboard

**Comment by bryevdv** [comment]
(FYI I am currently updating the demo site to the new release version, so the site itself may be intermittently down)

@xavArtley Thanks for checking, I am not sure what can/should be done. This is far from my area of expertise. Are there examples of text inputs with better mobile interactions that we can refer to? Is this clunkiness just typical for mobile text inputs? If so we could just close this since it works.

**Comment by xavArtley** [comment]
After testing the search input of github. I think we can't do that much since the focus is lost because the page is reload

**Comment by bryevdv** [comment]
@xavArtley just clarifying you think this can be closed at this point then?

**Comment by xavArtley** [comment]
Yes
