### ISSUE TITLE
RangeSlider stuck when modified by pressing the keyboard arrows

### ISSUE THREAD

**Issue by BenZickel** [bokeh/bokeh#8911]
When changing the lower value of a RangeSlider by pressing the keyboard arrows the RangeSlider gets stuck on NaNs.

![image](https://user-images.githubusercontent.com/35469979/57588553-9f160580-751e-11e9-8eb8-7a941c53a1da.png)

Bokeh version: 1.1.0
Platform: Windows
Command line: bokeh serve app

**Comment by bryevdv** [comment]
@BenZickel Please provide a compete script/test case for us to reproduce with.

**Comment by BenZickel** [comment]
The sample code at [https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html#slider](https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html#slider) is enough to replicate the problem if you try moving the slider using the keyboard arrows:

```
from bokeh.io import output_file, show
from bokeh.models.widgets import RangeSlider

output_file("range_slider.html")

range_slider = RangeSlider(start=0, end=10, value=(1,9), step=.1, title="Stuff")

show(range_slider)
```

**Comment by bawalsh3000** [comment]
It looks like the function linked to the keyboard event replaces a two element array with a single value.
Also, the upper value slider doesn't react at all to keyboard events

**Comment by bryevdv** [comment]
@bawalsh3000 since you have dug in some already, if you have the ability to make a stab at a PR it would be helpful and appreciated. I'm not sure when I would be able to look at this more closely.

**Comment by bawalsh3000** [comment]
Not really up to speed with Typescript, but it looks like it could be a
simple fix and I'll give it a stab
