### ISSUE TITLE
[BUG] Error in the bokeh --serve documentation

### ISSUE THREAD

**Issue by Jasper51297** [bokeh/bokeh#8915]
#### Versions:
- Bokeh: 1.1.0
- Python: 3.5.2
- OS: Ubuntu 16.04 LTS
- Browser: Google Chrome 74.0.3729.131

#### Description of expected behavior and the observed behavior
According to `bokeh serve --help` it should be possible to start a Bokeh server with this command:
`bokeh serve --dev script.py` but this throws an error. It won't throw an error if this order is used: `bokeh serve script.py --dev`. I think this is because it sees script.py as an argument of the --dev option. This could be fixed by editing the `bokeh serve --help` documentation and moving the directory or script to the first position in the usage example.
Another small issue is that some of the options for the bokeh serve command are missing on [this page](https://bokeh.pydata.org/en/latest/docs/reference/command/subcommands/serve.html) on the documentation website:
- --index
- --disable-index
- --websocket-max-message-size
- --dev

#### Error message
```
jasper@jasper-Inspiron-7548:~/Desktop$ bokeh serve --dev script.py
ERROR: list index out of range
```

https://stackoverflow.com/questions/56111167/how-to-start-bokeh-server-in-dev-mode

**Comment by bryevdv** [comment]
@Jasper51297 Thanks for the report, the proper fix here is to make it so the position of `--dev` works anywhere.

**Comment by bryevdv** [comment]
So it turns out the option does have to be last, since it accepts any "left over" orgs. Unfortunately the usage example is auto-generated by argparse so I am not sure we can do anything about it. But I will add a note in the help for the individual option.

**Comment by bryevdv** [comment]
Right so more specifically, the files accepts `nargs=*` and so does `--dev`. It works to put any other option in between, e.g.
```
bokeh serve --dev --show sliders.py
```
Becuase then argparse knows how to apportion the leftover args. I will see if  can move `--dev` up in the help list, and also add the note.
