### ISSUE TITLE
[FEATURE] Optional valid values list attribute for DatePicker

### ISSUE THREAD

**Issue by zdgriffith** [bokeh/bokeh#8917]
It would be nice to be able to give the DatePicker widget a list of valid dates, such that within the minimum and maximum date range only the dates in the list are able to be selected.  Ideally this would also grey out the invalid dates just like dates outside the range given are marked now (example below).

![image](https://user-images.githubusercontent.com/17169544/57723539-72610b80-764e-11e9-895e-a678c7f45813.png)

I'd imagine this involves the JavaScript/TypeScript side of things which I have no experience in, but if someone in the know thinks this is would be a smaller job and could point me in the right direction I'd be happy to take a crack at it.

**Comment by bryevdv** [comment]
Looks like `pikaday` has a `disableDayFn` which requires passing a JS function to return true/false for every day in the view to specify if it is selectable:

https://github.com/Pikaday/Pikaday

That's not really ideal but also not impossible to work with.

**Comment by bryevdv** [comment]
#9509 fixes this and many other datepicker issues (as well as adds selenium tests) but note that the implementaton was switched to Flatpickr, and also now date values can *only* be expressed as ISO date strings, or `datetime.date` and nothing else (in particular no more datetime values which caused endless trouble with time zones)
