### ISSUE TITLE
[BUG] DataTable copy-paste doesn't keep the order of rows after sorting

### ISSUE THREAD

**Issue by deazzz** [bokeh/bokeh#8923]
ubuntu/16.04
firefox/66.0.5 (64-bit)
chrome/74.0.3729.157 (64-bit)
bokeh/1.1.0

Copy-pasting rows from a bokeh gallery example:
https://demo.bokeh.org/export_csv
after sorting that DataTable by `Employee Name`, results in out of order data:
```
97	Abdul Crooks	38581.7791509	3
88	Akeem Pfannerstill	26974.3379311	2
12	Alayna Goyette	44427.462095099996	5
4	Alford Rau	37929.3731943	6
56	Abbey Ziemann	42864.5023151	2
```

The expected row order would be the one a user sees after sorting,
```
56	Abbey Ziemann	42864.5023151	2
97	Abdul Crooks	38581.7791509	3
88	Akeem Pfannerstill	26974.3379311	2
12	Alayna Goyette	44427.462095099996	5
4	Alford Rau	37929.3731943	6
```

**Comment by ivan-usov** [comment]
Having a closer look, it seems that it's always the last row which needs to be moved to the first position.
