### ISSUE TITLE
Allow to derive ColorBar's low/high from data

### ISSUE THREAD

**Issue by harmbuisman** [bokeh/bokeh#8924]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 1.10.0
python: 3.7.3
OS: Windows 10
browser: all

#### Description of expected behavior and the observed behavior
ColorBar tick labels do not show for geoplot patch plots. See the added image. Expectation: labels with the values for each color next to the legend.

Fails in both notebook version and standalone Bokeh server, on all browsers

The code in #8724 does show the colorbar labels, suggesting it could be related to using patches for filling the figure.

To run the code, you need the following geojson file:
[provinces.zip](https://github.com/bokeh/bokeh/files/3198886/provinces.zip)

#### Complete, minimal, self-contained example code that reproduces the issue

```
import geopandas as gpd 
from bokeh.palettes import Reds
from bokeh.models import GeoJSONDataSource, LinearColorMapper, ColorBar
from bokeh.plotting import figure, show

geodf = gpd.read_file("provinces.geojson")

color_mapper = LinearColorMapper(palette=Reds[9][::-1])
color_bar = ColorBar(color_mapper=color_mapper, 
                     location=(0,0),
                     label_standoff=8, )

p = figure()
geo_source = GeoJSONDataSource(geojson=geodf.to_json())
p.patches('xs', 'ys', fill_alpha=1, 
              fill_color={'field': 'index', 'transform': color_mapper}, 
              line_color='white', line_width=0.5, 
              source=geo_source)

p.add_layout(color_bar,'right')

show(p)
```

#### Screenshots or screencasts of the bug in action
![bokeh_plot](https://user-images.githubusercontent.com/7702207/58038041-2f5fd600-7b2f-11e9-8c65-0ff99a3d028e.png)

**Comment by harmbuisman** [comment]
Closed as low and high are needed for labels, they are not derived from the data.

**Comment by mattpap** [comment]
I will leave this open. We have ongoing work to allow derivation of low/high from data, among other things (PR #8922).
