### ISSUE TITLE
[FEATURE]Change date format of DatePicker

### ISSUE THREAD

**Issue by Hacky-DH** [bokeh/bokeh#8926]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).

**Is your feature request related to a problem? Please describe.**
I want to change date format of the DatePicker to local date format.
So for the DatePicker value is Wed May 22 2019, but 05-22-2019 or 2019-05-22 is desired

**Describe the solution you'd like**
The DatePicker class supports a format parameter

**Describe alternatives you've considered**

**Additional context**
windows 10
bokeh 0.13.0

**Comment by bryevdv** [comment]
Pikaday appears to support formatting dates throught built-in JS `Date` by default (I doubt we could justify taking on a dependency on `momentjs` just for this)

https://github.com/Pikaday/Pikaday

**Comment by Hacky-DH** [comment]
Thanks for the reply.
I am really looking forward to this feature.

**Comment by bryevdv** [comment]
noting that the implementation is changing from Pikaday to Flatpickr for 2.0 and it has this capability built in AFAIK
