### ISSUE TITLE
[FEATURE] Tabs lazy evaluation (loads only when clicked on)

### ISSUE THREAD

**Issue by devmood** [bokeh/bokeh#8928]
bokeh: 1.1.0dev11
python: 3.7.2
OS: Ubuntu 18.04.2 LTS
browser: Mozilla Firefox Quantum 66.0.5

I've been developing a following visualization dashboard (standalone web page) lately and I believe bokeh would benefit from having a feature allowing lazy tabs loading so that the canvases would not plot / resize while not being in an active mode (selected tab). Although, callback attached to the `CheckboxGroup` elements works pretty smoothly, plot resizing becomes more and more laggy and time-consuming with the growth of the number of tabs. Removal of the other tabs (performed as a part of the test) almost entirely gets rid of the problem and everything works really well. I'm pretty sure if only currently checked tab's contents were being loaded, the whole process would become way more user-friendly and responsive.

![Screenshot_2019-05-24 Bokeh Plot](https://user-images.githubusercontent.com/32578489/58325855-5ec25b80-7e2b-11e9-8740-7dc73fdd57c8.png)

Besides the feature request, in case it's already achievable, is there a way to achieve such behaviour given current bokeh implementation? If not, is it in any of Your close-future plans?

**Comment by philippjfr** [comment]
You can achieve this already by listening to the active property of the Tabs and then populating the currently active tab.

**Comment by jukiewiczm** [comment]
@philippjfr 
How can you populate/depopulate the currently active Tab?
One thing that's not included in the feature request is that it is about a standalone webpage without the bokeh server (I know this because it's my colleague reporting the issue).

**Comment by philippjfr** [comment]
I see, on the server you can dynamically replace the contents of a tab but in a static page this is indeed problematic and there's probably currently no good solution. I do think it makes sense to avoid rendering tab contents which are not currently visible, but this may be problematic in relation to layout computations (@mattpap would know more about the details of that).

**Comment by mattpap** [comment]
I will close this in favor of older issue #7438.

**Comment by devmood** [comment]
All right. Thanks for the quick response.
