### ISSUE TITLE
[BUG] DatePicker Displayed Value is not Updating

### ISSUE THREAD

**Issue by Fredericco72** [bokeh/bokeh#8934]
### My current installation:
Python version      :  3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
IPython version     :  7.1.1
Tornado version     :  5.1.1
Bokeh version       :  1.1.0
BokehJS static path :  c:\python36\lib\site-packages\bokeh\server\static
node.js version     :  v10.15.3
npm version         :  6.4.1

### My problem:

When using an script to update the DatePicker widget's value it updates the underlying value but not the displayed value.

### Working example:

I'm using ``` python.exe -m bokeh serve text.py --dev``` to run the server locally

Code:
```
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models.widgets.buttons import Button
from bokeh.models.widgets.inputs import DatePicker
from bokeh.models.widgets import Paragraph

from datetime import date

def click_event(e):
    para1.text = str(dp.value)
    dp.value = date(2019,2,1)
    para2.text = str(dp.value)

dp = DatePicker(value=date(2019,1,10), min_date=date(2019,1,1), max_date=date(2019,2,28))

btn = Button(label='Click Me!')

para1 = Paragraph(text='')

para2 = Paragraph(text='')

btn.on_click(click_event)

curdoc().add_root(column(dp, btn, para1, para2, width=150))

```

### Screen clipping:

![image](https://user-images.githubusercontent.com/33041227/58482278-fc809800-8155-11e9-8ae3-9299555419f1.png)

You can see the initial value of 10th Jan 2019, then the value of the DatePicker updates to 1st Feb 2019 but the DatePicker display still shows 10th Jan 2019.

**Comment by bryevdv** [comment]
NOTE: #9509 re-fixes this and many other datepicker issues (as well as adds selenium tests) but note that the implementatoon was switched to Flatpickr, and also now date values can *only* be expressed as ISO date strings, or `datetime.date` and nothing else (in particular no more datetime values which caused endless trouble with time zones)
