### ISSUE TITLE
Adding support for superscript exponents

### ISSUE THREAD

**Issue by micrenda** [bokeh/bokeh#8954]
It would be very useful to me to have logarictimic axis values written as 10⁴¹ instead than 10^41.

I implemented a patch to add this feature, which add a new property `LogTickFormatter.use_superscript_exponents`:
https://github.com/micrenda/bokeh/tree/use_superscript_exponents

But there are two pending issues:
1. It seems that this code is just ignored:
`p.xaxis[0].formatter.use_superscript_exponents = True`
(an expert Bokeh developer will surely find a solution)

2. The exponents from 1 to 3 are rendered with a smaller font (I think this is a font related issues, changing fonts may help).

**Comment by bryevdv** [comment]
@micrenda In order see see effects from changes to the BokehJS source code, you have to: 

* compile BokehJS locally from the source
* tell Bokeh to use your locally-built version (e.g. by setting `BOKEH_RESOURCES`)

These steps are described in the [Developer Guide]9https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup). I'd suggest going through that (I can answer any questions you have along the way) and then submitting a Pull Request to add this feature (we can discuss iterate on any changes in a Pull Request)

This seems like a reasonable thing and a small change, so I'd be pleased to consider a Pull Request from you

**Comment by micrenda** [comment]
Thank you @bryevdv for your fast and kind response. I was able to fix the issue nr. 1 and to test it locally.

If you decide to accept my pull request, please be aware there is a small problem with the font size. It is not the fault of bokeh, but it is possible you will receive some complaints. Changing fonts may help (here you can find [more details]( https://graphicdesign.stackexchange.com/questions/66878/unicode-superscript-numbers-1-to-3-vs-4-and-above))
![bokeh_plot](https://user-images.githubusercontent.com/774993/58700773-ae63d280-83a9-11e9-8871-f53268437883.png)

**Comment by micrenda** [comment]
Setting this solve the problem with different superscript sizes:
`p.axis.major_label_text_font = "sans"`

**Comment by bryevdv** [comment]
going also to close this in favor of existing #6036

**Comment by bryevdv** [comment]
noting that #10828 will add support for superscript exponents even without mathtext support

**Comment by bryevdv** [comment]
re-opening to close with #10828
