### ISSUE TITLE
issues with dateslider/types 

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#896]
@mattpap we need to look into how datetimes should be handled with the time slider + our serialization

in the downloads app, they are first set as dates, and then coerced into millis, which work.  But then if you do anything in the app before sliding the date range, they come back as millis which pandas interps as nanos, and so the plot is empty.

But when we slide the slider, the values come out as strings, which pandas can handle

**Comment by bryevdv** [comment]
@mattpap is this still an issue?

**Comment by mattpap** [comment]
I didn't yet touch date/time serialization, so the issue mostly likely persists.

**Comment by bryevdv** [comment]
The app in question is gone, and there is currently not a date range slider.
