### ISSUE TITLE
Set use_strict to default to True

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#8966]
@mattpap do you mean to have the default change to `True` or remove `use_strict` option entirely and always apply?

**Comment by mattpap** [comment]
The default should be `True` and option removed.

**Comment by mattpap** [comment]
Is github broken, because all those `landing-2.0` issues aren't closed automatically when PRs close?

**Comment by bryevdv** [comment]
I was wondering the same thing, I am assuming auto-close only functions on master, evidently, but I have not enquired or looked into it further
