### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by internshipdeco** [bokeh/bokeh#8978]
Hover tool is not working properly on vbar graphs. it display only values of x-axis, for y-axis value it show "???". Below i have given my code, kindly point out me where i am going wrong.
![Untitled](https://user-images.githubusercontent.com/36809439/58882402-ca44dc80-86f9-11e9-9085-fc041b3642ff.png)

from bokeh.io import show, output_file, curdoc
from bokeh.models import ColumnDataSource, FactorRange
from bokeh.plotting import figure

import numpy as np
x =np.arange(1000)
y =np.random.random(100)
source = ColumnDataSource(data=dict(x=x, y=y))

plots = figure(plot_width = 1300, plot_height = 400,tools ="hover",tooltips=[("Date", "@x"), ("Volume", "@y")])
plots.vbar(x, width = 1, bottom = 0, top = y)
curdoc().add_root(plots)

**Comment by bryevdv** [comment]
This is not a bug, you are not configuring the HoverTool correctly. However, GH is not the appropriate place for support discussions. I would be happy to help you if you posts your question in the Discourse:

https://discourse.bokeh.org/c/community-support

**Comment by internshipdeco** [comment]
Thank you for your support 👍
