### ISSUE TITLE
Overlay Hexbin on Google Map

### ISSUE THREAD

**Issue by xys234** [bokeh/bokeh#8982]
I understand hexbin function returns (q, r) in axial coordinate system and the hextile function also expects the data in axial system. However, the gmap is in Cartesian system. Is there a way to overlay a hexbin glyph on a gmap?

**Comment by bryevdv** [comment]
Certainly possible in principle, but there's nothing built in to bokeh to do the necessary transformations. So it would take some figuring out. However, that's a support topic, so GitHub is not the appropriate place to discuss it. Please feel free to open a new topic on the public Discourse site:

https://discourse.bokeh.org/c/community-support
