### ISSUE TITLE
[BUG] Using pandas index in CDS does not update in bokeh serve

### ISSUE THREAD

**Issue by kasuteru** [bokeh/bokeh#8983]
I noticed inconsistent behaviour when using the pandas index (pandas.DataFrame.index) when e.g. plotting a line in bokeh serve and then changing the underlying data later. Basically, when creating a dataframe like this:

```
df1 = pd.DataFrame({"a":[1,2,3],"b":[1,2,3]})
source = ColumnDataSource(df1)
```
I can then add a line plot the following way:
```
fig = figure()
fig.line(x="index", y="b", source=source)
```
since the pd.DataFrame.index is automatically added to the CDS as well (which is nice, but might not be intended?

The problem is, that when later updating the CDS, e.g. like this:

```
def on_update_segments():
  source.data =  df2.to_dict(orient="list")
```
I get inconsistent behaviour. I did some testing and found the following cases, shown in the code samples below.

1) `fig.line(x="a", y="b", source=source)` -> Updating this works as expected, since we aren't using the index at all.

2)  `fig.line(x="index", y="b", source=source)` -> If I update this with a different dataframe, it does not update at all. If the new dataframe has fewer rows, it deletes some from the first one, but it always seems to keep the data from the first one.

3) Special case: Having an "index" column in the dataframes, like this:
```
df1 = pd.DataFrame({"index":[1,2,3],"b":[1,2,3]})
df2 = pd.DataFrame({"index":[1,2],"b":[4,4]})
df1 = pd.DataFrame({"index":[1,2,3],"b":[1,2,3]})
```
sometimes works and sometimes doesn't.

I think bokeh should at least throw a warning when using the index, or even an error if the bug in 2.) cannot be fixed. Currently, the behavior seems undefined (unless I missed that in the documentation?) when having the index and also the index column. 

Issue noticed in bokeh 1.1.0 AND 1.2.0 (current).
Windows 10, all Browsers.

#### 1.) Works as expected

```
import pandas as pd

from bokeh.layouts import column
from bokeh.models.widgets import Button
from bokeh.plotting import figure, ColumnDataSource, curdoc

df1 = pd.DataFrame({"a":[1,2,3],"b":[1,2,3]})
df2 = pd.DataFrame({"a":[1,2],"b":[4,4]})

source = ColumnDataSource(df1)

fig = figure()
fig.line(x="a", y="b", source=source)

button_update_curves = Button(label="Update", button_type="success")

def on_update_segments():
  source.data =  df2.to_dict(orient="list")
button_update_curves.on_click(on_update_segments)

# Show
layout_tagging = column(fig, button_update_curves)
curdoc().add_root(layout_tagging)

```

#### Does not work:
```

import pandas as pd

from bokeh.layouts import column
from bokeh.models.widgets import Button
from bokeh.plotting import figure, ColumnDataSource, curdoc

df1 = pd.DataFrame({"a":[1,2,3],"b":[1,2,3]})
df2 = pd.DataFrame({"a":[1,2],"b":[4,4]})

source = ColumnDataSource(df1)

fig = figure()
fig.line(x="index", y="b", source=source)

button_update_curves = Button(label="Update", button_type="success")

def on_update_segments():
  source.data =  df2.to_dict(orient="list")
button_update_curves.on_click(on_update_segments)

# Show
layout_tagging = column(fig, button_update_curves)
curdoc().add_root(layout_tagging)

```

#### Sometimes works, sometimes doesn't:
```

import pandas as pd

from bokeh.layouts import column
from bokeh.models.widgets import Button
from bokeh.plotting import figure, ColumnDataSource, curdoc

df1 = pd.DataFrame({"index":[1,2,3],"b":[1,2,3]})
df2 = pd.DataFrame({"index":[1,2],"b":[4,4]})

source = ColumnDataSource(df1)

fig = figure()
fig.line(x="index", y="b", source=source)

button_update_curves = Button(label="Update", button_type="success")

def on_update_segments():
  source.data =  df2.to_dict(orient="list")
button_update_curves.on_click(on_update_segments)

# Show
layout_tagging = column(fig, button_update_curves)
curdoc().add_root(layout_tagging)

```

**Comment by bryevdv** [comment]
@kasuteru `df.to_dict` drops this index from the output. That's Pandas behavior we have no control over. If you want to the Bokeh behavior that preserves indices, you will need to use Bokeh functions, e.g. this fixes your second example:
```
source.data =  source.from_df(df2)
```
If you are interested in tweaking the documentation (any/all of docstrings user guide sections, etc), then we'd welcome your contribution. Otherwise I am inclined to close this issue.
