### ISSUE TITLE
Modularize CSS

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#8984]
The idea is to drop `*.css` bundles in favor of including individual `*.css` files as proper TypeScript modules (with CSS class names exported for improved static safety).

**Comment by philippjfr** [comment]
This sounds great. Excuse my lack of knowledge about CSS imports but is importing a module which itself imports some css files sufficient to actually load the css in the browser?

**Comment by mattpap** [comment]
> (...) s importing a module which itself imports some css files sufficient to actually load the css in the browser?

No, you have create a new style sheet declaration and add it to the document tree, like this:

https://github.com/bokeh/bokeh/blob/f5eea9d475a08dc7105bf27cb62558f7bd4f6f44/bokeh/util/compiler.py#L401-L415

This will be handled automatically by our build, so that downstream users will be able to just import `*.js` modules without additional processing. On our side there will be a TypeScript AST transformer, which will combine `*.ts` modules (under `sr/lib/styles`) with compiled (from `*.less`) `*.css` files and add this CSS loading code.

**Comment by mattpap** [comment]
From compatibility standpoint, until 2.0 there will be empty `*.css` and `*.min.css` bundles generated, so that users' code can stay unchanged. At 2.0 we will remove all CSS bundles' related code.

**Comment by mattpap** [comment]
This change (with some additional work) will allow to have multiple incompatible versions of bokehjs on one page (at least from CSS perspective, because there is still `Bokeh` JS global). For example, in jupyter lab this will allow loading a CDN version of bokehjs in one tab and a development version in another.
