### ISSUE TITLE
[FEATURE] Modify high and low of a color mapper.

### ISSUE THREAD

**Issue by hadim** [bokeh/bokeh#8991]
I am trying to build a multi-dimensional image viewer using Panel and Bokeh and I would like to provide a slider to modify the scale of the intensities shown on the image.

For this, I would need to modify the color mapper of the Bokeh figure image. I first tried to set the argument `color_mapper` of `fig.image` to a string `color_mapper` so I could set it in a `ColumnDataSource` but it does not work.

Is that possible to set a new color mapper attached to a Bokeh image? Or even better to modify the high and low parameters (avoiding the unnecessary recreation of the color mapper object).

**Comment by hadim** [comment]
The same question also applies to the palette used in the `ColorMapper`. That would be nice to be able to 'dynamically' modify it.

**Comment by bryevdv** [comment]
@hadim GitHub is not the appropriate place for support discussions, as the issue template stated. Please ask your questions on the Discourse: https://discourse.bokeh.org/
