### ISSUE TITLE
[FEATURE] Keep a fixed aspect ratio when zooming with box tool

### ISSUE THREAD

**Issue by hadim** [bokeh/bokeh#8992]
Is that possible to force an equal aspect ratio when zooming using `box_zoom`?

The use case is when zooming on an image, you don't really want to zoom and modify the aspect ratio of the pixel. You want them to stay as a square.

**Comment by bryevdv** [comment]
@hadim GitHubis not the appropriate place for support discussions, as the issue template stated. Please ask your questions on the Discourse: https://discourse.bokeh.org/
