### ISSUE TITLE
documentation: duplicate $name description

### ISSUE THREAD

**Issue by aliamcami** [bokeh/bokeh#8995]
https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#basic-tooltips

$name property has duplicate description

<img width="1024" alt="Screen Shot 2019-06-12 at 20 19 49" src="https://user-images.githubusercontent.com/12300792/59392841-87b17e80-8d4f-11e9-81bd-9cd7cf980f9e.png">

**Comment by bryevdv** [comment]
Thanks for the catch @aliamcami would you like to submit the PR to fix it? The file to update is here:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/tools.rst

**Comment by aliamcami** [comment]
Sure! I opened the PR #8997 to fix this and the other documentation typo (#8994). Thank you!
