### ISSUE TITLE
[BUG] odd display behavior for overlapping glyphs

### ISSUE THREAD

**Issue by omayer** [bokeh/bokeh#8999]
#### ALL software version info

- bokeh server: 1.2.0
- tornado 6.0.2
- python 3.7.3

#### Description of expected behavior and the observed behavior

I am using bokeh to build an interactive application that requires adding/removing glyph locations, often adding/removing many at a time. However, I have found that in some cases when I try to add a glyph location that overlaps an existing one, ALL existing glyphs change their display to transparent and blue (I am assuming the default settings). I think this is a bug and it is causing unwanted behavior in my application.

#### Complete, minimal, self-contained example code that reproduces the issue
Here is a short example that runs on bokeh server, where you tap on a figure to add a lime-green box to the figure at the tap location.

```
from bokeh.models import ColumnDataSource, Column
from bokeh.plotting import figure
from bokeh.events import Tap
from bokeh.io import curdoc

# setup figure
fig = figure(title="glyph test",
             x_range=(0,1000), y_range=(0,1000),
             tools="tap")
fig.toolbar.logo = None
fig.toolbar_location = None

#setup source
source = ColumnDataSource(data=dict(x=[], y=[]))   
fig.circle(source=source,x='x',y='y',
         radius=100,line_color='limegreen',
         fill_color=None,line_width=2)


#on-tap callback
def ontap(event):
    #update coordinate list
    xlist = source.data['x']
    ylist = source.data['y']
    xlist.append(event.x)
    ylist.append(event.y)

    #update source
    source.data = dict(x=xlist, y=ylist)
                     
fig.on_event(Tap, ontap)
layout=Column(fig)
curdoc().add_root(layout)


```
#### Screenshots or screencasts of the bug in action
Separate glyphs appear fine:
<img width="632" alt="Screen Shot 2019-06-13 at 3 39 23 PM" src="https://user-images.githubusercontent.com/5599055/59462338-8b95dd00-8df1-11e9-8bd0-604ee4c24301.png">

Adding a new location, overlapping an existing one causes unintended display behavior:
<img width="623" alt="Screen Shot 2019-06-13 at 3 39 38 PM" src="https://user-images.githubusercontent.com/5599055/59462387-a405f780-8df1-11e9-93ca-04f53abc7f81.png">

Add a new non-overlapping location causes display as a intended:
<img width="620" alt="Screen Shot 2019-06-13 at 3 39 44 PM" src="https://user-images.githubusercontent.com/5599055/59462447-c26bf300-8df1-11e9-8ac3-e7fd6df6a0b9.png">

Video of the example showing unintended display:

![ScreenRecording20190613at3](https://user-images.githubusercontent.com/5599055/59462736-60f85400-8df2-11e9-855b-16bf6906e096.gif)

**Comment by bryevdv** [comment]
@omayer This is not a big, this is the standard highlighting that happens when you select a glyph by tapping a glyph. I.e. when you tap one glyph to select it, all the untapped glyphs shows as "non selected" which bay default is light grey low alpha. If you want different behavior, you will have to explicitly tell Bokeh that, either by:

* setting `renderers` on the `TapTool` to exclude the glyphs that you are clicking on (e.g. `tap_tool.renderers = []` will turn of selection/unselection for all glyphs. Or,

* allow the tool to keep making selections, but change the default appearance: https://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#selected-and-unselected-glyphs

**Comment by bryevdv** [comment]
Also, if you have further usage questions or need more details about this, please take things to the Discourse:

https://discourse.bokeh.org/c/community-support

**Comment by omayer** [comment]
Great. Thanks.
