### ISSUE TITLE
hatch_pattern and svg

### ISSUE THREAD

**Issue by Vitamin9024** [bokeh/bokeh#9001]
When I use output_backend='svg' and a hatch_pattern, the html file never loads (as if it was too many points). The same is with exporting.

Example:
```
f = figure(width=1000, height=500, output_backend='svg')
f.varea(x=[0, 100], y1=[0, 0], y2=[1, 1], alpha=0,
            hatch_pattern="/", hatch_scale=150)
show(f)  # or export_svgs(f, "some.svg") or export_png(f, "some.png")
```

**Comment by mattpap** [comment]
I can reproduce this and this behavior isn't unexpected given that bokehjs is a raster rendering library by default. I suppose this particular issue is fixable, but in any case that would require changes to canvas2svg library (https://github.com/gliffy/canvas2svg/) that we use to convert raster rendering commands to vector. They have an open PR for image embedded, which should be useful to improve performance in this case.
