### ISSUE TITLE
[BUG] Impossible to set max widget/column/plot size

### ISSUE THREAD

**Issue by figgis** [bokeh/bokeh#9014]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python 3.7.2
bokeh 1.1.0

#### Description of expected behavior and the observed behavior
We're trying to display a picture in bokeh server which will scale  with the window up to a reasonable defined size.

Only sizing_mode="fixed" seems to be working and uses the provided with and height, anything else scales infinitely 

#### Complete, minimal, self-contained example code that reproduces the issue

```
def thumbnail(source: ColumnDataSource, width: int = 800, height: int = 320):
    """
    Thumbnail
    """
    handler = figure(plot_width=width, plot_height=height,
                     name='thumbnail', sizing_mode='scale_width')
    handler.toolbar.logo = None
    handler.toolbar_location = None
    handler.x_range = Range1d(start=0, end=width)
    handler.y_range = Range1d(start=0, end=height)
    handler.xaxis.visible = None
    handler.yaxis.visible = None
    handler.xgrid.grid_line_color = None
    handler.ygrid.grid_line_color = None
    handler.outline_line_alpha = 0
    thumbnail_update(handler, source, index=0)
    return handler


def thumbnail_update(handler: Figure, source: ColumnDataSource,
                     index: int = 0):
    """
    Load the index thumbnail
    """
    src = Image.open(BytesIO(b64decode(source.data['thumbnail'][index])))
    xdim, ydim = src.size
    source = src.convert('RGBA')
    img = np.empty((ydim, xdim), dtype=np.uint32)
    view = img.view(dtype=np.uint8).reshape((ydim, xdim, 4))
    # Copy the RGBA image into view, flipping it so it comes right-side up
    view[:, :, :] = np.flipud(np.asarray(source))

    # Change figure dimensions based on the new image and update
    handler.plot_height = ydim
    handler.plot_width = xdim
    handler.x_range = Range1d(start=0, end=xdim)
    handler.y_range = Range1d(start=0, end=ydim)
    handler.image_rgba(image=[view], x=0, y=0, dw=xdim, dh=ydim)


```

#### Screenshots or screencasts of the bug in action
![bokeh_image](https://user-images.githubusercontent.com/124234/59761907-3c8af480-9296-11e9-9b80-f940d7f68311.png)

**Comment by figgis** [comment]
using ffmpeg we extract some metadata from a video an convert each frame into a thumbnail, then we plot a bunch of stuff, like bitrate and if you click on plot we display the corresponding thumbnail. This was the only way we could think about to link mouse event in plot to update image.

Is there an example available on updating `Div` content from bokeh?

I'll see if I  can provide a MWE. Give me a day or so :-)

**Comment by bryevdv** [comment]
Here is an example Bokeh server app. You could accomplish the same thing with a `CustomJS` callback in a non-server case.
```
from bokeh.io import curdoc
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, Div
from bokeh.plotting import figure

source = ColumnDataSource(data={
    'x'     : [1, 2, 3],
    'y'     : [4, 5, 6],
    'extra' : ["foo", "bar", "baz"],
})

plot = figure(title="Click the circles", tools="tap")
plot.circle('x', 'y', size=20, source=source)

div = Div()

def callback(attr, old, new):
    div.text = " ".join(source.data['extra'][i] for i in new)  # Update the Div

source.selected.on_change('indices', callback)

curdoc().add_root(column(plot, div))
```

**Comment by figgis** [comment]
Here is a MWE. 

The idea is that we want the plot to scale up to a maximum defined value (horiz and vert) and not indefinitely as it is now.
 
```
from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers

import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import row, column
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Slider, TextInput
from bokeh.plotting import figure

# Set up data
N = 200
x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)
source = ColumnDataSource(data=dict(x=x, y=y))


# Set up plot
plot = figure(plot_height=400, plot_width=400, title="my sine wave",
              sizing_mode='scale_width',
              tools="crosshair,pan,reset,save,wheel_zoom",
              x_range=[0, 4*np.pi], y_range=[-2.5, 2.5])

plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)


# Set up widgets
freq = Slider(title="frequency", value=1.0, start=0.1, end=5.1, step=0.1)


def update_data(attrname, old, new):

    # Get the current slider values
    k = freq.value

    # Generate the new curve
    x = np.linspace(0, 4*np.pi, N)
    y = np.sin(k*x)

    source.data = dict(x=x, y=y)

freq.on_change('value', update_data)


# Set up layouts and add to document
inputs = column(freq)

curdoc().add_root(row(inputs, plot))
curdoc().title = "Sliders"
```

**Comment by bryevdv** [comment]
> The idea is that we want the plot to scale up to a maximum defined value (horiz and vert) and not indefinitely as it is now.

I'm not sure I understand, when I run your code, with "scale_width", the output appears to be scaled to the width (which means it can extend below the bottom, if you make the window wide), as expected. Are you saying you are seeing something different?

<img width="894" alt="Screen Shot 2019-07-09 at 8 21 06 AM" src="https://user-images.githubusercontent.com/1078448/60901278-870ee980-a222-11e9-939c-55c0b277572f.png">

**Comment by bryevdv** [comment]
If you want the plot to fill the space, even if that means the aspect ratio changes, then you want "stretch", not "scale". The "scale" modes speficically scale both dimensions to always retain the original aspect ratio (even if that means part of the plot goes off screen)
```

But it's a little more work to get things right, you probably want to make the column fixed, and tell the slider to fill it:
from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers

import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import row, column
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Slider, TextInput
from bokeh.plotting import figure

# Set up data
N = 200
x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)
source = ColumnDataSource(data=dict(x=x, y=y))


# Set up plot
plot = figure(plot_height=400, plot_width=400, title="my sine wave",
              tools="crosshair,pan,reset,save,wheel_zoom",
              x_range=[0, 4*np.pi], y_range=[-2.5, 2.5])

plot.line('x', 'y', source=source, line_width=3, line_alpha=0.6)


# Set up widgets
freq = Slider(title="frequency", value=1.0, start=0.1, end=5.1, step=0.1, sizing_mode="scale_width")


def update_data(attrname, old, new):

    # Get the current slider values
    k = freq.value

    # Generate the new curve
    x = np.linspace(0, 4*np.pi, N)
    y = np.sin(k*x)

    source.data = dict(x=x, y=y)

freq.on_change('value', update_data)


# Set up layouts and add to document
inputs = column(freq, sizing_mode="fixed", width=200)

curdoc().add_root(row(inputs, plot, sizing_mode="stretch_both"))
curdoc().title = "Sliders"
```
That yields

<img width="1288" alt="Screen Shot 2019-07-09 at 8 27 00 AM" src="https://user-images.githubusercontent.com/1078448/60901928-a0fcfc00-a223-11e9-94d9-d35de39ec705.png">

**Comment by philippjfr** [comment]
>The idea is that we want the plot to scale up to a maximum defined value (horiz and vert) and not indefinitely as it is now.

I think you are looking for the ``max_width`` and ``max_height`` arguments. If you change your code to:

```python
plot = figure(max_height=400, max_width=400, title="my sine wave",
              sizing_mode='scale_width',
              tools="crosshair,pan,reset,save,wheel_zoom",
              x_range=[0, 4*np.pi], y_range=[-2.5, 2.5])
```

It works as you would expect I believe.

**Comment by figgis** [comment]
This is exactly what I was looking for. Can't find `max_width, height` in the documentation though.

Thanks for the support and sorry for not explaining the problem in a better way.
