### ISSUE TITLE
Allow tooltips to compute and display metrics across source columns

### ISSUE THREAD

**Issue by bill-coman** [bokeh/bokeh#9017]
Hello, 

This is merely a suggestion but perhaps include functionality for computing metrics across columns in the source dataframe.  

Say, for example, I had a dataframe containing various metrics E.G:
quartiles: q1,q2,q3,q4  where the interquartile range(iqr) =q3-q1
_____________________________________________________
    i   |    q1      |     q2      |     q3      |     q4      |   (q3-q1)   |
    0   |            |             |             |             |             |
    1   |            |             |             |             |             |
    2   |            |             |             |             |             |

It would be nice if I could display the iqr in the tooltip along each point without having to add the column to the ColumnDataSource as shown above.  I believe this is the only workaround at this point in time.  

Although, this is a reasonable solution for an example this size, it is not feasible at scale.  Say if I had these metrics for 400 different categories - the dataframe would require 400 extra columns to compute the iqr for each one.

Please correct me if I'm wrong?  
Otherwise I hope this is a helpful suggestion.

Great work by the way folks!

**Comment by bryevdv** [comment]
> It would be nice if I could display the iqr in the tooltip along each point without having to add the column to the ColumnDataSource as shown above. I believe this is the only workaround at this point in time.

Please see [`CustomJSTransform`](https://bokeh.pydata.org/en/latest/docs/reference/models/transforms.html#bokeh.models.transforms.CustomJSTransform) and [`CustomJSHover`](https://bokeh.pydata.org/en/latest/docs/reference/models/tools.html#bokeh.models.tools.CustomJSHover). C.f. search for examples in the `examples` directory. For further usage questions please us the Discourse: https://discourse.bokeh.org
