### ISSUE TITLE
[BUG] Bokeh movies demo auto-scaling larger than browser width

### ISSUE THREAD

**Issue by AntonSavchenko** [bokeh/bokeh#9021]
when I open [https://demo.bokeh.org/movies](https://demo.bokeh.org/movies) demo it scales a bit larger than my browser window (tried with both Chrome and Edge on Win10) regardless of the window size and zoom level, so it always shows horizontal scroll at the bottom.
![Bokeh_movies_demo](https://user-images.githubusercontent.com/22128555/59938789-46f3ec80-9456-11e9-870c-7c52c3fdfe0d.png)

**Comment by philippjfr** [comment]
I've noticed the same thing can happen for the height, e.g. this app https://glaciers.pyviz.demo.anaconda.com/app also uses responsive sizing and goes off screen (very slightly) in my browser:

<img width="1680" alt="Screen Shot 2019-06-21 at 10 00 26 AM" src="https://user-images.githubusercontent.com/1550771/59939029-7e897700-940b-11e9-9f75-43daca07f2b6.png">

**Comment by AntonSavchenko** [comment]
If I were to guess, I'd say some padding between the subplots got larger in a recent version and they did not adjust the plot sizes to account for it...

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by mattpap** [comment]
This was fixed in the recent layout redesign. No overflow anymore, including if margins are set.
