### ISSUE TITLE
[BUG] "Cannot read property 'style' of null" JavaScript error when moving slider

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#9022]
**ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)**
```
Python version      :  2.7.15 (default, Oct  4 2018, 22:42:40) 
IPython version     :  5.8.0
Tornado version     :  4.5.3
Bokeh version       :  1.2.0
BokehJS static path :  /usr/local/lib/python2.7/site-packages/bokeh/server/static
node.js version     :  v10.15.1
npm version         :  6.7.0
```
OS: Mac OS X Yosemite 10.10.5
Browser: Google Chrome  75.0.3770.100 (Official Build) (64-bit)

**Description of expected behavior and the observed behavior**
Expected behavior: No errors should be displayed in JS console
Observed behavior: Error message in JS console:
```
bokeh-widgets-1.2.0.min.js:31 Uncaught TypeError: Cannot read property 'style' of null
    at f (bokeh-widgets-1.2.0.min.js:31)
    at Object.<anonymous> (bokeh-widgets-1.2.0.min.js:31)
    at bokeh-widgets-1.2.0.min.js:32
    at Array.forEach (<anonymous>)
    at bokeh-widgets-1.2.0.min.js:32
    at Array.forEach (<anonymous>)
    at j (bokeh-widgets-1.2.0.min.js:32)
    at bokeh-widgets-1.2.0.min.js:32
    at Array.forEach (<anonymous>)
    at H (bokeh-widgets-1.2.0.min.js:32)
```

**Complete, minimal, self-contained example code that reproduces the issue**
```py
from bokeh.plotting import show
from bokeh.models import Slider

slider = Slider(start=0, end=3, value=0, step=1, show_value = False, tooltips = False)

show(slider)
```

**Comment by bryevdv** [comment]
The proximate cause is setting `tooltips=False` and the ultimate problem is occurring here:

https://github.com/bokeh/bokeh/blob/8f0495bf9e99ff5c0f622d65595893258c73d615/bokehjs/src/lib/models/widgets/abstract_slider.ts#L177-L184

There is no conditioning on the code based on whether tooltips are enabled. 

Thanks for the detailed report @tony-bony if you have some JS experience this would be a nice issue for a new contributor to tackle.

**Comment by tony-bony** [comment]
Sure. I could try but no sooner then in 10-12 days as I'm very busy now to meet some other high-prio deadlines
