### ISSUE TITLE
Simplify remote data sources

### ISSUE THREAD

**Issue by alhoo** [bokeh/bokeh#9029]
When creating the server sent events data source, we noticed that we had made an assumption made that all remote data sources should have polling interval defined. This was not the case with server sent events and we decided to create an new layer for web events that do not have polling interval embedded in them. This caused us to have a bit too many abstract classes with little use.

This is a proposition to remove unneeded web data source, since the code base will be a little bit simpler at the moment when defining the polling interval in the ajax data source.

**Comment by bryevdv** [comment]
This was closed by #9030
