### ISSUE TITLE
[BUG] Spinner only considers 1 decimal

### ISSUE THREAD

**Issue by harmbuisman** [bokeh/bokeh#9035]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh.version = 1.1.0
python: 3.7.3
OS: Windows 10
browser: all

#### Description of expected behavior and the observed behavior
I have a Spinner for numeric input set to a step of 0.01, but the output of the spinner only considers 0.1 changes and values. 

The problem occurs both with changing the value using the spinner up and down buttons and with entering values manually. When entering a value manually the input is reset to single decimal, for the spinner buttons the value is not reset to single decimal points, but the output in the console does show that higher precision than 1 decimal point is ignored.

With the code below check the console while using the spinner's buttons and manual input. See that it only prints out single decimal output.

Expectation:
* I can enter any value manually, regardless of button step size, e.g. if I enter 0.542 and press enter this should update the spinner value to 0.542
* spinner button updates should reflect value, e.g. if I up 0.8 to 0.81, then the value of the spinner should also be 0.81

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models.widgets import Spinner
from bokeh.layouts import layout
from bokeh.plotting import curdoc

spinner = Spinner(low=0.0, step=0.01, value=0.99, high=1.0,
                             title="Spinner:")

def print_spinner(attr, old, new):
    print(attr, old, new)

spinner.on_change('value', print_spinner)

curdoc().add_root(spinner)
```

#### Stack traceback and/or browser JavaScript console output
value 0.99 1
value 1 0.9
value 0.9 0.8
value 0.8 0.7
value 0.7 0.6
value 0.6 0.5
value 0.5 0.3
value 0.3 0.4
value 0.4 0.3

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/7702207/60175570-3d7ed180-9814-11e9-89e8-67f399385512.png)

**Comment by bryevdv** [comment]
I am not sure we can do anything about this. The current behavior, which limits the significant digits of spinner-updated values to the number of significant digits in the step, was introduced in https://github.com/bokeh/bokeh/pull/8796 in response to serious rounding issues that rendered the slider unusable. This I would merely consider an inconvenience, and I am not sure how to do anything about it that would not bring back the bad rounding problems.
