### ISSUE TITLE
[BUG] Can't interact with multiple RangeTools

### ISSUE THREAD

**Issue by cassiotbatista** [bokeh/bokeh#9047]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh.version: 1.2.0
Python version: 3.5.3
OS: Debian GNU/Linux 9.9 (stretch) 
System info: SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
Browser: Google Chrome 75.0.3770.100 and Mozilla Firefox 60.7.2

#### Description of expected behavior and the observed behavior

I'm working on a customised version of the [ridge plot](https://bokeh.pydata.org/en/latest/docs/gallery/ridgeplot.html) with multiple patches. What I wanted was a `RangeTool` object _for each patch of my plot_.  I'm currently using the `add_tools()` method from `plotting.figure` inside a for loop, but even though those multiple `RangeTool` objects do appear as expected, I can only interact with the first one, which means I'm not able to drag or stretch the remaining.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.models import ColumnDataSource, RangeTool, Range1d
from bokeh.plotting import figure
from bokeh.io import show

import numpy as np

NPOINTS = 100
labels = ['Time','To','Be','Free']

def ridge(category, data=None, scale=1.0):
    return list(zip([category]*len(data), scale*data))

p = figure(title='Horizon chart wannabe',
        y_range=labels + [''], # FIXME y_max padd workaround
        x_range=(0, NPOINTS),
        plot_width=1000, plot_height=600,
        toolbar_location=None)

for i, lab in enumerate(labels):
    source = ColumnDataSource(data=dict(x=np.arange(NPOINTS),))
    vector = np.random.rand(NPOINTS-2)
    vector = np.insert(vector, 0, 0) # FIXME
    vector = np.append(vector, 0)    # FIXME 
    y = ridge(lab, data=vector)
    source.add(y, lab)

    renderer = p.patch('x', lab, name=lab,
            color='red', line_color='red', 
            fill_alpha=0.4, line_alpha=0.1,
            source=source)

    range_tool = RangeTool(
            x_range=Range1d((i+1)*5, (i+1)*5+5),
            y_range=Range1d(i+0.5, i+1.5), y_interaction=False)
    range_tool.overlay.fill_color = "navy"
    range_tool.overlay.fill_alpha = 0.2

    p.add_tools(range_tool) # TODO add to `renderer` patch?

show(p)
```

#### Screenshots or screencasts of the bug in action
The red circle comes from the screen recorder and appears when I click with the mouse. It is not related to Bokeh.
![bug](https://user-images.githubusercontent.com/2287025/60756506-7cf7ab80-9fd4-11e9-8321-08c82f6453a5.gif)

**Comment by kylrth** [comment]
Looks like only one RangeTool can be active in a single plot at a time:

![multiple_ranges](https://user-images.githubusercontent.com/5044802/60759360-ae2ea680-9fe9-11e9-8755-fa0f7f05b669.gif)

This can be worked around by using multiple plots, but this should be fixed.

**Comment by bryevdv** [comment]
Ah of course. Currently there is a notion that only a single tool can be active at a time for a given gesture type (e.g. a single "drag" tool). So to extend this we could either:

* make a single RangeTool be potentially responsible for multiple manipulable ranges at once, or 
* broader the "single gesture at a time" assumption, but as little as possible i.e. maybe multiple instances of the same tool type can be active, or tool types that are specially marked. 

Doing the second also gets in to the need to fix the toolbar UI as well, e.g. all the repeated toolbar icons for multiple hover or range tools... we could really use a UI person's help with that.
