### ISSUE TITLE
[DOCS] Developer notes rendered in live docs

### ISSUE THREAD

**Issue by shughes-uk** [bokeh/bokeh#9049]
"TODO rewrite this"
<img width="1892" alt="Screen Shot 2019-07-09 at 12 31 55 PM" src="https://user-images.githubusercontent.com/546891/60917405-c00c8580-a245-11e9-8733-4ecf70485489.png">

**Comment by timsnyder** [comment]
This can probably be folded into #8834

**Comment by bryevdv** [comment]
FYI @timsnyder hoping to have an RC tomorrow and release tuesday or so. If you won't get to this before then let me know and I will make the change in the GH web UI.

**Comment by bryevdv** [comment]
@timsnyder FYI in the interests of time I just pushed a change from the GH web UI to master (living on the edge!)

Fixed in https://github.com/bokeh/bokeh/commit/36ddfe4c39128b07c21138e5fc5f84b6db8e245c
