### ISSUE TITLE
Typo/Misspelling on Mapping Geo Data page[BUG]

### ISSUE THREAD

**Issue by ssleva** [bokeh/bokeh#9050]
There is a typo on the Mapping Geo Data page, link here:
https://bokeh.pydata.org/en/latest/docs/user_guide/geo.html

The sentence currently reads: "Please tell use your use cases through the mailing list or on github so that we can continue to build out these features to meet your needs."

The sentence should read: "Please tell us your use cases through the mailing list or on github so that we can continue to build out these features to meet your needs."

So the first "USE" should be "US"

**Comment by bryevdv** [comment]
Thanks for the catch @ssleva would you like to make the Pull Request to fix this? The relevant file to edit is here:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/geo.rst

**Comment by ssleva** [comment]
Sure.

**Comment by bryevdv** [comment]
I went ahead and fixed it in 3dd0f355e255cb850e970e2472d9664cec379142 in the web UI so it can be sure to be in the next release. Thanks for the catch @ssleva !
