### ISSUE TITLE
CustomJS args breaking HTML generation after updating from 1.0.4

### ISSUE THREAD

**Issue by brentertainer** [bokeh/bokeh#9051]
I recently updated bokeh from 1.0.4 to 1.2.0, and I am experiencing issues with CustomJS. The gist of the problem is that passing certain types of arguments to CustomJS causes errors that prevent anything from being displayed in exported HTML files. Here is a minimal example that reproduces the issue.

``` python
import pandas as pd
import numpy as np
from bokeh.layouts import layout
from bokeh.models import BoxSelectTool, ColumnDataSource, CustomJS
from bokeh.plotting import figure, output_file, show


output_file('bokeh_example.html')

df = pd.DataFrame(columns=['t', 'x', 'y'])
df['t'] = range(1000)
df['x'] = np.random.normal(0, 1, size=1000).cumsum()
df['y'] = np.random.normal(0, 1, size=1000).cumsum()
source = ColumnDataSource(df)

figure_kwargs = {
    "tools": [
        "reset,save",
        BoxSelectTool(dimensions="width")
    ]
}

plots = []
for feature in ['x', 'y']:
    plot = figure(title=feature, **figure_kwargs)
    plot.line('t', feature, source=source)
    plot.circle('t', feature, source=source, alpha=0)
    plots.append(plot)

callback = """\
console.log(plots);
console.log(source);
plots[0].title.text = 'changed0';
plots[1].title.text = 'changed1';\
"""
args = {'source': source, 'plots': plots}

source.selected.js_on_change('indices', CustomJS(code=callback, args=args))

show(layout(plots))
```

With bokeh 1.0.4, the Python and JS code work as expected. In bokeh 1.1.0/1.2.0, the resulting HTML file is empty, and this error is present in the console:

![image](https://user-images.githubusercontent.com/42847267/60990175-712a2300-a30d-11e9-983c-6643822156d2.png)

I believe the issue is specific to the passing of `plots` as an argument to the callback. If I change `callback` and `args` to the following

``` python
callback = """\
console.log(source);\
"""
args = {'source': source}
```

then the HTML file does render the two figures and the (now limited) callback works as expected.

I [originally sought community help on Discourse](https://discourse.bokeh.org/t/customjs-args-after-updating-from-v1-0-4/3732), and was redirected here. From that conversation, I realized this issue is caused by some objects, but not all. For example, passing a list of Figure titles is permitted, but passing a list of Figure renderers is not.

**Comment by bryevdv** [comment]
This is almost certainly and order of initialization issue. i.e. when the `CustomJS` is initialized on the JS side, plots and renderers are not yet initialized, so trying to hook up their events fails. But by chance some things are already initialized (e.g. titles) so they do work.

**Comment by bryevdv** [comment]
This was fixed at some point (working in 2.2)

**Comment by sachamedaer** [comment]
I currently have this exact same issue while updating Bokeh from 2.3.3 to 2.4.

**Comment by mattpap** [comment]
The original example works in bokeh 2.4. You will need to provide more context if the issue persists.
