### ISSUE TITLE
[BUG] Error using AjaxDataSource while x abscissa is DateTime

### ISSUE THREAD

**Issue by slegallamiral** [bokeh/bokeh#9059]
Using Bokeh 1.2.0

I started using AjaxDataSource to update periodically my graphics and everything works fine when x abscissa values are integer. 
I wanted to make it work with dateTime as x-abscissa but my graphics stays empty. Seems that there is a issue with dateTime as x-abscissa

Below my code 
```
def channel(request):
   """http://localhost:8000/api/diagnosis/ is a GET function  
   that returns a dico {"date":[datetime1, datetime2], "distance" : [10,12,5]} """

   source = AjaxDataSource(method="GET",  
                 data_url='http://localhost:8000/api/diagnosis/',  
                 polling_interval=5000) 

   plot = figure(plot_height=400, plot_width=600,
                  tools = 'pan,box_zoom,wheel_zoom,reset',
                  x_axis_type='datetime', x_axis_label='Temps',
                  y_axis_label='Distance')
   plot.line('date', 'distance', line_width=2, source=source)
   plot.toolbar.logo = None
   bokeh_script, bokeh_plot = components(row(plot, sizing_mode="stretch_both"))
   return render(request, 'front/channel.html', locals())
```

**Comment by bryevdv** [comment]
BokehJS expects date times as ms-since-epoch, is that what your REST endpoint is providing?

**Comment by slegallamiral** [comment]
My Rest Api give me date like this : "2019-07-12T16:00:46.082Z".
When I'm not using AjaxDataSource, my bokeh graphics is well displayed. But when I use AjaxDataSource, the bokeh graphics stays empty

**Comment by bryevdv** [comment]
You will have to convert them to proper numerical timestamps, not strings. But this is s support/usage issue so I will direct to the project Discourse to discuss further: https://discourse.bokeh.org
