### ISSUE TITLE
Improve bokeh/util/logconfig.py call signature

### ISSUE THREAD

**Issue by mborus** [bokeh/bokeh#9070]
bokeh/util/logconfig.py 
in branch landing-2.0, version 1.1.0

regarding:
def basicConfig(*args, ''kwargs):

`logging.basicConfig(*args, **kwargs)`
but should only call 
`logging.basicConfig(**kwargs)`

*args should be removed from parameters, it seems that
no other code used args to call it..

### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by bryevdv** [comment]
@mborus do you intend to submit a pr for this?
