### ISSUE TITLE
[DOCS] page for selection tools does not tell users how to get the values/indices of the selection

### ISSUE THREAD

**Issue by GenevieveBuckley** [bokeh/bokeh#9073]
I've been talking with another bokeh user at Scipy 2019 and found we shared very similar frustrations when starting to work with bokeh selections. The problem is the [documentation page for selection tools](https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#boxselecttool
) at bokeh.pydata.org does not include information on how you can get the indices/values after you have selected something.

(It's not that there's no documentation on this, the problem is that it's split up & scattered around the place, plus is difficult to surface on google.)

**Comment by jsignell** [comment]
Is it this one https://bokeh.pydata.org/en/latest/docs/reference/events.html?

**Comment by bryevdv** [comment]
I would suggest the "Data Sources? chapter is a good place to add docs for selections:

* they live on data sources
* that chapter is not already too-overly-long like some others

**Comment by bryevdv** [comment]
OK I am just going to add a very minimal sentence to each tool that mentions that the selections are stored on `source.selected` and links to 

https://docs.bokeh.org/en/latest/docs/reference/models/selections.html#bokeh.models.selections.Selection

which I will also expand to state which selection properties are used in which cases.

**Comment by bryevdv** [comment]
If there are no comments on #9234 by tomorrow I will merge it to close this.
