### ISSUE TITLE
[DOCS] Update links to bokehplots.com, gitter and mailing-list

### ISSUE THREAD

**Issue by timsnyder** [bokeh/bokeh#9080]
Dev documentation still points to https://bokehplots.com/pages/contact.html.  bokehplots.com has out-dated information and is being deprecated.  On the gitter @bryevdv said he want's those links to point to bokeh.org instead.

**Comment by timsnyder** [comment]
@bryevdv , there are a number of links out to bokehplots.com from the release notes in `sphinx/source/docs/releases/` and on blog.bokeh.org.   What are your thoughts on updating those links?  

It's probably right to leave them alone.  I think most people understand that the release notes make sense at the time of release but things get updated as newer releases are made.  However, I could see how you might not want people to hit 404's if bokehplots.com eventually gets taken down.

**Comment by bryevdv** [comment]
If there is a reasonable new link to update to, my ideal preference is definitely that they be updated. That said, I don't think it's a high priority so if it's a lot of work, or excessively tedious, leaving them alone is also fine.

**Comment by timsnyder** [comment]
There aren't that many.  I think most of them are links to the "roadmap" and I see https://bokeh.org/roadmap/ that looks like the right place to link.

After taking the contacts.rst out, I was curious whether Sphinx checked for broken refs in the documentation.  Looks like there is a configuration called 'nitpicky' that can warn about those. https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=nitpicky#confval-nitpicky

Do you guys have any experience with trying to turn on nitpicky?  I'm building the docs right now with it to see if it generates a bunch of garbage or points me at places where contacts needs to be updated.

**Comment by bryevdv** [comment]
The issue with checking links during the build is that it makes the build take longer but more importantly, sometimes the build gets broken due to things outside your control (e.g. we used to check GH issue links, but occasionally GH is down and when that happens the build broke for no good reason). I would very much like to start performing link checks on our site but I think I'd rather do it outside the context of builds (also because there are sites besides the docs that could be checked)

**Comment by timsnyder** [comment]
Makes sense.  Also looks like sphinx nitpicky gets confused about what's available in the autogenerated refguide stuff:
`Warning, treated as error:
/home/ubuntu/environment/sphinx/source/docs/dev_guide/models.rst:41:py:class reference target not found: bokeh.core.properties.Property`

**Comment by timsnyder** [comment]
@bryevdv , has the bokeh-dev mailing list mentioned on the [bindings page](https://bokeh.pydata.org/en/latest/docs/dev_guide/bindings.html) moved onto the discourse as well?

**Comment by bryevdv** [comment]
Bokeh dev was shuttered a long time ago. The nearest thing now is the Development category on the Discourse:

https://discourse.bokeh.org/c/development
