### ISSUE TITLE
Nodes and Edges do not render when data is updated

### ISSUE THREAD

**Issue by saracgil** [bokeh/bokeh#9097]
Got stuck trying to update/replot a subgraph of graph with new nodes and edges when user enters TextInput.  I think the issue is that re-rendering doesn't get called properly but new to Bokeh and can't figure out non-buggy way to do this:

bokeh: 1.2.0
python: 3.6.6
windows 10 

This is pretty long.  Nodes are tickers.  Graph G is a networkx object pre-loaded here. 

# Bokeh
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
from bokeh.models import Circle, HoverTool, TapTool, LabelSet, ColumnDataSource, MultiLine, OpenURL
from bokeh.models.widgets import TextInput
from bokeh.models.graphs import from_networkx, NodesOnly, NodesAndLinkedEdges
from bokeh.palettes import Spectral4
from bokeh.layouts import row,column, widgetbox
output_notebook()

def my_plot(doc):
    
    ticker = 'AMZN'
    # Widgets
    
    text_input = TextInput(value=ticker, title="Label:")
    
    # x and y ranges should be tied to radius of your choosing
    plot = figure(title=ticker+" Connections", x_range=(-3,3), y_range=(-1.5,1.5),x_axis_label = '', y_axis_label = '', plot_width = 800, plot_height = 800,
                tools = ['reset', 'pan','wheel_zoom','save', 'lasso_select', ]) # add tap
    
    # Custom function that returns a subgraph
    ego = make_ego(ticker)
    
    # Main Chart
    graph = from_networkx(ego, nx.spring_layout, pos = {ticker: (0,0)}, fixed = [ticker], weight='weight', scale = 1, seed=10)
    graph.node_renderer.glyph = Circle(size=50, fill_color=Spectral4[0])
    
    # Selection
    selected_circle = Circle(fill_alpha=1, fill_color=Spectral4[1], line_color=None)
    nonselected_circle = Circle(fill_alpha=0.2, fill_color=Spectral4[3])
    graph.node_renderer.selection_glyph = selected_circle
    graph.node_renderer.nonselection_glyph = nonselected_circle
    graph.node_renderer.hover_glyph = Circle(size=50, fill_color='red')
    graph.selection_policy = NodesOnly()
    graph.inspection_policy = NodesAndLinkedEdges()

    # Edges
    graph.edge_renderer.data_source.data['line_width'] = [100*ego.get_edge_data(a,b)['weight'] for a, b in ego.edges()]
    graph.edge_renderer.glyph.line_width = {'field': 'line_width'}
    graph.edge_renderer.glyph = MultiLine(line_color="#CCCCCC", line_alpha=0.8, line_width= 'line_width')
    graph.edge_renderer.selection_glyph = MultiLine(line_color=Spectral4[2],line_width= 'line_width')
    graph.edge_renderer.hover_glyph = MultiLine(line_color=Spectral4[1], line_width= 'line_width')

    # Add the graph
    plot.renderers.append(graph)

    # Tap Tool to go to company page
    url = <some url>
    taptool = plot.select(type=TapTool)
    taptool.callback = OpenURL(url=url+'@Ticker')

    # Add Hover
    node_hover = HoverTool(tooltips=[("Status", "@Status"), ("Sector", "@Sector"), ("Country", "@Country"), ("Name", "@Name")])
    plot.add_tools(node_hover)

    # Custom function to add ticker labels
    add_labels(graph, plot)

    # Custom function to adjust x y ranges
    adjust_ranges(graph,plot)
    
    def text_handler(attr, old, new):
        if new != '':
            # read and create a new subgraph to update
            temp_ticker = new
            temp = make_ego(temp_ticker)
            temp_g = from_networkx(temp, nx.spring_layout, pos = {temp_ticker: (0,0)}, fixed = [temp_ticker], weight='weight', scale = 1, seed=10)
            # Clear prior values otherwise update extends and not overwrites
            # Update layout
            graph.layout_provider.graph_layout.clear()
            graph.layout_provider.graph_layout.update(temp_g.layout_provider.graph_layout.items())
            # Get new edge and node sources
            edge_source = temp_g.edge_renderer.data_source.data
            node_source = temp_g.node_renderer.data_source.data
            # Update nodes
            graph.node_renderer.data_source.data.clear()
            graph.node_renderer.data_source.data = node_source
            # Update edges
            graph.edge_renderer.data_source.data.clear()
            graph.edge_renderer.data_source.data = edge_source
            # Update edge width
            graph.edge_renderer.data_source.data['line_width'] = [100*temp.get_edge_data(a,b)['weight'] for a, b in temp.edges()]
            graph.edge_renderer.glyph.line_width = {'field': 'line_width'}
            
            # Clear the plot and re-render new nodes, edges on new layout
            plot.renderers.clear()
            plot.renderers.append(graph)
            plot.title.text = temp_ticker +' Connections'

            # Add Ticker Labels
            add_labels(graph, plot)

            # Adjust the ranges
            adjust_ranges(graph,plot)

        else:
            print('Enter something')
    
        
    text_input.on_change("value", text_handler)
        
    layout = column(widgetbox(text_input), plot)
    doc.add_root(layout)

This is what you get for
show(my_plot)

Default shows all good
![image](https://user-images.githubusercontent.com/31630780/61325881-a50cb900-a7e3-11e9-853f-92b0a5fba411.png)
Update doesn't render the nodes and edges even though labels show where they should be.  For some reason it does draw one node each time!
![image](https://user-images.githubusercontent.com/31630780/61325929-c66da500-a7e3-11e9-93ab-b7e4f298b55d.png)

**Comment by saracgil** [comment]
This is potentially similar to this issue here:
https://github.com/bokeh/bokeh/issues/6946
which doesn't get properly resolved.  I tried and worked out the following hack which is also mentioned in one of the comments there:

This is the callback to TextInput which does not update the graph.node or edge renderer as well as layout_values but instead it simply regenerated the whole graph and replaces it in the layout

This is not the ideal solution but generates the desired output

def text_handler(attr, old, new):
        if new != '': #check if there is a new entry

            temp_ticker = new
            
            temp = make_ego(temp_ticker)
            temp_g = from_networkx(temp, nx.spring_layout, pos = {temp_ticker: (0,0)}, fixed = [temp_ticker], weight='weight', scale = 1, seed=10)
            
            # make new plot
            new_plot = figure(title=ticker+" Connections", x_range=(-3,3), y_range=(-1.5,1.5),x_axis_label = '', y_axis_label = '', plot_width = 800, plot_height = 800,
                tools = ['reset', 'pan','wheel_zoom','save', 'lasso_select', ]) # add tap
            # Make a new Main Chart
            new_graph = from_networkx(temp, nx.spring_layout, pos = {temp_ticker: (0,0)}, fixed = [temp_ticker], weight='weight', scale = 1, seed=10)
            new_graph.node_renderer.glyph = Circle(size=50, fill_color=Spectral4[0])

            # Selection
            selected_circle = Circle(fill_alpha=1, fill_color=Spectral4[1], line_color=None)
            nonselected_circle = Circle(fill_alpha=0.2, fill_color=Spectral4[3])
            new_graph.node_renderer.selection_glyph = selected_circle
            new_graph.node_renderer.nonselection_glyph = nonselected_circle
            new_graph.node_renderer.hover_glyph = Circle(size=50, fill_color='red')
            new_graph.selection_policy = NodesOnly()
            new_graph.inspection_policy = NodesAndLinkedEdges()

            # Edges
            new_graph.edge_renderer.data_source.data['line_width'] = [100*temp.get_edge_data(a,b)['weight'] for a, b in temp.edges()]
            new_graph.edge_renderer.glyph.line_width = {'field': 'line_width'}
            new_graph.edge_renderer.glyph = MultiLine(line_color="#CCCCCC", line_alpha=0.8, line_width= 'line_width')
            new_graph.edge_renderer.selection_glyph = MultiLine(line_color=Spectral4[2],line_width= 'line_width')
            new_graph.edge_renderer.hover_glyph = MultiLine(line_color=Spectral4[1], line_width= 'line_width')
            # add the new graph to new plot
            new_plot.renderers.append(new_graph)
            
            # Add Ticker Labels
            add_labels(new_graph, new_plot)

            # Adjust the ranges
            adjust_ranges(new_graph,new_plot)
            # Update the layout
            layout.children[1] = new_plot

        else:
            print('Enter something')


Default output
![image](https://user-images.githubusercontent.com/31630780/61389825-92e45680-a887-11e9-835f-dc9357602e2a.png)
Change to another ticker in the TextInput:
![image](https://user-images.githubusercontent.com/31630780/61389875-a7c0ea00-a887-11e9-899c-df6c346bb1e2.png)

**Comment by bryevdv** [comment]
@saracgil sorry it took so long to triage this. However, to look in to things, we really must have a *complete* minimal reproducer. Perhaps you can pare this down with some fake data that just illustrates the problem you are seeing?

**Comment by saracgil** [comment]
it has been so long hat I forgot this issue already:) i fixed it already so can be closed until I run into it again
