### ISSUE TITLE
Move from tornado.gen to native coroutines ?

### ISSUE THREAD

**Issue by timsnyder** [bokeh/bokeh#9098]
[tornado docs 
](https://www.tornadoweb.org/en/stable/gen.html) for `tornado.gen` say:

> The “decorator and generator” approach in this module is a precursor to native coroutines (using async def and await) which were introduced in Python 3.5. Applications that do not require compatibility with older versions of Python should use native coroutines instead

With the dropping of support for `python<3.5`, are we going to move to native coroutines and `asyncio`?

**Comment by mattpap** [comment]
Yes, there's WIP branch https://github.com/bokeh/bokeh/tree/bryanv/async for that.

**Comment by bryevdv** [comment]
I will probably have to re-do all that after landing-2.0 is merged, though, it's messy to keep that branch in up to date

**Comment by mattpap** [comment]
> (...) it's messy to keep that branch in up to date.

Is it really the case? I just rebased it and there was one trivial conflict. Also, what are the show stoppers for merging it as-is (except one recurring unit test failure)?

**Comment by bryevdv** [comment]
> Is it really the case? 

Maybe not, if you've got `bryanv/async` rebased on `landing-2.0` the please push it up. Maybe I was thinking of the out-of-tree tests branch, which is definitely not re-baseable cleanly at this point. 

We do need to figure out the one failing class of tests with `ManagedServerLoop`. It was working sort of by serendipity before, I think we may need actual separate client/server processes now to test those on different IOLoops. See https://gitter.im/tornadoweb/tornado?at=5cf46a5d82c2dc79a53ea237 for some comments with Ben Darnell

**Comment by mattpap** [comment]
I pushed the rebase and fixed an unrelated test. I will need to do some reading first to tackle the main issue, however it seems to make sense separating client and server in tests, as if it would be in real life scenarios.

**Comment by mattpap** [comment]
@bryevdv, the command for fixing the branch was `git rebase --onto origin/landing-2.0 67c8fd0^`, where the SHA is the first new commit in your feature branch. `--onto` expects one commit before that, thus `^`. There's no symbolic ref for that (perhaps a temporary tag could be used), so every time you rebase, you will have to figure out the starting commit SHA.

**Comment by zhammer** [comment]
btw (just randomly stumbled upon this on a google search) but i made a codemod for the coroutine -> async upgrade: https://github.com/zhammer/tornado-async-transformer. happy to try running that over some code here when ready to upgrade

**Comment by mattpap** [comment]
We already upgraded the code base in https://github.com/bokeh/bokeh/tree/bryanv/async. The problem currently is with updating tests, as described in https://github.com/bokeh/bokeh/issues/9098#issuecomment-513501421. Help with that would be very welcome.
