### ISSUE TITLE
[FEATURE] Extend FileInput to return filename and make output clearer

### ISSUE THREAD

**Issue by jbeanland** [bokeh/bokeh#9099]
I have been playing with the new FileInput widget in the 1.3.0rc2 release and have 2 suggestions/needs I found I had:

- Return the filename of the file being uploaded, since I need to display the names of imported files back to the users.
- Return the actual base64 encoded string of the file content separately from the mime type, rather than combined as they are at the moment. (something like this `data:application/json;base64,ewogICAgInBlcnNvbiI6IHsKICAgICAgICAiYWdlIjogMjIKICAgIH0KfQo=`)

I have a working version that does both of these so if its wanted I can create a pull request to maybe get into the 1.3.0 main release.

#### Background:
Following #9083 / #6096 I saw that the new widget is based on the Panels one, but it seems they have some sort of logic to split up the file string in the python part of the code after the ts bit. The new bokehjs code just does this logic in the ts instead.

**Comment by bryevdv** [comment]
> I have a working version that does both of these so if its wanted I can create a pull request to maybe get into the 1.3.0 main release.

Yes, if you can submit it today-ish
