### ISSUE TITLE
[BUG] Wrong option names in sphinxext documentation

### ISSUE THREAD

**Issue by Miiike89** [bokeh/bokeh#9101]
Hi guys, 
I am currently using the sphinxextension to build the documentation of my project. The module bokeh-plot is particularly usefull. While working with bokeh plot I noticed the following Issue.

Issue:
------

On the hompage: https://bokeh.pydata.org/en/latest/docs/reference/sphinxext.html#module-bokeh.sphinxext.bokeh_plot 
The two options for bokeh_plot are described:

![grafik](https://user-images.githubusercontent.com/28698827/61533988-a978e200-aa2e-11e9-89e5-1f107d81eade.png)

When using this options in an bokeh-plot directive this options can not be found
(see Console Output)

Actually I already found the problem:
In the implementation of the Directory (`bokeh.sphinxext.bokeh_plot.py`) the names of the options are simply different:

-----------------------------------------------------------------------------
    class BokehPlotDirective(Directive):

        has_content = True
        optional_arguments = 2

        option_spec = {
            'source-position': lambda x: choice(x, ('below', 'above', 'none')),
            'linenos': lambda x: True if flag(x) is None else False,
            ...
        }
--------------------------------------------------------------------------
Expected Behaviour/Solution:
-------------------------------

In my opinion the documentation should be updated from:
* source-positionenum(‘above’, ‘below’, ‘none’)
* linenosflag

to:
* source-position(‘above’, ‘below’, ‘none’)
* linenos

Like in the source code.

Environment:
-------------
python=3.6.8
bokeh=1.2.0
Sphinx=2.1.2

Console Output:
-----------------
C:\HGroot\spam-visualizers\GeoViewsion\doc\how_to.rst:112: WARNING: Error in "bokeh-plot" directive:
unknown option: "linenosflag".

.. bokeh-plot:: ../examples/minimum_map/main.py
        :linenosflag:
        :source-positionenum: above

**Comment by bryevdv** [comment]
@Miiike89 They are clearly not correct, but I don't know where those suffixes are coming from. A search for "linenosflag" in the entire repo turns up nothing. So something, somewhere, is adding those suffixes during the docs build, but I don't have any idea offhand what that might be.

**Comment by bryevdv** [comment]
Guess the docstring format is wrong, and it's picking up the extra from there:

https://github.com/bokeh/bokeh/blob/1f966a53bb5889ccfd43dde1c62a13f9372891d9/bokeh/sphinxext/bokeh_plot.py#L45-L50

@Miiike89 would you submit the small PR to change these?

**Comment by Miiike89** [comment]
@bryevdv I have never done a PR before. But I am definitly willing to. 
Is their an instruction on how to?

**Comment by bryevdv** [comment]
@Miiike89 Awesome! This page has a pretty nice howto:

https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR

If you have any questions or issues along the way please ask them and we will help you get un-stuck!

**Comment by Miiike89** [comment]
Hi Bryan.

I noticed that this issues also occures in collapsible_code_block.py:
https://github.com/bokeh/bokeh/blob/af3de9158688f0c60ba9e9ff4104d5635a7af659/bokeh/sphinxext/collapsible_code_block.py#L23-L26

Should i fix this in this file to?

**Comment by bryevdv** [comment]
@Miiike89 good catch, definitely would say +1 to fixing both at the same time

**Comment by Miiike89** [comment]
Perfect. 
Then I will setup up my env and try to fix it. :)
