### ISSUE TITLE
[BUG] Spurious "extra unexpected referrers" warning when using python debugger

### ISSUE THREAD

**Issue by analog-cbarber** [bokeh/bokeh#9107]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages

bokeh 1.2.0

panel 0.6.0, python 3.6.7, Mac OSX 10.14.3, PyCharm 2019.1

#### Description of expected behavior and the observed behavior

Ran a bokeh application in debugger from inside of PyCharm. After closing application Window in browser, got seemingly spurious warning about module having "extra unexpected referrers".

This does not occur if not run with debugger.

#### Complete, minimal, self-contained example code that reproduces the issue

Here is the script:

```python
import panel as pn
from bokeh.command.util import build_single_handler_application
from bokeh.server.server import Server

if __name__ == '__main__':
    server = Server(build_single_handler_application(__file__))
    server.start()
    server.show('/')
    server.io_loop.start()
else:
    pn.Pane('hi').servable()
```

#### Stack traceback and/or browser JavaScript console output

ERROR:bokeh.document.document:Module <module 'bk_script_1001' from '/Users/cbarber/ws/fabml/panel_apps/bug.py'> has extra unexpected referrers! This could indicate a serious memory leak. Extra referrers: [{'self': <bokeh.document.document.Document object at 0x114814400>, 'get_referrers': <built-in function get_referrers>, 'FrameType': <class 'frame'>, 'module': <module 'bk_script_1001' from '/Users/cbarber/ws/fabml/panel_apps/bug.py'>, 'referrers': [...]}, {'self': <bokeh.application.handlers.script.ScriptHandler object at 0x10181cac8>, 'doc': <bokeh.document.document.Document object at 0x114814400>, 'module': <module 'bk_script_1001' from '/Users/cbarber/ws/fabml/panel_apps/bug.py'>, 'old_doc': <bokeh.document.document.Document object at 0x1148149b0>, 'old_io': {'output_notebook': <function output_notebook at 0x11444b0d0>, 'output_file': <function output_file at 0x11444b048>, 'show': <function show at 0x11444b598>, 'save': <function save at 0x11444b1e0>, 'reset_output': <function reset_output at 0x11444b158>}, 'post_check': <function CodeHandler.modify_document.<locals>.post_check at 0x1017d8840>}, {'post_check': <function CodeHandler.modify_document.<locals>.post_check at 0x1017d8840>, 'module': <module 'bk_script_1001' from '/Users/cbarber/ws/fabml/panel_apps/bug.py'>, 'self': <bokeh.application.handlers.code_runner.CodeRunner object at 0x10181ca58>, '_cwd': '/Users/cbarber/ws/fabml/panel_apps', '_sys_path': ['/Users/cbarber/ws/fabml/panel_apps', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/cbarber/ws/fabml', '/Users/cbarber/ws/fabml/src/test/python', '/Users/cbarber/ws/fabml/src/main/python', '/Applications/PyCharm.app/Contents/helpers/third_party/thriftpy', '/Applications/PyCharm.app/Contents/helpers/pydev', '/Users/cbarber/Library/Caches/PyCharm2019.1/cythonExtensions', '/Users/cbarber/ws/fabml/panel_apps', '/miniconda3/envs/fabml-dev/lib/python36.zip', '/miniconda3/envs/fabml-dev/lib/python3.6', '/miniconda3/envs/fabml-dev/lib/python3.6/lib-dynload', '/miniconda3/envs/fabml-dev/lib/python3.6/site-packages'], '_sys_argv': ['/Users/cbarber/ws/fabml/panel_apps/bug.py']}]

**Comment by analog-cbarber** [comment]
The code in question is in `Document.delete_modules`:

```python
            # Modules created for a Document should have three referrers at this point:
            #
            # - sys.modules
            # - self._modules
            # - a frame object
            #
            # This function will take care of removing these expected references.
            #
            # If there are any additional referrers, this probably means the module will be
            # leaked. Here we perform a detailed check that the only referrers are expected
            # ones. Otherwise issue an error log message with details.
            referrers = get_referrers(module)
            referrers = [x for x in referrers if x is not sys.modules]
            referrers = [x for x in referrers if x is not self._modules]
            referrers = [x for x in referrers if not isinstance(x, FrameType)]
            if len(referrers) != 0:
                log.error("Module %r has extra unexpected referrers! This could indicate a serious memory leak. Extra referrers: %r" % (module, referrers))
```

This code does not account for references that are indirectly referred to by the debugger frame, specifically in my case, this is not eliminate references from the frame's `f_locals` attribute.

**Comment by bryevdv** [comment]
@analog-cbarber you seem to have dived fairly deep into this, I'd be pleased to consider a PR from you to ignore those referrers when computing the total

**Comment by analog-cbarber** [comment]
Ok, but I don't think I will have the time for a while. I spent less than an hour debugging this and don't even have a developer configuration for bokeh at this time.

I just wanted other people debugging bokeh apps to know that this behavior does not necessarily an actual leak.

**Comment by bryevdv** [comment]
I that case I'm also not opposed to just closing this with `discussion` and leaving it as documentation. I have been told directly by Python core devs that there are few guarantees around consistency of referrers in this sort of situation between versions.

**Comment by analog-cbarber** [comment]
Debuggers are probably not common because (1) you don't document how to do it and (2) sadly there are still a lot of people who have not gotten around to learning how to use them. But if someone is using the debugger, they should not get spurious errors like this. While using a debugger is not a normal production deployment, it is perfectly reasonable for developers. This really should be considered to be a bug. 

The referrers check is obviously a bit of a hack. Because it does not call `gc.collect()` it could also get theoretically get extra references that have not been collected yet, but as long as we are going to do this, we should try to get it right.

Note that the code does in fact check for `FrameType`, so whoever wrote that was already aware that the current frame object can hold a reference. We just need to also exclude frame attributes from the reference list.

**Comment by bryevdv** [comment]
I don't disagree with any of this, but there is a matter of resources. There's only so many hours in the day, and given that it is both rare and not something I actually know the how to definitively reproduce ( don't use debuggers in IDEs and have never encountered this in plain pdb.set_trace), it's just very unlikely that this is anything I will be able to prioritize any time soon. The cost/benefit simply not there. So I look for a range of possible responses. One would be just to leave this issue as documentation. Another quick "fix" would be to just update the message, or make the message silenceable by people who know what they are doing. Or we can wait until someone else can provide a more thorough fix, which I am also happy to do.

**Comment by analog-cbarber** [comment]
I am mostly arguing against closing the bug without fixing it. It is totally fine to have low-priority open bugs. Leaving them open is usually enough for developers to find the description and understand what is going on without debugging from scratch, but people are less likely to search through closed bug tickets for active problems.

I do not know that this bug is unique to the PyCharm debugger. That is just what I happened to be using. The extra reference in my case appeared to come from the frames `f_locals` attribute, which is a standard frame attribute (see https://docs.python.org/3/reference/datamodel.html#frame-objects), so I would expect the same thing could happen with any debugger. It will just depend on whether a given implementation uses the gc to manage the frame objects.

The behavior is reproducible in PyCharm using the script I provided, so it should be pretty easy to try other debuggers provided you have them at hand. I just tried using `python -m pdb` and did not see the problem (presumably it does not manage frame objects using the gc).

In any case, this should not be all that hard to fix, at least for this case, and I will give it a shot when I have a chance, but I have only just started using bokeh and have not gotten around to building it from source, so it may be a while before I get around to it.

So I recommend you just leave the bug as is and wait for me (or someone else) to come up with a fix and verify that it works.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this at this point to clean up the tracker. It's here as documentation if anyone else ever runs in to it (tho I have not heard of that happening). @analog-cbarber if you are ever able to submit a PR we would be pleased to accept it.
