### ISSUE TITLE
[BUG] Doesn't render color block when plot_width is very large

### ISSUE THREAD

**Issue by eromoe** [bokeh/bokeh#9115]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

From this example https://bokeh.pydata.org/en/latest/docs/gallery/unemployment.html
I fill my data.  About 4600 index with 7 column

#### Screenshots or screencasts of the bug in action

plot_width=18000
![image](https://user-images.githubusercontent.com/3938751/61934267-81ebc180-afba-11e9-90f8-e008a3615113.png)

plot_width=30000
![image](https://user-images.githubusercontent.com/3938751/61934189-5537aa00-afba-11e9-9f20-540bc3413e2c.png)

**Comment by mattpap** [comment]
This is an intrinsic limitation of the allowed canvas size in web browsers. For example Chrome allows canvas size up to 32k pixels (see https://bugs.chromium.org/p/chromium/issues/detail?id=339725), but this varies a lot (mostly towards smaller numbers, especially on mobile). There's also a limit on the surface area of the canvas, which may present it self in such extreme scenarios. Additionally hidpi transform may kick in and reduce this limit by a factor > 1 (usually 2 or more, depending on the platform and hardware). You can set `Plot(..., hidpi=False)` to disable the transform.

I'm not sure what you're trying to achieve here, except testing bokeh's extreme capabilities, but if you need a raster image of this size, I would export the plot to SVG and use a postprocessing tool (e.g. Inkscape) to export a PNG of the desired size.

One think we could do is to warn against this kind of extreme settings, though given the high variability between implementations and the fact that those limits are usually not easily obtainable by bokehjs, this my be more work than it's worth.

**Comment by bryevdv** [comment]
I'm inclined to think this should be closed with `upstream` or `wontfix` The scope of Bokeh is to create interactive visualizations for web presentation and I think images of this size fall outside that scope (they can/should be rendered with tools that are more specialized for generating static images)
