### ISSUE TITLE
[BUG]Datepicker displayed value is not updating correctly

### ISSUE THREAD

**Issue by PierreLB6** [bokeh/bokeh#9129]
Hi ! First of all thanks for the amazing work.

I just updated bokeh to 1.3.0 and noticed that the displayed DatePicker value is not updating correctly after changing it manually. Basically, the underlying value responds well but the displayed value corresponds to the selected day - 1 day. So if you click on 30th July 2019, the displayed value is 29th July 2019. The displayed value updates correctly only if you select the 30th July a 2nd time.

I just checked with 1.2.0 and we don't seem to have this issue (tested on chrome, Edge and firefox).

Minimal Example code:
```
from bokeh.models import DatePicker
from bokeh.io import curdoc
import datetime

def callback(attr, old, new):
    print('old:', old, 'new:', new)

date_picker = DatePicker(value=datetime.date.today())

date_picker.on_change('value', callback)

curdoc().add_root(date_picker)
```

Thanks and sorry if it's not the right way to submit an issue, it's my first time doing this.

Software version info:
Bokeh - 1.3.0
Python - 3.7.3
Chrome - 75.0.3770.142

**Comment by bryevdv** [comment]
@PierreLB6 I am unable to reproduce any problem personally. What time zone are you testing in?

**Comment by PierreLB6** [comment]
@bryevdv i'm in France (UTC+2), i didn't think about this. I guess that could explain it but there were no problems with 1.0.2.

**Comment by bryevdv** [comment]
Well, there were several `DatePIcker` problems with 1.2 but it's possible fixing them introduced new others at the same time.

**Comment by madkopp** [comment]
Having the exact same issue here.  I came from v 1.1.0,, where I was having no issues, then upgraded to v1.3.0 and started experiencing the problem.  Made no changes to my code.  In the UK.

**Comment by bryevdv** [comment]
OK I have added this to the 1.4 milestone. @PierreLB6 @madkopp  When the time comes, I could very much use help testing a PR

**Comment by madkopp** [comment]
Can't promise that I'll be much use, but I'm certainly willing to give it a shot.  FYI, I think I have a lead on the problem.  Looking at the DatePicker source code (bokeh/bokehjs/src/lib/models/widgets/date_picker.ts), check out line 78, the _unlocal_date method:

  _unlocal_date(date: Date): Date {
    // this sucks but the date comes in as a UTC timestamp and pikaday uses Date's local
    // timezone-converted representation. We want the date to be as given by the user
    const datestr = date.toISOString().substr(0, 10)
    const tup = datestr.split('-')
    return new Date(Number(tup[0]), Number(tup[1])-1, Number(tup[2]))
  }

**Comment by madkopp** [comment]
Sorry, forgot to finish my thought in my last comment, but if the comments in the code are to be believed, it seems anyone in a UTC+ timezone (as both France and the UK are) would experience this issue.

Hope that helps, but doubt that it does.

**Comment by sebastian-lapuschkin-sideprojects** [comment]
same issue here. displayed value is one day behind, returned values is correct. from germany.

any news on this?

**Comment by bryevdv** [comment]
I don't know how to fix it.

**Comment by madkopp** [comment]
What if you change _unlocal_date to the following?  Sorry, I've never written in JS, so please excuse any errors. 

Credit to user2875462 from https://stackoverflow.com/questions/7403486/add-or-subtract-timezone-difference-to-javascript-date. 

```
_unlocal_date(date: Date): Date {
    // this doesn't suck??

    var timeOffsetInMS = date.getTimezoneOffset() * 60000
    date.setTime(date.getTime() - timeOffsetInMS)
    
    const datestr = date.toISOString().substr(0, 10)
    const tup = datestr.split('-')
    return new Date(Number(tup[0]), Number(tup[1])-1, Number(tup[2]))
}
```

**Comment by bryevdv** [comment]
I'll try to apply this to a branch and test it out this week, but we will need someone from the affected timezones to also be able to build and test locally as well (happy to help out with getting set up etc)

**Comment by bryevdv** [comment]
Well, I suppose I can try changing the TZ of my laptop but it'd be good for a real users to check as well.

**Comment by madkopp** [comment]
If you can help me get set up I'd be happy to help test.

**Comment by madkopp** [comment]
So I managed to get setup with the Bokeh source code, and I tested the proposed solution.  The good news is that it works.  Let me know what the next steps are.

**Comment by bryevdv** [comment]
@madkopp Great, sorry my week ended up very busy and this slipped off my radar. The next step would be to make a Pull Request from your fork of the repo, then we can test it easily and think about tests that might be possible to add.

**Comment by madkopp** [comment]
@bryevdv No worries, man, glad I could take something off your plate.  Let me know if I did that wrong and I'll be happy to fix the pull request.

**Comment by bryevdv** [comment]
NOTE: #9509 re-fixes this and many other datepicker issues (as well as adds selenium tests) but note that the implementatoon was switched to Flatpickr, and also now date values can *only* be expressed as ISO date strings, or `datetime.date` and nothing else (in particular no more datetime values which caused endless trouble with time zones)
