### ISSUE TITLE
[FEATURE] Line+markers

### ISSUE THREAD

**Issue by crayxt** [bokeh/bokeh#9131]
**Is your feature request related to a problem? Please describe.**
It would be great to have a line+markers type visualization. Currently we add two items (line and marker) resulting in two legend items. To enable/disable it, we need to do it twice.
Thanks,

**Comment by bryevdv** [comment]
> Currently we add two items (line and marker) resulting in two legend items. 

This is not true, glyphs with the same legend value are combined (that is the intended mechanism for doing that):

https://bokeh.pydata.org/en/1.3.1/docs/gallery/legend.html

**Comment by crayxt** [comment]
It looks like it is a time to upgrade

**Comment by crayxt** [comment]
Will the data be duplicated it that case?

**Comment by bryevdv** [comment]
@crayxt Please take support questions to the project Discourse, thanks

https://discourse.bokeh.org/
