### ISSUE TITLE
[BUG] Tabs ignore explicitly set dimensions

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#9133]
The Tabs layout currently responds only to the dimensions of its contents and does not respect any of the ``width``/``height``/``min_width``/``min_height``/``sizing_mode`` etc. properties. This makes it very difficult to use Tabs as part of some larger layout because you always have to make sure that at least one of its Panels contains something of the required size. I would expect Tabs to behave as they do by default but if an explicit (min) width or height is set that should also be respected ensuring that the tabs take up the allocated space.

```python
from bokeh.models.widgets import Panel, Tabs
from bokeh.io import output_file, show
from bokeh.plotting import figure
output_file("tabs.html")

p1 = figure(plot_width=300, plot_height=300)
p1.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

p2 = figure(plot_width=300, plot_height=300)
p2.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=3, color="navy", alpha=0.5)

tab1 = Panel(child=p1, title="circle")
tab2 = Panel(child=p2, title="line")
tabs = Tabs(tabs=[ tab1, tab2 ], width=500)

show(tabs)
```

Versions:

<details>
Python: 3.7.3</br>
Bokeh: 1.3.0
</details>

**Comment by mattpap** [comment]
Setting `Tabs.width` works, at least in this particualr case, which can be visualized by setting `Tabs.background`, e.g.:
![image](https://user-images.githubusercontent.com/27475/62905430-c1602f00-bd6a-11e9-9a69-648fefc5cba7.png)
`{min,max}_{width,height}` aren't fully implemented, so they are destined to fail.

**Comment by philippjfr** [comment]
Ah yes, this is true, but seemingly the tab header does not span the full width:

<img width="511" alt="Screen Shot 2019-08-13 at 1 46 59 AM" src="https://user-images.githubusercontent.com/1550771/62905782-43048c80-bd6c-11e9-92dc-ebaa08a35a9a.png">

**Comment by mattpap** [comment]
> Ah yes, this is true, but seemingly the tab header does not span the full width:

That may be just a CSS quirk.

**Comment by mattpap** [comment]
Note also that a lot depends on the sizing policies/modes of all layout items involved, so we may need to speak about each suspicious complex layout individually. This is all way more complicated that it needs to be, but that was the price for backwards compatibility at the time.

**Comment by mattpap** [comment]
Actually the header is clearly broken, because it shouldn't show scroll buttons in this scenario.

**Comment by philippjfr** [comment]
>Actually the header is clearly broken, because it shouldn't show scroll buttons in this scenario.

Right I would have expected it to span the full width here:

```python
from bokeh.models.widgets import Panel, Tabs
from bokeh.io import output_file, show
from bokeh.plotting import figure
output_file("tabs.html")

panels = []
for i in range(5):
    p = figure(plot_width=300, plot_height=300)
    p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

    panels.append(Panel(child=p, title="circle %d" % i))
tabs = Tabs(tabs=panels, width=500, background='gray')

show(tabs)
```
