### ISSUE TITLE
Be able to order legend items when using GroupBy Legend [FEATURE]

### ISSUE THREAD

**Issue by arturomoncadatorres** [bokeh/bokeh#9135]
Ordering legend items can be done very easily by [reordering the elements of `p.legend`](https://discourse.bokeh.org/t/legend-ordering/2224). However, when [using a GroupBy Legend, this isn't so straightforward](https://discourse.bokeh.org/t/cant-order-legend-entries-in-hbar-plot/3816/5?u=arturomoncadatorres), since the order is computed on the JS side, which can lead to [lengthy and manual workarounds](https://discourse.bokeh.org/t/cant-order-legend-entries-in-hbar-plot/3816/8?u=arturomoncadatorres).

It would be great if the GroupBy Legends could also be ordered using the same syntax as for non-GroupBy ones.

**Comment by bryevdv** [comment]
@bokeh/dev what do you think about deprecating  `legend` (which is a little too magic in some ways) and having some more explicit (mutually exclusive) options:

* `legend_label="foo"` always creates a single legend item and always with that text as a label
* `legend_field="foo"` sets a "field" for client-side grouping in BokehJS
* `legend_group="foo"` does a *Python* side grouping and creates multiple legend items with appropriate indices values

For the last I think there should be API for it so the items could easily be updated in a Bokeh server app callback

**Comment by birdsarah** [comment]
This seems great. Obviously a long deprecation cycle for `legend` kwarg, but yes, the ability to be more specific seems very appropriate and your API fields intuitive and compact. That said, I haven't done a lot of legend work in a while and don't feel like I have a deep feeling for the API currently.
