### ISSUE TITLE
inner_width and inner_height not available after display

### ISSUE THREAD

**Issue by happydasch** [bokeh/bokeh#9136]
with the latest bokeh (1.3.1) when running a plot in a server, inner_width and inner_height is not available at the begin but gets available after panning on plot. 

I expected the values to be available after plot is shown.

**Comment by bryevdv** [comment]
@mattpap I thought this was a dupe but I can't find any other issue, are you aware of any?

**Comment by mattpap** [comment]
I'm not aware of any issues, nor I had a chance to actually reproduce this.

**Comment by happydasch** [comment]
i am sorry, I did not add an example:

[example.txt](https://github.com/bokeh/bokeh/files/3463878/example.txt)

**Comment by bryevdv** [comment]
@happydasch FYI your example does not set ranges/does not have axes. The `inner_width` refers to the pixel dimensions inside the axes, it does not make sense to be computed if there are no axes present, as with your code. That said, adding axes does not help this case. Here is an updated example:
```
from bokeh.plotting import figure
from bokeh.layouts import layout
from bokeh.models import Button
from bokeh.io import curdoc

fig = figure(x_range=(0,10), y_range=(0,10))
btn = Button()
layout = layout([btn])

def btnClick(event):
    if not fig in layout.children:
        layout.children = [fig,btn]
    print(fig.inner_width)
btn.on_click(btnClick)

curdoc().add_root(layout)
```

This workaround idea does not work either:
```

def btnClick(event):
    if not fig in layout.children:
        layout.children = [fig,btn]
btn.on_click(btnClick)

layout.on_change('children', lambda attr, old, new: print(fig.inner_width))
```
 I am not sure this will be simple to do something about. At a guess, the information is simply not yet available at the time these events are triggered. 

@mattpap  is there another event that might reliably occur *after* the layout recomputation here? (Perhaps we should just have an observable event *for* layout recomputation)

**Comment by happydasch** [comment]
The values were available when I did not run with bokeh serve. I used this value to align some labels at top of the figure, it also becomes available after first resize. (I did not test this now, I just write from memory)

**Comment by mattpap** [comment]
The problem is that `document` isn't available on a `Plot` in bokehjs at the time `inner_*` properties are being set, which prevents any updates to be sent to the client.

**Comment by bryevdv** [comment]
We could add some hooks that allow sending updates for specified properties upon doc attachment. I will see if there is a quick solution along these lines.

**Comment by bryevdv** [comment]
OK I overlooked the key element that this example is not relying on a property change event trigger but is trying to read off the values immediately when adding a plot inside a callback. I am actually quite skeptical that will be possible to achieve. I *can* make this work, with a very small patch:
```
from bokeh.plotting import figure
from bokeh.layouts import layout
from bokeh.models import Button
from bokeh.io import curdoc

fig = figure(x_range=(0,10), y_range=(0,10))
btn = Button()
layout = layout([btn])

def btnClick(event):
    if not fig in layout.children:
        layout.children = [fig,btn]
btn.on_click(btnClick)

# have to rely on events to read off values 
fig.on_change('inner_width', lambda attr, old, new: print(fig.inner_width))
fig.on_change('inner_height', lambda attr, old, new: print(fig.inner_height))

curdoc().add_root(layout)
```
Events like above already work for plots added at the beginning, but don't work on dynamically added plots. So this would be an improvement, and probably the best we can expect. 

So I will submit a PR for that and consider this issue closed.

**Comment by bryevdv** [comment]
@happydasch PR submitted, this should be in 1.4 next week or so. I hope the approach above can be sufficient, as I mentioned I really don't think it's possible to make an immediate readout of the values in the same callback where a plot was dynamically added work.

**Comment by happydasch** [comment]
Thanks Bryan, the callback (on_change) when these values are set would be enough for my issue.

I can add the label to be positioned when these values were made available. Thanks a lot for your work.
