### ISSUE TITLE
[BUG] Roadmap link on docs page links to a nonexistent page

### ISSUE THREAD

**Issue by gshpychka** [bokeh/bokeh#9143]
#### Description of expected behavior and the observed behavior
https://bokeh.pydata.org/en/latest/index.html
In the footer, the 'Roadmap' link leads to
'https://bokeh.pydata.org/en/latest/docs/https://bokeh.org/roadmap.html',
which does not exist.

Expected behavior: Display the Roadmap page.
Observed behavior: 404 error.

Now, the obvious issue here is the wrong URL, but https://bokeh.org/roadmap.html produces 404 as well.

**Comment by mattpap** [comment]
In fact all links in "About us" section are broken and 404 page is broken (missing or bad CSS?) as well.

**Comment by bryevdv** [comment]
The roadmap is on the main project page now:

https://bokeh.org/roadmap/


You can actually see that embedded in the middle of the broken link above:

`https://bokeh.pydata.org/en/latest/docs/***https://bokeh.org/roadmap.html***`

I updated all these links when the main front page was stood up, to point there for static content that should not be built in the docs anymore, but the links are not getting rendered properly. We should definitely fix before 1.4 but it's doubtful I would ry to fix the 1.3.1 docs already deployed.
