### ISSUE TITLE
Bokeh Grouped Bar Plots Not Updating Bar Width Correctly

### ISSUE THREAD

**Issue by ashvin777** [bokeh/bokeh#9145]
I am using Bokehjs 1.3.0 version and trying to update the Group vbar chart dynamically. However, it is not working properly and not setting the bar width and placement properly. 

Here is the live URL - https://jsitor.com/ZJUc8ZXGt where this issue is reproducing.

In sort - there are 2 vbars 
```
p.vbar({
  x: {
    field: 'time',
    transform: new Bokeh.Dodge({
      value: -0.20,
      range: p.x_range
    })
  },
  top: { field: '2015' },
  width: 0.2,
  source: source,
  legend: '2015 ',
  color: 'orange'
});

p.vbar({
  x: {
    field: 'time',
    transform: new Bokeh.Dodge({
      value: 0.20,
      range: p.x_range
    })
  },
  top: { field: '2016' },
  width: 0.2,
  legend: '2016 ',
  source: source,
  color: 'green'
});
```

And I am dynamically adding data in `source`.

This is how it looks like when I am adding more than one single data -
![Screenshot 2019-08-05 at 10 33 13 PM](https://user-images.githubusercontent.com/8143154/62481957-82156980-b7d1-11e9-9deb-cc9d5bc1d29c.png)
it is supposed to show 2 bars side by side and width of bars should be big enough.

It works properly when I set only single data -
![image](https://user-images.githubusercontent.com/8143154/62482037-ae30ea80-b7d1-11e9-8216-a8672ee2b21f.png)

**Comment by bryevdv** [comment]
cc @mattpap 

I'm inclined to think this is a support question (and so should move to the [Project Discourse](https://discourse.bokeh.org). In particular you seem to be mixing numerical and categorical coordinates on your x range which seems like incorrect usage.

**Comment by bryevdv** [comment]
I'm fairly certain this is a usage issue, @ashvin777 please come by the Discourse to discuss further.
