### ISSUE TITLE
[BUG] - Plot is blurr (Not respecting device pixel ratio)

### ISSUE THREAD

**Issue by ashvin777** [bokeh/bokeh#9149]
In general, all charts and graph created using Bokehjs are a little bit blurred and not crisp. Looks like below -

![image](https://user-images.githubusercontent.com/8143154/62624584-09351f80-b941-11e9-9ba8-b85737d742ee.png)

This is something which can be related to HTML5 canvas which can be resolved using https://www.html5rocks.com/en/tutorials/canvas/hidpi/.

**Comment by philippjfr** [comment]
Thanks for the report.Could you post your bokeh and browser versions as requested in the issue template? Hard to tell if this is a current issue or an issue with all browsers otherwise.

**Comment by mattpap** [comment]
> This is something which can be related to HTML5 canvas which can be resolved using

bokehjs already supports hidpi transform, that is configurable through `Plot.hidpi` property. By default the transform is enabled and browser provided pixel ratio is used. Given that you mention bokehjs directly, I suppose your code is in JavaScript? If so, please submit a reproducible code sample on top of what @philippjfr requested.

**Comment by bryevdv** [comment]
Marking this as `NEEDS MORE INFO`, will close in 1wk unless details/reproducer are made available.
