### ISSUE TITLE
Remove bokeh.embed.notebook.widgets from -OO blacklist

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9157]
This should happen as soon as new version if ipywidgets is released.

**Comment by bryevdv** [comment]
I don't think we can remove it outright unless you are suggesting we set a minimum ipywidgets version that is band new.

**Comment by mattpap** [comment]
Well, I suppose we should from users' perspective. But as far as this issue is concerned, this is about testing only, and for that purpose we pull most recent versions.

**Comment by bryevdv** [comment]
Fair enough, I forgot it's only a test-dep, we can indeed set to whatever we need.

**Comment by bryevdv** [comment]
What's the last broken version of ipywidgets?

**Comment by mattpap** [comment]
7.5.1, however I will be removing ipywidgets dependent code after all, so this issue will be a no-op.
