### ISSUE TITLE
HelpTool should allow for a modal/stay on page help rather than new tab [FEATURE]

### ISSUE THREAD

**Issue by ClaudiuCreanga** [bokeh/bokeh#9162]
**Is your feature request related to a problem? Please describe.**
I would like to explain the plots for users. Currently the only way is through the help tool that will open a new window: https://bokeh.pydata.org/en/latest/_modules/bokeh/models/tools.html#HelpTool
But I have the information on the same page. I would like to either open a modal with js or navigate to a div (#help )

**Describe the solution you'd like**
I think a third argument would be useful here https://bokeh.pydata.org/en/latest/_modules/bokeh/models/tools.html#HelpTool where we can give a css class and if that is passed, do not open a new window on click. Let users bind to that element using the css class to do what they want from an external script.

Thanks.

**Comment by bryevdv** [comment]
@ClaudiuCreanga is this something you might be interested to work on with some support or guidance as needed? The core team is very time-limited at the moment so I sure you would be able to look into things well before we could.

**Comment by ClaudiuCreanga** [comment]
@bryevdv might as well, since I'm using bokeh a lot. I guess I should start from here https://bokeh.pydata.org/en/latest/docs/dev_guide.html

**Comment by bryevdv** [comment]
@ClaudiuCreanga Brilliant, yes that's a good place to start, mostly the parts about building and running with BokehJS locally. Let me know if I can answer any questions!

**Comment by bryevdv** [comment]
Im going to go ahead and close this. If desired, in recent versions, a `CustomAction` tool could be used to raise any modal, etc desired
