### ISSUE TITLE
[BUG] [DOCS] Broken images in custom tooltip example

### ISSUE THREAD

**Issue by kevin1kevin1k** [bokeh/bokeh#9181]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh: 1.3.4 (latest at the time of writing)

#### Description of expected behavior and the observed behavior

In the example of the section
https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#custom-tooltip
an image should be displayed on hover over each circle.
However, the five images seem to be broken, and the links (see below) also fail.

https://bokeh.pydata.org/static/snake.jpg
https://bokeh.pydata.org/static/snake2.png
https://bokeh.pydata.org/static/snake3D.png
https://bokeh.pydata.org/static/snake4_TheRevenge.png
https://bokeh.pydata.org/static/snakebite.jpg

#### Screenshots or screencasts of the bug in action
![cropped](https://user-images.githubusercontent.com/9023838/63419716-deb28e80-c437-11e9-83d2-cca98c290e4c.png)

**Comment by bryevdv** [comment]
Thanks for the report @kevin1kevin1k we have been migrating the docs to a new system and the static directory got left out. I have moved it over now.
