### ISSUE TITLE
Add hover tooltip support for Patch, HArea, and VArea

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9182]
Hover highlight was added in #9084 but work is still needed to make hover tooltips work with the area-style glyphs with connected topology.

**Comment by BexDunn** [comment]
This would be great!

**Comment by manny1206** [comment]
Any progress? I kinda need this.

**Comment by bryevdv** [comment]
Hi @manny1206 there is not really any need to ever leave a comment just to ask this question of an OSS project. If there were any updates, they would be here. There are many issues, and a small team, so some things will simply take more more time until/unless new contributors decide to get involved to help speed things up. I am happy to advise/mentor anyone who wants to work on this sooner. Otherwise, in the mean time, a potential workaround is to use `patches` to construct the areas you require explicitly.

**Comment by bryevdv** [comment]
@xaptronic I'd be very happy to, can I use the email on your GH to invite you to the Bokeh dev Slack instance? That's a good place for async Q&A etc. 

As a very quick, very high level summary, the main sticking point with adding this: unlike almost all other glyphs, these three are not "vectorized". You supply an array of coordinates, yes, but because of the connected topology, there is only *one* Patch, or *one* VArea, etc. However, all of the hit-testing machinery is geared around reporting a selection or inspection ***index***, e.g the mouse hit the 137th scatter marker in a scatter plot, and the hover tool expects that it can use that index to look up associated data in the CDS. That's not the case for Patch, etc. 

So we will need to figure out a minimal scheme to report hit testing on connected glyphs like these, and also teach the hover tool how to understand it.

**Comment by xaptronic** [comment]
Yes please! I submitted a slack invite a few days age using my GH email.

**Comment by bryevdv** [comment]
Our free-for-OSS QuestionScout account seems to have been disabled recently, so I think we missed the response. You should have an invite now!
