### ISSUE TITLE
[BUG] Pinch Zoom and Panning not working correctly

### ISSUE THREAD

**Issue by DarkCyTic** [bokeh/bokeh#9187]
I am using Bokeh standalone **1.3.4** on the back end (Django) and bokehjs on the front end. While scrolling to zoom and using the mouse to pan works well on desktop, the experience on mobile devices is ambiguous. In Chrome (**76.0.3809.111**) on mobile devices, nor panning, nor pinching to zoom work. Panning works great in Safari and Firefox on mobile devices, but pinching to zoom doesn't work there as well. 

This is the back end code:
```python
p = figure()

color_palette = Spectral11[0:num_lines]

source = ColumnDataSource(power_data)

p.add_layout(Legend(items=legend_items))
p.legend.click_policy = "hide"

p.add_tools(CrosshairTool(
        dimensions='height',
        line_color='red'
))

item_text = json.dumps(json_item(p, "myplot"))

return Response(item_text)
```

This is the front end code:
```javascript
declare var Bokeh: any

// some lines later, inside a request callback
Bokeh.embed.embed_item(JSON.parse(response))
```

I have found a website where the pinch to zoom and pan work well and they are using an older version of Bokeh(**1.0.4**), so I am not sure if it's something with my code or it no longer works.

Are these features still supported on mobile devices?

**Comment by mattpap** [comment]
They are supposed to work, but we have limited resource to test on mobile, so regressions are inevitable.

**Comment by mattpap** [comment]
The problem with pinch motion is that it often ends up as rotation, and rotation is half-implemented in bokeh, resulting in an exception (which isn't easily accessible on mobile). Panning issue in Chrome Mobile is a bit more severe. I will have to investigate this.

**Comment by bryevdv** [comment]
@mattpap should this be moved out of `1.4` milestone? It would need to be fixed before the end of next week.

**Comment by mattpap** [comment]
I will have this fixed during PyCon.DE sprints this weekend.

**Comment by bryevdv** [comment]
@mattpap should this be moved out?

**Comment by do1tgood** [comment]
Experiencing a very similar issue. BoxZoomTool doesn't work in iOS Safari (well, in any browser on iOS **13.x**). But it still works fine on iOS 12.4.4. Actually, this iOS version is a key here. They have implemented PointerEvents in iOS 13. That's why libraries that used to imitate handling touch events started to receive new issues in their repos. Hammer.js too. I've found a workaround which definitely fixes Box Zoom Tool. I will test it over pinch zoom and panning. If it also resolves these issues I will submit a PR for it.

It is based on comment to Hammer.js' issue - https://github.com/hammerjs/hammer.js/issues/1084#issuecomment-544220158

**Comment by bryevdv** [comment]
> Hammer.js too. 

Bokeh actually uses Hammer.js under the covers. Do you have any insight into whether things might get addressed in a newer version of Hammer? Definitely any PRs  or concrete suggestions you can provide are very helpful, as this is not an area of deep expertise for the current core devs. Thanks!

**Comment by mattpap** [comment]
> Do you have any insight into whether things might get addressed in a newer version of Hammer?

Looking at the state of that project, it's unlikely to get any fixes, unless someone forks it.

**Comment by bryevdv** [comment]
> Looking at the state of that project, it's unlikely to get any fixes, unless someone forks it.

Well, we first adopted it ~7 years ago so perhaps not surprising. Maybe there is a similar, more up to date library available these days. @DarkCyTic any thoughts or suggestions welcome
