### ISSUE TITLE
[FEATURE] Add fill properties to slope

### ISSUE THREAD

**Issue by kylrth** [bokeh/bokeh#9194]
It'd be useful to have an annotation like [BoxAnnotation](https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#box-annotations) that creates a dividing line, but which can be angled. It's possible to achieve something similar with an image, but then interaction is extremely slow as the plot has to re-render the image at every frame.

#### Using [bands](https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#bands)

This may be possible if we expand the features of the `Band` annotation. Currently, leaving `lower` or `upper` unspecified results in a blank figure, but we could change the behavior such that if either is unspecified the band continuous off infinitely.

I'd like to hear the thoughts of those more familiar with the capabilities of annotations.

**Comment by kylrth** [comment]
If people are looking for a vertical line, they'll choose a Span, right? Can you even specify `Slope(gradient=np.inf)`? I think `fill_above` and `fill_below` (or some variant thereof) will always make sense for the parameters of a Slope object.

**Comment by bryevdv** [comment]
I had forgotten `Slope` is configured with an intercept and derivative (instead of a point and an angle, say) so yes I agree it's not possible to make a vertical slope, and that above/below are therefore well-defined always.

**Comment by kylrth** [comment]
Add this to the list of things I will "eventually" work on. :P

**Comment by bryevdv** [comment]
Just noting that the way properties are named is slightly constrained, so for concreteness the proposal is to add `above_fill_color` and `below_fill_color`:

```
slope = Slope(gradient=gradient, y_intercept=y_intercept,
              line_color='orange', above_fill_color="red", below_fill_color="blue")
```

and similarly for `above_fill_alpha` and `below_fill_alpha`. It would be nice to also add above/below hatch properties at the same time but that's certainly a lower priority.

**Comment by graeme-hattan** [comment]
If you add `above_fill_color` and `below_fill_color` to `Slope`, then what is missing is the ability to fill between slopes like you can for horizontal/vertical lines using `BoxAnnotation`. Maybe a better solution is along the lines of adding `gradient` parameters to `BoxAnnotation` (then probably renaming the class to something more descriptive and then making `BoxAnnotation` a subclass which uses 0 or 1 for each gradient).
