### ISSUE TITLE
[BUG] [DOC] Broken link to examples/app

### ISSUE THREAD

**Issue by kevin1kevin1k** [bokeh/bokeh#9199]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

The current version of Bokeh.

#### Description of expected behavior and the observed behavior

In [this README](https://github.com/bokeh/bokeh/blob/master/examples/app/clustering/README.md), there is
```
[`examples/app`]([`examples/app`](https://github.com/bokeh/bokeh/tree/master/examples/app))
```
which is incorrect.
Should be replaced with
```
[`examples/app`](https://github.com/bokeh/bokeh/tree/master/examples/app)
```

**Comment by bryevdv** [comment]
@kevin1kevin1k would you like to submit a PR to update this link?

**Comment by kevin1kevin1k** [comment]
Sure, I've submitted one at #9204.
