### ISSUE TITLE
[BUG] vbar_stack: Columns with zero height show 1px in certain browsers

### ISSUE THREAD

**Issue by jnettels** [bokeh/bokeh#9207]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Windows 10
Google Chrome: Version 76.0.3809.132 (Offizieller Build) (64-Bit)
Firefox: 68.0.2
Microsoft Edge: 44.1862.267.0
Bokeh: 1.3.4
Python: 3.7.1

#### Description of expected behavior and the observed behavior

When vbars with a height of zero are stacked, some browsers show those vbars with a height of what looks like just 1px:

- Microsoft Edge: OK
- Firefox: Not OK
- Chrome: Not OK

This has bugged me for a very long time, but I have never seen an issue about it. I have no clue whether this is something bokeh could actually solve. Maybe the browsers are at fault.

While testing, I realized that replacing all occurances of ``0`` with ``np.nan`` or ``float('NaN')`` is a valid workaround. The plot is shown correctly in all browsers. Since I can automate this, I am fine with leaving this as wontfix.

#### Complete, minimal, self-contained example code that reproduces the issue
Use the official example and change some values to zero:
https://bokeh.pydata.org/en/latest/docs/gallery/bar_stacked.html

```
from bokeh.core.properties import value
from bokeh.io import show, output_file
from bokeh.plotting import figure

output_file("bar_stacked.html")

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ["2015", "2016", "2017"]
colors = ["#c9d9d3", "#718dbf", "#e84d60"]

data = {'fruits' : fruits,
        '2015'   : [2, 1, 4, 3, 2, 4],
        '2016'   : [5, 3, 4, 2, 4, 6],
        '2017'   : [0, 0, 0, 4, 5, 3]}

p = figure(x_range=fruits, plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="hover", tooltips="$name @fruits: @$name")

p.vbar_stack(years, x='fruits', width=0.9, color=colors, source=data,
             legend=[value(x) for x in years])

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.axis.minor_tick_line_color = None
p.outline_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"

show(p)
```

#### Screenshots or screencasts of the bug in action
Google Chrome:
![bokeh_plot_chrome](https://user-images.githubusercontent.com/8526498/64021695-d2fc5180-cb34-11e9-8767-4985a89b25db.png)
Microsoft Edge
![bokeh_plot_edge](https://user-images.githubusercontent.com/8526498/64021696-d2fc5180-cb34-11e9-8251-4d21760a4177.png)

**Comment by bryevdv** [comment]
@jnettels The thickness is due to the *line*, which is technically dawn *around* the bar, which is filled to zero height. If you don't want an outline, you can set `line_color=None` or `line_width=0` on the bar glyph,
