### ISSUE TITLE
[FEATURE] External data file read, with Bokeh standalone html (no bokeh server)

### ISSUE THREAD

**Issue by Tablel352** [bokeh/bokeh#9215]
**Idea:**
On commodity webhosting, where there is no Bokeh server available, it might be useful to have read access to an external data file (such as CSV) from the standalone html file.

**Benefit:**
This way, a user/scheduler can update the data file (for example upload a new CSV file with the same name), and the Bokeh data visualization wil use this updated data automatically.

**Impact:**
The name of the external file should then, of course, be specified in the Python Bokeh code beforehand.

**Comment by bryevdv** [comment]
Do you mean read a file for the local filesystem without user intervention (i.e a file chooser dialog)? This is impossible, browsers will never allow any page to have direct local filesystem access due to security restrictions. A standalone Bokeh page could read a file from a URL with an AJAX call, etc. but that can be done today in a variety of different ways without any new features.  I would suggest taking this question to the Discourse:

https://discourse.bokeh.org

**Comment by Tablel352** [comment]
No, that is not what I mean. It's like the CSV function in D3:

`d3.csv("path/to/file.csv")`

Now the visualisation in the standalone HTML file and the data (in the CSV file), are seperated. And if user updates the CSV file, the Bokeh visualization op top changes with it. 

(the structure of the data in the csv file should not change)

**Comment by bryevdv** [comment]
The closest thing to that would be [`AjaxDataSource`](https://docs.bokeh.org/en/latest/docs/reference/models/sources.html#bokeh.models.sources.AjaxDataSource). Right now it expects data to be returned in the CDS format. I thought there was an open in issue to a `CustomJS` callback to it that could be used to adapt any format to the expected CDS format, but I can't find one. We could repurpose this issue for that, especially if you would be interested in working on it. It would be a great task for a new contributor.

**Comment by bryevdv** [comment]
For reference here is the docs or `adapter`:
```
adapter = Instance(CustomJS, help="""
    A JavaScript callback to adapt raw JSON responses to Bokeh ``ColumnDataSource``
    format.
    If provided, this callback is executes immediately after the JSON data is
    received, but before appending or replacing data in the data source. The
    ``CustomJS`` callback will receive the ``AjaxDataSource`` as ``cb_obj`` and
    will receive the raw JSON response as ``cb_data.response``. The callback
    code should return a ``data`` object suitable for a Bokeh ``ColumnDataSource``
    (i.e.  a mapping of string column names to arrays of data).
    """)
```
