### ISSUE TITLE
[BUG] Shared ColumnDataSource issues in JS callback (Uncaught TypeError: Cannot read property 'connect' of undefined)

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#9218]
**ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)**
```
Python version      :  3.7.2 (default, Mar 15 2019, 01:06:31) 
IPython version     :  (not installed)
Tornado version     :  6.0.3
Bokeh version       :  1.3.0
BokehJS static path :  /usr/local/lib/python3.7/site-packages/bokeh/server/static
node.js version     :  v10.15.1
npm version         :  6.10.0
```
OS: Mac OS X Mojave 10.14.6
Browser: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Description of expected behavior and the observed behavior**
Expected behavior: page should open and a plot containing line and circles should be shown 

Observed behavior: a new page opens but no plot is shown. The following JS error is given in JS console in the browser:

```js
Uncaught TypeError: Cannot read property 'connect' of undefined
    at e.t.connect (bokeh-1.3.0.min.js:31)
    at n (bokeh-1.3.0.min.js:31)
    at e.connect_signals (bokeh-1.3.0.min.js:31)
    at e.finalize (bokeh-1.3.0.min.js:31)
    at bokeh-1.3.0.min.js:31
    at i (bokeh-1.3.0.min.js:31)
    at i (bokeh-1.3.0.min.js:31)
    at i (bokeh-1.3.0.min.js:31)
    at i (bokeh-1.3.0.min.js:31)
    at i (bokeh-1.3.0.min.js:31)
```

**Complete, minimal, self-contained example code that reproduces the issue**

main.py
```py
from bokeh.plotting import show, figure
from bokeh.models import ColumnDataSource, CustomJS

p = figure()

source = ColumnDataSource(dict(x = [1, 2], y = [2, 1]))
line = p.line('x', 'y', source = source)
circle = p.circle('x', 'y', source = source)

glyphs = [line, circle]
                       
source.selected.js_on_change('indices', 
                             CustomJS(args = {'glyphs': glyphs},  
                                      code = 'console.log("OK")'))                                                            
show(p)
```

**Additional Info**

When I replace the code with:
```py
from bokeh.plotting import show, figure
from bokeh.models import ColumnDataSource, CustomJS

p = figure()

line = p.line(x = [1, 2], y = [2, 1])
circle = p.circle(x = [1, 2], y = [2, 1])

glyphs = [line, circle]
                       
glyphs[0].data_source.selected.js_on_change('indices', 
                                            CustomJS(args = {'glyphs': glyphs},  
                                                     code = 'console.log("OK")'))                                                            
glyphs[1].data_source.selected.js_on_change('indices', 
                                            CustomJS(args = {'glyphs': glyphs},  
                                                     code = 'console.log("OK")'))     
show(p)
```

then everything works fine. Another option is to create a separate source for each glyph (which is not the best solution):
```py
from bokeh.plotting import show, figure
from bokeh.models import ColumnDataSource, CustomJS

p = figure()

source_line = ColumnDataSource(dict(x = [1, 2], y = [2, 1]))
source_circle = ColumnDataSource(dict(x = [1, 2], y = [2, 1]))
line = p.line('x', 'y', source = source_line)
circle = p.circle('x', 'y', source = source_circle)

glyphs = [line, circle]
                       
source_line.selected.js_on_change('indices', 
                                  CustomJS(args = {'glyphs': glyphs},  
                                           code = 'console.log("OK")'))  
source_circle.selected.js_on_change('indices', 
                                  CustomJS(args = {'glyphs': glyphs},  
                                           code = 'console.log("OK")'))                                                          
show(p)
```

**Comment by bryevdv** [comment]
@tony-bony FWIW another option could be to give each glyph a separate unique name in `args`, instead of putting them in a list. 

cc @mattpap

**Comment by tony-bony** [comment]
I actually wanted to group two glyphs in a tuple (line, circle) to form one logical glyph to easily toggle visibility via a callback. So I had 
`renderers = [(line1, circles1), (line2, circles2), etc...]` but this was giving issues. 
My current work-around is: 
`renderers = {  "name1": [line1, circles1], "name2": [line2, circles2], etc... }`

**Comment by p-himik** [comment]
A bit simpler example:
```python
from bokeh.io import show
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.plotting import figure

cds = ColumnDataSource(data=dict(x=[0], y=[0]))

p = figure()
p.circle('x', 'y', source=cds)

cds.js_on_change('patching', CustomJS(args=dict(p=p), code=''))

show(p)
```

It seems that it's because `finalize()` calls both `initialize()` and `connect_signals()`. Tentatively, I would speculate that calling `initialize()` first on _all_ models only then calling `connect_signals()` would solve this issue.

**Comment by p-himik** [comment]
Just tried that. It worked both for my example and the example in the OP. @mattpap does such a solution make sense to you?

**Comment by mattpap** [comment]
That should work, at least as a temporary measure, because this doesn't address what I think is the underlying issue, which is wrong iteration order in `foreach_depth_first()`. Perhaps you could benchmark this solution on bokehjs level? I'm wondering how much another iteration over an entire object graph adds to the overall initialization time. Though I would have to add some benchmarking capability to our tests first.

**Comment by p-himik** [comment]
> wrong iteration order in `foreach_depth_first()`

Are you sure it's not possible to create circular references with e.g. `args` of `CustomJS`? Hmm, maybe even if it is possible, it should be reported as a user error.

> Perhaps you could benchmark this solution on bokehjs level?

I would definitely prefer to not do that before the mentioned benchmarking capability is in place.
But I don't think it can possibly create much of an impact: iteration is cheap (assuming you store the steps and not calculate them twice), and this step is run only once, when the document is first fetched.

**Comment by p-himik** [comment]
This just popped up again at https://discourse.bokeh.org/t/reset-zoom-after-data-source-update-from-bokeh-server/5340/11

I now realize that circular references are definitely possible, and are completely justified. In the example above, `ColumnDataSource` has `CustomJS`, which has `GlyphRenderer`, which has the data source. @mattpap Do you have any thoughts on the possibility of such cycles?

**Comment by mattpap** [comment]
> Do you have any thoughts on the possibility of such cycles?

Not yet. If you can, please submit a PR with your original solution. We can always improve this later.
