### ISSUE TITLE
[BUG] Update time is different for Python2/Python3

### ISSUE THREAD

**Issue by skata112** [bokeh/bokeh#9225]
Hi.

I have an app for visualizing data in a database. In the app I have a button for loading the data from the database, and when it starts downloading I display a text that says that the downloading has started. I recently updated my code to Python 3 and now the text is updated after the database has been loaded. I added a toy example below where I have replaced the database loading with a time.sleep call.

```
from bokeh.server.server import Server
from bokeh.layouts import column
from bokeh.models.widgets import Button
from bokeh.models import PreText

class Layout:

    def __init__(self):
        self._button = Button(label='Click')
        self._status_indicator = PreText(text='Button pressed: 0 times', width=800)
        self._button.on_click(self._update_message)
        self.counter = 0

    def _update_message(self):
        self.counter += 1
        self._status_indicator.text = 'Button pressed: ' + str(self.counter) + ' times'
        time.sleep(5) # Simulate database load

    @property
    def widget(self):
        return column(self._button, self._status_indicator)

def main(doc):

    layout = Layout()
    doc.add_root(layout.widget)


if __name__ == '__main__':
    print('Opening Bokeh application on http://localhost:5007/')

    server = Server({'/': main}, num_procs=1, port=5007)
    server.start()
    server.io_loop.start()

```

In the example above python2 will show the text when i press the button, while python3 will wait for the sleep. Is this intentional?

Best Regards,
Simon

**Comment by bryevdv** [comment]
Not intended, but to be honest I don't understand how the behavior you describe for python 2 is possible. The bokeh server is asynchronous but single-threaded, so if you block in a callback, you block the server from sending update events. The Python 3 behavior is what I would expect, and Python 2 support is ending in the nexts few months. So I think this is `reso: noaction` would be appropriate here. 

Generally speaking, if you need to do blocking work, you should follow the guidance in 

https://docs.bokeh.org/en/latest/docs/user_guide/server.html#updating-from-threads

**Comment by bryevdv** [comment]
I'm going to go ahead and close this as `noaction` for the reasons stated.
