### ISSUE TITLE
[BUG] WebGL + CDSView seems to use incorrect marker fill colours

### ISSUE THREAD

**Issue by andrewramsay** [bokeh/bokeh#9230]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 1.0.4 + 1.3.4
Python 3.7.4
Windows 10 + (Arch) Linux
Firefox Dev + Chrome Dev

#### Description of expected behavior and the observed behavior
I guess this is a pretty obscure issue, but it was leading to some problems with a bokeh server app I'm working on and so I spent a while trying to narrow down the cause. 

The app has a figure that displays a collection of circle markers. The data comes from a ColumnDataSource passed to ```circle()``` using the source keyword arg. There are two types of points in the collection, and I'm using a CDSView instance passed with the view keyword arg combined with a checkbox widget to allow the figure to be toggled between showing all the points, or just one specific type. The datasource has a 'fill' column with hex colour strings for each point, and so when calling circle() I just set ```fill_color='fill'``` to handle that. That all works as expected.

The problem appears when updating the CDSView instance so that it displays all or only some of the markers. I expected that I could simply use an IndexFilter containing the datasource indices of the subset of points I wanted to display, and that does indeed show the correct set of markers. But it didn't seem to be displaying them with the right fill colours for some reason. Eventually I realised that it was seemingly reading the fill colours consecutively from index 0 of the datasource, not picking out the values specified by the filter. The end result of this was that toggling back and forth between the two states caused the colours to toggle between two different mappings as well. 

What finally fixed it was simply removing ```output_backend='webgl'``` from my call to ```figure```. I'd added this to see if it improved performance as some of the plots have a few thousand points, and then forgot about it. With the same code and that parameter removed, I can now toggle back and forth and see the colours remain fixed as they should. 

The example script below should show two plots, one using the default backend and one using WebGL. It creates a simple dataset with points distributed between the left/right halves, colouring the first POINTS/2 markers red and the others green. As you can see in the screenshots, the "all points" state of both plots is identical, and as you'd expect there are a mix of colours on either side. After clicking the "toggle" button to hide half the points, the default backend plot retains both position and marker colours, while the WebGL plot retains position but colours all the markers red - since the red values are the first half of the 'fill' column in the datasource, this seems to indicate it's ignoring the IndexFilter indices and is reading the colours from the beginning of the 'fill' column instead. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
from random import random

import bokeh
from bokeh.layouts import column
from bokeh.models import Button, CDSView, IndexFilter, ColumnDataSource
from bokeh.plotting import figure, curdoc

# bokeh serve example.py

POINTS = 100

data = {'x': [], 'y': [], 'fill': []}
for i in range(POINTS):
    # put half the points on either side of the plot
    data['x'].append(random() + (i % 2))
    data['y'].append(random())
    # colour the first POINTS//2 markers red and the rest green
    data['fill'].append('#ff0000' if (i < POINTS // 2) else '#00ff00')

# a filter which only shows the points on the left half
fil = IndexFilter([i for i in range(POINTS) if i % 2 == 0])

def callback():
    view.filters = [] if len(view.filters) == 1 else [fil]

ds = ColumnDataSource(data=data)
view = CDSView(source=ds, filters=[])

p_ok = figure(x_range=(-0.25, 2.25), y_range=(-0.25, 1.25), title='Using default backend')
p_ok.circle('x', 'y', radius=.05, source=ds, view=view, fill_color='fill')

p_bug = figure(x_range=(-0.25, 2.25), y_range=(-0.25, 1.25), title='Using WebGL backend', output_backend='webgl')
p_bug.circle('x', 'y', radius=.05, source=ds, view=view, fill_color='fill')

button = Button(label="toggle")
button.on_click(callback)
curdoc().add_root(column(button, p_ok, p_bug))
```
#### Screenshots or screencasts of the bug in action
Here's what the script should look like when started:
![one_](https://user-images.githubusercontent.com/9051013/65313533-681ac500-db8c-11e9-9386-24ec95abce64.jpg)

And here is the toggled state showing the difference between default (top) and WebGL (bottom) backends:
![two_](https://user-images.githubusercontent.com/9051013/65313534-681ac500-db8c-11e9-9c34-08613e0a2519.jpg)

**Comment by bryevdv** [comment]
Thanks for the detailed bug report @andrewramsay FYI we are hoping to get some funding to completely overhaul WebGL support in Bokeh, but that won't be until some time nexts year.

**Comment by jokteur** [comment]
I seem to face the same bug (Bokeh 1.3.4 + 1.4.0, Python 3.7.3, Ubuntu with WSL). I switched to the default backend, but the bug seems to persist when using the box_select or lasso_select tool. Using the reset button makes the colors right again.

I used the code of @andrewramsay and I just added the box select tool. Here are the results 👍 

![2019-11-1022-28-39](https://user-images.githubusercontent.com/25845695/68551145-12cf9700-040a-11ea-9005-342973a6bbd2.gif)

It seems that for now I can only avoid this bug by avoiding using CDSView.

**Comment by p-himik** [comment]
Can confirm that this does not require WebGL to reproduce. A minimal example:
```python
from bokeh.io import show
from bokeh.models import ColumnDataSource, BooleanFilter, CDSView
from bokeh.palettes import d3
from bokeh.plotting import figure

p = figure(plot_width=300, plot_height=300, tools='tap,box_select,reset')

n = 4
data = ColumnDataSource(dict(x=list(range(n)), y=list(range(n)), c=d3['Category10'][n]))
v = CDSView(source=data, filters=[(BooleanFilter([False, True, True, True]))])
p.circle('x', 'y', source=data, color="c", size=20, view=v)

show(p)
```
If you tap or hover over any circle, it will be rendered in a different color.

The root cause is that `visuals.fill` for regular glyphs should have `all_indices`. But `all_indices` is set only by `GlyphView.set_data`, which is not called for glyph variants, such as decimated, selection, nonselection, hover, muted.

**Comment by p-himik** [comment]
I tried to fix it by calling `glyph.set_data` along with `glyph.set_visuals` for all glyph variants. And it does indeed fix the issue for the default backend. But it breaks the WebGL backend. The whole regular vs WebGL glyph logic separation seems quite a bit convoluted making a quick fix not possible.

**Comment by mattpap** [comment]
> I tried to fix it by calling glyph.set_data along with glyph.set_visuals (...)

This would also cancel out optimization the current approach provides. There's a simpler way to fix selection glyphs, etc. I will submit a PR shorty. However, webgl requires some deeper changes.

**Comment by p-himik** [comment]
> This would also cancel out optimization the current approach provides.

Indeed. It seems to me that it would make sense to combine all glyph variants in a single glyph that shares all the relevant data automatically. Visuals would be separate but `set_data` and all similar stuff would be the same. Or maybe it's possible and makes sense to move all such stuff to the `GlyphRenderer` level, I don't know.
