### ISSUE TITLE
Add 256-color palettes, add a function to generate diverging palettes

### ISSUE THREAD

**Issue by russellburdt** [bokeh/bokeh#9241]
This feature request will modify the `bokeh.palettes` module to include additional 256-color palettes and a `diverging_palette` function.  

The _problem_ this feature request could be considered to solve is that [**bokeh 1.3.4 palettes**](https://bokeh.pydata.org/en/latest/docs/reference/palettes.html) do not currently replicate all of the available [**matplotlib 3.1.1 palettes**](https://matplotlib.org/examples/color/colormaps_reference.html). 

Color palettes in **bokeh** are hard-coded as lists of hex color strings.  For example,
```
>>> from bokeh import palettes
>>> palettes.Reds9
['#67000d', '#a50f15', '#cb181d', '#ef3b2c', '#fb6a4a', '#fc9272', '#fcbba1', '#fee0d2', '#fff5f0']
```
Max size of a `palettes.Reds` palette in **bokeh** is 9 which may hide information in a chart where colors encode numbers.  A 256-color palette could encode more information.

![reds](https://user-images.githubusercontent.com/11150141/65626450-4f425300-df82-11e9-9580-e1ccb2680d0a.png)

This feature request will add several 256-color palettes (including but not limited to):

![palettes256](https://user-images.githubusercontent.com/11150141/65627487-54a09d00-df84-11e9-8885-c3fb407113b6.png)

**A second component of this feature request** is to add a function to the `bokeh.palettes` module that can return any diverging palette created as a piecewise linear interpolation of fixed palettes. 

![diverging1](https://user-images.githubusercontent.com/11150141/65628158-c0373a00-df85-11e9-8a8b-1da0c860c54b.png)

The `diverging_palette` function will also support asymmetric diverging palettes, which means the intersection of the two palettes constituting the diverging palette is somewhere other than the middle.  This can be useful to create charts where high and low values are mapped to colors asymmetrically (e.g. as in [this blog post](https://www.rbtechblog.com/blog/stocks2018)).

![diverging2](https://user-images.githubusercontent.com/11150141/65628697-d5f92f00-df86-11e9-91ac-22fdd28d4aa2.png)

The `diverging_palette` function can be implemented as in the code below.  It is a direct manipulation of input palettes that uses the already-implemented `linear_palette` function.  A `ValueError` will be raised by the `linear_palette` function if more colors are requested than are available.
```
def diverging_palette(palette1, palette2, n=256, midpoint=0.5):
    palette2 = palette2[::-1]
    n1 = np.round(midpoint * n)
    n2 = np.round((1 - midpoint) * n)
    return palettes.linear_palette(palette1, n1) + palettes.linear_palette(palette2, n2)
```

**Comment by bryevdv** [comment]
@bokeh/dev I am +1 on adding the `diverging_palette` palette, but +0 about adding the additional 256 color palettes (e.g. `Reds256`). Does anyone have strong feelings for/against?

**Comment by philippjfr** [comment]
Adding a utility to generate the 256 color palettes from the existing palettes seems useful, also +0 about actually hardcoding those. We ship exactly that in HoloViews already and expand them on the fly when requested.

**Comment by p-himik** [comment]
I would definitely like to see a function that is able to generate N colors from a specified palette. 256 or not 256 - any number that's relevant to my data.

On a side note, I would also rewrite the whole palette module since it's impossible to work with it in an IDE. But that's likely a separate task.

**Comment by bryevdv** [comment]
@p-himik can you add an issue for your proposal? I think you mean changing to tuples instead of lists and then ditching the class-module business. That's fine but it should coincide with 2.0

**Comment by mattpap** [comment]
> On a side note, I would also rewrite the whole palette module since it's impossible to work with it in an IDE. But that's likely a separate task.

We already did this in 2.0 branch, to allow static typing of that module.

**Comment by p-himik** [comment]
@mattpap `landing-2.0`, right? What IDE do you use? Because PyCharm still doesn't have any auto-completions for the palettes.

**Comment by russellburdt** [comment]
@p-himik Right now the `linear_palette` function will return a palette with an arbitrary number of colors less than or equal to an input palette.  The max size in many cases is 256, and less than that in other cases.  `matplotlib` implementation of palettes can return any arbitrary number (including above 256) from any palette.  256 is good upper limit from a practical point of view.
```
In [13]: palettes.linear_palette?
Signature: palettes.linear_palette(palette, n)
Docstring:
Generate a new palette as a subset of a given palette.

Given an input ``palette``, take ``n`` colors from it by dividing its
length into ``n`` (approximately) evenly spaced indices.
...
```

**Comment by p-himik** [comment]
@russellburdt 
> and less than that in other cases

That's exactly what the issue was for me. Only 6 palettes have 256 colors.

**Comment by bryevdv** [comment]
OK, I think I am fine to just add the new 256 palettes. It's not like they will increase the size of the package to an appreciable degree. @russellburdt can you list all the ones you have in mind? The OP mentions "including but not limited to..."

**Comment by bryevdv** [comment]
I've tentatively added this to the 1.4 milestone but it's fine if it slips. To get in 1.4 would need a PR before the end of next wee.

**Comment by jbednar** [comment]
How will we know when you'll next need to wee?

**Comment by bryevdv** [comment]
k

**Comment by mattpap** [comment]
> Because PyCharm still doesn't have any auto-completions for the palettes.

Right, I guess the module hack is still an issue. vscode, that I use, has the same problem.

**Comment by bryevdv** [comment]
> Right, I guess the module hack is still an issue. vscode, that I use, has the same problem.

Yes, I believe the proposal there is to replace the lists with tuples, so that they are immutable, and get rid of the module hack altogether.

**Comment by russellburdt** [comment]
@bryevdv @p-himik Any new palettes added for this issue #9241 will be tuples instead of lists.  Would we be able to use a single PR to address this issue as well as #9248 ?

**Comment by p-himik** [comment]
@russellburdt Why would a single PR be better?
Anyway, I'm not sure because @bryevdv said that using tuples for palettes should coincide with 2.0 and this issue has 1.4 as its milestone.

**Comment by bryevdv** [comment]
@russellburdt Yes, please follow the existing patterns int he module for all new palettes (i.e. return lists as all the existing ones do), we will make breaking changes to the structure of the module after the 1.4 release in a separate PR.

**Comment by russellburdt** [comment]
@p-himik There are 3 options for type of palettes created / modified in #9241.  Please provide some direction here.

1. Add new palettes as tuples
2. Add new palettes as lists
3. If (1) also convert all existing palettes from lists to tuples.

**Comment by russellburdt** [comment]
@bryevdv Got that, thanks.

**Comment by russellburdt** [comment]
@bryevdv @p-himik @mattpap Given that it is already agreed to rewrite the whole palettes module in 2.0 I think we can limit the scope of changes for this issue. I propose to add `Reds256`, `Purples256`, `Blues256`, `Greens256`, and `Oranges256` palettes as lists of hex color strings (not tuples) and to add a `diverging_palette` function with signature `diverging_palette(palette1, palette2, n=256, midpoint=0.5)` that returns a generic symmetric or asymmetric diverging palette.  

This will be my first open-source contribution, so I may have some process questions later on.

**Comment by bryevdv** [comment]
@russellburdt that sounds perfect, please let us know any questions we an answer, and thanks!

**Comment by bryevdv** [comment]
@russellburdt Just as an FYI, for this to go in 1.4 it would need to be submitted/merged befor the end of next week

**Comment by russellburdt** [comment]
PR has been submitted.
