### ISSUE TITLE
[BUG] "set_select" and "select" are not working well with layouts

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#9245]
With the rest of the elements: `Circles`, `LinearAxis`, `Title` the method `set_select` works well as you can check in the following example. But, I am not able to make it work when I try to select plots through the layout:

    from bokeh.io import show
    from bokeh.models import ColumnDataSource, LinearAxis, Title, Circle, Plot
    from bokeh.plotting import figure, Figure
    from bokeh.layouts import column, row

    source = ColumnDataSource(dict(
        x=[1, 2, 3, 4, 5, 6],
        y=[1, 2, 3, 4, 5, 6],
    ))

    # ------------------ PLOT 1 ---------------------- #

    p = figure(
        title='Original',
        plot_width=200,
        plot_height=200,
        x_axis_label='X Axis',
        y_axis_label='Y Axis',
        tools='lasso_select,tap',
    )
    p.circle(
        x='x', y='y',
        size=3, source=source
    )
    p.xaxis.axis_label_text_font_style = 'normal'
    p.yaxis.axis_label_text_font_style = 'normal'

    # ------------------ BIGGER PLOT ---------------------- #

    p2 = figure(
        name='bigger',
        title='Bigger',
        plot_width=200*3,
        plot_height=200*3,
        x_axis_label='X Axis',
        y_axis_label='Y Axis',
        tools='',
        toolbar_location=None,
    )
    c2 = p2.circle(
        name='p2_circle',
        x='x', y='y',
        size=3, source=source
    )
    p2.xaxis.axis_label_text_font_style = 'normal'
    p2.yaxis.axis_label_text_font_style = 'normal'

    big_width = 2

    p2.set_select(
        selector=LinearAxis,
        updates=dict(
            axis_line_width=big_width,
            major_tick_line_width=big_width,
            minor_tick_line_width=big_width,

            axis_label_text_font_size='15pt',
            major_label_text_font_size='10pt'
        )
    )

    p2.set_select(
        selector=Title,
        updates=dict(text_font_size='20pt')
    )

    p2.set_select(
        selector=Circle,
        updates=dict(size=15)
    )

    r = row([p, p2])

    r.set_select(
        selector=Figure,
        updates=dict(
            plot_width=500,
        )
    )

    # r.set_select(
    #     selector=Plot,
    #     updates=dict(
    #         plot_width=500,
    #     )
    # )

    show(r)

And I am getting this error

    Traceback (most recent call last):
    File "set_select_plot.py", line 81, in <module>
        plot_width=500,
    File "env\lib\site-packages\bokeh-1.3.4-py3.7.egg\bokeh\model.py", line 628, in set_select
        for obj in self.select(selector):
    File "env\lib\site-packages\bokeh-1.3.4-py3.7.egg\bokeh\core\query.py", line 87, in <genexpr>
        return (obj for obj in objs if match(obj, selector, context))
    File "env\lib\site-packages\bokeh-1.3.4-py3.7.egg\bokeh\core\query.py", line 159, in match
        for key, val in selector.items():
    AttributeError: type object 'Figure' has no attribute 'items'

Also, If I use select in a plot like this works well

    p2.select(
        name='p2_circle'
    )

And if I use the method with a layout an error is thrown `TypeError: select() got an unexpected keyword argument 'name'`:

    r.select(
        name='p2_circle'
    )

**Comment by bryevdv** [comment]
@chesucr I'm a little unclear. This is uncommented:
```
r.set_select(
    selector=Figure,
    updates=dict(
        plot_width=500,
    )
)
```
Are you saying that works, or not?

**Comment by bryevdv** [comment]
@chesucr Well, it's easy enough to try and see that it doesn't. But this does work:

```
r.set_select(
     selector=dict(type=Figure),
     updates=dict(
         plot_width=500,
     )
)
```
The actual format of selectors is dictionaries like those. There are some convenience APIs that try to convert e.g. types in to `dict(type=...)` automatically, and it seems that's not what is happening here. Do you want to try and take a look at this? I am happy to point you at the relevant modules. Given that this is a very obscure function, and there is a workaround (to use the actual full selector format) I doubt this will rise on my priority list any time soon.

**Comment by kumaran-14** [comment]
@bryevdv I'd like to take an attempt at this. I have built bokeh from source and can start right away.

What should I look into?

**Comment by bryevdv** [comment]
Hi @kumaran-14 The `set_select` function is defined on `Model` here:

https://github.com/bokeh/bokeh/blob/master/bokeh/model.py

and on `Document` here:

https://github.com/bokeh/bokeh/blob/master/bokeh/document/document.py

And there are some minimal test (for Document only) here:

https://github.com/bokeh/bokeh/blob/master/tests/unit/bokeh/document/test_document.py#L301


As I recall the issue was that it was desirable for 
```
r.set_select(selector=Figure, ... )
```
to work as a convenience shorthand for the more verbose:
```
r.set_select(selector={"type": Figure}, ... )
```
I think you can make that happen by simply checking to see if the value of selector is `isinstance` of a Bokeh `Model` and if it is, replacing the value with the dict. It would be good to add some minimal tests for the `Model.set_select` as well as making sure both groups of test cover the case in this issue where the `Selector` passed in is a model.

**Comment by bryevdv** [comment]
I guess I should add, the above is the "quick fix" if you want to look in to things a little more deeply, you could see if it's possible to make updates in only one place, in the `query` module:

https://github.com/bokeh/bokeh/blob/master/bokeh/core/query.py

**Comment by kumaran-14** [comment]
@bryevdv I was trying to fix it, but faced some problems.
First I executed the above file, reproduced the error and got the output when I used dict instead. Then I trying to debug and play around for some time. It was all fine and suddenly now I could no longer get the output. The html file shows this error.

```
Uncaught TypeError: Cannot read property 'connect' of undefined
    at p.connect (bokeh-2.0.0dev5.min.js:162)
    at p.connect_signals (bokeh-2.0.0dev5.min.js:229)
    at p.finalize (bokeh-2.0.0dev5.min.js:161)
    at bokeh-2.0.0dev5.min.js:148
    at n (bokeh-2.0.0dev5.min.js:148)
    at s (bokeh-2.0.0dev5.min.js:148)
    at Function._initialize_references_json (bokeh-2.0.0dev5.min.js:148)
    at Function.from_json (bokeh-2.0.0dev5.min.js:148)
    at g (bokeh-2.0.0dev5.min.js:146)
    at bokeh-2.0.0dev5.min.js:146
```

The examples given in the developer documentation run correctly though.
Could you help me out?

**Comment by bryevdv** [comment]
@kumaran-14 Sure but I really would need some idea of the changes that you made

**Comment by kumaran-14** [comment]
Thats the issue. I tried it after ```git reset --hard```. It still persists.

**Comment by bryevdv** [comment]
See above edit about using locally built BokehJS

**Comment by kumaran-14** [comment]
@bryevdv  thanks for the quick response. It works now. 
Now, I'm trying ```isinstance(selector, Model)```, which seems to evaluate to false. Is this what you suggested? Or Am I wrong?
Thanks again.

**Comment by bryevdv** [comment]
Sorry, mis-typed earlier. These are types so you want `issubclass`:
```
In [1]: from bokeh.model import Model

In [2]: from bokeh.models import Plot

In [3]: issubclass(Plot, Model)
Out[3]: True
```

**Comment by kumaran-14** [comment]
Thanks. 
In `/bokeh/model.py`, I added few these few lines

```
	# added these
	if (isinstance(selector, dict)):
        selector = selector["type"]
    if (issubclass(selector, Model)):
        selector = dict(type=selector)
	
	# existing code
    for obj in self.select(selector):
        for key, val in updates.items():
            setattr(obj, key, val)
```

Now, In above example, all these work correctly.

```
	.
	.
	.

	r.set_select(
	     selector=dict(type=Figure),
	     updates=dict(
	         plot_width=500,
	     )
	)
	
	r.set_select(
	    selector=Figure,
	    updates=dict(
	        plot_width=500,
	    )
	)
	
	r.set_select(
	    selector=Plot,
	    updates=dict(
	        plot_width=500,
	    )
	)

	show(r)

```

Is this close to what you had in mind? Do you think hardcoding the keyname 'type' is right?

**Comment by bryevdv** [comment]
@kumaran-14 I don't think the first two lines:
```
if (isinstance(selector, dict)):
    selector = selector["type"]
```
are necessary. `dict` is the actual real format for selectors, they should just be passed through as-is. The only task is to check if a passed-in selector value is a `Model` instead of a `dict` and then in that case, construct the `dict` with key "type" as a convenience.

**Comment by kumaran-14** [comment]
@bryevdv Sure.
My pre-commit hook `py.test -m codebase` fails due to wrong import order in some files.
I run this on unchanged working tree of bokeh upstream. Any suggestions?

**Comment by kumaran-14** [comment]
@bryevdv Sure.
My pre-commit hook `py.test -m codebase` fails due to wrong import order in some files.
I run this on unchanged working tree of bokeh upstream.
How do I fix this?

**Comment by bryevdv** [comment]
@kumaran-14 you need to  make sure you have done `pip install channels` first. There is not a conda package for it yet, and `isort` gets confused about some third part vs package imports if it is not installed.
