### ISSUE TITLE
New bokeh-static package

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#9249]
This may not be the right place for this issue, but we can move it as appropriate. I was considering again today my annoyances with getting static plots (in particular so i can readily share static views of notebooks on github)

Additionally, firefox is now available as a conda package (https://github.com/conda-forge/firefox-feedstock). This will provide us much nicer rendering than what phantomjs spits out by default.

I'm imagining a workflow like:

```
conda install bokeh-export   # install selenium, pillow, phantomjs, firefox, geckodriver

# In a notebook
from bokeh_export import (
    initialize_driver,
    notebook_show as show
)
initialize_driver('firefox')  # set-up a single driver instance for faster rendering, pick your driver. use this to pass in options that are passed into a typical webdriver setup

p = figure().....
show(p)  # does the work of Ipython.display.Image(export_png(p)) with driver globally scoped to be the one setup
```

**Comment by bryevdv** [comment]
@birdsarah Any new helpers for creating webdrivers shoud plug in to the existing webdriver control machinery:

https://github.com/bokeh/bokeh/blob/master/bokeh/io/webdriver.py

Where would this package live? I doubt Anaconda would add it to defaults. I'm normally not super inclined to put more than releases in the  bokeh channel at this point, tho if this is just a metapackage (it seems?) then maybe that's ok. Or we can create a new channel for bokeh-related but not-release things.

**Comment by birdsarah** [comment]
> Where would this package live?

conda-forge and bokeh channel is what I'd suggest. I generally only use conda-forge these days. I'm just sick of working a whole bunch the getting an error and remembering that I need to install selenium etc.

>  Tho if this is just a metapackage

It certainly could be

> Any new helpers for creating webdrivers should plug in to the existing webdriver control machinery.

That's fine with me. 

Combining together these ideas, I think you get the following. Feel free to correct with a code example I may have misunderstood what you were trying to convey (I'm torn between `image` / `static` / `export`): 

```python
conda install -c bokeh bokeh bokeh-export  # Now my environment.yaml can be clean and I know much better why things like selenium have been installed

from bokeh.io import show_image, output_image
output_image(context='notebook', driver='firefox', ...other options)  # sets up a driver object
p = figure().....
show_image(p)  # Get out an image in the notebook / open a browser tab with an image in the 
```

The context option to output_image would setup using `IPython.display` to put image in a notebook, or html if you wanted to spit out html page with the image in it (or file if you wanted to save images to file???) - This is a straw proposal that I just came up with to solicit suggestions.

**Comment by bryevdv** [comment]
@birdsarah This all sounds fairly reasonable. I don't really use  conda-forge, and I probably would not use the package much either tbh, so I'd ask that you take the lead on implementing this (happy to assist with anything, as necessary).

For the package name `bokeh-optional` or `bokeh-extras` also seem reasonable and more generic, if more generic is better. The others all seem OK too though.

As for the API I think it could be simpler? All the `output_X` functions activate  persistent modes, so if you call `output_image` I don't see why we wouldn't just make `show` do the right thing based on the active mode. `show_image` could be a low-level function, ala `show_app` but I would not imagine advertising or demonstrating it. 

Alternatively, if you want a special function just for explicitly showing images, then a  persistent mode is not necessary.

**Comment by bryevdv** [comment]
@birdsarah did you intend to work on this? If not I think it can be closed

**Comment by birdsarah** [comment]
I did. Whether I'll get to it any time soon is an open question.....if I can re-open it at a later date if I get motivated then I'm fine with closing. This also seems like it would be a good intro issue. 

I noticed this is still labeled a discussion - is this really still a discussion as opposed to a feature. I thought we'd had the discussion and settled on a path. Are you wanting to close it as a stale discussion?

**Comment by bryevdv** [comment]
> I noticed this is still labeled a discussion - is this really still a discussion as opposed to a feature. I 

I'd consider it a task, but it was only still `discussion` because no one happened to change it. I'm not pressed to close if you think there it's still good to keep open, just checking in on things.

**Comment by birdsarah** [comment]
it's definitely an improvement i'd love to see happen, and i will work on it, if it comes up.

**Comment by birdsarah** [comment]
In case it's useful inspiration: have been playing with altair - they have an `altair_saver` package which seems to be similar to my idea here. Ref: https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format

**Comment by joelostblom** [comment]
@birdsarah @bryevdv You might have seen it already, but I just stumbled across the recently announced [Kaleido](https://medium.com/plotly/introducing-kaleido-b03c4b7b1d81) library from plotly, which is a new library for static export of web-based graphics, with the specific goal to make this functionality widely available.

> The goal of the Kaleido project is to make static image export of web-based visualization libraries as universally available and reliable as it is in matplotlib and ggplot2.

I am excited about this because I would love to see better support for this functionality across several libraries. While I don't know how this would fit with bokeh technically, it might be something to consider instead of developing a separate library for static export. In the blog post linked above, they mention briefly how to integrate it with other libraries:

> While the development of Kaleido has been motivated by the needs of the plotly.py community, we know we’re not unique in facing these challenges. We’ve designed the C++ and Python portions of Kaleido using a basic plugin architecture (Kaleido plugins are called Scopes) with the goal of making it possible to support image export for other web-based visualization libraries. If you’re interested in adding support to Kaleido for another web-based visualization library, check out the [Scope (Plugin) Architecture](https://github.com/plotly/Kaleido/wiki/Scope-(Plugin)-Architecture) wiki page and let us know how we can help!

**Comment by bryevdv** [comment]
We are definitely interested to look at kaleido, it's just a matter of someone finding the time. Assuming it works as well as the complicated selenium process we have how, I'd be in favor of just taking it on as a hard dependency since (AFAIK) it is widely available on pip and conda.

**Comment by birdsarah** [comment]
This is very interesting. Thanks for sharing @joelostblom.

**Comment by bryevdv** [comment]
I'm going to go head and close this. Pip downloads outnumber conda by 2 to 1 so making and maintaining a new conda package would be focussing on the wrong area. I would be more interested to exploring [`pyppeteer`](https://github.com/pyppeteer/pyppeteer) (which already exists) as a simple way for users to explore a chrome runtime. I recently saw it in another context and it "just worked".
