### ISSUE TITLE
[BUG] Empty bokeh.min.css in bokeh/server/static/css

### ISSUE THREAD

**Issue by jxrossel** [bokeh/bokeh#9255]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 1.3.4, python 3.6, windows 10

#### Description of expected behavior and the observed behavior

I use Bokeh to generate stand-alone figures embedded in my website using ``from bokeh.embed import components``. I provide the static files separately.

In version 1.0.2, I could go to the installed folder `bokeh/server/static/css` to get the `bokeh.min.css` file. In 1.3.4, this file is empty and there is a number of other small css files. What's the strategy to provide the css files without CDN ?

**Comment by mattpap** [comment]
Stylesheets are now included in `bokeh*.js` bundles as JS modules and loaded when needed. There is no need for managing bokeh's CSS files any more. We left empty `bokeh*.css` for backwards compatibility. Those will be removed in bokeh 2.0.

**Comment by jxrossel** [comment]
Nice, thanks !

**Comment by bernd-wechner** [comment]
Just a heads up that I'm on Bokeh 3.0.3 and the empty lists are still there, they were not removed in 2.0 it seems (and remain confusing for that reason).

**Comment by mattpap** [comment]
CSS bundles were dropped in PR https://github.com/bokeh/bokeh/pull/9332. If you are referring to `CSSResources`, then it is still in use for including third-party CSS bundles.

**Comment by bernd-wechner** [comment]
Referring `Resources`. In my debugger:

![image](https://user-images.githubusercontent.com/7296506/208652268-17ff3820-df93-4180-b333-a2359e4272b0.png)

Empty lists for `ccs_files` et. al.
