### ISSUE TITLE
[BUG] Incorrect BAD_EXTRA_RANGE_NAME trigger

### ISSUE THREAD

**Issue by jxrossel** [bokeh/bokeh#9256]
I found a case where https://github.com/bokeh/bokeh/issues/8723 is not solved (see last post there). I open this issue since I can't re-open https://github.com/bokeh/bokeh/issues/8723

**Comment by bryevdv** [comment]
@jxrossel please include all the relevant information directly in this issue so that it is self-contained. "last post there" is in general not a stable reference.

**Comment by jxrossel** [comment]
In 1.3.4, https://github.com/bokeh/bokeh/issues/8723 is still triggered incorrectly in the following case:

```
from bokeh.models import Range1d, LinearAxis, Legend
from bokeh.layouts import gridplot
from bokeh.embed import components

def plot_on_extra( p, legs ):
    """
    create twin axes and plot something on it
    """
    
    # init
    extra_range_name = 'extra'
    y_range_name = dict( y_range_name=extra_range_name )
    
    p.extra_y_ranges = { extra_range_name: Range1d( 0, 2 ) }    
    p.add_layout( LinearAxis( **y_range_name ), 'right' )
    lright = p.line( [0,2], [0,2], **y_range_name )
    legs.append( ( '1-extra', [ lright ] ) )

# inits
legs = []
extra_on_2nd_not_1st = True

p1 = figure()
l1 = p1.line( [0,3], [0,3] )
legs.append( ( '1', [ l1 ] ) )

if not extra_on_2nd_not_1st:
    # Doesn't create the bug
    plot_on_extra( p1, legs )

p2 = figure()
l2 = p2.line( [ 0,1], [0,1] )
legs.append( ( '2', [ l2 ] ) )

if extra_on_2nd_not_1st:
    # Creates the bug, but only if (1) Legend, (2) extra not defined on 1st figure
    plot_on_extra( p2, legs )

# Necessary to create the bug. NB: using [legs[0]] would not create it
legend = Legend( items=legs, location=(10, 0) )
p1.add_layout( legend, 'right' )

model = gridplot( [ p1, p2 ], ncols=1, plot_width=500 )
script, div = components( model )
```

Note: to get the bug, the extra axis must be on the 2nd figure (only) and the legend must cover both figures. It is maybe a side-effect of the unsupported shared legend (?): https://github.com/bokeh/bokeh/issues/7607

**Comment by bryevdv** [comment]
@jxrossel it did jump out to me that you were trying add glyphs renderers from different plots on a asingle legend. This is not currently supported at all. Closing with a reference to #7607
