### ISSUE TITLE
[BUG] Glyph clipping fails when using render level to control glyph order

### ISSUE THREAD

**Issue by jxrossel** [bokeh/bokeh#9260]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 1.3.4, Python 3.6, IE 11 and Edge

#### Description of expected behavior and the observed behavior

Specifying render level is suggested to control glyph order display here https://github.com/bokeh/bokeh/issues/5823

At the "annotation" and "overlay" levels, the glyphs are rendered outside the figure box.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure
from bokeh.models import Legend
from bokeh.palettes import plasma

levels = [ 'image', 'underlay', 'glyph', 'annotation', 'overlay' ]
colors = plasma( len( levels ) )
legs = []

p = figure( x_range=[1,2] )

for ii, ( level, color ) in enumerate( zip( levels, colors ) ):
    end = 3 + ii
    l = p.line( [ 0, 3 ], [ 0, end ], level=level, color=color, line_width=3 )
    legs.append( ( level, [ l ] ) )
    
legend = Legend( items=legs, location=(10, 0) )
p.add_layout( legend, 'right' )

show( p )

```
![image](https://user-images.githubusercontent.com/12891830/66122111-2e5faa80-e5df-11e9-9b45-0ee44df3ffa7.png)

**Comment by bryevdv** [comment]
The is intentional, to support annotations or overriders that might do past of their drawing outside the plot frame. If your want slope line annotations the is `Slope`, that clips itself.

**Comment by jxrossel** [comment]
Ok, thanks for the answer! I was able to avoid specifying levels altogether in the end by storing plot specifications in a list, each element having a field to specify the plot order. I then re-order the list using this field before plotting each element.
