### ISSUE TITLE
CDN invalidations too narrow

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9264]
Need a wildcard, e.g. 
```
aws cloudfront create-invalidation --distribution-id <<distid>> --paths '/en/dev/*'
```

**Comment by osule** [comment]
@bryevdv Would this wildcard invalidate all files in the `/en/dev` directory or and files in it and its subdirectory?

**Comment by bryevdv** [comment]
@osule Well, to start off, we definitely want to invalidate any object with  the `/en/dev` prefix. Otherwise the CDN will not serve the newer files. It's unclear to me from the docs whether the old (current) version of the invalidation does that. But updating to the line about should definitely accomplish what we need.

**Comment by osule** [comment]
From the [Cloudfront example docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html), the `/en/dev/*` pattern invalidates all objects in the directory whereas `/en/dev*` invalidates all objects prefixed with the pattern. 
The latter should be fitting in this case.

**Comment by bryevdv** [comment]
@osule I'm not sure sure? We do want to invalidate all objects in the "directory". To be clear we want to make sure that files like

> /en/dev/docs/user_guide/quickstart.html

*do* get invalidated, for instance. Will `/en/dev*` also capture this file?

**Comment by bryevdv** [comment]
@osule Thank you for pushing me on this, I was able to find another page in the docs one link away:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#invalidation-specifying-objects-paths

> To invalidate a directory, all of its subdirectories, and all of the files in the directory and subdirectories:
>
> /directory-path*

So you are indeed correct, I will merge the PR when green, thank you !
