### ISSUE TITLE
rename modify_doc in notebook app contexts

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9265]
`modify_doc` is a wonky name that relates only to a fairly low level view of how apps work, and APIs that most users will never see directly. See [this SO comment for an example of confusion](https://stackoverflow.com/questions/58286323/cannot-get-a-bokeh-checkbox-group-to-update-graph/58289753?noredirect=1#comment102950492_58289753) that name causes. For user-facing examples, we should switch to a function name that's more suggestive of the semantics that are important to users, that the function *defines* the app, e.g. `create_app` or even just `app`

**Comment by mattpap** [comment]
I think it could be extended to more classes of examples. I was confused with this myself when working on Django integration.

**Comment by bryevdv** [comment]
Here are all the occurrences under `examples`
```
./examples/howto/server_embed/flask_embed.py:
   16 : def modify_doc(doc):
   48 :     server = Server({'/bkapp': modify_doc}, io_loop=IOLoop(), allow_websocket_origin=["localhost:8000"])
./examples/howto/server_embed/flask_gunicorn_embed.py:
   35 : def modify_doc(doc):
   58 : bkapp = Application(FunctionHandler(modify_doc))
./examples/howto/server_embed/notebook_embed.ipynb:
   37 :     "Here is the function `modify_doc(doc)` that defines our app:"
   46 :     "def modify_doc(doc):\n",
   85 :     "Now we can display our application using ``show``, which will automatically create an ``Application`` that wraps ``modify_doc`` using ``FunctionHandler``. The end result is that the Bokeh server will call ``modify_doc`` to build new documents for every new sessions that is opened.\n",
   96 :     "show(modify_doc) # notebook_url=\"http://localhost:8888\" "
./examples/howto/server_embed/standalone_embed.py:
    9 : def modify_doc(doc):
   34 : server = Server({'/': modify_doc}, num_procs=4)
./examples/howto/server_embed/tornado_embed.py:
   22 : def modify_doc(doc):
   51 : server = Server({'/bkapp': modify_doc}, num_procs=4, extra_patterns=[('/', IndexHandler)])
```
I'm not personally concerned with updating all the usage in tests
