### ISSUE TITLE
[BUG] DataTable sorting broken

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#9266]
**ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)**
```
Python version      :  3.7.2 (default, Mar 15 2019, 01:06:31) 
IPython version     :  (not installed)
Tornado version     :  6.0.3
Bokeh version       :  1.3.0
BokehJS static path :  /usr/local/lib/python3.7/site-packages/bokeh/server/static
node.js version     :  v10.15.1
npm version         :  6.10.0
```
OS: Mac OS X Mojave 10.14.6
Browser: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Description of expected behavior and the observed behavior**
Expected behavior: table columns should remain unsorted when accidentally clicking on the column header and then editing a value in the same column

Observed behavior: After clicking the column header "Downloads" nothing happens (as expected) but after editing a value in the same column and hitting ENTER the sort action is still being executed

**Complete, minimal, self-contained example code that reproduces the issue**

main.py
```py
from datetime import date
from random import randint

from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

data = dict(dates=[date(2014, 3, i+1) for i in range(10)], 
            downloads=[randint(0, 100) for i in range(10)], )

columns = [TableColumn(field="dates", title="Date", formatter=DateFormatter()),
           TableColumn(field="downloads", title="Downloads"), ]

data_table = DataTable(source=ColumnDataSource(data), columns=columns, width=400, height=280, editable=True, sortable=False)

show(data_table)
```

**Reproduction steps**

1) Click the column header "Downloads"
2) Edit any value in the same column

**Additional Info**
JavaScript error after clicking on a column header:
```js
bokeh-tables-1.3.0.js:1048 Uncaught TypeError: Cannot read property 'map' of undefined
    at TableDataProvider.sort (bokeh-tables-1.3.0.js:1048)
    at SlickGrid.<anonymous> (bokeh-tables-1.3.0.js:1198)
    at Event.notify (bokeh-tables-1.3.0.js:11377)
    at trigger (bokeh-tables-1.3.0.js:14514)
    at HTMLDivElement.<anonymous> (bokeh-tables-1.3.0.js:14154)
    at HTMLDivElement.dispatch (bokeh-tables-1.3.0.js:5635)
    at HTMLDivElement.$event.dispatch (bokeh-tables-1.3.0.js:10177)
    at HTMLDivElement.elemData.handle (bokeh-tables-1.3.0.js:5487)
```

**Comment by bryevdv** [comment]
@tony-bony I don't understand this:

> Expected behavior: table columns should remain unsorted when accidentally clicking on the column header and then editing a value in the same column

If the header is clicked when sorting is enabled, then the columns should not remain unsorted, they should unconditionally change to be sorted, always. That's the purpose of setting `sortable=True`

Regardless, it appears sortable-ness became broken at some point. The issue is here:
```
  this.grid.onSort.subscribe((_event: any, args: any) => {
      columns = args.sortCols
      this.data.sort(columns)
      this.grid.invalidate()
      this.updateSelection()
      this.grid.render()
      if (!this.model.header_row) {
        this._hide_header()
      }
      this.model.update_sort_columns(columns)
    })
```
Specifially, `args.sortCols` does not exist. @mattpap did we rev versions or make changes to our fork recently?

**Comment by bryevdv** [comment]
Seems this has been broken since at least 1.0.x! I don't have any older envs laying around right now, but I know it worked at some point.

**Comment by bryevdv** [comment]
@tony-bony Oh, I only just noticed that you have `sortable=False`? I misunderstood your original title to mean that editable and sortable did not work when they are **both enabled**. OK, so there are two issues:

* When `sortable=False` clicking a column header just crashes. This is probably a simple fix, the sort callback just needs to check `sortable` and exit immediately if it is `False`

* sorting is broken when `sortable=True` an has been since 1.3.0. @mattpap I am guessing something in the big 1.3 refactor broke it.

**Comment by bryevdv** [comment]
This diff seems to fix all the issues, and suppresses a resort on data edit when `sortable=False`:
```
diff --git a/bokehjs/src/lib/models/widgets/tables/data_table.ts b/bokehjs/src/lib/models/widgets/tables/data_
index 6bf116a0b..c6a8dc945 100644
--- a/bokehjs/src/lib/models/widgets/tables/data_table.ts
+++ b/bokehjs/src/lib/models/widgets/tables/data_table.ts
@@ -134,14 +134,17 @@ export class DataTableView extends WidgetView {

     // This is obnoxious but there is no better way to programmatically force
     // a re-sort on the existing sorted columns until/if we start using DataView
-    const columns = this.grid.getColumns()
-    const sorters = this.grid.getSortColumns().map((x: any) => ({
-      sortCol: {
-        field: columns[this.grid.getColumnIndex(x.columnId)].field,
-      },
-      sortAsc: x.sortAsc,
-    }))
-    this.data.sort(sorters)
+    if (this.model.sortable) {
+      const columns = this.grid.getColumns()
+      const sorters = this.grid.getSortColumns().map((x: any) => ({
+        sortCol: {
+          field: columns[this.grid.getColumnIndex(x.columnId)].field,
+        },
+        sortAsc: x.sortAsc,
+      }))
+
+        this.data.sort(sorters)
+    }

     this.grid.invalidate()
     this.grid.render()
@@ -236,6 +239,8 @@ export class DataTableView extends WidgetView {
     this.grid = new SlickGrid(this.el, this.data, columns, options)

     this.grid.onSort.subscribe((_event: any, args: any) => {
+      if (!this.model.sortable)
+        return
       columns = args.sortCols
       this.data.sort(columns)
       this.grid.invalidate()
```
Annoyingly though, if you click a header SlickGrid still shows the up/down arrows as if sorting had happened. I am not sure if/how those can be disabled.

**Comment by tony-bony** [comment]
The button callback in the code below shows that despite `sortable = false` all columns have `sortable` attribute set:

```py
from datetime import date
from random import randint

from bokeh.io import show
from bokeh.models import ColumnDataSource, Button, Column, CustomJS
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

data = dict(dates=[date(2014, 3, i+1) for i in range(30)], 
            downloads=[randint(0, 100) for i in range(30)], )

columns = [TableColumn(field="dates", title="Date", formatter=DateFormatter()),
           TableColumn(field="downloads", title="Downloads"), ]

data_table = DataTable(source=ColumnDataSource(data), columns=columns, width=400, height=126, editable=True, disabled=True, sortable=False, reorderable=False, name="TestTable")

button = Button(label='Test')
column = Column(data_table, button)

code = '''
var views = Bokeh.index[column.id].child_views

for (i=0; i<views.length; i++) {
    //console.log(views[i])
    if (views[i].model.name == "TestTable") {
        grid = views[i].grid
        columns = grid.getColumns()
        
        for (j=0; j<columns.length; j++) {
            console.log(columns[j].name, columns[j].sortable)
        }
        
        
        grid.scrollCellIntoView(20, 1)
    }
    else {
        views[i].remove()
    }
}
'''

button.callback = CustomJS(args={'column': column}, code = code)

show(column)
```

Output:
```js
# true
Date true
Downloads true
```

**Comment by bryevdv** [comment]
@tony-bony Columns have their own `sortable` property, perhaps you mean to be setting that? 

https://docs.bokeh.org/en/1.3.4/docs/reference/models/widgets.tables.html#bokeh.models.widgets.tables.TableColumn.sortable

The property on the table allows or disallows sorting in general (or is supposed to) and the individual properties on each column pertain to that column. /

**Comment by tony-bony** [comment]
Yes. The TableColumn `sortable` is set to `true` despite of DataTable `sortable` set to `false`.  So this is a bug, I guess?

**Comment by bryevdv** [comment]
@tony-bony Not in that specific way, no. The two properties are not linked. `sortable=False` on the table should globally disable sorting, but it should not force the table columns to be any different than they are (their `sortable`  values are just (should be) irrelevant  in that case)
