### ISSUE TITLE
[BUG] website showcase url is incorrect

### ISSUE THREAD

**Issue by afonit** [bokeh/bokeh#9268]
on https://bokeh.org
The link under 'User Showcases' for Microscopium, The link to their website goes here (page not found):
https://bokeh.org/github.com/microscopium/microscopium
I am assuming it should be:
https://github.com/microscopium/microscopium

**Comment by afonit** [comment]
I just found the website repo - will close this and oepn it over there.

**Comment by bryevdv** [comment]
Thanks, and sorry for the typo, I put the site together in a hurry and didn't really have anyone else looking over it, so any/all mistakes are mine!

**Comment by bryevdv** [comment]
@afonit I did not want this to get lost in the shuffle I just edited the file in the GH UI directly and it is fixed now. Thanks for the report!
