### ISSUE TITLE
Simplify dependency installation of developer environment setup

### ISSUE THREAD

**Issue by mansenfranzen** [bokeh/bokeh#9280]
Setting up bokeh's developer environment consists of several different steps. The section [Installing dependencies](https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#installing-dependencies) could be simplified into a single command like `python scripts/install_dev_env.py`.

This should work across all operating systems (and shells) while moving the corresponding steps into a separate python file which coordinates the subsequent steps.

**Comment by bryevdv** [comment]
This was recently done, see new shorter instructions at https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#devguide-setup
