### ISSUE TITLE
Error with Selenium/Chromedriver and export_png: chrome not reachable

### ISSUE THREAD

**Issue by p-doyle** [bokeh/bokeh#9290]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
OS: Raspbian Buster
Linux Kernel: 4.19.75-v7+
python: 3.7.3
bokeh: 1.3.4
selenium: 3.141.0
chromium-browser:  74.0.3729.157
chromedriver: 74.0.3729.157

#### Description of expected behavior and the observed behavior
Trying to create a simple line chart and output a png

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
from bokeh.plotting import figure
from bokeh.io import export_png
import numpy as np
from selenium import webdriver

p = figure(plot_width=1200, plot_height=250, x_axis_type='datetime')
df = pd.DataFrame(np.random.randint(0,30,size=10),
                  columns=["value"],
                  index=pd.date_range("20191013", periods=10))
p.line(df.index, df['value'], alpha=1)


options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')

driver = webdriver.Chrome(chrome_options=options)
export_png(p, filename='output.png', webdriver=driver)

```

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "ChartDebugExample.py", line 19, in <module>
    export_png(p, filename='output.png', webdriver=driver, timeout=30)
  File "/usr/local/lib/python3.7/dist-packages/bokeh/io/export.py", line 97, in export_png
    image = get_screenshot_as_png(obj, height=height, width=width, driver=webdriver, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/bokeh/io/export.py", line 225, in get_screenshot_as_png
    wait_until_render_complete(web_driver, timeout)
  File "/usr/local/lib/python3.7/dist-packages/bokeh/io/export.py", line 296, in wait_until_render_complete
    WebDriverWait(driver, timeout, poll_frequency=0.1).until(is_bokeh_loaded)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/usr/local/lib/python3.7/dist-packages/bokeh/io/export.py", line 293, in is_bokeh_loaded
    ''')
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.157 (7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}),platform=Linux 4.19.75-v7+ armv7l)

```
 
I am able to use driver.get to return a webpage so the issue seems to be with bokeh.

**Comment by bryevdv** [comment]
@p-doyle the code above works fine for me (modulo the fact that a correct pixel-ratio is not set) so I am inclined to think this is a local configuration issue of some sort on your end.

**Comment by bryevdv** [comment]
FYI I am using OSX with the same versions of Bokeh, Selenium, and Python,  but ChromeDriver 77.0.3865.40. Given that: 

 * the exception is actually coming from Selenium, not from Bokeh:
    > selenium.common.exceptions.WebDriverException: Message: chrome not reachable

* no one on the core dev team has access to a RasbPi

I am going to close this with `norepro` Some offhand suggestions:

* see if a newer selenium version helps
* see if increasing the `timeout` to `export_png` helps
* see if you can reproduce any issue on a common platform (in which case we could perhaps re-open)
