### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9295]
I would like us to reconsider the base Python version after dropping 2.7 support, and use Python 3.6 instead of 3.5. The benefits of using Python 3.6 are:

* Support for variable type declarations, which are required to get serious with static typing of bokeh's code base. Otherwise we will be able to only statically type APIs, which while being useful on its own (e.g. helping with API backwards compatibility issues), is far from what full program typing would give us.
* `pathlib`, or `PathLike` interface to be specific, support in the standard library. Given that we are introducing breaking changes anyway, it would be good to have proper `pathlib` support in the APIs that use paths.
* `asyncio` support in 3.5 is provisional and 3.6 makes it stable and adds new features (e.g. async generators and comprehensions). Given that there is ongoing work to switch from Tornado's coroutines to `async` and `await`, 3.6 would be a better suited basis for this work.
* `numpy` may be dropping 3.5 soon (see NEP 29, there's an open WIP PR with 3.5 removal).
* Availability of new versions of bokeh's existing or prospective dependencies in the form of conda packages seems limited for 3.5.
* Fewer testing subjects, especially given the recent release of Python 3.8.
* Possibly other more or less important things (e.g. f-strings would be nice to have).

The arguments against this are:

* Python 3.5 is still supported, in security bugfix mode only, until September 2020. This doesn't 
stop numpy's and other developers from considering dropping support early. The fact that Python itself will get bug fixes, doesn't mean that we have to actively develop software for such platform.
* There will be people left behind. This is true, tough I don't know how big impact this would really have. I suppose marginal, but maybe someone has data to prove otherwise. I would prefer to provide improved quality software, for example with static typing, to the majority of our users, than to appease to a minority at the expense of everyone else (both users and developers of this project). At the technical level, upgrading minor Python 3.x versions should be a no-op in most cases. It's nothing like switching from Python 2 to 3. In cases where users can't upgrade due to bad IT culture at companies and institutions, there workarounds like Anaconda Distribution and other tools. If that's too much, then having new shiny features in a visualization library should be really low on one's problem list. There still will be older, perfectly usable versions of bokeh to work with on Python versions not supported anymore. I would consider supporting backporting of critical bugfixes, if feasible.

In the long run, we may want to align development of this project with [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html), though that's a separate concern. Hopefully my views on this subject aren't too radical and this proposal will gather enough support to proceed as outlined.

**Comment by bryevdv** [comment]
cc @bokeh/dev

**Comment by hugovk** [comment]
The Python 3.5 share of downloads from PyPI is fairly small.

Here's the pip installs for bokeh from PyPI for September 2019:

| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  41.06% |   246,823 |
| 3.6      |  27.25% |   163,797 |
| 3.5      |  15.49% |    93,143 |
| 3.7      |  15.06% |    90,507 |
| null     |   0.95% |     5,700 |
| 3.4      |   0.19% |     1,114 |
| 3.8      |   0.01% |        33 |
| 2.6      |   0.00% |         2 |
| 3.3      |   0.00% |         1 |
| Total    |         |   601,120 |

Date range: 2019-09-01 - 2019-09-30

Source: `pip install -U pypistats && pypistats python_minor bokeh --last-month`

The use of `python_requires` (https://github.com/bokeh/bokeh/pull/8996) means for people using 3.5, pip will install the last version of bokeh to support 3.5.

**Comment by jsignell** [comment]
> The use of python_requires (#8996) means for people using 3.5, pip will install the last version of bokeh to support 3.5.

It seems like that might cause lots of bug reports on old versions of bokeh. But I guess if people are diligent about reporting versions when they report bugs it'll be fine.

**Comment by philippjfr** [comment]
I'm strongly in favor and will propose the same thing for other packages I help maintain.

**Comment by jsignell** [comment]
I'm in favor as well, just trying to think if there are any warnings or something that we can use to make it very clear to users that there are more recent versions of bokeh available (just not for their Python version).

**Comment by bryevdv** [comment]
I'm personally mostly ambivalent about this but it seems the tide is turning at least within the context of the "PyData" space. So I'm not inclined to stand in the way. That said I would love to also see September Conda numbers for Bokeh, broken down by version as well. @philippjfr is that something you can try to obtain and report here?

**Comment by jsignell** [comment]
@bryevdv, I can get you those.

**Comment by philippjfr** [comment]
Thanks @jsignell, travelling for the rest of the day.

**Comment by jsignell** [comment]
Here are the numbers: 

| category   |   percents |   downloads |
|:-------------|-----------:|------------:|
| 2.6          | 0.00%     |           0 |
| 2.7          | 14.68%   |       41681 |
| 3.3          | 0.35% |        1003 |
| 3.4          | 0.49% |        1382 |
| 3.5          | 4.15%  |       11791 |
| 3.6          | 38.43%  |      109100 |
| 3.7          | 41.89%   |      118910 |
| 3.8          | 0.00%     |           0 |

More verbose than pypistats. I'm trying to see if we can create a condastats package like that. But for now, this is how I got that table

```python
import pandas as pd
import datetime
import intake

cat = intake.Catalog('https://raw.githubusercontent.com/ContinuumIO/anaconda-package-data/master/catalog/anaconda_package_data.yaml')

today = datetime.date.today()
first = today.replace(day=1)
last_month = first - datetime.timedelta(days=1)
try:
    monthly = cat.anaconda_package_data_by_month(year=last_month.year, month=last_month.month,
                                                 columns=['pkg_name', 'counts', 'pkg_python']).to_dask()
except:
    # if the last month isn't available, get the month before
    month_before = last_month.replace(day=1) - datetime.timedelta(days=1)
    monthly = cat.anaconda_package_data_by_month(year=month_before.year, month=month_before.month,
                                                 columns=['pkg_name', 'counts', 'pkg_python']).to_dask()

bokeh = monthly[monthly['pkg_name'] == 'bokeh'].compute()
tot = bokeh.groupby('pkg_python').counts.sum()
pct = tot / tot.sum()
df = pd.DataFrame({'percents': pct, 'downloads': tot})

df.style.format({
    'percents': '{:,.2%}'.format,
    'downloads': '{:,d}'.format,
})
```

See https://github.com/ContinuumIO/anaconda-package-data for more info

**Comment by jbednar** [comment]
I wonder if there is a way to show this data but only for the _most recent_ Bokeh versions? People using old Python with old Bokeh on old, not updated codebases won't be affected by anything we do now, and I suspect that many of the 4.15% py35 users are also on old Bokeh and thus not relevant to any decision here.

**Comment by jsignell** [comment]
Yeah it seems that the more recent versions aren't getting any py3.5 downloads

**Comment by bryevdv** [comment]
@jsignell thanks for digging in to this! 

Given that we currently seem to have a broad agreement and no strong calls (or any calls) in the other direction, as well as arguments and evidence that supports the decision, I think we can talk about next steps, which I think would be:

* [BEP-5](https://github.com/bokeh/bokeh/wiki/BEP-5:-Python-2-Support-Timeline) needs to be updated including leaving an edit history with a link to this discussion.

* A new issue needs to be made around drafting a BEP-6 for codifying our python version tracking practices (i.e our version of NEP 29)

I guess the only question is whether we want to appeal any harder for additional input first? @birdsarah also relayed her support for this in a personal conversation. So there's a clear majority of @bokeh/core in favor. Are there any other stakeholders in particular we could/should ping? Or even a public call of some sort?

**Comment by jbednar** [comment]
Thanks, @jsignell; that looks quite definitive to me! :-) I don't know of any other stakeholders to involve.

**Comment by bryevdv** [comment]
I have updated BEP-5 so closing this. Would ask that someone else make an issue about BEP-6

**Comment by bryevdv** [comment]
> Thanks, @jsignell; that looks quite definitive to me! :-) 

After thinking about it, I would point out this result is entirely expected since anaconda does not publish new 3.5 packages anymore for Bokeh or anything else. It would be nice to have PyPI breakdown for this if possible (not to change any decision at this point, but it would be good to know)

**Comment by jbednar** [comment]
Ah, good point. :)

**Comment by quasiben** [comment]
It looks like pypi (for bokeh at least) only shows splits between 2 and 3 but not download stats between 3.5, 3.6, etc

https://pypistats.org/packages/bokeh

**Comment by Karel-van-de-Plassche** [comment]
Looks you can query the API for that though: https://pypistats.org/api/#api-packages-package-python_minor

**Comment by bryevdv** [comment]
> It looks like pypi (for bokeh at least) only shows splits between 2 and 3 but not download stats between 3.5, 3.6, etc

Don't the third and fourth to last charts show that?

**Comment by quasiben** [comment]
Ooops, didn't scroll down far enough

**Comment by hugovk** [comment]
> Looks you can query the API for that though: [pypistats.org/api/#api-packages-package-python_minor](https://pypistats.org/api/#api-packages-package-python_minor)

Yep, the stats in https://github.com/bokeh/bokeh/issues/9295#issuecomment-543526422 are from the `pypistats` CLI, which uses the pypistats.org API.

**Comment by bryevdv** [comment]
Reviving this discussion, I'd like propose something that is simple or reactive or both, i.e.:

* We will guarantee to support the three latest minor versions of Python, measured from 6 months after the latest minor release  (to allow the later release some time for adoption), or 
* We will follow NEP 29
