### ISSUE TITLE
[FEATURE] Provide mouse press up event

### ISSUE THREAD

**Issue by ethan-nelson** [bokeh/bokeh#9298]
bokeh provides the option to capture many mouse event types from plots in the browser, taking advantage of the [HammerJS](https://hammerjs.github.io/) library. In particular, bokehjs passes events like Tap, Press, and Pan on to the python backend (see demonstration in bokeh documentation [here](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-user-interaction-events)).

When a user long presses or holds their mouse button for longer than 0.251 seconds, a [press event](https://hammerjs.github.io/recognizer-press/) is activated in HammerJS and picked up by bokehjs. However, the corresponding mouse release, or "press up" is not picked up by bokehjs. It is still activated in HammerJS though (again see [here](https://hammerjs.github.io/recognizer-press/) for the `pressup` event).

A "press up" event can be added by extending the events bokehjs captures that are already available from HammerJS. To that end, I have a feature branch that accomplishes this if a PR is welcomed.

**Comment by bryevdv** [comment]
@ethan-nelson If it can be added in a straightforward, non-disruptive manner (sounds like?) then I wouldn't have any issues around adding a new event. I'd suggest submitting the PR so we can review the actual code and go from there

**Comment by ethan-nelson** [comment]
Great! Yes, just a few minor additions--PR coming soon.
