### ISSUE TITLE
[FEATURE] Scientific notation for NumberFormatter

### ISSUE THREAD

**Issue by harmbuisman** [bokeh/bokeh#9304]
### FOLLOW THESE INSTRUCTIONS CAREFULLY
NumberFormatter(format="0.[00]") allows me to set the number of decimals for a number to 2. I use this to format my cells in a DataTable.

But if I have very small numbers with a variable number of 0's, e.g. in the case of P-values, I only see 0's.

If I use no formatter for a column I get:
![image](https://user-images.githubusercontent.com/7702207/67021109-744c6080-f0ff-11e9-9ad3-905cc18d113e.png)

But what I would like to have is to have this scientific notation + be able how many significant numbers are shown. I have not succeeded in getting that to work and the documentation does not mention such a use case.

**Describe the solution you'd like**
have the option use_scientific also for NumberFormatter
if this is passed, then only the part outside of the exponent is formatted using formatting rules.
NumberFormatter(format="0.[00]", use_scientific=True) should give something like 1.62e-10 rather than 1.6234252343e-10

Also an update to the docs is needed. 

**Describe alternatives you've considered**
My alternative would be converting to a string and show the string, but this breaks sorting
I tried basictickformatter which has use_scientific, but that doesn't work, besides that, I am not sure if you can set the # of decimals

**Comment by bryevdv** [comment]
I think we would need to make a new `CellFormatter` subclass. If we just add some flag `use_scientific` to `NumberFormatter` then it become possible for users to pass combinations of parameters that don't make sense together, and that is an invitation for support issues. 

Alternatively, if there is a new format string that is easily and completely distinguishable from any of the existing Numbro formats that can be tested for in a simple way, then we could go that route. 

@harmbuisman This is a nice self-contained task that would be ideally suited for a new contributor. Would you be interested in working up a PR with some guidance/help?

**Comment by harmbuisman** [comment]
@bryevdv, yes, I can give it a try. What is the best/preferred channel in case I need help?

**Comment by bryevdv** [comment]
closed by #9319
