### ISSUE TITLE
[BUG] Documentation panels empty

### ISSUE THREAD

**Issue by xavArtley** [bokeh/bokeh#9309]
Hello,

I was looking for documentation on Tabs and I went to the page :

https://docs.bokeh.org/en/latest/docs/reference/models/widgets.panels.html
However it display a blank page :
![image](https://user-images.githubusercontent.com/18531147/67140166-fcde1480-f257-11e9-9c5a-a0bd3bbe2ad7.png)

The last time the page was ot empty was on:

https://docs.bokeh.org/en/1.0.4/docs/reference/models/widgets.panels.html

**Comment by xavArtley** [comment]
I suppose it's because Panel and Tabs where moved from models.widgets.panels into models.layout and none of the __all__ variable reference it.
I can make a PR however I don't know what is the recommanded way to correct it.
Remove the panels.rst and add Panels and Tabs to the `__all__` of layout.py.
Or just add the __all__ varible in panels.py

**Comment by mattpap** [comment]
> Remove the `panels.rst` and add `Panel` and `Tab` to the` __all__` of layout.py.

That's the correct approach.

**Comment by bryevdv** [comment]
Just passing FYI starting very soon I want to revamp all examples and docs to only ever import from `bokeh.models` and not from the sub-modules. That should be the single public API location
