### ISSUE TITLE
[BUG] Bokeh rendering performance

### ISSUE THREAD

**Issue by mdah90** [bokeh/bokeh#9320]
Hi ,
Description:
i created a bokeh application for data annalysis, my application include also bokeh buttons, Divs .... that will give the user the ability to control the generated graphs.
however i found out that there is a performance issue in the rendering caused mainly by many calls to  getboundingclientrect from bokeh module.

i have created  a dummy application that will help reproducing the issue.
in the application you can click the add div button and you will see it will take ~3 seconds to add the div.
in my real applications the issue is worst since some small updates in the layout will take ~12 seconds.
attached python script with the dummy application and screen snapshots for the initial performance analysis done from chrome.
the issue also exists when running from jupyter notebook on linux.

Software version info:
Python 3.7
Bokeh 1.3.4
google chrome: Version 77.0.3865.120
OS: windows 10

![getBoundingClientRect](https://user-images.githubusercontent.com/56922069/67402409-38ab0e00-f5b9-11e9-9497-8837b1cc538e.PNG)
![profiling_summary](https://user-images.githubusercontent.com/56922069/67402410-3943a480-f5b9-11e9-9c3e-e15c74fe9c7d.PNG)

[bokeh_app.zip](https://github.com/bokeh/bokeh/files/3762809/bokeh_app.zip)

**Comment by bryevdv** [comment]
Hi @mdah90 When I run that code locally on OSX, I would say that it performs at a level that seems acceptable (e.g. ~1s load and response when "Add Div" is pressed). It's possible there is an issue specific to windows. It would require more investigation, and an ability to reproduce, to be sure. 

That said, I should be clear that the use case illustrated by your code, with nearly 400 DOM layout objects, is not really one that Bokeh explicitly sets out to cater to. Bokeh is much better suited (and explicitly designed for) cases with far DOM objects, but potentially much larger data sources (e.g. to drive plots). So I am not sure whether we will able to address your concerns or not. 

cc @mattpap

**Comment by mattpap** [comment]
> with nearly 400 DOM layout objects, is not really one that Bokeh explicitly sets out to cater to.

The layout wasn't designed to handle that many "foreign" elements. However, with growing need for integration of bokeh's layouts with other systems (e.g. jupyer widgets), this will have to be revisited and improved in near future.

**Comment by bryevdv** [comment]
I wonder if there is not a way to relinquish layout costs for people who care primarily about the JS/python synchronization, and would be happy to just let the browser do whatever it wants to do with a pile of DOM content.

**Comment by gshklover** [comment]
Is there a suggested method/workaround to switch to browser-controlled layout?

**Comment by bryevdv** [comment]
Not at present, that was merely a speculation about possible future development.

**Comment by mdah90** [comment]
Thank you guys i will try it and update when i have more results.
i think that improvement for the bokeh layout performance will enable fast development of UI 'mini' application, for me mainly used to configure the data that should be used to generate the plots.
