### ISSUE TITLE
x_range option not available from bokehJS (linked ranges)

### ISSUE THREAD

**Issue by PBrockmann** [bokeh/bokeh#9322]
Tested with last 1.3.4 release.

In pyhton
```
xdr = DataRange1d(bounds=None)
p1 = figure(
        plot_width = 400,
        plot_height = 400,
        tools = "pan,wheel_zoom,box_zoom,reset,save",
        toolbar_location = "above",
        active_scroll = "wheel_zoom",
        x_range = xdr
)
```
I try to minic the previous part of python code to BokehJS, but I get the error:
```Uncaught Error: models must be owned by only a single document```

In JS
```
var xdr = new Bokeh.DataRange1d({bounds: "none"});
plot = new Bokeh.Plotting.figure({
          plot_width: 400,
          plot_height: 400,
          tools: "pan,wheel_zoom,box_zoom,reset,save",
          //active_scroll:  "wheel_zoom",           // not available as well
          x_range: xdr
});
```
More generally, I would like to produce linked plot from BokehJS.
Any working example ?

**Comment by bryevdv** [comment]
Hi @PBrockmann That particular message always illustrates a usage problem. Please head over to the Project Discourse to discuss support type questions. https://discourse.bokeh.org
