### ISSUE TITLE
[BUG] Background property change not  working for WidgetBox

### ISSUE THREAD

**Issue by xavArtley** [bokeh/bokeh#9324]
Here is a MRE:

```python
from bokeh.io import show, output_notebook, push_notebook
from bokeh.models import Div, CustomJS, ColorPicker, Column, WidgetBox, Row, Slider
output_notebook()

d = Div(background='black', width=300, height=300)
s = Slider(start=0, end=1)
w = WidgetBox(children=[s], background='black', width=300, height=300)
c = ColorPicker()

c.js_on_change('color', CustomJS(args=dict(d=d, w=w),code="d.background=this.color; w.background=this.color;"))
show(Column(Row(d,w),c))
```

![ezgif com-video-to-gif (15)](https://user-images.githubusercontent.com/18531147/67466202-f3352200-f646-11e9-8f69-d1720a749716.gif)

The Div element color change but not the WidgetBox.
This is due to the fact that background change invalidate layout but as the dimensions of the layout are not modified nothing happened.
https://github.com/bokeh/bokeh/blob/069a7a9aeb8c63115f00f8e03739fe466270fb8f/bokehjs/src/lib/models/layouts/layout_dom.ts#L75-L86

The color of the div element change because it inherit from MarkupView which connect all changes to a render call
https://github.com/bokeh/bokeh/blob/069a7a9aeb8c63115f00f8e03739fe466270fb8f/bokehjs/src/lib/models/widgets/markup.ts#L13-L19

I think backgroud should invalidate the render and not the layout since the background is applied in the render method:
https://github.com/bokeh/bokeh/blob/069a7a9aeb8c63115f00f8e03739fe466270fb8f/bokehjs/src/lib/models/layouts/layout_dom.ts#L86-L89

If this is the correct correction I'll be happy to make a PR

**Comment by bryevdv** [comment]
@xavArtley offhand that seems reasonable, I would say if a small change like that fixes then please submit a PR and we can discuss any further details on the PR
