### ISSUE TITLE
[FEATURE] "Open in new tab"-tool

### ISSUE THREAD

**Issue by BenPortner** [bokeh/bokeh#9326]
### feature description
I use bokeh to embeded plots in Rmarkdown and jupyter notebooks because I love the interactivity. However, depending on the widths of window and layout, plots can turn out rather small. I thought it would be helpful to have a button in the bokeh toolbar that opens the plot in a separate browser tab in fullscreen mode. This way users can engage in data exploration more easily.

### alternatives considered
It would be easy to add a separate html button with the same functionality somewhere close to the plot. However, this would be less nice-looking. Also, it is more user-friendly if all actions concerning the plot can be chosen from the same toolbar.

**Comment by bryevdv** [comment]
@BenPortner Have you considered a `CustomAction`? That would let you put a button on the toolbar that executes a snippet of JS code. Would that satisfy your need? If so I might suggest this could better be added as an example in the docs.

**Comment by BenPortner** [comment]
@bryevdv thanks for your answer! I didn't know there was such a thing as `CustomAction`. I had a look at [this example](https://docs.bokeh.org/en/latest/docs/user_guide/extensions_gallery/tool.html) but to be honest, I don't understand what is going on there. Writing a JS script that opens the plot in a new tab should be easy but so far I have no idea how to add the button to the toolbar.

**Comment by bryevdv** [comment]
@BenPortner That example is for an entire full Custom Extension, which is far more involved. See:

https://docs.bokeh.org/en/latest/docs/reference/models/tools.html#bokeh.models.tools.CustomAction

Basically:
```
tool = CustomAction(icon="icon.png",
                    callback=CustomJS(code='alert("foo")'))

plot.add_tools(tool)
```

**Comment by BenPortner** [comment]
Very nice! I got it to work. Thanks a lot for your help @bryevdv !

Code snippet:

```python
import bokeh.plotting
import bokeh.models

parent_file = "foo_parent.html"
bokeh_file = "foo.html"

# create custom tool
newTool = bokeh.models.CustomAction(
    icon="icon.png",
    callback=bokeh.models.CustomJS(code="window.open('"+bokeh_file+"')")
)

# make plot with custom tool in toolbar
f = bokeh.plotting.figure(tools=[newTool])
f.line(x=[0,1], y=[0,1])

# export plot as html
bokeh.plotting.output_file(bokeh_file)

# write parent file with too small embedded bokeh plot
html = "<html><head></head><body><embed src="+bokeh_file+" style='width:10%;'></embed></body></html>"
file = open(parent_file,"w")
file.write(html)
file.close()
```

**Comment by bryevdv** [comment]
@BenPortner awesome! I am going to go ahead and close this with `noaction` since I don't think we need to consider adding anything to the library at this point.

**Comment by bryevdv** [comment]
FYI I would only note that a slightly more sophisticated approach would be to not rely on a separate HTML file but to literally generate new HTML that embeds the Bokeh JSON. I think that's do-able but don't have the time to investigate ay present.

**Comment by BenPortner** [comment]
Not sure I understand correctly. You mean `foo_parent.html` should contain all the bokeh code and upon clicking the custom button, a html document will be created dynamically instead of opening `foo.html`? Sounds interesting. Can you explain to a noob like me why it is better?

**Comment by bryevdv** [comment]
I mean Bokeh documents have JSON representation and there are JS functions to embed that JSON in HTML documents, so the cleanest solution would extract the existing JSON representation of the plot or object in question and open a new document based off a template that embeds that JSON.
