### ISSUE TITLE
Document bokeh.sampledata

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9329]
The Reference Guide page is nearly empty. The `bokeh.sampledata` module should automatically include relevant submodules in its main docsring, and all the submodule docstrings should be updated/completed to be useful, e.g. explain what the module contains, or show example data, or link/include examples that use the data.

**Comment by bryevdv** [comment]
The simplest/quickest solution:

* Add docstrings with a common/similar format to all the sample data modules. 
* manually add `automodule` sphinx directives to the top level module docstring

If we wanted to go for a little more automated approach, then  the second step could be:

* create a `:bokeh-sampledata:` directive that scans the `bokeh/sampledata` directory for all relevant submodules and adds `automodule` directives atomatically for them.

**Comment by Tekaichi** [comment]
The simplest/quickest solution would be adding something like the following for each .py in the sampledata folder ?
Should I also add the files inside _data?
```
bokeh.sampledata.airports
.. automodule:: bokeh.sampledata.airports
   :members:
```
Right now, I'm just going for the first solution but would like to explore the second one later.

**Comment by bryevdv** [comment]
@Tekaichi All of the files in `_data` are accessed via one of the Python modules in `bokeh.sampledata`, so I think it suffices to just add the docstrings to the modules. Just to be clear up front: the bulk of the work here is adding all the docstrings. Ideally each data docstring should describe the format of the data variables in the module, provide provenance information (where known), have some sample snippets showing how to work with the data, and if possible link to relevant examples.
