### ISSUE TITLE
Deprecate WidgetBox

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9334]
Propose to deprecate `WidgetBox` at 2.0 and also to simply have it return `Column` instances at that time. 

cc @mattpap

**Comment by bryevdv** [comment]
FYI I have removed all usage of `widgetbox` in the repo and examples as of 1.4

**Comment by bryevdv** [comment]
no feedback but this seems uncontroversial so marking as `task`

**Comment by mattpap** [comment]
I overlooked this. Sure, `WidgetBox` is already a `Column`, so apart from name, there will be no breakage.
