### ISSUE TITLE
[BUG] NumeralTickFormatter format="0a" generates wrong -1k tick on "extra" y axis

### ISSUE THREAD

**Issue by zelenij** [bokeh/bokeh#9337]
I have a relatively straightforward graph, which uses NumeralTickFormatter(format="0a"):

```
        num_formatter = NumeralTickFormatter(format="0a")
        plot = figure(x_axis_type="datetime",
                      title=_("Assets change over time"),
                      sizing_mode='stretch_both')
        plot.grid.grid_line_alpha = 0.3
        plot.xaxis.axis_label = 'Date'
        plot.yaxis.axis_label = 'Total value'
        plot.yaxis.formatter = num_formatter

        plot.line(dates_from_totals,
                  totals,
                  color='#A6CEE3',
                  legend='Totals')
        plot.extra_y_ranges = {"extra_data": Range1d(start=np.min(extra_data), end=np.max(extra_data))}
        plot.add_layout(LinearAxis(y_range_name="extra_data", axis_label="Extra total", formatter=num_formatter), 'right')
        plot.line(dates_from_totals,
                  extra_data,
                  color='blue',
                  y_range_name='extra_data',
                  legend="Extra total")
        plot.legend.location = "top_left"
        self.charts.append(components(plot))

```

All works well, however the lowest tick on the right y axis is -1k, while I was expecting it to be -2k (the smallest value in my data set is -1,693.26).  I don't see any JavaScript issues in the console, nor are there any python errors.  See image:

![sample](https://user-images.githubusercontent.com/5512551/67789786-247a7b80-faa7-11e9-94f7-ca512c0a8b3f.png)

**Comment by bryevdv** [comment]
@zelenij offhand I imagine this is a rounding issue of some sort. However, we cannot investigate something we cannot reproduce. Can you provide a *complete* script to reproduce?

**Comment by zelenij** [comment]
OK, I figured this out - not a but, but my misunderstanding.

The second "-1k" tick is at -1500 mark actually.  Since I didn't specify the format to include fractions, it looks the same as -1000 tick.  I now switched to the "0.0a" and the y axis ticks look as expected.  This can be closed.
