### ISSUE TITLE
 Aggregate and Chart in One Shot ala Excel Pivot Charts

### ISSUE THREAD

**Issue by aschneiderman** [bokeh/bokeh#934]
When users want to create a bar graph, scatter chart, etc.,  they frequently need to aggregate the data. Right now it's a two-step process: aggregate the data via aggregate or pivot_table, then create a chart. It would be great if you could do it in one shot ala Excel Pivot Charts. For example:

Scatter(products, x='Year', y='Product Type', function='count')
or
Scatter(products, x='Year', y='Product Type', function='sum', aggregate_field='Revenue')

Although you could trick out this feature to handle much more complex cases, I wouldn't bother – the vast majority of the time users only need to do a simple aggregation.

A suggestion from one of my colleagues on choosing a name for the parameter specifying which function to use to aggregate the data:

> I would personally suggest something like “Function”, “Perform” or “Calculate”. When you think about how this would be spoken, you’d say 
> - I want to run the sum function on flowers
> - I want to calculate the sum of flowers
> - I want to perform the sum operation on flowers

**Comment by rothnic** [comment]
I think there is some cleanup needed, but the example should now be possible with charts. An aggregation type is exposed via things like bar chart, but also you can use the binning specification to summarize the data going into any chart, though we need to add examples/testing across them all.

Any dimension to a chart should accept the result of the [bins](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/stats.py#L379) function. See the [heatmap chart examples](https://github.com/bokeh/bokeh/blob/master/examples/charts/file/heatmap.py) where this is primarily being used.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/38)
