### ISSUE TITLE
Archive release artifacts 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9341]
As a first step after successfully building everything, the "build and upload" script should send everything to an archive S3 bucket. If this fails then the build is aborted before any non-reversible uploads happen. If a later upload fails, e.g. because an access token expired, they it can be retried manually with the artifact that was archived to try and salvage the release.

**Comment by bryevdv** [comment]
Thoughts on all the steps for build and publish

# Steps

## Build
 
All of these steps are re-doable/un-doable

* clone repo
* verify repo state
* check out release branch
* update version numbers
* build BokehJS
* update SRI hash manifest
* update changelog
* build python packages
* build NPM packages
* build docs
* confirm changes (?)
* upload build artifacts to S3 staging
* upload BokehJS to CDN 
* commit changes
* merge branch
* tag version
* push to github

## Test

At this stage, the staged packages are locally installable and testable, but no irreversible steps have been taken. e.g. BokehJS is uploaded to CDN, but if necessary, can be removed  manually if the release needs to be aborted.

* install conda pacakge
* run `verify_sri_hashes`
* install pip package
* run `verify_sri_hashes`
* other smoke/unit tests?

## Publish

Most of the following steps are irreversible

* verify all secret credentials
* publish docs to CDN
* publish conda package to anaconda.org
* publish pip package to pypi 
* publish NPM package

# Options

How should this be split up CI vs non-CI? Generally want everything automated via scripts but do we continue to run any or all of this on CI, or some steps locally? What CI system?

**Comment by bryevdv** [comment]
Seems like GH Deployments might be a good option for "where does this live" They can be triggered via API (e.g. a curl call) so and GH can hold the necessary secrets. As long as we can get separate build/publish workflows I think it would be a nice option.

**Comment by bryevdv** [comment]
Since 2.0 will be released by hand, actually re-building the automation is a post-2.0 task, so moving this to `next`

**Comment by bryevdv** [comment]
@mattpap what of this can we exclude in the build sdists? our sdist is 37M which is not really reasonable
```
104K	bokeh/server/static/js/bokeh-api.js
112K	bokeh/server/static/js/bokeh-api.js.map
68K	bokeh/server/static/js/bokeh-api.min.js
112K	bokeh/server/static/js/bokeh-gl.js
124K	bokeh/server/static/js/bokeh-gl.js.map
64K	bokeh/server/static/js/bokeh-gl.min.js
792K	bokeh/server/static/js/bokeh-tables.js
896K	bokeh/server/static/js/bokeh-tables.js.map
252K	bokeh/server/static/js/bokeh-tables.min.js
616K	bokeh/server/static/js/bokeh-widgets.js
684K	bokeh/server/static/js/bokeh-widgets.js.map
244K	bokeh/server/static/js/bokeh-widgets.min.js
1.6M	bokeh/server/static/js/bokeh.js
1.8M	bokeh/server/static/js/bokeh.js.map
9.2M	bokeh/server/static/js/bokeh.json
664K	bokeh/server/static/js/bokeh.min.js
200K	bokeh/server/static/js/compiler
17M	bokeh/server/static/js/compiler.js
19M	bokeh/server/static/js/compiler.js.map
50M	bokeh/server/static/js/compiler.json
20M	bokeh/server/static/js/legacy
4.6M	bokeh/server/static/js/lib
1.7M	bokeh/server/static/js/types
```

**Comment by mattpap** [comment]
You can start by removing all `*.json` files and `compiler.js.map`. That will save a lot. Other `*.map` files could be removed as well. Having non-minified resources in a package is of dubious value in general, though we support this in resources. Compiler's stuff could be factored out into separate library or made downloadable on demand, similarly to sample data.

**Comment by bryevdv** [comment]
Plan to have full automation working for 2.3. Most everything is done up to some triggerable GH Action that actually runs the code. Also need to decide where deployment tarballs archived to. S3 is one option but the are quite big so maybe only store full releases.

**Comment by bryevdv** [comment]
This is done
