### ISSUE TITLE
Change button_type doesn't work

### ISSUE THREAD

**Issue by ShanshanBi** [bokeh/bokeh#9345]
I called the callback function when clicking button. The code is shown below. But the button_type didn't work for me. 

 def retrain_limits():
        retrain_button.button_type = 'warning'
        mill = mill_dropdown.value
        if mill in av_mills[1:]:
            notif.text = "Retraining limits for {}...".format(mill)
            ds.identify_limits(mill)
            # need to update ooc and zscore, otherwise the bar chart will not be updated
            ds.calculate_ooc_full(mill)
            ds.calculate_zscore_full(mill)
            notif.text = "Data has been updated, you're good to go..."
        else:
            notif.text = "Please select a mill first..."
        #####
        retrain_button.button_type = 'primary'

version:
Name: bokeh
Version: 1.0.4

python 3.7
anaconda3 03/2019

**Comment by bryevdv** [comment]
Please provide all the information that was asked for in the issue template, versions, etc.

**Comment by ShanshanBi** [comment]
> Please provide all the information that was asked for in the issue template, versions, etc.

The version info has been included. Thanks.

**Comment by bryevdv** [comment]
Please try with the latest version 1.3.4 as this may already be fixed

**Comment by bryevdv** [comment]
@ShanshanBi Will you be able to:

* provide a complete minimal reproducing script that others can run in order to investigate?
* report back on the lastest version 1.4?

**Comment by bryevdv** [comment]
Closing for lack of full information. We can certainly re-open if the required details are provided.
