### ISSUE TITLE
[BUG] bokeh server stops updating plots in browser after approx. 1 second of work

### ISSUE THREAD

**Issue by Felix-neko** [bokeh/bokeh#9359]
#### Problem description

I'm trying to make bokeh update plot in browser without reopening any new browser tabs. To do it, I've run `bokeh serve` and connected to it via `pull_session` from Python code. I'm creating the plots and try to update them, and it even starts to update --- but after approximately 1 second of work the plots in browser stop to update. There is no error message, and the session is still alive, but nothing happens in my browser.

Can you please help me?

#### Software Versions: 
- bokeh: 1.3.4
- OS: Windows 7x64
- browser: Google Chrome
- Python: 3.7x64

#### Code example:
```
import time

from bokeh.plotting import figure
from bokeh.client import pull_session
from bokeh.models import ColumnDataSource

# Please run "bokeh serve" in console before start!

session = pull_session()

x_array = []
y_array = []

datasource = ColumnDataSource(data={"x": x_array, "y": y_array})

fig = figure(title=("Total TBS (in bits) for %s"), plot_height=300, plot_width=800)

line = fig.line(x="x", y="y", source=datasource, line_width=2, legend=("Super dooper line from hell"))

session.show(fig)

for i in range(10000):

    # Plot on the screen stops updating after 1 second. What am I doing wrong?
    x_array.append(len(x_array))
    y_array.append(x_array[-1] ** 2)
    datasource.data = {"x": x_array, "y": y_array}


    print(i)
```

**Comment by bryevdv** [comment]
@Felix-neko This kind of usage, trying to push to a bokeh server from a separate python process, is explicitly and unequivocally **dis**-encouraged. It is an anti-pattern with Bokeh, and nothing we intend as standard usage. The only use we demonstrate or document `pull_session` for is to make one-off, initial customizations to a session before embedding it an a template of some sort and serving the result to a user.   At this point I would go so far as to say anything else is unsupported and out of scope.
