### ISSUE TITLE
[FEATURE] No color change or flicker when panning on docs site.

### ISSUE THREAD

**Issue by matt-erhart** [bokeh/bokeh#9360]
**Is your feature request related to a problem? Please describe.**
Plots flicker/change color on pan on the docs website. 

**Describe the solution you'd like**
No color change or flicker. 

**Describe alternatives you've considered**
Use another lib. Main reason I haven't tried bokeh outside of the docs site as it seems janky. Might be holding bokeh back. 

**Additional context**
![m4JX4Nnfkm](https://user-images.githubusercontent.com/3199847/68094299-c3aac480-fe53-11e9-951b-3929bcccb1aa.gif)

**Comment by bryevdv** [comment]
This is an intended feature, which you can adjust or turn off if you like. See:

https://docs.bokeh.org/en/1.3.4/docs/user_guide/tools.html#controlling-level-of-detail
