### ISSUE TITLE
Pan tools broken on mobile

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9361]
Ref: https://stackoverflow.com/questions/58675210/moving-plot-bokeh-tools

Looking at docs pages on my phone, this appears to have been broken since 1.2

cc @mattpap

**Comment by mattpap** [comment]
@bryevdv, which browser/platform? I suppose this is a duplicate of issue #9187.

**Comment by bryevdv** [comment]
yup this a dupe
