### ISSUE TITLE
Toolbox css style in notebook

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#937]
Sometimes, after a while working in the notebook, the toolbox, looks like this:

![screen shot 2014-07-31 at 2 02 38 pm](https://cloud.githubusercontent.com/assets/4940549/3769975/842f3e16-18e5-11e4-9599-f1d8de16e740.png)

 I'm not sure how to reproduce the issue, it just happens sometimes to me. I'll give more details if I find a common pattern when this happens.

**Comment by bryevdv** [comment]
FWIW I see this flash by occasionally. I have no way of reproducing, though. Possibly upstream issue?

**Comment by damianavila** [comment]
maybe upstream, but I did not see this since a lot of time... maybe because I use IPython master most of the time...
