### ISSUE TITLE
User authentication hooks NOT provided (default user enabled)

### ISSUE THREAD

**Issue by GitProfAn** [bokeh/bokeh#9371]
Hello,
After applying «bokeh serve» command I receive two messages:
Starting Bokeh server version 1.4.0 (running on Tornado 6.0.3)
User authentication hooks NOT provided (default user enabled)

OS Win 8.1

Pls. help me to fix the problem
Regards

![report](https://user-images.githubusercontent.com/48450635/68183306-164bc400-ffad-11e9-9600-777532f16c4a.png)

**Comment by mattpap** [comment]
This is correct. By default there is no authentication set up. See [server documentation](http://docs.bokeh.org/en/latest/docs/reference/command/subcommands/serve.html?highlight=authentication#authentication-options) for details. Also, please ask further usage questions at https://discourse.bokeh.org/.

**Comment by bryevdv** [comment]
I'll add: that ERROR line is for something that follows the auth hook message (which is merely informational, and not an error) but you have not included whatever follows. However as suggested the appropriate place to start is the community Discourse.

**Comment by MohammedSalman** [comment]
The same thing just happened to me. I just had to remove the last line I added which was an import for a function from another file and now I got it fixed.

**Comment by sdc50** [comment]
I know this is a closed issue, but I think there may actually be a bug here. While I cannot reproduce the error on my system (OSX) I have two teammates that are running Windows 10 that both get this same behavior. 

> but you have not included whatever follows

In our case there is no information after the "ERROR:" message; it simply hangs.

This behavior is only happening with Bokeh 1.4.0 on Windows. Reverting to 1.3.4 allows the server to startup without issue.

**Comment by bryevdv** [comment]
@sdc50 We can't investigate something we can't repro. Please open a new issue with anything that might help reproduce this to investigate.

**Comment by bryevdv** [comment]
@sdc50 @MohammedSalman I just tried the provided example at 

https://github.com/bokeh/bokeh/tree/master/examples/howto/server_auth

On Win 10 with Bokeh 1.4.0 and it worked as expected. So we would definitely need a complete reproducer to test with.

**Comment by GitProfAn** [comment]
Thank you guys!
I have finished my tests with this issue and had no positive results but probably the next time I should start using OS Win 10 (in my case it was Win 8.1).

Regards

**Comment by sdc50** [comment]
> we would definitely need a complete reproducer to test with.

Of course. I'll work with my teammates to come up with a minimum reproducible example.

**Comment by bryevdv** [comment]
> I have finished my tests with this issue and had no positive results

I'm not sure what this means. You were unsuccessful at resolving the issue? Or unsuccessful at making a reproducer for the issue?

**Comment by GitProfAn** [comment]
I could not solve my problem and stopped my attempts. I was unsuccessful at resolving the issue.

I just played with this feature and did not need it for my work.

If you need my assistance in re-producing the error, I faced earlier – just let me know. I will try to help you.

Probably some other guys will need this frame-work exactly on OS Win 8.1.

**Comment by GitProfAn** [comment]
just put the log here

![log](https://user-images.githubusercontent.com/48450635/70168841-b6932680-16da-11ea-92db-f215fb6535b8.jpg)

**Comment by bryevdv** [comment]
@GitProfAn thanks for clarifying. 

I definitely don't have easy access to any Win 8 machine or VM. I guess the next thing that would be good for anyone to try who has the time: does the example in the repo also fail for you? Tying to identify if this is a general problem or something specific to your systems or code.

**Comment by sdc50** [comment]
> Please open a new issue with anything that might help reproduce this to investigate (i.e. a full example code to run on windows)

I was able to reproduce the problem with an example from the repo. It looks like it's an issue with the Python 3.8 build on Windows. See #9507
