### ISSUE TITLE
bokeh-server support for multiple users/instances?

### ISSUE THREAD

**Issue by samchrisinger** [bokeh/bokeh#938]
Is there any support via the bokeh-server to allow serving many instances of the same visualization? 

Right now I have a Flask app that spawns a new thread every time a certain endpoint is hit. While this works it leaves quite a lot be be desired-- in particular I have no reliable way to know when it's safe to kill one of those threads. 

Alternatively is there a way to listen for when a bokeh session gets closed (i.e. when the the user leaves the page, or when the websocket connection is closed)? I'm wondering browsers' websocket APIs will automatically close websockect connections if a user leaves a page, and if perhaps this could serve as a reliable signal for killing app instances.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
