### ISSUE TITLE
[BUG] - Tick & axis labels cut off in embedded plots in Chrome/Chromium browsers

### ISSUE THREAD

**Issue by Tommos0** [bokeh/bokeh#9387]
In some situations, axis & tick labels are cut off in Chromium based browsers.

E.g. normally you'd expect this:
![image](https://user-images.githubusercontent.com/9217533/68400479-688d1080-0178-11ea-8769-e88a3dc76fc1.png)

But sometimes several things are cut off and I'm getting this:
![image](https://user-images.githubusercontent.com/9217533/68400633-a5f19e00-0178-11ea-9c9a-0e974e961775.png)

Now, this effect is a bit hard to reproduce. As an example I've setup a repl.it:
https://repl.it/@Tommos0/bokehbugchromeexample

Using Chrome, the preview will show the broken version, with things cut off. However, when the plot is not served from an iframe (e.g. by opening https://bokehbugchromeexample.tommos0.repl.co/), things appear to be fine.

Using Firefox, there is never any problem at all.

My actual situation is some plots being served in a Flask app, and it is similarly broken as what is shown in the repl.it preview. This happens for all the plots in my app. I'm using a sort off workaround by using `min_border` as in:
```python
plot.min_border_left = 100
plot.min_border_top = 100
plot.min_border_bottom = 100
```
This fixes most things, but it's hacky and not responsive.

I'm getting this effect on:
- Debian/testing
- Brave browser Version 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)
- Google Chrome Version 78.0.3904.87 (Official Build) (64-bit)
- With bokeh 1.3.4 & 1.4.0 (everything was fine before I updated bokeh from version 0.12.13)
- Python 3.7

Code used to serve and plot (same as what is on the `repl.it`):

```python
from bokeh.plotting import figure
from bokeh.embed import components
from http.server import BaseHTTPRequestHandler, HTTPServer

def simple_plot(with_border=False):
  x = [1, 2, 3, 4, 5]
  y = [6, 7, 2, 4, 5]
  p = figure(
    title="simple line example", 
    x_axis_label='x', 
    y_axis_label='y',
    plot_width=300,
    plot_height=300,
  )
  p.line(
    x,
    y,
    legend_label="Line height.",
    line_width=2
  )
  if with_border:
    p.min_border_left = 100
    p.min_border_top = 20
    p.min_border_bottom = 50
  return p


class myHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        script, div = components(simple_plot('border' in self.path))
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        response = f"""
<html>
<head>
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-1.4.0.js"></script>
</head>
<body>
  {div}
  {script}
</body>
</html>
        """
        self.wfile.write(response.encode('ascii'))

try:
    server = HTTPServer(('', 8080), myHandler)
    server.serve_forever()

except KeyboardInterrupt:
    server.socket.close()

```

**Comment by bryevdv** [comment]
Unfortunately I have been unable to reproduce any issue either locally with with Python 3.7, Chrome 78.0.3904.70 and Bokeh 1.4, or with your link, despite reloaded both many dozens of times. Are there any JS console messages when this occurs?

**Comment by Tommos0** [comment]
I'm not sure what's going on, but all of the sudden things were normal again in one of my Chromium-based browsers - so it must be a in browser caching problem, even though I tried to clear everything many times before.

I think the issue can be closed since it's more likely to be some kind of Chromium bug.
