### ISSUE TITLE
Remove tags?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9391]
The `tags` property is a disused feature that intended to allow users to annotate models with arbitrary data that could be used for querying the object graph. AFAIK the only place it shows up at all is in one integration test:
```
./integration/embed/referencing_roots.py:
   35 :     <!-- filtering roots by tags -->
   38 :         {% if "quad" in root.tags %}
   67 : quad_red = figure(tags=["quad"], **opts)
   70 : quad_green = figure(tags=["quad"], **opts)
   73 : quad_blue = figure(tags=["quad"], **opts)
```
And over the years there have been almost no questions or conversations about the property. I'd like to propose simply removing it for 2.0 without deprecation. 

cc @bokeh/dev

**Comment by philippjfr** [comment]
We use tags internally in HoloViews and Panel to keep track of state and to perform querying. Filtering roots by tag is not something I had thought of but now that I see it's possible I'd actually like to use it for some of the template work I'm going to start on. I'd be surprised if no other project made use of it in some form so I'm -1 on removing them.

**Comment by philippjfr** [comment]
Is it possible there has been no discussion around them since they are pretty simple and just work?

**Comment by bryevdv** [comment]
@philippjfr AFAIK they were also never really documented. In any case, if Holoviews is making use of them then that's enough reason to leave them be.
