### ISSUE TITLE
[BUG] Inferno3 palette in BokehJS is incorrect

### ISSUE THREAD

**Issue by netbek** [bokeh/bokeh#9392]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh: 1.4.0

#### Observed behavior

The Inferno3 palette in BokehJS incorrectly uses the values from Viridis3. See:

* https://github.com/bokeh/bokeh/blob/a338ea836720f14f6e8c720fc1fb46a66aed8816/bokehjs/src/lib/api/palettes.ts#L259
* https://github.com/bokeh/bokeh/blob/a338ea836720f14f6e8c720fc1fb46a66aed8816/bokehjs/src/lib/api/palettes.ts#L355

#### Expected behavior

I expected the same colours as `bokeh.palettes.Inferno3` in Python:

```typescript
export const Inferno3    = [0x000003, 0xba3655, 0xfcfea4]
```

See:

https://github.com/bokeh/bokeh/blob/b4def4947ed607114bce7df0bf3a3b5ff5444261/bokeh/palettes.py#L1410

**Comment by bryevdv** [comment]
@netbek Thanks for the issue, would you care to submit the small PR to update things?

**Comment by netbek** [comment]
Ready for review: https://github.com/bokeh/bokeh/pull/9397
