### ISSUE TITLE
BOKEH_RESOURCES does not work with server

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9395]
As of 1.4 the server currently ignores e.g. 

    BOKEH_RESOURCES=cdn

The reason for this is that previously, setting resources like that actually modified all Resources objects to simply override their specified operation. So although the server hard codes "server" resources:

    return Resources(mode="server", root_url=root_url, path_versioner=StaticHandler.append_version)

Things still "worked". However with the latest settings updates, this surreptitious modification no longer happens. The server code should be updated to actually inpect `settings.resources` and act accordingly.

**Comment by bryevdv** [comment]
Noting that this mostly affects the demo site, as CDN  resources were specified as a means to reduce our costs by utilizing less ELB bandwidth. I think it will be OK to leave as-is until 2.0 but if there is a spike in cost we may revert to 1.3.4 (some tweaking/better tagging of our dockerhub will be necessary)

**Comment by mattpap** [comment]
I also noticed that development resources have been finicky to use recently. I suppose both issues are connected.

**Comment by bryevdv** [comment]
@mattpap can you elaborate? I don't really use `BOKEH_DEV` so I don't know what it's supposed to do. But if you mention specific requirements I can make sure they are in place when I fix this.
