### ISSUE TITLE
[BUG] bokeh.tile_providers is an unknown_location in Pycharm

### ISSUE THREAD

**Issue by zarifaziz** [bokeh/bokeh#9402]
Can't import get_provider and Vendors from tile_providers.py file. Using Python 3.7 and Bokeh 1.4

![image](https://user-images.githubusercontent.com/15042003/68660299-0162c800-058d-11ea-85a9-cd42b994f13c.png)

![image](https://user-images.githubusercontent.com/15042003/68660310-0889d600-058d-11ea-9109-9b09d0b7ed58.png)

**Comment by bryevdv** [comment]
It's `get_provider` (no s)

**Comment by bryevdv** [comment]
You either have a botched install, or you are using an old version of Bokeh (possibly without realizing, i.e. conda or virtual env mixup). However, helping with this is a support question, so it should be on the Discourse, not the issue tracker. https://discourse.bokeh.org/

**Comment by bryevdv** [comment]
Also: *please* always copy and paste real code text when possible, don't past images of code. That makes it much much harder to actually try and reproduce what you are seeing.
