### ISSUE TITLE
[BUG] Unable to disable buttons in on_click callbacks

### ISSUE THREAD

**Issue by agyanttiwari** [bokeh/bokeh#9404]
I am trying to disable a button after making a search call and enable it back after the search call is successful. However, the button is not getting disabled:
 
```python
from bokeh.layouts import widgetbox
from bokeh.models import widgets
from bokeh.plotting import curdoc
def make_search_call():
    global search_button
    search_button.disabled = True
    # Mimicking a search call
    time.sleep(5)
    search_button.disabled = False

search_button = widgets.Button(label="Search", button_type="success")
search_button.on_click(make_search_call)
layout = widgetbox([search_button])
curdoc().add_root(layout)
```
Bokeh version: `1.4.0`
OS: MacOs
Browser: Chrome
I think the button state tries to change only after the callback completes.
This was working fine in Bokeh version 0.13.

PS: I see the same behaviour if I try changing a  label for a widget as well.

**Comment by bryevdv** [comment]
@agyanttiwari Changes are only synchronized to the client at the *end* of a callback. Your blocking work is blocking updates from being sent to the client too. If you need to do something like this you would need to follow some of the patterns described here about putting blocking work in threads:

https://docs.bokeh.org/en/latest/docs/user_guide/server.html#updating-from-threads

for further support-type help the appropriate place is the Discourse: https://discourse.bokeh.org/

**Comment by agyanttiwari** [comment]
@bryevdv Thanks! That worked for me. 👍
