### ISSUE TITLE
bokeh serve --develop docs seem contradictory

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#9405]
The docs describe how to use `bokeh serve --develop`, but they also claim that the feature is not implemented, which seems contradictory:

![image](https://user-images.githubusercontent.com/1695496/68699270-52040200-0548-11ea-8452-963b62390753.png)

It does seem to work in practice, so should the text "* DEVELOP MODE BELOW NOT YET IMPLEMENTED *" just be removed?

**Comment by mattpap** [comment]
This documentation needs updating. The option is now called `--dev` and was implemented for 1.0.

**Comment by bryevdv** [comment]
@jbednar where exactly are these docs? I scanned the entire repo and came up with nothing
```

~/work/bokeh master
(base) ❯ grin "DEVELOP MODE BELOW NOT"

~/work/bokeh master 12s
```

**Comment by mattpap** [comment]
This documentation was removed in f18a6398fbd37b6372b03d8df890f0ef6762e312 (in 2016).

**Comment by jbednar** [comment]
D'oh!  I must have found an old version of the docs online and failed to notice the URL.  Sorry for the noise!
