### ISSUE TITLE
Options for "untrusted" deployments

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9411]
Some users have expressed interest in using Bokeh in services that would ultimately host user-generated Bokeh content. Similarly, a potential future `share.bokeh.org` site would explicitly be for hosting user-generated content. In these cases it seems desirable to limit the ability to execute arbitrary JS code, e.g. from `CustomJS` type models, or from custom extensions. 

I imagine we could provide a `Bokeh.set_untrusted()` function that could be set (and never unset) by whatever is rendering the page and loading Bokeh, which would cause:

* custom model registration to fail
* CustomJS `execute` functions to no-op

I think we could leave `js_link` intact since the JS code to perform those linkages is generated solely by us, there are no hooks to accept arbitrary code. 

Thoughts @bokeh/dev @mattpap @shughes-uk ?

**Comment by mattpap** [comment]
> custom model registration to fail

This seems too restrictive. We should only limit dynamically added JS. Bundled extensions, especially originating from wher bokehjs was loaded, should be fine.

**Comment by bryevdv** [comment]
No one seems to have any interest in this, closing.
