### ISSUE TITLE
CI coverage reports have issues

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9421]
* Getting double results: from checkout, and from test env
* result now include `sampledata` but they should not

@mattpap did anything change recently?

**Comment by mattpap** [comment]
> did anything change recently?

No idea.

**Comment by bryevdv** [comment]
It's also way undercounting coverage now, e.g it has full coverage for a repo file:

> /home/travis/build/bokeh/bokeh/bokeh/client/states.py                                                                 33      0   100%

but then zero coverage for the same package file

> /home/travis/miniconda/envs/testenv/lib/python3.7/site-packages/bokeh/client/states.py                                33     33     0%

**Comment by bryevdv** [comment]
This seems to have resolved itself, but we are now only at 80% coverage
