### ISSUE TITLE
[BUG] Linked Plot Update Not Working in NBViewer or HTML

### ISSUE THREAD

**Issue by mfi7z** [bokeh/bokeh#9423]
Hi all,

I am having trouble with an interactive plot which works perfectly fine when used in my local notebook but not when shared via nbviewer or as html. Below is a picture of part of the plot:

![image](https://user-images.githubusercontent.com/17951239/69007978-67f93480-0945-11ea-82d9-6d94eda2b656.png)

The upper part is plotting glyphs with rect. Below that there are some sliders and below that there is a grid with information including pictures of molecules (which are integrated via ImageURLs). What is supposed to happen is that when you click on one of the upper tiles the information and pictures in the lower part is updating based on the selection. This is working but not when shared (nbviewer or html). Also, the other interactive elements (slider, tooltip) are working in either environment. 

The code which updates the selection is as follows:

```
    js_code = """
        var ind = cb_obj.indices;
        var xitm = s1.data.x[ind];
        var yitm = s1.data.y[ind];
       
        var inds = [];
        for (var i = 0; i < s2.data.ePhile_URL.length; i++) {
            if ((s2.data.REPLACE_X[i] == xitm) && (s2.data.REPLACE_Y[i] == yitm)){
                inds.push(i);
            }
        }
        inds = _.sample(inds, REPLACE_NREAC);
        
        s3.data['ePhile_URL']     = [];
        s3.data['nPhile_URL']     = [];
        s3.data['Product_1_URL']  = [];
        s3.data['Solvent_1_Name'] = [];
        s3.data['Base_1_Name']    = [];
        s3.data['Ligand_1_Name']  = [];
        s3.data['Solvent_1_URL']  = [];
        s3.data['Base_1_URL']     = [];
        s3.data['Ligand_1_URL']   = [];
        s3.data['LeavingGroup']   = [];
        s3.data['SubstrateClass'] = [];
        s3.data['Reagent_1_URL']  = [];
        s3.data['Yield']          = [];
        s3.data['CitString']      = [];
        for (var i = 0; (i < inds.length); i++) {
            s3.data['ePhile_URL'].push(s2.data['ePhile_URL'][inds[i]].toString());
            s3.data['nPhile_URL'].push(s2.data['nPhile_URL'][inds[i]].toString());
            s3.data['Product_1_URL'].push(s2.data['Product_1_URL'][inds[i]].toString());
            s3.data['Solvent_1_Name'].push(s2.data['Solvent_1_Name'][inds[i]].toString());
            s3.data['Base_1_Name'].push(s2.data['Base_1_Name'][inds[i]].toString());
            s3.data['Ligand_1_Name'].push(s2.data['Ligand_1_Name'][inds[i]].toString());
            s3.data['Solvent_1_URL'].push(s2.data['Solvent_1_URL'][inds[i]].toString());
            s3.data['Base_1_URL'].push(s2.data['Base_1_URL'][inds[i]].toString());
            s3.data['Ligand_1_URL'].push(s2.data['Ligand_1_URL'][inds[i]].toString());
            s3.data['LeavingGroup'].push(s2.data['LeavingGroup'][inds[i]].toString());
            s3.data['SubstrateClass'].push(s2.data['SubstrateClass'][inds[i]].toString());
            s3.data['Yield'].push(s2.data['Yield'][inds[i]].toString());
            s3.data['CitString'].push(s2.data['CitString'][inds[i]].toString());
            
            if (s2.data['Reagent_1_URL'][inds[i]].toString() == ""){
                s3.data['Reagent_1_URL'].push("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAA1BMVEX///+nxBvIAAAASElEQVR4nO3BgQAAAADDoPlTX+AIVQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwDcaiAAFXD1ujAAAAAElFTkSuQmCC");
            }
            else{
                s3.data['Reagent_1_URL'].push(s2.data['Reagent_1_URL'][inds[i]].toString());
            }
        }
        
        s3.change.emit();
    """
    js_code = js_code.replace('REPLACE_Y',y)
    js_code = js_code.replace('REPLACE_X',x.replace('compKey','Name'))
    js_code = js_code.replace('REPLACE_NREAC',str(nReac))
    
    s1.selected.js_on_change('indices', CustomJS(args=dict(s1=s1, s2=s2, s3=s3), code=js_code))
```

Essentially what I am doing is plotting the lower part based on source s3, whcih is a subset of source s2, updated when you click on a tile in the upper part (which is plotted via source s1).

I have tried to investigate this issue further by plotting that graph into a .html and opening the developers console. The error I get when clicking on a tile is
```
VM17:12 Uncaught ReferenceError: _ is not defined
    at eval (eval at get (bokeh-1.4.0.min.js:428), <anonymous>:12:9)
    at n.execute (bokeh-1.4.0.min.js:428)
    at e.<anonymous> (bokeh-1.4.0.min.js:316)
    at t.n.emit (bokeh-1.4.0.min.js:266)
    at t.emit (bokeh-1.4.0.min.js:266)
    at e.t._setv (bokeh-1.4.0.min.js:265)
    at e.t.setv (bokeh-1.4.0.min.js:265)
    at e.set [as indices] (bokeh-1.4.0.min.js:265)
    at e.update (bokeh-1.4.0.min.js:323)
    at e.do_selection (bokeh-1.4.0.min.js:345)
```

This however is cryptic to me, could this be a bug or a version issue?

Relevant versions are:
OS Windows 10.0.17763
Browser Google Chrome 78.0.3904.70 (problem also appearing in internet explorer)
Python 3.6.7
Bokeh 1.4.0
Jupyter NB 5.7.2
JavaScript 1.7

Many thanks

**Comment by xavArtley** [comment]
The error does not seems so cryptic to me:
`VM17:12 Uncaught ReferenceError: _ is not defined`
which is use here : `inds = _.sample(inds, REPLACE_NREAC);`
I suppose it's related to the underscore.js library which is embed in jupyter notebook but not exported with NBViewer

**Comment by bryevdv** [comment]
Right, Bokeh does not use or provide Underscore, so it is coming from somewhere else Presumablely the live notebook, but apparently not included in nbviewer output. 

Options:
* Rework JS code to not use underscore
* Find a way to include underscore in nbviewer output

We could possibly help/discuss the former on the Bokeh project Discourse, but the latter is a question Jupyter people on their tracker or forum.

**Comment by mfi7z** [comment]
Many thanks, I reworked the JS code to avoid underscore and now it works. Cheers
