### ISSUE TITLE
[BUG] bokeh.plotting fails when provided a ColumnDataSource containing nan in a list column

### ISSUE THREAD

**Issue by bensoussanj** [bokeh/bokeh#9425]
**Version**
bokeh 1.4.0

**Description**
bokeh plotting functions fail when provided a ColumnDataSource that has one or more NaN values in a column containing lists (even though unrelated to the plot - no pun intended)

```
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource

import pandas as pd
import numpy as np

p = figure()

# this line works
# df = pd.DataFrame({'A':[1,2,3], 'B':[3,2,1], 'C': [[1,2,3], [2,3,4], ['x','y']]})

# this one fails
df = pd.DataFrame({'A':[1,2,3], 'B':[3,2,1], 'C': [[1,2,3], [2,3,4], np.nan]})
source=ColumnDataSource(data=df)

p.circle(x='A', y='B', source=source)

show(p)
```

**Comment by bryevdv** [comment]
If your data has NaN values you will have to put it in a NumPy array. Bokeh can faithfully transmit NaNs in NumPy arrays because those get serialized using a binary format. Plain lists are serialized as JSON, and the JSON spec does not support or include NaN or Inf in. I think that is an inexplicable oversight but also not anything we can do anything about.

**Comment by bryevdv** [comment]
To add a bit more, in the case above, that data is rendered as:
```
data":{"A":[1,2,3],"B":[3,2,1],"C":[[1,2,3],[2,3,4],"NaN"]
```
which clearly will not work. I expect Pandas has decided those are integer columns, so if you are more explicit and tell Pandas that should be floating point then things should work

**Comment by bryevdv** [comment]
Actually the real problem here is that pandas makes it dtype object:
```
In [4]: df.C
Out[4]:
0    [1.1, 2, 3]
1      [2, 3, 4]
2            NaN
Name: C, dtype: object
``` 
That's nothing Bokeh an work with in general.

**Comment by bryevdv** [comment]
And *also* I did not notice before, you `C` data does not have consistent dimensions. There's no way to make sense of an array with two subarrays, and then a third single nan. The third element would also need to be an array with consistent size. Here is a way to make things work under those assumptions:
```
df = pd.DataFrame({'A':[1,2,3], 'B':[3,2,1]})
source=ColumnDataSource(data=df)
source.data['C'] = np.array([[1,2,3], [2,3,4], [1, 2, np.nan]])
```

**Comment by bensoussanj** [comment]
Understood, but this is very confusing (and time consuming) because bokeh accepts dataframes as datasources, and then without any explanation it fails to show a graph.
You say nothing you could do anything at all about, but maybe you could actually filter the datasource columns to only include the columns that are relevant to a given chart?

**Comment by bryevdv** [comment]
> You say nothing you could do anything at all about, but maybe you could actually filter the datasource columns to only include the columns that are relevant to a given chart?

Not really, extra columns may be used by hover tools,  any number of customJS callbacks, or even by JS code outside of Bokeh. It was a deliberate choice to include the data as-is because it it needed and desired in so many situations.

**Comment by bensoussanj** [comment]
I completely agree, and that is what I ended up doing, but it took some time to figure out why bokeh wasn't showing anything! (my dataset has about 100 columns)

So, why not at least fail gracefully, i.e. returning an error indicating that Bokeh failed to serialize the DataSource, which could also help the user look up the error and understand more quickly that something is wrong in the data.

**Comment by bryevdv** [comment]
> So, why not at least fail gracefully, i.e. returning an error indicating that Bokeh failed to serialize the DataSource, which could also help the user look up the error and understand more quickly that something is wrong in the data.

Scanning entire arrays is not free. There are already people using Bokeh in performance situations (e.g. the Dask dashboard) that want options to *reduce* some of the existing validations we do, because they want things to perform faster. It's hard to justify making 99.99% of all working cases slower to catch this is relatively uncommon error case. E.g. this works fine:
```
df = pd.DataFrame({'A':[1,2,3], 'B':[3,2,np.nan]})
```
It's only your list of lists, specifically in Pandas, that caused problems, and I've not seen users run  in to that in seven years until now.
