### ISSUE TITLE
[BUG] Changing color bar range dynamically with CustomJS makes tick labels disappear

### ISSUE THREAD

**Issue by ahuang11** [bokeh/bokeh#9431]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
python=3.7.3
bokeh=1.4.0
jupyter                            1.0.0
jupyter-client                     5.2.4
jupyter-console                    6.0.0
jupyter-contrib-core               0.3.3
jupyter-contrib-nbextensions       0.5.1
jupyter-core                       4.4.0
jupyter-highlight-selected-word    0.2.0
jupyter-latex-envs                 1.4.4
Chrome

#### Description of expected behavior and the observed behavior
Changing color bar range dynamically with CustomJS RangeSlider makes the image colors change accordingly, but makes tick labels disappear

#### Complete, minimal, self-contained example code that reproduces the issue
code modified from https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/J8inS0yMqWc
```
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import Row
from bokeh.models import LinearColorMapper, BasicTicker, ColorBar
from bokeh.models.widgets import RangeSlider

data = np.random.rand(10,10)

color_mapper = LinearColorMapper(palette="Viridis256", low=0, high=1)

figure = figure(x_range=(0,1), y_range=(0,1))
img = figure.image(image=[data], color_mapper=color_mapper,
                   dh=[1.0], dw=[1.0], x=[0], y=[0])

color_bar = ColorBar(color_mapper=color_mapper, ticker= BasicTicker(),
                     location=(0,0))

figure.add_layout(color_bar, 'right')

range_callback = CustomJS(args=dict(img=img), code='''
                        img.glyph.color_mapper.high = cb_obj.value[0];
                        img.glyph.color_mapper.low = cb_obj.value[1];
                        ''')
range_slider = RangeSlider(start=data.min(), end=data.max(),
                           value=(data.min(), data.max()),
                           step=0.1, title="PWR", width=400,
                           callback=range_callback, callback_throttle=1000)

show(Row(figure, range_slider))
```

#### Stack traceback and/or browser JavaScript console output
[bokeh] document idle at 22 ms

#### Screenshots or screencasts of the bug in action
Before
![image](https://user-images.githubusercontent.com/15331990/69186029-6b272880-0add-11ea-8e20-ef4c6ab0ac3e.png)

After
![image](https://user-images.githubusercontent.com/15331990/69186005-62365700-0add-11ea-81c6-7fba8d10151f.png)

**Comment by AlphaJi** [comment]
Your code has a bug. Switch 'low' & 'high' as below:
```
range_callback = CustomJS(args=dict(img=img), code='''
                        img.glyph.color_mapper.low = cb_obj.value[0];
                        img.glyph.color_mapper.high = cb_obj.value[1];
                        ''')
```
![20191218150426](https://user-images.githubusercontent.com/15061887/71063769-6a4ee880-21a8-11ea-837b-74a0287be58f.jpg)

**Comment by bryevdv** [comment]
@AlphaJi  Thank you for the observation I concur this is a usage issue and the code functions as expected with your change.
