### ISSUE TITLE
remove f-strings from docstrings

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9432]
@mattpap  I know we made a few changes around this already but evidently f-strings are not allowed as docstrings (and result in None for `__doc__`) so we should undo them:

https://bugs.python.org/issue28739

```
>>> class foo:
...    f'''{10}'''
...
>>> foo.__doc__ is None
True
```
seems we are stuck with `format_docstring`

**Comment by mattpap** [comment]
> https://bugs.python.org/issue28739

People still call this a simple programming language. Either they should have made this work or throw a syntax error, but they chose the hidden option number three, make it confusing.

**Comment by mattpap** [comment]
Unless you want do do this, I will revert those changes when I have a moment.
