### ISSUE TITLE
[BUG] Network latency results in orphaned embedded divs for Bokeh Server

### ISSUE THREAD

**Issue by Gordonei** [bokeh/bokeh#9435]
Before I get into the bug report, I would like to thank the core Bokeh team for their hard work on this project - increasingly it's my Python plotting tool of choice!

#### Software Version Info (bokeh, python, notebook, OS, browser, any other relevant packages)
* Bootstrap `4.0.0`
* Bokeh: `1.4.0`
* Python: `3.6.8`
* OS: Ubuntu Linux `19.10`
* Browser: Firefox `70.0.1`, Chrome `78.0.3904.70`

##### Expected Behaviour
Provided the network is fairly snappy, everything works as it should, and my Bokeh server plots are properly located within my HTML template, e.g.

```html
<div class="bk-root" id="a080f844-164a-495b-b7c3-848fd2c9342c" data-root-id="1432">
  <div class="bk" style="position: relative; display: block; left: 0px; top: 0px; width: 500px; height: 250px; margin: 0px;">
    <div class="bk" style="width: 618px; height: 309px; cursor: default;">
      <!-- rest of plot's divs here -->
    </div>
  </div>
</div>
```

##### Observed Behaviour
However, when there is latency on the network, or the Bokeh server is under strain (I've reproduced this by DoSing with many concurrent browser tabs), the bokeh plots are **not** properly placed in the designated place in the Jinja template, but rather appended to the end of the document's body. So the plots **are** rendering, just in the wrong place, e.g.

```html
<div class="bk-root" id="f98d93cb-905f-4d52-8fbf-9e7f0393b631" data-root-id="1373"></div>
<!-- Rest of my HTML body -->
<div class="bk bk-root">
    <div class="bk" style="position: relative; display: block; left: 0px; top: 0px; width: 948px; height: 474px; margin: 0px;">
        <div class="bk" style="width: 1354px; height: 677px;">
          <!-- rest of plot's divs here -->
        </div>
    </div>
</div>
```

As I'm doing all of my styling and layout in a HTML template using Bootstrap, this results in a pretty broken WUI.

##### Complete, minimal, self-contained example code that reproduces the issue
I've struggled to reproduce this with a minimalist example, as I suspect is being caused by the size of the rendered plots, etc.

I can share all of my code, however I'm concerned that parsing that would slow down this request - I have a strong suspicion about where the problem is [here](https://github.com/bokeh/bokeh/blob/aa8f3028e1b02a438f740116b127ded280f18038/bokehjs/src/lib/embed/dom.ts#L27-L34). See the theory subsection for more detail.

#### Browser JavaScript console output
From unhappy case:
```
[bokeh] setting log level to: 'info' logging.js:1
[bokeh] Websocket connection 0 is now open connection.js:1
Source map error: Error: request failed with status 404
Resource URL: <network path to app>/static/css/bootstrap.min.css
Source Map URL: bootstrap.min.css.map
Use of mozImageSmoothingEnabled is deprecated. Please use the unprefixed imageSmoothingEnabled property instead. canvas.js:1
[bokeh] document idle at 382 ms document.js:1
Bokeh items were rendered successfully index.js:1
```
I don't think the missing bootstrap file is relevant, but happy to be corrected on this.

Is the line `document idle at 382 ms` relevant?

##### Expected
![bokeh_happy_case](https://user-images.githubusercontent.com/1272984/69227922-5b661d80-0b8b-11ea-8ca0-1b35590bb7e9.png)

##### Observed
![bokeh_unhappy_case](https://user-images.githubusercontent.com/1272984/69227908-5608d300-0b8b-11ea-9e88-5ce2dedf29ce.png)

The empty div is present, but compressed into a single line. You can actually see one of the orphaned divs in the background, out of place.

#### Theory
**caveat** I'm not much of a web-dev, so I might be horribly off base here.

As mentioned earlier, I have a  suspicion the problem is [here](https://github.com/bokeh/bokeh/blob/aa8f3028e1b02a438f740116b127ded280f18038/bokehjs/src/lib/embed/dom.ts#L27-L34). Tracing the code through, it looks like the only place where the bokeh `item` either ends up in the right place, or just appended to `document.body`.

My theory is that there is some sort of race condition, where the client side Bokeh JS is trying to embed the plot, and somehow the `document.getElementById` [here](https://github.com/bokeh/bokeh/blob/aa8f3028e1b02a438f740116b127ded280f18038/bokehjs/src/lib/embed/dom.ts#L10) is not returning the right `div`, and hence it's defaulting to `document.body`.

I suppose another possibility is that Bootstrap is somehow interfering with the Bokeh JS finding the right div?

I'm open to working on a patch for this, but unfortunately I don't know TypeScript, so if someone is willing to provide a fair bit of guidance, I could give it a bash?

**Comment by Gordonei** [comment]
I should have looked more carefully, but I did find [this issue](https://github.com/bokeh/bokeh/issues/4188) which seems to be describing a similar issue.

Looking at the [relevant code](https://github.com/bokeh/bokeh/blob/c70ed019e9ed2822845a54c60c4716524e907482/bokeh/embed/wrappers.py#L75), I wonder if another possible race condition is around `document.readyState`?

**Comment by Gordonei** [comment]
I've tried this monkey patch that switches over to the `load` event - it doesn't seem to have resolved the issue:

```python
wrappers._ONLOAD = """\
(function() {
  var fn = function() {
%(code)s
  };
  if (document.readyState != "complete") fn();
  else document.addEventListener("load", fn);
})();\
"""
```

I suppose this suggests it is less likely to be a race condition, and some sort of issue where the client side Bokeh JS just can't find the right div.

**Comment by bryevdv** [comment]
> some sort of issue where the client side Bokeh JS just can't find the right div.

Can this be detected? Perhaps an exponential backoff retry with some cap? Not sure what else to suggest offhand.

**Comment by Gordonei** [comment]
Thanks for the prompt reply - OK, I'll try add some debugging logging to see if I can get a better idea about the nature of error.

**Comment by Gordonei** [comment]
@bryevdv, after looking at things further, will you please explain how the `elementid` property is set on each of the `render_items` from the generated code?

In the generated `_ONLOAD` JS wrapper (from `embed.wrappers`), `doc_json` and `render_items` values are set, and passed to `root.Bokeh.embed.embed_items` i.e.: 
```javascript
var docs_json = document.getElementById('5284').textContent;
var render_items = [{
  "roots":{"4935":"188f407e-f67f-4e2f-b5d4-d2c663374bed","4936":"aece6d19-0fc8-43fe-8d70-f5f4d20f5f31","4937":"22f75cf9-3972-451d-8ce8-c5b4d2ff439f","4943":"40e1e449-c634-473c-98b4-a968edcd71ba","5026":"9ec8c608-0833-481c-8711-ce389fd64f7a","5046":"a0cc338c-cd7b-4141-947d-0663a8ff5643","5068":"181ea377-bd7c-4aa2-8d17-e6cd1bb436c8","5139":"aab53010-244a-469c-90a3-1c5f43897569"},
  "sessionid":"rSKssif89X0DaKANNdQghndP5apcJO1akXuwHJxtybGn",
  "use_for_title":true}];
  root.Bokeh.embed.embed_items(docs_json, render_items);
```

There is no `elementid` property, hence it makes sense to me that the `_resolve_element` function resolves to `document.body` - so how does it ever resolve to anything else, i.e. the case when my page renders as I expect?

**Comment by Gordonei** [comment]
Actually, nevermind - after instrumenting the client code a fair bit, I don't think it's the problem, but would welcome confirmation of my thinking.

I've logged out element that is being returned [here](https://github.com/bokeh/bokeh/blob/aa8f3028e1b02a438f740116b127ded280f18038/bokehjs/src/lib/embed/dom.ts#L10), which is pretty early on in the flow, and I'm seeing a difference in the **HTML** of the happy vs sad case, i.e. the `innerHTML` attribute of the element is set in the happy case, and not set in the sad case.

My thinking is that this then points the finger at the server code (?).

**Comment by mattpap** [comment]
Unless you already tried this, please reproduce this issue without any custom templates, external libraries (like bootstrap) etc. If the issue persists, then we will know that this is problem with bokeh (js or sever). Otherwise, please add your changes one by one, and see which makes the difference. Then we will be able to differentiate if this is a usage error or an interaction with other libraries/code (bokehjs should be unaffected, but web tech doesn't allow us for proper isolation).

**Comment by Gordonei** [comment]
Sure, so I've spent most of the evening instrumenting both the client and server side to see if I can work out what is going on both sides, as increasingly it looks like this might be arising out of some strange interaction between the two. 

I have been able to reproduce after disabling all external libraries. I'm not 100% how I could reproduce without my custom template, as the nature of the problem is that my template is getting mangled.

Here's what I've been able to trace so far:
1. On the server side, initially when generating the HTML:
```
2019-11-20 23:32:38,979 main.<module> [DEBUG]: session_id=ggNztoXAdPSLTrU0Zgnp5uSsuGw4Kembw9WaSsatZiNl
2019-11-20 23:32:38,979 main.<module> [DEBUG]: root_ids=2412, 2414, 2413, 2420, 2501, 2521, 2543, 2612
```
2. A little while later, the session gets discarded because it looks abandoned:
```
2019-11-20 23:33:05,653 contexts._discard_session [DEBUG]: Discarding session 'ggNztoXAdPSLTrU0Zgnp5uSsuGw4Kembw9WaSsatZiNl' last in use 26648.23295800388 milliseconds ago
```
3. However, later, a new request comes in, and this seems to trigger another response with the same session ID from the server, however the div root IDs change i.e.
```
2019-11-20 23:32:38,979 main.<module> [DEBUG]: session_id=ggNztoXAdPSLTrU0Zgnp5uSsuGw4Kembw9WaSsatZiNl
2019-11-20 23:32:38,979 main.<module> [DEBUG]: root_ids=11843, 11845, 11844, 11851, 11932, 11952, 11974, 12043
```
4. And sure enough, now, when the WS request comes, asking for the plot contents, it gets the new div values:
```
2019-11-20 23:33:27,936 session._handle_pull [DEBUG]: Sending pull-doc-reply from session 'ggNztoXAdPSLTrU0Zgnp5uSsuGw4Kembw9WaSsatZiNl'
2019-11-20 23:33:27,962 document.to_json_string [DEBUG]: root_ids=11843, 11845, 11844, 11851, 11932, 11952, 11974, 12043
```

On the client side, I'm obviously getting the HTML generated in (1), and the WS values in (4), but I'm not seeing any trace of the request that caused (3).

The divs are getting appended haphazardly because of this function [here](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/embed/standalone.ts#L23-L32), which checks if the id is in the existing set of roots, otherwise it just appends it to the body, wrapped in a div.

**Comment by bryevdv** [comment]
@Gordonei are you running with `--num-procs` > 1 or with multiple Bokeh servers running behind a load balancer by chance?

**Comment by Gordonei** [comment]
On my local machine, no, I'm using dev mode - that's where the logs above come from.

I have also deployed it to a cluster, where the problem occurs more frequently (it's what caused me to notice it in the first place). I kept the number of replicas down to 1, but I have been using `--num-procs` > 1. It is going through a traefik reverse proxy.

**Comment by Gordonei** [comment]
Another observation is that bumping `--check-unused-sessions` and  `--unused-session-lifetime` helps on my local machine, so I think there is something strange going on around session persistence.

**Comment by bryevdv** [comment]
Oh, well let's also clarify: just *how much* lag are we talking about here? I just noticed the 26648 milliseconds log message...

Byt default Bokeh will happily create a new session for a session ID that it does not recognize, and that includes both the initial HTTP connection, as well as on the subsequent WS connection upgrade. If there is really a *huge* delay between the HTTP connection and the WS upgrade that the original session expires, I guess I can see how this could happen. Think in that case the only option is to tune up `--unused-session-lifetime` really high, well past what you expect the lag might ever reasonably be (that's what it is for)

**Comment by Gordonei** [comment]
Sure, thanks for clarifying the behaviour around clients with unseen session IDs - I think it explains a lot of the behaviour I'm seeing. I can live with tuning up the timeouts. The comment about load-balancing was pertinent too, thanks - I've fiddled with my cluster settings, and by setting `--num-procs` to 1, but with multiple replicas and LB stickiness, I get horizontal scaling and the occurrence rate seems to be much lower compared to 1 replica with multiple threads.

Generally, I think we're talking up to a few seconds here, which is not inconceivable when serving up via a bursty mobile network, or one administered by those prone to fits of deep-packet inspection enthusiasm. I suppose another plausible scenario is a low powered device desperately time-slicing.

The relatively long latency in the logs above is due to how I've been reproducing it on my local machine - turning off all caching inside my application, and DoSing with multiple concurrent browser sessions.

> That said, there might also be an issue anytime there is a custom template and multiple server processes. The solution would have to be to communicate the div IDs through to the WS connect, in that case.

This makes sense to me - the divs IDs are unique to a particular session, hence they'll need to be shared back and forth. Given that the user has already provided a unique identifier to place the div in the template (the `name` attribute on the Bokeh model object), could you use that as the div ID? Then it wouldn't vary across sessions. Although you would probably need to sanitise them in some way.

**Comment by bryevdv** [comment]
TBH if the lag is only a few seconds that would seem to not fall outside the default session expiry parameters. But if you have LB stickiness and can increase them anyway, that might be the best workaround for now. 

> Given that the user has already provided a unique identifier to place the div in the template (the name attribute on the Bokeh model object), could you use that as the div ID? 

Possibly. Outside custom templates, we just generate UUID div ids IIRC, so perhaps it's simply a case of not replacing user supplied div ids with those (if that is what is going on). If that's the case that then HTTP vs WS session would cease to be at issue. 

> Although you would probably need to sanitise them in some way.

It's entirely possible this is why we still use UUIDs come to think of it. If we need to communicate ids to the WS connection the only real place will be inside the encoded session token, but that would also provide a mechanism for rendered HTML to connect to sessions with stable div ids. (Tho again, it may result is a large-ish token... but I guess that's ok)

**Comment by Gordonei** [comment]
> TBH if the lag is only a few seconds that would seem to not fall outside the default session expiry parameters.

So what I think was happening was on my server, requests were hitting different threads, whilst on my local tests, sessions were timing out. So different causes, but resulting in the same manifestation of empty divs in my template, and orphaned divs being appended to the end of the document body.

Before talking about potential remedies, I wonder if taking a step back here, there should have been a more explicit error on the client side, as opposed to just appending the content to the body? The behaviour of the server accepting unseen session IDs makes sense to me (as documented via [XKCD](https://xkcd.com/869/)), but to my mind, from the client perspective, the server was breaking a previously defined contract (i.e. the layout of the page). Maybe I don't understand the circumstances where [this behaviour makes sense](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/embed/standalone.ts#L29-L32)?

> But if you have LB stickiness and can increase them anyway, that might be the best workaround for now.

To get onto the topics of remedies, I'm happy to do a PR for the [Running a Bokeh Server documentation](https://docs.bokeh.org/en/latest/docs/user_guide/server.html) - I'm thinking of a slightly more general subsection under the Deployment Scenarios section? Or is my scenario maybe a bit too niche?

As a broader principle, I quite like making load-balancing and session state coherence out of the scope of the server. With all of the scaling options available, there really isn't much cost to having multiple server instances running with a load balancer focused on routing traffic appropriately, as opposed to one instance with many threads having to also manage some sort of shared state.

**Comment by Gordonei** [comment]
OK, @bryevdv and @mattpap, I've finally created a PR for the proposed change to the Server documentation.

An alternative would be to create a consistent way to generate Figure divs.

**Comment by bryevdv** [comment]
OK I think we determined this was due to `--num-procs` > 1, is that correct? I so this can be closed in favor of other similar issues.

**Comment by Gordonei** [comment]
As far as I've seen, but I've also now reproduced it with multiple server instances behind a load balancer without session stickiness.

Is this in line with the issues you have in mind?

**Comment by Gordonei** [comment]
OK, I've been able to carve out a little time to take a look at the underlying code here. I'm not very familiar with the code base, so I'm going to need a little hand-holding, I'm afraid.

What I've been done so far is trace backwards from the [embed code](https://github.com/bokeh/bokeh/blob/master/bokeh/core/_templates/macros.html#L2), and it seems to me what we require is that the `elementid` attribute (as distinct from the `id` attribute) of the [`RenderItem` class](https://github.com/bokeh/bokeh/blob/master/bokeh/embed/util.py#L166) to be consistent across threads/server instances.

Something that isn't clear to me is where the `elementid` is assigned/initiatilised for the models within the server document? I'm going to add some logging to see if I can tease it out, but I suspect there is a bigger picture here that I'm not appreciating.

**Comment by Gordonei** [comment]
@bryevdv , sorry to bug you, but do you mind pointing me to where the `elementid` field is set for server documents?

**Comment by bryevdv** [comment]
cc @mattpap (all the `RenderItem` machinery was written by him)

**Comment by Gordonei** [comment]
Thanks, @bryevdv!

**Comment by Gordonei** [comment]
Hey, @mattpap - do you mind commenting on the above? 

Probably the most pressing question I have at this point is where the `elementid` value for server documents' `RenderItem` are assigned.

**Comment by Gordonei** [comment]
Shamelessly bumping the thread :)

**Comment by mattpap** [comment]
I suppose PR #9660 fixed this as well?

**Comment by bryevdv** [comment]
I believe it should, @Gordonei is it possible for you to test with current master? Or else provide a minimal reproduce?

**Comment by Gordonei** [comment]
Thanks guys, reading through the above PR, it does seem to be hitting the issue I was describing.

I'll try with my code against master - failing that, I'll try provide a simple reproduction.

**Comment by Gordonei** [comment]
OK, looks like the fix solves this issue!

## Baseline
1. Cloned the repo anew
2. Checked out b19f2c5547024bdc288d02e73fdb65e65991df5f (1.4.0)
3. Did a fresh install (i.e. selected choice (1) for build and install fresh)
4. Checked version (`python3 -m bokeh --version`): `1.4.0`
5. Started up a server instance of my app with two processes: `BOKEH_LOG_LEVEL='debug' python3 -m bokeh serve city_dashboard_app --num-procs=2 --log-level debug`
6. DoSed the server using firefox: `for i in 1 2 3 4 5 6 7 8 9 10; do firefox -new-tab -url http://localhost:5006; done`

Confirmed that the plots got misplaced.

## With #9660
1. Checked out e0b465a12162170087bc5adc08689fd3ff602e3c (the commit with the fix in it)
2. Did a fresh install (i.e. selected choice (1) for build and install fresh)
3. Checked version (`python3 -m bokeh --version`): `2.0.0dev6-41-ge0b465a12-dirty`
4. Started up a server instance of my app with two processes: `BOKEH_LOG_LEVEL='debug' python3 -m bokeh serve city_dashboard_app --num-procs=2 --log-level debug`
5. DoSed the server using firefox: `for i in 1 2 3 4 5 6 7 8 9 10; do firefox -new-tab -url http://localhost:5006; done`

No sign of misplaced divs!

Thanks to @philippjfr and @mattpap for sorting this out!
