### ISSUE TITLE
[Suggestion] use pre-commit

### ISSUE THREAD

**Issue by ammarnajjar** [bokeh/bokeh#9439]
I would suggest setting up [pre-commit](https://github.com/pre-commit/pre-commit) for this project.

Reasoning:
I have seen these under-development issues/PRs:
- apply auto formatter (black) #9438
- apply static-typing (mypy): #9358, #9064, #9353, #9066, #9069

Pros:
- configurable (yaml-file)
- supports python and node (used for Bokeh)
- can be used as a pre-commit hook (runs against staged changes)
- can be run against working tree directly from the cli: `pre-commit run --all-files`
- so many [supported hooks](https://pre-commit.com/hooks.html)
- can be integrated into the CI-pipline
- uses shallow cloning
- thanks to @asottile, a pre-commit github action is under development.

Cons (not really):
- first run take some time to clone the configured hooks to a local location.

If the idea clicks, let me know. I will be able to prepare a working draft soon 😉

**Comment by bryevdv** [comment]
I think this could be good to look into. We have an open PR (hopefully soon to be merged) that applies black formatting across the `bokeh` and `tests` dirs (but not docs scripts, those need to optimize for different readability considerations). We also just merged an `isort` PR as well. Let's take a look at this after the PR is merged and the code base is stable and updated with the new formatting. Then this work would be a matter of keeping the status quo. Sound good?

**Comment by bryevdv** [comment]
I recently had occasion to encounter `pre-commit` in another project and found it flaky and hard to use (it never actually worked for me). We have a couple of suggested git hooks in our dev docs and instrutions to install them, I think that is sufficient.

**Comment by asottile** [comment]
@bryevdv I'd be curious what you encountered -- if you could send some bug reports that would be appreciated -- I've put a lot of work into making it _not_ flaky :)
