### ISSUE TITLE
Misname/copypasta: login_hander?

### ISSUE THREAD

**Issue by timkpaine** [bokeh/bokeh#9446]
Are these supposed to be `login_handler` and `logout_handler` instead of `hander`?
https://github.com/bokeh/bokeh/blob/master/bokeh/server/auth_provider.py#L110

**Comment by bryevdv** [comment]
WOW yes 😮 Can you submit a PR to change them?

**Comment by timkpaine** [comment]
@bryevdv yep will do tonight
