### ISSUE TITLE
Update examples to current Bokeh status for clarity and simplification

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#945]
e.g:
Examples that do this:
```python
source = ColumnDataSource(
    data=dict(
        petal_length=flowers['petal_length'],
        petal_width=flowers['petal_width'],
        sepal_length=flowers['sepal_length'],
        sepal_width=flowers['sepal_width'],
        color=flowers['color']
    )
)
```

instead of
```python
source = ColumnDataSource(flowers)
```

Please list examples that you think could be simplified or clearer with recent bokeh releases and features, so someone can update them.

**Comment by bryevdv** [comment]
I have gone ever every example to simplify and bring everything up to current best practice usage.
