### ISSUE TITLE
ColumnDataSource documentation update

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#946]
In the documentation, I can find information on 
`PandasDataSource`: 
http://bokeh.pydata.org/docs/reference.html?highlight=datasource#bokeh.objects.PandasDataSource
(which is actually "really not implemented")
And `DataSource`: 
http://bokeh.pydata.org/docs/reference.html?highlight=datasource#bokeh.objects.DataSource

But not much in `ColumnDataSource`, which is what most/all examples use:
http://bokeh.pydata.org/docs/bokehjs.html?highlight=columndatasource#data-sources

>Data is typically passed to bokehjs through a ColumnDataSource which has named columns of data that are available to glyph renderers. Note that all the columns in a given ColumnDataSource should have the same length. It is possible and often necessary to have different data sources for different renderers.

**Comment by damianavila** [comment]
This is also covered by @bryevdv work on docs... so closing it.
