### ISSUE TITLE
[BUG] figure does not load properly if output_backend="svg" and Arrow is used

### ISSUE THREAD

**Issue by m3bert** [bokeh/bokeh#9471]
#### software version info 
- bokeh: 1.4.0
- tornado: 6.0.3
- nodejs: 12.12.0
- python: 3.7.5
- browser: Firefox 70.0.1 (32-Bit)

#### Description of expected behavior and the observed behavior
**Expected:**
![svg_expected](https://user-images.githubusercontent.com/39389064/69631486-40455300-104e-11ea-84dd-15ae293b6f5e.png)

**Observed:**
- After loading the page, the figure is incomplete. Axis, toolbar and title are missing. Also only the Arrowhead is visible.
![svg_bug](https://user-images.githubusercontent.com/39389064/69631544-505d3280-104e-11ea-814b-2a147320ce3e.png)

- When moving/panning the plot, it seems like it "floats" away.
![svg_bug_after_pan](https://user-images.githubusercontent.com/39389064/69631555-53582300-104e-11ea-8509-10c237f27e74.png)

- If multiple figures are used, the figures after the buggy figure are not plotted at all, regardless of whether svg, canvas or webgl is used.

- The console outputs the warning `W-1000 (MISSING_RENDERERS): Plot has no renderers: Figure(id='1002', ...)` **BUT** it seems it has nothing to do with it, because when I'm adding e.g. `figure_test.line(x=[2,4], y=[2,2])` this warning disappears, however the bug stays.

- This only happens if an `Arrow`  is used (as far as I can tell).
- output_backend="svg" works with LinearAxis and Label, so I don't think add_layout is broken?
- `Grid` seems to also cause these problems (if no ticker is set) but independet of output_backend (i.e. this "floating problem" also occurs for canvas and webgl for `figure_test.add_layout(Grid(dimension=0))` )

- JavaScript console output: `Attempted to apply path command to node g canvas2svg.js:1
Error rendering Bokeh items: DOMException: "Node was not found"  index.js:1`

- related to #8744 (direct export instead of browser display there, JS error message differs a bit)
- Maybe somehow related to #9436 due to general bugs in the Arrow model?

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.plotting import figure
from bokeh.models import Arrow
from bokeh.io import curdoc


figure_test = figure(title="Example Figure", x_range=(-1,6), y_range=(-0.5,4.5), height=300, width=400, tools="pan, save", output_backend="svg")
# ok for webgl and canvas

figure_test.add_layout(Arrow(x_start=2, y_start=2, x_end=3, y_end=2))
# does not matter if I add end=OpenHead() or end=NormalHead() explicitly

curdoc().add_root(figure_test)

```

**Comment by mattpap** [comment]
> related to #8744 (direct export instead of browser display there, JS error message differs a bit)

This is the same issue. Long story short, svg backend is broken, because the underlying library, that we use for svg rendering, is broken/incomplete and not actively maintained.

> `Error rendering Bokeh items: DOMException: "Node was not found" index.js:1`

We could at least catch this error, because it is this that prevents other plot components from rendering.
