### ISSUE TITLE
Area glyph does not recognise missing data points (nans)

### ISSUE THREAD

**Issue by ghost** [bokeh/bokeh#9475]
### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh.version: 1.3.4
Python version: 3.7.3
OS: GNU/Linux x86_64
Browser: Google Chrome 77.0.3865.90
JupyterLab version: 1.1.3

#### Description of expected behavior and the observed behavior

When plotting an area chart that contains missing values, I would expect that there would be a corresponding gap in the area glyph. However, Bokeh seems to interpolate the data, as shown in the example below. This is different to the behaviour in other plotting libraries such as matplotlib.

This issue may be related to #7890 - it looks like a similar issue has already been fixed for the **line** and **step** glyph, but not yet **area**.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.plotting import figure, output_notebook, show
import matplotlib.pyplot as plt
import numpy as np

# Example data
y = [0,1,2,3,4,5]
x1 = [1,2,np.NaN,np.NaN,1,1]
x2 = [5,7,np.NaN,np.NaN,5, 6]

# Bokeh plot
f = figure()
f.harea(y=y, x1=x1, x2=x2)
show(f)

# Matplotlib plot (for comparison)
f, ax = plt.subplots()
ax.fill_betweenx(y, x1, x2)
```

#### Screenshots or screencasts of the bug in action
![bokeh_area](https://user-images.githubusercontent.com/22548039/69818576-f0ed5700-11f4-11ea-912d-006ce09ac20a.PNG)

**Comment by bryevdv** [comment]
My first inclination is to say that if you need this sort of behavior then `Patches` or `MultiPolygons` is probably a better choice Bokeh and MPL do not always operate under the same constraints or assumptions so it's not a foregone conclusion that they should share the same behavious. Trying to do this for harea/varea would dramatically complicate the interactive hit-testing in a way that I am not sure we can support.

**Comment by bryevdv** [comment]
I'm going to close this for lack of any additional discussion or interest and reiterate that `Patches` or `MultiPolygons` are better options for cases like this.
