### ISSUE TITLE
`nonselection_color` (etc.) doesn't apply after PR #9153

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9479]
See e.g. `examples/app/selection_histogram.py`.

Ref: #9153

**Comment by bryevdv** [comment]
cc @solstag 

I'd regard this as a failure of test coverage, primarily. We should make sure the fix includes additional tests.

**Comment by bryevdv** [comment]
@solstag do you have any thoughts? In a nutshell, code like this:
```
p.scatter(x, y, radius=radii,
          fill_color=colors, fill_alpha=0.6)
```
Produces a non-selection glyph with a fill_alpha 0f 0.6 instead of the trait_default of 0.1

**Comment by solstag** [comment]
Ni! Hi @bryevdv ,

The problem with changing that order is that it would mess with the hardcoded ultimate defaults for traits 'color' and 'alpha'. For those, `trait_defaults` is supposed to come after `defaults`.

What I think would work for special casing nonselection is to do it directly at line 967, as in:

```
diff --git a/bokeh/plotting/helpers.py b/bokeh/plotting/helpers.py
index 4dd5294e8..b7cb7c634 100644
--- a/bokeh/plotting/helpers.py
+++ b/bokeh/plotting/helpers.py
@@ -964,7 +964,9 @@ def _glyph_function(glyphclass, extra_docs=None):
             raise RuntimeError(_GLYPH_SOURCE_MSG % nice_join(incompatible_literal_spec_values, conjuction="and"))
 
         # handle the nonselection glyph, we always set one
-        nsglyph_ca = _pop_visuals(glyphclass, kwargs, prefix='nonselection_', defaults=glyph_ca, trait_defaults={'alpha':0.1})
+        if 'alpha' in glyphclass.properties() or any(prop.endswith('_alpha') for prop in glyphclass.properties()):
+            kwargs['nonselection_alpha'] = kwargs.get('nonselection_alpha', 0.1)
+        nsglyph_ca = _pop_visuals(glyphclass, kwargs, prefix='nonselection_', defaults=glyph_ca)
 
         # handle the selection glyph, if any properties were given
         if any(x.startswith('selection_') for x in kwargs):

```

Another option, which I kinda like, is to do away with this special case and have people explicitly pass the nonselection characteristics they want, but I'm quite sure that's not what you folks expect ;-)

.~´

**Comment by bryevdv** [comment]
> Another option, which I kinda like, is to do away with this special case and have people explicitly pass the nonselection characteristics they want, but I'm quite sure that's not what you folks expect 

Definitely need things to just work in some reasonable way by default. The support burden for (mostly me, personsally) having to continually answer "why doesn't selection work?" is too much to consider. 

@solstag did you see my actual PR changes which are different from the diff above? I left `trait_defaults` at the end split them from the the passed in `override_defatults` which happen earlier. The only place override defaults are used (currently) are for this alpha so I think this should be equivalent to what you have above, but also keep the current usage outside `_pop_visuals`?

**Comment by solstag** [comment]
Sorry @mattpap , I did not see the PR :P 

There is indeed no problem with your solution, and thanks for the tests!

Now, I kinda feel that this "override_defaults" behaviour, being only ever used in that one line of code, perhaps does not justify the extra argument and logic in `_pop_visuals`. One idea is to keep my solution, your tests, and remove the "trait_defaults"/"override_defaults" parameter from `_pop_visuals`.

Does that speak to you? Otherwise we can keep your solution!

**Comment by bryevdv** [comment]
I will keep things as they are currently, I'd like to keep the responsibility for computing these values in one place. Thanks @solstag
