### ISSUE TITLE
CustomJS interfering with button click plot update[BUG]

### ISSUE THREAD

**Issue by samirak93** [bokeh/bokeh#9481]
Hi, 

I came across this issue while trying to add a CustomJS for a button click [https://discourse.bokeh.org/t/custom-js-for-button-click/4327/2](https://discourse.bokeh.org/t/custom-js-for-button-click/4327/2). In a scenario where the button is associated with a plot update and a customJS (like a loading circle), the plot update stops after 2 button clicks. 

Example code: 

```
from bokeh.io import curdoc
from bokeh.models.widgets import Button
from bokeh.layouts import layout, column
from bokeh.models.callbacks import CustomJS
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

import numpy as np

fruits = []
counts = []
source = ColumnDataSource(data=dict(fruits=fruits, counts=counts))

p = figure(x_range=[], plot_height=350, toolbar_location='left', title="Fruit Counts", tools='wheel_zoom')
p.vbar(x='fruits', top='counts', width=0.9, source=source)

def plot_change():
    fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
    counts = np.random.randint(low=1, high=100, size=6)
    source.data = dict(fruits=fruits, counts=counts)
    p.x_range.factors = list(fruits)

callback_button = CustomJS(args={},code="""
                $(document).ready(function() {
                $('.button').on('click', function() {
                    var $this = $(this);
                    var loadingText = '<p style="font-size:20px;"> <i class="fa fa-circle-o-notch fa-spin"></i> loading...</p>';
                    if ($(this).html() !== loadingText) {
                    $this.data('original-text', $(this).html());
                    $this.html(loadingText);
                    }
                    setTimeout(function() {
                    $this.html($this.data('original-text'));
                    }, 3000);
                });
                })""")

button_plot = Button(label="Draw Plot", css_classes=['button'])

button_plot.js_on_click( callback_button)
button_plot.on_click(plot_change)

curdoc().title = "Loading Button"
doc_layout = layout(column(button_plot, p))
curdoc().add_root(doc_layout)

```

If you run the above code you'd see the below issue: 

![loader_issue](https://user-images.githubusercontent.com/22864480/69894319-1355a200-12d3-11ea-934e-e4ad55f2de3a.gif)

```
Python version: 3.7.5
Bokeh version: 1.4.0
```
I cannot see any issue on the browser console or terminal. 

I'm not highly comfortable with JS. If the issue is with the script, please provide a feedback or if this is a bug in bokeh, let me know as well.

Thank you.

**Comment by bryevdv** [comment]
I would not consider this sort of messing around with Bokeh views to be supported usage. This sort of this was never envisioned or intended, it is simply out of scope. If you want to do this sort of direct DOM manipulation you should explicitly add and manage your own (non-Bokeh) buttons.
