### ISSUE TITLE
Disable option in FileInput not working [BUG]

### ISSUE THREAD

**Issue by samirak93** [bokeh/bokeh#9485]
Hi,

The `disabled = True` option in FileInput is not working when either given within the widget or set explicitly as below. 

```
from bokeh.io import show
from bokeh.models.widgets import FileInput

file_input = FileInput(disabled = True)
file_input.disabled = True
show(file_input)
```

![image](https://user-images.githubusercontent.com/22864480/69908285-fd131900-139a-11ea-901d-e49986428d67.png)

```
Python: 3.7.5
Bokeh: 1.4.0
```

Thanks.

**Comment by bryevdv** [comment]
Need to set `disabled` on the DOM element when appropriate, here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/widgets/file_input.ts#L15

**Comment by bryevdv** [comment]
Though, looking at that logic, I think a little more work is justified. This test at the top of `render`:
```
   if (this.dialogEl) {
      return
    }
``` 
means that the widget will not respond to any model property changes once the DOM element is initially created, AFAIK. So we should fix that by splitting out the DOM element creation (which only needs to happen once) from updating properties on the element (which should happen whenever there is a change or even just every render is probably fine)

**Comment by samirak93** [comment]
I'll give it a try and let you know how it goes. Thanks :)
