### ISSUE TITLE
Manually release version 2.0?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9491]
I'd like to get opinions on shutting down the current deploy automation and releasing Bokeh 2.0 by hand. 

The reason for this is because there need to be some fairly non-trivial build/release changes for 2.0 e.g the SRI hashes work (#8397), and I *really* do not want there to be any chance of a "botched" 2.0 release requiring an immediate 2.0.1 and scramble. With a manual release all the build steps can be done up front, and the CDN resources uploaded, then the packages can be installed and tested before any irreversible publish steps to package repositories. If there is some problem along the way, we can pause, rewind, and try again after issues are fixed. 

After 2.0 I would restore automated build and publish steps, but would make those steps separate and distinct, to afford final package tests and testing before publication. (#9341)

Thoughts @bokeh/dev?

**Comment by birdsarah** [comment]
Fine by me.
