### ISSUE TITLE
[BUG] DatePicker display off-by-one in non-GMT timezone after upgrade to 1.4.0

### ISSUE THREAD

**Issue by rstrutt** [bokeh/bokeh#9494]
Versions:

- Bokeh: 1.4.0
- Python: 3.7.3
- Chrome: 78.0.3904.108 (Official Build) (64-bit)
- O/S: Windows 7 Pro SP1
- **TimeZone**: EST (Issue observed in EST but not in GMT)

After the fix of [this issue](https://github.com/bokeh/bokeh/pull/9232/commits/472e4770d363b3914bb478f0a6c3a83787b20c0d#) in 1.4, I observe the following issue;

In the EST timezone, if I update a DatePicker based on the value of another DatePicker, I get a different date (1 day previous to the selected date).  If the browser is located in a GMT timezone then I do not observe the issue.  Minimal example below.

**Expected behavior**: On selecting a date from the first DatePicker, the second DatePicker displays that same date;

![image](https://user-images.githubusercontent.com/7271339/70002782-16e56500-152f-11ea-9f05-3b810742904f.png)

**Observed behavior**: On selecting a date from the first DatePicker, the second DatePicker shows a date one day previous to the selected date;

![image](https://user-images.githubusercontent.com/7271339/70002817-354b6080-152f-11ea-9c39-ad09e0b5ca05.png)

```
from bokeh.layouts import column
from bokeh.models import DatePicker
from bokeh.plotting import curdoc


def a_changed(attr, old, new):
    date_picker_b.value = new


date_picker_a = DatePicker()
date_picker_b = DatePicker()

# When we pick a date in date_picker_a, set the date in date_picker_b
date_picker_a.on_change('value', a_changed)

curdoc().add_root(column(date_picker_a, date_picker_b))

```

In our application, we have a date slider and some fixed date-range buttons (year-to-date, month-to-date etc) coupled to two date pickers, which is how we observed the issue, but the above example seems to minimally demonstrate the issue that dates don't round-trip from the DatePickers.

**Comment by bryevdv** [comment]
At this point I really want to spend some time trying a different date picker. We have had more issues with Pikaday than any other single widget. 

https://www.cssscript.com/tag/date-picker/

**Comment by rstrutt** [comment]
Thanks Bryan.  Both those options look good.  In the mean-time I'll work around it.  Top work on Bokeh, it's a fantastic bit of kit.

**Comment by bryevdv** [comment]
Well, not a promising start at least with me trying. Litepicker does not have a TS module defined and Flatpickr, which seems very nice, tiny, and much more capable than Pickaday, is absolutely destroyed by our layout tinkering. 

cc @mattpap if you have any guidance

**Comment by bryevdv** [comment]
#9509 fixes this and many other datepicker issues (as well as adds selenium tests) but note that the implementaton was switched to Flatpickr, and also now date values can *only* be expressed as ISO date strings, or `datetime.date` and nothing else (in particular no more datetime values which caused endless trouble with time zones)

**Comment by rstrutt** [comment]
Nice work, Sir.  Thank you.  Looking forward to trying this out along with all the other good stuff in 2.0
