### ISSUE TITLE
[FEATURE] Add functionality so interactive Bokeh Plots shared as HTML files can be sent and seen to users through IOS text messages

### ISSUE THREAD

**Issue by samcoh** [bokeh/bokeh#9497]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**
When sharing Bokeh code as an HTML file through text message, Bokeh interactive plots do not appear. Interactive plots created on bokeh should be available to users through imessage on IOS devices. 
 
**Describe the solution you'd like**
HTML file formats should display bokeh interactive plots on mobile devices. This feature will increase the usability of the software for users. 

**Describe alternatives you've considered**
Currently, interactive plots made through Bokeh do not show up on mobile devices when HTML file is shared through text message on IOS devices. This is annoying and frustrating for users when trying to share code with others through this format. 

**Additional context**

**Comment by bryevdv** [comment]
@samcoh I very much doubt this is possible, in principle. Bokeh plots are actually small Javascript applications that turn a blob of JSON into an interactive plot. AFAIK there is no capability to execute JavaScript code in text messages, in general, and hence no way to have real interactive Bokeh plots function at all. If you know of something about running JS code in text messages that I don't, please provide a reference.

**Comment by bryevdv** [comment]
I guess I would add, tangentially, that we are interested in starting up a `share.bokeh.org` site (think Imgur for Bokeh plots). In which can you could send links to the share site via SMS that could then be viewed *in a mobile browser*. But that is a substantial long term idea that will take actual monetary investment or sponsorship to make happen.

**Comment by bryevdv** [comment]
I don't actually think there is any action that can be taken here so I am going to close with `noaction` if there is new information we can re-open and re-evaluate.
