### ISSUE TITLE
[FEATURE] Bokeh Sizing mode that inherits from parent

### ISSUE THREAD

**Issue by shughes-uk** [bokeh/bokeh#9498]
Is there a way to have Bokeh inherit it's size from a parent div that has height/width set to 100%? I am trying to use bokeh with react-grid-layout, a very popular grid react library that is used by tools like grafana to allow users to create dashboards. https://strml.github.io/react-grid-layout/examples/4-grid-property.html.

It sets a fixed width/height on a parent div several levels up from bokeh, but i have had no luck getting bokeh to pay attention to this.

This is using sizing _mode "stretch_both"
![one](https://user-images.githubusercontent.com/546891/70110396-ad835600-1603-11ea-8280-11731eb8978f.gif)
![two](https://user-images.githubusercontent.com/546891/70110421-bffd8f80-1603-11ea-9467-1ad50fee2202.gif)

**Comment by shughes-uk** [comment]
"scale_both" yields  better results, but only when I trigger a rerender somehow (ive just been resizing the browser window in testing)

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by mattpap** [comment]
Any "responsive" (`scale_*` and `stretch_*`) sizing mode will adjust to available space, however layout has to be notified that a change has happened. By default `resize` events on `window` and a change in `display` trigger relayout. Monitoring other DOM/CSS changes proved unreliable, and not that desirable, so far, but I can always reevaluate this. In the mean time you can use the underlying framework's event system to trigger a relayout manually (use `LayoutDOM.resize_layout()`).

**Comment by shughes-uk** [comment]
Thanks I was able to get it working by fetching the plot from Bokeh.index, as i dont have a direct reference to the LayoutDom because i'm using embed_item
![bokeh](https://user-images.githubusercontent.com/546891/70182823-75c6ed80-1699-11ea-87cb-4eee97d7afa7.gif)
