### ISSUE TITLE
[FEATURE] Allow access to the authenticated user from within an app

### ISSUE THREAD

**Issue by sdc50** [bokeh/bokeh#9506]
It would be nice to be able to access the authenticated user from within the app code so that the app can be customized based on a user.

Consider the [server_auth example](https://github.com/bokeh/bokeh/blob/master/examples/howto/server_auth/app.py#L31-L34): 

I would like to be able to do something like this:
```
# Set up plot
username = get_current_user_somehow()
plot = figure(plot_height=400, plot_width=400, title=f"{username}'s sine wave",
              tools="crosshair,pan,reset,save,wheel_zoom",
              x_range=[0, 4*np.pi], y_range=[-2.5, 2.5])
```

There is a `get_user` function defined in the `auth.py` module, but it seems like this isn't intended to be used in the app. In any case it is not clear how one would get the `request_handler` (presumably an instance of `tornado.web.RequestHandler`) to pass to the function.

It appears that the only information from the `auth_module` that is intended to be accessed from the app is the `logout_url` which is accessible as `curdoc().session_context.logout_url`. Would it make sense to have add a `user` attribute to the `session_context` (i.e. `curdoc().session_context.user`)? 

**Additional context**
More generally, what I would like to be able to do is configure the authentication to use an OAuth provider and then use the access token from the OAuth to access the provider's API. Following the example provided in the [Tornado Docs](https://www.tornadoweb.org/en/stable/guide/security.html?highlight=get_cookie#third-party-authentication) it was fairly straightforward to create an OAuth login to the Bokeh app, but there is no way that I can tell to then get access to the user information including the access token.

**Comment by sdc50** [comment]
@philippjfr, @bryevdv perhaps you've already discussed this, but this issue describes what I think is needed.

**Comment by philippjfr** [comment]
This is linked to https://github.com/bokeh/bokeh/issues/9505 which will make it possible to expose various information about the request, authentication etc. from within the app in a consistent way.

**Comment by bryevdv** [comment]
I'd personally vote to  close this as a dupe of #9505, since one of the aims of that work is explicitly to expose an authenticated user to app code.

**Comment by sdc50** [comment]
> I'd personally vote to close this as a dupe of #9505, since one of the aims of that work is explicitly to expose an authenticated user to app code.

Oops! I should have refreshed my browser before opening the new issue. I didn't see @philippjfr's  issue, but, yes, that would address everything I'm requesting here.
