### ISSUE TITLE
[BUG]  Click_policy hide not working for multiline plots

### ISSUE THREAD

**Issue by harmbuisman** [bokeh/bokeh#9510]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 1.4.0

<details>

python: 3.7.4.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
</details>

#### Description of expected behavior and the observed behavior
Legends have a click policy with which you can show/hide legend items
from a graph. In the case of multi-line plots this policy however shows/hides
all the shown lines, not just the one that is clicked. This means this
functionality is not usable for multi-line plots.

Desired behaviour: only show/hide the line that is clicked, such that
with a multi-line plot you can use this functionality.

#### Complete, minimal, self-contained example code that reproduces the issue

```
#  Multi-line legend
from bokeh.plotting import curdoc, figure
import numpy as np
from bokeh.models import ColumnDataSource

source = ColumnDataSource()
source.data = {'xs': [np.arange(5) * 1, np.arange(5) * 2],
        'ys': [np.ones(5) * 3, np.ones(5) * 4],
        'labels': ['one', 'two']}

p = figure(width=600, height=300)
p.multi_line(xs='xs', ys='ys', legend_group='labels', source=source)
p.legend.click_policy = "hide"
curdoc().add_root(p)
```

#### Screenshots or screencasts of the bug in action
Before clicking one item in the legend:
![image](https://user-images.githubusercontent.com/7702207/70347061-02230d00-1860-11ea-969c-d8317c4b28c2.png)

After:
![image](https://user-images.githubusercontent.com/7702207/70346900-a35d9380-185f-11ea-90c6-f05d1050edd7.png)

Expected:
Only one of the lines hidden

**Comment by bryevdv** [comment]
@harmbuisman This is just not going to be feasible, we can only modulate a single glyph at a time. If you need this capability, you should use multiple `line` glyphs instead of a single `multi_line` glyph.
