### ISSUE TITLE
async io_loop lock process?

### ISSUE THREAD

**Issue by john-pasglop** [bokeh/bokeh#9512]
I am a newbie in bokeh, so my question should be stupid...
But when I try to test the following bokeh example:
  https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/standalone_embed.py
I only replace `Server(...,numprocs=4)` by `numprocs=1`.
And I had a `print('finish')` as a last line of code in this example after the 'server.io_loop.start()'.
When I close the web browser, I obtain the following message:
_###!!! [Parent][MessageChannel] Error: (msgtype=0x160080,name=PBrowser::Msg_Destroy) Closed channel: cannot send/recv_
And my python process seems to be listening on default port 5006 'for_ever', without printing the message 'finish' as I was waiting by the print last command line.

Is the error message could explain such behaviour ? and I need to solve this point.
Or is-it the expected behaviour? (i.e. python process listening for_ever)
In this last case, how can I integrate more python code after the `server.io_loop.start()` to be execute after I close the web browser? (need to use a thread in way to manage bokeh server for example ?)

**Comment by bryevdv** [comment]
@john-pasglop We reserve the issue tracker for bug reports and development related topics. Please take support questions to the Project Discourse:


https://discourse.bokeh.org/
