### ISSUE TITLE
Update bokeh developer documentation

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh#9517]
The following changes can be made in the [developer documentation](https://docs.bokeh.org/en/latest/docs/dev_guide.html):

* _Getting set up -> Preliminaries -> [Conda](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#conda)_: Links to the [conda documentation](https://docs.conda.io/en/latest/) need to be updated.
* Throughout the developer guide, `contact the developers` currently links to https://bokeh.org/, we can have it point to https://discourse.bokeh.org/c/development/.
* _Getting set up -> [Cloning the repository](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#cloning-the-repository)_ asks us to clone the main bokeh repo. We can briefly describe that active @bokeh/dev contributors should use the main repo whereas new/casual contributors must clone their personal fork instead (and why).

Credits: @bryevdv

**Comment by bryevdv** [comment]
@pavithraes are you still interested to make a PR for these changes?
