### ISSUE TITLE
[BUG] Arrow lines do not render completely if figure is placed below some div

### ISSUE THREAD

**Issue by m3bert** [bokeh/bokeh#9522]
#### software version info
- Bokeh 1.4.0
- Python 3.7.5
- Tornado 6.0.3
- nodejs 12.12.0
- Firefox 71.0 (32-Bit) on Windows 10

#### Description of expected behavior and the observed behavior
Arrow lines should render fully.
They actually do, but in the setting Spacer + Figure + Slider they are being cropped.

**Expected**
![arrow_render_bug_expected](https://user-images.githubusercontent.com/39389064/70634656-e4282480-1c32-11ea-9b07-970c9e574d04.png)
Up to some specific position the arrow lines are rendered.

**Observed**
![arrow_render_bug_shown](https://user-images.githubusercontent.com/39389064/70634666-eb4f3280-1c32-11ea-8fbe-e41e8f2a1caa.png)
At some point the lines are not rendered anymore but the arrow heads are still visible.

![arrow_render_bug_little_spacer](https://user-images.githubusercontent.com/39389064/70634765-19cd0d80-1c33-11ea-8426-d8d65449167d.png)
When using a smaller Spacer, the cropping starts later.
I would guess that the div above the plot uses twice the height which is actually needed, but I could not validate this assumption.

The same problem also appears when including a Div or widgets instead of a Spacer.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, Arrow, OpenHead, NormalHead, Slider
from bokeh.plotting import figure
from bokeh.layouts import column, row, Spacer

a1_cds = ColumnDataSource(data=dict(xS=[0], xE=[4], yS=[-2], yE=[-2]))
a2_cds = ColumnDataSource(data=dict(xS=[7], xE=[7], yS=[-3], yE=[-2.9]))

def change_arrows(attr,old,new):
    a1_cds.stream(dict(xS=[0], xE=[4], yS=[new], yE=[new]), rollover=1)
    a2_cds.stream(dict(xS=[7], xE=[7], yS=[-3], yE=[new]),rollover=1)
    

f = figure(tools="", x_range=(-1,10), y_range=(-4,10))

a1_glyph = Arrow(end=NormalHead(), x_start='xS', y_start='yS', x_end='xE', y_end='yE', source=a1_cds)

a2_glyph = Arrow(end=OpenHead(), x_start='xS', y_start='yS', x_end='xE', y_end='yE', source=a2_cds)

f.add_layout(a1_glyph)
f.add_layout(a2_glyph)

s_arrows = Slider(title="change arrows", value=-2, start=-3, end=10, step=0.2)
s_arrows.on_change('value', change_arrows)

curdoc().add_root(column(Spacer(height=50),f,s_arrows))
```

#### Current Workaround and Trials
Setting the level attribute to `level="overlay"` or any other alternative level property does not help.
Lines via `f.line(...)` are rendered correctly.

If the sliders (or other widgets) are not positioned below the plot but next to the plot, i.e. `curdoc().add_root(column(Spacer(height=100),row(f,s_arrows)))`, the bug does not appear.

**Workaround** if the sliders really need to be positioned under the plot:
Adding an extra column.
`curdoc().add_root(column(Spacer(height=50), column(f,s_arrows) ))` 
So in general the figure should be the first object inside a column to avoid this bug.

#### Related Issues:
#9436  (that's why in the minimal example .stream with rollover=1 is used instead of direct assignment to data)

**Comment by bryevdv** [comment]
Well that's weird. Thank you for the issue with complete MRE @m3bert

**Comment by p-himik** [comment]
An even smaller example:
```python
plot = figure(x_range=(0, 6), y_range=(-1, 1))
btn = Button(label="noop")
plot.add_layout(Arrow(x_start=1, x_end=5, y_start=0, y_end=0))
doc.add_root(row(btn, plot))
```
