### ISSUE TITLE
[BUG] Hover info is behind some parts of the plot

### ISSUE THREAD

**Issue by gerdos** [bokeh/bokeh#9527]
Version 1.0.1

```
main_plot = gener_main_plot()
plot = add_some_box1(main_plot)
plot = add_some_box2(plot)
plot = add_some_box3(plot)
```
I generate the plot from multiple subplots. If I add a hover to the subplot generated by add_some_box2, it will be underneath the part generated by add_some_box3. 

Example picture: 
https://i.stack.imgur.com/Y1aGx.png

This bug was not present in version 0.12.15

**Comment by bryevdv** [comment]
@gerdos can you give some context why you closed the issue?

**Comment by gerdos** [comment]
@bryevdv Yes, sorry, I am not really familiar with GitHun issues yet. So the bug is present in version 1.0.1, however I was stupid, and thought that that is the latest release. The but is NOT present in the latest 1.4.0 version, thus is closed the issue.

**Comment by bryevdv** [comment]
Thanks for the info!
