### ISSUE TITLE
[BUG] compute_layout taking 7.8 seconds?

### ISSUE THREAD

**Issue by mstump** [bokeh/bokeh#9529]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

- bokeh==1.4.0
- Firefox 71.0 (64-bit) or Chrome 78.0.3904.108
- OSX 10.15.1

#### Description of expected behavior and the observed behavior

I've got a fairly complex app that we're using as the front end for our labeling flow. When we click on one of the items to be labeled it causes 5 widgets to be updated: two DataTables, two line plots, and one network graph. The python code is fast, it's just selecting different views or pre-computed dataframes. The problem lays with the JS code, taking 28-32 seconds to render with the browser being frozen most of the time. I did a profile with Chrome, and all of the time is being consumed by 4 calls to `compute_layout` each taking more than 7 seconds. 1/3 of that time is being spent in `measure`, and 2/3s being spent in `set_geometry`.

- Do I have too many rows and columns? 
- Is there something obvious that could be causing layout to take so long? 
- Are there strategies for speeding up layout? 
- The dimensions of my plots aren't changing, can I disable layout recompute when repainting?

#### Complete, minimal, self-contained example code that reproduces the issue

I'm not sure how to reproduce without handing over my entire app, but have uploaded a [Chrome profiling dump](https://www.dropbox.com/s/a3swqw6w0vune1q/Profile-20191217T210610.json?dl=0)

#### Screenshots or screencasts of the bug in action

![screenshot-localhost_5006-2019 12 17-21_15_33](https://user-images.githubusercontent.com/228171/71059453-c3bb0700-2117-11ea-886f-549d95599892.png)

**Comment by bryevdv** [comment]
@mstump  Thank you for the detailed report. This is almost certainly the same issue as #9515 so I am going to close marked as `dupe`, but that issue will get a link to this one for reference. Although some aspects of layout have gotten much better in the last year, there are still areas that need a lot of attention, in particular more than a couple of levels of nesting seems to be a problem. We are looking in to ways to prevent the over-computation that is happening. The only suggestion I have is that it might be helpful to reduce the overall level of complexity and nesting by splitting  things up in to separate Document roots (i.e. things that are passed to `curdoc().add_root(...)`) and rendered individually into an app template.

**Comment by bryevdv** [comment]
cc @mattpap in case you have any other workaround/mitigation ideas to suggest.

**Comment by mstump** [comment]
I tried your suggestion of decomposing the layout into several roots and wanted to report that it resulted in a significant improvement. The app was already composed of 4 logical "panels" arranged vertically. By adding these to the doc as separate calls to `add_root` instead of 4 rows in one master layout it shrank the time spent in layout from ~7.5 seconds per call to ~1.5 seconds. I'll see if I can decompose further.

**Comment by bryevdv** [comment]
@mstump That's good to hear, if you have an opportunity, a summary of findings in the other issue would welcome
