### ISSUE TITLE
Please replace MultiSelect widget with something more compact, effective and nicer looking

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/bokeh#9532]
ORIGINALLY POSTED AS PANEL FEATURE REQUEST AT https://github.com/holoviz/panel/issues/874

#### My Pain

I know of experience that many of my dashboard have multiple multi-selections. 

The MultiSelect widget of panel is not compact so it takes up a lot of space.

Furthermore I find the MultiSelect not very nicely looking. I would like my dashboards to look appealing and fresh.

Futhermore I think navigating and selecting in the MultiSelect widget is slow as soon as you have to start scrolling in the MultiSelect

![image](https://user-images.githubusercontent.com/42288570/70967814-c2e29080-2097-11ea-97cd-e41d3b9e1bc7.png)

#### Solution

Implement compact, efficient and nicer looking MultiSelect. 

It should work as a dropdown with multiselect.

#### Additional Context

You can get inspiration from Dash, Streamlit and Tableau that all have a much more compact and modern looking widget.

![image](https://user-images.githubusercontent.com/42288570/70967921-240a6400-2098-11ea-9d99-cefe44ed27dc.png)

![image](https://user-images.githubusercontent.com/42288570/70967964-3d131500-2098-11ea-8991-3ff2f1c29fc8.png)

FYI. Tableau has both a more compact Dropdown and something similar to the MultiSelect.

Here it's used an that's where I have my evaluation from. You can find it in the Gallery at awesome-panel.org.

![kickstarter_dashboard](https://user-images.githubusercontent.com/42288570/70968057-72b7fe00-2098-11ea-8680-73de1f2bf843.gif)

**Comment by bryevdv** [comment]
@MarcSkovMadsen it would be more helpful if you point to a specific widget or widgets that you would like to be considered, and ideally, would be something you wish to collaborate on implementing within Bokeh.

**Comment by philippjfr** [comment]
[Choices.js](https://github.com/jshjohnson/Choices) seems like the only option without a jQuery dependency.

**Comment by philippjfr** [comment]
I've now opened a PR with the widget [on Panel](https://github.com/holoviz/panel/pull/910). I'd be quite happy to the widget to Bokeh though.

**Comment by bryevdv** [comment]
I think it would be a good addition to Bokeh
