### ISSUE TITLE
[BUG] ```export_svg``` shifting x-axis upward and overlapping with ticks in Bokeh v1.4

### ISSUE THREAD

**Issue by magruca** [bokeh/bokeh#9551]
I'm working in bokeh v1.4 on Fedora29 and have been running into an issue that I hadn't seen before in ```export_svgs``` where the x-axis labels are getting shifted over the x-axis itself making it messy/illegible. This problem is not replicated in either show(p) or save_svg (I've attached an example of both the svg and png to demonstrate the problem -- both saved/imported here as pngs, but the file from the svg export is labeled as such). For some reason, this is worse in other plots (attached an example from my data -- I can provide more example code but I can't provide the data necessary to reproduce it).

Here's some example code for a couple of the provided plots:

```
from bokeh.plotting import figure, show
from bokeh.sampledata.iris import flowers
from bokeh.transform import factor_cmap, factor_mark

SPECIES = ['setosa', 'versicolor', 'virginica']
MARKERS = ['hex', 'circle_x', 'triangle']

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Sepal Width'

p.scatter("petal_length", "sepal_width", source=flowers, legend_field="species", fill_alpha=0.4, size=12,
          marker=factor_mark('species', MARKERS, SPECIES),
          color=factor_cmap('species', 'Category10_3', SPECIES))

p.output_backend = "svg"
export_svgs(p, filename = 'test_scatter.svg')
export_png(p, filename = 'test_scatter.png')

```
![test_scatter](https://user-images.githubusercontent.com/37707530/71643853-1b12b880-2c7c-11ea-910d-209ca82b06e6.png)
![test_scatter_svg](https://user-images.githubusercontent.com/37707530/71643861-3978b400-2c7c-11ea-8f5a-83738ed469c6.png)
![svg_export_example](https://user-images.githubusercontent.com/37707530/71643878-6dec7000-2c7c-11ea-93ac-ddfa3175442c.png)

Thanks a bunch for any help!

**Comment by bryevdv** [comment]
@magruca The export svg functionality has a number of currently known issues. Unfortunately, the third-party `canvas_to_svg` library that we used to implement it is no longer active or maintained. That means fixing the problems with be substantially more involved. I am not certain when that might happen, and I do not have any other workaround suggestions except to use the PNG export instead for now. 

FYI I am probably going go collect all the separate SVG issues (including this one) in to one master issue and close the individual ones.

**Comment by magruca** [comment]
I figured something as much when I was combing through the other issues -- appreciate the quick response on it!
