### ISSUE TITLE
[FEATURE] Placeholder text for FileInput

### ISSUE THREAD

**Issue by JorisMeertBambrugge** [bokeh/bokeh#9552]
The default text on the bokeh FileInput is "Choose File - No file chosen".

Is there a way i can change this text, e.g. to "Upload image"?
Could we create FileInput arguments like:

button_text='Choose File'
field_text='No file chosen'

Thanks

**Comment by bryevdv** [comment]
@JorisMeertBambrugge this would be a good first issue for a new contributor. Would you be interested to work on a PR for it with some guidance?

**Comment by bryevdv** [comment]
Actually this may require some discussion. Apparently this text is nominally hard-coded by the browser, and there are only relatively hacky (and possibly browser-specific) ways to try and override it:

https://stackoverflow.com/questions/686905/labeling-file-upload-button

It's possible we simply punt with `noaction` on this one.

**Comment by JorisMeertBambrugge** [comment]
Thanks Bryan for looking into it.
Indeed the stackoverflow suggestions on this topic are a bit hacky. The proposal at the bottom is relatively simple and works for me on both Chrome, Edge and IE11:

<input type="button" id="loadFileXml" value="Custom Button Name" onclick="document.getElementById('file').click();" />
<input type="file" style="display:none;" id="file" name="file"/>

That is easy to embed in a Div in Bokeh, however then I’m not sure how to get the imported file via a callback on the Div.

[cid:image001.png@01D5C473.47355BA0]
But even if there is a way, maybe this is something you don’t want in your distribution.
Cheers,
Joris

**Comment by ceziegler** [comment]
Why not at least add title feature to FileInput so that text describing the file can be placed above the choose file button?

**Comment by bryevdv** [comment]
@ceziegler perhaps but the cost of adding and maintaining features has to be weighed against what is already possible. I think nearly the same result could be accomplished by putting the file input in a column under a Div with the text you want displayed as a title.
