### ISSUE TITLE
[BUG] Bokeh on_click function changes text only after entire function has completed

### ISSUE THREAD

**Issue by choijonathan** [bokeh/bokeh#9569]
**Software Versions:**
OS: Windows 10
Browser: Version 79.0.3945.88 (Official Build) (64-bit)
Python: 3.7
JupyterLab: 1.2.4
Bokeh: 1.4.0

**Issue**
I am noticing that when I use a button to run a function that changes the text on the page and then run some code, the text does not change until the entire function has finished running. Here is an example where you would expect the text to change instantly, but it does not change until the time.sleep() has completed. Here is an example snippet I am launching from a jupyter notebook:

```
import time
from bokeh.models.widgets import Div
from bokeh.layouts import layout
from bokeh.models.widgets import Button
from bokeh.server.server import Server
from bokeh.application import Application
from bokeh.application.handlers.function import FunctionHandler

def make_document(doc):
    bokeh_text=Div(text="")
    test_button=Button(label='TEST',button_type="success")
    def test():
        bokeh_text.text = "Text has been changed"        
        time.sleep(3)
    test_button.on_click(test)
    my_layout=layout([test_button,bokeh_text])
    doc.add_root(my_layout)

apps = {'/': Application(FunctionHandler(make_document))}
server = Server(apps)
server.io_loop.add_callback(server.show, "/")
```
I would expect the time.sleep() should not have any effect on the speed of the text change since it occurs after the text is changed. However, I am observing that the page doesn't update the text until time.sleep() completes:
![slow_gif](https://user-images.githubusercontent.com/21065749/72113230-d935e200-330d-11ea-8944-1bd20107e060.gif)

Here is what it looks like if I remove the time.sleep() line
![fast_gif](https://user-images.githubusercontent.com/21065749/72113406-5d886500-330e-11ea-85db-5114b01a4ec9.gif)

**Comment by bryevdv** [comment]
@choijonathan This is not a bug, this is simply how the Bokeh server functions. Synchronization happens at the end of the function, as you have noted. In particular, doing the work to synchronize things is blocked by your code that is already running, until that moment. 

If you want something to happen "immediately" you will need to yield control and schedule any further work in a next-tick callback. See this SO answer:

https://stackoverflow.com/questions/59196855/python-bokeh-markup-text-value-cant-update/59199773#59199773

**Comment by choijonathan** [comment]
Thank you
