### ISSUE TITLE
DataTable Sort and Wrap text

### ISSUE THREAD

**Issue by edishu** [bokeh/bokeh#9574]
I have been unable to find these features anywhere:

1. DataTable Sort
There should be a way to sort (ascending and descending) a DataTable object on it first appearance, by any column desired. The tables can be sorted by users, but there should be a way from code to set the default sort order for a table:

```
source = ColumnDataSource(data=dict(message=['Placeholder row 1', 'Placeholder row 2', 
                                             'Placeholder row 3', 'Placeholder row 4',
                                             'Placeholder row 5', 'Placeholder row 6', 
                                             'Placeholder row 7', 'Placeholder row 8']))
columns = [
        TableColumn(field="message", title="Data Rows"),
    ]
data_table = DataTable(source=source, columns=columns, width=400)

show(data_table)
```
**Current Output**
![image](https://user-images.githubusercontent.com/37514088/72223512-9a866e80-353d-11ea-8317-d2f3f367233c.png)

**Desired Output** (Reverse sorted by index in this case)
![image](https://user-images.githubusercontent.com/37514088/72223520-bab62d80-353d-11ea-80c1-bafcb5179f3d.png)
there should be some way from code to output table in above format.

2. Wrap text
There should to some way to wrap text for longer content in any row:
```
source = ColumnDataSource(data=dict(message=['Placeholder row 1 for a very very long content in this column. Very very long content in this column.', 
                                             'Placeholder row 2 for a very very long content in this column. Very very long content in this column.',
                                             'Placeholder row 3 for a very very long content in this column. Very very long content in this column.',
                                             'Placeholder row 4 for a very very long content in this column. Very very long content in this column.',
                                             'Placeholder row 5 for a very very long content in this column. Very very long content in this column.',
                                             'Placeholder row 6 for a very very long content in this column. Very very long content in this column.',
                                             'Placeholder row 7 for a very very long content in this column. Very very long content in this column.',
                                            ]))
columns = [
        TableColumn(field="message", title="Data Rows"),
    ]
data_table = DataTable(source=source, columns=columns, width=400)

show(data_table)
```
![image](https://user-images.githubusercontent.com/37514088/72223595-97d84900-353e-11ea-9e56-7ed5a205adee.png)

Wrap text shall allow to display full content.

Please let me know if these functionalities already exist. Or please try to add these features in future versions.

**Comment by bryevdv** [comment]
@edishu I believe the HTMLTemplateFormatter will provide this possibility:

https://docs.bokeh.org/en/latest/docs/reference/models/widgets.tables.html?highlight=cellformatter#bokeh.models.widgets.tables.HTMLTemplateFormatter

For future reference please start usage questions in the Project Discourse, not the tracker:

https://discourse.bokeh.org/
