### ISSUE TITLE
Example report upload location

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9575]
All runs seem to be uploading to the exact same location:

https://ci.bokeh.org/github-ci/run10/examples.html

**Comment by bryevdv** [comment]
OK we are actually blocked on this:

https://github.community/t5/GitHub-Actions/Getting-the-run-id-of-a-run-in-Github-Actions/td-p/36567

Tho supposedly a unique run id will be available within the month. 

That said cc @mattpap I am not sure the diff-ref logic is working as intended, either.

**Comment by bryevdv** [comment]
Not sure how soon this will be unblocked on the GH side. Thinking of just switching to a different scheme for the report location e.g. `<PR #>/<date>`

cc @mattpap

**Comment by mattpap** [comment]
We can switch to a different scheme, in fact the proposed one seems better than what we use currently. On a side note, I already implemented locally the scheme for keeping images in the repository (for now in bokehjs' tests), so this issue will be a no-op soon, but given technical issues, this may take another week or so.

**Comment by bryevdv** [comment]
When you said store images in the repo I understood that to mean storing
one set of reference images only. Is that correct?

**Comment by bryevdv** [comment]
Given the other PR I am going to close this.

**Comment by bryevdv** [comment]
just documenting the run id is now available if we need it 

https://github.community/t5/GitHub-Actions/Getting-the-run-id-of-a-run-in-Github-Actions/m-p/45658#M6302
