### ISSUE TITLE
[FEATURE]Allow use of multiple formatters in DataTables

### ISSUE THREAD

**Issue by jensencl** [bokeh/bokeh#9584]
I would like to use both NumberFormatter and HTMLTemplateFormatter in some of my cases. If would be nice to have the capability to do something like: 

TableColumn(field='Part ID', title='Part ID', formatters=(HTMLTemplateFormatter(template='<a 
    onclick="window.location;" href="http://' + host_ip + ':8000/media/<%=value %>.pdf" 
    target="_blank"><%= value %></a>'), NumberFormatter(format='0[.]0000')), width=100)

**Comment by bryevdv** [comment]
To make the implementation as simple and self-contained as possible, this would probably have to take the form of a new "composite" formatter that is configured with a list of other formatters to apply in sequence:
```
my_formatter = CompositeFormatter([
    NumberFormatter(format='0[.]0000'),
    HTMLTemplateFormatter(template='...'),
])
```

@jensencl would you be interested to work on this with some help/guidance? This would make a good first issue.

**Comment by jensencl** [comment]
@bryevdv @bokeh/dev 
Sure. I would be interested in helping to get this moving forward.

**Comment by bryevdv** [comment]
@jensencl Brilliant! I would say the first steps are"

* Fork the Bokeh repo in to your own account
* Clone it locally to you machine

Then we have a Dev Guide that has all the steps needed to get set up to build BokehJS and dev/test locally:

https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#devguide-setup

Do you have any JavaScript/TypeScript experience? If not, that's fine, this will really be a small amount of that and I can walk you though things.

**Comment by jensencl** [comment]
@bryevdv  Not much. I have done a little playing with JS in django projects here recently, but most of my experience is in python. Luckily, I am trying to branch-out into other languages, so this will be good for me. I have the repo downloaded and installed per the instructions. 

Now it's just hoping I am not getting myself in over my head.
@bokeh/dev

**Comment by bryevdv** [comment]
> Now it's just hoping I am not getting myself in over my head. 

That's a really great way to learn, in my experience :Sri

**Comment by jensencl** [comment]
I do have it. I am looking at the bokeh>models>widgets>tables.py right now around line 107 right now trying to think how this could be added into this to start. I am thinking something like this might be a starting off point:

class CompositeFormatter('''Formatters'''):
    '''Formatter to apply multiple formatters to a single TableColumn'''

I believe I will need a list of the applicable formatters in the ( ) of class? And I believe this would need to be added to the __all__ list as well, correct?

**Comment by bryevdv** [comment]
@jensencl awesome. So there will be updates needed on both the "Python side" and on the "JS Side" The Python side will be let's start with that. You have identified exactly the correct file to make an addition to. I think it will basically just need to look like this:
```
class CompositeFormatter(CellFormatter):
    """ docstring here """

    formatters = Sequence(Instance(CellFormatter), default=[], help="""
    help bring for formatters here
    """
```

You may need to import the `Sequence` property type at the top of the file. Note that the correct alphabetical order will need be maintained in the imports as we have started verifying sort order in our CI test. If I may make a suggestion, I would say go ahead and open a new PR with this addition (fill in the docstrings) and we can continue to iterate on the JS side of things on the PR. Does that sound OK?

**Comment by jensencl** [comment]
@bryevdv I'm sorry I didn't get back to you the other day Bryan. I am still planning on working on this. I left work Friday evening and have had a pretty hectic weekend. I set everything up on my computer at work and I am having troubles remoting into it, but I will be getting on this first thing Tuesday morning when we go back into work. 

I would be working on this right now if I could. I'm glad I was on the right path though. I think once I sit down and really get plugging away at this, I should be able to get through it pretty reasonably. I'm excited to get to the "JS Side" of things and start learning something. I will make sure to keep everything alphabetical. And I will open a new PR Tuesday morning.

**Comment by bryevdv** [comment]
@jensencl Awesome FYI there's no hurry so please work at any pace that works for you :)

**Comment by jensencl** [comment]
@bryevdv @bokeh/dev

Bryan,
Below is a snip of what I currently have in the tables.py file. I tried to be as descriptive as possible and may have gone a bit overboard with the example and/or explanation. Please let me know what you think. I was getting started on creating the PR (pull request, right?). This is admittedly the first one I have done, so I want to make sure I do it right, I am trying to go by this guide: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request. Does this look right for how to do the PR? 

Thank you again for all the help. This is very helpful to me I am already learning a lot about Bokeh and everything I did not realize about it 'behind the scenes'.

![image](https://user-images.githubusercontent.com/60002857/72802222-47857900-3c19-11ea-8ef6-1dd794466c51.png)

**Comment by jensencl** [comment]
I also did a little digging in the package this morning and it looks like the JS file I am looking for might be located at: \bokehjs>build\js>bokeh-tables.js

Am I at least in the right neighborhood?

**Comment by bryevdv** [comment]
@jensencl That's a good resource for PRs, TLDR the basic steps are:

* fork repo
* clone forked repo locally
* make changes 
* push changes back to GH

Then you can open a PR from your fork. 

The helpstring is great. In general, the existing ones in the project are too short and would be better if they were more like yours. We will want to tweak some formatting but can discuss that in the PR.

For the other question: that is the final, built package file. You will need to update the original source module, which is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/widgets/tables/cell_formatters.ts

which looks more intimidating than it is. There is a *lot* of boilerplate you'll be able to basically copy and paste. We can talk more in the PR.
