### ISSUE TITLE
Breakpoint line renderer

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#959]
I would like a line renderer that takes three arguments, `x, y, breakpoints`.  Breakpoints is a series of x co-ordinates through which the line should be discontinuous.  NaNs in the X or Y series shouldn't result in line breaks,  only x-coordinates that occur in the breakpoints series.  

This gives me finer grained control over how to plot when data is actually None, vs NaN.  As I have mentioned previously, NaNs frequently occur when combining timeseries of different periodicities into a dataframe.  

This shouldn't be a hard renderer to write, and I can do it.  Would the bokeh team be interested in accepting a patch?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
