### ISSUE TITLE
How to update the Figure attributes (x_range) after the Figure is already created using bokeh 1.4 ?

### ISSUE THREAD

**Issue by Rajatsharma07** [bokeh/bokeh#9596]
# Figure Object already created
 lst_category= df['category'].unique()
p = figure(
                # I don't want to set x_range here, after 'p' is created
                # x_range=lst_category,
                title="Title",
                plot_height=800,
                plot_width=600,
                background_fill_color="#f9f9f9",
            )

p.x_range = lst_category # I want to do like this
Tried with:

p.x_range.factors = lst_category  # Not working
p.x_range=FactorRange(factors=lst_category)  # Not working

#################################################

 def generate_bar_chart(
        self,
        lst_category,
        lst_frequency,
        lst_colors,
        str_xlabel,
        str_ylabel,
        str_plot_title,
        plot_height=700,
        plot_width=800,
        width_bar=0.6,
    ):
        try:
            source = ColumnDataSource(
                dict(
                    x=lst_category,
                    values=lst_frequency,
                    color=lst_colors[:len(lst_category)],
                )
            )

            hover_tool = HoverTool(
                tooltips=[("Prod Order", "@x"), ("Frequency", "@values")]
            )

            p = figure(
                x_range=lst_category,  # I will comment this
                title=str_plot_title,
                plot_height=plot_height,
                plot_width=plot_width,
                background_fill_color="#f9f9f9",
            )
            p.add_tools(hover_tool)
            p.vbar(
                x="x",
                top="values",
                width=width_bar,
                source=source,
                line_color="#020B13",
            )
            p.y_range.start = 0
            p.x_range.range_padding = 0.2
            p.xaxis.axis_label = str_xlabel
            p.yaxis.axis_label = str_ylabel
            p.xaxis.major_label_orientation = 1.1
            p.outline_line_color = "#020B13"
            p.xaxis.major_label_text_font_size = "11pt"
            p.yaxis.major_label_text_font_size = "11pt"
            p.yaxis.axis_label_text_font_size = "11pt"
            p.xaxis.axis_label_text_font_size = "11pt"
            p.yaxis.axis_label_text_font_style = "bold"
            p.xaxis.axis_label_text_font_style = "bold"
            p.title.text_font_size = "20pt"
            show(p)
            return True
        except Exception as e:
            if hasattr(e, "message"):
                print(e.message)
            else:
                print(e)

**Comment by bryevdv** [comment]
Hi @Rajatsharma07, the GitHub issue tracker is reserved for bug reports and feature requests. For that general support or help with usage questions, please consider the [Project Discourse](https://discourse.bokeh.org).
