### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9597]
Although much better now, there are still a few flaky Selenium tests. Seems to be mostly some of the edit tool tests. It's possible the issue is down to explicit waits as it was in the case of other flaky tests.

**Comment by mattpap** [comment]
Commonly failing tests:

- Test_MultiChoice.test_server_on_change_round_trip_on_enter

**Comment by bryevdv** [comment]
We've got to do something about this sooner, even if it is just disabling some tests entirely for now.

**Comment by bryevdv** [comment]
Also the flaky BokehJS test

**Comment by mattpap** [comment]
> Also the flaky BokehJS test

There are specific issue already open for this. This issue is only about bokeh's integration tests.

**Comment by mattpap** [comment]
Old integration tests were removed in PR #13992.
