### ISSUE TITLE
[BUG] Bokeh server apps do not run with minified resources

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9611]
cc @mattpap 

Running any app with minified resources fails:

<img width="666" alt="Screen Shot 2020-01-26 at 3 46 05 PM" src="https://user-images.githubusercontent.com/1078448/73143781-0a731980-4053-11ea-9fc1-b6f594e27f98.png">

Setting `BOKEH_MINIFIED=no` allows the app to run. 

Have not had a chance to bisect yet.

**Comment by mattpap** [comment]
Works for me. Perhaps this is a platform specific issue with building bokehjs.

**Comment by bryevdv** [comment]
OK it didn't work before after an`npm install` and several rebuilds but ofc it's working now after an `npm clean` and rebuild.

**Comment by mattpap** [comment]
> it's working now after an npm clean and rebuild.

If you see weird behavior, then cleaning the build (or really invalidating the cache) is a quick way to fix things. However, it's interesting that it only affected minified resources. I suppose the cache invalidation logic is insufficient.
