### ISSUE TITLE
[BUG] `TypeError: u is undefined` occurred when using dataframe that contains `dict`.

### ISSUE THREAD

**Issue by yuji38kwmt** [bokeh/bokeh#9620]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
* Python 3.6.9
    * bokeh 1.4.0
    * pandas 0.25.3
* Xubuntu 18.04
* Firefox 71.0

#### Description of expected behavior and the observed behavior
I executed the following python code.

```python
import bokeh
import bokeh.plotting
import pandas

def plot_line(df: pandas.DataFrame, html_file:str):
    source = bokeh.plotting.ColumnDataSource(data=df)
    fig = bokeh.plotting.figure()
    fig.line(x="u", y="v", source=source)
    bokeh.plotting.reset_output()
    bokeh.plotting.output_file(html_file)
    bokeh.plotting.save(fig)

df_base= pandas.DataFrame({"u":[1,2], "v":[2,4]})
df_failure1 = df_base
d1 = {"a":1}
df_failure1["w"] = [d1, d1]
plot_line(df_failure1, "test_failure1.html")
```

#####  Expected behavior
The following  line graph is displayed on html file.
![image](https://user-images.githubusercontent.com/6350027/73416694-1adc0a80-4359-11ea-8896-4a5fbbeaf3c7.png)

#####  Observed behavior
Graph is not displayed on html file.
And error occurred on console of firefox.

#### Complete, minimal, self-contained example code that reproduces the issue
Please refer to  theabobe code.

#### Stack traceback and/or browser JavaScript console output
[](url)

```
TypeError: u is undefined bokeh-1.4.0.min.js:346:2235
    l https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:346
    decode_column_data https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:346
    initialize https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:320
    finalize https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:265
    _initialize_references_json https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:242
    o https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:242
    f https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:242
    _initialize_references_json https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:242
    from_json https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:242
    v https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:240
    embed_items https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js:240
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/6350027/73416893-9b027000-4359-11ea-8ae1-2e00b85ef13e.png)

#### Verification
I tried with changing cell type, and I verified wheather line graph is displayed.

```python
df_failure2 = df_base
# cell type is  List[Dict[str, int]]
df_failure2["w"] = [[d1,d1], [d1,d1]]
plot_line(df_failure2, "test_failure2.html")
# => fail

df_success = df_base
# cell type is  List[str]
df_success["w"] = [["a","b"], ["a","b"]]
plot_line(df_success, "test_success.html")
# => success
```

**Comment by bryevdv** [comment]
@yuji38kwmt dicts are not valid data values to put in a `ColumnDataSource`. CDS columns generally resolve to JS Typed arrays (i.e. they can only hold numbers), or lists of strings. Trying to expand the current capability to include dicts is not justifiable: 

* it would be difficult and time-consuming, as it would involve very low-level serialization machinery and therefor require extensive tests
* even with tests, changing low-level code always involves risk
* changing low level code paths may also  possibly adversely affects performance for *all* usage 
* there has be no perceptible demand for this (this is the first request in ~8 years)

**Comment by yuji38kwmt** [comment]
@bryevdv 
OK, I see.
But I don't understand why `TypeError: u is undefined` occurred.
Please print log message that dicts are not valid data values to put in a ColumnDataSource.

**Comment by bryevdv** [comment]
All of the examples in the docs only ever show numerical arrays, categorical factor values, or colors in CDS. I think we do a decent job in the docs of *implicitly* documenting what is not allowed, by doing a good job of explicitly documenting what *is allowed*. For something as rare as this I am more inclined to simply let this issue serve as the explanation in case anyone ever needs to search for it they will find this discussion.
