### ISSUE TITLE
[BUG] Bad document JSON data leads to a dangling promise returned by `pull_session`

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#9621]
Suppose I have created a document with a non-existing model. When the `pull_session` is called, I see these messages in the JS console:
```
[bokeh] Got an event for unknown model  {id: "1053", type: "LinearColorMapper"}
Document.apply_json_patch @ bokeh.js?v=1.3.4:8503
ClientSession._handle_patch @ bokeh.js?v=1.3.4:528
ClientSession.handle @ bokeh.js?v=1.3.4:477
(anonymous) @ bokeh.js?v=1.3.4:317
Promise.then (async)
ClientConnection._repull_session_doc @ bokeh.js?v=1.3.4:299
ClientConnection._awaiting_ack_handler @ bokeh.js?v=1.3.4:405
_current_handler @ bokeh.js?v=1.3.4:347
ClientConnection._on_message @ bokeh.js?v=1.3.4:365
_this.socket.onmessage @ bokeh.js?v=1.3.4:217
```
```
21:37:36.553 backend.js:6 Error: event model wasn't known
    at Document.apply_json_patch (bokeh.js?v=1.3.4:8504)
    at ClientSession._handle_patch (bokeh.js?v=1.3.4:528)
    at ClientSession.handle (bokeh.js?v=1.3.4:477)
    at bokeh.js?v=1.3.4:317
r @ backend.js:6
(anonymous) @ bokeh.js?v=1.3.4:338
Promise.catch (async)
ClientConnection._repull_session_doc @ bokeh.js?v=1.3.4:336
ClientConnection._awaiting_ack_handler @ bokeh.js?v=1.3.4:405
_current_handler @ bokeh.js?v=1.3.4:347
ClientConnection._on_message @ bokeh.js?v=1.3.4:365
_this.socket.onmessage @ bokeh.js?v=1.3.4:217
```
```
21:37:36.553 bokeh.js?v=1.3.4:339 [bokeh] Failed to repull session Error: event model wasn't known
(anonymous) @ bokeh.js?v=1.3.4:339
Promise.catch (async)
ClientConnection._repull_session_doc @ bokeh.js?v=1.3.4:336
ClientConnection._awaiting_ack_handler @ bokeh.js?v=1.3.4:405
_current_handler @ bokeh.js?v=1.3.4:347
ClientConnection._on_message @ bokeh.js?v=1.3.4:365
_this.socket.onmessage @ bokeh.js?v=1.3.4:217
21:40:08.999 
```

It's pretty clear what the culprit is in my particular case.
However, the issue in Bokeh is that in this case the promise returned by `pull_session` is never resolved or rejected. And it makes it seem like `add_document_from_session` is still busy.

The root cause, I believe, is that `ClientConnection._repull_session_doc` does not call any callback if it fails - it just logs the error and that's it.
The constructor of `ClientConnection` doesn't even have any such callback for errors not related to a closed connection.
It's not really related to the issue itself, but there's also some strange code that:
1. Uses both the 2-argument form of `Promise.then` and the `Promise.catch`, which makes no sense
2. Makes it possible to call `reject` after `resolve` has already been called

With that being said, this is probably a very low priority issue since only some specific errors can trigger it, and even then it's should be clear to the developer what to do. It's just that the custom error handling code that someone's app may rely on will never be called.

**Comment by mattpap** [comment]
I see this is bokeh 1.3.4. Can you try out most recent 2.0-dev if the issue persists? Recently almost all promise handling code was rewritten to use more manageable async/await syntax, so this problem should go away.

**Comment by p-himik** [comment]
`ClientConnection` has not been changed in a long time. The last change certainly predates 1.3.4. And apart from just observing the issue, I tried to understand what's going on using the latest master.
Either way, I have already assigned myself to this issue, so I'll check it when I start working on it.

**Comment by mattpap** [comment]
> ClientConnection has not been changed in a long time.

That's a good remainder that I forgot to push the relevant changes.

**Comment by p-himik** [comment]
@mattpap Should I wait for you to push something?

**Comment by mattpap** [comment]
@p-himik, unfortunately my changes weren't complete. I submitted a partial PR #9630. If you want to take it over and finish it, then go ahead.

**Comment by p-himik** [comment]
Is it OK to change `ClientConnection`'s interface? The class is exported but it's not documented, so it doesn't look like a part of the public API.

**Comment by bryevdv** [comment]
@p-himik we have not made any full promises about BokehJS API compatibility. That's probably Bokeh 3.0 territory. What we have said is that the range of usage in existing examples in the docs should continue to work. But we have not demonstrated `ClientConnection` in any way, so I'd say it's fair game (and even to mark as private in some way).

**Comment by mattpap** [comment]
> The class is exported but it's not documented (...)

Unfortunately pretty much everything has to be exported, e.g. to allow testing. Neither ES nor TypeScript have a good way (or any way at all) to declare visibility of module-level members properly. We are yet to figure out how to declare internal APIs effectively.

**Comment by p-himik** [comment]
@mattpap To check the changes in an actual environment, I need to install the changed Bokeh version.
So far I tried:
- Installing the Bokeh source directory a an editable Python package.
Doesn't work because it contains `.ts` files and the custom Bokeh models builder doesn't like that
- Building a conda package with `conda-build conda.recipe`.
For some reason, it contains only Python sources
- Running `python setup.py sdist` and installing the resulting archive.
Doesn't work because the archive also includes the `.ts` files for some reason
- Removing the `tree_ts` library from the archive.
Still doesn't work because apart from `types/document/document.d.ts` I for some reason also have `types/document.d.ts`, which has a different interface.

No idea how this all happens, seems like magic. Especially the part where I have two `document.d.ts` files with different contents.

Can you give my any pointers on how to actually build a Bokeh package properly? I couldn't find any documentation on it.

**Comment by p-himik** [comment]
Never mind that, I just had to manually remove `bokehjs/build`...

**Comment by mattpap** [comment]
> Removing the `tree_ts` library from the archive.

This indicates to me that you had a very old setup, so removing the build directory is the only way to go. The new bokehjs' build uses aggressive caching, which can cause weird behavior in some edge cases, so cleaning up the build (by removing it or running `node make clean`) can help in general, especially after a long absence from bokehjs development.
