### ISSUE TITLE
Add link to Jupyter chapter from Installation chapter

### ISSUE THREAD

**Issue by allefeld** [bokeh/bokeh#9623]
The [documentation](https://docs.bokeh.org/en/latest/docs/installation.html) does not mention that for JupyterLab, it is necessary to separately install an extension:

    jupyter labextension install @bokeh/jupyter_bokeh

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Packages installed with conda 4.7.11:
```
bokeh                     1.4.0                    py37_0    conda-forge
python                    3.7.6                h357f687_2    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
```

Debian 10.2, Chrome 79.0.3945.130

#### Description of expected behavior and the observed behavior

I discovered that the extension has to be installed separately when trying to run `examples/howto/notebook_comms/Jupyter Interactors.ipynb`. Without it, the figure is shown but the sliders are not functional. After performing the installation, it works. The documentation says that `conda install bokeh` is all that is necessary.

**Comment by bryevdv** [comment]
@allefeld This information is in a dedicated chapter for notebooks:

http://docs.bokeh.org/en/dev/docs/user_guide/notebook.html

Which has also recently been updated further (as yet unreleased). Note the URL for that chapter will change with Bokeh 2.0 to 

http://docs.bokeh.org/en/dev/docs/user_guide/jupyter.html 

to reflect a broader scope of information covered. 

We will add a link to there from the installation chapter.
