### ISSUE TITLE
bokeh.client.pull_session (RuntimeError: connection to server was lost)

### ISSUE THREAD

**Issue by laurentiupiciu** [bokeh/bokeh#9633]
Hello,

I'm trying to embed a bokeh application (server) that creates and renders a scatter plot into a flask application.
I followed the documentation found at https://docs.bokeh.org/en/latest/docs/reference/client/session.html and managed to do this for a 15K 2-dim points dataset. However, when I try to trigger the bokeh application from flask using a bigger dataset (30K points), I receive the following error (_RuntimeError: connection to server was lost_): [https://ibb.co/kmxsFpD](url)

**Comment by bryevdv** [comment]
There is a default max websocket size limit, your bigger dataset probably exceeds it. For discussing this usage question further, please use the Project Discourse:

https://discourse.bokeh.org/
