### ISSUE TITLE
Remove Black Formatting

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9636]
Black formatting is becoming increasingly common (and expected), improves diff performance, and is automatible under test, taking stylistic matters out of the realm of debate. It takes a little getting used to (but not that much).

**Comment by Ak-Bhatia** [comment]
@bryevdv  Can you please elaborate on this..

**Comment by Ak-Bhatia** [comment]
@bryevdv Sir, can you please elaborate on this.

**Comment by bryevdv** [comment]
Refers to:

https://black.readthedocs.io/en/stable/

However give the scale of changes that will land, this is a task only the core team will be able to execute.

**Comment by bryevdv** [comment]
Expanding on the benefits that doing this affords:

* Black formatting is structured explicitly to reduce diff noise 
* Fully automatable formatting removes formatting completely as a topic for discussion
* It is increasingly becoming a standard expectation on OSS python projects
* Sets clear and unambiguous expectations for contributors

"I don't personally love it" is not a sufficient reason to not do this. For that matter: *I, myself* don't personally love things about, but having now worked with codebases that employ it, I can say that it is easily get-used-to-able. It does not impede actual development work in any way. 

@mattpap I am happy to go about this either of two ways:

* rip the bandaid off, i.e. one big PR to do everything and turn on automation at once
* incrementally over time, in PRs here and there, turning on automation sometime later

I personally prefer option 1, as I think it is cleaner. But if you would prefer to have some time to adjust to this, I will proceed on the basis of option 2.

**Comment by Anthchirp** [comment]
fwiw: We maintain a project of a similar size (in terms of LoC) at https://github.com/dials/dials, and we [moved to black](https://github.com/dials/dials/commit/b1acc0de527b00b32ce88d37e1e54bef810a32c3#diff-8d777f385d3dfec8815d20f7496026dc) last year. There were also concerns: I myself was on the skeptical side as it takes away the freedom to do nice, manual matrix formatting which is so useful for scientific software - and a 2 space indent is much better anyway...

In hindsight moving to black was absolutely the right choice. It _significantly_ reduced the mental load when writing and reading code - especially when combined with a pre-commit setup that automatically fixes your code before committing. We also found a number of bugs that were previously hidden by our manual indentation. Having a single large commit in the history is somewhat annoying at first, but as time goes by this becomes less and less of an issue.

**Comment by bryevdv** [comment]
@bokeh/core I am raising the following proposal for a formal decision:

> Black formatting shall be applied and maintained on all Python code in the Bokeh organization. This will be completed for the 2.4 release. 

Please record your votes on this comment with 👍 / 👎 (@bokeh/core only)

I am setting a timebox for this until December 7th, at which point I will record the result below, with a screenshot of this comment. 

I believe I have made my affirmative case for this proposal above, but I am happy to expand on or discuss any specific tpopics further.

**Comment by bryevdv** [comment]
Also FYI there are currently two paths already under Black formatting, if anyone would like to take a look at what it looks like:

* https://github.com/bokeh/bokeh/tree/branch-2.3/release
* https://github.com/bokeh/bokeh/tree/branch-2.3/bokeh/sphinxext

**Comment by bryevdv** [comment]
I would also add one more reason to do this: We are having trouble turning on CI for Python 3.9 due to issues upgrading to isort 5, but isort 5 now has various profiles including one to work with black automatically.

**Comment by bryevdv** [comment]
@mattpap reminder that if you want to make a case against this, you have until Dec 7th.

**Comment by mattpap** [comment]
I'm not in favour of auto-formatting in general and black in particular. Even if I liked its output, I still would be against it. Black's output is far from ideal, but with line length set to a decent number, it's at least bearable to work with, and something I may get used to at some point. What I don't want to see, is a codebase that has lines broken for the sake of it, making it impossible for me to follow the logic. The way `release/` is set up, seems fine to me.

**Comment by bryevdv** [comment]
OK this has passed (see screenshots recorded below) 

> What I don't want to see, is a codebase that has lines broken for the sake of it, making it impossible for me to follow the logic.

As you note our long line length should produce acceptable results in most instances but I do plan on looking out for any trivial changes that make specific improvements even after formatting. 

<img width="392" alt="Screen Shot 2020-12-06 at 6 54 17 PM" src="https://user-images.githubusercontent.com/1078448/101304201-8f42ce00-37f4-11eb-807a-63b657af6257.png">

<img width="316" alt="Screen Shot 2020-12-06 at 6 54 23 PM" src="https://user-images.githubusercontent.com/1078448/101304204-923dbe80-37f4-11eb-89fb-6dc51a447f24.png">

**Comment by bryevdv** [comment]
After some experience observing Black development, and with breakage from a new update today, I have unfortunately reversed course on this. AFAIK Black development still have a good deal of churn leading to unnecessary changes. We could pin to a specific version, but that will eventually cause problems with conda installing in newer with new versions of Python. 

Most specifically, the decision on https://github.com/psf/black/issues/144 to apply to docstrings is, I think just fundamentally wrong. The right bargain to being extremely opinionated is that you have to also have very narrow focus, to reduce the risk of trampling on others. As I pointed out there, lots of tools have expectations around docstrings. My opinion is therefore that Black should do absolutely nothing, ever, with the contents of docstrings, which are *not code*. Black sholud stick to code. 

Given that they chose otherwise, and that their transformations are not stable, I will remove the current black testing on `release` and `sphinxext` and close this issue. 

I will remove the current black tests on `branch-2.3` and forward port.
