### ISSUE TITLE
Export fails on OSX

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9639]
As I noted in the issue about switching to chrome as the default, a long time ago, the default settings do not work on OSX because they use the wrong pixel ratio:

![iris](https://user-images.githubusercontent.com/1078448/74006088-80b72c00-492f-11ea-9e5f-4715ddc80b74.png)

**Comment by bryevdv** [comment]
I guess a bigger question is: why are these tests passing on the macos builds on GH CI? Becasue all the chromium export tests fail locally for me.

**Comment by bryevdv** [comment]
Here is the relevant issue (that was not referenced by the PR for some reason) https://github.com/bokeh/bokeh/issues/8176

**Comment by bryevdv** [comment]
Tho, I am guessing this is happening with FF (so, both) if that is the default? 

BTW ` /Applications/Google\ Chrome.app/Contents/MacOS/` is not going to be on anyone's path. You will need to search for `Google Chrome` at that absolute path.

**Comment by mattpap** [comment]
There are explicit tests for both browsers, i.e. Chromium/Chrome and Firefox, so there is no way you will get let's say Firefox tested twice, though how exactly those tests will fail is a different matter. There is also a default test, so if Chromium/Chrome can't be found on your system, you will be notified. In general, I need test output to have a chance at understanding what's going on, especially it looks like there are multiple issues happening at the same time.

**Comment by mattpap** [comment]
The tests didn't catch the difference in pixel ratio, because they disable hidpi transform to have any chance at working across platforms, especially within the confines of unit testing. It's also not clear to me what to expect in terms of pixel ratio on headless systems. We are currently not set up at all to catch such issues. Within the recent work on bokehjs testing, I've been experimenting with performing testing with explicit device metrics (resolution, pixel density, etc.) with chrome's devtools protocol. Though that would have to be generalized, to make it available for io.export testing.

**Comment by bryevdv** [comment]
> In general, I need test output 
```
[08:39:36] Finished 'test:size' after 693 ms
[08:39:36] Starting 'test:start:headless'...
[08:39:36] Failed 'test:start:headless' after 4 ms
[08:39:36] Starting 'test:start:server'...
listening on 127.0.0.1:5777
[08:39:38] Finished 'test:start:server' after 1.73 s
[08:39:38] Starting 'defaults:generate'...
[08:39:39] generate_defaults.py: Wrote models_defaults.json with 179 model classes
[08:39:39] generate_defaults.py: Wrote widgets_defaults.json with 23 model classes
[08:39:39] Finished 'defaults:generate' after 1.27 s
[08:39:39] Starting 'test:compile'...
[08:39:43] Finished 'test:compile' after 3.97 s
[08:39:43] Starting 'test:unit:bundle'...
[08:39:48] Finished 'test:unit:bundle' after 5.07 s
[08:39:48] Starting 'test:integration:bundle'...
[08:39:49] Finished 'test:integration:bundle' after 44 ms
[08:39:49] failed: task 'test' failed
[08:39:49]     at _run (/Users/bryan/work/bokeh/bokehjs/make/task.ts:134:26)
[08:39:49]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

That's it.

Also FYI there is some flakiness in using chromium an CI, just restarted a test with this
> E       selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
E         (chrome not reachable)
E         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by mattpap** [comment]
>  selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally

I saw this in some PRs as well. I presume it's selenium or the driver having an issue, because otherwise I didn't have a single problem with starting chrome/chromium when doing things outside of selenium.
