### ISSUE TITLE
Selection by query

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#965]
Thinking again about my histogram example.  It seems inefficient to have to draw as many boxes as there are points on the scatter.  Could there be some way of saying "When a quad is selected, select every scatter point that has a matching rank property".  I'm sure there is a better way of stating this, but imagine these quads
```
{x1:1, x2:2, y1:0, y2:10, rank:1},
{x1:2, x2:3, y1:0, y2:30, rank:2},
{x1:3, x2:4, y1:0, y2:20, rank:3},
```
and these scatter points
```
{x:0, y:3, rank:1},{x:1, y:30, rank:3},{x:2, y:30, rank:3},{x:3, y:13, rank:2},{x:4, y:15, rank:2},
```
when quad `{x1:3, x2:4, y1:0, y2:20, rank:3}` is selected, scatter points `{x:1, y:30, rank:3},{x:2, y:30, rank:3}` should also be selected.

**Comment by birdsarah** [comment]
@paddymul - you could now do this with the selection callback. can we close?

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
