### ISSUE TITLE
[BUG] Undocumented API removals in 2.0

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#9651]
Currently trying to update the HoloViz stack to bokeh 2.0 compatibility and running into some undocumented deprecations:

* `bokeh.io.create_webdriver` removed (see https://github.com/bokeh/bokeh/pull/9331#discussion_r376234181)
* `bokeh.plotting.helpers` removed
* `AbstractButton` clicks property removed

I'll keep adding to these as I encounter these.

Reference: https://docs.bokeh.org/en/dev/docs/releases.html#api-removals

**Comment by bryevdv** [comment]
Also need to mention `app_hooks.py` as preferred new server hooks file location (and update docs)
