### ISSUE TITLE
Task - convert deps.py to requirements.txt and environment.yml

### ISSUE THREAD

**Issue by crdietrich** [bokeh/bokeh#9652]
The goal would be to have single install files using conda and pip, with a minimum of extra install steps.  There would still need to be a script to generate these two from meta.yml, possibly deps.py.  Also, this might simplify the commands across OSX/Linux/Windows.

Referencing the install commands, convert the current installation method (linux bash example):    
```
conda install `python scripts/deps.py build run test`
```
to using something like:  
```
conda install environment.yml
```
or   
```
pip install requirements.txt
```

**Comment by bryevdv** [comment]
The idea here would be to change `deps.py` to generate these files (which would then get checked in) and then add a test to make sure that the files are kept up to date with the `meta.yaml` source of truth. That should make getting set up and running for dev more "normal" and similar to the typical python experience.

**Comment by jeremy9959** [comment]
Actually I have one other question on this general topic.  When I wanted to test my proposed new code I needed to use version 1.4 of bokeh.  The bokeh repo master branch comes in at the cutting edge. I checked out v1.4.0 so that was ok but I'm not sure if that's the correct approach for contributing in other ways.  I wonder if there's a place where I can read about the right git protocol for contributing to a big complicated project like this one?

**Comment by bryevdv** [comment]
Well, a couple of comments:

* We generally only have one line of development off master. With a few exceptions, we are just not resourced to be able to support mulitple lines of development at once. 
* So if you are looking to add a new feature or  bugfix you should generally always be working against a recent branch off latest master
* If you are asking about how to use latest BokehJS versions, one way is to set `BOKEH_RESOURCES=inline` which will use a locally built BokehJS. Or you can run `bokeh static` and set `BOKEH_RESOUCES="server" (I think) which will also serve a locally built BokehJS

**Comment by mattpap** [comment]
I think this was resolved by introduction of `ci/environment-*.yml` files (PR #10058).
