### ISSUE TITLE
[FEATURE] Iterate over submodels of a model and draw submodel graph

### ISSUE THREAD

**Issue by jeremy9959** [bokeh/bokeh#9654]
It would be useful to be able to iterate over the submodel structure of a given bokeh model,
and to view the submodel graph, both a way to better understand how bokeh is put together and to more efficiently manipulate attributes of submodels.

I have a proposed solution that constructs a networkx DiGraph of submodels and displays it in a bokeh graph using the graph rendering tools. 

I showed this in the [discourse showcase](https://discourse.bokeh.org/t/revealing-the-structure-of-a-bokeh-model/4685) and this issue follows up on a discussion there with @bryevdv.  This issue is going to be associated with  a PR very soon.

**Comment by jeremy9959** [comment]
I rethought my approach to this and have resolved some problems in situations where the model used JS callbacks.    The improved version is demonstrated here:
- [Bokeh Model Interactive Graph](https://jeremy9959.net/structure_graph.html). 
 
I closed the earlier PR and can reopen one if you think it worthwhile.

**Comment by bryevdv** [comment]
Marking this as `completed` any follow on work welcome but let's make new issues!
