### ISSUE TITLE
File Import Not Working

### ISSUE THREAD

**Issue by peteribanks** [bokeh/bokeh#9656]
Hello, 

I'm trying to learn how to use bokeh and I've run into a problem. When using Bokeh in a jupyter notebook all of the widgets work with the exception of 'FileInput'. When I run the code from the documentation shown below. 

from bokeh.io import output_file, show
from bokeh.models.widgets import FileInput

output_file("file_input.html")

file_input = FileInput()

show(file_input)

I get the following error. 

ImportError: cannot import name 'FileInput' from 'bokeh.models.widgets' (/anaconda3/lib/python3.7/site-packages/bokeh/models/widgets/__init__.py)

if someone can help me figure out what's going on I would appreciate it!

Thank you in advance! :)

**Comment by bryevdv** [comment]
That most likely means that your installed version of Bokeh is too old. In the future, please use the Project Discourse for support/usage questions.

https://discourse.bokeh.org/
