### ISSUE TITLE
[BUG] Can't update vbar plot with categorical data

### ISSUE THREAD

**Issue by gbei93** [bokeh/bokeh#9664]
I am running a Bokeh server, and I would like to have a figure with a bar plot that display categorical data where:
 * the plot is empty at the beginning
 * as a consequence of some user actions, bars can be added to the plot (one at time)

Note that the data required to compute the height of each bar depends on the user input, so it's not possible to load all data at once.

I tried to implement the updating process by selecting a `source` for the `vbar` and then updating it in the callbacks, but it seems that this process does not work with categorical data. 

In the minimal working example below I applied the same procedure to some random numerical data and some random categorical data. The first one works flawlessly, while the second one is stuck with an empty figure. 

```python
import string
import pandas as pd

from bokeh.layouts import column
from bokeh.models import Button, ColumnDataSource, FactorRange
from bokeh.plotting import figure
from bokeh.server.server import Server

nr_of_points = 0
initial_df = pd.DataFrame(columns=['x', 'y'])

cdf_circles = ColumnDataSource(initial_df)
cdf_bars = ColumnDataSource(initial_df)

fig_circles = figure()
# I have tried to initialize x_range in different ways but I had no luck
fig_bars = figure(x_range=FactorRange(factors=[]))


def add_point():
    df = pd.DataFrame(
        {
            'x': list(range(nr_of_points)),
            'y': list(range(nr_of_points))
        })
    cdf_circles.data = ColumnDataSource(df).data


def add_bar():
    df = pd.DataFrame(
        {
            # it produces a list like ["a", "ab", "abc"...]
            'x': [string.ascii_lowercase[0:i+1] for i in range(nr_of_points)],
            'y': list(range(nr_of_points))
        })
    # I have tried with and without this line
    fig_bars.x_range = FactorRange(factors=list(df['x']))
    cdf_bars.data = ColumnDataSource(df).data


def update_plots():
    global nr_of_points
    nr_of_points += 1

    add_point()
    add_bar()


def main(doc):
    button = Button(label='Update plots')
    button.on_click(update_plots)
    fig_circles.circle(source=cdf_circles, x='x', y='y')
    fig_bars.vbar(source=cdf_bars, x='x', top='y', width=0.9)
    doc.add_root(column(button, fig_circles, fig_bars))


if __name__ == '__main__':
    port = 5006
    print(f'Opening Bokeh application on http://localhost:{port}/')
    server = Server({'/': main}, num_procs=1, port=port)
    server.start()
    server.io_loop.start()


```
The screenshots show what happens after each time the button is pressed.
![step0](https://user-images.githubusercontent.com/56308292/74543723-309b2380-4f46-11ea-9d8c-2da3ccb35cc9.png)
![step1](https://user-images.githubusercontent.com/56308292/74543725-3133ba00-4f46-11ea-9a9e-b5b4985d9eb4.png)
![step2](https://user-images.githubusercontent.com/56308292/74543727-31cc5080-4f46-11ea-86f6-ae52965877bf.png)
![step3](https://user-images.githubusercontent.com/56308292/74543728-3264e700-4f46-11ea-8f24-6cac84a86835.png)

No error message is shown.

My configuration:
* Python 3.6.8
* Pandas 0.23.4
* Bokeh 1.4.0
* Ubuntu 18.04
 
The described behavior occurs with both Google Chrome 77.0.3865.90 and Firefox 72.0.2.

**Comment by bryevdv** [comment]
@gbei93 this seems like a support question (there are definitely some usage issue with the code as-is) I am happy to discuss but we should start on the Discourse. We can re-open if there is determined to be any specific action to take.

https://discourse.bokeh.org/

**Comment by gbei93** [comment]
Ok, I managed to make it work by following pointers I found on Discourse, thank you very much for your prompt answer. 
In case someone has the same problem in future: https://stackoverflow.com/questions/44491172/how-to-draw-categorical-bar-plot-using-vbar-method-in-bokeh-plotting-module
