### ISSUE TITLE
Add an option to glyph to make it non-selectable

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#967]
If I wanted to overlay a histogram on top of a scatter plot, it would be useful to be able to select on the histogram glyphs, and have that show up on the scatter glyphs.  Currently, the selection area would need to include the relevant scatter and histogram glyphs for anything to be selected.

Also consider the case where you have a column data source with columns `x, IBM, AAPL`.  If you have two scatter renderers on the same plot, one for (x, IBM), the other for (x, AAPL), a point only is selected if both IBM and AAPL for that x value are in the selection box.  I'm not sure if this is desired behavior or not.

**Comment by bryevdv** [comment]
Closing this as a`discussion` Selection tools can now be configured on a per-glyph basis, and linking selection behaviours across different plots or data sources has been demonstrated in the examples with CustomJS callbacks.
