### ISSUE TITLE
[BUG] Spinner error for steps <= 1e-7

### ISSUE THREAD

**Issue by xavArtley** [bokeh/bokeh#9672]
In javascript to get the number of significative digits we use the toString function on the step value.
It works well as long as the step is >= 1e-6 since :
```
Number(1e-6).toString()
```
return "0.000001"
However
```
Number(1e-7).toString()
```
return "1e-7" and all the logic of the function
https://github.com/bokeh/bokeh/blob/28f9226dee9d0895b84c5e86574fc215228a1bea/bokehjs/src/lib/models/widgets/spinner.ts#L9-L13

failed.
Solution is to replace
https://github.com/bokeh/bokeh/blob/28f9226dee9d0895b84c5e86574fc215228a1bea/bokehjs/src/lib/models/widgets/spinner.ts#L11
by:
num.toFixed(16).replace(/\.?0+$/,"").split(".")[1].length

Moreover some checks on the minimal value handle by step must be added (1e-16)

I'll open a PR later to fix this bug

**Comment by bryevdv** [comment]
@xavArtley  Please test with a 2.0 Dev build.  The slider implementation was replaced with a new one that does not use strong munging at all.
```
conda install -c bokeh/c/dev bokeh
```

**Comment by xavArtley** [comment]
@bryevdv I don't understand the link with the slider implementation?

**Comment by bryevdv** [comment]
@xavArtley sorry disregard, I mis-read on my phone.
