### ISSUE TITLE
What should I do if I want to embed bokeh in Django? And it can update the document

### ISSUE THREAD

**Issue by yanwencheng** [bokeh/bokeh#9674]
The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).
What should I do if I want to embed bokeh in Django? And it can update the document

**Comment by birdsarah** [comment]
The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org/).
