### ISSUE TITLE
JS NaN to Python ??? in Range1D

### ISSUE THREAD

**Issue by JosephCottam** [bokeh/bokeh#968]
The multi-line renderer initializes some ranges to have a start and end of NaN.  When using server-side downsampling, these get represented in python Range1D as something other than NaN.  The type of the value is Either(DateTime, Float).  In this configuration, it deserialized to a DateTime with a value of today.  Flipping it to Either(Float, DateTime) it deserialized to None instead of NaN.  

Is there a reason behind this behavior? (Or is it a bug.)

I suggest that NaN always deserializes to Float (if present), regardless of order in the Either.  If note, DateTime should deserialize NaN to None and Float should deserialize it to NaN.

**Comment by bryevdv** [comment]
@JosephCottam @mattpap is there more to discuss? to change?
