### ISSUE TITLE
[BUG] Bokeh server + Flask on Rasp Pi - Failed to load resource: net::ERR_CONNECTION_REFUSED - autoload.js

### ISSUE THREAD

**Issue by BitKnitting** [bokeh/bokeh#9683]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
- bokeh: 1.4.0
- OS: Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
- browser: From Mac OS - Brave (Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit))
- flask: 1.1.0

#### Description of expected behavior and the observed behavior

My code works on the Mac.  Connection refused to autoload.js on Raspberry Pi.

#### Complete, minimal, self-contained example code that reproduces the issue

```
@app.route('/', methods=['GET'])
def bkapp_page():
    script = server_document('http://localhost:5006/bkapp')
    return render_template("interactive.html", script=script, template="Flask")


def bk_worker():
    # Can't pass num_procs > 1 in this configuration. If you need to run multiple
    # processes, see e.g. flask_gunicorn_embed.py
    # server = Server({'/bkapp': make_interactive}, io_loop=IOLoop(),
    #                 allow_websocket_origin=["0.0.0.0", "127.0.0.1"])
    server = Server({'/bkapp': make_interactive}, io_loop=IOLoop(), address='0.0.0.0',
                    port=5006, allow_websocket_origin=["0.0.0.0", "127.0.0.1"])
    server.start()
    server.io_loop.start()


Thread(target=bk_worker).start()

if __name__ == '__main__':
    print('Opening single process Flask app with embedded Bokeh application.')
    print('The bokeh docs discuss this at')
    print('https://docs.bokeh.org/en/latest/docs/user_guide/server.html#embedding-bokeh-server-as-a-library')
    app.run(host='0.0.0.0', port=8000, debug=True)

```

![image](https://user-images.githubusercontent.com/5501704/74674964-581d0680-5167-11ea-8579-a4e13728526f.png)

**Comment by bryevdv** [comment]
@BitKnitting if you are trying to access a Bokeh server embedded in another remote page, you will need to configure the Bokeh server to allow websocket connections from whitelisted origins. Happy to discuss, but the appropriate venue for support questions is the Project Discourse:

https://discourse.bokeh.org/

**Comment by BitKnitting** [comment]
@bryevdv - thank you.  [here is my support question on discourse](https://discourse.bokeh.org/t/bokeh-server-flask-on-rasp-pi-failed-to-load-resource-net-err-connection-refused-autoload-js/4744)
