### ISSUE TITLE
[BUG] bokeh (html|png|svg) commands all broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9687]
Trying to use any of them:
```
bokeh html iris.py
ERROR: OutputDocumentFor expects a sequence of Models
```
I tried several mods to get working (e.g. passing a list to `show` in the script) but nothing got it running. AFAIK these have been broken a fairly long time and no one noticed until just now. I'd like to propose just removing them for 2.0. This direction of usage was never promoted and never took off. I'd personally support jettisoning dead code now for 2.0, sooner rather than later. 

Thoughts @bokeh/dev

**Comment by mattpap** [comment]
> ERROR: OutputDocumentFor expects a sequence of Models

This shows also another failing, very common to CLI tools written in scripting languages. This error is not a usage error, which would prompt a concise error message without a traceback. This, however, is an internal error indicating a bug and should have been displayed in full. Usage errors should use a custom error class and should be caught by the CLI, and everything else should display unaltered. Usually it's one extreme or the other. A good example of the other extreme was conda, though it improved greatly recently.

**Comment by mattpap** [comment]
> ERROR: OutputDocumentFor expects a sequence of Models

This error message is also misleading, because it got a sequence of models, just an empty one. This was confusing, because all the relevant code is already statically typed and sound as far as types of objects being passed around are concerned.

**Comment by mattpap** [comment]
This was broken in 1.0. I think this is a nice feature, but if no one noticed this regression in such a major release and since that release until today, then it should go.

**Comment by jbednar** [comment]
I did try to use this feature a couple of months ago, but I was in a hurry, thought I was doing something wrong, and found another way. I don't think I even looked in the manual to see if something like that _was_ supported; I just tried it and thought that it might work.  So I guess that's a weak vote to keep it, i.e. that I expected it to work or half-remembered that it would work, as well as a weak vote to remove it, i.e. that I wasn't particularly concerned when it didn't work.

**Comment by bryevdv** [comment]
OK we seem to be +3.5 for removing so I will switch this to a `task` and try to take care of it today. 

@mattpap your reporting suggestions sound good, I'd suggest an issue so they are not lost/forgotten

**Comment by bryevdv** [comment]
BTW I also *personally* thought this was a nice feature, but my experiences with users is that everyone expects and wants to just run "plain python" scripts and that these therefore are mostly just confusing.

**Comment by numeric-lee** [comment]
@bryevdv   any luck fixing #9687?   Still getting the same result
bokeh = 2.2.1.  export_png

    ValueError: OutputDocumentFor expects a sequence of Models

Is there an alternative approach which works?

**Comment by bryevdv** [comment]
@numeric-lee This is a different issue concerning old command line tools (that have since been entirely removed). The export functions including `export_png` are maintained under continuous test, so if you are having some issue, I would suggest first asking a detailed, complete question on the discourse: https://discourse.bokeh.org
