### ISSUE TITLE
Link to Discourse from github issues

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#9690]
When opening a new issue at https://github.com/bokeh/bokeh/issues/new/choose, a user is presented with options for bug report, feature request, or blank issue:

![image](https://user-images.githubusercontent.com/1695496/74854256-b7644d80-5304-11ea-92d9-472ad4aeed76.png)

I've recently set up the HoloViz org to replace the blank-issue link with a link to Discourse (see https://github.com/holoviz/.github/pull/2 for discussion):

![image](https://user-images.githubusercontent.com/1695496/74854367-db279380-5304-11ea-9bd0-90d53e5b289d.png)

This seems like an appropriate approach for Bokeh as well -- send people to Discourse for anything other than bug reports or feature requests. To make it concrete, I'll open a PR for what I think will work for Bokeh.

**Comment by bryevdv** [comment]
I was not aware of this feature. Can you point to docs for it? (Or make a PR!)

**Comment by jbednar** [comment]
Thanks for merging; looks like it works!

![image](https://user-images.githubusercontent.com/1695496/74855654-97ce2480-5306-11ea-90f2-33ec2c13617b.png)
