### ISSUE TITLE
[BUG] Add click_policy='show' to Legend to show the corresponding glyph and hide others

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#9696]
Consider the plot as on image below showing price history for vacations in Dominican Republic. There are 38 lines (hotels) on the plot so I have to click **37 times** to hide them all and clearly see the price history for the very one hotel I am interested in e.g. RIU Bambu.

Adding `click_policy=show` to the current set of ['none', 'hide', mute] will make it much easier to select only the interesting glyphs on the plot.

An option could be added to use CTRL or CMD to select more glyphs while keeping others hidden.

See also [this question on stackoverlow](https://stackoverflow.com/questions/60145543/hovering-over-the-legend-will-hide-all-lines-except-the-corresponding-line/60311410?noredirect=1#comment106686615_60311410)

![Screenshot 2020-02-20 at 11 33 12](https://user-images.githubusercontent.com/10279903/74926221-d848a380-53d5-11ea-8b42-1e14e2bb1707.png)

![Screenshot 2020-02-20 at 11 34 07](https://user-images.githubusercontent.com/10279903/74926241-e0084800-53d5-11ea-91f6-7d8ec1ec0e6e.png)

This is how would it look like in one possible solution:

![](https://i.stack.imgur.com/qWoLO.gif)

**Comment by bryevdv** [comment]
@tony-bony I agree this is a good feature and would like to do something around it (or help someone work on it) but this is already under discussion in https://github.com/bokeh/bokeh/issues/8841 so closing this as a duplicated.

**Comment by bryevdv** [comment]
I've re-posed the main blocking question in the other issue, in case you have thoughts.
