### ISSUE TITLE
[BUG] DateRangeSlider is broken

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#9702]
### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.0.0dev6 (ff2d2f62)

#### Description of expected behavior and the observed behavior
If `start` is set to today, the slider is not displayed at all. The JS exception:
```
Error rendering Bokeh items: TypeError: Cannot read property '0' of null
    at nouislider.js:298
    at Array.sort (<anonymous>)
    at new Spectrum (nouislider.js:298)
    at Object.testRange [as t] (nouislider.js:392)
    at nouislider.js:711
    at Array.forEach (<anonymous>)
    at testOptions (nouislider.js:703)
    at Object.initialize [as create] (nouislider.js:1770)
    at DateRangeSliderView.render (abstract_slider.js:105)
    at DateRangeSliderView.build (layout_dom.js:119)
```
It's caused by the `start` value being `null` on the JS side. The relevant `attributes` value in the `PULL-DOC-REPLY` message:
```
{end: 1583107200000, value: ["2020-02-21", "2020-03-02"]}
```

If `start` is set to any other day, the slider is displayed, but incorrectly - it doesn't depict the actual range. There's only one handle at the very start. Any attempt to move it leads to the displayed value set to
```
function () { return request.convert(arguments); } .. function () { return request.convert(arguments); }
```
and the exception:
```
ValueError: expected an element of Tuple(Datetime, Datetime), got (None, None)
```
It's caused by an incorrect update to the `value` field. One of the corresponding WS messages:
```
{"events":[{"kind":"ModelChanged","model":{"id":"1041"},"attr":"value","new":[null,null]}],"references":[]}
```

#### Complete, minimal, self-contained example code that reproduces the issue
```python
from datetime import date, timedelta

from bokeh.io import curdoc
from bokeh.models import DateRangeSlider

start = date.today() - timedelta(days=1)
end = start + timedelta(days=10)
beginning = DateRangeSlider(value=(start, end), start=start, end=end)

curdoc().add_root(beginning)
```

**Comment by bryevdv** [comment]
@p-himik  any idea when  this broke or what change caused it? I thought we had integration tests on date slider but apparently not.

**Comment by p-himik** [comment]
Not a clue. I just did a quick check for a SO question and found out that it works on 1.4.0 but fails on 2.0.0dev6.
Yeah, there are only Python tests for the slider.

**Comment by bryevdv** [comment]
OK, if you have a chance to do any sort of bisection that'd be helpful otherwise I will try to dig in to it tonight.

**Comment by p-himik** [comment]
I'll try to do some bisecting - a good opportunity to actually use `git bisect` for the first time. :)

**Comment by bryevdv** [comment]
`git bisect` is a great tool, I literally always refer back to this page every time I need to use it though http://webchick.net/node/99

**Comment by p-himik** [comment]
Yeah, that's the resource I used.

Why did you change `Date` to `Datetime` here? https://github.com/bokeh/bokeh/commit/16d3d0ef

**Comment by bryevdv** [comment]
Because `Date` is now an unambiguous ISO date string, not a timestamp. That change was to put a finished to the endless years of time zone issues that plagued the date picker. But `DateRangeSlider` has always expected a timestamp, so it could not be `Date` any longer. I did check `DateRangeSlider` at some points during that PR, but maybe there were issues I missed with the change.

**Comment by p-himik** [comment]
Hmm. Now it seems strange that we have a **Date**RangeSlider but it accepts datetimes.
From the API standpoint, I think it would make sense to have both `DateRangeSlider` and `DatetimeRangeSlider`. But that's a separate matter.

Another question - is this really a desired thing to make this function return a number instead of an instance of `datetime`? https://github.com/bokeh/bokeh/blob/03618bf8a6233303574e846d70a238f891a1a93a/bokeh/util/serialization.py#L134-L144

**Comment by bryevdv** [comment]
> Now it seems strange that we have a DateRangeSlider but it accepts datetimes.

I don't disagree, getting the new DatePicker working with minimal other change was all I had bandwidth for. Though I think "DateRangeSlider" has generally been implicitly understood to be a range slider for full date times (and afaik that is how people use it). I think really cleaning this up is probably Bokeh 3.0 territory at this point though, we should just get the previous functionality working again. 

>  is this really a desired thing to make this function return a number instead of an instance of datetime?

Practically speaking that's a totally internal function if you want to rename it to `convert_date_to_datetime` to `convert_date_to_timestamp` that's fine with me.

**Comment by p-himik** [comment]
> I think really cleaning this up is probably Bokeh 3.0 territory

Agree. To be honest, I hate handling anything time-related at all, so if nobody complains about it I'd leave it as is.

> if you want to rename it [...] that's fine with me

Sorry, I didn't make it clear enough. All the other functions that convert input values for `Datetime` do return an instance of `datetime`.
And indeed, changing the function to return just `dt.datetime(*obj.timetuple()[:6])` seems to fix the issue.

**Comment by bryevdv** [comment]
> And indeed, changing the function to return just dt.datetime(*obj.timetuple()[:6]) seems to fix the issue.

Well, that change is fine too though I would expect some other changes are necessary? Or is this function just not being used anywhere at all?

**Comment by bryevdv** [comment]
This function is used to confirm that the `Datetime` property properly transforms to a timestamp:

https://github.com/bokeh/bokeh/search?utf8=✓&q=convert_date_to_datetime&type=

So if we change it we would also need to add back a timestamp version and have the test use that.

**Comment by p-himik** [comment]
Not sure whether it affects TZ issues in any way though.
The current implementation also seems shaky w.r.t. TZs. We accept a proper `datetime` but strip away any TZ information and just send away a float, and receive a float.
But that's just voicing a concern, nothing more - as I mentioned, I'm happy to not have to touch it. :)

Speaking of which - do you mind if I offload this to you? Playing Miss Marple is fun right until the archenemy named timezones appears. And you at least seem to know and remember a lot more about the background of this than I do.

**Comment by bryevdv** [comment]
Sure, FYI we try to be tz-naive i.e. treat all datetime values as local and leave it to users to convert as necessary for what they want to show. The issue with the old date picker was that we could not prevent a conversion that it did internally which really mucked with that assumption.

**Comment by bryevdv** [comment]
@p-himik I actually can't reproduce any issue with your code on my laptop with master (with either `today` or "today-1") can you add more detail about platform, etc?

**Comment by bryevdv** [comment]
FYI Here is the updated test script I am using:
```
from datetime import date, timedelta, datetime

from bokeh.io import curdoc
from bokeh.models import DateRangeSlider

start = date.today() # - timedelta(days=1)
end = start + timedelta(days=10)
beginning = DateRangeSlider(value=(start, end), start=start, end=end)

def callback(attr, old, new):
    print(beginning.value_as_date)
beginning.on_change('value', callback)

curdoc().add_root(beginning)
```
It always prints out the expected console output and I am not seeing any errors there or in the browser.

**Comment by p-himik** [comment]
Wait, WTH just happened? Now it works for me as well, both for the current master and for the branch mentioned in the beginning!
I now always remove the `bokehjs/build` directory before building BokehJS. And I did `git bisect`, and I could reproduce it _all the time_ after your commit that replaced `Date` with `Datetime`.

Magic. Love me some reverse schroedinbugs.

FWIW, I'm on Ubuntu 19.10, latest Google Chrome.

**Comment by p-himik** [comment]
Phew, false alarm - no magic here. I'm sleepy and I forgot that I replaced `date.today()` with `datetime.now()` to test something else.

Still breaks for me. Your code is breaking for me as well.
When you tried to reproduce it, did you make sure that the built BokehJS is in sync?

**Comment by bryevdv** [comment]
@p-himik Weird/annoying: my env path was wrong. I think there is a bug in conda deactivate (I deactivated from "140" env to "dev" env  and path ended up on base env...) I can repro now

**Comment by p-himik** [comment]
Heh, I hit a similar issue while bisecting. It seems I had used `python setup.py install` at some point, which made me always use some random Bokeh version.

**Comment by bryevdv** [comment]
OK I have a handle on this. It basically boils down to value being a tuple, and container properties not being careful to transform their contained values, so the tuple of actual date objects hits the JSONEncoder, which serializes date objects as ISO string. I will have to think a bit about the best/minimal way to resolve this. I should possibly d have a PR tomorrow but possibly not until the afternoon.

**Comment by bryevdv** [comment]
@p-himik  if you have a chance, here is a diff you could try out
```
diff --git a/bokeh/core/property/container.py b/bokeh/core/property/container.py
index 9907784d8..97249ac5c 100644
--- a/bokeh/core/property/container.py
+++ b/bokeh/core/property/container.py
@@ -299,9 +299,17 @@ class Tuple(ContainerProperty):
                 msg = "" if not detail else "expected an element of %s, got %r" % (self, value)
                 raise ValueError(msg)

+    def serialize_value(self, value):
+        ''' Change the value into a JSON serializable format.
+
+        '''
+        return tuple(typ.serialize_value(x) for (typ, x) in zip(self.type_params, value))
+
     def _sphinx_type(self):
         return self._sphinx_prop_link() + "( %s )" % ", ".join(x._sphinx_type() for x in self.type_params)

+
+
 class RelativeDelta(Dict):
     ''' Accept RelativeDelta dicts for time delta values.

diff --git a/bokeh/core/property/datetime.py b/bokeh/core/property/datetime.py
index da56b6388..e9f901985 100644
--- a/bokeh/core/property/datetime.py
+++ b/bokeh/core/property/datetime.py
@@ -86,7 +86,7 @@ class Datetime(Property):

     '''

-    def __init__(self, default=datetime.date.today(), help=None):
+    def __init__(self, default=None, help=None):
         super().__init__(default=default, help=help)

     def transform(self, value):
@@ -96,7 +96,7 @@ class Datetime(Property):
             value = dateutil.parser.parse(value)

         elif Datetime.is_timestamp(value):
-            value = datetime.date.fromtimestamp(value)
+            value = datetime.date.fromtimestamp(value/1000)

         # Handled by serialization in protocol.py for now, except for Date
         if isinstance(value, datetime.date):
@@ -107,6 +107,9 @@ class Datetime(Property):
     def validate(self, value, detail=True):
         super().validate(value, detail)

+        if value is None:
+            return
+
         if is_datetime_type(value):
             return

@@ -126,6 +129,14 @@ class Datetime(Property):
         msg = "" if not detail else f"Expected a date, datetime object, or timestamp, got {value!r}"
         raise ValueError(msg)

+    def serialize_value(self, value):
+        ''' Change the value into a JSON serializable format.
+
+        '''
+        if isinstance(value, datetime.date):
+            value = convert_date_to_datetime(value)
+        return value
+
     @staticmethod
     def is_timestamp(value):
         return isinstance(value, (float,) + bokeh_integer_types) and not isinstance(value, bool)
diff --git a/bokeh/models/widgets/sliders.py b/bokeh/models/widgets/sliders.py
index 53bf21637..54af23982 100644
--- a/bokeh/models/widgets/sliders.py
+++ b/bokeh/models/widgets/sliders.py
@@ -152,6 +152,38 @@ class RangeSlider(AbstractSlider):
 class DateSlider(AbstractSlider):
     """ Slider-based date selection widget. """

+    @property
+    def value_as_datetime(self):
+        ''' Convenience property to retrieve the value tuple as a tuple of
+        datetime objects.
+
+        '''
+        if self.value is None:
+            return None
+
+        if isinstance(self.value, numbers.Number):
+            dt = datetime.utcfromtimestamp(v1 / 1000)
+        else:
+            dt = self.value
+        return dt
+
+    @property
+    def value_as_date(self):
+        ''' Convenience property to retrieve the value tuple as a tuple of
+        date objects.
+
+        Added in version 1.1
+        '''
+        if self.value is None:
+            return None
+
+        if isinstance(self.value, numbers.Number):
+            dt = datetime.utcfromtimestamp(self.value / 1000)
+            d = date(*dt.timetuple()[:3])
+        else:
+            d = self.value
+        return d
+
     value = Datetime(help="""
     Initial or selected value.
     """)
@@ -194,7 +226,7 @@ class DateRangeSlider(AbstractSlider):
             d2 = datetime.utcfromtimestamp(v2 / 1000)
         else:
             d2 = v2
-        return d1, d2    \
+        return d1, d2

     @property
     def value_as_date(self):
```

This change:

* only affects tuples (worried about performance implications of a general change to all containers)
* makes datetime properties nullable (which is true for basically every other property), which lets us not have "today" as a default value (which is kind of weird)

**Comment by bryevdv** [comment]
Noting: do need to resolve the timestamp/1000 business. We could put back the ugly try/except we had before but maybe there is a way to just fix it for real and always report the timestamp in units that can be known ahead.

**Comment by p-himik** [comment]
I assume that this
```diff
+            dt = datetime.utcfromtimestamp(v1 / 1000)
```
should instead be this
```diff
+            dt = datetime.utcfromtimestamp(self.value / 1000)
```

If so, then it works. :+1:

**Comment by bryevdv** [comment]
Yup, I fixed that in the PR but didn't go back and fix it up here
