### ISSUE TITLE
[BUG] image_url combined anchor and angle options generated unexpected results

### ISSUE THREAD

**Issue by comperem** [bokeh/bokeh#9703]
Hello, this is an issue raised from [this discourse comment](https://discourse.bokeh.org/t/getting-anchor-argument-of-image-url-to-work/4760).

In Bokeh 1.4.0, the `anchor` argument doesn't seem to work in `image_url()` specifically in combination with the `angle` argument. Both `anchor` and `angle` work independently but the combination ends up rotating the image around the upper left corner.

This script should rotate the image around the center (anchor) but it still seems to rotate around the upper left corner of the image. Regardless of rotation the image should be centered at (0,0).

    from bokeh.plotting import figure, show, output_file
    output_file("foo.html")

    p = figure(x_range=(-500,500), y_range=(-500,500))
    
    img="https://static.bokeh.org/logos/logo.png"
    p.image_url( url=[ img ],
             x=0, y=0, w=400, h=400, anchor="center", angle=0.5)

    show(p)

This was tested on Ubuntu 18.04.4.

Screenshot showing rotated image with incorrect offset from (0,0). Ideally, these two options together should put the image at (0,0) no matter what angle it is rotated.
![screenshot](https://user-images.githubusercontent.com/29280226/75048265-3dfc6480-5496-11ea-950e-3e6f3fac4d0f.jpg)

**Comment by bryevdv** [comment]
Thanks for the detailed report, @comperem !
