### ISSUE TITLE
[FEATURE] js_link attr indexing

### ISSUE THREAD

**Issue by RyanRio** [bokeh/bokeh#9706]
**Related problem**
With a standard `Slider` you can do:
```python
slider.js_link('value', figure.x_range, "start")
```
However if I now want to use a `RangeSlider` which has `value` of type `Tuple[Float, Float]` I cannot currently do:
```python
range_slider.js_link('value[0]', figure.x_range, "start")
```

More generally, I cannot use js_link for subscriptable attributes.

**Possible solution**
A simple solution would be to change the signature of js_link to, as Bryan mentioned in [this topic](https://discourse.bokeh.org/t/rangeslider-js-link-with-a-range-object/4772/5):
```python
def js_link(self, attr, other, other_attr, attr_selector=None):
        # is it possible to check if attr is subscriptable?
        if attr_selector is None:
            cb = CustomJS(args=dict(other=other), code="other.%s = this.%s" % (other_attr, attr))
        else:
            cb = CustomJS(args=dict(other=other), code="other.%s = this.%s[%d]" % (other_attr, attr, attr_selector))
```
Ideally, as mentioned in the comment, we would check if attr is subscriptable using some form of `get_attr(attr, "__getitem__")`. I'm not sure where the actual retrieval of the attr value occurs, though.

**Ideal solution**
Ideally, a user could essentially register a callback (`callable`) to retrieve a value from attr, this would be much more dynamic, the simplest case being `attr_selector = lambda attr: attr`, where it just returns the unsubscripted or altered `attr`. Again, I believe this depends on where the retrieval of the attr value occurs and how to attach the `attr_selector` callable.

**Additional context**
On version: 2.0.0dev6-36-gff2d2f628-dirty

**Comment by bryevdv** [comment]
@RyanRio I would only make one change to the "Possible Solution" which is that I think the selector could also reasonably be a string and not just and int (e.g. if the value is a dict/object)

Re: "Ideal Solution" I think at the point of adding a JS callback code we've moved into duplicating what can just be done already / better with `CustomJS` directly.

**Comment by RyanRio** [comment]
@bryevdv This needs to be reopened -> if you provide an `attr_selector` of `0` then the statement `f"[{attr_selector!r}]" if attr_selector else ""` returns `""`.

Fix:
`f"[{attr_selector!r}]" if attr_selector is not None else ""`

Oops haha

**Comment by bryevdv** [comment]
@RyanRio You can just submit a PR and reference this issue in it. Will you be able to submit this today?
