### ISSUE TITLE
Bottom of plot truncated using large Height value in Figure

### ISSUE THREAD

**Issue by Squirrel8475** [bokeh/bokeh#9711]
An unexpected behavior is observed when increasing height above a certain treshold: the plot is truncated and some data disappear at the bottom of the graph as illustrated in the attached picture.
![bug_large_height2](https://user-images.githubusercontent.com/52817858/75110342-4d61e600-562d-11ea-8a37-00cdf6cc3b38.jpg)

This can be reproduced with the small code below by setting the height to 17000. Reducing the height to 16000 brings the situation back to normal.

```py
from bokeh.plotting import show
from bokeh.plotting import figure

d0=[0,400]   
i0=[0,-100000]   
d1=[0,400]   
i1=[-200000,0] 

y_min   = min(min(i0),min(i1))
y_max   = max(max(i0),max(i1))
y_range = [y_min,y_max] 
fig = figure(height=17000,y_range=y_range)
fig.line(x=d0,y=i0)
fig.line(x=d1,y=i1)
show(fig)
```

**Comment by mattpap** [comment]
See https://github.com/bokeh/bokeh/issues/9115 for details. HTML5 canvas and its implementations have their limitations. Depending on the browser, 17000px is either pushing it or far beyond those limits.

**Comment by Squirrel8475** [comment]
Thank you very much for your support.
