### ISSUE TITLE
Update Bokeh milestone process

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9714]
The current `short-term` and `long-term` categories are not really serving the needs of @bokeh/dev This issues is to discuss what changes we would like to make, and also be a reminder that once a decision is taken, BEP-1 should be updated so that it is accurate for new contributors.

https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management

cc @mattpap @philippjfr @p-himik @hyles-lineata @pavithraes

**Comment by bryevdv** [comment]
As a first talking point, I'll just explicitly describe what @mattpap has already experimented with :

* `x.y.z`  work for a specific release
* `future` work for a future major release (will have breaking changes)
* `next` work we intend to do in some upcoming non-major release

Are there any other categories that would be useful? What is the expected flow for assigning milestones?

**Comment by p-himik** [comment]
> `short-term` and `long-term` categories are not really serving the needs of `bokeh/dev`

And what are the needs, exactly? It's not really clear from the proposed list of milestones and from BEP-1.

> to distinguish between ideas that are merely proposed vs ideas we have definitely agreed should be done

I feel like `type: discussion` is always for some proposal. If that's not the case, maybe an additional `type: proposal` would make sense. Anything without the preferred label can be considered as planned.

> Should it be the case that anything we definitely want to be done, should always be in _some_ milestone?

With the proposed milestones, definitely not. E.g. everybody agrees that some feature would be good to have, and it is planned as "when it's done". None of the milestones would really fit it.

**Comment by bryevdv** [comment]
> I feel like type: discussion is always for some proposal. If that's not the case, maybe an additional type: proposal would make sense. Anything without the preferred label can be considered as planned.

That's basically true. What I don't currently like is that means all rejected proposals are lumped in to one undifferentiated category, i.e. whether they were feature requests, a bug we can't/won't fix, a bug we disagree is a bug, just some random task, etc. 

That said, I'm not sure anyone care about that besides me.

**Comment by p-himik** [comment]
> `short-term` being a bucket of things contributors could easily draw from without much coordination or planning

Sounds like a job for the existing `good first issue` tag. :)

> that means all rejected proposals are lumped in to one undifferentiated category

How so?
- Feature request -> `reso: noaction` + `type: feature`
- a bug we can't/won't fix -> `reso: wontfix` + `type: bug`
- bug we disagree is a bug - `reso: invalid` + maybe `type: bug`.

**Comment by bryevdv** [comment]
> Sounds like a job for the existing good first issue tag. :)

No, I just didn't describe it well. :) I meant a bucket from which core contributors could freely pull issues into upcoming milestones from, not that they are suitable fo new contributors. 

Which is actually a good question itself: How should GFI issues be milestoned? We do want them done, but specifically don't want core devs to do them, typically.

> How so?

That would be a change from current practice (just noting). Currently, marking `feature` is the closest we have to `feature we agree and want to do`. Accordingly I have been changing rejected proposals to `discussion` for a long time to indicate that they were not that.

**Comment by p-himik** [comment]
> How should GFI issues be milestoned?

In my understanding, these are low-priority issues that can be done whenever. If so, it doesn't seem to make much sense to put any milestone on them. It'd make sense to put a specific version there when the PR is already merged, just to indicate when the functionality will be available.
