### ISSUE TITLE
BEP 1: Issues and PRs management.

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#973]
This is a meta issue associated with this proposal [document](https://github.com/ContinuumIO/bokeh/wiki/BEP-1:-Issues-and-PRs-management) to discuss about our Issues and PR management strategy.

**Comment by damianavila** [comment]
We think we need to make explicit that PRs does not need to be milestoned unless we face with a "standalone PR" (the ones that does not have an associated issue). If people agree I will make the modification in the BEP and close this one again...

**Comment by damianavila** [comment]
pinging @bryevdv who were interested in this change too...

**Comment by bryevdv** [comment]
I think that is exactly right. PRs that have a related issue ONLY have a status. "Standalone" PRs that are their own issues also have al the things that an issue might have: tags, type, reso, a milestone. As an aside at this point core dev's should only be submitting PRs that have related issues, the explicit mention of "standalone" PRs is really just to accommodate the form that many PRs by outside contributors will probably take.

**Comment by damianavila** [comment]
OK... we agreed... I will do the changes in the BEP.

**Comment by bryevdv** [comment]
Propose splitting platform tags off into `plat: osx`, `plat: firefox` etc.

**Comment by damianavila** [comment]
BEP updated with the no milestones on PRs, closing again for now...
