### ISSUE TITLE
Drop support for legacy web browsers

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9731]
By legacy web browsers I understand any browser that doesn't support at least ES6, which in particular includes Internet Explorer and phantomjs. In bokeh 1.x we support most all browsers without specifying the minimum supported versions, with the exception of IE, which we support only in version 11.x. This continues in bokeh 2.x, however support for legacy browsers was relegated to legacy support, where creators have to opt-in into allowing users to use those browsers. The proposal is to remove legacy support completely in bokeh 3.x. Additionally we could specify what's the minimum version of each supported browser, though that may be resolved in a separate issue.

So far we've been bound by client support for IE 11, but that's not the case anymore. Any users stuck with obsolete web browsers, will still be able to still use bokeh 2.x in the long term.

Supporting only modern web browsers will allow us to:

- use features that were either not available to us or prohibitively expensive to polyfill
- simplify build, testing and deployment

**Comment by bryevdv** [comment]
The first thing we should do is look at the user-agent field in the CDN logs. That will be the best proxy we have for the number of viewers using old browsers.

**Comment by gdementen** [comment]
Hi, it was a big (bad) surprise to me that IE11 support was moved to a different package. I could not find any mention of this in the release notes for any version, nor could I find any mention of supported browsers except that they must be "modern". This is kinda vague. In short, please document such changes!

**Comment by bryevdv** [comment]
Given the recent announcement from Microsoft regarding next August, I propose that we simply drop all IE support at Bokeh 3.0, sometime in the next year. If Microsoft, as vast and wealthy as it is, can no longer justify putting in any resources in to IE, then we certainly cannot.

**Comment by mattpap** [comment]
The announcement: https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666.

**Comment by mattpap** [comment]
@bryevdv, all our clients either migrated or are migrating away from IE, so 2.3 is the last release that must have IE support. I think it's the right time to at least deprecate it. Perhaps this could be the last release that supports it altogether.

**Comment by mattpap** [comment]
@bryevdv, so what's the conclusion here? I think it would be good to deprecate it 2.3 and drop in 2.5 (i.e. 2.4 being the last release supporting legacy browsers). This way I could target CSS layout for 2.5 without legacy browser burden.

**Comment by bryevdv** [comment]
I'm fine with deprecating and 2.4 being the last. We should discuss where the following release should be 2.5 or 3.0 though. cc @bokeh/dev

**Comment by jbednar** [comment]
I vote for 3.0 being the first one with no IE or other legacy browser support; seems like a good way to convey such a change.
