### ISSUE TITLE
[BUG] push_notebook broken in jupyter-lab 1.2.6

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9737]
notebook_comms examples work in classic notebook, but do not work in jlab. (OSX/Safari) This is with a fresh install of jlab and also 
```
jupyter labextension install @bokeh/jupyter_bokeh
```

I tried with versions all the way back 1.1.4 and they all report that the extension fails to load:

<img width="567" alt="Screen Shot 2020-02-27 at 9 13 11 PM" src="https://user-images.githubusercontent.com/1078448/75512910-cbb0e600-59a7-11ea-80b2-d84546ba51a6.png">

Other plots work, presumably because the Jupyter folks relented and now allow JS execution by default like before (or so I heard)

Not sure what's up. I thought this was fixed/tested recently. If there is an issue with my installation it is one that lots of people will run into because I just copy/pasted the commands from the user guide. 

cc @mattpap @philippjfr

**Comment by bryevdv** [comment]
And conversely, embedded Bokeh apps seem to work in jlab but not in classic notebooks.

**Comment by mattpap** [comment]
Did you install this?
```sh
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
Currently there is no support for specifying extensions' dependencies.

**Comment by bryevdv** [comment]
I did not, are you saying it needs to be? There is nothing here about it

https://docs.bokeh.org/en/latest/docs/user_guide/notebook.html

**Comment by mattpap** [comment]
Indeed it's missing. There's only a mention in the extension's readme. I will update this together with the blog post.

**Comment by bryevdv** [comment]
That still leaves the embedded app on classic notebook case, I will see what more I can investigate later during lunch.

**Comment by bryevdv** [comment]
notebook error is here in our code: 

<img width="1483" alt="Screen Shot 2020-02-28 at 8 53 36 AM" src="https://user-images.githubusercontent.com/1078448/75568309-e155f800-5a07-11ea-89f2-32996298e281.png">

`msg` does not have any `contect` attr.

**Comment by bryevdv** [comment]
@mattpap I will update the user's guide with a note. I need to be able to build (but not yet publish) real 2.0 builds over the weekend in order test SRI functionality and that is blocked until the repo is ready to be tagged 2.0 (including docs up to date).

**Comment by bryevdv** [comment]
So a band-aid fix for the other notebook issue is to wrap the code above into a function that is more forgiving and does not blow up if called when there are no sessions. Before resorting to that, I will try to do a bisection to see if there is a more identifiable cause for the change.

**Comment by bryevdv** [comment]
I have identified the issue and will submit a PR shortly.
