### ISSUE TITLE
Feature Request: Changing line width in data range 

### ISSUE THREAD

**Issue by p-ortmann** [bokeh/bokeh#9739]
**Is your feature request related to a problem? Please describe.**
I'd like to plot lines next to one another without clashes or gaps, currently I can only do this for one zoom level (at plot initiation) by manipulating the line coordinates in sync with the line width. However if you zoom the line width stays constant on the screen and they clash or gaps appear, depending on if you zoom in or out.
**Describe the solution you'd like**
I'd like to be able to choose between setting line width in coordinate space or screen units.

**Describe alternatives you've considered**
I am aware that rects/polygons may do the trick here, however I want to do this for a large amount of lines (10k - 100k , the more the better) and utilize WebGL.
I was also thinking that range tool may offer a solution (instead of zoom) by just calculating the  line offset to line width mapping twice, but you loose some flexibility here..

**Additional context**
posted a question on stackoverflow: https://stackoverflow.com/questions/60411960/using-data-line-widths-in-bokeh
This is for a large scale vehicular traffic visualization tool, we use line width as a visual aid to identify major flows in the network. However, typically we have two links between nodes (directed graph), the clashing inhibits analysis when zooming out.

Kudos to the work you guys do!

**Comment by bryevdv** [comment]
@p-ortmann  what would "width in data space" mean, specifically, in cases where there scales are very different on the x and y axes?

**Comment by p-ortmann** [comment]
@bryevdv I can't come up with a meaningful use case if your scales are very different. But it's a valid point, i guess you'd have to introduce axis oriented widths, one for a horizontal and one for a vertical line. That sounds like a lot of effort though, especially considering that rectangles offer a solution. 
I think I better wait for WebGL support for rectangles
