### ISSUE TITLE
[BUG] Hover tool not working correctly for rotated rectangles

### ISSUE THREAD

**Issue by nixie** [bokeh/bokeh#9752]
#### Software version info
 BokehJS 1.4.0 successfully loaded (I am using Jupyter notebooks)
Python 3.7.5
The version of the notebook server is: 6.0.3
IPython 7.10.1
Linux 5.3.0-40-generic # 32~18.04.1-Ubuntu
Firefox 73.0.1 (64-bit) / same behaviour also in Chromium Version 80.0.3987.122

#### Description of expected behavior and the observed behavior
Hover tool should raise a tooltip whenever the mouse cursor enters the region of a rect glyph. Unfortunately, if there are some rect glyphs in a plot with non-zero rotation (e.g. angle=90, angle_units='deg'), the tooltips show up in a weird manner (I was unable to decipher the dependency) - some regions work, some do not work, the tooltip sometimes pops-up even when outside of the glyph. Most probably it's related to rotation because if I set angle=0 for all rectangles, it works as expected.

- The behaviour is deterministic
- Also affects stand-alone HTML pages rendered using output_file()
- I tried the same example also with oval glyphs and in that case, there seems to be no such problem
- The problem goes away if I do not use ColumnDataSource and call `p.rect()` multiple times for each point. But then I can't use tooltip formatters to display various metadata, so such workaround is not good for me.

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.plotting import figure, output_notebook, show, ColumnDataSource
output_notebook()
p = figure(tools='hover')

rects={}
rects['xx'] = [1,2,3]
rects['yy'] = [1,2,3]
rects['width'] = [1,2,3]
rects['height'] = [1,2,3]
rects['angle'] = [90,90,90]
source = ColumnDataSource(data=rects)

p.rect('xx', 'yy', 'width', 'height', 'angle', fill_alpha=0.5,source=source,angle_units='deg')
show(p)
```

#### Stack traceback and/or browser JavaScript console output
```
Bokeh: BokehJS not loaded, scheduling load and callback at 
Date Mon Mar 02 2020 21:43:48 GMT+0100 (Central European Standard Time)
main.min.js:199:13
Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js main.min.js:233:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.4.0.min.js main.min.js:233:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-tables-1.4.0.min.js main.min.js:233:15
Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-gl-1.4.0.min.js main.min.js:233:15
[bokeh] document idle at 29 ms bokeh-1.4.0.min.js:242:1545
Bokeh: all BokehJS libraries/stylesheets loaded main.min.js:205:17
Bokeh: BokehJS plotting callback run at 
Date Mon Mar 02 2020 21:43:49 GMT+0100 (Central European Standard Time)
main.min.js:289:15
[bokeh] setting log level to: 'info' bokeh-1.4.0.min.js:317:2257
Bokeh: all callbacks have finished main.min.js:183:13
Source map error: Error: request failed with status 403
Resource URL: https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js
Source Map URL: bokeh.min.js.map
```
#### Screenshots or screencasts of the bug in action
![rect_glyph_hover](https://user-images.githubusercontent.com/580648/75719517-2e222300-5cd5-11ea-9e85-d5fff7cb505d.gif)

Thanks a lot!

**Comment by floschl** [comment]
just stumbled upon the same issue. Is there a quick fix for this?

**Comment by nixie** [comment]
Hi,
I finally "solved" it by computing absolute rectangle vertice coordinates after rotation inside my code (simple trigonometry) and then used [p.patches](https://docs.bokeh.org/en/latest/docs/reference/plotting.html#bokeh.plotting.Figure.patches) for plotting such polygons. The hover tooltip then works as expected and the code becomes more general.

Here is the conversion function (line + line thickness is considered here as a rectangle):
```python
def get_2d_line_as_polygon(point_1, point_2, width):
    """
    Converts line + line thickness representation (midline+width) to a vector of corners ordered for polygon plotting.
    """
    # compute the directional vector
    dir_vector = complex(*(np.array(point_2) - np.array(point_1)))
    line_length = abs(dir_vector)
    directional_vector = dir_vector / line_length

    # compute position of all corners, which we need to specify when creating polygons
    rot_minus90 = -1j  # complex multiplication with this number results in phase shift by -90 degrees
    rot_plus90 = +1j  # complex multiplication with this number results in phase shift by +90 degrees
    lower_left = (directional_vector * rot_minus90) * (width / 2) + complex(*point_1)
    lower_right = lower_left + dir_vector
    upper_left = (directional_vector * rot_plus90) * (width / 2) + complex(*point_1)
    upper_right = upper_left + dir_vector

    return np.array(
        [
            [lower_left.real, lower_left.imag],
            [lower_right.real, lower_right.imag],
            [upper_right.real, upper_right.imag],
            [upper_left.real, upper_left.imag]
        ])
```

**Comment by bryevdv** [comment]
@floschl generally speaking, if there are no updates in the issue, then there are no updates at all, so it's not necessary to ask this question.

**Comment by floschl** [comment]
@nixie, great idea thank you very much for this workaround, this helps a lot!

@bryevdv , I did rather mean to ask for a workaround of this issue and promptly @nixie gave showed one.
