### ISSUE TITLE
[BUG] bokeh 1.4.0 labextension for jupyterlab is "outdated" for jupyterlab 2.0.0

### ISSUE THREAD

**Issue by pythonic2020** [bokeh/bokeh#9756]
After installing **jupyterlab 2.0.0** and using this command:

`jupyter labextension install @bokeh/jupyter_bokeh`,

`jupyter labextension list`

shows that the bokeh labextension is "outdated."  Bokeh plotting and server still seemed to work ok in jupyterlab 2.0.0.  I went back to jupyterlab 1.2.6 or else I would list the output here.

ipympl 0.5.2 labextensions also had issues with JLab 2.0.0, but 0.5.3 has just been released which may have fixed those issues.

```
> conda list "bokeh|python|matplotlib|notebook|ipympl|nodejs"
# packages in environment at C:\Users\me\Miniconda3\envs\forge:
#
# Name                    Version                   Build  Channel
bokeh                     1.4.0                    py37_0
ipympl                    0.5.2                      py_0    conda-forge
ipython                   7.13.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                    py37_0
matplotlib                3.1.3                    py37_0
matplotlib-base           3.1.3            py37h64f37c6_0
nodejs                    13.9.0                        0    conda-forge
notebook                  6.0.3                    py37_0
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.7                   py37_0
```

**Comment by bryevdv** [comment]
There is already an issue for this in the extension repo: 

https://github.com/bokeh/jupyter_bokeh/issues/88

We will have to get through the Bokeh 2.0 release before we can do anything about this.

**Comment by pythonic2020** [comment]
Ok, thank you.
