### ISSUE TITLE
[BUG] TextInput unresponsive on Edge

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9761]
Works fine on Chrome and FF. Enter, tab, etc nothing will seem to register an update e.g. in sliders.py

**Comment by bryevdv** [comment]
This seems like a pretty glaring problem but I don't know how to fix it and I think trying to start the release over from scratch is too risky.

**Comment by mattpap** [comment]
If this was legacy Edge, not the new Chromium based one, then this issue should be fixed as "won't fix", because this browser is not supported anymore.

**Comment by mattpap** [comment]
I will assume this was either legacy Edge or old version of modern Edge.
