### ISSUE TITLE
[BUG] `gridplot` `merge_tools` removes distinct tools it thinks are repeated, e.g., `xpan` and `ypan`

### ISSUE THREAD

**Issue by anthonytw** [bokeh/bokeh#9763]
### Software versions

**bokeh version**: 1.4.0
**python version**: 3.7.3 (macOS), 3.8.0 (Ubuntu)
**OS**: macOS 10.15.3 and Ubuntu 19.10
**browser**: (tested only on macOS) Firefox 73.0.1, Chrome 80.0.3987.132

### Expected and Observed Behavior

**Expected behavior**: Merged toolbar contains both vertical and horizontal pan tools.
**Observed behavior**: Only one of the pan tools is present on the merged plot.

Note: With `merge_tools=False`, each plot correctly contains two pan tools, but there are multiple toolbars, which is not desired.
Note: Same problem when using e.g., `xwheel_zoom` and `ywheel_zoom`

### Minimal code to reproduce

```python
import pandas as pd
import numpy as np

from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource
from bokeh.layouts import gridplot


t = np.linspace(0, 10, 1000)
data = pd.DataFrame(data={
    'time': t,
    'x': 12*np.cos(2*3.14/0.5*t),
    'y': 12*np.cos(2*3.14/2*t),
})
source = ColumnDataSource(data)

tools = 'xpan,ypan'
plt_x = figure(tools=tools, height=150)
plt_x.line(x='time', y='x', source=source)
plt_y = figure(tools=tools, height=150)
plt_y.line(x='time', y='y', source=source)
gplt = gridplot([[plt_x], [plt_y]], toolbar_location='right', merge_tools=True)

show(gplt)
```

### Python and Browser output

(no error, no stack trace)

Python output:

```
/Users/***/.virtualenvs/py37/lib/python3.7/site-packages/bokeh/plotting/helpers.py:689: UserWarning: PanTool are being repeated
  warnings.warn("%s are being repeated" % ",".join(repeated_tools))
```

Browser console (Firefox):

```
Request to access cookie or storage on “https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js” was blocked because we are blocking all third-party storage access requests and content blocking is enabled. bkmin.html
[bokeh] setting log level to: 'info' bokeh-1.4.0.min.js:317:2257
[bokeh] document idle at 210 ms bokeh-1.4.0.min.js:242:1545
Source map error: Error: request failed with status 403
Resource URL: https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js
Source Map URL: bokeh.min.js.map 2
```

### Screenshots

Merging toolbars (incorrect behavior):

![image](https://user-images.githubusercontent.com/1521221/76053152-4181f800-5f3a-11ea-9763-342561772386.png)

Not merging toolbars (correct behavior, but multiple toolbars):

![image](https://user-images.githubusercontent.com/1521221/76053038-e6e89c00-5f39-11ea-837b-83beec1057af.png)

**Comment by HrithikKumar49** [comment]
I'd like to work on this issue

**Comment by anthonytw** [comment]
@mattpap This issue was not resolved, the problem still persists. The "warning" that was handled by #9829 was not the issue. Still only one plot tool shows. And, it even doesn't have the correct function (e.g., for me in both Chrome and Firefox, the horizontal pan button only shows, but its function is the vertical pan. I think the problem got slightly worse.)

**Comment by bryevdv** [comment]
@mattpap this is a problem with the tool proxying on the JS side AFAICT
