### ISSUE TITLE
[FEATURE] Add path to fileInput

### ISSUE THREAD

**Issue by NikoDap** [bokeh/bokeh#9765]
Hello Friends,

would it be possible to add a attribute to fileInput? I would like to have the path of the file that is chosen. I have some files that include data from a measuring machine. If I take the base64 value and try to convert it to utf-8 or something else, i don't get the right data. Even if I try to convert base64 with a different tool, it won't work.
So it would be great to get the path of the selected file, so that I can read it with normal python tools.

Thank you very much.

Greetings,
Niko

**Comment by bryevdv** [comment]
It's not possible to provide the full path. For security reasons, browsers hide this information and the is nothing we can do about it.

**Comment by bryevdv** [comment]
Why `wontfix` ? That indicates a decision on our part. This is not something we could fix, even if we wanted to. I'd suggest if this needs a reso at all that `noaction` is the most appropriate.
