### ISSUE TITLE
Visual not displayed with bokeh serve

### ISSUE THREAD

**Issue by jaseuts** [bokeh/bokeh#9768]
I have a file called "bokeh app.py" saved in Documents folder as follows:
```
import pandas as pd
import numpy as np
from bokeh.plotting import figure
from bokeh.io import output_file, show, curdoc
from bokeh.plotting import ColumnDataSource
from bokeh.models import HoverTool, Slider
from bokeh.models import CategoricalColorMapper
from bokeh.layouts import row, column, gridplot, widgetbox
from bokeh.models.widgets import Panel, Tabs

a = 0.3; b = 10.04
x = np.arange(a, b, (b-a)/300)
a = -0.1; b = 0.1
y = np.arange(a, b, (b-a)/300)

source = ColumnDataSource(data={'x':x, 'y':y})

plot = figure()
plot.line('x', 'y', source=source)

slider = Slider(title='slider', start=0, end=10, step=0.1, value=1)

def callback(attr, old, new):
    scale = slider.value
    new_y = np.sin(scale/x)
    source.data = {'x': x, 'y': new_y}

# Attach the callback to the 'value' property of slider
slider.on_change('value', callback)  

layout = column(widgetbox(slider), plot)
curdoc().add_root(layout)
```
When I run `bokeh serve "documents\bokeh app.py" in anaconda prompt, I got these messages:
```
(venv) D:\Users\jng>bokeh serve "documents\bokeh app.py"
2020-03-10 11:28:11,906 Starting Bokeh server version 2.0.0 (running on Tornado 5.1.1)
2020-03-10 11:28:12,004 User authentication hooks NOT provided (default user enabled)
2020-03-10 11:28:12,101 Bokeh app running at: http://localhost:5006/bokeh app
2020-03-10 11:28:12,103 Starting Bokeh server with process id: 13852
```
But no visual displayed anywhere. I then entered this `http://localhost:5006/bokeh app` in chrome browser, it said "404: Not Found", and some additional messages appeared in the anaconda prompt
```
(venv) D:\Users\jng09>bokeh serve "documents\bokeh app.py"
2020-03-10 11:28:11,906 Starting Bokeh server version 2.0.0 (running on Tornado 5.1.1)
2020-03-10 11:28:12,004 User authentication hooks NOT provided (default user enabled)
2020-03-10 11:28:12,101 Bokeh app running at: http://localhost:5006/bokeh app
2020-03-10 11:28:12,103 Starting Bokeh server with process id: 13852
2020-03-10 12:41:21,539 404 GET /bokeh%20app (::1) 1.00ms
2020-03-10 12:41:21,828 404 GET /favicon.ico (::1) 1.00ms
2020-03-10 12:51:24,548 404 GET /bokeh%20app (::1) 1.00ms
```
My questions are:

- Is this a bug?
- How to fix it?

Thanks

**Comment by bryevdv** [comment]
@jaseuts The issue is the space in your module filename. While in principle perhaps that "should" work, in practice it is extremely unusual to ever have python module names with spaces in them, so I'm not sure we would ever bother doing anything about this. 

BTW I'd like to gently direct you to the project discourse, which is the best place to start if you are not sure if something is a bug pr not:

https://discourse.bokeh.org/

**Comment by jaseuts** [comment]
Thanks for your response @bryevdv. I renamed the file to "bokehApp.py" but it didn't work either, still having the same message shown in anaconda prompt without any visual displayed. As have no knowledge in programming, I thought if anything didn't work as intended, it must be a bug?

**Comment by bryevdv** [comment]
@jaseuts I ran your exact code in a file named `bkapp.py` and it worked as expected for me. So, we will need more complete information from you:

* python, platform and browser versions
* the output of running `bokeh info`
* the exact set of commands you ran and steps you took

**Comment by bryevdv** [comment]
<img width="1229" alt="Screen Shot 2020-03-09 at 7 21 31 PM" src="https://user-images.githubusercontent.com/1078448/76273539-5660d300-623b-11ea-8972-22887f090948.png">

**Comment by jaseuts** [comment]
@bryevdv, please see below:
```
(venv) D:\Users\jng09>bokeh info
Python version      :  3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)]
IPython version     :  7.12.0
Tornado version     :  5.1.1
Bokeh version       :  2.0.0
BokehJS static path :  D:\Users\jng\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\bokeh\server\static
node.js version     :  v13.9.0
npm version         :  6.13.7
```
OS: Windows 7 64-bit
Browser: Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
```

**Comment by bryevdv** [comment]
I am afraid I don't have access to Windows 7 to test on. Is there any way you can test on different platforms are report back?

**Comment by bryevdv** [comment]
Also, please provide the other information I asked for: *what is the exact set of command and steps you took*

**Comment by bryevdv** [comment]
@jaseuts perhaps you should also try running with the `--show` option. That will raise a browser to the correct location for you:

```
bokeh serve --show bokehApp.py
```

**Comment by jaseuts** [comment]
Sorry @bryevdv. Thanks for being patient with me. Here is the command I entered in anaconda prompt.

**Comment by bryevdv** [comment]
After running that did you navigate a browser to `http://localhost:5006/bokehApp` ? if you did (for if you run with `--show`) are there any errors reported in the browsers JavaScript console? (This differs by browser you will need to google how to access the JS console for your browser)

**Comment by jaseuts** [comment]
@bryevdv, thanks for your help. it works automatically now with your command `bokeh serve --show bokehApp.py`. 

The new question then: what is the purpose of the command `bokeh serve` without the `--show`?

**Comment by bryevdv** [comment]
@jaseuts `--show` is a useful convenience for anyone running things locally, but if you are deploying a Bokeh server in a production setting, then the instance running the bokeh serve command a remote compute for all viewers (it may not even have a display attached).
