### ISSUE TITLE
IPywidgets examples

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9772]
Need at least the following examples

* server example with basic sliders, etc
* server example with ipyvolume
* server example with ipyleaflet 
* notebook example with bokeh plot in ipywidgets layotut

maybe best under a `howto/ipywidgets` directory?

@mattpap for the last I am basing on my understanding that that direction is also now possible. Can you point to some example code for how to do that?

**Comment by bryevdv** [comment]
@mattpap it would be very helpful and appreciated if you could take one hour and provide 1 or 2 of the examples above so I can point users asking how to actually use this feature, at something concrete

**Comment by mattpap** [comment]
Rescheduling back 2.0.1. I will get that done by tomorrow.

**Comment by bryevdv** [comment]
I was planning on building packages today, since I have the time today.

**Comment by mattpap** [comment]
I see. In that case let's proceed, but we will need to have 2.0.2 soon after that.
