### ISSUE TITLE
Incorrect guidance on installing additional dependencies for export() functions

### ISSUE THREAD

**Issue by OriolAbril** [bokeh/bokeh#9778]
Release 2.0.0 has changed the guidance on [additional dependencies to export plots](http://docs.bokeh.org/en/2.0.0/docs/user_guide/export.html#additional-dependencies) as png, svg... It currently states that the extra dependencies can be installed via conda using:

    conda install selenium geckodriver firefox

However, of the 3 packages, only [selenium](https://anaconda.org/search?q=selenium) is available via anaconda channel, [geckodriver](https://anaconda.org/search?q=geckodriver) and [firefox](https://anaconda.org/search?q=firefox) are not available via anaconda main channel, they are available via conda-forge channel. Trying to run the command above results in `PackagesNotFoundError: The following packages are not available from current channels`.

I would expect the command provided to work straight away. Would adding conda-forge as the channel be an acceptable solution for you? I can make a PR to edit this.

**Comment by mattpap** [comment]
Yes, please submit a PR. This seems to be a purely documentation issue:
```sh
$ git grep "conda install" | grep geckodriver
bokeh/io/webdriver.py:                               "with 'conda install -c conda-forge firefox geckodriver'.")
sphinx/source/docs/user_guide/export.rst:    conda install selenium geckodriver firefox
```

**Comment by bryevdv** [comment]
@OriolAbril Yes a PR would be great. I would suggest we should make it clear that conda installing (from conda-forge) is *one* way to install these. But note that they can be installed by other means as well, and that is ok.
