### ISSUE TITLE
[FEATURE] Expose `_known_tools` and `_tool_from_string` to allow reuse

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#9783]
Right now, `_known_tools` from `bokehjs/src/lib/api/plotting.ts` cannot be used outside of BokehJS and `_tool_from_string` is private within `bokeh/plotting/_tools.py`.
That means that if a user wants to add a tool with default parameters on an existing instance of `Figure`, they will have to dig its definition in the Bokeh(JS) sources and copy it over to their codebase.
It would be useful to be able to just call something like `tool_from_string('pan')`.

**Comment by mattpap** [comment]
This is a nice idea. I would just implement this as a static method on `Tool` class.
