### ISSUE TITLE
wrong links in bokeh embed example readme

### ISSUE THREAD

**Issue by chrisbarber** [bokeh/bokeh#9793]
repro: just run the example and try the links.

https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/django_embed/README.md

**Comment by bryevdv** [comment]
@philippjfr @mattpap This example seems to assume the examples are installed under site-packages? 

> WARNING:bokeh.server.django.routing:bokeh applications directory '/Users/bryan/anaconda/envs/dev/lib/python3.7/site-packages/examples/app' doesn't exist

That was due to an obscure early conda package feature that I believe nothing other than bokeh ever used (literally). I removed it for 2.0 to make packages much smaller.

**Comment by bryevdv** [comment]
@chrisbarber did you intend to make a PR against the main repo? FYI the PR above is against master on your fork.
