### ISSUE TITLE
DataTable does not show in JupyterLab

### ISSUE THREAD

**Issue by asodeur** [bokeh/bokeh#9795]
## Description

`bokeh.DataTable` does not show in Jupyterlab (tried my luck on the JupyterLab [issue tracker](https://github.com/jupyterlab/jupyterlab/issues/8049) already).

## Reproduce
Run the following code in a JupyterLab notebook
```python
from datetime import date
from random import randint

from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn
from bokeh.io import show, output_notebook, output_file

output_notebook()
# output_file('data_table_test.html')

data = dict(
        dates=[date(2014, 3, i+1) for i in range(10)],
        downloads=[randint(0, 100) for i in range(10)],
    )
source = ColumnDataSource(data)

columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280)

show(data_table)
```

## Expected behavior

Should display a table like the one you get in the HTML file produced when you change the output in the above code by
```python
# output_notebook()
output_file('data_table_test.html')
``` 

## Context

- Operating System and version: Windows 7
- Browser and version: Chrome 78.0.3904.87
- JupyterLab version: 2.0.1
- bokeh: 2.0.0

<details><summary>Browser Output</summary>
<pre>
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not callable
    at init (bokeh-tables-2.0.0.min.js:97)
    at new SlickGrid (bokeh-tables-2.0.0.min.js:97)
    at x.render (bokeh-tables-2.0.0.min.js:46)
    at x.build (bokeh-2.0.0.min.js:419)
    at x.renderTo (bokeh-2.0.0.min.js:419)
    at r (bokeh-2.0.0.min.js:534)
    at async Object.t.add_document_standalone (bokeh-2.0.0.min.js:534)
</pre>
</details>

**Comment by mattpap** [comment]
Can't reproduce this with any kind of resources on Linux. Maybe this is a Windows specific issue.

**Comment by asodeur** [comment]
Tried the [binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo) on JupyterLab's github page and that produced another error on first start but worked after the second attempt (error in the JS console was something like: Invalid model DataTable).

The obvious difference is the JupyterLab binder says `BokehJS 2.0.0 successfully loaded.` while on my computer it says `BokehJS 1.4.0 successfully loaded.`. The JS backtrace contains `bokeh-2.0.0.min.js`. Did not spot this before, looks like my installation is broken somehow.

**Comment by bryevdv** [comment]
Also working for me on OS X:

<img width="705" alt="Screen Shot 2020-03-20 at 8 48 44 AM" src="https://user-images.githubusercontent.com/1078448/77180775-a46da600-6a87-11ea-9e79-8cae33a3576d.png">

@asodeur do you have the Bokeh Jupyter extension installed?

**Comment by asodeur** [comment]
@bryevdv  Yes, Bokeh Jupyter extension is installed. By now I realized BokehJS 1.4.0 gets mixed with 2.0.0 somehow. Looks like my installation is broken.

**Comment by leomrocha** [comment]
Issue in Linux Ubuntu 20.04, 
Jupyter Lab
Python 3.8
BokehJS 2.0.2

![image](https://user-images.githubusercontent.com/3646521/84046526-82126700-a9aa-11ea-90fd-5e219c122dca.png)

**Comment by bryevdv** [comment]
@leomrocha please open a new issue (that is not the same thing described in this issue) and please always provide actual code text that can be quickly copy and pasted by maintainers, not images of code.
