### ISSUE TITLE
Deprecation warnings after PR #9807

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9820]
E.g. running bokeh server shows:
```
BokehDeprecationWarning: bokeh.core.property.regex is deprecated, use bokeh.core.property.string module instead
```
All references to `.regex` module within bokeh should have been updated in PR #9807.

**Comment by mattpap** [comment]
@ayushiitr2901 please submit a follow up PR to fix this.

**Comment by bryevdv** [comment]
More generally, everything should really only ever import from the top level `bokeh.properties` and not from sub-modules (which I thought was already the case but should have suggested to check)

**Comment by ayushiitr2901** [comment]
I think to find and updating all references to the `.regex `module with `.string` would solve the issue. Should I continue with the same? Or we can update the files to call regex from `bokeh.properties` rather than calling the sub-module directly.

**Comment by ayushiitr2901** [comment]
The only files causing the error are `bokeh/core/property/color.py` and `bokeh/core/property/visual.py`, both in the properties folder itself. I think calling to` string `module directly would be better.
