### ISSUE TITLE
[BUG] Bokeh 2.0.0 no longer accepts a `selected` argument in the `ColumnDataSource` constructor

### ISSUE THREAD

**Issue by barentsen** [bokeh/bokeh#9823]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh=2.0.0
python=3.6.8
OS=macOS 10.14.6

#### Description of expected behavior and the observed behavior

As of Bokeh 2.0.0, calling the constructor of `ColumnDataSource` with a
 value for the `selected` argument yields a `RuntimeError: ColumnDataSource.selected is a readonly property`.

I understand from the [data release notes](https://docs.bokeh.org/en/latest/docs/releases.html#columndatasource-properties) that the `ColumnDataSource.selected` property is read-only as of 2.0.0.  It is surprising however that a value cannot be passed while instantiating the object, because the [API docs still show](http://docs.bokeh.org/en/latest/docs/reference/models/sources.html?highlight=columndatasource#bokeh.models.sources.ColumnDataSource.selected) that a value for `selected` can be passed to the `ColumnDataSource` constructor.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.models import ColumnDataSource, Selection
cds = ColumnDataSource(data={'a': [1, 2, 3]},
                       selected=Selection(indices=[2]))
```

#### Stack traceback and/or browser JavaScript console output

```
In [1]: from bokeh.models import ColumnDataSource, Selection 
   ...: cds = ColumnDataSource(data={'a': [1, 2, 3]}, 
   ...:                        selected=Selection(indices=[2]))                                                                            
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-d22061c5d870> in <module>
      1 from bokeh.models import ColumnDataSource, Selection
      2 cds = ColumnDataSource(data={'a': [1, 2, 3]},
----> 3                        selected=Selection(indices=[2]))

~/bin/anaconda/lib/python3.6/site-packages/bokeh/models/sources.py in __init__(self, *args, **kw)
    191             else:
    192                 raise ValueError("expected a dict or pandas.DataFrame, got %s" % raw_data)
--> 193         super().__init__(**kw)
    194         self.data.update(raw_data)
    195 

~/bin/anaconda/lib/python3.6/site-packages/bokeh/model.py in __init__(self, **kwargs)
    232         kwargs.pop("id", None)
    233 
--> 234         super().__init__(**kwargs)
    235         default_theme.apply_to_model(self)
    236 

~/bin/anaconda/lib/python3.6/site-packages/bokeh/core/has_props.py in __init__(self, **properties)
    244 
    245         for name, value in properties.items():
--> 246             setattr(self, name, value)
    247 
    248     def __setattr__(self, name, value):

~/bin/anaconda/lib/python3.6/site-packages/bokeh/core/has_props.py in __setattr__(self, name, value)
    271 
    272         if name in props or (descriptor is not None and descriptor.fset is not None):
--> 273             super().__setattr__(name, value)
    274         else:
    275             matches, text = difflib.get_close_matches(name.lower(), props), "similar"

~/bin/anaconda/lib/python3.6/site-packages/bokeh/core/property/descriptors.py in __set__(self, obj, value, setter)
    535 
    536         if self.property._readonly:
--> 537             raise RuntimeError("%s.%s is a readonly property" % (obj.__class__.__name__, self.name))
    538 
    539         self._internal_set(obj, value, setter=setter)

RuntimeError: ColumnDataSource.selected is a readonly property
```

**Comment by bryevdv** [comment]
hi @barentsen The properties in the API docs are intended to reflect exactly what properties *exist* on a Bokeh model. Separately, the large majority of these can be configured in initializers, but there are a few exceptions, among them this. If you would like to submit a PR to update the help string for `selected` to make it clear that this is one of the exceptions, that would certainly be accepted. The spot to change is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L74

Otherwise, with > 2.0 users should only update properties of the `Selection` models that Bokeh automatically configured.

**Comment by barentsen** [comment]
Ok, thanks!  Recording here for future reference that the solution is to use
```python
cds = ColumnDataSource(data={'a': [1, 2, 3]})
cds.selected.indices = [2]
```
instead of:
```python
cds = ColumnDataSource(data={'a': [1, 2, 3]},
                       selected=Selection(indices=[2]))
```

**Comment by bryevdv** [comment]
@barentsen yes exactly, I should have added that in my response, thank you for circling back
