### ISSUE TITLE
[BUG] HTMLTemplateFormatter prepends notebook server url in DataTable

### ISSUE THREAD

**Issue by gclen** [bokeh/bokeh#9824]
#### Software version info
Bokeh: 2.0.0
Notebook: 6.0.3
Python: 3.7.6
Browser: Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)

#### Description of expected behaviour and the observed behaviour
I am trying to create a datatable with a column that includes clickable URLs. When I create the table using the code below (formatting the URL column with HTMLTemplateFormatter) it appears to work. However, when I click on the link (or hover over it), the link goes to http://localhost:8888/notebooks/%E2%80%9Dhttps://github.com/bokeh/bokeh%E2%80%9D where localhost:8888/notebooks comes from my jupyter notebook server. Is there a way to turn off this behaviour and just go directly to the specified URL? 

#### Complete, minimal, self-contained example code that reproduces the issue
I ran this code in a jupyter notebook
```python
from datetime import date
from random import randint
import pandas as pd
from bokeh.io import output_file, show, output_notebook
from bokeh.models import ColumnDataSource, DataTable, DateFormatter, TableColumn, HTMLTemplateFormatter

output_notebook()

data = dict(url = ['https://github.com/bokeh/bokeh'] * 10)
data_df = pd.DataFrame.from_dict(data)

source = ColumnDataSource(data_df)

columns = [
        TableColumn(field='url', title="URL", formatter=HTMLTemplateFormatter(template='<a href=”<%= value %>”><%= value %></a>'))
    ]

data_table = DataTable(source=source, columns=columns)
show(data_table)
```
#### Screenshots or screencasts of the bug in action

![bokeh_url_output_cell](https://user-images.githubusercontent.com/4321675/77570430-299af580-6ea2-11ea-9e59-27f1b6a973bd.png)

![bokeh_url_bug](https://user-images.githubusercontent.com/4321675/77570447-328bc700-6ea2-11ea-81ee-bf360c28447f.png)

**Comment by bryevdv** [comment]
@gclen I believe you are over-quoting the templated value. In any case, support/usage questions belong on the Discourse so any more discussion should occur there:

https://discourse.bokeh.org/
