### ISSUE TITLE
[FEATURE] Dynamic Legend placement in plots

### ISSUE THREAD

**Issue by Latecomer4** [bokeh/bokeh#9827]
I'd like to be able to position the Legend in a plot dynamically along a border edge depending on where it will overlap the fewest data points.  I'm creating stock time series charts, and certain areas of the chart may or may not have data points at different times.

The feature request would be to add legend.location options such as 'bottom_dynamic' or 'left_dynamic' to accomplish this.  Perhaps there is a way to determine on Legend creation the dimensions in screen coordinates that the Legend will occupy and compare that to the underlying data to determine where there is the least overlap?  I looked for a way to access these screen coordinates to attempt the comparison, but could not find one.

Thanks for considering - Bokeh is a fantastic tool!

**Comment by bryevdv** [comment]
Hi @Latecomer4 thank you for the kind words. This was actually a proposed feature from very early on (maybe 8 years ago), but was never acted on.  I think there are some significant obstacles to dynamic legend placement: 

* not all glyphs will be able to participate equally well (e.g. patch glyphs might have a huge bounding box but actually take up a very small sliver of space)
* even if all glyphs could perform well, the plot range may simply be full, with *no* good place to place a legend without significant overlap. 

So then we could maybe think about letting legends inform range bounds to be able to ask to make room for themselves. But ranges are actually already *enormously* complicated, with intersections of of: user set values, auto-ranging, reversed ranges, fixed bounds, auto-following, synthetic and hierarchical ranges for categoricals... It's just really hard to justify adding more complication to all that. 

Can I ask if you have considered placing the legend outside the plot area in this situation? That seems like an immediately available solution.

**Comment by Latecomer4** [comment]
Thanks for the quick response and the background, @bryevdv .  Sounds like this would be a lot of lift for a limited amount of functionality.  The suggestion about locating the legend outside the plot is a good one; I may do that or just use the existing attributes to minimize the footprint of the Legend.
