### ISSUE TITLE
[BUG] Unhandled exceptions in FunctionHandler cause hang/blank screen

### ISSUE THREAD

**Issue by wearpants** [bokeh/bokeh#9831]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.0.0
Panel 0.9.3
Django 2.2.11
Channels 2.4.0
Python 3.8.2
Chromium 80.0.3987.149 (Official Build) snap (64-bit)
Ubuntu 19.10

#### Description of expected behavior and the observed behavior
An exception in user code running in a `FunctionHandler` under Django/Channels causes a blank browser screen and a request for `autoload.js` that hangs. This is analogous to #24 and #8034.

Pull request forthcoming.

**Comment by bryevdv** [comment]
@wearpants sure but I'd ask for one more change. `_handle_exception` can be made a method on `Handler` and then we won't have to be importing private functions:
```
    def _handle_exception(self, e):
        """ Record an exception and details on a Handler.

        """
        self._failed = True
        self._error_detail = traceback.format_exc()

        _exc_type, _exc_value, exc_traceback = sys.exc_info()
        filename, line_number, func, txt = traceback.extract_tb(exc_traceback)[-1]

        self._error = "%s\nFile \"%s\", line %d, in %s:\n%s" % (str(e), os.path.basename(filename), line_number, func, txt)

```
I actually made and tested this change and tried to push directly to the PR branch on your fork (which I should be able to as a maintainer, unless you have opted out) but I could not get it to work.

**Comment by wearpants** [comment]
I was gonna do that, but CodeRunner inherits from object, not Handler, and
we need the logic both places :-\

**Comment by bryevdv** [comment]
Ah so it does. In the case let's just make it public under "Dev API" (and update the docstring as above).Did confirm notebooks work as expected, thanks!

**Comment by PeteFein** [comment]
ok done
