### ISSUE TITLE
[BUG]v2.0.1 problem with bkzep

### ISSUE THREAD

**Issue by mhebrard** [bokeh/bokeh#9854]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

* bokeh v2.0.1
* python v3.6.8
* zeppelin v 0.8.2
* amazon-linux-ami 2018.03-release
* emr v5.28.0
* Spark v2.4.4
* Hail v0.2.32
* Chrome v80.0.3987.149

#### Description of expected behavior and the observed behavior

In zeppelin, when import bokeh and bkzep an error is fired.
it was working fine with bokeh v2.0.0

#### Complete, minimal, self-contained example code that reproduces the issue

```
%pyspark
from bokeh.io import show, output_notebook
import bkzep
output_notebook(notebook_type='zeppelin')
```

#### Stack traceback and/or browser JavaScript console output

```
Fail to execute line 10: output_notebook(notebook_type='zeppelin')
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-5737857176342887979.py", line 380, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 10, in <module>
  File "/usr/local/lib/python3.6/site-packages/bokeh/io/output.py", line 111, in output_notebook
    run_notebook_hook(notebook_type, 'load', resources, verbose, hide_banner, load_timeout)
  File "/usr/local/lib/python3.6/site-packages/bokeh/io/notebook.py", line 298, in run_notebook_hook
    return _HOOKS[notebook_type][action](*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/bkzep/io.py", line 161, in load_notebook
    lab_html, lab_js = _load_notebook_html(resources, verbose, hide_banner, load_timeout)
  File "/usr/local/lib/python3.6/site-packages/bkzep/io.py", line 132, in _load_notebook_html
    timeout  = load_timeout
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/bokeh/core/_templates/autoload_nb_js.js", line 1, in top-level template code
    {% extends "autoload_js.js" %}
  File "/usr/local/lib/python3.6/site-packages/bokeh/core/_templates/autoload_js.js", line 88, in top-level template code
    const hashes = {{ bundle.hashes|json }};
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'bundle' is undefined
```

#### Screenshots or screencasts of the bug in action

![image](https://user-images.githubusercontent.com/1891334/77866350-36826500-7265-11ea-954f-2ad67204eb19.png)

**Comment by bryevdv** [comment]
@mhebrard `bkzep` is an outside project that is not maintained  by the Bokeh team. It's entirely possible they will need to make adjustments for 2.0 since it was a major release that included breaking changes. But you will need to file an issue on their repo directly: https://github.com/zjffdu/bkzep

**Comment by bryevdv** [comment]
By way of being helpful I will point to this PR:

https://github.com/bokeh/bokeh/pull/9798/files

That made a change that should have occurred in the 2.0 release, to make sure that SRI hashes were used consistently, even in notebooks. From the POV of our users, this change in 2.0.1 is purely internal and not a breaking change. Evidently `bkzep` will need to adjust to accommodate this change even tough it is a micro release, but they are in a unique category and there's no specific contract we have promised around these low level details.

**Comment by marzuqikram** [comment]
Fixed this issue by adding bundle into AUTOLOAD_NB_JS.render in bkzep io.py file.


```
js = AUTOLOAD_NB_JS.render(
        bundle = bundle_for_objs_and_resources(None, Resources(mode=settings.resources())),
        elementid = '' if hide_banner else element_id,
        js_urls  = resources.js_files,
        css_urls = resources.css_files,
        js_raw   = resources.js_raw + [custom_models_js] + ([] if hide_banner else [FINALIZE_JS % element_id]),
        css_raw  = resources.css_raw_str,
        force    = True,
        timeout  = load_timeout
```

**Comment by Xiezhibin** [comment]
One workaround is not using bkzep (At least bokeh 2.x doesn't need bkzep.
bokeh v2.3.0
zeppelin v 0.9.0
python v3.7.9
centos 7.6(Unionpay Cloud)

```
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()
fig = figure()
fig.line([1,2], [3,4])
show(fig)
```
