### ISSUE TITLE
Code quality refactoring

### ISSUE THREAD

**Issue by auirarrazaval** [bokeh/bokeh#9855]
I was doing a code quality analysis with [SonarQube](www.sonarqube.org) on Bokeh and came through several refactoring candidates that may be addressed quickly and I believe would benefit the overall project. Some of them may be minor bugs but still.
Here are the main issues (that may be repeated througout the code)

### Readability issues

- Nested ```if``` statements that may be merged:

```python
if condition1:
    if condition2:
        # ...
```
to 
```python
if condition1 and condition2:
        # ...
```

### Maintainability Issues

- Repeated constants should be assigned to variable for easier future refactoring. 

### Efficiency

- In cycles (for/while) the use of if/elif and continue/break to improve performance and excecution time when its not necesary to excecute the remaining code

### Cognitive complexity

- Some functions are very cognitively complex, some of them could be eithermodularized or simplified. Some of the issues mentioned beforehand even reduce complexity in some of them.

### Repeated turnouts in conditions

[plots.py](https://github.com/bokeh/bokeh/blob/master/bokeh/models/plots.py#L357) has the same result for the if and elif conditions. It can be replaced by the ```or``` operator as its more efficient and clear. (or stops checking the remaining conditions once it finds a ```True```) run this code if you dont believe me:
```python
def f():
	print("text")
	return False
print(True or f())
```

### switch case issues

- Some switch functions are missing the break after each ```case``` test, making the switch statement lose its puropose. (both cases are completely different) 
- ~Also, when evaluating ```case a || b```, only ```a``` is considered. Should be wrapped around parenthesis or considered as two separate cases [templating.js line 35](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/core/util/templating.ts#L35)~

### indent and curly braces in if/else {}

This is just a good practice and a very minor issue, but it improves readability for future maintainers

### Missing type in [```palettes.ts```](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/api/palettes.ts)
- Set3 considers Set3_11 twice and doesnt consider Set3_12

####  length >= 0
- In [index_filters.ts](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/filters/index_filter.ts) line 32 an array length is checked to be greater **or equal** than 0... Is this a mistake or on purpose?

Is it alright if I fix these issues and submit a PR? If any of them are intentional for some reason, please let me know :+1:

**Comment by bryevdv** [comment]
@auirarrazaval These are fairly disparate and not all of them are described at a level of detail that affords evaluation here. I would suggest making individual PRs so that things can be considered individually. @mattpap has strong opinions regarding code style and will likely want to comment.

**Comment by auirarrazaval** [comment]
@bryevdv Yes that's what I thought, it wouldn't make sense to have only one PR for all of this, as changes differ regarding each issue, i was thinking of making one for each of the prevoiusly mentioned points

**Comment by auirarrazaval** [comment]
I will wait on what @mattpap has to say about this

**Comment by bryevdv** [comment]
Regarding things I do feel there is enough information to comment on immediately:

* `palettes.ts` - this is certainly a copypasta bug and should be fixed

* `templating.ts` case statement - I don't really understand the comment. That case is already wrapped in parens, and certainly cannot be split up (that case represents inclusion in a range)

* if / or - everyone here is aware of Python's short-circuiting booleans :) I am often in favor or this to simply assignments from nullable quantities, e.g `foo = bar or baz`. I would be -1 on just having bare `or` expressions to replace `if/else` that don't assign.

**Comment by bryevdv** [comment]
@auirarrazaval I would go ahead and start submitting PRs. It's not really possible to comment on all the things above currently, since it's not always clear what exactly you intend to change. A PR is a concrete thing that can be commented on.

**Comment by auirarrazaval** [comment]
@auirarrazaval I just re-checked the ```templating.js``` issue and it was my bad, it works just fine.
Ill start submitting PRs then 👌 
Thanks!

**Comment by mattpap** [comment]
This should have been submitted as a set of issues, then it would have been easier to address particular problems and filter out that is and what isn't worthwhile. Each point should have been accompanied by an example (a link to a case of offending code), because in some cases I'm not certain what you are referring to.

**Comment by mattpap** [comment]
> Set3 considers Set3_11 twice and doesnt consider Set3_12

This is an obvious bug. What would be useful in this case, is to understand why tsc doesn't complain about this. Perhaps there are some compiler options that could be enabled to make our setup stricter. Otherwise maybe there are `typescript-eslint` rules that could help in pointing this kind of bug out. If there are none, including in third-party rulesets, then maybe you could contribute one?

**Comment by mattpap** [comment]
> In index_filters.ts line 32 an array length is checked to be greater or equal than 0... Is this a mistake or on purpose?

This seems to be an artifact from transition from coffeescript to typescript. Once again, a `typescript-eslint` rule would be in order, to make sure this doesn't happen again (I doubt this could be expressed at the type system level).

**Comment by auirarrazaval** [comment]
@mattpap I've been looking into ```typescript-eslint``` rules that could satisfy that could help, but for the array lenght issue its actually [impossible to track](https://github.com/typescript-eslint/typescript-eslint/issues/1831). I wil still try to look into the ```palettes.ts``` rule

**Comment by bryevdv** [comment]
@auirarrazaval  I am going to go ahead and close this discussion issues. The ones remaining deserve a bit more detail in their own issues, should you want to go forward with them individually.
