### ISSUE TITLE
Release commits

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9857]
This is currently at the `HEAD` of `master` branch:
```
commit 4423d6d4753b2f3b36a2c83bb8e863baf2b94351 (HEAD -> master, origin/master, origin/HEAD)
Author: Bryan Van de Ven <bryan@bokeh.org>
Date:   Mon Mar 30 18:16:20 2020 -0700

    remove notebook

commit d48306fe0fc2cd82f1d2149297bfe92196de35d2
Merge: 4af967f9c 488bf7941
Author: Bryan Van de Ven <bryan@bokeh.org>
Date:   Mon Mar 30 17:55:04 2020 -0700

    Merge branch release-2.0.2dev1

commit 488bf7941837d2a84d11f71a73579b827d188c8b (tag: 2.0.2dev1)
Author: Bryan Van de Ven <bryan@bokeh.org>
Date:   Mon Mar 30 17:48:01 2020 -0700

    Updating for version 2.0.2dev1

commit 755412e2a5875262226bc09f40d71284ebae4eaf
Author: Bryan Van de Ven <bryan@bokeh.org>
Date:   Mon Mar 30 17:48:01 2020 -0700

    Updating for version 2.0.2dev1

commit 60a8683c2cb7c0377f100f55c8ce827d463551c1
Author: Bryan Van de Ven <bryan@bokeh.org>
Date:   Mon Mar 30 17:48:01 2020 -0700

    Updating for version 2.0.2dev1

commit 3f3e159bd1f771f7eeffb789dfff52c9879540c9
Author: Bryan Van de Ven <bryan@bokeh.org>
Date:   Sat Mar 28 15:30:09 2020 -0700

    checkpoint
```
What's the purpose of having three commits with the same message per release? I understand that it's one change per commit. How does that scale with increasing number of publishable artifacts (per issue #9296)? Shouldn't those commits be squashed, especially when non-descriptive commits like "checkpoint" are present?

On an orthogonal note, a tag was introduced but no artifacts were published to neither anaconda.org nor npmjs.com. Is this a bug or a feature? I would expect the later.

**Comment by bryevdv** [comment]
@mattpap The work to restore build automation capability is *very much* still a work a progress. It is slow, and tedious, and (most unfortunately) at some point you have to start testing things that make real changes, which carries risk. I'm still the process of restoring "dry run" capability, which will help somewhat

> What's the purpose of having three commits with the same message per release?

There's a combined change+commit operation for each file that gets a version string automatically updated. FWIW this is not new, and is how things have operated for years. Happy to consider improvements. (e.g. make all changes first as a batch then one commit at the end, or figuring out the CLI to squash things)

> checkpoint
> a tag was introduced but no artifacts were published to neither anaconda.org nor npmjs.com. . Is this a bug or a feature? 

Neither. I was testing some machinery and killed the process part way through. I intend to delete the tag, just have not done so yet.
