### ISSUE TITLE
[BUG] Node12 import error bokeh 2.0

### ISSUE THREAD

**Issue by bsdis** [bokeh/bokeh#9862]
When trying to use bokehjs together with npm and create-react-app the compiler gives an error.
This can be easily reproduced by building the following dockerfile and running it after

```
FROM node:12
WORKDIR /usr/src/app
RUN npx create-react-app bokehbug --template typescript
WORKDIR /usr/src/app/bokehbug/src
RUN wget https://gist.githubusercontent.com/bsdis/415a77d017c32d2678cefd9a0a23fb22/raw/83a7a91fb82420a550b8ad66f8001034fc1dab69/App.tsx -O App.tsx
WORKDIR /usr/src/app/bokehbug
RUN wget https://gist.githubusercontent.com/bsdis/415a77d017c32d2678cefd9a0a23fb22/raw/83a7a91fb82420a550b8ad66f8001034fc1dab69/package.json -O package.json
RUN npm install
CMD npm start
```

Build this dockerfile by first installing docker and then use `docker build -t bbug .`.
To see the error after building, run:

`docker run -it --name bokehbug -p 3000:3000 bbug bash`

and when in the container run 

`npm start`

The observed error is:

```
zuifrontend_1  | Failed to compile.
zuifrontend_1  |
zuifrontend_1  | ./node_modules/@bokeh/bokehjs/build/js/lib/index.js 3:9
zuifrontend_1  | Module parse failed: Unexpected token (3:9)
zuifrontend_1  | File was processed with these loaders:
zuifrontend_1  |  * ./node_modules/babel-loader/lib/index.js
zuifrontend_1  | You may need an additional loader to handle the result of these loaders.
zuifrontend_1  | | export { version } from "./version";
zuifrontend_1  | | export { index } from "./embed";
zuifrontend_1  | > export * as embed from "./embed";
zuifrontend_1  | | export * as protocol from "./protocol";
zuifrontend_1  | | export * as _testing from "./testing";
```

I believe the error is caused by use of Ecmascript in certain modules which the underlying configuration of webpack in create-react-app cannot handle. 
Therefore this bug maybe belongs more in create-react-app issue tracker - i am not sure.

If there is some easy solution to this which i fail to see, let me know. 
I was urged to create an issue here after first posing question in discourse channel: https://discourse.bokeh.org/t/node12-import-error-bokeh-2-0/5061

**Comment by bsdis** [comment]
The TRIAGE label was added automatically (not by me)

**Comment by mattpap** [comment]
Resolved in discourse.
