### ISSUE TITLE
[FEATURE] Reflect bivariate scatter styles in legend

### ISSUE THREAD

**Issue by BenPortner** [bokeh/bokeh#9867]
Say we have a df with 4 columns- a, b, c, d. a and b are numbers, c and d contain categorical values. We want to make a scatter plot, with `x=a`, `y=b`, `color=c` and `marker=d`. This is already possible using transformations. How ever, it is not possible to create a legend which documents the meaning of the colors and markers at the same time. Using the `legend_field` attribute, one can document either the markers or the colors. It would be nice to have the possibility to document both. A good example of how the legend should look like comes from the [seaborn documentation](https://seaborn.pydata.org/generated/seaborn.scatterplot.html):

`ax = sns.scatterplot(x="total_bill", y="tip", hue="day", style="time", data=tips)`
<img src=https://seaborn.pydata.org/_images/seaborn-scatterplot-4.png></img>

**Comment by bryevdv** [comment]
@BenPortner  Please provide a sample that generates everything except the legend, that can be used or testing and development.

**Comment by BenPortner** [comment]
Here is an example. I adapted it from the [documentation](https://docs.bokeh.org/en/latest/docs/user_guide/data.html#transforming-data). In the docs, the `species` column is used for both `color` and `marker`. I added a fourth categorical column `scent` which I map to the `colors`. The `markers`are still maped to the `species`. The scent is spicy for setosa and versicolor and sweet for virginica. Hence, both are blue. There are two entries in the legend: `spicy`and `sweet`. There are no entries explaining the different markers mapping the species.

```python
from bokeh.plotting import figure, show
from bokeh.sampledata.iris import flowers
from bokeh.transform import factor_cmap, factor_mark

SPECIES = ['setosa', 'versicolor', 'virginica']
MARKERS = ['hex', 'circle_x', 'triangle']
SCENT = ['spicy', 'spicy', 'sweet']

flowers['scent'] = flowers['species'].map({k:v for k,v in zip(SPECIES, SCENT)})

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Sepal Width'

p.scatter("petal_length", "sepal_width", source=flowers, legend_field="scent", fill_alpha=0.4, size=12,
          marker=factor_mark('species', MARKERS, SPECIES),
          color=factor_cmap('scent', 'Category10_3', SCENT))

show(p)
```

**Comment by bryevdv** [comment]
I suppose from a syntax POV the solution is to allow 
```
legend_field=("scent", "species")
```
but I am not sure what amount of work that would be. Given that there does not seem to be a high demand for this, and also that such a legend could be constructed manually from individual `LegendItem` objects (instead of using `legend_field`) I think I am inclined to close this for now, unles/until more community interest is displayed.

**Comment by BradenAnderson** [comment]
I have spent awhile now trying to figure out how to do this. Any chance there is an update?

**Comment by BradenAnderson** [comment]
@bryevdv could you please provide an example of how the legend could be created manually using LegendItem?
