### ISSUE TITLE
[BUG] TableColumn doesn't use `field` when `title` is not set

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#9871]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.0.1

#### Description of expected behavior and the observed behavior
The docstring of `TableColumn.title` says: "If not set, column's data field is used instead."
But this is not the case, the title becomes `null` instead.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.io import show
from bokeh.models import DataTable, TableColumn, ColumnDataSource

cds = ColumnDataSource(dict(value=[1, 2, 3]))
dt = DataTable(columns=[TableColumn(field='value')], source=cds)
show(dt)
```

**Comment by bryevdv** [comment]
Tho actually looking at the code. I am not sure what `title` is even for? There is `header` that controls the column header. What is `title` for  a column?

**Comment by p-himik** [comment]
Why would they need to know about sources? The values are not specs, they're just plain strings - they don't interact with the sources in any way. Probably the fix could be as simple as `name: this.title || this.field,`

**Comment by bryevdv** [comment]
Yup, sorry, reading things in too much of a hurry. Should just delegate to `field` as you say
