### ISSUE TITLE
[BUG] BoxAnnotation doesn't respect fill_color=None

### ISSUE THREAD

**Issue by lucius-messerer** [bokeh/bokeh#9877]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 2.0.0 | Python 3.7 | Firefox 74.0 | Windows 10 build 16299.1747

#### Description of expected behavior and the observed behavior

Expected behavior: Glyphs generally support turning off fill by supplying a `fill_color` value of `None`. Would expect the same from `BoxAnnotation`.

Observed behavior: `BoxAnnotation` (and maybe others? haven't tested) instead appears to have a white fill with a low (but nonzero) alpha under these conditions. Setting `fill_alpha` to zero has the desired effect, but this is not my standard usage pattern for turning off fill, and it should probably be consistent anyway.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import bokeh.plotting
import bokeh.models

bokeh.plotting.output_file("box_annotation_test.html")

fig = bokeh.plotting.figure(width=500, height=500, x_range=[0, 3], y_range=[0,3])

fig.circle(x=[1, 1, 2, 2], y=[1, 2, 1, 2], size=100, line_color=None, fill_color="Red")

ba = bokeh.models.BoxAnnotation(bottom=1, top=2, left=1, right=2, line_color="Blue",
                                line_dash="dotted", fill_color=None)
fig.add_layout(ba)

bokeh.plotting.save(fig)
```

#### Screenshots or screencasts of the bug in action

![bokeh_plot](https://user-images.githubusercontent.com/63124336/78400812-631be100-75c5-11ea-9b70-69fe4b51d8e4.png)

The `BoxAnnotation` is drawn between the centers of the red circles. Notice the "notches" of paler red where the box intersects them.

**Comment by bryevdv** [comment]
Right, it's currently not explicitly checking for `null` condition on the JS side, so it is rendering "null" color with a default opacity of 0.4 (whatever canvas defines that to do). For now you can add `fill_alpha=0` as a workaround:

<img width="502" alt="Screen Shot 2020-04-03 at 1 48 25 PM" src="https://user-images.githubusercontent.com/1078448/78403841-fba86600-75b1-11ea-8542-6ef9445dff41.png">

Since it should be a simple fix and since there a a workaround I will leave it for now a `Good First Issue`

**Comment by Tekaichi** [comment]
We can then assume when fill_color = None, fill_alpha should be set to zero then?
If so, I'm opening a PR with this fix.

**Comment by mattpap** [comment]
> We can then assume when fill_color = None, fill_alpha should be set to zero then?

No, `fill_color == None` means no rendering should happen. The value of `fill_alpha` in this situation is irrelevant.

**Comment by Tekaichi** [comment]
Both the lines and the background should not be rendered then or  just the background (which happens if fill_alpha = 0)?

**Comment by mattpap** [comment]
Line and fill visuals should be considered independently, the same way as glyphs work. Essentially you have to replace:
```ts
 this.visuals.fill.set_vectorize(ctx, i)
ctx.fill()
```
with
```ts
if (this.visuals.fill.doit) {
  this.visuals.fill.set_vectorize(ctx, i)
  ctx.fill()
}
```
and similarly change `line` visuals.

The tricky bit is that annotations have both canvas and CSS modes. This code only handles to former and you will have to figure out the later.

**Comment by Tekaichi** [comment]
Ok, thanks for the feedback! Fixing that on the PR!
