### ISSUE TITLE
server event loop methodology

### ISSUE THREAD

**Issue by hhuuggoo** [bokeh/bokeh#988]
This is my mental model of how the server event loop should work.  During an update on the server, this is what happens https://github.com/ContinuumIO/bokeh/blob/master/bokeh/server/views/backbone.py#L162
- document is loaded from redis
  - raw json is naively turned into PlotObjects (no references are resolved, no events are used)
  - second pass through the object chain resolves all the references to other objects
- new json is loaded from the web request into an existing backbone object
- this update triggers events on changed properties
- changed objects are pushed out over websockets

The important thing, is that we don't want to process events until all objects are created (or else you can't really bind to other objects)  We currently have 2 constructs for doing this,

-  there is a _block_callbacks flag on a PlotObject which will tell plot objects to not execute events on changes, rather store them to be executed later. This was the original mechanism that used to induce this functionality.
-  In addition during the 2 pass object initialization, it looks like now a second mechanism for doing this has appeared, In https://github.com/ContinuumIO/bokeh/blob/master/bokeh/document.py#L230, if an object is new (not loaded yet)  we don't setup any events, but instead we setup events during the finalize loop.  If an object is already existing, then we allow events to be triggered.

I think the second (newer) mechanism that @mattpap  wrote (I think?) is better than the original.  I would advocate removing all concepts of _block_callbacks, and callback_queues, I think they are quite complicated and un-necessary.  And definitely having 2 constructs in there is redundant I believe.

Then I think the logic is rather clear

- load json from redis
- Turn json into naive backbone objects
- resolve references
- setup events

load new json from http request

- update models

One concept we would have to preserve when eliminating the first approach is to make sure that the client can specify whether or not they want to trigger events or not during the update.  This is because in the python client is capable of processing events, so we can assume that all necessary events/changes have already occured on the client side and the server does not need to do anything.

cc @mattpap @bryevdv @pzwang @kdodia

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
