### ISSUE TITLE
[BUG] saving bokeh example notebooks causes notebook validation errors

### ISSUE THREAD

**Issue by dbuscher** [bokeh/bokeh#9892]
### Summary

Many of the notebook files provided in the examples directory trigger an error message in nbformat versions > 5.0.0. This appears to be the same problem as mentioned here: https://github.com/jupyter-widgets/ipywidgets/issues/2788. 

The work-around is to manually edit the ipynb files in a text editor to change the value of nbformat_minor to 2. This bug report serves to help those who find this problem while trying out the bokeh examples.

#### ALL software version info

bokeh: 2.0.0
notebook server: 6.0.3
Python 3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]
nbformat version: 5.0.4
OS: MacOS

#### Description of expected behavior and the observed behavior

Open a notebook in the bokeh examples directory, for example

examples/howto/notebook_comms/Basic Usage.ipynb

Execute the first cell.

Save the notebook.

Expected behaviour: saves the notebook with no problems

Observed behaviour: The notebook is saved, but a large error popup appears (see below). This happens every time the notebook is saved or autosaved, so gets annoying really fast.

#### Stack traceback and/or browser JavaScript console output

The save operation succeeded, but the notebook does not appear to be valid. The validation error was:

Notebook validation failed: 'application/vnd.bokehjs_load.v0+json' does not match any of the regexes: '^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$':

*truncated for brevity*

**Comment by bryevdv** [comment]
bumping the minor number seems to be stated as the preferred solution in the linked issue. @dbuscher would you mind making a PR to update the notebooks in this repo accordingly?
