### ISSUE TITLE
[BUG] Hard dependency on IPython, unable to use bokeh in xeus-python

### ISSUE THREAD

**Issue by jahmed-invn** [bokeh/bokeh#9894]
The only kernel that supports Jupyter Debugging protocol is xeus-python but there is a hard dependency of bokeh on IPython in publish_display_data  in output_notebook() function which renders it to be not used in any other kernel other IPython. Is there a work in progress that gets rid of this dependency. Following is the traceback,
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
In  [4]:
Line 1:     output_notebook()

lib\site-packages\bokeh\io\output.py, in output_notebook:
Line 111:   run_notebook_hook(notebook_type, 'load', resources, verbose, hide_banner, load_timeout)

lib\site-packages\bokeh\io\notebook.py, in run_notebook_hook:
Line 298:   return _HOOKS[notebook_type][action](*args, **kw)

lib\site-packages\bokeh\io\notebook.py, in load_notebook:
Line 415:   publish_display_data({'text/html': html})

lib\site-packages\bokeh\io\notebook.py, in publish_display_data:
Line 426:   from IPython.display import publish_display_data

ImportError: cannot import name 'publish_display_data' from 'display' (unknown location)
---------------------------------------------------------------------------
```

**Comment by bryevdv** [comment]
@jahmed-invn I am not sure what you are proposing. The express purpose of `output_notebook` is to prepare for outputting Bokeh content in to Jupyter notebook (or Jupyterlab) output cells. That is it's only purpose, so getting rid of it does not really make sense, and there are no plans to do anything different. The import is protected inside the function tho. If you are not inside the notebook or JupyterLab, the answer is simply that you should not be calling that function.

**Comment by bryevdv** [comment]
I guess I'd like to add: I would *love* to be able to detect and condition on the currently running frontend(s).  I think it is a mistake, that makes life difficult for anyone developing integrations for Jupyter tools. But the Jupyter team has remained steadfast about not exposing that information for a decade or more now, and I don't think it is reasonable to expect they will ever change this position.

**Comment by philippjfr** [comment]
This is definitely **not** a bokeh issue, xeus-python is an alternative kernel for Jupyter, not a frontend, and messes with the internals of `IPython.display` see https://github.com/jupyter-xeus/xeus-python/issues/106.

**Comment by bryevdv** [comment]
Oh I see. I definitely agree this is not a Bokeh concern. @jahmed-invn If there is some very small change (e.g. adding one more level of function between the import, so that you yourselves could patch or something) that would make your life simpler, then I'm certainly willing to entertain a PR (with tests), should you want to submit one. But otherwise I am going to close this now.
