### ISSUE TITLE
Bundling and serving precompiled extensions in broken on windows

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9900]
Original issue in panel https://github.com/holoviz/panel/issues/1233.

**Comment by philippjfr** [comment]
Have you been able to confirm this? If not I can spin up a Windows machine later. Also this is a fairly major regression for us. @bryevdv How would you feel about a 2.0.2 sooner rather than later?

**Comment by mattpap** [comment]
Confirmed and fixed in PR #9901. I would target 2.0.2 for early next week.

**Comment by bryevdv** [comment]
Fine w/ me
