### ISSUE TITLE
Improve Auth Request Handler hierarchy

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9907]
`AuthMixin` is not a proper Mixin since it shadows methods on another base class. Move to just single inheritance as described in https://github.com/bokeh/bokeh/pull/9906#issuecomment-611855445

**Comment by ayushiitr2901** [comment]
You mentioned about renaming class `AuthMixin` to `BokehAuthRequestHandler`. Would it be better handled by creating a new file, defining the class `BokehAuthRequestHandler`, and adding a deprecation message to the old auth_mixin file.

**Comment by bryevdv** [comment]
I don't personally think there is any need for a deprecation on this, I think we can just take the change at 3.0 without anything else done up front. It's not part of any user-facing code paths, I can't imagine any scenario that any user would even know about this class much less be trying to use it directly.

**Comment by ayushiitr2901** [comment]
Oh, I get it. I agree the code part is not visible to the user directly and hence there is no need to give a deprecation message. I will go ahead and make the changes accordingly.

**Comment by bryevdv** [comment]
If a PR is made now, it will have to be against the `future` branch not `master`. This is a breaking change so it should go in a future 3.0 release, but that's probably quite a way off. I only meant that I did not think a deprecation was not necessary during the rest of the 2.x series leading up to 3.0.

**Comment by ayushiitr2901** [comment]
Oh apologies, I already made a pull request should I close it for now or mark it to the future branch?

**Comment by bryevdv** [comment]
@ayushiitr2901 No apologies necessary! Thinking a bit about it it might have been misleading to mark this as a `Good First Isssue` since it does have this extra consideration. 

I don't have a strong preference about merging now (against `future`) or closing and re-resubmitting nearer to 3.0. In general it's a bit of a pain to keep long running branches of parallel development, but @mattpap  has been tending to `future`. @mattpap do you want this in `future` now? or close and wait?

**Comment by mattpap** [comment]
> do you want this in future now? or close and wait?

I changed the base of PR #10011 to `future`, so it can be merged as soon as code quality issues are addressed. As to `future` branch itself, I backported all changes from that branch to `master` and reset it to `master`, so that we don't duplicated commits.

**Comment by bryevdv** [comment]
@mattpap it can't be merged into master now, if that is what you mean?  It is a breaking change so should go in 3.0 I would say in that case close for now and re-open when we are on final approach for 3.0

**Comment by ayushiitr2901** [comment]
I will look at the code bug in the PR and fix it. But, I agree with @bryevdv, this is a big change that can be merged in the next coming update as a big change.

**Comment by mattpap** [comment]
> It is a breaking change so should go in 3.0 (...)

That's why it should go into `future` branch. As I said, I changed the base of the PR to `future`, so it can be merged into that branch as soon as test failures are sorted out.
