### ISSUE TITLE
Lux & page styles

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#991]
from @pzwang 

>https://github.com/cscheid/lux

>To get started, you just chdir into the checkout, and then run "python -m SimpleHTTPServer 8888", then go to http://localhost:8888.

>This takes you to a simple but pretty page (with nice background and great font) listing live demos and the tutorial.

>We could do similar with an executable python script, that would display an index page and then link the standalone examples, the Ipython notebooks for the tutorial, my 5-minute overview notebook, etc. etc.

**Comment by bryevdv** [comment]
Moving this kind of thing to the Wiki: https://github.com/bokeh/bokeh/wiki/Other-Projects-of-Interest
