### ISSUE TITLE
[BUG] The footer on the documentation website extends past its visible area

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#9915]
For example, this page: https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html

Notice how the `::before` pseudo-element covers the link at the bottom, making it unclickable but for a few pixels at the top.

![image](https://user-images.githubusercontent.com/4410314/79045212-989e7b00-7c12-11ea-8b3f-9e93954fe209.png)

**Comment by Kraboobee** [comment]
I've just adjusted the CSS, and I think I've fixed the issue. I'll make a PR shortly.
