### ISSUE TITLE
[BUG] Example For 'DateTime Axes' On user_guide/quickstart.html needs modification

### ISSUE THREAD

**Issue by Rubix982** [bokeh/bokeh#9917]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh: `2.0.1`
Python: `3.8.1`
Notebook: `6.0.2`, though I'm running the file on a terminal
OS: `Linux archlinux 5.5.3-arch1-1 #1 SMP PREEMPT Tue, 11 Feb 2020 15:35:41 +0000 x86_64 GNU/Linux`

#### Description of expected behavior and the observed behavior

Example for `datetime axes` on the page `user_guide/quickstart.html`, [here](https://docs.bokeh.org/en/latest/docs/user_guide/quickstart.html), does not work correctly. 
Line 3, which is,
```
from bokeh.sampledata.stocks import AAPL
```
runs into a problem when ran with `python datetime_axes.py`. where it complains that it cannot find the sample data on the machine. It also provides the immediate solution, which is to just use the method, `bokeh.sampledata.download()` to download the sample data locally first. 

Including the below code,
```
import bokeh
bokeh.sampledata.download()
```
at the top of the file **immediately** fixes this issue,  though nothing like this is mentioned in the `quickstart.html` page.

#### Complete, minimal, self-contained example code that reproduces the issue

A fresh install of bokeh using `pip install bokeh`,

And running the code for `datetime axes` on the page `user_guide/quickstart.html`, [here](https://docs.bokeh.org/en/latest/docs/user_guide/quickstart.html), or saving you a click, run the below code
```
import numpy as np

from bokeh.plotting import figure, output_file, show
from bokeh.sampledata.stocks import AAPL

# prepare some data
aapl = np.array(AAPL['adj_close'])
aapl_dates = np.array(AAPL['date'], dtype=np.datetime64)

window_size = 30
window = np.ones(window_size)/float(window_size)
aapl_avg = np.convolve(aapl, window, 'same')

# output to static HTML file
output_file("stocks.html", title="stocks.py example")

# create a new plot with a datetime axis type
p = figure(plot_width=800, plot_height=350, x_axis_type="datetime")

# add renderers
p.circle(aapl_dates, aapl, size=4, color='darkgrey', alpha=0.2, legend_label='close')
p.line(aapl_dates, aapl_avg, color='navy', legend_label='avg')

# NEW: customize by setting attributes
p.title.text = "AAPL One-Month Average"
p.legend.location = "top_left"
p.grid.grid_line_alpha = 0
p.xaxis.axis_label = 'Date'
p.yaxis.axis_label = 'Price'
p.ygrid.band_fill_color = "olive"
p.ygrid.band_fill_alpha = 0.1

# show the results
show(p)
```

Using `python datetime_axes.py`.

#### Stack traceback and/or browser JavaScript console output

Not related to JS - it's just Python.

#### Screenshots or screencasts of the bug in action

![image](https://user-images.githubusercontent.com/41635766/79051320-006fb880-7c49-11ea-8c72-eafe6d32dc5d.png)

Thank you, and have a nice day!
Would like to make a pull request to just edit in the two lines myself ( or just a note before the code ), but I was expecting a folder called `docs`, or `web` which is most commonly used to contain the documentation, so I don't know exactly where to make the modification.

**Comment by bryevdv** [comment]
@Rubix982 The sample data only needs to be downloaded a single time, so it would not be advised to add code to the script itself, which would cause re-download attempts every single time the code is run. We normally advise users to use the command line `bokeh sampledata` to get the data. And in fact, there is a section earlier up in the Quickstart that explicitly states this, and also that many examples assume the sample data is present:

https://docs.bokeh.org/en/latest/docs/user_guide/quickstart.html#sample-data

However, if you would like to add a note above the code that links back to the `SampleData` section (using Sphinx link syntax, not a raw URL) that emphasizes that the sample data is assumed, would be happy to accept it.

**Comment by Rubix982** [comment]
Sure, I'll add a note myself there. Thank you.

**Comment by bryevdv** [comment]
sample datasets are now handled more simply by a separate pip-installable `bokeh_sampledata` and any error conditions should report actionable errors, so I will close this now.
