### ISSUE TITLE
Example script tags in docs should be version-correct with SRI hashes

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9919]
There are a few places where we show example BokehJS script tags on some fixed version. These should be rendered with a Sphinx plugin that makes them version-correct for the current version of docs and also includes SRI hashes.

**Comment by bryevdv** [comment]
Some notes for any new contributor:

* Dev Guide for getting set up and running is [here](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html)

* here are some locations:

  https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/installation.rst
  https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/embed.rst

* If looking in to a sphinx extension, those are located here:

  https://github.com/bokeh/bokeh/tree/master/bokeh/sphinxext

**Comment by teresafds** [comment]
I'm interested in work on this issue, but I have the following doubts: 
* In the locations links provided by you, some NodeJS script tags have fixed versions (but using them as an example). Is the idea to replace them too (I mean, to replace all of them)?
* Also, there are some python libraries with fixed versions (as specified on location:  https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/installation.rst). Is the idea to handle those too? 

Thanks.

**Comment by santos22** [comment]
Is the following issue related? https://github.com/bokeh/bokeh/issues/9982

**Comment by bryevdv** [comment]
Not exactly. In that case there were real scripts being loaded to render actual Bokeh content. This issue is more about the places where adding BokehJS scripts tags is *documented*, e.g:

<img width="967" alt="Screen Shot 2020-05-20 at 10 17 56 AM" src="https://user-images.githubusercontent.com/1078448/82476726-56731f80-9a83-11ea-8580-1b6d8d162283.png">


That section is a mess, have various different versions demonstrated, some of which show how to use SRI hashes and some don't. This issue is about being consistent in what we document/demosntrate, and automating things so that versions match up with the actual docs version without requiring manual updates. We might want to se if there is API (or could be new API) to just spit out these script tags with SRI hashes automatically for users, in which case we should probably start by showing how to use that instead of how to make these script tags by hand.

**Comment by santos22** [comment]
I see. Would the following work for outputting version correct script tags?

- add a new option to bokehjs_content.py called `js_files` which is a comma-separated string of Bokeh JS components you want to include
- if this option is provided, return an HTML code block with script tags only for the JS components that were included

I think this overloads the `bokehjs-content` directive a bit but all of necessary code (e.g. `get_codeblock_node()` is in this file already to make this work. The alternative would be to create a new directive with and copy over the `get_codeblock_node()` method.

**Comment by bryevdv** [comment]
Closing since SRI hashes will no longer be included by default starting in 2.4
