### ISSUE TITLE
Set themes using bokehjs

### ISSUE THREAD

**Issue by ashvin777** [bokeh/bokeh#9920]
How can we set dark_minimal in JavaScript version of bokehjs ? There is no example available for it.

**Comment by mattpap** [comment]
Themes are a bokeh feature and currently there is nothing equivalent available in bokehjs.

**Comment by bryevdv** [comment]
@ashvin777 this issue should not be closed, @mattpap has triaged it indicating interest to work on it at some point.

**Comment by mattpap** [comment]
I've been actually working on this this week, so that new bokeh's latex examples can be ported to bokehjs.

**Comment by ashvin777** [comment]
Great thanks!

**Comment by shimondoodkin** [comment]
` Bokeh.require("core/properties").use_theme(Bokeh.Themes.night_sky)`
