### ISSUE TITLE
AutocompleteInput has no case insensitive option  

### ISSUE THREAD

**Issue by gmanolia** [bokeh/bokeh#9922]
Is there a way to have AutocompleteInput to be case insensitive?

For example when I type in "book" and in the completions there is a keyword named "Book of the Jungle" then there is no match. 

Is there an option that I am missing ?

**Comment by bryevdv** [comment]
@gmanolia You are correct the only current option is for case-sensitive comparison. I think this should be a fairly straightforward add, so I have marked it `good first issue`. Would you be interested to work on this, with some help/guidance?

**Comment by bryevdv** [comment]
Some notes for any new contributor:

* Dev Guide for getting set up and running is [here](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html)

* On the Python side, the `AutocompleteInput` is defined in here:

  https://github.com/bokeh/bokeh/blob/master/bokeh/models/widgets/inputs.py

  It woudl need to get a new property to control this new behaviour. Possibly a `Bool` to toggle case sensitive or not. But if we imagine more other kinds of policies it might be better to start with a policy `Enum`

* The BokehJS code to find "startswith" completions is here:

  https://github.com/bokeh/bokeh/blob/379f644e5133a1ecdba3ecf73395df0957213aa8/bokehjs/src/lib/models/widgets/autocomplete_input.ts#L141-L145

 Best would be to factor that into a method that conditions on the policy(s) that is set (case insensitive, startswith vs inclusion, etc.) to return an appropriate set of comlpetions.

**Comment by krisward1** [comment]
I'm looking to help with this issue.

**Comment by dwsideriusNIST** [comment]
Is the syntax for this feature non-standard? When I try to set up a case-insensitive autocomplete box, i.e.:

`self.inp_box = panels.widget.AutocompleteInput(
            name='the name',
            options=list_of_options,
            placeholder='placeholder_value',
            case_sensitive='False'
        )`

the following error is returned:

`Setting non-parameter attribute case_sensitive=False using a mechanism intended only for parameters`

I'm running Python 3.6.10, from the Anaconda distribution, with bokeh 2.1.1
