### ISSUE TITLE
Add hatch rendering to Box Annotation

### ISSUE THREAD

**Issue by smartyal** [bokeh/bokeh#9929]
the hatch pattern on varea appears/disappears on zoom. I wanted to create a vertical span with hatch pattern. The only way I could find is creating a varea which is very high compared to the data, so it will always span the entire height. When zooming in and out, the hatch pattern can disappear 

bokeh 2.01 on python 3.6.5 (anaconda), win 10
```
from bokeh.plotting import figure, output_file, show

output_file("hatch.html")
length = 200
small = 0.0001

y = [ 20 +0.0001*i for i in range(length)]
x = list(range(length))
p = figure(plot_width=400, plot_height=400)
p.line(x,y)
yLim = 1000000 #try 100 here, it works
p.varea(x=[length*0.25,length*0.75],y1=[-yLim,-yLim],y2=[yLim,yLim],hatch_color="black",hatch_pattern="v",hatch_alpha=1,fill_alpha=0.5)
#p.vbar(x=length*0.5,top=yLim,bottom = -yLim,width=length*0.5,hatch_color="black",hatch_pattern="v",hatch_alpha=1,fill_alpha=0.5) #this one works as well

p.y_range.start = min(y)
p.y_range.end = max(y)
show(p)

```
on start, the hatch pattern is not visible, now zoom out to see the hatch pattern 
it also works when changing the height of the varea to 100 or using the vbar

**Comment by mattpap** [comment]
The proper way would be to use `BoxAnnotation`, which can be configured to span plot's frame in one dimension and hook it into the data space in the other. However, it doesn't support hatch patterns currently.

**Comment by bryevdv** [comment]
@smartyal unfortunately the HTML browser canvas has various limitations that we can't do much about, and drawing things much larger than the viewport is one instance of that. As @mattpap notes this would best be handed by adding hatching support to `BoxAnotation`. That should be fairly simple to do so I have marked this `Good First Issue` and adjusted the title accordingly. If you would be interested to take a crack at it we are always happy to help new folks get started.

**Comment by smartyal** [comment]
I actually thought already several times about digging into the bokeh software and contribute as I have built many workarounds already and need deeper integration into my project especially on the frontend. I'm currently pretty busy but I have somebody in my team, let's see -  I'll come back to you. If you are faster with the feature this time, we have plenty more ideas ... :)

**Comment by bryevdv** [comment]
Some notes for any new contributor:

* Dev Guide for getting set up and running is [here](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html)

* Now that the work to remove CSS render modes has been merged, this will be even simpler. On the Python side you would add a property similar to the one in `Grid`

  https://github.com/bokeh/bokeh/blob/6639b36f931e3dc0790b8a00a3c40c1e93c25f7a/bokeh/models/grids.py#L113-L115

* The on the JS side it would be *similar* to how things are done in `grid.ts`:

  https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/grids/grid.ts
