### ISSUE TITLE
[FEATURE] Plot pandas dataframe with index and columns (and nans)

### ISSUE THREAD

**Issue by dickreuter** [bokeh/bokeh#9936]
I think it should be made possible to plot a pandas pivot e.g. df.pivot_table(index=['x'], columns=['y'], values=['z'], aggfunc=sum) with Bokeh.

With matplotlib it's no problem, but it appears there are two issues with Bokeh: 
- It cannot iterate over the columns (as each one needs to be a separate line or circles)
- It doesn't support nan

**Comment by bryevdv** [comment]
@dickreuter I'm going to ask to move this to the Discourse for now:

https://discourse.bokeh.org/

As presented, it seems like more of a support issue (e.g. Bokeh can handle nans in many places) and fi there is ideas for new feature work that arise form a Discourse discussion, then a new issue can be opened with a more fleshed-out proposal (i.e. actual code comparisons of current vs desired, potential API, etc)
