### ISSUE TITLE
Deprecate CSS rendering modes for annotations

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9941]
Currently the `BoxAnnotation` is used as an annotation and also as an overlays like `BoxZoomTool`. To support the interactive use cases `BoxAnnotation` has a "CSS mode". But this mode is never generally useful to user code and can't support all the options the canvas version does, making developing `BoxAnnoation` (e.g. to add hatching) more difficult. This is  both confusing and complicated. Propose:

* Splitting CSS box rendering into `BoxOverlay`
* Deprecating CSS mode in `BoxAnnotation`
* Making tools use `BoxOverlay`
* Removing CSS mode from `BoxAnnotation` at 3.0

We could also removing CSS mode immediately, and simply ignoring the setting (with a warning/deprecation that it will raise an error at 3.0)

Potentially the same could be done for `PolyAnnotation`, which might make the lasso tool faster on all platforms as a result, as well. (Note there is nothing to *split* here as `PolyAnnotation` does not have a CSS mode. But we could add a `PolyOverlay` for API consistency and performance).

cc @bokeh/dev

**Comment by mattpap** [comment]
I actually implemented a variation of this idea a few months back, as a part of a bigger chunk of work. I extracted relevant changes into PR #9948. The main difference is that CSS mode is dropped completely and overlays are painted on a secondary canvas. Primary canvas is not repainted if only overlays changed, making this comparably efficient to the current implementation.

**Comment by yinyea** [comment]
how we can do the same after the "render_mode" Deprecate? (Im have an annotation that's on top on the canvas but after the render_mode is gone, the annotation is hidden behind the axis :( )

**Comment by mattpap** [comment]
There are `HTML*` variants for annotations where it makes sense, so e.g. `Label` has `HTMLLabel` variant, which are equivalent to the original `Label(render_mode="canvas")` and `Label(render_mode="css")` respectively. For some annotations non-canvas rendering doesn't make sense, so they don't provide a HTML variant.

As to clipping, anything added to the central area of a plot (cartesian frame) should clip. Previously it may not have, but that was a bug. However, we may consider adding finer control over clipping. I would suggest starting a new feature issue requesting this.
