### ISSUE TITLE
Mandatory 2FA 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9949]
In order to get Non-profit status under NumFocus and get a GH sponsor badge that deposits directly to the Bokeh project account, we will need to enable mandatory 2FA for the organization. This is a good thing to do anyway. 

cc @anthonydouc @Karel-van-de-Plassche @jburgy @StevenCHowell you are the only folks I dd not know how to reach outside GitHub. Please turn on 2FA when you can (or let me know if you no longer wish to be in a member). We will probably flip the switch in late April or Early May.

**Comment by Karel-van-de-Plassche** [comment]
Thanks, I have enabled 2FA
