### ISSUE TITLE
[BUG] Race condition between legend and glyph when using `legend_label`

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#9953]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.0.2-4-gea1f11fc4

#### Description of expected behavior and the observed behavior
Adding a glyph with a lot of data points breaks the plot in unexpected ways.
Note that if you don't see the described behavior, you can try changing the `100000` below to a higher number.
However, even with low values the behavior can be observed if you press the button more than once.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.layouts import row
from bokeh.models import Button, ColumnDataSource
from bokeh.plotting import curdoc, figure

p = figure()

src = ColumnDataSource(dict(x=list(range(100000))))
b = Button(label="Add line")


def add_line():
    p.line('x', 'x', source=src, legend_label=str(len(p.renderers)))


b.on_click(add_line)
curdoc().add_root(row(p, b))
```

#### Stack traceback and/or browser JavaScript console output
After pressing the "Add line" button, you can see this in the JS console:
```
Uncaught (in promise) TypeError: Cannot read property 'draw_legend' of undefined
    at LegendView._draw_legend_items (legend.js:226)
    at LegendView.render (legend.js:178)
    at PlotView._paint_levels (plot_canvas.js:843)
    at PlotView.paint (plot_canvas.js:825)
    at PlotView.repaint (plot_canvas.js:763)
    at plot_canvas.js:157
    at later (throttle.js:33)
```

**Comment by mattpap** [comment]
I suppose this is a side effect of adding `lazy_initialize`, during which rendering can happen with half initialized state.

**Comment by p-himik** [comment]
@mattpap Fortunately, this seems to not be the case - it's just a matter of ordering two closely related document patches. I keep thinking about consolidating multiple patches into one - surely it would solve and prevent all such problems automatically.
