### ISSUE TITLE
[FEATURE] varea_stack support in bokehjs

### ISSUE THREAD

**Issue by ashvin777** [bokeh/bokeh#9956]
The Python version of this library supports varea_stack, https://docs.bokeh.org/en/latest/docs/gallery/stacked_area.html, However the same method is not available in Bokehjs. Can we have support for this feature?

**Comment by bryevdv** [comment]
Some notes:

* Dev Guide for getting set up and running is [here](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html)

* At a minimum, a PR should also implement `harea_stack` at the same time. Ideally the PR would handle all the "stacked" glyph methods

* The relevant Python code is here:

   https://github.com/bokeh/bokeh/blob/23166fd9d8232decce0ce9219812e570e83d8412/bokeh/plotting/figure.py#L1252-L1255

  and the helper functions like `double_stack` are here:

  https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/_stack.py

* And the BokehJS file to add to is here:

    https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/api/plotting.ts
