### ISSUE TITLE
[BUG] Bokeh latest documentation warning 

### ISSUE THREAD

**Issue by ZviBaratz** [bokeh/bokeh#9957]
Hi,

It seems like there's a small bug with the docs:

![image](https://user-images.githubusercontent.com/22370149/80284280-4e46ef00-8726-11ea-861a-28db31748513.png)

As you can see, it is the latest version, but I still get the warning when I view the [Adding Widgets](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html) page.
I can't imagine it matters but I'm using Firefox on Linux.

**Comment by xavArtley** [comment]
use shift+F5 in your browser

**Comment by ZviBaratz** [comment]
Well that's embarrassing. Thank you and sorry.

**Comment by bryevdv** [comment]
Not embarrassing, it should not be required for users to force-reload. There an open issue to b use the caching of the version file here: #9952
