### ISSUE TITLE
[FEATURE] add a LineEditTool

### ISSUE THREAD

**Issue by scaine1** [bokeh/bokeh#9963]
I would like to have a **LineEditTool** for editing line glyphs, similar to the PolyEditTool.

For my specific need I have time-series data and I want to be able to edit the y-values only, leaving the x-values in place. 

I have had a go to see if I could create the tool, mainly to learn how bokeh works and to learn how to use JS/Typescript.

I created both what I will call **TimeSeries** mode where the x-axis values are frozen and a normal **LineEdit** mode where each point is free to move anywhere. 

If you think it would be worthwhile I would be more than happy to work on getting this feature included.

As mentioned above I am extremely new to TypeScript/JS. While I could get the code to work by looking at the PolyEditTool code,  I will likely need some help to make sure the code is up to scratch.

Attached are some gifs showing the results. 

The only difference between the two is that ```freeze_x=True``` is passed to the LineEditTool constructor on the second example

![line_edit_tool](https://user-images.githubusercontent.com/2906750/80563960-e814e180-8a2f-11ea-9963-6f5520f176b3.gif)

![timeseries_edit_tool](https://user-images.githubusercontent.com/2906750/80563936-da5f5c00-8a2f-11ea-8469-8940f81cc503.gif)

``` python
from bokeh.models import LineEditTool
from bokeh.plotting import figure, output_file, show
from bokeh.io import curdoc, show


p = figure(
    x_range=(0, 10), y_range=(0, 10), width=400, height=400, title="TimeSeries Edit Tool"
)

l1 = p.line(
    [1, 2, 3, 4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 4, 3, 2, 1],
    color="green",
    alpha=1.0,
    line_width=5,
)
l2 = p.line(
    [1, 2, 3, 4, 5, 6, 7, 8, 9],
    [8, 8, 8, 8, 8, 8, 8, 8, 8],
    color="blue",
    alpha=1.0,
    line_width=5,
)
c1 = p.circle([], [], size=10, color="red")

ledit_tool = LineEditTool(renderers=[l1, l2], intersection_renderer=c1, freeze_x=True)
p.add_tools(ledit_tool)

curdoc().add_root(p)
show(p)
```

**Comment by mattpap** [comment]
@scaine1, this looks pretty good. Submit your changes as a PR and we will start from there.

**Comment by scaine1** [comment]
Haven't done these PR's too many times so always a bit cautious when doing one.

I can see that the PR is going from my feature branch and into the bokeh/bokeh master branch.

![pr](https://user-images.githubusercontent.com/2906750/80599732-ba9b5880-8a6e-11ea-98aa-860d5fd35347.png)

Is this correct? I would have thought the code should stay on its own branch until it is all ready to go?

**Comment by bryevdv** [comment]
@scaine1 That is correct. A Pull Request is, first, just a request :) The code will stay on your branch until one a maintainer here presses the button to merge it. It looks like there are some conflicts, though. This can often happen if your fork is not up to date when you make the branch. I would suggest pulling the latest master branch in to your fork, and making a new branch with your changes for the PR. (You could also merge or rebase the up to date master in the current branch if you are comfortable doing that).
