### ISSUE TITLE
No examples of injecting data from python to low level custom js/html plot without any bokeh plots or inputs.

### ISSUE THREAD

**Issue by wolfiex** [bokeh/bokeh#9967]
I want to add a layer of direct interaction to a bank page into which data can be read/injected. I do not want any sliders or plots for the time being. There are no examples of such a basic usage of the bokeh server.

**Comment by bryevdv** [comment]
@wolfiex I have no idea *at all* what you are trying to accomplish from that description. Please post a (much) more detailed support question on the Disourse as a first step:

https://discourse.bokeh.org/

And if it seems like there's a good example to be added we can discuss a follow up issue.

**Comment by wolfiex** [comment]
I wish to inject (insert) js code to manipulate a new or already existing page (from the bokeh server). This page should be able to send or read data to/from the already existing page. 
DOM manipulation should be possible either directly or through d3 for a custom plotting tool, as opposed to the current wrapper functions. 

Basically I want to interact with the plethora of tools that already exist for manipulating items on a page and not be constrained by what has been baked into the python library. "direct interaction" could mean anything, which is exactly what I wish to be able to do. 

Three should be a way to add js to a page in realtime, and not only through callbacks when a bokeh element is interacted with.

**Comment by bryevdv** [comment]
@wolfiex I am afraid that sounds out of scope to me. Bokeh is, first and foremost, a library for interactive visualization. If you don't need Bokeh's vis capabilities, then I would say there's already a plethora of other tools for general web/app dev in python that we do not need to duplicate.

**Comment by wolfiex** [comment]
I wish to create an interactive visualisation, one whose complexity is far beyond the current limitations of bokeh. Unfortunately, the project I am working on is using Bokeh already. Since the library already interacts directly with the pages it creates, can those tools not be better documented and exposed to the user?

**Comment by bryevdv** [comment]
There is nothing to document. There is not currently any Bokeh API to inject arbitrary JS into pages. You are the first person to have asked for this in 8 years.
