### ISSUE TITLE
Direct bokeh - d3 interface. 

### ISSUE THREAD

**Issue by wolfiex** [bokeh/bokeh#9968]
Data-Driven Documents (d3) is a widely used library for manipulating visualisations to the users whim. Bokeh spawns a web server, which can run javascript, CSS and HTML. It then would be logical to be able to use the most heavily utilised library for visualisation on the web within bokeh itself. 

Proposal 
A plotting class (CustomD3) which contains a string stylesheet and a  section for javascript code to be executed (e.g. `run_d3(data input){ <code> ; return svg.node | canvas}` should be made available to build on the current selection of plots. 

For example, an issue such as node-links network graphs, which are trivial to implement and draw, was suggested as an addition in 2013 (#187) took 7 years to make it into the main plotting library 6f4115344e81fafbd7d3836b62ce31f5ef9b6782. Similar problems can be seen with closed issues suggesting converting a couple of lines into a custom bokeh extension - a task where adequate tutorial descriptions are missing from the documentation.

**Comment by bryevdv** [comment]
This is out of scope, and there is zero chance of this happening in the library proper. Bokeh renders primarily to HTML canvas and in the future may move to pure webgl rendering. D3 as a 'backend" is not a priority for us, at all. However, Bokeh is extensible. If you (or anyone) wants to create a custom extension that connects D3 to Bokeh models and data sources, then you could do that:

https://docs.bokeh.org/en/latest/docs/user_guide/extensions.html

However, the appropriate place to discuss usage questions is the project Discourse, not the issue tracker:

https://discourse.bokeh.org/

**Comment by philippjfr** [comment]
Feel free to submit a feature request on Panel (https://github.com/holoviz/panel), which builds in bokeh and aims to provide support for common visualization libraries.

**Comment by bryevdv** [comment]
Thanks @philippjfr I agree Panel is probably a much more reasonable place for a request like this

**Comment by bryevdv** [comment]
Also just to set the record straight: #187 did not take seven years to add, initial work on it was completed nearly four years ago. As to why it even took that long: while it is certainly easy to *draw* network graphs, the question at hand was how to cleanly integrate a data and selection model into Bokeh, which started out and until then had focused almost exclusively on handling columnar data.

**Comment by wolfiex** [comment]
Ah fair enough. I was going on the discrepancy between issue creation and
commit data of the bokeh plotting files - sorry.

Part of the reason I wanted a more direct approach to using js, is that
selection and manipulation of objects (especially within an SVG context -
something which could be manually implemented this way) are far more
straightforward, and the results could then be returned to bokeh for use
within different pages/scripts. I just find tasks as simple as writing text
along a user drawn path can prove difficult to implement within the current
framework.
