### ISSUE TITLE
Select widget un-focuses after selection

### ISSUE THREAD

**Issue by ahuang11** [bokeh/bokeh#9972]
**Is your feature request related to a problem? Please describe.**
Prior to integration of panel widgets in holoviews, a user could select a value and keep the select widget highlighted so that they could use the arrow keys to browse through each value, but now users have to manually select values with a pointer.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15331990/80729009-404df100-8acd-11ea-8ba9-0b3d3e3210ce.gif)

**Describe the solution you'd like**
To add a keyword that allows the select widget highlighted after selection

**Additional context**
If that wasn't clear, I want the blue highlighting to be retained after selecting a new value so I can use the arrow keys to continue browsing.
![image](https://user-images.githubusercontent.com/15331990/80729094-5e1b5600-8acd-11ea-8509-9f42415a4779.png)
The slider is capable of this already.
![image](https://user-images.githubusercontent.com/15331990/80729109-61aedd00-8acd-11ea-9194-e6e040c3faec.png)

https://github.com/holoviz/hvplot/issues/460

**Comment by bryevdv** [comment]
@philippjfr is that the Bokeh selection widget? I thought holoviews used its own select widget, in which this should be closed as `invalid`. 

In particular, the dropdown/select at https://demo.bokeh.org/movies is different from the one above and also does have the arrow key functionality working.

**Comment by philippjfr** [comment]
>I thought holoviews used its own select widget, in which this should be closed as invalid.

HoloViews widgets were rewritten on top of Panel, which is built on top of Panel, so those are indeed bokeh select widgets. As far as I can tell the example you pointed to has the same issue, once you've selected a new item the focus is lost.

**Comment by bryevdv** [comment]
OK I guess  am confused by 

>  could use the arrow keys to browse through each value, but now users have to manually select values with a pointer.

because I can definitely scroll through the list with arrow kieys, make a selection and then if the widget is activated again, I can scroll through again with arrow keys, starting at the previous selection. Is the issue that *activating* the widget at all requires a click? Or that making a selection collapses the the list? I am not sure what the ask is here.

**Comment by philippjfr** [comment]
The ask here is that after making a first selection the focus should stay on the widget, so that you can simply use the arrow keys to open the dropdown again and select a new value without having to click to put the widget in focus each time.

**Comment by ahuang11** [comment]
"Is the issue that activating the widget at all requires a click?" No, I want the widget to stay activated after making a selection.

**Comment by bryevdv** [comment]
Interestingly enough, if you keep making the *same* selection, the focus does remain, and the menu can be continually re-activated with an arrow down. It starts to lose focus once a new value is selected.

**Comment by philippjfr** [comment]
>It starts to lose focus once a new value is selected.

Guessing selecting a new value triggers a rerender.

**Comment by bryevdv** [comment]
Yes that is the most likely explanation. I'm not sure what simple solution there would be. Offhand I think we might have to keep track globally of a "currently focused" widget and restore that after renders. But that seems potentially fragile If there's a simpler idea I'd love to hear it.

**Comment by philippjfr** [comment]
That's one option, another would be to replace the general change event:
```
    this.connect(this.model.change, () => this.render())
```

with separate events and the `value` update event would not trigger a full rerender and just mark the new `value` as selected.

**Comment by bryevdv** [comment]
tentatively marking for 2.1 also marking as `task` since I'm not sure we ever promised this would be the behavior. If this can be put under an integration test that would be ideal

**Comment by mattpap** [comment]
>  `this.connect(this.model.change, () => this.render())`

It's cheap to implement this way, but the result is lost focus, bad performance and perhaps other side effects.

**Comment by philippjfr** [comment]
Right, maybe we should review other widgets too and see if we should implement granular change events for those as well.
