### ISSUE TITLE
[BUG] Cannot apply patch to [id] which is not in the document anymore

### ISSUE THREAD

**Issue by Dr-Nuke** [bokeh/bokeh#9978]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.0.0 py37_0
python 3.7.7 hcf32534_0_cpython
WSL Ubuntu 18.04 (hosted on win10
Firefox 75.0 (64-bit)
running the app with command` bokeh serve testapp.py --dev`
#### Description of expected behavior and the observed behavior
in reply to https://github.com/bokeh/bokeh/issues/7738#issuecomment-605670765, I open this new issue:

On updating the layout, the errors
```
2020-05-01 10:43:42,474 Cannot apply patch to 1606 which is not in the document anymore
2020-05-01 10:43:42,475 Cannot apply patch to 1606 which is not in the document anymore
2020-05-01 10:43:42,477 Cannot apply patch to 1606 which is not in the document anymore
2020-05-01 10:43:42,478 Cannot apply patch to 1606 which is not in the document anymore
```
are thrown, where the timestamp and id number change accordingly. **The Webapp however runs unaffected of these messages.**

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import bokeh.io as io
import bokeh.models as mod
import bokeh.layouts as bly
import datetime as dt
from bokeh.plotting import figure

# Set up plots
def MyPlots():
    # make 2 simple plots
    x = np.linspace(0, 15, 200)
    y = np.sin(x)
    plot1 = figure(plot_height=400, plot_width=400, title=str(np.random.normal()))
    plot1.line(x, y,  line_width=3, line_alpha=0.6)

    plot2 = figure(plot_height=400, plot_width=400, title=str(np.random.normal()))
    plot2.line(x, y,  line_width=3, line_alpha=0.6)
    
    return [plot1,plot2]

p1,p2= MyPlots()

# make an input
buttons = mod.RadioButtonGroup( 
    labels=['One', 'Two'])

# callback
def update(attr, old, new):
    pl1,pl2=MyPlots()
    rev.children[0] = pl1
    rev.children[2] = pl2

buttons.on_change('active', update)

# Set up layouts and add to document
rev=bly.column(p1, buttons, p2)
io.curdoc().add_root(rev)

```

#### Stack traceback and/or browser JavaScript console output
no error traceback

**Comment by bryevdv** [comment]
@bokeh/dev I propose we simply lower this from `log.warning` to `log.debug` (or even `log.trace`) with a slightly tweaked message. AFAICT there is basically only one situation that triggers this message, and in that situation ignoring the changes for the already-removed models is just the correct thing to do.

**Comment by philippjfr** [comment]
That would be great, +1 from me.

**Comment by bryevdv** [comment]
This is a one line change so I have marked GFI. The line is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/document/document.py#L406

But it should be done for 2.1 even if no one new picks it up.

**Comment by naveensaigit** [comment]
I'm willing to work on this issue. What do you want the new message to be?

**Comment by bryevdv** [comment]
@naveensaigit great! To be honest the main this is that the log level should be lowered to `debug` or `trace`. The current message is probably OK as is, or you could add "(this is usually harmless)" or similar to the end of it.

**Comment by naveensaigit** [comment]
@bryevdv Ok, I'll change this and make a PR

**Comment by ascoril** [comment]
i have version 2.0.2 and my client is reluctant to change this version. Is there anyway available to suppress this warning

import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

is not working

**Comment by bryevdv** [comment]
It's a log message, not a warning call. You'll have to grab the logger and configure that (I don't know the details)
