### ISSUE TITLE
BokehJS User Guide section not using SRI hashes

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9982]
e.g. 
```
./html/docs/user_guide/bokehjs.html:
  392 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.0.2.min.js"></script>
  393 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.0.2.min.js"></script>
  394 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.0.2.min.js"></script>
  395 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-gl-2.0.2.min.js"></script>
  396 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.0.2.min.js"></script>
  397 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.0.2.min.js"></script>
  413 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.0.2.min.js"></script>
  414 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.0.2.min.js"></script>
  415 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.0.2.min.js"></script>
  416 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-gl-2.0.2.min.js"></script>
  417 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.0.2.min.js"></script>
  418 : <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.0.2.min.js"></script>
```

Ideally we might want to add some sort of check if possible that ensures we don't ever load BokehJS without including the SRI hashes.

**Comment by MagnumDingusEdu** [comment]
@bryevdv I would like to work on this

**Comment by MagnumDingusEdu** [comment]
@bryevdv I would like to work on this.

**Comment by bryevdv** [comment]
@MagnumDingusEdu That would be fantastic. First I just want to make sure the nature of the task is clear. This is mostly a coding task, to up date our `:bokehjs-content:` Sphinx directive:

https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokehjs_content.py

I'm happy to elaborate on the details of what it will take to update this automation but first please confirm that this is the sort of task you were looking for.

**Comment by MagnumDingusEdu** [comment]
@bryevdv  I was looking to familiarize myself with the documentation, for Google Season of Docs, and thought this was a good opportunity. But now that you mention it, it doesn't really come under technical writing, and is mostly a coding task. I'll explore other areas if that's okay.

**Comment by santos22** [comment]
I can take a look at this! I was able to build the docs locally and am looking at the `Resources` class for more clues.
