### ISSUE TITLE
[BUG] TextInput.on_change() doesn’t work on Microsoft Edge

### ISSUE THREAD

**Issue by jpvnunes** [bokeh/bokeh#9985]
As I run the sliders [https://github.com/bokeh/bokeh/blob/master/examples/app/sliders.py](url) script on a Bokeh server, the TextInput.on_change() doesn’t work when running on Microsoft Edge. I tried it on Chrome and it works.

For your reference: I am running Bokeh 2.0.1 on Anaconda, python version 3.7.4. on Windows 10 64-bit. I created the server via the following command:

```
bokeh serve sliders.py

```

**Comment by bryevdv** [comment]
@jpvnunes can you confirm that you are using old (non-chromium) Edge 44.x?

**Comment by bryevdv** [comment]
Have not really been able to make any headway on this. If you click the little ms-specific "clear" X and then tab focus, the event callback *does* fire. And I can also step over the `render` function to see the callback be added and also that there is not excessive re-rendering. But the event does not fire when enter is pressed. Or tab focus change or a variety of other attempts. I haven't located any reported bugs with edge and text input cahnge event tho so I am a bit stumped.

**Comment by mattpap** [comment]
Old Edge is not supported since bokeh 3.0.
