### ISSUE TITLE
[BUG] Dynamic use of bokeh.plotting glyph method breaks the plot render in browser

### ISSUE THREAD

**Issue by sfosset** [bokeh/bokeh#9988]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh info:
Python version      :  3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
IPython version     :  7.13.0
Tornado version     :  6.0.4
Bokeh version       :  2.0.0
node.js version     :  v12.16.1
npm version         :  6.13.4

Windows 10
Bug reproduced in:
Jupyter Notebook 2.0.1
Firefox 75.0
Edge 44.18362.449.0

#### Description of expected behavior and the observed behavior
Context: serving a bokeh app with the bokeh server, using python callbacks

Expected:
The checkbox widgets are linked to a python callback method that uses circle() to add a new series to the plot. It only creates the glyphrenderer via circle() on the first click, then it uses the visible property of the renderer to toggle the visibility.

Observed:
On the first click on a checkbox two cases can happen where the bug is not consistently triggered.

First case: on the first click, the plot is not correctly rendered. The axis label disappears and won't reappear on any further clicks on this checkbox. On Firefox, an error message shows up in the javascript console (see after)

Second case: on the first click the plot is correctly rendered. Then, on further clicks on the same checkbox, the show/hide behavior works as expected, and the bug seems to never trigger. A first click on another checkbox can trigger the bug though.

Additional observation:
When the legend_label parameter is not set, the bug seems to never trigger.

#### Complete, minimal, self-contained example code that reproduces the issue

```Python
import math
from bokeh.plotting import figure, curdoc
from bokeh import layouts
from bokeh.models import CheckboxGroup
from bokeh.io import output_notebook, show
from bokeh.models import ColumnDataSource

sources = {}

for i in range(10):
    sources['source{}'.format(i)] = ColumnDataSource(data=dict(
        x=[k for k in range(100)],
        y=[math.sin(k+(i*0.314)) for k in range(100)],
    ))

"""Initialize plot"""
p1 = figure(plot_width=900, plot_height=600)
p1.circle('x', 'y', size=10, color="navy", source=sources['source0'], name="source0")

"""Add TM option widget"""
checkbox_group_srcs = CheckboxGroup(labels=list(sources.keys()), active=[0])
    
def update_plot_series(attr, old, new):        
    change_type = len(new)-len(old)
    changed_source = checkbox_group_srcs.labels[list(set(old).symmetric_difference(set(new)))[0]]
    changed_renderer = p1.select(name = changed_source)

    if change_type==-1:
        changed_renderer.visible = False
    elif change_type==1:
        if changed_renderer:
            changed_renderer[0].visible = True
        else:
            p1.circle('x', 'y', size=10, color="navy", source=sources[changed_source], legend_label=changed_source, name=changed_source)
    
checkbox_group_srcs.on_change("active", update_plot_series)
    
out_layout = layouts.layout(
    [[p1,checkbox_group_srcs]])
curdoc().add_root(out_layout)
```

#### Stack traceback and/or browser JavaScript console output
Firefox Javascript console log

```

TypeError: this.plot_view.renderer_views[e.id] is undefined bokeh.min.js:289:4632
    _draw_legend_items http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:289
    render http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:289
    _paint_levels http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:455
    paint http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:455
    repaint http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:455
    connect_signals http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:455
    connect http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:219
    emit http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:162
    emit http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:162
    throttled_paint http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:455
    u http://localhost:5006/static/js/bokeh.min.js?v=545398055367f7e60a67590a85ade60b:474

```

#### Screenshots or screencasts of the bug in action
In the following example, the bug did not trigger when click source1, but triggered when clicking source2

![before](https://user-images.githubusercontent.com/9079710/81107221-1d7d6b80-8f17-11ea-874d-35c2ab9357e7.PNG)
![after](https://user-images.githubusercontent.com/9079710/81107225-1eae9880-8f17-11ea-8344-0cb1f55a1c7a.PNG)

**Comment by bryevdv** [comment]
@sfosset I think if you are going to dynamically add glyphs you will have to manage your `Legend` and `LegendItem` objects manually as well. The `legend_label` machinery is a convenience for that but I guess I am not especially surprised it does not work with this kind of usage, and I am not not sure it can be made to, either (in which case that should be documented better).

Definitely worth some investigation, however I will also state that I think the best advice is simply not to add glyphs dynamically at all. It would be simpler to add all the glyphs up front, and then use the callback to merely toggle their visibility.

**Comment by sfosset** [comment]
Thanks for the advice on dealing with glyph dynamically, it is indeed working much better this way.

I initially wanted to do it this way because I have a large set of data to be made available to the user, but the user will be interested only in small chunk of it to show on the plot at a single time (telemetry time series exploration and report). This way I wanted to avoid having all the data loaded upfront, and rather have it downloaded one useful piece at a time. After investigating a bit it turns out that it doesn't make sense to do that kind of things with this approach in bokeh.
Taking the example above with 10 000 points for each source. With the pre-loaded method, it gives 2.5 MB upfront, and virtually nothing for each click. With the dynamically loaded method, upfront is only 300kB, but each new "first click" will actually take more and more data (>1MB) It seems that it's reloading the complete plot with each click.
Fair enough. For my application it turns out that the upfront load is still acceptable. If it grows bigger, I'll have to use a different approach, maybe outside of bokeh.

Regarding the legend management, I handle them manually, but use the LegendItem generated automatically by the glyph method. I retrieve them based on the attached glyph. It could also work looking at the label if it is a good identifier. It's not pretty and not very safe but it works.

```python
    legenditems = dict()

    def get_one_legend_item(p, renderer):
        for li in p.legend.items:
            if li.renderers[0]==renderer:
                return li

    p1.circle('x', 'y', size=10, color="navy", source=sources["source0"], name="source0", legend_label="source0")

    legenditems["source0"] = get_one_legend_item(p1, p1.select(name = "source0")[0])

    #Remove all legends
    p1.legend.items = []
    #Toggle legend visibility
    #on
    p1.legend.items.append(legenditems["source0"])
    #off
    p1.legend.items.remove(legenditems["source0"])
    
```
Suggestion: a .visible property on LegendItem would be incredibly handy

By the way, a big thank to you (and to all the contributors behind the project) for your work, bokeh is an amazing library :)

**Comment by tcmetzger** [comment]
Hey @sfosset, sorry this issue hasn't seen any action for so long. Since you seem to have found a workable solution based 
on @bryevdv's comment, I'll go ahead and close this issue. 
If you still see a need for a `visibility` feature, please start a [discussion](https://github.com/bokeh/bokeh/discussions) or a [fature request](https://github.com/bokeh/bokeh/issues/new/choose). Thank you!
