### ISSUE TITLE
[BUG] Elaborate on how the margin attribute works in documentation

### ISSUE THREAD

**Issue by chrisjdixon** [bokeh/bokeh#9990]
When trying to adjust a margin the [documentation for the margin attribute](https://docs.bokeh.org/en/latest/docs/reference/models/layouts.html?highlight=margin#bokeh.models.layouts.Tabs.margin) didn't tell me everything I wanted to know. It took longer than I care to admit to figure out how it works and I think it'd help others if the documentation for margin explained:

- the ints in the tuple start at the top and go clockwise: top, right, bottom, left
- negative values can squeeze things together more tightly if desired

**Comment by bryevdv** [comment]
Hi @chrisjdixon That helps string coudl certainly use some elaboration. AFAIK the sense of "margin" here matches the standard CSS sense of "margin", but at a minimum we should link to something the w3schools reference for margin:

https://www.w3schools.com/Css/css_margin.asp

And possibly add some of our own explanation inline as well. 

We have applied to Google Summer of Docs so with any luck we might get someone to take on the project of reviewing/expanding all of the property helpstrings. However would you like to submit a Pull Request to update this specific one in the mean time? The relevant code section is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/layouts.py#L117

**Comment by ashwani-rathee** [comment]
Hey @bryevdv ,I saw the updates by @naveensaigit...is this issue still open??
