### ISSUE TITLE
[BUG] Select widget hiding tabs, when selecting a plot

### ISSUE THREAD

**Issue by tretaki** [bokeh/bokeh#9992]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh: 2.0.2
python: 3.8.2
OS: Linux 4.19.118-1-MANJARO
browser: Firefox 75.0, Brave 1.7.98 Chromium: 81.0.4044.113 (Official Build)

#### Description of expected behavior and the observed behavior

Context: Select widget menu is implemented to show a selected plot via a custom JS callback. The plot to show is implemented in the tabs, which show either linear o

Expected: When selecting the plot to be displayed the tabs should be visible.

Observed: When selecting the plots, while going down the selector, the tabs and radio buttons are hidden. Therefore one cannot choose the desired tab.

#### Complete, minimal, self-contained example code that reproduces the issue

```py
import numpy as np
from bokeh.layouts import column
from bokeh.plotting import figure, output_file, save
from bokeh.models import ColumnDataSource, Tabs, Panel, Select, CustomJS

output_file("selector.html")


def create_figure(x, y, logscale=False):
    source = ColumnDataSource(data=dict(x=x, y=y))
    if logscale:
        fig = figure(y_axis_type="log")
    else:
        fig = figure()

    fig.line("x", "y", source=source, line_width=3, line_alpha=0.6)

    return fig


def create_lin_log_tabs(tab1, tab2, name=None):
    """ Create linar and logarithmic tabs from two plots.
    """

    tab1 = Panel(child=tab1, title="Linear")
    tab2 = Panel(child=tab2, title="Logarithmic")

    return Tabs(tabs=[tab1, tab2], name=name)


def create_selector(figs, title="Select Curve"):
    names = [fig.name for fig in figs]
    selector = Select(title=title, value=names[0], options=names, width=200)

    for fig in figs[1:]:
        fig.visible = False

    callback = CustomJS(
        args=dict(figs=figs),
        code="""
        let selected = cb_obj.value;
        for(let fig of figs){
            fig.visible = fig.name == selected;
        }
    """,
    )

    selector.js_on_change("value", callback)

    return [selector] + figs


x = np.linspace(0, 10)


fig_lin_lin = create_figure(x, x)
fig_lin_log = create_figure(x, x, logscale=True)
fig_lin = create_lin_log_tabs(fig_lin_lin, fig_lin_log, name="Linear")

fig_quad_lin = create_figure(x, x ** 2)
fig_quad_log = create_figure(x, x ** 2, logscale=True)
fig_quad = create_lin_log_tabs(fig_quad_lin, fig_quad_log, name="Quadratic")

fig_exp_lin = create_figure(x, np.exp(x))
fig_exp_log = create_figure(x, np.exp(x), logscale=True)
fig_exp = create_lin_log_tabs(fig_exp_lin, fig_exp_log, name="Exponential")


figs = [fig_lin, fig_quad, fig_exp]

selector = column(create_selector(figs))

save(selector)
```

#### Other Comments
The tabs get hidden if we go down the selector menu, if we go up then the tabs get visible. As shown in the screenshots below.

If figures are not put into columns, then the behavior is as expected.
```selector =  create_selector(figs)```

Similar problem exists if one uses radio button groups to implement the tabs. In that case we can avoid the problem by setting the height of the radio buttons. If this parameter is not explicitly set, then half of the buttons get hidden when one selects the plot, see the gif below.

#### Screenshots or screencasts of the bug in action
Example with tabs:
![bokeh_selector1](https://user-images.githubusercontent.com/38312200/81195451-1f4e3a00-8fbe-11ea-8909-5876dd312326.gif)

Example with radio button group:
![bokeh_selector2](https://user-images.githubusercontent.com/38312200/81195579-53295f80-8fbe-11ea-9446-33c249ca0c8c.gif)

**Comment by nbw-iii** [comment]
Just a note on the second example showing the radio button issue. This can be worked around if the height of the radio button is explicitly set and the height_policy is 'fixed'.  On another note.  Thanks for bokeh, its awesome.

n
